### ISSUE TITLE
Crashes on pause and hibernate with MFHU

### ISSUE THREAD

**Issue by tilkinsc** [hrydgard/ppsspp#10009]
Crashes on pause and windows 7 hibernate on game Monster Hunter Freedom Unite

(ppsspp v1.4.2-354)

**Comment by hrydgard** [comment]
Regarding the hibernation crash, can you try switching the audio backend to DirectSound?

**Comment by Hydroque** [comment]
I turned it from auto to DSound, hibrinated and turned pc on, signed in, pressed emulation -> resume, it let me run around without sound for a whole 3 seconds before crashing my driver and then popping up PPSSPP has stopped working APPCRASH and PPSSPPWindows64.exe is the fault module.

**Comment by unknownbrackets** [comment]
I wonder if we should do the "lost" and "restore" on Windows based on WM_POWERBROADCAST, e.g. on PBT_APMSUSPEND and PBT_APMRESUMEAUTOMATIC (though maybe we do actually want to delete GL objects/etc. in case they are preserved...)

-[Unknown]

**Comment by hrydgard** [comment]
yeah in Windows we definitely do want to delete the GL objects properly, it's just Android that has this weird object-killing behaviour.

But do we know this crash has anything to do with graphics? Since it came back without sound, maybe that's the only thing we need to reinit in this case...

**Comment by tilkinsc** [comment]
Note that may be related to my other crash problem with hibernation

**Comment by unknownbrackets** [comment]
I know we made some changes to detect device connection adjustments.  Has this improved?

-[Unknown]

**Comment by tilkinsc** [comment]
I have no tested it, as I am now on Windows 10. Windows 7 had a lot of weird buggy natures with hibernations, where the restored state was errornous
