### ISSUE TITLE
Broken Gran Turismo in latest snapshots

### ISSUE THREAD

**Issue by iArti** [hrydgard/ppsspp#10005]
In all game font is broken, it just shows random letters every frame
Also, the game is blinking
In early snapshots (1.4.2.-6x) everything was alright

**Comment by hrydgard** [comment]
You don't happen to be trying out the Vulkan backend, are you? That one still has some issues and is to be considered experimental. In particular I know it has this issue :)

**Comment by iArti** [comment]
Yes, I am using Vulkan
And when I'm trying to switch to OpenGL, PPSSPP force closes without saving settings
Have I to open another issue?
How can I change backend through .ini file?

**Comment by hrydgard** [comment]
Open memstick/PSP/SYSTEM/ppsspp.ini and set GPUBackend to 0.

I'm surprised it's crashing without saving though, that shouldn't happen...  Are you on Android or PC?

**Comment by iArti** [comment]
I'm using Android 7.1.2 on Xiaomi Mi Max 
I'm sorry, that I haven't said it yet
Do you need crash logs?

**Comment by hrydgard** [comment]
If you can get logcat logs that show the SIGSEGV or whichever exception, and paste it here or make a gist, that would be great. I'm gonna investigate on my Nexus 5X too and see if it has the same problem switching backends.

**Comment by hrydgard** [comment]
Submitted a possible fix for the crash during backend switching, and a safety measure that saves the setting immediately.

Please try when the new build arrives on https://buildbot.orphis.net/ppsspp/ .

**Comment by iArti** [comment]
Updated to the latest snapshot and now it saves GPU backend but still force closes

**Comment by hrydgard** [comment]
Okay, well I guess that's progress. Doesn't force close on my phone...

**Comment by hrydgard** [comment]
This should work better now but there are still some issues..

**Comment by iArti** [comment]
Installed -563 build, still facing this problem, unfortunately

**Comment by Intuki** [comment]
If this can help I tried to track down first build with the regression.

v1.4.2-359-g4e2726f54: there is no this issue with Vulkan on Android
v1.4.2-360-ged776d8c0: no build
v1.4.2-361-gb9b2656e9: fonts and screen flicker in most situations (changelog has Vulkan optimizations)

**Comment by hrydgard** [comment]
This should actually be fixed now, but the buildbot is still broken. Hopefully @Orphis will have time to bring it up again soon.

**Comment by Intuki** [comment]
I just tried the build "v1.4.2-663-g70c70b1e7", it's fixed.
Thank you!
