### ISSUE TITLE
Colin McRae Rally : 2005 Plus black sky with Vulkan API

### ISSUE THREAD

**Issue by righN** [hrydgard/ppsspp#10011]

**Comment by Michal1324** [comment]
Some stuff isn't implemented yet.

**Comment by hrydgard** [comment]
How about now @righN?

**Comment by ppmeis** [comment]
Tested with latest Windows build. All backends have the same issues, but sky seems to be fine:
Sun has a black square, blinking shadows, and some textures have a red square.

Default settings, OpenGL (only two screenshots in this backend to show blinking shadows, but it happens in all backends):
![image](https://user-images.githubusercontent.com/4381277/33524698-ed5dcd40-d821-11e7-8d03-de0b11f402ac.png)
![image](https://user-images.githubusercontent.com/4381277/33524699-f6d87c30-d821-11e7-9409-ab9c72ce8e12.png)

Default settings, Direct3D9 complete black sun and there are no shadows. Also there is like a flickering in overall image:
![image](https://user-images.githubusercontent.com/4381277/33524722-51edad84-d822-11e7-8035-35d13d99f2f0.png)

Default settings, Direct3D11:
![image](https://user-images.githubusercontent.com/4381277/33524738-a3b0e208-d822-11e7-98c0-a243d078ac4f.png)

Default settings, Vulkan. Same issues but also with critical errors
![image](https://user-images.githubusercontent.com/4381277/33524759-e64e088e-d822-11e7-8d2e-209a1575df72.png)
![image](https://user-images.githubusercontent.com/4381277/33524760-eb5d5096-d822-11e7-91ee-4255d4d92523.png)
after click yes button:
![image](https://user-images.githubusercontent.com/4381277/33524764-f833a32e-d822-11e7-8137-c7bb9682d05c.png)
then, emulator stops working.

**Comment by ppmeis** [comment]
Some issues in this game was mentioned at #7810

**Comment by hrydgard** [comment]
Yeah, the sky seems to no longer be black at least, so let's bundle up remaining issues with this game in #7810.
