### ISSUE TITLE
Input with x360 Wireless Controler not working on PI3 : here the solution

### ISSUE THREAD

**Issue by Darknior** [hrydgard/ppsspp#10019]
Hi

I already ask for it and no one give me a solution, but the DPad is not working fine on PPSSPP on RPI3.
I have found it and ask you if you can add it to the source code for every one .

On the **assets/gamecontrollerdb.txt**
We have drivers for **X360 Controller** and **X360 Wireless Controller**
And i don't know why, but we must use the one for **Xbox 360 Wireless Receiver** where we connect the 4 controlers.
I give it to you here, if you add it, all is working fine 100% :)

`030000005e040000a102000000010000,Xbox 360 Wireless Receiver,b:b1,righty:a3,rightx:a2,a:b0,x:b2,righttrigger:b7,rightstick:b12,leftshoulder:b4,dpup:b15,start:b9,dpdown:b16,rightshoulder:b5,dpright:b14,lefttrigger:b6,leftstick:b11,guide:b8,y:b3,lefty:a1,leftx:a0,back:b8,dpleft:b13,platform:Linux,`

Thanks

**Comment by hrydgard** [comment]
Thanks. Blind committed a fix in f6bf1d5d7cda4c094441ae00edcba7faa51a48a5  (without testing :)
