### ISSUE TITLE
God of War : Ghost of Sparta crashing/flickering with Vulkan

### ISSUE THREAD

**Issue by righN** [hrydgard/ppsspp#10010]
Hi, so there's a strange problem when playing GoW: Ghost of Sparta with Vulkan API. So, sometimes textures flicker and somehow it drops fps because of that or you're just playing and PPSSPP app just crashes. I'm on latest PPSSPP Android development.

**Comment by animania260** [comment]
I can report the same. However I wasn't sure if Vulkan (at least on Android) was in a playable state for any games quite yet, as I haven't tried Vulkan with anything else. Sometimes the app just crashes when set to use Vulkan before even trying to load a game. But I think that has mostly been resolved with the last Vulkan update around a week ago far as I've seen. But PPSSPP does crash when trying to play GoW.

**Comment by animania260** [comment]
My device does actually support Vulkan just FYI (though not full featured. Alot of extensions aren't supported. Though Qualcomm claims this chip was "designed with the Vulkan API in mind" (paraphrasing). My ass.). Anyway I can provide more information if needed. I'm fairly sure the devs are already aware of this though.

**Comment by hrydgard** [comment]
We might have some obscure bug somewhere that doesn't show up on PC for whatever reason, might be timing (PCs are drastically faster and nVidia drivers are so much faster again than Qualcomm or Mali drivers, even with Vulkan...). Not certain to be driver bugs.

**Comment by animania260** [comment]
Right. I wish Nvidia would release an updated Android X1 tablet model or Google or some manufacturer that would actually support the device for at least two years. I think Nvidia did pretty good supporting their Shield, and Shield K1 tablets for a while, and continuing to support the Shield TV. Hopefully Android 0 with Project Treble will end up improving graphics driver compatibility and support in the future as well.

Anyway thanks for the quick reply and thanks for all of yall's work on this great emulator. :-)

**Comment by hrydgard** [comment]
This might be improved now, please try again.

**Comment by Sunil2735** [comment]
It's has become more buggy 😬

**Comment by hrydgard** [comment]
@Sunil2735 in what way? Please provide screenshots or at least descriptions. Tried playing one of the games for a bit and it seemed to work fine, on PC at least.

**Comment by Sunil2735** [comment]
Sorry for that... It is now much better but the issue still exist... On my windows 10 hp  it works great but on my Lenovo p2  sometimes the frame drops and it slutter...  How can I send a video to you?

**Comment by Sunil2735** [comment]
I will send video in few minutes

**Comment by Sunil2735** [comment]
[videocompress-042-20171114_061425.zip](https://github.com/hrydgard/ppsspp/files/1469176/videocompress-042-20171114_061425.zip)

**Comment by Sunil2735** [comment]
Please rename the file to .mp4

**Comment by hrydgard** [comment]
Sure there are a few stutters and framedrops but the graphics look correct, as far as I can tell. There are more optimizations left to do, but currently you simply need more powerful hardware to make it really smooth. We can't have separate issues for every game that doesn't run fast enough on a specific device, that's unmanagable.
