### ISSUE TITLE
Gods Eater Burst Cant Load Data on Latest Build

### ISSUE THREAD

**Issue by TediExcaliber** [hrydgard/ppsspp#10020]
Help, i cant load my GEB savedata, the screen is freezing on select slot data and cant load data! Here image https://m.imgur.com/pvqjlVl

Before this iam using build 474 and now iam using build 502, and the problem is happen at both version, idunno what version is start this bug.

Before this, at #10004 is report the same problem but different a bit but but, the problem is same, cant load data, at #10004 is using the JP ver, and Me using the US ver, and i think this problem is happen at EU ver too..

Please fix this bug.

Ps: sorry 4 my bad english :)

**Comment by TediExcaliber** [comment]
UPDATE: This problem also happen when saving/creating new savedata too

**Comment by unknownbrackets** [comment]
What's the last git build that worked?

IIRC, this game requires proper rounding.  Still works on x86.

-[Unknown]

**Comment by TediExcaliber** [comment]
At #10004 he say, Last work: v1.4.2-359-g4e2726f54. First break:
v1.4.2-361-gb9b2656e9.

Pada tanggal 19 Okt 2017 10.32 AM, "Unknown W. Brackets" <
notifications@github.com> menulis:

**Comment by TediExcaliber** [comment]
Update: now iam using latest build 523, and the bug still here.

When changing the cpu core to Interpreter, I can go into select savedata (not freezing) but when I press X to load data, the screen is going back into main menu, when i trying to savestate it the ppsspp is Stop working (force close) and savestate data is not save.

When changing to IR Interpreter, the game is crash when in title screen.

**Comment by vsub** [comment]
By looking at the size of the screenshot and the touch buttons,you are probably talking about the android version of ppsspp
At least on the windows version it works fine here on the latest beta and on one little older version

**Comment by hrydgard** [comment]
So it's https://github.com/hrydgard/ppsspp/commit/b9b2656e93133ed781e082005c6cc5311c756c13#diff-fc05b6629e71f8ecba4c02d7ce371d30L132 or https://github.com/hrydgard/ppsspp/commit/ed776d8c0bff2233ccd23f6c6a1bc00273c016c7 .

Highly doubt it's the latter as that one would never trigger. So I'm gonna try reverting the first.

**Comment by hrydgard** [comment]
@TediExcaliber  Can you try this again with a newer build? Any from the past couple of days.

**Comment by TediExcaliber** [comment]
The bug is still here (786), and oh right, this bug also happen on SSX On
Tour when want to load data

Pada tanggal 14 Nov 2017 6.44 PM, "Henrik Rydgård" <notifications@github.com>
menulis:

**Comment by TediExcaliber** [comment]
Last Update:

Now Iam using 803 and bug still here, then i trying to backup my savedata and make a new one... Then what happen? Idunno what happen but I CAN LOAD my new savedata, then ill try to place back my savedata, and the result is still cant load...

So here i make conclusion, the newer PPSSPP is not accordance with Old GEB savedata *(i name it old cuz ill make my old savedata on ppsspp v1.3)*

So now its can be considered finished right?

Additional how to get back my old GEB savedata:

First ill install the older ppsspp build *(listed 668 but when install it list 663 maybe a typo, on this build i can load my old savedata, after this build i cant load my savedata again)*, then load my old savedata, after load ill savestate it, and delete my old savedata, then i make a new one, after that, i load the savestate and save my old savedata again in the new savedata... Then ill try to load again, and success :)

**Comment by hrydgard** [comment]
I think this is a result of the CPU rounding mode bugfixes that @unknownbrackets mentioned. As long as there's a workaround like that, and you can now load and save properly, there's not really much else we can do that makes sense. I'm closing.
