### ISSUE TITLE
Tactics Ogre crashes at a certain point (Android, using most recent build on Play Store)

### ISSUE THREAD

**Issue by NocturneN5** [hrydgard/ppsspp#10023]
I have the exact same issue as posted in this thread:
https://github.com/hrydgard/ppsspp/issues/9488

And it will crash on the exact same point as the user who posted on that thread. Disabling fastmem didn't work either. Though unlike that other user, I've experienced no "endless loading screen", it will just crash at that certain point, fastmem or no.

Definitely not an ISO issue as I once played this ISO about 2+ years ago, using an older version of PPSSPP, and it worked just fine. Problems began to arise when I recently updated my PPSSPP.

Any help will be appreciated. For now, I'll try installing an older version of PPSSPP and see if it'll get past that certain point.

UPDATE: I'm now using PPSSPP version 1.1.1, and it works like a charm. No crashes on that point in the game. For now I'll stick to using this version, and refrain from updating.

UPDATE 2: I've done some more testing and I figured out what's wrong. It has nothing to do with the PPSSPP versions, but rather, the SAVEDATA folder inside the PSP folder. For some reason, if I have save files in that folder, and then play a new game up to the certain point, it will crash. But if the SAVEDATA folder has nothing in it, I can proceed past that point in the game. Not sure what's going on exactly, but I hope this information helps you, Henrik. Here's hoping you can fix this.

**Comment by hrydgard** [comment]
Wait so any files inside SAVEDATA will make it crash? What about directories?

(For reference, the point where it is reported to crash in the other issue is "Well, its very early. In the beginning, it shows you how the battle system works. After that its a small cut scene. After the cut scene, that's when it crashes".)

**Comment by ResurrectionRedmi9** [comment]
This is still an issue?

**Comment by hrydgard** [comment]
I don't think we're likely to investigate this if it doesn't come up again. Closing.
