### ISSUE TITLE
PPSSPP AND JAR TOUCH SCREEN GAME

### ISSUE THREAD

**Issue by skelletR** [hrydgard/ppsspp#10027]
I have a question.. In ppsspp  I can  play old jar games with emulator but some jar games is touch screen and the ppsspp gold can put touch in emulator? Can anyone make it this possible to play an touch screen jar games inside in emulator in PSPKVM?

**Comment by LunaMoo** [comment]
No. PSP didn't have it, so emulators written for it will never be able to support touchscreen.

 Also PSPKVM is not related to PPSSPP in any way, so this is really no place to ask about it's possible developement. Closing.
