### ISSUE TITLE
Missing text on Duel Bonus screen in Yu-Gi-Oh! 5D's Tag Force 5.

### ISSUE THREAD

**Issue by NaturalHarmonia** [hrydgard/ppsspp#10030]
This also happens in Tag Force Special.

There's an image in this post here: http://forums.ppsspp.org/showthread.php?tid=2091&pid=89442#pid89442

**Comment by unknownbrackets** [comment]
This is probably a duplicate of #2788.  Does it happen with original PSP fonts (you'll need to have a PSP to get them)?

-[Unknown]

**Comment by unknownbrackets** [comment]
I'm going to close assuming that it's a duplicate - if not, please reply with more detail.

-[Unknown]
