### ISSUE TITLE
PPSSPP Crashes My Laptop

### ISSUE THREAD

**Issue by LightMakerStudios** [hrydgard/ppsspp#10039]
Hi. I've been using PPSSPP for...I believe over 10 days now. Great Emulator, very smooth with the proper settings. But...one problem constantly persists for me. I don't know if there's something wrong with the build of my laptop, or something else, but at seemingly random times while playing, my whole computer crashes and blue screens. No damage seems to be happening, but it's still a little weird. And like I said, seemingly random times. The game I'm playing, and only one I have on it at the moment, is Dissidia 012. If someone could help me, it would be very appreciated.

**Comment by hrydgard** [comment]
In Graphics settings, have you tried changing backends? Are you using OpenGL, D3D9, D3D11 or Vulkan? Graphics drivers are the most common cause of such things so also might want to see if you can upgrade them...

**Comment by LightMakerStudios** [comment]
I'm using Open GL. I'm not sure if I can upgrade them, I'm using one of those laptop's that's like a tablet running windows 10.

**Comment by hrydgard** [comment]
OK. Try switching to Direct3D11 and see if you see the same thing.

**Comment by LightMakerStudios** [comment]
Well if nothing else it runs a bit smoother. I'll report if I get anymore crashes.

**Comment by LightMakerStudios** [comment]
Just got another crash.
The Emulator seemed to run a lot smoother with Direct3D 11 Though. Less graphical glitches, less lag, and it was actually able to correct itself and not drop in frames the second there was a problem.
Still crashed though.

**Comment by unknownbrackets** [comment]
I think there was a weird z-fighting like graphical bug in Dissidia 012 - can you describe (or ideally screenshot) the graphical issue?

In theory, if Windows and your drivers are "working properly", it should be impossible for PPSSPP to completely crash your computer no matter what it does.  But, no software is perfect, not even drivers.

When you stay still crashed - PPSSPP crash, or blue screen?

If you try the latest git build, it may also be worth trying the Vulkan backend.

-[Unknown]

**Comment by LightMakerStudios** [comment]
Well, since swapping to Direct3D 11, crashes are less frequent but still happen.
There have been graphical glitches now though. Every now and then, when a big event happens, like an EX Burst, or map change, or when loading a saved state, the top layer, with all the overlay stuff, gets all buggy. Sometimes happens with an aura around the characters as well.
When I say crash, I mean blue screen. Total crash. 
Last I checked Vulkan Backend was experimental. I'm worried that might cause more problems.

**Comment by LightMakerStudios** [comment]
There's also the occasional game crash when loading a state. Not computer crash, just a game crash.

**Comment by unknownbrackets** [comment]
Hmm, I think Direct3D 11 must still have that load state bug...

Vulkan support is definitely still experimental, but has had a lot of recent improvements.  The reason I'm thinking it might help is that the reason Vulkan even exists is that graphics drivers are COMPLEX.  Vulkan  was designed to give more "to the metal" access so the driver can be nice and simple.

If we assume this is a bug in your driver, "nice and simple" might be less likely to blue screen.

That said, it may have more graphical glitches from issues in PPSSPP's Vulkan support...

-[Unknown]

**Comment by LightMakerStudios** [comment]
It says it fails to initialize graphics. 
Error Message: Failed to load Vulkan Driver library.

**Comment by unknownbrackets** [comment]
Ah, so you don't have Vulkan support in your graphics driver.  Darn.

Direct3D 9 is unlikely to be better than 11.

-[Unknown]

**Comment by LightMakerStudios** [comment]
OK. Any other suggestions? Maybe changing some of the graphical settings?

**Comment by hrydgard** [comment]
Sounds to me like you have some hardware issues, maybe broken memory. Have you tried running memtest64 and similar?

**Comment by LightMakerStudios** [comment]
I'm not even sure what that is.

**Comment by hrydgard** [comment]
https://www.memtest86.com/

**Comment by unknownbrackets** [comment]
Any change here?  Do other games and emulators run on the same system without issues?

-[Unknown]

**Comment by LightMakerStudios** [comment]
Turns out my computer is of terrible quality.
![computerstats](https://user-images.githubusercontent.com/33263489/34343397-f3fdaec4-e99a-11e7-9637-1eb2b53a47cf.PNG)

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
