### ISSUE TITLE
Maverick Hunter X Graphical Backend Crashes

### ISSUE THREAD

**Issue by TallgeeseHeaven** [hrydgard/ppsspp#10032]
Using latest Git build as of this post.

On Vulkan: Crashes after the first intro video.

On OpenGL: On Flame Mammoth's stage, as soon as you go right and see lava, the game freezes, the graphics become heavily corrupted, and the emulator crashes rather ungracefully.

Direct3D11 does not experience either of these crashes.

**Comment by hrydgard** [comment]
How's it working on Vulkan now?

**Comment by SamueldeSena** [comment]
this problem has already been solved in the new version of ppsspp v1.5.4 please install and tester this topic can already be closed
