### ISSUE TITLE
Dante inferno crash at launch (vulkan)

### ISSUE THREAD

**Issue by brujo5** [hrydgard/ppsspp#10031]
Dante inferno crash at launch in Vulkan api since ppsspp v1.4.2-520 (Initial work on passing the latest Vulkan validation checks.)
Last build working v1.4.2.-519

Tested in Galaxy S6

**Comment by hrydgard** [comment]
Does only Dante's crash or also other games?

**Comment by brujo5** [comment]
Only Dante inferno.

**Comment by brujo5** [comment]
This is fixed now thx.
