### ISSUE TITLE
Android: Changing to Vulkan auto-resets to OpenGL without an error message

### ISSUE THREAD

**Issue by oli0371** [hrydgard/ppsspp#10034]
I have two issue each time i select vulkan it stay on opelgl and each time i exit setting reset to defaul

**Comment by hrydgard** [comment]
That happens if it fails to initialize Vulkan. It's currently missing a way to print an error message when that happens.

**Comment by PepeJulio** [comment]
Doesn't this happen to phones that don't support vulkan? Recently tried on a Z5 Compact (no vulkan support) and while the vulkan option was present, it remained in OpenGL after reboot.

**Comment by hrydgard** [comment]
Yes, the problem is that it should at least show a message indicating that.
