### ISSUE TITLE
F1 Grand Prix crash PPSSPP 1.4.2

### ISSUE THREAD

**Issue by Robsoie** [hrydgard/ppsspp#10043]
F1 Grand Prix is the first game of the Formula One serie that was released on PSP, the year after they released Formula One 06 .
No idea if both game use the same engine as i never played the 2006 version.
I had read that F1 2006 on ppsspp was requiring "Simulate UMD delay" to be able to load, but for F1 Grand Prix it loads both with Simulate UMD Delay or Fast.

Anyways, when the game will load a circuit , PPSSPP will crash just when the loading is completed (both in d3d9 and opengl, can't say for vulkan my system does not support it) on win32 (can't say if 64bits build work).

I gave a try to the latest ppsspp-v1.4.2-575-g0c7ae95df (current at the time i write) build from the buildbot but it crashes at the same moment as in stable 1.4.2 release.
Here's the log on dropbox as it's too big to attach it there
https://www.dropbox.com/s/kp0dl1xq75uq9xj/F1GPppsspplog.zip?dl=0

In stable PPSSPP 1.3, the game has no such problem, the circuit load and you can start your engines.
Now as in the past i was wanting to check some 1.3-xxx builds from the buildbot to try to see which one introduced the problem but it looks like every builds prior to v1.4.2-267-g033676ca4 aren't downloadable anymore ?

**Comment by hrydgard** [comment]
Thanks for reporting, this seems bad.

@Orphis mentioned that he'll be looking into fixing the buildbot problem. The issue is that Git changed how it computed those shortened version numbers, and the links are now broken. You can try dropping some letters from the url and you might get them.

**Comment by Robsoie** [comment]
Thank you, by removing the 2 numbers/letters of the version in the url i managed to download the builds for testing.

After testing i found out that the last win32 build that does not crash with F1 Grand Prix is 
ppsspp-v1.3-508-gabf7a7a-windows-x86

The first win32 build that crash PPSSPP for that game is 
ppsspp-v1.3-515-g96c450e-windows-x86

Unfortunately there's no win32 build available between those 2 versions so i can't pinpoint more, but hopefully it will help.

**Comment by unknownbrackets** [comment]
That implicates #9284.

-[Unknown]

**Comment by hrydgard** [comment]
OK, I know what's causing the crash now. It's doing some drawing in through-mode with completely bogus viewport parameters, meaning that it gets ignored. In our heuristics that try to figure out the framebuffer size, we do use the viewport even when drawing is in through mode because games often set it up "correctly" even if not used. 

No idea why it wouldn't crash before that change though... 

I'm going to change it to ignore the viewportwidth/height in the heuristic if it seems bogus.

**Comment by Robsoie** [comment]
Hello,
As new builds were available, i tried the current lastest ppsspp-v1.4.2-614-gd30520a43 for win32
And i can confirm the problem has been fixed completely, F1 Grand Prix does not crash anymore on completing circuits loading.
Thank you.
