### ISSUE TITLE
Gods Eater Burst - crash in Vulkan after logos

### ISSUE THREAD

**Issue by unknownbrackets** [hrydgard/ppsspp#10048]
It seems to end the frame with `curRenderStep_` null (`steps_` is also empty), so when `screenManager()->getUIContext()->Begin();` happens in `EmuScreen::render()`, it crashes.

It might be it went too many frames without drawing, so we bailed out to keep audio playing at a correct pace.

Calling this before rendering the UI "fixes" it:
```c++
thin3d->BindFramebufferAsRenderTarget(nullptr, { RPAction::KEEP, RPAction::KEEP, 0xFF000000 });
```

-[Unknown]

**Comment by SinfulSerenade** [comment]
GEB Region? US? EU?
I'm using US no problem (For now, i guess)

**Comment by SinfulSerenade** [comment]
Also which device are you using Sir?
Well, vulkan is still beta for now and still in it's very early development, so, Bugs and Errors are most likely to occur haha

**Comment by hrydgard** [comment]
I think that's an ok "fix", since we can now eliminate the extra framebuffer bind anyway when it's not needed.

**Comment by unknownbrackets** [comment]
@SinfulSerenade sorry, forgot to mention - this will only happen when FPS counter / debug stats / devmenu / etc. are enabled.

-[Unknown]
