### ISSUE TITLE
Stuttering and crashes in Project Diva 2nd and Project Diva Extend 

### ISSUE THREAD

**Issue by kurayami6** [hrydgard/ppsspp#10040]
Using OpenGL, Project Diva 2nd and Project Diva Extend both suffer from constant stuttering.

Using Vulkan, they both suffer from stuttering and crash when I quit. 

![capture](https://user-images.githubusercontent.com/31968468/32253750-b2e898ba-bef0-11e7-9aa3-69ac2286b4c6.PNG)

![1509492013150](https://user-images.githubusercontent.com/31968468/32253757-b9cb1dce-bef0-11e7-91bf-8c0bee052249.png)

**Comment by hrydgard** [comment]
Why close?
