### ISSUE TITLE
Sticky buttons for touchscreen controls.

### ISSUE THREAD

**Issue by blackman91** [hrydgard/ppsspp#10051]
The emulator epsxe for Android has an option to add extra touchscreen buttons called sticky buttons, when you press a sticky button the button is pressed automatically until you press it again. This works great for games like Mega Man to charge the shot automatically or for racing games when you want to accelerate automatically and use only the accelerometer to move. Example:
https://youtu.be/9iRt0_-xZh4.  (see sticky button in upper right corner)

Would it be possible to add this feature to ppsspp? That would be awesome.

**Comment by Gamemulatorer** [comment]
@iota97

**Comment by LunaMoo** [comment]
Closing then. Thanks for your work @iota97
