### ISSUE TITLE
Latest ppsspp don't install in lineage 15 (Oreo)

### ISSUE THREAD

**Issue by brujo5** [hrydgard/ppsspp#10053]
Latest ppsspp don't install in lineage 15 (Oreo)

The only way to install it is sign application via apktools 

Tested in S6 lineage 15 Oreo
Not tested in s6 stock ROM but may work fine on it

**Comment by dave9292** [comment]
same issue here

**Comment by dave9292** [comment]
not oreo but nougat (miui) please Henrik fix it

**Comment by hrydgard** [comment]
I don't even know what Lineage is.

Turns out to be a spiritual successor to Cyanogen, and I don't have any phones running that. So you guys will need to provide logs and any other information that might help... I don't know what's wrong.

**Comment by brujo5** [comment]
Lineage 15 for S6 https://github.com/TeamNexus

Oficiall https://github.com/LineageOS

**Comment by brujo5** [comment]
the temporary solution is to sign the application

**Comment by hrydgard** [comment]
Oh, ok. @Orphis did the new signing setup for the buildbot, any ideas?

**Comment by iArti** [comment]
@hrydgrard, seems to be that this new singing setup is not working at all

**Comment by fivefeet8** [comment]
Is the the reason for the corruption error when installing the latest dev APK?

**Comment by blackman91** [comment]
Yep same happens on Android 7 motog5 plus, using latest dev.

**Comment by iArti** [comment]
@blackman91 Yes, it is
And this issue still present even with the newest builds

**Comment by Orphis** [comment]
I guess there are issues when signing, I'll investigate today! Thanks for the report.

**Comment by SukharevAndrey** [comment]
The latest installable build on Nvidia Shield Tablet is 1.4.2-563.
Every later build is not installable due to package corruption.

**Comment by WodsonKun** [comment]
@brujo5 you tried ADB?

**Comment by brujo5** [comment]
Nope. I use apktool to sign the application then install as normal apk.

**Comment by Orphis** [comment]
Problem fixed, latest version has been updated.
Just don't zipalign after your apksigner kids. Doesn't work the same as jarsigner!
