### ISSUE TITLE
apk corrupt

### ISSUE THREAD

**Issue by oli0371** [hrydgard/ppsspp#10062]
I try the two last version and each time i got error that apk is corrupt

**Comment by Sunil2735** [comment]
Try to sign the app with Zipsigner on playstore. Works for me.

**Comment by Blacob777** [comment]
thx bro zipsigner works

**Comment by brujo5** [comment]
https://github.com/hrydgard/ppsspp/issues/10053#issuecomment-342165419
Related to this

**Comment by Orphis** [comment]
Problem fixed, the latest version has been updated.
