### ISSUE TITLE
Vulkan? - Crash on saving state during Turbo

### ISSUE THREAD

**Issue by DJScias** [hrydgard/ppsspp#10064]
Hello there,

In certain games that require grinding or a lot of slow walking I turn on the turbo function and every so often use F2 (save the state) just to make sure I don't fuck myself over.

I've however noticed that every time I try this on Vulkan it'll immediately crash out.

The reason why I stated `Vulkan?` though is because about a week ago I was playing Star Ocean 1 & 2 on Direct3D11 (stencil support didn't exist for Vulkan yet then) and noticed every so often that when I tried to save my state on turbo it also would crash.

I can't, however, reproduce the Direct3D11 crash immediately (it doesn't happen 100% of the time) unlike the 100% vulkan crash on savestate.

I hope this issue can help you forward a bit and apologize if it's a repost. Feel free to ask for more information if necessary.

Kind regards,
DJScias

**Comment by hrydgard** [comment]
Thanks for the report, definitely a bug that needs fixing.

**Comment by unknownbrackets** [comment]
Hmm, this isn't happening for me in #10068, at least not with a few games I tried.  It didn't seem like that code was triggering, though...

Does this happen for you in any game, and even in menus or where ever?

-[Unknown]

**Comment by DJScias** [comment]
Hello there,

This happened to me at all times, honestly. Whether I'm in a menu, battle screen or just walking around. The save state crash on Vulkan triggers every single time for me.

Kind regards,
DJScias

**Comment by hrydgard** [comment]
What GPU do you have? Do you have the latest drivers installed?

I can't repro this on nVidia, at least.

**Comment by DJScias** [comment]
Hello there,

Using Geforce 1080 Ti and I do have the latest drivers (388.13) installed.

Crash happens every single time to me while I'm on "turbo" mode and save the state. Just reproduced it once again and it immediately crashed.

**Comment by hrydgard** [comment]
Bizarre. Just to clarify, with Turbo you mean holding TAB to unthrottle the speed?

Another thing to try, make a backup of your memstick/PSP/SYSTEM/PPSSPP.ini and try resetting all settings to default, and see if it still happens.

**Comment by DJScias** [comment]
Hello there,

I've done a new check with the latest commit 3dd08b84fe369c108c76ebf062f0feb520f00be0 and it seems it is no longer crashing.

The only thing that happens is a small 'freeze' for a second when I have both turbo and savestate enabled but afterwards it just continues on without crashing as it did before.

I guess that means it can be resolved, unless you want me to go back and try and see between which commits it got fixed?

Kind regards,
DJScias

**Comment by hrydgard** [comment]
If you feel like doing a few quick checks to somewhat narrow down the range, that could be interesting.  

Closing anyway, you should still be able to post here.

**Comment by DJScias** [comment]
Hello there,

I've narrowed issue down to being fixed in either one of these two commits:
afa5b23abbf1f074448fe7225863f4358e99d0cb
525cb40f8426ee5e0a0e9d84bbdb1116fadbc8ab

Two commits considering the bottom build on the image below still gives crashes for me while using turbo and saving the state but the top one doesn't.
![image](https://user-images.githubusercontent.com/439655/32704310-2a7fb6cc-c803-11e7-80e2-b7db302fe6cb.png)

Kind regards,
DJScias

**Comment by hrydgard** [comment]
Oh! What internal resolution are you using? If it's very high, it was my sloppy readback buffer code that I fixed in the middle commit there, the image just didn't fit.

**Comment by DJScias** [comment]
Hello there,

I use 10x PSP (Rendering Resolution is internal resolution, right?).

Kind regards,
DJScias

**Comment by hrydgard** [comment]
Yup, pretty much confirms my guess. Thanks!

**Comment by DJScias** [comment]
Thank you for fixing the issue. 👍 

Kind regards,
DJScias

**Comment by unknownbrackets** [comment]
Oh, because of the screenshot, of course...

-[Unknown]
