### ISSUE TITLE
[Vulkan] "Failed creating graphics pipeline!"

### ISSUE THREAD

**Issue by Ankris** [hrydgard/ppsspp#10065]
It crashes when I start the game.

Revision: gea2fc5521
[ppsspplog.txt](https://github.com/hrydgard/ppsspp/files/1447977/ppsspplog.txt)

**Comment by hrydgard** [comment]
Interesting. AMD, nVidia or Intel? Fresh drivers?

**Comment by Ankris** [comment]
Dammit, now for some reason it starts. Weird. Should I close?

**Comment by hrydgard** [comment]
Try some more and see if you can get it to happen. If you can't, yeah, go ahead and close, but sounds strange.

**Comment by Ankris** [comment]
It crashes randomly (this time loading a savestate of CoD). Another log:
[ppsspplog.txt](https://github.com/hrydgard/ppsspp/files/1448058/ppsspplog.txt)

**Comment by hrydgard** [comment]
I'm gonna have to improve logging for that error for the log dumps to be useful...

**Comment by hrydgard** [comment]
With that we might get more clues...

**Comment by hrydgard** [comment]
@Ankris Can you try again with the latest builds?

**Comment by Ankris** [comment]
Revision g7922a2ab5

[ppsspplog.txt](https://github.com/hrydgard/ppsspp/files/1450441/ppsspplog.txt)

**Comment by hrydgard** [comment]
OK, so now we're getting 

    55:17:571 idle0        E[G3D]: Vulkan\PipelineManagerVulkan.cpp Failed creating graphics pipeline! result='VK_ERROR_INITIALIZATION_FAILED'

Very odd. Wonder if we might be accidentally using some feature that need to be explicitly enabled, without enabling it... but the validation layers should have caught that.

**Comment by hrydgard** [comment]
@Ankris feel like trying out the latest build from the buildbot?

**Comment by Ankris** [comment]
Same issue.
[ppsspplog.txt](https://github.com/hrydgard/ppsspp/files/1461787/ppsspplog.txt)

**Comment by hrydgard** [comment]
Darn. Really no clue then... So it's very random when it happens? Does it seem related to the use of save states somehow, like, it doesn't happen if you don't use savestates, or something like that?

**Comment by Ankris** [comment]
It's not random this time, it happens instantly when I start Burnout Dominator.

**Comment by hrydgard** [comment]
Interesting, looking at your log it happens when the first shader with dual source blending appears. So yet another vendor is affected. I'm going to try blacklisting AMD from using dual source blending in Vulkan.

**Comment by hrydgard** [comment]
There's a new build up, try that.

**Comment by hrydgard** [comment]
https://community.amd.com/thread/210605  so this appears to be an issue in drivers from early this year.

Can you check again that you really have updated drivers? And before you try to upgrade your driver, can you check what driver version is reported in PPSSPP's Settings/Tools/System Information? Might be able to make this conditional on driver version.

**Comment by Ankris** [comment]
It seems to work now.

![image](https://user-images.githubusercontent.com/14199521/32674871-3b1703e6-c655-11e7-8b78-1159d3bcd8eb.png)

**Comment by LunaMoo** [comment]
Just wondering, does disabling this feature(or it simply not working) could lead to inverted vertices(kind of looking like depth issues) or stuff like that? Because that's how I'm experiencing Vulkan in most more complex games and while I thought it's just something unfinished yet, it might as well be related to dual source blending as well:|.

 Tested this game, and it works and looks same pre and post disabling dual source blending for AMD.
![burnout vulkan](https://user-images.githubusercontent.com/5485237/32675564-8db5eade-c657-11e7-854e-176f61ad6d90.png)
 Similar glitches shows up for example in Metal Gear Solid PW, but does not in simple games like Monster Hunter.

 Might just be a different driver issue;p, 16.12.2 doesn't seem anywhere close to latest one through, I'm on 17.11.1 right now and those versions are going by date I belive:].

**Comment by hrydgard** [comment]
No, the only thing that happens is that a few rare things don't show up like glows around transparent objects in Wipeout.

That's more likely to be this, which makes me sad: https://community.amd.com/thread/221378

**Comment by hrydgard** [comment]
@LunaMoo feel like reporting that as a separate issue btw? I'm closing this one since this particular error has been worked around.

**Comment by unknownbrackets** [comment]
Not that I'm arguing with the workaround, it's great (if unfortunate) - but not having dual source also causes issues like #7356 in some games, so it's not always a glow missing or etc.

-[Unknown]

**Comment by hrydgard** [comment]
Oh yeah, fair enough. Should really get around to implementing a dual pass workaround at some point...
