### ISSUE TITLE
Vulkan - Crash on fullscreen --> windowed (double-clicking)

### ISSUE THREAD

**Issue by DJScias** [hrydgard/ppsspp#10063]
Hello there,

Due to the fact that Vulkan has been receiving a lot of updates I've been using it more and more for the increased performance but I consistently run into this one issue.

I fullscreen my game but from time to time I'll double-click it to make it go back to windowed so I can look at something else but usually the following happens and then it's well.. Gone.

Note: This happened during Persona, but it basically happens with every game on Vulkan. Never had this on Direct3D11 or anything.

What the screen looks like when I go to windowed
![ppssppwindows64_2017-11-06_21-36-48](https://user-images.githubusercontent.com/439655/32462785-ea5910a6-c33a-11e7-993c-5bfcf05a73f1.png)

What the screen looks like when I try to fullscreen it afterwards again
![ppssppwindows64_2017-11-06_21-37-48](https://user-images.githubusercontent.com/439655/32462790-ec4e53e4-c33a-11e7-8df5-6ebe21069de3.png)

The popup that happens (it happens three times)
![ppssppwindows64_2017-11-06_21-37-55](https://user-images.githubusercontent.com/439655/32462792-edaca72c-c33a-11e7-9f97-8e2e1e571b30.png)

And the last popup after trying to close the window by using the red X after clicking the earlier popups away
![ppssppwindows64_2017-11-06_21-40-48](https://user-images.githubusercontent.com/439655/32462852-2b653304-c33b-11e7-9f92-cf07b53425e9.png)

I'm not sure if you'd like some debug information, but it literally happens to me about 90% of the time I resize the screen in Vulkan by double-clicking on it. It doesn't happen immediately but usually about 2-3 min in the games (so not on the ppsspp main menu screen).

Hope this information is helpful and that it's not a repost. If more information is necessary, feel free to ask.

Kind regards,
DJScias

**Comment by hrydgard** [comment]
AMD, nVidia or Intel?

**Comment by DJScias** [comment]
Nvidia, using Geforce GTX 1080 Ti.

**Comment by hrydgard** [comment]
Yeah, I can reproduce this too.

@unknownbrackets I don't quite understand why this happens though, we do try to synchronize..

**Comment by DJScias** [comment]
Understood,

I'll let you two figure it out. Do let me know if I you need more.

**Comment by hrydgard** [comment]
Should be taken care of now, multiple bugs fixed.

**Comment by DJScias** [comment]
Hello there,

@hrydgard I can confirm that I'm not able to make it crash anymore after a rigorous session of resizing it over and over for a few minutes at random times. 👍 

Kind regards,
DJScias

**Comment by hrydgard** [comment]
Excellent, thanks!
