### ISSUE TITLE
Android Cant Install Latest Build

### ISSUE THREAD

**Issue by TediExcaliber** [hrydgard/ppsspp#10067]
I dunno what version of build is starting this problem, but i have try 3 version from 663 lower for android and the result is same

I have trying to reinstall first before installing the latest build but again the result is same, btw iam currently using Android 7

Here image https://imgur.com/QGbNiO7

"App Not Installed"
"Package Seem To Be Broken"

Sorry bad english.

**Comment by hrydgard** [comment]
Try again with the latest from https://buildbot.orphis.net/ppsspp/ and report back please. Orphis fixed a problem with the buildbot.

**Comment by TediExcaliber** [comment]
I try build 668 and still cant be install

Pada tanggal 7 Nov 2017 7.51 PM, "Henrik Rydgård" <notifications@github.com>
menulis:

**Comment by hrydgard** [comment]
That's very strange, seemed to work for most people now...  Try to uninstall the old one completely first, if you didn't try that already.

**Comment by TediExcaliber** [comment]
Oh yes, now i can install it, but need to uninstall the previos build first

Btw i try this method to install build 663 and lower but failed

Anyway thanks.

Pada tanggal 8 Nov 2017 6.53 AM, "Henrik Rydgård" <notifications@github.com>
menulis:
