### ISSUE TITLE
Can't Install PPSSPP Versions after v1.4.2-563-gf0a73353b for Android

### ISSUE THREAD

**Issue by 66Muramasa** [hrydgard/ppsspp#10066]
Getting constant errors about the .apk being corrupted during installation attempt.  Can install other apps just fine, including older versions of PPSSPP.

**Comment by Saramagrean** [comment]
https://github.com/hrydgard/ppsspp/issues/10053

**Comment by 66Muramasa** [comment]
Nevermind.  Was able to resolve by signing the apk with ZipSigner.  Had to uninstall the previous version of PPSSPP to properly install the newly signed apk.
