### ISSUE TITLE
Quitting Symphony of the Night causes a crash

### ISSUE THREAD

**Issue by kurayami6** [hrydgard/ppsspp#10071]
Quitting the unlockable version of Symphony of the Night in Dracula X chronicles causes a crash. 

Using Windows 7, i5, GTX 970. All PPSSPP settings default. Backend is Vulkan. 

![capture](https://user-images.githubusercontent.com/31968468/32530977-8973e80e-c495-11e7-8543-c93e6e09daae.PNG)

**Comment by hrydgard** [comment]
Still happens in the latest builds? Many bugs have been fixed.

http://buildbot.orphis.net/ppsspp/

**Comment by kurayami6** [comment]
Yeah it's fixed in the latest build. Thanks.
