### ISSUE TITLE
Downloaded builds are empty

### ISSUE THREAD

**Issue by PepeJulio** [hrydgard/ppsspp#10073]
@Orphis
If downloaded on PC, last builds show as 0,0 bytes. On phone, it flat out throws an error in the download attempt due to an unknown error.

**Comment by Orphis** [comment]
It works for me though? Maybe a fluke on the interwebz!

**Comment by Orphis** [comment]
(Just joking, I ran out of quota on disk, removed some ancient builds and it's working again).

**Comment by PepeJulio** [comment]
Thanks a lot.
