### ISSUE TITLE
Prince of Persia rival swords  crash in game (Vulkan log included)

### ISSUE THREAD

**Issue by brujo5** [hrydgard/ppsspp#10089]
This game crash in game after seconds of gameplay 
![screenshot_20171111-094958](https://user-images.githubusercontent.com/4172898/32691607-96f9b88a-c6c7-11e7-93ae-ac81a4da3ef6.jpg)

Full log
https://www.sendspace.com/file/e9lcli

Using opengl + slow effects ON
![20171111_093408](https://user-images.githubusercontent.com/4172898/32691642-14e0586c-c6c8-11e7-8901-65822f5f2bee.jpg)

Vulkan + slow effects ON  look fine 
![screenshot_20171111-092607](https://user-images.githubusercontent.com/4172898/32691653-31a66aa4-c6c8-11e7-9409-878f3f540a39.jpg)

Tested in galaxy S6

**Comment by unknownbrackets** [comment]
OpenGL issue looks like it's just #4199.

Does toggling those settings affect the crash on Vulkan?

-[Unknown]

**Comment by hrydgard** [comment]
In the log it looks like a crash related to hardware tesselation (bezier). Try turning off that setting.

Surprised though that this game would make use of those...

**Comment by brujo5** [comment]
@hrydgard you right was a bug with tesselation. 

@unknownbrackets 
Disabled hardware transform + vertex chache etc. But no help 
The only way to fix the weird colour is disabling slow effects but that make game looks dark  (This problem is for Opengl only) 
![screenshot_20171111-114957](https://user-images.githubusercontent.com/4172898/32692574-8ab3c7a4-c6d7-11e7-99dc-97fc4a3c717c.jpg)



Anyway with vulkan work perfectly  thx

**Comment by hrydgard** [comment]
Thanks for testing and reporting.

Gonna have to look into what could be wrong with the tess code but I have some idea. As for the OpenGL bug, maybe some other time :P

**Comment by hrydgard** [comment]
Just committed a fix that should make it work even with hardware tesselation enabled, please try it when the build is done.

**Comment by brujo5** [comment]
@hrydgard 
Still crashes.
Here another log from latest build https://www.sendspace.com/file/giau75

**Comment by hrydgard** [comment]
Hm, ok, thanks.

BTW to get cleaner logs, if you are using ADB command line directly try this:

    adb logcat -s DEBUG NativeActivity PPSSPPNativeActivity PPSSPP

**Comment by hrydgard** [comment]
Redid vulkan hardware tess entirely. Please try again with the latest.

**Comment by brujo5** [comment]
@hrydgard 
Fixed in latest build , thank you.
