### ISSUE TITLE
Midnight Club 3: Vulkan build 707 sky lagging

### ISSUE THREAD

**Issue by Blacob777** [hrydgard/ppsspp#10087]
![screenshot_2017-11-11-21-35-44-001_org ppsspp ppsspp](https://user-images.githubusercontent.com/29165096/32689966-736a1c90-c729-11e7-9d8f-30bbc01f9d97.png)
![screenshot_2017-11-11-21-35-18-560_org ppsspp ppsspp](https://user-images.githubusercontent.com/29165096/32689967-73a3e5a6-c729-11e7-83cb-1d82a1ff78d1.png)

**Comment by Blacob777** [comment]
Android, build 688 vulkan works fine

**Comment by Blacob777** [comment]
And please fix map)

**Comment by hrydgard** [comment]
Looks like some depth buffer conflict, probably related to https://github.com/hrydgard/ppsspp/pull/10086 , maybe we're missing some small detail.

**Comment by Blacob777** [comment]
Midnight club 3

**Comment by hrydgard** [comment]
And what phone or device (most importantly, which GPU does it have?)

**Comment by Blacob777** [comment]
xiaomi mi5s plus snap 821

**Comment by marosis** [comment]
Map Is ok. You must have off-Disable stencil test or something like that

**Comment by Blacob777** [comment]
Default settings vulkan, map broken
![screenshot_2017-11-15-18-11-49-056_org ppsspp ppsspp](https://user-images.githubusercontent.com/29165096/32830736-268047dc-ca31-11e7-990a-a09ffb5ea324.png)

**Comment by Blacob777** [comment]
the sky continues to lag...

**Comment by hrydgard** [comment]
I think this is a side effect of turning on GPU_SUPPORTS_ACCURATE_DEPTH for Vulkan. Not sure whether to blacklist or try to somehow fix it...

**Comment by Blacob777** [comment]
Build 843 sky fixed, thanks guys) pls fix map too)

**Comment by hrydgard** [comment]
Yeah, OK, the map doesn't look very good. Should be cut off into a circle shape I guess but isn't, looks like a typical stencil issue or similar.

**Comment by unknownbrackets** [comment]
What's the actual depth viewport and minz/maxz values used to draw the sky?  What's the clipping flag value?

It seems like this isn't the same issue as a crazy viewport range not being clipped properly (which by the way, doesn't work properly in non-accurate depth either, and I think we could relatively easily make it as bad as OpenGL there.)  So it'd be good to understand what this issue is to figure out how to improve the depth handling.

-[Unknown]

**Comment by unknownbrackets** [comment]
Could you try exporting a GE debugger dump on PC?

To do this, open the game and select Debug -> GE debugger..., then when it's displaying the scene, press Record in the top right.  After a second or so, it'll finish and save a trace of the drawing activity.

After that, check the memstick/PSP/SYSTEM/DUMP folder and it'll have created a file named something like "ULES12345_0000.ppdmp".  You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by hrydgard** [comment]
I believe this to be some sort of ARM driver bug. Bumping further investigation to 1.8.0.

**Comment by hrydgard** [comment]
This one is probably related to https://github.com/hrydgard/ppsspp/issues/11937.

**Comment by hrydgard** [comment]
I believe this is fixed, and we should possibly file a separate issue about the map (might be an issue where the game gets tricky with stencil/alpha).
