### ISSUE TITLE
AMD Vulkan drivers bugginess.

### ISSUE THREAD

**Issue by LunaMoo** [hrydgard/ppsspp#10082]
Pretty awful depth issue which can be seen in quite a lot of games, here's an example from MGS PW:
![vulkan bugginess amd](https://user-images.githubusercontent.com/5485237/32677973-ce9274d8-c660-11e7-8fb5-238d50e5addd.png)
Tested on win 7 and win 10 x64 with latest 17.11.1 drivers.

As Henrik mentioned it's likely this https://community.amd.com/thread/221378

**Comment by hrydgard** [comment]
Yup, it's clearly not handling viewports with "reverse Z" correctly. So we'll have to flip Z in the projection matrix or in the vertex shader instead, if the game wants it flipped.

**Comment by unknownbrackets** [comment]
This would just be the same logic we use in Direc3D 9 right?

-[Unknown]

**Comment by hrydgard** [comment]
Oh right, I forgot D3D9 had a similar or the same problem. Yeah.

**Comment by hrydgard** [comment]
#10086 might take care of this.

**Comment by LunaMoo** [comment]
Yup, looks as in other backends now:).

**Comment by hrydgard** [comment]
@LunaMoo How's performance on AMD?

**Comment by LunaMoo** [comment]
As advertised Vulkan works best when CPU is the bottleneck, which should not be my case with i5-4690K and R7-265 ~ not exactly gaming gpu:).

In MGS PW I get:

OGL
598% x10 res
780%   x1 res

Vulkan
593% x10 res
1400% x1 res

D3d11
629% x10 res
1270% x1 res

(d3d9 seems to be limited to 60 fps max for some reason, so can't test)

Either way I can't complain on performance, thanks:).

**Comment by hrydgard** [comment]
Alright, sounds good enough :)
