### ISSUE TITLE
Black Screen Issues after Version 688 on Android

### ISSUE THREAD

**Issue by 66Muramasa** [hrydgard/ppsspp#10083]
Just as it says in the title.  I'm also getting the old apk corrupt error on version 701.  I was able to install by signing the apk with ZipSigner.

**Comment by 66Muramasa** [comment]
Looks like the issue was considered closed, but I'm still experiencing the same issue.  I use 2x PSP for rendering resolution and Native for device resolution.

**Comment by hrydgard** [comment]
OK, will have another look tomorrow.  Need to be careful when messing with graphics initialization obviously....

Regarding the signing problems, if you uninstall completely then reinstall they should go away. I think.

**Comment by hrydgard** [comment]
@66Muramasa  Are you still seeing this in the latest builds?

**Comment by 66Muramasa** [comment]
@hrydgard Nope.  Thanks and keep up the good work.
