### ISSUE TITLE
Massive Slowdon in Maverick Hunter X in Sting Chameleon Boss room.

### ISSUE THREAD

**Issue by blackman91** [hrydgard/ppsspp#10085]
Game runs contant 60/60 fps using the latest dev version for Android 7 with both Vulkan and GL but when Sting Chameleon turns invisible a massive slowdown occurs (see attachment) in both vulkan and gl, it turns back to normal 60 fps when he is visible again, also in vulkan there is a big graphical bug when he turns invisible, see screenshot:
![screenshot_20171111-022710](https://user-images.githubusercontent.com/6578180/32687721-7d762298-c688-11e7-87a9-a2794c1b623d.png)

Device: Motog5plus

**Comment by hrydgard** [comment]
Sounds like a framebuffer readback effect, maybe the readback can be avoided.

**Comment by SamueldeSena** [comment]
there is only one way to disable block transfer

**Comment by hrydgard** [comment]
How is this now on the two backends? I would guess that Vulkan works better but both still slow?

**Comment by hrydgard** [comment]
@SamueldeSena  Could you try this again with the latest build from https://buildbot.orphis.net/ppsspp/ ? Or at least provide a save or GE capture? https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

**Comment by unknownbrackets** [comment]
Any updates here?

-[Unknown]

**Comment by hrydgard** [comment]
Can we get a GE capture?

**Comment by Gamemulatorer** [comment]
I can clearly reproduce this issue on Vulkan backend but not on OpenGL using ppsspp latest build.
# OpenGL
![Screenshot_2021-09-26-18-28-20-643_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/134804047-99c592bf-817c-4d07-911f-0079c00f9d31.jpg)

# Vulkan
![Screenshot_2021-09-26-18-28-42-412_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/134804062-98a980e5-b9b3-4f50-a2ed-6a85de9ec041.jpg)
![Screenshot_2021-09-26-18-25-42-839_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/134804069-d31b2172-5d27-47a5-9db6-ff5d3f6bc6a2.jpg)

# Dump
[maverickxhunter.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/7231196/maverickxhunter.ppdmp.zip)

**Comment by ResurrectionRedmi9** [comment]
@blackman91 no feedback/outdated!!!

**Comment by hrydgard** [comment]
@ResurrectionRedmi9 Please don't post "no feedback/outdated" unless that's really the case. In this case, we have a known and reproducible (by some) problem, so not much more further feedback is really needed.

**Comment by unknownbrackets** [comment]
Does the VK only glitch happen only with texture scaling on, or always?

Is it much better with a texture shader (i.e. 4xBRZ or MMPX) configured, or is it worse?

-[Unknown]

**Comment by Gamemulatorer** [comment]
> Does the VK only glitch happen only with texture scaling on, or always?

Umm.. yes sometimes happen with textures scaling on without block transfer effects enable but that the cause of performance decrease.

> Is it much better with a texture shader (i.e. 4xBRZ or MMPX) configured, or is it worse?
> 
> -[Unknown]

I can only try MMPX and it's not really worse.

**Comment by Gamemulatorer** [comment]
OpenGL Simulated Block Transfer Effects is ON

https://user-images.githubusercontent.com/37603562/135250289-ab8e1025-de8b-4acf-8952-03bad82060f3.mp4

Vulkan Simulated Block Transfer Effects is ON

https://user-images.githubusercontent.com/37603562/135250337-0e93d6db-73b9-42f8-b5e1-2f7cc3f882d4.mp4

Vulkan Simulated Block Transfer Effects ON fix the graphics issue but lower the performance of the game.

GE Dump
[recording.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/7251041/recording.ppdmp.zip)

**Comment by Gamemulatorer** [comment]
@hrydgard added this game id to RequireBlockTransfer to warn the user that the game will have issue graphic, if simulate block transfer is not enabled.

Also fix the performance issue by adding this game to IntraVRAMBlockTransferAllowCreateFB.

**Comment by Gamemulatorer** [comment]
Here's the game id
# Mega Man Maverick Hunter X
ULES00251 = true
ULUS10068 = true

**Comment by hrydgard** [comment]
Done

**Comment by Felipefpl** [comment]
Thanks again for caring about the oldest issues, this is something HARDLY seen in any other projects here or in sourceforge.

**Comment by Gamemulatorer** [comment]
I think this can be close now this is already fixed?
also remove the No Feedback/Outdated tag.

**Comment by hrydgard** [comment]
Yeah, I guess so.

**Comment by EternalsDarkhole** [comment]
This issue should remove from future milestone.
