### ISSUE TITLE
Vulkan: The "Webfest" (tempest clone) homebrew draws lines wrong

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#10095]
No idea what could cause this, bizarre. 

Vulkan:

![image](https://user-images.githubusercontent.com/130929/32699418-a179e46c-c7b5-11e7-8fa5-c04e8ea2864d.png)

OpenGL:
![image](https://user-images.githubusercontent.com/130929/32699425-bac9eff2-c7b5-11e7-90ca-a643cf8ad715.png)

It's like some of each draw gets included in the previous ones, like if the vertex data offset in PSP RAM was wrong.

Repros on nVidia and Mali so this should be our bug.

**Comment by hrydgard** [comment]
The characters are all stored at the origin and are positioned individually by adjusting the world matrix. It seems to be the updates of these, so the base uniform buffer, that's not completely in sync with the drawing, it's like it's a half step behind. Very odd.

**Comment by hrydgard** [comment]
OK, the game overwrites each set of vertices immediately after drawing with it to prepare for the next draw, and adding a Flush in a strategic location (DrawEngineVulkan.cpp:420, in SubmitPrim) fixes it entirely. So something is somewhat different between the backends.

**Comment by hrydgard** [comment]
Note to self later: The problem is that the Vulkan drawengine has skipped implementing FinishDeferred. Due to how it works it will need to be done slightly differently. (or we just flush).

**Comment by unknownbrackets** [comment]
Ah yes, this is the same issue Crimson Gem Saga had, then.

-[Unknown]
