### ISSUE TITLE
Vulkan: debug messages pop up in some games

### ISSUE THREAD

**Issue by LunaMoo** [hrydgard/ppsspp#10098]
By some games I only reproduced it in MGS PW so far:P - while loading savestate or changing resolution if the new one is higher I get:
````
dstrect offset x + extent > width
````
the other way around where new one is lower I get
````
dstPos + extent x > width
````
not sure if it points to any problem as I don't see anything getting broken by just continuing.

**Comment by hrydgard** [comment]
Gonna want to fix those, as some Vulkan drivers can crash or misbehave if we give them bad data for copies.

**Comment by hrydgard** [comment]
That might take care of it?

**Comment by unknownbrackets** [comment]
I wonder if we ever need full bufferHeight?  I think no...

-[Unknown]

**Comment by LunaMoo** [comment]
That fixed it, thanks.
