### ISSUE TITLE
[Vulkan] Static texture on screen

### ISSUE THREAD

**Issue by Ankris** [hrydgard/ppsspp#10090]
Game: Silent Hill Origins
![image](https://user-images.githubusercontent.com/14199521/32691977-83dd25ea-c710-11e7-8871-19dbead1eb21.png)
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/1463953/ppsspplog.zip)

It happens after the intro.

**Comment by brujo5** [comment]
Could be the same ?

![screenshot_20171112-104759](https://user-images.githubusercontent.com/4172898/32702117-00fb1422-c79f-11e7-8bff-059e165f2dea.jpg)

Sorry for this log but I don't have a PC right now.

Log https://www.sendspace.com/file/ks7w66

**Comment by hrydgard** [comment]
Could be the same issue, could also be something completely different. Not easy to know.

**Comment by Ankris** [comment]
Latest builds doesn't have this issue, closing.
