### ISSUE TITLE
Menu decoration idea

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#10103]
THIS IS NOT PROBLEM IN GAME! ONLY IDEA. some  games also contain an ever-repeating video in psp menu. I think if the same thing was in ppsspp the overall look of the menu would look better. it's just my opinion :).

**Comment by LunaMoo** [comment]
Closing as a duplicate of #2585

**Comment by marosis** [comment]
Aha. Thanks lunamoo i didn't know about it
