### ISSUE TITLE
Vulkan/D3D11: We should reduce the number of generated shaders and pipelines

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#10106]
Since these two backends are for modern hardware where static branching is cheap or nearly free, and they share their uniform handling code, any changes seem natural to introduce in these together.

The goal is to decrease shadergen stutter without having to go as far as to a "ubershader" system (though one similar to dolphin's might be desirable, just complex to support).

Currently we create separate shader variants for every little thing like for example "fog enabled" or not.  The more shaders, the more stutter. For example in Wipeout, nearly every shader exists both in with and without fog variants. Fog is super cheap so this does not feel motivated. We can change this to dynamic state very easily, either by sending in "neutral" fog parameters if it's off, in this case, or simply add a new field of bitflags to the uniform buffers. 

Other examples abound, like the alphatest vs alphatest0 distinction.

Also, a drastic reduction in Vulkan pipelines / D3D11 input layouts can often be made by reducing the number of *output* vertex formats - do we really need to decode to 8-bit normals or can we just decode it all to float?

**Comment by unknownbrackets** [comment]
Makes a lot of sense - we could probably do this with a supports flag or similar to keep GLES the same.  Or would we just change everyone - not sure whether the duplicate fog shaders are really benefiting GLES.

-[Unknown]

**Comment by hrydgard** [comment]
In plain GLES 2.0 there are no integer operations or bitmasking, so that would take a lot of bool variables. That's the reason I don't really feel like doing GLES from the start, at least.

**Comment by Gamemulatorer** [comment]
This is related to #12108 ?

**Comment by unknownbrackets** [comment]
Well, loosely related - but that just creates the existing number of shaders asynchronously.  This is about creating less shaders.

-[Unknown]

**Comment by hrydgard** [comment]
Closing, this has been taken over by #16567.
