### ISSUE TITLE
Use Vulkan by default and disable vertex cache by default

### ISSUE THREAD

**Issue by unknownbrackets** [hrydgard/ppsspp#10102]
Since vertex caching no longer helps as much in Vulkan, and has always caused various flickering and glitches, I think it's reasonable to disable it by default.

I'm not sure we're quite ready - as of opening this issue - to default to Vulkan on supported devices.  But I think we will want to do this.

The biggest blocker to enabling it by default will be sufficient testing and ensuring that there's always a path to a working backend if Vulkan isn't properly supported on the device.

-[Unknown]

**Comment by hrydgard** [comment]
Agreed on both points, and also on the milestone :)

**Comment by Michal1324** [comment]
Yeah that's a good idea

Most of devices are capable of vulkan
