### ISSUE TITLE
Wrong AMD driver info detected

### ISSUE THREAD

**Issue by LunaMoo** [hrydgard/ppsspp#10109]
Basically all backends reports same driver version:
![vulkan wrong driver version shows up](https://user-images.githubusercontent.com/5485237/32706580-b4dcb584-c81e-11e7-9423-91169aa7f1ad.png)

Which from what I can see is my OpenCL driver version:
![open cl](https://user-images.githubusercontent.com/5485237/32706646-1f62b46c-c81f-11e7-9ed7-91c67e42dacb.png)

 Wouldn't really care about the info itself much, but I was hoping the "fix" for #10065 could get limited to older Vulkan drivers as this problematic feature works fine for me and probably would for all other people with gpu's that still get driver updates in 2017.

**Comment by unknownbrackets** [comment]
On Windows, this comes from `GetVideoCardDriverVersion()`.  The code definitely looks like it could be suspect - maybe multiple rows of information are returned.

-[Unknown]

**Comment by LunaMoo** [comment]
In other backends driver version is always same, but other info travels around so maybe:
![ogl version](https://user-images.githubusercontent.com/5485237/32707482-7b4fdc00-c824-11e7-8f50-c83eed1567a6.png)
![d3d11 version](https://user-images.githubusercontent.com/5485237/32707487-8766a7b2-c824-11e7-8263-afdea3c70217.png)
![d3d9 version](https://user-images.githubusercontent.com/5485237/32707488-8aa6e9d2-c824-11e7-8cc2-bfd912c75ba7.png)

**Comment by unknownbrackets** [comment]
Can you paste what this logs?

https://github.com/hrydgard/ppsspp/compare/master...unknownbrackets:driver-ver

Maybe there are multiple "video controllers" (this is my suspicion) and the first one happens to be OpenCL....

-[Unknown]

**Comment by LunaMoo** [comment]
Here:
````
38:23:638 main.cpp:207 I[SYSTEM]: Device: ASUS R7 265 Series v23.20.788.0 from 20171102000000.000000-000 @60hz
38:23:638 main.cpp:208 I[SYSTEM]: Caption: ASUS R7 265 Series, processor: AMD Radeon Graphics Processor (0x6819)
38:23:638 main.cpp:209 I[SYSTEM]: RAM: -2147483648, RAM type: 2, drivers: aticfx64.dll,aticfx64.dll,aticfx64.dll,aticfx32,aticfx32,aticfx32,atiumd64.dll,atidxx64.dll,atidxx64.dll,atiumdag,atidxx32,atidxx32,atiumdva,atiumd6a.cap,atitmm64.dll
````

**Comment by unknownbrackets** [comment]
Hmm, maybe at least the driver date is correct?  Mine looks correct.  I guess we need to see a system with old drivers, though...

-[Unknown]

**Comment by LunaMoo** [comment]
For Vulkan at least I think this  https://www.khronos.org/registry/vulkan/specs/1.0/man/html/vkGetPhysicalDeviceProperties.html could maybe be used instead?

**Comment by unknownbrackets** [comment]
Yeah - we call it in VulkanContext - what type of `driverVersion` does it have?  You're right, that's probably the best thing to use for detecting driver bugs, at least.

I imagine on a multi-GPU system we're listing the wrong version entirely, heh...

-[Unknown]

**Comment by unknownbrackets** [comment]
Realized we're already showing the version, d'oh.

Looks like the broken one was 00404001 from December 2016, before the bug was fixed.  Maybe we can just take  00407000 as the minimum version (probably even 00406000 works, though.)

-[Unknown]

**Comment by LunaMoo** [comment]
Nice:). BTW Vulkan Hardware Capability Viewer software uses a simple:
````
	static const std::string versionToString(uint32_t version)
	{
		std::stringstream ss;
		ss << (version >> 22) << "." << ((version >> 12) & 0x3ff) << "." << (version & 0xfff);
		return ss.str();
	}
````
to get a nice text number from that version id which matches what AMD software shows up: "1.7.0" so yeah to me that part just looked like a random number, but is in fact driver version.

They also have some special code for Nvidia apparently more complex versioning ~ [here](https://github.com/SaschaWillems/VulkanCapsViewer/blob/56b8f4f13933c76fd99c4b125cd733d42f5bd145/vulkanDeviceInfo.hpp#L258)
