### ISSUE TITLE
OpenGL: Weird graphics glitches in Burnout Dominator

### ISSUE THREAD

**Issue by Programie** [hrydgard/ppsspp#10119]
I often have very weird graphics glitches in Burnout Dominator where big parts of the screen are overlayed with some black (but transparency) box.

Normal:
![ules00750_00001](https://user-images.githubusercontent.com/1206521/32741041-31d1e4b6-c8a5-11e7-9330-f88f56b0effd.png)

Glitched:
![ules00750_00002](https://user-images.githubusercontent.com/1206521/32741042-31f38f3a-c8a5-11e7-98b1-712660680f7e.png)

The glitch seems to be disappearing if "Simulate block transfer effects" is disabled.

**Comment by hrydgard** [comment]
Which graphics backend is selected in settings? Which hardware are you running on? Always report these things in graphics issues.

**Comment by marosis** [comment]
Off-disable stencil test, off Vertex cache, on Software rendering, on Buffered rendering, on- Simulate transfler effects, try disable slower effects on or off

**Comment by LunaMoo** [comment]
I can reproduce this in OGL only, bottom pic should show same UI/text as the one above and is in other backends.
 Seams to be affected by the sun effect, it only fails to render when the sun is visible, the sun itself isn't made in standard way as can be seen ~ #6316. I'll try to look at it in the debugger.

**Comment by Programie** [comment]
My graphics configuration:

* Graphics backend: OpenGL
* Mode: Buffered rendering
* Simulate block transfer effects: enabled (disabling this option fixes the glitch for me)
* Frameskipping: Off
* Auto frameskip: disabled
* Prevent FPS from exceeding 60: enabled
* Alternative speed: Unlimited
* Postprocessing shader: FXAA Antialiasing
* Fullscreen: enabled
* Rendering resolution: 10x PSP
* Hardware transform: enabled
* Software skinning: enabled
* Vertex cache: enabled
* Lazy texture caching: disabled
* Retain changed textures: disabled
* Disable slower effects: disabled
* Spline/Bezier curves quality: High
* Hardware tessellation: disabled
* Upscale level: 4x
* Upscale type: Hybrid + Bicubic
* Deposterize: enabled
* Anistropic filtering: 16x
* Texture filtering: Auto
* Screen scaling filter: Linear
* Timer hack: disabled
* Disable stencil test: disabled
* Lower resolution for effects: Off

My environment:
* OS: Kubuntu 17.10
* PPSSPP version: v1.4.1
* Game ID: ULES00750

**Comment by marosis** [comment]
Try latest version 1.4.2

**Comment by Programie** [comment]
@marosis There is no release for version 1.4.2 in the Ubuntu PPA yet, right? I'm using the testing PPA.

**Comment by Programie** [comment]
Just tested it with the latest dev build (v1.4.2-750-gc3c4ec4) but the issue still exists.

**Comment by marosis** [comment]
Aha ok

**Comment by hrydgard** [comment]
This is a scissor rect issue, a broken one gets bound at some point leading to problems. I'm on it.
