### ISSUE TITLE
Buildbot for PSP emulator android downloading not starting

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#10118]
When i click get emulator revision, it will open and close internet window whithout starting downloading. I must copy And paste link for download. :(

**Comment by hrydgard** [comment]
@Orphis ?

**Comment by hrydgard** [comment]
He manages the buildbot.

**Comment by marosis** [comment]
Aha

**Comment by unknownbrackets** [comment]
Downloads seem to work.  Is this still an issue?

-[Unknown]

**Comment by marosis** [comment]
I don't know, maybe problem Is in my mobile.

**Comment by Orphis** [comment]
Which browser and phone are you using?

**Comment by marosis** [comment]
I using Chrome. Lenovo K10a40

**Comment by Orphis** [comment]
Downloads could be rejected for many reasons, one of which is that by policy, you are not allowed to download APK files from Chrome.
Another thing that can happen is the download happening in the background and not noticing.

It works for me otherwise on my own phone?

**Comment by marosis** [comment]
So how I can fix this on android browser?

**Comment by marosis** [comment]
Yeah with background i have problem. When I go out from browser, downloading will automaticaly stop. How I can fix this?

**Comment by Clyybber** [comment]
That probably has to do with your battery settings or your manufacturers OS is killing apps in background very aggressively for more ram or something. Should be closed.

**Comment by Orphis** [comment]
Just download on your PC and transfer the APK to your phone with your cable if the phone has too many issues.
