### ISSUE TITLE
Tomb Raider: Legend weird texture(format related?) in d3d11 / Older Windows only.

### ISSUE THREAD

**Issue by LunaMoo** [hrydgard/ppsspp#10120]
![ules00283_00000](https://user-images.githubusercontent.com/5485237/32743902-1bf974ca-c8ae-11e7-9a1d-9dd9a1bd63d7.jpg)
Frame dump:
[ULES00283_0001.zip](https://github.com/hrydgard/ppsspp/files/1468117/ULES00283_0001.zip)
I think this might be texture format OS version limitation? The problem shows up in win 7, will test in win 10 in a moment.
Yup, not sure if there can be any workaround for that, or should just close, but it does not happen in win 10:).

**Comment by LunaMoo** [comment]
I think all affected textures have are in 5650 format. They have a  row of colorful pixels at the very top, maybe color pallete or something?
![tr textures](https://user-images.githubusercontent.com/5485237/32746011-b5a0c550-c8b4-11e7-9020-fdb883554f8a.png)

**Comment by hrydgard** [comment]
Huh, that's really curious. I'm starting to lean towards bug here, but still a strange one.

**Comment by hrydgard** [comment]
In the bottom picture it looks like texture upscaling is active. is that the case, and does it affect the problem?

**Comment by LunaMoo** [comment]
Nope, but funny thing, texture returns exactly same hashes for replacements, so dumping such texture in for example vulkan can be used to replace it in d3d11 (or other way around ~ Tomb Raider - in search of artifacts:]).

here's a texture dumped in d3d11:
![d3d11](https://user-images.githubusercontent.com/5485237/32750302-89c81b78-c8c2-11e7-800e-88249e368553.png)
and same one dumped in vulkan:
![vulkan](https://user-images.githubusercontent.com/5485237/32750319-936c3d58-c8c2-11e7-8a57-fdc3293e2f5e.png)

**Comment by hrydgard** [comment]
Okay, that is highly suspicious :)

Come to think of it, there's an important difference between Windows 7 and Windows 10 in D3D11. Only later windows versions actually support 16-bit textures in D3D11, and we do workarounds for Windows 7. That might be buggy. It might be possible to repro on Windows 10 by removing this line in GPU_D3D11.cpp:

	features |= GPU_SUPPORTS_16BIT_FORMATS;

**Comment by hrydgard** [comment]
Found the bug. The code tries to be clever by going backwards when upconverting the colors inside the same buffer (to avoid reading just-overwritten data), but fails miserably because inside each line, it's still going forwards. Will need an extra temporary buffer. See if you can fix it :) You'll want to switch to a forward loop while at it.

			} else if (expandTo32bit) {
				UnswizzleFromMem((u32 *)out, outPitch / 2, texptr, bufw, h, 2);
				for (int y = h - 1; y >= 0; --y) {
					ConvertFormatToRGBA8888(format, (u32 *)(out + outPitch * y), (const u16 *)(out + outPitch / 2 * y), w);
				}
			}

**Comment by LunaMoo** [comment]
Will try, from just reverse of the loop without doing anything else I discovered that lots more textures was affected by the issue than it was normally seen:
![ules00283_00001](https://user-images.githubusercontent.com/5485237/32755244-a530a4e0-c8d4-11e7-9b19-f7b36e7a2aa9.jpg)
:3

**Comment by LunaMoo** [comment]
Dunno if that's the right thing to do, but after trying to understand what's happening there just removing that code and making it follow the other path works fine and seems to be doing what you said(:P?), I have no faith in myself through.
````
		} else if (h >= 8 && !expandTo32bit) {
			// Note: this is always safe since h must be a power of 2, so a multiple of 8.
			UnswizzleFromMem((u32 *)out, outPitch, texptr, bufw, h, 2);
			if (reverseColors) {
				ReverseColors(out, out, format, h * outPitch / 2, useBGRA);
			}
		} else {
			// We don't have enough space for all rows in out, so use a temp buffer.
			tmpTexBuf32_.resize(bufw * ((h + 7) & ~7));
			UnswizzleFromMem(tmpTexBuf32_.data(), bufw * 2, texptr, bufw, h, 2);
			const u8 *unswizzled = (u8 *)tmpTexBuf32_.data();

			if (reverseColors) {
				for (int y = 0; y < h; ++y) {
					ReverseColors(out + outPitch * y, unswizzled + bufw * sizeof(u16) * y, format, w, useBGRA);
				}
			} else if (expandTo32bit) {
				for (int y = 0; y < h; ++y) {
					ConvertFormatToRGBA8888(format, (u32 *)(out + outPitch * y), (const u16 *)unswizzled + bufw * y, w);
				}
			} else {
````

**Comment by unknownbrackets** [comment]
Erp, yeah that seems right.

-[Unknown]
