### ISSUE TITLE
Awful Memory Leak while dumping AVI.

### ISSUE THREAD

**Issue by LunaMoo** [hrydgard/ppsspp#10125]
Existing before new changes, it seems to leak every frame quickly filling ram, so something somewhere has to be cleared and it isn't, not sure if I can find it myself, so opening this issue.:]

Edit:
I noticed it's calling av_frame_free when closing file... shouldn't this happen for every frame?

**Comment by hrydgard** [comment]
FFmpeg's frame APIs are confusing so I'd suggest you go look for examples to figure out how to do it correctly, then send a pull :)
