### ISSUE TITLE
Tomb Raider Anniversary Vulkan Render Bugs (video included)

### ISSUE THREAD

**Issue by fivefeet8** [hrydgard/ppsspp#10137]
The start menu is missing at the start of the game.  And missing gun effects and other effects.  The game also freezes when the bear attacks in this video.  The FPS goes to single digits like it's still running, but everything is frozen.   Similar render bugs with Tomb Raider Legend as well.

Device:  Shield TV running 6.1 update

Video:
https://www.youtube.com/watch?v=8-ITXDatXEY&feature=youtu.be

**Comment by hrydgard** [comment]
Merged into #10136
