### ISSUE TITLE
Screenshot feature broken in Vulkan

### ISSUE THREAD

**Issue by LunaMoo** [hrydgard/ppsspp#10134]
It crashes in VKContext::CopyFramebufferToMemorySync with a null source buffer.

**Comment by unknownbrackets** [comment]
Oh, fixing.  It's probably the switch.

-[Unknown]

**Comment by unknownbrackets** [comment]
Err, not so simple.  I guess we could like remember or replay the last frame commands or something?  Might not be so simple...

-[Unknown]

**Comment by hrydgard** [comment]
I'm on it, it's not that hard, you'll see :)

**Comment by hrydgard** [comment]
Hm, I guess there is one problem, swapchain images are not created with usageflags & VK_IMAGE_USAGE_TRANSFER_SRC_BIT, so can't, theoretically at least, be copied from (unless the driver is really nice and lets us do it anyway).
