### ISSUE TITLE
Bloom effects too sharp / not affected by hack in Vulkan

### ISSUE THREAD

**Issue by LunaMoo** [hrydgard/ppsspp#10135]
In order - other backends, other backends with a hack, vulkan:
![other backends](https://user-images.githubusercontent.com/5485237/32818532-2860f942-c9c4-11e7-8bd2-7d116a134f47.png)![other backends and hack](https://user-images.githubusercontent.com/5485237/32818544-331c0e6c-c9c4-11e7-91d2-e7568019c0dd.png)![vulkan backend](https://user-images.githubusercontent.com/5485237/32818551-38cd10a4-c9c4-11e7-9315-7710ece7f1e8.png)
Vulkan isn't even affected by a hack here, so maybe framebuffer doesn't get downsized correctly?

Not sure if that's a really important issue, adding 1,5,0 milestone just because it's Vulkan related.

Edit: One clear difference in GE debugger is that frabuffer size changes in other backends show a smaller picture in preview. In Vulkan the image still fills up whole preview and only resolution shows as reduced, I think that's why the problem happens.

**Comment by hrydgard** [comment]
Seems clear that something is not going right. If you want to investigate, I'd suggest running it twice in RenderDoc, once using D3D11 the other using Vulkan, grabbing snapshots and looking at what happens differently in this scene.

**Comment by LunaMoo** [comment]
To my eyes, everything is made differently:|, so let me write it down, looking at simpler scene - just game logo/startup screen which also has bloom and I see this like that:
0. Draws everything
1. Outputs a nicely rendered screen.
2. Outputs slightly smaller copy of the previous step with a bit less colors, d3d11 starts looking blurry, vulkan one has noticeable aliasing.
3. Outputs previous texture very sharp and pixelated   / First difference as in d3d11 3rd step is very blurry.
4. Even smaller res, again Vulkan looks like using nearest neighbor while d3d looks extremely filtered.
5. Slightly bigger res, d3d11 looks like getting first layer of bloom, vulkan looks messed up,
6. Even bigger res, d3d has pretty bloom, vulkan looks less pixelated, but still looks really bad, kind of like blending 2 layers of smaller images resized with nearest filtering with original picture, the only blur seems to come from that blending and not from filtering images.
7. Finished product with brigt colors and lost details for Vulkan, for d3d11 original image.
8. d3d11 get's finished bright texture with pretty bloom.

 So with that, the problem must be happening around step 2. When I check details of that step things become complicated;p.
D3d11 has just few steps:
DrawIndexed
CopyResource
DrawIndexed
CopyResource
DrawIndexed with different number

Copy resource seems uninteresting, but first DrawIndexed already does output blurry lower res copy so that's I guess where I have to look.
Vulkan starts weird from vkCmdBeginRenderPass(C=Load, DS=Load) 0.00 which already shows image with bloom that doesn't look right, looks kind of blurry due to layer of bloom from who knows where maybe original brighter image get's blended with smaller res aliased copy of itself, next step shows just aliased image.

Heh I'm clueless so I made a copy of all API calls from those steps of second pass:

d3d11 drawIndexed:
````
702    ID3D11DeviceContext::PSSetShaderResources
       context: ResID_3
       StartSlot: 0
       NumViews: 1
       id: ResID_319
703    ID3D11DeviceContext::PSSetSamplers
       context: ResID_3
       StartSlot: 0
       NumSamplers: 1
       id: ResID_302
704    ID3D11DeviceContext::RSSetViewports
       context: ResID_3
       NumViewports: 1
       Viewport[0][0] = 0.0000
       Viewport[0][1] = 0.0000
       Viewport[0][2] = 242.0000
       Viewport[0][3] = 138.0000
       Viewport[0][4] = 0.3750
       Viewport[0][5] = 0.6250
705    ID3D11DeviceContext::RSSetScissors
       context: ResID_3
       NumRects: 1
       Rects: RECT<0,242,0,138>
706    ID3D11DeviceContext::RSSetState
       context: ResID_3
       id: ResID_73
707    ID3D11DeviceContext::OMSetBlendState
       context: ResID_3
       State: ResID_205
       BlendFactor[0] = 0.2510
       BlendFactor[1] = 0.2510
       BlendFactor[2] = 0.2510
       BlendFactor[3] = 1.0000
       SampleMask: 4294967295
708    ID3D11DeviceContext::OMSetDepthStencilState
       context: ResID_3
       State: ResID_206
       StencilRef: 0
709    ID3D11DeviceContext::PSSetShader
       context: ResID_3
       Shader: ResID_320
       NumClassInstances: 0
710    ID3D11DeviceContext::VSSetShader
       context: ResID_3
       Shader: ResID_314
       NumClassInstances: 0
711    ID3D11DeviceContext::Unmap
       context: ResID_3
       Resource: ResID_180
       Subresource: 0
       MapType: D3D11_MAP_WRITE_DISCARD
       MapFlags: 0
       DiffStart: 0
       DiffEnd: 480
       MapData: RawBuffer   480:< 0x3fb6cd00 0x00000000 0x00000000 0x00000000 ...>
712    ID3D11DeviceContext::VSSetConstantBuffers
       context: ResID_3
       StartSlot: 0
       NumBuffers: 3
       id: ResID_180
       id: ResID_181
       id: ResID_182
713    ID3D11DeviceContext::PSSetConstantBuffers
       context: ResID_3
       StartSlot: 0
       NumBuffers: 1
       id: ResID_180
714    ID3D11DeviceContext::IASetInputLayout
       context: ResID_3
       InputLayout: ResID_321
715    ID3D11DeviceContext::IASetPrimitiveTopology
       context: ResID_3
       Topology: TriangleList
716    ID3D11DeviceContext::Unmap
       context: ResID_3
       Resource: ResID_157
       Subresource: 0
       MapType: D3D11_MAP_WRITE_NO_OVERWRITE
       MapFlags: 0
       DiffStart: 143600
       DiffEnd: 143744
       MapData: RawBuffer   144:< 0x43727000 0x430a7000 0x00000000 0x00000000 ...>
717    ID3D11DeviceContext::IASetVertexBuffers
       context: ResID_3
       StartSlot: 0
       NumBuffers: 1
       Strides: 36
       Offsets: 143600
       id: ResID_157
718    ID3D11DeviceContext::Unmap
       context: ResID_3
       Resource: ResID_158
       Subresource: 0
       MapType: D3D11_MAP_WRITE_NO_OVERWRITE
       MapFlags: 0
       DiffStart: 13344
       DiffEnd: 13356
       MapData: RawBuffer    12:< 0x00010000 0x00030002 0x00020000 0x00000000    >
719    ID3D11DeviceContext::IASetIndexBuffer
       context: ResID_3
       Buffer: ResID_158
       Format: DXGI_FORMAT_R16_UINT
       Offset: 13344
720    ID3D11DeviceContext::DrawIndexed
       context: ResID_3
       IndexCount: 6
       StartIndexLocation: 0
       BaseVertexLocation: 0

````

Vulkan vkCmdBeginRenderPass:
````
337    vkCmdPipelineBarrier
       cmdid: ResID_101
       srcStages: VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT
       destStages: VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT
       flags: 0
       memCount: 0
       bufCount: 0
       imgCount: 1
       imgMemBarriers = VkImageMemoryBarrier
       sType: VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER
       srcAccessMask: VK_ACCESS_COLOR_ATTACHMENT_READ_BIT | VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT
       dstAccessMask: VK_ACCESS_SHADER_READ_BIT
       oldLayout: COLOR_ATTACHMENT_OPTIMAL
       newLayout: SHADER_READ_ONLY_OPTIMAL
       srcQueueFamilyIndex: 0
       dstQueueFamilyIndex: 0
       image: ResID_22484
       subresourceRange = VkImageSubresourceRange
       aspectMask: VK_IMAGE_ASPECT_COLOR_BIT
       baseMipLevel: 0
       levelCount: 1
       baseArrayLayer: 0
       layerCount: 1
338    vkCmdPipelineBarrier
       cmdid: ResID_101
       srcStages: VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT
       destStages: VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT
       flags: 0
       memCount: 0
       bufCount: 0
       imgCount: 1
       imgMemBarriers = VkImageMemoryBarrier
       sType: VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER
       srcAccessMask: VK_ACCESS_SHADER_READ_BIT
       dstAccessMask: VK_ACCESS_COLOR_ATTACHMENT_READ_BIT | VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT
       oldLayout: SHADER_READ_ONLY_OPTIMAL
       newLayout: COLOR_ATTACHMENT_OPTIMAL
       srcQueueFamilyIndex: -1
       dstQueueFamilyIndex: -1
       image: ResID_30115
       subresourceRange = VkImageSubresourceRange
       aspectMask: VK_IMAGE_ASPECT_COLOR_BIT
       baseMipLevel: 0
       levelCount: 1
       baseArrayLayer: 0
       layerCount: 1
339    vkCmdBeginRenderPass
       cmdid: ResID_101
       beginInfo = VkRenderPassBeginInfo
       sType: VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO
       renderPass: ResID_117
       framebuffer: ResID_30121
       renderArea = VkRect2D
       offset: VkOffset<0,0>
       extent: VkExtent<242,138>
       pClearValues[]
       cont: VK_SUBPASS_CONTENTS_INLINE

````
And since that was weird, also Vulkan drawIndexed which is another step of that colour pass:
````
340    vkCmdBindPipeline
       cmdid: ResID_101
       bind: VK_PIPELINE_BIND_POINT_GRAPHICS
       pipeid: ResID_30128
341    vkCmdSetScissor
       cmdid: ResID_101
       first: 0
       count: 1
       scissors = VkRect2D
       offset: VkOffset<0,0>
       extent: VkExtent<242,138>
342    vkCmdSetViewport
       cmdid: ResID_101
       first: 0
       count: 1
       views: VkViewport<0.000000,0.000000, 242.000000x138.000000, 0.375000-0.625004>
343    vkCmdSetStencilWriteMask
       cmdid: ResID_101
       face: VK_STENCIL_FRONT_AND_BACK
       mask: 255
344    vkCmdSetStencilCompareMask
       cmdid: ResID_101
       face: VK_STENCIL_FRONT_AND_BACK
       mask: 255
345    vkCmdSetStencilReference
       cmdid: ResID_101
       face: VK_STENCIL_FRONT_AND_BACK
       mask: 0
346    vkCmdBindDescriptorSet
       cmdid: ResID_101
       layoutid: ResID_22355
       bind: VK_PIPELINE_BIND_POINT_GRAPHICS
       first: 0
       numSets: 1
       DescriptorSet: ResID_36608
       offsCount: 3
       offs: 28896
       offs: 29376
       offs: 1056
347    vkCmdBindIndexBuffer
       cmdid: ResID_101
       bufid: ResID_22346
       offs: 13048
       idxType: VK_INDEX_TYPE_UINT16
348    vkCmdBindVertexBuffers
       cmdid: ResID_101
       first: 0
       count: 1
       pBuffers[]: ResID_22344
       pOffsets[]: 111224
349    vkCmdDrawIndexed
       cmdid: ResID_101
       idxCount: 48
       instCount: 1
       firstIdx: 0
       vtxOffs: 0
       firstInst: 0

````


 And with all that info I still can at best guess fail at guessing, but I would think the problem might be that Vulkan doesn't do any blending while d3d11 does in  ID3D11DeviceContext::OMSetBlendState? :C

 I also include a frame dump of that scene, but in d3d11 this frame dump just have completely missing bloom and vulkan has sharp second copy of original render stretched all over the screen, maybe that says more than my investigation:|.
[NPEH00029_0001.zip](https://github.com/hrydgard/ppsspp/files/1475597/NPEH00029_0001.zip)

Gotta take a break after that wall of text;p.

**Comment by LunaMoo** [comment]
While I was closing everything it wanted to save, so I decided to add also dumps in render doc format:
[render doc format dumps.zip](https://github.com/hrydgard/ppsspp/files/1475675/render.doc.format.dumps.zip)

**Comment by marosis** [comment]
you know that OpenGL has this problem as well

**Comment by hrydgard** [comment]
When you see that Vulkan does LOAD and shows an image at the start of a render pass, that's the previous contents of that framebuffer. Ideally we should start most passes with CLEAR but we aren't always able to detect clears reliably so sometimes we load and then immediately clear which isn't great on mobile. oh well.

Renderdoc crashes when loading your vk log, but in the D3D11 log I can clearly see that it's using shader blending in pass 5, which I know is a bit buggy in Vulkan. In d3d11 it correctly binds the blurry texture in the first slot and then adds them together while I bet in Vulkan it's got the wrong image, a sharp one, in the first slot.

So, known bug that I've seen before. Will look into it soon.

**Comment by marosis** [comment]
Ok good luck :D

**Comment by hrydgard** [comment]
Found it, fixed it.

**Comment by LunaMoo** [comment]
@marosis OGL didn't have this bug, if you seen it, you might have some additional / device specific problem or you just ran the game at higher render res and didn't know about "Lower resolution for effects" hack(which results can be seen on the middle picture at the very top of this issue), a few PSP effects look really bad when sampled using higher res and will only look nice with x1 rendering res, hence the hack that at least detects some of them:].

@hrydgard Thanks<3 would never figure that out myself ^_^;.
That software is pretty cool through, I'll probably spend more time staring at things I don't understand much in the future with it. ~Wonder if the logs are saving some AMD driver bugginess, since it still loads fine for me.~

**Comment by hrydgard** [comment]
Yeah, RenderDoc is awesome. Only problem with it is that it doesn't work with legacy OpenGL so can't use it for that backend unfortunately.
