### ISSUE TITLE
Need for Speed Underground Rivals crash during loading on Android

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#10131]
I dont know but Need for Speed Underground Rivals is very unstable when loading game enviroment. In menu Is All ok.

**Comment by hrydgard** [comment]
More detail please. Unstable? Do you mean that it shakes, it flickers or it crashes_

**Comment by marosis** [comment]
Android OpenGL

**Comment by marosis** [comment]
Crashing

**Comment by marosis** [comment]
https://photos.app.goo.gl/vLYU34E0pGQhiCcf2

**Comment by marosis** [comment]
https://photos.app.goo.gl/DOmCVjMAtw9J0hJE2

**Comment by marosis** [comment]
https://photos.app.goo.gl/VD9Ihfb15lIGCdji2

**Comment by LunaMoo** [comment]
"Change emulated PSP's CPU clock" is as it says "unstable":P.
If you don't want your game crashing and having other problems you might need to set it to 0 and reload without using savestates and the game might work better ~ althrough probably at worse performance, can't have everything.:]

 Also please stop sending one line messages every few minutes, you can fit many screenshots and text in single post if you have to, no point being annoying to people subscribed here.

**Comment by hrydgard** [comment]
If it works with default settings, close this. Changing the PSP clock is indeed not recommended at all, I'm thinking of making the option harder to access because it causes quite a bit of trouble.

**Comment by marosis** [comment]
Aaaannd for what Is Rewind Snapshot frequency? I dont know how it working and how i can use it. I will try off PSP clock but i will have very Slow  Speed:)

**Comment by hrydgard** [comment]
I think you'll have ok speed on that device even with normal PSP clock, maybe you need to turn up frameskipping to 1.

That's how often it will take savegames automatically, if you turn on that feature. Got nothing to do with emulation speed.

**Comment by marosis** [comment]
No it's not helped me. I deleted my settings + reset ppsspp settings+ restarted ppsspp.same Crash

**Comment by marosis** [comment]
Yes when i using 1frameskipping All Is ok with 15 fps. I have been using ppsspp for two years, so I know something :)

**Comment by marosis** [comment]
Thanks hrydgard for explanation. Ok LunaMoo no problem

**Comment by marosis** [comment]
Not helped

**Comment by unknownbrackets** [comment]
I'm confused by the recent comments.  Everything is okay with frameskip 1 and default settings, or it still crashes?

Also - enabling rewind could slow things down, so it could have an impact on emulation speed.  Just leave it off unless you have a powerful device.

-[Unknown]

**Comment by marosis** [comment]
Sorry. In menu And in game Is All ok..ONLY in loading Are always crashes

**Comment by marosis** [comment]
Used default settings

**Comment by marosis** [comment]
I found the mistake. when loading, the processor loads too much and the game crashes. will start to show slowly: fps20 / 20 => fps 10/10 => fps 0/0 => CRASH. I tried setting 1000Mhz (the most safer, but the slowest) and the game was as crashed.

**Comment by unknownbrackets** [comment]
Using the locked CPU setting is not the most safe - it's a hack that is known to cause crashes.  Does this happen when that setting is disabled?

-[Unknown]

**Comment by marosis** [comment]
I tried everything with MHZ, graphics settings atd. But allways crashing

**Comment by marosis** [comment]
I think, I need have Vulkan

**Comment by hrydgard** [comment]
@marosis how is this now?

**Comment by marosis** [comment]
Same

**Comment by marosis** [comment]
Now trying. I've deleted savestates https://photos.app.goo.gl/VUMEzyZl4JbhSBDm2

**Comment by marosis** [comment]
Looks like working but do not close it yet

**Comment by marosis** [comment]
https://photos.app.goo.gl/351eosKJxpU2vZ902

**Comment by marosis** [comment]
Crash Is after two first races in career mode

**Comment by hrydgard** [comment]
Interesting, that's useful info.

**Comment by marosis** [comment]
Btw i wrote you to Gmail

**Comment by marosis** [comment]
Wow fixed but idk how! Thank you. Closing

**Comment by M4M0M3N** [comment]
Good morning.
I also have this problem when I have to load specific maps. I drop the fps while loading and freezes the screen. I read that a user has fixed it. How did he do it?

**Comment by Gamemulatorer** [comment]
> Good morning.
> I also have this problem when I have to load specific maps. I drop the fps while loading and freezes the screen. I read that a user has fixed it. How did he do it?

@M4M0M3N what is your phone specifications and are you using the latest ppsspp github on buildbot?

**Comment by M4M0M3N** [comment]
Not used ppsspp on my phone, but on retropie installed on raspbery pi4 (I have other games and they work fine god of war, Star Wars - Battlefront II). I have now updated ppsspp. Now when it blocks the loading, it asks me if I want to upload the old saved state
