### ISSUE TITLE
ShieldTV Vulkan Render Bugs (video included)

### ISSUE THREAD

**Issue by fivefeet8** [hrydgard/ppsspp#10136]
FF4:

Starting a new game with FF4 shows many rendering issues.  Blacks screens, missing effects, dialog missing, etc..etc..

Device:  Shield TV running 6.1 update

Here is a video of them:
https://www.youtube.com/watch?v=1x2sdHdfNsM&feature=youtu.be

Tomb Raider:

The start menu is missing at the start of the game. And missing gun effects and other effects. The game also freezes when the bear attacks in this video. The FPS goes to single digits like it's still running, but everything is frozen. Similar render bugs with Tomb Raider Legend as well.

Device: Shield TV running 6.1 update

Video:
https://www.youtube.com/watch?v=8-ITXDatXEY&feature=youtu.be

**Comment by hrydgard** [comment]
There are many games breaking on Shield TV with Vulkan specifically. Really don't understand what's going on since nVidia drivers are usually solid, heh.

**Comment by unknownbrackets** [comment]
Seems like stencil is completely broken.  Maybe we're ending up with a preferred depthstencil format without stencil or something?  Haven't had a chance to look yet.

-[Unknown]

**Comment by hrydgard** [comment]
Nope, it's dual src again. Sigh.

**Comment by hrydgard** [comment]
And it was broken for a really stupid reason...
