### ISSUE TITLE
PPSSPP crashing when switch to full screen (Vulkan)

### ISSUE THREAD

**Issue by GuilhermeGS2** [hrydgard/ppsspp#10146]
If I'm using Vulkan API in window mode and press F11 to go full screen, I get a black screen and a few seconds later a message saying PPSSPP stopped working.

My GPU: NVIDIA GTX 650 1GB.

**Comment by hrydgard** [comment]
Ingame (if so which game) or in the menu or both?

**Comment by GuilhermeGS2** [comment]
I'm using v1.4.2-810-ga56d6f239 now, and it's not happening anymore. If I remember well it crashed ingame and in the menu too, but last time I tried was in the menu.

**Comment by hrydgard** [comment]
Okay, good, closing then. When reporting bugs, always try the latest build first.
