### ISSUE TITLE
Weird slowdown using Vulkan in Win7(only with Aero?)

### ISSUE THREAD

**Issue by LunaMoo** [hrydgard/ppsspp#10153]
Works perfectly fine on Windows 10 as well as with basic win 7 theme(which has aero disabled) I can reproduce it easily in God of War demo where my performance on Vulkan drops from 500%(normal speed as seen under Win 10, also comparable with d3d11) to about 50-80% speed.
 Weird thing is, my cpu load is pretty low ~ 7% with my gpu load often dropping to 0% when PPSSPP window is showing(and slowing down), when it's not by either minimizing or even alt tabbing to web browser window, the gpu load goes to 20% and for a short moment after going back to PPSSPP it runs fast until dropping again.

 No idea why it would only happen with GOW(also have only demo to test), but I really can't find any other game affected soo far, this feels soo weird that it could as well be another AMD driver issue, dunno, doesn't bother me at all, but probably worth tracking to see in case it's more popular issue.

**Comment by hrydgard** [comment]
Ugh. Given the problems we've seen so far, seems like AMD/Windows users are better off sticking to D3D11 for the time being. Sigh.

**Comment by LunaMoo** [comment]
Don't have a platform to test this anymore and nobody else reported such issue so going to close.
