### ISSUE TITLE
Graphical Issues in Dead or Alive Paradise when Using Vulkan on Android

### ISSUE THREAD

**Issue by 66Muramasa** [hrydgard/ppsspp#10150]
It'll be easier to explain by submitting a couple of images.  OpenGL doesn't have this problem.  I'm running this on a OnePlus 5 (Android).
![screenshot_20171117-131836](https://user-images.githubusercontent.com/33438850/32964987-a7672e46-cb9a-11e7-8df5-3c99deedcc68.jpg)
![screenshot_20171117-131841](https://user-images.githubusercontent.com/33438850/32964990-af50493a-cb9a-11e7-81a7-9115e9ee8b3a.jpg)

**Comment by LunaMoo** [comment]
Just to clarify did you tested and it works on pc or changed to "on android" because that's the only platform you tried?

 This problem was affecting OGL in the distant past until it was fixed in #4105

**Comment by hrydgard** [comment]
It also affected Vulkan until fairly recently. Which build where you using, the latest?

**Comment by 66Muramasa** [comment]
I don't have a PC capable of running PPSSPP.  I'm currently using build 815 on Android.

**Comment by hrydgard** [comment]
Found what I think is the problem. Let me know if it works.

**Comment by 66Muramasa** [comment]
![screenshot_20171117-175019](https://user-images.githubusercontent.com/33438850/32973922-2543b4f4-cbc0-11e7-820f-0bbbb0a394d5.jpg)
Yep, that took care of it.  Thanks and good work.
![screenshot_20171117-175013](https://user-images.githubusercontent.com/33438850/32973920-210e5db2-cbc0-11e7-8124-ac46c05a1789.jpg)
