### ISSUE TITLE
[Request] Sync audio with emulation speed

### ISSUE THREAD

**Issue by GuilhermeGS2** [hrydgard/ppsspp#10156]
Don't know if you guys already considered this and if I'm asking in correct area, but something that sync the audio with the emulation speed would be nice, just like on PCSX2. A "robotic" sound is more enjoyable than cracked sound.

**Comment by LunaMoo** [comment]
We already have one request for it in #8412, so I'll close this.

Just a heads-up, but this was implemented in #8717 ~ unfortunately delayed due to instability.:]
