### ISSUE TITLE
Vulkan: Bomberman graphical issues during the game (ULUS10121)

### ISSUE THREAD

**Issue by CesarAxe** [hrydgard/ppsspp#10152]
In OpenGL and Direct3D 9/11 works well, tested with the last git build.
Settings:
Windows 10 16299
AMD Radeon R7 250 with latest drivers.
![ee](https://user-images.githubusercontent.com/17837481/32977950-c9c68854-cc05-11e7-8437-43460f6d2bac.PNG)

**Comment by LunaMoo** [comment]
If you can, please open GE debugger while running this game and press "Record" wait a moment then check your \memstick\PSP\SYSTEM\DUMP find the newly created ThisGameID.ppdmp file, zip it and drag and drop here, that should give a better idea what's not working there:].

**Comment by CesarAxe** [comment]
I did it in this part of the game:
[ULUS10121_0001.zip](https://github.com/hrydgard/ppsspp/files/1484801/ULUS10121_0001.zip)

**Comment by unknownbrackets** [comment]
That dump renders right for me on Windows 7 / NVIDIA.  Does this still not work for you in the latest git build?

Vertex format for missing things:
float texcoords, ABGR 8888 colors, float normals, float positions, u16 indexes
Cull is disabled.

Characters:
float texcoords, float normals, float positions, float weights (8), u16 indexes

UI:
through, u16 texcoords, ABGR 8888 colors, float positions
Cull is also disabled (but it's through.)

Also, I think it's using a negative Z, so maybe cull + negative depth was broken.

-[Unknown]

**Comment by hrydgard** [comment]
Wondering if this is another victim of the reverse-Z issue in AMD drivers, which we worked around by enabling "accurate depth".

**Comment by CesarAxe** [comment]
@hrydgard I tried the last driver 17.12 and it does not give that problem.

**Comment by unknownbrackets** [comment]
Okay, sounds like it was a depth issue, then.  Thanks for verifying.

-[Unknown]
