### ISSUE TITLE
(Suggestion) Add Toggle L & R Buttons feature and "separable" buttons (Android)

### ISSUE THREAD

**Issue by Leopard20** [hrydgard/ppsspp#10159]
Can you please add an option that makes L & R buttons toggleable? This would be extremely useful in games that require you to hold L and/or R buttons to perform actions (such as Assassin's Creed).
A way to do this would be to add another virtual button (but maybe hide it by default), so that every time the user presses it the L and R buttons become toggleable.

Also, can you add an option that makes the directional buttons and the "shape" buttons (triangle, cross, etc) move separately when you want to change the layout?

**Comment by 66Muramasa** [comment]
You could try using the "Combo Key Setup" and add the corresponding buttons in "Control" settings. That would help to alleviate any issues with the L & R buttons on a touch screen.  You can use multiple inputs with the press of one button with that feature.  Or better yet, get a gamepad to pair up with your Android device, via Bluetooth.  Don't know what to say about your other suggestions.

**Comment by leopard20** [comment]
Does that mean, for instance, if I check R and cross in the "combo key setup" menu and then press either of the buttons, both will be pressed at the same time?

**Comment by leopard20** [comment]
Never mind. I figured it out!
But that means I'll have to add 4 more buttons for high profile actions too! The toggle feature seems more reasonable to me! 
Still, thanks for the tip!

**Comment by leopard20** [comment]
@hrydgard 
Instead of making the default "shape" buttons separable, I think it's better to add another set of shape buttons, but make them invisible.
This is a concept drawing I prepared that shows what I mean:
![screenshot_2017-12-06-18-54-14-747_org ppsspp ppsspp](https://user-images.githubusercontent.com/16115820/33670390-328f7874-daba-11e7-94e3-6c1e0824a7f6.png)

**Comment by leopard20** [comment]
@hrydgard 
Should I close this or what?!

**Comment by hrydgard** [comment]
Why? Just haven't gotten around to it, doesn't mean it won't ever happen..

I'd really like to make touch controls a lot more flexible in some more generic way, maybe allowing lua scripts so people can make really smart things for each game. That's quite a project though.

**Comment by leopard20** [comment]
Sorry. You hadn't said anything so I figured you weren't interested!

**Comment by hrydgard** [comment]
There are many many issues :)

**Comment by leopard20** [comment]
By the way, how are you gonna prioritize these issues?! Some issues are really old and are practically buried under newer issues. So maybe they deserve to be fixed first.
On the other hand, newer issues probably have better chance of receiving feedback if needed (their creators probably check their issues on a regular basis). 
This must be really tough too! 😵

**Comment by Gamemulatorer** [comment]
Can we have this in the future v1.15?

**Comment by Gamemulatorer** [comment]
This might be fixed with https://github.com/hrydgard/ppsspp/commit/57b4cd394a69029dcb8943e1bad33a4d149dcf99?

**Comment by unknownbrackets** [comment]
Yeah, this can be accomplished now with #13869, so I'll close as such.

-[Unknown]
