### ISSUE TITLE
Vulkan : Project Diva Extend / 2nd flicker and invisible text 

### ISSUE THREAD

**Issue by zminhquanz** [hrydgard/ppsspp#10155]
I saw a new problem , issue in this game , when ingame and main menu , it's flicker
![bugs 2](https://user-images.githubusercontent.com/11285640/32987019-aad10b60-cd11-11e7-960e-d2b807027707.png)
![bugs 3](https://user-images.githubusercontent.com/11285640/32987020-ab08a4e4-cd11-11e7-9354-73c718c923e8.png)

**Comment by unknownbrackets** [comment]
If you open ppsspp.ini (found in memstick/PSP/SYSTEM/ppsspp.ini on Windows), and find this line:

```
HighQualityDepth = 1
```

And replace it with:

```
HighQualityDepth = 0
```

Does this issue go away?

-[Unknown]

**Comment by zminhquanz** [comment]
@unknownbrackets Oh , the issues is gone , on Android is the same , i used Galaxy S7 using Adreno 530 but the issues not happen

**Comment by unknownbrackets** [comment]
It might be that depth clamping (supported on some Adreno) fixed this?

-[Unknown]

**Comment by zminhquanz** [comment]
![screenshot_20180103-174629](https://user-images.githubusercontent.com/11285640/34517630-5e415226-f0ae-11e7-8773-cb3cfafd568b.png)
![screenshot_20180103-174648](https://user-images.githubusercontent.com/11285640/34517631-5e78b2e8-f0ae-11e7-951f-6662d36922d2.png)
Nope , i updated latest firmware , driver version there isn't update , so depth clamping temporary isn't support at this time

**Comment by zminhquanz** [comment]
![image](https://user-images.githubusercontent.com/11285640/34525448-8edde57a-f0d1-11e7-854c-92ef3369b610.png)
![image](https://user-images.githubusercontent.com/11285640/34525500-bd230e88-f0d1-11e7-88a6-92593a857883.png)
@unknownbrackets On PC using NVIDIA GPU , have depth clamping feature but having issues when enable HighQualityDepth

**Comment by leopard20** [comment]
@unknownbrackets @LunaMoo 
I  have completed this game and didn't notice the issue even once (android). I think it's fixed.

**Comment by benderscruffy** [comment]
this can be closed
i didnt come across the issue

**Comment by unknownbrackets** [comment]
Great, I know we made some improvements to depth handling (but more are needed.)

-[Unknown]
