### ISSUE TITLE
(Android) PPSSPP restarts when I lock the device (on Vulkan only)

### ISSUE THREAD

**Issue by leopard20** [hrydgard/ppsspp#10178]
Every time I lock my phone while PPSSPP is in the foreground, the app restarts (after unlocking the device).
However, if I minimize it then locking and unlocking won't cause any problem.
I'm not sure if it's only on my device but maybe someone else could test it to verify the issue.

**Comment by hrydgard** [comment]
Can you check if this is new from 1.4.0 , or if it only does it in development builds? These Android lifecycle issues are super nasty to debug and fix..

**Comment by leopard20** [comment]
After testing it for a while I realized it only happens when I enable Vulkan. No issue on OpenGL.

**Comment by leopard20** [comment]
Unrelated question: do you think you could also add "backend hot swapping" to the public release later? It would be nice if I could choose a specific backend for each game in the game settings.

**Comment by hrydgard** [comment]
Backend hotswapping is very unstable, way too crashy to enable in release. Not sure exactly why, but seems more like a driver issue than something we could fix easily.

The version I will release very soon is 1.5.0.

**Comment by SamueldeSena** [comment]
This issue has already been resolved in the new version of ppsspp v1.5.4 this topic can now be closed

**Comment by leopard20** [comment]
Confirmed. No issue in my tests. I close the issue now.

**Comment by leopard20** [comment]
The issue seems to be back.

**Comment by hrydgard** [comment]
Can you check a few previous builds to figure out approximately when the problem returned?

**Comment by unknownbrackets** [comment]
Hmm, I just tried locking and unlocking a bunch of times, and eventually segfaulted on a nullptr in `Vulkan2D::DestroyDeviceObjects()`.

From what I can tell, it's because of this change:
https://github.com/hrydgard/ppsspp/commit/7d0fc9ce65543419c3f4cb9da0934422521069f9#diff-53eb901b2b467d523153817680d8c888L1183

Since the shutdown request came in before NativeInitGraphics was called, which is why I'd added that guard previously.

-[Unknown]

**Comment by hrydgard** [comment]
Oh, I see. Yeah, should probably not have removed that if-check when removing lostdevice in favor of shutdown...

**Comment by hrydgard** [comment]
This should be fixed now, please re-open if not.
