### ISSUE TITLE
PES: Black screen problem in last update

### ISSUE THREAD

**Issue by hanooty** [hrydgard/ppsspp#10179]
I have pes game and I'm trying to play it with the default settings but I have some ugly grafics like black screen 
ScreenshotsAsPNG link

http://upfile.mobi/mWhjYM619H1

**Comment by hrydgard** [comment]
What hardware? Vulkan or OpenGL? Default settings?

**Comment by hanooty** [comment]
OpenGL 
GPU :
Adreno(TM)330

**Comment by hanooty** [comment]
But when I use old versions like v1.3 and un-check MipMap working fine. ..but in new builds haven't MipMap option and I want use last builds serial 
Any solution? ???

**Comment by LunaMoo** [comment]
You already opened one issue about this in #9733, closing.
