### ISSUE TITLE
Objects disappear beyond a certain distance in the main menu of Midnight Club LA Remix

### ISSUE THREAD

**Issue by Leopard20** [hrydgard/ppsspp#10173]
In the main menu objects disappear beyond a certain distance. 
One more thing (although I'm not sure about this one because I haven't played the original game before): when the game slows down, e.g in the first few seconds of the game when the phone rings, the world around the car turns black.
GPU: Adreno 530
PPSSPP version: 1.4.2.816 (dev build)

**Comment by hrydgard** [comment]
.816? Try the latest. 

https://buildbot.orphis.net/ppsspp/

**Comment by leopard20** [comment]
P.S: The above-mentioned issues happen regardless of the selected backend.

**Comment by leopard20** [comment]
Sure.

**Comment by leopard20** [comment]
You're right. There flickering issue is fixed in the latest build.

**Comment by unknownbrackets** [comment]
The main menu bug isn't new right?

-[Unknown]

**Comment by hrydgard** [comment]
No it isn't, bumping to 1.7.

**Comment by marosis** [comment]
Still same issue

**Comment by unknownbrackets** [comment]
Could you try exporting a GE frame dump?  These help a lot.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by benderscruffy01** [comment]
still happens
![midnight](https://user-images.githubusercontent.com/48821663/54876041-370f4100-4e44-11e9-9fa7-d2902abf8ba8.PNG)
[DUMP.ZIP](https://github.com/hrydgard/ppsspp/files/3000111/DUMP.ZIP)

**Comment by Anuskuss** [comment]
Fixed by #13262.

**Comment by Panderner** [comment]
Hmm that's a depth texturing issue.

**Comment by hrydgard** [comment]
That's good to know - I'll close this when depth texturing is implemented for OpenGL.

**Comment by Gamemulatorer** [comment]
> still happens ![midnight](https://user-images.githubusercontent.com/48821663/54876041-370f4100-4e44-11e9-9fa7-d2902abf8ba8.PNG) [DUMP.ZIP](https://github.com/hrydgard/ppsspp/files/3000111/DUMP.ZIP)

Looks fix this to me using OpenGL/Vulkan Snapdragon 439 Adreno 505.

![Screenshot_20230314_120754_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37603562/224890831-12c2f28f-cc29-4bb2-b951-931ed97fbe13.jpg)

Might be fix by https://github.com/hrydgard/ppsspp/pull/16961?

**Comment by Panderner** [comment]
Unfortunately still has an issue for Direct3D 9:
![ULUS10383_00000](https://user-images.githubusercontent.com/37503397/224921019-06a7fe27-c9e4-4e01-944e-c009242fb9da.jpg)
![ULUS10383_00001](https://user-images.githubusercontent.com/37503397/224921036-420f5b30-c3d6-4424-8484-604114e41b45.jpg)

**Comment by Gamemulatorer** [comment]
> Unfortunately still has an issue for Direct3D 9: ![ULUS10383_00000](https://user-images.githubusercontent.com/37503397/224921019-06a7fe27-c9e4-4e01-944e-c009242fb9da.jpg) ![ULUS10383_00001](https://user-images.githubusercontent.com/37503397/224921036-420f5b30-c3d6-4424-8484-604114e41b45.jpg)

And this is also is not fix using Direct3D 9? https://github.com/hrydgard/ppsspp/issues/12294

**Comment by hrydgard** [comment]
I think we're gonna leave D3D9 behind here.
