### ISSUE TITLE
(Android) Manhunt 2 - newspaper in radar instead of arrow!

### ISSUE THREAD

**Issue by leopard20** [hrydgard/ppsspp#10175]
In the radar you can see something like a note or newspaper instead of arrow for enemies!

**Comment by hrydgard** [comment]
Screenshot?

**Comment by leopard20** [comment]
Can't upload cuz I'm on mobile. But found this on the web:
https://lh3.googleusercontent.com/-Ly7nwxKcZ6E/WF9hNckKKII/AAAAAAAAEr0/I3v9fyPS_Qw/1482644556821.jpg%20cursor:%20pointer;

This is how it should be:
https://r.mprd.se/media/images/157386-Manhunt_2_(USA)-3.jpg

**Comment by LunaMoo** [comment]
Closing as a duplicate of #9615. Please try to search before opening new issues to check if they don't already exist.:]

**Comment by leopard20** [comment]
Right. Sorry.
