### ISSUE TITLE
Tactics Ogre runs slow

### ISSUE THREAD

**Issue by mrcorra** [hrydgard/ppsspp#10171]
I'm using an LG Stylo 3+. Most games work fine. What I don't understand is why a less advanced game runs very slow. Trying to control the frame rate improves nothing and makes the game flash constantly. Nothing I do can really fix the issue. It just runs very slow.

**Comment by hrydgard** [comment]
Try to disable the setting "Simulate block transfer effects" for this game. IIRC it likes to copy the framebuffer back to RAM every frame, why it does it I don't know. That's a very slow operation. @unknownbrackets  you've looked at this, right?

**Comment by mrcorra** [comment]
Oh my god... The fix was so simple. I feel like an idiot. Thank you haha

**Comment by mrcorra** [comment]
Oh man. Now the text is all really blurry. And some things just don't show up.

**Comment by mrcorra** [comment]
Never mind I fixed it. Sorry.

**Comment by unknownbrackets** [comment]
I haven't really played this game through, so maybe there's a good reason, but it seems to download the bottom right corner - 48x48 pixels - every frame, and in some areas even upload that to the next frame, and then clear over it anyway.

Kinda suspect it's a leftover debugging feature.

The game may use block transfer effects in other areas, such as in battle.

-[Unknown]
