### ISSUE TITLE
Some UI is wrong size (Android)

### ISSUE THREAD

**Issue by Saramagrean** [hrydgard/ppsspp#10174]
Lastwork: v1.4.2-165-g705499c.

![screenshot_20171122-175917](https://user-images.githubusercontent.com/26355472/33139827-f766d8e8-cfe0-11e7-90b0-dd33751dd2bc.png)

![screenshot_20171122-175927](https://user-images.githubusercontent.com/26355472/33139932-32f58a9e-cfe1-11e7-82e9-b892f50b9a45.png)

Firstbreak: maybe  since v1.4.2-177-gd2ac92e. (app doesn't start) I take screenshot from v1.4.2-181-gae94516.

![screenshot_20171122-175823](https://user-images.githubusercontent.com/26355472/33139952-42423d30-cfe1-11e7-8aa6-a3cd929be463.png)

![screenshot_20171122-175831](https://user-images.githubusercontent.com/26355472/33139976-5057773c-cfe1-11e7-9833-7cd84c9f6359.png)

.

**Comment by hrydgard** [comment]
Probably related to the switch to native truetype rendering on Android. Thanks for reminding me, I'd seen the NEON issue but hadn't noticed sliders could get so broken.

**Comment by unknownbrackets** [comment]
Heh.  But think of all the bugs you wouldn't have had fun fixing.

-[Unknown]

**Comment by Saramagrean** [comment]
Thanks :)
