### ISSUE TITLE
Tiny text offset on pause screen(UI)

### ISSUE THREAD

**Issue by LunaMoo** [hrydgard/ppsspp#10180]
It's not much of a problem, most might never notice it:
![font offset](https://user-images.githubusercontent.com/5485237/33173606-fdcaca5e-d054-11e7-9454-edfcc42f6550.png)
you can see a line of pixels wrapping around. It's affected by small ui at window size x1, disappearing from "save state" and appearing at "load state".
 Doesn't happen in OGL.

**Comment by hrydgard** [comment]
Can't be bothered to figure out whatever layout issue is causing the offset, instead just always round to whole pixels when drawing text. Should be done anyway as our text bitmaps are not meant to be drawn with subpixel offsets, as can be seen in your screenshot :)

**Comment by LunaMoo** [comment]
Hmm weirdly the problem is unchanged, looks exactly as before in all affected backends so I'll reopen. Hopefully this is not something AMD specific(:p).

**Comment by unknownbrackets** [comment]
Reproduces for me for sure - let me try something.

-[Unknown]

**Comment by hrydgard** [comment]
Hm, my change should have at least made it a little sharper :)  But yeah there was another problem, thanks @unknownbrackets .
