### ISSUE TITLE
Micromachines V4 Crash after loading

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#10183]
After loading i press START button and game will Crash. All was fine in many builds back. Using latest build.

**Comment by marosis** [comment]
crashing after loading map

**Comment by hrydgard** [comment]
As always I'm going to ask. Android or PC? Vulkan or GL, or D3D? What hardware? This is important information, don't forget to put it in your bug reports.

**Comment by oli0371** [comment]
Me too i have issue game force close without warning on android nougat 7.0, vulkan backend, mali gpu

**Comment by hrydgard** [comment]
OK, I know what this is, it's a check in the ARM64 JIT that wasn't turned on before but is now. It might point to an interesting bug... Thanks.

**Comment by marosis** [comment]
Fixed thanks
