### ISSUE TITLE
Call of Duty Crash after v1.4.2-848

### ISSUE THREAD

**Issue by Lotv** [hrydgard/ppsspp#10184]
In Call of Duty PPSSPP crash when starting a Mission with every version after v1.4.2-848
with Vulkan or OpenGL

Os: Android 7.1.1
Model: ZTE Axon7 
Snapdragon 820
Adreno 430

**Comment by hrydgard** [comment]
Got a crash log? through ADB or otherwise.

**Comment by Lotv** [comment]
Unfortunately not

**Comment by hrydgard** [comment]
I think this may be related to #10183 , stay tuned..

**Comment by hrydgard** [comment]
Fixed that one, let me know if the fix works for COD as well.

**Comment by Lotv** [comment]
Issue fixed... COD working again....  thank you very much
