### ISSUE TITLE
[Feature Request] Close PPSSPP when using command line

### ISSUE THREAD

**Issue by Anuskuss** [hrydgard/ppsspp#10197]
I'm using an emulation frontend to start my games. When PPSSPP gets started with a game path supplied as a command line argument, the last button in the pause menu (**Exit to menu**) should be replaced with **Exit** (closes the emulator). This would make the transition from frontend to emulator (and vice versa) smoother.

**Comment by Anuskuss** [comment]
@hrydgard Would it be possible to squeeze this in for the big release tomorow or do you have to think about this first?

**Comment by LunaMoo** [comment]
There's already an option which makes "transition from emu to frontend smoother" :
````
--escape-exit
```` 
replaces the pause completely for an instant exit.

**Comment by Anuskuss** [comment]
Nice, I could've sworn that I saw an exit there once (maybe RetroPie?) but I wasn't really sure.

Anyway, where can (Windows) users see the command line options? Could you include them in the ReadMe?

**Comment by Anuskuss** [comment]
Whoops, that was a bit premature. This is not *really* what I want, I still want to access the settings. I'll reopen this.
