### ISSUE TITLE
Vulkan: Bloom effect on pause screen becomes black in Midnight Club L.A. Remix

### ISSUE THREAD

**Issue by iArti** [hrydgard/ppsspp#10194]
(Maybe it isn't shaders, I don't know, sorry)
Here is an example
Vulkan:
![screenshot_20171126-235814](https://user-images.githubusercontent.com/23010139/33244308-0730713a-d306-11e7-915d-a359eb653b65.png)
OpenGL:
![screenshot_20171126-235841](https://user-images.githubusercontent.com/23010139/33244309-076c8184-d306-11e7-828d-6b4ff52df188.png)

Using last build on Xiaomi Mi Max (Snapdragon 650) (Android 7.1.2)

**Comment by hrydgard** [comment]
Is this only when paused or all the time when playing? (curious why the screenshot is from the pause screen).

**Comment by iArti** [comment]
Only when paused, because at pause background became bright and bloom (using OpenGL)

**Comment by iArti** [comment]
Solved by turning slow effects on

**Comment by unknownbrackets** [comment]
Ah, okay.  If there was no downside to disabling slow effects, we would just disable them for everyone and remove the option.

I'm going to close this then - the bug was already fixed, but we gave people an option to not have it fixed if they want more speed.

-[Unknown]
