### ISSUE TITLE
Daxter force close

### ISSUE THREAD

**Issue by oli0371** [hrydgard/ppsspp#10193]
When finish 1st mission in daxter the game force close.. i am using latest ppsspp on s7 edge exynos mali gpu and vulkan backend.. i try 4 latest build same issue on all

**Comment by zllIJudgeIllz** [comment]
![image](https://user-images.githubusercontent.com/34289935/33638586-c751db92-da1e-11e7-80f1-e2c4a7ca1401.png)

**Comment by hrydgard** [comment]
@oli0371  Does this still happen in the latest builds?

**Comment by hrydgard** [comment]
Yeah, I suspect a lot of the remaining Vulkan issues are driver bugs..

**Comment by hrydgard** [comment]
How is this now?

**Comment by zminhquanz** [comment]
@hrydgard It's about driver bugs , so i think you can close this issue

**Comment by hrydgard** [comment]
Yeah, probably.
