### ISSUE TITLE
Medal of honor Heroes fully playable

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#10198]
Hrydgard you did it!!!!!!!! Game Is fully playable And don't have any glitches thanks a lot!!!!!! You Are awesome. (Sorry i know this Is not issue:D) Screenshot: https://photos.app.goo.gl/NL9iMg9V7IgLqm9G2

**Comment by marosis** [comment]
THX everybody

**Comment by hrydgard** [comment]
Thanks, but @LunaMoo deserves a lot of the credit for discovering the suspicious BBOX commands before each draw, which screwed things up.

Also no need to open a new issue, we have #6554 already.
