### ISSUE TITLE
Android: Path to SD card hard to find on some devices

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#10199]
We should try to detect the presence of an extra SD card (in addition to the built-in storage) and show a button to navigate to it.

For example, I got a report that on a Galaxy Note 8, it's mounted on ```/storage/6BF1-DDB6/```, which is not very intuitive.

**Comment by Michal1324** [comment]
Yeah its not something nice one some phone brands in file explorer its random numbers/letters instead of like internal/sdcard

**Comment by unknownbrackets** [comment]
Is it always /storage/?  Or can we just read mtab?

-[Unknown]

**Comment by hrydgard** [comment]
This one is really difficult to do well because there's no official API for managing multiple external storages, other than as "media folders" and nonsense like that. There are possibilities for device specific hacks, but it's just a lot of messing around. Additionally, this one will also get harder in the future with the new storage stuff. I'm gonna push this to future.

**Comment by hrydgard** [comment]
Fixed by #13885, as far as it's possible...
