### ISSUE TITLE
Significant input lag in all Project Diva games

### ISSUE THREAD

**Issue by ghost** [hrydgard/ppsspp#10195]
I assume the input lag is present in every game, but it''s a major problem in the Project Diva series, for obvious reasons. 

Even with the 60 FPS cheat, a wired controller, Aero turned off in Windows 7, the games are basically unplayable on any difficulty other than easy in my opinion. I've tried the Retroarch core, and the difference between it and standalone PPSSPP in terms of input lag is like night and day.

My question is can anything be done to fix or reduce it? I'm using Windows 7, GTX 970, i5. Not that I think those things make any difference.

**Comment by hrydgard** [comment]
I'm not quite sure why it's better in retroarch, so this should be looked into.

**Comment by Dotty** [comment]
RetroArch has display options to prevent excessive buffering. Including a pretty neat GL swap trick labelled hard sync.
https://github.com/libretro/docs/blob/master/docs/guides/optimal-vsync.md#input-latency
There's even quite a sizeable thread on their forums dedicated to getting input latency as low as possible.
https://forums.libretro.com/t/an-input-lag-investigation/4407

**Comment by unknownbrackets** [comment]
So basically using this to sync against the GPU:
https://www.khronos.org/opengl/wiki/Sync_Object

We could also do this in Vulkan.

-[Unknown]

**Comment by leopard20** [comment]
PD Extend has almost zero input lag on my device (Android). But PD 2nd has a noticeable input lag (~50-80 ms)

**Comment by unknownbrackets** [comment]
As noted in #4020, enabling real clock sync helps.

@hrydgard, I wonder if it makes sense to reduce the max frames rendered ahead of display when this setting is on.  It's already basically a clear choice that input/network should be realtime as possible, so it seems logical to extend to display as well.

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, that's not a bad idea. I'm not gonna go poking in the frame timing until well after 1.8.0 though :)

**Comment by unknownbrackets** [comment]
Yeah, agreed.  For 1.8.0, we should probably remember to add to the release notes that if you get a drop in performance, it's because lag sync works correctly now... or maybe we should just flip it off automatically, it mostly didn't work before anyway.

-[Unknown]

**Comment by AkiraJkr** [comment]
I think it's best to keep it turned off automatically. It's best to not have people complaining about a drop in performance soo suddenly.

**Comment by hrydgard** [comment]
I'm gonna change the name of the ini parameter so it gets reset for everybody.

**Comment by leopard20** [comment]
Just a reminder: PD Extend works well so make sure you don't break it in 1.9.0! ;)

**Comment by hrydgard** [comment]
I don't plan to break anything, and if I do let me know :)

**Comment by hrydgard** [comment]
Closnig this in favor of #17685
