### ISSUE TITLE
Mgs peace walker bugs loading next area (cataratas de la muerte) on android

### ISSUE THREAD

**Issue by mobsoe** [hrydgard/ppsspp#10191]
First of all love the app. Been having an awesome time playing through this game with my tablet. And its been going smoothly until now.

During mission I go to next area and it just keeps loading forever. Its only this area in the mission. Also been in this area before so must be something like a cutsene or tweak or whatever. (If its important its the mission to get the I'd card from the soldier in an orange jacket)

Any ideas on what to do? 

Version 1.4.2 on android. version of peace walker is us

**Comment by hrydgard** [comment]
Might want to try the latest build from https://buildbot.orphis.net/ppsspp/ . Be careful though, if you end up going back you won't be able to use any save states, only regular save games will transfer back and forth between versions.

**Comment by mobsoe** [comment]
Thank you for your reply.  Downloaded new build but sadly it did not work.. Still freezes at loading that specific next area. Could it be the game img who is faulty? Any other ideas?

BTW Norwegian danish or swedish Henrik?

**Comment by hrydgard** [comment]
Could very well be the image, as I haven't seen any other reports of this. Try to redump your UMD..

Swedish.

**Comment by Sunil2735** [comment]
Try loading the game directly and do not load save states. There is a possibility you have lost the save/install data for MGS Peace walker.

**Comment by mobsoe** [comment]
Oh sorry since im traveling i havent been able to reply here. It fixed when i reinstalled with the small package. And then it worked perfectly. Installed det large install and it also worked fine!:) so thanks for replies if anybody else experience this issue, hopefully this helps!

**Comment by Sunil2735** [comment]
U r welcome ☺️
