### ISSUE TITLE
[Vulkan] Critical message Juiced 2: Hot Import Nights

### ISSUE THREAD

**Issue by GuilhermeGS2** [hrydgard/ppsspp#10190]
I get a critital message when try to go  to the next race in the game, it happens at loading screen. Doesn't occur using OpenGL. The message says:

"Ran out of space in pool. sz=3034 res=-2
Try to continue?"

Whatever I choose results in the emulator crashing.

**Comment by hrydgard** [comment]
@GuilhermeGS2 Does this still occur?
