### ISSUE TITLE
Garbled text / image quality issues on Vulkan renderer in Ace Combat X (Android, possibly Windows as well)

### ISSUE THREAD

**Issue by gannon345** [hrydgard/ppsspp#10208]
Running on a Shield K1 tablet on Android 7.

Here is what it looks like on Vulkan:

![screenshot_20171129-230534](https://user-images.githubusercontent.com/8151956/33416696-2578e616-d55b-11e7-9993-3c1d06ea7733.png)

And here is what it *should* look like (on the OpenGL renderer):

![screenshot_20171129-230641](https://user-images.githubusercontent.com/8151956/33416706-326ec6b0-d55b-11e7-975d-cb9c37dd1e86.png)

The heavy black font also impacts other 2D / UI related items, adding black lines in places where there shouldn't be anything.

Both images were captured at 1x PSP resolution, upscaled to native, with no speed hacks. Buffered rendering on (if also occurs on Vulkan with buffered rendering off). Not sure if it helps, but a while back the OpenGL renderer had a similar issue and you were able to fix it by making some changes specific to Nvidia implementations, but I don't know the details. I believe it was fixed alongside the corrections made to fix the black/invisible ground issues with regard to Nvidia hardware on Gods Eater Burst, if that rings any bells.

I don't currently have PPSSPP installed on my PC to test if it's also occurring in Windows, but will test it as soon as I have time and update here.

**Comment by LunaMoo** [comment]
Could be just another case of dual source blending. It was disabled on X1 due to buggy drivers, K1 might be using similar ones:].

**Comment by gannon345** [comment]
Will this be corrected in a future build? I swear, I love my Shield tablet, but it seems like Nvidia has some problematic implementations in OGL and Vulkan compared to other Android devices. :(

**Comment by unknownbrackets** [comment]
If this is dual source blending (do we know if this works right on PC yet?), then it's probably an issue of either drivers or hardware limitation.

So far, we've had to disable dual source blending on a bunch of devices, because the drivers do it incorrectly.  I know the NVIDIA SHIELD TV is one of them.  The driver even says it supports the feature, it just doesn't work.

I'm not sure about the SHIELD tablet - I don't think we're blacklisting it there, right now.  Maybe the issue is we should...

If you go to System Information -> Vulkan Features, do you see "dualSrcBlend" in the list as active/enabled?

-[Unknown]

**Comment by gannon345** [comment]
Yep. 

dualScrBlend: Available: 1 Enabled: 1

**Comment by hrydgard** [comment]
In settings/tools/system information, what does it say under name and board? Gonna blacklist it.

**Comment by gannon345** [comment]
Name: NVIDIA:SHIELD Tablet K1
Board: unknown

**Comment by hrydgard** [comment]
Realized that the field I wanted was "Vendor" but I'm gonna guess it's "NVIDIA Tegra K1". Made a quick commit to blacklist it, let me know if it works.

**Comment by gannon345** [comment]
I see the changes on the build bot. I don't have network on the device right now (I'm at work) but will download and test the latest build when I get home tonight.

Also you're right on the Vendor, "NVIDIA Tegra K1."

**Comment by gannon345** [comment]
Changing dualScrBlend fixed it. The text looks like on the OGL renderer now in Ace Combat X and this fixed the black field issue in Madden 12 as well on Vulkan.

**Comment by unknownbrackets** [comment]
I'm going to mark this closed then - although we should re-enable once drivers fix this feature.

-[Unknown]
