### ISSUE TITLE
Field Commander crashes when skipping videos

### ISSUE THREAD

**Issue by Leopard20** [hrydgard/ppsspp#10209]
When I skip ANY video (intros, mission briefing, etc) the game crashes.
Unthrottling is safe though.

It happens on both OpenGL and Vulkan.
Version: 1.5.1-6 
GPU: Adreno 530

P.S:
@hrydgard 
What have you changed in the lastest build? It's much smoother in some games! (such as Syphon Filter and SOCOM) Great work.

**Comment by leopard20** [comment]
Also tested on v1.5.2. Same issue.

**Comment by hrydgard** [comment]
@leopard20  There have been many optimizations between 1.4.2 and 1.5, and also many opportunities for new bugs apparently :)

**Comment by unknownbrackets** [comment]
Did this not crash in 1.4.2?  If so, it would help a lot if you could try a few git builds between the two.

https://buildbot.orphis.net/ppsspp/index.php?m=fulllist

There's about 1000 changes made in PPSSPP between 1.4.2 and 1.5.0, but if you check v1.4.2-500-g424af6008 and it was a bug there, you can cut that in half.  If you try 8 to 10 builds this way (going by halves), you can find exactly the change that caused the bug.

-[Unknown]

**Comment by leopard20** [comment]
Update: If I don't skip ANY video (intros, mission briefing, etc) then I can play missions too. But as soon as I skip a video the game crashes.
Thankfully there's the unthrottle feature to fill in for that! 😉

**Comment by leopard20** [comment]
@unknownbrackets 
I just tested it on version 1.4.2. This time the game freezes completely. No crash though.

**Comment by leopard20** [comment]
Update: Not platform-specific. Also happens on PC.

**Comment by unknownbrackets** [comment]
Could you try exporting a GE debugger dump on PC?

To do this, open the game and select Debug -> Ge debugger..., then when it's displaying the scene, press Record in the top right.  After a second or so, it'll finish and save a trace of the drawing activity.

After that, check the memstick/PSP/SYSTEM/DUMP folder and it'll have created a file named something like "ULES12345_0000.ppdmp".  You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by leopard20** [comment]
Should I skip the video too? How can it dump if it crashes?!

**Comment by leopard20** [comment]
Here it is:
[ULUS10088_0001.zip](https://github.com/hrydgard/ppsspp/files/1527422/ULUS10088_0001.zip)
Don't know if I did it right though!

**Comment by leopard20** [comment]
Should I press Record right before the crash? I did it **before** skipping the video in this dump.

**Comment by hrydgard** [comment]
Any difference on the latest builds?

**Comment by leopard20** [comment]
Nope. Still the same.

**Comment by benderscruffy** [comment]
v1.7.1-210-g9bda7cb64
still happens
47:45:108 SasThread    E[CPU]: MIPS\MIPSTables.cpp:929 MIPSCompileOp: Invalid instruction 00231c1e
47:45:108 SasThread    E[CPU]: MIPS\MIPSTables.cpp:929 MIPSCompileOp: Invalid instruction 00050101
47:45:108 SasThread    E[CPU]: MIPS\MIPSTables.cpp:929 MIPSCompileOp: Invalid instruction 000c0501
47:45:108 SasThread    E[MEMMAP]: MemmapFunctions.cpp:56 Unknown GetPointer 00000000 PC 00000000 LR 04088000

[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/2622625/ppsspplog.zip)

**Comment by benderscruffy** [comment]
now when you load the game it closes down ppsspp straight away
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/4021278/ppsspplog.zip)

**Comment by unknownbrackets** [comment]
v1.9.3-170-g6a196c04a may fix the crash, but probably won't fix the video issue.

-[Unknown]

**Comment by benderscruffy** [comment]
yep that fixed it

**Comment by Panderner** [comment]
Same happens in v1.9.3-1015-gba06c87a7.

**Comment by ANR2ME** [comment]
Apparently, if you presses the X button fast enough (like rapidly clicking it) before the first video appeared, it will skip the video without getting bluescreen/crash, although based on the log it seems the video was processed without issue.

**Comment by MojoJojoDojo** [comment]
Can confirm this is still a thing on the latest dev builds.
You would get a purple screen with some error in it (not blue one) if you try to skip he intro.

**Comment by ANR2ME** [comment]
i think it's purple when you had cheat enabled, and blue if cheat being disabled

**Comment by MojoJojoDojo** [comment]
> i think it's purple when you had cheat enabled, and blue if cheat being disabled

Nope I had plugins enabled in ppsspp.ini and that caused it...
Kinda weird but ok.

**Comment by Gamemulatorer** [comment]
Adding this game id to MpegAvcWarmUp fix the crashing issue :)

**Proof**

MpegAvcWarmUp Not Enable = CRASH on the first video

https://user-images.githubusercontent.com/37603562/135722547-40e2fcc0-3283-4992-9e74-29ebea4b88bf.mp4

MpegAvcWarmUp Enable For This Game = NO crash on the first video

https://user-images.githubusercontent.com/37603562/135722609-2f6bf9d0-d3b9-47c4-beec-6eefaee655f3.mp4

@hrydgard what do you think it is safe to add this game to MpegAvcWarmUp?

**Comment by hrydgard** [comment]
Since it turns a crash into a non-crash, yeah, safe enough, I'll put it in... But of course, would be nice long term to understand what the actual problem is.

**Comment by benderscruffy** [comment]
is this still an issue ??

**Comment by hrydgard** [comment]
I guess the workaround worked. We know the ffmpeg stuff isn't that accurate, leading to problems like this, but it's not game specific - so I'm closing this one.
