### ISSUE TITLE
GOD of war bad Speed

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#10204]
I have GOW on android. Problem Is when you have  low fps (like 10+fps) but 100% sound Speed. 100% sound Speed but Slow emulation WHY?

**Comment by unknownbrackets** [comment]
The forum has lots of information dedicated to this topic.  This will probably help the most:
http://forums.ppsspp.org/showthread.php?tid=22159

Part of the problem as well is that most phones have bad GPU drivers.  This is getting better with Vulkan, so if your device supports Vulkan, try that.

See the forum for more info.

-[Unknown]
