### ISSUE TITLE
Reported shader mismatches

### ISSUE THREAD

**Issue by unknownbrackets** [hrydgard/ppsspp#10210]
Since 1.5.x (and some v1.4.2 git builds), we're getting reports of link errors due to shader mismatches.

Maybe we should report/log the shader ids along with this message.

Some examples:

(Mali-400 MP)
```
Error in shader program link: info: L0007 Varying 'v_color1' not found in vertex shader / fs: #version 100
precision lowp float;
 varying vec4 v_color0;
 varying vec3 v_color1;
void main() {
  vec4 s = vec4(v_color1, 0.0);
  vec4 v = v_color0  + s;
  gl_FragColor = v;
}
 / vs: #version 100
precision highp float;
attribute vec4 position;
attribute lowp vec4 color0;
uniform mat4 u_proj_through;
varying lowp vec4 v_color0;
void main() {
  v_color0 = color0;
  gl_Position = u_proj_through * vec4(position.xyz, 1.0);
}
```

(VideoCore IV?)
```
Error in shader program link: info: ERROR:LINK-7 (line -1) Fragment shader uses a varying that has not been declared in the vertex shader / fs: #version 100
precision lowp float;
uniform sampler2D tex;
 varying vec4 v_color0;
varying mediump vec3 v_texcoord;
void main() {
  vec4 t = texture2D(tex, v_texcoord.xy);
  vec4 p = v_color0;
  vec4 v = vec4(p.rgb + t.rgb, p.a);
  gl_FragColor = v;
}
 / vs: #version 100
precision highp float;
attribute vec4 position;
attribute lowp vec4 color0;
uniform mat4 u_proj;
varying lowp vec4 v_color0;
void main() {
  v_color0 = color0;
  gl_Position = u_proj * vec4(position.xyz, 1.0);
}
```

(iOS / PowerVR)
```
Error in shader program link: info: WARNING: Could not find vertex shader attribute 'normal' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'w2' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'texcoord' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'w1' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'color1' to match BindAttributeLocation request.
ERROR: Input of fragment shader 'v_texcoord' not written by vertex shader
 / fs: #version 100
precision lowp float;
uniform sampler2D tex;
 varying vec4 v_color0;
varying highp vec3 v_texcoord;
void main() {
  vec4 t = texture2D(tex, v_texcoord.xy);
  vec4 p = v_color0;
  vec4 v = vec4(p.rgb + t.rgb, p.a);
  gl_FragColor = v;
}
 / vs: #version 100
precision highp float;
attribute vec4 position;
attribute lowp vec4 color0;
uniform mat4 u_proj;
varying lowp vec4 v_color0;
void main() {
  v_color0 = color0;
  gl_Position = u_proj * vec4(position.xyz, 1.0);
}
```

(Mali-T720)
```
Error in shader program link: info: L0007 Fragment shader uses a varying v_color1 that has not been declared in the vertex shader.
 / fs: #version 300 es
#extension GL_ARM_shader_framebuffer_fetch : require
precision lowp float;
 in vec4 v_color0;
 in vec3 v_color1;
out vec4 fragColor0;
void main() {
  vec4 s = vec4(v_color1, 0.0);
  vec4 v = v_color0  + s;
  fragColor0 = v;
}
 / vs: #version 300 es
precision highp float;
in vec4 position;
in lowp vec4 color0;
uniform mat4 u_proj_through;
out lowp vec4 v_color0;
void main() {
  v_color0 = color0;
  gl_Position = u_proj_through * vec4(position.xyz, 1.0);
}
```

Marking as a regression for now.

-[Unknown]

**Comment by unknownbrackets** [comment]
I'll also note - we've seen these before 1.4.2 though - there's also u_proj/u_proj_through mismatches too.  I had hoped a change in 1.5.x would fix this, but it probably didn't.

```Error in shader compilation: info: Compile failed.
ERROR: 0:14: 'u_proj' : undeclared identifier
ERROR: 1 compilation errors. No code generated.

 / code: #version 300 es
precision highp float;
in vec3 position;
in mediump vec3 normal;
uniform mat4 u_proj_through;
uniform mat4 u_world;
uniform mat4 u_view;
uniform lowp vec4 u_matambientalpha;
out lowp vec4 v_color0;
void main() {
  vec3 worldpos = (u_world * vec4(position.xyz, 1.0)).xyz;
  mediump vec3 worldnormal = normalize((u_world * vec4(normal, 0.0)).xyz);
  vec4 viewPos = u_view * vec4(worldpos, 1.0);
  gl_Position = u_proj * viewPos;
  v_color0 = u_matambientalpha;
}
```
(PowerVR Rogue G6200)

-[Unknown]

**Comment by hrydgard** [comment]
Hm, nasty. I hoped we were done with these too...

**Comment by hrydgard** [comment]
Do we get any information about which games this happens in?

**Comment by unknownbrackets** [comment]
Yes.

Mismatches reported in: MONSTER HUNTER PORTABLE 3rd HD Ver., DRAGON BALL Z SHIN BUDOKAI 2, MONSTER HUNTER FREEDOM UNITE™, NEED FOR SPEED™ MOST WANTED 5-1-0, Patapon™3
http://report.ppsspp.org/logs/kind/355

Hardware transform compile error reported in: Bakugan™: Defenders of the Core, Prince of Persia The Forgotten Sands™
http://report.ppsspp.org/logs/kind/39

-[Unknown]

**Comment by hrydgard** [comment]
The NEED FOR SPEED report is probably the one we did fix. 

But I realized (and reproduced) something - if you switch between hardware and software transform, you can trigger some of these errors fairly easily, at least on Windows. We should probably wipe the shader caches and make sure the switch only takes effect at the end of the frame.  I don't quite understand why this happens though as the ID should effectively include the effect of hardware transform...

**Comment by GuilhermeGS2** [comment]
I got some graphics issues recently on my both devices (Mali 400MP4 and Mali T720MP2). I habe random "ghosts" of some HUD texture upscaled to whole screen, sometimes the game start with this, sometime happens when I change the resolution, most times when I load a saved state.

**Comment by GuilhermeGS2** [comment]
The games I have this is Midnight Club 3 and Naruto Shippuden Ultimate Ninja Impact. Dom't remember other game.

**Comment by hrydgard** [comment]
@GuilhermeGS2  Does HW/SW transform make a difference?

**Comment by GuilhermeGS2** [comment]
I loaded a state of Naruto with HW transform disabled and had the same issue, but doesn't happen with non-buffer rendering. This issue doesn't only cause these "ghosts", on MC3 it affects the car refelection and color (sometimes the car is white instead of red). This issue with car color has been always present on my Mali 400MP4 device (Galaxy SII).

**Comment by GuilhermeGS2** [comment]
Some screenshots (Mali T720MP2):

https://ibb.co/doaE4b
Switching between different resolutions MC3:
https://ibb.co/cxRRHw
https://ibb.co/k5ALcw
https://ibb.co/mB42qG

**Comment by GuilhermeGS2** [comment]
I was wrong about non-buffer rendering, it happens too.

**Comment by hrydgard** [comment]
This is the issue I'm worried the most about, but I can't reproduce for the life of me. Suspecting broken shader caches, and I'm bumping the shader cache version for 1.5.3 going out tomorrow, let's see if that helps...

As for the Mali issues @GuilhermeGS2 is showing above, they need investigation but are probably not related to this issue.

**Comment by GuilhermeGS2** [comment]
Sorry then. As you guys said this shader issue is related to both mobile GPU I have, my issues began some weeks ago, and don't happen on PC, I thought it was something related.

**Comment by hrydgard** [comment]
I'm not 100% sure though :)

**Comment by unknownbrackets** [comment]
So, it turns out this may not be new, it was reported in v1.3.0.1 and v1.2.2 too, just with less games.

(Mali-400)
```
Error in shader program link: info: L0007 Varying 'v_texcoord' not found in vertex shader / fs: #version 100
precision lowp float;
uniform sampler2D tex;
 varying vec4 v_color0;
varying mediump vec2 v_texcoord;
void main() {
  vec4 t = texture2D(tex, v_texcoord);
  vec4 p = v_color0;
  vec4 v = p * t;
  v.rgb = v.rgb * vec3(v.a);
  v.a = v.a * 2.0;
  gl_FragColor = v;
}
 / vs: #version 100
precision highp float;
attribute vec3 position;
attribute lowp vec4 color0;
uniform mat4 u_proj;
uniform mat4 u_world;
uniform mat4 u_view;
uniform lowp vec4 u_matambientalpha;
varying lowp vec4 v_color0;
void main() {
  vec3 worldpos = (u_world * vec4(position.xyz, 1.0)).xyz;
  mediump vec3 worldnormal = vec3(0.0, 0.0, 1.0);
  vec4 viewPos = u_view * vec4(worldpos, 1.0);
  gl_Position = u_proj * viewPos;
  v_color0 = color0;
}
```

-[Unknown]

**Comment by hrydgard** [comment]
Huh. It's very weird, either way. Let's see if the new logging provides a clue after I release 1.5.3 tomorrow.

**Comment by unknownbrackets** [comment]
Still not gone, but here's more info:

```
Error in shader program link during preload: info: L0007 Fragment shader uses a varying v_color1 that has not been declared in the vertex shader.

fs: 01010000:0000091c LM 
#version 300 es
#extension GL_ARM_shader_framebuffer_fetch : require
precision lowp float;
 in vec4 v_color0;
 in vec3 v_color1;
out vec4 fragColor0;
void main() {
  vec4 s = vec4(v_color1, 0.0);
  vec4 v = v_color0  + s;
  fragColor0 = v;
}

vs: 00000000:00200002 THR 
#version 300 es
precision highp float;
in vec4 position;
in lowp vec4 color0;
uniform mat4 u_proj_through;
out lowp vec4 v_color0;
void main() {
  v_color0 = color0;
  gl_Position = u_proj_through * vec4(position.xyz, 1.0);
}
```

-[Unknown]

**Comment by unknownbrackets** [comment]
> vs: 00004000:00000022 THR

This is definitely an invalid ShaderID - bit 5 is set, even though this is a VSID.  There's no bit 5.  If it were a FSID, though, it would be `FS_BIT_DO_TEXTURE | FS_BIT_TEXALPHA | FS_BIT_FLATSHADE`, which is a very sane FSID.

> fs: 00000000:0000091c LM 

Also invalid, as an FSID.  Applying the same logic, though, if it were a VSID: `VS_BIT_ENABLE_FOG | VS_BIT_HAS_COLOR | VS_BIT_DO_TEXTURE | VS_BIT_USE_HW_TRANSFORM | VS_BIT_HAS_TEXCOORD`.

So my assessment: somewhere we're getting FS/VS ids backwards.  They'd be valid if they were swapped.

-[Unknown]

**Comment by unknownbrackets** [comment]
I think it's a bug in DenseHashMap's size() vs. TAKEN flags, maybe.  It would explain everything.

-[Unknown]

**Comment by hrydgard** [comment]
Huh! Nice digging! That would indeed explain it...

**Comment by unknownbrackets** [comment]
I think those will have fixed this - I'm gonna mark this as closed and will reopen if we get more reports.

These errors themselves aren't a big deal since it's only on preload, but the hashmap errors might cause other strangeness...

-[Unknown]
