### ISSUE TITLE
Reported attempts to texture from target

### ISSUE THREAD

**Issue by unknownbrackets** [hrydgard/ppsspp#10211]
http://report.ppsspp.org/logs/kind/922

https://github.com/hrydgard/ppsspp/blob/ac518f819a05478a16f73609b4cd6f4bb7afad60/GPU/Vulkan/FramebufferVulkan.cpp#L453

In theory, we should only be skipping the copy in cases where we're about to render somewhere else, and don't need a copy.  This may indicate we're not resetting the render framebuffer target properly for CLUT renders or something.

-[Unknown]

**Comment by hrydgard** [comment]
Strange. Tried a couple of games in that list and it doesn't happen, not even with post proc on.

**Comment by unknownbrackets** [comment]
It's happening in D3D11 as well.  So far we have a report, and it's using flags=7, which means BINDFBCOLOR_MAY_COPY (1) was set.

So that narrows it down: this happens when `g_Config.bDisableSlowFramebufEffects` is true, although it could also happen due to `GPUStepping::IsStepping()` (which in GLES doesn't need the copy since it will download the framebuffer - but in other backends I guess does.)

So this definitely isn't a regression, and maybe isn't a bug.  Maybe we should remove the reporting, at least when `bDisableSlowFramebufEffects` is true.

-[Unknown]

**Comment by hrydgard** [comment]
Still a bug that could be fixed, and I still can't seem to repro... but yeah not gonna worry too much about it.

**Comment by unknownbrackets** [comment]
Is it really a bug, though?  In this case, it's probably trying to use a depal shader, but because slow effects are disabled, it's not even doing that.

I think using input attachments would be interesting, but potentially still a slow effect (especially with the proper barriers?)

But I will say - Vulkan isn't setting SKIPDRAW_BAD_FB_TEXTURE, which it probably should.

But SKIPDRAW_BAD_FB_TEXTURE doesn't seem like it works the way I'd expect anyway.  If the last draw on the frame sets it, we may skip flipping, which doesn't really seem ideal.  It also doesn't really skip drawing (and can't, because we can't decide the value of the flag until setting the texture, which currently happens on flush.)

-[Unknown]

**Comment by hrydgard** [comment]
Hm, that's interesting, that should probably be fixed, maybe pass a special flag to FramebufferManagerVulkan::BindFramebufferAsColorTexture and friends to avoid skipping in the flip case.

**Comment by hrydgard** [comment]
Wait, that doesn't seem right. FramebufferCommon::CopyDisplayToOutput doesn't call FramebufferManagerWhatever::BindFramebufferColor when flipping, it calls thin3d directly and so will bypass that check?

**Comment by unknownbrackets** [comment]
Oh, I guess it only doesn't set it when binding, it still sets `reallyDirtyAfterDisplay` after the draw, right.  So then SKIPDRAW_BAD_FB_TEXTURE does nothing, I guess.

-[Unknown]

**Comment by Gamemulatorer** [comment]
This is related to disable slower effects graphics bug that recently remove?

**Comment by unknownbrackets** [comment]
Yeah, I think we can close this now - looks like this shouldn't happen anymore.

-[Unknown]
