### ISSUE TITLE
Text rendering: Line wrapping bugs with Thai language

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#10217]
Details in https://github.com/hrydgard/ppsspp-lang/issues/629 , making an issue here too so it's harder to miss as it's not a translation issue but a text rendering issue.

**Comment by hrydgard** [comment]
The first part of the problem (inadvertent extra line break) appeared in https://github.com/hrydgard/ppsspp/pull/9773 somewhere. As for the second part, that one's a bit baffling - Android only.

**Comment by unknownbrackets** [comment]
Sounds like we're not breaking it up by line there properly?

-[Unknown]

**Comment by hrydgard** [comment]
On Windows we don't need to, we just tell it to render the whole thing, lines and all. But on Android it seems to be different.
