### ISSUE TITLE
Syphon Filter Dark Mirror - lights are visible through buildings

### ISSUE THREAD

**Issue by Leopard20** [hrydgard/ppsspp#10229]
What happens?
You can see the sources of lights through buildings (e.g lamps, ground reflections, etc)
It's a minor issue and the game's perfectly playable. I was just wondering if you could improve it.

What *should* happen?
I'm not sure if the game's meant to be like this or not because I don't own an actual PSP. But I think it shouldn't be like this.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Android 7.0
GPU: Adreno 530
PPSSPP Build: 1.5.3

**Comment by unknownbrackets** [comment]
Does this happen in both Vulkan and OpenGL?  Does it also happen on a PC?

My guess is this is related to dual src alpha, but not sure.  I think there's a similar bug in another game which isn't, and might be depth related.

-[Unknown]

**Comment by leopard20** [comment]
Yes it happens on both backends.
I don't have the PC version installed. I'll install it and report later.

**Comment by leopard20** [comment]
Update: The issue also happens on the PC version:
![scr](https://user-images.githubusercontent.com/16115820/33556323-bc4339f0-d918-11e7-91ef-df2279113ef5.png)

**Comment by hrydgard** [comment]
Most likely the game is peeking at the depth buffer with the CPU, which is something we can't easily support (though in Vulkan now, we totally could have asynchronous download of the depth buffer every frame without too much slowdown, possibly... but probably wouldn't want that enabled for all games)

**Comment by leopard20** [comment]
Yeah, I totally understood that! 😉

**Comment by unknownbrackets** [comment]
Sorry, this is the one I meant to suggest a GE debugger dump on.  Commented on the wrong issue like a dope.

But yeah, could be the depth buffer... I think I had a temp branch which downloaded that on desktop GL, although it was buggy...

-[Unknown]

**Comment by leopard20** [comment]
Oh. Well in that case, here you are:
[UCUS98641_0001.zip](https://github.com/hrydgard/ppsspp/files/1527529/UCUS98641_0001.zip)

**Comment by leopard20** [comment]
@hrydgard , @unknownbrackets 
BTW, can you guys check out the new issue I submitted?
https://github.com/hrydgard/ppsspp/issues/10251

**Comment by benderscruffy01** [comment]
the same as #6105

**Comment by hrydgard** [comment]
Certainly a similar outcome, but I don't think these games work the same.

**Comment by unknownbrackets** [comment]
The lights are drawn at 4880/4946, with the only useful test being a `>=` depth test.  But the specified depth is 1, so I'm not sure why it wouldn't draw... it also shows these lights in the software renderer.

The dump also shows the same on a real PSP:
![UCUS98641_#10229_syphon_lights](https://user-images.githubusercontent.com/191233/54881215-f47d4280-4e0a-11e9-979d-b529390eed91.png)

A fresh dump (there have been improvements) might help, but it could be that some CPU work is uploading depth?  The dump won't catch this.  I don't think it's the same exact cause as the other indeed.

-[Unknown]

**Comment by MojoJojoDojo** [comment]
Also affects Resistance.

**Comment by oldmario** [comment]
don't know if it's worth mentioning or not so i'll post it here anyways.

someone did a texture pack on the forums for both games and one thing i noticed in the screenshots is when they have their textures enabled the lights don't show through the buildings 

https://forums.ppsspp.org/showthread.php?tid=28201&pid=142926#pid142926

**Comment by LunaMoo** [comment]
Didn't checked, but it's probably just using empty textures to get rid of those lights, you can see the screenshots with texture replacement active which have much darker light sources. Nothing related to the issue, just a partial workaround at the cost of darker game.

**Comment by Kayael76** [comment]
I made this pack and that's what I did, the lens-flare effect is just fully transparent.

**Comment by Gamemulatorer** [comment]
How about this now?
https://github.com/hrydgard/ppsspp/pull/15772 might help this.

**Comment by Gamemulatorer** [comment]
Using the ge dump issue can still reproduce.
Both hardware and software
![Screenshot_2022-08-03-08-56-29-605_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/182501525-99f0a8bd-b9aa-4bf2-b355-3e3d6fbd3a21.jpg)

**Comment by QrTa** [comment]
Syphon Filter Logan's Shadow have the same lens flare (through the walls) problem

![Screenshot_2022-08-30-22-45-49-643_org.ppsspp.ppsspp.jpg](https://user-images.githubusercontent.com/81707167/187540042-dd464b3a-f44d-4ea9-90b1-b9780981d477.jpg)

**Comment by Leyo1** [comment]
> Most likely the game is peeking at the depth buffer with the CPU to check whether to draw the flares, which is something we can't easily support (though in Vulkan now, we totally could have asynchronous download of the depth buffer every frame without too much slowdown, possibly... but probably wouldn't want that enabled for all games)

changing skip draw range to 1:3 solves this same issue in syphon filter on PCSX2, sadly PPSSPP doesn't have skip draw range

**Comment by hrydgard** [comment]
Light/flare occlusion is indeed done by peeking in the depth buffer, and it does work 100% correctly in the software renderer, possibly not from a framedump though?

#16907 fixes it for hardware rendering at the cost of an expensive readback.

**Comment by hrydgard** [comment]
An update, the new depth buffer software rasterization (#19748) solves this in a better way, removing the latency from the late readbacks that caused flicker before, and will also work on all backends. It also works with Logan's Shadow.
