### ISSUE TITLE
Switch Android build from gnustl to libc++

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#10227]
https://developer.android.com/ndk/guides/cpp-support.html

Since NDK r16, libc++ stl is now out of beta, and will be the default in r17 and deprecated in r18. We need to move at some point. Should probably not be too much of a hassle.

**Comment by unknownbrackets** [comment]
From that documentation - do we disable RTTI/exceptions in CMake, or are they enabled now in CMake Android builds?

-[Unknown]

**Comment by unknownbrackets** [comment]
This was done in #10371.

-[Unknown]
