### ISSUE TITLE
CPU core switching Is not working

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#10224]
I have same fps in all my games. But i think Dinarect JIT Is Faster than Interpreter, so why i don't see some changes?

**Comment by marosis** [comment]
OpenGL

**Comment by hrydgard** [comment]
Even when unthrottling speed? Otherwise that just means that your computer is fast enough to run in interpreter mode. Many PSP games are otherwise limited to 30fps or 60fps, some even as low as 20fps - you're not gonna get them to go faster by changing CPU emulation cores.

**Comment by leopard20** [comment]
@hrydgard 
Really? 20 FPS? Does that mean the 20 FPS I get on Metal Great Solid PW is normal? There's no choppy sound. But PPSSPP keeps telling me to turn on frameskipping.
Speaking of which, can I turn off these messages?

**Comment by unknownbrackets** [comment]
There's a setting to turn that off, but if you're getting that, it ought to mean something is wrong.

That said, I do think I've heard that game runs at 20 fps.  I think someone may have a cheat that makes it run at a higher FPS?

Are you getting that message even when it's at a consistent 20 fps?  It will only show it once per start of PPSSPP, and is supposed to only show it when you're getting worse than actual game speed.  It was added because not everyone even realized they weren't getting proper speed (it just felt "weird" and there were audio glitches.)

-[Unknown]

**Comment by leopard20** [comment]
I only get it once per start of the game, as you said. But yeah my FPS is constantly @ 20, except in FMV videos and in the menu (mother base) where it's 30.
Did you say I can turn it off? How?

**Comment by marosis** [comment]
No i using android

**Comment by marosis** [comment]
And running games 10~30fps

**Comment by hrydgard** [comment]
The message is definitely a little too sensitive, I get it sometimes even when things look and sound like it's running perfectly well, maybe except for some shader loading stutters.

**Comment by marosis** [comment]
I found this problem. You can't switch CPU core when you playing game. You must switch And restart game for working right

**Comment by unknownbrackets** [comment]
Darn, that used to work just fine.

-[Unknown]

**Comment by leopard20** [comment]
@hrydgard 
Do you mind answering my question please? The one about PoP and disabling messages. I think you didn't see it.

**Comment by hrydgard** [comment]
@leopard20 You can turn it off by setting "HideSlowWarnings = True" under [CPU] in PSP/SYSTEM/ppsspp.ini. 

20 fps is normal in Metal Gear Solid Peace Walker, it doesn't go any faster without hacks - but if it's a solid 20, you should not get the message. If you do that's a bug.

**Comment by Sunil2735** [comment]
This cheat file may help you a lot to get 30 fps and if you have a powerful device you can also get 60 fps. :) Let me know if it works for u.

**Comment by Sunil2735** [comment]
https://forums.ppsspp.org/showthread.php?tid=4799

**Comment by leopard20** [comment]
@Sunil2735 
Thanks! I got a variable FPS from 55 to 60 but it was nice! 
I'm now using the 30FPS cheat. I don't know why 60 FPS just felt wrong with this game! For example the first cutscene plays too fast!  Kinda messes with the music and the game's atmosphere! ,😉
