### ISSUE TITLE
version 1.5.3-7 crashes

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#10233]
In latest version are crashes (Crash on GOD OF WAR when i switched frameskip to 1) in 1.5.2 was All ok

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

**Comment by unknownbrackets** [comment]
Didn't test enough after the assert, #10232 should fix this and potentially other issues.

-[Unknown]

**Comment by marosis** [comment]
+ new problem what i hadn't https://photos.app.goo.gl/ZR9jwTHGz7GmP2Pw2

**Comment by brujo5** [comment]
Same here .
Games crashes when in game

**Comment by marosis** [comment]
Yeah crashing fixed
