### ISSUE TITLE
F1 Grand Prix - PrehashMap problem on 1.5.3-17

### ISSUE THREAD

**Issue by Robsoie** [hrydgard/ppsspp#10237]
Using ppsspp-v1.5.3-17-gb79525846-windows-x86 , in D3D9

In the middle of a race , the game stop with a window saying 

PrehashMap : Hit full on Get(

(clicking "OK" only lead into the same window appearing again and again)
It was on the 3rd turn, for some reason this didn't happened at all on the first 2 ones

**Comment by unknownbrackets** [comment]
Does it stop happening if you disable vertex cache?

-[Unknown]

**Comment by ppmeis** [comment]
Tested with latest build, Direct3D9 vertex cache disabled, no crash:
![image](https://user-images.githubusercontent.com/4381277/33525243-154849d4-d82c-11e7-8471-e6b0e1013ed1.png)

**Comment by Robsoie** [comment]
I confirm with vertex cache turned off, it seems the problem does not happen anymore, as i just did 3 grand prix in a row without a problem.

For the texture reflection becoming broken reported by ppmeis , it has always happened to me on any ppsspp version, i never reported it before because i have never been able to make a reproduction case.
I have been able to run a full grand prix without it happening, i have ran full grand prix in which it was there from the start and even ran some grand prix in which the problem only happened at +/- mid circuit, all in same ppsspp versions.

**Comment by unknownbrackets** [comment]
Hmm, that reminds me of #4199.

If you use the latest build, does it work even with vertex cache on?  It should now.  That said, I recommend using Vulkan with the vertex cache off.

Does this color bug happen only when the vertex cache is off, or it happens in both cases?

-[Unknown]

**Comment by Robsoie** [comment]
I had it always happen as i posted before (and always had vertex cache enabled) and when i did my 3 grand prix to test with cache vertex enabled it happened on the 2nd grand prix, roughly mid-circuit.

I'll give a try when there will be a newer build as the latest isn't available for download as i write this.

**Comment by unknownbrackets** [comment]
#10238 may have fixed the crash issue.  Can you report the other bug as a separate GitHub issue, since it doesn't seem to have the same cause?  It will be interesting if hardware transform or vertex cache effect that bug...

Back to this bug - does the Prehashmap crash still happen, even with vertex cache enabled?

-[Unknown]

**Comment by Robsoie** [comment]
I have downloaded ppsspp-v1.5.3-50-gab95dcae9-windows-x86.7z and did 4 quick grand prix to their fullest.
I didn't observed the bug anymore (with default setting, so vertex cache is enabled) 

It seems fixed, thank you for your work.
I'll open a report for the reflection/damage texture bug with screenshots when i'll have more time later today.

**Comment by unknownbrackets** [comment]
Awesome, thanks.

-[Unknown]
