### ISSUE TITLE
Ppsspp crash when change display resolution (HW scaler) (vulkan) 

### ISSUE THREAD

**Issue by brujo5** [hrydgard/ppsspp#10244]
Ppsspp crash when change display resolution (HW scaler) (vulkan) 
Also when I hit  exit button the emulator show message  ppsspp stopped 
 
Edite 
Multitask broken again. Ppsspp can't run in background 

Tested in galaxy s6

**Comment by unknownbrackets** [comment]
I can repro, only with Vulkan.  It's also a recent regression - it worked sometime before 1.5.0.

-[Unknown]

**Comment by brujo5** [comment]
Sorry for delay. Fixed thx
