### ISSUE TITLE
N.O.V.A fps drops

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#10256]
Near Orbit Vanguard Aliance have fps drops 20/20-> 7-13/20 on my android device (OpenGL). When it Is dropped fps, I must set from Buffered rendering to non-buffered Rendering for stable 20/20 but later i have same fps drop in non-buffered Rendering and i must switch to Buffered rendering. ONLY in zone with graphics effects like shooting or something like that.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

**Comment by hrydgard** [comment]
Probably the game is drawing a bit more than normal. Performance is not something we usually fix for certain spots, except in very special cases. Expect further improvements in the future but for now, use autoframeskip or something in that area.

**Comment by unknownbrackets** [comment]
There was some issue before about this game using a lot of VRAM.  It sounds like forcing some cache to clear is helping.

-[Unknown]

**Comment by marosis** [comment]
I think same

**Comment by unknownbrackets** [comment]
See also #5351.  We did fix SOME memory leak back then...

-[Unknown]

**Comment by marosis** [comment]
Ok
