### ISSUE TITLE
Naruto Heroes 3 stopped emulating from this version 1.4.0 and so far no strange solution

### ISSUE THREAD

**Issue by SamueldeSena** [hrydgard/ppsspp#10257]
In version 1.2.2 the game Naruto Heroes 3 takes but after 1.4.0 it stopped getting both OpenGL and Vulkan the first image and version 1.2.2 and the second of the current build does not show this image ives black in any type of configuration but if I use a save state it normally runs this and it      ![screenshot_20171204-200136](https://user-images.githubusercontent.com/34135636/33582158-a659b5e6-d932-11e7-9233-4808d35ac1b9.png)
![screenshot_20171204-213413](https://user-images.githubusercontent.com/34135636/33582293-479e7d06-d933-11e7-8f9f-f8247f9ee8b4.png)

**Comment by SamueldeSena** [comment]
I have already found the build that caused the black screen in build v1.3-31-gb3a7c0e67 the game is emulator normally but already in build v1.3-37-g8b5693b4d happens that black splat error at the time of the screen cyberconnect2 then it should have stayed longer easy to find the problem

**Comment by unknownbrackets** [comment]
Okay, so then it's probably #9014.  I guess that means the CyberConnect2 logo is part of a video.

It might be parsing corruption like the change in #8867 was designed to fix...

-[Unknown]

**Comment by SamueldeSena** [comment]
When this problem will be solved

**Comment by SamueldeSena** [comment]
Please when could this problem be solved?

**Comment by ppmeis** [comment]
@SamueldeSena just don't ask when this game will be fixed. You will be noticed here. Also, please be a bit more clear with your report next time (correct game Title, region, platform, device...) 

About the error, tested with latest Windows build, Vulkan and OpenGL default settings. Blackscreen after a few logo videos.

InfoLog and DebugLog:
[logs.zip](https://github.com/hrydgard/ppsspp/files/1555124/logs.zip)
