### ISSUE TITLE
F1 Grand Prix cars sometime recieve broken reflection texture

### ISSUE THREAD

**Issue by Robsoie** [hrydgard/ppsspp#10255]
In F1 Grand Prix sometime cars recieve visually broken reflection textures.
Once the problem start to happen  (all the cars at gameplay time are affected, not just yours), restarting the same grand prix lead into previously normal looking texture starting with the broken reflection

example when it works 
https://i.imgur.com/bmSh7db.jpg

example after restarting same race after the problem started to appear mid-race
https://i.imgur.com/k01mTyP.jpg

The problem there is also how to reproduce, as it's possible to complete a whole grand prix with the texture being normal for the whole time, but sometime the problem happen only a few seconds after starting, or a long time after starting, etc... i have not been able to figure out a reproduction case unfortunately.

The sure thing is that when you see the texture becoming broken, the same happens to every single cars on the circuit too, not only the player's one.

**Comment by ppmeis** [comment]
Tested with latest build, default settings OpenGL no issues:

![image](https://user-images.githubusercontent.com/4381277/33578336-8469bcf6-d946-11e7-86c7-b604cd84def8.png)

Same on Vulkan:
![image](https://user-images.githubusercontent.com/4381277/33579104-e99d950a-d948-11e7-8deb-e8aea3c777b7.png)

Also, I notice reflection is "strange", I mean, look at the images below, it's more like a "transparent" effect than a reflection:
![image](https://user-images.githubusercontent.com/4381277/33578459-e6873972-d946-11e7-9bf4-708863160de9.png)
Look at the starting blocks (this mark is under the car, not ON the car):
![image](https://user-images.githubusercontent.com/4381277/33578516-1e86eb10-d947-11e7-8892-5217881b01b4.png)

**Comment by unknownbrackets** [comment]
From previous similar issues, this could be a driver bug - or something we're doing wrong that only goes wrong on certain drivers.

It seems like the vertices are wrong.  In #4199, I think it helped to turn off hardware transform (even though it made it slower.)  Does that help here?

If this happens on Vulkan and OpenGL, that's very interesting, since they push vertices in a very different way...

-[Unknown]

**Comment by Robsoie** [comment]
On D3D9 i disabled hardware transform and still on some test race after a couple of minute the reflections went wrong
https://i.imgur.com/jERjKmD.jpg

And that said, something that never bothered me before (due to how fast the game is i was always paying more attention to the road and opponents than to my own car visuals) , but looking more closely to my cars while testing settings for this report made me noticed 
In D3D9 the reflection , even when they don't go buggy, are wrong by default, first check the car front , the texture is normal but there something missing
https://i.imgur.com/KkQrS60.jpg

Comparing with the same roughly view but in OpenGL, notice on the front of the car the reflection that works and display as expected the environment (the trees in that case)
https://i.imgur.com/FcnPf66.jpg

Maybe it's D3D9 having trouble with the reflection that lead later the game to display them finally totally wrong (with the garbled coloring stuff) ?

**Comment by AoManz** [comment]
tHIS HAPPEN FOR ME TOO

look
![image](https://user-images.githubusercontent.com/34289381/33637726-93412f32-da1a-11e7-96e8-16a74475040f.png)

**Comment by unknownbrackets** [comment]
Could you try exporting a GE frame dump?  These help a lot.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by ppmeis** [comment]
I think shadows and reflections are broken in Direct3D9:

No shadows or reflections:
![image](https://user-images.githubusercontent.com/4381277/49368152-4b40fe00-f6ee-11e8-808b-ca57e9a34729.png)
[DUMP.zip](https://github.com/hrydgard/ppsspp/files/2639042/DUMP.zip)


Vulkan looks fine:
![image](https://user-images.githubusercontent.com/4381277/49368254-7fb4ba00-f6ee-11e8-86e2-e84ecb1e39cc.png)

**Comment by unknownbrackets** [comment]
The shadows and reflections seem to render correctly in those frame dumps within Direct3D 9 now.  I suspect this is a bug that has since been fixed.  Closing as such.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
