### ISSUE TITLE
Replacement of textures with mipmaps cause validation errors in Vulkan

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#10259]
When running in debug mode, the validation layers trigger on texture upload, seems we upload the wrong size. Should not ship with this.

**Comment by hrydgard** [comment]
Ah, this turns out to be when mipmaps are specified that are the wrong size.

**Comment by unknownbrackets** [comment]
Ah, I probably just assumed people would use the right sizes... d'oh.

-[Unknown]

**Comment by hrydgard** [comment]
They tend to link all the mips to the top level texture :(

Should just generate mipmaps ourselves if they are wrong or missing.
