### ISSUE TITLE
PD Extend - Controls don't work after character swap

### ISSUE THREAD

**Issue by leopard20** [hrydgard/ppsspp#10251]
*What happens?*
**Project Diva Extend**: When I swap the characters (in Character Selection menu when you press the Triangle button), the controls become unresponsive.

OS: Android and Windows

**Comment by zllIJudgeIllz** [comment]
![image](https://user-images.githubusercontent.com/34289935/33638586-c751db92-da1e-11e7-80f1-e2c4a7ca1401.png)

**Comment by SamueldeSena** [comment]
This usually occurs when the game is loading the elements soon after and cutsene so it is practically normal for the buttons to crash during that period. This topic may now be closed

**Comment by leopard20** [comment]
Well, this issue doesn't occur on the PC version. There must be some nested bad code in there!
I don't think it's too hard to fix. Though I don't know how you simulate the touch keys. But if you only simulate key presses similar to the PC version there shouldn't be any issue.

**Comment by unknownbrackets** [comment]
Does it happen on PC when using touch controls only?

-[Unknown]

**Comment by leopard20** [comment]
@unknownbrackets 
No. No issue on the PC version if I enable on-screen controls and drag the analog stick using mouse.

Can you reproduce the issue on your phone? I've uploaded the saved state so it shouldn't take long. If you don't have the iso, download if from EmuParadise. It's only 700 MBs.

**Comment by leopard20** [comment]
@hrydgard @unknownbrackets 
Same issue in Project Diva Extend.
When I swap the characters (in Character Select when you press the Triangle button), the controls become unresponsive.
No issue on PC.

**Comment by hrydgard** [comment]
This is not one of those custom-rom-features-messing-up-multitouch things, is it?

**Comment by leopard20** [comment]
Nope! Tested it again after disabling that option.

If you have the game you could try it yourself. If not you can download it for free! (it's for testing purposes so it's not ethically wrong 😉)

**Comment by unknownbrackets** [comment]
I don't have either of those games, but I can't reproduce on my phone with other games that play videos, even with lazy texture caching.

Since a graphics setting effects it - does Vulkan vs. OpenGL matter?

Are there any other games (especially demos, or for my purposes RPGs which is what I mostly have) that reproduce this?

Does this reproduce in 1.5.4?  Can you find the first git build it starts in if not (this might not find a useful commit, but that would at least confirm if it's uninitialized memory)?

-[Unknown]

**Comment by leopard20** [comment]
Well, I didn't say it happens in all games, just those two (def jam had a tiny issue too, but it was different and probably a bug in the game)

No, both of these issues occur irrespective of the selected backend.

Unfortunately, the only RPG game I have is MHFU. And it doesn't have this issue.

Yes, v1.5.4 has the same problem.

**Comment by hrydgard** [comment]
In that case I'm gonna move this to 1.7, no idea how to get to the bottom of it...

**Comment by unknownbrackets** [comment]
Does even like 1.3.0 or 1.0.1 have the same issue?  If we can find when it started we might be able to fix it.

-[Unknown]

**Comment by leopard20** [comment]
I think the PoP issue might've been an old one passed down because of savestates (I haven't played this game since v1.4.2 with which I saved that state), because after doing the following steps I couldn't reproduce it anymore:
1. Turned off lazy texture caching.
2. Saved the state.
3. Loaded the state, but turned lazy texture caching back on.
4. Can pass the cutscene now.
Sorry for not thinking of that before.

The issue in PD Extend still stands though (I don't use save states or lazy texture caching in that game). But I'll try some older versions to see if I can find a version that plays fine.
Here's a video from PD Extend, just so you know what to look for if you ever get the game:
[Miku.mp4.zip](https://github.com/hrydgard/ppsspp/files/1910719/Miku.mp4.zip)

**Comment by leopard20** [comment]
Same issue on Windows.

**Comment by leopard20** [comment]
Yes. It was caused by a 60 FPS cheat code. I modified it slightly to switch to 30 FPS when the characters are being swapped, then switch back to 60 FPS. Now it's fixed.

**Comment by leopard20** [comment]
@hrydgard 
Can I ask a question? The Refresh Rate in cheats is actually a "rate" right, not an interval? (as in the higher the rate the more the number of refreshes) 
Can setting the refresh rate too high cause more CPU consumption?
