### ISSUE TITLE
vulkan option cannot appear

### ISSUE THREAD

**Issue by fahadfoyjur** [hrydgard/ppsspp#10359]
Hello ,
Latest version of ppsspp vulkan option not appear only open gl ,  
and multithread option not here ?

**Comment by hrydgard** [comment]
If there's a Vulkan driver on your device, it will show. I'm guessing yours doesn't have one.

Multithreading is gone because it worked badly and made the code hard to maintain. I'm planning a new better multithreading mode for GL but it's not gonna happen very soon unfortunately.

**Comment by leopard20** [comment]
I'm assuming you're talking about the android version right?
If so it's because of one of two things:
1. GPU doesn't support Vulkan.
2. Even if your GPU supports Vulkan, you need to have Android 7.0 and above (API level 24 and above) for it to work.

**Comment by fahadfoyjur** [comment]
Thanks hrydgard sir
