### ISSUE TITLE
Postprocessing shaders don't work with GL Core contexts (affects mac, windows, linux?)

### ISSUE THREAD

**Issue by thedax** [hrydgard/ppsspp#10362]
What happens?

When you select any postprocessing shader from the graphics options, the shader will not apply and instead spit this error message out to the Terminal:

```
E[FRAMEBUF]: GLES/FramebufferManagerGLES Failed to build post-processing program from shaders/natural.vsh and shaders/natural.fsh!
ERROR: 0:1: '' :  #version required and missing.
ERROR: 0:3: 'attribute' : syntax error: syntax error
```

Steps to reproduce:
1. Start a game
2. Go to the pause menu -> settings -> graphics -> post processing shaders -> pick any (I used Natural Colors in this test)

What *should* happen?

The shader should run correctly and change the graphics as desired.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

It's a hackintosh, but the GPU is fully supported by the Nvidia Web Drivers.

CPU: Intel i7 5930k @ 3.5GHz
GPU: Nvidia Geforce GTX 970 4GB
Driver: Nvidia Web Driver 378.10.10.10.20.109
PPSSPP version: 1.5.4-23-g3b7868767

The offending commit appears to be https://github.com/hrydgard/ppsspp/commit/e3eb6d36b16506f8c7cc5c6de613cf246499c4d6. The one prior to that (https://github.com/hrydgard/ppsspp/commit/9a732fe52eb25ce92f0289f08d86bd4ca648fdd2), as well as v1.5.4 release/stable and v1.5.3 stable do not exhibit this behaviour.

**Comment by hrydgard** [comment]
Yeah, expected some issues, had to merge to discover the last ones like this :)

@unknownbrackets  should probably do something similar here to what I do for Vulkan, replace attribute with in etc.

**Comment by unknownbrackets** [comment]
What if a shader already had a `#version`?  If I recall, Mac drivers were very picky and wanted the exact same version.

I think NVIDIA drivers on Windows didn't care much whether the shader was the exact GLSL version corresponding with the profile.

-[Unknown]
