### ISSUE TITLE
Vulkan Renderer Minor Bug

### ISSUE THREAD

**Issue by M220** [hrydgard/ppsspp#10365]
If you try to change the display resoluation while your renderer is vulkan and you are ingame , that will force emulator to Stop on Android
OS : Android
PPSSPP Version : 1.5.4 Official
Device : Galaxy S6
GPU : Mali
This bug isn't exist in OpenGL renderer 
If you want I can search and find the exact version to find the version that this bug appeared :)
Thank you for your Awesome Emulator :D 
EDIT : in newer versions this problem partially fixed , it's now don't force stop right at that moment but force stop when you hit the "Back" button ( test version 1.5.4-60- )

**Comment by unknownbrackets** [comment]
If you're able to find the version where it started, that'd help.

This doesn't happen to me on a Pixel with the latest git build.  Does it happen for you in all games?

Does it crash as soon as you change the resolution, or only once you resume the game?

-[Unknown]

**Comment by M220** [comment]
@unknownbrackets 
Version that doesn't have bug : 1.5.2-49-
Version that Does have bug : 1.5.3-7- ( Can't download 1.5.3 because of server problems ) ( in this version bug is different but still there : 
In this version ( 1.5.3-7- ) when you change Display Resolution ( ingame ) and than press back button , Emulator Doesn't Stop but when you try to go ingame after that , emulator will stop working.
So the bug is somewhere between this commits but cause there isn't any builds between this commits ( as before said , 1.5.3 cannot be downloaded so doesn't count that 😄 ) I Can't Say for Sure what is the exact version that this bug appeared
- Does it happen for you in all games?
Yes :) 
- Dles it Crash as soon as you change the resolution, or only once resume the games?
Different types of bug in different builds :)
For example in latest version it happens when you hit "Back" button but in i think 1.5.4-45(4*?) Build , it will stop right after you change resolution , and in 1.5.3-7- ... i said that :D 
Hope this will be helpfull

**Comment by unknownbrackets** [comment]
I think we made some changes here - is it working any better?

-[Unknown]

**Comment by M220** [comment]
No, it's the same on the latest dev version ( 1.5.4-591 )

**Comment by hrydgard** [comment]
Related fixes have been made, just tried this and it works just fine. Please reopen if it doesn't for you.
