### ISSUE TITLE
Black screen on menu of Burnout Legends S7Edge Exnyos

### ISSUE THREAD

**Issue by c0manche** [hrydgard/ppsspp#10361]
What happens?

Screen is black on startup of  Burnout legends using vulkan renderer (renders fine using opengl back end).

Bug first appeared in 1.5.3 was fine in 1.5.2 same bug is pressent in the new 1.5.4

What *should* happen?

VIdeo should play with menus overlayed

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

Samsung Galaxy S7Edge (SM-G935F) Exnyos version Mali-T880 vulkan driver version 212.131.1927

**Comment by unknownbrackets** [comment]
So that would implicate:
https://github.com/hrydgard/ppsspp/compare/v1.5.2...v1.5.3

Not seeing anything specific, though...

This happens even with default settings, right (slow effects enabled, buffered rendering enabled)?

-[Unknown]

**Comment by c0manche** [comment]
Yes with settings at default buffered rendering slow effects are enabled etc.

was working fine in in all versions going back from 1.5.2 to before in the experimental vulkan supporting 1.4 series bug first appeared for me in 1.5.3

**Comment by unknownbrackets** [comment]
Can you try git builds after 1.5.2 but before 1.5.3?

-[Unknown]

**Comment by VictorRosaB** [comment]
Was working in the version 1.5.2-49. Bug first appeared  in 1.5.3

**Comment by unknownbrackets** [comment]
That's strange.  There weren't really any code changes in v1.5.3 that weren't in v1.5.2-49-g734d9c494.  Only two differences: two language files were updated, and the version numbers were updated.

-[Unknown]

**Comment by VictorRosaB** [comment]
I tried downloading 1.5.3 to test one more time but i can't, the page keep giving me a error. So i downloaded 1.5.3-7, and it's working perfectly. So i started downloading every build after that. Till 1.5.3-50 was working perfectly. 1.5.3-52, there you have it. the bug.

**Comment by VictorRosaB** [comment]
1.5.3-51   Disable "Accurate Depth" in Burnout games, they have trouble with it on Mali (Z-fighting...)     Could be related to this?

**Comment by hrydgard** [comment]
Oh yeah, that'll be it. Older Mali drivers have problems without Accurate Depth, but the setting causes other glitches on the S8 generation of Mali GPUs so I turned it off. Sigh. That one's been reported to ARM for investigation.  I guess it'll have to be a driver version check then...

**Comment by hrydgard** [comment]
@c0manche please report the Vulkan driver version of your device so I can get the check right. Can be found in settings/tools/system information in PPSSPP.

**Comment by VictorRosaB** [comment]
Device Galaxy A5 2017, mali t830mp3 exynos 7880. 
Api Vulkan, Driver version: 428.43.2674 (6b32ba72)      
That will be it?

**Comment by hrydgard** [comment]
Yup, that's it, thanks! Seems it was broken for longer than I thought.  It's fixed in 482.381.3347 on my device so it doesn't happen there. I'll change the check to match your device.

**Comment by c0manche** [comment]
Sure

Device Galaxy S7 Edge SM-G935F Mali T-880
driver version 212.131.1927 (35183787)

**Comment by VictorRosaB** [comment]
Tested v1.5.4-63, now it's working. 
Thanks hrydgard

**Comment by c0manche** [comment]
@hrydgard 
Tested 1.5.4-66, all working fine now
Thanks a lot.
