### ISSUE TITLE
Problems with Control Layout Settings v1.5.4-19-gcf5ede493 and Later Builds (Android)

### ISSUE THREAD

**Issue by 66Muramasa** [hrydgard/ppsspp#10360]
Whenever I start a game in PPSSPP v1.5.4-19-gcf5ede493, the control layout reverts to the default.  However, when I go to the settings to make changes, it was back to the way it was before reverting to the default control layout without me making any further changes.  The layout sticks until I restart PPSSPP.

Build v1.5.4-9-ge3eb6d36b doesn't have this issue.  I'm running this on a OnePlus 5, if that helps.  Thanks.

**Comment by marosis** [comment]
Yes i have same problem.

**Comment by hrydgard** [comment]
That is really weird. Does this happen to other settings or only controls?

**Comment by 66Muramasa** [comment]
The issue only occurs with the control layout.  All of the other settings are fine.

**Comment by 66Muramasa** [comment]
The issue still persists with the latest build v1.5.4-23-g3b7868767.

**Comment by hrydgard** [comment]
So if it works with 9 but not with 19, the only possible culprit is #10247 . @unknownbrackets , any ideas? I don't see anything...

**Comment by unknownbrackets** [comment]
Hmm, unless that's a mistake (-9) and it's actually from the UI event centralization?  Not sure...

-[Unknown]

**Comment by LunaMoo** [comment]
Seems to still be reading config from ppsspp.ini for touch controls layout when booting a game while using per-game settings. Can easily reproduce on pc so it's not platform specific.

**Comment by hrydgard** [comment]
I just tried to repro and I failed. I did this:

  * Enable touch controls, move the controls around a bit
  * Start a game. The controls are still in the moved positions
  * Exit the game and start it again. Controls are still in the moved positions, as expected.
  * Exit the emulator and start it again. Still works.

Any idea what I'm missing?

**Comment by LunaMoo** [comment]
Create a game config if you tried on a game without one. At least that's the way I can reproduce it, if per-game config differs from standard one, it should be pretty clear that it doesn't load correct config on boot, but only for touch controls which is weird.

**Comment by hrydgard** [comment]
Tried that, can't get it to happen...

**Comment by hrydgard** [comment]
OK, it's got nothing with config loading. It's just that now the button views get created *before* the game config is loaded instead of after. I'll see if I can change that easily..

**Comment by hrydgard** [comment]
Did a quickfix but it's not great as you can see the controls move :)  @unknownbrackets this is a bit of a tricky one - or should we just hide the buttons until boot is done?

**Comment by 66Muramasa** [comment]
Just to let you know: I have custom configs created for all of the games I have on PPSSPP.

**Comment by hrydgard** [comment]
@66Muramasa Alright, but I've figured out what the problem is, and it should work for you in the latest build (26), although you'll see the buttons move.

**Comment by 66Muramasa** [comment]
Thanks.  I'll try the latest build then.

**Comment by 66Muramasa** [comment]
I do notice the buttons moving from the default positions to where my configs place them for a fraction of a second.  No big deal, though.  Thanks, and keep up the good work.

**Comment by unknownbrackets** [comment]
@hrydgard maybe we could use `NativeMessageReceived` in the per-game reload, which might be a little faster (because it would happen before loading shaders, at least.)

We could also hide the controls until the game finishes loading...

-[Unknown]
