### ISSUE TITLE
serious error in api vulkan vv1.5.4-40-g6e3cb0cd4 and a gold v1.5.4

### ISSUE THREAD

**Issue by SamueldeSena** [hrydgard/ppsspp#10377]
for some reason after a message appears talking about memory of full video the textures of the games comesa to bugar to be black or quandrados black I do not know what is exactly but an error in vulkan

my cell is an
adreno 502
octa core 2 Ghz
3 of ram
snapdragon 625

**Comment by unknownbrackets** [comment]
This most likely means you're upscaling / render resolution settings are too high.  If you run out of memory, it's a problem.  We're trying to keep the game from crashing, but black textures are expected.

What games does this happen during?
Are you using an HD texture pack?
What settings are you using?
Have you tried closing all other apps?

Your 3GB of memory is shared between any open apps, PPSSPP, and your graphics drivers.  Using high upscaling settings can quickly consume all of that.

-[Unknown]

**Comment by SamueldeSena** [comment]
I do not use upscaling I've tried everything else but nothing works

**Comment by SamueldeSena** [comment]
![screenshot_20171207-171008](https://user-images.githubusercontent.com/34135636/33800072-ecece31e-dd17-11e7-8b90-cca771b14e78.png)

**Comment by unknownbrackets** [comment]
Have you applied all system updates on your phone?  It's possible it has a buggy Vulkan driver.

-[Unknown]

**Comment by 66Muramasa** [comment]
What is your device's make and model?  I ran Guilty Gear Accent Core on my OnePlus 5 the other day without these graphical issues on Vulkan.
![screenshot_20171207-232641](https://user-images.githubusercontent.com/33438850/33802341-77a0698c-dd3a-11e7-9de6-d6c2f40d56e6.jpg)

**Comment by SamueldeSena** [comment]
this problem does not happen immediately you have to play for at least 1 hour to get started but what your configuacao

**Comment by Tomo12** [comment]
I would also like to chime in. Video memory full message appears on Jeanne DArc. In my case, during the Neufchateau stage, when Jean and Bertrand join the party. Battle is started, 12 turns to go, and the game displays the dreaded video memory full message at around turn 6 to 8. Happens sooner if I rotate the camera more often. First thing that goes haywire is the background ( goes black ). Sometimes, same thing happens at the end of stage, when that NPC jumps off the cliff.

Tested a couple of times, fresh PPSSPP start, save state loaded from the beginning of stage.

Playing the game on Redmi Note 3 PRO, Snapdragon 650, Adreno 510, LineageOS.

PPSSPP settings are fully default, besides being set to Vulkan, 1x rendering 2x display resolution.

**Comment by SamueldeSena** [comment]
the build v1.5.4-111-gc55847a79 has already corrected my black texture problem this topic can already be closed and thanks hrydgard for being running those kind of error and remember and I will always be reporting vulkan problems here in github

**Comment by unknownbrackets** [comment]
It sounds like this may be working better now - are we good to close it for 1.6.0?

-[Unknown]

**Comment by unknownbrackets** [comment]
Going to close - please comment if that's wrong.

-[Unknown]
