### ISSUE TITLE
Windows installer: cosmetic fix

### ISSUE THREAD

**Issue by TotalCaesar659** [hrydgard/ppsspp#10370]
What happens?

CCleaner shows the name of the program as "PPSSPP version 1.5.4", but there is already version number in it's separate right column.
![1](https://user-images.githubusercontent.com/14265316/33724886-b6662c34-db81-11e7-8390-9e76ec87c28f.png)

What *should* happen?

You can remove "version 1.5.4" from the name and set "PPSSPP" only.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

Windows 10 64-bit, PPSSPP 1.5.4 (installer).

**Comment by hrydgard** [comment]
Now you're just nitpicking :)

**Comment by TotalCaesar659** [comment]
Haha, sorry, but perfectionist inside of me is very angry :-) And there is no need to update two labels istead of one.

**Comment by hrydgard** [comment]
it's completely automated anyway so it's not extra work :) so pretty low priority, but I'll leave it open.
