### ISSUE TITLE
Emulation reset crash

### ISSUE THREAD

**Issue by LunaMoo** [hrydgard/ppsspp#10383]
Starting from #10378 as in the title, resetting emulation crashes PPSSPP, easy to reproduce launch any game(custom config or not doesn't matter), press ctrl+B or reset from menu.

**Comment by hrydgard** [comment]
Ugh, it's a double lock of the pendingMutex for messages in NativeApp.cpp. NativeUpdate ends up sending a message that eventually ends up sending another message. Hm.
