### ISSUE TITLE
Add Samba share support

### ISSUE THREAD

**Issue by gabriellluz** [hrydgard/ppsspp#10384]
What happens?
Right now, PPSSPP cannot load ISOs over LAN network. At least I can't do this.

What *should* happen?
We should be able to load isos over the LAN with SMB (Samba) support.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Android 7.1

**Comment by unknownbrackets** [comment]
I'm not sure how SMB works on Android, or if it has to be done manually by the app.

That said, in case you're not aware, there is a feature to read ISOs from http:// via LAN.  It should work with any standard webserver (apache, nginx, lighttpd, IIS, etc.) as long as it supports byte range requests.

You can also run PPSSPP on the other end and start an internal webserver.

-[Unknown]
