### ISSUE TITLE
Display layout and touch controls layout screens break when resizing window

### ISSUE THREAD

**Issue by LunaMoo** [hrydgard/ppsspp#10396]
Possibly affects only windows. Just alt+enter while in one of those screens to reproduce, sometimes it might work, but probably only when quickly returning back to same size. 

In the past I remember fixing it with: https://github.com/hrydgard/ppsspp/blob/ab95dcae91056241a561058e5434795d5946c50b/Windows/MainWindow.cpp#L282
which is still there and is called, but doesn't really do much?

It was broken by:
https://github.com/hrydgard/ppsspp/commit/900539e200ac6fc5fd9935d4ede984e34f6d9600
that was supposedly fixing similar/same problem for touch controls on linux, guess linux and windows doesn't like cooperating much.

**Comment by unknownbrackets** [comment]
Reopening just because this is probably still a race condition.  See #10397.

-[Unknown]
