### ISSUE TITLE
The latest version of ppsspp doesn't show on iOS.

### ISSUE THREAD

**Issue by iOS4all** [hrydgard/ppsspp#10399]
Hi there I noticed the latest version of ppsspp doesn't show on the version above when you launch the app it's just showing the previous version 1.4 not 1.5
Please help and give an iOS port some love.
Thanks a lot....

**Comment by hrydgard** [comment]
If Apple would show me love, like letting me put the emulator on the App Store or at least making JIT stuff and memory maps a bit less limited and crazy, I'd give the iOS port more love :P

**Comment by iOS4all** [comment]
You know apple doesn't like emulators on their AppStore. So that's why we're doing jailbreak.
Cydia store similar to AppStore.
Anyway isn't there any solution for iOS not getting the latest build of ppsspp?
Don't forget you promise if you have a free time or next major update to work on Metal api as vulkan for iOS.

**Comment by unknownbrackets** [comment]
Looks like the builds are here:
https://build.ppsspp.org/?page/downloads

As noted, it's not well supported on iOS - potentially also affected by #11219.  Closing this one.

-[Unknown]
