### ISSUE TITLE
Lines Across the screen

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#10391]
What happens?
in some games, when loading the game world, there are interesting lines across the screen

What *should* happen?
I don't know

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
OpenGL android

**Comment by marosis** [comment]
https://photos.app.goo.gl/hVAidxyHQWgRbTXz2

**Comment by hrydgard** [comment]
Oh you mean the thin, thin horizontal lines? Those are a common issue, a result of drawing games designed for lower resolution at higher resolution - sometimes things don't line up exactly especially when they use texture coordinate wrapping. If the issues don't go away in 1x rendering, it could be something else. If not, there are two options: 

  * Live with it
  * Manually replace those textures with higher resolution versions using the texture replacement feature

**Comment by marosis** [comment]
No i using 2x PSP resolution

**Comment by marosis** [comment]
Aha!! This problem Is only with 2xPSP resolution +(1xPSP Is ok)

**Comment by hrydgard** [comment]
Exactly. It's unfortunately not really fixable.
