### ISSUE TITLE
Vertical UI settings are missing

### ISSUE THREAD

**Issue by LunaMoo** [hrydgard/ppsspp#10398]
What happens?
![uiproblem](https://user-images.githubusercontent.com/5485237/33853924-071e1e20-dec0-11e7-959a-72cadd6347d2.png)

What *should* happen?
![uinoproblem](https://user-images.githubusercontent.com/5485237/33853928-0aefddfe-dec0-11e7-8b47-2bec1e4f43c4.png)

Tired enough for today to finally use template;c, from quick check #10388 broke it.

**Comment by hrydgard** [comment]
I'll leave it to @unknownbrackets :)
