### ISSUE TITLE
PPSSPP GPL violated.

### ISSUE THREAD

**Issue by JhonLoveJoy** [hrydgard/ppsspp#10409]
This guy copied part of the PPSSPP source code (and another part of the PCSX2*): https://play.google.com/store/apps/details?id=com.damonplay.damonps2.pro.ppsspp

* https://forums.pcsx2.net/Thread-android-compatability?page=2

Copycat!!!

**Comment by hrydgard** [comment]
Aware of this, discussed in #10402 .

Have little hard evidence of copying of PPSSPP things so far apart from part of the package name, though the in-game menu appears to be nearly identical which almost is proof. But mostly it almost certainly uses PCSX2 code, so it's them who have the best chance of taking it down through a DMCA request.
