### ISSUE TITLE
Libretro core crashes with fast memory disabled.

### ISSUE THREAD

**Issue by orbea** [hrydgard/ppsspp#10408]
## Description

The ppsspp libretro core in PR https://github.com/hrydgard/ppsspp/pull/10407 crashes if fast memory is disabled in the core options. I have not been able to reproduce this in the SDL2 or Qt5 frontends, but as its crashing in upstream code and since @hrydgard requested so I am reporting it here.
```
ppsspp_fast_memory = "disabled"
```
Also see this issue report. https://github.com/libretro/ppsspp/issues/32

### Expected behavior

It should not crash when fast memory is disabled.

### Actual behavior

It crashes when booting content or will crash after a short period of time if fast memory is disabled while running content.
```
48:55:458 root         I[G3D]: GLES/ShaderManagerGLES.cpp:176 Linked shader: vs 41 fs 54
48:55:459 root         I[G3D]: GLES/ShaderManagerGLES.cpp:176 Linked shader: vs 39 fs 58
48:55:460 root         I[SCEKERNEL]: HLE/sceKernelThread.cpp:19 276=sceKernelCreateThread(user_main, 088041cc, 00000020, 262144, 80000000, 00000000)
48:55:460 root         I[SCEKERNEL]: HLE/sceKernelThread.cpp:20 0=sceKernelStartThread(276, 33, 09fffed0)
48:55:460 root         I[SCEKERNEL]: HLE/sceKernelThread.cpp:21 __KernelReturnFromThread: 0
48:55:461 user_main    E[SYSTEM]: Common/MsgHandler.cpp:45 Critical: WriteRest: op out of range (0x401078d9 uses 0x7fffe8ecf6c0)
 
Thread 1 "retroarch" received signal SIGINT, Interrupt.
0x00007ffff0603f37 in kill () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff0603f37 in kill () from /lib64/libc.so.6
#1  0x00007fffe857d2de in Gen::OpArg::WriteRest (this=0x7fffffffd550,
    emit=0x29a0ea8, extraBytes=1, _operandReg=Gen::EDI, warn_64bit_offset=true)
    at ../Common/x64Emitter.cpp:242
#2  0x00007fffe8580db2 in Gen::OpArg::WriteNormalOp (this=0x7fffffffd550,
    emit=0x29a0ea8, toRM=true, op=Gen::nrmCMP, operand=..., bits=32)
    at ../Common/x64Emitter.cpp:1241
#3  0x00007fffe8580efb in Gen::XEmitter::WriteNormalOp (this=0x29a0ea8,
    emit=0x29a0ea8, bits=32, op=Gen::nrmCMP, a1=..., a2=...)
    at ../Common/x64Emitter.cpp:1270
#4  0x00007fffe8581341 in Gen::XEmitter::CMP (this=0x29a0ea8, bits=32, a1=...,
    a2=...) at ../Common/x64Emitter.cpp:1300
#5  0x00007fffe85b4557 in MIPSComp::Jit::WriteExitDestInReg (this=0x29a0e90,
    reg=Gen::EAX) at ../Core/MIPS/x86/Jit.cpp:700
#6  0x00007fffe858f82c in MIPSComp::Jit::Comp_JumpReg (this=0x29a0e90, op=...)
    at ../Core/MIPS/x86/CompBranch.cpp:750
#7  0x00007fffe853cba2 in MIPSCompileOp (op=..., jit=0x29a0ed0)
    at ../Core/MIPS/MIPSTables.cpp:922
#8  0x00007fffe85b2a48 in MIPSComp::Jit::DoJit (this=0x29a0e90,
    em_address=144061904, b=0x7fffd5397d10) at ../Core/MIPS/x86/Jit.cpp:353
#9  0x00007fffe85b24b1 in MIPSComp::Jit::Compile (this=0x29a0e90,
    em_address=144061904) at ../Core/MIPS/x86/Jit.cpp:273
#10 0x00007fffe84fea60 in MIPSComp::JitAt ()
    at ../Core/MIPS/JitCommon/JitCommon.cpp:48
#11 0x000000004010012c in ?? ()
#12 0x0000000000000000 in ?? ()
```
Full GDB log. https://pastebin.com/rT4xfWhw

### Steps to reproduce the bug

1. Disable `ppsspp_fast_memory` in the core options.
2. Start the ppsspp core in RetroArch.
3. It crashes immediately.

### Bisect Results

This started with the recent ppsspp libretro core and did not occur before with the old core. However a lot has changed in upstream ppsspp between those two cores.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: `1.6.9`
- ppsspp: https://github.com/hrydgard/ppsspp/pull/10407

### Environment information

- OS: `Slackware64-current`
- Compiler: `gcc-7.2.0`

**Comment by hrydgard** [comment]
Right before the crashing call there is a check that the value can be reached (RipAccessible). For that crash to happen it must have returned true, even though the pointer is very far away from the code.

The only way I can see that happen is that _M_IX86 is defined in the build somehow (see the check in RipAccessible!), even though it's a 64-bit build. Can you put this check anywhere nearby and try to build, and see what happens?

````
#ifdef _M_IX86
#error _M_IX86 should not be defined in a 64-bit build!
#endif
```

**Comment by hrydgard** [comment]
No wait, the check is bogus. Fixing.

**Comment by orbea** [comment]
That works here! As simple as the solution was that would of taken me a long time to find on my own, thanks!
