### ISSUE TITLE
installed.txt not being recognized?

### ISSUE THREAD

**Issue by MarioMasta64** [hrydgard/ppsspp#10403]
What happens?
ppsspp still reads the psp memory stick as my documents

What *should* happen?
ppsspp shouuld read the directory as F:\ (this path exists and is read / writeable)

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
windows 10, generic graphics.
installed.txt is in the same directory as PPSSPPWindows64 & PPSSPPWindows (.\bin\ppsspp\installed.txt)
installed.txt contains "F:\"
PPSSPP v1.5.4

**Comment by LunaMoo** [comment]
In windows 10 apps might require elevated priviledges for writing files in most places;p. If you run PPSSPP as admin you'll likely see it working.

**Comment by MarioMasta64** [comment]
im writing to F:\ a flashdrive that in previous versions worked. im unsure whats wrong, when i choose open memory stick it should open up F:\ like it used to. this only happened after updating to 1.5.4

**Comment by MarioMasta64** [comment]
okay, trying a different computer and it works. im honestly stumped but hey i guess you can close the issue now. (the drive is still F:\ but in a sd port instead of usb (its a microsd)) must be my adapter dying,
