### ISSUE TITLE
Horizontal tearing on fullscreen

### ISSUE THREAD

**Issue by Peduls** [hrydgard/ppsspp#10426]
What happens?
Regardless of vsync and backend settings there is noticeable tearing on all games.

What *should* happen?
Versions 1.5.4 and earlier do not have this problem and tearing is completely eliminated by selecting vsync (on)

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Operating System
	Windows 10 Enterprise 2016 LTSB 64-bit
CPU
	Intel Core i7 4790K @ 4.00GHz
	Haswell 22nm Technology
RAM
	16.0GB Dual-Channel DDR3 @ 799MHz (9-9-9-24)
Motherboard
	ASUSTeK COMPUTER INC. Z97-A (SOCKET 1150)
Graphics
	Acer S231HL (1920x1080@60Hz)
	4095MB NVIDIA GeForce GTX 1070 (EVGA)
Storage
	465GB Samsung SSD 850 EVO 500GB (SSD)
	2794GB TOSHIBA HDWD130 (SATA)	
Optical Drives
	ASUS DRW-24B1ST j
Audio
	High Definition Audio Device

**Comment by unknownbrackets** [comment]
In NVIDIA settings, the vsync option has basically 3 settings:
Auto (let the game decide)
Force on (override game)
Force off (override game)

Can you double check it's not forced off?  If so, the PPSSPP settings will have no impact.

-[Unknown]

**Comment by Peduls** [comment]
It's not set to "Force off". I have played around with the vsync settings in the NVIDIA control panel and having it set to "Force on (override game)" fixes the tearing, but restricts the fast-forward function in PPSSPP. Using the default settings (Auto) the tearing persists. Without making any changes in NVIDIA control panel and reverting to an older version of PPSSPP fixes the issue though.

**Comment by hrydgard** [comment]
You can get a different type of fast-forward by setting FrameSkipUnthrottle = True in memstick/PSP/SYSTEM/ppsspp.ini under [Graphics], that will work with force-vsync.

**Comment by unknownbrackets** [comment]
What's the first git build it stopped working on, and the latest one that it worked with?

-[Unknown]

**Comment by Peduls** [comment]
The issue is first present in v1.5.4-86-g3a44769f4. The latest version without this issue is v1.5.4-83-gcaf9eca2d.

**Comment by unknownbrackets** [comment]
Does it happen in the latest version if you change to OpenGL in the settings?

That points to #10390, which just made Vulkan the default setting.  It used to be OpenGL, but you can still switch back to OpenGL.

-[Unknown]

**Comment by Peduls** [comment]
Aw, geez. Yeah, that was the solution. I apologize for not testing this more thoroughly before coming here. Thank you both for your help!
