### ISSUE TITLE
AMD regressions from the removed legacy BGRA path

### ISSUE THREAD

**Issue by LunaMoo** [hrydgard/ppsspp#10425]
Starting from v1.3-1135-g67fb745 users of AMD gpu's have new problems with OGL backend, for example:
- [missing graphics in FFIV as reported in the forums](https://forums.ppsspp.org/showthread.php?tid=1971&pid=127526#pid127526),
- instant crash on boot in Brave Story(using standard, buffered rendering / default settings).

It's certainly a fault of AMD ogl drivers and a good solution is to just use other backend.
 ~ Unfortunately some things still work better in OGL backend, in more modern backend Vsync is not as good to everyone(might be system/hardware dependant) which will cause some ocassional, but noticeable tearing/stutter while moving on FFIV world map where lots of side scrooling happens. The Brave Story also still is glitchy in all non-ogl backends.

**Comment by unknownbrackets** [comment]
The crash is interesting - you'd think it'd just cause things not to be visible.

#9505 shows the removals - most of which should be the same.  But rather than restoring them, it'd be interesting to know which changes are needed to make it crash (minimally.)

For example, is it enough to make it not crash by changing this line to `true`?
https://github.com/hrydgard/ppsspp/pull/9505/files#diff-c186d1e5c210507a5c29e758cecef602L1105

If we bring it back, we'll want to do it possibly only for AMD / ATI.

-[Unknown]

**Comment by LunaMoo** [comment]
Can't find a single change which causes the crash, maybe I missed something, have to try again, call stack from the crash:
````
>	PPSSPPDebug64.exe!GPU_GLES::FastRunLoop(DisplayList & list) Line 559	C++
 	PPSSPPDebug64.exe!GPUCommon::InterpretList(DisplayList & list) Line 887	C++
 	PPSSPPDebug64.exe!GPUCommon::ProcessDLQueue() Line 1037	C++
 	PPSSPPDebug64.exe!GPUCommon::InterruptEnd(int listid) Line 2090	C++
 	PPSSPPDebug64.exe!GeIntrHandler::handleResult(PendingInterrupt & pend) Line 178	C++
 	PPSSPPDebug64.exe!__KernelReturnFromInterrupt() Line 418	C++
 	PPSSPPDebug64.exe!CallSyscallWithoutFlags(const HLEFunction * info) Line 469	C++

````
Under autos it shows:
Memory::base	0x0000000142fd0000 <Error reading characters of string.>	unsigned char *
<Unable to read memory>	unsigned char

**Comment by LunaMoo** [comment]
NVM it was the convert line, I initially trying by changing things one by one in build that had that path added, but trying to just set convert to true in latest version does indeed stop it from crashing.

**Comment by unknownbrackets** [comment]
Does this fix it?

https://github.com/hrydgard/ppsspp/compare/master...unknownbrackets:gl-pack-len

-[Unknown]

**Comment by LunaMoo** [comment]
Yeah:), thanks. Both, graphics and the boot crash get fixed by your code:).
