### ISSUE TITLE
Final Fantasy Type-0 Specific part of the game crash.

### ISSUE THREAD

**Issue by Dj-jom2x** [hrydgard/ppsspp#10438]
[What] happens?
![screenshot_2017-12-24-18-15-58-805_org ppsspp ppsspp](https://user-images.githubusercontent.com/12135498/34325770-87e4e30c-e8d6-11e7-8d71-a91fc674f659.png)

On final fantasy type 0 english .  when i open this book the system crashes.. theres a fast forward sound in the background and the buttons became unclickable even the analog doesn't rotate its like it doesn't work jist stuck.. but the sound still working at the background. and the screen goes black. you cant even press back button to show ppsspp menu nope.. GUI totally crashed. unresponsive

![screenshot_2017-12-24-18-11-38-296_org ppsspp ppsspp](https://user-images.githubusercontent.com/12135498/34325746-ef5b2b82-e8d5-11e7-9778-781d3330f521.png)

What *should* happen?
it supposed to introduce me whats inside this book.. I use ppsspp from gplay.. and i also used ppsspp nightly build but still no luck.. how do I know whats happening? :( the game is so smooth tho.. on my xiomi redmi note 4x mtk helio x20

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Phone : Xiomi Redmi Note 4x 64gb MTK Helio x20 Deca Core
OS : Android 6.0

**Comment by LunaMoo** [comment]
That's a known problem with this particular translation(one of the many). If I remember saving in-game and reloading from that save(not savestates!) might help with at least some of those issues. There was also second version of that patch which supposedly reduces amount of crashes, but both "patches" were pretty much distributed as warez with whole game content included and as such does not have any legal downloads.

 This isn't emulation issue, so I'm going to close this as invalid issue.

**Comment by Dj-jom2x** [comment]
omg your right hehe xD if i use save state from ppsspp it crash.. but if i load my save state via game it works hahaha your so genius

**Comment by Dj-jom2x** [comment]
i use the v2 of English patch
