### ISSUE TITLE
Crash on using Dynarec and IR Interpreter | iOS 10.3.3 32bit (JBed)

### ISSUE THREAD

**Issue by 1Conan** [hrydgard/ppsspp#10444]
What happens?
Dynarec - Application crash on loading up a game (Tested with God Eater Burst) 
IR Interpreter - Application crash after Game Intro (Tested with God Eater Burst) 

(Will update once I test other roms.)

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

iPhone 5 (iPhone5,2)
iOS 10.3.3
Tested on Dev-Latest and Dev-Working builds.
H3lix Jailbreak http://h3lix.tihmstar.net

**Comment by iOS4all** [comment]
I hope this will be fixed for micro-stutter which is happening every 3-4 seconds on jailbroken 64-bit devices

**Comment by 1Conan** [comment]
@iOS4all that is a completely irrelevant issue though.

**Comment by unknownbrackets** [comment]
See #10446, which will fix the IR crash.

-[Unknown]

**Comment by 1Conan** [comment]
@unknownbrackets unfortunately, I don't have a mac to test that PR.
Also, not really sure I understand #9232 but according to it, 32bit doesn't have the problem.

**Comment by Finixs** [comment]
Did you game run smooth? Im using helix jb and ip5 too

**Comment by unknownbrackets** [comment]
32-bit builds seem to work fine on a slightly newer device.  But so do 64-bit now.

-[Unknown]

**Comment by 1Conan** [comment]
Seems like it was an issue with h3lix. It has been updated and Dynarec works now. 
As for IR Interpreter, I haven't tested yet since the builds on the cydia repo isn't updated yet.
