### ISSUE TITLE
SDL2 credits transition letters running ultra fast

### ISSUE THREAD

**Issue by mrcmunir** [hrydgard/ppsspp#10445]
When running UI -> Credits 

The letters  transition is running ultra fast and it makes reading difficult.

This problem is not affected OpenGL rendering

Testing 
Antergos distro linux + mesa3d git 
GPU IGPU skylake HD 520

**Comment by hrydgard** [comment]
Yeah, we're not limiting framerate correctly, and maybe should use a different swap mode.

**Comment by vnctdj** [comment]
Not Vulkan-specific, I experience this bug with OpenGL on Debian.
