### ISSUE TITLE
Display Driver Crash Crashes PPSSPP

### ISSUE THREAD

**Issue by tilkinsc** [hrydgard/ppsspp#10457]
What happens?
Display driver crash doesn't reload context or something and application crashes

What *should* happen?
No crash

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Win7 SP1
Nvidia GT 730 (Zotax gt 730 4gb)

**Comment by hrydgard** [comment]
Um. You mean that if the driver crashes due to some other app crashing, PPSSPP doesn't recover? Or does PPSSPP cause the driver crash?

**Comment by Hydroque** [comment]
When the driver crashes from any source, PPSSPP doesn't recover.

**Comment by hrydgard** [comment]
Does this apply to all four graphics backends?

**Comment by Hydroque** [comment]
ppsspp v1.5.2-45
Direct3D 11

Haven't been able to crash my driver while using opengl or vulkan and D3D9 doesn't apply to me.

**Comment by Hydroque** [comment]
Yes

**Comment by tilkinsc** [comment]
This is only due to poor old drivers by the way. On windows 10 I don't get this issue.

**Comment by hrydgard** [comment]
I'm just gonna close this, we have a couple other similar ones anyway...
