### ISSUE TITLE
Latest android builds crash on GPD XD with Android Kitkat.

### ISSUE THREAD

**Issue by NikaBosmit** [hrydgard/ppsspp#10451]
What happens?
All latest PPSSPP builds since "ppsspp-v1.5.4-30-g3eda31000-android" crash trying boot any game with any set of preferences.
Crash log attached.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
GPD XD console with Kitkat android.
[log.txt](https://github.com/hrydgard/ppsspp/files/1587249/log.txt)

**Comment by unknownbrackets** [comment]
Is v1.5.4-33-gc268e3781 the first one that crashes (which would mean the switch to libc++), or is v1.5.4-30-g3eda31000 the first that crashes?  And v1.5.4-28-gb75c8b72c works fine?

I think you mean that v1.5.4-30-g3eda31000 is the first that crashes.  Maybe this is some kind of OOM, because it's just crashing in the texture cache constructor, it seems like?  But the device ought to have 2GB of RAM, so that's odd.

-[Unknown]

**Comment by NikaBosmit** [comment]
v1.5.4-30-g3eda31000 is the latest working build. 
Just re-checked v1.5.4-33 and few later builds incl latest, they all crash.

**Comment by hrydgard** [comment]
Ugh, then it's indeed some kind of issue with libc++ backwards compatibility. Strange, since for me things are fine even on Nexus One.

Can you get an ADB log of the crash?

**Comment by NikaBosmit** [comment]
>Can you get an ADB log of the crash?

I made one in the op post via Catlog app. But i'll try to made one using logcat.

**Comment by hrydgard** [comment]
Sorry, missed it.
Looks very strange...

**Comment by tiagaoextremo** [comment]
Hi, i'm facing the same issue as NikaBosmit. Nightly builds still crashing with any game, but playstore is working just fine. Could this be fixed?

**Comment by hrydgard** [comment]
Hopefully, but no idea how tricky it will be to find the problem. We could go back to the old libc but that method will stop working in a couple more versions of the Android NDK...

**Comment by unknownbrackets** [comment]
Just to confirm, does this still happen with the latest git builds?

-[Unknown]

**Comment by NikaBosmit** [comment]
Yep. Confirm the bug on v1.5.4-580-g375032705.

**Comment by tiagaoextremo** [comment]
Hi, just wanted to say thank you.  Yesterday i tried the latest nightly build (v1.5.4-653-g0ed3deabe) and it's working again. Even better i tried megaman x maverick hunter and it ran at steady 60fps for the whole stage. This one would drop frames some times. Thanks for your work, it's highly appreciated.

**Comment by hrydgard** [comment]
Huh. No idea what might have caused it then... but I suppose that's good. @NikaBosmit  can you confirm?

Also it would be good if you guys could test a few past versions so we can see what might have fixed it...

**Comment by NikaBosmit** [comment]
Confirm this bug fixed. First **working** build is v1.5.4-643-g37f44364d.  Thanks for Your hard work.

**Comment by hrydgard** [comment]
Hm, that's unexpected, that's just the removal of hardware skinning. I don't like bugs where I don't understand how I fixed them :) Oh well, closing. Please keep testing new versions every few weeks at least, I don't want this to come back.

**Comment by unknownbrackets** [comment]
Hmm, maybe it was actually vertexjit related?  Strange.

-[Unknown]

**Comment by hrydgard** [comment]
romain337 reported on IRC that there's a very similar crash on the GPD XD when building locally but not on buildbot builds. Could be an incompatibility between newer NDKs and this device, which sounds like a pain...

**Comment by hrydgard** [comment]
That's been resolved now, so not reopening.

**Comment by dre10g** [comment]
On my OG running legacy rom. After some testing with different version, I figure something happened between these 2 builds that broke the Outrun for me: 

V1.10.3-1106-gbd066b4e5 Henrik Rydgård 2020-11-02 13:32:35 Merge: 085900adb ce4ee010a Merge pull request #13613 from hrydgard/shader-writer Shader writer utility, other cleanups 

v1.10.3-1 099-g085900adb Henrik Rydgård 2020-11-02 09:03:08 Fix vertex shader generator bug. Got caught by the new test 

Using 1.10.3-1099 for now as it's the latest version that works with Outrun for me.
