### ISSUE TITLE
PS4 Controller Slow REACTIONS with Bluetooth

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#10452]
This problem have every device (of course PS4 not). Is it possible to create a patch to fix this problem?

**Comment by marosis** [comment]
Please try fix this hrydgard if you can

**Comment by unknownbrackets** [comment]
If you go to Settings -> Controls -> Control mapping, and then click Test analogs on the left, is it just as slow there?

If so, there may not be a ton we can do.  Do other apps have better responsiveness?  Is this on Android, Linux, Windows, or...?

-[Unknown]

**Comment by marosis** [comment]
I wrote this problem have every device (android Linux, Windows, every device! Not PS4)

**Comment by marosis** [comment]
this problem is only with the controller. the only way to fix this problem is to create a patch. The PS4 Controller is designed to suit the PS4 console. not for another device even though it can be paired with Bluetooth. even on the Internet people ask why this is happening.

**Comment by GamerzHell9137** [comment]
The DS4 controller have a higher input lag than their counterparts DS3 and DS2. Its just how the controller works, its not perfect on PC. (I'm getting like 10ms lag spikes a lot). Either connect the controller with USB or use a DS3/DS2/DS1 controller.

**Comment by marosis** [comment]
I using PS4 Controller on android And for working i need double micro USB. I tried otg cable but Its not working. On PC i didnd't tried it

**Comment by adenovan** [comment]
if the controller has less input lag with usb then it can be DS4Windows problem over bluetooth that cause input lag on Windows PC, im using DS3 to play and the best Xinput Wrapper for them i found is the SCP one its need you to replace some bluetooth driver on your pc but from my experience there is no input lag i found with bluetooth connection. some user state its works on DS4 here is the link. did you mean this kind of patch?

https://forums.pcsx2.net/Thread-XInput-Wrapper-for-DS3-and-Play-com-USB-Dual-DS2-Controller?pid=334146#pid334146

**Comment by marosis** [comment]
I didn't tried playing with USB. ONLY with BT and only on android never on PC:). But this Is good too. On YouTube Is lot of videos with this problems what i mean.

**Comment by marosis** [comment]
Input lags are on BT.

**Comment by marosis** [comment]
Did you tried on android?

**Comment by GamerzHell9137** [comment]
@marosis I've fixed my BT issues with DS4Windows by buying an extend USB cable and plugging my BT Dongle to that, try it. It costs like a buck or so.

**Comment by unknownbrackets** [comment]
It sounds like this is not a bug in PPSSPP.  To say, it's entirely expected that Bluetooth devices will have more latency than wired devices.  I've never seen a benchmark or analysis predicting the opposite.

If you're seeing latency across applications this means that it's either a device, driver, or technology problem.  PPSSPP isn't an operating system or a physical device - it can't solve these problems.

The forum is a good place to ask the community about what controllers have the best latency.

-[Unknown]
