### ISSUE TITLE
Android build no longer works

### ISSUE THREAD

**Issue by leopard20** [hrydgard/ppsspp#10469]
What happens?
So I wanted to check how the development process was going when I noticed something:
PPSSPP freezes when I launch a game.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Android 7.0
Snapdragon 821
PPSSPP v1.5.4-227

**Comment by unknownbrackets** [comment]
Works fine for me on a Pixel, which is also Snapdragon 821.  But I think I'm running Android 8.1.

What games have you tried?

-[Unknown]

**Comment by M220** [comment]
Bug happened for me too.
I have S6 with android 7.0 but i think bug started with PR #10467 and friends.

**Comment by yyk0418** [comment]
same problem

If I try to run any game I have, it stops on black screen

I had this problem with v1.5.4-227-gcb3b1876d, but v1.5.4-214-g60c10e77c build no problem 

Galaxy note 5
Android 7.0 
exynos 7420 
Mali T760MP8

**Comment by leopard20** [comment]
Every game I tried had this issue:
NFS carbon
Def Jam
Field Commander
PoP

I bet it's the same for all games!

**Comment by unknownbrackets** [comment]
Hm.  Okay, I think I reproduced it.  Definitely not every game, but after trying a bunch of games I found one that isn't working.  Hopefully because of the same issue, bisecting now.

-[Unknown]
