### ISSUE TITLE
Problem with buildbot on Cydia

### ISSUE THREAD

**Issue by iOS4all** [hrydgard/ppsspp#10478]
It's been a while we didn't see any new update on Cydia
I installed the latest available version on Cydia which is v1.5.4-114 but even though inside ppsspp app is still on v1.4.2-575

Please can anyone figure out and see what wrong?
Thanks.

**Comment by hrydgard** [comment]
@angelXwind is aware and is looking into it.  You already opened #10399 about this, so closing as dupe.

**Comment by iOS4all** [comment]
Oh sorry I didn't notice that.
