### ISSUE TITLE
Tekken 6 freeze app 

### ISSUE THREAD

**Issue by Blacob777** [hrydgard/ppsspp#10474]
When loading fight app Just freeze, Last works build 214
![screenshot_2017-12-30-18-09-59-252_org ppsspp ppsspp](https://user-images.githubusercontent.com/29165096/34453413-79f2e286-ed8f-11e7-96c8-ecff16fccbf5.png)

**Comment by hrydgard** [comment]
Already reported in https://github.com/hrydgard/ppsspp/issues/10473 , closing as duplicate. Will look into it soon.
