### ISSUE TITLE
Midnight Club 3 graphics glitches

### ISSUE THREAD

**Issue by ghost** [hrydgard/ppsspp#10473]
Tekken 6 freezes and stops working just before starting a match with Build 232.  I've made no changes to my settings or files, except updating PPSSPP.

There's also strange graphical glitches on Midnight Club 3 that seem to be occurring on Vulkan only, as seen here:
![screenshot_20171229-193125](https://user-images.githubusercontent.com/33438850/34450529-f458fcd2-ecd0-11e7-83c8-8f27ed48693f.jpg)

The graphical glitches also happen on Builds 198 and up.  I also confirmed that Build 176 looks fine, regardless of which API chosen.  I'm currently using a OnePlus 5 (Android 8.0.0).  If I find anything else, I'll let you know.

**Comment by hrydgard** [comment]
I'll bisect the Tekken problem in a bit.

**Comment by 66Muramasa** [comment]
Tekken 6 plays fine in Build 246.  The graphical glitches in Midnight Club 3 still persist, however.
![screenshot_20171230-104820](https://user-images.githubusercontent.com/33438850/34455997-30078bb0-ed51-11e7-8c21-5e2827343a4d.jpg)

**Comment by hrydgard** [comment]
Looks like depth issues again...

**Comment by Blacob777** [comment]
Android 7,snap 821 normal graphics, only map 
![screenshot_2017-12-31-01-59-37-861_org ppsspp ppsspp](https://user-images.githubusercontent.com/29165096/34456326-8c17f070-edce-11e7-895d-f011eb6fe9b1.png)

**Comment by 66Muramasa** [comment]
@Blacob777 Is that on Vulkan or OpenGLES?

**Comment by Blacob777** [comment]
Vulkan bro

**Comment by unknownbrackets** [comment]
Note: we have a flag that's disabling the accurate depth path for this game.  See #10087.

I wonder if it's just using a far-away depth value like that other game.  Depth clamping might even fix it, if so...

-[Unknown]

**Comment by 66Muramasa** [comment]
Anything new?

**Comment by oli0371** [comment]
On s7 edge T880 using vulkan i have sky glitch in midnight club 3 dub remix otherwise all is good and game run smoothly

**Comment by marosis** [comment]
Oli0371 we know about Sky:)

**Comment by marosis** [comment]
#10087

**Comment by 66Muramasa** [comment]
Can people please quit talking about the sky glitch?  That has nothing to do with my problem.

**Comment by 66Muramasa** [comment]
The depth issue still persists in Build 315.

**Comment by unknownbrackets** [comment]
I wonder if this is depth clamp related.  Could you try exporting a GE debugger dump on PC?

To do this, open the game and select Debug -> GE debugger..., then when it's displaying the scene, press Record in the top right.  After a second or so, it'll finish and save a trace of the drawing activity.

After that, check the memstick/PSP/SYSTEM/DUMP folder and it'll have created a file named something like "ULES12345_0000.ppdmp".  You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by 66Muramasa** [comment]
I'll have to pick up the ISO again before sending the dump when I have more time.  This evening, most likely.

**Comment by 66Muramasa** [comment]
Guess it's not possible to do this on my Android phone, isn't it?  My laptop has terrible specs.

**Comment by GuilhermeGS2** [comment]
Issue fixed on latest builds (probably after v1.7.5-527-g593c3139b). But using resolutions higher than 1x the performance is lower than OpenGL.

**Comment by unknownbrackets** [comment]
Yeah, this was probably related to the Adreno bugs affecting Harvest Moon, then.  Thanks for the report - closing.

-[Unknown]
