### ISSUE TITLE
iPhone X resolution 

### ISSUE THREAD

**Issue by dmr86** [hrydgard/ppsspp#10486]
Hi, 

the iPhone X resolution isn't supported ATM, there are black bars on the both sides. Changing Deployment target in XCode to 11.1 results in:

> clang: error: invalid iOS deployment version '-miphoneos-version-min=11.1', iOS 10 is the maximum deployment target for 32-bit targets [-Winvalid-ios-deployment-target]

Any suggestions on how to make PPSSPP fit the whole screen size?

 Thanks!

**Comment by yoshisuga** [comment]
Were you able to get PPSSPP to run at all on the iPhone X in the first place? Assuming you're on iOS 11, you can only run 64-bit apps, and the error you're getting is showing that your binary is 32-bit.

If you were able to get PPSSPP to run on the iPhone X on iOS 11, please post instructions how you did that :)

**Comment by unknownbrackets** [comment]
It's possible #10507 would help this.

The jit now works on arm64, so you can just disable the armv7 target now.

-[Unknown]

**Comment by iOS4all** [comment]
@unknownbrackets please can you give me the deb file of latest ppsspp app with JIT 64-bit?
Thanks

**Comment by unknownbrackets** [comment]
I haven't the slightest clue how to create an iOS build file, and no longer have access to an iOS device.  Asking me won't help.  Someone was already looking into the issue, and it belongs in #10399.

-[Unknown]

**Comment by dmr86** [comment]
Thanks @unknownbrackets ! Though when I pulled the newest version it is now giving me an error on ZERO_CHECK:

> ZERO_CHECK_cmakeRulesBuildPhase.make$CONFIGURATION all'
Command /bin/sh failed with exit code 2

@yoshisuga I was able to run it, on the earlier build (1.5.4-272-ge82237bb0) using the instructions from here: http://blog.greggant.com/posts/2017/10/16/install-ppsspp-ios-without-jailbreak.html

Tested Persona 3 and it seemed to work fine. iPhone X 11.1.2, not jailbroken (yet :P)

However, as I mentioned earlier I cannot run it on the newest build because of the ZERO_CHECK error.

**Comment by hrydgard** [comment]
Yup, that look is to be expected, just like on supertall Android devices like S8.

**Comment by unknownbrackets** [comment]
Two notes about that post:

1. It might result in a debug version on your phone, which will run at approximately 50% the speed of a release build.  I had to change the scheme settings to Release or RelWithDebInfo for proper performance.
2. The crash (which is now fixed) was due to a bug in the 64-bit jit that only affected iOS, not the lack of a 64-bit jit entirely.

If you really want to (I wouldn't), you can stretch the display in the settings under the display layout editor.

-[Unknown]

**Comment by dmr86** [comment]
Thanks @unknownbrackets , that's good to know. I have changed the scheme to release however even at the debug mode I was running everything at 100% speed. Guess that A11 chip really is a best :)

**Comment by Chrisx333** [comment]
Hello!
It's been a year and still no new iphones full screen resolution.
Will be this ever pushed or is not on plan?

Thanks!
