### ISSUE TITLE
Psx2psp

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#10487]
What happens?

https://photos.app.goo.gl/0YvJtj0kDqsMgigm1

is it because of copyright?

Can I fix it by downloading PS1 Eboot?

**Comment by marosis** [comment]
Game: Diablo

**Comment by unknownbrackets** [comment]
See #9431.  You've downloaded the wrong kind of emulator by mistake.  This is a PSP emulator.

-[Unknown]

**Comment by marosis** [comment]
Yeah I know but this game Is psx2psp So you can play psx games on Real PSP.
