### ISSUE TITLE
Unification fullscreen on Windows and Linux versions

### ISSUE THREAD

**Issue by TotalCaesar659** [hrydgard/ppsspp#10485]
On Linux (Lubuntu 16.04.3, Ubuntu PPA), PPSSPP opens in fullscreen at startup. On Windows, PPSSPP opens in window mode.
There are ppsspp.desktop and ppsspp-sdl.desktop in /usr/share/applications. Could you remove "--fullscreen" from "Exec" string?

**Comment by unknownbrackets** [comment]
The packager has added that, maybe to workaround #8032.  There's no code in this repo that makes PPSSPP start full screen by default - if you compile PPSSPP from source, that doesn't happen.

-[Unknown]

**Comment by vnctdj** [comment]
I don't see a reason to open the SDL version in fullscreen by default.
I think it's better to open PPSSPP in windowed mode like in all other builds: the user can choose to switch to fullscreen if/when he wants.

**Comment by TotalCaesar659** [comment]
@sergiobenrocha2 Hello, do you have any plans for fixing this bug? There is already 1.8.0 released.

**Comment by TotalCaesar659** [comment]
Cause this issue is referred to former PPSSPP [PPA](https://launchpad.net/~ppsspp/+archive/ubuntu/stable) that isn't maintained anymore, it can be closed now.
