### ISSUE TITLE
OutRun 2006 - Artifacts on screen

### ISSUE THREAD

**Issue by Levan7** [hrydgard/ppsspp#10499]
You get some additional garbage Artifacts on screen.
I am using v1.5.4-305-g690a409da version on windows x64
I get this issue on dx11, opengl and software rendered looks really funky

DX11

![dx11](https://user-images.githubusercontent.com/5770076/34488809-4dce0634-eff3-11e7-8394-06e2a826296e.gif)
 
OpenGl

![gl](https://user-images.githubusercontent.com/5770076/34488843-6bf0bd50-eff3-11e7-9325-cee476120386.gif)

software rendered
![software](https://user-images.githubusercontent.com/5770076/34488891-9d2ad626-eff3-11e7-9ee8-6422e9b23286.gif)

Log file

[log.zip](https://github.com/hrydgard/ppsspp/files/1597956/log.zip)

**Comment by ppmeis** [comment]
Tested with latest windows build, default settings. Vulkan is affected too:
![image](https://user-images.githubusercontent.com/4381277/34503954-b28b1f12-f01b-11e7-8d73-57b16e592145.png)

**Comment by unknownbrackets** [comment]
Could be guardband.  The software renderer result is pretty interesting...

-[Unknown]

**Comment by hrydgard** [comment]
Isn't this the same as #5507 ?  Also guessing mostly guardband issues ( #9527 ) but I think Outrun has additional problems (related to colors of cars, some missing water).

**Comment by unknownbrackets** [comment]
Oops, yes.  Closing as duplicate.

-[Unknown]
