### ISSUE TITLE
Brothers in Arms: can't go past first mission cutscene

### ISSUE THREAD

**Issue by leopard20** [hrydgard/ppsspp#10490]
What happens?
PPSSPP freezes after the end of the first mission intro cutscene. You can still interact with the controls (e.g move the control stick around) but it visibly lags a lot.
Sometimes it even freezes before the cutscene.
Skirmish mode can be played without problems though.
This happened in version 1.5.4-274

What *should* happen?
v1.5.4 (stable) successfully passes the cutscene.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Android 7.0
Snapdragon 821

P.S: Happy new year guys!

**Comment by unknownbrackets** [comment]
Just to confirm, this is no longer worse than 1.5.4 was right?

-[Unknown]

**Comment by leopard20** [comment]
@unknownbrackets 
Dunno. Didn't test it because I don't have the game anymore, and since you guys didn't say anything I decided to close this.
