### ISSUE TITLE
Building for iOS 11 / arm64

### ISSUE THREAD

**Issue by yoshisuga** [hrydgard/ppsspp#10509]
I don't think we have a true 64-bit build of PPSSPP for iOS. iOS 11 only runs 64-bit binaries.

I started going down the path of building for arm64 for iOS and I think I made some progress. I made a few tweaks and got the cmake to create the Xcode project.

I had to fix some std::map allocator reference because of Xcode's std c++ library (?) and I ran into this error while building:

```
ld: library not found for -lSPVRemapper
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I think this is being built somewhere but where would I find the SPVRemapper library so I can point Xcode to it?

Also, I need to build ffmpeg in the iOS arm64 architecture as well. I'm hoping I can just change the arch to arm64 and everything would just work.

**Comment by unknownbrackets** [comment]
iOS already uses universal arm64/arm7 libraries.  I was recently testing the arm64 jit on a iPhone which definitely ran under arm64.  So it is presently building it, and there were no errors.

-[Unknown]

**Comment by yoshisuga** [comment]
Hmm was this on a jailbroken iPhone? I'm trying to get this to run on a non-jailbroken phone.

I checked the ffmpeg libraries in `ffmpeg/ios/universal/lib` and they look to be 32-bit:

```
libavcodec.a:    Mach-O universal binary with 2 architectures: [arm_v7:current ar archive random library] [arm_v7s]
...
```

**Comment by hrydgard** [comment]
I know I've been running 64-bit in the past on my iPad, those ffmpeg libraries should have 64-bit code in them too...

**Comment by yoshisuga** [comment]
Hmm ok that's strange - if anyone can provide build instructions for iOS 64-bit arm64, that'd be great. Or, if anyone has a pre-built IPA that runs on 64-bit devices, that'd be great as well.

@hrydgard Do you happen to know where the `SPVRemapper` library is supposed to reside after doing cmake?

Thanks!

**Comment by hrydgard** [comment]
That library doesn't even need to get built, it's just a part of spirv-cross that we don't use..

**Comment by yoshisuga** [comment]
Ah, ok - I removed the reference to that library, and now I think it's just
the linking to the ffmpeg libraries that are the issue:


```

ld: warning: ld: warning: ignoring file
/Users/yoshi/Code/ppsspp-master/ffmpeg/ios/universal/lib/libavformat.a,
missing required architecture arm64 in file
/Users/yoshi/Code/ppsspp-master/ffmpeg/ios/universal/lib/libavformat.a (2
slices)ignoring file
/Users/yoshi/Code/ppsspp-master/ffmpeg/ios/universal/lib/libavcodec.a,
missing required architecture arm64 in file
/Users/yoshi/Code/ppsspp-master/ffmpeg/ios/universal/lib/libavcodec.a (2
slices)

```


Can I just use any ffmpeg library compiled for iOS or does it need to be
the one included as a submodule in the ppsspp repo?

**Comment by unknownbrackets** [comment]
This was with a non-jailbroken iPhone 6, and the latest master / ffmpeg submodule back a couple weeks ago.

Build steps were:
1. Run cmake with Xcode generator per build instructions wiki.
2. Open in Xcode 8.
3. Change signing profile to something that works (there was some auto managed thing.)
4. Change min deploy target to 10.  This had to be done in two places, and there were weird errors without it (I think Xcode was missing the older iOS SDK code.)
5. Validate that exceptions and RTTI are enabled.  I thought to disable these, but it made SPIRV fail to build.  They were on by default, though.
6. Optional: edit the target processor settings (there were two next to each other, had to change both.)
7. Edit the scheme to be RelWithDebInfo for Run, if you want mostly realistic performance and C++ debugging.
8.  Hit Run with the device connected.

-[Unknown]

**Comment by yoshisuga** [comment]
Thanks for the instructions. Do you know what iOS version you're using? The
iPhone 6 is arm64, and up until iOS 10, was able to run 32-bit binaries.

The issue is that iOS 11 won't execute 32-bit binaries, so everything needs
to be compiled using the arm64 architecture.

I think if I can get the ffmpeg module built in arm64 as its done on
android, it'd be one step further in having a true 64-bit build for iOS.

**Comment by hrydgard** [comment]
As you can see in this script: 

https://github.com/hrydgard/ppsspp-ffmpeg/blob/master/ios-build.sh#L9

we are building for multiple archs already, x86 for the xcode "simulator" and arm and arm64. 

If the new stuff really hates having a 32-bit lib included, you could try just editing that script and re-running ios-build.sh from ffmpeg/. Let us know if it works.

**Comment by Dribblejam** [comment]
Keeping an eye on this. Been looking for an iOS 11 build since July. Unfortunately don’t have a Mac so can’t contribute. Hopefully all work out!

**Comment by yoshisuga** [comment]
Well it looks like I failed in git submodules and I was totally wrong. I re-checked out everything from scratch and the ffmpeg libs did have an arm64 slice.

I was able to get the latest master to run on my iPhone 7 Plus on iOS 11, so PPSSPP does fully support 64-bit non-jailbroken devices.

And it looks like someone fixed the launch screen to support the higher resolution :)

Closing, thanks!

**Comment by Dribblejam** [comment]
Yoshi can you email me an iOS 11 build?

**Comment by yoshisuga** [comment]
Here's a link to the IPA:
https://mega.nz/#!ONYyHTQR!0aDgNemznTv9_7us85f26CB0ETrzQKHicMEEjKHG0dM

It needs to be re-signed to install it, of course.

**Comment by Dribblejam** [comment]
Amazing! Thank you so much!

**Comment by DuIslingr** [comment]
For anyone looking for an Electra compatible version here. https://cdn.discordapp.com/attachments/171698955237851136/407416977305501717/PPSSPP.zip

Unzip and place in /Applications (already signed it with entitlements so should work out of the box)
In terminal run uicache and ur good to go.
App will tell you where it expects to find games at the top so make sure you take note of the location so you can find it in filezilla or w/e.

Removed the 32 bit from the build provided by @yoshisuga since iOS 11 can't run it anyways.

**Comment by thereturn932** [comment]
@DuIslingr your version crashes on start on iOS 11.1.2 Electra beta 9

**Comment by DuIslingr** [comment]
@thereturn932 Ensure PPSSPP has the correct permissions. its possible they were lost when i zipped up the archive since i didnt do it on device, instead i transferred it to windows then zipped it. just run chmod 755 on the binary.

**Comment by M1staAwesome** [comment]
@yoshisuga Tried sideloading that PPSSPP.ipa on my iPhone 8+ on 11.3 beta 4, and it worked fine. Afterwards though, when I deleted it and tried to resideload it then add roms, it just stays on a blue screen. Any ideas?
