### ISSUE TITLE
Issue in NFS Most Wanted 5.1.0

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#10504]
What happens?
In game when you have off-Disable slower effects game have when you driving Fast or using nitro this issue 
https://photos.app.goo.gl/RElSLzlh8uVQw4uh2
With ON-disable slower effects (Speed Up) Issue Is fixed but game Is blury. Used default settings
What *should* happen?
I thought this Is created by hardware transforming but not

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
OpenGL android 6.0

**Comment by marosis** [comment]
Problem have with this too GOD OF WAR https://photos.app.goo.gl/QIf13WfpWWj21Qx92 I think ppsspp need more cleansup

**Comment by ppmeis** [comment]
What device are you using? What PPSSPP version? What game region? Does it happend in other backends?

Also please create a thread for each game.

Tested with latest windows build, default settings. It works fine regardless Disable Slower Effects is off or on:

OpenGL:
![image](https://user-images.githubusercontent.com/4381277/34669952-7b2315ea-f474-11e7-8f28-0edc2945bb15.png)

**Comment by marosis** [comment]
I using newest version Lenovo K10A40.

**Comment by marosis** [comment]
Maybe this problem Is when you always changing settings. I don't know

**Comment by ppmeis** [comment]
So that's a LENOVO C2:

OS | Android 6.0 (Marshmallow)
Chipset | Mediatek MT6735P
CPU | Quad-core 1.0 GHz Cortex-A53
GPU | Mali-T720MP2
