### ISSUE TITLE
Frontier Gate Boost bugs while using IR or interpreter

### ISSUE THREAD

**Issue by unknownbrackets** [hrydgard/ppsspp#10500]
Might be some form of invalidation problem for IR - see #7066.  But even interpreter behaves weirdly (but different.)

While testing that other bug, I had created save data with a new game.

With x86jit: I'm able to go into the place where you get missions.
With irjit: When I approach that place, I end up in some other place about half way there.
With interpreter: When I approach that place, I suddenly disappear and can no longer move.  The game isn't frozen, though.

Very strange...

-[Unknown]

**Comment by unknownbrackets** [comment]
Maybe this is related to rounding mode, which I think doesn't work on IR and maybe not interpreter either.

-[Unknown]

**Comment by benderscruffy** [comment]
Please close in favour of #15670

**Comment by unknownbrackets** [comment]
This bug appears to be fixed actually, anyway.  So closing.  I can't reproduce any problems with IR or interpreter now.

Note: I did test using the #16396 fix, but I suspect it's some prior interpreter fix, maybe the vscl one.

-[Unknown]
