### ISSUE TITLE
Unthrottling (with frameskip) causes graphical issues in a number of games

### ISSUE THREAD

**Issue by Leopard20** [hrydgard/ppsspp#10519]
What happens?
When I unthrottle certain games, they misbehave (mostly graphical glitches)
For example, if I unthrottle The 3rd Birthday before the autosave warning screen is shown, I get a black screen. I can still press X to confirm it though.
Also, I think the issue I mentioned in https://github.com/hrydgard/ppsspp/issues/10490 is partly caused by this issue (I can't pass the cutscene no matter what, but fast forwarding makes it worse)

V1.5.4 has no issues though.

What *should* happen?
Unthrottling should only increase emulation speed. Not cause issues (as in v1.5.4)

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Android 7.0
Snapdragon 821
PPSSPP v1.5.4-336 AND v1.5.4-227 (the issue probably exists in all builds between/before these two)

**Comment by unknownbrackets** [comment]
This is likely because frameskip is (by default) on when you unthrottle.  That ends up preventing block transfers too.

Did you check Vulkan and OpenGL in the latest git build and also in 1.5.4?  It's much more likely that this is just something that behaves differently in Vulkan, and not something that was broken in OpenGL since 1.5.4.

-[Unknown]

**Comment by unknownbrackets** [comment]
Maybe the graphicsContext or something could pass back a flag on whether vsync is forced?

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, something like that would probably be the best way.

**Comment by unknownbrackets** [comment]
Just noting here: #12970 will make an ini option to change this, but it won't change the default (at least yet.)

-[Unknown]
