### ISSUE TITLE
Castlevania - The Dracula X Chronicles graphics glitch

### ISSUE THREAD

**Issue by Levan7** [hrydgard/ppsspp#10528]
Well on the second mission i get this glitch I tried it on opengl and dx 11

I am using v1.5.4-361-g6e8d18df8 |  build however the 1.4.2 suffers from the same issue 

![1](https://user-images.githubusercontent.com/5770076/34906541-f5d47b36-f888-11e7-9be7-ebfa09104433.gif)

and 

![2](https://user-images.githubusercontent.com/5770076/34906544-0cc7aeee-f889-11e7-8dfb-f4392d975a77.gif)

log files
[log.zip](https://github.com/hrydgard/ppsspp/files/1628395/log.zip)

Software renderer has the same issue 

![3](https://user-images.githubusercontent.com/5770076/34906578-a0829a2c-f889-11e7-8ad9-8bad9b2716f3.gif)

**Comment by LunaMoo** [comment]
Looks like you're using some game breaking settings, use hacks or damaged game copy. Not into witch hunting, but from the forums I know people love to pirate some korean copy of this title which is a known bad dump. The original game works fine here.

**Comment by Levan7** [comment]
@LunaMoo 
Yes you were correct it is the cheats i used i disabled them and now it works fine 
![ulus10277_00000](https://user-images.githubusercontent.com/5770076/34909926-99c5ca84-f8c4-11e7-9668-0b0bc8de236e.jpg)
