### ISSUE TITLE
PPSSPP buildbot do not update after v1.5.4-336

### ISSUE THREAD

**Issue by CesarAxe** [hrydgard/ppsspp#10521]
Automated builds do not update after v1.5.4-336-ga989b4a93 - January 5.

**Comment by vnctdj** [comment]
I don't know if @Orphis is aware of this ?

**Comment by Orphis** [comment]
I wasn't, looking into it now.

**Comment by mrcmunir** [comment]
Is fixed no? I see v1.5.4-356-g0954f24a7 and downloading fine from https://buildbot.orphis.net/ppsspp/
