### ISSUE TITLE
Fate/Unlimited Codes shadows/lighting wrong

### ISSUE THREAD

**Issue by SakuraUO** [hrydgard/ppsspp#10532]
What happens?
https://drive.google.com/open?id=1L8rKX6Yu67cqHTjEzB8DZRx8LvbfVk3P

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

Windows 7 Pro
Dell OptiPlex 7010 
I5-3470 Quad-Core (3.20 GHz)
16GB Memory (RAM)
GeForce GT 1030 (2GB-VRAM)

**Comment by unknownbrackets** [comment]
Can you give some words other than a 1.1 GB file to download?  A screenshot perhaps?  The name of the game?

-[Unknown]

**Comment by asferot** [comment]
I downloaded the file. There are 2 videos and explanation of the problem... But...

I dont understand what you mean? "During the fight scenes Nothing happens"? What nothing? for me it looked like a normal gameplay.

**Comment by hrydgard** [comment]
Looks like a vertex lighting bug. We know we have a couple of those left, I think they're mostly related to specular lighting.

**Comment by unknownbrackets** [comment]
Is this still happening?  If so, could you try exporting a GE frame dump?  These help a lot.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by Panderner** [comment]
I tested this game in latest version of PPSSPP using Direct3D 11 i can't find this issue here:
![Screenshot (27)](https://user-images.githubusercontent.com/37503397/116807593-97febc80-ab66-11eb-8203-0db5cb687bbd.png)

Here's a GE dump:
[NPUH10009_0001.zip](https://github.com/hrydgard/ppsspp/files/6411041/NPUH10009_0001.zip)

**Comment by hrydgard** [comment]
Oh, maybe some of Unknown's lighting fixes fixed it. Closing.
