### ISSUE TITLE
[Windows] Can't load some files with a very long path.

### ISSUE THREAD

**Issue by AkiraMiyakoda** [hrydgard/ppsspp#10539]
### What happens?
When I try to open an ISO file with a very long path from File -> Load on the window menu, "Could not load the game. error reading file." error occurs. 
The built-in file browser works fine. 

Here "very long path" means a Unicode one which becomes longer than ```MAX_PATH``` or 260 bytes when converted into UTF-8.

### Cause

Look at the line 407 of ```Windows\MainWindowMenu.cpp```:
```
// TODO: What is this for / what does it fix?
if (browseDialog->GetType() != W32Util::AsyncBrowseDialog::DIR) {
	// Decode the filename with fullpath.
	char drive[MAX_PATH];
	char dir[MAX_PATH];
	char fname[MAX_PATH];
	char ext[MAX_PATH];
	_splitpath(filename.c_str(), drive, dir, fname, ext);
	filename = std::string(drive) + std::string(dir) + std::string(fname) + std::string(ext);
}
```
```filename``` contains the full path of the opened file in UTF-8. ```_splitpath``` fails and all the arrays become empty if ```filename``` is too long. So ```filename``` will be an empty string.

### Fix

Privately, I think we can safely remove the entire ```if``` block above. However, I have no idea what is it for.
Anyway, it's harmful to pass an UTF-8 path to ```_splitpath```.

**Comment by unknownbrackets** [comment]
https://github.com/hrydgard/ppsspp/blame/0421207d8bcf3848812dd272c93822c4a41d4b76/Windows/WndMainWindow.cpp#L855

That code came from the first commit pushed to GitHub.  I'm the one who added the comment questioning its goals.

I vote we remove it, doesn't seem useful to me.

-[Unknown]
