### ISSUE TITLE
Unable to compile project problem,help! 

### ISSUE THREAD

**Issue by fzx19910714** [hrydgard/ppsspp#10542]
I can't compile project, unable to regenerate arm64-v8a/x86 /x86_64/armeabi-v7a 。
 I want to know your development environment, the NDK versions, development tools,
why i can't. thanks

**Comment by hrydgard** [comment]
Please detail what errors you see. Make sure you follow the build instructions from https://github.com/hrydgard/ppsspp/wiki/Build-instructions . If those don't work properly we'll want to fix them.

**Comment by unknownbrackets** [comment]
I'm going to close this now - I'm guessing the build instructions helped.  If you're still having issues, make sure to paste the errors you're getting.  A comment here is fine - we'll reopen the issue if so.

-[Unknown]
