### ISSUE TITLE
Fix Multiplayer support for Mirage Arena - Kingdom Hearts BBS & FM

### ISSUE THREAD

**Issue by AkiraJkr** [hrydgard/ppsspp#10540]
Players are able to get in the lobby and connect normally, but upon starting any mode, they end in a infinite loading process, before it stops and disconnects both.

After selecting the mode and both press A then Start, they should be brought to the mode they chose and play it normally.

My specs are on https://steamcommunity.com/id/AkiraJkr - On the info box. Specs don't matter here, trust me.

Also, a user in the forums reported that Mirage Arena is fully working on the other emulator, JPCSP, or whatever it's spelled.

**Comment by adenovan** [comment]
if some dev want to fix it this might be related to sceNetAdhocctlGameMode that still unimplented on PPSSPP or not reaching AdhocMatching event callback that fake ppsspp thread execute , many games did not accept that fake callback NetAdhocTriggerCallback. Dragonball Z Shin Budokai and Digimon world re:digitize has the same issues.

**Comment by MorrisonGamer** [comment]
Then what about adding that option to the Networking tab, but keep it separated from everything and be simply named "Enable AdhocMatching(Fixes Kingdom Hearts, etc)", or something like that? It wouldn't hurt much.

**Comment by Superdoom4u** [comment]
yeah.... also the last message as like 2 years ago i am surprised no one has fixed it scene kingdom hearts is a big series and a lot of people love it

**Comment by Jerdo32** [comment]
I hope they eventually fix this.

**Comment by Jerdo32** [comment]
I hope they eventually fix this.

**Comment by Superdoom4u** [comment]
yay hrydgard added fixing it to the future mile stones :)

not sure if this will help but i have found someone who found a way to get kingdom hearts birth by sleep arena/versus mode working on the jpcsp emulator. i figure you could test it on that emulator and compare it to the ppsspp emulator to see why it works on jpcsp so you can get it working on ppsspp.

if i remember correctly what they did was dump the flash0 files form a real psp using psp dumper (if i remember correctly) then they remove some files that cause conflicts from the flash0 and they where able to play it using 1 pc with two jpcsp's (also another person got it to work online using hamachi on youtube)... their name on youtube is 亮onelight and FooniVentes

not sure if i am allowed to share links on this forum i never used it before but here is a video showing that it does work (FooniVentes gives a description in the description explaining how they got it working)
亮onelight video: https://youtu.be/DFZCOhJVXpQ
FooniVentes video: https://youtu.be/oxy_tBSZJGs

hopefully this helps ;)

**Comment by MojoJojoDojo** [comment]
@adenovan The Shin Budokai games work now on AdamN/Azuka test builds.

**Comment by adenovan** [comment]
@ANR2ME summoning the dev here if shin budokai already fixed it will not be long to see PR about that , maybe he still have WIP in the branch or some testing

**Comment by MeijiTsukiKora** [comment]
please someone fix this issue,it would be so great to play the arena in this game,I've tried to no avail to get everything to work,even with jpcsp..nothing....please!

**Comment by Jerdo32** [comment]
@MeijiTsukiKora It's already on Future Milestones, in other words, it's already known and they'll try to fix it.

**Comment by MojoJojoDojo** [comment]
Arena VS works now so the only thing left is the coop mode.

**Comment by hrydgard** [comment]
Is this fixed now with https://github.com/hrydgard/ppsspp/pull/13318 merged?

**Comment by hrydgard** [comment]
Partially fixed by https://github.com/hrydgard/ppsspp/pull/13318 .

**Comment by MojoJojoDojo** [comment]
Ah nvm Arena is the coop mode and that works.
Both Arena and VS modes.

**Comment by hrydgard** [comment]
Ah so we can close this then?

**Comment by MojoJojoDojo** [comment]
Yeah you can close this now.
It's fixed.

**Comment by ANR2ME** [comment]
> 
> 
> Ah so we can close this then?

I think so, all multiplayer modes are working properly now, but i only tested them on localhost tho

**Comment by Pik-a-boo** [comment]
Working online as well tested with 2 players.
