### ISSUE TITLE
I lost access to ppsspp gold and was not refunded play store

### ISSUE THREAD

**Issue by SamueldeSena** [hrydgard/ppsspp#10555]
I paid 15.99 reais and the refund show of 12.99 was not that I paid the app is very bad on my cell phone and I want to talk directly to the developer to solve my case and also did not enter the amount into my account

**Comment by hrydgard** [comment]
Please email me at hrydgard@gmail.com and in the e-mail, tell me your email address that you use for your account. I'll fix up whatever went wrong.
