### ISSUE TITLE
MGS Peace Walker Online Problem

### ISSUE THREAD

**Issue by Dawnmetty** [hrydgard/ppsspp#10559]
What happens?

Before explaining the problem, i need to say that this problem has NEVER occurred during my playthrough with my friend. We finished the game with no problems whatsoever and when we started doing the Extra Ops, this problem started happening.

What happens is, we join a lobby, start the OP, and we play for 1 minute or 30 seconds (it varies a lot, don't know why too) and suddenly my friend's FPS drops to 1 and it stays like that until i (or him) disconnect,when i disconnect from the game, his FPS goes to 20 again and all is normal. (Note: He never had FPS issues and i'm hosting) So we tried to make him host a game and me joining, same problem. In my vision he simply stops or keeps running in circles while the words "CONNECTION UNSTABLE" are in red and stays like that for some time.

Sometimes the game simply works with no problems, but sometimes we cannot play and there's nothing we can do about it (as far as we know)

Don't know if this is the right place to post, but i'm desperate and i really want a fix, sorry if i'm doing something wrong but thanks anyway.

**Comment by adenovan** [comment]
does you play locally with lan connection or over internet with some vpn software? if the connection has very high latency some games might wait some packet and start dropping the fps to keep in sync with other peer. its happen on dissidia DLC character as well 65536 byte data transfer every 1ms , the buffer size of transfer data is large and sometimes it not reached to the other peer over internet that make the game desync or stuck.

**Comment by unknownbrackets** [comment]
Is this still an issue on the latest git build with recent networking improvements?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
