### ISSUE TITLE
Question about memory usage:)

### ISSUE THREAD

**Issue by KMFDManic** [hrydgard/ppsspp#10564]
What happens?
Attempting to get the Core working on arm.  It works via Uart Connection with Command Line Prompts. But, it tries to use 256MB of Memory for some reason or another.  I am curious as to what reason this may be happening.  Is there a specific amount of memory allocated for the Emulator, by chance?  My first assumption was something akin to the original 256 MB Card that came with the PSP 1000:)  

What *should* happen?

I am interested in any input that may help as far as Memory Stick Memory Allocation, etc, to help get this more optimally running for the SNES Classic:)  

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

SNES Classic

Thanks for the response!

**Comment by hrydgard** [comment]
PPSSPP allocates a bunch of memory for various uses, 64MB RAM + 4MB VRAM for the PSP, then a large buffer for the JIT to store converted code, then textures take up space etc.

Some of the memory allocations (for RAM and VRAM) need to be allocated at specific distances from each other, so to find a contiguous space for those we do mmap specifically 256MB of memory (on 32-bit), see the bottom of MemArenaPosix.cpp. We then drop it immediately and make the proper smaller allocations.

Is that a problem for the SNES classic hardware, does the mmap call fail?

**Comment by madmonkey1907** [comment]
mmap call fails, there is just 256m of physical memory total and no swap on normal setups.
I got it to work with echo "1" > "/proc/sys/vm/overcommit_memory", not sure if this subverts whatever call to mmap tries to achive?
maybe MAP_NORESERVE and then holding on to mapped area will work better in this case?

**Comment by hrydgard** [comment]
Try it and send a pull request with the change if it works :)

256 megs is pretty tight for PPSSPP though, might just barely work depending on the games you run.

**Comment by KMFDManic** [comment]
@hrydgard I am going to record and post a video shortly.  I will link to it in a response:)  For what it's worth, it is pretty incredible being able to run it.  Truly truly excellent work on the Core.  I have been a tremendous fan of the emulator for quite some time now, and have been running it on my Android Phone ever since I got a Samsung Galaxy S5 and on:)  Before that, I primarily ran everything via a custom PSP:)  Anyways, I will post video shortly:)

**Comment by madmonkey1907** [comment]
thanks, I'll try, but I don't understand the purpose of it. changing to not calling munmap looks like pretty big change, which might break other platforms.
I guess not all games will work, but lunar works fine, mostly 60fps, sometimes dips to 30-40, but that might be because of slow storage device. I have no speakers here though, so no idea how sound works.

Mem: 215716K used, 35880K free, 21448K shrd, 13176K buff, 108884K cached
CPU: 16.4% usr  2.0% sys  0.0% nic 81.5% idle  0.0% io  0.0% irq  0.0% sirq
Load average: 0.76 0.64 0.40 3/84 7665
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
 2279  2260 root     R     244m 99.3   0 15.1 retroarch -c /etc/libretro/retroar

**Comment by KMFDManic** [comment]
@hrydgard 

https://www.youtube.com/watch?v=nr0B-puYYiM

Much more than I could have hoped for:)  3d Games do not fare so well:)  But, 2d ones most certainly are very acceptable.  Some sort of optimization that might help be able to "quit" the games a little faster, would be something to strive for, if we can possibly pull it off!  But, I am very glad to have this as part of the working Cores for NES/SNES Classic now, thanks to your amazing work and Madmonkey's:)

**Comment by KMFDManic** [comment]
Thanks again for the assistance, @hrydgard , got it running quite nicely now, on SNES Classic/NES Classic, with quick exits and saves both working. I appreciate all you've done to make the Core so amazing.

**Comment by hrydgard** [comment]
@KMFDManic , what made the exits quick? (or rather, what made them slow before?)

**Comment by KMFDManic** [comment]
@hrydgard The 256 MB limit would max out cache upon attempting to exit games, locking them up for 20-40 seconds.  I devised a clever workaround, wherein I would load into a Dummy Core, after ensuring saves are complete, then exit from the Dummy Core.  In this case, the great puzzle Core, 2048 makes a great escape route.  It instantly clears up cache, also allowing a clean SIGINT exit.  I also go over some examples of Games in action, and minor tweaks to run them more optimally in my Phase 2, Phase 3, and Final Test videos.  You can view them from my link above.  Thanks again.
