### ISSUE TITLE
Graphic issues on some Mali GPUs

### ISSUE THREAD

**Issue by GuilhermeGS2** [hrydgard/ppsspp#10569]
I reported it some months ago in another thread, some "ghosting"/random transparent HUD textures on scren running games like Midnight Club 3, Naruto Shippuden Ultimate Ninja Impact, now with new GL manager also happens sometimes on God of War Ghost of Sparta. The issue is present on Mali T720 (Galaxy J7 2015) and was on Mali 400 (Galaxy SII), but not on newer Mali T830 (Galaxy J7 Metal). Aparently it got worse on new GL manager, and also happens with other games, some are unplayable because of these issues.

**Comment by hrydgard** [comment]
Screenshots please.

**Comment by GuilhermeGS2** [comment]
https://ibb.co/fVWDYm
https://ibb.co/mTYhR6
https://ibb.co/ir6QeR
https://ibb.co/c7NsR6

These are the screenshots I take two months ago. MC3 can be "fixed" if switch between different rendering resolutions until get a sastifatory graphic (with minor issue). This also happens on Ridge Racer 2, now with GL render manager isn't playable with hood camera (black background and some textures on screen), same with Gran Turismo but changing camera doesn't affect.

**Comment by brujo5** [comment]
No issue on Mali T760 
Games  run faster with the new GL Threading

**Comment by GuilhermeGS2** [comment]
It's really faster than before, MC3 now running 20-30 FPS 1x resolution, but this issue plus low resolution makes the gameplay very annoying.

**Comment by PepeJulio** [comment]
Mali T-860 seems to be alright...

**Comment by hrydgard** [comment]
@GuilhermeGS2 Try ridge racer again with the latest commits.

**Comment by GuilhermeGS2** [comment]
@hrydgard it's worse now:

https://ibb.co/b4YG3m
https://ibb.co/kzHb3m
https://ibb.co/bD79Om

Mali T760 and T860 are newer than T720, it must be a issue with older versions.

**Comment by GuilhermeGS2** [comment]
@hrydgard the buffer rendering issue in Thrillville games is back in this build too.

**Comment by hrydgard** [comment]
Oh, interesting. Well, should not be hard to fix...

**Comment by hrydgard** [comment]
Think I got it, https://github.com/hrydgard/ppsspp/commit/c21b02a22dcf9b88c4e89c064f771983b1409a83

**Comment by GuilhermeGS2** [comment]
Thanks! Now the upscale and Ridge Racer/Gran Turismo black screen issues have been fixed. The "ghosting HUD textures" are still present. When I get some time I'll search for the last build without that issue.

**Comment by GuilhermeGS2** [comment]
Was quick! The last build without this issue is 1.4.2-799-gbabfec523.

**Comment by unknownbrackets** [comment]
I guess that implicates 23f78193295a78d398107b0349f436ada28abe3a?  The functional difference there is that it clears more state dirty flags.

A few ideas:

 * To confirm, this happens even with frameskip off, right?
 * Does this happen only on devices without GLES3?
 * Does it go away (potentially with other worse effects) with "disable slower effects" enabled?

If the answers were all yes, then my suspicion is a shaded blit (maybe a render-to-self or complex shading copy) that happens after state is setup and leaves things dirty.

-[Unknown]

**Comment by GuilhermeGS2** [comment]
@unknownbrackets 
-I don't use frameskip, so yes, it happens!
-No, Mali T720MP2 is GLES 3.1.
-With "disable slower effects" it looks fixed, but in MC3 the cars are white.

**Comment by unknownbrackets** [comment]
Does this still happen in latest git?

-[Unknown]

**Comment by GuilhermeGS2** [comment]
Sorry for late reply. After I installed a custom kernel with new driver version (r15p0, previously was r7p0), the most issues were fixed. Someone else with that old driver will have to try it.

**Comment by hrydgard** [comment]
If it's thus fixed in the newer drivers, then this problem will go away over time, and is less worthy of spending time on. Closing for now.
