### ISSUE TITLE
Opengl crash all games Android 

### ISSUE THREAD

**Issue by Blacob777** [hrydgard/ppsspp#10567]
Vulkan working, Last build 
![screenshot_2018-01-31-22-13-00-356_com miui bugreport](https://user-images.githubusercontent.com/29165096/35627638-7d8f81c0-06d4-11e8-8ef9-4ae703a596b9.png)

**Comment by hrydgard** [comment]
This one is very odd, haven't seen it on my devices..

**Comment by mrcmunir** [comment]
libllvm-glnext.so is part from Adreno GPU drivers from Adreno 400 and higher .
So it must be related to GPUS Adreno i think.

**Comment by hrydgard** [comment]
If you had any postprocessing effects on, this might have been caused by a bug I fixed recently, might be worth trying the latest build.

**Comment by Blacob777** [comment]
no changes with latest build, opengl chrashed app, postprocessing off

**Comment by Blacob777** [comment]
now all games working, fixed
