### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [hrydgard/ppsspp#1056]
I would like to point out that identifiers like "[`_MEMMAP_H`](https://github.com/hrydgard/ppsspp/blob/cf2a1dd3d20a12597c474a0d3f468b00e8b892c5/Core/MemMap.h#L18)" and "[`_JIT_ABI_H_`](https://github.com/hrydgard/ppsspp/blob/64cc57370386d28bdeab2854682498f1553266f0/Common/ABI.h#L18)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL32-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL32-CPPDonotdeclareordefineareservedidentifier-NoncompliantCodeExampleHeaderGuard) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by hrydgard** [comment]
We've mostly switched to #pragma once. As for the rest, it doesn't really seem worthwhile to cleanup so I'm closing this.

**Comment by elfring** [comment]
How do you think about to avoid that [this software](https://github.com/hrydgard/ppsspp/blob/aa927e0681ed76fec3b540218981a2c407a78e47/Core/MemMap.h#L147 "Update candidate") [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by hrydgard** [comment]
I'm sure we do in many much worse ways than having identifiers starting with __sce or __Kernel. Better focus on other things than names that will never collide with anything anyway.

**Comment by elfring** [comment]
I propose to reconsider the tampering with [the reserved name space](https://en.cppreference.com/w/c/language/identifier#Reserved_identifiers "Description for reserved identifiers") at more source code places.
