### ISSUE TITLE
GL threading - postprocessing broken

### ISSUE THREAD

**Issue by JhonLoveJoy** [hrydgard/ppsspp#10566]
**PC Specs:**

Windows 7 x64
GPU: 7570M

--------------------------------

**Game:** Monster Hunter Freedom Unite

FrameBuffer on: https://i.imgur.com/3rQAuna.png

With Framebuffer off it works normally - with some instability when changing graphics settings like V-Sync and resolution, and eventual crashes._ 

**PS:** God of War: Chains of Olympus and Monster Hunter 3rd portable also suffer from the same instability issue._

**Comment by hrydgard** [comment]
Huh, that looks like a recompiled postprocessing shader or something .. 

Are you using OpenGL backend?

**Comment by JhonLoveJoy** [comment]
Yeap, the problems/bugs happen only on OpenGL.

**Comment by hrydgard** [comment]
If you scroll up a big in that debug console, can you paste the start of that error dump?

**Comment by JhonLoveJoy** [comment]
Sure.

**Full error log:** https://i.imgur.com/3dNpxib.png

**Comment by hrydgard** [comment]
Thanks. If you turn off Postprocessing, what happens?
