### ISSUE TITLE
Crashs on Android

### ISSUE THREAD

**Issue by GuilhermeGS2** [hrydgard/ppsspp#10568]
I noticed it before the GL threading get merged to master, but I thought it was some issue with my gl-render-manager build, but also heppens with new buildbot builds. First time when we allow PPSSPP to read files, it freezes, we need to restart the app. Some times when we open the app it's just black screen. On my old Galaxy SII when I try to open most of my games the app show black screen for a while then close.

**Comment by hrydgard** [comment]
Yeah, I've seen the same, will look into it.

**Comment by hrydgard** [comment]
@GuilhermeGS2  how is this now?

**Comment by GuilhermeGS2** [comment]
It seems fine (no crash), but some games are running slower than normal OpenGL on SII.

**Comment by unknownbrackets** [comment]
Okay, we should probably open a separate issue for that if there's something specific we can look into.

Sounds like this issue is fixed though.

-[Unknown]
