### ISSUE TITLE
Crashes on PPSSPP 1.5.4-488-gc21b02a22 (OpenGL) [Render Manager]

### ISSUE THREAD

**Issue by ReilerTheDragonknight** [hrydgard/ppsspp#10578]
Every time I try to open a game with the OpenGL renderer, once it finally loads, PPSSPP crashes. The debug console doesn't give me anything useful to work with. It's incredibly inconsistent. Most of the time it crashes, other times it doesn't crash and loads up fine. However, Direct3D9 works fine, but I don't have support for Direct3D11 because of an old graphics card, which only supports OpenGL 2.0. This issue also occurs in many other games, and again the debug console doesn't give me anything.

What really should happen (as we all expect to) is the game to boot up fine without any issues, if maybe a little slowdown at the start as the CPU and GPU get to the higher rendering levels. Since it's inconsistent, I've not been able to replicate it 100% of the time, and the debug console doesn't give me anything either. 
To really replicate the bug: Just go with OpenGL and try to boot the game, as I've not been able to replicate as frequently as an actual issue.

However, I believe it's a hardware issue of my own, but I also don't believe it because I've been able to play fine up until this point. I have an AMD Athlon II 170u, Geforce 6150SE nForce 430, and 2GB of RAM.

I also included this picture to see if that helps anything regarding this issue. Thanks a lot for reading this.

![discord_2018-02-03_18-35-52](https://user-images.githubusercontent.com/22803374/35770403-63e58c84-0912-11e8-80f0-84f462fd7700.png)

**Comment by jpcima** [comment]
I believe to also encounter the bug described here.
I observe it after upgrading from 2ae2dd7d4 (r381) to c21b02a22 (r488).

GL related crash after starting a game.
I ran it in a debugger and I looked for relevant commits in that timeframe. I found that reverting 3a988400a702ede4137ee3f6d885796c03d727ea worked around the crash for me.

I'm including a partial valgrind log. You will see it relates to shader compilation and the GL deleter.
x86_64 Linux
04:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] RV630 XT [Radeon HD 2600 XT]

    OpenGL core profile version string: 3.3 (Core Profile) Mesa 17.3.3
    OpenGL core profile shading language version string: 3.30
    OpenGL version string: 3.0 Mesa 17.3.3
    OpenGL ES profile version string: OpenGL ES 3.0 Mesa 17.3.3
    OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00


[vg-bug.log](https://github.com/hrydgard/ppsspp/files/1692163/vg-bug.log)

**Comment by hrydgard** [comment]
Yeah, I think I need to rethink #3a98840...

**Comment by jpcima** [comment]
Update on 39fd77b35 after doing a quick test
As far I am concerned, the games start and run without having apparent problems.
I have an occasional segfault when I close but it has possibly nothing to do. I will run a debug build to check what causes it.
