### ISSUE TITLE
GL threading - Crash when saving on emulator. 

### ISSUE THREAD

**Issue by JhonLoveJoy** [hrydgard/ppsspp#10572]
The option to save in the emulator causes crash in all games, and I can't post the error log because the emulator closes itself... 

 Again, it works normally in DX9 and DX11.

_PC: Win 7 x64 @ HD 7570M_
_Tested on latest build._

**Comment by hrydgard** [comment]
Do you mean savestates? In-game saves? I can't seem to reproduce the problem, everything works for me.

Can you explain more in detail when it crashes?

**Comment by JhonLoveJoy** [comment]
No. Save built-in on emulator (F2).

To reproduce the bug, you must do the following steps:

- Open a game.
- Change the language of the interface. (I can save again by doing this, but the bug happens again if I activate and deactivate the framebuffer)
- Turn off\on framebuffer.
- Try saving by pressing F2.

**Comment by hrydgard** [comment]
Strange. Tried all of that, can't seem to get it to happen..

**Comment by JhonLoveJoy** [comment]
Maybe this will help:

[ppsspplog.txt](https://github.com/hrydgard/ppsspp/files/1683755/ppsspplog.txt)

![image](https://user-images.githubusercontent.com/31490343/35654523-b575a434-06d4-11e8-86d0-0c2a6fbf8685.png)

**Comment by JhonLoveJoy** [comment]
**Update with latest build.** 

Now I can save if the framebuffer is active. However, By disables it and save pressing F2 the emulator still crashes and exit.

**Comment by unknownbrackets** [comment]
F2 means create a save state.

So what you're saying is: when you disable "buffered rendering", creating a save state causes a crash.

This is probably happening when it tries to create a screenshot.

-[Unknown]
