### ISSUE TITLE
Crash when Switching resolution

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#10579]
What happens?
When you switching resolution, emulator still stop working

What *should* happen? 
Build with new faster rendering

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
OpenGL 3.10 Lenovo K10a40

**Comment by hrydgard** [comment]
Yup, aware of this, related to all the other crashes after the new rendering was introduced. Working on some fixes.

**Comment by hrydgard** [comment]
Should be fixed now.

**Comment by marosis** [comment]
Yeah fixed thank you
