### ISSUE TITLE
PPSSPP won't start on macOS, issue with homebrew libzip 1.4.0 suspected

### ISSUE THREAD

**Issue by oatmeal** [hrydgard/ppsspp#10575]
What happens?

PPSSPP crashes on start ever since updating libzip from 1.3.0 to 1.4.0 with homebrew. Here's the relevant part of the crash message:

 "Dyld Error Message:
  Library not loaded: /usr/local/opt/libzip/lib/libzip.5.dylib
  Referenced from: /Applications/PPSSPPSDL.app/Contents/MacOS/PPSSPPSDL
  Reason: Incompatible library version: PPSSPPSDL requires version 6.0.0 or later, but libzip.5.dylib provides version 5.0.0"

What *should* happen?

PPSSPP should open normally. It worked fine yesterday before the libzip update.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

macOS 10.12.6

**Comment by oatmeal** [comment]
PPSSPP works again after downgrading the version of libzip from 1.4.0 to 1.3.0 following these instructions https://stackoverflow.com/a/4158763 . See also http://formulae.brew.sh/formula/libzip for the formula history.

(For anyone who wants to do this, run the following commands in this order:)
`brew uninstall libzip`
`cd $(brew --repository)/Library/Taps/homebrew/homebrew-core`
`git checkout b6d3796 -- Formula/libzip.rb`
`HOMEBREW_NO_AUTO_UPDATE=1 brew install libzip`

To keep homebrew from updating libzip to 1.4.0:
`brew pin libzip`

**Comment by TazLaud** [comment]
Same problem here.

macOS 10.12.5

@oatmeal thank you for the workaround but it's not working for me:
`fatal: invalid reference: b6d3796`

**Comment by hrydgard** [comment]
That should have taken care of it, let me know if you still have issues after that merge.

**Comment by Orphis** [comment]
If you upgrade your libraries in homebrew, you should rebuild any software built against them. That seems pretty standard to me.

**Comment by hrydgard** [comment]
I disagree, things shouldn't break this easily - you'd expect most libs to be reasonably backwards compatible. 

Also, we need to bundle a copy anyway for Android and Windows, so might as well use it on all platforms for consistency.

**Comment by TazLaud** [comment]
Any plans to update the macOS app without using vine or any equivalent?
