### ISSUE TITLE
ppsspp-sdl segmentation fault crash ubuntu 16.04

### ISSUE THREAD

**Issue by tiagoplacido** [hrydgard/ppsspp#10574]
Emulator crashes with every game with a segmentation fault 

Vulkan is not available.
W: file_util.cpp:175: IsDirectory: stat failed on /usr/games/assets/lang/en_US.ini
W: file_util.cpp:175: IsDirectory: stat failed on /usr/games/lang/en_US.ini
I: Config.cpp:431: Longest display side: -1 pixels. Choosing scale 1
42:45:011 Core/Config.cpp:1043 I[LOADER]: Loading controller config: /home/tiago/.config/ppsspp/PSP/SYSTEM/controls.ini
Pixels: 960 x 544
Virtual pixels: 960 x 544
OpenGL 2.0 or higher.
I: gpu_features.cpp:136: GPU Vendor : NVIDIA Corporation ; renderer: GeForce GTX 560M/PCIe/SSE2 version str: 4.6.0 NVIDIA 390.25 ; GLSL version str: 4.60 NVIDIA
I: thin3d_gl.cpp:234: Shader module created (0x27c3e90)
I: thin3d_gl.cpp:234: Shader module created (0x2655f50)
I: thin3d_gl.cpp:234: Shader module created (0x27c3d50)
I: thin3d_gl.cpp:234: Shader module created (0x27c3db0)
I: NativeApp.cpp:612: NativeInitGraphics
I: NativeApp.cpp:696: NativeInitGraphics completed
E: SDLMain.cpp:976: Output audio samples: 1024 (requested: 2048)
loading control pad mappings from gamecontrollerdb.txt: SUCCESS!
W: file_util.cpp:175: IsDirectory: stat failed on /usr/games/assets/flash0/font/jpn0.pgf
W: file_util.cpp:175: IsDirectory: stat failed on /usr/games/flash0/font/jpn0.pgf
I: GLRenderManager.cpp:110: Running first frame (0)
42:45:092 thin3d/GLQueueRunner.cpp:285 W[G3D]: Got an error after init: 00000500 (GL_INVALID_ENUM)
42:51:792 Core/Config.cpp:1370 I[LOADER]: Failed to read /home/tiago/.config/ppsspp/PSP/SYSTEM/NPEG00023_ppsspp.ini. No game-specific settings found, using global defaults.
42:51:792 Core/System.cpp:304 I[BOOT]: PPSSPP v1.5.4
42:51:793 Core/MemMap.cpp:291 I[MEMMAP]: Memory system initialized. Base at 0x2300000000 (RAM at @ 0x2308000000, uncached @ 0x2348000000)
42:51:793 Core/PSPLoaders.cpp:194 I[LOADER]: NPEG00023 : God of War: Chains of Olympus
42:51:793 Core/Config.cpp:1370 I[LOADER]: Failed to read /home/tiago/.config/ppsspp/PSP/SYSTEM/NPEG00023_ppsspp.ini. No game-specific settings found, using global defaults.
42:51:793 Core/PSPLoaders.cpp:253 I[LOADER]: Loading disc0:/PSP_GAME/SYSDIR/EBOOT.BIN...
42:51:794 HLE/sceKernelMemory.cpp:434 I[SCEKERNEL]: Kernel and user memory pools initialized
W: file_util.cpp:175: IsDirectory: stat failed on /usr/games/assets/flash0/font/jpn0.pgf
W: file_util.cpp:175: IsDirectory: stat failed on /usr/games/flash0/font/jpn0.pgf
42:51:827 HLE/sceKernel.cpp:154 I[SCEKERNEL]: Kernel initialized.
42:51:881 Util/BlockAllocator.cpp:392 I[SCEKERNEL]: -----------
42:51:881 Util/BlockAllocator.cpp:396 I[SCEKERNEL]: Block: 08800000 - 08804000 size 00004000 taken=1 tag=usersystemlib
42:51:881 Util/BlockAllocator.cpp:396 I[SCEKERNEL]: Block: 08804000 - 08b70200 size 0036c200 taken=1 tag=ELF/dax
42:51:881 Util/BlockAllocator.cpp:396 I[SCEKERNEL]: Block: 08b70200 - 0a000000 size 0148fe00 taken=0 tag=(untitled)
42:51:881 Util/BlockAllocator.cpp:398 I[SCEKERNEL]: -----------
42:51:883 HLE/sceKernelModule.cpp:1254 I[LOADER]: Module dax: 00000000 08b05d08 08b05d20
42:52:538 HLE/sceKernelModule.cpp:1341 I[LOADER]: Exporting ent 0 named dax, 2 funcs, 4 vars, resident 08b0607c
42:52:538 HLE/sceKernelModule.cpp:1647 I[LOADER]: Module entry: 08807b88
W: file_util.cpp:175: IsDirectory: stat failed on /usr/games/assets/flash0/font/jpn0.pgf
W: file_util.cpp:175: IsDirectory: stat failed on /usr/games/flash0/font/jpn0.pgf
42:52:545 root         N[BOOT]: UI/EmuScreen.cpp:244 Loading /home/tiago/Games/PSP/God of War - Chains of Olympus.iso...
42:52:562 root         I[SCEKERNEL]: HLE/sceKernelThread.cpp:19 276=sceKernelCreateThread(user_main, 08807c9c, 00000020, 262144, 80004000, 00000000)
42:52:562 root         I[SCEKERNEL]: HLE/sceKernelThread.cpp:20 0=sceKernelStartThread(276, 33, 09fffed0)
42:52:562 root         I[SCEKERNEL]: HLE/sceKernelThread.cpp:21 __KernelReturnFromThread: 0
42:52:569 user_main    I[SCEKERNEL]: HLE/sceKernelThread.cpp:19 278=sceKernelCreateThread(ExitCallbackThread, 0880b4c4, 00000010, 4096, 00200000, 00000000)
42:52:569 user_main    I[SCEKERNEL]: HLE/sceKernelThread.cpp:20 0=sceKernelStartThread(278, 0, 00000000)
42:52:569 user_main    I[HLE]: HLE/scePower.cpp:384 scePowerSetClockFrequency(333,333,166)
Falha de segmentação (imagem do núcleo gravada)

What *should* happen?
 open emulator chose a game and play

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Ubuntu 16.04
ppsspp- sdl from the unstable ppa version 1.5.4-r201802021307-c21b02a-80~ubuntu16.04.1 with default settings
GPU gtx560m with proprietary drivers

**Comment by hrydgard** [comment]
You think you can run under GDB and get a stack trace?   (bt)

**Comment by hrydgard** [comment]
@tiagoplacido  Is this still happening with a fresh build?

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
