### ISSUE TITLE
Colin McRae Dirt 2 corrupted grafics after #10411

### ISSUE THREAD

**Issue by MarcoEstevez** [hrydgard/ppsspp#10570]
Dirt 2 seems regresed on OpengGL after merging #10411

Internal Resolution x1 looks fine
![image](https://user-images.githubusercontent.com/3447089/35639505-aa0074c2-06ba-11e8-91e2-a8e6873c05a9.png)

Internal Resolution x2 broken as any other greater than x1
![image](https://user-images.githubusercontent.com/3447089/35639529-c46356d6-06ba-11e8-9aa2-913d79fd6711.png)

Internal Resolution Automatic
![image](https://user-images.githubusercontent.com/3447089/35639576-e50f3828-06ba-11e8-9b65-31be60c2b53f.png)

**Comment by MarcoEstevez** [comment]
Actually this applies also to Coll

**Comment by hrydgard** [comment]
Thanks, good report.

**Comment by MarcoEstevez** [comment]
Ups wrong button.

Actually this also applies to Colin McRae 2005 Plus

![image](https://user-images.githubusercontent.com/3447089/35639992-2f355d96-06bc-11e8-938d-aef9317c966f.png)

Looks like renders correctly at Internal resolution the top left corner, rest of the screen is just randon data on the buffers

**Comment by MarcoEstevez** [comment]
Ummm...

Sorry hrydgard my bad, I talked too fast, I downloaded now just #10411 and works fine, It had to be the latest PR #10566 then

**Comment by hrydgard** [comment]
I think https://github.com/hrydgard/ppsspp/commit/c21b02a22dcf9b88c4e89c064f771983b1409a83 fixes it.

**Comment by MarcoEstevez** [comment]
Wow, that was fast, Ill test it, BTW, great job on #10411, performance boost is hard to believe.

**Comment by MarcoEstevez** [comment]
At least on windows GL Performance is quite close to Vulkan one, and it doesn't stutter

![image](https://user-images.githubusercontent.com/3447089/35641542-bff61696-06c0-11e8-9fa7-f135bb0c40ef.png)

**Comment by MarcoEstevez** [comment]
The latest commit fixed #10566 IR Issue, Great job, and thanks  👍
