### ISSUE TITLE
Crash when changing resolution on Android Galaxy Note3

### ISSUE THREAD

**Issue by hanooty** [hrydgard/ppsspp#10576]
In last ppsspp build v1.5.4-488-gc21b02a22
Problem in 
Display Resolution  (HW scaler)
When I select auto or any part 2x ....etc 
Ppsspp don't work...
Try to fix it please 
Android galaxy note3 
Ram 3 gb
Resolution 1080×1920
GPU 
3D API ADRENO 330

**Comment by GuilhermeGS2** [comment]
It's a gl-render-manager issue, I noticed that too. The only way to change the scale is editing ppsspp.ini in PSP/SYSTEM.

**Comment by hanooty** [comment]
Yes...I try ed your idea and successful... I edited it from SYSTEM/PPSSPP.INI 
I hope problem will fix soon...
Thanks bro for your information

**Comment by hrydgard** [comment]
Fix underway in #10591

**Comment by hrydgard** [comment]
Should be fixed now.
