### ISSUE TITLE
Videos crashes

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#10587]
What happens?
A lot of games Are crashing when playing videos

What *should* happen?

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Lenovo K10a40 OpenGL 3.10

**Comment by hrydgard** [comment]
Is this new, does it work on the same device with older versions of PPSSPP? If so, which was the first version where it started crashing?

**Comment by marosis** [comment]
I think in new faster rendering was everything ok. It Will be in newer builds

**Comment by marosis** [comment]
Looks like fixed thank you
