### ISSUE TITLE
Graphical glitches in Ys: the Oath in Felghana

### ISSUE THREAD

**Issue by kurayami6** [hrydgard/ppsspp#10583]
What happens?

A large grid of dark circles follows the player character around.

What *should* happen?

Not that.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

PPSSPP version 1.5.4-503. OpenGL, all settings default. Windows 7. GTX 970, i5. 

![capture](https://user-images.githubusercontent.com/31968468/35876758-5e959258-0bc7-11e8-8f23-88c841ab40d0.PNG)

![caputre2](https://user-images.githubusercontent.com/31968468/35876766-6453d7fe-0bc7-11e8-92ec-0cb4e7c9e861.PNG)

**Comment by hrydgard** [comment]
Oh, this one again. Clearly an issue with texture wrap mode in the new gl-render-manager.

**Comment by hrydgard** [comment]
That fix is pretty likely to take care of it.

**Comment by kurayami6** [comment]
Yes, that fixed it. The crashing when closing PPSSPP and changing backends is also fixed, so you can close my other issue as well.
