### ISSUE TITLE
Can't build source code in Macos

### ISSUE THREAD

**Issue by saber1024** [hrydgard/ppsspp#10585]
try cmake or ./b.sh --qt (installed qt in mac)

all generate the fllow  error code

`Normal Build
-- No build type selected, default to Release
CMAKE_SYSTEM_PROCESSOR: x86_64
Generating for x86, Release
Generating for x86_64, Release
CMake Error at ext/CMakeLists.txt:3 (add_subdirectory):
  The source directory

    /Users/zhushuai/desktop/ppsspp/ext/armips

  does not contain a CMakeLists.txt file.

CMake Error at ext/CMakeLists.txt:11 (add_subdirectory):
  The source directory

    /Users/zhushuai/desktop/ppsspp/ext/glslang

  does not contain a CMakeLists.txt file.
CMake Error at cmake/Modules/FindFFmpeg.cmake:147 (list):
  list sub-command REMOVE_DUPLICATES requires list to be present.
Call Stack (most recent call first):
  CMakeLists.txt:490 (find_package)
CMake Error at /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find FFmpeg (missing: FFmpeg_INCLUDE_avcodec
  FFmpeg_LIBRARY_avcodec FFmpeg_INCLUDE_avformat FFmpeg_LIBRARY_avformat
  FFmpeg_INCLUDE_avutil FFmpeg_LIBRARY_avutil FFmpeg_INCLUDE_swresample
  FFmpeg_LIBRARY_swresample FFmpeg_INCLUDE_swscale FFmpeg_LIBRARY_swscale
  avcodec avformat avutil swresample swscale)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindFFmpeg.cmake:154 (find_package_handle_standard_args)
  CMakeLists.txt:490 (find_package)`

I've already installed FFmpeg using Homebrew

> ffmpeg version 3.4.1 Copyright (c) 2000-2017 the FFmpeg developers
  built with Apple LLVM version 9.0.0 (clang-900.0.39.2)

Platform-specific (Mac OS X)

**Comment by terrycloth** [comment]
@saber1024 I'm running into a similar issue. What was your solution?

**Comment by hrydgard** [comment]
@terrycloth ```git submodule update --init --recursive```
