### ISSUE TITLE
Dante's inferno bad performance and issues on OpenGL

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#10589]
What happens?
Dante's inferno can't reach 100% emulation Speed. In game, in videos, in menu, never reached 100%!!! I've tried 30 fps cheat but you have automaticaly lower fps. 60fps cheat= 20-25/25fps (+-80%+) in menu.  30fps cheat 17-23/25fps in menu. (Interresting). Next issue Is this:https://photos.app.goo.gl/aa943ulWQNWpeXeZ2 (sometimes it Is ok sometimes not)

https://photos.app.goo.gl/zyaEaqElXowtkYXx1 retain changed textures(sometimes slower)-ON. When it Is OFF, issue Is fixed. Used 1xPSP resolution for best performance
What *should* happen?

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
OpenGL 3.10 android Lenovo K10a40

**Comment by marosis** [comment]
Btw in videos Is bad performance too

**Comment by marosis** [comment]
And if you using bigger resolution than 1xPSP, you will get new glitch

**Comment by ppmeis** [comment]
According to your device, It has a Mediatek MT6735P, which is a quad core 1GHz processor. Its a bit low to get full speed in this kind of games (it will happen I guess in GoW and others).

**Comment by unknownbrackets** [comment]
Also, retain changed textures increased collisions.  Decent chance it would make this game slower, if it wasn't creating collisions.

I'm not sure what the cheats do, but usually higher fps cheats reduce performance.  In this case, I think there's a bug as I suspect the game ran 60 fps on a real PSP.  That said, the differences you're seeing could be a sign of power throttling your phone is doing - something PPSSPP has no control of.

We're always trying to improve performance, and aren't likely to stop.  That said, it's not really a bug we can do anything specific with if a weak CPU has trouble emulating more complicated games.  So I'm closing this - but we'll keep working on performance, as always.

It might be better to ask on the forum if anyone has found settings or any cheats to improve the performance.

-[Unknown]

**Comment by marosis** [comment]
Ok thank you unknown :)

**Comment by marosis** [comment]
Ppmeis interresting is, GOD OF WAR running in fullspeed with 222MHZ with new Faster rendering;). So this only have Dante's inferno. Maybe more games
