### ISSUE TITLE
Crashes related to GLRenderManager::Deleter (Gpu Adreno (TM) 304)

### ISSUE THREAD

**Issue by Endarko** [hrydgard/ppsspp#10590]
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
LineageOS Version: '13.0-20170902-UNOFFICIAL'
Build fingerprint: 'OnePlusOne/A0001/A0001:6.0.1/MHC19Q/ZNH2KAS1KN:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 28820, tid: 28834, name: Emu  >>> org.ppsspp.ppsspp <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: 'GLRenderManager.h:161 (Take): [IsEmpty()] Deleter already has stuff'
    r0 00000000  r1 000070a2  r2 00000006  r3 a0aff978
    r4 a0aff980  r5 a0aff930  r6 00000002  r7 0000010c
    r8 a1dc5388  r9 a0aff348  sl a0a01000  fp a15b8de1
    ip 00000006  sp a0afeec0  lr b6cc454d  pc b6cc693c  cpsr 40000010
    d0  ffffffffffffffff  d1  ffffffffffffffff
    d2  0000000000000073  d3  0000000000000074
    d4  0000000000000000  d5  0000000000000000
    d6  0000000000000000  d7  0000000000000000
    d8  0000000043f00000  d9  0000000044558000
    d10 0000000000000000  d11 0000000000000000
    d12 0000000000000000  d13 0000000000000000
    d14 0000000000000000  d15 0000000000000000
    d16 0000000000000000  d17 0000000000000000
    d18 0a1f6600a0428000  d19 0000000043f00000
    d20 0000000044558000  d21 000000003f800000
    d22 bb88888900000000  d23 0000000000000000
    d24 3d400e61ec39a5e6  d25 3fa55553e1053a42
    d26 3ef99342e0ee5069  d27 bf56c087e80f1e1a
    d28 3a5282e7a7c8eec2  d29 bf56c087e80f1e24
    d30 3783e9434058af91  d31 4012d97c80000000
    scr 20000093

backtrace:
    #00 pc 0004293c  /system/lib/libc.so (tgkill+12)
    #01 pc 00040549  /system/lib/libc.so (pthread_kill+32)
    #02 pc 0001c44f  /system/lib/libc.so (raise+10)
    #03 pc 00019601  /system/lib/libc.so (__libc_android_abort+34)
    #04 pc 00017514  /system/lib/libc.so (abort+4)
    #05 pc 00002d7b  /system/lib/liblog.so (__android_log_assert+86)
    #06 pc 0042e961  /data/app/org.ppsspp.ppsspp-2/lib/arm/libppsspp_jni.so (_Z16AndroidAssertLogPKcS0_iS0_S0_z+60)
    #07 pc 004c87e9  /data/app/org.ppsspp.ppsspp-2/lib/arm/libppsspp_jni.so (_ZN9GLDeleter4TakeERS_+80)
    #08 pc 004c8777  /data/app/org.ppsspp.ppsspp-2/lib/arm/libppsspp_jni.so (_ZN15GLRenderManager6FinishEv+498)
    #09 pc 004d7b19  /data/app/org.ppsspp.ppsspp-2/lib/arm/libppsspp_jni.so (_ZN13ScreenManager6renderEv+148)
    #10 pc 00439527  /data/app/org.ppsspp.ppsspp-2/lib/arm/libppsspp_jni.so (_Z12NativeRenderP15GraphicsContext+794)
    #11 pc 0043373d  /data/app/org.ppsspp.ppsspp-2/lib/arm/libppsspp_jni.so (_Z20UpdateRunLoopAndroidP7_JNIEnv+76)
    #12 pc 00434bf1  /data/app/org.ppsspp.ppsspp-2/lib/arm/libppsspp_jni.so
    #13 pc 002c0e17  /data/app/org.ppsspp.ppsspp-2/lib/arm/libppsspp_jni.so (_ZNSt6__ndk114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEPFvvEEEEEEPvSA_+54)
    #14 pc 0003fe4b  /system/lib/libc.so (_ZL15__pthread_startPv+30)
    #15 pc 00019c85  /system/lib/libc.so (__start_thread+6)

**Comment by hrydgard** [comment]
This one is known, will work on it soon.

**Comment by Endarko** [comment]
![screenshot_20180208-153705](https://user-images.githubusercontent.com/16800334/35965642-726fcc5c-0cb3-11e8-831d-ce9b3e3174d3.png)
background black superbike 2009

**Comment by hrydgard** [comment]
@Endarko That seems like an entirely separate problem? Please file it as such, and detail whether you're using OpenGL or Vulkan or D3D, and which device you're running it on.

Closing this, it should be fixed now.

**Comment by Endarko** [comment]
i'm use OpenGL mode

**Comment by hrydgard** [comment]
Even so, click "New Issue" on the top right and put your screenshot and all the other info there. This issue #10590 is fixed.

**Comment by Endarko** [comment]
![screenshot_20180208-211750](https://user-images.githubusercontent.com/16800334/35978296-39825e08-0cdd-11e8-867b-3044707d8328.png)
v1.5.4-521-gb9b41f52c can not play video in superbike game,

**Comment by hrydgard** [comment]
Since you're not listening, I created an issue here: https://github.com/hrydgard/ppsspp/issues/10595

Please add any further comments there.

**Comment by hrydgard** [comment]
This may have been fixed by #10596 .
