### ISSUE TITLE
Vulkan Performance Regression in Earth Defence Force 2

### ISSUE THREAD

**Issue by fivefeet8** [hrydgard/ppsspp#10597]
What happens?
Earth Defense Force 2 performance with the Vulkan render is below 50% ingame.  OpenGL now runs the game full speed when before it was at 50%.

What *should* happen?
In earlier builds the game ran 100% speed with the Vulkan path and 50% with OpenGL.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
This is on a Nvidia Shield TV.

**Comment by fivefeet8** [comment]
I did some more testing of previous builds and the last build where Vulkan performance was ok in this game was rev.  386 and before.  It was already slower than even earlier builds.  Any build above 386, and Vulkan is very slow in this game.

**Comment by hrydgard** [comment]
So 387 is really slower? Not much change in that vs 386..  I would rather expect 484 to be the first bad one, if anything...

**Comment by fivefeet8** [comment]
I think you're correct.  I didn't check 387, but all the 4xx revision I checked are slower with Vulkan.

**Comment by unknownbrackets** [comment]
Are you able to compile?  If you could try to bisect, it'd really help.  I think as long as you use the Vulkan backend there shouldn't be any crashes in that range, probably...

-[Unknown]

**Comment by hrydgard** [comment]
I've been looking at the diff restricted to Vulkan-related code between 386 and 484:

```git diff 26b146a24 22e28e218 Common/Vulkan ext/native/thin3d/Vulkan* GPU/Vulkan GPU/Common```

and I really can't see anything that would make it slower. I don't see any speed difference for Vulkan in other games on my computer or phones between these two revisions, though haven't tried the Shield TV yet due to minor setup inconveniences.

EDF2 is, if I remember correctly, one of those insane games that make many tens of thousands of draw call per frame because they switch backface culling every few triangles in order to be able to wind strips backwards, which is just dumb. You'd expect to see some change that would be likely to slow down making draw calls but I can't see anything in the diff.

**Comment by fivefeet8** [comment]
Hmm.  It may be something specific to the shield tv.  The game runs a lot faster with Vulkan on my zte phone with an adreno 5xx GPU.

**Comment by hrydgard** [comment]
So, I'm mystified. Tried a couple of my favorite performance-intense games and not a hint of a slowdown in newer builds as compared to #387. 

The buildbot hasn't started doing debug builds or something like that right @Orphis ?  :P  (not exactly likely...)

**Comment by unknownbrackets** [comment]
With #10973 merged, does this still happen?  Whatever the issue here, driver or otherwise, that change may have helped overcome the performance problems.

-[Unknown]

**Comment by fivefeet8** [comment]
I checked the game on my ZTE Snapdragon 820 phone and it seems Vulkan performance is up.  I'll check my Shield TV later tonight.

**Comment by fivefeet8** [comment]
Hmm.  Still seems quite slow with Vulkan on my Shield TV.  OpenGL is much faster still.

**Comment by fivefeet8** [comment]
Tested the recent code updates on my Shield TV and Snapdragon 820 phone and the low performance is still there.  OpenGl is much faster on both.

**Comment by unknownbrackets** [comment]
Note that #11172 has not yet been merged.

-[Unknown]

**Comment by unknownbrackets** [comment]
That change has not been merged, and some follow up issues fixed.  How does this look now?

-[Unknown]

**Comment by hrydgard** [comment]
s/not/now :)

**Comment by fivefeet8** [comment]
It looks amazing.  Both OpenGL and Vulkan are full speed on the game.  👍
