### ISSUE TITLE
SBK Superbike - videos don't play

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#10595]
What happens?

Videos don't play in OpenGL.

![screenshot_20180208-211750](https://user-images.githubusercontent.com/16800334/35978296-39825e08-0cdd-11e8-867b-3044707d8328.png)

What *should* happen?

Videos should play.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

Any, probably, since the gl render manager. Reported in https://github.com/hrydgard/ppsspp/issues/10590

**Comment by Endarko** [comment]
![Uploading Screenshot_20180209-085256.png…]()
![screenshot_20180209-085315](https://user-images.githubusercontent.com/16800334/36007997-ff77e8da-0d3c-11e8-874e-0987e221d923.png)

ppsspp-v1.5.4-526-g39fd77b35 fix play video and background not black screen

**Comment by unknownbrackets** [comment]
Does that mean this works now and can be closed?

-[Unknown]

**Comment by Endarko** [comment]
yes, please close
