### ISSUE TITLE
PSSPP crashes after reopening on Android.

### ISSUE THREAD

**Issue by blackman91** [hrydgard/ppsspp#10600]
Using the latest dev build, with vulkan the app crashes after selecting it again if you exit via recent apps or home button on Android 7. Doesn't crash for me with the gl renderer.

**Comment by fokee** [comment]
Yap same but on opengl too (meizu m3 note)

**Comment by SamueldeSena** [comment]
This issue has already been resolved in build version v1.5.4-562-g864eb5dca this topic can already be closed.
