### ISSUE TITLE
PPSSPP crashes while loading every game I've tried. v1.5.4-484 and up. Windows x86

### ISSUE THREAD

**Issue by Rekrullurker** [hrydgard/ppsspp#10601]
I'm using the Windows x86 version of PPSSPP and so far, versions of PPSSPP past v1.5.4-387 have crashed on literally every game that I've tried. These games work on v1.5.4-387, but crash on v1.5.4-484 or later. I have tested up to v1.5.4-537 and they crash on every one I've tried.

I tested the following games and every one of them crashed PPSSPP with a standard "PPSSPP has encountered an error and must close." message.

Burnout Dominator
BurnOut Legends
Death Jr. II - Root Of Evil
FlatOut Head On
James Cameron's Avatar - The Game
Juiced - Eliminator
Juiced 2 - Hot Import Nights
Medievil - Resurrection
Midnight Club 3 - DUB Edition
Midnight Club LA Remix
OutRun 2006 Coast 2 Coast
Pursuit Force
Pursuit Force - Extreme Justice
SoulCalibur IV - Broken Destiny

All of these games work fine on v1.5.4-387. Well, Juiced 2 and OutRun 2006 have graphical issues, but they work. For fastest results, test the game Juiced - Eliminator, that one crashed the fastest.

My system;

2.4Ghz Core-2-Duo
Windows SP Pro, SP3
4GB RAM
GT430 Graphics card
Onboard Realtek audio

**Comment by hrydgard** [comment]
Does it make a difference if you use OpenGL or Direct3D9 as the Graphics Backend?

**Comment by hrydgard** [comment]
Hm, this reproduces trivially on my XP VM just running the homebrew app "Moppi PSP Flower". Odd...

**Comment by Rekrullurker** [comment]
Yes, sorry, I meant to write Windows XP Pro, SP3. Sometimes I get ahead of myself and make dumb typos.

Also, yes, I just tested D3D9 as the backend and the games all work. I should have thought to test that first. So it seems the problem is only with the OpenGL backend.

**Comment by hrydgard** [comment]
Thanks for testing D3D9, that narrows it down a bit. Yeah, the GL backend is the major part that changed, pretty much got rewritten.

**Comment by hrydgard** [comment]
As a workaround it might be time to disable OpenGL support on XP anyway, the OS is 17 years old and the state of drivers isn't always the greatest...

**Comment by LunaMoo** [comment]
Or the official support for Win XP could as well be discontinued, finally dropping out the dependency on old SDK and XP compat stuff. It's not like d3d9 will ever get anything new that would enhance future experience of XP users and people who possibly have better hardware, but choose to use OS that doesn't support their hardware correctly should not be affecting majority of the other people.

 Just an observation, but as I understand most people for whom this dependency was kept(chinese userbase) actually do care about OGL part seeing how they spammed emotes in OGL render manager pr trying to convince everyone and their grandmother about importance of support for outdated/weak devices.:]

**Comment by unknownbrackets** [comment]
Hmm, I'm seeing an unaligned `pand`...

-[Unknown]

**Comment by hrydgard** [comment]
That's interesting. How are you seeing that?

**Comment by unknownbrackets** [comment]
The latest Windows 7 SDK (.NET 4) had a working WinDbg, used that.

-[Unknown]
