### ISSUE TITLE
PPSSPP crashes after setting the screen resolution

### ISSUE THREAD

**Issue by iArti** [hrydgard/ppsspp#10602]
Last build crashes when I try to change screen resolution (hardware screen resolution, not rendering) even without saving
It stuck to 2x PSP and I can't change it neither globally nor for one game
Also, my existing configs became screwed up and somewhere I have rendering resolution 1:1 but h/w resolution stuck to 2x PSP
Using latest ppsspp build on Xiaomi Mi Max (hydrogen) (Snapdragon 650/Adreno 510, Android 7.1.2)

**Comment by unknownbrackets** [comment]
When did this last work?

-[Unknown]

**Comment by hrydgard** [comment]
Which version exactly? This has been fixed again quite recently, might have been re-broken but hard to tell without knowing the specific version you tested.

**Comment by iArti** [comment]
Uh, I can't say where it worked last time, I hadn't tracked it
Now I'm using
1.5.4-541

**Comment by hrydgard** [comment]
Yeah, I can reproduce in Vulkan. Fix coming soon.

**Comment by SamueldeSena** [comment]
This issue has already been resolved in build version v1.5.4-562-g864eb5dca this topic can already be closed.
