### ISSUE TITLE
I can't get ppsspp to work on my iPad 1

### ISSUE THREAD

**Issue by chikipunk93** [hrydgard/ppsspp#10612]
What happens?
I have IOS 5.1.1 and tried installing the IPA through ITunes and it said the the app required a highers IOS version and won't let me install it, have the same problem installing it through cydia, app just crash upon start attempt.

What *should* happen?
Can review IOS 5.x compatility? Or maybe tell me what am I doing wrong.

Thank you

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

**Comment by unknownbrackets** [comment]
I think that the requirements were increased to iOS 8.  I believe this was to properly support devices like the iPad Pro which have a larger resolution, and was done as part of an effort to fix other bugs.

You might have to use an older version of PPSSPP to run on iOS 5.

-[Unknown]

**Comment by unknownbrackets** [comment]
Going to close this - it's not compatible anymore as noted above.  Sorry.

-[Unknown]
