### ISSUE TITLE
PPSSPP flickering screen!

### ISSUE THREAD

**Issue by blackman91** [hrydgard/ppsspp#10613]
Using latest dev on Android 4.2.2 tablet with mali GPU and the screen is flickering like crazy, see this short video:
https://drive.google.com/file/d/12f9Ym8JwP1HN_Y7RcdjKS0r8_BgKXX1U/view?usp=drivesdk

**Comment by FlatOutPS2** [comment]
I get the same on Windows (7) after booting a game with the OpenGL renderer. The in-game graphics are broken, and when I press escape to bring up the menu, it starts flickering like crazy like the video. Using Exit to menu send me to a black screen and switching to Direct3D11 crashed the emulator. :/

**Comment by unknownbrackets** [comment]
Is this with buffered rendering?

-[Unknown]

**Comment by FlatOutPS2** [comment]
> Is this with buffered rendering?

I didn't change any settings from the defaults of the build(nor did I import/copy anthing from older builds) . Switching between buffered rendering and skip buffer effects doesn't affect the issue.

**Comment by c3ntr0n800** [comment]
I've been having that issue as well with the Android build. It's completely fine for me on the Windows x64 build on 10, though.

**Comment by FlatOutPS2** [comment]
The Windows issue probably restricted to the (legacy) AMD OpenGL drivers.

**Comment by unknownbrackets** [comment]
Just to confirm, on legacy AMD on this Android device:

v1.5.4-545-g4ccf30d0a has no flickering.
v1.5.4-555-g4e5fb6e28 has flickering.
v1.5.4-562-g864eb5dca also has flickering.

Is that right?  I guess this means `glFlushMappedBufferRange` may not work correctly?

-[Unknown]

**Comment by hrydgard** [comment]
I thought I disabled the use of glMapBuffer and friends except on nVidia recently?

**Comment by FlatOutPS2** [comment]
> I thought I disabled the use of glMapBuffer and friends except on nVidia recently?

It's either something else failing or the GPU vendor check doesn't behave correctly, as there is no difference between v1.5.4-553 and v1.5.4-562. I assume it'll be the same for Android, as the latest build(562) had already been released by the time this issue was opened.

**Comment by unknownbrackets** [comment]
I think `glMapBufferRange` is still used when `gl_extensions.ARB_buffer_storage || gl_extensions.EXT_buffer_storage`...

-[Unknown]

**Comment by hrydgard** [comment]
Right... sigh.

**Comment by unknownbrackets** [comment]
From what I can see on one mobile device, it seems like the flush explicit bit makes it slower.  Removing that and the flushing makes it faster, but not much faster than without.

-[Unknown]

**Comment by hrydgard** [comment]
Seems like these bits are pretty much arbitrary driver-specific magic :P Maybe should just make a table of which bits to set for which vendor, heh...
