### ISSUE TITLE
Please Add Icon in Comboy key Setting

### ISSUE THREAD

**Issue by Endarko** [hrydgard/ppsspp#10614]
![1518548054-picsay](https://user-images.githubusercontent.com/16800334/36168638-aa9e1394-10f1-11e8-9888-79c5bad0598c.jpg)

@hrydgard please in combo key settings added icon like the one in the photo. so there are not just icons 1-5

**Comment by ResurrectionRedmi9** [comment]
There are many shape now on combo key icons.
![Screenshot_2021-09-14-17-19-47-534_org ppsspp ppsspp](https://user-images.githubusercontent.com/90336524/133231488-d1072314-54b2-4fca-a917-5fb5477283e1.jpg)

**Comment by Gamemulatorer** [comment]
Duplicate https://github.com/hrydgard/ppsspp/issues/14515
