### ISSUE TITLE
Black Screen [Android] 

### ISSUE THREAD

**Issue by Zytheus** [hrydgard/ppsspp#10619]
What happens?

Dynasty Warriors (2004)

Game refuses to load. The screen is black. No sounds are playing. Unable to progress. Buttons on screen work fine. 

What *should* happen?

Game should load as normal. 

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

Razer Phone (only one model) 

OS	Android 7.1.1 (Nougat)
Chipset	Qualcomm MSM8998 Snapdragon 835
CPU	Octa-core (4x2.35 GHz Kryo & 4x1.9 GHz Kryo)
GPU	Adreno 540

**Comment by ppmeis** [comment]
Tested on latest windows build, default settings. Game runs perfect:
![image](https://user-images.githubusercontent.com/4381277/36340539-939277b2-13df-11e8-8562-1efe0c89bea9.png)

Did you try in other backends (vulkan, OpenGL)?

**Comment by Zytheus** [comment]
Used another program for extracting my files. Seemed like an issue on my end with the programs. Something probably got corrupted in transit. 

Thanks for the help though.
