### ISSUE TITLE
NBA Live 10 arm texture problems

### ISSUE THREAD

**Issue by Levan7** [hrydgard/ppsspp#10617]
I am using the latest git build v1.5.4-562-g864eb5dca
and noticed that arm textures look strange.

![ulus10465_00000](https://user-images.githubusercontent.com/5770076/36273300-825d6378-129d-11e8-9656-2648b461b72e.jpg)
![ulus10465_00001](https://user-images.githubusercontent.com/5770076/36273301-827ed77e-129d-11e8-9158-ff466534717c.jpg)

**Comment by ppmeis** [comment]
Already reported in #6614
