### ISSUE TITLE
Fight night round 3 have extremly long loading

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#10622]
What happens?

What *should* happen?

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Android OpenGL

**Comment by marosis** [comment]
7 minutes

**Comment by unknownbrackets** [comment]
Is the game on your device's SD card?  Are you counting 7 minutes from clicking the game to the loading message going away, or until some other time?

If the game is running slow, it may appear to load slowly, but this could just be a performance problem.  7 minutes seems like a long time, but it's not a lot of detail.

Does this happen on other devices too?

Are you using default settings?

-[Unknown]

**Comment by ppmeis** [comment]
Tested with latest Windows build, default settings. Game loads just fine.

**Comment by marosis** [comment]
I have game on SD card And yeah 7 minutes after clicking to the game. Game normal running on 30fps with default settings. Interresting is, TEKKEN 6 loading only 5 seconds.

**Comment by marosis** [comment]
I forgot! game didn't have this long loading in last versions where wasn't this long loading

**Comment by marosis** [comment]
Game didn't have long loading in the older versions

**Comment by hrydgard** [comment]
How about the latest build now?

**Comment by marosis** [comment]
sorry. i will check it later because i don´t have phone :)

**Comment by marosis** [comment]
Fully fixed thank you! Closing
