### ISSUE TITLE
Font in-game save dialogs issues

### ISSUE THREAD

**Issue by Iemnur** [hrydgard/ppsspp#10621]
What happens?
The problem occurs in the save, load data game interface. 
Character not support from 0x1EA0 to 0x1EF9 (vietnamese character).

![ules01500_00000](https://user-images.githubusercontent.com/16165686/36338502-7002e63e-13e3-11e8-8cc8-ab16fabd6bc2.jpg)

Tested on build v1.5.4-562-g864eb5dca, v1.5.4 official...

**Comment by hrydgard** [comment]
Yeah, unfortunately we are currently unable to use the original PSP fonts when rendering the in-game save UI as we are doing that ourselves, not using the PSP sceFont library which we can't ship with the emulator (though we could manually pluck characters out of the font files...)

**Comment by ppmeis** [comment]
@hrydgard is there any way to do it manually? Because I have an original PSP, I can extract them from flash  memory. Does copy original fonts to the emulator solves the problem?

**Comment by hrydgard** [comment]
Like I said, when rendering these screens we use our own basic font system as we have to render them ourselves, they're not part of the game so we can't access the sceFont library as not all games even use that. There is currently no way, needs work.

**Comment by Magdno1** [comment]
Thank for working @hrydgard 

@ppmeis you can use atlastool in project to create your own font.
