### ISSUE TITLE
PPSSPP Crashing on Android Box

### ISSUE THREAD

**Issue by Pinhcy** [hrydgard/ppsspp#10625]
What happens?
PPSSPP crashing after I open my ISO file using latest version from play store. Latest dev build refuses to open at all and crashes immediately. 

What *should* happen?
ISO should open and be playable, have tested same ISOs on my S8 and they run fine.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

Custom Nexus Android TV Rom 7.1 

CPU: Amlogic S912 64 bit Octa core ARM Cortex-A53 CPU up to 2 GHz
GPU: ARM Mali-T820MP3 GPU up to 750MHz (DVFS)
RAM: 3GB DDR4

**Comment by unknownbrackets** [comment]
What was the most recent git build that worked fine (you can redownload and test them)?  What's the first one that stopped working?

-[Unknown]

**Comment by Pinhcy** [comment]
I have yet to have it work on this device. The only actual build that opens so far is 1.5.4 downloaded directly from the Play Store. 

These are what I have tried so far. 

v1.5.4-565-g78449ce67 - Does not open ( PPSSPP Has Stopped )
v1.5.4-562-g864eb5dca - Does not open ( PPSSPP Has Stopped )
v1.5.4-560-g038d8b7f3 - Does not open ( PPSSPP Has Stopped )
v1.5.4-557-g9e75358cd - Does not open ( PPSSPP Has Stopped )
v1.5.4-555-g4e5fb6e28 - Does not open ( PPSSPP Has Stopped )
v1.5.4-545-g4ccf30d0a - Does not open ( PPSSPP Has Stopped )
v1.5.4-541-gc6a9c884b - Does not open ( PPSSPP Has Stopped )
v1.5.4-538-g813c376ae - Does not open ( PPSSPP Has Stopped )
v1.5.4-537-g030de0ad0 - Does not open ( PPSSPP Has Stopped )
v1.5.4-530-g3c93eaf16 -  Does not open ( PPSSPP Has Stopped )

**Comment by Pinhcy** [comment]
I manage to get it working on with this one v1.3.0.1 https://www.ppsspp.org/files/1_3/ppsspp.apk 

This is one however https://www.ppsspp.org/files/1_4_2/ppsspp.apk 

Gave the same PPSSPP has stopped error

**Comment by Pinhcy** [comment]
v1.4-252-gad84058d3 - Seems to the most recent build that works on this device.

**Comment by unknownbrackets** [comment]
Does that mean #9701?  To confirm, it doesn't run with that commit anymore?

-[Unknown]

**Comment by Pinhcy** [comment]
I haven't been able to run any builds above 
v1.4-252-gad84058d3

**Comment by Pinhcy** [comment]
Messed around a bit more but v1.4-252-gad84058d3 is still the latest build that works but for some reason I am now able to install the latest builds that I could not previously but they are still crashing when I launch a game.

**Comment by hrydgard** [comment]
@Pinhcy , are the latest build still crashing? Seems clear this has something to do with gl feature/version detection, at least...

**Comment by Pinhcy** [comment]
Currently have this box disconnected from my TV, I will re hook it up in the next day or so and do some more troubleshooting.

**Comment by hrydgard** [comment]
@Pinhcy had some time to take a look yet?

**Comment by Pinhcy** [comment]
Yes you close this up as everything is fine now, the box got an update. Thanks

**Comment by hrydgard** [comment]
Then it's unclear whether the fix was in PPSSPP or the box. Oh well.
