### ISSUE TITLE
Copy to... iOS Feature

### ISSUE THREAD

**Issue by l-steve-l** [hrydgard/ppsspp#10638]
Is there any chance we can see a Copy To... function added to the build for iOS

This is more of an issue for non-jb users (I've done the iFile route before but I am not jb'ed on the X and rather not be) - maybe this could shed some light?

https://developer.apple.com/library/content/qa/qa1587/_index.html

Sorry if this is the wrong place to ask - hopefully it isn't.

**Comment by unknownbrackets** [comment]
Does this work now with #10921?

-[Unknown]

**Comment by l-steve-l** [comment]
I got a build of 1.6.2 installed and no that did not add the ability to Open in...  -- on my Phone (iPhone X) it gave me the ability to send my ppsspp data to icloud/dropbox/google drive.

I was looking at your code and it put in document viewer - but I think this might be more what is needed (see link below) - UIDocumentInteractionController

https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/DocumentInteraction_TopicsForIOS/Articles/PreviewingandOpeningItems.html#//apple_ref/doc/uid/TP40010410-SW1

**Comment by l-steve-l** [comment]
Hmm maybe you can explain the process then... Because when I do the same process as adding videos to VLC it fails to show PPSSPP https://youtu.be/wO8a_8uwLj4

**Comment by l-steve-l** [comment]
Thank you for sharing - that was a different way to add data to any app I've ever used.
