### ISSUE TITLE
Screen Flickering on OpenGL

### ISSUE THREAD

**Issue by torben656** [hrydgard/ppsspp#10635]
The screen flickers when I run a game.

Windows 7
Processor: AMD A4-6300 APU with Radeon(tm) HD Graphics 3.70 GHz
RAM: 2.00 GB
System Type: 32-bit

**Comment by FlatOutPS2** [comment]
See https://github.com/hrydgard/ppsspp/issues/10613 ;)

**Comment by hrydgard** [comment]
Yeah, closing as duplicate of #10613

**Comment by torben656** [comment]
Oh, I'm really sorry. But thanks! The latest version(not the dev ones) worked with OpenGL like a charm.
