### ISSUE TITLE
Star Ocean First Departure 

### ISSUE THREAD

**Issue by fivefeet8** [hrydgard/ppsspp#10634]
![screenshot_2018-02-20-19-41-03](https://user-images.githubusercontent.com/12039585/36462091-2836b02a-1676-11e8-8ed1-b43b3c7669e2.jpg)

What happens?
Characters hidden behind objects.  
What *should* happen?
They should be seen on top of them.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Using opengl on Snapdragon 820 ZTE Axon 7

**Comment by fivefeet8** [comment]
Vulkan render does the opposite.  Characters are rendered in front of objects the should be behind.

**Comment by unknownbrackets** [comment]
Are you using the latest git build?  What render resolution?

-[Unknown]

**Comment by fivefeet8** [comment]
Latest build at 4x resolution.

**Comment by unknownbrackets** [comment]
Interesting, happens at 1x too.

OpenGL: Seems like it's somehow only doing the bottom right quadrant of the screen.  Maybe stencil is still set, but I wonder why it behaves differently on desktop.

Vulkan: Maybe it's not even uploading stencil at all, for some reason.  Could even be a driver bug.

-[Unknown]

**Comment by fivefeet8** [comment]
Confirmed that the rendering errors don't happen on my Shield Tv.

**Comment by ppmeis** [comment]
Tested on latest Windows build. Even using 10x IR and texture scaling under Vulkan all seems to be fine:
![image](https://user-images.githubusercontent.com/4381277/36531911-9cfe0eb8-17bf-11e8-91cb-6ac602f40c32.png)

Under OpenGL, if I use any texture scaling (xBR, Hybrid, etc) there are a lot of issues:
![image](https://user-images.githubusercontent.com/4381277/36532162-494037fa-17c0-11e8-9c78-d4230e97299f.png)

Without scaling, OpenGL looks fine:
![image](https://user-images.githubusercontent.com/4381277/36532106-27aefd10-17c0-11e8-8ff3-b6541ab50127.png)

**Comment by fivefeet8** [comment]
Still the same no the latest builds.

**Comment by unknownbrackets** [comment]
Vulkan on Adreno is apparently misdetecting the shader as one that's safe to run early fragment tests on.  At least, `discard;` in the shader as no effect.  Changing the coords in the vertex shader does.

Writing statically to `gl_FragDepth` causes it to work properly, but the spec says that OpKill should disable early fragment tests (unless explicitly enabled.)

Maybe GLES has the same issue... checking.

-[Unknown]

**Comment by unknownbrackets** [comment]
So on GLES, this makes it work:

```c++
static const char stencil_vs[] = R"(#version 300 es
precision highp float;
out vec2 v_texcoord0;
void main() {
	int id = gl_VertexID;
	v_texcoord0.x = (id == 2) ? 2.0 : 0.0;
	v_texcoord0.y = (id == 1) ? 2.0 : 0.0;
	gl_Position = vec4(v_texcoord0 * vec2(2.0, 2.0) + vec2(-1.0, -1.0), 0.0, 1.0);
}
)";
```

That works fine with the fs, with appropriate `#version`.  The original vs for reference:

```glsl
#ifdef GL_ES
precision highp float;
#endif
#if __VERSION__ >= 130
#define attribute in
#define varying out
#endif

attribute vec4 a_position;
attribute vec2 a_texcoord0;
varying vec2 v_texcoord0;

void main() {
  v_texcoord0 = a_texcoord0;
  gl_Position = a_position;
}
```

I triple checked the verts being passed in, which seem fine.  We could in theory just use a different shader on GLES3, if this is a driver bug.  Ignoring the attributes doesn't seem like a problem, per se.  But I don't get how they're going wrong.

-[Unknown]

**Comment by unknownbrackets** [comment]
Arrrggg, no, it's missing the semantics.

-[Unknown]
