### ISSUE TITLE
PPSSPP crashes under experimental Android x86 Vulkan ISOs..

### ISSUE THREAD

**Issue by oscarbg** [hrydgard/ppsspp#10631]
What happens?
Download PPSSPP 1.54 with VUlkan support from APKMIRROR as Play store has been removed only gold payed version....
as seems it's only x86 and x64 native app which supports Vulkan..

using this exp builds:
nougat
https://drive.google.com/drive/folders/0B_OFHiIqgpSFMlk4bkhaMnAwbDA
oreo
https://drive.google.com/drive/folders/0B_OFHiIqgpSFTFpkQWc1eXV3ME0
with Vulkan support..

upon changing renderer to Vulkan..

![img_1947](https://user-images.githubusercontent.com/669305/36402028-cd65dec2-15db-11e8-88ca-a9cf7e0b5b2c.JPG)
(please zoom image if not seems down)
altough seems crashing other Vulkan apps not only yours

fails on both RADV and ANV drivers..

perhaps can help @maurossi (creator of ISOs) debugging the issue..
thanks..

**Comment by unknownbrackets** [comment]
Maybe the device doesn't support rendering at 4K?

Resolution: 3840 * 2076
Bits: 32 (RGBA)
Min: 3 images

-[Unknown]

**Comment by maurossi** [comment]
Now I remenber:

`vkCreateImage w/ native buffer failed: 3294895293`

The problem was related to drm_gralloc not supporting the necessary dma_buf (prime fd) for buffers allocation, so a drm_gralloc limitation, in the end.
Mauro

**Comment by oscarbg** [comment]
Yes can be closed now..
forgot to say..
