### ISSUE TITLE
ppsspp keep freezing until the last build on my android kitkat

### ISSUE THREAD

**Issue by sephiroth0396** [hrydgard/ppsspp#10633]
so.. I download ppsspp 1.5.4-545 and everything is fine but when I download the build above that version, ppsspp started to freeze right on the first screen when I click it. I don't even have to change to see the gamelist/menu. it's just freeze. not force close

**Comment by sephiroth0396** [comment]
I don't even have a change to see the gamelist/menu* typo. Sorry lol

**Comment by sephiroth0396** [comment]
Still experimenting the same issue lol

**Comment by sephiroth0396** [comment]
wait. I can open the latest build version but the screen is flickering since the start. I tried to load a game and it's only show me a blackscreen, I can heard the audio though.

**Comment by hrydgard** [comment]
If it's still problematic, why did you close?

**Comment by hrydgard** [comment]
Oh I see, you opened another one, alright.

**Comment by sephiroth0396** [comment]
no no.. it's fine now. I can open the game. no more hang on the menu but I get another problem here #10666 lol
