### ISSUE TITLE
Metal Gear Solid OPS +, Vulkan, Ran out of descriptor space in pool

### ISSUE THREAD

**Issue by weihuoya** [hrydgard/ppsspp#10641]
What happens?
![qq 20180224103925](https://user-images.githubusercontent.com/3827333/36624832-7f6569fa-194f-11e8-8065-e91003b47419.png)

crashed on android phone, too.

What *should* happen?

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

Windows 10, x64, 1050 Ti

**Comment by hrydgard** [comment]
Thanks, I guess I'll finally have to get around to fixing this properly... stay tuned.

**Comment by weihuoya** [comment]
still assert msg

**Comment by hrydgard** [comment]
@weihuoya  Did you build it yourself already? Because I just merged it, builds with the change aren't up yet on https://buildbot.orphis.net/ppsspp/ .

**Comment by hrydgard** [comment]
Although hm, looking closer at your error message there, it's really suspicious that it would happen when sz == 61... (very low number)

**Comment by weihuoya** [comment]
build by vs2017
![20180224182147](https://user-images.githubusercontent.com/3827333/36629357-d01a2990-198f-11e8-97fa-4a10abcbf022.png)

**Comment by hrydgard** [comment]
Hm, that looks alright..

Working on another possible fix.

**Comment by weihuoya** [comment]
![20180224182147](https://user-images.githubusercontent.com/3827333/36629518-b5f7090a-1991-11e8-86ad-8d32edf3bc31.png)
![20180224183617](https://user-images.githubusercontent.com/3827333/36629523-bd4f3ace-1991-11e8-8d9d-7b6fafd4a503.png)
fps down a lot

**Comment by hrydgard** [comment]
Looks like you built a debug build instead of release, then FPS will of course be down.

**Comment by weihuoya** [comment]
cancel hardware transform, issue disappear... debug build normally 20 fps

**Comment by hrydgard** [comment]
Weird, not seeing any slowdown effect like that myself. Should also keep in mind that using "Show debug statisics" causes some slowdown by itself.

**Comment by hrydgard** [comment]
Got an idea about this, it's possible that this helped: https://github.com/hrydgard/ppsspp/commit/5d77c63216f413285a4e0acda37246fbea10b280

Do you have hardware tesselation enabled?

**Comment by weihuoya** [comment]
hardware tesselation enabled, and 5d77c63 help a lot, but fps is unstable, slowly down and slowly up.
when hardware tesselation is disabled, fps smoothly

**Comment by hrydgard** [comment]
interesting. So it doesn't crash anymore? If so we can close this at least.

**Comment by weihuoya** [comment]
doesn't crash, thanks a lot
