### ISSUE TITLE
Vulkan: AMD devices not using threading

### ISSUE THREAD

**Issue by unknownbrackets** [hrydgard/ppsspp#10643]
In #10097 we saw issues with AMD drivers and had to disable by default.

On recent drivers (in that bug), enabling the thread worked, but gained no performance.  We've so far left it disabled.

There's still a possibility that it could gain performance (OpenGL gains performance with the thread, after all) in the future.  It may be a bug (perhaps we're handling fences in a way that doesn't work great on AMD), or it may be something AMD fixes in a driver update.

Opening this so we can track that.

-[Unknown]

**Comment by hrydgard** [comment]
We no longer have a way to disable threading, do we really need to keep this open?

**Comment by unknownbrackets** [comment]
This issue is specifically about these lines of code in Vulkan:

https://github.com/hrydgard/ppsspp/blob/f2244f789e6c64fede1cea006804875f1c7aec78/ext/native/thin3d/VulkanRenderManager.cpp#L138-L141

It's still using the threaded "method", but not threading the same way all other vendors do.

-[Unknown]

**Comment by hrydgard** [comment]
Oh right, I forgot that flag still existed.

**Comment by hrydgard** [comment]
We really should re-test this...

**Comment by RinMaru** [comment]
I have AMD anything i can do?

**Comment by hrydgard** [comment]
If you can compile, please remove the "useThread_ = false" line in ppsspp/ext/native/thin3d/VulkanRenderManager.cpp , compile, and see if things work as they should.

**Comment by RinMaru** [comment]
not sure how to do that no appvoyer?

**Comment by gameblabla** [comment]
Is this windows specific ?
Removed
```c
	// Temporary AMD hack for issue #10097
	if (vulkan_->GetPhysicalDeviceProperties().properties.vendorID == VULKAN_VENDOR_AMD) {
		useThread_ = false;
	}
```
from https://github.com/hrydgard/ppsspp/blob/master/Common/GPU/Vulkan/VulkanRenderManager.cpp#L210

... and it still worked fine for me.
I tested it on Void linux, Mesa 20.2, Ryzen 7 4750G APU with AMDGPU/RADV Vulkan drivers.
Whenever or not the bug is windows specific, the condition and useThread_ = false still get triggered on Linux despite the fact it works fine.

**Comment by LunaMoo** [comment]
Define "works fine".
Vulkan's multithreading was disabled on AMD gpu's because it had no benefit whatsoever and could even be a minor slowdown, not because it caused problems.

**Comment by hrydgard** [comment]
No, it was actually disabled because early Windows Vulkan drivers indeed had problems. Since then we've just left it as it is.

**Comment by LunaMoo** [comment]
I recall it being disabled after my own report it doesn't benefit AMD gpu back when I had one, it always worked, it just never had any benefit of "working". But not sitting in anyone elses mind to know other reasons.

**Comment by gameblabla** [comment]
Removing the workaround actually improves the speed by quite a significant amount, at least on Linux with latest Mesa drivers.

![nothreads](https://user-images.githubusercontent.com/8717966/101163307-586d8c00-362b-11eb-8d44-b8e985a1605e.png)
^ With workaround in place

![threads](https://user-images.githubusercontent.com/8717966/101163317-5b687c80-362b-11eb-9412-da73cf67a1ed.png)
^ With workaround removed and gone.

What i did was to boot up Battlegrounds 3 at the titlescreen and just uncap the framerate.

Settings
![2020-12-04-132351_1920x1080_scrot](https://user-images.githubusercontent.com/8717966/101163604-bf8b4080-362b-11eb-9fe8-17f7f2c9af82.png)
![2020-12-04-132355_1920x1080_scrot](https://user-images.githubusercontent.com/8717966/101163624-c4e88b00-362b-11eb-8fd8-6f5ce60413b5.png)
![2020-12-04-132356_1920x1080_scrot](https://user-images.githubusercontent.com/8717966/101163630-c74ae500-362b-11eb-90a7-c04c2ec08b73.png)

It's a poor benchmark but it doesn't seem to be any slower.

**Comment by hrydgard** [comment]
@LunaMoo Well just look at the first post of this thread, and https://github.com/hrydgard/ppsspp/issues/10097.

**Comment by hrydgard** [comment]
Let's experimentally turn it back on after the 1.11 release. In the meantime, most machines with an AMD gpu are gonna be "fast enough" anyway, so...

**Comment by LunaMoo** [comment]
@hrydgard ok, but following that issue it was more of a problem with windows update, either way even back then it ran on amd GPU, just without benefits.

**Comment by unknownbrackets** [comment]
If there are no performance benefits on some Windows devices, but no longer any driver bugs - I'd still say we should enable this everywhere.  There's definitely benefit to all GPUs running the same way.  I'm sure we could have special annoying double free issues in this alternate codepath, and there's no reason to maintain it if it has no upside.

-[Unknown]
