### ISSUE TITLE
Feature: Enable Vulkan on macOS/iOS using MoltenVK and the LunarG Apple SDK for Vulkan

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#10654]
Might be interesting to see what kind of performance we could get with this stuff (Vulkan on top of Metal).

https://www.khronos.org/news/press/vulkan-applications-enabled-on-apple-platforms
https://github.com/KhronosGroup/MoltenVK
 https://www.anandtech.com/show/12465/khronos-group-extends-vulkan-portability-with-opensource

Interesting is the "Portable Subset", which I believe will not affect us very much:

https://www.khronos.org/vulkan/portability-initiative

At most we might have to emulate triangle fans and maybe swap some texture color channels.

**Comment by konistehrad** [comment]
Assuming the performance impact is minimal: do you see the project moving to the Portable Subset for all Vulcan-supporting platforms, or only for platforms that require a MoltenVK translation layer?

**Comment by hrydgard** [comment]
We only exceed the Portable Subset in a single place currently, we use texture channel swizzles to get the texture formats to match the PSP completely. We'll probably just add a slower path for MoltenVK that swizzles texture colors in software before upload, for simplicity, if we ever get around to trying this :)

**Comment by iOS4all** [comment]
There's a new update about using vulkan rendering for apple devices Mac/iOS

Just see here on retroarch commit:
https://github.com/libretro/RetroArch/commit/0a4ff225be284744168f2e3f97b48f2df067f25b
https://github.com/libretro/RetroArch/commit/789933b333f4a3988edc20b92fac17f31feb8492

Maybe you'll find it very interesting.

**Comment by hrydgard** [comment]
(Just a note, the texture swizzle issue above is no longer a concern, MoltenVK handles it transparently, and it's natively supported in newer Metal versions).

**Comment by hrydgard** [comment]
I retract that - it still seems to be an issue at least on my old macbook.

**Comment by Halo-Michael** [comment]
![@I(L@5K LU18RP6YQ98HCG](https://user-images.githubusercontent.com/45062120/101402006-1df73e00-390e-11eb-91b1-6eea2b966af2.png)
I am not sure if vulkan is actually used. When I switch between OpenGL and Vulkan when running a game, it seems that the frame rate has not changed significantly; in addition, I have not obtained information in the log that the engine used by the game is OpenGL or Vulkan. Maybe you need to add the currently used engine to the log?

**Comment by Halo-Michael** [comment]
https://github.com/hrydgard/ppsspp/pull/13751
Experimental code submission, obviously need to continue research more.

**Comment by unity** [comment]
Dear Friends. By the following chain of dependencies, it seems we would benefit greatly from this feature being finalized :

- OpenGL is being ramped down by Apple
- As a consequence, RetroArch has released a branch supporting Metal
- As a consequence, Unfortunately PPSSPP w/ libretro isn’t supported

In my specific use case the reason I’m interested is that I’m building a Steam remote play box on a MacMini with RetroArch for retro goodness. But only RetroArch’s Metal branch behaves properly, leaving me no choice in the flavor. The other displays a quarter-screw on Steam remote play.

**Comment by 2V3EvG4LMJFdRe** [comment]
Same case as the guy above me. Citra has just announced Vulkan support, which has been taken up by the guys at RA to implement to their core. Just chiming in to show my support for the request.
