### ISSUE TITLE
“d3d11_1.h”: No such file or directory 

### ISSUE THREAD

**Issue by sidney9111** [hrydgard/ppsspp#10657]
while compile, I got this message.
I know it's a common problem
but could anyone tell how to make it compile work through on win7?
d3d seems to be installed, did I ignore some reference?

**Comment by hrydgard** [comment]
No this should not be a common problem. Which version of Visual Studio are you using?

Also, did you clone with submodules properly?

     git clone --recursive git@github.com:hrydgard/ppsspp.git

Alternatively, afterwards:

    git submodule update --init --recursive

If these help, please close this issue.

**Comment by sidney9111** [comment]
Thanks hrydgard,
I finally found out this solution by offical instruction in here, github
We have to run the command "submodule update" after clone the main branch to make the whole project right
d3d seems to reference correctlly now without message "No such file or directory " as before
And I had launch the project by my android phone, but crash
I'm checking with another officical document (seems also was writtern by you)
