### ISSUE TITLE
Burnout dominator. some things not rendering correctly.

### ISSUE THREAD

**Issue by nathanhitch** [hrydgard/ppsspp#10655]
What happens?
Most of the cars and the tracks render transparent

# Tests
### DX 11
car
![ules00703_00000](https://user-images.githubusercontent.com/19424968/36720446-08aedfb6-1bf8-11e8-8826-2686b905b116.jpg)
track
![ules00703_00001](https://user-images.githubusercontent.com/19424968/36720448-0aa1231a-1bf8-11e8-8d3f-755211f12311.jpg)
### DX 9
car
![ules00703_00002](https://user-images.githubusercontent.com/19424968/36720618-7d516c12-1bf8-11e8-869a-a32f36da9706.jpg)
track
![ules00703_00004](https://user-images.githubusercontent.com/19424968/36720625-8212a5f4-1bf8-11e8-9b7f-45a91fe5d5ed.jpg)
### Open GL
Renders correctly
but not screenshoting correctly
### DX 11
car
![ules00703_00004](https://user-images.githubusercontent.com/19424968/36720107-ef251890-1bf6-11e8-85e9-f595bf8edc2d.jpg)
hubusercontent.com/19424968/36719949-72830c16-1bf6-11e8-8e0a-25b2dde19026.jpg)
track
![ules00703_00003](https://user-images.githubusercontent.com/19424968/36719963-7a4b9eae-1bf6-11e8-9986-0fe075715113.jpg)
### DX 9
car
![ules00703_00004](https://user-images.githubusercontent.com/19424968/36720127-01cda6d8-1bf7-11e8-9a45-bd1d03bfde8f.jpg)
track
![ules00703_00005](https://user-images.githubusercontent.com/19424968/36720136-06f4aecc-1bf7-11e8-982d-cb1dc5826240.jpg)
### Open GL
Renders correctly
![ules00703_00000](https://user-images.githubusercontent.com/19424968/36720291-81ea4a9c-1bf7-11e8-804a-f577836365b5.jpg)

What *should* happen?

![ules00703_00000](https://user-images.githubusercontent.com/19424968/36720291-81ea4a9c-1bf7-11e8-804a-f577836365b5.jpg)

![ules00703_00008](https://user-images.githubusercontent.com/19424968/36721113-ea8e939e-1bf9-11e8-90df-bece1dabe9f7.jpg)

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
GPU:Intel HD 5500
CPU:Intel Core i5-5200U
OS:Windows 10 x86-64
RAM:4 GB

if you need anything else just ask

**Comment by hrydgard** [comment]
This seems to affect the D3D backends only. Very strange. If you want to help, try some more old versions in order to find the last version where it worked - pretty sure it has worked on all backends in the past.

**Comment by nathanhitch** [comment]
the last automatic build that works is 83-gcaf9eca2d the push that i think is the cause could be 84-g522447dca with the commit message "GPU: Default to Vulkan if possible. Fall back to Direct3D 11 on Windows 8+ to target Windows 10 most especially. Default vertex cache off everyone except OpenGL where it helps the most."

**Comment by hrydgard** [comment]
That would be #10390. Quite odd..

**Comment by nathanhitch** [comment]
hey just here to say that this also happens with vulkan on linux
