### ISSUE TITLE
Untold legends: the warrior's code close ppsspp android

### ISSUE THREAD

**Issue by oldboy1988** [hrydgard/ppsspp#10656]
What happens?
Close ppsspp after go on 3 stage on game Untold legends: the warrior's code, fps 0 and close app:( on stage 1-2 all good and all work.. but on 3 stage not load. this issue on all render vulcan and opengl
All other work perfect:)
Download this game from tree sorces and on all this crash:(  Try latest dev version and stable version PPSSPP 
Video on close app https://youtu.be/n-De3TeAaCU

What *should* happen?
Next stage loading

What hardware and operating system are you running PPSSPP on? 
Xiaomi Redmi Note 3 Pro 3/32 MIUI 9 Android 7. Snapdragon 650 Adreno 510

**Comment by oldboy1988** [comment]
Report:
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/hydrogen/hydrogen:6.0.1/MMB29M/V8.2.3.0.MBCCNDL:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 9507, tid: 9531, name: AndroidRender  >>> org.ppsspp.ppsspp <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x23deae0b03
    x0   00000000deadbeef  x1   000000000000000c  x2   0000000008ac0000  x3   0000000008ac0000
    x4   0000000008480000  x5   0000000000000000  x6   0000000000000001  x7   7f8000017f800001
    x8   0000000000000000  x9   8cbc31a9efe99c3d  x10  0000007f781c3c58  x11  000000000004423e
    x12  0000000005f5e100  x13  0000051fd76848c2  x14  7f8000017f800001  x15  0000000100000000
    x16  00000000deae0b03  x17  0000000000004c14  x18  0000000000000020  x19  0000002309fbf950
    x20  0000000000000000  x21  00000000deadbeef  x22  0000000000000000  x23  0000000008806150
    x24  0000000000044236  x25  0000000060000000  x26  0000007f6f600000  x27  0000007f781d2e40
    x28  0000002300000000  x29  0000007f741bea90  x30  0000007f6f60191c
    sp   0000007f741bea90  pc   0000007f6f643778  pstate 0000000060000000

backtrace:
    #00 pc 0000000000043778  <anonymous:0000007f6f600000>
    #01 pc 0000000000001918  <anonymous:0000007f6f600000>

**Comment by oldboy1988** [comment]
yes. crash and agter set fast memory off and if set IR intepreter...

**Comment by hrydgard** [comment]
Fault address 0x23deae0b03 is interesting, it might have the 0xdeadbeef from x0 included in it...

**Comment by oldboy1988** [comment]
Build fingerprint: 'Xiaomi/hydrogen/hydrogen:6.0.1/MMB29M/V8.2.3.0.MBCCNDL:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 23651, tid: 23673, name: AndroidRender  >>> org.ppsspp.ppsspp <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x23deb2beef
    x0   00000000deadbeef  x1   00000000deb2beef  x2   0000007f759f6d1c  x3   0000000000000003
    x4   0000000000000000  x5   0000000000000000  x6   ffffffffffffffff  x7   0000000200000002
    x8   0000000000000000  x9   0000007f759f6dc0  x10  0000000000000040  x11  ffffffffffffffc0
    x12  0000007f759f6dc0  x13  0000000000000040  x14  0000000000000040  x15  0000000000000040
    x16  00000000deb2beef  x17  00000000000eb248  x18  0000000000200017  x19  0000002309fbf910
    x20  0000000000000000  x21  00000000deb2beef  x22  0000000008a3cb74  x23  000000000899f360
    x24  0000000000043c0a  x25  0000000020000000  x26  0000007f75800000  x27  0000007f7dc85e90
    x28  0000002300000000  x29  0000007f7a777440  x30  0000007f758001bc
    sp   0000007f7a777440  pc   0000007f7580018c  pstate 0000000020000000

backtrace:
    #00 pc 000000000000018c  <anonymous:0000007f75800000>
-----------------
if this help this crash today

**Comment by oldboy1988** [comment]
yes i try on windows tonight

**Comment by hrydgard** [comment]
Still crashing?

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
