### ISSUE TITLE
screen flickering and blackscreen.

### ISSUE THREAD

**Issue by sephiroth0396** [hrydgard/ppsspp#10666]
https://youtu.be/d1NRWuSOjJA here's the footage. I get blackscreen when I load a game tho but the audio is fine.

**Comment by hrydgard** [comment]
Wow, that is not good.

Please report what hardware you are using, and Android version. Clearly you're using OpenGL, our OpenGL code recently got a big rewrite so something obviously went wrong - but it works fine on all my devices...

**Comment by sephiroth0396** [comment]
alright. let me check it. btw it's a old phone lol

Chipset: MediaTek MT6572
CPU: Dual Core 1.3 GHz, Cortex-A7
GPU: Mali-400 MP1 @ 500 MHz
android version: 4.4.2 kitkat

**Comment by sephiroth0396** [comment]
oh. it's using opengl es

**Comment by hrydgard** [comment]
I've reproduced this problem on my Galaxy S3 which also has Mali. Extremely odd, will investigate soon.

**Comment by sephiroth0396** [comment]
I see. I've tried to get into the game (final fantasy type-0) used my savestate and the characters become yellow objects-like-circle but the background don't shown anything. It's just blank and black.

**Comment by hrydgard** [comment]
This started in https://github.com/hrydgard/ppsspp/pull/10604 and even though the functionality was whitelisted to only be used on nVidia, Mali and some other ES 2 devices are still completely broken. Can't figure it out :(    @unknownbrackets you don't happen to have any idea?

**Comment by sephiroth0396** [comment]
Aw. I see. 1.5.4-45 is work perfectly without any issues though. The problem started since 1.5.4-46 untill now lol

**Comment by hrydgard** [comment]
Oh if it broke that early for you, then it's yet another bug. Though https://github.com/hrydgard/ppsspp/commit/b10b24feeaf29764e3d8c5ce551b6b23da11a2d4 (which is 1.5.4-46) does not seem like it would be the cause of issue like this..

**Comment by sephiroth0396** [comment]
Let me check it. I'm not sure it's 1.5.4-45 or 1.5.4-645 lol

**Comment by sephiroth0396** [comment]
Testing 1.5.4-545 and it's working perfectly on my phone. Except that final fantasy type-0's cutscenes won't play but skipable.

**Comment by hrydgard** [comment]
Ah okay, got it. That makes more sense.

**Comment by unknownbrackets** [comment]
Hmm, naybe here?

https://github.com/hrydgard/ppsspp/pull/10604/files#diff-2ac99ae10d3cccae9c154c12ff263384R683

Maybe this is avoiding some flush?  But really, they should be locked right?  Other ideas:

 * It broke glCopyImageSubDataOES due to GL func pointer limits?
 * There's a timing problem with the buffer Flush() in Run() (even though it should only happen on a locked thread data)?

Hmm...

-[Unknown]

**Comment by sephiroth0396** [comment]
hmm.. my friends tested it with their phone with the same cpu and gpu. sometimes one of them just hang right when they open it and got blackscreen but then he got screen flickering. he said he just deleted all the system's files to avoid the blackscreen. strange. however the 1.5.4-545 version is working good even we are using frameskip when online lol

**Comment by hrydgard** [comment]
@unknownbrackets It cannot have been glCopyImage related because even the PPSSPP UI is affected.

**Comment by hrydgard** [comment]
@sephiroth0396 with 38bf10b, this should be completely fixed. So be on the lookout for that build or later :)

**Comment by sephiroth0396** [comment]
hmm.. this is strange.. ''failed to save setting.'' I experience the same issue like my friend. I have to delete the system's .ini files to avoid blackscreen and right now, the build doesn't create the system's folder.. need to open the original version which is 1.5.4 to get the system's files back-- and delete it again-- and when I successfully attempt to get into the menu/gamelist.. the screen still flickering.. omg..

**Comment by hrydgard** [comment]
Well the fix is in version 1.5.4-631 which is not out on the buildbot yet. Use that.

**Comment by sephiroth0396** [comment]
trying for the 3th times. I'm exploring my folder without close application and right, the ppsspp.ini isn't there..

**Comment by sephiroth0396** [comment]
alright. I will try that one too

**Comment by hrydgard** [comment]
Anyway your ini file problems have nothing to do with the black screen/flicker which is the topic of this issue. If it's still present in 631, please file a new issue detailing the problems you are having.

**Comment by sephiroth0396** [comment]
I see. alright, sir. will report it if I figure out a new issue lol
