### ISSUE TITLE
Ppsspp huge battery drain

### ISSUE THREAD

**Issue by HypeChangerIvan** [hrydgard/ppsspp#10669]
Hi! Here I am again, Ive noticed that when I play ppsspp for about 30 minutes,  my battery drains about 10-20%, Ive noticed it since 1.5 .4 version

Specs:
Samsung Galaxy S5
Android 6.0.1
Adreno 330
Snapdragon 801
2800 mAh battery

**Comment by leopard20** [comment]
30 hours and 10-20 % drain?! I would rate it as awesome battery life/perfect battery optimization on the ppsspp side! LoL 😉

**Comment by HypeChangerIvan** [comment]
Wait, its typo hahahah i mean 30 minutes hahaha

**Comment by Leafino** [comment]
I don't think this is something @hrydgard could fix. Try flashing Android 8.0, if there's a build of it somewhere. That'll probably help. Your battery is probably just getting old. Emulation is no easy task for the components.

**Comment by Carter07** [comment]
Battery drain is more because now ppsspp is faster on OpenGl, 2 cores use more battery.

**Comment by hrydgard** [comment]
Increasing frameskipping is one way to lower power consumption. I don't think there's much we can do here other than keep optimizing the emulator to run faster.

**Comment by fahadfoyjur** [comment]
Carter bro is ppsspp use 2 core ?
