### ISSUE TITLE
The Simpsons Game - Adreno 540 Visual Issues

### ISSUE THREAD

**Issue by Leafino** [hrydgard/ppsspp#10667]
What happens?
The game's textures sometimes either appear white (OpenGL) or missing/black (Vulkan).

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Android - OnePlus 5T - OxygenOS Skin
No configuration appears to resolve the issue as others have mentioned possible.

I have noticed other reports I just want to make sure this has not been forgotten.

Thanks for your hard work! <3

 - James.

**Comment by Leafino** [comment]
Here is the result with default settings:
![image](https://user-images.githubusercontent.com/7761055/36872049-ee186dd4-1d9b-11e8-88de-a17dcaa490b3.png)

**Comment by Leafino** [comment]
...and this is Vulkan. 

![image](https://user-images.githubusercontent.com/7761055/36872733-287a09e0-1d9e-11e8-82ba-5eca9540e787.png)

**Comment by Blacob777** [comment]
I have this problem too, snap 821

**Comment by hrydgard** [comment]
Duplicate report of #9830 , closing.
