### ISSUE TITLE
Can't unthrottle GoW: GoS during splash screens + lag when I unthrottle

### ISSUE THREAD

**Issue by leopard20** [hrydgard/ppsspp#10668]
What happens?
I only tested GoW: GoS  but I'm guessing the issue may not be limited to this game alone.
I can't unthrottle the game during the splashcreens anymore.
Also I noticed something else about GoW when I unthrottle. Not only does it not speed up the loading, it actually slows it down, and you can see lots of lag between transitions (even without holding down the unthrottle button)

What *should* happen?
I used to be able to unthrottle the game just fine in v1.5.4.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Android 7.0
Snapdragon 821
PPSSPP v1.5.4-623

**Comment by leopard20** [comment]
@hrydgard
I noticed something else about GoW when I unthrottle. Not only does it not speed up the loading, it actually slows it down, and you can see lots of lag between transitions (even without holding down the unthrottle button)

**Comment by leopard20** [comment]
BTW, I tested more games and apparently this IS limited to GoW! Other games worked OK. So I'll change the title.

**Comment by unknownbrackets** [comment]
I think this may somehow be a side effect of the heuristic change I made for the 60 FPS limit setting.  But have to be careful about not breaking FF4 or Tales of Phantasia.

Not sure what the interaction with fast forward is, seems like something is using the wrong timer or events, then...

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, that seems likely. The fast-forward issue is indeed weird though. It does fast-forward on Windows but it now doesn't on platforms where we frameskip-fastforward.

**Comment by unknownbrackets** [comment]
That's odd.  I actually saw this on Windows some time ago but forgot to come back to it.  It indeed doesn't happen anymore, I wonder what changed...

-[Unknown]

**Comment by unknownbrackets** [comment]
Strange - I bisected backwards and it doesn't happen on desktop for me even in older versions now... odd.

-[Unknown]
