### ISSUE TITLE
Building on Odroid XU4 fails

### ISSUE THREAD

**Issue by Tillman-Z** [hrydgard/ppsspp#10664]
Building current master on Odroid XU4 fails.
See attached log.

Any idea how to fix this?

https://pastebin.com/2mEuHyhA

**Comment by hrydgard** [comment]
Looks like both our ES headers and desktop gl headers are getting included, strange...

**Comment by Tillman-Z** [comment]
Should I try a build with the desktop gl headers removed? Where would I need to change the Makefile?

And thanks for being so super fast in your response btw!!

**Comment by hrydgard** [comment]
No wait, that's not it. It's your gl2ext headers that defining stuff that we already also define in gl3stub.h, we should avoid getting that included. Just to test, open ext/native/gfx/gl_common.h and remove the line that includes gl3stub.h and see if that helps.

**Comment by Tillman-Z** [comment]
Building again - will know more in about 8-10mins :)

**Comment by Tillman-Z** [comment]
And this is what we get now: 

https://pastebin.com/dficFx4B

**Comment by hrydgard** [comment]
That was just a silly mistake from my side, I've fixed it now.

**Comment by Tillman-Z** [comment]
Ok - pulled again and rebuilding now. :)

**Comment by Tillman-Z** [comment]
After a new pull this what I am getting now:
https://pastebin.com/tqH6Njz4
Still looks like Vulkan is in.

**Comment by Tillman-Z** [comment]
The retropie build script is using a cmake file called "generic.armv7.cmake" on the Odroid XU4.
I have modified it to set USING_GLES2 to off.
This is how it looks like:
set(ARMV7 ON)

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -march=armv7-a -mfpu=neon -mcpu=cortex-a9")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -march=armv7-a -mfpu=neon -mcpu=cortex-a9")
set(CMAKE_ASM_FLAGS "${CMAKE_ASM_FLAGS} -march=armv7-a -mfpu=neon -mcpu=cortex-a9")
set(USING_GLES2 OFF)

However still no joy:

https://pastebin.com/s8Wk0sES

**Comment by Tillman-Z** [comment]
If you have any further ideas I am happy to try them. :)

**Comment by mrvanes** [comment]
Looking at the same problem, but building in an arm chroot env.

**Comment by mrvanes** [comment]
I've managed to compile ppsspp in an odroid flavoured arm chroot by patching /usr/include/GLES2/gl2ext.h
I changed the #ifdefs to fail by adding a nonsense _FAIL to the check:
```
279:#ifdef GL_GLEXT_PROTOTYPES_FAIL
1088:#ifdef GL_GLEXT_PROTOTYPES_FAIL
```
Then I ran into this problem:
https://forum.odroid.com/viewtopic.php?f=91&t=26822

Which I solved by supplying __ARM_PCS_VFP to the asm, c and cxx flags like suggested in the forum.

**Comment by unknownbrackets** [comment]
Is this still a problem?

If `__ARM_PCS_VFP` needs to manually be defined, that seems concerning.  We use that currently to detect hard float:

https://github.com/hrydgard/ppsspp/blob/aa927e0681ed76fec3b540218981a2c407a78e47/Core/MIPS/ARM/ArmCompVFPU.cpp#L2223-L2230

-[Unknown]

**Comment by mrvanes** [comment]
It's not a problem in the sense that I stopped trying to cross-compile ppsspp. But if you think cross-compiling ppsspp is worthwile (e.g. speed, Travis test building) this will come up again.

**Comment by unknownbrackets** [comment]
I think we've fixed the ARM problem.  Since this is an older issue and hasn't gotten feedback recently, I'm going to close it in favor of #13840 which has more detail by now on the GL header issue.

-[Unknown]
