### ISSUE TITLE
PPSSPP android latest dev build can't resume from background standby?

### ISSUE THREAD

**Issue by lim2222** [hrydgard/ppsspp#10675]
What happens?

Just discovered this bug after answer a phone call,ppsspp can't resume from background standby.
I don't know whether this is a limitation of free version? just kidding:)
PPSSPP gold works fine.
Sorry for my bad english.
What *should* happen?
This video would tell

https://youtu.be/vR-YZDBemCs

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

1:Oneplus 5 A5000 OxygenOS 4.5.15 Android 7.1.1
2:Zenfon selfie Asus_Z00UD Android 6.0.1

**Comment by lim2222** [comment]
After several test, comfirm that bug is starting after v1.5.4-582-gb3957ff35

**Comment by hrydgard** [comment]
Thanks, will look into this, seems connected to some other bugs.

**Comment by lim2222** [comment]
[ABD X.txt](https://github.com/hrydgard/ppsspp/files/1777306/ABD.X.txt)
THX BRO,adb logs provide incase you need it.

**Comment by blackman91** [comment]
Can confirm this happens on latest build too on both gl and vulkan, pressing recent apps android button or home and going back crashes ppsspp. Tested on motog5 plus

**Comment by blackman91** [comment]
Latest dev no longer crashes on gl but it still crashes on vulkan.

**Comment by hrydgard** [comment]
Well, at least there's progress :) I'll try to fix up the rest soon.

**Comment by weihuoya** [comment]
this issue and #10696 is maybe same issue

**Comment by lim2222** [comment]
latest build v1.5.4-657-g3c16f8437 has fixed both gl and vulkan unable to resume bugs,good job bro.THX.
