### ISSUE TITLE
[Qt] Text flicking when testing gamepad controller

### ISSUE THREAD

**Issue by CarterLi** [hrydgard/ppsspp#10678]
What happens?

Text flickering. Doesn't happen in SDL version.

Video attached.  
[ppsspp.mp4.zip](https://github.com/hrydgard/ppsspp/files/1777446/ppsspp.mp4.zip)

What *should* happen?

Don't flicker.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

```
MacBook Pro (Retina, 15-inch, Mid 2015)
AMD Radeon R9 M370X 2 GB
Intel Iris Pro 1536 MB

macOS 10.13.3 (17D102)
```

**Comment by unknownbrackets** [comment]
This should be fixed now with #11808.

-[Unknown]
