### ISSUE TITLE
Loading screen quirk (would not dare to call it a regression)

### ISSUE THREAD

**Issue by Anonymphous** [hrydgard/ppsspp#10673]
What happens?

On press of "BACK" button, pause menu opens after "loading game" screen.

What *should* (probably) happen?

Instant opening of pause menu.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

Xperia Z5, Android 7.1, OpenGL.

Before 1.5(...?(I build my PPSSPP from sources, can't remember the change)) I really liked the responsiveness when the pause menu with load states opened instantly on "Back" press after clicking on a game.
Now it waits for "loading game" screen completion, which can be rather long sometimes.

I wonder, if it is possible to return to the previous behavior, and if it's necessary, put this "load screen" after "load state".
If not, I understand.

**Comment by unknownbrackets** [comment]
It always waited, but there seem to be cases where loading is taking longer recently.

Just to confirm: if you select the PPSSPP app under Storage, and hit CLEAR CACHE, does it change anything?

https://www.cnet.com/how-to/how-to-clear-app-cache-and-app-data-in-android-6-0-marshmallow/

-[Unknown]

**Comment by hrydgard** [comment]
@unknownbrackets  Maybe we could show a progress string during load, like "Loading modules...", "Compiling shaders..." etc. That would make it clear which part is being slow.

**Comment by Anonymphous** [comment]
Sorry for being absent on the issue, was quite a bit sick last week.

I'll try to show what I mean in the next few days in a gif (if I'll manage to replicate it), will have to dig through revisions to find that sweet behavior I'm talking about.

**Comment by Anonymphous** [comment]
@unknownbrackets @hrydgard 
Yay, was lucky that the commit introducing the loading screen was a day _after_ 1.5.3 milestone release.

Well,  here is what I was talking about:
As it was:
[Imgur](https://i.imgur.com/f6mIO64.gifv)

As it is now:
[Imgur](https://i.imgur.com/vBvDT0D.gifv)

**Comment by hrydgard** [comment]
Thanks. Still pretty mysterious what in that commit slowed it down...

**Comment by unknownbrackets** [comment]
It looks like `MIPSAnalyst::ScanForFunctions()` takes a good chunk of the loading time in some games.  For example, even on desktop, that takes about 1s on desktop in 3rd Birthday.

But we need it for replacements.  There's probably something to optimize there, though.

I know I recently changed it to scan more accurately based on the relocation tables, maybe that slowed it down a bit.

-[Unknown]

**Comment by unknownbrackets** [comment]
Okay, might've found the regression.  At least it was the case for 3rd Birthday.

-[Unknown]

**Comment by hrydgard** [comment]
This should be much faster now.

**Comment by hrydgard** [comment]
@Anonymphous can you confirm that this is fixed for you now?

**Comment by Anonymphous** [comment]
@hrydgard Yes, perfect, just like before!

Probably the issue can be closed now.
