### ISSUE TITLE
NFS Most Wanted 5-1-0 Graphic Issue

### ISSUE THREAD

**Issue by HypeChangerIvan** [hrydgard/ppsspp#10683]
Hi! This issue is just the same in burnout legends but in this case, the tires of the cars in nfs are black, even I changed the color of it, but when Im on a race, the car wheels are shown.

**Comment by ppmeis** [comment]
@HypeChangerIvan please give us more information, such as screenshots, PPSSPP version used, platform, specs etc.

**Comment by HypeChangerIvan** [comment]
Android
Samsung S5
Snapdragon 801
Adreno 330
Android 6.0.1
2GB RAM

**Comment by Gamemulatorer** [comment]
@HypeChangerIvan no feedback/outdated

**Comment by Gamemulatorer** [comment]
This might be solve by https://github.com/hrydgard/ppsspp/pull/15235

**Comment by Gamemulatorer** [comment]
This issue can be closed now.

**Comment by unknownbrackets** [comment]
Yeah, I think this was fixed when we corrected the culling to use pre-viewport Z.

-[Unknown]
