### ISSUE TITLE
Regression: Parappa the Rapper hanging after opening FMV.

### ISSUE THREAD

**Issue by vaguerant** [hrydgard/ppsspp#10684]
**What happens?**
`PaRappa the Rapper (Japan) (En,Ja)` (No-Intro naming, other regions not tested) hangs if user either watches or skips the opening FMV, then enters the Menu from the title screen and exits back out, which triggers the opening FMV to play again. After the FMV has ended for the second time (either via player interruption or allowing it to play through), the game enters a transition screen and hangs there.

Potentially related to issues #3338 or (more likely) #7713. Similar issues have been noted in the [Parappa forum thread](http://forums.ppsspp.org/showthread.php?tid=1800).

**What *should* happen?**
I'm guessing the title screen should show up again.

**What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.**
PPSSPP-SDL 1.5.4 under Raspbian Jessie on a Raspberry Pi Model 3.

Also checked using 64-bit PPSSPP on Windows 10. CPU is an Intel Xeon E5-1560 @ 6x3.2 GHz, GPU is an NVidia Quadro 2000 (a workplace GPU meant for CAD operations and such), which from some Googling is roughly equivalent to a GeForce GTS450.

**Log (from Pi)**
[ppsspp.log](https://github.com/hrydgard/ppsspp/files/1778278/ppsspp.log)

**Comment by unknownbrackets** [comment]
Have you verified this is a clean rip of your original disc?  Just want to be sure this isn't an issue with some hacked version of the game.

-[Unknown]

**Comment by vaguerant** [comment]
I can confirm that my image matches No-Intro's and Redump's databases of clean rips, with md5sum `db9d2942f81154a2028561580ad5af72`.

**Comment by benderscruffy** [comment]
v1.7.1-204-gd08a2eed6
i found no problem using windows 7
this can be closed

**Comment by hrydgard** [comment]
@vaguerant  can you also confirm if it's fixed for you in the latest builds?

**Comment by Panderner** [comment]
No problem after opening FMV. yeah it fixed for recent build

**Comment by unknownbrackets** [comment]
Going to close this for now, assuming it was fixed sometime in 2018.  It may have even been ARM-specific.

Please reply if this is not the case.  But if you're a new person seeing issues in the same game, it's likely a new issue and unrelated - even if it has the same hang.  In that case, please open a new issue.

-[Unknown]
