### ISSUE TITLE
Frequent crashing since Ppsspp 1.5.4-625

### ISSUE THREAD

**Issue by HypeChangerIvan** [hrydgard/ppsspp#10689]
Ive noticed during this version, when I launch this app, it takes me back to my home screen, and says "Unfortunately, PPSSPP has stopped". But sometimes, the crash didnt happen

**Comment by unknownbrackets** [comment]
This doesn't happen with v1.5.4-630-g1ea474724?

-[Unknown]

**Comment by HypeChangerIvan** [comment]
Yep @unknownbrackets

**Comment by unknownbrackets** [comment]
Strange.  I can't see anything wrong with 38bf10baa.  And it's still crashing in newer builds too?

Maybe #10688 will help somehow, since it fixes the other part of the alignment issue.

-[Unknown]

**Comment by Saramagrean** [comment]
Happens on my device too (Huawei P9+: Kirin 955, Mali880, Support Vulkan)

Crash when open app after installed (first time only) & crash after given permission, but i found this problem since v1.5.4-625-ga0612f4c8. (v1.5.4-623-gb74634aa3 isn't crash)

**Comment by unknownbrackets** [comment]
Hmm, that sounds like #10672?

-[Unknown]

**Comment by Saramagrean** [comment]
Yes, sir.

**Comment by hrydgard** [comment]
Suspecting some kind of race condition between the java and c++ init code, will look into this soon.

**Comment by Saramagrean** [comment]
I try latest build v1.5.4-657-g3c16f8437, Isn't crash after given permission. 👍

**Comment by unknownbrackets** [comment]
Closing in that case - but please comment if it's still happening and we'll reopen.

Note: not every possible crash is definitely this one.  So if you're looking at this message and it says I made this comment "months ago", it's probably a brand new bug that's unrelated, and you should create a new issue.

-[Unknown]
