### ISSUE TITLE
BIOS/Firmware Emulation

### ISSUE THREAD

**Issue by PeladoFeo** [hrydgard/ppsspp#10687]
No emulator so far has this feature... NOT EVEN PPSSPP!
Therefore, PPSSPP should be able to emulate the PSP firmware as a "nostalgia option".

**Comment by hrydgard** [comment]
Not happening anytime soon, way too much work for little benefit, and I'm not even sure we're able to decrypt the whole thing. JPCSP has started work in this direction though.
