### ISSUE TITLE
Burnout Legends graphic issues

### ISSUE THREAD

**Issue by HypeChangerIvan** [hrydgard/ppsspp#10682]
Since, the 1.4 version of ppsspp, the graphics of burnout legends is still the same, the graphics became blurred and the sun, is turning into a "paper-like" structure.

**Comment by hrydgard** [comment]
On what hardware? On all devices I've tried it on, Burnout Legends looks fine (though is a bit slow when the sun appears due to the readbacks). If you are only seeing this with "slow block transfer effects" disabled, then that's as expected as the setting is required for the sun effect to work.

**Comment by HypeChangerIvan** [comment]
On android sir.

**Comment by abdellahking** [comment]
Hi men just give him the hardwar information so he can help you. You can find it on Sitting>tool>system information

**Comment by crazyrexz** [comment]
any chance to fix the sun ? when it gets on sun or certain areas, it slowdown, will it gets fixed in version 1.7.0? im on android

**Comment by Emulatorer** [comment]
### Buffered Rendering @ X1 Rendering Resolution
![Screenshot_2019-08-15-06-58-48](https://user-images.githubusercontent.com/37603562/63062149-6412dc00-bf2a-11e9-8e78-0ff179b860c8.png)
### Skipp Buffered Rendering @ Native Device Resolution
![Screenshot_2019-08-15-06-57-34](https://user-images.githubusercontent.com/37603562/63062176-87d62200-bf2a-11e9-960a-85d445d7a309.png)
### Buffered Rendering, Simulate Block Transfer Effects ON @ X1 Rendering Resolution
![Screenshot_2019-08-15-06-57-27](https://user-images.githubusercontent.com/37603562/63062256-ca97fa00-bf2a-11e9-8ba2-de75dcccca25.png)
This game running smooth @ X1 Rendering Resolution with Simulate Block Transfer Effects ON but I add this game to compat.ini
[BlockTransferAllowCreateFB]
ULES00125 = true # Burnout Legend
ULUS10025 = true # Burnout Legend
ULJM05228 = true # Burnout Legend
NPJH50305 = true # Burnout Legend
ULJM05049 = true # Burnout Legend
ULKS46027 = true # Burnout Legend
ULAS42019 = true # Burnout Legend

•Phone Specs
•Mali-450 GPU
•Android 5.1

**Comment by Emulatorer** [comment]
Using my tablet (Mali-T720/mt8163) even if I added burnout legend to blocktransferallowcreatefb compact.ini this game is so very lag @ X2 rendering resolution if block transfers effects is ON :/
Here's the dump hope you can fixed this @hrydgard 

[Burnout Legend DUMP.zip](https://github.com/hrydgard/ppsspp/files/3507982/Burnout.Legend.DUMP.zip)

**Comment by hrydgard** [comment]
I think it might possible to improve the way blocktransferallowcreatefb  works with this game (it uses inconsistent copy sizes so ends up creating a lot of little fbs, which is not ideal).

**Comment by hrydgard** [comment]
There's nothing more to do here except #12345 .

**Comment by Vemjay** [comment]
HEY GUYS. I FOUND THE FIX FOR THIS PROBLEM. 
GO TO YOUR SETTINGS IN THE EMULATOR. CHANGE THE MODE TO "SKIP BUFFER EFFECTS". 
MAKE SURE "SIMULATE BLOCK TRANSFER EFFECTS" IS ON. 
NEXT MAKE SURE FRAME SKIPPING & AUTO FRAMESKIP IS OFF. 
AFTER THAT, CHANGE YOUR RENDERING RESOLUTION  TO 2x PSP & YOUR DISPLAY RESOLUTION TO 2x PSP.
TRY TO SEE IF THAT WORKS BECAUSE IT SURE DID FOR ME!

**Comment by Gamemulatorer** [comment]
> HEY GUYS. I FOUND THE FIX FOR THIS PROBLEM.
> GO TO YOUR SETTINGS IN THE EMULATOR. CHANGE THE MODE TO "SKIP BUFFER EFFECTS".
> MAKE SURE "SIMULATE BLOCK TRANSFER EFFECTS" IS ON.
> NEXT MAKE SURE FRAME SKIPPING & AUTO FRAMESKIP IS OFF.
> AFTER THAT, CHANGE YOUR RENDERING RESOLUTION TO 2x PSP & YOUR DISPLAY RESOLUTION TO 2x PSP.
> TRY TO SEE IF THAT WORKS BECAUSE IT SURE DID FOR ME!

SIMULATE BLOCK TRANSFER EFFECTS WILL NOT WORK ON SKIPP BUFFERED RENDERING.
