### ISSUE TITLE
Castlevania sotn sprites glitches vulkan

### ISSUE THREAD

**Issue by Blacob777** [hrydgard/ppsspp#10695]
Opengl sprites look good but low perfomance 
![screenshot_2018-03-07-19-02-24-588_org ppsspp ppsspp](https://user-images.githubusercontent.com/29165096/37089420-72704284-223b-11e8-8a13-5eb96bd25ad2.png)

Vulkan norm perfomance but sprites glitches 
![screenshot_2018-03-07-18-53-04-257_org ppsspp ppsspp](https://user-images.githubusercontent.com/29165096/37089444-90914312-223b-11e8-890c-8a01d9c76cc9.png)
![screenshot_2018-03-07-18-54-15-540_org ppsspp ppsspp](https://user-images.githubusercontent.com/29165096/37089445-90c13bd0-223b-11e8-8684-3c42200345f1.png)
![screenshot_2018-03-07-19-03-53-393_org ppsspp ppsspp](https://user-images.githubusercontent.com/29165096/37089446-90f6d394-223b-11e8-9e5d-6dc43a77f51d.png)

**Comment by Blacob777** [comment]
Android, game running in dracula x chronicles

**Comment by hrydgard** [comment]
What GPU does your Android device have, and which driver version? You can find out in Tools/System Information in settings.

**Comment by Blacob777** [comment]
Adreno 530, im dont have information for driver version

**Comment by hrydgard** [comment]
Think I got this one, give it a shot.

**Comment by Blacob777** [comment]
@hrydgard now game just crashed
![screenshot_2018-03-20-17-26-33-146_com miui bugreport](https://user-images.githubusercontent.com/29165096/37646251-20c02c8c-2c64-11e8-9d75-f58861afec83.png)

**Comment by hrydgard** [comment]
Hm, thought I had fixed that one :(   Very latest build?  I'll look into it.

**Comment by Blacob777** [comment]
@hrydgard yeah latest build, game crashed only one firts time after update, next few times working normal, sprites fixed)

**Comment by hrydgard** [comment]
ok, it's some shader cache bug. I'll make sure it'll work in the future. Thanks!
