### ISSUE TITLE
Gran Turismo's funky text issue, Opengl backend

### ISSUE THREAD

**Issue by weihuoya** [hrydgard/ppsspp#10697]
What happens?
Gran Turismo's funky text issue, Opengl backend

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

ppsspp v1.5.4-652-g90dbd9a72, android 7.0, s7 edge

**Comment by marosis** [comment]
snapshot pls?

**Comment by weihuoya** [comment]
![screen](https://user-images.githubusercontent.com/3827333/37150390-7e0ec12a-230c-11e8-94cb-2cbd346c4100.png)
![screen2](https://user-images.githubusercontent.com/3827333/37150406-85dc07dc-230c-11e8-9a3e-072143376edc.png)

**Comment by weihuoya** [comment]
![screen3](https://user-images.githubusercontent.com/3827333/37150474-c2b765c0-230c-11e8-9d00-1acc303ac888.png)

**Comment by hrydgard** [comment]
Ah, this old thing, the game repeatedly overwrites a single texture and draws it, so something wrong in drawcall timing... Possibly related to the new gpu interpreter optimizations. How is it in Vulkan on that device?

**Comment by weihuoya** [comment]
vulkan not have this issue

**Comment by unknownbrackets** [comment]
I thought it was a block transfer, in the end, and we simply weren't zapping the texture cache on block transfers?

Can you confirm:
 * Which PPSSPP version this started on (e.g. did it happen in v1.5.4?)
 * That you have "simulate block transfer" enabled.
 * That you have "lazy texture hashing" off.
 * That you have "vertex cache" off.
 * That you have "disable slower effects" unchecked.

This is the code that should be preventing the issue:
https://github.com/hrydgard/ppsspp/blob/90dbd9a725540bbf6221e8437adea518371a38cc/GPU/GPUCommon.cpp#L2480

-[Unknown]

**Comment by weihuoya** [comment]
lastest dev build doesn't have this issue, sorry

**Comment by unknownbrackets** [comment]
Thanks for the update.  I wonder what fixed it...

https://github.com/hrydgard/ppsspp/compare/90dbd9a725540bbf6221e8437adea518371a38cc...3c16f84378b6267d03a071e0b8b9b23222eb0f50

I'm going to close this then.

-[Unknown]

**Comment by hrydgard** [comment]
There are still minor issues with text in Gran Turismo as @notnotme has shown on IRC.

https://imgur.com/a/CxCH8

**Comment by unknownbrackets** [comment]
Was it working before, or was it never fully fixed?

-[Unknown]

**Comment by notnotme** [comment]
@unknownbrackets If you mean ifit worked on the 1.5.4, yes, on this version text is nice. and with the fix you applied above on the dev builds, it looks like on my screenshot, so it's a bit better, but there are still some glitch.
