### ISSUE TITLE
Raspberry Pi and/or SDL issue: Screen goes black when text is displayed on Ape Quest.

### ISSUE THREAD

**Issue by vaguerant** [hrydgard/ppsspp#10690]
**What happens?**
Whenever text is displayed on-screen, e.g. subtitles during the opening FMV or dialogue upon starting a new game, the rest of the screen is completely black. That is, the FMV does not display at all, and the opening cutscene (not an FMV, rendered with in-game graphics) is only visible between snippets of dialogue; when dialogue boxes disappear, the screen becomes visible again.

The "invisible" content still seems to be being rendered if performance is anything to go by: a significant performance hit can be incurred on the Pi by increasing the internal resolution, even though all that's actually visible is some plain text.

**What *should* happen?**
From testing with the same image on the 64-bit Windows build, this issue is not present at all, the background over which the text is being overlaid is fully visible during all on-screen display of text.

**What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.**
PPSSPP-SDL 1.5.4 on a Raspberry Pi running Raspbian Jessie.

**Log**
[ppsspp.log](https://github.com/hrydgard/ppsspp/files/1779688/ppsspp.log)

**Comment by unknownbrackets** [comment]
Could be dual source blending or some other feature that isn't supported on GLES2.

-[Unknown]

**Comment by hrydgard** [comment]
Or any sort of GL driver bug, quite common on these devices that aren't heavily supported by games...

**Comment by unknownbrackets** [comment]
Could you try exporting a GE debugger dump on PC?

To do this, open the game and select Debug -> GE debugger..., then when it's displaying the scene, press Record in the top right.  After a second or so, it'll finish and save a trace of the drawing activity.

After that, check the memstick/PSP/SYSTEM/DUMP folder and it'll have created a file named something like "ULES12345_0000.ppdmp".  You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by hrydgard** [comment]
Is this still an issue? Please reopen if so.
