### ISSUE TITLE
From one Swedish guy to another @hrydgard (regarding shaders)

### ISSUE THREAD

**Issue by TheLocoBandito** [hrydgard/ppsspp#10699]
Hej Henrik!

Först vill jag säga tack för en strålande PSP emulator, den gör sitt jobb med stor glans.

Jag antar att du känner till Libretro? Av någon konstig anledning [fungerar inte användandet av shaders](https://github.com/libretro/ppsspp/issues/55) [**](https://forums.libretro.com/t/ppsspp-not-working-with-shaders/12482) så värst bra för Libretro kärnan.

psp-color.glsl fungerar men bara i så kallat Windowed mode, ej när du togglar fullskärm och motionblur-simple.glsl fungerar inte alls och inte kombinerat med psp-color.glsl heller.

Vet du om ppsspp är känsligt för vissa typer av shader filer?

Jag har starkt för mig att användandet av shaders i den utdaterade versionen av Libretro kärnan som var baserad på 1.0.1 fungerade alldeles ypperligt.

Vill inte på något sätt låta desperat men detta är ett tappert försök att till vädjan.
Tro mig, jag har försökt att konvertera dessa två ovannämnda shaders till ppsspp's .fsh och .vsh format men har inte lyckats.

psp-color och motionblur-simple är typ det ända jag saknar men inte har lyckats fått fungera.

Jag vet inte om det är RetroArch det är fel på eller om det är ppsspp som ställer till det när man försöker använda shaders med Libretro kärnan.

Tack på förhand!

**Comment by hrydgard** [comment]
Hej,

Please stick to English when posting bug reports. Tack! :)

The RetroArch port is not very actively maintained unfortunately, but thanks for reporting these issues - hopefully somone will take a look in the near future :)

**Comment by TheLocoBandito** [comment]
Actually, by some miracle all my shader problems have been lifted away because it now works as intended.

The PPSSPP core used to be called PPSSPP 1.4.2-git, but now it's just called PPSSPP 7f30ab1 (as an example) and by looking at the core options there seems to have been a lot of work made to it in just a few days time.

Well I'm sorry if I posted in Swedish, it was not my intention and as you surely can tell English is not my first language.

Thanks a ton anyway Henrik!
