### ISSUE TITLE
Running via command line crashes the game

### ISSUE THREAD

**Issue by torben656** [hrydgard/ppsspp#10692]
What happens?
The game crashes when I try to either drag and drop the iso file to the .exe or when I try to use the command line parameters (PPSSPP.exe "the game.iso"). I am currently using the latest nightly, but somehow the stable builds allow the command line and drag n' drop. Please help.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

AMD A4 6300 with Radeon Graphics 3.7 GHz
2.00 GB RAM
32-Bit operating system Windows 7

**Comment by TheLocoBandito** [comment]
I have the same issue as you, I can confirm it still works on 1.5.4-562 at least and the latest seems to be 1.5.4-652 [here](https://buildbot.orphis.net/ppsspp/) so it's only recently it started to be broken.

I use customized batch file loaders to load my games and noticed it crashed right away in 1.5.4-652 but not in 1.5.4-562.

**Comment by TheLocoBandito** [comment]
https://github.com/hrydgard/ppsspp/commit/0ed3deabe6b4723e918a9d2d36ad6407ccd017f2 sure did fix this, thanks a lot!
