### ISSUE TITLE
Change display resolution(HW scaler) crash, Vulkan backend

### ISSUE THREAD

**Issue by weihuoya** [hrydgard/ppsspp#10696]
What happens?
Change display resolution(HW scaler) crash, Vulkan backend

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

ppsspp v1.5.4-652-g90dbd9a72, android 7.0, s7 edge

**Comment by Blacob777** [comment]
yes i have this problem too

**Comment by weihuoya** [comment]
app on resume `graphicsContext` is NULL  in this function, because on pause this function delete `graphicsContext`
```c++
extern "C" bool JNICALL Java_org_ppsspp_ppsspp_NativeActivity_runEGLRenderLoop(JNIEnv *env, jobject obj, jobject _surf) {

	NativeShutdownGraphics();
	renderer_inited = false;

	ILOG("Shutting down graphics context.");
	graphicsContext->Shutdown();
	delete graphicsContext;
	graphicsContext = nullptr;
	renderLoopRunning = false;
	WLOG("Render loop function exited.");
}
```

**Comment by hrydgard** [comment]
Ah, right. It's annoying that we need two separate render loops for GL vs Vulkan on Android, the interactions get complex. I'll fix it up, thanks @weihuoya .

**Comment by hrydgard** [comment]
@weihuoya  This should be fixed now, let me know if you still have trouble.
