### ISSUE TITLE
blackscreen on final fantasy type-0's fmv

### ISSUE THREAD

**Issue by sephiroth0396** [hrydgard/ppsspp#10694]
The latest official release and build won't play any FF type-0's cutscenes.

**Comment by Saramagrean** [comment]
On my device (Huawei P9+), Cutscenes (FMV) is playable normally but slowdown with Simulate block transfer effects enabled.

**Comment by unknownbrackets** [comment]
What graphics backend, what device, what PPSSPP versions?  Does it work with an earlier version, and if so, what's the first git build that stopped working?

-[Unknown]

**Comment by hrydgard** [comment]
@sephiroth0396 , any details you can share, as unknownbrackets asks for above?

**Comment by sephiroth0396** [comment]
Sorry, I just get a chance to use internet again lol I'm using openGL ES. It's work fine in 1.4.2 but in the latest official and build version, it's doesn't work at all

**Comment by llothbrok** [comment]
I have the same issue. The cutscenes até playing normally in the 1.4.2 version for Android, but It doesn't in 1.5.4. The plugin is OpenGL as well.

**Comment by llothbrok** [comment]
are*

**Comment by unknownbrackets** [comment]
What's the first git build that doesn't work, and the most recent git build that does?

You can go by halves, so if there are 1000 builds in between, try somewhere around 500 first.  You can find where it broke with about 10 tries this way, even among 1000 builds.

Unfortunately, I don't have this game and haven't seen this issue anywhere else, so I can't do this.

-[Unknown]

**Comment by hrydgard** [comment]
Suspecting this may be another one of the cases where we forget to disable wrapping for non-pow-2 textures somehow...

**Comment by sephiroth0396** [comment]
@unknownbrackets actually it's doesn't work since the official release of 1.5.4 version ( I'm not sure it's work in the final git build of 1.4.2 version. )

**Comment by unknownbrackets** [comment]
This may have been fixed by #10892.  Can you try the latest git build?

-[Unknown]

**Comment by unknownbrackets** [comment]
This game was confirmed fixed in #10862, although there are potentially other issues there.

I'm closing, but you can still comment if it's not fixed for you and we'll reopen.

-[Unknown]

**Comment by sephiroth0396** [comment]
Sorry, Just have a chance to use the internet again. It's fixed in the latest git build, I am trying it right now. Not sure if it's work till I finish the game, will report it later.
