### ISSUE TITLE
UWP freezes right at the beginning On XBox One and PC (WIN10) "Platform-specific (UWP)" 

### ISSUE THREAD

**Issue by Slippy2k** [hrydgard/ppsspp#10705]
What happens?
I'm loading a game with UWP no matter what game I start I have started for example (Rocky Balboa Europe) But others also do not run (freezes right at the beginning) but this in all games

What *should* happen?
Game should not freeze after the invite

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
On PC  (WIN10) and XBox One In both systems, the UWP emulators freezes

**Comment by asferot** [comment]
Have I missed something? Since when there is UWP PPSSPP port?

**Comment by hrydgard** [comment]
There is an experimental one, look in the UWP subdirectory for the .sln if you want to build it yourself. but it often breaks, I fix it up from time to time but nobody is actively maintaining it. Right now it even seems to have some kind of code signing issue that I haven't gotten around to figuring out yet.

**Comment by Slippy2k** [comment]
I noticed that it's experimental because it only works with older versions. Because there the emulator does not freeze yet
