### ISSUE TITLE
[Feature Request] Auto Landscape Rotation option

### ISSUE THREAD

**Issue by leopard20** [hrydgard/ppsspp#10708]
By auto landscape I mean automatic switch between landscape and inverted landscape modes as you flip the device upside down.

**Comment by Florin9doi** [comment]
setRequestedOrientation(SCREEN_ORIENTATION_SENSOR_LANDSCAPE); in android/src/org/ppsspp/ppsspp/NativeActivity.java should do it

**Comment by leopard20** [comment]
@hrydgard
Thank you for trying to implement this. But what I meant was Landscape Auto, which is an automatic switch between **Landscape** and **Landscape Reverse**, but right now the Auto option cycles through all possible orientations, including portrait and portrait reverse.
Another limitation: The option doesn't work if Autorotation is turned off through phone settings.

**Comment by hrydgard** [comment]
Yeah I eventually understood that. Florin9doi has contributed what you want in https://github.com/hrydgard/ppsspp/pull/10751 , just waiting for him to make a change.

**Comment by leopard20** [comment]
Actually, I've seen plenty of games that work without autorotation on. I'm not sure how they do this though!

For example:
GTA SA, Xash3D, Special Forces Group 2, etc.

That Xash3D I mentioned is actually open source, hosted on this very github. Maybe you could look at the source codes or ask the creator, a1batross.

**Comment by leopard20** [comment]
Here's the link:
https://github.com/FWGS/xash3d-android-project

**Comment by hrydgard** [comment]
But that seems completely pointless? Presumably, if the user has disabled autorotation in the OS, they don't want the screen to rotate.

**Comment by leopard20** [comment]
You could be right. But personally I don't want my phone to change from Landscape to Portrait every time I make a ~50 degree rotation, which is inadvertent most of the time! But switching between Landscape and Landscape Reverse in games doesn't pose any inconveniences to me. Besides, it only reverses when I rotate the phone more than 90 degrees. That can't be inadvertent.

Besides, since this new rotation option is called Landscape Auto, people who select it **want** their phone to rotate right?! 😉

**Comment by Florin9doi** [comment]
Landscape Auto don't requires to enable autoratotion.  It works the same as the games mentioned.
