### ISSUE TITLE
EmuThread timed out MHP3rd

### ISSUE THREAD

**Issue by NoProbz** [hrydgard/ppsspp#10701]
What happens?

Crashes after saying Beginning Quest in Loading Screen

What *should* happen?

Well...loaded properly and no crash

[ppsspplog.txt](https://github.com/hrydgard/ppsspp/files/1796079/ppsspplog.txt)

**Comment by NoProbz** [comment]
The Crash didnt happen yesterday... It just happen today

**Comment by fahadfoyjur** [comment]
Is ppsspp use 2 core ? Plz tell me

**Comment by NoProbz** [comment]
my pc specs is quite an oldie 
 intel hd 
 intel core i5 M520 @ 2.40ghz

**Comment by unknownbrackets** [comment]
What's the first git build that crashed, and the last one that didn't?

If you try an older stable release and it works, finding when it stopped doesn't take all that long: just go by halves.  If it was 1000 builds ago, try 500 ago, and then go up or down.  It would take 10 tries to find the commit out of 1000.

I don't personally have the game or experience the issue, so finding out when it broke is really hard for me.  But there's a decent chance I can fix it if you can tell me when it broke.

If it's always been broken, that's harder.  But other people have been able to play this game without crashes in the past.

-[Unknown]

**Comment by hrydgard** [comment]
Surprising amount of ```D[G3D]: GPUCommon.cpp:1218 RET: Stack empty!``` seen in the logs, which might be a game bug? Other than that I'm not seeing anything suspicious in the log. Also, the latest builds don't have the message "EmuThread timed out" any more...

**Comment by unknownbrackets** [comment]
I believe testing on hardware has shown that stack empty / stack full is just ignored.  I think we've seen that in this game for a long time and I think it may be expected.

-[Unknown]

**Comment by unknownbrackets** [comment]
Does this still happen in 1.6.0 or the latest git build?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
