### ISSUE TITLE
OpenGL Vsync not working since new GL multithreading render

### ISSUE THREAD

**Issue by ShadowLady** [hrydgard/ppsspp#10711]
As title says, Vsync when using OpenGL hasn't worked for me since the new  GL multithreading render manager got merged. (last worked on ppsspp-v1.5.4-387)

Can't check Vulkan (doesn't work with fermi) and Direct3D11 always seem to use the WDM vsync  (not as smooth as OpenGL vsync) regardless of me enabling the option on PPSSPP or not.

Windows 10
nvidia GTX 560ti
ppsspp on fullscreen mode (not sure if it matters)

**Comment by fahadfoyjur** [comment]
Is ppsspp really use 2core ??

**Comment by hrydgard** [comment]
Thanks @ShadowLady , forgot to fix this up, will do so soon.

@fahadfoyjur  Yes now it does, but should be irrelevant to this issue.

**Comment by fahadfoyjur** [comment]
But ppsspp.ini  file shows 1core ?

**Comment by hrydgard** [comment]
@fahadfoyjur That's not relevant anymore, multithreading is now fully automatic.

**Comment by fahadfoyjur** [comment]
Thank you for reply hrydgard now psp games fully lag free but little bit sound choppy .  Thanks again sir

**Comment by hrydgard** [comment]
Should be fixed now, let me know if it works for you.

**Comment by ShadowLady** [comment]
Working great. Thank you.
