### ISSUE TITLE
Memory leak when I use load state

### ISSUE THREAD

**Issue by leopard20** [hrydgard/ppsspp#10721]
What happens?
When I use load state too many times my device's RAM fills up and causes the OS to close all programs, including PPSSPP.
If I don't use load state a lot even playing for hours doesn't cause any issue (except maybe causing some injury to myself! LoL)

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Android 7.0
Vulkan Backend (OpenGL not tested)
RAM: 4 GB (approximately 2.2 GB free)

I noticed the issue in the following games (not sure about the rest). All states were saved in-game and not in menus:
Project Diva Extend
GoW GoS
The 3rd Birthday

To reproduce the issue, run a heavy game, save the state mid-game, and load it 20-30 times!

**Comment by unknownbrackets** [comment]
This doesn't happen for me in 3rd Birthday on Windows - I just went to the start of the first mission, saved state, and then proceeded to load that state over and over.

Can you upload a state that causes this - in case it's something specific?

It's possible this is some sort of Vulkan driver issue...

-[Unknown]

**Comment by hrydgard** [comment]
Or simply a Vulkan backend bug, though I'd be hard-pressed to think of a likely culprit....

**Comment by leopard20** [comment]
I don't think it's caused by a specific state because it happend in three different games. 
I'll test openGL later to see if it has the same issue.
Did you try overwriting the state a few times? Maybe it's caused by a combination of saving and loading?

**Comment by leopard20** [comment]
OK I can confirm it only happens with Vulkan. So that should narrow it down.
After loading the same state over and over again for like 20 times my amount of free RAM dropped from 2 GB to 1.4 GB. But doing the same with openGL didn't cause any drop in free RAM (constantly at ~1.9 GB)

**Comment by leopard20** [comment]
Can you guys test it on your phones? Maybe it's a bug in my ROM.

**Comment by leopard20** [comment]
BTW I tested the latest dev version and the issue was already fixed! (I did the above tests with v1.5.4)
I'll leave this open so you guys can confirm the same thing on your phones. Then close this if you want.

**Comment by unknownbrackets** [comment]
Ah, I think there may indeed have been a leak fixed since v1.5.4.

-[Unknown]

**Comment by hrydgard** [comment]
Gonna close, haven't seen issues like this for some time.
