### ISSUE TITLE
ppsspp 1.5.4 on Gentoo doesn't respond over bluetooth to Sony DualShock 4.

### ISSUE THREAD

**Issue by crocket** [hrydgard/ppsspp#10724]
What happens?

DualShock 4 input over bluetooth is ignored. USB input is recognized.

What *should* happen?

DualShock 4 bluetooth input should be respected.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

* GPU
  * AMD HD6450
* CPU
  * AMD FX-8300
* OS
  * Gentoo Linux
* Controller
  * Sony DualShock 4 Green Camouflage CUH-ZCT2G 16 (This model was released on January 2017.)
* ppsspp-1.5.4 USE flags (- means disabled. + means enabled)
  * -headless
  * -libav
  * +qt5
  * -sdl
  * +system-ffmpeg

**Comment by hrydgard** [comment]
Does bluetooth DualShock4 work in other games on your machine? Thinking that it might not be a PPSSPP-specific problem..

**Comment by crocket** [comment]
It works on RetroArch and PCSX2.

**Comment by Anonymphous** [comment]
Well, it does work on Windows through an ASUS USB-BT400,
and it works on Android when paired with a Sony Xperia Z5, but it seems Sony does provide a driver for Android, as DS4 does not work on a Galaxy Tab through Bluetooth.

**Comment by unknownbrackets** [comment]
Having -sdl ought to mean that no gamepad will work.

-[Unknown]

**Comment by crocket** [comment]
I reinstalled with +sdl and -qt. The terminal output reveals that DualShock 4 is recognized, but its mappings are wrong. For example, the touchpad click is recognized as D-pad up in PPSSPPSDL.

**Comment by hrydgard** [comment]
Ah, seems like it. When you got a gamecontrollerdb.txt line that works, report it here and I'll merge it (or you can make a pull request).

**Comment by unknownbrackets** [comment]
Even in the Qt port, we use SDL for gamepads.  I'm not sure if -sdl disables that or not.

-[Unknown]

**Comment by crocket** [comment]
All I had to do was to copy the mappings from

```
030000004c050000cc09000011010000,Sony DualShock 4 V2,a:b1,b:b2,y:b3,x:b0,start:b9,guide:b12,back:b13,leftstick:b10,rightstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a5,lefttrigger:a3,righttrigger:a4,platform:Linux,
```

I added the following line to gamecontrollerdb.txt, and my DualShock 4 works over bluetooth.

```
050000004c050000cc09000001000000,Sony DualShock V2 Wireless Controller,a:b1,b:b2,y:b3,x:b0,start:b9,guide:b12,back:b13,leftstick:b10,rightstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a5,lefttrigger:a3,righttrigger:a4,platform:Linux,
```

**Comment by hrydgard** [comment]
Thanks! Don't usually bother with updating sub-releases, but this will get into 1.6.

**Comment by crocket** [comment]
After recompiling ppsspp with -sdl and +qt5, I discovered that adding that line to the dataabse was sufficient to make my controller work.
