### ISSUE TITLE
Vulkan is available as a choice even if device does not support it (Android 7+)

### ISSUE THREAD

**Issue by fahadfoyjur** [hrydgard/ppsspp#10729]
My friend's device is android 7.0 , 2gb ram ,
Mali 400mp2 , the ppsspp graphics backend shows open gl & vulkan 
I am choose vulkan , the ppsspp restered and sayed cannot support vulkan api , 
Why ?  I am using latest version of ppsspp 1.5.4 build .
Sorry for my bad english

**Comment by hrydgard** [comment]
Mali 400 does not support Vulkan, there is no way it will work. I think some newer Android versions ship an "empty" vulkan implementation, need to add smarter detection to avoid displaying Vulkan as an option on those.

**Comment by hrydgard** [comment]
This should be fixed now - Vulkan should no longer show up on these devices.
