### ISSUE TITLE
[Feature Request]Expand Discord Integration with Rich Presence

### ISSUE THREAD

**Issue by AkiraJkr** [hrydgard/ppsspp#10720]
I have no idea how to make a pull request, so that's why I made a issue instead:

Discord has created Rich Presence, which lets game creators expand how their games get detected, and what is shown in the rich presence feature. So, I've been wondering if that feature can have game detection implemented as in: The user status in Discord will still be "Playing PPSSPP". BUT, upon clicking them on the userlist, the Rich Presence shows, with the name of the game they are currently playing.

I feel like this would be soo much better than simply showing the user is using the emulator. But not the game.

https://discordapp.com/rich-presence

**Comment by hrydgard** [comment]
Yeah, this would be totally possible, the SDK is actually released under the MIT license so I don't believe there would be any licensing issues. It's just a bunch of work :)

**Comment by MorrisonGamer** [comment]
When approximately do you think this would be implemented then? And do you have any idea what would be a solution to making this easy?

I believe that the use of a database(if there isn't one already) That has the game's original ID/Name, then a simplified name seems like a good solution, and the community can contribute to the database by adding the ULXXXXX - Name for them.

**Comment by hrydgard** [comment]
Don't even need that, pretty much all games have a decently formatted game name already included, which is what you're seeing if you change the game list to list view.

Just need to do a small integration, but you know, priorities. Coding, testing, takes a little time.

**Comment by hrydgard** [comment]
For future reference, here's RPCS3's implementation:

https://github.com/RPCS3/rpcs3/commit/3b24e7e685d075fc08c81ae6839bb809ea8e3cd4

**Comment by AkiraJkr** [comment]
Marking this issue as closed, as it is solved, even with the basic integration.
