### ISSUE TITLE
PPSSPP control mappings don't match /usr/share/ppsspp/assets/gamecontrollerdb.txt

### ISSUE THREAD

**Issue by crocket** [hrydgard/ppsspp#10739]
* OS
  * Gentoo Linux
* PPSSPP version
  * 1.5.4
* PPSSPP USE flags
  * +sdl
* Default PPSSPP control mappings
  * Cross : pad1.b2
  * Circle : pad1.b3
  * Rectangle : pad1.b4
  * Triangle : pad1.b1
  * Left Shoulder : pad1.b7 (It needs to be changed to pad1.b6)
  * Right Shoulder : pad.b8 (It needs to be changed to pad1.b5)
* /usr/share/ppsspp/assets/gamecontrollerdb.txt
  * a = b1 = Cross
  * b = b2 = Circle
  * x = b0 = Rectangle
  * y = b3 = Triangle
  * LeftShoulder = b4
  * RightShoulder = b5
* Controller
  * Sony DualShock 4 Green Camouflage CUH-ZCT2G 16 over USB and Bluetooth

I can't see a relationship between PPSSPP control mappings and gamecontrollerdb.txt

**Comment by unknownbrackets** [comment]
Are you sure you were looking at the right line?  It may also allow reading from other folders, including these and where the binary is:

https://github.com/hrydgard/ppsspp/blob/106a299c06b854998c154bea1b0fdd6dac36591a/UI/NativeApp.cpp#L469-L472

-[Unknown]

**Comment by crocket** [comment]
I don't use ppsspp anymore. I choose to close this issue.
