### ISSUE TITLE
Ppsspp latest built crash

### ISSUE THREAD

**Issue by abdellahking** [hrydgard/ppsspp#10732]
What happens?
When i just update ppsspp on latst built he just crash. and whe i use v1.5.4-689-g31de74c56 built or any other he work well.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
my device is Arm64 mali t720 quad Processor 1.3GHZ .3GB RAM with open gl

And if you need any thing just ask me

**Comment by hrydgard** [comment]
Ok, probably some issue with the new Vulkan detection. I'll look into it.

**Comment by hrydgard** [comment]
Can you get an ADB log of the crash? 

So 689 works, but 692 is broken?

**Comment by abdellahking** [comment]
I actually didnt have root access and my pc is broken so no i cant get you adb log.sorry
And yes 689 work verry well but the latest (692) he just crash when i opened him

**Comment by hrydgard** [comment]
ah, weird :(    Does Vulkan work on your device at all?

**Comment by abdellahking** [comment]
No. my device didnt support vulkan library:'(

**Comment by fahadfoyjur** [comment]
Latest build shows unfortunately stopped

**Comment by abdellahking** [comment]
Yaaay. The latest built(696) it work Porfectly thank's sir for the yoir hard work and i wish you luck

**Comment by hrydgard** [comment]
Excellent, thanks for letting me know.
