### ISSUE TITLE
Android Ppsspp api vulkan crashing on recent build 

### ISSUE THREAD

**Issue by SamueldeSena** [hrydgard/ppsspp#10744]
In build v1.5.4-712-g1dabccb45 when I select the picture vulkan practically dotos the games closing few times they can execute seem emulator close my cell phone octa core 2hgz adreno 506 3 of ram

**Comment by fahadfoyjur** [comment]
Android version ??

**Comment by hrydgard** [comment]
Maybe a problem with the new shader cache. Try the latest build, 715, and see if it's the same.

**Comment by fahadfoyjur** [comment]
Hrydgard , 
I want to know what is. SAS thread ? And I/o thread ??    And separate sas thread cause ?? & i/o thread ?? Sry my bad eng . and sorry off topic plz reply

**Comment by hrydgard** [comment]
@fahadfoyjur Sas is the audio mixer. I/O is for doing I/O (disk read/write) off thread to support background loading.

**Comment by fahadfoyjur** [comment]
Thank you big bro hrydgard . 😊😊😊 love you

**Comment by SamueldeSena** [comment]
the problem still persists after an emulation time depending on the game

**Comment by hrydgard** [comment]
Still happens?

**Comment by hrydgard** [comment]
This issue doesn't have enough detail to be actionable, I'm closing.
