### ISSUE TITLE
Phantasy Star Portable 2: Dark background fights to be on top (z-fighting)

### ISSUE THREAD

**Issue by mlwj1993** [hrydgard/ppsspp#10749]
What happens?
On Vulkan Rendering backend the background fights to be on top (looks like Z-fighting)
(uploaded .avi to make issue visual, see latest few seconds of recording, this also happens with the text bubbles in-game):
http://www.mediafire.com/file/d4euaq1gc2jz7f0/ULUS10529_2018-03-19_18-59-27.zip

What *should* happen?
Background should be rendered as the background and not fight to be on top.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Windows 10 Home 64 bits (10.0, build 16299).

Intel core i7-6700HQ @2.60 GHz (8 CPU's)
Intel HD Graphics 530
Nvidia Geforce GTX960M (Geforce game ready driver 391.01)

Using PPSSPP version: 1.5.4-719-g24b9fb6ea

**Comment by hrydgard** [comment]
Thanks for reporting. Just noting that ULUS10529 is Phantasy Star Portable 2, which many people report depth issues with, like in #10735 .

**Comment by unknownbrackets** [comment]
I think we also use a depth hack in this game.  I'm not sure if it's compatible with the accurate depth path (it may disable accurate depth, I forget.)  So there could also be flipped depth issues.

-[Unknown]

**Comment by hrydgard** [comment]
Bumping this to 1.7.0 since it's not clear it's a regression.

**Comment by hrydgard** [comment]
Is this still an issue?

**Comment by mlwj1993** [comment]
Just checked on latest dev build, seems to be fixed, at least the initial start menu is fine now.

**Comment by unknownbrackets** [comment]
Okay, I'll mark this closed, but if you or anyone else experience it again on Intel or mobile NVIDIA please comment and we can reopen.  Might've been the game ids.

-[Unknown]
