### ISSUE TITLE
fix glitching chara

### ISSUE THREAD

**Issue by akuda** [hrydgard/ppsspp#10759]
What happens?

![2018-03-21](https://user-images.githubusercontent.com/37605508/37692681-dee0e354-2cec-11e8-8ef6-6f01cdc46a57.png)
why is the graphics like this? ive tried multiple settings

What *should* happen?

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

**Comment by LunaMoo** [comment]
I don't think we need another issue for this game's graphics with #4786 and #5918, so going to close this.

 Also that problem looks like the old issue affecting Danball, Gundam, Jeanne d'Arc, Saint Seiya and maybe some other games which require modern gpu(preferably dedicated one) with proper GLES/OGL 3+ support to emulate certain effects and will most likely never display correct graphics on ancient hardware. If your gpu is new, try updating gpu drivers, make sure to use default settings and maybe also try different backend.
