### ISSUE TITLE
Couldn’t communicate with a helper application. MAC

### ISSUE THREAD

**Issue by BenCosmos** [hrydgard/ppsspp#10754]
What happens?
I tried playing the Sony PSP but every game I try just keeps giving me this message. "Couldn’t communicate with a helper application."

I've tried looking up solutions but no avail. Could someone walk me through this?

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

**Comment by unknownbrackets** [comment]
I'm not sure, but it sounds like this is an Apple / Mac error and not specific to PPSSPP itself (I'm assuming you get it when either trying to compile or run PPSSPP?)

It might be better to use the forum or stackexchange/etc. to get answers on Mac issues.

Otherwise, need more information - when exactly does this happen?  What versions have you tried?

-[Unknown]

**Comment by BenCosmos** [comment]
I think this is a problem with the program since the problem only affects a few emulators. I'm not sure if this will help but here is a screenshot of things I am supposingly missing (though I don't see anything missing for ppsspp). 

<img width="423" alt="screen shot 2018-03-20 at 9 41 42 am" src="https://user-images.githubusercontent.com/37565254/37658117-313a237e-2c23-11e8-8dff-53b6c3a9941b.png">
<img width="419" alt="screen shot 2018-03-20 at 9 41 56 am" src="https://user-images.githubusercontent.com/37565254/37658118-31482b04-2c23-11e8-91ba-5d0de33a6fbe.png">
<img width="420" alt="screen shot 2018-03-20 at 9 40 58 am" src="https://user-images.githubusercontent.com/37565254/37658119-3152fa34-2c23-11e8-818c-6ae022df2ea8.png">
<img width="424" alt="screen shot 2018-03-20 at 9 41 22 am" src="https://user-images.githubusercontent.com/37565254/37658120-316a9af4-2c23-11e8-9bbe-a81536e8c127.png">
<img width="423" alt="screen shot 2018-03-20 at 9 42 03 am" src="https://user-images.githubusercontent.com/37565254/37658122-317ad680-2c23-11e8-8a0d-a3b9b8d3466a.png">

I am using the latest version OpenEmu v2.0.6.1
When the game loads up its just a black screen forever. When I quit the game it gives me that message. I hadn't thought about using other versions 😛.

**Comment by unknownbrackets** [comment]
Ah - this is PPSSPP, which only emulates PSP games.  I think you're looking for this:

https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

Note that OpenEmu seems to use an old version of PPSSPP with customizations for OpenEmu.  You can also try PPSSPP itself from here:
https://ppsspp.org/downloads.html

-[Unknown]
