### ISSUE TITLE
Naruto Shippuden Ultimate Ninja Heroes 3 Blackscreen during intro movie

### ISSUE THREAD

**Issue by Jinzombie** [hrydgard/ppsspp#10758]
What happens? Naruto Shippuden Ultimate Ninja Heroes 3 blackscreen during intro movie using ppsspp 1.4.2-1.5.4 but when I use ppsspp 1.3 below its work no blackscreen?

PS: Sorry for my english 

What *should* happen?

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

phone specs:
Mali-450 MP
Octacore
2GB RAM
1.4Ghz

**Comment by Saramagrean** [comment]
Duplicate https://github.com/hrydgard/ppsspp/issues/9591 ?

**Comment by Jinzombie** [comment]
Oh sorry I didn't know its already been reported 😅
