### ISSUE TITLE
Hang at Launch (OpenGL only, fallback to D3D9 doesn't happen)

### ISSUE THREAD

**Issue by KatherineFtw** [hrydgard/ppsspp#10752]
What happens?
I launch it, and windows basically stops until it's closed. I've tried both 1.4.2 and 1.5.4, both installer and zip, both cause this issue. Can't even open the debugger for a log file, it's that bad. 

- Problem details -
Problem signature
Problem Event Name:	AppHangB1
Application Name:	PPSSPPWindows64.exe
Application Version:	1.5.4.0
Application Timestamp:	5a26acd0
Hang Signature:	334c
Hang Type:	134217728
OS Version:	10.0.16299.2.0.0.768.101
Locale ID:	1033
Additional Hang Signature 1:	334c6b321bb203e931b3c5865c5127a1
Additional Hang Signature 2:	1348
Additional Hang Signature 3:	1348ccb9c2ab6d5bece49268e52481fd
Additional Hang Signature 4:	334c
Additional Hang Signature 5:	334c6b321bb203e931b3c5865c5127a1
Additional Hang Signature 6:	1348
Additional Hang Signature 7:	1348ccb9c2ab6d5bece49268e52481fd

What *should* happen?
IDK, it opens and doesn't nearly crash windows? I last used PPSSPP years ago on my old PC.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Dell Insperion 7559
Intel-i5 6300 HQ
Nvidia GTX-960M
8GB of RAM
Western Digital 2 TB External Hard Drive

**Comment by hrydgard** [comment]
Weird, this is not happening for many people so must be something specific to your setup. Two things that may be interesting to try: 

  * Upgrade your NVIDIA drivers to the latest version
  * Go into memstick/PSP/SYSTEM/ppsspp.ini and change GPUBackend to 0, 1, 2, and 3, and see if any of those work.

**Comment by KatherineFtw** [comment]
System is empty.

**Comment by KatherineFtw** [comment]
Update: Deleated PPSSPP, attempting the ZIP of 1.5.4 again.

**Comment by unknownbrackets** [comment]
Can you try much older versions, such as 1.0.1?  Just wondering if any version works.

https://github.com/hrydgard/ppsspp/releases/tag/v1.0.1

-[Unknown]

**Comment by KatherineFtw** [comment]
Problem signature
Problem Event Name:	AppHangB1
Application Name:	PPSSPPWindows64.exe
Application Version:	1.0.1.0
Application Timestamp:	54ef8192
Hang Signature:	db44
Hang Type:	134217728
OS Version:	10.0.16299.2.0.0.768.101
Locale ID:	1033
Additional Hang Signature 1:	db44db06cf72c887e5d965642ec2cfcf
Additional Hang Signature 2:	7c9c
Additional Hang Signature 3:	7c9cdcf1bdb3e667e59fa7366cd8ab80
Additional Hang Signature 4:	db44
Additional Hang Signature 5:	db44db06cf72c887e5d965642ec2cfcf
Additional Hang Signature 6:	7c9c
Additional Hang Signature 7:	7c9cdcf1bdb3e667e59fa7366cd8ab80

I'll keep trying 1.0.1.

**Comment by KatherineFtw** [comment]
Attempt with v0.9.5.

Well first off, I got the debug console open, not too much to report though.............
![untitled](https://user-images.githubusercontent.com/36945646/37859850-6c513a66-2ee8-11e8-801e-bf9c1533ab6a.png)

Problem signature
Problem Event Name:	AppHangB1
Application Name:	PPSSPPWindows64.exe
Application Version:	0.0.9.5
Application Timestamp:	527393b8
Hang Signature:	eca0
Hang Type:	134217728
OS Version:	10.0.16299.2.0.0.768.101
Locale ID:	1033
Additional Hang Signature 1:	eca02242278a6f8fa2ad3f43ddd75196
Additional Hang Signature 2:	3057
Additional Hang Signature 3:	3057384488d384f8a71184efd4df4e51
Additional Hang Signature 4:	eca0
Additional Hang Signature 5:	eca02242278a6f8fa2ad3f43ddd75196
Additional Hang Signature 6:	3057
Additional Hang Signature 7:	3057384488d384f8a71184efd4df4e51

**Comment by KatherineFtw** [comment]
I have an idea if nothing else. Can you upload the default memstick files for me to put in there and see if it hangs?

**Comment by Michal1324** [comment]
Perhaps try to clean boot and try to run PPSSPP no idea if that would work but its worth a shot or even in safe mode

**Comment by KatherineFtw** [comment]
<img width="591" alt="untitled" src="https://user-images.githubusercontent.com/36945646/37865854-38c0ec24-2f50-11e8-8a95-9d998a315150.png">

We found the issue I guess. Booted in Safe Mode. OpenGL was the issue according to this. No issues with DX9.

**Comment by hrydgard** [comment]
OK, good. Unfortunate that we failed to fall back automatically to D3D...

Hopefully if anyone else has this problem they'll end up here when googling. To force another GPU backend on first boot, start PPSSPP from the command line (or a shortcut) with the argument  --graphics=directx9" or "--graphics=directx11" or "--graphics=vulkan".

By the way, you might want to try to download the latest drivers for your GPU from NVIDIA, that might also have solved it.

**Comment by KatherineFtw** [comment]
I have the latest drivers, the issue is that memstick doesn't load properly either. I had to go into safe mode before this occurred.

**Comment by TehPlayer14** [comment]
Make sure the dedicated gpu gets picked to render job for ppsspp because you might've integrated graphics

**Comment by hrydgard** [comment]
@KatherineFtw OK, that's very weird. 

@TehPlayer14  We already use NVIDIA's recommended hack to get it to use the dedicated GPU if there are two.

**Comment by TehPlayer14** [comment]
Permission issues then perhaps try to run PPSSPP as administrator? or moving the folder somewhere else or erasing memstick

**Comment by unknownbrackets** [comment]
Does this still happen in the latest git and with the latest drivers?

-[Unknown]

**Comment by KatherineFtw** [comment]
Hold on, I'll try a fresh install.

>

**Comment by KatherineFtw** [comment]
No issue, auto sets to Vulkin without problem. Not even using latest Nvidia Drivers yet. Don't if if me having already fixed the issue affects this at all though.

**Comment by unknownbrackets** [comment]
Ah - we default to Vulkan now in 1.6.x, maybe that's just effectively worked around this problem.  But if it's a driver bug and it supports Vulkan anyway, that might be the best we can do.

-[Unknown]

**Comment by hrydgard** [comment]
I'm gonna close this, not clear what we can do...
