### ISSUE TITLE
Bug when click on save data on Vulkan API

### ISSUE THREAD

**Issue by zminhquanz** [hrydgard/ppsspp#10764]
What happens?
When I click on Patapon 2 save data , it's show error log . On Android , i'll crash when using Vulkan API , but on OpenGL , it's normal
![image](https://user-images.githubusercontent.com/11285640/37720107-23a9278c-2d59-11e8-90b7-1eb681746029.png)
When i'm click YES to continue
![image](https://user-images.githubusercontent.com/11285640/37720186-4dab5b40-2d59-11e8-9a79-3a9fe5ba8243.png)

**Comment by hrydgard** [comment]
That's an interesting one, thanks for reporting!

**Comment by leopard20** [comment]
You sure you're not loading a state that was saved on OpenGL? Because I've had numerous crashes when trying to do that! (vulkan and openGL states are not compatible I think)

**Comment by hrydgard** [comment]
They should be compatible.

**Comment by leopard20** [comment]
@zminhquanz 
Silly me! You said "crash on save state" not load state!

@hrydgard 
Really? I just assumed that since they use different codes and perhaps storing stuff (e.g textures) in memory by different names then a crash is justifiable. 
Maybe I should've reported it sooner!

**Comment by hrydgard** [comment]
huh, yeah, you should have :)  Can you reproduce any such fault consistently? I've never had problems loading saves across graphics backends.

**Comment by leopard20** [comment]
No, only in a few games. I don't use openGL anymore and those crashes I mentioned mostly happened when I had reinstalled the app (to switch builds) and the configs were reset because of the config overwrite issue I mentioned before.
I'll test more and get back with the results.

**Comment by Michal1324** [comment]
I've never had an issue with loading games on different backends including vulkan

**Comment by zminhquanz** [comment]
I'm going to the savadata manager UI , not load state , you got it

**Comment by hrydgard** [comment]
Seems it's actually two bugs. Fixed the Windows one, looking into Android now.

**Comment by unknownbrackets** [comment]
Ah, nice catch.

-[Unknown]

**Comment by zminhquanz** [comment]
@unknownbrackets you're welcome , because i'm developer
