### ISSUE TITLE
hello 

### ISSUE THREAD

**Issue by kokoalpha** [hrydgard/ppsspp#10761]
its just a small question 
pardon my ignorance but what is uwp doe's it effects the gaming performance on android 
and please sir is there a possibility to  increase ppsspp performance on opengl 
THANK U

**Comment by hrydgard** [comment]
UWP is Universal Windows Platform, that is, Windows Store "Apps" and Windows Phone. Has nothing to do with performance on android.

The next version has some pretty good performance improvements with OpenGL. Try early builds from https://buildbot.orphis.net/ppsspp/ .
