### ISSUE TITLE
Games look blurry at 1X resolution

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#10769]
What happens?
Every game is blury with 1x PSP resolution. Checked with PSP E-1004 where is same game Sharp! Android have only over few mm bigger screen. Nearest screen filtering not helped and anisotropic filtering not helped too! Maybe who have PSP can check it too.Of course you can set AGRESSIVE for lower resolution for effects but fot that you need set 2xPSP resolution but that very decreasing FPS

What *should* happen?
Set sharper screen

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

**Comment by hrydgard** [comment]
Sorry, this is an illusion created by the fact that the PSP is running at native resolution and thus gets exactly 1:1 "pixel-mapped" while we have to scale the image for your device.  Nothing we can do. 

If you insist that there's a difference, please prove it by taking photos and post them here for comparison.

**Comment by marosis** [comment]
https://photos.app.goo.gl/zHrzgYNog4Eux32w2   Here it is

**Comment by marosis** [comment]
If we (respective you) cannot do enything, i will close it

**Comment by Rokkest** [comment]
1x PSP + buffer render + natural shader little fix blury. but its hard on eyes. still use auto & native device

**Comment by marosis** [comment]
But please fix triangles glitches in toca race driver pls.(codemasters games)

**Comment by hrydgard** [comment]
Well I mean you should compare against a photo of your real PSP. Because it's not actually sharper.

Regarding toca race driver we have an attempt already in #9527. I might try to make that a "compatibility option" soon...

**Comment by jonasbantunes** [comment]
I think @marosis is trying to say that PPSSPP upscaling (from 1xPSP)  is using some form of linear filtering. Some images for comparison on my Android phone (If necessary, I can send more information about my device and apps):

PPSSPP standalone (1xPSP rendering resolution, native HW Scaler): https://i.imgur.com/nlGum0e.png
Retroarch PPSSPP core (1xPSP rendering resolution, linear filtering disabled on Retroarch Video settings): https://i.imgur.com/vAVu12o.png

It would be cool to have a "nearest upscaling" on PPSSPP standalone (apk). The Retroarch PPSSPP core on Android still is on version 1.5.4.

**Comment by hrydgard** [comment]
But that is supported. Just set it to render at 1x, set Screen Scaling Filter to Nearest, and set the hw scaler to 2x or 3x for a clean look.

**Comment by jonasbantunes** [comment]
Oh that's right. This options works like a charm. Thanks :smile:

**Comment by Unknow0059** [comment]
> But that is supported. Just set it to render at 1x, set Screen Scaling Filter to Nearest, and **set the hw scaler to 2x or 3x** for a clean look. I do admit that the Screen Scaling Filter is miscategorized under the Texture Scaling section.

Where can I find that option on PC?

**Comment by Unknow0059** [comment]
@jonasbantunes 
> But that is supported. Just set it to render at 1x, set Screen Scaling Filter to Nearest, and **set the hw scaler to 2x or 3x** for a clean look. I do admit that the Screen Scaling Filter is miscategorized under the Texture Scaling section.

Where can I find that option on PC?

**Comment by Unknow0059** [comment]
@hrydgard 
> But that is supported. Just set it to render at 1x, set Screen Scaling Filter to Nearest, and **set the hw scaler to 2x or 3x** for a clean look. I do admit that the Screen Scaling Filter is miscategorized under the Texture Scaling section.

Where can I find that option on PC?
