### ISSUE TITLE
[Feature Request] Add Screenshot Button on Android

### ISSUE THREAD

**Issue by TediExcaliber** [hrydgard/ppsspp#10762]
Good day sir.

Can you make screenshot button feature on Android?

A touch button or a mapping button (like speed toggle) to take screenshot instantly?

On some phone is little hard to take a good screenshot because some problem like slow taking picture or something, I know this can be handle with using toggle speed button or use savestate with buffered rendering, but I think it will make more easy to take screenshot on Android.

**Comment by Endarko** [comment]
@hrydgard , please add

**Comment by unknownbrackets** [comment]
It is now possible to assign a controller button or similar (maybe volume up/down) to screenshot.  It's not possible to require a combination of buttons or to use a touch button currently.

-[Unknown]

**Comment by TediExcaliber** [comment]
Ah, I see, sorry long time didn't open this web
