### ISSUE TITLE
[Feature Request] Less blurry Natural Colors PP shader

### ISSUE THREAD

**Issue by leopard20** [hrydgard/ppsspp#10766]
The Natural Colors Postprocessing shader is awesome, but it's a bit too blurry. Do you think you could tweak it a little to be better? The FXAA level of blurriness is just fine IMO.

**Comment by hrydgard** [comment]
pull requests accepted :)

**Comment by leopard20** [comment]
Would've done that if I knew how!

**Comment by leopard20** [comment]
How can I compile the .apk from source code without Android Studio (like an online buildbot or something)?
