### ISSUE TITLE
[Android] Audio lag after connecting headphones mid-game

### ISSUE THREAD

**Issue by leopard20** [hrydgard/ppsspp#10772]
I'm not sure if it's PPSSPP's fault, but when I connect my headphones mid-game I get a weird audio lag (like 1+ seconds). But after closing PPSSPP and starting it again the problem's gone.
Can someone test this please to see if it happens for you too or not?
Device: Xiaomi Mi 5s Plus

**Comment by hrydgard** [comment]
Sounds like a platform problem, not sure there's all that much we can do about it...

**Comment by leopard20** [comment]
You mean you didn't encounter this on your phone right? Then I guess you can close this.

**Comment by hrydgard** [comment]
Bluetooth headphones? Don't have any :)

**Comment by leopard20** [comment]
No, wired ones!

**Comment by hrydgard** [comment]
what. that's weird..

**Comment by Michal1324** [comment]
@leopard20 What Android version you are running?

**Comment by leopard20** [comment]
7.0
If you guys don't get the same problem then I can just close this. It's not a big problem after all (a simple restart fixes it)

**Comment by unknownbrackets** [comment]
Doesn't happen on a Pixel at least, but I'm running Android 8.1.0.

-[Unknown]

**Comment by hrydgard** [comment]
@leopard20  Not gonna prioritize it, but if it's a problem, it's problem, so we'll leave it open. More details could be useful in future investigation, please add some details about what device you have this problem on.

**Comment by Michal1324** [comment]
I will also try swapping the audio on the fly and I will see what happens

**Comment by leopard20** [comment]
Found out it wasn't PPSSPP's fault, but because of an app that suddenly started in the background as soon as I connected the headphones. Sorry for the false report. 😥
