### ISSUE TITLE
Gradius Collection problems

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#10778]
All Games Except Gradius 4 Freezes and only Hear Sound

Gradius 4 Works Great

**Comment by unknownbrackets** [comment]
Did they work in some previous version?  What device is this, and have you tried on other devices?

Are you using the latest git build?

-[Unknown]

**Comment by Panderner** [comment]
Thanks unknown to updating git build

**Comment by unknownbrackets** [comment]
Does that mean it works in the latest git build?

-[Unknown]

**Comment by Panderner** [comment]
Yes

**Comment by unknownbrackets** [comment]
Great, glad to hear it's fixed.  Thanks for reporting.

-[Unknown]
