### ISSUE TITLE
CANT HIT/HOLD TRIPLE CONTROLS [STICK ON ARM]

### ISSUE THREAD

**Issue by Rokkest** [hrydgard/ppsspp#10771]
Its hard when try to combo on PES / another game

try hold R + X and analog freezz/ change auto to right/left

combo set is not solution cos its fine on my another hh[x86]

**Comment by Michal1324** [comment]
Please provide more info like

Device, operating system of device, PPSSPP version

without that we can't help you

**Comment by leopard20** [comment]
I don't think it has anything to do with the device.

Controls get stuck on my device too when I hold three or more buttons together. 

But it's weird that @Rokkest says he can't use combos because they work fine for me.

**Comment by leopard20** [comment]
I'm not a noob and I know about this stuff. I have a high-end android device. And yes it supports up to 10 touch points. 

But there is a chance it's ROM-related.

**Comment by leopard20** [comment]
![20180323_210315](https://user-images.githubusercontent.com/16115820/37841895-6129f772-2ede-11e8-9ec3-8c11fb8d2e91.gif)

**Comment by Michal1324** [comment]
I checked out quickly on my Xperia I can press 3 buttons at once (I was playing Platypus)

**Comment by leopard20** [comment]
Did you try R+X+Stick like me?

**Comment by Michal1324** [comment]
Yeah I was holding down R trigger X stick and L as well

**Comment by leopard20** [comment]
That's really weird. So maybe I was right. Maybe it's ROM related.

**Comment by Michal1324** [comment]
Try to use the debug menu to show touch points in Android's debug menu and try again if it shows on screen as a dot and its not pressed then its PPSSPP fault

**Comment by leopard20** [comment]
You mean enabling Show Touch Points from Developer Options in my settings or PPSSPP debug menu?

**Comment by Michal1324** [comment]
The Develpoer options in android

**Comment by leopard20** [comment]
Never mind I figured out what was the culprit! It was indeed because of my ROM!

I use a custom ROM (Xiaomi's MIUI) which has an option in the settings for using three-finger swipe for taking screenshots. After disabling that option problem's solved!

**Comment by LunaMoo** [comment]
Quite frankly screenshots showing pressed/not pressed keys are useless and not a proof of anything other than player pressing/not pressing selected keys. The screenshot included here does however show tightly packed keys overlapping each other even without them being pressed which due to enlarge makes it even worse and that possibly could be causing some weird problems/unplanned situation.

 I don't have any issues on my phone with default button layout(and default settings in general), R+X+analog or whatever everything works fine, through I would never actually want to nor recommend anyone I like to play PSP games using touch screen.;p

**Comment by Michal1324** [comment]
Just as Luna said better get yourself something to play on like a gamepad or even a keyboard

**Comment by leopard20** [comment]
Perhaps you guys didn't see my above comment. Like I said, it was because of my ROM and I fixed it. So no worries here! 😋

**Comment by hrydgard** [comment]
Gonna close, it's likely the same - and either way it's hard to do anything about it, if the touchscreen reports wrong events then we're screwed... As long as we get proper touch events, our buttons do work.
