### ISSUE TITLE
Using Android 7's split window will crash ppsspp 

### ISSUE THREAD

**Issue by TehPlayer14** [hrydgard/ppsspp#10779]
When changing the active Window for example from PPSSPP to YouTube and back to PPSSPP it will crash

**Comment by hrydgard** [comment]
Vulkan or OpenGL?

**Comment by TheComputerGuy96** [comment]
@hrydgard OpenGL

**Comment by TehPlayer14** [comment]
Vulkan it seems I hadn't any success with OpenGL in terms of crashing

**Comment by SamueldeSena** [comment]
Vulkan has some issues to be solved for example if I am playing in ppsspp by Villa and someone calls me if I understand the connection my cell phone reboots or if I am playing and block the screen with the emulator in the foreground the cell phone reboots

**Comment by hrydgard** [comment]
There are problems with the screen rotation check (a workaround for a platform bug) when you resize the window in certain ways. I'll look into it soon, though is there really a point to playing PPSSPP on half the screen?

**Comment by TheComputerGuy96** [comment]
@hrydgard Yes (at least on a tablet)

**Comment by TehPlayer14** [comment]
@hrydgard There's probably few reasons can't think of right now but it would prove as a nice utility when you don't have to switch between windows manually to see something update in 2nd window

**Comment by hrydgard** [comment]
Yeah, I'll get it fixed, just wondering :)

**Comment by hrydgard** [comment]
Should work better now, let me know.

**Comment by unknownbrackets** [comment]
Well, I think a feature request (which makes a lot of sense, esp. when using an external controller on a tablet) for an option to pause/no pause during split screen is a separate issue.  As long as it doesn't crash, better to release v1.6.0.

I found a crash while testing this, but it's also a separate bug.

Going to close this though.

-[Unknown]
