### ISSUE TITLE
haptic feedback (vibration) doesn't work

### ISSUE THREAD

**Issue by ultrasuper19** [hrydgard/ppsspp#10786]
What happens?
Well,i tested it on other device like asus,samsung,etc.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
I'm using Xiaomi Redmi 3S with Snapdragon,GPU adreno 505,and I'm using ppsspp 1.5.4 from the latest build

**Comment by weihuoya** [comment]
did you enabled feedback in system settings? 
s7 edge has vibrate feedback

**Comment by ultrasuper19** [comment]
Yes i enabled it, and the weird is when i use other emulator,the vibration worked fine

**Comment by hrydgard** [comment]
Huh. It seems that behaviour has possibly changed in newer Android versions. What I see now on 8.1 is that it works when the global setting. Android Settings / Sounds / Advanced / Vibrate on Tap is on, but it doesn't if it's off.

I can work around it like this in NativeActivity.java:

```surfView.performHapticFeedback(HapticFeedbackConstants.VIRTUAL_KEY, HapticFeedbackConstants.FLAG_IGNORE_GLOBAL_SETTING);```

Which means that people who have disabled haptic feedback globally will still get haptic feedback in PPSSPP, which might be desired? I'm not sure we should still have it on by default though.

**Comment by leopard20** [comment]
Agreed. Disable it by default but make it independent of phone settings.
