### ISSUE TITLE
Tekken 6 blackscreen after starting the game

### ISSUE THREAD

**Issue by ultrasuper19** [hrydgard/ppsspp#10787]
What happens?
This problem does not occurred in previous version,but when i download ppsspp from the latest build,it became blackscreen

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Xiaomi Redmi 3S
Snapdragon 430
Adreno 505
1.4 Ghz

**Comment by marosis** [comment]
Try you to set emulate clocks to 222MHZ

**Comment by ultrasuper19** [comment]
Well it worked,thanks

**Comment by Jinzombie** [comment]
@ultrasuper19 Try to use this cheat code its fix the blackscreen issue even if you set the emulated cpu clockspeed in any value except 222MHz :)

_C0 Custom CPU speed freeze [Fixed]
_L 0xE0030004 0x001C6094
_L 0x201C6094 0x00000000
_L 0x201CFC28 0x00000000
_L 0x201CFE74 0x00000000
