### ISSUE TITLE
[Android] Texture hashing method changed since v1.5.4 - Custom Textures don't work

### ISSUE THREAD

**Issue by leopard20** [hrydgard/ppsspp#10796]
What happens?
Apparently you've made some changes to the hashing method since v1.5.4, which means custom textures don't work anymore and need to be renamed.
For example, these textures are from The 3rd Birthday.
**Saved via v1.5.4:**
![screenshot_2018-03-25-18-14-39-481_com estrongs android pop](https://user-images.githubusercontent.com/16115820/37875747-aee45afe-3058-11e8-8d04-12f94f1c7479.png)

**Saved via v1.5.4-760:**
![screenshot_2018-03-25-18-14-26-893_com estrongs android pop](https://user-images.githubusercontent.com/16115820/37875758-d1723dc0-3058-11e8-92fd-c382e146b70b.png)

They only differ in the last 8 characters.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Android 7.0
CPU Architecture:Qualcomm Kryo - ARMv8a (64 bit)

**Comment by hrydgard** [comment]
If you compare the hashes to those from a PC/Windows build, which match?

**Comment by TehPlayer14** [comment]
So can't we just make a converter if they are equally offset?

**Comment by hrydgard** [comment]
Absolutely not, we need to fix whatever bug changed the hashes.

**Comment by MorrisonGamer** [comment]
I can confirm the latest PPSSPP build and a few more further older ones, texture replacement didn't work for android on my phone, tested with my Birth by Sleep HD ReMix pack.

**Comment by hrydgard** [comment]
Right, so what we need is to find out the very last build where it did work. Apparently it does work in 1.5.4, so it's just a matter of trying builds in between...

**Comment by leopard20** [comment]
@hrydgard
Build 209 works but 480 doesn't. I'll see if I can narrow it down any further.

**Comment by leopard20** [comment]
This is as close as I could get:
Build 211 works but 246 doesn't. 
Some builds between these couldn't even run the game so I got fed up!😩

**Comment by unknownbrackets** [comment]
That range would imply the arm64jit improvements, I guess?  But the texture hash shouldn't use jit, so unless those changes messed up arm64 global state or wrote the memory wrong...

https://github.com/hrydgard/ppsspp/compare/v1.5.4-211-gc948a3df0...v1.5.4-246-geb35e8828

-[Unknown]

**Comment by hrydgard** [comment]
@leopard20 , one more thing to test - go into settings/tools/developer options and change CPU Core to IR Interpreter or Interpreter. Does that make a difference?

**Comment by leopard20** [comment]
@hrydgard 
Good news! Build 235 also works. That's as as narrow as it gets!

**Comment by hrydgard** [comment]
Wow, ok, thanks for confirming. @unknownbrackets seems indeed so, but what state could have changed? I can't find any uninitialized variables in the hashing code, and it doesn't use floating point so it's not rounding mode or something...

**Comment by leopard20** [comment]
One more thing that I noticed is that build 235 sometimes works and sometimes doesn't (JIT).

**Comment by hrydgard** [comment]
Does it depend on the game whether it works or not or does it seem completely random?

**Comment by leopard20** [comment]
I only tested the 3rd Birthday like before. Do you want me to test more games?

**Comment by leopard20** [comment]
Apparently the hashes changes randomly every time I restart PPSSPP. Once it works (no matter how many times I restart the game), but once I restart PPSSPP it doesn't!

**Comment by leopard20** [comment]
Any idea why this happens? (first time custom textures don't work, but works next time)
[20180326_150523.mp4.zip](https://github.com/hrydgard/ppsspp/files/1847450/20180326_150523.mp4.zip)

**Comment by leopard20** [comment]
Ok that's definitely weird. I also noticed a similar behavior in the latest build. Sometimes the textures don't work but if I close the game and start it again (sometimes a couple of times) it works!

**Comment by leopard20** [comment]
@hrydgard @unknownbrackets 
Please hold off on making any changes for now. Apparently the patterns have been random. I'll test more builds before 211 to see when it happened.

**Comment by hrydgard** [comment]
OK, thanks for your testing work :)

**Comment by leopard20** [comment]
@hrydgard 
Build 34, has the same patterns!
Total shot in the dark, but could it be because of this commit (build 25):

> Vulkan: Add facility to auto-generate mipmap levels. Not yet used. Intended for replacement textures and optional quality improvements later.

**Comment by hrydgard** [comment]
Seems highly unlikely.

**Comment by leopard20** [comment]
Do you see any change before build 34 that could've caused this?

**Comment by leopard20** [comment]
@hrydgard 
Build 19 works too.

**Comment by leopard20** [comment]
https://github.com/hrydgard/ppsspp/compare/v1.5.4-19-gcf5ede493...v1.5.4-34-g253bba28d

**Comment by hrydgard** [comment]
I sure hope it's not https://github.com/hrydgard/ppsspp/commit/253bba28d85696260eef01c9f2b55161dbd5687b  ... that would indicate possibly a compiler bug.

**Comment by leopard20** [comment]
Seems like it could be 34 because build 30 works!

**Comment by leopard20** [comment]
@hrydgard Ok good news (I hope!). Build 33 doesn't work either!

**Comment by leopard20** [comment]
https://github.com/hrydgard/ppsspp/compare/v1.5.4-30-g3eda31000...v1.5.4-33-gc268e3781

**Comment by hrydgard** [comment]
Well it's different but also annoying :) Somehow switching to a different STL implementation caused this, and not a bug in our code - or a bug that manifests itself differently :P   Might be tricky to figure out..

**Comment by leopard20** [comment]
One thing I don't get is why is it such a big deal?! (sorry if this question seems stupid! 😉)

**Comment by hrydgard** [comment]
The annoying thing is that it broke when we updated external libraries. If the problem had started with a change in our code, we would know exactly where to start looking, but in this case, it's much harder...

**Comment by leopard20** [comment]
No I meant why this entire issue is a big deal! Because textures render correctly in the game and for the custom texture issue we can always rename them.

**Comment by hrydgard** [comment]
Programmers get uneasy when code misbehaves! Also, having to rename textures specifically for android - and only sometimes! - is not a good user experience.

**Comment by TehPlayer14** [comment]
Perhaps there another way of replacing textures that wouldn't cause so much trouble at cost of computing power

**Comment by leopard20** [comment]
@hrydgard
By the way, IR Interpretor doesn't work either (it worked because of the same random pattern)

**Comment by hrydgard** [comment]
Oh! Well that's important info. That means it might not have anything to do with the JIT.

**Comment by leopard20** [comment]
@hrydgard 
Congrats! Issue is fixed!

**Comment by leopard20** [comment]
It certainly fixes The 3rd Birthday.
But for some games the textures are saved with different names.

**Comment by leopard20** [comment]
This is from Flatout:
**v1.5.4:**
![screenshot_2018-03-26-22-47-53-528_com estrongs android pop](https://user-images.githubusercontent.com/16115820/37924691-d5881e80-3147-11e8-9e4c-2069789669a2.png)
**v1.5.4-773:**
![screenshot_2018-03-26-22-47-48-839_com estrongs android pop](https://user-images.githubusercontent.com/16115820/37924708-e3c1febc-3147-11e8-8d00-7037734cd41e.png)

**Comment by leopard20** [comment]
It looks like the only game that's fixed is the 3rd Birthday.

**Comment by leopard20** [comment]
@hrydgard 
Seems like the random pattern also occurs on Windows! This is really weird!
If it was because of Android STL, then this wouldn't happen on Windows right?!

**Comment by hrydgard** [comment]
Definitely not. This is quite mysterious...

**Comment by unknownbrackets** [comment]
What hash mode are you using in these inis?  Does this happen even without an ini, or only when there is an ini?

Does anything change if you force the size of a particular texture (use its address) to a certain w/h via hashrange?

On Windows, when this happens, are you sure they're not just different textures?  Remember that PSP games specify textures using powers of 2.  If a texture contains garbage at the end (this is frequent), then it may appear using multiple hashes - PPSSPP can't be sure what area of the texture will really be used.

-[Unknown]

**Comment by leopard20** [comment]
If by inis you're referring to the configs, I tried deleting my configs but didn't make any difference.

I don't understand what the rest means! Just tell me what to do (in simpler words!).

**Comment by unknownbrackets** [comment]
When you create replacements, you can optionally create a textures.ini file in that directory and change settings for replacements.  Are you using that, or is all of this without any such ini files?

Actually, it looks like the reduceHash_ thing was unintialized in 1.5.4, so it was probably always on in older versions.  So the hashes in v1.5.4 were somewhat random or otherwise wrong.

-[Unknown]

**Comment by leopard20** [comment]
Nope, not using inis.

**Comment by leopard20** [comment]
@unknownbrackets 
1. Yes
2. Yes
3. Yes

I also compared v1.4.2 and the latest git. Turns out you were completely right (they are both compatible). It was v1.5.4 that created different hashes.
But to clear one thing up, the randomness was aggravated after v1.5.4-34 (it created different hashes every time you restarted a game) and later fixed by @hrydgard 's commit (a few comments above)

I guess you can close this then.

**Comment by hrydgard** [comment]
Alright, yeah. Unfortunate with the bug in 1.5.4, but not much we can do about it now.
