### ISSUE TITLE
The new shader(naturalA) 

### ISSUE THREAD

**Issue by abdellahking** [hrydgard/ppsspp#10793]
So this is not an issue but just ask : the new shader(naturalA) suppose to do this to games

![screenshot_20180325-141738](https://user-images.githubusercontent.com/36864704/37875729-30a42268-303b-11e8-969d-adcbcba29b43.png)
![screenshot_20180325-143121](https://user-images.githubusercontent.com/36864704/37875751-64e09408-303b-11e8-9f17-d944da8a85b1.png)

But the Call of duty :rtv
Didn't do like this ahe work perfectly

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Mali t720 quad core
Android 6.0
OPENGL

**Comment by leopard20** [comment]
That's weird. I tested most games with this shader and they work ok (GoW, GTA, Assassin's Creed, Flatout, Burnout, NFS, Project Diva Extend, Def Jam, PoP)

**Comment by marosis** [comment]
Yes i have same problem and it's more blury  than when i don't have eyeglasses https://photos.app.goo.gl/QMpiZlSuMmmVR2cq2

**Comment by abdellahking** [comment]
Hmmm. Thats wierd maybe the problem on my device?

**Comment by marosis** [comment]
Leopard20 yes?! And did you tried latest version?https://photos.app.goo.gl/iI17zOd8JgXlCe7g1

**Comment by marosis** [comment]
Flatout have same problem

**Comment by leopard20** [comment]
@marosis I guess you're using the Natural Colors shader!

@abdellahking No, like I said it happens with openGl.

BTW guys, this new shader is called Natural Colors (No Blur), if you still see it as NaturalA you can update your PPSSPP to fix it.

**Comment by leopard20** [comment]
More screenshots:
On Vulkan:
![screenshot_2018-03-25-18-51-37-543_org ppsspp ppsspp](https://user-images.githubusercontent.com/16115820/37876176-14d79e84-305e-11e8-824a-4af4f9ae799c.png)

![screenshot_2018-03-25-18-53-42-074_org ppsspp ppsspp](https://user-images.githubusercontent.com/16115820/37876185-293ace6e-305e-11e8-8bc4-4b52f4a8105a.png)

OpenGL:
![screenshot_2018-03-25-18-52-34-496_org ppsspp ppsspp](https://user-images.githubusercontent.com/16115820/37876194-3e8a69dc-305e-11e8-8633-1152bdebb483.png)

![screenshot_2018-03-25-18-52-53-097_org ppsspp ppsspp](https://user-images.githubusercontent.com/16115820/37876200-540ca446-305e-11e8-87ef-2e5499c057ba.png)

**Comment by leopard20** [comment]
@hrydgard
Any idea why this happens?

**Comment by hrydgard** [comment]
My guess is that some of the math goes wrong and ends up at infinity (1/0) or NaN or something .. don't feel like debugging your shader right now

**Comment by LunaMoo** [comment]
Issues like that are usually:
 - incorrect syntax(vendors are often interpretating common mistakes coming from lazy programming, but not all vendors does that, sometimes even if they do, interpretation can differ, that's common problem for example in games ported from consoles when devs are only using Nvidia or AMD hardware during porting significantly breaking the other vendor and not even trying to support intel),
 - complexity(some mobile gpu's have silly limits and can't compile complex shaders properly),
 - driver bugs,
 - silly mistakes.

 The only thing I see which could be bad is that the shader doesn't output alpha which might set it to 0 resulting in black?

**Comment by leopard20** [comment]
Could be. Let me see if I can find the culprit.

**Comment by LunaMoo** [comment]
I already pushed potential fix.

**Comment by leopard20** [comment]
Didn't work unfortunately.

**Comment by marosis** [comment]
Can i ask, how leopard20 are you did, i can see pictures without link?

**Comment by leopard20** [comment]
You mean how pictures are visible on GitHub directly?
That's because I uploaded them here. 
If you're on mobile, go to the bottom of the page and select Desktop Version. Then when you want to comment there's a blue text at the bottom of the textbox that says "selecting them". Click on it. Pick your files, wait for them to upload, and voila!

**Comment by marosis** [comment]
THX
