### ISSUE TITLE
Opengl ES vertex count limit

### ISSUE THREAD

**Issue by weihuoya** [hrydgard/ppsspp#10794]
I find there is a vertex count limit for mobile in DrawEngineGLES.cpp
```c++
void DrawEngineGLES::DoFlush() {

		// TODO: Split up into multiple draw calls for GLES 2.0 where you can't guarantee support for more than 0x10000 verts.
#if defined(MOBILE_DEVICE)
		if (vertexCount > 0x10000 / 3)
			vertexCount = 0x10000 / 3;
#endif

}
```

is safe increase to 0xFFFF for nowaday mobile device? it is a resonable performance gain.
```c++
void DrawEngineGLES::DoFlush() {

#if defined(MOBILE_DEVICE)
		if (vertexCount > 0xFFFF)
			vertexCount = 0xFFFF;
#endif

}
```

**Comment by hrydgard** [comment]
Lots of older drivers have problems with that and no games ever make such large draw calls anyway, the only use of this is running "sprite.elf" from the pspsdk. There is no way that changing this gives you a performance gain, you must be measuring something else like maybe once the device was hot and downclocked itself.
