### ISSUE TITLE
FireTV 3rd Gen 4K - Storage Permissions Denied

### ISSUE THREAD

**Issue by ppsspp213** [hrydgard/ppsspp#10807]
Read / Write storage permissions denied on 
Amazon FireTV 3rd Gen 
I've tried changing the permission but it just makes a blocked bleeping sound.
I don't know how it works but https://www.amazon.co.uk/AFTVnews-com-Downloader/dp/B01N0BP507 
has access to dl files and delete them also, maybe cause it's signed with a key authorised by Amazon???
I believe the Amazon Fire OS installed is based off Android 7.1

**Comment by unknownbrackets** [comment]
Does this happen both in v1.5.4 and in the latest git build?

-[Unknown]

**Comment by ppsspp213** [comment]
I could only test v1.5.4, the dev build links won't dl, the aftnews
downloader app doesn't seem to be able decipher them are they mirrored
anywhere else for dl???

**Comment by ppsspp213** [comment]
https://developer.amazon.com/blogs/appstore/post/2ef7b757-557e-4464-b4e8-a6cf67ccb598/managing-app-permissions-with-fire-tv-gen-3

of any use?

**Comment by ppsspp213** [comment]
Ok I just downloaded v1.5.4-795 using

http://build.ppsspp.org/builds/Android/ppssppbuildbot-org.ppsspp.ppsspp-dev-latest-android.apk

It popped up with a message asking me to grant access for photo storage
which I did, all seems ok.

I don't yet have a bluetooth controller to test it further with though
atm it's just recognises the d-pad circle as input, the middle confirmation
button doesn't work so I can't enter settings to re-map the over four
usasable buttons
options,
play/pause,
rewind,
fastforward
buttons of the FireTV remote, the back and Home buttons can't be used since
there used to just exit the app.

**Comment by unknownbrackets** [comment]
Sounds like asking immediately in #10781 helped this, then - FYI @hrydgard.

I'm not sure about the button mapping, but that probably belongs in a separate issue.  We should ideally recognize the confirmation button by default - although it sounds like this will never be able to provide a full controller experience.

I'm going to close this given that the storage permission is working now, but if I've misunderstood feel free to comment and we'll reopen.

-[Unknown]

**Comment by doodie** [comment]
@ppsspp213 i have an app that i installed on a gen3 4k firestick and not able to change the permissions for the app on storage. did you ever figure that out? does it make a difference on how you install the apk? i installed through ES file explorer

**Comment by ppsspp213** [comment]
Slight update to this, I got my DS4 working by USB with an OTG adapter.
It’ll work to power the Amazon device and controller fine but if you plug
another adapter into in dual I don’t think it supplies enough power for USB
sticks that contain led lights, without the controller plugged in, ES File
Explorer was able to see it’s contents, I need to try it with a USB stick
without leds drawing more power.

**Comment by ppsspp213** [comment]
As to your question, I think the app specifically needs the request
permission from the app it’s self, changing the permissions in settings of
Amazon device is locked out. I don’t think anyone has managed to Root it
yet or the 2018 Fire Tablets ☹️

**Comment by doodie** [comment]
thanks for the reply. waiting for Root...

**Comment by ppsspp213** [comment]
> 
> 
> thanks for the reply. waiting for Root...

You can decompile & recompile .APKs with various tools at the xdadevelopers forum, 
the format isn't too compilated it's more or less just a renamed .zip file.
They'll be more versed in which source files you'd need to edit to add the permission request though, iirc the needed permissions set are listed in part of the manifest file.   
These are the otg adaptor type you need, so you gain extra ports to split out the usb power input
https://www.amazon.co.uk/gp/product/B078J57HZ3/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1 Like I said it doesn't really supply enough power to use more than device at once, which is probably why it isn't officially supported.

**Comment by doodie** [comment]
Thanks. So i spent more time yesterday and made some progress. The app does ask for permission to access storage, but the dialogue box is distorted and does not show properly on my tv. tried all options from my tv and firestick. I got it working previously on another firestick and dont recall having this much issue. will check out  xdadevelopers forum for some decompile & recompile options. unzipped and poked around but had no clue. Was hoping to edit xml files but they were not readable.
