### ISSUE TITLE
Strange OpenGL behavior across platforms

### ISSUE THREAD

**Issue by leopard20** [hrydgard/ppsspp#10800]
What happens?
I noticed that openGL behaves quite differently than other backends.
First there's this issue on OpenGL ES: 
https://github.com/hrydgard/ppsspp/issues/10793
Then I discovered that the Natural Color shader (older one) doesn't have the blur effect on OpenGL! 

What do you guys think? Is it normal?

What *should* happen?
All shaders should look the same on all backends.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Windows 8.1 64 bit - 64 bit CPU intel Core i7 - Nvidia GPU
Android 7.0 and 6.0 - Adreno and Mali GPU.

**Comment by unknownbrackets** [comment]
OpenGL and OpenGL ES are actually different.  Similar in a way to how the Tesla Semi is different from a Tesla Model 3.

Modern versions of OpenGL often have all the features of OpenGL ES and then some.  For older versions of OpenGL, this wasn't true - they lacked features that OpenGL ES had (OpenGL ES also lacked features of OpenGL.)

Anyway, this could just have been that the old shader was failing to compile correctly, or a difference in resolution settings.

If the shader is compiling properly, then differences are either bugs in the shader code (using features not fully supported) or driver bugs (which are not at all uncommon.)

-[Unknown]
