### ISSUE TITLE
PPSSPP crashes when selecting |Networking| in Settings

### ISSUE THREAD

**Issue by MorrisonGamer** [hrydgard/ppsspp#10802]
Here is a screenshot of how it happens, and which version this happens. This problem occurs in ANY game.
https://i.imgur.com/aT9wNpc.png

I have no idea where exactly this problem appeared, but I've had no problems at ver. 1.5.4.712

This happens with ANY game.

Here's the config files for troubleshooting if necessary: https://dl.dropboxusercontent.com/s/4yl62dwgetmdm1y/SYSTEM.7z

EDIT: If this is a problem with...game config files again...I really think there should be some way to workaround around those, maybe separate the NETWORKING settings from everything, or just separate it between games, and only apply the game's NETWORKING settings, and never consider the general NETWORKING settings.

**Comment by hrydgard** [comment]
No, this is just a screwup on my part when I fixed the postshader UI issues. I'll fix it right away, stay tuned
