### ISSUE TITLE
Samuraidou portable ULJS00155 main character's face distorted

### ISSUE THREAD

**Issue by lim2222** [hrydgard/ppsspp#10803]
What happens?

Main character's face alignment seem has problem,both vulkan and gl backend tried nothing fixed

What *should* happen?
![samuraidou](https://user-images.githubusercontent.com/35925370/37882670-5ee44e14-30e0-11e8-8dd9-f4be51503bcb.jpg)
![screenshot_20180326-085342](https://user-images.githubusercontent.com/35925370/37882683-81a5d328-30e0-11e8-86bf-e8e26016b223.jpg)
![screenshot_20180326-085351](https://user-images.githubusercontent.com/35925370/37882684-81ddf2d0-30e0-11e8-8a93-526847821c14.jpg)
![screenshot_20180326-085402](https://user-images.githubusercontent.com/35925370/37882686-82184b56-30e0-11e8-9388-1ca4040d7fdf.jpg)
![screenshot_20180326-085418](https://user-images.githubusercontent.com/35925370/37882687-82537b22-30e0-11e8-84e1-503fff705d8b.jpg)

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
ppsspp v1.5.4-772-gf39897cfa
oneplus 5 android 7.1.1 snapdragon 835 adreno 540
windows 10
Intel i5-5200U
Nvidia geforce 920m

**Comment by unknownbrackets** [comment]
Does it work in an older version of PPSSPP?  Like 1.5.4, 1.4.2, etc.?  If yes, is it possible to find which git build first broke it?

Sounds like it happens on Android and on Windows - right?

Poor guy got punched really hard in the face.

-[Unknown]

**Comment by lim2222** [comment]
Just tried older version v1.0.1 android the problem still there,seem this problem have not been fixed before.

**Comment by unknownbrackets** [comment]
Interesting - thanks for checking.

It seems like he's being drawn twice, really.  Even the arms are doubled up.  I wonder if it's even some sort of depth issue.

Could you try exporting a GE debugger dump on PC?

To do this, open the game and select Debug -> GE debugger..., then when it's displaying the scene, press Record in the top right.  After a second or so, it'll finish and save a trace of the drawing activity.

After that, check the memstick/PSP/SYSTEM/DUMP folder and it'll have created a file named something like "ULES12345_0000.ppdmp".  You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by lim2222** [comment]
[DUMP.zip](https://github.com/hrydgard/ppsspp/files/1846119/DUMP.zip)
Do record couple of files don't know whether right or not

**Comment by lim2222** [comment]
PSP screenshot
![201103040412_001](https://user-images.githubusercontent.com/35925370/37892619-59bb396a-3113-11e8-99f4-cbcdc5796574.jpg)
![201103040415_001](https://user-images.githubusercontent.com/35925370/37892620-5a01ef2c-3113-11e8-9ac1-39694a7485bf.jpg)

PS VITA screenshot
![img_20180326_152427](https://user-images.githubusercontent.com/35925370/37892856-3a9efe62-3114-11e8-9775-ce938b1d3c3d.jpg)

May be this is bugs of game itself,screenshot from psp and ps vita also looks face distorted,ppsspp with  HD resolution make it more obvious.

**Comment by LunaMoo** [comment]
Closing as a non-emulation issue.
 Problems like that which also happen on real hardware(PSP screenshots matter, not PSV ones since it also emulates PSP and actually often has similar problems to PPSSPP) can at most be fixed by modding the game itself, not by emulation.
