### ISSUE TITLE
Missing graphics in WipEout® Pulse (UCES00465) OpenGL

### ISSUE THREAD

**Issue by Peduls** [hrydgard/ppsspp#10810]
![d3d](https://user-images.githubusercontent.com/34750422/37925501-f4d1c030-30f1-11e8-86a2-d51bafd07d34.PNG)
![opengl](https://user-images.githubusercontent.com/34750422/37925523-00c38220-30f2-11e8-987f-a2e26e385ecc.PNG)

What happens?
The "3...2...1...GO!" is missing from the sign above the finish line along with many other graphics on the signage along the tracks in OpenGL but look fine in D3D.

What *should* happen?
Older versions of PPSSPP displayed these graphics correctly in OpenGL.
I'm currently downloading older versions to pinpoint which build the issue was first observed in.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Operating System
	Windows 10 Enterprise 2016 LTSB 64-bit
CPU
	Intel Core i7 4790K @ 4.00GHz
	Haswell 22nm Technology
RAM
	16.0GB Dual-Channel DDR3 @ 799MHz (11-11-11-28)
Motherboard
	ASUSTeK COMPUTER INC. Z97-A (SOCKET 1150)
Graphics
	Acer S231HL (1920x1080@60Hz)
	R240HY (1920x1080@60Hz)
	4095MB NVIDIA GeForce GTX 1070 (EVGA)
Storage
	465GB Samsung SSD 850 EVO 500GB (SSD)
	2794GB TOSHIBA HDWD130 (SATA)
Optical Drives
	ASUS DRW-24B1ST j
Audio
	High Definition Audio Device

**Comment by hrydgard** [comment]
Hm, indeed. Might be since the threading rewrite, not sure. Works in Vulkan too.

**Comment by marosis** [comment]
Do you have on buffered rendering? This game i tried few months ago and with non-buffered rendering was same problem (what can be normal) try off hardware transforming( with offed hw transforming i've fixed some problems sometimes)

**Comment by marosis** [comment]
Btw This problem wasn't in version 1.4

**Comment by hrydgard** [comment]
OK, found what's happening, though not quite the cause yet. It uses UV coordinates outside the [0..1] box relying on wrapping, and for some reason texture sampling is set to clamp, so we just get the border of the texture filling up the sign, which is green when GO shows up. The texture is a render target. 

Will debug in detail later.

**Comment by unknownbrackets** [comment]
Is it a framebuffer?  We used to emulate wrapping for render-to-texture, maybe that is broken?

-[Unknown]

**Comment by hrydgard** [comment]
@unknownbrackets Right, indeed seems so - the shader being used does not include the manual wrapping code. Maybe another dirty-bit fail, or similar..

**Comment by hrydgard** [comment]
In this particular case though, the other backends actually apply WRAP so it really is a problem setting those flags - since the texture is a power of 2 we don't go the shader wrapping path.
