### ISSUE TITLE
Metal Gear Acid 2 Importing MGA1 Save Issue

### ISSUE THREAD

**Issue by TideGear** [hrydgard/ppsspp#10814]
In Metal Gear Acid 2, when starting a new game and importing a save from Metal Gear Acid 1, the game offers some cards not unlocked in my MGA1 save and some that are. It also gives me 13,426,149 PTS when it should only be giving me 54 PTS (as tested on my hacked Vita using Adrenaline)...

![screenshot_20180326-180142_ppsspp](https://user-images.githubusercontent.com/16357059/37941161-9f0343ec-3121-11e8-97d2-8c861ac6f155.jpg)

...I did not use any cheats on either game. (That said, could [this](https://github.com/hrydgard/ppsspp/issues/7775) be a related issue somehow?) This MGA1 save was created by playing on my hacked Vita using Adrenaline, so it should be a good save...

[Completed MGA1 Save.zip](https://github.com/hrydgard/ppsspp/files/1850040/Completed.MGA1.Save.zip)

...I'm playing on a Galaxy S9+ with GIT v1.5.4-772-gf39897cfa.

**Comment by LunaMoo** [comment]
````
save was created by playing on my hacked Vita using Adrenaline, so it should be a good save
````
Vita = not PSP = PSP emulation = involves it's own set of problems and glitches, it can mean PPSSPP has a problem, or PSV psp emu has a problem or both have problems, We might never know;p.

 If you don't have actual psp, you would get more useful info by just trying someone elses saves from [gamefaqs](https://gamefaqs.gamespot.com/psp/920776-metal-gear-acid/saves).

**Comment by TideGear** [comment]
I do have an actual PSP, so I'll test a save from that ASAP.

**Comment by TideGear** [comment]
Ok, I can now confirm the problem is with PPSSPP, Here's a save from an actual PSP right after the first full mission...
[MGA1 Save (from Actual PSP).zip](https://github.com/hrydgard/ppsspp/files/1854525/MGA1.Save.from.Actual.PSP.zip)

Note that I have 1600 PTS in this save on the actual PSP...
![20180327_201738](https://user-images.githubusercontent.com/16357059/38007989-24dcdc00-3201-11e8-9515-52422091c4f1.jpg)

Here's the cards unlocked in this save on the actual PSP...
![20180327_201758](https://user-images.githubusercontent.com/16357059/38008064-7674d54a-3201-11e8-83a4-deb743800520.jpg)

![20180327_201805](https://user-images.githubusercontent.com/16357059/38008067-7a097cf6-3201-11e8-9545-fcdc3aeda114.jpg)

![20180327_201814](https://user-images.githubusercontent.com/16357059/38008071-7d89dd6c-3201-11e8-9a4d-fb66654e2e0c.jpg)

Here's the import process in MGA2 on the actual PSP...
![20180327_202045](https://user-images.githubusercontent.com/16357059/38008118-cc4837aa-3201-11e8-9065-ee9c969acccb.jpg)

...and the cards offered are only cards available in my save (as they should be)...
![20180327_202115](https://user-images.githubusercontent.com/16357059/38008122-d2d58cb2-3201-11e8-81fc-fd9aaec3aa6f.jpg)

![20180327_202125](https://user-images.githubusercontent.com/16357059/38008125-d59cf8f4-3201-11e8-8723-8e76d95d7cdb.jpg)

![20180327_202134](https://user-images.githubusercontent.com/16357059/38008128-d7d618c6-3201-11e8-953b-5bdb8ab1327f.jpg)

...and 16 PTS are given as it is 1/100th of 1600 PTS...
![20180327_202318](https://user-images.githubusercontent.com/16357059/38008145-f8ee2df0-3201-11e8-9730-8705fcb42c01.jpg)

Now, here's the save import process on PPSSPP using the actual PSP save. Uh oh, it's showing many cards that aren't unlocked...
![screenshot_20180327-203734_ppsspp](https://user-images.githubusercontent.com/16357059/38008203-5399e4ce-3202-11e8-8135-5e5deb8357ef.jpg)

![screenshot_20180327-203747_ppsspp](https://user-images.githubusercontent.com/16357059/38008207-5773ab2a-3202-11e8-8802-07dde5e48620.jpg)

![screenshot_20180327-203756_ppsspp](https://user-images.githubusercontent.com/16357059/38008209-59e9c43e-3202-11e8-9d0e-0fe75af4fb00.jpg)

![screenshot_20180327-203802_ppsspp](https://user-images.githubusercontent.com/16357059/38008211-5b97bb56-3202-11e8-9209-0962414bcb51.jpg)

![screenshot_20180327-203809_ppsspp](https://user-images.githubusercontent.com/16357059/38008215-5f29d380-3202-11e8-88b0-031a727fd2f0.jpg)

![screenshot_20180327-203818_ppsspp](https://user-images.githubusercontent.com/16357059/38008217-60eb5c16-3202-11e8-956d-9cfe09e9a71c.jpg)

![screenshot_20180327-203827_ppsspp](https://user-images.githubusercontent.com/16357059/38008223-648d257a-3202-11e8-95ab-6946fb5ecb33.jpg)

![screenshot_20180327-203834_ppsspp](https://user-images.githubusercontent.com/16357059/38008224-6649d548-3202-11e8-9e11-f0884daaab27.jpg)

![screenshot_20180327-203843_ppsspp](https://user-images.githubusercontent.com/16357059/38008227-67e553fa-3202-11e8-8736-f73ba63afb7e.jpg)

...and it's importing a huge amount of negative?! points...
![screenshot_20180327-203919_ppsspp](https://user-images.githubusercontent.com/16357059/38008228-6a227e9a-3202-11e8-8463-8dedc195e1bc.jpg)

It's also worth mentioning that when using this save with MGA1 (not MGA2) on PPSSPP, it loads fine!

So it's safe to say this issue is with PPSSPP and specifically it's importing of MGA1 saves. Pretty good proof, eh?

Thanks for sticking with me!

**Comment by hrydgard** [comment]
No idea what could be wrong here...

**Comment by unknownbrackets** [comment]
It might help to have a JpcspTrace of the save calls.  Another question: does this happen in JPCSP with the same save data?

-[Unknown]

**Comment by TideGear** [comment]
Yes, this bug happens in JPCSP too.

**Comment by unknownbrackets** [comment]
Hm.  Okay, another thing to check: the SDK versions of each game.

Go to Debug -> Run on Load (uncheck it), then Debug -> Disassembly on Windows.  Next, load MGA1.  In the Disassembly window, you'll see something like this:

```
	jal	zz_sceKernelSetCompiledSdkVersion
```

It's usually close to the start, and there might be numbers after "CompiledSdkVersion".  Find the line two steps down from that, and double click it so it becomes red.  For example, it might look like this:

```
	jal	zz_sceKernelSetCompiledSdkVersion
	move	s0,a1
	lui	a1,0x3   <-- this is the one to double click
```

Next, hit Go in the top left of the Disassembly window.  All we're doing is making it run until right after that function is called.  Now, in the left pane you should see "zero", "at", etc.  The one we want is a0.  It will look similar to 0x02060010 (which would mean the game was built against the PSP SDK version 2.60.)

If you right click the "zz_sceKernelSetCompiledSdkVersion" line (not the lower one we made red), and select "Copy Instruction (Disasm)", and then do the same for a0 on the left side, you can paste the values here.

Then the same for MGA2.  What I'm thinking is: they may be using different SDK versions, and different SDK versions encoded save data differently.  Maybe there's some way to override the SDK version that we're not respecting, but I want to make sure my theory even makes sense first.

-[Unknown]

**Comment by TideGear** [comment]
Thanks, UB, do I do this in JPCSP or PPSSPP?

**Comment by unknownbrackets** [comment]
PPSSPP - I don't really know JPCSP's debugger so I'm not sure how to get this info out of it.

-[Unknown]

**Comment by hrydgard** [comment]
Could it be decrypting the savegame with the wrong key, or something? (sorry, don't remember much about how that stuff works so might be way off...)

**Comment by TideGear** [comment]
@unknownbrackets Did I give you the necessary info?

**Comment by unknownbrackets** [comment]
Yes.  02060010 should be "version 3" savedata and no version would normally be "version 1" I think.  The main difference there is that version 1 doesn't use any kind of key.

I think this supports the theory that there might be some parameter the game is sending to the SDK to tell it to use a different savedata version...

-[Unknown]

**Comment by unknownbrackets** [comment]
I've added some reporting - I think the game is probably using the "secureVersion" field.

It'd help if you could use the latest git build (wait at least 10 minutes from when this message was posted) and enable "Enable compatibility server reports" in Settings -> System.  Then try to just load the save from MGA2.

If I'm right, it will report something ([which will show up in the report log](http://report.ppsspp.org/logs/game/ULUS10077_1.00)) like "Savedata version requested: 1".

-[Unknown]

**Comment by TideGear** [comment]
Ok, cool, I'll try this later tonight. Thanks!

**Comment by unknownbrackets** [comment]
Thanks - confirmed, so far.  Also, another game using this feature (but it seems to be a romhack):
http://report.ppsspp.org/logs/kind/1001

Will watch out for other reporting in case there are more affected games, but this looks promising.

-[Unknown]

**Comment by TideGear** [comment]
@unknownbrackets Awesome! Thanks for your help!

**Comment by TideGear** [comment]
I just tried importing a save with v1.6.3-536-g7b34eaa1f, and it appears to work correctly now!
