### ISSUE TITLE
[Android] Minimizing the app while paused causes a crash

### ISSUE THREAD

**Issue by leopard20** [hrydgard/ppsspp#10819]
What happens?
When I minimize (press the menu or "recents" button) and return to PPSSPP again, the app appears to be fine, but:
1. Save state screenshots appear blank (like a png picture with alpha=0).
2. As soon as I want to return to the game, it crashes.

If however I don't pause the game, everything works fine.

@hrydgard 
I think your pull request https://github.com/hrydgard/ppsspp/pull/10816 will fix it, but opened it just in case.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Android 7.0
Vulkan

**Comment by hrydgard** [comment]
Try it now :)

**Comment by leopard20** [comment]
Yep. It's fixed.
