### ISSUE TITLE
Cross-compile ppsspp (target) fails for Lakka

### ISSUE THREAD

**Issue by Ntemis** [hrydgard/ppsspp#10817]
What happens?
Compile fails

What *should* happen?

To be or not to be, competed!

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

Cross-compile on Linux x64 for arm

What is the error? Any logs we can look at?
Sure here it is:
          BUILD    ppsspp (target)
make[1]: Entering directory '/media/demetris/c4487cfd-d71a-441b-b83d-23d8ce19475d/Lakka-oem/build.Lakka-OdroidXU3.arm-2.1-devel/ppsspp-6505f77/libretro'
/media/demetris/c4487cfd-d71a-441b-b83d-23d8ce19475d/Lakka-oem/build.Lakka-OdroidXU3.arm-2.1-devel/toolchain/bin/armv7ve-libreelec-linux-gnueabi-g++ -mcpu=cortex-a15.cortex-a7 -mabi=aapcs-linux -Wno-psabi -Wa,-mno-warn-deprecated -mfloat-abi=hard -mfpu=neon-vfpv4 -fomit-frame-pointer -Wall -pipe -O2  -std=c++11 -O2 -D_NDEBUG  -DVK_USE_PLATFORM_XLIB_KHR -D__LIBRETRO__ -DPPSSPP -DUSE_FFMPEG -DGLEW_STATIC -DGLEW_NO_GLU  -I../ffmpeg/linux/x86_64/include -I. -I.. -I../Common -I../libretro -I../ext/native -I../ext/zlib -I../ext/snappy -I../ffmpeg  -I../ffmpeg/linux/x86_64/include -I../ext/cityhash -I../ext/armips -I../ext/native/ext -I../ext/native -I../ext/libkirk -I../ext/xbrz -I../ext/xxhash -I../ext/glew   -fPIC    -msse -msse2 -D_M_X64 -D_ARCH_64 -DGLES -DUSING_GLES2  -DDYNAREC -ffunction-sections -fdata-sections -c -o../ext/snappy/snappy-c.o ../ext/snappy/snappy-c.cpp
/media/demetris/c4487cfd-d71a-441b-b83d-23d8ce19475d/Lakka-oem/build.Lakka-OdroidXU3.arm-2.1-devel/toolchain/bin/armv7ve-libreelec-linux-gnueabi-g++ -mcpu=cortex-a15.cortex-a7 -mabi=aapcs-linux -Wno-psabi -Wa,-mno-warn-deprecated -mfloat-abi=hard -mfpu=neon-vfpv4 -fomit-frame-pointer -Wall -pipe -O2  -std=c++11 -O2 -D_NDEBUG  -DVK_USE_PLATFORM_XLIB_KHR -D__LIBRETRO__ -DPPSSPP -DUSE_FFMPEG -DGLEW_STATIC -DGLEW_NO_GLU  -I../ffmpeg/linux/x86_64/include -I. -I.. -I../Common -I../libretro -I../ext/native -I../ext/zlib -I../ext/snappy -I../ffmpeg  -I../ffmpeg/linux/x86_64/include -I../ext/cityhash -I../ext/armips -I../ext/native/ext -I../ext/native -I../ext/libkirk -I../ext/xbrz -I../ext/xxhash -I../ext/glew   -fPIC    -msse -msse2 -D_M_X64 -D_ARCH_64 -DGLES -DUSING_GLES2  -DDYNAREC -ffunction-sections -fdata-sections -c -o../ext/snappy/snappy.o ../ext/snappy/snappy.cpp
armv7ve-libreelec-linux-gnueabi-g++-6.4.0: error: unrecognized command line option '-msse'; did you mean '-fdse'?
armv7ve-libreelec-linux-gnueabi-g++-6.4.0: error: unrecognized command line option '-msse2'
make[1]: *** [Makefile:438: ../ext/snappy/snappy-c.o] Error 1
make[1]: *** Waiting for unfinished jobs....
armv7ve-libreelec-linux-gnueabi-g++-6.4.0: error: unrecognized command line option '-msse'; did you mean '-fdse'?
armv7ve-libreelec-linux-gnueabi-g++-6.4.0: error: unrecognized command line option '-msse2'
make[1]: *** [Makefile:438: ../ext/snappy/snappy.o] Error 1
make[1]: Leaving directory '/media/demetris/c4487cfd-d71a-441b-b83d-23d8ce19475d/Lakka-oem/build.Lakka-OdroidXU3.arm-2.1-devel/ppsspp-6505f77/libretro'
Makefile:27: recipe for target 'image' failed
make: *** [image] Error 2

**Comment by unknownbrackets** [comment]
You must not define X86_64 or X86 for cmake.  Not sure what your cmake command was or if you're properly cross compiling, but it seems to think it should be optimizing for Intel 64 bit.

-[Unknown]

**Comment by orbea** [comment]
I think this is the static makefile and not cmake? The static makefile has long been broken for arm linux, but it seems no one who has the hardware has been willing to take this farther or has not been able to. I personally don't have the hardware...

Its probably better to get this working with cmake instead.

**Comment by orbea** [comment]
Related issue https://github.com/libretro-mirrors/ppsspp/issues/31.

**Comment by gouchi** [comment]
I think I found the root cause, TARGET_ARCH is not changed for [arm](https://github.com/hrydgard/ppsspp/blob/master/libretro/Makefile#L203) or [imx6](https://github.com/hrydgard/ppsspp/blob/master/libretro/Makefile#L98) platform because we are using in the beginning of the [Makefile](https://github.com/hrydgard/ppsspp/blob/master/libretro/Makefile#L18-L20) [override directive](https://www.gnu.org/software/make/manual/html_node/Override-Directive.html#Override-Directive) .
