### ISSUE TITLE
[Feature Request] Ability to re-map certain F keys freely (to controllers?)

### ISSUE THREAD

**Issue by Abbanon** [hrydgard/ppsspp#10825]
Searching the internet only results in a single un-answered forum post from 2016, here: http://forums.ppsspp.org/showthread.php?tid=22174

But I was curious if there could be an addition to remap the F11 and F12 keys to whichever setup we'd like, be it different keyboard keys or controller/joypad inputs.
I have several unused buttons on my joypad when playing PPSSPP, for example, and it would be pretty awesome to be able to re-map Screenshot (F12) and Fullscreen (F11) to either more easily accessible keyboard keys, or just on the joypad itself.
Would this be a possibility?

**Comment by AggressivePencil** [comment]
Glad I found this before becoming the third guy to create yet ANOTHER request for it. Are we the only guys who want this simple, additional remap? I noticed that forum post last year haha, surprised nobody responded here or there!
