### ISSUE TITLE
Not saving ANYTHING[PC Version]

### ISSUE THREAD

**Issue by kf21** [hrydgard/ppsspp#10822]
What happens?
Saving games does not work cause for some reason the memory stick is not inserted, Save/load states doesnt work. And It doesnt save my settings

Saving games I really have no problems with(would be nice if you could help me with that), its just the fact that it doesnt save mmy settings(controls, graphics) and its annonying to just keep having to change the settings to the way i want them to be. and it doesnt even let me create a game config.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

**Comment by hrydgard** [comment]
How did you install the emulator, using the installer or unzip? My guess is that you put it in some location where it doesn't have rights to write a memstick subdirectory.

**Comment by leopard20** [comment]
My thoughts exactly. If you have installed it in one of the system directories (e.g Program Files), you have to run the program with admin rights.

**Comment by TehPlayer14** [comment]
You need access for writing data for particular folder or Admin rights or even Ownership

**Comment by unknownbrackets** [comment]
It will try to write to My Documents if it can't write to memstick, or at least it used to.

But, if it can't write there either (I'm not sure, but this could happen if you ever ran it as admin), then it won't be able to write at all.

It's not clear what platform you're using, but iOS also has this problem in spades - I think some methods of putting the app on iOS devices make everything read-only to the app, and it can't write its settings (this doesn't happen when using Xcode.)

-[Unknown]

**Comment by MorrisonGamer** [comment]
I can confirm this issue...for some reason...the game settings just don't apply when you launch a game, specially through a command line(I doubt it's the issue)

![image](https://user-images.githubusercontent.com/27028529/38086172-bdd6dd06-3329-11e8-85ca-954287f178ab.png)

Then, if you maximize, pause, or anything, the settings return to the normal, which is really weird.

**Comment by hrydgard** [comment]
@MorrisonGamer That's clearly not the same issue as the poster was complaining that no settings saved. But that also does seem like a bug where things aren't initialized in the correct order, please make a new issue about that.

**Comment by MorrisonGamer** [comment]
Right, creating the issue, sorry for taking soo long.

But posted the issue on #10835

**Comment by unknownbrackets** [comment]
Does this still happen in the latest git build?

-[Unknown]

**Comment by unknownbrackets** [comment]
Maybe this was actually #11114?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.  #11124 will not show a warning if the cause is #11114.

It's hard to tell when fixes in PPSSPP might fix other games or issues, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game or games, just create a new issue instead.

-[Unknown]
