### ISSUE TITLE
Gta vc stories shutter 

### ISSUE THREAD

**Issue by fahadfoyjur** [hrydgard/ppsspp#10824]
What happens?
Grant theft auto vice city stories , 
Sometime shutter this game , and sometime smooth avg fps 30+  
Every 5-7seconds the gta vc story keep shuttering . sorry for my bad eng 😥😥😥

What *should* happen?

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

**Comment by leopard20** [comment]
No issue in my tests. Tested both vulkan and openGL. v1.5.4-793

What system are you running the game on? What's the PPSSPP version?

**Comment by fahadfoyjur** [comment]
Still face the prob in latest build 795 
 Others psp games properly best worked ,
but gta vc shutter blackscreen prob . 
My device support only opengl not vulkan 
😥😥😥😥😫😫😫

**Comment by Jinzombie** [comment]
*Sorry for my english too 😅✌

**Comment by fahadfoyjur** [comment]
Non buffer effect cause blackscreen

**Comment by fahadfoyjur** [comment]
Adreno 505

**Comment by marosis** [comment]
Try set 222MHZ on CPU Clocks maybe

**Comment by fahadfoyjur** [comment]
No bro same prob in my pc  too 😫😫

**Comment by leopard20** [comment]
Did you dump the UMD yourself? Sometimes dumped UMDs have some problems.

If we don't have the problem and you get it on both PC and Android and you're sure both systems are powerful enough, the only explanation is either you're using bad settings or the UMD you're using is corrupted.

I recommend that you try the instructions under **Step 2** here:
https://github.com/hrydgard/ppsspp/wiki/Help:-PPSSPP-is-crashing

If it doesn't help, then perhaps you should try another UMD. There are a lot of sites you can download the UMD from, like EmuParadise, LoveROMs, FreeROMs, CDromance, etc. I recommend the first two.

**Comment by hrydgard** [comment]
@leopard20 please stop referring to download sites. For all kinds of reasons, it's not a good idea to post such things here.

**Comment by leopard20** [comment]
Whatever dude

**Comment by Jinzombie** [comment]
https://youtu.be/EwpChOxBxos
Watch my video maybe it help I provide with settings so better watch it abd feedback if still has problem.

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
