### ISSUE TITLE
Ultimate Ghost 'n Goblins Crashes

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#10823]
The game has crashes trying to start the game

**Comment by hrydgard** [comment]
Please follow these instructions:
https://github.com/hrydgard/ppsspp/wiki/How-to-report-an-issue-properly

**Comment by adennen** [comment]
I have this issue too, I'm running the latest source version on a Mac, the crash is a EXC_BREAKPOINT (SIGTRAP) in TextureCacheCommon::ApplyTexture().I think it's being caused by line 1520: _assert_(!entry->texturePtr); commenting this line out fixes the crash for me

**Comment by hrydgard** [comment]
Huh, interesting.

**Comment by hrydgard** [comment]
Same game used to leak a lot of textures in a different way before: https://github.com/hrydgard/ppsspp/issues/9089

**Comment by hrydgard** [comment]
Try now.

**Comment by adennen** [comment]
It's working for me
