### ISSUE TITLE
Amazon FireTV remote input - Confirmation button recognition.

### ISSUE THREAD

**Issue by ppsspp213** [hrydgard/ppsspp#10831]
https://developer.amazon.com/docs/fire-tv/remote-input.html
https://developer.amazon.com/docs/fire-tv/supporting-controllers-in-web-apps.html

Select (D-Pad Center) | KEYCODE_DPAD_CENTER | 13 

Over usable buttons
Play/Pause | KEYCODE_MEDIA_PLAY_PAUSE | 179 
Rewind | KEYCODE_MEDIA_REWIND | 227
Fast Forward | KEYCODE_MEDIA_FAST_FORWARD | 228  
Menu | KEYCODE_MENU

Not sure but would the back button be usable in-game also?
Back | KEYCODE_BACK

**Comment by ppsspp213** [comment]
Also if you have Samsung Smart TV remote you can connect it to the Anynet+ (HDMI-CEC) 
service to control Amazon FireTV with the following usable buttons, found them using Mupen64AE_FZ :-)

0 | KEYCODE_0 | 7
1 | KEYCODE_1 | 8
2 | KEYCODE_2 | 9
3 |  KEYCODE_3 | 10
4 |  KEYCODE_4 | 11
5 |  KEYCODE_5 | 12
6 |  KEYCODE_6 | 13
7 |  KEYCODE_7 | 14
8 |  KEYCODE_8 | 15
9 |  KEYCODE_9 | 16

Red | KEYCODE_PROG_RED | 183
Green |  KEYCODE_PROG_GREEN | 184
Yellow |  KEYCODE_PROG_YELLOW | 185
Blue |  KEYCODE_PROG_BLUE | 186

Stop | KEYCODE_MEDIA_STOP | 86
Rewind | KEYCODE_MEDIA_REWIND | 89
Fast Forward | KEYCODE_MEDIA_FAST_FORWARD | 90
Play | KEYCODE_MEDIA_PLAY| 126
Pause | KEYCODE_MEDIA_PAUSE | 127

Up | KEYCODE_DPAD_UP | 19
Down | KEYCODE_DPAD_DOWN | 20
Left | KEYCODE_DPAD_LEFT | 21
Right | KEYCODE_DPAD_RIGHT | 22
Confirm | KEYCODE_DPAD_CENTER | 23

**Comment by unknownbrackets** [comment]
Is this still an issue?  I know there were some changes made to Android input handling.

-[Unknown]

**Comment by ppsspp213** [comment]
It works fine for the menus but I'd need to do a fresh install to fully
check if it gets past the initial storage check.

**Comment by ppsspp213** [comment]
You can use usb storage & controller in dual via otg adapter but sometimes
the storage fails, I guess it doesn't carry enough power to support all
three.
Advisable to use a powered usb hdd instead of usb stick.

**Comment by hrydgard** [comment]
OK, I'll close this then.
