### ISSUE TITLE
some minor problems v 1.5.4.804 and older

### ISSUE THREAD

**Issue by kokoalpha** [hrydgard/ppsspp#10838]
What happens?
1_auto rotation still causing the emulator to crush 

2_the shader's warning is missing

**Comment by leopard20** [comment]
You sure about the first one? Doesn't happen for me.

**Comment by kokoalpha** [comment]
yes

**Comment by unknownbrackets** [comment]
Which backend?  OpenGL or Vulkan?

What do you mean by shader warning?  Can you show a screenshot of it working in a different version?

-[Unknown]

**Comment by kokoalpha** [comment]
1_opengl sir 

2_in older ppsspps versions when you change the shader's if it's not working or not compatible it will show you a warning now it doesn't i will download an older version and I will show you

**Comment by kokoalpha** [comment]
costume shader's sir not the built in

**Comment by unknownbrackets** [comment]
I tried rotating my Pixel for a while, over and over, but it didn't crash in OpenGL.  But maybe it's some kind of race and related to #10849?  Interesting that that didn't happen.

For the other, see #10853.

-[Unknown]

**Comment by zminhquanz** [comment]
I think he isn't feedback . That's why he didn't comment in topic here =))

**Comment by hrydgard** [comment]
Let's close this for now.
