### ISSUE TITLE
Can I create a ui_atlas.zim file with the atlastool with english fonts?

### ISSUE THREAD

**Issue by Slippy2k** [hrydgard/ppsspp#10846]
Can I also create a ui_atlas.zim file with the atlastool with english fonts?
Because when I create a ui_atlas.zim with the atlastool everything is in Korean or Chinese font

**Comment by unknownbrackets** [comment]
The regions within ui_atlas.zim are compiled into PPSSPP.  You must recompile PPSSPP with the updated ui atlas information when you regenerate ui_atlas.zim.

-[Unknown]

**Comment by Slippy2k** [comment]
What is the command for the US regenerate ui_atlas.zim ?

**Comment by unknownbrackets** [comment]
U is for US.  As long as you have the U flag, it will include ASCII characters in the map:

https://github.com/hrydgard/ppsspp/blob/master/atlasscript.txt#L2

But again, it also generates this file:

https://github.com/hrydgard/ppsspp/blob/master/UI/ui_atlas.cpp

And the cpp compiled into ppsspp must always exactly match the zim file, or you'll get garbage.

-[Unknown]
