### ISSUE TITLE
Game shortcut issue

### ISSUE THREAD

**Issue by abdellahking** [hrydgard/ppsspp#10841]
What happens?
So this is an issue and request
And this is NOT a big issue so feel free to close it.
So when i use shortcut for any games it work just one time, and after i wenna re-open it she dosen't work she keep going to the ppsspp home
And the request is you make the original icon of the game ,in shortcuts like "epsxe" it be nice,and i know mybe it useless,but just make a try

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Android 6.0
Opengl 
Mali t720

And by the way th"issue" ti hapend on every ppsspp version

And sorry about the english😂😂

**Comment by MorrisonGamer** [comment]
You mean...you want something like THIS?

![image](https://user-images.githubusercontent.com/27028529/38168121-3d247658-351a-11e8-8878-31640f3cbe8e.png)

Well..it's not that easy, there would need to be a database with icons, PPSSPP would need to have a system to create shortcuts...bla bla bla...it's literally a waste of time if there's no database.

Make shortcuts with Steam ROM Manager, that way, you have less problems initializing them from shortcuts. And  they even integrate into te Steam Overlay.

**Comment by abdellahking** [comment]
Ah ,ok so this seem pointlees so im gonna close it

**Comment by hrydgard** [comment]
Wait, this used to be an issue but I thought I had it fixed, last I tested shortcuts they worked as expected...

**Comment by abdellahking** [comment]
Yeah tnx, and i realize somthing whene i open the shortcut and after taking me to ppsspp home screen and exite and reopen the shortcut it will cause a crash

And tnx for your work

**Comment by abdellahking** [comment]
Yeah so it fix on latest built but when i exite and reopen it crash 2 or 3 times and the it will open

**Comment by abdellahking** [comment]
So any idea ?

**Comment by unknownbrackets** [comment]
Crashes before might've been graphics restart / resizing crashes.  Has this improved?

-[Unknown]

**Comment by abdellahking** [comment]
Yeah ,i can tell that's  has improved on latest built(820) no crash so far so maybe colse it?

Sorry about the english 😦

**Comment by unknownbrackets** [comment]
Okay, great.  Icons are a bit trickier - although maybe we could use the icon for the game, it's a bit too wide.  I've created #10885 for that.

-[Unknown]
