### ISSUE TITLE
shadow of destiny's textures.

### ISSUE THREAD

**Issue by sephiroth0396** [hrydgard/ppsspp#10851]
I don't know. It's look like the emulator doesn't load/place the textures on the character's head right. Only the head of them. Everything is work fine except the textures of their head, I guess.

**Comment by hrydgard** [comment]
Screenshot? Comparison to what it looks like on a real PSP?

**Comment by sephiroth0396** [comment]
I don't have the game right now will make a footage of it later.

**Comment by sephiroth0396** [comment]
Oh. Oh.https://m.youtube.com/watch?v=UZDRB0hPDe0 Someone else is uploaded it already. Here is the issue

**Comment by sephiroth0396** [comment]
It's should be like this one https://m.youtube.com/watch?v=81PKHpX-cPM

**Comment by unknownbrackets** [comment]
Pretty sure this game uses morph for faces, so I'm guessing this is an issue with morph - perhaps related to the software skinning changes?

-[Unknown]
