### ISSUE TITLE
[Android] More audio click and pops from 1.4 and later

### ISSUE THREAD

**Issue by RaduNastase** [hrydgard/ppsspp#10865]
What happens?
All games i tested (BlazBlue, DBZ:Shin Budokai, Soul Calibur, Capcom Collection - Street Fighter 2) have minor but frequent audio distorsions, clicks and pops, while the games run full speed. 

What *should* happen?
Trying different settings like Audio Latency, Frameskip, CPU clocks gives no better results. Revisions 1.2.2 and 1.4.2 of ppsspp had no such issues.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Rooted Snapdragon Galaxy Note 3 with kit kat

**Comment by hrydgard** [comment]
What about the original 1.5.4 on your device?

**Comment by RaduNastase** [comment]
Intalled it now and tested BlazBlue and DBZ:Shin Budokai with frameskip set to Auto 3. It still has audio cracks that's for sure. DBZ has it, but BlazBlue is the game to test for this issue, as it's much more noticeable and frequent.

**Comment by unknownbrackets** [comment]
Maybe we made rendering more efficient so it's clocked the CPU down more?

What's the first git build with the issue and the last git build that worked right?

-[Unknown]

**Comment by RaduNastase** [comment]
Ok, so after a few hours of testing i have some answers. I picked BlazBlue to test as it's the most noticeable.

The last version with minimal audio issues (there are a few clicks and pops but )

**Comment by RaduNastase** [comment]
..sorry for double post ...i  accidentally pressed the comment button and i don't seem to find the edit option (i'm on mobile).

So, the last version with virtually no issues is 1.3.x. 

Starting with 1.4, the audio starts to have more clicks and very brief distortions, as far as i could observe, mainly in effects, but also in music. Overall there is a tangible downgrade in audio fidelity.

1.5.x official is about the same as 1.4

Latest 1.5 - builds - have even more clicks in special effects an music is also a little jumpier.

**Comment by RaduNastase** [comment]
Yeah, the clicks in audio are definitely more frequent in latest builds compare to 1.3, which was much cleaner. I haven't been able to determine a pattern, or some connection to a certain setting or to sudden drops in performance, as all is pretty smooth and even cutting the framerate of a 60 fps game in half (by adding one frame skip) changes nothing. It's random. 2D games like BlazBlue and Guilty Gear XX _seem_ to be more affected than 3D like Soul Calibur and Tekken Dark Ress.

It also can't be caused by the speed enhancements in the latest builds as 1.4 and 1.5 have the clicks as well. 

Sustained, lengthy higher pitch sounds seem to have most clicks in comparison to other effects and normal background music.

**Comment by leopard20** [comment]
I also get occasional slow downs when audio falls out of sync. The game stutters for like a second or two and the sound loops for that period. It's very infrequent and some games I played didn't have this issue at all (e.g MHFU)

Some games that have this issue (mostly games that play songs one after the other):
Tekken 6
NFS Underground and Carbon
Burnout Dominator

**Comment by AlexHankins** [comment]
I'm also experiencing this with _Disgaea Afternoon of Darkness._  Even with the frameskip set to 8, and the HUD showing over 99% speed, it clicks during any audio.  It's especially obvious with the music.

**Comment by hrydgard** [comment]
@AlexHankins  if you're still around, what device are you experiencing that on?

I don't know if there's anything actionable here because generally audio clicking is caused by slowdowns, and whenever things are full speed on my devices, i don't hear any clicking.

**Comment by Emulatorer** [comment]
I didn't experience this issue using ppsspp last build 🤔

**Comment by hrydgard** [comment]
@Emulatorer  are you saying that you think it improved?

**Comment by Emulatorer** [comment]
@hrydgard Im not really sure though 😅
My phone is Mali-450 GPU only with 1.4GHz CPU speed
maybe its depend on the phone specifications?

**Comment by Emulatorer** [comment]
IDK if this really could useful but i found out the difference in ppsspp v1.8 vs ppsspp v1.8.0-630 using my Tablet w/ 1gb ram mali-t720 gpu 1.3Ghz cpu 😅
![1569150984554](https://user-images.githubusercontent.com/37603562/65386423-28abce80-dd6e-11e9-9cbf-70e3b47e4dda.jpg)
![1569151094858](https://user-images.githubusercontent.com/37603562/65386428-32cdcd00-dd6e-11e9-91ab-5d0fa15a279f.jpg)

**Comment by Gamemulatorer** [comment]
This issue should be close now no feedback/updated

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
