### ISSUE TITLE
Some games cutscene video unplayable/flickering

### ISSUE THREAD

**Issue by C4rrotMilk** [hrydgard/ppsspp#10862]
What happens?
Final Fantasy Type 0
Some cutscene unplayable(Blackscreen and no sound at all,but skip-able)

Shin Sangoku Musou 5 Speacial
Cutscene Flickering

Cutscene play normally on 1.4 and older version

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

Snapdragon 801 Adreno 330 OpenGL Backend

**Comment by C4rrotMilk** [comment]
Forgot to say i using newest Dev build v1.5.4-819-gd70568abd

**Comment by MorrisonGamer** [comment]
Can confirm this happens.

Final Fantasy Type-0
Movies were previously working JUST fine, never flickering, full speed even with frameskip off, now they are randomly flickering, but still work fine. Tested with Simulate Block Transfer effect on/off.

Specs on info box: http://steamcommunity.com/id/AkiraPlays

**Comment by unknownbrackets** [comment]
This sounds like a duplicate of #10694?

Interesting that it's happening on an Intel card too.

-[Unknown]

**Comment by MorrisonGamer** [comment]
Well, I'm not having any blackscreen, but I've never felt flickering audio on the opening scene or any movies in Type-0. No matter what settings I change, FPS remains the same, 30/100% speed and the audio just randomly flickers. Never happened before.

**Comment by hrydgard** [comment]
Can you go back and find the first build where this problem appears?

**Comment by C4rrotMilk** [comment]
v1.4.2-199-g3249d8165 is the last build tht still work properly

**Comment by hrydgard** [comment]
So 1.4.2-208 doesn't work? That would implicate https://github.com/hrydgard/ppsspp/pull/9810 which seems a bit unlikely..

**Comment by C4rrotMilk** [comment]
It doesn't work on 1.4.2-208,something might be messed up in 1.4.2-200 maybe.I have zerp knowledge about coding,sry can't help u on this :(

**Comment by hrydgard** [comment]
Hm. Do the various I/O timing settings under Settings/System make any difference?

**Comment by unknownbrackets** [comment]
If this is happening specifically with Type-0, my recollection is that it was > 2GB.

Does it happen even when compressed as cso, or does that affect it?  Note that not all compressors support >= 2GB files, but maxcso for example does.

-[Unknown]

**Comment by C4rrotMilk** [comment]
It worked just like Unknown said,can close the issue now

Thanks for the trouble :)

**Comment by unknownbrackets** [comment]
Can you try this again - with the original iso - to see if that bug is fixed?

It's better to use the cso, but want to make sure people using the iso without knowing that don't get crashes.

-[Unknown]

**Comment by unknownbrackets** [comment]
Also, is Shin Sangoku Musou 5 Special also fixed by using a cso?  How large is that ISO?

-[Unknown]

**Comment by C4rrotMilk** [comment]
The bug is fixed,Shin Sangoku is around 1.5GB but i don't have the game right now,have to ask my friend test it later.

**Comment by C4rrotMilk** [comment]
Shin Sangoku got fixed as well,guess can finally close the issue now.

Thanks for the hardwork 🙂

**Comment by unknownbrackets** [comment]
Thanks - I'm going to close.  @MorrisonGamer it sounds like your issue might be a different one?  Can you open a new issue if it still happens?

-[Unknown]
