### ISSUE TITLE
Cyrillic text issues 

### ISSUE THREAD

**Issue by Blacob777** [hrydgard/ppsspp#10879]
![screenshot_2018-04-05-14-04-09-279_org ppsspp ppsspp](https://user-images.githubusercontent.com/29165096/38411900-b3cefbda-39ba-11e8-9761-61fc73818e04.png)

**Comment by unknownbrackets** [comment]
I think this may actually be the same as #2127?

-[Unknown]

**Comment by hrydgard** [comment]
Yes, closing as duplicate, even though your new PR will also close it soon :)
