### ISSUE TITLE
ds4 cuh-zct2g model v2 buttons are reversed

### ISSUE THREAD

**Issue by zebranco** [hrydgard/ppsspp#10873]
What happens?
ds4 cuh-zct2g dualshock 4 v2
Hardware ID: USB\VID_054C&PID_09CC&REV_0100&MI_00
Location of Information:  0000.0014.0000.004.000.000.000.000.000

square and triangle buttons are reversed
buttons l1 r1 station on l2 r2

What *should* happen?
square should be in the triangle
triangle should be in square
l2 should be in l1
r2 should be in r1

![ds4 bug input](https://user-images.githubusercontent.com/31833329/38346394-2e6ad6ee-386b-11e8-8522-a9adf9596741.jpg)
windows 10 fall creators update

**Comment by LunaMoo** [comment]
See [this discussion on steam](https://steamcommunity.com/app/376300/discussions/0/487876568223419528/) for a potential solution. Or just remap your buttons.
 Either way this doesn't seem to be a PPSSPP issue, but the fact that you're using gamepad which isn't properly supported under your operating system potentially through a third party software which makes it work as dinput and xinput at once(which is terrible for any app or native game which supports both standards) as such I'll close it.

**Comment by zebranco** [comment]
in the emulator rpcs3 the control works correctly "driver vanilla" https://github.com/RPCS3/rpcs3/issues/2266

in steam the error of the buttons reversed for ds4 v2 has already been corrected in time "NATIVELY FUCHSLY WITHOUT USE OF THIRD PARTY SOFTWARE"

https://community.playstation.com/content/pdc/us/en_US/pdc-communities/helldivers.topic.html/steam_update_adding-Pk6e.html

http://store.steampowered.com/news/?feed=steam_client
Steam Client Update Released

21 de mar Added a custom kernel driver for Sony DS4 controllers which allows use with Steam Input when connected over Bluetooth

11/out/2017 Fixed DS4 Gyro when streaming over a Steam Link

29/ago/2017 Fixed a bug where PS4 controllers connected via streaming would be ignored due to a local instance of DS4Windows or Inputmapper

10/jul/2017 Added check for InputMapper and DS4Windows on connection of PS4 Controllers. If either program is running Steam will ignore the controller until it is reconnected.

1/jun/2017 Simplified UI for DPad mode on DS4 Dpad

9/mar/2017 Added audio support for official DS4 v2 Slim controllers

the problem only hits ppsspp
