### ISSUE TITLE
Vram full error message on Jeanne D'Arc on Android.

### ISSUE THREAD

**Issue by blackman91** [hrydgard/ppsspp#10877]
What happens?
Vram full error message after playing for a while and some textures become black and everything slows down. Default settings and enabling the cache ppsspp options doesn't fix it.

What *should* happen?
Not that.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

Latest ppsspp dev build on Android 7 motog5 plus, vulkan renderer.

**Comment by hrydgard** [comment]
@unknownbrackets Obtained the below screenshot. For some reason, our Vulkan allocator has serious issues with this game.. Very odd, wonder what those lingering allocations are. We really seem to eager to make new blocks instead of re-using the existing ones...

![jeanne](https://user-images.githubusercontent.com/130929/38386069-f02901ae-3913-11e8-8d54-f4a69ee50a25.JPG)

**Comment by unknownbrackets** [comment]
I've added some basic tag tracking but running short on time - will check on it more tomorrow.

This game does use beziers and depth copies but otherwise I don't remember any funny business that'd make leaks specially likely.  Who knows, though.

-[Unknown]

**Comment by unknownbrackets** [comment]
I did find some old textures, but they're not leaking - we're just not decimating when the texture cache isn't very full (`cacheSizeEstimate_ >= TEXCACHE_MIN_PRESSURE` - this cut down on deletions of textures that game back in racing games, etc.)

So what's happening in the above screenshot is that MOST of the memory gets used up by textures getting replaced, and it crawling forward.  It tries to avoid reusing slab memory in many cases, in part so larger slabs can be allocated.  However, there's not that much - total - in the texture cache, so it doesn't decimate.

Not seeing any actual leaks, although there are some UI textures that are kept during gameplay.

-[Unknown]

-[Unknown]
