### ISSUE TITLE
Emulator Freezes on Windows 10 UWP! If I want to return to the game from the settings

### ISSUE THREAD

**Issue by Slippy2k** [hrydgard/ppsspp#10882]
When I play an ISO game and then in pause go with ESC and then in the settings and from there back click on back freezes the emulator!
In games from the homebrew store the emulators freezes but not when I get out of the settings

**Comment by hrydgard** [comment]
Couldn't repro but found another freeze issue (almost all games in debug mode...) and fixed that, so hopefully this problem will go away too.

**Comment by Slippy2k** [comment]
This fix does not do anything, the emulator is still freezing. I used the demo cube.iso

**Comment by hrydgard** [comment]
Ok, thanks for reporting.

**Comment by Slippy2k** [comment]
I just do not understand why homebrew work without problems and ISO Games not where is the difference?

**Comment by hrydgard** [comment]
On UWP, we can access our own directory freely but to access files outside it like ISOs, we have to use the async StorageFolder APIs, which is very annoying as they don't fit our use case at all. I had to make a terrible threaded wrapper around it, and that may still have some bugs.

It does seem to work for me on Windows just fine though..

**Comment by dominater01** [comment]
this should be fixed now

**Comment by unknownbrackets** [comment]
Closing based on the above comment.

-[Unknown]

**Comment by hrydgard** [comment]
I have recently fixed a bunch of additional bugs in the UWP async file wrapper, this should indeed no longer happen.
