### ISSUE TITLE
When I switch from DirectX 11 to DirectX 9 or OpenGL under UWP, the API does not change

### ISSUE THREAD

**Issue by Slippy2k** [hrydgard/ppsspp#10883]
What happens?
When I switch from DirectX 11 to DirectX 9 or OpenGL under UWP, the API does not change
In the Windows version the API conversion works but without problems.
Is the problem fixable?

What *should* happen?
Change the API from DirectX 11 to DirectX 9 or OpenGL

**Comment by Slippy2k** [comment]
And what is with Vulkan ?

**Comment by hrydgard** [comment]
The only 3D APIs that can be used in UWP apps are D3D11 and D3D12. We don't support D3D12, leaving D3D11 as the only choice.
