### ISSUE TITLE
Can not enable Vulkan API on Intel n3450 under Arch Linux

### ISSUE THREAD

**Issue by Naozumi2k** [hrydgard/ppsspp#10886]
**What happens?**

PPSSPP does not start up after changing API from OpenGL to Vulkan

**What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.**

Intell Apollo Lake n3450 iGPU HD Graphics 500 Arch Linux 4.15.15-1-ARCH kernel
PPSSPP git version 1.5.4-850-g93bf86612

```
I: VulkanLoader.cpp:290: Vulkan test instance created successfully.
I: VulkanLoader.cpp:324: Found working Vulkan API!
Vulkan might be available.
I: Config.cpp:440: Longest display side: -1 pixels. Choosing scale 1
06:27:045 Core/Config.cpp:1051 I[LOADER]: Loading controller config: /home/yakov/.config/ppsspp/PSP/SYSTEM/controls.ini
Pixels: 960 x 544
Virtual pixels: 960 x 544
W: VulkanLoader.cpp:369: Vulkan base functions loaded.
W: VulkanLoader.cpp:536: Vulkan instance functions loaded.
I: VulkanContext.cpp:457: Chose physical device 0: 0x55f5697287b0
W: VulkanLoader.cpp:543: Vulkan device functions loaded.
I: VulkanContext.cpp:581: Device created.

I: VulkanContext.cpp:635: Creating Vulkan surface (960, 544)
I: VulkanContext.cpp:797: swapchain_format: 44 (/2)
I: VulkanContext.cpp:801: gfx_queue_: 0x55f569a8be50
I: VulkanContext.cpp:833: Supported present mode: 0 (IMMEDIATE)
I: VulkanContext.cpp:833: Supported present mode: 1 (MAILBOX)
I: VulkanContext.cpp:833: Supported present mode: 2 (FIFO)
I: VulkanContext.cpp:857: Chosen present mode: 1 (MAILBOX)
I: VulkanContext.cpp:863: numSwapChainImages: 3
I: VulkanQueueRunner.cpp:8: VulkanQueueRunner::CreateDeviceObjects
PPSSPPSDL: ../mesa-18.0.0/src/intel/vulkan/anv_device.c:2273: anv_bind_buffer_memory: Assertion `(buffer->usage & mem->type->valid_buffer_usage) == buffer->usage' failed.
Aborted (core dumped)
```

**Comment by mrcmunir** [comment]
Working fine here with mesa 18.1-devel and IGPU HD 520 GPU.
So will be specific for some IGPU architecture or maybe some regresion in some mesa3d commit .

**Comment by hrydgard** [comment]
Yeah that looks like a driver bug, please see if you can update to the latest mesa. If not do what mrcmunir says :)

**Comment by Naozumi2k** [comment]
My mesa version is 18.0.0-2 so it is latest avalible build.
I'll try to build mesa-git from AUR to see if it helps.
[gdb log](https://gist.github.com/Naozumi2k/e6e9054d3c96de8ae0fc8080441771d0) (not sure it helps a lot)

**Comment by hrydgard** [comment]
yeah that doesn't say very much, seems the symbols got stripped off that intel driver..

**Comment by Naozumi2k** [comment]
After a few days it issue got resoulved by itself :D lol
I've got an update to vulkan-intel package so maybe that bug was fixed by dev since it is working fine now
