### ISSUE TITLE
[Android] Enable 4X MSAA in developers options give some graphis enhancemnts in some games?

### ISSUE THREAD

**Issue by Jinzombie** [hrydgard/ppsspp#10889]
1. 

What happens?
When I enable 4X msaa in developers options during skipp-buffer rendering set the rendering resolution to X1 and display resolution to Auto (same as rendering resolution) it gives enhancement the graphics it fix the pixelated graphics

What *should* happen?
Can you add option that enable 4X msaa?

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

Mali-400 GPU
Android 6.0

**Comment by hrydgard** [comment]
Hm, actually in https://github.com/hrydgard/ppsspp/issues/3999 there is discussion of a few GL extensions that make it fairly easy on mobile. Though we already have an issure for this, https://github.com/hrydgard/ppsspp/issues/6218 , so closing this as a duplicate.

**Comment by Jinzombie** [comment]
![not pixelated](https://user-images.githubusercontent.com/37603562/38464467-032a8264-3afe-11e8-901f-40c9ac0c2381.png)
When enable 4X msaa

**Comment by Jinzombie** [comment]
@hrydgard  ok tnx for the info :)
