### ISSUE TITLE
the code signing identity value to "Mac Developer" in the build settings editor.

### ISSUE THREAD

**Issue by fedorax** [hrydgard/ppsspp#10880]
What happens?
I cant signing "iOS Developer" and not available to select my iPhone.
- My iPhone update ios 11.3
- Xcode update 9.3

before update ios. signing and select target fine.

What *should* happen?

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

**Comment by fedorax** [comment]
This issue was solved myself. so this is close.
thank you.

**Comment by hrydgard** [comment]
It could be useful for others to know how you solved it, feel like telling us?
