### ISSUE TITLE
Latest build not work on armv7

### ISSUE THREAD

**Issue by endrare** [hrydgard/ppsspp#10901]
What happens?

Error when open ppsspp

What *should* happen?

latest build not work after since v1.5.4-857-g7dbd2cecd 

screenshot notif: [IMG]http://i64.tinypic.com/vi0d3a.jpg[/IMG]

What hardware and operating system are you running PPSSPP on?
Lenovo A60+ 
GB 2.3.6

MTK6575
PowerVR SGX531

**Comment by leopard20** [comment]
ARMv8a works though.

**Comment by mrcmunir** [comment]
Working fine for me in Samsung Galaxy s3 neo is armv7 but with newer Android versión .

Maybe broken  Android 2.3.6 and not Armv7 problem

You can log with logcat or adb What reason for won't load lib?

**Comment by hrydgard** [comment]
I think I know what this is, I'll fix it up soon.

**Comment by hrydgard** [comment]
That change should have fixed it. Let me know if that's the case, or I'll have to dig up some old phones..

**Comment by hrydgard** [comment]
Yeah. Newer SDKs don't actually officially support older Android versions than SDK 14 (4.0), so if we use functions that simply aren't there on older versions of Android, all bets are off.

**Comment by hrydgard** [comment]
@endrare  does the latest build work for you?

**Comment by endrare** [comment]
yes new build now working
