### ISSUE TITLE
Investigate alternative ways to do depal, to fix performance in Sonic Rivals and MGS: Acid 2

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#10908]
When games use palettized (CLUT, color look up table) texturing when texturing from a framebuffer, we currently "depalettize" (index) it into a full color texture, and then texture using that. This has the great advantage that texture filtering works as normal, but is quite expensive since we do this in a pixel shader and thus need to start up a render pass, which is not cheap on mobile.

An alternative would be to "depalettize" directly in the shader when reading these textures, but to do that we need to handle filtering ourselves since that needs to happen after the depalettization. So the pixel shader gets heavier but we lose the extra render pass. An additional alternative may be to use a compute shader to do the work, in order to avoid starting up a render pass, but I don't think it's that much cheaper and has obvious compatibility issues with older devices.

Now, the issue is that a few games, like Sonic Rivals, Metal Gear Solid Acid 2 and, IIRC, Test Drive Unlimited, use the depal functionality with color ramps as palettes to perform various forms of color correction. They do this in little tiles across the screen, resulting in many tens or hundreds of render passes per frame. The cost of the above-mentioned alternative with in-shader manual filtering would be much smaller, so might be worth implementing to get acceptable performance out of these games on mobile.

**Comment by hrydgard** [comment]
Implemented shader depal for Vulkan in #10911 , Unknown later implemented it for OpenGL. 

Leaving open since it's not implemented for all backends, but bumping to 1.8 (at least).

**Comment by Panderner** [comment]
But how about OpenGL label?

**Comment by hrydgard** [comment]
The faster depal implementation is done for OpenGL. It's however not fully utilized yet to fix the perf in these games (by reordering render passes) so yeah, I suppose it should be added.

**Comment by Panderner** [comment]
Did Rock Band Unplugged use Depal?

**Comment by Gamemulatorer** [comment]
Sonic Rivals running smooth on my Redmi Note 9 both VK and OpenGL.
![Screenshot_2021-05-03-02-26-12-173_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/116823425-0c614c00-abb7-11eb-92bc-dd71a1538244.jpg)
![Screenshot_2021-05-03-02-26-07-803_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/116823428-12572d00-abb7-11eb-89e6-d0240221652d.jpg)
![Screenshot_2021-05-03-02-25-39-953_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/116823430-15eab400-abb7-11eb-86df-5b9e50ffb6f5.jpg)

**Comment by Gamemulatorer** [comment]
https://github.com/hrydgard/ppsspp/issues/8390#issuecomment-1467699268 this is belong this?

**Comment by hrydgard** [comment]
This is implemented in all backends that can reasonably implement it. Closing.
