### ISSUE TITLE
How to improve FPS On ppsspp?

### ISSUE THREAD

**Issue by CYH1996** [hrydgard/ppsspp#10904]
I just downloaded  gundam vs gundam and it very lag, the fps run like 6 to 12. Anyway to fix this issue?
The  phone I using is Huawei Y7 Prime.Sorry for bad English

**Comment by hrydgard** [comment]
You got unlucky and chose one of the slowest games to run in PPSSPP, due to its strange method of drawing stuff. You'll find that most other games will probably run okay on that device.

See #1319 if you care about the details.

**Comment by marosis** [comment]
Try need for speed most wanted 5.1.0, Cal of Duty roads to Victory, Micromachines V4, Assassin's creed Bloodlines, God of War and more...

**Comment by marosis** [comment]
For better FPS and speed off Simulate block transfler effects and set Emulated CPU clocks to 60MHZ. But some games for runnig need have 222MHZ(like Tekken 6)
