### ISSUE TITLE
Metal Gear Acid 2 Graphical Glitch Only in Vulkan Mode

### ISSUE THREAD

**Issue by TideGear** [hrydgard/ppsspp#10905]
I'm playing GIT v1.5.4-889-g26f5b5b93 on a Galaxy S9+. Here's a missing-graphics glitch in Metal Gear Acid 2 that only appears in Vulkan mode...
![ulus10077_1 00_0](https://user-images.githubusercontent.com/16357059/38667765-1c70ffa4-3df7-11e8-97d0-dc04094951b2.jpg)
...That background shouldn't just be green. Snake should be there. If you switch from Vulkan to OpenGL, then the graphics appear as they should.

The savestate below is right where the glitch happens...
[MGA2 Vulkan Only Glitch.zip](https://github.com/hrydgard/ppsspp/files/1902293/MGA2.Vulkan.Only.Glitch.zip)

**Comment by hrydgard** [comment]
Appears to be some kind of depth clipping issue, some wall is drawn very close to the camera covering everything.

**Comment by weihuoya** [comment]
a spline draw is wrong, weird

**Comment by hrydgard** [comment]
The question is why it's wrong only in Vulkan. And also why this game is using so damn many splines, and such a silly method for color correction (similar to Sonic Rivals, slowing things down a lot). Should really make a solution for that at some point...

**Comment by weihuoya** [comment]
It seems like the latest code fixes the problem, test by android

**Comment by weihuoya** [comment]
Xiaomi MIX2 and S7 edge don't has this problem, but my PC has this problem

**Comment by TideGear** [comment]
I found another occurrence of this...
![ulus10077_1 00_3](https://user-images.githubusercontent.com/16357059/38775943-573484dc-4043-11e8-910d-41296e075ca7.jpg)

[Another Vulkan Only Blocked Camera.zip](https://github.com/hrydgard/ppsspp/files/1911813/Another.Vulkan.Only.Blocked.Camera.zip)

I was using v1.5.4-913-gfb377b0b8 with this one.

**Comment by TideGear** [comment]
And another? This time with a weird blackout effect (e.g. barrels). Aim around to the different targets to see...

[Another Vulkan-Only With Weird Effect.zip](https://github.com/hrydgard/ppsspp/files/1911883/Another.Vulkan-Only.With.Weird.Effect.zip)

**Comment by TideGear** [comment]
P.S. Ignore the white stuff. Snake got blasted with a fire extinguisher explosion.

**Comment by TideGear** [comment]
Yet another...
[Yet Another.zip](https://github.com/hrydgard/ppsspp/files/1911915/Yet.Another.zip)

I probably will stop uploading these for this issue unless you want them. It's becoming clear it's a Vulkan issue.

**Comment by TideGear** [comment]
Only found one tonight, so aim might as well upload it...
[And Yet Another.zip](https://github.com/hrydgard/ppsspp/files/1914439/And.Yet.Another.zip)

**Comment by TideGear** [comment]
Just FYI, I'm continuing to get these camera blockages only on vulkan. I'm just not bothering posting any more savestates since they're probably all the same issue.

**Comment by hrydgard** [comment]
Yeah, no need for more, thanks :)

**Comment by unknownbrackets** [comment]
Could you try exporting a GE debugger dump on PC?

To do this, open the game and select Debug -> GE debugger..., then when it's displaying the scene, press Record in the top right.  After a second or so, it'll finish and save a trace of the drawing activity.

After that, check the memstick/PSP/SYSTEM/DUMP folder and it'll have created a file named something like "ULES12345_0000.ppdmp".  You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by TideGear** [comment]
@unknownbrackets I just loaded this savestate in v1.6.3-485-gc69e4261d on both Android and PC, and the issue seems to be gone! Apparently it was fixed by an update at some point. However, I haven't done extensive testing.

**Comment by hrydgard** [comment]
That's great! Would be good to know what fixed it, but I'm still gonna close the issue.

**Comment by unknownbrackets** [comment]
Maybe this was that depth clamping thing, even.

-[Unknown]

**Comment by TideGear** [comment]
I tested my four other savestates, and they were fixed too. Looks like we're good!
