### ISSUE TITLE
[Android] Vulkan memory leak

### ISSUE THREAD

**Issue by leopard20** [hrydgard/ppsspp#10907]
Reproduction steps:
1. Run a 3D game.
2. Without pausing the app, keep switching back and forth from recents (or home or another app) to PPSSPP.

I think it's the same as https://github.com/hrydgard/ppsspp/issues/10850.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Android 7.0

**Comment by hrydgard** [comment]
This is similar enough to #10850 to keep them together in one issue. If you found that one, why did you create this one instead of posting a message there? :)  I see all messages.

Closing as duplicate of #10850.

**Comment by leopard20** [comment]
Good point. Moving it there
