### ISSUE TITLE
Naruto Ultimate Ninja Heroes 3 not working for IOS!!

### ISSUE THREAD

**Issue by D3shly** [hrydgard/ppsspp#10900]
What happens?
Whenever I start up the game, they play the intros of the companies that made the game, then it just shows a black screen and nothing happens after.

What *should* happen?
After the intros, the game should automatically begin.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
I am running PPSSPP v1.5.4-336-ga989b4a93 on iOS 11.

**Comment by D3shly** [comment]
bump

**Comment by Jinzombie** [comment]
This issue is the same as #9591 ?

**Comment by D3shly** [comment]
I still don't get how I am supposed to fix this

**Comment by D3shly** [comment]
Plus, none of these were actually on iOS

**Comment by hrydgard** [comment]
I think those issues indicate that this issue is not specific to iOS in any way, but instead is a more generic type of bug.

**Comment by D3shly** [comment]
Yes, but there are no direct steps to solving this problem, so I am really lost on what to do.

**Comment by D3shly** [comment]
P.S. I'm also a swede. :P

**Comment by Jinzombie** [comment]
@D3shly Try to use the "Skip-intro movie" cheat code in #9591 I use that and it's work in the latest build atleast 😅

*Sorry for my bad english ✌

**Comment by D3shly** [comment]
Where do I type cheat codes? @Jinzombie

**Comment by Jinzombie** [comment]
@D3shly First copy the cheat code that you will find in #9591 after that go to your file manager locate the PSP folder then open it you will see a Cheat folder open it again then you will see a file ini that name ULUS10518.ini for US version ULES01407.ini for Europe Paste it inside.
2nd enable the cheat in ppsspp system done 👍
*Nosebleed 😲 Sorry for my wrong english 😅

**Comment by D3shly** [comment]
@Jinzombie is this the method to fixing it on iOS?
Sorry for the amount of questions I'm asking, I just really want it to work so I can play it at school when I have breaks cause they're awfully boring.

**Comment by D3shly** [comment]
Bump

**Comment by samuelguebo** [comment]
@Emulatorer's method works like a charm. Here is a slightly different variant that worked on MacOs.

- Enable cheat code in Settings > System > Enable cheat
- Create a `Cheats` directory in `~/.config/ppsspp/PSP`
- Launch the game until that black screen of death and quit the emulator
- A new file will be created within the `Cheats` directory: ULUS10518.ini for US version ULES01407.ini for Europe 
- Copy the cheat code from #9591 and paste it inside the .ini file.
- Launch again the emulator, start the game and enjoy.
