### ISSUE TITLE
Play Store version not saving settings

### ISSUE THREAD

**Issue by GuilhermeGS2** [hrydgard/ppsspp#10903]
I downloaded the Play Store version on a friend's phone and even giving PPSSPP permission, the settings aren't saved, the same happened when I downloaded it using Bluestacks (I'm using the BETA with Nougat, but my friend's phone uses Marshmallow). Aparently the latest build is working fine on both. I don't know if you devs are awere of this issue, but this might be a problem for new users.

**Comment by leopard20** [comment]
I think this was already fixed.

**Comment by hrydgard** [comment]
Yeah, this should be solved by the 1.6 release to Play Store when it happens.
