### ISSUE TITLE
Platypus freezes

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#10919]
The game Stucks at loading screen

**Comment by unknownbrackets** [comment]
Other people say it runs okay, by the way:
http://report.ppsspp.org/games?name=platypus

-[Unknown]

**Comment by unknownbrackets** [comment]
It's marked in game and 3 stars for graphics and gameplay, though, so guessing it didn't hang at the menu for them.  Maybe they just didn't test the whole game.

-[Unknown]

**Comment by Panderner** [comment]
Yes

**Comment by TehPlayer14** [comment]
I've played platypus hold on and it booted and worked just fine

**Comment by hrydgard** [comment]
Broken ISO?

**Comment by leopard20** [comment]
Could be. 
The game's compressed iso is only 40~50 MBs on ROM sites so maybe someone could grab and test it.

**Comment by Panderner** [comment]
No

**Comment by Panderner** [comment]
It stuck at loading screen

**Comment by Panderner** [comment]
Thanks

**Comment by unknownbrackets** [comment]
Wait, did it start working?

-[Unknown]

**Comment by Panderner** [comment]
Yes but it's stays 5 fps at loading screen and boots

**Comment by TehPlayer14** [comment]
Shouldn't this be closed?

**Comment by crazyrexz** [comment]
it boots on 1.7.1, but not respond at  low fps

**Comment by TehPlayer14** [comment]
Can somebody else test this?

Perhaps it's just device specific

**Comment by crazyrexz** [comment]
to be specific, my device is snapdragon 625 oreo 8.1.0 ,  tested on vulkan open gl , still black screen, also tested ducati challenge getting slow fps

**Comment by hrydgard** [comment]
How is this on the latest builds now, any changes?

**Comment by Panderner** [comment]
Loading screen is too long on 222 MHz. When underclock it faster loading
it's playable

**Comment by crazyrexz** [comment]
following setting like @Panderner mention, confirmed it works , use USA version. so burnout that left slow right now on sun shines in the morning :)

**Comment by crazyrexz** [comment]
forgot to mention, the loading is the culprit, need to fast forward to make it quick to main menu

**Comment by Panderner** [comment]
Underclocking the psp cpu makes game load faster
