### ISSUE TITLE
Sustained performance mode... unsupported?

### ISSUE THREAD

**Issue by leopard20** [hrydgard/ppsspp#10913]
What happens?
My device is running on Android 7.0 but in PPSSPP system info it says Sustained perf mode is not supported. Is it a PPSSPP bug?
Does it mean even if I enable it manually through ppsspp.ini, it won't be activated? Also, if enabled, does it give me more battery life and/or less overheating? 

What *should* happen?
Android 7.0 should inherently have that ability.

**Comment by LunaMoo** [comment]
Android version "supporting" some feature doesn't mean your device running that version of the OS will have it. It's for each vendor to implement new technology/feature to work on their exact hardware and many will not do that especially on tight budget.

 PPSSPP has nothing to do about it, so I'm closing this as a non issue.
