### ISSUE TITLE
[Vulkan] Audio sync issue

### ISSUE THREAD

**Issue by leopard20** [hrydgard/ppsspp#10929]
What happens?
I sometimes get occasional slow downs when audio falls out of sync (Vulkan only). They generally happen in two ways:
1. The game stutters for like a second or two and the sound loops for that period. It's very infrequent and some games I played didn't have this issue at all (e.g MHFU). Sometimes I can play for like 20 minutes without problems, and sometimes the issue appears within 5 minutes of playing a game. (in case of MHFU, I've played for nearly 2 hrs without encountering any issue)

2. Audio falls out of sync but fails to resync and the game stutters forever. The only solution is to restart the game.

At first I thought maybe they happen because of thermal throttling (the symptoms are similar) but I made some tests while recording my CPU temperature and  its max clock speed. And it wasn't because of that.

Some games that have this issue (mostly games that play songs one after the other):
Tekken 6 (the issue happens a lot in this game)
NFS Underground and Carbon
Burnout Dominator
Project Diva 2nd and Extend.

I don't remember noticing these issues in v1.5.4 (but not 100% sure).

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Android 7.0
Snapdragon 821

**Comment by RaduNastase** [comment]
Yes. I have more or less the same symptoms with audio. Quite frequent in latest builds. Nothing to do with thermal throttling. I have a rooted phone and tested multiple Cpu/Gpu clocks and governors while monitoring temperature.

Version 1.3 was the last one without audio issues for me.

**Comment by hrydgard** [comment]
That is really odd, never seen anything like this. I assume Vulkan vs OpenGL doesn't make a difference?

**Comment by leopard20** [comment]
Actually I just made some tests using OpenGL. It is remarkably better (tested for 15 minutes without finding any issue in Tekken 6, which as I said is plagued by that issue)

**Comment by hrydgard** [comment]
Maybe on this particular device, heh. There are still some rather immature Vulkan drivers out there for sure, I think we'll have to chalk this one up to those, for me it runs great...

**Comment by leopard20** [comment]
You mean all games run great without any issues for you?! Did you even test Tekken 6?

**Comment by RaduNastase** [comment]
Ogl for me and i have random and frequent stutters and clicks.

**Comment by hrydgard** [comment]
I played Tekken for some minutes on my S8+ (international) without issues a few days ago..

**Comment by leopard20** [comment]
Huh. Then maybe it's a problem with Qualcomm drivers?

**Comment by leopard20** [comment]
Interesting. I tested Vulkan without unthrottling the game at any point. No issue occurred. Maybe I was right?

**Comment by hrydgard** [comment]
Yeah, I don't even know where to start...

**Comment by leopard20** [comment]
Well I just got a conflicting result from another test I did. I switched to Vulkan again, but after 30 minutes I haven't gotten this issue. The only option that I've changed since last time is HW Tessellation. But I really don't think it should've had much impact (at least on audio) 
Speaking of which, is HW tessellation faster or slower?

**Comment by hrydgard** [comment]
Depends on the game and the balance between the power of your CPU and GPU, and how games use the feature, but HW should normally be faster. Most games don't even use tesselation at all, Tekken 6 doesn't for example.

**Comment by leopard20** [comment]
Regarding battery usage it appears I was wrong. Both use exactly the same amount of battery. 
But still OpenGL performs better in terms of audio. Performance is nearly the same in all games. 
When I looked at my CPU usage more carefully, it seemed Vulkan never used too high clock speeds (mostly under 50 percent usage),  but OpenGL occasionally reached ~70% or even higher. Maybe the real reason here is that Vulkan doesn't adjust the clock speed too well.

**Comment by leopard20** [comment]
Gonna close till I find the culprit for this.

**Comment by unknownbrackets** [comment]
It could just be that OpenGL is more demanding, and so your operating system is deciding to keep the CPU clocked higher.

Mobile power management is this ironic space like division budgeting: if your budget for 1 year is 5000 EUR, and you only spend 4000 EUR, your budget next year will be 4000 EUR.  That means a wasteful division can have more funds than an efficient division and therefore handle unexpected situations better.

See here for another explanation of power management:
https://github.com/hrydgard/ppsspp/issues/10607#issuecomment-375843042

That means the issue here COULD be that we're spiking at some point and using more CPU usage, and on Vulkan the same spike is a bigger change from "situation normal" than on OpenGL.  The actual difference in battery usage might not be significant, depending on how aggressive your device's power throttling is.

-[Unknown]

**Comment by leopard20** [comment]
@hrydgard @unknownbrackets
I figured out what the issue was. It was because of Vulkan CPU usage being lower + my CPU governor not adjusting the clock speed accordingly (my governor targetload setting had a wide gap between two different loads, which caused my CPU to be underclocked for a load between the two).
