### ISSUE TITLE
naruto shippuden ultimate ninja heroes 3 stuck issue

### ISSUE THREAD

**Issue by joelolopez** [hrydgard/ppsspp#10926]
after the 2 intro logos the game stuck , tested it using opengl and vulkan.. no frame skip applied.. other fighting games are working smoothly but i cant believe this one is getting this kind of problem

the game title should appear after the intro logos

OS android 7.0 , Octa-core, 2360 MHz, ARM Cortex-A53, 64-bit, 16 nm , Mali-T830 MP2 , 4 GB RAM

**Comment by Jinzombie** [comment]
This is a duplicate issue of #9591
