### ISSUE TITLE
[Asking] ) Sorry for this non issue topic but I badly need this in our ppsspp fb group

### ISSUE THREAD

**Issue by Jinzombie** [hrydgard/ppsspp#10924]
What happens? Can you guys list the games that still unplayable in ppsspp so that we could avoid them to download. Thank You In Advanced for anyone could give me the list ☺

What *should* happen?

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

**Comment by hrydgard** [comment]
There is no such official list, if you want one, make it yourself. And no talking about downloading games in the issue tracker please.

**Comment by Jinzombie** [comment]
OK Sir

**Comment by unknownbrackets** [comment]
Some of these games are potentially unplayable (possibly only with bad settings):
http://report.ppsspp.org/games?compat=none

-[Unknown]

**Comment by Jinzombie** [comment]
@unknownbrackets Thank you so much Sir I really appreciate it 😇

**Comment by hrydgard** [comment]
Oh, right, I keep forgetting what our reporting server can do..
