### ISSUE TITLE
simulate block transfer so slow

### ISSUE THREAD

**Issue by joelolopez** [hrydgard/ppsspp#10927]
im having display issues with naruto ultmate ninja impact, "character portrait background" at the upper leftmost of the screen is displaying black.. in order to display this correctly i have to enable simulate block transfer but the thing is it really slows down the game even if im using vulkan backend.. is there anyway you can fix this minor diplay issues without sacrificing the overall game speed

OS android 7.0 , Octa-core, 2360 MHz, ARM Cortex-A53, 64-bit, 16 nm , Mali-T830 MP2 , 4 GB RAM

**Comment by slikk66** [comment]
You guys are geniuses.  I'm sure you can speed it up somehow!  I recently found and downloaded PPSSPP solely to play the Open Tee (everybody's golf) games.  I still have my hacked original PSP-1000 at home, but being able to play them on my phone would be amazing, such great games.  Unfortunately, both version 1 and version 2 of the game suffer from the "simulate block transfer" issues.  With it off, the game works perfectly until you go to strike the golf ball, which as you can imagine is important in a golf game.  If you put it on, it mostly works, but at a slow stuttering speed (samsung note8) which also makes it pretty much unplayable.  On the green to putt it's even worse.  Quite a shame!  Such a great emulator but I'm sure you could make some strides here to improve it.

THANKS!

**Comment by Gamemulatorer** [comment]
Simulate Block Transfer Effects is optimize now on the latest version of ppsspp on playstore v1.11.3
Tried and tested on Naruto Shippuden Ultimate Ninja Impact both OpenGL and Vulkan run at full speed
![Screenshot_2021-05-18-00-18-49-627_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/118522630-dacbb180-b76e-11eb-95e0-afdf1799536a.jpg)
![Screenshot_2021-05-18-00-18-41-374_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/118522644-ddc6a200-b76e-11eb-85cb-e1aba10ed3cc.jpg)
(60fps cheats code is on 😅)

**Comment by Panderner** [comment]
> Simulate Block Transfer Effects is optimize now on the latest version of ppsspp on playstore v1.11.3
> Tried and tested on Naruto Shippuden Ultimate Ninja Impact both OpenGL and Vulkan run at full speed
> ![Screenshot_2021-05-18-00-18-49-627_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/118522630-dacbb180-b76e-11eb-95e0-afdf1799536a.jpg)
> ![Screenshot_2021-05-18-00-18-41-374_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/118522644-ddc6a200-b76e-11eb-85cb-e1aba10ed3cc.jpg)
> (60fps cheats code is on 😅)
> 
> My phone is Redmi Note 9 4/128

@Gamemulatorer this is why I enabled BlockTransferAllowCreateFB for Ultimate Ninja Impact via #13821. When I set the game ID to false in BlockTransferAllowCreateFB it will run horribly slow.

**Comment by Gamemulatorer** [comment]
> @Gamemulatorer this is why I enabled BlockTransferAllowCreateFB for Ultimate Ninja Impact via #13821. When I set the game ID to false in BlockTransferAllowCreateFB it will run horribly slow.

But this game is still lag on low - entry level phone when set to buffered rendering + block transfer effect is on

**Comment by ResurrectionRedmi9** [comment]
This still an issue? there's a lot of improvement now on ppsspp latest github also if your phone support vulkan you must enable it to avoid slow performance using SBTE @joelolopez

**Comment by Gamemulatorer** [comment]
This should be closed long ago since https://github.com/hrydgard/ppsspp/pull/13821 https://github.com/hrydgard/ppsspp/pull/11531
