### ISSUE TITLE
feature request: quick snapshot (like speed toggle button)

### ISSUE THREAD

**Issue by joelolopez** [hrydgard/ppsspp#10937]
i would like to request a button for quick snapshot of he game coz when im using my phone's snapshot there always a 1-2 secs delay.. thats why i cant capture the exact moment of my desired scenario of the game.

What *should* happen?

OS android 7.0 , Octa-core, 2360 MHz, ARM Cortex-A53, 64-bit, 16 nm , Mali-T830 MP2 , 4 GB RAM

**Comment by leopard20** [comment]
It's a duplicate request.

**Comment by LunaMoo** [comment]
As mentioned it's a duplicate(of #10762), closing.
