### ISSUE TITLE
application closes by itself

### ISSUE THREAD

**Issue by joelolopez** [hrydgard/ppsspp#10936]
there are sometime that when im playing a game, the application closes by itself

What *should* happen?

OS android 7.0 , Octa-core, 2360 MHz, ARM Cortex-A53, 64-bit, 16 nm , Mali-T830 MP2 , 4 GB RAM

**Comment by hrydgard** [comment]
Which games?

**Comment by joelolopez** [comment]
star ocean 2nd evolution, sol trigger english patched, marvel ultimate alliance 2 .. i cant recall which of these games ,but these are the games i recently played.

**Comment by unknownbrackets** [comment]
Does this still happen in 1.6.0 / the latest git builds?

Can you include an adb logcat?  Google for that for more information on what it means.

-[Unknown]

**Comment by joelolopez** [comment]
Please close this one its already fixed

**Comment by unknownbrackets** [comment]
Glad to hear.

-[Unknown]
