### ISSUE TITLE
Prince of Persia Rival swords black screen

### ISSUE THREAD

**Issue by greedy12** [hrydgard/ppsspp#10938]
blackscreen ingame  please fix
My device spec
Ram 1gb
Mali 450

**Comment by leopard20** [comment]
If your phone supports the Vulkan backend (though I doubt it) you can use that for now. 
It's a duplicate.

**Comment by greedy12** [comment]
My phone does not supported by vulkan Is there any other solution?
On Apr 19, 2018 1:48 PM, "Leo" <notifications@github.com> wrote:
>
> If your phone supports the Vulkan backend (though I doubt it) you can use
that for now

**Comment by lim2222** [comment]
Try the old version of ppsspp v1.0.1,install with app cloner,this is the way to keep both new and old version  parallelly.

**Comment by Jinzombie** [comment]
duplicate issue of #3723
