### ISSUE TITLE
UWP Build Issues

### ISSUE THREAD

**Issue by b33tlejuice** [hrydgard/ppsspp#10946]
Getting an error while compiling Gold uwp, the 310x150 img kicks back an error for actually being 291x141
and an error for the store logo in the manifest (not part of the payload)

Also have an expired certificate going on, not sure when it expired but it is over a year old now.

I handled all this locally, not sure if you want me to commit nor how to lol (kinda new to this whole github thing)

**Comment by hrydgard** [comment]
Merged your pull request so I guess we can close.
