### ISSUE TITLE
Rerun game in ppsspp, game will slow down

### ISSUE THREAD

**Issue by weihuoya** [hrydgard/ppsspp#10940]
What happens?
start ppsspp, Sonic 2  will run nearly 30 fps
![screen0](https://user-images.githubusercontent.com/3827333/39033621-85d52c4a-44a5-11e8-90bb-df5585e9d119.jpg)

exit to menu, restart Sonic 2 will run nearly 21fps
![screen1](https://user-images.githubusercontent.com/3827333/39033624-8a2b2d30-44a5-11e8-9896-38f1d2f49a58.jpg)

full exit ppsspp, Sonic 2  will run nearly 30 fps

killzone has this issuse, too.
s7edge, 820

**Comment by weihuoya** [comment]
GPU can't always running at the max frequency, phone getting heated-up during usage, and then slow down.

**Comment by leopard20** [comment]
@weihuoya If you're into modding and have a rooted phone, you can tweak your governor settings and increase the thermal limits of your phone (or reduce the amount of throttling) to avoid the issue. I did the same thing on my phone too! Now games run as smooth as butter and my phone is only slightly warmer. My phone is Xiaomi Mi 5s Plus which has the same chipset as yours!

**Comment by weihuoya** [comment]
nice, custom Rom can do a lot of things, like rm thermal engine.

**Comment by weihuoya** [comment]
no,thanks. root has a lot of drawbacks for Samsung phone, Samsung pay will not usable anymore. Samsung is not open as Xiaomi.

**Comment by leopard20** [comment]
Oh. I thought these services didn't work in China! Sorry. My bad.
