### ISSUE TITLE
Vulkan no longer detected on Android 8.0

### ISSUE THREAD

**Issue by YvanDroid** [hrydgard/ppsspp#10955]
Selecting the Vulkan renderer option in PPSSPP settings causes the device not supported error, even though the system used to support it before, It has happened either after the android update that rolled out on my device, causing the new renderer to have issues (switching renderers in developer options has no difference). I also recieved an update on the Google Play Store before the issue as well.

The Vulkan renderer should be selected with no errors as the GPU is supported for the Vulkan API

Operating System: Android 8.0 (Oreo)
Hardware: Mediatek Helio P20 and Mali T880 GPU
PPSSPP version: 1.5.4 Gold Official Release.

**Comment by YvanDroid** [comment]
The phone that I'm running PPSSPP on is a G3121 Xperia XA1

**Comment by LunaMoo** [comment]
From the amount of complains with Oreo about this device over the net for example [here](https://talk.sonymobile.com/t5/Xperia-XA1/bd-p/xperia-xa1), it's probably a problem with your update and not a PPSSPP issue.

**Comment by YvanDroid** [comment]
Thank you for the insight. This update has been more problematic than helpful and I might downgrade back to 7.0 until the problems are fixed.

**Comment by unknownbrackets** [comment]
If you can grab the adb logcat output, we might be able to see more detail on why it's failing.

-[Unknown]

**Comment by YvanDroid** [comment]
How does go about that? I've searched it up on the internet but the methods I've tried just output everything anyway

**Comment by leopard20** [comment]
@YvanDroid
You can confirm if your OS supports Vulkan globally by using an app called "Vulkan Caps Viewer". You can download it for free from Google Play.
If that app says your device doesn't support Vulkan, there's nothing the PPSSPP team can do about it. It leaves you no choice but to downgrade.

**Comment by leopard20** [comment]
Here's the link:
https://play.google.com/store/apps/details?id=de.saschawillems.vulkancapsviewer&hl=en&referrer=utm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_term%3Dvulkan+caps+viewer+app
