### ISSUE TITLE
POP The Forgotten Sands Black Floor

### ISSUE THREAD

**Issue by Rafidmuhaiminwafi** [hrydgard/ppsspp#10958]
In Pop The Forgotten Sands, the floors are full black. But I think this floor shouldn't be black, also in some parts of game floors are normal. I'm using OpenGL.
Intel 5010U 2.10 GHz
4GB Ram
Intel HD Graphics 5500(300-850 MHz 1.7GB Graphics)

**Comment by Rafidmuhaiminwafi** [comment]
Okay. It is solved. I select buffered rendering mode and black floors are gone.

**Comment by unknownbrackets** [comment]
Yeah, "skip buffer effects" makes PPSSPP ignore the game when it tries to use buffers.  This is faster, but has lots of graphical issues.

-[Unknown]
