### ISSUE TITLE
PPSSPP Runs but window wont show

### ISSUE THREAD

**Issue by vivimarthy** [hrydgard/ppsspp#10959]
Hi!

I've been using version 1.5.4 and it has been working properly and then when I tried to run PPSSPP, the initial PPSSPP window wont appear. I checked my task manager and it says it's running the app but I just dont see the window. I tried installing v 1.5.4-933 thinking it could just be an update thing and it worked again but when I wanted to play earlier I encountered the same problem. The PPSSPP menu wont show but my task manager is saying it's running.

I tried looking for posts who have similar problems and most of them would say it could be a disk drive update thing but my disk drives are all up to date and working properly.

Here are my specs :)

OS Name	Microsoft Windows 10 Home Single Language
Version	10.0.16299 Build 16299
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	DESKTOP-1E46AK9
System Manufacturer	ASUSTeK COMPUTER INC.
System Model	X456UQ
System Type	x64-based PC
System SKU	ASUS-NotebookSKU
Processor	Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz, 2400 Mhz, 2 Core(s), 4 Logical Processor(s)
BIOS Version/Date	American Megatrends Inc. X456UQ.202, 15/02/2016
SMBIOS Version	3.0
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	ASUSTeK COMPUTER INC.

Hope you can help me with this :)

Thank you!

**Comment by vivimarthy** [comment]
Thank you very much for this! The ALT+ENTER worked :P

**Comment by unknownbrackets** [comment]
Does it work normally now, or does it only work when full screen?

Which graphics backend are you using (you can now just check this in the settings normally)?

-[Unknown]

**Comment by unknownbrackets** [comment]
Is this working better with the latest git builds?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
