### ISSUE TITLE
[Request] Disable screen sleep prevention while in PPSSPP menu or when game is paused on Android

### ISSUE THREAD

**Issue by leopard20** [hrydgard/ppsspp#10968]
I don't know why you should prevent the phone from turning off the screen when you're in the menu.
After exiting a game, I left my phone for 7 hours thinking it would automatically turn off but it didn't. Definitely not good. 
I'm not sure if turning the screen off when game is paused is liked by everyone (not to mention possible issues, such as screen aspect ratio problem and maybe crashes and memory leaks) so maybe you should add a toggle-able option for that. But I'm ready to bet no one likes the first case (in menu) so you can disable it safely!

**Comment by hrydgard** [comment]
I don't think it's likely that your phone got hurt by that, but I wasn't aware that we even do any kind of sleep prevention on Android. You sure it's not just that you had the USB cable plugged, and the developer setting to always keep the screen on?

**Comment by leopard20** [comment]
I had left my phone plugged in, which, with the screen on, probably caused the battery to keep draining and then topping up over and over. That's not good for the battery! 

And no, I don't use that option from devs menu.

Besides, if you didn't use screen prevention, then the screen would turn off when you left the phone for like a minute (assuming you haven't set the timer too high in Display Settings).

**Comment by hrydgard** [comment]
Did you see the battery level drop and go up again? Just sitting at 100% powered by USB and being used is not at all harmful for the battery.

Can't find any code that tries to keep us awake on Android but maybe it's some API I've forgotten about..

**Comment by leopard20** [comment]
Well, I'm just assuming that's what happens "under the hood"! But no, my power settings don't show any drop. 

There has to be something you use, otherwise the screen would turn off. 
I thing you're a member of Dolphin Emu team right?  Their emulator doesn't have this problem, so you might wanna ask them if you don't know the cause.

**Comment by leopard20** [comment]
BTW, how's v1.6 coming along? I figured it'd be released by now. But you've been "quite" lately! Busy with life stuff?!

**Comment by leopard20** [comment]
@hrydgard 
Maybe you should use something not not use something! 😉

**Comment by unknownbrackets** [comment]
@hrydgard, this is where we do it, right?

https://github.com/hrydgard/ppsspp/blob/19ddeea8ee49eeb592651f9d6e35f97ed52863ab/android/src/org/ppsspp/ppsspp/NativeActivity.java#L481

-[Unknown]

**Comment by hrydgard** [comment]
Oh! I searched the code for so many synonyms to sleep and hibernation :/

I'll get this fixed soon..

**Comment by leopard20** [comment]
@hrydgard 
As you know the screen-off process happens in two steps on most Android devices. First the display is dimmed, then after a few seconds it turns off completely.
I was wondering if it is possible to keep the screen in its dimmed state using some sort of code. It would be very useful for the case where the game is paused! This way you can avoid possible issues with app-switching while also reducing unnecessary battery consumption.

**Comment by hrydgard** [comment]
I don't know. I'm just going to turn off sleep prevention when in the menu, as suggested.

**Comment by leopard20** [comment]
Is there still room for improvement or should I close this?

**Comment by leopard20** [comment]
?

**Comment by unknownbrackets** [comment]
Hm.  We could adjust screenBrightness manually, maybe, but I'd be worried about that.  Some games have movies, etc... I hate when my screen dims or turns off while I'm watching a cutscene.

If this is dimming in UI now I think that's pretty good.

-[Unknown]

**Comment by leopard20** [comment]
> If this is dimming in UI now I think that's pretty good.
-[Unknown]

That's more or less what I mean.
To be more accurate what I mean is when you pause the game (via PPSSPP, not the game pause menu or sth like that), the screen should be allowed to be dimmed in case somebody leaves their phone on, but at the same time do not allow it to be turned off completely to avoid issues (e.g PPSSPP bugs and also some ROMs clear RAM when screen is off)

But preferably do not adjust the brightness manually because that could cause problems too (e.g if the app is closed unexpectedly, the brightness might not return to its previous state)

**Comment by hrydgard** [comment]
Yeah, I think we're done here for now.

**Comment by leopard20** [comment]
@hrydgard 
Nothing to be alarmed about (!), but right now the screen also turns off when the game is paused!

**Comment by hrydgard** [comment]
Well, that's just the next step of dimming... I think that's working as intended.

**Comment by leopard20** [comment]
I thought you said you didn't want the screen to turn off right now to prevent app-switching issues?!
