### ISSUE TITLE
Possible input bug (needs testing on PSP) 

### ISSUE THREAD

**Issue by leopard20** [hrydgard/ppsspp#10963]
In Tekken 6, when I hold down, say the down ⬇ button and then press X, I can see three ⬇ inputs. It's almost as if when I press X, the ⬇ button gets released for a fraction of a second, then reapplied. 
![screenshot_2018-04-25-18-00-58-281_org ppsspp ppsspp](https://user-images.githubusercontent.com/16115820/39249350-b28fe56a-48b3-11e8-941e-cbd57b0dea9c.png)

I'm not 100% sure if this is a problem with the game or PPSSPP, because I've never played the game before on the PSP. I was wondering if someone could test it on the real hardware to make sure.

**Comment by marosis** [comment]
Leopard20 i can And i Will try it😉

**Comment by marosis** [comment]
Can you write me that combo

**Comment by leopard20** [comment]
Thanks! 
It's not a combo! Just hold the down ⬇ button, and without releasing it, press X. 
Also turn on command history from practice settings to see the buttons recorded by the game (like the bottom of this screenshot). See if you get three ⬇ like the screenshot or just one.

**Comment by marosis** [comment]
Here is problem, you must be really fast to do it. It is hard on PSP too

**Comment by marosis** [comment]
Tekken in this is really bad😥

**Comment by leopard20** [comment]
Hm, that's not what I was looking for! 
I'm not pressing ⬇ three times (nor do I want to!)
The game should (if it's a PPSSPP bug) **show only one ⬇**, **not three** because I'm **holding** the button, not tapping it.

**Comment by LunaMoo** [comment]
That's not an emulation issue, that's how hit history works in fighting games and it doesn't show that you're pressing button 3 times, but that it was pressed at action 1, was still pressed at action 2 and keeps being pressed when the action 2 get's released. Basically each change is a new action, but all buttons that are hold during, will still show up.
 Closing.

**Comment by leopard20** [comment]
Ok. Thanks for confirming.
