### ISSUE TITLE
dust effect displays green triangular shapes issue

### ISSUE THREAD

**Issue by joelolopez** [hrydgard/ppsspp#10969]
im playing this Brave story new traveler game using vulkan backend when i notice that the dust effects displays wrong images (green triangular shapes) 

![1](https://user-images.githubusercontent.com/5791856/39340167-3e8a7e44-49ff-11e8-97fe-371b6ca170d9.png)

OS android 7.0 , Octa-core, 2360 MHz, ARM Cortex-A53, 64-bit, 16 nm , Mali-T830 MP2 , 4 GB RAM

**Comment by leopard20** [comment]
Did you try changing the options? Like disabling the stencil test?

**Comment by joelolopez** [comment]
yup i tested it and still displaying the same image

**Comment by unknownbrackets** [comment]
If I remember correctly, this is rendered using flat shading.  It might be impacted in some way by render-to-CLUT, though.

Stencil test won't help.  Does this happen with both OpenGL and Vulkan?

If it happens with OpenGL, did it work in v1.5.4?  Is it broken in the latest git build?

-[Unknown]

**Comment by joelolopez** [comment]
this only happen with vulkan

**Comment by unknownbrackets** [comment]
In this specific case it's a triangle strip.  Really, the first two colors are garbage, it's correct after that.

Always software transforming flat really doesn't sound too terrible to me.  They're pretty infrequent, although I could imagine finding some crazy game that uses flat for complicated many-vertex shape rendering or something...

-[Unknown]
