### ISSUE TITLE
Moh fps drop 

### ISSUE THREAD

**Issue by fahadfoyjur** [hrydgard/ppsspp#10965]

**Comment by Jinzombie** [comment]
I can play that game running at 20-30 fps 80-100% speed my phone gpu is Mali-450 MP @1.4ghz.
Here's my settings
Buffered Rendering
Frameskipping off or X1
Auto Frameskipping is on
Alternative Speed unlimited
Rendering resolution 1X
Display resolution 2X
Lazy Textures Cache ON
Disable Slower Effects ON
Timer Hack ON
Disable Stencil ON
Emulated CPU ClockSpeed 33
that's all just try it 👍

**Comment by marosis** [comment]
FPS drop in some places is normal. Somewhere can be a lot of textures, effects..., This is why FPS droping. Set try settings what you got Jinzombie. Speed can improve FPS cheat codes. You can find them in the forum

**Comment by marosis** [comment]
I think, this can be closed

**Comment by hrydgard** [comment]
Yeah, when you drop the emulated CPU speed, all bets are off.
