### ISSUE TITLE
[Bug] Combo keys are glitched and cause many issues

### ISSUE THREAD

**Issue by leopard20** [hrydgard/ppsspp#10974]
Remember the new shader cache loading screen you added?! (the screenshot should refresh your memory LOL!) Well, after enabling combo keys it's not shown anymore.
![screenshot_2018-04-27-13-40-44-259_org ppsspp ppsspp](https://user-images.githubusercontent.com/16115820/39354862-dd7268ac-4a20-11e8-9b93-5c1eddc1e68b.png)

Here's another weird thing:
![screenshot_2018-04-30-01-18-49-911_org ppsspp ppsspp](https://user-images.githubusercontent.com/16115820/39410903-bce462f2-4c14-11e8-9535-aaba94a1c96b.png)
Combo keys and some other keys have a different transparency level than action buttons and DPAD

**Comment by unknownbrackets** [comment]
It only shows if loading takes long enough.  Your graphics driver will probably cache shaders in memory after they're loaded.

Is it showing a black screen for longer than it normally does when the game starts?

-[Unknown]

**Comment by leopard20** [comment]
What I don't understand is why does it show it the first few times I run a game, but disappears later?

Yes, the game takes longer to start than normal (as compared to v1.5.4). It looks like it **wants** to show the same caching screen but doesn't.

**Comment by leopard20** [comment]
I also compared two ini's for two different games (one that didn't show this screen and one that did) but there was no difference.

**Comment by leopard20** [comment]
Here is the game config after deleting it and recreating it (it shows the screen now) 

[NPJH50465_ppsspp.ini.zip](https://github.com/hrydgard/ppsspp/files/1955477/NPJH50465_ppsspp.ini.zip)

**Comment by leopard20** [comment]
@unknownbrackets @hrydgard 
Good news! I found the cause! It's caused by touch controls. If you replace the controls section from NPJH... with that of any other game, it won't work anymore.

**Comment by leopard20** [comment]
I just realized the ultimate cause! It happens when you **manually** edit the controls (through the ini file) . Really weird!

**Comment by hrydgard** [comment]
That is seriously weird. Good job finding a hint to the problem! :)

**Comment by leopard20** [comment]
Glad to help! But let's hope it's not a bogus culprit, like the texture hashing issue I reported!

**Comment by hrydgard** [comment]
Just to clarify, was it when you replaced the [Control] or [ControlMappings] section? Also I really don't understand how this makes any sense :) Can't seem to repro.

**Comment by leopard20** [comment]
[Control] (i.e touch controls)
Just copy all of my config for NPJH50465 into another game config. (From System.zip)

**Comment by unknownbrackets** [comment]
Is that simplest way to reproduce this?  Does it require a game-specific ini with game-specific control positions?  Or does it happen even if you change the controls manually in ppsspp.ini?

-[Unknown]

**Comment by leopard20** [comment]
Well I'm not entirely sure about this. Like I said there was an exception (ULJM... archive above) But the rest of games I edited have this problem (3rd Birthday, Assassin's Creed, Tekken 6, PD Extend, etc)
Here is what you should look for:
Tekken 6 with the config I posted above:
![20180430_003712](https://user-images.githubusercontent.com/16115820/39410545-28c35f10-4c0f-11e8-9e64-581407507f97.gif)

Tekken 6 after deleting its config and using the default config:
![20180430_003749](https://user-images.githubusercontent.com/16115820/39410548-38b2d5fe-4c0f-11e8-9f71-f3206da1f2c4.gif)

**Comment by leopard20** [comment]
Just to be sure let me test it on my PC too

**Comment by leopard20** [comment]
OK now I'm 100 positive that:
1. It's not game specific (tried some games with the config I mentioned, all had issues)
2. It's not platform specific (same thing on PC)

So it might depend on which variable you edit.
Another possiblity is, for example, setting the center of a control at an invalid display region.
For example, both my PC and Android are 1080p. Now if I changed the center of a button such that it fell at (1000, 205.7), an invalid point, it may lead to issues.

**Comment by leopard20** [comment]
Another discovery!
It's not caused by editing controls but rather by using Combo keys!

**Comment by leopard20** [comment]
Uodated the issue (see the original post)

**Comment by hrydgard** [comment]
Bizarre! I've repro'd. I tried looking the tween color value used for the background, and yeah:

	loadingViewColor_->SetCallback([loadingBG, loadingTextView, loadingSpinner](View *v, uint32_t c) {
		ILOG("Tween: %08x", c);

    I: emuscreen.cpp:917: I: Tween: 00ffffff
    I: emuscreen.cpp:917: I: Tween: 00ffffff
    ...

Very confused as to how combo keys has anything to do with that tween value... hm.

**Comment by unknownbrackets** [comment]
Oh.  Maybe it's when a different number of views are created - it uses the persisted data thing, it might need a tag to keep the correct values.

-[Unknown]

**Comment by hrydgard** [comment]
Oh duh, forgot about that ... that makes some sense :)

**Comment by leopard20** [comment]
Seems fixed. 
Guess we (you!) 're good for 1.6 then.

**Comment by leopard20** [comment]
Wait. I noticed that the texts are missing now. Was it intentional?
Also, are gonna do something about the transparency issue? It's not really important though.

**Comment by unknownbrackets** [comment]
The text was intentionally removed because it causes a lot of extra strings to translate for 1.6.0.

I think we should open a separate issue about the transparency - seems strange.

-[Unknown]

**Comment by leopard20** [comment]
Ok
