### ISSUE TITLE
TalkMan (Europe) freezes up on loading screen

### ISSUE THREAD

**Issue by benderscruffy** [hrydgard/ppsspp#10970]
v1.5.4-933-g386c9d4fc
after you press start on the title screen if freezes up on the loading screen
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/1953725/ppsspplog.zip)

**Comment by benderscruffy** [comment]
v1.6.3-526-g669079454
still a problem
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/2437670/ppsspplog.zip)

**Comment by benderscruffy** [comment]
still happens with 
v1.9.3-167-gb2dd3c7e1
17:32:304 GSAPISID     E[HLE]: hle\hle.cpp:545 Unimplemented HLE function sceUsbMicInputInitEx
17:32:304 GSAPISID     E[HLE]: hle\hle.cpp:545 Unimplemented HLE function sceUsbWaitState
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/4015810/ppsspplog.zip)

**Comment by unknownbrackets** [comment]
Yeah, very likely it's caused by those being unimplemented.

-[Unknown]

**Comment by Panderner** [comment]
This game requires microphone support see #12336

**Comment by Panderner** [comment]
Microphone Test in TalkMan is now working on PPSSPP on Android in https://github.com/hrydgard/ppsspp/pull/13575
![Screenshot_2020-10-31-19-25-10-10_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/97778020-23df5e00-1baf-11eb-9f0b-741dadd8a6b8.png)

https://github.com/hrydgard/ppsspp/pull/13229 also works for Windows.

**Comment by Panderner** [comment]
And unfortunately microphone support for Linux, IOS, MacOS and other platforms are still not supported yet.

**Comment by Florin9doi** [comment]
This ticket is resolved and the support for other platforms is tracked in #12336. 
@hrydgard, I propose this for closure
