### ISSUE TITLE
Open Season (USA) crashes out the emulator

### ISSUE THREAD

**Issue by benderscruffy** [hrydgard/ppsspp#10972]
v1.5.4-933-g386c9d4fc
on the third screen the emulator crashes out
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/1954123/ppsspplog.zip)
![open](https://user-images.githubusercontent.com/2696404/39349319-19c9776c-4a2d-11e8-9d6d-6e2426c6b9cb.PNG)

**Comment by unknownbrackets** [comment]
Does it crash even with fast memory disabled?

-[Unknown]

**Comment by benderscruffy** [comment]
no it doesnt crash with fast memory disabled
it just comes up with a black screen after the Sony Pictures Animation screen
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/1954192/ppsspplog.zip)

**Comment by sum2012** [comment]
I test from v1.2.2 to v1.5.4-936-g35375691d
The game always crash

**Comment by benderscruffy** [comment]
v1.7.5-566-gf316a6590
still the same problem
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/2966056/ppsspplog.zip)

**Comment by hrydgard** [comment]
No obvious problem in the log, some async I/O is going on before the crash, that's about it...

**Comment by Panderner** [comment]
Here's a log when crash triggers:
```
59:06:176 user_main    E[MEMMAP]: Core/MemFault.cpp:167 Bad memory access detected! 00000001 (0x6f00000001) Stopping emulation. Info:
0070f8200174 ldr w16, [x28 + x16]
```
![Screenshot_2020-07-29-14-59-58-31_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/88767684-930e7600-d1ac-11ea-816d-8dcc6f0762c0.png)

**Comment by Panderner** [comment]
and same happens in v1.10.3-249-g7a3c95ee3
