### ISSUE TITLE
Analog input in the loader menu?

### ISSUE THREAD

**Issue by YvanDroid** [hrydgard/ppsspp#10996]
I noticed this when using the PPSSPP on Android that the menus do not interpret input from the analog sticks on my Bluetooth controller. I either need to reach up and touch the screen or activate my inner rhythm master in spamming the dpad. Just a quality of life upgrade. I am on the latest commit on Android, so I don't know if other operating systems have analog input.

P.S. Does this post just get tagged with feature request or do we have to tag it ourselves?

**Comment by leopard20** [comment]
Only the owner and collaborators can add labels. (i.e those with access to the repository)
