### ISSUE TITLE
Build PPSSPP is slow in god of war

### ISSUE THREAD

**Issue by SamueldeSena** [hrydgard/ppsspp#10992]
this problem happens from version v1.5.4-936-g35375691d onwards until the moment this problem occurs in both vulkan and opengl the game is taking too long to start and is running slow

**Comment by unknownbrackets** [comment]
@hrydgard this implies #10944....

-[Unknown]

**Comment by ShadowLady** [comment]
Just as a side note, if you are using a force 30 or 60 FPS cheat code this doesn't affect the games at all. Probably known but just figured I'd mention it, since I thought it wasn't affecting my build somehow but it was just the cheats keeping everything working for me.

**Comment by hrydgard** [comment]
I've reverted #10944 for now, will think of something else, otherwise might release with the slowness on game over...

**Comment by leopard20** [comment]
This had also caused a regression in Project Diva Extend. It was horrible on Vulkan :) Thanks for removing it.

**Comment by SamueldeSena** [comment]
thanks hrydgard I'm going to test the current version of PPSSPP

**Comment by SamueldeSena** [comment]
ok it's working normally thanks for the time I'll be closing the topic
