### ISSUE TITLE
Metal Gear Solid Peace Walker Vulkan Rendering 

### ISSUE THREAD

**Issue by fivefeet8** [hrydgard/ppsspp#10993]
### What happens?
Vulkan rendering is not right.  Too bright with patches

### What *should* happen?
Should look like the OpenGL render.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Android Snapdragon 820 ZTE Phone, PPSSPP Dev Ver 1.5.4-947

OpenGL Render:
![screenshot_2018-05-01-14-31-37](https://user-images.githubusercontent.com/12039585/39495322-b15bac0c-4d4e-11e8-9d88-4cdec1b80224.jpg)

Vulkan Render:
![screenshot_2018-05-01-14-31-10](https://user-images.githubusercontent.com/12039585/39495316-ab63a458-4d4e-11e8-9778-de69f23010df.jpg)

**Comment by leopard20** [comment]
Checking "Disable slower effects" fixes it though.

**Comment by leopard20** [comment]
@hrydgard 
Quick question: Why is the game running @ 21/20 speed but PPSSPP is showing a 99% speed?! 😅

**Comment by fivefeet8** [comment]
@leopard20 

That's more like a workaround.  Slower effects worked fine before.  Also, the game normally runs at 20 FPS ingame.  You can increase it to 60 or 30 FPS with the FPS cheats.

**Comment by fivefeet8** [comment]
Confirmed this happens on my Shield TV as well with PPSSPP dev 945.

**Comment by marosis** [comment]
If you want more FPS, you can try this FPS cheat code.                                                    _C0 Force 60 FPS beta
_L 0x2055DDB4 0x00000001
_L 0x203E7500 0x00000005
_L 0x203E74E4 0x3F800000
_C0 Force 30 FPS beta
_L 0x2055DDB4 0x00000002
_L 0x203E7500 0x0000000A
_L 0x203E74E4 0x40000000
_C0 Force 20 FPS beta
_L 0x2055DDB4 0x00000003
_L 0x203E7500 0x0000000F
_L 0x203E74E4 0x40400000

**Comment by marosis** [comment]
This is for eur version

**Comment by hrydgard** [comment]
did this start with the recent depal changes, or has it been like this for some time?

**Comment by leopard20** [comment]
If I recall correctly it was after the depal changes. Will test later.

**Comment by hrydgard** [comment]
If you're building yourself, you can use the latest version and try modifying this line in TextureCacheVulkan.cpp to false:

https://github.com/hrydgard/ppsspp/pull/10911/files#diff-3e0e122df6d1f6394367a0fc6e8066d5R347

**Comment by leopard20** [comment]
No. Android studio is not downloadable here (we have to go through unofficial channels!)

But build 896 works.

**Comment by hrydgard** [comment]
Ok, good. I'll see what I can figure out, if it can't be fixed in time I'll just disable that new optimization for 1.6 and deal with it later.
