### ISSUE TITLE
Can't Save at all. Disk is full?? 

### ISSUE THREAD

**Issue by 11ROLAND11** [hrydgard/ppsspp#10995]
Help plz. I can't save anything at all. The game apparently shows that the disk is full, or even unable to save state.

**Comment by hrydgard** [comment]
Need more information. Is this on Android or PC?  If Android, did you give the app permission to read/write storage?  Which device? Does a reboot help?

**Comment by 11ROLAND11** [comment]
PC. Given Permission. Rebooting doesn't help

**Comment by 11ROLAND11** [comment]
The app just won't save. I don't know why

**Comment by 11ROLAND11** [comment]
I fixed the problem.

**Comment by Rafidmuhaiminwafi** [comment]
I think that his hdd was really full so he fixed it by deleting files

**Comment by 11ROLAND11** [comment]
I looked at the other threads, and I moved the PPSSPP files onto the desktop, instead of the Program files
