### ISSUE TITLE
Why a dualcore android phone doesn't gain the improvement of multithreaded in ppsspp

### ISSUE THREAD

**Issue by Jinzombie** [hrydgard/ppsspp#11005]
I install the latest build of ppsspp in my old tablet with a dualcore 1.6Ghz CPU Mali-400 GPU and tried to play Tekken 6 but its very lag :(
doesn't improve why?

**Comment by Jinzombie** [comment]
*sorry for my bad english

**Comment by marosis** [comment]
Tekken 6 is very problematic game with improving performance. Here i think nobody  can't help you. You have Slow device. Do you have latest build with new multithreading?

**Comment by Jinzombie** [comment]
Not only in Tekken 6 but also in other games like Brave: New Traveler,Naruto Ultimate Ninja Heroes and Burnout Legend.
Im using the latest build 1.5.4-962

**Comment by Jinzombie** [comment]
But in my quadcore device with the same GPU mali-400 @1.3ghz CPU I feel the improvement it's just like 20-30 percent increase in the performance.

**Comment by hrydgard** [comment]
Performance on Android is super complex. Many devices will downclock the CPU and GPU as soon as they get a little hot, and it may even be the case that this happens sooner if we manage to utilize two cores. I don't think there's much we can do here.

**Comment by Jinzombie** [comment]
I root my tablet since its android jelleybean
I easily root it then I change the CPU Governor from Interactive to Performance now its fast using the latest build :)
tnx @hrydgard for the info

**Comment by marosis** [comment]
You can try set emulate clocks to 60MHZ And restart game, but!!!!!! Do not use this in Tekken 6. Tekken need have PSP CPU clocks (222MHZ)

**Comment by marosis** [comment]
Lower MHZ mean better speed, but lower max FPSs

**Comment by Jinzombie** [comment]
@marosis I don't need to lower the MHz clock in tekken 6 I have force 30 FPS cheat and also I have a cheat that fix the blackscreen issue of Tekken 6 when emulated cpu clockspeed set to any number except 222MHz or Auto.

Now my games run at solid 30 FPS & 100% Speed because I change the cpu governor to performance.

**Comment by marosis** [comment]
Can you send me here that 30FPS cheat? I can't find it

**Comment by marosis** [comment]
I don't see it in Forum

**Comment by Jinzombie** [comment]
_C1 Custom CPU speed freeze [Fixed]
_L 0xE0030004 0x001C6094
_L 0x201C6094 0x00000000
_L 0x201CFC28 0x00000000
_L 0x201CFE74 0x00000000
_C0 Custom CPU speed freeze [Default]
_L 0xE0030000 0x001C6094
_L 0x201C6094 0x10400004
_L 0x201CFC28 0x1443FFF5
_L 0x201CFE74 0x1443FFF5
_C1 Force 30 FPS [Fixed]
_L 0x20452890 0x00000000//FPS=30
 
NOTE:Set refresh rate to 17

**Comment by marosis** [comment]
Thank you
