### ISSUE TITLE
Tactics Ogre warning content popup

### ISSUE THREAD

**Issue by pipi212** [hrydgard/ppsspp#11006]
### What happens?
When the game start.  It shows a warning.
It keeps alerting me every time, when i start game.

![ules01500_00000](https://user-images.githubusercontent.com/39021866/39671247-6fd41582-513e-11e8-99e6-aa4515f4ea84.jpg)

Log:
![log ppsspp warning tactics](https://user-images.githubusercontent.com/39021866/39671240-58b771b4-513e-11e8-9caf-0bb1a20a5244.PNG)

I found error starting from version v1.5.4-856-g6fccefae5 ... v1.5.4-963-g94ab646cd
Version v1.5.4-850-g93bf86612 no error

**Comment by hrydgard** [comment]
That implicates #10888 @unknownbrackets  ...
