### ISSUE TITLE
Shader depal slightly offset (bilinear filtering)

### ISSUE THREAD

**Issue by unknownbrackets** [hrydgard/ppsspp#11008]
In Dragon Ball Z Tag Team, outlines are drawn around characters using a depal effect.  This is probably most apparent at 1x.

Before / without shader depal:
![npeh90042_00000](https://user-images.githubusercontent.com/191233/39675363-12a3b09a-510f-11e8-8ee9-77e3f8b180dd.png)

With it (#10911):
![npeh90042_00002](https://user-images.githubusercontent.com/191233/39675382-47ef1398-510f-11e8-9c81-22487f6f80cc.png)

I tried adjusting the fraction to account for pixel centers (since 0.5,0.5 should really have no linear filtering...)
![npeh90042_00001](https://user-images.githubusercontent.com/191233/39675365-161f9f90-510f-11e8-9532-ab0c6c95385f.png)

That helped, but they still seem to pull left...

Technically a 1.6.0 regression but not very major.

-[Unknown]

**Comment by hrydgard** [comment]
Right, I think with manual bilinear we need indeed offset by 0.5. Not sure why there would be a remaining horizontal-only offset though, unless the 0.5 offset got unevenly scaled by texture size somehow...

**Comment by hrydgard** [comment]
No we need to offset the UV not just for the filtering but also the actual texture lookups. I'll try to put it together soon..
