### ISSUE TITLE
Asphalt Urban GT 2 Gameplay Gliches

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#11013]
Runs ok but there's is a video Gliches missing lighting and background bug in Paris track
![screenshot_2018-05-07-18-24-55](https://user-images.githubusercontent.com/37503397/39697642-309017fe-5224-11e8-8159-9d68d45770b1.png)

**Comment by Panderner** [comment]
Nitros and arrows won't glow

**Comment by Emulatorer** [comment]
@Panderner this game is running smooth in your phone in ppsspp last build default using settings only?

**Comment by Emulatorer** [comment]
@Panderner you still didn't answering my question 🤷

**Comment by Emulatorer** [comment]
Graphics issue didn't happen to my phone/tablet using ppsspp latest build my only problem is lag :/

@Panderner Can you upload the GE DUMP of this game from that area paris track???

**Comment by Emulatorer** [comment]
No feedback/outdated?

**Comment by Panderner** [comment]
The bug still here on latest build

**Comment by unknownbrackets** [comment]
Sorry, we don't understand.  What is wrong?

Here's a picture of the game from 2007:
https://d2skuhm0vrry40.cloudfront.net/articles//a/7/4/9/3/0/2.jpg.jpg

It looks like your picture to me.

-[Unknown]

**Comment by Panderner** [comment]
The Paris track background looks glitchy

**Comment by unknownbrackets** [comment]
Could you try exporting a GE frame dump?  These help a lot.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by Panderner** [comment]
[GE Dump.zip](https://github.com/hrydgard/ppsspp/files/3724710/GE.Dump.zip)
Here

**Comment by Panderner** [comment]
No response? Here's a GE Dump
[GE Dump.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/4309676/GE.Dump.ppdmp.zip)

**Comment by unknownbrackets** [comment]
Hm, that dump is blank.  Neither of those dumps show anything when you open them with PPSSPP.  Can you try making multiple dumps?  If it's < 3 KB it's probably no good.

-[Unknown]

**Comment by Emulatorer** [comment]
here
[recording.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/4315935/recording.ppdmp.zip)
400kbs can't get 1mb dump 🤔

**Comment by unknownbrackets** [comment]
Hm, this looks like a loading screen.  Is that the dump you get when you take a screenshot in game and see something like this?

https://user-images.githubusercontent.com/37503397/39697642-309017fe-5224-11e8-8159-9d68d45770b1.png

If so, it may mean the game is doing software rendering or something the GE debugger can't see...

-[Unknown]

**Comment by Emulatorer** [comment]
Here's the logcat from Catlog app (need root access)
[ppsspp_log.txt](https://github.com/hrydgard/ppsspp/files/4317224/ppsspp_log.txt)
Because I can't get ge dump properly with this game using ppsspp latest build 😕

**Comment by Panderner** [comment]
> Hm, that dump is blank. Neither of those dumps show anything when you open them with PPSSPP. Can you try making multiple dumps? If it's < 3 KB it's probably no good.
> 
> -[Unknown]

Oops I mean this:
[recording.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/4364778/recording.ppdmp.zip)

**Comment by LeRutY** [comment]
I have transparency issues, I see the track arrows, pick up items and the skybox through the road and barriers

**Comment by Panderner** [comment]
Cop Cam Screenshot and player's car crash animation does not correct properly.

![Screenshot_2020-11-15-09-28-50-47_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/99160743-24d2cc80-2725-11eb-8312-8a47ced62617.png)
![Screenshot_2020-11-15-09-24-55-46_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/99160745-2f8d6180-2725-11eb-863b-dc09bf4cdbe8.png)

This how's it looks on real hardware:
![IMG_20201115_093202](https://user-images.githubusercontent.com/37503397/99160769-898e2700-2725-11eb-8759-305f5dc0ebb6.jpg)
![IMG_20201115_093151](https://user-images.githubusercontent.com/37503397/99160774-9c086080-2725-11eb-9100-47eb56d4c125.jpg)

**Comment by Panderner** [comment]
Here's a GE Dumps:
[Cop Cam.zip](https://github.com/hrydgard/ppsspp/files/5541723/Cop.Cam.zip)
[Car Crash.zip](https://github.com/hrydgard/ppsspp/files/5541724/Car.Crash.zip)

**Comment by Panderner** [comment]
These things does not occur for Vulkan:
![Screenshot_2020-12-22-19-41-41-693_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/102885287-126b5180-448e-11eb-9f23-d5dacbe2c26f.jpg)
![Screenshot_2020-12-22-19-41-21-238_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/102885297-14cdab80-448e-11eb-8925-e8b9f1c39c90.jpg)
![Screenshot_2020-12-22-19-37-50-931_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/102885299-15fed880-448e-11eb-8fe0-da469d2e1a57.jpg)

**Comment by Gamemulatorer** [comment]
> Runs ok but there's is a video Gliches missing lighting and background bug in Paris track
> ![screenshot_2018-05-07-18-24-55](https://user-images.githubusercontent.com/37503397/39697642-309017fe-5224-11e8-8159-9d68d45770b1.png)
Can't see the difference on my ss 🤔
![Screenshot_2021-09-04-00-31-02-191_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/132038849-6538c5e0-963c-43f3-ae0a-5c1a6370bafe.jpg)

**Comment by unknownbrackets** [comment]
In the dump, the game spends most of its time drawing the scene in color:
![image](https://user-images.githubusercontent.com/191233/132108087-694bca84-6692-4c8a-b815-6013c87cf0e1.png)

It then does another pass to grayscale it.  This starts at 192/262.

Those draws follow this pattern:
 * Texture from 0x04000000 -> 0x04154000, 30px wide strip, depth and stencil write disabled (8888.)
 * Do this copy using a simple CLUT - 32-bit index & 0xFF, to a palette with a grayscale ramp.
 * Next, do another texture from the same, but looking at G.  Simple ONE + ONE blending.
 * And the another draw, which is B.
 * With this done, texture 0x04154000 -> 0x04000000 back, now in grayscale.

The screenshots where it's darker look like what would happen if blending weren't applied (it uses fixed + fixed, both 0xFFFFFF.)  The CRASHED thing showing twice implies there's some stretching issue too.

I don't see any issue in the dumps - does this still reproduce?

As far as the paris background, I don't see any working frame dumps for that.

-[Unknown]

**Comment by hrydgard** [comment]
Oh I confused the issues. I think this one is indeed outdated, the current issue is #14299.
