### ISSUE TITLE
Motorstorm: Arctic Edge freeze on loading screen

### ISSUE THREAD

**Issue by Godavatar** [hrydgard/ppsspp#11019]
So, emulator version 966 was the last where game worked us usual. From 968 game freeze on loading screen (after intro, just before main menu shows). I also check 971 with same result.

Also, a game has one minor issue with "ice shader"  (i doubt its called like that, but dont have better words). On few tracks (like Vertigo, ice colums just in the beggining of the race) ice in game shows with visual "square" artifacts, but only on Vulcan rendering, its fine on OpenGL.

**Comment by hrydgard** [comment]
@unknownbrackets  This seems to be another fallout of the replay stuff. thinking about reverting and re-merging after 1.6....

**Comment by unknownbrackets** [comment]
Well, I'd said WIP so that's okay, but might be good to know what happened.  Maybe this hit the `if (w32err == ERROR_SHARING_VIOLATION) {` case?  Maybe this needs to be (`} else if (!success) {`):
https://github.com/hrydgard/ppsspp/commit/8f5a23b6a8bb9092a521c210554eee22e9f8fb00#diff-3b1798ba26372863d8005a22e0c7fc72R255

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, of course it would be even better to spot the cause. Things do seem mostly solid... and that sounds plausible.

**Comment by Godavatar** [comment]
I take few screenshots with Vulcan and OpenGL renders (Vulcan first), hope it helps:
![screenshot_2018-05-08-19-12-57-715_org ppsspp ppsspp](https://user-images.githubusercontent.com/38508924/39769900-28be539c-52f6-11e8-8eb4-6ff2416de6d2.png)
![screenshot_2018-05-08-19-15-23-795_org ppsspp ppsspp](https://user-images.githubusercontent.com/38508924/39769914-31f9269e-52f6-11e8-9290-1d5ef2891664.png)
![screenshot_2018-05-08-19-12-15-753_org ppsspp ppsspp](https://user-images.githubusercontent.com/38508924/39769933-432f9902-52f6-11e8-9a4f-4db08a5788b9.png)
![screenshot_2018-05-08-19-18-28-679_org ppsspp ppsspp](https://user-images.githubusercontent.com/38508924/39769939-498d097e-52f6-11e8-9b01-d4107ba981c8.png)

**Comment by unknownbrackets** [comment]
Maybe depth or mipmapping?

-[Unknown]

**Comment by hrydgard** [comment]
Or texturing from the framebuffer in some obscure way that we're missing... given that it's ice, it doesn't seem unlikely

**Comment by unknownbrackets** [comment]
Does the error on start still happen in the latest git build?

-[Unknown]

**Comment by Godavatar** [comment]
Tried 980 build, but game still stuck at loading screen.

**Comment by unknownbrackets** [comment]
Does it happen with certain savedata - if so, can you upload?

-[Unknown]

**Comment by Godavatar** [comment]
I doubt it connected with saves, because game freeze before menu where i can select and load a save, and there were no problems before.

**Comment by Godavatar** [comment]
Sure, if it helps 
[UCES012500000.zip](https://github.com/hrydgard/ppsspp/files/1989311/UCES012500000.zip)

**Comment by unknownbrackets** [comment]
Hmm, I can't reproduce - I've tried default settings and 32-bit as well, and checked the buildbot builds in case there's some compilation bug.

I don't have the DLC, so there is a file open error on start, but it doesn't hang - it just logs a (correct) error and continues on.

-[Unknown]

**Comment by iArti** [comment]
I have this issue on ver 1.7, my hardware is Snapdragon 650 (Adreno 510)
It freezes on any loading screen on both OpenGL ES and Vulkan
European version of the game (UCES01250)

**Comment by unknownbrackets** [comment]
Does it work for you in older versions like v1.6.3 or v1.5.4?  What is the crc of your iso?

-[Unknown]

**Comment by iArti** [comment]
> Does it work for you in older versions like v1.6.3 or v1.5.4? What is the crc of your iso?
It worked in 1.5.4, but since 1.6.3 it freezes
CRC32 of iso - 0x1D422CEE

**Comment by unknownbrackets** [comment]
Hm, that doesn't seem to match a good crc.

-[Unknown]

**Comment by Nine-H** [comment]
got the loading screen freeze on ubuntu xenial on the 1.7.0 release.

**Comment by unknownbrackets** [comment]
Is there any improvement in the latest git build?

-[Unknown]

**Comment by sisxgame** [comment]
No improvments on my phone ( leeco le pro 3 elite snapdragon 820 cpu ) whit latest git.
Still stuck in loading screen

**Comment by hausnes** [comment]
Same problem on my Nvidia Shield v2.
