### ISSUE TITLE
Can PPSSPP use DX12 or would adding it improve anything?

### ISSUE THREAD

**Issue by tilkinsc** [hrydgard/ppsspp#11011]
I know yall work so hard on rendering, but would dx12 lead to anything good?

**Comment by hrydgard** [comment]
Vulkan has pretty much the same performance profile and features as D3D12, so no, it would not add anything. Use Vulkan.

**Comment by tilkinsc** [comment]
Vulkan would be the latest and greatest?

**Comment by hrydgard** [comment]
Yeah.
