### ISSUE TITLE
[Android] Display size remaining the same as rendering resolution after switching program

### ISSUE THREAD

**Issue by Leopard20** [hrydgard/ppsspp#11016]
If you switch away from the PPSSPP (e.g by pressing home or simply by locking and unlocking the device), after returning to the app you can see that the display size has been cropped to the size of the rendering resolution. 
This screenshot is taken from Tekken 6 @ 3x rendering resolution. HW scaler is ~~Auto~~ Native (in this case 1080p).
![screenshot_2018-05-07-19-10-51-652_org ppsspp ppsspp](https://user-images.githubusercontent.com/16115820/39708930-ba6bf782-522d-11e8-92fb-c32979270a7a.png)

**Comment by hrydgard** [comment]
Yeah, these bugs are driving me crazy. They don't happen on all devices either.

**Comment by leopard20** [comment]
😅 Yeah! Just when you think everything is good for the new version, another bug pops up!

You don't have to prioritize all of them, you know! For example, this one is easily fixed by simply saving the state at that time and reloading it.

**Comment by 1234Sameer** [comment]
![screenshot_2018-05-15-08-31-10](https://user-images.githubusercontent.com/39208952/40034413-744ea806-581a-11e8-8523-ec8203d33985.png)
![screenshot_2018-05-15-08-48-22](https://user-images.githubusercontent.com/39208952/40035155-0aab0620-581e-11e8-82f2-f992b1e7a5e3.png)

[Android] I guess these are same kind of bug. This happens when I return to ppsspp after minimizing. The first one is easy to reproduce but the 2nd one happens sometime. In the first one the screen looks like a stretched one but the settings and credits tabs are moved to the top. In the second the settings and credits tabs are moved  to the centre and screen shows half black at the right.  In both cases buttons don't work properly. I think this is a recent bug as the latest stable version don't have this bug. In both cases no games are launched. And these bugs don't happen if I lock and unlock my device.

**Comment by unknownbrackets** [comment]
I think this is related to the onCreated behavior I described in the other bug regrading the display width and height being updated at the wrong times.  Maybe these devices are always doing an onCreated at the would size and then an immediate update to the right size.

-[Unknown]

**Comment by leopard20** [comment]
Also happens in PPSSPP menu (not necessarily a game) if you, for example, click on Support PPSSPP and press back in market.

**Comment by 1234Sameer** [comment]
![screenshot_2018-05-17-08-21-23](https://user-images.githubusercontent.com/39208952/40155392-1a09fa06-59b1-11e8-972a-ca1b26148075.png)
Hear is a Screenshot of Soul Calibur and This is the minimize bug( if I press home and relaunch my game from recent ). Here the buttons are affected with the bug while the game runs fine without any bug. Locking and unlocking didn't affect my game in any way. I tested multiple times with different rendering resolution and display resolution but couldn't get any kind of bug with locking and unlocking my device.

**Comment by leopard20** [comment]
@1234Sameer 
Oh you're right! (kinda)
@hrydgard 
Turns out the lock-and-unlock bug only happens on Vulkan, not OpenGL.

**Comment by leopard20** [comment]
Exactly. 1x is smaller. But like I said it only happens on Vulkan.

**Comment by 1234Sameer** [comment]
@leopard20 
Sorry for asking you twice,
but can you test with some more settings like
1)Rendering resolution 1xPSP and HW scaler 1xPSP.
2)Rendering resolution Auto(1:1) and HW scaler native.

**Comment by leopard20** [comment]
Obviously if Rendering reolution is equal to HW scaler (1:1) then you won't see the cropping.
Another interesting thing I found is that if HW scaler is smaller than Rendering resolution (e.g HW scaler 2x and Rendering res. 3x) then you won't see the bug either.
In summery, for HW scaler equal to or smaller than Rendering res. there's no cropping bug.

**Comment by 1234Sameer** [comment]
@leopard20
So the HW scaler is somehow causing the bug, but I don't think only making the HW scaler game specific would solve the bugs. It may be able to solve the 2nd bug reported by you which looks different but won't necessarily fix the first bug. So let's we make the HW scaler game specific and put HW scaler native and rendering resolution 1xPSP, Then we will still get the bug as normal. Plus what about the Vulkan API only.
Yes, we need to test on other devices (Vulkan) to confirm whether or not this is a device specific bug.

**Comment by leopard20** [comment]
I didn't say it fixes the bug, it's just annoying that you can't set it per game.

**Comment by unknownbrackets** [comment]
Has this improved with latest fixes?

-[Unknown]

**Comment by leopard20** [comment]
No. And there isn't anything in the commits that could possibly fix this!

**Comment by 1234Sameer** [comment]
@leopard20 
The bugs I reported, should I open another issue on this as they are different from yours and they still exist on PPSSPP v1.6.2-17-g6db008fc0 ? or it is good here.

**Comment by leopard20** [comment]
I'm not sure!
@hrydgard What do you say?

**Comment by XiaomiRedmi9** [comment]
Any update?

**Comment by Gamemulatorer** [comment]
Can still reproduce this sometimes :/
![Screenshot_2022-07-11-20-52-29-306_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/178268939-285c246a-1ede-44e5-b77c-7e5e45e20a45.jpg)

**Comment by Gamemulatorer** [comment]
Can't reproduce this issue after https://github.com/hrydgard/ppsspp/pull/16794 maybe the culprit is the HW scaler?

**Comment by hrydgard** [comment]
Likely.
