### ISSUE TITLE
[UI] Post-processing shader name not translated until you click on it

### ISSUE THREAD

**Issue by vnctdj** [hrydgard/ppsspp#11015]
When you open the settings, the selected post-processing shader name is not translated.
You have to click on the preference, as if you would like to change it, and you can see it gets translated in the background.

For example, you have chosen "Natural Colors (no blur)".
The UI doesn't show this string but "NaturalA" instead, until you click on the preference.

I'm using PPSSPP v1.5.4-971-g97546d30f

**Comment by leopard20** [comment]
I actually meant to report it a while back but I forgot!

**Comment by SamueldeSena** [comment]
This issue has now been resolved This topic can already be Closed

**Comment by hrydgard** [comment]
Really? If it's broken in 971, I don't think so..

**Comment by vnctdj** [comment]
Of course this is not fixed, you need maybe 10 seconds to check it @SamueldeSena...

**Comment by hrydgard** [comment]
Huh, maybe. I'll defer this to after 1.6, anyway..
