### ISSUE TITLE
[Vulkan] Resizing the window freezes the UI (SDL, Linux)

### ISSUE THREAD

**Issue by vnctdj** [hrydgard/ppsspp#11014]
Resizing the window freezes the UI when using Vulkan (it stops drawing anything), however the process doesn't seem to hang.

There is no problem with OpenGL.

**OS:** Debian GNU/Linux testing (buster) x86_64
**Kernel:** 4.16.0-1-amd64
**CPU:** Intel i7-6700HQ (8) @ 3.500GHz
**GPU:** NVIDIA GeForce GTX 960M
**PPSSPP:** v1.5.4-971-g97546d30f

It may matter that I use i3 as window manager.

**Comment by hrydgard** [comment]
So what happens is that we get back VK_ERROR_OUT_OF_DATE_KHR when trying to acquire an image, every single frame, and we never try to recreate the swapchain. Something is missing.

**Comment by unknownbrackets** [comment]
Yeah, it's just commented out:
https://github.com/hrydgard/ppsspp/blob/master/SDL/SDLVulkanGraphicsContext.h#L28-L37

-[Unknown]
