### ISSUE TITLE
Sustained performance mode not working correctly

### ISSUE THREAD

**Issue by szale9001** [hrydgard/ppsspp#11018]
### What happens?
Using Pixel 2 (Android 8.1) with sustained performance mode checked in settings.

When opening the app with Auto rotation selected, sustained performance mode activates. However, when rotating the device, sustained performance mode will then deactivate and processor will return to normal mode. Can verify with cpu monitor. 

Video link to demonstrate. When in Sustained perf mode, freq shouldn't go above or below 1.2Ghz. After rotating, frequency is operating in normal mode again, rising and lowering based on demand (in video, cpu monitor is in upper left corner of status bar)
https://gfycat.com/WelloffVengefulEuropeanpolecat

### What *should* happen?
Sustained perf mode should not disable upon rotation.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
PPSSPP 1.5.4-957 (latest as of yesterday, I think)
Android 8.1

**Comment by unknownbrackets** [comment]
I guess we just need to call `updateSustainedPerformanceMode()` in `surfaceChanged`?  Or really looks like it should be done on `onWindowFocusChanged` probably.

-[Unknown]

**Comment by szale9001** [comment]
Tested build 980-g6615e55c5, and it looks like the issue is still present

**Comment by szale9001** [comment]
Fingers crossed ;)

And thanks for looking into it

**Comment by hrydgard** [comment]
How is this now?

**Comment by szale9001** [comment]
No dice, unfortunately. Tested 985, and it still does it. 

Also, I noticed that if I select Landscape in PPSSPP, but launch the app in Portrait mode, Sustained performance mode won't even engage. Not sure if that'd help diagnose, but I figured I should mention it.

**Comment by hrydgard** [comment]
That's very curious, and makes it seem like the bug maybe isn't in PPSSPP...

**Comment by szale9001** [comment]
I'm not so sure. I tested tinyCAM free (which is literally the only other app I know of that has an option for Sustained perf mode) and it seems to operate as you'd expect. When rotating back and forth, the mode sticks and the CPU is consistent at 1.2Ghz.

Linked to another capture:
https://gfycat.com/TornFocusedCaterpillar
(full disclosure, I recently upgrade to the Android 9 preview, but the behavior I posted about was also present in 8.1.)

Also, not posting this to pressure you or anything, just for information's sake.

**Comment by hrydgard** [comment]
Okay, hm. Can't explain it though..

**Comment by szale9001** [comment]
App called CPU Stats
https://play.google.com/store/apps/details?id=jp.takke.cpustats&hl=en_US

It's wonky with how it displays CPU clusters, but its enough to get the info I need.

**Comment by unknownbrackets** [comment]
Are there any open source Android apps which use this feature and work properly, that we could perhaps reference?

-[Unknown]

**Comment by szale9001** [comment]
I did some googling and couldn't really find much. I did find a repo for something called moonlight-stream. Not sure what it is but they apparently use sustained perf mode.

https://github.com/moonlight-stream/moonlight-android

In this commit, they disable SPF during split screen
https://github.com/moonlight-stream/moonlight-android/commit/912925ef2c2aa0a24e2dd64cea58f9955f1fcae2

Not sure if it helps, but there you go.

**Comment by unknownbrackets** [comment]
Have the latest changes here helped or is it still happening?

-[Unknown]

**Comment by szale9001** [comment]
Sorry, just got around to testing this just now. Yes, it does seem to still occur despite latest changes.

**Comment by unknownbrackets** [comment]
I wonder if there would be drawbacks to calling setSustainedPerformanceMode just every second or even frame.

Maybe the only solution to our weird race conditions with backbuffer size (immersive) and sustained perf is a timer that rechecks them every 73 frames or something...

-[Unknown]

**Comment by unknownbrackets** [comment]
We call this a bit more now, has anything improved?  Make sure you're testing the latest git build (v1.9.3-754-g6edf4ddc5 or newer.)

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]

**Comment by unknownbrackets** [comment]
It shows as supported on my Pixel 1 (Android 10) with a slightly older version of PPSSPP, but not on a Pixel 5a (Android 11 or Android 12.)

-[Unknown]

**Comment by hrydgard** [comment]
I think they kinda gave up on the feature, it wasn't used a lot I guess
