### ISSUE TITLE
Hive Sweeper - NPEZ00214 crashes out after the title screen

### ISSUE THREAD

**Issue by benderscruffy** [hrydgard/ppsspp#11025]
PPSSPP v1.5.4-971-g97546d30f Windows 64 bit
after the title screen the game crashes out 
nothing but a blank screen
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/1988092/ppsspplog.zip)

**Comment by benderscruffy** [comment]
v1.6.3-526-g669079454
still the same problem
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/2437673/ppsspplog.zip)

**Comment by benderscruffy** [comment]
v1.7.5-566-gf316a6590
still the same problem
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/2961620/ppsspplog.zip)

**Comment by hrydgard** [comment]
Seems we might have some bad error handling or missing functionality in sceUtilityMsgDialogInitStart:

```
22:25:854 user_main    I[SCEUTIL]: HLE\sceUtility.cpp:349 00000000=sceUtilityMsgDialogInitStart(08897d18)
22:25:854 user_main    E[SCEUTIL]: Dialog\PSPMsgDialog.cpp:47 sceUtilityMsgDialogInitStart: invalid status
22:25:854 user_main    I[SCEUTIL]: HLE\sceUtility.cpp:349 00000000=sceUtilityMsgDialogInitStart(08897d18)
22:25:854 user_main    E[SCEUTIL]: Dialog\PSPMsgDialog.cpp:47 sceUtilityMsgDialogInitStart: invalid status
```

**Comment by hrydgard** [comment]
Still happens? Clean ISO?

**Comment by unknownbrackets** [comment]
What if you change:

```c++
	if (GetStatus() != SCE_UTILITY_STATUS_NONE) {
		ERROR_LOG_REPORT(SCEUTILITY, "sceUtilityMsgDialogInitStart: invalid status");
		return 0;
	}
```

To:

```c++
	if (GetStatus() != SCE_UTILITY_STATUS_NONE) {
		ERROR_LOG_REPORT(SCEUTILITY, "sceUtilityMsgDialogInitStart: invalid status");
		return SCE_ERROR_UTILITY_INVALID_STATUS;
	}
```

I'm mostly sure that's right, but haven't tested it.

-[Unknown]

**Comment by benderscruffy** [comment]
using v1.9.3-167-gb2dd3c7e1
still happens

**Comment by hrydgard** [comment]
I committed the change (finally :P ). Let's try it.

**Comment by benderscruffy** [comment]
goes ingame now
![hive](https://user-images.githubusercontent.com/2696404/76310581-03a21c80-630a-11ea-8c4e-31e0cd8ed4db.PNG)
