### ISSUE TITLE
Support Windows/ARM64 at some point

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#11027]
Yeah, it's coming, even proper desktop apps.

https://blogs.windows.com/buildingapps/2018/05/08/visual-studio-support-for-windows-10-on-arm-development/

**Comment by driver1998** [comment]
Just to show that I am working on it:
![批注 2019-04-30 063727](https://user-images.githubusercontent.com/22699485/57116437-b8cd8500-6d87-11e9-9aff-9ceeb29e2d5a.png)

**Comment by driver1998** [comment]
https://github.com/hrydgard/ppsspp/pull/12013
