### ISSUE TITLE
[Android] PPSSPP silent FC while playing Kingdom Hearts BBS (ULJM05775) in OpenGL

### ISSUE THREAD

**Issue by marcoslpaulo** [hrydgard/ppsspp#11029]
Xiaomi Mi A1
Android Oreo 8.0.0

PPSSPP crashes during battle in KHBBS if using OpenGL
The game works fine in Vulkan, but this device has better performance using OpenGL.

[logcat.txt](https://github.com/hrydgard/ppsspp/files/1989342/logcat.txt)

**Comment by unknownbrackets** [comment]
Is this not happening anymore in the latest version?

-[Unknown]

**Comment by marcoslpaulo** [comment]
It still happens
I was using Lenovo Zuk Z2 (Snapdragom 820 / 4gb ram) for a while and it didnt happen 
But I'm on marshmallow.

I guess it is related to android oreo (cant test on nougat)
App still dies on 8.0 and 8.1 on Xiaomi Mi A1 (Snapdragon 625 / 4gb)

**Comment by unknownbrackets** [comment]
Just to note:

> ioctl fd 49 code 0xc040094a (IOCTL_KGSL_GPU_COMMAND) failed: errno 71 Protocol error

This is the same error we're seeing on #11355.  Seems to be a driver bug in Oreo and higher, and doesn't happen in Vulkan.  We haven't figured out what behavior exactly is causing it, though.

-[Unknown]

**Comment by Gamemulatorer** [comment]
This can be also fix by adding this game to PixelDepthRounding?
