### ISSUE TITLE
I Kill Zombies - NPUZ00305 crashes out the emulator

### ISSUE THREAD

**Issue by benderscruffy** [hrydgard/ppsspp#11026]
PPSSPP v1.5.4-971-g97546d30f Windows 64 bit
after the intro the emulator crashes out
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/1988115/ppsspplog.zip)

**Comment by benderscruffy** [comment]
v1.6.3-526-g669079454
still the same problem
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/2437680/ppsspplog.zip)

**Comment by benderscruffy** [comment]
v1.7.5-566-gf316a6590
still the same problem
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/2965834/ppsspplog.zip)

**Comment by hrydgard** [comment]
Log ends with:
```
10:45:150 user_main    D[ME]: HLE\sceMpeg.cpp:1423 73=sceMpegRingbufferAvailableSize(09fff364)
10:45:150 user_main    D[SCEKERNEL]: HLE\sceKernelMutex.cpp:567 sceKernelLockMutex(444, 1, 00000000)
10:45:150 user_main    D[SCEKERNEL]: HLE\sceKernelMutex.cpp:646 sceKernelUnlockMutex(444, 1)
10:45:150 user_main    D[ME]: HLE\sceMpeg.cpp:1699 0=sceMpegGetAtracAu(09fff360, 00000006, 09fff42c, 09fff310)
10:45:150 idle0        D[SCEKERNEL]: HLE\sceKernelThread.cpp:3056 Context switch: user_main -> idle0 (276->272, pc: 088504e0->08000000, mpeg get atrac) +16us
10:45:150 user_main    D[SCEKERNEL]: HLE\sceKernelThread.cpp:3056 Context switch: idle0 -> user_main (272->276, pc: 08000000->088504e0, woke from hle delay) +100us
10:45:150 user_main    W[MEMMAP]: MemmapFunctions.cpp:92 ReadFromHardware: Invalid address 00000000
10:45:150 user_main    D[ME]: HLE\sceMpeg.cpp:1901 sceMpegAtracDecode(09fff360, 09fff42c, 00000000, 1)
10:45:150 user_main    W[MEMMAP]: MemmapFunctions.cpp:128 WriteToHardware: Invalid address 00000000
```
Some kind of misbehaviour with sceMpeg Atrac decoding seems likely though definitely not certain...

**Comment by Emulatorer** [comment]
@hrydgard this out of topic but you add this issue to v1.10.0? not v1.9.0?

**Comment by benderscruffy** [comment]
using v1.9.3-167-gb2dd3c7e1
still happens

**Comment by benderscruffy** [comment]
goes one screen further then crashes out the emulator
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/4025332/ppsspplog.zip)
please reopen

**Comment by shenweip** [comment]
I guess you enable the fast memory?If yes,what happen if you diable that option?

**Comment by benderscruffy** [comment]
no i dont have fast memory enabled it is always disabled

**Comment by unknownbrackets** [comment]
That log mainly has video and font stuff in it.  I wonder if the recent changes helped - any changes here?

-[Unknown]

**Comment by shenweip** [comment]
I can confirm this had been fixed now, maybe by font alloc callback stuff.
