### ISSUE TITLE
Android: Configure "app bundle" to get automatic split APK by ABI from Play Store

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#11033]
https://developer.android.com/guide/app-bundle/configure

Very useful new feature that lets Google Play automatically generate minimal APKs only including the native binaries for each platform, greatly reducing the size of the APKs most users will get installed on their devices.

This is not useful for buildbot etc, those APKs still should include all ABIs, it's only for the release builds I make and upload to Google Play.

**Comment by Florin9doi** [comment]
Is there anything left to do? 
./gradlew bundleDebug seems to work
