### ISSUE TITLE
Crash on open program thru command line

### ISSUE THREAD

**Issue by tilkinsc** [hrydgard/ppsspp#11030]
### What happens?
A generic crash with message

### What *should* happen?
A message or rightful continuation of program

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Windows, Vulkan, PPSSPP v1.5.4 dev 971

When you try to open an EBOOT.PBP or ELF from hard drive, but it is not found, a generic program-generated message pops up and crashes the application. However, since it isn't found the program should just continue normally, or better yet display a message file couldn't be found too.

**Comment by hrydgard** [comment]
Huh, indeed! I'll fix it up.

**Comment by tilkinsc** [comment]
Arghh I didn't even check the console window! Forgot about that.

**Comment by hrydgard** [comment]
That's not the console window, it's the debugger. And I found the problem.

**Comment by tilkinsc** [comment]
Same thing.

**Comment by hrydgard** [comment]
Huh, indeed. It's behaving differently when I run it from VS with argument vs from the actual command line... Weird.

**Comment by hrydgard** [comment]
Oh never mind, I was running the wrong EXE.  For me it works now at least on Windows..
