### ISSUE TITLE
Gods Eater Burts graphics bugs in the Tranquil Temple

### ISSUE THREAD

**Issue by Jinzombie** [hrydgard/ppsspp#11039]
### What happens?
There's a grapics bugs in the Tranquil Temple showing small black square in the floor

### What *should* happen?
There's should no that in the floor

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Mali-450
Android 5.1
Octacore CPU
PPSSPP 1.5.4-991

**Comment by SamueldeSena** [comment]
try lowering the resolution to 1xpsp or 2 psp

**Comment by marosis** [comment]
This is 1xPSP resolution @SamueldeSena

**Comment by unknownbrackets** [comment]
I feel like this was some Mali driver bug, and seen in other games like Monster Hunter even.

I vaguely recall it being depth related?  It might help to try toggling HighQualityDepth in ppsspp.ini if so (there is no UI for this setting.)

-[Unknown]

**Comment by Jinzombie** [comment]
No changes happen :(
I change the HighQualityDepth number from the default is 1 so I try 0,2 & 3 the black square still there.

*Sorry for my bad english

**Comment by Jinzombie** [comment]
In PPSSPP 1.6.2 showing a grey color in the right side when immersive is on 
![screenshot_2018-05-31-11-15-00](https://user-images.githubusercontent.com/37603562/40820217-d0a75490-654e-11e8-87d9-da61f574b022.png)
only happen during introduction movie

**Comment by Jinzombie** [comment]
The graphics bugs it's not only showing in Tranquil Temple and I think it's the same issue as #7218 because it's only happen in Mali-400 & Mali-450 as I tested it on Mali-T720 the graphics bugs didn't ahow up.
So I will close this issue :)
