### ISSUE TITLE
Feature request : AES-NI (AES Hardware Acceleration)

### ISSUE THREAD

**Issue by zminhquanz** [hrydgard/ppsspp#11048]
There a lot of processor present from Intel, AMD and ARM64 ( aarch64) support AES-NI
You can see : RPCS3/rpcs3#2457

**Comment by leopard20** [comment]
This isn't supported on Android though, is it?

**Comment by zminhquanz** [comment]
@leopard20 i don't think android isn't support AES though
https://stackoverflow.com/questions/8622367/what-are-best-practices-for-using-aes-encryption-in-android?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by hrydgard** [comment]
PPSSPP only does crypto when it loads a game and it's definitely not the performance bottleneck. Using hardware accelerated decryption would not speed up things noticeably.
