### ISSUE TITLE
Retroficial by Titan all demos reset back to ppsspp game menu

### ISSUE THREAD

**Issue by benderscruffy** [hrydgard/ppsspp#11040]
PPSSPP v1.5.4-993-gab65c5210 Windows 64 bit
shows the menu but what ever demo you choose it resets back to ppsspp game menu
can be download
http://www.pouet.net/prod.php?which=20995

**Comment by benderscruffy** [comment]
no problems with it now

**Comment by unknownbrackets** [comment]
Very interesting, wonder what fixed it.  Thanks for retesting.

-[Unknown]
