### ISSUE TITLE
Add Replace & Save Textures from developer options to Windows's PPSSPP bar.

### ISSUE THREAD

**Issue by AkiraJkr** [hrydgard/ppsspp#11046]
I think this feature could be nice, because it's a chore having to pause the game everytime I wanna see the difference with and without the textures, and test things.

Perhaps add it to the Debug bar?
![image](https://user-images.githubusercontent.com/27028529/40208857-4af80ab6-5a12-11e8-94c7-8bbce9e9061e.png)

**Comment by LunaMoo** [comment]
Not exactly that, but we have IMO a better option right now where you can just set a hotkey to dump / replace textures, so I'll close this request, can reopen later if you disagree.
