### ISSUE TITLE
nehetutorial demos 6-10 dont load

### ISSUE THREAD

**Issue by benderscruffy** [hrydgard/ppsspp#11051]
PPSSPP v1.5.4-993-gab65c5210 Windows 64 bit
nehetutorial demos 6-10 dont load and just return to the ppsspp game menu
but nehetutorial demos 1-5 do load 
[demos.zip](https://github.com/hrydgard/ppsspp/files/2019159/demos.zip)

**Comment by LunaMoo** [comment]
All of those should work, the archive simply doesn't have required files, it's looking for:
````
NeHe.bmp
Crate.bmp
glass.bmp
Star.bmp
mud.bmp
world.txt
````
all in 
````
memstick\PSP\GAME\Data
````
They can't work without the files they require as such closing.

**Comment by benderscruffy** [comment]
just wondering as they work in Jpcsp

**Comment by hrydgard** [comment]
if the work in jpcsp, you might have those files in jpscp's memstick folder?

**Comment by benderscruffy** [comment]
yep it works in ppsspp if you put the data file in
 my mistake 
closed
