### ISSUE TITLE
Apollonia nothing but a blank screen

### ISSUE THREAD

**Issue by benderscruffy** [hrydgard/ppsspp#11050]
PPSSPP v1.5.4-993-gab65c5210 Windows 64 bit
nothing but a blank screen
http://www.brewology.com/downloads/get.php?id=9550

**Comment by LunaMoo** [comment]
Create an empty file called timidity.cfg in the homebrew dir;p.

**Comment by benderscruffy** [comment]
ok that worked thanks for that

**Comment by unknownbrackets** [comment]
Is this just a bug in the homebrew, requiring that file, or is it a bug in PPSSPP and should work without that file?

-[Unknown]

**Comment by Gamemulatorer** [comment]
Using ppsspp latest git build.
![Screenshot_20200604-175300](https://user-images.githubusercontent.com/37603562/83744995-7fa0cc00-a68f-11ea-975d-22c12f72003b.png)
![Screenshot_20200604-175439](https://user-images.githubusercontent.com/37603562/83745000-82032600-a68f-11ea-9edd-7f93f5590096.png)
@benderscruffy still an issue on your platform?

**Comment by hrydgard** [comment]
I think we can just close this, seems it's working alright. Hopefully if someone has the issue of a missing timidity file they'll arrive here by googling.

**Comment by Gamemulatorer** [comment]
@hrydgard not gonna add to v1.10 milestone?

**Comment by hrydgard** [comment]
I don't know when it was fixed (or if it was ever only the missing timidity.cfg).

**Comment by hrydgard** [comment]
Ah good to know. Still, no idea when it was fixed, so not tagging. Doesn't matter much anyway

**Comment by Gamemulatorer** [comment]
@hrydgard ok :) waiting for v1.10.0 to release this month.
