### ISSUE TITLE
Crash on Savestate when => Skipbuffer Effects is enabled (on any game) (GPD XD)

### ISSUE THREAD

**Issue by ChurroBoi** [hrydgard/ppsspp#11056]
PPSSPP dev version 1.5.4-979, however after trying earlier dev build issue seems to be present even around 1.5.4-400 and still looking. Gplay version is fine. Savestate on buffered rendering is fine. 
Using GPD XD, legacyrom, kitkat 4.4.4

[alogcat.2018-05-20-19-22-10+1000.txt](https://github.com/hrydgard/ppsspp/files/2020196/alogcat.2018-05-20-19-22-10.1000.txt)

**Comment by unknownbrackets** [comment]
I guess it's likely crashing while trying to take a screenshot.

-[Unknown]

**Comment by unknownbrackets** [comment]
Hmm... not crashing for me.

Does this perhaps not happen in all games, or require more steps?  What I did:

1. Hit back button.
2. Clicked Save on the pause menu next to slot 1.

Tried both OpenGL and Vulkan on a Pixel in Legend of Heroes 3.

-[Unknown]

**Comment by hrydgard** [comment]
If I remember correctly, the GPD XD was very sensitive to any GL errors. Gonna run on one of my older devices and watch out for GL error codes..

**Comment by AkiraJkr** [comment]
I have the same issue on Direct3D9 but with Buffered Rendering.

**Comment by unknownbrackets** [comment]
Did any of the app switching fixes perhaps help this?  Does it happen in the latest git?

-[Unknown]

**Comment by vsub** [comment]
In my case it was crashing only with DX11 while using non buffered rendering
The latest beta fixes the problem

**Comment by ChurroBoi** [comment]
Still experiencing the problem here. On GPD XD the application seems to be extremely crash sensitive at the moment. Click on any links in the menu, crash. Switch apps, crash. Save on skip-buffer, crash. 
I wonder if this is a universal issue with the GPD XD?

**Comment by hrydgard** [comment]
Still having issues with gl errors happening during task switching, which I need to dig into... Fixing that will probably fix the crashes, given what we know about how sensitive the GPD XD are to those.

**Comment by ChurroBoi** [comment]
Hey! @hrydgard I managed to fix the save state issue through the gltools application, Legacy ROM on the GPD XD is set to fake device id as a Nexus 5 by default, by setting the fake device template to a Mali-T760 which is the XD's actual GPU, it resolved the Save state crashing issue. Not sure if that helps, but the other crash related issues such as crash on switching apps, menu links, and changing display resolution are still present.

**Comment by hrydgard** [comment]
the non save state crashes on GPD XD are reported here: https://github.com/hrydgard/ppsspp/issues/11063

**Comment by ChurroBoi** [comment]
Issue seems all cleared up to me :) thanks! Good job.
