### ISSUE TITLE
Sunday Vs Magazine Shuuketsu! Choujou Daikessen (Japan) crashes out after the intro

### ISSUE THREAD

**Issue by benderscruffy** [hrydgard/ppsspp#11060]
PPSSPP v1.5.4-995-g373366911 Windows 64 bit
choose arcade mode and after you choose your character  and opponent the intro plays and after that it goes to play music but then static and nothing but a black screen
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/2021031/ppsspplog.zip)

**Comment by unknownbrackets** [comment]
```
35:48:388 sndp thread  E[SCEAUDIO]: HLE\sceAudio.cpp:114 sceAudioOutputPannedBlocking() - bad channel
35:48:388 sndp thread  D[SCEAUDIO]: HLE\sceAudio.cpp:130 80260003 = sceAudioOutputPannedBlocking(10080000, 00008000, 00008000, 08c85fc0)
35:48:389 sndp thread  I[SCEIO]: HLE\sceIo.cpp:1017 stdout: sceWaveAudioWriteBlocking failed 80260003!!!!!!!!!!!!!!!!!!!!!
```

That error is SCE_ERROR_AUDIO_INVALID_CHANNEL.  I wonder if this is a thread timing issue.

But it first goes wrong here:

```
35:46:990 sndp thread  D[SCEAUDIO]: HLE\sceAudio.cpp:130 00000100 = sceAudioOutputPannedBlocking(00000004, 00008000, 00008000, 08c85bc0)
35:46:990 sxm_main     D[SCEKERNEL]: HLE\sceKernelThread.cpp:30 Context switch: sndp thread -> sxm_main (288->276, pc: 088f2cac->0880970c, blocking audio) +13us
35:46:992 sndp thread  D[SCEKERNEL]: HLE\sceKernelThread.cpp:30 Context switch: sxm_main -> sndp thread (276->288, pc: 08809764->088f2cac, audio drain) +5597us
35:46:992 sndp thread  W[MEMMAP]: MemmapFunctions.cpp:91 ReadFromHardware: Invalid address 10080000
```

It's output other audio to the same address, so I'm not sure why it's suddenly getting invalid accesses.  After that, it starts making weird wrong SAS calls, so it definitely seems like that thread's memory got corrupted.

-[Unknown]

**Comment by benderscruffy** [comment]
v1.7.1-210-g9bda7cb64
goes ingame now
![sunday](https://user-images.githubusercontent.com/2696404/49130399-b1084100-f30e-11e8-9aa4-a327c04125d7.PNG)

**Comment by unknownbrackets** [comment]
Interesting - I wonder what fixed this.

-[Unknown]

**Comment by nassau-tk** [comment]
[Android][OpenGL/Vulkan]

This issue is not fix on the Android.

PPSSPP Ver. : 1.8.0-617
OS: Android 9.0
DeviceName: SONY SO-02K / Xperia XZ1 Compact (Japan)
CPU: Snapdragon835 (Octa-core)
GPU: Adreno 540
Resolution: 720×1280
RAM: 4GB
ROM:32GB
ExternalStrage: microSDXC 512GB

[recording_ULJM05450.zip](https://github.com/hrydgard/ppsspp/files/3620338/recording_ULJM05450.zip)

**Comment by nassau-tk** [comment]
I tested on the Windos10(64-bit).
The issue happen on the Windows PPSSPP too yet.
PPSSPP crash when the movie finished.
You can play the game when If you skip the movie.

PPSSPP: v1.9.3-656
CPU: i7-4770K
GPU: GeForce750Ti
RAM: 16GB
OS:Windows10 Home

**Comment by nassau-tk** [comment]
![sunday_vs_magazine_error](https://user-images.githubusercontent.com/48179091/88283448-58c55480-cd26-11ea-8b76-535b91aca107.png)

**Comment by sum2012** [comment]
I will get a look when my mpeg pull request merged

**Comment by sum2012** [comment]
Where is the crash video ?
I test no problem in intro.

**Comment by nassau-tk** [comment]
@sum2012 

Please, See movie from below link.(On my Google drive)
https://drive.google.com/file/d/1dJEDLJWicQfM-rn5n2BRq_t_DG13CI4K/view?usp=sharing

The points of issue is not intro movie of wakeup.

1 Select a character.(Any character is OK.)
2 Intro movie is play per character.
3 Freeze!(Invalid Memory Access Error.)

[Log]
14:07:325 sxm_main     D[G3D]: gpu\gpucommon.cpp:1205 Starting DL execution at 08a16b40 - stall = 00000000
14:07:325 sxm_main     D[G3D]: gpu\gpucommon.cpp:1374 Signal without wait. signal/end: 0000 0000
14:07:325 sxm_main     D[SCEGE]: hle\scege.cpp:348 35000008=sceGeListEnQueue(08a16b40, 00000000, 0, 09fff650[00000010])
14:07:325 idle0        D[SCEKERNEL]: hle\scekernelthread.cpp:3107 Context switch: sxm_main -> idle0 (276->272, pc: 08807dc0->08000000, interrupt) +47us
14:07:325 idle0        D[CPU]: hle\scege.cpp:121 Entering GE interrupt handler 0880a050
14:07:325 idle0        D[SCEKERNEL]: hle\scekerneleventflag.cpp:311 0=sceKernelSetEventFlag(282, 00000001)
14:07:325 idle0        D[G3D]: gpu\gpucommon.cpp:1205 Starting DL execution at 08a16b48 - stall = 00000000
14:07:325 idle0        D[G3D]: common\framebuffermanagercommon.cpp:200 Est: 04044000 V: 480x272, R: 480x272, S: 480x272, STR: 512, THR:1, Z:44088000 = 480x272
14:07:325 idle0        D[FRAMEBUF]: common\framebuffermanagercommon.cpp:4 Switching render target to FBO for 04044000: 480 x 272 x 1
14:07:325 idle0        D[G3D]: gpu\gpucommon.cpp:1374 Signal without wait. signal/end: 0001 0000
14:07:325 sxm_main     D[SCEKERNEL]: hle\scekernelthread.cpp:3107 Context switch: idle0 -> sxm_main (272->276, pc: 08000000->08807dc0, left interrupt) +9us
14:07:325 idle0        D[SCEKERNEL]: hle\scekernelthread.cpp:3107 Context switch: sxm_main -> idle0 (276->272, pc: 08807dc0->08000000, interrupt) +5us
14:07:325 idle0        D[CPU]: hle\scege.cpp:121 Entering GE interrupt handler 0880a050
14:07:325 idle0        D[SCEKERNEL]: hle\scekerneleventflag.cpp:311 0=sceKernelSetEventFlag(282, 00000001)
14:07:325 idle0        D[G3D]: gpu\gpucommon.cpp:1205 Starting DL execution at 08a16cf8 - stall = 00000000
14:07:325 idle0        D[G3D]: common\texturecachecommon.cpp:711 Texture different or overwritten, reloading at 09283c80: different params
14:07:325 idle0        D[G3D]: gpu\gpucommon.cpp:1374 Signal without wait. signal/end: 0002 0000
14:07:325 sxm_main     D[SCEKERNEL]: hle\scekernelthread.cpp:3107 Context switch: idle0 -> sxm_main (272->276, pc: 08000000->08807dc0, left interrupt) +11us
14:07:325 idle0        D[SCEKERNEL]: hle\scekernelthread.cpp:3107 Context switch: sxm_main -> idle0 (276->272, pc: 0884cd18->08000000, interrupt) +18us
14:07:325 idle0        D[CPU]: hle\scege.cpp:121 Entering GE interrupt handler 0880a050
14:07:325 idle0        D[SCEKERNEL]: hle\scekerneleventflag.cpp:311 0=sceKernelSetEventFlag(282, 00000001)
14:07:325 idle0        D[G3D]: gpu\gpucommon.cpp:1205 Starting DL execution at 08a17834 - stall = 00000000
14:07:325 idle0        D[G3D]: gpu\gpucommon.cpp:1374 Signal without wait. signal/end: 0003 0000
14:07:325 sxm_main     D[SCEKERNEL]: hle\scekernelthread.cpp:3107 Context switch: idle0 -> sxm_main (272->276, pc: 08000000->0884cd18, left interrupt) +11us
14:07:325 idle0        D[SCEKERNEL]: hle\scekernelthread.cpp:3107 Context switch: sxm_main -> idle0 (276->272, pc: 0884cd18->08000000, interrupt) +5us
14:07:325 idle0        D[CPU]: hle\scege.cpp:121 Entering GE interrupt handler 0880a050
14:07:325 idle0        D[SCEKERNEL]: hle\scekerneleventflag.cpp:311 0=sceKernelSetEventFlag(282, 00000001)
14:07:325 idle0        D[G3D]: gpu\gpucommon.cpp:1205 Starting DL execution at 08a1783c - stall = 00000000
14:07:325 idle0        D[G3D]: gpu\gpucommon.cpp:1374 Signal without wait. signal/end: 0004 0000
14:07:325 sxm_main     D[SCEKERNEL]: hle\scekernelthread.cpp:3107 Context switch: idle0 -> sxm_main (272->276, pc: 08000000->0884cd18, left interrupt) +11us
14:07:325 idle0        D[SCEKERNEL]: hle\scekernelthread.cpp:3107 Context switch: sxm_main -> idle0 (276->272, pc: 0884cd18->08000000, interrupt) +5us
14:07:325 idle0        D[CPU]: hle\scege.cpp:121 Entering GE interrupt handler 0880a050
14:07:325 idle0        D[SCEKERNEL]: hle\scekerneleventflag.cpp:311 0=sceKernelSetEventFlag(282, 00000001)
14:07:325 idle0        D[G3D]: gpu\gpucommon.cpp:1205 Starting DL execution at 08a17848 - stall = 00000000
14:07:325 idle0        D[G3D]: gpu\gpucommon.cpp:1374 Signal without wait. signal/end: 0005 0000
14:07:325 sxm_main     D[SCEKERNEL]: hle\scekernelthread.cpp:3107 Context switch: idle0 -> sxm_main (272->276, pc: 08000000->0884cd18, left interrupt) +11us
14:07:325 idle0        D[SCEKERNEL]: hle\scekernelthread.cpp:3107 Context switch: sxm_main -> idle0 (276->272, pc: 0884cd18->08000000, interrupt) +5us
14:07:325 idle0        D[CPU]: hle\scege.cpp:121 Entering GE interrupt handler 0880a050
14:07:325 idle0        D[SCEKERNEL]: hle\scekerneleventflag.cpp:311 0=sceKernelSetEventFlag(282, 00000001)
14:07:325 idle0        D[G3D]: gpu\gpucommon.cpp:1205 Starting DL execution at 08a17850 - stall = 00000000
14:07:325 sxm_main     D[SCEKERNEL]: hle\scekernelthread.cpp:3107 Context switch: idle0 -> sxm_main (272->276, pc: 08000000->0884cd18, left interrupt) +10us
14:07:325 idle0        D[SCEKERNEL]: hle\scekernelthread.cpp:3107 Context switch: sxm_main -> idle0 (276->272, pc: 0884cd18->08000000, interrupt) +5us
14:07:325 idle0        D[CPU]: hle\scege.cpp:121 Entering GE interrupt handler 0880a0d0
14:07:325 sxm_main     D[SCEKERNEL]: hle\scekernelthread.cpp:3107 Context switch: idle0 -> sxm_main (272->276, pc: 08000000->0884cd18, left interrupt) +6us
14:07:325 sxm_main     D[SCEKERNEL]: hle\scekernelmutex.cpp:562 sceKernelLockMutex(311, 1, 00000000)
14:07:325 sxm_main     D[SCEKERNEL]: hle\scekernelmutex.cpp:641 sceKernelUnlockMutex(311, 1)
14:07:325 sxm_main     D[SCEKERNEL]: hle\scekernelmutex.cpp:562 sceKernelLockMutex(311, 1, 00000000)
14:07:325 sxm_main     D[SCEKERNEL]: hle\scekernelmutex.cpp:641 sceKernelUnlockMutex(311, 1)
14:07:325 sxm_main     D[ME]: hle\scempeg.cpp:1630 0=sceMpegGetAvcAu(09b7b340, 00000003, 09b78dfc, 09fff640)
14:07:325 idle0        D[SCEKERNEL]: hle\scekernelthread.cpp:3107 Context switch: sxm_main -> idle0 (276->272, pc: 08995170->08000000, mpeg get avc) +532us
14:07:325 sxm_main     D[SCEKERNEL]: hle\scekernelthread.cpp:3107 Context switch: idle0 -> sxm_main (272->276, pc: 08000000->08995170, woke from hle delay) +100us
14:07:325 sxm_main     D[ME]: hle\scempeg.cpp:1306 *buffer = 091cbe80, *init = 00000001
14:07:325 sxm_main     D[ME]: hle\scempeg.cpp:1333 sceMpegAvcDecodeYCbCr(09b7b340, 09b78dfc, 08a97f9c, 09fff644)
14:07:325 idle0        D[SCEKERNEL]: hle\scekernelthread.cpp:3107 Context switch: sxm_main -> idle0 (276->272, pc: 089951a8->08000000, mpeg decode) +5us
14:07:325 sndp thread  D[SCEKERNEL]: hle\scekernelthread.cpp:3107 Context switch: idle0 -> sndp thread (272->288, pc: 08000000->088f2cac, audio drain) +1481us
14:07:325 sndp thread  D[SCESAS]: hle\scesas.cpp:302 0=__sceSasCore(08a6de40, 08c85fc0)
14:07:325 idle0        D[SCEKERNEL]: hle\scekernelthread.cpp:3107 Context switch: sndp thread -> idle0 (288->272, pc: 088ee624->08000000, sas core) +13us
14:07:325 sndp thread  D[SCEKERNEL]: hle\scekernelthread.cpp:3107 Context switch: idle0 -> sndp thread (272->288, pc: 08000000->088ee624, woke from sas mix) +173us
14:07:325 sndp thread  D[SCESAS]: hle\scesas.cpp:720 sceSasGetAllEnvelopeHeights(08a6de40, 167508480)
14:07:325 sndp thread  D[SCEAUDIO]: hle\sceaudio.cpp:131 00000100 = sceAudioOutputPannedBlocking(00000004, 00008000, 00008000, 08c85fc0)
14:07:325 idle0        D[SCEKERNEL]: hle\scekernelthread.cpp:3107 Context switch: sndp thread -> idle0 (288->272, pc: 088f2cac->08000000, blocking audio) +6us
14:07:325 DisplayThrea D[SCEKERNEL]: hle\scekernelthread.cpp:3107 Context switch: idle0 -> DisplayThread (272->314, pc: 08000000->08995ad8, woke from hle delay) +1521us
14:07:325 DisplayThrea D[SCEKERNEL]: hle\scekernelsemaphore.cpp:413 0=sceKernelWaitSema(313, 1, 0)
14:07:325 DisplayThrea D[SCEKERNEL]: hle\scekernelsemaphore.cpp:305 sceKernelSignalSema(313, 1) (count: 0 -> 1)
14:07:325 DisplayThrea D[SCEKERNEL]: hle\scekernelmutex.cpp:562 sceKernelLockMutex(311, 1, 00000000)
14:07:325 DisplayThrea D[SCEKERNEL]: hle\scekernelmutex.cpp:641 sceKernelUnlockMutex(311, 1)
14:07:325 idle0        D[SCEKERNEL]: hle\scekernelthread.cpp:3107 Context switch: DisplayThread -> idle0 (314->272, pc: 08995040->08000000, vblank start waited) +16us
14:07:325 sxm_main     D[SCEKERNEL]: hle\scekernelthread.cpp:3107 Context switch: idle0 -> sxm_main (272->276, pc: 08000000->089951a8, woke from hle delay) +2187us
14:07:325 sxm_main     D[SCEKERNEL]: hle\scekernelsemaphore.cpp:413 0=sceKernelWaitSema(313, 1, 0)
14:07:325 sxm_main     D[SCEKERNEL]: hle\scekernelsemaphore.cpp:305 sceKernelSignalSema(313, 1) (count: 0 -> 1)
14:07:325 sxm_main     D[SCEKERNEL]: hle\scekernelsemaphore.cpp:413 0=sceKernelWaitSema(313, 1, 0)
14:07:325 sxm_main     D[SCEKERNEL]: hle\scekernelsemaphore.cpp:305 sceKernelSignalSema(313, 1) (count: 0 -> 1)
14:07:325 sxm_main     D[SCEKERNEL]: hle\scekernelsemaphore.cpp:413 0=sceKernelWaitSema(313, 1, 0)
14:07:325 sxm_main     D[SCEKERNEL]: hle\scekernelsemaphore.cpp:305 sceKernelSignalSema(313, 1) (count: 0 -> 1)
14:07:325 sndp thread  D[SCEKERNEL]: hle\scekernelthread.cpp:3107 Context switch: sxm_main -> sndp thread (276->288, pc: 08809664->088f2cac, audio drain) +1886us
14:07:325 sndp thread  D[SCESAS]: hle\scesas.cpp:302 0=__sceSasCore(08a6de40, 08c85bc0)
14:07:325 sxm_main     D[SCEKERNEL]: hle\scekernelthread.cpp:3107 Context switch: sndp thread -> sxm_main (288->276, pc: 088ee624->08809664, sas core) +20us
14:07:325 sndp thread  D[SCEKERNEL]: hle\scekernelthread.cpp:3107 Context switch: sxm_main -> sndp thread (276->288, pc: 08995c90->088ee624, woke from sas mix) +173us
14:07:325 sndp thread  D[SCESAS]: hle\scesas.cpp:720 sceSasGetAllEnvelopeHeights(08a6de40, 167508480)
14:07:325 sndp thread  D[SCEAUDIO]: hle\sceaudio.cpp:131 00000100 = sceAudioOutputPannedBlocking(00000004, 00008000, 00008000, 08c85bc0)
14:07:325 sxm_main     D[SCEKERNEL]: hle\scekernelthread.cpp:3107 Context switch: sndp thread -> sxm_main (288->276, pc: 088f2cac->08995c90, blocking audio) +13us
14:07:326 sndp thread  D[SCEKERNEL]: hle\scekernelthread.cpp:3107 Context switch: sxm_main -> sndp thread (276->288, pc: 0880970c->088f2cac, audio drain) +5597us
14:07:326 sndp thread  W[MEMMAP]: core\core.cpp:443 Read Word: Invalid address 10080000 PC 088f0674 LR 088ef788 088f0674_z_un_088f05fc
movzx esi, byte [rbx+rax]

14:07:326 sndp thread  E[MEMMAP]: core\memfault.cpp:192 Bad memory access detected! 10080000 (000002718E1D0000) Stopping emulation. Info:
088f0674_z_un_088f05fc
movzx esi, byte [rbx+rax]

**Comment by sum2012** [comment]
v1.10.3-1375-g52c6169a5-windows-amd64 mpeg log:
https://gist.github.com/sum2012/94e50eadc97a7d292336ffe491ad4106

@nassau-tk I have no idea now.
I teach you about some logging:
When there is a video \audio problem
Need this setting 
![1](https://user-images.githubusercontent.com/2177532/103088824-023aaa00-4627-11eb-8dfc-bcd459763c23.jpg)
Then paste it in https://gist.github.com to share the log to contributor.

**Comment by nassau-tk** [comment]
@sum2012 
Thank you for teaching!!
Is this OK???
https://gist.github.com/nassau-tk/76d1e133323b778c7b6b968f52c84d24

**Comment by sum2012** [comment]
System->Developer tools->Logging channels->"ME" Change to "Debug",others change to "Info"

**Comment by nassau-tk** [comment]
Oops! Sorry.

When Load screen. (I found Red code .For reference.)
https://gist.github.com/nassau-tk/d6faf14b94053deb2f23089cc7be34bf

When play the character movie.(between start to error.)
https://gist.github.com/nassau-tk/3a44b01a3c270a3717faf6e31778b458

Is this right?:sweat_smile:

**Comment by sum2012** [comment]
Next time you post all log into the gist.
No need separate.

**Comment by nassau-tk** [comment]
OK!
I understood it.
Thank you for your kindness!!

**Comment by shenweip** [comment]
What happen if change sceMpeg.cpp line 1336
from
```javascript
Memory::Write_U32(ctx->avc.avcFrameStatus, initAddr);
```
to
```javascript
Memory::Write_U32(1, initAddr);
```
?

**Comment by sum2012** [comment]
Yes,It fix the crash
modify log: https://gist.github.com/sum2012/f0fbed7c1f75067319c4afc1cf8de289

**Comment by sum2012** [comment]
Take the record that this game's firmware is 5.03

**Comment by benderscruffy** [comment]
PPSSPP v1.13.1-234-g5434bd83e
still crashes out
![PPSSPP v1 13 1-234-g5434bd83e 8_08_2022 3_06_47 PM](https://user-images.githubusercontent.com/2696404/183367603-aefb46b8-184c-4ed1-b054-1e0c85f0b89e.png)
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/9279878/ppsspplog.zip)

**Comment by sum2012** [comment]
Update the log to v1.13.1-544-g31bd16a04 
https://gist.github.com/sum2012/0c50736b1b95968d50ef1406c1578e70

**Comment by Nekorozo** [comment]
v1.13.2, still crash after character FMV... Any Fix?

**Comment by sum2012** [comment]
update the log to v1.13.2-1209-ga26a353c2
[ppsspplogv1.13.2-1209-ga26a353c2.zip](https://github.com/hrydgard/ppsspp/files/9640801/ppsspplogv1.13.2-1209-ga26a353c2.zip)

**Comment by sum2012** [comment]
The game do not load mpeg.prx from disc0:\PSP_GAME\USRDIR\module\mpeg.prx
Will pull  request @shenweip method. Not sure is hack or not ........

**Comment by Nekorozo** [comment]
> Yes,It fix the crash modify log: https://gist.github.com/sum2012/f0fbed7c1f75067319c4afc1cf8de289

how to do this?

**Comment by sum2012** [comment]
> > Yes,It fix the crash modify log: https://gist.github.com/sum2012/f0fbed7c1f75067319c4afc1cf8de289
> 
> how to do this?

I will upload the build here if @hrydgard don't accept my patch.
You are run in windows or android ?

**Comment by Nekorozo** [comment]
Windows!

**Comment by sum2012** [comment]
> Windows!

[PPSSPPWindows64v1.3.2-1209m.zip](https://github.com/hrydgard/ppsspp/files/9641875/PPSSPPWindows64v1.3.2-1209m.zip)

**Comment by Nekorozo** [comment]
> > Windows!
> 
> [PPSSPPWindows64v1.3.2-1209m.zip](https://github.com/hrydgard/ppsspp/files/9641875/PPSSPPWindows64v1.3.2-1209m.zip)

Thank you so much!

**Comment by Gamemulatorer** [comment]
Still crashing using build from https://github.com/hrydgard/ppsspp/pull/16106
![Screenshot_2022-10-03-22-05-25-01](https://user-images.githubusercontent.com/37603562/193597881-e7db0257-fcff-4c77-95da-15d8dd03e406.png)

**Comment by Gamemulatorer** [comment]
Thanks it's finally fix it.
![Screenshot_2022-10-03-22-10-39-45](https://user-images.githubusercontent.com/37603562/193598968-2fe763d5-82df-4d0e-b712-d4535e68e7a2.png)

**Comment by sum2012** [comment]
Credit to @shenweip 
I just add some code from it,

**Comment by Gamemulatorer** [comment]
> Credit to @shenweip I just add some code from it,

Hoping you can also fix the crash issue of SOCOM Fireteam Bravo 3 https://github.com/hrydgard/ppsspp/issues/12730

**Comment by sum2012** [comment]
ok,I try again
> > Credit to @shenweip I just add some code from it,
> 
> Hoping you can also fix the crash issue of SOCOM Fireteam Bravo 3 #12730
