### ISSUE TITLE
PSP Camera - Invizimals Game - Camera image not being rendered

### ISSUE THREAD

**Issue by IncognitoJam** [hrydgard/ppsspp#11080]
### What happens?
In the game 'Invizimals' the image from the camera is not drawn to the screen, although the camera is working as the game can detect the colours. For example, the first task in the game is to point your camera at a red surface. The scanning screen is shown but all you can see on your screen is black:

![black screen](https://i.imgur.com/5te7t6Y.png)

However, if you point your camera at a red surface (I opened Google Images and searched for red as an example) it will detect the colour red. This shows that the camera is functioning and that this is a rendering issue.
![detecting red](https://i.imgur.com/M6oVufU.png)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
I am using a Samsung Galaxy S5 (klte) using Lineage OS 15.1. The camera app on my phone works correctly. I am using the latest version of the app from the play store (`v1.5.4`)

**Comment by IncognitoJam** [comment]
I have confirmed that this is also an issue on the latest release `v1.6`.

**Comment by IncognitoJam** [comment]
This issue seems to have been known about since at least August last year. See [this comment](https://github.com/hrydgard/ppsspp/pull/9927#issuecomment-325200727) on the original camera support pull request.

**Comment by unknownbrackets** [comment]
Ah, thanks for catching that.

-[Unknown]
