### ISSUE TITLE
PPSSPP gold still have version 1.5.4

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#11083]

**Comment by hrydgard** [comment]
If you mean on the Play Store, that's because I'm doing a slow rollout to catch the worst bugs before everyone gets the new version.

**Comment by unknownbrackets** [comment]
https://www.ppsspp.org/version.json still even says 1.5.0, not 1.5.4, heh.

-[Unknown]

**Comment by hrydgard** [comment]
Well, I'm not updating version.json until i'm at 100% rollout. Yeah, it should be 1.5.4, but meh :)

**Comment by unknownbrackets** [comment]
Don't forget version.json... but I think everything else is updated.

-[Unknown]

**Comment by marosis** [comment]
Closing
