### ISSUE TITLE
Logcat for android?

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#11089]
Is possible create logcat for ppsspp on android, ios, etc.? It can run on the background. Maybe feature request? I will close it if not

**Comment by unknownbrackets** [comment]
#10909 is close, but won't catch crashes and system messages.  I think that's the responsibility of a different app.

-[Unknown]

**Comment by marosis** [comment]
Aha. So, what with this. Close?

**Comment by unknownbrackets** [comment]
Sure, let's close.  We'll wait to merge the new debugger features until the dust settles for any 1.6.x hotfix releases.

-[Unknown]
