### ISSUE TITLE
star ocean first departure invisible character sprite/ blinking screen while walking

### ISSUE THREAD

**Issue by joelolopez** [hrydgard/ppsspp#11086]
opengl: 

star ocean first departure invisible character sprite , but when walking there are times that a partial of character sprite is visible..  this issue has been fixed before, tried on 1.6

the screen blinks whenever the character move but the cahracter is now visible, tried on 1.6 other build

OS android 8.0 , Octa-core, 2360 MHz, ARM Cortex-A53, 64-bit, 16 nm , Mali-T830 MP2 , 4 GB RAM

**Comment by unknownbrackets** [comment]
This sounds similar to #10634.

-[Unknown]

**Comment by unknownbrackets** [comment]
Assuming this is using the GLES backend, #11192 has likely fixed the issue.  I'm going to close, but if I'm wrong, feel free to comment and we'll reopen.

-[Unknown]

**Comment by joelolopez** [comment]
already fixed thank you! using ppsspp-v1.6.3-219-gf3ab56e15-android
