### ISSUE TITLE
[Android] [OpenGL] If "Disable slower effects is unchecked" The 3rd Birthday is very slow

### ISSUE THREAD

**Issue by Emulatorer** [hrydgard/ppsspp#11092]
<!-- Want the issue fixed faster?  Check the wiki for tips:
https://github.com/hrydgard/ppsspp/wiki/How-to-report-an-issue-properly
You can remove this stuff - just don't forget to answer the questions.  They're important. --

### What happens?
The game The 3rd Birthday & Brave: New Traveler become very slow when disable slower is disable

### What *should* happen?
The games run smooth in default settings

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Android 5.1
Mali-450 MP
PPSSPP 1.6

**Comment by Jinzombie** [comment]
The two games run smooth in even in default using ppsspp 1.5.4

**Comment by Jinzombie** [comment]
![screenshot_2018-05-28-23-27-25](https://user-images.githubusercontent.com/37603562/40621560-d12f0440-628c-11e8-8071-4f334d30d6b2.png)
And also when I overdrive there's a grapics bugs in The 3rd Birthday (Disable Slower Effects is On)
Im using now the latest ppsspp version 1.6
Phone Specs:
Android 5.1
Mali-450
OpenGL

**Comment by Jinzombie** [comment]
ppsspp 1.6.1
![screenshot_2018-05-29-14-46-55](https://user-images.githubusercontent.com/37603562/40668947-4c6e6038-6355-11e8-83bb-b67d45dbb5ef.png)

**Comment by Jinzombie** [comment]
In ppsspp-v1.5.4-931-g9c059a7b6 the game running 20+fps in default settings but in ppsspp-v1.5.4-933-g386c9d4fc the game running only 15+FPS in default settings

**Comment by Jinzombie** [comment]
This is just a minor issue enable "Disable Slower Effects" speed up the game with a little graphical issue 😃

**Comment by unknownbrackets** [comment]
So that's #10956.  Maybe there's a way to detect that it's not needed to to combine depals here, but it makes sense unfortunately that fixing #10951 would make it slower.

-[Unknown]

**Comment by hrydgard** [comment]
As mentioned in #10956 post processing the display lists like we do with Sonic Rivals on Vulkan is probably the only way to fix this properly, which takes some effort..

**Comment by leopard20** [comment]
@hrydgard I also notice slow-downs in other games as well. :(

**Comment by unknownbrackets** [comment]
For the purpose of recombining, it'd be nice to have some better meta information on the draws - ideally, the clut params / palette hash, source framebuf, and area (maybe this can be read from the verts.)  That might allow combining automatically in a general case.

At least for 3rd Birthday, that ought to allow combining.  In render-to-self cases, I don't know if it can be automatic without detecting the destination pixel area.  It's relatively uncommon, though...

-[Unknown]

**Comment by Emulatorer** [comment]
Sad to say 3rd birthday still lag when disable slower effects is OFF :(

**Comment by hrydgard** [comment]
Doing something clever here is too much work, it'll unfortunately have to be like this in 1.8.0.

**Comment by Emulatorer** [comment]
### UPDATE
Using ppsspp v1.8.0 graphics glitches is rarely happens if I enable the "Disable Slower Effects"

**Comment by Emulatorer** [comment]
Disable Slower Effects in the latest build cannot help speedup this games anymore so I will close this and for the meantime I will use skip buffered rendering for this games
Hoping someday this 2 games will improve performance in buffered rendering :)
The 3rd Birthday Skip Buffered Rendering
![Screenshot_20200324-105000](https://user-images.githubusercontent.com/37603562/77383464-ef582800-6dbd-11ea-92ae-8067e6c529cc.png)
Brave Story Skip Buffered Rendering
![Screenshot_20200324-105034](https://user-images.githubusercontent.com/37603562/77383477-f717cc80-6dbd-11ea-9284-d02fa13d825c.png)

**Comment by Emulatorer** [comment]
Reopened hoping for OpenGL shader depal as mentioned here https://github.com/hrydgard/ppsspp/issues/10908#issuecomment-421800480

**Comment by Emulatorer** [comment]
Closing the game is work fine so now
