### ISSUE TITLE
libretro texture scaling level black screen

### ISSUE THREAD

**Issue by BParks21** [hrydgard/ppsspp#11098]
### What happens?
When setting the texture scaling level to anything other than 1 in the libretro core a black screen is only visible. This only occurs when launching more than 1 psp game in one retroarch session

### What *should* happen?
I should be able to set the texture scaling level to any value without a black screen displaying after launching more than 1 game in a single session.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues. 
i7 7700k @4.9GHz, Asus GTX 1080ti, 32gb ram, Windows 10 64bit. Every PPSSPP core I've tested in the past year. Desktop.

**Comment by BParks21** [comment]
Ok the black screen no longer occurs but now changes made to scaling do not take affect right away, i have to change the resolution or close and restart the content. Making changes simply isn't behaving the same way as upstream.

**Comment by BParks21** [comment]
I wasn't sure to open this in the libretro issues or upstream https://github.com/libretro/ppsspp/issues/40

**Comment by BParks21** [comment]
This appears to be fixed in the most recent versions of RA.

**Comment by unknownbrackets** [comment]
Interesting, I don't think we really changed anything?  Glad it's fixed, thanks for reporting.

-[Unknown]
