### ISSUE TITLE
"Lower resolution for effects" missing in libretro port.

### ISSUE THREAD

**Issue by BParks21** [hrydgard/ppsspp#11099]
### What happens?
Having this feature is useful for things like misaligned bloom at higher than native resolutions. I use it quite often in upstream.

### What *should* happen?
Nothing just want the feature added.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
i7 7700k @4.9GHz, Asus GTX 1080ti, 32gb ram, Windows 10 64bit. Desktop.

**Comment by ToniBC** [comment]
Ok, thanks for answering, so this will be for the future version 1.11.0

So we just have to wait, to see if it comes as a Christmas gift.

Thank you.

**Comment by hrydgard** [comment]
Fix on the way in #13654
