### ISSUE TITLE
Latest stable version? 1.6 or 1.6.1?

### ISSUE THREAD

**Issue by ilovezfs** [hrydgard/ppsspp#11095]
https://github.com/hrydgard/ppsspp/releases shows a 1.6.1 tag
https://github.com/hrydgard/ppsspp/releases/latest points to 1.6

which should be in Homebrew?

**Comment by hrydgard** [comment]
1.6.1, fixed.

I wonder why you can't just have github automatically update this, hate having to do this manually.

**Comment by ilovezfs** [comment]
You can use the releases API for that: https://developer.github.com/v3/repos/releases/

Alternatively, delete all explicit GitHub releases and https://github.com/hrydgard/ppsspp/releases/latest just becomes a redirect to the tag list.
