### ISSUE TITLE
I can't get ppsspp v1.6 on official Cydia repo?

### ISSUE THREAD

**Issue by iOS4all** [hrydgard/ppsspp#11109]
As you see on the title there's still no ppsspp v1.6 on official ppsspp cydia repo?
Can you help please?

**Comment by hrydgard** [comment]
@angelXwind  any idea what's going on?

**Comment by iOS4all** [comment]
It’s appear on cydia.
Thanks for your help.

I’m gonna to close this issue because it’s solved.
