### ISSUE TITLE
[Direct3D9?] PSP2 - Missing UI

### ISSUE THREAD

**Issue by AkiraJkr** [hrydgard/ppsspp#11103]
For some reason, the UI seems to be missing in-game, mostly noticeable at the bottom-right part of it.
![image](https://user-images.githubusercontent.com/27028529/40681938-e0c88bfe-6360-11e8-8924-145c125f272d.png)

Pressing Start shows some of it briefly:
![image](https://user-images.githubusercontent.com/27028529/40681915-d2090cce-6360-11e8-9e8a-976f7f197528.png)

There's also the fact of the map showing up past the minimap square. This was tested with the default settings.

EDIT: Got a bit of debug log, transitioning from VN mode to In-game right at the game's start.
![image](https://user-images.githubusercontent.com/27028529/40682153-6bd99e2c-6361-11e8-95aa-3d49fdd63ede.png)

Plus, seems like text balloons also are cut from being drawn only at the minimap area.
![image](https://user-images.githubusercontent.com/27028529/40682295-c2c226be-6361-11e8-9dcc-f274d189f88b.png)

This issue is not present in Phantasy Star Portable, the UI drawing correctly. But it is in Phantasy Star Portable 2.

**Comment by joelolopez** [comment]
character sprite of star ocean first departure is missing too, maybe their related

**Comment by AkiraJkr** [comment]
Further to add here. The UI seems to render properly in 1.5.4

![image](https://user-images.githubusercontent.com/27028529/41811919-d28672ee-76ee-11e8-9ff7-aef84ec396b5.png)

Here is the same thing, but in 1.6.3

![image](https://user-images.githubusercontent.com/27028529/41811933-3f70fdac-76ef-11e8-9b17-0784871c0393.png)

**Comment by unknownbrackets** [comment]
https://github.com/hrydgard/ppsspp/compare/v1.5.4-387-g56eb2b892...v1.5.4-484-g22e28e218

Well, that means #10411.

These are the probably related changes:
 * https://github.com/hrydgard/ppsspp/compare/v1.5.4-387-g56eb2b892...v1.5.4-484-g22e28e218#diff-7cfe5975216a7fb6b8f90a974ea1ba6fL174
 * https://github.com/hrydgard/ppsspp/compare/v1.5.4-387-g56eb2b892...v1.5.4-484-g22e28e218#diff-f54cf59c770973ea3b832f805812410bL579

-[Unknown]

**Comment by vsub** [comment]
Works fine on 1.7 with DX9

**Comment by AkiraJkr** [comment]
Confirmed. This is for some reason fixed in 1.7. Weird. Wonder which update fixed it.

![image](https://user-images.githubusercontent.com/27028529/47667004-b0e81a80-db83-11e8-8874-65c5d5bdd341.png)
