### ISSUE TITLE
Black borders when HW scaler is not set to Native Disp. Res.

### ISSUE THREAD

**Issue by leopard20** [hrydgard/ppsspp#11102]
This is certainly not a big issue (and I'm assuming it's natural), but decided to report anyway in case it can be improved.

When HW scaler is set to anything other than Native, you can see black borders on either side of the display. 
HW scaler 3x (and 4x, etc):
![screenshot_2018-05-29-18-12-56-479_org ppsspp ppsspp](https://user-images.githubusercontent.com/16115820/40662913-d6647efa-636c-11e8-80cf-378985ebc96c.png)

HW scaler Native:
![screenshot_2018-05-29-18-13-14-518_org ppsspp ppsspp](https://user-images.githubusercontent.com/16115820/40662932-e0403f0e-636c-11e8-99b5-05c3d740b2e4.png)

**Comment by leopard20** [comment]
@hrydgard
Is this a valid issue or...?

**Comment by hrydgard** [comment]
I'm not actually sure. It doesn't seem to be very urgent either way so I'm bumping it to Future...

**Comment by hrydgard** [comment]
I'm not sure this is something we can ever fix reasonably, probably a platform issue. I'm closing.
