### ISSUE TITLE
Detect when PPSSPP is running inside a temp folder

### ISSUE THREAD

**Issue by unknownbrackets** [hrydgard/ppsspp#11114]
https://forums.ppsspp.org/showthread.php?tid=24383

I'm making an assumption, but a mistake users sometimes make is running an executable file from a zip.  Compression programs will create a folder inside Temp, run the program, and then delete once you exit.  Users may not understand why their saves and settings are "lost".

Ideally we should either show a message to the user (so they know their saves will be lost), or else just use the My Documents/PPSSPP approach.

-[Unknown]

**Comment by vsub** [comment]
I think it will be best to show a message.
For example if ppsspp if running inside the temp folder,every attempt to save(and maybe at the game start but the users may miss or ignore the message),it will also warn you.

In my case I use a ram drive which is set as the windows temp folder and I use that ram drive to download and test things before moving them to my hdd(in ppsspp case,replace the old version)

**Comment by unknownbrackets** [comment]
That makes sense - using the Documents folder silently would be confusing if you were intentionally running it in your temp folder and knew what that meant.

I'd be inclined to show the message in the way we do for Android.  It should mean you don't have any recent anyway.  Better then than after they've sorted out the file browser and configured all the settings.

-[Unknown]

**Comment by TehPlayer14** [comment]
Perhaps make an installer/self extracting archive to prevent this from happening?

**Comment by hrydgard** [comment]
We have an installer already, but only produce it for official builds.
