### ISSUE TITLE
PSP2 is crashing while using Vulkan and changing the resolution

### ISSUE THREAD

**Issue by vsub** [hrydgard/ppsspp#11113]
That includes using Auto and do any kind of window sizing.
When it crashes,first it shows a dialog with Yes and No and as info

Critical
dstrect offset y + extent > height
Try to continue?
Yes   No

Choosing No,kills the emulator and choosing Yes
Critical
Lost the Vulkan device!
Try to continue?
Yes   No

Choosing No,kills the emulator and choosing Yes shows the same dialog and you can hear the music for a second

It doesn't crash only on 1.4.2 and on the latest beta,there are some weird blinking things at the title screen while using vulkan on 1.6

This is the log
56:25:898 user_main    E[SCEKERNEL]: HLE\sceKernel.cpp:675 UNIMPL sceKernelReferGlobalProfiler(deadbeef)
56:41:539 user_main    E[ME]: HLE\sceMpeg.cpp:1971 UNIMPL sceMpegAvcInitYCbCr(09092700, 1, 480, 272, 086091c0)
56:41:539 user_main    E[ME]: HLE\sceMpeg.cpp:1971 UNIMPL sceMpegAvcInitYCbCr(09092700, 1, 480, 272, 08638f80)
56:41:539 user_main    E[ME]: HLE\sceMpeg.cpp:1971 UNIMPL sceMpegAvcInitYCbCr(09092700, 1, 480, 272, 08668d40)
56:41:539 user_main    E[ME]: HLE\sceMpeg.cpp:1971 UNIMPL sceMpegAvcInitYCbCr(09092700, 1, 480, 272, 08698b00)
56:41:840 user_main    E[ME]: HLE\sceMpeg.cpp:1335 UNIMPL sceMpegAvcDecodeFlush(09092700)
56:42:098 SOUND_THREAD E[ME]: HLE\sceAtrac.cpp:1695 80630016=sceAtracResetPlayPosition(0, 0, 0, 0): first byte count not in valid range
56:48:365 SOUND_THREAD E[ME]: HLE\sceAtrac.cpp:1695 80630016=sceAtracResetPlayPosition(0, 0, 0, 0): first byte count not in valid range
57:03:834 SOUND_THREAD E[ME]: HLE\sceAtrac.cpp:1695 80630016=sceAtracResetPlayPosition(0, 0, 0, 0): first byte count not in valid range
57:05:056 idle0        E[G3D]: thin3d\VulkanRenderManager.cpp:7 dstrect offset y + extent > height
57:05:056 idle0        E[SYSTEM]: MsgHandler.cpp:45 Critical: dstrect offset y + extent > height
58:42:000 idle0        E[SYSTEM]: MsgHandler.cpp:45 Critical: Lost the Vulkan device!

**Comment by hrydgard** [comment]
```
57:05:056 idle0 E[G3D]: thin3d\VulkanRenderManager.cpp:7 dstrect offset y + extent > height
57:05:056 idle0 E[SYSTEM]: MsgHandler.cpp:45 Critical: dstrect offset y + extent > height
58:42:000 idle0 E[SYSTEM]: MsgHandler.cpp:45 Critical: Lost the Vulkan device!
```
Seems we're doing some kind of blit outside bounds again...

**Comment by hrydgard** [comment]
Please test again with the latest.

**Comment by vsub** [comment]
Yes it works fine now on v1.6.2-14-gad1b75292,thanks
