### ISSUE TITLE
PICODRIVE incorrect buffers handling

### ISSUE THREAD

**Issue by r9guy** [hrydgard/ppsspp#11112]
### What happens?
[PicoDrive](http://notaz.gp2x.de/pico.php) Opensource Sega Genesis emulator
if using buffered redering mode , PPSSPP is not properly handles screen buffers. with each button press in main menu screen alternated between black and normal picture. 
if running in non buffered mode, upon pressing any button PPSSPP hangs.

Have tested with both OpenGL and Vulkan renderers

PPSSPP version 1.6.2.
no version known to work
Android OS v8

**Comment by LunaMoo** [comment]
Most emulator menus will just like in this case require Software Rendering to show correctly since they manyally copy bytes to VRAM instead of drawing the graphics correctly.

 Closing as something which will not be fixed following #9080
