### ISSUE TITLE
Vulkan: Glitches in God of War

### ISSUE THREAD

**Issue by Sunil2735** [hrydgard/ppsspp#11127]
### What happens?
Graphic issue in vulkan 

![screenshot_20180603-180419](https://user-images.githubusercontent.com/10764283/40886596-95312844-6758-11e8-8525-be25a0553221.jpg)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

One Plus 6
Snapdragon 845
Gpu adreno 630

**Comment by Sunil2735** [comment]
![screenshot_20180603-180419](https://user-images.githubusercontent.com/10764283/40886596-95312844-6758-11e8-8525-be25a0553221.jpg)

**Comment by hrydgard** [comment]
Ah, the little colored glitches? That doesn't look very good, indeed...

**Comment by leopard20** [comment]
Looks like a driver bug to me! Being a new device powered by a new GPU makes it even more likely!

**Comment by Sunil2735** [comment]
It's also on god of war chain of olympus

**Comment by Sunil2735** [comment]
Open gl is fine

**Comment by Sunil2735** [comment]
Today the issue was resolved with the new system update. Closing this one. 😁

**Comment by hrydgard** [comment]
Alright thanks, not gonna worry about this then. Created a new label to put on issues like this that are confirmed resolved by driver updates, "Confirmed Driver Bug".
