### ISSUE TITLE
FF Type-0 crash on GPD XD with button input

### ISSUE THREAD

**Issue by Kronicler27** [hrydgard/ppsspp#11125]
### What happens?

So like the title says FF Type-0 crashes after button input, specifically left analog input. It always occurs after this "combat end" screen seen below. This screen is shown when you defeat all the enemies on a map.

![screenshot_2018-06-02-21-12-25](https://user-images.githubusercontent.com/39868842/40882524-6219ceb0-66aa-11e8-958a-719bd556b118.png)

Pressing other buttons directly after this screen only causes a crash maybe 40% of the time, but left analog input always crashes the game. After 5-10 seconds if nothing is pressed, the game will not crash. I have remapped the left analog to the right stick, the face buttons, and even used the touch screen controls all with the same result. I have also verified the crash in 3 other locations in the game with the same "combat end" screen. It can also occur when clearing other maps without the "combat end" screen appearing.

The game also crashes inconsistently during other times, but only in combat. I believe it can happen during level up while in combat but am not sure. The game does not crash at any other time as far as I can tell.

Crashes with default settings, buffered and skipping buffered effects.

I have tested this with the same rom and save on both the Nexus 6p on 7.1.1 and a Kindle Fire HD 10 without the game crashing. 

### What *should* happen?

I should continue on my way and defeat the evil empire.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

I am using a GPD XD on android 4.4.4. Current version of PPSSPP is 1.6.2-14-gad1b75292. This crash has been occurring since the later versions of 1.5. Could have been happening at the first versions of 1.5 but those caused extreme flickering on my GPD XD. 

Version 1.4.2-824-g7ab403e32 does not have this issue.

**Comment by unknownbrackets** [comment]
Is it possible to obtain an adb logcat of the crash?

-[Unknown]

**Comment by Kronicler27** [comment]
Hey, just saw the email. On the latest version, v1.6.3-348-g404594da5, the game requires skip buffer effects to be on otherwise the game will crash upon loading. I can provide a logcat for that if you want, but here is the logcat of it still crashing in my original scenario:

--------- beginning of /dev/log/system
E/DrmService(  153): ----------------running drmservice---------------
E/DrmService(  153): ----------serianno =M3VR17GKCY
E/Vold    (  142): Start Misc devices Manager...
E/DrmService(  153): auto generate serialno,serialno = M3VR17GKCY
E/DrmService(  153): rknand_sys_storage open fail
E/DrmService(  153): detect keybox disabled
E/MountService(  521): updatePublicVolumeState get null volume
E/MobileDataStateTracker(  521): default: Ignoring feature request because could not acquire PhoneService
E/MobileDataStateTracker(  521): default: Could not enable APN type "default"
E/VoldConnector(  521): NDC Command {3 volume mount /mnt/external_sd} took too long (948ms)
E/ActivityThread(  750): Failed to find provider info for sms
E/ActivityThread(  766): Failed to find provider info for sms
E/ActivityThread(  766): Failed to find provider info for mms
E/ActivityThread(  766): Failed to find provider info for com.google.android.gm
E/ActivityThread(  972): Failed to find provider info for com.google.android.gm
E/ActivityThread(  972): Failed to find provider info for sms
E/ActivityThread(  972): Failed to find provider info for mms
E/ActivityThread(  972): Failed to find provider info for com.google.android.gm
F/ActivityManager(  521): Service ServiceRecord{41d64cb8 u0 com.google.android.gms/.chimera.PersistentDirectBootAwareApiService} in process ProcessRecord{41c33cd0 735:com.google.android.gms.persistent/u0a7} not same as in map: null
F/ActivityManager(  521): Service ServiceRecord{41cc31e0 u0 com.google.android.gms/.usagereporting.service.UsageReportingService} in process ProcessRecord{41c33cd0 735:com.google.android.gms.persistent/u0a7} not same as in map: null
E/ActivityThread( 1140): Failed to find provider info for sms
E/ActivityThread( 1140): Failed to find provider info for mms
E/ActivityThread( 1140): Failed to find provider info for com.google.android.gm
F/ProcessStats(  521): Starting service ServiceState{41cd2c60 com.android.smspush.WapPushManager pkg=com.android.smspush proc=41cd2c60} without owner
F/ProcessStats(  521): Starting service ServiceState{41cfb6a8 com.softwin.sd2flash.AutoStartServices pkg=com.softwin.sd2flash proc=41cfb6a8} without owner
F/ProcessStats(  521): Starting service ServiceState{41cd2c60 com.android.smspush.WapPushManager pkg=com.android.smspush proc=41cd2c60} without owner
F/ProcessStats(  521): Starting service ServiceState{41cfb6a8 com.softwin.sd2flash.AutoStartServices pkg=com.softwin.sd2flash proc=41cfb6a8} without owner
F/ProcessStats(  521): Starting service ServiceState{41cd2c60 com.android.smspush.WapPushManager pkg=com.android.smspush proc=41cd2c60} without owner
F/ProcessStats(  521): Starting service ServiceState{41cfb6a8 com.softwin.sd2flash.AutoStartServices pkg=com.softwin.sd2flash proc=41cfb6a8} without owner
--------- beginning of /dev/log/main
E/BaseAppContext( 1397): Tried to stop global GMSCore RequestQueue. This is likely unintended, so ignoring.
E/dalvikvm( 1678): Could not find class 'com.google.android.finsky.fc.e', referenced from method com.google.android.finsky.fc.c.a
E/PlayCommon( 1678): [166] com.google.android.play.b.g.a(412): Failed to connect to server: java.net.UnknownHostException: Unable to resolve host "play.googleapis.com": No address associated with hostname
E/dalvikvm( 1376): Could not find class 'com.google.common.flogger.backend.google.GooglePlatform', referenced from method ayeg.a
E/dalvikvm( 1847): Could not find class 'sun.nio.ch.DirectBuffer', referenced from method com.esotericsoftware.kryo.util.UnsafeUtil.releaseBuffer
E/dalvikvm( 1847): Could not find class 'java.util.Optional', referenced from method com.esotericsoftware.kryo.serializers.OptionalSerializers.addDefaultSerializers
E/dalvikvm( 1847): Could not find class 'java.util.OptionalInt', referenced from method com.esotericsoftware.kryo.serializers.OptionalSerializers.addDefaultSerializers
E/dalvikvm( 1847): Could not find class 'java.util.OptionalLong', referenced from method com.esotericsoftware.kryo.serializers.OptionalSerializers.addDefaultSerializers
E/dalvikvm( 1847): Could not find class 'java.util.OptionalDouble', referenced from method com.esotericsoftware.kryo.serializers.OptionalSerializers.addDefaultSerializers
E/dalvikvm( 1847): Could not find class 'java.time.Duration', referenced from method com.esotericsoftware.kryo.serializers.TimeSerializers.addDefaultSerializers
E/dalvikvm( 1847): Could not find class 'java.time.Instant', referenced from method com.esotericsoftware.kryo.serializers.TimeSerializers.addDefaultSerializers
E/dalvikvm( 1847): Could not find class 'java.time.LocalDate', referenced from method com.esotericsoftware.kryo.serializers.TimeSerializers.addDefaultSerializers
E/dalvikvm( 1847): Could not find class 'java.time.LocalTime', referenced from method com.esotericsoftware.kryo.serializers.TimeSerializers.addDefaultSerializers
E/dalvikvm( 1847): Could not find class 'java.time.LocalDateTime', referenced from method com.esotericsoftware.kryo.serializers.TimeSerializers.addDefaultSerializers
E/dalvikvm( 1847): Could not find class 'java.time.ZoneOffset', referenced from method com.esotericsoftware.kryo.serializers.TimeSerializers.addDefaultSerializers
E/dalvikvm( 1847): Could not find class 'java.time.ZoneId', referenced from method com.esotericsoftware.kryo.serializers.TimeSerializers.addDefaultSerializers
E/dalvikvm( 1847): Could not find class 'java.time.OffsetTime', referenced from method com.esotericsoftware.kryo.serializers.TimeSerializers.addDefaultSerializers
E/dalvikvm( 1847): Could not find class 'java.time.OffsetDateTime', referenced from method com.esotericsoftware.kryo.serializers.TimeSerializers.addDefaultSerializers
E/dalvikvm( 1847): Could not find class 'java.time.ZonedDateTime', referenced from method com.esotericsoftware.kryo.serializers.TimeSerializers.addDefaultSerializers
E/dalvikvm( 1847): Could not find class 'java.time.Year', referenced from method com.esotericsoftware.kryo.serializers.TimeSerializers.addDefaultSerializers
E/dalvikvm( 1847): Could not find class 'java.time.YearMonth', referenced from method com.esotericsoftware.kryo.serializers.TimeSerializers.addDefaultSerializers
E/dalvikvm( 1847): Could not find class 'java.time.MonthDay', referenced from method com.esotericsoftware.kryo.serializers.TimeSerializers.addDefaultSerializers
E/dalvikvm( 1847): Could not find class 'java.time.Period', referenced from method com.esotericsoftware.kryo.serializers.TimeSerializers.addDefaultSerializers
E/Fabric  ( 1847): Unknown error while loading Crashlytics settings. Crashes will be cached until settings can be retrieved.
E/Answers ( 1847): Failed to retrieve settings
E/dalvikvm( 1579): Could not find class 'android.app.usage.UsageStatsManager', referenced from method aaab.a
E/dalvikvm( 1579): Could not find class 'android.app.AutomaticZenRule', referenced from method asqs.onReceive
E/dalvikvm( 1376): Could not find class 'mae', referenced from method mad.a
E/BluetoothInputDevice( 1900): Could not bind to Bluetooth HID Service with Intent { act=android.bluetooth.IBluetoothInputDevice }
E/BluetoothPan( 1900): Could not bind to Bluetooth Pan Service with Intent { act=android.bluetooth.IBluetoothPan }
E/BluetoothMap( 1900): Could not bind to Bluetooth MAP Service with Intent { act=android.bluetooth.IBluetoothMap }
E/BluetoothPbap( 1900): Could not bind to Bluetooth Pbap Service with Intent { act=android.bluetooth.IBluetoothPbap }
E/dalvikvm( 1376): Could not find class 'android.app.ActivityManager$TaskDescription', referenced from method com.google.android.gms.growth.ui.webview.GrowthWebViewChimeraActivity.onCreate
E/ActivityThread( 1920): Failed to find provider info for com.android.launcher2.settings
E/dalvikvm( 1397): Could not find class 'mae', referenced from method mad.a
E/dalvikvm( 1376): Could not find class 'android.service.persistentdata.PersistentDataBlockManager', referenced from method gdl.a
E/dalvikvm( 1376): Could not find class 'android.os.SystemUpdateManager', referenced from method akxn.h
E/dalvikvm( 1376): Could not find class 'android.net.Network', referenced from method akwn.a
E/dalvikvm( 1579): Could not find class 'android.app.usage.UsageStatsManager', referenced from method teq.a
E/dalvikvm( 1579): Could not find class 'android.app.job.JobScheduler', referenced from method tlj.a
E/dalvikvm( 1376): Could not find class 'akzr', referenced from method akyf.b
E/dalvikvm( 1376): Could not find class 'android.telephony.SubscriptionManager', referenced from method com.google.android.gms.checkin.CheckinChimeraService.c
E/dalvikvm( 1579): Could not find class 'android.app.usage.UsageStatsManager', referenced from method tnd.a
E/BaseAppContext( 1376): Tried to stop global GMSCore RequestQueue. This is likely unintended, so ignoring.
E/dalvikvm( 1376): Could not find class 'android.app.usage.UsageStatsManager', referenced from method teq.a
E/dalvikvm( 1579): Could not find class 'android.net.NetworkRequest$Builder', referenced from method com.google.android.gms.gcm.GcmChimeraService.onCreate
E/dalvikvm( 1376): Could not find class 'android.app.ActivityManager$TaskDescription', referenced from method zer.a
E/WakeLock( 1579): GCM_HB_ALARM release without a matched acquire!
E/dalvikvm( 1376): Could not find class 'android.telephony.SubscriptionManager', referenced from method kho.a
E/dalvikvm( 1376): Could not find class 'android.app.NotificationChannel', referenced from method zkk.a
E/dalvikvm( 1376): Could not find class 'android.app.NotificationChannelGroup', referenced from method zkk.a
E/ActivityThread( 1376): Failed to find provider info for sms
E/ActivityThread( 1376): Failed to find provider info for mms
E/DeviceContactImportDelegate( 1376): Device contact import is disabled.
E/DeviceContactImportDelegate( 1376): Data layer device contacts import is disabled.
E/DeviceContactImportDelegate( 1376): Device contact import is disabled.
E/DeviceContactImportDelegate( 1376): Data layer device contacts import is disabled.
E/DeviceContactImportDelegate( 1376): Device contact import is disabled.
E/DeviceContactImportDelegate( 1376): Data layer device contacts import is disabled.
E/DeviceContactImportDelegate( 1376): Device contact import is disabled.
E/DeviceContactImportDelegate( 1376): Data layer device contacts import is disabled.
E/dalvikvm( 1579): Could not find class 'android.app.usage.UsageStatsManager', referenced from method dyj.i
E/IndexManagementDelegate( 1376): Rebuild index is disabled.
E/dalvikvm( 2026): Could not find class 'javax.net.ssl.SNIServerName', referenced from method com.google.android.gms.org.conscrypt.Platform.getSniHostnameFromParams
E/dalvikvm( 2026): Could not find class 'javax.net.ssl.SNIHostName', referenced from method com.google.android.gms.org.conscrypt.Platform.setParametersSniHostname
E/dalvikvm( 2026): Could not find class 'javax.net.ssl.SNIHostName', referenced from method com.google.android.gms.org.conscrypt.Platform.setParametersSniHostname
E/dalvikvm( 2026): Could not find class 'com.google.android.gms.org.conscrypt.Java8ExtendedSSLSession', referenced from method com.google.android.gms.org.conscrypt.Platform.wrapSSLSession
E/dalvikvm( 1376): Could not find class 'android.app.job.JobScheduler', referenced from method yjg.j
E/dalvikvm( 1579): Could not find class 'android.telecom.TelecomManager', referenced from method com.google.android.gms.wearable.service.WearableChimeraService.a
E/dalvikvm( 1579): Could not find class 'android.app.usage.UsageStatsManager', referenced from method com.google.android.gms.wearable.service.WearableChimeraService.onCreate
E/dalvikvm( 2058): Could not find class 'javax.net.ssl.SNIServerName', referenced from method com.google.android.gms.org.conscrypt.Platform.getSniHostnameFromParams
E/dalvikvm( 2058): Could not find class 'javax.net.ssl.SNIHostName', referenced from method com.google.android.gms.org.conscrypt.Platform.setParametersSniHostname
E/dalvikvm( 2058): Could not find class 'javax.net.ssl.SNIHostName', referenced from method com.google.android.gms.org.conscrypt.Platform.setParametersSniHostname
E/dalvikvm( 2058): Could not find class 'com.google.android.gms.org.conscrypt.Java8ExtendedSSLSession', referenced from method com.google.android.gms.org.conscrypt.Platform.wrapSSLSession
E/MDM     ( 1376): [198] ybw.a: Couldn't connect to Google API client: lak{statusCode=API_UNAVAILABLE, resolution=null, message=null}
E/ctxmgr  ( 1579): [FencePendingIntentCache]Expected to find a PendingIntent for pendingIntentKey=2db080de-e90c-4af9-ac98-6146e9726427
E/dalvikvm( 2058): Could not find class 'android.net.Network', referenced from method pjj.a
E/dalvikvm( 1579): Could not find class 'android.hardware.fingerprint.FingerprintManager', referenced from method ajnb.a
E/dalvikvm( 2058): Could not find class 'mae', referenced from method mad.a
E/SeTransactionSyncTask( 1579): Error retrieving account
E/SeTransactionSyncTask( 1579): java.lang.IllegalStateException: No current tap-and-pay account
E/SeTransactionSyncTask( 1579):         at aisk.b(:com.google.android.gms@12874002@12.8.74 (000304-204998136):3)
E/SeTransactionSyncTask( 1579):         at aisk.a(:com.google.android.gms@12874002@12.8.74 (000304-204998136):1)
E/SeTransactionSyncTask( 1579):         at ajmi.a(:com.google.android.gms@12874002@12.8.74 (000304-204998136):28)
E/SeTransactionSyncTask( 1579):         at com.google.android.gms.tapandpay.gcmtask.TapAndPayGcmTaskChimeraService.b(:com.google.android.gms@12874002@12.8.74 (000304-204998136):1)
E/SeTransactionSyncTask( 1579):         at com.google.android.gms.tapandpay.gcmtask.TapAndPayGcmTaskChimeraService.a(:com.google.android.gms@12874002@12.8.74 (000304-204998136):1)
E/SeTransactionSyncTask( 1579):         at ajbw.i(:com.google.android.gms@12874002@12.8.74 (000304-204998136):8)
E/SeTransactionSyncTask( 1579):         at ajbw.a(:com.google.android.gms@12874002@12.8.74 (000304-204998136):2)
E/SeTransactionSyncTask( 1579):         at com.google.android.gms.tapandpay.init.TapAndPayInitIntentOperation.onHandleIntent(:com.google.android.gms@12874002@12.8.74 (000304-204998136):3)
E/SeTransactionSyncTask( 1579):         at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@12874002@12.8.74 (000304-204998136):2)
E/SeTransactionSyncTask( 1579):         at dgb.a(:com.google.android.gms@12874002@12.8.74 (000304-204998136):8)
E/SeTransactionSyncTask( 1579):         at klm.a(:com.google.android.gms@12874002@12.8.74 (000304-204998136):9)
E/SeTransactionSyncTask( 1579):         at dgg.run(:com.google.android.gms@12874002@12.8.74 (000304-204998136):10)
E/SeTransactionSyncTask( 1579):         at dgd.run(:com.google.android.gms@12874002@12.8.74 (000304-204998136):9)
E/SeTransactionSyncTask( 1579):         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/SeTransactionSyncTask( 1579):         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/SeTransactionSyncTask( 1579):         at java.lang.Thread.run(Thread.java:841)
E/Drm     (  149): Failed to open plugin directory /vendor/lib/mediadrm
E/SeTransactionSyncTask( 1579): Error retrieving account
E/SeTransactionSyncTask( 1579): java.lang.IllegalStateException: No current tap-and-pay account
E/SeTransactionSyncTask( 1579):         at aisk.b(:com.google.android.gms@12874002@12.8.74 (000304-204998136):3)
E/SeTransactionSyncTask( 1579):         at aisk.a(:com.google.android.gms@12874002@12.8.74 (000304-204998136):1)
E/SeTransactionSyncTask( 1579):         at ajmi.a(:com.google.android.gms@12874002@12.8.74 (000304-204998136):28)
E/SeTransactionSyncTask( 1579):         at com.google.android.gms.tapandpay.gcmtask.TapAndPayGcmTaskChimeraService.b(:com.google.android.gms@12874002@12.8.74 (000304-204998136):1)
E/SeTransactionSyncTask( 1579):         at com.google.android.gms.tapandpay.gcmtask.TapAndPayGcmTaskChimeraService.a(:com.google.android.gms@12874002@12.8.74 (000304-204998136):1)
E/SeTransactionSyncTask( 1579):         at com.google.android.gms.tapandpay.phenotype.PhenotypeCommitIntentOperation.onHandleIntent(:com.google.android.gms@12874002@12.8.74 (000304-204998136):47)
E/SeTransactionSyncTask( 1579):         at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@12874002@12.8.74 (000304-204998136):2)
E/SeTransactionSyncTask( 1579):         at dgb.a(:com.google.android.gms@12874002@12.8.74 (000304-204998136):8)
E/SeTransactionSyncTask( 1579):         at klm.a(:com.google.android.gms@12874002@12.8.74 (000304-204998136):9)
E/SeTransactionSyncTask( 1579):         at dgg.run(:com.google.android.gms@12874002@12.8.74 (000304-204998136):10)
E/SeTransactionSyncTask( 1579):         at dgd.run(:com.google.android.gms@12874002@12.8.74 (000304-204998136):9)
E/SeTransactionSyncTask( 1579):         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/SeTransactionSyncTask( 1579):         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/SeTransactionSyncTask( 1579):         at java.lang.Thread.run(Thread.java:841)
E/WakeLock( 1579): GCM_HB_ALARM release without a matched acquire!
E/ctxmgr  ( 1579): [BaseServerTask]Failed network request due to no network connectivity:
E/ctxmgr  ( 1579): [SyncServerInterestRecordsOperation]Failed WriteInterestRecord: network status=1
E/CheckinRequestProcessor( 1376): CheckinNowTaskTag : Checkin failed: https://android.clients.google.com/checkin (fragment #0): java.net.UnknownHostException: Unable to resolve host "android.clients.google.com": No address associated with hostname
E/Finsky  ( 1678): [165] com.google.android.finsky.aq.c.a(25): Unable to build selector: /storage/emulated/0/Download/marketenvs.csv: open failed: ENOENT (No such file or directory)
E/Finsky  ( 1678): [1] com.google.android.finsky.wear.ad.a(3): onConnectionFailed: ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null, message=null}
E/WakeLock( 1579): GCM_HB_ALARM release without a matched acquire!
E/dalvikvm( 1376): Could not find class 'android.app.usage.UsageStatsManager', referenced from method vwf.a
E/WakeLock( 1579): GCM_HB_ALARM release without a matched acquire!
E/PpssppActivity( 2233): Got ACTION_VIEW without a valid uri, trying param
E/PpssppActivity( 2233): Shortcut missing parameter!
E/PPSSPP  ( 2233): [SCEKERNEL] 800201bc=sceKernelReferThreadStatus(276, 09fff390): bad size 146669568
F/libc    ( 2233): Fatal signal 11 (SIGSEGV) at 0x0000001e (code=1), thread 2248 (AndroidRender)
E/JavaBinder(  521): !!! FAILED BINDER TRANSACTION !!!
E/InputDispatcher(  521): channel '41b81348 org.ppsspp.ppsspp/org.ppsspp.ppsspp.PpssppActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
E/ActivityThread( 1140): Failed to find provider info for sms
E/ActivityThread( 1140): Failed to find provider info for mms
E/EmojiFactory_jni(  521): Failed to load libemoji.so: dlopen failed: library "libemoji.so" not found
E/ActivityThread( 1140): Failed to find provider info for com.google.android.gm
E/WakeLock( 1579): GCM_HB_ALARM release without a matched acquire!
E/Lights  (  521): write_int failed to open sys/class/leds/battery_led/brightness
E/biyw    ( 1376): *~*~*~ Channel {0} was not shutdown properly!!! ~*~*~*
E/biyw    ( 1376):     Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
E/Auth    ( 1397): [GoogleAccountDataServiceImpl] getToken() -> NETWORK_ERROR. Account: <ELLIDED:-1975279048>, App: com.google.android.gms, Service: oauth2:https://www.googleapis.com/auth/myphonenumbers
E/WhitePageServiceGrpcCli( 1376): Error making Grpc request.
E/ctxmgr  ( 1579): [BaseServerTask]Failed network request due to no network connectivity:
E/ctxmgr  ( 1579): [SyncServerInterestRecordsOperation]Failed WriteInterestRecord: network status=1
E/WakeLock( 1579): GCM_HB_ALARM release without a matched acquire!

**Comment by unknownbrackets** [comment]
This is a good logcat filter:

```
adb logcat -s DEBUG PPSSPPNativeActivity PPSSPP NativeGLView NativeRenderer NativeSurfaceView PowerSaveModeReceiver InputDeviceState
``

It looks like the attached crash is a segfault during render.  I wonder if the button press is causing a resize somehow, or otherwise causing something in the render manager to get invalidated...

-[Unknown]

**Comment by unknownbrackets** [comment]
Has this improved in the latest git build?  We've fixed some crashes on resize.

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
