### ISSUE TITLE
Incompatible libSDL2-2.0.0.dylib version(requires version 9.0.0 but provides version 5.0.0)

### ISSUE THREAD

**Issue by hddhddhdd** [hrydgard/ppsspp#11126]
### What happens?

It is always crash while I run PPSSPP on my macOS. It seems caused by libSDL2-2.0.0.dylib which requires version 9.0.0 but provides version 5.0.0). However, I already uninstall SDL2 and reinstall it by "brew install sdl2". the  version of libSDL2-2.0.0.dylib is still 5.0.0 when I use "otool -L /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib" after reinstall. 

How can I fix it? Thanks!

Process:               PPSSPPSDL [19423]
Path:                  /Volumes/VOLUME/*/PPSSPPSDL.app/Contents/MacOS/PPSSPPSDL
Identifier:            PPSSPPSDL
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           PPSSPPSDL [19423]
User ID:               501

Date/Time:             2018-06-03 17:27:58.492 +0800
OS Version:            Mac OS X 10.13.5 (17F77)
Report Version:        12
Anonymous UUID:        --

Sleep/Wake UUID:       --

Time Awake Since Boot: 26000 seconds
Time Since Wake:       97 seconds

System Integrity Protection: enabled

Notes:                 Translocated Process

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x3] Wrong version

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib
  Referenced from: /Volumes/VOLUME/*/PPSSPPSDL.app/Contents/MacOS/PPSSPPSDL
  Reason: Incompatible library version: PPSSPPSDL requires version 9.0.0 or later, but libSDL2-2.0.0.dylib provides version 5.0.0

Binary Images:
       0x1045e6000 -        0x1053bfff7 + (??? - ???) <6388C643-DAB7-36E4-9001-A6EB180EE1F1> /var/folders/*/PPSSPPSDL.app/Contents/MacOS/PPSSPPSDL
       0x108012000 -        0x10805c9df  dyld (551.3) <AFAB4EFA-7020-34B1-BBEF-0F26C6D3CA36> /usr/lib/dyld

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
mbp 2013 with macOS 10.13.5

**Comment by unknownbrackets** [comment]
I assume you've already tried `brew update` to make sure you have the latest brew?

The most bulletproof suggestion is probably just to try compiling PPSSPP, if the build uses a newer SDL than your system.

-[Unknown]

**Comment by hddhddhdd** [comment]
@unknownbrackets 
Yes! Should run `brew update` and it is fixed
(my brew is too old and have to uninstall and install again, and then it is ok)

Thanks!
