### ISSUE TITLE
Compatibility Feedback menu bug

### ISSUE THREAD

**Issue by AkiraJkr** [hrydgard/ppsspp#11129]
Tested on v1.6.2-14-gad1b75292

The menu as it shows up after clicking it when the game is paused.
![image](https://user-images.githubusercontent.com/27028529/40889046-6ce696ca-6736-11e8-91c2-9cf374d48b9a.png)

And after selecting a few things, as you can see, it doesn't seem like you can submit it yet for some reason.
![image](https://user-images.githubusercontent.com/27028529/40889058-80b060c8-6736-11e8-9d6d-2738b4b7686e.png)

Clicking on "**Overall** Perfect" will fix it, so you can just select whatever option you selected in "Overall" after that's done.

**Comment by unknownbrackets** [comment]
Is there a certain order you click them in that causes this?

Things that I tried:

1. When first opened, it's disabled -> expected.
2. Clicking Perfect -> enabled as expected.
3. Perfect, then any other overall -> enabled as expected.
4. Nothing, then anything -> have to reselect each of Graphics, Speed, and Gameplay (nothing forces to "Bad".)

Is it possible that you just haven't scrolled down to Gameplay?

Maybe in this case (for wider resolutions in general), it'd be better to put Graphics, Speed, and Gameplay horizontally next to each other.  Then they'd all show on the screen together.

-[Unknown]

**Comment by AkiraJkr** [comment]
Not at all. It seems that the only way to trigger the button to be enabled is by clicking Perfect in **Overall**, no matter the order I do things, this seems to be the only way.

From what I tested:

Clicking Perfect, then nothing, then any of the other 3 options - > Disabled. No matter if the other options are selected.

There is also no specific order, as long as you press Perfect, you can select the other options and then submit. But if you select nothing, and anything else other than Perfect, it just disables forever.

**Comment by unknownbrackets** [comment]
Strange, I can't reproduce.

Internally, the logic is that it's disabled in any of the following cases:
 * Reporting setting in config is disabled and "enable reporting" checkbox is unchecked.
 * Overall is not set to *something*.
 * Graphics is not set to *something*.
 * Speed is not set to *something*.
 * Gameplay is not set to *something*.

For the four choices (outside report enabled), it directly uses the values that are used to draw.  This means, if you visibly see all those set to something, then they *must* be set to something.  There's no copy or cached value that could be wrong.

For the reporting setting, if this was disabled you'd see a checkbox prompting you to enable reporting.  That's not in your screenshot, so I assume it's enabled.

The submit button's enable state is not real time - it's updated in these situations:
 * User checks or unchecks the "enable reporting" checkbox.
 * User selects a value for Overall, Graphics, Speed, or Gameplay.

I'm not seeing where it could leave the button disabled... I tried using gamepad only to select the options as well.

Here's a screenshot after following the steps you gave (I've scrolled all the way down so you can see my selections too):
![reporting-great](https://user-images.githubusercontent.com/191233/40891047-2544909e-6734-11e8-9465-c1a63f7e9ac2.png)

-[Unknown]

**Comment by leopard20** [comment]
@unknownbrackets Seems like there's also a minor typo:
"...but too buggy **too** complete" 
It should be "to".

**Comment by unknownbrackets** [comment]
Derp, thanks.  Fixed in #11132.

-[Unknown]

**Comment by unknownbrackets** [comment]
Did anything in #11132 improve this?

-[Unknown]

**Comment by AkiraJkr** [comment]
Yes indeed. It seems like Reporting buttons are triggering the submit button to work like it should from all of them.
Before pressing any buttons.
![image](https://user-images.githubusercontent.com/27028529/41072234-fa2105e0-69d2-11e8-8394-1eab458fdd91.png)
After selecting from each of the four categories, no matter the button or the order.
![image](https://user-images.githubusercontent.com/27028529/41072263-1958bc78-69d3-11e8-81da-904f2852d819.png)

This can be closed now.
