### ISSUE TITLE
POP:Rival Swords GLES Graphic Glitches

### ISSUE THREAD

**Issue by lim2222** [hrydgard/ppsspp#11134]
### What happens?

![screenshot_20180604-112221](https://user-images.githubusercontent.com/35925370/40897833-48534c50-67f8-11e8-8d0c-f07562cabbf4.jpg)
![screenshot_20180604-113933](https://user-images.githubusercontent.com/35925370/40897835-4895a82a-67f8-11e8-937e-6e059547b6ea.jpg)
![screenshot_20180604-122032](https://user-images.githubusercontent.com/35925370/40898145-6b9900b8-67fa-11e8-98de-add45f4d4745.jpg)

Happy to see that yellow screen bug of GLES gone after 1.6.2 update,but it still have some graphic glitches.
It is very easy to reproduce that glitches by playing the chariot race mini game.

### What *should* happen?
Vulkan backend looks normal
![screenshot_20180604-112817](https://user-images.githubusercontent.com/35925370/40898298-65804f00-67fb-11e8-9e00-12389a0813ce.jpg)
![screenshot_20180604-113911](https://user-images.githubusercontent.com/35925370/40898299-66d2275c-67fb-11e8-8646-3e429c760138.jpg)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Android 7.1.1 Snapdragon 835 Adreno 540 Oneplus 5
Sorry for my bad english:(

**Comment by unknownbrackets** [comment]
I wonder if this is flat shadring related or something.. maybe not all drivers use the same provoking vertex for GL?  But, that's probably not it.  Strange.

Maybe it's just more rounding bugs like the yellow screen.

-[Unknown]

**Comment by hrydgard** [comment]
It could be that the driver just isn't using full precision integers in GLES. Turns out that the standard doesn't require it, but in Vulkan, an int should be a 32-bit integer. In that case, we should probably use a GLES2-style path for the depal (access components directly, instead of computing the full integer and shifting it).

**Comment by leopard20** [comment]
@hrydgard 
I was right! I had seen this issue before! It's possibly the same as https://github.com/hrydgard/ppsspp/issues/10089, right? Not because of recent changes.

**Comment by lim2222** [comment]
no,post-processing shaders off

**Comment by hrydgard** [comment]
Hm, don't think that one is related, actually...

**Comment by hrydgard** [comment]
If I'm right the fix for this will be pretty easy, but slightly risky so I won't squeeze it into the 1.6 bugfix series, I'll do it afterwards.

**Comment by leopard20** [comment]
@lim2222 Is "Disable slower effects" on?

**Comment by lim2222** [comment]
No,Disable slower effects is off,if turn on will produce black screen,totally unplayable.

**Comment by marosis** [comment]
Interresting

**Comment by lim2222** [comment]
FIxed by 1.6.3,thanks bro.

**Comment by lim2222** [comment]
Weird,by1.6.3 first time test it fixed,however the second attempt of it all comeback:(

**Comment by joelolopez** [comment]
looks like related to my issue about triangles in brAVE Story

**Comment by unknownbrackets** [comment]
Does this still happen in latest git?  May have been fixed by #10981.

-[Unknown]

**Comment by lim2222** [comment]
Unable to test with latest git because there are no android build after v1.6.3-404-ga004196d4 ,issue remain on  v1.6.3-404
@unknownbrackets

**Comment by lim2222** [comment]
Still no fix on v1.6.3-420-gf87dcefdd.
Actually this was good with ppsspp v1.0.1,both POP rival sword and revelations with no graphic glitch.
The only bad thing was emulating slower compare with the new version.

**Comment by lim2222** [comment]
v1.7.5-288-g9fd8d3b91 fixed the issue,great job guy

**Comment by unknownbrackets** [comment]
This might have been the depal precision fix.  Thanks for reporting.

-[Unknown]
