### ISSUE TITLE
Linux: No recent amd64 builds for Ubuntu 18.04 LTS (and variants) in stable PPA

### ISSUE THREAD

**Issue by FranciscoPombal** [hrydgard/ppsspp#11138]
Currently there are no PPSSPP builds for the most recent LTS version in the stable PPA. When can we expect them to be added, and is there any prerequisite that is currently not satisfied? What can be done to help out?

Also somewhat related, the PPA still provides builds for versions that are EOL and therefore unsafe to use (15.04, 15.10, 16.10 and 17.04, and also 17.10 very soon as well). In my opinion, these builds should be removed so as to not encourage the use of insecure OSs.

### What happens?
The PPA does not have builds for Ubuntu 18.04 LTS (bionic)

### What *should* happen?
The PPA does should have builds for Ubuntu 18.04 LTS (bionic)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Hardware: not applicable
OS: (X)ubuntu 18.04 LTS
PPSSPP version: any

**Comment by LunaMoo** [comment]
Not really my thing, but probably your question should be directed to one of the people listed  [on that ppa](https://launchpad.net/~ppsspp) as they might not be lurking around here often. That site seems to be quite outdated when it comes to ppsspp version to begin with.;3

**Comment by FranciscoPombal** [comment]
@sergiobenrocha2 ping

**Comment by sergiobenrocha2** [comment]
Use the testing PPA for now, I'll see it later

**Comment by sergiobenrocha2** [comment]
No, they aren't. Forget the number in the package, it's still building daily: https://code.launchpad.net/~ppsspp/+recipe/ppsspp-daily

**Comment by FranciscoPombal** [comment]
@sergiobenrocha2 
You are right, I guess I can use that for now.
But the version numbers in the package names being wrong is very misleading. It would be better to not have them in the name at all. Or perhaps there is a way of updating the name of the package automatically in launchpad?
I have never used launchpad, so I don't know.

**Comment by poVoq** [comment]
Daily builds are also failing right now it seems.
Would be nice to have more than 1.5.4 in the repo since there has been so much improvements lately.

Thanks!

**Comment by tiagoplacido** [comment]
Hello i've just noticed that the unstable ppa as reached it max repository size, maybe thats the reason the packages don't build?

**Comment by FranciscoPombal** [comment]
@sergiobenrocha2 
Like @tiagoplacido said, the repo (on launchpad) has reached its max size, and there have been no new builds since early June.

**Comment by FranciscoPombal** [comment]
@hrydgard @sergiobenrocha2
Sorry to bother, any news about this?

**Comment by sergiobenrocha2** [comment]
Wut? The builds are just failing, take a look at recipe page

I'll try to take a look this week, sorry

**Comment by unknownbrackets** [comment]
It looks like some custom patch failed:

```
patching file Core/TextureReplacer.cpp
Hunk #1 FAILED at 16.
1 out of 1 hunk FAILED -- rejects in file Core/TextureReplacer.cpp
```

Seems to be named 03_libpng.patch.

-[Unknown]

**Comment by WattanaGaming** [comment]
Soooooo i came here and doesnt get the answer, is it still being up-to-date in the end?

**Comment by WattanaGaming** [comment]
still waiting

**Comment by sergiobenrocha2** [comment]
Sorry... patch & recipe updated, you can see if it'll build correctly in the recipe page

**Comment by unknownbrackets** [comment]
Sorry - I'm still not sure how to see where the patch is, but looks like it needs to change `Core/Debugger/WebSocket/GPUBufferSubscriber.cpp` also (for arm only?) to use some other path for libpng.

-[Unknown]

**Comment by WattanaGaming** [comment]
Latest updates
ppsspp 5 hours 30 minutes ago 
Failed to build: amd64 arm64 armhf i386
ppsspp 5 hours 50 minutes ago 
Failed to build: arm64 armhf

probably should count that as a failure, still stuck at 1.5.4

**Comment by sergiobenrocha2** [comment]
Patchs updated, you'll see new packages in the unstable & stable PPA soon

Ping me if anything goes wrong

**Comment by WattanaGaming** [comment]
OMFG Im so hyped for this fix. thank you guys so much!!!

**Comment by poVoq** [comment]
Works great here on my x86 GPDWin with Ubuntu18.04.

**Comment by FranciscoPombal** [comment]
@sergiobenrocha2
Thanks, everything seems to be in order. I guess we should wait a few days for people to test a bit, and if nothing else pops up I will close this myself.

**Comment by unknownbrackets** [comment]
The stable one only does stable releases right?  There's no 1.7.0 yet.

-[Unknown]

**Comment by WattanaGaming** [comment]
I mean the build system is literally failing LOL. nvm its probably waiting for a stable update :P

**Comment by FranciscoPombal** [comment]
Let's wait for a new stable release to figure out if there is anything wrong with the PPA this time.

**Comment by sergiobenrocha2** [comment]
@WattanaGaming what Ubuntu version are you using? PPA is building only for 14.04, 16.04 and 18.04, other versions of Ubuntu are not supported anymore (End of Life)

**Comment by sergiobenrocha2** [comment]
Also, if you are using alpha/beta version of 18.10, you'll see packages only in the Testing PPA

It does not make sense to have packages in Stable PPA until Ubuntu official release

**Comment by FranciscoPombal** [comment]
@sergiobenrocha2 
I can confirm that the stable PPA has been working correctly. Today I updated to 1.7.0 successfully.

**Comment by hrydgard** [comment]
So can we close this?

**Comment by FranciscoPombal** [comment]
@hrydgard yes

**Comment by Rad0van** [comment]
PPA does not contain 1.8.0 as of this day. No sigh of attempting to build it. Or am I missing something?
