### ISSUE TITLE
Recents list bug - multiple instances of a game

### ISSUE THREAD

**Issue by leopard20** [hrydgard/ppsspp#11131]
Don't know why I see multiple instances of a game in the Recents list. In this image there's two. At one point there was even three of them!
![screenshot_2018-06-04-01-03-37-014_org ppsspp ppsspp](https://user-images.githubusercontent.com/16115820/40890974-81a1a89a-6793-11e8-99e3-08b26803b49e.png)

My Homebrew list is fine though:
![screenshot_2018-06-04-01-07-32-683_org ppsspp ppsspp](https://user-images.githubusercontent.com/16115820/40890994-be7e8ac6-6793-11e8-8df7-7adaebf53cac.png)

It's become like this ever since I tested PoP Revelations on OpenGL!

**Comment by leopard20** [comment]
For now I'll clear my recents list. Let's see if I can reproduce.

**Comment by leopard20** [comment]
Nope. Tried a series of combinations of changing backends, app-switching and stuff like that bit couldn't reproduce.
Still don't know why it became like this in the first place!

**Comment by unknownbrackets** [comment]
Hmm.  Wonder if it has the \ vs / issue again... if you can figure out how to repro, would be interesting to fix.

-[Unknown]

**Comment by leopard20** [comment]
Sure. Will reopen if I encounter this again.

**Comment by marosis** [comment]
Reopen please issue Is Back

**Comment by hrydgard** [comment]
@marosis  can you please show the [Recent] section of PSP/SYSTEM/ppsspp.ini when this happens?

**Comment by marosis** [comment]
[ppsspp.ini.zip](https://github.com/hrydgard/ppsspp/files/2211407/ppsspp.ini.zip)
You mean this @hrydgard ?

**Comment by hrydgard** [comment]
From your ini:
```FileName2 = /storage/emulated/0/Download/a-nfsmwu.iso```
```FileName3 = /sdcard/Download/a-nfsmwu.iso```

looks to me like you simply have the same ISO in two places. That will show up twice, since we use the filename instead of the game id to deduplicate. So well, not gonna prioritize this :)

**Comment by 1234Sameer** [comment]
@hrydgard 
I think this is not because of same .iso in two places but multiple ways to access the same directory.
In this case
`/storage/emulated/0/`
will show same files as
`/sdcard/`
Also a third way is possible
`/storage/sdcard0/`
On my device(5.0) all three ways open my phone storage.
Thus making 3 instances of the same file
I created the same using the multiple ways.
![screenshot_2018-07-20-06-35-06](https://user-images.githubusercontent.com/39208952/42978484-aa5ff19e-8bea-11e8-8044-7c17d0fed363.png)
But can't say how PPSSPP does this itself.
I guess same thing possible for other versions of android as well.
Also phone manufacturers play some role designing the directories.
@marosis 
What version of android do you have ?

**Comment by marosis** [comment]
1234Sameer 6.0

**Comment by unknownbrackets** [comment]
For me, /sdcard is a symlink to /storage/emulated/0/.  I don't have /storage/sdcard0/, but /storage/self/primary is also a symlink for me.

We could (potential everywhere, or maybe just Android?) take the realpath to keep from having symlink duplicates.

Of course, for some more obscure use cases (mostly I'm thinking of romhacking where say "current" might be a symlink to a series of builds) this might be undesirable, but I'm not sure if that's a compelling use case.  Such a user could just hand edit in a symlink path as long as we performed realpath when adding and deduping.

-[Unknown]

**Comment by marosis** [comment]
![screenshot_20180720-090501](https://user-images.githubusercontent.com/33152267/42988506-15744766-8bfd-11e8-8314-881235761928.png)
![screenshot_20180720-090506](https://user-images.githubusercontent.com/33152267/42988507-159aaf46-8bfd-11e8-9842-3cc3d62edcbd.png)
I found it look at this

**Comment by marosis** [comment]
But when i delete this one, second duplicate Is deleted too

**Comment by hrydgard** [comment]
Oh, right, forgot the symlinks... yeah that's the same problem.
