### ISSUE TITLE
Boxer's Road 2 cannot load save data

### ISSUE THREAD

**Issue by RedSawn** [hrydgard/ppsspp#11149]
I can't find an issue or a thread that describes anything like this, so I'm going to have to go here. 

### What happens?
This is an issue I've been working around for a few months or so. I primarily play the Japan-only Boxer's Road 2 on PSP and PPSSPP, and I've been toying with a feature I've only started to probe, the Boxer Directory, basically a way for retired characters to show up to be fought in future careers. I have plans for it. PPSSPP can create the data file for it, but at prompts to load it it cannot be found. Transferring the Directory data to my PSP, it works. Transferring the Directory data from my working PSP to PPSSPP, it still can't find it. The name of the data file created is ボ ク サ ー 名 鑑 デ ー タ, residing in the folder ULJM05125BRD. It's in the correct place; sitting alongside my other game saves, 35 different boxer saves which work, and 41 replay saves.

![20180607_132443](https://user-images.githubusercontent.com/25901811/41099485-972a88d8-6a56-11e8-98a7-90b42c8e87f0.jpg)

If the picture actually appears upside down like it does in my preview, no I don't know why, but it shows the same data file can be found on an actual PSP but not in PPSSPP. I even preemptively loaded it on PSP for the picture (Boxer Directory data is not autoloaded) to demonstrate there is something on it.

This applies to the two other Japanese save data names I have to test:

- Boxer's Road 2 system data (シ ス テ ム デ ー タ/ULJM05125SYS) - autoloaded without prompt on boot, can be saved, cannot be found via load prompt in options menu
- Hajime no Ippo Portable Victorious Spirits system data (シ ス テ ム デ ー タ/ULJS00125SYS) - autoloaded without prompt on boot, can be saved, cannot be found via load prompt in options menu

I tested a game that uses an English name for it's save data when prompted to load it manually and that works, though that game wasn't Japan region (Street Supremacy European version).

### What *should* happen?

The files with Japanese names should be findable and thus loadable. If this turns out to be an isolated issue, then it should be noted both Japanese games I listed are based off the same engine and could have the same technical oversight.

### What hardware, operating system, and PPSSPP version?

I've tested on Windows 10 64-bit with PPSSPP 1.4.2 and 1.6.3, and a Samsung S7 with PPSSPP 1.6.3. I'll go into PC specs if asked but I don't think this is hardware related.

**Comment by unknownbrackets** [comment]
When you say name - you're talking about the display name right?

The filenames created on a PSP don't actually have Japanese characters in them, right?

I know save/load works great for a large number of Japanese language games.  The problems most people see are related to pressing X/O which isn't what's happening here AFAICT.

PSP games do not search for saves based on display name.

-[Unknown]

**Comment by RedSawn** [comment]
The display name, yes, but then I cannot identify what it could be otherwise as a layman. These are my only Japanese games, and the only kinds of save files that do not use the file selector kind of load/save system menu.

**Comment by RedSawn** [comment]
Wouldn't know where to begin on forcing the names either I'm afraid. I'm an expert at the game, not the PSP backend.

**Comment by hrydgard** [comment]
Yeah, I'm just saying that there's no real reason to suspect that the issue actually has anything to do with the Japanese names...

**Comment by unknownbrackets** [comment]
Can you upload a zip file of the saves for one of these games?

Also, has anything improved in the latest git build?  There have been improvements to savedata handling.

-[Unknown]

**Comment by unknownbrackets** [comment]
You can just download a release here:

https://buildbot.orphis.net/ppsspp/

You should be able to extract it to a new directory, or make a copy of the existing ppsspp directory and then overwrite things in there.

Hmm, those files look right - I don't see anything that shouldn't load.  I don't have this game to actually try loading.  Maybe it's something about how it's processing the save name in this request.  For example, "<>" is used as a wildcard when alone.  Maybe there's other cases, though.

-[Unknown]

**Comment by RedSawn** [comment]
Alright, cool. Well I can report with v1.6.3-332-gb9bed664b there is no change to the original behaviour.

**Comment by nassau-tk** [comment]
I downloaded and installed the save data below.
> ULJM05125BRD.zip

It could loading the save data.
![image](https://user-images.githubusercontent.com/48179091/101982060-c7468700-3cb4-11eb-87f5-464ed598536b.png)

**Comment by hrydgard** [comment]
OK, I'm gonna close this then. Thanks!
