### ISSUE TITLE
Tekken 6 Missing animations & effects when lock to 30/30 FPS

### ISSUE THREAD

**Issue by Jinzombie** [hrydgard/ppsspp#11143]
IDK 😅 if its been already reported but if its I will close this issue immediately kindly watch my video here https://youtu.be/VTiyQVIJo34 you will see that there's a lot missing in the animation & effects Im just curious what is the cause of this.

Phone Specs:
Mali-450
Android 5.1
Octacore CPU

**Comment by leopard20** [comment]
You sure it's not because of the modded version you use? Maybe they removed the effects in the modded version.

**Comment by Jinzombie** [comment]
Nope they can't do that they just change the intro movie,unlock all stage ang chane BGM but they can't remove the animations & effects.

**Comment by leopard20** [comment]
Maybe set your PSP model to PSP2000/3000 and/or change the clock speed to 333 MHz. It helps in some games (such as Gran Turismo). Don't know about Tekken.

**Comment by Jinzombie** [comment]
Set my emulated cpu clockspeed to 111MHz lock the game 30/30 FPS and still tha same missing some animations and effects

**Comment by leopard20** [comment]
I don't know. Maybe asking on the forum will give you something.

**Comment by Jinzombie** [comment]
You didn't experience this if you lock the FPS of Tekken6 to 30/30 ? Just Set Emulated CPU ClockSpeed to 111 or 60 and used this cheat code to skip blackscreen.
_C1 Custom CPU speed freeze (FIXED)
_L 0xE0030004 0x001C6094
_L 0x201C6094 0x00000000
_L 0x201CFC28 0x00000000
_L 0x201CFE74 0x00000000

**Comment by Jinzombie** [comment]
I have 2 cheat for 30/30 FPS
the other one showing completely the animations and effects but its super slow and the other one is fast but miss some animations and effects.

_C1 Force 30 FPS (Slow)
_L 0x20452890 0x00000002
_C1 Force 30 FPS (Fast)
_L 0x20452890 0x00000000

*Note Set Cheats refresh rate to 33 or below

**Comment by LunaMoo** [comment]
Closing as it's not emulation issue, when you're modding the game to skip stuff don't expect for that stuff to still show.

**Comment by Jinzombie** [comment]
I don't think so....
Not only me experience this issue in Tekken 6 original ISO or Modded ISO the game reduce animations and effects when lock to 30/30 FPS and that's an emulations issue I think 😕 
tried and tested and different version of ppsspp.

**Comment by Jinzombie** [comment]
I thinks it's related to #10928

**Comment by leopard20** [comment]
I tested it on my version of Tekken 6 (original) but didn't notice any missing effects.
What effects are missing on your version?

I really doubt they are related.

**Comment by hrydgard** [comment]
If things break when you do things like forcing the clock frequency low, don't blame the emulator.

**Comment by Jinzombie** [comment]
As you can see in my video the falls and Aura/Ki of my opponent doesn't Move and also when bounce/falling in the floor there's no cracked and others effects missing when I hit
my opponent.
@leopard20 tnx for testing 👍

**Comment by Jinzombie** [comment]
@hrygard it's only happen in Tekken 6 I force the cpu clockspeed down to 30fps in GoW Chain Of Olympus but the graphics still okay
