### ISSUE TITLE
Tom Clancy's Ghost Recon Predator sound bug.

### ISSUE THREAD

**Issue by 1234Sameer** [hrydgard/ppsspp#11141]
### What happens?
The sound in this game is buggy and can be noticeable in gun fights.

### What *should* happen?
Should work normal.

**Comment by unknownbrackets** [comment]
Are you running at full speed?  Does this happen even on a powerful desktop, or only on a weak 1ghz phone?

-[Unknown]

**Comment by 1234Sameer** [comment]
@unknownbrackets 
The game runs at full speed and and I guess this is not a speed related problem. The bugs are like this -
Sometimes missing gun shoot sound, sometimes you can hear enemy screaming even after they are long dead, weird sounds of vehicles. It appears to be like an in game bug but an actual PSP runs just fine.

**Comment by marosis** [comment]
Do you have set 222mhz? I know dante's inferno have sound problem in videos when you don't have 222mhz

**Comment by 1234Sameer** [comment]
No, it is not working. I just checked out some YouTube videos. The videos with PPSSPP have this bug but the videos with real PSP or cross playing with PS vita don't have the bug.

**Comment by marosis** [comment]
Of course

**Comment by Levan7** [comment]
still an issue on  v1.8.0-569-g31de5a508 build

**Comment by ResurrectionRedmi9** [comment]
@Levan7 @marosis @1234Sameer Feedback/Outdated?

**Comment by Levan7** [comment]
@ResurrectionRedmi9 still an issue 

v1.11.3-1404-g2229bea92 |

**Comment by Levan7** [comment]
still an issue on v1.13.2-1018-g0e6e1eb93

**Comment by 1234Sameer** [comment]
I played the game recently, It looks like the the sound glitches have been fixed.

**Comment by hrydgard** [comment]
Thanks for testing, closing.
