### ISSUE TITLE
GPD XD (original): Display resolution (HW scaler) causes crashes

### ISSUE THREAD

**Issue by radiocaravan** [hrydgard/ppsspp#11154]
When I select a Display resolution other than the default (2x PSP), the app crashes instantly.

GPD XD (original), LegacyROM, PPSSPP Gold 1.6.3

**Comment by ChurroBoi** [comment]
[gpd_xd_res-crash.txt](https://github.com/hrydgard/ppsspp/files/2089224/gpd_xd_res-crash.txt)
Here, I made a crash log.

**Comment by ChurroBoi** [comment]
ALSO, if you aren't patient enough to wait for a fix you can go to the ppsspp.ini in the SYSTEM folder and set AndroidHwScale = 0 to make full resolution.

**Comment by radiocaravan** [comment]
I made this change in the INI file... it worked great.  AND it also magically fixed the Manual Scaling issue.

**Comment by hrydgard** [comment]
Good find. Yeah we should probably not default that to On, it causes too many issues....

**Comment by hrydgard** [comment]
I'm gonna close this as a duplicate of #11063 because it's almost certainly has the same causes.
