### ISSUE TITLE
Display distorted on Nexus Player Android TV 8.0

### ISSUE THREAD

**Issue by RoylandRW** [hrydgard/ppsspp#11151]
This is all that I can see when opening the app on my Nexus Player Android TV 8.0, tried deleting settings backup, tried uninstalling and reinstalling, tried most things I can do without actually being able to access the apps settings menu, cause it is not viewable or changeable in this state. https://photos.app.goo.gl/ZJtodgT7eS9Y19Jh6

**Comment by hrydgard** [comment]
Probably a GPU driver bug, quite an unfortunate one though :(

**Comment by hrydgard** [comment]
@RoylandRW  can you please test the latest builds? It might be fixed now...

**Comment by hrydgard** [comment]
@RoylandRW  Sorry the play store version won't be enough, you'll need to get the latest from the buildbot and install manually via usb (or one of the other ways to sideload): https://buildbot.orphis.net/ppsspp/

**Comment by RoylandRW** [comment]
This one? v1.6.3-383-g22a536fb0

**Comment by RoylandRW** [comment]
I wish I'd seen your response before I'd updated from the play store. Should I delete the play store version I have before installing this one?

**Comment by hrydgard** [comment]
Sorry for the late reply @RoylandRW , thank you very much for reporting, a bit surprising that it didn't help, maybe it needs even bigger alignment. Probably better to force scaling off, can you try to edit /PSP/SYSTEM/ppsspp.ini on your Nexus (I guess just copy the file to your computer and back) and change AndroidHwScale under [Graphics] to 0?

**Comment by hrydgard** [comment]
@RoylandRW could you please try again with a fresh build, deleting ppsspp.ini first? It should no longer even try to use hardware scaling so hopefully this glitch will be gone (unless you enable it, and we should probably detect TV devices and get rid of it...)

**Comment by hrydgard** [comment]
@RoylandRW haven't got a sec to try it? Would be great to get confirmation before releasing 1.7.0.

**Comment by hrydgard** [comment]
No confirmation, moving to 1.8.0 for now.

**Comment by hrydgard** [comment]
Very likely to be fixed now, closing.
