### ISSUE TITLE
Minor graphical issue in K-On! Houkago Live

### ISSUE THREAD

**Issue by kurayami6** [hrydgard/ppsspp#11156]
### What happens?

At higher resolutions, a thin white line appears on the loading screen.

### What *should* happen?

It doesn't happen at native resolution or on a real PSP.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Windows 7, i5, GTX 970, PPSSPP version 1.6.3-92-ge4aef7209

At native resolution.

![capture2](https://user-images.githubusercontent.com/31968468/41143172-b2e1130e-6b3b-11e8-9d35-72ebfe5ce794.PNG)

At x4 resolution. Notice the thin white line next to the left hole.

![capture](https://user-images.githubusercontent.com/31968468/41143200-cbc83000-6b3b-11e8-8d2c-b43492252eed.PNG)

**Comment by hrydgard** [comment]
Yeah, this is one of those things that happen when you upscale games that are not made for it that use bilinear filtering. This is one of many, and like the others, not really solvable without per-game hacks...
