### ISSUE TITLE
Soul eater battle resonance crash

### ISSUE THREAD

**Issue by joelolopez** [hrydgard/ppsspp#11161]
### What happens?
After selecting character and displaying the versus protraits, the emulator crashes

### What *should* happen?
It should not crash

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

OS android 8.0 , Octa-core, 2360 MHz, ARM Cortex-A53, 64-bit, 16 nm , Mali-T830 MP2 , 4 GB RAM

**Comment by unknownbrackets** [comment]
Does it also crash on a PC, or only on mobile?  Did previous versions crash too, or is the crash new?

-[Unknown]

**Comment by joelolopez** [comment]
Im using the latest build 1.6.3 105 for mobile

**Comment by sum2012** [comment]
@joelolopez Does it crash in opengl mode and Vulkan mode ?

**Comment by joelolopez** [comment]
Yup both backends

**Comment by sum2012** [comment]
I only crash in Vulkan mode in lg v20 phone

**Comment by sum2012** [comment]
@unknownbrackets It is Vulkan mode in lg v20 phone crash log v1.6.3-331-g90edace7c
https://gist.githubusercontent.com/sum2012/4cfe3990baf1d132e1b7c1dac3c2d521/raw/4af56000749d29c067af234a67a2f8b4a4dd9b3f/gistfile1.txt

**Comment by unknownbrackets** [comment]
```
08-12 18:48:01.988 29522 29593 W Adreno-GSL: <gsl_ldd_control:467>: ioctl fd 40 code 0xc040094a (IOCTL_KGSL_GPU_COMMAND) failed: errno 35 Resource deadlock would occur: org.ppsspp.ppsspp
08-12 18:48:01.988 29522 29592 W PPSSPP  : [SCENET] UNTESTED sceNetGetMallocStat(9fff4e0): org.ppsspp.ppsspp
08-12 18:48:01.988 29522 29593 W Adreno-GSL: <log_gpu_snapshot:376>: panel.gpuSnapshotPath is not set.not generating user snapshot: org.ppsspp.ppsspp
08-12 18:48:01.989 29522 29593 E PPSSPP  : [SYSTEM] Critical: vkQueueSubmit failed (main, split=0)! result=VK_ERROR_INITIALIZATION_FAILED: org.ppsspp.ppsspp
08-12 18:48:01.989 29522 29593 E PPSSPP  : vkQueueSubmit failed (main, split=0)! result=VK_ERROR_INITIALIZATION_FAILED: org.ppsspp.ppsspp
08-12 18:48:01.989 29522 29593 F PPSSPP  : VulkanRenderManager.cpp:929 (Submit): [res == VK_SUCCESS] vkQueueSubmit failed (main, split=0)! result=VK_ERROR_INITIALIZATION_FAILED: org.ppsspp.ppsspp
```

Maybe caused by the "Resource deadlock would occur: org.ppsspp.ppsspp"?

-[Unknown]

**Comment by hrydgard** [comment]
That's an internal driver message - so either we're doing something bad in the Vulkan backend, or the driver has a bug.

**Comment by hrydgard** [comment]
Sorry to hear that :( maybe better switch to OpenGL until the drivers get better... or we fix whatever we're doing wrong, if we are doing anything wrong.

**Comment by joelolopez** [comment]
For some reason this issue has been fixed after updating to the latest builds
