### ISSUE TITLE
Midnight Club 3 stuck in menu after v1.6.3-6-gb9388f50e build

### ISSUE THREAD

**Issue by GuilhermeGS2** [hrydgard/ppsspp#11165]
After loading the save game the menu options doesn't appears. This is the screen:

https://ibb.co/bv1TNo

The last working build is v1.6.3-6-gb9388f50e. It's still possible to get in the game loading save states.

**Comment by unknownbrackets** [comment]
It could also be the savedata version thing:
https://github.com/hrydgard/ppsspp/compare/v1.6.3-6-gb9388f50e...v1.6.3-10-gb22c48858

Midnight Club 3: Dub Edition is reported as sending a "1" (possibly a hacked version, though?)  Does this also happen with no savedata - maybe it's just angry about the old savedata?  Which makes me wonder - does PPSSPP savedata load on a PSP from old versions?

It might also be good to check the disc crc to make sure it's not got hacks of any kind to bypass firmware checks, whether it's the savedata or sdk version change.

-[Unknown]

**Comment by GuilhermeGS2** [comment]
@LunaMoo it was already 150 when I checked.

@unknownbrackets I created a new save then everything worked, but when I restarted the game and loaded the new save happened the same thing as in the picture. Using no save (by disabling "memory sitck inserted") the game also works fine. I tried both options: PSP 1000 and 2000/3000. Nothing changed.

**Comment by unknownbrackets** [comment]
Hmm, so this problem seems contrary to #10814 then, which was fixed by #11000.

It probably means either some of the savedata actions ignore the secureVersion parameter, or the disc in question is hacked to make it work on older CFW versions.  It may be necessary to compare with a real PSP...

-[Unknown]

**Comment by unknownbrackets** [comment]
Does the latest git build make this work now?

-[Unknown]

**Comment by oli0371** [comment]
@unknownbrackets i use latest version and midnight club 3 run perfectly on my phone

**Comment by unknownbrackets** [comment]
Great to hear - another vote of confidence for conforming to hardware/firmware tests.

-[Unknown]

**Comment by GuilhermeGS2** [comment]
In latest builds it only shows a message saying it's an old savedata and can cause issues, but my old save is working fine.
