### ISSUE TITLE
Snk arcade classic issue 

### ISSUE THREAD

**Issue by fahadfoyjur** [hrydgard/ppsspp#11175]
### What happens?
Snk arcade classic volume 1  , after launch tha game snk logo appear and freeze  , hang , sorry for my bad english :(

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

my device adreno 505 , snapdragon 430 ,3gb ram  and ppsspp latest newest build

**Comment by fahadfoyjur** [comment]
And same prob here  ( The King of Fighters Portable 94-98 - Chapter of Orochi )

**Comment by unknownbrackets** [comment]
Has this changed in the latest git builds?

Can you try providing a log?  Either from adb or the web debugger:
https://github.com/hrydgard/ppsspp/wiki/How-to-get-an-adb-logcat-from-a-PC

-[Unknown]

**Comment by Emulatorer** [comment]
@fahadfoyjur is Harvest Moon Boy and Girl are lag on your phone because you and my friends have the same specs of android device.
See #12824

I will also test this game in his phone and see if you both have the same issue.

**Comment by Emulatorer** [comment]
This is not crashing anymore in the last ppsspp git
