### ISSUE TITLE
Can't compile the UWP version as a result of the recent D3D11-related commit getting the following error:

### ISSUE THREAD

**Issue by Slippy2k** [hrydgard/ppsspp#11174]
Hello,
When I compile PPSSPP. sln I get the following error message at the end:

ppsspp\uwp\ppsspp_uwpmain.cpp(123): error C2660: "NativeInit": function does not take 6 Arguments
ppsspp\ext\native\base\nativeapp.h(48): note: See Declaration of "NativeInit"
ppsspp\uwp\ppsspp_uwpmain.cpp(325): error C2660: "Draw::T3DCreateD3D11Context": function does not take 6 Arguments
ppsspp\ext\native\thin3d\thin3d_create.h(35): note: See Declaration of "Draw::T3DCreateD3D11Context"

**Comment by stuken** [comment]
This has also broken the libretro windows build.
Changeset 8ee3cd5 appears to be responsible. The D3D11DrawContext constructor takes an extra argument that hasn't been added in both the UWP and libretro specific callers.

**Comment by unknownbrackets** [comment]
I believe this was fixed in #11652.  Thanks go to pent0.

-[Unknown]
