### ISSUE TITLE
Simpsons game ppsspp graphics error

### ISSUE THREAD

**Issue by MegaLord22** [hrydgard/ppsspp#11178]
The screen is totally black please help me I am using ppsspp 1.6.3

![ulus10295_00000](https://user-images.githubusercontent.com/40259191/41401090-bddb09b4-6fe0-11e8-9188-2606a41ecc9c.png)

**Comment by Skittels05** [comment]
deactivate "disable slower effects"

**Comment by MegaLord22** [comment]
I have already deactivated it

**Comment by weihuoya** [comment]
it's a duplicate? see #9830.

**Comment by MegaLord22** [comment]
THX going to switch to opengl

**Comment by hrydgard** [comment]
@MegaLord22  What device are you playing on?

**Comment by MegaLord22** [comment]
PC

**Comment by MegaLord22** [comment]
can you give me a good opengl link can't find one myself

**Comment by hrydgard** [comment]
?   You just go into graphics settings of PPSSPP and change the Backend to OpenGL.

**Comment by MegaLord22** [comment]
Its not working

**Comment by MegaLord22** [comment]
It does not work it displays error message

**Comment by hrydgard** [comment]
Try to install new drivers.

Builds are here: https://buildbot.orphis.net/ppsspp/

**Comment by MegaLord22** [comment]
which build should i download GPU drivers not working sorry old pc

**Comment by unknownbrackets** [comment]
Is this using Direct3D 9?  Does it still show the same issue?

Part of the display is upside down, which can't be right.  That said, if this is an older device, it may lack features that we use on newer devices to simulate absdiff blending - which I think this was using.

-[Unknown]

**Comment by hrydgard** [comment]
The game is working on good hardware and drivers, I don't think we'll ever get around to debugging it on old buggy stuff so I'm closing.
