### ISSUE TITLE
F1 2006 eur ( UCES00238 )  cannot in-game since v1.5.4-189-gc1a23658d

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#11177]
@unknownbrackets 
In the past (at least v1.3-276-gad04f97) ,It need simulate UMD delay to in-game #9193 
But in v1.6.3 cannot in-game.

Fast test 
last good: v1.5.4-187-g6b6487afc
last bad: v1.5.4-189-gc1a23658d
Compare: https://github.com/hrydgard/ppsspp/compare/v1.5.4-187-g6b6487afc...v1.5.4-189-gc1a23658d
That mean #10456
v1.5.4-187-g6b6487afc debug log: https://drive.google.com/file/d/1gRP5GHTvJNZcfslVXZyNmw3lWtBHGd5T/view?usp=sharing
v1.5.4-189-gc1a23658d debug log:
https://drive.google.com/file/d/1whMo0oNZCzas2E3jL3WAMoCBO08jFZEC/view?usp=sharing
v1.6.3-173-g0fd4ea882 debug log:
https://drive.google.com/file/d/1AE_croUJq8VCiObW2x4wcWKQu5NTno-i/view?usp=sharing

The screen is unlimited loading,then show full white screen,

**Comment by hrydgard** [comment]
Thanks. Oh, it's that one... We really need to find a better solution for God of War's timing issues...

**Comment by unknownbrackets** [comment]
Does it work with "force max fps" disabled?  Technically, that's a hack, so if that's required it means we have a timing issue we need to fix that's probably separate.  It was probably just accidentally working around that timing issue, then.

-[Unknown]

**Comment by sum2012** [comment]
It does not work with "force max fps" disabled.
I forget to tell that in the beginning ,the top of screen display "Running slow: try frameskip, sound is choppy when slow"

**Comment by sum2012** [comment]
Very Thanks @hrydgard 
![2](https://user-images.githubusercontent.com/2177532/52383725-888e8700-2ab5-11e9-8d60-fb237452c1bc.jpg)

**Comment by marosis** [comment]
I can confirm
