### ISSUE TITLE
Text messages ingame causes massive slowdown seriously? 

### ISSUE THREAD

**Issue by joelolopez** [hrydgard/ppsspp#11170]
### What happens?
![screenshot_20180610-184018](https://user-images.githubusercontent.com/5791856/41209661-76e1e39e-6d5f-11e8-9efb-76b3703a53bc.jpg)
As you can see  im viewing the character background of the servant in fate extra.. Notice that the articles bit long.. You can see the scrollbars indicating that textarea is loaded with a lots of info.. Also from 100% fps rate my fps rate dropped to 66.9%?! Tested on 1.6.3.105 build /mobile

### What *should* happen?
Simple Long text messges shouldnt have a big impact in the performance of the game

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

OS android 8.0 , Octa-core, 2360 MHz, ARM Cortex-A53, 64-bit, 16 nm , Mali-T830 MP2 , 4 GB RAM

**Comment by hrydgard** [comment]
The game is probably using some very inefficient method to render text, but it might be possible to work around. To make it easier to debug this, can you take a frame dump?  Will require you to run on a PC though. Instructions are here: https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

**Comment by SuperNic333** [comment]
This is interesting.
I just tested it on my device with a Snapdragon 430 (a ARM Cortex-A53 with a Adreno 505) on Vulkan at 2x PSP resolution and it ran just fine without a performance drop. (I tested 3x too and it worked fine there too, although on normal gameplay it was too much for this poor low-end SoC)
![photo_2018-06-11_16-07-55](https://user-images.githubusercontent.com/8961085/41251896-cd81ea1e-6d91-11e8-9882-37981925ead2.jpg)
Maybe it's a slowdown specific to Mali drivers?
Anyway, I'm not OP but here is a frame dump, it's at the same text that OP showed on his screenshot: 
[ULUS10576_0001.zip](https://github.com/hrydgard/ppsspp/files/2091432/ULUS10576_0001.zip)

**Comment by unknownbrackets** [comment]
This does what a ton of lazy games do:

It draws the entire 3D scene, every character, every shadow, every blade of grass outside the wall that you can't even see.  Once it's done, it goes over the entire scene to add bloom.

After that, it draws a blue menu background over everything it just wasted its time doing, and then "Matrix Level E" on top of that.  All of this with 32x32 squares that probably are less efficient to separately draw on modern hardware.

Once that's all finally done, it draws black over all that again, but semi-transparent (you can actually see it  in the screenshot.)  So redrawing the menu was not a waste of time, at least.

After that, it draws every letter of the text (potentially separately - or maybe this is just a GE dump bug), one by one.  Even the part of the text that is off screen is drawn, but with a scissor set (this should in theory be fast...)

I'm getting 44k total verts submitted from that dump, which ain't great, especially on GL.  But I think the GE dump is preventing some prim combining by accident.

-[Unknown]

**Comment by joelolopez** [comment]
Just a follow up, there are some cases that eventhough i opened that bunch of text i got 100% fps, but now i got 60% fps again.. Fps is not consistent..

**Comment by AkiraJkr** [comment]
The same issue occurs on Fate/Extra CCC, on Secret Garden levels 1 and 2 of any character, the game falls into a massive performance drop.

**Comment by joelolopez** [comment]
In my default setting of fate extra i disabled simulate  block transfer to get 100%fps, but fpa still drips even if i dsiabled simulate block transfer

**Comment by unknownbrackets** [comment]
Can you try a frame dump with the latest git build?  It would be good to confirm if performance is the same.

It now supports Android, but the instructions are in the same place:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

If it's high flushing, it may run better in Vulkan if that's an option on your device.

-[Unknown]

**Comment by XiaomiRedmi9** [comment]
No feedback outdated?

**Comment by hrydgard** [comment]
Yeah, there was no response to the last question Unknown made, so he now tagged it as such. That means we're less likely to go back and look more at it.

**Comment by ResurrectionRedmi9** [comment]
This should improve now, maybe?

**Comment by Gamemulatorer** [comment]
This safe to close now the author cannot response to this issue 3 years ago and ppsspp improve a lot now.
