### ISSUE TITLE
Unable to open Vulkan mode on devices that support Vulkan

### ISSUE THREAD

**Issue by shenzhiweilou** [hrydgard/ppsspp#11183]
### What happens?
Vulkan mode does not open properly when using beta PPSSPP

### What *should* happen?
Vulkan should be used normally because the device supports the Vulkan API

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
This problem occurs in any beta version
aida64 shows that my Vulkan API version is 1.0.66.
GPU  adreno 540,   android 8.1

**Comment by unknownbrackets** [comment]
What does "does not open properly" mean?

Does it fail to start when you switch to Vulkan?  Does it not even show a Vulkan option?

I use a Google Pixel with Adreno 530 and Android 8.1.0.  It works on this device.  We need more information about your device, and about the errors you get.

-[Unknown]

**Comment by shenzhiweilou** [comment]
Without this option

What information do I need to provide for my device?

My English is not very good，I will try my best to describe my problem

**Comment by shenzhiweilou** [comment]
Device name：    Xiaomi 6   （sagit）
GPU Version：    OpenGL ES 3.2V@298.0 (GIT@df5eed6,le1c2adf65d)(Date:03/06/18)
Vulkan API:     1.0.66

**Comment by shenzhiweilou** [comment]
https://photos.app.goo.gl/GRGzGU9gqVxDwTes6

**Comment by shenzhiweilou** [comment]
http://vulkan.gpuinfo.org/displayreport.php?id=3422

**Comment by leopard20** [comment]
What ROM are you using? I know that the default MIUI works.

**Comment by shenzhiweilou** [comment]
Lineage OS
I can run the 3D Mark's Vulkan test properly.
And I can also play other games that use the Vulkan API.

**Comment by shenzhiweilou** [comment]
https://photos.app.goo.gl/U54UiNAV9BqHwFoL8
https://photos.app.goo.gl/kXyyXuZA31Ee2Hhy6

**Comment by shenzhiweilou** [comment]
I think this may not be a problem with my equipment because I passed the 3D Mark Vulkan test and got a good score.

https://photos.app.goo.gl/ErVPiYErzwJAsGdGA

**Comment by unknownbrackets** [comment]
Can you try to get an `adb logcat`?  It might include the error.

We try to load Vulkan, but if it fails we hide the option.  So Vulkan must be failing to load in PPSSPP for some reason.

-[Unknown]

**Comment by shenzhiweilou** [comment]
https://drive.google.com/open?id=1q_BPkIHLC5cZa3Vov-IkZ0E8lUOZcwoM

**Comment by unknownbrackets** [comment]
Sorry.  It only logs once when PPSSPP starts, so you will have to "Force Stop" PPSSPP first.

It won't log if "libvulkan.so" doesn't load, but that should not happen.

-[Unknown]

**Comment by shenzhiweilou** [comment]
https://drive.google.com/open?id=17G3TQ-YCrhTNHF_shjuYjuqcMv7CRtlT

**Comment by shenzhiweilou** [comment]
Is the newly uploaded log in line with your request?

**Comment by unknownbrackets** [comment]
Yes, looks like this has errors about Vulkan.

```
D/vndksupport(15791): Loading /vendor/lib64/hw/vulkan.msm8998.so from current namespace instead of sphal namespace.
E/linker  (15791): "/system/vendor/lib64/hw/vulkan.msm8998.so" has invalid shdr offset/size: 2528344/1280
E/HAL     (15791): load: module=/vendor/lib64/hw/vulkan.msm8998.so
E/HAL     (15791): dlopen failed: "/system/vendor/lib64/hw/vulkan.msm8998.so" has invalid shdr offset/size: 2528344/1280
D/vulkan  (15791): searching for layers in '/data/app/org.ppsspp.ppsspp-zTiCfWnZCssNcEHEIxNA3g==/lib/arm64'
D/vulkan  (15791): searching for layers in '/data/app/org.ppsspp.ppsspp-zTiCfWnZCssNcEHEIxNA3g==/base.apk!/lib/arm64-v8a'
I/PPSSPP  (15791): Vulkan test instance created successfully.
E/PPSSPP  (15791): No physical Vulkan devices.
```

The driver failed to load.  Since it works for other apps, it might mean that only the 32-bit driver works.  We're trying to load the 64-bit driver because PPSSPP is 64-bit.

The device specifically has a 64-bit driver though, so it's surprising that it wouldn't work.  There aren't any available device updates, right?

It might mean there's corruption on your flash storage (hopefully not.)  The error message "has invalid shdr offset/size" really should never happen for a system driver file.

-[Unknown]

**Comment by unknownbrackets** [comment]
Did this get fixed by a device update - potentially Android 9?

-[Unknown]
