### ISSUE TITLE
MacOS build lacks debugger

### ISSUE THREAD

**Issue by rezual** [hrydgard/ppsspp#11199]
Would it be possible to have the debugger enabled on the MacOS version of PPSSPP that's available on the downloads page, and not just for Windows?

**Comment by unknownbrackets** [comment]
See #10909 - the CPU debugger is already available in the latest git builds, but it's a separate UI (instructions in the linked PR.)

Also, it's not that it was somehow "disabled" for Mac or only in some sort of "developer builds".  The Windows debugger is written using the Windows API, and doesn't work in SDL, Qt, Cocoa, etc.  However, it works fine in WINE which simulates the Windows API (using the Windows binary.)

That said, the new WebSocket based debugger can also be used for remote debugging (e.g. for PPSSPP running on Android) and runs on all platforms without WINE.

-[Unknown]
