### ISSUE TITLE
Switch between apps issue

### ISSUE THREAD

**Issue by abdellahking** [hrydgard/ppsspp#11191]
### What happens?
When i switch between ppsspp and another apps this what i got the first time:
![screenshot_20180617-233756](https://user-images.githubusercontent.com/36864704/41512863-abcbe454-7289-11e8-99d4-63c89c48d94f.png)
And the i re-switch the second time that's what i got: 
![screenshot_20180617-233810](https://user-images.githubusercontent.com/36864704/41512897-56349184-728a-11e8-9e1a-7281961e50d0.png)
And The third time is fine

### What *should* happen?
Should switch probebly

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Androi 6.0
Opengl
Mali-T720
3GB RAM
OPENGL ES3.0

**Comment by unknownbrackets** [comment]
Are you using the latest git build?

-[Unknown]

**Comment by abdellahking** [comment]
Yes (1.6.3-190)

**Comment by ziso1986** [comment]
Yeah it happens to me too.But only in Vulkan.

**Comment by 1234Sameer** [comment]
I mentioned it earlier in #11016 (comment).
This is probably due to ppsspp getting started with wrong screen orientation like portrait while it should be with landscape.

**Comment by abdellahking** [comment]
Oh yeah and i think its deplicate to #11016
So im gonna close it

**Comment by abdellahking** [comment]
Oh,really because it's sound familiar to this issue i'll reopen it and see

**Comment by 1234Sameer** [comment]
@ziso1986 
Are you sure this bug only happens on Vulkan on your device cause I expected this bug is independent of Backends.

**Comment by ziso1986** [comment]
@1234Sameer
I tested it and happened on opengl also
but not always its a random bug.

**Comment by TehPlayer14** [comment]
I think this is device related

**Comment by 1234Sameer** [comment]
This happens on many devices.

**Comment by 1234Sameer** [comment]
I am not getting this bug anymore.

**Comment by unknownbrackets** [comment]
Maybe it was fixed by #11455.

@abdellahking does this still happen to you in the latest git builds?

-[Unknown]

**Comment by unknownbrackets** [comment]
I think there was a pull request to fix immersive mode issues recently which has been working well.  Since this hasn't received feedback since the above, I'm going to close.

If you're still seeing issues, please feel free to comment and we'll reopen.

-[Unknown]

**Comment by 1234Sameer** [comment]
@unknownbrackets 
I am not getting this bug on v1.8.0-291-gcfa79b686. So probably it has been fixed.

**Comment by unknownbrackets** [comment]
Great, thanks for confirming.

-[Unknown]
