### ISSUE TITLE
Should prevent setting hardware scaling settings that don't work

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#11198]
Got an email report of a case where the screen when black after fiddling with graphics settings. I got the ppsspp.ini, it had the following interesting settings:

    InternalResolution = 2
    AndroidHwScale = 5

The device in question, a Kindle Fire 10 HD, only has 1920x1200 resolution which is less than 5x the PSP resolution, which would be 2400x1360 so the user should not have been able to set that hw scaler resolution. And either way, we should catch it with some sanity checks vs the device resolution...

[ppssppini.txt](https://github.com/hrydgard/ppsspp/files/2119402/ppssppini.txt)

**Comment by unknownbrackets** [comment]
Related to #11154, #11289, #11102.

Perhaps for now we make the setting ini only and see how that goes?

-[Unknown]

**Comment by hrydgard** [comment]
I'm thinking:

  * Round desired_width to closest 4 pixels, to try to work around the thing that looks like a stride issue
  * Default to off (forcibly through changing the setting name), prevent smaller settings than 2x on android devices >= Kitkat
  * If no complaints, just kill the feature entirely

**Comment by unknownbrackets** [comment]
Should we punt the rest of this to 1.8.0?

-[Unknown]

**Comment by hrydgard** [comment]
Yeah. I'm gonna try to do a release this week.

**Comment by hrydgard** [comment]
Our current checks should have caught this, and I have not been able to reproduce the fault on any other device without disabling the checks and increasing to really extreme resolutions (at which point I got black instead of a crash). I'm gonna close it.
