### ISSUE TITLE
Pes 2009 app crash 

### ISSUE THREAD

**Issue by fahadfoyjur** [hrydgard/ppsspp#11200]
### What happens?
After i launch pes2009 the ppsspp crash :(
Unfortunately stoped :( 
Plz any solution ( my eng is bad )

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Open gl , snapdragon 430, latest ppsspp build

**Comment by Jinzombie** [comment]
Maybe this could help 😕
https://gamefaqs.gamespot.com/boards/949453-pro-evolution-soccer-2009/47593610

**Comment by leopard20** [comment]
Can you post an ADB log? If your phone directly displays crash logs that should suffice.

**Comment by unknownbrackets** [comment]
People report this game runs well (although no one has reported for 1.5.4):

https://report.ppsspp.org/games?name=2009

But reports show that there are bad copies of discs that don't work, and certain speed hacks (like disabling slow framebuffer effects) might cause it not to work.

Does it work in 1.5.4?  Are you using 1.6.3?

-[Unknown]

**Comment by fahadfoyjur** [comment]
Yes nice work on 1.5.4 ,  1.6 , 
yes i use 1.6.3 latest last build

**Comment by fahadfoyjur** [comment]
(build v1.6.3 -6-gb9388f50e) It is running pes 200 without problems, now please fix this problem :(

**Comment by unknownbrackets** [comment]
Sounds likely this is related to #11165.

-[Unknown]

**Comment by fahadfoyjur** [comment]
Any solution ?

**Comment by unknownbrackets** [comment]
I've done some testing, I think I've got an idea what might be going on here - the modes don't map exactly as we have currently.  Still doing testing.

-[Unknown]

**Comment by unknownbrackets** [comment]
Does the latest git build make this work now?

-[Unknown]

**Comment by fahadfoyjur** [comment]
Yes latest git build works for me :) 
many many thanks :)  , close it
