### ISSUE TITLE
Gundam Vs Gundam next plus stuck on loading screen.

### ISSUE THREAD

**Issue by CYH1996** [hrydgard/ppsspp#11201]
I just can't get rid of it even using latest build.
I'm using Huawei Y7 Prime: snapdragon 435octacore 1.4ghz,3GB RAM, adreno 505

**Comment by Jinzombie** [comment]
The loading screen take too long in my phone & tablet like 20-25 seconds but didn't stuck Im also using the latest build.

**Comment by Jinzombie** [comment]
Phone Specs:
Mali-450
android 5.1
Octacore
1.4GHz CPU
here's my video gameplay in YouTube
https://youtu.be/ZVOAI_fhQeg

**Comment by weihuoya** [comment]
GVGNP loading is a little long. 
I use `.cso` format, and more longer.

**Comment by CYH1996** [comment]
Where did you guys download the game

**Comment by Jinzombie** [comment]
Here's my loading screen I didn't include it from my  YouTube video because its take too long to load 😕
[Screen_Recorder_mobizen_20180622_180301.mp4.zip](https://github.com/hrydgard/ppsspp/files/2127206/Screen_Recorder_mobizen_20180622_180301.mp4.zip)
