### ISSUE TITLE
New Vulkan validation error related to the depth fixes

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#11214]
With the latest SDK, we get the below message when running in debug. This could well be a bug in the old version of glslang we're using to compile our shaders... and might explain the driver issue. We should check the SPIR-V output...

ERROR: [Validation]  Code 5 : Object: VK_NULL_HANDLE (Type = 0) | SPIR-V module not valid: Vulkan spec requires DepthReplacing execution mode to be declared when using BuiltIn FragDepth. ID <0> (OpStore) is referencing ID <8> (OpVariable) which is decorated with BuiltIn FragDepth in function <4>.

**Comment by hrydgard** [comment]
Seems it was added here:

https://github.com/KhronosGroup/glslang/commit/c034c5a8a2004b01a5cbe254eb4b72e1412c1bb6

Alright, time to bite the bullet and upgrade glslang. I'll do it soon.

**Comment by unknownbrackets** [comment]
Oh, bah.  I guess I'll need to double check that the workaround still works afterward too.

-[Unknown]

**Comment by hrydgard** [comment]
Oh, right. Hm. Well, maybe if the DepthReplacing mode was specified correctly the driver would have taken a different path? Anyway, we can experiment after upgrading glslang.
