### ISSUE TITLE
[Android]  Some FMVs can't be unthrottled after load state

### ISSUE THREAD

**Issue by Leopard20** [hrydgard/ppsspp#11217]
Making a savestate during certain FMV's and then loading the state has a weird bug where unthrottling doesn't work anymore.

Example of affected games:
Project Diva Series - Intro FMV's
Pursuit Force 

Example of unaffected games:
The 3rd Birthday

**Comment by 1234Sameer** [comment]
@leopard20 
Same thing for SOCOM bravo 1, but the sound crackles a bit when unthrottling while the speed of the FMV doesn't changes. And also the unthrottling doesn't work only for that FMV in the middle of which save state is created. The game and other FMVs afterwards can be unthrottled.

**Comment by leopard20** [comment]
> And also the unthrottling doesn't work only for that FMV in the middle of which save state is created. The game and other FMVs afterwards can be unthrottled.
I forgot to mention this. Thanks.

**Comment by leopard20** [comment]
@unknownbrackets If this can't be fixed/improved, feel free to close it.

**Comment by unknownbrackets** [comment]
Are there any more affected games?  I'm fishing for one that I have.

-[Unknown]

**Comment by Gamemulatorer** [comment]
> Making a savestate during certain FMV's and then loading the state has a weird bug where unthrottling doesn't work anymore.
> 
> Example of affected games:
> Project Diva Series - Intro FMV's
> Pursuit Force

I cannot reproduce this on Pursuit Force

**Comment by Gamemulatorer** [comment]
> @Gamemulatorer how about Project DIVA?

I don't have that game :/

**Comment by Leopard20** [comment]
Yep, it's been fixed since the new throttling mode was introduced for Android devices. Please close this.

**Comment by unknownbrackets** [comment]
Fixed by #13865.

-[Unknown]
