### ISSUE TITLE
[KHBBS]Command Bar always filled, jumping high 'solves' it

### ISSUE THREAD

**Issue by AkiraJkr** [hrydgard/ppsspp#11223]
There was no useful info on the log, it didn't change while reproducing this.

While in the ground:

![image](https://user-images.githubusercontent.com/27028529/41943752-13ffa52c-797b-11e8-8a99-0452af8a579f.png)

While jumping high enough, it goes back to normal:

![image](https://user-images.githubusercontent.com/27028529/41943771-27dd233a-797b-11e8-9bb0-fe5fc95fc052.png)

And just for a reference, this happens in several areas, no matter the character, and again for reference, D3D9 renderer, though I have haven't got this issue before.

I tested on 1.5.4 release, and here is the result:

![image](https://user-images.githubusercontent.com/27028529/41944019-45598376-797c-11e8-9a92-8f2d92b596ab.png)

Here is on 1.5.4-387:

![image](https://user-images.githubusercontent.com/27028529/41944254-631d8e42-797d-11e8-97f8-68fffda1533a.png)

Here it is on 1.5.4-484:

![image](https://user-images.githubusercontent.com/27028529/41944107-a13e78ae-797c-11e8-9903-4034d7d8be10.png)

**Comment by vsub** [comment]
Just as extra info,the bars that fills up once you use the skill just stay at light blue until the skill is ready to be used again
And also,using non buffered rendering also fixes that problem

So DX9+Buffered rendering causes this problem(it's not gpu drivers thing because it happens on nvidia and intel gpu)
Here is a dump
[ULJM05775.zip](https://github.com/hrydgard/ppsspp/files/2164096/ULJM05775.zip)

**Comment by unknownbrackets** [comment]
Could be some dual source blending thing - only Direct3D 9 right?  Software rendering and every other backend is fine?

-[Unknown]

**Comment by vsub** [comment]
Yes,DX11,OGL,Vulkan,SW mode,all are fine exept DX9

**Comment by AkiraJkr** [comment]
Yeah, it seems that the gl-render-manager update has broken things in several games for the Direct3D 9 backend that were working perfectly.

**Comment by unknownbrackets** [comment]
This is caused by the scissor change:
https://github.com/hrydgard/ppsspp/commit/9340260802a1841d6406883220b3480dd36ef8dd#diff-f54cf59c770973ea3b832f805812410bL579

-[Unknown]

**Comment by vsub** [comment]
Works fine on 1.7 with DX9

**Comment by AkiraJkr** [comment]
Alright, I went ahead and I can now confirm it is definitely fixed. I wonder which update fixed if it wasn't #11510 ...

![image](https://user-images.githubusercontent.com/27028529/47667026-c0676380-db83-11e8-80a4-f8f9ac07e506.png)

**Comment by unknownbrackets** [comment]
Would definitely be curious to know what change fixed this.  Could be some dirty flag tracking issue, I suppose.

-[Unknown]

**Comment by hrydgard** [comment]
Reopened? Started happening again? If so, please try to narrow down which commit did it.

**Comment by DeviSuper100** [comment]
So this issue has returned recently and the last version that it was fixed is v1.10.3-1150-g614540aa6,alot of versions are not downloadable after that one but when you download v1.10.3-1160-gee4662960 the issue returns,also i should mention that this issue happens only when you use directx9 with buffered rendering.

**Comment by hrydgard** [comment]
Interesting, so it's #13636 .

**Comment by unknownbrackets** [comment]
It would not at all surprise me if this was relying on the 565 clearing, it might even be alpha/stencil related.

-[Unknown]

**Comment by hrydgard** [comment]
Yes, that seems very plausible.
