### ISSUE TITLE
Textures Black

### ISSUE THREAD

**Issue by Endarko** [hrydgard/ppsspp#11225]
ppsspp build new: textures original black,  textures not replace.

screenshoot: https://ibb.co/eyYn28

**Comment by unknownbrackets** [comment]
If you're using texture replacements, you may have just run out of video memory.  This happens when the replacements are large.  It takes a lot of video memory.

If this started in some PPSSPP version, and didn't happen in some past PPSSPP version - which versions are those?

-[Unknown]

**Comment by Endarko** [comment]
it has not changed my textures, it is still the original textures of the game.

PPSSPP v1.6.3-271-g5abf324da

**Comment by unknownbrackets** [comment]
v1.6.3-271-g5abf324da doesn't look likely to have caused this problem - it should only affect Linux.

Are you saying that v1.6.3-267-gfb9524b63 worked fine?  If not, what's the first broken version?

-[Unknown]

**Comment by ppmeis** [comment]
I tested all PES games, I can't get this issue in any of them.

**Comment by unknownbrackets** [comment]
Maybe this is a disc corruption issue, like #11423.

-[Unknown]

**Comment by unknownbrackets** [comment]
Any feedback on these questions?

-[Unknown]

**Comment by AkiraJkr** [comment]
From the looks of it, it just sounds like a lack of video memory issue. If that is a modified game, they probably added textures with way too much quality, which can make the issue happen too...but it's hard to know, with no feedback here.

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]

**Comment by MeikelLP** [comment]
I can reproduce this issue with the game `Yu-Gi-Oh! GX Tag Force 3` Europe Edition (German).

![image](https://user-images.githubusercontent.com/11669846/161440784-e5f99c7e-4895-4a2a-990d-1bd9a847a09b.png)

Using v1.12.3


<details>
    <summary>ppsspp.ini</summary>
    <pre>[General]
FirstRun = False
RunCount = 3
Enable Logging = True
AutoRun = True
Browse = False
IgnoreBadMemAccess = True
CurrentDirectory = 
ShowDebuggerOnLoad = False
CheckForNewVersion = True
Language = de_DE
ForceLagSync2 = False
DiscordPresence = True
UISound = False
AutoLoadSaveState = 0
EnableCheats = False
CwCheatRefreshRate = 77
CwCheatScrollPosition = 0.000000
GameListScrollPosition = 0.000000
ScreenshotsAsPNG = False
UseFFV1 = False
DumpFrames = False
DumpVideoOutput = False
DumpAudio = False
SaveLoadResetsAVdumping = False
StateSlot = 0
EnableStateUndo = True
StateLoadUndoGame = NA
StateUndoLastSaveGame = NA
StateUndoLastSaveSlot = -5
RewindFlipFrequency = 0
ShowOnScreenMessage = True
ShowRegionOnGameIcon = False
ShowIDOnGameIcon = False
GameGridScale = 1.000000
GridView1 = True
GridView2 = True
GridView3 = False
RightAnalogUp = 0
RightAnalogDown = 0
RightAnalogLeft = 0
RightAnalogRight = 0
RightAnalogPress = 0
RightAnalogCustom = False
RightAnalogDisableDiagonal = False
SwipeUp = 0
SwipeDown = 0
SwipeLeft = 0
SwipeRight = 0
SwipeSensitivity = 1.000000
SwipeSmoothing = 0.300000
DoubleTapGesture = 0
GestureControlEnabled = False
ReportingHost = default
AutoSaveSymbolMap = False
CacheFullIsoInRam = False
RemoteISOPort = 0
LastRemoteISOServer = 
LastRemoteISOPort = 0
RemoteISOManualConfig = False
RemoteShareOnStartup = False
RemoteISOSubdir = /
RemoteDebuggerOnStartup = False
InternalScreenRotation = 1
BackgroundAnimation = 1
TopMost = False
WindowX = 792
WindowY = 418
WindowWidth = 1434
WindowHeight = 819
PauseOnLostFocus = False
PauseWhenMinimized = False
DumpDecryptedEboots = False
MemStickInserted = True
EnablePlugins = True
[CPU]
CPUCore = 1
SeparateSASThread = True
SeparateIOThread = True
IOTimingMethod = 0
FastMemoryAccess = True
FunctionReplacements = True
HideSlowWarnings = False
HideStateWarnings = False
PreloadFunctions = False
JitDisableFlags = 0x00000000
CPUSpeed = 0
[Graphics]
EnableCardboardVR = False
CardboardScreenSize = 50
CardboardXShift = 0
CardboardYShift = 0
ShowFPSCounter = 0
GraphicsBackend = 1 (DIRECT3D9)
FailedGraphicsBackends = 
DisabledGraphicsBackends = 
VulkanDevice = 
D3D11Device = 
CameraDevice = 
RenderingMode = 0
SoftwareRenderer = False
HardwareTransform = True
SoftwareSkinning = True
TextureFiltering = 1
BufferFiltering = 1
InternalResolution = 0
AndroidHwScale = 1
HighQualityDepth = 1
FrameSkip = 0
FrameSkipType = 0
AutoFrameSkip = False
FrameRate = 0
FrameRate2 = -1
UnthrottlingMode = CONTINUOUS
AnisotropyLevel = 4
VertexDecCache = False
TextureBackoffCache = False
TextureSecondaryCache = False
FullScreen = False
FullScreenMulti = False
SmallDisplayZoomType = 2
SmallDisplayOffsetX = 0.500000
SmallDisplayOffsetY = 0.500000
SmallDisplayZoomLevel = 1.000000
ImmersiveMode = True
SustainedPerformanceMode = False
IgnoreScreenInsets = True
ReplaceTextures = True
SaveNewTextures = False
IgnoreTextureFilenames = False
TexScalingLevel = 1
TexScalingType = 0
TexDeposterize = False
TexHardwareScaling = False
VSyncInterval = False
BloomHack = 0
SplineBezierQuality = 2
HardwareTessellation = False
TextureShader = Off
ShaderChainRequires60FPS = False
MemBlockTransferGPU = True
DisableSlowFramebufEffects = False
FragmentTestCache = True
LogFrameDrops = False
InflightFrames = 2
RenderDuplicateFrames = False
[Sound]
Enable = True
AudioBackend = 0
ExtraAudioBuffering = False
GlobalVolume = 10
ReverbVolume = 10
AltSpeedVolume = -1
AudioDevice = 
AutoAudioDevice = True
[Control]
HapticFeedback = False
ShowTouchCross = True
ShowTouchCircle = True
ShowTouchSquare = True
ShowTouchTriangle = True
Custom0Mapping = 0x0000000000000000
Custom0Image = 0
Custom0Shape = 0
Custom0Toggle = False
Custom1Mapping = 0x0000000000000000
Custom1Image = 1
Custom1Shape = 0
Custom1Toggle = False
Custom2Mapping = 0x0000000000000000
Custom2Image = 2
Custom2Shape = 0
Custom2Toggle = False
Custom3Mapping = 0x0000000000000000
Custom3Image = 3
Custom3Shape = 0
Custom3Toggle = False
Custom4Mapping = 0x0000000000000000
Custom4Image = 4
Custom4Shape = 0
Custom4Toggle = False
Custom5Mapping = 0x0000000000000000
Custom5Image = 0
Custom5Shape = 1
Custom5Toggle = False
Custom6Mapping = 0x0000000000000000
Custom6Image = 1
Custom6Shape = 1
Custom6Toggle = False
Custom7Mapping = 0x0000000000000000
Custom7Image = 2
Custom7Shape = 1
Custom7Toggle = False
Custom8Mapping = 0x0000000000000000
Custom8Image = 3
Custom8Shape = 1
Custom8Toggle = False
Custom9Mapping = 0x0000000000000000
Custom9Image = 4
Custom9Shape = 1
Custom9Toggle = False
ShowTouchPause = True
IgnoreWindowsKey = False
ShowTouchControls = False
DisableDpadDiagonals = False
GamepadOnlyFocused = False
TouchButtonStyle = 1
TouchButtonOpacity = 65
TouchButtonHideSeconds = 20
AutoCenterTouchAnalog = False
AnalogAutoRotSpeed = 8.000000
TouchSnapToGrid = False
TouchSnapGridSize = 64
ActionButtonSpacing2 = 1.000000
ActionButtonCenterX = 0.915374
ActionButtonCenterY = 0.842105
ActionButtonScale = 1.150000
DPadX = 0.100846
DPadY = 0.621053
DPadScale = 1.150000
ShowTouchDpad = True
DPadSpacing = 1.000000
StartKeyX = 0.581100
StartKeyY = 0.909211
StartKeyScale = 1.150000
ShowTouchStart = True
SelectKeyX = 0.500000
SelectKeyY = 0.909211
SelectKeyScale = 1.150000
ShowTouchSelect = True
UnthrottleKeyX = 0.418900
UnthrottleKeyY = 0.909211
UnthrottleKeyScale = 1.150000
ShowTouchUnthrottle = True
LKeyX = 0.048660
LKeyY = 0.425000
LKeyScale = 1.150000
ShowTouchLTrigger = True
RKeyX = 0.951340
RKeyY = 0.425000
RKeyScale = 1.150000
ShowTouchRTrigger = True
AnalogStickX = 0.100846
AnalogStickY = 0.878947
AnalogStickScale = 1.150000
ShowAnalogStick = True
RightAnalogStickX = 0.915374
RightAnalogStickY = 0.878947
RightAnalogStickScale = 1.150000
ShowRightAnalogStick = False
fcombo0X = 0.597320
fcombo0Y = 0.500000
comboKeyScale0 = 1.150000
ShowComboKey0 = False
fcombo1X = 0.678420
fcombo1Y = 0.500000
comboKeyScale1 = 1.150000
ShowComboKey1 = False
fcombo2X = 0.759520
fcombo2Y = 0.500000
comboKeyScale2 = 1.150000
ShowComboKey2 = False
fcombo3X = 0.597320
fcombo3Y = 0.332895
comboKeyScale3 = 1.150000
ShowComboKey3 = False
fcombo4X = 0.678420
fcombo4Y = 0.332895
comboKeyScale4 = 1.150000
ShowComboKey4 = False
fcombo5X = 0.402680
fcombo5Y = 0.500000
comboKeyScale5 = 1.150000
ShowComboKey5 = False
fcombo6X = 0.321580
fcombo6Y = 0.500000
comboKeyScale6 = 1.150000
ShowComboKey6 = False
fcombo7X = 0.240480
fcombo7Y = 0.500000
comboKeyScale7 = 1.150000
ShowComboKey7 = False
fcombo8X = 0.402680
fcombo8Y = 0.332895
comboKeyScale8 = 1.150000
ShowComboKey8 = False
fcombo9X = 0.321580
fcombo9Y = 0.332895
comboKeyScale9 = 1.150000
ShowComboKey9 = False
AnalogDeadzone = 0.150000
AnalogInverseDeadzone = 0.000000
AnalogSensitivity = 1.100000
AnalogIsCircular = False
AnalogLimiterDeadzone = 0.600000
LeftStickHeadScale = 1.000000
RightStickHeadScale = 1.000000
HideStickBackground = False
UseMouse = False
MapMouse = False
ConfineMap = False
MouseSensitivity = 0.100000
MouseSmoothing = 0.900000
SystemControls = True
[Network]
EnableWlan = False
EnableAdhocServer = False
proAdhocServer = socom.cc
PortOffset = 10000
MinTimeout = 0
ForcedFirstConnect = False
EnableUPnP = False
UPnPUseOriginalPort = False
EnableNetworkChat = False
ChatButtonPosition = 0
ChatScreenPosition = 0
EnableQuickChat = True
QuickChat1 = Quick Chat 1
QuickChat2 = Quick Chat 2
QuickChat3 = Quick Chat 3
QuickChat4 = Quick Chat 4
QuickChat5 = Quick Chat 5
[SystemParam]
PSPModel = 1
PSPFirmwareVersion = 660
NickName = PPSSPP
MacAddress = dc:7a:c7:f6:d2:f6
Language = 4
ParamTimeFormat = 0
ParamDateFormat = 0
TimeZone = 0
DayLightSavings = False
ButtonPreference = 1
LockParentalLevel = 0
WlanAdhocChannel = 0
BypassOSKWithKeyboard = False
WlanPowerSave = False
EncryptSave = True
SavedataUpgradeVersion = True
MemStickSize = 16
[Debugger]
DisasmWindowX = 800
DisasmWindowY = 469
DisasmWindowW = 781
DisasmWindowH = 713
GEWindowX = 800
GEWindowY = 469
GEWindowW = 776
GEWindowH = 699
ConsoleWindowX = -1
ConsoleWindowY = -1
FontWidth = 8
FontHeight = 12
DisplayStatusBar = True
ShowBottomTabTitles = True
ShowDeveloperMenu = False
SkipDeadbeefFilling = False
FuncHashMap = False
MemInfoDetailed = False
DrawFrameGraph = False
[Upgrade]
UpgradeMessage = 
UpgradeVersion = 
DismissedVersion = 
[Theme]
ItemStyleFg = 0xffffffff
ItemStyleBg = 0x55000000
ItemFocusedStyleFg = 0xffffffff
ItemFocusedStyleBg = 0xffedc24c
ItemDownStyleFg = 0xffffffff
ItemDownStyleBg = 0xffbd9939
ItemDisabledStyleFg = 0x80eeeeee
ItemDisabledStyleBg = 0x55e0d4af
ItemHighlightedStyleFg = 0xffffffff
ItemHighlightedStyleBg = 0x55bdbb39
ButtonStyleFg = 0xffffffff
ButtonStyleBg = 0x55000000
ButtonFocusedStyleFg = 0xffffffff
ButtonFocusedStyleBg = 0xffedc24c
ButtonDownStyleFg = 0xffffffff
ButtonDownStyleBg = 0xffbd9939
ButtonDisabledStyleFg = 0x80eeeeee
ButtonDisabledStyleBg = 0x55e0d4af
ButtonHighlightedStyleFg = 0xffffffff
ButtonHighlightedStyleBg = 0x55bdbb39
HeaderStyleFg = 0xffffffff
InfoStyleFg = 0xffffffff
InfoStyleBg = 0x00000000
PopupTitleStyleFg = 0xffe3be59
PopupStyleFg = 0xffffffff
PopupStyleBg = 0xff303030
[Recent]
MaxRecent = 60
FileName0 = E:/Games/Emulatoren/Yu-Gi-Oh! GX Tag Force 3 (Europe).iso
[Log]
SYSTEMEnabled = True
SYSTEMLevel = 2
BOOTEnabled = True
BOOTLevel = 2
COMMONEnabled = True
COMMONLevel = 2
CPUEnabled = True
CPULevel = 2
FILESYSEnabled = True
FILESYSLevel = 2
G3DEnabled = True
G3DLevel = 2
HLEEnabled = True
HLELevel = 2
JITEnabled = True
JITLevel = 2
LOADEREnabled = True
LOADERLevel = 2
MEEnabled = True
MELevel = 2
MEMMAPEnabled = True
MEMMAPLevel = 2
SASMIXEnabled = True
SASMIXLevel = 2
SAVESTATEEnabled = True
SAVESTATELevel = 2
FRAMEBUFEnabled = True
FRAMEBUFLevel = 2
AUDIOEnabled = True
AUDIOLevel = 2
IOEnabled = True
IOLevel = 2
SCEAUDIOEnabled = True
SCEAUDIOLevel = 2
SCECTRLEnabled = True
SCECTRLLevel = 2
SCEDISPEnabled = True
SCEDISPLevel = 2
SCEFONTEnabled = True
SCEFONTLevel = 2
SCEGEEnabled = True
SCEGELevel = 2
SCEINTCEnabled = True
SCEINTCLevel = 2
SCEIOEnabled = True
SCEIOLevel = 2
SCEKERNELEnabled = True
SCEKERNELLevel = 2
SCEMODULEEnabled = True
SCEMODULELevel = 2
SCENETEnabled = True
SCENETLevel = 2
SCERTCEnabled = True
SCERTCLevel = 2
SCESASEnabled = True
SCESASLevel = 2
SCEUTILEnabled = True
SCEUTILLevel = 2
SCEMISCEnabled = True
SCEMISCLevel = 2
[PostShaderSetting]
BloomSettingValue1 = 0.600000
BloomSettingValue2 = 0.500000
CartoonSettingValue1 = 0.500000
ColorCorrectionSettingValue1 = 1.000000
ColorCorrectionSettingValue2 = 1.000000
ColorCorrectionSettingValue3 = 1.000000
ColorCorrectionSettingValue4 = 1.000000
ScanlinesSettingValue1 = 1.000000
ScanlinesSettingValue2 = 0.500000
SharpenSettingValue1 = 1.500000
[PostShaderList]
PostShader1 = FXAA

</pre>
</details>

**Comment by hrydgard** [comment]
That would probably be because you have Rendering Mode set to non-buffered - does it work with it set to Buffered?

**Comment by MeikelLP** [comment]
That fixes it thanks :)
