### ISSUE TITLE
Analog axis keeps tiny values even when there's no input(mouse/gamepad analog)

### ISSUE THREAD

**Issue by LunaMoo** [hrydgard/ppsspp#11226]
Following the discussion in the [forum](https://forums.ppsspp.org/showthread.php?tid=24439) about mouse control not working as easily as third party one(glovePIE) only when mapping axis to PSP buttons I made https://github.com/hrydgard/ppsspp/compare/master...LunaMoo:AxisToButtonThreshold however I noticed a separate problem - if too small threshold is allowed, PPSSPP get's input even if there's none.

 It's like something doesn't clear input properly and a tiny value not always, but very commonly "sticks" to emulated analog axis:], I noticed it as well in the past while making right analog patches but I thought back then that my gamepad just is old and missbehaves so I added high deadzone by default to all my patches, but I guess it could just be some issue in PPSSPP itself.

 Steps to reproduce problem, either use right analog patch and reduce it;s deadzone to very small value or any game with the branch linked above,, threshold set to low value (ie 0.5) and mouse axis mapped to anything which is easily observable like camera movement. Possibly could also be the case with standard gamepad when setting deadzone to very small value, but I moved and not sure where my gamepads are so I currently can't test that;p. 

 In case it's platform specific I'm using windows 10 x64.

**Comment by AkiraJkr** [comment]
I noticed that too, everytime I began a game, it was normal, however after moving a bit to, say, down, it began to walk on it's own to the right.

Windows 7 btw.
