### ISSUE TITLE
Midnight Club L.A remix fps problem

### ISSUE THREAD

**Issue by Jinzombie** [hrydgard/ppsspp#11224]
The game running a good speed but theirs a problem in the fps it didn't lock to 60 or 30 even when I use a fps patch codes.

Mali-450
Android 5.1
Octacore CPU
PPSSPP 1.6.3-220 buildbot

**Comment by Jinzombie** [comment]
As you can see in this picture
![screenshot_2018-06-27-23-19-53](https://user-images.githubusercontent.com/37603562/41984052-365ae808-7a1f-11e8-8b88-b7318d2b6580.png)

**Comment by Jinzombie** [comment]
The FPS should be 13/60 or 13/30?

**Comment by LunaMoo** [comment]
Did you messed with emulated PSP cpu clock setting? If you did,  the fps you see would be normal and nothing you can do about it / not a bug. In such case to fix the game you should restore defaults then restart the game and avoid using savestates made earlier.

**Comment by Jinzombie** [comment]
it's ok now 👍
But its lag on my phone :(
