### ISSUE TITLE
Compile Uwp for xbox one

### ISSUE THREAD

**Issue by strikersix23** [hrydgard/ppsspp#11237]
### What happens?
compilation fails

### What *should* happen?
It should conpile

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issue
Im using VS2017 with all deps installed its not working with the older compilers what should i do abd if i do get it to compile how do i package it

**Comment by unknownbrackets** [comment]
Is this still a problem?  What errors do you get?

I've seen written elsewhere that it was compiling for Xbox One or perhaps Xbox Series X, though I didn't read into the details.

-[Unknown]

**Comment by hrydgard** [comment]
Nah, this can be closed. It works, at least to some degree.
