### ISSUE TITLE
Linux compilation error (v1.6.3-274-g5e6429abf)

### ISSUE THREAD

**Issue by thesourcehim** [hrydgard/ppsspp#11231]
Compiler is gcc 8.1.1

In file included from /mnt/d/projects/git/ppsspp/ext/armips/Core/Assembler.h:4,
                 from /mnt/d/projects/git/ppsspp/Core/Debugger/SymbolMap.cpp:41:
/mnt/d/projects/git/ppsspp/ext/armips/Core/FileManager.h:68:21: error: ‘std::shared_ptr’ has not been declared
  bool openFile(std::shared_ptr<AssemblerFile> file, bool onlyCheck);
                     ^~~~~~~~~~
/mnt/d/projects/git/ppsspp/ext/armips/Core/FileManager.h:68:31: error: expected ‘,’ or ‘...’ before ‘<’ token
  bool openFile(std::shared_ptr<AssemblerFile> file, bool onlyCheck);
                               ^
/mnt/d/projects/git/ppsspp/ext/armips/Core/FileManager.h:69:20: error: ‘std::shared_ptr’ has not been declared
  void addFile(std::shared_ptr<AssemblerFile> file);
                    ^~~~~~~~~~
/mnt/d/projects/git/ppsspp/ext/armips/Core/FileManager.h:69:30: error: expected ‘,’ or ‘...’ before ‘<’ token
  void addFile(std::shared_ptr<AssemblerFile> file);
                              ^
/mnt/d/projects/git/ppsspp/ext/armips/Core/FileManager.h:83:7: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
  std::shared_ptr<AssemblerFile> getOpenFile() { return activeFile; };
       ^~~~~~~~~~
/mnt/d/projects/git/ppsspp/ext/armips/Core/FileManager.h:83:2: note: ‘std::shared_ptr’ is defined in header ‘<memory>’; did you forget to ‘#include <memory>’?
/mnt/d/projects/git/ppsspp/ext/armips/Core/FileManager.h:5:1:
+#include <memory>
 
/mnt/d/projects/git/ppsspp/ext/armips/Core/FileManager.h:83:2:
  std::shared_ptr<AssemblerFile> getOpenFile() { return activeFile; };
  ^~~
/mnt/d/projects/git/ppsspp/ext/armips/Core/FileManager.h:88:19: error: ‘shared_ptr’ is not a member of ‘std’
  std::vector<std::shared_ptr<AssemblerFile>> files;
                   ^~~~~~~~~~
/mnt/d/projects/git/ppsspp/ext/armips/Core/FileManager.h:88:19: note: ‘std::shared_ptr’ is defined in header ‘<memory>’; did you forget to ‘#include <memory>’?
/mnt/d/projects/git/ppsspp/ext/armips/Core/FileManager.h:88:19: error: ‘shared_ptr’ is not a member of ‘std’
/mnt/d/projects/git/ppsspp/ext/armips/Core/FileManager.h:88:19: note: ‘std::shared_ptr’ is defined in header ‘<memory>’; did you forget to ‘#include <memory>’?
/mnt/d/projects/git/ppsspp/ext/armips/Core/FileManager.h:88:30: error: template argument 1 is invalid
  std::vector<std::shared_ptr<AssemblerFile>> files;
                              ^~~~~~~~~~~~~
/mnt/d/projects/git/ppsspp/ext/armips/Core/FileManager.h:88:30: error: template argument 2 is invalid
/mnt/d/projects/git/ppsspp/ext/armips/Core/FileManager.h:88:43: error: expected unqualified-id before ‘>’ token
  std::vector<std::shared_ptr<AssemblerFile>> files;
                                           ^~
/mnt/d/projects/git/ppsspp/ext/armips/Core/FileManager.h:89:7: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
  std::shared_ptr<AssemblerFile> activeFile;
       ^~~~~~~~~~
/mnt/d/projects/git/ppsspp/ext/armips/Core/FileManager.h:89:2: note: ‘std::shared_ptr’ is defined in header ‘<memory>’; did you forget to ‘#include <memory>’?
  std::shared_ptr<AssemblerFile> activeFile;
  ^~~
/mnt/d/projects/git/ppsspp/ext/armips/Core/FileManager.h: In member function ‘bool FileManager::hasOpenFile()’:
/mnt/d/projects/git/ppsspp/ext/armips/Core/FileManager.h:70:30: error: ‘activeFile’ was not declared in this scope
  bool hasOpenFile() { return activeFile != nullptr; };
                              ^~~~~~~~~~
/mnt/d/projects/git/ppsspp/ext/armips/Core/FileManager.h:70:30: note: suggested alternative: ‘closeFile’
  bool hasOpenFile() { return activeFile != nullptr; };
                              ^~~~~~~~~~
                              closeFile
In file included from /mnt/d/projects/git/ppsspp/Core/Debugger/SymbolMap.cpp:41:
/mnt/d/projects/git/ppsspp/ext/armips/Core/Assembler.h: At global scope:
/mnt/d/projects/git/ppsspp/ext/armips/Core/Assembler.h:41:7: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
  std::shared_ptr<AssemblerFile> memoryFile;
       ^~~~~~~~~~
/mnt/d/projects/git/ppsspp/ext/armips/Core/Assembler.h:41:2: note: ‘std::shared_ptr’ is defined in header ‘<memory>’; did you forget to ‘#include <memory>’?
/mnt/d/projects/git/ppsspp/ext/armips/Core/Assembler.h:5:1:
+#include <memory>
 
/mnt/d/projects/git/ppsspp/ext/armips/Core/Assembler.h:41:2:
  std::shared_ptr<AssemblerFile> memoryFile;
  ^~~
cc1plus: warning: unrecognized command line option ‘-Wno-deprecated-register’
make[2]: *** [CMakeFiles/Core.dir/build.make:856: CMakeFiles/Core.dir/Core/Debugger/SymbolMap.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:558: CMakeFiles/Core.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by hrydgard** [comment]
Add

    #include <memory>

at the top of FileManager.h ?

**Comment by thesourcehim** [comment]
That helped with this error, however:

/mnt/d/projects/git/ppsspp/Core/MIPS/MIPSAsm.cpp: In function ‘bool MIPSAsm::MipsAssembleOpcode(const char*, DebugInterface*, u32)’:
/mnt/d/projects/git/ppsspp/Core/MIPS/MIPSAsm.cpp:80:21: error: no match for ‘operator=’ (operand types are ‘std::shared_ptr<AssemblerFile>’ and ‘MIPSAsm::PspAssemblerFile*’)
  args.memoryFile = &file;
                     ^~~~
In file included from /usr/include/c++/8/memory:81,
                 from /mnt/d/projects/git/ppsspp/Core/MIPS/MIPSAsm.cpp:7:
/usr/include/c++/8/bits/shared_ptr.h:309:19: note: candidate: ‘std::shared_ptr<_Tp>& std::shared_ptr<_Tp>::operator=(const std::shared_ptr<_Tp>&) [with _Tp = AssemblerFile]’
       shared_ptr& operator=(const shared_ptr&) noexcept = default;
                   ^~~~~~~~
/usr/include/c++/8/bits/shared_ptr.h:309:19: note:   no known conversion for argument 1 from ‘MIPSAsm::PspAssemblerFile*’ to ‘const std::shared_ptr<AssemblerFile>&’
/usr/include/c++/8/bits/shared_ptr.h:313:2: note: candidate: ‘template<class _Yp> std::shared_ptr<_Tp>::_Assignable<const std::shared_ptr<_Yp>&> std::shared_ptr<_Tp>::operator=(const std::shared_ptr<_Yp>&) [with _Yp = _Yp; _Tp = AssemblerFile]’
  operator=(const shared_ptr<_Yp>& __r) noexcept
  ^~~~~~~~
/usr/include/c++/8/bits/shared_ptr.h:313:2: note:   template argument deduction/substitution failed:
/mnt/d/projects/git/ppsspp/Core/MIPS/MIPSAsm.cpp:80:21: note:   mismatched types ‘const std::shared_ptr<_Tp>’ and ‘MIPSAsm::PspAssemblerFile*’
  args.memoryFile = &file;
                     ^~~~
In file included from /usr/include/c++/8/memory:81,
                 from /mnt/d/projects/git/ppsspp/Core/MIPS/MIPSAsm.cpp:7:
/usr/include/c++/8/bits/shared_ptr.h:324:2: note: candidate: ‘template<class _Yp> std::shared_ptr<_Tp>::_Assignable<std::auto_ptr<_Up> > std::shared_ptr<_Tp>::operator=(std::auto_ptr<_Up>&&) [with _Yp = _Yp; _Tp = AssemblerFile]’
  operator=(auto_ptr<_Yp>&& __r)
  ^~~~~~~~
/usr/include/c++/8/bits/shared_ptr.h:324:2: note:   template argument deduction/substitution failed:
/mnt/d/projects/git/ppsspp/Core/MIPS/MIPSAsm.cpp:80:21: note:   mismatched types ‘std::auto_ptr<_Up>’ and ‘MIPSAsm::PspAssemblerFile*’
  args.memoryFile = &file;
                     ^~~~
In file included from /usr/include/c++/8/memory:81,
                 from /mnt/d/projects/git/ppsspp/Core/MIPS/MIPSAsm.cpp:7:
/usr/include/c++/8/bits/shared_ptr.h:333:7: note: candidate: ‘std::shared_ptr<_Tp>& std::shared_ptr<_Tp>::operator=(std::shared_ptr<_Tp>&&) [with _Tp = AssemblerFile]’
       operator=(shared_ptr&& __r) noexcept
       ^~~~~~~~
/usr/include/c++/8/bits/shared_ptr.h:333:7: note:   no known conversion for argument 1 from ‘MIPSAsm::PspAssemblerFile*’ to ‘std::shared_ptr<AssemblerFile>&&’
/usr/include/c++/8/bits/shared_ptr.h:341:2: note: candidate: ‘template<class _Yp> std::shared_ptr<_Tp>::_Assignable<std::shared_ptr<_Yp> > std::shared_ptr<_Tp>::operator=(std::shared_ptr<_Yp>&&) [with _Yp = _Yp; _Tp = AssemblerFile]’
  operator=(shared_ptr<_Yp>&& __r) noexcept
  ^~~~~~~~
/usr/include/c++/8/bits/shared_ptr.h:341:2: note:   template argument deduction/substitution failed:
/mnt/d/projects/git/ppsspp/Core/MIPS/MIPSAsm.cpp:80:21: note:   mismatched types ‘std::shared_ptr<_Tp>’ and ‘MIPSAsm::PspAssemblerFile*’
  args.memoryFile = &file;
                     ^~~~
In file included from /usr/include/c++/8/memory:81,
                 from /mnt/d/projects/git/ppsspp/Core/MIPS/MIPSAsm.cpp:7:
/usr/include/c++/8/bits/shared_ptr.h:349:2: note: candidate: ‘template<class _Yp, class _Del> std::shared_ptr<_Tp>::_Assignable<std::unique_ptr<_Up, _Ep> > std::shared_ptr<_Tp>::operator=(std::unique_ptr<_Up, _Ep>&&) [with _Yp = _Yp; _Del = _Del; _Tp = AssemblerFile]’
  operator=(unique_ptr<_Yp, _Del>&& __r)
  ^~~~~~~~
/usr/include/c++/8/bits/shared_ptr.h:349:2: note:   template argument deduction/substitution failed:
/mnt/d/projects/git/ppsspp/Core/MIPS/MIPSAsm.cpp:80:21: note:   mismatched types ‘std::unique_ptr<_Tp, _Dp>’ and ‘MIPSAsm::PspAssemblerFile*’
  args.memoryFile = &file;
                     ^~~~
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-deprecated-register’
make[2]: *** [CMakeFiles/Core.dir/build.make:2611: CMakeFiles/Core.dir/Core/MIPS/MIPSAsm.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:558: CMakeFiles/Core.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by unknownbrackets** [comment]
Ah - you're using a newer armips than we've yet updated to, I think?  We'll need to change that parameter.

-[Unknown]
