### ISSUE TITLE
SOCOM U.S. Navy SEALs: Tactical Strike unplayable on any version past 1.2.2

### ISSUE THREAD

**Issue by gigajuice** [hrydgard/ppsspp#11239]
### What happens?

Socom Tactical Strike is unplayable on any version past 1.2.2. When the game starts, the Socom logo is watermarked and flashing in the middle of the screen. Also, when switching units, the entire screen flashes a different array of colors. This issues happen on the PC version of PPSSPP and the iPhone version of PPSSPP so i assume it happens with all platforms. I have confirmed that this issue does not happen with version 1.2.2 and below. I can't find that version for the iPhone though which is where i primarily use PPSSPP. 

![socomissue](https://user-images.githubusercontent.com/40864751/42332671-9f42723c-8046-11e8-8cb1-79ac496885ab.jpg)

### What *should* happen?

There shouldn't be flashing colors and the Socom logo when attempting to play the game.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Happens on PC(windows) and iPhone as far as i know. Any version past 1.2.2.

**Comment by gigajuice** [comment]
No one wants to take a crack at this?

**Comment by hrydgard** [comment]
Are you using frameskipping or are you "unthrottling" (using the fast forward button) at any point during loading?

**Comment by SpecialGameOver** [comment]
Seams related to this known old bug https://github.com/hrydgard/ppsspp/issues/8973

**Comment by unknownbrackets** [comment]
I think #8994 was disabled at some point due to performance impact.

-[Unknown]

**Comment by benderscruffy** [comment]
v1.7.1-210-g9bda7cb64
still happens
[UCUS98649_0001.zip](https://github.com/hrydgard/ppsspp/files/2623102/UCUS98649_0001.zip)

**Comment by benderscruffy** [comment]
this can be closed now
![socom](https://user-images.githubusercontent.com/2696404/71754840-f6f4e880-2ec2-11ea-9d7e-048a09ef8f33.PNG)

**Comment by hrydgard** [comment]
Thanks for reporting!
