### ISSUE TITLE
RetroArch Texture Replacement Option?

### ISSUE THREAD

**Issue by DuIslingr** [hrydgard/ppsspp#11242]
Is it currently possible to enable texture replacement on the retroarch version of ppsspp? More specifically I am using Lakka on the switch and it functions albeit a cpl issues, I cannot find a way to enable texture replacement in that or even on the windows version of retroarch. Cannot find any sort of documentation on this and so far nobody on libretro chat or ppsspp irc have answered my question.

**Comment by unknownbrackets** [comment]
It seems like this was probably implemented by #11515.  If this isn't the case, feel free to comment and we'll reopen.

-[Unknown]
