### ISSUE TITLE
compile error on macos

### ISSUE THREAD

**Issue by 1900forever** [hrydgard/ppsspp#11241]
use ./b.sh to compile ppsspp on my mbp, running 10.13.6, error shows as below:

> 
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList are out of sync. Falling back to library file for linking.
Undefined symbols for architecture x86_64:
  "_avcodec_parameters_from_context", referenced from:
      MediaEngine::setVideoStream(int, bool) in libCore.a(MediaEngine.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [PPSSPPSDL.app/Contents/MacOS/PPSSPPSDL] Error 1
make[1]: *** [CMakeFiles/PPSSPPSDL.dir/all] Error 2
make: *** [all] Error 2

**Comment by hrydgard** [comment]
On a freshly updated macOS + brew, I have no issues whatsoever building. Qt build works too.

Tried ./b.sh --debug out of habit though.

**Comment by CarterLi** [comment]
I can confirm this issue. `brew unlink ffmpeg` resolve the problem

**Comment by vit9696** [comment]
This issue happens due to outdated ffmpeg bundled with ppsspp, which has lower inclusion priority to headers from /opt/local/include for MacPorts and /usr/local/include for HomeBrew. cmake finds ffmpeg headers in /opt/local/include directory, yet tries to link to ppsspp bundled ffmpeg, thus the error.

To resolute this I believe one needs to move the ffmpeg lookup upper in cmake source code.

**Comment by hrydgard** [comment]
Lower inclusion priority?? Shouldn't local things always go before system things?  When you say "upper in cmake source code", do you mean somehow in our CMakeLists.txt or in the actual CMake source?

**Comment by vit9696** [comment]
I think from cmake standpoint both are local. I also think cmake may be adding the first include due to SDL2, but I am yet to check it.

Yes, I meant moving upper in CMakeLists.txt.

**Comment by vit9696** [comment]
Should be closed now.
