### ISSUE TITLE
Can we get Patapon 3 multiplayer patched with this for now?

### ISSUE THREAD

**Issue by TehPlayer14** [hrydgard/ppsspp#11248]
https://youtu.be/xv2FNJigjew

Via cheats it forces games to synchronize

**Comment by unknownbrackets** [comment]
Is this still an issue on the latest git build with recent networking improvements?

-[Unknown]

**Comment by ANR2ME** [comment]
Yes, it's fixed, multiplayer cheat code no longer needed, and as i remembered on Patapon 3 community discord, using the multiplayer cheat on the already fixed PPSSPP could cause a stability issue.
