### ISSUE TITLE
Black Screen Problem

### ISSUE THREAD

**Issue by marquisavrin** [hrydgard/ppsspp#11251]
I have a black screen on Ultimate Ninja Heroes 3, i can move the joystick and click the buttons. But no audio. It's just a black screen.

I'm using a Asus Zenfone 2.

**Comment by marquisavrin** [comment]
It didn't show any logos or anything.

So here's the screenshot: https://ibb.co/ccQq1o

**Comment by Emulatorer** [comment]
Duplicate issue of #9591

**Comment by unknownbrackets** [comment]
Thanks, closing as duplicate.

-[Unknown]
