### ISSUE TITLE
crash when starting ppssp in ubuntu 18.04 32bit on kernel  4.15.0-23-generic

### ISSUE THREAD

**Issue by mnabila** [hrydgard/ppsspp#11259]
$ppsspp
I: Config.cpp:440: Longest display side: -1 pixels. Choosing scale 1
08:23:931 Core/Config.cpp:1418 E[LOADER]: Failed to read /home/dani/.config/ppsspp/PSP/SYSTEM/controls.ini. Setting controller config to default.
I: QtMain.cpp:385: Initializing GL graphics context
I: gpu_features.cpp:142: GPU Vendor : Intel Open Source Technology Center ; renderer: Mesa DRI Mobile Intel® GM45 Express Chipset x86/MMX/SSE2 version str: 2.1 Mesa 18.0.5 ; GLSL version str: 1.20
I: QtMain.cpp:387: Using thread, starting emu thread
I: NativeApp.cpp:1152: NativeResized ignored, not initialized
I: NativeApp.cpp:659: NativeInitGraphics
I: NativeApp.cpp:735: NativeInitGraphics completed
dbus[1175]: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file ../../../dbus/dbus-message.c line 1362.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
[1]    1175 abort      ppsspp

when i try to start pspspp program, i got the error message, guess about how to solve it?
thank you.
sorry if my inggriss ugly
_translated from indonesian to english using google translate_

**Comment by unknownbrackets** [comment]
The error references "D-Bus".  We don't directly use D-Bus.

It looks like you are using PPSSPPQt.  Did you compile this?  Or did you download it pre-compiled from a ppa?

Does PPSSPPSDL work?  PPSSPPSDL may use Vulkan instead of OpenGL.  PPSSPPQt can only use OpenGL.

-[Unknown]

**Comment by nabil48** [comment]
I downloaded it pre-compiled from unstable ppa version [ppa:ppsspp/testing](https://launchpad.net/~ppsspp/+archive/ubuntu/testing)[
![screenshot_20180722_080712](https://user-images.githubusercontent.com/37516576/43041305-6140c036-8d86-11e8-86a0-201d7e1bfd16.png)
](url)

**Comment by unknownbrackets** [comment]
I'd recommend trying a compile for Qt.  It usually doesn't take that much to compile:

https://github.com/hrydgard/ppsspp/wiki/Build-instructions#building-for-qt-platforms

It may simply be that the packages on your system aren't compatible with whatever version of things that ppa used for compilation.

-[Unknown]

**Comment by unknownbrackets** [comment]
Is this still happening?  Did you try compiling?

-[Unknown]

**Comment by Nine-H** [comment]
testing and stable ppas are shipping 1.7.0, it's going to cause a ton of issues, is there a ppa maintainer? as I understood it they're official.

**Comment by unknownbrackets** [comment]
See #11661 and #11520.  As far as I know, none of the contributors who commit to this repo (hrydgard/ppsspp) have access to that ppa.  It's maintained by @sergiobenrocha2.

Generally, all the builds you'll find of PPSSPP except Windows and Android are not "really" official.  Actually, even the git builds just come from Orphis who has graciously setup his buildbot for PPSSPP.

-[Unknown]

**Comment by Nine-H** [comment]
might be time to set up an official channel, appimage is pretty painless. sergio might fix his ppa now he's been pinged.

**Comment by unknownbrackets** [comment]
It sounds like the latest versions are working, just not as easily available and require compilation.  That said, there hasn't been feedback on the specific D-Bus error in over a year.

Given that, I'm going to close this.  #11661 already exists for the lack of builds.

-[Unknown]
