### ISSUE TITLE
In menu is 2x same pic.0 texture of the game

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#11252]
![screenshot_20180714-113105](https://user-images.githubusercontent.com/33152267/42723213-2504f61e-875a-11e8-9780-9959b4fd1b97.png)
Game is extracted only 1x
I have this problem on Android

**Comment by marosis** [comment]
Ehhmmm not pic.0 but Icon.0 my bad

**Comment by Drasikk** [comment]
DTM work good? Or have graphic errors?

**Comment by marosis** [comment]
@Drasikk you can see here #5001

**Comment by 1234Sameer** [comment]
@marosis 
I don't clearly understand the title of the issue but if you mean duplicate icons in the recent list, you might want to see #11131 by @leopard20 .

**Comment by marosis** [comment]
Ok i will write it to #11131 And close this issue

**Comment by marosis** [comment]
Thank you
