### ISSUE TITLE
Patapon 3 graphic bugs [PC/Android]

### ISSUE THREAD

**Issue by TehPlayer14** [hrydgard/ppsspp#11250]
https://youtu.be/EMwqAKum_oY?t=1m

There should be text where the commands are shown when the dark texture moves over

Also that right panel on Android always stays on screen when in Adhoc mode

**Comment by hrydgard** [comment]
Does it work correctly with the other backends?

**Comment by TehPlayer14** [comment]
No it does not it works fine with OpenGL, its vulkan only

Just checked it

**Comment by unknownbrackets** [comment]
Could you try exporting a GE debugger dump on PC?

To do this, open the game and select Debug -> GE debugger..., then when it's displaying the scene, press Record in the top right.  After a second or so, it'll finish and save a trace of the drawing activity.

After that, check the memstick/PSP/SYSTEM/DUMP folder and it'll have created a file named something like "ULES12345_0000.ppdmp".  You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by TehPlayer14** [comment]
Sure Unknown will do soon

**Comment by TehPlayer14** [comment]
I'm sorry for not updating on this been a while and forgot, but on PC it works fine now, probably on Android too

**Comment by unknownbrackets** [comment]
Thanks for the update, glad it's working now.

-[Unknown]
