### ISSUE TITLE
Constant 96% speed

### ISSUE THREAD

**Issue by acrosstheline** [hrydgard/ppsspp#11264]
### What happens?

Games don't reach full speed despite the hardware being more than enough to achieve it. In almost all the games I try the speed remains between 95 and 98% and the result is not smooth gameplay and crackling audio. I haven't had the problem on other devices and people with the same device don't have the problem either. So it seems to be a unique case. One of the things that I assume could be the cause is the big cores not waking up in the app. However, both easier and harder to emulate games lock around that speed in particular which makes no sense. If the little cores could achieve that speed in some simple 2d rpg, wouldn't they struggle even more in Ridge Racer for example? I'm not sure it's a governor or cpu scheduler issue either as like I said other with same device and software can't replicate the problem.

### What *should* happen?

I assume I should be able to run some games at full speed. Some of the titles I've tried are Ragnarok tactics, FF Crisis Core, Persona 3 and Growlanser all of which I've ran full speed on less capable hardware.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Nokia 8 (Snapdragon 835, adreno 540), android 8.1, ppsspp 1.6.3, 1.5 and older stable builds on default settings.

**Comment by LunaMoo** [comment]
If all the games you're trying are running at 60fps it could simply be a limitation of your display, android has forced vsync and some devices have screens with weird refresh rate like 55 or 58. I think there was some try to work around such issue, but it might not work in which case try frameskipping.

 Also PPSSPP as an emulator doesn't fit typical(but stupid) optimizations aimed at native games, so android might give it not enough power and things like that, there's nothing PPSSPP can do to avoid that, althrough some settings that makes it heavier like force real clock sync might sometimes help.

**Comment by acrosstheline** [comment]
The display refresh rate is 60hz.

As I said, I was suspecting the scheduler not giving the app priority and using the big cores but then again other people with the same phone and software don't experience such problems.

Forcing the real clock sync didn't help either. Thanks for the suggestion.

**Comment by hrydgard** [comment]
That is very strange. So it shows 60 hz when you lookup the frame rate in PPSSPP's system information?

**Comment by acrosstheline** [comment]
Yes. Lower refresh rate of the panel would explain the problem but the system info in the app says 60.000hz. Checked it with Aida 64 for confirmation and it also says 60hz. I've never had issues with other emulators with games that run in native 60fps either.

**Comment by unknownbrackets** [comment]
This happened on the Nexus 5, which had a lower than 60 Hz rate:

https://forum.xda-developers.com/google-nexus-5/devs-only/how-fix-stuttering-concerning-58-6hz-t2989311
https://issuetracker.google.com/issues/37015715

You might try the calibrate feature mentioned to double check.

Is it safe to assume that using auto frameskip, you get full speed (but not 60 fps)?

-[Unknown]

**Comment by marosis** [comment]
I have same problem lenovo C2

**Comment by TehPlayer14** [comment]
Yeah some phones have under 60fps... and it drops 1 frame per 60 frames

**Comment by TehPlayer14** [comment]
Can we close this?

Since there doesn't seem to be an option to have that 60 frames on some devices
