### ISSUE TITLE
Ultimate Ghost's n Goblins graphical issues in Raspberry Pi 3

### ISSUE THREAD

**Issue by luizthiagor** [hrydgard/ppsspp#11267]
### What happens?

I have problems with this game in my RPI3 even if in v 1.5.4 or in new 1.6.3  - The game starts OK, but when i try to play, in level one the screen gets very black and only the Arthur (main person of game) are visible ... the rest of scenary game dissapeared  - I have tried several configs but none results in correction of this bug

### What *should* happen?

The game should work well in RPI3 because are an 2D game and has a lot of power to run it ..but the grapical issues related turn this game unplayable ....   :(

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

RPI3 , Batocera Linux 5.15 or 5.16 with the 1.5.4 or 1.6.3 (same problem in all this versions)

**Comment by luizthiagor** [comment]
has any specif configs to run this game ? i have tried in my raspberry PI3 even in the 1.5.4 or in 1.6.3 and tried some configs, but none ...

**Comment by luizthiagor** [comment]
I have tested and old version of Fev/2017 and still not playable for this game in raspberry ...so, if i stay in very old version or in 1.5.4 or in new 1.6.3 ....the same...this game is unplayable in Raspberry Pi 3 ...

**Comment by unknownbrackets** [comment]
Is this the same as #5915?

If not - could you try exporting a GE debugger dump on PC?  And can you confirm the bug doesn't occur on PC, and is specific to the Raspberry Pi?

To do this, open the game and select Debug -> GE debugger..., then when it's displaying the scene, press Record in the top right.  After a second or so, it'll finish and save a trace of the drawing activity.

After that, check the memstick/PSP/SYSTEM/DUMP folder and it'll have created a file named something like "ULES12345_0000.ppdmp".  You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by luizthiagor** [comment]
This is not the same problem, but is similar ....

i'm on Batocera Linux 5.17 with 1.5.4 ppsspp (last commit) [because 1.6.3 is loss performance on the Raspberry Pi 3]

how i can help here , operating in raspberry ?

**Comment by unknownbrackets** [comment]
I'll see if I can spend some time and create a UI to create a GE debugger dump from Linux.  Currently there's no UI, but it can be retrieved via the WebSocket API - just need to create a quick page that shows a button to press and downloads the file.

I hope it's not just driver bugs...

-[Unknown]

**Comment by luizthiagor** [comment]
thanks friend ....

Otherwise, the main "problem" is about i'm running ppsspp from a raspberry Pi 3 ....so, i don't understand why i can get as debbuger in this platform ....

I still believe if devs can have an Rpi 3 and can do tests in it, will be so great ! 

Because PPSSPP is amazing ...even im my rpi with the last commit of 1.5.4 i can run games like GoW - CoO well and playable...i have video in youtube about this ! ...but in newer versions 1.6.3 the performance is so bad .... unplayable .....

but the main problem in this topic with this specific game still remaining in all versions  ....1.5.4 or 1.6.3, the same

**Comment by unknownbrackets** [comment]
Circled back to this finally.  Go here:

http://ppsspp-debugger.unknownbrackets.org/gpu

And you'll be able to download a GE dump (just start the game first.)  You may have to switch to PPSSPP so it runs before it'll download.  Should work in any reasonably up to date browser.

-[Unknown]
