### ISSUE TITLE
While compiling arm libretro latest ~HEAD

### ISSUE THREAD

**Issue by Ntemis** [hrydgard/ppsspp#11276]
../ext/glslang/glslang/MachineIndependent/glslang_tab.o:glslang_tab.cpp:function yyparse(glslang::TParseContext*): error: undefined reference to 'glslang::TParseContext::makeAttributes(std::basic_string<char, std::char_traits<char>, glslang::pool_allocator<char> > const&) const'
../ext/glslang/glslang/MachineIndependent/glslang_tab.o:glslang_tab.cpp:function yyparse(glslang::TParseContext*): error: undefined reference to 'glslang::TParseContext::makeAttributes(std::basic_string<char, std::char_traits<char>, glslang::pool_allocator<char> > const&, TIntermNode*) const'
../ext/glslang/glslang/MachineIndependent/glslang_tab.o:glslang_tab.cpp:function yyparse(glslang::TParseContext*): error: undefined reference to 'glslang::TParseContext::mergeAttributes(glslang::TList<glslang::TAttributeArgs>*, glslang::TList<glslang::TAttributeArgs>*) const'
../ext/glslang/glslang/MachineIndependent/glslang_tab.o:glslang_tab.cpp:function yyparse(glslang::TParseContext*): error: undefined reference to 'glslang::TParseContext::handleSwitchAttributes(glslang::TList<glslang::TAttributeArgs> const&, TIntermNode*)'
../ext/glslang/glslang/MachineIndependent/glslang_tab.o:glslang_tab.cpp:function yyparse(glslang::TParseContext*): error: undefined reference to 'glslang::TParseContext::handleLoopAttributes(glslang::TList<glslang::TAttributeArgs> const&, TIntermNode*)'
../ext/glslang/glslang/MachineIndependent/glslang_tab.o:glslang_tab.cpp:function yyparse(glslang::TParseContext*): error: undefined reference to 'glslang::TParseContext::handleSelectionAttributes(glslang::TList<glslang::TAttributeArgs> const&, TIntermNode*)'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:468: ppsspp_libretro.so] Error 1

**Comment by hrydgard** [comment]
Make sure to update submodules properly. Or might need to add a missing file or two from glslang to the retro build system?

**Comment by hrydgard** [comment]
I see, sounds like I should update glslang again. Will do shortly.
