### ISSUE TITLE
Transformers takes minutes to start up

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#11272]
Another one reported through email.

"Yes, Transformers will launch but takes about 10 minutes. I have a Samsung Note 3 running Android 8.1, Remix Mini Android 5.1, and a Gpd Xd Android 4.4. Seem to be that way on all devices. "

We do still have some pathological behaviour in the loader where we loop through stuff unnecessarily for every section, or something like that, don't remember right now.

**Comment by unknownbrackets** [comment]
I thought that loader thing was only in debug mode?

-[Unknown]

**Comment by unknownbrackets** [comment]
I wonder if they are talking about BEFORE the game technically boots or not.  Maybe this is another case of the max 60 fps thing misbehaving.  It'd help to understand what they see while they are waiting and before they start waiting (e.g. does the loading spinner go away, etc.)

-[Unknown]

**Comment by unknownbrackets** [comment]
Is this still an issue?

-[Unknown]

**Comment by hrydgard** [comment]
Confirmed fixed.
