### ISSUE TITLE
Videos showing garbled. but have sound

### ISSUE THREAD

**Issue by dmschwartzii** [hrydgard/ppsspp#11278]
using libreto ppsspp videos in game are garbled

**Comment by hrydgard** [comment]
Likely linked with the wrong version of ffmpeg?

**Comment by dmschwartzii** [comment]
Lakka uses releases from here: https://github.com/FFmpeg/FFmpeg/releases

**Comment by dmschwartzii** [comment]
@Ntemis

**Comment by unknownbrackets** [comment]
FFmpeg specifically does not maintain compatibility between releases.  Like saying your USB-C plug doesn't seem to charge your Galaxy S3.  It's absolutely expected that randomly updating FFmpeg past the version we're compatible with will cause issues.

Small projects with stable APIs, like zlib or xxhash, are different stories.  But FFmpeg breaks their API all the time.

-[Unknown]

**Comment by dmschwartzii** [comment]
Even using your ffmpeg 2.7.2 the issue persists

**Comment by dmschwartzii** [comment]
@unknownbrackets

**Comment by unknownbrackets** [comment]
Must be something specific to libretro then, I suppose.  Although we use 3.0.2 on most platforms.

-[Unknown]

**Comment by Ntemis** [comment]
Hi there, Lakka uses what comes with ppsspp git submodules and to be clear we dont use our own ffmpeg version. what i have told @dmschwartzii  is that we have garbled video in intros in all the boards even the most supported ones like the raspberry pi's after he open an issue in our repo.
After i had a look i saw this
https://github.com/hrydgard/ppsspp-ffmpeg/commits?author=sergiobenrocha2
and looks like ffmpeg hasn't been updated for armv7 for a long time now ofc i might be wrong in the first place assuming it as the culprit

**Comment by orbea** [comment]
@Ntemis Can you test if updating the arm build for ffmpeg helps? I don't have the hardware to test.

**Comment by unknownbrackets** [comment]
Given #14176, I'm going to assume this is now fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
