### ISSUE TITLE
Graphics error

### ISSUE THREAD

**Issue by MegaLord22** [hrydgard/ppsspp#11270]
Help me the graphics are going liney and stuff
![ulus10234_00000](https://user-images.githubusercontent.com/40259191/43353996-8c7fe734-9265-11e8-9de2-91004c8be145.jpg)

**Comment by hrydgard** [comment]
You didn't just change the Texture Filtering option from Auto to Nearest?

**Comment by MegaLord22** [comment]
![ulus10234_00001](https://user-images.githubusercontent.com/40259191/43355774-3b73618a-9284-11e8-8110-cd9bb6cc9a75.jpg)
works
