### ISSUE TITLE
1xPSP hardware scaler glitches on tablet

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#11289]
### What happens?
![screenshot_2018-08-06-17-39-13-105](https://user-images.githubusercontent.com/33152267/43726643-fbfb5ec2-999f-11e8-95fe-35ee75ae4465.jpeg)
Issue with 1xPSP resolution on tablet (maybe because of big screen?)

**Comment by marosis** [comment]
It is display resolution not rendering resolution

**Comment by unknownbrackets** [comment]
Are you using 1x or auto hardware scaler?  This might be a driver bug when we try to set 1x in that case.

-[Unknown]

**Comment by marosis** [comment]
I using native. On first launch i have 2xPSP. But when i will set 1xPSP i will get this. Overclicking over this bug is for long time, so i go to the android settings, clean saved data and relaunch emulator

**Comment by unknownbrackets** [comment]
I assume that means that this:
https://github.com/hrydgard/ppsspp/blob/b9388f50e1b203cb53302ad67129c046dfc3abca/android/src/org/ppsspp/ppsspp/NativeActivity.java#L571

Is failing on that device for certain resolutions.  It looks to me like it set the stride wrong.

-[Unknown]

**Comment by marosis** [comment]
Oh. This looks like for along time this fixing

**Comment by hrydgard** [comment]
I'm starting to think we should probably get rid of the hardware scaler stuff. It is a minor speed boost but worth all the trouble? not sure..

**Comment by hrydgard** [comment]
Well the biggest gain is on the very weakest devices, and that means 1x. Although they're kind of all getting too old.. just because they're in my pile of devices doesn't mean that anyone out there still use them. But hm, maybe it would help this particular issue restrict it to sizes divisible by 2 or 4 pixels or something..

**Comment by marosis** [comment]
This tablet isn't weak. Games are running to stable 20-30 fps(some games 40). Are only some kind of games, what have poor performance like juiced 2 or dante's inferno

**Comment by hrydgard** [comment]
Turns out this kind of stuff happens even with setFixedSize(0, 0) (auto size) on some other PowerVR, see #11743. Hm, maybe we just need to find some resolution that works and enforce that... Sigh.

**Comment by hrydgard** [comment]
Seems we need to make sure that any custom display resolutions are divisible by 32 horizontally.

**Comment by unknownbrackets** [comment]
So we could only do anything different when the width is not divisible right?

But hmm, the Pixel 3 has 2160 which is not divisible by 32... so only do it on PowerVR?

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, this seems PowerVR-specific.

**Comment by marosis** [comment]
Dont forget Tell me to test after implementing pull request.

**Comment by hrydgard** [comment]
@marosis  This should be fixed in the latest builds.

**Comment by marosis** [comment]
Ok i will test it tomorrow:)

**Comment by marosis** [comment]
![screenshot_2019-02-01-16-15-21-862](https://user-images.githubusercontent.com/33152267/52131335-cd8d6600-263c-11e9-8919-945f69154c4f.jpeg)

**Comment by marosis** [comment]
I can confirm issue Is fixed. Closing as fixed
