### ISSUE TITLE
Valhalla Knights series Networking

### ISSUE THREAD

**Issue by Rathh** [hrydgard/ppsspp#11286]
### What happens?
In Valhalla Knights, Valhalla Knights 2 and Valhalla Knights 2: Battle Stance, when attempting to host a match through Ad-Hoc, the game shows a "blank" screen, as if searching for other players, and does not show any options until prompted to back out from said screen.
The game is supposed to host a match so that other players can join it.

### What should happen?
https://www.youtube.com/watch?v=GFEWUhEONUo
As shown at the start of the video, the session should be hosted and options for the quest should be given after.

My friends and I used PPSSPP v1.6.3 in Windows 7 and 10 while attempting to connect to each other. We also tested the PSP-1000 and PSP-2000/3000 PSP model options and saw no difference.

Log from Valhalla Knights 2 (last two lines are red, if it matters):

```
14:31:508 root         N[G3D]: GLES\ShaderManagerGLES.cpp:906 Precompiling the shader cache from 'C:\ppsspp\memstick/PSP/SYSTEM/CACHE//ULUS10366.glshadercache'
14:31:511 root         N[G3D]: GLES\ShaderManagerGLES.cpp:987 Compiled and linked 94 programs (37 vertex, 20 fragment) in 3.6 milliseconds
14:31:512 root         N[BOOT]: EmuScreen.cpp:278 Loading C:/ppsspp/ISOs/Valhalla Knights 2.iso...
14:48:725 user_main    E[SCEKERNEL]: HLE\sceKernelThread.cpp:28 800201a1=sceKernelDeleteCallback(0): bad cbId
14:55:736 user_main    E[SCEUTIL]: HLE\sceUtility.cpp:497 UNIMPL 00000000=sceUtilityNetconfUpdate(1)
```

Second to last line happens when networking starts. Last line is when the game attempts to host a session.

**Comment by unknownbrackets** [comment]
Is this still an issue on the latest git build with recent networking improvements?

-[Unknown]

**Comment by Rathh** [comment]
Yes, the issue is the same as described.

**Comment by unknownbrackets** [comment]
At least the log lines should be different - sceUtilityNetconfUpdate should be working better now.

Everyone involved is using the latest git build, not v1.10.3 or some older version, right?

-[Unknown]

**Comment by Rathh** [comment]
Yes, I'm hosting on 1.10.3. The log does indeed look different, nothing comes up when I try to host, and I can't back out from the "blank" screen anymore.
Log:
`48:13:468 root         N[BOOT]: UI\EmuScreen.cpp:299 Loading C:/ppsspp/ISOs/Valhalla Knights 2.iso...
48:34:555 user_main    E[SCEKERNEL]: HLE\sceKernelThread.cpp:2827 800201a1=sceKernelDeleteCallback(0): bad cbId
`

**Comment by unknownbrackets** [comment]
The fixes I'm talking about are not in v1.10.3.  Just like Windows 95, we're never going to update that old version with the improvements from newer versions.

There are networking improvements in the latest git builds available here:
https://buildbot.orphis.net/ppsspp/

There have been around 1400 different improvements made to PPSSPP since v1.10.3.  Many of those hundreds of changes may have fixed this issue.

-[Unknown]

**Comment by ANR2ME** [comment]
Well.. Valhalla Knights 2 (US) worked fine on localhost, i can't tested it on LAN anymore since remote disc streaming no longer works now :(

**Comment by unknownbrackets** [comment]
Alright, sounds like it's fixed in the latest git builds, then.

Closing - if there are still issues we can reopen.

-[Unknown]
