### ISSUE TITLE
I can’t save any game it shows me ‘unable to save data , disk maybe full’ I still got 15gb space free on my iPhone 6s iOS 11.3.1 any solution please ?

### ISSUE THREAD

**Issue by simo514** [hrydgard/ppsspp#11291]

**Comment by marosis** [comment]
And do you have set memory stick inserted in settings?

**Comment by rKsanu2MMYvypWePtQWM** [comment]
Same here, 11.3.1 6+. Stick is inserted. I guess it has something to do with permissions. Also the folder PSP is missing in Documents folder, idk if it has something to do with this problem.

**Comment by rKsanu2MMYvypWePtQWM** [comment]
Fixed by setting owner of Documents to mobile. Now if only the problem with exiting the emulator on iOS gets fixed...

**Comment by unknownbrackets** [comment]
Okay - going to close this, then.  I think different methods of installing iOS apps have permission / file ownership issues.

It used to just silently not save, which was pretty terrible.

-[Unknown]
