### ISSUE TITLE
Warrior Orochi Enemy Missing

### ISSUE THREAD

**Issue by Exiasa** [hrydgard/ppsspp#11299]
My HP name is Redmi Note 4 SnapDragon 
Spec 2.0GHZ Octa Core ARM64

PPSSPP Ver: 1.6.3 Vulkan

All Graphic Setting and Developer setting change but still same?

**Comment by LunaMoo** [comment]
Closing as a duplicate of #9843
Please search for existing issues before opening a new one, duplicate issues makes it harder to track and fix things.
