### ISSUE TITLE
lakka-Retroarch: Frameskip and skip buffer effects unusable

### ISSUE THREAD

**Issue by Renetrox** [hrydgard/ppsspp#11292]
I downloaded Lakka version 2.1 of development and ppsspp still has failures. One of them has to do with the option of "frameskip", it is unusable, when setting it, the game disappears, only the sound is heard, when using the option "non buffered" the screen is flipped. I placed the PPSSPP folder in System, but that does not change anything.
Lakka 2.1 nigthlty
hw: Raspberry pi 3b

**Comment by orbea** [comment]
I can reproduce the issue with `frameskip`, when set to `1` the video breaks. The video will start working again if its set to `0` again.

**Comment by unknownbrackets** [comment]
This is probably the same as #14783.  I'm closing assuming that resolved things, please comment if the issue still exists.

-[Unknown]
