### ISSUE TITLE
Compile on android with a error

### ISSUE THREAD

**Issue by innovation2013** [hrydgard/ppsspp#11302]
[armeabi-v7a] Compile++ thumb: armips <= PsxRelocator.cpp
jni/../../Core/FileSystems/DirectoryFileSystem.cpp:903Git not on path, trying default Msysgit paths...
:31[armeabi-v7a] Compile++ thumb: armips <= CAssemblerCommand.cpp
: "C:\Program Files (x86)\Git\bin\git.exe"
error: [armeabi-v7a] Compile++ thumb: armips <= CAssemblerLabel.cpp
use of undeclared identifier [armeabi-v7a][armeabi-v7a] Compile++ thumb: Compile++ thumb: armips <= CDirectiveConditional.cpp armips <= CDirectiveArea.cpp

'findData'
[armeabi-v7a] Compile++ thumb: armips <= CDirectiveData.cpp
                if (!listingRoot || (wcscmp(findData.cFileName, L"..") && wcscmp(findData.cFileName, L".")))
                                            ^
jni/../../Core/FileSystems/DirectoryFileSystem.cpp:903:68: error[armeabi-v7a] Compile++ thumb: armips <= CDirectiveFile.cpp
: use of undeclared identifier 'findData'
                if (!listingRoot || (wcscmp(findData.cFileName, L"..") && wcscmp(findData.cFileName, L".")))
                                                                                 ^
2 errors generated.
make: *** [obj/local/armeabi-v7a/objs/ppsspp_core/__/__/Core/FileSystems/DirectoryFileSystem.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by unknownbrackets** [comment]
Fixed by #11301 - update to the latest git.

-[Unknown]
