### ISSUE TITLE
GLES: Issues of untick Disable slower effects(speedup)

### ISSUE THREAD

**Issue by lim2222** [hrydgard/ppsspp#11304]
### What happens?
Starting from version v1.6.3-341-g187204d7b,whenever Disable slower effects(speedup) is untick,ppsspp will crash at certain point.
Even it did not crash at some game but some of the graphic effects was missing,like FF Type zero charactor's shadow missing,POP revelations totally broken with Disable slower effects untick.
This video may tell
https://www.youtube.com/watch?v=zg1fRk0opeM
### What *should* happen?
Last known good version v1.6.3-334-g7aa71fc84

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Oneplus 5 Adroid 8.1

**Comment by unknownbrackets** [comment]
Should be fixed by #11308.  Closing, but if you still get the issue, just reply and I'll reopen.

-[Unknown]

**Comment by lim2222** [comment]
Thanks,issues solved.
