### ISSUE TITLE
[Rich Presence] Game turning into unknown game, or no games at all being recognized.

### ISSUE THREAD

**Issue by AkiraJkr** [hrydgard/ppsspp#11309]
Currently, there is no steps to reproduce this issue, but I've seen and experienced this happening sometimes. This needs some investigation.

**Comment by unknownbrackets** [comment]
Maybe there's a race condition here:
https://github.com/hrydgard/ppsspp/blob/0684068c8178d9afc649f4667b0da5924782b996/UI/EmuScreen.cpp#L193

If you load the game in some way that the cache doesn't yet have info for it (maybe via shortcut?) immediately, and the loading background image doesn't have a chance to display, it's possible this might still not be set.

This might also explain reports that sometimes the game config doesn't load properly?

-[Unknown]

**Comment by Drayano** [comment]
I have the "untitled psp game" showing up everytime i try to launch a game either through Launchbox front-end or normally through the emulator. However, stopping the emulation via CTRL+W then loading a game makes it showing up properly only if the game is present on the "recently loaded" list (i noticed it doesn't work if it's the first time i boot the game).

**Comment by hrydgard** [comment]
This should be fixed now, please try it and report.

**Comment by Drayano** [comment]
Can confirm it's fixed now, even when launching through a front-end !
