### ISSUE TITLE
[MacOS] Rich Presence fails/ RP Suggestions

### ISSUE THREAD

**Issue by ExperiBass** [hrydgard/ppsspp#11303]
Ive ben playing WipEout Pure with PPSSPP on my MacBook Air, and I've noticed that PPSSPP doesn't pop up as a game. It's not even in the dropdown for selecting a game.

Im running MacOS High Sierra (10.13.6), and my PPSSPP version is 1.6.3.

Suggestion for Rich Presence:
Could we have the RP show the game we're playing?

**Comment by LunaMoo** [comment]
Outdated PPSSPP versions will not have features that were just merged.
Closing as non issue, through no clue, if that stuff isn't platform dependant.

**Comment by GingkathFox** [comment]
@LunaMoo um, it shows up as blank after I re-installed it. You sure this isn't an issue?

**Comment by hrydgard** [comment]
It is absolutely an issue. I've only enabled it on Windows so far, will fix it on the Mac soon.

**Comment by GingkathFox** [comment]
Ok!

**Comment by GingkathFox** [comment]
@hrydgard I downloaded the latest version, but PPSSPP is still popping up as empty in Mac and Ubuntu.

**Comment by unknownbrackets** [comment]
If you start it from a Terminal, does the log say anything about Discord?

-[Unknown]

**Comment by GingkathFox** [comment]
I dunno how to start from terminal, but ill check the logs on MacOS

**Comment by GingkathFox** [comment]
I don't see anything about Discord in it.

**Comment by benderscruffy** [comment]
Please close as this has not been updated in years
