### ISSUE TITLE
Texture scaling causing black screen when launching multiple games (RetroArch)

### ISSUE THREAD

**Issue by BParks21** [hrydgard/ppsspp#11339]
### What happens?
If texture scaling is set to anything but 1 launching another psp game in the same retroarch session causes a black screen. This is in RetroArch only on Windows and Android.

### What *should* happen?
Should be able to launch multiple games without a black screen when using other texture scaling values.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.System Specs:
Operating System: Windows 10 Pro 64-bit
MOBO: Asus Maximus IX Code
Processor/CPU: Intel(R) Core(TM) i7-7700k @5ghz
Video Card/GPU: MSI GTX 1080 Ti
Memory/RAM: 32GB DDR4 @3000Mhz

**Comment by fr500** [comment]
Ditto for this one, I can't reproduce on my shield

**Comment by orbea** [comment]
I can reproduce the black screen when starting a second game with ppsspp in a single RetroArch session in linux.

I suspect its related to issue https://github.com/hrydgard/ppsspp/issues/10784.

**Comment by BParks21** [comment]
This is fixed!
