### ISSUE TITLE
Core crashing when closing game (RetroArch64 bit Android)

### ISSUE THREAD

**Issue by BParks21** [hrydgard/ppsspp#11340]
### What happens?
Load a game using the latest core in RetroArch64 bit for andoid and close the game, RetroArch freezes.

### What *should* happen?
Close game no freeze.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Operating System: Windows 10 Pro 64-bit
MOBO: Asus Maximus IX Code
Processor/CPU: Intel(R) Core(TM) i7-7700k @5ghz
Video Card/GPU: MSI GTX 1080Ti
Memory/RAM: 32GB DDR4 @3000Mhz

**Comment by fr500** [comment]
I can't reproduce this on my NVIDIA Shield

**Comment by orbea** [comment]
I can't reproduce this on Linux either.
