### ISSUE TITLE
Folder permanently pinned even if deleted/not existing.

### ISSUE THREAD

**Issue by AkiraJkr** [hrydgard/ppsspp#11356]
How to repro:

1. Make a folder
2. Put a game on it
3. Start said game
4. Delete the folder
5. Browse other folders inside PPSSPP

And that folder will be pinned and following you wherever you go. No matter what.
![image](https://user-images.githubusercontent.com/27028529/45046791-9f840580-b04d-11e8-8abb-641391d55e85.png)

**Comment by unknownbrackets** [comment]
Pinning /should/ require you to hit `+`.  I can't reproduce it being automatically added when you run a game, which should not happen.

That said, once one is added (perhaps by accidental tap), it can cause problems if it's been deleted.  Fixing.

-[Unknown]
