### ISSUE TITLE
Android：Graphics Backend swtiching problems

### ISSUE THREAD

**Issue by lim2222** [hrydgard/ppsspp#11359]
### What happens?
Regression staring from v1.6.3-423-g562c5f648,whenever graphics backend switch to vulkan then hardly to switch back to opengl from UI.
Changing inside ppsspp.ini by editing backend to number other than 0 or 3 would change to opengl

### What *should* happen?
This video tells the story
[https://www.youtube.com/watch?v=WtGqxQKSjyk](url)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Oneplus 5,oxygenos 5.1.5,android 8.1.0

**Comment by unknownbrackets** [comment]
Can you get an adb logcat?  Before, did PPSSPP close or crash when changing backends?

-[Unknown]

**Comment by lim2222** [comment]
PPSSPP did not close or crash,what command should i write for the logcat,
This one ok? adb logcat -s DEBUG PPSSPPNativeActivity PPSSPP NativeGLView NativeRenderer NativeSurfaceView

**Comment by unknownbrackets** [comment]
Just to make sure - can you try clearing the cache on the app?

https://www.lifewire.com/clear-cache-android-4157780#heading-block_1-0-1

Though, it doesn't look like it's detecting a crash.  If you downgrade to an older git build, does it work?

-[Unknown]

**Comment by lim2222** [comment]
Yes,i did cleared app cache and data then wipe cache in recovery also try to uninstall ppsspp then reinstall still same problems happen.
v1.6.3-420-gf87dcefdd can switch backend with no problem.

**Comment by unknownbrackets** [comment]
I added some additional logging.  Could you try the latest git build and post the adb logcat again?

It should include a log line like "Failed graphics backends:".

-[Unknown]

**Comment by lim2222** [comment]
09-06 22:13:19.147  7664  7664 E PPSSPP  : [LOADER] Failed graphics backends: 0,3,ALL,ALL,ALL,ALL,ALL,ALL
09-06 22:13:19.148  7664  7664 E PPSSPP  : [LOADER] Graphics backend failed for 0, trying another
09-06 22:13:19.148  7664  7664 E PPSSPP  : [LOADER] All graphics backends failed
09-06 22:13:19.148  7664  7664 W PPSSPP  : [LOADER] Failed graphics backend switched from 0 to 3
[new log.txt](https://github.com/hrydgard/ppsspp/files/2357418/new.log.txt)

**Comment by unknownbrackets** [comment]
Thanks - I think I found the bug, #11362 should hopefully fix.

-[Unknown]

**Comment by lim2222** [comment]
Yes ,v1.6.3-428-g8ac50b232 fix this issue,however after 3 to 4 times switching job the problem strike back.
[new new log.txt](https://github.com/hrydgard/ppsspp/files/2359070/new.new.log.txt)

**Comment by unknownbrackets** [comment]
I got it this time, I think - sorry.  #11364.

-[Unknown]
