### ISSUE TITLE
unplayable fps on devices with PowerVR GX6250 when buffered rendering is on

### ISSUE THREAD

**Issue by nex86** [hrydgard/ppsspp#11352]
### What happens?
The Framerate drops to unplayable framerate in several games when Buffered Rendering (1x PSP) is on.
Its fine when I turn Buffered Rendering off but it suffers of some post processing glitches (mostly just blank screens)

Post processing glitches (artifacts) even occur with buffered rendering on after some time.

Games I tried that have the issue so far are Ridge Racer and Ratchet and Clank Size Matters.

### What *should* happen?

Expecting this to run fine without fps drops and glitches, since it does on other devices that even have lower specs than this one.

PPSSPP version : 1.6.3-404-ga004196d4

Accurate device model: GPD XD Plus

Operating system and its version: Android 7.0

Rendering backend used: OpenGL, (Vulkan is even slower)

**Comment by unknownbrackets** [comment]
It would be good to try more games.  Also try "disable slower effects" with buffered rendering enabled.

-[Unknown]

**Comment by marosis** [comment]
Can you try older builds?

**Comment by hrydgard** [comment]
I think this is just terrible drivers/hardware, not much for us to do.
