### ISSUE TITLE
WRC FIA World Rally graphics error in Vulkan (menu)

### ISSUE THREAD

**Issue by Drasikk** [hrydgard/ppsspp#11368]
### What happens?
This game has graphic errors in the menu using Vulkan.

Vulkan: 
![ppsspp_2018-09-08-11-10-40](https://user-images.githubusercontent.com/38067925/45252729-1249f500-b35c-11e8-8cdf-e7c89176cbe1.jpg)

[IMG]http://i68.tinypic.com/209poj6.jpg[/IMG]

Open GL: 
![ppsspp_2018-09-08-11-09-34](https://user-images.githubusercontent.com/38067925/45252734-27bf1f00-b35c-11e8-9320-08ea55243253.jpg)

[IMG]http://i67.tinypic.com/2q31vdw.jpg[/IMG]

### What *should* happen?
Well, what looks good. 

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Samsung Galaxy Note 8 N-950F Samsung Exynos 9 Octa 8895. 8.0.0 Oreo.
PPSSPP v1.6.3-432-gfd6c3145d

**Comment by unknownbrackets** [comment]
Could you try exporting a GE debugger dump on PC?

To do this, open the game and select Debug -> GE debugger..., then when it's displaying the scene, press Record in the top right.  After a second or so, it'll finish and save a trace of the drawing activity.

After that, check the memstick/PSP/SYSTEM/DUMP folder and it'll have created a file named something like "ULES12345_0000.ppdmp".  You can zip that and then drag and drop it into a reply here.

Also - does this happen on any other devices for you?  It could be a driver issue, or it could be a depth issue.

-[Unknown]

**Comment by Drasikk** [comment]
@unknownbrackets I just play it on my mobile.

@leopard20 any.

**Comment by ppmeis** [comment]
It works fine on Windows build:

![image](https://user-images.githubusercontent.com/4381277/45258966-a6e73e00-b3c2-11e8-8c58-48dae25879e8.png)

**Comment by unknownbrackets** [comment]
Hmm, but that grid pattern thing - that's probably not correct, right?

-[Unknown]

**Comment by Drasikk** [comment]
@unknownbrackets is correct this file?

[WRCDUMP.zip](https://github.com/hrydgard/ppsspp/files/3487262/WRCDUMP.zip)

**Comment by unknownbrackets** [comment]
Thanks, that's right.  It's not even a lot of draws, interestingly.

It is rendering from an offset of its own texture in a way that's probably trying to create an effect of like a brighter square panning around?  Or something like that?  This would potentially cause glitches if "disable slower effects" is checked.

-[Unknown]

**Comment by Drasikk** [comment]
It looks like I've found a "partial" solution. When you enter the game you look this way, with mistakes.

![PPSSPP_2019-08-10-19-44-15](https://user-images.githubusercontent.com/38067925/62825141-44388c80-bba7-11e9-8ee5-1cad769dc0d4.jpg)

If you enter the emulator settings and turn on the "rendering resolution" and activate the option to "PSP X2" it looks this way;

![PPSSPP_2019-08-10-20-01-24](https://user-images.githubusercontent.com/38067925/62825283-a98d7d00-bba9-11e9-88ac-a8c7145e3264.jpg)

The problem comes when you leave the emulator and go back in, the error returns. :/

**Comment by Drasikk** [comment]
With Android 9 version, the issue has been fixed.

**Comment by unknownbrackets** [comment]
Okay, I think that makes it pretty clear this was a driver bug...

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, not worth looking into probably.
