### ISSUE TITLE
Android: Chromebook on dev channel Chrome OS v.70.0.3538.7 has display issues

### ISSUE THREAD

**Issue by SoFLazerTag** [hrydgard/ppsspp#11363]
### What happens?

On ChromeOS Dev channel 70.0.3538.7 (possibly other versions?) running any ISO/CSO (that I have tried) either displays black screen, a red gradient horizontal line, or the display is corrupted on in-game graphics.  Movie sequences, such as the intro of God of War CoO, looks normal.  Dropping back to ChromeOS Beta channel on this Chromebook is version 69.0.3497.73, everything mostly works fine again. In game menus are missing and in game text??

### What *should* happen?

The game should display normally.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Acer R11 CB5-132T quad core Chromebook. Chrome OS 70.0.3538.7 is the broken version while 69.0.3497.73 is working mostly normal.  Both tested with PPSSPP 1.6.3 from the Playstore and latest Android build from website 1.6.3-432.

This is an example of GoW:CoO on dev channel

![screenshot 2018-09-06 at 2 37 08 pm](https://user-images.githubusercontent.com/43046948/45217196-d124e880-b268-11e8-9c65-1169469a6edc.png)

This is on Beta channel, should be showing main menu and picking to start a new game.

![image](https://user-images.githubusercontent.com/43046948/45254629-1583b780-b341-11e8-950c-619c3afbff04.png)

![image](https://user-images.githubusercontent.com/43046948/45254637-259b9700-b341-11e8-8c3c-b0ce9dfbc800.png)

**Comment by SoFLazerTag** [comment]
Is there anything I can do or help with to try and get some traction on this reported issue?  I know chromebook users are probably few overall but anything that might help on this I'd be willing to help out.

**Comment by SoFLazerTag** [comment]
The UI does work.  The Android user area on Chromebooks is only 32bit at this time, so I am not able to run Dolphin.  Mupen64Plus FZ works without any perceived issues far as I can tell.  I could not find the cube demo you spoke of so I tried a few homebrew items from the ppsspp download section Cave Story, PSP Flower, and Mega Drops 1 and 2, all same kind of issues.  Either a black screen or some gradient color, though not always just in the center of the screen.  All the games I have tried running I can hear sound and it does seem normal, no skips, crackling, pops, otherwise laggy sounding.

I will look tomorrow at possibly getting the logging. I have not tried doing that yet but I think I can.

**Comment by hrydgard** [comment]
Maybe we get ES 3.0 and we're messing up the global VAO somehow.. or who knows...

**Comment by SoFLazerTag** [comment]
[adb_logcat_capture.txt](https://github.com/hrydgard/ppsspp/files/2411285/adb_logcat_capture.txt)

Here is my logcat I captured while trying to load some games and demos.  Hope it helps in some way.

**Comment by unknownbrackets** [comment]
> Error in shader compilation! 0:2(12): error: extension `GL_EXT_shader_framebuffer_fetch' unsupported in fragment shader

Okay, so that's strange.  What shows under GL extensions in Settings -> Tools -> System information?

The problem is that the extension list had that extension, but it's not letting us create shaders that use it:
https://github.com/hrydgard/ppsspp/blob/f87dcefdd89b72953c6b7172ac3e887d9a7f823b/ext/native/gfx_es2/gpu_features.cpp#L342
https://github.com/hrydgard/ppsspp/blob/e2a9f6acdd74904a4131aa8d7bb620441d2b6729/GPU/GLES/FragmentShaderGeneratorGLES.cpp#L95

According to this:
https://news.softpedia.com/news/mesa-18-1-officially-released-as-the-most-advanced-linux-graphics-stack-series-521215.shtml

GL_EXT_shader_framebuffer_fetch on desktops is a new feature of a recent Mesa, so it's likely this is a bug somewhere in either it exposing that feature incorrectly, or not fully supporting it in fragment shaders.

-[Unknown]

**Comment by SoFLazerTag** [comment]
Interesting, yeah I don't see that string.  Here is what I have

![screenshot 2018-09-24 at 4 39 03 pm](https://user-images.githubusercontent.com/43046948/45980807-a08ad000-c018-11e8-8f7a-8b17694ec125.png)
![screenshot 2018-09-24 at 4 38 55 pm](https://user-images.githubusercontent.com/43046948/45980808-a1236680-c018-11e8-87f1-e22e35d14ce9.png)
![screenshot 2018-09-24 at 4 38 43 pm](https://user-images.githubusercontent.com/43046948/45980809-a1236680-c018-11e8-9e38-ca563e2d86be.png)
![screenshot 2018-09-24 at 4 38 30 pm](https://user-images.githubusercontent.com/43046948/45980810-a1236680-c018-11e8-817e-fa4d552a067d.png)

**Comment by SoFLazerTag** [comment]
Sounds good.  I should close out my bug report on the Chromium site.

Offhand would this same issue, even though it worked better in the previous version, been the cause of why in-games menus in some games would not display properly?  Again a specific game showing that issue would be GoW:CoO.

**Comment by SoFLazerTag** [comment]
Awesome!  Just tried "v1.6.3-504-ge263b3af8" and things are back as they were previously.  Thanks for the work and quick fix.

Menus in some games, such as GoW, still do not display properly and some of the in game help screens.  Should I open that as a different issue or could it possibly be another misdetected GL_EXT ?

or, is there some setting in PPSSPP that could control something like this?

other games such as Exit, and those demos I note above appear to be normal best I can tell.  I could try more to test with however I only own GoW and Exit currently.

**Comment by hrydgard** [comment]
Good to hear that one problem is fixed at least! The other issue is likely to be something completely different, unclear what...

**Comment by unknownbrackets** [comment]
The fix should make all extension names detect properly - so it shouldn't be another misdetected extension name.

I think it'd be best to use a separate issue.  That said - does that happen in v1.6.3 and v1.5.4 as well?

-[Unknown]

**Comment by SoFLazerTag** [comment]
I'll open a new issue for it.  Unable to tell if 1.5.4 behaves the same as I would have to drop back to ChromeOS version 69.  The issue you fixed here with misdetected extensions was an issue with ChromeOS version 70 no matter what PPSSPP version I was using.

thanks again!
