### ISSUE TITLE
No sound after switching headsets

### ISSUE THREAD

**Issue by AlwaysHave** [hrydgard/ppsspp#11367]
### What happens?
I switched my headset from a USB type to one that uses audio jacks and now I have no sounds period. 

### What *should* happen?
Should hear sound.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Windows 10
i7-6700HQ | 960M | 16gb Ram 
v1.6.3-432-gfd6c3145d

**Comment by unknownbrackets** [comment]
I assume you're the person who had this issue on Discord, right?  If not, two people have this issue.

Just some notes from that conversation:
 * Restarting PPSSPP didn't help
 * Changing audio backend didn't help
 * Reinstalling audio drivers didn't help
 * Disabling other Windows audio devices didn't help
 * PPSSPP definitely had sound enabled
 * PPSSPP was not muted in per-app volume settings
 * Affected multiple games

-[Unknown]

**Comment by hrydgard** [comment]
How is this now?

**Comment by ppmeis** [comment]
Tested in latest Windows build. It seems to works fine, tested changing audio output with headphones, TV audi an PC audio.
