### ISSUE TITLE
Some really crazy graphical defects on Linux

### ISSUE THREAD

**Issue by WattanaGaming** [hrydgard/ppsspp#11389]
### What happens?
When playing Colin McRae: Dirt 2 and ToCA Race Driver 2, a really weird graphical defects accur.
In Dirt 2, the car color looks really weird and the polygons and vertices are literally exploding in ToCA Race Driver 2
Sorry but my screenshot tool seems to only capture a gray screen instead of the PPSSPP screen on fullscreen mode

### What *should* happen?
Those things shouldnt happen

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
![screenshot from 2018-09-15 12-57-47](https://user-images.githubusercontent.com/25323231/45583158-f8258f00-b8e6-11e8-9e38-5b35663b5475.png)
PPSSPP version: 1.6.3
NOTE: The GPU is Nvidia GeForce GTX 1050

**Comment by unknownbrackets** [comment]
Are these different problems than #5001?  Can you provide a screenshot?

-[Unknown]

**Comment by marosis** [comment]
No it is duplicate

**Comment by marosis** [comment]
WattanaGaming. Than when you will post something here check forum and look at the compatibility of the game. I will post you it here for you http://forums.ppsspp.org/showthread.php?tid=1473 it is ok. Looks like you are new here.

**Comment by marosis** [comment]
BUT HEY!!! Please reopen it Unknownbrackets. In compatibility is said Colin McRae DiRT 2 is fully playable, but he Is talking about bad graphic colors on car.

**Comment by unknownbrackets** [comment]
They're all related to the same issue:
https://github.com/hrydgard/ppsspp/issues/7026#issuecomment-60517322

It's not Linux specific.

-[Unknown]

**Comment by marosis** [comment]
Ok. Understand
