### ISSUE TITLE
Impossible Mission (EUR

### ISSUE THREAD

**Issue by Slippy2k** [hrydgard/ppsspp#11384]
### What happens?
Impossible mission (EUR version) keeps the game attached and the picture stays black

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Tested with Windows 10 x64
PPSSPP v1.6.3-434
DirectX 11

**Note with OpenGL and DirectX9 the game is running**

**Comment by unknownbrackets** [comment]
Could you try exporting a GE debugger dump on PC?

To do this, open the game and select Debug -> GE debugger..., then when it's displaying the scene, press Record in the top right.  After a second or so, it'll finish and save a trace of the drawing activity.

After that, check the memstick/PSP/SYSTEM/DUMP folder and it'll have created a file named something like "ULES12345_0000.ppdmp".  You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by ppmeis** [comment]
Tested under Windows build, it works fine under DirectX11:

![image](https://user-images.githubusercontent.com/4381277/45575391-a55ebf80-b873-11e8-90b9-23f0ee396577.png)

**Comment by Slippy2k** [comment]
Hello here is my Dump File:
[ULES00764_0001.zip](https://github.com/hrydgard/ppsspp/files/2386007/ULES00764_0001.zip)
I hope you can help me!

**Comment by unknownbrackets** [comment]
Hmm.  Looks fine here on an NVIDIA card in Direct3D 11 with that dump too - I don't see anything too funny, most interesting thing I see is a depth >= 0 test.  What video card are you using?

-[Unknown]

**Comment by Slippy2k** [comment]
I use nVidia GeForce 8400M
other Games work

**Comment by ppmeis** [comment]
Maybe the problem is GF 8000M Series don't support D3D11 according to geforce webpage:

https://www.nvidia.es/page/geforce_8M_techspecs.html

**Comment by Slippy2k** [comment]
But why do other games work with the Directx 11 setting?

**Comment by ppmeis** [comment]
Some DirectX10 rutines are in common with DirectX11, this could be de reason

**Comment by benderscruffy** [comment]
Is this still an issue ??

**Comment by ppmeis** [comment]
Tested in latest build. Seems to work fine in Direct3D11 backend.

**Comment by hrydgard** [comment]
Alright, let's close then.
