### ISSUE TITLE
First cheat line is automatically removed after first edit.

### ISSUE THREAD

**Issue by Trancol** [hrydgard/ppsspp#11398]
### What happens?
1. Open game menu by pressing Esc after launching a game.
2. Edit cheat (I tried with multiple games with no cheats added yet)
3. Copied and paste cheats into the cheat file (Notepad launches by default)
4. Save the file
5. Go back to cheat in the game menu and see that the first cheat (or the only cheat) added is not there.
6. Edit cheat again and the Notepad shows that the first line of the cheat is gone for some reason.
7. Re-add the cheat again and save.
8. First cheat now appears in the game menu

### What *should* happen?
After step 4 above, the first cheat (or all cheats, really) should have been visible after the first save but PPSSPP deletes the first cheat line for some reason.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

PPSSPP Version: v1.6.3-468-gad6938de5
OS: Windows 10 64-bit 1803 (17134.286)
Hardware: Don't think it's relevant.

**Comment by unknownbrackets** [comment]
Is it possible the cheat file has Unicode characters in it, and Notepad is saving it with a byte-order-mark?

You can answer this question by viewing the file with a hex editor, after saving it.  For example, MadEdit.  If the first 3 characters are EF BB BF, then that's probably the issue.

I think the old code that reads the file for the UI editing doesn't handle the BOM.

-[Unknown]

**Comment by Trancol** [comment]
I didn't use MadEdit, but load one of the cheat file on onlinehexeditor.com. 

This is the cheat

`_C0 60 fps
_L 0xE0011420 0x0018C166
_L 0x2018C164 0x10000003
_C0 60 fps [Disable]
_L 0x2018C164 0x14200003`

This is the result

![screenshot_2018-09-18 free online hex editor viewer](https://user-images.githubusercontent.com/22363618/45667838-3f14be00-bb4d-11e8-846a-91d0c1d88cf7.png)

I'll try and share better info if necessary at a later time.

**Comment by Andrew9x** [comment]
Try putting a new line between here:
...
_L 0x2018C164 0x10000003
<here>
_C0 60 fps [Disable]

I remember I had the same issue too, but it was resolved with correct formatting.
