### ISSUE TITLE
Medievil weapon glow

### ISSUE THREAD

**Issue by HotcockMiami** [hrydgard/ppsspp#11408]
PPSSPP v1.6.3

Medievil : Ressurection (Russian version) USUC98620

Windows 10 17134.285
GTX 750 TI
Ryzen 5 2600x

Vulkan

weapon charge always glowing

![buhxwb3hu6e 1](https://user-images.githubusercontent.com/29071437/45864639-4d4c1f80-bd83-11e8-8579-f0076827df43.jpg)

**Comment by unknownbrackets** [comment]
Did it used to work in a previous version, like 1.5.4?  Does it happen on other backends, or only Vulkan?  Does this happen in the [latest git build](https://buildbot.orphis.net/ppsspp/)?

Could you try exporting a GE debugger dump?

To do this, open the game and select Debug -> GE debugger..., then when it's displaying the scene, press Record in the top right.  After a second or so, it'll finish and save a trace of the drawing activity.

After that, check the memstick/PSP/SYSTEM/DUMP folder and it'll have created a file named something like "ULES12345_0000.ppdmp".  You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by SpiffyJUNIOR** [comment]
I'll check this one when I get home.

**Comment by unknownbrackets** [comment]
Updated instructions - this can now be done on more platforms:

https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

-[Unknown]

**Comment by SpiffyJUNIOR** [comment]
PPSSPP v1.7.5-509-g6c9ee0ea5

Medievil : Ressurection (US version) UCUS98620

Windows 10 
GTX 1050 TI Mobile
Intel i5-7300HQ
Vulkan

Fixed. @unknownbrackets close this issue. (Frame dump also attached for those interested)
[recording.zip](https://github.com/hrydgard/ppsspp/files/2922612/recording.zip)

**Comment by unknownbrackets** [comment]
Great to hear, thanks for checking.  There were a lot of changes that may have fixed this.

-[Unknown]
