### ISSUE TITLE
Latest build cannot be opened

### ISSUE THREAD

**Issue by endrare** [hrydgard/ppsspp#11404]

**Comment by endrare** [comment]
Latest build does not work on my phone, I tried to build v1.6.3-483-g1f881d790 but it can't be opened and just returned to the menu, but version v1.6.3-468-gad6938de5 works fine


test on Imo S78
MTK6575 1,9GHZ
PowerVR SGX531
ARMv7 android 2.3

**Comment by AreaScout** [comment]
Can you remove line 41 ``add_compile_options(-mfpu=neon-vfpv4)`` in CMakeLists.txt and rebuild it ?

**Comment by hrydgard** [comment]
Oh, that one is probably not a good idea indeed.

**Comment by AreaScout** [comment]
@hrydgard 

according to https://en.wikipedia.org/wiki/MediaTek it's an 1GHZ single core CPU and according to this https://en.wikipedia.org/wiki/Comparison_of_ARMv7-A_cores all ``Cortex-A9`` CPU's don't support vfpv4

should be change it back to ``-mfpu=neon`` or drop support for it ?

**Comment by hrydgard** [comment]
Not sure we made a decision to require NEON but it's pretty safe nowadays. We dropped support for pre-ARMv7 devices a long time ago, and I only know of one ARMv7 device that doesn't have NEON support, the early Tegra tablet.

**Comment by AreaScout** [comment]
this is what @unknownbrackets did say:

``neon will be faster for sure we can use those for all armv7 only a few processors didn't support neon, and I don't think we care about them anymore``

-vfpv4 was added by me and is supported according to the list on 2013 and later (ARMv7) I think, my two cents on this is -> support on any earlier neon and floating point architecture should be dropped

**Comment by hrydgard** [comment]
Well I still try to keep PPSSPP running on Sony Xperia Play just out of a matter of pride :) And I don't think it support VFPv4.

**Comment by unknownbrackets** [comment]
Is it working now?

-[Unknown]

**Comment by endrare** [comment]
Working but new problem, graphic glitch on gameplay 

here screenshot [url=https://ibb.co/jJaQu9][img]https://thumb.ibb.co/jJaQu9/SC20180922_204913.png[/img][/url]

**Comment by endrare** [comment]
here 
https://ibb.co/jJaQu9

**Comment by AkiraJkr** [comment]
Are you very sure that this is on the latest build? A few builds ago, things were a bit broken, but it was fixed in the actual latest one avaiable right now. Just to make sure.

**Comment by endrare** [comment]
@AkiraJkr

of course I try from v1.6.3-487-g92b857ceb to v1.6.3-497-gead4946fd but the results are the same

**Comment by unknownbrackets** [comment]
Could you try exporting a GE debugger dump on PC?

To do this, open the game and select Debug -> GE debugger..., then when it's displaying the scene, press Record in the top right.  After a second or so, it'll finish and save a trace of the drawing activity.

After that, check the memstick/PSP/SYSTEM/DUMP folder and it'll have created a file named something like "ULES12345_0000.ppdmp".  You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by endrare** [comment]
No I don't have PC

**Comment by endrare** [comment]
@Emulatorer

not just one, I tried the Valkyria Chronicles 3 but only a white screen with normal audio, 
maybe I'll try using gltools

**Comment by Emulatorer** [comment]
See my settings of GLtools #11393 (comment)

**Comment by unknownbrackets** [comment]
Hmm, Valkyria Chronicles 3 is working on a Pixel in GLES, at least.

I wonder if this is not handling nan correctly on w.

-[Unknown]

**Comment by Emulatorer** [comment]
PowerStone Collection suffer the same issue as Valkyria Chronicles 3 and I tried to use Catlog to capture the activity log of ppsspp hope this can help 
[PPSSPP.log](https://github.com/hrydgard/ppsspp/files/2415219/PPSSPP.log)

**Comment by hrydgard** [comment]
That's a straight up compiler error, unfortunately we're not logging enough code to tell where the error is. That I'm gonna fix soon. Is that from the very latest build, unknownbrackets recently fixed a bug?

**Comment by Emulatorer** [comment]
Im currently using build v1.6.3-500-gee62e19c6
Incase you need my ppsspp log while using GLtools GLSL Shaders is on in ppsspp 
[PPSSPPGLtools.log](https://github.com/hrydgard/ppsspp/files/2415324/PPSSPPGLtools.log)

**Comment by unknownbrackets** [comment]
Try the latest git - I found another mistake which is fixed in a newer build.  I wish drivers on the devices I used were less forgiving.

-[Unknown]

**Comment by hrydgard** [comment]
another reason to roundtrip GL shaders through glslang+spirv-opt I guess...

**Comment by endrare** [comment]
latest build are now working well :)
