### ISSUE TITLE
Consider auto-optimizing shaders

### ISSUE THREAD

**Issue by unknownbrackets** [hrydgard/ppsspp#11412]
Potentially, we could do this even on GLES.  Not sure if it would be unsafe in some cases.

I'm not sure what it does, but this suggested an optimization pass helped both Mali-4xx bugs and performance a bit:
https://github.com/hrydgard/ppsspp/pull/11393#issuecomment-423416935

-[Unknown]

**Comment by hrydgard** [comment]
We could also be more careful to generate efficient glsl directly, but yeah, it would be neat to just run all glsl shaders through spirv-opt and back to glsl. Could possibly be beneficial for Vulkan in addition to GLES, although it was kind of implied.

**Comment by ResurrectionRedmi9** [comment]
This is still valid?

**Comment by hrydgard** [comment]
I don't think this is very likely to have a big effect and not gonna get around to it anytime soon. closing.
