### ISSUE TITLE
Monster hunter 3 portable ppsspp version - crash in certain quest with OpenGL 

### ISSUE THREAD

**Issue by Maxzhia** [hrydgard/ppsspp#11410]
Phone: Oppo a3s

I played it smothly with no problems, finish the first part of village quest and now will go to level 2 offline quest. After finishing the first gathering quest i got the problem, everytime i get the level 2 gathering oxffline quest my game crashes and closed out my ppsspp app. Even other online quest like hunting barroth give me a headache, it closes the game where in i need to completely launch ppsspp app.

Whenever I go to rank 2 mission game crashes or if i will fight a barroth monster and when i go to offline village gathering quest 2.
I tried all possible setting but it didn't change anything.
Even downloaded same game it will change but nothing happened.

### What *should* happen?

It should go through and play it.
I should be able to go online quest with other players with no problem.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

PPSSPP 1.6.3
OPPO a3s 
Android version 8.1.0

Heres the sample video:
https://www.youtube.com/watch?v=wMMQw6eBaoQ&t=12s

**Comment by Emulatorer** [comment]
Try to use the latest git build DL here 👇
https://buildbot.orphis.net/ppsspp/

**Comment by Maxzhia** [comment]
I did, issue not resolved.

**Comment by Emulatorer** [comment]
full specifications of your android phone?

**Comment by Maxzhia** [comment]
I am using Oppoa3s
2gb ram
16 gb rom
Android 8.0.1

**Comment by Maxzhia** [comment]
I tried asking my friend to send me his iso game, and copy it in my phone
and the issue is still there. How can i send my save data here?

**Comment by endrare** [comment]
@Maxzhia

You use mh3p not HD iso so you have to use the PAUTH file, or download the mh3p HD version

**Comment by Saramagrean** [comment]
Game crash with OpenGL only, on Vulkan not crash.

**Comment by DivineKi** [comment]
Hey, i'm having the same issue as you 2 years later and I'm wondering of you ver found the solution, i'd really like to know because I really want to play and well I can't with this issue constantly stopping me

**Comment by DivineKi** [comment]
Hey there, I've been having this problem for a while and I may have found the solution. Our issues were either the same or very similar but I'm pretty sure they're the same so the solution is the same. I fixed it by changing my backend rendering from OpenGL to Vulkan, so try that :)

**Comment by Gamemulatorer** [comment]
> Game crash with OpenGL only, on Vulkan not crash.

Savestates of area where this game crash on OGL?

**Comment by LuisMayo** [comment]
To throw a bit of light here
It only happens with OpenGL renderer, Vulkan is fine, it'd be cool to have it fixed since OpenGL renderer is faster at least in my device

The problem is with the desert area of the game. The game will show graphical glitches(like displaced geometry/textures and flickering) the very moment the map loads, and will crash when approaching the quest items box

It has happened to me on PPSSPP 1.10.3 over Android 9 with a Qualcomm Adreno 506 graphical chipset

**Comment by LuisMayo** [comment]
I can provide more info if needed

**Comment by Gamemulatorer** [comment]
> I can provide more info if needed

Could you try exporting a GE frame dump? These help a lot. Just make sure to export it when you see the issue - it's almost like a screenshot. If you make it while the issue isn't happening, it won't help.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

**Comment by LuisMayo** [comment]
> > I can provide more info if needed
> 
> Could you try exporting a GE frame dump? These help a lot. Just make sure to export it when you see the issue - it's almost like a screenshot. If you make it while the issue isn't happening, it won't help.
> 
> See here for instructions - it's not hard and works on Android too:
> https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump
> 
> You can zip that and then drag and drop it into a reply here.

The last day I tested it on multiplayer which allowed me more movement freedom, but in single player it crashes upon entering the mission so it has been harder to take a good shot

Anyway I attach you two zips, I'm fairly confident that, at least in the second file, graphical glitches were happening. Both dumps are very similar anyway and the game crashed almost instantly after taken them since the window of opportunity is not that big
[crashes.zip](https://github.com/hrydgard/ppsspp/files/5398083/crashes.zip)

Regards and thanks for your job

**Comment by Saramagrean** [comment]
PPSSPP v1.10.3-1538-g291f9fdd7 still crash with OpenGL.

Model: Samsung Galaxy A01 (Snapdragon 439, Adreno 505, Android 10)

[ppsspp logcat.zip](https://github.com/hrydgard/ppsspp/files/5792068/ppsspp.logcat.zip)

**Comment by ANR2ME** [comment]
I can't reproduce it on Windows/Geforce's OpenGL, i can enter the mission without issue.
May be it's because i already have the "Harvest Tour : Sandy Plains" mission cleared before? or may be it's specific for mobile GPU (OpenGL ES)?
![image](https://user-images.githubusercontent.com/7974720/104283254-d94d5c80-54e2-11eb-9d8c-ba044ce8d502.png)

**Comment by Saramagrean** [comment]
Yeah, first time before cleared mission. it crash immediately when intro scene video Sandy Plains show up.

Specific Adreno old series (maybe 4xx-5xx only) because I tried device Adreno 665 device it not crash.

**Comment by Saramagrean** [comment]
Happen in MHFU too, crash after access area 5 in Jungle map. (OpenGL only)
![140397282_1666846596821181_7740174107445652345_o](https://user-images.githubusercontent.com/26355472/105571729-fad10280-5d84-11eb-95a3-345ae974f2ff.jpg)

![140005911_1666830353489472_8685914599870946888_o](https://user-images.githubusercontent.com/26355472/105571735-08868800-5d85-11eb-9682-e78830e41b80.jpg)
![139857990_1666830166822824_2709935262230383025_o](https://user-images.githubusercontent.com/26355472/105571739-09b7b500-5d85-11eb-97d1-d366fb6e56cc.jpg)
Cause by driver bug?

**Comment by Gamemulatorer** [comment]
This issue should label as adreno gpu only

**Comment by unknownbrackets** [comment]
If there's a crash that's only happening on Adreno 4xx-5xx and only in OpenGL, it sounds like #11355.

Does the same error get logged?

-[Unknown]

**Comment by Gamemulatorer** [comment]
@Maxzhia no feedback outdated?

**Comment by Gamemulatorer** [comment]
This can be also fix by adding this game to PixelDepthRounding :)

I think it's time to create a compat fix for adreno 3xx and 5xx series opengl bug.

Device: Oppo a3s 3/64 Snapdragon 450 adreno 506.

**Comment by unknownbrackets** [comment]
Maybe the stencil/discard workaround isn't working anymore or isn't enough to avoid this bug.  We probably don't need to actually round in the frag shader, and we don't need to do it ALWAYS.  If it's the issue from before we can do it with less perf impact than that.

-[Unknown]
