### ISSUE TITLE
Not working on some Galaxy Note 9

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#11417]
I'm getting multiple end-user report of PPSSPP not functioning properly on Note 9. 

Should be looked into. I've asked a few for screenshots of the error they get, hopefully there will be some responses.

Unclear if this only applied to the current version on Google Play or also the latest builds.

**Comment by Florin9doi** [comment]
[1.txt](https://github.com/hrydgard/ppsspp/files/2412712/1.txt)
[2.txt](https://github.com/hrydgard/ppsspp/files/2412713/2.txt)
Reproduced with Google Play

**Comment by hrydgard** [comment]
Ugh, no good. But does the latest buildbot build work?

**Comment by Florin9doi** [comment]
![screenshot_20180925-003315_ppsspp](https://user-images.githubusercontent.com/2995486/45980712-67c01a80-c05b-11e8-9826-5311b8da2e4d.jpg)
![screenshot_20180925-003713_ppsspp](https://user-images.githubusercontent.com/2995486/45980713-67c01a80-c05b-11e8-9ccf-b15aa22c1bdc.jpg)
With vulkan, it crashes every time when I jump to the marked location. 
With openGl, it do not crash, but I haven't tested more

**Comment by Florin9doi** [comment]
This should be the latest version

**Comment by hrydgard** [comment]
Huh! That's quite odd, but it might also be a clue to our remaining vulkan bugs.. or it's just a driver bug.

**Comment by Florin9doi** [comment]
Vulkan also crashes every time I change "display resolution (hw scaler)", with no game loaded

**Comment by unknownbrackets** [comment]
I think I saw that happen on Linux recently.

-[Unknown]

**Comment by hrydgard** [comment]
@Florin9doi  Is that a US or International Note 9?  (relevant because they have different GPUs)

**Comment by Florin9doi** [comment]
It's an Exynos 9810/ Mali-G72

**Comment by hrydgard** [comment]
Another reporter also confirmed that it's the International model (Exynos/Mali G72) that is affected.

@themaister Here's an easy-to-repro ARM Vulkan driver crash - just get the latest PPSSPP, install the free homebrew "Cave Story" from the built-in homebrew store, run it, and directly after the intro the scene above happens. Would be really cool if you could take a look...

**Comment by Themaister** [comment]
Is this Note 9 specific? I tried 1.6.3 from Play Store with Cave Story, and it works fine on an S9+ at least. It should be the same chipset and driver stack. Is it possible to repro on an S9+? Is this using the latest OTA update? Don't have a Note 9 handy to test if it's isolated to that.

**Comment by hrydgard** [comment]
@Themaister  It appears to be specific, oddly. I've only gotten reports about these unexplained Vulkan crashes from Note 9 users, and no similar ones from Galaxy 9 users.

**Comment by Themaister** [comment]
Ok, so it seems like the Note 9 has a newer driver stack: https://opengles.gpuinfo.org/displayreport.php?id=2836, r12 rather than r9. I guess there might be a regression somewhere in that case.

**Comment by Themaister** [comment]
We were able to reproduce this on a Note 9, press square button to bring up menu after the intro screen and it crashes.

However, I cannot reproduce this on our driver on a devboard using the same release.

I've pinged Samsung about this issue. In the meantime, I'll probably try to hack the code for some plausible workarounds. I'll let you know if I find anything.

**Comment by Themaister** [comment]
Hi. Finally figured it out, turns out this is an application bug, and not a driver issue.
Here's a patch:

```
diff --git a/ext/native/thin3d/VulkanRenderManager.cpp b/ext/native/thin3d/VulkanRenderManager.cpp
index 9a788b146..6a726afcc 100644
--- a/ext/native/thin3d/VulkanRenderManager.cpp
+++ b/ext/native/thin3d/VulkanRenderManager.cpp
@@ -174,14 +174,6 @@ void VulkanRenderManager::CreateBackbuffers() {
                color_image_view.flags = 0;
                color_image_view.image = sc_buffer.image;
 
-               // Pre-set them to PRESENT_SRC_KHR, as the first thing we do after acquiring
-               // in image to render to will be to transition them away from that.
-               TransitionImageLayout2(cmdInit, sc_buffer.image, 0, 1,
-                       VK_IMAGE_ASPECT_COLOR_BIT,
-                       VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_LAYOUT_PRESENT_SRC_KHR,
-                       VK_PIPELINE_STAGE_ALL_COMMANDS_BIT, VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT,
-                       0, VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT);
-
                res = vkCreateImageView(vulkan_->GetDevice(), &color_image_view, nullptr, &sc_buffer.view);
                swapchainImages_.push_back(sc_buffer);
                assert(res == VK_SUCCESS);
```

The problem is that PPSSPP is for some reason transitioning to PRESENT_SRC_KHR all the images, but those images have not been acquired yet. This is illegal, and the newer drivers are stricter here, causing a VK_DEVICE_LOST on first frame if you're lucky. The Cave Story thing seems to have been a complete red herring (very strange, but hey).

The backbuffer render pass is doing the transition with subpass dependencies anyways, so this is both a fix and an optimization I guess.

After this patch, it works as expected.

**Comment by hrydgard** [comment]
Huh! Thanks for the catch Hans!

Yes, should probably go ahead and report this to the validation layer project. I'll take care of it soon.

**Comment by hrydgard** [comment]
@Themaister   I filed a bug here: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/365

**Comment by unknownbrackets** [comment]
Cool.  I wonder if this is related to the crash we were recently seeing on Intel as a secondary GPU (I think it crashed while creating the swapchain, though...) - will test later.

Thanks for figuring that out.

-[Unknown]
