### ISSUE TITLE
BoF3 frame flicker issue

### ISSUE THREAD

**Issue by Abbanon** [hrydgard/ppsspp#11414]
Issue with Breath of Fire 3's frame flicker starting from Git build v1.5.4-23-g3b7868767 to current.

Has been narrowed down to https://github.com/hrydgard/ppsspp/pull/10213 by Unknown
Submitting this issue for reference.

**Comment by unknownbrackets** [comment]
It waits for vblank start and then seems to set the framebuf immediately.  When it thinks it can flip immediately, it's barely outside the vblank (hcount=13.)

It doesn't seem to draw the wrong frame, but what I don't really get is: it just blits to the two possible display framebufs.  It should never show the wrong content, despite when it flips (even though these timing problems seem incorrect...)

I checked and it's always applying the right diff in the software transform.  Everything in the scene I'm looking at (intro) is a rectangle, so there's no even hardware transform.  I also tried forcing everything dirty, always, etc. so it doesn't seem to be related.

But even the GE debugger does show it offset, even though there's never anything drawn to the frame without the offset...

-[Unknown]

**Comment by hrydgard** [comment]
I'm tempted to just blacklist this game from the latency optimization.... gah.

**Comment by hrydgard** [comment]
Hm, that sounds reasonable, although yeah, still odd.

**Comment by hrydgard** [comment]
Fixed enough to be closed, I think...
