### ISSUE TITLE
gradle 3.2 fails sync very quickly

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#11420]
Tried to update the android build to the latest gradle version, but it fails very quickly with little in the way of error messages. Needs investigation.

    build.gradle:
    classpath 'com.android.tools.build:gradle:3.2.0'

Want to use the new "App Bundles" feature to reduce the download size from Google Play, so this is important.

**Comment by unknownbrackets** [comment]
Should be fixed by #11434, right?  Closing.

-[Unknown]
