### ISSUE TITLE
Android: Chromebook - Beta channel Chrome OS v.70.0.3538.22 - display issues

### ISSUE THREAD

**Issue by SoFLazerTag** [hrydgard/ppsspp#11423]
### What happens?
GoW:CoO doesn't display menus or help tips in game.

### What *should* happen?
Should display these items normally

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Acer R11 Chromebook (Intel N3150 CPU (Braswell) has N3000 GPU aka Intel HD Graphics 400).  Currently on Chrome OS 70.0.3588.22 that has Android 7.1.1.  PPSSPP version ppsspp-v1.6.3-504-ge263b3af8-android

Here are samples of what it looks like just starting a game from the main menu and then the first hint as the game begins following the opening cutscene.

![screenshot 2018-09-25 at 1 38 27 pm](https://user-images.githubusercontent.com/43046948/46035939-e5227400-c0c9-11e8-8bf2-739e5b1ccfdf.png)

![screenshot 2018-09-25 at 1 38 45 pm](https://user-images.githubusercontent.com/43046948/46035938-e489dd80-c0c9-11e8-8d03-87567b59cd9b.png)

![screenshot 2018-09-25 at 1 39 37 pm](https://user-images.githubusercontent.com/43046948/46035937-e489dd80-c0c9-11e8-94f2-3188e3fdb7d5.png)

**Comment by unknownbrackets** [comment]
It might help to see another adb logcat, in case something else is failing.

If you set the rendering mode to "skip buffer effects" does it change anything?  What about disabling "simulate block transfer"?

Normally, you want both of those on, just trying to determine if they aren't working right here.

-[Unknown]

**Comment by SoFLazerTag** [comment]
I made log output for PPSSPP with the normal setup for this game and then with each setting disabled individually and then both disabled.  All are attached.

I think the only thing I noticed was a difference in overall speed of the game and when fast forwarding but nothing related to the emulation of the games graphics.

[adb_logcat_PPSSPP_.txt](https://github.com/hrydgard/ppsspp/files/2419488/adb_logcat_PPSSPP_.txt)
[adb_logcat_PPSSPP_SkipBufferEffects_off.txt](https://github.com/hrydgard/ppsspp/files/2419487/adb_logcat_PPSSPP_SkipBufferEffects_off.txt)
[adb_logcat_PPSSPP_SimulateBlockTransfer_off.txt](https://github.com/hrydgard/ppsspp/files/2419486/adb_logcat_PPSSPP_SimulateBlockTransfer_off.txt)
[adb_logcat_PPSSPP_SkipBufferEffects_and_SimulateBlockTransfer_off.txt](https://github.com/hrydgard/ppsspp/files/2419485/adb_logcat_PPSSPP_SkipBufferEffects_and_SimulateBlockTransfer_off.txt)

**Comment by unknownbrackets** [comment]
There are messages indicating that your disc is corrupt:

```
[LOADER] block 742848: inflate : invalid distance too far back[-3]
[LOADER] Inflate frame 740688: failed - invalid stored block lengths[-3]
[LOADER] Inflate frame 740697: block size error 2 != 2048
[LOADER] block 740734: inflate : invalid stored block lengths[-3]
```

I would guess the images for the missing UI elements are in the corrupt parts of the disc image.

-[Unknown]

**Comment by SoFLazerTag** [comment]
I had no clue a CSO image file could still function in any capacity if it was corrupt at all.  I had copied this from my NAS to a memory cards months ago.  While the one on my NAS works fine from Windows when I played through Steam Link or using Gamestream I hadn't ever considered something was wrong with the CSO image I was toting around on my Chromebook.

Replacing the image with one that isn't corrupt solved it as you thought.

I am so sorry for troubling you about this one.  :/

![screenshot 2018-09-26 at 9 40 55 am](https://user-images.githubusercontent.com/43046948/46087961-01c5b700-c171-11e8-9cba-4bc3a30f9050.png)
![screenshot 2018-09-26 at 9 41 10 am](https://user-images.githubusercontent.com/43046948/46087960-01c5b700-c171-11e8-8404-5af16c92ac21.png)
![screenshot 2018-09-26 at 9 41 57 am](https://user-images.githubusercontent.com/43046948/46087959-012d2080-c171-11e8-8d46-902b091f8469.png)


Thank you again!

**Comment by SoFLazerTag** [comment]
Is there any app that can verify CSO files or is it best to simply check the PPSSPP logging? (now that I know what those lines mean)

again my humble gratitude for your awesome help!

**Comment by hrydgard** [comment]
@unknownbrackets  it should be possible to detect truncated CSO at least by comparing the file size to the header data, right? As for regular ISO it might require traversing the file system.

Then there are of course other forms of corruption than truncation...

**Comment by unknownbrackets** [comment]
We should probably surface that there were deflate errors to the user somehow too.  Right now they have no way of knowing (as highlighted here.)  Although, if bad compatibility had been reported via the UI, the reporting server should've responded indicating that the crc was likely invalid (based on other positive reports with different crcs)...

But yeah, simple truncation is the easiest to detect and probably the most common type.  For an ISO, I guess we could also look at the path table assuming it's actually valid all the time.  Safest would be to traverse indeed...

Anyhow - to verify files, you could use [`maxcso`](https://github.com/unknownbrackets/maxcso), simply `maxcso --crc file.cso`.  If it's truncated, it'll say "Unable to read entire sector" at some point, and otherwise it should return the deflate error if there's corruption in the middle.

-[Unknown]
