### ISSUE TITLE
Riviera Missing Attack Effects

### ISSUE THREAD

**Issue by TideGear** [hrydgard/ppsspp#11431]
I'm playing Riviera on a Samsung Galaxy S9+ (USA) with v1.6.3-514-gbb5b981ef. I've noticed the effects that are supposed to appear during attacks are missing. This still happens on default settings. Any ideas?

**Comment by unknownbrackets** [comment]
Can you give a screenshot or video clip of what they should look like?

Does this only not happen using mobile or even doesn't happen on desktop?  OpenGL and Vulkan both?

It'd help to describe which effect specifically.

-[Unknown]

**Comment by TideGear** [comment]
@unknownbrackets I just tested v1.6.3-521-g4fbeec1e5 on both PC and Android. On Android, the effects don't appear on either Vulkan or OpenGL. However, on PC, they do appear! Here's a savestate...

[Riviera Attack Effects Only on PC.zip](https://github.com/hrydgard/ppsspp/files/2432978/Riviera.Attack.Effects.Only.on.PC.zip)

Hit X to attack and you'll see burst and slash effects on PC. They won't appear on Android.

**Comment by hrydgard** [comment]
Seems likely that it's one of the effects that require dual source blending though, which generally isn't available on mobile - it's an old feature but has its uses.

Probably need to get around to finally implement a multi-pass solution for those effects...

**Comment by TideGear** [comment]
Why isn't it available on mobile? It'd be great if you could find a way. The attacks are pretty lifeless at the moment.

**Comment by hrydgard** [comment]
It's just not supported by mobile GL and Vulkan drivers, for some reason. It is possible to work around it with some rather gnarly coding, haven't gotten around to it yet.

That said I don't know for sure that this is the cause here. It could be.

**Comment by hrydgard** [comment]
It's just not supported by mobile GL and Vulkan drivers, for some reason. It is possible to work around it with some rather gnarly coding, haven't gotten around to it yet.

That said I don't know for sure that this is the cause here. It could be.

**Comment by unknownbrackets** [comment]
Ah, so just the first battle?  Effects seem to work fine on my Pixel with OpenGL or Vulkan.

Some relevant settings:

 * Buffered rendering
 * Simulate block transfer
 * Hardware transform
 * Software skinning
 * Vertex cache off
 * Lazy texture caching off
 * Disable slower effects off

The S9+ in the Americas uses a newer Snapdragon than my Pixel, but they should be fairly similar.  I didn't see any difference in the effect on desktop when I disabled dual source blending.

-[Unknown]

**Comment by TideGear** [comment]
@unknownbrackets Not just the first battle. The options you listed are already set, since they are default. Should I try changing them?

**Comment by unknownbrackets** [comment]
Hmm, if they're already set like that I'm not sure why it's acting differently for you.

Just to confirm - no effects happen at all during an attack?

https://youtu.be/68DlYcb-Ivs?t=10m25s

So here, for example:

 * Einherjar - the green slash effect
 * Hound - bite animation
 * Lorelai - sparks and then red strike effect

None of these are showing for you, right?

-[Unknown]

**Comment by TideGear** [comment]
@unknownbrackets That is correct. Anything I can provide you with to help figure this out?

**Comment by unknownbrackets** [comment]
It might help to double check your disc - just to make sure there's no disc corruption.  Maybe something went wrong when copying it to the Android device.  If you're using remote disc streaming, try clearing the PPSSPP's app cache (long press on the icon in your launcher.)

If that doesn't help, it'd be useful to see an `adb logcat`.  That requires getting `adb` from here:
https://developer.android.com/studio/releases/platform-tools

Then enable developer mode per this page (build 7 times):
https://developer.android.com/studio/command-line/adb

To use `adb logcat`:

1. Extract the platform-tools zip somewhere.
2. Plug your phone into your PC via USB.
3. Open a command prompt (Start -> command prompt.)
4. Drag the "adb" program from the extracted zip into the command prompt.  You'll see something like:

   ```
   C:\Users\Me>"C:\Users\Me\Downloads\platform-tools_r28.0.1-windows\platform-tools\adb.exe"
   ```

5. Keep typing after that, starting with a space (you can copy and paste this, just make sure you get the space): ` logcat > "%USERPROFILE%\Desktop\ppsspp.log"`
6. Now press enter.  Your device might show a message asking you to confirm debugging.  Go ahead and allow.
7. Now just reproduce the problem on your device.  Make sure not to unplug the USB cord.
8. Once you're done, go back to that command prompt window and press Ctrl-C.  It should go back to a new line like `C:\Users\Me>`.
9. There should be a file named "ppsspp.log" on your desktop.  Zip it up, and attach it here.

-[Unknown]

**Comment by TideGear** [comment]
Here's the log...
[ppsspp.zip](https://github.com/hrydgard/ppsspp/files/2445114/ppsspp.zip)
...It's worth mentioning that, for this log, I used a savestate to load right into a battle, but this bug happens whether or not I use a savestate.

**Comment by TideGear** [comment]
@unknownbrackets Have a chance to check out the log?

**Comment by unknownbrackets** [comment]
Unfortunately, the log doesn't really show any errors - I was hoping it would.  And my device is Adreno too...

-[Unknown]

**Comment by unknownbrackets** [comment]
I wonder if this is related to the Adreno workaround, which we recently found applied differently to newer/older Adreno devices.  Has anything changed here by chance?

-[Unknown]

**Comment by TideGear** [comment]
@unknownbrackets I just tried my savestate on v1.7.5-374-g8aea19434 with default settings and both OpenGL and Vulkan. Still no effects. Is there a setting I should try?

**Comment by Gamemulatorer** [comment]
Why this issue still open if it's confirmed a driver bug?

**Comment by Gamemulatorer** [comment]
@TideGear no feedback/outdated

**Comment by hrydgard** [comment]
Probably won't do anything more here, let's hope the driver bugs are fixed.
