### ISSUE TITLE
Rockman Dash 2 - Music Issues

### ISSUE THREAD

**Issue by JMC47** [hrydgard/ppsspp#11442]
### What happens?

During certain music tracks, particularly during the Kimotoma Caverns (Fire Ruin) Pillar Attack and Bon Bonne chase, music becomes incredibly broken.  It sounds like it loads the sounds for the start of the race minigame and instruments can get stuck.

Some of the other music sounds a bit off, but that could just be a shoddy port job.

I clipped a video of the issue, but, my reaction to it included a naughty word so be warned.

https://clips.twitch.tv/AgileEnticingCobraPeteZaroll

### What *should* happen?

I'm assuming the music shouldn't be that messed up.  While I haven't played this game on PSP in years, the people within the Mega Man Legends speedrunning community had no idea what was going on when it happened.

If required I can ask one of them to record how it plays on console or I can figure out how to hook up my PSP to my computer.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

I'm using PPSSPP v1.6.3 - Windows 10, GTX 1070,

**Comment by unknownbrackets** [comment]
Seems like something got hung playing indeed.

Can you save a log (if you download a git build, there's a DebugLog.bat file that you can just run)?  Ideally, going right to that from in game save.

-[Unknown]

**Comment by JMC47** [comment]
Here's the log... the issue is currently happening (for about 10 - 20 seconds?) when I stop emulation.

[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/2445345/ppsspplog.zip)

**Comment by unknownbrackets** [comment]
Hm, it looks like this is loading unencrypted sceAtrac and other modules (we blacklisted them anyway, but this is unusual.)  Can you double check that you're using an unpatched disc?  It looks like this may have a patch to run on CFW.

It's using both sceSas and sceAtrac, but I'm guessing it's probably SAS.

ffffe048=sceSasGetEndFlag(08d8af00)

It uses VAG samples (no Atrac or PCM in the SAS mixing), sometimes using odd pitch values.

The only error I see is this:
W[FILESYS]: FileSystems\ISOFileSystem.cpp:518 Reading beyond end of file, clamping size 131072 to 38784

I suppose it's possible the ISO file is truncated.  Might help to double check its crc.

-[Unknown]

**Comment by unknownbrackets** [comment]
I'm guessing it's an SAS or ADSR bug then.  We used to have issues there in spades a long time ago, but I thought they were all solved.

Interesting that it sounds different.

If you're able to compile PPSSPP, I'd suggest a couple things worth trying:

1. Remove these lines: https://github.com/hrydgard/ppsspp/blob/289928a17020cd11cdd22fdb2b262db00d969ad8/Core/HW/SasAudio.cpp#L552-L555 - this should make all SAS effects silent.  If the sound still happens, I'm wrong and it's not SAS at all.

2. Remove this line (if it is SAS): https://github.com/hrydgard/ppsspp/blob/289928a17020cd11cdd22fdb2b262db00d969ad8/Core/HW/SasAudio.cpp#L617 - this will disable reverb effects, which can confirm if this is somehow caused by reverb.

If it is SAS, but not reverb, then I suspect ADSR, but that might be more complicated to eliminate.

-[Unknown]

**Comment by JMC47** [comment]
First change removes almost all the audio.  Second change doesn't fix the issue.

**Comment by JMC47** [comment]
Changing line 896 of SasAudio.cpp to 

WalkCurve(PSP_SAS_ADSR_CURVE_MODE_LINEAR_DECREASE, sustainRate * 2);

Suppresses the issue.

**Comment by unknownbrackets** [comment]
The unique ADSR simple values are:

```
0005, 043c -> sustainType=LINEAR_INCREASE sustainRate=29360128, sustainLevel = 402653184 (37.5%)
00ff, 1fc0 -> sustainType=LINEAR_INCREASE sustainRate=0, sustainLevel = ENVELOPE_HEIGHT_MAX (100%)
80ff, 1fc0 -> sustainType=LINEAR_INCREASE sustainRate=0, sustainLevel = ENVELOPE_HEIGHT_MAX (100%)
80ff, 500b -> sustainType=LINEAR_DECREASE sustainRate=7168, sustainLevel = ENVELOPE_HEIGHT_MAX (100%)
80ff, 5fc7 -> sustainType=LINEAR_DECREASE sustainRate=0, sustainLevel = ENVELOPE_HEIGHT_MAX (100%)
80ff, 5fc9 -> sustainType=LINEAR_DECREASE sustainRate=0, sustainLevel = ENVELOPE_HEIGHT_MAX (100%)
80ff, 5fcd -> sustainType=LINEAR_DECREASE sustainRate=0, sustainLevel = ENVELOPE_HEIGHT_MAX (100%)
afff, 5fce -> sustainType=LINEAR_DECREASE sustainRate=0, sustainLevel = ENVELOPE_HEIGHT_MAX (100%)
```

The first one seems a bit suspect, but it could be an issue with any of the 0s, really - if they're never being manually keyed off.

We cold try to be more surgical and find if one of these configurations is misbehaving:

```c++
if (sustainType == PSP_SAS_ADSR_CURVE_MODE_LINEAR_INCREASE) {
   WalkCurve(PSP_SAS_ADSR_CURVE_MODE_LINEAR_DECREASE, sustainRate);
} else {
   WalkCurve(sustainType, sustainRate);
}
```

Although, we did validate that sustain does do increases...

-[Unknown]

**Comment by unknownbrackets** [comment]
It does seem like increase should increase for sustain (at least per PSP's SAS emulation), at least so far.  Need to test more.

That said, there is one glitch I did find - `if (height_ < sustainLevel)` should be `if (height_ <= sustainLevel)`.  Tests show this pretty clearly so far.  It's possible this could have a small effect to music instruments, but doesn't explain the whine.

-[Unknown]

**Comment by unknownbrackets** [comment]
I doubt they'll help this issue, but try these changes:

https://github.com/hrydgard/ppsspp/compare/master...unknownbrackets:sas-adsr?expand=1

I think the max isn't needed, just wanting to check if it helps.

-[Unknown]

**Comment by JMC47** [comment]
When I click that link it takes me to make a Pull Request instead of letting me see the code

**Comment by JMC47** [comment]
This is frustrating, but I was watching a speedrun last night and someone else ran into this sound issue (on a different music track, but same issue.)

I asked them and they were running on console... which makes me wonder if this is just possible to happen.

**Comment by unknownbrackets** [comment]
I'm usually not a fan of hacks, but I wonder if an option in settings like "Simulate PS1 ADSR".

When on, we would just prevent increase for sustain, I think.  I wonder if it would improve FF Tactics and others too...

-[Unknown]

**Comment by hrydgard** [comment]
Adding ever more obscure options does not seems like an appealing way to go, given what it means for translations and so on... This seems more like a task for compat.ini, assuming no ill effects are found in these games, even if it's a bit ugly semantically.

**Comment by unknownbrackets** [comment]
Well, that's fair yes.

```c++
if (sustainType == PSP_SAS_ADSR_CURVE_MODE_LINEAR_INCREASE) {
   WalkCurve(PSP_SAS_ADSR_CURVE_MODE_LINEAR_DECREASE, sustainRate);
} else {
   WalkCurve(sustainType, sustainRate);
}
```

This still makes it sound fine, right?

-[Unknown]

**Comment by JMC47** [comment]
This fixes the extremely broken effects from showing up.  The music isn't as good as on PS1 regardless, but, I don't think that's under your control.

**Comment by benderscruffy** [comment]
Please close as this has not been updated in years
