### ISSUE TITLE
Rockman Dash 2 - OpenGL Minimap Issues

### ISSUE THREAD

**Issue by JMC47** [hrydgard/ppsspp#11444]
### What happens?

Whenever a minimap is scrolling on screen, you can see the uncropped minimap as it scrolls into place.  This can be more/less damaging depending on the size of the minimap.

OpenGL

![openglminimapload](https://user-images.githubusercontent.com/6598209/46460759-f125ca00-c78a-11e8-808b-d7385deec46d.gif)

### What *should* happen?

By using Vulkan or D3D11, you can get a better idea that this isn't supposed to happen.

Vulkan

![vulkanminimapload](https://user-images.githubusercontent.com/6598209/46460779-04d13080-c78b-11e8-9c5a-42786b95632f.gif)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Test performed on a Core i7-6700K, GTX 1070 on Windows 10.  Tested both 1.6.3 stable and 1.6.3 - 536

**Comment by unknownbrackets** [comment]
Could you try exporting a GE debugger dump on PC? Ideally, capturing it while it is uncropped.

To do this, open the game and select Debug -> "GE debugger...".  Next, get ready to press "Step Frame".  Then start the transition (it helps if you're using a controller), and quickly press "Step Frame".

If you caught it early enough, you should see a still of the issue.  Then press Record in the top right of the GE Debugger, and then Resume.  After a second or so, it'll finish and save a trace of the drawing activity.

After that, check the memstick/PSP/SYSTEM/DUMP folder and it'll have created a file named something like "ULES12345_0000.ppdmp".  You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by JMC47** [comment]
I included a dump (the first one) from Vulkan and the rest from OpenGL.  It appears to be the same issue.

[DUMP.zip](https://github.com/hrydgard/ppsspp/files/2447513/DUMP.zip)

**Comment by hrydgard** [comment]
Hm. I wonder if there's a possibility of negative scissor coordinates that we need to clamp. 

Looking at the equations in GPUStateUtils.cpp though, seems the only way that could handle would be if renderX went negative, which would mean gstate_c.curRTOffsetX went negative. Which I don't quite see how it could happen, but I wouldn't rule it out completely...

**Comment by JMC47** [comment]
I'd be willing to test anything.  Note: this bug doesn't seem to happen in D3D?  Though the first few frames of the minimap scrolling on don't seem to appear at all.  I can get a rendering of this from PSTV if it'd help.

**Comment by unknownbrackets** [comment]
It looks ugly because it draws at 640x240 (ew)...

Importantly, the minimap is drawn on that.  The textures for the minimap:

dump 1 - 0x08a35300 (scissor 816,25 - 959,95 on a 960x240 surface)
dump 2 - 0x08a350b0 (scissor 24,24 - 167,95 on a 640x240 surface)
dump 3 - 0x08a35270 (scissor 976,25 - 95,95 on a 640x240 surface)
dump 4 - 0x08a35270 (scissor 16,24 - 159,95 on a 640x240 surface)

Most of the drawing happens with scissor set to 0,0 - 639,239.  So that rules out the high bit being a negative bit, IMHO.

The framebuffer stride is 1024, so I think the question really is - what happens when the scissor x1 is greater than the scissor x2?

-[Unknown]

**Comment by hrydgard** [comment]
So the hardware register sets up a backward rectangle, it's not just our coordinate conversion that's broken on the way somewhere? Yes, that would need hardware testing indeed...

**Comment by unknownbrackets** [comment]
Tested, #11510 makes it simply skip draws for backwards rectangles, which both makes sense and matches tests.  Expecting that to fix this.

I had been worried it should flip or treat values with the 0x300 bit as negative or something, knowing the weirdnesses of the PSP GE...

-[Unknown]

**Comment by unknownbrackets** [comment]
Is this working now?

**Comment by JMC47** [comment]
Last time I did a run on OpenGL I didn't notice any issues.  I haven't tested Vulkan/D3D yet though, been busy.

**Comment by hrydgard** [comment]
I think we can assume that it's fixed, given what we know. Please re-open if that isn't the case.
