### ISSUE TITLE
No sound what so ever

### ISSUE THREAD

**Issue by RazedandRisen** [hrydgard/ppsspp#11440]
Hi, 

This is my first time using openemu. I installed version 2.0.6.1 on my mac book pro (early 2013, macOS Sierra) and my first game is Castlevania Dracula X Chronicles for PSP.

From the intro all the way to the game play there is no sound what so ever. The volume is turned on my computer and in the game as well. 

I've restarted my compute as well, that had no effect.

Not sure what to do now.

**Comment by LunaMoo** [comment]
First thing to do would be reporting to the openemu project or trying ppsspp, as it stands this doesn't seem related to ppsspp at all so I'm going to close it.
