### ISSUE TITLE
PPSSPP Corrupted in FullScreen Mode (Vulkan+Nvidia DSR)

### ISSUE THREAD

**Issue by Combone** [hrydgard/ppsspp#11457]
### What happens?

I updated PPSSPP for Latest version and show this..

https://imgur.com/Yzv09hN

Other problem,. Trying exit, emulator Freeze (FullScreen only).

Note: i put windowed because my Win7 failed Screenshots in FullScreen games.

### What *should* happen?

I use Nvidia DSR FullScreen. Drivers is 411.70 (Latest).

Without DSR work normal.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

PC, Windows 7 x64, GPU Nvidia.

**Comment by hrydgard** [comment]
Wow, that looks quite bizarre... Thanks for reporting.

Did this not happen in earlier versions?

**Comment by Combone** [comment]
> 
> 
> Wow, that looks quite bizarre... Thanks for reporting.
> 
> Did this not happen in earlier versions?

Versions of a few days ago, No.

I look Development Builds and tested PPSSPP v1.6.3-559-g5a224d7a2, problem persists.

**Comment by hrydgard** [comment]
It would be very helpful if you could find the first build that has this problem for you.

**Comment by Combone** [comment]
> 
> 
> It would be very helpful if you could find the first build that has this problem for you.

I need Remember first.

**Comment by Combone** [comment]
Hi hrydgard 

I make Downgrade in my Nvidia Driver. Version 399.24 don't have issue.

All Fonts works perfectly and emulator close without crash. Tested in PPSSPP v1.6.3-599.

**Comment by hrydgard** [comment]
OK, seems like a driver bug then, or a bug of ours that interacts with some driver difference. I'll look into it or report is as appropriate, soon.

**Comment by unknownbrackets** [comment]
Does this still happen with the latest drivers?

-[Unknown]

**Comment by Combone** [comment]
Sorry for Delay.

Tested Latest Nvidia Driver >> 417.71.

- Continue corrupted and Crash after Exit emulator.

https://imgur.com/z9DcFnJ

**Comment by Combone** [comment]
> 
> 
> Does this still happen with the latest drivers?
> 
> -[Unknown]

Sorry for Delay.

Tested Latest Nvidia Driver >> 417.71.

    Continue corrupted and Freeze after Exit emulator.

https://imgur.com/z9DcFnJ

I use Resolution 2560x2048 for FullScreen and cause this issue.

Tested 1280x720/1280x1024 and fonts work perfect in FullScreen.

**Comment by hrydgard** [comment]
Hi, is this still an issue with the latest PPSSPP build and with the latest NV driver? I did a fix related to swapchain size which might have helped, plus you never know with drivers...

**Comment by Combone** [comment]
> 
> 
> Hi, is this still an issue with the latest PPSSPP build and with the latest NV driver? I did a fix related to swapchain size which might have helped, plus you never know with drivers...

Hi Henrik :)

Tested latest Nvidia Drivers and bug persists (FullScreen only).
Windowed is Ok. My PPSSPP start ever in FullScreen (2560x2048). I use program called, "Res-o-matic" for change automatically Resolution.

Create shortcut with new Resolution, find software here: http://www.bcheck.net/apps/reso.htm

Resolutions above 1280x1024 cause this issue.

**Comment by hrydgard** [comment]
Does this still happen on the latest drivers? I do believe this is a driver bug.

**Comment by ppmeis** [comment]
Tested with latest build. With DSR activated at 4K resolution, seems to work just fine:

![image](https://user-images.githubusercontent.com/4381277/110170937-38e92980-7dfb-11eb-9bad-72e03318787c.png)

![image](https://user-images.githubusercontent.com/4381277/110171043-5ddd9c80-7dfb-11eb-8c7d-c462f6abf757.png)

**Comment by hrydgard** [comment]
Whether it's drivers or PPSSPP that fixed it, that looks promising. I'll close, reopen if it reappears.
