### ISSUE TITLE
Why and how can I fix "Postprocessing filter" off/not available

### ISSUE THREAD

**Issue by MirceaMx** [hrydgard/ppsspp#11458]
Os: Archlinux (Artix-runit), DE: KDE Plasma
PPSSPP version: PPSSPP-qt 1.6.3
GPU: Intel integrated ( [Intel® HD Graphics 4400](https://ark.intel.com/products/81018/Intel-Core-i3-4030U-Processor-3M-Cache-1-90-GHz-) )

### What happens?
Postprocessing filter is off, cannot select other option / options
Used to have it available on other (Linux) OS'es but  here is off / not available

### What *should* happen?
Postprocessing filter should be available

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Os: Archlinux (Artix-runit) - Desktop, DE: KDE Plasma
PPSSPP version: PPSSPP-qt 1.6.3
GPU: Intel integrated ( [Intel® HD Graphics 4400](https://ark.intel.com/products/81018/Intel-Core-i3-4030U-Processor-3M-Cache-1-90-GHz-) )

**Comment by unknownbrackets** [comment]
Does it work using the SDL port instead of the Qt port?

-[Unknown]

**Comment by MirceaMx** [comment]
> SDL port

How can I test that. Sorry for the long time for the answer I was out, barely came home. In any case, should I just install the standard version or what?

**Comment by unknownbrackets** [comment]
This should've been fixed in v1.7.0 iirc (and in dev builds before that.)  It was fixed in #11162.

-[Unknown]
