### ISSUE TITLE
Rockman Dash 2: Shadows Improperly Render Underwater

### ISSUE THREAD

**Issue by JMC47** [hrydgard/ppsspp#11456]
### What happens?

Underwaters have some kind of wave effect across the screen.  For some reason it causes the shadows to malfunction.

![image](https://user-images.githubusercontent.com/6598209/46597256-67893b80-caad-11e8-9b26-f3f4d39e36b4.png)

This seems to happen regardless of backend.

### What *should* happen?

According to runners shadows should render normally in the underwater areas.  I can grab footage of the stream going up to the area in question.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

PPSSPP v1.6.3-536, but also happens in 1.6.3 stable.  Tested on a Core i7-6700K, GTX 1070 on Windows 10.

**Comment by hrydgard** [comment]
If it happens in a GE frame dump, one would be useful.

**Comment by JMC47** [comment]
[ULJM05037_0005.zip](https://github.com/hrydgard/ppsspp/files/2455261/ULJM05037_0005.zip)

I don't know if it's apparent, but the distortion effect moves things up and down on the screen.  When stuff is distorted far enough up/down, the shadows break.  In the middle the shadows look fine.  So, it's really weird looking.

**Comment by JMC47** [comment]
I tested this on PSP and it appears to be a game bug.

**Comment by hrydgard** [comment]
Thanks for confirming that! :)
