### ISSUE TITLE
Recent Choppy frame rate Ridge Racer

### ISSUE THREAD

**Issue by jcgamer60** [hrydgard/ppsspp#11468]
Ios 12
Latest ppsspp build from iemulators
iPhone 6
Ridge Racer

I was able to get this game running practically full speed with IR interpreter and automatic frameskip 1. 

I once went to test out a setting in the ppsspp menu and the game suddenly started to become choppy at times. I resetted the ppsspp settings to default and tried frameskip 1 again but it is still choppy. I even tried deleting ppsspp and reinstalling and I have the same issue. 

I am a bit puzzled why I am having this issue since it was working perfectly before. I even rebooted my iPhone. Any help would be appreciated

**Comment by unknownbrackets** [comment]
Unfortunately, this is probably just temperature throttling of the device.  It may have gotten warmer internally, so to avoid internal damage and harm your hands, it slows down to cool off.  All phones do this, and it's outside PPSSPP's control.

It may temporarily get better if you let your phone cool down for a while.

-[Unknown]

**Comment by unknownbrackets** [comment]
We're always trying to make PPSSPP faster, although we're somewhat limited on iOS devices due to Apple restrictions.

Closing as per the note above.

-[Unknown]
