### ISSUE TITLE
PPSSPP won't recognize PSP as a controller (FuSa Gamepad)

### ISSUE THREAD

**Issue by ShiroAKA707** [hrydgard/ppsspp#11460]
### What happens?
I launch PPSSPP and head to control mapping in order to check if it recognizes my PSP (connected via FuSa Gamepad) as a controller. It doesn't seem to recognize any button presses. The FuSa program worked just fine for stuff like Rocket League and some other Steam games. I can see the controller being recognized in my control panel device list and I can see controller signals on http://html5gamepad.com/

### What *should* happen?
PPSSPP should be able to recognize the PSP as a controller of all things, I mean, its meant to emulate that. 

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

CPU: Intel Core i7 860
GPU: Nvidia GeForce GTX 660
RAM: 8GB 
OS: Windows 10 64-bit 

I have the latest version downloaded, 1.6.3

**Comment by LunaMoo** [comment]
PPSSPP is in no way entitled to support PSP as controller, quite the opposite it's design overall from UI and graphics to controls via full / comfortable gamepads is to enhance the experience beyond what PSP offered.

 I can guess through that this Fusa gamepad most likely works as a generic Dinput gamepad. PPSSPP can only use one dinput gamepad and it has to be set as default controller in windows, if you don't set it like that, I guess it would not be detected.

**Comment by ShiroAKA707** [comment]
It is the only controller connected though, and since so many controllers are supported, I don't see why this wouldn't work.

**Comment by unknownbrackets** [comment]
It's working fine for me on Windows 10 with a PSP-3000.  It registers the buttons without issue, and then they work fine.  It also shows up in test analogs.

Note: I did start PPSSPP *after* starting FuSa Gamepad.  Currently, PPSSPP doesn't support plugging in a DirectInput controller after launch.

-[Unknown]

**Comment by unknownbrackets** [comment]
If you try the latest git build, it will detect this even if plugged in after PPSSPP is started.

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other problems, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same software, just create a new issue instead.

-[Unknown]
