### ISSUE TITLE
Not support Android P

### ISSUE THREAD

**Issue by Lzhiyong** [hrydgard/ppsspp#11462]
Ppsspp always crashes on Android P，does it support Android P？

**Comment by hrydgard** [comment]
It's not supposed to crash on Android P. What device do you have? If it's a Galaxy Note 9 or similar, it's a known bug which is fixed in the latest builds and the fix will be in 1.7.0, coming soon.

**Comment by Lzhiyong** [comment]
My device is Xiaomi 6

**Comment by Lzhiyong** [comment]
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/sagit/sagit:8.0.0/OPR1.170623.027/V9.2.3.0.OCAMIEK:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 32269, tid: 32299, name: Thread-2  >>> org.ppsspp.ppssppgold <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: 'NativeApp.cpp:694 (NativeInitGraphics): [colorPipeline] Assertion failed!'
    x0  0000000000000000  x1  0000000000007e2b  x2  0000000000000006  x3  0000000000000008
    x4  0000000000000080  x5  0000000000000080  x6  0000000000000080  x7  8000000000000000
    x8  0000000000000083  x9  0000007532bb99a8  x10 fffffff87ffffbdf  x11 0000000000000001
    x12 0000007492ffde70  x13 0000000000000000  x14 ffffffffffffffff  x15 0000007492ffdbd8
    x16 0000007532bf22c8  x17 0000007532b30288  x18 0000007492ffd65a  x19 0000000000007e0d
    x20 0000000000007e2b  x21 0000000000000083  x22 000000749736ab59  x23 00000074b064f600
    x24 0000000000000003  x25 0000007497732b70  x26 00000074965c3ca0  x27 00000074965c3d40
    x28 0000000000000010  x29 0000007492ffdd90
    sp  0000007492ffdd50  lr  0000007532b24a90  pc  0000007532b24abc

backtrace:
    #00 pc 0000000000021abc  /system/lib64/libc.so (abort+124)
    #01 pc 00000000000080f8  /system/lib64/liblog.so (__android_log_assert+296)
    #02 pc 00000000005621c8  /data/app/org.ppsspp.ppssppgold-lWSdvgQa9CYAm4XWadzdHw==/lib/arm64/libppsspp_jni.so (AndroidAssertLog(char const*, char const*, int, char const*, char const*, ...)+164)
    #03 pc 000000000056e0f0  /data/app/org.ppsspp.ppssppgold-lWSdvgQa9CYAm4XWadzdHw==/lib/arm64/libppsspp_jni.so (NativeInitGraphics(GraphicsContext*)+1272)
    #04 pc 0000000000569a54  /data/app/org.ppsspp.ppssppgold-lWSdvgQa9CYAm4XWadzdHw==/lib/arm64/libppsspp_jni.so (Java_org_ppsspp_ppsspp_NativeActivity_runEGLRenderLoop+336)
    #05 pc 00000000000021b8  /data/app/org.ppsspp.ppssppgold-lWSdvgQa9CYAm4XWadzdHw==/oat/arm64/base.odex (offset 0x2000) (org.ppsspp.ppsspp.NativeActivity.runEGLRenderLoop+152)
    #06 pc 000000000055c988  /system/lib64/libart.so (art_quick_invoke_stub+584)
    #07 pc 00000000000cf740  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
    #08 pc 00000000002823b0  /system/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+344)
    #09 pc 000000000027c36c  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+948)
    #10 pc 000000000052f428  /system/lib64/libart.so (MterpInvokeVirtualQuick+584)
    #11 pc 0000000000552e14  /system/lib64/libart.so (ExecuteMterpImpl+29972)
    #12 pc 00000000000079b4  /data/app/org.ppsspp.ppssppgold-lWSdvgQa9CYAm4XWadzdHw==/oat/arm64/base.vdex (org.ppsspp.ppsspp.NativeActivity$1.run+76)
    #13 pc 0000000000255e68  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.2146680767+496)
    #14 pc 000000000051cb18  /system/lib64/libart.so (artQuickToInterpreterBridge+1032)
    #15 pc 0000000000565afc  /system/lib64/libart.so (art_quick_to_interpreter_bridge+92)
    #16 pc 000000000025cfc8  /system/framework/arm64/boot.oat (offset 0x114000) (java.lang.Thread.run+72)
    #17 pc 000000000055c988  /system/lib64/libart.so (art_quick_invoke_stub+584)
    #18 pc 00000000000cf740  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
    #19 pc 00000000004633b8  /system/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
    #20 pc 0000000000464480  /system/lib64/libart.so (art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue*)+424)
    #21 pc 000000000048f7f0  /system/lib64/libart.so (art::Thread::CreateCallback(void*)+1120)
    #22 pc 00000000000830c4  /system/lib64/libc.so (__pthread_start(void*)+36)
    #23 pc 00000000000233bc  /system/lib64/libc.so (__start_thread+68)

stack:
         0000007492ffdcd0  0000007492ffdd78  <anonymous:0000007492efc000>
         0000007492ffdcd8  0000000000000000
         0000007492ffdce0  0000007492ffdd40  <anonymous:0000007492efc000>
         0000007492ffdce8  0000006424e564dc  /system/bin/app_process64 (sigprocmask64+124)
         0000007492ffdcf0  0000007492ffdd90  <anonymous:0000007492efc000>
         0000007492ffdcf8  00000075345cec08  /system/lib64/liblog.so (__android_log_buf_write+288)
         0000007492ffdd00  0000000700000000
         0000007492ffdd08  753186873f9e8186
         0000007492ffdd10  00000074b064f600  [anon:libc_malloc]
         0000007492ffdd18  00000074b064f600  [anon:libc_malloc]
         0000007492ffdd20  000000749736ab59  /data/app/org.ppsspp.ppssppgold-lWSdvgQa9CYAm4XWadzdHw==/lib/arm64/libppsspp_jni.so
         0000007492ffdd28  000000749736abd0  /data/app/org.ppsspp.ppssppgold-lWSdvgQa9CYAm4XWadzdHw==/lib/arm64/libppsspp_jni.so
         0000007492ffdd30  0000000000007e2b
         0000007492ffdd38  0000000000007e0d
         0000007492ffdd40  0000007492ffdd90  <anonymous:0000007492efc000>
         0000007492ffdd48  0000007532b24a90  /system/lib64/libc.so (abort+80)
    #00  0000007492ffdd50  000000000000004a
         ........  ........
    #01  0000007492ffdda0  0000007492ffe7b0  <anonymous:0000007492efc000>
         ........  ........
    #02  0000007492ffe2b0  288056365bbc9dad
         ........  ........
    #03  0000007492ffe7b0  0000007492ffe810  <anonymous:0000007492efc000>
         ........  ........
    #04  0000007492ffe8c0  0000000000000000
         ........  ........
    #05  0000007492ffe920  00000074aa848b68  /dev/ashmem/dalvik-LinearAlloc (deleted)
         ........  ........
    #06  0000007492ffe9f0  0000000000000000
         ........  ........
    #07  0000007492ffea80  0000000014a76dc8  /dev/ashmem/dalvik-main space (region space) (deleted)
         ........  ........
    #08  0000007492ffeb10  0000007492ffed90  <anonymous:0000007492efc000>
         ........  ........
    #09  0000007492ffeba0  0000007492ffee40  <anonymous:0000007492efc000>
         ........  ........
    #10  0000007492ffecc0  0000007492ffed20  <anonymous:0000007492efc000>
         ........  ........
    #11  0000007492ffed30  0000007492fff588  <anonymous:0000007492efc000>
         ........  ........
    #12  0000007492ffed80  0000000000000000
         ........  ........
    #13  0000007492ffed80  0000000000000000
         ........  ........
    #14  0000007492ffee40  0000000000000000
         ........  ........
    #15  0000007492ffefd0  0000000070d0f9c8  /data/dalvik-cache/arm64/system@framework@boot.art
         ........  ........
    #16  0000007492fff0b0  0000000070c989c0  /data/dalvik-cache/arm64/system@framework@boot.art
         ........  ........
    #17  0000007492fff0e0  0000000000000000
         ........  ........
    #18  0000007492fff170  0000000000000000
         ........  ........
    #19  0000007492fff200  0000007492fff3c0  <anonymous:0000007492efc000>
         ........  ........
    #20  0000007492fff310  0000000000000000
         ........  ........
    #21  0000007492fff3d0  0000000000000000
         ........  ........
    #22  0000007492fff4a0  0000007532b860a0  /system/lib64/libc.so (_ZL15__pthread_startPv)
         ........  ........
    #23  0000007492fff4c0  000000753617a548  <anonymous:000000753617a000>
         0000007492fff4c8  0000000000000000
         0000007492fff4d0  000000753617a5e0  <anonymous:000000753617a000>
         0000007492fff4d8  000000753617a5f0  <anonymous:000000753617a000>
         0000007492fff4e0  0000000000000000
         0000007492fff4e8  0000000000000000
         0000007492fff4f0  000000749547e4f0  <anonymous:0000007495382000>
         0000007492fff4f8  0000007492ef94f0  <anonymous:0000007492dfe000>
         0000007492fff500  00000000ffffffff
         0000007492fff508  0000007f00000001
         0000007492fff510  0000007492efa000  [anon:thread stack guard]
         0000007492fff518  00000000001054f0
         0000007492fff520  0000000000001000
         0000007492fff528  0000000000000000
         0000007492fff530  00000074b0614c00  [anon:libc_malloc]
         0000007492fff538  0000007fd2a9e3a8  [stack]

**Comment by Lzhiyong** [comment]
OK , I'll try it again

**Comment by hrydgard** [comment]
Now that's an odd crash.. Would not expect it to get that far if Vulkan wasn't working, and since it seems to work, really wouldn't expect that pipeline to fail building.... hm.

**Comment by Lzhiyong** [comment]
I have downloaded the latest version from https://buildbot.orphis.net/ppsspp/, now it works fine.
Thanks!

**Comment by unknownbrackets** [comment]
Oh, that's great.  Maybe it was the same issue as the Galaxy Note 9.  I'll close.

-[Unknown]
