### ISSUE TITLE
snd0.at3 doesnt respect it's loop points

### ISSUE THREAD

**Issue by Kitsu-neechan** [hrydgard/ppsspp#11466]
since we're starting, might aswell report this too.

i've done quite a wide array of hacks to psp games over the years and using a custom snd0.at3 is a pretty standard feature in hacks i've released.

i noticed that the snd0.at3 that plays on ppsspp simply wholeloops the file, instead of actually reading it's loop point. not really a big deal but this behavior does differ from hardware, so a bug report it is.

**Comment by unknownbrackets** [comment]
Do you have a few examples of games that use loop points for reference?

-[Unknown]

**Comment by Kitsu-neechan** [comment]
retail games, no.
like i said, i do custom ones for some hack works that i've done over the years (as do other people), 
and those all work on hardware, but ppsspp just wholeloops the file.

i can send you example files if needed for this, but as far as i know, retail games tend to just
wholeloop their audio files in general.
