### ISSUE TITLE
Standalone psp player for linux?

### ISSUE THREAD

**Issue by InfamousKnight** [hrydgard/ppsspp#11474]
There's a tool on linux called libtas which doesn't support standard gui layouts, but supports sdl and opengl which ppsspp 1.6.3. So we would need a standalone player to test tasing with it. Have a text file to read a game path. Maybe a text file for configuration(I believe this already exist, just pointing out).

So in a linux only package, could you provide a standalone player for testing?

**Comment by hrydgard** [comment]
Sorry, I don't understand what you're asking? PPSSPPSDL is as standalone as it goes.

**Comment by InfamousKnight** [comment]
Okay. I’ll test it out today. Thank you
