### ISSUE TITLE
[Andriod] Games on vulkan not rendering properly 1.6.3

### ISSUE THREAD

**Issue by mickprash** [hrydgard/ppsspp#11471]
### What happens?
Switching the emulator to vulkan often lead to games not rendering properly. Switching to open gl often fixed the issue but not always. Test Drive unlimited runs at incredibly sluggish frame rates on vulkan. Motorstorm gets stuck on supplementary information screen. Other games tested include; Midnight club La remix, Pursuit force, and Naruto Ultimate Ninja Heroes (all of which don't render properly).

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Samsung Galaxy s9 Snapdragon Variant.

**Comment by unknownbrackets** [comment]
Does this happen in the latest git build?  There are a bunch of changes.

Unfortunately, we're seeing some driver bugs on Adreno / Snapdragon devices both in Vulkan (#10421) and GLES (#11355).  I don't know if they're causing these specific issues, though.

It's hard to even guess anything without screenshots and descriptions of the specific problems.

-[Unknown]

**Comment by hrydgard** [comment]
Gonna close this one in favor of more specific issues.
