### ISSUE TITLE
New to PPSSPP and having issues with Test Drive Unlimited on android 8.0

### ISSUE THREAD

**Issue by TheFrogdamnRock** [hrydgard/ppsspp#11478]
Hi. I'm new to ppsspp and Test Drive Unlimited is extremely slow. (I'm on android) My device is Samsung Galaxy A8+ 2018. I found this cheat to fix it but i dont know how to make it a cheat db file.
Cheat below

_S NPJH-50443
_G Final Fantasy Type 0 UMD1
_C0 Remove blur from cutscenes
_L 0xE0010006 0x0032D0B8
_L 0x2032D0B8 0x00002021
_C0 Remove blur from cutscenes [Disable]
_L 0xE0012021 0x0032D0B8
_L 0x2032D0B8 0x34040006
_S NPJH-50444
_G Final Fantasy Type 0 UMD2
_C0 Remove blur from cutscenes
_L 0xE0010006 0x0032D0B8
_L 0x2032D0B8 0x00002021
_C0 Remove blur from cutscenes [Disable]
_L 0xE0012021 0x0032D0B8
_L 0x2032D0B8 0x34040006
_S ULUS-10094
_G Me & My Katamari
_C0 Skip glitch
_L 0xE0010000 0x0008CE7C
_L 0x2008CE7C 0x00001821
_C0 Skip glitch [Disable]
_L 0xE0011821 0x0008CE7C
_L 0x2008CE7C 0x90830000
_S NPJH-50050
_G Macross Ultimate Frontier
_C0 Requires restart
_C0 Geometry bug workaround
_L 0xE00800E4 0x0001EED4
_L 0x2001EED0 0x0A200004
_L 0x2001EED4 0x00000000
_L 0x20000010 0x15200003
_L 0x20000014 0x00000000
_L 0x20000018 0x0A207BB6
_L 0x2000001C 0x00000000
_L 0x20000020 0x0A207BB7
_L 0x20000024 0xDD0600E4
_S ULJS-00321
_G Macross Triangle Frontier
_C0 Requires restart
_C0 Geometry bug workaround
_L 0xE00800E4 0x0001ABA8
_L 0x2001ABA4 0x0A200004
_L 0x2001ABA8 0x00000000
_L 0x20000010 0x15200003
_L 0x20000014 0x00000000
_L 0x20000018 0x0A206AEB
_L 0x2000001C 0x00000000
_L 0x20000020 0x0A206AEC
_L 0x20000024 0xDD0600E4
_S ULJS-00281
_G Gundam Assault Survive
_C0 Requires restart
_C0 Geometry bug workaround
_L 0xE00800E4 0x0001F1BC
_L 0x2001F1B8 0x0A200004
_L 0x2001F1BC 0x00000000
_L 0x20000010 0x15200003
_L 0x20000014 0x00000000
_L 0x20000018 0x0A207C70
_L 0x2000001C 0x00000000
_L 0x20000020 0x0A207C71
_L 0x20000024 0xDD0600E4
_S NPJH-50720
_G Battle Robot Damashii
_C0 Requires restart
_C0 Geometry bug workaround
_L 0xE00800E4 0x0001EEE8
_L 0x2001EEE4 0x0A200004
_L 0x2001EEE8 0x00000000
_L 0x20000010 0x15200003
_L 0x20000014 0x00000000
_L 0x20000018 0x0A207BBB
_L 0x2000001C 0x00000000
_L 0x20000020 0x0A207BBC
_L 0x20000024 0xDD0600E4
_S UCJS-10085
_G Bleach: Soul Carnival
_C0 Hang Workaround
_L 0xE0010003 0x001C6CB4
_L 0x201C6CB4 0x34070001
_C0 Hang Workaround [Disable]
_L 0xE0010001 0x001C6CB4
_L 0x201C6CB4 0x28A70003
_S UCJS-10106
_G Bleach: Soul Carnival 2
_C0 Hang Workaround
_L 0xE0010003 0x002A43D8
_L 0x202A43D8 0x34070001
_C0 Hang Workaround [Disable]
_L 0xE0010001 0x002A43D8
_L 0x202A43D8 0x28A70003
_S UCAS-40297
_G Bleach: Soul Carnival 2
_C0 Hang Workaround
_L 0xE0010003 0x002A4AE4
_L 0x202A4AE4 0x34070001
_C0 Hang Workaround [Disable]
_L 0xE0010001 0x002A4AE4
_L 0x202A4AE4 0x28A70003
_S NPUH-10023
_G Armored Core 3 Portable
_C0 Hang Workaround
_L 0xE0010003 0x002258E8
_L 0x202258E8 0x34070001
_C0 Hang Workaround [Disable]
_L 0xE0010001 0x002258E8
_L 0x202258E8 0x28A70003
_S NPUH-10024
_G Armored Core: Last Raven Portable
_C0 Hang Workaround
_L 0xE0010003 0x002BB274
_L 0x202BB274 0x34070001
_C0 Hang Workaround [Disable]
_L 0xE0010001 0x002BB274
_L 0x202BB274 0x28A70003
_S NPUH-10025
_G Armored Core: Silent Line Portable
_C0 Hang Workaround
_L 0xE0010003 0x00248884
_L 0x20248884 0x34070001
_C0 Hang Workaround [Disable]
_L 0xE0010001 0x00248884
_L 0x20248884 0x28A70003
_S NPUH-10069
_G Auditorium
_C0 Black screen workaround
_L 0xE0010228 0x0002E3D4
_L 0x2002E3D4 0x10000228
_S ULES-00622
_G Sonic Rivals
_C0 Use with slow effects disabled
_C0 Requires restart
_C0 Graphic Workaround
_L 0xE003FFFF 0x0012AA00
_L 0x2012AA00 0x0000C821
_L 0x2012AA04 0x2442FF88
_L 0x2000BA58 0x00005021
_S ULES-00940
_G Sonic Rivals 2
_C0 Use with slow effects disabled
_C0 Requires restart
_C0 Graphic Workaround
_L 0xE003FFFF 0x00169084
_L 0x20169084 0x0000C821
_L 0x20169088 0x2442FF88
_L 0x2000BCD0 0x00005021
_S ULES-00640
_G Activision Hits Remixed
_C0 Use with slow effects disabled
_C0 Requires restart
_C0 Graphics workaround
_L 0xE001FFFF 0x00010334
_L 0x20010334 0x0000C821
_C0 You can use multithreading instead
_C0 Freeze Workaround
_L 0XE0060001 0x0000F9EC
_L 0x2000F9EC 0x00005821
_L 0x2000FC5C 0x00002821
_L 0x2000F968 0x00000000
_L 0x2000FBB4 0x00000000
_L 0x2000FAE4 0x00000000
_L 0x2000FAC8 0x00000000
_S ULJM-05167
_G Ore no Dungeon
_C0 Hide Glitch
_L 0xE0070010 0x0004317C
_L 0x2004317C 0x0A200400
_L 0x20001000 0x3407FF00
_L 0x20001004 0x00E4382A
_L 0x20001008 0x54E00001
_L 0x2000100C 0x34040000
_L 0x20001010 0x0A210C61
_L 0x20001014 0x94A70010
_C0 Hide Glitch [Disable]
_L 0xE0010400 0x0004317C
_L 0x2004317C 0x94A70010
_S ULJM-05404
_G Hokuto no Ken: Raoh Gaiden - Ten no Haoh
_C0 Depth Workaround
_L 0xE0040054 0x0001164C
_L 0x2001164C 0x0A200800
_L 0x20002000 0x3C1B3F78
_L 0x20002004 0x0A204595
_L 0x20002008 0x449B6800
_C0 Depth Workaround [Disable]
_L 0xE0010800 0x0001164C
_L 0x2001164C 0xC48D0054
_S ULJS-00191
_G Zettai Zetsumei Toshi 3
_C0 Freeze workaround
_L 0xE0012AFA 0x00039300
_L 0x20039300 0x00000000
_C0 Freeze workaround [Disable]
_L 0xE0010000 0x00039300
_L 0x20039300 0x0E2F2AFA
_S NPEH-00154
_G Carnage Heart EXA
_C0 UI offset fix
_L 0xE00C2021 0x001EBF3C
_L 0x201EBF3C 0x34040800
_L 0x201390A4 0x34040800
_L 0x20379280 0x0E200800
_L 0x20002000 0x3C1B3ECD
_L 0x20002004 0x277BCCCD
_L 0x20002008 0x4411A800
_L 0x2000200C 0x563B0002
_L 0x20002010 0x3C1BBFD3
_L 0x20002014 0x3C1BBEFE
_L 0x20002018 0x03E00008
_L 0x2000201C 0x00000000
_L 0x203792D8 0xACDB0030
_C0 UI offset fix [Disable]
_L 0xE0040800 0x001EBF3C
_L 0x201EBF3C 0x00862021
_L 0x201390A4 0x00862021
_L 0x20379280 0x46152C40
_L 0x203792D8 0xE4D10030
_S ULES-00850
_G Final Fantasy Tactics: The War of the Lions
_C0 Battle animation lag fix
_L 0xE0030004 0x0020EF80
_L 0x2020EF80 0x24050002
_L 0x2020EF90 0x24050003
_L 0x2020EF9C 0x24050002
_C0 Battle animation lag fix [Disable]
_L 0xE0030002 0x0020EF80
_L 0x2020EF80 0x24050004
_L 0x2020EF90 0x24050002
_L 0x2020EF9C 0x24050003
_C0 Original resolution
_L 0xE00DA2E2 0x00035780
_L 0x20035780 0x879EA2E4
_L 0x20035784 0x0E200800
_L 0x20002000 0x341001E0
_L 0x20002004 0x121E0007
_L 0x20002008 0x8790A2E2
_L 0x2000200C 0x34130046
_L 0x20002010 0x34120010
_L 0x20002014 0x34160154
_L 0x20002018 0x341700F0
_L 0x2000201C 0x341E0154
_L 0x20002020 0x341500F0
_L 0x20002024 0x03E00008
_L 0x20002028 0x00000000
_C0 Original resolution [Disable]
_L 0xE002A2E4 0x00035780
_L 0x20035780 0x8790A2E2
_L 0x20035784 0x879EA2E4
_S ULUS-10515
_G Valkyria Chronicles II
_C0 Black Sky Fix
_L 0xE004002D 0x004884B8
_L 0x204884B8 0x0A200580
_L 0x20001600 0x254AFFFF
_L 0x20001604 0x0A322130
_L 0x20001608 0x98CB002D
_C0 Black Sky Fix [Disable]
_L 0xE0010580 0x004884B8
_L 0x204884B8 0x98CB002D
_S ULJM-05957
_G Senjou no Valkyria 3 E2
_C0 Black Sky Fix
_L 0xE004002D 0x004721C0
_L 0x204721C0 0x0A200580
_L 0x20001600 0x254AFFFF
_L 0x20001604 0x0A31C872
_L 0x20001608 0x98CB002D
_C0 Black Sky Fix [Disable]
_L 0xE0010580 0x004721C0
_L 0x204721C0 0x98CB002D
_S ULJM-05781
_G Senjou no Valkyria 3 E2 (English patch uses wrong ID!)
_C0 Black Sky Fix
_L 0xE004002D 0x004721C0
_L 0x204721C0 0x0A200580
_L 0x20001600 0x254AFFFF
_L 0x20001604 0x0A31C872
_L 0x20001608 0x98CB002D
_C0 Black Sky Fix [Disable]
_L 0xE0010580 0x004721C0
_L 0x204721C0 0x98CB002D
_S ULJM-05842
_G San Goku Shi IX with Power-Up Kit
_C0 Disable Depth Test
_L 0xE0010005 0x00009B80
_L 0x20009B80 0x34040008
_C0 Disable Depth Test [Disable]
_L 0xE0010008 0x00009B80
_L 0x20009B80 0x34040005
_S ULUS-10509
_G Metal Gear Solid: Peace Walker
_C0 Recruit discovery
_L 0xE03B18C4 0x007EF070
_L 0x207EF070 0x34020008
_L 0x207EF078 0x00000000
_L 0x20001200 0x3C1B0880
_L 0x20001204 0xAF7F11E8
_L 0x20001208 0x0E40E1AA
_L 0x2000120C 0x276411F0
_L 0x20001210 0x936811FC
_L 0x20001214 0x34099069
_L 0x20001218 0x01090018
_L 0x2000121C 0x00005012
_L 0x20001220 0xA36A11EC
_L 0x20001224 0x34090019
_L 0x20001228 0x0109001A
_L 0x2000122C 0x00005812
_L 0x20001230 0x8F7F11E8
_L 0x20001234 0x03E00008
_L 0x20001238 0xA36B11ED
_L 0x207EF0C8 0x0E200494
_L 0x20001250 0x3C1B0880
_L 0x20001254 0xAF65124C
_L 0x20001258 0xAF7F1248
_L 0x2000125C 0x0E200480
_L 0x20001260 0x00000000
_L 0x20001264 0x8F7F1248
_L 0x20001268 0x8F65124C
_L 0x2000126C 0x34090001
_L 0x20001270 0x00093080
_L 0x20001274 0x00A63821
_L 0x20001278 0x012B602A
_L 0x2000127C 0x25290001
_L 0x20001280 0x5580FFFB
_L 0x20001284 0xACE7FFFC
_L 0x20001288 0x03E00008
_L 0x2000128C 0x00001021
_L 0x207EF14C 0x0E2004C0
_L 0x20001300 0x3C1B0880
_L 0x20001304 0xAF6612FC
_L 0x20001308 0xAF7F12F8
_L 0x2000130C 0x936211ED
_L 0x20001310 0x00424021
_L 0x20001314 0x00481021
_L 0x20001318 0x24420002
_L 0x2000131C 0xAF6212F4
_L 0x20001320 0x0E200480
_L 0x20001324 0x00000000
_L 0x20001328 0x8F6212F4
_L 0x2000132C 0x2442FFFF
_L 0x20001330 0x8F6612FC
_L 0x20001334 0xA0CA0000
_L 0x20001338 0x24C60001
_L 0x2000133C 0x1C40FFF7
_L 0x20001340 0xAF6612FC
_L 0x20001344 0x8F7F12F8
_L 0x20001348 0x03E00008
_L 0x2000134C 0x00001021
_L 0x207EF168 0x0E2004C0
_L 0x207EF184 0x0E2004C0
_L 0x207EF1B8 0x0E2004C0
_L 0x207EF238 0x0E2004C0
_C0 Recruit discovery [Disable]
_L 0xE0080008 0x007EF070
_L 0x207EF070 0x7C0218C4
_L 0x207EF078 0x0E40E1A6
_L 0x207EF0C8 0x0E40E1A8
_L 0x207EF14C 0x0E40E1A4
_L 0x207EF168 0x0E40E1A4
_L 0x207EF184 0x0E40E1A4
_L 0x207EF1B8 0x0E40E1A4
_L 0x207EF238 0x0E40E1A4
_S ULES-01367
_G Assassin's Creed: Bloodlines
_C0 PS3 Connectivity
_L 0xE00D0005 0x000F6628
_L 0x200F6628 0x00000000
_L 0x2001A700 0x00000000
_L 0x2001A57C 0x00000000
_L 0x2001A658 0x00000000
_L 0x2001A590 0x0A200803
_L 0x2000200C 0x80850002
_L 0x20002010 0x341B0002
_L 0x20002014 0x0365D82A
_L 0x20002018 0x53600001
_L 0x2000201C 0x24A5003E
_L 0x20002020 0xA0850002
_L 0x20002024 0x0A206966
_L 0x20002028 0x80850000
_C0 PS3 Connectivity [Disable]
_L 0xE0050000 0x000F6628
_L 0x200F6628 0x04810005
_L 0x2001A700 0x14C4000F
_L 0x2001A57C 0x14850030
_L 0x2001A658 0x10400003
_L 0x2001A590 0x80850000
_C0 Synchronize Save
_L 0xE0020006 0x000A7B5C
_L 0x200A7B5C 0x00000000
_L 0x200A7B70 0x10000003
_C0 Synchronize Save [Disable]
_L 0xE0020000 0x000A7B5C
_L 0x200A7B5C 0x14850006
_L 0x200A7B70 0x10850003
_S UCUS-98751
_G Patapon 3
_C0 Allow saving over newer save
_L 0xE0011212 0x00223C46
_L 0x20223C44 0x1000000B
_C0 Allow saving over newer save [Disable]
_L 0xE0011000 0x00223C46
_L 0x20223C44 0x1212000B
_S ULES-00318
_G Monster Hunter Freedom
_C0 Synchronize save
_L 0xE00308EC 0x0009F288
_L 0x2009F288 0x00C31821
_L 0x2009F28C 0x8C65FFF8
_L 0x2009F2A4 0x8C64FFFC
_C0 Synchronize save[disable]
_L 0xE0031821 0x0009F288
_L 0x2009F288 0x8C8508EC
_L 0x2009F28C 0x00C31821
_L 0x2009F2A4 0x8C8408F0
_S ULUS-10084
_G Monster Hunter Freedom
_C0 Synchronize save
_L 0xE00308EC 0x0009E65C
_L 0x2009E65C 0x00C31821
_L 0x2009E660 0x8C65FFF8
_L 0x2009E678 0x8C64FFFC
_C0 Synchronize save[disable]
_L 0xE0031821 0x0009E65C
_L 0x2009E65C 0x8C8508EC
_L 0x2009E660 0x00C31821
_L 0x2009E678 0x8C8408F0
_S ULES-01213
_G Monster Hunter Freedom Unite
_C0 Synchronize save
_L 0xE0030980 0x000C055C
_L 0x200C055C 0x00C31821
_L 0x200C0560 0x8C65A0E0
_L 0x200C0578 0x8C64A0E4
_C0 Synchronize save[disable]
_L 0xE0031821 0x000C055C
_L 0x200C055C 0x8C850980
_L 0x200C0560 0x00C31821
_L 0x200C0578 0x8C840984
_S ULJM-05500
_G Monster Hunter Portable 2nd G
_C0 Synchronize save
_L 0xE0030980 0x000C2EB0
_L 0x200C2EB0 0x00C31821
_L 0x200C2EB4 0x8C65A0E0
_L 0x200C2ECC 0x8C64A0E4
_C0 Synchronize save[disable]
_L 0xE0031821 0x000C2EB0
_L 0x200C2EB0 0x8C850980
_L 0x200C2EB4 0x00C31821
_L 0x200C2ECC 0x8C840984
_S ULJM-05800
_G Monster Hunter Portable 3rd
_C0 Synchronize save
_L 0xE0031460 0x0008CC40
_L 0x2008CC40 0x00822021
_L 0x2008CC44 0x8C850FE0
_L 0x2008CC68 0x8C830FE4
_C0 Synchronize save[disable]
_L 0xE0032021 0x0008CC40
_L 0x2008CC40 0x8CC51460
_L 0x2008CC44 0x00822021
_L 0x2008CC68 0x8CC31464
_S NPJB-40001
_G Monster Hunter Portable 3rd HD Ver.
_C0 Synchronize save
_L 0xE0031460 0x0008DE88
_L 0x2008DE88 0x00822021
_L 0x2008DE8C 0x8C850FE0
_L 0x2008DEB0 0x8C830FE4
_C0 Synchronize save[disable]
_L 0xE0032021 0x0008DE88
_L 0x2008DE88 0x8CC51460
_L 0x2008DE8C 0x00822021
_L 0x2008DEB0 0x8CC31464
_S ULES-00841
_G Castlevania: The Dracula X Chronicles
_C0 Requires restart and display size - full
_C0 Symphony of the Night original res
_L 0xE0100001 0x0010000C
_L 0xE00F0100 0x1011D8CC
_L 0x2011D8CC 0x24100100
_L 0x2011D75C 0x24030100
_L 0x2011D768 0x240300D0
_L 0x2011E764 0x240401E0
_L 0x2011E768 0x24050110
_L 0x2010330C 0x0A200800
_L 0x20002000 0x341B01E0
_L 0x20002004 0x15FB0005
_L 0x2000200C 0x147B0003
_L 0x20002014 0x00001821
_L 0x20002018 0x00007821
_L 0x2000201C 0x0A240CC5
_L 0x20002020 0xAF0C0004
_L 0x201143C0 0x24110100
_L 0x201143C4 0x241000D0
_C0 Symphony of the Night full screen
_L 0xE0060001 0x0010000C
_L 0xE00501E0 0x1011D8CC
_L 0x2011D8CC 0x241001E0
_L 0x2011EDD8 0x240201E0
_L 0x2011ED5C 0x00000000
_L 0x2011D75C 0x240301E0
_L 0x201143C0 0x241101E0
_C0 Symphony of the Night restore resolution
_L 0xE0090001 0x0010000C
_L 0x2011D8CC 0x241001A2
_L 0x2011EDD8 0x240201A2
_L 0x2011ED5C 0x10200005
_L 0x2011D75C 0x2403016A
_L 0x2011D768 0x24030110
_L 0x2011E764 0x00002021
_L 0x2010330C 0xAF0C0004
_L 0x201143C0 0x241101A2
_L 0x201143C4 0x24100110
_C0 Rondo of Blood original res
_L 0xE00C0918 0x0010000C
_L 0xE00B3F80 0x100282D4
_L 0x200282D4 0x3C033F80
_L 0x200282E0 0x00602021
_L 0x200282EC 0x3C033F80
_L 0x200282F0 0x00602021
_L 0x200282FC 0x3C0342E0
_L 0x20028300 0x00602021
_L 0x2002AD10 0x3C034388
_L 0x2002830C 0x3C044200
_L 0x20028310 0xAC64C130
_L 0x20028314 0x03E00008
_L 0x20029A78 0x24040000
_C0 Rondo of Blood fullscreen
_L 0xE0060918 0x0010000C
_L 0xE00543AA 0x10029CDC
_L 0x20029CDC 0x3C0243AA
_L 0x20029CE0 0x3C0243AA
_L 0x2002AD10 0x3C0343AA
_L 0x2002AD0C 0x44800000
_L 0x20029D44 0x44800800
_C0 Rondo of Blood full screen [Disable]
_L 0xE0050918 0x0010000C
_L 0x20029CDC 0x3C024380
_L 0x20029CE0 0x3C024380
_L 0x2002AD10 0x3C034380
_L 0x2002AD0C 0xC440C12C
_L 0x20029D44 0xC441C12C
_C0 Akumajyo Dracula Peke full screen
_L 0xE0050000 0x0010000C
_L 0xE00443AA 0x10118E10
_L 0x20118E10 0x3C0243AA
_L 0x201188E8 0x44800800
_L 0x20118E38 0x44801800
_L 0x20118DBC 0x24060154
_C0 Akumajyo Dracula Peke full screen [Disable]
_L 0xE0040000 0x0010000C
_L 0x20118E10 0x3C024380
_L 0x201188E8 0xC4416C60
_L 0x20118E38 0xC4436C60
_L 0x20118DBC 0x24060100
_S ULUS-10401
_G Samurai Shodown Anthology
_C0 Disable magnification filtering in SSVI
_L 0xE0010107 0x0004CEA0
_L 0x2004CEA0 0x35C70007
_C0 Disable magnification filtering in SSVI [Disable]
_L 0xE0010007 0x0004CEA0
_L 0x2004CEA0 0x35C70107
_S ULJM-05109
_G Sakura Taisen 1 & 2
_C0 Disable heavy effects
_L 0xE00C0000 0x00102B00
_L 0x20102B00 0x0A200400
_L 0x20001000 0x3C0D0406
_L 0x20001004 0x25AD0002
_L 0x20001008 0x15A50006
_L 0x2000100C 0x3C0DB800
_L 0x20001010 0x25AD0909
_L 0x20001014 0x8D9BFFEC
_L 0x20001018 0x176D0002
_L 0x2000101C 0x00000000
_L 0x20001020 0x00002821
_L 0x20001024 0x0A240AC2
_L 0x20001028 0xAD2B0000
_C0 Disable heavy effects [Disable]
_L 0xE0010400 0x00102B00
_L 0x20102B00 0xAD2B0000
_S ULES-00307
_G Megaman Powered Up
_C0 Movement Mod
_L 0xE00E0014 0x0012F0D8
_L 0x2012F0D8 0x0E200440
_L 0x20001100 0x8E640000
_L 0x20001104 0x30840300
_L 0x20001108 0x3C050880
_L 0x2000110C 0xACA41118
_L 0x20001110 0x03E00008
_L 0x20001114 0x8FA50014
_L 0x2005A43C 0x0E200447
_L 0x2000111C 0x3C070880
_L 0x20001120 0x8CE71118
_L 0x20001124 0x54E00001
_L 0x20001128 0xE60C03C0
_L 0x2000112C 0x03E00008
_L 0x20001130 0x00000000
_C0 Hold L or R to restore old movement
_C0 Movement Mod [Disable]
_L 0x2012F0D8 0x8FA50014
_L 0x2005A43C 0xE60C03C0
_C0 Instant Movement
_L 0xE00114A0 0x0005A416
_L 0x2005A414 0x10000029
_C0 Instant Movement [Disable]
_L 0x2005A414 0x14A00029
_S ULES-00740
_G Driver '76
_C0 Set spiky vertices to NaN
_L 0xE03D000D 0x002FE288
_L 0x202FE288 0x0E200400
_L 0x202FE30C 0x0E200400
_L 0x202FE628 0x0E200400
_L 0x202FE6AC 0x0E200400
_L 0x202FE9CC 0x0E200400
_L 0x202FEA54 0x0E200400
_L 0x202FB8E8 0x0E200400
_L 0x202FB96C 0x0E200400
_L 0x202FBC58 0x0E200400
_L 0x202FBCDC 0x0E200400
_L 0x202FBEE4 0x0E200400
_L 0x202FBF5C 0x0E200400
_L 0x20001000 0x34090000
_L 0x20001004 0xE8C3000D
_L 0x20001008 0x8CCE0008
_L 0x2000100C 0x3C1B4500
_L 0x20001010 0x036ED82A
_L 0x20001014 0x13600007
_L 0x20001018 0x3C1B7FFF
_L 0x2000101C 0x3C0E7FC0
_L 0x20001020 0xACCE0008
_L 0x20001024 0xACCE000C
_L 0x20001028 0xACCE0010
_L 0x2000102C 0x03E00008
_L 0x20001030 0x00000000
_L 0x20001034 0x036ED82A
_L 0x20001038 0x1760FFF8
_L 0x2000103C 0x3C1BC500
_L 0x20001040 0x036ED82A
_L 0x20001044 0x1760FFF5
_L 0x20001048 0x8CCE000C
_L 0x2000104C 0x1120FFEF
_L 0x20001050 0x25290001
_L 0x20001054 0x1000FFF5
_L 0x20001058 0x00000000
_L 0x202FE294 0x0E200417
_L 0x202FB8F4 0x0E200417
_L 0x202FBC64 0x0E200417
_L 0x2000105C 0x34090000
_L 0x20001060 0xE8C30021
_L 0x20001064 0x8CCE001C
_L 0x20001068 0x3C1B4500
_L 0x2000106C 0x036ED82A
_L 0x20001070 0x13600007
_L 0x20001074 0x3C1B7FFF
_L 0x20001078 0x3C0E7FC0
_L 0x2000107C 0xACCE001C
_L 0x20001080 0xACCE0020
_L 0x20001084 0xACCE0024
_L 0x20001088 0x03E00008
_L 0x2000108C 0x00000000
_L 0x20001090 0x036ED82A
_L 0x20001094 0x1760FFF8
_L 0x20001098 0x3C1BC500
_L 0x2000109C 0x036ED82A
_L 0x200010A0 0x1760FFF5
_L 0x200010A4 0x8CCE000C
_L 0x200010A8 0x1120FFEF
_L 0x200010AC 0x25290001
_L 0x200010B0 0x1000FFF5
_L 0x200010B4 0x00000000
_C0 Set spiky vertices to NaN [Disable]
_L 0xE00F0400 0x002FE288
_L 0x202FE288 0xE8C3000D
_L 0x202FE30C 0xE8C3000D
_L 0x202FE628 0xE8C3000D
_L 0x202FE6AC 0xE8C3000D
_L 0x202FE9CC 0xE8C3000D
_L 0x202FEA54 0xE8C3000D
_L 0x202FB8E8 0xE8C3000D
_L 0x202FB96C 0xE8C3000D
_L 0x202FBC58 0xE8C3000D
_L 0x202FBCDC 0xE8C3000D
_L 0x202FBEE4 0xE8C3000D
_L 0x202FBF5C 0xE8C3000D
_L 0x202FE294 0xE8C30021
_L 0x202FB8F4 0xE8C30021
_L 0x202FBC64 0xE8C30021
_S ULUS-10107
_G Valkyrie Profile: Lenneth
_C0 Credits Movie Freeze workaround
_L 0xE012FFC3 0x00004248
_L 0x20004248 0x0E200800
_L 0x2000424C 0x3C020100
_L 0x20002000 0x2442FFFF
_L 0x20002004 0x8E080008
_L 0x20002008 0x8E09000C
_L 0x2000200C 0x3C1B0001
_L 0x20002010 0x15020003
_L 0x20002014 0x0370D820
_L 0x20002018 0x8F680008
_L 0x2000201C 0x8F69000C
_L 0x20002020 0xAE080008
_L 0x20002024 0xAE09000C
_L 0x20002028 0x56040003
_L 0x2000202C 0x92020005
_L 0x20002030 0x03E00008
_L 0x20002034 0x00000000
_L 0x20002038 0x0A201056
_L 0x2000203C 0x00000000
_C0 Credits Movie Freeze workaround [Disable]
_L 0xE0020800 0x00004248
_L 0x20004248 0x5604FFC3
_L 0x2000424C 0x92020005
_S ULUS-10249
_G Test Drive Unlimited
_C0 (Requires restart)
_C0 Remove slow and ugly effect
_L 0xE0020406 0x002DC218
_L 0x202DC218 0x00003021
_L 0x202DC21C 0x00000000

**Comment by LunaMoo** [comment]
That looks like my cheats, just download cheat.db directly from my github repo https://github.com/LunaMoo/PPSSPP_workarounds
when cheat.db is placed under PSP\Cheats on memstick, you will be able to import cheats for the particular game from the database from cheat menu(available on pause menu after activating cheats in system settings).

**Comment by Emulatorer** [comment]
Duplicate Issue Of #7347

**Comment by unknownbrackets** [comment]
Closing as duplicate noted above.

-[Unknown]
