### ISSUE TITLE
[Android] Regression On James Cameron Avatar Rendering and speed

### ISSUE THREAD

**Issue by mgemt** [hrydgard/ppsspp#11479]
### What happens?
Games James Cameron Avatar not rendered properly when using opengl es on 1.6.3-536 version

![screenshot_20181018-114332](https://user-images.githubusercontent.com/44252828/47132256-3985d180-d2cd-11e8-9841-6dc3a13ab087.png)

### What *should* happen?
Games rendered properly like 1.6.3-312 version using opengl es

![screenshot_20181018-114145](https://user-images.githubusercontent.com/44252828/47132307-60dc9e80-d2cd-11e8-8907-fbbda57ee769.png)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Snapdragon 636, Android Oreo, PPSSPP 1.6.3-536

**Comment by Emulatorer** [comment]
Did you try to use the latest git build 1.6.3-569?

**Comment by mgemt** [comment]
Yes, the issue still exist, it fine on cutscene/few second then the screen become bluish like the image above

**Comment by mgemt** [comment]
tested but nope, the -341 version render the game properly

**Comment by mgemt** [comment]
the -341 got polygon glitch at random times
![screenshot_20181018-145020](https://user-images.githubusercontent.com/44252828/47139491-23d0d600-d2e6-11e8-96b7-5016bb89df01.png)

the -334 fine but the spark has the pink color issue

![screenshot_20181018-145451](https://user-images.githubusercontent.com/44252828/47139604-6a263500-d2e6-11e8-928c-0df264a49451.png)

**Comment by hrydgard** [comment]
Huh, okay, that's a bit unexpected. Would you be able to try some more versions and see if you can find where the color breaks down? Maybe 355?

**Comment by mgemt** [comment]
Confirmed, the color Breaks down started at -355 version

**Comment by hrydgard** [comment]
Thanks. That means it's https://github.com/hrydgard/ppsspp/pull/11308   (though I guess the polygon glitches also should be looked into).

@unknownbrackets This is quite odd, I don't see how https://github.com/hrydgard/ppsspp/pull/11308/files#diff-373d34b78ddb2c505b1d87f732335c49R362 would possibly break it...

**Comment by unknownbrackets** [comment]
My guess would be: the previous change broke it, but the shader compile failed so it ended up doing nothing (visible) and therefore wasn't obvious?

Could you try exporting a GE debugger dump on PC?

To do this, open the game and select Debug -> GE debugger..., then when it's displaying the scene, press Record in the top right.  After a second or so, it'll finish and save a trace of the drawing activity.

After that, check the memstick/PSP/SYSTEM/DUMP folder and it'll have created a file named something like "ULES12345_0000.ppdmp".  You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by mgemt** [comment]
I'm sorry since I new for this, but do you want me to debug on the PC/Android? since the PC version (-355) using OpenGL run the game fine

**Comment by Emulatorer** [comment]
@mgemt you can only capture GE debugger log on PC

**Comment by hrydgard** [comment]
How is this now?

**Comment by mgemt** [comment]
So far it working great now, thanks 😘

**Comment by hrydgard** [comment]
Thanks for letting me know! Closing.
