### ISSUE TITLE
Direct3D 9 does not display images of 3D games

### ISSUE THREAD

**Issue by DmdHoH000** [hrydgard/ppsspp#11477]
### What happens?
When the renderer is set to Direct3D 9 no 3D games display images

Some games that i have tested

Tekken Dark Resurrection

![ulus10139_00001](https://user-images.githubusercontent.com/44216669/47055783-8e233280-d18f-11e8-8a4d-df75d4997229.png)

MegaMan Maverick Hunter X

![ulus10068_00000](https://user-images.githubusercontent.com/44216669/47055805-b6129600-d18f-11e8-8391-047c0aeaa07b.png)

K-On! Houkago Live!!

![uljm05709_00000](https://user-images.githubusercontent.com/44216669/47055868-04279980-d190-11e8-8ce2-44e7add95ffa.png)

Dissidia 012

![ules01505_00000](https://user-images.githubusercontent.com/44216669/47055924-3d600980-d190-11e8-983a-19b42b6aaba9.png)

Kingdom Hearts Birth By Sleep Final Mix

![uljm05775_00000](https://user-images.githubusercontent.com/44216669/47056449-c415e600-d192-11e8-8e54-e77c06dd6bac.png)

Project Diva 2nd

![uljm05681_00000](https://user-images.githubusercontent.com/44216669/47056593-849bc980-d193-11e8-9c2f-342401c5f22f.png)

Fate Unlimited Codes

![npuh10009_00000](https://user-images.githubusercontent.com/44216669/47056653-d6445400-d193-11e8-9a7b-6e56fccc87f2.png)

### What *should* happen?

The games should have been displaying images normally but that is not what happening

Although that 2d games display fine on Direct3D 9

Here s some pics

![ulus10062_00000](https://user-images.githubusercontent.com/44216669/47056269-df342600-d191-11e8-985d-7d0db47261fb.png)

![ulus10584_00000](https://user-images.githubusercontent.com/44216669/47056703-2e7b5600-d194-11e8-9c1c-16ceb494d818.png)
 
### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
My specs
OS: Windows 7 Ultimate Service Pack 1
Processor: Pentium(R) Dual-Core E5400 2.70 Ghz
RAM memory: 4,00 GB (3,87 usable)
GPU: Intel(R) GMA X4500
Last version that work: PPSSPP-v1.6.3-472-g3f34c7a21
Version that broke: PPSSPP-v1.6.3-478-gacfd68864

Sorry if my english is not good because im from Brazil
I have to use Google Translate

**Comment by AkiraJkr** [comment]
That's...pretty weird, considering I am able to emulate just fine on my GMA 450...

Kingdom Hearts Birth by Sleep
![image](https://user-images.githubusercontent.com/27028529/47058480-9d0fe200-d19b-11e8-84a5-458ee38ff41e.png)

Dissidia 012
![image](https://user-images.githubusercontent.com/27028529/47058515-c597dc00-d19b-11e8-983b-58aa0b835c01.png)


Do you mind going to Discord? That way, further can be discussed much faster, and maybe we could find a fix for your issue. https://discord.gg/5NJB6dD

**Comment by unknownbrackets** [comment]
It sounds like some testing had narrowed this down to a certain commit range, right?  I remember seeing a note that it was suspected related to #11393 - can you confirm?

If so, maybe we disable that on Direct3D 9 (theory: only people on older hardware more likely to bug out with that change use Direct3D 9)?

-[Unknown]
