### ISSUE TITLE
Crash on iOS12.1(Beta 5)

### ISSUE THREAD

**Issue by MoshiOfficial** [hrydgard/ppsspp#11489]
### What happens?
Application still can open but, when start emulate psp .iso game file, game will crash.(everytime)

### What *should* happen?
It should can emulate psp with no crash.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
iPhoneX | iOS 12.1 (Beta 5) | PPSSPP v1.6.3-570-g42a73e4c7

**Comment by Emulatorer** [comment]
Duplicate #11483?

**Comment by unknownbrackets** [comment]
Closing as duplicate.  It probably works with jit disabled, because Apple probably fixed the bug that allowed emulation to be fast on iOS.  So you can only have it slow now.  See #11483.

-[Unknown]

**Comment by MoshiOfficial** [comment]
> Duplicate #11483?

I really don't know, have any one asking about this before sorry.
