### ISSUE TITLE
crashing upon loading iOS 12/12.0.1

### ISSUE THREAD

**Issue by SpaceCanvas** [hrydgard/ppsspp#11483]
### What happens?
Crashing upon loading a game

### What *should* happen?
I think it needs a ios 12 support 

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

iPhone X, iOS 12/12.0.1, PPSSPP 1.6.3 

Note: this also happend with a lot of users using ios 12/12.0.1

**Comment by unknownbrackets** [comment]
This is probably a jailbreak issue, not really a PPSSPP issue.  Remember that basically, Apple has a bug in their issue tracker whenever PPSSPP works.  Sometimes one of their developers fixes the bug.

Probably not much we can do.  You can try turning off jit in the developer tools section.

-[Unknown]

**Comment by unknownbrackets** [comment]
It was noted on Discord that disabling jit worked fine, confirming that Apple fixed the bug allowing jit to work.  I guess that means we can do #9186 and just leave iOS people to have terribly battery life and often not get 60 FPS.

-[Unknown]

**Comment by mygizli04** [comment]
Is this old? I can play with JIT on my i6 on 12.0.1.

**Comment by unknownbrackets** [comment]
Okay, great.  I'll close this then.

-[Unknown]
