### ISSUE TITLE
[Feature Request] GPU Turbo Support For Huawei Smart Phone? 

### ISSUE THREAD

**Issue by Emulatorer** [hrydgard/ppsspp#11485]
https://consumer.huawei.com/sg/press/news/2018/huawei-upgrades-devices-gaming-performance-with-gpu-turbo-update/

The GPU Turbo tweak claims to increase the phone’s GPU power by up to 75% but at the same time reduces power consumption by up to 25%

**Comment by hrydgard** [comment]
Is this something apps have to individually support? Assuming it's a device feature, it should just work, no?

**Comment by LunaMoo** [comment]
This is more like profiles/driver optimizations on pc, it's done by Huawei to most popular games, it's pretty much outside of anyone's power here.

**Comment by unknownbrackets** [comment]
Based on the above, I'm going to close this.  If there's something we can do to enable it, feel free to comment here and we'll reopen.

-[Unknown]
