### ISSUE TITLE
ppsspp 1.7 ppa unstable appears named as 1.6.3

### ISSUE THREAD

**Issue by mrdeathjr28** [hrydgard/ppsspp#11494]
### What happens?

ppsspp appears incorrectly named as 1.6.3

### What *should* happen?

ppsspp must be appear as 1.7

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Nvidia Drivers 410.57 (run package from nvidia drivers homepage)

Xubuntu 18.04 x64 - Kernel 4.17.12 generic (ubuntu mainline) - 

CPUFreq: Performance

CPU: Core i3 8350K Tri-Core (Coffelake 14nm) 5.0Ghz + CoolerMaster Hyper T4

MEMORY: 8GB DDR4 2400mhz (4x2) Mushkin (dual channel: 37.5 gb/s)

GPU: Gigabyte Nvidia Geforce GTX 1050 OC (GP107 14nm: 640 Shaders / 40 TMUS / 32 ROPS) Windforce 2GB DDR5 7000Mhz 128Bit (110Gb/s)

MAINBOARD: ASUS Z370-P

**Comment by unknownbrackets** [comment]
Okay, I'm going to close this then if it's fixed.

-[Unknown]
