### ISSUE TITLE
Not applied & missing strings to translate?

### ISSUE THREAD

**Issue by AkiraJkr** [hrydgard/ppsspp#11499]
I've just noticed a few strings that aren't in the .ini files for translation, so I'm keeping a shot of where they are. It's in credits, but dunno. It was kinda offsetting to see that.

![image](https://user-images.githubusercontent.com/27028529/47609924-f4754400-da1e-11e8-89fd-b54ffaa563e6.png)

![image](https://user-images.githubusercontent.com/27028529/47609973-10c5b080-da20-11e8-9401-a88318d07467.png)

**Comment by AkiraJkr** [comment]
Thanks for it. By the way, the Discord strings still aren't applying for some odd reason, although I've seen it in other languages such as french.

**Comment by vnctdj** [comment]
You're welcome :)

Which "Discord strings" are you referring to?
If it works in one language, it must work in all...

**Comment by AkiraJkr** [comment]
Ok, this is a very...interesting thing going on... in two scenarios, the status isn't displayed in the correct language it should.

1 - When you just start PPSSPP, it will always be "In menu" instead of the translated language's line

and

2 - When you switch languages, it doesn't switch until the status changes.

**Comment by unknownbrackets** [comment]
Maybe there's a race condition and it's trying to initialize the discord status prior to loading the language text.  And it surely doesn't update on language switch.

Maybe the easiest thing is to reset the discord status when language data is loaded.  That does mean it would momentarily set "In menu" before fixing to the proper language.

-[Unknown]

**Comment by unknownbrackets** [comment]
Does that mean the race condition with translations loading after Discord setting the status is no longer happening?

-[Unknown]
