### ISSUE TITLE
Ace combat lag

### ISSUE THREAD

**Issue by kyousuke77** [hrydgard/ppsspp#11492]
In Ace combat X, whatever your hardware or setting is, end up very choppy video playback at 33% speed.
Upper one is problem I'm encountering. it's all chopped up, not even smooth slow motion - While below one is using Hi-res replaced textures and running in 8x PSP resolution without even full loading GPU.
Originally I had no problem viewing intro cutscene until Mission 14, but now this is giving me headache. I can't withstand that sound.
 lagging is happening when decoding video, with intense delay on Kernel itself too.
So when I save state, leave that lagging for while and reloading state - That part plays so smoothly as they are using cache.
That means PPSSPP is having issue decoding video for some reason.
I just skipped that video for now but it's important stories.

**Comment by unknownbrackets** [comment]
Sometimes games do unexpected things, like render an entire 3D scene and then draw a video on top of it.

What graphics backend are you using?  What device?

-[Unknown]

**Comment by kyousuke77** [comment]
Buffered rendering,xiaomi redmi 5A

**Comment by unknownbrackets** [comment]
OpenGL or Vulkan?

It could also be texture replacements, e.g. if it is using a different hashing method or something.

-[Unknown]

**Comment by kyousuke77** [comment]
https://imgur.com/a/L3mUb21
openGL

**Comment by kyousuke77** [comment]
Thank you so much
I just update my ppspp from 1.6.3 to 1.7 and its fix all the issue

**Comment by unknownbrackets** [comment]
Oh, glad to hear.

-[Unknown]
