### ISSUE TITLE
Spectral vs generation black screen

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#11500]
Spectral vs generation has been black screen but I can hear the sound

**Comment by leopard20** [comment]
Can you provide more details? What device are you running PPSSPP on? Also provide its hardware (GPU, CPU, etc) and software details (OS, driver version, etc).
What backend do you use in PPSSPP? Are you using the default settings?

**Comment by Emulatorer** [comment]
https://github.com/hrydgard/ppsspp/wiki/How-to-report-an-issue-properly

**Comment by benderscruffy01** [comment]
this can be closed
