### ISSUE TITLE
Force unthrottle

### ISSUE THREAD

**Issue by InfamousKnight** [hrydgard/ppsspp#11511]
With libtas, we would have to hold the unthrottle key for time to advance.

So having an auto unthrottle key would be nice to benefit tasers.

Linux only problem

**Comment by unknownbrackets** [comment]
Can you just use alternate speed (which can be on press or toggled)?

-[Unknown]

**Comment by InfamousKnight** [comment]
Sorry for the late response, keylie tested alternate speed and it works! Psp games can now be tased:
