### ISSUE TITLE
MGS-Peace Walker - Stuck at loading screen

### ISSUE THREAD

**Issue by Iron-Claws** [hrydgard/ppsspp#11514]
### What happens?

  I can't get past the loading screen of the  mission "Infiltrate the crater Base" in Metal Gear Solid: Peace Walker. 
   After clicking start mission, the loading screen appears and the peace symbol at the bottom right corner starts oscillating endlessly, but the actual game never starts. 

### What *should* happen?

  The game should start as it's supposed to be

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

  Hardware info:
Device: Honor 9 lite HUAWEI:LLD-AL10
CPU: Hisilicon Kirin 659 Cores: 8
RAM: 3 GB

  OS:
Android 8.0.0

  PPSSPP 
Build: Release
Version: v1.6.3

This happens on both Vulkan and OpenGL

  Savestate:
[ULUS10509_1.01_1.ppst.zip](https://github.com/hrydgard/ppsspp/files/2533037/ULUS10509_1.01_1.ppst.zip)

  Screenshots:
![screenshot_20181031-121623](https://user-images.githubusercontent.com/44631244/47770820-e10bf680-dd06-11e8-83bc-6bb7db55c9d1.jpg)

This is where it gets stuck:
![screenshot_20181031-121633](https://user-images.githubusercontent.com/44631244/47770833-ee28e580-dd06-11e8-9c47-c97bdb253433.jpg)

**Comment by bababoombatman** [comment]
It happened to me as well, have you tried loading your save like you would do in a normal psp and not used your savestate? It fixed it for me. Remember that using only savestates after a while can cause bugs so once in a while load your normal state then do a new savestate

**Comment by Iron-Claws** [comment]
> It happened to me as well, have you tried loading your save like you would do in a normal psp and not using your savestate? It fixed it for me. Remember that using only savestates after a while can cause bugs so once in a while load your normal save then do a new savestate.

That worked. Thanks a lot 😊😊😊
