### ISSUE TITLE
Ace Combat Joint Assault - Missing ground texture when too close

### ISSUE THREAD

**Issue by Abbanon** [hrydgard/ppsspp#11521]
In Ace Combat Joint Assault, the ground texture disappears in a certain radius around your aircraft when you get too close to it.
This happens in D3D9 and D3D11. The entire game is just a black screen in OpenGL. Cannot test Vulkan.

![ulus10511_00025](https://user-images.githubusercontent.com/37251822/47940223-6555a980-dec0-11e8-99cc-f187753be4f2.png)
![ulus10511_00032](https://user-images.githubusercontent.com/37251822/47940228-65ee4000-dec0-11e8-8799-0106535ed00e.png)
![ulus10511_00030](https://user-images.githubusercontent.com/37251822/47940229-65ee4000-dec0-11e8-89e5-066e1ace2ca1.png)
![ulus10511_00031](https://user-images.githubusercontent.com/37251822/47940230-65ee4000-dec0-11e8-87aa-0ad208d2b805.png)

**Comment by LunaMoo** [comment]
Turn off "Disable Slower Effects". This is not an emulation bug, just a speedhack in action, closing.
![ulus10511_00001](https://user-images.githubusercontent.com/5485237/47940934-8df39880-deec-11e8-92d6-901fa70b444d.jpg)
