### ISSUE TITLE
Burnout Legend Graphics Glitch in v1.7.1 - v1.7.2

### ISSUE THREAD

**Issue by Emulatorer** [hrydgard/ppsspp#11527]
Buffered Rendering (Default Settings)
![screenshot_2018-11-04-09-30-56](https://user-images.githubusercontent.com/37603562/47959024-51e63380-dfd1-11e8-8ca1-8a74e3da31e2.png)

Non-Buffered Rendering
![screenshot_2018-11-04-09-31-05](https://user-images.githubusercontent.com/37603562/47959038-7b9f5a80-dfd1-11e8-8b2d-a65be85bfd58.png)

Logcat
[ppsspp.txt](https://github.com/hrydgard/ppsspp/files/2545482/ppsspp.txt)

Phone Specs:
GPU - Mali-450 MP
CPU - MT6592 Octacore
RAM - 2GB

**Comment by unknownbrackets** [comment]
Is this only happening on Mali-4xx devices?  Are you able to test a desktop?

-[Unknown]

**Comment by Emulatorer** [comment]
Sorry I don't have a desktop :(

But I test the latest gitbuild seems the graphics issue is fix

**Comment by hrydgard** [comment]
I don't really see any possible changes that could have fixed something like this... Can you try a few git builds and see if you can figure out which one it is?

**Comment by Emulatorer** [comment]
@unknownbrackets seems ok in Mali-T720 GPU Android 6.0 Marshmallow :'/

**Comment by Emulatorer** [comment]
Start only in ppsspp v1.7.1 and then
fix in v1.7.1-2 gitbuild but why still this happen in v1.7.2 from playstore?

**Comment by Emulatorer** [comment]
I think my phone is the real problem 
maybe because its rooted ? :/ 
Because I tested android 6.0 Mali-400 MP2 GPU there's no graphics issues

So I will closed this ✌😅
