### ISSUE TITLE
After 1.7.1, on-screen buttons don't work / are misaligned

### ISSUE THREAD

**Issue by Devilden92** [hrydgard/ppsspp#11526]
Samsung Galaxy s8 plus.
PPSSPP 1.7.1.
Game: Monster hunter freedom Unite.
Right buttons doesn't work.

**Comment by leopard20** [comment]
Do you mean controller buttons? Because touch controls work just fine for me.

Perhaps you should check the controls setup.

**Comment by Devilden92** [comment]
Hi Leo!

I mean on screen touch controls (triangle, X, square and circle buttons).
When I touch them, they are work once from 4-5 touchings
Other button works well.

Отправлено из приложения "Почта" для Windows 10

От: Leo
Отправлено: 3 ноября 2018 г. в 16:06
Кому: hrydgard/ppsspp
Копия: Devilden92; Author
Тема: Re: [hrydgard/ppsspp] After 1.7.1 update some button doesn't work.(#11526)

Do you mean controller buttons? Because touch controls work just fine for me.
Perhaps you should check the controls setup.

**Comment by unknownbrackets** [comment]
Hm, this is a problem I've seen before.  If you go into settings and toggle immersive mode, does it (temporarily) make the buttons work?

Are you using Vulkan or OpenGL?  If you change the backend and try playing / restarting PPSSPP a couple times, does it work on one but not the other?

-[Unknown]

**Comment by Devilden92** [comment]
Immersive mode doesn't help. Buttons work a couple times, and then nothing.
I use Vulkan. When I changed the backend an try to  play/restart ppsspp, on
both variants same story.


сб, 3 нояб. 2018 г., 18:46 Unknown W. Brackets notifications@github.com:

**Comment by Devilden92** [comment]
Version 1.7.2
Samsung Galaxy s8 plus.
Problems with right buttons on screen disappears when I toggled an immersive mode.
Thank you guys!!!👏👏👏👏👏

**Comment by unknownbrackets** [comment]
Hm, that's concerning... though I'm glad toggling it is working now.

@hrydgard I seem to remember we had some hacks trying to work around bugs on this device - maybe they're not working or my Vulkan sizing fix reverted them?

-[Unknown]

**Comment by Devilden92** [comment]
I don't know, man, really:)

This situation is really strange, and I have no useful thoughts about this.
But now everything is working well and this is all that we have in this
situation.
If something bad happens again, I'll report to you immediately.
Keep in touch.


вс, 4 нояб. 2018 г., 17:46 Unknown W. Brackets notifications@github.com:

**Comment by hrydgard** [comment]
Unknowns fix would be this one, https://github.com/hrydgard/ppsspp/pull/11455 - in that case, the problem should have started around v1.6.3-553. Is that the case?

**Comment by Devilden92** [comment]
lol))) You now what? I checked immersive mode with on/off, and in both
variants buttons worked well!!
I don't know what happened, but it works now anyways.

вс, 4 нояб. 2018 г., 22:26 Henrik Rydgård notifications@github.com:

**Comment by unknownbrackets** [comment]
I think the issue is - when you first start it up, it will be wrong (this was the case before #11455 on my Pixel with Vulkan), however once you change the resolution it will fix it.

That means, if you turn immersive off or on, it's fine.  However, if you quit PPSSPP and start it again (with immersive on), it will be wrong.  Again, that's just the behavior that existed prior to #11455 on my Pixel.

-[Unknown]

**Comment by Devilden92** [comment]
Wait a minute. I rechecked immersive mode again and now when it's off,
right buttons doesn't work. When i touch them little in a side they didn't
work.

вс, 4 нояб. 2018 г., 22:32 Henrik Rydgård notifications@github.com:

**Comment by Devilden92** [comment]
Now I can say that when immersive mode is "on", everything works well, even
if I quit and start ppsspp. But when it's "off", buttons didn't work.

вс, 4 нояб. 2018 г., 22:46 Unknown W. Brackets notifications@github.com:

**Comment by Devilden92** [comment]
Hello. I have a strange problem in Monster Hunter Freedom Unite game. After
a couple months of not playing I have loaded the game and there is only
music, but no sfx sounds. That happens only in save/load state mode, but if
I started a new game - all sounds ok. Help please, if it's possible.

вс, 4 нояб. 2018 г., 22:54 Denis Fastenkov <deniforester2013@gmail.com>:
