### ISSUE TITLE
chinese.txt and korean.txt are unnecessary

### ISSUE THREAD

**Issue by gary-ts** [hrydgard/ppsspp#11534]
I think chinese.txt and korean.txt are unnecessary.
They are moved to assets/lang/zh_CN.ini and ko_KR.ini.

**Comment by Narugakuruga** [comment]
agreed

**Comment by xiushudongfang** [comment]
it is necessary. ui_atlas.cpp  and ui_atlas.zim  need them.

**Comment by hrydgard** [comment]
Many platforms now don't need the bitmap font atlas that we used to generate with them (since they now can use system fonts), but a few still do. Should probably regenerate zoon...
