### ISSUE TITLE
FF4 Complete collection font issuo

### ISSUE THREAD

**Issue by masterqfox** [hrydgard/ppsspp#11532]
I had problem with Final fantasy IV complete collection Iso , i even updated the ppsspp to latest one but still facing same issue ~ is it from my iso or my computer or there is way to fix it through the emulator
![ffiv font problem](https://user-images.githubusercontent.com/35999854/47972369-13c24000-e0b5-11e8-9258-a203fb45cec9.png)

**Comment by unknownbrackets** [comment]
Have you already tried v1.7.1?  Is this happening in every version for you?

-[Unknown]

**Comment by benderscruffy** [comment]
this has been fixed 
i tried it with my own dumped fonts from my psp and the default fonts that come with ppsspp and they both worked

**Comment by unknownbrackets** [comment]
Strange, not sure where this issue came from then.  Closing.

Thanks for confirming.

-[Unknown]
