### ISSUE TITLE
CMake: USE_WAYLAND_WSI doesn't allow disabling Wayland support

### ISSUE THREAD

**Issue by akien-mga** [hrydgard/ppsspp#11536]
### What happens?

Building PPSSPPSDL on Linux with Wayland installed but `USE_WAYLAND_WSI=OFF` still links against Wayland (if installed on the system). The option seems to be only used to force check that wayland support will be enabled here: https://github.com/hrydgard/ppsspp/blob/f81dd83aa053316f1be7b12b627cf528b4cdc801/CMakeLists.txt#L149-L151

### What *should* happen?

I'd want the option to define whether Wayland should be used or not, and not simply whether its absence is a fatal error.

As such I'd propose something like the following diff. Opening an issue for feedback instead of a PR for now, as the current behaviour might be intended - I'm just suggesting to change it.
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 4c15cba0d..9129a6659 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -134,7 +134,7 @@ option(USE_FFMPEG "Build with FFMPEG support" ${USE_FFMPEG})
 option(USE_SYSTEM_SNAPPY "Dynamically link against system snappy" ${USE_SYSTEM_SNAPPY})
 option(USE_SYSTEM_FFMPEG "Dynamically link against system FFMPEG" ${USE_SYSTEM_FFMPEG})
 option(USE_SYSTEM_LIBZIP "Dynamically link against system libzip" ${USE_SYSTEM_LIBZIP})
-option(USE_WAYLAND_WSI "Set to ON to require Wayland support for Vulkan" ${USE_WAYLAND_WSI})
+option(USE_WAYLAND_WSI "Set to ON to require Wayland support for Vulkan" ON)
 option(USE_ADDRESS_SANITIZER "Use Clang memory sanitizer" ${USE_ADDRESS_SANITIZER})
 
 if(UNIX AND NOT (APPLE OR ANDROID) AND VULKAN)
@@ -145,13 +145,14 @@ if(UNIX AND NOT (APPLE OR ANDROID) AND VULKAN)
 		message("NOT using X11 for Vulkan")
 	endif()
 	# add_definitions(-DVK_USE_PLATFORM_XCB_KHR)
-	find_package(Wayland)
-	if(USE_WAYLAND_WSI AND NOT WAYLAND_FOUND)
-		message(FATAL_ERROR "Could not find libwayland, but USE_WAYLAND_WSI was enabled. Failing.")
-	endif()
-	if(WAYLAND_FOUND)
-		include_directories(${WAYLAND_INCLUDE_DIR})
-		add_definitions(-DVK_USE_PLATFORM_WAYLAND_KHR)
+	if(USE_WAYLAND_WSI)
+		find_package(Wayland)
+		if(NOT WAYLAND_FOUND)
+			message(FATAL_ERROR "Could not find libwayland, but USE_WAYLAND_WSI was enabled. Failing.")
+		else()
+			include_directories(${WAYLAND_INCLUDE_DIR})
+			add_definitions(-DVK_USE_PLATFORM_WAYLAND_KHR)
+		endif()
 	endif()
 endif()
 
 ```

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Mageia 7 x86_64 (Linux), PPSSPP 1.7.2/master.

**Comment by akien-mga** [comment]
BTW Wayland is considered "found" even if wayland-egl is missing, but that might be on purpose. Just mentioning it in case it's a bug in `FindWayland.cmake`:
```
-- Found WAYLAND_CLIENT: /usr/lib/libwayland-client.so  
-- Found WAYLAND_SERVER: /usr/lib/libwayland-server.so  
-- Could NOT find WAYLAND_EGL (missing: WAYLAND_EGL_LIBRARIES) 
-- Found WAYLAND_CURSOR: /usr/lib/libwayland-cursor.so  
-- Found WAYLAND: /usr/lib/libwayland-client.so;/usr/lib/libwayland-server.so;WAYLAND_EGL_LIBRARIES-NOTFOUND;/usr/lib/libwayland-cursor.so
```

**Comment by hrydgard** [comment]
Your change looks fine to me, feel free to make a pull request.

That could very well be a bug in FindWayland.cmake. Feel free to fix it if you like :)

**Comment by akien-mga** [comment]
Had a quick look at `FindWayland.cmake`, but I don't see an easy way to improve the script. It will mark `WAYLAND_FOUND` as true if those variables are defined: https://github.com/hrydgard/ppsspp/blob/master/cmake/Modules/FindWayland.cmake#L56

And it seems to consider that `/usr/lib/libwayland-client.so;/usr/lib/libwayland-server.so;WAYLAND_EGL_LIBRARIES-NOTFOUND;/usr/lib/libwayland-cursor.so` is a proper definition.

All in all I'd say let's not fix what's not broken -- if some users start complaining about not being able to build because they had a partial wayland dev setup, it can be investigated further.
