### ISSUE TITLE
ppsspp crash immediately after clicking (edf portable 2)

### ISSUE THREAD

**Issue by kyousuke77** [hrydgard/ppsspp#11544]
https://imgur.com/a/hyYrfUE
ppsspp 1.7.1
xiaomi redmi 5a (Adreno 308)
buffered rendering
game:earth defence force portable 2
ppsspp pc version normal but crashes on android

**Comment by unknownbrackets** [comment]
Did it work in older versions, like v1.5.4?  Have you tried the latest git build?

-[Unknown]

**Comment by hrydgard** [comment]
Vulkan or OpenGL in Graphics backend?

**Comment by kyousuke77** [comment]
Open GL in Graphic backend

**Comment by hrydgard** [comment]
Closing as outdated.
