### ISSUE TITLE
Regression in tenchu: shadow assasins

### ISSUE THREAD

**Issue by bababoombatman** [hrydgard/ppsspp#11555]
### What happens?
In 1.7.1-137 during assasination scenes the screen display this issue:
https://ibb.co/iiTgdV
It goes away when the assasination is performed

### What *should* happen?
In 1.7.1-132 everything is fine as you can see here:
https://ibb.co/hfREXq

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Running ppsspp 1.7.1-137 (OpenGL) on a Asus zenfone go (android 5.1)
GPU: ARM Mali-400 MP1

**Comment by hrydgard** [comment]
Thanks for reporting, this needs fixing. I feared that change could break a few obscure things here and there, and here we go.

**Comment by JimsAlliance** [comment]
The same update also added some artifacts on screen during races in Motorstorm Arctic Edge.

**Comment by bababoombatman** [comment]
Good news! I've just downloaded 1.7.1-181 and the tenchu issue is fixed! It can be closed, thanks for your hard work.
You need the exact build that fixed it? I can't search it right now 😀

**Comment by hrydgard** [comment]
Nah, that's alright, it was likely Unknown's latest little fix, https://github.com/hrydgard/ppsspp/pull/11575.

Hopefully it took care of the new problem in Motorstorm too, @JimsAlliance ?

**Comment by JimsAlliance** [comment]
> Hopefully it took care of the new problem in Motorstorm too, @JimsAlliance ?

Yes, all is clear again.
