### ISSUE TITLE
[Vulkan] Burnout Dominator - Graphical issue

### ISSUE THREAD

**Issue by leopard20** [hrydgard/ppsspp#11557]
The cars and the tracks are not rendering properly. It's very similar to this issue: https://github.com/hrydgard/ppsspp/issues/10655
![screenshot_2018-11-12-19-30-11-643_org ppsspp ppsspp](https://user-images.githubusercontent.com/16115820/48360179-e167a280-e6b3-11e8-891a-d96ab55abcbf.png)
Tested v1.7.1-141, v1.7.1 and v1.6.3 and got the same result on all three. OGL works fine.
It's weird though. I can swear I used to play this game flawlessly before. It seems to have happened after updating my OS. So chances are it's a driver bug. Or maybe it's caused by Depth Clamping, which wasn't available on my previous driver.
Can someone else test and verify this plz?

Device: Mi 5s plus, Android 8.0, Vulkan backend.

**Comment by hrydgard** [comment]
It's probably the recent changes to buffer management that were made to allow speedups in some games. It's clear that something was overlooked. Thanks for reporting!

**Comment by leopard20** [comment]
> Thanks for reporting!

You're welcome!
BTW, I tested version 1.5.4 and that one worked fine. So I guess you're right!

**Comment by crazyrexz** [comment]
at burnout legends too had this issue also when sun approached framerate getting crawl

**Comment by ppmeis** [comment]
Tested both Burnout games, no issues here (Windows 10 x64 October Update and Nvidia GPU):

![image](https://user-images.githubusercontent.com/4381277/48943715-5d6bb100-ef24-11e8-8bbd-fb54865659d5.png)

![image](https://user-images.githubusercontent.com/4381277/48943732-6a88a000-ef24-11e8-9991-dc2965ae5c67.png)

Burnout Legends: https://github.com/hrydgard/ppsspp/issues/10436#issuecomment-441229478

**Comment by leopard20** [comment]
@ppmeis And this is the Vulkan backend?

**Comment by ppmeis** [comment]
> @ppmeis And this is the Vulkan backend?

Yes it is.

**Comment by unknownbrackets** [comment]
Maybe this is related to the #10421 issue and Adreno specific?

-[Unknown]

**Comment by crazyrexz** [comment]
confirmed i using adreno and vulkan too, snapdragon 625, 64bit. so its adreno only, or maybe another android gpu got this issue too? like mali powervr etc

**Comment by hrydgard** [comment]
Still an issue?

**Comment by leopard20** [comment]
Yeah. Nothing has changed.

**Comment by hrydgard** [comment]
More screenshots in the linked duplicate. Seems like another fun Adreno bug to investigate.

**Comment by unknownbrackets** [comment]
Could you try exporting a GE frame dump?  These help a lot.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by hrydgard** [comment]
@leopard20  Can you also check the Game ID of your game? (hold press the icon on the game selection screen, it's after the name).

**Comment by leopard20** [comment]
@hrydgard 
ULUS10236

@unknownbrackets 
Is there something wrong with the remote debugger? It keeps saying not connected.

**Comment by crazyrexz** [comment]
hi, it still slow down at sun area on me, im on latest build github right now. using opengl or vulkan same result. both legends and dominator

**Comment by leopard20** [comment]
@crazyrexz Turn off block simulation.

**Comment by crazyrexz** [comment]
@leopard20 oh is it thanks! yeah finally can play burnout series with stable, i dont mind the annoying boxed shadowed sun, as long as game not hurt. oh a question, by default the vertex cache is checked, is it matter with performance if unchecked? im using vulkan.

btw thanks devs @hrydgard and other people whom fix this.

**Comment by leopard20** [comment]
@crazyrexz Vertex cache doesn't affect the performance much (it nearly has no effect at all) thanks to some optimizations. If you're using Vulkan, you can turn it off safely without any performance hit.

**Comment by hrydgard** [comment]
That's not entirely true, there are some edge cases where vertex cache helps by a few percent - but yeah, not like before.
