### ISSUE TITLE
I think Coldbird is down

### ISSUE THREAD

**Issue by jistjak** [hrydgard/ppsspp#11554]
### What happens?
it seems coldbird is down. Has been for a few days and there is no news i can find that answers why. there seems to be an issue with the DNS, maybe their dynadns or whatever stopped hosting their domain name. However i've tried connecting to the explicit IP (i can't remember the numbers, and i can't google it since all results point to "how to play ppsspp online" with the search query "what is pro.coldbird.net ip address") and even that didn't work. So I'm thinking maybe coldbird servers shutdown. It's not just me, i've tried multiple 'isWebsiteDown' services to see if other places cannot connect to pro.coldbird.net. all of them say that they cannot reach coldbird. I'm hoping it's not down, or at least it will be fixed soon.

### What *should* happen?
like to not get a dns lookup failure and instead get a "network initialized" and optionally (while hopefully) get a rando or two to play with.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
not sure this matters since it seems to be an issue on coldbird's side but.... it's a hp laptop with 4cores@ 2.1ghz, windows 8.1, ppsspp v 1.71 (latest release as of this post), 8GB Ram, and i think it has 768mb vram. Also i use a X360 controller

**Comment by adenovan** [comment]
ppsspp have a build in adhoc server based on that server code so we can still play. if you want to host in internet get your machine connected to internet as DMZ and host the server your client also must be under DMZ. this is an hosting server service issues not a bug tracker. should belong to forum instead.

**Comment by MrColdbird** [comment]
New hostname: black-seraph.com

The old domain got terminated in a recent spring cleaning along with a few alternative domains used to reach the server.

**Comment by hrydgard** [comment]
Noted, will update the default shortly.

**Comment by jistjak** [comment]
I've also found an alternative.
http://www.myneighborsushicat.com/

**Comment by hrydgard** [comment]
I've changed the default to black-seraph.com.

However, need to think about maybe updating this automatically somehow.

**Comment by hrydgard** [comment]
@MrColdbird  Actually does black-seraph.com work as an adhoc server? It doesn't have a listing of online games that I can see?

Anyway, I added a server list at http://ppsspp.org/adhoc.html .  Can be reached from "Guides and help". Should probably do something integrated in the emulator at some point.

**Comment by MrColdbird** [comment]
@hrydgard Yes, it works as an adhoc server, however it currently has no status page associated with it.
This is because the old vhost entry on the nginx webserver hasn't been changed to accomodate the new domain yet.

For PPSSPP (and actual PSP units using the client prx) this doesn't matter however as they don't utilize the status page in any way. I will see to setting up a new vhost this weekend and reply to this issue with updated information when the deed is done.

I like the idea of hosting a known server list though. Giving people alternatives has never been a bad thing.

**Comment by JacobMrox** [comment]
> I like the idea of hosting a known server list though. Giving people alternatives has never been a bad thing.

I second this.

**Comment by devinprater** [comment]
Hi @MrColdbird, has a status page been created yet? I use this a lot to find out if anyone is playing a game I'm about to play or on. Thanks so much for the server.

**Comment by Nexusblack** [comment]
slt qui joue encore a  metal solid gear peace walker psp en ligne

**Comment by Nexusblack** [comment]
> J'ai aussi trouvé une alternative. 
> http://www.myneighborsushicat.com/

merci a celui qui a trouver se site il fonctionne bien
