### ISSUE TITLE
[FMV]KHBBS FMV delay issue

### ISSUE THREAD

**Issue by AkiraJkr** [hrydgard/ppsspp#11559]
![image](https://user-images.githubusercontent.com/27028529/48380017-5a1f2c80-e6bd-11e8-84e0-431de2d3fb39.png)

How to reproduce: Start an FMV. Can be the opening. The video will hang for one sec, and the errors will pop up. Thanks to the hang, the audio is now delayed from the video.

Oddly enough, this DOESN'T happen in the Final Mix version.

**Comment by AkiraJkr** [comment]
Well the particular video I've tried was the first FMV that the game can play after booting the game, which is the uncolored opening.

Final Mix Ver.:
![image](https://user-images.githubusercontent.com/27028529/48475343-ba0ff300-e7e3-11e8-9d24-aff99cd029f8.png)
Weirdly, the Final Mix ver still has warnings, but the audio seems to sync normally with the video.

EUR:
![image](https://user-images.githubusercontent.com/27028529/48475489-11ae5e80-e7e4-11e8-8fb4-e244e345aa97.png)
Way more warnings than Final Mix, and audio is delayed by 1/2/3 seconds. Haven't seem how much exactly, but it's notably 1 second minimum of delay.

Both are using IO Timing Fast. There seems to be no difference when changing it.

For some reason, the hang seems to occur 1 second after the FMV starts, which causes the audio delay. The audio only begins when that hang happens, which is how it ends up delayed.

**Comment by benderscruffy** [comment]
can be closed
i saw no problem with it
