### ISSUE TITLE
Star Wars Lethal Alliance texture regression

### ISSUE THREAD

**Issue by JimsAlliance** [hrydgard/ppsspp#11551]
### What happens?
Textures are missing at especially the edge of screens, most noticeably in narrow hallways. In the first level very near the beginning, the area up the first elevator is a great place to see it.

### What *should* happen?
No missing textures.

No settings where changed from the defaults. I did try using the other backends and a couple of graphical settings, but they did not seem to affect the issue.
The issue is not there in build v1.6.3-472 and first appears in v1.6.3-478. And it is still there in the latest development build as of this post; v1.7.1-127.
Windows PC

**Comment by hrydgard** [comment]
Screenshots of the problem?

**Comment by unknownbrackets** [comment]
What GPU are you using?  Is it an Intel GPU?

Are you using OpenGL, Vulkan, Direct3D 11, or Direct3D 9?  Does it happen on all backends or just some?

-[Unknown]

**Comment by JimsAlliance** [comment]
![b](https://user-images.githubusercontent.com/44926818/48304060-42a44000-e513-11e8-8126-605f1d99c0d9.jpg)
Missing section on the left side.

I tried using the record option of PPSSPP to make a video, but that doesn't seem to work. It only records and saves during the opening FMVs for some reason.

@unknownbrackets I am not using an intel GPU, but I am using an old AMD 7000 series GPU for my retro gaming system. I will have a spare GTX 970 available in a couple of weeks, would using that avoid the issue?
And as I mentioned I did try the other backends, it affects all of them.

**Comment by unknownbrackets** [comment]
The NVIDIA card is likely to render this better, but I'm not certain.

Could you try exporting a GE debugger dump?

To do this, open the game and select Debug -> GE debugger..., then when it's displaying the scene, press Record in the top right.  After a second or so, it'll finish and save a trace of the drawing activity.

After that, check the memstick/PSP/SYSTEM/DUMP folder and it'll have created a file named something like "ULES12345_0000.ppdmp".  You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by hrydgard** [comment]
Could that also be a culled/clipped triangle, rather than just the texture missing?

**Comment by JimsAlliance** [comment]
> Could you try exporting a GE debugger dump?

[ULES00599_0001.zip](https://github.com/hrydgard/ppsspp/files/2582109/ULES00599_0001.zip)

Here you go.

> Could that also be a culled/clipped triangle, rather than just the texture missing?

It probably is. The first couple of times I clearly noticed it was a square section missing, but those were probably just 2 connected triangles.

**Comment by unknownbrackets** [comment]
It could be either 0x0896e050 or 0x08963b20 as the texture in that dump (probably the latter.)

Both are drawn with depth clamp enabled.  Min/max Z: 0x0000-0x2421.  Standard viewport except Z.  Cull front (CW.)

This is what it should look like from a PSP:
![star wars cull](https://user-images.githubusercontent.com/191233/48664770-77a31c00-ea58-11e8-8237-90dab821f749.png)

But software rendering even gets this wrong (looks the same as Vulkan/etc.)  Here for reference:
![star wars cull bad](https://user-images.githubusercontent.com/191233/48664787-e7190b80-ea58-11e8-904e-88e18671d5a8.png)

Narrowed it down to a specific vertex being culled (drawing is fine if just this vert is not culled.)  These are the screen coords:
(522.056763, 4505.915039, 17335.781250)

This is inclusive of offset, so X and Y are out of 4096 (we can see Y is not /very/ outside.)  Depth is approximately 0x43b8 which would not be clamped, so we're continuing to cull it.

HOWEVER, 0x43b8 is outside the max z 0x2421.  My new theory is that it may only cull points outside 4096x4096 if they are within minz/maxz, and otherwise perform clamping and clipping again minz/maxz.  I am certain it does NOT clamp to minz/maxz, but it makes sense that the culling behavior might be controlled by the clipping values.

-[Unknown]

**Comment by ppmeis** [comment]
This is a very buggy game: intro videos plays very bad, and I also suffer rendering issues under an Nvidia card, mostly when you move the camera or you are too close to a wall (these do not happend on real PSP).

**Comment by unknownbrackets** [comment]
It seems related to the viewport parameter, actually.  Maybe it clamps to viewport scale/center, not 0/65535 after all.  Will need to investigate more later.  But it's definitely not my theory above.

-[Unknown]

**Comment by JimsAlliance** [comment]
> This is a very buggy game: intro videos plays very bad, and I also suffer rendering issues under an Nvidia card, mostly when you move the camera or you are too close to a wall (these do not happend on real PSP).

The video sync issues have been reported in #2997 and the discolored double image only appears when using a Direct3D backend.

The other issue you mention is exactly the one from this issue, and can be avoided by using an older version I mentioned in the first post. Other than the video sync issues and long black screens, the game isn't buggy and fun to replay.

**Comment by Gamemulatorer** [comment]
PPSSPP v1.11.3

### OpenGL
![Screenshot_2021-05-23-11-31-28-769_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/119247273-adda2d00-bbba-11eb-9905-b5212d9a369d.jpg)
### Vulkan
![Screenshot_2021-05-23-11-31-10-501_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/119247279-b6326800-bbba-11eb-80b8-7a294ea889f5.jpg)

**Comment by hrydgard** [comment]
Committed what's likely to be a quick workaround, hopefully it'll help until we can really figure out how the PSP's clipping works.

**Comment by unknownbrackets** [comment]
> Narrowed it down to a specific vertex being culled (drawing is fine if just this vert is not culled.) These are the screen coords:
(522.056763, 4505.915039, 17335.781250)

This draw, at 227/396, uses pre-viewport/offset coords of (-6.358097,-18.072906, -2.748493) which per logic in #14168 / #12058 is likely to clip earlier, which would prevent culling.  Although not yet implemented and fully tested, it's very likely those changes would fix this issue.

-[Unknown]

**Comment by unknownbrackets** [comment]
This was fixed in #14833, with or without hardware clip/cull/geometry support.  The frame dump renders correctly (with a hack to display its output) without any compat flags, etc.  As such, closing this.

-[Unknown]
