### ISSUE TITLE
Digimon Adventures graphics Issue when block transfer effects is not enable after #11531

### ISSUE THREAD

**Issue by Emulatorer** [hrydgard/ppsspp#11558]
### What happens?
Graphics issue started in v1.7.1-141-gdf5fbaef7 after implementing the Virtual Readbacks #11531

**Comment by Emulatorer** [comment]
![screenshot_2018-11-13-00-37-21](https://user-images.githubusercontent.com/37603562/48362106-d18f9480-e69a-11e8-88d4-ce77823cb7b2.png)
[Buffered Rendering]

**Comment by hrydgard** [comment]
When does this happen?

**Comment by Emulatorer** [comment]
@hrydgard in the latest gitbuild v1.7.1-141

**Comment by Emulatorer** [comment]
![screenshot_2018-11-13-00-37-33](https://user-images.githubusercontent.com/37603562/48362167-f126bd00-e69a-11e8-96db-09eea31c157c.png)
[Non-Buffered]
![screenshot_2018-11-13-00-37-33](https://user-images.githubusercontent.com/37603562/48362272-2d5a1d80-e69b-11e8-9b10-c59b9751e383.png)

The game also is running very slowly compare to the gitbuild v1.7.1-125

**Comment by Emulatorer** [comment]
Phone Specs:
Mali-450 GPU
OpenGL 2.0

**Comment by hrydgard** [comment]
Well, this is the opposite of what I expected. Will look into it.

**Comment by Emulatorer** [comment]
Enable "Simulate block transfer effects" in rendering mode fixes the issue but the game is very very slow :(

**Comment by hrydgard** [comment]
Bizarre, it should at the very least be faster than before.

**Comment by Emulatorer** [comment]
gitbuild v1.7.1-143 fixed the graphics regression but the game still lag
![screenshot_2018-11-14-08-57-20](https://user-images.githubusercontent.com/37603562/48452783-85327a80-e7a8-11e8-8faa-e8dae49628d4.png)

**Comment by Emulatorer** [comment]
Oops... After a couple of minutes playing issue still happen :/
![screenshot_2018-11-14-09-50-59](https://user-images.githubusercontent.com/37603562/48454958-4ce36a00-e7b1-11e8-83e3-4296c35f1111.png)
![screenshot_2018-11-14-09-52-51](https://user-images.githubusercontent.com/37603562/48454971-566cd200-e7b1-11e8-9ed6-266f40d5a0f5.png)

**Comment by Emulatorer** [comment]
@unknownbrackets didn't happen in v1.7.1-137-g256d5e0b0 it's only started in v1.7.1-141-gdf5fbaef7

**Comment by Emulatorer** [comment]
[ppsspp.txt](https://github.com/hrydgard/ppsspp/files/2585553/ppsspp.txt)
logcat

**Comment by hrydgard** [comment]
Still happening in the latest builds?

**Comment by Emulatorer** [comment]
Same status using latest beta build
![screenshot_2018-11-23-09-29-28](https://user-images.githubusercontent.com/37603562/48946370-6dd05b80-ef25-11e8-9f80-c9fd0030b8bc.png)

**Comment by hrydgard** [comment]
I actually got my hands on this game now. So if you can give me a save or tell me what to do to make it break like this, please do so. Is it easy to get it to happen?

**Comment by hrydgard** [comment]
Thanks.

Ah, so you had "simulate block transfer effects" off when you got the artifacts? You really should have it on for this game (and nearly all other games), that's when the new code will run anyway.

I'm completely baffled as to why you didn't get a huge speedup with it on though. It really should have helped...

**Comment by hrydgard** [comment]
I'll investigate later on my phones and see if I find out something. Because this game should run okay on reasonably-specced phones...

**Comment by hrydgard** [comment]
On my S3 it runs pretty badly but mostly fine on the S8. Still it's slower than I would have expected it to be... probably worth looking into.

**Comment by Emulatorer** [comment]
Sir @hrydgard any update about this?
This will be added in v1.8.0 milestone?

**Comment by hrydgard** [comment]
I don't know how much more there is we can do here, but I'll tag it and take another look later.

**Comment by Emulatorer** [comment]
@hrydgard sir can you add this game Digimon Adventure to RequireBlockTransfer compat.ini to avoid graphics issue in ppsspp v1.8.0?

**Comment by hrydgard** [comment]
It should be there already - if not working for you, tell me the game ID.

**Comment by hrydgard** [comment]
Yeah, I will

**Comment by hrydgard** [comment]
@Emulatorer  done.

**Comment by Emulatorer** [comment]
I think I can close this now because this game demand a powerful device to emulate smoothly in ppsspp 🤔

Sad because my phone is low specs only 😣 I didn't enjoy playing this game in a low fps/speed using the latest build I tried everything :/

So it's time to surrender 🏳 CLOSING?
