### ISSUE TITLE
[Android] [OpenGL] [Mali GPU] Call Of Duty: Road To Victory Lucky Thirteen Mission Graphics Glitches

### ISSUE THREAD

**Issue by Emulatorer** [hrydgard/ppsspp#11573]
### What happens?
Graphical issue in lucky thirteen mission
![screenshot_2018-11-23-00-13-32](https://user-images.githubusercontent.com/37603562/48914350-1671b300-ee73-11e8-98a0-055d19bc0799.png)
![screenshot_2018-11-23-00-14-12](https://user-images.githubusercontent.com/37603562/48914362-21c4de80-ee73-11e8-94b9-063293e279d8.png)

### What *should* happen?
There no violet screen ovelay I think in that mission ?

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Mali-450 MP4 GPU
MT6592 CPU
Android 5.1
PPSSPP v1.7.1-165

**Comment by unknownbrackets** [comment]
Is this a new issue or has it always happened?

A GE frame dump might help, especially if it reproduces when playing the dump (just open it with PPSSPP.)

https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

-[Unknown]

**Comment by Emulatorer** [comment]
@unknownbrackets this always happen even in old version of ppsspp

I can't get GE frame dump maybe waiting for someone who can 😅

**Comment by leopard20** [comment]
@Emulatorer Sure thing. Just give me the save data. I hope you're using the US version?

**Comment by Emulatorer** [comment]
@leopard20 Yes Im using USA :)
here 👉 [ULUS10218COD0000.zip](https://github.com/hrydgard/ppsspp/files/2609478/ULUS10218COD0000.zip)

**Comment by leopard20** [comment]
@Emulatorer 
Strange. I played through the entire mission. Both on Vulkan and OGL. But I didn't notice any issues whatsoever.
![screenshot_2018-11-23-15-27-45-846_org ppsspp ppsspp](https://user-images.githubusercontent.com/16115820/48942421-9dd32b00-ef34-11e8-9559-9ff58b116cf6.png)

**Comment by Emulatorer** [comment]
@leopard20 thank you for testing

Now I face a new graphics issue using ppsspp latest beta build
![screenshot_2018-11-23-20-08-47](https://user-images.githubusercontent.com/37603562/48946241-f13d7d00-ef24-11e8-985f-2d3214f6f42a.png)
[LOAD INGAME]

![screenshot_2018-11-23-20-20-10](https://user-images.githubusercontent.com/37603562/48946260-fef30280-ef24-11e8-9075-a551bb3f94f3.png)
[LOAD VIA SSAVESTATES]

**Comment by Emulatorer** [comment]
@1234Sameer What I need to do?

**Comment by 1234Sameer** [comment]
@Emulatorer 
follow the above guide.
According to the guide you should be able to do this on an android phone without PC if you have PPSSPP 1.7.0 or latter. You have to do this online. I never tried though.

**Comment by leopard20** [comment]
@Emulatorer It's very simple. Just follow this guide:
1. Enable Remote Debugger in settings (it's under Tools->Developer Tools)
2. Open your browser (preferably Chrome or anything based on Chrome, such as Yandex) and go here: http://ppsspp-debugger.unknownbrackets.org/gpu
3. Launch the game. 
4. Just for testing, go back to browser. The page should say that debugger is connected. Otherwise there's something wrong.
5. Play the Luck Thirteen mission.
6. Once you see the issue, go back to browser (Note: DO NOT pause PPSSPP, just use the "Home" or "Recent Apps" button)
7. On that page, press Record.
8. Again go back to PPSSPP. It freezes for a few seconds. Wait until it resumes your game. That means the dump is successfully created.
9. Go back to browser. It should automatically start downloading a file named recording.ppdmp If not change your browser.  
10. Zip the file. Then come back here and upload it (you should switch to Desktop Mode)

**Comment by Emulatorer** [comment]
This is what you want to say?
![screenshot_2018-11-28-14-56-14](https://user-images.githubusercontent.com/37603562/49134246-d24f3a00-f2da-11e8-8b30-0d18f793c9a9.png)
I can't connect always but sometimes connect but freezes the game :v

**Comment by leopard20** [comment]
That freezing is natural. It should go back to normal in a few secs.
BTW, did you see my above comment?

**Comment by Emulatorer** [comment]
So I need to use a chrome browser I currently use UC browser it is not supported for debugging?

**Comment by leopard20** [comment]
I'm not sure about UC. But any browser that uses speed boost techniques (e.g Opera or Yandex with Turbo mode turned on) doesn't work. So chances are UC doesn't work either.

**Comment by leopard20** [comment]
This is how it should be:
![screenshot_2018-11-28-10-43-51-566_com yandex browser](https://user-images.githubusercontent.com/16115820/49134955-94620e00-f2fa-11e8-8db4-b2c68a91940d.png)

**Comment by Emulatorer** [comment]
Thanks @1234Sameer & @leopard20 
OK here we go 👍 thanks again for helping me

[recording.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/2623367/recording.ppdmp.zip)

Im hoping I do it correctly :)

**Comment by unknownbrackets** [comment]
It mostly doesn't matter where it's captured.  The recording records what PPSSPP tries to do, but in some cases will record some of what it actually did (we avoid this as much as possible.)

This game is doing bloom with a series of resize downs to different buffers, but for some reason it's also doing render-to-self in between to blur it a bit.  I'm guessing the render-to-self is the problem here.

Just to confirm: you have "disable slower effects" unchecked, right?  That could definitely cause this behavior.

-[Unknown]

**Comment by Emulatorer** [comment]
@unknownbrackets yes I unchecked the "disable slower effects" in graphics performance settings because when I turn it's on the game turn into a violet screen as you can above screenshot

**Comment by unknownbrackets** [comment]
Right okay.  So this game is using an effect that can't easily be disabled.  That's why - checking that box is a hack.  It can make things faster but it has unavoidable bugs like this.

This is only an issue when "disable slower effects" is checked, right?

-[Unknown]

**Comment by Emulatorer** [comment]
@unknownbrackets Yes Sir

**Comment by unknownbrackets** [comment]
Okay, the most we could do here is explicitly bind a black texture instead of trying to use the render-to-self texture when disabling slow effects.

-[Unknown]

**Comment by 1234Sameer** [comment]
You mean there is no bug when disable slower effect is unchecked?
Please provide screenshots with this option turned off and on.

**Comment by leopard20** [comment]
I think he means that the second set of screenshots occur when it's off, and the purple ones occur when it's on.

**Comment by Emulatorer** [comment]
@leopard20 you are right 👍

**Comment by leopard20** [comment]
Disable Slower effects on:
Vulkan:
![screenshot_2018-11-29-10-02-48-931_org ppsspp ppsspp](https://user-images.githubusercontent.com/16115820/49203590-1a935880-f3be-11e8-8a6c-5c5f8c9e0f6b.png)

OGL:
![screenshot_2018-11-29-10-03-27-045_org ppsspp ppsspp](https://user-images.githubusercontent.com/16115820/49203608-297a0b00-f3be-11e8-9058-0e0286d8b110.png)

**Comment by Emulatorer** [comment]
@leopard20 The game was okay in VK while there's a graphic issue in OGL when "disable slower effects" is on

**Comment by leopard20** [comment]
It wasn't OK, it was too dark.

**Comment by Emulatorer** [comment]
Opps.. Im bad didn't notice that ✌

So it's clear now that "disable slower effects" causes graphics issue both Vulkan & OpenGL

**Comment by Emulatorer** [comment]
### UPDATE
Default Settings
![Screenshot_2019-03-23-23-23-59](https://user-images.githubusercontent.com/37603562/54868047-34203c00-4dc3-11e9-9b13-763dcf563135.png)
Disable Slower Effects (✓)
![Screenshot_2019-03-23-23-24-09](https://user-images.githubusercontent.com/37603562/54868063-531ece00-4dc3-11e9-8532-1e54b35c6b0c.png)

Seems ppsspp v1.8.0 improve the disable slower effects because it wasn't the same as v1.7.5 that make the screen violet when disable slower effects is on

**Comment by unknownbrackets** [comment]
It just disables less effects now.

-[Unknown]

**Comment by hrydgard** [comment]
I think this can be closed, no?

**Comment by unknownbrackets** [comment]
Well, the default settings screenshot above looks a bit off...

-[Unknown]

**Comment by hrydgard** [comment]
Oh oops..

**Comment by Emulatorer** [comment]
![Screenshot_20200303-211728](https://user-images.githubusercontent.com/37603562/75779528-bfa49a00-5d94-11ea-9c6a-a88378fbc675.png)
PPSSPP v1.9.3-367 DEFAULT SETTINGS

![Screenshot_20200303-211738](https://user-images.githubusercontent.com/37603562/75779566-d21ed380-5d94-11ea-8a20-853d92e9e986.png)
PPSSPP v1.9.3-367 DISABLE SLOWER ENABLE

**Comment by Emulatorer** [comment]
Closing this as it's look like a duplicate of #11598
