### ISSUE TITLE
Ppsspp keeps crashing my pc

### ISSUE THREAD

**Issue by garpt** [hrydgard/ppsspp#11582]
I'm using windows 10, latest insider preview, and when i open ppsspp, my pc just feezes for a few seconds, and then gives me the green screen of death.

**Comment by hrydgard** [comment]
Try to update your graphics drivers?

**Comment by unknownbrackets** [comment]
What graphics card are you using?  It's possible this could be a hardware problem - do other emulators and games run fine?

-[Unknown]

**Comment by garpt** [comment]
I'm running an hd 6670, and yes, other emulators run fine, in fact, ppsspp
was running extremely well  before i updated my pc

На сб, 24.11.2018 г., 18:07 Unknown W. Brackets <notifications@github.com
написа:

**Comment by garpt** [comment]
Tried it, my pc still keeps crashing

На сб, 24.11.2018 г., 17:41 Henrik Rydgård <notifications@github.com написа:

**Comment by unknownbrackets** [comment]
Unfortunately, this seems to be an issue multiple people are seeing with the latest Windows 10 insider preview, see #11603.  I'm going to close this for now as it doesn't seem like we can do anything about it.

Apparently even old versions of PPSSPP crash.

-[Unknown]
