### ISSUE TITLE
Queen's Blade Spiral Chaos keeps crashing before battle begins

### ISSUE THREAD

**Issue by PSPDude** [hrydgard/ppsspp#11604]
Before starting the first chapter's battle (once after starting a new game) it keeps crashing

Enemies should start appearing around the map showcasing where they're locating/appearing to.

I'm using Windows 10 64-bit with PPSSPP v1.7.1-204-gd08a2eed6

![screenshot](https://user-images.githubusercontent.com/45407003/49115544-13a70180-f269-11e8-9c1d-69e4d8c6b512.png)

**Comment by PSPDude** [comment]
[crash dump.zip](https://github.com/hrydgard/ppsspp/files/2622075/crash.dump.zip)

**Comment by unknownbrackets** [comment]
Unfortunately, that dump doesn't reproduce the issue, at least on NVIDIA.

-[Unknown]

**Comment by hrydgard** [comment]
Related to #11599, linking bug.

**Comment by unknownbrackets** [comment]
As described in #11599, this may now be fixed with #11613.  It also explains why it doesn't reproduce in the GE frame dump.

Does this still happen in the latest git builds?

-[Unknown]

**Comment by hrydgard** [comment]
Inconclusive, closing.
