### ISSUE TITLE
Go back to APK on Google Play? It seems some custom roms can't handle the new App Bundles

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#11608]
App Bundles ( https://developer.android.com/platform/technology/app-bundle/ ) seems to be poorly supported on some custom Android ROMs, users get errors like this:

![screenshot_20181128-170700](https://user-images.githubusercontent.com/130929/49154778-a1422a00-f319-11e8-8797-d80c88a80b7e.jpg)

Deploying APKs like before is probably a safer option (but does take up unnecessary space on the device).

Though I'd guess the users of these ROMs will soon notice this happening in a lot of other apps....

**Comment by unknownbrackets** [comment]
How common is this?  If not that common, we could adjust the error message to suggest they try a git build if they are using a custom ROM.

-[Unknown]

**Comment by hrydgard** [comment]
I would like to get some kind of confirmation that this only happens on custom roms. But I believe so from the reports I've been getting.

I agree that sending people to download the git builds, or the APK from the website, is probably a better solution indeed, good idea.

**Comment by unknownbrackets** [comment]
Have you gotten many more reports of this?

-[Unknown]

**Comment by hrydgard** [comment]
Nope, closing this
