### ISSUE TITLE
Monster Hunter 3rd Portable HD Graphics Glitches like geometrical probelm

### ISSUE THREAD

**Issue by Emulatorer** [hrydgard/ppsspp#11601]
### What happens?
There are graphical glitch in ppsspp v1.7.1-204 gitbuild
### Screenshot
![screenshot_2018-11-26-18-51-43](https://user-images.githubusercontent.com/37603562/49021732-37941580-f18b-11e8-89a9-9e9f817ad78a.png)

### What *should* happen?
Seems ok in ppsspp v1.7.1-195 beta gitbuild
### Screenshot
![screenshot_2018-11-26-18-51-02](https://user-images.githubusercontent.com/37603562/49021924-9d809d00-f18b-11e8-8fca-db06b848103c.png)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Mali-450 MP4
Android 5.1
2GB RAM

**Comment by Abbanon** [comment]
Myself as well as other users are experiencing identical results on the Windows Git build `204-gd08a2eed6`
This is when the new culling change was implemented that fixed #11593 and #11591 
Before the culling change there is no issue.

GE dump:
https://cdn.discordapp.com/attachments/480103153803460614/516643877642567681/NPJB40001_0001.ppdmp

Screenshot for reference:

![npjb40001_00000](https://user-images.githubusercontent.com/37251822/49025735-49b18c00-f16a-11e8-93b8-a98095fa4ba3.png)

**Comment by hrydgard** [comment]
Thanks for reporting. Should probably have reviewed that change more...

**Comment by unknownbrackets** [comment]
At this point, I guess it means there's a case #11172 doesn't catch?  #11594 just made it flush in the right place.

Maybe it means there's an issue with the cull reversing for non-triangle strips?

https://github.com/hrydgard/ppsspp/pull/11172/files#diff-aadfcd071e41f07936f2d354f1ee44faL1585

@weihuoya what do you think?  You can open the ppdmp files as if they were games, and it will render the scene with basically the same draw commands the game used.

-[Unknown]

**Comment by unknownbrackets** [comment]
I'm actually not able to reproduce this issue with that dump.

Just to lay out a timeline, because I want to make sure there has been no confusion:

 * v1.6.3-497-gead4946fd: "range culling" is implemented which fixes graphical glitches in several games.
 * v1.7.1-188-g4942c52f7: "cull mode flipping" optimization expanded to cover more games.
 * v1.7.1-204-gd08a2eed6: "cull mode flipping" optimization is fixed to flush correctly.
 * v1.7.1-213-g93bb96dbd: [Unknown] cannot reproduce the issue with the GE dump.

If you're able to reproduce this, even when loading the [GE dump above](https://cdn.discordapp.com/attachments/480103153803460614/516643877642567681/NPJB40001_0001.ppdmp) as a game, it may mean this issue is GPU driver specific.

That seems a bit odd since the "cull mode flipping" optimization doesn't seem likely to behave differently on different GPU drivers (unlike the "range culling" feature, which is a bit more dangerous as far as GPU drivers go.)  However, this was reported to happen only starting with v1.7.1-204-gd08a2eed6 which means it's related to "cull mode flipping" - right?

I tried reproducing both on an NVIDIA and Adreno device.

-[Unknown]

**Comment by Peduls** [comment]
![npjb40001_00002](https://user-images.githubusercontent.com/34750422/49263196-b8127a80-f406-11e8-972c-b07cda209884.png)
Just tested on v1.7.1-213-g93bb96dbd and the issue is present for me. I have an NVIDIA GeForce GTX 1070 with the latest drivers.

**Comment by leopard20** [comment]
@unknownbrackets Weird. I tried my own dump just now, but I don't see it either! It turns out that the dump doesn't show the issue. Maybe it's the driver again?!

**Comment by unknownbrackets** [comment]
It seems like it doesn't happen with dumps (except for Peduls?), which is very weird.  However, I have found a way to reproduce the issue.

So far it appears to happen when `newPrim != prim`.  Using this on the prim fixes it:

```c++
			if (newPrim != prim)
				goto bail;
```

It might be an acceptable workaround if the games that benefit from this optimization most don't use different prim types?  I'm guessing something goes wrong with the triangle combining when the prim type switches?

-[Unknown]

**Comment by leopard20** [comment]
I think Peduls is using his own game, not the dump! (look at the names in the screenshots again)

**Comment by Peduls** [comment]
Right, I was just booting the game like normal.

**Comment by Emulatorer** [comment]
Issue still appear :(
### Screenshot
![screenshot_2018-11-30-19-27-25](https://user-images.githubusercontent.com/37603562/49287203-7f20e700-f494-11e8-9edc-cea58c3464f0.png)
### PPSSPP DUMP
[MH3PHD.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/2633052/MH3PHD.ppdmp.zip)

**Comment by leopard20** [comment]
Strange. It's been fixed for me:
![screenshot_2018-11-30-15-12-28-873_org ppsspp ppsspp](https://user-images.githubusercontent.com/16115820/49287367-7939fe80-f4b2-11e8-92d6-6536e3927839.png)
Does it happen in that mission only?

**Comment by Emulatorer** [comment]
Fixes in some maps but only happen in that particular area weird 😅
### Screenshot
![screenshot_2018-11-30-19-54-14](https://user-images.githubusercontent.com/37603562/49288149-dd02fe00-f497-11e8-8783-90a788c1c24c.png)
![screenshot_2018-11-30-19-43-59](https://user-images.githubusercontent.com/37603562/49288181-f73cdc00-f497-11e8-9cbc-7956d376c1fa.png)

**Comment by Emulatorer** [comment]
@leopard20 can you try that mission? (Location Tundra)

**Comment by unknownbrackets** [comment]
Does the tundra area have issues even with older builds?  Maybe it's a separate issue.

It might help to try to create a GE dump of that area, although this issue didn't reproduce super well in dumps...

-[Unknown]

**Comment by leopard20** [comment]
@Emulatorer Sorry I accidentally formatted my phone recently and I've lost all my saved data. I'm playing all games from the beginning. :(
Can you upload your save data for me to test?

**Comment by leopard20** [comment]
@unknownbrackets Yep. I can definitely reproduce from the dump:
https://github.com/hrydgard/ppsspp/files/2633052/MH3PHD.ppdmp.zip
