### ISSUE TITLE
Controller Inputs Dropping

### ISSUE THREAD

**Issue by YvanDroid** [hrydgard/ppsspp#11619]
Inputs sent by an X-input style controller are being dropped, only working half of the time and have significant input lag. This is not a specific game bug but is also occurring in the menus. Using keyboard and mouse are unaffected. Using the Bluetooth functionality also yields the same results, even though Direct inputs shouldn't be affected. 

This occurred after updating from the 1.6.3 release version of PPSSPP. I am currently on Windows 10 build 1809 64bit if that helps. 

Sidenote: I have also troubleshooted the controller by using different inputs and used a gamepad tester and all seem to be working fine.

**Comment by hrydgard** [comment]
Did you try the latest build from http://buildbot.orphis.net/ppsspp/ ?   Because there was a DInput fix committed that could have helped.

**Comment by YvanDroid** [comment]
I will try this and reply back to you with the results.

**Comment by YvanDroid** [comment]
Yes, it does work. Thanks for suggesting the latest build.

**Comment by unknownbrackets** [comment]
Okay, closing since this has already been fixed.  @hrydgard we may want to publish 1.7.4 or 1.7.5 for Windows?

-[Unknown]
