### ISSUE TITLE
Unable to map Dpad on Hori Mini Wired PS4 Controller

### ISSUE THREAD

**Issue by 6alileo** [hrydgard/ppsspp#11617]
I plugged in a keyboard to get to control mapping and the Dpad isn't recognized.

If I use Dual Shock 4 via Bluetooth, it works.

### What happens?
Dpad doesn't work.

### What *should* happen?
Dpad should work.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Odroid XU4, RetroPie and latest build from source.

**Comment by 6alileo** [comment]
I have two wired controllers. I needed to add this to gamecontrollerdb.txt

`03000000380700008532000010010000,MadCatz Madcatz Fightpad,platform:Linux,a:b1,b:b2,y:b3,x:b0,start:b9,guide:b12,back:b8,leftshoulder:b4,rightshoulder:b6,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,lefttrigger:b5,righttrigger:b7,`

`030000000d0f0000ee00000011010000,HORI CO.,LTD. HORIPAD mini4,platform:Linux,a:b1,b:b2,y:b3,x:b0,start:b9,guide:b12,back:b8,leftstick:b10,rightstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b6,righttrigger:b7,`

**Comment by unknownbrackets** [comment]
Thanks for contributing the fix for others.

-[Unknown]
