### ISSUE TITLE
Software renderer handles self-texturing incorrectly

### ISSUE THREAD

**Issue by unknownbrackets** [hrydgard/ppsspp#11623]
An example can be seen in Motorstorm.  The game renders to 0x04000000 at about 512x290, then scales it down (0x04000000 -> 0x04000000) to 480x272.  It does this in vertical strips.

This runs into a couple problems:

1. We run multiple threads, which causes some hazards if the parts below run in parallel (or if strips to the right if we queued prims at all.)
2. Even without that, streaks are visible when we've partially rendered a block when texture sampling from it.

The solution to this is probably to implement a texture cache in the software renderer.  A simple way might be to simply copy the entire texture to a temporary if rendering within the target (although this would be inaccurate in some cases...)

We could also try to implement the texture cache more precisely, but not sure we could do the threading or etc. then.  Someone on the internet going by chp says:

> You are correct, the texture cache is VERY important on the PSP (as it was on the PS2). From experiments it seems to be 8kB, so that means it's 64x32 in 32-bit, 64x64 in 16-bit, 128x64 in 8-bit and 128x128 in 4-bit (the sizes are qualified guesses by looking at the PS2). Ordering your draws so that locality in uv-coordinates is maximized will make sure your rendering is optimal.
>
> And yes, DXTn is decompressed into 32-bit when loaded into the cache, so what you gain in shrinking the texture-size, you lose in texture-cache. If you can, use 4- or 8-bit textures, which will allow a much larger area to be kept in the cache.

That said, I did try briefly redirecting all textures to a temp cache, and disabling threading - it didn't work because I did it at the triangle level.

GE dump: [UCUS98743_#11623_motorstorm_self_render.zip](https://github.com/hrydgard/ppsspp/files/2637106/UCUS98743_.11623_motorstorm_self_render.zip)

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, it's one of those things that's not "supposed" to work but actually works perfectly fine on the hardware due to the inner workings of the texture cache. Quite nasty...
