### ISSUE TITLE
(GLES) ppsspp is always full screen with SDL2

### ISSUE THREAD

**Issue by orbea** [hrydgard/ppsspp#11627]
### What happens?

When using the SDL front end with OpenGL ES 2.0 (`-DUSING_GLES2=ON`) ppsspp has two issues with full screen support.

- [ ] ppsspp will always start full screen.
- [ ] Toggling the full screen setting in the ui does nothing and ppsspp will remain full screen.

This issue is not present with OpenGL or Vulkan and the SDL front end. Its also not an issue with the Qt front end and OpenGL ES.

### What *should* happen?

The full screen setting should work immediately and without issues while using OpenGL ES 2.0.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

OS: `Slackware64-current`
Linux: `4.19.5`
ppsspp: https://github.com/hrydgard/ppsspp/commit/95ffa15a842730e8ddc467d28d50d7995e258c13
mesa: https://github.com/mesa3d/mesa/commit/94bfb8bf386b560e8e6095727ed1cf08522a027d
SDL: `2.0.9`
vulkan-sdk: `1.1.92.1`
GPU: `AMD RX Vega 56` (amdgpu + radeonsi)
```
$ glxinfo | grep Core
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.0.0-devel (git-94bfb8bf38)
```

**Comment by unknownbrackets** [comment]
It's intentional currently:

https://github.com/hrydgard/ppsspp/blob/57bf9e3048dbc3ddb24d7332701db8a3b7dde2cb/SDL/SDLMain.cpp#L443-L445

-[Unknown]

**Comment by orbea** [comment]
I suppose its making the assumption that no one will ever try to use GLES on a desktop. :)

**Comment by orbea** [comment]
This works here, would it be that easy?
```
diff --git a/SDL/SDLMain.cpp b/SDL/SDLMain.cpp
index 6dd6d2242..db786c3f1 100644
--- a/SDL/SDLMain.cpp
+++ b/SDL/SDLMain.cpp
@@ -441,7 +441,7 @@ int main(int argc, char *argv[]) {
        }
 
        // If we're on mobile, don't try for windowed either.
-#if defined(USING_GLES2) || defined(MOBILE_DEVICE)
+#if defined(MOBILE_DEVICE)
     mode |= SDL_WINDOW_FULLSCREEN;
 #else
     mode |= SDL_WINDOW_RESIZABLE;
```
I am not sure if there are any devices that would be using GLES and toggling full screen would be detrimental that are not defined under `MOBILE_DEVICE`.

**Comment by orbea** [comment]
I think `MOBILE_DEVICE` is correctly set for android and IOS so this should be safe there, are there any other platforms to worry about?

**Comment by orbea** [comment]
Further full screen issues with OpenGL ES and SDL are covered in issue https://github.com/hrydgard/ppsspp/issues/11625.
