### ISSUE TITLE
Direct3D 9 does not display images of 3D games on Nvidia GPU

### ISSUE THREAD

**Issue by teorex3** [hrydgard/ppsspp#11638]
I have a graphical issues after implementing vertex range culling #11393

Tested on:
ppsspp-v1.6.3-472 - working OK
ppsspp-v1.6.3-478 - NOT working
ppsspp-v1.7.4 - NOT working

GPU: Nvidia 7600 GT

![ppsspp v1-7-4 - npuh10125 - final fantasy iii](https://user-images.githubusercontent.com/35883258/49466528-63f60480-f811-11e8-8954-5d28157a5119.jpg)

maybe this is help too?..
https://github.com/hrydgard/ppsspp/issues/11477#issuecomment-431645540

**Comment by hrydgard** [comment]
Strange. I guess we'll have to turn it off on older NVIDIAs as well indeed..

**Comment by hrydgard** [comment]
@teorex3  But the menus work, right? If you go into Settings/Tools/System Information and look at the Vendor line, what does it say exactly?  Would need to look there to detect old NVIDIAs in D3D9 I think...

**Comment by teorex3** [comment]
![ppsspp v1-7-4 - npuh10125 - final fantasy iii](https://user-images.githubusercontent.com/35883258/49645359-a3e50380-fa2c-11e8-9d3e-685e5eb97e29.jpg)
This report from OpenGL Extensions Viewer, also contains information about D3D:
[report.txt](https://github.com/hrydgard/ppsspp/files/2657053/report.txt)

**Comment by hrydgard** [comment]
Thanks, I'm gonna try to make something to detect old Geforces, working around this problem.

Anyway, any particular reason you're using D3D9? D3D11 should work better for you.

**Comment by teorex3** [comment]
One reason is no support D3D11 on NVIDIA 6xx, 7xx, if i run with D3D11 plugin, I get APPCRASH PPSSPPWindows.exe error.

**Comment by hrydgard** [comment]
You mean 6xxx, 7xxx. But crashing is unexpected... Darn.

**Comment by unknownbrackets** [comment]
It probably means we're doing something that isn't supported on feature level 9?  Could be npot textures or separate alpha blend at 9_1, even...?

Unfortunately, I don't have anything older than 8xxx.

Try turning off settings: hardware transform, hardware tessellation, anisotropic, maybe even skip buffer effects.  If any of these help, it'll help us narrow down the cause.

-[Unknown]

**Comment by unknownbrackets** [comment]
It seems like we use ps_4_0_level_9_1 on D3D11 with < 9.3 support, but then try to use some higher level features anyway (like bitwise shader ops.)  This appears to affect UWP.

-[Unknown]

**Comment by hrydgard** [comment]
@unknownbrackets We don't expose D3D11-feature-level-9 except on UWP, this is an issue about real D3D9 problems, so not related. But yes, we probably have a few cases like that...

**Comment by unknownbrackets** [comment]
I was referring to "if i run with D3D11 plugin, I get APPCRASH PPSSPPWindows.exe error."

I wonder though if setting w to 0 would more likely work.  That it breaks rendering even that shouldn't be culled implies to me that it just has trouble because a nan is involved in the conditional.

-[Unknown]

**Comment by unknownbrackets** [comment]
Has this improved?

-[Unknown]

**Comment by teorex3** [comment]
yes it helped
ppsspp-v1.7.5-430 - working OK

**Comment by hrydgard** [comment]
Thanks for testing!
