### ISSUE TITLE
Ppsspp crash in xiaomi device

### ISSUE THREAD

**Issue by dikorommel** [hrydgard/ppsspp#11636]
Log:
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/rolex/rolex:7.1.2/N2G47H/V10.1.1.0.NCCMIFI:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 13334, tid: 13352, name: Emu  >>> org.ppsspp.ppsspp <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x2300000000
    x0   0000007f87d900e0  x1   000000000152bec0  x2   00000000ffffffff  x3   0000000000000000
    x4   0000000000000000  x5   00000000ffffffff  x6   00000000ffffffff  x7   0000000000000000
    x8   0000007f8f63c3d0  x9   0000000000013aa0  x10  000000000000ec80  x11  0000000000013aa0
    x12  0000000005f5e100  x13  0000007f8f63bff0  x14  000000000002cd80  x15  0019af099a79149e
    x16  0000000000000000  x17  0000000000000000  x18  0000000000015180  x19  0000002300000000
    x20  0000000000000000  x21  0000000000000000  x22  0000000000000000  x23  0000000000000000
    x24  0000000000013aa0  x25  00000000000fd000  x26  0000007f87d90000  x27  0000007f8f63bff0
    x28  0000002300000000  x29  0000007f8d9ff050  x30  0000007f87d90140
    sp   0000007f8d9ff050  pc   0000007f87d9016c  pstate 0000000060000000

backtrace:
    #00 pc 000000000000016c  <anonymous:0000007f87d90000>
    #01 pc 000000000000013c  <anonymous:0000007f87d90000>

**Comment by Emulatorer** [comment]
### What xiaomi phone and what ppsspo version is crashing?

**Comment by dikorommel** [comment]
Xiaomi redmi 4A
Ppsspp 1.7.1

**Comment by hrydgard** [comment]
When does it happen? On startup or when starting some game, if so which game?

**Comment by dikorommel** [comment]
On startup

**Comment by hrydgard** [comment]
Unfortunately that stack trace isn't very helpful. Is anything else printed in the log that looks like it's from PPSSPP?

**Comment by leopard20** [comment]
As far as I know, this error is kind of similar to "access violation". 
@dikorommel 
Can you try the latest dev build?
Also, try opening app settings and grant storage permission (this shouldn't cause a crash. but you never know!)

**Comment by hrydgard** [comment]
How is this on the latest builds now?

**Comment by Narugakuruga** [comment]
Fixed.

**Comment by hrydgard** [comment]
I'm gonna assume this is fixed.

**Comment by robirooorbi** [comment]
How to fix these, please somebody help :"< 

I got the same situation, it crashes before the game even started! Crash commands as well..

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'xiaomi/tulip/tulip:8.1.0/OPM1.171019.011/V10.2.1.0.OEKMIXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 23619, tid: 23686, name: Emu  >>> org.ppsspp.ppsspp <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x2300000010
    x0   0000002300000010  x1   00000000088758ac  x2   0000000000000001  x3   0000000000000003
    x4   0000000000000000  x5   0000007a02713f48  x6   ffffffffffffffff  x7   0000000000000000
    x8   0000000000000000  x9   00000079fd0187c0  x10  0000000000000040  x11  ffffffffffffffc0
    x12  00000079fd0187c0  x13  0000000000000040  x14  0000000000000040  x15  0000000000000040
    x16  00000079fd018760  x17  0000000000000068  x18  0000000000000411  x19  0000002309fff3c0
    x20  0000000008ab0000  x21  0000000008ab4680  x22  0000000009bb4f58  x23  00000000088fbd34
    x24  0000000000004cc9  x25  0000007a0382d7a0  x26  00000079fd000000  x27  0000007a0381ca70
    x28  0000002300000000  x29  0000007a02714100  x30  00000079fd00019c
    sp   0000007a02714100  pc   00000079fd018768  pstate 0000000060000000

backtrace:
    #00 pc 0000000000018768  <anonymous:00000079fd000000>
    #01 pc 0000000000000198  <anonymous:00000079fd000000>

**Comment by robirooorbi** [comment]
Xiaomi Phone
Redmi Note 6 Pro

**Comment by unknownbrackets** [comment]
It's important to report:

 * What game are you running?
 * Where does it happen in the game?  What steps should someone take to get the same problem?
 * Does it happen every time?
 * Are you using cheats?
 * Does it happen with default settings?

-[Unknown]

**Comment by leopard20** [comment]
@robirooorbi This doesn't seem to be related to ths emulator. Perhaps the game ROM is corrupt (I've personally received this exact error when I use a cheat that attempts access an invalid memory address, and also a couple of times when I used bad DLCs). Have you tested any other games?
