### ISSUE TITLE
New git branch tagging scheme

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#11639]
For 1.7 I had to make a side branch for some hotfixes, and I expect to have to do the same again occasionally.

The side branch, 1.7-hotfixes, now has a latest tag of "v1.7.5" while the main branch, which the buildbot builds, is still called "v1.7.1-xxx". This confuses some people into thinking the main branch isn't up to date (although probably not a lot of them). 

Maybe after a release of say 1.7 we should immediately put a tag "v1.8-wip" or something on the main branch?

**Comment by unknownbrackets** [comment]
Hm, right now that would cause reporting to get confused at least, since it would calculate v1.8-wip-500-gabcde123 as newer than v1.8.0.  And I think humans might run into the same confusion.

We could do a merge -s ours of 1.7 hotfixes, does that make it start numbering from 1.7.5?

-[Unknown]

**Comment by hrydgard** [comment]
Yes, that does seem to fix the numbering. Will consider that.

**Comment by unknownbrackets** [comment]
Is this working well enough now, or do we want to revisit for 1.8.x?

-[Unknown]

**Comment by hrydgard** [comment]
Seems alright... Well, except for https://github.com/hrydgard/ppsspp/issues/10837 but that seems to be a more specific thing.
