### ISSUE TITLE
Can't change the CPU Core

### ISSUE THREAD

**Issue by mygizli04** [hrydgard/ppsspp#11646]
### What happens?
When changing CPU Core, the changes don't work. I see no performance/graphical change whatsoever, and a reset doesn't help. ( Yes, i'm sure i'm changing it properly. )

### What *should* happen?
CPU Core should be changed.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
iPhone 6, iOS 12.0.1 ( not jailbroken, obviously ), version 1.6.3-456-g6d0ed4a

**Comment by mygizli04** [comment]
No, the other issues on the same problem all say to reset, which doesn't fix my problem so it's not a duplicate.

**Comment by LunaMoo** [comment]
Currently iOS is the worst platform for more complex emulators, JIT will not work, the only cpu cores you can pick are interpreter and IR interpreter, the latter might be faster, but whenever the speed improve would be noticeable also differ per game.
 
  If I recall fully/safe changing cpu core required restart without reloading from savestates. If you have low fps and changing to interpreter IR from interpreter doesn't help(doing the opposite surely will not and JIT will not work on your OS), you might as well be limited by gpu, gpu drivers or system throttling(mobile OS's will never allow the device to run at it's full specs all the time and unknown apps might even be intentionally limited).

**Comment by unknownbrackets** [comment]
This is better to discuss on the forum or Discord - there doesn't seem to be a bug in the CPU core change feature, it's just not enabling some "magic mode" you expect that makes it run all games at 60 FPS on your phone.

Unfortunately, no one knows how to create such a magic mode at this time, but if you can figure out the recipe (not just the idea of it maybe existing, but how to actually make it), we'd be glad to hear it.

-[Unknown]
