### ISSUE TITLE
Suicide Barbie demo not work in Windows

### ISSUE THREAD

**Issue by UnknownLocation** [hrydgard/ppsspp#11648]
### What happens?

Black screen, information on screenshot. However, the demo works great on Android and I like the music which used.

![screenshot 22](https://user-images.githubusercontent.com/24863635/49681032-7cce1680-faac-11e8-8d95-5c4f02e4cdb3.png)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

PPSSPP 1.7.4 / Windows 10 1607 64-bit / Intel Core i5 2410M / AMD Radeon 6600M (Switchable)

**Comment by unknownbrackets** [comment]
Make sure it's in PSP/GAME/.  Homebrew often were built to be in a specific folder on the PSP, and wouldn't work if you put them in "ms0:/Games/Homebrew/My Stuff/Cool" on a real PSP either.

-[Unknown]

**Comment by firodj** [comment]
I've same problem with PPSSPP on MacOS and already fixing it by remove PPSSPP User files (assets, flash0, etc.). Sorry, I don't know which files that makes the Barbie Suicide cannot run. On Mac and Linux, it's in `~/.config/PPSSPP`.

**Comment by UnknownLocation** [comment]
I tried everything (renamed/deleted demo/PPSSPP folder) - nothing helps.

**Comment by unknownbrackets** [comment]
Is this working now since #11788?

-[Unknown]

**Comment by UnknownLocation** [comment]
Build [v1.7.5-476-g01f0f3e86](https://buildbot.orphis.net/ppsspp/index.php?m=dl&rev=v1.7.5-476-g01f0f3e86&platform=windows-amd64) works great.

**Comment by hrydgard** [comment]
@unknownbrackets , related, currently a lot of people who have used PPSSPP for some time will have PSPFirmware =150 while all new users will get PSPFirmware = 660. 

I'm thinking we should just hardcode it to 660, to avoid this kind of hard-to-reproduce bugs. Opinions?

**Comment by unknownbrackets** [comment]
All our pspautotests, at least that I've created, are against 6.60.  I think it was made configurable in #4816 for the purpose of sometimes making it 6.60 anyway.

-[Unknown]

**Comment by hrydgard** [comment]
Right. We should probably just rename the setting to bump everyone forward to 660, and leave it configurable in case there's actually a use for it.
