### ISSUE TITLE
Remote disc streaming crashes

### ISSUE THREAD

**Issue by mygizli04** [hrydgard/ppsspp#11647]
### What happens?
When trying to start remote disc streaming in Ubuntu PPSSPP just crashes ( it just exits for some reason), it works fine when i do it on a host-only network. Well i'm not waiting support for that since i'm using parallels ( Virtual Machine ) to use Ubuntu. When on iOS trying to stream it works fine, but i can't browse games since that crashes PPSSPP ( and causes issue #11645 in the proccess )

### What *should* happen?
It should start remote disc streaming

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Intel i5 1,8 ghZ, 8 GB RAM, Intel HD Graphics 6000, Ubuntu ( emulated, host is macOS 10.14 ), version 1.6.3-456-g6d0ed4a

iPhone 6, iOS 12.0.1 ( not jailbroken, obviously ), version 1.6.3-456-g6d0ed4a

**Comment by unknownbrackets** [comment]
I assume it doesn't crash when you run it directly from Mac?

Can you try getting a stack trace of the crash from gdb?  There are some instructions here:
https://github.com/hrydgard/ppsspp/issues/11312#issuecomment-415439829

It could be some interaction with AppArmor, I guess.

-[Unknown]

**Comment by mygizli04** [comment]
Here's the stack trace:
#0  0x00007ffff7bca9ff in __libc_send (fd=18, buf=0x7fffc0003550, n=167, 
    flags=0) at ../sysdeps/unix/sysv/linux/x86_64/send.c:26
#1  0x000000000084bf4e in Buffer::FlushSocket(unsigned long) ()
#2  0x0000000000875812 in http::Client::GET(char const*, Buffer*, std::vector<std::string, std::allocator<std::string> >&, float*, bool*) ()
#3  0x0000000000875963 in http::Client::GET(char const*, Buffer*, float*, bool*) ()
#4  0x000000000051238c in RegisterServer(int) ()
#5  0x00000000005126a1 in ExecuteWebServer() ()
#6  0x00007ffff6a31c80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff7bc16ba in start_thread (arg=0x7fffe4ed3700)
    at pthread_create.c:333
#8  0x00007ffff61973dd in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Also i don't want to install ppsspp directly on my mac beacuse i share this mac and don't wanna install any public things e.g homebrew

**Comment by mygizli04** [comment]
Update: I just tried with the latest git build. The issue doesn't happen anymore. I don't know how i can close a issue though :/

**Comment by unknownbrackets** [comment]
Ah, didn't realize you were running an older version than #11475, was probably just the SIGPIPE issue.

-[Unknown]
