### ISSUE TITLE
PPSSPP Crashing upon launch (windows, vulkan)

### ISSUE THREAD

**Issue by FusionX22** [hrydgard/ppsspp#11654]
After playing FF3 for a bit the program shut down.  

Everytime I went to open up the emulator, it would open the window to a black screen then shut completely back down.

After speaking with Abbanon, I went into the ppsspp.ini and changed the Backend to 0, 1, 2 to revert it away from defaulting to Vulkan.  I have a NVIDIA graphics.  After attempting all 3, I would eventually get the program to launch, but after starting a game, it would crash again and revert the settings back to default.

**Comment by FusionX22** [comment]
I will attempt those solutions a little later on this evening after I return home from work.  I will then comment with any changes or updates after then!  Thank you for looking deeper into this, as I am very much aware this is an annoyance more so than an issue.  

Also, just a tidbit, I normally NEVER run the program as an Administrator.  I HAVE extracted PPSSPP to multiple different locations (albeit C:/ or D:/) and also to the desktop and program file locations.  

But, as I said, I'll attempt these fixes later and will post an update following that!  Thank you guys.

**Comment by hrydgard** [comment]
How is this now with the latest builds?

**Comment by hrydgard** [comment]
Hopefully #11802 has taken care of this. In the meantime, this has cropped up in the Khronos issue tracker: https://github.com/KhronosGroup/Vulkan-Loader/issues/182
