### ISSUE TITLE
Trying to change nickname crashes on Mac?

### ISSUE THREAD

**Issue by mygizli04** [hrydgard/ppsspp#11653]
### What happens?
When clicked "change nickname" the application crashes.

### What *should* happen?
A prompt asking for the new nickname should appear.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
MacBook Air 2017 model, macOS 10.14, v1.7.1-250-ge4b887cc4

[Here's the crash report (generated by MacOS)](https://pastebin.com/cLp2wcRj)

**Comment by hrydgard** [comment]
Hm, this would probably crash on Qt for Linux as well. It's probably another of those cases where the threading of the GL renderer isn't taken into account in the Qt code.

**Comment by mygizli04** [comment]
It works but i get some temporary artifact effects when trying to type... It's not a huge problem but it's there. https://youtu.be/LM1-P1T0r7c

**Comment by hrydgard** [comment]
Yeah, I noticed those too. I'll try to get them fixed when I take care of #11271
