### ISSUE TITLE
Is Vulkan support temporarily disabled?

### ISSUE THREAD

**Issue by xebra** [hrydgard/ppsspp#11657]
I'm confusing a bit because I can't change the backend to Vulkan from internal menu but I can select Vulkan from Windows menu. However, it causes initialize error even if I selected the menu.

![-1](https://user-images.githubusercontent.com/1607422/49781463-2ab01e00-fd56-11e8-9585-a6f7e4bc01e0.jpg)
![-2](https://user-images.githubusercontent.com/1607422/49781464-2ab01e00-fd56-11e8-9f61-2f0e386e6217.jpg)

**Comment by unknownbrackets** [comment]
Normally, we try to initialize it in a quick way, and if that fails, hide it from the Backend menu.  Maybe that's just not working for the Windows menu.

But I think this means your graphics driver is having problems initializing Vulkan - did you update it recently?

-[Unknown]

**Comment by xebra** [comment]
No, I have nothing changed about graphics device and driver recently.
Hmm it's weird.

**Comment by unknownbrackets** [comment]
Maybe try installing the latest SDK and runtime?  https://vulkan.lunarg.com/sdk/home#windows

Does it give any details on the initialize error when you select Vulkan?

-[Unknown]

**Comment by xebra** [comment]
Ah, I remembered that I uninstalled VulkanSDK recently.
Sorry, I will try to reinstall the runtime.
I will report a result later, thanks!

**Comment by xebra** [comment]
The error message is here.
![-3](https://user-images.githubusercontent.com/1607422/49783481-47038900-fd5d-11e8-8986-240e9bbf2e0e.jpg)

**Comment by xebra** [comment]
I solved Vulkan backend issue with reinstall it.
And thank you for fixing the menu.
