### ISSUE TITLE
GLES (GBM) rendering size is wrong

### ISSUE THREAD

**Issue by mrfixit2001** [hrydgard/ppsspp#11651]
I haven't had time to troubleshoot this, but I wanted to get the issue on your radar... 

I can confirm that sometime between November 18 (commit fed779e21a22dabec1c068c34be64c5c3b8a57ab) and today the framebuffer size is not always the same as the screen's resolution. When I build from the master commit today the game is rendered in the lower left corner of my screen with the rest of it black, but the screen's resolution is set to 720p. When I build the commit I referenced above from November 18, the game renders correctly as the full resolution. I am compiled on ARMV7 with no vulkan, no X11, no QT, and no wayland. No other emulators or video players behave this way.

As time allows I will gather some logs for you, but right now I'm strapped for time as I'm working to include this in the next recalbox release. So if you aren't able to reproduce the issue, let me know what you'd like me to gather and I'll try and get some of the detail for you.

**Comment by 6alileo** [comment]
Happens on Odroid XU4 running RetroPie as well.

**Comment by AreaScout** [comment]
The solution to this is probably to start with ``./PPSSPPSDL --fullscreen`` or to add -DMOBILE_DEVICE=ON to your cmake command line

**Comment by 6alileo** [comment]
`--fullscreen` worked. Thank you! @AreaScout

**Comment by unknownbrackets** [comment]
Is this resolved by #11806?

-[Unknown]

**Comment by mrfixit2001** [comment]
Yes I believe so. I've already added the full screen parameter as well, so good to close. Thanks so much for the follow up and hard work!
