### ISSUE TITLE
Remove Cardboard stereo rendering

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#11668]
Is anyone actually using this, or is it just something somebody implemented for fun?

I don't really see much point to be honest, especially since we're not doing real stereo rendering anyway...

**Comment by marosis** [comment]
No i don't.

**Comment by JimsAlliance** [comment]
Where can I enable this?

**Comment by unknownbrackets** [comment]
I wouldn't miss it.

It's under graphics settings, and causes a "silver screen" effect where there's a projected 2d screen where the game is rendered.

-[Unknown]

**Comment by JimsAlliance** [comment]
> It's under graphics settings, and causes a "silver screen" effect where there's a projected 2d screen where the game is rendered.

If you like VR gaming that is the best way to support it without an actual VR mode. I don't game much on mobile because my gamepads are incompatible, but I would definitely use it otherwise. I wouldn't remove it as I'm sure there are VR gamers out there who use it regularly.

**Comment by mygizli04** [comment]
I mean this is great for people who want to experience PSP games in VR but don't wanna spend too much money... And no reason for removing it right?

**Comment by weihuoya** [comment]
I think play psp game with this "fake" VR mode is a bad experience. these settings are not useful in my opinion.

**Comment by LunaMoo** [comment]
Playing with "real VR" would be even worse as PSP games were not designed with VR in mind, that feature wasn't either.

 The point was to use tiny screen placed in front of the eyes to simulate big screen. For such use separate image for each eye is pretty neat doesn't matter if they are exactly same, but if it's super rare it could be degraded to ini-only setting as the clutter in UI it causes is pretty serious, even people who could use it regulary, shouldn't have need to switch it's settings all the time.

**Comment by hrydgard** [comment]
Unlike some of the other settings I want to remove at least this one doesn't cause compatibility problems, so it's not as big of a win to remove it, just getting rid of a little bit of code and UI clutter. 

I'll leave this issue around for comments for a while longer before making a decision.

**Comment by Emulatorer** [comment]
@hrydgard Sir what the use of "Rewind Snapshot Frequency (mem hog) in system?

*Sorry for asking Im just curious

**Comment by unknownbrackets** [comment]
It basically makes PPSSPP create an internal save state every so often (e.g. every second or every minute.)  Then you can press a button to rewind backwards.  Let's say you were platforming and you fell off a cliff - you press rewind and try the cliff again.

-[Unknown]

**Comment by Emulatorer** [comment]
@unknownbrackets thanks for info about that 👍

**Comment by Emulatorer** [comment]
The hack setting "Lower Resolution For Effects (Reduce Artifacts)" should  also be removed I didn't use that and no performance improvement :/ (imo)

**Comment by hrydgard** [comment]
@Emulatorer  That hack setting fixes bloom effect in a few games (they use bilinear filter to blur, which doesn't work if the resolution is too high).

Although, it could be argued that we should just force it on where needed using compat.ini.

**Comment by Emulatorer** [comment]
Yup it's better in compat.ini than a check box in ui

**Comment by hrydgard** [comment]
God another confused email where a user accidentally enabled it.

I think this feature does more harm than good at this point, and I am going to kill it off.

**Comment by 94svtbird** [comment]
I just spend about 15 minutes trying to find the cardboard enable setting only to stumble upon this thread. Thanks for all the hard work everyone. I use PPSSPP with Legacy Doom and Gear VR. Its ok I can just use the last version. I feel like the code could have just been left in there. But as is life, the dumb ones ruin it for the rest of us.

**Comment by LunaMoo** [comment]
@94svtbird just use the latest version(not last release), this was re-added two weeks ago.

**Comment by Jamrrad** [comment]
Uhm, where did the cardboard vr setting go? That's the only reason I support this emulator. I play with a pocket vr clipped to a hat visor. Why the hell would anyone want to play this emulator without this feature?!!!

**Comment by unknownbrackets** [comment]
Update to the latest git build, it has returned.  See the comment right above yours.

-[Unknown]

**Comment by Jamrrad** [comment]
Ya, thanks for that and huge thanks to everyone who works on PPSSPP. Will this be coming back to the official play store build though? 🥺

**Comment by hrydgard** [comment]
Yes, what's in the git builds is the progress towards the next release.

**Comment by Jamrrad** [comment]
Cool 😎*total newb*
...Here's why the vr option is a must for me... www.virtualvizor.com .... pairing a visor headset with a steel series stratus on PPSSPP is still one of the best pocket VR experiences out there.

**Comment by hrydgard** [comment]
haha yeah that's like a cardboard without the cardboard, cool

**Comment by Jamrrad** [comment]
Heck ya, I never leave home without a pocket visor VR. Well atleast until the "Mojo Lense" is commercialized or something. I'll still likely use it even then though. I have a different custom made pocket visor VR that I use primarily too because it works with curved hat visors as well as flat visors. It's being tailored for the 3D printing community and I'd be happy to link it to y'all when its done!

**Comment by hrydgard** [comment]
I got a 3D printer, but I guess I'd still need to get some lenses, those won't print well even with transparent PETG :D

**Comment by Jamrrad** [comment]
Ya lol, a CNC router can create lenses though! Lenses are pretty cheap too. The pocket headset I'm creating for 3d printing is capable of interchangeable lenses. I'm coupling the creation as a GearVR mod, so the lenses from GearVR can be used and the GearVR circuitry is then minimized to fit into a pocket as well! This works really well as a wireless display for windows through the gearvr virtual desktop app. Other headsets don't allow a person to see their hands for typing and multitasking. The open peripheral view on this type of headset and its portability is extremely useful!
