### ISSUE TITLE
Tales of phantasia x Vulkan graphic issue 

### ISSUE THREAD

**Issue by asbel123** [hrydgard/ppsspp#11671]

**Comment by asbel123** [comment]
Hey do U remove stencil test that's fix for that game on Android Samsung galaxy s8 and s9 fix that's U can't see the text and grAphics

**Comment by asbel123** [comment]
Vulkan issue not OpenGL issue

**Comment by asbel123** [comment]
OpenGL works too very slow

**Comment by Emulatorer** [comment]
Could you try exporting a GE frame dump? These help a lot.

See here for instructions - it's not hard and works on Android too:

https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

**Comment by unknownbrackets** [comment]
This isn't enough information.  Can you post screenshots and try to say more about the issue?  It's okay to use Google Translate - even if the text is a bit wrong, it's better than no text at all.

-[Unknown]

**Comment by Gamemulatorer** [comment]
@hrydgard this is a duplicate of #12890

**Comment by Gamemulatorer** [comment]
@sum2012 this is duplicate of #12890

**Comment by hrydgard** [comment]
Duplicate of #12890
