### ISSUE TITLE
Mega Man Legends 2: Long Menu Hangs

### ISSUE THREAD

**Issue by JMC47** [hrydgard/ppsspp#11672]
### What happens?

Mega Man Legends 2 (Or Rockman Dash 2 as is the Japanese name) has very irregular behaviors on the menu depending on the **in-game** aspect ratio option.  On 4:3 mode, the main menu displays *emulated* lag, as if the game itself is lagging on the emulator.  You can see this with very janky transition animations.

This does not happen in 16:9 mode, it displays a Solid 60/60 in the main menu when using the game's 16:9 mode.  Unfortunately, when in this mode, the game *loves* to hang for 20+ seconds on transitions, making it very, very difficult to do speedruns considering it likes to do this when loading the game the first time.

I've tried all of the timing options and emulated CPU clock override to try and fix it.

### What *should* happen?

While I don't personally have the equipment to test this, other runners in the community run on console and these behaviors do not happen.  The menus don't seem to lag in 4:3 mode, and they definitely do not hang on 16:9 mode when using PSTV.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

We've seen this exhibited across half a dozen computers.  My computer is a Core i7-6700K, GTX 1070, Windows 10.  I've tried having the ISO stored on my solid-state and preloaded into RAM via the available option to avoid the menu hangs.  The menu hangs **never** happen in 4:3 mode, but, the menus do run at a lower framerate and the in-game music seems to struggle a bit (though, it's running 100% speed, just 49/49 instead of 60/60)

**Comment by JMC47** [comment]
I forgot to mention that this happens in 1.7.1 and the latest development builds.

Runners did mention that this did not used to happen ~2 years ago, but, I haven't been able to pinpoint a build yet.

**Comment by JMC47** [comment]
It seems some God of War hack in the menu causes this.  I don't remember enabling it, so, maybe this game needs it disabled by default?

**Comment by hrydgard** [comment]
Oh, interesting! Yeah, that hack has issues... It might be time to forcibly limit it to just the GoW games.

**Comment by Gamemulatorer** [comment]
How about now?

**Comment by unknownbrackets** [comment]
I think that hack is no longer enabled for this game, so it probably has improved.

-[Unknown]
