### ISSUE TITLE
ONLY ASK NOT ISSUE!!!!

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#11673]
Firstly hello @hrydgard! i have one Fast ask. Of course yeah PPSSPP still a lot of work and not everything work perfect. But that what you and PPSSPP team did @LunaMoo, @UnknownBrackets and another and another over years Is AWESOME! You guys Are AWESOME! I playing on PSP emulator over 3 years and i still not supported you  by buying gold version. Iam f***ing PLEB. NOW THAT ASK: Will you ever start to do PS2 emulator? today Is a lot of smartphone's what have enough strong hardware for playing games on 30fps. Yeah here is one good emulator (D*mon) but this isn't emulator! This is f*cking copy of PCSX2 And from half of your PPSSPP code.

**Comment by Emulatorer** [comment]
Play! is already a PS2 emulator for android but is still under development but the most stable is the DamonPS2 so I think the PPSSPP has no plan for that :) (imo)

**Comment by marosis** [comment]
@Emulatorer PLAY! Emulator is super slow over 2 years. Damon Is maybe 4x Faster than play!

**Comment by Emulatorer** [comment]
Then use DamonPS2 :/

**Comment by Abbanon** [comment]
I believe something of this nature belongs in the forums, not here...

**Comment by Emulatorer** [comment]
@Abbanon I agree

**Comment by Emulatorer** [comment]
@marosis here 👉 https://www.ppsspp.org

**Comment by marosis** [comment]
?

**Comment by hrydgard** [comment]
Thanks for the appreciation! Closing though because this isn't an issue :)

**Comment by marosis** [comment]
Of course close it but i still don't know answer:(

**Comment by hrydgard** [comment]
I have no plans to work on the PS2 at present, sorry.
