### ISSUE TITLE
Real time speed on main thread

### ISSUE THREAD

**Issue by InfamousKnight** [hrydgard/ppsspp#11688]
Linux problem only:

I opened an issue about something similar before, but the speed toggle causes many problems for libtas. Like it doesn’t render duplicate frames and switches from 60 to 30 fps.
So we need real time speed to be in main thread.

The discussion can be found here: 

http://tasvideos.org/forum/viewtopic.php?t=20542

Jump to the bottom of the page to find if I didn’t elaborate enough.

**Comment by unknownbrackets** [comment]
You'll want to disable the "FrameskipUnthrottle" setting, which is used to overcome forced vsync on Linux (by skipping frames to make unthrottle actually... unthrottle) and is therefore enabled by default on Linux.  It's ini only.

-[Unknown]

**Comment by InfamousKnight** [comment]
And where’s that ini file?

**Comment by unknownbrackets** [comment]
Did that help?

-[Unknown]

**Comment by InfamousKnight** [comment]
Yeah, somewhat. Are new threads constantly being created? Because when playing pspkvm or battlefront 2, I can’t load save states in libtas because new threads were created. I make another save state and try to load and the same thing comes up..

And ratchet and clank size matters still speeds up despite the change.
