### ISSUE TITLE
Bezier low-quality graphics glitch is caused by Vertex Range Culling.

### ISSUE THREAD

**Issue by xebra** [hrydgard/ppsspp#11692]
From https://github.com/hrydgard/ppsspp/pull/11425#issuecomment-425303109

Seems, this issue is caused by Vertex Range Culling #11393.

**Comment by unknownbrackets** [comment]
Hmm, we could skip the vertex range culling when doing a curve.  Maybe even only with low/medium quality.

I have not done any tests to confirm if the PSP draws splines or beziers with points outside the 4096x4096 valid space.  It's entirely possible it always clips curves and they are never culled...

-[Unknown]

**Comment by xebra** [comment]
I think we need to skip it only with low/medium quality curves.

**Comment by hrydgard** [comment]
Seems unlikely that any game would rely on bezier/spline curves hitting range culling... We should indeed just turn it off.
