### ISSUE TITLE
Infinite loading screen in danganronpa (android)

### ISSUE THREAD

**Issue by idkwhattonamemyself** [hrydgard/ppsspp#11699]
So, I was playing danganronpa on ppsspp, Up to this point, i have never had much of a major issue, I need help on this.

reaching chapter 5, after the breakfast assembly, I was stuck in the  loading screen, I thought that it was just loading slowly and that it would load after a while, i sped it up after some time of waiting, and still, nothing

doees anyone know a way to fix this?

**Comment by Emulatorer** [comment]
Please include your phone specs & ppsspp version when filing a issues :/

**Comment by idkwhattonamemyself** [comment]
> Please include your phone specs & ppsspp version when filing a issues :/

oh sorry, I'm quite new to github, I'll go and edit it
