### ISSUE TITLE
[WINDOWS][PPSSPP v1.7.4] Function Keys Spamming Issue

### ISSUE THREAD

**Issue by Joiio** [hrydgard/ppsspp#11702]
When using the function keys (i.e F2 Save State and F4 Load State) ppsspp saves/loads multiple times as long as key remains pressed. Haven't checked the code but a variable to toggle and one "if" should fix it with two lines of code.

**Comment by unknownbrackets** [comment]
Isn't this intentional?  This is normally how it works.  I could see it being useful behavior for save state, for example.

-[Unknown]

**Comment by benderscruffy** [comment]
No feedback/outdated?

**Comment by hrydgard** [comment]
Not planning to do anything about this, closing. If you don't want this, don't hold the key down..
