### ISSUE TITLE
Question: How to build non-headless on Windows?

### ISSUE THREAD

**Issue by njfox** [hrydgard/ppsspp#11705]
I followed the instructions in the wiki and built the solution successfully in Visual Studio 2017, but in the release folder I am only seeing the PPSSPPHeadless executable, which indicates in the usage that it is only intended for testing. Is there some way to build the regular application as well? I tried just building the PPSSPPWindows project but that didn't seem to change anything.

Thanks!

**Comment by mygizli04** [comment]
Well you can simply get the builds from here: https://buildbot.orphis.net/ppsspp/index.php?m=fulllist

**Comment by njfox** [comment]
Thanks, I saw those, but I am choosing to build from source.

**Comment by njfox** [comment]
nevermind, I found it in the root repo directory.
