### ISSUE TITLE
Samsung sm-t231, ppsspp 1.7.4 - exploding vectors in every game.

### ISSUE THREAD

**Issue by Hasster1** [hrydgard/ppsspp#11703]
What happens?
Every game (Mostly 3D games) are showing a giant exploding vectors from middle of the screen above games.
![screenshot_2018-12-30-20-32-28](https://user-images.githubusercontent.com/20757715/50549700-dde3a700-0c72-11e9-9ccf-146be6864867.png)
![screenshot_2018-12-30-20-33-59](https://user-images.githubusercontent.com/20757715/50549704-e63be200-0c72-11e9-89e0-6352a3bbe525.png)

What *should* happen?
Thiese exploding vectors shouldn't be appearing

 What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Screenshots - 
![screenshot_2018-12-30-20-40-33](https://user-images.githubusercontent.com/20757715/50549716-361aa900-0c73-11e9-8fb5-f0f8732111ff.png)
![screenshot_2018-12-30-20-40-21](https://user-images.githubusercontent.com/20757715/50549717-361aa900-0c73-11e9-97d1-2e862e4a86a7.png)
![screenshot_2018-12-30-20-40-15](https://user-images.githubusercontent.com/20757715/50549718-361aa900-0c73-11e9-8caf-a70251b2c3e2.png)

**Comment by hrydgard** [comment]
Vivante GPU, that's a new one.... I assume we accidentally tickle some bug it has.

**Comment by unknownbrackets** [comment]
Could be that range culling is resulting in coordinates at the center on Vivante?

-[Unknown]

**Comment by hrydgard** [comment]
Ah yes, thats a reasonable guess.

**Comment by hrydgard** [comment]
My theory about this kind of stuff is that GLSL "if" statements are converted to LERP on some of the more primitive architectures. And NaNs in those can cause weird things.

As previously discussed, if it's possible to kill primitives with 0 in W or something we should probably try that instead, but I think that will just result in spikes, too.

**Comment by hrydgard** [comment]
@Hasster1  can you try again with the latest build? This should be fixed now

**Comment by Hasster1** [comment]
Last nightly build - those exploding vectors still here.

**Comment by unknownbrackets** [comment]
In that case, it'd help if you could go back and find when this started happening.  It must be something else...

The fastest way is by halves.  For example, if you know it worked in 1.5.4 and is broken in 1.7.5, you can start by checking somewhere in the middle.  There are 1664 changes between those two versions, but going by halves you can find the exact cause in about 11 tries.

If half way in between still works, go to halfway up in newer versions.  If it doesn't work, try older.

-[Unknown]

**Comment by hrydgard** [comment]
Just to be sure, can you also go into the system info screen above and check that Vendor (detected) now is Vivante?

**Comment by Hasster1** [comment]
Yeah, vendor (detected) is now a VENDOR_VIVANTE

**Comment by hrydgard** [comment]
@Hasster1  Thanks, good to know that worked at least.

**Comment by fortunereject** [comment]
I am also experiencing this weird effect, but on a RPi3 with PPSSPP 1.7.5 and Lego Star Wars II
