### ISSUE TITLE
Black Screen - playing the game One Piece : Romance Dawn

### ISSUE THREAD

**Issue by MojoJojoDojo** [hrydgard/ppsspp#11701]
Using the Vulkan and DX11 renderer the game One Piece : Romance Dawn gets a black screen.
Only the music works.
The game works fine using the OpenGL and Directx 9 renderers.
I am using the latest PPSSPP git version 1.7.5-336 on using Windows 10.
My GPU is AMD Radeon 530 but i also have an Intel GPU called UHD 620 that I rarely use.

**Comment by unknownbrackets** [comment]
Could you try exporting a GE frame dump?  These help a lot.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by MojoJojoDojo** [comment]
[recordings.zip](https://github.com/hrydgard/ppsspp/files/2716259/recordings.zip)

This contains recordings for both renderers.

**Comment by unknownbrackets** [comment]
This has to do with viewport and depth in the cull range path.

-[Unknown]

**Comment by MojoJojoDojo** [comment]
Just a note , if you use the Vulkan renderer on linux the game does work correctly.
I could try the DIrectx 11 renderer with DXVK but dunno if it will help.
