### ISSUE TITLE
Inaccurate GU emulation?

### ISSUE THREAD

**Issue by suicvne** [hrydgard/ppsspp#11710]
### What happens?
![unknown-1](https://user-images.githubusercontent.com/861492/50622428-0372e980-0edb-11e9-8a75-1a7a26e7fabf.png)

### What *should* happen?
![image0](https://user-images.githubusercontent.com/861492/50622426-0077f900-0edb-11e9-9578-2efa23316a6c.jpg)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Hardware - Hackintosh
Core i7 3770
12gb RAM
RX 580 8gb

OS - macOS Mojave
PPSSPP Version - 1.6.3-456-g6d0ed4ad0

Not sure what's going on here, but I've been working on developing a PSP homebrew using the raw sceGu calls available in the SDK. I'm more than willing to provide code to try and help debug this, as you can see it looks beautiful in the emulator but moving it over to real hardware causes...the result you see there. I am wondering if this is an inaccuracy on the emulator's end or if my code is that severely screwed up.

**Comment by unknownbrackets** [comment]
Did you figure this out?  Was it something related to cache after all, or was it something else?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.  Assuming it was cache, which we know we don't accurately emulate but is complicated (and slow) to emulate.

-[Unknown]
