### ISSUE TITLE
PPSSPP displays on part of the screen from commit 070e29d, on Amlogic S905

### ISSUE THREAD

**Issue by shantigilbert** [hrydgard/ppsspp#11714]
### What happens?
From commit 070e29d921845fe324baa4f9c403df0898c2d1ca PPSSPP shows in a small part of the screen even with Full Screen set to on 

### What *should* happen?
Display on full screen 

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Amlogic s905 ARM device running CoreELEC 

Not sure what changed on that commit that would break the screen size, but this is the result when I run any version after that commit, you can see it says Pixels: 960 x 544 Virtual pixels: 960 x 544

`Vulkan is not available.
sh: setterm: not found
I: Config.cpp:490: Longest display side: -1 pixels. Choosing scale 1
58:55:733 Core/Config.cpp:1089 I[LOADER]: Loading controller config: /storage/.config/ppsspp/PSP/SYSTEM/controls.ini
58:55:778 Core/Config.cpp:1175 I[LOADER]: Config saved: '/storage/.config/ppsspp/PSP/SYSTEM/ppsspp.ini'
58:55:781 Core/Config.cpp:1188 I[LOADER]: Controller config saved: /storage/.config/ppsspp/PSP/SYSTEM/controls.ini
Pixels: 960 x 544
Virtual pixels: 960 x 544
I: gpu_features.cpp:181: GPU Vendor : ARM ; renderer: Mali-450 MP version str: OpenGL ES 2.0 ; GLSL version str: OpenGL ES GLSL ES 1.00
loading control pad mappings from gamecontrollerdb.txt: SUCCESS!
found control pad: Logitech F310 Gamepad (XInput), loading mapping: SUCCESS, mapping is:
030000006d0400001dc2000014400000,Logitech F310 Gamepad (XInput),a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b8,leftshoulder:b4,leftstick:b9,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b10,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,platform:Linux,
pad 1 has been assigned to control pad: Logitech F310 Gamepad (XInput)
I: NativeApp.cpp:758: NativeInitGraphics
found control pad: Logitech F310 Gamepad (XInput), loading mapping: SUCCESS, mapping is:
030000006d0400001dc2000014400000,Logitech F310 Gamepad (XInput),a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b8,leftshoulder:b4,leftstick:b9,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b10,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,platform:Linux,
I: NativeApp.cpp:835: NativeInitGraphics completed
58:55:806 UI/DiscordIntegration.cpp:55 I[SYSTEM]: Discord connection initialized
I: GLRenderManager.cpp:187: Running first frame (0)
58:56:184 Core/Config.cpp:1175 I[LOADER]: Config saved: '/storage/.config/ppsspp/PSP/SYSTEM/ppsspp.ini'
58:56:188 Core/Config.cpp:1188 I[LOADER]: Controller config saved: /storage/.config/ppsspp/PSP/SYSTEM/controls.ini
^CI: NativeApp.cpp:846: NativeShutdownGraphics
I: NativeApp.cpp:873: NativeShutdownGraphics done
I: GLRenderManager.cpp:216: GL submission thread paused. Frame=2
I: GLRenderManager.cpp:124: ThreadEnd
58:58:907 Core/Config.cpp:1175 I[LOADER]: Config saved: '/storage/.config/ppsspp/PSP/SYSTEM/ppsspp.ini'
58:58:910 Core/Config.cpp:1188 I[LOADER]: Controller config saved: /storage/.config/ppsspp/PSP/SYSTEM/controls.ini`

and this is what shows with any version before that commit, here it says Pixels: 1920 x 1080 Virtual pixels: 1920 x 1080

`Vulkan is not available.
sh: setterm: not found
I: Config.cpp:490: Longest display side: -1 pixels. Choosing scale 1
59:41:833 Core/Config.cpp:1094 I[LOADER]: Loading controller config: /storage/.config/ppsspp/PSP/SYSTEM/controls.ini
59:41:878 Core/Config.cpp:1180 I[LOADER]: Config saved: '/storage/.config/ppsspp/PSP/SYSTEM/ppsspp.ini'
59:41:881 Core/Config.cpp:1193 I[LOADER]: Controller config saved: /storage/.config/ppsspp/PSP/SYSTEM/controls.ini
Pixels: 1920 x 1080
Virtual pixels: 1920 x 1080
I: gpu_features.cpp:181: GPU Vendor : ARM ; renderer: Mali-450 MP version str: OpenGL ES 2.0 ; GLSL version str: OpenGL ES GLSL ES 1.00
loading control pad mappings from gamecontrollerdb.txt: SUCCESS!
found control pad: Logitech F310 Gamepad (XInput), loading mapping: SUCCESS, mapping is:
030000006d0400001dc2000014400000,Logitech F310 Gamepad (XInput),a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b8,leftshoulder:b4,leftstick:b9,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b10,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,platform:Linux,
pad 1 has been assigned to control pad: Logitech F310 Gamepad (XInput)
I: NativeApp.cpp:756: NativeInitGraphics
found control pad: Logitech F310 Gamepad (XInput), loading mapping: SUCCESS, mapping is:
030000006d0400001dc2000014400000,Logitech F310 Gamepad (XInput),a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b8,leftshoulder:b4,leftstick:b9,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b10,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,platform:Linux,
I: NativeApp.cpp:832: NativeInitGraphics completed
59:41:907 UI/DiscordIntegration.cpp:51 I[SYSTEM]: Discord connection initialized
I: GLRenderManager.cpp:187: Running first frame (0)
59:42:292 Core/Config.cpp:1180 I[LOADER]: Config saved: '/storage/.config/ppsspp/PSP/SYSTEM/ppsspp.ini'
59:42:296 Core/Config.cpp:1193 I[LOADER]: Controller config saved: /storage/.config/ppsspp/PSP/SYSTEM/controls.ini
`

**Comment by hrydgard** [comment]
@shantigilbert  Others might have issues too, can you provide your patch please?

**Comment by hrydgard** [comment]
Actually, well, never mind, that's so simple that it's obvious what you did. We probably should default to fullscreen on more devices?

**Comment by shantigilbert** [comment]
Yeah, sorry I didn't think an explanation for the patch was needed. It just reverts that change. Also after I closed this issue I found out about the - - fullscreen argument, which also works

**Comment by unknownbrackets** [comment]
Are you using `-DUSING_FBDEV`, in which case #11806 will make this work without any extra switches?  Or are you using something more complex?

Sorry, I'm not familiar with CoreELEC.  It seems like something that might not use a window manager.

-[Unknown]

**Comment by shantigilbert** [comment]
@unknownbrackets yes, that PR would work in my case as I am using FBDEV

**Comment by unknownbrackets** [comment]
Okay, great.  It's merged now, so I'm going to close this then.  Thanks for the quick confirmation.

-[Unknown]

**Comment by shantigilbert** [comment]
Thank you for the great work!
