### ISSUE TITLE
[Regression] PPSSPP won't start AMD GPU

### ISSUE THREAD

**Issue by TLuigi003** [hrydgard/ppsspp#11719]
It may be related to #11679 however I have never changed graphic card, My PC has always been AMD, while 11679 PC is now NVidia. Feel free to close this issue if you think it's the same problem.

### What happens?
PPSSPP don't start, when I try to open it it does generate the folder structure under Documents but the process finish itself without a Warning

### What *should* happen?
It should open, or, on worst case scenario it should at least throw an error message

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
AMD A8(x64) with Radeon R5 APU Graphics(OpenGL 4 compatible. NO Vulkan comaptible)
Windows 10 Home
Failing PPSSPP version: 1.7.4
Latest known working version: 1.5.4

### What have I tried
Executing the AMD cleanup utility and deleting ALL AMD stuff makes the emulator able to start, however since no driver is installed the emulator fails to use hardware rendering, making the games unplayable.
Installing basic AMD drivers through Windows Update makes the emulator unable to start once again.
Starting as admin doesn't make a difference.
Using 1.5.4 version works perfectly.

I'll be glad to run any test you want

**Comment by hrydgard** [comment]
What about the latest build from https://buildbot.orphis.net/ppsspp/  ?

**Comment by hrydgard** [comment]
But it's interesting that our Vulkan detection fails badly enough to cause this on a GPU that doesn't even support it...

**Comment by TLuigi003** [comment]
I just tried v1.7.5-357-g79d4b0f5a , both 32 and 64 bits with same result. PPSSPP is not starting.
Just as it happened before, running as administrator doesn't make a difference.

I've also tried running the two batch files provided within the zip file and the logs files are not even generated(or i Couldn't find them)

**Comment by TLuigi003** [comment]
I have had a long history of problems with AMD's website drivers. My screen freezes like a second sometimes with them installed so I prefer the Windows Update AMD drivers
I could try anyway

I didn't know about the existence of that tool so I'm pretty confident I'm not using it

I have almost finished my computer science degree and this past year I've been working as web developer so if you have a wiki on how to set up the environment (for Windows) I could try to check it in my spare time

Thanks for you time BTW

**Comment by hrydgard** [comment]
https://github.com/hrydgard/ppsspp/wiki/Build-instructions

The build instructions for windows are pretty much:

   * Install git, Visual Studio Community Edition
   * git clone --recursive https://github.com/hrydgard/ppsspp.git
   * Open Windows\PPSSPPWindows.sln , press F5 to build and debug

**Comment by unknownbrackets** [comment]
When installing Visual Studio Community (I recommend 2017), make sure to select "desktop development with C++" on the left, and then "Windows XP Support" on the right side.

This is a screenshot, although slightly different options are highlighted:

https://social.msdn.microsoft.com/Forums/getfile/1035488

If the latest drivers make your system less stable then that's probably not terribly worth trying...

-[Unknown]

**Comment by unknownbrackets** [comment]
Found anything?  If you press F5 and get it to crash, it should show the stack trace / call stack in a tabbed pane.

Also curious to know if this is still happening, perhaps AMD has released fixed drivers.

-[Unknown]

**Comment by hrydgard** [comment]
@TLuigi003 , can you try the latest build?  (v1.7.5-389 or later)

**Comment by TLuigi003** [comment]
@unknownbrackets  I'm so sorry, I had university exams. I'm free again!
@hrydgard I'm gonna test, if id doesn't work I'm gonna try to debug!

**Comment by TLuigi003** [comment]
I'll debug later, Last build doesn't seem to work @hrydgard

**Comment by TLuigi003** [comment]
Apparently bug is in line 321 of VulkanLoader.cpp.

The function create instance is failling giving this error Exception thrown at en 0x00007FFE48AEAD11 (amdvlk64.dll) in PPSSPPDebug64.exe: 0xC0000005 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.

Commenting that line and setting Res to another value makes PPSSPP able to launch so that function must be broken.

![image](https://user-images.githubusercontent.com/20229636/52140694-b0b05d00-2653-11e9-961d-209adc475267.png)

**Comment by TLuigi003** [comment]
I have tried instantiating the ci structure a bit, maybe garbage reading but it doesn't work.

I'm not really used to PPSSPP, nor to Vulkan so I can only experiment, let's hope you guys can discover it, ask me whatever you want

Thanks!

**Comment by hrydgard** [comment]
Thanks for experimenting. I really had hope this change would work, but nope :(  Very unfortunate. 

Really not sure what to try next, I guess we'll just have to not do the check on startup, but that would make it possible to pick Vulkan and then for it to fail on the next startup.... Grr.

**Comment by unknownbrackets** [comment]
It sounds terrible, but we could detect the amd driver dll existing and not check Vulkan.  Probably simplest and best to just not check on startup and show the warning, though.

@TLuigi003 just to clarify, the localCreateInstance function is basically provided by the GPU driver.  It's actually provided by the Vulkan loader, which then calls the GPU driver, but the crash is occurring in AMD code.  And we can't initialize or correctly check for Vulkan without calling that function.

We could at least continue to check if the vulkan dll exists, i.e. up to before that call, which would eliminate some cases of no Vulkan, but not most.  And it means if the user switches to Vulkan in settings, it will crash and there's no way for us to prevent this.

-[Unknown]

**Comment by unknownbrackets** [comment]
@TLuigi003 would be great if you could try the latest master now and confirm if it no longer crashes.  It should silently show no Vulkan option, as expected.

Note: this will only happen in a Release build.  To allow debugging the Vulkan detection, Debug builds will work as before.  You can change the build type in the dropdown right underneath Depurar in your screenshot above.  Or you can just use a build from [the buildbot](https://buildbot.orphis.net/ppsspp/).

-[Unknown]

**Comment by hrydgard** [comment]
This has now cropped up on the Khronos loader issue tracker:  https://github.com/KhronosGroup/Vulkan-Loader/issues/182

**Comment by hg-ctangora** [comment]
To confirm, amdvlk64.dll attempting to read 0xFFFFFFFFFFFFFFFF was the behaviour I saw after installing AMD driver 17.1.1 as discussed over on that issue, so this is the same crash we're now looking at workarounds for.

**Comment by TLuigi003** [comment]
Never got to answer to @unknownbrackets but yes, nowadays the emulator starts perfectly on my machine.

**Comment by Makalov** [comment]
I have the symptoms described in this post. I am using Windows 10, AMD RX580 and the latest driver version(22.3.1)

**Comment by hrydgard** [comment]
@Makalov and the latest build of PPSSPP?

**Comment by Makalov** [comment]
Yes, 1.12.3 has this issue. I tried the 1.5.4 version mentioned in this thread and it works fine. 

In 1.12.3 when I try to run it I can see the process in task manager but the window doesn't show up

**Comment by Makalov** [comment]
Update: 

I built from source and compiled and I don't see the issue.  The version shown is v1.12.3-1144-g28532fe4e.

When I try to run 1.12.3 from the installer I see a tab in my taskbar below, but no window show up.

![image](https://user-images.githubusercontent.com/1303571/167087795-027416a9-bb36-42bd-afe8-f8ef502991d8.png)

**Comment by hrydgard** [comment]
OK, well that's good news if it works on master. 

I'm gonna do another official release in about a month.
