### ISSUE TITLE
Boot screen is unusable Android 8.1.0

### ISSUE THREAD

**Issue by SillyAnarchist** [hrydgard/ppsspp#11723]
Working with a newly purchased tcl I can click on the torn menus and get links to open but can't mostly can't see anything I'm working with had the same issue years ago on htc and iPhone 5s never have been able to get PPSSPP to run correctly and would like to play the psp games I never got to p.s. no laptop or tower so I'm left with just the phone for fixing the issue thanks a ton in advance

**Comment by hrydgard** [comment]
Can you take a screenshot of what you're seeing and post it here?

Den tis 8 jan. 2019 kl 05:38 skrev SillyAnarchist <notifications@github.com

**Comment by SillyAnarchist** [comment]
![screenshot_20190108-055555](https://user-images.githubusercontent.com/46471998/50831242-d6299f80-130f-11e9-959d-d3abc6ceac8d.png)

**Comment by hrydgard** [comment]
That looks familiar...  See https://github.com/hrydgard/ppsspp/issues/11151  (google photos link a few post down works).

Has to be a GPU driver bug, that we are somehow triggering. Are you testing with the latest build of PPSSPP from https://buildbot.orphis.net/ppsspp/ ? What phone model exactly?

**Comment by marosis** [comment]
Duplicate #11289

**Comment by SillyAnarchist** [comment]
In unable to find any info on what version I'm running maybe issues with the download from the play store I read the other thread maybe send me a link to switch out the files or I could send mine dont know if it would make a difference

**Comment by SillyAnarchist** [comment]
App not installed when I try to update

**Comment by unknownbrackets** [comment]
You may have to remove the Google Play app since the nightly builds have a different signature.

-[Unknown]

**Comment by hrydgard** [comment]
I'm getting exactly the same kind of nonsense on my Honor 7S, that has a PowerVR GPU though and I don't find any TCL phones that have that? @SillyAnarchist  exactly which device model do you have?

**Comment by hrydgard** [comment]
This is fixed now, assuming it's the same PowerVR bug. If not, I don't know what to do.
