### ISSUE TITLE
[Mac OS] Crash when held F5 (switching buffered rendering on/off fast)

### ISSUE THREAD

**Issue by mygizli04** [hrydgard/ppsspp#11725]
(even more problems on QT, yay.)
### What happens?
When held F5 ( switching quickly between buffered rendering and non-buffered rendering ) PPSSPP crashes with "Killed: 9"

### What *should* happen?
It shouldn't crash? ( i know this isn't very specific but still )

[Terminal output](https://gist.github.com/mygizli04/0163bb208b667c68c2b9a5aea619fb34) doesn't have any info so here's the [MacOS crash log](https://gist.github.com/mygizli04/461694c8fabf8db51b2ae4de24d66e5b). Simply limiting the number of changes to buffered to non-buffered per something can prevent this :P

Edit: Realized i wasn't actually using the latest git build, updated and it still occours on v1.7.5-363-ge3dd1533f

**Comment by hrydgard** [comment]
Thanks. Definitely a real bug that should be fixed, even though it's not practically that much of a problem.

**Comment by hrydgard** [comment]
Yes, that would seem to be the case..

**Comment by hrydgard** [comment]
That takes care of the immediate problem, bumping a proper fix to 1.9.0.

**Comment by unknownbrackets** [comment]
I guess the simplest options would be:

1. Delay updating settings until frame start in Qt.
2. More generically, change `iRenderingMode` using an event everywhere that is processed at frame start.
3. Track state at frame start, and use that for buffered rendering, ignoring changes to `iRenderingMode` mid frame.

-[Unknown]

**Comment by hrydgard** [comment]
Since we really have multiple options that this applies to (even if the consequences are less severe), a generic solution should probably be found, the easiest would be 2 I think. This should also be applied to the Windows UI...
