### ISSUE TITLE
Easier access for Replace/Save new textures

### ISSUE THREAD

**Issue by AkiraJkr** [hrydgard/ppsspp#11734]
In regards to future texture modders, I think it would be a good idea to give them easier access to these two buttons, as they will be visited, a lot, specially if it's a huge game, or one with duplicate textures popping each second.

There is the DevMenu, yes. But while I tried to use it, I found out that even after checking the boxes, nothing is affected until you pause and go to settings, so it's not viable. A suggestion for a perfect place for those would be...

![image](https://user-images.githubusercontent.com/27028529/51239634-0c46cf00-1961-11e9-8a85-0ec26c4e909c.png)

A secret shortcut for that would also be appreciated too.

**Comment by gamaghostmagus** [comment]
Please, do it!
Just do it!

I need a shorcut :'(
