### ISSUE TITLE
Ppsspp on Android screen auto rotate crash

### ISSUE THREAD

**Issue by Blarrrgh** [hrydgard/ppsspp#11739]
### What happens?

Setting screen rotation to "Auto" in the settings crashes ppsspp.

### What *should* happen?

Screen orientation should just auto rotate as normal.

### What hardware, operating system, and PPSSPP version?

Pocophone F1
MIUI 10.2 Global Stable
10.2.2.0(PEJMIXM)

I can confirm that PPSSPP 1.7.5-277 screen auto rotation works fine as I'm using it right now. The problem is 1.7.5-363(or maybe somewhere between 277 and 363). That's where it crashes whenever I set screen rotation to auto.

I've installed/uninstalled and cleared data of 1.7.5-363 to no avail.

**Comment by hrydgard** [comment]
Thanks, will investigate. Just got myself an F1 :)

**Comment by Blarrrgh** [comment]
Sorry for the late reply. Gmail didn't display the whole message. Currently installed 1.7.5-433.

If it helps, Vulkan doesn't crash during rotation but the screen doesn't scale down or up when rotating from either landscape or portrait. 

For example, the screen would stay in landscape size when rotating to portrait therby cutting the screen in half. Portrait to landscape would lock the screen to the size that it was when in portrait mode also the screen would be off center. 

Also installed 433 on my old K3 Note. Screen rotation and screen scaling works perfect.

**Comment by unknownbrackets** [comment]
The crash should be fixed in the latest git builds.  The rest is probably the same issue as #11526.  It's an annoying workaround, but going into the settings and changing the immersive option back and forth fixes it.

-[Unknown]
