### ISSUE TITLE
Android: Separate PSP directory for Gold app (or any other clone with a different package name)

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#11731]
When you have both a stable Gold version installed (for example) and PPSSPP nightlies, their directories can conflict in terms of save state and setting compatibility.

It would be good to allow a separate PSP directory per different-package-name installation of the app.

**Comment by unknownbrackets** [comment]
I assume this would have to be an option somehow?  At least for saves (and generally, save states), it seems like a feature not a bug that they are shared.

-[Unknown]

**Comment by hrydgard** [comment]
yes, it would be an option saved in the Android-managed app-specific directory.

**Comment by unknownbrackets** [comment]
We effectively have this now, see #14619.  As such, closing.

-[Unknown]
