### ISSUE TITLE
"Suicide Barbie" homebrew demo doesn't work when PSPFirmware = 600

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#11733]
As in title. At least broken on Android and Linux.

Related to #11648 ?

**Comment by mygizli04** [comment]
Broken in MacOS too.

**Comment by hrydgard** [comment]
Really? Works on both Windows and Mac for me, fresh builds.

However it does appear to be broken on Android.

**Comment by hrydgard** [comment]
```01-17 00:01:43.890 27952 28085 E PPSSPP  : [LOADER] 80010002=sceKernelLoadModule(flash0:/kd/audiocodec_260.prx, 00000000, 09fbf34c): file does not exist
01-17 00:01:43.902 27952 28085 E PPSSPP  : [SCEMODULE] UNIMPL sceKernelSelfStopUnloadModule(00000001, 00000000, 00000000): game may have crashed
```
This is quite odd since on PC, it tries (and "succeeds") to load ms0:/PSP/GAME/SuicideBarbie/BarbieData/music/atrac3streamer.prx ...

**Comment by kkwannyc** [comment]
Check the eboot.pbp file - the original demo comes with a ~660kb file, while the version currently in the homebrew store is ~937kb - that seems suspiciously large.  

The publicly available version of Suicide Barbie at https://files.scene.org/view/parties/2007/breakpoint07/wild/tbl-suicidebarbie-final.zip works just fine on the MacOS builds, and the only difference is the ATRAC3 song being different inside BarbieData/music/ (licensing/distribution issues?) - I swapped the entire barbiedata directory located inside .config/ppsspp/game/suicidebarbie (the location from the homebrew store) into the working public demo and it worked just fine, so whatever is breaking it, it's not the artwork/music/geometry files, it's most likely the eboot.psp being corrupted.

The md5 hash on the eboot.psp as distributed from the homebrew store is  133b82374c897f820eda2bdcc9379242 - can you confirm that this is supposed to be correct?

**Comment by hrydgard** [comment]
Wacky. Because the current version on the HB store works fine on Windows for me. This feels like some weird I/O issue, maybe we suddenly got sensitive to capitalized directory names when we shouldn't, or something.

The version on the store is not the final version of the demo because that one had a different soundtrack, which I liked less than the original one. The difference is a short sample of another song, which I think would go under normal sampling exception but isn't OK in the context of a demo competition, hence the final.

**Comment by kkwannyc** [comment]
Did you reinstall your Windows version, reinstall it, download the HBstore and re-run it? 
Anyways, I am more than happy to help out and debug this, but you'll have to walk me through the developer/debug facilities on ppsspp.

**Comment by hrydgard** [comment]
So! It turns out that it works if you set [SystemParam] PSPFirmwareVersion=150 in ppsspp.ini.

Quite curious...

**Comment by unknownbrackets** [comment]
That in theory only changes the result of `sceKernelDevkitVersion()`.  Maybe the homebrew tries to run some hack that doesn't work in PPSSPP for newer firmwares?

-[Unknown]

**Comment by KCropIT** [comment]
I ran some tests - It works up until and including PSPFirmware = 250.  
2.60 and above will pretty much fail to run.

**Comment by kkwannyc** [comment]
It ran up until and including PSPFirmware = 250.   260 and above does not work.

**Comment by hrydgard** [comment]
Yeah, the homebrew obviously changes behaviour at 260 then.. Wonder what it does differently and why.
