### ISSUE TITLE
DTM race driver 3 performance drop (VULKAN)

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#11745]
I've catched frame drop. This drop i have found only on one curcuit. 
I've posted video in in Mp4 format (zipped) (2 minutes 100mb sorry) on Gdrive. Differents are between VULKAN And OPENGL.

Xiaomi redmi note 5 
Snapdragon 636
(DUMP FILE OR LOGCAT can be good)
https://drive.google.com/file/d/1n4JskTjhUrh1PAvZKL5qiFfTo3hT9BVs/view?usp=drivesdk

**Comment by hrydgard** [comment]
Is this new in recent builds or has it always been there? Those are some strange stutters indeed.

**Comment by marosis** [comment]
Sorry i dont have the other abilities. If Is this new issue i can't confirm because i don't have this android long time

**Comment by hrydgard** [comment]
That's alright, thanks for reporting. Uploading that savestate you have could help investigating.

**Comment by marosis** [comment]
[DTM RD3 Save State.zip](https://github.com/hrydgard/ppsspp/files/2818193/DTM.RD3.Save.State.zip)
Here it Is ;)

**Comment by hrydgard** [comment]
Does this still happen?

**Comment by Panderner** [comment]
> [DTM RD3 Save State.zip](https://github.com/hrydgard/ppsspp/files/2818193/DTM.RD3.Save.State.zip)
> Here it Is ;)

That save state is for DTM race driver 2

**Comment by Panderner** [comment]
I can't see the difference where this game has performance drops (except 2 frame difference) when I using POCO M3 in both backends

OpenGL: 
![Screenshot_2021-01-07-12-39-35-398_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/103851884-b9cec200-50e5-11eb-9ff9-212fc28e1caa.jpg)

Vulkan: 
![Screenshot_2021-01-07-12-39-52-916_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/103851938-d8cd5400-50e5-11eb-857b-b4b4a5bd0533.jpg)

**Comment by Gamemulatorer** [comment]
DTM Race Driver 2 is also slow on my Oppo a3s both opengl and vulkan.
![Screenshot_2022-09-24-14-16-12-70](https://user-images.githubusercontent.com/37603562/192083084-acc75a0a-4004-4fd2-b59f-76b8173b5ebc.png)

**Comment by hrydgard** [comment]
Yeah, hopefully. Closing.
