### ISSUE TITLE
Future perf feature: Zero-copy texture conversion in Vulkan

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#11749]
Just writing down this idea so I don't forget it, it won't happen soon and the benefit won't be huge - but could help eliminating stutter caused by texture uploading.

~~Since 1.1~~ With VK_EXT_external_memory_host, Vulkan allows you to import RAM and expose it directly to the GPU through the external memory type VK_EXTERNAL_MEMORY_HANDLE_TYPE_HOST_ALLOCATION_BIT_EXT . 

We could simply directly expose the PSP RAM and VRAM to a compute shader, which could take care of all the swizzling and format conversion, writing to a native Vulkan image. This would eliminate the need to spend CPU cycles uploading textures to the GPU, the GPU would just pull it out of RAM while doing the conversion.

Or even more insane, we could manually read the RAM/VRAM directly while texturing, but probably not worth it.

**Comment by hrydgard** [comment]
Actually, scratch that - Vulkan 1.1 does include features for external memory, but not the critical VK_EXT_external_memory_host by default. So this will only be possible on devices that support that extension (which is quite a few recent desktop GPUs, but no mobile ones so far).

**Comment by hrydgard** [comment]
So it is, that doesn't mean it's actually supported by devices though. Extension support is optional.

https://vulkan.gpuinfo.org/listreports.php?extension=VK_EXT_external_memory_host

**Comment by Narugakuruga** [comment]
Okay thanks for teaching.😅

**Comment by unknownbrackets** [comment]
> 3<span>)</span> Can the application free the host allocation?
>
> RESOLVED: No, it violates valid usage conditions.
> Using the memory object imported from a host allocation that's already freed
> thus results in undefined: behavior.

Does this mean that the pointer becomes owned by the implementation?

-[Unknown]

**Comment by hrydgard** [comment]
It's a bit unclear but I think it just means that while the GPU allocation created from the memory is alive, behaviour is undefined (and probably bad) if the application frees the allocation.

Anyway, I'm less and less sure this is a good idea since our PSP GPU lives in a kind of delayed timeline, if you know what I mean...

**Comment by hrydgard** [comment]
Decided that this is not worth doing, there are other more effective performance improvements we can do to texture loading on Vulkan and other APIs.
