### ISSUE TITLE
PPSSPP Crash When Changing OpenGL Display Resolution

### ISSUE THREAD

**Issue by TideGear** [hrydgard/ppsspp#11755]
PPSSPP crashes when changing the display resolution while OpenGL is selected. Vulkan doesn't seem to have this issue.

I'm using v1.7.5-394-g4816e80b4 on a Galaxy S9+ (USA) on OS 9.0.

**Comment by Drasikk** [comment]
I also have the same problem with the latest version available.

**Comment by hrydgard** [comment]
This is the same issue as #11739 and #11755, closing as duplicate (and will fix soon).
