### ISSUE TITLE
Feature: Add ability to turn off parts of the JIT at runtime through debug menu

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#11753]
This could help us debug the final ARM64 jit issues a bit faster by letting end-users bisect the JIT with simple instructions, and would have minimal runtime overhead.

Idea from Dolphin: https://github.com/dolphin-emu/dolphin/commit/3da06970d9e497e497b452182ec99fa6e960d15a

**Comment by marosis** [comment]
Cool!

**Comment by Emulatorer** [comment]
Nice 👍

**Comment by unknownbrackets** [comment]
Rather than a series of options, perhaps we could make it a bitmask for disabled parts?  I think the ini file system has support for hex values, right?

-[Unknown]

**Comment by hrydgard** [comment]
Yup, I was planning to add bitfield support for UI checkboxes.
