### ISSUE TITLE
Black screen in app

### ISSUE THREAD

**Issue by MrPiunov** [hrydgard/ppsspp#11756]
Good day! You cannot start the application normally when you start the black screen, however in recent applications the interface will be normal (and in any screenshot too), so when you click on the black screen in the area of ​​any button, the application responds to it normally, which can be seen in recent applications. Checked versions of PPSSPP from 1.4.2 to 1.7.2. Screenshots are attached.
Phone Micromax Q380 Canvas Spark
Mediatek MT6582M processor (4x1.3 GHz)
Android 5.0.2 Exception OS version 0.4
From overclocking, use only RAM Manager Pro in hard gaming mode and swap file.
![screenshot_2019-02-01-10-16-53](https://user-images.githubusercontent.com/47259172/52164456-a6996780-2702-11e9-8c1d-ed37f788979d.png)
![screenshot_2019-02-01-10-17-04](https://user-images.githubusercontent.com/47259172/52164457-a731fe00-2702-11e9-9a5c-2625870cea60.png)

**Comment by MrPiunov** [comment]
Managed to run the latest nightly build v1.7.5-394-g4816e80b4

**Comment by unknownbrackets** [comment]
What's the first build that started showing a black screen and the last build the worked fine?  Did it work in v.1.7.4?  Did it work in v1.6.x?

-[Unknown]

**Comment by MrPiunov** [comment]
Sorry, I was able to write on github, no longer need to communicate by mail.02.02.2019, 22:11, "Unknown W. Brackets" <notifications@github.com>:What's the first build that started showing a black screen and the last build the worked fine?  Did it work in v.1.7.4?  Did it work in v1.6.x?
-[Unknown]

**Comment by MrPiunov** [comment]
For the first time disappears to a black screen in v1.7.5-302-g51fec7f43 when he first appeared could not be determined.

**Comment by MrPiunov** [comment]
In v 1.6.x doesn't work. I couldn't find any v 1.7.4

**Comment by MrPiunov** [comment]
The situation has changed a bit, explain in order:

Yesterday: 
v1.7.5-295-g868696018 - > this has a black screen. 
v1.7.5-302-g51fec7f43 -> this does not have a black screen.

Today: 
v1.7.5-295-g868696018 - > this has a black screen. 
v1.7.5-302-g51fec7f43 - > this has a black screen. v1.7.5-304-g015c314fb -> this does not have a black screen.

There were no updates on the phone.

**Comment by hrydgard** [comment]
Wacky. Does a reboot of the phone affect things?

**Comment by MrPiunov** [comment]
Rebooting does not affect this in any way.

**Comment by MrPiunov** [comment]
Does not working versions it is wrong to define GL? My chip doesn't support OpenGL 3.0

**Comment by unknownbrackets** [comment]
We should work fine even on GLES 2.  I'm still not sure I understand.

It sounds like old versions show a black screen.  The last few messages say it is fixed in v1.7.5-304-g015c314fb.  Is it also fixed in later versions?

v1.7.5-304-g015c314fb changes the way PPSSPP draws graphics.  It affects your device.

It sounds like this is now fixed.  The version on the play store is still broken.  When a new version is put on the play store (v1.8.0) it will have the fix from v1.7.5-304-g015c314fb.

Am I understanding wrong?  It sounds like this bug is already fixed.

-[Unknown]

**Comment by MrPiunov** [comment]
Yes, all later corrections, probably can be closed

**Comment by unknownbrackets** [comment]
Thanks for the confirmation.

-[Unknown]
