### ISSUE TITLE
Crash on boot - black screen (Android ARMv7, Adreno 308)

### ISSUE THREAD

**Issue by shadowknight1620** [hrydgard/ppsspp#11757]
### What happens?
When booting app it just is a black screen then force closes/Crash.

### What *should* happen?
It should boot like previous builds. 

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Samsung Android 6.0.1 armv7 opengl adreno 308. build ppsspp-v1.7.5-321-g2dbdd73e5 is last working version later builds all have boot issue.

Edit: also seems to have some exit or app closing freeze-up/crash issues on the listed build above, although it is very rare.

**Comment by hrydgard** [comment]
So that's #11695 , if 321 works. Hmm...

**Comment by shadowknight1620** [comment]
If you would like me to test any specific builds just comment here and I'll see if I can help squash this.

**Comment by hrydgard** [comment]
I'm gonna dig out some of my older devices and try to repro first, but thanks!

**Comment by Emulatorer** [comment]
I thought Adreno GPU's is x86 cpu architecture not armv7 🤔

@shadowknight1620 what's the full brand name of your Samsung device?

**Comment by shadowknight1620** [comment]
SM-327VL

**Comment by hrydgard** [comment]
Try the latest build now. I believe  #11786 may have fixed this (it fixed it for Nexus 4).

**Comment by shadowknight1620** [comment]
I  can confirm that build v1.7.5-450-g0b9c2128a does boot and exit correctly. :)

**Comment by unknownbrackets** [comment]
Thanks for the update.

-[Unknown]
