### ISSUE TITLE
Not true information about the application version

### ISSUE THREAD

**Issue by MrPiunov** [hrydgard/ppsspp#11762]
Why is the software version in ppsspp and in the phone settings different? In the information about the position of v1.7.5 - 158, and in the ppsspp v1.7.5-403-g128c0adc3

**Comment by Florin9doi** [comment]
Duplicate of #10837?

**Comment by hrydgard** [comment]
It would seem that the difference is bigger than what that commit could explain? Very strange.

**Comment by unknownbrackets** [comment]
Maybe it's only counting merge commits, period?

-[Unknown]

**Comment by Emulatorer** [comment]
This issue is a duplicate of #10837 ([Android] In-app build version and package manifest don't match)

**Comment by unknownbrackets** [comment]
Yep, confirmed:

v1.7.5-436-g23dd47ab7
androidGitVersion.name  1.7.5-191-dirty
androidGitVersion.code  17050191

-[Unknown]
