### ISSUE TITLE
Remove some texture upscaling methods?

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#11769]
I plan to eventually move automatic texture upscaling to the GPU. 

I'm wondering if we really need all the options we currently have:

* xBRZ
* Hybrid
* Bicubic
* Hybrid+Bicubic

plus the Deposterize setting.

Bicubic will be turned into a texture filtering mode and moved directly into the shaders (it can be done in four lookups, and some hardware actually has direct support for it), but there's still Hybrid and Deposterize. I bet few people have any idea what any of these do. Are Hybrid and Deposterize really worth keeping?

**Comment by Narugakuruga** [comment]
Glad to see Bicubic be turned into a texture filtering mode. 
Deposterize does help reduce flickers in some case when using Bicubic.

**Comment by hrydgard** [comment]
Really? In what cases does it reduce flickering?

**Comment by Narugakuruga** [comment]
Monster Hunter Portable 3rd HD, the "CAPCOM" Logo.

**Comment by hrydgard** [comment]
When texture scaling is off, Deposterize doens't do anything - it's just a minor modifier to the output of the texture scaler. But if that's the only flicker that's fixed, that's not very strong argument for keeping it, heh.

**Comment by hrydgard** [comment]
Seems from other discussion that at least most of the modes have some purpose, I'm closing this.

**Comment by Narugakuruga** [comment]
But sir will bicubic move to textures filtering? Because it's definitely better than linear.

**Comment by hrydgard** [comment]
yes I will, later.
