### ISSUE TITLE
UI Checkbox always On in the latest build v1.7.5-399-g60bd2d8a6

### ISSUE THREAD

**Issue by Emulatorer** [hrydgard/ppsspp#11761]
### What happens?
All CheckBox is on even if I turn it off

### What *should* happen?
CheckBox can turn off

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Android 5.1
Mali-450 GPU
1.4GHz Octacore
### Video File
This video will tell the issue
[recording_ppsspp.zip](https://github.com/hrydgard/ppsspp/files/2827842/recording_ppsspp.zip)

**Comment by hrydgard** [comment]
I'll fix, it's from #11758.
