### ISSUE TITLE
Super Robot Taisen A Portable - Map Movement Area overlay drawing issue

### ISSUE THREAD

**Issue by PikachuEXE** [hrydgard/ppsspp#11779]
### What happens?
The colored overlay area drawn is not in squares (Direct 3D 9, OpenGL)
Reproduced with 1.7.4 windows version, iOS 1.7.5 (build from source)
![uljs00143_00000](https://user-images.githubusercontent.com/1018543/52511648-e51bae80-2c3b-11e9-9b5e-b044c97b2fb1.jpg)

### What *should* happen?
This is 
![uljs00143_00001](https://user-images.githubusercontent.com/1018543/52511649-e5b44500-2c3b-11e9-80e5-6801aaa470eb.jpg)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
- Windows 7, PPSSPP 1.7.4, NVIDIA GeForce GTX 980 Ti
- iOS 12, PPSSPP 1.7.5 (build from source)

Let me know what other details I can provide

**Comment by unknownbrackets** [comment]
I feel like this game used beziers.  This still happens with Vertex Cache off and Hardware Tessellation off, right?

Does it not happen with Direct3D 11 and Vulkan (on Windows)?

Could you try exporting a GE frame dump?  These help a lot.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by PikachuEXE** [comment]
I can't test with Vulkan, keep getting #11599
But works fine with Direct3D 11

Here is the dump: (with windows 1.7.4)
[recording.zip](https://github.com/hrydgard/ppsspp/files/2847382/recording.zip)

**Comment by PikachuEXE** [comment]
I tried testing again with `v1.7.5-431-g9736bc431` and it seems the issue is gone
Tried with window version (download from https://buildbot.orphis.net/ppsspp/index.php)
and iOS version (commit checked out & built from source)
Tested with OpenGL, Direct3D 9, Direct3D 11, Vulkan (on iOS I can only test OpenGL)
(Yup #11599 does not happen with Vulkan with `v1.7.5-431-g9736bc431`)

**Comment by unknownbrackets** [comment]
Ah, that's great.  Thanks for reporting.

-[Unknown]
