### ISSUE TITLE
installation retropie / odroid Xu4 impossible, compilation fails

### ISSUE THREAD

**Issue by karatoso** [hrydgard/ppsspp#11778]
Hello community, thank you for all the help you can bring me. I am looking to compile this superb emulator on Odroid Xu4 to integrate it with a Retropie image. The installation provided by Retropie fails. What could I do for this emulator to install correctly?

[Installation logs on Retropie](https://pastebin.com/SwJfYVvE)

(ubuntu-18.04.1-4.14-minimal-odroid-xu4-20181203)

**Comment by unknownbrackets** [comment]
See #11344.  It looks like you're trying to use v1.5.4 which is an old version.  The current stable version is 1.7.5.

-[Unknown]

**Comment by karatoso** [comment]
oh I did not see that ! I'm going to edit the Retropie script, thanks a lot! I will look at it

**Comment by karatoso** [comment]
I tried with the installation process of Odroid Magazine, latest version taken into account, ppsspp compiles well, sdl2 library installed and updated. I end up with these errors at runtime? an idea ?

[article Odroid Magazine](https://magazine.odroid.com/article/building-ppsspp-for-ubuntu-on-the-odroid-xu3-xu4/)

`E: VulkanLoader.cpp:339: Failed to create vulkan instance.
Vulkan is not availabe.
Failed to initialize SDL with joystick support. Retrying whitout.
Unable to initialize SDL: No available video device`

**Comment by karatoso** [comment]
The gpu Mali T628 of the Odroid xu4 does not seem to support Vulkan, an idea to compile ppsspp without Vulkan but rather openGl?

**Comment by hrydgard** [comment]
Hm, it should have automatically fallen back to OpenGL, if it doesn't that's a bug...

**Comment by karatoso** [comment]
oh I have the creator online, thank you for your work, a pure pleasure this emulator, I have it on Pc under windows, but I would like to get it to work on Odroid Xu4 in its latest version! Thank you for your help !

**Comment by unknownbrackets** [comment]
https://github.com/hrydgard/ppsspp/blob/80e7f083e3935033b017097ab9f6d912f0b6ff20/SDL/SDLMain.cpp#L407

I think the Vulkan errors are unrelated, it's just logging that Vulkan was not detected which is completely correct and expected.

The SDL error seems to be separate, see here:
https://retropie.org.uk/forum/topic/18504/retropie-on-odroid-xu4-ubuntu-18-emulationstation-issues/4
https://discourse.libsdl.org/t/sdl2-not-working-without-x11-mode-in-odroid/24669/12
https://github.com/RetroPie/RetroPie-Setup/issues/586

I don't have an ODROID but it looks like this is a common problem, but it's a bit unclear to me if it just means starting multi-user mode or recompiling SDL or what to fix it.  But it doesn't seem to be a problem with PPSSPP.

-[Unknown]

**Comment by karatoso** [comment]
Thank you for your help, tell me, I read in your articles link that Sdl does not seem to work without x11, so recompile sl2 with kmsdrm to hope to use it under Odroid xu4
Excuse my lack of knowledge on the subject, but what is kmsdrm?

**Comment by unknownbrackets** [comment]
KMS stands for "Kernel Mode-Setting (KMS)", and DRM for "Direct Rendering Manager".  Basically, when you change your resolution on Linux, it used to be handled by a program running as a service, and now it's handled directly by the OS.

I don't know enough about SDL to know how it needs to be compiled, but according to this post:
https://discourse.libsdl.org/t/can-we-now-use-sdl2-without-x11/23421/2

> The option for configure is --enable-video-kmsdrm.

That seems worth trying.

-[Unknown]

**Comment by unknownbrackets** [comment]
Did that help?  Have you gotten this working?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
