### ISSUE TITLE
killzone liberation heavy lag & 1 fps on start menu

### ISSUE THREAD

**Issue by kyousuke77** [hrydgard/ppsspp#11789]
screenshot:
https://ibb.co/LRTKshc
other game work perfectly like crisis core final fantasy vii,final fantasy type 0 but killzone liberation seems have a problem,when on the start menu.
Fps are dropping to 1 fps but only in start menu.
ppsspp 1.7.5
xiaomi redmi 4a

**Comment by Emulatorer** [comment]
Duplicate #6207?

**Comment by kyousuke77** [comment]
> Duplicate #6207?

yep,same problem

**Comment by hrydgard** [comment]
Closing as duplicate, tagging #6207 for investigation
