### ISSUE TITLE
Thrillville Off The Rails - vertex range culling breaks it

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#11781]
Turns out that vertex range culling is killing every vertex in the game! What gives...

Here's a GE capture:

[ULES00889_0001.zip](https://github.com/hrydgard/ppsspp/files/2847728/ULES00889_0001.zip)

**Comment by unknownbrackets** [comment]
I've been slammed recently, but I'm pretty sure the viewport Z accounting is wrong in the depth range uniform calculation.  I was testing a fix with some games but need to get back to it.

-[Unknown]
