### ISSUE TITLE
Formula 2006 menu text issue (all backends)

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#11782]
How it Is looks like:
![screenshot_2019-02-09-16-53-32-085_org ppsspp ppsspp](https://user-images.githubusercontent.com/33152267/52522907-972e9700-2c8b-11e9-8ad3-50805d3d715c.png)

How it would lookslike:
![screenshot_2019-02-09-16-58-31-862_com google android youtube](https://user-images.githubusercontent.com/33152267/52522953-2e93ea00-2c8c-11e9-93d4-7fb1e4cf441d.png)

**Comment by unknownbrackets** [comment]
Does this happen even with vertex cache, lazy texture caching, and retain changed textures off?

Could you try exporting a GE frame dump?  These help a lot.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by marosis** [comment]
1. Yes it Is happen with every settings.
2. No i can't because online GE dump never working for me

**Comment by Panderner** [comment]
I can't produce this in Latest build:
![Screenshot_2020-11-25-21-48-05-26_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/100236137-3ce9ed80-2f68-11eb-84a6-40345310af4d.png)
![Screenshot_2020-11-25-21-41-37-28_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/100236178-48d5af80-2f68-11eb-8f86-25f800a5a4c7.png)

Here's a GE Dumps:
[GE DUMP.zip](https://github.com/hrydgard/ppsspp/files/5597073/GE.DUMP.zip)

**Comment by hrydgard** [comment]
In that case, I'm just gonna close it. Thanks for testing!

**Comment by Panderner** [comment]
this also not happen for this issue in latest stable version.
