### ISSUE TITLE
Last Ranker graphics corruption issue (user-reported through email)

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#11791]
[SVID_20190129_180137_1.zip](https://github.com/hrydgard/ppsspp/files/2850273/SVID_20190129_180137_1.zip)

Very strange graphics corruption. I'm trying to collect more information from the reporter.

**Comment by unknownbrackets** [comment]
Complete guesswork, but to me it looks like it's clearing with an alpha check or something, and some sort of dual source blending issue.  But who knows really.

-[Unknown]

**Comment by ppmeis** [comment]
Tested with latest Windows build, default settings. No issues:

![issue2](https://user-images.githubusercontent.com/4381277/60810270-018d2a00-a18d-11e9-981d-df225a4d996d.gif)

I also notice user video is translated to english. It may be a patched game.

**Comment by Emulatorer** [comment]
I will test this game lately and see if it's ok on my Mali-450 GPU android phone :)

**Comment by Emulatorer** [comment]
The game is very lag in menu
![Screenshot_2019-08-16-21-15-29](https://user-images.githubusercontent.com/37603562/63170191-5749d180-c06b-11e9-8760-7a8e3ddc2a43.png)
I also noticed during saving point the game fps is change from 30/30 - 60/60 fps
![Screenshot_2019-08-16-21-12-42](https://user-images.githubusercontent.com/37603562/63170298-924c0500-c06b-11e9-994f-ac409eceb4ad.png)
But running smooth during gameplay solid 30/30 fps
![Screenshot_2019-08-16-21-12-48](https://user-images.githubusercontent.com/37603562/63170367-b3acf100-c06b-11e9-8e52-27883429a39d.png)
I only got a few graphical glitches before fight scene or pausing the game :/
![Screenshot_2019-08-16-21-15-52](https://user-images.githubusercontent.com/37603562/63170480-ee168e00-c06b-11e9-92c0-d2330f1c15c4.png)

**Comment by Emulatorer** [comment]
Here's the dump:
[Menu_Dump.zip](https://github.com/hrydgard/ppsspp/files/3509787/Menu_Dump.zip)
[Last_Ranker_Dump.zip](https://github.com/hrydgard/ppsspp/files/3509789/Last_Ranker_Dump.zip)
I'm hoping you can fixed this before v1.9.0 is released @hrydgard :)

**Comment by unknownbrackets** [comment]
The text thing is #10967.

-[Unknown]

**Comment by Emulatorer** [comment]
I tested this game in my Tablet w/ Mali-T720 GPU and mt8163 CPU the game is running smooth without graphics glitches except the text maybe because this game is English Patch??

**Comment by Emulatorer** [comment]
I tested this game using the latest beta build v1.9.3-500 in it's ok no graphics glitches 🤷

**Comment by Gamemulatorer** [comment]
Mali 400 MP1 GPU
![Uploading Screenshot_20200604-144330.png…]()
![Screenshot_20200604-144218](https://user-images.githubusercontent.com/37603562/83724141-5aea2b80-a672-11ea-914c-37bb38f4975d.png)
Using PPSSPP v1.9.3-998

**Comment by Gamemulatorer** [comment]
Using PPSSPP v1.9.3-998 on Mali 400 GPU
![Screenshot_20200604-144942](https://user-images.githubusercontent.com/37603562/83724364-bd432c00-a672-11ea-912d-ee8d5a0aca26.png)
![Screenshot_20200604-144330](https://user-images.githubusercontent.com/37603562/83724369-bfa58600-a672-11ea-98a7-eae4236d98da.png)
![Screenshot_20200604-144218](https://user-images.githubusercontent.com/37603562/83724375-c207e000-a672-11ea-9dba-ac99a93cf78d.png)

**Comment by hrydgard** [comment]
I think that's enough confirmation, closing as fixed even though we don't know what did it.
