### ISSUE TITLE
Implement incompatible controller? RED DRAGON HARROW

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#11794]
Is possible implement to ppsspp controller? Name is: RED DRAGON HARROW. Controller is incompatible on android and do nothing but is connected with USB OTG.
It is only one controller from this developer

**Comment by hrydgard** [comment]
Does it work with other games on Android?

**Comment by marosis** [comment]
No it is not. This gamepad isn't for android but you can still connect it.

**Comment by hrydgard** [comment]
If there are no Android drivers for it, there's not much we can do. Writing custom USB communications code for a rare controller is a bit out of scope....

**Comment by marosis** [comment]
Understand
