### ISSUE TITLE
We should warn user that original fonts are missing, when running the few games that require them

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#11796]
Just like we now warn if buffered rendering is off for games that require it, we could also warn if the user does not have original PSP fonts installed.

Some affected games: 

Jeanne D'arc
Exit
Boxer's Road 2 The Real

**Comment by Anuskuss** [comment]
I have a better solution for this. Just ask the user to supply a [PS3 System Software Update](https://www.playstation.com/de-de/get-help/ps3-system-software/) file. Inside the pspemu path (`PS3UPDAT.PUP\update_files.tar\dev_flash.tar\pspemu`), there is is `flash0\font` folder which includes all the fonts found on a real PSP (hashes match with my dump from 6.60). RPCS3 requires the user to install the firmware so you can [check out their implementation](https://github.com/RPCS3/rpcs3/blob/2b8890b1936e10ae87437d842c62e0c3d1f02e2e/rpcs3/rpcs3qt/main_window.cpp#L471).

We could even go a step further and do that automatically (or at least less manually) by getting the [latest update](http://fus01.ps3.update.playstation.net/update/ps3/list/us/ps3-updatelist.txt) and downloading it for them. What do you think?

**Comment by hrydgard** [comment]
Huh! That's actually a really interesting idea.

**Comment by Panderner** [comment]
@nassau-tk can you test Boxer's Road 2: The Real?

**Comment by nassau-tk** [comment]
@Panderner 

No,l can't.

**Comment by Panderner** [comment]
> @Panderner
> 
> No,l can't.
> What's happen?
> Is it related this topic?

Yes @nassau-tk Boxer's Road 2 has text glitches for the comparison:

Older versions of PPSSPP:
![Screenshot_2020-11-30-18-22-40-46](https://user-images.githubusercontent.com/37503397/100598232-6aa0af00-3339-11eb-8f0f-0344fb3d4f89.png)
![Screenshot_2020-11-30-18-22-52-73](https://user-images.githubusercontent.com/37503397/100598245-6ecccc80-3339-11eb-8ee2-7785fb6a7687.png)
![Screenshot_2020-11-30-18-23-04-41](https://user-images.githubusercontent.com/37503397/100598255-72f8ea00-3339-11eb-8331-428b618c47af.png)

Real PSP Font:
![Screenshot_2020-11-30-18-21-42-37_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/100599264-c28be580-333a-11eb-9174-d3cf07b8ee27.png)
![Screenshot_2020-11-30-18-21-49-43_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/100599378-ea7b4900-333a-11eb-8ce5-3ddd36cc313c.png)
![Screenshot_2020-11-30-18-21-58-11_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/100599989-accaf000-333b-11eb-8872-b6bee19eac3c.png)

Latest build font:
![Screenshot_2020-11-30-18-27-07-88_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/100600461-47c3ca00-333c-11eb-8046-affe9a655b0c.png)
![Screenshot_2020-11-30-18-27-14-71_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/100600482-4c887e00-333c-11eb-8370-950d48f45817.png)
![Screenshot_2020-11-30-18-27-27-24_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/100600495-514d3200-333c-11eb-9ef3-5c03bfc0b3c6.png)

**Comment by hrydgard** [comment]
It seems like there's a very clear improvement, at least, and the new font is quite readable, if a bit wiggly. It appears to me that subpixel offsets are not right with the new fonts, leading to the wiggly look.

**Comment by nassau-tk** [comment]
You want say "Please imitate the shape more(More beautiful)"?
If you want say above then my answer is "Impossible!".
If I have more Knowledge and technique then it can do it.
But,I don't have it.

My purpose of font making is "That possible does minimum play".
- It must not crash by the font.
- It can read normaly.

It's immature, I'm sorry.:wink:

**Comment by hrydgard** [comment]
It's great as it is :)

**Comment by nassau-tk** [comment]
Thank you:sparkles:

>Actually I think we can even close this now, because I don't think any games really require the original fonts to work anymore?

Yes, I think(hope) so too.

**Comment by nassau-tk** [comment]
@hrydgard 
https://github.com/hrydgard/ppsspp/issues/13718#issuecomment-735402469
Please read & tell me this.
If you have a time.:wink:

**Comment by hrydgard** [comment]
I'm gonna go ahead and close this - let's reopen if we still find games that require the original font files to work.

**Comment by Anuskuss** [comment]
@hrydgard What about https://github.com/hrydgard/ppsspp/issues/11796#issuecomment-539194674? That's completely legal and would solve it once and for all.

**Comment by hrydgard** [comment]
That is absolutely a possibility, but seems a lot less urgent now given that we have these fonts, saving the user from an extra step of downloading those big update files.

**Comment by Panderner** [comment]
Umm yes Snake Warriors: Training requires the real PSP font to render the text correctly:

Current PPSSPP font:
![Screenshot_2020-12-01-10-20-10-41_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/100692321-8f426880-33c5-11eb-9723-a59944d485c0.png)
![Screenshot_2020-12-01-10-20-20-81_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/100692326-91a4c280-33c5-11eb-8abf-a19398d76c2f.png)

Real PSP font:
![Screenshot_2020-12-01-11-09-37-99_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/100692439-cb75c900-33c5-11eb-9573-9ee469ae36fb.png)
![Screenshot_2020-12-01-11-09-46-94_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/100692446-d03a7d00-33c5-11eb-8881-95abb18efb52.png)

@hrydgard can you reopen this?

**Comment by nassau-tk** [comment]
@Panderner 

Hey! Come here. #13718 

This games use ltn9.pgf.
It's my maked PGF font problem.

**Comment by Panderner** [comment]
and here's Eragon another that requires real PSP font to render correctly:

Current PPSSPP Font:
![Screenshot_2020-12-02-16-20-30-29_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/100852834-fcd3bf00-34c1-11eb-9ba3-c63b218135c8.png)
![Screenshot_2020-12-02-16-31-42-12_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/100853017-3ad0e300-34c2-11eb-940c-3089e8830f88.png)



Real PSP Font:
![Screenshot_2020-12-02-17-15-50-24_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/100853302-9307e500-34c2-11eb-9ede-081e483c7927.png)
![Screenshot_2020-12-02-16-49-49-87_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/100853325-99965c80-34c2-11eb-9c6c-94cc18f44e22.png)

**Comment by Panderner** [comment]
Reopen this Snake Warriors: Training and Eragon are remaining to requires real PSP font.

**Comment by Panderner** [comment]
and Here's Fieldrunners:

Current PPSSPP Font:
![Screenshot_2020-12-02-17-56-12-44_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/100857951-4b845780-34c8-11eb-86a6-adb98339b1a7.png)
![Screenshot_2020-12-02-17-55-56-39_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/100857970-5212cf00-34c8-11eb-848d-347f5be938e3.png)


Real PSP font:
![Screenshot_2020-12-02-17-56-47-64_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/100857990-58a14680-34c8-11eb-92d5-53163d8694d3.png)
![Screenshot_2020-12-02-17-55-27-60_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/100858010-5f2fbe00-34c8-11eb-82e5-76f4a08cea63.png)

**Comment by hrydgard** [comment]
Alright alright. At least it's greatly improved and it's mainly the line distance that's still an issue.

**Comment by nassau-tk** [comment]
@hrydgard 
I will check here too. :sweat_smile:

**Comment by nassau-tk** [comment]
Is this topic still need?:smile:

**Comment by unknownbrackets** [comment]
Thanks, very good to see these improvements.

-[Unknown]

**Comment by nassau-tk** [comment]
@unknownbrackets 
Thank you very much!
When you can say so from you, I'm very happy!

**Comment by Panderner** [comment]
It seems the letter i is missing in blazblue:
![Screenshot_2020-12-14-14-29-00-420_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/102048179-a0559580-3e19-11eb-8fc9-54427cf5e18d.jpg)
![Screenshot_2020-12-14-14-30-45-090_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/102048193-a64b7680-3e19-11eb-9d9c-f1a722ecf18d.jpg)
![Screenshot_2020-12-14-14-33-13-721_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/102048198-a9defd80-3e19-11eb-81e4-94915119c485.jpg)

**Comment by Panderner** [comment]
@nassau-tk can you help me out to fix the letter i in blazblue?

**Comment by nassau-tk** [comment]
@Panderner 

OK. I will check it.
And,Please create a new issue page about this.
