### ISSUE TITLE
Analog Stick doesn't work to move a character in Naruto Ultimate Ninja Heroes 3?

### ISSUE THREAD

**Issue by Emulatorer** [hrydgard/ppsspp#11793]
### What happens?
Analog Stick can't control to move a character that Im using

### What *should* happen?
It can move 🤔

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Phone Quick Specs:
Android 5.1
Mali-450 GPU
Tested on PPSSPP v1.3 - v1.7.5-450

### Screen Record Zip
https://www100.zippyshare.com/v/vJsX8ath/file.html

**Comment by hrydgard** [comment]
Just to be sure... does it work on a real PSP? It's been a long time since we had any controller issues like this.

**Comment by Emulatorer** [comment]
Sorry I don't have a PSP 😔

I will ask from my fb group that own a PSP for this issue

**Comment by hrydgard** [comment]
So can I close this? If the player character moves with the arrows but not the stick, it's very likely that it's simply how the game is coded.

**Comment by Emulatorer** [comment]
okey 🤔
