### ISSUE TITLE
Homebrew "Smashgpsp" reported not to be working

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#11819]
Got a report through email that this homebrew won't run. I'll take a brief look for 1.8.0, bumping it to the next version if it's tricky.

https://www.methodshop.com/gadgets/tutorials/pspinstallgames/index.shtml

**Comment by LunaMoo** [comment]
Seems to work fine for me. Althrough graphics require software rendering otherwise it will glitch out, blink or not show at all. Typical homebrew stuff.

**Comment by hrydgard** [comment]
OK, closing then.

**Comment by Panderner** [comment]
Software rendering is super slow on all Android devices even SD865, and i7 powered PCs

**Comment by hrydgard** [comment]
Yeah, that's just the way it is for now. Speeding up the software rasterizer in a more general way than I did for Darkstalkers is a massive project.
