### ISSUE TITLE
Screenshot key should be mappable

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#11816]
I got a feature request through email which I think is very reasonable - if you want to take screenshots of your progress when playing with a controller, or on platforms other than Windows where we don't have a shortcut key, it would be useful if it was mappable.

**Comment by marosis** [comment]
Is possible automaticaly create log?

**Comment by Abbanon** [comment]
I already have a similar issue up for this, from a few months back.
#10825

**Comment by hrydgard** [comment]
Ah duh, closing as duplicate then.
