### ISSUE TITLE
Spiderman 3 in-game hang (user report)

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#11811]
Got a report through email that this game works well initially but simply hangs 3-7 minutes into the main story. 

Reporter is on OPPO F1s (plus) android version 5.1, GPU MALI-T860.

**Comment by Emulatorer** [comment]
Similar #10196 🤔

**Comment by hrydgard** [comment]
Oh, I searched for Spiderman, not Spider-man. Darn.
