### ISSUE TITLE
Initial message screen empty on master banch

### ISSUE THREAD

**Issue by Salz** [hrydgard/ppsspp#11818]
I'm running a self-build version of the current master branch of ppsspp (commit 13c85b127d35648398001684045c7a45641fa517).

On startup, Final Fantasy IV Complete Collection gives me an empty screen (1st attachement), when there should be a message about the Auto-Save feature (2nd attachement).

git bisect traces the bug back to commit [9a5fbe5ea56ad7203c25b71253b4a14703ae8176] Savedata: Truncate detail if it's too long.

This commit introduces an additional parameter wrapHeight to PPGeDrawTextWrapped(), but the parameter is set to 0 in the calls in the files Core/Dialog/PSPMsgDialog.cpp, Core/Dialog/PSPNetconfDialog.cpp and Core/Dialog/PSPSaveDialog.cpp. This would try to wrap the text into a 0 height sized box, which fails and leaves the message area empty. I have no idea how high the wrapHeight parameter should be, but setting it to 150 seems to work.

Bad screen from current master (at commit 13c85b127d35648398001684045c7a45641fa517)
![ppsspp-bad](https://user-images.githubusercontent.com/2346918/53127971-fd58cb00-3563-11e9-95c7-fcbbb0b1ece8.png)

Good screen from 1.7-hotfixes branch (at commit 74d87fa2b4a3c943c1df09cc26a8c70b1335fd30)
![ppsspp-good](https://user-images.githubusercontent.com/2346918/53127978-00ec5200-3564-11e9-8737-ab5735fd6be4.png)

**Comment by Emulatorer** [comment]
Yes I also noticed that but forget to report here 🙂
![screenshot_2019-02-21-06-38-24](https://user-images.githubusercontent.com/37603562/53129787-7c212880-35a3-11e9-978c-9a5d16315a12.png)
![screenshot_2019-02-21-06-39-15](https://user-images.githubusercontent.com/37603562/53129799-880cea80-35a3-11e9-85a8-cccb93b476e1.png)

**Comment by unknownbrackets** [comment]
Oops, forgot to add the check after adding the scaling.  Fixed in b1146d8.

-[Unknown]
