### ISSUE TITLE
God of War: Chains of Olympus BIG performance hit

### ISSUE THREAD

**Issue by JhonLoveJoy** [hrydgard/ppsspp#11815]
Hardware: 

i5 3320M @ AMD HD 7570M
OS W7 x64

I'm comparing version 1.7.1 with the latest build(1.7.5 - 479). Why has the performance of GOW fallen so much? (50~60 FPS Stable -> 25~30 FPS )

I noticed the multi-core hack is gone, was that the problem?

_PS: I've tested on all APIs except the Vulkan due to lack of compatibility._

**Comment by hrydgard** [comment]
What multi-core hack? There wasn't one in 1.7.1.

I haven't seen anything close to what you are describing. Do you think you could test a few intermediate builds to narrow down the range?

**Comment by JhonLoveJoy** [comment]
Sorry. I tricked the name of the hack, the correct is  "prevent FPS from exceeding 60fps ". It seems that the bug affects only GOW.

**Comment by hrydgard** [comment]
Ah! Well, then we missed the game ID of the version of your game, now that we selectively enable that option only for this game, but automatically.

Can you rightclick or longpress the game, then tell me the game ID that's right after the name? It should look something like UCES01401.

**Comment by JhonLoveJoy** [comment]
Mine is this one: UCET00844

**Comment by hrydgard** [comment]
Alright, added that ID, should fix performance right up. GameFAQs (where I often look these up) didn't have that ID...  I hope there aren't too many more.

**Comment by marosis** [comment]
- GoW Chains of Olympus: UCUS-98653, NPUG-80325, NPEG-00023, UCET-00844, UCES-00842, UCED-00971 .
- GoW Ghost of Sparta: UCUS-98737, UCES-01401, NPEG-00044, UCES-01473, NPEG-90035.

**Comment by hrydgard** [comment]
Thanks, I think we got all of them now, with the addition of the list Unknown extracted from our reporting. Closing.

**Comment by marosis** [comment]
Here are all versions: https://forums.ppsspp.org/showthread.php?tid=22159

**Comment by unknownbrackets** [comment]
Actually, I think there are some missing from our reporting.  For example, reporting is definitely missing:

 * EU Chains of Olympus demo
 * Japanese demo IDs (PSN store says NPJG90095 for Sparta, other seems missing from PSN now...?)
 * Japanese full digital Sparta (NPJG00120)

Most likely several more.  Remember that the letters in the ID mean things.  NPEG90035 / UCKS45084:

 * N means digital, U means UMD
 * P means PSN published, C means first-party, L means licensed
 * E means Europe, K means Hong Kong according to what someone told me (might be Korea.)
 * Last one I don't know as well, there are S/M/H/Z/G are most common, D sometimes means Demo, T sometimes means Test, B sometimes means remaster.  I think Mini/etc. is noted here.

So when there's only one game with region K (UCKS45084) means it's at least suspicious that there's none for Sparta, although maybe there was no release.

I know I'm always saying it, but there are a lot of game ids.  Currently we know of almost 4400 from reporting (ignoring homebrew.)  That number has definitely grown in the last year.  Actual unique games is obviously closer to 1500 or something.

-[Unknown]

**Comment by hrydgard** [comment]
I think only Chains of Olympus was released in the east, at least officially.
