### ISSUE TITLE
Compiling for ARM64 GLES

### ISSUE THREAD

**Issue by 6alileo** [hrydgard/ppsspp#11825]
Hi there, I have a working script with patch for arm64 and GLES2. I would like to know what parameters to set for GLES3?

Do I simply change to `set(OPENGL_LIBRARIES GLESv3)` and `set(USING_GLES3 ON)`

```
include_directories(SYSTEM
  /usr/local/include
  /usr/include
)

set(ARCH_FLAGS "-O2  -march=armv8-a+crc -mtune=cortex-a73.cortex-a53 -mfloat-abi=hard -ftree-vectorize -funsafe-math-optimizations -pipe")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${ARCH_FLAGS}"  CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${ARCH_FLAGS}" CACHE STRING "" FORCE)
set(CMAKE_ASM_FLAGS "${CMAKE_ASM_FLAGS} ${ARCH_FLAGS}" CACHE STRING "" FORCE)

set(OPENGL_LIBRARIES GLESv2)
set(ARM64 ON)
set(USING_GLES2 ON)
set(USING_X11_VULKAN OFF CACHE BOOL "" FORCE)
set(USING_EGL OFF)
set(VULKAN OFF)
set(HEADLESS OFF)
set(USING_QT_UI OFF)
set(UNITTEST OFF)
set(USE_WAYLAND_WSI OFF)
set(USE_FFMPEG YES)
set(USE_SYSTEM_FFMPEG NO)
set(SIMULATOR OFF)
```

**Comment by unknownbrackets** [comment]
USING_GLES2 means GLES 2+, as compared to OpenGL.  GLES 1 is not supported.  There is no separate define for GLES 3+, it's automatically enabled.

The official Khronos recommendation is that the ES 3 library should be named libGLESv2 for forward compatibility.  So it's also still libGLESv2 - no changes should be needed there.

Do you not see GLES 3 detected in the logs and system information screen?

-[Unknown]

**Comment by 6alileo** [comment]
Got it. It's implied. Thanks.
