### ISSUE TITLE
XU4 PPSSPP only showing in bottom of screenl

### ISSUE THREAD

**Issue by Binxy2** [hrydgard/ppsspp#11821]
Since the latest Retropie release everytime I use PPSSPP it's squashed in the bottom left hand corner of the screen and no matter what I do with the options configurations it will not go full screen. Any ideas what's causing this issue as it was fine before?. I've reinstalled it from source and binary and it's still the same.

**Comment by unknownbrackets** [comment]
Are you using latest git or some older git / stable version?  Are you using USING_FBDEV or EGL?

-[Unknown]

**Comment by 6alileo** [comment]
They need to add the `--fullscreen` flag

**Comment by Binxy2** [comment]
How do you add the --fullscreen flag as I've been tearing my hair out trying to get it full screen again. Instructions much appreciated.

**Comment by unknownbrackets** [comment]
If you are compiling with USING_FBDEV, then:

 * Using 1.7.5 or lower, you'll have to add `--fullscreen` to the command line, i.e. `./PPSSPPSDL --fullscreen`.
 * Using the latest git build and 1.8.0 and later (once released), you will not have to do anything.  It will be fullscreen automatically.

What git sha are you using for your source builds?

-[Unknown]

**Comment by unknownbrackets** [comment]
Has 1.8.0 fixed this for you?

-[Unknown]
