### ISSUE TITLE
First time open apk set rotation=Auto

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#11832]

**Comment by hrydgard** [comment]
Is this a feature request or a bug? I don't think it's a good idea to set it to Auto, PSP games are best played horizontally.

**Comment by marosis** [comment]
I dont think it is a bug but would be good set AUTO landscape and landscape horizontaly

**Comment by hrydgard** [comment]
Ah yes, auto landscape is not a bad initial state.
