### ISSUE TITLE
Bundling SDL within PPSSPP on macOS

### ISSUE THREAD

**Issue by vit9696** [hrydgard/ppsspp#11830]
@hrydgard, last time I grumbled about it, @angelXwind said it was your desire not to bundle libSDL within PPSSPP builds on macOS. I think there was some misunderstanding from the sides here, and request it to be changed.

For instance, I do not use HomeBrew, and constantly having to fix provided binaries to locate the right lib (/usr/local/lib → /opt/local/lib) makes me unhappy. Putting aside having to install something like libSDL at all. I believe PPSSPP should launch on stock macOS without this mess.

Something as simple as the script below puts libSDL binary inside app Frameworks and makes the resulting build portable. I admit that Qt framework, which you also use, does exactly the same thing via `macdeployqt`, which is slightly more advanced.

```bash
SDL=$(otool -L PPSSPPSDL.app/Contents/MacOS/PPSSPPSDL | grep -Eo /.+libSDL.+dylib)
if [ "$SDL" != "" ]; then
  if [ -f "$SDL" ]; then
    SDLNAME=$(basename "$SDL")
    mkdir -p PPSSPPSDL.app/Contents/Frameworks || exit 1
    cp -r "$SDL" PPSSPPSDL.app/Contents/Frameworks || exit 1
    install_name_tool -change "$SDL" "@executable_path/../Frameworks/$SDLNAME" PPSSPPSDL.app/Contents/MacOS/PPSSPPSDL || exit 1
  fi
fi
```

I think we should include its invocation in cmake, and given that you use Travis, upload macOS builds to https://buildbot.orphis.net/ppsspp/index.php and/or some other place. I kind of hope to see release builds instead of snapshots too.

**Comment by hrydgard** [comment]
Yeah, I think I agree with this. Pull requests accepted :)

The buildbot situation needs improvement for sure. Will see what I can do...

**Comment by vit9696** [comment]
I guess everyone here likes pull requests way more than I do. Submitted a patch :)
Let it go through travis before merging. It worked fine for me with macports, but I did not have a chance to test it with homebrew. Also, is it too late for 1.9.0?

**Comment by hrydgard** [comment]
Definitely not too late, especially since we don't yet do official releases for Mac (though yes, we should).
