### ISSUE TITLE
Add Oculus Go support (port it to native GearVR app)?

### ISSUE THREAD

**Issue by PSzczepanski1996** [hrydgard/ppsspp#11833]
As title says - it would be nice to try cardboard/VR rendering on it.

**Comment by hrydgard** [comment]
Pull requests accepted ;)   I don't have a GearVR and PSP games don't really lend themselves very well to VR gaming anyway.

**Comment by HoshiYamazaki** [comment]
Yeah, they lack 60FPS/Hz rendering. But still, it's maybe nice to see it in the future.

**Comment by benderscruffy** [comment]
has this been added already or a work in progress ???

**Comment by hrydgard** [comment]
Oculus Go / Gear VR is not happening, but more modern VR is work-in-progress. Closing this.
