### ISSUE TITLE
Handle leak on Windows

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#11841]
Looking at PPSSPP in Process Explorer, there's a strange issue where handles to games appears as open files unexpectedly. It repros the easiest by just rightclicking on a game in the menu.

Really not sure where these are coming from, but they have the annoying side effect that you can't fully delete a homebrew game that you just played, and it's never good to leak handles so this needs to be fixed.

Possibly Windows-specific.

**Comment by hrydgard** [comment]
Seems we're somehow leaking LocalFileLoader objects. It feels like it has something to do with CleanRecent but not sure. Either way it's kind of awkward that CleanRecent will try to do ConstructFileLoader on directories, which tries to open them as files, which does succeed but is weird.

**Comment by unknownbrackets** [comment]
This might be what #11698 was getting at.

-[Unknown]

**Comment by hrydgard** [comment]
Huh, indeed. Anyway, caught it.
