### ISSUE TITLE
OpenGL Backend broken on some games (black screen with sound)

### ISSUE THREAD

**Issue by Abbanon** [hrydgard/ppsspp#11849]
I'm having issues with how to word this properly, but...

On the OpenGL backend, some games (not all) show up as nothing but a black screen for me.
I can still *hear* the games just fine, but I can't *see* anything in-game except for some menu screens. Getting to actual **gameplay** provides nothing but sound and a black screen, and this Windows notification:
![untitled](https://user-images.githubusercontent.com/37251822/53428228-6bfcb500-39b8-11e9-8103-8ff943c2f9b3.png)

(D3D9/D3D11 give me no issues. I can't test Vulkan.)

Both **Ace Combat X** and **Ace Combat Joint Assault** give me this issue.

Here's a GE dump of **Joint Assault**'s black screen:
[recording.zip](https://github.com/hrydgard/ppsspp/files/2906471/recording.zip)

**Comment by hrydgard** [comment]
What GPU do you have and (I don't think I have to ask you this, but) are the drivers up to date?

From your screenshot I deduce that the OS is Windows :)

**Comment by Abbanon** [comment]
On Win8.1, and it's an integrated Intel HD Graphics 4400 (Yes, laptop.) All drivers are up-to-date.
It's just confusing to me that D3D9&11 works fine across all games, but OpenGL is being selective and only works on some.

**Comment by hrydgard** [comment]
Old Intel OpenGL drivers are notably iffy. I don't plan to spend time on this since we have D3D to support these architectures. So closing as won'tfix, unfortunately.
