### ISSUE TITLE
Audio latency has no effect at all

### ISSUE THREAD

**Issue by leopard20** [hrydgard/ppsspp#11844]
I'm wondering if this option is broken or obsolete or something. It doesn't make any difference in any game I tried (even the extremes High and Low are the same)
~Or maybe it only doesn't work on Android and is meant for Linux and Windows?~

**Comment by hrydgard** [comment]
Yeah I've been meaning to get rid of it but everytime I try someone insists it does something noticeable :) 

It's a really small change to buffering in the audio code.

**Comment by Emulatorer** [comment]
If the two of this #8717 #10783 is being merged in v1.9.0 the audio problem in ppsspp is gone? 🤔

**Comment by leopard20** [comment]
I don't notice any problems with the audio at the moment (all games I currently play run at full speed, with occasional hiccups when the phone gets hot). I hope those changes won't break anything. And I sure hope the time stretching option is not gonna be the same as Dolphin's cuz that one is a mess really.

**Comment by hrydgard** [comment]
@Emulatorer , nope, unfortunately.

#8717 will not be merged, I'm gonna try a different approach. #10783 just affects a few games that use a specific way to decode audio.

**Comment by Emulatorer** [comment]
I noticed in the latest build of ppsspp for android the crackling sounds is getting noticable even my phone reach the maximum fps/speed or maybe my phone is getting slower 🤔

Sad to hear #8717 will not merged in v1.9.0? also #10783 not really fixed the crackling sounds?

**Comment by unknownbrackets** [comment]
Could we potentially remove this setting?

Does anyone actually get any benefit from altering these settings nowadays?

-[Unknown]

**Comment by leopard20** [comment]
I don't!

**Comment by Panderner** [comment]
How about lowering audio latency helps input lag on rhythm games?

**Comment by hrydgard** [comment]
That would be nice, turns out this option was never effective at doing that.

**Comment by leopard20** [comment]
I play Project Diva and DJ max games and I don't notice any difference even between High and Low latency settings.
