### ISSUE TITLE
Cannot find a wireless connection in warrior orochi 2

### ISSUE THREAD

**Issue by dikorommel** [hrydgard/ppsspp#11847]
screenshot
https://ibb.co/tbJmtNn
https://pasteboard.co/I2X22vE.png

**Comment by AkiraJkr** [comment]
Can confirm this is a issue.

**Comment by unknownbrackets** [comment]
Is this still an issue on the latest git build with recent networking improvements?

-[Unknown]

**Comment by ANR2ME** [comment]
This should already been fixed along with Ridge Racer 2 who had similar issue.
