### ISSUE TITLE
Homebrew install get cancelled, HTTP 302 mistaken as error

### ISSUE THREAD

**Issue by asl97** [hrydgard/ppsspp#11840]
### What happens?
PPSSPP Homebrew download not working.
HTTP 302 is mistaken as an error and installation get cancelled.
```
I: http_client.cpp:459: Completed downloading http://store.ppsspp.org/index.json to memory
I: http_client.cpp:459: Completed downloading http://store.ppsspp.org/icons/cavestory_icon0.png to memory
52:36:789 UI/Store.cpp:301 I[SYSTEM]: Triggering install of http://store.ppsspp.org/files/cavestory.zip
E: http_client.cpp:464: Error downloading http://store.ppsspp.org/files/cavestory.zip to /home/asl97/.config/ppsspp//ppsspp.dl: 302
52:37:157 Util/GameManager.cpp:110 I[HLE]: Download completed! Status = 302
52:37:157 Util/GameManager.cpp:121 E[HLE]: Expected HTTP status code 200, got status code 302. Install cancelled, deleting partial file.
```
### What *should* happen?
Homebrew install successfully.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Linux PPSSPPSDL V1.7.5  (commit 74d87fa2b4a3c943c1df09cc26a8c70b1335fd30)

**Comment by hrydgard** [comment]
Yeah, this should be fixed - but strange that you're getting 302, none of these files should redirect. running behind some mysterious proxy?

**Comment by asl97** [comment]
I should really had open up the ip address that I gotten redirected to.
I am just going to say it's yet another stupid Singapore ISP issue until proven otherwise.
```
http://103.1.138.144/store.ppsspp.org/files/cavestory.zip
http://103.1.138.144/ says www.Singaporeapp.com (Cdn Cache Server V2.0)
```

Running ppsspp with a proxy works instead.

**Comment by hrydgard** [comment]
Well, would be good if we handled that, so I'll leave it open. Just probably won't prioritize it right now.
