### ISSUE TITLE
Final Fantasy 4 rendering issues with DIRTY_CULLRANGE

### ISSUE THREAD

**Issue by Salz** [hrydgard/ppsspp#11850]
### What happens?

Final Fantasy 4 is missing some digits/text at the end of some lines. This happenes on 1.7.5 and current master branch (commit 593c3139bd4d92093691b130026b6a535146ccec). Digits at the end of numbers are missing at least in the bestiary, the time and gil display and the number of items already owned in shops. Letters at the end of long lines are missing in the story description of The After Years, and on some in game dialogue, too. See attached pictures for examples.

I bisected this to commit 67058495f5f67b7fe3177aaeaf1a4d6918794df3 - reverting it fixes the output on both 1.7 and master branch.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

I'm running the Qt:Linux build on Intel(R) Haswell Graphics (CPU G3450).

![bug1](https://user-images.githubusercontent.com/2346918/53434485-054abc00-39f7-11e9-999f-314214c8c403.png)
![bug2](https://user-images.githubusercontent.com/2346918/53434486-05e35280-39f7-11e9-914e-66ec607db3e7.png)

**Comment by hrydgard** [comment]
That commit by itself should be safe, it must be hiding some other bug....

**Comment by hrydgard** [comment]
Could you take a GE frame dump? 

https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

**Comment by Salz** [comment]
Zipfile contains the ppdumps for both Images of the original bugreport.



[ppdmp.zip](https://github.com/hrydgard/ppsspp/files/2907212/ppdmp.zip)

**Comment by hrydgard** [comment]
Thanks, that will help investigation.

**Comment by hrydgard** [comment]
Interesting, this seems to only affect the D3D 9 and OpenGL backends, Vulkan and D3D11 are fine.

**Comment by hrydgard** [comment]
The affected characters are drawn with a small-ish rectangular viewport including the bounding box of the letter and the bottom-right corner of the screen, while the working characters are drawn within a full screen viewport (their shadows with a 1px offset). Most likely we compute the wrong horizontal/vertical culling region for these.

**Comment by hrydgard** [comment]
In one example, CalcCullRange computes a minX  of -592 and a maxX of -236. Not easy for vertices with final clip space positions within approximately the -1...1 range to make it through that..  Something is wrong with the math.

**Comment by hrydgard** [comment]
@unknownbrackets  I know you said you don't have time this week, but you're the viewport master :)  I'm planning to release 1.8.0 around March 12 or so, if you have sec before then it would be great. If not, I'll dig into it myself. But this is definitely caused by CalcCullRange going wrong with viewports that we clip manually on platforms that don't support large ones.

**Comment by hrydgard** [comment]
This should now be fixed! Thanks unknown.

**Comment by hrydgard** [comment]
Oh, and thanks @Salz for the great bisection!

**Comment by Salz** [comment]
Thanks, I can confirm this issue is fixed in the current master branch.
