### ISSUE TITLE
Strange game crash on Monster Hunter Portable 3rd HD 

### ISSUE THREAD

**Issue by Abbanon** [hrydgard/ppsspp#11854]
I'm experiencing a very strange game crash every so often with MHP3rdHD on the `v1.7.5-522-g64dd4257a` Git build.
In short, I'll be in the middle of something (navigating menus, dialogue, etc) and the game will just... Stop. Black screen, no sound.
It's happened once when playing offline, and happened again when playing online.
The .exe itself doesn't crash, the game just full-on stops for whatever reason to a black screen. But PPSSPP still says the game is running.
I'm unable to do a GE Dump on the black screen, either from the remote debugger or the in-emulator one.
I've taken a screenshot of the Debug console, in hope that it will explain something:
![logcrashfull](https://user-images.githubusercontent.com/37251822/53540932-85e7e600-3ae5-11e9-9ad2-ddbfc5217b93.png)

**Comment by Abbanon** [comment]
Should also mention that this problem has never occurred before.

**Comment by hrydgard** [comment]
Sounds very odd. Could you try some older versions to try to pinpoint if this error was introduced recently? https://buildbot.orphis.net/ppsspp/index.php?m=fulllist

**Comment by unknownbrackets** [comment]
Does it ever normally log those thread wait errors?  They seem bad, but could be related to network threads misbehaving.

I hope the branch in the jump delay slot wasn't taken...

-[Unknown]

**Comment by Abbanon** [comment]
I will get around to trying this game on `v1.7.5-537-g2d5acc83b` eventually, to see if the issue comes up again. If it does, I'll work backwards from there to try and narrow it down. 
The only issue is, the two "crashes" I've experienced of this were very far apart, and seemingly random. So it will take a good chunk of normal gameplay of an unknown length to see if it will happen a third time.
I will post with results if I catch it again.

**Comment by Abbanon** [comment]
Alright, can confirm it happened again on build `537-g2d5acc83b`
![Untitled](https://user-images.githubusercontent.com/37251822/54247853-e6791900-4510-11e9-85fc-62f5ad6a8dd6.png)

**Comment by unknownbrackets** [comment]
The address of the jump is nearby, so now I think it is the delay slot.  That said, an initial screenshot of the disassembly shows only nops:
![Pre-game disassembly showing many nop instructions around a jump instruction](https://cdn.discordapp.com/attachments/480103153803460614/555210817545568260/Untitled.png)

Once in game it seems to (partially?) fill this in:
![In-game disassembly showing normal looking code around two jump instructions](https://cdn.discordapp.com/attachments/480103153803460614/555211546041516033/Untitled.png)

And there are indeed to `j`s next to each other.  It does look like actual code, so I don't think it's in outer space.  I wonder if the initial `j` was just not supposed to be there or was meant to be overwritten (it appears to be unchanged.)

That or it's accidentally depending on the behavior of a jump in a jump delay slot, which I think might have predictable behavior.

-[Unknown]

**Comment by Abbanon** [comment]
Closing this issue, I believe it was a strange bug being caused by a CWCheat that I completely forgot I had active/in use. After getting rid of that the issue seems to have gone away. Either that, or a recent build has fixed the problem.
