### ISSUE TITLE
Recommended Flags for Odroid N2 AARCH64

### ISSUE THREAD

**Issue by 6alileo** [hrydgard/ppsspp#11851]
Hi there,

I have PPSSPP compiled on an Odroid N2 with Mali FBdev drivers running OpenGLES 3.2.

During compile, I apply the patch below. I was wondering if there was any additional/removal of flags that could affect performance? Please take a look below. Thank you!

https://github.com/Retro-Arena/RetroArena-Setup/blob/master/scriptmodules/emulators/ppsspp/odroid-n2.armv7.cmake

**Comment by unknownbrackets** [comment]
A lot of performance is affected by GPU driver and jit, so as long as you're selecting the right CPU and getting hardware accelerated graphics, I'm not sure what else to recommend.  I suppose you could try `-03` (recommend benchmarking, may make no difference.)

Questions like this might be better for [the forum](https://forums.ppsspp.org/), though.

-[Unknown]
