### ISSUE TITLE
Small text in Disassembly view in High-DPI

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#11856]
As in title, pretty straightforward. We're not scaling the debugger text appropriately.

**Comment by unknownbrackets** [comment]
The web debugger, although more limited, is probably more accessible in many ways including this one.  That said, not heavily tested either...

-[Unknown]

**Comment by hrydgard** [comment]
Fair, but I still want to keep this one usable.

**Comment by unknownbrackets** [comment]
Yeah, definitely agreed - was just pointing out that among the various upsides and downsides of a web-based debugger, this aspect is definitely an upside.

-[Unknown]
