### ISSUE TITLE
ppsspp ios manually config remote streaming server

### ISSUE THREAD

**Issue by gt2416** [hrydgard/ppsspp#11858]
Running iOS 12.1.2 on iPhone X
ppsspp 1.6.3-456
When trying to manually configure remote disk streaming server, no keyboard pops up to manually enter the server ip or port. 
I have a apache2 server running which points to all my games but I need to manually configure the ip for it to work. Without that it wont automatically find the server. 
Is there a way to make my server automatically discoverable ? Or maybe the path to the settings file that I can manually enter the ip ?

**Comment by unknownbrackets** [comment]
You can just change it in ppsspp.ini.

-[Unknown]

**Comment by gt2416** [comment]
Thanks ! I didnt see the tag "LastRemoteISOServer" before. That worked. 

This is unrelated but my server does not work. 
What exactly does it expect in the index.html file ? I tried copying the index.html file from the server created by the ppsspp app. 
My apache page looks the same as the ppsspp hosted one on chrome.. any help would be appreciated. Most of the guides lead to expired forum links so I cant find any info.
This is my file
`<html>
<head></head>
<body>
<pre style="word-wrap: break-word; white-space: pre-wrap;">/
/GranTurismo.iso
</pre>
<style id="extraClass">.extraClassAspect {-webkit-transform: scaleX(1.35)!important;}.extraClassCrop {-webkit-transform: scale(1.35)!important;}</style>
</body>
</html>`

**Comment by unknownbrackets** [comment]
It normally expects a txt file, so you would need to configure it to serve text/plain i.e. index.txt.

Someone made it parse links in html files, like a standard directory listing output by Apache.

-[Unknown]

**Comment by gt2416** [comment]
Thanks for fast response. So made it serve a txt file and you can see it works here:
[https://www.dropbox.com/s/42d5lkpy2gn8e6f/psp.bmp?dl=0](url)

However its not able to find my server. I tried using the ip address and dns name, both dont work. It just says scanning. This is on both my ios and windows client.

**Comment by unknownbrackets** [comment]
To skip scanning, make sure LastRemoteISOPort is set (e.g. to 80) and you can set RemoteISOManual to true.  Make sure your Apache instance is not behind a firewall - try accessing the hostname from the browser on the phone.

-[Unknown]

**Comment by gt2416** [comment]
Thanks ! My bad, in the ip field I used http://, Using just the ip or hostname I can find my server. 
However as soon as I do it crashes :/
Ill use your wireless debugging tool and see if I can get any useful info. Thanks again you've been super helpful !

**Comment by gt2416** [comment]
I got the server to work mostly. It was crashing due to whitespace and a new line at the end of the file. 
I believe there was another issue where someone setting up a lighthttp server said it would say retrieving game list forever, this happened as well. 
Now my problem is that it only shows 1 game. Whatever game is on the last line. The syntax is 
/Game01
/Game02
right ? Whatever game is last is the only one that shows.

**Comment by unknownbrackets** [comment]
Hm - when you say crashing, do you actually mean crash (the iOS app would close), or just that it failed to connect / get any items?

You should definitely update to the latest git as there are improvements in the handling of the list and ipv6 which may fix issues like you're describing.  If there's still something you can put in the index file that makes PPSSPP crash, it's a bug that should be fixed.

In latest versions at least, it expects strictly filenames on each line.  They must end in ".cso", ".iso", ".pbp", or ".ppdmp".  Any other filenames (such as /debugger, which advertises remote debugging is enabled) are ignored.

My guess is your file probably uses Windows-style newlines (CRLF), which we don't currently support.  We should probably strip out the CRs if they are present.  If you use a text editor more advanced than Notepad, it may have an option to save with "Unix line endings".

-[Unknown]

**Comment by gt2416** [comment]
on iOS it would the whole app would freeze and on Windows it would just close. 
I managed to fix it by using vi on my server to make the index.txt file. Thanks, it seems the CRLF was probably the issue.

**Comment by unknownbrackets** [comment]
I think CRLFs are supported now, so I'm going to close this.

-[Unknown]
