### ISSUE TITLE
[UWP] ISO Load menu option no longer present

### ISSUE THREAD

**Issue by Toff-kun** [hrydgard/ppsspp#11855]
### What happens?
The latest UWP builds of PPSSPP no longer have the Load option for ISOs. This happened between February 09 and 21, 2019. Build 433 still has the Load option shown, build 490+ does not.

![image](https://user-images.githubusercontent.com/10385850/53572218-71522f00-3b73-11e9-8207-28d376ec7800.png)

### What *should* happen?
Load option should be shown above the Settings menu item as before.

![image](https://user-images.githubusercontent.com/10385850/53575229-cee97a00-3b79-11e9-96de-9d241f91df64.png)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Latest version checked is 1.7.5-534.
UWP ARM version.
Tested on Lumia 950 XL.

**Comment by hrydgard** [comment]
This is not intentional, I'll have a look.

**Comment by unknownbrackets** [comment]
Should the if around `topBar->Add(new Choice(mm->T("Browse", "Browse...")` also allow UWP?

Maybe it can/should become a runtime SYSPROP_HAS_FILE_BROWSER if...

-[Unknown]

**Comment by hrydgard** [comment]
Oh yeah, forgot we had that. That would be better, I'll take care of it.

**Comment by hrydgard** [comment]
Actually we currently don't support folder picking in UWP, only file picking. Can probably be added though.

**Comment by unknownbrackets** [comment]
Ah okay, the "should" screenshot had it so I guess it's good that's fixed.

-[Unknown]
