### ISSUE TITLE
Peter Jackson's King Kong: Touchscreen controls too slow

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#11865]
Got an email report from a user that our touch screen controls are too slow, but it works in Retroarch. Maybe it's a 30hz game and that is preventing us somehow from processing them timely? Maybe real clock sync would help?

"Hi. Here I want to report some serious problem about ppsspp. Please reply to this because is a critical!
I just played Peter Jackson's King Kong on my phone with ppsspp for Android.
Then I tried to tap repeatedly the ∆ button in this part of the game. But it ALWAYS FAILED! SO THE ANDROID PORT OF PPSSPP DOESN'T SUPPORT FAST TOUCH? OTHERS EMULATOR CAN RECOGNIZED THIS REPEATEDLY PRESS ONSCREEN BUTTON JUST FINE. BUT PPSSPP SADDLY NOT. Here is a proof I can press repeatedly the on screen button and past the scene, with your more slower libretro port. ..
I don't have external game controller. So I rely much on Onscreen button."

![screenshot_2019-03-03-06-14-55](https://user-images.githubusercontent.com/130929/53694183-8913f800-3dab-11e9-83be-f4206a265d2b.png)
![screenshot_2019-03-03-06-12-00](https://user-images.githubusercontent.com/130929/53694185-8d401580-3dab-11e9-94b5-f4156548cb91.png)

**Comment by unknownbrackets** [comment]
I thought we only processed touches once per CORE_NEXTFRAME, right?  So lag sync wouldn't help.  It may with an external controller.

-[Unknown]

**Comment by unknownbrackets** [comment]
it's possible this was related to the sceCtrl bug recently.

-[Unknown]

**Comment by unknownbrackets** [comment]
Have we heard any news about this issue?

-[Unknown]

**Comment by unknownbrackets** [comment]
Should we close this given we don't have any feedback?

-[Unknown]

**Comment by Panderner** [comment]
No more input lag on touch controls
