### ISSUE TITLE
Little big planet PSP problem when saving costumes and items

### ISSUE THREAD

**Issue by Anonimo11252** [hrydgard/ppsspp#11877]
I am a veteran playing Little big planet games and the emulator runs the game very well. But I can not save the items I make or the suits and I get an error that says. Critical dstrect offset x + extent> width Try to continue ?. When I say yes. Lost the vulkan device! Try continue ?. By putting if the message is repeated and when you put No PPSSPP it stops working. Please fix it. (I do not know much English because I'm Argentine and use the Google translator)

**Comment by hrydgard** [comment]
Which version are you using? Does this happen in the latest build from here? . https://buildbot.orphis.net/ppsspp/  

Because I think we might have already fixed this
