### ISSUE TITLE
[Ubuntu 18.04] Crash on start -- Vulkan is not Available

### ISSUE THREAD

**Issue by JeffBobbo** [hrydgard/ppsspp#11874]
Fresh Ubuntu 18.04 installation, NVidia 650 TI, using nvidia 390.77 (from nvidia-driver-390).
Using ppsspp-sdl from the PPA, executing in the terminal gives
```
I: VulkanLoader.cpp:290: Vulkan test instance created successfully.
E: VulkanLoader.cpp:293: Failed to count physical devices.
Vulkan is not available.
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  100
  Current serial number in output stream:  101
```

It ran correctly the first time, as did the Qt version; but since I've rebooted it's trying to use Vulkan and I don't know what to do to fix it. I tried setting the GraphicsBackend/RenderingMode in ppsspp.ini directly, but they already seemed to be set to OpenGL as far as I could tell. Fresh installs/clearing my configuration doesn't seem to work either.

**Comment by unknownbrackets** [comment]
The Vulkan message is just a log, it shouldn't be related.

Did you close this because you found the cause?  It might help other people searching for issues if you comment here on what it was.

-[Unknown]

**Comment by JeffBobbo** [comment]
I closed it because I rebooted and it worked; I'm guessing some driver or kernel update happened and a reboot as required.
