### ISSUE TITLE
Assassin's Creed Bloodlines [text textures issue]

### ISSUE THREAD

**Issue by Dreamer-4pda** [hrydgard/ppsspp#11870]
In Russian translation characters too close.
On original PSP all good with same iso:
![img_20190305_210236](https://user-images.githubusercontent.com/4630430/53828776-a73a4d80-3f8f-11e9-8e41-93f1182e8059.jpg)
![img_20190305_210420](https://user-images.githubusercontent.com/4630430/53828778-a73a4d80-3f8f-11e9-8dbe-69f5934cef59.jpg)
![img_20190305_210252_1](https://user-images.githubusercontent.com/4630430/53828779-a7d2e400-3f8f-11e9-9bac-f1b3265ceff4.jpg)
![img_20190305_210307_1](https://user-images.githubusercontent.com/4630430/53828780-a7d2e400-3f8f-11e9-8594-b528f1711bde.jpg)
Screenshots from PPSSPP:
![screenshot_20190305-213231_ppsspp](https://user-images.githubusercontent.com/4630430/53828828-c802a300-3f8f-11e9-912d-fc8dedc9fedb.png)
![screenshot_20190305-213326_ppsspp](https://user-images.githubusercontent.com/4630430/53828829-c802a300-3f8f-11e9-936c-57bf609a62bd.png)
![screenshot_20190305-213355_ppsspp](https://user-images.githubusercontent.com/4630430/53828831-c802a300-3f8f-11e9-8109-b359b020481f.png)
![screenshot_20190305-213435_ppsspp](https://user-images.githubusercontent.com/4630430/53828832-c89b3980-3f8f-11e9-97cc-f50a38d66e1f.png)

**Comment by Dreamer-4pda** [comment]
I tried edit textures, but no luck.

**Comment by AkiraJkr** [comment]
Did you try to dump your PSP's Font to PPSSPP? I believe this issue is caused due to using the stock font PPSSPP uses.

**Comment by Dreamer-4pda** [comment]
@AkiraJkr the game not use fonts, they use textures like that:
![09aade809798e31a0fc83939](https://user-images.githubusercontent.com/4630430/53855073-2e61e280-3fdd-11e9-93af-0e9bbd3ed1e3.png)
But I will try your solution
