### ISSUE TITLE
PPSSPP is crashing when hitting "Exit" after disabling 'Send Discord "Rich Presence" information'

### ISSUE THREAD

**Issue by 53SWYj3cV8nKsSr** [hrydgard/ppsspp#11881]
Problem:

If you disable 'Send Discord "Rich Presence" information', and then try to close the PPSSPP by using the "Exit" button in the main menu, the iPhone becomes unresponsive until reboot. On the other hand, if you don't disable the 'Send Discord "Rich Presence" information', the "Exit" button works as intended.

Environment:

* PPSSPP v1.7.5 
* iOS 12.1.4, iPhone 7 (No JB)

Steps To Reproduce:

1. Launch PPSSPP. 
2. Go to Settings -> Networking -> Send Discord "Rich Presence" information (third option)
3. Uncheck 'Send Discord "Rich Presence" information' option.
4. Return to main menu.
5. Click the 'Exit' button.
6. iPhone becomes unresponsive.

Notes:

* So I think this bug might be related to the issues found in #9186 because when I tried commenting out `syscall(SYS_ptrace, 0 /*PTRACE_TRACEME*/, 0, 0, 0);`, the problem was resolved.

* I have also tried changing the 'Send Discord "Rich Presence" information' default option to `false` instead of `true` when building the app. However, this didn't fix the issue.

**Comment by hrydgard** [comment]
Huh. Rather surprising that the Discord stuff would be involved..

**Comment by unknownbrackets** [comment]
Just to note, before Discord this issue still existed, but not for clicking Exit as far as I'm aware.

If PPSSPP is crashing/segfaulting in some exit path, it might change this behavior.

@53SWYj3cV8nKsSr does this behavior change in the latest git?  v1.7.5 is old at this point and v1.8.0 is soon to be released with many changes.  Included in them is also a CMake option to disable Discord, which might alter behavior on iOS where Discord was supposed to be disabled already.

-[Unknown]

**Comment by andyroid1023** [comment]
Hey man! Do you mind if you could share the ipa file for 1.7.5?

**Comment by hrydgard** [comment]
I think this one is likely fixed.
