### ISSUE TITLE
Strike Witches - Hakugin no Tsubasa  missing intro video

### ISSUE THREAD

**Issue by benderscruffy** [hrydgard/ppsspp#11898]
v1.8.0-3-gd6d6dbb77
missing the intro video nothing but a grey screen with the music and sound fx playing 
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/2973561/ppsspplog.zip)

**Comment by benderscruffy** [comment]
using v1.9.3-167-gb2dd3c7e1
still happens
psmf mpeg bug ???
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/4021422/ppsspplog.zip)

**Comment by unknownbrackets** [comment]
There's rendering happening during the video.  I wonder if it's a memory copy we don't detect.

Does it work during software rendering?

-[Unknown]

**Comment by benderscruffy** [comment]
no it doesnt work with software rendering

**Comment by Abbanon** [comment]
Are you playing in Buffered Rendering, or Non-Buffered Rendering? 
Because I've noticed Non-Buffered can visually break video playback in some games (Coded Arms for example, some videos appear black but still produce sound in Non-Buffered until you switch back to Buffered)

**Comment by benderscruffy** [comment]
playing with Buffered Rendering
