### ISSUE TITLE
(UWP) pls include flash0 shaders and lang folders and files

### ISSUE THREAD

**Issue by dominater01** [hrydgard/ppsspp#11894]
the build for uwp does not include them and ppsspp may need them for homebrew https://github.com/hrydgard/ppsspp/tree/master/UWP/Content

**Comment by dominater01** [comment]
the homebrew Triple Triad Requires there to be at least a font0 folder/files to work

unfortunately tho when you move these files over it stops asking but crashes on xbox one still even tho it works fine on pc

**Comment by Antx64** [comment]
#12031

**Comment by unknownbrackets** [comment]
Is this working now?

-[Unknown]

**Comment by hrydgard** [comment]
I believe this is working now.
