### ISSUE TITLE
Socom fireteam bravo 3 force close after complete level

### ISSUE THREAD

**Issue by dikorommel** [hrydgard/ppsspp#11896]
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/rolex/rolex:7.1.2/N2G47H/V10.1.1.0.NCCMIFI:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 8339, tid: 8381, name: Emu  >>> org.ppsspp.ppsspp <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x23ef323a30
    x0   0000002308e21480  x1   0000002308cde8c0  x2   0000000008e575a0  x3   0000000099888300
    x4   0000000000000000  x5   0000000000000000  x6   0000007facc49000  x7   000000000000a9db
    x8   0000007f8d9cef90  x9   0000007f823dd7b0  x10  0000007f80dd7630  x11  0000000000000008
    x12  0000000000000008  x13  0000000000001d10  x14  000000000000000c  x15  2e8ba2e8ba2e8ba3
    x16  0000000008aca954  x17  000000000000459c  x18  0000000000015180  x19  0000002309ffaa30
    x20  0000000000000000  x21  00000023ef323a20  x22  0000000000000000  x23  0000000008af98c4
    x24  00000000000023f1  x25  0000000020000000  x26  0000007f863c8000  x27  0000007f8d9dea70
    x28  0000002300000000  x29  0000007fa77f6050  x30  0000007f86492774
    sp   0000007fa77f6050  pc   0000007f86492948  pstate 0000000020000000

backtrace:
    #00 pc 000000000010a948  <anonymous:0000007f86388000>
    #01 pc 000000000010a770  <anonymous:0000007f86388000>

**Comment by Emulatorer** [comment]
Similar #10461?

**Comment by dikorommel** [comment]
yes
