### ISSUE TITLE
1.8 black bar visual artifacts in FFT

### ISSUE THREAD

**Issue by RosesAreDan** [hrydgard/ppsspp#11908]
What happens?
![20190318175625_1](https://user-images.githubusercontent.com/48698628/54569107-0b0d3f00-49b0-11e9-9cc6-82959590828b.jpg)

Some type of visual artifact in the black bar area of FFT. Tried changing almost all settings to no avail. Default settings also do not help. Not sure what to call it. The game is modded and I originally thought it was the issue, but after trying it out in different versions of PPSSPP I found that it only happens in 1.8

What *should* happen?
![20190318175918_1](https://user-images.githubusercontent.com/48698628/54569113-0f395c80-49b0-11e9-94b5-455c8940baa6.jpg)

What it looks like in default settings for PPSSPP 1.74

What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Nvidia 770 on Windows. Version 1.8 has issues and previous versions do not.

**Comment by unknownbrackets** [comment]
Is this only with some patch to unstretch the screen?  Could you try exporting a GE frame dump?  These help a lot.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

It'd also help if you could try a few builds in between 1.7.5 and 1.8.0.  If you go by halves, it should only take 9 tries to narrow it down pretty specifically:
https://buildbot.orphis.net/ppsspp/index.php?m=fulllist

Which graphics backend are you using (Vulkan, Direct3D 9, Direct3D 11, OpenGL)?  Does it happen on all of them for you?

-[Unknown]

**Comment by ppmeis** [comment]
Tested with latest Windows build. No issues:
![image](https://user-images.githubusercontent.com/4381277/64928488-3666ce80-d819-11e9-8753-edff17843ed9.png)

**Comment by LunaMoo** [comment]
Just to note here are at least two "patches" to achieve original/unstretched graphics in this game, one made by me for ULES-00850 version works and always worked perfectly fine:
![ULES00850_00003](https://user-images.githubusercontent.com/5485237/76708212-67a35700-66f5-11ea-9809-a24fed3bf6d7.jpg)
~ https://github.com/LunaMoo/PPSSPP_workarounds

 I have no idea how the other one works and why it fails, in fact I couldn't find the other patch without pre-patched warez, that's why I created my own back when I was interested in playing that game on PPSSPP, but at least people have a properly working alternative that also doesn't require piracy.

**Comment by hrydgard** [comment]
I'm gonna close this. If anyone runs into this, just use LunaMoo's patch.

**Comment by LunaMoo** [comment]
My cheat is only for EU version, so if anyone want's that patch for other regions and they differ aka EU version cheat doesn't work in other regions(ocassionally games might share executable file between regions making such cheats region agnostic), find this function in you game and post a similar screenshot:
![res function FFT](https://user-images.githubusercontent.com/5485237/76708514-a9cd9800-66f7-11ea-9bf6-5637628a836f.jpg)
So after starting a game open PPSSPP disassembly(windows only I guess) from the debug menu or pressing Ctrl+D, by for example starting at 8804000(type that in Go to field at the top left and press enter), press TAB once to see hexadecimal values of opcodes and search for(ctrl+s or ctrl+f) 0282A021, it should end around this place in third result.
