### ISSUE TITLE
[ Suggestion ] Ability to combine multiple shaders together?

### ISSUE THREAD

**Issue by WattanaGaming** [hrydgard/ppsspp#11909]
I already have a concept for this but I dunno if it will work.

I think if we pipe the output of one shader into another, we can combine the effect of two shader or more together.

Say I want to have both natural color and video upscale, I can pipe the output of the video upscale shader into natural color shader.

I really want to be able to use multiple shaders at once because it would even enhance the experience even more

**Comment by hrydgard** [comment]
There is support for doing it with some shader file editing:

https://github.com/hrydgard/ppsspp/pull/12905

I seem to recall that we had a PR with some easy UI for it too? Hm

**Comment by iota97** [comment]
UI is in #12924, I missed this issues in search so I forgot to mention it in the PR

**Comment by hrydgard** [comment]
Oh right, that PR had such an obscure name I couldn't find it, heh. Renamed it :)

**Comment by Gamemulatorer** [comment]
This can be closed now?
Postprocessing: User chain support #12924 already merge to main
