### ISSUE TITLE
Peace Walker Disappearing Graphics in Cutscenes

### ISSUE THREAD

**Issue by vegas487** [hrydgard/ppsspp#11901]
### Graphics disappear in certain cutscenes. Here Snake should be in the box.

https://cdn.discordapp.com/attachments/364177901064814615/556296284601057280/2019-03-15_2.png

I used disable stencil test and the graphics came back but were not restricted to the box, breaking most of the comic book style cutscenes with characters breaking out of their boxes and blocking each other

https://cdn.discordapp.com/attachments/412415837706911754/556383220220952596/54257831_2200576156874038_2202717262434009088_n.png

**Comment by hrydgard** [comment]
Please also try version 1.8.0.

**Comment by AkiraJkr** [comment]
For all I know this only happens in DX9, and only if you disable a few settings, I could be wrong, but I shall see and edit an response.

**Comment by vegas487** [comment]
> Please also try version 1.8.0.

I have now tried this version. It still has the same issue

**Comment by vegas487** [comment]
> For all I know this only happens in DX9, and only if you disable a few settings, I could be wrong, but I shall see and edit an response.

It happens in all the other backends too although in 1.8.0 on DX9 the issue was even worse with the screen being black

**Comment by unknownbrackets** [comment]
Could you try exporting a GE frame dump?  These help a lot.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by vegas487** [comment]
> Could you try exporting a GE frame dump? These help a lot.
> 
> See here for instructions - it's not hard and works on Android too:
> https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump
> 
> You can zip that and then drag and drop it into a reply here.
> 
> -[Unknown]

I don't know if I did this right but here it is:

[peacewalkerrecording.zip](https://github.com/hrydgard/ppsspp/files/2974671/peacewalkerrecording.zip)

**Comment by unknownbrackets** [comment]
Thanks, that's helpful.  Here's how it should look on a PSP:

![ULUS10509_#11901_missing_cutscene](https://user-images.githubusercontent.com/191233/54484153-960a0000-481d-11e9-9805-ca62260d204b.png)

And it looks almost correct in the software renderer (which is really slow, not suggesting this as a fix):

![ULUS10509_#11901_softgpu](https://user-images.githubusercontent.com/191233/54484162-a4581c00-481d-11e9-9937-f6d84cebf8f0.png)

The transparency is clearly a bit different, which is interesting.  At least the speech bubble looks more correct in Vulkan/etc.

Draw 86/560 at 09FC37C8 uses stencil values of 5 and 7, with a `& 3 == 3` test (so only the 7 values.)  This uses a tex uv scale, and normalized normal for texmap.

Draw 5/560 replaces the inner box with stencil=2. with a mask of 2.  This results in 3.  Draw 7/560 sets the 4 bit bringing it to 5 and 7.

However, we're ending up with stencil at 4.  It's correct at draw 10, but becomes wrong at draw 35, despite a stencil mask of 3.  I think it's a clear not respecting the stencil mask.

The speech bubble is drawn with color doubling and simple alpha blending.  Which points to a dumb mistake on my part, easy to fix to make the software renderer right.

-[Unknown]

**Comment by vegas487** [comment]
> Thanks, that's helpful. Here's how it should look on a PSP:
> 
> ![ULUS10509_#11901_missing_cutscene](https://user-images.githubusercontent.com/191233/54484153-960a0000-481d-11e9-9805-ca62260d204b.png)
> 
> And it looks almost correct in the software renderer (which is really slow, not suggesting this as a fix):
> 
> ![ULUS10509_#11901_softgpu](https://user-images.githubusercontent.com/191233/54484162-a4581c00-481d-11e9-9937-f6d84cebf8f0.png)
> 
> The transparency is clearly a bit different, which is interesting. At least the speech bubble looks more correct in Vulkan/etc.
> 
> Draw 86/560 at 09FC37C8 uses stencil values of 5 and 7, with a `& 3 == 3` test (so only the 7 values.) This uses a tex uv scale, and normalized normal for texmap.
> 
> Draw 5/560 replaces the inner box with stencil=2. with a mask of 2. This results in 3. Draw 7/560 sets the 4 bit bringing it to 5 and 7.
> 
> However, we're ending up with stencil at 4. It's correct at draw 10, but becomes wrong at draw 35, despite a stencil mask of 3. I think it's a clear not respecting the stencil mask.
> 
> The speech bubble is drawn with color doubling and simple alpha blending. Which points to a dumb mistake on my part, easy to fix to make the software renderer right.
> 
> -[Unknown]

A few other scenes have things missing at times but not many

**Comment by unknownbrackets** [comment]
Thanks for the detail in the report and verifying past versions.  This should be fixed by #11902, but it may not be merged for a little while in case we need urgent bugfixes for 1.8.1.

-[Unknown]

**Comment by vegas487** [comment]
> Thanks for the detail in the report and verifying past versions. This should be fixed by #11902, but it may not be merged for a little while in case we need urgent bugfixes for 1.8.1.
> 
> -[Unknown]

What is #11902?

**Comment by unknownbrackets** [comment]
Code changes that fix this issue (at least based on the dump you uploaded.)  I think it's likely they'll fix similar issues in other cutscenes in the game, but can't be certain (I don't have the game.)

Once those code changes are available in a git build (they are not yet), you'll be able to download it and try the fix.

-[Unknown]

**Comment by unknownbrackets** [comment]
You can find this fix in the git builds on the downloads page now.

-[Unknown]

**Comment by vegas487** [comment]
> You can find this fix in the git builds on the downloads page now.
> 
> -[Unknown]

Is this the link? https://github.com/hrydgard/ppsspp/pull/11902/commits/c5b844cc98bd544dd0fda68309be0b9bf4436393

I don't know how to download this. Sorry, I am pretty new here

**Comment by hrydgard** [comment]
@vegas487  no these: https://buildbot.orphis.net/ppsspp/ . The topmost one, the android download.

**Comment by vegas487** [comment]
> @vegas487 no these: https://buildbot.orphis.net/ppsspp/ . The topmost one.

Thank you! It works
