### ISSUE TITLE
Suggestion: Color palette and gamma level options for accurate emulation

### ISSUE THREAD

**Issue by Nashismo** [hrydgard/ppsspp#11911]
Hi:

I have been using the latest version of this emulator on Windows. I have a good enough PC so I run the games perfectly.

But I also recently bought a PSP 3000. And I realize that the color palette and the brightness/gamma levels are completely off.

The real hardware is more bright in terms of gamma levels, and the colors are much more vivid!

There is no shader that fixes this. There is the "natural" shader, and even though it makes the colors better, it actually makes the gamma/brightness even lower.

I would love to see an accurate representation of the PSP colors and brightness levels!

This is no minor thing, on the opposite, to me, this is EVERYTHING, FCE Ultra GX (a NES emu for the Wii) aims for accuracy and gives you the options for color palettes and the difference is oustanding!

Choosing the correct color palette can actually make the games look like they did on the real console.

I ask you for this KEY feature. It should not be so hard to implement and it shouldn't require shaders (a good thing because shaders add lag).

I use my PSP color space at: Wide.

So it should be like this:

Original PSP Color Space: Wide/Normal  (wide=vivid)
Original PSP gamma level: Yes/No          (yes=higher gamma)

Cheers and thank you, my best regards and thanks again.

**Comment by LunaMoo** [comment]
Different lcd's of different psp models had different colors, all pretty off to what games displayed. Ie. PSP 2000 has bluish tint whilewhile 3000 is oversaturated. You can use any coloring post process shader to get whatever your model of choice displayed with, a bit of tweaking, but they all were poor compared to modern lcd's. Also you don't want to mess with actual color palete of games, they sometimes depend on exact colors, post process effects like my customizable shader on forums are the way to go for re-coloring needs.

**Comment by Nashismo** [comment]
> 
> 
> Different lcd's of different psp models had different colors, all pretty off to what games displayed. Ie. PSP 2000 has bluish tint whilewhile 3000 is oversaturated. You can use any coloring post process shader to get whatever your model of choice displayed with, a bit of tweaking, but they all were poor compared to modern lcd's. Also you don't want to mess with actual color palete of games, they sometimes depend on exact colors, post process effects like my customizable shader on forums are the way to go for re-coloring needs.

I am asking for this feature and will continue to do so, I am not going to start an argument whether LCD's are poorer or better now or in the PSP years. The PSP "games" were meant to be played at higher gamma and wider color palette. Games were developed with these screens in mind.

And there are now shaders anywhere that I have found that do this, there are many shaders that do horrible saturated coloring and nothing in between. I think that if a weak console like the Wii can do different color palettes for NES emulators (without the need of shaders), PPSSPP could do it too.

**Comment by LunaMoo** [comment]
PSP games were not ment to do anything like PSP 3000 did, it's screen was rubbish and the games looked totally different on other PSP's. There's 5 different models with 5 different LCD's, you can't say games were designed to look as they did on particular LCD, it would not be true. Also as I said my customizable shader which can be found [here](http://forums.ppsspp.org/showthread.php?tid=6594) was made for tweaking. It's default settings does NOT matter and are just examples, among other effects which all can be turned off, it allows for all basic color corrections/tweaks.

 You can request all you want, but unless you write what you're requesting yourself, if it's an unnecessary thing which only you care about especially when it's easily done within existing system, don't be surprised that it will never be done.

**Comment by hrydgard** [comment]
Unlike the older consoles the PSP operates in truecolor and has no global color palette as such. The way to do this is indeed postprocessing shaders, and those don't add any noticeable lag. Try to tweak the natural colors one until the colors are to your liking, or write your own that does what you want. Contributions welcome.

For a true LCD experience we should also mix in a bit of the last frame which is not currently implemented, but I don't think you want that anyway.

**Comment by Narugakuruga** [comment]
https://github.com/jdgleaver/ppsspp_shaders

**Comment by Nashismo** [comment]
> 
> 
> https://github.com/jdgleaver/ppsspp_shaders

Wow thank you so much, this is looking great. I will test this. Thanks again.

**Comment by Nashismo** [comment]
> 
> 
> PSP games were not ment to do anything like PSP 3000 did, it's screen was rubbish and the games looked totally different on other PSP's. There's 5 different models with 5 different LCD's, you can't say games were designed to look as they did on particular LCD, it would not be true. Also as I said my customizable shader which can be found [here](http://forums.ppsspp.org/showthread.php?tid=6594) was made for tweaking. It's default settings does NOT matter and are just examples, among other effects which all can be turned off, it allows for all basic color corrections/tweaks.
> 
> You can request all you want, but unless you write what you're requesting yourself, if it's an unnecessary thing which only you care about especially when it's easily done within existing system, don't be surprised that it will never be done.

You must have a faulty unit, or you are heavily biased (for what reason I dont know), my PSP 3000 screen looks beautiful and it is the best in terms of black levels/contrast, viewing angles compared to the other PSP models.

That is I got a PSP 3000 in almost new condition, maybe that's the reason. Or maybe you are just talking out of your ass and haven't played on a real PSP in years.

Nevertheless, I will stick with my PSP though, no lag like on emulators (even PPSSPP), and no micro stuttering due to caching.

Thanks to hrydgard and Narugakuruga for their help, you guys are great, and Lunamoo, thanks for nothing, no contribution, just negative opinions.

**Comment by unknownbrackets** [comment]
There's no reason to get so harsh.  In 2008 people had strong opinions about the LCD, good and bad - and clearly, even in 2019 people still do.  That's okay, no reason to bare fangs and claws at each other.  I for one recognize everyone's [right to be wrong](https://xkcd.com/386/).

Just to note: another difference (that you probably also don't want) is that PPSSPP always renders graphics at 32-bit, rather than sometimes with 16-bit and dithering (as occurs on a real PSP.)

-[Unknown]

**Comment by Nashismo** [comment]
> 
> 
> There's no reason to get so harsh. In 2008 people had strong opinions about the LCD, good and bad - and clearly, even in 2019 people still do. That's okay, no reason to bare fangs and claws at each other. I for one recognize everyone's [right to be wrong](https://xkcd.com/386/).
> 
> Just to note: another difference (that you probably also don't want) is that PPSSPP always renders graphics at 32-bit, rather than sometimes with 16-bit and dithering (as occurs on a real PSP.)
> 
> -[Unknown]

I did not know the LCD thing was a heated issue back in the day :) But I personally like the PSP 3000 screens, but I guess it could always be in the eyes of the beholder.

And of course that was never my point, my suggestion was to "recreate" the PSP screens, wether they were good or bad was never my point, and it bothers me that there are people that take everything like it was a fight or an argument, that's ridiculous.

Thank you for that info also, things are making more sense.
