### ISSUE TITLE
Incorrect Text when loading the savegame

### ISSUE THREAD

**Issue by Drasikk** [hrydgard/ppsspp#11912]
### What happens?

When you load the game from an emulator save, a wrong text comes up.

### What *should* happen?

Has to put "Guarda la partida..." and not "Gruada la..."

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Samsung Galaxy Note 8 Oreo 8.0.0 Exynos. PPSSPP v1.8.0-14-gb0048525a

![PPSSPP_2019-03-21-15-24-11](https://user-images.githubusercontent.com/38067925/54759224-edc5b400-4bed-11e9-8e9b-a3cdb640ef4b.jpg)

**Comment by hrydgard** [comment]
Ah, just a minor translation error. I'll fix it up.
