### ISSUE TITLE
(Xbox One) No Way To Read Store Description

### ISSUE THREAD

**Issue by dominater01** [hrydgard/ppsspp#11919]
if i have a desc for a game and it hits the character limit the text gets cut off and theres no way to read it because the xbox one doesnt have a mouse the scroll the text so

can you make it so it either scrolls automatically or make it so we can toggle the text to read it?

**Comment by unknownbrackets** [comment]
We could set the description text view as focusable, but none of the descriptions are really all that long...

-[Unknown]
