### ISSUE TITLE
Menu in memory viewer is displayed improperly

### ISSUE THREAD

**Issue by WanderMax** [hrydgard/ppsspp#11913]
### What happens?
Menu in memory viewer is displayed improperly as below:
![2019-03-21 230632](https://user-images.githubusercontent.com/15909056/54762003-369d5d00-4c2e-11e9-965e-4e0295b20675.jpg)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Win10 x64 1809 4K screen 250% system ratio,  PPSSPP v1.8.0-14-gb0048525a

**Comment by unknownbrackets** [comment]
Probably related to #11856.

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, more coordinates that need scaling.

**Comment by hrydgard** [comment]
Fixed.
