### ISSUE TITLE
Crash when switching to Direct3D 11 on Windows 7 with Direct3D 11.0

### ISSUE THREAD

**Issue by CatKasha** [hrydgard/ppsspp#11914]
PPSSPP crash when switching to Direct3D 11 on old AMD GPU.

Windows 7 x64
GPU ATI Radeon HD5770, tried with latest stable driver 15.7.1 and nonWHQL beta 16.2.1
PPSSPP v1.8.0, tried x86 and x64

Logs from PPSSPPWindows64.exe --log
```
07:39:840 ui\nativeapp.cpp:384 E[LOADER]: Failed graphics backends: 2
07:39:840 core\config.cpp:557 E[LOADER]: Graphics backend failed for 2, trying another
07:39:957 thin3d\glrendermanager.cpp:745 E[G3D]: Defragment must not run on the render thread
07:39:957 common\msghandler.cpp:45 E[SYSTEM]: Critical: Defragment must not run on the render thread
```

**Comment by unknownbrackets** [comment]
That means that Direct3D 11 failed to initialize so it tried another, specifically OpenGL.  But then that failed in a different way.

The failure is strange, though.  Does OpenGL normally work fine - does this only happen when Direct3D 11 fails?

-[Unknown]

**Comment by CatKasha** [comment]
OpenGL and Direct3D 9 work fine (with game too), but if switch to Direct3D 11, PPSSPP crash
I also try different versions (1.5.4, 1.6.3, 1.7.4), all the same, PPSSPP crash when switching to Direct3D 11

After crash, if i open PPSSPP again, PPSSPP shows me a message "Defragment must not run on the render thread" with buttons yes/no, if i press the yes button several times, the message disappears and PPSSPP remains open with a black screen, and after closing PPSSPP, the PPSSPP process remains to work in the background

By the way, after several crashes, the PPSSPP switches to Direct3D 9

**Comment by WattanaGaming** [comment]
@CatKasha your GPU is probably too old

**Comment by hrydgard** [comment]
It's obviously too old to run D3D11 otherwise that would work, but it seems we have a bug in our error handling which should be worth fixing.

**Comment by CatKasha** [comment]
Radeon HD 5000 series and higher has Direct3D 11 support, and i can play games that have Direct3D 11 support
PCSX2 emulator also works with my GPU in Direct3D 11 (hardware) render mode, but maybe the performance of my GPU or processor is not enough to get 60 FPS

Maybe the problem is that my GPU does not support Direct3D 11 above 11.0 (information from GPU-Z), or the issue in the GPU or its driver :woman_shrugging:  
![screenshot](https://user-images.githubusercontent.com/19823797/54879927-1816ac00-4e50-11e9-943d-21851c49c32e.png)

**Comment by CatKasha** [comment]
Sooo, i installed Windows 10 x64 (10.0.17763) for the test, PPSSPP v1.8.0 x64 runs on Direct3D 11 backend and starts the game (tested only one game) without any problems
GPU-Z showed me that Direct3D 11 is now supported up to 11.5

I also found information that Direct3D 11.1 has backported to Windows 7 SP1, update KB2670838:
>https://support.microsoft.com/en-us/help/179113/how-to-install-the-latest-version-of-directx
>DirectX versions and updates by Operating System
>Windows 7 and Server 2008 R2

I installed the update and GPU-Z now writes about the presence of support for Direct3D 11.1, and now PPSSPP runs without problems on Direct3D 11 backend, i launched one game for the test and it worked fine (without error messages in Debug Console)

Happy end?

**Comment by hrydgard** [comment]
Not completely happy as I had thought PPSSPP would work with plain 11.0, and our error handling does seem faulty, but either way, it shows that the number of users affected by this is probably very small.

**Comment by benderscruffy** [comment]
please close as it hasn't been updated in years

**Comment by hrydgard** [comment]
Yeah, unlikely to look at this any time soon, and not getting any new reports of it.
