### ISSUE TITLE
Gran Turismo-Massive performance decrease in Menu→Cardealerships→Catalogue

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#11929]
Performance decrease from this
![Screenshot_20190324-132938](https://user-images.githubusercontent.com/33152267/54879594-fb23ae00-4e3a-11e9-81fe-b5f98d44ba95.png)
Into this
![Screenshot_20190324-132947](https://user-images.githubusercontent.com/33152267/54879601-070f7000-4e3b-11e9-9e8d-ef13fe1c0a15.png)

That Blue Is catalague. When you open it, you will get this performance decrease.
Tested OpenGL

**Comment by unknownbrackets** [comment]
Could you export a [GE frame dump](https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump) of the slow screen?  I'm not sure if it will be graphics related, but it's probable.

Also, if you turn on debug statistics in settings, a screenshot of what that shows on that screen would help too (it'll show various time measurements for the frame.)

-[Unknown]

**Comment by marosis** [comment]
![Screenshot_20190324-153715](https://user-images.githubusercontent.com/33152267/54880928-de8f7200-4e4a-11e9-94b8-3bc8ec7e5496.png)

**Comment by unknownbrackets** [comment]
It's definitely graphics then, although not all that many draw calls interestingly.  I think the GE frame dump would make it clear what all it's doing.

-[Unknown]

**Comment by marosis** [comment]
How i said: it's not working for me

**Comment by hrydgard** [comment]
The game is using a very stupid way of displaying text, it's writing a single character to a texture and performing a draw call, syncing, then writing another character to the same texture and performing another draw call.  This performs terribly in OpenGL especially, and that screen is just too full of text.

**Comment by marosis** [comment]
Understand

**Comment by unknownbrackets** [comment]
I guess it's possible that the "retain changed textures" setting might improve performance here, then.

-[Unknown]

**Comment by hrydgard** [comment]
Oh right, yeah possibly.
