### ISSUE TITLE
[Features Request] Auto scan storage for psp games?

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#11927]
### What happens?
Can we have searching games automatically so no need to locate psp games manually.

Other emulator have this feature so possible ppsspp can have this too :)

**Comment by unknownbrackets** [comment]
Just noting: At least for Android, this seems directly at odds with #11997.

-[Unknown]

**Comment by Emulatorer** [comment]
So do we need to close this for #11997?

**Comment by hrydgard** [comment]
I mean, it could still be useful for older devices and other operating system. But #11977 indeed throws a lot of wrenches into this and the general user experience. Need to come up with a plan soon...

**Comment by hrydgard** [comment]
I plan to get v1.10.0 out before tackling the storage issue.

**Comment by Gamemulatorer** [comment]
This is now impossible on android 11?

**Comment by hrydgard** [comment]
Yeah, will no longer be possible :( 

I'm closing, not worth the effort to do it only on older devices.
