### ISSUE TITLE
Burnout Legends - broken graphics on dx11

### ISSUE THREAD

**Issue by arnoldsecret** [hrydgard/ppsspp#11921]
### What happens?
Car models glitched up, sections of track randomly glitches out

### What *should* happen?
It should experience the same behavior as using OpenGL.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Intel HD Graphics (Bay Trail)
Windows 8.1
PPSSPP v1.8.0

**Comment by WattanaGaming** [comment]
I think the problem is a corrupted game ROM or a bad GPU. I tested the game on my PC and everything is normal.
![image](https://user-images.githubusercontent.com/25323231/54867191-ed751680-4daf-11e9-8737-b57efab29e99.png)

**Comment by arnoldsecret** [comment]
dx11 backend?

**Comment by benderscruffy01** [comment]
work properly for me too using dx11 backend

**Comment by unknownbrackets** [comment]
I'd suggest verifying the crc of the disc.  If googling the crc gives no results, you may have gotten a bad read.

-[Unknown]

**Comment by arnoldsecret** [comment]
ok so I verified the iso and it matches the redump crc32 of that game, yet problems still persist.

![Untitled](https://user-images.githubusercontent.com/41223243/54877198-45feef00-4e56-11e9-8ed6-d8349690bc90.png)
![Untitled2](https://user-images.githubusercontent.com/41223243/54877199-45feef00-4e56-11e9-870b-25171491e148.png)

it's definitely an issue with intel graphics.

**Comment by WattanaGaming** [comment]
> it's definitely an issue with intel graphics.

Have fun with your GPU going nuts lol

**Comment by Gamemulatorer** [comment]
#12836 any improvement

**Comment by WattanaGaming** [comment]
Ok I just realized my stupidity. After  a literal year, I realized I used an older version to check the problem.

**Comment by unknownbrackets** [comment]
Well, we did change something in a recent git build related to Intel cards, as @Gamemulatorer pointed out.  So it may have been specific to Intel indeed, especially if it's fixed now.

-[Unknown]

**Comment by WattanaGaming** [comment]
It's still very embarrassing though.

**Comment by Gamemulatorer** [comment]
This should be added to v1.10.0 milestone

**Comment by hrydgard** [comment]
@arnoldsecret  can you confirm again that it's working for you now, since you closed it?

**Comment by arnoldsecret** [comment]
haven't been checking this one out, but it might work now
