### ISSUE TITLE
Mali hardware bug: Image corruption in Burnout on Android P on Galaxy S8+

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#11937]
Large graphical glitches whether or not a "sun readback" (lens flare effect) is happening, looks like tile buffer invalidation problems or similar - or a depth issue of sorts.

I've confirmed that it's not our regression by testing older builds.

Here's what a GE dump looks like (in game it's slightly different since it's overdrawing the last frame but it's still clearly wrong):

![Screenshot_20190806-164431_PPSSPP](https://user-images.githubusercontent.com/130929/62550027-d2400a80-b869-11e9-9b99-e3b1af387f24.jpg)

And here's a download of the GE dump:

[ULUS10025_0001.zip](https://github.com/hrydgard/ppsspp/files/3472839/ULUS10025_0001.zip)

Tested on Galaxy S8+ (SM-G955F). Driver version "04000000".

**Comment by hrydgard** [comment]
I think this might be a case where two consecutive render passes to the same target are missing a pipeline barrier in between - I think we elide the subpass dependencies in that case.

**Comment by hrydgard** [comment]
Yeah, this is the old ARM Mali Z precision hardware bug rearing its ugly face again. Will try some workarounds before 1.9.0.

**Comment by hrydgard** [comment]
Hm, when the sky draws happen, which (might) be what breaks the Z buffer, the viewport depth is set to (MinDepth = 0, MaxDepth = 0). The rest of the frame is drawn with MinDepth = 1, MaxDepth = 0.

**Comment by hrydgard** [comment]
It really appears to be something around when gl_Position.z/gl_Position.w == 1.0.

This gets the sky to glitch out really weirdly but lets the rest of the graphics survive intact:

		WRITE(p, "  if (gl_Position.z/gl_Position.w == 1.0) gl_Position.zw = vec2(0.9999, 1.0);\n");

**Comment by unknownbrackets** [comment]
I thought we did it here?

https://github.com/hrydgard/ppsspp/blob/7790e61b12d016e5d9b97895f9d51f605398ff69/GPU/Common/SoftwareTransformCommon.cpp#L465

GPU_SCALE_DEPTH_FROM_24BIT_TO_16BIT still uses that wider range you describe when depth clamping is enabled by the game, in order to "simulate" depth clamping where unsupported.  Basically, anything <= 0.498047 is "zero" and anything >= 0.50193 is "one".  In theory, this is better than clipping graphics that should draw.

Hm, what makes it so the sky isn't improved by `gl_Position.zw = vec2(0.9999, 1.0);`?

-[Unknown]

**Comment by hrydgard** [comment]
It's improved in that it doesn't corrupt the Z buffer anymore, but the texture mapping gets really wacky, I guess we break perspective correction. In that hack, I should probably multiply by those factors instead of overwriting the values.

**Comment by hrydgard** [comment]
Ok, so the new "minimal" working hack is:

    WRITE(p, "  if (gl_Position.z == gl_Position.w) gl_Position.z *= 0.9999;\n");

**Comment by unknownbrackets** [comment]
Well, I suppose that doesn't seem that horrible, I'm sure it'll cause some unexpected depth testing issue but not like we don't already have weird depth issues on Adreno Vulkan too...

-[Unknown]

**Comment by hrydgard** [comment]
Updated the pull request with that.
