### ISSUE TITLE
Sengoku Basara - Graphical glitch (Android)

### ISSUE THREAD

**Issue by Saramagrean** [hrydgard/ppsspp#11931]
### What happens?

Graphics showing glitch, since v1.6.3-483-g1f881d790 (after Implement vertex range culling) occurs only in the OpenGL, on Vulkan is work well and happen on Android only.

![1](https://user-images.githubusercontent.com/26355472/54883767-dc093880-4e9b-11e9-80c8-e0d42f9d25f1.jpg)

### What *should* happen?

Last work v1.6.3-468-gad6938de5 or v1.8.0 recent build with Vulkan.

![2](https://user-images.githubusercontent.com/26355472/54883829-95680e00-4e9c-11e9-8b23-288d30450283.jpg)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Huawei P9+ (Kirin 955/Mali T-880/Android 8.0)

**Comment by unknownbrackets** [comment]
If I understand correctly, it's just the ground that is wrong, right?  Interesting that it's OpenGL only - might mean that it's related to depth clamping in some way.

Could you try exporting a GE frame dump?  These help a lot.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by Saramagrean** [comment]
Yes, graphical glitch on the ground and here GE dump.
[Dump (OGL).ppdmp.zip](https://github.com/hrydgard/ppsspp/files/3000727/Dump.OGL.ppdmp.zip)

![Screenshot_PPSSPP_20190325-015158](https://user-images.githubusercontent.com/26355472/54884210-c4807e80-4ea0-11e9-9c65-7888d5724b7b.png)

**Comment by unknownbrackets** [comment]
For me, that's drawing correctly on all backends, so it may mean that's specific to Mali-T880.  Just to confirm: you're using v1.8.0 or higher right?  There were some fixes to range culling depth handling recently.

For reference, it should look like this:
![NPJH50460_#11931_culling](https://user-images.githubusercontent.com/191233/54884790-2eae0a80-4e32-11e9-97f6-673130c8c078.png)

-[Unknown]

**Comment by Saramagrean** [comment]
Yes, I use PPSSPP v1.8.0-31-g8adb0dfd6.

**Comment by Saramagrean** [comment]
Samsung J7 (Mali T-720) 😂
![FB_IMG_1553463848371](https://user-images.githubusercontent.com/26355472/54886271-dec65680-4eb8-11e9-92de-ab1fbeb8398d.jpg)

**Comment by Saramagrean** [comment]
Lord of Apocalypse get same problem too.
[NPJH50503.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/3060634/NPJH50503.ppdmp.zip)

![Screenshot_PPSSPP_20190410-021920](https://user-images.githubusercontent.com/26355472/55829000-d6684f80-5b37-11e9-8936-5b509836798b.png)

**Comment by unknownbrackets** [comment]
Strange.  The draw happening there doesn't seem even close to being culled.

-[Unknown]

**Comment by Saramagrean** [comment]
Enable DepthHackRange for this game (or any game that encounter the same problem like Lord of Apocalypse, MGS:PW) It fixed graphical glitch on my device.

**Comment by Saramagrean** [comment]
Okay, fixed by https://github.com/hrydgard/ppsspp/pull/12227

Thank you. ヽ(´▽｀)/

**Comment by unknownbrackets** [comment]
Ah, great.  Thanks for retesting and reporting.

-[Unknown]
