### ISSUE TITLE
Untold Legends The Warrior Code Does not show the character to write (needs wide line emulation)

### ISSUE THREAD

**Issue by ghost** [hrydgard/ppsspp#11930]

**Comment by Drasikk** [comment]
Nose Yes later there is a problem using Vulkan.

**Comment by unknownbrackets** [comment]
Could you try exporting a GE frame dump?  These help a lot.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by Drasikk** [comment]
But How do I open it? With a Web browser? If Yes, it always shows me not connected to PPSSPP.

**Comment by unknownbrackets** [comment]
Ah.  Make sure you've enabled the debugger in PPSSPP's settings.  If that doesn't help, it may not be working on your device.

If you know someone else with the game, a frame dump from any device would still help.

-[Unknown]

**Comment by Drasikk** [comment]
Reviewing PPSSPP Folders I found this file. @unknownbrackets Is This what you asked me for?

[DUMP.zip](https://github.com/hrydgard/ppsspp/files/3051698/DUMP.zip)

**Comment by unknownbrackets** [comment]
I'm afraid that's not a frame dump, it looks like an executable dump.  If you have access to a computer running Windows, you can try the alternate method found lower down on this page:

https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

-[Unknown]

**Comment by Drasikk** [comment]
Only Vulkan.

[DUMP.zip](https://github.com/hrydgard/ppsspp/files/4353811/DUMP.zip)

![PPSSPP_2020-03-19-10-53-45](https://user-images.githubusercontent.com/38067925/77054574-3ca85400-69d0-11ea-9c7a-ffa0c8eb7775.jpg)

**Comment by unknownbrackets** [comment]
This simply uses LINES to draw the highlight.  It shows correctly in the dump for me on NVIDIA.

If you go to Settings -> Tools -> System information -> Vulkan features, you'll see a list of featured available and enabled.

Is "wideLines" available: 1 and enabled: 1?  Or are either of those 0?

It may be that this will work better at 1x PSP and only looks this way at higher render resolutions when wideLines is unsupported.  That means this probably needs #8276.

-[Unknown]

**Comment by Drasikk** [comment]
I don't get Vulkan features.

![PPSSPP_2020-04-04-09-19-56](https://user-images.githubusercontent.com/38067925/78421147-cbb29e80-7655-11ea-9e57-8d6ab4b2c038.jpg)

**Comment by unknownbrackets** [comment]
You have to switch to the Vulkan backend first, sorry.

-[Unknown]

**Comment by Drasikk** [comment]
@unknownbrackets 

![Screenshot_20200404-223732_PPSSPP](https://user-images.githubusercontent.com/38067925/78460904-3222d580-76c5-11ea-8432-e5fa251cef48.jpg)

**Comment by Panderner** [comment]
The bug still not fixed please reopen

**Comment by Panderner** [comment]
Ok it displays lines for this game for POCO M3 using Vulkan:
![Screenshot_2021-01-06-21-06-53-843_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/103771685-2a80ca80-5063-11eb-894a-6bece7b6f14c.jpg)

**Comment by Gamemulatorer** [comment]
Looks ok on my both phone?
![1631522378940](https://user-images.githubusercontent.com/37603562/133052523-05eb48df-2d08-435e-a722-85d3b0adea2f.jpg)

**Comment by Gamemulatorer** [comment]
Looks ok also on me
![Screenshot_2021-09-14-06-30-15-141_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/133164848-9f822758-9a48-4844-a752-09e43daffce8.jpg)

**Comment by unknownbrackets** [comment]
I haven't tested this, but #15076 may help on devices where wideLines is not supported.

-[Unknown]

**Comment by Panderner** [comment]
His deleted reporter's device is Samsung Galaxy Note 8 Exynos

**Comment by Gamemulatorer** [comment]
Galaxy Note 8 android oreo yeah I know that 😃
maybe this issue can be fixed by upgrading his android version 🤔

**Comment by unknownbrackets** [comment]
Based on the frame dump, this appears fixed.  I'm going to assume it's fixed and close.

If you're still seeing this issue in the latest git builds, please reply and we'll reopen.  If you're seeing another issue in this game, please open a new issue.

-[Unknown]
