### ISSUE TITLE
cant talk to hrydgard on discord anymore

### ISSUE THREAD

**Issue by dominater01** [hrydgard/ppsspp#11944]
i either have been blocked or discord is being stupid

can you send me a friend request on discord hrydgard

**Comment by AkiraJkr** [comment]
You can always ask to speak to him(without needing to tag) by visiting the #help_and_support channel if there is something you wanted to ask. His DMs are probably disabled to avoid the spammers that come on the server.

**Comment by marosis** [comment]
Close please. This Is issue tracker! Next time post only emulator issues please.

**Comment by hrydgard** [comment]
I had to block random DM:s, sorry. Friend added.
