### ISSUE TITLE
PPSSPP doesn't work 

### ISSUE THREAD

**Issue by Refanner** [hrydgard/ppsspp#11941]
Hi guys,
I've tried to install ppsspp on my mac i followed all the instructions but now the ppsspp doesnt work and i got this error report. Can anyone help me? thanks and sorry for the poor english.
P.S. My mac run High sierra 10.13.6

Report:
Process:               PPSSPPSDL [9267]
Path:                  /private/var/folders/*/PPSSPPSDL.app/Contents/MacOS/PPSSPPSDL
Identifier:            PPSSPPSDL
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           PPSSPPSDL [9267]
User ID:               501

Date/Time:             2019-03-26 23:56:13.922 +0100
OS Version:            Mac OS X 10.13.6 (17G65)
Report Version:        12
Anonymous UUID:        EC0FDA85-5143-E32E-3D31-0D4AD59EAAC9

Time Awake Since Boot: 10000 seconds

System Integrity Protection: enabled

Notes:                 Translocated Process

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib
  Referenced from: /private/var/folders/*/PPSSPPSDL.app/Contents/MacOS/PPSSPPSDL
  Reason: image not found

Binary Images:
       0x100ff8000 -        0x101f24fe7 + (??? - ???) <61D21A43-ACF7-3ED8-AA38-1B6721866E4B> /var/folders/*/PPSSPPSDL.app/Contents/MacOS/PPSSPPSDL
       0x10f650000 -        0x10f69aacf  dyld (551.4) <8A72DE9C-A136-3506-AA02-4BA2B82DCAF3> /usr/lib/dyld

Model: MacBook6,1, BootROM MB61.00CC.B00, 2 processors, Intel Core 2 Duo, 2,26 GHz, 2 GB, SMC 1.51f53
Graphics: NVIDIA GeForce 9400M, NVIDIA GeForce 9400M
Memory Module: BANK 0/DIMM0, 1 GB, DDR3, 1067 MHz, 0x80AD, 0x484D54313132533654465238432D47372020
Memory Module: BANK 1/DIMM0, 1 GB, DDR3, 1067 MHz, 0x80AD, 0x484D54313132533654465238432D47372020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x93), Broadcom BCM43xx 1.0 (5.106.98.102.30)
Bluetooth: Version 6.0.7f10, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: TOSHIBA MK2555GSXF, 250,06 GB
Serial ATA Device: MATSHITADVD-R   UJ-898
USB Device: USB 2.0 Bus
USB Device: Storage Media
USB Device: USB 2.0 Bus
USB Device: Built-in iSight
USB Device: USB Bus
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Razer Naga
USB Device: USB Bus
USB Device: BRCM2070 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus:

**Comment by unknownbrackets** [comment]
The error message says that you don't have SDL2 installed.

The instructions say:

> Step 1: Install SDL2 via Homebrew
>
>  * Open the Terminal app
>  * Paste this into a terminal session: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
>  * Follow the instructions, and wait for installation to finish
>  * Paste this into a Terminal: brew install sdl2 libzip 

-[Unknown]

**Comment by Refanner** [comment]
I did all the steps and i tried many times to unistall and reinstall homebrew and the sdl2. I've the sdl2 in the directory the ppsspp just doesn't found it.

**Comment by unknownbrackets** [comment]
Strange.  Do you see a file at /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib?  You can open a Terminal window and type:

    ls /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib

(then press enter.)

If it just responds with "/usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib", then you have it and you should at least be getting a different error when starting PPSSPP.

If it says "ls: /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib: No such file or directory" then there must be something going wrong with SDL install.  In that case, can you copy & paste or screenshot what happens if you put this into the Terminal window?

    ls /usr/local/opt/sdl2/lib/

-[Unknown]

**Comment by Refanner** [comment]
![Schermata 2019-03-27 alle 08 17 14](https://user-images.githubusercontent.com/48968714/55057310-1ffd6880-5069-11e9-8281-d3910c514c62.png)

It says "No such file or directory" but if i check the homebrew folder the sdl2 is there i don't get it

**Comment by Refanner** [comment]
I just manually copy the sdl2 folder into the directory and now the ppsspp seems to work. Thanks for the tip!!!

**Comment by unknownbrackets** [comment]
Okay, I'm going to close this unless we get another report of this happening.  Not sure if maybe Homebrew changed something.

-[Unknown]

**Comment by yvnAK** [comment]
2022 im still getting this issue. idk if this is still an issue for other ppl cuz i havent found any other forums for this but i went through the steps and ended up with the same results. idk.
