### ISSUE TITLE
Backslash used in recent list causes issues with features depending on forward slash

### ISSUE THREAD

**Issue by LunaMoo** [hrydgard/ppsspp#11946]
Homebrew detection and fake ID generation doesn't work on recent list while it does just fine everywhere else.

 Easy way to reproduce is to install any homebrew from homebrew store which is missing an icon for example "Trigonometry Wars" then making a screenshot and restart ppsspp, the icon will show in game and homebrew lists as well as game info screen, but it will still show an "unknown.png" on recent list due to fake ID generation failure(since it searches for last forward slash to get the folder name), homebrew using PBP will also not be detected as homebrew since it includes a search for a string also with forward slash as separator.

 Note that manually editing recent list and changing "\\" to "/" does fix the effect of the problem, but PPSSPP will restore the windows backslash as separator whenever updating recent entry breaking it again.

**Comment by unknownbrackets** [comment]
I thought we did the whole resolve path thing to normalize the slashes and file casing?  Is there somewhere we're not doing that?

-[Unknown]

**Comment by unknownbrackets** [comment]
Have any of the changes recently to normalize all paths helped here?

-[Unknown]

**Comment by LunaMoo** [comment]
It helped path are now normalized which is great and the issue is fixed.

 However there's another small issue now which possibly could happen only with a homebrew like trygwars or extracted games / bootable folders existing inside GAME folder where fake ID can be generated incorrectly from the "EBOOT" if the path will include it(it does when running it from the GAME tab or from drag and drop of it's EBOOT.PBP. When drag&dropping whole folder or launching from homebrew installer it saves only path to the folder and generates fake ID from it. In the past I recall it always saved eboot.pbp part in this case, but fake ID generation was stripping it to the folder, but not sure now.

 Still, it's a different and a very minor issue, so I'll close this one.
