### ISSUE TITLE
PPSSPP Android - Does Not Delete Files

### ISSUE THREAD

**Issue by Drasikk** [hrydgard/ppsspp#11958]
### What happens?

I Want To delete a game from the emulator itself, and when I delete it nothing happens. Come Back.

### What *should* happen?

I can delete It from a file explorer, but how it takes it.... 

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Samsung Galaxy Note 8 Oreo 8.0.0 Exynos. 

https://youtu.be/i_wqYgyy7LM

**Comment by leopard20** [comment]
Duplicate...
