### ISSUE TITLE
Gran turismo - every frame screen is moving 1 px up and down

### ISSUE THREAD

**Issue by NKSHV** [hrydgard/ppsspp#11969]
### What happens?
Edges are very blurry. If you use slow motion, you can see that every frame screen moves up and down by 1 pixel, and that causes blurriness. It does this with all screen resolutions in both opengl and vulcan. I tried all other settings and problem still persists.
Other games work with no shaking.
video - https://www.youtube.com/watch?v=_pOj1y9LxUc
Recorded at 1x psp scale for clarity. At first I press slow motion key than show without it. Unfortunately, I can't record 60 FPS. On 24 fps video it looks shaky, but on actual screen it looks like still blurred image.
 
### What *should* happen?
Screen should not shake every frame and cause blurry image

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Android 8 (MIUI 10), Xiaomi Redmi Note 6 Pro, latest ppsspp from play market.

**Comment by NKSHV** [comment]
Found a solution - go to INGAME settings, display settings and change video output to external video output. Problem solved

**Comment by NKSHV** [comment]
Closed by accident not sure what this is on github

**Comment by unknownbrackets** [comment]
Is this the game that did that on purpose?

The PSP's LCD was pretty slow to update, so doing something like this could be used to get a motion blur effect and make it seem more like you're "accelerating" I guess.  In theory, fully emulating it would mean a shader or similar to simulate the slow LCD...

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, this is an old one that has come up repeatedly. The game tries to do antialiasing by adjusting the projection matrix by half a pixel every frame, but when scaled up, it becomes a pixel or more and it just looks like bouncing instead.

That solution works, there's also a cheat code in the forums.
