### ISSUE TITLE
Automaticly start game at PPSSPP launch

### ISSUE THREAD

**Issue by Ferbez** [hrydgard/ppsspp#11967]
### What happens?
I'm trying to make certaing game to launch automaticly at PPSSPP launch, but there's no such option. I'm doing so since I want all my games at XPERIA Play games launcher, and currently I'm making separate app with replaced icon, but stuck at launching games at emulator opening. And yeah, by the way - long time ago some of the devs said that support of XPERIA Play sticks will be implemented at some point, but it's kinda difficult due to "messed up API provided by sony since there's no native gamepad support in andoid 2.3". I guess it's kinda obvious that nobody's using their XPlays anymore, so I just want to hear that this thing will not be implemented at all

### What *should* happen?
Is it possible somehow to launch sertain image at emulator launch? I know about desktop shortcuts implemented in android version long ago, but it isn't possible to add such at XPERIA Play games launcher (by reading PPSSPP forums I believe devs know about what device XPERIA Play, so you might understand my willing to add games to its launcher)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
PPSSPP 1.8.0, XPERIA Play, 2.3.4 android and OpenGL renderer

**Comment by unknownbrackets** [comment]
Does Android 2.3 support widgets?  We already allow widgets to start games directly.

-[Unknown]

**Comment by Ferbez** [comment]
I know about widgets and game shortcuts and said that they are implemented and 2.3 can use it, but I want to automaticly launch game simply by pressing PPSSPP icon. I do understand that this is quite unusual request, so there's explanation: XPERIA Play is a phone that is extremely near to PSP Go with it's sliding mechanism, and featuring android 2.3.3 out of the box (that was updated to 2.3.4 and beta 4.0 at some point), and when you open that sliding mechanism this phone automaticly launch specially made launcher which features specially optimised games for this phone. The only known way to add a game's logo to this launcher is to add certain things into androidmanifest.xml, and this launcher doesn't support shortcuts, widgets and all stuff like that. This is how this launcher looks:
![image](https://user-images.githubusercontent.com/30198857/56083264-54806b00-5e44-11e9-8c29-29e0b7edc5ba.png)
The only idea that came to my mind is to make separate copies of PPSSPP with different icons and names for each game (which you can see at that attached screenshot), but I still can't figure out how to automaticly start game when I open that app. Again - I understand how I'm making problems for myself out of the air, but I guess that's kinda more esthetic when all games appears in that launcher. And yeah, English is not my native language so sorry for every mistake that I may made while writing this.

**Comment by unknownbrackets** [comment]
Hm okay.  I'm assuming you're compiling different copies with different app ids, right?

If that's true, you could add something before this line:
https://github.com/hrydgard/ppsspp/blob/aba375e2f7498072962135a141006f1aa956f158/android/jni/app-android.cpp#L432

For example:
```c++
	shortcut_param = "/sdcard/path/to/patapon.cso";
```

Which should make that version launch Patapon automatically.  That's really all a shortcut widget does.

-[Unknown]

**Comment by Ferbez** [comment]
Sorry for not replying for this long. After reading this I felt myself extremely dumb because I could easily figure this out myself. Now that I made those changes and replaced "exit to menu button" with "exit" button in pause menu I finally done what I want. Thank you very much. I guess it should be closed now.

**Comment by unknownbrackets** [comment]
Everyone needs to be pointed in the right direction sometimes.

-[Unknown]

**Comment by aatopanrizky** [comment]
> Sorry for not replying for this long. After reading this I felt myself extremely dumb because I could easily figure this out myself. Now that I made those changes and replaced "exit to menu button" with "exit" button in pause menu I finally done what I want. Thank you very much. I guess it should be closed now.

hey dude do u know how to change the package name ?
