### ISSUE TITLE
"God of War" series game does not work properly on v180-105 or higher

### ISSUE THREAD

**Issue by Halo-Michael** [hrydgard/ppsspp#11976]
### What happens?
On iOS devices, after the PPSSPP is updated from v1.8.0-102 to v1.8.0-105, "God of War" series game does not work properly.(Usually freezes within one second of entering the game, the FPS counter shows that the number of frames drops to zero)

### What *should* happen?
Works fine like on the v102 or other game on v105 or high version(v106).

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
iOS12.1.1 Already jailbroken; PPSSPP v1.8.0-105 or higher(v1.8.0-106)

**Comment by unknownbrackets** [comment]
Should be fixed now, at least in the demo.  See 8d4ab57b46263f838394f06409dc19e0aaf0b018.

-[Unknown]

**Comment by a5585233** [comment]
Apple X11.2.1 Already jailbroken; Ppssppv1.8.0-106 the god of war series is not working properly. (usually stops within a second of entering the game, and the FPS counter shows zero frames)

**Comment by a5585233** [comment]
Apple X ios11.2.1 has been jailbroken; The ares series is not working properly. (usually stops within one second of entering the game, and the FPS counter displays zero frames)

**Comment by Halo-Michael** [comment]
> Apple X ios11.2.1 has been jailbroken; The ares series is not working properly. (usually stops within one second of entering the game, and the FPS counter displays zero frames)

Fixed on v1.8.0-107

**Comment by a5585233** [comment]
My current version is v1.8.0-106. When will your source update v1.8.0-107

**Comment by Halo-Michael** [comment]
Already updated

**Comment by Halo-Michael** [comment]
> My current version is v1.8.0-106. When will your source update v1.8.0-107

Already updated

**Comment by a5585233** [comment]
Version 107 has been updated, God of War is running well, thank you!
