### ISSUE TITLE
Tekken 6: Can't go past autosave warning screen

### ISSUE THREAD

**Issue by leopard20** [hrydgard/ppsspp#11977]
After the latest CPU clock speed changes (since v1.8.0-105, if I'm not mistaken), the game gets stuck at the autosave warning screen. 
Note that the same thing happened in previous versions when you manually set the CPU clock speed (but now it happens even with default settings)
GoW also has the same problem.

Device: Mi 5s Plus, Android 8.0

**Comment by unknownbrackets** [comment]
May be fixed now (8d4ab57b46263f838394f06409dc19e0aaf0b018).  This could imply that the 60 FPS hack is involved in the problem when you change the CPU clock speed.  Maybe the 60 FPS hack values need to be reset on mhz change.

-[Unknown]

**Comment by leopard20** [comment]
Yeah that fixes it.
