### ISSUE TITLE
how to build for mac os?

### ISSUE THREAD

**Issue by yyz1989** [hrydgard/ppsspp#11989]
Hi there,

I would like to build ppsspp for mac os. In wiki there are build instructions for other platforms, but mac os does not seem to be included. Is there any documentation on how to build for mac os?

Thanks you very much for your help.

Best regards,
Yang

**Comment by LunaMoo** [comment]
You'll find build instructions on the [wiki](https://github.com/hrydgard/ppsspp/wiki/Build-instructions) - for MacOSX check "Building for Qt platforms", remembering to follow the Prerequisites as well as downloading the source code together with submodules correctly.

**Comment by yyz1989** [comment]
@LunaMoo I see, thanks a lot for the suggestion!
