### ISSUE TITLE
gradle build running stuck when build apk - android studio

### ISSUE THREAD

**Issue by aatopanrizky** [hrydgard/ppsspp#11986]
i have a problem with android studio after open project ppsspp and i have followed all build instructions but after generate signed apk the gradle build running just loading without end after 1 hours waiting i got nothing the gradle still running 
i have installed ndk,cmake,sdk and my pc is not problem because running i7 with 32gb ram

any help ?
![Screenshot_10](https://user-images.githubusercontent.com/48789204/56468765-f4e51980-645a-11e9-8031-a7bbf93030f4.png)

**Comment by aatopanrizky** [comment]
and how to change the package name properly ? becaues i changed package name in build.gradle that make many error

**Comment by hrydgard** [comment]
Don't change the package name? There's no good reason to.

**Comment by aatopanrizky** [comment]
> Don't change the package name? There are few good reasons to.
> 
> As for it getting stuck on gradle, haven't seen that for a while. Latest Androd Studio?

oh oke i see
im using latest android studio with latest ndk and sdk
maybe because build variant wrong ? which one normaloptmized build variant i need to chooes

**Comment by 846524417** [comment]
Has the landlord solved the problem? Can you tell me how to build the project?

**Comment by unknownbrackets** [comment]
Is this still an issue?

-[Unknown]

**Comment by 846524417** [comment]
This problem has been solved according to the operation, thank you very much!






------------------ 原始邮件 ------------------
发件人: "Unknown W. Brackets"<notifications@github.com>; 
发送时间: 2019年6月24日(星期一) 凌晨1:51
收件人: "hrydgard/ppsspp"<ppsspp@noreply.github.com>; 
抄送: "846524417"<846524417@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [hrydgard/ppsspp] gradle build running stuck when build apk -android studio (#11986)




这仍然是个问题吗？
 
-[未知]
 
—
你收到这封信是因为你评论了。
直接回复这封电子邮件，在GitHub上查看，或使线静音.
