### ISSUE TITLE
AdHoc/Multiplayer issue in Monster Hunter Portable 3rd HD

### ISSUE THREAD

**Issue by Peduls** [hrydgard/ppsspp#11981]
### What happens?
When attempting to play a multiplayer game each player connects just fine and everything works while the players are in the lobby, but upon starting a mission the players appear frozen in animation and slide around the map for a while and then disconnects. I am using Hamachi to emulate a LAN connection and have run the diagnostic test and everything appears to be functioning correctly.

### What *should* happen?
In the past I've been able to play just fine with the same settings on the same Hamachi server without any issues.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Operating System
	Windows 10 Enterprise 2016 LTSB 64-bit
CPU
	Intel Core i7 4790K @ 4.00GHz
	Haswell 22nm Technology
RAM
	16.0GB Dual-Channel DDR3 @ 799MHz (11-11-11-28)
Motherboard
	ASUSTeK COMPUTER INC. Z97-A (SOCKET 1150)
Graphics
	VG248 (1920x1080@144Hz)
	4095MB NVIDIA GeForce GTX 1070 (EVGA)
Storage
	465GB Samsung SSD 850 EVO 500GB (SATA (SSD))
	2794GB TOSHIBA HDWD130 (SATA )
Optical Drives
	ASUS DRW-24B1ST j
Audio
	High Definition Audio Device
PPSSPP Version
	v1.8.0-107-g8d4ab57b4

**Comment by tywald** [comment]
This is usually happens if you have enabled "Timer hack" in the graphics options.

**Comment by Peduls** [comment]
I don't see this setting under graphics. Is this option enabled by default? My friend and I have been playing Monster Hunter Portable 3rd HD together in the same Hamachi group for years and never had this problem before. We even cleared all of our setting back to their defaults and only changed the necessary networking options and it still occurs.

**Comment by tywald** [comment]
Seems it was removed with #11666 . I do know it it caused a very similar issue a couple of years ago :P video proof here: https://youtu.be/Gs1Ic2VVvI4?t=12

Does any older PPSSPP version still work?

**Comment by Peduls** [comment]
I'm currently trying to see if any older versions work, but me and my friend have very different schedules and it isn't easy to find time to test like 100 versions of PPSSPP.

**Comment by Peduls** [comment]
That video is exactly what I am experiencing. Maybe this'll help me narrow down which version it first started happening in.

**Comment by Peduls** [comment]
I've noticed the problem only occurs when a large monster is on screen. I know small monsters are not synced between players so it must be something to do with how PPSSPP handles syncing the large monster's position to all connected players and failing?

**Comment by unknownbrackets** [comment]
Does it help to turn on / turn off the "real time clock sync" setting on both computers?

-[Unknown]

**Comment by Peduls** [comment]
Haven't tried but the issue doesn't happen with the latest stable build, 1.8.0 We just hunted a large monster without any problems.

**Comment by Peduls** [comment]
My friend and I just tested this using the latest dev build "v1.8.0-143-g122f871c7" with the same settings as before except we changed the "Force real clock sync" option. With it off the issue remains but when both computers have it on the issue seems to be fixed.

**Comment by unknownbrackets** [comment]
Is this still an issue on the latest git build with recent networking improvements?

-[Unknown]

**Comment by Peduls** [comment]
My friend and I just tested this using the latest dev build v1.10.3-1436 and the issue seems to be fixed. No longer requires "Force real clock sync" to be turned on.

**Comment by unknownbrackets** [comment]
Thanks for retesting and confirming.

-[Unknown]
