### ISSUE TITLE
force close when open settings

### ISSUE THREAD

**Issue by f1j4r** [hrydgard/ppsspp#11988]
Everything work fine but app force close when open settings on meizu m2 mini. I have tried to clear data and delete ppsspp folder but it still doesn't work.

**Comment by hrydgard** [comment]
can you get adb logs?

**Comment by unknownbrackets** [comment]
In case it helps:
https://github.com/hrydgard/ppsspp/wiki/How-to-get-an-adb-logcat-from-a-PC

-[Unknown]

**Comment by f1j4r** [comment]
I have fix it, the problem is on my ROM. Sorry for my mistake.

**Comment by hrydgard** [comment]
Well a bad ROM or ISO or whatever is not supposed to crash, and it would be good to debug this. Do you still have the bad file?

**Comment by f1j4r** [comment]
I mean not PSP ROM, but android ROM. The problem occurred after I flashing bravia engine on my Android. And PPSSPP work fine after uninstall it.

**Comment by hrydgard** [comment]
Oh, ok. Well then, I think it's fair to close.
