### ISSUE TITLE
 It does not give me option for Vulkan, only OpenGL

### ISSUE THREAD

**Issue by iWeaker4you** [hrydgard/ppsspp#12004]
I downloaded the last build for its compilation 1.8.0 119, but when I started it, it did not give me the Vulkan API option, only OpenGL

I installed correctly with the command:
sudo apt install libvulkan1 table-vulkan-drivers vulkan-utils

but for some reason it does not give me the option, but Vulkan detects me in other emulators and games that I have installed.

My PC:
Ubuntu 19.04
i5 3470
GTX1050 2GB
8Gb DDR3
Nvidia Drivers 430

**Comment by hrydgard** [comment]
Ddi you build the Qt build or the SDL build? The Qt version currently doesn't support Vulkan.

**Comment by iWeaker4you** [comment]
> Ddi you build the Qt build or the SDL build? The Qt version currently doesn't support Vulkan.

Thanks bro.

I did not know that QT did not have support for Vulkan, I just compiled it with SDL and if it worked ...

**Comment by hrydgard** [comment]
Just for the record, this is tracked in https://github.com/hrydgard/ppsspp/issues/11628 .
