### ISSUE TITLE
PPSSPP is crashing when I try to load games from Apache2 server caused by wrong string detection behaviour

### ISSUE THREAD

**Issue by HoshiYamazaki** [hrydgard/ppsspp#12018]
### What happens?
PPSSPP crashes, both on Windows 32 and 64 bit apps, also on Android (I tested it on Oculus GO) too.
This is caused by not detected correctly filename in `index.txt` file - when you use `/dissidia.iso` everything works fine but when you don't add slash at start (`dissidia.iso`) it stops working.

### What *should* happen?
It should connect and display games thumbnail. I assume this is easy string fix in PPSSPP code.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
My server is running under Ubuntu 18.04 and Apache2 (from apt repo).
Also Apache prints these errors:
```
[Sun May 05 16:59:09.411871 2019] [core:notice] [pid 1415:tid 140023030959040] AH00094: Command line: '/usr/sbin/apache2'
[Sun May 05 16:59:19.212035 2019] [authz_core:error] [pid 1417:tid 140022795704064] [client 192.168.1.115:53107] AH01630: client denied by server configuration: /home/hoshi/WWW/
[Sun May 05 16:59:19.912966 2019] [authz_core:error] [pid 1417:tid 140022778918656] [client 192.168.1.115:53107] AH01630: client denied by server configuration: /home/hoshi/WWW/
[Sun May 05 16:59:20.610266 2019] [authz_core:error] [pid 1417:tid 140022812489472] [client 192.168.1.115:53107] AH01630: client denied by server configuration: /home/hoshi/WWW/
[Sun May 05 16:59:21.132612 2019] [authz_core:error] [pid 1417:tid 140022753740544] [client 192.168.1.115:53107] AH01630: client denied by server configuration: /home/hoshi/WWW/
[Sun May 05 16:59:21.733119 2019] [authz_core:error] [pid 1417:tid 140022728562432] [client 192.168.1.115:53107] AH01630: client denied by server configuration: /home/hoshi/WWW/
[Sun May 05 16:59:22.370190 2019] [authz_core:error] [pid 1417:tid 140022711777024] [client 192.168.1.115:53107] AH01630: client denied by server configuration: /home/hoshi/WWW/
[Sun May 05 17:00:29.703316 2019] [mpm_event:notice] [pid 1415:tid 140023030959040] AH00491: caught SIGTERM, shutting down
```

**Comment by hrydgard** [comment]
Crashing for something like this is bad, tagging.

**Comment by Florin9doi** [comment]
The crash happens in Url::Split():
https://github.com/hrydgard/ppsspp/blob/8f4bafea9c50f4595aaa4ade9f7ef55b90983e9a/ext/native/net/url.cpp#L21

It receive something like this: http://127.0.0.1:8000cube.iso
The simple solution would be to check if sep==std::string::npos but this will just avoid the crash.
Why is that slash required on server, instead of being added automatically when the URL is composed on client?

**Comment by hrydgard** [comment]
It should tolerate missing slashes, it's just a bug. I'll get on it shortly.

**Comment by Florin9doi** [comment]
```diff --git a/UI/RemoteISOScreen.cpp b/UI/RemoteISOScreen.cpp
index 9ba9df4f7..ade6720e5 100644
--- a/UI/RemoteISOScreen.cpp
+++ b/UI/RemoteISOScreen.cpp
@@ -210,7 +210,8 @@ static bool LoadGameList(const std::string &host, int port, std::vector<std::str
                }

                char temp[1024] = {};
-               snprintf(temp, sizeof(temp) - 1, "http://%s:%d%s%s", host.c_str(), port, subdir.c_str(), item.c_str());
+               snprintf(temp, sizeof(temp) - 1, "http://%s:%d%s/%s", host.c_str(), port, subdir.c_str(), item.c_str());
                games.push_back(temp);
        }
```

**Comment by hrydgard** [comment]
Both sides of this bug should be fixed now.

**Comment by hrydgard** [comment]
@HoshiYamazaki Please re-test with a new build. I believe this is fixed, so I'm closing.
