### ISSUE TITLE
[Feature Request] More (customizable) touch screen buttons

### ISSUE THREAD

**Issue by Leopard20** [hrydgard/ppsspp#12011]
I think that the current number of touch screen button options are limited and a new set of them should be added. For instance, from our discussion here https://github.com/hrydgard/ppsspp/issues/11562 I would like you to add save state and load state buttons for easier access, because using phone buttons (like Vol up or down) for this purpose is not very optimal as the original phone buttons won't function anymore.

If these touch screen buttons could be mapped to all functions in Control Mapping (for example, 
one of these buttons can simulate pressing the F1 key and in Control Mapping, F1 was used to create savestate) it would be even better! You can create a set of them similar to the combo keys, and call them Option keys or something.

**Comment by Gamemulatorer** [comment]
Hoping @iota97 can implement this in v1.15 :)

**Comment by iota97** [comment]
Isn't this already done in #13869? I think this can be closed :)

**Comment by Gamemulatorer** [comment]
> Isn't this already done in #13869? I think this can be closed :)

Didnt know that :)

**Comment by unknownbrackets** [comment]
Yep, seems indeed well covered by #13869.  Closing.

-[Unknown]
