### ISSUE TITLE
phantasy star portable crash on loading after creating character

### ISSUE THREAD

**Issue by dikorommel** [hrydgard/ppsspp#12015]
screenshot
https://postimg.cc/DWcpv7PZ/436d6708
psspp version:v1.8.0-154-g2d6514feb
device:xiaomi redmi 4A,MIUI 10,Android nougat

**Comment by unknownbrackets** [comment]
If you have a PC, can you check if you get the same issue on Windows (just to help narrow down the cause)?

Have you tried changing the graphics backend?  Has any previous version worked for you?

It might also help to see logs:
https://github.com/hrydgard/ppsspp/wiki/How-to-get-an-adb-logcat-from-a-PC

-[Unknown]

**Comment by dikorommel** [comment]
well
phantasy star portable work perfectly in ppsspp 1.7.5 beside little lag
and didn"t working since 1.8.0 update

**Comment by unknownbrackets** [comment]
It'd help if you could try some git builds and see when it first stopped working.

https://buildbot.orphis.net/ppsspp/index.php?m=fulllist

v1.7.5-571-g1bedb97bc is basically the same as 1.8.0.  If you try one half way between, you can eliminate 265 possible versions one just one try.  If you try about 9 different versions (going by halves) you'll find when the problem started happening.

That can make it a lot easier to fix.

-[Unknown]

**Comment by Gamemulatorer** [comment]
I can't reproduce this issue in the lastest git build of ppsspp
# screenshots
![Screenshot_20200523-070558](https://user-images.githubusercontent.com/37603562/82715161-83624500-9cc4-11ea-8178-46d425287610.png)
![Screenshot_20200523-070814](https://user-images.githubusercontent.com/37603562/82715164-86f5cc00-9cc4-11ea-9f43-1955fd471cb6.png)
![Screenshot_20200523-070836](https://user-images.githubusercontent.com/37603562/82715172-8a895300-9cc4-11ea-9bcb-2e5b1b632129.png)
![Screenshot_20200523-070905](https://user-images.githubusercontent.com/37603562/82715176-8d844380-9cc4-11ea-9583-749b1596dd8d.png)
![Screenshot_20200523-070915](https://user-images.githubusercontent.com/37603562/82715181-91b06100-9cc4-11ea-9047-5f1bdf34883c.png)
![Screenshot_20200523-070905](https://user-images.githubusercontent.com/37603562/82715185-99700580-9cc4-11ea-9bb6-089afe810371.png)
![Screenshot_20200523-070921](https://user-images.githubusercontent.com/37603562/82715190-9d038c80-9cc4-11ea-8146-2bd8439b8c7c.png)
![Screenshot_20200523-070943](https://user-images.githubusercontent.com/37603562/82715197-a0971380-9cc4-11ea-847b-0c646546646d.png)

**Comment by Gamemulatorer** [comment]
@dikorommel any feedback?

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
