### ISSUE TITLE
PPSSPP remote disc feature select only last line from index.txt file

### ISSUE THREAD

**Issue by HoshiYamazaki** [hrydgard/ppsspp#12019]
### What happens?
PPSSPP loads only one game if using remote disc option, which is ISO location in last line of index.txt file.

### What *should* happen?
Load all contents of index.txt at Apache server.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Windows 64bit.

**Comment by unknownbrackets** [comment]
Well, it will probably work fine if you use unix newlines (as PPSSPP does.)  Most likely you have Windows style newlines (\r\n or CRLF) and it's not ignoring the \r or CR.

Fixable but not really a priority.  For example, I think .htaccess (in Apache) is glitchy if you use \r\n as well.

-[Unknown]

**Comment by HoshiYamazaki** [comment]
> Well, it will probably work fine if you use unix newlines (as PPSSPP does.) Most likely you have Windows style newlines (\r\n or CRLF) and it's not ignoring the \r or CR.
> 
> Fixable but not really a priority. For example, I think .htaccess (in Apache) is glitchy if you use \r\n as well.
> 
> -[Unknown]

Yes I used Windows notepad to edit index.txt file via Filezilla on Windows host to my Ubuntu server. So I probably should use nano or other editor instead... Thanks!

**Comment by hrydgard** [comment]
This is unexpected enough behaviour that I'm tagging it.

**Comment by hrydgard** [comment]
Should be fixed now. Can you confirm?

**Comment by hrydgard** [comment]
@HoshiYamazaki Please re-test with a new build. I believe this is fixed, so I'm closing.
