### ISSUE TITLE
Test Drive Unlimited: Ad-Hoc not working.

### ISSUE THREAD

**Issue by christorrella** [hrydgard/ppsspp#12010]
### What doesn't happen?
Ad-hoc play is broken. You can't see other players and they can't see you. Race lobbies are unreachable by anybody playing. There appears to be zero communication occurring between connected systems. 

### What should happen?

Players should be able to:
- see each other on the free-drive minimap
- see each other's cars driving on the island, drive with eachother, etc
- race each other at "Drive-In" locations across the map

### More information

Title: Test Drive Unlimited
Genre: Racing, Open World
Region: US
Format: ISO
Version: v?.?
OS: Android/Mac
Compatibility: Playable/In-game
Notes: Ad-Hoc unplayable

I love PPSSPP! Thanks for all of your work. I'll buy PPSSPP Gold if this can get resolved.

I'm also offering a bounty of $100 USD (PayPal, Venmo, etc.) to whoever can help me get a fix for this game, Test Drive Unlimited, so the multiplayer ad-hoc portion of the game actually works.

Important info:

- The game's official ID is ULUS-10249
- I'm running PPSSPP 1.8.0 on all devices
- I've confirmed that another game's ad-hoc works for me, called Pilot Academy
- To get the game's choppiness bug fixed, there's a cheat code that must be enabled before loading the game to remove a forced post-processing on the graphics. This is included at the end of the post.

So here's the problem: Test Drive Unlimited (TDU) is a game that's meant to be played in multiplayer, but ever since the servers went offline in 2009, it's been a very quiet world to play in. I want to try and revive the game by creating a dedicated ad-hoc server that TDU players can access through PPSSPP.

Everything in-game works and I'm delighted that the post-processing graphics issue finally got a fix, but now the only thing missing is the ad-hoc multiplayer compatibility.

The network initialization process *apparently* goes just fine in the main menu settings screen, for PPSSPP's built-in Pro server, but once you get in-game and have two people at the same spot on the driving map, you can't see the other player. Also, in the "Drive-In" rooms, accessible via the map, you should be able to create a room to play with other people. That also never works. Basically, ad-hoc is completely broken here and needs a fix.

I've included [some screenshots on Imgur](https://imgur.com/a/VAzNywQ) in hopes that you may be able to see what the issue is. If you have any specific questions about this bug, don't be afraid to PM me directly or comment below. 

**Just to re-iterate, I'm promising $100 to the first dev that fixes this to the point where I can set up a public server, where I can have friends join me from another city.** 

Cheers and thanks for your help!

Cheat code necessary for in-game play to work:
`_S ULUS-10249`
`_G Test Drive Unlimited`
`_C0 (Requires restart)`
`_C0 Remove slow and ugly effect`
`_L 0xE0020406 0x002DC218`
`_L 0x202DC218 0x00003021`
`_L 0x202DC21C 0x00000000`

**Comment by LunaMoo** [comment]
I checked and at least when driving around the world it works fine.
![ULUS10249_00002](https://user-images.githubusercontent.com/5485237/57164243-cd476700-6df3-11e9-8c9d-93ac35cc0cf9.jpg)
That's using my custom build which allows adhoc between multiply instances on same pc, online might not work due to latency, firewalls, closed ports etc. which are not a problem playing through LAN or on same pc.

You should probably read some adhoc guides as if you expected playing online an adhoc game mode without problems, then that's exactly your issue.

**Comment by christorrella** [comment]
I've set up the Ad-Hoc system and it's been successful with at least one game. I also tried port-shifting and that also hasn't done me any good. Can you give any advice, or a link to a good, up-to-date tutorial to follow? It would be much appreciated.

**Comment by christorrella** [comment]
I should also mention that I'm using a Mac and an Android phone to connect to each other. I've tried using a router as a middle-man, and also using the phone's hotspot feature. Guess I should look at the firewall info. Thanks again!

**Comment by christorrella** [comment]
Okay, I think I've found something: The game is trying to communicate over port 8883 which is reserved for SSL. How do I go about port forwarding this? Researching more.

**Comment by christorrella** [comment]
I just worked on this for about 10 hours today, to no avail. Here's what I found, though. 

This game runs on three ports: TCP 27312 for the adhoc server itself, and two UDP connections on 8122 and 8883. One other game that I knew works, Pilot Academy, communicates on ports TCP 27312 (for adhoc server) and UDP 3658. WipEout Pure also runs on 3658, and both of these games run multiplayer like a charm, just fine no problem. 

So I thought, in theory, if I port-shift WipEout and Pilot Academy by 4464, I can get them to try and communicate on UDP 8122 (because the original port, 3658, plus 4464 = 8122.) I checked using `nettop` on linux to make sure it was communicating on this new port that we think may be problematic, and sure enough, multiplayer worked like a charm.

I also tried port shifting those two games to make them communicate on TDU's other port, UDP 8883. I thought that maybe because it's reserved for SSL it may be a problem with firewalls, etc. Nope. Both Pilot Academy and Wipeout communicated just fine over TCP 27312 and UDP 8883.

I confirmed that each port was correct using `nettop`, I tried multiple computers, different routers, made sure it worked for the two games first and then tried TDU... Nothing. Nothing at all.

What am I missing here??

**Comment by LunaMoo** [comment]
I can't test official version since I have just one pc nowadays and not into wasting ssd space for virtual machine just to be able to test ppsspp adhoc, so I'm using my personal branch ~ https://github.com/LunaMoo/ppsspp/tree/TemporaryHackishBranch which does include adhoc between multiply instances on same device, it does have compatibility improvements, but game specific which are activated only for selected games and TDU is not one of them. It's always possible some other changes from my branch are affecting it this game's compatibility, but probably bigger difference is the fact you're using a mac and android getting more points of failure compared to windows, don't really use mac nor android so can't tell what could go wrong there.

 Settings wise that could matter I only use simulate UMD delay for IO and disable fast memory which is generally recommended to run buggy stuff like adhoc or even homebrew as it will avoid some crashes that would otherwise happen on real hardware. Network settings are basic, just need different mac, server running on one of the clients and both clients using the same server address pointing to that device. Don't use Coldbird's or any other online server for testing as that will just add a lot of stuff that can go wrong, but when using two different devices, one thing worth trying is to swap which one runs server as the one which has trouble connecting, might still be fine for other devices to connect to.

**Comment by christorrella** [comment]
I tried the settings you suggested, setting Simulate UMD Delay and disabling Fast Memory didn't do the trick for me. Would you mind sharing your ppsspp.ini file?

**Comment by christorrella** [comment]
Trying to compile your "hackish" branch brings many errors, most notably a PPSSPPDL.app on Mac that doesn't have any executable inside. Must bea problem on my end.

**Comment by LunaMoo** [comment]
Outside of the two I mentioned I keep all relevant settings on default.

 Adhoc is pretty much an unfinished WIP that was included with all it's mess by popular demand and is typically broken by not implemented or incorrectly implemented functions, however it's even more commonly simply blocked via some system specific weirdness.
 Many games for example expect really low or non-existent latency for adhoc multiplayer, time between different clients usually also has to match, port offset if used has to be exactly same on all clients etc. unthrottle or fps cheats can also cause problems as it's very asy to desync adhoc multiplayer and many games can't handle that there's probably a lot more things which can go wrong, but I'm not really into networking so can't tell. Only thing I can tell for sure is that running multiply clients on a single windows based system is pretty much a best case scenario and usually if that works, the problem lies within connection.

 For connection problems tunneling through a single port(#7268) could make things easier, but at the cost of killing PSP compatibility and potentially affecting in a bad way some more sensitive games.

 As for my branch I have no mac I also don't have a buildbot checking mac builds with each changes, so it's possible I broke mac build at some point;p, but most common problem people have building PPSSPP is to init and update submodules. If you simply grab the source code via download from github it will in fact not come with any submodule and PPSSPP has quite a few of them;3. You'll find build instructions [here](https://github.com/hrydgard/ppsspp/wiki/Build-instructions), mac specific stuff is under Qt platforms.

**Comment by christorrella** [comment]
Ugh, still not working. Can you confirm the ID of the game (i.e. ULES vs ULUS)? I can't for the life of me figure out how to get even the official PPSSPP branch compiled, I always get an empty .app for my Mac.

**Comment by HiImBrala** [comment]
> Ugh, still not working. Can you confirm the ID of the game (i.e. ULES vs ULUS)? I can't for the life of me figure out how to get even the official PPSSPP branch compiled, I always get an empty .app for my Mac.

what port offset did u set i want to play with some1 but when i try connecting error comes out

**Comment by adenovan** [comment]
need someone to post log here with scekernel , sceutility and scenetadhoc checked , debug log should be good as im writing much test code to inspect psp adhoc right nowm

**Comment by MojoJojoDojo** [comment]
If i am not mistaken this works now on the latest PPSSPP build or AdamN test builds from his PR.
Last time I tried it worked anyway.

**Comment by christorrella** [comment]
> If i am not mistaken this works now on the latest PPSSPP build or AdamN test builds from his PR.
> Last time I tried it worked anyway.
> You can try to see if it works over multiple instances now.

Hey MojoJojoDojo, thank you and adenovan for continuing to look after this post! 

I will try to run this now between a PC and a Mac. I'll let you know what I find.

**Comment by ANR2ME** [comment]
@christorrella is this game have a working multiplayer on the latest version?

**Comment by christorrella** [comment]
@LunaMoo I was *finally* able to get my own install of your TemporaryHackishBranch working so I could try multiple instances and do a localhost server. [I uploaded a video here](https://youtu.be/S4QsY_nMAmk) to show you exactly what I'm doing, and I still can't get anything to work. How can I help fix this? 

@ANR2ME No, I have tried using the official build (1.11.3) and even after following the instruction to "use localhost for multiple instances", I still can't get this to work. I'm using different MAC addresses for each, thought that might be the issue.

 @MojoJojoDojo Despite the "use localhost for multiple instances" instructions that appear in the official 1.11.3 build, I still can't get this to work across 2 instances. Would you mind showing me how you are able to get this working? This is driving me up the wall LOL

@adenovan I'm using MacOS, how can I get these logs for you? I would love to help.

Thank you everybody for helping me with this!

**Comment by ANR2ME** [comment]
Based on your video the 2nd instance didn't shows "Network initialized" message, so it probably falling back to faked success.
May be the port is blocked/restricted, since your port offset is 0, if the game is using port under 1024 you'll need `sudo`.
Try changing port offset to above 1024 (ie. 1500 or 10000)

PS: I'm not sure whether both instance will have a different loopback address or not on MacOS (never tested this), if both instance happened to have the same IP it will also cause issue.

**Comment by christorrella** [comment]
@ANR2ME I will try with a port offset of 1500. 

Also, I think that @LunaMoo intended for their hackishbranch to be able to let you bind PPSSPP instances to a different network interface, i.e. 127.0.0.2, but I don't see that as an option in 1.11.3, maybe it was broken with a merge?

**Comment by christorrella** [comment]
Maybe insignificant, but when I start AdHoc in the game, this is what the logs say:
`28:44:998 user_main    I[SCEKERNEL]: HLE/sceKernelThread.cpp:2007 455=sceKernelCreateThread(user_InetReceive, 08921a2c, 0000006a, 61440, 00000000, 00000000)
28:44:998 user_main    I[SCEKERNEL]: HLE/sceKernelThread.cpp:2102 0=sceKernelStartThread(455, 0, 00000000)
28:44:998 user_main    I[SCEKERNEL]: HLE/sceKernelThread.cpp:2007 456=sceKernelCreateThread(user_InetSend, 089216f8, 0000006a, 16384, 00000000, 00000000)
28:44:998 user_main    I[SCEKERNEL]: HLE/sceKernelThread.cpp:2102 0=sceKernelStartThread(456, 0, 00000000)
28:44:998 user_main    W[SCENET]: HLE/sceNet.cpp:648 sceNetInit(poolsize=131072, calloutpri=40, calloutstack=16384, netintrpri=40, netintrstack=16384) at 0892852c
28:44:998 user_main    I[SCENET]: HLE/sceNetAdhoc.cpp:1144 0=sceNetAdhocInit(): at 08928544
28:44:998 user_main    I[SCENET]: HLE/sceNetAdhoc.cpp:1151 sceNetAdhocctlInit(32768, 48, 08ca69c0) at 08928564
28:44:998 user_main    I[SCEKERNEL]: HLE/sceKernelThread.cpp:2007 457=sceNetAdhocctlInit(32768, 48, 08ca69c0)
28:44:998 idle0        I[SCENET]: HLE/proAdhoc.cpp:1321 FriendFinder: Begin of Friend Finder Thread
28:45:004 idle0        I[SCENET]: HLE/proAdhocServer.cpp:545 AdhocServer: New Connection from 127.0.0.1
28:45:009 idle0        I[SCENET]: HLE/proAdhoc.cpp:1353 FriendFinder: Network [RE]Initialized
28:45:016 idle0        I[SCENET]: HLE/proAdhocServer.cpp:639 AdhocServer: PPSSPP (MAC: 70:ce:29:da:30:0a - IP: 127.0.0.1) started playing ULES00637
28:45:030 user_main    W[SCENET]: HLE/sceNetAdhoc.cpp:2279 UNTESTED sceNetAdhocctlAddHandler(892872c, 0): added handler 0
28:45:030 user_main    I[SCENET]: HLE/sceNetAdhoc.cpp:2712 sceNetAdhocctlConnect(VetStudi) at 089283f8
28:45:040 idle0        I[SCENET]: HLE/proAdhocServer.cpp:902 AdhocServer: PPSSPP (MAC: 70:ce:29:da:30:0a - IP: 127.0.0.1) joined ULES00637 group VetStudi
28:45:041 idle0        I[SCENET]: HLE/proAdhoc.cpp:1415 Received 7 Bytes of Data from Adhoc Server
28:45:041 idle0        I[SCENET]: HLE/proAdhoc.cpp:1434 FriendFinder: Incoming OPCODE_CONNECT_BSSID [70:ce:29:da:30:0a]
28:47:133 user_main    I[SCENET]: HLE/sceNetAdhoc.cpp:1223 sceNetAdhocPdpCreate(70:ce:29:da:30:0a, 8122, 2000, 0) at 08842b7c
28:47:134 user_main    I[SCENET]: HLE/sceNetAdhoc.cpp:1223 sceNetAdhocPdpCreate(70:ce:29:da:30:0a, 8883, 2000, 0) at 08842b7c
`

I'm not sure why it's saying I'm playing ULES00637, that's the PAL version of this game, I'm using NTSC. Would that have any effect on AdHoc play?

**Comment by christorrella** [comment]
@ANR2ME I tried using two different machines, each with port offset 1500, pointing to one instance's IP, they both connect to the AdHoc server but there is no communication beyond that.

Here is what the log of the host PPSSPP says when starting the AdHoc server:
`45:00:602 user_main    I[SCEKERNEL]: HLE/sceKernelThread.cpp:2007 398=sceKernelCreateThread(user_InetReceive, 08921a2c, 0000006a, 61440, 00000000, 00000000)
45:00:602 user_main    I[SCEKERNEL]: HLE/sceKernelThread.cpp:2102 0=sceKernelStartThread(398, 0, 00000000)
45:00:602 user_main    I[SCEKERNEL]: HLE/sceKernelThread.cpp:2007 399=sceKernelCreateThread(user_InetSend, 089216f8, 0000006a, 16384, 00000000, 00000000)
45:00:602 user_main    I[SCEKERNEL]: HLE/sceKernelThread.cpp:2102 0=sceKernelStartThread(399, 0, 00000000)
45:00:602 user_main    W[SCENET]: HLE/sceNet.cpp:648 sceNetInit(poolsize=131072, calloutpri=40, calloutstack=16384, netintrpri=40, netintrstack=16384) at 0892852c
45:00:602 user_main    I[SCENET]: HLE/sceNetAdhoc.cpp:1144 0=sceNetAdhocInit(): at 08928544
45:00:602 user_main    I[SCENET]: HLE/sceNetAdhoc.cpp:1151 sceNetAdhocctlInit(32768, 48, 08ca69c0) at 08928564
45:00:602 user_main    I[SCEKERNEL]: HLE/sceKernelThread.cpp:2007 400=sceNetAdhocctlInit(32768, 48, 08ca69c0)
45:00:602 idle0        I[SCENET]: HLE/proAdhoc.cpp:1321 FriendFinder: Begin of Friend Finder Thread
45:00:612 idle0        I[SCENET]: HLE/proAdhocServer.cpp:545 AdhocServer: New Connection from 127.0.0.1
45:00:614 idle0        I[SCENET]: HLE/proAdhoc.cpp:1353 FriendFinder: Network [RE]Initialized
45:00:622 idle0        I[SCENET]: HLE/proAdhocServer.cpp:639 AdhocServer: PPSSPP (MAC: 70:ce:29:da:30:0a - IP: 127.0.0.1) started playing ULES00637
45:00:635 user_main    W[SCENET]: HLE/sceNetAdhoc.cpp:2279 UNTESTED sceNetAdhocctlAddHandler(892872c, 0): added handler 0
45:00:635 user_main    I[SCENET]: HLE/sceNetAdhoc.cpp:2712 sceNetAdhocctlConnect(VetStudi) at 089283f8
45:00:643 idle0        I[SCENET]: HLE/proAdhocServer.cpp:902 AdhocServer: PPSSPP (MAC: 70:ce:29:da:30:0a - IP: 127.0.0.1) joined ULES00637 group VetStudi
45:00:651 idle0        I[SCENET]: HLE/proAdhoc.cpp:1415 Received 7 Bytes of Data from Adhoc Server
45:00:651 idle0        I[SCENET]: HLE/proAdhoc.cpp:1434 FriendFinder: Incoming OPCODE_CONNECT_BSSID [70:ce:29:da:30:0a]
45:02:734 user_main    I[SCENET]: HLE/sceNetAdhoc.cpp:1223 sceNetAdhocPdpCreate(70:ce:29:da:30:0a, 8122, 2000, 0) at 08842b7c
45:02:734 user_main    I[SCENET]: HLE/sceNetAdhoc.cpp:1223 sceNetAdhocPdpCreate(70:ce:29:da:30:0a, 8883, 2000, 0) at 08842b7c
`

Here is what host PPSSPP says when secondary system connects:
`47:26:049 user_main    I[SCENET]: HLE/proAdhocServer.cpp:545 AdhocServer: New Connection from 192.168.86.119
47:26:049 user_main    I[SCENET]: HLE/proAdhocServer.cpp:639 AdhocServer: PPSSPP 2 (MAC: 30:23:e6:45:e2:c9 - IP: 192.168.86.119) started playing ULES00637
47:26:073 user_main    I[SCENET]: HLE/proAdhocServer.cpp:902 AdhocServer: PPSSPP 2 (MAC: 30:23:e6:45:e2:c9 - IP: 192.168.86.119) joined ULES00637 group VetStudi
47:26:083 user_main    I[SCENET]: HLE/proAdhoc.cpp:1415 Received 139 Bytes of Data from Adhoc Server
47:26:083 user_main    I[SCENET]: HLE/proAdhoc.cpp:1525 FriendFinder: Incoming OPCODE_CONNECT [30:23:e6:45:e2:c9][192.168.86.119][PPSSPP 2]
`

**Comment by ANR2ME** [comment]
Ah you can't use localhost when playing on LAN, one of them is 127.x.x.x and the other is 192,x,x,x they won't be able to talk each other.
You need to choose the IP 192.168.x.x on both PPSSPP when playing on LAN, localhost is only used for multiple-instance.

Btw, did the MacOS build have the Toggle List working on AdhocServer IP address settings? Did is shows IP 192.168.x.x in the list?

**Comment by christorrella** [comment]
> Ah you can't use `localhost` when playing on LAN, one of them is 127.x.x.x and the other is 192.x.x.x they won't be able to talk to each other.

Oh! I thought that 127.0.0.1 and localhost were the exact same thing. You learn something new every day!

> You need to choose the IP 192.168.x.x/172.x.x.x/10.x.x.x on both PPSSPP when playing on LAN, `localhost` is only used for multiple-instance.

So if I do 127.0.0.1 for the server, and 192.168.86.XXX (the LAN IP of the host) for the secondary, this should work?

> You can refer to this guide https://github.com/hrydgard/ppsspp/wiki/How-to-play-multiplayer-games-with-PPSSPP

I will look at this. Has it been updated recently? 

> Btw, did the MacOS build have the Toggle List working on AdhocServer IP address settings? Did is shows IP 192.168.x.x in the list?
> Something like this

Yes, that always shows the local IP address of the computer I'm running PPSSPP on.

> And regarding the game title code shown on AdhocServer log, it's because the server is converting any region code into a single region in order to allow cross-region multiplayer.

This makes sense, thank you.

I will try doing the IP address change and see what I can find. Do both fields need to say the exact same thing (i.e. host says host IP address, 192.168.86.244, and secondary uses the same IP address, 192.168.86.244)?

**Comment by christorrella** [comment]
I think you can close this one... Thank you SO much, @ANR2ME. I swear I tried all of these combinations before and it wasn't working. Thanks again.

**Comment by ANR2ME** [comment]
> 
> So if I do 127.0.0.1 for the server, and 192.168.86.XXX (the LAN IP of the host) for the secondary, this should work?
> 
No, it won't work, all players will need to use 192.x.x.xincluding the host, otherwise Adhoc Server will be sending IP 127.x.x.x to all players for the host IP and everyone ended trying to talk to them self.

**Comment by christorrella** [comment]
It works now! I thought 127.0.0.1 was supposed to always be used on the host.

**Comment by ANR2ME** [comment]
Okay, i'll close this now.
