### ISSUE TITLE
PPSSPP v1.8.0-180-g5fe02a4ea unable to initialize rendering engine

### ISSUE THREAD

**Issue by Emulatorer** [hrydgard/ppsspp#12023]
### SCREENSHOTS
![Screenshot_2019-05-08-08-32-02](https://user-images.githubusercontent.com/37603562/57341473-22290b80-716d-11e9-853a-58cae524ff06.png)

### What happens?

I can't play any games in the latest ppsspp buildbot
### What *should* happen?
I can play without problem in ppsspp v1.8.0-155

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Android 5.1 Lollipop
Mali-450 MP GPU
Octacore CPU

**Comment by Emulatorer** [comment]
@hrydgard issue started in v1.8.0-178-gb22b54b63

**Comment by hrydgard** [comment]
That implicates https://github.com/hrydgard/ppsspp/pull/12013.  I guess some ifdef went slightly wrong...

**Comment by vsub** [comment]
Same here and yes,it happens since https://github.com/hrydgard/ppsspp/pull/12013
Android 5.1 Lollipop
Mali-400 MP GPU
