### ISSUE TITLE
FFIV Complete Collection minor text issue

### ISSUE THREAD

**Issue by Alucard-XII** [hrydgard/ppsspp#12020]
Win10
i7
Radeon RX Vega M
16GB Ram

RetroArch 1.7.6 - PPSSPP 6f2a6e2

Letters are missing from the edge of the text window. It's a minor issue, but it's getting annoying, especially when I buy stuff from the shops. Examples:

The last digits of the timer and GP are missing:

![b-ff4u-190506-165633](https://user-images.githubusercontent.com/50328733/57228622-4548a380-7025-11e9-855a-9fa580e9f458.png)

The last character's name is missing during battles:

![b-ff4u-190506-165736](https://user-images.githubusercontent.com/50328733/57228977-1b43b100-7026-11e9-8eb0-d7db51cf8a74.png)

Missing letters in conversations:

![b-ff4u-190506-170352](https://user-images.githubusercontent.com/50328733/57229050-4201e780-7026-11e9-8235-bf3ee26b1aef.png)

![b-ff4u-190506-171913](https://user-images.githubusercontent.com/50328733/57229052-429a7e00-7026-11e9-9560-887d4c5096bd.png)

![b-ff4u-190506-171937](https://user-images.githubusercontent.com/50328733/57229053-429a7e00-7026-11e9-939c-4ce8ddf12b9a.png)

I tried, changing all available core settings, and using a different iso. None fixed the issue.

Thanks in advance.

**Comment by hrydgard** [comment]
Might be related to https://github.com/hrydgard/ppsspp/issues/11850 ?

**Comment by Alucard-XII** [comment]
Thanks for the quick response. Any idea if downloading ppsspp again using the built-in core download will get me the new version? Or do I have to delete it and download it manually?

I'm asking because I'm a noob and the easiest way for me is to uninstall RA and re-download the cores.

**Comment by hrydgard** [comment]
@Alucard-XII  May I ask, what backend were you seeing the bug with?

**Comment by Alucard-XII** [comment]
Yes, I was using the gl video driver option in retroarch 1.7.6.
