### ISSUE TITLE
Problems holding down multiple buttons

### ISSUE THREAD

**Issue by ozill131** [hrydgard/ppsspp#12025]
Why can't I hold up to three buttons while using the psspp gold app

**Comment by ozill131** [comment]
My device is tecno KB7 spark 3

**Comment by hrydgard** [comment]
Android normally supports 10 touches but some devices support less. But generally, this issue happens because you enable some special gestures on the device or similar. Are you using some special swipe shortcuts or something like that? Can they be turned off?

**Comment by ozill131** [comment]
thanks I look at that and check
But the problem is that to play this game normally until I upgraded the
system online

**Comment by Emulatorer** [comment]
@ozill131 Try to create combo keys you can combine any button you want for e.g key #1 is equal to X+O+⬜ so you don't need to press the 3 buttons at the same time that's useful for android phone that only have 2points multi touch

Hope you understand me 👍

**Comment by leopard20** [comment]
@ozill131 If your device has some gesture shortcuts that use 3 buttons, try disabling them. 
On Xiaomi devices, same issue happens with the 3-finger-swipe-down screenshot gesture.

**Comment by ResurrectionRedmi9** [comment]
This still an issue?

**Comment by hrydgard** [comment]
@ResurrectionRedmi9 Please stop posting in all old issues like this.

**Comment by unknownbrackets** [comment]
As mentioned this is probably related to three finger gestures.  It was never confirmed, though.

I do think latest Android tries to convince you to enable this by default on all systems now, I wonder if there's some way for us to workaround.

-[Unknown]

**Comment by Gamemulatorer** [comment]
This should be safe to close now assuming that this is an android gesture bug.?
