### ISSUE TITLE
UWP Build Needs a new certificate to compile

### ISSUE THREAD

**Issue by dominater01** [hrydgard/ppsspp#12021]
the xbox one version aka uwp version wont compile because the certificate file has expired

can someone fix this?

**Comment by LunaMoo** [comment]
You can do it yourself ~ https://github.com/hrydgard/ppsspp/pull/10947#issuecomment-383276080
Feel free to open a pull request with new test certificate.

**Comment by dominater01** [comment]
fixed :)

also thanks lunamoo that helped :)
