### ISSUE TITLE
Valkyrie Profile Lenneth (JP ver): Black screen on cutscene

### ISSUE THREAD

**Issue by rkguy** [hrydgard/ppsspp#12045]
When reaching the second cutscene (where princess turns into monster, https://www.youtube.com/watch?v=GXghsV7t9KM @ 51:05)  I only get a black screen, but it does play the audio.
I tried messing with the backends, but nothing changes. 
The game returns to its normal screen when the cutscene finishes.
The game however strangely does indeed play the first cutscene.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Windows, ver 1.8.0 and ver 1.6.3

**Comment by hrydgard** [comment]
Does it matter which graphics backend you are using? Vulkan, OpenGL, D3D9, D3D11?

**Comment by rkguy** [comment]
Yeah, regardless of backend it still would not load.

**Comment by unknownbrackets** [comment]
What's the last version the video played correctly, or did it never?

-[Unknown]

**Comment by rkguy** [comment]
The earliest version I tested was 1.1.1, so I'm guessing it never worked. I also tested on 1.6.x, but that did not work as well.

**Comment by unknownbrackets** [comment]
This check is now not matching: `yOffset < dstYOffset && (int)yOffset <= (int)vfb->height - dstHeight`.  Therefore we assume that we've misdetected a block transfer and skip it.

-[Unknown]

**Comment by unknownbrackets** [comment]
From what I can see, this was broken by 0ee0583.

-[Unknown]
