### ISSUE TITLE
Just only trying something sorry! NOT A ISSUE

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#12047]
1. 

- [ ] 

> ### **_`[](url)`_**

[ ]

**Comment by LunaMoo** [comment]
When you're typing on github you can click preview right above the text box where you type to see how the formatting ends up, also you can just use https://jbt.github.io/markdown-editor/ to do the same, no point creating an issue and editing it for that.

**Comment by marosis** [comment]
Ahhaa. I didn't know that i have just want to learn how to do CHECK button as you can see. But thank you.
