### ISSUE TITLE
Stuttering issue when the emulator loads custom textures

### ISSUE THREAD

**Issue by Ice-w1nd** [hrydgard/ppsspp#12043]
I've been working on texture replacement for a few years now in a couple of projects (for MHFU and MHP3rd) and there's an issue that's always been bothering me: a kind of stutter that happens when the game has to suddenly load either a large (in file-size) texture or several smaller ones at the same time. The best way to see it is when a monster suddenly enters the area where your character is, since the game has to instantly load its custom textures (which in my case are quite large), the game will just freeze for a moment until the textures are loaded. 

It doesn't matter the backend you use (OpenGL, etc), the rendering resolution, whether you are using special shaders or not, texture filtering, anisotropic filtering, etc; and I've also tried several combinations of all those different special options like "lazy texture caching", "retain changed textures" or "Fast memory". None made any difference. I tried on both Windows 7 and 10, and again: same results. I'm using the "xxh64" hash type on the textures.ini file by the way.

Now, all this time I thought it was a matter of storage speed, since the game has to load those textures from your storage device, and I was using an HDD. So I decided to buy a SATA SSD to see if it would make a difference. That was several months ago. And indeed, it made a substantial difference: now I was seeing less stuttering overall when the game had to load custom textures, some of the instances where I was seeing stuttering before where completely solved and in others the game would still stutter but for a smaller period of time.

However, that was not enough, since I was still experiencing plenty of stuttering which made playing the game still kinda frustrating. Now, at that time I was using a pretty old PC (with components from 2009-2010), so I also thought that some of those old components were causing some sort of bottleneck which in part caused the stutter. So I had to wait to try it out on a newer PC to be sure.

Which brings us to this week, when I finally was able to buy a new PC. This is my current setup, which is gonna be relevant to prove a point: Ryzen 5 2600X, GTX 1660ti, 16gb DDR4 3200 MHz.
All brand new components which, even though they aren't super high end, are still tons of times better than what I had before. But I was in for a surprise, since the stutter was still there; the exact same amount, to be precise. So now I'm convinced that none of those components where actually the problem, that wasn't the bottleneck, and I'm pretty sure that even if someone tries it out on an RTX 2080ti and an i9-9900K they would get the same results.

Plan B then, let's go back to storage speed. "Maybe the speed you get with a SATA SSD is still not enough, maybe that's still the bottleneck". Well, that's at least what I thought; so I bought a fast NVME M2 SSD. But surprise surprise: It made literally CERO difference. The same amount of stutter on the same places as before. The sole reason that I bought it in the first place was because I was convinced it would solve that issue or at least make a difference. Oh well...

But wait! I thought. There's still something else I can try! A RAM Disk! So I very excitedly set it up, put all the emulator files and textures in there aaand....
It made no difference, at all. Again. 

So at this point I really don't know what to think. But at least I'm certain of one more thing: storage speed doesn't seem to be a bottleneck either. Maybe only a bit (when you go from an HDD to a SATA SSD), but the fact that even using a RAM Disk didn't make a difference makes it pretty clear to me that the problem comes from somewhere else.

Now, I still have to ask (with my cero knowledge about how this actually works): could it be that there is some sort of hard-coded limit on the total texture file-size that the emulator can manage at the same time, and when it is surpassed (when the emulator has to load more than that at the same time) it just lags? Because again, since both the storage and cpu/gpu/ram speed don't seem to be the bottleneck, it has to be something in the software, right?

Getting better hardware or faster storage won't solve the issue, so it's up to the developers of the emulator to see what causes the problem and how it could be potentially fixed. 

I hope my "research" can serve for something and if someone in the dev team has any idea of what could be causing the issue I would gladly help in any way I can, since it's in my absolute best interest that the issue could be fixed, taking into account that I plan on eventually releasing complete custom texture packs for those games.

Here is a video I recorded where you can see (and hear as well) that when the emulator has to load Zinogre's custom textures, it stutters (at around 0:06). That's an example of the issue.
https://youtu.be/bHkQ8-Oi25Q

**Comment by LunaMoo** [comment]
PNG's aren't textures, they have to be converted and uploaded before used that's not free and high res makes it pretty bad.
Either way we still keep open original request with a list of potential improvements in #4630 so I'll close this as a duplicate. For now best if you reduce size of your replacement images or/and reduce how many of them you're using. Frameskip on auto will also help avoiding the stutter at cost of a dropped frame or two.
