### ISSUE TITLE
Flatout Head On. Instantly freeze emulator when go menu\multiplayer\WLAN

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#12046]

**Comment by marosis** [comment]
Maybe would be good create library eith games what are freeze by going to WLAN

**Comment by hrydgard** [comment]
Linking to #12048.

**Comment by unknownbrackets** [comment]
Is this still an issue on the latest git build with recent networking improvements?

-[Unknown]

**Comment by ppmeis** [comment]
Tested in latest Windows Build. No issues:
![image](https://user-images.githubusercontent.com/4381277/104255168-bf772f80-5478-11eb-93ce-8a92340645ea.png)
