### ISSUE TITLE
Motorstorm Arctic edge menu problem

### ISSUE THREAD

**Issue by Radical05** [hrydgard/ppsspp#12056]
A few days ago I picked up ppsspp looking forward to play all of my old nostalgic games to-go, yet Motorstorm, my favorite, has a huge problem, it freezes on the loading screen (right after the cutscene) which it makes it impossible to play. So I was wondering if you could please fix this issue it would mean a lot to me and every other Arctic Edge fan with the same problem, thank you for reading

                                Warm regards, Radical05

**Comment by unknownbrackets** [comment]
Are you using the latest version?  Have you tried the latest git build?

This sounds like #11019 which was fixed in v1.8.0.

-[Unknown]

**Comment by unknownbrackets** [comment]
Closing this based on #12072 - this issue is already fixed in the latest versions, but unfortunately the state of iOS for PPSSPP isn't so good and the latest versions aren't available yet.  That's being tracked under #11905.

-[Unknown]
