### ISSUE TITLE
A better FXAA shader for CJK Fonts Rendering.

### ISSUE THREAD

**Issue by peaceshi** [hrydgard/ppsspp#12061]
the default fxaa is not perfect for complex fonts such as CKJ fonts.
so I try the NVIDIAGameWorks Sample.
https://github.com/NVIDIAGameWorks/GraphicsSamples/blob/80e8ba8f5e8935821513207033490735dd3279d8/samples/es3-kepler/FXAA/assets/shaders/FXAA_Extreme_Quality.frag

here is my profile.
https://github.com/peaceshi/ppsspp-shaders

this is only for PC. Phone or other devices may be hard to run it because of its hardware.

And really really really really really need official SMAA support!
it is perfect with this FXAA.

**Comment by hrydgard** [comment]
Thanks, will take a look at these soon.

**Comment by peaceshi** [comment]
> Thanks, will take a look at these soon.

really really really really need official **SMAA** support!!!!

**Comment by hrydgard** [comment]
I meant I'll take a look at your FXAA shader.

Why SMAA specifically? That's just an old somewhat more advanced FXAA-ish technique.

**Comment by peaceshi** [comment]
> I meant I'll take a look at your FXAA shader.
> 
> Why SMAA specifically? That's just an old somewhat more advanced FXAA-ish technique.

use fxaa with smaa is better for some games. such as SMAA is just like what you said.

maybe what really need is another AntiaAliasining with fxaa.

**Comment by LunaMoo** [comment]
If you are in need of a higher quality AA only useful for powerful desktop, we kind of have other options which you can also try that might end up looking better(althrough nothing is universally better and having options is always good).
 Most complex AA shader we currently have included in PPSSPP is the video smothingAA which invents new pixels and can work pretty well even on 2D graphics depending on it's settings(it's results can be similar to upscaling shaders), by default it's a subtle AA in-game and heavy smoothing for videos.
 We also have SSAA which can be manually set above x2 it defaults to and at x4 will already give better results than any other AA for 3D graphics at least. Fonts are best just replaced using texture replacement as most PSP games outside of some visual novels have extremely low res fonts and nothing can make them look good.

**Comment by leopard20** [comment]
What about CMAA? I use it on a few PC games and it works really well. Performance penalty is the same as FXAA but the final result is very close to SMAA. Not sure how it works and whether it can be implemented but might be worth taking a look at.
