### ISSUE TITLE
"Test analogs" screen ignores input value below 0.75 confusing the users

### ISSUE THREAD

**Issue by royqh1979** [hrydgard/ppsspp#12062]
### What happens?
In games and "Test analogs", the analog stick buttons  won't generate any input with slightly pushes.
Only when I  push the buttons near the max distance, ppsspp will get input values.

The minimum input values ppsspp get in "Test analogs" is about 0.75.
![Snap3](https://user-images.githubusercontent.com/8803140/58360590-2dde3700-7ebc-11e9-8c2f-4b5c9cfc2a2c.png)

And I have set the dinput and xinput deadzone settings to 0.0.
![Snap2](https://user-images.githubusercontent.com/8803140/58360584-24ed6580-7ebc-11e9-84bd-8693c2c3a0a8.png)

### What *should* happen?
PPSSPP should get inputs when I push the analog buttons slightly.
It should get small input values below 0.75.

Some flight simulation games like ace combat x, need analog sticks to work smoothly to play.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

PPSSPP 1.8.0
Windows 10 Home Edition（10.0.17763）
Gamepads(sticks)  I tested:
* BETOP BFM Gamepad 
* Thrustmaster Hotas 4
* xbox one wireless controller

**Comment by LunaMoo** [comment]
Seems that some change made it use axis to button threshold(normally used for translation from axis to buttons). My builds have a setting to change that threshold and it affects analog sticks now, pretty sure it's not how it was working in the past.

**Comment by LunaMoo** [comment]
I tested in game to make sure full range is used in games that support it and it is, so I renamed this issue to reflect what actually happens.

**Comment by royqh1979** [comment]
ok. Thanks!

**Comment by unknownbrackets** [comment]
Hm, the 0.75 threshold seems high.

I'd propose we lower it to at least 0.5, and then always draw the analogs +s, ignoring threshold, but only show the message if the value is beyond the threshold.  I think that'd make it clearer without burying other messages with noise.

-[Unknown]
