### ISSUE TITLE
Can’t download v 1.8.0 iOS 

### ISSUE THREAD

**Issue by Radical05** [hrydgard/ppsspp#12072]
Alright so this pretty stupid but my phone is jail broken yet I can’t seem to install v 1.8.0, I’ve tried all the links as well as entering them into cydia yet no matter what I do it will not update ppsspp to v 1.8.0, so will someone please instruct me to get around this problem?

                      Thanks in advance, Radical05

**Comment by LunaMoo** [comment]
Closing as directly related to #11905 where you can read more
In short, iOS port has no active maintainter neither it has a build provider so you'll not see any new versions until one of you(iOS users) becomes one and provide builds for others to download. Until then, you can build iOS version yourself.
