### ISSUE TITLE
Patapon 2 problems on Samsung SM-T231

### ISSUE THREAD

**Issue by Hasster1** [hrydgard/ppsspp#12073]
On my tab, there are some problems with patapon 2.
When i've encountered them before, i was using the european version of patapon 2 with russan translation, and i thought it was making those problems.
Then i've got normal usa version, and fully completed it with no problems on my phone (Honor 4C).
Now i'm trying to play the same version on my tab (Samsung SM-T231), and i've started to encounter the same glitches, that were on old european version of patapon 2.
There are a list of thise glitches:
1 - slow game on the levels with many enemies (etc. Hunting levels) - this might be because my tab is old, and every game is lagging on it, so don't bother with that one
2 - in paragate, after completing a level, in a minigame where you should hatch an egg by pressing buttons in order - the sound is delayed - the sound should match pressing buttons, but it's going too late. It's very hard to press buttons on right time, when sound is delayed, even if i've mastered this minigame before.
And the third - is the most disrurbing - when your troops stop loading.
In the obelisk/paragate, when your troops are loading, they sometimes could just stop loading at all, leaving a blank space which results in a softlock, because you can't start the level or go back - the game won't let you do it before loading every unit of an army.
If you'll try to change unit's weapons or helmet - it'll disappear too, and won't load.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

PPSSPP v1.8.0-237-gd0d8ea3fb

Here are some screenshots

![Screenshot_2019-06-01-18-45-05](https://user-images.githubusercontent.com/20757715/58750634-bdc44800-849d-11e9-8a30-f7011732b8d7.png)

![Screenshot_2019-06-01-18-45-14](https://user-images.githubusercontent.com/20757715/58750647-dcc2da00-849d-11e9-9066-1cd888e134c1.png)

![Screenshot_2019-06-01-18-45-18](https://user-images.githubusercontent.com/20757715/58750650-e6e4d880-849d-11e9-9383-5e046e80c39b.png)

**Comment by Hasster1** [comment]
Correction: in paragate's minigame, sound is not delayed. It's opposite of that - sound is ending too fast.

**Comment by unknownbrackets** [comment]
Some questions:

1. I was a bit unclear - on your Honor 4C, did you see any issues?  Were they only on the Samsung SM-T231, or on both devices?  The biggest difference is that one is arm64 (Honor 4C) and the other arm32 (Samsung SM-T231.)

2. On your Samsung SM-T231, can you enable the "FPS Counter" (end of graphic settings) to show "Both"?  This will show the speed the game is getting in the top right corner.  Then go somewhere it gets slowdown.  If the number drops below 100%, then yes - it's your phone's performance.  Increasing frameskip may help.

3. Are you using: a bluetooth (wireless) audio headset, your phone's built-in speakers, or 3.5mm connected earbuds/headset? (for the egg problem.)

4. Also, when the egg problem occurs, do you get 100% speed?  Does this happen even with frameskip disabled?

5. Is there any consistency on the troops not loading?  For example, does it never happen the first time after you load your save?

6. Do these issues reproduce if you avoid using save states at all?  For example, save in game, and then restart PPSSPP and load that save.  Then only use in-game saves until it happens again.  Also, make sure you don't have any cheats enabled when trying this.

-[Unknown]

**Comment by Hasster1** [comment]
1 - There are ISSUES on my TABLET (Samsung SM-T231), and there are NO ISSUES on my PHONE (Honor 4C). I've completed it entierly on my PHONE without even a single issue.

2 - Already enabled all the time, and no, there are 100% of the speed and 20/20 fps (Should be 30/30)
Frameskip doesn't do anything. 

3 - 3.5mm connected headset, but it doesn't really matter, it still lags.

4 - 100% speed, 30/30 fps, frameskip on/off - doesn't matter, still this sound is not in sync.

5 - IDK, it just happens randomly. Once it was when troops were just loading, Once it was when i've changed a weapon. Funny story, this thing actually hurt me really bad one time, where i got a cool hammer and went to test it before save... Then it happened, and i restarted the game.

6 - Not even a single save state here, i'm not using them since i've played patapon 3, and lost my save files because of them.

**Comment by unknownbrackets** [comment]
That's really interesting.  If it's not happening on arm64, this could indicate armjit bugs.

It's strange that timing / slowdown would be different on the two devices, because that's something that should generally be the same across arm32/arm64.  This could be related somehow to the audio - though I know that some devices have higher-latency audio output systems than others.

Thanks for the quick feedback.  Any chance you've tried any of these things on a PC?  Just to have another datapoint and confirm if it's ARM only (and not Intel.)

Also, it would make it slower (so beware) but can you try going into Settings -> Tools -> Developer tools, and change the CPU core to "IR Interpreter"?  If the bugs don't happen this way, it's not really a fix, but it would confirm that it's an armjit problem (since that disables jit.)

If that changes anything, there's another thing we can try.  In recent git builds, you set CPU core back to Dynarec (JIT), and then select "JIT debug tools" under it.  There you can try disabling parts of the jit to find what part is behaving incorrectly.  The best way to do this would be in clumps (i.e. try disabling all that start with VFPU first) and narrow down if you find a clump that helps.

ALU and LSU would probably have the biggest impact to speed, second to GPR Regalloc across instructions.  So you could try disabling all the others and see what happens.

It may be that it's not actually an armjit bug, in which case IR Interpreter or disabling parts of jit will make no difference.

-[Unknown]

**Comment by Hasster1** [comment]
IR interpreter didn't worked, the issue is still here.

**Comment by Hasster1** [comment]
Btw, i wanted to tell more about slowdowns.
They aren't casual slowdowns, because when game really lags (example: when i'm enabling interpreter core) then everything slows down - the game AND the music AND the controls.
So basically i have to press buttons much slower - the rythm changes and % of the speed isn't 100, but smaller.
But with those unususal slowdowns that happens only on levels with many enemies - only game slowdowns, i can normally control patapons, the rythm is still normal, and there is 100% speed with 20/20 fps, which has to be 30/30.
I think those slowdowns - are from the game itself, not from the emulator.

**Comment by unknownbrackets** [comment]
IT's very strange that such a slowdown would happen only on arm32 and not on arm64.

It would be great if you could confirm if any of these problems occur on a PC as well.

-[Unknown]

**Comment by Hasster1** [comment]
WHAT THE FU....
Ahem, sorry....

So, i've tried to play patapon on my laptop - Here's the system information
![psp1](https://user-images.githubusercontent.com/20757715/59560207-d3497e00-9016-11e9-982f-e85266fdffbf.png)
I've made the same config as on my tab, and.... They're here.
Those issues.
I've really thought it was just my old tab, but it's something else....

I think i'll better just drop my config here.
[UCUS98732_ppsspp.zip](https://github.com/hrydgard/ppsspp/files/3293883/UCUS98732_ppsspp.zip)

**Comment by Hasster1** [comment]
I FOUND IT!
I've changed emulated PSP's CPU clock back to 0 (I was previously using 40 on every game, since it wasn't giving me any trouble until now), and everything worked as intended!
This was the only option, that i didn't expect to ruin the entire game like that...

**Comment by hrydgard** [comment]
Oh! Well CPU clock is a very dangerous setting to change.

I've been thinking about how we can best warn people about settings that can have bad effects. Maybe if any such settings are set, show a quick warning screen when starting the game listing the settings. Though people quickly get used to just clicking through such things without reading...
