### ISSUE TITLE
Dumb iOS update issue 

### ISSUE THREAD

**Issue by Radical05** [hrydgard/ppsspp#12075]
Alright this is a pretty straight forward issue, so I’m trying to update ppsspp on my jail broken iPhone to v 1.8.0 and I’ve tried everything to update it yet unfortunately nothing works, I’ve tried putting the links in cydia, I’ve tried just clicking the links, etc., yet nothing seems to be working in my case so can someone please help me with my issue

                                Sincerely, Radical05

**Comment by LunaMoo** [comment]
Closing for same reason your previous issue (#12072) about same thing was closed.
iOS builds will not magically appear for you by spamming issues about them not being available:].

**Comment by unknownbrackets** [comment]
If you're passionate about this issue - remember, PPSSPP is open source.  If you can't wait any longer, muster up your courage and try setting up iOS builds yourself.  You could be that amazing person who solves this problem for everyone.

-[Unknown]
