### ISSUE TITLE
Cannot compile PPSSPP_libretro on Visual Studio 2019 Community version

### ISSUE THREAD

**Issue by JackoboLeChocobo** [hrydgard/ppsspp#12071]
### What happens?
Error during the compilation of PPSSPP (libretro support) on Windows 10 with Visual Studio 2019 Community version

```
6>native.lib(thin3d_d3d9.obj) : error LNK2019: symbole externe non résolu "bool __cdecl LoadD3DCompilerDynamic(void)" (?LoadD3DCompilerDynamic@@YA_NXZ) référencé dans la fonction "class Draw::DrawContext * __cdecl Draw::T3DCreateDX9Context(struct IDirect3D9 *,struct IDirect3D9Ex *,int,struct IDirect3DDevice9 *,struct IDirect3DDevice9Ex *)" (?T3DCreateDX9Context@Draw@@YAPEAVDrawContext@1@PEAUIDirect3D9@@PEAUIDirect3D9Ex@@HPEAUIDirect3DDevice9@@PEAUIDirect3DDevice9Ex@@@Z)
6>native.lib(thin3d_d3d9.obj) : error LNK2019: symbole externe non résolu "long __cdecl dyn_D3DCompile(char const *,unsigned int,char const *,struct _D3D_SHADER_MACRO const *,struct ID3DInclude *,char const *,char const *,unsigned int,unsigned int,struct ID3D10Blob * *,struct ID3D10Blob * *)" (?dyn_D3DCompile@@YAJPEBDI0PEBU_D3D_SHADER_MACRO@@PEAUID3DInclude@@00IIPEAPEAUID3D10Blob@@3@Z) référencé dans la fonction "public: bool __cdecl Draw::D3D9ShaderModule::Compile(struct IDirect3DDevice9 *,unsigned char const *,unsigned __int64)" (?Compile@D3D9ShaderModule@Draw@@QEAA_NPEAUIDirect3DDevice9@@PEBE_K@Z)
6>native.lib(d3d9_shader.obj) : error LNK2001: symbole externe non résolu "long __cdecl dyn_D3DCompile(char const *,unsigned int,char const *,struct _D3D_SHADER_MACRO const *,struct ID3DInclude *,char const *,char const *,unsigned int,unsigned int,struct ID3D10Blob * *,struct ID3D10Blob * *)" (?dyn_D3DCompile@@YAJPEBDI0PEBU_D3D_SHADER_MACRO@@PEAUID3DInclude@@00IIPEAPEAUID3D10Blob@@3@Z)
```

### What *should* happen?
I must have no error during the compilation of the project and get my ppsspp_libretro.dll
Compilation of the project for ppsspp_libretro.so on Linux (Xubuntu 18.04 - 64 bits) with Cmake and Make commands works without issue

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
OS : Windows 10 - 64 bits
PPSSPP : latest source code on github

**Comment by JackoboLeChocobo** [comment]
Thanks LunaMoo for adding the label on the ticket. I don't take the time to see if I could do it.

**Comment by JackoboLeChocobo** [comment]
Problem solved : 

I do this on ppsspp_config.sh

`// Comment this and uncomment PPSSPP_API_D3DX9 if D3DX9 is prefered.
**//#define PPSSPP_API_D3D9_D3DCOMPILER 1
#define PPSSPP_API_D3DX9 1**
#endif
#define PPSSPP_API_D3D11 1
#endif`

Have a nice day all !

**Comment by hrydgard** [comment]
having to manually change that is no good. 

Either it should be fixed to work with D3DCOMPILER, or you should check the libretro define (can't recall what it's named) and use an #ifdef to switch to D3DX9.

**Comment by JackoboLeChocobo** [comment]
From commit here I see the information : https://github.com/hrydgard/ppsspp/commit/21d2008676f261c7b5991445d18259bec6d3aa7c#diff-112074486f1bfc49a8914b05fc37076b

For information , compilation cannot be done on my computer without the modifications that I have done in my previous anwser.

**Comment by hrydgard** [comment]
I checked in a probably better fix.

**Comment by unknownbrackets** [comment]
I think it's very likely that fixed it and there hasn't been any update here to the contrary, so closing.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.

-[Unknown]
