### ISSUE TITLE
fix gold assets for UWP builds (file included)

### ISSUE THREAD

**Issue by dominater01** [hrydgard/ppsspp#12085]
since its still broken atm, here the appx manifest file
[PackageGold.zip](https://github.com/hrydgard/ppsspp/files/3257013/PackageGold.zip)

i cant do pull requests myself so if someone finds time pls add it

also hrydgard i know i asked you to do it which you still can but im adding this here as some sort of reminder

**Comment by hrydgard** [comment]
Yeah sorry I'll get to it soon.
