### ISSUE TITLE
PS3 Stick Controller suddenly not working anymore on OSX 10.14.5

### ISSUE THREAD

**Issue by hedikasmanto** [hrydgard/ppsspp#12096]
### What happens?

PS3 Stick Controller not working after upgrade OSX 10.14.5 (Mojave)
I have tested the joystick, still works properly on PS3 Console

### What *should* happen?
PS3 Stick Controller can be working properly

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Macbook Pro 2015 Earlier
OSX Mojave 10.14.5
PPSSPP v.1.6.3

I can't find PPSSPP 1.8.0 Mac version :(

**Comment by unknownbrackets** [comment]
We just use the SDL gamecontrollerdb, which should be a file in PPSSPP, so it might be that it's being reported to SDL as a different type of controller after the upgrade.

The "dev latest" here is at least a newer version, so might be worth trying:
https://build.ppsspp.org/?page/downloads#osx

It's also possible to compile PPSSPP on macOS, but it requires downloading Xcode from Apple (it's free, but many gigabytes to download.)

-[Unknown]

**Comment by hedikasmanto** [comment]
@unknownbrackets 

Please find this Issue too : https://github.com/hrydgard/ppsspp/issues/11799

- Dev Latest contains only txt file
- Someone have tried to compile using Mojave 14.4 and fails to compile

**Comment by hedikasmanto** [comment]
@unknownbrackets 
Just update about this issue...

I have tried to use PPSSPP 1.8 that compiled before.. and PS3 stick still not working

**Comment by hedikasmanto** [comment]
I have found root cause of this issue. OSX 10.14.5 will interrupt insecure bluetooth connection.
So Fake PS3 Stick will not work anymore after upgrade to 10.14.5. And I have tried using PS3 Stick Original from Sony PS3, and it works.. So I will close this issue

Source : https://support.apple.com/en-us/HT209149

```
Disables accessories with insecure Bluetooth connections.
```

**Comment by hrydgard** [comment]
OK, that's unfortunate, but thanks for reporting that!
