### ISSUE TITLE
1.8.0 version on Nvidia Shield K1 Tablet.. setting menu crash overtime.

### ISSUE THREAD

**Issue by DitzRoom** [hrydgard/ppsspp#12093]
### What happens?
Hi... at 1.8.0 version, the setting menu always crash when i want to opened. 

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
my device is Nvidia Shield K1 - Nougat 7.0 stock os.

**Comment by unknownbrackets** [comment]
Can you try the 1.7.5 version again and check that it doesn't happen there?  And also the latest git build and verify it still happens?

If yes to both, it'd really help if you could try git builds in between and try to narrow it down.

-[Unknown]

**Comment by DitzRoom** [comment]
> Can you try the 1.7.5 version again and check that it doesn't happen there? And also the latest git build and verify it still happens?
> 
> If yes to both, it'd really help if you could try git builds in between and try to narrow it down.
> 
> -[Unknown]

hi.. i was try with old version (1.5.4) and it's work properly.. thank you

**Comment by unknownbrackets** [comment]
There's been a lot of changes (about 2521) since v1.5.4.  It was released a year and a half ago.

It would help a lot if you could try some in between, like 1.7.5, 1.6.4, etc.

-[Unknown]

**Comment by hrydgard** [comment]
Do you mean that it crashes if you are just in the main menu of the emulator and press Settings, or if you pause a running game and go into settings?

**Comment by DitzRoom** [comment]
just when i want to open setting menu in ppsspp app. if i use version 1.5.4, setting menu it's work properly.. but, i just only can use opengl in backed. if choosing vulkan, the app will be crashed.

**Comment by Emulatorer** [comment]
@DitzRoom try the latest gitbuild of ppsspp
https://buildbot.orphis.net/ppsspp/index.php?m=fulllist and see if the issue still occur?

**Comment by Germaenace** [comment]
> @DitzRoom try the latest gitbuild of ppsspp
> https://buildbot.orphis.net/ppsspp/index.php?m=fulllist and see if the issue still occur?

I had and still have that issue too.
I installed newest auto build from your link. But still as soon as I try to enter settings in main menu of PPSSPP the app crashes.
Nvidia Shield tablet k1
Stock+ ROM 7.0 Android
Magisk as root

Can I send some logs or more info?

**Comment by Emulatorer** [comment]
@Germaenace could you try exporting a GE frame dump?

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

That's the only way how to know the developers about your graphics issue ^^

**Comment by Emulatorer** [comment]
Or use catlog https://play.google.com/store/apps/details?id=com.nolanlawson.logcat since your phone is rooted 🤔

**Comment by hrydgard** [comment]
Framedumps are not going to help when the emulator crashes. Logcat though, yes please.

**Comment by Germaenace** [comment]
Since I can't even access settings of PPSSPP, I made a logcat.
I attached the txt filtered for "PPSSPP".
Hope it helps.
[PPSSPP_LOG_2019-08-04-10-23-21.txt](https://github.com/hrydgard/ppsspp/files/3464684/PPSSPP_LOG_2019-08-04-10-23-21.txt)

**Comment by unknownbrackets** [comment]
Well, it's crashing in VulkanMayBeAvailable, so this is probably a driver problem... ugh.

Your ini also has "Failed graphics backends: OPENGL".  Can you try deleting ppsspp.ini and trying again?

-[Unknown]

**Comment by hrydgard** [comment]
We could blacklist the device ID... Can you check what it is in System Information?

Not that that style of workaround pleases me....

**Comment by Germaenace** [comment]
> Well, it's crashing in VulkanMayBeAvailable, so this is probably a driver problem... ugh.
> 
> Your ini also has "Failed graphics backends: OPENGL". Can you try deleting ppsspp.ini and trying again?
> 
> -[Unknown]

I tried it with deleted. Ini , cleared data, fresh installation of new build
Still crashes when selecting Settings.

**Comment by unknownbrackets** [comment]
Right.  So startup will call `VulkanMayBeAvailable()` if OpenGL is marked as failed, and settings will call it always.  Since that function is crashing with your drivers, this behavior makes (unfortunate) sense.

There is a workaround you can apply, but it won't make this stop being a bug.  You'll need to edit PSP/SYSTEM/ppsspp.ini and find the line `DisabledGraphicsBackends = `.  Change it to `DisabledGraphicsBackends = VULKAN`.  This will prevent PPSSPP from even considering Vulkan a viable option for you.

We had this problem on Windows with terrible AMD drivers, and we checked on Vulkan out of process.

In theory, it would be possible to do the same here and ship a separate binary to check on Android.  That said, I haven't a clue how to build a binary command line Android app with Gradle.  And it's very sad to even consider resorting to such a thing anyway....

I can only imagine if checking if you had a Bluetooth headset randomly sometimes crashed some devices.  In fact, I think that used to be true in the days of Windows 98 or XP or something...

-[Unknown]

**Comment by Germaenace** [comment]
Thanks for your detailed answer!
I made the change in PPSSPP.ini
That way everything seems to work now.

Do you think, the shield tablet k1 even would take advantage by VULKAN? This is an AMD/ATI development, right?
Still am in good mood that the tablet has enough power to emulate all. Got this device for games and big part is PSP through PPSSPP! 😉

So thanks again! Let me know if I can help in testing with this tablet (or Shield TV)...

**Comment by hrydgard** [comment]
Vulkan works just great on NVIDIA chips that support it, like Shield TV, nothing AMD specific about it despite its root in Mantle. The old tablet, though, doesn't.

Can you go to Game Settings / System / Tools / System Information and tell me what it says next to "Name"?

**Comment by hrydgard** [comment]
@Germaenace  can you download a new build from https://buildbot.orphis.net/ppsspp/ , remove the line from PPSSPP.ini, and try again?

**Comment by Germaenace** [comment]
A little late, but here you have the screenshots of system info in PPSSPP settings.
I will try newest build right now and give response in some minutes...
![Screenshot_20190815-084934](https://user-images.githubusercontent.com/44316909/63078103-b956e980-bf3a-11e9-90b0-a839c438aa25.png)
![Screenshot_20190815-085007](https://user-images.githubusercontent.com/44316909/63078106-b956e980-bf3a-11e9-83f7-901208849d5d.png)

**Comment by Germaenace** [comment]
Okay. I tried build 154. Deleted ini.
Again PPSSPP crashes.
See log
[PPSSPP2019-08-15-09-04-35.txt](https://github.com/hrydgard/ppsspp/files/3504586/PPSSPP2019-08-15-09-04-35.txt)

**Comment by hrydgard** [comment]
Yeah, I need to change the blacklist string. I'll fix it up.

**Comment by hrydgard** [comment]
I fixed it, then I made another commit that disables the blacklist again but adds more log output. If you could try that build and get another log, it would be great.

**Comment by Germaenace** [comment]
With build 516 PPSSPP crashes on start of app.

[PPSSPP_2019-08-15-11-32-18.txt](https://github.com/hrydgard/ppsspp/files/3505036/PPSSPP_2019-08-15-11-32-18.txt)

**Comment by hrydgard** [comment]
Very curious:

"08-15 11:32:51.400 E/PPSSPP  (19691): [LOADER] Failed graphics backends: OPENGL
08-15 11:32:51.400 E/PPSSPP  (19691): [LOADER] Graphics backend failed for 0, trying another"  

Wonder how that happened..

Anyway, in a new commit I just re-added your device name to the blacklist so it should not crash any more.

**Comment by Germaenace** [comment]
I tried new build. Works fine.
Log in case it's useful:
[PPSSPP_2019-08-15-12-37-49.txt](https://github.com/hrydgard/ppsspp/files/3505233/PPSSPP_2019-08-15-12-37-49.txt)


Copy of edit from last post:
Edit:
It seems like it doesn't get whole resolution height, but just without pixels of bar with home button etc. at bottom of display (?)
I can set fullscreen on in shield tablets quick settings. Bottom bar disappeares on every screen (extended desktop?) and also in PPSSPP. Now resolution is correct recognized as 1920 1200.
Don't know if it helps.

**Comment by hrydgard** [comment]
Weird. Separate issue though, please make a new one with details. Closing this one.
