### ISSUE TITLE
Compile error on NDK r20

### ISSUE THREAD

**Issue by 846524417** [hrydgard/ppsspp#12105]
我通过Github 下载了最新的PPSSPP源码，并且用最新的Android Studio打开项目。NDK跟Cmake全部安装完成。SDK路径配置没错，但是报错了。有人能告诉我，我还需要做些什么吗？

**Comment by 846524417** [comment]
This is my build Variant
![image](https://user-images.githubusercontent.com/51825152/59548752-51aa0f80-8f86-11e9-9458-b307680b1002.png)

**Comment by 846524417** [comment]
![image](https://user-images.githubusercontent.com/51825152/59548780-96ce4180-8f86-11e9-9599-bb61e5e1fcd2.png)
This is the screenshot of the error report. I did not do anything after importing it.

**Comment by 846524417** [comment]
![image](https://user-images.githubusercontent.com/51825152/59548801-c5e4b300-8f86-11e9-9cef-d887e394a5ce.png)
This is not the case where I downloaded some files completely.

**Comment by 846524417** [comment]
![image](https://user-images.githubusercontent.com/51825152/59548836-24119600-8f87-11e9-836a-2e2cd89cb7b3.png)
I see here that I'm missing these two files, if so.Where should I download it?

**Comment by 846524417** [comment]
![image](https://user-images.githubusercontent.com/51825152/59548915-0d1f7380-8f88-11e9-8c5d-38a7c8428a7f.png)
This is a screenshot of cmakeoutput.log

**Comment by 846524417** [comment]
![image](https://user-images.githubusercontent.com/51825152/59549030-fbd76680-8f89-11e9-8904-d6d30549d1a2.png)

**Comment by LunaMoo** [comment]
You're missing submodules, check how to download the source code properly in [here](https://github.com/hrydgard/ppsspp/wiki/Build-instructions).

 You're also using latest NDK, this is not related to the problem you're seeing and not even sure if it's a thing for x86 android, but from my recent experience PPSSPP will not build with latest NDK, I used android-ndk-r16b, through it's probably not the only on that works, you can check a guide how to use older NDK's in Android Studio in [here](https://stackoverflow.com/questions/52503989/android-sdk-manager-install-specific-version-of-ndk-bundle).

**Comment by hrydgard** [comment]
Actually, while officially not compatible with the old versions of Android that PPSSPP supports, the latest NDK works fine.

Just update the submodules and you'll be fine.

**Comment by 846524417** [comment]
I lack those submodules, where should I download them?

**Comment by unknownbrackets** [comment]
Use `git submodule update --init` (also seen in build instructions.)

-[Unknown]

**Comment by LunaMoo** [comment]
@hrydgard you sure about latest NDK? I got the same problem when trying to build latest master as the user had with compiling my branch in this [log](https://forums.ppsspp.org/attachment.php?aid=16599). I never used android studio before, but travis builds with older NDK and that's what I tried and which helped to build fine. :3

**Comment by hrydgard** [comment]
Have not had any such issues on ndk up to 19 at least.

**Comment by LunaMoo** [comment]
Maybe a new thing with ndk 20 then.

**Comment by 846524417** [comment]
![image](https://user-images.githubusercontent.com/51825152/59566097-c7e56980-908d-11e9-941e-4eae7d8efe30.png)
    @@@@![image](https://user-images.githubusercontent.com/51825152/59566105-ddf32a00-908d-11e9-8343-aed9bab71dc9.png)
After I updated the sub-module according to what you said, there was an error in compiling it.What's this about?
     @@@@@@

**Comment by LunaMoo** [comment]
As I wrote in my reply in addition to missing submodules:

> **You're also using latest NDK (...), you can check a guide how to use older NDK's in Android Studio in [here](https://stackoverflow.com/questions/52503989/android-sdk-manager-install-specific-version-of-ndk-bundle).**

NDK v19 should be ok from what Henrik said.

**Comment by hrydgard** [comment]
I'm gonna have another look at the ndk issue soon. It shouldn't fail, I'd be very annoyed if we can't keep up with the latest SDK anymore.

**Comment by unknownbrackets** [comment]
Please see android-ndk/ndk#1000.

-[Unknown]

**Comment by hrydgard** [comment]
Oh, ok. So I guess we're waiting for an NDK fix then.

**Comment by hrydgard** [comment]
This should now be "fixed" (or at least worked around).

Please close when confirmed.
