### ISSUE TITLE
vtfm instruction broken in Interpreter

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#12109]
Falling this instruction back to interpreter on current master using the JIT debug tools breaks graphics in GTA: LCS pretty badly. Probably some fallout from @unknownbrackets prefix fixes: https://github.com/hrydgard/ppsspp/commits/ec7cffa847  , should be fairly easy to track down.

**Comment by unknownbrackets** [comment]
Dumb mistake, I think I even remember copy/pasting the ternaries and thinking "I'll need to change this" but then clearly forgot after testing something (may have found a bug elsewhere.)

-[Unknown]
