### ISSUE TITLE
Gamesir G3w controller not supported

### ISSUE THREAD

**Issue by ghost** [hrydgard/ppsspp#12102]
Feren OS  
cinnamon version 4.0.10
Linux Kernel 4.18.0-21-generic

PPSSPP (SDL) 1.70

I have not been able to get this controller to work with PPSSPP. Is there a list of what controllers actually work with PPSSPP Linux versions? I have thought of getting the the SteelSeries Stratus which sounds like a nice addition for PC gaming.

**Comment by LunaMoo** [comment]
PPSSPP uses [gamecontrollerdb](https://github.com/hrydgard/ppsspp/blob/master/assets/gamecontrollerdb.txt) to support gamepads on your OS, you can use SDL tools or some other software like [this](http://generalarcade.com/gamepadtool/) to add your gamepad to the list. Feel free to open pull request with your gamepad added if you do so.

**Comment by Gitlab1111** [comment]
Thank you, will respond when I get around to utilizing it. The Gamesir controllers are usually under Xiaoji. I did not see the SteelSeries on that list either.

**Comment by unknownbrackets** [comment]
PPSSPP relies on community contributions for this DB, and it looks like the original issue author has deleted their account.  If anyone is interested in contributing mapping information to PPSSPP, it's welcome.

That being said, there are probably a lot of controllers (unfortunately) not in that database.  I'm going to close this given that the author deleted their GitHub account.

-[Unknown]
