### ISSUE TITLE
[Android] [PC] [Not Enough FPS] Death JR 2: Root of Evil ULUS10157

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#12101]
### What happens?
The game is really.. really.. slow on my device using any version of ppsspp or trying different settings this game is slower than Digimon Adventures

### TESTED ON THE FF DEVICES
•Android 5.1 Lollipop
•MT6592 MALI-450 MP
•Octacore
•1.4GHz
•Android 6.0 Marshmallow
•Snapdragon 430 Adreno 506
•Octacore
•1.4Ghz

### SCREENSHOTS
![Screenshot_2019-06-14-09-30-23](https://user-images.githubusercontent.com/37603562/59477682-d9a9ef80-8e88-11e9-9d31-bf07f0d91b17.png)
![Screenshot_2019-06-14-09-34-34](https://user-images.githubusercontent.com/37603562/59477688-e29ac100-8e88-11e9-9438-4afd17841676.png)

**Comment by Drasikk** [comment]
If it helps, I've tried it on my Samsung Galaxy Note8 Exynos and it works well for speed.

![PPSSPP_2019-06-14-13-25-33](https://user-images.githubusercontent.com/38067925/59506985-ea1e9200-8ea9-11e9-8b76-fe4ee4756aeb.jpg)

I've activated this speed trick

![PPSSPP_2019-06-14-13-25-59](https://user-images.githubusercontent.com/38067925/59507036-11755f00-8eaa-11e9-9223-179107117cfe.jpg)

At first it was a little slow, but activating that trick is much better.

**Comment by Emulatorer** [comment]
@Drasikk thanks but I already did that nothing change in performance because Death JR 2 Root Of Evil default FPS is 30 😅

Maybe if you have a 20 or 15 FPS cheat code that could help improve the performance of the game in my devices

**Comment by unknownbrackets** [comment]
Could you try exporting a GE frame dump?

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by Emulatorer** [comment]
@unknownbrackets here 
[Death Junior 2: Root Of Evil GE Dump.zip](https://github.com/hrydgard/ppsspp/files/3293707/Death.Junior.2.Root.Of.Evil.GE.Dump.zip)

**Comment by benderscruffy** [comment]
same happens to the PC version aswell
![death](https://user-images.githubusercontent.com/2696404/59560036-67c6d700-903d-11e9-92d4-65b8bda89f8c.PNG)

**Comment by LunaMoo** [comment]
Well it depends on your gpu power, weaker pc's aren't really more powerful than a new mobile, but modern gaming pc's can brute force more demanding games pretty easily:
![ULUS10157_00002](https://user-images.githubusercontent.com/5485237/59563734-2682f700-903e-11e9-8b9a-c3df79c42ab3.jpg)

but yeah this game is heavilly bottlenecked on the gpu side, it does a lot of small draws to blend bloom effect with pre-bloom image, the result doesn't seem to differ in any noticeable way, but it's probably what makes it so demanding.

**Comment by hrydgard** [comment]
It might be possible to fix/workaround this the same way we did with the Sonic games in Vulkan, but haven't looked in detail yet.

**Comment by unknownbrackets** [comment]
Unfortunately, the record doesn't capture the bulk of what it's doing (probably block transfers?)

-[Unknown]

**Comment by Emulatorer** [comment]
@unknownbrackets do I need to upload GE dump of this game?

**Comment by unknownbrackets** [comment]
No, it was a useful dump but it doesn't show the thing causing the performance exactly enough (the GE dump has limits in how precisely it can record what the game is doing, since it only records graphics things.)

-[Unknown]

**Comment by Emulatorer** [comment]
Hoping this can help #12602 to this issue

**Comment by unknownbrackets** [comment]
The changes in #12602 will not make any game run faster.  If you think of CPU power as money, slowness is when you're in debt.  #12602 will spend a bit more money, so it will definitely be slower.

The good thing about #12602 is that it will spend money a bit more evenly.  So rather than spending 1000 € every month on one day, it will spend 250 € every week.  It will be a bit more money total, but it will not be a sudden surprise as often.

Back to performance, any game that lags or runs slow will at best be just as bad.  Only if a game can run at 100% speed but you're still seeing frames drop occasionally (that is, not having 1000 € all at once some rare days) will that change help.

-[Unknown]

**Comment by unknownbrackets** [comment]
I'll just note: I realized later and commenting here to correct myself: the above explanation ignores the heuristics your device might have on its performance throttling for battery life / temperature.

A possible (though not at all certain) outcome is that #12602 convinces your OS to give PPSSPP more power and results in an improvement in performance, actually.  Because the way these behave is a bit of a "black box" to us, it's hard to predict.

-[Unknown]

**Comment by hrydgard** [comment]
So it turns out that our current Vulkan render pass reordering does a pretty decent job fixing this game up - so if you can, switch to Vulkan for this game. This won't be possible on older devices like the mentioned one with Mali 450, of course, unfortunately.

I'll add an OpenGL tag and postpone.

**Comment by Emulatorer** [comment]
No improvement in my phone w/ mali-450 gpu but on my tablet w/ mali-t720 gpu this game improve a little bit.

How in your PC @benderscruffy any improvement?

**Comment by Emulatorer** [comment]
I notice that when I'm enable render duplicate frames to 60hz and using a shader makes th game laggy 🤔

e.g Tekken6 w/ Natural Colors No Bloom Render Duplicate Frames to 60hz is ON
![Screenshot_20200317-141518](https://user-images.githubusercontent.com/37603562/76828354-b834c480-685b-11ea-914c-0655709e70e0.png)

Tekken6 w/ Natural Colors No Bloom Render Duplicate Frames to 60hz is OFF
![Screenshot_20200317-141542](https://user-images.githubusercontent.com/37603562/76828521-224d6980-685c-11ea-9e17-5517171920f0.png)

**Comment by Panderner** [comment]
@emulatorer what device are you using? Name of your device not the specs

**Comment by hrydgard** [comment]
@Panderner  Please make sure to post reports in the right issue. That is irrelevant for Death JR, create a new issue if you can't find a suitable one.

**Comment by Gamemulatorer** [comment]
PPSSPP v1.11.3 still have a framedrop on OGL default settings using my Redmi9 but on VK it's running smooth :)

Should I close this?

**Comment by Gamemulatorer** [comment]
Perfectly smooth on Vulkan and slightly framedrops on OpenGL using my Redmi Note 9 :). Closing..
