### ISSUE TITLE
"Gitaroo Man Lives!" Cannot join multiplayer sessions

### ISSUE THREAD

**Issue by JonTerp** [hrydgard/ppsspp#12114]
Repro steps:

Launch "Gitaroo Man Lives!"(ULUS10207) on two clients that are confirmed to work with ad-hoc multiplayer (I used Monster Hunter Freedom Unite).

1. Select "Multiplay" on the main menu.
2. On one client select "Duet Start" and idle on the next screen. (Network will init here).
3. On the other client press "Join Game". (Network will init here).
4. Clients should start trying to send packets to each other.
5. Observe the "Join Game" client never joins the session.

### What happens?
When attempting to join an existing multiplayer session in "Gitaroo Man Lives!" the searching client will never find the existing session.

This has been tested with multiple configurations and even LunaMoo's ad-hoc fork build (https://github.com/LunaMoo/ppsspp). All testing instances were tested against Monster Hunter Freedom Unite to confirm multiplayer was fully functional.

1.8.0 Local network Pro Adhoc server: Clients connect to the ad-hoc server and send [HELLO] packets forever when both clients are waiting for matches / joiners.

1.8.0 Remote ad-hoc server: Using remote ad-hoc server "psp.gameplayer.club". After many attempts, the searching-for-matches client will send a [JOIN] packet. But the host-match client replies with [REJECT].

LunaMoo (two instances running on one PC): Reliably sends [JOIN] packets replied with a [REJECT].

LunaMoo Local network ad-hoc: Same as 1.8.0 remote ad-hoc server.

### What *should* happen?
The searching-for-match client should quickly see the hosting client and connect to the match.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Windows 10, 1.8.0 (LunaMoo fork for testing).

### Logs

PC Host 1.8.0: https://pastebin.com/zDar8nJT
LunaMoo (two instances) Host: https://pastebin.com/QEaFDsEP
LunaMoo (two instances) Client: https://pastebin.com/4EaPZFeq

**Comment by LunaMoo** [comment]
My branch has adhoc stuff mostly from #8134, but I didn't kept original commits and just picked the changes to enable adhoc on same pc, adding hacks on top of it.
 I cleaned it and rebased keeping hacks in separate commits in case we want at least the adhoc on same pc functionality merged as it does make testing adhoc much easier solo while I don't really want my hackish branch to be used for any kind of compatibility testing ~ even less with my nickname misspelled ;p.

 All adhoc related changes from my branch can be seen here: https://github.com/hrydgard/ppsspp/compare/master...LunaMoo:AdhocStuff_from_THBranch?expand=1

**Comment by JonTerp** [comment]
> 
> 
> My branch has adhoc stuff mostly from #8134, but I didn't kept original commits and just picked the changes to enable adhoc on same pc, adding hacks on top of it.
> I cleaned it and rebased keeping hacks in separate commits in case we want at least the adhoc on same pc functionality merged as it does make testing adhoc much easier solo while I don't really want my hackish branch to be used for any kind of compatibility testing ~ even less with my nickname misspelled ;p.
> 
> All adhoc related changes from my branch can be seen here: https://github.com/hrydgard/ppsspp/compare/master...LunaMoo:AdhocStuff_from_THBranch?expand=1

Ah sorry about misspelling your name. I have dyslexia and it happens all the time :P

**Comment by unknownbrackets** [comment]
Is this still an issue on the latest git build with recent networking improvements?

-[Unknown]

**Comment by ANR2ME** [comment]
According to this local multiplayer game list, Gitaroo Man Lives seems to works fine on localhost https://docs.google.com/spreadsheets/d/1PvBsDWtA4VueBtr9vz_aLPIXwpkgjxMCyQOy8sIMaok/edit#gid=0
