### ISSUE TITLE
Black screen on vice city with buffer render

### ISSUE THREAD

**Issue by Askmewho** [hrydgard/ppsspp#12112]
Hi, ive just compiled ppsspp and the games are running good on my armhf platform. Why is it not launching?? Any way to debug???

**Comment by hrydgard** [comment]
running god? good? what?

**Comment by Askmewho** [comment]
Its happenning on other games, I am running on an rpi3 with mesa 19 and sdl 2.0.9

**Comment by Askmewho** [comment]
Hahah sorry, good.

**Comment by Askmewho** [comment]
@hrydgard could you give me any debug instruction to give you more info??

**Comment by Askmewho** [comment]
it was the fbdev!!!! mindblowing performance!!! i am stunned !!!
