### ISSUE TITLE
Since iOS external display, the Exit button causes hangs / freezes

### ISSUE THREAD

**Issue by Halo-Michael** [hrydgard/ppsspp#12140]
### What happens?
In the latest version (0v1.8.0-367-ge8aad38e7), the "Exit" button does not work and will cause the program frozen
This is different from the problem in https://github.com/hrydgard/ppsspp/issues/11905 . When the "Exit" button is pressed and the program is frozen, side PPSSPP out of the background and re-open it, PPSSPP can still work.

### What *should* happen?
In version 0v1.8.0-291-gcfa79b686, this problem does not exist yet - the program will exit normally after pressing the "Exit" button

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Apple A10 arm64, iOS 12.1.1, 0v1.8.0-367-ge8aad38e7

**Comment by Halo-Michael** [comment]
It seems that more than that. On the non-jailbroken device, whether side PPSSPP out of the background or clicke the "Exit" button, ppsspp will be frozen, only restart can make it work again.

**Comment by Halo-Michael** [comment]
Things are worse than I thought. On devices that use Electra (iPhoneXS, iOS 12.1.2), PPSSPP will also freeze when trying to exit—until it restarts.

**Comment by Halo-Michael** [comment]
I really have a hard time confirming whether this is still caused by syscall - on devices that use unc0ver to jailbreak, it will freeze when clicking the exit button on the main page, and when side out PPSSPP from background and then enter PPSSPP again, it will also freeze briefly  - But eventually it will work again without any other operations.

**Comment by unknownbrackets** [comment]
It sounds like this is related to #12096 

What happens if you revert these changes?
https://github.com/imxieyi/ppsspp/commit/1affe0bff3c62fbdc6235e061d40d82eecf71785#diff-ae393d2b0619781d62bbb186fef9e7dc

Maybe it was only secretly working before because it was crashing on exit?

-[Unknown]

**Comment by Halo-Michael** [comment]
> It sounds like this is related to #12096
> 
> What happens if you revert these changes?
> [imxieyi@1affe0b#diff-ae393d2b0619781d62bbb186fef9e7dc](https://github.com/imxieyi/ppsspp/commit/1affe0bff3c62fbdc6235e061d40d82eecf71785#diff-ae393d2b0619781d62bbb186fef9e7dc)
> 
> Maybe it was only secretly working before because it was crashing on exit?
> 
> -[Unknown]

Yes, it is.

**Comment by unknownbrackets** [comment]
Oops, when I paste #12094, GitHub is strangely changing it to #12096.

-[Unknown]

**Comment by Halo-Michael** [comment]
Wrong tap

**Comment by Halo-Michael** [comment]
> Oops, when I paste #12094, GitHub is strangely changing it to #12096 (in the issue typeahead autocomplete.)
> 
> -[Unknown]

That's really cool!
Will external display support broken if revert https://github.com/imxieyi/ppsspp/commit/1affe0bff3c62fbdc6235e061d40d82eecf71785#diff-ae393d2b0619781d62bbb186fef9e7dc ? (I don't have Lightning-to-HDMI line so I can't test it)

**Comment by unknownbrackets** [comment]
I'm not sure - I don't have any iOS device to test it.  I think probably not.

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, I think it makes sense to try to revert that part.

**Comment by Halo-Michael** [comment]
eg: If really need revent, just revent the part of main.mm

**Comment by hrydgard** [comment]
Ok, done.

**Comment by imxieyi** [comment]
This issue seems to be related to iOS version. I included this in #12094 because touching exit button caused hang on both iOS 12.1.1 and 12.3 and this change fixed it.

I just tried the latest code on master branch on both iOS 12.4 and 13.1.1 and the exit button caused hang. The reason was the same as before:

```
Assertion failed: (!initialized_), function ~Discord, 
file /.../ppsspp/UI/DiscordIntegration.cpp, line 42.
```

 However it works again if I change the exit routine to the same as #12094.

Maybe we can try running ppsspp on different iOS versions and figuring out since which version this change is needed?

**Comment by unknownbrackets** [comment]
Maybe the assertion failing trips some kind of handling that prevents the hang (since the hang is caused by a "debugger" being attached)?

I think Discord is disabled on iOS anyway, but that code still runs (it's deeper in that it's disabled.)

-[Unknown]

**Comment by hrydgard** [comment]
Good find! Should be pretty easy to fix then.

**Comment by hrydgard** [comment]
So it seems that NativeShutdown doesn't run on iOS then, since it calls g_Discord.Shutdown() which would prevent this assert from triggering.

Nevertheless I'm disabling the assert for now since it's pretty low-value.

**Comment by Halo-Michael** [comment]
So can we restore the exit animation on iOS now?

**Comment by hrydgard** [comment]
No idea about that stuff, sorry

**Comment by Halo-Michael** [comment]
After merge the pull request #12421 from sbingner, this problem can basically be confirmed as a complete fix. Even if you run PPSSPP on non jailbroken device, or if CS_DEBUGGED is not turned on, it will no longer freeze on exit.
I have compiled ipa and deb for it and can use them for testing.
https://github.com/Halo-Michael/halo-michael.github.io/raw/master/ipas/PPSSPP_0v1.9.3-80-g73bf6098e.ipa
https://github.com/Halo-Michael/halo-michael.github.io/raw/master/repo/debs/org.ppsspp.ppsspp-dev-latest_0v1.9.3-80-g73bf6098e_iphoneos-arm.deb
