### ISSUE TITLE
Crisis Core Final Fantasy VII (ULUS10336) Android, graphical issue

### ISSUE THREAD

**Issue by mrtawsiti3** [hrydgard/ppsspp#12143]
What happens?
- character doubles x2 on one screen, next scenes he is invisible.

### What *should* happen?
There can be only one same character on one screen and he should be visible on the next scenes.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Snapdragon 855, android 9.0, ppsspp gold 1.8.0 OpenGL and Vulkan

**Comment by mrtawsiti3** [comment]
![Screenshot_20190629-195256](https://user-images.githubusercontent.com/35630219/60387900-66b88f80-9aaa-11e9-9d07-0f1157f08eab.png)
![Screenshot_20190629-195301](https://user-images.githubusercontent.com/35630219/60387901-66b88f80-9aaa-11e9-8e16-10e122acba7f.png)
![Screenshot_20190629-195304](https://user-images.githubusercontent.com/35630219/60387903-66b88f80-9aaa-11e9-9d7a-31063e63c80d.png)
![Screenshot_20190629-195237](https://user-images.githubusercontent.com/35630219/60387904-66b88f80-9aaa-11e9-970f-71b2574c4190.png)
![Screenshot_20190629-195249](https://user-images.githubusercontent.com/35630219/60387905-67512600-9aaa-11e9-8d47-3f6e254d1b6c.png)

**Comment by Emulatorer** [comment]
Try to use ppsspp gitbuild from buildbot and see if this issue still happening https://buildbot.orphis.net/ppsspp/index.php?m=fulllist

**Comment by mrtawsiti3** [comment]
It is fixed on latest github version
