### ISSUE TITLE
GoW Block Transfer Effects Bugged

### ISSUE THREAD

**Issue by C4rrotMilk** [hrydgard/ppsspp#12169]
What happens?

It seem like the block transfer effects are on by default and unable to turn off or something? It make GoW graphic flickering if I didn't turn it off

What *should* happen?

On:
https://imgur.com/a/AocpBFk

Off:
https://imgur.com/a/80v2yQM

It bugged after v1.7.5-431-g9736bc431

What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Huawei Mate 9 MHA-L29 HiSilicon Kirin 960 Mali-G71 MP8 Android 8.0

**Comment by Emulatorer** [comment]
Look like the same graphics issue 🤔
![Locking Bloom Effects](https://user-images.githubusercontent.com/37603562/61127332-8e174f80-a4e1-11e9-83ff-2f56869dc726.jpeg)

**Comment by hrydgard** [comment]
I am so sick of broken graphics drivers... The game works in PPSSPP, it's the driver that screw things up. You can't switch to Vulkan?

**Comment by C4rrotMilk** [comment]
Uhhh I'm on Vulkan, it's fine on OpenGL but fps is low

**Comment by Emulatorer** [comment]
Similar #11127? Maybe this a driver bug try to update your Vulkan api 🙂

**Comment by C4rrotMilk** [comment]
I think there might have some misunderstanding here. I play with BTE off and it's working fine on v1.7.5-431 just like screenshot 2, but on v1.7.5-433 uncheck the BTE option box doesn't turn the effect off and result in screenshot 1. Is it really driver bug? 🤔

**Comment by hrydgard** [comment]
Ah, okay. Yeah, sorry I misunderstood. I don't generally test stuff with BTE off very much...  I recommend to always have it on. Does it make a big speed difference in this game for you_

**Comment by C4rrotMilk** [comment]
I don't know since I didn't play with BTE on, it make everything flickering on my device, totally unplayable. I only notice some fps drop on mobs heavy scene with it off 😅

**Comment by Emulatorer** [comment]
@C4rrotMilk Could you try exporting a GE frame dump?

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

That's the only way how to know the developers about your graphics issue ^^

**Comment by C4rrotMilk** [comment]
From latest Git build
[recording.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/3389492/recording.ppdmp.zip)

**Comment by PilipinoAko** [comment]
I play this but issue in there is speed of game me using 30fps cheat
And how to use frame dump

**Comment by hrydgard** [comment]
Most of these glitches (not talking about performance) should now have been fixed by https://github.com/hrydgard/ppsspp/pull/12224. Can you guys confirm?

**Comment by C4rrotMilk** [comment]
> These glitches (not talking about performance) should now have been fixed by #12224. Can you guys confirm?

Ya the glitches are fixed but performance is low since it still running with BTE on by default. I understand that the game should be running with BTE on for correct graphic and you wanna get rid of that option too.Well, hope you find a way to improve it  meanwhile I still gonna play it on old build due to performance issue, cheers 🙂

**Comment by hrydgard** [comment]
Thanks for confirming!

I'm closing this, but I'll also be cooking up some possible performance improvements that may let you run with BTE...

**Comment by Emulatorer** [comment]
@C4rrotMilk try to create compat.ini inside psp system folder and add this text inside compat.ini

[BlockTransferAllowCreateFB]

# GOW : JP/Korean
UCJS10114 = true
UCKS45084 = true
# GOW : Ghost of Sparta
UCUS98737 = true
UCAS40323 = true
NPHG00092 = true
NPEG00044 = true
NPEG00045 = true
NPJG00120 = true
NPUG80508 = true
UCJS10114 = true
UCES01401 = true
UCES01473 = true
# GOW : Ghost of Sparta Demo
NPJG90095 = true
NPEG90035 = true
NPUG70125 = true
# GOW : Chains Of Olympus
UCAS40198 = true
UCUS98653 = true
UCES00842 = true
ULJM05438 = true
ULJM05348 = true
UCKS45084 = true
NPUG80325 = true
NPEG00023 = true
NPHG00027 = true
NPHG00028 = true
NPJH50170 = true
UCET00844 = true
# GOW: Chains of Olympus Demo
UCUS98705 = true
UCED00971 = true
UCUS98713 = true

Hope it can help about the performance issue on your phone even BTE is enable ^^
