### ISSUE TITLE
Valkyrie Profile (US) Black Screen on Cutscene

### ISSUE THREAD

**Issue by rkguy** [hrydgard/ppsspp#12165]
### What happens?
On the second cutscene of the game (where the girl transforms into a monster), the screen cuts to a black screen instead of playing the cutscene. You can hear the audio, but the movie doesn't play. 

### What *should* happen?
The cutscene should play along with the audio

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Windows, ver 1.8.0, desktop

**Comment by unknownbrackets** [comment]
Pretty sure this used to work - can you try some old versions and check when it last used to work?

-[Unknown]

**Comment by Emulatorer** [comment]
Similar  #12045?

**Comment by hrydgard** [comment]
That seems to be the same issue, yes. Closing as duplicate.
