### ISSUE TITLE
Is compile with the latest submodules better, or compile with the submodule version which PPSSPP currently using?

### ISSUE THREAD

**Issue by Halo-Michael** [hrydgard/ppsspp#12163]
PPSSPP is a terrific job with a lot of complicated code, and there are a lot of external sub-modules. I noticed that many of the submodules being used actually have a newer version. So, is it better to use the recorded submodule version (git submodule update --init --recursive) or the latest submodule version (git submodule update --remote) when actually compiling?

**Comment by hrydgard** [comment]
Always compile with the recorded submodules, that is, ```update --init --recursive``` (except for assets/lang, optionally).
