### ISSUE TITLE
Fast foward bug

### ISSUE THREAD

**Issue by PilipinoAko** [hrydgard/ppsspp#12168]

**Comment by Emulatorer** [comment]
HEY! fill up all the information requirements or else the developers will close this issue 🤷

**Comment by marosis** [comment]
We need more informations. But i know about one. When i hold in video cutscene 'ff' button video is running faster (that's normal) but i see only one same frame.

**Comment by hrydgard** [comment]
That happens because on mobile we are frame skipping during fast forward. Could possibly change it to render multiple frames every device frame to help this, but fast-forward speed would be reduced.

**Comment by PilipinoAko** [comment]
When i play some game its force close when pasforwarding

**Comment by Emulatorer** [comment]
@PilipinoAko anong game at anong phone meron ka ba?

**Comment by PilipinoAko** [comment]
Date kase MALI AKO NGAYON ADRENO many problems in adreno driver for mali
the emulation is great but adreno has many bugs for my opnion

**Comment by unknownbrackets** [comment]
To help, we need information:
 * Which games crash on fast forward?  Specific names help.
 * Does this happen with default settings?  Or only with customized settings?
 * Have you tried the latest git build?  What version of PPSSPP are you using?
 * What phone/device are you using?

Adreno and Mali drivers both definitely have bugs that can affect games.

-[Unknown]

**Comment by Emulatorer** [comment]
@PilipinoAko No feedback Outdated ?

**Comment by PilipinoAko** [comment]
How to pose video bug here to see

**Comment by Emulatorer** [comment]
@PilipinoAko upload it via your youtube channel and post the link here as simple as that :)

**Comment by PilipinoAko** [comment]
https://m.youtube.com/watch?v=lcOwALSLEYk

**Comment by PilipinoAko** [comment]
Here

**Comment by Emulatorer** [comment]
Didn't see a bug in that game after watching 🤔
I think it's normal that the game has audio distortion and lag while pressing the unthrottle 🤷 (imo)

**Comment by Emulatorer** [comment]
@PilipinoAko could you try exporting a GE frame dump?

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

That's the only way how to know the developers about your graphics issue ^^

**Comment by Emulatorer** [comment]
@hrydgard this issue can be close now :/

**Comment by unknownbrackets** [comment]
It's not really clear what the problem is, so I'm going to close as lacking information.  Feel free to use Google Translate and try to provide more detail.

-[Unknown]
