### ISSUE TITLE
Japanese characters don't display properly

### ISSUE THREAD

**Issue by ainzee** [hrydgard/ppsspp#12161]
### What happens?
Japanese characters are displayed as incomprehensible dots. (the game is Neon Genesis Evangelion 2)

### What *should* happen?
The characters should display properly

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
asus pc, windows, ver. 1.8
[ULJS00064_0001.zip](https://github.com/hrydgard/ppsspp/files/3366190/ULJS00064_0001.zip)

**Comment by unknownbrackets** [comment]
This is at least not a bug in this frame's rendering, because a PSP also displays the same:

![PSP result](https://cdn.discordapp.com/attachments/480103153803460614/597564877514604556/playback.expected.png)

It probably means that text was rendered to a temporary buffer (perhaps for scrolling reasons or something?) and then downloaded to RAM, but we missed it.

Just noting here for posterity.

-[Unknown]

**Comment by unknownbrackets** [comment]
I noticed this game uses sceFont.  Are you using PSP fonts, or the ones that come with PPSSPP?

-[Unknown]

**Comment by nassau-tk** [comment]
@ainzee 

You should download [latest PPSSPP](https://www.ppsspp.org/downloads.html).
**PPSSPP v1.10.3-878**or later.
(Scroll down the download page.You can find it!!)

**This screen shot is default setting of PPSSPP v1.10.3-878.**
![ShinseikiEvangelion2_jpn0_font](https://user-images.githubusercontent.com/48179091/95657667-acd71c80-0b50-11eb-8683-be69ac409834.png)

**Comment by nassau-tk** [comment]
@hrydgard 

This issue already solve.
So,this can close.

**Comment by Panderner** [comment]
> @hrydgard
> 
> This issue already solve.
> So,this can close.

But how about the Real PSP font?

**Comment by nassau-tk** [comment]
No, no needs Real PSP font.
Maybe it appear the Japanese text on latest build.
Because, PPSSPP v1.10.3-878 is fixed jpn0.pgf.

Please try it!

**Comment by nassau-tk** [comment]
@hrydgard 

This japanese font issue can close.
Please check it.

**Comment by nassau-tk** [comment]
@hrydgard

You can this font issue close.
Please check it!!
