### ISSUE TITLE
YGO Arc V Tag Force Special Missing Textures?

### ISSUE THREAD

**Issue by Emulatorer** [hrydgard/ppsspp#12172]
### What happens?
As you see in this pictures
![Screenshot_2019-07-14-14-41-05](https://user-images.githubusercontent.com/37603562/61180292-e61b9680-a646-11e9-9b73-0c74b4b60c5b.png)
The rotating rainbow color square is quite missing using ppsspp last build
### What *should* happen?
It should look like this
![Screenshot_2019-07-13-21-19-30](https://user-images.githubusercontent.com/37603562/61180312-06e3ec00-a647-11e9-8972-00c2c8b78278.png)
ppsspp v1.7.1-171 buildbot
### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Android 5.1 Lollipop
Mali-450 GPU
Default Settings
### GE Dump

[NPJH-00142.zip](https://github.com/hrydgard/ppsspp/files/3389539/NPJH-00142.zip)

**Comment by LunaMoo** [comment]
You sure you know how it looks on PSP?

The bottom screenshot looks glitched to me comparing to the top one.

**Comment by Emulatorer** [comment]
Confirmed last work is v1.7.1-171 buildbot issue started in c789c34

**Comment by Emulatorer** [comment]
@LunaMoo seems your right didn't notice that sorry :(
Closing this issue ^^
