### ISSUE TITLE
Discord::Shutdown() is never called in ios 12.2 with ipad air 3? 

### ISSUE THREAD

**Issue by weihu120** [hrydgard/ppsspp#12185]
### What happens?
set a breakpoint at Discord::Shutdown() in xcode , then  luanch ppsspp from xcode 10 to ipad air3 (ios12.2), select Exit menu from main menu of ppsspp, xcode will not stop at Discord::Shutdown() and throw a exception "Assertion failed: (!initialized_), function ~Discord, file /Users/xxx/Documents/ppsspp/UI/DiscordIntegration.cpp, line 42.".
## What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
mac os 10.13.6
xcode 10.0
ipad air3
ios 12.2
ppsspp 1.8.0-433-g37a97e741

**Comment by benderscruffy** [comment]
Please close as this has not been updated in years
