### ISSUE TITLE
Manhunt skip bufered

### ISSUE THREAD

**Issue by PilipinoAko** [hrydgard/ppsspp#12192]
### What happens?
To lags when bufferd rendering

### What *should* happen?
Skip bufferd and not black screen
All rock star games need skip bufferd

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
1.80 build bot

**Comment by Emulatorer** [comment]
Skip buffered is a hack so obviously the game turn blackscreen when set to skip buffered because psp games is designn only in buffered rendering 🤷

**Comment by PilipinoAko** [comment]
(Damn) its FRIDAY MOVIE MEME
I know but bit lags in this game soory

**Comment by Emulatorer** [comment]
@PilipinoAko you can close this issue because your demand will never gonna happen 🤷

All Rockstar games or any other games in psp always blackscreen when set to skipp-buffered rendering ^^

**Comment by PilipinoAko** [comment]
How the GTA VICE STORY HAVE SKIP BUUFERD CHEAT searh for forums b0b0 ko mag
english

On Jul 27, 2019 7:02 PM, "Angielo Burgos" <notifications@github.com> wrote:

@PilipinoAko <https://github.com/PilipinoAko> you can close this issue
because your demand will never gonna happen 🤷

All Rockstar games or any other games in psp always blackscreen when set to
skipp-buffered rendering ^^

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/hrydgard/ppsspp/issues/12192?email_source=notifications&email_token=AMM7BMBYLP3B5H2SA5ZTCBLQBQTOFA5CNFSM4IHAK5ZKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD26JMEY#issuecomment-515675667>,
or mute the thread

**Comment by unknownbrackets** [comment]
Disabling the game's ability to use buffers is always going to cause problems, because on the PSP, games were able to use buffers.  It's just a speedhack.

At most, this issue might be resolved by making it show a warning in this game that you must not use "skip buffer effects".

-[Unknown]

**Comment by PilipinoAko** [comment]
Yeah sorry and thanks for that
