### ISSUE TITLE
Ressitance retribution need analog supported

### ISSUE THREAD

**Issue by PilipinoAko** [hrydgard/ppsspp#12193]
### What happens?
Not supported analog 

### What *should* happen?
When you play with analog its good and easy to play make cheat like assasins creed

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
1.80 build bot

**Comment by Emulatorer** [comment]
There's a cheat in resistance retribution right analog in ppsspp forums I think 🤔

**Comment by PilipinoAko** [comment]
No cheat for that i think we need LUNAMOON

**Comment by Emulatorer** [comment]
Who is Lunamoon? maybe you asking for sir @Lunamoo?

**Comment by PilipinoAko** [comment]
Yesh besh

**Comment by unknownbrackets** [comment]
If the original PSP game didn't support analog, then emulation is correct and there's no issue / bug to fix.  Cheats can be discussed on the forum.

-[Unknown]
