### ISSUE TITLE
A problem with B-Boy when converted from ISO to CSO

### ISSUE THREAD

**Issue by Ahmed0425** [hrydgard/ppsspp#12191]
Recently I'm compressing all my games to save disc space and when I compressed B-Boy game using YACC at CisoPlus Compression level 9, threshold 99, optimized and multithreaded .. the final result was a slightly larger file in size

### What happens?
PPSSPP didn't read the game at all and a "?" mark appeared instead of the game

### What *should* happen?
PPSSPP should be able to read the game

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Windows 10 and PPSSPP v1.8.0
Processor: AMD Ryzen 5 2400G
16GB RAM
Nvidia Geforce GTX 1660

**Comment by LunaMoo** [comment]
Not a PPSSPP issue. Your file was likely corrupted/compression failed, hence it can't be read. Report to YACC whatever it is or try a different tool. Closing.

**Comment by unknownbrackets** [comment]
It might be worth trying [`maxcso`](https://github.com/unknownbrackets/maxcso) to compress it.  maxcso can also recompress an existing CSO and may report better errors - try converting the CSO you got from YACC to a new CSO using it.

You can also check the CRC hash of the original ISO and the generated CSO using maxcso, which will help you confirm if it's corrupted.

-[Unknown]
