### ISSUE TITLE
support for ipega PG-9021

### ISSUE THREAD

**Issue by kpalczewski** [hrydgard/ppsspp#12208]
### What happens?
ipega has unique way to handle press down and release up of a button.
gamepad sends device and key [up] and [down] for UP and then sends different device and key [up] and [down] for DOWN.

### What *should* happen?
gamepad sends device and key UP for UP and DOWN for DOWN

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
last commit: 37a97e7
date build: 19.07.2019
Xcode version: 10.2.1
hardware: iphone 7
iOS: 12.3.1 without jailbreak

Can someone point me to a function that handles keypresses? I would love to try to support this unique gamepad behavior.

**Comment by hrydgard** [comment]
That sounds bizarre, is the behavior documented anywhere?

As for keypress code, the first stage is platform specific, in case of iOS look at ios/ViewController.mm, search for KeyInput. Or in case of Android look at android/src/org/ppsspp/ppsspp/InputDeviceState.java, etc. Then follow the trail into the native code, and figure out where to best apply the fix. Probably the first layer.

**Comment by benderscruffy** [comment]
No feedback/outdated?

**Comment by kpalczewski** [comment]
I don't have this controller any more. I won't be able to test it anymore with ppsspp.
