### ISSUE TITLE
Samurai dou 1 and 2 lag 

### ISSUE THREAD

**Issue by PilipinoAko** [hrydgard/ppsspp#12204]
### What happens?
To lag in SNAP DRAGON 425
ADRENO game is not lot of speed 

### What *should* happen?
High frame rate but the graphics
Is ok no buggs and glich
### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Lates build bot

**Comment by marosis** [comment]
I really dont know if you are joking or not. How old are you? You really dont know how is github working? Please stop sending these uselles posts! Nobody will help you and you dont helping too. If you have lags it is your problem not developers and SD 425 is really slow processor for these days. Just buy new faster phone. Every issue what have you post is uselles! 0% information. No .log, no DUMP. And if you will say: DO THIS EMULATOR FASTER MY PHONE IS SO WEAK..... everybody will here fuck you SO STOP and gtfo or read and learn guide lines.

**Comment by marosis** [comment]
https://github.com/hrydgard/ppsspp/wiki/How-to-report-an-issue-properly
