### ISSUE TITLE
Robot damashii Frame drop

### ISSUE THREAD

**Issue by PilipinoAko** [hrydgard/ppsspp#12207]
### What happens?
Its so slow

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Build bot

**Comment by Emulatorer** [comment]
Here we go again :/

**Comment by marosis** [comment]
XD

**Comment by Emulatorer** [comment]
@PilinoAko No feedback outdated?

**Comment by marosis** [comment]
@Emulatorer this is not real issue. If have somebody slow phone, nobody can help to it.

**Comment by Emulatorer** [comment]
@marosis agree 👍
