### ISSUE TITLE
iBuffalo BSGP1601BK (16-button) controller inputs switched

### ISSUE THREAD

**Issue by polsvoice** [hrydgard/ppsspp#12223]
### What happens?
When I try to set up my controller under Controls > Control Mapping, some of the buttons I press register as other buttons.

[This is the controller I'm using:](https://global.rakuten.com/en/store/mannishboy/item/20011386252/) an iBUFFALO 16-button BSGP1601BK.

For example, here's what I get when I press the following buttons:
13 = Pad1.ThumbR
15 = Pad1.Down
14 = Pad1.Up
16 = Pad1.Left
L1 (9) = Pad1.b9
L2 (7) = Pad1.b5
R1 (10) = Pad1.b10
R2 (8) = Pad1.ThumbL

There's also something weird going on with the analog sticks. Nothing registers unless I press down and make it click, then I get

Left stick (any direction) = Pad1.Back
Right stick (any direction) = Pad1.ThumbL

If I leave the analog controls at their defaults, though, they seem to work fine.

### What *should* happen?
The correct buttons should appear in the configuration.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

CPU: AMD Athlon II X4 635
Renderer: OpenGL
OS: Manjaro Linux 18.0.4
PPSSPP version: 1.8.0-480-g6e78ec9c7

**Comment by unknownbrackets** [comment]
You'll need to use SDL_GameControllerDB to configure the device and add the settings to the gamecontrollerdb file.  Search for those terms here for more information.

-[Unknown]

**Comment by polsvoice** [comment]
There's no entry for it in SDL_GameControllerDB.

**Comment by unknownbrackets** [comment]
See here: https://github.com/gabomdq/SDL_GameControllerDB#mapping-tools

-[Unknown]

**Comment by polsvoice** [comment]
When I run the SDL2 Gamepad Tool, it shows me a BUFFALO BSGP1601 series controller, but it's different from mine. It has 4 buttons on the right-hand side, and mine has six. So, I can only program 4 of them.

**Comment by polsvoice** [comment]
This string seems to work pretty well:

`03000000d81d00000b00000010010000,Buffalo BSGP1601BK,platform:Linux,a:b2,b:b1,x:b3,y:b0,back:b13,start:b15,guide:b12,leftstick:b10,rightstick:b11,leftshoulder:b8,rightshoulder:b9,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b4,righttrigger:b5,`

The schema is pretty simple: the button values are the same as the numbers printed on them *minus 1* (because they're zero-indexed). So, b0 = button 1, b1 = button 2, and so on, up to b15 for button 16. The analog sticks don't have numbers printed on them, but they're b10 for the left stick and b11 for the right stick.

The biggest annoyance is that PPSSPP doesn't know that the button exists if it isn't defined here, and I ran out of labels. That's why there's no b6, b7, or b14. Buttons 7 and 8 would be L2 and R2 if the PSP had an L2 and R2, but I assigned lefttrigger and righttrigger to b4 and b5 so that those buttons were accessible for people who wanted to assign 3-6 for square/triangle/cross/circle instead of 1-4.

**Comment by hrydgard** [comment]
It's not really PPSSPP that defines the meaning of that string, it's SDL. 

If that's the best we can do I'm happy to merge that string, it at least seems to solve some of your problems.

**Comment by benderscruffy** [comment]
No feedback/outdated?

**Comment by hrydgard** [comment]
Looks like I forgot to put that string in, will do.
