### ISSUE TITLE
Change the name of the setting "Immersive Mode"

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#12229]
Few people understand what it is - should we just call it Full Screen?

**Comment by Drasikk** [comment]
Yes!
But that option is for Android very old right?

**Comment by hrydgard** [comment]
No, it's for any device with soft back/home/appswitch buttons on screen - it hides them.

**Comment by unknownbrackets** [comment]
Or perhaps "Auto-hide system menu"?  But I think "Full screen" makes enough sense.

-[Unknown]

**Comment by leopard20** [comment]
Yet another suggestion: "Hide navigation buttons"

**Comment by unknownbrackets** [comment]
"Hide Android navigation buttons"?  I can't really think of any other apps that even make this an option.

-[Unknown]

**Comment by leopard20** [comment]
No, I meant for the name! That's what they're called: "Navigation buttons", not system menu!

**Comment by hrydgard** [comment]
I'm gonna go with Full Screen.

**Comment by Emulatorer** [comment]
Phone with notch still can't get fullscreen 🤷

**Comment by hrydgard** [comment]
Yeah, I know - whenever I tried to enable it I get an ugly white bar on my notched Android phone. I think it's some weird theming issue but it's sooo annoying digging into that stuff....
