### ISSUE TITLE
Dante's inferno-everytime instant crash on one place 

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#12235]
As is written. Im just posting savestate for better operation with this
![Screenshot_2019-08-01-13-01-13](https://user-images.githubusercontent.com/33152267/62879937-80492a00-bd2c-11e9-9982-906142ac1571.png)
![Screenshot_2019-08-12-17-55-56](https://user-images.githubusercontent.com/33152267/62879959-8f2fdc80-bd2c-11e9-88d8-cb078492dd57.png) 

[Dante's inferno ss.zip](https://github.com/hrydgard/ppsspp/files/3493380/Dante.s.inferno.ss.zip)

**Comment by LunaMoo** [comment]
Closing as this is a known problem with pirated copy. Dump the game properly and it will not crash.

**Comment by marosis** [comment]
Understand. Thx for answer

**Comment by marosis** [comment]
@lunamoo pls answer me one more time will it work when will somebody post savestate behind that place?
