### ISSUE TITLE
[Feature Request] Allowing one folder to replace textures in multiple games for multi-region games

### ISSUE THREAD

**Issue by AkiraJkr** [hrydgard/ppsspp#12230]
This could be really useful when a game has multiple regions, and the texture replacement is basically the same between each, and will make it not required to keep multiple copies of the same files. Very helpful for texture modders but not much for users.

To think about it, it could be implemented with the previously introduced feature...creating a neutral folder with a specific name/number to help the emulator identify it's a multi-regional texture pack.

**Comment by unknownbrackets** [comment]
I still recommend what I posted here:

https://github.com/hrydgard/ppsspp/pull/12175#issuecomment-511281886

-[Unknown]

**Comment by AkiraJkr** [comment]
Well, this feature would really only be useful for developers soo...I guess that suggestion is fine, hopefully it helps who finds these issues.
