### ISSUE TITLE
Shield TV (2017) running Android Pie (9): Games crashing immediately.

### ISSUE THREAD

**Issue by bettik** [hrydgard/ppsspp#12249]
### What happens?
Launching any game crashes immediately -- every time.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Shield TV (2017); Shield Experience 8.0; Android Pie (9).

---------------

_Posting new issue for visibility and because the hardware OS updated, but this is likely related to this closed issue_ #11643 

The Shield TV (2017 model) is now updated to "Android Experience 8" which runs Android Pie (9). PPSSPP is crashing when loading any game for me now. I've tried OpenGL and Vulkan. Fresh installs of 1.8.0 from play store as well as latest nightly. I've tried the suggestions regarding ppsspp.ini, as well. All with no change.

Logcat attached: [logcat.txt](https://github.com/hrydgard/ppsspp/files/3511597/logcat.txt)

**Comment by unknownbrackets** [comment]
> [JIT] Comp_RunBlock should never be reached!
> fault addr 0x238371f327

Hm, 0x8371f327 ought to be a valid address.  But, interesting, `gfx_queue_: 0x233ffef750`.  This implies that someone else is using the `0x23########` range.  So I think it's crashing because something else is also using that memory range.

-[Unknown]

**Comment by hrydgard** [comment]
Works for me, but yeah, we should get rid of this hardcoded address for sure.

**Comment by hrydgard** [comment]
#12250 should have fixed this, hopefully.

**Comment by hrydgard** [comment]
@bettik  Can you confirm that the very latest build from https://buildbot.orphis.net/ppsspp/ fixes this for you?

**Comment by bettik** [comment]
@hrydgard Confirmed all games launching fine with latest build!

**Comment by unknownbrackets** [comment]
Great, thanks for confirming.

-[Unknown]
