### ISSUE TITLE
I get an error message when loading a saved game

### ISSUE THREAD

**Issue by Drasikk** [hrydgard/ppsspp#12244]
### What happens?

I make a manufacturing adjustment of my smartphone (something wasn't right). I install an apk that I have on my memory card (ppsspp-v1.8.0-514-g7811b596b-android.apk) So, I uninstall that app and under the latest version available (ppsspp-v1.8.0-517-g61e20d72c-android.apk). I enter the emulator and I get the message of "Failed to load the state: The file is from an earlier version the PPSSPP".

![PPSSPP_2019-08-15-11-15-00](https://user-images.githubusercontent.com/38067925/63087751-38581c00-bf53-11e9-94f6-df79c6fa859d.jpg)

![PPSSPP_2019-08-15-11-15-13](https://user-images.githubusercontent.com/38067925/63087765-4017c080-bf53-11e9-9046-5d2c1df79655.jpg)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Samsung Galaxy Note 8 Oreo 8.0.0 Exynos.
ppsspp-v1.8.0-517-g61e20d72c-android.apk

**Comment by Drasikk** [comment]
I've been able to fix it. I loaded the saved game through the emulator itself (not the saved states) I saved it again on top of that saved game and it's already going well.

**Comment by Drasikk** [comment]
@hrydgard do you know anything about that error?

**Comment by unknownbrackets** [comment]
Generally, this means that the save state was corrupt.  If you can find a way to reproduce creating this save state, it's a bug and that'd be good to know and fix.

That said, since it's associated with a hardware change, it's possible the file actually became corrupted.

-[Unknown]

**Comment by Drasikk** [comment]
Whenever I make a factory setting (custom rom) two or three saved I get that error message.

**Comment by unknownbrackets** [comment]
Any specific settings?

Can you copy the save state onto another device (such as a PC, even if older), change the setting, and copy the save state off again to another folder?  Then try the old save state.

Save states should also be compatible between devices, so even if you try it on a PC, it should load fine there.  What I'm trying to determine is if the save state is changed by the custom rom settings somehow, or if the old file you transferred off still wouldn't work after the change.

-[Unknown]

**Comment by Drasikk** [comment]
Now it's going to be a little complicated, because I've advanced on the history of that game and saved on top of that corrupt save.
