### ISSUE TITLE
Ridge Racer Black Wall Textures

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#12240]
I found a bug where I saw black wall textures in Ridge Racer
![Screenshot_2019-08-13-22-22-48-95_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/62949847-879a3180-be19-11e9-8639-ad2bd50b6c60.png)

I'm using Realme C2 Android 9 Pie and ppsspp-v1.8.0-507-gaea42006d

**Comment by hrydgard** [comment]
Yeah, this seems to have appeared fairly recently. Do you think you can try some old builds to try to pin down when this started to happen?

**Comment by Panderner** [comment]
Yeah I found it in previous builds

**Comment by hrydgard** [comment]
Many versions back? 

Are you using Vulkan or Android?

**Comment by Panderner** [comment]
Opengl

**Comment by Emulatorer** [comment]
@Panderner complete your phone specifications like what's the GPU, CPU and graphics backend like OpenGL or Vulkan and most importantly what version of ppsspp this issue didn't happen 🤷

**Comment by Panderner** [comment]
Problem solved.  I turned on disable slow effects to fix this bug. But Sonic games too bright when you turn on disable slow effects I remembered #6117

**Comment by hrydgard** [comment]
Actually, that's really weird. The walls should be ok even with slow effects not disabled.

**Comment by Panderner** [comment]
False. The bug still happens when the disable slow effects are not turned on

**Comment by Emulatorer** [comment]
@Panderner are you using the USA version of that game if yes could you possibly upload the savestates of that game here so that I can also check the bug 😅

**Comment by Panderner** [comment]
Disable slow effects on:
![Screenshot_2019-08-17-20-26-11-00_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/63211710-a9ebc200-c12d-11e9-8a85-f83dfc4aac9e.png)

Disable slow effects off:
![Screenshot_2019-08-17-20-25-33-62_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/63211714-b4a65700-c12d-11e9-83f3-453a4c93ad74.png)

**Comment by Emulatorer** [comment]
Go to PSP > PPSSPP_STATE > then compressed ULUS10001_1.00_0.ppst and ULUS10001_1.00_0.jpg into zip or rar file

**Comment by Emulatorer** [comment]
@Pandener ???

**Comment by Panderner** [comment]
Here:
[PPSSPP_STATE.zip](https://github.com/hrydgard/ppsspp/files/3512052/PPSSPP_STATE.zip)

**Comment by Emulatorer** [comment]
Looks fine to my phone with Mali 450 GPU using your savestates
![Screenshot_2019-08-17-22-36-45](https://user-images.githubusercontent.com/37603562/63213527-08ba3700-c140-11e9-914c-e78cf8d8b620.png)
![Screenshot_2019-08-17-22-36-53](https://user-images.githubusercontent.com/37603562/63213530-1374cc00-c140-11e9-8ee0-fdce3261e1bd.png)

Hmm... 🤔
Can you check your display settings in ppsspp and see if it's set to auto scaling?
That's the only thing I think that causes that issue in your phone also are you using fullscreen mode of ppsspp?

**Comment by Emulatorer** [comment]
I'm hoping this GE Dump can track the issue
[ULUS10001_0001_GE_Dump.zip](https://github.com/hrydgard/ppsspp/files/3512120/ULUS10001_0001_GE_Dump.zip)

**Comment by Emulatorer** [comment]
Enabling  The "Disable Slower Effects" fixes the graphics glitches in my phone also speed up the game performance ^_^
![Screenshot_2019-08-17-23-27-59](https://user-images.githubusercontent.com/37603562/63214148-1f17c100-c147-11e9-99c0-8c5e85b8b202.png)

**Comment by Panderner** [comment]
Thanks I turned on disable slow effects

**Comment by Emulatorer** [comment]
@Panderner can you check the graphics > display layout editor and see if it's to AUTO SCALING if YES try to change it to PARTIAL STRETCH?
and see if this solve your problem?

**Comment by Panderner** [comment]
@Emulatorer Nothing happens

**Comment by Emulatorer** [comment]
Ok probably @unknowbrackets and @hrydgard can only solve your issue about
that ^^

Sorry I didn't help you :(

**Comment by hrydgard** [comment]
This problem started at the following commit by @unknownbrackets : https://github.com/hrydgard/ppsspp/pull/12158

Here's a GE dump with a repro: 
[UCES00002_0001.zip](https://github.com/hrydgard/ppsspp/files/3531612/UCES00002_0001.zip)

Haven't investigated more yet..

**Comment by hrydgard** [comment]
Closing it as fixed for now after reverting that in d8db8ec, but will reopen when digging into #12272.

**Comment by Panderner** [comment]
Thanks @hrydgard
