### ISSUE TITLE
Fast forward speed adjust?

### ISSUE THREAD

**Issue by PilipinoAko** [hrydgard/ppsspp#12247]
### What happens?
Some emulators have fasT forward adjustment?

### What *should* happen?
Have it?

**Comment by Emulatorer** [comment]
PPSSPP already have that the alternative speed 1 & 2 🤷
![Screenshot_2019-08-16-21-31-34](https://user-images.githubusercontent.com/37603562/63171062-56b23a80-c06d-11e9-89c5-7ff386bdec2a.png)

**Comment by PilipinoAko** [comment]
Ahhhh THATS THE use of alternative speed close this issue

**Comment by hrydgard** [comment]
Though yeah, it's not completely self-explanatory. Not sure what could be done to make it more obvious though.
