### ISSUE TITLE
Reproducable freeze in Riviera

### ISSUE THREAD

**Issue by ShalokShalom** [hrydgard/ppsspp#12255]
### What happens?

Emulator freezes when item/weapon "**Mr Bat**" is used. 
Here, you have a save state: [It will expire in 7 days from now](https://send.firefox.com/download/04c5e45a920159bc/#czHad8k2iT-sPFSqcY6KmQ)

EDIT by hrydgard: Added non-expiring link:
[Send-Archive.zip](https://github.com/hrydgard/ppsspp/files/3513193/Send-Archive.zip)

### What *should* happen?

Not freezing. 

### What hardware, operating system, and PPSSPP version?  

Lenovo L540 
Intel i5 4200M
Intel HD 4600

KaOS Linux
PPSSPP Qt v1.8.0-490-g864336043

**Comment by unknownbrackets** [comment]
Does this reproduce with a regular save (not save state)?  Save states can sometimes save bugs, even from older versions, so a save is better to reproduce issues when possible.

Do you know if this happened with older versions?

-[Unknown]

**Comment by ShalokShalom** [comment]
I would need to play a couple of hours till I can reproduce it based on save states. 
Or is it possible to save a game internally, based on a save state load?

This is my first approach to running this game, so no previous versions tested.

**Comment by unknownbrackets** [comment]
I wonder if this was IO related.  I tried the save state in the latest git build, and am not seeing any crash - on Windows, at least.  I used it until it broke.

Does this still happen?

-[Unknown]

**Comment by ShalokShalom** [comment]
Guess its Linux related then or resolved. Don't have this save state, game or the emulator anymore, hence this is 9 months old.

**Comment by Panderner** [comment]
When I'm using Mr bat item it no longer freezes in latest version
