### ISSUE TITLE
Gundam

### ISSUE THREAD

**Issue by PilipinoAko** [hrydgard/ppsspp#12265]
### What happens?
its literally slow loads in gundam vs gundam i forgot.... on andriod version? 
### What *should* happen?
Fast load when fast load its will have bug
My english is not good'

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
1.80

**Comment by unknownbrackets** [comment]
What device?

-[Unknown]

**Comment by PilipinoAko** [comment]
Open gl only 2gb ram snap425 VIVO Y53

**Comment by unknownbrackets** [comment]
RAM doesn't matter.  That device CPU is 1.4 Ghz.  It is not fast.  The graphics are also slow.

Loading may be affected most by microSD card.  Cheap microSD cards are slow:
https://en.wikipedia.org/wiki/SD_card#Class

If it loads fast on other devices, this is probably not a bug.

-[Unknown]
