### ISSUE TITLE
I close the emulator and when I reopen it, black screen with sound

### ISSUE THREAD

**Issue by Drasikk** [hrydgard/ppsspp#12267]
### What happens?

I'm playing a game, *I turn off the phone in standby mode (pressed the power button) and when I reopen I get the screen black and with the sound of the game itself. Even if a second has passed, the same thing happens. It also happens when you return to the Launcher and I'm back to the ppsspp emulator again.

*I make a save with the quick save option.

It seems that the problem comes from the Vulkan graphics engine. With OPENGL no problem.

### What *should* happen?

I remember this didn't happen before. 🤔

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Samsung Galaxy Note 8 Oreo 8.0.0 Exynos.
ppsspp-v1.8.0-553-g16f4f525e-android.apk

**Comment by Drasikk** [comment]
I tried it with OPENGL and it works well, instead with Vulkan it stays the screen black with sound.

**Comment by unknownbrackets** [comment]
Do older PPSSPP versions work?

-[Unknown]

**Comment by Drasikk** [comment]
I tested with version ppsspp-v1.7.5-571-g1bedb97bc-android.apk and the same thing happens.

**Comment by hrydgard** [comment]
OK, so not a new bug and might be a driver issue. PPSSPP restores fine on all my Vulkan-capable devices last I tried. 

But probably should try to get the Vulkan validation layers going on Android too and see if they have something to complain about...

**Comment by unknownbrackets** [comment]
Have any OS updates come along and changed this issue on your device?  Or has the latest git build improved it?  Would just be nice to confirm if it really is a driver issue.

-[Unknown]

**Comment by Drasikk** [comment]
I didn't even remember this problem anymore, as I've been able to check it's already fixed.
