### ISSUE TITLE
[Android] Screen rotation isn't working while Vulkan is used

### ISSUE THREAD

**Issue by Florin9doi** [hrydgard/ppsspp#12275]
### What happens?
The emulator gets out of screen after the device is rotated (landscape to portrait or portrait to landscape). 

### What *should* happen?
It should work the same way as OpenGL

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
- Galaxy Note9, Android 9, Vulkan
- Pixel 1 , Android 10, Vulkan

**Comment by Florin9doi** [comment]
An additional issue: if `screen rotation` is locked to `landscape reverse` or if `screen rotation` is set to `auto` and ppsspp is started while holding the smartphone with the USB port toward left; then the menus will be empty : https://i.imgur.com/LF43Ypi.png
This issue happens since v1.9.3.77. It is not reproducible on v1.9.3.72.

**Comment by hrydgard** [comment]
Huh, I thought I tested this pretty well a while ago... Back at it I guess

**Comment by hrydgard** [comment]
I don't know, I just can't reproduce. Feels like a GPU driver bug related to image rotation if anything, but none of my Vulkan-capable devices seem to have any problems with rotation anymore.

**Comment by unknownbrackets** [comment]
Hm, not sure if it's useful, but someone reported this a while back:
https://github.com/hrydgard/ppsspp/pull/12419#issuecomment-575955055

-[Unknown]

**Comment by ShaynAshaen** [comment]
#
![20200824_004603](https://user-images.githubusercontent.com/66774393/90989561-4b102280-e5a3-11ea-85b1-13d2ae56c198.gif)
Here's a short video about the issue.

**Comment by Gamemulatorer** [comment]
Yes I can also reproduce this

**Comment by Gamemulatorer** [comment]
Landscape rotation now also doesn't work both opengl and vulkan

**Comment by hrydgard** [comment]
Sorry I don't understand, what do you mean doesn't work? Auto landscape?

**Comment by Gamemulatorer** [comment]
What I mean is if I using the landscape mode it doesn't rotate 270° even my phone auto rotation is unlock or this is normal?

https://user-images.githubusercontent.com/37603562/207860079-2bef33db-2b63-4154-bf15-8e6560450008.mp4

**Comment by hrydgard** [comment]
That's normal, choosing "landscape" is supposed to lock you to landscape. if you want it to change with how you hold the phone, use "auto" or "auto landscape"

**Comment by Gamemulatorer** [comment]
I think this issue can be close now because I cannot reproduce the issue original poster submitted.

**Comment by Gamemulatorer** [comment]
> ![20200824_004603](https://user-images.githubusercontent.com/66774393/90989561-4b102280-e5a3-11ea-85b1-13d2ae56c198.gif) [ ![20200824_004603](https://user-images.githubusercontent.com/66774393/90989561-4b102280-e5a3-11ea-85b1-13d2ae56c198.gif) ](https://user-images.githubusercontent.com/66774393/90989561-4b102280-e5a3-11ea-85b1-13d2ae56c198.gif) [ ](https://user-images.githubusercontent.com/66774393/90989561-4b102280-e5a3-11ea-85b1-13d2ae56c198.gif) Here's a short video about the issue. And for me it happens regardless of which video renderer is used.

I think this issue should belong here https://github.com/hrydgard/ppsspp/issues/11016?
