### ISSUE TITLE
Help me here building this to my android using android studio

### ISSUE THREAD

**Issue by proganime1200** [hrydgard/ppsspp#12274]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':android:generateJsonModelNormalOptimized'.
> Build command failed.
  Error while executing process C:\Users\opera\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HC:\Users\opera\Desktop\ppsspp-master -BC:\Users\opera\Desktop\ppsspp-master\android\.cxx\cmake\normalOptimized\armeabi-v7a -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-16 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\opera\Desktop\ppsspp-master\android\build\intermediates\cmake\normalOptimized\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Release -DANDROID_NDK=C:\Users\opera\AppData\Local\Android\Sdk\ndk\20.0.5594570 -DCMAKE_TOOLCHAIN_FILE=C:\Users\opera\AppData\Local\Android\Sdk\ndk\20.0.5594570\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=C:\Users\opera\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja -DANDROID=true -DANDROID_PLATFORM=android-16 -DANDROID_TOOLCHAIN=clang -DANDROID_CPP_FEATURES= -DANDROID_STL=c++_static -DANDROID_ARM_NEON=TRUE}
  -- Check for working C compiler: C:/Users/opera/AppData/Local/Android/Sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
  -- Check for working C compiler: C:/Users/opera/AppData/Local/Android/Sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: C:/Users/opera/AppData/Local/Android/Sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe
  -- Check for working CXX compiler: C:/Users/opera/AppData/Local/Android/Sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- The ASM compiler identification is Clang
  -- Found assembler: C:/Users/opera/AppData/Local/Android/Sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
  -- Could NOT find SDL2 (missing:  SDL2_LIBRARY SDL2_INCLUDE_DIR SDL2_SDLMAIN_LIBRARY) 
  -- Looking for pthread.h
  -- Looking for pthread.h - found
  -- Looking for pthread_create
  -- Looking for pthread_create - found
  -- Found Threads: TRUE  
  -- Could NOT find Snappy (missing:  SNAPPY_LIBRARIES SNAPPY_INCLUDE_DIR) 
  -- Configuring incomplete, errors occurred!
  See also "C:/Users/opera/Desktop/ppsspp-master/android/.cxx/cmake/normalOptimized/armeabi-v7a/CMakeFiles/CMakeOutput.log".
  
  Clang enabled
  Normal Build
  CMAKE_SYSTEM_PROCESSOR: armv7-a
  Generating for ARMv7, Release
  Generating for ARM, Release
  CMake Error at ext/CMakeLists.txt:3 (add_subdirectory):
    The source directory
  
      C:/Users/opera/Desktop/ppsspp-master/ext/armips
  
    does not contain a CMakeLists.txt file.
  
  
  CMake Error at ext/CMakeLists.txt:16 (add_subdirectory):
    The source directory
  
      C:/Users/opera/Desktop/ppsspp-master/ext/glslang
  
    does not contain a CMakeLists.txt file.
  
  
  CMake Error at cmake/Modules/FindFFmpeg.cmake:147 (list):
    list sub-command REMOVE_DUPLICATES requires list to be present.
  Call Stack (most recent call first):
    CMakeLists.txt:536 (find_package)
  
  
  CMake Error at C:/Users/opera/AppData/Local/Android/Sdk/cmake/3.6.4111459/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
    Could NOT find FFmpeg (missing: FFmpeg_INCLUDE_avcodec
    FFmpeg_LIBRARY_avcodec FFmpeg_INCLUDE_avformat FFmpeg_LIBRARY_avformat
    FFmpeg_INCLUDE_avutil FFmpeg_LIBRARY_avutil FFmpeg_INCLUDE_swresample
    FFmpeg_LIBRARY_swresample FFmpeg_INCLUDE_swscale FFmpeg_LIBRARY_swscale
    avcodec avformat avutil swresample swscale)
  Call Stack (most recent call first):
    C:/Users/opera/AppData/Local/Android/Sdk/cmake/3.6.4111459/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
    cmake/Modules/FindFFmpeg.cmake:154 (find_package_handle_standard_args)
    CMakeLists.txt:536 (find_package)
  
  

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 32s
11 actionable tasks: 1 executed, 10 up-to-date

**Comment by hrydgard** [comment]
You didn't read the instructions, sorry. 

git submodule update --init --recursive

**Comment by proganime1200** [comment]
i read the instruction i type this on terminal it does not work i had sync all from github

**Comment by Hidte09** [comment]
![59548836-24119600-8f87-11e9-836a-2e2cd89cb7b3](https://user-images.githubusercontent.com/124633547/219410447-525bfe28-3ab4-4301-a5b7-da27e0a11bb8.png)
Same problem occurred while building apk: the source directory doesn't contains cmakelists.txt erorr

**Comment by hrydgard** [comment]
@Hidte09 Same old solution:

```bash
git submodule update --init --recursive
```

**Comment by Hidte09** [comment]
When run command "git submodule update --init --recursive" git submodule didn't update anything

**Comment by Hidte09** [comment]
![Screenshot 2023-02-18 152519](https://user-images.githubusercontent.com/124633547/219856932-d2282445-c826-4ade-baf7-eb0f692c39b6.png)
Task :android:configureCMakeDebug[arm64-v8a]
C/C++: Clang enabled
C/C++: Normal Build
C/C++: CMAKE_SYSTEM_PROCESSOR: aarch64
C/C++: Generating for ARMv8, Debug
C/C++: --  Found avcodec: C:/OPTIMIZED PSP PROJECT/ppsspp-1.14.4/ffmpeg/android/arm64/include C:/OPTIMIZED PSP PROJECT/ppsspp-1.14.4/ffmpeg/android/arm64/lib/libavcodec.a
C/C++: --  Found avformat: C:/OPTIMIZED PSP PROJECT/ppsspp-1.14.4/ffmpeg/android/arm64/include C:/OPTIMIZED PSP PROJECT/ppsspp-1.14.4/ffmpeg/android/arm64/lib/libavformat.a
C/C++: --  Found avutil: C:/OPTIMIZED PSP PROJECT/ppsspp-1.14.4/ffmpeg/android/arm64/include C:/OPTIMIZED PSP PROJECT/ppsspp-1.14.4/ffmpeg/android/arm64/lib/libavutil.a
C/C++: --  Found swresample: C:/OPTIMIZED PSP PROJECT/ppsspp-1.14.4/ffmpeg/android/arm64/include C:/OPTIMIZED PSP PROJECT/ppsspp-1.14.4/ffmpeg/android/arm64/lib/libswresample.a
C/C++: --  Found swscale: C:/OPTIMIZED PSP PROJECT/ppsspp-1.14.4/ffmpeg/android/arm64/include C:/OPTIMIZED PSP PROJECT/ppsspp-1.14.4/ffmpeg/android/arm64/lib/libswscale.a
C/C++: CMake Error at ext/zstd/build/cmake/CMakeLists.txt:46 (project):
C/C++:   VERSION ".." format invalid.

> Task :android:configureCMakeDebug[arm64-v8a] FAILED
