### ISSUE TITLE
Un-revert #12158 and fix Ridge Racer (CLUT download issue)

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#12272]
https://github.com/hrydgard/ppsspp/pull/12158 broke Ridge Racer (see https://github.com/hrydgard/ppsspp/issues/12240)  and only fixed the more obscure game Gallery Fake. Reverted it ( d8db8ecfc ) for now, but will restore it later and figure the real issue out.

**Comment by Panderner** [comment]
Yep, ridge racer works fine when disable slow effects are not enabled

**Comment by hrydgard** [comment]
Dealing with this correctly will take some work that won't happen until after the 1.11 release.

**Comment by unknownbrackets** [comment]
I think this has been un-reverted now and I don't think there's a frame dump for the other game (Gallery Fake), but it has its own issue: #8406.

-[Unknown]
