### ISSUE TITLE
Test Drive Unlimited Lag

### ISSUE THREAD

**Issue by HiImBrala** [hrydgard/ppsspp#12283]
### What happens?
The game runs really slow

### What *should* happen?
It should run smoothly

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Direct3d11 backend with intel(hd) graphics device rendering device

**Comment by Panderner** [comment]
It is slow means the CPU are not powerful enough to play all games. God of War And Midnight Club are demanding games. Even a Snapdragon 855 powered phone doesn't run this game full Speed

**Comment by hrydgard** [comment]
That's not the problem with Test Drive Unlimited, the game is doing some very strange framebuffer copies that our texture memory management system doesn't handle well.

There are cheats to avoid this, and there's also already an issue about it, #7347, so I'm closing as duplicate.

**Comment by TAbdiukov** [comment]
Test Drive Unlimited has the undocumented way to change the graphics and performance settings. These settings are poorly configured by default, and one can easily double the game performance. You gonna need "UMDGen".

Go to ```/PSP_GAME/USRDIR/SKINNY/```. ```GAMEPSP.INI```,
* ```OpponentDifficulty		=	1.0			// between 0.0f & 1.0f``` - set to max by default, I suggest lowering
* ```SetTraceSize				=	500 // default is 500``` - most likely the max trails count, lowering should increase performance? Untested
Then ```SYSPSP.INI```
* ```SetSyncToVBL``` - disable VSync, impoves performance dramatically
* ```SetNbVBL		= 2				// Number of VBl min``` - suggest switching to 1 
* ```SetMovie		= ON			// Set MOVIE ON/OFF``` - switch to FALSE to disable playback (the feature unused in-game anyway)

Also I remember that switching to OpenGL or DirectX adds extra +10 fps.

**Comment by HiImBrala** [comment]
You can use cheat that is for your version of game that removes added layers that game reproduces and it will look better.

**Comment by TAbdiukov** [comment]
From  [CWCheat workarounds](https://github.com/LunaMoo/PPSSPP_workarounds),

```
_S ULUS-10249
_G Test Drive Unlimited
_C0 Remove slow and ugly effect
//This patches stuff on boot, aka requires restarting emulation/starting the game with cheat activated
_L 0xE0020406 0x002DC218
_L 0x202DC218 0x00003021
_L 0x202DC21C 0x00000000
_C0 Remove slow and ugly effect [Disable]
_L 0x202DC218 0x3C060406
_L 0x202DC21C 0x34C60002
```

(I would've called it "Remove stupid GBA-like pixelization", can't believe the game can look this good!) Is this what you're talking about? Cheers

**Comment by LunaMoo** [comment]
I don't think those ini files mentioned above are used by the game, they might be in the PC version, however in PSP changes made there will not have any effects, at least the video settings are totally ignored. Maybe it was used during port developement, but the final config seems hardcoded.

**Comment by TAbdiukov** [comment]
> I don't think those ini files mentioned above are used by the game, they might be in the PC version, however in PSP changes made there will not have any effects, at least the video settings are totally ignored. Maybe it was used during port developement, but the final config seems hardcoded.

I'm afraid you're wrong
* ```GAMEPSP.INI``` -> Change ```SetCurGameMode``` from 0 to 1 -> the game starts in the (undocumented) ```GAME_MODE_FREERIDE``` mode
* ```SYSPSP.INI``` -> Change ```SetHeight``` to some high value (say, 600) -> map gets messed up (as if the resolution changed)
