### ISSUE TITLE
Settings menu is invisible 

### ISSUE THREAD

**Issue by oldmario** [hrydgard/ppsspp#12282]
# What happens?
when opening the settings menu i quickly see it shoot up the screen and disappear, the options are still toggleable if i touch where the UI should be displayed, same thing happens on the audio, controls, networking, tools, and system tabs

### What *should* happen?
settings menu should display a UI

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Galaxy Tab A (2019) android 9.0

happens with the v1.8.0-583-gc8730c933 build, last build i had installed on the device was v1.8.0-565-gd8db8ecfc and it displayed perfectly fine

also cleared the data/cache thinking it was probably some setting i had changed in the previous build but it still happens once i start the app up again

**Comment by hrydgard** [comment]
Can you record a video of this?

**Comment by oldmario** [comment]
i think i've figured out how to fix it and how to cause it

on the OS level there's an option to change the navigation bar to either show the traditional 3 buttons (the 3 lines, box, and back button) or an alternative option where you swipe up from the bottom of the screen (kinda new to android 9 and having these onscreen buttons instead of an area of the screen so i don't know if these 3 swipe buttons exist outside of the samsung android version or if they're on all android versions)

if i have it selected to show the 3 buttons and the black bar, the settings appear perfectly fine but as soon as i turn it to the alternative option which is 3 hidden buttons you swipe instead the settings will instantly disappear, i've been unable to get the split second thing of seeing the settings shoot up to happen but atleast i've figured out kinda how to duplicate part of the problem i was having

this was still done in the 583 build as i haven't had much free time today to test the others out yet

**Comment by unknownbrackets** [comment]
I think this might've also been related to the inset / NAN issue possibly?

Does this still happen in recent git builds on either setting?

-[Unknown]

**Comment by oldmario** [comment]
> 
> 
> I think this might've also been related to the inset / NAN issue possibly?
> 
> Does this still happen in recent git builds on either setting?
> 
> -[Unknown]

haven't used my tablet for PPSSPP in a while since i got a better phone but i've just tried it on the same tablet and i don't seem to be getting the problem anymore, tried it on both 1.11.3 (latest googleplay version) and the latest buildbot version v1.11.2-540

**Comment by unknownbrackets** [comment]
Thanks for retesting.

-[Unknown]
