### ISSUE TITLE
iOS: If emulator hangs a reboot of the device is required

### ISSUE THREAD

**Issue by arjanvlek** [hrydgard/ppsspp#12285]
### What happens?
If the emulator crashes, the app cannot be closed in any way. If I reopen it, it will still display the hanged picture. If I force close the app by long pressing power button then home button, SpringBoard crashes and the app is still unusable afterwards (only light blue screen shows). A reboot of the phone is needed to get it working again. 

### What *should* happen?
Crashed / hanged PPSSP should be closable by using the multitasking menu of the phone. 

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Software:

PPSSPP v<TODO after reboot of phone>

Hardware:

iPhone 8 64GB, iOS 12.4, no jailbreak, sideloaded though Cydia impactor with my program-enrolled Apple Developer account (so it works for 365 days)

**Comment by hrydgard** [comment]
This has been reported many, many times and we still don't have a solution.
