### ISSUE TITLE
Default to OpenGL for Android Pie devices that Doesn't support Vulkan

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#12284]
Hi. A recent build defaults to Vulkan. but PowerVR GE8320 powered CPUs (e.g. Mediatek Helio P22, A22 and P35) Does not Support Vulkan. I thought the PowerVR GE8320 supports Vulkan But Drivers are not installed

**Comment by hrydgard** [comment]
If Vulkan is not available, it will fall back to OpenGL. Or at least it should - does it cause problems?

**Comment by Panderner** [comment]
![Screenshot_2019-08-27-16-17-40-73_4ba7ab436e01844e0417980b76613850](https://user-images.githubusercontent.com/37503397/63753896-87ecff00-c8e6-11e9-891b-a3d5510b6f28.png)
This message right here. Also happens for dolphin emulator

**Comment by hrydgard** [comment]
What? I don't think that error message is from PPSSPP. It should just silently switch over to OpenGL.

**Comment by Panderner** [comment]
![Screenshot_2019-08-27-16-16-26-93_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/63766142-1bc9c580-c8fd-11e9-8c5a-7daa73ced3dc.png)
Oops I mean this

**Comment by hrydgard** [comment]
Yes, but that's not a problem. It will still work and use OpenGL. 

I could remove the message, maybe it's too annoying.

**Comment by Panderner** [comment]
There's a problem Right here
![Screenshot_2019-09-03-13-11-39-21_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/64145729-90948680-ce4c-11e9-85a3-874d19ac1535.png)

**Comment by hrydgard** [comment]
Fair enough, that's pretty bad.

**Comment by Panderner** [comment]
Can we revert https://github.com/hrydgard/ppsspp/commit/57c6ab7206aaeda74a0af3fe2ea96edd5d33a247? Because of #12331 you remove pop up message.

**Comment by hrydgard** [comment]
I don't know, I don't really see any purpose of keeping the popup message. In the cases where it was shown, we had no option but to use OpenGL anyway...

**Comment by Panderner** [comment]
When I changing the GraphicsBackend = 3 (VULKAN) using ppsspp.ini for a android device that doesn't support Vulkan it happened.

**Comment by hrydgard** [comment]
I suppose it's kinda useful to know when, but it's still pretty clear that Vulkan is not available since it's not selectable..
