### ISSUE TITLE
[Andoroid][OpenGL][Vulkan] Input isn't accepted. A game can't be begun.[ 絶体絶命都市3 Zettai Zetsumei Toshi 3](ULJS00191)

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#12289]
### What happens?
Input isn't accepted. A game can't be begun.
GameTitle: Japanese : 絶体絶命都市3 -壊れゆく街と彼女の歌-
                 Zettai Zetsumei Toshi 3 - Kowareyuki Machi to Kanojo no Uta-
(ULJS00191)

### What *should* happen?
Load Game......
Step0: System data load.(OK)
Step1: Appear title menu.
Step2: Select "New Game".
Step3: Change to the character select screen.
Step4: Input isn't accepted. A game can't be begun.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

PPSSPP Ver. : 1.8.0-585
OS: Android 9.0
DeviceName: SONY SO-02K / Xperia XZ1 Compact (Japan)
CPU: Snapdragon835 (Octa-core)
GPU: Adreno 540
Resolution: 720×1280
RAM: 4GB
ROM:32GB
ExternalStrage: microSDXC 512GB

and SONY Xperia X Performance Android8.0 & CHUWI Hi9Pro(Android8.0) too.

[Titel screen]
![Screenshot_20190830-145640](https://user-images.githubusercontent.com/48179091/63996447-b8c37300-cb36-11e9-88ae-8fbb1142fdf1.png)

[Select NewGame => became Input isn't accepted]
![Screenshot_20190830-145701](https://user-images.githubusercontent.com/48179091/63996499-d8f33200-cb36-11e9-8010-114cdaed36c6.png)

**Comment by leopard20** [comment]
Search for existing issues before posting. This is a duplicate of https://github.com/hrydgard/ppsspp/issues/4901

You can use the cheat that can be found in the comments.

**Comment by nassau-tk** [comment]
OK.
Yes, I　Know.
But even if the clock of CPU is changed by my environment above-mentioned, I don't move.
In other words, this problem is the case that it isn't improved fundamentally, isn't it?
I also received lead to #12288 4901, so it closes.

Thank you!! @leopard20
