### ISSUE TITLE
[Crash] [Android] [Vulkan] Switch OpenGL to Vulkan Crashes

### ISSUE THREAD

**Issue by urain39** [hrydgard/ppsspp#12287]
### What happens?
Switch OpenGL to Vulkan crashes, device has a white screen and cannot be operated(included system).

### What *should* happen?
Switch OpenGL to Vulkan all should be work

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Device: Redmi Note7 Pro
OS: Android 9.x (MIUI10)
PPSSPP: 1.8.0
GPU: Adreno 612

**Comment by urain39** [comment]
Game: God of War - Ghost of Sparta

**Comment by Emulatorer** [comment]
Try ppsspp latest build 👉 https://buildbot.orphis.net/ppsspp/index.php?m=fulllist
and see if the issue still occurs?

**Comment by urain39** [comment]
@Emulatorer Seems it work, thanks! :)
