### ISSUE TITLE
[Android][OGL] Asphalt: Urban GT 2 Performance Decrease If Multi-Threaded Is Enable

### ISSUE THREAD

**Issue by Emulatorer** [hrydgard/ppsspp#12286]
### What happens?
Asphalt: Urban GT 2 Is Lag When  Multi-Threaded since v1.6 and above where multi-threaded is enable by default

### What *should* happen?
This game is running smooth in v1.4.2 because I can turnoff the multi-threaded

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Tested on the following devices:
•Android 6.0
-Mali-T720 GPU
-MT8361 Quadcore

•Android 5.1
-Mali-450 MP GPU
-MT6592 Octacore

### Screenshots
v1.4.2 MT Is Off
![Screenshot_20190828-190256](https://user-images.githubusercontent.com/37603562/63851910-b394e580-c9c9-11e9-8a63-0ecaecbd9e8b.png)
v1.8.0-585 beta build
![Screenshot_20190828-190522](https://user-images.githubusercontent.com/37603562/63851947-c4ddf200-c9c9-11e9-9817-a3e16226745c.png)
_-*GE Dump*-_
[Asphalt: Urban GT 2 (ULES00719).zip](https://github.com/hrydgard/ppsspp/files/3550598/Asphalt.Urban.GT.2.ULES00719.zip)

**Comment by Panderner** [comment]
What phone are you using @emulatorer

**Comment by Emulatorer** [comment]
@hrydgard any thoughts the cause of lag of this game?

**Comment by hrydgard** [comment]
No, not really. No idea why this would get slower. It's possible readbacks got a little bit slower and that's the reason, but in case the game is doing readback, disabling slower effects and block transfers should greatly boost it - does it?

**Comment by unknownbrackets** [comment]
It's strange that we're detecting 34 as the FPS.  Didn't notice anything obvious in the dump that looks like it should be slow.

-[Unknown]

**Comment by hrydgard** [comment]
Oh, didn't even notice that part. Hm...

**Comment by Emulatorer** [comment]
@hrydgard disable slower effects and block transfer I already did that 🤷
The only way to speed up this game in my phone/tablet is to disable the MT using ppsspp v1.4.2 🤔

**Comment by Emulatorer** [comment]
I think I need to upgrade my phone/tablet so closing this :<

**Comment by HaZe5657** [comment]
Urban GT 2 still runs at 34 fps. Is there a fix for this?

**Comment by hrydgard** [comment]
It seems to be the game's own choice to run at a wacky framerate internally, but I haven't tested on hardware. Does it feel like a smooth 30fps or 60fps on hardware?

**Comment by HaZe5657** [comment]
Sure doesn't feel smooth on 30 fps. It doesn't seem like it's running full
speed, there's no audio hiccups but still. I found this video on YouTube,
they say it's real hardware,
https://youtu.be/glkQ0SrpeBw?feature=shared

**Comment by hrydgard** [comment]
Yeah, I think the game is just really badly coded. It would require some carefully authored game patches (cheat codes) to fix it, nothing the emulator itself can reasonably do.

**Comment by HaZe5657** [comment]
Ah, I see. Uhm, anything you can do regarding the chest codes?

**Comment by HaZe5657** [comment]
Cheat codes*
