### ISSUE TITLE
[Andoroid][OpenGL][Vulkan] Certain Japanese isn't indicated right on the save screen.

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#12288]
### What happens?
Talk of a save screen in the game.
Japanese Character is not appear correctly.
May be only "kanji".
*Of course, I'm using a pure Japanese font of the PSP body.

### What *should* happen?
It's unclear which kanji turns into garbage why.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

PPSSPP Ver. : 1.8.0-585
OS: Android 9.0
DeviceName: SONY SO-02K / Xperia XZ1 Compact (Japan)
CPU: Snapdragon835 (Octa-core)
GPU: Adreno 540
Resolution: 720×1280
RAM: 4GB
ROM:32GB
ExternalStrage: microSDXC 512GB

and SONY Xperia X Performance Android8.0 & CHUWI Hi9Pro(Android8.0) too.

[Smaple Screen Shot]
![Screenshot_20190830-141009](https://user-images.githubusercontent.com/48179091/63995542-d9d69480-cb33-11e9-950c-9f179e1b1c13.png)

![Screenshot_20190830-140944](https://user-images.githubusercontent.com/48179091/63995544-dba05800-cb33-11e9-87cc-eea89b13ceec.png)

![Screenshot_20190830-135740](https://user-images.githubusercontent.com/48179091/63995522-c6c3c480-cb33-11e9-9e4c-0888102bfe6e.png)

**Comment by Panderner** [comment]
Are you using real PSP font?

**Comment by nassau-tk** [comment]
Yes!! Sure.
I got the font frnom my real PSP-2000.
And copy in the PSP>flash0>font folder.

**Comment by hrydgard** [comment]
Yeah, this is a long standing issue. For in-game overlay graphics like this, we're reusing the PSP graphics pipeline, uploading our own (incomplete due to space issues) font into PSP kernel memory and drawing. Unfortunately this text drawing system is very primitive. I've been considering how to make it possible to either use real system fonts or the real PSP fonts here, but it's quite a bit of work. It'll happen eventually.

**Comment by nassau-tk** [comment]
OK!
I understood the reason.
I will wait your updating!!
Thank you!!

**Comment by nassau-tk** [comment]
Please tell me.
Should I close this issue?

**Comment by unknownbrackets** [comment]
Well, this is a problem, but we already have an issue for it: #1904.  I'm going to close this as a duplicate.

-[Unknown]
