### ISSUE TITLE
Log Manager LogType.enabled reset into Default every launch

### ISSUE THREAD

**Issue by adenovan** [hrydgard/ppsspp#12291]
### What happens?
-- Logging Channels options reset into defaults (all enabled) every launch , not loaded properly from config and not save latest enabled options based from Developer Tools Menu Logging Channel menu.

### What *should* happen?
-- Logging Channels enable options should load properly every boot based on dev options choice on what should be enabled and logged into console. its tiring to uncheck and check the Logging Channel options every recompile and launch the program. PPSSPP log is getting bigger hard to read the log when working on specific HLE Module.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
-PPSSPP Version latest
-OS : osx (SDL Build)

**Comment by hrydgard** [comment]
Huh, I think this used to work... I'll have a look soon.

**Comment by unknownbrackets** [comment]
They persist on Windows, at least.  Not sure if this is somehow a macOS specific issue, or related to outdated builds for macOS.

Have you tried the latest git build (which you might have to compile)?

-[Unknown]

**Comment by adenovan** [comment]
i always use the latest upstream commit before working. did not have windows to try but android has same issues if i am not mistaken.

Even if i try to freeze the ini file with read only permission and set the logging channel options to false on every module except SceNetAdhoc its stil replace the configuration with new file.

**Comment by adenovan** [comment]
https://drive.google.com/file/d/1UAIycWY6wPqjQHM6-AgZS4U0Im-_ypXO/view 

video that describe the issues clearly

**Comment by hrydgard** [comment]
Finally got around to reproing this on my Mac. And it does repro. Will look into it.
