### ISSUE TITLE
[Andoroid][OpenGL] Screen is blinked [Minna no Golf Portable (UCJS100001)]

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#12290]
What happens?
Talk of a playing screen in the game.
OpenGL: Play screen blink.
Vulkan: Blink the screen.some time. 

What should happen?
OpenGL: When you shot any time.
Vulkan: When you shot the putter on the green.some time.

What hardware, operating system, and PPSSPP version? On desktop, GPU matters for graphical issues.
PPSSPP Ver. : 1.8.0-585
OS: Android 9.0
DeviceName: SONY SO-02K / Xperia XZ1 Compact (Japan)
CPU: Snapdragon835 (Octa-core)
GPU: Adreno 540
Resolution: 720×1280
RAM: 4GB
ROM:32GB
ExternalStrage: microSDXC 512GB

**Comment by unknownbrackets** [comment]
It sounds like this may be the same as #6655.  Do you know if it happens in both Minna no Golf 1 and Minna no Golf 2?

Could you try exporting a GE frame dump?  These help a lot.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by nassau-tk** [comment]
I can not connect the debugger.
ofcourse,"Allow remote debugger" tunr to enable.

Why????

**Comment by nassau-tk** [comment]
Oh! Sorry. I'm worked on Vulkan.
Change to the OpenGL. No problem.

May be debbugging is finish.
Please, Check it.

[UCJS10001_0001.zip](https://github.com/hrydgard/ppsspp/files/3564028/UCJS10001_0001.zip)

**Comment by unknownbrackets** [comment]
Thanks.  I don't see any block transfers or unusual drawing in that dump - I was expecting it to have more complex drawing that would explain the blink.  Maybe it's actually a timing issue...

-[Unknown]

**Comment by nassau-tk** [comment]
To : unknowncrackets-san

Thank you for your cheking.

I would try capture the playing screen.
If you have interesting and a time.
Please download the file from below URL.
And look the issue.

Thanks!

https://drive.google.com/open?id=1Q1Kqj8DDiMzaK7qwCLrF6TEp8jfTGdSE

**Comment by nassau-tk** [comment]
This isseu will soleved by build of v1.9.3-529-ga95f3111c.

I tested at build of v1.9.3-548-gedbd01807.
It was tested several times, but a problem has not occurred.

So,I am close this issue!!
Thnaks for @unknownbrackets and others!!
