### ISSUE TITLE
Shrek Smash n Crash Racing freeze

### ISSUE THREAD

**Issue by HiImBrala** [hrydgard/ppsspp#12292]
### What happens?
The game automatically freezes after click start and before race.

### What *should* happen?
The game should operate fine.The only way to unfreeze is save where its frozen then load

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Running Direct3D11 with Intel(HD)Graphics device on PPSSPP version 1.8.0 from ppsspp.org

**Comment by Saramagrean** [comment]
Duplicate https://github.com/hrydgard/ppsspp/issues/10139?

**Comment by hrydgard** [comment]
Yeah, this is a dupe. Closing. Please search existing issues before filing new ones.
