### ISSUE TITLE
[Vulkan] PPSSPP crashes when a folder with lots of games is open

### ISSUE THREAD

**Issue by Florin9doi** [hrydgard/ppsspp#12299]
### What happens?
PPSSPP crashes when a folder with lots of games is open (need to have more than a page of games at 2560x1440).
Only reproducible with Vulkan.
I reproduce this crash maximizing the emulator on a display connected via Miracast (2560x1440). I cannot reproduce this on my main monitor (1680x1050).

### What *should* happen?
no crash

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Windows 10, RTX 2060 Super, 1.8.0-HEAD

**Comment by Florin9doi** [comment]
![1](https://user-images.githubusercontent.com/2995486/64126444-714b1a00-cdb6-11e9-969c-3ee218e1f0c6.png)
![2](https://user-images.githubusercontent.com/2995486/64126445-714b1a00-cdb6-11e9-9b78-07f468b314cf.png)

**Comment by hrydgard** [comment]
thanks for the crash dumps, should be fixed now.

**Comment by Florin9doi** [comment]
this was fast!!

**Comment by hrydgard** [comment]
Well, it was a very obvious issue =)
