### ISSUE TITLE
Vulkan: Non-buffered rendering broken by pre-rotation.

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#12303]
Image is rendered in the wrong direction.

See #12296 for screenshot.

**Comment by hrydgard** [comment]
We correctly adjust the draw matrices, but VulkanStateMapping.cpp is missing code to rotate the viewport/scissor rectangles. This results in squishing the image.

**Comment by Drasikk** [comment]
This? 

![PPSSPP_2019-09-03-20-08-53](https://user-images.githubusercontent.com/38067925/64197637-d53d1380-ce86-11e9-9979-e0c2d9d4fd61.jpg)

Skip the buffer effects.

**Comment by hrydgard** [comment]
@Drasikk Yeah, that. I've fixed it now.
