### ISSUE TITLE
[Windows 10] Kenka Banchou: Badass Rumble stops working when accessing moves list

### ISSUE THREAD

**Issue by xqvn** [hrydgard/ppsspp#12312]
Trying to open the "moves" menu (first accessible after getting to the hotel menu fairly early in) causes the game to enter a loop of loading screen messages or crash PPSSPP.

Everything else seems to function totally fine. I had done some googling prior to posting this issue and had seen mention of a "patched" ISO and people implying this is an anti-piracy feature, but searching for it brought no meaningful results.

As said in the title, this happens on Windows 10, using PPSSPP version 1.8.0.

**Comment by LunaMoo** [comment]
It's not an anti-piracy feature, it's pirated iso being incomplete/corrupted. Original properly made copy always had working moves menu. Closing as non issue.
