### ISSUE TITLE
Controller not working on iOS 12.4 with nControl

### ISSUE THREAD

**Issue by Shihira** [hrydgard/ppsspp#12311]
How to reproduce:

1. Get an iOS 12.4 device
2. jailbreak and install nControl_1.2.2-19 and PPSSPP(Dev-Latest)_0v1.6.3-456 from Cydia
3. Connect a Xbox One Controller, which works well with Steam Link
4. Launch PPSSPP, and try to move around with the joystick
5. The controller is not controlling PPSSPP at all, and I am not able to map buttons either

On cydia it says PPSSPP only supports until iOS 11, but it launched and games were running normally. I am just wondering if PPSSPP simply don't support this sort of controller or it is all about system imcompatibility? And is there any plan to adapt this, because it has been officially stated that third party controllers are supported on iOS 13.

**Comment by LunaMoo** [comment]
Just to note - there's really no active developer working with iOS in here so it's not officially supported, probably best thing you can do is try to solve it yourself or google for other people that had that issue and solved it for themselves.

 Also we're almost at version 1.9, the version you're using is VERY old, to get new one you will have to build it yourself ~ https://github.com/hrydgard/ppsspp/wiki/Build-instructions

**Comment by Shihira** [comment]
Thank you. I noticed some information about a 1.8 port when browsing around. Maybe I can get some help there.

**Comment by Shihira** [comment]
Tried with the build instruction written in #11905 and successfully install the v1.8.0 on iOS 12.4, iPad Pro 2nd-Gen

And the controller works very well out of the box. So it turns out that it was the problem of the outdated version provided on the cydia repo. Btw the app cannot launch the second time as #9186 reports. Anyway now that the controller problem has gone I will close this issue.

Thanks again for your great app.

**Comment by hrydgard** [comment]
Pull requests accepted for both syslog and your commenting out of the line :)

**Comment by unknownbrackets** [comment]
Hm, if we remove that line then it means we get the latest connected controller instead of the first?  That's probably better but I guess there's no way to say for sure.  Seems like the best way would be to register all of them (PPSSPP supports multiple controllers.)

We already use different logging macros on Android, I'd imagine the same approach can be used for iOS.

-[Unknown]

**Comment by yaqub2003** [comment]
Hello. I have the same problem in ios 12 at the latest build, but i am using xbox series controller
