### ISSUE TITLE
[Feature request] automatic analog rotation by pressing a key

### ISSUE THREAD

**Issue by none41** [hrydgard/ppsspp#12315]
some games demand you to rotate the analog, which in my case fail all the time on keyboard or be very frustrating whit the touch screen, i'am in gow: ghost of sparta and i can't continue because of this. so as this feature would be very helpful: you press a key and the analog rotate counter/clockwise.

**Comment by leopard20** [comment]
If not this then at least the option to rotate the touch buttons would be really nice.

**Comment by hardBSDk** [comment]
I was wishing for this feature too, like me and others that don't have a dedicated controller.
