### ISSUE TITLE
Wrong post processing shader after multiple selection

### ISSUE THREAD

**Issue by iota97** [hrydgard/ppsspp#12317]
### What happens?
Changing the post processing effect multiple time (4 - 5) result in the applied effect to be a random one of the previous selected effect.

Number of selection before the bug appear seem random from 3 to 6.
Restarting PPSSPP make the correct shader be used for some selection.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Bug seem to be hardware/backend dependant:

I manage to reproduce ONLY on 2 different Redmi 4X (Snapdragon 435, Adreno 505).
Redmi note 7 (Snapdragon 660, Adreno 512) is NOT affected.
Desktop NVIDIA GTX 1060 is NOT affected.

The bug happen ONLY on Vulkan backend.
OpenGL ES backend is NOT affected.

PPSSPP 1.8 from playstore as well as v1.8.0-615-gedcd5e1c7 from automated build are affected.

### What *should* happen?
Post processing effect used should always be the selected one.
The bug seem more a driver one from specific affected hardware and backend (Reuse a old shader/pipeline instead of recompiling it thinking its the same?).
The use case of changing shader multi time is only to preview them to chose one (which can still be done with some restart) so is not a big deal.

**Comment by hrydgard** [comment]
Wacky! Thanks for reporting.

**Comment by unknownbrackets** [comment]
It's possible this is some sort of race condition that is more likely on Android or doesn't happen in Windows code.  But it's also possible this is a driver bug.

It'd really help if people could report whether this happens on other devices or platforms too.

-[Unknown]

**Comment by leopard20** [comment]
My Mi 5s Plus (Snapdragon 821, Android 8.0) isn't affected either.

**Comment by iota97** [comment]
I made some more test, once the bug start manifesting it change shader randomly even if you just open the setting menu without changing any option and go back in game (just opening the pause menu doesn't trigger any change).

If triggered in this way it use shader in a more deterministic way: switching between 2 of the previous one everytime the app return from a pause where the setting menu was open (opening the setting once or multiple time in 1 pause doesn't change the result).

Selecting another shader make the bug more random and i didn't find any pattern.

Exit to menu (return to game selection screen) will not reset the bug as restarting the App does.

I tried capture the frame (not sure how help full it could be in this case), the in PPSSPP GE capture doesn't seem to save the post processing effect, RenderDoc managed to capture some frame, but it gave IO error when I tried to open the saved capture.

I still upload 2 [capture](https://drive.google.com/open?id=1MNiY1gj1zpFJIs19SLlgqPzWmLGonYV_) from RenderDoc as it may open on someone else setup:
Working.rdc is Grayscale and working normally before the bug appear.
NotWorking.rdc is Inverse Color in the menu, but display Grayscale as well.

**Comment by iota97** [comment]
Commenting line 216 to 219 of VulkanUtils.cpp fix the problem.
The method is VkPipeline Vulkan2D::GetPipeline

auto iter = pipelines_.find(key);
if (iter != pipelines_.end()) {
		return iter->second;
}

Performance penality is big of course removing this of course.

**Comment by iota97** [comment]
I confirm indeed that postVs_ and postFs_ are indeed pointer (long long in) and they can have the same value of a previous shader.

I'm not sure if this behaviour is standard compliant or not, anyway way this bug can affect other shader and not only postprocessing one i guess. (might happen more on low end device this less memory?)

I upload some screen with the shader path on file system and the value of postFs_
In the bugged (1st) one it is the same of a previous one (3rd).

![bug](https://user-images.githubusercontent.com/13517524/64911635-c2e39500-d724-11e9-9ac7-c20aa6677e37.png)
![ok0](https://user-images.githubusercontent.com/13517524/64911636-c37c2b80-d724-11e9-84b2-b8550388fbba.png)
![ok1](https://user-images.githubusercontent.com/13517524/64911637-c37c2b80-d724-11e9-9cc4-d52872a71b08.png)
![ok2](https://user-images.githubusercontent.com/13517524/64911638-c37c2b80-d724-11e9-937b-56372184d5ab.png)

**Comment by unknownbrackets** [comment]
Ah, that's probably it.  We're not clearing the cache entries when deleting a shader module.

-[Unknown]

**Comment by unknownbrackets** [comment]
Does #12324 help?

-[Unknown]

**Comment by iota97** [comment]
Yes, PR #12324 fix it!
