### ISSUE TITLE
[libretro][Android][armeabi_v7]make ppsspp so

### ISSUE THREAD

**Issue by N-ever** [hrydgard/ppsspp#12319]
I can not make libretro_ppsspp_android.so by the libretro doc
How can make it ？

**Comment by gouchi** [comment]
@N-ever please close this issue and open one in the [dedicated repository issue tracker](https://github.com/libretro/libretro-super/issues).

Also you may start by reading [this documentation](http://docs.libretro.com/development/retroarch/compilation/android/#building-the-cores).

Thank you.

**Comment by unknownbrackets** [comment]
I'm closing this based on the above comment.  It seems like it is possible based on #12464.

-[Unknown]
