### ISSUE TITLE
Raspberry Pi 4 64 Bit compilation issue

### ISSUE THREAD

**Issue by kaiomatico** [hrydgard/ppsspp#12326]
Hi everyone, it's me again (you maybe remember me from https://github.com/hrydgard/ppsspp/issues/12137 where we successfully fixed the compilation on raspberry pi 4).
Since a few days the raspberry pi 4 supports an official 64 Bit kernel aarch64 (using sudo apt update && sudo apt dist-upgrade && rpi-update. After a reboot add arm_64bit=1 to the /boot/config.txt). Kernel is 64 Bit then, but userland is still 32 Bit.
I then edited the cmake file to the following line: set(ARCH_FLAGS "-march=armv8-a -mfpu=neon-vfpv4 -mfloat-abi=hard")
After that gave me a compilation error at 92% (more on that later) I tried the following line in the cmake file instead: set(ARCH_FLAGS "-march=armv8-a") . Again a compilation error at 92%. For a sanity check I then restored the original file with the following line: set(ARCH_FLAGS "-march=armv7-a -mcpu=cortex-a72 -mtune=cortex-a72 -mfpu=neon-vfpv4 -mfloat-abi=hard")
and again a compilation error at 92%. Here is the error:

`/home/pi/ppsspp/GPU/Common/TextureDecoder.cpp:311:1: error: ‘QuickTexHashFunc’ does not name a type; did you mean ‘QuickTexHashBasic’?
 QuickTexHashFunc DoQuickTexHash = &QuickTexHashBasic;
 ^~~~~~~~~~~~~~~~
 QuickTexHashBasic
/home/pi/ppsspp/GPU/Common/TextureDecoder.cpp:312:1: error: ‘QuickTexHashFunc’ does not name a type; did you mean ‘QuickTexHashBasic’?
 QuickTexHashFunc StableQuickTexHash = &QuickTexHashNonSSE;
 ^~~~~~~~~~~~~~~~
 QuickTexHashBasic
/home/pi/ppsspp/GPU/Common/TextureDecoder.cpp:313:1: error: ‘UnswizzleTex16Func’ does not name a type; did you mean ‘DoUnswizzleTex16Basic’?
 UnswizzleTex16Func DoUnswizzleTex16 = &DoUnswizzleTex16Basic;
 ^~~~~~~~~~~~~~~~~~
 DoUnswizzleTex16Basic
/home/pi/ppsspp/GPU/Common/TextureDecoder.cpp:314:1: error: ‘ReliableHash32Func’ does not name a type; did you mean ‘ReliableHash32NEON’?
 ReliableHash32Func DoReliableHash32 = &XXH32;
 ^~~~~~~~~~~~~~~~~~
 ReliableHash32NEON
/home/pi/ppsspp/GPU/Common/TextureDecoder.cpp:315:1: error: ‘ReliableHash64Func’ does not name a type; did you mean ‘ReliableHashType’?
 ReliableHash64Func DoReliableHash64 = &XXH64;
 ^~~~~~~~~~~~~~~~~~
 ReliableHashType
/home/pi/ppsspp/GPU/Common/TextureDecoder.cpp: In function ‘void SetupTextureDecoder()’:
/home/pi/ppsspp/GPU/Common/TextureDecoder.cpp:322:21: error: assignment of function ‘u32 QuickTexHashNEON(const void*, u32)’
   DoQuickTexHash = &QuickTexHashNEON;
                     ^~~~~~~~~~~~~~~~
/home/pi/ppsspp/GPU/Common/TextureDecoder.cpp:323:25: error: assignment of function ‘u32 QuickTexHashNEON(const void*, u32)’
   StableQuickTexHash = &QuickTexHashNEON;
                         ^~~~~~~~~~~~~~~~
/home/pi/ppsspp/GPU/Common/TextureDecoder.cpp:324:23: error: assignment of function ‘void DoUnswizzleTex16NEON(const u8*, u32*, int, int, u32)’
   DoUnswizzleTex16 = &DoUnswizzleTex16NEON;
                       ^~~~~~~~~~~~~~~~~~~~
/home/pi/ppsspp/GPU/Common/TextureDecoder.cpp:327:23: error: assignment of function ‘u32 ReliableHash32NEON(const void*, size_t, u32)’
   DoReliableHash32 = &ReliableHash32NEON;
                       ^~~~~~~~~~~~~~~~~~
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-deprecated-register’
make[2]: *** [CMakeFiles/Core.dir/build.make:3417: CMakeFiles/Core.dir/GPU/Common/TextureDecoder.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
cc1plus: warning: unrecognized command line option ‘-Wno-deprecated-register’
cc1plus: warning: unrecognized command line option ‘-Wno-deprecated-register’
cc1plus: warning: unrecognized command line option ‘-Wno-deprecated-register’
make[1]: *** [CMakeFiles/Makefile2:493: CMakeFiles/Core.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
`

Maybe this suddenly happens because the rpi-update firmware update added "fkms" to the config.txt file? Could somebody please help? Linpack sees a 20% performance improvement on the Pi 4 32 vs 64 Bit, so I am very interested and it is probably very desirable to have a working 64 Bit build on the latest updated raspbian distro. :+1:

**Comment by unknownbrackets** [comment]
Delete the build folder (or just create a new one) and try building from scratch - it sounds like something is cached or you've got multiple defines conflicting.

64 bit ought to be an improvement though.

-[Unknown]

**Comment by kaiomatico** [comment]
Thank you for the suggestion, I deleted the whole ppsspp folder and cloned it again. I then tried every combination of armv8-a with and without mfpu and mfloat-abi optimizations and with and without the "set(ARMV7_ON)" at the bottom of the cmake file. Between every compilation I deleted and re-cloned the ppsspp folder and did a reboot in between so nothing can be cached. But it is still always the same error as descibed before :(

**Comment by unknownbrackets** [comment]
Ah, I just make the cmake build folder, not all of ppsspp.

You definitely don't want ARMV7_ON, but it's also important it ends up here:
https://github.com/hrydgard/ppsspp/blob/master/CMakeLists.txt#L47

You could try adding those two lines to the raspberry cmake file.  It sounds like right now, it's not using ARM64, but that must mean cmake isn't detecting the cpu as 64 bit...

-[Unknown]

**Comment by kaiomatico** [comment]
Ah thank you :) According to this site:  https://cmake.org/cmake/help/v3.7/variable/CMAKE_SYSTEM_PROCESSOR.html

the variable is the same as CMAKE_HOST_SYSTEM_PROCESSOR, which is retrieved by "uname -p". When I run "uname -p" it just returns "unknown". I really have no knowledge of cmake and thus I have no idea on how to set or mask the variable to aarch64. Should I just write  set(CMAKE_HOST_SYSTEM_PROCESSOR aarch64) at the beginning of CMakeLists.txt or somethin similar? Thank you in advance :)

**Comment by kaiomatico** [comment]
Thank you, I edited the compiler optimizations to: -march=armv8-a -mtune=cortex-a72 -mfpu=neon-vfpv4 -mfloat-abi=hard, I removed ARMV7_ON  and I edited the two lines you just posted at the end of the raspberry cmake file. Sadly it still fails with the same error. I also found out why cmake is not detecting the 64 bit CPU. It is because CMAKE_SYSTEM_PROCESSOR is the same as CMAKE_HOST_SYSTEM_PROCESSOR, which is determined by "uname -p" which just returns "unknown" on the Raspberry Pi. I really don't know anything about cmake, but maybe there is a way to set CMAKE_SYSTEM_PROCESSOR  manually globally? Thank you in advance! If you don't have any more hints I will try to compile it on Manjaro Linux or Gentoo Linux the next few days rather than the official Raspbian, because these two distros support a native 64 bit userland, which is most likely configured correcty for cmake.

**Comment by unknownbrackets** [comment]
Not sure.  Ultimately, that means `__aarch64__` must not be defined.  Maybe it'd be easier to test using gcc directly and see what you can do to make this program compile and run properly:

```c++
#include <cstdio>

int main() {
#ifdef __aarch64__
    printf("Looks good\n");
#else
#error Wrong defines
#endif
    return 0;
}
```

-[Unknown]

**Comment by kaiomatico** [comment]
g++ test.c -o test.o says Wrong defines

**Comment by kaiomatico** [comment]
Sadly i can't configure clang correctly on any other distro. But I think this can be closed now, I'm pretty confident that once raspbian or debian or ubuntu is released as official full 64 bit image it is pretty easy to compile and run ppsspp. Just changing -march=armv8-a+crc -mtune=cortex-a72 -funsafe-math-optimizations and commenting out set(ARMV7_ON) out of the cmake file. Thank you for your help. As soon as these kind of images are released I will let you know on your discord wether I'm successfully in building und arunning ppsspp in these images then ;-)
