### ISSUE TITLE
[Network & Ad-Hoc issue] LCS/VCS Multiplayer, loading-disconnection.

### ISSUE THREAD

**Issue by AliceTS1337** [hrydgard/ppsspp#12329]
### What happens?
I'd start a lobby on Liberty City Stories or Vice City stories, someone would join, I'd start the game, it would load until the end of the loading bar.

(A related but yet different issue: if the clients load to 100% before the host, the host's game will black screen/crash)

LCS: It will instantly disconnect for the host once the bar reaches full
VCS: The game will wait a little while after the bar has reached full, then disconnects.

### What *should* happen?
Both clients and host should have a "wait for host/clients" feature where clients or the host is frozen for a short period to make sure everything is definitely synchronized between clients and host. Check Amultios method of doing this. (LCS is still a bit buggy on their version, but VCS works great. 

For LCS, as the host you need to pause as soon as the loading starts. Once the clients have loaded past the loading of the host, you can continue the host's game and it'll start properly)

### Current tricks to temporarily fix the disconnection issue:

As the host, unthrottle or speedhack once you get  into the loading screen to get ahead of the clients in loading progress. If done correctly, you'll be able to play. However often times this will still fail because you are required to be really precise, especially on LCS as that game lacks a certain player check (or whatever)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Any hardware, any operating system and the latest PPSSPP version (1.8.0)

### Side note
I've spoken to Hrydgård about the issue in the official discord server, however I thought I'd add the issue here anyway as I think this desync problem could be affecting more games other than LCS and VCS due to there's no "wait4players2sync" function.

**Comment by adenovan** [comment]
on current proadhoc code almost all the scenetadhoc module is depend on adhocctl , in amultios adhoc code most of scenetadhoc code is independent its not tied into adhoc control.

Digimon world redigitize can enter the lobby as its not depend on adhocctl first to swap data.

still waiting the logcat for this game to see what function cause the disconnection

**Comment by MojoJojoDojo** [comment]
This game works now with at least up to 3 players (playing online) on the latest PPSSPP dev builds.
The ad-hoc code Rockstar created for this game is really not that good though.
Even on real hardware trying to play this game locally with multiple people would sometimes cause issues (confirmed with someone I know that plays it).
