### ISSUE TITLE
Found out which commit broke Fire TV Stick 4k

### ISSUE THREAD

**Issue by kaiomatico** [hrydgard/ppsspp#12339]
### What happens?
Instead of displaying the menu where to choose ROMS on the Amazon Fire TV Stick 4k Android device, it just briefly displays the splash loading screen, asks for file access permissions and then displays a black screen. When exiting with the back button you can see the menu being rendered for the fraction of a second.

### What *should* happen?
The menu should be displayed to choose and play roms successfully

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Android Fire TV Stick 4k with Fire OS 6.2.6.5
Last working PPSSPP APK Version: v1.7.5-302-g51fec7f43
What must have broke it: either v1.7.5-303-gc8f86def9 (no APK available from buildbot to test) or v1.7.5-304-g015c314fb (APK tested, black screen)

**Comment by hrydgard** [comment]
Wow, that's interesting. 

So this commit: https://github.com/hrydgard/ppsspp/commit/015c314fb18fe002b74a161a75c3e71e296117e8

But seems incredible that a Fire TV Stick could not support such a simple set of requirements (32-bit RGBA, min 16-bit depth and 8 of stencil)? Maybe it's the alpha that trips it up?

We could create an exception - can you check in 1.7.5 what PPSSPP says in Tools/System Information/Name ?

**Comment by kaiomatico** [comment]
Here is a Screenshot. I can make more if additional info is needed
![IMG_20190919_102700186](https://user-images.githubusercontent.com/8037196/65226985-245e8780-dac8-11e9-922f-178bb26837ab.jpg)

**Comment by hrydgard** [comment]
Thanks, that's enough - trying a hacky workaround.

**Comment by kaiomatico** [comment]
I just downloaded ppsspp-v1.8.0-629-gb5af797ca-android.apk and the problem is not fixed... so maybe it was the other commit?

**Comment by hrydgard** [comment]
Oops! my bad. Fixing.

**Comment by hrydgard** [comment]
Fix is in, now just wait for the build.

**Comment by kaiomatico** [comment]
According to this site the build is done: https://travis-ci.org/hrydgard/ppsspp/builds/586964244?utm_source=github_status&utm_medium=notification
But I can only see a Windows 64 Bit build on buildbot. Why is no new APK built? I mean I can wait a few days, I am just wondering :smile:

**Comment by hrydgard** [comment]
The buildbot is separate from the Travis build, that might be the confusion you had :)

**Comment by kaiomatico** [comment]
Wow this build is working great! With simulate block transfer effects I can play Burnout with 2x on full speed without frameskip :) Thank you, the fix is working :)

**Comment by hrydgard** [comment]
Great!
