### ISSUE TITLE
[Feature Request]Add "Open TEXTURES folder" to File

### ISSUE THREAD

**Issue by AkiraJkr** [hrydgard/ppsspp#12356]
Title. Would be quite handy for texture modders, and on the cases some people(somehow) don't know how to install a texture pack, or wanna do it themselves.

![image](https://user-images.githubusercontent.com/27028529/65739020-4d7bab00-e0ba-11e9-88be-a3ca0350f60f.png)

**Comment by unknownbrackets** [comment]
IMHO, this is too specific.  If we have a TEXTURES shortcut, obviously we need a SAVEDATA one.  And probably SCREENSHOT.  Surely, SYSTEM as well, maybe even CACHE.  Definitely VIDEO, MUSIC, and DUMP.  Then we need PPSSPP_STATE, of course.  GAME goes without saying.  In case they exist, also Cheats and flash0.

Once we're done with that, PPSSPP's menu should look similar to this:

![Many UI options in a window.](https://news.softpedia.com/images/extra/WINDOWS/large/Bulk%20Rename%20Utility_09large.png)

But really, I think that's overdoing it.  Most people will probably install a texture pack via zip, and it's only a couple clicks after Open Memory Stick...

-[Unknown]

**Comment by hrydgard** [comment]
Agreed, want to keep the file menu short.

There may be other interface improvements possible around texture packs though, but I'm closing this.
