### ISSUE TITLE
"この部室は帰宅しない部が占拠しましたsummer wars" crash on start

### ISSUE THREAD

**Issue by azuse** [hrydgard/ppsspp#12359]
### What happens?
PPSSPP(1.92) crashed on loading the game.
I take the screenshot of debug console before it crash.
![](https://gitlab.com/azuse/pkbkbss_summer-wars_1.0_cn/raw/master/1.9.jpg)

I uploaded the game iso file, maybe it will be helpful.
-removed link to warez-

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Tried on PPSSPP 1.92 1.9 1.3 1.01
Operating system is windows 10 1903
Hardware: i7-8086k 16g ram RTX2060

**Comment by LunaMoo** [comment]
Looks like another fan translated -in a weird way- game.

**Comment by hrydgard** [comment]
The log is actually helpful here - sysclib_strcmp and friends are lacking any kind of safety check. Can't hurt to add them, so I will - but no guarantees the game will proceed beyond this anyway as presumably an argument is bad...

**Comment by unknownbrackets** [comment]
Root cause here is probably that we don't implement the kernel-only function sceKernelFindModuleByUID (which I think is usually used to patch functions we HLE.)  We also don't implement sceMesgLed at all (a kernel-only module.)

-[Unknown]

**Comment by azuse** [comment]
> The log is actually helpful here - sysclib_strcmp and friends are lacking any kind of safety check. Can't hurt to add them, so I will - but no guarantees the game will proceed beyond this anyway as presumably an argument is bad...

The game successfully loaded now, thanks very much for the help.

**Comment by unknownbrackets** [comment]
Oh, great.  Thanks for reporting.

-[Unknown]
