### ISSUE TITLE
FR: autoscale (or manual) game icon sizes

### ISSUE THREAD

**Issue by eddiegalvez** [hrydgard/ppsspp#12353]
### What happens?

I start PPSSPP, and on my GPD XD+ the two little games I have... I have these tiny rectangles!

### What *should* happen?

Give me:
"Fit to screen" - scale the icons smartly to use the space (with just two games I don't expect each game to be 50% of my screen but let's have bigger icons!)
"Icon size" options (could even just be relative, like "X-Small, Small, Medium, Large, Huge"...

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
I'm on a GPD XD+ aka Android version

**Comment by hrydgard** [comment]
Can you show a screenshot of what it looks like for you now?

The icons are pretty low resolution, so making them big will make them look worse.

**Comment by eddiegalvez** [comment]
https://imgur.com/a/IUObkVG

**Comment by eddiegalvez** [comment]
If resolution forces the images to only be sized at a certain res, I might suggest:
 let the user decide if they are ok with 1x or 2x (hey, 2x might still look okay?)
 and if necessary just "fill" a rectangle

Ideally yes the icons are large crisp images as you have them today, but somewhat more importantly... its a larger tap target (and visually so I don't squint as much).
Oh and label (since if you do not res the image larger, then I'd still squint... but if the title showed in scalable font...)

**Comment by hrydgard** [comment]
Right, yeah, I agree that the layout looks very unbalanced with such small icons, and yeah, a bit bigger will indeed work.

**Comment by eddiegalvez** [comment]
Maybe use the boxarts from https://github.com/libretro/libretro-thumbnails/tree/master/Sony%20-%20PlayStation%20Portable for "large" ? (options: use <whatever you guys have>; use boxarts, etc?)

**Comment by hrydgard** [comment]
Well, that's a very incomplete collection and the images are a bit heavy. Would need to jpeg them and host them ourselves, and it just becomes a whole ordeal... the icons are nice because they are included with the games themselves.

Maybe one day.

**Comment by LunaMoo** [comment]
We could just support custom icons like we already do for games(homebrew mostly) that has no icon. But I think that was already requested at some point.

**Comment by DavidTamas** [comment]
In case the enlarged game boxes are gonna get filled instead of scaling the game icons with them, can we get some ROM specific information (such as title & serial) displayed under the icon? Since I have multiple versions of the same game I kinda need to right click on every version to find the one I want to launch, so the UMD serial would help identifying the correct version much faster. 
![Multiple game versions](https://user-images.githubusercontent.com/22328803/65724422-a47c8280-e0b0-11e9-9a10-e4539cdd9391.png)

**Comment by unknownbrackets** [comment]
It seems like #12646 pretty much implemented this, except any "autoscaling".

Perhaps we'd set the initial size based on DPI?

-[Unknown]

**Comment by hrydgard** [comment]
I think resizable game icons is close enough to this - closing.
