### ISSUE TITLE
Can't download ppsspp v1.9.2 in ppsspp buildbot

### ISSUE THREAD

**Issue by Emulatorer** [hrydgard/ppsspp#12357]
![Screenshot_20190927-132510](https://user-images.githubusercontent.com/37603562/65744530-32954f00-e12b-11e9-8d51-959be69979f0.png)
![Screenshot_20190927-132536](https://user-images.githubusercontent.com/37603562/65744541-39bc5d00-e12b-11e9-8b40-8ab830ab66c0.png)

I know this is not a big issue and I want it to report via discord but IDK what's Sir @hrydgard  discord # 😅

**Comment by unknownbrackets** [comment]
Strange.  Forcing a rebuild didn't help, but it fixed the Windows 32-bit build.

It'll probably work again upon the next commit.  There's no real difference from the previous build in this case.

-[Unknown]

**Comment by Emulatorer** [comment]
Ok so I will just wait for the next commit ^^
