### ISSUE TITLE
Feature request: snapping options for on-screen touch controls

### ISSUE THREAD

**Issue by fefo-dev** [hrydgard/ppsspp#12361]
Please add a snap-to-grid option when editing on-screen buttons, Also add snap steps or expose the values, or both, to the resize/spacing option to make editing a proportional controller easier.

It's a cosmetic feature, but it's something sorely needed for me.

Thanks a lot.

**Comment by hrydgard** [comment]
That's a good idea, thanks for writing it up.

**Comment by DavidTamas** [comment]
I believe PR #12517 closes this. It would be a nice addition to have the grid displayed though. Should I open a separate issue for that?

**Comment by hrydgard** [comment]
Yeah.
