### ISSUE TITLE
Mega Drops 2 crashes when you play any mode

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#12368]
Mega drops 2 is a Homebrew game and it included on PPSSPP Homebrew store.

The game crashes when selecting any mode after chosing play and bonus

**Comment by hrydgard** [comment]
huh! Will have to look at that.

**Comment by unknownbrackets** [comment]
Supposedly there was a problem at some point with zip extraction... I wonder if recent changes regressed it?

https://forums.ppsspp.org/showthread.php?tid=17911

-[Unknown]

**Comment by Panderner** [comment]
interpreter works but dynarec and ir interpreter crashes

**Comment by hrydgard** [comment]
Yeah, it works if you simply disable System/Fast Memory.

Something is fooling the game into trying to read from the invalid addresses 0x00000000 and 0x00000004. 

The only suspicious thing in the log output is:
```
18:38:641 user_main    W[ME]: hle\sceaudiocodec.cpp:133 UNIMPL sceAudiocodecCheckNeedMem(08b43000, 4098 (MP3))
18:38:641 user_main    W[ME]: hle\sceaudiocodec.cpp:138 UNIMPL sceAudiocodecGetEDRAM(08b43000, 4098 (MP3))
```

I wonder if this has worked in past versions...

**Comment by Panderner** [comment]
I turned off fast memory but the game won't start

**Comment by hrydgard** [comment]
Hm, worked on Windows..

**Comment by Panderner** [comment]
It doesn't work on android

**Comment by Emulatorer** [comment]
It's working fine when fast memory is off
Sir @hrydgard is correct this game only crashing when fast memory is on.

Im using android 6.0.1 LOS13 Custom ROM

**Comment by Panderner** [comment]
I turned off fast memory but it won't reach in game

**Comment by Emulatorer** [comment]
What phone are you using? Can you upload a video of what happening 🤔

**Comment by Panderner** [comment]
I'm using realme C2

**Comment by Panderner** [comment]
changing to interpreter to dynarec in-game when I turned off fast memory it displays crash message to game not emulator crash
![Screenshot_2019-10-21-11-21-52-78_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/67208915-fc58a000-f448-11e9-9d21-e21d7072cac7.png)

**Comment by Panderner** [comment]
Changing interpreter to dynarec when fast memory is off will result fatal error message

**Comment by Panderner** [comment]
I turned off fast memory I used GE dump it happens
,,,
33:11:827 user_main    E[SCEMODULE]: HLE/sceKernelModule.cpp:2217 UNIMPL sceKernelSelfStopUnloadModule(00000001, 00000000, 00000000): game has likely crashed
,,,

**Comment by unknownbrackets** [comment]
Implementing sceKernelSelfStopUnloadModule probably won't help.  That's like giving a person in prison for life something to harm themselves with.  If you want them to live and be free, it's not really solving the problem.  Gotta get them released instead.

Something must be going wrong that makes it call that function.  But I'm not sure why the behavior is different for different people.

-[Unknown]

**Comment by Panderner** [comment]
Switching interpreter to dynarec or ir interpreter in-game when the fast memory is off:
```
24:02:288 user_main    E[SCEKERNEL]: HLE/sceKernelThread.cpp:2656 sceKernelWaitThreadEnd - bad thread -1
```

**Comment by Panderner** [comment]
I don't think it's a jit bug
