### ISSUE TITLE
Unable to save bug related to hosting

### ISSUE THREAD

**Issue by DarkD** [hrydgard/ppsspp#12367]
Guys, guess I accidentally found exact reason behind save bug, that plagued PPSSPP since forever.
Checked for lots of times and bugged every time with Kidou Senshi Gundam AGE - Cosmic Drive. Same goes for Danball Senki Boost and probably everywhere, needs testing.

What exactly happens?
Save dialog doesn't appear and you just stuck without able to choose save slot or go back.

So when it happens?
When you try to host battle and  there's no one it returns to menu as if nothing happened, but it did, it broke saving.

Step-by-step guide to bug in Gundam AGE game:
1. Play game for some time till you gain access to mechas.
2. Save game (last string of triangle menu).
3. Restart game.
4. Choose 3rd option in main menu and create any character there.
5. From first string of menu go to next menu and again choose 1st one.
6. Choose any mission and start it.
7. You'll end up in second menu, choosing last string of it(save option) will give the bug.

This one happened in different games(mostly Japanese, when I just tried menus I don't knew meaning of) for me for a long time when I by accident triggered it not knowing that I triggered it, played for [;enty of time only to find out I can't save and stuck.
And to make testing more clear - first 1.9.2 with default settings(WLAN off). Maybe there're easier cases where to check the issue...

**Comment by unknownbrackets** [comment]
Does this still happen in the latest git builds?  There were some changes related to the network dialogs that may have fixed this.

-[Unknown]

**Comment by DarkD** [comment]
Yeah, still there. Just grabbed v1.9.3-513-g25197451e to test it.

**Comment by benderscruffy** [comment]
is this still an issue ??

**Comment by DarkD** [comment]
Can't check on latest build right now, there's save incompatibility and I don't want to throw away my saves. I'll fill issue if there isn't about that.

**Comment by unknownbrackets** [comment]
Just a note for posterity, that's referencing #15970.

-[Unknown]

**Comment by DarkD** [comment]
Now I can confirm this one is finally gone too!
