### ISSUE TITLE
[android] Square, X, triangle, and circle buttons not registering

### ISSUE THREAD

**Issue by chowder908** [hrydgard/ppsspp#12375]
Since the recent update the action buttons just don't seem to want to work. I tried moving them to a different part of the screen but taps seem to only register when they want to. Was working fine before so thought I'd report as a possible bug.

**Comment by hrydgard** [comment]
Does it seem to be like an offset, where you consistently have to push to the left or right of them, or something?

**Comment by hrydgard** [comment]
@chowder908  It would also be very helpful if you could say what device you are using, and if you are using the fullscreen option.

**Comment by chowder908** [comment]
Yeah it does seem off like I have to move my finger around a little bit over the action buttons to get it to register. 
Also, yes I'm using fullscreen. I'm about to get a new phone tomorrow if it's the phone I'm using I'll update let you

**Comment by hrydgard** [comment]
You could still tell us what model your current phone is :)

**Comment by unknownbrackets** [comment]
It sounds like this is probably just the same as #12381.

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, most certainly.
