### ISSUE TITLE
Who is maintaining the build bot for iOS?

### ISSUE THREAD

**Issue by Halo-Michael** [hrydgard/ppsspp#12384]
### What happens?

Who is maintaining the build bot for iOS?  I met a person who claimed to be the maintainer of PPSSPP iOS build bot. He promoted the compiled ipa version of PPSSPP in a forum in China (Baidu Post Bar), but the things he compiled were inferior, so I want to confirm.

Here is the link:
https://tieba.baidu.com/p/6283888802?

Here is the ipa which he built:
https://pan.baidu.com/s/1xNQx08FpY1s2CqJtyP1h0g#/
the password is
uc1k

**Comment by hrydgard** [comment]
Currently nobody official.

**Comment by W-MS** [comment]
Whoa, great to see you there. @Halo-Michael 
I'm working on the new buildbot for ios and thank you for your advice from tieba.

Here is the web archive from 2013. I'm not official and only declares I was a maintainer of ios build. http://web.archive.org/web/20131221130232/http://www.ppsspp.org/downloads.html

I appreciate your help and will open-source the buildbot once it runs.

**Comment by Halo-Michael** [comment]
> Whoa, great to see you there. @Halo-Michael
> I'm working on the new buildbot for ios and thank you for your advice from tieba.
> 
> Here is the web archive from 2013. I'm not official and only declares I was a maintainer of ios build. http://web.archive.org/web/20131221130232/http://www.ppsspp.org/downloads.html
> 
> I appreciate your help and will open-source the buildbot once it runs.

https://github.com/Halo-Michael/ppsspp-builder
I hope this helps.

**Comment by unknownbrackets** [comment]
This isn't really an issue, so I'm going to close.  Feel free to continue the discussion here.

-[Unknown]

**Comment by Halo-Michael** [comment]
Do not close it

**Comment by Halo-Michael** [comment]
Now this person said that the version he compiled will be available on the official website (ppsspp.org) within two days, and he is now highly recommending that you download the version he compiled.  I want to know if this is true?  To be honest, if this is true, I can hardly agree that the files he compiled can be downloaded to the user as "official files.".

**Comment by hrydgard** [comment]
Well, W.MS used to make a few iOS build that we called official in the past, so it's not that strange. Still they will be marked as unsupported.
