### ISSUE TITLE
Raspberry Pi 4 is no longer correctly starting

### ISSUE THREAD

**Issue by kaiomatico** [hrydgard/ppsspp#12388]
### What happens?

PPSSPPSDL crashes and does not display the menu. It seems like the old issue of SDL not using the default display all over again on the Pi 4 maybe?

`pi@raspberrypi:~/ppsspp $ ./PPSSPPSDL 
I: VulkanLoader.cpp:264: VulkanMayBeAvailable: Device allowed ('SDL:Linux')
I: VulkanLoader.cpp:271: VulkanMayBeAvailable: Library loaded ('libvulkan.so')
I: VulkanLoader.cpp:322: VulkanMayBeAvailable: Enumerating instance extensions
I: VulkanLoader.cpp:333: VulkanMayBeAvailable: Instance extension count: 2
I: VulkanLoader.cpp:341: VulkanMaybeAvailable: Instance extension found: VK_EXT_debug_report (00000009)
I: VulkanLoader.cpp:341: VulkanMaybeAvailable: Instance extension found: VK_EXT_debug_utils (00000001)
E: VulkanLoader.cpp:359: Surface extension not found
DEBUG: Vulkan is not available, not using Vulkan.
I: Config.cpp:517: Longest display side: -1 pixels. Choosing scale 1
20:25:244 Core/Config.cpp:1558 E[LOADER]: Failed to read /home/pi/.config/ppsspp/PSP/SYSTEM/controls.ini. Setting controller config to default.
20:25:249 Core/Config.cpp:1227 E[LOADER]: Error saving config - can't read ini '/home/pi/.config/ppsspp/PSP/SYSTEM/ppsspp.ini'
20:25:257 Core/Config.cpp:1272 I[LOADER]: Config saved (got storage permission): '/home/pi/.config/ppsspp/PSP/SYSTEM/ppsspp.ini'
20:25:257 Core/Config.cpp:1278 E[LOADER]: Error saving config - can't read ini '/home/pi/.config/ppsspp/PSP/SYSTEM/controls.ini'
20:25:258 Core/Config.cpp:1285 I[LOADER]: Controller config saved: /home/pi/.config/ppsspp/PSP/SYSTEM/controls.ini
Pixels: 960 x 544
Virtual pixels: 960 x 544
* failed to add service - already in use?
`

### What *should* happen?

PPSSPPSDL should start normally showin the menu window with the game selection using the SDL / OpenGL backend as how it was up until very recently ( ~1 month since I last tried)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Raspberry Pi 4, latest raspbian (debian buster armhf based) with latest updates and firmware, latest git PPSSPP version pulled and compiled from git today

**Comment by unknownbrackets** [comment]
See here:
https://github.com/hrydgard/ppsspp/issues/12137#issuecomment-508291899

Are you USING_FBDEV or not?  Are you starting within X or not?

The only recent change to SDL was 18edfefa0a78aed9feb27f390dd8177bf9d73f54.  You could try reverting it.

-[Unknown]

**Comment by kaiomatico** [comment]
I am using the ppsspp provided cmake file which auto detects the pi 4 model and then is not using_fbdev. I am running it within X. I also tried running not within X, then a red text appears 
Failed graphics backends: OPENGL,ALL,ALL
Grapgics backend failed for 0, trying another
All graphics backends failed

Thank you, I will try reverting to the recent SDL change

**Comment by kaiomatico** [comment]
Mh I checked out https://github.com/hrydgard/ppsspp/commit/5a4a96893e6cbd229a5a1c7ac9fc49b3acbf5a3c so the codebase is before the recent SDL change, but I get this slighty different error message now (4 times an "ALL" backend)

pi@raspberrypi:~/ppsspp $ ./PPSSPPSDL 
I: VulkanLoader.cpp:264: VulkanMayBeAvailable: Device allowed ('SDL:Linux')
I: VulkanLoader.cpp:271: VulkanMayBeAvailable: Library loaded ('libvulkan.so')
I: VulkanLoader.cpp:322: VulkanMayBeAvailable: Enumerating instance extensions
I: VulkanLoader.cpp:333: VulkanMayBeAvailable: Instance extension count: 2
I: VulkanLoader.cpp:341: VulkanMaybeAvailable: Instance extension found: VK_EXT_debug_report (00000009)
I: VulkanLoader.cpp:341: VulkanMaybeAvailable: Instance extension found: VK_EXT_debug_utils (00000001)
E: VulkanLoader.cpp:359: Surface extension not found
DEBUG: Vulkan is not available, not using Vulkan.
I: Config.cpp:517: Longest display side: -1 pixels. Choosing scale 1
59:58:650 Core/Config.cpp:1187 I[LOADER]: Loading controller config: /home/pi/.config/ppsspp/PSP/SYSTEM/controls.ini
59:58:654 UI/NativeApp.cpp:387 E[LOADER]: Failed graphics backends: OPENGL,ALL,ALL,ALL,ALL,ALL
59:58:654 Core/Config.cpp:599 E[LOADER]: Graphics backend failed for 0, trying another
59:58:654 Core/Config.cpp:624 E[LOADER]: All graphics backends failed
59:58:663 Core/Config.cpp:1272 I[LOADER]: Config saved (got storage permission): '/home/pi/.config/ppsspp/PSP/SYSTEM/ppsspp.ini'
59:58:664 Core/Config.cpp:1285 I[LOADER]: Controller config saved: /home/pi/.config/ppsspp/PSP/SYSTEM/controls.ini
Pixels: 960 x 544
Virtual pixels: 960 x 544
* failed to add service - already in use?
 

By the way: Is a make install needed or is make sufficient? because I now also added make install, but when compiling the master I just ran make and not make install, sorry if this is the mistake

**Comment by hrydgard** [comment]
It says right here that it's not using Vulkan:
```DEBUG: Vulkan is not available, not using Vulkan.```

Is there no log after Virtual Pixels? "Failed to add service", is that part of the log?

**Comment by kaiomatico** [comment]
Yes I'm sorry I misread the Vulkan message (so I edited the thread title). After "Virtual pixels" there comes "Failed to add service" which is part of the log. After that no further logging appears and I get back to the shell prompt (so the program exited). I can see a window border with no content popping up for the fraction of a second before I get returned to the shell.

**Comment by unknownbrackets** [comment]
Failed to add service is something that is logged by Raspberry Pi drivers or something.

Maybe try fresh settings just in case:
```sh
mv /home/pi/.config/ppsspp /home/pi/.config/ppsspp~
```

And also make sure USING_FBDEV is not enabled.  Maybe even use `make clean` and do a full rebuild after checking that it's off.

Do you remember the last sha that did work?  If you go back to it, does it work again?

-[Unknown]

**Comment by kaiomatico** [comment]
I reverted back to #edcd5e1 which was known working but it does not work now. I guess the latest raspberry pi drivers are broken, so no issue of PPSSPP itself. Feel free to close this now, it will probably fix itself :)

**Comment by hrydgard** [comment]
Well, you should probably create a bug report upstream then! Thanks for testing.
