### ISSUE TITLE
[ANDROID] Star ocean First Departure Sprite Overlapping 

### ISSUE THREAD

**Issue by Xenon68** [hrydgard/ppsspp#12385]
![Screenshot_20191005-153811_PPSSPP Gold](https://user-images.githubusercontent.com/56187228/66251774-47ef2680-e786-11e9-9e13-825a546e64fc.jpg)
Speed is perfect, no flickering, the only problem is the sprite overlap.

I'm using OpenGL on Samsung Galaxy J4+ and the latest version of PPSSPP
Buffered Rendering
Auto Frameskip

**Comment by Emulatorer** [comment]
Similar https://github.com/hrydgard/ppsspp/issues/10634#issuecomment-367203930

**Comment by hrydgard** [comment]
This works on all modern phones with working drivers. Not sure there's much we can do here...

**Comment by Xenon68** [comment]
Oh well, I guess I'll play the second evolution instead. Thanks for the info!
