### ISSUE TITLE
Remote Disc Streaming (v 1.9.3)

### ISSUE THREAD

**Issue by HiImBrala** [hrydgard/ppsspp#12399]
Hi its me again with Remote Disc Streaming issue.I have problem with remote disc streaming.PC wont show on browsing even with port.Running version 1.9.3 on android and PC.I already tried 192.168.1.x:48700 on chrome on PC.On PC it loads the page but on android it does not load the page.Firewall is not blocking it because it worked on myneighborsushicat.com.Also i tried LAN cross platform game and it worked well.Is there any ideas why it is happening?

**Comment by unknownbrackets** [comment]
If you've defined the network you connected to as "Public" on the PC, you may need to grant additional privileges to PPSSPP in your firewall.

Try going to Start -> type Windows Firewall and press enter.  Next, click "Advanced settings" on the left.  You should see a new window pop up with "Inbound Rules" and "Outbound Rules" on the left, but I'm not 100% sure if this is Windows 10 Pro only.

Assuming it came up, click Inbound Rules on the left.  Then click inside the list on the right and type "PPSSPP".  This should select one of the PPSSPP rules (there may be multiple.)

Double click each "PPSSPP" rule, and in the properties make sure:
 * Action is set to "Allow the connection" on the General tab.
 * "Private" and "Public" are both selected in the Advanced tab.  It's fine if you check "Domain" too.

That said, I don't recommend using remote disc streaming on public networks like universities, libraries, restaurants, etc.

If the above doesn't help, double check that both your PC and phone have IP addresses in the same "subnet".  That means, they both need to start with "192.168.1." and only the last number at the end can be different.  Some phones can also switch wifi off when the signal is not strong - make sure your connection is using wifi.

-[Unknown]

**Comment by unknownbrackets** [comment]
I'm going to assume that helped.  #12700 will show more messaging so you can discover this (hopefully) yourself.

-[Unknown]
