### ISSUE TITLE
Naruto Impact - Crash in cutscene. (Android)

### ISSUE THREAD

**Issue by Saramagrean** [hrydgard/ppsspp#12407]
### What happens?
Game crash in custscene, on Chapter 8 - "Path to Peace", at battle scene of Naruto with Pain. happen on both OpenGL & Vulkan backend.
![72627076_405760743456150_7939842762914922496_n](https://user-images.githubusercontent.com/26355472/66624503-95521480-ec1a-11e9-9a46-337218f5221f.png)

### What *should* happen?
Nor crash. :)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

- Huawei P9 Plus (Kirin 955, Mali T-880, Android 8.1)
- PPSSPP v1.9.3-64-g0b17dd04e with default settings

Logcat file from Android.
[ppsspp-android-naruto-impact.zip](https://github.com/hrydgard/ppsspp/files/3715633/ppsspp-android-naruto-impact.zip)

**Comment by hrydgard** [comment]
Got a savegame or something near this? Which country version of the game is it?

I see several different crashes in the log, I guess you tested some other games too, or only this one?

This one is definitely a null pointer access made by the game itself, due to the nicely rounded addr:
```
10-11 11:01:58.860 21059 21682 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x7500000000 in tid 21682 (Emu), pid 21059 (androidInit)
```

Then there's a graphics driver crash:

```
10-10 23:57:48.620 24081 24081 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
10-10 23:57:48.620 24081 24081 F DEBUG   : LineageOS Version: 'unknown'
10-10 23:57:48.620 24081 24081 F DEBUG   : Build fingerprint: 'HUAWEI/VIE-AL10/HWVIE:8.0.0/HUAWEIVIE-AL10/537(C00):user/release-keys'
10-10 23:57:48.620 24081 24081 F DEBUG   : Revision: '0'
10-10 23:57:48.620 24081 24081 F DEBUG   : ABI: 'arm64'
10-10 23:57:48.620 24081 24081 F DEBUG   : pid: 23999, tid: 24076, name: Thread-8  >>> org.ppsspp.ppsspp <<<
10-10 23:57:48.620 24081 24081 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x48
10-10 23:57:48.620 24081 24081 F DEBUG   : Cause: null pointer dereference
10-10 23:57:48.620 24081 24081 F DEBUG   :     x0   00000077aca63220  x1   0000000000000000  x2   0000000000000008  x3   0000000000000000
10-10 23:57:48.620 24081 24081 F DEBUG   :     x4   000000770d80a748  x5   00000077aca63228  x6   000076f180000003  x7   000076f180000003
10-10 23:57:48.620 24081 24081 F DEBUG   :     x8   0000000000000001  x9   000000770cbd9180  x10  0000000000000000  x11  0000000000000001
10-10 23:57:48.620 24081 24081 F DEBUG   :     x12  00000077aca63180  x13  0000000000000000  x14  0000000000000040  x15  0000000000000008
10-10 23:57:48.620 24081 24081 F DEBUG   :     x16  000000000000003f  x17  000000000000000f  x18  0000000000000064  x19  0000000000000001
10-10 23:57:48.620 24081 24081 F DEBUG   :     x20  00000076f5eed570  x21  0000000000000020  x22  0000000000000000  x23  000000770d80a888
10-10 23:57:48.620 24081 24081 F DEBUG   :     x24  0000000000000000  x25  0000000000000000  x26  000000000000001f  x27  0000000000000018
10-10 23:57:48.620 24081 24081 F DEBUG   :     x28  0000000000000001  x29  0000007722a24bd0  x30  000000771ba0910c
10-10 23:57:48.620 24081 24081 F DEBUG   :     sp   000000770d80a6c0  pc   000000771ba09200  pstate 0000000060000000
10-10 23:57:48.696 24081 24081 F DEBUG   : 
10-10 23:57:48.696 24081 24081 F DEBUG   : backtrace:
10-10 23:57:48.696 24081 24081 F DEBUG   :     #00 pc 00000000007cd200  /vendor/lib64/egl/libGLES_mali.so (vkUpdateDescriptorSets+748)
10-10 23:57:48.696 24081 24081 F DEBUG   :     #01 pc 00000000006b3b6c  /data/app/org.ppsspp.ppsspp-t5QE6ZHmcoK83Bnc3u6iLw==/lib/arm64/libppsspp_jni.so (Draw::VKContext::GetOrCreateDescriptorSet(VkBuffer_T*)+540)
10-10 23:57:48.696 24081 24081 F DEBUG   :     #02 pc 00000000006b4f90  /data/app/org.ppsspp.ppsspp-t5QE6ZHmcoK83Bnc3u6iLw==/lib/arm64/libppsspp_jni.so (Draw::VKContext::DrawUP(void const*, int)+324)
10-10 23:57:48.696 24081 24081 F DEBUG   :     #03 pc 00000000006870a4  /data/app/org.ppsspp.ppsspp-t5QE6ZHmcoK83Bnc3u6iLw==/lib/arm64/libppsspp_jni.so (DrawBuffer::Flush(bool)+264)
10-10 23:57:48.696 24081 24081 F DEBUG   :     #04 pc 00000000006c5980  /data/app/org.ppsspp.ppsspp-t5QE6ZHmcoK83Bnc3u6iLw==/lib/arm64/libppsspp_jni.so (UIContext::Flush()+28)
10-10 23:57:48.696 24081 24081 F DEBUG   :     #05 pc 00000000006d4ddc  /data/app/org.ppsspp.ppsspp-t5QE6ZHmcoK83Bnc3u6iLw==/lib/arm64/libppsspp_jni.so (UI::TextureView::Draw(UIContext&)+120)
10-10 23:57:48.703 24081 24081 F DEBUG   :     #06 pc 00000000006da9c8  /data/app/org.ppsspp.ppsspp-t5QE6ZHmcoK83Bnc3u6iLw==/lib/arm64/libppsspp_jni.so (UI::ViewGroup::Draw(UIContext&)+360)
10-10 23:57:48.703 24081 24081 F DEBUG   :     #07 pc 00000000006da9c8  /data/app/org.ppsspp.ppsspp-t5QE6ZHmcoK83Bnc3u6iLw==/lib/arm64/libppsspp_jni.so (UI::ViewGroup::Draw(UIContext&)+360)
10-10 23:57:48.703 24081 24081 F DEBUG   :     #08 pc 00000000006c7038  /data/app/org.ppsspp.ppsspp-t5QE6ZHmcoK83Bnc3u6iLw==/lib/arm64/libppsspp_jni.so (UIScreen::render()+160)
10-10 23:57:48.703 24081 24081 F DEBUG   :     #09 pc 0000000000619654  /data/app/org.ppsspp.ppsspp-t5QE6ZHmcoK83Bnc3u6iLw==/lib/arm64/libppsspp_jni.so (GameScreen::render()+48)
10-10 23:57:48.703 24081 24081 F DEBUG   :     #10 pc 00000000006c4a7c  /data/app/org.ppsspp.ppsspp-t5QE6ZHmcoK83Bnc3u6iLw==/lib/arm64/libppsspp_jni.so (ScreenManager::render()+148)
10-10 23:57:48.703 24081 24081 F DEBUG   :     #11 pc 00000000005ea4f0  /data/app/org.ppsspp.ppsspp-t5QE6ZHmcoK83Bnc3u6iLw==/lib/arm64/libppsspp_jni.so (NativeRender(GraphicsContext*)+416)
10-10 23:57:48.703 24081 24081 F DEBUG   :     #12 pc 00000000005e42e8  /data/app/org.ppsspp.ppsspp-t5QE6ZHmcoK83Bnc3u6iLw==/lib/arm64/libppsspp_jni.so (Java_org_ppsspp_ppsspp_NativeActivity_runEGLRenderLoop+652)
10-10 23:57:48.703 24081 24081 F DEBUG   :     #13 pc 000000000000dae8  /data/app/org.ppsspp.ppsspp-t5QE6ZHmcoK83Bnc3u6iLw==/oat/arm64/base.odex (offset 0x8000)
10-10 23:57:49.158   990 24082 I chatty  : uid=1000 system_server expire 3 lines
```
That one could possibly be our fault, passing a null pointer in where one shouldn't be, but I still wouldn't expect UpdateDescriptorSets to crash so easily..

Hm.

**Comment by Saramagrean** [comment]
Test again and load from regular save, not get crash. Maybe cause of issue from Save stage? I play this game 2-3 hours with multiple save/load stage. 

If u want to check Save stage file. (Naruto Impact - ULUS10582) here...

Save stage with crash.
https://drive.google.com/file/d/19AWEuR3eRRSvhuIBrYEf9V5IhxU2fB_S/view?usp=drivesdk

Save stage with no crash.
https://drive.google.com/file/d/19Du7A1RNeL3zC3RrwYrnZH1VaNiVz2aE/view?usp=drivesdk

Okay, I should close?

**Comment by hrydgard** [comment]
Well, save state files crashing is not really good, but sometimes it can be impossible to find out what the original bug was.  If you can get it to crash again after saving and reloading with the latest PPSSPP, it might still be worth looking at.

**Comment by Saramagrean** [comment]
> "I see several different crashes in the log, I guess you tested some other games too, or only this one?"

Yes, logcat from only this game.

**Comment by Saramagrean** [comment]
Found another crash in-game with OpenGL only, since v1.5.0. Test on Galaxy A9 Pro & Huawei Y7 Prime 2018

**Comment by hrydgard** [comment]
@Saramagrean from exactly 1.5.0 or could you repeat what you did for WWE? :)

**Comment by Saramagrean** [comment]
I want to do too, but PPSSPP from Buildbot, oldest version show at 1.5.3-50. 😂

How can build old version (1.4.2 build) from source code? I install Android studio and download source code already.

**Comment by Saramagrean** [comment]
Oh, found direct link. 
https://buildbot.orphis.net/ppsspp/index.php?m=get&rev=v1.4.2-500-g424af6008&platform=android

**Comment by unknownbrackets** [comment]
Does the new crash have a similar logcat?  Or is the stack different?

-[Unknown]

**Comment by Saramagrean** [comment]
Crash issue in cutscene. I has no longer to see it.

but game crash after select character still present in latest git build (happen in OpenGL, Vulkan is fine). report from my friend use Vivo V9.

**Comment by Saramagrean** [comment]
Okay, for crash issue after select character move to https://github.com/hrydgard/ppsspp/issues/12847.

**Comment by unknownbrackets** [comment]
Thanks.

-[Unknown]
