### ISSUE TITLE
Renamed function hashes doesn't save reliably

### ISSUE THREAD

**Issue by LunaMoo** [hrydgard/ppsspp#12404]
It worked once for me, however when I tried dumping more functions it just wouldn't work. Not sure what are requirements for it to save and it doesn't show anything in the log about it, maybe the first time it worked I ran the game for longer time or switched between different savestates, but after one time it worked I can't get it to save function hashes again, removing knownfuncs.ini inside the system folder get's it recreated, but it's always empty:/.

 I saw daniel229 message in https://github.com/hrydgard/ppsspp/issues/7960#issuecomment-141620156 mentioning it worked last time for him in v1.0.1-891-g1c67de0, but [Unknown] said it still works for him, so maybe there are some specific requirements to make it work. Maybe a right click menu option to just save it at will would be nice as currently it's unclear when it saves the hash if at all.

**Comment by unknownbrackets** [comment]
Before, we found that it was only happening for builds from the buildbot.  No one could reproduce it with a build they made themselves.

I haven't noticed this problem, but I only ever muck with knownfuncs.ini from my own compiled builds.

-[Unknown]

**Comment by LunaMoo** [comment]
I always use my own builds so I don't think it's that, but I now tried with debugger attached and it seems to save pretty much every time(well it did 3 times in a row), maybe that's the actual difference and not the buildbot/self build thing. If I run it without debugger it saves once, then it ignores my next function renames even if I restart PPSSPP, kind of like I have to restart my pc for it to work one time again which is weird since PPSSPP process closes properly, so it's something else in windows causing this?

**Comment by unknownbrackets** [comment]
How do you quit the game?

I usually go to the pause menu, return to menu, and then give it a moment before hitting the exit button again.  I'm pretty sure they would not save reliably if I just hit X or Alt-F4 from within the game.  Just wondering what sequence you use.

-[Unknown]

**Comment by LunaMoo** [comment]
I use Ctrl+W shortcut.

 I tried to re-test this now and weirdly it saves all hashes without fail, maybe it was fixed by something or I'm getting lucky x times in a row, but tried both ctrl+w and exiting from pause menu and it saves hashes instantly after exiting the game.

 Since nobody else had problems with it and it's working now, I'll close this:3.
