### ISSUE TITLE
God of War Ghost of Sparta hang since #12328

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#12400]
God of War Ghost of Sparta hangs since #12328 (async IO on PSP threads), reported on Discord as such:

> Deividmsr: Hello, I encountered a problem in God of War GOFS that "freezes" on the "Warning" screen as soon as I enter the game. This happens since the commit "v1.9.3-39-geb2109a0f". I'm using Galaxy Note 9 - SD version

**Comment by vsub** [comment]
I was wondering what wrong...the game started once and after that it never worked again until I uninstall ppsspp and install it again(and it worked only once again)

PPSSPP freezes so hard on my phone that there is nothing I can do except force rebooting the phone

Redmi Note 7 Pro and I started the game by streaming it from my pc

**Comment by hrydgard** [comment]
Additional info: Reporter says that I/O Timing was set to Fast.

**Comment by vsub** [comment]
At least here,the problem seems to be the rendering resolution.
If I leave it to the default Auto(1:1),on my phone the game barely runs at 10fps at the title screen and if I try to boot it at that resolution,the phone will freeze.

When I set to to 1x(just for a test),the game boots just fine on any I\O mode
My phone native resolution is 2130x1080 which may be too much for my cpu\gpu

Disabling buffered rendering is another way to get better graphics than 1x\2x but some games require buffered rendering

**Comment by hrydgard** [comment]
rendering resolution has nothing to do with the hang though.

**Comment by unknownbrackets** [comment]
It looks like this has exposed a timing bug in sceUmd.  Won't have time to test on hardware until late this week, but probably sceUmdWaitDriveStatWithTimer (possibly sceUmdActivate or sceUmdCheckMedium.)

Basically, execution isn't leaving the thread calling sceUmd funcs, so it's starving the same-priority async IO thread.  It's pretty likely one of these funcs should incur a delay.

-[Unknown]

**Comment by hrydgard** [comment]
That makes sense. Wonder what else this might shake out...

**Comment by LunaMoo** [comment]
Just for a test to confirm this, delaying all 3 mentioned functions by 10000(us) made GOW games(both were affected) work again. delaying each one separately by same amount also helped, not sure if I could get correct timing as while I have 2 PSP's currently sitting unused for about a year, only one had a working UMD drive and I recall it was in pretty bad condition.

**Comment by unknownbrackets** [comment]
Hm, so I thought but afaict, none of those functions reschedule.  I checked others being called nearby, and they don't either.  Must be something wrong in the async code, after all... investigating.

-[Unknown]

**Comment by Halo-Michael** [comment]
Same question on iOS. But for me, it seems that it only hangs when it first enters. When I choose to load a game archive, it will return to normal.

**Comment by leopard20** [comment]
> At least here,the problem seems to be the rendering resolution.
If I leave it to the default Auto(1:1),on my phone the game barely runs at 10fps at the title screen and if I try to boot it at that resolution,the phone will freeze.
When I set to to 1x(just for a test),the game boots just fine on any I\O mode

@hrydgard I have a similar problem with Naruto Impact on OGL backend. The game crashes on any rendering resolution other than 1x. Vulkan is fine in this regard but has the "Z-fighting" issue.

**Comment by hrydgard** [comment]
This is now fixed.
