### ISSUE TITLE
Midnight Club 3 Dub edition error in the Sky

### ISSUE THREAD

**Issue by Drasikk** [hrydgard/ppsspp#12402]
### What happens?

It only happens in Vulkan. Makes mistakes like elongated triangles.

I recorded a little video with the error.

https://youtu.be/ABOxm5Z8lRQ

![PPSSPP_2019-10-08-17-05-56](https://user-images.githubusercontent.com/38067925/66407831-2db78180-e9ee-11e9-8ee2-dbf5412db21f.jpg)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Samsung Galaxy Note 8 Oreo 8.0.0 Exynos.
ppsspp-v1.9.3-51-g56e2e0845-android.apk

**Comment by Drasikk** [comment]
Midnight Club Los Angeles Remix the same thing happens

![PPSSPP_2019-10-08-17-23-20](https://user-images.githubusercontent.com/38067925/66409317-b8997b80-e9f0-11e9-9b2a-4abaab5dd6f1.jpg)

**Comment by unknownbrackets** [comment]
Is this #10473?  The device does have an affected Adreno 5xx device, so it may be that was only fixed because the other user's device got driver updates?

-[Unknown]

**Comment by hrydgard** [comment]
Well actually this is an Exynos device, which means Arm Mali. Looks very similar to the end-of-Z range bug we had in Burnout, #11937 . Maybe the value only needs tweaking a little bit to work around it...

**Comment by hrydgard** [comment]
A GE frame dump would be very useful: https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

**Comment by Drasikk** [comment]
@hrydgard I can't load the page.

https://github.com/hrydgard/ppsspp/issues/12413

**Comment by Drasikk** [comment]
@unknownbrackets that rare, this error has come out recently, I've never seen that mistake until now.

**Comment by Drasikk** [comment]
With the latest version of the emulator (ppsspp-v1.9.3-500-ge14bf3bcc-android.apk) or Android 9 version, the issue is fixed.
