### ISSUE TITLE
Missing menus on Galaxy A20 (user-reported)

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#12406]
Got this screenshot by email from a Mr Hernandez:

![Screenshot_20191009-130346_PPSSPP](https://user-images.githubusercontent.com/130929/66553310-25c12400-eb4b-11e9-893d-84f698de4ef2.jpg)

No idea what might be going wrong here, something with scissors?

Not sure if it's Vulkan or OpenGL, I'll ask for clarifications.

**Comment by hrydgard** [comment]
Seen on Pixel 3 by another user:

[20191010_131514 (1).zip](https://github.com/hrydgard/ppsspp/files/3716237/20191010_131514.1.zip)

@unknownbrackets  this is a weird one..

**Comment by hrydgard** [comment]
Confirmed that on the first one, backend is OpenGL. On the pixel 3, likely vulkan? 

I have a feeling this is a tween bug.

**Comment by hrydgard** [comment]
Got a contradicting report to that theory - the Pixel 3 user claims that it works fine with OpenGL, which would rule out the tween bug and probably point to a scissor rectangle miscalculation issue (which of course could be indirectly tween related).

**Comment by hrydgard** [comment]
Now I have a theory that the new screen rotation code for Android Vulkan speedup can in some cases cause slightly off scissor rectangles to end up slightly outside the screen, which is not allowed. That would mean though that the backend on the first one is not OpenGL (which a submitted ppsspp.ini indicated, but the user might have changed it before copying the file).

**Comment by hrydgard** [comment]
This is confirmed fixed now.

**Comment by Emulatorer** [comment]
@hrydgard there will be ppsspp v1.9.4 😃

**Comment by hrydgard** [comment]
Yes.
