### ISSUE TITLE
ios ppsspp 1.9.2 Texture error

### ISSUE THREAD

**Issue by ljjljjmvp** [hrydgard/ppsspp#12415]
### What happens?
when i play Warriors Orochi 2 on ios12，Vision map does not display properly

### What *should* happen?

Vista map displays normally
### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
iphone 8，ios12，ppsspp 1.9.2

**Comment by hrydgard** [comment]
Got a screenshot?

**Comment by ljjljjmvp** [comment]
The game name is Musou Orochi: Maou Sairin Plus. I'm sorry I made a mistake.
![895272B993FC56F818EDE8AA215C482E](https://user-images.githubusercontent.com/56484993/66706066-30550680-ed61-11e9-8aa0-6f3dcdcfdb1d.png)
![895272B993FC56F818EDE8AA215C482E](https://user-images.githubusercontent.com/56484993/66706074-45ca3080-ed61-11e9-8d90-56c7c21d55b6.png)
![34351C28DE73FB94525E8220CD1C0151](https://user-images.githubusercontent.com/56484993/66706075-495db780-ed61-11e9-9727-be5050684ce8.png)
The last picture is not displayed properly.
ppsspp 0.99 can run the game properly,1.6.3 mapping can be displayed normally,but there will be bugs that the generals will disappear,the game can't go on.Here that ppsspp 1.75 can run normally

**Comment by ljjljjmvp** [comment]
This is the mapping error.
![09D3642A291CB853DAAF6D5143DB4D71](https://user-images.githubusercontent.com/56484993/66706158-0e0fb880-ed62-11e9-9afd-69bded4834c7.png)

**Comment by unknownbrackets** [comment]
What should it look like?

-[Unknown]

**Comment by ljjljjmvp** [comment]
It should look like this
https://user-images.githubusercontent.com/56484993/66706075-495db780-ed61-11e9-9727-be5050684ce8.png
This is the wrong picture of the mapping.
https://user-images.githubusercontent.com/56484993/66706158-0e0fb880-ed62-11e9-9afd-69bded4834c7.png

**Comment by unknownbrackets** [comment]
It seems like you're in a different location and there are totally different characters.  I can't tell what's wrong.  Should there be a mountain?  Should there be grass?

If someone told me both were right, I would believe them.  I have not played this game, so it is not obvious to me what is wrong.

-[Unknown]

**Comment by ljjljjmvp** [comment]
OK, now I use the same people and the same map. You can see the difference easily.
![图片](https://user-images.githubusercontent.com/56484993/67217207-f1a50780-f456-11e9-86b6-3d5f61cedfbe.png)
This is the wrong image

**Comment by ljjljjmvp** [comment]
OK, now I use the same people and the same map. You can see the difference easily
This is the wrong image
![图片](https://user-images.githubusercontent.com/56484993/67217607-97587680-f457-11e9-83ae-3c26cd45873d.png)

**Comment by ljjljjmvp** [comment]
This is the right image
![图片](https://user-images.githubusercontent.com/56484993/67217696-c0790700-f457-11e9-8acc-09a8fdf2a26a.png)
I really like this game. If you can fix it, it's really good. Thank you.

**Comment by unknownbrackets** [comment]
This could be depth related.  I don't know if the GE dump feature works on iOS, but I think it does.  Can you try creating a GE dump of this screen?  These help a lot.

See here for instructions - it's not hard:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

Things I'm thinking it could be:
 * Maybe it's reading the depth buffer to apply an effect by depth.
 * Maybe our GL backend's incorrect depth handling is causing depth tests to behave incorrectly drawing the fog.
 * Maybe it's actually something related to stencil or dual source blending.

-[Unknown]

**Comment by unknownbrackets** [comment]
I wonder if this was just the iOS flat shading issue, actually.

This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
