### ISSUE TITLE
God of War: Ghost of Sparta crash

### ISSUE THREAD

**Issue by BreeshChaser** [hrydgard/ppsspp#12416]
### What happens?

![Screenshot_2019-10-12-17-29-37](https://user-images.githubusercontent.com/56372891/66707931-98cac600-ed16-11e9-930e-0b41a297a6ea.png)
At this part, when I push (L) to drop onto the platform, the emulator will kick me and send me back to my device's home screen. The game will also completely close out and I'll have to reload it. *Note this is right after spear shooting the guy holding the crank into the electrical water*
### What *should* happen?
I should be able to drop onto the platform and continue the sequence

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical sequence. 
PPSSPP most recent version, LG Q7+, PPSSPP Gold

**Comment by Saramagrean** [comment]
Duplicate by https://github.com/hrydgard/ppsspp/issues/10897 ?
