### ISSUE TITLE
I can't access PPSSPP Debugger

### ISSUE THREAD

**Issue by Drasikk** [hrydgard/ppsspp#12413]
### What happens?

I've tried it with three mobile web browsers and nothing comes out.

![Screenshot_20191012-115203_Chrome](https://user-images.githubusercontent.com/38067925/66699390-c4ce5300-ece6-11e9-9489-673bf6410849.jpg)

![Screenshot_20191012-115139_Opera](https://user-images.githubusercontent.com/38067925/66699392-cb5cca80-ece6-11e9-8206-31f72bbd2309.jpg)

![Screenshot_20191012-115215_Firefox](https://user-images.githubusercontent.com/38067925/66699397-d57ec900-ece6-11e9-8d4e-99a44125e165.jpg)

@hrydgard 
@unknownbrackets

**Comment by unknownbrackets** [comment]
Hm, will look into it.  It seems to be loading slow for me sometimes, but it does load.  If you pull down (to refresh), does it load?

Can you try giving it a solid 30 seconds?  It shouldn't take that long, but I just want to confirm if it's loading slowly or if it's not loading at all.

Does it load for you on a PC?  http://ppsspp-debugger.unknownbrackets.org/

If you select the top right "kabob" (the three dots) -> Settings (near end) -> About Chrome (last item), what Chrome version does it say?  I'm using 77.

-[Unknown]

**Comment by Emulatorer** [comment]
This is also happen to my chrome browser
here's the logcat hope it could help 
[Chrome_PPSSPP_Debugger.txt](https://github.com/hrydgard/ppsspp/files/3720821/Chrome_PPSSPP_Debugger.txt)

**Comment by Drasikk** [comment]
@unknownbrackets the page does not load at all.

Now;

![Screenshot_20191012-212400_Opera](https://user-images.githubusercontent.com/38067925/66706730-e0f9e080-ed36-11e9-870c-66b80c464ac0.jpg)

**Comment by Emulatorer** [comment]
It's ok now 😅
I just click the link from unknown but weird because my bookmark link is cannot load because it's has a /gpu at the end http://ppsspp-debugger.unknownbrackets.org/gpu

**Comment by Emulatorer** [comment]
![Screenshot_20191013-083758](https://user-images.githubusercontent.com/37603562/66709365-07e6ff80-ed95-11e9-9d45-0aad16579eaa.png)
![Screenshot_20191013-083313](https://user-images.githubusercontent.com/37603562/66709366-10d7d100-ed95-11e9-9a0c-011ef02ebd7c.png)

**Comment by unknownbrackets** [comment]
Thanks, that was it.  I had just typed the url directly in my phone.  It's on github pages, so had to copy the index.html to 404.html, but haven't hooked that into a build script.

-[Unknown]
