### ISSUE TITLE
WWE 2009 - crash in loading game screen. (Android/Windows)

### ISSUE THREAD

**Issue by Saramagrean** [hrydgard/ppsspp#12414]
### What happens?
WWE 2009 crash in loading game screen on all backends. 
![WWE-crash](https://user-images.githubusercontent.com/26355472/66700825-7f7a4780-ed1f-11e9-9391-366424f51c95.png)

Last work: v1.5.4 can boot game normally.
First break: v1.6.3 show loading spinner for a moment and then crash.

Logcat from Android.
[ppsspp-logcat-wwe-2009.zip](https://github.com/hrydgard/ppsspp/files/3720593/ppsspp-logcat-wwe-2009.zip)

### What *should* happen?
Not crash. :)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

- PPSSPP v1.9.3-64-g0b17dd04e with default settings.

- Windows 10 64 bit (i5-6200U, Nvidia 940m)
- Huawei P9+ (Kirin 955, Mali T-880)

**Comment by hrydgard** [comment]
Any chance you could use the buildbot to try to narrow down the version when this started happening? Try to go by halves.

**Comment by Saramagrean** [comment]
Okay. found it. :)

Last work: v1.5.4-305-g690a409da
First break: v1.5.4-309-g2e2d76e10

**Comment by hrydgard** [comment]
Thanks, that's super helpful!

That implicates this one, which makes sense given crash on load, but is still a little surprising:

https://github.com/hrydgard/ppsspp/pull/10501

**Comment by hrydgard** [comment]
@Saramagrean  how about now?

**Comment by Saramagrean** [comment]
Confirmed v1.9.3-70 fixed this issue. 👌

**Comment by hrydgard** [comment]
This is reported to be happening again in the latest stable.
