### ISSUE TITLE
Android/Vulkan: Display stretched past edge of screen when starting PPSSPP in immersive mode

### ISSUE THREAD

**Issue by vgf89** [hrydgard/ppsspp#12425]
### What happens?
This may or may not be related to previous touch/overlay offset/scale issues as this happens EVERYWHERE and only in Vulkan mode. Unhiding the nav bar or status bar fixes it until I kill the emulator. The problem does not appear in OpenGL mode. PPSSPP 1.9.3

Starting the emulator, notice the oversized screen:
![Screenshot_20191016-195616_PPSSPP](https://user-images.githubusercontent.com/5163157/66974635-8f13cc00-f050-11e9-8143-0a4a78cbe568.png)

Opening Settings (it's horrendously obvious here, but it's everywhere):
![Screenshot_20191016-195618_PPSSPP](https://user-images.githubusercontent.com/5163157/66974639-963ada00-f050-11e9-97a2-89e64de10710.png)

Swipe from side of screen:
![Screenshot_20191016-195622_PPSSPP](https://user-images.githubusercontent.com/5163157/66974644-9c30bb00-f050-11e9-9d26-6f1ce82eb66c.png)

After the buttons hide themselves again everything stays good:
![Screenshot_20191016-195624_PPSSPP](https://user-images.githubusercontent.com/5163157/66974646-9e931500-f050-11e9-8e6f-28b1198f2653.png)

If I start a game before unhiding the nav bar:
![Screenshot_20191016-200000_PPSSPP](https://user-images.githubusercontent.com/5163157/66974650-a2bf3280-f050-11e9-88d8-6dcb6e384faa.png)

After unhiding the navbar while in-game:
![Screenshot_20191016-200004_PPSSPP](https://user-images.githubusercontent.com/5163157/66974656-a5218c80-f050-11e9-8006-b16dd9e9886d.png)

Stays good after the navbar goes away:
![Screenshot_20191016-200006_PPSSPP](https://user-images.githubusercontent.com/5163157/66974660-a6eb5000-f050-11e9-9222-12f87b56a543.png)

### What *should* happen?
I shouldn't have to unhide the navigation bar or status bar for the emulator to correct its size.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

OnePlus 5T, Android 9 Lineage OS 16, PPSSPP 1.9.3 from Google Play in Vulkan mode (OpenGL does not present the issue)

**Comment by leopard20** [comment]
Perhaps the immersive setting should be applied after the app has shown the intro?

**Comment by vgf89** [comment]
No, it only happens if the Fullscreen mode is already on when I start the app. If it's off, the screen is the correct size.

I just discovered another related problem. If PPSSPP is in Fullscreen mode and I pull up the app switcher (square nav button) and click PPSSPP, PPSSPP appears to adjust its size. One of three things happen when returning to PPSSPP: Text/buttons/etc end up slightly wider (bit still properly laid out and without the oversized screen), or the entire screen is oversized like in my original comment, or everything is the correct size. Unhiding the nav bar fixes both bad states. Seems like maybe there's a race condition related to switching activities and recalculating dimensions?

**Comment by unknownbrackets** [comment]
Does this still happen after #12881 in the latest git builds?  I wasn't able to reproduce, and based on #10916 it seems promising that this issue may be fixed.

Note: this would be v1.9.3-754-g6edf4ddc5 or newer.

-[Unknown]

**Comment by Saramagrean** [comment]
v1.9.3-878-ge29d79a5a this issue still present.
![Screenshot_20200518-181935_PPSSPP](https://user-images.githubusercontent.com/26355472/82207832-aabbb980-9934-11ea-8a79-057c427f9260.png)

Change backend (OpenGL to Vulkan) > after PPSSPP restart choose "set UI background" > and see this issue.

**Comment by unknownbrackets** [comment]
Hm, that doesn't seem to happen on a Pixel with Android 10.  I guess it must be Android version or device build specific... or I'm doing it wrong somehow.

-[Unknown]

**Comment by Saramagrean** [comment]
Maybe, I use Huawei P9+ install custom rom Android 9.0 (Lineage OS 16).

**Comment by hrydgard** [comment]
The current stuff works on all my weirdest devices so this is surprising...

**Comment by Saramagrean** [comment]
Okay, after updated LOS16 to the latest build version (19/05/2020), I didn't see this problem anymore.

**Comment by hrydgard** [comment]
Yeah, I don't think this is our bug. Closing.
