### ISSUE TITLE
Gamepad on android causes app UI to skip across pages of options

### ISSUE THREAD

**Issue by wvnative** [hrydgard/ppsspp#12423]
On Shield TV 2017, on the newest firmware (I believe it's 8.0.0.1 or whatever) using a dualshock 4 on PPSSPP causes the D-pad to skip over several options on the app UI, as if I've pressed the button like 15 times. It's the most up to date version of PPSSPP.

Doesn't happen with the Shield controller, but vastly prefer my Dualshock 4

EDIT: Use the Dualshock 4 wired, wireless syncing is problematic.

**Comment by LunaMoo** [comment]
Renamed as it seems not specific to DS4 nor Shield TV.

**Comment by wvnative** [comment]
I have an update: Managed to finally get my dualshock 4 to sync to the shield via blutooth. And the UI worked properly. Seems tied to USB controllers.

**Comment by hrydgard** [comment]
I got the same result (works fine) when bluetooth syncing, but I wasn't able to get mine to work directly over USB. How did you do that?

**Comment by wvnative** [comment]
> 
> 
> I got the same result (works fine) when bluetooth syncing, but I wasn't able to get mine to work directly over USB. How did you do that?

I dunno man, on my shield, I just plug it in and it works.

**Comment by hrydgard** [comment]
Strange, did not work for me. But I'll try it again soon and see if I can get to the bottom of this - it would be good of both connection methods worked equally well.

**Comment by wvnative** [comment]
> 
> 
> Strange, did not work for me. But I'll try it again soon and see if I can get to the bottom of this - it would be good of both connection methods worked equally well.

Yeah, blutooth has some impracticalities. Don't wanna resync it every time i go between Shield/PS4

**Comment by ds22x** [comment]
Seems like I'm not the only one with this issue.
It doesn't seem to happen when using an Xbox One S controller via USB.

**Comment by wvnative** [comment]
I tried my xbox controller and it still happened...

**Comment by ds22x** [comment]
That's weird.
I'll try it again later today to see if it happens for me as well, as it worked just fine last time I tried (which was like a weeks ago).

**Comment by wvnative** [comment]
> 
> 
> That's weird.
> I'll try it again later today to see if it happens for me as well, as it worked just fine last time I tried (which was like a weeks ago).
> EDIT: Nope, my Xbox controller navigates the UI just fine with its DPad.

I have an xbox one X controller, but i'm pretty sure its the same as the S. very strange

**Comment by ds22x** [comment]
If its model number is 1708, then yeah, it is exactly the same.

**Comment by ds22x** [comment]
To come back to this issue.
It seems that, for whatever reason, PPSSPP detects the DPAD inputs of a wired DS4 V2 controller as analog instead of digital.
To be more precise:
```
Up = 10-4033
Down = 10-4032
Left = 10-4031
Right = 10-4030
```
Instead of:
```
Up = 10-19
Down = 10-20
Left = 10-21
Right = 10-22
```

**Comment by wvnative** [comment]
> 
> 
> To come back to this issue.
> It seems that, for whatever reason, PPSSPP detects the DPAD inputs of a wired DS4 V2 controller as analog instead of digital.
> To be more precise:
> 
> ```
> Up = 10-4033
> Down = 10-4032
> Left = 10-4031
> Right = 10-4030
> ```
> 
> Instead of:
> 
> ```
> Up = 10-19
> Down = 10-20
> Left = 10-21
> Right = 10-22
> ```

First, it happens to me regardless of using analog sticks or the D-pad.

Secondly, shit, you reminded me, I never thought to try a V1 controller. Sadly I think I sold my V1 controllers. But I will look around and if I have one I will try it out.

**Comment by wvnative** [comment]
I can update and say this is NOT happening on my shield controller. Hate that controller, but might have to play it that way until you guys can figure this out.

**Comment by ds22x** [comment]
@hrydgard Another way to fix the problem would be to allow navigation via the left control stick, as that is currently only possible with the Dpad (would also improve navigation with asymmetrical stick controllers like the Xbox One contoller and the like).

**Comment by unknownbrackets** [comment]
I initially had older firmware, and didn't have this problem.  After upgrading to 8.0.0+, it reproduces for me.

The digital buttons come through as HAT axis events, not buttons.  The analog stick doesn't have this issue, and already works.

The problem here, I suspect, is that the HAT analog conversion to keyboard doesn't really think about how often they ought to fire...

-[Unknown]
