### ISSUE TITLE
PPSSPP(jb build) didn't work on ios 12.2

### ISSUE THREAD

**Issue by thanhmoe** [hrydgard/ppsspp#12420]
PPSSPP( jb build) didn't work on ios 12.2-iphone 6s+. 
The loading screen is black and can't be run. It happen with lastest ver on cydia 1.6.3 and unoffical ver 1.9.2. I try turn off device but nothing chance! Please help. Thank u!!
![902BB071-874F-41BE-A327-B79193FFEADC](https://user-images.githubusercontent.com/56545972/66767256-2efb1980-eeda-11e9-8272-4b077a2f55ab.png)
![E1642205-3037-4984-A6AF-5E1C379FD95D](https://user-images.githubusercontent.com/56545972/66767259-2efb1980-eeda-11e9-8d1c-39636e60a716.png)

**Comment by Halo-Michael** [comment]
This is basically the same problem as https://github.com/hrydgard/ppsspp/issues/11905

**Comment by Halo-Michael** [comment]
> This is basically the same problem as

Not right, this is basically the same problem as #12269 
Which is totally fixed
You can try the ipa/deb
https://github.com/Halo-Michael/halo-michael.github.io/raw/master/ipas/PPSSPP_0v1.9.3-80-g73bf6098e.ipa
https://github.com/Halo-Michael/halo-michael.github.io/raw/master/repo/debs/org.ppsspp.ppsspp-dev-latest_0v1.9.3-80-g73bf6098e_iphoneos-arm.deb

**Comment by thanhmoe** [comment]
It very strange, in ppsspp(non-jb ver) on jb device, some time it got crash and can't open. When i restart(disable jb) it run normally and have no bug but can't run any game.

**Comment by Halo-Michael** [comment]
Can‘’t guarantee you can enable JIT without jailbreak.

**Comment by imxieyi** [comment]
> Can‘’t guarantee you can enable JIT without jailbreak.

JIT used to work fine on both jailbroken and non-jailbroken devices. After #12421 JIT no longer works on non-jailbroken devices. It crashes when launching a game (EXC_BAD_ACCESS). It is also broken on my jailbroken iPad on iOS 12.4. However, it can be made to work by attaching xcode debugger to PPSSPP process. After reverting changes in #12421 JIT works again.

**Comment by sbingner** [comment]
I expect that getting debugged is failing on non-jailbroken because it's not allowing you to fork.  I need to look into what is possible when not jailbroken to see how to ask some other process to debug you.  In the meantime I sent PR #12424 to make the old way that leaves the process in a bad state be used if the fork method fails.

**Comment by unknownbrackets** [comment]
Is that working as well as it did before, at least, now?

-[Unknown]

**Comment by Halo-Michael** [comment]
Yes, it allowed JIT works fine again on non-jb device.
Tested on iPhoneSE iOS12.4
Here is the ipa for anyone who waht to test, build with SDK 11.4:
https://halo-michael.github.io/ipas/PPSSPP_0v1.9.3-91-ge09296b9b.ipa

**Comment by thanhmoe** [comment]
i used ppsspp 1.9.3 (non-jb build) in jb device. It works very well. All good❤️

**Comment by Halo-Michael** [comment]
> i used ppsspp 1.9.3 (non-jb build) in jb device. It works very well. All good❤️

It's not a "non-jb build", just can be run on non-jb device.

**Comment by unknownbrackets** [comment]
Okay, going to close this then, given we have the other issues.

-[Unknown]

**Comment by xdccrlz** [comment]
Halo-Michael! Tell me how was you able to compile 1.9.3-91 when last GitHub version is 1.9.3-64?

**Comment by hrydgard** [comment]
Latest github version is -125, no mystery here.

**Comment by xdccrlz** [comment]
Thank you a lot,  When I updating to current version pulled from github: main screen show me old number. If I making ipa - all correct.

**Comment by xdccrlz** [comment]
> Yes, it allowed JIT works fine again on non-jb device.
> Tested on iPhoneSE iOS12.4
> Here is the ipa for anyone who want to test, build with SDK 11.4:
> https://halo-michael.github.io/ipas/PPSSPP_0v1.9.3-91-ge09296b9b.ipa

Excuse me! After clean-install i can see real version number 125.
