### ISSUE TITLE
Draw distance cause huge fps loss in mid ranged phones 

### ISSUE THREAD

**Issue by fahadrashid7705** [hrydgard/ppsspp#12437]
### What happens?
Draw distance problem 

### What *should* happen?
One problem I noticed in some games is that Draw distance is causing a lot of fps loss in mid ranged mobile, because of a lot of waste. Because the draw render is scary it can have a huge impact on cpu - gpu. So if you know of any way to fix it, please kindly give it exactly. And if you can find any of these options, you can add . Sorry for my bad english  and Sorry for saying something wrong

**Comment by hrydgard** [comment]
Draw distance? Is it a setting in some game?

Drawing more stuff takes more CPU and GPU power, yes, especially on lower power devices.

Which device in particular do you have problems on?

**Comment by fahadrashid7705** [comment]
how are you hrydgard .  in snapdragon 430 and 435 devices . medal of honor heroes 1-2 use cdraw calls highest 1400 and tenchu shadow assassin use calls draw 4000 , cause fps huge fps loss  . but draw calls 3000-3500 the games are fully stable .

**Comment by marosis** [comment]
That would be a bit hacky bit really cool.

**Comment by fahadrashid7705** [comment]
So much for this problem
Looks bad If there is a solution to this? Hopefully all the games will be good if it gets rid of it.

**Comment by fahadrashid7705** [comment]
@hrydgard any news for this issue ?

**Comment by LunaMoo** [comment]
I think you missunderstood things here, Henrik asked for your device to consider whenever something weird happens that could be fixed or it's just a slow device.

 He said nothing about creating or accepting graphics glitching/removing speedhacks, in fact, we have a different issue about removing dangerous/game breaking settings and that's the direction PPSSPP goes on.

**Comment by fahadrashid7705** [comment]
There was no misunderstanding at this time. I think it's a problem and it needs a solution. Thank you for commenting. :)

**Comment by hrydgard** [comment]
Well, PPSSPP is an emulator and just runs the games. If the games want to draw in the distance, PPSSPP obeys and does it. It's not always trivial for PPSSPP to know what draws are in the distance and which ones aren't, plus often a lot of the cost of a draw still can't be avoided even if PPSSPP knows what it is.

Certainly there's no generic solution that could be applied to all games equally, and I only do game-specific tweaks in cases where all else fails. So given that this is just about a performance drop and there's not even a good reliable way to eliminate far draws, I don't plan to work on this anytime soon, sorry.

**Comment by fahadrashid7705** [comment]
thanks henrik bother

**Comment by Gamemulatorer** [comment]
Snapdragon 430 & 435 aren't mid-range chipset they are categorise as entry-level phone chipset.

Medal Of Honor heroes 1-2 & Tenchu Shadow Assassin are running full speed on my mid-range phone Redmi Note 9 Helio G85 🤷
