### ISSUE TITLE
How to disable windowed mode?

### ISSUE THREAD

**Issue by xmha97** [hrydgard/ppsspp#12435]
Hello
I always use full-screen mode.
How I can disable double click and Alt+Enter and F11?
I don't like switching to windowed mode.
Please Help me.
![Untitled Project](https://user-images.githubusercontent.com/23485114/67173101-7eee4a80-f3ca-11e9-8a3f-e7e62c7f8833.gif)

**Comment by amirrammari** [comment]
cc: @unknownbrackets @hrydgard @xsacha @raven02

**Comment by unknownbrackets** [comment]
In recent git builds, a setting is available under Controls: Enable standard shortcut keys.  Uncheck this, and Alt-Enter / F11 will not toggle full screen.

-[Unknown]
