### ISSUE TITLE
Should reintroduce Cardboard, with an on-screen off button

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#12446]
I got rid of the Google Cardboard VR option since many users got confused by it, and I thought no-one used it, but I have received a lot more complaints than I anticipated so I've decided to bring it back.

This time there needs to be an intuitive way to turn it off from in-game.

**Comment by LunaMoo** [comment]
Top center of the screen would be a good place to place a touch button to disable it as it should not be visible while using actual googles even if it stays always on.

**Comment by hrydgard** [comment]
Put it in the bottom center, should be just as good, just looks better there IMHO.

Fixed in https://github.com/hrydgard/ppsspp/pull/12449.
