### ISSUE TITLE
Burnout Dominator Crash from v1.9.3-39-geb2109a0f and up / Android

### ISSUE THREAD

**Issue by JBDaz** [hrydgard/ppsspp#12447]
### What happens?

Title-Screen pops up for a spiltsecond, then blackscreen and sometimes full Android crash.
This happens in PPSSPP standalone and the Retroarch-Core.

### What *should* happen?

Game should load and display the loading-bar accordingly as it did before.
This bug was introduced with version: v1.9.3-39-geb2109a0f

Game works fine up to version: v1.9.3-23-g13f87301c

**Comment by hrydgard** [comment]
That's this one, the async i/o:

https://github.com/hrydgard/ppsspp/pull/12328

**Comment by unknownbrackets** [comment]
This should be fixed now based on comments in #12506.

-[Unknown]

**Comment by JBDaz** [comment]
It WAS fixed up to v1.9.3-164-g0a5ec4838

Recent changes (as of v1.9.3-170-g6a196c04a) broke it again - Burnout Dominator crashes again
