### ISSUE TITLE
Kingdom Hearts: BBB Multiplayer doesn't work.

### ISSUE THREAD

**Issue by Jerdo32** [hrydgard/ppsspp#12444]
### What happens?
 When your friend(s) joins Mirage Arena and the match starts, it *loads* for a really long time, and then disconnects the players.

### What *should* happen.
You start the match, then loads and the game plays normally

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
I don't think the hardware matters, but it's Windows 10, using PPSSPP version 1.9.3

**Comment by AkiraJkr** [comment]
This is a duplicate of #10540 without any new details.

**Comment by Jerdo32** [comment]
Should I cloae this issue then?

**Comment by Superdoom4u** [comment]
i mean because it is newer maybe ppl will see it and then someone will fix it...
