### ISSUE TITLE
Midnight Club 3 Missing Textures/Graphic bug on Xbox one

### ISSUE THREAD

**Issue by Changedd** [hrydgard/ppsspp#12459]
![Screenshot_2019-10-31_17-48-29](https://user-images.githubusercontent.com/57240597/67995315-e98e6880-fc9d-11e9-94fc-fd283a2828e9.png)
![Screenshot_2019-10-31_17-49-19](https://user-images.githubusercontent.com/57240597/67995317-eeebb300-fc9d-11e9-876c-3292a330fd9a.png)
![Screenshot_2019-10-31_17-49-45](https://user-images.githubusercontent.com/57240597/67995320-f27f3a00-fc9d-11e9-8542-f489a34ade0d.png)
This only happens when using the emulator on xbox one. I am using ppsspp v1.9.2 on xbox but when using ppsspp emulator on a android device the game runs fine. Any solution? 

Thanks

**Comment by unknownbrackets** [comment]
Does this happen on a PC using the Direct3D 11 backend?

-[Unknown]

**Comment by Panderner** [comment]
> Does this happen on a PC using the Direct3D 11 backend?
> 
> -[Unknown]

it does not happen on PCs running on Direct3D 11

**Comment by Panderner** [comment]
it also happens on Xbox Series X and Xbox Series S

**Comment by JaegerFox** [comment]
It also happens in the 1.9.3 version (I use that version because the unthrottle frameskip is much faster) on Windows 8.1
In the last version 1.10.3 work fine

**Comment by GABO1423** [comment]
Game seems to run fine now on the latest PPSSPP version:
![7-21-2022_10-42-49_PM-mjgz5zii](https://user-images.githubusercontent.com/35014183/180351426-2efb7e9d-59a2-4de7-9c3b-cc22a3217282.png)
![7-21-2022_10-42-35_PM-nazptmel](https://user-images.githubusercontent.com/35014183/180351446-18895a1b-5a31-4802-bf50-129a404ccaf7.png)

Even at resolutions higher than 1x graphics and textures worked fine. So this issue can be now closed.

**Comment by Panderner** [comment]
@GABO1423 are you using Xbox?

**Comment by unknownbrackets** [comment]
Based on previous comments / commits, I'm going to assume yes.  So I'll close this, assuming it was fixed in v1.10.0.

-[Unknown]

**Comment by GABO1423** [comment]
> @GABO1423 are you using Xbox?

Yes. Xbox Series X.
