### ISSUE TITLE
PPSSPP Libretro update

### ISSUE THREAD

**Issue by FinixFighter** [hrydgard/ppsspp#12456]
Hi! Can you please update the libretro port of PPSSPP?
https://github.com/libretro/ppsspp/commits/master
Last update has been in June 6 2019. Are you still supporting the Libretro core?

**Comment by hrydgard** [comment]
What makes you think I am responsible for github.com/libretro? It's a separate project.

We support it by keeping libretro's patches and wrapper inside the main PPSSPP repository, but the updating work is not done by us.

**Comment by FinixFighter** [comment]
Ok, I didn't know that, sorry. Thank you for your very quick answer! :)
