### ISSUE TITLE
Remote Streaming on Switch crash

### ISSUE THREAD

**Issue by FelicitusNeko** [hrydgard/ppsspp#12451]
### What happens?
The Switch port of PPSSPP crashes when attempting to browse streamed games.

### What *should* happen?
A list of available games to stream shows up.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Server:
 - Windows 10 Professional x64 10.0.18362.295
 - EVGA NVIDIA GeForce GTX 1050
 - PPSSPP 1.9.3 Stable

Client:
 - Nintendo Switch (regular) 9.0.1
 - Kosmos Atmosphere CFW 14.2
 - PPSSPP 1.9-5-gde7db87f5 (from Homebrew App Store)

Additional info: streaming from Windows to Android works fine.

**Comment by unknownbrackets** [comment]
#12371 may have already helped this, but it's from after the version you're trying.  Are there newer git builds available?

-[Unknown]

**Comment by unknownbrackets** [comment]
The code related to this has been improved not to trip on the Switch toolchain issues for threading.  There's a good chance a Switch build based on recent git will work.

@m4xw have you checked if the debugger works?  At the very least it may be an easy way for users to grab logs.

-[Unknown]

**Comment by unknownbrackets** [comment]
Confirmed working on Discord with the latest updates.

-[Unknown]
