### ISSUE TITLE
Discord-rpc is not supported anymore

### ISSUE THREAD

**Issue by strikersix23** [hrydgard/ppsspp#12450]
I'm saying this as a heads up discord rpc is not being worked on and discord says to use the discord games-sdk instead

**Comment by strikersix23** [comment]
here's the link

https://discordapp.com/developers/docs/rich-presence/how-to

**Comment by benderscruffy** [comment]
Please close as this has not been updated in years

**Comment by hrydgard** [comment]
Last I looked at it, the DIscord Games SDK didn't look suitable. We're gonna stick with the working solution and if it does stop working one day, might remove it or take another look. In the meantime, can indeed close this as not planned.
