### ISSUE TITLE
Segmentation fault on Fedora 31

### ISSUE THREAD

**Issue by sagitter** [hrydgard/ppsspp#12465]
Hi all.

### What happens?
PPSSPP-1.9.4 does not work on Fedora 31 64bit producing a `segmentation fault` (see output attached)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
ppsspp-1.9.4 targz created by the commands:

```
# git clone https://github.com/hrydgard/ppsspp.git
# cd ppsspp && git checkout %%{commit}
# git submodule update --init ext/armips
# git submodule update --init ext/glslang
# git submodule update --init ext/SPIRV-Cross
# git submodule update --init ext/discord-rpc
# git clone https://github.com/hrydgard/ppsspp-lang
# rm -rf ppsspp/.git ppsspp/.gitignore
# tar -czvf ppsspp-1.9.4.tar.gz ppsspp
```
- Fedora 31 64bit
- Kernel 5.3.7
- Driver Nouveau

```
description:    nVidia Riva/TNT/GeForce/Quadro/Tesla/Tegra K1+
author:         Nouveau Project
parm:           vram_pushbuf:Create DMA push buffers in VRAM (int)
parm:           tv_norm:Default TV norm.
		Supported: PAL, PAL-M, PAL-N, PAL-Nc, NTSC-M, NTSC-J,
			hd480i, hd480p, hd576i, hd576p, hd720p, hd1080i.
		Default: PAL
		*NOTE* Ignored for cards with external TV encoders. (charp)
parm:           nofbaccel:Disable fbcon acceleration (int)
parm:           fbcon_bpp:fbcon bits-per-pixel (default: auto) (int)
parm:           mst:Enable DisplayPort multi-stream (default: enabled) (int)
parm:           tv_disable:Disable TV-out detection (int)
parm:           ignorelid:Ignore ACPI lid status (int)
parm:           duallink:Allow dual-link TMDS (default: enabled) (int)
parm:           hdmimhz:Force a maximum HDMI pixel clock (in MHz) (int)
parm:           config:option string to pass to driver core (charp)
parm:           debug:debug string to pass to driver core (charp)
parm:           noaccel:disable kernel/abi16 acceleration (int)
parm:           modeset:enable driver (default: auto, 0 = disabled, 1 = enabled, 2 = headless) (int)
parm:           atomic:Expose atomic ioctl (default: disabled) (int)
parm:           runpm:disable (0), force enable (1), optimus only default (-1) (int)
```

**Comment by sagitter** [comment]
[ppsspp-valgrind.zip](https://github.com/hrydgard/ppsspp/files/3804067/ppsspp-valgrind.zip)

**Comment by unknownbrackets** [comment]
A gdb backtrace would be more helpful, especially with RelWithDebInfo or Debug.  You should also explain if this segfault happens on startup, or soon after, or when you start a game, etc.

Have you tried the SDL version?  Some of the leaks reported are from Qt.  The Qt port is not as well maintained.

Also, your steps are missing something like `./android/git-version-gen.sh`.

-[Unknown]

**Comment by sagitter** [comment]
>You should also explain if this segfault happens on startup, or soon after, or when you start a game, etc.

At startup.

>Have you tried the SDL version? Some of the leaks reported are from Qt. The Qt port is not as well maintained.

No.

Hope GDB log is useful.
[backtrace.log](https://github.com/hrydgard/ppsspp/files/3805852/backtrace.log)

**Comment by sagitter** [comment]
>> Have you tried the SDL version? Some of the leaks reported are from Qt. The Qt port is not as >> well maintained.
>
> No.

[Dev-working release](https://build.ppsspp.org/builds/Linux/amd64/ppssppbuildbot-org.ppsspp.ppsspp-dev-working-linux-amd64.zip) is running correctly with same SDL2-2.0.10 that i used for compiling the release `1.9.4`

**Comment by sagitter** [comment]
SDL version compiled on Fedora works if i disable EGL option with CMake.
Qt version compiled on Fedora works if i disable both EGL and GLES2 options with CMake.

**Comment by unknownbrackets** [comment]
Looks like the crash is in nouveau?  The threads all seem to just be Qt.

Some years ago when I was trying, I had issues with nouveau and had to switch to the closed source driver to get things to work properly.

-[Unknown]

**Comment by unknownbrackets** [comment]
Has this improved with the latest stable drivers?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
