### ISSUE TITLE
Multi touch problem

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#12473]
This bug has problems when I touch 3 finger at the same time jams the on screen controls
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/37503397/68522850-60091700-02eb-11ea-9b0f-ec2409adad6f.gif)
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/37503397/68522854-6d260600-02eb-11ea-8f5f-c428cd36c8ff.gif)

**Comment by LunaMoo** [comment]
Probably related or duplicate of #12025
Do you have some multi touch shortcuts on your device? If so, try turning them off, if it's same issue, that might fix it.

**Comment by Panderner** [comment]
> Probably related or duplicate of #12025
> Do you have some multi touch shortcuts on your device? If so, try turning them off, if it's same issue, that might fix it.

But it's different, I don't use multi touch shortcuts, when I enabled show touches in Android's developer options and tapping three or more touches it jammed

**Comment by LunaMoo** [comment]
That's exacly what happens WITH multi touch shortcuts. You probably have some active without knowing about/using it. On xiaomi there's a 3 touch slide for screenshots for example.

**Comment by leopard20** [comment]
That's most probably the cause. I was experiencing this on my Xiaomi Mi 5s Plus as well. Just disable the shortcut.

**Comment by Panderner** [comment]
I never enabled multi touch shortcuts i'm using realme C2

**Comment by leopard20** [comment]
Maybe it's a bug in your ROM. But this is definitely not an emulator bug.

**Comment by Panderner** [comment]
> Maybe it's a bug in your ROM. All I can say is this is definitely not an emulator bug.

My phone touchscreen is fine though, nothing happens on other emulators, but ppsspp and redream have this bug.

**Comment by leopard20** [comment]
Can you name some of those other emulators?

**Comment by Panderner** [comment]
> Can you name some of those other emulators?

My boy, Retroarch and mupen64plus fz

**Comment by hrydgard** [comment]
I get the occasional report of this from various devices but I've never been able to reproduce or seen this problem myself on any of my many devices. 

I suspect either system-configured shortcuts or a driver fault, though why other emulators would work perfectly I don't know. I think we check which device the touch events are coming from, maybe some devices are mixing them up somehow. I can't really do much without a device locally to try things on (though I might try to improve the touch test screen a bit to get more info)...

**Comment by leopard20** [comment]
Funny. I can't reproduce the issue on my phone anymore. Guess Xiaomi must've fixed it in the newer ROMs.

**Comment by Panderner** [comment]
Problem solved I turned off 3 finger screenshot, the 3 finger screenshot might cause issues for some Emulators like PPSSPP, Redream and ePSXe.

**Comment by LunaMoo** [comment]
Closing as a duplicate of existing issue mentioned few months ago;p.
