### ISSUE TITLE
Make a libretro android arm64-v8a core

### ISSUE THREAD

**Issue by BlackFacePi** [hrydgard/ppsspp#12479]
### What happens?
on ubuntu 18.04 using android ndk 19c, following the order : ./b.sh --libretro --android i can get the armeabi-v7a for android. and i add set(FORCED_CPU aarch64) into CMakeLists.txt to wish getting the arm64-v8a for android,that's failed

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
VMware + Ubuntu 18.04 PPSSPP v1.8.0 @ lastest

**Comment by BlackFacePi** [comment]
using  ndk-build , i havn't success v7a or v8a.

**Comment by unknownbrackets** [comment]
I don't know much about libretro, but #12679 implies that it builds now on Android although apparently it has issues.

Is this issue still relevant?  You may not get many comments on issues here from people who know how to build libretro.

-[Unknown]

**Comment by gouchi** [comment]
This issue should be closed and opened [here](https://github.com/libretro/libretro-super).

Thank you.
