### ISSUE TITLE
iOS build failure

### ISSUE THREAD

**Issue by squall311** [hrydgard/ppsspp#12470]
When creating PPSSPP.xcodeproj from the command line following the steps described in iOS Build Instructions, I get this error.
I am running macOS 10.15.1, Xcode 11.2.
Any help is greatly appreciated.

The C compiler

    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/Mila/Desktop/PPSSPP/ppsspp/build-ios/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/xcodebuild -project CMAKE_TRY_COMPILE.xcodeproj build -target cmTC_d50b9 -configuration Debug -hideShellScriptEnvironment && User defaults from command line:
        HideShellScriptEnvironment = YES
    
    Prepare build
    note: Using legacy build system
    === BUILD TARGET cmTC_d50b9 OF PROJECT CMAKE_TRY_COMPILE WITH CONFIGURATION Debug ===
    
    Check dependencies
    No architectures to compile for (ARCHS=armv7 arm64, VALID_ARCHS=i386 x86_64).
    
    ** BUILD FAILED **
    
    
    The following build commands failed:
    	Check dependencies
    (1 failure)
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)

**Comment by xdccrlz** [comment]
For Xcode 11.2 you must use this command for compile:cmake -DCMAKE_TOOLCHAIN_FILE=./cmake/Toolchains/ios.cmake -DIOS_PLATFORM=OS -DCMAKE_IOS_SDK_ROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk -H. -Bbuild.ios -GXcode
according to https://github.com/hrydgard/ppsspp/issues/11905#issuecomment-539296356
after that your build files have been written to: /ppsspp/build.ios

**Comment by squall311** [comment]
Thanks, but after deleting all files and cloning the repository again, the build succeeded even with the original command

**Comment by DrConflict** [comment]
Could you upload the latest ipa you managed to compile please? @squall311 I tried the latest 1.9.2 from the official website but it fails to install. Other ipas work fine. I'm on iOS 13.2.2 with Checkra1n 0.9.2. Latest Appsync unified 64 is now released as well.

**Comment by squall311** [comment]
It won't be possible because I run it on my device directly in Xcode. When I try to archive it to to make an IPA, it doesn't show up in Archives in Xcode Organizer. I have no idea how to fix it.

**Comment by unknownbrackets** [comment]
Sounds like this was a temporary error - I'm going to close it.  If there's an issue that's repeatable (even if only on first build), then please comment ad we can reopen.

If you have just a new build issue, please open a new issue.  If you're reading this and your issue is that you want it easier to obtain iOS builds, there's already an issue for that.

-[Unknown]
