### ISSUE TITLE
Weird drawing glitches in GTA LCS

### ISSUE THREAD

**Issue by TAbdiukov** [hrydgard/ppsspp#12485]
### What happens?

Somewhat related: #12060 

I use [this video](https://www.youtube.com/watch?v=9DoUzUU8Neo) for reference. Otherwise occurs during normal gameplay. Played on PPSSPP (16:04)

Among what was noticed:

Description | Time-codes
---- | ----
Ammo count glitches (sometimes randomly) | 0:00-0:11; 42:58-43:02; and many more
Text alpha is weird - there are outlines visible | 40:22-40:30 (subs); 44:45-44:50 (location)
Sometimes text gets discoloured (on the video rarely occurs, but in the wild usually happens as you fall off the bike and health-bar flickers) | 1:08:02-1:08:05
Rarely, HUD gets behind textures (never occured on real hw) | 13:02 (LHS text); 33:09 (ammo count)

Other bugs seemingly never encountered in the video
*  Sometimes text gets discoloured sometimes also at wanted level change and digital countdown timers

### What *should* happen?

Neither. I think in the old builds, there were no such glitches. Though I'm not too sure

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Windows 8.1 x64, Nvidia GTX 650. PPSSPP 1.8.0+

**Comment by TAbdiukov** [comment]
Edit: As mentioned in #12060 , perhaps the issue is only present with non-OpenGL-based drawing?

**Comment by unknownbrackets** [comment]
Any issues with text alpha - I suggest trying with 1x PSP render resolution, upscaling off, vertex cache off, texture scaling off, lazy texture caching off, and retain changed textures off.

If you experience less problems with that configuration, then issues like text alpha and discolorization may be unavoidable with rendering enhancements.

-[Unknown]

**Comment by DavidTamas** [comment]
Another thing that seems to fix issues with text alpha (at least in GTA) is the combination of texture scaling and anisotropic filter.
The other 3 issues are caused by the depth clamping bug present in non-OpenGL renderers as already described in #12060 .

**Comment by unknownbrackets** [comment]
Right.  To better understand why some of that happens, you can see here (warning: contains discussion of basic maths, proceed at your own risk):

https://forums.ppsspp.org/showthread.php?tid=13556

-[Unknown]

**Comment by benderscruffy** [comment]
No feedback/outdated?

**Comment by hrydgard** [comment]
I believe most of this is fixed. If not, please re-open.
