### ISSUE TITLE
Libretro ppsspp core in retroarch(android) has sound latency

### ISSUE THREAD

**Issue by BlackFacePi** [hrydgard/ppsspp#12483]
### What happens?
In the ppsspp APK alone, playing Tiequan 5 is very smooth. In RETROARCH + libretro PPSSPP core, the sound is stuck
### What *should* happen?
smooth

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Mobile : Huawei P9

**Comment by benderscruffy** [comment]
Please close as this has not been updated in years
