### ISSUE TITLE
Probably typo in the playstore page

### ISSUE THREAD

**Issue by vsub** [hrydgard/ppsspp#12488]
I have 1.9.3-11 installed.
Google Playstore is not showing ppsspp in available updates list
When I check for updates with an all called "App Watcher" it says that

I have: 1.9.3-11(19030001)
There is update to :1.9.4(19040000)

When I check the playstore page there are few things:

> Lots of performance and compatibility fixes! See the website for details.
> 1.9.4 delivers some additional touch screen and crash fixes and fixes a rare issue with the settings menu being invisible.

And down at the bottom

> Current Version
> 1.9.4

In the main ppsspp download game(not playstore) and the buildbot,the latest stable is 1.9.3

**Comment by LunaMoo** [comment]
Not a typo, official release is based on 1.9-hotfix branch. Closing.

**Comment by hrydgard** [comment]
Yeah, there were a few Android-specific hotfixes I wanted to get out, so did an extra minor version.

Although I should get around to merging the hotfix branch back in so that the numbering gets updated.
