### ISSUE TITLE
Pangya - Infinite loading. (Android/Windows)

### ISSUE THREAD

**Issue by Saramagrean** [hrydgard/ppsspp#12492]
### What happens?
Game infinite loading in every mode. since v1.9.3-91-ge09296b9b.
![Pangya1](https://user-images.githubusercontent.com/26355472/69187358-073c4880-0b4d-11ea-963a-32d14018d725.png)
![Pangya2](https://user-images.githubusercontent.com/26355472/69187730-c1cc4b00-0b4d-11ea-849f-1c77505cbd29.png)

### What *should* happen?
Game can loading and play normally in every mode. :)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
- Huawei P9 Plus (Android 8.1/Kirin 955/Mali T-880)
- Windows 10 64 bit (i5 6200U/Gefore 940M)
and Use PPSSPP v1.9.3-140-ga8d2e513b with default settings.

**Comment by Panderner** [comment]
Did you turned on simulate umd delays and fast memory off?

**Comment by Saramagrean** [comment]
I tried it but not help, still infinite loading. It's work fine with v1.9.3-88-g1856dabb2.

**Comment by Panderner** [comment]
Yeah I mentioned namco museum's infinite loading when I selecting any game on original selection (left side) #9523

**Comment by Panderner** [comment]
@Saramagrean did you tried a ge dump?

**Comment by Saramagrean** [comment]
👍 👍 👍
