### ISSUE TITLE
MacOS: memory issue when booting game

### ISSUE THREAD

**Issue by devinprater** [hrydgard/ppsspp#12495]
### What happens?
I launch PPSSPP from the command line, since I installed it using Homebrew. The GUI launches, I press down arrow twice to get to my game, and Press "A". The GUI crashes.

Terminal Output:

devinprater@Devins-MacBook-Pro ~ % ppsspp
I: VulkanLoader.cpp:264: VulkanMayBeAvailable: Device allowed ('SDL:OSX')
I: VulkanLoader.cpp:280: Vulkan loader: Library not available
DEBUG: Vulkan is not available, not using Vulkan.
I: Config.cpp:517: Longest display side: -1 pixels. Choosing scale 1
05:37:803 Core/Config.cpp:1187 I[LOADER]: Loading controller config: /Users/devinprater/.config/ppsspp/PSP/SYSTEM/controls.ini
05:37:808 Core/Config.cpp:1272 I[LOADER]: Config saved (got storage permission): '/Users/devinprater/.config/ppsspp/PSP/SYSTEM/ppsspp.ini'
05:37:809 Core/Config.cpp:1285 I[LOADER]: Controller config saved: /Users/devinprater/.config/ppsspp/PSP/SYSTEM/controls.ini
Pixels: 960 x 544
Virtual pixels: 960 x 544
OpenGL 2.0 or higher.
I: gpu_features.cpp:175: GPU Vendor : Intel Inc. ; renderer: Intel(R) Iris(TM) Plus Graphics 655 version str: 4.1 INTEL-14.2.16 ; GLSL version str: 4.10
loading control pad mappings from gamecontrollerdb.txt: SUCCESS!
I: NativeApp.cpp:777: NativeInitGraphics
I: thin3d_gl.cpp:935: Linking shaders.
I: thin3d_gl.cpp:935: Linking shaders.
I: NativeApp.cpp:854: NativeInitGraphics completed
05:38:199 UI/DiscordIntegration.cpp:60 I[SYSTEM]: Discord connection initialized
I: GLRenderManager.cpp:196: Running first frame (0)
05:38:465 Core/Config.cpp:1272 I[LOADER]: Config saved (clearFailedGPUBackends): '/Users/devinprater/.config/ppsspp/PSP/SYSTEM/ppsspp.ini'
05:38:466 Core/Config.cpp:1285 I[LOADER]: Controller config saved: /Users/devinprater/.config/ppsspp/PSP/SYSTEM/controls.ini
I: BackgroundAudio.cpp:151: read ATRAC, frames: 785, rate 44100
06:00:765 Core/Config.cpp:1519 I[LOADER]: Failed to read /Users/devinprater/.config/ppsspp/PSP/SYSTEM/ULUS10437_ppsspp.ini. No game-specific settings found, using global defaults.
06:00:766 Core/System.cpp:336 I[BOOT]: PPSSPP v1.9.4
06:00:769 Common/MemArenaDarwin.cpp:48 I[MEMMAP]: Successfully allocated 117473280 bytes at 0x113091000
06:00:769 Core/MemMap.cpp:292 I[MEMMAP]: Memory system initialized. Base at 0x11a099000 (RAM at @ 0x122099000, uncached @ 0x162099000)
06:00:769 Common/MemoryUtil.cpp:196 E[MEMMAP]: Failed to allocate executable memory (1048576)
06:00:769 Common/MsgHandler.cpp:45 E[SYSTEM]: Warning: Failed to allocate executable memory
Unknown error
zsh: segmentation fault  ppsspp
devinprater@Devins-MacBook-Pro ~ % 

### What *should* happen?
The game should boot and launch properly.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
MacBook Pro 15 inch, mid 2019, running macOS Catalina.

**Comment by maxmadzz** [comment]
me too

35:31:936 Common/MemoryUtil.cpp:196 E[MEMMAP]: Failed to allocate executable memory (1048576)
35:31:936 Common/MsgHandler.cpp:45 E[SYSTEM]: Warning: Failed to allocate executable memory
Unknown error

**Comment by christorrella** [comment]
Same here. MacOS Catalina.

**Comment by hrydgard** [comment]
Seems to be some Catalina issue. Debating with myself whether to upgrade my aging 2014-or-so macbook...

**Comment by christorrella** [comment]
Can I help at all? Need a system report or something?

**Comment by christorrella** [comment]
`➜  ~ sudo ppsspp
Password:
I: VulkanLoader.cpp:264: VulkanMayBeAvailable: Device allowed ('SDL:OSX')
I: VulkanLoader.cpp:280: Vulkan loader: Library not available
DEBUG: Vulkan is not available, not using Vulkan.
I: Config.cpp:517: Longest display side: -1 pixels. Choosing scale 1
46:42:063 Core/Config.cpp:1187 I[LOADER]: Loading controller config: /Users/Chris/.config/ppsspp/PSP/SYSTEM/controls.ini
46:42:068 Core/Config.cpp:1272 I[LOADER]: Config saved (got storage permission): '/Users/Chris/.config/ppsspp/PSP/SYSTEM/ppsspp.ini'
46:42:069 Core/Config.cpp:1285 I[LOADER]: Controller config saved: /Users/Chris/.config/ppsspp/PSP/SYSTEM/controls.ini
Pixels: 960 x 544
Virtual pixels: 960 x 544
OpenGL 2.0 or higher.
I: gpu_features.cpp:175: GPU Vendor : ATI Technologies Inc. ; renderer: AMD Radeon Pro 555X OpenGL Engine version str: 4.1 ATI-3.2.24 ; GLSL version str: 4.10
loading control pad mappings from gamecontrollerdb.txt: SUCCESS!
found control pad: PS4 Controller, loading mapping: SUCCESS, mapping is:
030000004c050000cc09000000016800,*,a:b0,b:b1,back:b4,dpdown:b12,dpleft:b13,dpright:b14,dpup:b11,guide:b5,leftshoulder:b9,leftstick:b7,lefttrigger:a4,leftx:a0,lefty:a1,rightshoulder:b10,rightstick:b8,righttrigger:a5,rightx:a2,righty:a3,start:b6,x:b2,y:b3,
pad 1 has been assigned to control pad: PS4 Controller
I: NativeApp.cpp:777: NativeInitGraphics
I: thin3d_gl.cpp:935: Linking shaders.
I: thin3d_gl.cpp:935: Linking shaders.
I: NativeApp.cpp:854: NativeInitGraphics completed
found control pad: PS4 Controller, loading mapping: SUCCESS, mapping is:
030000004c050000cc09000000016800,*,a:b0,b:b1,back:b4,dpdown:b12,dpleft:b13,dpright:b14,dpup:b11,guide:b5,leftshoulder:b9,leftstick:b7,lefttrigger:a4,leftx:a0,lefty:a1,rightshoulder:b10,rightstick:b8,righttrigger:a5,rightx:a2,righty:a3,start:b6,x:b2,y:b3,
I: GLRenderManager.cpp:196: Running first frame (0)
46:43:760 Core/Config.cpp:1272 I[LOADER]: Config saved (clearFailedGPUBackends): '/Users/Chris/.config/ppsspp/PSP/SYSTEM/ppsspp.ini'
46:43:760 Core/Config.cpp:1285 I[LOADER]: Controller config saved: /Users/Chris/.config/ppsspp/PSP/SYSTEM/controls.ini
46:45:115 Core/Config.cpp:1519 I[LOADER]: Failed to read /Users/Chris/.config/ppsspp/PSP/SYSTEM/ULES00479_ppsspp.ini. No game-specific settings found, using global defaults.
46:45:115 Core/System.cpp:336 I[BOOT]: PPSSPP v1.9.4
46:45:116 Common/MemArenaDarwin.cpp:48 I[MEMMAP]: Successfully allocated 117473280 bytes at 0x11424d000
46:45:116 Core/MemMap.cpp:292 I[MEMMAP]: Memory system initialized. Base at 0x11b255000 (RAM at @ 0x123255000, uncached @ 0x163255000)
46:45:116 Common/MemoryUtil.cpp:196 E[MEMMAP]: Failed to allocate executable memory (1048576)
46:45:116 Common/MsgHandler.cpp:45 E[SYSTEM]: Warning: Failed to allocate executable memory
Unknown error
[1]    12000 segmentation fault  sudo ppsspp
➜  ~ 
`

**Comment by christorrella** [comment]
➜  ~ sudo ppsspp
Password:
I: VulkanLoader.cpp:264: VulkanMayBeAvailable: Device allowed ('SDL:OSX')
I: VulkanLoader.cpp:280: Vulkan loader: Library not available
DEBUG: Vulkan is not available, not using Vulkan.
I: Config.cpp:517: Longest display side: -1 pixels. Choosing scale 1
46:42:063 Core/Config.cpp:1187 I[LOADER]: Loading controller config: /Users/Chris/.config/ppsspp/PSP/SYSTEM/controls.ini
46:42:068 Core/Config.cpp:1272 I[LOADER]: Config saved (got storage permission): '/Users/Chris/.config/ppsspp/PSP/SYSTEM/ppsspp.ini'
46:42:069 Core/Config.cpp:1285 I[LOADER]: Controller config saved: /Users/Chris/.config/ppsspp/PSP/SYSTEM/controls.ini
Pixels: 960 x 544
Virtual pixels: 960 x 544
OpenGL 2.0 or higher.
I: gpu_features.cpp:175: GPU Vendor : ATI Technologies Inc. ; renderer: AMD Radeon Pro 555X OpenGL Engine version str: 4.1 ATI-3.2.24 ; GLSL version str: 4.10
loading control pad mappings from gamecontrollerdb.txt: SUCCESS!
found control pad: PS4 Controller, loading mapping: SUCCESS, mapping is:
030000004c050000cc09000000016800,*,a:b0,b:b1,back:b4,dpdown:b12,dpleft:b13,dpright:b14,dpup:b11,guide:b5,leftshoulder:b9,leftstick:b7,lefttrigger:a4,leftx:a0,lefty:a1,rightshoulder:b10,rightstick:b8,righttrigger:a5,rightx:a2,righty:a3,start:b6,x:b2,y:b3,
pad 1 has been assigned to control pad: PS4 Controller
I: NativeApp.cpp:777: NativeInitGraphics
I: thin3d_gl.cpp:935: Linking shaders.
I: thin3d_gl.cpp:935: Linking shaders.
I: NativeApp.cpp:854: NativeInitGraphics completed
found control pad: PS4 Controller, loading mapping: SUCCESS, mapping is:
030000004c050000cc09000000016800,*,a:b0,b:b1,back:b4,dpdown:b12,dpleft:b13,dpright:b14,dpup:b11,guide:b5,leftshoulder:b9,leftstick:b7,lefttrigger:a4,leftx:a0,lefty:a1,rightshoulder:b10,rightstick:b8,righttrigger:a5,rightx:a2,righty:a3,start:b6,x:b2,y:b3,
I: GLRenderManager.cpp:196: Running first frame (0)
46:43:760 Core/Config.cpp:1272 I[LOADER]: Config saved (clearFailedGPUBackends): '/Users/Chris/.config/ppsspp/PSP/SYSTEM/ppsspp.ini'
46:43:760 Core/Config.cpp:1285 I[LOADER]: Controller config saved: /Users/Chris/.config/ppsspp/PSP/SYSTEM/controls.ini
46:45:115 Core/Config.cpp:1519 I[LOADER]: Failed to read /Users/Chris/.config/ppsspp/PSP/SYSTEM/ULES00479_ppsspp.ini. No game-specific settings found, using global defaults.
46:45:115 Core/System.cpp:336 I[BOOT]: PPSSPP v1.9.4
46:45:116 Common/MemArenaDarwin.cpp:48 I[MEMMAP]: Successfully allocated 117473280 bytes at 0x11424d000
46:45:116 Core/MemMap.cpp:292 I[MEMMAP]: Memory system initialized. Base at 0x11b255000 (RAM at @ 0x123255000, uncached @ 0x163255000)
46:45:116 Common/MemoryUtil.cpp:196 E[MEMMAP]: Failed to allocate executable memory (1048576)
46:45:116 Common/MsgHandler.cpp:45 E[SYSTEM]: Warning: Failed to allocate executable memory
Unknown error
[1]    12000 segmentation fault  sudo ppsspp
➜  ~

**Comment by JPEspinoza** [comment]
Same problem, PPSSPP 1.6.3 and OpenEmu's 1.9.3.1 PPSSPP core work fine though.

This on macOS Catalina.

**Comment by hrydgard** [comment]
I guess I have no choice, I'll have to upgrade my machine to Catalina and investigate....

**Comment by christorrella** [comment]
Sounds like a plan. I’m rooting for you!

**Comment by unknownbrackets** [comment]
https://github.com/flutter/flutter/issues/36714

Maybe we need to use MAP_JIT or use the RW exclusive code now?

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, something like that. I'll solve it after the holidays.

**Comment by hrydgard** [comment]
Turns out the culprit was our use of MAP_32BIT which we no longer need anyway, I think. Disabled it on Mac.

**Comment by unknownbrackets** [comment]
Yeah, I think we fixed needing that even on Linux.

-[Unknown]
