### ISSUE TITLE
Mhp3rd quest always closing

### ISSUE THREAD

**Issue by Dartfeld0** [hrydgard/ppsspp#12499]
Can someone help me my ppsspp was always exiting when im doing a quest in mhp3rd "leading the charge" at the village girl

**Comment by Emulatorer** [comment]
What's your platform Android or PC?
Are you using latest ppsspp github version
you didn't use cheat code

**Comment by Saramagrean** [comment]
Similar https://github.com/hrydgard/ppsspp/issues/11410 ?

**Comment by DivineKi** [comment]
It may be your backend rendering, if its OpenGL, try Vulkan

**Comment by Gamemulatorer** [comment]
@hrydgard this is a duplicate of #11410

**Comment by hrydgard** [comment]
Duplicate of #11410.
