### ISSUE TITLE
Crisis Core Final Fantasy VII (PAL Ver) Crash

### ISSUE THREAD

**Issue by StygianGames** [hrydgard/ppsspp#12497]
I have an issue, while playing through Crisis Core (PAL) the game keeps crashing at a certain point. It tries to load but it ends up crashing the whole emulator. I haven't had any problems with the game before, it was playing smoothly at good frame rates too but just this one part won't load. 
I have tested with default settings and even with some settings off but still ends with a crash. 
The game is meant to continue into another cutscene, the whole game was working completely fine with no crashing/interruptions. This one scene just won't load. I am using the latest version of PPSSPP as of 25/11/2019 which is version 1.9.3 on PC. 
My PC specs:
Intel(R) Core(TM) i7-7700HQ CPU @ [2.80GHz]
16GB RAM
GeForce GTX 1050 Ti

PPSSPP folder (with savefile and savestates) below:

Downloads:
PPSSPP Folder: https://1drv.ms/u/s!AvTYtV4g4WU9gP8wXoXNDkTAtpKxpw?e=2aWkYz
![ULES01044_00001](https://user-images.githubusercontent.com/38231770/69539276-44cf2480-0fd8-11ea-88a5-fe2e69f3fae3.jpg)

**Comment by LunaMoo** [comment]
Don't upload iso, it's illegal. Post your iso hash like crc instead, to show whenever it's just a copy corruption.

**Comment by hrydgard** [comment]
Oops, didn't even notice that link, just quickly saw that the savegame was link.

**Comment by StygianGames** [comment]
My apologies, I didn't know about that. 😓

**Comment by unknownbrackets** [comment]
Can you check the CRC of your disc?

There are multiple PAL versions but people have reported they work fine in the past.

Additionally, you should try saving in game, deleting all save states, and then loading the save and continuing.  Sometimes, save states can "save" bugs from previous PPSSPP versions, or even expose bugs in games (not many people played PSP games for 10s of hours in one sitting.)

-[Unknown]

**Comment by unknownbrackets** [comment]
Any feedback here?  Were you using a good disc?  Did saving help?

-[Unknown]

**Comment by Gamemulatorer** [comment]
Im experiencing blacksreen using your savestates 🤔
![Screenshot_20200523-065001](https://user-images.githubusercontent.com/37603562/82714579-e1d9f400-9cc1-11ea-8f93-89620c07c1c6.png)
GE dump 
[recording.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/4670685/recording.ppdmp.zip)

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
