### ISSUE TITLE
Assignable MUTE toggle Hotkey [Feature Request]

### ISSUE THREAD

**Issue by mcabel** [hrydgard/ppsspp#12491]
Please, add an assignable toggle mute hotkey. I'm not talking about the "sound note" button or volume button on hardware psp. I believe those are included for things like homebrew or other functions, so I rather have a dedicate sound toggle.  I often find myself browsing an online guide and psp audio + the video makes quite a ruckus. There are many other situations where I have needed to mute the emulator, but not the computer.

LunaMoo sugested a workaround using alternate speed hotkeys, which work, to an extent, but with this, it becomes a pain in the neck to use the speed hotkey efficiently.

To make it fancy-er it could even be and audio toggle using Audio = [textbox 1]  or [textbox 2]....but I would totally be satisfied with a simple hot key to toggle between 0% audio and Xglobal

**Comment by hrydgard** [comment]
Kind of a niche use case but I see the point.
