### ISSUE TITLE
Final Fantasy IV text render from big to small

### ISSUE THREAD

**Issue by ngoncom** [hrydgard/ppsspp#12498]
Hi,

I get a trouble when playing Final Fantasy IV, text seem being smaller.

Thank!

<img width="822" alt="2019-11-25_205759" src="https://user-images.githubusercontent.com/8530544/69547071-85727200-0fc7-11ea-86b4-b7689f9baa03.png">

**Comment by hrydgard** [comment]
Whoa, that's a bizarre one.

Which platform is this on? Android/Windows/iOS? What GPU?

**Comment by ngoncom** [comment]
I am using PPSSPP Gold v1.9.3 (64bit) with fresh install

I am using Dell XPS with:
- CPU is Intel Core i7-8550U
- GPU is Intel UHD Graphics 620

P/S: game's menu is horrible, I can't see the text inside it

**Comment by hrydgard** [comment]
Did you try to switch backend (D3D/Vulkan/OpenGL) in graphics settings? Which ones have the problem, or all of them?

**Comment by ngoncom** [comment]
Oh oh!

When changing graphic backenk from Direct3D 11 to (OpenGL, Direct3D 11 or Vulkan) it work well 😄 

Thank you so much!

<img width="678" alt="2019-11-25_214307" src="https://user-images.githubusercontent.com/8530544/69550187-2adc1480-0fcd-11ea-9113-a4cba28794d1.png">

**Comment by hrydgard** [comment]
Thanks for testing! Leaving this open, this will need looking into at some point.

**Comment by unknownbrackets** [comment]
Does it work under Direct3D 11 work if you set:

 - Texture scaling off
 - Render resolution 1x
 - Vertex cache off

I tried this and didn't have problems, so I'm wondering if it's related to other settings.

-[Unknown]

**Comment by unknownbrackets** [comment]
Additionally, which region of the game are you using?  Could you try exporting a GE frame dump?  These help a lot.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by nassau-tk** [comment]
@hrydgard 
@unknownbrackets 

for Reference.

I tested FinalFantasyIV (NPJH50414)(Japanese) on Windows10(64-bit).
Dump files here.
[FinlFantasyIV_Dump.zip](https://github.com/hrydgard/ppsspp/files/5309566/FinlFantasyIV_Dump.zip)

It's not happen any situation.
1.9.3/D3D11
1.9.3 -577/OpenGl/Vulkan/D3D9/D3D11 (#12768 )
1.10.3-803/OpenGl/Vulkan/D3D9/D3D11
GPU is GeForce GTX750Ti.

**Comment by hrydgard** [comment]
OK, we can close this then. Thanks!
