### ISSUE TITLE
Danganronpa 2 Frame Drop on mobile

### ISSUE THREAD

**Issue by SpicyJuicyMemes** [hrydgard/ppsspp#12500]
I was playing SD2 on the ppsspp when i was on the loading menu i had 60 frames, but when i start up a game i instantly go down to 3 fps. this is the only game that ever happened to me other games dont do that. here are some references:
![Screenshot_20191202-175121_PPSSPP Gold](https://user-images.githubusercontent.com/58422537/69950603-96266900-152e-11ea-8781-d10a3363a190.jpg)
![Screenshot_20191202-175126_PPSSPP Gold](https://user-images.githubusercontent.com/58422537/69950625-9de60d80-152e-11ea-9b23-6190d0076c39.jpg)
![Screenshot_20191202-175130_PPSSPP Gold](https://user-images.githubusercontent.com/58422537/69950631-a1799480-152e-11ea-9045-b82c623ae434.jpg)
![Screenshot_20191202-174827_CPU-Z](https://user-images.githubusercontent.com/58422537/69950637-a4748500-152e-11ea-94e9-a27c97363b48.jpg)

**Comment by hrydgard** [comment]
Likely something to do with the readbacks required for this game to work, but 3fps is extreme and shouldn't happen. 

Do you get the same behavior with Backend set to OpenGL as with Vulkan?

**Comment by SpicyJuicyMemes** [comment]
yes, but i quickly resolved it because i forgot to download and move some
files. it still has like 17 frames but its an improvement, sorry about
that. i just wasted your time, im really sorry.

**Comment by SpicyJuicyMemes** [comment]
here is proof to back me up.
