### ISSUE TITLE
TAS support

### ISSUE THREAD

**Issue by InfamousKnight** [hrydgard/ppsspp#12501]
I recall there being an attempt at this 2 years ago, and since those 2 years this emulator has gotten major improvements.

I also recall it being abandoned because it was too complicated at the time and lack of free time on the project leader(fog).

So is anyone willing to give this a shot? Its been wanted for years.

**Comment by MiYakuGaming** [comment]
Is there any interest in this at all?

**Comment by hrydgard** [comment]
Closing this in favor of the new issue, which at least has a better description of the required features: #15617
