### ISSUE TITLE
The 3rd Birthday

### ISSUE THREAD

**Issue by Drasikk** [hrydgard/ppsspp#12502]
# What happens?

This happens on both Android 8 and 9.

OPENGL

![PPSSPP_2019-12-05-17-23-24](https://user-images.githubusercontent.com/38067925/70254535-85bbfb80-1785-11ea-820c-0ee38fe31534.jpg)

Vulkan

![PPSSPP_2019-12-05-17-23-49](https://user-images.githubusercontent.com/38067925/70254575-98363500-1785-11ea-9ff9-ece88fc9eb00.jpg)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Samsung Galaxy NOTE 8 SM-N950F
Android 9
ppsspp-v1.9.3-147-ge84788138-android.apk

Dump:

[ULES01513_0001.zip](https://github.com/hrydgard/ppsspp/files/3928024/ULES01513_0001.zip)

**Comment by hrydgard** [comment]
So I assume you mean that it looks right in Vulkan, and that the OpenGL picture should look the same? I'm not that familiar with this game.

**Comment by Drasikk** [comment]
> So I assume you mean that it looks right in Vulkan, and that the OpenGL picture should look the same? I'm not that familiar with this game.

The error is only in OPENGL.

**Comment by hrydgard** [comment]
Thanks.

**Comment by unknownbrackets** [comment]
To confirm, this is with default settings, without "disable slower effects" or similar, right?

If so, I'd guess this is some sort of weird depal shader accuracy/overflow issue.

-[Unknown]

**Comment by Drasikk** [comment]
Yes, it's with the standard settings.

With the option enabled "disable slower effects" comes out this way;

![PPSSPP_2019-12-28-08-26-37](https://user-images.githubusercontent.com/38067925/71540584-f1d8ec00-294c-11ea-9de3-6e0d09f628b6.jpg)

![PPSSPP_2019-12-28-08-33-37](https://user-images.githubusercontent.com/38067925/71540589-fd2c1780-294c-11ea-9132-22f8a0b7c3f1.jpg)

**Comment by Emulatorer** [comment]
related #11092

**Comment by Emulatorer** [comment]
![Screenshot_20200303-204729](https://user-images.githubusercontent.com/37603562/75777571-2c1d9a00-5d91-11ea-97bd-e3a55ad1fc29.png)
DEFAULT SETTINGS 🤔
PPSSPP v1.9.3-367
Mali-450MP GPU
Opengl 2.0

**Comment by Drasikk** [comment]
Looks like it's fixed. I'm going to close it and if I see it seems like the problem again, I'll comment it here.
