### ISSUE TITLE
[Android][Graphic]Draslot Syuyaku wa Zenigata(ULJM05014) ドラスロット 主役は銭形

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#12507]
### What happens?
This game is a slot machine game.
When a steel case of a slot machine is OpenGL, a problem don't be drawn right.
It's drawn right at the time of Vulkan use.

### What *should* happen?
Even OpenGL is drawn right.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
PPSSPP Ver. : 1.9.3-147
OS: Android 9.0
DeviceName: SONY SO-02K / Xperia XZ1 Compact (Japan)
CPU: Snapdragon835 (Octa-core)
GPU: Adreno 540
Resolution: 720×1280
RAM: 4GB
ROM:32GB
ExternalStrage: microSDXC 512GB

Please check the screenshot.

![Screenshot_20191212-161510](https://user-images.githubusercontent.com/48179091/70691429-6a5c6d80-1cfc-11ea-869a-16735455ee7f.png)

![Screenshot_20191212-161621](https://user-images.githubusercontent.com/48179091/70691436-6deff480-1cfc-11ea-8f16-d30a9acd89a1.png)

**Comment by hrydgard** [comment]
That's interesting! Can you make a GE frame capture? https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

**Comment by nassau-tk** [comment]
It was a very difficult request, but I think it's probably done.　(^o^)/
Please check it!!

[ULJM05014_GEdump.zip](https://github.com/hrydgard/ppsspp/files/3954641/ULJM05014_GEdump.zip)

**Comment by iota97** [comment]
Shouldn't the label be OpenGL? It look like Vulkan render fine while OpenGL is broken from the screenshot.

**Comment by hrydgard** [comment]
Oh, indeed, oops! Thanks for making the frame capture nassau!

**Comment by unknownbrackets** [comment]
The specular coef is 00ff2626 / -220849154580920358351916130867047563264.  This seems to cause it to use full white.  Essentially, this makes the specular factor Infinity.

When I skip the specular, things look right.  Even if I cap it, it doesn't look like it's supposed to - here's a PSP's rendering:
![ULJM05014_#12507_draslot_metal_rendering](https://user-images.githubusercontent.com/191233/71647941-59c36580-2cb2-11ea-876a-1251022f674d.png)

It seems infinity should be treated as zero, but will probably need to figure out where the limit is that the hardware kills it...

-[Unknown]
