### ISSUE TITLE
Medievil resurrection doesn't boot in the latest builds

### ISSUE THREAD

**Issue by LuismaSP89** [hrydgard/ppsspp#12506]
Medievil resurrection no longer boots on the latests PPSSPP development versions. Was working fine more or less a month ago. Tested with other games and it seems that it is the only game affected.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

PPSSPP 1.9.3-143-gf03417c08
Windows 10 x64
16 GB DDR3
i7 4790k

**Comment by LuismaSP89** [comment]
I forget to include my graphic's card:
Nvidia GTX 970

**Comment by hrydgard** [comment]
That's really odd, thanks for reporting - will look into it.

**Comment by lastblade** [comment]
The same is happening with Burnout Dominator. posting here cause it's probably the same issue. i was able to play by loading a savestate tho.

**Comment by brujo5** [comment]
+1 I just noticed

**Comment by LuismaSP89** [comment]
@brujo5 Sorry, I didn't bisected the guilty build yet. I can only say that it is working a month ago "more or less"

**Comment by hrydgard** [comment]
I'll dig into it this week, but if you guys feel like bisecting in the meantime that would be helpful :)

**Comment by brujo5** [comment]
@LuismaSP89 Ok thanks

@hrydgard here log files 
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/3945706/ppsspplog.zip)

**Comment by iota97** [comment]
Bisection of "Burnout Dominator" result in: 
e817d79c39fa952e5c06c0be803fc45932a4b596 is the first bad commit

**Comment by hrydgard** [comment]
Great, thanks @iota97 !

Yeah, not too surprising that a few more games broke from that, it's a big change (but should be fore the better once we've ironed out the bugs..)

**Comment by unknownbrackets** [comment]
> 80020323=sceIoChangeAsyncPriority(-1, 0000005f): bad file descriptor

Hm.

> 4=sceIoOpenAsync(disc0:/sce_lbn0x5c70_size0x22ea1000, 1, 0)
> 0=sceIoWaitAsync(4, 09b8c080[0000000000000000]): waiting
> 8002032a=sceIoWaitAsync(4, 09b8c220[0000000000000000]): no async pending

That's odd.

> 38:55:625 user_main    D[SCEIO]: hle\sceio.cpp:1389 0=sceIoLseekAsync(4, 0000000000000800, 0)
> 38:55:625 user_main    D[HLE]: hle\hle.cpp:504 Compiling syscall to sceIoPollAsync

This is where it dies, though.  Seems to spin loop.

Maybe it's an issue with seeking specifically on sce_lbn?

-[Unknown]

**Comment by benderscruffy** [comment]
Need for Speed - Shift (USA) (En,Fr,Es) doesnt load aswell

**Comment by brujo5** [comment]
The same for SOCOM- U.S. Navy SEALs Fireteam Bravo 2

**Comment by unknownbrackets** [comment]
Are these games working now in the latest git build?

-[Unknown]

**Comment by brujo5** [comment]
![UCES00006_00000](https://user-images.githubusercontent.com/4172898/71502052-0fae3000-282b-11ea-9d6c-bc90b5b9648a.png)
yes, big thanks.

**Comment by unknownbrackets** [comment]
Thanks for validating, I'm going to close this.

If there are other games still not working, let's open a new issue.

-[Unknown]

**Comment by LuismaSP89** [comment]
Medievil keeps failing at boot "at least for me" anyone else can confirm this please?

Note: using 1.9.3-160-g70ddfc7c8

**Comment by brujo5** [comment]
that's the version i tested

![3](https://user-images.githubusercontent.com/4172898/71526278-56377500-2893-11ea-9e16-0824e9009a0a.png)

**Comment by LuismaSP89** [comment]
You're using the 1.9.3-64 version. 1.9.3-60 is mine. I'll try to look for this new version. Thanks.

**Comment by unknownbrackets** [comment]
It's fixed in v1.9.3-164-g0a5ec4838.  It's not fixed in any of v1.9.3-160-g70ddfc7c8, v1.9.3-64-g0b17dd04e, etc.  You have to use the latest git build as of this reply.

-[Unknown]

**Comment by benderscruffy** [comment]
Need for Speed - Shift (USA) (En,Fr,Es) works again
