### ISSUE TITLE
Fast forward locked to monitor refresh rate

### ISSUE THREAD

**Issue by Sanaki** [hrydgard/ppsspp#12515]
### What happens?
Fast forward (on unlimited) cannot exceed 60 fps (my refresh being ~60Hz).

### What *should* happen?
Unlimited fast forward should be limited only by hardware constraints.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

OS: Linux Mint 19.2 Cinnamon
Kernel: 4.15.0-72-generic
Backend: both OpenGL and Vulkan
Build: SDL git build v1.9.3-147-ge84788138 (issue has been present for quite some time)
GPU: Geforce GTX 1060 6GB
Driver: 4.6.0 NVIDIA 440.44

The libretro core (also self-built) does not have this issue, nor have I experienced it on android (from orphis buildbot, not self-built).

I attempted to bisect, but the issue is still present in 8db14a3f674dc6e0589a96a4a761f32ac662a736 and I can't build older due to the cmake issue that one repairs.

**Comment by Sanaki** [comment]
I'm an idiot. It's something in my settings. I'm closing this, but I'll post back if I find the exact setting responsible.

**Comment by Sanaki** [comment]
In ppsspp.ini, the setting causing this was FrameSkipUnthrottle = False. Switch it to True and all is well. Not entirely sure how that happened, but this is the same config I've been using for years, so who knows what's happened to it over time.

**Comment by hrydgard** [comment]
Sounds like you may have forced vsync in the graphics driver settings? That can cause this.

**Comment by unknownbrackets** [comment]
On Linux, vsync is always forced and `FrameSkipUnthrottle` defaults to true.  It defaults to false on Windows/UWP, though.

It's better for it to be false when possible (Windows/UWP), because there are some negative side effects to frameskipping.

Perhaps you copied an ini that came from a Windows install?

-[Unknown]

**Comment by Sanaki** [comment]
I carried my config between a few operating systems over the years, it's entirely possible that one started on Windows. Good to know.
