### ISSUE TITLE
PPSSPP not opening, Crashing on Activation

### ISSUE THREAD

**Issue by LastChalice** [hrydgard/ppsspp#12514]
### What happens?
PPSSPP hasn't been able to open on my new macbook. 
Specifically, I backed up my old macbook air onto a time machine external hard drive, but after installing this time machine backup onto my new computer (macbook pro 16 in.),  ppsspp hasn't been able to boot at all, and that's after reinstalling the "ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" homebrew addition just to make sure. 
Any idea as to why this is happening?
Note - all of this is happening on MacOS Catalina, 15.1

### hardware
Old macbook air (that ppsspp still works on) - 2017 Macbook Air, 13 in., 
1.8GHz dual-core Intel Core i5 processor
8GB of 1,600MHz LPDDR3 RAM.
128GBflash storage.
13.3in, 1,440 x 900-pixel display.

New Macbook Pro - 16 in.  (That PPSSPP won't work on, using identical backup)
CPU: 9th gen Core i7,
RAM: 16GB (up to 64GB)
Storage: 512GB t
GPU: AMD Radeon Pro 5300M (4GB)

### Error Report
Process:               PPSSPPSDL [10830]
Path:                  /Applications/PPSSPPSDL.app/Contents/MacOS/PPSSPPSDL
Identifier:            ???
Version:               ??? (???)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           PPSSPPSDL [10830]
User ID:               501

Date/Time:             2019-12-15 21:23:41.954 -0500
OS Version:            Mac OS X 10.15.1 (19B2093)
Report Version:        12
Bridge OS Version:     4.1 (17P1583)
Anonymous UUID:        (Blanked out for personal privacy)

Time Awake Since Boot: 7200 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib
  Referenced from: /Applications/PPSSPPSDL.app/Contents/MacOS/PPSSPPSDL
  Reason: image not found

Binary Images:
       0x101cb7000 -        0x102be3fe7 + (??? - ???) <61D21A43-ACF7-3ED8-AA38-1B6721866E4B> /Applications/PPSSPPSDL.app/Contents/MacOS/PPSSPPSDL
       0x10d83d000 -        0x10d8cdb5f  dyld (733.6) <DAFEA246-2F9A-3DCB-A37C-4246D4F92770> /usr/lib/dyld

Model: MacBookPro16,1, BootROM 1037.40.127.0.0 (iBridge: 17.16.11583.0.0,0), 6 processors, 6-Core Intel Core i7, 2.6 GHz, 16 GB, SMC 
Graphics: kHW_IntelUHDGraphics630Item, Intel UHD Graphics 630, spdisplays_builtin
Graphics: kHW_AMDRadeonPro5300MItem, AMD Radeon Pro 5300M, spdisplays_pcie_device, 4 GB
Memory Module: BANK 0/ChannelA-DIMM0, 8 GB, DDR4, 2667 MHz, Micron, 8ATF1G64HZ-2G6E1
Memory Module: BANK 2/ChannelB-DIMM0, 8 GB, DDR4, 2667 MHz, Micron, 8ATF1G64HZ-2G6E1
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x7BF), wl0: Oct 19 2019 15:38:45 version 9.113.2.0.32.5.39 FWID 01-c66dbfbd
Bluetooth: Version 7.0.1f1, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: Satechi Multiport Pro
USB Device: USB 3.1 Bus
USB Device: Satechi Multiport Pro
USB Device: USB 2.0 BILLBOARD
USB Device: USB Receiver
USB Device: Apple T2 Bus
USB Device: Composite Device
USB Device: Touch Bar Backlight
USB Device: Touch Bar Display
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Headset
USB Device: Ambient Light Sensor
USB Device: FaceTime HD Camera (Built-in)
USB Device: Apple T2 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 51.4
Thunderbolt Bus: MacBook Pro, Apple Inc., 51.4

**Comment by Panderner** [comment]
Unfortunately Apple deprecated opengl support for iOS 12 and MacOS Mojave and above. I hope it gets moltenvk or metal support

**Comment by Panderner** [comment]
And also MacOS Catalina dropped support for all 32 bit apps including carbon api and QuickTime 7 apps

**Comment by LunaMoo** [comment]
Read the log you posted - you're missing libraries.
From ppsspp Wiki here:
On Mac, you can use brew to install the required dependencies:

brew upgrade
brew install sdl2 cmake libzip

**Comment by LastChalice** [comment]
Thanks, it works now!
