### ISSUE TITLE
[Vulkan] FIFA Soccer (USA) speed issues

### ISSUE THREAD

**Issue by meowthed** [hrydgard/ppsspp#12523]
### What happens?
Game reported 15 frames, while speed remains at 100% most of the time. Additionally, the game has some graphics issues as shown here:
![Untitled](https://user-images.githubusercontent.com/41223243/71389821-ec239380-2638-11ea-95c6-bd01c6c11868.png)

### What *should* happen?
Speed and graphics should match this gameplay footage:
`https://www.youtube.com/watch?v=spYHpVCJ1yI`

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Intel Core i7-4500U
NVIDIA GeForce 740M
Windows 10 Pro x64
PPSSPP 1.9.3 Stable

**Comment by iota97** [comment]
Look vulkan render part of the scenario that is behind the camera on top of it all (Player, ball and UI use a new depth texture so they are not affected). An example below.

Render pass:
![tex](https://user-images.githubusercontent.com/13517524/71402777-04da7c00-262e-11ea-9e0f-f710f0252ae3.png)

The mesh being rendered:
![mesh](https://user-images.githubusercontent.com/13517524/71402785-0a37c680-262e-11ea-8000-45fff18d0685.png)

One vertex position for reference:
![vertex](https://user-images.githubusercontent.com/13517524/71402787-0ad05d00-262e-11ea-8f16-4114fdb98555.png)

Vulkan vertex after raster:
![vulkan](https://user-images.githubusercontent.com/13517524/71402985-a2ce4680-262e-11ea-858a-5fb97a9dae82.png)

OpenGL vertex position (using OpenGL the mesh doesn't get rendered on screen)
![opengl](https://user-images.githubusercontent.com/13517524/71402786-0a37c680-262e-11ea-8af2-e94a009f80d3.png)

About the performance i get about 15 fps as well on both vulkan and opengl (linux) with a i5 6400 and a GTX 1060, the most active Syscall is "sceDisplaySetFrameBuf" taking 16 ms, i dunno if is expected or the game keep changing framebuffer or something.

Frame dump:
[fifaDump.zip](https://github.com/hrydgard/ppsspp/files/3997688/fifaDump.zip)

**Comment by unknownbrackets** [comment]
What FPS does it get on a real PSP?  There are plugins that can measure FPS.  15 FPS would be surprising, but I want to confirm if it should really be 30 FPS.

Did it used to work in a previous version of PPSSPP, or has this always happened?

-[Unknown]

**Comment by arnoldsecret** [comment]
From what I played the game back in the day, it did ran at 30fps. The game had some really bad performance issues even on older versions.

**Comment by LunaMoo** [comment]
As far as I checked graphics is fine and the FPS is not just incorrect fps, but it's running at half speed as well. I tried some hacks with my custom build and delaying the delay thread makes it run at ~ 28-30 fps(variable fps), which would likely mean it's a timing issue aka yet another case of PPSSPP running too fast is confusing the game.

 That hack is additionally delaying the result of sceKernelDelayThread by 6000us, but that's a completely made up value which accidentially improves some things, it's just a dirty hack I made trying to improve Resistance Retribution crashes, but it was still crashing in some places anyway and with lack of time I didn't investigated further.

**Comment by unknownbrackets** [comment]
If only one specific thread needs additional delays, it'd be useful to list out the syscalls it executes.  We could then make sure those have been timed - there's definitely a bunch that are incorrectly 0 cycles.

-[Unknown]

**Comment by iota97** [comment]
About the graphical issues might be related to the "stadium", the game by default select a random one, also its affected by the camera position.

Try to select "San Siro" and move down with the player to reproduce: you should see some 2D crowd getting over the field. (it happen to me on both android and linux with Vulkan).

**Comment by meowthed** [comment]
Closing this thread as gameplay speed matches real hardware, and as of the latest version, the related graphical bugs have been fixed.
PSVita footage - https://www.youtube.com/watch?v=DOSrAi__Q-0
