### ISSUE TITLE
#android# speed ingame problem

### ISSUE THREAD

**Issue by farouk327** [hrydgard/ppsspp#12522]
Hi noble dev grateful for the emulator so far🙆.
I tried popolocrois ( ID:ULUS-10018 ) with every possible configurations ( when sound chopped the frameskipping make the game unplayable) but the game keep lagging and the speed slow down sooo much ( 11/30  64%) the same with spiderman 3

**Comment by hrydgard** [comment]
What device? Some are just not strong enough.

For popolocrois there are also a few settings that might help such as secondary texture cache, and definitely turn off texture scaling.

**Comment by farouk327** [comment]
Oh my bad
P1ma40
The phone is weak.
