### ISSUE TITLE
Arctic Adventures: Polar's Puzzles - NPUZ00114 graphic glitches

### ISSUE THREAD

**Issue by benderscruffy** [hrydgard/ppsspp#12529]
during gameplay the graphics are glitched
![arctic](https://user-images.githubusercontent.com/2696404/71447510-12951c00-276a-11ea-9d65-59d27474c65c.PNG)
GE dump
[NPUZ00114_0001.zip](https://github.com/hrydgard/ppsspp/files/4000557/NPUZ00114_0001.zip)

**Comment by hrydgard** [comment]
Wow, that's pretty wacky. Same in all backends I guess?

**Comment by Panderner** [comment]
After merging #12596 the emulator crashes when I booting the game

**Comment by Panderner** [comment]
But the game crash when I boot the game rather than Simulated UMD Delays
In order to get this game work change the I/O to Simulated UMD Delays

**Comment by Panderner** [comment]
It seems the graphics are fixed in latest build I've tested OpenGL it does happens in all backends?

**Comment by hrydgard** [comment]
Right, we should close this.

**Comment by Gamemulatorer** [comment]
> But the game crash when I boot the game rather than Simulated UMD Delays
> In order to get this game work change the I/O to Simulated UMD Delays
> And now the graphics fixed

No need to set the I/O Timing Method to Simulated UMD Delays to this game as I tested as of now the game is ok.

**Comment by unknownbrackets** [comment]
There's a hack in compat.ini forcing simulate umd delays for this game, even though it's a PSN game.

-[Unknown]
