### ISSUE TITLE
[FIXED][Android] Game sometimes freezes for a sec and continues then freezes again.

### ISSUE THREAD

**Issue by FalconTRM** [hrydgard/ppsspp#12521]
### What happens?
It sometimes freezes then continue on and freezes again.

### What *should* happen?
Smooth gameplay

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Xiaomi Redmi Note 8, Android, Android 9(MIUI Global 10.3.4), PPSSP 1.9.2/1.9.4, Vulkan(

My old phone which is Huawei GR5 2016 works properly(1.9.2) but when I play Mobile Suit Gundam: Gundam vs. Gundam Next... But when I used my new phone Xiaomi Redmi Note 8(1.9.2/1.9.4), it sometimes freezes for a sexond and continues and freezes again. I tried copying the settings from my old phone to my new phone but still I am having the same issue but it almost fixed the issue when I enabled Retain Changed Textures, it lessens the chances on doing it again, I noticed that my frame lowers(from 60 to about 40+) right after the freezing stops... Please help me, I can't play the game properly now...

**Comment by LunaMoo** [comment]
Disable texture scaling if you have it on.

**Comment by FalconTRM** [comment]
> Disable texture scaling if you have it on.

I already did, but still it didn't do anything...

**Comment by FalconTRM** [comment]
Fixed the Issue, I just have to change the I/O Timing Method from Fast to Host.

**Comment by unknownbrackets** [comment]
That probably indicates you have slow storage (maybe a slow microSD card?)  Note that Host makes bugs less consistent - you might encounter a bug that only happens 10% of the time, and doesn't happen for anyone else.

-[Unknown]
