### ISSUE TITLE
Is PPSSPP Support Android 9?

### ISSUE THREAD

**Issue by Exiasa** [hrydgard/ppsspp#12520]
When I Try Play Some Game Such Like GundamBattleUniverse or NarutoNinja Impact or HackLink In Android Ver 7 is very perfect with OpenGL Backend.....
But When I Update to Android 9 The Game was able to start but in Randomly Crash And ForceClose with OpenGL...Some Game able to fix the crash using Vulkan but it GraphicalBugs...
My iso Not Corrupted At all........

Redmi Note 4
Android 9
Octa2ghz

I Hope U understand what i say

**Comment by Panderner** [comment]
Yes. Other phones running Android 9 pie works well, but your phone Is still android nougat. Are you using custom rom?

**Comment by Exiasa** [comment]
yes it a cusrom..so bug of rom?

**Comment by Panderner** [comment]
> yes it a cusrom..so bug of rom?

Lineage os?

**Comment by Exiasa** [comment]
umm nope HavocOS....AOSP base

**Comment by hrydgard** [comment]
It supports all android versions, but custom roms can do anything so you're really on your own there...
