### ISSUE TITLE
FPS go to 0 then game corrupts or crashes after a while

### ISSUE THREAD

**Issue by mcabel** [hrydgard/ppsspp#12527]
### What happens?
FPS go to 0 then game corrupts or crashes after a while.

Generally, after the game session becomes "corrupted" one is able to "do things ingame" until before a screen transition happens. A screen transition will fully  send the game session to 0 fps. In most cases the audio is still present, so it might not be a "full" crash.

The easiest way to notice "early" that the bug happened is to try and save the game to the memstick on an normal ingame save point. The save pictures will look like white boxes, instead of game art. When the bug is noticed earlier, it is possible to play through several screen transitions, until eventually, it will hang during one of them.

If the issue is noticed early, it is possible to bypass it by saving into the memstick, and reloading normally. If the bug has been there for a while in that session, the screen "transition" required for the saving menu will hang the game, in a similar manner to any other screen transition.

It has been noticed with Persona 1 and Y's Ys I & II Chronicles, but it does not seem to be game specific.

It can be reproduced through a savestate. Load the savestate and create one or more save files ingame if needed, by pressing start>files>save. After checking the same menu again, all save files will look like white boxes. To trigger the hanging, do screen transitions, and it will happen sooner or later.

Savestates and clean save files were both uploaded

![ULUS10547_00001](https://user-images.githubusercontent.com/10392829/71434717-abb52b80-26b3-11ea-8265-e82a8c8957c3.jpg)

### What *should* happen?
No hang or gameplay corruption.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
v1.9.3-148-g608d71641 windows-amd64 (Have noticed this as earlier as in October versions; Haven't used ppsspp for a while before then, so can't trace if it happened earlier than that)
Windows 8.1 
Processor	Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz, 2401 Mhz 
 NVIDIA GeForce GT 755M
-have seen this in both vulkan or opengl iirc

![ULUS10547_00000](https://user-images.githubusercontent.com/10392829/71434555-13b74200-26b3-11ea-8ec2-e739cc20e4b7.jpg)
[PPSSPP_STATE.zip](https://github.com/hrydgard/ppsspp/files/3999759/PPSSPP_STATE.zip)
[ULUS105470006.zip](https://github.com/hrydgard/ppsspp/files/3999794/ULUS105470006.zip)

![Capture](https://user-images.githubusercontent.com/10392829/71435926-19178b00-26b9-11ea-970c-a1b0eb90d665.JPG)
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/3999864/ppsspplog.zip)

**Comment by unknownbrackets** [comment]
Does this happen in older versions of PPSSPP (like 1.8.x, etc.)?  It's possible this could be a regression.

-[Unknown]

**Comment by mcabel** [comment]
@unknownbrackets I have not been able to trigger it in ppsspp-v1.8.0-645-ge05193a67-windows-amd64 (savestate not compatible; normal game save may take a while to trigger the bug if it would be present). I will play a longer session and post back if I see anything (or not).

**Comment by unknownbrackets** [comment]
It looks like it's running out of kernel ram, maybe something about this access pattern is preventing some helper thread from getting its memory freed...

If yes, it would work fine in v1.9.3-27-g83c349a92 but not in future git builds.

-[Unknown]

**Comment by mcabel** [comment]
So far, 6+ hours game session with version ppsspp-v1.8.0-645-ge05193a67-windows-amd64, and have not encountered the bug again, @unknownbrackets

**Comment by hrydgard** [comment]
Okay so I guess it ends up just creating new async IO threads but never deleting them? Their call stack allocations would slowly eat kernel RAM...  So there's a path that I/O gets ended or cancelled but not the thread.

**Comment by unknownbrackets** [comment]
Seems there's a bug in saving state.  Without saving state, and after fixing that, I'm not seeing any thread buildup.

Note: the bug was not in loading a save state, but in saving.  So if you saved state, went somewhere, saved state again, that's what made the problem worse.

-[Unknown]

**Comment by hrydgard** [comment]
Please test again with the latest build, this issue should now be fixed.

**Comment by mcabel** [comment]
ok, I'll do another long play test and post later

**Comment by mcabel** [comment]
during 6+ hour, using a combination of regular save, savestates and rewind on various ocasions, the issue did **NOT** appear, using version v1.9.3-164-g0a5ec4838-windows-amd64.

**Comment by unknownbrackets** [comment]
Great, thanks for reporting.
