### ISSUE TITLE
Archlinux no sound

### ISSUE THREAD

**Issue by suryadana** [hrydgard/ppsspp#12528]
### What happens?

ALSA lib dlmisc.c:283:(snd_dlobj_cache_get0) Cannot open shared library /usr/lib32/alsa-lib/libasound_module_pcm_pulse.so ((null): libpulse.so.0: cannot open shared object file: No such file or directory)
E: /home/karen/Development/ppsspp/native/base/PCMain.cpp:631: E: Failed to open audio: ALSA: Couldn't open audio device: No such device or address

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

On desktop

**Comment by suryadana** [comment]
also force close on connect to adhoc

00:17:841 user_main    W[NET]: HLE/sceNet.cpp:119 sceNetInit(poolsize=131072, calloutpri=32, calloutstack=0, netintrpri=32, netintrstack=0) at 0887cdec
00:17:877 user_main    I[NET]: HLE/sceNetAdhoc.cpp:163 sceNetAdhocInit() at 0887d030
00:17:877 user_main    W[KERNEL]: HLE/sceKernelThread.cpp:2164 sceKernelCreateThread(name=AdhocThread): unsupported options parameter 00001000
00:17:877 user_main    I[KERNEL]: HLE/sceKernelThread.cpp:2173 312=sceNetAdhocInit()
00:17:907 user_main    I[NET]: HLE/sceNetAdhoc.cpp:189 sceNetAdhocctlInit(8192, 48, 08ab3a3c) at 0887cfbc
00:18:131 CsePspAtrac3 I[NET]: HLE/proAdhoc.cpp:1003 FriendFinder: Begin of Friend Finder Thread
00:18:159 user_main    W[NET]: HLE/sceNetAdhoc.cpp:1029 UNTESTED sceNetAdhocctlAddHandler(887c36c, 0): added handler 0
00:18:206 user_main    I[NET]: HLE/sceNetAdhoc.cpp:869 sceNetAdhocctlScan() at 08830e7c

**Comment by iota97** [comment]
You are missing libpulse.so.0, could you try installing pulse with:

`sudo pacman -Sy pulseaudio`

**Comment by suryadana** [comment]
> You are missing libpulse.so.0, could you try installing pulse with:
> 
> `sudo pacman -Sy pulseaudio`

i already install pulseaudio

$pulseaudio --version
pulseaudio 13.0-dirty

and also library already exists

/usr/lib/libpulse.so.0
/usr/lib/libpulse.so.0.21.1
/usr/lib32/alsa-lib/libpulse.so.0

**Comment by unknownbrackets** [comment]
Are you using a 32-bit version of PPSSPP?  I don't recommend that.  Asking based on `/usr/lib32/alsa-lib/libasound_module_pcm_pulse.so`.

It seems like your 64 bit and 32 bit libpulse.so.0 libraries are in different folders, which implies to me that you may not have a 32-bit pulseaudio installed, or something.

I'd recommend compiling PPSSPP for 64-bit, though.

This seems less like a PPSSPP problem and more like an SDL problem.  PPSSPP is trying to open audio on your device using SDL, and SDL is failing to open the audio.  There's probably nothing we can change in PPSSPP's source code to make this work.

-[Unknown]

**Comment by iota97** [comment]
If 32 bit library is missing try:

`sudo pacman -Sy lib32-libpulse`

Does PPSSPP from the repo work fine? (this is 64 bit as Arch doesn't provide 32 bit package beside library)

`sudo pacman -Sy ppsspp`

**Comment by suryadana** [comment]
i am download the ppsspp 64bit and its work well. Thank you for support.
