### ISSUE TITLE
MGS Peace Walker: Sniper rifle camera stuck when zoomed (using 60 FPS cheat)

### ISSUE THREAD

**Issue by Quick-Brown-Fox-147** [hrydgard/ppsspp#12525]
Hello everyone, I am playing Metal Gear Solid Peace Walker and I am having problem moving camera when I use sniper rifle zoom. The problem only occurs when I enable 60 FPS or 30 FPS cheat code.

(In picture 1) When I use any sniper rifle (except for PTRD1941 & PTRS1941) and try (1×zoom) or (2×zoom), everything's fine. Under action type control I press L to zoom and D-pad to move camera to aim. 
![image](https://user-images.githubusercontent.com/59200783/71416858-9d074e00-268c-11ea-9595-f3d101b60c30.png)
But when I try (3×zoom), the camera no longer moves (in zoomed state). I press D-pad but the camera is stuck(In picture 2). 
![image](https://user-images.githubusercontent.com/59200783/71416899-c4f6b180-268c-11ea-8779-280eb1fa7281.png)
Moreover, when I try to use PTRD1941 & PTRS1941(the best sniper rifles in game), the camera at zoomed stage doesn't move at all. I mean it does not move at (1×zoom) or (2×zoom) or (3×zoom) mode and no matter what zoom type I try. (In picture 3)
![image](https://user-images.githubusercontent.com/59200783/71416914-d6d85480-268c-11ea-8b79-f64f6fa20b3f.png)
I am playing at -
Windows 10 pro 64 bit, i7 8700k, 16 gb ram, Intel(R) UHD Graphics 630
ppsspp- v1.9.3, Settings: Backend-Direct 3D11
The followings are the 60 FPS and 30 FPS cheat code I tried and could find on internet (ppsspp forum and others)

_C1 60FPS v4 [Always]
_L 0xE0120000 0x10071AF0
_L 0x20071AF0 0x00000000//Something,a
_L 0x20071AF8 0x0A21C6D6//Something,b
_L 0x20071B58 0x0A21C6DA//Something,d
_L 0x20071BA4 0x00000000//Speed1,a
_L 0x20071BAC 0x0A21C734//Speed1,b
_L 0x20071CD0 0x00000000//Speed1,c
_L 0x20071E2C 0x00000000//Speed2,a
_L 0x20071E34 0x0A21C7AF//Speed2,b
_L 0x20071EBC 0x00000000//Speed2,c
_L 0x20071B94 0x24040000//Speed3,a
_L 0x203E752C 0x00000000//Speed3,b
_L 0x2007A41C 0x00000000//FPS,a
_L 0x2007A424 0x0A21E91C//FPS,b
_L 0x2007A470 0x0A21E917//FPS,c
_L 0x20091A28 0x3C013EAB//OceanMovement
_L 0x201F298C 0x3C013EB7//TextSpeed,a
_L 0x201F2990 0x3421C1BD//TextSpeed,b
_L 0x2020F8A8 0x3C013EAB//ThrowingWeaponsTimer
_L 0xE0017540 0x0085F2D0//Cutscene,cond
_L 0x2085F2D0 0x2403000A//CutsceneSync60Fix
_L 0xE0043421 0x00861C4A//MonsterIsland
_L 0x20861C44 0x3C013C93//PooyanBalloon1,a
_L 0x20861C48 0x3421E93F//PooyanBalloon1,b
_L 0x20863A8C 0x3C013C93//PooyanBalloon2,a
_L 0x20863A90 0x3421E93F//PooyanBalloon2,b

_C0 60FPS v3 [Ingame only]
_L 0xE00F0003 0x0055DE04
_L 0x2055DE04 0x00000001
_L 0x203E7540 0x00000005
_L 0x203E7524 0x3F800000
_L 0x203E7528 0x3F800000
_L 0x203E752C 0x00000000
_L 0x203E753C 0x00000001
_L 0x203E7FD4 0x00000000
_L 0x203E85D4 0x00000000
_L 0x203E7520 0x40AE38E4
_L 0x20449C54 0x3F8B7584
_L 0x20449C64 0x0000003C
_L 0x20091A28 0x3C013EAB//OceanMovement
_L 0x201F298C 0x3C013EB7//TextSpeed,a
_L 0x201F2990 0x3421C1BD//TextSpeed,b
_L 0x2020F8A8 0x3C013EAB//ThrowingWeaponsTimer
_L 0xE0043421 0x00861C4A//MonsterIsland
_L 0x20861C44 0x3C013C93//PooyanBalloon1,a
_L 0x20861C48 0x3421E93F//PooyanBalloon1,b
_L 0x20863A8C 0x3C013C93//PooyanBalloon2,a
_L 0x20863A90 0x3421E93F//PooyanBalloon2,b

_C0 30FPS v4
_L 0xE009C6C6 0x10071AF0
_L 0x20071AF0 0x0A21C6C6//Something,a
_L 0x20071BA4 0x0A21C6F5//Speed1,a
_L 0x20071B94 0x24040001//Speed3,a
_L 0x203E752C 0x00000001//Speed3,b
_L 0x2007A41C 0x0A21E911//FPS,a
_L 0x20091A28 0x3C013F2B//OceanMovement
_L 0x201F298C 0x3C013F37//TextSpeed,a
_L 0x201F2990 0x3421C1BD//TextSpeed,b
_L 0x2020F8A8 0x3C013F2B//ThrowingWeaponsTimer
_L 0xE0043421 0x00861C4A//MonsterIsland
_L 0x20861C44 0x3C013D13//PooyanBalloon1,a
_L 0x20861C48 0x3421E93F//PooyanBalloon1,b
_L 0x20863A8C 0x3C013D13//PooyanBalloon2,a
_L 0x20863A90 0x3421E93F//PooyanBalloon2,b

_C0 20/30 FPS v4 [Default]
_L 0xE0130009 0x10071AF0
_L 0x20071AF0 0x10830009//Something,a
_L 0x20071AF8 0x14400017//Something,b
_L 0x20071B00 0x1082000B//Something,c
_L 0x20071B58 0x10800003//Something,d
_L 0x20071BA4 0x1205000B//Speed1,a
_L 0x20071BAC 0x14400048//Speed1,b
_L 0x20071CD0 0x1600FFBD//Speed1,c
_L 0x20071E2C 0x10650012//Speed2,a
_L 0x20071E34 0x14400021//Speed2,b
_L 0x20071EBC 0x1460FFE4//Speed2,c
_L 0x20071B94 0xAC44752C//Speed3,a
_L 0x203E752C 0x00000002//Speed3,b
_L 0x2007A41C 0x10830009//FPS,a
_L 0x2007A424 0x14400012//FPS,b
_L 0x2007A470 0x1080FFFA//FPS,c
_L 0x20091A28 0x3C013F80//OceanMovement
_L 0x201F298C 0x3C013F89//TextSpeed,a
_L 0x201F2990 0x3421D14E//TextSpeed,b
_L 0x2020F8A8 0x3C013F80//ThrowingWeaponsTimer

_C0 Force 60 FPS beta
_L 0x2055DE04 0x00000001
_L 0x203E7540 0x00000005
_L 0x203E7524 0x3F800000

_C0 Force 30 FPS beta
_L 0x2055DE04 0x00000002
_L 0x203E7540 0x0000000A
_L 0x203E7524 0x40000000

Thanks in advance for your help.

**Comment by LunaMoo** [comment]
This place is an issue tracker of an emulator, if you want support with patches, you should ask their author. FPS patches are common to break timing and physics which both occurs in those patches you're using, it's no wonder they break more stuff. Closing since it happens with a generally game breaking hack and doesn't without.
