### ISSUE TITLE
Managing multiple audio devices

### ISSUE THREAD

**Issue by vnctdj** [hrydgard/ppsspp#12536]
I have 2 audio devices : an internal laptop sound card / chipset + an external USB DAC.
The "Device" setting in "Audio" works well, even "Auto" does the right thing: it chooses the DAC (why? maybe just because it's the first one in the list ?)

### What happens?
The "Switch on new audio device" setting is broken:
When enabled, no matter which value has been set for the "Device" setting, the used audio device is the internal one... unless I touch the "Device" setting each time I launch PPSSPP!

### What *should* happen?
At launch, PPSSPP should use the audio device set in the "Device" setting.
No switching should happen given that I haven't connected/disconnected a device.

### What hardware, operating system, and PPSSPP version? On desktop, GPU matters for graphical issues.
**OS:** Debian GNU/Linux bullseye/sid x86_64
**Kernel:** 5.3.0-2-amd64
**WM:** i3
**CPU:** Intel i7-6700HQ (8) @ 3.500GHz
**GPU:** NVIDIA GeForce GTX 960M
**PPSSPP:** latest Git build, it doesn't matter

**Comment by unknownbrackets** [comment]
Maybe SDL is just notifying us about the USB device being "plugged in" shortly after we start listening for events?  That would cause us to always switch to it.

https://github.com/hrydgard/ppsspp/blob/0a5ec483825b6ad55568e66a50c5d014b9241c45/SDL/SDLMain.cpp#L913

Try making that line:

```c++
					// Don't start auto switching for a second, because some devices init on start.
					bool doAutoSwitch = g_Config.bAutoAudioDevice && framecount > 60;
					if (doAutoSwitch || g_Config.sAudioDevice == name) {
```

Does that help?

-[Unknown]

**Comment by vnctdj** [comment]
Perfect! This change fixes the issue, thanks :)
Should I create a pull request for it, as it is?

**Comment by unknownbrackets** [comment]
Sure.  I went ahead and created one.

-[Unknown]

**Comment by vnctdj** [comment]
Thanks again @unknownbrackets!
