### ISSUE TITLE
Iron Man (USA) (En,Fr,Es) critical error (block transfer negative extent)

### ISSUE THREAD

**Issue by benderscruffy** [hrydgard/ppsspp#12531]
during the intro a critical error appears
![ironman](https://user-images.githubusercontent.com/2696404/71474816-357e0980-2818-11ea-9777-ac9c26f07309.PNG)
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/4002416/ppsspplog.zip)

**Comment by unknownbrackets** [comment]
```
Creating FBO for 04000000 : 512 x 272 x 0
Creating FBO for 04088000 : 512 x 272 x 3

Est: 04044000 V: 480x272, R: 512x272, S: 512x272, STR: 512, THR:0, Z:00000000 = 512x272
Est: 04088000 V: 480x272, R: 512x272, S: 480x272, STR: 512, THR:1, Z:44044000 = 512x272

Block transfer: 04044000/200 -> 04088780/400, 64x272x2 (64,0)->(0,0)
Inter-buffer block transfer 04044000 -> 04088780
srcrect offset x (128) + extent (-896) > width (1024)

Block transfer: 04044000/200 -> 04088780/400, 64x272x2 (128,0)->(0,0)
srcrect offset x (256) + extent (-896) > width (1024)
```

04088780/400 should be 04088000 + 480 pixels.  We're copying 64 pixels at 16-bit, so 32 pixels into the space between 480 and 512.  That means `srcX2 - srcX1` became -896, I guess.  Not sure why, though.

-[Unknown]
