### ISSUE TITLE
Could provide a crt-shader without shaking scanline?

### ISSUE THREAD

**Issue by Oend** [hrydgard/ppsspp#12546]
CRT shader looks pretty good, but when I don't move, I can see scanlines are shaking or move or something (not sure how to say it) on static screen, this breaks the enjoying for beautiful static image.

Or could you tell me how to add crt-shader from RetroArch? so I can add it by myself.

very appreciative for help :) :) :)

**Comment by Oend** [comment]
https://forums.ppsspp.org/showthread.php?tid=18926
ok, so I copy crt-pi.glsl from RetroArch and rename it fsh, it works but looks very different with ppsspp-crt, ppsspp-crt looks much better.....much much better.....

**Comment by Oend** [comment]
Just need to remove that shaking it will be perfect......

**Comment by Oend** [comment]
ok I'm wrong, that's not crt-pi that I add, that's scanlines.fsh from ppsspp-self
For crt-pi from RetroArch, I edit ppsspp-shader-ini, add it

[CRT-PI]
Name=CRT-PI
Author=NO
Fragment=crt-pi.fsh
Vertex=fxaa.vsh

After ppsspp load it, nothing changes, looks this way doesn't work

**Comment by iota97** [comment]
There are 2 CTR shader in PPSSPP, only one (ctr.fsh) have any effect that change over time, if you want to remove those effect:

Open the .fsh file with a text editor such as notepad or notepad++
Now look at the line that mention u_time.x:

Remove u_time.x * 0.5 will remove the like shaking over time, or you may just want to change the 0.5 to other value to change the speed of the effect instead:

`  int vPos = int( ( v_texcoord0.y + u_time.x * 0.5 ) * 272.0 );`

The other line controll the "black shadow" passing behind:
```
float rollbar = sin( ( v_texcoord0.y + u_time.x ) * 4.0 );
gl_FragColor.rgba = c + (rollbar * 0.02);
```

Here as well you may just multiply u_time.x to change it's speed, to remove the effect instead just remove the `+ (rollbar * 0.02)` from the next one.

Here the code without any effect changing overtime:
```
// Retro (CRT) shader, created to use in PPSSPP.

#ifdef GL_ES
precision mediump float;
precision mediump int;
#endif

uniform sampler2D sampler0;
varying vec2 v_texcoord0;
uniform vec4 u_time;

void main()
{
    // scanlines
    int vPos = int( ( v_texcoord0.y ) * 272.0 );
    float line_intensity = mod( float(vPos), 2.0 );
    
    // color shift
    float off = line_intensity * 0.0005;
    vec2 shift = vec2( off, 0 );
    
    // shift R and G channels to simulate NTSC color bleed
    vec2 colorShift = vec2( 0.001, 0 );
    float r = texture2D( sampler0, v_texcoord0 + colorShift + shift ).x;
    float g = texture2D( sampler0, v_texcoord0 - colorShift + shift ).y;
    float b = texture2D( sampler0, v_texcoord0 ).z;
    
    vec4 c = vec4( r, g * 0.99, b, 1.0 ) * clamp( line_intensity, 0.85, 1.0 );
    
    gl_FragColor.rgba = c;
}
```

About shader from other program they hardly work without any edit.

**Comment by Oend** [comment]
@iota97
amazing! now it‘s totally perfect! thanks thanks thanks thanks thanks all the thanks to you iota97! you are best!
