### ISSUE TITLE
[Android][OpenGL&Vulkan][Not enough FPS] NARUTO Shippuden NARUTIMATE IMPACT (NPJH50435)

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#12544]
### What happens?
Not enough(stable) FPS.

### What *should* happen?
Work on stable FPS.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

PPSSPP Ver. : 1.9.3-164
OS: Android 9.0
DeviceName: SONY SO-02K / Xperia XZ1 Compact (Japan)
CPU: Snapdragon835 (Octa-core)
GPU: Adreno 540
Resolution: 720×1280
RAM: 4GB
ROM:32GB
ExternalStrage: microSDXC 512GB

I attached dump.
Please,check it.

[NPJH50435_0001.zip](https://github.com/hrydgard/ppsspp/files/4014878/NPJH50435_0001.zip)

**Comment by Panderner** [comment]
Have you lowered the psp resolution?

**Comment by nassau-tk** [comment]
No,I don't!!

So,I tested low resolution (x1).
It became stable FPS more than x3 to x5.
But,Gose down FPS when play voice sound.

The framedump attached for reference.
*Lowresolution (x1) ver.
[NPJH50435_0002.zip](https://github.com/hrydgard/ppsspp/files/4018457/NPJH50435_0002.zip)

**Comment by unknownbrackets** [comment]
This game draws things that are far away first, so it's a bit heavier on the fill rate than some games might be.  I would generally expect an 835 to handle relatively well, though.

Have you tried "sustained performance mode"?  Sounds and voices shouldn't be that expensive to performance, as long as you're using jit.

-[Unknown]

**Comment by nassau-tk** [comment]
Yes,I did it.
But,no change both performance.

**Comment by unknownbrackets** [comment]
About the slow down when voices play:
Just to be sure, can you try changing SeparateSASThread to False instead of True in ppsspp.ini?  I don't think this will help, but I just want to eliminate it as a possibility.

-[Unknown]

**Comment by Emulatorer** [comment]
@unknownbrackets  what's the use of SeparateSASThread?
I tried it to change from true - false and it give some of my games a smooth performance 🙂

**Comment by hrydgard** [comment]
@Emulatorer , that's kind of surprising - having it on is supposed to be a minor speed boost by allowing work on more cores. But maybe it's counterproductive in some situations.  What games are you playing on what device that you notice a smoothness improvement on?

**Comment by Emulatorer** [comment]
I tried it on Tekken6, PS Collection and NFS Underground.
My Phone Specs 
[DevCheck-20200318-0823.txt](https://github.com/hrydgard/ppsspp/files/4346354/DevCheck-20200318-0823.txt)

**Comment by nassau-tk** [comment]
I can't feel change anything in my case.

Tested 4-Roms below.

NARUTO Shippuden NARUTIMATE IMPACT
(NPJH50435) #12544

The KING of Fighters Portable '94-'98 Chapter of Orochi 
(NPJH50258) #12543

MahjongFightClub (ULJM05002)
&MahjongFightClub ZenkokuTaisenBan (ULJM05163) #12524

Pursuit Force (ULJM05097) #12335

**Comment by Emulatorer** [comment]
@nassau-tk try my settings in Naruto Shippuden Impact just extract this file and move to PSP > SYSTEM 👍
[System.zip](https://github.com/hrydgard/ppsspp/files/4352879/System.zip)

**Comment by nassau-tk** [comment]
>Emulatorer

Yes,I tried it...But,The game can't working.
Ahahaha!! I don't know why?
Thank your kind!!👍

**Comment by unknownbrackets** [comment]
The best I've been able to come up with is that maybe (?) this is a problem in a specific scenario, which might be more common (?) than I expected:
 * If the cost of thread switching/locks/cond vars is pretty non-trivial.
 * If the game mixes SAS and then has no other useful work to do until it completes (whether because it finished drawing, or is waiting to catch up on cycles consumed by drawing, etc.)
 * If there's overhead from a different core accessing the same memory.

That seems like a recipe for offloading SAS to just add overhead (memory caches + thread handling), so maybe that's what's happening here?  Or maybe it's just competing for threads and ousting out something more important?

But it seems it didn't help in this specific case.

-[Unknown]

**Comment by Gamemulatorer** [comment]
> > Emulatorer
> 
> Yes,I tried it...But,The game can't working.
> Ahahaha!! I don't know why?
> Thank your kind!!

I understand now why my settings doesb work on you because it's opengl issue on adreno gpu see  #12847

**Comment by Panderner** [comment]
It's seems it uses Block Transfers to eliminate black boxes inside character icon and to fix Glitching effects during using ninja dash. but it has lots of slowdowns during gameplay on most android devices.

**Comment by nassau-tk** [comment]
um...

It's will not happen on Galaxy S20.(SD865+RAM12GB)

**Comment by Panderner** [comment]
Umm there's some framerate fixes on low-end devices for ultimate ninja impact by turning off simulate block transfer effects or switching the mode to skip buffer effects.

Skip buffer effects:
![Screenshot_2020-11-11-23-36-34-30_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/98831714-e44e2700-2476-11eb-8288-d732bee41f88.png)

Buffered rendering:
![Screenshot_2020-11-11-23-36-43-22_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/98831809-02b42280-2477-11eb-8543-e2a4c0e954a0.png)
.

**Comment by Panderner** [comment]
@Gamemulatorer @nassau-tk try this modified compat.ini file with BlockTransferAllowCreateFB for this game from #13821

**Comment by unknownbrackets** [comment]
Does separate SAS thread still make a difference?  Ideally, without the above change.

If so, does it help all of these games the same way, or are some helped more than others?

Persona 3: 173
Kingdom Hearts / Dissidia: 327 - plus
Wipeout Pure: 900

The number is basically how complex the SAS operations it does are.

-[Unknown]

**Comment by Panderner** [comment]
Where can I check the separate SAS thread difference?

**Comment by unknownbrackets** [comment]
It's not a visible option.  You have to edit ppsspp.ini directly.

-[Unknown]

**Comment by Panderner** [comment]
Disabling separate SAS thread has no difference for performance but how can I check SAS operations?

**Comment by unknownbrackets** [comment]
Well, if it makes no difference for each of those games then what I was thinking won't help.  I was reacting to the problem of it making a difference (which is what this issue was earlier about.)

If it does make a difference, but for example doesn't in Wipeout Pure, that might indicate I could use a threshold to only use the thread in certain situations.

-[Unknown]

**Comment by Gamemulatorer** [comment]
Simulate Block Transfer Effects is enable with 3X rendering resolution, native device resolution (1080p)
with Natural Color (no bloom) and PSP Color post processing shaders.
![Screenshot_2021-05-18-00-18-41-374_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/118524777-1b2c2f00-b771-11eb-86d2-0f3e9a8468a8.jpg)
![Screenshot_2021-05-18-00-18-49-627_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/118524797-1f584c80-b771-11eb-8bf6-6df6893dfe2c.jpg)
My phone is Redmi Note 9 tried and tested both OpenGL and Vulkan this game is running smooth using ppsspp latest version.

**Comment by Gamemulatorer** [comment]
This issue is related/duplicate to 10927

**Comment by XiaomiRedmi9** [comment]
@nassau-tk any updates?

**Comment by nassau-tk** [comment]
> @nassau-tk any updates?

fm....I don't know about it.
And, You should not talk about update per issue.

**Comment by XiaomiRedmi9** [comment]
> > @nassau-tk any updates?
> 
> fm....I don't know about it.
> And, You should not talk about update per issue.

I'm sorry master I'm just hoping that your issue will fixed on the latest build, I'm sorry again master 👺

**Comment by nassau-tk** [comment]
I'm the same feeling as you, too. :grin:

**Comment by Gamemulatorer** [comment]
This might improve now

**Comment by Gamemulatorer** [comment]
Safe to close this now?

**Comment by unknownbrackets** [comment]
Okay, let's close assuming that the thing to make it create a framebuffer instead is working out.

-[Unknown]
