### ISSUE TITLE
Permission to add PPSSPP to Steam as free DLC for RetroArch

### ISSUE THREAD

**Issue by twinaphex** [hrydgard/ppsspp#12562]
Hi @hrydgard and @unknownbrackets,

we would like to seek your permission to include PPSSPP as a core as free DLC for RetroArch on Steam.

The user would have to manually install this, it would be freely made available.

If there's anything you are unsure of or are hesitant about, don't hesitate to bring it to our attention. We will always go with whatever you decide.

**Comment by hrydgard** [comment]
I guess I'm alright with it, as long as it's indeed a free DLC.

**Comment by twinaphex** [comment]
Hi, just a status update that this finally happened -

https://store.steampowered.com/app/1234350/RetroArch__PPSSPP/

Lastly, we'd really appreciate if we could work further together to improve the core so that users get a good user experience out of it. There are still some longstanding issues to do with it, and it'd be great to have them resolved.
