### ISSUE TITLE
[Windows]PPSSPP Gold Icon Smaller

### ISSUE THREAD

**Issue by HiImBrala** [hrydgard/ppsspp#12560]
Not really bug but the icon of executables are way smaller than original PPSSPP Icon.Would be nice to have same size icons

**Comment by Panderner** [comment]
Did you see the image?

**Comment by LunaMoo** [comment]
On Windows we use up to 256x256 for regular and up to 128x128 for gold version icons. If you want to make them even just add 256x256 to ppsspp_gold.ico, through I don't get why would anyone want to use gold on win unless have prefference for that color and building it himself. Hope you do understand it's just a form of donation, regular is exactly same and as an addition also has buildbot for latest changes.

 Either way pull requests are welcome, there's an 512x512 icon in source assets that can be used to generate that missing 256x256 one, just nobody cared.

**Comment by HiImBrala** [comment]
> On Windows we use up to 256x256 for regular and up to 128x128 for gold version icons. If you want to make them even just add 256x256 to ppsspp_gold.ico, through I don't get why would anyone want to use gold on win unless have prefference for that color and building it himself. Hope you do understand it's just a form of donation, regular is exactly same and as an addition also has buildbot for latest changes.
> 
> Either way pull requests are welcome, there's an 512x512 icon in source assets that can be used to generate that missing 256x256 one, just nobody cared.

If nobody wants i could make it normal size.Since i care

**Comment by hrydgard** [comment]
I'll fix it soon.

**Comment by LunaMoo** [comment]
Fixed by #12564
