### ISSUE TITLE
Ridge Racer can't be at MAX [PC,Android]

### ISSUE THREAD

**Issue by ghost** [hrydgard/ppsspp#12561]
### What happens?
Ridge Racer can't go 60/60 on any device.Tried on my friend PC,mine PC and my Phone

### What *should* happen?
Game should run maybe 55fps but not 40

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Using D3D9 and D3D11,on phone OpenGL.

Game won't run at MAX on buffered rendering and i think this is bug that can be repaired

**Comment by Panderner** [comment]
Do you have a fast pc and phone?

**Comment by unknownbrackets** [comment]
It's able to run at 60 fps on my device.  Have you tried reducing your settings?  What specs does your PC have?

-[Unknown]

**Comment by HiImBrala** [comment]
I have laptop windows 8.1 pro build 9600 CPU:Intel N3520 4-core 4gb ram D3D11 and D3D9 and my friend has windows 10,8gb RAM,Intel(i don't remember the name since im not always at his place due to school)8 core.Using 2x Rendering WITHOUT postprocessing shader.Everything else is stock settings

**Comment by Panderner** [comment]
@HiImBrala what is your phone are you using?

**Comment by HiImBrala** [comment]
> @HiImBrala what is your phone are you using?

Xiaomi Redmi 6

**Comment by unknownbrackets** [comment]
We're always working on performance, but the CPUs/GPUs involved here aren't very powerful.  Since the original reporter has deleted their account, I'm going to close this issue.  We'll continue working on ways to speed up this game and others like it.

-[Unknown]
