### ISSUE TITLE
[Android][OpenGL&Vulkan][Crash&Freeze] Work v.1.9.3-189==> Crash v.1.9.3-204 & 208

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#12571]
### What happens?
Not work on v.1.9.3-204 & 208 below games.
*Start crash.
*v.1.9.3-189 is working.

Muso Orochi (ULJM05314)
Muso Orochi Maou Sairin (ULJM05402)
GOD EATER (ULJS00237)
GOD EATER 2 (NPJH50832)
GOD EATER BURST (NPJH50352)
GOD EATER BURST Apend (ULJS00350)

Theese games are crash and freeze at start.
PPSSPP is not response any action.

### What *should* happen?
Working at collectly.
Like a v.1.9.3-189 or more.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

PPSSPP Ver. : 1.9.3-189  (Work)
                          1.9.3-204 & 208 (Not work)
OS: Android 9.0
DeviceName: SONY SO-02K / Xperia XZ1 Compact (Japan)
CPU: Snapdragon835 (Octa-core)
GPU: Adreno 540
Resolution: 720×1280
RAM: 4GB
ROM:32GB
ExternalStrage: microSDXC 512GB

**Comment by hrydgard** [comment]
Probably same as #12571 ?

**Comment by nassau-tk** [comment]
Yes,maybe!!

**Comment by nassau-tk** [comment]
Result : v.1.9.3-210

[Work]
Muso Orochi (ULJM05314)
Muso Orochi Maou Sairin (ULJM05402)
*Like a v.1.9.3-189

[Not work]
GOD EATER (ULJS00237)
GOD EATER 2 (NPJH50832)
GOD EATER BURST (NPJH50352)
GOD EATER BURST Apend (ULJS00350)
*It became to shutdown the PPSSPP.

**Comment by hrydgard** [comment]
Huh, I did not expect -210 (https://github.com/hrydgard/ppsspp/commit/c2e857775617e75306bcb98969dd06ee7d0feacb) to actually fix anything, but I guess that's good. We know the cause of the other ones now, some kind of fix is coming soon.
