### ISSUE TITLE
God Eater 2 - Crash on start. [Android/Windows]

### ISSUE THREAD

**Issue by Saramagrean** [hrydgard/ppsspp#12570]
### What happens?
God Eater 2 crash on start since v1.9.3-194-g42bfcc7fa.

### What *should* happen?
v1.9.3-189-g6d8ddb7a7 game can run normally.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
- WIndows 10 64 bit (i5-6200U/Intel HD Graphics 520)
- Huawei P9 Plus (Android 9.0/Kirin 955/Mali T-880)

**Comment by Saramagrean** [comment]
Logcat from Android. (PPSSPP v1.9.3-208-ge2845363e)
[ppsspp_android.zip](https://github.com/hrydgard/ppsspp/files/4052390/ppsspp_android.zip)

**Comment by unknownbrackets** [comment]
Looks like a crash trying to read an instruction from 0x84000000, which seems invalid.  Coming from `MIPSAnalyst::ScanForFunctions` during a `sceKernelLoadModule`.

-[Unknown]

**Comment by hrydgard** [comment]
Bizarre - the commits seem to point to the long filename fix... Should not be too hard to find what broke.

**Comment by Saramagrean** [comment]
The log on Windows is very huge size. So I just cut out some parts that I thought were necessary.

Log from Windows. (v1.9.3-194-g42bfcc7fa)
https://gist.github.com/Saramagrean/a5df530a5e9b146c75bb52b3048618dd
Log from Windows. (v1.9.3-208-ge2845363e)
https://gist.github.com/Saramagrean/a2f24a7af1a84b317c8551d8e7e85e9d

![GE2-Crash2](https://user-images.githubusercontent.com/26355472/72250114-730ecf00-362d-11ea-879b-1652ec0318dc.png)

**Comment by unknownbrackets** [comment]
If v1.9.3-194-g42bfcc7fa crashes, it has nothing to do with the long filename changes?

-[Unknown]

**Comment by Saramagrean** [comment]
Yes.

**Comment by hrydgard** [comment]
Oh, I misread the commit list then - must be the PRX decryption changes? Hm
