### ISSUE TITLE
MHFU Crash when trying to attach decorations

### ISSUE THREAD

**Issue by sailikhit123** [hrydgard/ppsspp#12577]
### What happens?
Recently, whenever I go to attach decorations to an armor piece or weapon, the game crashes.
Any solutions?

I'm running an HP Pavillion 630 with 6 gigs of RAM,
Here are the problems shown by PPSSPP -
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	PPSSPPWindows64.exe
  Application Version:	1.9.3.0
  Application Timestamp:	5d99f05d
  Fault Module Name:	StackHash_1e37
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	00000000
  Exception Code:	c0000005
  Exception Offset:	000000013ec926ee
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	1e37
  Additional Information 2:	1e373e69fff075aed81f57003e66ce10
  Additional Information 3:	9f0e
  Additional Information 4:	9f0e095f32a88249d7a2b7eca4e322ea

**Comment by hrydgard** [comment]
Any idea which was the first version where this started happening?

**Comment by sailikhit123** [comment]
To be honest I have no clue. This is my first experience with emulators in general. I'm pretty sure I'm running the latest version.

**Comment by hrydgard** [comment]
I mean, you could try some old builds from https://buildbot.orphis.net/ppsspp/ and see which is the first one that broke it. That will help us find the problem.

**Comment by iota97** [comment]
I can't reproduce any crash (on Linux or Android tho'), I wonder if is a corrupted ISO/Savedata.

What version of the game are you using: EU, USA, JP (or patched JP with english translation)?
Does that happen with every decoration/armor/weapon or with a specific one?
Have you used any cheats? Some of them get saved and will be enabled even after you disable them.
Also are you using data install?

**Comment by sailikhit123** [comment]
I'm using the USA version. Yes I am using cheats. Would simply deleting the Cheats folder do the trick? I have no experience in programming so any help is appreciated. The game crashes as soon as I access the attach decoration panel.

**Comment by Abbanon** [comment]
It's likely a specific cheat that's triggering it. 
Disable them one by one as you access the decoration crafting menu to figure out which one exactly is causing the issue. 
I have no issues on my end, and I'm cheat-less.

**Comment by iota97** [comment]
If that doesn't work it could also mean the cheat got saved in the savedata, some chat alter stats that are saved and could corrupt them. Could you also please try to replicate with other save (you should find a lot of complete save, so you don't need to replay all the game to the decoration, just backup your save before overwrite them).

**Comment by Gamemulatorer** [comment]
I can't reproduce this issue 🤔
![Screenshot_20200525-064315](https://user-images.githubusercontent.com/37603562/82766600-17621700-9e53-11ea-88b9-1a109cb06027.png)
Im not using cheats 🤷

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
