### ISSUE TITLE
does not work with steam controller

### ISSUE THREAD

**Issue by puddingepoch** [hrydgard/ppsspp#12581]
I bought a controller JUST FOR using this emulator and does not work...

The steam controller connects to android fine and is able to interact with the touch screen and other elements of android

However, this emulator and others are completely ignoring its controls... theyre pretty generic too so wtf?

**Comment by hrydgard** [comment]
If it doesn't work with other emulators either, it's clearly not PPSSPP's fault. Sorry it didn't work for you, but PPSSPP just listens to gamepad events from the OS. If the OS doesn't send the events, it can't work. If you get it to work with other apps but still not in PPSSPP, please reopen.
