### ISSUE TITLE
Touch Control Grid Draw is Broken

### ISSUE THREAD

**Issue by DavidTamas** [hrydgard/ppsspp#12587]
It draws the lines next to each other diagonally instead of forming a grid.
Using v1.9.3-225-gdd1de41db on Win10.

![Névtelen](https://user-images.githubusercontent.com/22328803/72684565-f0c95380-3ae1-11ea-94fc-bafcd547fb50.png)

_Originally posted by @DavidTamas in https://github.com/hrydgard/ppsspp/issues/12565#issuecomment-576021958_

**Comment by iota97** [comment]
It seem that DX11 is broken (DX9, Vulkan and OpenGL render fine on my end), tho' the problem is likely on the method that render the line as also the rectOutline in the analog test is broken.

**Comment by hrydgard** [comment]
Thanks for spotting this, should be an easy fix.

**Comment by hrydgard** [comment]
The rectOutline should also be fixed now.
