### ISSUE TITLE
Windows Camera code shuts down prematurely, causing random crash going into settings

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#12588]
Discovered by Sorer, Azuka and Zakiji from our Discord.

Currently the whole camera system is shut down after a game exits, from Camera::stopCapture in sceUsbCam (both STOP and SHUTDOWN is called). This is not ok because later you might go into settings, which enumerates the cameras - and if the camera system is gone, we're toast :)

@shenweip :)

![unknown](https://user-images.githubusercontent.com/130929/72838329-5f4c1400-3c90-11ea-9809-43bb0145bc7b.png)

**Comment by shenweip** [comment]
Okay,I will submit a fix soon:)
