### ISSUE TITLE
F1 2009 - Missing some audio

### ISSUE THREAD

**Issue by MarcoEstevez** [hrydgard/ppsspp#12584]
On game audio, like menus selection, and on race car sounds, ambient sounds are fine, but game is missing Team Radio Audio messages on race, Circuit Audio Intro, and music on general

**Comment by Emulatorer** [comment]
Get ppsspp log via ppsspp debugger
http://ppsspp-debugger.unknownbrackets.org

**Comment by MarcoEstevez** [comment]
Debugger could not connect
Debugger could not connect
Debugger could not connect
Debugger could not connect
Debugger connected
29:15:377 root         N[G3D]: vulkan\shadermanagervulkan.cpp:407 Loaded 24 vertex and 29 fragment shaders
29:15:380 root         N[G3D]: vulkan\pipelinemanagervulkan.cpp:728 Creating 198 pipelines...
29:15:382 root         N[G3D]: vulkan\pipelinemanagervulkan.cpp:760 Recreated Vulkan pipeline cache (198 pipelines).
29:15:389 root         N[BOOT]: ui\emuscreen.cpp:293 Loading E:/3 - PSP/F1 2009.iso...
29:33:003 Sound mixing E[FILESYS]: filesystems\isofilesystem.cpp:326 File /PSP_GAME/USRDIR/AUDIO/WAV/SFX/MUSIC/MUSIC_MAIN_MENU.AT3 not found
29:33:003 Sound mixing E[SCEIO]: hle\sceio.cpp:2073 00000004=sceIoOpenAsync(DISC0:/PSP_GAME/USRDIR/AUDIO/WAV/SFX/MUSIC/MUSIC_MAIN_MENU.AT3, 1, 0): file not found
29:33:085 Sound mixing E[SCEIO]: hle\sceio.cpp:2213 80020323=sceIoPollAsync(4, 09fdf950[ffffffffffffffff]): invalid fd
30:26:506 FileLoadThre E[FILESYS]: filesystems\isofilesystem.cpp:326 File /PSP_GAME/USRDIR/AUDIO/WAV/PITR/PITRADIO_SP.PAC not found
30:26:506 FileLoadThre E[SCEIO]: hle\sceio.cpp:1481 80010002=sceIoOpen(disc0:/PSP_GAME/USRDIR/AUDIO/WAV/PITR/PITRADIO_SP.PAC, 00000001, 00000000)
30:30:445 Sound mixing E[FILESYS]: filesystems\isofilesystem.cpp:326 File /PSP_GAME/USRDIR/AUDIO/WAV/TRACKS/AUSTRALIA/AMBIENCE.AT3 not found
30:30:445 Sound mixing E[SCEIO]: hle\sceio.cpp:2073 00000004=sceIoOpenAsync(DISC0:/PSP_GAME/USRDIR/AUDIO/WAV/TRACKS/AUSTRALIA/AMBIENCE.AT3, 1, 0): file not found
30:30:445 Sound mixing E[FILESYS]: filesystems\isofilesystem.cpp:326 File /PSP_GAME/USRDIR/AUDIO/WAV/PITR/SP/RACE_INTRO_AUSTRALIA1.AT3 not found
30:30:445 Sound mixing E[SCEIO]: hle\sceio.cpp:2073 00000005=sceIoOpenAsync(DISC0:/PSP_GAME/USRDIR/AUDIO/WAV/PITR/SP/RACE_INTRO_AUSTRALIA1.A..., 1, 0): file not found
30:30:445 Sound mixing E[FILESYS]: filesystems\isofilesystem.cpp:326 File /PSP_GAME/USRDIR/AUDIO/WAV/PITR/SP/RACE_INTRO_AUSTRALIA2.AT3 not found
30:30:445 Sound mixing E[SCEIO]: hle\sceio.cpp:2073 00000006=sceIoOpenAsync(DISC0:/PSP_GAME/USRDIR/AUDIO/WAV/PITR/SP/RACE_INTRO_AUSTRALIA2.A..., 1, 0): file not found
30:30:544 Sound mixing E[SCEIO]: hle\sceio.cpp:2213 80020323=sceIoPollAsync(4, 09fdf950[ffffffffffffffff]): invalid fd
30:30:544 Sound mixing E[SCEIO]: hle\sceio.cpp:2213 80020323=sceIoPollAsync(5, 09fdf950[ffffffffffffffff]): invalid fd
30:30:544 Sound mixing E[SCEIO]: hle\sceio.cpp:2213 80020323=sceIoPollAsync(6, 09fdf950[ffffffffffffffff]): invalid fd
30:30:960 Sound mixing E[FILESYS]: filesystems\isofilesystem.cpp:326 File /PSP_GAME/USRDIR/AUDIO/WAV/PITR/SP/RACE_INTRO_AUSTRALIA2.AT3 not found
30:30:960 Sound mixing E[SCEIO]: hle\sceio.cpp:2073 00000004=sceIoOpenAsync(DISC0:/PSP_GAME/USRDIR/AUDIO/WAV/PITR/SP/RACE_INTRO_AUSTRALIA2.A..., 1, 0): file not found
30:31:046 Sound mixing E[SCEIO]: hle\sceio.cpp:2213 80020323=sceIoPollAsync(4, 09fdf950[ffffffffffffffff]): invalid fd
33:12:005 Sound mixing E[FILESYS]: filesystems\isofilesystem.cpp:326 File /PSP_GAME/USRDIR/AUDIO/WAV/SFX/MUSIC/MUSIC_MAIN_MENU.AT3 not found
33:12:005 Sound mixing E[SCEIO]: hle\sceio.cpp:2073 00000004=sceIoOpenAsync(DISC0:/PSP_GAME/USRDIR/AUDIO/WAV/SFX/MUSIC/MUSIC_MAIN_MENU.AT3, 1, 0): file not found
33:12:105 Sound mixing E[SCEIO]: hle\sceio.cpp:2213 80020323=sceIoPollAsync(4, 09fdf950[ffffffffffffffff]): invalid fd
33:20:321 vulkan\shadermanagervulkan.cpp:429 N[G3D]: Saved 24 vertex and 29 fragment shaders
33:20:322 vulkan\pipelinemanagervulkan.cpp:672 N[G3D]: Saved Vulkan pipeline ID cache (198 unique pipelines/198).
Debugger disconnected

**Comment by unknownbrackets** [comment]
There are a lot of errors about missing AT3 files.  It's possible these are normal, but it's also possible this indicates something wrong on the disc.

Can you double check the disc CRC?  Some tools allow you to strip out things like music or videos to make ISOs smaller.  Maybe you did this some time ago, and forgot.

-[Unknown]

**Comment by MarcoEstevez** [comment]
Name: F1 2009.iso
Size: 263006208 bytes (250 MB)

CRC32: 340E7EF8

**Comment by unknownbrackets** [comment]
That's much smaller than it should be.  It sounds like a corrupt disc.

-[Unknown]

**Comment by MarcoEstevez** [comment]
You are right, I did grab another pal iso and it's 680 mb, this one has no issues, sorry my bad, I feel we can close this I guess.
