### ISSUE TITLE
Invalid download prompt in Linux

### ISSUE THREAD

**Issue by siddharths2710** [hrydgard/ppsspp#12591]
### Issue

In Linux, Booting PPSSPP prompts us to download the newer version as shown below:

![ppsspp_issue](https://user-images.githubusercontent.com/13200018/73073754-0c679c00-3ede-11ea-81c6-d83368bd50ea.png)

However, when I click on the Download button, the PPSSPP downloads page opens but it does not show up the recent version in Linux, i.e `1.8.0`.

I'm also unable to upgrade the package through the Ubuntu APT package manager, which says that the package is already in the latest version.

### Details

OS: Ubuntu 16.04
Version: 1.7.0
Download mechanism: PPSSPP Stable PPA

**Comment by unknownbrackets** [comment]
Is this different from #11889?

-[Unknown]

**Comment by siddharths2710** [comment]
@unknownbrackets to some extent. Since there's Currently no Linux build for version 1.8.0 as per #11889 , the prompt for downloading a new version isn't expected to appear.

**Comment by unknownbrackets** [comment]
I suppose we could change the button text from Download to something else.  This prompt would even show on self-compiled Linux builds (or even other platforms.)

Personally, I think PPSSPP should tell you if there's a new stable version regardless.  Even if you're using a custom Longsoon build, or whatever.  The problem of whoever maintains the builds you're using not having updated them yet is simply a separate issue.

But it's a fact that a new version of PPSSPP is out, and most likely (unless your system is very old), you can use the new version, even if you have to compile it.

-[Unknown]
