### ISSUE TITLE
Deadzone config should apply to more than DInput

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#12590]
We seem to only have deadzone settings for tilt, touch controls and DInput, other input sources are not processed. Was reminded of this by "Terminus" on Discord, should look into it.

**Comment by leopard20** [comment]
Correct me if I'm wrong but touch controls don't have any deadzone config either. At least I don't see it in settings.

**Comment by unknownbrackets** [comment]
I think XInput has a deadzone too?

https://github.com/hrydgard/ppsspp/blob/06dc3dbd29d9f5f05b8c4dca56fa4018bca47b47/Windows/XinputDevice.cpp#L258
https://github.com/hrydgard/ppsspp/blob/84c1fc86a18c7f4c60b04fbd4e19fb57c9d4cbe5/UI/GameSettingsScreen.cpp#L611

I'm not against it for touch, but I'm also not sure how necessary it is for touch.  Though I remember most games having deadzones, others were hypersensitive to that stupid nub... so a deadzone makes sense, but normally this isn't an issue with touch controls.  I didn't mind that it was sensitive when I actually intended to use it.

-[Unknown]

**Comment by leopard20** [comment]
As you said, some games might have a high sensitivity, making them hard to control on smaller screens. On the other hand, some games are not sensitive enough, such as NFS and Flatout, and I recall pushing the stick all the way near the corner without the car moving at all (it was the default behavior on actual PSP and it worked fine, but with touch controls it doesn't, especially on large screens such as tablets).
Thus having a deadzone setting would be very useful for touch controls, possibly a "negative" deadzone option too to fix the issue I mentioned with large displays.

**Comment by benderscruffy** [comment]
No feedback/outdated?

**Comment by hrydgard** [comment]
This is fixed, closing.
