### ISSUE TITLE
Rare race condition between i18n LoadIni and uses of it

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#12594]
If something calls for a translation while Clear is being called from NativeInit->PostLoadConfig->LoadIni->Clear , things can crash. This can happen in debug mode on Windows when changing backends on the fly (but doesn't always).

Our translation system is inherently pretty "racy" unfortunately. We should probably use some lock during rendering of UI - or just ignore this since I haven't triggered it outside of Debug builds..

**Comment by unknownbrackets** [comment]
Hm, I guess the most efficient thing is to lock during update, but we don't even always access from the UI.  Probably would not be that expensive to lock during each access.

What do you think about this, as a temporary step?  https://github.com/unknownbrackets/ppsspp/pull/new/i18n-lock

It should at least reduce the windows crashes can occur in, but doesn't prevent them outright.

-[Unknown]

**Comment by hrydgard** [comment]
Huh, yeah that's an interesting idea. It should reduce the chances of a crash by a lot indeed.

**Comment by hrydgard** [comment]
I went ahead and turned it into PR #12606 .
