### ISSUE TITLE
F1 2006 runs at 25 fps?

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#12600]
Possible add fps cheat for F1 2006? Game have locked 25 FPS ingame. That's really unplayable. On Forum fps cheat wasnt created
![Screenshot_2020-01-27-12-27-02-001_org ppsspp ppsspp](https://user-images.githubusercontent.com/33152267/73171463-13babf80-4101-11ea-87cc-9cd87fd168db.png)

**Comment by LunaMoo** [comment]
This is an issue tracker as long as the game runs at 25fps on psp, nothing will be done about it here. It's not a place to post game modding requests.
