### ISSUE TITLE
[Android][OpenGL&Vulkan][Graphic] Shin Mater of Monsters Final EX(ULJS00282) 真マスターオブモンスターズEX

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#12605]
### What happens?
Not appear the graphics after the tittle.
It became black out or blue screen.
But working the game back ground the display.
*Playing BGM & SE.It can be controll.

This issue had happen the below case.
1:Start the game.
2:Apeear the logo of "Systemsoft".
3:Start the intro movie.
4:Push start button quickly. 
  Before appear the tittle logo in the movie.(About past 10sec.)
  This timming is important.
5:Appera the tittle.
6:Push start button.
7:Dsiplay is not apper.Become Black or Blue screen.

If you push start button after appearing the tittle logo in the movie perfectly.
*About past 15sec. the intro movie.
Display appear collectly.(Why? I don't know!!)

### What *should* happen?
Any time appear the graphic collectly.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

PPSSPP Ver. : 1.9.3-251
OS: Android 9.0
DeviceName: SONY SO-02K / Xperia XZ1 Compact (Japan)
CPU: Snapdragon835 (Octa-core)
GPU: Adreno 540
Resolution: 720×1280
RAM: 4GB
ROM:32GB
ExternalStrage: microSDXC 512GB

I attached dump.
Please,check it.
[ULJS00282_0001.zip](https://github.com/hrydgard/ppsspp/files/4142287/ULJS00282_0001.zip)

[Remarks with ScreenShots]
![Screenshot_20200201-154514](https://user-images.githubusercontent.com/48179091/73588664-25d89b80-450f-11ea-9d3f-c6860a340fa1.png)
1:Start the game and appear the logo of Sytemsoft.

![Screenshot_20200201-154524](https://user-images.githubusercontent.com/48179091/73588673-46a0f100-450f-11ea-805f-2201c161cebb.png)
2:Start the intro movie....

![Screenshot_20200201-154532](https://user-images.githubusercontent.com/48179091/73588678-5a4c5780-450f-11ea-953f-1328657de922.png)
3:This issue separate the root at this tittle logo in the movie. Before? or After?

**Comment by unknownbrackets** [comment]
This is a game that has recently logged sceKernelStopUnloadSelfModuleWithStatus.

https://report.ppsspp.org/logs/game/ULJS00282_1.01

The dump only has the Systemsoft logo, so this dump doesn't tell us much.

If I understood correctly, the game does work if you press start at the right time.  That means this is probably video related, though it's not certain.

-[Unknown]

**Comment by nassau-tk** [comment]
Umm...
1.9.3-271 build is maybe OK.
I will close this!!
