### ISSUE TITLE
Fullscreen resize race

### ISSUE THREAD

**Issue by iota97** [hrydgard/ppsspp#12603]
On linux using SDL and OpenGL (Vulkan and Qt are fine, that might be just luck tho') starting PPSSPP in fullscreen might end up (kinda rare) having the actual rendered viewport of the size of windowed one logging:

`I: NativeApp.cpp:1271: NativeResized ignored, not initialized`

This is likely a race between thread (dropping RAM cache and force to load from HDD with `sync; echo 1 > /proc/sys/vm/drop_caches` seem to trigger it almost always on my machine, might be useful to test it).

![fs](https://user-images.githubusercontent.com/13517524/73381384-eb2ff280-42c5-11ea-8ca2-54d8eb2ffed2.png)

**Comment by unknownbrackets** [comment]
In theory, NativeResized (assuming it runs on the same thread as NativeInitGraphics and NativeShutdownGraphics do), should safely be able to ignore that per the warning.  It'd only be an issue if NativeInitGraphics was in progress and NativeResized ran on another thread.

On OpenGL, in fact, we in fact do run them on separate threads.

-[Unknown]
