### ISSUE TITLE
[Feature Request]Mouse controls cannot be mapped to analog controls in macOS

### ISSUE THREAD

**Issue by navneetrajoriya** [hrydgard/ppsspp#12610]
Mouse controls cannot be mapped to analog controls in ppsspp. There is no such option for MacOS.

**Comment by iota97** [comment]
This is duplicate of #4650

**Comment by LunaMoo** [comment]
Yeah, one generic issue about it is enough, closing as a duplicate od the mentioned issue. 
It was made only for windows so far and this might not change until some Linux/MacOS user/dev implements it and opens a Pull Request with his code, soo far there were no takers.

**Comment by navneetrajoriya** [comment]
Can I take this issue for MacOS? I'll try and once done I'll create a Pull Request and it could be reviewed.

**Comment by hrydgard** [comment]
@navneetrajoriya Sure!
