### ISSUE TITLE
Conflict between tilt input and other input methods on Android in LocoRoco 2?

### ISSUE THREAD

**Issue by alkalinethunder** [hrydgard/ppsspp#12620]
### What happens?

If you enable tilt input in Android for the **L** and **R** buttons in LocoRoco 2, and then set up a Combo Key or other method to press both L and R at once, that other input method doesn't work.

### What *should* happen?

LocoRoco uses the L and R buttons to tilt the world.  The game also has you press both L and R at once to shake the world to make your LocoRoco bounce.  These controls are the most important controls in the game.  Although PPSSPP allows you to control L and R with the acceleroeteer and LocoRoco handles this extremely well, there's no way to press both L and R at once.  A combo key or physical controller should be able to do it, but neither work.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

So far I've tested on an Alcatel A30 8-inch tablet running Android Nougat 7.1.1.  Not sure what PPSSPP version it's running but I got it from the Play Store.  Tablet's not with me right now but when I get home in a few hours, I'll update this with the version.  I'm also going to test on an LG G5 running Android Oreo with the latest Play Store version to see if the bug persists on there.

As for my input configuration, I have tilt input set to the L and R buttons.  This works as expected - tilting the device to the right, tilts the LocoRoco world to the right.  I have Combo Key 1 set to press L and R at once.  This should shake the LocoRoco world, but the combo key never registers a press when I tap it.  The game never sees the input.  I've also tried with an Xbox One S controller over Bluetooth, all inputs work fine except for the L and R buttons when the tilt control is on.  Perhaps the accelerometer is conflicting with other inputs?

### Further (but possibly not pertainant) information

I wanted to see if I could recreate a similar input conflict on desktop by hooking up a Logitech racing wheel to PPSSPP and setting the wheel up to control L and R (steering left should tilt the LocoRoco world to the left, steering right should tilt the world to the right.) Minus the fact I have to steer EXCESSIVELY to register a press, this works fine.  I also bound the rear buttons of the wheel to both press L and R at once so that either hand can bounce the world.  This also works with no issue, other than when you steer in a direction and press one of those buttons at the same time to shake while tilting.  This confuses the game and causes the world to flatten even though one of the tilt buttons is still held down, but I imagine that's a LocoRoco engine issue and not a PPSSPP issue.

**Comment by iota97** [comment]
When tilt control are enabled they keep releasing the key if the tilt is not enough, this basically cancel your other input.
#12530 address this (beside some edge case), as well as allowing to press both L and R tilting the phone back.

**Comment by alkalinethunder** [comment]
Okay, so I'm not the first one to notice this? I wonder if the people behind that wass also testing with LocoRoco? :)

That game definitely deserves some love and I've always wondered what it'd be like with true tilt controls on a modern device.  Glad to see there's a way to get closer to my dream.  I'll look into that change to see if maybe I can compile and sideload it. :)
