### ISSUE TITLE
ppsspp last beta build wrong display of refresh rate value

### ISSUE THREAD

**Issue by Emulatorer** [hrydgard/ppsspp#12625]
![Screenshot_20200214-082420](https://user-images.githubusercontent.com/37603562/74490559-dbd6b900-4f03-11ea-9ed2-948a625af3cd.png)
also notice that ppsspp auto frameskipp are not working correctly 🤔

**Comment by hrydgard** [comment]
Oops, will look into that soon.

**Comment by Panderner** [comment]
What device are you using @Emulatorer

**Comment by Emulatorer** [comment]
Android Platform w/ Mali-450 GPU, Octacore @1.4GHz and 2gb of RAM

**Comment by Panderner** [comment]
> Android Platform w/ Mali-450 GPU, Octacore @1.4GHz and 2gb of RAM

Name of your device not specs

**Comment by Emulatorer** [comment]
CyanogenMod/LineageOS 13 Custom ROM

**Comment by Emulatorer** [comment]
I tested v1.9.3-285 build it fixes the refresh rate and also the auto frameskip is now working correctly 😅
Before when I set frameskipp x1 w/ auto frameskipp the fps is only at 30/60fps but now using the latest beta build the fps is adjusting to 30-50+/60fps weird 🤣

**Comment by Panderner** [comment]
> CyanogenMod/LineageOS 13 Custom ROM

No I said the name of the device not the custom rom
