### ISSUE TITLE
Sims 2 Castaway Lag [OpenGL]

### ISSUE THREAD

**Issue by ghost** [hrydgard/ppsspp#12629]
Sims 2 Castaway lags when looking at Forest [First Beach].Can't go 30/30
Tried x1 rendering resolution.Still has lag
Tested on Xiaomi Redmi 6
GPU:PowerVR Rogue 8320
CPU:Mediatek Helio P22
Octa-Core 2.00Ghz 3GB RAM
![Screenshot_2020-02-16-12-24-38-318_org ppsspp ppssppgold](https://user-images.githubusercontent.com/54099546/74603778-598ef600-50b7-11ea-90c3-9ba5b3beeb73.png)
Sound is choppy as well

**Comment by Panderner** [comment]
Have you tried Vulkan?

**Comment by HiImBrala** [comment]
> Have you tried Vulkan?

I don't have it.And works fine on DirectX tho

**Comment by Panderner** [comment]
> And works fine on DirectX tho
DirectX is only available on the Microsoft Windows

**Comment by unknownbrackets** [comment]
It might help to see a GE frame dump.  See here for instructions:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

If you can enable "show debug statistics" in PPSSPP settings, seeing a screenshot of those might help too.

-[Unknown]

**Comment by HiImBrala** [comment]
> It might help to see a GE frame dump. See here for instructions:
> https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump
> 
> If you can enable "show debug statistics" in PPSSPP settings, seeing a screenshot of those might help too.
> 
> -[Unknown]

I will try and update tomorrow

**Comment by Emulatorer** [comment]
And also that game is still freezed on some areas #8999

**Comment by HiImBrala** [comment]
![image](https://user-images.githubusercontent.com/54099546/74811026-eb357800-52f0-11ea-9106-6fd99cf65189.png)
This is screenshot facing the forest that lags.Me,myself i never encountered freezing issue but encountered music stop some time
![image](https://user-images.githubusercontent.com/54099546/74811380-a9590180-52f1-11ea-89eb-8d3e128b61ae.png)
Also memory is way more used with OpenGL than used with DirectX 9/11
GE Frame Dump:
[recording.zip](https://github.com/hrydgard/ppsspp/files/4223619/recording.zip)
Will test on my phone today,but i think it is the bug with phone GPUs that they cache textures so PPSSPP can draw them faster

**Comment by HiImBrala** [comment]
![Screenshot_2020-02-19-09-41-16-873_org ppsspp ppssppgold](https://user-images.githubusercontent.com/54099546/74818393-dc55c200-52fe-11ea-9d43-58fb9b12d167.png)
![Screenshot_2020-02-19-09-36-52-263_org ppsspp ppssppgold](https://user-images.githubusercontent.com/54099546/74818399-de1f8580-52fe-11ea-91cc-69081e1a8822.png)
These are screenshots from my phone.Intro has some weird graphical bug where they weren't any on my PC.
[recording.zip](https://github.com/hrydgard/ppsspp/files/4224086/recording.zip)
This is phone GE Frame Dump

**Comment by unknownbrackets** [comment]
Is performance any better on PC with v1.9.3-291-g6610cd766?  If so, a screenshot of debug statistics again would help.

Also, it may help to see multiple screenshots, especially if what it says under "Most active syscall" changes over time.  Normally, that should look like your mobile screenshot (being some sceGe... function.)

-[Unknown]

**Comment by HiImBrala** [comment]
> Is performance any better on PC with v1.9.3-291-g6610cd766? If so, a screenshot of debug statistics again would help.
> 
> Also, it may help to see multiple screenshots, especially if what it says under "Most active syscall" changes over time. Normally, that should look like your mobile screenshot (being some sceGe... function.)
> 
> -[Unknown]

Since i'm not going to install APKs on my device,will wait for official release

**Comment by Panderner** [comment]
> Since i'm not going to install APKs on my device,will wait for official release

Why are you not Installing build APK?

**Comment by HiImBrala** [comment]
> Performance improved on Realme C2 which is Same CPU as Xiaomi Redmi 6
> at 1x resolution on OpenGL in latest build but the EA Logo FMV Glitched out

any fix for logo @hrydgard ?

**Comment by HiImBrala** [comment]
I think it can be more improved,wish i could help,0 % of coding experience,building Bot in Baby Steps so really can't know

**Comment by Gamemulatorer** [comment]
I got 60fps on this game on ppsspp github apk
![Screenshot_2021-05-24-13-20-40-170_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/119300287-17c60580-bc93-11eb-9ac5-515c8b14307b.jpg)

**Comment by unknownbrackets** [comment]
Okay, I'm going to assume that the previous change fixed it then, because it definitely seemed likely to.  Thanks for testing.

-[Unknown]
