### ISSUE TITLE
Raspberry Pi 4 - Out Run 2016 and Locco Rocco 2

### ISSUE THREAD

**Issue by rhunjadi** [hrydgard/ppsspp#12634]
### What happens?
Out Run 20016: The game starts fine and everything works. But when I try to start the game over the menu "drive" the game play loads and then it just breaks and throws me out of the emulator.
Locco Rocco 2: You can finish the first level. When the second level runs the game starts to play...u just fall down from the air and then the emulator just breaks and throws me out of the emulator.

When checking the /dev/shm/runcommand.log I get the following text:

/opt/retropie/supplementary/runcommand/runcommand.sh: line 1247:  2419 Segmentation fault      /opt/retropie/emulators/ppsspp/PPSSPPSDL --fullscreen "/home/pi/RetroPie/roms/psp/OutRun 2006 - Coast 2 Coast (USA).iso"
^

### What *should* happen?
The emulator shoudn't quit :)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
I'm using Raspberry Pi 4 with Retropie 4.5.13

**Comment by unknownbrackets** [comment]
Does this happen with fast memory turned off?

If it doesn't, that's still a bug, but may represent a workaround.

A few other things:
 * It's possible the RetroPie version of PPSSPP is out of date.  What version does it show inside it if you run `/opt/retropie/emulators/ppsspp/PPSSPPSDL`?
 * Do you have a mobile device, and can you confirm if the same games run on the mobile device?  This is to confirm if it's somehow rpi4 or SDL specific.

-[Unknown]

**Comment by rhunjadi** [comment]
I have tried now with the latest version of build 25726de. 

`pi@retropie:~/RetroPie-Setup/logs $ /opt/retropie/emulators/ppsspp/PPSSPPSDL --version
25726de
`
Now I've tried with the options fast memory turned off and the results are the same:

Outrun 2016: still breaks. 
Locco Rocco 2: same as before.

I've tried the same .iso Outrun 2016 with my mobile android phone with PPSSPP emulator and the game runs fine.

**Comment by hrydgard** [comment]
Curious. Are you running a 32-bit or 64-bit OS (and PPSSPP) on the R4?

**Comment by rhunjadi** [comment]
I am running a 32 bit Retropie  4.5.14 with latest from source compiled ppsspp emulator

**Comment by rhunjadi** [comment]
If this helps, you can check the runncommand.log. The log stars when I select from the main menu in the game the option just drive. Ive tried also to select any other game mode but there is always the same bug.

` tail -f -n 100 /dev/shm/runcommand.log`

and on [this link ](https://justpaste.it/2rdkc)is the runcommand log (justpaste.it).

**Comment by quicksilver7837** [comment]
@rhunjadi I just tested these two games on my pi 4 and I cannot reproduce your issues. Can you try updating your pi 4 firmware/drivers and see if that fixes your issue?

From the terminal run:
sudo apt update
sudo apt full-upgrade

Then reboot and retest

**Comment by rhunjadi** [comment]
Hello! Sorry for the late response...Now I've tried the lastest firmware and kernel (sudo apt update
and sudo apt full-upgrade)...and still the same result....

**Comment by quicksilver7837** [comment]
Have you changed any ppsspp settings from default? What version of retropie are you using?

**Comment by rhunjadi** [comment]
I'm ashamed I didn't try that before :/

I changed all my settings to default and now all the games work as expected!

Thank you so much!

**Comment by hrydgard** [comment]
Would be interesting to know what setting broke things so if you still have your old config file, please post it. If not, we'll just let this fade into history.

**Comment by rhunjadi** [comment]
Found an old image when settings were not working:

The files are from /opt/retropie/configs/psp/PSP/SYSTEM/ppsspp.ini

old version - the games broke the emulator:
[https://justpaste.it/2zpx6](https://justpaste.it/2zpx6)

default version (reset to defaults with some modifications) - all games work
[https://justpaste.it/2zpx6](https://justpaste.it/57amc)

P.S. I've updated the retropie and ppsspp from the source at the last version

**Comment by unknownbrackets** [comment]
Relevant differences:

 * Audio latency setting (it only gives you a subtle way to make timing incorrect)
 * Cheats (maybe a cheat was breaking games?)
 * Hardware tessellation (I'm surprised this is supported on rpi4, so maybe it actually isn't...)

```diff
--- badini.txt
+++ goodini.txt
@@ -13,7 +13,7 @@
 DiscordPresence = True
 NumWorkerThreads = 4
 AutoLoadSaveState = 0
-EnableCheats = True
+EnableCheats = False
 CwCheatRefreshRate = 77
 ScreenshotsAsPNG = False
 UseFFV1 = False
@@ -58,11 +61,12 @@
 CardboardScreenSize = 50
 CardboardXShift = 0
 CardboardYShift = 0
-ShowFPSCounter = 3
+ShowFPSCounter = 0
 GraphicsBackend = 0 (OPENGL)
 FailedGraphicsBackends =
 DisabledGraphicsBackends =
 VulkanDevice =
+CameraDevice =
 RenderingMode = 1
 SoftwareRenderer = False
 HardwareTransform = True
@@ -100,17 +104,17 @@
 VSyncInterval = False
 BloomHack = 0
 SplineBezierQuality = 2
-HardwareTessellation = True
+HardwareTessellation = False
 PostShader = Off
 MemBlockTransferGPU = True
 DisableSlowFramebufEffects = False
 FragmentTestCache = True
 LogFrameDrops = False
-CameraDevice =
+InflightFrames = 2
 [Sound]
 Enable = True
 AudioBackend = 0
-AudioLatency = 2
+AudioLatency = 1
 ExtraAudioBuffering = False
 AudioResampler = True
 GlobalVolume = 10
```

-[Unknown]

**Comment by quicksilver7837** [comment]
I believe opengl es 3.2 is required for tessellation. The pi 4 is gles 3.2 capable but the driver's only support gles 3.1 currently.
