### ISSUE TITLE
Allow more than 1 virtual L and R buttons

### ISSUE THREAD

**Issue by Yanpas** [hrydgard/ppsspp#12631]
I use Android and would like to have both L and R buttons on the top left and top right corners. Sometimes you need to combine R+O to shoot, sometimes R+right to drift

**Comment by iota97** [comment]
You can add 2 combo button that only press one key, one for R and one for L, and place them at the 2 screen corner.

**Comment by Yanpas** [comment]
Thanks, didn't manage to find out this feature
