### ISSUE TITLE
[Feature Request] Game Region Thumbnail Icons in Recent + Games lists

### ISSUE THREAD

**Issue by Abbanon** [hrydgard/ppsspp#12636]
I have multiple copies of the same game, all for different regions, and they all share the same thumbnails for the "Recent" and "Games" menus in PPSSPP.
For example, I own 3 copies of Ace Combat X -- ULUS10176 (US),  UCES00423 (EU), and ULJS00086 (JP).

This makes it a bit tedious with finding out which version is which region, so I always have to right-click them to view the information page, so that I can see the game region and Game ID to identify which version I want to launch.

My suggestion? 
An optional, small visual overlay for thumbnails that changes depending on the game's detected region.
It could function similarly to the "game config" gear icon, like so:
![region-flag-example](https://user-images.githubusercontent.com/37251822/75103141-cda03100-55c4-11ea-88e6-9a928993775d.png)
(This mockup is using free public domain 24x24 pixel region map icons)

This certainly isn't a _major_ issue by any degree, but could definitely prove useful for other users in the same boat. Thoughts and opinions?

**Comment by Emulatorer** [comment]
Why mine not change using latest ppsspp build :/
![Screenshot_20200226-173025](https://user-images.githubusercontent.com/37603562/75331751-3980e300-58be-11ea-9485-9acb22374728.png)
It should look like this 🤔
![75151646-7c4c8a80-5707-11ea-8881-19731d7570d6](https://user-images.githubusercontent.com/37603562/75331919-78169d80-58be-11ea-9e51-b82792c9e839.png)

**Comment by Abbanon** [comment]
@Emulatorer It must be enabled here:
![Screenshot_3](https://user-images.githubusercontent.com/37251822/75335087-e45db680-5856-11ea-8299-362187b31c3f.png)

**Comment by Drasikk** [comment]
This new option is very good (thank you @Abbanon) but now they just need to be translated into Spanish.

**Comment by Emulatorer** [comment]
@Abbanon thnx :)

**Comment by hrydgard** [comment]
Might consider turning the flags on by default in the future (though not the IDs).

**Comment by vnctdj** [comment]
@hrydgard 

I'm surprised, I personally think this is a very niche feature. Maybe I'm wrong but I don't think most people have multiple copies of the same game.

For the rare cases when we need to know the game's region, we can already long click/tap the game.

**Comment by hrydgard** [comment]
Yeah, that's true. I am going to leave them disabled by default, since it'll be more convenient than now to enable them once #12646 is in.
