### ISSUE TITLE
Android devices with low resolution scale UI poorly

### ISSUE THREAD

**Issue by Abbanon** [hrydgard/ppsspp#12644]
https://forums.ppsspp.org/showthread.php?tid=26192

**Comment by hrydgard** [comment]
Whoa, seems the DPI scale the device tells us about is entirely inappropriate for that screen. Very odd.

**Comment by meveric** [comment]
using MOBILE_DEVICE=OFF should solve this issue (at least it did for me).

**Comment by hrydgard** [comment]
If you're able to navigate to Settings/Tools/System Information and check "Name", and tell me what's there, we can autodetect this device and halve the DPI or something.

**Comment by Panderner** [comment]
Due to Odroid Go Advance's resolution, the resolution is 480x320 which is fit to PSP's resolution but the DPI of the menu doesn't fit for that resolution

**Comment by hrydgard** [comment]
Without knowing the Name from System Information, I can't detect and modify the DPI for this. I guess could use the tiny, tiny resolution as a hint maybe, but I don't know if that's safe enough.

**Comment by unknownbrackets** [comment]
For other platforms, we have code to detect small resolution/window sizes and reduce the DPI - see `UpdateScreenScale()`.  Android doesn't call this.

-[Unknown]

**Comment by Panderner** [comment]
@teehee4341 do you changed the resolution?

**Comment by Hope9415** [comment]
@hrydgard PPSSPP detected resolution as 1572x756 on my Pocophone F1 for some reason. Is there any way to manually set the PPSSPP resolution?

Or where can I change this value on the phone? I looked into build.prop but found no such value

[https://imgur.com/tUmxqjZ](url)

[https://imgur.com/BJVUT27](url)

**Comment by hrydgard** [comment]
I noticed that we now have a problem where if you change the display scaler resolution in-game, we don't update the size of our framebuffers, causing some problems.

**Comment by Hope9415** [comment]
Yeah. The other day I noticed changing render resolution seems to did the trick in the meantime

**Comment by hrydgard** [comment]
Let's merge this issue into #14527 which is the same problem but opposite.
