### ISSUE TITLE
Touch Control Icon Collisions Don't Match Their Sprites

### ISSUE THREAD

**Issue by NABN00B** [hrydgard/ppsspp#12649]
Now that we have an option to display a grid in the "Edit touch control layout..." menu it is easy to see that the pictures of the buttons do not match the grid at all. It has also always been noticeable that if you put 2 buttons next to each and want to move the one on the right, it will often select the one on the left instead.
![kép](https://user-images.githubusercontent.com/22328803/75472942-9c44ae00-5994-11ea-8a4b-a6430c2faf9a.png)

Small but annoying thing that I could finally bring myself to report. 😄

**Comment by ResurrectionRedmi9** [comment]
This should improve now via https://github.com/hrydgard/ppsspp/pull/14806

**Comment by NABN00B** [comment]
What I mean is that the areas that can be used to grab the buttons are wider than the sprites of the buttons.
For example in the image below, the sprite can be grabbed from anywhere within the area of the red rectangle.
![image](https://user-images.githubusercontent.com/22328803/158026296-61542521-5e7a-41ac-b34b-46b38283be56.png)

In case this is intended, the issue can be closed.

**Comment by iota97** [comment]
There is an extra 25% size to make it easier to grab. It's intentional :)

**Comment by Gamemulatorer** [comment]
This doesn't cover by https://github.com/hrydgard/ppsspp/commit/57b4cd394a69029dcb8943e1bad33a4d149dcf99?

**Comment by iota97** [comment]
Not by that commit, but this is probably enough to close this: #14744 :)
