### ISSUE TITLE
UI texture atlas system should not need to generate source files.

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#12645]
As in the title, just a reminder to myself to redo it based on string IDs for resources instead of these sequential numbers that require "hardcoding".

**Comment by unknownbrackets** [comment]
Can we consider this done now?  Or do we still want to compress and embed the metadata in the zim?

-[Unknown]

**Comment by hrydgard** [comment]
This issue can be closed now indeed. Let's see if I'll bother with that, this way works too (and at least on Android, will be compressed in the apk zip anyway).
