### ISSUE TITLE
UI/store.cpp File, has a problem with https URLs

### ISSUE THREAD

**Issue by Slippy2k** [hrydgard/ppsspp#12666]
### What happens?

If I replace the address http://store.ppsspp.org/ with my https://example.com address I get the error:

<Html>
<head> <title> 400 The plain HTTP request was sent to HTTPS port </title> </head>
<Body>
<center> <h1> 400 Bad Request </h1> </center>
<center> The plain HTTP request was sent to HTTPS port </center>

If I have a URL without https e.g. http://example.com
Then it works. But http:// is out of date with the current time

PPSSPP v1.9.3-293

**Comment by unknownbrackets** [comment]
PPSSPP doesn't have any TLS support at the moment, neither for outbound connections (accessing https:// URLs) or inbound connections (servicing https:// URLs like sharing or debugger.)

-[Unknown]

**Comment by hrydgard** [comment]
Agree, unfortunately we currently don't support https.

Need to look into replacement for my homegrown little http library.

**Comment by hrydgard** [comment]
I've opened #17583 a while back, it replaces this issue.
