### ISSUE TITLE
Weird behaviour with unthrottle and vsync and speed

### ISSUE THREAD

**Issue by vsub** [hrydgard/ppsspp#12662]
I don't know from where to even begin,it's so confusing

v1.9.3-335-gb1e83df52
6700HQ\GTX1060\Intel HD530(the same fps limit exist on both cards)

Vsync is set to "Use the 3D application setting" in the nvidia control panel

If FrameSkipUnthrottle is not set to True(which is not by default)

Vulkan + PPSSPP Vsync disabled - limited to 60fps
Vulkan + PPSSPP Vsync enabled - limited to 200%(KH2FM runs at above 200%,Cube.iso runs at max 200%...as smooth as 200% and as fast as 200% but the percentage shows above 700%)

OGL\DX9\DX11 + PPSSPP Vsync enabled - limited to 60fps
OGL\DX9\DX11 + PPSSPP Vsync disabled - limited to 60fps

If FrameSkipUnthrottle is set to True
Unthrottle work on all backends

If Frame skipping is not set to anything different than off,alternative speeds will not work.

And finally the most annoying problem...all games don't run at 100%(even if the FPS counter says full speed)which in KH2FM for example results in a really annoying constant audio crackling\poping\stuttering(not sure what's the correct word but you can hear it when a game is not running at full speed)

When I use unthrottle the sound is fixed for few seconds until ppsspp adjust the speed back to 98%

But if I enable auto frameskipping and set the frames to 1 or 2,then the audio is fixed.

The percentage shows less than 100% when the game is running at full speed(30/60fps)
For example the Cube.iso never reaches 100% even if it says 60fps,it will stay between 98-99% and I get a message saying that ppsspp is running slow and I should enable frame skipping(even if tho I can run it at above 1000fps without frame skipping...it was long ago I see that kind of number)

On 30fps game,because of the 60fps limit,when I use unthrottle(FrameSkipUnthrottle is off),ppsspp shows 60fps but the percentage shows 197%

KH2FM
![kh](https://user-images.githubusercontent.com/5032540/75627968-c97ba100-5bcc-11ea-9424-7d5e436e286d.jpg)
Cube.iso
![cb](https://user-images.githubusercontent.com/5032540/75627969-c97ba100-5bcc-11ea-8a7e-b9b994abaed6.jpg)

**Comment by unknownbrackets** [comment]
I'm not reproducing most of these problems, but there is an issue I'm seeing with a 60 FPS game and 200% speed - I get ~60-61 FPS with vsync in Vulkan.

I tried unthrottling both with the unthrottle key and alternate speed.  Both are working fine on all backends.

Basically, Vulkan turns on frameskip unthrottle automatically when unthrottled (or should.)
Other backends turn off vsync temporarily when unthrottled.  It almost sounds like on your system, it's refusing to turn it off.

That doesn't really explain the 98% issue, though.

OpenGL should not really have changed at all from before.  Did it?

-[Unknown]

**Comment by unknownbrackets** [comment]
Is it possible your display vsyncs at less than 60 FPS?

-[Unknown]

**Comment by vsub** [comment]
I figure it out...it's that nVidia Whisper(I think it's laptops specific option)messing with the FPS yet again.

And yes,there is still the problem with vulkan and vsync(I have to wait for that commit to be merged and compiled to test it)
