### ISSUE TITLE
PPSSPP 64bit core crashes on game exit

### ISSUE THREAD

**Issue by ds22x** [hrydgard/ppsspp#12679]
### What happens?
The PPSSPP core on Android 64bit crashes when closing most games (E.G. Dissidia Final Fantasy, Angry Birds, GTA Vice City Stories).
Doesn't happen when exiting out of 7 Wonders of the Ancient World.

### What *should* happen?
It should close the game and return to Retroarch's UI, which happens when using the core on Windows.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Nvidia Shield 2017 version and OnePlus 6 running Android 9 and 10 respectively, both with the latest PPSSPP core version.

**Comment by garga3838** [comment]
!<arch>
/               1359214541  0     0     0       118       `
����ttt__gnu_mcount_ncmonstartupmoncleanupprofCountfree_mapsread_mapsget_real_addressgnu_mcount.o/   1359214540  1000  1000  100664  1496      `
ELF(�4(���qF���������F���A aeabi7-A
A	
,G'�
jnignu_mcount.S!!!!/!"!!!!bjni/gnu_mcount.S/home/travis/builds/richq/android-ndk-profilerGNU AS 2.21�%.symtab.strtab.shstrtab.rel.text.data.bss.ARM.attributes.note.GNU-stack.rel.debug_line.rel.debug_info.debug_abbrev.rel.debug_aranges4	�%P+P0pP!@qTqKP	�d�f`	� 	p"�8 ~	�X���	t!	$t$d__gnu_mcount_ncprofCount
 
4prof.o/         1359214540  1000  1000  100664  27920     `
ELF(t?4(;8dsecondss�FJFI�zDyD �����
������F
 
���� �
	�� "��!����8� ������8�
K{Dh��K�m{Dh|�]hm��h�h����(ۨB�4�03$�08��0*���-��AFaI��aHyDxD����9F����^K{Da�]IyD<�Fh�h[L��|Dh YJ!F�zD;F����WHxD������!
F����(F�RJzDP`�QJ !FzD����OL5&�%�|D# �`�eaO�V�a�`O�H����F �EIyD����j� �����aH�@IyD����8F����A����pd!����2#1( b�O��s�B�#b6L! |D#jYC����F`bX�1IyD����8F�����i�����a6�"�����/�K ���&K{D�����F`�����#I#JyDzDh �#F�����K�{DHYh������	���� F"F����K"{D`����@B|~tpf^XD<.������xV���-��O���M�H}D-hxD+h
������F �x#��L|D�L|D�M �J}D�NzD)F~D����!"�����"� ����I# 3`yD����}J)F zD����{I FyD����F �xIyD������kK"!�'��$ �#F��%p��&p��'p����(F�mI8FyD��lM
�8	
F}D	�+}HFkh�b#F����(Fф�ii(i����F F������ F�j����p� Fqh�����F@�"�9F#F����(r�VIyDR�7�;!"
���0
��0#F����(�MIyD?�6�j�B�۫i'JNJMO�S~D}D>��iy3�0+7гh0i������i3���F*�!��
!HF#F
F����(�@�#(i��kjS�����F F����0�kj FCDYh����(�0IyD ����	�kj�D�������7_E�� F�����h(i����F F����(��o��9F:F#F����(�/hFF�і� FQF����(�����
�h�B���������gmon**������T2 ����5K�{Dh*c�'`2K{D�h��i�BJ��i�@2�`��\jj%����%��BB�"�P#]CcaQ_`�4�[j%nC��Y�B�/F�ch3c`'�,F&���M�}D4-j����B �&fC��Q#k`2�)�"�@�~C��Y�B��)�kh3k`#�!�2�)�"�0K"{D`�
K"
I {DyD`���@��������n( ����PROFILING%d: %s/proc/self/mapsrNo maps foundProfile %s %x-%x: %dCPUPROFILE_FREQUENCYInvalid frequency value: %dNo space for profiling buffer(s)
add_profile_handler, sigaction failed %d %d/sdcard/gmon.outCPUPROFILEparent: moncleanup calledparent: done profilingwriting gmon.outwbmcount: gmon.outmcount: gmon.out headermcount: gmon.out histmcount: gmon.out samplemcount: arcmcount: tos overflow
��|�HDOv�����0�tint�ԈmSA�3�A5�`a7���K c+��-�j/�	vf�Kv��g�{��v
��#�_6HZC�H'c=�d2uiS8��	 	�
�U�
�V�
�WZ	v		1
|�
*Z)
+v#�
,v#�
-v#�
X[#
��T�_uX�#bY�#sZ�#>[�#
�a�]b1#�cv#�d}#"e��

8
v
�
1!
�
2??
3�#�
4d#
7�

8�#l
9v#�
:�#Z
;#M
<v#���
?�?
@�#�
Ad#Z
B#
E?
F�#�
Gd#
Hv#G
Io#�
Jo#
M6/
N1#
T[E
U�#_fd
Vv#t
/�
�
0�
%
5
�
=?_rt
C�
�
K�
�
R
]
W6v���
Y�Nz�W�X#�Yv#
��Tw(_px#_ryv#_wzv#�{�# |�#_bf}�#�~v#=�1#��8# �X#$�x#(���#,+��#0_up�#8_ur�v#<*��#@���#C_lb��#D��v#LN��#Pv8	1
(vX	1	^	v
>�x	1	�	v
^v�	1	�	v
��
~������������#��##4&�5�#J6�#�
x]
z^#
{v#u
|�#/��!�#"�#F#�#������(�w���
��#lo�#hi�#z#
�-TK	0�#��#�#V�#��#��#��#��#��# p�#$��#(��#,��#0e�#4"�#8��#<� �#@�!�#D8"�#H�#�#L�$�#P5l�	/�#z�	#��##��#h
K	}K	T��	8�b��	pc�v
���(
sig�vX�(

�15�.
,�4
 
�
�	
�_Z
b_^v_ �Tvw
setTw
 
���
������
*�v��
�^�v!���
"V ^ �mvfmbm�
� "vMfbuf^n��gmbg^vg�#�Z �$aZv $msgZ�>%huv,h	$fu�$vu�&bufw��t':
x(P
�)G
�t�*�	@��(�	�(�	�(
+
%+
8,�	
@�(
M-
@.
.
/�	/�	'�	
 �(�	`-@+�	s+�	������`��v���0N����
1�٘�2��v�2^�^28�Q2a�2Y��3�
Fr�
-Fr+�
�-Pr+�
�4�
~(�
,�v�586��H+�6��X7�'�78fd)d9�*v�9�+v�9�,�9�-v:�.]�@:&/�T"K�	:L���8iMvH;�
P/�5p+�
[;�
4�1<�
=�
4�'5�/�
,}
@T�-@T6�
��;:
��93(P
n(G
�;�
�@Y)yU(�>E�(C�(8�(/@>M$.O�(ct(Z�>�
~�`�(�(�=�0F(C�(8(/L7Dq�u�?8q��?q^�8tops�19st��9�u��@���@>��Aout��
�
&B�HvB�I�&tosJ�$B0K� B5LB�MBN�BAPvBkQ^BBRvBTv(�j�B2UZBV�B�WBLXv%RU�B�B:;(
$>:;I$>'	I
I':;
 
:;I:;
:;I8

:;I8
:;:;I!I
:;I!I/'I&I:;.:;' :;I4:;I:;I4:;I .:;'I !.:;'I "4:;I#.:;'@$:;I%.:;'I@&4:;I
'1RUXY(1)1
*.1@+41,1XY-.41/10.?:;'@1:;I24:;I31XY41XY5U641
7.?:;'@84:;I94:;I:4:;I
;1RUXY<1=1RUXY>1XY?:;I@
:;A
:;B4:;I
} }PS
Q
P�p},}P#SQQ}@}PQ
RRr�
R!R!!4T"4P}
}
�}�P�W��X�~X��P��P�W0�~W*8p8�V��,8p8vUv~u}�~�U��UPNWP\jPjqS~1�49P9~T}}$�}�z�P��TRX0�X�W��W WR�[��[ [jmQvxPx�Z��Z Zv�X��X XLV0P� 1�� �D���T��T� T?��?���?�� ?�������� �T�T��T� T*S@���X������x�T��T T�1���1�� 1������� ��T��T� T}�}"P"�p1$"���p1$r"���p1$"���P�Q��u��Q��Q��QBJSRdTdfUfnT��U��T��UdfT��T&4V4@UJPVx�T��s@$@%�9�msystemMessage�profWrite32	profile_action�monstartup�
moncleanupprofCount�profiling�froms�tos�tolimit�s_lowpc�s_highpcs_textsizessiz'sbuf8s_scaleIhist_num_binsjhist_dimension{hist_dimension_abbrev�s_maps�s_freq_hz�3android_LogPriority?ANDROID_LOG_UNKNOWNEANDROID_LOG_DEFAULTKANDROID_LOG_VERBOSEQANDROID_LOG_DEBUGWANDROID_LOG_INFO]ANDROID_LOG_WARNcANDROID_LOG_ERRORiANDROID_LOG_FATALoANDROID_LOG_SILENTvint�unsigned int}size_t�unsigned char�signed char�__uint8_t�short int�short unsigned int�__uint16_t�__uint32_t�long long int�long long unsigned int�long unsigned int�long int�char�uint8_t�uint16_tuint32_t__kernel_off_t'__kernel_pid_t2__kernel_time_t=__kernel_suseconds_tH__kernel_clock_tS__kernel_timer_td__kernel_uid32_toclock_tzoff_t�pid_t�suseconds_t�time_t�timer_t�sigset_t�__signalfn_t�__sighandler_t`sigaction�sigaltstack�stack_t�sigvalsigval_tsiginfo�siginfo_t�fpos_t�__sbuf__sFILE�FILE�timeval�itimerval&tostruct]gmon_hdr�proc_mapsigcontextK	ucontext�	ucontext_tD ,@���
@$&v
,
,46:<@b46:<@b46:<@b������������� ,@������
jni/home/travis/builds/richq/android-ndk-profiler/android-ndk-r8d/platforms/android-3/arch-arm/usr/include/home/travis/builds/richq/android-ndk-profiler/android-ndk-r8d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/include/home/travis/builds/richq/android-ndk-profiler/android-ndk-r8d/platforms/android-3/arch-arm/usr/include/machine/home/travis/builds/richq/android-ndk-profiler/android-ndk-r8d/platforms/android-3/arch-arm/usr/include/asm/home/travis/builds/richq/android-ndk-profiler/android-ndk-r8d/platforms/android-3/arch-arm/usr/include/sys/home/travis/builds/richq/android-ndk-profiler/android-ndk-r8d/platforms/android-3/arch-arm/usr/include/asm-generic/home/travis/builds/richq/android-ndk-profiler/android-ndk-r8d/platforms/android-3/arch-arm/usr/include/linux/home/travis/builds/richq/android-ndk-profiler/android-ndk-r8d/platforms/android-3/arch-arm/usr/include/androidprof.csignal.hstddef.h_types.hstdint.hposix_types.htypes.hsignal.hsignal.hsiginfo.hstdio.htime.hgmon.hgmon_out.hread_maps.hsigcontext.hucontext.hlog.h	� !!u� l /.j !.k .=?�#tJ r <0Y./�@$Yg!?!!f�K!K!!L f!0-%!z #"-"!Y!K"Y!K d<2L!"K#!/-;#!K>=!"",#�<#�.� !>="�!Y-!KX�J-�<x (x.(x.K 0
X�J� �.� �.YX!!�<gg!K"�~ � �~.�."�~ //�.YN�~<� �~<� �~.�t�"I"W�~ � �~.�fD/�~J/�<Y9 D!!
 t 0
 u !O 1 M""/;!�~J��#9�uwfIy< .SJ�B�~.���~ �.t0�n  M5K?!!/$!K1/=!!!"K$.\.$=  i 6!!/1=!/=/&/D=!!=3]0,"$,suseconds_thist_dimension_abbrevprofWritemcontextucontextoverflow_utimemonstartupselfbufferarm_r10unsigned intnextversionsiginfo_t_lbfsize/home/travis/builds/richq/android-ndk-profiler__signalfn_tarm_ip_sa_sigactionprofPut16_timerprofControlhist_sampleselfpc_readsigval_tmode_addrs_lowpc_cookie_band__kernel_pid_t_sigvalsa_maskuint32_tprevtop__kernel_clock_tfpos_tfault_addresscookiebasesigvalfrompcprofPut32resultss_sizelong long unsigned int__sFILE_flags_padlibname__uint16_tget_frequency__sighandler_tgmon_hdrfrompcindexprofCount_offsetgmon_outclock_t__kernel_suseconds_tsiginfo_sigchldmonsizetimevalsigemptysetsize_tsi_errnoGMON_TAG_BB_COUNTs_highpcghdrtv_usec__kernel_time_tsystemMessagearm_cpsrfreq_tidcount_statuschar_kill_extANDROID_LOG_WARNssizspares_freq_hzarm_r0ss_spuint8_tsbufarm_r6GMON_TAG_TIME_HISTtime_t_closefromsANDROID_LOG_VERBOSEtostructget_gmon_outlong long intGMON_TAG_CG_ARC_base_sifieldspid_t__kernel_timer_tcontexts_textsize_filegmon_nametolimitarm_pc_pidandroid_LogPriorityinfo_sigpoll__kernel_off_ttimer_tucontext_tdoneuc_stack_sa_handlerarm_r1arm_r2arm_r3arm_r4arm_r5uint16_tarm_r7arm_r8arm_r9_writetoindexmoncleanupuc_sigmaskfreqvalANDROID_LOG_SILENTitimervalsigcontextsigset_tshort intlong intcheck_profilhighpcprofWrite32ANDROID_LOG_FATALprofile_actionANDROID_LOG_INFOaction_stimes_maps__uint8_tarm_spsigactionadd_profile_handler_uid_blksizetv_secarm_lrlong unsigned intremove_profile_handleruc_flagssival_ints_scaleit_valueunsigned char__uint32_t_overrunlinkuc_linkGNU C 4.6 20120106 (prerelease)ANDROID_LOG_DEBUGfromindexprofWrite8__sbufit_intervalproc_mapsi_codeerror_codeprofilingsigaltstackuc_mcontextoldmaskarm_fpsi_signohist_dimensionsigned char_sys_privateoff_tshort unsigned intsa_flagsjni/prof.c_size_nbufANDROID_LOG_DEFAULTFILEtimerANDROID_LOG_UNKNOWNss_flagssival_ptrendfrom_sigfaultANDROID_LOG_ERROR__kernel_uid32_thist_num_bins_seekstack_t_ubuftrap_nolowpcsa_restorerGCC: (GNU) 4.6 20120106 (prerelease)A2aeabi(7-A
A	
,����|
 A����,A����@A���� �B������CH$�B$���������	A`�B�����.symtab.strtab.shstrtab.text.data.bss.rel.text.systemMessage.ARM.extab.text.systemMessage.rel.ARM.exidx.text.systemMessage.rel.text.profWrite32.ARM.extab.text.profWrite32.rel.ARM.exidx.text.profWrite32.rel.text.profile_action.ARM.extab.text.profile_action.rel.ARM.exidx.text.profile_action.rel.text.monstartup.ARM.extab.text.monstartup.rel.ARM.exidx.text.monstartup.rel.text.moncleanup.ARM.extab.text.moncleanup.rel.ARM.exidx.text.moncleanup.rel.text.profCount.ARM.extab.text.profCount.rel.ARM.exidx.text.profCount.rodata.str1.1.rel.debug_info.debug_abbrev.rel.debug_loc.rel.debug_pubnames.rel.debug_pubtypes.rel.debug_aranges.rel.debug_ranges.rel.debug_line.debug_str.comment.note.GNU-stack.ARM.attributes.rel.debug_frame4!4'P,NP ,	�R9Dpfp�|b	�R9��,�	�R9	���p��	�	�R9��@�	�R9�p�	S9P�1	S@9F�ep��a	PT9����	`Tp9�l�p�l�	�U9�t��	�U89�dp�d�	V9 2l�.�*	(V(9#:�gL!�H	Pa�9&[
%=W	�i9(oG&k	j9*�O*H	j89,��*��	@j@9.�,��	�l090�03J�0N;&�t;�pt;3��;��	�l`96x<��H�:c	LPK�� 
"!"		&,	2@8�A!"F"K#"P1"UF"Z["_w"d�"4i�"o�"u�"{�"�"�#"�&"�7"�O"�e"�}"���"  "��������% -$1(#%&(*,.0246635?Sjq���������������/A�prof.c$tsystemMessage$d.LC1.LC0profWrite32profile_action.LC3.LC2.LC4.LC5.LC6.LC7.LC8.LC9.LC11.LC10.LC12.LC13.LC14.LC15.LC16.LC17.LC18.LC19.LC20.LC21profilings_freq_hzhist_dimensionhist_dimension_abbrevsbufssizs_lowpcs_scales_mapss_highpcs_textsizefromstolimittoshist_num_bins__android_log_print__aeabi_unwind_cpp_pr1fwrite__aeabi_uidiv__aeabi_unwind_cpp_pr0__aeabi_idivmonstartupfopenread_mapsgetenvstrtolcallocfreesigaction__errnosetitimermoncleanupmemsetget_real_addressfclose__stack_chk_fail__stack_chk_guardprofCount
c	
*d* 
e*d*
f8<*g
j
kB
cJ
lT
mn
c�
n�
�
n�
�o�
f�
n�

o
o.
p6
qJ
cZ
hr
r� �!��"�
�#�$��%��&�&��&��
�'��*g
l<
cF
tP
r^
j
ct
j�
�
e�
e�
u�
�
�


e0
ej
u�
e�
u�
�
�
�
v�
u�

e
*
w8`x<.@/D/H
L0PT1X2\3`4d5hl6p7tx|8*+g�������?*<gV]]]![%\)X-Y4]@]F]L]R]X]^]d]j]p]~]�]�]�]�]�]�]�]�]�]�]�]�]�]�]�]]](]3]>]I]T]e]p]{]�]�]�]�]�]�]�]�]�]]"]0]>]L]a]z]�]�]�]�]�]�]�]�]�]]]#]1]H]V]d]r]�]�]�]�]�]�]�]]](]?]d]o]z]�]�]�]�]�]�]�]�]]:]H]d]r]�]�]�]�]�]�]�]]]�]�]�]�]�]
]]']3]A]O]^]j]x]�]�]�]�]�]�]]]%]3]A]O]]]k]y]�]�]�]�]�]�]�]�]�]	]	]!	]/	]=	]L	]X	]f	]t	]�	]�	]�	]�	]�	]�	]�	]
]
]
];
][
]~
]�
]�
]�
]�
]�
]�
]�
]�
]�
]]N]n]uy}W�W�W�]���W�W�W��[�WW#W,W5W>WGWPT_Wdh��[�W���W�W�]�]�]�]�]���W
]
W
]
W
])
W.
]8
W=
]G
WL
]V
W_
c
n
r
{
W�
�
�
W�
�
�
W�
�
�
[�
W�
]�
+�
+�
WW]W]#W(]3W8]CWH]W]e]q]�W�+�[�[�W�+�[�+�[�[�+�+�+�++[%W.W8+<[TW^+b+rW{W�W�+�+�W�W�+�+�W�W�+�[�W�W�W]<<W]*W/]:WJWO]ZW_]jWo]v<{]�<�<�]��]���]��]��]]]#(]49]EJ]Vk]w|]��]��]� $+/>BIMTXhltx���������������%)8<MQ`dsw~����������������� '+26>BQU]ahls�����������������	$(7+;+C+G+O+S+d+h+o+s+�+�+�+�+�+�+�+�+�+�+�+�+�+�+�+�+�+�+�+�++++++#+*+.+5+9+H+L+[+_+n+r+�+�+�+�+�+�+�+�+�+�+�+�+�+�+�+�+�+�+++++#(+,+3@+D+K+O+V+Z+a+e+t+x+�+�+�+�+�+�+�+�+�+�+�+�+�+�+�+�+++++$+(+/4+8+?L+P+W+[+b+f+u<y<�<�<�<�<�<�<��<�<�<�<��<�<�<�<�<<<<<<<"<1<5<<<@<G<K<R<V<]<a<h<l<s<w<�<�<�<�<�<�<�<�<�<�<�<�<�<�<UUU (0+8< $(,8<@DP+T+X+\+`+d+p+t+x+|+�+�+�+�+�+�+�+�+�+�+�+�+�+�+�+�+�+�+�+�+�+�+�+�+++++++ +$+0+4+8+<+HLPTX\`dh+l+p<t<����+�<`0`4L`Ph`l�`�+�`�<read_maps.o/    1359214540  1000  1000  100664  9024      `
ELF(�4(+(8�F�h��h����(F(�� F��8@�������-��O�F��F�F����$!M!O&F}DD�F/�(F����#A�EkT'���HFi�����F��(F�9F�����	����� .������`FF������`F����#`�c`	��`(FO�qZF����(��0F����|~��
��Ch�Bӂh�B����h(��FpG����%x-%x %4c %x %c��i@H=K�int�:�h��T�py�C��N�UW�ZX�#�YM#8\Tw	_px�#	_ryM#	_wzM#�{?#�|?#	_bf}�#'~M#`�w#��# ��3#$��S#("�~#,���#0	_up��#8	_ur�M#<T��#@���#C	_lb��#D��M#L���#P
Mw
M3w�M
�Sw�M9
MswsMyyY
8�T
8�Td��
�8T#	loT#	hiT#5�#��Gs� 5�>tmp�����fp��s����0�0� �{len"�� c&�D0'"�Hlo(M�L8(M�Phi(M�T�
y"T
y2Tq;T}{�;{��;T�mp={���
y�T�)�%RU�B�B$>$>:;II:;
:;I8
	
:;I8
 
'II&I
I!I/.?:;'@:;I4:;I4:;I.?:;'I@:;IU4:;I
4:;I
.?:;'I@
}}PTt
P
 
p
UP
P}}$�}�
P
�[Q�Y 0� dVdhPh�V 0� dTdhPhnTn�P��T P �Z&*P*4QPQQPJ��free_mapsGread_maps2get_real_address�s_line'�1signed char8unsigned char?short intFshort unsigned intMintTunsigned int[long long intblong long unsigned intilong unsigned intplong intychar�size_t�__kernel_off_t�off_t�fpos_t�__sbuf�__sFILE�FILE�proc_map,� �@���P�
jni/home/travis/builds/richq/android-ndk-profiler/android-ndk-r8d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/include/home/travis/builds/richq/android-ndk-profiler/android-ndk-r8d/platforms/android-3/arch-arm/usr/include/asm/home/travis/builds/richq/android-ndk-profiler/android-ndk-r8d/platforms/android-3/arch-arm/usr/include/sys/home/travis/builds/richq/android-ndk-profiler/android-ndk-r8d/platforms/android-3/arch-arm/usr/includeread_maps.cstddef.hposix_types.htypes.hstdio.hread_maps.h !!"!-3!-M#-"(u #(w !!>"! ��!/!1>>//l.�;!<=05size_tproc_maplong long unsigned int_lbfsizepermnextlong long intsigned char_ubuf_base_cookielong intget_real_address_flags_blksizelname_offsetoff_t_readfpos_tunsigned intGNU C 4.6 20120106 (prerelease)_closelong unsigned int_fileshort unsigned intjni/read_maps.c_writes_linecurrentbaseunsigned charshort int__sbuf__sFILEFILE/home/travis/builds/richq/android-ndk-profilerread_maps_seekchar_size_extfree_maps__kernel_off_tnamelenmaps_nbufresultsfakeGCC: (GNU) 4.6 20120106 (prerelease)A2aeabi(7-A
A	
,����|
A����$�B$���������	BP.symtab.strtab.shstrtab.text.data.bss.rel.text.free_maps.ARM.extab.text.free_maps.rel.ARM.exidx.text.free_maps.rel.text.read_maps.ARM.extab.text.read_maps.rel.ARM.exidx.text.read_maps.ARM.extab.text.get_real_address.rel.ARM.exidx.text.get_real_address.rodata.str1.1.rel.debug_info.debug_abbrev.rel.debug_loc.rel.debug_pubnames.rel.debug_pubtypes.rel.debug_aranges.rel.debug_ranges.rel.debug_line.debug_str.comment.note.GNU-stack.ARM.attributes.rel.debug_frame4!4'4J4,	�)@R^p�TZ	)�\�x	H)	���p��	�	`)�� �p� �	p)
2(8�	��))�Z;:�7	 0)J5	NF	8")^�	+Z	@")r�
0n	H" )��
`�	h"�)�>��	�") �0��0&�-�p-3�`d�	#0)&��d*'	t���
	
	�	
 "$&&#%).E�	OV]dkqread_maps.c$t$d.LC0s_linefree_mapsfree__aeabi_unwind_cpp_pr0read_mapsstrlenstrcmpsscanfmallocfgetsget_real_address
 
((*)
+"
+8
,T
-\
.h
.�
/��
*
)*)!!!!% )-4!;!B!I!W!^!e!l!s!|!�!�!�!�!�!�!�!�!!#!?!M![!i!w!�!�!�!�!�!�!�!�!�!�!�!	!).2AI!T
X
\ns!}�!��!��!�����!�!4!?CO!Y^!hv�!� $+/>BJNUYaelp��
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�





!
0
4
<
@
G
K
R
V
]
a
h
l
{

�
�
�
�
�
�
��������
 





 
$
(
,
0
4
@DH
L
PT]z
�$0$4
X$\

**Comment by garga3838** [comment]
Master

**Comment by garga3838** [comment]
_Envoyé depuis mon Galaxy Tab S2 en utilisant [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Panderner** [comment]
It translates to Sent from my Galaxy Tab S2 using FastHub. @garga3838 speak English not French

**Comment by benderscruffy** [comment]
No feedback/outdated?

**Comment by unknownbrackets** [comment]
Who knows, it always seems like libretro is a buggy mess.  But there are other issues about save state crashes and etc., so maybe this is a duplicate.

-[Unknown]

**Comment by gouchi** [comment]
@ds22x is it still an issue using [F-Droid RetroArch package](https://f-droid.org/en/packages/com.retroarch/) ? Thank you.

**Comment by ds22x** [comment]
It doesn't crash anymore on my phone.
