### ISSUE TITLE
Arctic Adventures: Polar's Puzzles Crashes on boot

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#12677]
### What happens?
When I boot the game the emulator crashes

### What *should* happen?
In order to prevent crashing for booting the game. change the I/O to Simulated UMD Delays
I/O timing Method Results:
Fast: Crashes
Host: Crashes
Simulated UMD Delays: The game Works

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Realme C2 Android 9 Pie PPSSPP v1.9.3-372-gbf7ed398a

**Comment by hrydgard** [comment]
Let's force this game to Simulated UMD Delays.

**Comment by Panderner** [comment]
This should be I/O Issue. This should be listed in #7647

**Comment by hrydgard** [comment]
Done. Closing this for now.

**Comment by unknownbrackets** [comment]
Just going to note that this game is a Mini, released only as a download.  UMD delays don't make sense for it, so it's definitely just papering over some bug.

-[Unknown]
