### ISSUE TITLE
User report: Brian Lara Cricket 2007 crash on start

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#12684]
According to a report I got by email, this game crashes immediately on Redmi Note 5 Pro (4 GB RAM).

**Comment by unknownbrackets** [comment]
Reference: https://report.ppsspp.org/game/ULES00814_1.01

Someone reported it playable in v1.7.5 with an Adreno 509, and it's been marked as working by other users.  The most recent Adreno 509 report saying it doesn't boot at all included this screenshot:

https://report.ppsspp.org/uploads/ULES00814_1.01/compat-287652.jpg

Are there any more details, log information, or a confirmation of the disc crc?

-[Unknown]

**Comment by hrydgard** [comment]
Hm. I guess this could very well just be a random corrupt iso report...

**Comment by Gamemulatorer** [comment]
Can't repro the crash issue of this game using ppsspp v1.9.3-960
![Screenshot_20200526-221901](https://user-images.githubusercontent.com/37603562/82912094-3d94cd80-9f9f-11ea-86bf-4c15c619e655.png)
![Screenshot_20200526-221938](https://user-images.githubusercontent.com/37603562/82912125-49808f80-9f9f-11ea-8a12-f4eaf594879a.png)

**Comment by Panderner** [comment]
@Gamemulatorer me too I can reach in game
![Screenshot_2020-05-27-01-13-26-36_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/82930110-6aed7580-9fb7-11ea-906c-814e73f7a5d6.png)

**Comment by hrydgard** [comment]
Alright, closing due to lack of confirmation of an actual problem.
