### ISSUE TITLE
Car Jack Streets Broken in Latest Build

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#12698]
### What happens?
When i start the game it stuck at white screen and it won't reach in game

### What *should* happen?
However The older versions work

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Realme C2 running Android 9 Pie ppsspp-v1.9.3-455-gaf604b143

**Comment by unknownbrackets** [comment]
What's the newest version that still works?  What's the first one that stopped working?

-[Unknown]

**Comment by Panderner** [comment]
I don't know if the someone's reported first build stopped working

**Comment by unknownbrackets** [comment]
Well, someone reported it working as recently as v1.9.4 in January:
https://report.ppsspp.org/game/NPUZ00043_1.02#report-compat-312259

But it was also reported to have a white screen at one point: #9065.

Maybe it depends on settings or gpu features?  Or maybe it broke again since v1.9.4.  Knowing which versions would help - there have been around 500 commits since then.  If you tried 9 builds, you could narrow it down.

-[Unknown]

**Comment by Panderner** [comment]
Same happens in stable version

**Comment by unknownbrackets** [comment]
Interestingly, it seems like the one reported as playable is a bad CRC... unfortunately, I don't have this game.  I guess we could try a GE dump, although it might not show much for a white screen.

-[Unknown]

**Comment by Panderner** [comment]
In GE Dump they reported there is no known error 
here's a GE Dump:
[recording.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/4310520/recording.ppdmp.zip)

**Comment by Panderner** [comment]
> unfortunately, I don't have this game

Here's a link for this game on Official PlayStation Store: https://store.playstation.com/en-us/product/UP4084-NPUZ00043_00-0000111122223365

**Comment by Panderner** [comment]
this isn't GE Emulation issue but I can't reach in-game

**Comment by shenweip** [comment]
This is a game bug about date, someone had  described this on [forum](https://forums.ppsspp.org/showthread.php?tid=804&pid=118884#pid118884) once.
I have confirmed this happened in a PSP too.

**Comment by Panderner** [comment]
What's the date when Car Jack Streets stopped working?

**Comment by shenweip** [comment]
2012/1/02 is the last working date.

**Comment by Panderner** [comment]
> 2012/1/02 is the last working date.

@shenweip It does it work on real PSP?

**Comment by shenweip** [comment]
yes, 2012/1/02 works on PSP, but 2012/1/03 stops working.
