### ISSUE TITLE
Render Duplicate Frames to 60hz not working in Skip Buffers Effects (Non-Buffered, Faster)

### ISSUE THREAD

**Issue by Emulatorer** [hrydgard/ppsspp#12724]
Default Settings Buffered Rendering
Render Duplicate Frames to 60hz is ON
PowerStone Collection
![Screenshot_20200318-103513](https://user-images.githubusercontent.com/37603562/76920160-c17a6b80-6905-11ea-992b-318787eab552.png)
Skip Buffers Effects (Non-Buffered, Faster)
Render Duplicate Frames to 60hz is ON
![Screenshot_20200318-103905](https://user-images.githubusercontent.com/37603562/76920215-df47d080-6905-11ea-80eb-994b1f286d4d.png)

### Solution
Grey Out The Render Duplicate Frames to 60hz when set to Skip Buffers Effects so user well not enable it during skip buffers mode?

**Comment by unknownbrackets** [comment]
Well, "skip buffer effects" means that we ignore what the game tries to do, and just draw everything directly to the screen.

As a side effect, when the game draws nothing - we draw nothing.  If we flip nothing, the display will flicker black every other frame in 30 FPS games.

We would have to use a buffer (that's the thing this disables) to remember what we drew last frame and draw it again so we can flip it.

-[Unknown]

**Comment by hrydgard** [comment]
Yeah this is not possible unfortunately. We might want to gray out the option.

Also I've been wanting to kill non-buffered mode for a long time ....

**Comment by Emulatorer** [comment]
Not added to Milestone v1.10.0?
