### ISSUE TITLE
Persona eternal punshment stuck on infinite loading screen

### ISSUE THREAD

**Issue by CommicKick69ing** [hrydgard/ppsspp#12734]
### What happens?
Eveytime a new game is started the game is stuck on an infinite loading screen. loading screen says
<img width="953" alt="Capture" src="https://user-images.githubusercontent.com/40266764/77141360-ff38da80-6a52-11ea-8101-8332207c5d3e.PNG">
"If there is save data for PSP® (PlayStation®Portable) version "persona 2 Sins", loading the data before the game starts may cause some change in the progress of this title."
### What *should* happen?
load, then dialouge box, then animated cutscene

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Windows 10  version 1.9.3

**Comment by Emulatorer** [comment]
Try the beta build of ppsspp 👉 https://buildbot.orphis.net/ppsspp/index.php?m=fulllist

**Comment by Panderner** [comment]
If this text box appears just press Circle Button

**Comment by Panderner** [comment]
If there is saved data for the PSP® (PlayStation®Portable) version of “Persona 2 Innocent Sin,” loading the data before the game starts may cause some changes in the progress of this title.
These Save files of Innocent Sin is only works in Japanese Versions of the game, and it doesn't work in international versions of the Game

**Comment by CommicKick69ing** [comment]
> If this text box appears just press Circle Button

Thanks :)
