### ISSUE TITLE
[Android/Windows][OpenGL&Vulkan][Input Kanji / 漢字] Problem of Input 2-byte characters. (Re-input timing)

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#12732]
### What happens?
It isn't an input screen of a kanji.
So,I can't enter the name of character by kanji.
Kanji is important factor for this game.

### What *should* happen?
Appear the input screen.
*PLease see below.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

PPSSPP Ver. : 1.9.3-519
OS: Android 9.0
DeviceName: SONY SO-02K / Xperia XZ1 Compact (Japan)
CPU: Snapdragon835 (Octa-core)
GPU: Adreno 540
Resolution: 720×1280
RAM: 4GB
ROM:32GB
ExternalStrage: microSDXC 512GB

[Input Screen in Real PSP]
![oresika_namae_kanji01](https://user-images.githubusercontent.com/48179091/77026286-a9265180-69d6-11ea-9df1-205daa16d630.png)

[Input Screen in PPSSPP for Android]
![oresika_namae_kanji99](https://user-images.githubusercontent.com/48179091/77026337-be02e500-69d6-11ea-858e-c35e0094deb6.png)

**Comment by nassau-tk** [comment]
Yes!
I will waiting the future!!

**Comment by hrydgard** [comment]
Haha. Yeah the problem is that we can't use the PSP's builtin text window, so we have to make our own - and without knowing Japanese it's hard to do better than the current stuff :)

We'd need someone who knows Japanese and C++ to contribute a better input method...

**Comment by nassau-tk** [comment]
Yes, I tried native text support.
It's good system!!

But, lt has a problem.
If touch out of lnput window then disappear the input window and can't play the game.

May be,I think the window goes background.

**Comment by nassau-tk** [comment]
Sorry,I found a different issue of native text support.

For example,,,
1:You can input 3 character(Max).
   A AB ABC Like this.
2:You input only 2 character.
   AB LIke this.
3:You tap the finish & OK.
4:The game screen is appear ”AB_” not  ”AB” 
5:Re open the input text area.
    It is appear  ”AB༬”

What is ”༬”???

Uuuum,,,l'm poor at my english.

**Comment by hrydgard** [comment]
Oh, that sounds like some kind of unicode bug. That needs fixing

**Comment by unknownbrackets** [comment]
The value uses `GetJavaString(env, jvalue)`... I wonder how that could get extra characters?  I couldn't reproduce in a game that supported more than 3 characters.

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, I don't know how it could possibly happen, but sure looks like it, or some off by one in us writing the text to PSP memory or something. Maybe it only happens with three- or four-byte utf-8 characters or something...

**Comment by unknownbrackets** [comment]
Well, OSK writes everything to PSP RAM as UCS-2 AFAIK.  But yeah, maybe there's some issue near the limit... it should be null terminating.  In theory, such a bug should reproduce on PC too (with the native keyboard option enabled.)

-[Unknown]

**Comment by nassau-tk** [comment]
Wao!!
Great !!
But, The issue happen at 1character too.
”A”  ==>  ”A_”       what's  ”ౠ”??!

And, Full screen mode(immersive) unlock when appear the input screen.

**Comment by unknownbrackets** [comment]
Hm, so you're getting U+0C60 when entering 1 character, and U+0F2C when entering two.  But it's always only one extra character.

Hm.  It only writes to outText characters within `inputChars.size()`, so it seems like this must be a bug in non-Windows ConvertUTF8ToWString?

-[Unknown]

**Comment by hrydgard** [comment]
I think we should make sure to use the same UTF8ToWString function for PSP purposes on all platforms, then we might see and be able to debug this on Windows as well if it's a bug in that. We should only use the Windows-native conversion functions when dealing with Windows APIs, for consistency.

I'm gonna give it a shot.

**Comment by hrydgard** [comment]
@nassau-tk  Could you try the latest build from https://buildbot.orphis.net/ppsspp/ ? Please report back whether it works or not.

**Comment by nassau-tk** [comment]
@hrydgard I tried latest buid at v1.9.3-548-gedbd01807 by @unknownbrackets .
It'll be reported from a result.
**Not appear the input charachter.**
1character~~3character all.

![UCJS10117_00](https://user-images.githubusercontent.com/48179091/77269977-e26c0380-6ced-11ea-97e7-35f7bf4207d1.png)

![UCJS10117_01](https://user-images.githubusercontent.com/48179091/77269984-e7c94e00-6ced-11ea-87de-0a7b3f4e49c1.png)

![UCJS10117_02](https://user-images.githubusercontent.com/48179091/77269993-ed269880-6ced-11ea-871f-00ac351d1684.png)

![UCJS10117_03](https://user-images.githubusercontent.com/48179091/77270000-f283e300-6ced-11ea-8d14-2fbe5ae4cc8f.png)

![UCJS10117_04](https://user-images.githubusercontent.com/48179091/77270010-f879c400-6ced-11ea-8827-74726d6314f0.png)

**Comment by nassau-tk** [comment]
By the way....
Immersive mode will resume when re-check in the setting screen.
**A check doesn't come off.**
So,This is meaning check off ==> check on.

**Comment by unknownbrackets** [comment]
Oops.  56a1b6d fixes the blank string and immersive reset issues.  It'll take a bit of time to build.

Thanks for the retesting.

-[Unknown]

**Comment by nassau-tk** [comment]
@unknownbrackets 
@hrydgard

 I tried latest buid at v1.9.3-550-g56a1b6d03.
It's working!?

But,Other issue will born!!
This isseu very difficulut to tell others by me....
Please,read below...

【Normal-case】
Step1: Enter the 3characters.(Max 3characters)
Step2: Appear the 3characters on the game screen.
　　　==>  ABC
Step3: Re-open the input screen.
Step4: Enter a only 1 character.
　　　==>  D
Step5: Appear the 2characters on the game screen!!
           Step4's 1character + Step 2's last character
　　　==> DC

And, If you return the "PPSSPP Menu screen" and re-start the game.
Theese input characters are remind from memory.
But, It didn't happen when shutdown the "PPSSPP".

If you clear all charaters, then the characters deleted on gam screen.
But,Appear the last one of 3characteres when input 1 character.

The issue not happen when input 2 characters on Step 4.

input 3characters
==>input 2characters
       ==>input 1characters
This case will not happen the issue.

It must happen input 1 character after input over 3 characters.

【A worst case scenario test】
Step1: Enter the **5** characters.(Max**3**Characters)
　　　==>  ABCDE
Step2: Appear the 3 characters on the play screen.
　　　==>  ABC
Step3: Re-open the input screen.
Step4: Enter a only 1 character.
　　　==>  Z
Step5: Appear the 3 characters on the play screen!!
　　　Step4's 1character + Step 2's number of 3&4  characters.
　　　==> Z**CD**
　　　Not last 2 characters.(I'm confuse...)

Sorry, will you understand?
I'm getting stuck in a bottomless swamp!! Ahaha!!
When you can understand well, I'm happy.

**Comment by unknownbrackets** [comment]
Thanks for the careful explanation.  I definitely understand the problem, and it's very interesting.

I don't have Ore no Shikabane wo Koeteyuke, but I tried with PixelJunk Monsters Deluxe.  Its limit is 11 characters.  But in that game, these scenarios (typing 13 characters, for example, etc.) work normally.

The most interesting thing is that it remembers what you put last time.  The initial value should always come from the game, and if the game doesn't provide one, we put "VALUE".  I can't find where it would remember after stopping the game.

-[Unknown]

**Comment by nassau-tk** [comment]
Yes,l was confuse by it.

By the way, it's the system to keep doing child making and taking the name over, but is this game the cause? Ahaha!!

**Comment by nassau-tk** [comment]
@unknownbrackets 

Um...
It will only happen when using "2-byte characters".
Example: Kanji/Hiragana/Katakana/SpecialMarks

1. Enter the 2-byte characters on input dialog.
   (Example: 海山川)
2. Re-open the input dialog and delete them.
    And input only 1-byte characters.(Example: abc)
3. Probably, It will appear the correctly. (abc)
4. Re-open the input dialog and delete them.
    And input only 1 letter of 2-byte character.(Example: 谷)
5. Probably, It will appear the 谷＋川. (谷川)

This issue has related with 2-byte characters.

Did you test only 1-byte characters on Pixel Junk Monsters Delux don't you?

**Comment by nassau-tk** [comment]
v1.17.1-350
It was solved!!
But, Sorry I don't know when it solved.
