### ISSUE TITLE
[Feature request] Add that two buttons become one

### ISSUE THREAD

**Issue by Drasikk** [hrydgard/ppsspp#12736]
# What happens?

It would be possible to add within the section "Controls" ==> assign button. If for example with a game I rotate the camera with the L1 button + direction button above, you can do it with just a button or with the right joystick squeezing up. I don't know if I explain myself...

**Comment by Emulatorer** [comment]
Similar of #12631?

**Comment by Drasikk** [comment]
I want to do it from a bluetooth controller (Dual Shock 4 v2).

**Comment by LunaMoo** [comment]
You can do that already. Assign same physical input to different emulated controls and it will "press" them together while you use just one physical key.

**Comment by Drasikk** [comment]
@LunaMoo What do you mean?

**Comment by Drasikk** [comment]
![PPSSPP_2020-03-20-15-19-53](https://user-images.githubusercontent.com/38067925/77172465-490ada80-6abe-11ea-9ca0-42d2a4990c41.jpg)

If I put it that way, I still depend on the L1 button + right joystick. What I want is for the right joystick to do that same function but only with one button.

**Comment by LunaMoo** [comment]
Just assign same button of your gamepad to two or more different PSP buttons. Can't explain that easier.

**Comment by Drasikk** [comment]
Okay, I get it. I had to change the L1 buttons to the right joystick (up, right, left and down). Thank you!

![PPSSPP_2020-03-20-15-37-03](https://user-images.githubusercontent.com/38067925/77173992-b1f35200-6ac0-11ea-9179-90fee341811c.jpg)
