### ISSUE TITLE
Final Fantasy Tactics: The War Of The Lions Unstable FPS and Slowdown

### ISSUE THREAD

**Issue by Emulatorer** [hrydgard/ppsspp#12731]
This game randomly change the fps from 30/30 - 60/60 - 15/15 FPS and become very slow here's my screenshot below
![Screenshot_20200319-103428](https://user-images.githubusercontent.com/37603562/77026432-9445c000-69ce-11ea-831e-e1443c1725bd.png)
![Screenshot_20200319-103433](https://user-images.githubusercontent.com/37603562/77026442-9c056480-69ce-11ea-8e1f-5a9a1897cf06.png)
![Screenshot_20200319-103513](https://user-images.githubusercontent.com/37603562/77026450-a162af00-69ce-11ea-81ed-1cb8a24b1ea6.png)

Im using ppsspp beta build v1.9.3-513
My phone specs:
[DevCheck-20200319-1045.txt](https://github.com/hrydgard/ppsspp/files/4352419/DevCheck-20200319-1045.txt)
GE Dump:
[ULUS10297.zip](https://github.com/hrydgard/ppsspp/files/4352420/ULUS10297.zip)

**Comment by Emulatorer** [comment]
PSP Gameplay
https://youtu.be/P1PnbuavER4
PPSSPP Solution for slowdown?
https://youtu.be/TVT6ipj1q8E

**Comment by LunaMoo** [comment]
The gameplay you marked as PSP is from PPSSPP, just patched as explained in the other video you also linked. This is not a PPSSPP bug, the game itself behave like that on real console and has to be patched. Closing.

**Comment by Emulatorer** [comment]
I don't know how to patch via android 😔
![Screenshot_20200319-130711](https://user-images.githubusercontent.com/37603562/77033609-ad586c00-69e2-11ea-8f91-fea8ea40033a.png)

**Comment by Emulatorer** [comment]
Correct label for this is Game Bug I think 🤔

**Comment by Panderner** [comment]
But I needed to test a real PSP that drops to 15 FPS for spell attack scenes
