### ISSUE TITLE
Memstick warning issues

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#12753]
There's a issues when memstick warning has problem for some games.

Jetpack Joyride:
![Screenshot_2020-03-23-21-55-55-10_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/77325136-bf276f80-6d52-11ea-9b3e-732e5866cdea.png)
Bomberman:
![Screenshot_2020-03-24-11-20-52-48_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/77384925-9ee2c980-6dc1-11ea-8e2b-74be9d14e102.png)

Sword Art Online:
https://streamable.com/rrhby

**Comment by hrydgard** [comment]
This is an effect of using the system fonts in the dialog I guess. Yeah, needs fixing.

**Comment by unknownbrackets** [comment]
Are you talking about the positioning of the text, or about the warning showing at all?

I saw a log that made me suspect a game might clear the FAT archive bit on savedata to detect someone modifying files on their PC...

-[Unknown]

**Comment by Panderner** [comment]
> Are you talking about the positioning of the text, or about the warning showing at all?
> 
> I saw a log that made me suspect a game might clear the FAT archive bit on savedata to detect someone modifying files on their PC... a bit we don't support.
> 
> -[Unknown]

Yes. Bomberman Stuck at memstick screen unless when I move to the left and press X button

**Comment by Emulatorer** [comment]
YES or NO text overlay bug in Bomberman and other games
### WRONG
![Screenshot_20200323-221510](https://user-images.githubusercontent.com/37603562/77377408-fc6d1b00-6dad-11ea-9889-6b8b6573950d.png)
### CORRECT
![Screenshot_20200323-222111](https://user-images.githubusercontent.com/37603562/77377474-232b5180-6dae-11ea-9c6b-dcb533995958.png)
