### ISSUE TITLE
Gangs of London crash on startup

### ISSUE THREAD

**Issue by Levan7** [hrydgard/ppsspp#12754]
Using the PPSSPP v1.9.3-513-g25197451e Windows 64 bit build and when i start the game it crashes on startup 

[debug.zip](https://github.com/hrydgard/ppsspp/files/4370095/debug.zip)

**Comment by hrydgard** [comment]
Possibly related to #12752 ?

**Comment by unknownbrackets** [comment]
I don't think so.  This is already noted in #7239.  The demo hits invalid addresses on startup and has for a while.  I double checked that v1.9.0 did.

-[Unknown]

**Comment by hrydgard** [comment]
Closing as duplicate of #7239.
