### ISSUE TITLE
PPSSPP not registering keyboard input

### ISSUE THREAD

**Issue by KirbyFan102** [hrydgard/ppsspp#12775]
### What happens?
PPSSPP emulator does not accept keyboard controls, in fact I cannot even change them in config.

### What *should* happen?
Emulator registers keyboard inputs properly.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

I'm using the emulator on Windows 10, and the latest version of PPSSPP for desktop.

**Comment by hrydgard** [comment]
Sounds bizarre, it certainly works for me. You can't even use the arrow keys to navigate the main screen?

**Comment by KirbyFan102** [comment]
Ok, I have just discovered that this problem seems to be occuring only on one game: Crisis Core. When I tested it with Metal Slug XX, it worked fine, but Crisis Core registers no keyboard inputs, not even the arrows. I have to activate onscreen controls to play it.

**Comment by hrydgard** [comment]
Sounds like you have created a per-game config with the keyboard unmapped maybe? You can delete the game-specific config by pressing ESC within the game to get the pause menu, in which you can press "Delete Game Config".

**Comment by KirbyFan102** [comment]
I tried what you said. There was no game config, but I created a new one and then deleted it, and now the game works. Very weird. But at least the problem is solved.

**Comment by hrydgard** [comment]
Wacky. Hm. Oh well...

**Comment by KirbyFan102** [comment]
Okay, the problem reocurred when I was playing Dissidia 012, so reopening this issue. And in fact, I have to say that I was mistaken when I thought that creating and deleting the game config solved the issue. The mere fact it responded to my pressing ESC was a sign it wasn't suffering from the problem at the time, as I just now confirmed when I pressed it and it didn't bring up the pause menu.

However, I have discovered what causes it to occur. When I open a game by clicking on its thumbnail, the game registers keyboard inputs fine. If I try to open a game by clicking on 'file' and then on 'load iso', the problem occurs (though fortunately onscreen controls work). This has held true all the times I tested this. At least I now have a way to reliably play the games with the keyboard now, but this _really_ should get fixed.

**Comment by hrydgard** [comment]
Even stranger!

I can't reproduce this problem at all. File+Load works fine.

Are you using any external programs to map joysticks to keyboard, or overlays, or something like that? Accessibility options?

**Comment by KirbyFan102** [comment]
Nothing of that sort, no.

**Comment by unknownbrackets** [comment]
The difference you describe implies it could be related to a shell extension.  Programs can install "shell extensions" to hook into native Windows file dialogs, and control file icons or behavior when you right click on files.

File -> Load... would be pulling in file extensions for the Windows open dialog.

To test this theory, start a game using the recent list (not the dialog), and then select File -> Load state file.  In that dialog, browse to the same folders you did when the issue occurred.  But then just click Cancel without loading anything.

If my theory is correct, doing that should still reproduce the issue.

-[Unknown]

**Comment by KirbyFan102** [comment]
Yes, it did happen as you said. Merely opening the load window caused the issue to occur. But how do I discover the cause of this?

**Comment by unknownbrackets** [comment]
https://www.nirsoft.net/utils/shexview.html (https://www.nirsoft.net/utils/shexview.html#DownloadLinks)

You can use this utility to view installed shell extensions, turn them off and on, and find the problem child.  I'd recommend leaving any by Microsoft Corporation enabled.

It is also possible it's something related to the dialog but not a shell extension, so maybe this won't help.  But I think a shell extension is most likely.

-[Unknown]

**Comment by KirbyFan102** [comment]
I'm currently very busy... but I'll try this and if it works, I'll come back to you guys.

**Comment by KirbyFan102** [comment]
Well, I tried using the program you recommended, but it's brought me no closer to finding out what's causing the problem. I disabled every extension not made by microsoft, yet the problem persists. And if it is a Microsoft extension causing it, I doubt disabling them would be advisable. Is there anything more I could try?

**Comment by unknownbrackets** [comment]
You could look at task manager for running processes, or try [safe mode](https://support.microsoft.com/en-us/help/12376/windows-10-start-your-pc-in-safe-mode) to confirm it's some extension or background process.

It's hard to guess what it might be though.

Does anything like this happen in other apps, like say Nestopia or PCSX2 something?  You'll want something that uses a regular file dialog, so not JPCSP or Retroarch.

-[Unknown]

**Comment by KirbyFan102** [comment]
No, the problem is exclusive to PPSSPP.

**Comment by unknownbrackets** [comment]
I don't think we've gotten any other reports of this or been able to reproduce.  Have any OS/driver updates changed the situation, and does it happen in the latest git build?

There were some changes to file path handling recently that could've potentially affected this, although I don't have high hopes.

If it's still happening, could you try:
 * Create a new folder and put an ISO in it.  Ideally, put this folder on C:\.
 * File -> Load to open that ISO (and reproduce this bug.)
 * Exit PPSSPP.
 * Start again and try loading that ISO (without browsing or seeing any other files.)

Does that also reproduce?

Also, right click on PPSSPPWindows64 (hopefully you are using the 64-bit version), and go to Properties.  Then switch to the Compatibility tab.  Make sure Compatibility mode is NOT enabled, and none of the other settings are enabled.

-[Unknown]

**Comment by KirbyFan102** [comment]
No, the problem is currently not ocurring, from what I can tell. Perhaps some Windows/Driver updates changed the source of the problem, but I cannot be sure at this point.

Even if it was, I doubt any recent changes could have been the cause, considering this thread was opened a year ago. If it does reoccur, I'll make sure to reopen it.

**Comment by unknownbrackets** [comment]
Thanks for validating, glad to hear it's resolved.

-[Unknown]
