### ISSUE TITLE
Yggdra Union --- Not Playable in Switch

### ISSUE THREAD

**Issue by Master-RX** [hrydgard/ppsspp#12776]
### What happens?
Game loads but cannot start New Game, always close the program (PPSSPP) unexpectedly. 
It also happens when loading a game save (Use a PPSSPP PC save of the game), winning or losing a combat, when the game try to show the morale screen at the end of the battle, it closes the program (PPSSPP) unexpectedly

### What *should* happen?
The game should run smoothly creating a new game or loading a game save and progressing through the game

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Nintendo Switch 9.1.0 / AltlasNX-Kosmos (AMS 0.10.2)
PPSSPP Version v1.9.3-476 in GL and GLES Mode
Adjusted options in FAQ´s for errors in Games before reporting an issue
2 ISOs from the same area (NTSC) were used

Sorry for my bad english

**Comment by unknownbrackets** [comment]
Hm.  I remember there being an issue on the morale screen at one point, though I can't find it.  It was a long time ago and I think it was just a graphics issue...

Are there any logs or anything available when PPSSPP crashes on Switch?

Not sure if the option is there, but can you try developer tools -> cpu core -> ir interpreter?  It'll be kinda slow, but if it gets passed the crash, that's very useful to know.

Another setting to try (after flipping that back to jit) would be "fast memory" in System.

If neither of these change anything, then it's hopefully a graphics related crash.  Even if either of the above help, it's still a bug, it just tells us where it is (all games should run properly with jit + fast memory.)

-[Unknown]

**Comment by Master-RX** [comment]
- Tested in IR interpreter in GL and GLES mode, same result. the program close unexpectedly

- Other Games runs ok (megaman maveric hunter x / dissidia 012 / Gran turismo) with default options

- Fast memory is disabled and enabled with the same results

where I find the debugger logs, I see that it is active by default but I don't know where it saves them?

**Comment by unknownbrackets** [comment]
If you open PPSSPP on the Switch with the remote debugger enabled, you can then go to this URL on any device (such as a PC) connected to the same wifi network:
http://ppsspp-debugger.unknownbrackets.org/

It will at least show some logs, but it won't give us the crash stack trace.  I don't know how to get that on a Switch.  I'm also not certain (but I am hopeful) that the remote debugger works on Switch.

-[Unknown]

**Comment by Master-RX** [comment]
The remote debbuger open and run (the URL opens from a PC connected to the same network and shows something when starting the game but closes the connection as soon as the error is generated). 

Should I do something to save the debug results? I'm not really an expert on these topics

**Comment by unknownbrackets** [comment]
You can copy the text in the black part of the screen and paste it here.  It disconnects when the emulator crashes, so the most interesting part will be right before the disconnect.  But it may not say much.

In developer tools you can change the log level to "Debug" from "Info" which will make it provide more detail.

You can put three backticks - \`\`\` - on separate lines above and below the pasted logs to format them a bit better.

-[Unknown]

**Comment by Master-RX** [comment]
this appears after load a snapstop of the game (I think they are called save state) and progress in the game. It is the only way in which I see that it generates some logs in this URL

> 43:33:262 user_main    I[SCEKERNEL]: HLE/sceKernelThread.cpp:1997 304=sceKernelCreateThread(CRI ADXATR Waveout Thread1, 089059c4, 00000010, 16384, 00000000, 00000000)
43:33:262 user_main    I[SCEKERNEL]: HLE/sceKernelThread.cpp:1997 306=sceKernelCreateThread(CRI ADXATR Waveout Thread1, 089059c4, 00000010, 16384, 00000000, 00000000)
43:33:428 NowLoading   I[SCEKERNEL]: HLE/sceKernelThread.cpp:2143 sceKernelExitThread(0)
43:33:428 user_main    I[HLE]: HLE/scePower.cpp:439 scePowerSetClockFrequency(222,222,111)
43:33:454 CRI ADX Audi I[ME]: HLE/sceAtrac.cpp:1910 0=sceAtracSetDataAndGetID(08c6f7c0, 00004000): atrac3+ stereo audio
43:33:473 CRI ADX Audi I[SCEKERNEL]: HLE/sceKernelThread.cpp:2088 0=sceKernelStartThread(304, 4, 09fbda50)
43:33:639 user_main    I[SCEUTIL]: Dialog/PSPSaveDialog.cpp:90 sceUtilitySavedataInitStart(08a89d58) - SIZES (8)
43:33:639 user_main    I[SCEUTIL]: Dialog/PSPSaveDialog.cpp:91 sceUtilitySavedataInitStart(08a89d58) : Game key (hex): F44CB0FA118F38471BB2116377C6F062
43:33:895 user_main    I[SCEUTIL]: Dialog/PSPSaveDialog.cpp:90 sceUtilitySavedataInitStart(08a89d58) - SIZES (8)
43:33:895 user_main    I[SCEUTIL]: Dialog/PSPSaveDialog.cpp:91 sceUtilitySavedataInitStart(08a89d58) : Game key (hex): F44CB0FA118F38471BB2116377C6F062
43:34:162 user_main    I[SCEUTIL]: Dialog/PSPSaveDialog.cpp:90 sceUtilitySavedataInitStart(08a89d58) - SIZES (8)
43:34:162 user_main    I[SCEUTIL]: Dialog/PSPSaveDialog.cpp:91 sceUtilitySavedataInitStart(08a89d58) : Game key (hex): F44CB0FA118F38471BB2116377C6F062
43:34:467 user_main    I[SCEUTIL]: Dialog/PSPSaveDialog.cpp:90 sceUtilitySavedataInitStart(08a89d58) - LIST (11)
43:34:467 user_main    I[SCEUTIL]: Dialog/PSPSaveDialog.cpp:91 sceUtilitySavedataInitStart(08a89d58) : Game key (hex): F44CB0FA118F38471BB2116377C6F062
43:34:712 user_main    I[SCEUTIL]: Dialog/PSPSaveDialog.cpp:90 sceUtilitySavedataInitStart(08a89d58) - LIST (11)
43:34:712 user_main    I[SCEUTIL]: Dialog/PSPSaveDialog.cpp:91 sceUtilitySavedataInitStart(08a89d58) : Game key (hex): F44CB0FA118F38471BB2116377C6F062
43:34:979 user_main    I[SCEUTIL]: Dialog/PSPSaveDialog.cpp:90 sceUtilitySavedataInitStart(08a89d58) - LIST (11)
43:34:979 user_main    I[SCEUTIL]: Dialog/PSPSaveDialog.cpp:91 sceUtilitySavedataInitStart(08a89d58) : Game key (hex): F44CB0FA118F38471BB2116377C6F062
43:35:300 user_main    I[SCEUTIL]: Dialog/PSPSaveDialog.cpp:90 sceUtilitySavedataInitStart(08a89d58) - AUTOLOAD (0)
43:35:300 user_main    I[SCEUTIL]: Dialog/PSPSaveDialog.cpp:91 sceUtilitySavedataInitStart(08a89d58) : Game key (hex): F44CB0FA118F38471BB2116377C6F062
43:35:483 idle0        I[SCEUTIL]: Dialog/SavedataParam.cpp:618 Loading file with size 200 in ms0:/PSP/SAVEDATA/ULUS10368YggdraUnion.Sys/SYSTEM
43:48:522 idle0        I[SAVESTATE]: Core/SaveState.cpp:743 Loading state from /switch/ppsspp/config/ppsspp/PSP/PPSSPP_STATE/ULUS10368_1.00_0.ppst
43:48:882 idle0        I[G3D]: Common/TextureCacheCommon.cpp:1580 Texture cached cleared from 6 textures
43:48:882 idle0        I[FRAMEBUF]: GLES/FramebufferManagerGLES.cpp:682 Destroying FBO for 04000000 : 480 x 272 x 3
43:48:882 idle0        I[FRAMEBUF]: GLES/FramebufferManagerGLES.cpp:682 Destroying FBO for 04088000 : 480 x 272 x 3
43:49:177 idle0        I[SAVESTATE]: Common/ChunkFile.h:637 ChunkReader: Done loading /switch/ppsspp/config/ppsspp/PSP/PPSSPP_STATE/ULUS10368_1.00_0.ppst
43:49:218 user_main    I[FRAMEBUF]: Common/FramebufferCommon.cpp:452 Creating FBO for 04000000 : 480 x 272 x 3
43:49:241 user_main    I[FRAMEBUF]: Common/FramebufferCommon.cpp:452 Creating FBO for 04088000 : 480 x 272 x 3
43:57:973 user_main    I[ME]: HLE/sceAtrac.cpp:1671 0=sceAtracReleaseAtracID(1)
43:57:988 CRI ADX Audi I[ME]: HLE/sceAtrac.cpp:1910 1=sceAtracSetDataAndGetID(08d021c0, 00004000): atrac3+ stereo audio
44:06:252 user_main    I[HLE]: HLE/scePower.cpp:439 scePowerSetClockFrequency(266,266,133)
44:06:412 user_main    I[ME]: HLE/sceAtrac.cpp:1671 0=sceAtracReleaseAtracID(0)
44:06:412 user_main    I[ME]: HLE/sceAtrac.cpp:1671 0=sceAtracReleaseAtracID(1)
44:06:560 CRI ADX Audi I[ME]: HLE/sceAtrac.cpp:1910 0=sceAtracSetDataAndGetID(08c6f7c0, 00004000): atrac3+ stereo audio
44:06:662 CRI ADX Audi I[ME]: HLE/sceAtrac.cpp:1910 1=sceAtracSetDataAndGetID(08d021c0, 00004000): atrac3+ stereo audio
44:14:250 user_main    I[HLE]: HLE/scePower.cpp:439 scePowerSetClockFrequency(222,222,111)
44:21:123 user_main    I[HLE]: HLE/scePower.cpp:439 scePowerSetClockFrequency(266,266,133)
44:39:092 user_main    I[ME]: HLE/sceAtrac.cpp:1671 0=sceAtracReleaseAtracID(1)
44:39:109 CRI ADX Audi I[ME]: HLE/sceAtrac.cpp:1910 1=sceAtracSetDataAndGetID(08d021c0, 00004000): atrac3+ stereo audio
Debugger disconnected

**Comment by Master-RX** [comment]
I'm going to test the info mode in the debug and upload what appears

**Comment by Master-RX** [comment]
This in info activated in debug mode

> 52:56:749 idle0        I[SAVESTATE]: Core/SaveState.cpp:743 Loading state from /switch/ppsspp/config/ppsspp/PSP/PPSSPP_STATE/ULUS10368_1.00_0.ppst
52:57:105 idle0        I[G3D]: Common/TextureCacheCommon.cpp:1580 Texture cached cleared from 9 textures
52:57:105 idle0        I[FRAMEBUF]: GLES/FramebufferManagerGLES.cpp:682 Destroying FBO for 04000000 : 480 x 272 x 3
52:57:105 idle0        I[FRAMEBUF]: GLES/FramebufferManagerGLES.cpp:682 Destroying FBO for 04088000 : 480 x 272 x 3
52:57:399 idle0        I[SAVESTATE]: Common/ChunkFile.h:637 ChunkReader: Done loading /switch/ppsspp/config/ppsspp/PSP/PPSSPP_STATE/ULUS10368_1.00_0.ppst
52:57:438 user_main    I[FRAMEBUF]: Common/FramebufferCommon.cpp:452 Creating FBO for 04000000 : 480 x 272 x 3
52:57:461 user_main    I[FRAMEBUF]: Common/FramebufferCommon.cpp:452 Creating FBO for 04088000 : 480 x 272 x 3
53:03:190 user_main    I[ME]: HLE/sceAtrac.cpp:1671 0=sceAtracReleaseAtracID(1)
53:03:217 CRI ADX Audi I[ME]: HLE/sceAtrac.cpp:1910 1=sceAtracSetDataAndGetID(08d021c0, 00004000): atrac3+ stereo audio
53:17:192 user_main    I[HLE]: HLE/scePower.cpp:439 scePowerSetClockFrequency(266,266,133)
53:17:351 user_main    I[ME]: HLE/sceAtrac.cpp:1671 0=sceAtracReleaseAtracID(0)
53:17:351 user_main    I[ME]: HLE/sceAtrac.cpp:1671 0=sceAtracReleaseAtracID(1)
53:17:499 CRI ADX Audi I[ME]: HLE/sceAtrac.cpp:1910 0=sceAtracSetDataAndGetID(08c6f7c0, 00004000): atrac3+ stereo audio
53:17:601 CRI ADX Audi I[ME]: HLE/sceAtrac.cpp:1910 1=sceAtracSetDataAndGetID(08d021c0, 00004000): atrac3+ stereo audio
53:21:155 user_main    I[HLE]: HLE/scePower.cpp:439 scePowerSetClockFrequency(222,222,111)
53:25:972 user_main    I[HLE]: HLE/scePower.cpp:439 scePowerSetClockFrequency(266,266,133)
53:32:079 user_main    I[ME]: HLE/sceAtrac.cpp:1671 0=sceAtracReleaseAtracID(1)
53:32:097 CRI ADX Audi I[ME]: HLE/sceAtrac.cpp:1910 1=sceAtracSetDataAndGetID(08d021c0, 00004000): atrac3+ stereo audio
Debugger disconnected

**Comment by unknownbrackets** [comment]
Hm, not a lot to go on.  An ATRAC3+ crash seems unlikely to be Switch-specific.  @m4xw is there a way to get details on a crash?

-[Unknown]

**Comment by Master-RX** [comment]
and this in debug flag activated, sorry for not understanding better

> 09:04:347 idle0        I[SAVESTATE]: Core/SaveState.cpp:743 Loading state from /switch/ppsspp/config/ppsspp/PSP/PPSSPP_STATE/ULUS10368_1.00_0.ppst
09:04:703 idle0        I[G3D]: Common/TextureCacheCommon.cpp:1580 Texture cached cleared from 3 textures
09:04:703 idle0        I[FRAMEBUF]: GLES/FramebufferManagerGLES.cpp:682 Destroying FBO for 04000000 : 480 x 272 x 3
09:04:703 idle0        I[FRAMEBUF]: GLES/FramebufferManagerGLES.cpp:682 Destroying FBO for 04088000 : 480 x 272 x 3
09:04:999 idle0        I[SAVESTATE]: Common/ChunkFile.h:637 ChunkReader: Done loading /switch/ppsspp/config/ppsspp/PSP/PPSSPP_STATE/ULUS10368_1.00_0.ppst
09:05:038 user_main    I[FRAMEBUF]: Common/FramebufferCommon.cpp:452 Creating FBO for 04000000 : 480 x 272 x 3
09:05:061 user_main    I[FRAMEBUF]: Common/FramebufferCommon.cpp:452 Creating FBO for 04088000 : 480 x 272 x 3
09:09:473 user_main    I[ME]: HLE/sceAtrac.cpp:1671 0=sceAtracReleaseAtracID(1)
09:09:485 idle0        N[SCEDISP]: HLE/sceDisplay.cpp:538 Dropping frames - budget = 16.68ms / 59.9fps, actual = 20.90ms (+4.22ms) / 47.8fps
Kernel processing time: 3.07 ms
Slowest syscall: sceGeListUpdateStallAddr : 0.66 ms
Most active syscall: sceGeListUpdateStallAddr : 2.79 ms
DL processing time: 2.76 ms
Draw calls: 51, flushes 51, clears 1
Cached Draw calls: 0
Num Tracked Vertex Arrays: 0
GPU cycles executed: 6626 (20.000000 per vertex)
Commands per call level: 653 0 0 0
Vertices submitted: 266
Cached, Uncached Vertices Drawn: 0, 268
FBOs active: 2
Textures active: 44, decoded: 6  invalidated: 1
Readbacks: 0, uploads: 0
Vertex, Fragment, Programs loaded: 7, 4, 10

09:09:488 CRI ADX Audi I[ME]: HLE/sceAtrac.cpp:1910 1=sceAtracSetDataAndGetID(08d021c0, 00004000): atrac3+ stereo audio
09:18:301 user_main    I[HLE]: HLE/scePower.cpp:439 scePowerSetClockFrequency(266,266,133)
09:18:462 user_main    I[ME]: HLE/sceAtrac.cpp:1671 0=sceAtracReleaseAtracID(0)
09:18:462 user_main    I[ME]: HLE/sceAtrac.cpp:1671 0=sceAtracReleaseAtracID(1)
09:18:610 CRI ADX Audi I[ME]: HLE/sceAtrac.cpp:1910 0=sceAtracSetDataAndGetID(08c6f7c0, 00004000): atrac3+ stereo audio
09:18:711 CRI ADX Audi I[ME]: HLE/sceAtrac.cpp:1910 1=sceAtracSetDataAndGetID(08d021c0, 00004000): atrac3+ stereo audio
09:22:513 idle0        N[SCEDISP]: HLE/sceDisplay.cpp:538 Dropping frames - budget = 16.68ms / 59.9fps, actual = 18.42ms (+1.74ms) / 54.3fps
Kernel processing time: 5.32 ms
Slowest syscall: sceAtracDecodeData : 0.77 ms
Most active syscall: sceGeListUpdateStallAddr : 4.32 ms
DL processing time: 4.14 ms
Draw calls: 300, flushes 300, clears 1
Cached Draw calls: 0
Num Tracked Vertex Arrays: 0
GPU cycles executed: 108244 (20.151575 per vertex)
Commands per call level: 3602 0 0 0
Vertices submitted: 5014
Cached, Uncached Vertices Drawn: 0, 5154
FBOs active: 2
Textures active: 40, decoded: 3  invalidated: 0
Readbacks: 0, uploads: 0
Vertex, Fragment, Programs loaded: 8, 5, 11

09:23:847 user_main    I[HLE]: HLE/scePower.cpp:439 scePowerSetClockFrequency(222,222,111)
09:29:518 user_main    I[HLE]: HLE/scePower.cpp:439 scePowerSetClockFrequency(266,266,133)
09:36:442 user_main    I[ME]: HLE/sceAtrac.cpp:1671 0=sceAtracReleaseAtracID(1)
09:36:461 CRI ADX Audi I[ME]: HLE/sceAtrac.cpp:1910 1=sceAtracSetDataAndGetID(08d021c0, 00004000): atrac3+ stereo audio
Debugger disconnected

**Comment by unknownbrackets** [comment]
Is there a crash report in atmosphere/crash_reports?  Apparently that's where it should show details about the actual crash.  I don't know exactly how to access it.

-[Unknown]

**Comment by Master-RX** [comment]
Hello, good day and thanks for the quick response. indeed I see several logs in that folder and some dumps ... I will attach those of that day when I carry out the tests.

I attach them directly through this platform or do I upload them somewhere?

**Comment by unknownbrackets** [comment]
You can zip them up and upload by dragging into the comment box here.

-[Unknown]

**Comment by Master-RX** [comment]
Ok. here is the files 
[crash_reports.zip](https://github.com/hrydgard/ppsspp/files/4416399/crash_reports.zip)

**Comment by m4xw** [comment]
@Master-RX Please delete all files/folders in crash_reports, then start the GLES or GL ver (you need to tell me which one you used!) and then upload the newly generated relevant crash reports.

**Comment by m4xw** [comment]
@Master-RX I did a debug build with the GL versions so we have the symbols, please use the NRO from https://m4xw.net/nextcloud/index.php/s/77rBMiRaTSsirmB

**Comment by Master-RX** [comment]
Hello @m4xw , Here
[PPSSPP_gl.zip](https://github.com/hrydgard/ppsspp/files/4416467/PPSSPP_gl.zip)
[PPSSPP_gles2.zip](https://github.com/hrydgard/ppsspp/files/4416468/PPSSPP_gles2.zip)

These correspond to the game when trying to start a new game, although the same thing happens when a fight ends when it shows victory or loss and the morale meter

 is the files

**Comment by m4xw** [comment]
Heh, sorry i guess i was a bit late, can u delete the reports and just try my specific ver?
Ideally include a log too if you can.

**Comment by Master-RX** [comment]
Ok, in a while I test it and send you details with the version that it sent me. I am working remotely due to quarantine and it will take a while

**Comment by Master-RX** [comment]
@m4xw where does the .elf file go?, I delete the asset folder and the .nro and I am replacing them with the sent ones but I don't see that elf

**Comment by m4xw** [comment]
The elf is for devs, ignore it.

**Comment by Master-RX** [comment]
@m4xw here is the files for your version. same thing. it crash at start a new game
[PPSSPP_GL_Dev.zip](https://github.com/hrydgard/ppsspp/files/4417314/PPSSPP_GL_Dev.zip) 
Sorry for the wait

**Comment by Master-RX** [comment]
Hello, is there a problem if I update the firmware version of the console / KosmosAltlasNX with the tests that are being carried out?

**Comment by unknownbrackets** [comment]
Just for posterity from Discord:

Apparently, QuickTexHashNEON is being called on a nullptr, from ApplyTexture.  There is a `Memory::IsValidAddress(addr + sizeInRAM)` check, but it should more ideally be `isValidSize`.  Maybe if addr and bufw/h are just the right kind of wrong, it's passing that will a null addr?

But that would mean something is breaking down somewhere earlier...

-[Unknown]

**Comment by hrydgard** [comment]
Only way I can see this happening in the code is if the checks in GetPointer and IsValidAddress don't match... since GetPointer is used in QuickTexHash, but only on addresses that have already passed IsValidAddress (due to the checks in the texture cache).

**Comment by unknownbrackets** [comment]
I know we changed some IsValidSize bug a little while back.  Has this improved in the latest Switch update?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
