### ISSUE TITLE
PPSSPP has stopped working

### ISSUE THREAD

**Issue by CookedPages** [hrydgard/ppsspp#12777]
### What happens?
Just as I load ppsspp after about 3 seconds I get the windows 'the program has stopped working'
tried running both 64x and regular version, tried both as administrator. no change.
### What *should* happen?
it shouldn't do that? It should run?

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Desktop PC
Dual intel xeon e5620 2.40ghx quad core 8 strings
Dual Geforce gtx 1050 Ti
windows 10 64x pro
PPSSPP 1.9.3
Note - 1.8.0 runs with no issues, no need for running as administrator either. will use that until 1.9.3 works or we figure the issue out.

**Comment by CookedPages** [comment]
Dang okay i messed up. i extracted the emulator in a folder with 7zip and it didn't give it it's own folder so i moved it into a manually created folder.. and i didn't move the 'assets' folder cause i didn't see it. my bad. However, i will note that it came up with a 'failed to load graphix'? warning, but started okay and runs the game i wanted to play with no issues. and suggested i update my drivers but those are up-to-date. idk what is going on.

**Comment by unknownbrackets** [comment]
It should in future versions (such as the latest git build) no longer crash in this case, although the UI will not look great.

-[Unknown]
