### ISSUE TITLE
Reversed tilt controls in "Landscape reversed" mode

### ISSUE THREAD

**Issue by Leopard20** [hrydgard/ppsspp#12780]
Tilt axes should be reversed automatically when the phone is inverted. Otherwise the tilt controls will be reversed.

Steps to reproduce:
1. Turn on tilt.
2. Turn on Landscape auto
3. Invert the phone
4. Tilt controls are reversed

Tested on Android

**Comment by leopard20** [comment]
@hrydgard @unknownbrackets 
Are you gonna look into this or should I close it?

**Comment by unknownbrackets** [comment]
It sounds likely to be a valid issue, I haven't looked into how the tilt is communicated on different devices.  I guess it needs to be reversed also if configured while landscape reversed?

-[Unknown]

**Comment by leopard20** [comment]
Yeah. You should take the orientation of the device into account before applying the axis parameters (reversed/normal)

**Comment by benderscruffy** [comment]
No feedback/outdated?

**Comment by hrydgard** [comment]
I'm gonna close this, because I don't think we can do much about it. Android has a misfeature that when you have auto landscape, and it auto switches between landscape and reversed, we don't even get an event, it just does it. So the tilt controls are backward after that.

**Comment by unknownbrackets** [comment]
Well, I suppose we could call `Activity.getResources().getConfiguration().orientation` once per frame or something.

-[Unknown]
