### ISSUE TITLE
MGS: Peace Walker Texure Issue

### ISSUE THREAD

**Issue by Cifxr** [hrydgard/ppsspp#12792]
Been having this issue all day, can't seem to find a solution. I've reinstalled everything and the issue persists. In the photo, the textures seem to be 'stretched'. Not sure what the exact term for this is called or how to fix it. 
![ULUS10509_00000](https://user-images.githubusercontent.com/63174129/78464089-2a5a3580-76b3-11ea-8d84-458744dc6e36.jpg)

**Comment by unknownbrackets** [comment]
What device is this on?  Are you using the latest git build?

-[Unknown]

**Comment by Cifxr** [comment]
> What device is this on? Are you using the latest git build?
> 
> -[Unknown]

On PC (Windows), using the latest git build.

**Comment by Cifxr** [comment]
Anything?

**Comment by unknownbrackets** [comment]
What graphics card?  We need as much information as possible.  The directions when you create an issue weren't for show.  Have you tried updating your graphics drivers?  Does it happen on every graphics backend (Vulkan, OpenGL, Direct3D 11)?

Did it work in previous builds?  If yes, what build did it first break in?

I personally don't even have this game.  The more details you give, the more likely I can help.  That said, this isn't an unpopular game, and no one else has reported issues, so I'm trying to understand what makes your experience different.

If you're not sure what graphics card you have, you can click Start, and type "dxdiag" (without the quotes) and press enter.  You may be asked if you want to check WHQL, either answer is fine.  Information about your graphics card will be on the Display tab.

-[Unknown]

**Comment by LunaMoo** [comment]
What mission is it the first one? 
Also this game has a broken fps patches you appear using, I know for sure they break physics and cutscenes, but maybe they also would be breaking other things causing such glitches. You should disable FPS patches or cheats alltogether when reporting issues. Also when you disable such hacks, make sure you restart emulation and resume from normal in-game save. Past savestates will forever be affected by any of their issues.

**Comment by Cifxr** [comment]
> What graphics card? We need as much information as possible. The directions when you create an issue weren't for show. Have you tried updating your graphics drivers? Does it happen on every graphics backend (Vulkan, OpenGL, Direct3D 11)?
> 
> Did it work in previous builds? If yes, what build did it first break in?
> 
> I personally don't even have this game. The more details you give, the more likely I can help. That said, this isn't an unpopular game, and no one else has reported issues, so I'm trying to understand what makes your experience different.
> 
> If you're not sure what graphics card you have, you can click Start, and type "dxdiag" (without the quotes) and press enter. You may be asked if you want to check WHQL, either answer is fine. Information about your graphics card will be on the Display tab.
> 
> -[Unknown]

Running on an Nvidia GT 740 (pretty bad I know). The issue persists with all backends. 

> What mission is it the first one?
> Also this game has a broken fps patches you appear using, I know for sure they break physics and cutscenes, but maybe they also would be breaking other things causing such glitches. You should disable FPS patches or cheats alltogether when reporting issues. Also when you disable such hacks, make sure you restart emulation and resume from normal in-game save. Past savestates will forever be affected by any of their issues.
> 
> Could not find any place withy grass messed up like that, but it could be a duplicate of #12348

This issue persists even with a fresh installation of both PPSSPP and with MGS PW regardless of cheats or not.

**Comment by Cifxr** [comment]
Going to close this issue, seemed to be the newest version of Github that was causing the issues; after reverting back to the official 1.9.3 the issue seemed to go away. Thank you guys regardless!

**Comment by hrydgard** [comment]
Wait - if it's broken in the latest git build, it's very much still an issue, because the git build series will develop into 1.10.0. Did you try the very latest one by the way? Could possibly be related to #12793 .

**Comment by LunaMoo** [comment]
I think maybe he just called it latest because it was a version from buildbot, but the mission that has that spot wasn't even loading for me until the recent fix.

 No graphic issues here:
![ULUS10509_00008](https://user-images.githubusercontent.com/5485237/78511958-f8bf9800-77a0-11ea-9517-3cd3e1c6cd8e.jpg)

**Comment by unknownbrackets** [comment]
Does it work now in the very latest git build?  The goal is to fix bugs in the latest versions - v1.9.3 is months old.

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
