### ISSUE TITLE
Display layout editor bugs in manual scaling

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#12797]
When I select manual scaling in display layout editor and it happens similar to #12781 

Here's a YouTube video:
https://youtu.be/O19BgISVquM

**Comment by Panderner** [comment]
Still not fixed when I keep pressing center button and tap of the screen
https://streamable.com/dkmtes

**Comment by unknownbrackets** [comment]
Okay, maybe there's something else going on specifically when there are insets.

-[Unknown]

**Comment by unknownbrackets** [comment]
Hm, is the PSP display supposed to center when there's only an inset on the left?

-[Unknown]

**Comment by Panderner** [comment]
The PSP display teleports to the right when I touch any screen.

**Comment by unknownbrackets** [comment]
Right, it's not accounting for insets properly.  It's fine on a device without insets.

That said, I think the display doesn't actually position correctly in emulation with insets...

-[Unknown]

**Comment by hrydgard** [comment]
@unknownbrackets  In emulation it should probably center within the deviceContext->LayoutBounds(). This indeed needs a little more work I think.

**Comment by hrydgard** [comment]
There's a lot of screen-relative positioning in DisplayLayoutScreen.cpp that should probably be replaced by a new kind of "DisplayLayoutEditorView" view, so that it and touch events would get the correct coordinate translations automatically.

**Comment by hrydgard** [comment]
Regarding the PSP display in game, in the maximum stretch mode, it's kinda neat that it's ignoring the inset, actually - really feels like it's maximizing the use of the screen. Though of course you lose a few pixels...

**Comment by Panderner** [comment]
Still happens on PPSSPP v1.9.3-736 i'm using Realme C2 Android 9 Pie
