### ISSUE TITLE
Crash in PSP's OSK (virtual keyboard) [Android]

### ISSUE THREAD

**Issue by Saramagrean** [hrydgard/ppsspp#12805]
### What happens?
Crash in PSP's OSK, if switch to other app and comeback to PPSSPP, after that press any button, PPSSPP is force close.

Last work : PPSSPP v1.9.3-470-g4219ce01d
First break : PPSSPP v1.9.3-481-gd0e2aa3a4

![92824127_2580044822211543_440843109778063360_n](https://user-images.githubusercontent.com/26355472/78754440-aef1d000-79a1-11ea-87b8-7c596c71954e.png)

### What *should* happen?
Not crash. :)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
- Huawei P9+ (Android 9, Kirin 955, Mali T-880)
- test with PPSSPP v1.9.3-635-ge30ae867c.

Logcat. [...here...](https://drive.google.com/open?id=1sDdjLzpZccI9leZKI-7TT5dKcAVZ6KbB)
Example video. https://youtu.be/vufoPzb9GuY

**Comment by unknownbrackets** [comment]
I got this to crash one time and env_ was somehow nullptr.  Now I'm having trouble reproducing.

I did notice `thrd_current()` changes each time I app switch.  Do we need to reattach thread each time?  But then why doesn't TextDrawerAndroid normally crash in the UI for this same reason?

I can't see anything that would cause env_ to become nullptr after working to draw PPGe before switch either...

-[Unknown]

**Comment by Panderner** [comment]
I've tested Realme C2 it doesn't crash on OSK When I switch to other app and comeback PPSSPP, and press any button. But PSP's OSK Crashed on @Saramagrean's Huawei P9+

**Comment by nassau-tk** [comment]
@Saramagrean 
Is an update of Android 9 a formal update in Huawei?
It wasn't reproduced by my device.(Official Update by SONY)
May it be anything related?
Default keyboard & Android system keyboard both.

PPSSPP Ver. : 1.9.3-642
OS: Android 9.0 (Official Update by SONY)
DeviceName: SONY SO-02K / Xperia XZ1 Compact (Japan)
CPU: Snapdragon835 (Octa-core)
GPU: Adreno 540
Resolution: 720×1280
RAM: 4GB
ROM:32GB
ExternalStrage: microSDXC 512GB

**Comment by Saramagrean** [comment]
I use custom rom. 🤣

**Comment by nassau-tk** [comment]
@Saramagrean 

But @unknownbrackets  saying that the problem could be reproduced once.
We'll hope!

**Comment by iota97** [comment]
I could reproduce easily on a RedMi 4X

Calling getEnv at the start of every other method using env_ of TextDrawerAndroid class as this:
`env_ = getEnv();` fixed it.

Maybe this quote from [here](https://stuff.mit.edu/afs/sipb/project/android/docs/training/articles/perf-jni.html) is relevant?

> The JNIEnv is used for thread-local storage. For this reason, you cannot share a JNIEnv between threads. If a piece of code has no other way to get its JNIEnv, you should share the JavaVM, and use GetEnv to discover the thread's JNIEnv. (Assuming it has one; see AttachCurrentThread below.)

**Comment by unknownbrackets** [comment]
I was thinking about this, maybe we restart the thread (from Java) in certain backends?  I think we do.  Maybe we just need a way to detect this (hooking the lost manager or something.)

Not sure if it'd be expensive to just call getEnv() each time.

-[Unknown]

**Comment by hrydgard** [comment]
I think getEnv is supposed to be fairly quick, should be fine, if that's the issue.
