### ISSUE TITLE
Fat Princess Fistful of Cake Lag issue (Can't reach 60 fps)

### ISSUE THREAD

**Issue by HiImBrala** [hrydgard/ppsspp#12809]
### What happens?
Fat Princess Fistful of Cake on 1x rendering resolution,can't reach 60 fps without frameskip

### What *should* happen?
Game should function normally

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Windows 8.1
CPU:Intel Quad-Core processor N3520
GPU:Intel (HD) Graphics
Direct3D 11 and 9 --> same result
Latest PPSSPP build from buildbot.orphis.net
[recording (1).zip](https://github.com/hrydgard/ppsspp/files/4464191/recording.1.zip)
![UCUS98740_00001](https://user-images.githubusercontent.com/54099546/79038076-d2519080-7bd6-11ea-8e4c-d24e797fecfe.jpg)

**Comment by Panderner** [comment]
You need to underclock the emulated PSP CPU speed to run smoothly.

Some games requires to underclock the CPU to run the game smoothly even the game's capped at 30 or 60 FPS:
Asphalt Urban GT 2
Sengoku Cannon
Car Jack Streets
Super Monkey Ball Adventure
Fat Princess
Platypus

**Comment by HiImBrala** [comment]
> You need to underclock the emulated PSP CPU speed to run smoothly.
> 
> Some games requires to underclock the CPU to run the game smoothly even the game's capped at 30 or 60 FPS:
> Asphalt Urban GT 2
> Sengoku Cannon
> Car Jack Streets
> Super Monkey Ball Adventure
> Fat Princess
> Platypus

I know about setting to 333Mhz and stuff,but how do i underclock

**Comment by Panderner** [comment]
![IMG_20200411_174832](https://user-images.githubusercontent.com/37503397/79040670-b2dd5680-7c1c-11ea-8e6d-9c1c13306514.jpg)
Look the Change emulated PSP's CPU clock (unstable) inside the System

**Comment by LunaMoo** [comment]
No, games don't need underclock, in fact doing PSP CPU underclock will BREAK most of them althrough this might not be noticable until reaching certain points in those games.
 Also this is not an emulation issue, most 60 fps games require a bit stronger hardware to run and the hardware you're trying to run it on is really just some old netbook which is slower than modern phones.

 It's not really an emulation issue. PPSSPP includes frameskipping(safe way) and various performance options and hacks that can completely break games, but are kept exactly due to bottom end hardware users. This is an issue tracker not a support forum to deal with every game for every person with bottom end hardware. As such closing.

**Comment by Panderner** [comment]
> No, games don't need underclock, in fact doing PSP CPU underclock will BREAK most of them althrough this might not be noticable until reaching certain points in those games.
> Also this is not an emulation issue, most 60 fps games require a bit stronger hardware to run and the hardware you're trying to run it on is really just some old netbook which is slower than modern phones.
> 
> For solutions - PPSSPP includes frameskipping(safe way) and various performance options and hacks that can completely break games, but are kept exactly due to bottom end hardware users. This is an issue tracker not a support forum to deal with every game for every person with bottom end hardware. As such closing.

Platypus needs to underclock the CPU to make the game load faster. Mumbo Jumbo logo and loading screen is way slower until the title screen but when I underclock the PSP CPU the game loads faster.

Auto:
![Screenshot_2020-04-11-21-01-35-14_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/79044433-b6320b80-7c37-11ea-94cc-581f1d2c3919.png)
50 MHz:
![Screenshot_2020-04-11-21-01-21-27_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/79044452-c944db80-7c37-11ea-96b9-73d83ae2f4cb.png)
