### ISSUE TITLE
[Vulkan]Sega Rally Revo Black Sky at Buffered Rendering

### ISSUE THREAD

**Issue by HiImBrala** [hrydgard/ppsspp#12819]
I'm making issue on GitHub for friend and member of my Ad-Hoc server,he doesn't know how to make issue so i'm reporting his issue here,if you don't mind

### What happens?
Sky is black,other textures appear fine,tested on Vulkan,OpenGL has no issues

### What *should* happen?
Sky should render correctly,like in OpenGL

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

OS:Linux
PPSSPP latest commit,compiled one,SDL version
PC specifications:1060 6GB GTX 440.82
Game:Sega Rally Revo (USA)
Buffered Rendering:
![image](https://user-images.githubusercontent.com/54099546/79101841-c2b68100-7d69-11ea-8b33-872ee24d6f4c.png)
Non-Buffered rendering:
![image](https://user-images.githubusercontent.com/54099546/79101899-e2e64000-7d69-11ea-818e-bcfda1796c69.png)

**Comment by nassau-tk** [comment]
It's happen on the Android Vulkan too.
v1.9.3-656

**Comment by Panderner** [comment]
Have you tried GE Dump?

**Comment by nassau-tk** [comment]
@Panderner 
I got the dump file.
Please check it!!

[ULJM05302_0001.zip](https://github.com/hrydgard/ppsspp/files/4473535/ULJM05302_0001.zip)

**Comment by hrydgard** [comment]
This has something to do with the alpha channel of the second render target of each frame. In OpenGL, alpha is 0.0, making a draw call that kind of destroys the sky not do anything, while in Vulkan, the alpha is 1.0. All draws to this target seem to be masked to not touch the alpha channel, so what's in there seems to stick around. 

I'm wondering if we somehow accidentally initialize new render targets with alpha 1.0 in Vulkan, though I can't really see how that would be possible...

**Comment by unknownbrackets** [comment]
On framebuf create, we upload to the framebuf (unless bDisableSlowFramebufEffects.)  This should be setting alpha the same way on all backends.

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, you'd think so. So it must be the game wiping the buffer in a way that ends up different in the two APIs, which is also weird..

**Comment by hrydgard** [comment]
What's kind of odd is that when drawing to the framebuffer that gets the wrong alpha, it's initially in 565 mode (no alpha) when it draws some not really visible stuff, then switches to 4444..

**Comment by unknownbrackets** [comment]
Oh, I wonder if the way we upload affects 565 differently?  Maybe we set alpha on some backends...

-[Unknown]

**Comment by hrydgard** [comment]
Simply replacing the last few lines of FramebufferManagerCommon::DrawPixels with the following fixes it:

```
	if (srcPixelFormat != GE_FORMAT_565) {
		Bind2DShader();
		DrawActiveTexture(dstX, dstY, width, height, vfb->bufferWidth, vfb->bufferHeight, u0, v0, u1, v1, ROTATION_LOCKED_HORIZONTAL, flags);
		gpuStats.numUploads++;
	}
```

The problem is that I can't see how it's any different on the other backends... They also seem to draw alpha 1.0.

**Comment by hrydgard** [comment]
Hmm... This might actually have something to do with our hacked-up implementation of ReformatFramebufferFrom in Vulkan, which is even less correct than the D3D11 one. But seems like that one should manage to clear to zero anyway... Still, I'll look into it.

**Comment by hrydgard** [comment]
Ah. ReformatFramebufferFrom clears the screen by beginning a new pass to the same framebuffer. Unfortunately ApplyRenderPassMerge gets a little merge-happy and apparently doesn't do a necessary check, ending up killing that clear. And there we have it - the bug is both in ApplyRenderPassMerge and in ReformatFramebufferFrom which really should simply draw a rectangle killing just the alpha channel instead.

I think I'll try to fix ApplyRenderPassMerge first.
