### ISSUE TITLE
Notches blocks some letters in Debug statics

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#12810]
It doesn't seems to right some letters in Debug statics blocked by a notch.
![Screenshot_2020-04-11-21-30-48-22_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/79045120-0ca14900-7c3c-11ea-89e5-0a235640182f.png)

**Comment by hrydgard** [comment]
Yeah, good find.
