### ISSUE TITLE
[GE Emulation] [Android/OpenGL] Harvest Moon Boy and Girl Poor Performance On Snapdragon 430 CPU Adreno 505 GPU

### ISSUE THREAD

**Issue by Emulatorer** [hrydgard/ppsspp#12824]
This game is smooth on my Mali-450 GPU phone default settings but lag on Adreno 505 GPU phone of my friend.
Screenshot from his phone:
![Screenshot_20200414-200303](https://user-images.githubusercontent.com/37603562/79223168-68addc80-7e8b-11ea-84fd-4edeb745631a.png)

GE Dump from his phone
[Harvest Moon Boy & Girl ULUS10142.zip](https://github.com/hrydgard/ppsspp/files/4475125/Harvest.Moon.Boy.Girl.ULUS10142.zip)

I already tried ppsspp v1.9.4 playstore also tried ppsspp latest git build but still lag.

**Comment by Panderner** [comment]
@Emulatorer what adreno 505 device are you using?

**Comment by hrydgard** [comment]
505 might simply be a very slow GPU? It's not clear there's anything we can do here. Does Vulkan make a difference, if you can run that on 505?

**Comment by Emulatorer** [comment]
@hrydgard no adreno 505 GPU is powerful compare to mali 450 GPU.

Here's the full specs of the phone:

### Specs Of Cloudfone Next Lite
SCREEN • 5.0-inch FHD IPS LCD Display (1080 x 1920 Pixels, 441 ppi) with 2.5D Arc Glass
OS • Android 6.0 Marshmallow
CHIPSET • Qualcomm Snapdragon 430
CPU • 1.4GHz Octa Core Cortex-A53
GPU • Adreno 505
RAM • 3 GB

**Comment by Emulatorer** [comment]
@Panderner Snapdragon 430 Adreno 505 is 64bit while MediaTek mt6592 Mali 450 is only 32bit.

**Comment by leopard20** [comment]
What about your GPU settings? Rendering resolution can significantly affect performance.

**Comment by Panderner** [comment]
@Emulatorer what Mali-450 devices are you using?

**Comment by Emulatorer** [comment]
@leopard20 His using default settings of ppsspp

Differences of Snapdragon 430 vs MediaTek MT6592
https://versus.com/en/mediatek-mt6592-vs-qualcomm-snapdragon-430

**Comment by unknownbrackets** [comment]
It could be down to the 1.7 Ghz of the other device?  Even if it's graphics limited, the GPU driver could be performing better with the 1.7 Ghz even on a weaker GPU.

-[Unknown]

**Comment by Emulatorer** [comment]
@unknownbrackets  no my phone mt6592 is only 1.36GHz while snapdragon 430 is 1.4GHz

Tekken6, Untold Stories, Crash Mind Over Mutant, Power Stone Collection and  Brave Stories are running full speed frameskiping off on Snapdragon 430 while in my MT6592 I need to use frameskiping x1 and reduce the rendering resolution.

**Comment by Emulatorer** [comment]
@unknownbrackets didn't find in my GE Dump why this game is lag on Snapdragon 430?

**Comment by unknownbrackets** [comment]
It renders at 320x240, then does a reverse-subtract blend from a solid color, then stretches that to the screen.  It doesn't draw all the efficiently (it starts with far away things), but it's not that many draw calls.

Not really seeing anything that should majorly impact performance.

Brave Story may leverage Mali features to blend more efficiently in some places.  Not sure of anything else for the others.

-[Unknown]

**Comment by Panderner** [comment]
> It renders at 320x240, then does a reverse-subtract blend from a solid color, then stretches that to the screen. It doesn't draw all the efficiently (it starts with far away things), but it's not that many draw calls.
> 
> Not really seeing anything that should majorly impact performance.
> 
> Brave Story may leverage Mali features to blend more efficiently in some places. Not sure of anything else for the others.
> 
> -[Unknown]

Um yes Harvest Moon: Boy & Girl is a port of a PS1 game Harvest Moon: Back to Nature but added female protagonist, The original game renders 320x240.

**Comment by Emulatorer** [comment]
@unknownbrackets I also tested this game on my tablet with Mali-T720 GPU 1.3GHz CPU clockspeed in it's running at FULL SPEED...

**Comment by Emulatorer** [comment]
Sad I don't have a phone with Snapdragon cpu to test if this game is lag :(

**Comment by Emulatorer** [comment]
@unknownbrackets I found out that the lag only happen when characters are moving but during dialogue this game is smooth there's must be something wrong 🤔

Screen Recording
https://drive.google.com/file/d/1-2m4GlL8-XgwY5zusg1NbGFhZJ0Icsik/view?usp=drivesdk

GE Dump from ppsspp latest git
[ULUS10142.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/4479676/ULUS10142.ppdmp.zip)

**Comment by LunaMoo** [comment]
There's nothing wrong, this game modifies textures when character is walking, it also loads new stuff when you walk around, movement will always be heavier than standing still doing nothing.

**Comment by Emulatorer** [comment]
@LunaMoo then why this lag doesn't happen on my ancient phone with Mali450 gpu?

**Comment by LunaMoo** [comment]
Maybe the other person is using texture scaling. This would kill performance on most or all phones, even vulkan's hardware texture scaling since this game as I said modifies textures when you're walking and they have to be processed again.

**Comment by Emulatorer** [comment]
It's kinda werid that Snapdragon 430 out performance by an old mali 450 gpu
🤣

**Comment by hrydgard** [comment]
Performance on Android is sometimes very unpredictable due to the many combinations of hardware, OS and driver and thermal management, and it's not uncommon that older devices outperform newer ones. And given that indeed 505 seems like a very weak Adreno, I don't think there's much to do here. Switch rendering to 1x resolution, might be enough to get it to better speeds.

**Comment by Emulatorer** [comment]
It is sad that this issue is close and not added to future milestone 😢
@hrydgard I already did that changing rendering resolution to x1 doesn't help  enabling speedup option doesn't also help.

Snapdragon 430 Adreno 505 can run the games
that I mention here https://github.com/hrydgard/ppsspp/issues/12824#issuecomment-613824225 at full speed so why this game is only lag 🤷
but running smooth on the weak old mt6592 mali450 GPU 😞

**Comment by hrydgard** [comment]
Because I don't know of any way we could fix it.

**Comment by Emulatorer** [comment]
Just putting here 
[recording.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/4480595/recording.ppdmp.zip) The GE Dump from my phone (MALI-450)
hoping someday, someone can fixed this issue :)

**Comment by leopard20** [comment]
If you're sure that your friend's phone is more powerful and it's underperforming, then it's probably related to some software issue (bad governor settings, bad drivers, etc.) I think the game (and accordingly the emulator) is doing something that the Adreno 505 driver can't handle efficiently.

**Comment by Emulatorer** [comment]
@leopard20 maybe your right..

**Comment by Gamemulatorer** [comment]
Just to note this game was smooth now using my vivo y51a snapdragon 410 adreno 306 maybe improve because of the code refactoring recently :)
