### ISSUE TITLE
cannot use libretro core without manually downloading assets

### ISSUE THREAD

**Issue by soredake** [hrydgard/ppsspp#12820]
see https://github.com/libretro/docs/blob/master/docs/library/ppsspp.md#bios

### What happens?
Assets not copied automatically.

### What *should* happen?
Assets should be downloaded with core.

**Comment by hrydgard** [comment]
No idea how to solve this other than baking the assets into the binary. Not sure what other libretro cores do?

**Comment by soredake** [comment]
https://github.com/libretro/dolphin/issues/143

**Comment by unknownbrackets** [comment]
I feel like this is a widespread issue of libretro, and less an issue of PPSSPP itself?

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, I don't know that there's anything sensible we can do about this.

**Comment by soredake** [comment]
https://github.com/libretro/retroarch-assets/issues/356

**Comment by matheuswillder** [comment]
@hrydgard When the LibRetro team started porting PCSX2, [they said this](https://www.libretro.com/index.php/pcsx2-libretroretroarch-core-progress-report-august-2021/):

> Reducing file requirements
> 
> As a general baseline, Libretro strives to make sure that the cores we self-maintain are fairly portable. We’d like not to have the user to require to install several data files inside the System folder in order for an emulator core to work. The problem with the PCSX2 core up to this point was that it was too much of a straight port – PCSX2 by itself writes to dozens of files during startup and logging. However, it also has many config files scattered about the place.
> 
> We have cut all this config file reading/writing. Now, the only configuration file that gets written to is the ever-trusty ‘core options config file’ from Libretro/RetroArch.
> 
> Furthermore, the only files you need to have in your /pcsx2 folder are your BIOS files inside /pcsx2/bios. Anything else is not necessary.

So, I believe that all their assets (e.g. cheats, databases) end up inside the core itself, or did i get it wrong? I'm not a developer nor do I know if it's possible to do the same with PPSSPP, but browsing through this issue I decided to leave this my 2 cents contribution.
