### ISSUE TITLE
[Network/Adhock] [Android/OpenGL] Metal Slug XX ULUS10495 Stuck On Boot When Connected To Internet

### ISSUE THREAD

**Issue by Emulatorer** [hrydgard/ppsspp#12822]
This game stuck during boot
![Screenshot_20200413-233256](https://user-images.githubusercontent.com/37603562/79134213-eae0c700-7ddf-11ea-8312-6a0ad0dd3b59.png)
I can't get GE Dump ppsspp isn't responding
![Screenshot_20200413-233448](https://user-images.githubusercontent.com/37603562/79134279-03e97800-7de0-11ea-9eb3-2820d325020a.png)
I try catlog app to capture log
[ppsspp-logs.txt](https://github.com/hrydgard/ppsspp/files/4470250/ppsspp-logs.txt)

### Phone Specs
Android 6.0.1
Mali-450 GPU
Octacore CPU
PPSSPP v1.9.3-658

**Comment by Emulatorer** [comment]
My ScreenRecording
[Mobizen_Metal_Slug_XX.mp4.zip](https://github.com/hrydgard/ppsspp/files/4470397/Mobizen_Metal_Slug_XX.mp4.zip)
When data connection is on this game is stuck on boot but turning off the data connection the game boot properly.

**Comment by Emulatorer** [comment]
Finally found out what the cause of this issue is the Pro adhoc Server IP Address that I change to
192.168.43.1 because I play wilan multiplayer adhoc with my niece, but this is only happen in this game other games with the same IP address of 192.168.43.1 are ok.

also this game always show this message during boot.
![Screenshot_20200414-153530](https://user-images.githubusercontent.com/37603562/79198919-c845c100-7e66-11ea-8ad6-32a624aba382.png)

sorry for my bad english... 😅

**Comment by Emulatorer** [comment]
Resetting to defaul settings fixes this issue using ppsspp v1.9.3-698 git :)
![Screenshot_20200422-085010](https://user-images.githubusercontent.com/37603562/79928822-9b049e80-8476-11ea-880b-34858373cc6f.png)
![Screenshot_20200422-084954](https://user-images.githubusercontent.com/37603562/79928830-9f30bc00-8476-11ea-9960-2311453d93c0.png)
No more DNS error warning..

**Comment by unknownbrackets** [comment]
Hm, if it crashes when the IP is set wrong or something, that seems like a bug still, no?

-[Unknown]

**Comment by Emulatorer** [comment]
> Hm, if it crashes when the IP is set wrong or something, that seems like a bug still, no?
> 
> -[Unknown]

Still stuck on blackscreen when I change the IP address to 192.168.43.1 then connected to internet :(
![Screenshot_20200422-095214](https://user-images.githubusercontent.com/37603562/79932051-22eea680-847f-11ea-8aeb-f831b7e0fa50.png)

**Comment by adenovan** [comment]
most likely it crash because of proadhocserver is not booted before starting the game , the host should start the game earlier than other peer , i can play this game normally in local network #10078
