### ISSUE TITLE
Remove Disable Slower Effects In Graphics Settings Not Helping Anymore Tried and Tested Using Latest Build

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#12827]
Related to #8171 kindly update that issue? 😅

**Comment by LunaMoo** [comment]
Disable slower effects is not an universal speedhack, it works only on some games that use very specific heavy effects. It should always work although some of it's cases might be optimized on Vulkan backend. While it would be nice to remove it, due to low end potatoes PPSSPP runs on, it has to stay as it's still way safer than some other options people abuse for low end devices.

**Comment by Emulatorer** [comment]
@LunaMoo in the previous version of ppsspp disable slower effects speedup the games like, Brave Stories, 3RD Birthday, Ghost Rider and Hellboy The Science.
But now enabling that option has nothing changed sometimes give graphics glitches so better to remove that option.

**Comment by unknownbrackets** [comment]
This is really a duplicate of #11610 which is possibly even a duplicate of #8171.

#11777 is when we altered the setting to disable slightly less effects.

-[Unknown]

**Comment by Panderner** [comment]
Do not turn on disable slow effects for some games: 
The Simpsons Game Will corrupt the graphics
Sonic games will result brighter bloom

**Comment by Panderner** [comment]
Some games like Call of Duty, Indiana Jones needs to turn on disable slow effects to fix graphical problem for Mali GPUs see: #11598 and #11573

**Comment by Emulatorer** [comment]
> Some games like Call of Duty, Indiana Jones needs to turn on disable slow effects to fix graphical problem for Mali GPUs see: #11598 and #11573

Disable Slower Effects is not the proper fixed for those games

**Comment by Panderner** [comment]
This is why The Simpsons Game needs to turn off Disable slower effects.

Disable slower effects off:
![Screenshot_2020-04-16-15-46-01-76_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/79429125-b3e5fd80-7ff9-11ea-9dc8-794a3d93dd8a.png)
Disable slower effects on:
![Screenshot_2020-04-16-15-46-09-96_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/79429151-bcd6cf00-7ff9-11ea-9782-2222edddd171.png)

**Comment by Emulatorer** [comment]
> This is why The Simpsons Game needs to turn off Disable slower effects.
> 
> Disable slower effects off:
> ![Screenshot_2020-04-16-15-46-01-76_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/79429125-b3e5fd80-7ff9-11ea-9dc8-794a3d93dd8a.png)
> Disable slower effects on:
> ![Screenshot_2020-04-16-15-46-09-96_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/79429151-bcd6cf00-7ff9-11ea-9782-2222edddd171.png)

That's why disable slower effects is needed to remove 🤷

**Comment by Emulatorer** [comment]
PPSSPP v1.7.5 is the last version that "Disable Slower Effects" can give speedup for some games when option is enable.

**Comment by LunaMoo** [comment]
No. You're simply running Vulkan backend AND trying on effect which is optimized there. Still 20% is a lot for some devices basically a difference between playable and not.

 But then when you switch to OGL which most people will use on their old potatoes you will see a difference between a single digit fps and fully playable game which in some cases like Death Jr. 2 game will not even cause any missing graphics. I don't have any benefit from that setting running on PC way more powerful than any phone will have for the next 10 years or more, but this setting for many poor people is a a difference between experience of playing a game and walking into dog s....

**Comment by Emulatorer** [comment]
> No. You're simply running Vulkan backend AND trying on effect which is optimized there. Still 20% is a lot for some devices basically a difference between playable and not.
> 
> But then when you switch to OGL which most people will use on their old potatoes you will see a difference between a single digit fps and fully playable game which in some cases like Death Jr. 2 game will not even cause any missing graphics. I don't have any benefit from that setting running on PC way more powerful than any phone will have for the next 10 years or more, but this setting for many poor people is a a difference between experience of playing a game and walking into dog s....

I tested Death JR 2 in Mali-T270 GPU OGL 3.1 and Adreno 505 GPU OGL 3.1 disable slower effects has no effects in the latest git build of ppsspp.

**Comment by LunaMoo** [comment]
Then maybe your devices can't emulate that effect to begin with. The difference on a PC which CAN emulate the effect used in that game, running on 32x PSP res for the sake of seeing a difference is between 2 and 30 fps, in OGL at least, in Vulkan it's also around 20% max which would still be a lot on a crappy device.

**Comment by Drasikk** [comment]
Here are some so-called "collaborators" with the dirtiest mouth.

**Comment by Panderner** [comment]
Um @hrydgard Did you remove @Drasikk's comment above?

**Comment by Drasikk** [comment]
@Panderner Yes, see that they want the best who speaks badly. It leaves a lot to be desired, this kind of behaviors of young children.

**Comment by Emulatorer** [comment]
> Lamentable, prefieren a una persona (por llamarlo de alguna forma) que hable mal. Y no es la primera vez que ese individuo suelta alguna perla.

Can't understand your language 😅

**Comment by hrydgard** [comment]
This type of stuff is not relevant here, I have no idea what you are arguing about .

**Comment by Panderner** [comment]
> Lamentable, prefieren a una persona (por llamarlo de alguna forma) que hable mal. Y no es la primera vez que ese individuo suelta alguna perla.

@Drasikk speak English not Spanish. It translates to:
Unfortunately, they prefer a person (to call it something) who speaks badly. And it is not the first time that this individual drops a pearl.

**Comment by hrydgard** [comment]
I really don't understand what he's talking about, in either language.

**Comment by Drasikk** [comment]
> > Lamentable, prefieren a una persona (por llamarlo de alguna forma) que hable mal. Y no es la primera vez que ese individuo suelta alguna perla.
> 
> Can't understand your language

Yo tampoco puedo entender tu lenguaje. 🤔

**Comment by Drasikk** [comment]
> > Lamentable, prefieren a una persona (por llamarlo de alguna forma) que hable mal. Y no es la primera vez que ese individuo suelta alguna perla.
> 
> @Drasikk speak English not Spanish. It translates to:
> Unfortunately, they prefer a person (to call it something) who speaks badly. And it is not the first time that this individual drops a pearl.

No se donde pone que no se pueda hablar en español, siendo una de los idiomas más importantes y hablados del planeta.

**Comment by Emulatorer** [comment]
> > > Lamentable, prefieren a una persona (por llamarlo de alguna forma) que hable mal. Y no es la primera vez que ese individuo suelta alguna perla.
> > 
> > 
> > @Drasikk speak English not Spanish. It translates to:
> > Unfortunately, they prefer a person (to call it something) who speaks badly. And it is not the first time that this individual drops a pearl.
> 
> No se donde pone que no se pueda hablar en español, siendo una de los idiomas más importantes y hablados del planeta.

Speak English so everyone can understand you 🤦

**Comment by Drasikk** [comment]
> I really don't understand what or who he's talking about, in either language.

Yo tampoco lo entiendo, tener a un colaborador diciendo esas barbaridades.

**Comment by unknownbrackets** [comment]
Entiendo que no te gustan los problemas de velocidad. No hablar un idioma común no ayuda. Algunas personas están estresadas en este momento. Trabajemos juntos para mejorar PPSSPP.

I understand you don't like the speed problems.  Not speaking a common language doesn't help.  Some people are stressed right now.  Let's work together to make PPSSPP better.

-[Unknown]

**Comment by Emulatorer** [comment]
disable slower effects has nothing to do in the brightness error of this #12044

**Comment by Gamemulatorer** [comment]
Closing this...

**Comment by Gamemulatorer** [comment]
This was fix by https://github.com/hrydgard/ppsspp/pull/15948
