### ISSUE TITLE
Jeanne D'Arc - Invisible Dialogue Box and Models (GLES2)

### ISSUE THREAD

**Issue by DarkTony93** [hrydgard/ppsspp#1283]
This game has some problems. While the in-game graphics were fixed in the latest builds, it is still impossible to play this game due to invisible dialogue boxes, characters' models, images and menus. 
However you guys are amazing. Keep up the good work!!!

Device: iPhone 4S
PPSSPP Build: 7.5-3

Here there are two images that show the issues reported above. :)
In the first one there should be the Jeanne D'Arc logo and the opening menu (New Game, Continue, etc...). The latter is self explaining. :D

![image](https://f.cloud.github.com/assets/4153658/378274/16985f2e-a52b-11e2-82ee-b19ba29747f1.jpg)
![image](https://f.cloud.github.com/assets/4153658/378273/1697802c-a52b-11e2-8ba3-3930d2a1b780.jpg)

**Comment by ppmeis** [comment]
Tested with latest build. LGTM:
![image](https://cloud.githubusercontent.com/assets/4381277/7019660/aecf9a0c-dd12-11e4-8af0-1769d27f3c24.png)

**Comment by sum2012** [comment]
I remember some people who reported in chinese ppsspp forum that still see invisible because their phone does not support opengl es 3.0

**Comment by hrydgard** [comment]
Yup, that's still the case unfortunately. It does work on ES 3.0+.

**Comment by Neikiddo** [comment]
Just recently redownloaded ppsspp 1.0.1. Loaded up Jeanne D' Arc just fine, before it was the issue with the sprites not showing up in battle (game play moving on their own, they would). Everything is runnign fine now, its great. But after the first battle, after the animated scene with the little prince and it goes back to showing Jeanne with a black background. It crashes right there. 

Running:
Dell XPS 15
Windows 10 64 bit
8gb Ram
Intel Core i5 2.50 ghz

I didn't mess with any settings when i downloaded ppsspp, so it all should be defaulted already.
![ddwqqdw](https://cloud.githubusercontent.com/assets/14130966/9692424/fefd6cf0-5316-11e5-9ced-091f0004d7d6.jpg)

**Comment by ofry** [comment]
Neikiddo, try the latest dev version from http://buildbot.orphis.net/ppsspp/index.php?m=fulllist
Latest version is v1.0.1-865-g825662d now

**Comment by unknownbrackets** [comment]
On Windows 10, make sure to update your video card drivers.  There have been bugs and issues in them.  Windows 10 was just released, and like with all new things, there have been bugs.

-[Unknown]

**Comment by Neikiddo** [comment]
I just did both of your guys suggestions (new dev came out today actually), still gettin that same crash.

**Comment by Plusman28** [comment]
Hey! 

I am using a GPD XD, which actually offers GLES 3.0. But there is still that problem with the partielly visible characters. Tested latest official and latest build. Why is that?

**Comment by hrydgard** [comment]
@Plusman28  is this still a problem on GPD XD?

**Comment by Emulatorer** [comment]
The issue still happen :'(

**Comment by hrydgard** [comment]
So does it look like any of the above screenshots, or can you provide a new one?

**Comment by unknownbrackets** [comment]
Well, it requires depth copying which isn't supported on GLES2.  So for a Mali-450, unfortunately it's expected that it would still happen.

It should work properly on GLES3 devices.

-[Unknown]

**Comment by Emulatorer** [comment]
@unknownbrackets sad to hear that :'(

**Comment by hrydgard** [comment]
Oh right. I think we can close this, anyway.

**Comment by Emulatorer** [comment]
GPU: Fix curve breakage due to cull flipping #11674 fixed this even in OGL 2.0?

**Comment by hrydgard** [comment]
No, at least it shouldn't have.

**Comment by Emulatorer** [comment]
:'(
