### ISSUE TITLE
Ppsspp boot up gives blue or black screen 

### ISSUE THREAD

**Issue by dmajor77** [hrydgard/ppsspp#12832]
### What happens?
Ppsspp won’t start once you press the app it launches to a blue screen and on other versions a black screen. This is the first thing you see, blank screen. No display no settings nothing. 

### What *should* happen?
It should boot up and greet you with ppsspp 2.0gl then to the games and apps settings etc

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

iPhone 7 Plus jailbroken iOS 13.2.3 ppsspp-dev working, dev latest as well as v1.9.3 and v1.9.3 x64 bit

**Comment by unknownbrackets** [comment]
Does it work if you restart your phone?  This may be #9186.

-[Unknown]

**Comment by dmajor77** [comment]
Yes it worked I restarted my jailbreak and downloaded the ppsspp from another ipa. Al though 1.9.3 x64 on the Cydia app isn’t working for iOS. But thanks I’m back up running again

**Comment by unknownbrackets** [comment]
Closing as a duplicate of #9186.

-[Unknown]
