### ISSUE TITLE
Weird graphical issue on NVIDIA Shield

### ISSUE THREAD

**Issue by kiki748** [hrydgard/ppsspp#12838]
### What happens?
Every game working fine but with weird graphic issue following the center of the screen and only behind 2D items (healthbar or names). 
Happens for every games

![Ppsspp](https://user-images.githubusercontent.com/63964339/79690702-10485780-825c-11ea-8b5a-bd2a0c811906.jpg)

### What *should* happen?
These distortion issue shouldn't appear

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
I'm using android version of ppsspp gold from playstore (last version)
On Nvidia shield
ARMv7 Processor rev2 (v7I)
Cores 4
3D API : OpenGL ES
Driver version : Nvidia Tegra
Core context : inactive 
Memory page size : 4096 bytes 
Rw/rx exclusive : inactice
Sustained perf mode : unsupported
ppsspp build : release
Native resolution : 1280 x 720
Api version : v2.0.0 ES
Shading Langyage : OpenGL ES GLSL 1.00
Moga : none detected

**Comment by Panderner** [comment]
Is that ultimate ninja heroes?

**Comment by hrydgard** [comment]
Oh, this is the old portable Shield? I guess I'll have to go dig it out...

**Comment by kiki748** [comment]
> Is that ultimate ninja heroes?

Yes, everygames are working perfectly but big problem is I can't see anything because pf the graphical issue
1 year ago everything worked perfectly tho, in dedault mode

**Comment by kiki748** [comment]
> Oh, this is the old portable Shield? I guess I'll have to go dig it out...

Exactly ! Ecery psp games are working perfectly but big problem is I can't see anything because pf the graphical issue...
1 year ago everything worked perfectly tho, in default mode, i don t know why

**Comment by Panderner** [comment]
Ultimate ninja heroes 1,2 or 3?

**Comment by unknownbrackets** [comment]
We may have to disable or alter range culling on these devices...

-[Unknown]

**Comment by kiki748** [comment]
> Ultimate ninja heroes 1,2 or 3?

It is 2

**Comment by hrydgard** [comment]
Yeah, I thought we already did though, but it's definitely the most likely culprit.

**Comment by kiki748** [comment]
If tried something, maybe it might help you but using the ppsspp 1.8.0 apk version fixed the issue !

**Comment by hrydgard** [comment]
Yeah, I know what it is - fix coming up.

**Comment by hrydgard** [comment]
Confirmed fixed with that commit, closing.
