### ISSUE TITLE
PPSSPP iOS build problems

### ISSUE THREAD

**Issue by kezzico** [hrydgard/ppsspp#12842]
### What happens?

Downloaded the latest code from this repository. I installed cmake using brew.

I'm seeing this ouput:

```
-- Toolchain using default iOS SDK: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk
CMake Error at /usr/local/Cellar/cmake/3.17.1/share/cmake/Modules/Platform/Darwin-Initialize.cmake:160 (string):
  string sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.17.1/share/cmake/Modules/Platform/Darwin-Initialize.cmake:213 (_apple_resolve_multi_arch_sysroots)
  /usr/local/Cellar/cmake/3.17.1/share/cmake/Modules/CMakeSystemSpecificInitialize.cmake:21 (include)
  CMakeLists.txt:3 (project)


-- The C compiler identification is AppleClang 11.0.0.11000033
-- The CXX compiler identification is AppleClang 11.0.0.11000033
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CMake Error at /usr/local/Cellar/cmake/3.17.1/share/cmake/Modules/Platform/Darwin-Initialize.cmake:160 (string):
  string sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.17.1/share/cmake/Modules/Platform/Darwin-Initialize.cmake:213 (_apple_resolve_multi_arch_sysroots)
  /usr/local/Cellar/cmake/3.17.1/share/cmake/Modules/CMakeSystemSpecificInitialize.cmake:21 (include)
  /Users/lee/projects/ppsspp/build-ios/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (project)


CMake Error at /usr/local/Cellar/cmake/3.17.1/share/cmake/Modules/CMakeTestCCompiler.cmake:44 (try_compile):
  Failed to configure test project build system.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)

```
There is no xcodeproj generated. 

Also, CMakeLists.txt: is not actually present. It may be that it's deleted before I can read its contents and see what the missing parameter might be.

**Comment by unknownbrackets** [comment]
We build every commit for iOS using Travis.  Unfortunately, it's under maintenance at this exact moment, but when it's back up you can check the latest build to see details of its log output in case it helps.

When it's back up, you'll see the latest build info here:
https://travis-ci.org/github/hrydgard/ppsspp

It might be we're using a different (newer?) cmake version, not sure.  It seems that error is occurring in an internal cmake file, triggered from this line of the project CMakeLists.txt:
https://github.com/hrydgard/ppsspp/blob/master/CMakeLists.txt#L3

Just to make sure, are you following these instructions?
https://github.com/hrydgard/ppsspp/wiki/Build-instructions#building-for-ios-mariolopjrs-method

Also, importantly, have you followed the common instructions as well?  Really it's just making sure you have the submodules:
https://github.com/hrydgard/ppsspp/wiki/Build-instructions#download-the-source-code

-[Unknown]

**Comment by kezzico** [comment]
Ok, got it working. Thank you. The cmake command is now outputting PPSSPP.xcodeproj

Something was wrong with the environment. I had previously upgraded to Catalina through Mojave, so I wiped the drive and installed Catalina fresh. 

In Catalina, Apple switched the system shell from BASH to ZSH. I believe this was at the root of the problem some how. The output from CMakeFiles/CMakeError.log read

xcode-select: error: tool ‘xcodebuild’ requires Xcode, but active developer directory ‘/Library/Developer/CommandLineTools’ is a command line tools instance

The answer online for this error is to switch the xcode-select path. Didn't work. I ran the command from both BASH and ZSH. The error would still appear. 

Something is buggy with Apple. Xcode's environment usually breaks some how on OSX between updates.

I used Brew to install cmake. I have Xcode 11.4.1. My OS is Catalina

**Comment by unknownbrackets** [comment]
Interesting, thanks for confirming.

Someone else was reporting the same error with xcode-select recently, and I suspect they may have gone the same zsh path you did.  Hopefully this information will help others - although a full clean install sounds a bit painful.  Glad you got it worked out, though.

I'm going to close this since it's not a PPSSPP issue.

-[Unknown]
