### ISSUE TITLE
Clicking On/Off Allow Remote Debbuger Option Crashing Out The Emulator

### ISSUE THREAD

**Issue by Emulatorer** [hrydgard/ppsspp#12848]
My ScreenRecording Video 
[recording_20200423_011405.mp4.zip](https://github.com/hrydgard/ppsspp/files/4517863/recording_20200423_011405.mp4.zip)

PPSSPP v1.9.3-698
Mali-450 MP4
Android 6.0.1
2GB of RAM

**Comment by Emulatorer** [comment]
Using catlog app (require root)
[ppsspp_crashlog.txt](https://github.com/hrydgard/ppsspp/files/4519706/ppsspp_crashlog.txt)

**Comment by unknownbrackets** [comment]
Oh, oops.  This is fallout from the join changes.

-[Unknown]

**Comment by unknownbrackets** [comment]
Thanks for catching this btw.

-[Unknown]
