### ISSUE TITLE
Naruto Shippuden Ultimate Ninja Impact - PPSSPP Screen Freeze

### ISSUE THREAD

**Issue by HydraTectical** [hrydgard/ppsspp#12847]
I recently got the Naruto Shippuden Ultimate Ninja Impact, and I set the settings to default. There was no problem and it was smooth, but then when I started to begin my first mission, it hanged. More like a screen freeze.

I tried to find settings in the internet and youtube but when I set them up in the settings, it still hangs and freezes. What should I do?

I have the latest version of PPSSPP as of now, not the beta. And I am using an Android OS 6.0 with a 2 GB RAM and a Quad Core.

**Comment by leopard20** [comment]
@HydraTectical 
Change the rendering resolution to 1x. I don't know why this happens on OGL. Vulkan doesn't have this problem.

**Comment by Emulatorer** [comment]
> I recently got the Naruto Shippuden Ultimate Ninja Impact, and I set the settings to default. There was no problem and it was smooth, but then when I started to begin my first mission, it hanged. More like a screen freeze.
> 
> I tried to find settings in the internet and youtube but when I set them up in the settings, it still hangs and freezes. What should I do?
> 
> I have the latest version of PPSSPP as of now, not the beta. And I am using an Android OS 6.0 with a 2 GB RAM and a Quad Core.

Why not try 1st ppsspp latest git from ppsspp buildbot to see if this issue still reproduce!? 🤔

**Comment by Emulatorer** [comment]
I can't reproduce your issue using latest ppsspp git build v1.9.3-968
![Screenshot_20200423-010924](https://user-images.githubusercontent.com/37603562/80011992-36415680-84ff-11ea-8506-e8149a6ab67a.png)

### phone specifications
Android Marshmallow
Mali-450 GPU MP4
2GB of RAM

**Comment by leopard20** [comment]
It's Adreno-specific

**Comment by Emulatorer** [comment]
> It's Adreno specific

ok

**Comment by leopard20** [comment]
@HydraTectical
Just to make sure, what is your phone model?

**Comment by unknownbrackets** [comment]
This may be the same fundamental issue as #11355 then.  As far as I can tell, the Adreno driver crashes and stops rendering new frames.

-[Unknown]

**Comment by leopard20** [comment]
@unknownbrackets 
Any ideas why it only does that at 2x and higher rendering resolutions? 1x doesn't seem to crash.

**Comment by hrydgard** [comment]
Driver bugs, which I'm pretty sure is what we're dealing with here, are hard to reason about.

**Comment by Emulatorer** [comment]
> @unknownbrackets
> Any ideas why it only does that at 2x and higher rendering resolutions? 1x doesn't seem to crash the emulator.

Can you try to add this game id to compat.ini [BlockTransferAllowCreateFB] and enable block transfer effects test if it's still crashing at 2x rendering resolution?

**Comment by leopard20** [comment]
Why should one even do that?! It crashes with or without Block Transfer Effects.

**Comment by faroukabd000** [comment]
I used 2x rendering resolution and the game work normally in opengl but have black squares (Block Transfer Effects not doing  adoin thing) and slow down in the loading screen ..... but work fine no crash
(mali720 with opengl 3.1 / 4 core 1ghz cpu each / 2 go ram).

**Comment by IrfanH495** [comment]
Sharp SH04H
Adreno 530
Snapdragon 820 
Openg GL
1xPSP GOOD
2xPSP FC
Vulkan 
for vulkan is good but there is a small bug
![Screenshot_20211225-170957](https://user-images.githubusercontent.com/78854859/147382806-92299017-4cc1-4ee9-b749-51debcd01554.png)

**Comment by IrfanH495** [comment]
@unknownbrackets 
I think PixelDepthRounding can fix it
[PixelDepthRounding]
narutospuni
ULES01537 = true
do i have to record it

**Comment by IrfanH495** [comment]
Both for vulkan & OpenGL good if naruto id added to PixelDepthRounding
this is video
https://drive.google.com/file/d/13URq3jPtwQwIzbD8GvWq5Q_oSQ1OdRbo/view?usp=drivesdk
slow because my device is overheating

**Comment by Gamemulatorer** [comment]
@IrfanH495 opengl doesn't freeze? Vulkan has graphics issue? Did you try the ppsspp latest development build apk?

**Comment by IrfanH495** [comment]
> @IrfanH495 opengl doesn't freeze? Vulkan has graphics issue? Did you try the ppsspp latest development build apk?

i'm using version v1.12.3-491-gcc767622d and using compat.ini PixelDepthRounding

**Comment by Gamemulatorer** [comment]
You forgot to answer my other question

**Comment by IrfanH495** [comment]
this game has also been experiencing fc Corpse Party & Ikki Tousen: Xross Impact
this only happens on opengl
https://drive.google.com/file/d/18w5C574m2GcAdygR3ZvGyQ-CFkSspNGS/view?usp=drivesdk

**Comment by IrfanH495** [comment]
is this the same issue.?  if i play as sasori in chapter 1 stage gai against kisame.  iron sand will not disappear
![Screenshot_20220701-065548](https://user-images.githubusercontent.com/78854859/176797518-c68c5e80-324c-4c0b-9107-af71927d2e10.png)
![Screenshot_20220701-065603](https://user-images.githubusercontent.com/78854859/176797522-022e32f7-d834-44ee-8570-3b1b1e5a5574.png)
![Screenshot_20220701-065635](https://user-images.githubusercontent.com/78854859/176797530-13c8b9af-e2e3-4b40-a4fe-47d3fc8d15a8.png)
![Screenshot_20220701-065659](https://user-images.githubusercontent.com/78854859/176797536-c9f579b3-74e8-4164-8b77-4737df2cc13c.png)

**Comment by IrfanH495** [comment]
only in black lines like screenshot black sand won't disappear
![sss](https://user-images.githubusercontent.com/78854859/176798469-2d73aefd-f0c7-4d4e-8e52-514d62f87194.png)

**Comment by Gamemulatorer** [comment]
> Sharp SH04H Adreno 530 Snapdragon 820 Openg GL 1xPSP GOOD 2xPSP FC Vulkan for vulkan is good but there is a small bug ![Screenshot_20211225-170957](https://user-images.githubusercontent.com/78854859/147382806-92299017-4cc1-4ee9-b749-51debcd01554.png)

Cannot reproduce this on adreno 610
5X Resolution Latest Build.
![Screenshot_2022-09-03-13-23-30-373_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/188257086-19d1da18-2b79-417f-ba49-39a59f9e3fba.jpg)

**Comment by Gamemulatorer** [comment]
> Sharp SH04H Adreno 530 Snapdragon 820 Openg GL 1xPSP GOOD 2xPSP FC Vulkan for vulkan is good but there is a small bug ![Screenshot_20211225-170957](https://user-images.githubusercontent.com/78854859/147382806-92299017-4cc1-4ee9-b749-51debcd01554.png)

PixelDepthRounding fixes this glitch.
![Screenshot_2022-09-09-21-29-14-45](https://user-images.githubusercontent.com/37603562/189361771-c0415860-c0c7-4f46-8c39-e82dd008ec33.png)

**Comment by Gamemulatorer** [comment]
This game doesn't crash anymore using opengl backend on my Oppo a3s adreno 506!

**Comment by hrydgard** [comment]
I think the remaining issue here then is exactly the same as #11583 ?

Closing.

(And like I commented in that one, could you try VertexDepthRounding? )

**Comment by Gamemulatorer** [comment]
This game still crashing using opengl backend on adreno 5xx or 3xx
