### ISSUE TITLE
Unification URLs in credits

### ISSUE THREAD

**Issue by TotalCaesar659** [hrydgard/ppsspp#12844]
URLs in credits of Windows/Linux and Android versions are different.
![0](https://user-images.githubusercontent.com/14265316/79803266-555aaf80-836a-11ea-8d36-376d93b9f860.png)
![1](https://user-images.githubusercontent.com/14265316/79803283-5986cd00-836a-11ea-91ec-97788dccaa0e.png)
I think it's better to remove Twitter URL in Android version (cause it's [rarely updated](https://twitter.com/PPSSPP_emu)) and add Discord one.

**Comment by hrydgard** [comment]
Now I just show all the buttons everywhere, except the Android-specific Share.
