### ISSUE TITLE
Raspberry Pi 3b: Error on start PPSSPP

### ISSUE THREAD

**Issue by 007fred50** [hrydgard/ppsspp#12859]
Hello,
I'm in (raspberry pi 3 b) i follow the guide here (https://www.youtube.com/watch?v=LwoTBAayP3c)

I have 2 screen on my raspberry pi (LCD and HDMI)

Error code here:
```
E: VulkanLoader.cpp:339: Failed to create vulkan instance.
DEBUG: Vulkan is not available, not using Vulkan.
Xlib:  extension "RANDR" missing on display ":0.0".
I: Config.cpp:492: Longest display side: -1 pixels. Choosing scale 1
02:06:868 Core/Config.cpp:1083 I[LOADER]: Loading controller config: /home/pi/.config/ppsspp/PSP/SYSTEM/controls.ini
02:06:959 Core/Config.cpp:1169 I[LOADER]: Config saved (got storage permission): '/home/pi/.config/ppsspp/PSP/SYSTEM/ppsspp.ini'
02:06:963 Core/Config.cpp:1182 I[LOADER]: Controller config saved: /home/pi/.config/ppsspp/PSP/SYSTEM/controls.ini
Pixels: 800 x 480
Virtual pixels: 800 x 480
OpenGL 2.0 or higher.
I: gpu_features.cpp:174: GPU Vendor : VMware, Inc. ; renderer: llvmpipe (LLVM 9.0.1, 128 bits) version str: 3.3 (Core Profile) Mesa 19.3.2 ; GLSL version str: 3.30
ALSA lib pcm_hw.c:1903:(_snd_pcm_hw_open) card is not defined
E: SDLMain.cpp:590: Failed to open audio: ALSA: Couldn't open audio device: Invalid argument
loading control pad mappings from gamecontrollerdb.txt: SUCCESS!
I: NativeApp.cpp:776: NativeInitGraphics
I: NativeApp.cpp:852: NativeInitGraphics completed
02:07:889 UI/DiscordIntegration.cpp:55 I[SYSTEM]: Discord connection initialized
I: GLRenderManager.cpp:196: Running first frame (0)
02:10:761 Core/Config.cpp:1169 I[LOADER]: Config saved (clearFailedGPUBackends): '/home/pi/.config/ppsspp/PSP/SYSTEM/ppsspp.ini'
02:10:765 Core/Config.cpp:1182 I[LOADER]: Controller config saved: /home/pi/.config/ppsspp/PSP/SYSTEM/controls.ini
```

Can you help me with that?
Thanks for your time :)

**Comment by hrydgard** [comment]
What happens next, does it crash or exit? It seems like an unlikely last line from a log in the latter case.

The audio error is the most likely to be related to the failure, wonder what `Invalid argument` that might be?

**Comment by 007fred50** [comment]
it will not start nothing happen, i run as PPSSPPSDL in terminal and get the error.

very short blink on LCD Screen. nut nothing in HDMI screen

**Comment by 007fred50** [comment]
Then i try to start VLC Player it says: (Audio output failed, The audio device "defualt" could not be used: invalid argument)

as you say (**invalid argument**) in another program still not working.

i need to install sound on my raspberry pi.

**Comment by 007fred50** [comment]
there can i download the right sound driver for (raspberry pi 3 b)

**Comment by hrydgard** [comment]
I really don't know about that. Though ideally PPSSPP would handle the lack of an audio device more gracefully, so even if you do manage to get sound drivers, I'll leave this open.

**Comment by unknownbrackets** [comment]
Not sure if this is a problem:

```
Xlib:  extension "RANDR" missing on display ":0.0".
```

https://bugs.launchpad.net/ubuntu/+bug/157319
https://askubuntu.com/questions/66372/gui-apps-always-generate-xlib-extension-randr-missing-on-display-0-0
https://www.raspberrypi.org/forums/viewtopic.php?t=16598

It seems odd that it's saying VMware.  Is this actually running on a Raspberry Pi?

-[Unknown]

**Comment by 007fred50** [comment]
i found a solution

Before i start the qustion i installed 2 steps*

Step 1:
https://www.youtube.com/watch?v=LwoTBAayP3c

Step 2:
https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=246384&sid=a99b23062f11e395cafbd6a4d4359f15

Step2.a: Note()
remove the line (dtparam=audio=off) and sound will be loaded !
Step2.b Note()
DON*T USE THIS COMMAND !!! (**sudo startx -- -layout Multihead**) IT WILL FUCK UP YOUR RASPBERRY PI !

**Comment by hrydgard** [comment]
Ok, cool - I'm gonna close this. Hopefully Google will find this for other people with the same problem.
