### ISSUE TITLE
Mumbo Jumbo games freeze on loading screen since v1.6

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#12857]
### What happens?
I try and test mumbo jumbo games 7 wonders & Super collapse 3 and they both hang/freeze on start up of the game showing game logo.
![Screenshot_20200427-111912](https://user-images.githubusercontent.com/37603562/80331289-44360500-887a-11ea-967c-c41d4ce5e21b.png)
![Screenshot_20200427-111953](https://user-images.githubusercontent.com/37603562/80331297-4ac47c80-887a-11ea-8c1f-572211ffd112.png)

### What *should* happen?
Should start the game without hang/freeze?

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Android 6.0.1
Octacore 1.36Ghz
2GB RAM
PPSSPP v1.9.3-722-gitbuild
GE Dump:
[ULUS10287_0001.zip](https://github.com/hrydgard/ppsspp/files/4537289/ULUS10287_0001.zip)

**Comment by Panderner** [comment]
And platypus too

**Comment by Gamemulatorer** [comment]
> And platypus too

Is platypus also a mumbo jumbo game?
I will link your issue here #10919

**Comment by unknownbrackets** [comment]
GE dumps are only really helpful for graphics.  If the game isn't rendering anything, it doesn't tell much more than the screenshot.

7 wonders has worked in the past:
https://report.ppsspp.org/game/ULES01037_1.00

Though one person on super slow hardware noted Super Collapse 3 not loading:
https://report.ppsspp.org/game/ULUS10287_1.01

Keep in mind that some of these less popular games were poorly optimized, even on a real PSP.  Loading screens lasting 10+ seconds was not unheard of.  Have you waited a good 30 seconds to make sure it's not just taking a while to load?  It sounds like that's the issue with Platypus.

It may show 1/60 if the game is changing frame rates rapidly while loading things, so that's not necessarily a good indicator even.

If 7 wonders really isn't working, compare your settings to the report where it was.  Try some older git builds and verify your disc's CRC.

-[Unknown]

**Comment by Panderner** [comment]
Mumbo Jumbo games needs in underclock the PSP CPU to below further to load the game faster. Super Jumbo 3 is playable and it's working fine I underclock the PSP CPU to 25 MHz.

**Comment by unknownbrackets** [comment]
But does it work if you wait long enough at default settings?

-[Unknown]

**Comment by Gamemulatorer** [comment]
> But does it work if you wait long enough at default settings?
> 
> -[Unknown]

Last working is v1.5.4 the game is loading properly issue started in v1.6 my suspect is #10888 not really sure I will test lately ppsspp v1.6 git build where is start broken..

**Comment by Gamemulatorer** [comment]
This issue is likely similar to #11019

**Comment by unknownbrackets** [comment]
Not really, that was a very different issue and changing the CPU clock had no effect there.

-[Unknown]

**Comment by Panderner** [comment]
> Not really, that was a very different issue and changing the CPU clock had no effect there.
> 
> -[Unknown]

Underclocking the PSP's CPU is needed to shorten loading times for low end Android devices, overclocking the PSP CPU might result longer loading times.

I'm using Realme C2 for Platypus loading screen until title screen results:

Default Settings: 50 seconds
1000 MHz in 2x resolution: 4 minutes
Auto in 1x resolution: 30 seconds
30 MHz: 5 seconds
1000 MHz in 1x resolution: 2 minutes and 30 seconds

**Comment by unknownbrackets** [comment]
Given the commit range it might be force max fps not being on by default anymore.

Maybe these games just render endlessly at max FPS during these loading screens.  That would explain it getting much worse if you crank up the Mhz to unrealistic values.

-[Unknown]

**Comment by hrydgard** [comment]
I turned the flag on for them, please test and report if it works.

**Comment by Panderner** [comment]
Luxor Games The Wrath of Set and Pharaoh's challenge which is published by Mumbo Jumbo works fine and it loads faster Even I set the PSP's Clock to 1000 Mhz

**Comment by Gamemulatorer** [comment]
> Given the commit range it might be force max fps not being on by default anymore.
> 
> Maybe these games just render endlessly at max FPS during these loading screens. That would explain it getting much worse if you crank up the Mhz to unrealistic values.
> 
> -[Unknown]

Yes this issue was fix by adding Mumbo Jumbo Games to [ForceMax60FPS] compat.ini 🙂
Closing...

**Comment by unknownbrackets** [comment]
There's probably some syscall that's not taking as long as it should or something to match the PSP, though...

**Comment by hrydgard** [comment]
Indeed...

**Comment by Gamemulatorer** [comment]
@hrydgard you forgot to add this game also
![Screenshot_20200428-190608](https://user-images.githubusercontent.com/37603562/80480494-5d76a880-8983-11ea-906f-e57bc1ba76d1.png)

**Comment by Panderner** [comment]
> @hrydgard you forgot to add this game also
> ![Screenshot_20200428-190608](https://user-images.githubusercontent.com/37603562/80480494-5d76a880-8983-11ea-906f-e57bc1ba76d1.png)

No need to add this game because the game work fine and loads faster even I overclocked to PSP's CPU 1000 MHz on stable version
