### ISSUE TITLE
xbox controller in ppsspp

### ISSUE THREAD

**Issue by 007fred50** [hrydgard/ppsspp#12864]
Is it posible to change xbox controls with your ppsspp ?

i'll change some key on xbox, **(start and select)** is missing in xbox controller.

So how can  i change select from xbox controller. are xbox controller supported?

**Comment by hrydgard** [comment]
Yes, there is control mapping support, just go into settings/controls. 

On Windows your Xbox controller should just work by default. Dunno about other platforms but it's not hard to map it. I'd just map select to clicking the left stick, or something.
