### ISSUE TITLE
Raspberry Pi 3b, run safe

### ISSUE THREAD

**Issue by 007fred50** [hrydgard/ppsspp#12863]
i have installed PPSSPP and i test it on Raspberry Pi 3b.
but there are lag in move the player inside the game.

the PPSSPP Menu run very well, but not the game

Can you help me with PPSSPP run in Raspberry Pi 3b !

**Comment by quicksilver7837** [comment]
The pi 3 isnt really powerful enough to run PPSSPP. A few undemanding games will work ok but overall it's a poor experience. Using a more powerful device is the only thing you can do. Or if you want to use a raspberry pi, then use the pi 4. It is a much improved experience.

**Comment by hrydgard** [comment]
Yeah, it just doesn't have the grunt. Gonna have to close this unfortunately.
