### ISSUE TITLE
Breath of Fire 3 ULES00193 constant screen flickering

### ISSUE THREAD

**Issue by Ledah** [hrydgard/ppsspp#12869]
Flickering started from build PPSSPP_v1.9.3-260-g81118454f and still exist on all builds till PPSSPP_v1.9.3-731-gf82e7a4e7 . 
It's not the same as it was on previous issue with this game, other games don't have this issue but maybe it breaks something else. Attached video for the problem. https://youtu.be/avHnW7TL8oQ

Iphone 7 plus iOS 13.4.1 
Open GL rendring

**Comment by sum2012** [comment]
Frame dump of the flickering  video
https://gist.github.com/sum2012/ffa292b6a486a150bf461c06d23b40fd

Confirm last work 
v1.9.3-254-gea819673d

First bad
v1.9.3-260-g81118454f

It mean #12596 bad

**Comment by hrydgard** [comment]
Thanks for finding the bad commit! I'll look into this for 1.10.

**Comment by hrydgard** [comment]
OpenGL is affected, but Vulkan is not.

**Comment by Gamemulatorer** [comment]
I just tested this game as of now and the issue also happened on android

**Comment by hrydgard** [comment]
Reverting this specific change fixes it: 

https://github.com/hrydgard/ppsspp/pull/12596/commits/3aa575daef1f269c6ee33036cba55524c159f487

So much state leaking around... Hm.

**Comment by hrydgard** [comment]
Ok so we got a little circular thing going on here. For this to work, in DrawEngineGLES.cpp, SoftwareTransform needs to happen before ApplyTexture. But for Artic Adventures to work (see #12538 ), SoftwareTransform needs to happen after ApplyDrawState. But ApplyDrawState must happen after ApplyTexture, making the whole thing impossible to solve - the constraints have no solution that keep both games working.

So one or more of these probably needs to be taken apart and things moved around a bit...  Need to look at it in a bit more detail to figure it out.

**Comment by unknownbrackets** [comment]
Wait, it doesn't really make sense right now.  It's checking for v to be beyond 1.8?  It's only triggering the other way because the previous texture had a 256 height.  It's a mistake that it's even working now, the formulas look wrong.

-[Unknown]
