### ISSUE TITLE
Orphis buildbot down (404 Not Found)

### ISSUE THREAD

**Issue by RokkumanX** [hrydgard/ppsspp#12872]
Hi

This isn't a issue with PPSSPP per se but I have used Orphis buildbot for a very very long time (5 years) to download daily/regular builds of PPSSPP but all of a sudden it looks like it's completely down giving a 404 Not Found message.

This seems to have happen quite recently, it was not long ago I could download PPSSPP 1.9.3-6xx builds and last Google cache is from 2020-05-03

Would making a ci.appveyor solution be possible enable to download PPSSPP builds?

Seems like good build sources is getting scarcer and scarcer these days.

Big thank you in advance!

**Comment by iota97** [comment]
https://buildbot.orphis.net/ppsspp/ work fine for me, might just have been down for a bit?

**Comment by RokkumanX** [comment]
Strange, this is how it looks for me:

![image](https://user-images.githubusercontent.com/50436544/81059912-bd180b00-8ed1-11ea-8098-946f9f63fd40.png)

**Comment by hrydgard** [comment]
Works for me...

**Comment by iota97** [comment]
It could also be some issues with the balance loader selecting a different server for him.

**Comment by RokkumanX** [comment]
Seems to work after I restarted my router, I don't know what really happened and on top of all things Firefox started to alert me that the website was unsafe and rambling about some certificate.

Thanks anyway guys!
