### ISSUE TITLE
✦Yu-Gi-Oh (yugi) Tag Force 2,3,4,5,6 + special "Tag duel" fixing Dream!✦

### ISSUE THREAD

**Issue by Ryo95** [hrydgard/ppsspp#12877]
✦This post will be posted in "Gitbhub + Discord + PPSSPP Forum" to maximize the search and help rate from all Admins (I don't intend to SPAM!)✦
✦My Story is..✦

✦5 Years ago I was happy that PPSSPP could finally run the game without any Problems with it's new release .. but nothing is perfect.. I was depressed because **I couldn't play Multiplayer**!
so I forgot about that game and moved on..
.
✦But this Year by Chance.. I was searching for a fix for this Problem and I found someone who says that I can play it online **on Version 1.3** which is old and the dream came true I could play it **1 vs 1** with no Problems from PC vs PC or PC vs Android with PPSSPP 1.3 apk using the Program "Zerotier one" instead of Hamachi! 
.
✦The game worked 1 vs 1 Duel on version **1.3 / 1.0.1 / 1.2.2** with no Problems.
BUT on the main website the newest versions of PPSSPP **1.9.4** and the other main version listed on the main Website **1.8.0 / 1.7.4 / 1.6.3**  gets **"Connection error!"** and can't even start a 1 vs 1 Duel!
.
✦Which makes me crazy and I ask myself did the developers accidentally and by chance fix the game 1 vs 1 on versions  1.3 / 1.0.1 / 1.2.2?
So I decided to try it Multiplayer 1 vs 1 on version **1.4** which came after 1.3 (which is perfect for 1vs1) and **it didn't WORK** and got Connection error !
and **starting from version 1.4 to the newest version 1.9.4 the game doesn't WORK 1 vs 1!**
.
✦So why the old versions supports 1 vs 1 duels and the whole new versions doesn't even support 1 vs 1 or 2 vs 2 Duels? Why the developers didn't notice and fix that till now in the new versions!?
So what is my Problem now if I can just play the Game in the older versions!?
and from here starts my Post!
.
✦Before telling my Problem I want to thank the Creator Henrik (who I wish he replies to me and all the Developers for their huge Efforts to make us able to play Tag force 1 to 6 + Tag special without any Problems!
.
✦But can we make it perfect and settle this this Year and fix the biggest Problem in the game which till now not fixed and it's the **"TAG DUEL CONNECTION ERROR"**
My Wish is to play with my Friends Tag Duel **2 vs 2** not Single Duel 1 vs 1 
.
I will report now the ways I tried to Tag Duel and what is the Error and why it appears!
At the beginning when I create a Game and join with my other Laptop and Android Phone
I couldn't see the other Players in the Lobby and the Problem because I had to **disable the Firewall** and it was fixed finally and also I had to make every device has the **same port offset number!**
.
✦So now I could fix the Problem of seeing each other **but couldn't even start the Tag Duel!**
I host with my PC and the Laptop and Mobile are the other players 
So when does the Error appear?
.
it appears when we start the game and I just found out that the Problem comes from the PPSSPP coding and System the PPSSPP only want to choose 1 Player from the 3 Devices, **he can't connect more than 2 Players in one Duel..** because I can create a Tag duel and connect 1 player only and we can play against the NPC 2 vs 2 with no problems but I can't play with friends!
.
✦I just want to know will this problem be fixed? should I still have faith in the developers or they will not fix it because they have no time and lives to run (I know) please whoever will reply to this tell me the Truth if this will be fixed or not so either i forget about it and the whole game or wait for your new version with the fix!
.
✦Notice 1: I can help with the process of fixing and testing if you need more players to test with

✦Notice 2: Please see the difference between the versions that able to run 1 vs 1 duel and the newest versions that can't run it and maybe there is a code missing or something that someone may changed it in the newer versions and edit it to fix it quicker..

**Comment by Gamemulatorer** [comment]
This is related to #8400 and #9623

**Comment by Gamemulatorer** [comment]
@Ryo95 Just OT :) I wanna ask you since you played yu-gi-oh games in ppsspp do you still experience this issue #7914 ?

**Comment by Ryo95** [comment]
Thanks for reply..
issue number #8400 is already like my case but its not perfect he could in that issue play with his Brother only 1 vs 1 but he didn't mention that he could play with more Friends like 2 vs 2! I already could play 1 vs 1 but the Tag duel still not fixed! and for issue #9623 I already make the number of port offset equal to all the other players so that is no problem and for #7914 I don't have any Problems for save data files..

**Comment by Gamemulatorer** [comment]
> Thanks for reply..
> issue number #8400 is already like my case but its not perfect he could in that issue play with his Brother only 1 vs 1 but he didn't mention that he could play with more Friends like 2 vs 2! I already could play 1 vs 1 but the Tag duel still not fixed! and for issue #9623 I already make the number of port offset equal to all the other players so that is no problem and for #7914 I don't have any Problems for save data files..

OK Thanks for the explanation and fast reply :)

**Comment by Ryo95** [comment]
@Gamemulatorer So.. Do you know how to start a Tag duel without Connection error?!

**Comment by Gamemulatorer** [comment]
> @Gamemulatorer So.. Do you know how to start a Tag duel without Connection error?!

@Ryo95 sad to say but idk :(

**Comment by adenovan** [comment]
instead of this issues getting to nowhere again helping us with the logs on old version that working and new version that break will be a great help

**Comment by Ryo95** [comment]
@adenovan I can help you all the day.. but I don't know **how** to get these logs and send it to someone to test and fix it .. can you explain it to me?

*Notice: I know that you are the Moderator of Amultios.. I tested your version and it behaves like the PPSSPP **1.4 till the newest version 1.9.4** which is sadly **not** even **working** in Multiplayer **Single** duel or the **Tag** duel.. but I believe that you are a hard working person who wants to fix it one day that's why you replied to me and took care and I appreciate it.

**Comment by adenovan** [comment]
see #9170 there is a log console screenshot that show how the game call adhoc function.

Debug logging is available on developer menu , use ppsspp on pc build to easily monitor the log. if you use android its still need pc to see the logs either using remote debugger or adblogcat.

with many refrence its will be more easier to debug the actual issues as every software develoment relying on logs a lot.

**Comment by Ryo95** [comment]
@adenovan HALLO BACK!
I wanted to inform you that **I CAN'T** get a proper Screenshot as it keeps respawning and spamming so quickly besides I am **NOT A PROGRAMMER!**.. SO>> Here is a link of the ISO FILE of YGO Tag force 2 which we will together make the test on!
https://www.freeroms.com/rom/psp/yu-gi-oh!_gx_tag_force_2_europe.htm
It's the same iso file that I have so we make sure it will work!
.
.
I have sent you a private message on Discord SO>> tell me when we can start testing it!
I will wait you to reply.. as long as the University is closed I will have much time to help xD

**Comment by Ryo95** [comment]
[ppsspp-1-3.zip](https://github.com/hrydgard/ppsspp/files/4605524/ppsspp-1-3.zip)
And that's the same ppsspp I use 1.3

**Comment by Ryo95** [comment]
@adenovan I am gonna now post all the **LOGS from the Single Duel errors and Tag duel errors** which you requested from me from different Versions to **maximize the analyzing** of all the codes! to fix the game hopefully! and I hope **all the devs and Henrik and all admins** see it too and help us! and hope that will be fixed **ASAP**!
.
.
First I am gonna divide my Post to >> Single duel << and >> Tag duel << ERRORS!
For >> Single Duel << Errors.. 
I am gonna first post the Logs of the Single duel which worked with me fine with no errors! on the version **1.0.1 / 1.2.2 / 1.3** **(WHICH ARE THE ONLY 3 VERSIONS THAT CAN RUN SINGLE DUEL IN MULTIPLAYER MODE!)** any Version after 1.3 unfortunately **DOESN'T WORK AT ALL!** for multiplayer Single Duel or Tag Duel!
And I will post for each version the Screenshots which might be more that 1 screenshot >> one for the Host (WHO HOSTED THE DUEL) and one for the Player (WHO JOINED THE DUEL)!
.
.
✦Single Duel ✦ ✦ Version 1.0.1 ✦ ✦Working!✦
✦Host✦
![1 0 1 HOST SCREEN NUMBER 1](https://user-images.githubusercontent.com/65016838/81576360-754d2400-93a8-11ea-85c0-91f7cfa2c154.png)
![1 0 1 HOST SCREEN NUMBER 2](https://user-images.githubusercontent.com/65016838/81576362-75e5ba80-93a8-11ea-91ec-d1f2955a4bc4.png)
✦Player✦
![1 0 1 PLAYER SCREEN NUMBER 1](https://user-images.githubusercontent.com/65016838/81576487-9a419700-93a8-11ea-8e08-623e60bc7db3.png)
![1 0 1 PLAYER SCREEN NUMBER 2](https://user-images.githubusercontent.com/65016838/81576491-9ada2d80-93a8-11ea-9201-85542af37d8c.png)
![1 0 1 PlAYER SCREEN NUMBER 3](https://user-images.githubusercontent.com/65016838/81576493-9b72c400-93a8-11ea-8d78-f5fb28d45250.png)
ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ
✦Single Duel✦ ✦Version 1.2.2✦ ✦Working!✦
✦Host✦
![1 2 2 HOST SCREEN NUMBER 1](https://user-images.githubusercontent.com/65016838/81576688-d83ebb00-93a8-11ea-8818-ffd07e9a5612.png)
![1 2 2 HOST SCREEN NUMBER 2](https://user-images.githubusercontent.com/65016838/81576696-d8d75180-93a8-11ea-8ca2-d88825777434.png)
✦Player✦
![1 2 2 PLAYER SCREEN NUMBER 1](https://user-images.githubusercontent.com/65016838/81576756-ec82b800-93a8-11ea-916f-3c09c050e478.png)
![1 2 2 PLAYER SCREEN NUMBER 2](https://user-images.githubusercontent.com/65016838/81576758-ed1b4e80-93a8-11ea-80cf-5532762a8bc3.png)
ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ
✦Single Duel✦✦Version 1.3✦ ✦Working!✦
✦Host✦
![1 3 HOST](https://user-images.githubusercontent.com/65016838/81576843-0c19e080-93a9-11ea-8068-d7e9b5f232b4.png)
✦Player✦
![1 3 Player](https://user-images.githubusercontent.com/65016838/81576877-150ab200-93a9-11ea-935c-d06deed9948f.png)
ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ
.
Now for the most important Part.. these are the Screenshots for the **NOT WORKING MULTIPLAYER SINGLE DUEL** on Version **1.8 / 1.9.3 / and also for Amultios!**
✦Single Duel✦ ✦Version 1.8.0✦ ✦not working!✦
✦Host✦
![1 8 0 HOST](https://user-images.githubusercontent.com/65016838/81577281-86e2fb80-93a9-11ea-845e-c21c9ea16e30.png)
✦Player✦
![1 8 0 PLAYER](https://user-images.githubusercontent.com/65016838/81577319-9104fa00-93a9-11ea-9548-42604915e670.png)
ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ
✦Single Duel✦ ✦Version 1.9.3✦ ✦not working✦
✦Host✦
![1 9 3 HOST](https://user-images.githubusercontent.com/65016838/81577423-b3971300-93a9-11ea-831e-cfc582fa5bbe.png)
✦Player✦
![1 9 3 Player](https://user-images.githubusercontent.com/65016838/81577457-bbef4e00-93a9-11ea-88ab-22315e3dbd9f.png)
ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ
✦Single Duel✦✦Amultios✦ ✦not working!✦
✦Host✦
![Amulitos HOST](https://user-images.githubusercontent.com/65016838/81577539-d5909580-93a9-11ea-863f-8051acd2568a.png)
✦Player✦
![Amulitos Player](https://user-images.githubusercontent.com/65016838/81577564-dcb7a380-93a9-11ea-9f4f-982f2018b180.png)
ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Now I finished posting about the Single Duel .. now this will be the Screenshots of the **TAG DUEL ERROR!** the test was made **on two different Versions 1.3 / 1.9.3**
I made that test with my PC and my LAPTOP and my ANDROID mobile we all use the same version.
*Notice* I know that we should be 4 players but I only have 1 pc and 1 laptop and 1 android so we can play for example (PC+LAP) TEAM1 + (Android+NPC(A.I)) Team 2..
.
.
When I host we can all see each other with no Problems in the game room but **we can never all start the Duel together!**
One of us must get a Disconnection! >> for example the PC hosts and The android joins! and the LAPTOP can't even join the room and sometimes when he can join the game room by luck,
and we start the duel he get disconnected! and when one us gets disconnect all the duel can't start because all players must be connected!
So that was the two errors that I saved their logs!
.
.
The first one is .. when PC host and Android joins and the Laptop can't even enter the game room..
✦Tag Duel✦ ✦Version 1.3✦ ✦Not working!✦
✦Host is the PC✦
![Error 3 1 3 Host](https://user-images.githubusercontent.com/65016838/81579762-d840ba00-93ac-11ea-97d8-6d51a6d75088.png)
✦LAPTOP✦
![Error 3 1 3 Player!](https://user-images.githubusercontent.com/65016838/81579849-f27a9800-93ac-11ea-99bd-fefa5b58859b.png)
ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Now I did the same Test but I made the ANDROID Host the Duel!
✦Tag Duel✦ ✦Version 1.3✦ ✦Not working!✦
✦Host is the ANDROID✦
✦This screenshot is from the PC while the mobile is the host✦
![Error 3 1 3 mobile host this is pc](https://user-images.githubusercontent.com/65016838/81580072-3ec5d800-93ad-11ea-8f43-5c6ceebca4a9.png)
✦LAPTOP✦
![Error 3 1 3 mobile host!](https://user-images.githubusercontent.com/65016838/81580121-4d13f400-93ad-11ea-902d-c61716fe4e7c.png)
ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Now the same error but on different Version>>
✦Tag Duel✦ ✦Version 1.9.3✦ ✦Not working!✦
✦Host is the PC+his screenshot✦
![Error 3 1 9 3 Host](https://user-images.githubusercontent.com/65016838/81580323-9401e980-93ad-11ea-87bc-4fe31686aca6.png)
✦Laptop+his screenshot✦
![Error 3 1 9 3 Player](https://user-images.githubusercontent.com/65016838/81580387-a9771380-93ad-11ea-9763-31e23ed8af63.png)
ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ
Now this is the same error too with the same version but the host is the mobile and I took 2 screenshots .. one from PC and one From Laptop!
✦Tag Duel✦ ✦Version 1.9.3✦ ✦Not working!✦
✦Host is the mobile✦
✦PC screenshot✦
![Error 3 1 9 3 mobile host this is pc](https://user-images.githubusercontent.com/65016838/81580669-083c8d00-93ae-11ea-957f-c0cff21caa9b.png)
✦Laptop Screenshot✦
![Error 3 1 9 3 mobile host this lap](https://user-images.githubusercontent.com/65016838/81580740-1e4a4d80-93ae-11ea-937d-31b8f8a720cb.png)
ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Now for the second Error >> This is the Erros which by luck I could join with all players the Game room and all are ready and when I start the duel one of the Players is not chosen to join with us and gets disconnect .. because the ppsspp might is programmed till now that he only chooses 1 player not more than 1!
✦Tag Duel✦ ✦Version 1.3✦ ✦Not working!✦
✦Host is the PC+his screenshot✦
![Error 2 1 3 Host](https://user-images.githubusercontent.com/65016838/81581051-7e40f400-93ae-11ea-9924-4055817f4fa9.png)
✦Laptop screenshot✦
![Error 2 1 3 Player](https://user-images.githubusercontent.com/65016838/81581241-c19b6280-93ae-11ea-88d0-130439460473.png)
ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Now I have posted all the things that you all need to fix the game.. 
If you need somethings else like new screenshots or anything contact me and the quickest way is my discord Ryo#4503

**Comment by adenovan** [comment]
hmm looks like this game suffer the same bug with kingdom heart. 

kk good catch what is this game do with 00:00:00:00:00 mac address something weird there and probably your tag is not working due to matching select target fail allot will look into that api call after im finished digging on control module.

**Comment by HiImBrala** [comment]
As i said on Discord,game has Syncing issues,works between 2 players,but not more,really would like to see this fixed

**Comment by Anuskuss** [comment]
This was caused by #8975. @tywald I don't understand the code fully but maybe we should check if the friends are still online before blindly removing them?

**Comment by adenovan** [comment]
i guess its not that code make problem , something corrupted on psp register still guessing probably related to memory allocation many of apis still badly implemented until im finished with digimon something will be clear enough to trace what is the real culprit.

**Comment by Anuskuss** [comment]
@adenovan Thank you for your work and especially the quick chat! Kinda offtopic but does DBZ:SB2 work in Amultios? I think I saw someone play it in another thread but I doesn't work for me.

Also you said in [#8975 (comment)](https://github.com/hrydgard/ppsspp/pull/8975#issuecomment-249116747) that YGO:TF6 worked for you while OP claims otherwise. Is that still true?

**Comment by adenovan** [comment]
many of games still broken in amultios  i need to sync the networking timing with main emulator thread first to deeply fix sync problem. guess its still not working

**Comment by Lemoncak3** [comment]
I have tested network duel in yu-gi-oh in 5DS tag force 5 and it worked, i even battled with my brother till the end without any error. Maybe other yu-gi-oh worked fine too now?

**Comment by Anuskuss** [comment]
Yeah, probably #13132 fixed this for good. Can be closed.

**Comment by Gamemulatorer** [comment]
> I have tested network duel in yu-gi-oh in 5DS tag force 5 and it worked, i even battled with my brother till the end without any error. Maybe other yu-gi-oh worked fine too now?

Can I ask what is your network settings to play multiplayer on ygo tag force v?

**Comment by Lemoncak3** [comment]
![Screenshot_20200819-174957](https://user-images.githubusercontent.com/67026697/90626163-c640a400-e244-11ea-93f9-f343154ed700.png)
![Screenshot_20200819-175002](https://user-images.githubusercontent.com/67026697/90626172-c93b9480-e244-11ea-8a26-8e9d306e6a6b.png)
This is my setting, and i have tested it for few times already.

**Comment by Gamemulatorer** [comment]
> ![Screenshot_20200819-174957](https://user-images.githubusercontent.com/67026697/90626163-c640a400-e244-11ea-93f9-f343154ed700.png)
> ![Screenshot_20200819-175002](https://user-images.githubusercontent.com/67026697/90626172-c93b9480-e244-11ea-8a26-8e9d306e6a6b.png)
> This is my setting, and i have tested it for few times already.

@Lemoncak3 thanks I will try your settings on YGO ARC V Tag Force Special 👍
