### ISSUE TITLE
[Android][OpenGL&Vulkan][Crash] Crash PPSSPP when Changing OpenGl <=> Vulkan on game working.

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#12885]
### What happens?
OpenGL/Vulkan is changed during a game start.
Then blackout. (Freeze)

The change on the menu screen is no problem.

### What *should* happen?
Don't crash.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

PPSSPP Ver. : 1.9.3-760
OS: Android 9.0
DeviceName: SONY SO-02K / Xperia XZ1 Compact (Japan)
CPU: Snapdragon835 (Octa-core)
GPU: Adreno 540
Resolution: 720×1280
RAM: 4GB
ROM:32GB
ExternalStrage: microSDXC 512GB

**Comment by unknownbrackets** [comment]
I can't reproduce, but it's possible the filename or path of the game you were running might matter.  If you name the file something like "game.cso" and put it on the root of your sdcard, does this still happen?

If that makes it not happen, what's the filename and folder you have it in that makes it crash?

-[Unknown]

**Comment by nassau-tk** [comment]
@unknownbrackets 

Oops!! Bingo!!

Rename : PURSUIT FORCE ～大追跡～.iso  ----> game.iso
Change directory : SD root > ROM_PSP  ---->  Under the SD root

This issue not happen.
I can change the backend when working the games.

But,,,I wonder the issue.
I'never changing filename and directory long time.
SD root > ROM_PSP (folder name)
Every iso files are saving under the folder.
Theese filenames are including Japanese character.
And,I could change backend(OpenGL/Vulkan) when working the games.

Why I can't do it suddenly?

I think this issue happen recently.

**Comment by unknownbrackets** [comment]
Yeah, this is a bug, I'll have to test to reproduce why.  We do send the filename back now when changing backend in the settings.  I can't think of any obvious reason that'd go wrong or crash but it's the most recent change.

Good catch.

-[Unknown]

**Comment by nassau-tk** [comment]
Thank you!!
