### ISSUE TITLE
homebrew games missing game icons?

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#12887]
### What happens?

Some of homebrew games has no default icons, showing question mark icon with white background.

### What *should* happen?
should they have game icon by default?

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

android 6.0
mali-450 gpu
ppsspp v1.9.3-760 git build

### Screenshots
![_20200512_161236](https://user-images.githubusercontent.com/37603562/81658679-9296f680-946b-11ea-9cb0-959946d33eb2.JPG)
![Screenshot_20200512-160916](https://user-images.githubusercontent.com/37603562/81658726-9d518b80-946b-11ea-91d0-a7d76a780b43.png)
![Screenshot_20200512-160923](https://user-images.githubusercontent.com/37603562/81658867-bfe3a480-946b-11ea-8864-c90ee0ff93e3.png)
![Screenshot_20200512-160928](https://user-images.githubusercontent.com/37603562/81658920-cd992a00-946b-11ea-8ce2-2cd28db2aa2f.png)

**Comment by LunaMoo** [comment]
They don't have icons, so there's nothing to display, make a screenshot in-game and it will be used as icon.

**Comment by Panderner** [comment]
> They don't have icons, so there's nothing to display, make a screenshot in-game and it will be used as icon.

But how about a missing icon on a real PSP?
