### ISSUE TITLE
God of War Ghost of Sparta  - ledge bug

### ISSUE THREAD

**Issue by darkmort** [hrydgard/ppsspp#12884]
### What happens?
Ledge bug, cannot jump to the upper ledge in mounts of aroania

https://www.youtube.com/watch?v=c6I6JWgAUhc    a video with the same issue as me (the fix there doesnt work for me, my ppsspp version doesnt have that option)

### What *should* happen?
kratos should just grab the ledge and reach the statue above to push it down and break it

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Windows 10, ppsspp 1.9.3 , ati radeon hd 3000 1gb vram smy onboard gpu, cpu is an amd athlon II x2 240 processor  , and my pc has 3gb of ram  , its a desktop pc

**Comment by Gamemulatorer** [comment]
That's not a bug all you need to do is find the right place to jump.

**Comment by darkmort** [comment]
Did You Even see the vídeo ? Kratos fails to hold  when in a normal PSP he
jumps right there ti progress

**Comment by darkmort** [comment]
> That's not a bug all you need to do is find the right place to jump.

Also there  are LOTS of videos with that issue just search god of war Ghost of sparta mounts of aroania bug

**Comment by darkmort** [comment]
> That's not a bug all you need to do is find the right place to jump.

https://gamefaqs.gamespot.com/psp/995953-god-of-war-ghost-of-sparta/answers/369146-how-do-i-get-past-mounts-of-anoaria

**Comment by LunaMoo** [comment]
This game is bugged by forcing emulated psp cpu clocks which people abuse to play on bad hardware. Make sure it's set to 0(auto) then restart and reload the game from normal savedata, old savestates will forever be broken so don't use them.

**Comment by Saramagrean** [comment]
Maybe it bug form 30 FPS Fixed cheat code.

Example video.
https://youtu.be/vSLFlACtsqw

**Comment by darkmort** [comment]
> Maybe it bug form 30 FPS Fixed cheat code.
> 
> Example video.
> https://youtu.be/vSLFlACtsqw

No, i'm not using it

**Comment by darkmort** [comment]
> This game is bugged by forcing emulated psp cpu clocks which people abuse to play on bad hardware. Make sure it's set to 0(auto) then restart and reload the game from normal savedata, old savestates will forever be broken so don't use them.

It's always at default , i also used a normal save

**Comment by Gamemulatorer** [comment]
> > That's not a bug all you need to do is find the right place to jump.
> 
> Also there are LOTS of videos with that issue just search god of war Ghost of sparta mounts of aroania bug

Can you upload your savestate in that particular area of the game where the ledge bug?

**Comment by darkmort** [comment]
> > > That's not a bug all you need to do is find the right place to jump.
> > 
> > 
> > Also there are LOTS of videos with that issue just search god of war Ghost of sparta mounts of aroania bug
> 
> Can you upload your savestate in that particular area of the game where the ledge bug?

I finally solved it,, i just increased the game resolution so  the framerate was low, and that for some reason fixed it and i coulld climb the ledge, i dropped the statue and then very slowly went to save, the issue is solved finally, thanks for all the help to you and the others though
