### ISSUE TITLE
Tales of phantasia and star ocean graphics issue vulkan on Exynos

### ISSUE THREAD

**Issue by asbel123** [hrydgard/ppsspp#12890]
Look this issue on tales on phantasia i cant see background in battle on vulkan u need disable stencil test fix the issue samsung galaxy s9 and s8 exynos and i tried opengl no problem but really slow. There no issue on windows.
![20200513_141659](https://user-images.githubusercontent.com/4496487/81770996-2d9fd700-9525-11ea-93ef-5a2bcb9f42e0.jpg)issue

I give u pictures 
![20200513_141643](https://user-images.githubusercontent.com/4496487/81770958-182aad00-9525-11ea-8259-bcca3578fe51.jpg)

**Comment by Gamemulatorer** [comment]
Tales of phantasia slow issue #8538 try ppsspp latest git build from here https://buildbot.orphis.net/ppsspp/

**Comment by hrydgard** [comment]
Getting somewhat different problems (character not behind furniture, as if stencil wasn't on) but yeah, it's not working right. Seems like another driver bug, sigh.

**Comment by hrydgard** [comment]
When that build is ready, please check if it fixes your problems.

**Comment by asbel123** [comment]
I try the build already u fix star ocean first deapuatre  vulkan perfect but tales of phantasia still the same now i can see arts display in battle menu display. 
 i try on weekend on my brother phone of snapdragon 855 see the difference for tales of phantasia cross edition

**Comment by Gamemulatorer** [comment]
> I try the build already u fix star ocean first deapuatre vulkan perfect but tales of phantasia still the same now i can see arts display in battle menu display.
> i try on weekend on my brother phone of snapdragon 855 see the difference for tales of phantasia cross edition

@asbel123 still slow on OpenGL?

**Comment by asbel123** [comment]
Its fullspeed in opengl its will go slow on when cress village destroyed no problem on vulkan thats a difference plus battle swrils is faster on vulkan on samung galaxy s9

**Comment by Gamemulatorer** [comment]
> Look this issue on tales on phantasia i cant see background in battle on vulkan u need disable stencil test fix the issue samsung galaxy s9 and s8 exynos and i tried opengl no problem but really slow. There no issue on windows.
> ![20200513_141659](https://user-images.githubusercontent.com/4496487/81770996-2d9fd700-9525-11ea-93ef-5a2bcb9f42e0.jpg)issue
> 
> I give u pictures
> ![20200513_141643](https://user-images.githubusercontent.com/4496487/81770958-182aad00-9525-11ea-8259-bcca3578fe51.jpg)

This is Tales of Phantasia Full Voice Edition (Jap) right?

**Comment by asbel123** [comment]
Cross edition better version no more pause magic
Its fix the background new version on vulkan still cant see menu display text just battle menu text is fixed. 
![20200522_085112](https://user-images.githubusercontent.com/4496487/82614470-4d14bf00-9c0b-11ea-931d-5a6c40663eb1.jpg)
![Uploading 20200522_085116.jpg…]()

**Comment by unknownbrackets** [comment]
Did this used to work in v1.9.4?  Or an older version?  It'd help to figure out when it broke, if so.

-[Unknown]

**Comment by hrydgard** [comment]
Could you create a frame dump, at any scene that's missing a background? 

https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

**Comment by asbel123** [comment]
I find the build ppsspp has  disable stencil test fix the graphics on vulkan send u pitcures.


1.6.3 548

**Comment by asbel123** [comment]
![Uploading 20200529_083921.jpg…]()

**Comment by Gamemulatorer** [comment]
> I find the build ppsspp has disable stencil test fix the graphics on vulkan send u pitcures.
> 
> 1.6.3 548

@asbel123 the devs asking for a ge dump not for a picture 🤦

**Comment by hrydgard** [comment]
So there's obviously some driver bug with regards to stencil testing here. I just got an idea for a possible workaround, but which will have a small performance penalty, just committed it.

**Comment by hrydgard** [comment]
@asbel123 Can you try again with the latest build from https://buildbot.orphis.net/ppsspp/ ?

**Comment by hrydgard** [comment]
@asbel123 Could you please re-test as described in my last post above?

**Comment by hrydgard** [comment]
Gonna leave this hack in place and postpone further work to after 1.10.

**Comment by Gamemulatorer** [comment]
> I try the build already u fix star ocean first deapuatre vulkan perfect but tales of phantasia still the same now i can see arts display in battle menu display.
> i try on weekend on my brother phone of snapdragon 855 see the difference for tales of phantasia cross edition

Any update and ge dump?

**Comment by unknownbrackets** [comment]
Maybe we should remove the pixel rounding if it's not actually helping.  But maybe it is and that's why there haven't been further reports...

-[Unknown]

**Comment by XiaomiRedmi9** [comment]
@asbel123 any news?

**Comment by Gamemulatorer** [comment]
Found new issue look at the **grass**
**1X resolution**
![Screenshot_2021-10-14-10-56-52-930_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/137243409-80ef47e6-9fed-4ba2-8521-df90b521c58c.jpg)
**2X resolution**
![Screenshot_2021-10-14-10-57-01-386_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/137243437-28bbdfdd-f890-4445-85c3-28e725559665.jpg)
**software**
![Screenshot_2021-10-14-10-55-02-815_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/137243554-e24cb679-daba-433e-ab77-373cc2b98e34.jpg)
[Tales of Phantasia - Narikiri Dungeon X.zip](https://github.com/hrydgard/ppsspp/files/7342628/Tales.of.Phantasia.-.Narikiri.Dungeon.X.zip)

**Comment by Gamemulatorer** [comment]
Just noticed that this issue is cause by auto max quality.
![Screenshot_2021-12-29-15-04-14-632_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/147636036-981ee880-67ad-4faa-93a3-b7d5b45f9dde.jpg)
**X1 PSP RESOLUTION**

Increasing PSP RESOLUTION make the graphics issue disappear.
![Screenshot_2021-12-29-15-04-39-355_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/147636107-6bfe2f04-c9eb-4ad0-b0ab-51e65174af94.jpg)
**10X PSP RESOLUTION**

**Comment by unknownbrackets** [comment]
FWIW, that's Narikiri Dungeon X, which is a remake of a GBC game, and the initial screenshots in this issue were for Tales of Phantasia X, a remake of a SNES game, which is included with Narikiri Dungeon X.  There's also Tales of Phantasia Full Voice Edition, which is a predecessor of sorts to Tales of Phantasia X.  Ah, the many remakes of Tales...

Anyway, the grass issue is therefore definitely #14986.  Doesn't seem related to the initial issue of missing background graphics in battles.

-[Unknown]

**Comment by leoxxx** [comment]
Is this issue for Cross Edition?
The title is ambiguous.

**Comment by Gamemulatorer** [comment]
This might be fix using the recently build? @asbel123?

**Comment by hrydgard** [comment]
I think this one was solved by the depth/stencil workaround (writing Z in the fragment shader even though we don't really want to change it) quite a while back. I'm closing.
