### ISSUE TITLE
PPSSPP crash after press report feedback.

### ISSUE THREAD

**Issue by Saramagrean** [hrydgard/ppsspp#12897]
### What happens?
Crash after press "Report feedback" button, happen on Vulkan only.

### What *should* happen?
PPSSPP not crash after press report feedback.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
- Windows 10 x64 (CPU: i5-6200U, GPU: Intel HD Graphics 520)
- PPSSPP v1.9.3-768-g009efa5c5

**Comment by hrydgard** [comment]
I can't reproduce this, it works for me.. Hm.

**Comment by unknownbrackets** [comment]
This will attempt to take a screenshot when you go from the Pause screen to the feedback reporting screen.  Maybe `TakeGameScreenshot()` is crashing...

-[Unknown]

**Comment by hrydgard** [comment]
Got a repro on this on the Intel GPU on a laptop (Intel(R) HD Graphics 620). Hmm...

**Comment by Saramagrean** [comment]
Found another crash after switch backend from OpenGL to any backend. (PPSSPP not start automatically after change backend).

maybe it cause from driver bug, because before update graphic driver (05/05/2020 v27.20.100.8190) I can change the backend or press report feedback without problems.

**Comment by hrydgard** [comment]
Yeah, possible. It crashes in a 6 vertex vkCmdDraw, Vulkan validation layers catches nothing. If I disable screenshot-taking, it doesn't crash so it's related to that, at least.

**Comment by hrydgard** [comment]
Strangely, taking a screenshot the normal way (F12) in game seems to work.

**Comment by unknownbrackets** [comment]
The ReportScreen takes screenshots the same way as save states do, but not the same way as an in game screenshot (in game includes UI.)  But shouldn't matter.

-[Unknown]

**Comment by unknownbrackets** [comment]
I was able to reproduce.  Importantly, it requires render resolution >= 5x, Vulkan, and Intel to see the issue.

That path does a blit to resize the screenshot down.

-[Unknown]

**Comment by Saramagrean** [comment]
I see .reporting.jpg inside PSP > SCREENSHOT folder, show before PPSSPP force close. May crash after take screenshot?

In my case, It crash with any rendering resolution.

log may help.
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/4641918/ppsspplog.zip)

**Comment by unknownbrackets** [comment]
I think I must've not let the game render or something when testing at 1x, I was wrong that render resolution was a requirement.  Found the bug.

-[Unknown]

**Comment by Saramagrean** [comment]
Test with PR https://github.com/hrydgard/ppsspp/pull/12923 confirm it fixed. :)
