### ISSUE TITLE
[Feature Request] Add a numbering to each save state

### ISSUE THREAD

**Issue by MiguelCardonaG** [hrydgard/ppsspp#12896]
# What happens?
Hello.

As you can see in this screenshot I have 5 saved games from God of War: Ghost of Sparta, well I want to ask if you can put a number to every save state:

![Screenshot_20200514-174328_PPSSPP](https://user-images.githubusercontent.com/65356692/81955492-73829b00-960a-11ea-9ab4-bdf67d61fb56.jpg)

If I save my game in Slot number 1 that says "Partida guardada (1)" or "estado cargado (1)". Do you understand me what I mean? That each saved game made from the emulator has a number in parentheses.

Edit:

To make it better understood

![IMG_20200515_101502](https://user-images.githubusercontent.com/65356692/82027860-2a2b5d80-9695-11ea-94ba-0948ee24d09f.jpg)
![IMG_20200515_101357](https://user-images.githubusercontent.com/65356692/82027870-2c8db780-9695-11ea-848a-4f518f79a31b.jpg)

Best regards!

**Comment by leopard20** [comment]
He means upon loading or saving a new state, the message displayed at the top should say: "State saved/loaded (n)", not just: "State saved/loaded"

**Comment by unknownbrackets** [comment]
Oh that wouldn't be too hard, and makes sense.

-[Unknown]

**Comment by MiguelCardonaG** [comment]
> He means upon loading or saving a new state, the message displayed at the top should say: "State saved/loaded (n)", not just: "State saved/loaded"
> 
> In my opinion, this version is even better:
> "Slot n: State loaded/saved"
> Or even full sentence:
> "State loaded from/saved in slot n"

That thing I'm talking about better, and I find it more understandable than I propose, in fact mine was simpler.

**Comment by MiguelCardonaG** [comment]
Thanks you.

**Comment by MiguelCardonaG** [comment]
@hrydgard When you make a saved state, there is a small sound hold, such as an "ta, ta, ta". This happens with versions (861 and 840). With the version 812 doesn't make that sound mistake.

**Comment by MiguelCardonaG** [comment]
Edit: With version 878 it no longer makes that sound error when saving.

**Comment by hrydgard** [comment]
@MiguelCardonaG Yeah, I figured out my mistake and fixed it.
