### ISSUE TITLE
[Android] [Mali GPU] [OpenGL] Lastest build blackscreen on buffered rendering mode

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#12898]
### What happens?
As the title say, last working build https://github.com/hrydgard/ppsspp/commit/d4b695cb78d25730fc1f5f8ed8e14ad645f74f2b

Issue started https://github.com/hrydgard/ppsspp/commit/864d138cd95f932b91ec7a7bc738f1eaca627667

### What *should* happen?
No blackscreen on buffered rendering mode

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Android 6.0.1
OpenGL 2.0
Mali-450

**Comment by Gamemulatorer** [comment]
@unknownbrackets here's the ge dump
[PPSSPP GE Dump.zip](https://github.com/hrydgard/ppsspp/files/4631624/PPSSPP.GE.Dump.zip)
tried to different games

**Comment by unknownbrackets** [comment]
It's working fine on Adreno.  Are you using a post-processing shader?

-[Unknown]

**Comment by Gamemulatorer** [comment]
> It's working fine on Adreno. Are you using a post-processing shader?
> 
> -[Unknown]

No, default settings only.

**Comment by Gamemulatorer** [comment]
My ScreenRecording game works fine in skip-buffered rendering.
Game audio also still playing while in blackscreen but not captured during screenrecording (I forget to enable 😅)
[recording_20200515_094046.zip](https://github.com/hrydgard/ppsspp/files/4631844/recording_20200515_094046.zip)

**Comment by Gamemulatorer** [comment]
Tried ppsspp-v1.9.3-806-g192198ef3-android still blackscreen :(

**Comment by Panderner** [comment]
I'm using Realme C2 Android 9 Pie and my games runs fine on buffered rendering.

**Comment by Panderner** [comment]
@Gamemulatorer what games are you using?

**Comment by Gamemulatorer** [comment]
> @Gamemulatorer what games are you using?

All of my games are blackscreen on buffered rendering but not on skip-buffered rendering see my screenrecording above comment.

I think this issue can only reproduce on old android devices with old gpu like Mali 400 & 450 on OpenGL 2.0?

**Comment by Gamemulatorer** [comment]
Confirmed! issue can only reproduce on Mali GPU with OpenGL 2.0, I tested the latest git build on Mali-t720 GPU with OpenGL 3.1 and it's work fine on it.

**Comment by hrydgard** [comment]
Wacky. I'll try to use my Galaxy S3 to debug this later.

**Comment by hrydgard** [comment]
Just did a quick check to confirm the repro and yeah, I got it. Getting a lot of the following:

W/PPSSPP  ( 6672): [G3D] Got an error after init: 00000500 (GL_INVALID_ENUM)

So it should be fairly easy to track down when I have more time later. Looks like we're accidentally now using some feature that's too new on GLES 2.0 devices.

**Comment by hrydgard** [comment]
The error happens when doing indexed draws with index type = GL_UNSIGNED_INT. This is not supported on older GLES devices, only GL_UNSIGNED_SHORT. Should be a pretty easy fix.

**Comment by hrydgard** [comment]
Was gonna make the index format a parameter of the draw call, but in D3D9 the index format is specified when creating the index buffer! Ugh.

I think I'll just only support 16-bit indices in thin3d.

**Comment by unknownbrackets** [comment]
I think it makes sense to specify it on create for all backends, but yeah, 16-bit only sounds simpler...

I guess that means softgpu was broken before on GLES2...

-[Unknown]

**Comment by hrydgard** [comment]
So it seems indeed.

**Comment by Gamemulatorer** [comment]
@hrydgard thanks! for the quick fixed.
Vampire Chronicles also works now unlike in the previous build started on ForceSoftwareRenderer implementation for this game that always stuck on blackscreen.
![Screenshot_20200516-054612](https://user-images.githubusercontent.com/37603562/82100837-6adeb180-973d-11ea-8995-06f246a18a2a.png)

**Comment by unknownbrackets** [comment]
That makes sense, the problem that caused the blackscreen was exactly how the software renderer was working before.  Now that they're using shared code, the fix affected both.

-[Unknown]
