### ISSUE TITLE
v1.9.3-805-g864d138cd Breaks FMV Videos

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#12899]
in v1.9.3-770-gd4b695cb7 and older the intro video displays properly but v1.9.3-805-g864d138cd is now broken.

ppsspp-v1.9.3-805-g864d138cd:
![Screenshot_2020-05-15-09-02-55-77_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/82001833-b25a3480-968e-11ea-8f02-b937056f8e63.png)

ppsspp-v1.9.3-770-gd4b695cb7 and older:
![Screenshot_2020-05-15-09-26-57-16_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/82001883-d453b700-968e-11ea-9859-ca95681d4181.png)

**Comment by Panderner** [comment]
Games affected:
Coded Arms
Persona 3 Portable
The Simpsons Game

**Comment by unknownbrackets** [comment]
Oops, fixed in 192198ef.

-[Unknown]
