### ISSUE TITLE
Little graphic bug

### ISSUE THREAD

**Issue by faroukabd000** [hrydgard/ppsspp#12904]
![received_241944257039137](https://user-images.githubusercontent.com/64847752/82086590-a0a47b80-96e6-11ea-87e2-609f9ac52529.jpeg)
 
V 1.9.0
Some times the black things cover half screen..

**Comment by LunaMoo** [comment]
This is a known issue which happens by disabling effects required to display those graphics.

Make sure you enable "simulate block transfer", or even restore default settings and if you choose to play without specific effects(ie for having slow hardware), then accept the side effect of not drawing them means not displaying them. Closing.

**Comment by Gamemulatorer** [comment]
@faroukabd000 try my settings here https://github.com/hrydgard/ppsspp/issues/12544#issuecomment-601003524
