### ISSUE TITLE
App crashing when loading intro of Brave Story New Traveler [ULUS10279] using Vulkan Backend

### ISSUE THREAD

**Issue by justafella** [hrydgard/ppsspp#12927]
### What happens?
When running the game using the Vulkan backend, it crashes just before the intro plays. The app then suggests to use Direct3D, which works fine, but performs worse than Vulkan on my setup.

### What *should* happen?
Should run normally, but since the build >ppsspp-v1.9.3-760-gf23dd7635-windows-amd64< (from 2020-05-11 at 00:18:59) it doesn't.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Windows 10 Home Single Language 64 bits on a Acer Aspire ES-1-533 with an Intel Celeron QuadCore N3450 (Intel HD Graphics 500) and 4 GB RAM. The PPSSPP version that crashes is v1.9.3-760-gf23dd7635 and the crash goes on until the latest build.

![ssbugrep](https://user-images.githubusercontent.com/65559598/82240865-2738a300-9909-11ea-8d42-4752e621cca9.png)

**Comment by hrydgard** [comment]
Did it start exactly on that build? In that case it's https://github.com/hrydgard/ppsspp/pull/12882 . Hm....

**Comment by justafella** [comment]
> 
> 
> Did it start exactly on that build? In that case it's #12882 . Hm....

Yes. I've been downloading these builds in a daily basis and having this issue since that one specific version. I made sure to download and try again at least the 8 previous available versions before that one and everything went fine.

**Comment by hrydgard** [comment]
Alright, thanks. Just a bit surprised, that merge looks very innocent...

**Comment by hrydgard** [comment]
Actually I have an idea, it could be similar to that other Intel crash we had recently...

**Comment by hrydgard** [comment]
@justafella If that one doesn't help, have you looked into upgrading the drivers for your Intel GPU, is that a possibility on your machine?

**Comment by justafella** [comment]
Ok I will try it and be back in a moment. About my drivers, they're up to date. I also thought they could be to blame.

**Comment by justafella** [comment]
> 
> 
> @justafella If that one doesn't help, have you looked into upgrading the drivers for your Intel GPU, is that a possibility on your machine?

Got the same issue with the new build

**Comment by hrydgard** [comment]
Thanks. It just makes zero sense to me how that build started crashing for you. Not seeing that at all on any computer I have.

It's really, really critical for us to understand exactly which build was the first bad one, so it's not that I don't believe you, but you are really sure that it worked on v1.9.3-754-g6edf4ddc5 ?

Been looking at GPU traces in Renderdoc and not finding anything suspicious...

**Comment by unknownbrackets** [comment]
Your screenshot says "State loaded".  Is there a save state involved here?

Or just to confirm, if you start fresh, it crashes in the intro?

If there's a specific scene it crashes during, the save state might help.

-[Unknown]

**Comment by justafella** [comment]
> 
> 
> Your screenshot says "State loaded". Is there a save state involved here?
> 
> Or just to confirm, if you start fresh, it crashes in the intro?
> 
> If there's a specific scene it crashes during, the save state might help.
> 
> -[Unknown]

I used a save state to test quickly through different versions. The crashes occur (and don't, on the working version) both with regular start and state loaded.

**Comment by hrydgard** [comment]
crashes "just before the intro plays"?  Which intro, the one at bootup or when starting the game? Can you be very very specific about when the crash happens?

I did an experimental commit reverting the only part of #12882 that can possibly have anything to do with this. A fresh build should be up in a while, please try that so we get more confirmation that it has something to do with render pass merging.

**Comment by justafella** [comment]
> 
> 
> Thanks. It just makes zero sense to me how that build started crashing for you. Not seeing that at all on any computer I have.
> 
> It's really, really critical for us to understand exactly which build was the first bad one, so it's not that I don't believe you, but you are really sure that it worked on v1.9.3-754-g6edf4ddc5 ?
> 
> Been looking at GPU traces in Renderdoc and not finding anything suspicious... (the game is a little inefficient in how it uses copies and renderpasses to perform what we call shader blending, but should be no big deal on a desktop).

Yes, I am sure. I'll attach more sreenshots and I'll try to upload a screen record later.
![ss1](https://user-images.githubusercontent.com/65559598/82266447-b8267300-9937-11ea-9745-bdde70dff89a.png)
![ss2](https://user-images.githubusercontent.com/65559598/82266449-ba88cd00-9937-11ea-8b49-8adfc32ab956.png)
![ss3](https://user-images.githubusercontent.com/65559598/82266454-bc529080-9937-11ea-936d-7525aef22a14.png)
![ss4](https://user-images.githubusercontent.com/65559598/82266462-bfe61780-9937-11ea-8a95-3fa56101cd42.png)
![ss5](https://user-images.githubusercontent.com/65559598/82266467-c2e10800-9937-11ea-987b-8d6677d25748.png)

**Comment by justafella** [comment]
> 
> 
> crashes "just before the intro plays"? Which intro, the one at bootup or when starting the game? Can you be very very specific about when the crash happens?
> 
> I did an experimental commit reverting the only part of #12882 that can possibly have anything to do with this. A fresh build should be up in a while, please try that so we get more confirmation that it has something to do with render pass merging.

The one at boot up, right after the Game Republic logo.

**Comment by hrydgard** [comment]
Alright, that's specific enough, no need for a recording..

**Comment by unknownbrackets** [comment]
Can you screenshot the "Features" section of system information under Settings -> Tools?

Wondering if it's down to logic op support or something else.  Sorry for all the confirmations - this is probably a driver bug, working around those is tricky.

-[Unknown]

**Comment by justafella** [comment]
> 
> 
> Can you screenshot the "Features" section of system information under Settings -> Tools?
> 
> Wondering if it's down to logic op support or something else. Sorry for all the confirmations - this is probably a driver bug, working around those is tricky.
> 
> -[Unknown]

Okay, whatever I can do to help.
![features 1](https://user-images.githubusercontent.com/65559598/82267798-6253ca00-993b-11ea-9ec5-4eaf83f6ebe5.png)
![features 2](https://user-images.githubusercontent.com/65559598/82267800-64b62400-993b-11ea-9b40-d0ad52ce089d.png)

**Comment by justafella** [comment]
I just noticed my Vulkan API version is 1.0.50 and this is probably a very important bit of information.
![ssapiv](https://user-images.githubusercontent.com/65559598/82268335-c1fea500-993c-11ea-8b29-d71cd4158bba.png)

**Comment by justafella** [comment]
> 
> 
> crashes "just before the intro plays"? Which intro, the one at bootup or when starting the game? Can you be very very specific about when the crash happens?
> 
> I did an experimental commit reverting the only part of #12882 that can possibly have anything to do with this. A fresh build should be up in a while, please try that so we get more confirmation that it has something to do with render pass merging.

This version worked fine.
![worked](https://user-images.githubusercontent.com/65559598/82269419-a2b54700-993f-11ea-98b1-fbec2ffe6857.png)

**Comment by Saramagrean** [comment]
Have you tried to update graphic drivers via the Intel website? (install Intel® Driver & Support Assistant)
https://www.intel.com/content/www/us/en/support/intel-driver-support-assistant.html

I use Intel HD Graphic 520 (I think it's the same as gen with 500) is support Vulkan driver v1.2.135.

**Comment by unknownbrackets** [comment]
Here are the steps that would (incorrectly) merge there.  There's three merges total right after the Game Republic logo.

All three are clearly stencil uploads (three different buffers).  We don't need to clear at all in that case.

```
Would have merged steps 1 (4 c) and 2 (34 c)
=== Dest step:
RenderPass Begin(739d4810, CLEAR, CLEAR, CLEAR)
  Viewport(0.000000, 0.000000, 1536.000000, 1632.000000, 0.000000, 1.000000)
  Scissor(0, 0, 1536, 1632)
  BindPipeline(73d0e040)
  Draw(4)
RenderPass End(739d4810)
=== Source step:
RenderPass Begin(739d4810, KEEP, KEEP, CLEAR)
  BindPipeline(73ceb540)
  Viewport(0.000000, 0.000000, 1536.000000, 1632.000000, 0.000000, 1.000000)
  Scissor(0, 0, 1536, 1632)
  PushConstants(4)
  Stencil(ref=0, compare=255, write=255)
  Draw(3)
  Stencil(ref=255, compare=255, write=1)
  PushConstants(4)
  Draw(3)
  Stencil(ref=255, compare=255, write=2)
  PushConstants(4)
  Draw(3)
  Stencil(ref=255, compare=255, write=4)
  PushConstants(4)
  Draw(3)
  Stencil(ref=255, compare=255, write=8)
  PushConstants(4)
  Draw(3)
  Stencil(ref=255, compare=255, write=16)
  PushConstants(4)
  Draw(3)
  Stencil(ref=255, compare=255, write=32)
  PushConstants(4)
  Draw(3)
  Stencil(ref=255, compare=255, write=64)
  PushConstants(4)
  Draw(3)
  Stencil(ref=255, compare=255, write=128)
  PushConstants(4)
  Draw(3)
  BindPipeline(73d139a0)
  Scissor(0, 0, 2880, 1632)
  Viewport(0.000000, 0.000000, 1536.000000, 1632.000000, 0.000000, 1.000000)
  DrawIndexed(6)
RenderPass End(739d4810)
===

Would have merged steps 3 (4 c) and 4 (10 c)
=== Dest step:
RenderPass Begin(739d4a50, CLEAR, CLEAR, CLEAR)
  Viewport(0.000000, 0.000000, 1536.000000, 1632.000000, 0.000000, 1.000000)
  Scissor(0, 0, 1536, 1632)
  BindPipeline(73d0e040)
  Draw(4)
RenderPass End(739d4a50)
=== Source step:
RenderPass Begin(739d4a50, KEEP, KEEP, CLEAR)
  BindPipeline(73ceb540)
  Viewport(0.000000, 0.000000, 1536.000000, 1632.000000, 0.000000, 1.000000)
  Scissor(0, 0, 1536, 1632)
  PushConstants(4)
  Stencil(ref=0, compare=255, write=255)
  Draw(3)
  BindPipeline(73d141c0)
  Scissor(0, 0, 2880, 1632)
  Viewport(0.000000, 0.000000, 1536.000000, 1632.000000, 0.000000, 1.000000)
  DrawIndexed(24)
RenderPass End(739d4a50)
===

Would have merged steps 42 (4 c) and 43 (38 c)
=== Dest step:
RenderPass Begin(739d4930, CLEAR, CLEAR, CLEAR)
  Viewport(0.000000, 0.000000, 768.000000, 1632.000000, 0.000000, 1.000000)
  Scissor(0, 0, 768, 1632)
  BindPipeline(73d0e040)
  Draw(4)
RenderPass End(739d4930)
=== Source step:
RenderPass Begin(739d4930, KEEP, KEEP, CLEAR)
  BindPipeline(73ceb540)
  Viewport(0.000000, 0.000000, 768.000000, 1632.000000, 0.000000, 1.000000)
  Scissor(0, 0, 768, 1632)
  PushConstants(4)
  Stencil(ref=0, compare=255, write=255)
  Draw(3)
  Stencil(ref=255, compare=255, write=1)
  PushConstants(4)
  Draw(3)
  Stencil(ref=255, compare=255, write=2)
  PushConstants(4)
  Draw(3)
  Stencil(ref=255, compare=255, write=4)
  PushConstants(4)
  Draw(3)
  Stencil(ref=255, compare=255, write=8)
  PushConstants(4)
  Draw(3)
  Stencil(ref=255, compare=255, write=16)
  PushConstants(4)
  Draw(3)
  Stencil(ref=255, compare=255, write=32)
  PushConstants(4)
  Draw(3)
  Stencil(ref=255, compare=255, write=64)
  PushConstants(4)
  Draw(3)
  Stencil(ref=255, compare=255, write=128)
  PushConstants(4)
  Draw(3)
  BindPipeline(73d141c0)
  Scissor(0, 0, 2880, 1632)
  Viewport(0.000000, 0.000000, 768.000000, 1632.000000, 0.000000, 1.000000)
  DrawIndexed(6)
  BindPipeline(73d11d30)
  Scissor(0, 0, 720, 408)
  Viewport(0.000000, 0.000000, 768.000000, 1632.000000, 0.000000, 1.000000)
  DrawIndexed(432)
RenderPass End(739d4930)
===
```

-[Unknown]

**Comment by justafella** [comment]
> 
> 
> Have you tried to update graphic drivers via the Intel website? (install Intel® Driver & Support Assistant)
> https://www.intel.com/content/www/us/en/support/intel-driver-support-assistant.html
> 
> I use Intel HD Graphic 520 (I think it's the same as gen with 500) is support Vulkan driver v1.2.135.

I tried but I can't. It is said that I should use the manufacturer version of the driver. I also tried to manually download and install the generic version available at Intel's page but to no avail as I get a message that basically says the driver is not for my computer.

**Comment by hrydgard** [comment]
Intel is starting to allow general driver installs in the next Windows update, at least for the last few generations, so there might be that to look forward too.. Dunno about gen 5xx though.

Anyway, merged unknownbracket's latest changes, hopefully this will be ok now...

**Comment by hrydgard** [comment]
@justafella  Just curious about one more thing. In the Vulkan extensions list in system information, can you check if your device support VK_EXT_shader_stencil_export?

**Comment by justafella** [comment]
> 
> 
> @justafella Just curious about one more thing. In the Vulkan extensions list in system information, can you check if your device support VK_EXT_shader_stencil_export?

I don't think so. This is all that's on the list.

> 
> 
> > Can you screenshot the "Features" section of system information under Settings -> Tools?
> > Wondering if it's down to logic op support or something else. Sorry for all the confirmations - this is probably a driver bug, working around those is tricky.
> > -[Unknown]
> 
> Okay, whatever I can do to help.
> ![features 1](https://user-images.githubusercontent.com/65559598/82267798-6253ca00-993b-11ea-9ec5-4eaf83f6ebe5.png)
> ![features 2](https://user-images.githubusercontent.com/65559598/82267800-64b62400-993b-11ea-9b40-d0ad52ce089d.png)

**Comment by hrydgard** [comment]
Okay, that's a surprisingly short list of extensions, but fine. 

Anyway, I assume the latest buildbot build is working for you? If so, we can close this for now, although it's still a little odd that this change got the driver to crash.

**Comment by justafella** [comment]
> Okay, that's a surprisingly short list of extensions, but fine.
> Anyway, I assume the latest buildbot build is working for you? If so, we can close this for now, although it's still a little odd that this change got the driver to crash.



> Have you tried to update graphic drivers via the Intel website? (install Intel® Driver & Support Assistant)
> https://www.intel.com/content/www/us/en/support/intel-driver-support-assistant.html
> I use Intel HD Graphic 520 (I think it's the same as gen with 500) is support Vulkan driver v1.2.135.

I just managed to update my graphic driver and the list got way bigger (and now it has VK_EXT_shader_stencil_export). Also my API version went from 1.0.50 to 1.2.135.

![ss1](https://user-images.githubusercontent.com/65559598/82325376-28b9a800-99a9-11ea-9a12-18387686580b.png)
![ss2](https://user-images.githubusercontent.com/65559598/82325386-2b1c0200-99a9-11ea-9fbc-ed826ce20b40.png)
![ss3](https://user-images.githubusercontent.com/65559598/82325391-2ce5c580-99a9-11ea-9316-f6a9a287e228.png)
![ss4](https://user-images.githubusercontent.com/65559598/82325395-2e16f280-99a9-11ea-9215-0266c7214d29.png)
![ss5](https://user-images.githubusercontent.com/65559598/82325398-2fe0b600-99a9-11ea-86e0-8d0a3a6aadc8.png)
![ss6](https://user-images.githubusercontent.com/65559598/82325508-5acb0a00-99a9-11ea-9d69-73806b23e006.png)

**Comment by hrydgard** [comment]
Cool, that's good. I might switch to using that extension if available to do the stencil updates, should boost performance a little, though I don't know if that's a concern for you.

Anyway, please confirm whether the latest buildbot build works or not, so I can close it. Would be interesting to know if those "bad" builds now work on your new driver, too :)

**Comment by justafella** [comment]
> Cool, that's good. I might switch to using that extension if available to do the stencil updates, should boost performance a little, though I don't know if that's a concern for you.
> Anyway, please confirm whether the latest buildbot build works or not, so I can close this issue. Would be interesting to know if those "bad" builds now work on your new driver, too :)

Just tested the latest buildbot and **_it's working fine._** Also I see no problem in reporting if anything goes wrong. It's my pleasure to be of any help. I'll test v1.9.3-760-gf23dd7635 again (the one Ihad issue first) and then some vesions later than that. I'll be back in minutes to feedback.

**Comment by justafella** [comment]
Alright. Just tested the "bad one" and the later 5. They worked fine BUT they had a quick sound cracking at the very beginning of the intro (as I always had and thought it was just my bad computer). The latest build has no sound cracking AT ALL as it runs smoothly through the intro. So I do guess it was a mix of driver and emulator issues. Now everything is just fine and I think it's case closed.

**Comment by hrydgard** [comment]
Great, thanks for confirming, and thank you for all your testing! This was very helpful. I'll close but you'll still be able to report any testing results below.
