### ISSUE TITLE
Tekken 6 and other 3D games performance decrease since #12922 on GL2.0 device

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#12925]
### What happens?
The game Tekken 6 performance decrease since ppsspp v1.9.3-882.It drops to 5fps on my android device w/ OpenGL 2.0 Mali-450 GPU but in ppsspp buildbot v1.9.3-812 the game is running smooth.

### Screenrecording
Game is running good.
[recording_ppsspp_v1.9.3-812.zip](https://github.com/hrydgard/ppsspp/files/4644169/recording_ppsspp_v1.9.3-812.zip)
Game decrease the performance.
[recording_ppsspp_v1.9.3-882.zip](https://github.com/hrydgard/ppsspp/files/4644173/recording_ppsspp_v1.9.3-882.zip)

**Comment by hrydgard** [comment]
Did you build -882 yourself? As I'm writing this, it's not yet up on https://buildbot.orphis.net/ppsspp/ .

**Comment by Gamemulatorer** [comment]
![Screenshot_20200518-210515](https://user-images.githubusercontent.com/37603562/82216276-5112b980-994b-11ea-90bf-e61e527c8503.png)
I just click see full list

**Comment by Panderner** [comment]
@Gamemulatorer can you restore to default settings?

**Comment by hrydgard** [comment]
What about -878? Could you try some in between?

**Comment by Panderner** [comment]
@Gamemulatorer can you lower the internal resolution to 1x?

**Comment by unknownbrackets** [comment]
There's also d88099e in that range.  Does vertex cache on/off influence the difference?

-[Unknown]

**Comment by Gamemulatorer** [comment]
Issue started https://github.com/hrydgard/ppsspp/commit/e29d79a5ae514ccbc4c1b0bf0e104c46d1ae98be

**Comment by unknownbrackets** [comment]
Hm, nothing there should have changed on a device without GLES3 and without Vulkan.  Invalidate isn't called anywhere.  At most it's tracking the tinyset of dependencies, but it's definitely a huge concern if just tracking that is somehow causing a huge slowdown...

Does disabling block transfer affect performance?

-[Unknown]

**Comment by Gamemulatorer** [comment]
> There's also [d88099e](https://github.com/hrydgard/ppsspp/commit/d88099e701ce54b9c21726a10bd8ae73b42f77bb) in that range. Does vertex cache on/off influence the difference?
> 
> -[Unknown]

Vertex off slightly improve the fps of the game but very minor only, here's the ge dump.
[vertex on.zip](https://github.com/hrydgard/ppsspp/files/4645603/vertex.on.zip)
[vertex off.zip](https://github.com/hrydgard/ppsspp/files/4645604/vertex.off.zip)

**Comment by unknownbrackets** [comment]
Hm okay.  GE dumps capture the drawing the game does, so they should not depend on settings (although cpu speed hacks etc. could change them.)  Vertex cache and block transfer won't change dumps.

Dropping to 5 FPS is significant.  It seems like it must be something with the creation or binding of framebuffers...

-[Unknown]

**Comment by hrydgard** [comment]
Asking again, are you downloading builds or building your own? If the latter, make really sure you're building Optimized and not Debug builds. I can't see what caused a drop like this.

**Comment by hrydgard** [comment]
I'm getting very acceptable performance in Tekken 6 (relatively) on my Galaxy S3 with Mali-400MP on a fresh build. Really not seeing any drop in performance between before e29d79a and master.

**Comment by Gamemulatorer** [comment]
@hrydgard sorry for the bothering.
I forgot that I recently deleted my ppsspp system folder that include compat.ini that I disable MoreAccurateVMMUL for Tekken6 that improve performance for my phone.
