### ISSUE TITLE
Immersive mode not re-fullscreen. [Android]

### ISSUE THREAD

**Issue by Saramagrean** [hrydgard/ppsspp#12926]
### What happens?
Immersive mode not auto re-fullscreen, after close other app overlay (like Facebook Messager). happen on both OpenGL and Vulkan.

![20200519_201106](https://user-images.githubusercontent.com/26355472/82330382-f80b5a00-9a0c-11ea-8556-c3921725315b.gif)

### What *should* happen?
Immersive mode should auto re-fullscreen after close other app overlay.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Huwaei P9+ (Android 9.0, Kirin 955, Mali T-880) / PPSSPP v1.9.3-882-g6593ff9ff.

Example video.
https://youtu.be/svX-2KxR_t4

**Comment by unknownbrackets** [comment]
Does this still happen with v1.11.x and higher?

-[Unknown]

**Comment by Saramagrean** [comment]
It fixed. :)

**Comment by unknownbrackets** [comment]
Thanks for validating.

-[Unknown]
