### ISSUE TITLE
WASAPI stability issues?

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#12929]
Got some scary reporting on Discord:

```
 Otoma: I did some more testing to help you guys find out the problem. Sadly, the testing results are absolutely not consistent. 

Turns out my exclusive mode find might not be the solution after all. Sometimes it took 2 tries for the settings to take effect? That why I thought exclusive Mode is the solution.

I tried to start the .exe probably about 1000 times now with different settings. 

What I found out was
Using Direct3D 11 and WASAPI works about 2% of the time when using 48000 Hz and exclusive Mode on and about 90% when using 44100 Hz and exclusive Mode on
Using Vulkan and WASAPI gave me slightly better results using 48000 Hz AND 44100 Hz, but might be some random testing tolerance

However using DirectSound as Sound Engine worked pretty much 100% of the time (tried it multiple times with Vulkan, OpenGL and Direct3D 11). Also it seems that it doesn't matter anymore if I use 44100 Hz / 48000 Hz / exclusive mode on/off

Sorry for the confusion.

```

Definitely sounds like some timing related instability with WASAPI...

**Comment by LunaMoo** [comment]
WASAPI and XAudio2 which uses WASAPI was historically problematic to systems with poor audio drivers not just with PPSSPP, but pretty much anything using it, so this stability problem might as well be a driver issue.

 Worth mentioning "latest driver" is not always the one with best compatibility. I recall in my old system, one of the oldest drivers was only one where this wasn't causing crashes in some other emulator.

**Comment by unknownbrackets** [comment]
I suspect it's some recent driver update or commonly used program.  This is in other words #12845, as far as I understand.  Actually has (probably) nothing to do with NVIDIA.

-[Unknown]

**Comment by hrydgard** [comment]
Duplicate of #12845
