### ISSUE TITLE
Toca Race Driver 2 No image only audio (version 708 if it works)

### ISSUE THREAD

**Issue by MiguelCardonaG** [hrydgard/ppsspp#12936]
Hello! 

In the versions ppsspp-v1.9.3-812, 840, 861, 878, 882, 895 and 900 no image, you only hear sound. In the version ppsspp-v1.9.3-708-g259ae2862-android.apk works properly.

**Comment by hrydgard** [comment]
What device are you running on? Vulkan or OpenGL?

**Comment by unknownbrackets** [comment]
And just to make sure, does v1.9.3-764-g857168634 work?  You mention it works in 708, but it helps a lot to know the most recent version that works, and the first version that broke.

For example, if v1.9.3-809-ga63706925 works but v1.9.3-812-g6798d4887 doesn't, that tells us a lot.

-[Unknown]

**Comment by MiguelCardonaG** [comment]
> What device are you running on? Vulkan or OpenGL?

Samsung Galaxy Note 8 SM-N950F.
Android 9.

None of them work. :(

**Comment by MiguelCardonaG** [comment]
> And just to make sure, does v1.9.3-764-g857168634 work? You mention it works in 708, but it helps a lot to know the most recent version that works, and the first version that broke.
> 
> For example, if v1.9.3-809-ga63706925 works but v1.9.3-812-g6798d4887 doesn't, that tells us a lot.
> 
> -[Unknown]

The version 738 It works well.

**Comment by MiguelCardonaG** [comment]
The version ppsspp-v1.9.3-770-gd4b695cb7-android.apk It works well.
The version ppsspp-v1.9.3-805-g864d138cd-android.apk It works well.

**Comment by hrydgard** [comment]
Thanks! This is almost certainly https://github.com/hrydgard/ppsspp/commit/54ffe9b235497a21f89c26a455298de363032a1a then.

**Comment by hrydgard** [comment]
I think maybe that check should only be done in newer versions of the firmware as the stack parameters are already only checked in that function if sceKernelGetCompiledSdkVersion() > 0x01FFFFFF ..

**Comment by hrydgard** [comment]
Potential fix merged.

**Comment by MiguelCardonaG** [comment]
With the version ppsspp-v1.9.3-906-ge8b737226-android.apk it's already working well. 😀

**Comment by sum2012** [comment]
Thanks report before v1.10
