### ISSUE TITLE
Star Wars: The Clone Wars - Graphic glitch [Android/Windows]

### ISSUE THREAD

**Issue by Saramagrean** [hrydgard/ppsspp#12949]
### What happens?
Graphic glitch (pink overlay) in-game happen in all backends.

![SW-TCW-1](https://user-images.githubusercontent.com/26355472/82667454-1b7b1280-9c62-11ea-85f9-774722b2384d.png)

Try all versions (0.3-1.9.3 latest git build) encounter all the same problems. 

### What *should* happen?
No graphic glitch.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
- Windows 10 (64 bit, CPU: Intel i5 6200U, GPU: Intel HD 520)
- Huwei P9+ (Android 9.0, Kirin 955, Mali T-880)
- PPSSPP v1.9.3-922-gc861bc0d7 with default settings.

GE Dump: [DUMP.zip](https://github.com/hrydgard/ppsspp/files/4668089/DUMP.zip)

**Comment by Panderner** [comment]
![Screenshot_2020-05-22-23-40-20-66_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/82684810-c9e47f00-9c85-11ea-93e8-f42e167e4b82.png)
it's works fine for me, I'm using Realme C2 Android 9 Pie and v1.9.3-913-g1dec77214

**Comment by Gamemulatorer** [comment]
I can repro this issue on my phone.
![Screenshot_20200525-140240](https://user-images.githubusercontent.com/37603562/82783216-a17ca080-9e90-11ea-8054-f7ba5551b976.png)
![Screenshot_20200525-140308](https://user-images.githubusercontent.com/37603562/82783228-a5a8be00-9e90-11ea-9cc9-672ef78680fc.png)

**Comment by unknownbrackets** [comment]
Hm, Mali and Intel, but not PowerVR?

There's a screenshot - US version - that looks fine here on Mali-450:
https://report.ppsspp.org/game/ULUS10477_1.00

But there are bad looking screenshots here for one of the EUR version:
https://report.ppsspp.org/game/ULES01284_1.00

Is this an issue that only happens on the European release?  I wonder if it's attempting some depth buffering...

-[Unknown]

**Comment by Panderner** [comment]
USA Version:
![Screenshot_2020-05-25-19-14-05-07_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/82808199-144f4100-9ebc-11ea-9981-46e1d96258d2.png)

Europe Version:
![Screenshot_2020-05-25-19-14-51-64_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/82808214-1e713f80-9ebc-11ea-8881-73ca744666f4.png)

USA Version is ok. This bug is only happens in the Europe version of the game

**Comment by Panderner** [comment]
but it doesn't occur in software renderer.
Here's a Screenshot I'm using software renderer in the Europe version of this game:
![Screenshot_2020-05-25-19-25-53-76_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/82809040-ca675a80-9ebd-11ea-8eee-5e0db45a8343.png)

**Comment by unknownbrackets** [comment]
In the dump, everything is fine at first.  Originally, it draws to 0x04000000 with depth at 0x04110000.

At 11495/11702, it draws to a temp buffer at 0x00154000, a simple stretch.  But then it draws with blend fixed ZERO + fixed ZERO and stencil REPLACE FF over that.  So, forget that earlier draw.

At 11527/11702, unsatisfied with the earlier waste of time, it stretches again.  But this time it uses an alpha test to make sure it will not draw anything and this will also be a waste of time.  But maybe in other scenes, stencil is used and would result in some more interesting effect.

After doing some things that would probably result in bloom for the above, at 11598/11702 it textures from 0x0418c200.  This is where things go wrong.

Actually, 0x0418c200 should be within that 0x04154000 buffer it's been working so hard to keep blank.  Specifically, it's at an offset of (128, 224).  It later uses 0x04184200 which has the same problem (offset of (128, 192)...)

We assume it's a mistake when it tries to access 224/272 of a buffer directly, with an X offset.  Maybe we need to be smarter about that being drawn to immediately prior.

-[Unknown]

**Comment by hrydgard** [comment]
Nice breakdown Unknown, I'm tagging it fro v1.11. 

I have some ideas in the back of my mind about a complete rework of GPU memory management, but it might be a pipe dream...

**Comment by unknownbrackets** [comment]
Yeah, it's complex.  I think we could potentially rely on the safeWidth and safeHeight to safely texture from this late in a buffer.

-[Unknown]

**Comment by Gamemulatorer** [comment]
Testing on PPSSPP v1.11.3
### OpenGL
![Screenshot_2021-05-23-11-24-11-167_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/119247090-8b93df80-bbb9-11eb-8fbb-a5bbfc26e018.jpg)
### Vulkan
![Screenshot_2021-05-23-11-24-27-603_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/119247097-a36b6380-bbb9-11eb-97e9-03629e36e185.jpg)

**Comment by Panderner** [comment]
Same happens for my PC for all backends:
<img width="960" alt="2021-05-23 (7)" src="https://user-images.githubusercontent.com/37503397/119259818-9f176880-bc02-11eb-8866-b51a2d3e1047.png">
<img width="960" alt="2021-05-23 (6)" src="https://user-images.githubusercontent.com/37503397/119259825-a3438600-bc02-11eb-847b-5df53d67abe6.png">

I recommend you to use USA version of this game but not the Europe Version.

**Comment by Panderner** [comment]
This issue is also related for USA Version of MotorStorm: Arctic Edge (#7552)

**Comment by Gamemulatorer** [comment]
I found a solution for this graphic glitch together with Star Wars: The Force Unleashed https://github.com/hrydgard/ppsspp/issues/9572

Add Star Wars: The Clone Wars and Star Wars: The Force Unleashed to Force04154000Download compat.ini fix graphics issue of those two game, but the performance penalty is huge :(

**Comment by Panderner** [comment]
Please Note: German and Italian Version (ULES01285) does not reproduce this issue:
![Screenshot_2021-10-06-09-10-44-629_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/136125127-6dd916d6-fa96-45d6-8cdc-2f9ae7a226c3.jpg)

**Comment by Gamemulatorer** [comment]
> Please Note: German and Italian Version (ULES01285) does not reproduce this issue: ![Screenshot_2021-10-06-09-10-44-629_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/136125127-6dd916d6-fa96-45d6-8cdc-2f9ae7a226c3.jpg)

Yes I know that Europe can only reproduce this, but I find a way to fix the graphics glitch but the perf penalty is huge. Hrydgard need to improve the Vram

**Comment by Panderner** [comment]
> Europe can only reproduce this

ULES01284 can reproduce this but ULES1285 doesn't.

**Comment by Saramagrean** [comment]
Enable [Force04154000Download] in compat.ini, can remove this glitch. :)

![SW-EU](https://user-images.githubusercontent.com/26355472/178772879-a0b0565a-8b95-4183-8df4-c38e27923142.png)

**Comment by unknownbrackets** [comment]
Right, this is all because we're avoiding writing everything back to RAM due to speed reasons.  Software renderer probably looks fine, based on my above explanation.

Maybe the safest thing, as much as I hate them, is a compat.ini hack that allows texturing from odd offsets in this game.

-[Unknown]

**Comment by Gamemulatorer** [comment]
> Enable [Force04154000Download] in compat.ini file, can remove this glitch. :)
> 
> ![SW-EU](https://user-images.githubusercontent.com/26355472/178772879-a0b0565a-8b95-4183-8df4-c38e27923142.png)

Yes it's fixes the graphics issue of both star wars the force unleashed but the performance penalty is huge on mobile devices.
