### ISSUE TITLE
Active memory breakpoints causes PPSSPP lockup on emulation start/reset

### ISSUE THREAD

**Issue by gibbed** [hrydgard/ppsspp#12953]
Having any active memory breakpoints causes PPSSPP to get stuck in UI updates when you invoke emulation start/reset. Occurs even if the disassembly window is closed prior.

The disassembly window actively flickers as if it's getting redrawn over and over. It seems `WM_DEB_UPDATE` gets endlessly spammed - somehow related?

This is probably specific to the Windows desktop build. Tested and occurs with latest master built in debug (0ff922c3e0bac41c76c9ebf65c6d4721f9e9b42d)  and 1.9.3 stable release build.

Easy steps to reproduce, with Tactics Ogre: Let us Cling Together (`ULUS10565`), though I would assume this happens with any game:

1. Start PPSSPP.
1. Load LUCT.
1. Open the disassembly window (`Ctrl+D`).
1. Add a memory breakpoint with any valid address, for example: `0x08A080F0`.
1. Invoke emulation reset (`Ctrl+B`).
1. PPSSPP is now locked up.

Can also reproduce this behavior if I add a memory breakpoint before loading LUCT:

1. Start PPSSPP.
1. Open the disassembly window (`Ctrl+D`).
1. Add a memory breakpoint with any valid address, for example: `0x08A080F0`.
1. Load LUCT.
1. PPSSPP is now locked up.

**Comment by unknownbrackets** [comment]
Yeah, this happens when the breakpoint trips for the initial ELF load (i.e. if it's code or text/bss data.)  Not hard to fix.

-[Unknown]
