### ISSUE TITLE
[Android] [GL2.0] Ys SEVEN (ULUS10551) Smoke going through the wall on "Rites of Demise" stage.

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#12964]
### What happens?
Idk how exactly to explain properly this issue
but here's a screenshot for comparison

PPSSPP
![Screenshot_20200524-214611](https://user-images.githubusercontent.com/37603562/82756110-95e69680-9e0a-11ea-8829-eb9b6421ea7c.png)

PSP
![Screenshot_20200524-215509](https://user-images.githubusercontent.com/37603562/82756120-a7c83980-9e0a-11ea-8925-fbde44a79f88.png)
Source: https://youtu.be/hW5Wp_WT-PM

### What *should* happen?
No graphics glitch overlay?

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Android 6.0.1
Mali-450 GPU
OpenGL ES 2.0
PPSSPP v1.9.3-941

### My Settings
Simulated Block Transfer Effects - ON
Buffered Rendering Mode
Rendering Resolution - x2
Device Resolution - Native
Hardware Transform - ON
Software Skinning - ON
Vertex Cache - OFF

GE Dump 
[ULUS10551.zip](https://github.com/hrydgard/ppsspp/files/4673668/ULUS10551.zip)

**Comment by Gamemulatorer** [comment]
@unknownbrackets looks correct on SW rendering mode
![Screenshot_20200524-221858](https://user-images.githubusercontent.com/37603562/82756399-a3048500-9e0c-11ea-927e-015fc407f479.png)

**Comment by Panderner** [comment]
> PSP
> ![Screenshot_20200524-215509](https://user-images.githubusercontent.com/37603562/82756120-a7c83980-9e0a-11ea-8925-fbde44a79f88.png)
> Source: https://youtu.be/hW5Wp_WT-PM

@Gamemulatorer that video source is isn't a footage running on a real PSP they running this on a Emulator.

**Comment by unknownbrackets** [comment]
That dump plays back as this:

![ULUS10551_#12964_missing_wall](https://user-images.githubusercontent.com/191233/82770142-45604080-9dec-11ea-8d01-ff8f87538fd1.png)

Although, I'm seeing a bug while replaying this dump (in the dump's creation), so I'm not sure.

Do you have nearby save data?  Can you tell me exactly how to get to this place so I can see it on a PSP?

-[Unknown]

**Comment by Gamemulatorer** [comment]
@unknownbrackets I downloaded my savesdata from here https://gamefaqs.gamespot.com/psp/958946-ys-seven/saves and select Save before last boss. Normal mode.

**Comment by unknownbrackets** [comment]
Hm.  For me, it does look pretty much like the "PSP" area, but it looks the same in Vulkan and OpenGL for me.

Here's a dump (you can open this and see it render on your device):
[ULUS10551_0001.zip](https://github.com/hrydgard/ppsspp/files/4675238/ULUS10551_0001.zip)

-[Unknown]

**Comment by Gamemulatorer** [comment]
> Hm. For me, it does look pretty much like the "PSP" area, but it looks the same in Vulkan and OpenGL for me.
> 
> Here's a dump (you can open this and see it render on your device):
> [ULUS10551_0001.zip](https://github.com/hrydgard/ppsspp/files/4675238/ULUS10551_0001.zip)
> 
> -[Unknown]

how can I open it on my phone using ppsspp?

**Comment by unknownbrackets** [comment]
Extract the zip somewhere and browse to that folder, same as an iso.  It won't have an icon but it should show up.

-[Unknown]

**Comment by Gamemulatorer** [comment]
Graphics overlay glitch still showing
![Screenshot_20200525-125703](https://user-images.githubusercontent.com/37603562/82779718-85c0cc80-9e87-11ea-8283-536f06c89995.png)

**Comment by Gamemulatorer** [comment]
No graphics glitch overlay on Snapdragon 430 Adreno 505.
![Screenshot_20200525-130501](https://user-images.githubusercontent.com/37603562/82780149-dab11280-9e88-11ea-93ac-17e7f37f4d83.png)
Maybe this issue can only repro on GLES 2.0 device

**Comment by unknownbrackets** [comment]
Oh, the smoke is going through the wall?  I didn't notice that before, I thought it was about the bottom part.

The game draws the smoke to a temporary buffer at 0x000cc000.  Then around ~267/312 it draws to the screen, using alpha blend src.a + ONE.  Depth clamp enabled but doesn't seem involved.  But the source image already seems clipped.

It starts drawing that at ~248/312, which is a clear.  There it's using depth testing.

So it's relying on depth being copied between two framebuffers, which indeed isn't supported in GLES 2.0...

-[Unknown]

**Comment by Panderner** [comment]
![IMG_20200525_132525](https://user-images.githubusercontent.com/37503397/82781493-83ad3c80-9e8c-11ea-846e-1bc3d7ddbd0a.jpg)
I'm using Realme C2 and PPSSPP v1.9.3-956-gc8f8d5511 it displays correctly

**Comment by hrydgard** [comment]
I think we can close this, not fixable on ES 2.0 devices..

**Comment by Panderner** [comment]
> I think we can close this, not fixable on ES 2.0 devices..

Any games that requires GLES3 to Render Correctly @hrydgard?

**Comment by unknownbrackets** [comment]
Jeanne d'Arc comes to mind, for the same reason (depth copying.)  There might be some with blending issues.

-[Unknown]

**Comment by Panderner** [comment]
> depth

how about other games than Jeanne d'Arc?

**Comment by hrydgard** [comment]
Saint Seiya, I believe.

**Comment by Gamemulatorer** [comment]
Just linking other related issues.

#1283 Jeanne D'Arc - Invisible Dialogue Box and Models (GLES2)

#1808 Saint Seiya Omega Missing Character (GLES2)
