### ISSUE TITLE
(UWP) Compiling Issues

### ISSUE THREAD

**Issue by dominater01** [hrydgard/ppsspp#12976]
when compiling the uwp aka xbox one version im getting a bunch of errors

https://cdn.discordapp.com/attachments/533036478503321631/714400452082532363/Untitled.jpg

**Comment by hrydgard** [comment]
still don't have any CI for this so it keeps breaking. I'll fix it soon.

**Comment by hrydgard** [comment]
This should no longer be an issue, although the sound is a bit broken right now. 

I hope to have a fix for it soon.
