### ISSUE TITLE
Ultimate Ghosts'n Goblins glitched effects OpenGL

### ISSUE THREAD

**Issue by leronoa** [hrydgard/ppsspp#12981]
### What happens?
On Nintendo Switch some effects display a white overlay. For example some monsters on the first stage:

![2020052819522200](https://user-images.githubusercontent.com/66084798/83178095-5d073400-a120-11ea-961f-a63dffc0d7f9.jpg)

Or show garbage on screen like the lightning:

![2020052819515100](https://user-images.githubusercontent.com/66084798/83178438-cbe48d00-a120-11ea-91a2-bd3feeb743a6.jpg)

I tried with software rendering and that seems to fix the lightning effect but not the white overlay on some enemies, it displays as border instead:

![2020052819543000](https://user-images.githubusercontent.com/66084798/83178802-588f4b00-a121-11ea-974d-59c6053379e0.jpg)

Checked with my phone and laptop  to see the problem was Switch specific but it has a different problem, some blue text appears instead of the overlay or the garbage on OpenGL:
![Screenshot_20200528_191033](https://user-images.githubusercontent.com/66084798/83179054-bc197880-a121-11ea-9119-40a9063e6a49.png)
This one appears more faint, it's hard to see:
![Screenshot_20200528_200234](https://user-images.githubusercontent.com/66084798/83179217-fdaa2380-a121-11ea-8d1a-1f4f184db3c3.png)

Vulkan works perfectly but unfortunately it isn't an option on Switch.

### What *should* happen?

The effects should render without an overlay or garbage on screen.
### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Nintendo Switch:
-Firmware 10.0.2
-Atmosphere 0.12
-PPSSPP Standalone GL 1.9.3-752-g244a60138 by m4xw
Laptop:
-Manjaro KDE
-Intel HD5500 with mesa 20.0.6
-PSSPP 1.9.4
Phone:
-Android 9
-Adreno 512
-PPSSPP 1.9.4

**Comment by Gamemulatorer** [comment]
> Checked with my phone and laptop to see the problem was Switch specific but it has a different problem, some blue text appears instead of the overlay or the garbage on OpenGL:
> ![Screenshot_20200528_191033](https://user-images.githubusercontent.com/66084798/83179054-bc197880-a121-11ea-9119-40a9063e6a49.png)
> This one appears more faint, it's hard to see:
> ![Screenshot_20200528_200234](https://user-images.githubusercontent.com/66084798/83179217-fdaa2380-a121-11ea-8d1a-1f4f184db3c3.png)

Could you create a frame dump, at any scene that's missing a background? Doesn't matter if the frame dump is created on PC or Android.

https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

**Comment by leronoa** [comment]
I made two frame dumps one for the lightning in 2-1 stage and other for the monsters in 1-1, both on my laptop:
[frame_dump_ugng.zip](https://github.com/hrydgard/ppsspp/files/4701442/frame_dump_ugng.zip)
Also the text that appears seems to be the first thing that shows on screen when starting the game, the check for the memory card.

**Comment by hrydgard** [comment]
How is this now in the latest builds?

**Comment by leronoa** [comment]
> How is this now in the latest builds?

On nintendo switch still the same, on android with opengl, in the castle level the lightning effect flashes parts a level in a blue overlay instead of the text.
Using the latest build by m4xw on switch (1.10.3-268-g7ffc37eb7) and the latest version avaliable on the Play Store on android.

**Comment by hrydgard** [comment]
That's not very new, you need to try a fresh build, something after 1.10.3-1264.

**Comment by leronoa** [comment]
Oh well, that's the latest version avaliable on switch, should this issue be closed?

**Comment by hrydgard** [comment]
I think it's pretty safe to close given the fixes I've made recently - let's see if it shows up again. Maybe m4xw will make a new release soon.
