### ISSUE TITLE
Rendering problem. (Android)

### ISSUE THREAD

**Issue by Saramagrean** [hrydgard/ppsspp#12992]
### What happens?
PPSSPP not rendering full screen in every game, after enable Immersive mode, Since v1.9.3-985.
![Screenshot_20200601-200109_PPSSPP](https://user-images.githubusercontent.com/26355472/83412641-aae3ab00-a444-11ea-976b-88a5ce2a9e6f.png)

### What *should* happen?
PPSSPP can rendering game in full screen with Immersive mode.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
- Huawei P9+ (Android 9.0, Kirin 955, Mali T-880)

**Comment by hrydgard** [comment]
That's.. a bit unexpected. What if you go to Settings / Graphics / Display Layout Editor and change the Option to Auto Scale? Do you still see this?

**Comment by Saramagrean** [comment]
Oh, It cause by "Auto scale", after change to "Stretching",  image comes back to full screen again.

**Comment by hrydgard** [comment]
Well, stretching is not really optimal, we want to support auto scale. I'm going to have to look into this, thanks for reporting.

**Comment by hrydgard** [comment]
Checked in a fix for the typo, hope that's enough to take care of this.

**Comment by Saramagrean** [comment]
Confirm, it fixed. 👍
