### ISSUE TITLE
Weird artifacts in Metal Gear Solid Peace Walker

### ISSUE THREAD

**Issue by milweekmoon** [hrydgard/ppsspp#12991]
Backend: OpenGL(This problem doesn’t seem to happen when using Vulkan)

PPSSPP: Version 1.9.3 

OS: iOS 1.13.5 Jailbroken 

Device: iPhone XR 

![D7BA6771-1ECB-4ED2-B807-A9E166893429](https://user-images.githubusercontent.com/66230819/83369474-7ad7d180-a38a-11ea-9ef5-0c52b08b43b9.png)
![D2ED5F2A-0794-459B-80C3-8FCB3411DDED](https://user-images.githubusercontent.com/66230819/83369484-80351c00-a38a-11ea-9822-8003bf6c7ca4.png)

This is what it supposed to look like:

![E118C30F-967B-4F43-B1F6-0614FB1E51FE](https://user-images.githubusercontent.com/66230819/83369680-313bb680-a38b-11ea-896b-be35b4680051.jpeg)

This might be a stupid question but I can’t find any answers online. Will Vulkan as Backend ever come the ppsspp on iOS?

This is the frame dump of the game:
https://github.com/milweekmoon/mgspw-frame-dump

**Comment by Gamemulatorer** [comment]
Related #12990?

Could you create a frame dump.? Doesn't matter if the frame dump is created on PC or Android.

https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

**Comment by jcchikikomori** [comment]
> This might be a stupid question but I can’t find any answers online. Will Vulkan as Backend ever come the ppsspp on iOS?

I can answer this for now. Apple is pushing hard to use its Metal API and deprecating OpenGL. So NO Vulkan for iOS

Reference: https://www.extremetech.com/gaming/264694-khronos-brings-vulkan-macos-ios-apple-refuses

**Comment by milweekmoon** [comment]
> Related #12990?
> 
> Could you create a frame dump.? Doesn't matter if the frame dump is created on PC or Android.
> 
> https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

Sorry, I do I make a frame dump?

**Comment by milweekmoon** [comment]
> Related #12990?
> 
> Could you create a frame dump.? Doesn't matter if the frame dump is created on PC or Android.
> 
> https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

> I have made one, how should I send it to you?

**Comment by Gamemulatorer** [comment]
> > I have made one, how should I send it to you?

Upload here in github so that @unknownbrackets can fixed your issue.

**Comment by milweekmoon** [comment]
> Upload here in github so that @unknownbrackets can fixed your issue.

**Comment by milweekmoon** [comment]
> > > I have made one, how should I send it to you?
> 
> Upload here in github so that @unknownbrackets can fixed your issue.

I have a link of the file at the very bottom of the post. Btw, thank you for helping.

**Comment by Gamemulatorer** [comment]
Looks fine on my phone using opengl
v1.9.4
![ppssppv1 9 4](https://user-images.githubusercontent.com/37603562/83375695-47d12480-a402-11ea-85d3-ab5c6c8023cd.png)
v1.9.3-985
![ppssppv1 9 3](https://user-images.githubusercontent.com/37603562/83375715-5cadb800-a402-11ea-98b0-e8238ca35dfd.png)

**Comment by milweekmoon** [comment]
> Looks fine on my phone using opengl
> v1.9.4
> ![ppssppv1 9 4](https://user-images.githubusercontent.com/37603562/83375695-47d12480-a402-11ea-85d3-ab5c6c8023cd.png)
> v1.9.3-985
> ![ppssppv1 9 3](https://user-images.githubusercontent.com/37603562/83375715-5cadb800-a402-11ea-98b0-e8238ca35dfd.png)

May I ask, what phone are you using? Is it Android or iOS?

**Comment by Gamemulatorer** [comment]
Android full specs here 
[DevCheck-20200601-1239.txt](https://github.com/hrydgard/ppsspp/files/4709396/DevCheck-20200601-1239.txt)

**Comment by milweekmoon** [comment]
> Android full specs here
> [DevCheck-20200601-1239.txt](https://github.com/hrydgard/ppsspp/files/4709396/DevCheck-20200601-1239.txt)

Ah, Android. This problem seems to only happen on iOS devices. Every video of msgpw on iOS seems to have this issue as well but I have never seen this problem on Android.

**Comment by Panderner** [comment]
Disable slower effects on:
![Screenshot_2020-09-02-17-59-00-94_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/91968185-d9746900-ed46-11ea-8ea3-9b4e1bd31771.png)

Disable slower effects off:
![Screenshot_2020-09-02-17-59-08-74_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/91968214-e42efe00-ed46-11ea-8c29-8c0919383337.png)

Here's a GE Dump:
[MGSPW.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/5161560/MGSPW.ppdmp.zip)

**Comment by unknownbrackets** [comment]
Has this improved in the latest git builds?

This could've been related to the IR interpreter fixes (maybe, probably not) or the flat shading driver bug.

-[Unknown]

**Comment by milweekmoon** [comment]
> Has this improved in the latest git builds?
> 
> This could've been related to the IR interpreter fixes (maybe, probably not) or the flat shading driver bug.
> 
> -[Unknown]

Dude it’s been like half a year since I posted this problem but still, thanks for commenting! I have no idea since I gave up after a while but I am going to try again now.

**Comment by unknownbrackets** [comment]
Okay, I'm going to assume there's a good chance those changes improved this especially given #10650.  Will close.

If you're still seeing exactly this bug please comment and we'll reopen.  If you're seeing another bug in the same game or a similar bug even, please create a new issue.

-[Unknown]
