### ISSUE TITLE
[Nvidia Shield] 8bitdo sn30 pro+ B button doesn't cancel in menus in D-input mode

### ISSUE THREAD

**Issue by ds22x** [hrydgard/ppsspp#12999]
### What happens?
When using a 8bitdo sn30 pro+ controller in D-input mode, both the A and B buttons act as confirm buttons inside the menu.

### What *should* happen?
At least one of the buttons (preferably B) should act as a cancel/back button.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Nvidia Shield 2017, Android 9 with Shield Experience 8.0.2, PPSSPP v1.9.3-998-gc739d4e16.

**Comment by unknownbrackets** [comment]
Was this a setting issue on the device?  If you can share your solution, it may help others in the future.

-[Unknown]

**Comment by ds22x** [comment]
Had to set the "O/X button to confirm" option to O, and then close and reopen the app.
