### ISSUE TITLE
[android] ghost rider doesn't starts

### ISSUE THREAD

**Issue by LuisFellp** [hrydgard/ppsspp#13000]
### What happens?

ghost rider.cso and .iso doesnt starts, it get stuck at rider face:
![Screenshot_20200605-120105_PPSSPP](https://user-images.githubusercontent.com/33043774/83899726-ed4c0700-a726-11ea-88cb-8691cd7f2b1e.jpg)

### What *should* happen?

it supposed to start normally, like on other devices

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Exynos 7 Octa (7904), Android 10, 1.9.4

**Comment by Panderner** [comment]
Works fine for me but it's seems your ISO is corrupted @LuisFellp

**Comment by Panderner** [comment]
@LuisFellp are you using USA or Europe version of this game?

**Comment by Gamemulatorer** [comment]
> ### What happens?
> ghost rider.cso and .iso doesnt starts, it get stuck at rider face:
> ![Screenshot_20200605-120105_PPSSPP](https://user-images.githubusercontent.com/33043774/83899726-ed4c0700-a726-11ea-88cb-8691cd7f2b1e.jpg)
> 
> ### What _should_ happen?
> it supposed to start normally, like on other devices
> 
> ### What hardware, operating system, and PPSSPP version? On desktop, GPU matters for graphical issues.
> Exynos 7 Octa (7904), Android 10, 1.9.4

Could you create a frame dump.? Doesn't matter if the frame dump is created on PC or Android.

https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

**Comment by fahadrashid7705** [comment]
yesterday i play this game without any issue , try to download this rom from another site maybe file corrupted

**Comment by Gamemulatorer** [comment]
> Exynos 7 Octa (7904), Android 10, 1.9.4

I notice that you are using the playstore v1.9.4 try ppsspp latest git build here
https://buildbot.orphis.net/ppsspp/

**Comment by Panderner** [comment]
> yesterday i play this game without any issue , try to download this rom from another site maybe file corrupted

@fahadrashid7705 Downloading From ROM sites are illegal without you legally own. Please refer dumping your UMDs or Digital games purchased on PSN.

**Comment by fahadrashid7705** [comment]
you are right pairacy not allowed , sry for my bad english

**Comment by LuisFellp** [comment]
I'm closing this issue. it happens because the wlan was turned off. when i start the game with wlan turned on, i have no issues
