### ISSUE TITLE
Weird emulation error (Something is accumulating) Sengoku Musou 3 Z Special

### ISSUE THREAD

**Issue by RobertSVG15** [hrydgard/ppsspp#13003]
Hello in the game **Sengoku Musou 3 Z Special**, a weird error occurs and **forces** the PPSSPP to close. Basically it is this:

_"When you use a certain character and carry out one of his attacks for multiple times; a point comes where the game crashes, it is as if something is accumulating and that causes the crash later"._ 

### **Detailed explanation:**

1) This is the Story Mode:

![IMG-20200606-WA0000](https://user-images.githubusercontent.com/59510411/83947380-9442a880-a7e4-11ea-8ebd-50f6a6cd8f1b.jpg)

2) The crash happens when playing with Tachibana Ginchiyo (立 花 誾 千代):
 
![IMG-20200606-WA0001](https://user-images.githubusercontent.com/59510411/83947390-a02e6a80-a7e4-11ea-913a-faa287ac68e8.jpg)

3) Usually the error almost certainly occurs in the 5th scenario of the campaign:

![IMG-20200606-WA0002](https://user-images.githubusercontent.com/59510411/83947397-a886a580-a7e4-11ea-9c25-1f522484c5b6.jpg)

4) When enemies are hit; the musou bar fills up. By filling a bar you can do the musou attack. When you hold down the "O" button Ginchiyo performs the animation in the picture. Notice the "big blue aura" around her.

![IMG-20200606-WA0004](https://user-images.githubusercontent.com/59510411/83947402-afadb380-a7e4-11ea-8e28-8290913c3f31.jpg)

5) If you perform that attack multiple times, the game will start to crash. It is as if something is accumulating (?) And at one point; crashes and closes PPSSPP. **The "big blue aura" around her also disappears!**

![IMG-20200606-WA0005](https://user-images.githubusercontent.com/59510411/83947409-b50afe00-a7e4-11ea-857a-0e3ecde7c7ed.jpg)

6) This is the exact route I take. I start in the blue circle, I follow the blue route and then the orange to the yellow circle area. In that area it is much more likely that the crash occurs. **(Just kill the big red points, they are officers).**

![IMG-20200606-WA0003](https://user-images.githubusercontent.com/59510411/83947415-bb997580-a7e4-11ea-9dbb-74da7941930b.jpg)

### **Additional information:**

- The only time I managed to complete the scenario was when I tried the **build v1.9.3-998-gc739d4e16**. For some reason it worked once.
- Build v1.9.3-999-g021e783b4 does not work with this. I t think most of the above maybe not either, I saw this bug over 1 year ago. Only the build v1.9.3-998-gc739d4e16 seemed to work more or less.
- I have tried many emulation options and none solves the problem.

Here I attach **[my savedata](https://drive.google.com/drive/folders/1eSck7WvOEJVLKUbXroNRewN60w3afUvE?usp=sharing)** to see if anyone can help with this problem. 

**Thank you.**

**Comment by RobertSVG15** [comment]
Hello @hrydgard ,could you please take a look into this when you can?

**Comment by sum2012** [comment]
v1.9.3-997-gd8992a6ae work
v1.9.3-998-gc739d4e16 don't work ?

**Comment by hrydgard** [comment]
997 was the experimental commit I did that extended the size of the scratchpad memory to bigger than the actual size on the PSP. Weird if that fixed this. To me, it seems like a different bug that accidentally got worked-around by that...

I just realized, too, that savestates from 997 are unsafe to use on other versions, so don't do that.

**Comment by sum2012** [comment]
Sorry @hrydgard  ,I only mean let @RobertSVG15  test again that two build

**Comment by hrydgard** [comment]
Oh okay, I misunderstood.

**Comment by hrydgard** [comment]
@RobertSVG15 can you comment on why you closed this, is the issue fixed for you in the latest builds?
