### ISSUE TITLE
[Switch] Earth Defense Force 2 Portable crash on Jit and IR Interpreter, with a catch

### ISSUE THREAD

**Issue by leronoa** [hrydgard/ppsspp#13002]
### What happens?
When you try to load a mission with the Jit or IR Interpreter cpu core, PPSSPP crashes. The Interpreter cpu core doesn't crash but it's too slow to be playable.. Here is the crash report generated by the Atmosphere CFW with the Jit cpu core if it helps:
[crash_reports.zip](https://github.com/hrydgard/ppsspp/files/4740130/crash_reports.zip)

The catch is that there is a workaround for this:
-Load a mission with Interpreter.
-Exit to menu from the PPSSPP pause menu.
-Change cpu core to Jit or IR Interpreter.
Now the game will not crash until you close PPSSPP, when you will have to play on Interpreter only or use the workaround mentioned above.
I don' have any problems with the game on my phone with the Jit cpu core, which has a Snapdragon 660.

### What *should* happen?
The game shouldn't crash.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Nintendo Switch:
-Firmware 10.0.2
-Atmosphere 0.12
-PPSSPP Standalone GL 1.9.3-752-g244a60138 by m4xw

**Comment by Panderner** [comment]
@leronoa have you tried the windows version of PPSSPP? for me it doesn't crash on my Android phone

**Comment by leronoa** [comment]
@Panderner  It doesn't crash on my phone either, i said it on my report:
> I don' have any problems with the game on my phone with the Jit cpu core, which has a Snapdragon 660.
I tried it on my laptop with Linux and it doesn't crash either, it is on Nintendo Switch only.

**Comment by Panderner** [comment]
> @Panderner It doesn't crash on my phone either, i said it on my report:
> 
> > I don' have any problems with the game on my phone with the Jit cpu core, which has a Snapdragon 660.
> 
> I tried it on my laptop with Linux and it doesn't crash either, it is on Nintendo Switch only.

@leronoa how about windows version of PPSSPP?

**Comment by leronoa** [comment]
@Panderner Just tried on a Windows 10 PC with the latest version, no problems either.

**Comment by Gamemulatorer** [comment]
Can you still reproduce this issue?

**Comment by hrydgard** [comment]
Sounds like this has likely been fixed in the code base, don't know if a new Switch version is out with the fix though. Anyway, closing.
