### ISSUE TITLE
Graphical Glitches in Colin McRae Dirt 2 (missing water)

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#13012]
There are some graphical gliches in Dirt 2:

Car Models renders incorrectly:

Real Hardware:
![IMG_20200608_161249](https://user-images.githubusercontent.com/37503397/84007460-0a8d0980-a9a3-11ea-9eba-051e3badb257.jpg)
![IMG_20200608_161300](https://user-images.githubusercontent.com/37503397/84008757-dc102e00-a9a4-11ea-89fa-c1635e05309e.jpg)

PPSSPP:
![Screenshot_2020-06-08-16-09-12-08_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/84007561-314b4000-a9a3-11ea-864f-546bf29475fa.png)
![Screenshot_2020-06-08-16-06-38-08_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/84008793-e92d1d00-a9a4-11ea-8ddc-841d22fea507.png)

Water are missing in some tracks.
Real Hardware:
![IMG_20200608_162404](https://user-images.githubusercontent.com/37503397/84008589-a66b4500-a9a4-11ea-9faf-d022cfe293dd.jpg)

PPSSPP:
![Screenshot_2020-06-08-16-22-40-67_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/84008881-0366fb00-a9a5-11ea-806b-6baa262cb607.png)

And of course here's a GE Dump:
[Car Select.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/4744765/Car.Select.ppdmp.zip)
[In-game.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/4744766/In-game.ppdmp.zip)
[Water.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/4744768/Water.ppdmp.zip)

**Comment by Gamemulatorer** [comment]
OpenGL
![Screenshot_20200609-202454](https://user-images.githubusercontent.com/37603562/84147081-603ee000-aa8f-11ea-8a3a-47ea3d66d168.png)

**Comment by Maarcis12** [comment]
Looks like you fixed the issue, thank you.
![ULES01301_00004](https://user-images.githubusercontent.com/26842473/93888553-d559bc80-fcf0-11ea-8777-5684bcda7fbf.jpg)
![ULES01301_00002](https://user-images.githubusercontent.com/26842473/93888562-d68ae980-fcf0-11ea-8f2f-bcff01d6e375.jpg)

**Comment by Maarcis12** [comment]
so now only water isn't rendered in the game.

**Comment by Panderner** [comment]
But the car models still not fixed in OpenGL on latest build
![Screenshot_2020-09-22-22-11-30-09_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/93894153-fcc87d80-fd20-11ea-88d6-d7fbe9fbcb18.png)
![Screenshot_2020-09-22-22-10-51-08_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/93894245-179af200-fd21-11ea-82fd-92e07b4fce06.png)

@Maarcis12 have you tested all backends?

**Comment by Panderner** [comment]
> Looks like you fixed the issue, thank you.
> ![ULES01301_00004](https://user-images.githubusercontent.com/26842473/93888553-d559bc80-fcf0-11ea-8777-5684bcda7fbf.jpg)
> ![ULES01301_00002](https://user-images.githubusercontent.com/26842473/93888562-d68ae980-fcf0-11ea-8f2f-bcff01d6e375.jpg)

it's seem the GO texture is wrong. here's a screenshot for correct result:
![Screenshot_2020-09-22-22-17-00-36_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/93894784-b1629f00-fd21-11ea-9a71-afa583d877b6.png)

**Comment by Maarcis12** [comment]
@Panderner yeah, i tested all backends, it could also be that i have "disable slower effects" enabled, so my bad on that one.

**Comment by Panderner** [comment]
![Screenshot_2020-09-30-20-11-14-21_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/94683672-7a137400-0359-11eb-8e4c-38568b21bd6e.png)
It's seems the Off-Road Vehicles are glitched too in white texture.

But when i tried to make the GE Dump the car disappears:
[Off-Road Vehicle.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/5305333/Off-Road.Vehicle.ppdmp.zip)

**Comment by Maarcis12** [comment]
also, sorry for silence, i was bit busy with my job, but i will apologize for the initial confusion because the reason it doesn't act up on my end is that i have "Disable slower effects" enabled.

**Comment by Panderner** [comment]
Umm yes @Maarcis12 . Disable slower effects can fix texture glitches for cars but the water still not fixed. the water issue still remain.

**Comment by Maarcis12** [comment]
and that's what i mentioned earlier.

**Comment by Panderner** [comment]
It seems v1.10.3-1267-gf1ab6c62c breaks Dirt 2
![Screenshot_2020-12-11-22-27-00-41_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/101915056-0e267500-3c00-11eb-94c1-f5f9affee80a.png)

**Comment by Maarcis12** [comment]
![ULES01301_00000](https://user-images.githubusercontent.com/26842473/101919968-e4575900-3bd3-11eb-9400-d67fbb689c9f.jpg)
Yeah, it definitely broke the game

**Comment by hrydgard** [comment]
I'll get that fixed, thanks for reporting!

**Comment by hrydgard** [comment]
OK, cars should be back now, and with better lighting.

**Comment by Panderner** [comment]
The graphics are fixed but water is still glitching
![Screenshot_2020-12-13-17-38-28-568_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/102008254-3c27c880-3d6a-11eb-9a9e-c3cca16c805b.jpg)

**Comment by Maarcis12** [comment]
![ULES01301_00002](https://user-images.githubusercontent.com/26842473/102015921-f4ec0880-3d66-11eb-8b91-0ceca39cd018.jpg)
yeah, the reflections are fixed, tho water is flickering, it spawns then it doesn't spawn

**Comment by Gamemulatorer** [comment]
> The graphics are fixed but water is still glitching
> ![Screenshot_2020-12-13-17-38-28-568_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/102008254-3c27c880-3d6a-11eb-9a9e-c3cca16c805b.jpg)

This gfx issue can only reproduce on opengl
![Screenshot_2021-08-09-16-04-30-715_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/128677650-0d928114-1ce7-47cd-8550-800cb7a8bfae.jpg)
vulkan is ok?
![Screenshot_2021-08-09-16-06-13-374_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/128677864-811867b4-516a-496d-a056-6c6f50100997.jpg)

**Comment by Panderner** [comment]
Same here for my PC and my phone using vulkan:
![Ppsspp Screenshot 2021 08 09 - 19 44 31 14](https://user-images.githubusercontent.com/37503397/128701271-b0184207-7e4a-4a0d-acc4-4c16696d26c6.png)

in DIrect3D 11 the water flickers:
![ezgif com-gif-maker](https://user-images.githubusercontent.com/37503397/128701325-c0430a24-7911-4e79-9b52-1b39a951576d.gif)

**Comment by Gamemulatorer** [comment]
> Same here for my PC and my phone using vulkan:
> ![Ppsspp Screenshot 2021 08 09 - 19 44 31 14](https://user-images.githubusercontent.com/37503397/128701271-b0184207-7e4a-4a0d-acc4-4c16696d26c6.png)
> 
> in DIrect3D 11 the water flickers:
> ![ezgif com-gif-maker](https://user-images.githubusercontent.com/37503397/128701325-c0430a24-7911-4e79-9b52-1b39a951576d.gif)

No glitch on my phone using vulkan issue only happen on opengl.

**Comment by Panderner** [comment]
@Gamemulatorer I'm using POCO M3 still have graphical glitch on vulkan.

**Comment by Gamemulatorer** [comment]
> @Gamemulatorer I'm using POCO M3 still have graphical glitch on vulkan.

So the vulkan gpu of sd 662 is so glitch on PPSSPP 🤔

**Comment by Panderner** [comment]
And yes my PC too on vulkan. I'm using a GTX 1050 Ti GPU

**Comment by unknownbrackets** [comment]
In the water frame dump, it seems like the water starting being drawn near 1999/6546.  The water is drawn using a stencil test, only drawing water where stencil is set.  At that point, there's just a bunch of dots where there should be water, so that's why it draws as a bunch of dots.  The problem must be earlier, where the stencil bits are established.

The frame starts with all stencil cleared.  It draws the water stencil around 1839/6546, which goes wrong mostly due to alpha testing on the texture:
![Game image with water visible](https://user-images.githubusercontent.com/191233/128813488-0ded2c86-a677-48b5-9a36-a3b954328816.png)

The texture is at 0x040cc000.  It's drawn at 1364/6546 as 565, but then used as 4444.  So definitely going through reinterpret.

The game is doing an alpha test on alpha for 0xE0 (effectively 0xE since it's 4444) == 0x20 (effectively a & 0xE == 0x2.)

This problem seems to be an RGB mask issue.  When the game draws the texture that is reinterpreted, its final draw is masked with 0x7FFFFF.  Because we don't actually support masking, we end up clearing the entire blue color, instead of just the top bit.

-[Unknown]

**Comment by hrydgard** [comment]
We do have support for write masks through shader framebuffer blend now if you turn them on in compat.ini, actually (ShaderColorBitmask). maybe that'll be enough together with reinterpret?

**Comment by hrydgard** [comment]
Even turning off BlueToAlpha and on ShaderColorBitmask doesn't help here, the reinterprets seem to be going okay though, don't quite see where it goes wrong or how exactly it's supposed to work. It does involve stencil too, and actually does two passes of first drawing water masks with alpha test and then stencil-tested water texture, just with two different diffuse colors, but I don't see any annoying stencil/alpha interaction like using DST_ALPHA or similar.

**Comment by unknownbrackets** [comment]
Turning off the alpha test for 1920/6546 gives pretty solid looking water (obviously that goes outside bounds.)  There's indeed an earlier pass at 1450/6546, which also sets stencil.

It's a bit odd that it wants alpha to be >= 0x20 && <= 0x3F.  When it renders at 565, we end up with this:
![Almost looks like an eyeball](https://user-images.githubusercontent.com/191233/188052032-f4c41f02-51d0-47ad-b70b-1731b1ddcffd.png)

The sphere is created around 2633/6546 (so, later in the frame), but all the draws starting at 1364 use a mask to write only 4 or less bits of blue.

Software rendering has a more dithered but similar result:
![Smaller eyeball](https://user-images.githubusercontent.com/191233/188050928-53ca0e2f-f742-483b-ad00-a23086bcbb0d.png)

But the reinterpreted result looks correct (still software):
![Nice cloudy water texture](https://user-images.githubusercontent.com/191233/188051029-94fe9f43-e60b-41bb-9a17-a637ead89f96.png)

And a lot of the alpha values are 34 (0x22.)  So this must be what it's going for.

Back to Vulkan, the preview in the GE debugger, at least, shows this:

![Weird blue patches](https://user-images.githubusercontent.com/191233/188052168-73c07369-e3fb-4ab4-bc87-1c538c9047b4.png)

The places we wanted to have alpha seem to have blue, and full alpha.  I wonder if 4444 and 5551 are swapped or something.

-[Unknown]

**Comment by unknownbrackets** [comment]
Okay, turns out the dump I'm using didn't activate the ShaderColorBitmask flag somehow, but forcing it on still gives this as the texture:

![Patchy alpha](https://user-images.githubusercontent.com/191233/188055136-250764a2-d1f6-4089-8328-ff7ba1884243.png)

Which is converted from this:

![Better eyeball](https://user-images.githubusercontent.com/191233/188055276-bb314020-49a0-415a-b957-84d2e6bd4e09.png)

There's almost no blue with the right colors.  In software, I see dither is actually not enabled during these draws.  But ultimately the alpha ends in the right ranges.

-[Unknown]

**Comment by hrydgard** [comment]
Maybe it was an old dump before we had game IDs embedded in them?

Anyway, I think there might bea problem with the combination shader blending (which is required for the masking) and logic ops. The logic operation will happen after the masking, and not itself be masked, which is gonna result in some wrong bits.

We are going to have to move logic ops into shader blending (assuming this is the issue, but we should anyway). This also allows for emulating logic ops on platforms where they are not available.

**Comment by unknownbrackets** [comment]
Aha, darn.  I missed that it was doing logic ops.  That explains it indeed.

-[Unknown]

**Comment by hrydgard** [comment]
Note: Not yet fully fixed on all platforms. D3D11 and OpenGL ES coming up. Keeping closed, since the mystery is solved.
