### ISSUE TITLE
Phantasy Star Portable (USA / EUR / Jap) under Windows 7

### ISSUE THREAD

**Issue by inukaze** [hrydgard/ppsspp#13019]
### What happens?
1 - Start the PPSSPP latest version under Windows 7 (64 Bits)

2 - Start Phantasy Star Portable (1 / 2 [USA/EUR/JAP] / 2i [JAP] )

3 - In a Single WiFi AdHoc Network (not router in middle) 
Port = 27312
Host PC = 192.168.1.3
Client 1 = 192.168.1.4
Client 2 = 192.168.1.7

With Integrated AdHoc
With Integrated AdHoc + AdHoc Pro Server
With AdHoc Pro Server without Integrated AdHoc.

Well we try rotating the host, and is equal, ever is the same result.

Start in Multi(Player LAN) Mode, You can see the another characters (Sometimes just don't appear or don't connect, just try a few of times)

Wait the the another player(s) join, and go and try to start any mission, the game stuck on "Now Loading"

### What *should* happen?
When the host, party leader select a mission and the another player(s) accept the mission should be start. but this don't happend under 

### What hardware, operating system, and PPSSPP version?  
One Desktop, One Laptop, One Netbook.
Windows 7 (32 Bits neither 64 Bits), Desktop, GPU not, just IGP from Intel and we can play fine anothers titles like : Burnout or Tekken 6 or Monster Hunter Freedom Unite. 

Note : if i ran for example for Lubuntu 16.04 LTS Live from USB, i solve the libs PPSSPPSDL search the emulator start fine, i configure for example : 
1 - Create a config folder with
`mkdir -p "$HOME/.config/ppsspp"`

2 - Create a symbolic link to my data on USB
`ln -sf "$USB/memstick/PSP/" "$HOME/.config/ppsspp/PSP"`

3 - Start PPSSPPSDL

4 - Check the network configuration, start the game, i must be the host and the leader party and via this method we can play, not stuck on "Now Loading" a in few second we can start. from Windows 7, we had wait 1 hour and nothing happend.

Under GNU/Linux i don't had any need to use the AdHoc Pro Server for the connection works, with the Integrated works very fine.

But i don't have autorization for replace Windows 7 with GNU/Linux. because of that i want to know if someone had a fix

**Comment by unknownbrackets** [comment]
So if I understand correctly, this works on Linux but only doesn't work on Windows (or didn't.)

I wonder if this is related to settings or if it's possibly been fixed.  Can you try the latest git build?  Also make sure "real clock sync" is enabled on both devices.

-[Unknown]

**Comment by inukaze** [comment]
> So if I understand correctly, this works on Linux but only doesn't work on Windows (or didn't.)

Yes, under GNU/Linux works fine.
Under Microsoft Windows, this game never connect just hang up in the screen "Now Loading..."
 
> I wonder if this is related to settings or if it's possibly been fixed. 
Its not the settings, i try a lot with that, but in that version is some on binary executable.

>Can you try the latest git build? Also make sure "real clock sync" is enabled on both devices.
> 
> -[Unknown]

Ok, i try with the latest windows versions under Windows 7 (64 Bits). Because i really dunno the latest versions for GNU/Linux works with Slackware64 14.2 [Because this distro use software 7 years old like the latest version officially supported]

**Comment by inukaze** [comment]
Finally is fixed, i forgot post the answer, yesterday, because the weekeend i play with friends directly from Windows 7 x64. before i must use an Live USB with Lubuntu 16.04 for we can play together, because before when the mission start, hang up the game in a infinite loop on loading screen. But finally is fixed under Windows 7 x64.
