### ISSUE TITLE
Digimon Adventure PSP NPJH-50686 Cutscene videos colors appear wrong on Direct3D 11 Backend.

### ISSUE THREAD

**Issue by LPatamon** [hrydgard/ppsspp#13014]
### What happens?
When using Direct3D 11 Backend, the videos don't show the right colors

![bad colors](https://user-images.githubusercontent.com/6118529/84111103-d1c55280-a9eb-11ea-896e-1459e5be0715.jpg)

### What *should* happen?
Cutscene videos should play in the right colors

![right colors](https://user-images.githubusercontent.com/6118529/84111105-d2f67f80-a9eb-11ea-826c-3cd791462a12.jpg)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

3Ghz Core i5-3330 (Quad Core), 4GB Ram and 2GB AMD Radeon R7 Graphics Card on Windows 7 Ultimate 32 bits Desktop PC.

PPSSPP Version: ppsspp-v1.9.3-1015-gba06c87a7-windows-x86

**Extra notes** 

I don't know yet in which exact version this issue started since I updated from ppsspp-v1.9.3-617-g350589dd6-windows-x86 to ppsspp-v1.9.3-1015-gba06c87a7-windows-x86. I will go back installing versions till I find the one where the issue started and I'll update this thread.

For the record, on OpenGL backend the videos play in the right colors on ppsspp-v1.9.3-1015-gba06c87a7-windows-x86.

Edit: Managed to pinpoint the exact version where the issue started. It was on v1.9.3-760-gf23dd7635 which has the following description:

Merge: 6edf4ddc5 c1d32e8b3 Merge pull request #12882 from hrydgard/vulkan-fix-renderpass-opt Vulkan: Don't merge render passes where the second one begins with a clear.

It seems that something on that pull request affected the videos when using Direct3D 11 Backend.

**Comment by LPatamon** [comment]
I am missing info on my report? Is just I find odd that there's no reply yet n.nU

**Comment by hrydgard** [comment]
I don't know, I think I just didn't notice this one somehow. I'll tag it up for 1.11, this should be fixed. Maybe even take a quick look sooner.

**Comment by LPatamon** [comment]
> 
> 
> I don't know, I think I just didn't notice this one somehow. I'll tag it up for 1.11, this should be fixed. Maybe even take a quick look sooner.

Thanks. And well, with so many issues reported, plus all this mess of the covid-19, I don't blame you for missing a few issues here. That's why I thought it was maybe that It was more on my side that maybe I forgot to add some info about the issue :)

**Comment by hrydgard** [comment]
I think I got it :)   Was just a silly typo.

Please confirm once the new build is up.

**Comment by LPatamon** [comment]
> 
> 
> I think I got it :) Was just a silly typo.
> 
> Please confirm once the new build is up.

Okay. as soon the build is up. I'll test it and report :)

**Comment by LPatamon** [comment]
Issue fixed :)

![fixed](https://user-images.githubusercontent.com/6118529/84671908-87613b80-aeed-11ea-8306-e6bd934451fa.jpg)

**Comment by hrydgard** [comment]
Thanks for reporting it!

**Comment by LPatamon** [comment]
> 
> 
> Thanks for reporting it!

No problem. Thanks to you for the fix. Incredible how a tiny typo was messing up with the colors on the videos lol
