### ISSUE TITLE
Randomly Crash and Force Close

### ISSUE THREAD

**Issue by Exiasa** [hrydgard/ppsspp#13020]
![Screenshot_20200612-181746](https://user-images.githubusercontent.com/41770003/84494951-eef46c80-acdc-11ea-8784-e711ed1782a3.jpg)
![Screenshot_20200612-182001](https://user-images.githubusercontent.com/41770003/84494960-f1ef5d00-acdc-11ea-9b0b-305d864d19db.jpg)

### What happens?
After i comeback on PPSSPP I realize that i unable to play it.In Some Game After i kill some enemy or walk it will randomly crash 
(In OpenGL Naruto will run but randomly crash)
(In Vulkan bug Graphic unable to see player + decrease performace)

### What *should* happen?
It will run the game without force close

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Octa2Ghz
Adreno506

#

**Comment by Gamemulatorer** [comment]
possibly related to #12847

**Comment by unknownbrackets** [comment]
Are you using any cheats?  Does it happen with other games?

Try doing this:
1. Save in game if you're using a save states.
2. Reset to default settings, disabling any hacks like CPU speed changes etc.
3. Turn off any cheats you're using.
4. Start the game *without using any save states* and load your in-game save if needed.

Does it crash now?  If not, it's related to a hack.  It's very easy to make a game crash using cheats or by modifying its CPU speed.

-[Unknown]

**Comment by Exiasa** [comment]
same.... i not using cheat and i already reset to default the setting

**Comment by Gamemulatorer** [comment]
@Exiasa can you upload a savestates for that area? Also this issue of crash and freeze only happens on this game Naruto Shippuden!?

**Comment by Exiasa** [comment]
no...not only naruto....it also happen on GundamBattleUniverse,Kingdom heart,SengokuMusou3Z....and it random....if it want to crash it crash :(

**Comment by Gamemulatorer** [comment]
> no...not only naruto....it also happen on GundamBattleUniverse,Kingdom heart,SengokuMusou3Z....and it random....if it want to crash it crash :(

try to use matlog app it can capture log and upload it here.

**Comment by Exiasa** [comment]
matlog？

**Comment by Gamemulatorer** [comment]
> matlog？

https://play.google.com/store/apps/details?id=com.pluscubed.matlog

**Comment by Gamemulatorer** [comment]
@Exiasa no feedback/outdated?

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
