### ISSUE TITLE
KUROK PSP Homebrew need ForceMax60FPS enable

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#13025]
![Screenshot_00](https://user-images.githubusercontent.com/37603562/84559948-cff3ea00-ad71-11ea-8479-03590ba1cec2.png)
source:https://www.bladebattles.com/kurok/

### What happens?
Game is lag if not added to compat ForceMax60FPS
![Screenshot_02](https://user-images.githubusercontent.com/37603562/84559969-fd409800-ad71-11ea-9928-8d41b3aeaa02.png)

### What *should* happen?
Game should run smooth 
![Screenshot_01](https://user-images.githubusercontent.com/37603562/84559973-05003c80-ad72-11ea-9efa-99222b9f000e.png)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Android 6.0
Mali-400 GPU
ppsspp latest build

### log
[logs-2020-06-13-12-28-28.zip](https://github.com/hrydgard/ppsspp/files/4773995/logs-2020-06-13-12-28-28.zip)

**Comment by LunaMoo** [comment]
Homebrew don't have reliable gameID, so we generate fake one based on folder's name as many features depend on it. With compat.ini it's kind of pointless adding any homebrew there oficially as each user could name his folder differently and homebrew ports of licensed games are probably too shady to add to the homebrew store either.

**Comment by hrydgard** [comment]
This particular homebrew does have a very distinctive and uniquelooking gameID though.
