### ISSUE TITLE
Metal slug anthology freeze issue 

### ISSUE THREAD

**Issue by fahadrashid7705** [hrydgard/ppsspp#13022]
### What happens?

Metal slug anthology in metal slug 6 mission 3 freeze issue , plz fix . 
### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Sd430 , adreno 505, last build of ppsspp

**Comment by Panderner** [comment]
can you upload the save state? for that part before freezes.

**Comment by fahadrashid7705** [comment]
ok

**Comment by fahadrashid7705** [comment]
https://drive.google.com/file/d/1lEF_iFJ588orc89q8huXZOFcX09pIb5i/view?usp=drivesdk

**Comment by Panderner** [comment]
@fahadrashid7705 what phone are you using?

**Comment by fahadrashid7705** [comment]
Symphony z8

**Comment by Panderner** [comment]
My phone is Realme C2, Mediatek Helio P22, PowerVR GE8320 and running on Android 9 Pie. for me it doesn't crash on Metal Slug 6 In Mission 3 before the boss fight.

**Comment by fahadrashid7705** [comment]
🤔🤔🤔 i am facing this issue

**Comment by Panderner** [comment]
Can you beat mission 3 without using save state?

**Comment by fahadrashid7705** [comment]
i am copy this save state end test in my pc , stiil having the same problem

**Comment by fahadrashid7705** [comment]
Yes without using the save state the game freezes too

**Comment by Panderner** [comment]
it's seems maybe your ISO is corrupted.

**Comment by fahadrashid7705** [comment]
Maybe this iso not corrupted because other m slug series good working

**Comment by Gamemulatorer** [comment]
> Maybe this iso not corrupted because other m slug series good working

Check the crc,size and region of your iso if still crash maybe your ISO is likely corrupted

**Comment by Panderner** [comment]
This is a save state related issue, save state results this what happens when i went to the sewers before boss fight in mission 3:

Before Chosing Metal Slug 6: Freeze
After Chosing Metal Slug 6: Doesn't Freeze.

**Comment by Panderner** [comment]
For me it doesn't crash for sewers before mission 3 boss without using save state

**Comment by fahadrashid7705** [comment]
ok let me check , i am inform you

**Comment by fahadrashid7705** [comment]
yes you re right ths rigion is the big problem, europe region works properly , thankyou

**Comment by fahadrashid7705** [comment]
Wait a minute bro , game runs well but some screen line prob
