### ISSUE TITLE
Splinter cell essentials graphics issue 

### ISSUE THREAD

**Issue by fahadrashid7705** [hrydgard/ppsspp#13035]
### What happens?

Splinter cell assentials save state load crash emulator issue , and terrain texture missing issue . but the game runs smoothly in 30/30 fps .
### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Sd430 , adreno 505, android 6.0

**Comment by Gamemulatorer** [comment]
Show some screenshots for the graphics issue
Also get a dump http://ppsspp-debugger.unknownbrackets.org/gpu
So that PPSSPP devs can easily see what is wrong/issue.

**Comment by fahadrashid7705** [comment]
sorry everytime i create dump , devolapers says my dump is blank. i send some screenshort wait

**Comment by fahadrashid7705** [comment]
[ULUS10070_0001.zip](https://github.com/hrydgard/ppsspp/files/4805355/ULUS10070_0001.zip)

**Comment by Gamemulatorer** [comment]
What this look like in real hardware?
![Screenshot_2020-06-19-23-47-16](https://user-images.githubusercontent.com/37603562/85152229-55eac600-b287-11ea-9de3-24b359865507.png)
That's screenshot is from your dump.

**Comment by fahadrashid7705** [comment]
![Screenshot_20200619-234141](https://user-images.githubusercontent.com/56797244/85164933-de1c9b80-b286-11ea-8088-878ebc35b0cc.png)

**Comment by fahadrashid7705** [comment]
![Screenshot_20200619-234245](https://user-images.githubusercontent.com/56797244/85164979-ef65a800-b286-11ea-87a4-0bf602fd7d4c.png)

**Comment by fahadrashid7705** [comment]
![Screenshot_20200619-234153](https://user-images.githubusercontent.com/56797244/85165014-fd1b2d80-b286-11ea-9b41-f8516bbf886f.png)

**Comment by fahadrashid7705** [comment]
![Screenshot_20200619-234416](https://user-images.githubusercontent.com/56797244/85165055-0d330d00-b287-11ea-93a7-2a0f140002f6.png)

**Comment by fahadrashid7705** [comment]
Here is some glitch photo , sorry for my bad english

**Comment by Panderner** [comment]
@fahadrashid7705 do you have a Real PSP or PS Vita?

**Comment by fahadrashid7705** [comment]
no

**Comment by fahadrashid7705** [comment]
anyone tell me how t fixed this issue plz ?

**Comment by hrydgard** [comment]
Looks like it's possibly another range culling issue - might try to add this game to [DepthRangeHack] in compat.ini 

(should really make a separate entry for disabling range culling, if we can't just get it right)

**Comment by fahadrashid7705** [comment]
yes plz do something ,

**Comment by fahadrashid7705** [comment]
maybe i fix this issue

**Comment by fahadfoyjur** [comment]
I fix it now but old save state load the ppsspp crashed

**Comment by Panderner** [comment]
> I fix it now but old save state load the ppsspp crashed

have you updated the latest build?

**Comment by fahadrashid7705** [comment]
hrydgard can fix this issues and upload in build

**Comment by fahadrashid7705** [comment]
no

**Comment by hrydgard** [comment]
With #13817 merged, I'm moving this to 1.12.

However we need to figure out what we're missing with regards to range culling...

**Comment by unknownbrackets** [comment]
It looks the same on hardware.

![ULUS10070_#13035_splinter_cell_culling](https://user-images.githubusercontent.com/191233/107133137-f97dfa80-6899-11eb-8c3e-21bbb020dd85.png)

Here's software rendering:

![ULUS10070_#13035_splinter_cell_culling_softgpu](https://user-images.githubusercontent.com/191233/107133220-abb5c200-689a-11eb-9e20-1ff1d76f7e48.png)

And here's Vulkan:

![ULUS10070_#13035_splinter_cell_culling_vulkan](https://user-images.githubusercontent.com/191233/107133223-b1130c80-689a-11eb-86a7-44e8f0d0e384.png)

It could be a bug in the game, or it could be a bug somewhere else (say a CPU bug) in how the display list / data was generated.  Or even some sort of caching thing.

Normally if it was a guardband bug I'd expect it to look different on the PSP.

-[Unknown]

**Comment by unknownbrackets** [comment]
Is there any sort of demo for this game, or does anyone have this game and a PSP to validate if it's darker than it should be?

-[Unknown]

**Comment by ThirteenAG** [comment]
> Is there any sort of demo for this game, or does anyone have this game and a PSP to validate if it's darker than it should be?
> 
> -[Unknown]

Screen from PS Vita:

![2023-07-25-112916](https://user-images.githubusercontent.com/4904157/180736961-bbe8037a-4ed5-4fc0-8d2e-b3969e3653f3.jpg)

**Comment by Gamemulatorer** [comment]
How about this now after https://github.com/hrydgard/ppsspp/pull/16142

**Comment by hrydgard** [comment]
Let's assume it's ended up fixed :)

**Comment by hrydgard** [comment]
@antipirgos on what device? Vulkan or OpenGL or D3D? A [GE frame dump](https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump) would be helpful too.

**Comment by hrydgard** [comment]
Actually I'll open a new issue.
