### ISSUE TITLE
Locale parsing not quite working on Ubuntu 20.04

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#13042]
No idea if this is new for 20.04, but looking in System Information I see locale = `LC_TYPE=en_US`, which is not really a useful locale for choosing a language. Only the `en_US` part should be there.

The reason is that the parsing we do in SDLMain.cpp fails to handle the following return value from setlocale():

```
LC_CTYPE=en_US.UTF-8;LC_NUMERIC=sv_SE.UTF-8;LC_TIME=sv_SE.UTF-8;LC_COLLATE=en_US.UTF-8;LC_MONETARY=sv_SE.UTF-8;LC_MESSAGES=en_US.UTF-8;LC_PAPER=sv_SE.UTF-8;LC_NAME=sv_SE.UTF-8;LC_ADDRESS=sv_SE.UTF-8;LC_TELEPHONE=sv_SE.UTF-8;LC_MEASUREMENT=sv_SE.UTF-8;LC_IDENTIFICATION=sv_SE.UTF-8
```

So I guess we should take this apart and pick out the LC_MESSAGES value.

**Comment by unknownbrackets** [comment]
This may be fixed now, but probably best to validate in context.

-[Unknown]

**Comment by hrydgard** [comment]
Confirmed fixed, closing.
