### ISSUE TITLE
[Android] [OpenGL] [Not Enough FPS] Beowulf is very slow @2X+ resolution but running smooth @1x

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#13040]
### What happens?
The game Beowulf running very slow using default settings @2X resolution even though the game fps is cap only @20/20fps
![Screenshot_2020-06-21-16-47-15](https://user-images.githubusercontent.com/37603562/85220672-0cfa5500-b3e0-11ea-90a3-e69059d9f89f.png)

### What *should* happen?
Game should run smooth using default settings

### Log
[beowulf_logcat.txt](https://github.com/hrydgard/ppsspp/files/4809208/beowulf_logcat.txt)

Ge dump
[beowulf.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/4809218/beowulf.ppdmp.zip)

Device Information
[device_info.txt](https://github.com/hrydgard/ppsspp/files/4809219/device_info.txt)

**Comment by Panderner** [comment]
it runs smoothly for me in 2x Resolution. I'm running Realme C2 3+32 model running Android 9 Pie.

**Comment by Panderner** [comment]
But your device is not powerful enough to run this game full speed in 2x resolution @Gamemulatorer

**Comment by hrydgard** [comment]
Seems to be a device power issue, unclear what can be done, closing.

**Comment by Gamemulatorer** [comment]
This issue also happen on Mali-T720T gpu :/
