### ISSUE TITLE
Resistance: Retribution crashes at the cutscene

### ISSUE THREAD

**Issue by NickDudeW** [hrydgard/ppsspp#13046]
### What happens?
Game freezes and then crashes at this moment: https://youtu.be/qGWEA15tMB0?list=PLzEYfnR7HaZHStEa6XMhZ0gw3SuZcgkXM&t=2607

![1](https://user-images.githubusercontent.com/41573059/85394200-e3176e80-b556-11ea-9c19-89ba14352a4e.png)

Turning off the subtitles did not help.
Log: [ppsspplog.txt](https://github.com/hrydgard/ppsspp/files/4818820/ppsspplog.txt)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Ryzen 5 2600, Windows 10, GTX 1060, Direct3D 11
Latest version v1.9.3-1056-g4bcd8df07

**Comment by Panderner** [comment]
Duplicate of #4626

**Comment by NickDudeW** [comment]
Sorry, didn't notice
