### ISSUE TITLE
Need for Underground crashes when selecting some game modes

### ISSUE THREAD

**Issue by Z3ph7r** [hrydgard/ppsspp#13045]
## What happens?
Game crashes when selecting any mode except Street cross, Drift and Circuit+Lap KO on Novice

### What *should* happen?
these modes should be playable

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
HP Pavilion 14
CPU: i5-4200U 1.60 Ghz
GPU: Intel HD
RAM: 4GB DDR3
OS: Win10 64

Tried the latest git build (Default settings) and some old versions too. Also changed the backend(OpenGL and D3D) but the problem remains. Circuit races from novice works perfectly.

**Comment by Panderner** [comment]
I've tested these modes it never crashed for me running on my Android phone.

**Comment by Panderner** [comment]
> couldn't try the Nitrous Run for now.

in order to play nitrous run you need to buy a nitro upgrade in pocket garage.

**Comment by Z3ph7r** [comment]
> > couldn't try the Nitrous Run for now.
> 
> in order to play nitrous run you need to buy a nitro upgrade in pocket garage.

yes that's why put this as i couldn't test that rn

**Comment by Panderner** [comment]
> couldn't try the Nitrous Run for now.

and why you can't try the Nitrous Run?
select quick play battle and choose Nitrous Run.

**Comment by Z3ph7r** [comment]
Anyway i tried Nitrous Run and it worked. so i'm removing it from the issue

**Comment by Panderner** [comment]
> so i'm removing it from the issue

don't remove this issue just close this issue instead

**Comment by Z3ph7r** [comment]
> don't remove this issue just close this issue instead
What why? there are other modes i mentioned here. we can forget about Nitrous Run
> Game crashes when selecting any mode except Street cross, Drift and Circuit+Lap KO on Novice

**Comment by hrydgard** [comment]
I'm confused. If it crashes, it's either a bug or a bad ISO file. In the former case, this should probably be left open?

**Comment by Z3ph7r** [comment]
Never mind i tried another region version which worked. first one probably was a bad iso. Sorry to bother you guys. Thanks for the support and i'm closing this.
