### ISSUE TITLE
Duplicate Frames to 60Hz prevents drawing in GTA

### ISSUE THREAD

**Issue by DavidTamas** [hrydgard/ppsspp#13068]
### What happens?
When the "Duplicate Frames to 60Hz" option is enabled, the emulator stops drawing frames in GTA LCS and VCS. The game is still running because I can move around, shoot and hear the sound of all of that. The pause menu of the games are drawn correctly, but only if a frame had been correctly drawn before enabling the 60Hz option.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
OS: Windows 10 (x64)
GPU: GeForce GTX 1060 3GB
PPSSPP: v1.10 (x64)
Backend: OpenGL / Vulkan / Direct3D 11
VSync: Enabled

**Comment by hrydgard** [comment]
I cannot seem to repro this, weirdly. Wonder if it's an interaction with another setting too?

**Comment by DavidTamas** [comment]
[ppsspp.zip](https://github.com/hrydgard/ppsspp/files/4842909/ppsspp.zip)
Here's my configuration.

**Comment by hrydgard** [comment]
That does actually repro if I switch to Vulkan. Thanks! But very weird... 

Since it uses the same mechanism to force 60fps rendering, the post processing effect CRT Scanlines also has the same behavior.

**Comment by hrydgard** [comment]
Aha, you had Frameskipping set to 1. That together with DuplicateFrames confuses things badly. 

I'm going to make DuplicateFrames only available if Frameskipping is 0.
