### ISSUE TITLE
Analog reversed in menu

### ISSUE THREAD

**Issue by NeonLightning** [hrydgard/ppsspp#13062]
### What happens?
analog stick up and down in ppsspp menu is reversed.

### What *should* happen?
not be reversed?

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Odroid Go Advance V1.0(aarch64), Retroroller(arch),latest git as of posted. and it's a handheld device

**Comment by DavidTamas** [comment]
Same. Analog controls in PPSSPP menus are reversed. W10, DualShock 4.

**Comment by hrydgard** [comment]
This is an annoying recurring problem that I still don't understand the root cause of. At this point I'm considering just adding an option to reverse the Y axis in menus... Though it really shouldn't be required.

**Comment by NeonLightning** [comment]
or be able to disable the analog in menu  would be sufficient aswell as reversing it.

**Comment by hrydgard** [comment]
Well for that, just don't use it and use the arrows instead?

**Comment by edale2** [comment]
I have this issue as well.
Even when I remap the controls so up and down on the analog work correctly in-game, they're still reversed in the menus.

When I go to 'test analog' it shows as up and down reversed.

That option to reverse the Y axis would be quite helpful for those of us trying to use PPSSPP with a DS4 controller.

I'm not using ds4windows, or any other interpreter program, just whatever setup is built into windows 10 to support DS4 controllers.

**Comment by emuchicken** [comment]
I also have this issue, but with pads on an Android TV box.  
I found the issue is when using X-Input.  D-Input no longer has the issue (can change this easily on a Logitech pad)

Id like to add another suggestion- having *reset to default* in a place that doesn't require you to push UP.  I've had multiple times were I simply couldn't push that as UP isn't set - even with a keyboard.  - maybe a keyboard bind would be helpful.

**Comment by unknownbrackets** [comment]
If you configure the analog the right way, this should now reverse automatically.

-[Unknown]

**Comment by hrydgard** [comment]
This should be fixed now, both by #14346 and also #14596.
