### ISSUE TITLE
Not handling VK_ERROR_OUT_OF_DATE properly

### ISSUE THREAD

**Issue by jekstrand** [hrydgard/ppsspp#13060]
### What happens?

Running PPSSPP on Gnome Wayland with Intel, it receives a `VK_ERROR_OUT_OF_DATE` which it fails to handle correctly.  The app doesn't crash but it also doesn't resize and re-create the swapchain as needed.  I'm not sure exactly what it does but the result is a black screen that mostly covers the window.

The problem is a race that happens as part of the full-screen process where the swapchain gets created 3200x1672 but, by the time vkQueuePresent gets called, the window is 3200x1800. Sadly, such races are all too common with full-screen. For some reason, runing it in GDB causes just enough of a delay somewhere that the race doesn't happen and it starts up just fine. :frowning:

Yes, we (the Mesa drivers) return `VK_ERROR_OUT_OF_DATE` for this rather than `VK_SUBOPTIMAL_KHR` here because it's not a case where the user is really served by the app ignoring the error and continuing.  If the swapchain is the wrong size to fit the window you really do want to re-create it.

### What *should* happen?

Upon receiving `VK_ERROR_OUT_OF_DATE`, the app should call `vkGetSurfaceCapabilitiesKHR` to re-query the size of the window, re-create the swapchain, and attempt to continue.  It's possible the race could happen multiple times so it needs to do so in a loop.  If you get a large number (say 10) back-to-back `VK_ERROR_OUT_OF_DATE_KHR` returns, that might indicate a real problem that should be addressed.  However, one or two during the full-screen process is unsurprising.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

OS: Linux, Fedora 32
Hardware: Intel HD graphics 5500

**Comment by hrydgard** [comment]
So question - do you return VK_ERROR_OUT_OF_DATE from`vkAcquireNextImageKHR` or from `vkQueuePresentKHR` ? We do react to it but only when it's coming from `vkAcquireNextImageKHR` currently - we ignore it from vkQueuePresentKHR.

But surely if vkQueuePresentKHR returns VK_ERROR_OUT_OF_DATE, the next vkAcquireNextImageKHR should, too?

**Comment by hrydgard** [comment]
As a quick test, could you try to increment `outOfDateFrames_` in the VK_ERROR_OUT_OF_DATE case after vkQueuePresent in VulkanRenderManager.cpp ?

I should probably also try to get wayland going on my laptop...

**Comment by hrydgard** [comment]
@jekstrand  I merged #13066 , could you test again on your machine?

**Comment by hrydgard** [comment]
Confirmed a while ago that this is working but forgot to close the issue. So here we go.
