### ISSUE TITLE
The stable version compiled from source code doesn't show its version number

### ISSUE THREAD

**Issue by TotalCaesar659** [hrydgard/ppsspp#13083]
### What happens?
The stable version compiled from [source code](https://github.com/hrydgard/ppsspp/releases/tag/v1.10) doesn't show its version number replaced by "unknown".
![1](https://user-images.githubusercontent.com/14265316/86422037-97965a80-bce4-11ea-8aff-8c3d7f6fef57.png)

### What *should* happen?
It has to show 1.10 version number.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Lubuntu 20.04, PPSSPP 1.10.

**Comment by unknownbrackets** [comment]
You must use git to get the version number.  If you're downloading some tarball from somewhere, that will not get the version number.

The tarball is just taken from the git code and is a snapshot of the source code, automatically generated by GitHub.  It does not include the version number.

-[Unknown]

**Comment by TotalCaesar659** [comment]
@unknownbrackets OK, but is there any way to compile stable version with git, not latest nightly build? Should I create new ticket or this will not be implemented?
Yes, you may answer something like "Why do you want to seat on old things? Latest build is more polished and updated", but I just don't want to compile another build after any regression. And I like simple pretty number in "About" window :-)

**Comment by unknownbrackets** [comment]
You can clone / checkout a specific tag.  For example:

```bash
git clone https://github.com/hrydgard/ppsspp.git --branch v1.10.1 --depth 1 --recurse-submodules --shallow-submodules
```

This will clone only v1.10.1 and its submodules.  You won't even get the latest commits, and it will skip downloading old data where it can.

From my perspective, this is superior to the tarball download because you don't need to separately hunt down the submodules, and it will do basic hash validation to verify the downloads and guard against disk corruption.

If you already have a clone with history, of course, you can just do:

```bash
git checkout v1.10.1
git submodule update --init --recursive
```

To go to any specific stable release.

-[Unknown]

**Comment by unknownbrackets** [comment]
Oh and lastly, if you're really against git being anywhere near your stable build, you can patch the git-version.cpp file.

```c++
const char *PPSSPP_GIT_VERSION = "v1.10.1"; 
// Don't update this file on compile.
#define PPSSPP_GIT_VERSION_NO_UPDATE 1
```

That said, I still personally find using git to be superior.

-[Unknown]

**Comment by TotalCaesar659** [comment]
I'm not against git, I just don't know it well yet and used to compile with tarballs. Thank you very much for both ways!
