### ISSUE TITLE
Unification default resolution on Windows and Linux

### ISSUE THREAD

**Issue by TotalCaesar659** [hrydgard/ppsspp#13086]
Rendering resolution is set on "Auto (1:1)" by default in Windows version.
![1](https://user-images.githubusercontent.com/14265316/86497590-f44c5080-bd8a-11ea-9247-04fcfe13bb32.png)
But on Linux, it is "1xPSP" by default, so I have to switch it manually for getting best picture in 2x window.
![0](https://user-images.githubusercontent.com/14265316/86497625-1514a600-bd8b-11ea-9bf4-7b98be54d174.png)

**Comment by unknownbrackets** [comment]
We can change it in Config.cpp:

```c++
static int DefaultInternalResolution() {
	// Auto on Windows, 2x on large screens, 1x elsewhere.
#if defined(USING_WIN_UI)
```

Just add `|| defined(USING_QT_UI)`.

-[Unknown]

**Comment by TotalCaesar659** [comment]
Thank you very much! Fixed in https://github.com/hrydgard/ppsspp/pull/13087.
