### ISSUE TITLE
Shin budokai Another Road slowing down on intro

### ISSUE THREAD

**Issue by boy13epic** [hrydgard/ppsspp#13089]
### What happens?
the intro lags

### What *should* happen?
run full speed

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
iPad 6 JIT,iOS and 1.10.1

**Comment by HiImBrala** [comment]
Settings > Tools > Developer Tools > Make sure Save New Textures is OFF

**Comment by boy13epic** [comment]
thanks
