### ISSUE TITLE
(UWP) Audio Issues - choppy sound on UWP, appears to be a buffering issue

### ISSUE THREAD

**Issue by dominater01** [hrydgard/ppsspp#13080]
for awhile now the audio has slowed down but gameplay is full speed, at some point it broke but was never fixed, not sure what the issue is but im hoping someone can look into it

**Comment by unknownbrackets** [comment]
Is it possible to try old versions and determine when it broke?

-[Unknown]

**Comment by dominater01** [comment]
all i know is the audio was fine on build 1.9.3-281 and was broken on 1.9.3-973

so somewhere between there sorry i cant narrow it down but those are the only builds i compiled

**Comment by dominater01** [comment]
this is still happening on build 1.10.3-1005
