### ISSUE TITLE
[Unsure]Surf's Up - Sound too quiet

### ISSUE THREAD

**Issue by ghost** [hrydgard/ppsspp#13088]
Hello,not sure if this is bug or not,but originally i didn't want to report this,it didn't mean much to me and it wasn't so gamebreaking,decided to do anyways because @Abbanon told me it is not good practice to do this,ditching possible bug,so here i want to report that they are lot of sound cracks,almost like lags when switching maps and menus,pretty sure that they don't happen because of 31/30 thing,more like 27/30 that second because it goes really slow and stuff,with music and all OST overall too quiet,happens on both PC and Phone,on Phone it is not because of the sound settings,same on PC

**Comment by Panderner** [comment]
@HiImBrala it's seems the game volume is too low. make sure you set the max volume in game's audio options

**Comment by HiImBrala** [comment]
Hi,settings are max in PPSSPP

-This is sent by CP BOT

**Comment by Panderner** [comment]
For me i can hear the sound louder in max volume. it's not a bug.

**Comment by hrydgard** [comment]
Let's merge this with #13148.
