### ISSUE TITLE
When ppsspp runs "Yu-Gi-Oh! Arc-v tag force special CHS 1.0", some operations will cause ppsspp to crash.

### ISSUE THREAD

**Issue by a65090482** [hrydgard/ppsspp#13097]
### What happens?
When you run "Yu-Gi-Oh! Arc-v tag force special CHS 1.0" in ppsspp, you will crash when you perform some operations. Known: from the hand, usually summon monsters. Set up the card. From the hand, activate the magic card; I don't know if there are any more actions that will cause ppsspp to crash.
It seems that any change in Settings will cause PPSSPP to crash.
Original text:
在ppsspp中运行“Yu-Gi-Oh! ARC-V Tag Force SPECIAL CHS 1.0”，执行一些操作时，便会发生崩溃。已知的有：从手牌中，通常召唤怪兽。设置卡片。从手牌中，发动魔法卡；我不知道还有没有更多的会导致ppsspp崩溃的操作。
似乎，再怎么更改“设置”都会导致崩溃。

### What *should* happen?
Ppspp stops working or ppsspp black screen.
Original text:
ppsspp停止工作或ppsspp黑屏。

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Intel(R) Pentium(R) CPU G630
8 GB
Windows 7 Unlimited (64 Bit)
1.10
Intel HD Graphics 1000

![ppsspp crashed](https://user-images.githubusercontent.com/12964634/86531398-558f3380-bef3-11ea-8915-34b11eec61ca.jpg)
[NPJH00142_1.01_0.zip](https://github.com/hrydgard/ppsspp/files/4874812/NPJH00142_1.01_0.zip)

**Comment by Gamemulatorer** [comment]
Try ppsspp latest git build https://buildbot.orphis.net/ppsspp/

**Comment by Gamemulatorer** [comment]
> The game download link: http://k73dx2.zxclqw.com/k73.com_Yu_Gi_Oh_ARC_V_TFS_CHS_psp.zip
@a65090482 game link is prohibited on ppsspp github

**Comment by a65090482** [comment]
> > 游戏下载链接：（删除）
> 
> 在ppsspp github上禁止使用@ a65090482游戏链接。

All right.

**Comment by Gamemulatorer** [comment]
Any update about this?

**Comment by unknownbrackets** [comment]
The latest version should at least show a blue screen instead of crashing, in most cases.

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
