### ISSUE TITLE
Nothing happens when pressing "Enable chat" in menu

### ISSUE THREAD

**Issue by TotalCaesar659** [hrydgard/ppsspp#13090]
When pressing "Game settings" - "Enable chat" in menu on Windows and Linux version, nothing happens if "Enable network chat" in settings is disabled. There are 2 ways for it:
1) to make this menu point inactive when "Enable network chat" in settings is disabled;
2) to add pop-up dialog like "Network chat is disabled in settings. Do you want to enable it? Yes/No".

Feel free to choose one or propose yours.

**Comment by unknownbrackets** [comment]
In the latest git builds, the menu option changes between "Open Chat" and "Enable Chat".  When you press, it both turns on chat and shows the chat box, without any confirmation prompt.

-[Unknown]
