### ISSUE TITLE
Asphalt Urban GT 2 not booting up

### ISSUE THREAD

**Issue by boy13epic** [hrydgard/ppsspp#13108]
### What happens?
the game stays at a black screen

### What *should* happen?
game boots up

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
IPad 6 JIT,iOS and ppsspp 1.10.2-1

**Comment by Panderner** [comment]
@boy13epic is this your ISO is Likely to be corrupted. Make sure your ISO is not corrupted.

**Comment by Panderner** [comment]
Works fine for me with my ISO is not corrupted but your ISO is not corrupted right @boy13epic?

**Comment by boy13epic** [comment]
i did not test

**Comment by boy13epic** [comment]
ohhhhh waittttttt

**Comment by boy13epic** [comment]
it was not corrupt

**Comment by boy13epic** [comment]
but it did not boot

**Comment by Panderner** [comment]
but i mean your ISO is corrupted

**Comment by Gamemulatorer** [comment]
This is an ISO issue not ppsspp

**Comment by hrydgard** [comment]
Gonna have to close this I think. Please try to re-dump the ISO from the disc and see if that helps. If not, please reopen.
