### ISSUE TITLE
Naruto Shippuden Graphical Issue on PPSSPP v1.10.2

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#13103]
### What happens?
Graphics Glitch as you can see using default settings
![Screenshot_2020-07-07-18-14-00](https://user-images.githubusercontent.com/37603562/86767109-14775a80-c07e-11ea-8bac-0bb7303747e6.png)

### What *should* happen?
No graphics glitch?

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Mali-450 GPU
PPSSPP v1.10.2

GE dump & Settings
[ULES01537.zip](https://github.com/hrydgard/ppsspp/files/4884160/ULES01537.zip)

**Comment by Saramagrean** [comment]
It cause graphic glitch, if u disable "Simulate block transfer effects" in-game.

**Comment by Gamemulatorer** [comment]
> It cause graphic glitch, if u disable "Simulate block transfer effects" in-game.

PPSSPP v1.9.4
![Screenshot_2020-07-07-20-18-37](https://user-images.githubusercontent.com/37603562/86780345-3e854880-c08f-11ea-9435-f2eb1bfea806.png)

**Comment by Gamemulatorer** [comment]
I try v1.10.3-66-g9ebb402e4 seems the issue is fixed even if I enable/disable block transfer effects ingame.
![Screenshot_2020-07-14-12-40-11](https://user-images.githubusercontent.com/37603562/87384978-a24bcc00-c5cf-11ea-9c35-9788594ebe4f.png)
