### ISSUE TITLE
Libretro build failure (IMFSourceReaderCallback)

### ISSUE THREAD

**Issue by twinaphex** [hrydgard/ppsspp#13116]
Hi there,

the libretro build cannot currently compile on Windows because of this -

cl.exe -DWINAPI_FAMILY=WINAPI_FAMILY_DESKTOP_APP -D_UNICODE -DUNICODE -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 -nologo -EHsc -O2 -D_NDEBUG  -D__LIBRETRO__ -DPPSSPP -DUSE_FFMPEG -DGLEW_STATIC -DGLEW_NO_GLU  -I../ffmpeg/Windows/x86_64/include -I. -I.. -I../Common -I../libretro -I../ext/glslang -I../ext/native -I../ext/zlib -I../ext/snappy -I../ffmpeg  -I../ffmpeg/Windows/x86_64/include -I../ext/cityhash -I../ext/armips -I../ext/native/ext -I../ext/native -I../ext/native/ext/libpng17 -I../ext/libkirk -I../ext/xbrz -I../ext/xxhash -I../ext/glew -I../dx9sdk/Include -I../dx9sdk/Include/DX11      -D_M_IX86_FP -D_M_X64 -D_ARCH_64 -DHAVE_OPENGL  -DDYNAREC -c -Fo../Core/HW/MpegDemux.o ../Core/HW/MpegDemux.cpp
MpegDemux.cpp
..\Windows/CaptureDevice.h(107): error C2504: 'IMFSourceReaderCallback': base class undefined

Can we stub these capturedevice codepaths out for now for the libretro port?

**Comment by twinaphex** [comment]
Here's my current solution for this -

https://github.com/hrydgard/ppsspp/pull/13117

**Comment by hrydgard** [comment]
Merged that, so closing this.
