### ISSUE TITLE
[Android][OpenGL]Eragon can't reach 60FPS - 1.10.2

### ISSUE THREAD

**Issue by EX-e-LD** [hrydgard/ppsspp#13112]
### What happens?
Game doesn't reach 30FPS.Rendering Resolution 1x doesn't help at all,i'm not sure if it is issue of my device's power or backend.I tested on my neighour's PC at OpenGL backend,and it didn't lag,so i'm lost at this point

### What *should* happen?
Game should reach 30FPS.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Phone:Honor9S
CPU:Mediatek MT6762R Helio P22
GPU:PowerVR GE8320
PPSSPP 1.10.2 from Google Play Store

**Comment by Panderner** [comment]
it's a not bug due to fact this game is running at 60 FPS in-game without using cheats or underclocking the CPU. For me this game smoothly on my phone with Helio P22.

**Comment by EX-e-LD** [comment]
Are you sure,game lags here,i will investigate this further.Is there anything i can do to help developers to fix issue?Like some log of game or something if it exists here on this Emulator

**Comment by Panderner** [comment]
Have you lowered the resolution? The game runs smoothly on my Realme C2 Phone in 1x resolution. @EX-e-LD your phone is the same CPU on my phone

**Comment by EX-e-LD** [comment]
> Have you lowered the resolution? The game runs smoothly on my Realme C2 Phone in 1x resolution. @EX-e-LD your phone is the same CPU on my phone

Sorry for wrong reply,i tried and while it was smoother a bit,it wasn't 60/60,and it didn't really improve much.

**Comment by Panderner** [comment]
![Screenshot_2020-07-10-20-41-18-25_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/87155756-19424580-c2ee-11ea-9e26-eb772e9acbe9.png)
![Screenshot_2020-07-10-20-42-59-36_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/87155775-25c69e00-c2ee-11ea-9ada-b93d93ff125f.png)
![Screenshot_2020-07-10-20-41-05-55_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/87155803-324af680-c2ee-11ea-9452-78f8a74d1689.png)
I've tested this game Running on 3GB RAM model of Realme C2 and this game runs smoothly on 2x but some dips in-game and cutscenes. Your phone is a same CPU of my phone but your phone is only 2GB RAM.

**Comment by EX-e-LD** [comment]
Well,should i close this or should i wait developer's opinion?

**Comment by unknownbrackets** [comment]
Could you try exporting a GE frame dump?  Just make sure to export it when you see the lower performance - it's almost like a screenshot.  If you make it while the FPS is good, it won't help.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

Can't promise there's anything we can do on that device, but a GE dump will give us an idea.

-[Unknown]

**Comment by EX-e-LD** [comment]
Thanks,i will drop it here now or by evening,busy atm.

**Comment by EX-e-LD** [comment]
Hi,me again.Here is dump of the game exactly like you asked.

[recording.zip](https://github.com/hrydgard/ppsspp/files/4907464/recording.zip)

**Comment by Gamemulatorer** [comment]
This is a device power issue not a ppsspp issue
![Screenshot_2020-07-12-10-50-06](https://user-images.githubusercontent.com/37603562/87237838-84466600-c42d-11ea-8bc0-98c36d1353bb.png)

**Comment by Panderner** [comment]
> This is a device power issue not a ppsspp issue
> ![Screenshot_2020-07-12-10-50-06](https://user-images.githubusercontent.com/37603562/87237838-84466600-c42d-11ea-8bc0-98c36d1353bb.png)

@Gamemulatorer What Device are you using? and Have you tried to lower the resolution to 1x?

**Comment by EX-e-LD** [comment]
@Panderner I have one guy as friend in phone center,i will ask him for errand to give me phone with Helio P22 and i will reply outcome here

**Comment by EX-e-LD** [comment]
@Panderner @unknownbrackets 
Hi,me again.I tested Xiaomi Redmi 6 3/32 RAM/ROM and things weren't so bright.Lag was still there even with 1x.Now i'm wondering is this really device power issue or emulator issue itself?I'm confused at this point,if anyone can point me in right direction,thank you.

TIA

**Comment by Panderner** [comment]
@EX-e-LD have you updated to Latest PPSSPP Build?

**Comment by EX-e-LD** [comment]
> @EX-e-LD have you updated to Latest PPSSPP Build?

I prefer stable ones,but i went all out at friend's and Redmi 6 phones

**Comment by Gamemulatorer** [comment]
Try that game on snapdragon cpu phone i.e SD450 and see if it still lag.

**Comment by EX-e-LD** [comment]
> Try that game on snapdragon cpu phone i.e SD450 and see if it still lag.

Hi,me again.I don't want to sound rude,but how do you expect me to throw this phone away and buy flagship.Excuse me,but money doesn't grow on trees,and if @Panderner ran it totally good on same GPU,it is probably a bug.

**Comment by Gamemulatorer** [comment]
> if @Panderner ran it totally good on same GPU,it is probably a bug.

Your phone cpu has a problem also SD450 is just a entry level phone not a highend phone 😅

**Comment by Panderner** [comment]
My phone supports 64-bit apps so i can launch dolphin and citra but it's super slow. Realme C2 is running on 64-bit version of Android

**Comment by EX-e-LD** [comment]
Wait,if **my** phone CPU has bugs,how come freshly opened Redmi 6 has bugs,while Panderner's same CPU doesn't lag?I don't want to sound rude,but this is mildly annoying.

**Comment by EX-e-LD** [comment]
> > if @Panderner ran it totally good on same GPU,it is probably a bug.
> 
> Your phone cpu has a problem also SD450 is just a entry level phone not a highend phone

Sorry,i apologize,i misread this.I thought you said SD800+

**Comment by Panderner** [comment]
> while Panderner's same CPU doesn't lag?

Maybe you used battery saving mode which is decrease game performance but it saves battery.

**Comment by EX-e-LD** [comment]
> > while Panderner's same CPU doesn't lag?
> 
> Maybe you used battery saving mode which is decrease game performance but it saves battery.

Nope,no sustained performance or battery saving mode.

**Comment by Panderner** [comment]
@EX-e-LD due to likely your phone refresh rate issue.

**Comment by EX-e-LD** [comment]
I can't really tell about it,but if developers would like to look into this it would be great.

**Comment by Panderner** [comment]
@EX-e-LD check your phone refresh rate and screenshot it

**Comment by Gamemulatorer** [comment]
> @EX-e-LD check your phone refresh rate and screenshot it

I agree with Panderner better to show your phone refresh rate this issue is most likely in Ninja Turtle.

**Comment by EX-e-LD** [comment]
> > @EX-e-LD check your phone refresh rate and screenshot it
> 
> I agree with Panderner better to show your phone refresh rate this issue is most likely the same in Teenage Mutant Ninja Turtles #13161

If you haven't read,happened on my PC too.How does that explain framerate?

TIA

**Comment by Panderner** [comment]
> > > @EX-e-LD check your phone refresh rate and screenshot it
> > 
> > 
> > I agree with Panderner better to show your phone refresh rate this issue is most likely the same in Teenage Mutant Ninja Turtles #13161
> 
> If you haven't read,happened on my PC too.How does that explain framerate?
> 
> TIA

Go to Tools/System Information and look for display information.

See? it's a refresh rate.
![IMG_20200720_124556](https://user-images.githubusercontent.com/37503397/87900482-0dd9e180-ca87-11ea-8b87-59a9a82ec181.jpg)

**Comment by EX-e-LD** [comment]
It is same as yours,so what now?Any more ideas?

**Comment by Panderner** [comment]
> It is same as yours,so what now?Any more ideas?

@EX-e-LD send me your Screenshot of refresh rate of your phone.

**Comment by EX-e-LD** [comment]
![Screenshot_2020-07-20-09-27-32-353_org ppsspp ppssppgold](https://user-images.githubusercontent.com/67833785/87911152-6f8c5280-ca6b-11ea-8b81-e118783975d8.png)

**Comment by EX-e-LD** [comment]
@Panderner 
![IMG_20200720_093017](https://user-images.githubusercontent.com/67833785/87911312-afebd080-ca6b-11ea-87b8-15a3fe5e4410.jpg)

**Comment by Panderner** [comment]
Good Job @EX-e-LD your phone is 60hz but how about the driver issue?

**Comment by EX-e-LD** [comment]
How would we exactly know,i run latest updates,so not exactly sure.I wish there was a way to check if it is.

**Comment by Panderner** [comment]
@EX-e-LD could you check the refresh rate of your phone in AIDA64?

**Comment by LunaMoo** [comment]
Drivers, bloatware(pre-installed services running in the background) and even OS settings differ between phones, even if they have same SOC or even if they are same model due to operators messing around a lot in that matter, so it's pretty normal for the performance to differ between different devices even if on paper they should be comparable. With battery powered potatoes even battery charge means a LOT to performance, as typically it's OS will degrade performance the lower the charge is.


 Also games which run at 60fps are typically much more demanding, commonly too demanding for phones even without doing any heavy special effects, so if you want to run it best thing you can try would be to find, request on forums or learn how to and create a 30fps patch which usually cut the requirements on both CPU and GPU side to half, or just use frameskip which is safer and easier, but will not affect cpu load much.

**Comment by Gamemulatorer** [comment]
this issue is a device power issue.

**Comment by Panderner** [comment]
> this issue is a device power issue.

or maybe a refresh rate issue

**Comment by EX-e-LD** [comment]
Well,closing this then.Thank you all who tried to solve this issue with me.

**Comment by Panderner** [comment]
> Well,closing this then.Thank you all who tried to solve this issue with me.

Wait @EX-e-LD check your phone refresh rate in AIDA64
