### ISSUE TITLE
[Android][OpenGL]Secret Agent Clank really laggy - 1.10.2

### ISSUE THREAD

**Issue by EX-e-LD** [hrydgard/ppsspp#13113]
### What happens?
Secret Agent Clank is really laggy.I reduced resolution to 1x,and PPSSPP is latest.Again,not sure if lag is caused by device or emulator bug.Interesting enough,my neighbor's PC using Direct3D11 is fine

### What *should* happen?
Secret Agent Clank should run properly at full speed,i think.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Phone:Honor9S
CPU:Mediatek MT6762R Helio P22
GPU:PowerVR GE8320

**Comment by Panderner** [comment]
Secret Agent Clank uses Same Engine for Ratchet and Clank: Size Matters. According to ETA Prime on YouTube, Ratchet and Clank: Size Matters Struggles on low end devices in 1x resolution without frame skip.

**Comment by EX-e-LD** [comment]
> Secret Agent Clank uses Same Engine for Ratchet and Clank: Size Matters. According to ETA Prime on YouTube, Ratchet and Clank: Size Matters Struggles on low end devices in 1x resolution without frame skip.

Should i close this then?

**Comment by Panderner** [comment]
> Should i close this then?

yes because your phone is not powerful enough to run this game at full speed without frameskip.

**Comment by Gamemulatorer** [comment]
This is a device power issue not a ppsspp issue 🤷
