### ISSUE TITLE
MGS Peace walker broken in retroarch core

### ISSUE THREAD

**Issue by kylebakerio** [hrydgard/ppsspp#13115]
### What happens?
Many missions are unplayable; basically any mission that has some item/weapon requirement. Even when you equip that item, the game will tell you you don't have the required item (e.g., 'A weapon is required for this mission' for any side-mission for target practice, or 'fulton recovery system is required for this mission' for fulton demo missions). This only becomes blocking once you get to the mission that requires C4, where even though I have developed it and equipped it, I cannot start the mission.

### What *should* happen?
This should be clear.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Oneplus 6T Android, stock, retroarch installed from play store, latest PPSSPP core (1.8.9, build updated today).

NOTE:
I downloaded and ran the latest PPSSPP on android itself to compare, with the same ROM, and the issue does not exist there. The problem is in the retroarch core. I'm reporting this here because when I asked on the retroarch discord where to report, they said here was the best place to do so. If I should report elsewhere, please let me know.

Thank you.

**Comment by fr500** [comment]
Wow, odd issue indeed

![imagen](https://user-images.githubusercontent.com/1721040/87104342-38bd6d80-c21d-11ea-8b58-a7769d86befb.png)

![imagen](https://user-images.githubusercontent.com/1721040/87104354-4115a880-c21d-11ea-99df-125e527c213d.png)

My save is from 2016, I just loaded it and tried to repro

**Comment by LunaMoo** [comment]
Not going to check third party frontends, but have 2 theories:
 - I recall they were disabling functions replacements which is bad and opposite to what happens in official PPSSPP where we only have an ini setting to disable it for testing, but it's on by default and required by some games to run correctly,
 - they might be running at incorrect speed to synchronize to common refresh rate of outdated fixed sync displays, doing so sure will improve experience of users with outdated lcd displays(which some of do have problems with PPSSPP), but would also cause timing issues in games that are sensitive for it, MGS PW is known to be broken by FPS cheats, so I'd say it's possibility here.

 Either way not an PPSSPP issue.

**Comment by fr500** [comment]
I tried with unsafe function replacements on/off but I have the theory that that option isn't working properly (maybe several)
would changing that on the fly work? or is it checked only at startup.

JIT on/off doesn't seem to affect speed so that's a hint at least.

**Comment by i30817** [comment]
This is a duplicate from a bug i reported (though maybe i reported on the libretro fork repo?) but this is already having much much more dev movement so i'm gonna close that now and post this to get notified here.

**Comment by kylebakerio** [comment]
Would be nice if there were a way to share savestates so you don't have to play for 25 minutes to get to the block, but yeah, I fired up ppsspp only to check the rom, which I initially assumed might be the source of the problem (being new to this scene). When I realized it worked, I just ran with that version instead and reported here.

**Comment by hrydgard** [comment]
Why wouldn't you be able to share savestates? They're just files (unless retroarch does something really weird).

**Comment by i30817** [comment]
I've noticed that some bugs just disappear sometimes with a normal save (a few years ago in persona 3 and some others), so i don't trust savestates. If you want to share, share the save OP (unless the game does something to prevent sharing saves).

**Comment by fr500** [comment]
@hrydgard the savestates are not really compatible, it doesn't use the internal api to get them and they are not going through snappy afaik, it's just a dump of the complete RAM

**Comment by kylebakerio** [comment]
That must be why the save states aren't working for ppsspp games in retroarch for me, then. :/

What's the best way to share a save? Basically any save file for metal gear where you've finished the first mission set and have access to the core game functionality you work with after starting a new game would work. I am 40 hours in on my ppsspp game now, but you would be able to see it there just as well I'm sure if it were opened in retroarch.

**Comment by fr500** [comment]
@kylebakerio you just need the folder under saves dir that holds the saves for each game.

**Comment by i30817** [comment]
Also if savestates aren't working at all, the culprit is likely to be either the chosen directory not having write permission or the chosen directory (in the config file, assuming 'write saves in game dir' option is not set) not existing.

**Comment by kylebakerio** [comment]
(save states worked fine, not sure if you're referring to some other general case for others, but being clear for me.)

**Comment by i30817** [comment]
> That must be why the save states aren't working for ppsspp games in retroarch for me, then. :/

**Comment by kylebakerio** [comment]
Sorry, misunderstanding replying quickly–in game saves worked, not "save states". My bad. I just remembered to get even that working I had to do stuff, thought that was misunderstood.

As for permissions, save states work fine for other cores, so I doubt permission errors were the culprit.

Using on Android, OnePlus 6T

**Comment by fr500** [comment]
does anyone know if this was fixed?

**Comment by fr500** [comment]
yeah still f'ed up

![image](https://user-images.githubusercontent.com/1721040/127788608-d8f9a4f6-4eb6-4548-ab0b-bddc2b7407c5.png)

**Comment by bslenul** [comment]
So, I found that the PS3 HD version had the same issue on RPCS3: https://github.com/RPCS3/rpcs3/issues/9095

Somehow related to MAC address, I'm not a dev but I've tried something stupid: adding `g_Config.sMACAddress = "12:34:56:78:9A:BC";` somewhere in "retro_init" (in libretro.cpp), and... it worked 😅 

Before:

https://user-images.githubusercontent.com/33353403/127837045-23a2eb15-2dc2-4ee0-a136-37264b1c5694.mp4

After:

https://user-images.githubusercontent.com/33353403/127837080-6e08bb26-b834-4d7d-b488-aaaac418a4b3.mp4

I won't make a PR tho, as I have absolutely no idea if it should be here, if it can break something, etc...

**Comment by unknownbrackets** [comment]
Well, retroarch should presumably either generate a random MAC or allow the user to customize it and regenerate a random MAC.  I think there's a couple games out there that even lock savedata to the MAC?

That said, given it's just blank I'm sure a pull request to do that would be better than current.  I don't see a major downside.

-[Unknown]

**Comment by i30817** [comment]
So it's just a bit of data in a config file that is not being filled automatically? Is there more data from where the core was supposed to pick that up that is missing?

**Comment by unknownbrackets** [comment]
Generally speaking, MAC addresses are like device serial numbers.  Because of the way they are assigned, it's pretty sure that every single PSP manufactured has its own unique MAC address in the hardware.  Actually, every device (including whatever you're using to read this) has its own unique MAC address.

They're often used to identify or tell devices apart (because they are long lived, unlike IP addresses.)  Some games even crash if certain bits are set in the MAC address that were never set that way on real PSPs.

Normally in PPSSPP, we generate a random (but valid) MAC address on first start.  However, because libretro (for some reason?) bypasses all our configuration initialization code, this doesn't happen there.  There's probably other things not initializing the Config class is doing wrong too.

-[Unknown]

**Comment by bslenul** [comment]
Thanks for the answer unknownbrackets! 👍 PR done.

**Comment by gouchi** [comment]
@bslenul So this issue should be closed now as the PR has been merged ?

@kylebakerio If it is the case please close this issue.

Thank you.

**Comment by kylebakerio** [comment]
Oh man, I only downloaded ppsspp to play this game. I beat it, then beat it again with my brother over a weekend or so, and haven't touched it since. I have moved through about 4 new linux installs since then and don't recall how to restart this, and would have to replay a new game until the point where the bug occurs.

Sorry. Was happy to report the bug, but I can't confirm it closed or not at this stage.

**Comment by bslenul** [comment]
> @bslenul So this issue should be closed now as the PR has been merged ?

Haven't tried every missions one by one tho (there are too many 😅 ) but AFAIK yes, it's fixed.

**Comment by kylebakerio** [comment]
Just testing that first mission 24 minutes in is likely sufficient to mark this as closed.

**Comment by gouchi** [comment]
@hrydgard @unknownbrackets May you close this issue ? Thank you.
