### ISSUE TITLE
[Feature Request]Make "Disable Slower Effects" visible on Android

### ISSUE THREAD

**Issue by EX-e-LD** [hrydgard/ppsspp#13114]
Hi,it is me again.I write for you to see this issue and think about adding Disable Slower Effects again.It fixes games like Ratchet & Clank:Size Matters,which breakes the game on Android,making game on PC stable

TIA

**Comment by unknownbrackets** [comment]
It is still an option on Android?

Disabling slower effects means it's using faster, but buggier, fallback code.  The slower effects are often needed to do things "properly" or to make drivers happy.  You may get different behavior on different devices with the setting disabled.

For example, some games draw in ways that are "illegal" in modern graphics APIs.  It wasn't illegal on the PSP, even if it was recommended against.  When "Disable slower effects" is off, we do extra work to change the game's effect to a legal effect.  But it's slower.

When "Disable slower effects" is on, we just send the "illegal" drawing commands straight to your graphics driver.  Some drivers will draw something weird or unexpected.  Other drivers will actually work fine.  Even others will just not draw it at all.

Sometimes, one of these effects are "desireable" to work around a bug.  But it's important to understand that it won't be consistent across devices.  It definitely may work different on PC than on Android.

-[Unknown]

**Comment by EX-e-LD** [comment]
Now i'm confused,is Ratchet And Clank games (including spin-off) really buggy on my phone to point where they lag.Should i open issue about it?

**Comment by EX-e-LD** [comment]
Oops,sorry,i didn't see it,thanks for lights up on this,i will close this issue right away
