### ISSUE TITLE
Yu-Gi-Oh! Tag Force 1/2/3/4/5/6/Arc-V TFS - Card names missing - 1.10.2

### ISSUE THREAD

**Issue by EX-e-LD** [hrydgard/ppsspp#13149]
Hi,*me again*.I found weird bug in Yu-Gi-Oh! games where when monster or spell is activated,names are missing,like this:
![Screenshot_2020-07-14-18-32-14-967_org ppsspp ppssppgold](https://user-images.githubusercontent.com/67833785/87451923-da1f3780-c600-11ea-8732-9e4571d0400a.png)

To be sure it is not device bug,i already tested on 3 different devices,and i hope this is something that can be fixed.

TIA

**Comment by Saramagrean** [comment]
Duplicate https://github.com/hrydgard/ppsspp/issues/7124 ?

**Comment by Gamemulatorer** [comment]
Hey before filing an issue please do a research of a pending issue about it.
This is a duplicate of #7124

**Comment by EX-e-LD** [comment]
Sorry,closing this.
