### ISSUE TITLE
F1 2009 with shaky fps

### ISSUE THREAD

**Issue by gianca54** [hrydgard/ppsspp#13140]

**Comment by Panderner** [comment]
Since the game runs at 60 FPS but Sometimes framedrops down to 30 FPS based on Default PSP CPU Clock. Have you overclock the CPU to 333MHz?

**Comment by Gamemulatorer** [comment]
I think this is a device power issue as noted in #11314
Huawei Y9 Prime SoC:
Octa Core CPU4x ARM Cortex-A73 @ 2.2GHz & @ 1.7GHz GPU ARM Mali-G51 MP4.

**Comment by gianca54** [comment]
> Since the game runs at 60 FPS but Sometimes framedrops down to 30 FPS based on Default PSP CPU Clock. Have you overclock the CPU to 333MHz?

It did not work, it is still the same, they need to limit the game to 30 fps so it would be better

**Comment by Gamemulatorer** [comment]
> It did not work, it is still the same, they need to limit the game to 30 fps so it would be better

@gianca54 what graphic backend are you using OGL or VK?

**Comment by gianca54** [comment]
Hi

> > It did not work, it is still the same, they need to limit the game to 30 fps so it would be better
> 
> @gianca54 what graphic backend are you using OGL or VK?
Works best with vulkan

**Comment by Panderner** [comment]
@gianca54 could you please send the screenshot in-game?

**Comment by gianca54** [comment]
> @gianca54 could you please send the screenshot in-game?

![Screenshot_20200714_113523_org ppsspp ppsspp](https://user-images.githubusercontent.com/68256365/87451899-25682480-c5c6-11ea-8827-b6d8c0e4dd35.jpg)
![Uploading Screenshot_20200714_113513_org.ppsspp.ppsspp.jpg…]()

**Comment by gianca54** [comment]
![Screenshot_20200714_113523_org ppsspp ppsspp](https://user-images.githubusercontent.com/68256365/88244225-cdca5880-cc58-11ea-9a63-5b26f2c05628.jpg)
![Uploading Screenshot_20200714_113513_org.ppsspp.ppsspp.jpg…]()

**Comment by Panderner** [comment]
@gianca54 could you lower the resolution?

**Comment by gianca54** [comment]
> @gianca54 could you lower the resolution?

Así la coloque en psp x1 sigue igual

**Comment by gianca54** [comment]
> @gianca54 could you lower the resolution?

So put it in psp x1 it stays the same

**Comment by Panderner** [comment]
and have you tried vulkan?

**Comment by gianca54** [comment]
> and have you tried vulkan?

Yes, I have it with 1 frame jump and with vulkan the problem is that in some parts the fps drop to 15, the good thing is that with the frame jump the speed of the game becomes stable and parts where it is supposed it goes at 60 fps it runs at 30 stable. The annoying thing is those 15 fps drops.

**Comment by Panderner** [comment]
@gianca54 the second image of the screen is broken could you reupload it?

**Comment by Panderner** [comment]
> > and have you tried vulkan?
> 
> Yes, I have it with 1 frame jump and with vulkan the problem is that in some parts the fps drop to 15, the good thing is that with the frame jump the speed of the game becomes stable and parts where it is supposed it goes at 60 fps it runs at 30 stable. The annoying thing is those 15 fps drops.

@gianca54 have you tried to turn off frame skip?

**Comment by gianca54** [comment]
> > > and have you tried vulkan?
> > 
> > 
> > Yes, I have it with 1 frame jump and with vulkan the problem is that in some parts the fps drop to 15, the good thing is that with the frame jump the speed of the game becomes stable and parts where it is supposed it goes at 60 fps it runs at 30 stable. The annoying thing is those 15 fps drops.
> 
> @gianca54 have you tried to turn off frame skip?

The game is only stable in speed and fps with the jump of frames in 1, but it will be with speed of 77%, 80%, 91%, and with 47 and 53 fps.

**Comment by gianca54** [comment]
![Screenshot_20200714_113513_org ppsspp ppsspp](https://user-images.githubusercontent.com/68256365/88407358-9f06cc00-cd97-11ea-9e95-737f095d7ba0.jpg)

**Comment by Panderner** [comment]
> > > > and have you tried vulkan?
> > > 
> > > 
> > > Yes, I have it with 1 frame jump and with vulkan the problem is that in some parts the fps drop to 15, the good thing is that with the frame jump the speed of the game becomes stable and parts where it is supposed it goes at 60 fps it runs at 30 stable. The annoying thing is those 15 fps drops.
> > 
> > 
> > @gianca54 have you tried to turn off frame skip?
> 
> The game is only stable in speed and fps with the jump of frames in 1, but it will be with speed of 77%, 80%, 91%, and with 47 and 53 fps.

could you screenshot it without frame skip?

**Comment by gianca54** [comment]
![Screenshot_20200724_112236_org ppsspp ppsspp](https://user-images.githubusercontent.com/68256365/88413449-cf9f3380-cda0-11ea-9a90-17894cd9156c.jpg)

**Comment by Panderner** [comment]
@gianca54 screenshot it in 1x resolution and without frameskip

**Comment by gianca54** [comment]
> @gianca54 screenshot it in 1x resolution and without frameskip

It's the same result

**Comment by gianca54** [comment]
> @gianca54 screenshot it in 1x resolution and without frameskip

It's the same result
