### ISSUE TITLE
[Android]Keyboard doesn't pop up at certain boxes - 1.10.2

### ISSUE THREAD

**Issue by EX-e-LD** [hrydgard/ppsspp#13147]
Hi,it is me again.I have found some bug where keyboard doesn't pop up where it should.Examples are Remote Disc Streaming Port Number and Port Offset at Networking tab.

Phone:Honor 9S
GPU:PowerVR GE8320
CPU:Mediatek MT6762R Helio P22

Keyboard:
GBoard v. 9.6.3.3201 (Beta)

Use System Native Keyboard is **ON**

TIA

Note:*It also happens at Controls Tab with Analog Axis Sensitivity,and other options as well*

**Comment by boy13epic** [comment]
happens also for ios

**Comment by ANR2ME** [comment]
Similar issue to https://github.com/hrydgard/ppsspp/issues/13716
Should also happened on Alternative speed on Graphic settings.

**Comment by hrydgard** [comment]
Right, I'm gonna combine all these issues into #13716, even though it's newer.
