### ISSUE TITLE
Sims 2 Castaway/Pets EA Logo glitched out - 1.10.2

### ISSUE THREAD

**Issue by itsXPCT** [hrydgard/ppsspp#13146]
Hi,it is me again.Well,i don't see this issue as something that should be on top to-do list,but i noticed and wanted to report it if it is OK with Owner.

![Screenshot_2020-07-14-17-14-27-245_org ppsspp ppssppgold](https://user-images.githubusercontent.com/67833785/87445769-bf48c500-c5f8-11ea-9344-040cfa8bc499.png)
![Screenshot_2020-07-14-17-14-49-961_org ppsspp ppssppgold](https://user-images.githubusercontent.com/67833785/87445839-d8ea0c80-c5f8-11ea-862e-4a6f4aed42f9.png)

Phone:Honor 9S
GPU:PowerVR GE 8320
CPU:Mediatek MT6762R Helio P22

TIA

**Comment by boy13epic** [comment]
i think its the power of the device

**Comment by hrydgard** [comment]
Nah, this kind of thing is independent of performance. It's some kind of minor buffering issue in our use of ffmpeg, dropping a bit of data in the beginning. There are a few games affected by this but none of them are broken more than cosmetically by it, as far as I know. It is a real bug though of course.

**Comment by boy13epic** [comment]
aaaaaaaaaaahhh

**Comment by boy13epic** [comment]
ok

**Comment by EX-e-LD** [comment]
> i think its the power of the device

Nope,game runs completely fine,and i think it is GPU issue.I also found few mentions how it happened on same GPU.

**Comment by boy13epic** [comment]
oh well

**Comment by Gamemulatorer** [comment]
Similar issue https://github.com/hrydgard/ppsspp/issues/12629#issuecomment-588113296

**Comment by sum2012** [comment]
Log:  https://gist.github.com/sum2012/99f39ae4c4644b1edccdcdec4fe10a8c
it is mpeg video
I remember @unknownbrackets said that mpeg maybe also have a warm staff

**Comment by sum2012** [comment]
Just a note jpcsp 69699f20 version no problem on video.

**Comment by sum2012** [comment]
@hrydgard @unknownbrackets this game blue screen due to #139999
It's firmware 3.52.
Please wait me to fix the crash first before release 1.11
ppsspp-v1.10.3-1682-gc251d69ea-windows-amd64 log:
https://gist.github.com/sum2012/12ce2d74afa090f973f315238d7f7985

**Comment by sum2012** [comment]
JPCSPTrace log:
https://gist.github.com/sum2012/8a7a7b69a5312f6c89e69569d3770298

In the real psp , sceMpegGetAtracAu and  sceMpegGetAvcAu don't return ERROR_MPEG_NO_DATA

**Comment by sum2012** [comment]
After merge above patch,only make change in sceMpegRingbufferPut is the last method to solve this original issue.

**Comment by sum2012** [comment]
Fix by #14199 
Closing
