### ISSUE TITLE
TextureDecoder.cpp fails to compile (Raspberry Pi 4)

### ISSUE THREAD

**Issue by gengar1603** [hrydgard/ppsspp#13150]
### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Raspberry Pi 4 4GB model, Running Raspbian Buster OS and 64-bit Linux 5.4 Kernel.

### What happens?
TextureDecoder.cpp fails to compile on Raspbian Buster after a freshly cloning the distro. The compilation fails with the following errors. (full log attached)
[log.txt](https://github.com/hrydgard/ppsspp/files/4920346/log.txt)

[ 91%] Building CXX object CMakeFiles/Core.dir/GPU/Common/TextureDecoder.cpp.o
/home/pi/ppsspp/GPU/Common/TextureDecoder.cpp:311:1: error: unknown type name 'QuickTexHashFunc'
QuickTexHashFunc DoQuickTexHash = &QuickTexHashBasic;
^
/home/pi/ppsspp/GPU/Common/TextureDecoder.cpp:312:1: error: unknown type name 'QuickTexHashFunc'
QuickTexHashFunc StableQuickTexHash = &QuickTexHashNonSSE;
^
/home/pi/ppsspp/GPU/Common/TextureDecoder.cpp:313:1: error: unknown type name 'UnswizzleTex16Func'
UnswizzleTex16Func DoUnswizzleTex16 = &DoUnswizzleTex16Basic;
^
/home/pi/ppsspp/GPU/Common/TextureDecoder.cpp:314:1: error: unknown type name 'ReliableHash32Func'; did you mean 'ReliableHashType'?
ReliableHash32Func DoReliableHash32 = &XXH32;
^~~~~~~~~~~~~~~~~~
ReliableHashType
/home/pi/ppsspp/GPU/Common/TextureDecoder.h:71:13: note: 'ReliableHashType' declared here
typedef u64 ReliableHashType;
            ^
/home/pi/ppsspp/GPU/Common/TextureDecoder.cpp:314:20: error: redefinition of 'ReliableHash32NEON' as different kind of symbol
ReliableHash32Func DoReliableHash32 = &XXH32;
                   ^
/home/pi/ppsspp/GPU/Common/TextureDecoder.h:65:26: note: expanded from macro 'DoReliableHash32'
#define DoReliableHash32 ReliableHash32NEON
                         ^
/home/pi/ppsspp/GPU/Common/TextureDecoderNEON.h:22:5: note: previous definition is here
u32 ReliableHash32NEON(const void *input, size_t len, u32 seed);
    ^
/home/pi/ppsspp/GPU/Common/TextureDecoder.cpp:315:1: error: unknown type name 'ReliableHash64Func'; did you mean 'ReliableHashType'?
ReliableHash64Func DoReliableHash64 = &XXH64;
^~~~~~~~~~~~~~~~~~
ReliableHashType
/home/pi/ppsspp/GPU/Common/TextureDecoder.h:71:13: note: 'ReliableHashType' declared here
typedef u64 ReliableHashType;
            ^
/home/pi/ppsspp/GPU/Common/TextureDecoder.cpp:315:20: error: redefinition of 'XXH64' as different kind of symbol
ReliableHash64Func DoReliableHash64 = &XXH64;
                   ^
/home/pi/ppsspp/GPU/Common/TextureDecoder.h:68:26: note: expanded from macro 'DoReliableHash64'
#define DoReliableHash64 XXH64
                         ^
/home/pi/ppsspp/ext/xxhash.h:85:20: note: previous definition is here
unsigned long long XXH64 (const void* input, size_t length, unsigned long long seed);
                   ^
/home/pi/ppsspp/GPU/Common/TextureDecoder.cpp:322:18: error: non-object type 'u32 (const void *, u32)' (aka 'unsigned int (const void *, unsigned int)') is not assignable
                DoQuickTexHash = &QuickTexHashNEON;
                ~~~~~~~~~~~~~~ ^
/home/pi/ppsspp/GPU/Common/TextureDecoder.cpp:323:22: error: non-object type 'u32 (const void *, u32)' (aka 'unsigned int (const void *, unsigned int)') is not assignable
                StableQuickTexHash = &QuickTexHashNEON;
                ~~~~~~~~~~~~~~~~~~ ^
/home/pi/ppsspp/GPU/Common/TextureDecoder.cpp:324:20: error: non-object type 'void (const u8 *, u32 *, int, int, u32)' (aka 'void (const unsigned char *, unsigned int *, int, int, unsigned int)') is not assignable
                DoUnswizzleTex16 = &DoUnswizzleTex16NEON;
                ~~~~~~~~~~~~~~~~ ^
/home/pi/ppsspp/GPU/Common/TextureDecoder.cpp:327:20: error: non-object type 'u32 (const void *, size_t, u32)' (aka 'unsigned int (const void *, unsigned int, unsigned int)') is not assignable
                DoReliableHash32 = &ReliableHash32NEON;
                ~~~~~~~~~~~~~~~~ ^
11 errors generated.
make[2]: *** [CMakeFiles/Core.dir/build.make:3443: CMakeFiles/Core.dir/GPU/Common/TextureDecoder.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:413: CMakeFiles/Core.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

Any idea what's going wrong?

**Comment by gengar1603** [comment]
I have tried rolling back to 1.10.2, 1.10.1, 1.10.0, and 1.9.4. TextureDecoder.cpp doesn't compile in those either, and gives the same errors

**Comment by hrydgard** [comment]
Truly odd given that our CMakeLists.txt seems to work on a lot of different distros. Seems the compile flags must end up wrong somehow?

**Comment by gengar1603** [comment]
The old build directory was deleted and recloned off of master today. No changes were made to the source code as provided by git. 

Here is the process I have gone through.
1. Deleted ~/ppsspp
2. at home directory run: git clone --recurse-submodules https://github.com/hrydgard/ppsspp.git
3. cd ppsspp
4. ./b.sh -rpi |& tee ./log.txt

Error occurs at 92% through the compile on TextureDecoder.cpp (errors occur at line 70886 in the attached log below)
[Full Log Here](https://github.com/hrydgard/ppsspp/files/5132665/log.txt)

**Comment by unknownbrackets** [comment]
Please try --rpi64 instead of -rpi.

-[Unknown]

**Comment by gengar1603** [comment]
Ok, that fixed the compile errors. However, it is unable to link against the FFMPEG library.
/usr/bin/ld: ../ffmpeg/linux/aarch64/lib/libavformat.a: error adding symbols: file format not recognized

Process followed:
1. Deleted previous ppsspp folder.
2. git clone --recurse-submodules https://github.com/hrydgard/ppsspp.git
3. cd ppsspp
4. ./b.sh --rpi64 |& tee ./log.txt

[Full Log here](https://github.com/hrydgard/ppsspp/files/5151562/log.txt)

**Comment by unknownbrackets** [comment]
Hmm, try running `pushd ffmpeg && ./linux_arm64.sh && popd` before step 4.  This shouldn't be necessary but if it helps, that will point us in the right direction.

-[Unknown]

**Comment by gengar1603** [comment]
Attempting to run "pushd ffmpeg && ./linux_arm64.sh && popd" after cloning the repo fails.

Process followed:

1. Deleted previous ppsspp folder.
2. git clone --recurse-submodules https://github.com/hrydgard/ppsspp.git
3. cd ppsspp
4. pushd ffmpeg && ./linux_arm64.sh && popd

pi@raspberrypi:~ $ cd ppsspp
pi@raspberrypi:~/ppsspp $ pushd ffmpeg && ./linux_arm64.sh && popd
~/ppsspp/ffmpeg ~/ppsspp
aarch64-linux-gnu-gcc is unable to create an executable file.
C compiler test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.

**Comment by unknownbrackets** [comment]
Hmm... okay.  Can you try removing a few lines from linux_arm64.sh first?

https://github.com/hrydgard/ppsspp-ffmpeg/blob/c52930efc02e54059ee26047537bc6a7ea44b6b4/linux_arm64.sh#L5

Replace this part:
```sh
GENERAL="\
   --enable-cross-compile \
   --extra-libs="-lgcc" \
   --arch=aarch64 \
   --cc=aarch64-linux-gnu-gcc \
   --cross-prefix=aarch64-linux-gnu- \
   --nm=aarch64-linux-gnu-gcc-nm"
```

With:
```sh
GENERAL="\
   --extra-libs="-lgcc" \
   --arch=aarch64"
```

Does it compile then?

-[Unknown]

**Comment by gengar1603** [comment]
Attempting to run "pushd ffmpeg && ./linux_arm64.sh && popd" after making the requested change fails (output pasted at the bottom). Could the issue be that I am using a 64-bit Kernel with a 32-bit Userland, and that's throwing off all the detections? uname -a reports the following:

pi@raspberrypi:~/ppsspp/ffmpeg $ uname -a
Linux raspberrypi 5.4.58-v8+ #1335 SMP PREEMPT Thu Aug 13 22:29:57 BST 2020 aarch64 GNU/Linux

Process followed:

1. Deleted previous ppsspp folder.
2. git clone --recurse-submodules https://github.com/hrydgard/ppsspp.git
3. Made the change in ~/ppsspp/ffmpeg/linux_arm64.sh as requested above. 
4. cd ppsspp
5. pushd ffmpeg && ./linux_arm64.sh && popd

pi@raspberrypi:~ $ cd ppsspp
pi@raspberrypi:~/ppsspp $ pushd ffmpeg && ./linux_arm64.sh && popd
~/ppsspp/ffmpeg ~/ppsspp ~/ppsspp
install prefix            ./linux/aarch64
source path               .
C compiler                gcc
C library                 glibc
ARCH                      aarch64 (generic)
big-endian                no
runtime cpu detection     yes
NEON enabled              no
VFP enabled               no
debug symbols             yes
strip symbols             yes
optimize for size         no
optimizations             yes
static                    yes
shared                    no
postprocessing support    no
new filter support        no
network support           no
threading support         pthreads
safe bitstream reader     yes
SDL support               no
opencl enabled            no
texi2html enabled         no
perl enabled              yes
pod2man enabled           yes
makeinfo enabled          no
makeinfo supports HTML    no

Enabled programs:

External libraries:
iconv			   libxcb		      xlib			 zlib

Enabled decoders:
aac			   h263			      mjpegb			 mpeg4
aac_latm		   h264			      mp3			 pcm_s16le
atrac3			   mjpeg		      mpeg2video		 pcm_s8
atrac3p

Enabled encoders:
ffv1			   huffyuv		      mjpeg			 pcm_s16le

Enabled hwaccels:

Enabled parsers:
aac			   h263			      mpeg4video		 mpegvideo
aac_latm		   h264			      mpegaudio

Enabled demuxers:
aac			   m4v			      mpegvideo			 pcm_s8
avi			   mp3			      oma			 pmp
h264			   mpegps		      pcm_s16le			 wav

Enabled muxers:
avi

Enabled protocols:

Enabled filters:

Enabled bsfs:

Enabled indevs:

Enabled outdevs:

License: LGPL version 2.1 or later
Creating config.mak, config.h, and doc/config.texi...
CC	libavformat/aacdec.o
In file included from ./libavutil/bswap.h:38,
                 from ./libavutil/intreadwrite.h:25,
                 from libavformat/aacdec.c:23:
libavformat/aacdec.c: In function ‘adts_aac_probe’:
./libavutil/aarch64/bswap.h:31:5: error: invalid 'asm': invalid operand for code 'w'
     __asm__("rev16 %w0, %w0" : "+r"(x));
     ^~~~~~~
./libavutil/aarch64/bswap.h:31:5: error: invalid 'asm': invalid operand for code 'w'
./libavutil/aarch64/bswap.h:38:5: error: invalid 'asm': invalid operand for code 'w'
     __asm__("rev %w0, %w0" : "+r"(x));
     ^~~~~~~
./libavutil/aarch64/bswap.h:38:5: error: invalid 'asm': invalid operand for code 'w'
make: *** [common.mak:60: libavformat/aacdec.o] Error 1

**Comment by unknownbrackets** [comment]
In that case, I think you want --rpi instead of --rpi64.  Maybe the original problem was just using `-rpi` without the extra hyphen.  I thought this was a 64 bit system, but it seems to be confused about which it is when we try to compile 64-bit.

-[Unknown]

**Comment by gengar1603** [comment]
Even when using --rpi, it still fails at the same point when linking against the FFMPEG library...
/usr/bin/ld: ../ffmpeg/linux/aarch64/lib/libavformat.a: error adding symbols: file format not recognized

Process followed:

1. Deleted previous ppsspp folder.
2. git clone --recurse-submodules https://github.com/hrydgard/ppsspp.git
3. cd ppsspp
4. ./b.sh --rpi |& tee ./log.txt

[Full Log Here](https://github.com/hrydgard/ppsspp/files/5188506/log.txt)

**Comment by unknownbrackets** [comment]
Has this improved?  You might need to compile FFmpeg with `pushd ffmpeg && ./linux_arm64.sh && popd`.

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.  Some of the NEON defines were normalized, and other users are reporting feedback using PPSSPP on Raspberry Pi 4, so I'm assuming this is resolved now.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
