### ISSUE TITLE
[Android][OpenGL]Phineas & Ferb can't reach 20/20 FPS - 1.10.2

### ISSUE THREAD

**Issue by itsXPCT** [hrydgard/ppsspp#13155]
Hi,me again.I went to play Phineas & Ferb - Across the 2nd Dimension,and game can't reach 20/20 FPS.I tried everything (I/O timing methods,buffered/non-buffered rendering,1x Rendering Resolution)However,i noticed that game looks like really bad rendered at **Buffered Rendering**,while looks better and performes better at **Non-buffered rendering**

Buffered Rendering:
![Screenshot_2020-07-16-12-04-07-800_org ppsspp ppssppgold](https://user-images.githubusercontent.com/67833785/87658535-9fcaad00-c75c-11ea-9393-8226605f4490.png)

Non-buffered Rendering:
![Screenshot_2020-07-16-12-04-42-162_org ppsspp ppssppgold](https://user-images.githubusercontent.com/67833785/87658851-051e9e00-c75d-11ea-9d7d-24910fd18a54.png)

All images were taken with 2x Rendering Resolution

TIA

**Comment by Gamemulatorer** [comment]
On the latest git build of ppsspp the screen is flickering in this game and I also notice it on other game(s) intro video

### screen recording
[Phineas and Ferb PSP.zip](https://github.com/hrydgard/ppsspp/files/4931192/Phineas.and.Ferb.PSP.zip)
### ge dump
[Phineas&Ferb.zip](https://github.com/hrydgard/ppsspp/files/4931194/Phineas.Ferb.zip)

@unknownbrackets @hrydgard

**Comment by Panderner** [comment]
@EX-e-LD what device are you using?

**Comment by EX-e-LD** [comment]
> @EX-e-LD what device are you using?

As always,Honor 9S.I will now test on my PC.

**Comment by EX-e-LD** [comment]
This game runs fine on Direct3D 11,this is sure OpenGL bug,i will provide GE Dump tomorrow.

**Comment by Panderner** [comment]
The game works fine for me running on Realme C2 on 3x Resolution
![Screenshot_2020-07-17-07-57-31-28_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/87733755-35207c80-c803-11ea-95bd-908bf3200f38.png)

**Comment by Gamemulatorer** [comment]
> The game works fine for me running on Realme C2 on 3x Resolution
> ![Screenshot_2020-07-17-07-57-31-28_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/87733755-35207c80-c803-11ea-95bd-908bf3200f38.png)

@Panderner the glscreen is not flickering on your phone using latest git build of ppsspp on opengl backend!?

**Comment by Panderner** [comment]
but @Gamemulatorer what device are you using?

**Comment by Gamemulatorer** [comment]
> but @Gamemulatorer what device are you using?

Just answer my question if it's flickering on your phone using the latest git build of ppsspp.

The stable version 1.10.3 has no screen flickering on my phone w/ opengl 2.0

**Comment by Panderner** [comment]
> > but @Gamemulatorer what device are you using?
> 
> Just answer my question if it's flickering on your phone using the latest git build of ppsspp.
> 
> The stable version 1.10.3 has no screen flickering on my phone w/ opengl 2.0

No screen flickering at all on my phone but Tell me what whone are you using?

**Comment by EX-e-LD** [comment]
No flickering here as well,but lag is same no matter the option.

**Comment by Gamemulatorer** [comment]
> Hi,me again.I went to play Phineas & Ferb - Across the 2nd Dimension,and game can't reach 20/20 FPS.I tried everything (I/O timing methods,buffered/non-buffered rendering,1x Rendering Resolution)However,i noticed that game looks like really bad rendered at **Buffered Rendering**,while looks better and performes better at **Non-buffered rendering**
> 
> Buffered Rendering:
> ![Screenshot_2020-07-16-12-04-07-800_org ppsspp ppssppgold](https://user-images.githubusercontent.com/67833785/87658535-9fcaad00-c75c-11ea-9393-8226605f4490.png)
> 
> Non-buffered Rendering:
> ![Screenshot_2020-07-16-12-04-42-162_org ppsspp ppssppgold](https://user-images.githubusercontent.com/67833785/87658851-051e9e00-c75d-11ea-9d7d-24910fd18a54.png)
> 
> All images were taken with 2x Rendering Resolution
> 
> TIA

It's weird that your phone is more powerful than mine but can't reach 20/20 FPS 99.9% Speed lol 😅✌
![Screenshot_2020-07-17-12-42-57](https://user-images.githubusercontent.com/37603562/87749485-644ae400-c82b-11ea-9552-d89adad53f23.png)
Im using PPSSPP v1.10.3-git buildbot (no screen flickering)

**Comment by Gamemulatorer** [comment]
> No flickering here as well,but lag is same no matter the option.

Try the latest git build first before you say that https://buildbot.orphis.net/ppsspp/

**Comment by EX-e-LD** [comment]
I will,give me a second,and i will report here.

**Comment by Panderner** [comment]
@Gamemulatorer what CPU are you using?

**Comment by EX-e-LD** [comment]
Nope,still same.Damm,gotta make GE Dump.

**Comment by Gamemulatorer** [comment]
> Nope,still same.Damm,gotta make GE Dump.

Still lag? can't reach 20fps using the latest git build of ppsspp? if yes, then it's your phone issue not ppsspp. 

because my low specs phone can reach 20fps & 99%speed.

**Comment by EX-e-LD** [comment]
Bugs can occur on certain devices,just search GitHub with term PowerVR,you would be surprised.I don't think phone can cause this way of handling.

**Comment by Gamemulatorer** [comment]
> Bugs can occur on certain devices,just search GitHub with term PowerVR,you would be surprised.I don't think phone can cause this way of handling.

Read here https://github.com/hrydgard/ppsspp/issues/12824#issuecomment-614069461 so you could understand that different games in psp behave different on every android gpu phones

**Comment by EX-e-LD** [comment]
Your opinion, @hrydgard ?

**Comment by EX-e-LD** [comment]
Here is my GE Dump:
[recording.zip](https://github.com/hrydgard/ppsspp/files/4936783/recording.zip)

**Comment by Gamemulatorer** [comment]
> Here is my GE Dump:
> [recording.zip](https://github.com/hrydgard/ppsspp/files/4936783/recording.zip)

Using your GE dump I still got 30fps
![Screenshot_2020-07-17-20-40-06](https://user-images.githubusercontent.com/37603562/87787185-cc221e80-c86d-11ea-89a8-40ff9c5ca019.png)

**Comment by EX-e-LD** [comment]
30?20 is default.

**Comment by hrydgard** [comment]
You can just open them in PPSSPP, but measuring performance from running the GE dump will not give you the whole pictures as only the rendering is performed, not the CPU emulation.

**Comment by EX-e-LD** [comment]
I get it.So what about the "bug" here?Is it my issue or emulator's issue?

TIA

**Comment by Gamemulatorer** [comment]
> I get it.So what about the "bug" here?Is it my issue or emulator's issue?
> 
> TIA

@EX-e-LD try another game with 20/20fps like #13040 and see if your phone can reach it :)

**Comment by Gamemulatorer** [comment]
![Screenshot_20200720-090434](https://user-images.githubusercontent.com/37603562/87890645-f6403000-ca69-11ea-8704-34d8b746c4b9.png)
I try this game on another low specs android device
the soc is snapdragon 430 adreno 505 but it can reach the game to it's maximum fps of 20/20.
![Screenshot_20200720-090405](https://user-images.githubusercontent.com/37603562/87890638-f2141280-ca69-11ea-80d6-151de3ee09b1.png)
So this issue maybe is your phone fault not ppsspp imoo

**Comment by Panderner** [comment]
or maybe it's related refresh rate issue

**Comment by EX-e-LD** [comment]
Sorry,but i'll wait developer's rant on this,if i get one.

**Comment by Gamemulatorer** [comment]
> Sorry,but i'll wait developer's rant on this,if i get one.

Better try other game(s) with 20fps limit like Beowulf #13040 or try MGSPW also have 20fps limit and check if your phone can reach it maximum fps.
If not your phone has the issue not ppsspp.

**Comment by EX-e-LD** [comment]
> > Sorry,but i'll wait developer's rant on this,if i get one.
> 
> Better try other game(s) with 20fps limit like Beowulf #13040 or try MGSPW also have 20fps limit and check if your phone can reach it maximum fps.
> If not your phone has the issue not ppsspp.

So what if it can run properly?

TIA

**Comment by Gamemulatorer** [comment]
> So what if it can run properly?
> 
> TIA

If those 2 games I mentioned earlier can run at maximum fps of 20 on your phone, then this only game P&P have problem not your phone.

Hope you get my phone I'm not really good in english :(

**Comment by EX-e-LD** [comment]
> > So what if it can run properly?
> > TIA
> 
> If those 2 games I mentioned earlier can run at maximum fps of 20 on your phone, then this only game P&P have problem not your phone.
> 
> Hope you get my point here I'm not really good in english :(✌

Emulator issue?If i understood correctly.I will keep it for chance developer will see it.Thanks anyways,i appreciate it.

**Comment by Gamemulatorer** [comment]
This game running smooth on a 1gb ram, quad-core CPU w/ Mali400 GPU but the annoying screen flickering issue on opengl es 2 made me quit using PPSSPP buildbot 😅
