### ISSUE TITLE
Activision Hits Remixed Flickerning using frame skip

### ISSUE THREAD

**Issue by boy13epic** [hrydgard/ppsspp#13160]
### What happens?
The screen flickers

### What *should* happen?
proper screen

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

IPad 6 JIT,iOS and ppsspp 1.10.3

**Comment by Gamemulatorer** [comment]
skip buffer or frameskip x1 or more!?

**Comment by unknownbrackets** [comment]
Do you have more information on what settings you're using?

-[Unknown]

**Comment by Panderner** [comment]
Still buggy for frame skip on and skip buffer effects on.

**Comment by unknownbrackets** [comment]
It's expected to have issues with skip buffer effects.  That's not really fixable.

-[Unknown]

**Comment by hrydgard** [comment]
Avoid frameskip for this game then.
