### ISSUE TITLE
Teenage Mutant Ninja Turtles can't reach 60FPS - 1.10.2

### ISSUE THREAD

**Issue by EX-e-LD** [hrydgard/ppsspp#13161]
Hi,me *again*.I went to play Teenage Mutant Ninja Turtle because of my Ad-Hoc list,and well,game really can't reach 60FPS.I've tried already;non-buffered rendering,1x resolution,I/O Timing Methods).Nothing except frameskip can't really help,but it doesn't really help since game is 50/60 FPS in most cases,and Frameskip would skip too much.If someone can help me figure this out,i'd be grateful.

GE Dump:
[recording (2).zip](https://github.com/hrydgard/ppsspp/files/4939305/recording.2.zip)

Phone:Honor 9S
GPU:PowerVR GE8320
CPU:Mediatek MT6762R Helio P22
Backend:OpenGL

**Note:This also happens with Direct3D backends,tested on 3 different PCs**

TIA

**Comment by Gamemulatorer** [comment]
Using your ge dump my phone can reach 56/60fps in 1x rendering resolution so this is another device power issue 🙂
![Screenshot_2020-07-18-09-43-55](https://user-images.githubusercontent.com/37603562/87841948-800dc300-c8db-11ea-9454-3cb5fbf5f16b.png)
![Screenshot_2020-07-18-09-46-49](https://user-images.githubusercontent.com/37603562/87841966-9fa4eb80-c8db-11ea-8634-ca14afdf542b.png)

Mediatek Helio P22 is not powerful cpu imhoo to run this game at 60/60fps in 2x rendering resolution or more set it to 1x rendering resolution and then enable some speed up in graphics settings.

**Comment by Panderner** [comment]
The game runs smoothly for me running on Realme C2
![Screenshot_2020-07-18-10-33-31-21_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/87842855-4c826700-c8e2-11ea-8dbc-f21944174d27.png)

**Comment by Panderner** [comment]
and remember @EX-e-LD check your refresh rate if the phone is 60hz
![IMG_20200718_103558](https://user-images.githubusercontent.com/37503397/87842894-9d925b00-c8e2-11ea-97ba-d5a9c8a983e3.jpg)

**Comment by EX-e-LD** [comment]
Closing this :|

**Comment by Panderner** [comment]
wait @EX-e-LD check your refresh rate for your phone

**Comment by Gamemulatorer** [comment]
@EX-e-LD you better upload your phone refresh rate screenshot.
