### ISSUE TITLE
LocoRoco 2 Broken Since #12709

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#13166]
There's a issues for LocoRoco 2 in latest git build (EDIT: And since #12709):

Some Letters are replaced by white boxes except the word options near the square button on the left:
![Screenshot_2020-07-19-18-19-55-76_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/87872627-d74f8880-c9ec-11ea-80db-058b2c278fca.png)

When i pause the game it crashes
![Screenshot_2020-07-19-18-23-18-91_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/87872641-05cd6380-c9ed-11ea-845e-eec3409965b5.png)

When i collect the Item Insect the game crashes
![Screenshot_2020-07-20-10-05-26-95_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/87892821-b466b800-ca70-11ea-9abf-ca5c14587a59.png)

**Comment by hrydgard** [comment]
Thanks for reporting, that's weird. Marking for investigation.

**Comment by hrydgard** [comment]
Do you know an earlier build when it worked properly? Would speed up investigation.

**Comment by Panderner** [comment]
Last Build Working is v1.9.3-500-ge14bf3bcc
The issue started in v1.9.3-507-g6310f559f

**Comment by hrydgard** [comment]
Thanks, that's very helpful!

#12709 indeed then. Hmm...

**Comment by hrydgard** [comment]
This should be fixed in master now, thanks @shenweip !

**Comment by Panderner** [comment]
Text glitches and Crashes are now fixed in latest build. I'm closing now

**Comment by hrydgard** [comment]
Great!
