### ISSUE TITLE
Backup savestates are hard to understand how to load

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#13188]
UX issue - nobody understands how to load them. Can't click them in the list:

https://cdn.discordapp.com/attachments/480103153803460614/735648982373630002/IMG_20200722_1118422.jpg

(reported on Discord by soma).

**Comment by unknownbrackets** [comment]
Right, see #10737.  I also think we should consider changing the mobile desktop to enabled.

-[Unknown]

**Comment by hrydgard** [comment]
I think we can consider this blocked on #13016 - we need a new pause screen design to fit the undo buttons.

**Comment by unknownbrackets** [comment]
Undo / backup save states behave the same in the savedata manager as regular save states, and now can be loaded from within the UI with #14676.  I'm going to close this as fixed by iota97.

-[Unknown]
