### ISSUE TITLE
screen question

### ISSUE THREAD

**Issue by LuisFellp** [hrydgard/ppsspp#13184]
how i get rid of black bars and fit the screen? (these left and right bars)
![Screenshot_20200722-182009_PPSSPP](https://user-images.githubusercontent.com/33043774/88235620-3e697900-cc49-11ea-81d9-15882acf3663.jpg)

**Comment by LunaMoo** [comment]
You don't, unless you want everything to look stretched and awful in which case use "Display Layout Editor" under graphics settings and pick "Stretching" in it's options, but again PSP games render at 16:9 and will not fill the screen without user-made game-specific hacks which in things like the screen you posted wouldn't even work anyway as there's nothing to render on the sides.

Forums is the place for questions and discussions, this is an issue tracker. Closing.
