### ISSUE TITLE
Jungle Party Fails to Boot - 1.10.2

### ISSUE THREAD

**Issue by EX-e-LD** [hrydgard/ppsspp#13197]
Hi,me again.I went to test game Jungle Party,and game couldn't boot at all at my phone.ISO is not corrupt,i double checked it,and i haven't found any issue on GitHub and i have to report.Game is booting and it freezes,like this:
![Screenshot_2020-07-24-20-36-05-723_org ppsspp ppssppgold](https://user-images.githubusercontent.com/67833785/88424168-5ed23880-cded-11ea-8217-10506607b514.png)
If there is fix for this,i would be happy if you told me.

TIA

**Comment by Panderner** [comment]
The game works fine for me except This game uses sceMP4 which is unimplemented on PPSSPP see #1755 but it can boot the game
![Screenshot_2020-07-25-07-28-18-14_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/88442929-db463500-ce48-11ea-9690-84226485a73e.png)

**Comment by Panderner** [comment]
@EX-e-LD have you tried to use Latest Build?
Here's a link for PPSSPP builds https://buildbot.orphis.net/ppsspp/index.php?m=fulllist

**Comment by EX-e-LD** [comment]
Running latest build on my PC and Phone,still not able to play game,any ideas why?

**Comment by Panderner** [comment]
@EX-e-LD what serial version of this game are you using?

**Comment by EX-e-LD** [comment]
Europe one - UCES01459

**Comment by Panderner** [comment]
because your iso is likely to be corrupted. have you redump your UMD?

**Comment by EX-e-LD** [comment]
Yes i did,three times.

**Comment by EX-e-LD** [comment]
@Panderner 
Closing this,my bad,my PPSSPP has some issue,idk why but i did reset my settings and it works now,so sorry for taking out time.

TIA
