### ISSUE TITLE
Crash while install texture pack. (Android)

### ISSUE THREAD

**Issue by Saramagrean** [hrydgard/ppsspp#13199]
### What happens?
PPSSPP crash after press texture pack zip file. (Android only)

First break: v1.10.3-91-gfe91f62f9
Last work: v1.10.3-73-g2916e5b67

### What *should* happen?
Can install texture pack zip file via PPSSPP. :)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Huawei P9 Plus (Kirin 955, Mali T-880)

Logcat: [ppsspp-logcat.zip](https://github.com/hrydgard/ppsspp/files/4975050/ppsspp-logcat.zip)

**Comment by hrydgard** [comment]
Link to a pack that crashes?

**Comment by Saramagrean** [comment]
Here.
https://forums.ppsspp.org/showthread.php?tid=25060

**Comment by hrydgard** [comment]
Thanks, I can repro. A couple of things going wrong... I'll get it fixed.
