### ISSUE TITLE
Shin Sangoku Musou 6 Special chinese patch cannot switch umd itself

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#13205]
The iso is combine disc 1 and disc 2

I think that we try to imp kernel module  instead directly modify sceumd
Please note that jpcsp emulator already done it.

18:22:888 hle\scekernelmodule.cpp:753 I[LOADER]: Function (sceMeCore_driver,67f0ed84) unresolved, storing for later resolving
18:22:889 hle\scekernelmodule.cpp:753 I[LOADER]: Function (sceMeCore_driver,c287ad90) unresolved, storing for later resolving
18:22:889 hle\scekernelmodule.cpp:753 I[LOADER]: Function (sceMeCore_driver,d857cf93) unresolved, storing for later resolving
18:22:889 hle\scekernelmodule.cpp:753 I[LOADER]: Function (sceMeCore_driver,8988ad49) unresolved, storing for later resolving
18:22:889 hle\scekernelmodule.cpp:753 I[LOADER]: Function (sceMeCore_driver,051c1601) unresolved, storing for later resolving
18:22:889 hle\scekernelmodule.cpp:753 I[LOADER]: Function (sceMeCore_driver,99e4dbfa) unresolved, storing for later resolving
18:22:889 hle\scekernelmodule.cpp:753 I[LOADER]: Function (InterruptManagerForKernel,f987b1f0) unresolved, storing for later resolving
18:22:889 hle\scekernelmodule.cpp:753 I[LOADER]: Function (InterruptManagerForKernel,8b61808b) unresolved, storing for later resolving
18:22:889 hle\scekernelmodule.cpp:753 I[LOADER]: Function (semaphore,4c537c72) unresolved, storing for later resolving
18:22:889 hle\scekernelmodule.cpp:753 I[LOADER]: Function (semaphore,77e97079) unresolved, storing for later resolving
18:22:889 hle\scekernelmodule.cpp:753 I[LOADER]: Function (SystemCtrlForKernel,159af5cc) unresolved, storing for later resolving
18:22:889 hle\scekernelmodule.cpp:753 I[LOADER]: Function (SystemCtrlForKernel,1c90becb) unresolved, storing for later resolving
18:22:889 hle\scekernelmodule.cpp:751 W[LOADER]: Unknown syscall in known module 'ThreadManForKernel': 0x28b6489c
18:22:889 hle\scekernelmodule.cpp:751 W[LOADER]: Unknown syscall in known module 'ThreadManForKernel': 0xef9e4c70
18:22:889 hle\scekernelmodule.cpp:751 W[LOADER]: Unknown syscall in known module 'SysMemForKernel': 0x536ad5e1
18:22:889 hle\scekernelmodule.cpp:751 W[LOADER]: Unknown syscall in known module 'SysMemForKernel': 0x3fc9ae6a
18:22:889 hle\scekernelmodule.cpp:753 I[LOADER]: Function (sceSysEventForKernel,d7d3fdcd) unresolved, storing for later resolving
18:22:889 hle\scekernelmodule.cpp:753 I[LOADER]: Function (sceSysEventForKernel,68d55505) unresolved, storing for later resolving
18:22:979 main_thread  W[LOADER]: hle\scekernelmodule.cpp:751 Unknown syscall in known module 'Kernel_Library': 0x05572a5f
18:22:979 main_thread  W[LOADER]: hle\scekernelmodule.cpp:751 Unknown syscall in known module 'Kernel_Library': 0x4ac57943
18:22:979 main_thread  W[LOADER]: hle\scekernelmodule.cpp:751 Unknown syscall in known module 'ThreadManForUser': 0x71ec4271
18:22:979 main_thread  W[LOADER]: hle\scekernelmodule.cpp:751 Unknown syscall in known module 'ThreadManForUser': 0x79d1c3fa
18:22:979 main_thread  W[LOADER]: hle\scekernelmodule.cpp:751 Unknown syscall in known module 'ThreadManForUser': 0x91e4f6a7
18:22:979 main_thread  W[LOADER]: hle\scekernelmodule.cpp:751 Unknown syscall in known module 'ThreadManForUser': 0xb435dec5

full log:
https://gist.github.com/sum2012/be0f227726e3fa96b7fb5bee381ba597

**Comment by sum2012** [comment]
Update the log to ppsspp-v1.10.3-276-g4766e4fcb-windows-amd64
https://gist.github.com/sum2012/710181a112483f69d18386457b409a12
I feel this error maybe related
18:34:786 main_thread  E[HLE]: hle\hle.cpp:728 Unimplemented HLE function sceKernelFindModuleByUID

**Comment by Exiasa** [comment]
sir where u got chinese patch sorry interup

**Comment by sum2012** [comment]
it is illegal

在 2020年8月4日週二 上午11:37，Exiasa <notifications@github.com> 寫道：

**Comment by Exiasa** [comment]
what it mean?

**Comment by sum2012** [comment]
I might work in a hacked sceumd first

**Comment by sum2012** [comment]
@shenweip thanks the umd patch
Anyway i try to force sceKernelFindModuleByUID return by real psp value,the patched game still cannot switch.
Do we have a hack method to work ? Thanks.

**Comment by shenweip** [comment]
I'm not sure now.I'll look into this later.

**Comment by sum2012** [comment]
#13592 fix it.
Another problem I re-create issue
