### ISSUE TITLE
Graphics are glitchy and jumpy in all games

### ISSUE THREAD

**Issue by MattIzSpooky** [hrydgard/ppsspp#13201]
### What happens?
I boot up a game in Retroarch and all the graphics look like they are dancing/jumping around. I left the config files alone.

The graphics are extremely glitchy and look like they are constantly jumping around. Check this video: 
https://imgur.com/a/bdjmyUg

This seems to happen in **all** games.

After testing around for a bit, it seems that increasing the internal resolution solves it a bit but that seems to introduce other problems. Such as sprites looking "broken" (lines between sprite parts etc).

How do I fix this?

### What *should* happen?
The graphics should behave normally.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
CPU: i7 6700k @ 4.5ghz
RAM: 16gb @ 2900mhz
GPU: GTX 1080
OS: Windows 10 (10.0.18363 Build 18363)
Display resolution: 3440x1440

PPSSPP Version: one included with Retroarch (1.8.9)
Render backend used: OpenGL and Vulkan (doesn't really seem to matter here, glitch still happens.)

**Comment by unknownbrackets** [comment]
That's really weird.  I assume it doesn't happen in PPSSPP proper, and only in libretro?  Does it happen for you when using libretro with other systems?

Increasing render resolution can cause "broken" lines.  If you're interested in the technical details why, see here:
https://forums.ppsspp.org/showthread.php?tid=13556&pid=96345#pid96345

But the shaky thing shouldn't be happening - except in Gran Turismo.  That game actually intentionally does something kinda similar to what you're seeing to simulate a motion blur effect (the PSP's LCD update speed was not super great.)

-[Unknown]

**Comment by MattIzSpooky** [comment]
@unknownbrackets 

This does not seem to happen in the standalone version.
Versions tested:
- 1.10.3
- 1.9.3 
- 1.8.0 

 I tested this with multiple games. (Fate/Extra, Valkyrie Profile: Lenneth and Ys I & II Chronicles). Once again tested with default configs.

It seems I was wrong about the PPSSPP version. The commit hash of this version is https://github.com/hrydgard/ppsspp/commit/020d7c3. I thought that the 1.8.9 was the PPSSPP version, but that seems to be the Retroarch version.
![image](https://user-images.githubusercontent.com/26460447/88471403-553df300-cf09-11ea-831f-5b97138dc08f.png)


This does not happen to me with the other libretro stuff. Cores tested:
- VBA-M
- Dolphin
- PCSX ReARMed

I also tested this on my phone and that seems to be working fine. (only tested 1 game, Valkyrie Profile: Lenneth). 
I should note that I also used Retroarch on my phone. That PPSSPP's version is on this commit https://github.com/hrydgard/ppsspp/commit/143d54a
Phone: Xiaomi Poco F2 Pro
SoC: Snapdragon 865 
GPU: Adreno 650
RAM: 6gb
OS: Android 10, MIUI 12

After messing around for a bit I decided to update the libretro core. New version is: https://github.com/hrydgard/ppsspp/commit/b4f2605. I still have that issue on this version.

**Comment by MattIzSpooky** [comment]
I also tested the Retroarch nightly (build: 25-6-2020) but that dit not resolve the issue. PPSSPP's version was https://github.com/hrydgard/ppsspp/commit/b4f2605

**Comment by i30817** [comment]
Pretty sure it's probably not the cause but this can sort of be worked around by disabling auto frameskip and setting frameskip to 1 or 3 or 5 or 7 (but curiously not 9) in the retroarch core options.

I didn't say it was a good work around.

Anyway this seems to indicate the jump is in alternate frames.

**Comment by MattIzSpooky** [comment]
> Pretty sure it's probably not the cause but this can sort of be worked around by disabling auto frameskip and setting frameskip to 1 or 3 or 5 or 7 (but curiously not 9) in the retroarch core options.
> 
> I didn't say it was a good work around.
> 
> Anyway this seems to indicate the jump is in alternate frames, though the 9 not working makes me wonder.

Setting frameskip to 1 seemed to fix it for me. Not the best solution but good enough for a temporary workaround. It still shows up sometimes but thats okay.

**Comment by i30817** [comment]
@MattIzSpooky , it's fixed by 5313fc5, so you won't need the frameskip soon.

**Comment by MattIzSpooky** [comment]
> @MattIzSpooky , it's fixed by [5313fc5](https://github.com/hrydgard/ppsspp/commit/5313fc5b368b8d7c92d47b0560563ae613461188) (in opengl), so you won't need the frameskip soon.

Yep, seems to work!

I tested this once again on libretro. The commit I am on is https://github.com/hrydgard/ppsspp/commit/1355255.

I will close this issue because it has clearly been fixed. Thanks!
