### ISSUE TITLE
Bug report about Alternative Speed

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#13211]
Got this report through email:

"in this latest version of the emulator 1.10.2, the alternative speed has lost its luster and utility.

The function makes it faster but the drop in FPS is absurd, something that did not happen in previous versions.

Please, if you have how to solve this bug I will be very grateful.
"

No idea what might have changed?

**Comment by unknownbrackets** [comment]
Maybe Vulkan + vsync enabled (previously did nothing)?  In v1.10.x, FPS reduces in that configuration to speed up.

This report isn't very descriptive to do anything about.

-[Unknown]

**Comment by hrydgard** [comment]
Yeah I'm asking for more details, let's see if we can clear up what this is actually about.

**Comment by Gamemulatorer** [comment]
This issue is related to alternative speed using latest ppsspp development apk.
This video will tell the issues.
[Screenrecorder-2021-08-10-23-05-28-15.mp4.zip](https://github.com/hrydgard/ppsspp/files/6962724/Screenrecorder-2021-08-10-23-05-28-15.mp4.zip)

**Comment by hrydgard** [comment]
With that change, is this now fixed?

**Comment by Gamemulatorer** [comment]
Im using the latest ppsspp build no framedrops when fast forward is pressing.
![Screenshot_2021-08-29-11-42-47-012_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/131237562-4a3452c8-0e5e-47af-a8c6-d12a7f1e7f75.jpg)
