### ISSUE TITLE
[Update Suggestion]Make UI for Ad-Hoc more organized

### ISSUE THREAD

**Issue by EX-e-LD** [hrydgard/ppsspp#13214]
**(Sorry for first closed one,accidentally hit enter)**

Hi,me again.Well,UI of PPSSPP is very unique and awesome,also good organized,well,except Ad-Hoc.With new UPnP addition,Ad-Hoc menu got really messy,and it is really hard to find what you're looking for.My opinion is it should be revamped in for example sections,where one could find what he actually needs.This is just suggestion,not something that should be your priority but my idea in general,because you did same thing with the Graphics and System,and that is really neat,and can be lot better.

TIA

**Comment by HiImBrala** [comment]
Not too bad idea,i have seen couple emulators and games and network settings now are really messed up.

**Comment by hrydgard** [comment]
Did #13232 improve it enough?

**Comment by EX-e-LD** [comment]
@hrydgard 
Thank you!!This looks really good,and it is more polished now,exactly way i was thinking.

**Comment by hrydgard** [comment]
Well, thank @ANR2ME for the actual work. I'll close it for you.
