### ISSUE TITLE
[Android] Crash in nearly all games

### ISSUE THREAD

**Issue by leopard20** [hrydgard/ppsspp#13215]
v1.10.3-243
Might be related to the adhoc changes.
I think you already know this but meh.
Sample crash log:
```
Revision: '0'
ABI: 'arm64'
pid: 14854, tid: 14906, name: Thread-3  >>> org.ppsspp.ppsspp <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x60
Cause: null pointer dereference
    x0   0000007877310220  x1   0000007877310220  x2   0000000000000020  x3   0000000000000020
    x4   4000000000000000  x5   0000000000000000  x6   0000000000000000  x7   7f7f7f7f7f7f7f7f
    x8   0000000000000062  x9   0000000000000000  x10  0000000000000000  x11  0000007877310220
    x12  0000000000000000  x13  0000000000000000  x14  ffffffffffffffff  x15  aaaaaaaaaaaaaaab
    x16  000000787ab14340  x17  00000078990e7c88  x18  00000078791ce098  x19  0000007877310220
    x20  000000787730fe60  x21  0000000000000050  x22  00000078749346a0  x23  0000000000000050
    x24  0000007877311588  x25  0000007877310708  x26  0000007877310731  x27  000000787ab8d698
    x28  0000000000000002  x29  000000787730fd90  x30  000000787a86ae54
    sp   000000787730fd90  pc   000000787a86ae54  pstate 0000000000000000

backtrace:
    #00 pc 0000000000c5ee54  /data/app/org.ppsspp.ppsspp-awj6ylbuJCxDVI4S6SN11w==/lib/arm64/libppsspp_jni.so
    #01 pc 000000000065e208  /data/app/org.ppsspp.ppsspp-awj6ylbuJCxDVI4S6SN11w==/lib/arm64/libppsspp_jni.so (_Z10LaunchFileP13ScreenManagerNSt6__ndk112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE+640)
    #02 pc 000000000066a2a0  /data/app/org.ppsspp.ppsspp-awj6ylbuJCxDVI4S6SN11w==/lib/arm64/libppsspp_jni.so (_ZN10MainScreen21OnGameSelectedInstantERN2UI11EventParamsE+328)
    #03 pc 000000000074e064  /data/app/org.ppsspp.ppsspp-awj6ylbuJCxDVI4S6SN11w==/lib/arm64/libppsspp_jni.so (_ZN2UI5Event8DispatchERNS_11EventParamsE+56)
    #04 pc 000000000073ee4c  /data/app/org.ppsspp.ppsspp-awj6ylbuJCxDVI4S6SN11w==/lib/arm64/libppsspp_jni.so (_ZN2UI14DispatchEventsEv+520)
    #05 pc 0000000000740378  /data/app/org.ppsspp.ppsspp-awj6ylbuJCxDVI4S6SN11w==/lib/arm64/libppsspp_jni.so (_ZN2UI19UpdateViewHierarchyEPNS_9ViewGroupE+1460)
    #06 pc 000000000066af0c  /data/app/org.ppsspp.ppsspp-awj6ylbuJCxDVI4S6SN11w==/lib/arm64/libppsspp_jni.so (_ZN10MainScreen6updateEv+16)
    #07 pc 0000000000741948  /data/app/org.ppsspp.ppsspp-awj6ylbuJCxDVI4S6SN11w==/lib/arm64/libppsspp_jni.so (_ZN13ScreenManager6updateEv+72)
    #08 pc 000000000064c900  /data/app/org.ppsspp.ppsspp-awj6ylbuJCxDVI4S6SN11w==/lib/arm64/libppsspp_jni.so (_Z12NativeUpdatev+276)
    #09 pc 0000000000645744  /data/app/org.ppsspp.ppsspp-awj6ylbuJCxDVI4S6SN11w==/lib/arm64/libppsspp_jni.so (Java_org_ppsspp_ppsspp_NativeActivity_runEGLRenderLoop+632)
    #10 pc 00000000000030a8  /data/app/org.ppsspp.ppsspp-awj6ylbuJCxDVI4S6SN11w==/oat/arm64/base.odex (offset 0x2000)
```

**Comment by Panderner** [comment]
@leopard20 any games affected?

**Comment by leopard20** [comment]
All games that I currently have on my device.

**Comment by Panderner** [comment]
Lastest build working is v1.10.3-238-g7d2b1952d
The issue started in v1.10.3-243-g49f1ac284

**Comment by Gamemulatorer** [comment]
ppsspp v1.10.3-243 still crashing

### crashlog
 org.ppsspp.ppsspp.NativeGLView{89b7e6e V.E..... ......I. 0,0-0,0}
07-28 13:53:45.851 I/PPSSPP  (24755): g_Config.screenRotation = 5
07-28 13:53:45.851 I/PPSSPPNativeActivity(24755): Setting requested rotation: 5 ('5') (onResume)
07-28 13:53:45.853 I/PPSSPPNativeActivity(24755): onResume
07-28 13:53:45.859 I/PPSSPP  (24755): NativeApp.resume() - resuming audio
07-28 13:53:45.859 I/PPSSPP  (24755): Calling OpenSLWrap_Init_T...
07-28 13:53:45.859 I/PPSSPP  (24755): Returned from OpenSLWrap_Init_T
07-28 13:53:45.886 D/PPSSPPSizeManager(24755): checkDisplayMeasurements: checking now
07-28 13:53:45.887 I/PPSSPP  (24755): NativeApp.setDisplayParameters(1213 x 720, dpi=300, refresh=56.06)
07-28 13:53:45.888 I/PPSSPPNativeActivity(24755): onAttachedToWindow
07-28 13:53:45.914 D/libc-netbsd(24755): [getaddrinfo]: hostname=report.ppsspp.org; servname=80; cache_mode=(null), netid=0; mark=0
07-28 13:53:45.918 D/libc-netbsd(394): [getaddrinfo]: hostname=report.ppsspp.org; servname=80; cache_mode=local, netid=101; mark=917605
07-28 13:53:46.026 D/libc-netbsd(394): res_queryN name = report.ppsspp.org, class = 1, type = 28
07-28 13:53:46.026 D/libc-netbsd(394): res_queryN name = report.ppsspp.org succeed
07-28 13:53:46.027 D/libc-netbsd(24755): getaddrinfo: report.ppsspp.org get result from proxy >>
07-28 13:53:46.028 E/PPSSPP  (24755): FlushSocket failed
07-28 13:53:46.030 E/PPSSPP  (24755): FlushSocket failed
07-28 13:53:46.116 I/PPSSPPSizeManager(24755): Correct orientation detected, resetting orientation counter.
07-28 13:53:46.117 D/PPSSPPSizeManager(24755): Surface created. pixelWidth=1280, pixelHeight=720 holder: android.view.SurfaceView$4@269a5f1e or: 6
07-28 13:53:46.117 I/PPSSPP  (24755): NativeApp.setDisplayParameters(1280 x 720, dpi=300, refresh=56.06)
07-28 13:53:46.117 I/PPSSPP  (24755): RecalcDPI: display_xres=1280 display_yres=720
07-28 13:53:46.117 I/PPSSPP  (24755): RecalcDPI: g_dpi=300.000000 g_dpi_scale_x=0.800000 g_dpi_scale_y=0.800000
07-28 13:53:46.117 I/PPSSPP  (24755): RecalcDPI: dp_xscale=0.800000 dp_yscale=0.800000
07-28 13:53:46.117 I/PPSSPP  (24755): RecalcDPI: dp_xres=1024 dp_yres=576
07-28 13:53:46.117 I/PPSSPP  (24755): RecalcDPI: pixel_xres=0 pixel_yres=0
07-28 13:53:46.117 I/PPSSPP  (24755): NativeResized - setting flag
07-28 13:53:46.117 D/PPSSPPSizeManager(24755): Setting fixed size 0 x 0
07-28 13:53:46.118 V/PPSSPPSizeManager(24755): surfaceChanged: isCreating:true holder: android.view.SurfaceView$4@269a5f1e
07-28 13:53:46.120 I/EglHelper(24755): eglInitialize = 1275, this = org.ppsspp.ppsspp.NativeGLView{89b7e6e V.E..... ......ID 0,0-1280,720}
07-28 13:53:46.120 I/EglHelper(24755): chooseConfig = 1275, this = org.ppsspp.ppsspp.NativeGLView{89b7e6e V.E..... ......ID 0,0-1280,720}
07-28 13:53:46.121 W/PPSSPPSizeManager(24755): Surface changed. Resolution: 1280x720 Format: 4
07-28 13:53:46.121 I/PPSSPP  (24755): NativeApp.backbufferResize(1280 x 720)
07-28 13:53:46.122 I/PPSSPP  (24755): RecalcDPI: display_xres=1280 display_yres=720
07-28 13:53:46.122 I/PPSSPP  (24755): RecalcDPI: g_dpi=300.000000 g_dpi_scale_x=0.800000 g_dpi_scale_y=0.800000
07-28 13:53:46.122 I/PPSSPP  (24755): RecalcDPI: dp_xscale=0.800000 dp_yscale=0.800000
07-28 13:53:46.122 I/PPSSPP  (24755): RecalcDPI: dp_xres=1024 dp_yres=576
07-28 13:53:46.122 I/PPSSPP  (24755): RecalcDPI: pixel_xres=1280 pixel_yres=720
07-28 13:53:46.122 I/PPSSPP  (24755): Size change detected (previously 0,0) - calling NativeResized()
07-28 13:53:46.122 I/PPSSPP  (24755): NativeResized - setting flag
07-28 13:53:46.123 I/DefaultContextFactory(24755): createContext = 1275, this = org.ppsspp.ppsspp.NativeGLView{89b7e6e V.E..... ......ID 0,0-1280,720}
07-28 13:53:46.124 I/PPSSPP  (24755): NativeApp.setDisplayParameters(1280 x 720, dpi=300, refresh=56.06)
07-28 13:53:46.135 D/PPSSPPSizeManager(24755): checkDisplayMeasurements: checking now
07-28 13:53:46.136 I/PPSSPP  (24755): NativeApp.setDisplayParameters(1280 x 720, dpi=300, refresh=56.06)
07-28 13:53:46.153 I/PPSSPP  (24755): NativeApp.displayInit() first time
07-28 13:53:46.153 I/PPSSPP  (24755): AndroidJavaEGLGraphicsContext::InitFromRenderThread
07-28 13:53:46.153 I/PPSSPP  (24755): GPU Vendor : ARM ; renderer: Mali-450 MP version str: OpenGL ES 2.0 ; GLSL version str: OpenGL ES GLSL ES 1.00
07-28 13:53:46.154 I/PPSSPP  (24755): Updating inflight frames to 2
07-28 13:53:46.158 I/PPSSPP  (24755): NativeInitGraphics
07-28 13:53:46.211 I/PPSSPP  (24755): Initializing TextDrawerAndroid with DPI scale 0.800000
07-28 13:53:46.211 I/PPSSPP  (24755): NativeInitGraphics completed
07-28 13:53:46.211 I/PPSSPP  (24755): Graphics initialized. Entering loop.
07-28 13:53:46.238 D/PPSSPPSizeManager(24755): checkDisplayMeasurements: checking now
07-28 13:53:46.240 I/PPSSPP  (24755): NativeApp.setDisplayParameters(1280 x 720, dpi=300, refresh=56.06)
07-28 13:53:46.566 I/PPSSPP  (24755): Running first frame (0)
07-28 13:53:46.700 I/PPSSPPSizeManager(24755): SystemUiVisibilityChange! visibility=7 navigationHidden: true
07-28 13:53:46.701 I/PPSSPPSizeManager(24755): decorView: 1280x720
07-28 13:53:46.711 D/PPSSPPSizeManager(24755): checkDisplayMeasurements: checking now
07-28 13:53:46.714 I/PPSSPP  (24755): NativeApp.setDisplayParameters(1280 x 720, dpi=300, refresh=56.06)
07-28 13:53:46.957 I/PPSSPP  (24755): [LOADER] Config saved (clearFailedGPUBackends): '/storage/sdcard0/PSP/SYSTEM/ppsspp.ini'
07-28 13:53:46.966 I/PPSSPP  (24755): [LOADER] Controller config saved: /storage/sdcard0/PSP/SYSTEM/controls.ini
07-28 13:53:47.051 I/PPSSPP  (24755): frameCommand 'event' 'mainscreen'
07-28 13:53:47.983 I/WindowState(1879): WIN DEATH: Window{168da34c u0 org.ppsspp.ppsspp/org.ppsspp.ppsspp.PpssppActivity}
07-28 13:53:47.983 E/InputDispatcher(1879): channel '168da34c org.ppsspp.ppsspp/org.ppsspp.ppsspp.PpssppActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

**Comment by sum2012** [comment]
@hrydgard 
It only crash on android.
Don't crash on windows
#13210

**Comment by hrydgard** [comment]
OK, I'll fix it.
