### ISSUE TITLE
ppsspp installiing tutorial?

### ISSUE THREAD

**Issue by onexzlayer95** [hrydgard/ppsspp#13230]

**Comment by unknownbrackets** [comment]
Tutorial:

Windows:
1. Download PPSSPP zip file.
2. Extract zip file somewhere.
3. Find something to celebrate your successful installation with.

Android:
1. Go to app store and search for PPSSPP.
2. Click Install.
3. Wait for download to complete in rapt anticipation.

macOS / Android / iOS:
See build instructions, this is harder.

-[Unknown]
