### ISSUE TITLE
[Libretro] The Libretro cores doesn't use new ashmem api

### ISSUE THREAD

**Issue by Swordfish90** [hrydgard/ppsspp#13240]
Since yesterday, application updates published on Google Play have a minimum targetSdk of 29, which mandates the use of the new [ashmem api](https://developer.android.com/about/versions/10/behavior-changes-10#shared-memory).

A few months back, I submitted a [pull request](https://github.com/hrydgard/ppsspp/pull/12611) for PPSSPP, but I don't think the Libretro Core is using the new code path, which results in a crash while loading games.

Sadly I'm not able to build the Android variant for the Libretro core for this [issue](https://github.com/libretro/libretro-super/issues/1457), but I'm attaching here a tentative fix which should expose the sdk version to the caller.

```diff
diff --git a/libretro/libretro.cpp b/libretro/libretro.cpp
index 4e2a6bf07..5934fc28b 100644
--- a/libretro/libretro.cpp
+++ b/libretro/libretro.cpp
@@ -3,6 +3,7 @@
 #include <thread>
 #include <atomic>
 #include <vector>
+#include <stdlib.h>
 
 #include "base/timeutil.h"
 #include "Common/ChunkFile.h"
@@ -32,6 +33,10 @@
 #include "libretro/libretro.h"
 #include "libretro/LibretroGraphicsContext.h"
 
+#if PPSSPP_PLATFORM(ANDROID)
+#include <sys/system_properties.h>
+#endif
+
 #define DIR_SEP "/"
 #ifdef _WIN32
 #define DIR_SEP_CHRS "/\\"
@@ -856,6 +861,15 @@ int System_GetPropertyInt(SystemProperty prop)
    {
       case SYSPROP_AUDIO_SAMPLE_RATE:
          return SAMPLERATE;
+#if PPSSPP_PLATFORM(ANDROID)
+      case SYSPROP_SYSTEMVERSION: {
+         char sdk[PROP_VALUE_MAX] = {0};
+         if (__system_property_get("ro.build.version.sdk", sdk) != 0) {
+            return atoi(sdk);
+         }
+         return -1;
+      }
+#endif
       default:
          break;
    }
```

Is anyone able to help me out with my build issues or to test if the fix works?

**Comment by hrydgard** [comment]
Was gonna do this now but you beat me to it!

**Comment by Swordfish90** [comment]
Glad I could help! :smile:
