### ISSUE TITLE
[iOS 14] PPSSPP crashes with JIT

### ISSUE THREAD

**Issue by xsm1997** [hrydgard/ppsspp#13255]
### What happens?
When connected to a debugger, things go normal.
When not connected to a debugger, PPSSPP crashes on all my games (tested 4) with JIT enabled. I am sure it is related to JIT because if I change to IR interpreter, things go normal but slow.

### What *should* happen?
Games run normally.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
iPad Pro 9.7 (1st generation), iPad OS 14 Public Beta 4, with no Apple developer program subscription (certificates expire after 8 days).
PPSSPP v1.10.3 self-compiled.

I think maybe Apple added some new security restrictions related to JIT. And maybe it is a bug to iOS or a temporary situation. When Apple finally releases iOS 14, I will test again.

**Comment by hrydgard** [comment]
Yeah, we've had reports of this before. I think the method we're using to fool it to believe it's running in the debugger is no longer working due to security fixes in iOS 14, and there's likely nothing that can be done about it without a jailbreak.

**Comment by i30817** [comment]
People have to face that buying apple is a terrible malinvestment.

**Comment by devinprater** [comment]
For some, like people with disabilities, it’s the only choice that allows one to use a phone, or tablet, productively. We just have to do the best we can with AltStore and other such tools. And with the IR Interpreter on my iPhone X R, even on iOS 14, it runs smoothly, unless the phone is under more-than-normal stress.
Devin Prater
d.prater@me.com
Https://devinprater.github.io

**Comment by hrydgard** [comment]
I'm gonna close this because I don't think there's anything we can do about the issue. Apple's gonna do what Apple wants to do, today they're blocking the JIT. I'm glad the iOS port is usable at least for people who have no choice.

**Comment by EhsanWaheed** [comment]
They’ve added jit support for iOS 14.2 and side loading via alt store also supports jit

**Comment by xsm1997** [comment]
@EhsanWaheed Which commit did them actually add JIT support for iOS 14.2？

**Comment by EhsanWaheed** [comment]
Hopefully but I think PPSSPP needs an update to use the iOS JIT as it crashes at the moment

**Comment by EhsanWaheed** [comment]
@hrydgard What do you reckon?

**Comment by xsm1997** [comment]
I ran JIT on PPSSPP successfully on my iPad mini 5 (iOS 14.2), by simply enabling the "Extended Virtual Addressing" capability in XCode 12.2. It seems that PPSSPP would run on iOS 14.2 normally with no additional modification. Enabling such capability needs an account in XCode and compile PPSSPP manually, whether with Apple Developer subscription or without. If PPSSPP releases a precompiled ipa with such capability enabled, we can also use AltStore or other approaches to sign the package and install on our iDevice.

**Comment by EhsanWaheed** [comment]
I guess it’s just a matter of testing and implementation into PPSSPP now . Ah thank god Apple has added JIT support regardless of their reason for the addition of it.

**Comment by jeeeyul** [comment]
> I ran JIT on PPSSPP successfully on my iPad mini 5 (iOS 14.2), by simply enabling the "Extended Virtual Addressing" capability in XCode 12.2. It seems that PPSSPP would run on iOS 14.2 normally with no additional modification. Enabling such capability needs an account in XCode and compile PPSSPP manually, whether with Apple Developer subscription or without. If PPSSPP releases a precompiled ipa with such capability enabled, we can also use AltStore or other approaches to sign the package and install on our iDevice.

Are you sure that the unmodified JIT just works with "EVA capability"?
I tried many times, however there was no luck. JIT did work only for X^W when connected with Xcode to debug.

Can you tell me little bit more detail? (used version of sdk or CLT...)

**Comment by xsm1997** [comment]
@jeeeyul I just enable the EVA capability, and it works without any special modifications. Did you compile PPSSPP in Release configuration? Some games will crash in Debug mode in this case, but work well in Release mode, while others work well even in Debug mode. Weird enough. Can you compile PPSSPP in release configuration, or try to play more games to see if it will still crash? For me, all the games I tested work well in Release mode (but with some graphics errors, which I have mentioned in another issue).

**Comment by jeeeyul** [comment]
@xsm1997 Yes, I did use `release` scheme.

These are what I did:
* I've tested on master branch and tag 1.10.3.
* I'v use Xcode12.2 & iOS 14.2(A10 iPhone7) & latest tool chain and SDK.
* I'v generate the project using below command:
```
cmake -DCMAKE_TOOLCHAIN_FILE=./cmake/Toolchains/ios.cmake -DIOS_PLATFORM=OS -H. -Bbuild.ios -GXcode
```
* I had to changed product identifier to sign the EVA entitlement.
* I added `Extended Virtual Addressing` to PPSSPP target.
* I configured signing identity.
* I had to made some change on `Cmake PostBuild Rules` on PPSSPP target since there were some tiny typos that makes manual build failure.

Then I build and launch using `release` without the `Debug executable` option to simulate running without debugging connection. 
These are what I got:

1. PPSSPP launched properly.
2. I launched Tekken6
3. I'v got these error logs with crash:
```
ERR  [MEMMAP] vm_remap failed (1) - could not remap from 10b1f8000 (offset 0) of size 4000 to 0x100010000
ERR  [MEMMAP] vm_remap failed (1) - could not remap from 10b1f8000 (offset 0) of size 4000 to 0x100810000
ERR  [MEMMAP] vm_remap failed (3) - could not remap from 10b1f8000 (offset 0) of size 4000 to 0x101010000
...
```

With debugging mode, everything did work well. 
When I launch the PPSSPP on iPhone itself, I had to see the errors that are exactly same with non-EVA.

Did I miss something?

**Comment by hrydgard** [comment]
@jeeeyul could you make a PR or just write some details of the postbuild rules typos you had to fix?

**Comment by jeeeyul** [comment]
> @jeeeyul could you make a PR or just write some details of the postbuild rules typos you had to fix?
> 
> (I'm gonna work a little on iOS soon so would be convenient)

I could not find which code generates this script, So I just paste result here:

original post script looks like
```bash
#!/bin/sh
set -e
if test "$CONFIGURATION" = "Debug"; then :
  cd /Users/jeeeyul/git/jeeeyul@github.com/ppsspp/build.ios
  mkdir -p "$(TARGET_BUILD_DIR)/$(FULL_PRODUCT_NAME)"
  tar -c -C /Users/jeeeyul/git/jeeeyul@github.com/ppsspp/build.ios --exclude .DS_Store --exclude .git assets *.png | tar -x -C "$(TARGET_BUILD_DIR)/$(FULL_PRODUCT_NAME)"
  /bin/bash /Users/jeeeyul/git/jeeeyul@github.com/ppsspp/ios/macbundle.sh "$(TARGET_BUILD_DIR)/$(FULL_PRODUCT_NAME)"
fi
...
```
Xcode did complain as: 
```
.../Script-32DE914AEA194C56A89D0E77.sh: line 12: TARGET_BUILD_DIR: command not found
.../Script-32DE914AEA194C56A89D0E77.sh: line 12: FULL_PRODUCT_NAME: command not found
.../Script-32DE914AEA194C56A89D0E77.sh: line 13: TARGET_BUILD_DIR: command not found
.../Script-32DE914AEA194C56A89D0E77.sh: line 13: FULL_PRODUCT_NAME: command not found
```
So I did replace all the command expressions to variable expression (`$(...)` → `${...}`):
```bash
#!/bin/sh
set -e
if test "$CONFIGURATION" = "Debug"; then :
  cd /Users/jeeeyul/git/jeeeyul@github.com/ppsspp/build.ios
  mkdir -p "${TARGET_BUILD_DIR}/${FULL_PRODUCT_NAME}"
  tar -c -C /Users/jeeeyul/git/jeeeyul@github.com/ppsspp/build.ios --exclude .DS_Store --exclude .git assets *.png | tar -x -C "${TARGET_BUILD_DIR}/${FULL_PRODUCT_NAME}"
  /bin/bash /Users/jeeeyul/git/jeeeyul@github.com/ppsspp/ios/macbundle.sh "${TARGET_BUILD_DIR}/${FULL_PRODUCT_NAME}"
fi
...
```

Thanks for your contribution!

**Comment by hrydgard** [comment]
Thanks, that will probably save me a few minutes of troubleshooting :)

**Comment by jeeeyul** [comment]
@hrydgard @xsm1997 JIT with EVA seems to need A12 or higher processor for current status. 
https://oatmealdome.me/blog/dolphinios-ver-3-1-1/

**Comment by hrydgard** [comment]
@jeeeyul  I figured out how to automatically fix the post-build parentheses, but still struggling a bit:

https://github.com/hrydgard/ppsspp/pull/13766

Any idea what I might be doing wrong?

**Comment by MrCapone** [comment]
Am i doing something wrong? I added **Extended Virtual Addressing** compatibility to PPSSPP target, but still can't use JIT on my iPhone 12 mini with iOS 14.4.

![Без имени](https://user-images.githubusercontent.com/5929042/107147343-1b51ad00-6980-11eb-9add-3357562a1feb.png)

**Comment by xsm1997** [comment]
@MrCapone iOS 14.4 blocked JIT again. I don't know what Apple want to do, but let Apple do the things they want. PPSSPP on a modern iOS device can run games perfectly without JIT.

**Comment by hrydgard** [comment]
Extended virtual addressing doesn't help us, we have workaround for that already. 

Indeed, regarding JIT, Apple's gonna do what Apple's gonna do :(

**Comment by iMonZ** [comment]
> People have to face that buying apple is a terrible malinvestment instead of expecting devs to subvert the user-hostile security apparatus around their products. If i were you i'd just place a notification with a big fat warning the first time PPSSPP is run on a apple platform that JIT is disabled because of apple's policy against JIT compilation so speed will be terrible and wash my hands off it otherwise.

What a bullshit!
Apple disabled JIT cause of really bad security issues with that.
They could enable that in iOS 15 again but let’s wait.
This kind of thing happened already with other features.
They enabled them then there was a security hole next update it’s disabled and in the next major release they enabled it again

**Comment by iMonZ** [comment]
> I'm gonna close this because I don't think there's anything we can do about the issue. Apple's gonna do what Apple wants to do, today they're blocking the JIT. I'm glad the iOS port is usable at least for people who have no choice.

Can you reopen the issue?
The app is still crashing and maybe you can add a check befor using JIT if it’s really available.

**Comment by hrydgard** [comment]
@iMonZ  I've tried to add such a check but haven't found a reliable way to tell if it's available or not.

**Comment by Spidy123222** [comment]
> @iMonZ  I've tried to add such a check but haven't found a reliable way to tell if it's available or not.

I'm not too experienced some stuff but does ppsspp detect if a debugger is attached? I have a tutorial for attaching a debugger to an app and use anywhere until restarted or app task ended. DolphinIOS and UTM has detection for debugging and are open source.

Here's link to tutorial [https://docs.google.com/document/d/11_jju27qzhH_epq9XS1SlIlaBDPfvekRRYs5NS_ze_U/edit](https://docs.google.com/document/d/11_jju27qzhH_epq9XS1SlIlaBDPfvekRRYs5NS_ze_U/edit) if you want to check it out. Works on any iOS that libimobiledevice works on which is right up to latest. I'll edit this post until I try the trick on ppsspp to see if it solves this issue

DolphinIOS Github: [https://github.com/OatmealDome/dolphin](https://github.com/OatmealDome/dolphin)

UTM GitHub: [https://github.com/utmapp/UTM](https://github.com/utmapp/UTM)

**Comment by loicpirez** [comment]
I enabled `Extended Virtual Addressing` too on build, and attach to existing process PPSSPP with Xcode 12.6.
I don't notice so much difference - even with interpreter set to JIT.
When I start to launch the app in debug mode (without attaching to existing process) the app crash.
I use Jitterbug to launch the app in debug mode. https://github.com/osy/Jitterbug
