### ISSUE TITLE
Sims 2 Castaways Softlocking when trying to enter the menu

### ISSUE THREAD

**Issue by boy13epic** [hrydgard/ppsspp#13257]
### What happens?
the game soft locks

### What *should* happen?
the game go to the menu

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
iPad 6 JIT,iOS and latest ppsspp orphis build

**Comment by boy13epic** [comment]
![Uploading DCE989EF-9D12-4EC6-A8A4-16DFB0328E1A.jpeg…]()

**Comment by HiImBrala** [comment]
Latest buildbot.orphis.net build,no softlocks.This is clearly issue of your settings or the .ISO itself,please next time don't open issue if you didn't check your issue with multiple people/devices.Glad you learnt something from this.
