### ISSUE TITLE
Harry Potter and the Goblet of Fire Stuck at Memory Stick Loading Screen 

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#13266]
I Have a problem when Harry Potter and the Goblet of Fire Stuck at Memory Stick Loading Screen. Same Problem as Crash Tag Team Racing when i overclocked to above 266 mhz
![Screenshot_2020-08-10-06-51-11-95_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/89743459-f4501680-dad5-11ea-9c97-6d37093e79f6.png)

**Comment by Panderner** [comment]
I'm sorry about that the saving is working I'm closing now

**Comment by Panderner** [comment]
Still stuck again in latest build

**Comment by hrydgard** [comment]
any idea which build it broke?

**Comment by Panderner** [comment]
Still happens in Stable Build

**Comment by shenweip** [comment]
Is this platform-specific? or not?

**Comment by unknownbrackets** [comment]
Isn't this the game that has a game bug which makes it break if you have certain amounts of free storage space, even on a real PSP?  Maybe I'm remembering wrong.

http://wololo.net/talk/viewtopic.php?t=37641

-[Unknown]

**Comment by hrydgard** [comment]
Heh. We should probably compat-ini ourselves around that....

**Comment by unknownbrackets** [comment]
I agree, and I think a few other games make the same math error.  Basically they treat the free space as a 32-bit integer, do some math on it, and so depending on how much exactly was free, Bad Things happen.

Here's what I was looking for:

https://github.com/hrydgard/ppsspp/commit/c4c581000f24ba118c6fe497d9495bd006aefca8

We could potentially force free space to like 1024 MB on those specific game IDs.

-[Unknown]

**Comment by hrydgard** [comment]
Would there be any ill effects to simply always cap to 1024 MB?

**Comment by unknownbrackets** [comment]
I don't know if any games would check free space before and after saving and complain, so ideally we shouldn't cap at all really.  But I guess no one has reported that...

Not sure if it would prevent converting longer battles to high-quality videos in Dissidia, or if there's any game installs over 1024 MB.  Those are the main ill effects I can imagine.

-[Unknown]

**Comment by hrydgard** [comment]
Alright. That's enough minor dangers that it's probably worth doing this game-specific. I'll add a compat.ini setting.

**Comment by Panderner** [comment]
it's seems #13512 fixed memory stick issues for this game and Street Fighter Alpha 3 Max (#10462) are now fixed I'm closing this.
