### ISSUE TITLE
(Libretro) (Android) Build failures

### ISSUE THREAD

**Issue by twinaphex** [hrydgard/ppsspp#13274]
### What happens?
Libretro core fails to compile for Android when running ndk-build (libretro/jni)

### What *should* happen?

It should finish compilation and linking and produce as output the libretro cores.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Windows/Linux, but irrelevant in this case. NDK is used for compilation.

@Swordfish90 Going to tag you here since I believe you were working on Android Libretro compilation earlier. I'm curious to see if you get the same build errors as we do on the buildbot. Here is the log -

http://paste.libretro.com/221216

**Comment by Swordfish90** [comment]
Hi @twinaphex . Sorry for the late reply, but I was on a work trip. Yesterday I tried a clean build on current master and I'm still able to get the so files using Ubuntu 20.04 and an the last update of ndk/sdk.

I've also checked the log and it seems to compile correctly, but somehow fails to to link the so files (which is something that I wasn't able to reproduce even before my fixes).

If you want to check them out you can find them here https://github.com/Swordfish90/LemuroidCores . I've tested the OpenGL renderer ant it works very well.

**Comment by unknownbrackets** [comment]
Is this still an issue?  #13559 for example references Android and libretro.

-[Unknown]

**Comment by twinaphex** [comment]
I'm going to assume this is outdated until further notice. My bad for not closing it sooner.
