### ISSUE TITLE
Valhalla knights 2 network stop at menu

### ISSUE THREAD

**Issue by Lemoncak3** [hrydgard/ppsspp#13279]
When try the network in Valhalla knights 2 and choose to host co-op i am stuck at the menu and have to restart, so basically it's not working. The screen shows nothing at all and i can't go back to previous menu either.
![Screenshot_20200813-003933](https://user-images.githubusercontent.com/67026697/90048681-0c09e380-dcfe-11ea-81da-7e67ae42048f.png)

**Comment by MojoJojoDojo** [comment]
You could try the orphis builds : https://buildbot.orphis.net/ppsspp/
They are currently not working so wait for them to be fixed.

**Comment by Lemoncak3** [comment]
After updating to the latest version of PPSSPP now it stops at the network notif message 
![Screenshot_20200816-045545](https://user-images.githubusercontent.com/67026697/90322292-dc1c4380-df7c-11ea-88ae-287f8960c57b.png)

**Comment by ANR2ME** [comment]
That screen is where it suppose to create the group using `sceNetAdhocctlCreateGroup` may be it failed to create the group and keeps trying, you need to make sure you're successfully connected to AdhocServer first (indicated by "Network Initialized" shown on screen)

Btw could you try again using the test build from this PR https://github.com/hrydgard/ppsspp/pull/13318
It supposed to have a better/fixed NetconfDialog possible issue.

**Comment by Lemoncak3** [comment]
I tried using the latest build of psp today, and it's no longer stuck at host screen but now it shows error and returned back to network menu
![Screenshot_20200904-221740](https://user-images.githubusercontent.com/67026697/92255930-3023a380-eefd-11ea-95d1-78ea5cb2cdfd.png)

**Comment by ANR2ME** [comment]
Internal error will be triggered if you failed to connect/create/join a group within 5 seconds, this to prevent it from stuck at "Connecting...." forever in the case you have connection issue to the Adhoc Server.

Make sure you are connected to Adhoc Server (when it shows "Network Initialized" on screen) and also check the Logs for Socket Error.

**Comment by ANR2ME** [comment]
I've checked the Logs, on localhost i'm not stuck on that screen it was able to connect successfully, but it can't see each other.

Apparently it first do `sceNetAdhocctlConnect` with an empty group name (`null`) and then later do `sceNetAdhocctlScan` while in connected state.

As i remembered from @adenovan  test on real PSP, we are allowed to Create a group with empty (null) group name.
But we are not allowed to Scan while i connected state.

PS: Normally, with laptop/smartphone we can Scan nearby AP without loosing connectivity to current AP, so i wonder why PSP adhoc can only do scan while not connected.

**Comment by adenovan** [comment]
its allowed on null for empty i forget looks like all hle still return 0 and updating the handler with error code , not much touching that yet auto test cannot dump the log..

log will be helpful there to trace it with adhoc homebrew tesf

**Comment by ANR2ME** [comment]
> 
> 
> its allowed on null for empty i forget looks like all hle still return 0 and updating the handler with error code , not much touching that yet auto test cannot dump the log..
> 
> log will be helpful here to trace it with adhoc homebrew test

Btw do you remembered what kind of value returned from Scan if it was already connected/joined to a group?

**Comment by ANR2ME** [comment]
Anyway, multiplayer works properly now on localhost
![image](https://user-images.githubusercontent.com/7974720/92290174-5a955100-ef3d-11ea-88ab-c99385135ec9.png)

However, @Lemoncak3 will need to solved the connection to Adhoc Server first before he can see other players.

**Comment by ANR2ME** [comment]
Btw @hrydgard Whenever i ran Valhalla Knights 2 with Debug x64 build and close down (clicking the [X] button) PPSSPP while in Start/Main Menu i always getting this crash
![image](https://user-images.githubusercontent.com/7974720/92291127-4d7a6100-ef41-11ea-9f49-4fe31776b61e.png)

**Comment by ANR2ME** [comment]
> 
> 
> Well the thing is in valhalla knight i never saw the network initialized thing. When in other game i saw it when i start the game or when entering network menu. I wish i could provide with log but i can't find anywhere in android...

Apparently there was a bug with the Group Creation where an error that supposed to be retried on blocking simulation didn't get retried and ended being a faked success (which is probably why you didn't see Network Initialized message)
Anyway, i've fixed that bug and the Scan bug on this PR https://github.com/hrydgard/ppsspp/pull/13383

**Comment by adenovan** [comment]
> > its allowed on null for empty i forget looks like all hle still return 0 and updating the handler with error code , not much touching that yet auto test cannot dump the log..
> > log will be helpful here to trace it with adhoc homebrew test
> 
> Btw do you remembered what kind of value returned from Scan if it was already connected/joined to a group?
> 
> Also, does Adhocctl handler being called even when error was returned from Connect/Create/Join/Scan/Disconnect?
> Does it still returning 0 on things that expected to get an error (ie. Joining a non-existing group may be) even when there are no handler being added?
> because currently PPSSPP will only trigger the callback handler when returning a success (faked or not)

this handler things need to be properly tested , as far as i remember it just return 0 with updated error code given to handler.

im not testing it on bad params yet to see how the handler got updated or not in case of false args we supply to the api its worth of test.

Multiplayer works without adhoc server is the way its officially implemented. signaling each other on psp its acquired through beacon broadcast of mac address in IEEE header LLC layer approx average latency around 20-30ms this what make game slow in transferring data , its spam rapidly to just tell presence to each other and its a bad things to do in general signaling ways.

adhoc server means to be inside somewhere of psp internal kernel address did not sure where is the original region on driver disassembly and its add the peer when its meets the beacon if there is none beacon shown its create one like another issues i create somewhere in adhoc server boot. 

its has sort of internal things gathering peer just like adhoc server did and its update the timestamp in the background.

**Comment by Gamemulatorer** [comment]
This should be added to v1.11.0 milestone
