### ISSUE TITLE
[Android] The downloads of "Automated PPSSPP builds" don't work

### ISSUE THREAD

**Issue by MiguelCardonaG** [hrydgard/ppsspp#13276]
### What happens?
Hello. 

I want to download the latest version of PPSSPP in build format but the website https://buildbot.orphis.net/ppsspp/ don't download the file properly, it does it at 0b.

![Screenshot_20200812-110127_Solid Explorer](https://user-images.githubusercontent.com/65356692/89996529-32db0200-dc8b-11ea-8167-1da80250ab82.jpg)

I've tried it with different web browsers and it all gives the same problem.

**Comment by MiguelCardonaG** [comment]
These versions fail and cannot be downloaded:

ppsspp-v1.10.3-380-g27c059bf9-android.apk
ppsspp-v1.10.3-379-gf617bfce2-android.apk

**Comment by Panderner** [comment]
it's seems the download link for PPSSPP latest builds for all platforms are down or corrupted.

**Comment by hrydgard** [comment]
will be fixed soon, orphis is working on it

**Comment by Panderner** [comment]
Last build link working to download is v1.10.3-377-gb2d6eef65. The Android build of v1.10.3-378-g14532847c is corrupted

**Comment by MiguelCardonaG** [comment]
The version ppsspp-v1.10.3-387-g6ca01d588-android.apk I've been able to download it right now. The others still don't work.

**Comment by MiguelCardonaG** [comment]
I'm going to close it because I see it's working well. No?

**Comment by Panderner** [comment]
Yes the latest builds of PPSSPP to download are working.
