### ISSUE TITLE
Recent games can't show up in recent menu after re-open PPSSPP

### ISSUE THREAD

**Issue by Halo-Michael** [hrydgard/ppsspp#13286]
![ImageOptim](https://github.com/Halo-Michael/PPSSPP-ULES01384_0001/raw/master/2020_08_15_13_41_IMG_2088.gif)

### What happens?
Recent games can't show up in recent menu after re-open PPSSPP.

### What *should* happen?
Recent menu shows up the new recent game after re-open PPSSPP.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
iPhoneSE2, iOS13.5, PPSSPP version is v1.10.3-387-g6ca01d588

Permission of /private/var/mobile/Documents is mobile:mobile 0777
Permission of /private/var/mobile/Documents/PSP, /private/var/mobile/Documents/PSP/SYSTEM, /private/var/mobile/Documents/PSP/SYSTEM/ppsspp.ini are mobile:mobile 0755
So can't be an issues of file permissions.

**Comment by hrydgard** [comment]
Is it just that no settings at all get saved?

**Comment by Halo-Michael** [comment]
> Is it just that no settings at all get saved?

Other settings can be saved like Language, UI Sound etc.

**Comment by unknownbrackets** [comment]
Has this always happened, or is it new - since which build?

If other settings update, but not recent, I would think that it's trying to add a path that it later thinks is not valid.  Maybe something about path handling in a new iOS version is returning paths that aren't consistent between runs for privacy reasons.

-[Unknown]

**Comment by Halo-Michael** [comment]
v1.6.3-456 saved recent successful but v1.8.0-433 are not.
I don't know if this is related to my build method. Since there is no official compiled version after 1.6.3, all subsequent versions are built by myself.
Since I have not added a new game for a long time, I am not sure if this problem exists in the previous system version.

**Comment by Halo-Michael** [comment]
I am pretty sure this should be a bug of ppsspp; ppsspp has full access to the control file, but for some reason, it did not write the recent game lists information into the control file when exiting.

**Comment by Halo-Michael** [comment]
I think I found the reason
This is the current version, what happens when the Exit button is clicked:
![QFL3`ISXCCQI1AWW_F1N7WC](https://user-images.githubusercontent.com/45062120/101289051-f1232800-3834-11eb-8324-d0c2068942cb.png)
This is the old version(v1.6.3-456), what happens when the Exit button is clicked:
![CJ~( JLZ(6K3B E`78B%QSM](https://user-images.githubusercontent.com/45062120/101289061-0730e880-3835-11eb-815f-f6bca1ef9f4e.png)
In the current version, the step to save data is missing when the Exit button is clicked. The temporary repair method is to click Settings-Back and then exit.

**Comment by Halo-Michael** [comment]
Some code about pre-exit processing is not executed at all

**Comment by Halo-Michael** [comment]
@hrydgard Can you check this?

**Comment by Halo-Michael** [comment]
Well, I was just worried before that if the creation time was too early and you could not see it lol

**Comment by hrydgard** [comment]
Ok, things are a little screwed up on exit. In MainScreen.cpp, we have:

```
	// Request the framework to exit cleanly.
	System_SendMessage("finish", "");

	// However, let's make sure the config was saved, since it may not have been.
	g_Config.Save("MainScreen::OnExit");
```

But the iOS implementation of "finish" just exits immediately:

```
void System_SendMessage(const char *command, const char *parameter) {
	if (!strcmp(command, "finish")) {
		exit(0);
		// The below seems right, but causes hangs. See #12140.
		// dispatch_async(dispatch_get_main_queue(), ^{
		// [sharedViewController shutdown];
		//	exit(0);
		// });
```

NativeShutdown calls "finish" at a somewhat saner point, but it will never execute since we already exited in OnExit.

I'll try to fix this up.

**Comment by Halo-Michael** [comment]
Fixed.
