### ISSUE TITLE
Figure out what to do with the framebuffer-clear optimization hack

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#13295]
We've long unintentionally (through forgetfulness) had a hack enabled that clears framebuffers on the first use - but only in OpenGL on mobile devices. After some cleanup, it's currently set like this in the FramebufferManagerCommon constructor:

```
clearFramebufferOnFirstUseHack_ = gl_extensions.IsGLES;
```

Basically, it forces a clear the first time we use a framebuffer during a frame. This is incorrect but seems to have few bad effects.

Clearing the framebuffer before drawing can be hugely beneficial on mobile chips (tiled renderers), since they can avoid loading the old framebuffer contents from main memory into tile memory. Some modern desktop chips can benefit too but not nearly as much. 

Since this is only enabled with OpenGL ES, it's possible that this could account for some reports of Vulkan being slower than GL on some devices (could of course also be driver issues or us doing something suboptimally, but...).

This could also be the cause of rendering bugs (effects that rely on previous frame data getting lost), though I don't know any that this is suspected of being the cause of.

Anyway, I see a few options:

* Also force-enable it on Vulkan for known "tiled" GPUs. Could introduce bugs.
* Enable it for everything (since the benefit it so tiny on non-tiled GPUs, probably not a good idea)
* Get rid of it entirely, slowing down GL ES
* Create a setting, default to true on tiled GPUs / mobile

Any other ideas?

**Comment by kage2051** [comment]
I don't think if it's related to your proposal, but in some games (God Eater Burst for example), you get slowdowns on Adreno devices when an enemy does a special attack. This is more noticeable in levels vs. Quadriga. There are also slowdowns at some parts in Final Fantasy Type-0 as well. Both issues happening on Vulkan only.

**Comment by Panderner** [comment]
@hrydgard what framebuffer-clear optimization hack mean?

**Comment by hrydgard** [comment]
@Panderner I added a sentence to the post above to clarify a little. Hope it's more understandable now.

**Comment by unknownbrackets** [comment]
I would propose a different option: add a setting, but default it false everywhere.  See what reports we get of problems / slower performance in games / fixes.  If it looks good, kill the setting.

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, I think @unknownbrackets plan might be one of the better options. Remains to be decided what to call it.

"Framebuffer Clear Speed Hack"?
"Clearing speedhack"
"Clear framebuffers on first use (speedhack)"

etc ...

**Comment by kage2051** [comment]
> "Framebuffer Clear Speed Hack"?
> "Clearing speedhack"
> "Clear framebuffers on first use (speedhack)"

Third name choice is more fitting.

**Comment by hrydgard** [comment]
I'm just also trying to think of the problems each name will cause for translators. I would not want to be the one to translate the last one to German in a way that fits on the screen :)

**Comment by hrydgard** [comment]
Bumping to 1.12 - what remains is removing the option, and I'll do it then.
