### ISSUE TITLE
Namco Museum Vol. 2 - ULJS00047 infinite loading in some game

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#13297]
No known version
(In fact test jpcsp first, then ppsspp)

The game only can load pacman,Moto
It is infinite loading in King & Balloon,Mappy,Dragon Spirit
The log below load pacman,Moto then King & Balloon.
v1.10.3-436-gc2c2ba7eb log: https://gist.github.com/sum2012/d6a86dca0fece099bc141d4480eb2544
debug log: 
[ppsspplog-v1.10.3-436-gc2c2ba7eb-debug.txt.zip](https://github.com/hrydgard/ppsspp/files/5084658/ppsspplog-v1.10.3-436-gc2c2ba7eb-debug.txt.zip)

From info log,It seem
42:36:539 Thread for L I[SCEKERNEL]: hle\scekernelthread.cpp:2155 sceKernelExitThread(-2147352152)
is wrong, should be https://github.com/jpcsp/jpcsp/blob/master/src/jpcsp/HLE/modules/ThreadManForUser.java#L3924

**Comment by hrydgard** [comment]
Most likely the cause will be related to #9523 which is a similar issue in Namco Museum - Battle Collection.

**Comment by sum2012** [comment]
Oh Yes,I have translated the error code to jpcsp. fixed the game .
Now I try to translate  the top part of the function .
