### ISSUE TITLE
InitLocalhostIP() (called from __sceNetInit) can block forever

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#13300]
When I tried starting PPSSPP on an old Samsung Galaxy S3 without an internet connection, it just sat there forever when trying to start the game. Turns out that getaddrinfo blocks forever.

So we really need to call that on a thread, once. Preferably either on app startup, or maybe on-demand the first time the LocalhostIP is needed?

Besides it's not entirely clear to me why we need getaddrinfo here anyway...

**Comment by hrydgard** [comment]
Hm, we are using getaddrinfo in DNSResolve in ext/native/net/resolve.cpp and it does not seem to have the problem. Maybe can change to its approach somehow...

**Comment by ANR2ME** [comment]
I kindda forgot what it actually do LOL
It seems the 1st part of the code just to fill LocalhostIP struct using instance number, so we can just use the fallback and skip the getaddrinfo
```
((sockaddr_in*)&LocalhostIP)->sin_family = AF_INET;
		((sockaddr_in*)&LocalhostIP)->sin_addr.s_addr = inet_addr(ipstr); //"127.0.0.1"
		((sockaddr_in*)&LocalhostIP)->sin_port = 0;
```

while the 2nd part of the code is to detects whether the adhoc server settings is resolved to 127.x.x.x or not, to indicate whether the adhoc server is located on the same PC or not. 
Since adhoc server is a string we eventually need to resolve the dns somehow.. i'll try to replace it with net::DNSResolve

**Comment by ANR2ME** [comment]
Will this code fix it?

```
void InitLocalhostIP() {
	// find local IP
	addrinfo* localAddr;
	addrinfo* ptr;
	char ipstr[INET_ADDRSTRLEN];
	sprintf(ipstr, "127.0.0.%u", PPSSPP_ID);	
	((sockaddr_in*)&LocalhostIP)->sin_family = AF_INET;
	((sockaddr_in*)&LocalhostIP)->sin_addr.s_addr = inet_addr(ipstr);
	((sockaddr_in*)&LocalhostIP)->sin_port = 0;

	// Resolve server dns
	addrinfo* resolved = nullptr;
	std::string err;
	in_addr serverIp;
	serverIp.s_addr = INADDR_NONE;
	net::DNSResolve(g_Config.proAdhocServer, "80", &resolved, err);
	if (resolved) {
		for (ptr = resolved; ptr != NULL; ptr = ptr->ai_next) {
			switch (ptr->ai_family) {
			case AF_INET:
				serverIp = ((sockaddr_in*)ptr->ai_addr)->sin_addr;
				break;
			}
		}
		isLocalServer = (((uint8_t*)&serverIp.s_addr)[0] == 0x7f);
		net::DNSResolveFree(resolved);
	}
	else {
		std::string serverStr = g_Config.proAdhocServer;
		// TODO: trims and transform the string to lowercase before checking
		isLocalServer = (serverStr == "localhost" || serverStr.find("127.") == 0);
	}
}
```

**Comment by ANR2ME** [comment]
Oh well we should just avoid using getaddinfo and just test the adhoc server setting against "localhost" or prefixed with "127."

**Comment by hrydgard** [comment]
It does have getaddrinfo, it just seems to block when asking for 127.0.0.1 even if no network. Kinda useless to do that lookup though...

I'll test and merge #13302 tonight.

**Comment by ANR2ME** [comment]
yeah, apparently getaddrinfo is a blocking function https://stackoverflow.com/questions/25479011/getaddrinfo-blocks-the-application-in-android-if-no-internet

**Comment by hrydgard** [comment]
I think if we can just wait to call getaddrinfo until later, when the player is actually trying to connect, then it's not so bad. What I really want to avoid is blocking during initialization...

**Comment by hrydgard** [comment]
PPSSPP has some trim functions in ext/native/base/stringutil.h  .  (StripSpaces and friends)

**Comment by ANR2ME** [comment]
> 
> 
> I think if we can just wait to call getaddrinfo until later, when the player is actually trying to connect, then it's not so bad. What I really want to avoid is blocking during initialization...

It's probably too complicated just to test for 127.x.x.x IP LOL we should just checks the string

**Comment by hrydgard** [comment]
Yeah :)

**Comment by unknownbrackets** [comment]
It may be enough to check specifically `localhost` and starts with `127.`.  If that check was removed, would it not hang?

-[Unknown]
