### ISSUE TITLE
Outrun 2006 C2C: Glitches in BUFFERED graphics mode / latest git build

### ISSUE THREAD

**Issue by emuchicken** [hrydgard/ppsspp#13308]
### What happens?
When selecting buffered / graphics settings, texture glitches on cars.  Get pink cars instead of red, other cars also display strangely. Earlier psspp 1.9.1 worked fine

### What *should* happen?
Textures should display red / real colours

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Tried win10 *both x64 and 32bit*, PPSSPP v1.10.3-461-g0752e7d15 *both x64 and x86 versions*  Geforce 750ti and 1060 - same issues.
Looks like:

![2020-08-19 10_08_01-PPSSPP v1 10 3-461-g0752e7d15 - ULES00262 _ OUTRUN 2006_ COAST 2 COAST](https://user-images.githubusercontent.com/45140115/90580680-6d511b80-e204-11ea-8c56-9feea9d4b321.png)

Should look like (or similar to) - unbuffered mode
![2020-08-19 10_07_29-PPSSPP v1 10 3-461-g0752e7d15 - ULES00262 _ OUTRUN 2006_ COAST 2 COAST](https://user-images.githubusercontent.com/45140115/90580681-6e824880-e204-11ea-89b7-44d7f2fef324.png)

**Comment by Panderner** [comment]
![Screenshot_2020-10-15-14-50-27-00_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/96087246-24f96580-0ef6-11eb-921a-46de0debf397.png)
Here's a GE Dump:
[GE Dump.zip](https://github.com/hrydgard/ppsspp/files/5382938/GE.Dump.zip)

**Comment by Panderner** [comment]
@emuchicken last build worked?

**Comment by emuchicken** [comment]
Yes. I believe so

**Comment by Panderner** [comment]
@emuchicken don't close it when it's not fixed. any last build worked for previous versions of PPSSPP?

**Comment by thedax** [comment]
This issue was fixed in #13640 for Vulkan and GLES3 (and desktop OpenGL), but it is worth noting, however, that GLES2 and D3D9 still have the problem (and maybe always will?).

**Comment by Panderner** [comment]
But how about this?

Disable slower effects on:
![Screenshot_2020-11-09-18-45-46-77_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/98531816-dbfdbc80-22bb-11eb-9bfa-0f2206b1bc0f.png)

Disable slower effects off:
![Screenshot_2020-11-09-18-45-26-75_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/98531865-e5872480-22bb-11eb-9213-f9f1df04eba9.png)

**Comment by hrydgard** [comment]
Top picture looks ok-ish to me? If it looks wrong in "Disable slower effects off", that's ok, that setting will break graphics to gain speed.

**Comment by hrydgard** [comment]
Anyway, water is still not solid - sometimes it works, sometimes it doesn't, I don't understand it.

**Comment by Panderner** [comment]
> Top picture looks ok-ish to me? If it looks wrong in "Disable slower effects off", that's ok, that setting will break graphics to gain speed.

but how about the screenshot for real PSP?

**Comment by hrydgard** [comment]
Actually the top one looks like it has some of the blue tint from before my latest fix... Hm. Might be related to the error seen in #13639

**Comment by Panderner** [comment]
![Screenshot_2020-11-09-22-09-40-75_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/98551674-8c79b980-22d8-11eb-8819-e70847e01688.png)
it seems the black tint still wrong.

**Comment by hrydgard** [comment]
Yeah that's no good, but this should help: #13646

**Comment by Panderner** [comment]
The latest build broke again:
![Screenshot_2020-11-16-10-35-02-10_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/99206875-70ee4180-27f7-11eb-8365-ece603119b02.png)

**Comment by hrydgard** [comment]
Alright, i've figured out what's going on there, we're using a ES 310 feature in ES 300. 

Gonna fix it soon.

**Comment by Panderner** [comment]
![Screenshot_2020-11-25-19-19-11-47_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/100221067-26856700-2f53-11eb-88b5-8b445f1cc5a1.png)
The color reflection is now fixed by #13669.
