### ISSUE TITLE
Dead Head Fred FMV Videos Broken Since v1.10.3-352-gd90630c26

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#13317]
As the title says #13262 breaks Dead Head Fred FMV Videos as result of FMV Video Doesn't display at all.

Last build working is v1.10.3-348-gdd79d33f1
Issue Started in v1.10.3-352-gd90630c26

**Comment by hrydgard** [comment]
Vulkan only or other backends too?

**Comment by Panderner** [comment]
i'm using OpenGL

**Comment by hrydgard** [comment]
Unfortunately, just discovered that #13262 also broke shadows in the God of War games.

**Comment by Panderner** [comment]
They Confirmed that #13329 fixed video issue. The videos display properly I'm closing it now.
