### ISSUE TITLE
Street fighter alpha3 save bug

### ISSUE THREAD

**Issue by Adnan1091** [hrydgard/ppsspp#13316]
#7780 but it happens on retroarchARM64.I have tried deleting the PSP file but still no luck.Also checked writing permissions,tried older cores but no luck.Only this game has save issues.

**Comment by Adnan1091** [comment]
I haven't tested it for a while but after the update i don.t experience this issue anymore.Can anyone verify this?

**Comment by hrydgard** [comment]
I think this should be fixed now.
