### ISSUE TITLE
[Android] [GLES] [MALI] X-MEN Origin Wolverine wacky graphics glitches

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#13310]
### What happens?
This game has multiple graphics glitches issue only on mali gpu w/ gles2? Related #11598 ?
![Screenshot_2020-08-19-12-10-22](https://user-images.githubusercontent.com/37603562/90591530-ec028480-e215-11ea-9fd6-791c9b883bf8.png)
![Screenshot_2020-08-19-12-10-03](https://user-images.githubusercontent.com/37603562/90591564-fde42780-e215-11ea-97a8-cee69c990ab5.png)
![Screenshot_2020-08-19-12-13-06](https://user-images.githubusercontent.com/37603562/90591589-0b99ad00-e216-11ea-9d92-5d60e61b04fb.png)

### What *should* happen?
No multiple graphics glitches

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Android OS
Mali-450 GPU
PPSSPP v1.10.3-452
GE Dump 
[X-men origin wolverine.zip](https://github.com/hrydgard/ppsspp/files/5093968/X-men.origin.wolverine.zip)

**Comment by Panderner** [comment]
![Screenshot_2020-08-19-18-47-48-40_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/90625824-bb8a0d00-e24c-11ea-853d-3ac6adaac27e.png)
![Screenshot_2020-08-19-18-47-59-08_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/90625868-c8a6fc00-e24c-11ea-95f9-ce5f220513a8.png)
![Screenshot_2020-08-19-18-48-49-81_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/90625891-d5c3eb00-e24c-11ea-8e95-7281d3599b31.png)
@Gamemulatorer i can't produce this issue for me i'm using Realme C2

**Comment by Gamemulatorer** [comment]
> ### What happens?

> ![Screenshot_2020-08-19-12-10-22](https://user-images.githubusercontent.com/37603562/90591530-ec028480-e215-11ea-9fd6-791c9b883bf8.png)
> ![Screenshot_2020-08-19-12-10-03](https://user-images.githubusercontent.com/37603562/90591564-fde42780-e215-11ea-97a8-cee69c990ab5.png)
> ![Screenshot_2020-08-19-12-13-06](https://user-images.githubusercontent.com/37603562/90591589-0b99ad00-e216-11ea-9d92-5d60e61b04fb.png)
> 
> ### What _should_ happen?
> No multiple graphics glitches
> 
> ### What hardware, operating system, and PPSSPP version? On desktop, GPU matters for graphical issues.
> Android OS
> Mali-450 GPU
> PPSSPP v1.10.3-452
> GE Dump
> [X-men origin wolverine.zip](https://github.com/hrydgard/ppsspp/files/5093968/X-men.origin.wolverine.zip)



> ![Screenshot_2020-08-19-18-47-48-40_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/90625824-bb8a0d00-e24c-11ea-853d-3ac6adaac27e.png)
> ![Screenshot_2020-08-19-18-47-59-08_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/90625868-c8a6fc00-e24c-11ea-95f9-ce5f220513a8.png)
> ![Screenshot_2020-08-19-18-48-49-81_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/90625891-d5c3eb00-e24c-11ea-8e95-7281d3599b31.png)
> @Gamemulatorer i can't produce this issue for me i'm using Realme C2

Because
> This game has multiple graphics glitches issue only on mali gpu w/ gles2? Related #11598 ?

**Comment by Panderner** [comment]
@Gamemulatorer Do you have any GLES3 Devices?

**Comment by hrydgard** [comment]
Some of this could very well be due to the lack of ability to copy depth buffers on GLES 2.0, which is not really fixable (there are hacks we could do with sharing depth buffers as well but effectively that results in broken stencil instead). This does look weird though...

**Comment by Gamemulatorer** [comment]
But this can be fixed by enabling disable slower effects 🎉🎊
![Screenshot_2020-08-19-21-50-48](https://user-images.githubusercontent.com/37603562/90643492-41668200-e266-11ea-91cd-dccbf639a3e5.png)
![Screenshot_2020-08-19-21-51-08](https://user-images.githubusercontent.com/37603562/90643528-475c6300-e266-11ea-92cf-b21331dd9b0a.png)

I think is a good idea to add compat.ini "forcedisableslowereffects " for this game, Indiana Jones and call of duty or any other games that similar affected by this issue on gles2 devices?

**Comment by Panderner** [comment]
Some games requires to turn off disable slower effects like The Simpsons, Tenkaichi Tag Team and Sonic Games to render the graphics properly.

**Comment by Gamemulatorer** [comment]
> But this can be fixed by enabling disable slower effects 🎉🎊
> ![Screenshot_2020-08-19-21-50-48](https://user-images.githubusercontent.com/37603562/90643492-41668200-e266-11ea-91cd-dccbf639a3e5.png)
> ![Screenshot_2020-08-19-21-51-08](https://user-images.githubusercontent.com/37603562/90643528-475c6300-e266-11ea-92cf-b21331dd9b0a.png)
> 


> Some games requires to turn off disable slower effects like The Simpsons, Tenkaichi Tag Team and Sonic Games to render the graphics properly.

Kindly read and understand this again.. 😀
> I think is a good idea to add compat.ini "forcedisableslowereffects " for this game, Indiana Jones and call of duty or any other games that similar affected by this issue on gles2 devices?

**Comment by Gamemulatorer** [comment]
> > But this can be fixed by enabling disable slower effects 🎉🎊
> > ![Screenshot_2020-08-19-21-50-48](https://user-images.githubusercontent.com/37603562/90643492-41668200-e266-11ea-91cd-dccbf639a3e5.png)
> > ![Screenshot_2020-08-19-21-51-08](https://user-images.githubusercontent.com/37603562/90643528-475c6300-e266-11ea-92cf-b21331dd9b0a.png)
> 
> > Some games requires to turn off disable slower effects like The Simpsons, Tenkaichi Tag Team and Sonic Games to render the graphics properly.
> 


> Some games requires to turn off disable slower effects like The Simpsons, Tenkaichi Tag Team and Sonic Games to render the graphics properly.

@Panderner kindly read and understand this sentence again.. 😀
> 
> > I think is a good idea to add compat.ini "forcedisableslowereffects " for this game, Indiana Jones and call of duty or any other games that similar affected by this issue on gles2 devices?

**Comment by Gamemulatorer** [comment]
> > Some games requires to turn off disable slower effects like The Simpsons, Tenkaichi Tag Team and Sonic Games to render the graphics properly.
> 
> @Panderner kindly read and understand this sentence again.. 😀
> 
> > > I think is a good idea to add compat.ini "forcedisableslowereffects " for this game, Indiana Jones and call of duty or any other games that similar affected by this issue on gles2 devices?

**Comment by Gamemulatorer** [comment]
I have my new redmi note 9 in this issue cannot reproduce this so I'm going to close this issue because OGL 2.0 is too old and hard to fixed by devs :)
![Screenshot_2021-05-02-21-12-13-403_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/116814375-3bfa5f00-ab8b-11eb-9576-8891fe1b2c9c.jpg)

**Comment by Panderner** [comment]
umm yeah it's a Mali GLES 2.0 driver bug.
