### ISSUE TITLE
Vertex cache broken in Vulkan

### ISSUE THREAD

**Issue by Anuskuss** [hrydgard/ppsspp#13324]
Enabling vertex cache makes [Quake 2 [hardware]](https://gbatemp.net/download/quake-ii-hardware.28816/) stutter **only** in Vulkan.

**Comment by unknownbrackets** [comment]
As noted in #12969, GLES/OpenGL still doesn't ever use vertex caching.  If you're comparing to GLES/OpenGL, it might just be that vertex caching makes this game stutter whenever enabled, which wouldn't necessarily shock me.

-[Unknown]

**Comment by Anuskuss** [comment]
Does Vertex Cache work in the Direct3D variants? Because only Vulkan is affected when enabled.

**Comment by hrydgard** [comment]
It does, so yeah, this is rather odd and should probably be investigated at some point.

**Comment by Gamemulatorer** [comment]
How about this now after https://github.com/hrydgard/ppsspp/pull/16104

**Comment by Anuskuss** [comment]
@Gamemulatorer This is not a stutter issue, it's a Vertex Cache issue.

Although interestingly enough a recent commit (between stable and now) seems to have broken transparency in that game. A dev should look into that.

**Comment by hrydgard** [comment]
Hm, indeed: 

![image](https://user-images.githubusercontent.com/130929/192358856-d66d1612-613e-4d88-b6a4-31353a8685c2.png)

**Comment by unknownbrackets** [comment]
Maybe something with color test them, framedump?

-[Unknown]

**Comment by hrydgard** [comment]
dump: 
[Quake transparency QUAK00553_0001.zip](https://github.com/hrydgard/ppsspp/files/9648963/Quake.transparency.QUAK00553_0001.zip)

**Comment by hrydgard** [comment]
Ah, u_alphacolorref can't be passed to roundAndScaleTo8x4 since it's 255 times too large, being passed in as integers.

I'll fix.

**Comment by hrydgard** [comment]
Also confirmed that this is still an issue, it does not work well with the vertex cache, spends crazy amounts of time in cache hashmap lookups for some reason.

**Comment by hrydgard** [comment]
Ah, switching the PreHashMap to a DenseHashMap mostly fixes it, what we use as keys for it must not be very well distributed..

**Comment by hrydgard** [comment]
Threw in a simple fix.

**Comment by Anuskuss** [comment]
Thanks, both issues have been fixed. Although that nullprogram.com link you mentioned links to an even better solution by TheIronBorn. But I don't know if you could just use that and if it even matters.

Now the questions remains: Does Vertex Cache even do something? If the best-case is better and the worst-case is equal performance, can this option be removed (always on)? What games start to flicker when enabled?

**Comment by hrydgard** [comment]
It does still give a very small benefit in some games by avoiding decoding the same vertices over and over every frame.

But I am also inclined to get rid of it...

**Comment by Gamemulatorer** [comment]
This pr https://github.com/hrydgard/ppsspp/pull/15103 might improve vertex cache?

**Comment by unknownbrackets** [comment]
Many games flicker, although it usually requires you wait a bit and happens more often with 2D graphics (including UI.)  An example would be text dialog on menus in games, if you sit for a while staring at it, and then change - it'll glitch out.  I seem to remember FF4 also had a lot of problems with it.

Generally, when it was on by default, people would create issues for all sorts of weird rendering glitches, and they'd end up not happening when the setting is off.  So if the speed benefit is small, it's imho not worth it.  Maybe we could determine games that use weights or something in a way that's safe, and allow it to be used on a case by case basis.

-[Unknown]
