### ISSUE TITLE
Black or noisy turning pages animation in Valkyria Chronicles II (ULUS10515_1.00)

### ISSUE THREAD

**Issue by justafella** [hrydgard/ppsspp#13320]
### What happens?
While going through the pages of the Yearbook (or anything with pages to turn) in Valkirya Chronicles II (ULUS10515_1.00) the turning pages animation becomes all black or noisy. Not something to keep me or people from playing but I thought I should report anyway.

### What *should* happen?
Pages should look like they are.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

- Windows 10 64 bit;
- Acer Aspire ES15;
- Intel Celeron QuadCore N3450;
- Intel HD Graphics 500 (driver ver. 27.20.100.8476);
- ppsspp-v1.10.3-470-ge8779fdc8-windows-amd64

### Additional Info
- Tried all the backends but none displayed the turning pages correctly;
- Tried different rendering resolutions;
- Tried turning on/off other options like Mode (Non-buffered & Buffered), Simulate block transfer effects, Vsync, Hardware transform, Software skinning, Hardware tesselation, Anisotropic filtering.
- I have recorded what happens and I have made a save state. If there is any way to make them available for you to take a closer look, just tell me.

P.S: I searched around to see if this issue had already been reported. I'm sorry if it turns out to be a duplicate.

**Comment by unknownbrackets** [comment]
Thanks for the report.

-[Unknown]

**Comment by justafella** [comment]
Tested the latest build and the issue persists if going back and forth the same page. Also, the pages don't look noisy anymore, but all black.

**Comment by unknownbrackets** [comment]
Ah, okay, the rest of this is caused by depth texturing.

Basically, we end up with no framebuffer attached, but also the texture released by ReleaseTexture in AttachFramebufferValid or AttachFramebufferInvalid.

```
Attach framebuf and release tex: 04114000
Creating FBO for 04114000 (z: 04088000) : 256 x 256 x 0
Saved safe size (256x256) 04114000 to 04134000
Decimating FBO for 04114000 (256 x 256 x 0), age 6
Detach framebuf (tex now dead): 04114000
```

The reason?  It xors the hash twice, making it all the way back to the original hash and preventing rebuild.

-[Unknown]
