### ISSUE TITLE
[Transrate/Localize][Japanese] Games list settings menu

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#13323]
@hrydgard 

Hello,Master.

When you'd make it reference of a Japanese translation, I'm happy.

Games list settings
  各ゲームリストの表示設定

Display"Recent" on a grid
  "履歴"をグリッド表示にする

Display"Games" on a grid
  "ゲーム"をグリッド表示にする

Display"Homebrew & Demos"" on a grid
  "自作ソフトとデモ"をグリッド表示にする

Grid icon size
  グリッド表示時のアイコンサイズ調整

Increase size
  サイズを拡大する

Decrease size
  サイズを縮小する

Display extra info
　拡張情報の表示/非表示

Show ID
  ゲームIDの表示

Show region flag
  対応言語の国旗を表示

Clear "Recent"
  履歴のクリア

Thank you.

**Comment by nassau-tk** [comment]
@sum2012 
@hrydgard 

Excuse me?
I don't have right knowledge to a modification method.
But...I think there are several mistakes.

**==Should not change below==**
372 Remove From Recent = 履歴から削除する <==Correct
372 Remove From Recent = 履歴のクリア        <==Not Correct

546 Games = ゲーム                                          <==Correct
546 Games = "ゲーム"をグリッド表示にする   <==Not Correct

549 Homebrew & Demos = 自作ソフトとデモ                                        <==Correct
549 Homebrew & Demos = "自作ソフトとデモ"をグリッド表示にする <==Not Correct

556 Recent = 履歴                                            <==Correct
556 Recent = "履歴"をグリッド表示にする     <==Not Correct



**==Should change below==**

953 Display Games on a grid = グリッドに「ゲーム」を表示する
**Change to**==> 953 Display Games on a grid = "ゲーム"をグリッド表示にする


954 Display Homebrew on a grid = グリッドに「自作ソフトとデモ」を表示する
**Change to**==>954 Display Homebrew on a grid = "自作ソフトとデモ"をグリッド表示にする

955Display Recent on a grid = グリッドに「履歴」を表示する
**Change to** ==>955 Display Recent on a grid = "履歴"をグリッド表示にする

**== ? ? ? ==**
I can't find the text "Clear Recent" = 履歴のクリア.
Please, see the screen shot.
![jp_text](https://user-images.githubusercontent.com/48179091/91072646-c7266b00-e674-11ea-9037-1bc02cede807.png)

 I think other fixs are no problem.

**Comment by sum2012** [comment]
![1](https://user-images.githubusercontent.com/2177532/91103954-5183c480-e69f-11ea-9769-32d9dc5de336.png)

I go out to work now,I will come back 7:30 pm in Hong Kong time

**Comment by nassau-tk** [comment]
@sum2012 

Yes!!

P.S. I love HongKong!!

**Comment by sum2012** [comment]
v1.10.3-486-g3574a352d have updated lang for this main project
Please check the japan lang.

**Comment by nassau-tk** [comment]
@sum2012 

Great!!
Perfect!!

**Comment by gary-ts** [comment]
@nassau-tk @sum2012 
See https://github.com/hrydgard/ppsspp-lang/pull/773#issuecomment-686246477 please.
