### ISSUE TITLE
? What happend to burnout blcksunsquare in buildbot

### ISSUE THREAD

**Issue by PilipinoAko** [hrydgard/ppsspp#13332]
### What happens?
Squarebox like old bugs

### What *should* happen?
Ummm remove or vgpur get back?

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Latest build yes
ppsspp-v1.10.3-485-g13552550b
Vivo y53 
2gb ram 16 gb rom
Snapdragon 425 
Adreno 308 lowest adreno gpu 
64 bit
![Screenshot_20200825_183021](https://user-images.githubusercontent.com/52031664/91168521-5af54700-e708-11ea-9ffc-07ae8daeeb7c.jpg)

**Comment by Panderner** [comment]
@PilipinoAko are you using a latest build?

**Comment by hrydgard** [comment]
Also, have you turned off any slow effects or block transfers?

**Comment by sum2012** [comment]
v1.10.3-486-g3574a352d WINDOWS 64 bit
opengl and valkan also no problem
![1](https://user-images.githubusercontent.com/2177532/91178021-2341cb80-e717-11ea-9f97-3921c4097ba7.jpg)

**Comment by sum2012** [comment]
I test black shark 3 android phone also no problem with default setting

**Comment by Panderner** [comment]
![Screenshot_2020-08-25-21-26-08-12_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/91179860-a2380380-e719-11ea-9a8b-8df3963dbf1f.png)
No problem for this game running on Realme C2 in default settings

**Comment by PilipinoAko** [comment]
Btw ist not black square in playstore version..

And i think th le merge
![Screenshot_20200824_164738](https://user-images.githubusercontent.com/52031664/91227418-0a5a0a00-e759-11ea-8229-852b83c71735.jpg)

**Comment by PilipinoAko** [comment]
And im in defualt settings
![Screenshot_20200826_045424](https://user-images.githubusercontent.com/52031664/91227521-3d040280-e759-11ea-912e-ba5954fb1ea4.jpg)
![Uploading Screenshot_20200826_045424.jpg…]()

**Comment by PilipinoAko** [comment]
> v1.10.3-486-g3574a352d WINDOWS 64 bit
> opengl and valkan also no problem
> ![1](https://user-images.githubusercontent.com/2177532/91178021-2341cb80-e717-11ea-9f97-3921c4097ba7.jpg)



No shadow send cwc or not?

**Comment by Panderner** [comment]
> v1.10.3-486-g3574a352d WINDOWS 64 bit
> opengl and valkan also no problem
> ![1](https://user-images.githubusercontent.com/2177532/91178021-2341cb80-e717-11ea-9f97-3921c4097ba7.jpg)

@sum2012 the screenshot has missing shadows but the sun's ok have you tried Direct3D 9 and Direct3D 11?

**Comment by sum2012** [comment]
I don't know why this time all gpu backend (opengl,dx9,dx11 and vulkan) have shadows 
![1](https://user-images.githubusercontent.com/2177532/91307654-d5919580-e7e0-11ea-8ba2-04e796c3f4b3.jpg)

**Comment by Gamemulatorer** [comment]
Could you try the latest PPSSPP buildbot apk @PilipinoAko it seems fixes some graphics glitch on the latest git build.

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
