### ISSUE TITLE
[Android/Windows][Graphic issue] Not work blur processing & Graphic missing issue [Danball Senki series]

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#13338]
### What happens?
Isn't the blur processing active in any games?
Example)
Danball Senki & Dunball Senki Boost (When Enter the menu screen.
~Bleach SoulCarnival2 (When Enter the menu screen.~ solved v1.10.3-1705

I'm poor at my English. (Both Read&Write)
But,I read this issue. #5918
And understood that blur processing is too difficult issue.
So,I think blur processing tunring off now on PPSSPP.
But,other issue happen the processing.
Causality of blur processing and background drawing isn't understood, but you make them report and can I have it?

Please check strange point by attached Screen shot.

### What *should* happen?
blur processing is performed right.
or
Background graphic draw correctly.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
PPSSPP Ver. : 1.10.3-486
OS: Android 9.0
DeviceName: SONY SO-02K / Xperia XZ1 Compact (Japan)
CPU: Snapdragon835 (Octa-core)
GPU: Adreno 540
Resolution: 720×1280
RAM: 4GB
ROM:32GB
ExternalStrage: microSDXC 512GB

PPSSPP Ver.：1.10.3-486
OS：Windows10 (64-bit) Japanese
CPU：Ryzen7 3800X（8-core）
GPU：RADEON RADEON RX5700XT
Resolution：2560×1440
RAM：24GB

**[ Real PSP Danball Senki ]==> blur processing ON & Drawing the character graphics.**
![DunballSenki_Menu_blur_RealPSP](https://user-images.githubusercontent.com/48179091/91383764-e3d6c480-e867-11ea-8bdf-8922968a0d2b.gif)

**There is girl & white robot.**

**[ PPSSPP Danball Senki ]==> No blur processing & Missing the character graphics.**
![DunballSenki_Menu_blur_PPSSPP](https://user-images.githubusercontent.com/48179091/91383768-e9340f00-e867-11ea-98f1-da095d4b1f2c.gif)

**There is not girl & white robot.**

Below games were solved at v1.10.3-1705
~**[ Real PSP Bleach SoulCarnival 2 ]==> blur processing ON & The HP gage of the upper left goes off, and "NowLoading" is drawn by the lower right.**~
![Bleach_SC2_Menu_Blur_RealPSP](https://user-images.githubusercontent.com/48179091/91385367-ab38ea00-e86b-11ea-888a-14e52f0cf04d.gif)

~**[PPSSPP Bleach SoulCarnival 2 ]==> blur processing OFF(Maybe) & The HP gage of the upper left is expanded while being indicated.**~
![Bleach_SC2_Menu_Blur_PPSSPP](https://user-images.githubusercontent.com/48179091/91385647-5b0e5780-e86c-11ea-8850-7e92bdf9c9df.gif)

**Comment by unknownbrackets** [comment]
Does this work any better at 1x PSP render resolution?  The Bleach example looks like a bug.

-[Unknown]

**Comment by nassau-tk** [comment]
No,Same issue happen on 1x resolurtion.

And,Dunball Senki has a another issue.
I could got the screen shot.
See below screenshot.

This is screen of warning when appear at startup.
![Screenshot_20200827-145629](https://user-images.githubusercontent.com/48179091/91398539-43889c00-e877-11ea-9589-2000895972c3.png)

and....

![Screenshot_20200827-145530](https://user-images.githubusercontent.com/48179091/91398447-0c19ef80-e877-11ea-84d4-ed3e5f16a5fb.png)

When opening the menu screen, I find out that it's drawn by a background in the penetration state.

This problem occurs irregularly.
When occurring, it keeps being indicated until it restarts.
I feel easy to get up at the time of movement of fast forwarding.
Only this warning screen isn't drawn.
The situation to which others completely have no relation is also drawn.
And,This issue will happen at timing of blur processing. (Battle start screen,Talk screen...too)

**Comment by unknownbrackets** [comment]
Danball is probably missing a framebuffer download, although I'm not sure why it'd be Android only.  The blur in this case is probably processed on the CPU and requires block transfer.  The problem is we still miss some block transfers.

The Bleach bug is different because we seemed to do the block transfer incorrectly, at the wrong size.

-[Unknown]

**Comment by nassau-tk** [comment]
[DunballSenki_GEdump.zip](https://github.com/hrydgard/ppsspp/files/5134479/DunballSenki_GEdump.zip)
[BleachSC2_GEdump.zip](https://github.com/hrydgard/ppsspp/files/5134480/BleachSC2_GEdump.zip)

I don't know whether you have come by a record right, but a dump file is attached.

**Comment by nassau-tk** [comment]
[Log : BLEACH SC1 Open the menu.]
![image](https://user-images.githubusercontent.com/48179091/99950311-b09cc680-2dbf-11eb-81b4-a721b9eabddb.png)

**Comment by nassau-tk** [comment]
OK.
This issue was solved one & duplicate #5918 .
So, I close this!
