### ISSUE TITLE
Constant screen tearing in FFIV.

### ISSUE THREAD

**Issue by Khronikos** [hrydgard/ppsspp#13339]
When moving in any direction screen tearing follows. Up down it is horizontal and left right it is vertical tearing.

What should happen is there should be no tearing. Forcing Vsync in various ways does not seem to fix the issue for me. Capping FPS does not fix it either.

1080ti/3770K Win 7 x64 

This could just be Win 7 or Nvidia, or obviously a setting I need to have on, as I don't recall having issues on the standalone. From the settings I do have I cannot configure anything to make it go away, so I thought might as well make an issues post.

**Comment by hrydgard** [comment]
Sounds familiar, try unchecking the "Vertex Cache" option?

**Comment by Khronikos** [comment]
> 
> 
> Sounds familiar, try unchecking the "Vertex Cache" option?

Hello, this sadly did not solve the issue. Thank you for suggestions.

**Comment by Khronikos** [comment]
Could someone tell me if they are too seeing this in the game? I haven't been able to solve it.

**Comment by Khronikos** [comment]
> 
> 
> Sounds familiar, try unchecking the "Vertex Cache" option?

Hello, this issue is currently fixed in the newest build on Retroarch. Thank you very much.

**Comment by Khronikos** [comment]
According to my rig, WIn 7 x64 1080ti and 3770K, and with options available to me in emulator and with Nvidia Control Panel, I no longer have this issue. Thank you for fixing it.
