### ISSUE TITLE
Saves using external memory stick folder fail to read/write

### ISSUE THREAD

**Issue by Masamune3210** [hrydgard/ppsspp#13345]
### What happens?
Trying to move the memstick outside of the normal folder with installed.txt causes saves and loads to the memstick to fail consistantly

I apologize if this is already reported, I didn't see a standing issue for it, and figured I would make one. Can't figure out what I'm doing wrong if it's my fault

### What *should* happen?
Saves should work correctly, being placed wherever the user has dictated in installed.txt

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
CPU: Ryzen 7 3700X
GPU: Radeon 5700XT
PPSSPP: 0.10.3-515=gcb3ed8f4a

**Comment by unknownbrackets** [comment]
Is this on Windows?

I know this works for other people - are you sure the path is a full path and correct?  Are you certain PPSSPP will have access to create files there?

One way to check is using the command prompt.  Open Start -> type "cmd".  You'll see a black box appear.

Inside this black box, type `cd /d "` (that's a double quote mark), and then copy and paste the EXACT CONTENTS of installed.txt.  After that, add another `"` and press enter.  If it works, you'll see the new path, like this:

```
C:\Users\Someone>cd /d "E:\PSP"

E:\PSP>
```

If it says anything, or if it doesn't show you the path, then something is wrong with the path and it won't work.  It should look like `C:\Path\To\Folder\Where\PPSSPP\Will\Put\Stuff`.

If the above did work, your next step is to verify it's actually writable.  Maybe this folder requires UAC, which isn't okay for PPSSPP.  To verify this, try typing: `echo Hello > hat.txt` (that's a greater than sign), and press enter.

If it says "Access is denied.", that means it's not a path PPSSPP will be able to write to.

-[Unknown]

**Comment by Masamune3210** [comment]
Ok, for some reason now it is working fine, even though I changed literally nothing other than recreating the installed.txt
Maybe Windows was just having a bad day that day, who knows
Sorry for the waste of time lol
