### ISSUE TITLE
[Android/Windows] Crash by Inavalid Memory Access [Fantasy Golf Pangya Portable (ULJM05440)ファンタジーゴルフパンヤポータブル]

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#13348]
### What happens?
FantasyGolfPangyaPortable crash at timing of start up. (100%)
Please see attached screenshot of inavalid memory access.

### What *should* happen?
Don't crash!! Please!!

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
PPSSPP Ver. : 1.10.3-515
OS: Android 9.0
DeviceName: SONY SO-02K / Xperia XZ1 Compact (Japan)
CPU: Snapdragon835 (Octa-core)
GPU: Adreno 540
Resolution: 720×1280
RAM: 4GB
ROM:32GB
ExternalStrage: microSDXC 512GB

PPSSPP Ver.：1.10.3-515
OS：Windows10 (64-bit) Japanese
CPU：Ryzen7 3800X（8-core）
GPU：RADEON RADEON RX5700XT
Resolution：2560×1440
RAM：32GB

![FantasyGolfPangya_InvalidMem](https://user-images.githubusercontent.com/48179091/91626575-54f2b500-e9eb-11ea-95e2-211d5aee12f7.png)

**Comment by Panderner** [comment]
@nassau-tk last build worked? it's same happens in bleach soul carnival 1 and 2 (#13346)

**Comment by nassau-tk** [comment]
I'm testing on latest build v1.10.3-515.

Bleach SC&SC2 can start and play.
But,Sometime crash and freeze.
Pangya can't start game.

But, PANYA knew that it can't start from the front fairly. A crash of a bleach started to occur by a recent build.

**Comment by Panderner** [comment]
Pangya Needs to change the I/O timing method to Simulate UMD delays listed in #7647. Maybe duplicate of #4996?

**Comment by nassau-tk** [comment]
@Panderner 
My Pangya issue is solved!!
By Simulate UMD delay.
Thanks!!

I will close this.

**Comment by Sukotto-1999** [comment]
@nassau-tk this game is equipped with a check to make sure it's being run on a UMD drive, if it is being run off memory stick, it hardlocks. The only way around is to Simulate UMD delays if using unmodified game.
