### ISSUE TITLE
[Windows/Android][Save issue]Capcom Classic Collection (ULJM05104) can't find the Suspend(System) Savedata.

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#13365]
### What happens?
This game has autosave system.
But,Everytime appear the warning of creating a new savedata  at timing of autosave.
If you select "Yes"(Create Save data) then appear "over write warning".
Because,The savedata was created allready.
And,You can over write corectly.
But,This issue is not corectly working of emulation.
PPSSPP has many other save issue.
May be,This one too.

And,I want know that the issue happen on "Capcom Classic Collection Reloaded (ULUS10134) " or not?
Because, Theese games are brother-like.

### What *should* happen?
System of save working corectly.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
PPSSPP Ver.：1.10.3-541
OS：Android 9.0
DeviceName：SONY SO-02K / Xperia XZ1 Compact（Japan）
CPU：Snapdragon835（Octa-core）
GPU：Adreno 540
Resolution：720×1280
RAM：4GB
ROM：32GB
ExternalStrage：microSDXC 512GB

PPSSPP Ver.：1.10.3-541
OS：Windows10（64-bit）Japanese
CPU：Ryzen7 3800X（8-core）
GPU：RADEON RADEON RX5700XT
解像度：2560×1440
RAM：32GB

**["In gaeme" autosave point]**
![CapcomClassicCollection_AutoSaveWarning](https://user-images.githubusercontent.com/48179091/91722590-6bf4fb00-ebd5-11ea-93a7-cae6fb813e7c.png)

[My poor translation below.]
There is no suspend savedata.
When you create a suspend savedata then required 192KByte space.
Will you create a suspend savedata?
"The suspend savedata will save automaticaly.You can change autosave ON/OFF in option screen."

**["Return to menu" autosave point]**
![CapcomClassicCollection_ReturnMenuAutoSaveWarning](https://user-images.githubusercontent.com/48179091/91722598-71524580-ebd5-11ea-8bf9-862213f048df.png)

**[OverWrite Warning]**
![CapcomClassicCollection_OverWriteWarning](https://user-images.githubusercontent.com/48179091/91722602-74e5cc80-ebd5-11ea-9e8c-20c3415b6e45.png)

**Comment by nassau-tk** [comment]
@Panderner

Hi,Don't happen on Capcom Classic Collection Reloaded(US)?

**Comment by Panderner** [comment]
> @Panderner
> 
> Hi,Don't happen on Capcom Classic Collection Reloaded(US)?

@nassau-tk yes same happens for English version of Capcom Classics Collection Reloaded due to autosave issue.
![Screenshot_2020-09-22-11-07-39-85_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/93840904-8f86ff00-fcc4-11ea-97eb-20309d3d31d4.png)

**Comment by nassau-tk** [comment]
Thank you for reporting!!

**Comment by nassau-tk** [comment]
@hrydgard 
This save issue can be saving the data, so I think this issue is low priority.
If there are no problems, I propose that "Save issue" tags.
Thank you.

**Comment by unknownbrackets** [comment]
From Reloaded:

> filesystems\directoryfilesystem.cpp:62 DirectoryFileSystem::OpenFile: FAILED, 5 - access = 1
> dialog\savedataparam.cpp:622 Error reading file ms0:/PSP/SAVEDATA/ULUS10134U000/

This might indicate that passing a blank filename has special meaning.

-[Unknown]

**Comment by nassau-tk** [comment]
@unknownbrackets 
Thank you for your checking.
When this clue leads to a solution of other "Saving Issue", I'm happy.
In particular, Assassin's Creed : Bloodlines.  (^o^)/

**Comment by hrydgard** [comment]
Please test again now that shenweip's https://github.com/hrydgard/ppsspp/pull/13507 is merged!

**Comment by nassau-tk** [comment]
Yes!!
A hasty report!
I tested easily.(v1.10.3-833@Android)

Report1: May be this issue is solved!!
Report2: #12761 solved too??? (If it's real then I'm so happy!!)

I will tested more at finished my work.
And I will report it again.

**Comment by hrydgard** [comment]
Ok, I'm closing this one then and leaving #12761 open.
