### ISSUE TITLE
[Windows/Andoroid][Freeze]Capcom Classic Collection (ULJM05104) stuck in return menu [Same #4671]

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#13361]
### What happens?
First Please see #4671.
The issue solved and close.
But,Same issue is happening on  Capcom Classic Collection (ULJM05104) yet.
PPSSPP v1.10.3.-515

Capcom Classic Collection Reloaded (ULUS10134) **for Out of Japan**
and
Capcom Classic Collection (ULJM05104) **for Japan**
I think these are brother-like software.
But,The issue isn't solved on Japan Ver..

### What *should* happen?
I want solve the issue on Capcom Classic Collection (ULJM05104).

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
PPSSPP Ver. : 1.10.3-515
OS: Android 9.0
DeviceName: SONY SO-02K / Xperia XZ1 Compact (Japan)
CPU: Snapdragon835 (Octa-core)
GPU: Adreno 540
Resolution: 720×1280
RAM: 4GB
ROM:32GB
ExternalStrage: microSDXC 512GB

PPSSPP Ver.：1.10.3-515
OS：Windows10 (64-bit) Japanese
CPU：Ryzen7 3800X（8-core）
GPU：RADEON RADEON RX5700XT
Resolution：2560×1440
RAM：32GB

**Comment by shenweip** [comment]
It's odd, the game I have is Japan version too(ULJM05104), but I can't produce that issue anymore. Could you check your CRC32 value of your ISO files? This is mine:`8F83E956`.

**Comment by nassau-tk** [comment]
@shenweip 
@sum2012 

CRC32=8F83E956 (Same it.)
It solved on v1.10.3-526.
Windows10(64-bit) & Android both.
Thank you!!

I will close this.
