### ISSUE TITLE
PPSSPP Crashes when trying to load Digimon Adventure PSP NPJH-50686 Cutscene videos

### ISSUE THREAD

**Issue by LPatamon** [hrydgard/ppsspp#13371]
### What happens?
When I go to the video library on the game and try to watch any of the cut scene videos, the emulator crashes, this also happens when advancing on the game and a get to a moment in which a cutscene video should appear. Here is a video of the issue.

https://www.youtube.com/watch?v=SPBRZcMMj-I

### What *should* happen?
The videos should play correctly as they used to do so on previous versions of PPSSPP

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

3Ghz Core i5-3330 (Quad Core), 4GB Ram and 2GB GDDR5 Gigabyte Nvidia GT1030  on Windows 7 Ultimate 32 bits Desktop PC.

PPSSPP Version: v1.10.3-547-gd8a5c710f

Notes.

This crashing started on the builds after v1.10.3-515-gcb3ed8f4a build, since v1.10.3-515-gcb3ed8f4a was the last one where the videos worked, since the next build was v1.10.3-518-g81159770d (but only for Android and Windows 64 bits, while the next build for Windows 32bits was v1.10.3-520-g594564298, the issue making the emulator to crash when trying to play the videos, has to be either on the 3 builds that had no download link or starting on build v1.10.3-518-g81159770d. 

This issue just made the game impossible to progress since the crash happens even when you're advancing through the story. I tested it starting a new game and when a cutscene video was to play, the emulator crashed, so no way to advance in the game unless you use a build where the videos work. 

Even so, on recent builds where the videos play correctly, the emulator still crashed randomly if you stopped the emulation while the video was playing, thing that didn't happened before. I'm still trying to pinpoint on which build the random crash started since from build v1.10.3-387-g6ca01d588 (which was the one I had before I updated to  build v1.10.3-515-gcb3ed8f4a which was the one where I noticed the random crash if I closed the emulation while the video was playing) to build v1.10.3-426-g3c8ca6ad8 the videos worked without any issue, I could stop the emulation with the video playing and no crash at all.

I'll keep searching where the random crash when stopping the emulation while a cutscene video is playing started, I'll update this thread as soon I get some information.

**Comment by hrydgard** [comment]
Thanks for reporting. We've made some rather drastic changes to framebuffer management lately so some fallout is to be expected and reporting is how it gets fixed :)

Will investigate.

**Comment by LPatamon** [comment]
> 
> 
> Thanks for reporting. We've made some rather drastic changes to framebuffer management lately so some fallout is to be expected and reporting is how it gets fixed :)
> 
> Will investigate.

No problem. Guess those changes to framebuffer management didn't get along with a few games like in this case with Digimon Adventure PSP.  

Ah well. Thanks for the reply :)

**Comment by LPatamon** [comment]
Okay. I managed to pinpoint the last build that had no crashes on Digimon Adventure PSP cutscene videos when stopping the emulation while the video was playing. 

The last good build in which there was no issues with the cutscene videos was v1.10.3-470-ge8779fdc8. After that there are two versions that had no build to download on the buildbot which are v1.10.3-471-g506a86300 and v1.10.3-472-g26ba65f38, after that the next build that has download links is v1.10.3-473-gbf18817fe and is on this build where the crashes when stopping the emulation while a cutscene video is played started. 

v1.10.3-473-gbf18817fe has the following comment on the buildbot: Merge: e8779fdc8 26ba65f38 Merge pull request #13319 from hrydgard/state-cleanup-cleanup State cleanup cleanup

Hope it helps.

**Comment by LPatamon** [comment]
Here is a video of the crash when you stop the emulation while a cutscene video of Digimon Adventure PSP is playing:

https://www.youtube.com/watch?v=jhkbYAytpXY&feature=youtu.be

I added the normal behavior the emulator should have by using a version where there was no crashes at all.

**Comment by hrydgard** [comment]
Fixed now, thanks for reporting!

**Comment by LPatamon** [comment]
Videos work now thanks! 

But there was a tiny side effect:

![image](https://user-images.githubusercontent.com/6118529/92223665-682bd780-ee66-11ea-9969-8ecd7c1ab3f0.png)

The line on the videos is back, but this time is kinda curious since it only happens when you play a video after loading your progress, but after that if you play that video or any other you had unlocked, the line doesn't appears o.o

This didn't happened before, before was the line present all time till it got fixed on issue #12186 that I reported as well. It was fixed for v1.8.0-623-gc7798715a (no download links, they appeared on the next build the same date) with the comment **"Fix issue preventing video to work correctly in Digimon. Fixes #12186 (due to BlockTransferAllowCreateFB not updating the framebuffer range speedhack)."**

And yes. it has to do with the framebuffer.

Other than that all is fine, crashes got fixed :)

**Comment by LPatamon** [comment]
Opened a new issue. There was a side effect on the fix. it partially undid another fix you did for this same game.

**Comment by hrydgard** [comment]
I think it was the change that started crashing that broken it, rather than the fix.

**Comment by LPatamon** [comment]
> 
> 
> I think it was the change that started crashing that broke it, rather than the fix.

Mmmh... yeah that's possible indeed. Framebuffer no doubt is such a very delicate thing to work with. any modification can lead to errors with some games, since it is impossible to know what will affect and what not.
