### ISSUE TITLE
[Windows] Crashed when closing down (clicking [x] button) PPSSPP Debug Build with D3D11

### ISSUE THREAD

**Issue by ANR2ME** [hrydgard/ppsspp#13389]
![image](https://user-images.githubusercontent.com/7974720/92315458-18890f80-f010-11ea-9d06-83ce406f3987.png)

### What happens?
1). Launch Valhalla Knights 2 using Debug Build x64 with D3D11
2). Press Start button twice to go to Start/Main Menu
3). Click [x] button to close down PPSSPP window, and bam! crashed.
When crashed, recent game history didn't get saved

### What *should* happen?
Properly terminate PPSSPP

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Laptop with Windows 10 Pro 64bit v2004 (fully updated) + Geforce MX150 (driver v452.06 whql)

**Comment by hrydgard** [comment]
Thanks, I'll look into this soon.

**Comment by ANR2ME** [comment]
This issue seems to be fixed with the latest commits, so i'll close this.
