### ISSUE TITLE
After update phantasy star portable 2 often crash in network play

### ISSUE THREAD

**Issue by Lemoncak3** [hrydgard/ppsspp#13381]
I download the latest build today and when i play together with my friend, the party will be disbanded on it's own or my game suddenly stuck at joining party. It doesn't happen before. Does something change?
I am using this version v1.10.3-573-gd6399b603 
now i am returning to this version v1.10.3-520-g594564298 and the network running again with no problem. Please check it since i don't want the network to become troubled in the future update.

**Comment by adenovan** [comment]
@ANR2ME is there something changed on local loopback address ? 

this game is very sensitive in first call of tcp connection to the host at loopback address  , blocking implementation sure handle this nicely , too many returning error on tcp connect in this game either from peer or host will forcefully disconnect the peer and must restart the whole matchmaking task which quite tiresome.

**Comment by ANR2ME** [comment]
There was a bug with adhocctlCreate (which is used to Create/Join a group) where a socket error with EAGAIN/EWOULDBLOCK supposed to be retried on the blocking simulation but didn't get retried (because i forgot to check the error code) and ended fallback to faked success, it could be the issue and should be fixed with this PR https://github.com/hrydgard/ppsspp/pull/13383

**Comment by adenovan** [comment]
make sure to recheck this socket error EAGAIN/EWOULDBLOCK on tcp connect and pdp send also , mh games depends alot on it especially when in 4 player mode at departing quest this game is similiar , im not in front of my workdesk yet its hard to see all the code on mobile. 

the error code its spam is error_netadhocwouldblock

**Comment by ANR2ME** [comment]
> 
> 
> make sure to recheck this socket error EAGAIN/EWOULDBLOCK on tcp connect and pdp send also , mh games depends alot on it especially when in 4 player mode at departing quest this game is similiar , im not in front of my workdesk yet its hard to see all the code on mobile.
> 
> the error code its spam is error_netadhocwouldblock

WOULDBLOCK error code shouldn't be shown anymore as error in the logs, because it's an expected error to occurred (pretty often) when using non-blocking socket, which mean need to retry again later.

Are you sure this error still spamming the Log with the latest changes?

**Comment by Lemoncak3** [comment]
So is it already fixed? which version should i download so later i can check it again?

**Comment by ANR2ME** [comment]
> 
> 
> So is it already fixed? which version should i download so later i can check it again?

The PR is not merged yet, this issue will be closed later after the fix is merged later.

**Comment by adenovan** [comment]
> WOULDBLOCK error code shouldn't be shown anymore as error in the logs, because it's an expected error to occurred (pretty often) when using non-blocking socket, which mean need to retry again later.
> 
> Are you sure this error still spamming the Log with the latest changes?

@ANR2ME thats i try to make sure the error code is still there and precisely back to the caller when timeout or socket error happen in new non block implementation. im not pull the latest master yet thats why i ask here im something changed.

i mean on old blocking implementation that return code is so sensitive in breaking the synchronization of player in this game and mh 4 player play so its should precisely simulated and returned on new implementation. 

psp often desync cross playing when we send the packet too fast to aemu also , something on packet timestamp but im not looking into that deeply yet.
