### ISSUE TITLE
Error message after saving and after loading states in Valkyria Chronicles II (ULUS10515_1.00)

### ISSUE THREAD

**Issue by justafella** [hrydgard/ppsspp#13382]
### What happens?
An error message (attached) pops up 3x when saving and 2x when loading a state.

### What *should* happen?
No error messages.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

- Windows 10 64 bit;
- Acer Aspire ES15;
- Intel Celeron QuadCore N3450;
- Intel HD Graphics 500 (driver ver. 27.20.100.8476);
- ppsspp-v1.10.3-573-gd6399b603-windows-amd64

### Additional info:
- All the 5 messages are the same;
- If I keep clicking "Sim" (Yes) it saves and loads.

![Anotação 2020-09-04 125051](https://user-images.githubusercontent.com/65559598/92267547-d1373d80-eeae-11ea-8958-1ab58c9e2ff2.png)

**Comment by justafella** [comment]
Never mind. Deleting PPSSPP settings brought things back to normal. Probably a case of incompatible/corrupted save states between versions v1.10.3-550-g0dcaeb784 and v1.10.3-573-gd6399b603.

**Comment by unknownbrackets** [comment]
This was fixed in a recent git build - see #13395.

-[Unknown]
