### ISSUE TITLE
Network multi instance broken under linux

### ISSUE THREAD

**Issue by iota97** [hrydgard/ppsspp#13390]
### What happens?
Using localhost for multiple instance result in socket error 32 (broken pipe) when 2nd instance try to connect, SIGPIPE get send to PPSSPP that terminate returning 141 (Linux broken pipe error code). 1st instance keep working fine.

Step I have done:

- Enabled build-in adhoc and set server address to localhost
- Starting Wipeout Pure (EU version) on 1st instance and host an adhoc game.
- Starting a 2nd instance (at start it prompt that buildin adhoc failed to bind the port, as it's already running on the other, don't think it have any relevance).
- Try to join and 2nd instance crash returning 141 (note that at least on my machine nothing is printed about what caused the crash, like segfault core dumped or so on with this error, it just die).

I couldn't get a nice log with it crashing so I reused the exception handling code to survive the SIGPIPE doing nothing and here the log (like this it just loop "overlay text" about network failing and retrying when I try to join), but at least it survive:

```
48:07:546 Main thread  W[SCENET]: HLE/sceNet.cpp:581 sceNetInit(poolsize=131072, calloutpri=42, calloutstack=0, netintrpri=42, netintrstack=0) at 08a23ea4
48:07:546 Main thread  I[SCENET]: HLE/sceNetAdhoc.cpp:760 0=sceNetAdhocInit(): at 08a23f5c
48:07:546 Main thread  I[SCENET]: HLE/sceNetAdhoc.cpp:767 sceNetAdhocctlInit(8192, 48, 090e73d4) at 08a23f7c
48:07:546 Main thread  I[SCEKERNEL]: HLE/sceKernelThread.cpp:2008 589=sceNetAdhocctlInit(8192, 48, 090e73d4)
48:07:546 readThread   I[SCENET]: HLE/proAdhoc.cpp:1253 FriendFinder: Begin of Friend Finder Thread
48:07:546 Atrac3 Play  I[SCENET]: HLE/proAdhoc.cpp:1265 FriendFinder: Network [RE]Initialized
48:07:547 Main thread  W[SCENET]: HLE/sceNetAdhoc.cpp:1789 UNTESTED sceNetAdhocctlAddHandler(8a24668, 0): added handler 0
48:07:547 Main thread  I[SCEIO]: HLE/sceIo.cpp:1142 stdout: NetInit :: FINISH -- FreeMem: 278272:272640
48:07:547 Main thread  I[SCEUTIL]: HLE/sceUtility.cpp:484 0=sceUtilityNetconfInitStart(090e72c8)
48:07:713 Main thread  I[SCENET]: HLE/sceNetAdhoc.cpp:2167 sceNetAdhocctlConnect() at 08a23948
48:07:713 Main thread  E[SCENET]: HLE/sceNetAdhoc.cpp:2107 Socket error (32) when sending
48:08:465 Main thread  I[SCEKERNEL]: HLE/sceKernelThread.cpp:2008 591=sceKernelCreateThread(rtPspnetUpdateThread, 08a669e0, 00000028, 8192, 00000000, 00000000)
48:08:465 Main thread  I[SCEKERNEL]: HLE/sceKernelThread.cpp:2103 0=sceKernelStartThread(591, 0, 00000000)
48:08:526 Main thread  I[SCENET]: HLE/sceNetAdhoc.cpp:836 sceNetAdhocPdpCreate(0c:93:2c:b1:69:f3, 3659, 65523, 0) at 08a6702c
48:08:527 Main thread  I[SCENET]: Util/PortManager.cpp:197 PortManager::Add(UDP, 3659, 3659)
48:09:547 idle0        E[SCENET]: HLE/proAdhoc.cpp:1290 FriendFinder: Socket Error (32) when sending OPCODE_PING
48:09:548 idle0        I[SCENET]: HLE/proAdhoc.cpp:1265 FriendFinder: Network [RE]Initialized
48:11:549 idle0        E[SCENET]: HLE/proAdhoc.cpp:1290 FriendFinder: Socket Error (32) when sending OPCODE_PING
48:11:550 idle0        I[SCENET]: HLE/proAdhoc.cpp:1265 FriendFinder: Network [RE]Initialized
48:12:775 Main thread  I[ME]: HW/MediaEngine.cpp:87 FF: error while decoding MB 15 10, bytestream -9
48:12:810 idle0        I[ME]: HW/MediaEngine.cpp:87 FF: left block unavailable for requested intra mode at 0 13
48:12:810 idle0        I[ME]: HW/MediaEngine.cpp:87 FF: error while decoding MB 0 13, bytestream 59
48:13:551 idle0        E[SCENET]: HLE/proAdhoc.cpp:1290 FriendFinder: Socket Error (32) when sending OPCODE_PING
48:13:552 idle0        I[SCENET]: HLE/proAdhoc.cpp:1265 FriendFinder: Network [RE]Initialized
```

### What *should* happen?
Would be nice to have it working on Linux as well, if it would require to much work for now might be worth to use the exception handling path to have a less fatal error?

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Using latest master (5f1e3b295039ce60872c4d44e420f777c23621a1), on Manjaro Linux  x86_64 (Arch based distro).

**Comment by unknownbrackets** [comment]
@ANR2ME we should probably use MSG_NOSIGNAL to avoid SIGPIPE.  See #11475.

-[Unknown]
