### ISSUE TITLE
Soulcalibur: Broken Destiny Character portrait rendering issue (ULUS10457)

### ISSUE THREAD

**Issue by tornadus** [hrydgard/ppsspp#13400]
### What happens?
In The Gauntlet (story mode), the first character portrait of every story sequence loads fine, however all subsequent ones do not appear. I have included 2 separate graphics dumps and a screenshot that show the bug.
![](https://cdn.discordapp.com/attachments/480103153803460614/752635331182067722/unknown.png)

### What *should* happen?
This exact same scene appears like this on real PSP hardware.
![](https://media.discordapp.net/attachments/480103153803460614/752651097763741706/unknown.png)

### Hardware and software info
Windows 10 (2004)
Ryzen 3600
GTX 1060 6GB (driver 452.06)
32GB of RAM
PPSSPP v1.10.3

[Graphics dump that shows the first portrait working as expected](https://cdn.discordapp.com/attachments/260582280324579339/752659563076911154/ULUS10457_FirstWorkingPortrait.ppdmp)
[Graphics dump of the included screenshot showing the issue](https://cdn.discordapp.com/attachments/260582280324579339/752659576939085904/ULUS10457_NoWorkingPortraits.ppdmp)

**Comment by unknownbrackets** [comment]
@hrydgard this is using a triangle strip with culling enabled.  It draws the wrong thing on top, but counter clockwise, so it should get culled... but doesn't.  Could this be an index generator problem?  It works fine in softgpu.

-[Unknown]

**Comment by hrydgard** [comment]
Huh, bizarre! This needs a closer look.

**Comment by unknownbrackets** [comment]
It's drawn in through mode - now very obvious that should do culling, I think.  Have a fix, just want to test clearmode too.

-[Unknown]

**Comment by tornadus** [comment]
I can confirm that the new build has fixed the issue!
