### ISSUE TITLE
Libretro context confusion bug

### ISSUE THREAD

**Issue by i30817** [hrydgard/ppsspp#13424]
### What happens?
Self built ppsspp core is very very confused about the context it creates. There are two ways i've been able to run ppsspp like this, one annoying and that requires a extra compile of retroarch, the other with code modification and that i'm pretty sure is a symptom of a bug.

1. Build retroarch with either the gl(opengl 3+ and gles 2+) or glcore (opengl3.3+ and gles 3+) drivers configured to use gles (it's either opengl or gles and you can't have one driver with one and another with the other). Then build ppsspp, and it appears to fall into a context that 'runs' on either. I'm not quite sure what context it falls on (i think it might be gles).

2. built retroarch with the gl and glcore drivers using opengl. Then build ppsspp with the define on `libretro/LibretroGLContext.h` :

```
#ifdef USING_GLES2
		: LibretroHWRenderContext(RETRO_HW_CONTEXT_OPENGLES2)
#elif defined(HAVE_OPENGL_CORE)
		: LibretroHWRenderContext(RETRO_HW_CONTEXT_OPENGL_CORE, 3, 1)
#else
		: LibretroHWRenderContext(RETRO_HW_CONTEXT_OPENGL)
#endif
```
using the second (with glcore driver) or the third (with gl driver). I commented out those that i didn't want, and the core started in RA.

So i though 'easy then, just add `CMAKE_ARGS="-DHAVE_OPENGL_CORE=OFF(or ON) -DUSING_GLES2=OFF" ./b.sh --libretro --release --no-package` to the build and you're done'. 

This results in this error on a libretro build:
```
[INFO] [Video]: Found display server: null
[libretro INFO] [G3D] Context reset
[libretro ERROR] [G3D] glewInit() failed.

Segmentation fault (core dumped)
```
So it seems 'commenting the superclasses i don't want' works because glewInit is not called in `libretro/LibretroGLContext.cpp:LibretroGLContext::CreateDrawContext()` in that case (i assume because `USING_GLES2` is **actually turned ON** - since HAVE_OPENGL_CORE is not used anywhere but in this file (once) and is not defined anywhere and that glewInit section is guarded by `if !defined(IOS) && !defined(USING_GLES2)`.

To recap: 
`USING_GLES2=ON` and forced `LibretroHWRenderContext(RETRO_HW_CONTEXT_OPENGL_CORE, 3, 1)` (or the third fallback) works, and `USING_GLES2=OFF` fails with the glewInit error always and if you comment the part with the glewInit (that was guarded by that env variable being off to run) you still crash.

### What *should* happen?

I just want to build a working core that works with one of the opengl configurations of the retroarch drivers, to not have to have a extra gles retroarch compile, and be able to use the core in both wayland and KMS.

Commenting the glewInit() section in `libretro/LibretroGLContext.cpp:LibretroGLContext::CreateDrawContext()` and building with those cmake args still crashes, so it's not that... or just that.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

cpu: Intel® Core™2 Duo CPU T6600 @ 2.20GHz × 2 
gpu: AMD® Rv710
os: Linux AIVAS 5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
ppsspp: 9753e317f367df82f65da07245851745ffbb5502 (master)

**Comment by unknownbrackets** [comment]
Probably this is because it's not telling PPSSPP to use the GL context as a core context at the appropriate times.  `SetGLCoreContext(true);` must be called if a core context is in use.  Note that standalone PPSSPP uses a core context, if possible, already on most platforms.  I don't think the libretro code does this, though.

PPSSPP will definitely crash if `glewInit()` is not called.  That's what loads the GL functions we call - if it's skipped or fails, we can't use OpenGL functions at all.

-[Unknown]

**Comment by i30817** [comment]
Adding a SetGLCoreContext(true) call in the function creating the draw context doesn't work to prevent the glewInit error:

`export CORE="$HOME/.config/retroarch/cores/ppsspp_libretro.so"; CMAKE_ARGS="-DHAVE_OPENGL_CORE=ON -DUSING_GLES2=OFF" ./b.sh --libretro --release --no-package && gio trash -f "$CORE" && mv -fT ./build/lib/ppsspp_libretro.so "$CORE" && chmod -x "$CORE";`
```
void LibretroGLContext::CreateDrawContext() {
	if (!glewInitDone) {
#if !defined(IOS) && !defined(USING_GLES2)
		SetGLCoreContext(true); //added for opengl

		if (glewInit() != GLEW_OK) {
			ERROR_LOG(G3D, "glewInit() failed.\n");
			return;
		}
#endif
		glewInitDone = true;
		CheckGLExtensions();
	}
	draw_ = Draw::T3DCreateGLContext();
	renderManager_ = (GLRenderManager *)draw_->GetNativeObject(Draw::NativeObject::RENDER_MANAGER);
}
```
```
$ retroarch 
[INFO] RetroArch 1.9.0 (Git ba9ad1057f)
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM)2 Duo CPU     T6600  @ 2.20GHz
[INFO] Capabilities:  MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4
[INFO] Built: Sep 12 2020
[INFO] Version: 1.9.0
[INFO] Git: ba9ad1057f
[INFO] =================================================
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] [Overrides]: Redirecting save file to "/home/i30817/.config/retroarch/saves/.srm".
[INFO] [Overrides]: Redirecting save state to "/home/i30817/.config/retroarch/states/.state".
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 48000.00 Hz.
[INFO] [Video]: Video @ fullscreen
[INFO] [Video]: Starting threaded video driver ...
[INFO] [Wayland]: Physical width: 340 mm x 190 mm.
[INFO] [Wayland]: Video mode: 1366 x 768 @ 59.9980 Hz.
[INFO] [Wayland]: Display scale factor 1.
[INFO] [Wayland]: Seat name: seat0.
[WARN] [Wayland]: Compositor doesn't support zwp_idle_inhibit_manager_v1 protocol!
[WARN] [Wayland]: Compositor doesn't support zxdg_decoration_manager_v1 protocol!
[INFO] [EGL] Found EGL client version >= 1.5, trying eglGetPlatformDisplay
[INFO] [EGL]: EGL version: 1.5
[INFO] [GLCore]: Found GL context: wayland
[INFO] [GLCore]: Detecting screen resolution 0x0.
[INFO] [EGL]: Current context: 0x7f54900a3d60.
[INFO] [EGL]: eglSwapInterval(1)
[INFO] [GLCore]: Vendor: X.Org, Renderer: AMD RV710 (DRM 2.50.0 / 5.4.0-47-generic, LLVM 10.0.0).
[INFO] [GLCore]: Version: 3.3 (Core Profile) Mesa 20.0.8.
[INFO] [GLCore]: Using resolution 640x480
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] [GLCore]: Loading stock shader.
[INFO] [slang]: Building pass #0 (N/A)
[INFO] [GLCore]: Not using frame history.
[INFO] [GLCore]: Not using framebuffer feedback.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Video]: Found display server: null
[INFO] [PulseAudio]: Requested 24576 bytes buffer, got 18432.
[INFO] [Display]: Found display driver: "glcore".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Display]: Found display driver: "glcore".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[WARN] [XMB] Asset missing: /home/i30817/.config/retroarch/assets/xmb/monochrome/png/bluetooth.png
[INFO] [MIDI]: Input disabled.
[INFO] [MIDI]: Output disabled.
[INFO] [MIDI]: Initialized "null" driver.
[WARN] Input device ID 517 is unknown to this libretro implementation. Using RETRO_DEVICE_JOYPAD.
[WARN] Input device ID 258 is unknown to this libretro implementation. Using RETRO_DEVICE_JOYPAD.
[INFO] Disconnecting device from port 3.
[INFO] Disconnecting device from port 4.
[INFO] Disconnecting device from port 5.
[INFO] Disconnecting device from port 6.
[INFO] Disconnecting device from port 7.
[INFO] Disconnecting device from port 8.
[INFO] Disconnecting device from port 9.
[INFO] Disconnecting device from port 10.
[INFO] Disconnecting device from port 11.
[INFO] Disconnecting device from port 12.
[INFO] Disconnecting device from port 13.
[INFO] Disconnecting device from port 14.
[INFO] Disconnecting device from port 15.
[INFO] Disconnecting device from port 16.
[INFO] [SRAM]: SRAM will not be saved.
[INFO] [Playlist]: Loading history file: [/home/i30817/.config/retroarch/content_history.lpl].
[INFO] [Playlist]: Loading history file: [/home/i30817/.config/retroarch/content_music_history.lpl].
[INFO] [Playlist]: Loading history file: [/home/i30817/.config/retroarch/content_video_history.lpl].
[INFO] [Playlist]: Loading history file: [/home/i30817/.config/retroarch/content_image_history.lpl].
[INFO] [Playlist]: Loading favorites file: [/home/i30817/.config/retroarch/content_favorites.lpl].
[INFO] [PulseAudio]: Pausing.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Wayland]: Entering output #4, scale 1
[INFO] [CORE]: Using content: /media/i30817/Games/Sony PSP/3rd Birthday, The (USA)/3rd Birthday, The (USA).iso.
[INFO] Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] [CORE]: Unloading core..
[INFO] [CORE]: Unloading core symbols..
[INFO] Threaded video stats: Frames pushed: 103, Frames dropped: 0.
[INFO] RetroArch 1.9.0 (Git ba9ad1057f)
[INFO] [Overrides]: Redirecting save file to "/home/i30817/.config/retroarch/saves/3rd Birthday, The (USA).srm".
[INFO] [Overrides]: Redirecting save state to "/home/i30817/.config/retroarch/states/3rd Birthday, The (USA).state".
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM)2 Duo CPU     T6600  @ 2.20GHz
[INFO] Capabilities:  MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4
[INFO] Built: Sep 12 2020
[INFO] Version: 1.9.0
[INFO] Git: ba9ad1057f
[INFO] =================================================
[INFO] [CORE]: Loading dynamic libretro core from: "/home/i30817/.config/retroarch/cores/ppsspp_libretro.so"
[INFO] [Overrides]: No core-specific overrides found at /home/i30817/.config/retroarch/config/PPSSPP/PPSSPP.cfg.
[INFO] [Overrides]: No content-dir-specific overrides found at /home/i30817/.config/retroarch/config/PPSSPP/3rd Birthday, The (USA).cfg.
[INFO] [Overrides]: No game-specific overrides found at /home/i30817/.config/retroarch/config/PPSSPP/3rd Birthday, The (USA).cfg.
[INFO] [Environ]: SET_VARIABLES.
[INFO] [Remaps]: remap directory: /home/i30817/.config/retroarch/config/remaps
[INFO] [Overrides]: Redirecting save file to "/home/i30817/.config/retroarch/saves/3rd Birthday, The (USA).srm".
[INFO] [Overrides]: Redirecting save state to "/home/i30817/.config/retroarch/states/3rd Birthday, The (USA).state".
[INFO] [Environ]: GET_LOG_INTERFACE.
[INFO] [CONTENT LOAD]: Content loading skipped. Implementation will load it on its own.
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] 	RetroPad, Port 1, Button "B (bottom)" => "Cross"
[INFO] 	RetroPad, Port 1, Button "Y (left)" => "Square"
[INFO] 	RetroPad, Port 1, Button "Select" => "Select"
[INFO] 	RetroPad, Port 1, Button "Start" => "Start"
[INFO] 	RetroPad, Port 1, Button "D-Pad Up" => "D-Pad Up"
[INFO] 	RetroPad, Port 1, Button "D-Pad Down" => "D-Pad Down"
[INFO] 	RetroPad, Port 1, Button "D-Pad Left" => "D-Pad Left"
[INFO] 	RetroPad, Port 1, Button "D-Pad Right" => "D-Pad Right"
[INFO] 	RetroPad, Port 1, Button "A (right)" => "Circle"
[INFO] 	RetroPad, Port 1, Button "X (up)" => "Triangle"
[INFO] 	RetroPad, Port 1, Button "L" => "L"
[INFO] 	RetroPad, Port 1, Button "R" => "R"
[INFO] [Environ]: SET_PIXEL_FORMAT: XRGB8888.
[INFO] [Environ]: GET_USERNAME: "".
[INFO] [Environ]: SYSTEM_DIRECTORY: "/home/i30817/.config/retroarch/system".
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[INFO] [Environ]: SET_HW_RENDER.
[INFO] Requesting OpenGL context.
[libretro INFO] [SYSTEM] Using OpenGL backend
[INFO] [Environ]: GET_VARIABLE ppsspp_button_preference:
	cross
[INFO] [Environ]: GET_VARIABLE ppsspp_fast_memory:
	enabled
[INFO] [Environ]: GET_VARIABLE ppsspp_vertex_cache:
	enabled
[INFO] [Environ]: GET_VARIABLE ppsspp_gpu_hardware_transform:
	enabled
[INFO] [Environ]: GET_VARIABLE ppsspp_frameskip:
	0
[INFO] [Environ]: GET_VARIABLE ppsspp_frameskiptype:
	0
[INFO] [Environ]: GET_VARIABLE ppsspp_auto_frameskip:
	disabled
[INFO] [Environ]: GET_VARIABLE ppsspp_block_transfer_gpu:
	enabled
[INFO] [Environ]: GET_VARIABLE ppsspp_texture_filtering:
	auto
[INFO] [Environ]: GET_VARIABLE ppsspp_texture_anisotropic_filtering:
	off
[INFO] [Environ]: GET_VARIABLE ppsspp_texture_deposterize:
	disabled
[INFO] [Environ]: GET_VARIABLE ppsspp_texture_replacement:
	disabled
[INFO] [Environ]: GET_VARIABLE ppsspp_unsafe_func_replacements:
	enabled
[INFO] [Environ]: GET_VARIABLE ppsspp_cheats:
	disabled
[INFO] [Environ]: GET_VARIABLE ppsspp_locked_cpu_speed:
	266MHz
[INFO] [Environ]: GET_VARIABLE ppsspp_rendering_mode:
	buffered
[INFO] [Environ]: GET_VARIABLE ppsspp_cpu_core:
	jit
[INFO] [Environ]: GET_VARIABLE ppsspp_io_timing_method:
	Fast
[INFO] [Environ]: GET_VARIABLE ppsspp_language:
	automatic
[INFO] [Environ]: GET_LANGUAGE: "0".
[INFO] [Environ]: GET_VARIABLE ppsspp_internal_resolution:
	480x272
[INFO] [Environ]: GET_VARIABLE ppsspp_texture_scaling_type:
	bicubic
[INFO] [Environ]: GET_VARIABLE ppsspp_texture_scaling_level:
	0
[libretro INFO] [BOOT] PPSSPP v1.10.3-642-g9753e317f
[libretro INFO] [MEMMAP] base: 0xffffffffffffffff
[libretro INFO] [MEMMAP] aligned_base: (nil)
[libretro INFO] [MEMMAP] Memory system initialized. Base at (nil) (RAM at @ 0x8000000, uncached @ 0x48000000)
[libretro INFO] [LOADER] ULUS10567 : The 3rd Birthday
[libretro INFO] [LOADER] Failed to read ULUS10567_ppsspp.ini. No game-specific settings found, using global defaults.
[libretro INFO] [LOADER] Loading disc0:/PSP_GAME/SYSDIR/EBOOT.BIN...
[libretro INFO] [SYSTEM] Installed exception handler
[INFO] found_last_state_slot: #0
[INFO] [SRAM]: Skipping SRAM load..
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Cheats]: Load game-specific cheatfile: /home/i30817/.config/retroarch/cheats/PPSSPP/3rd Birthday, The (USA).cht
[INFO] [Audio]: Set audio input rate to: 44144.10 Hz.
[INFO] [Video]: Video @ fullscreen
[INFO] [Video]: Using HW render, OpenGL driver forced.
[INFO] [Video]: Using configured "glcore" driver for GL HW render.
[libretro INFO] [SCEKERNEL] Initializing kernel...
[INFO] [Wayland]: Physical width: 340 mm x 190 mm.
[INFO] [Wayland]: Video mode: 1366 x 768 @ 59.9980 Hz.
[INFO] [Wayland]: Display scale factor 1.
[INFO] [Wayland]: Seat name: seat0.
[WARN] [Wayland]: Compositor doesn't support zwp_idle_inhibit_manager_v1 protocol!
[WARN] [Wayland]: Compositor doesn't support zxdg_decoration_manager_v1 protocol!
[INFO] [EGL] Found EGL client version >= 1.5, trying eglGetPlatformDisplay
[libretro INFO] [SCEKERNEL] Kernel and user memory pools initialized
[libretro ERROR] [SCENET] Error parsing mac address 
[libretro WARN] [SCENET] LocalHost IP will be 127.0.0.0 [00:00:00:00:00:00]
[libretro INFO] [SCENET] UPnPService: Begin of UPnPService Thread
[INFO] [EGL]: EGL version: 1.5
[libretro INFO] [SCEGE] PPGe drawing library initialized. DL: 08000400 Data: 08010400 Atlas: 08020d00 (2097152) Args: 08020400
[libretro INFO] [SCEKERNEL] Kernel initialized.
[libretro INFO] [LOADER] Decrypting tag D91613F0
[libretro INFO] [LOADER] Decrypting tag D91613F0
[libretro INFO] [LOADER] Decrypting tag D91613F0
[INFO] [GLCore]: Found GL context: wayland
[INFO] [GLCore]: Detecting screen resolution 0x0.
[INFO] [EGL]: Created shared context: 0x564a0f1b0010.
[INFO] [EGL]: Current context: 0x564a0f4351a0.
[INFO] [EGL]: eglSwapInterval(1)
[INFO] [GLCore]: Initializing HW render (512 x 512).
[INFO] [GLCore]: Max texture size: 8192 px, renderbuffer size: 8192 px.
[INFO] [GLCore]: Vendor: X.Org, Renderer: AMD RV710 (DRM 2.50.0 / 5.4.0-47-generic, LLVM 10.0.0).
[INFO] [GLCore]: Version: 3.0 Mesa 20.0.8.
[libretro INFO] [SCEKERNEL] -----------
[libretro INFO] [SCEKERNEL] Block: 08800000 - 08804000 size 00004000 taken=1 tag=usersystemlib
[libretro INFO] [SCEKERNEL] Block: 08804000 - 08cb3a00 size 004afa00 taken=1 tag=ELF/pe
[libretro INFO] [SCEKERNEL] Block: 08cb3a00 - 0a000000 size 0134c600 taken=0 tag=(untitled)
[libretro INFO] [SCEKERNEL] -----------
[libretro INFO] [LOADER] Module pe: 00000000 08c19d20 08c19d38
[INFO] [GLCore]: Using resolution 640x480
[libretro INFO] [HLE] Replaced memcpy_jak at 08afca40 with hash 0ffa5db8396d4274
[libretro INFO] [HLE] Replaced memmove at 08afca80 with hash 3c421a9265f37ebc
[libretro INFO] [HLE] Replaced memset_jak at 08afcd44 with hash eabb9c1b4f83d2b4
[libretro INFO] [LOADER] Exporting ent 0 named pe, 2 funcs, 4 vars, resident 08c1a228
[libretro INFO] [LOADER] Module entry: 08af9774
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] [GLCore]: Loading stock shader.
[INFO] [slang]: Building pass #0 (N/A)
[INFO] [GLCore]: Not using frame history.
[INFO] [GLCore]: Not using framebuffer feedback.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Video]: Found display server: null
[libretro INFO] [G3D] Context reset
[libretro ERROR] [G3D] glewInit() failed.

Segmentation fault (core dumped)
```
I don't understand this sequence too well, but from my intuition is 'RA starts menu in glcore with a wayland context, then starts game and game requests one of the opengl implementation superclasses, then EGL butts in (to translate between contexts?) and finds the wayland context; then everything goes wrong when `[INFO] [Video]: Found display server: null` (maybe) and libretro does a *context reset* that as part of it fails the glewInit(). Is it possible `LibretroGLContext::CreateDrawContext()` being called twice and fails the second time?

To verify a added a log and recompiled and the answer is 'No,'.

**Comment by i30817** [comment]
I also now tried a different modification earlier for the call in the function that inits in that `libretro/LibretroGLContext.cpp` and it still fails in the glewInit

```
bool LibretroGLContext::Init() {
#if !defined(USING_GLES2)
	SetGLCoreContext(true);
#endif
	if (!LibretroHWRenderContext::Init(true))
		return false;

	g_Config.iGPUBackend = (int)GPUBackend::OPENGL;
	return true;
}
```

**Comment by unknownbrackets** [comment]
I assume that message is from libretro:
https://github.com/hrydgard/ppsspp/search?q=%22Found+display+server%22&unscoped_q=%22Found+display+server%22

Anyway, it would be useful to know what glewInit is returning - can get a string of it with `glewGetErrorString(err)`.

Might have to set a breakpoint at glewInit and step through to see where things go wrong.

-[Unknown]

**Comment by i30817** [comment]
Unfortunately the string is '[libretro ERROR] [G3D] glewInit() failed: Unknown error'.

I'm unsure how to add and use breakpoints in gdb for this. I presume i'm building with ./b.sh --debug --libretro, then add the breakpoint in gdb then run then step until it crashes. Which file contains the libretro glewInit()? and is it different from the system glewInit?

**Comment by i30817** [comment]
Ok i don't really know how to debug a breakpoint on a dynamically loaded .so I guess.

I'm doing this:
`gdb [path to retroarch exec]`

I do:
`break /media/i30817/Huginn/Documents/projects/ppsspp/libretro/LibretroGraphicsContext.cpp:CreateDrawContext() `

gdb says to me:
```
No symbol table is loaded.  Use the "file" command. 
Make breakpoint pending on future shared library load? (y or [n])
```
I say yes of course (btw i used the file command before with the .so to see if the function name i gave to the break was correct, though running after that file does nothing because the .so needs to run from retroarch)

Then i do run and run a psp game in RA. Then the crash occurs as usual without triggering the break. I don't know what i'm supposed to do here.

**Comment by i30817** [comment]
I think glew.c is not being compiled with --debug or the libretro build is not using the 'ext' version here. Because when i stepped into it it skipped over the debug until it returned to the function instead of going inside it, which if the `libretro/ext/glew/glew.c` copy was being used shouldn't have happened.

**Comment by i30817** [comment]
I'm a bit perplexed how i'm supposed to make the obvious replacement of glew.c in `libretro/ext/glew/glew.c` override `ext/glew/glew.c` without copying it over. 

The libretro version is a single file missing the GL/ headers dir and glewinfo.c and visualinfo.c; not to mention that when the system glew is missing (i uninstalled it) b.sh chooses the external top level, not the libretro external.

**Comment by i30817** [comment]
Ok, now it's going somewhere. Both the system and the 'normal' glew that ppsspp build falls back on to fail at

```
GLenum glxewInit ()
{
  Display* display;
  int major, minor;
  const GLubyte* extStart;
  const GLubyte* extEnd;
  /* initialize core GLX 1.2 */
  if (_glewInit_GLX_VERSION_1_2()) return GLEW_ERROR_GLX_VERSION_11_ONLY;
  /* check for a display */
  display = glXGetCurrentDisplay();
  if (display == NULL) return GLEW_ERROR_NO_GLX_DISPLAY;
```
I'm not sure if this is because of that earlier `[INFO] [Video]: Found display server: null` or not, but the fact it tries to get a 'X' current display in wayland should be self explanatory. Current glew apparently really really doesn't like wayland, so now i'll try to copy over the libretro version of glew.c.

**Comment by i30817** [comment]
Ok... this was painful but there is a light at the end of the tunnel.

First i uninstalled system glew to force the build to externals: `sudo apt-get remove libglew-dev`

Then i duplicated the glew dir from the `ext/glew` to `ext/glew_libretro`. Then i copied `libretro/ext/glew/glew.c`; and `libretro/libretro.h` to that new dir, overwriting the old glew.c.

Then i added a CMakeLists.txt to the new dir:
```
find_package(OpenGL REQUIRED)
add_library(glew STATIC
	libretro.h
	GL/glew.h
	GL/glxew.h
	GL/wglew.h
	glew.c
)
add_library(Ext::GLEW ALIAS glew)
target_link_libraries(glew PUBLIC ${OPENGL_LIBRARIES})
target_compile_definitions(glew PUBLIC GLEW_STATIC)
target_include_directories(glew PUBLIC . ${OPENGL_INCLUDE_DIR})
set_target_properties(glew PROPERTIES
EXCLUDE_FROM_ALL ON
)
```

Then i edited the CMakeMakeLists.txt of the folder above (notice that this is the wrong test, you'd need something to test a wayland instead of libretro build, but i'm using libretro as a proxy of wayland without xwayland available (which happens in a compile of retroarch without X11 compatibility, because it's slightly faster). Ideally you'd use something like 'LIBRETRO_WAYLAND' and 'LIBRETRO_X11'.

```
diff --git a/ext/CMakeLists.txt b/ext/CMakeLists.txt
index 16b4adbd7..efedc8fae 100644
--- a/ext/CMakeLists.txt
+++ b/ext/CMakeLists.txt
@@ -1,9 +1,12 @@
 set(ARMIPS_REGEXP OFF CACHE BOOL "" FORCE)
 
 add_subdirectory(armips)
-if(NOT USING_GLES2)
+if(NOT USING_GLES2 AND NOT LIBRETRO)
        add_subdirectory(glew)
 endif()
+if(NOT USING_GLES2 AND LIBRETRO)
+       add_subdirectory(glew_libretro)
+endif()
 
 set(ENABLE_GLSLANG_BINARIES OFF CACHE BOOL "let's not build binaries we don't need" FORCE)
 set(SPIRV_CROSS_EXCEPTIONS_TO_ASSERTIONS ON CACHE BOOL "let's not use exceptions" FORCE)

```

A modification for adding `SetGLCoreContext(true);` wasn't needed so i didn't add it, though i'm not sure if I should and where.

Finally I built with : `CMAKE_ARGS="-DHAVE_OPENGL_CORE=ON -DUSING_GLES2=OFF" ./b.sh --libretro --debug --no-package` and placed it in the right Retroarch dir.

It started with the retroarch 'gl' driver and blackscreened with the 'glcore' driver; however i'm pretty sure that `-DHAVE_OPENGL_CORE=ON` is being filtered out of the CMAKE environment because of this warning: 

```
CMake Warning:
  Manually-specified variables were not used by the project:

    HAVE_OPENGL_CORE
```

So i think that's because of that. Not sure how to solve it?

Anyway do you think the `b.sh --libretro` should be fixed for libretro on wayland like this?

**Comment by i30817** [comment]
I'm going to open a PR with extensions following the ideas on the outdated comment here to make it easy to build RA for libretro (in retroarch with support for XWayland) or libretro (in retroarch with support for Wayland) or libretro (for gl3.1+) or combinations.

I probably won't add entries to `b.sh` but i will give cmake options to make it easy to activate or deactivate these.

**Comment by i30817** [comment]
Ok i have a branch that runs but it basically crashes or hangs in when it tries to stop or destroy the GL thread.

For instance when you ask the core to close it keeps waiting at
`ext/native/thin3d/GLRenderManager.cpp:199` at ThreadFrame() in that wait.
```
			std::unique_lock<std::mutex> lock(frameData.pull_mutex);
			while (!frameData.readyForRun && run_) {
				VLOG("PULL: Waiting for frame[%d].readyForRun", threadFrame_);
				frameData.pull_condVar.wait(lock);
			}
```
Dunno how to fix this so i'm not sure i should open the pr. BTW here is what i did:

1. created a copy of the dir `ext/glew` called `ext/glew_libretro` and copied `libretro.h` and the libretro version of `glew.c` there.
2. applied this patch (creating 1 and modifying 2 CMakeLists.txt):
```
diff --git a/ext/CMakeLists.txt b/ext/CMakeLists.txt
index 16b4adbd..cad70284 100644
--- a/ext/CMakeLists.txt
+++ b/ext/CMakeLists.txt
@@ -2,7 +2,14 @@ set(ARMIPS_REGEXP OFF CACHE BOOL "" FORCE)
 
 add_subdirectory(armips)
 if(NOT USING_GLES2)
-	add_subdirectory(glew)
+	if(LIBRETRO)
+		#if using libretro without gles, use a glew with support for libretro_get_proc_address
+		#needed to run the core in environments without XWayland, such as retroarch in KMS
+		#or retroarch built with wayland but without x11 support
+		add_subdirectory(glew_libretro)
+	else()
+		add_subdirectory(glew)
+	endif()
 endif()
 
 set(ENABLE_GLSLANG_BINARIES OFF CACHE BOOL "let's not build binaries we don't need" FORCE)
diff --git a/ext/glew_libretro/CMakeLists.txt b/ext/glew_libretro/CMakeLists.txt
new file mode 100644
index 00000000..f147939a
--- /dev/null
+++ b/ext/glew_libretro/CMakeLists.txt
@@ -0,0 +1,21 @@
+find_package(GLEW)
+if(NOT APPLE AND GLEW_FOUND)
+  add_library(system_glew INTERFACE)
+  add_library(Ext::GLEW ALIAS system_glew)
+  target_link_libraries(system_glew INTERFACE GLEW::GLEW)
+else()
+  find_package(OpenGL REQUIRED)
+  add_library(glew STATIC
+    GL/glew.h
+    GL/glxew.h
+    GL/wglew.h
+    glew.c
+  )
+  add_library(Ext::GLEW ALIAS glew)
+  target_link_libraries(glew PUBLIC ${OPENGL_LIBRARIES})
+  target_compile_definitions(glew PUBLIC GLEW_STATIC)
+  target_include_directories(glew PUBLIC . ${OPENGL_INCLUDE_DIR})
+  set_target_properties(glew PROPERTIES
+    EXCLUDE_FROM_ALL ON
+  )
+endif()
diff --git a/libretro/CMakeLists.txt b/libretro/CMakeLists.txt
index b590cc25..37fff4db 100644
--- a/libretro/CMakeLists.txt
+++ b/libretro/CMakeLists.txt
@@ -1,3 +1,8 @@
+if(NOT USING_GLES2)
+	#enable the 3.1 core variation of opengl because that's what the core advertises as the non gles2 gl requirement
+	#this enables a elif in LibretroGLContext.h after gles2 and before compatibility opengl (which is not used)
+    add_definitions(-DHAVE_OPENGL_CORE)
+endif()
 
 set(LIBRETRO_SRCS
 	libretro.cpp
```

The idea is that whenever libretro and non-gles is chosen, you get the libretro gl 3.1 superclass (since the core says it's the opengl it supports and it works on both the gl and glcore driver unlike the other) and the libretro version of glew. 
This is starting in wayland (retroarch with wayland support), x11(well, xwayland aka retroarch without wayland and with x11) and kms here - though i don't have windows to see if this version of glew works there.

The problem is that there are a bunch of other things broken. Savestates, closing the core, restarting the core, etc.

**Comment by i30817** [comment]
I guess i forgot to tell, i didn't need any of this, just to use the libretro build system (the make) instead of the cmake --libretro option (that is broken) and pass in 

`CXX='ccache g++' CC='ccache gcc' make -j2 DEBUG=0 DYNAFLAGS="-DHAVE_OPENGL_CORE"`

Basically it's possible to force the glcore context without the patch above but you must use the libretro build makefile in the libretro dir, cmake is broken for libretro.

I also had to revert https://github.com/hrydgard/ppsspp/pull/11990 because it's freezing on load again now (but the relevant issue is already reopened so nothing to do).
