### ISSUE TITLE
Touch control in Landscape auto/reversed doesn't align well

### ISSUE THREAD

**Issue by Zinogre1993** [hrydgard/ppsspp#13439]
### What happens?
— As my title implies, the touch control doesn't align well when PPSSPP's Screen rotation set to Landscape auto/reversed.

Games: MHP3rd, GE2, FFT-0, VC3E2, etc.
Backend: OpenGL/Vulkan
Display layout editor: Stretching
Ignore camera notch when centering: ✓
Fullscreen: ✓
Camera device: Back/Front Camera

I disclosed some illustrative screenshots attachment to provide you with a better understanding of my concern issue:
![IMG_20200916_185957](https://user-images.githubusercontent.com/71383385/93333535-08660100-f856-11ea-9ecb-a9effe505f24.jpg)
![IMG_20200916_185802](https://user-images.githubusercontent.com/71383385/93333556-0e5be200-f856-11ea-830e-ce4050bf41c1.jpg)

### What *should* happen?
— It should have been align well as I never have this kind of glitch with the previous builds (v1.9.4 and below). I look forward to hearing from you regarding with my concern. Hoping for your kind and consideration. Thank you.

### What hardware, operating system, and PPSSPP version?
— Realme 3: RMX1821
— OS: Android 10
— v1.10.3

**Comment by hrydgard** [comment]
Oh, this is a case I apparently missed testing when I added support for notched displays. Marking for investigation.

**Comment by unknownbrackets** [comment]
This doesn't reproduce for me currently when insets (i.e. camera gap) are in place.  Is this still an issue?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other issues on other devices.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
