### ISSUE TITLE
[ Feature Request] Change the position date

### ISSUE THREAD

**Issue by MiguelCardonaG** [hrydgard/ppsspp#13435]
### What happens?

Hello.

Can change the position of date? Instead of starting with the year, I start with the day.

![Screenshot_20200915-170913_PPSSPP](https://user-images.githubusercontent.com/65356692/93229456-e2b5fa80-f776-11ea-97d9-564f66ca41ed.jpg)

In Spain it is, first the day, second the month and finally the year.

### What *should* happen?
I'd like it to stay that way; 15-9-20.

**Comment by nassau-tk** [comment]
”YYYY-MM-DD” is generaly in Japan.

**Comment by unknownbrackets** [comment]
Isn't this a setting?  System Settings -> Date Format.

-[Unknown]

**Comment by nassau-tk** [comment]
@unknownbrackets 

No,It's not change on date of savestate.

**Comment by MiguelCardonaG** [comment]
Work good. Thanks.

![PPSSPP_2020-09-17-16-34-59](https://user-images.githubusercontent.com/65356692/93486035-03f82180-f904-11ea-8685-1533f994b11b.jpg)
