### ISSUE TITLE
Graphical Regression in Burnout games Since v1.10.3-661-ga6084f6fe

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#13431]
It seems #13420 broke Burnout games here's a list of bugs

Burnout Legends:
in Car select screen in legends the car textures are black:
![Screenshot_2020-09-15-00-09-43-22_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/93111802-b86a2b80-f6e9-11ea-89b2-c91138fe2a63.png)

Some tracks gave big performance killing problem (winter city, silver lake, waterfront, etc)
Before v1.10.3-661-ga6084f6fe:
![Screenshot_2020-09-15-00-07-04-60_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/93112425-91602980-f6ea-11ea-88fd-fc4c1d634416.png)

After v1.10.3-661-ga6084f6fe:
![Screenshot_2020-09-15-00-10-01-75_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/93112458-a0df7280-f6ea-11ea-9c3d-2443fe8ecb6b.png)

During in-game the police cars textures became black:
![Screenshot_2020-09-15-00-11-45-02_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/93112711-e439e100-f6ea-11ea-9a64-f9c64f0d8caf.png)

The Flags are corrupted (as i reported in r/EmulationOnAndroid in Reddit)
![df7e6a3](https://user-images.githubusercontent.com/37503397/93113069-4eeb1c80-f6eb-11ea-9cb5-d96f98288c41.jpg)

In Burnout Dominator I don't notice any Graphical glitches but big performance bottleneck:

Before v1.10.3-661-ga6084f6fe (i turned off simulate block transfer effects):
![Screenshot_2020-09-15-00-07-59-02_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/93113246-85289c00-f6eb-11ea-8e07-434a8e990e25.png)

After v1.10.3-661-ga6084f6fe:
![Screenshot_2020-09-15-00-32-49-16_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/93113416-bef9a280-f6eb-11ea-81e8-4b62fd8054e9.png)

**Comment by Panderner** [comment]
The last build worked is v1.10.3-650-g2b49c3e46
The issue started in v1.10.3-661-ga6084f6fe

**Comment by hrydgard** [comment]
Weird, but I expected some issues - would be surprising if everything was perfect after such a change. Will look into it.

**Comment by hrydgard** [comment]
Investigating this uncovered several new and old issues with the texture cache, needs a bit more work but I'll get this solved soon.

**Comment by hrydgard** [comment]
How is this now, with #13436 merged? 

(I still think there's a bug lurking somewhere but it seems to be hiding now...)

**Comment by Panderner** [comment]
The performance killing problem is gone but the textures in car selection screen and police cars in-game are not fixed.
![Screenshot_2020-09-16-16-03-06-94_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/93309540-389da780-f836-11ea-952e-065baecf8c82.png)
![Screenshot_2020-09-16-16-01-15-60_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/93309563-405d4c00-f836-11ea-913f-5ddc56ca20f2.png)

**Comment by Panderner** [comment]
Here's a GE Dump of unfixed issues
[Car Selection.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/5230765/Car.Selection.ppdmp.zip)
[Police.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/5230767/Police.ppdmp.zip)

**Comment by Gamemulatorer** [comment]
Performance still decrease on my phone using default settings unlike in the previous build this game run 25/30fps also texture bugs also present on my phone mali-450 gpu opengl
![Screenshot_20200916-171541](https://user-images.githubusercontent.com/37603562/93317911-9931e200-f840-11ea-8828-92750bf2863b.png)
![Uploading Screenshot_20200916-171615.png…]()

**Comment by Panderner** [comment]
> Performance still decrease on my phone using default settings unlike in the previous build this game run 25/30fps also texture bugs also present on my phone mali-450 gpu opengl

could you reupload the 3rd image? it's corrupted

**Comment by hrydgard** [comment]
Thanks guys. Still more investigation to do.

**Comment by Gamemulatorer** [comment]
> > Performance still decrease on my phone using default settings unlike in the previous build this game run 25/30fps also texture bugs also present on my phone mali-450 gpu opengl
> 
> could you reupload the 3rd image? it's corrupted

It was the second picture so I reupload the third pic is the same as the second pic 😅

**Comment by kage2051** [comment]
@Gamemulatorer 
In your case, you might want to check the new 'Clear framebuffer on first use' option, as well as disabling slow effects.

You cannot expect every game to run fullspeed on a Mali-450 phone, due to the fact their GPU drivers are pretty old for today's standards.

**Comment by hrydgard** [comment]
Yeah well, we clearly still have a bug here, that can contribute to the slow speed - it's not expected to be slower now than it was before #13420, if it is, it's a bug.

**Comment by hrydgard** [comment]
Note to self: Cause of the crash on Intel (and possibly other issues) seem to be related to vkCmdCopyImage (color) in VulkanQueueRunner::PerformCopy.

**Comment by Gamemulatorer** [comment]
> @Gamemulatorer
> In your case, you might want to check the new 'Clear framebuffer on first use' option, as well as disabling slow effects.
> 
> You cannot expect every game to run fullspeed on a Mali-450 phone, due to the fact their GPU drivers are pretty old for today's standards.

I'm not expecting full lol, but compare here https://github.com/hrydgard/ppsspp/pull/13246#issuecomment-670345614 this game run smooth compare to the current ppsspp build that I only got 15/30fps with the same settings 🤔

**Comment by Panderner** [comment]
it seems the headlights and wheels are glitched too
![Screenshot_2020-09-18-07-08-33-54_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/93537676-ca183100-f97e-11ea-84f1-8949a4120ca1.png)
![Screenshot_2020-09-18-07-13-59-42_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/93537695-d2706c00-f97e-11ea-9230-97686b55b239.png)

**Comment by Panderner** [comment]
And damaged cars during crash sequence and after crash in road rage are glitched too.
![Screenshot_2020-09-18-07-20-12-95_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/93538225-2891df00-f980-11ea-8ecc-234584d363af.png)
![Screenshot_2020-09-18-07-23-31-77_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/93538232-2c256600-f980-11ea-8559-198257c69c76.png)

**Comment by Gamemulatorer** [comment]
The performance is good now on my phone but still have a lot of graphics glitch
![Screenshot_20200917-092504](https://user-images.githubusercontent.com/37603562/93546816-3ce0d680-f996-11ea-84af-9e29372bcc72.png)
![Screenshot_20200918-100447](https://user-images.githubusercontent.com/37603562/93546897-70bbfc00-f996-11ea-8935-ce1e26cb9099.png)

**Comment by Gamemulatorer** [comment]
PPSSPP v1.10.725 the graphics glitch is ok now on my phone mali-450 gpu opengl
![Screenshot_20200921-135859](https://user-images.githubusercontent.com/37603562/93736451-f8ae3a00-fc12-11ea-8e35-872408879016.png)
![Screenshot_20200921-135914](https://user-images.githubusercontent.com/37603562/93736458-fe0b8480-fc12-11ea-8f77-973edfcb3d71.png)
![Screenshot_20200921-135839](https://user-images.githubusercontent.com/37603562/93736474-0f549100-fc13-11ea-9dad-396a30b30a6e.png)
![Screenshot_20200921-135828](https://user-images.githubusercontent.com/37603562/93736489-1d0a1680-fc13-11ea-8a55-1f004a8a62e8.png)

**Comment by Panderner** [comment]
Closing this because the graphical glitches are now fixed in burnout legends but if someone still glitching in Burnout Legends or Burnout Dominator except the sun in Dominator mentioned in #11100 I'll reopen
