### ISSUE TITLE
[Windows][OpenGL/D3D9][Lagging] FINAL FANTASY (ULJM052441)

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#13449]
### What happens?
FINAL FANTASY (ULJM052441) is a little lagging.
I hope that you play in the state of the fast forwarding and it's understood.

### What *should* happen?
Working more smooth.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

PPSSPP Ver.：1.10.3-709
OS：Windows10（64-bit）Japanese
CPU：Ryzen7 3800X（8-core）
GPU：RADEON RADEON RX5700XT
Resolution：2560×1440
RAM：32GB

PPSSPP Ver.：1.10.3-709
OS：Android 9.0
DeviceName：SONY SO-02K / Xperia XZ1 Compact（Japan）
CPU：Snapdragon835（Octa-core）
GPU：Adreno 540
Resolution：720×1280
RAM：4GB
ROM：32GB
ExternalStrage：microSDXC 512GB

**Comment by Panderner** [comment]
@nassau-tk could you send me the screenshot?

**Comment by nassau-tk** [comment]
@Panderner 
I rec the movie.
Please Download here.
When it's transmitted, I'm happy that I want to say.
https://drive.google.com/file/d/1MASUmRpJe7JQsq3mx4Q-v7vmn0CTvvOQ/view?usp=sharing

**Comment by nassau-tk** [comment]
It will happen on OpenGL & D3D9 at Windows.
Vulkan & D3D11 is woriking smooth even if I used fast fowarding too.

**Comment by nassau-tk** [comment]
um.....
This problem is caused by RADEON?
Is this too?

Related #13460 ?

**Comment by nassau-tk** [comment]
I tested on Intel&GeForce.

OS: Windows10(64-bit)
CPU: Intel i7-4770K
GPU: NVIDIA GeForce GTX750Ti

It's working very smooth!!

Some RADEON GPU is not good on OpenGL...? :sweat:

Like a #13460 .

**Comment by Panderner** [comment]
> Some RADEON GPU is not good on OpenGL...? 😓

Yeah AMD GPU on OpenGL runs slowly for other emulators due to unoptimized AMD OpenGL driver.

**Comment by unknownbrackets** [comment]
It looks like you have texture upscaling enabled.  Does it run smooth with that off?

If yes, it's probably performing worse on the Radeon driver.  Most likely it'd be better to implement hardware upscaling on OpenGL.

-[Unknown]

**Comment by nassau-tk** [comment]
> It looks like you have texture upscaling enabled. Does it run smooth with that off?
> 
> If yes, it's probably performing worse on the Radeon driver. Most likely it'd be better to implement hardware upscaling on OpenGL.
> 
> -[Unknown]

Yes! It was a great advice for me!
 
My setting was below.
![image](https://user-images.githubusercontent.com/48179091/102883401-51e86c80-4493-11eb-8087-43d337adb3cc.png)

And, I would turn off the Upscale level then the game became working smooth.
Or, Auto & Hybrid is smooth & good seems  more than xBRZ.

But,#13460 is not changed the response by this advice.

Should I close this Issue?

**Comment by LunaMoo** [comment]
Do you mean Hybrid is faster for you than xBRZ?
 That doesn't have much sense unless you're running in power saving mode and more load boosted the CPU clocks since Hybrid makes lots more work(it includes xBRZ and does additional work on top of that) and usually is much slower.

**Comment by nassau-tk** [comment]
Really?!

Fm...
I will try to check more.

**Comment by nassau-tk** [comment]
@LunaMoo 

Yes, Maybe you right!

"Turn off Upscale Level" is right way that @unknownbrackets said it.
"Yes", The lag has disappeared.

And, xBRz & Hybrid is my imaginary (I got wrong feeling).

Maybe, This issue will happening by "RADEON Driver's issue".
So, I close this topic.

Thanks everyone.
