### ISSUE TITLE
(Libretro) Clean up/update core options?

### ISSUE THREAD

**Issue by bslenul** [hrydgard/ppsspp#13448]
### What happens?

Some core options are incorrect or misleading, a few example:

* **Texture Scaling Level**: you can chose 1/2/3/4/5/0, "1" is for "off", "2/3/4/5" are for "2x/3x/4x/5x" and "0" is for "auto", could we just have proper names instead of just numbers? It'd make much more sense IMO.

I wanted to make a small PR for this one since it seems easy to fix, but I'm not a dev and I'm afraid to break something :p But I'd guess you just need to replace this:
https://github.com/hrydgard/ppsspp/blob/e8d91a2faa87513ecc337129bc10959d5d86fd86/libretro/libretro.cpp#L203
with:
```cpp
static RetroOption<int> ppsspp_texture_scaling_level("ppsspp_texture_scaling_level", "Texture Scaling Level", { { "off", 1 }, { "2x", 2 }, { "3x", 3 }, { "4x", 4 }, { "5x", 5 }, { "auto", 0 } });
```
I changed it and compiled it like that, it *seems* to work just fine, but again I don't want to break anything...

* **Frameskip**: you can chose from 0-9, in standalone it's off or 1 to 8 (not 9!).
* **Frameskip Type**: you can chose from 0-9 too, which makes absolutely no sense compared to standalone where it's "Number of frames" or "Percent of FPS"...

Other ones look fine from what I can tell.

And then, standalone seems to have options that core doesn't have ("Buffer graphics commands" for example), I'm not sure how important/useful they are, but maybe it could be a nice to have some of them available?

**Comment by soredake** [comment]
Any progress on this?
