### ISSUE TITLE
[Windows][Vulkan][Crash] When change to other backend from Vulkan on the game working .

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#13459]
### What happens?
PPSSPP will crash when change to other backend from Vulkan on the game working.
It's appear a dialog.
Please see attached screenshot.

Maybe,Android will not happen.
But,I met the issue on Android a few times.
So,I say [Maybe].

### What *should* happen?
Don't crash!!

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
PPSSPP Ver.：1.10.3-723
OS：Windows10（64-bit）Japanese
CPU：Ryzen7 3800X（8-core）
GPU：RADEON RX5700XT
Resolution：2560×1440
RAM：32GB

![Vulkan to OtherBackEnd Error](https://user-images.githubusercontent.com/48179091/93745289-3d939a00-fc2e-11ea-9c4a-ab592030e94b.png)

![Log_Vulkan to Other BackEnd Error](https://user-images.githubusercontent.com/48179091/93745443-864b5300-fc2e-11ea-9115-72ff961bebea.png)

**Comment by hrydgard** [comment]
Thanks, fixed.
