### ISSUE TITLE
[Windows][Vulkan] Gran Turismo - graphics glitches

### ISSUE THREAD

**Issue by ANR2ME** [hrydgard/ppsspp#13458]
### What happens?
![image](https://user-images.githubusercontent.com/7974720/93740530-e2a17900-fc14-11ea-8671-bb34f855bbed.png)
Flickering issue on Main Menu when using Vulkan compared to D3D11.
FPS also less stable on Vulkan compared to D3D11 on Main Menu, sometimes could drops to under 50 FPS if the flicker got worsen

Also minor text issue showing too much of letter "u" sometimes on both Vulkan and D3D11, for example if my nickname is "Azuka" it's shown as "Azuua" during the race on multiplayer, just like what happen to "Multiplayer" shown as "Muutiplayer"
![image](https://user-images.githubusercontent.com/7974720/93741153-13ce7900-fc16-11ea-933b-1144330f2f36.png)

### What *should* happen?
Should be as smooth and as fast as D3D11 with stable FPS on Main Menu

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Laptop with Win10 x64 v2004, Geforce MX150 with driver 452.06 DCH whql

PS: Last working version for the flickering issue is v1.10.3-700-g3a38e0dfd
Not sure about the text issue, but it was showing the correct nickname when i was working on the multiplayer fix on this game based on this screenshot https://github.com/hrydgard/ppsspp/issues/13366#issuecomment-685532167

**Comment by hrydgard** [comment]
This menu screen is really evil in how it does drawing :) Individual framebuffer copies for every little letter of text. Found and fixed a regression but there's more to be done here (I want it fast even in debug builds, and it isn't). The U too needs fixing ...

**Comment by Panderner** [comment]
Hey @ANR2ME could you produce this issue using a real PSP fonts?

**Comment by hrydgard** [comment]
The game uses its own fonts here, real PSP fonts or not doesn't matter.

**Comment by ANR2ME** [comment]
Well from this older screenshot it's showing my nickname correctly, so the text issue probably happened recently.

Sometimes i'm seeing the wrong letter ("u") on "Multiplayer" switches with the correct letter ("l") randomly (feels like a slow flicker on that letter alone) in the Multiplayer screen (the next menu after selecting Multiplayer from Main Menu)
https://user-images.githubusercontent.com/7974720/91967189-13d90880-ed3d-11ea-9d0d-b5a087d13b63.png

**Comment by hrydgard** [comment]
Yeah, it should of course be investigated and fixed again, clearly a bug of some sort.

**Comment by ANR2ME** [comment]
I though only letter "u" is the only one having the issue, but apparently letter "i" is also getting duplicated, like "available" became "avaiiable"
![image](https://user-images.githubusercontent.com/7974720/93843829-6b77ed80-fcc5-11ea-824c-3cdb44ad1546.png)

**Comment by nassau-tk** [comment]
I find strange text on GranTurismo (UCJS10100) Japan ver..
Maybe, Same bug at adove?

It's tested on Windows10(64-bit)/Ryzen7 3800X/RADEON RX5700XT.
And,Tested Backends are OpenGL/Vulkan/D3D9/D3D11.
Font files installed "Real PSP Fonts".

Corect:　日産 シルビア Q's エ**ア**ロ (S14) '93

Wrogn: 日産 シルビア Q's エ**エ**ロ (S14) '93

I checked the GE dump.
GE Dump is appear the text corectly.
But,The wrong text appear on the screen.

Dump file here.
[UCJS10100_0001.zip](https://github.com/hrydgard/ppsspp/files/5259430/UCJS10100_0001.zip)
*[Screen shot]*
![granturismo_wrongtext](https://user-images.githubusercontent.com/48179091/93848761-7cd0f200-fce5-11ea-8456-07db6ea9feef.png)

**Comment by ANR2ME** [comment]
This issue seems to be resolved, so i'm closing this.

**Comment by nassau-tk** [comment]
Yes! UCJS10100 solved too.

**Comment by hrydgard** [comment]
That is actually a bit unexpected - not sure what might have solved this!

**Comment by nassau-tk** [comment]
@hrydgard 
Really!? OK
I will test past builds.

**Comment by nassau-tk** [comment]
@hrydgard 

OK. Maybe I finded the it.
v1.10.3-776 happen the issue yet.
v1.10.3-777 solved the issue.


v1.10.-777
Fix issue with duplicate texture dumps. Fixes #13487 .

**Comment by hrydgard** [comment]
Oh! Interesting. Well that does make some sense. Glad that fixed it.

**Comment by hrydgard** [comment]
Noting for future reference that this does still appear when the option "Lazy texture caching (speedup)" is selected. But that's the kind of glitch you can expect with that option on.

**Comment by nassau-tk** [comment]
Wao,I understood now.  (^o^;)

![GT_lazytexture_on](https://user-images.githubusercontent.com/48179091/95090498-5046bc80-0760-11eb-9768-fd2bb0ac259f.png)
