### ISSUE TITLE
[Windows]Crash at choose Savedata Loading on title screen.[BLEACH SC (UCJS10085) & SC2 (UCJS10106)]

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#13467]
### What happens?
BLEACH Soul Carnival (UCJS10085)
BLEACH Soul Carnival2 (UCJS10106)

Crash at choose Savedata Loading on title screen.
It happen from v1.10.3-747.
v1.10-3-741 is not happen.

Android is loading corectly on v1.10.3-747.

### What *should* happen?
Load corectly.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

OS: Windows10(64-bit)
CPU: Intel i7-4770K
GPU: NVIDIA GeForce GTX750Ti
RAM:16GB

![Bleach_SC_SaveDataLoadIssue_v1 10 3-747](https://user-images.githubusercontent.com/48179091/93950904-ca9a3880-fd7f-11ea-8ed6-563322510aee.png)

The Logging stop them.

**Comment by hrydgard** [comment]
How is this now in the latest builds? I think I fixed this in 754 (https://github.com/hrydgard/ppsspp/commit/9cdf4941f2b585661e288a4f6353201f3273fef1 )

**Comment by nassau-tk** [comment]
Yes!
It's fixed!!
