### ISSUE TITLE
Bust A Move Deluxe Black Screen when WLAN on

### ISSUE THREAD

**Issue by Lemoncak3** [hrydgard/ppsspp#13479]
I just download it and play it without WLAN it works fine, then I want to try the versus mode using AdHoc and turn on my WLAN and restart my game. After majesco can't get to title screen because it was black and waited for a while and nothing happen.

https://drive.google.com/file/d/1EHFFxq_pq0K-Shzdjdgy0ogs9S8-BowB/view?usp=drivesdk

**Comment by Panderner** [comment]
@Lemoncak3 have you set the I/O timing method to Simulate UMD Delays?

**Comment by Lemoncak3** [comment]
Will try it later, since i never change that option before because i don't know the function of that option. Thanks.

**Comment by Panderner** [comment]
It's a Duplicate of #8795
