### ISSUE TITLE
PPSSPP core crashes Retroarch on Windows.

### ISSUE THREAD

**Issue by demodanza** [hrydgard/ppsspp#13471]
### What happens?

Using the PPSSPP core on Retroarch on my Windows 7 and 10 64bits machines (gl driver) games used to load fine a week or so ago, but I assume after a couple core updates something changed because now retroarch crashes every time I load a PSP game. I have been using the same shaders and configs, besides updating the cores through the menu nothing has changed. On my Android tablet, PSP games load fine using retroarch. I'm attaching the log.

### What *should* happen?

Game should load correctly/not crash, as it did before.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

PPSSPP Core on Retroarch latest stable release using gl driver, Windows 10, 64 bits, 12gb ram, Intel core i5-6200U, Intel HD 520. Windows 7 64bits, 8gb ram, intel core i5, Intel HD 3000. Windows 10 (can't use Vulcan or direct 3d in retroarch on this machine for some reason, gl works fine though) .

Log:
[retroarch.log](https://github.com/hrydgard/ppsspp/files/5272021/retroarch.log)

**Comment by Remylenain** [comment]
Hello, 

I've exactly got the same problem, PPSSPP open a white screen then crash.

In the log console there is an exception : 

Exception code=0xc0000005 flags=0x0 at 0x00007FF8E3AD6CF8. Access violation - attempting to read data at address 0x0000000000000018

**Comment by bslenul** [comment]
Bisecting done, looks like the first bad commit is 0c885db.

Crash log: [crash-200925-015716.log](https://github.com/hrydgard/ppsspp/files/5279812/crash-200925-015716.log)

**Comment by IngwiePhoenix** [comment]
Can confirm the same issue.

I would know how to reproduce this and produce a stacktrace with LLDB on macOS but my MacBook is at servicing right now and I mainly play on Windows anyway.

So far, I got: `Exception code=0xc0000005 flags=0x0 at 0x00007FF8E2236C58. Access violation - attempting to read data at address 0x0000000000000018`

Would be neat to drop a debug-enabled PPSSPP core in to see what exactly causes the crash. One of the parameters passed to `std::string::compare` could be bad?
