### ISSUE TITLE
Breath of Fire 3 broken character texture

### ISSUE THREAD

**Issue by Lemoncak3** [hrydgard/ppsspp#13475]
Using version 747, when walking on area the character texture broken i have recorded it in video since it's hard to capture it with screenshot. When you have fix the flickering bug i didn't find this broken texture when walking, is something changed?
[BOF 3 Video](https://drive.google.com/file/d/1DsfgJGORs34JzLJ7tAIykqxgSQLm92A1/view?usp=drivesdk)

**Comment by Panderner** [comment]
@Lemoncak3 strange are you using OpenGL or Vulkan?

**Comment by Lemoncak3** [comment]
I am using OpenGL

**Comment by Panderner** [comment]
@Lemoncak3 what device are you using?

**Comment by Lemoncak3** [comment]
I am using this device :
Asus Max Pro M2
4 GB ram
Android 8.0
Snapdragon 660

**Comment by Panderner** [comment]
I can't produce this issue when i'm using Realme C2. 
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/37503397/94094265-9f801980-fe51-11ea-9969-db533499d847.gif)

**Comment by Panderner** [comment]
@mattkanwisher how the walking animation looks like in vulkan?

**Comment by Lemoncak3** [comment]
I tried in vulkan and still the same, the texture of the characters are broken. 
https://drive.google.com/file/d/1Dxq32X5E4fyRbsJ4ZoVp5yTy4LNFqUgY/view?usp=drivesdk

**Comment by Lemoncak3** [comment]
Oh when i take a another look the lazy texture caching are enabled and make the texture broken. Sorry will closed this now.
