### ISSUE TITLE
Text missing on tales of radiant mithology

### ISSUE THREAD

**Issue by Lemoncak3** [hrydgard/ppsspp#13474]
I am using version 747 and when playing tales of radiant mithology there is text missing when collecting materials and also when talk to people in town. I don't know since when this is happened but I am sure once the textbox was okay.
![Screenshot_20200924-081816](https://user-images.githubusercontent.com/67026697/94090213-44ddc200-fe3f-11ea-94e9-acdbe88fea8c.png)
![Screenshot_20200924-082026](https://user-images.githubusercontent.com/67026697/94090214-46a78580-fe3f-11ea-8b4a-7c693f6eaac9.png)

**Comment by kage2051** [comment]
Does the issue happen on Vulkan as well? I read on another issue ticket that you're using OpenGL.

**Comment by Panderner** [comment]
Enabling Lazy texture caching to fix text glitches.

Lazy texture caching off:
![Screenshot_2020-09-24-13-40-04-33_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/94105323-9c922280-fe6b-11ea-865b-1ff7de530a7a.png)

Lazy texture caching on:
![Screenshot_2020-09-24-13-40-13-25_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/94105378-b3387980-fe6b-11ea-8622-76f9969e7bae.png)

**Comment by Lemoncak3** [comment]
Oh yeah enabling lazy texture caching does fix it up. Okay i closed this then.

**Comment by hrydgard** [comment]
Good find! Gonna open this again though, it's supposed to work in either mode.

**Comment by Gamemulatorer** [comment]
> I am using version 747 and when playing tales of radiant mithology there is text missing when collecting materials and also when talk to people in town. I don't know since when this is happened but I am sure once the textbox was okay.
> ![Screenshot_20200924-081816](https://user-images.githubusercontent.com/67026697/94090213-44ddc200-fe3f-11ea-94e9-acdbe88fea8c.png)
> ![Screenshot_20200924-082026](https://user-images.githubusercontent.com/67026697/94090214-46a78580-fe3f-11ea-8b4a-7c693f6eaac9.png)

Could you try exporting a GE frame dump? These help a lot. Just make sure to export it when you see the issue - it's almost like a screenshot. If you make it while the issue isn't happening, it won't help.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

**Comment by unknownbrackets** [comment]
I can't reproduce this problem, the text looks fine without lazy texture caching enabled.  Also tried with retain changed textures.

I'm going to close and assume this was fixed already in v1.11.0.

-[Unknown]
