### ISSUE TITLE
PPSSPP Dump duplicate texture since v1.10.3-661.

### ISSUE THREAD

**Issue by Saramagrean** [hrydgard/ppsspp#13487]
### What happens?
PPSSPP Dump duplicate texture since v1.10.3-661. It happen on all backends.

![DupTex](https://user-images.githubusercontent.com/26355472/94447156-b4530900-01d3-11eb-90af-17a60328bdb7.png)

### What *should* happen?

Last work v1.10.3-650.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Windows 10 64 bit. (Intel i5-6200U, Intel HD Graphics 520)

**Comment by hrydgard** [comment]
That implicates this one: https://github.com/hrydgard/ppsspp/commit/a6084f6feed9c93df7940202b0cdfcf76790ff15

Looks like we're saving both with and without the CLUT hash. Shouldn't be too hard to track down, will fix this soon.

**Comment by hrydgard** [comment]
Should be OK now.
