### ISSUE TITLE
Cutscenes flickering in various games

### ISSUE THREAD

**Issue by Ala7x** [hrydgard/ppsspp#13499]
Device model :Leagoo Z6 
Android version :6.0
PPSSPP version:latest on play store
Backend : OpenGL
So i have star ocean ,valkerie profile lenneth and disgaea 2 every time a video cutscene (anime,CGI) it flicker like hell 
Some time I can fix this by putting ppsspp in the background and open it again but it doesn't always work I guess 
And yeah street fighter alpha 3 is flickering all the time tho

**Comment by Panderner** [comment]
@Ala7x Please use latest builds of PPSSPP and how's it fixed in latest builds
Here's a link to download latest builds 
https://buildbot.orphis.net/ppsspp/index.php?m=fulllist

**Comment by Gamemulatorer** [comment]
Download ppsspp latest git build here
https://buildbot.orphis.net/ppsspp/

**Comment by Ala7x** [comment]
Wow thanks guys 
Worked like a charm
