### ISSUE TITLE
[iOS Feature Request]Add Buggy APRR JIT for jailbroken devices

### ISSUE THREAD

**Issue by boy13epic** [hrydgard/ppsspp#13498]

**Comment by hrydgard** [comment]
I don't understand this - APRR?

**Comment by boy13epic** [comment]
Aprr jit is faster jit available to a11 and up

**Comment by boy13epic** [comment]
for ios

**Comment by hrydgard** [comment]
Link to information? I really have no idea what you're talking about.

**Comment by boy13epic** [comment]
Ok https://www.google.fr/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjV0f6U6ZXsAhVMXhoKHU7LCMoQFjAAegQIARAC&url=https%3A%2F%2Fsiguza.github.io%2FAPRR%2F&usg=AOvVaw3lv0u-vgipxnrERECb_M_C

**Comment by hrydgard** [comment]
Sounds complicated and of dubious benefit, it'll just provide a slightly faster way to switch page permissions compared to solutions we have, as far as I understand it. Don't think you'll find anyone willing to dig into this, but I'll leave it open just in case.

**Comment by hrydgard** [comment]
I no longer think this is relevant for PPSSPP, there's nothing about APRR that will help.
