### ISSUE TITLE
[Android] [OpenGL] Phantasy Star Portable Not Enough FPS / Lag Using PPSSPP Latest Build

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#13495]
### What happens?
This game is lag at the start of the mission even using 1X PSP Resolution and enable speed hack in graphics settings.
![Screenshot_2020-10-01-12-06-08](https://user-images.githubusercontent.com/37603562/94767403-d7053d80-03de-11eb-907b-80e0383a1b3e.png)

### What *should* happen?
SHOULD RUN at LEAST 25/30FPS 85% SPEED at 1X PSP RESOLUTION? 😅

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Android
Mali-450 GPU
1.36Ghz CPU
Performance mode enable using fde.ai

### Ge Dump
[ULUS10410.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/5309422/ULUS10410.ppdmp.zip)

**Comment by Panderner** [comment]
@Gamemulatorer your phone is not powerful enough to run this game at full speed. and your GPU is outdated.

**Comment by Gamemulatorer** [comment]
> @Gamemulatorer your phone is not powerful enough to run this game at full speed. and your GPU is outdated.

Im not requesting full speed for this game on my phone lol 😒
