### ISSUE TITLE
Overclocking the PSP's CPU Causing lag but it can improved by underclocking the PSP's CPU.

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#13503]
Hi it's seems the some games that are lag a lot on most android devices but it can greatly increase the performance by underclocking the PSP's CPU. but why Prevent FPS from exceeding 60 option is removed since 1.6.0?

Here's a comparison for performance:
What's Tron Evolution looks like for overclocked to 1000MHz:
![Screenshot_2020-10-03-21-28-21-40_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/95003425-d6a0b880-0611-11eb-9938-fec1084b8325.png)

and what's looks like for underclocked to 70MHz:
![Screenshot_2020-10-03-21-28-50-39_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/95003446-0059df80-0612-11eb-8969-3f6519a51bed.png)

Games affected:
~~Tron Evolution~~
~~Atari Classics Evolved~~
Open Season
Killzone Liberation
~~Scooby-Doo! Who's Watching Who?~~
Activision Hits Remixed (Manuals)
Freak out Extreme Freeride

**Comment by kage2051** [comment]
This also benefits GoW on low-end PCs/phones. By underclocking the CPU to 120, you get decent speeds on 2x resolution without frameskipping. You still need to activate the speedhacks on some devices though.

**Comment by Gamemulatorer** [comment]
Related #12811

**Comment by hrydgard** [comment]
If ForceMax60FPS improves it (as you posted on Discord), that's a better solution and we should probably add it.

**Comment by Panderner** [comment]
This how it looks in Killzone Liberation title screen:

Auto:
![Screenshot_2020-12-13-15-13-12-704_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/102005731-26100d00-3d56-11eb-954c-9305d3898f8e.jpg)

35 MHz:
![Screenshot_2020-12-13-15-14-33-880_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/102005738-37f1b000-3d56-11eb-952f-6224d87ad612.jpg)

**Comment by Panderner** [comment]
Enabling ForceMax60FPS for Killzone won't help performance.

**Comment by Panderner** [comment]
and I tried to enable ForceMax60FPS for Activision Hits Remixed but it stucks at black screen before Activision logo

**Comment by Panderner** [comment]
Games that I'm unable to add ForceMax60FPS because it won't help performance.
Open Season
Killzone Liberation
Activision Hits Remixed (Freezes before Activision logo)

**Comment by ANR2ME** [comment]
Killzone Liberation really feels strangely "heavy" on that Press Start screen, i'm also getting 45/60 fps on my laptop with 1:1 Window size, even my fan is getting noisy (ie. speeding up).
Pressing the alternative 50% speed causing the FPS to be stable at 30/60 fps.

**Comment by LunaMoo** [comment]
Killzone start menu is suffering from two things:
 - a somewhat heavy special effect.
 - PPSSPP still being much faster than the real thing.

 Not much to do about effect(Henrik did made some hack to remove it, but implementing skipdraw hacks is on a PCSX2 level of awfulness and should never be part of PPSSPP project), however the latter might improve in the future.
 Just a stupid hack I made trying to reduce crashes(and add another tool for testing) of other timing sensitive game which literally delays delay thread allowed 4 times higher render res to be used in this game's start screen(from x2 to x4 constant 60 fps, ofc that's on desktop pc) and that's with just a really poor hack that wasn't even ment for this game. Someone could implement better timings properly for more functions actually used by this game making it much ligher.

**Comment by unknownbrackets** [comment]
One thing that helps, which I thought I created at one point, is seeing the most used functions by any particular game.

It takes time to measure each function and so we haven't done it for every last one.  But if a game is calling `sceCccUTF8toUTF16` in a tight loop, it makes sense to prioritize and probably will help to get its timing right.  The most called functions are most likely to have an impact.

I think the title of this issue isn't really an issue though.  Increasing the amount of work we try to do every second (by increasing the clock speed of emulation) should at best do nothing, and at worst cause lag.  Reducing the amount of work we're doing each second (by decreasing the clock speed) may improve performance with the risk of not doing things the game expects to get done.  There's no bug there.

"Overclocking" sounds like it should always improve performance, but you're actually not overclocking your device - instead, the device you're emulating is being "overclocked."  So it reverses everything, just like emulating a PS3 is harder than emulating a NES.  Making it more powerful doesn't make emulation faster, it makes it slower.

You can think of it the same as travel or shipping.  Let's imagine you're ordering products online from a company.  You tell them that you expect delivery by a specific time or date, and if anything arrives later you won't accept it or pay for it.
 * If you decrease the amount of time you're willing to wait (underclock), you'll get less stuff.
   * That item that always takes 3 days to ship will be unavailable to you (reducing actual rendered FPS.)
   * The things you do get will probably arrive slightly faster, improving "performance".
   * At a certain extreme, nothing will work ("it must be here in 60 seconds or less.")
 * If you increase the amount of time you're willing to wait (overclock), it maximizes what you get.
   * As you increase, all potential items will be available to you (FPS becomes more stable.)  Like preorders.
   * The more willing you are to wait, the slower things will arrive, reducing performance (even if they could've arrived sooner.)
   * At a certain extreme, you'll be waiting so long you never practically get anything (like some kickstarters.)

-[Unknown]

**Comment by unknownbrackets** [comment]
We made some adjustments to CPU instruction timing.  We'll make more, but I'm thinking this issue should be closed - as I explain above, it's completely logical that overclocking the PSP CPU would increase lag.

-[Unknown]

**Comment by Panderner** [comment]
Why closing? that's a big issue for low end devices, If the game starts lagging if the CPU clock is set to auto but it can improved the performance by lowering the CPU clock speed. Killzone and Open Season are the examples of problem games.

**Comment by LunaMoo** [comment]
Because it's not an issue, but expected behaviour. Changing CPU clock can be used as a game breaking speedhack when lowering it, it can also be used to achieve better/smoother gameplay at the cost of increasing the requirements, this is completely expected and normal behaviour, not a bug.

**Comment by Panderner** [comment]
Note: enabling ForceMax60FPS Spider-Man 3 had no effect for performance.

**Comment by Gamemulatorer** [comment]
> Note: Enabling ForceMax60FPS for Spider-Man 3 had no effect for performance.

Maybe on your phone but not on mine 😉
Also there is no negative using ForceMax60FPS on Spider-Man 3 right?

**Comment by Panderner** [comment]
> Also there is no negative effect using ForceMax60FPS on Spider-Man 3 right?

Umm yeah I overclocked the CPU to 1000MHz for this game no big performance decrease.
