### ISSUE TITLE
Persona 2 innocent sin fps drop

### ISSUE THREAD

**Issue by Ala7x** [hrydgard/ppsspp#13502]
Device model:Leagoo z6
Android version:6.0
PPSSPP version :latest android github build 
(Same for the playstore version)
Some times the game fps drops I guess 
I tried frameskipping :at first frameskipping kills the game making it unplayable but later for some reason frameskipping worked at how its supposed to be 
But what really matters here that framskipping (on 2) fix the sound chopping but make the game moves a lot forward or something but on 1 the game works good but the sound is very annoying 
I dunno why I have fps drops on this game since I tried more powerful games (I guess they are since this is nearly 2d game)and they worked well 
Notice: I have a vague memory that I played this game on this device and it worked well I'm not sure tho

**Comment by Gamemulatorer** [comment]
Leagoo Z6 hardware is not good to run this game without frame drop :(
### Hardware CPU Quad-Core 1.3GHz ARM Cortex-A7 GPU ARM Mali-400 MP2 2-Cores RAM (Memory) 1GB Internal Storage 8GB

**Comment by kage2051** [comment]
> Leagoo Z6 hardware is not good to run this game without frame drop :(
> 
> ### Hardware CPU Quad-Core 1.3GHz ARM Cortex-A7 GPU ARM Mali-400 MP2 2-Cores RAM (Memory) 1GB Internal Storage 8GB

Yes, one cannot expect good performance with such setting. You need at least 1.8GHz and a modern GPU (such as Adreno 509) if you want decent speeds.

**Comment by ANR2ME** [comment]
2D games can be more demanding on the CPU side compared to the so called more powerful 3D games :) so 1.3 ghz might be too low isn't?

**Comment by Panderner** [comment]
@Ala7x have you lowered the rendering resolution to 1x?

**Comment by Ala7x** [comment]
I lowered the resolution but the performance is the same 
Im pretty sure I played the game like 1 year ago and I remember having no lags 
I heard multithreadig can fix it or something but I can't find it

**Comment by Ala7x** [comment]
Guys I found it I changed the resolution to 1:1 and for some random reason I guess it worked no sound cracking anymore 
Thank you for replying guys
