### ISSUE TITLE
Graphical glitches in Dragon Ball Z: Tenkaichi Tag Team

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#13517]
There's a graphical issue where the glitching lines are drawn inside the clouds but it does not occur on real hardware.

PPSSPP:
![Screenshot_2020-10-06-21-19-32-80_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/95207344-58633280-081a-11eb-9ee2-57f16ccd831c.png)

PPSSPP's Software Renderer:
![Screenshot_2020-10-06-21-29-20-03_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/95208059-2dc5a980-081b-11eb-81bb-d116bcc991e7.png)

Real Hardware:
![Screenshot_2020-10-06-21-27-22-41](https://user-images.githubusercontent.com/37503397/95208085-37e7a800-081b-11eb-982a-84cd252066a9.png)

Here's a GE Dump:
[recording.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/5334142/recording.ppdmp.zip)

**Comment by hrydgard** [comment]
I was pretty sure this game worked fine. What hardware? GL or Vulkan?

**Comment by Panderner** [comment]
I'm using OpenGL but my phone doesn't support vulkan

**Comment by hrydgard** [comment]
Definitely a math precision issue, I can repro this now on Vulkan after my recent attempts at being more consistent with precision - 34efa1281b81bc. 

Will fix soon

**Comment by hrydgard** [comment]
Hm fixing it on Vulkan was trivial but I'm having some bizarre issue on OpenGL on a Huawei device where whatever change I make to the shader, it breaks the outlines entirely (!). It's like it's cached a working shader with exactly the text I'm using now but any change and it recompiles and breaks. Very odd.

**Comment by hrydgard** [comment]
Hm, shader-depal was broken, the uniform not updated properly. Fixing that!

**Comment by Panderner** [comment]
@hrydgard I'm using PowerVR GPU.

**Comment by Gamemulatorer** [comment]
Cannot reproduce this on my RN9 Mali-G52 GPU using ppsspp v1.10 🤔
