### ISSUE TITLE
[OGL/Vulkan] God Eater series — Text glitches

### ISSUE THREAD

**Issue by kage2051** [hrydgard/ppsspp#13511]
![Screenshot_2020-10-05-11-57-44-692_org ppsspp ppsspp](https://user-images.githubusercontent.com/25725203/95115261-69208500-0702-11eb-95cb-ffabab99bf9c.jpg)

As you can see in the screenshot, text glitches itself randomly, this issue happens on both backends even with default settings (yes, I used them to make sure). Latest git build was used. I remember playing them on the stable build with no glitched text.

I should mention that I made the test on a few devices with different specs, where I could reproduce the same issue.

**Comment by Panderner** [comment]
@kage2051 last build worked?

**Comment by kage2051** [comment]
> @kage2051 last build worked?

It was sometime before the recent framebuffer work, if I remember correctly.

**Comment by hrydgard** [comment]
Strangely, this one seems all OK if you turn on Lazy Texture Cache - opposite of #13458 .

Definitely some kind of bug in the texture cache, as the "non-lazy" texture cache mode should handle things like this.

**Comment by hrydgard** [comment]
There's some kind of weird bug in the texture cache - for some reason, these little character textures get promoted to "reliable" and then never hashed properly again, even with lazy texture cache off. Investigating.

**Comment by hrydgard** [comment]
Fixed.
