### ISSUE TITLE
Persona 3 Portable text disappears from save screen

### ISSUE THREAD

**Issue by sumit0190** [hrydgard/ppsspp#13518]
### What happens?
After playing Persona 3 (ULUS10512) for a while (usually after an hour or so), the text on the save screen disappears entirely, and an error is seen in the console:
`E[SCEKERNEL]: Util\BlockAllocator.cpp:140 Block Allocator (08000000-08400000) failed to allocate 46080 (0000b400) bytes of contiguous memory`.
The error is repeated on the console for as long as the user is on the save screen.

This is visible in the screenshots below (the first one is the screen when the system asks you to select the save data, the second one is when the system asks you if you are sure you want to overwrite the data).

![saveDataInfo](https://user-images.githubusercontent.com/8823156/95374327-30241400-08ac-11eb-9496-0a05801d0116.jpg)
![savePrompt](https://user-images.githubusercontent.com/8823156/95374342-3619f500-08ac-11eb-981a-a1c65da0479c.jpg)

**This is always reproducible from the attached savestate.**

To reproduce this:
1) Load the ROM.
2) Load the attached savestate.
3) Try to save the game (using the open register on the desk).

**The problem vanishes after resetting the emulator**.

To see this behavior:
1) Load the ROM.
2) Load the attached savefile.
3) Try to save the game (using the open register on the desk).

To be clear, the game save is from the same point in the game as the savestate.

### What *should* happen?
The save prompt and the save-data info should be correctly visible, like in the screenshot below (taken after resetting the system).
![ULUS10512_00000](https://user-images.githubusercontent.com/8823156/95374957-f8699c00-08ac-11eb-8794-1a1f0681b14a.jpg)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Windows 10 x64 (Version 10.0.18363 Build 18363)
Intel i5-6600K @ 3.5GHz
GeForce GTX 970
Direct3D 11
PPSSPP v1.10.3 release build
[persona3saveStateAndData.zip](https://github.com/hrydgard/ppsspp/files/5343222/persona3saveStateAndData.zip)

**Comment by hrydgard** [comment]
Thanks for reporting, must be a result of the new truetype font rendering for game dialogs. Some kind of bug or just fragmentation? hm.

**Comment by sumit0190** [comment]
Looks like the allocation fails when trying to set the texture for the save icon. I put a breakpoint at `Util\BlockAllocator.cpp:141` (where the error occurs) and observed the stack:
```
PPSSPPDebug.exe!BlockAllocator::AllocAligned(unsigned int & size, unsigned int sizeGrain, unsigned int grain, bool fromTop, const char * tag) Line 141
PPSSPPDebug.exe!BlockAllocator::Alloc(unsigned int & size, bool fromTop, const char * tag) Line 149
PPSSPPDebug.exe!__PPGeDoAlloc(unsigned int & size, bool fromTop, const char * name) Line 194
PPSSPPDebug.exe!PPGeImage::Load() Line 1221
PPSSPPDebug.exe!PPGeImage::SetTexture() Line 1283
PPSSPPDebug.exe!PSPSaveDialog::DisplaySaveList(bool canMove) Line 381
PPSSPPDebug.exe!PSPSaveDialog::Update(int animSpeed) Line 628
PPSSPPDebug.exe!sceUtilitySavedataUpdate(int animSpeed) Line 250
PPSSPPDebug.exe!WrapI_I<&sceUtilitySavedataUpdate>() Line 251
PPSSPPDebug.exe!CallSyscallWithoutFlags(const HLEFunction * info) Line 652
```
I can probably investigate further if you'd be kind enough to give me some pointers on where to go next.

**Comment by Lemoncak3** [comment]
I can't produce this issue or is it only for male protagonist?

![Uploading Screenshot_20201018-184223.png…]()

This is the video
https://drive.google.com/file/d/1NxCLeZLwJn0O2DlSRBTisOgYrYdBd5t9/view?usp=drivesdk
