### ISSUE TITLE
[Android] In-game saves don't work

### ISSUE THREAD

**Issue by jeffman** [hrydgard/ppsspp#13524]
### What happens?
1. Start game (in my case: Cave Story)
2. Use in-game save feature (Cave Story: play through the first cutscene, save using the spinning floppy disk in the start cave; in-game text confirms that it saved)
3. Exit game (Cave Story: press Start, go to Exit)
4. Restart game
5. No previously saved data appears (Cave Story: going to Load plays the intro cutscene again instead of loading you in the cave as it should)

Save states work fine. It is only in-game saves that do not work.

### What *should* happen?
In-game saves should load. (Cave Story: going to Load should start you in the cave instead of playing the intro cutscene)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
- Android 10
- Samsung Galaxy S9 (SM-G960W, Snapdragon 845)
- PPSSPP version: 1.10.3 from Google Play Store
- Rendering backend: Vulkan
- SD card: Present (ROM is loaded from SD card)
- Memory Stick folder: /storage/emulated/0/ (I can't change this, but there is indeed a /storage/emulated/0/PSP folder with some subfolders that contain config files so that should confirm it's writable at least)

**Comment by Panderner** [comment]
In-game saves for cave story worked properly for me. I'm using Realme C2 on Android 9.

**Comment by Panderner** [comment]
but @jeffman have you tried a lastest builds?

**Comment by jeffman** [comment]
I tried both the latest build in the Play store and the latest development build for Android (v1.10.3-892-g3fe1e35e3) and I have the same issue.

**Comment by hrydgard** [comment]
Extremely strange, this has never been a problem before, and works fine for me on Galaxy S8. Are you using some custom firmware on the phone?

**Comment by jeffman** [comment]
Nope, all stock firmware and OS. I've attached a logcat from a Cave Story session. There is a file error near the end:

```
10-10 15:33:27.433 30101 11893 E PPSSPP  : [FILESYS] DirectoryFileSystem::OpenFile: FAILED, 13 - access = 26: org.ppsspp.ppsspp
```
[ppsspp-logcat.log](https://github.com/hrydgard/ppsspp/files/5359859/ppsspp-logcat.log)

**Comment by jeffman** [comment]
Figured it out. It was trying to save in the same folder as the ROM instead of in the memory stick folder. My ROM was on the SD card so I guess it doesn't have permission to write there. After moving the ROM to internal storage it works fine.
