### ISSUE TITLE
[Windows][OpenGL/Vulkan/D3D9&11][Graphic Glitch]Some games screen Shake/Vibrate/Flash.

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#13525]
### What happens?
Some games screen shake or vibrate or flash very quickly.

Muso Orochi 2 Special (ULJM06097)
Colin Mcrae Rally (ULJM05223)
~~GranTurismo (UCJS10100)~~ Sorry #12468 Thank you @Panderner

And,I find a strange things in GE Debugger.

Step1 : Open The GE Debugger.
Step2 : Click "StepFrame" button 1 time.
Step3 : Appear the preview screen of 1st frame.
Step4 : Click "StepFrame" button more 1 time.
Step5 : Appear the preview screen of next frame.

Step 4&5 are not match each preview size(or position).
But,GE Dump files are not appear the each strange size.
I think a screen seems to be vibrating because of this.
Please,See attached Gif Animation.

Is it normaly? or known bug?

Android will not happen the issue on OROCHI & GranTurismo.

### What *should* happen?
Drawing the screen size and position correctly.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Flash
PPSSPP Ver.：1.10.3-876
OS：Windows10（64-bit）Japanese
CPU：Ryzen7 3800X（8-core）
GPU：RADEON RX5700XT
Resolution：2560×1440
RAM：32GB

**Muso Orochi 2 Special**
![ULJM06097_StepFrame](https://user-images.githubusercontent.com/48179091/95646336-60fd8680-0b02-11eb-8b56-4ed9331e890e.gif)

**ColinMcreyRally**
![ULJM05223_StepFrame](https://user-images.githubusercontent.com/48179091/95646345-6f4ba280-0b02-11eb-8381-27900fd62dbb.gif)

~~**GranTurismo**   "The Real PPSSPP is vibrate more fast."~~
![UCJS10100_StepFrame](https://user-images.githubusercontent.com/48179091/95646350-7a063780-0b02-11eb-8915-b91a99182e4b.gif)

**Comment by Panderner** [comment]
Gran Turismo Shaking issue can be fixed in-game by changing the Video Output setting to external.

See https://github.com/hrydgard/ppsspp/issues/12468#issuecomment-549920844 for more info

**Comment by nassau-tk** [comment]
@Panderner 
Thank you for teach.
Edited it.
I'm not good at English.
So,I can't search it well.
Always give comment to me, and thank you very much.

**Comment by nassau-tk** [comment]
Add more game.
Pro Yakyu Spirits 2010 (NPJH50234).

This Baseball game has more seriese.
Pro Yakyu Spirits 2011 (NPJH50336).
Pro Yakyu Spirits 2012 (NPJH50520).
Pro Yakyu Spirits 2013 (NPJH50730).
Pro Yakyu Spirits 2014 (NPJH50838).

**But,This phenomenon happen only this game.**
**And,This game is not vibrate the screen.**
![NPJH50234_StepFrame](https://user-images.githubusercontent.com/48179091/95648065-80e77700-0b0f-11eb-8945-32e79ee911c6.gif)

Is not related to vibrate screen this things?

**Comment by nassau-tk** [comment]
Add more.

**Tekken 6 (NPJH50184)**
![NPJH50184_StepFrame](https://user-images.githubusercontent.com/48179091/95650666-e3487380-0b1f-11eb-9d05-57228f2d75f0.gif)

**GachiTora! Abarenbou kyoushi in High School (NPJH50409)**
**This game appear black line on right side every frame.**
![NPJH50409_EveryFrame_BlacKLine_RightSide](https://user-images.githubusercontent.com/48179091/95653527-4d6b1380-0b34-11eb-9b97-bff390a6a5b9.png)

**Comment by ANR2ME** [comment]
That black space on the right side, isn't because the frame buffer is 512 pixels while PSP display can only shows 480 pixels width? so some part of the frame buffer aren't used.

**Comment by hrydgard** [comment]
Seems we have detected one frame buffer as 512 wide and the other as 480 wide. This can happen but shouldn't have any bad effects other than looking confusing in the debugger. Does the screen actually shake in game?

The Gran Turismo problem is correct emulation, the game does that to achieve a primitive TAA effect but it of course doesn't work in higher resolution so use the in-game setting to fix that.

**Comment by nassau-tk** [comment]
@ANR2ME 
@hrydgard 

GE Dubbuger's black line is normaly isn't it?
OK! I understood it.

Screen(text?) vibrate is Muso Orochi 2 Special.
But,Text vibration stop when resize screen.

Usually,Some games not appear black line on GE Dubbuger preview window.
So,I have misunderstood.

Maybe this report and my thinking is not match isn't it?

**Comment by hrydgard** [comment]
If the black line is ONLY in GE debugger window, it's no issue. However, if it's present in gameplay or causes the screen to vibrate during gameplay, it's a problem.

**Comment by nassau-tk** [comment]
@hrydgard 
I see!!
I will close this.
Thank you!
