### ISSUE TITLE
Gundam vs Gundam Next Plus: sometimes the charge bar's map is error

### ISSUE THREAD

**Issue by leoxxx** [hrydgard/ppsspp#13531]
As shown in title.

**Comment by Panderner** [comment]
@leoxxx screenshot?

**Comment by leoxxx** [comment]
![QQ截图20201011112206](https://user-images.githubusercontent.com/5364709/95669560-c7db7800-0bb4-11eb-9c51-8b75389f2314.png)
This is the right. "Charge" flash and blue to full when charging.
![QQ截图20201011112054](https://user-images.githubusercontent.com/5364709/95669598-14bf4e80-0bb5-11eb-9cf5-d30ddd6b9cfb.png)
I'm not charging, but the bule is full.
![QQ截图20201011112222](https://user-images.githubusercontent.com/5364709/95669617-446e5680-0bb5-11eb-879f-2694ce5322d9.png)
Also not charging.
These happen sometimes after enemy attack you and not relaese the charge.
![QQ截图20201011112445](https://user-images.githubusercontent.com/5364709/95669627-623bbb80-0bb5-11eb-93d9-17f827438b4c.png)
Charging, just "charge" flash.
This often happen.
@Panderner

**Comment by unknownbrackets** [comment]
Could you try exporting a GE frame dump?  It might help in this case.  Just make sure to export it when you see the issue - it's almost like a screenshot.  If you make it while the issue isn't happening, it won't help.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by leoxxx** [comment]
Not connected to PPSSPP.
Strange,I enable the "Allow remote debugger".

**Comment by unknownbrackets** [comment]
The dump is huge for some reason, which makes it difficult for me to run this on a PSP.

That said, the draw of the bar is near the end, and textures from a white dot to blend in the hazy blue/green color.  If this is incorrect, it may be that it's a CPU issue or caused by something else, and not a rendering issue.

-[Unknown]

**Comment by Gamemulatorer** [comment]
This really a graphics issue?
I saw this psp video behave the same.
https://youtu.be/3GQJeoVIsz8

**Comment by unknownbrackets** [comment]
Can you create a new frame dump from the latest git builds?  It may create a more usable frame dump with some recent fixes.

-[Unknown]

**Comment by leoxxx** [comment]
@unknownbrackets
I'll try it later.

**Comment by leoxxx** [comment]
Maybe I found what the issue is caused by. Off "Vertex Cache",  it can solve model error, also can solve this issue. But it's not sure. I think need more test.
