### ISSUE TITLE
Gran Turismo multiplayer issues

### ISSUE THREAD

**Issue by MojoJojoDojo** [hrydgard/ppsspp#13539]
This is a strange one.
When a friend of mine host a game on one of the garages the game will load into a black screen for awhile and then disconnect (first for me then for my friend).
![image](https://user-images.githubusercontent.com/33392696/95680488-d771b580-0be2-11eb-97c0-17098fccee83.png)
The game will spam "sceNetAdhocPtpConnect(4, 0, 1)" continuously until it will show this:
![image](https://user-images.githubusercontent.com/33392696/95680884-5a940b00-0be5-11eb-876d-29cfba96929d.png)
If I host the game this won't happen and the game will continue normally.
This is what my friend gets with the log : 
![image](https://user-images.githubusercontent.com/33392696/95680906-8f07c700-0be5-11eb-89dd-77298cdea33b.png)
We both have SCENET with "Info".
There is also another minor issue that the garages will be active even with no one in them and after people got out of them.
We tried this with the PPSSPP 1.10.3 908 version.
I did try to modify the timeout option on PPSSPP but it didn't help.
Thank you for your time.

**Comment by MojoJojoDojo** [comment]
This is what happens if I host and the race succeeds : 
![image](https://user-images.githubusercontent.com/33392696/95683996-2de8ef00-0bf7-11eb-98a8-6cb35eebaf8a.png)

**Comment by ANR2ME** [comment]
The person who had these kind of log seems to have issue getting disconnected from UPnP router, so the ports might not be opened which will cause connection issue.
![image](https://user-images.githubusercontent.com/7974720/95716834-41976280-0c96-11eb-9bf2-b27aa0fd6508.png)
Is this person able to play other games with UPnP or he doesn't have UPnP router?

**Comment by MojoJojoDojo** [comment]
Decided to also do a local test with clunky here because it gives similar results : 
![image](https://user-images.githubusercontent.com/33392696/95717477-ac847180-0c75-11eb-9ee6-7b9e9e52d29a.png)

but not [4] in the end of the disconenction.

**Comment by ANR2ME** [comment]
LOL 270ms latency, most adhoc games can only handle upto 200ms latency, and packet loss rate of 10% is considered a bad connection.

**Comment by MojoJojoDojo** [comment]
> The person who had these kind of log seems to have issue getting disconnected from UPnP router, so the ports might not be opened which will cause connection issue.
> ![image](https://user-images.githubusercontent.com/7974720/95716834-41976280-0c96-11eb-9bf2-b27aa0fd6508.png)
> Is this person able to play other games with UPnP? or he doesn't have UPnP router?
> 
> This also shows an issue with UPnP router, i'll try to find out what error 404 mean
> ![image](https://user-images.githubusercontent.com/7974720/95717169-c3878b80-0c96-11eb-819a-b2766b89d392.png)
> Might be this error (not sure)
> 
> ```
> printf("DISCOVER ERROR : %d\n", code);
> 		switch(code) {
> 		case UPNPC_ERR_NO_DEVICE_FOUND:
> 			printf("UPNPC_ERR_NO_DEVICE_FOUND\n");
> 			break;
> 		case UPNPC_ERR_ROOT_DESC_ERROR:
> 			printf("UPNPC_ERR_ROOT_DESC_ERROR\n");
> 			break;
> 		case 404:
> 			printf("Root desc not found (404)\n");
> 			break;
> 		default:
> 			printf("unknown error\n");
> }
> ```

Hmm so you say its UPNP ah I never thought of it because if i host the race works.
If UPNP is not working I thought no one could play a game but ok.

> LOL 270ms latency, most adhoc games can only handle upto 200ms latency, and packet loss rate of 10% is considered a bad connection.

Ah ok lol I don't know how it is for him so I guessed it.
If it was a connection issue neither of us could have played no matter who hosted so maybe it is a UPNP issue I dont know.

**Comment by ANR2ME** [comment]
All players need to have the port opened in order to works, not only the host, so all players need to have a working UPnP/DMZ/port forwarding.

**Comment by MojoJojoDojo** [comment]
> All players need to have all required ports opened in order to works properly, not only the host, so all players need to have a working UPnP/DMZ/port forwarding.

That still does not make sense because i host and it works so it does open all the ports if I host? does it open different ports if you host or not?

**Comment by ANR2ME** [comment]
Based on the logs, may be his router occasionally got trouble with UPnP, he probably need to update his router firmware.
