### ISSUE TITLE
[Font][Japanese] jpn0.pgf modified＆fixed

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#13544]
### What happens?
@hrydgard 
I tried more brush up the "jpn0.pgf" to make easy to see and modified shape and margin.
Because, A few character is because it collapsed and broke, and was piled.
Anything can't do the perfect guarantee, but I'm thinking it becomes better.

I tested on my Xperia SO-02K(1280x720) and Windows10(FHD Display).

I tried to font test on these games below.

- Assassin's CREED : BloodLines (ULJM05571)
- Monster Hunter Portable 3rd (ULJM05800)
- GUNDAM VS GUNDAM NEXT PLUS (NPJH50107)
- JEANNE D'ARC  (UCJS10048)
- QIXX++(NPJH50199) Only Menu Screen  [exept] **Real ltn8.pgf**

I felt no problem at the some warning dialogs when starting, and the play of the several minutes and  menu screen.

But,Sorry. I don't know how to should I do.
(Um....Pull Request???? Oh...Ah....)

So,I will Upload here.
[jpn0.zip](https://github.com/hrydgard/ppsspp/files/5372252/jpn0.zip)

### What *should* happen?
If there are no problems, a renewal of "jpn0.pgf" is proposed.

**Comment by hrydgard** [comment]
Hehe, I can merge the file for you, but you better be sure this is the one we want - it's not good to check in binaries too often, they make the git repository big since all history is saved.

**Comment by nassau-tk** [comment]
>they make the git repository big since all history is saved.

Is this means ”github server will punk!!” right?
Yes sure! I should not do it don't you.

I have many ”I don't know.” that l feel so sorry.

**Comment by nassau-tk** [comment]
If you don’t mind,please tell me about PSP font.
Is there any softweare or application that can see the ".pgf" on Windows?
If it exists then I can updete font accuracy on my local PC.
Do you have any information about this?

**Comment by hrydgard** [comment]
I don't, sorry. PSP fonts are really annoying to deal with.

**Comment by nassau-tk** [comment]
OK!!
I see.
I will try on the my little desk! :smile:

**Comment by nassau-tk** [comment]
@hrydgard 
Please tell me.
If I upload the customized jpn0.pgf on my google drive and paste the link here.
Does that probably become troublesome?

**Comment by hrydgard** [comment]
Oh you can push as much as you want to your pull request, it'll only grow your repo - and if you "amend" and force-push and thus replace the commit, it won't even grow.

My issue is that I don't want to merge this binary file into the official repository many many times :)  So just tell me when you feel it's ready and I'll merge what you have pushed only, instead of merging for every change you make.  No need for Google Drive.

**Comment by nassau-tk** [comment]
@hrydgard 

OK.
I will try to setting the repository of ppsspp on Github Web.
And,Install and setting Github Desktop.
Finally,I will try to reading and learning about "Github system & how to use Github" by some web pages.:sweat_smile:

So, I close this!
Thank you for teaching!:beginner:
