### ISSUE TITLE
Tekken 5 Dark Resurrection: game data is corrupted

### ISSUE THREAD

**Issue by iax2RqPZbq** [hrydgard/ppsspp#13540]
### What happens?
After upgrading my version of PPSSPP, when loading my save file from Tekken 5 Dark Resurrection, I get "game data is corrupted: failed to load data from memory stick duo".

### What *should* happen?
Save file should load fine.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Raspberry Pi 4, Raspbian (Linux i386), PPSSPP version 0dcaeb7.

**Comment by shenweip** [comment]
Something about savedata stuff was improved recently, could you try the latest git build?

**Comment by iax2RqPZbq** [comment]
So I just built from latest source (using RetroPie's setup script); version `615e07f` but unfortuately I still get the same error message (corrupted). All of my other saves are fine. (It's possible there is some genuine data corruption but this is the only instance of it I've ever had happen...)

**Comment by iax2RqPZbq** [comment]
Some log entries if there of any help:

```
07:26:345 user_main    I[SCEUTIL]: Dialog/PSPSaveDialog.cpp:93 sceUtilitySavedataInitStart(08b7a790) - AUTOLOAD (0)
07:26:345 user_main    I[SCEUTIL]: Dialog/PSPSaveDialog.cpp:94 sceUtilitySavedataInitStart(08b7a790) : Game key (hex): 01AF6F00020070D52E2412C7E1FF83BA
07:26:545 user_main    I[SCEUTIL]: Dialog/SavedataParam.cpp:652 Loading file with size 57280 in ms0:/PSP/SAVEDATA/ULUS10139GAMEDATA/GAMEDATA
07:26:594 user_main    W[HLE]: HLE/sceOpenPSID.cpp:28 UNTESTED sceOpenPSIDGetOpenPSID(167700256)
07:26:595 user_main    W[HLE]: HLE/sceOpenPSID.cpp:28 UNTESTED sceOpenPSIDGetOpenPSID(167700384)
07:26:680 user_main    I[SCEUTIL]: HLE/sceUtility.cpp:352 00000000=sceUtilityMsgDialogInitStart(08b7c94c)
```

**Comment by shenweip** [comment]
Um... What happen if you remove the old save to let the game create a new one?

**Comment by iax2RqPZbq** [comment]
Thanks @shenweip, it overwrites it. And then it can load that one fine—but I lose all my (old) progress from the previous save file. I'm tempted to build from source the version from June/July as that's when I last updated my save file.

On an unrelated note, it looks like the save data is encrypted. Perhaps it's a proprietary (ie, specific to that game) format but maybe it's one other PSP saves use? It would be nice if there were a tool that would help me decrypt it.

**Comment by iax2RqPZbq** [comment]
I had a go at building v1.9.4 and my (old) save file now works fine. It probably works with a newer build (I'm guessing something from June/July), but the only tagged version that was sufficiently old was that one.

Something has changed since v1.9.4 RE save data.

**Comment by unknownbrackets** [comment]
Based on #14937, I think the game is validating something - maybe MAC address or OpenPSID - matches the save.  You may be able to transfer using a save state.

-[Unknown]

**Comment by lance8765** [comment]
It's incredible that, as of what, two decades later, nobody has found a way to move PSP "locked" saves like this (and Tekken 5, or Super Stardust Portable, among few others) between different PSPs, or from PSP to emulator and vice-versa.

**Comment by hrydgard** [comment]
@lance8765 I guess nobody has cared enough to make it a priority over all the other things there are to work on. Why don't you give it a shot?
