### ISSUE TITLE
Nefarius.ViGEm.Client.dll doesn't seem to work against your xinput binding.

### ISSUE THREAD

**Issue by jmoseman01** [hrydgard/ppsspp#13558]
### What happens?
I'm trying to run the following program and map an axis via vigem c# bindings but it doesn't appear to be working.

```C#
using System.Threading;
using Nefarius.ViGEm.Client;
using Nefarius.ViGEm.Client.Targets;
using Nefarius.ViGEm.Client.Targets.Xbox360;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            ViGEmClient client = new ViGEmClient();

            IXbox360Controller controller = client.CreateXbox360Controller();

            controller.Connect();

            while (true) {
                
                controller.SetAxisValue(Xbox360Axis.LeftThumbY, 3000);
                Thread.Sleep(5000);

            }

        }
    }
}
```
### What *should* happen?
It should move the character in the game forward.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Windows 10, 1.10.3

**Comment by unknownbrackets** [comment]
You may need to make it sleep longer and ensure the controls are properly mapped while its connected.

-[Unknown]

**Comment by jmoseman01** [comment]
https://www.youtube.com/watch?v=EngEEFEUyXw

**Comment by jmoseman01** [comment]
I set the value to low
