### ISSUE TITLE
Can't install ppsspp-v1.10.3-999-g3d1cf3733 on Android

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#13577]
It seems some users can't install ppsspp-v1.10.3-999-g3d1cf3733 and Newer vesions on Android Device. I'm using Realme C2 and ppsspp-v1.10.3-987-g327eb21e0 is the last build worked
![Screenshot_2020-10-23-21-43-41-84](https://user-images.githubusercontent.com/37503397/97011445-43f09b00-1579-11eb-88e9-0bf85e687efe.png)

**Comment by Panderner** [comment]
Even the ppsspp-v1.10.3-999-g3d1cf3733-android.apk is not corrupted and I have 1GB+ of free storage.

**Comment by nassau-tk** [comment]
I can't inatall 1.10.3-999 too.

Xperia SO-02K

**Comment by hrydgard** [comment]
Weird, must be something with the gradle update (Android build system). Reverted it for now, new builds should work.

**Comment by nassau-tk** [comment]
I retry download and install now.
but It's not work.

**Comment by hrydgard** [comment]
you're gonna have to wait until -1000 or later shows up, that will work.

**Comment by MiguelCardonaG** [comment]
I came to complain about the same haha.

![20201023_163239](https://user-images.githubusercontent.com/65356692/97017453-3671eb80-154e-11eb-87ef-32b3ec4018a8.jpg)

**Comment by Panderner** [comment]
![IMG_20201023_225322](https://user-images.githubusercontent.com/37503397/97019263-b44fea00-1582-11eb-822f-f6271400f7f9.jpg)
Still no Android build for v1.10.3-1000-g349fc7071 only 64-bit version of windows.

**Comment by hrydgard** [comment]
It's coming.

**Comment by Panderner** [comment]
They Confirmed v1.10.3-1000-g349fc7071 is now working to install. Closing

**Comment by hrydgard** [comment]
I would really like to understand what happened here. The latest Android Studio requires the latest gradle build to run apps properly from the IDE, and we don't want to be stuck on old Android Studio versions.

I downloaded -999 and I have no problems installing it on a Samsung Galaxy S3.

What devices will that build not run on?

**Comment by hrydgard** [comment]
Unzipped both APKs and something is weirdly different - the file dates:

![apkproblem](https://user-images.githubusercontent.com/130929/97809688-b430a800-1c6e-11eb-9397-e30ccf18284e.PNG)

Seems a new tool is used to package zip files, SignFlinger:

![signflinger](https://user-images.githubusercontent.com/130929/97809707-d4f8fd80-1c6e-11eb-9565-5765eabab8ef.png)

The changes otherwise look mostly expected...

**Comment by Panderner** [comment]
I'm using Realme C2 and I can't install ppsspp-v1.10.3-999-g3d1cf3733

**Comment by hrydgard** [comment]
what method of install did you use? `adb install` from a PC, or just the file directly?

**Comment by Panderner** [comment]
> what method of install did you use? `adb install` from a PC, or just the file directly from the browser on the app?

I'm downloaded it in https://buildbot.orphis.net/ppsspp/index.php?m=fulllist

**Comment by MiguelCardonaG** [comment]
> what method of install did you use? `adb install` from a PC, or just the file directly from the browser on the app?

I download it directly from the Opera Mobile web browser and install it from my Samsung Galaxy Note 10 Plus Exynos. And I can't install it either.

**Comment by Panderner** [comment]
> I downloaded -999 and I have no problems installing it on a Samsung Galaxy S3.

There's some issues that most recent Android versions can't install ppsspp-v1.10.3-999-g3d1cf3733.

**Comment by hrydgard** [comment]
I've tried to report this bug to Google here: https://issuetracker.google.com/issues/172153881

Until then I guess we're stuck on Android Studio 4.0. 

Older Android Studio versions can be downloaded here:

https://developer.android.com/studio/archive

**Comment by ANR2ME** [comment]
I'm using the latest Android Studio & gradle and i can still build test apk and install it on my Realme C12 (Android 10), and my testers also didn't says anything about failing to install it, so it shouldn't have any issue on them.

However, i always need to click this "Load Gradle Changes" in order to build it successfully when ever i pull a fresh one from master (because i discard gradle changes/upgrades before i pull from master)
![image](https://user-images.githubusercontent.com/7974720/98396943-264f2580-2091-11eb-8bcd-c2a07e6fd449.png)

**Comment by ANR2ME** [comment]
Hmm.. after uninstalling my own build (was built using v4.1) i try to install the latest dev build (ppsspp-v1.10.3-1196-gc483d3f06-android.apk)
Apparently i'm also getting this "App not installed" message 😯 i thought the latest dev build is using v4.0 again?

Btw, there is an update for Android Studio v4.1.1 but i haven't tried it yet.

**Comment by unknownbrackets** [comment]
I believe this is fixed, given #14147.  Closing, but please reply if there's still problems and we can reopen.

-[Unknown]
