### ISSUE TITLE
[Suggestion][Solved to Latin Font issue] I made Font File. [ltn0~7.pgf]

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#13589]
### What happens?
Please tell me.
PPSSPP has many font problem.
I think the most troublesome one is "the particularity of the PGF file".

I infer that the present "ltn file" is in the cruel state.
(As far as Jeanne d'Arc is seen.)

So,I try made only "ltn1.pgf""ltn3.pgf""ltn5.pgf""ltn7.pgf".
(Maybe can make 0/2/4/6 too. But small size hasn't way now.ltn8~15)
It's modified "Ume-Font-Mincho" by manually.

I'm Japanese.So,I can check japanese perfectly.  :stuck_out_tongue_closed_eyes:
But, I can't chekc about "English".:scream:

I have not Groundless.
But,I believe to be improved more than now.

How to way the test on this case?

**Test Result is below Animation gif.**

![JD_TExttest_ltn1_3_5_7](https://user-images.githubusercontent.com/48179091/97262210-c2905580-1863-11eb-967c-a6b69e01db32.gif)

**Comment by nassau-tk** [comment]
Offcourse, Those are distant from a "Real PSP Font", but whether it's the current state lay now means that it becomes good.

**Comment by nassau-tk** [comment]
I tested these charachers.

- ABCDEFGHIJKLMNOPQRSTUVWXYZ
- abcdefghijklmnopqrstuvwxyz
- 1234567890/*-+()[]{}<>!"#$%&'()-^=~|@`;:,.?_

I tested on  Jeanne D'arc (Not Monospaced?) and Monster Hunter Freedom(Monospaced?).
Monster Hunter Freedom has can enter the free text on "GuildCard".
Jeanne D'arc tested on between "clear the first battle" from "intro".

I think actually, "jpn0" is being used in MHF.
But, I deleted all font files and install only target font file.

Maybe, It's not become a ground isn't it?

"ttf2pgfj" is useful but not match a bit a size for ltnX.pgf.

**Comment by nassau-tk** [comment]
I made ltn0/2/4/6.pgf too.

**Comment by hrydgard** [comment]
I think it might be worth trying a different font for English, that one is really not very pretty... Hm. Something like Calibri or Segoe UI?  Primarily I want it to be a sans-serif font: https://en.wikipedia.org/wiki/Sans-serif

**Comment by nassau-tk** [comment]
@hrydgard 

Are You saying simply, "the design of the font is too bad!!"?:smile:

I check just in case.
- Sans-serif = The Gothic Style
- Serif = Antique Style

- Real PSP Font "ltn0/2/4/6.pgf" = **Sans-serif Style**
- Real PSP Font "ltn1/3/5/7.pgf" = **Serif Style**
"Jeanne d'Arc" and "EXIT" default font is [ltn1/5 = Sans-serif] (Antique Style.)
" EXIT" is done now using part jpn0.pgf.

You want change to Gothic for all font?
If you answer "Yes".
Rename below.
- ltn0.pgf　→ ltn1.pgf
- ltn2.pgf　→ ltn3.pgf
- ltn4.pgf　→ ltn5.pgf
- ltn6.pgf　→ ltn7.pgf

How do you think?

ltn0/4.pgf test on "Jeanne d'Arc".
![JD_TExttest_ltn0](https://user-images.githubusercontent.com/48179091/97791467-17dab700-1c16-11eb-953e-3e35cdcbb064.gif)

ltn1/5.pgf Test on "EXIT".
![EXIT_TExtTest_ltn0~7+jpn0](https://user-images.githubusercontent.com/48179091/97791493-65efba80-1c16-11eb-84e5-2771df9fc955.gif)

**Comment by nassau-tk** [comment]
Or "It's well-shaped." is it better to look for a serif font?
Perhaps would you like the standard shape that you're bland?

**Comment by hrydgard** [comment]
Hm right, I forgot that the PSP itself has serif fonts. Never mind then :)

Though I still think the font looks a little wide? or is it about as wide as the original PSP fonts?

**Comment by nassau-tk** [comment]
>looks a little wide?

Yes,right.
Because,I make the PGF from TrueTypeFont converting by "ttf2pgfj.exe".
It's convert only fixed Width&Hight.
This "width" is not meaning the just character.
It's meaning include "fixed blank pixel".
And,It will be programed a little wide.(ttf2pgfj.exe)

**I want the converter which can be changed to the proper width and height.**

In other words, I can't make a font which just fits same as PSP.
But I think becomes better than now.
I think an overlap of the character can be quite canceled at least.

The other day, You, merged the fixed jpn0.pgf.
That PGF is use on some English version games too.
I think It working well.

https://github.com/hrydgard/ppsspp/issues/11796#issuecomment-539194674
This wondeful propose will coming future.
Should I think all users can use a Real PSP Font when this is mounted?
When it's so, the font making now will be only a link thoroughly, but I believe improvement to be effective.

**Comment by nassau-tk** [comment]
https://github.com/hrydgard/ppsspp/issues/2788#issuecomment-289334732

@unknownbrackets has great skill I think.:smiley:

If anyone can make a simply tool of "PGF reduce size" then small font of "ltn8~15" it will better than now.
It won't be also so easy, will it?:sweat_smile:

I regrettable that I have no programming skill.:sob:

**Comment by nassau-tk** [comment]
To be honest, I think many Github people lose interest to PGF.
But,many user(Player) need these original Fonts I thnk.

**Comment by hrydgard** [comment]
I'm gonna try them out soon, stay tuned.

And yes, we're going to have to write a tool that resizes a font to match the real dimensions of the PSP font, I think...

**Comment by nassau-tk** [comment]
For reference.
![text_misalignment](https://user-images.githubusercontent.com/48179091/97820395-542f1580-1cf1-11eb-8c3a-ba3453cc43b3.png)

**Comment by nassau-tk** [comment]
This working is finished!!
But, "ltn8~15" is not fixed yet.
