### ISSUE TITLE
[Libretro] No font in loading/save screen

### ISSUE THREAD

**Issue by Kupo91** [hrydgard/ppsspp#13583]
I'm using the recent libretro core from the buildbot (linux x86_64)

Here are some screenshots from my issue:

![woamyw4lfpu51](https://user-images.githubusercontent.com/41426906/97079377-aa1a0400-15f3-11eb-88c3-3c7c8d3ddbed.jpg)
![wf8zkx4lfpu51](https://user-images.githubusercontent.com/41426906/97079379-ab4b3100-15f3-11eb-98af-1e5967277dde.jpg)
![7hh6v05lfpu51](https://user-images.githubusercontent.com/41426906/97079381-abe3c780-15f3-11eb-9361-0309471bfacb.jpg)

**Comment by Panderner** [comment]
It needs assets for PPSSPP. to fix it go to PPSSPP's directory and copy all files from assets to Retroarch/system/PPSSPP folder.
For android users. Use ZArchiver find PPSSPP APK view and extract every files from assets folder to /Retroarch/system/PPSSPP directory.

**Comment by Kupo91** [comment]
> 
> 
> It needs assets for PPSSPP. to fix it go to PPSSPP's directory and copy all files from assets to Retroarch/system/PPSSPP folder.
> For android users. Use ZArchiver find PPSSPP APK view and extract every files from assets folder to /Retroarch/system/PPSSPP directory.

This worked, thanks a lot :)
