### ISSUE TITLE
god of war chains of olympus ppsspp atlantis ship bug

### ISSUE THREAD

**Issue by dml360** [hrydgard/ppsspp#13596]
### What happens?
The game is infinitely in that part

### What *should* happen?

in 5 or 6 minutes there should be a scene where the game continues

in this video

this video shows what should happen, but for me the battle never ends, I saw on the internet that many people have the same problem
https://www.youtube.com/watch?v=G3CSzdI9wxg

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

i5 8400
gtx 1060
16gb ram
W10 pro
ppsspp: 1.10.3 - 1017 (64bits)

PS: 
I'm sorry if you already have a problem with this call, I looked it up and didn't find it

**Comment by Saramagrean** [comment]
Duplicate https://github.com/hrydgard/ppsspp/issues/8299
