### ISSUE TITLE
Preformance of Dissidia Final Fantasy Chinese patch

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#13601]
The game call this function often
W[SCEMODULE]: hle\scekernelmodule.cpp:2441 0 = sceKernelFindModuleByName(sceFont_Library): Module Not Found or Fake
Mobile Phone preformance  may be poor.
JPCSPtrace of sceKernelFindModuleByName
https://gist.github.com/sum2012/4d9c69313272f66301e8ec59ac451cb2
Notice last call is
18:13:09.131250 main_thread - <- sceKernelFindModuleByName660 0x8820C498('sceFont_Library') = 0x880CFB54
but our ppsspp return 0 for fake module.

I try something test
ppsspp full log:
https://gist.github.com/sum2012/11888fcc5a93261183e675a72e5b41ec

**Comment by unknownbrackets** [comment]
It might be worth more for performance to eat cycles in sceKernelFindModuleByName, if it really calls it a lot.  But the log doesn't really show it that often.

What does "show debug statistics" indicate as far as what's taking the most time?

-[Unknown]

**Comment by sum2012** [comment]
![1](https://user-images.githubusercontent.com/2177532/108512620-74183280-72fc-11eb-9e23-71dbf3830bce.png)

**Comment by sum2012** [comment]
![1](https://user-images.githubusercontent.com/2177532/108512700-9316c480-72fc-11eb-854a-453e935ed509.png)

**Comment by hrydgard** [comment]
Hm, maybe each individual call isn't slow enough, or we're bottlenecked by logging and it somehow doesn't show up there?

Like Unknown suggests, try calling `	hleEatCycles(1000);` in sceKernelFindModuleByName and see if that helps. Try higher values too..

**Comment by unknownbrackets** [comment]
I'd expect logging time to ultimately be included in those numbers.  Does "Kernel processing time" stay under 2ms, or are there spikes?

-[Unknown]

**Comment by hrydgard** [comment]
Hm, yeah, even if it would be backpressure from the logging thread, it should indeed show up, come to think about it.
