### ISSUE TITLE
Syphon Fillter Logan's Shadow & Resistance: Retribution Freeze upon entering multiplayer mode

### ISSUE THREAD

**Issue by MojoJojoDojo** [hrydgard/ppsspp#13607]
### What happens?
The game will freeze when you try to enter the multiplayer mode from the main menu

### What *should* happen?
Game should continue past it with no issues.

Logs :

At least on Logan's Shadow : 
`user_main    E[SCEMODULE]: HLE\sceKernelModule.cpp:2245 UNIMPL sceKernelStopUnloadSelfModuleWithStatus(00000001, 00000000, 00000000, 00000000, 00000000): game may have crashed`

https://forums.ppsspp.org/attachment.php?aid=16891

As noted on AdamN on PPSSPP forums the issue is not related to networking - it will even happen if you disable WLAN on PPSSPP.
More detailed log here : 
[ppsspplog.txt](https://github.com/hrydgard/ppsspp/files/5468875/ppsspplog.txt)
Maybe someone like @sum2012 could fix it because I always see him/her making changes related to Kernel (it seems like a kernel issue?).

**Comment by MojoJojoDojo** [comment]
[Uploading ppsspplog.txt…]()
A more detailed log here.

**Comment by ANR2ME** [comment]
You mentioned 2 different games but only provides 1 log file?

**Comment by MojoJojoDojo** [comment]
It's the same issue between both games @ANR2ME so no point.
It's also by the same developer too.

**Comment by ANR2ME** [comment]
But it could cause confusion when the dev tries to analyze the log file.
Anyway, the log file you provides doesn't seems to be coming from from Syphon Fillter Logan's Shadow.
So i'll attach the log for that game here:
[ppsspplog.txt](https://github.com/hrydgard/ppsspp/files/5468914/ppsspplog.txt)

**Comment by MojoJojoDojo** [comment]
it seems to be related to issue #4626 but I dont know if it counts as a duplicate.

**Comment by MojoJojoDojo** [comment]
Also the freeze on main menu also happens if you try to play the game on a PS Vita but not a PSP...

**Comment by shenweip** [comment]
`47:00:002 idle0        E[SCEKERNEL]: HLE\sceKernelThread.cpp:2293 sceKernelDeleteThread(285): thread not dormant`
This is odd.

**Comment by shenweip** [comment]
Please try #13608.

**Comment by Pik-a-boo** [comment]
How can I download it?
Can you give a test build here?

**Comment by MojoJojoDojo** [comment]
Can you give a test build here?
There is no way to download a build from a PR here unlike other emulators I know of.

**Comment by shenweip** [comment]
[PPSSPPWindows64-Test.zip](https://github.com/hrydgard/ppsspp/files/5469342/PPSSPPWindows64-Test.zip)

**Comment by MojoJojoDojo** [comment]
Yep it's fixed !
Thank you very much !
I will need to try Resistance as well but Logan's Shadow works for now.

**Comment by shenweip** [comment]
Glad to hear this news:)

**Comment by MojoJojoDojo** [comment]
Resistance is fixed as well.

**Comment by sum2012** [comment]
Well done @shenweip

**Comment by MojoJojoDojo** [comment]
Someone told me that the European version of Resistance still got the same issue so I am reopening this .

**Comment by shenweip** [comment]
If possible, please post log file here.

**Comment by MojoJojoDojo** [comment]
I know this is already fixed but for others to know this issue also happens if you play the game on a Vita and use adrenaline.
Maybe someone will find the fix for it useful or something.

**Comment by ANR2ME** [comment]
If you can ask them to provide the log file, it might be useful for the devs to investigate whether it was similar issue or not.

**Comment by ANR2ME** [comment]
I don't think whatever occurred on Vita can be fixed by PPSSPP :)
May be you can open an issue at https://github.com/TheOfficialFloW/Adrenaline and refer to issue, in case they're having a similar issue.

**Comment by MojoJojoDojo** [comment]
Well it freezes in both cases so I thought it is related.
Also in both cases they use emulation.
Too bad you can't report on it.

**Comment by ANR2ME** [comment]
@MojoJojoDojo Is it just me or Syphon Filter Shadow's Logan is stuck again when choosing adhoc multiplayer menu using the latest dev build? 
i think it supposed to shows the NetconfDialog instead of freezing.
