### ISSUE TITLE
Saving data issue - crash on loading old Assassin's Creed save state

### ISSUE THREAD

**Issue by faroukabd000** [hrydgard/ppsspp#13602]
I have mi a3 android zero cpu sd 665  gpu adreno 610
I start playing assassins creeds
When i click The save States and the load States button the emulator crash
And 
The game said the first memory stick that you had use it before is not detected (the auto save option in the game is not working)

**Comment by Gamemulatorer** [comment]
use ppsspp latest git build

**Comment by faroukabd000** [comment]
The old data state from phone to a new ppsspp version of other phone is not working so used new build and start the game from the beginning

**Comment by Panderner** [comment]
> The old data state from phone to a new ppsspp version of other phone is not working so used new build and start the game from the beginning

@faroukabd000 are you using a latest git build of PPSSPP?

**Comment by faroukabd000** [comment]
@panderner
Yes the latest and it works i start the game from the beginning😣
Thx

**Comment by hrydgard** [comment]
Do you still have the old save state that doesn't load? If so, can you upload it?

**Comment by faroukabd000** [comment]
https://mega.nz/#!8ENUiBzZ!W0KAkF263fs9DOK9jZDSth0K2Fvoz2lQd4upOxidiB8

**Comment by faroukabd000** [comment]
@hrydgard
https://mega.nz/#!8ENUiBzZ!W0KAkF263fs9DOK9jZDSth0K2Fvoz2lQd4upOxidiB8

**Comment by hrydgard** [comment]
Thanks! I'll investigate as soon as I can.

**Comment by hrydgard** [comment]
That state does not seem to be broken. 

I'm gonna close this, don't think there's more to do here..
