### ISSUE TITLE
Crash after drag & drop texture pack in main screen. (Windows)

### ISSUE THREAD

**Issue by Saramagrean** [hrydgard/ppsspp#13614]
### What happens?
Crash after drag & drop texture pack in main screen.

- v1.10.3-133-g5010fc846 : can install texture pack work well.
- v1.10.3-139-g89d563717 : can install texture pack sometime but sometime show error message.
![CrashInstallTexture](https://user-images.githubusercontent.com/26355472/97871591-4efcb580-1d47-11eb-9a31-e3d70546156f.png)
- 1.10.3-243-g49f1ac284 : this https://github.com/hrydgard/ppsspp/pull/13210 fixed on Android but break on Windows. (crash)

### What *should* happen?
Can install texture pack zip file via PPSSPP latest git without crash. :)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Windows 10 64 bit (Intel i5-6200, Intel HD520, Ram 8)

**Comment by hrydgard** [comment]
After that change, it no longer crashes but there's still some error checking weirdness, sometimes it only works on the second try. Gonna dig into that later.
