### ISSUE TITLE
God of War: Chains of Olympus Mid-image failure

### ISSUE THREAD

**Issue by MiguelCardonaG** [hrydgard/ppsspp#13619]
### What happens?

ppsspp-v1.10.3-1116-g627be6052-android.apk
ppsspp-v1.10.3-1107-g21830d498-android.apk

![Screenshot_20201103-095800_PPSSPP](https://user-images.githubusercontent.com/65356692/97967780-fb797e80-1dbd-11eb-80fd-216a2bd7772e.jpg)

![Screenshot_20201103-095821_PPSSPP](https://user-images.githubusercontent.com/65356692/97967817-0a603100-1dbe-11eb-980a-6be86647aa36.jpg)

ppsspp-v1.10.3-1081-gfb785f5f0-android.apk

![Screenshot_20201103-100851_PPSSPP](https://user-images.githubusercontent.com/65356692/97967982-4e533600-1dbe-11eb-9b95-bdafa3ad5c51.jpg)

![Screenshot_20201103-100906_PPSSPP](https://user-images.githubusercontent.com/65356692/97968022-5f03ac00-1dbe-11eb-91e0-153870ad5a40.jpg)

### What *should* happen?
Make the image look good in the latest versions.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Samsung Galaxy Note 10 Plus Exynos.

**Comment by Panderner** [comment]
last build worked?

**Comment by hrydgard** [comment]
Vulkan or OpenGL or both?

**Comment by hrydgard** [comment]
Never mind, this was easy to repro.

**Comment by hrydgard** [comment]
Ok, this broke in 32eb882bc6205f5b488e86bf40076d6fd2fd4e75 . Will fix later today.
