### ISSUE TITLE
Harry Potter and the Order of the Phoenix graphical problem since v1.10.3-352-gd90630c26

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#13621]
There some graphical problems for harry Potter and the Order of the Phoenix unless disable slower effects enabled.

v1.10.3-348-gdd79d33f1 and older
![Screenshot_2020-11-04-15-02-27-80_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/98080354-4673be80-1eb0-11eb-9a4c-5876b4c97c19.png)

v1.10.3-352-gd90630c26 and newer
![Screenshot_2020-11-04-15-04-56-82_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/98080375-4d023600-1eb0-11eb-8a04-62ad9b732a84.png)

Here's a GE Dump:
[ULUS10261.zip](https://github.com/hrydgard/ppsspp/files/5486062/ULUS10261.zip)

**Comment by hrydgard** [comment]
Repro's with the dump on OpenGL but not Vulkan.

**Comment by hrydgard** [comment]
Ah, this is depth fog like in Katamari, this belongs to #13256 .

Seems the GL backend (which doesn't yet support depth texturing) goes ahead and applies it with the color texture as input, I'll fix that.

**Comment by hrydgard** [comment]
Pushed a workaround.

At some point, should of course implement depth texturing for GL...
