### ISSUE TITLE
[OGL] The 3rd Birthday — minor graphical glitch

### ISSUE THREAD

**Issue by kage2051** [hrydgard/ppsspp#13628]
![Screenshot_2020-11-05-22-23-38-001_org ppsspp ppsspp](https://user-images.githubusercontent.com/25725203/98326498-09462400-1fb7-11eb-95f6-ccf5d3f56e1a.jpg)

As you can see in the screenshot above, I am getting those blue artifacts in that game, starting from git 1125 or so. Keep in mind that it is only affecting OGL, tried Vulkan and results were as it should.

**Comment by hrydgard** [comment]
Thanks for testing, I think I know what it is, will fix shortly.

**Comment by kage2051** [comment]
![Screenshot_2020-11-15-18-42-49-613_org ppsspp ppsspp](https://user-images.githubusercontent.com/25725203/99201893-cd5b4d80-2772-11eb-90ac-da4519c368b5.jpg)

As of build 1201, there are lots of white lines at almost everywhere if OGL backend is used. I don't know if it's Adreno specific or not since I don't own a Mali phone to check.
