### ISSUE TITLE
[Android][Warning screen glitch][Open GL]

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#13620]
### What happens?
This issue will happen only "OpenGL working on Android".

Maybe some warning screen is not appear.
Some one appear dark yellow screen.
some one appear rainbow square.
What's happen? I can't understand it.

After V1.10.3-1106 not working correctly.
(v1.10.3-1099 is last working build.)

Movie,game screen is OK.(Maybe)

This one Assasin's Creed:Blood Line StartUp screen.
![Screenshot_20201103-223518](https://user-images.githubusercontent.com/48179091/97992646-52b33980-1e26-11eb-805f-b6b357615036.png)

Windows(64-bit) is not happen the issue.

### What *should* happen?
Should be Working like v1.10.3-1099.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

PPSSPP Ver.：1.10.3-1106 ~ 1117
OS：Android 9.0
DeviceName：SONY SO-02K / Xperia XZ1 Compact（Japan）
CPU：Snapdragon835（Octa-core）
GPU：Adreno 540
Resolution：720×1280
RAM：4GB
ROM：32GB
ExternalStrage：microSDXC 512GB

Galaxy S20 too.

**Comment by Panderner** [comment]
Oh V1.10.3-1106 Broke Assassin's Creed too.

**Comment by hrydgard** [comment]
Thanks, will look into it. Kind of expected a few issues like this from my recent shader code rework, they will all be fixed as they are discovered.

**Comment by hrydgard** [comment]
Should be fixed now.

**Comment by nassau-tk** [comment]
Yes!
Thanks!
