### ISSUE TITLE
Error in shader compilation causing games atock on blackscreen

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#13631]
### What happens?
![Screenshot_20201106-201208](https://user-images.githubusercontent.com/37603562/98365174-f9891700-206c-11eb-88af-8a976ce42f7d.png)
### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Android 6.0
Mali-T720
OpenGL 3.1
Resolution 1920X1080
PPSSPP v1.10.3-1139

**Comment by hrydgard** [comment]
Whoops! I'll take a look at that shortly. Looks like it erroneously puts `#version 300` in the shader instead of `#version 300 es`.

**Comment by Gamemulatorer** [comment]
![Screenshot_20201106-201032](https://user-images.githubusercontent.com/37603562/98365996-3dc8e700-206e-11eb-9ed1-b550122237fc.png)
![Screenshot_20201106-201044](https://user-images.githubusercontent.com/37603562/98366035-4d483000-206e-11eb-81fc-b5a80ddae8e5.png)
![Screenshot_20201106-201049](https://user-images.githubusercontent.com/37603562/98366083-5c2ee280-206e-11eb-91a1-3221f6e3d152.png)
![Screenshot_20201106-201128](https://user-images.githubusercontent.com/37603562/98366107-69e46800-206e-11eb-951d-0a1d4a6b3cfe.png)
![Screenshot_20201106-201144](https://user-images.githubusercontent.com/37603562/98366144-75d02a00-206e-11eb-9fff-054d83124bd0.png)

**Comment by hrydgard** [comment]
Yeah, don't need more screenshots, I know how to fix this.

**Comment by Gamemulatorer** [comment]
> Yeah, don't need more screenshots, I know how to fix this.

Sorry late upload because of poor internet 😅
