### ISSUE TITLE
PPSSPP Crashes when i minimize while playing some games.

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#13649]
### What happens?
when i tried to minimize PPSSPP while playing Outrun 2006, return to PPSSPP it crashes

### What *should* happen?
Other games doesn't crash for me.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Realme C2 Android 9 Pie and ppsspp-v1.10.3-1187-g5eea7435d

**Comment by Panderner** [comment]
[Record_2020-11-10-13-24-16_2f85358b2198d26f8aca533d68bee793.mp4.zip](https://github.com/hrydgard/ppsspp/files/5515000/Record_2020-11-10-13-24-16_2f85358b2198d26f8aca533d68bee793.mp4.zip)
Here's a video for crash.

**Comment by hrydgard** [comment]
That should take care of it, thanks for reporting!
