### ISSUE TITLE
Save states randomly cause graphical corruption

### ISSUE THREAD

**Issue by DanGLES3** [hrydgard/ppsspp#13644]
For almost a week now all builds have been causing random graphical corruptions after using savestates (from controllers disappearing, to the home screen being outright unrecognizable) it also causes the savestates themselves to have corrupted thumbnails (even in saves which do not trigger graphical corruption)

![ULUS10336_1.00_3.jpg](https://user-images.githubusercontent.com/32078304/98535497-f8bad580-2264-11eb-8102-71da3433a1ec.jpg)

![Screenshot_20201109-081746_PPSSPP.png](https://user-images.githubusercontent.com/32078304/98535131-5ac70b00-2264-11eb-8050-291da17891a1.png)

Device: Moto G5S Plus
PPSSPP 1.10.3-1174
Renderer: Vulkan

**Comment by DanGLES3** [comment]
After some quick testing this seems to only be affecting Final Fantasy Crisis Core

**Comment by DanGLES3** [comment]
Can also confirm that it is an Vulkan only issue as OpenGL doesn't generate corrupted savestate thumbnails

**Comment by hrydgard** [comment]
Weird!

Can you figure out exactly which build it starts at?

**Comment by DanGLES3** [comment]
> Weird!
> 
> Can you figure out exactly which build it starts at?

Can confirm the build where this issue begins is 1139

**Comment by hrydgard** [comment]
Thanks for reporting this and nailing down the commit! Easy fix thanks to your testing.
