### ISSUE TITLE
Tekken 6 blending issues after 1169 on Vulkan

### ISSUE THREAD

**Issue by Salman7236** [hrydgard/ppsspp#13650]
![Screenshot_20201110_165112_org ppsspp ppsspp](https://user-images.githubusercontent.com/64946014/98670838-22fbb880-2375-11eb-81df-285546fb4f0c.jpg)
![Screenshot_20201110_165108_org ppsspp ppsspp](https://user-images.githubusercontent.com/64946014/98670843-24c57c00-2375-11eb-8cca-3eaea900dc72.jpg)

**Comment by hrydgard** [comment]
what hardware? OpenGL or Vulkan? I guess that's Tekken 6?

**Comment by Salman7236** [comment]
> what hardware? OpenGL or Vulkan? I guess that's Tekken 6? Only on the fire level?

Vulkan. All levels.

**Comment by hrydgard** [comment]
Fixed
