### ISSUE TITLE
Save state issue after update to build 1196

### ISSUE THREAD

**Issue by Lemoncak3** [hrydgard/ppsspp#13658]
I tried with build 1196, whenever i load state and tried to save state the ppsspp force close. 
![Screenshot_20201112-175654](https://user-images.githubusercontent.com/67026697/98931384-88d07780-2510-11eb-9907-abff7c7b61b5.png)
![Screenshot_20201112-175704](https://user-images.githubusercontent.com/67026697/98931399-8e2dc200-2510-11eb-9592-e13822d3b6f4.png)
My save data is from around september 2020, have tried three games with same issue ( P3P, Digimon english patched, and growlanser)

**Comment by hrydgard** [comment]
What hardware? OpenGL, Vulkan or which backend?

**Comment by hrydgard** [comment]
Actually I can repro this very easily in a debug build on Windows.

This fails in __PsmfPlayerDoState:

		CoreTiming::RestoreRegisterEvent(eventPsmfPlayerStatusChange, "PsmfPlayerStatusChangeEvent", &__PsmfPlayerStatusChange);

since eventPsmfPlayerStatusChange is -1 in this case. Hm. These event restore things are so tricky...

**Comment by Lemoncak3** [comment]
I have tried your latest build 1202, but same problem still happening my P3P make ppsspp crashed after i load and save.

**Comment by sum2012** [comment]
I reproduce the problem,re-opening

**Comment by sum2012** [comment]
@hrydgard 
![1](https://user-images.githubusercontent.com/2177532/99163015-05489d80-273f-11eb-9ebc-ed9459b0c512.png)

**Comment by sum2012** [comment]
I fix it now

**Comment by sum2012** [comment]
@Lemoncak3 please check again in 
v1.10.3-1204-g486a82331 or newer.
