### ISSUE TITLE
Chinese font missing issue

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#13652]
I use World chinese patch of NeverlandNaruru Oukoku Monogatari for example

![1](https://user-images.githubusercontent.com/2177532/98684437-2147ea00-23a1-11eb-889b-89eb395c883f.png)

edit:wrong picture
![2](https://user-images.githubusercontent.com/2177532/98685830-d3cc7c80-23a2-11eb-9ce8-ea7c83b771e5.png)

Old version of jpn0.pgf  more support chinese font

@hrydgard this must solve in v1.10 otherwise chinese people (special using android) will use older version forever.

Do we detect lang using zh_CN.INI or zh_TW.ini use older version of jpn0.pgf ?
Or use eboot.* ? (This game use disc0:/PSP_GAME/SYSDIR/EBOOT.LEI )
Or detect using kernel function ?

**Comment by sum2012** [comment]
upload again bad picture
![2](https://user-images.githubusercontent.com/2177532/98686038-0fffdd00-23a3-11eb-8e7c-b43146ca1bae.png)

**Comment by sum2012** [comment]
@nassau-tk Can your jpn0.pgf add more support of chinese font ?

**Comment by hrydgard** [comment]
Yup, that would seem to be the problem...

**Comment by nassau-tk** [comment]
> @ nassau-tk jpn0.pgfで中国語フォントのサポートを追加できますか？

This is a heavy ploblem!
If add chinese font then I don't have converter for including Chinese. 

@hrydgard 
What kind of converter used "Old  jpn0.pgf"?
And,Do you have it?

**Comment by hrydgard** [comment]
I haven't touched that font stuff for many years, I don't remember :(

**Comment by sum2012** [comment]
First I need to list out games that must use current jpn0.pgf
GUNDAM VS GUNDAM NEXT PLUS (NPJH50107) 
Neon Genesis Evangelion 2 ULJS00064
@nassau-tk do you know must games ?

**Comment by nassau-tk** [comment]
@sum2012 

janne d'arc
Monster Hunter Seriese (MHP/MHP2/MHP2G/MHP3)
Assassin's Creed : Blood Line
QIX+
EXIT
Kangaeru EXIT (EXIT2)
Tantei Jinguji Saburo -Hai to Diamond- (maybe?)

I can  remember only these now.

I will try think about some way to solve font problems this week end.

By the way, How many chinese patched game is there?
Do you know?
It's many? or a little?

I want try hard to soleve the issue!!  :triumph:

**Comment by sum2012** [comment]
There are more 600 chinese patched games.
I may solve it by programly by temp method:
1: Default use older jpn0.pgf for PPSSPP 'S ui that choose chinese
2: For some games that must use current  jpn0.pgf

My chinese friend said that jpcsp emulator now use better chinese font.
Can you try it ? Thanks.

https://github.com/jpcsp/jpcsp/raw/ed2de4afb7e449b0bf0ebbc6da3e1dd9d6f473a3/flash0/font/jpn0.pgf

**Comment by nassau-tk** [comment]
@sum2012 

Is it a TTF?
If it's "Right" then please tell me it!

**Comment by sum2012** [comment]
It is SourceHanSans font.

**Comment by nassau-tk** [comment]
Thank you!
I will check & test later.

**Comment by nassau-tk** [comment]
@sum2012 

I was checked about Chinese font a few minutes.
I felt dizzy a little.:sweat_smile:
Please help me when Several questions may be done about Chinese.

**Comment by nassau-tk** [comment]
@sum2012 

If your friends knowing the application of "TTF to PGF Converter" then Please give me the application information.

**Comment by nassau-tk** [comment]
@hrydgard 
@sum2012 

And....Do you know how to use this PGF converter(?).?
https://github.com/tpunix/pgftool

If you know then please teach me....

**Comment by nassau-tk** [comment]
hm...report.
To be honest, an amateur is doing unreasonably.
But possibly? I have a chance...?
![image](https://user-images.githubusercontent.com/48179091/99160993-a4b26400-2730-11eb-987d-fced602d8917.png)

I installed "MinGW" and compile the PGF tool.
but, I could not compile all tool completely.

-1 Add Chinese Kanji Fonts to My Custom Japanese font.
-2 Convert by TTF2PGFJ.
-3 Mix "JPCSP's jpn0.pgf" and "My custom jpn0.pgf" by PGF Tool.

JPCSP's jpn0.pgf need for "Font code base".
I can't create a jpn0.pgf of "including chinese code".
So,I tested mix them.
I will try hard a little more.

@sum2012 
If you can test apperarlance chinese then download data below .
**Balance is not tuning yet.**
https://drive.google.com/file/d/1jCqCa6dz50K7pGyLahmYKG36R4sQoZyg/view?usp=sharing

**Comment by sum2012** [comment]
Sorry @nassau-tk 
Last week I need OT to work.
Your jpn0 seems work.Well done
![1](https://user-images.githubusercontent.com/2177532/99161405-f953e000-272c-11eb-8db0-f470955f23a4.jpg)

**Comment by nassau-tk** [comment]
If you have "Chinese patched Janne d'Arc" then please chekc it.
Becasue,that game can check the font appearlance.

**Comment by nassau-tk** [comment]
@hrydgard 
It's expected that it takes time for correction of the point of view of the font and the size.
So, Please consider whether it's returned to the previous data which didn't have much in haste and dissatisfaction.

**Comment by sum2012** [comment]
@nassau-tk 
![1](https://user-images.githubusercontent.com/2177532/99162016-5488d100-2733-11eb-82c3-ffc074f9c49b.jpg)

tag @lightfirst which is jpcsp 's font maker

**Comment by nassau-tk** [comment]
@sum2012 
Thank you!

**Comment by Panderner** [comment]
How about real PSP font for Chinese patched games?

**Comment by sum2012** [comment]
It should use gb3s1518.bwfon but jpcsp emulator is not full support

**Comment by nassau-tk** [comment]
ttf2pgfj.exe is only packing "Japanese JIS-Lv1 code".
If mix the 2 PGF(included Chinese & Only Japanese) by "[PGF Tool](https://github.com/tpunix/pgftool)" then appear the garbage on right side on some character.
Not good....

I want conver to including Chinese from TTF to PGF directly.

**Comment by sum2012** [comment]
Can use this one ?
https://www.freechinesefont.com/simplified-traditional-hanyi-senty-candy/
It support simplified and traditional chinese

**Comment by nassau-tk** [comment]
Is this a TTF?
Yes,Maybe can do it.
But,Why?

**Comment by sum2012** [comment]
https://www.sentyfont.com/index_htm_files/Hanyi%20Senty%20Candy-color.ttf

Becuase you said that you want to  including Chinese from TTF to PGF directly .This one is is ttf

**Comment by nassau-tk** [comment]
Oh,sorry.

The prblem is not TTF.
I got Chinese Kanji-characters already on my TTF file.
Problem is a my using converter.

Because, I am using a converter "ttf2pgfj".
ttf2pgf(J) is convert to jpn0.pgf & ltn0.pgf from some TTF.
But,It's convert only "Japanese JIS-Lv1" not include chinese code.
So, I must mix the my converted PGF & chinese base PGF(example old PPSSPP or JPCSP jpn0.pgf).

So,I want converter that can including the chinese.

I'm exploring in Github now.

**Comment by sum2012** [comment]
oh i see

**Comment by nassau-tk** [comment]
Um....

Only MHP3 is appear the garbage.

Janne d'Arc
EXIT
Evangelion2
Assassins Creed : BloodLine
And Maybe "WorldNeverLand"?
These games no Problem....Why?

**Comment by nassau-tk** [comment]
@sum2012 
@hrydgard 

A hasty report!
I have a good news!

I got PGF converter that helping by @tpunix .
And , I could make "Japanese & Chinese Mix PGF".
The converted PGF will not appear the garbage.
And,This font including 12,989 character of Kanji.
I think "Maybe,enough".
I think about this tool is good convert more than ttf2pgfj.

I think that I must tuning the base TTF a little.(Maybe,real little bit.)
https://drive.google.com/file/d/1MCpPquQ_gDMoMPSxEu19hGJhTqdg1ag0/view?usp=sharing
I uploaded the file on my GoogleDrive.

**[Japanese Hira-gana Sample.]**
![image](https://user-images.githubusercontent.com/48179091/99261088-96af3100-285f-11eb-8e94-f71d1cb9b314.png)

**[Kanji-sample of Include Chinese 簡体字.]**
![image](https://user-images.githubusercontent.com/48179091/99261165-afb7e200-285f-11eb-998a-b3aeb81b0e51.png)
![image](https://user-images.githubusercontent.com/48179091/99261539-3371ce80-2860-11eb-9fc6-8a0acf49794f.png)
![image](https://user-images.githubusercontent.com/48179091/99261611-4b495280-2860-11eb-878f-5d1002981643.png)

**Comment by sum2012** [comment]
Sorry, I don't know that that font don't support  traditional chinese (繁体字)
![1](https://user-images.githubusercontent.com/2177532/99264672-be9c9580-285b-11eb-9935-d15b39f7cc69.png)
Can you use this one instead ?
https://www.sentyfont.com/index_htm_files/Hanyi%20Senty%20Candy-color.ttf

**Comment by nassau-tk** [comment]
Please tell me!
簡体字
繁体字
Do you need both isn't it?

**Comment by sum2012** [comment]
Yes

在 2020年11月16日週一 下午11:51，nassau-tk <notifications@github.com> 寫道：

**Comment by nassau-tk** [comment]
OK!
I understand it!!
I try it!!
Please wait......!

**Comment by nassau-tk** [comment]
@sum2012 

Can you check?
https://drive.google.com/file/d/1rmBMlKewFKqQXoqyhbKNoU-8OJ1u7ml9/view?usp=sharing
(Sorry I will sleep....Good Night.)

**Comment by sum2012** [comment]
Same problem as
https://user-images.githubusercontent.com/2177532/99264672-be9c9580-285b-11eb-9935-d15b39f7cc69.png

It is missing "以" and "來"

**Comment by nassau-tk** [comment]
Um...
I see. I will retry to check.

**Comment by nassau-tk** [comment]
Um...
It characters seems including in font file.
And, It character appear on "Monster Hunter 3rd Guild Card editting".

![image](https://user-images.githubusercontent.com/48179091/99382889-80ad7900-2910-11eb-9b8d-af4eddbb283f.png)

![image](https://user-images.githubusercontent.com/48179091/99382846-755a4d80-2910-11eb-815a-efdfce40ac79.png)

![image](https://user-images.githubusercontent.com/48179091/99384613-07635580-2913-11eb-8227-fda1aa70b65d.png)

If you can try enter the "以" and "來" on MHP3 then please tell me the result.

**Comment by sum2012** [comment]
Sorry @nassau-tk 
Check my real psp , the font also have problem
https://ibb.co/t8PD92j
https://ibb.co/Wk8DTCK

**Comment by nassau-tk** [comment]
@sum2012 

Wao!
Is this a installed my font on your real PSP?!
Thank you for your testing.

And , I'm remaking the PGF from Zero.
But,It's not working correctly.

I'll report later.

**Comment by sum2012** [comment]
No,It is a original psp font
I don't know how to change real PSP Font
I am using 6.60  PRO-C2

**Comment by nassau-tk** [comment]
Oh!!
Is it said that it's a problem of Chinese patch?

I had seen the information which became changed to the Unicode font  after Ver.6.0 of original firmware.
Is it related this case???(An amateur idea.:smile:)

**Comment by nassau-tk** [comment]
@sum2012 

Please tell me about Chinese Patch.
And, Can you do below?

- Is it not official & not updated isn't it?
- Can you test MHP3 Guild Card Editting?
  If you can do it then enter the some Simplified & some Traditional chracters.
 Offcourse, You should test strange characters that appeared on the warning screen.

**Comment by nassau-tk** [comment]
@hrydgard 

Do you have any lnfo of Chinese patch?

**Comment by sum2012** [comment]
I don't know that how can see older history before this
https://github.com/hrydgard/ppsspp/commit/8d1ece05ca5d7de2e1926b8c7469a5d5f616c6b8#diff-50ce87ea76562d0c1c91b05e0f4b512b1ec437b8e1fefc43703f96548543d8db

I don't have MHP3 on hand

**Comment by nassau-tk** [comment]
@sum2012

OK! I see!

**Comment by leoxxx** [comment]
@sum2012 
https://github.com/hrydgard/ppsspp/issues/13510
Try this one.
It's convert from sarasa-mono-slab-sc-regular.tff.

**Comment by nassau-tk** [comment]
@leoxxx 

Thank you for your recomend.
If you know about this font then Please tell me about it.
Is this font inclueding simplified & traditional both?
And, What kind of font converter did you use?

**Comment by leoxxx** [comment]
https://github.com/be5invis/Sarasa-Gothic
CJK font. SC & TC  fonts are independent.
I just use the SC font to convert. Not test, may be SC font can display TC.
Covert by PSP FontMaker.

**Comment by sum2012** [comment]
@leoxxx can you upload a complied version of jpn0.pgf ?Thanks

**Comment by leoxxx** [comment]
I'm not a developer, can't compile the jpn0.pgf.
If you want the covert one, it's in https://github.com/hrydgard/ppsspp/issues/13510 the issue of the first comment.
https://github.com/hrydgard/ppsspp/files/5327744/jpn0.zip

**Comment by sum2012** [comment]
@leoxxx Your font is too large
![1](https://user-images.githubusercontent.com/2177532/99802387-9621dd80-2b72-11eb-8738-f3e5249e39f9.png)

**Comment by sum2012** [comment]
@nassau-tk You font 's size is right (But I cannot confirm again because you don't share the font now )
![2](https://user-images.githubusercontent.com/2177532/99802609-f284fd00-2b72-11eb-8fa7-4e69d0329b4c.png)

**Comment by leoxxx** [comment]
@sum2012
You can try other version Sarasa Gothic https://github.com/be5invis/Sarasa-Gothic or other font.
Convert it by PSP FontMaker.
你可以试试其它版本的更纱黑体，我只是用了其中的等宽简中版。或者你可以自己找其它字体。
然后用PSP FontMaker转换一下看看。

**Comment by leoxxx** [comment]
I think PPSSPP can give more jpn0.pgf to choose by gamers, when the game text display error.

**Comment by nassau-tk** [comment]
@sum2012 

My latest jpn0.pgf(Source-Hans-sans base) is below.
https://drive.google.com/file/d/1iW7Qe8eKuTVsk3-eG5JVvQC0F2KBN1lB/view?usp=sharing

I think about this font that maybe noproblem on any games.

And,I have begun to think that may be unrelated in an indication problem of the characters of the warning screen.

Please try below.

Please eliminate all font data from a FONT folder of PPSSPP.

Next Start the 真・三国無双6.

Maybe, Appear the warning screen.(Auto-save? Data load?)

So,Warning screen(Gray background=PSP System warning) is not use PGF isn't it?

Assassin's Creed:Blood Line is Original warning screen.
So,Appear the Invalid Memory Access Error.


@leoxxx 

um...
I don't think so about "Selectable font system".
Beacause,PSP font file is not "just a font".
It's because the game which doesn't move exists when there are no perfect original fonts (Or and it's equal.) like QIX++.
It can't be said that it's also right to include Chinese in jpn0.pgf by such meaning.:sweat_smile:

I think most important things that the chinese characters appear or not appear "in game".

**Comment by sum2012** [comment]
@nassau-tk You font is perfect for me.

**Comment by nassau-tk** [comment]
@sum2012 

OK!
I maked PL!

**Comment by Panderner** [comment]
Could you send me the screenshot of real PSP running World Neverland Chinese Patched?

**Comment by nassau-tk** [comment]
@sum2012 
@leoxxx 

The fixed font file was merged.
Maybe, It will coming update on latest git build.
Um...
I'm sleepy.... :sleepy:

**Comment by sum2012** [comment]
Thanks a lot

在 2020年11月23日週一 上午2:59，nassau-tk <notifications@github.com> 寫道：

**Comment by hrydgard** [comment]
Thanks all for the testing and reporting, and nassau-tk for the work creating the final fonts :) 

Time to close.
