### ISSUE TITLE
Phantasy Star Portable 2 Infinity (english patched) black screen with DX11

### ISSUE THREAD

**Issue by brujo5** [hrydgard/ppsspp#13653]
Phantasy Star Portable 2 Infinity (english patched) black screen with DX11. Just tested with DX9 and OpenGL and work fine. so the issue is related to DX11 only.

DX11
![Captura de pantalla (28)](https://user-images.githubusercontent.com/4172898/98714230-df3d8a80-2345-11eb-969d-a20a32a2c0c3.png)

DX9
![Captura de pantalla (29)](https://user-images.githubusercontent.com/4172898/98714403-11e78300-2346-11eb-9578-01baeff5fb8e.png)

OpenGL
![Captura de pantalla (30)](https://user-images.githubusercontent.com/4172898/98714571-48250280-2346-11eb-8738-43d1b5c60fc8.png)

log 
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/5519426/ppsspplog.zip)

ppsspp v1.10.3-1188-g0510101f6
windows 8.1 pro
intel hd
8gb ram
n2840

**Comment by Panderner** [comment]
@brujo5 Direct3D 11 works fine?

**Comment by brujo5** [comment]
@Panderner 
Yes, it works fine without problems.
