### ISSUE TITLE
D-Pad Inputs not registering correctly (Joycon / Nintendo Switch / Ubuntu)

### ISSUE THREAD

**Issue by sergioroprado** [hrydgard/ppsspp#13651]
### What happens?
On Settings/Control Maping, the D-Pad doesn't register the inputs correctly, e.g.: 
Dpad Up is detected as pad.Down, Dpad Down is detected as pad.Left, Dpad Left as pad.Right, and the Dpad Right isn't detected at all. The emulator simply doesn't detect anything when I press the Right Dpad on my controller.

### What *should* happen?
Detect the input when I press the right dpad

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Hardware: Nintendo Switch / Joycon controller
Operating system: L4T Ubuntu
PPSSPP version: 1.10.3-1186-g9f33a82b4

**Comment by hrydgard** [comment]
This is with the SDL build of PPSSPP, right? 

I assume we need a new line in assets/gamecontrollerdb.txt for these...

**Comment by sergioroprado** [comment]
@hrydgard After a lot of search, I was able to find the values to add to gamecontrollerdb.txt. Now everything works fine.

**Comment by sergioroprado** [comment]
I kinda new to GitHub, so i don't know if the procedure I did here is right

**Comment by hrydgard** [comment]
You did great. Closing this issue now!
