### ISSUE TITLE
[Mpeg][Freeze]v1.10.3-1207 has problem?

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#13662]
### What happens?
For example) Janne d'Arc Movie scene will frreze.(First Movie)
v1.10.3-1204 is not happen.

PPSSPP Ver.：1.10.3-1207
OS：Windows10（64-bit）Japanese
CPU：Ryzen7 3800X（8-core）
GPU：RADEON RX5700XT
Resolution：2560×1440
RAM：32GB

**Comment by Panderner** [comment]
Jeanne d'Arc affected this issue: it freezes at the first movie cutscene. 
The Last build worked is v1.10.3-1204-g486a82331
The issue started in v1.10.3-1207-ge01d53870
