### ISSUE TITLE
[OGL] Performance regression on Adreno

### ISSUE THREAD

**Issue by kage2051** [hrydgard/ppsspp#13668]
Since PR #13656, I have been experiencing a huge performance regression when using **any** resolution higher than 1x, especially in The 3rd Birthday where doing the 'overdive' technique (triangle button) makes the game run at around 12 FPS, only on GL backend though. Vulkan is unaffected by such issue.

I've tested this on two Adreno devices with 506 and 509 models and both are suffering from this.

**Comment by hrydgard** [comment]
Okay I can reproduce this, though I had to push resolutions higher on my Pixel 3a to see the difference. Still runs great on Vulkan though.

So, I'm mystified. If anything the change should have made things MORE similar to Vulkan, since we're now using the same method of "depal" (per-pixel color lookup) on both backends on ES 3.0 and higher.

Maybe I'll bump Adreno OpenGL back on the ES 2.0 path... The ES 3.0 path has a clear advantage in some games though like Sonic.

**Comment by kage2051** [comment]
The recent commit didn't solve the slowdown. There is something Adreno GPUs in general don't like.

**Comment by hrydgard** [comment]
Well, they seem to like it just fine when submitted through Vulkan instead of OpenGL :)  Since we're now using the same technique on both backends.

Anyway, like I said, I might either try to optimize the shader or go back to the old technique on Adreno for now...

**Comment by kage2051** [comment]
I'm thinking of a temporary workaround for that: implementing an option where the user can choose between GLESv2 and v3 context rendering (it should be named as 'accurate color lookup' or something), such option is only available if the GPU supports both contexts.

Redream and flycast implements a similar option, as 'per-strip' and 'per-pixel', obviously the latter is more demanding on mobile GPUs.

**Comment by hrydgard** [comment]
I've limited shader depal to 6xx level GPUs for now, until I can investigate the performance issue further.

**Comment by kage2051** [comment]
Yeah, it WAS the shader depal algorithm causing the white artifacts on the few builds prior to 1232.

Also I don't know if Adreno 610 should be excepted as well or not, since it's used on lower-end chipsets (SD460, 662 and 665) which are in fact rehashed variants of SD636/660 with a slightly better GPU.

**Comment by hrydgard** [comment]
The (rather complex) shader depal path is required for good performance in a few games like Sonic Rivals, so I had hoped we could use it universally, and as you have tested it does perform ok in Vulkan! But I guess OpenGL will have to stick to the old ways then.

**Comment by kage2051** [comment]
In my opinion, the 5xx line was one of their 'bad' generations of GPUs, just like 3xx and 4xx were. With the current 6xx line, they've learned from some of their competitors (Nvidia for example with their Tegra X1 chip) and are trying to reduce the gap between mobile and PC when it comes to balanced performance/quality ratio.

**Comment by Gamemulatorer** [comment]
OpenGL performance decrease also on Mali GPU see https://github.com/hrydgard/ppsspp/issues/11953

**Comment by Gamemulatorer** [comment]
Both opengl and vulkan has a good performance on my adreno 506.

OpenGL
![Screenshot_2022-09-14-05-35-40-66](https://user-images.githubusercontent.com/37603562/190013830-a574aa60-ee9f-44c9-b29a-407b75d08d96.png)

Vulkan
![Screenshot_2022-09-14-05-36-16-78](https://user-images.githubusercontent.com/37603562/190013863-b6586963-c72e-4fd5-baaa-54244e2833e1.png)

But vulkan is has too much brightness compare to opengl 🤔

**Comment by unknownbrackets** [comment]
Hm, Brave Story uses logic ops (INVERT) on that screen, may indicate logic ops are not working properly when simulated...

-[Unknown]

**Comment by unknownbrackets** [comment]
Added a hopefully simple workaround in #16024 by forcing hardware logic op support off on my PC.  I wonder why your GL supports them but not Vulkan... oh well.

-[Unknown]
