### ISSUE TITLE
Half of the game's opening logo is displayed

### ISSUE THREAD

**Issue by xiaolang0668** [hrydgard/ppsspp#13660]
The logo at the beginning of the game is not fully displayed. It is only normal to display the logo after opening the software rendering, but it is slower.
![20201115002748](https://user-images.githubusercontent.com/74450832/99151921-75243d00-26d9-11eb-98db-cfa989b9bb68.jpg)

![开场logo](https://user-images.githubusercontent.com/74450832/99151861-faf3b880-26d8-11eb-9247-ff4091c1d976.jpg)

**Comment by unknownbrackets** [comment]
Which game?  Do older versions/git builds work, such as v1.10.3?  If yes, what's the first version that stopped working?

If v1.10.3 works (it probably does), you can test in halves to narrow things down very quickly.  Since you have the game and reproduce the issue, you can do this pretty quickly.  Knowing which versions introduced this problem would make it a lot faster to fix.

-[Unknown]

**Comment by xiaolang0668** [comment]
![没有勾上之前](https://user-images.githubusercontent.com/74450832/99152266-b1589d00-26db-11eb-9b8a-e8c5267c3b6f.jpg)

![勾上后的结果](https://user-images.githubusercontent.com/74450832/99152313-072d4500-26dc-11eb-8cc8-774082f69270.jpg)
Look at the results of the above figure

**Comment by xiaolang0668** [comment]
Like other games, the opening display problem.

**Comment by Panderner** [comment]
@xiaolang0668 last build worked

**Comment by xiaolang0668** [comment]
Stable version did not appear such a problem, unfortunately stable version of some games can not be online

**Comment by xiaolang0668** [comment]
![1 10 3-634no problem](https://user-images.githubusercontent.com/74450832/99153007-8cb2f400-26e0-11eb-82a3-e014a7ef3c06.jpg)
![1 10 3-634](https://user-images.githubusercontent.com/74450832/99153014-989eb600-26e0-11eb-8b5e-26d7fac0b259.jpg)
1187 Incomplete display
634 The display is normal

**Comment by Panderner** [comment]
> ![1 10 3-634no problem](https://user-images.githubusercontent.com/74450832/99153007-8cb2f400-26e0-11eb-82a3-e014a7ef3c06.jpg)
> ![1 10 3-634](https://user-images.githubusercontent.com/74450832/99153014-989eb600-26e0-11eb-8b5e-26d7fac0b259.jpg)
> 1187 Incomplete display
> 634 The display is normal

could you investigate when the last build worked?

**Comment by xiaolang0668** [comment]
The problem is solved.
If you want to override the ppsspp simulator, set the（ ppsspp.ini ）Delete the file and let it regenerate to display the logo normally.

**Comment by hrydgard** [comment]
Hm. Sounds like some setting affects this.

**Comment by xiaolang0668** [comment]
> Hm. Sounds like some setting affects this.
Can the author make online rooms and add players to the service side of playing together?

**Comment by xiaolang0668** [comment]
> Hm. Sounds like some setting affects this.

Can the author make online rooms and add players to the service side of playing together?

**Comment by xiaolang0668** [comment]
> Hm. Sounds like some setting affects this.

![Tick this to cause](https://user-images.githubusercontent.com/74450832/99522500-b5810500-29d0-11eb-9d77-b974e76aebac.jpg)

![After removing the selection](https://user-images.githubusercontent.com/74450832/99522517-bade4f80-29d0-11eb-95d2-5758ce0b9d73.jpg)

The reason is the problem with this setting

**Comment by hrydgard** [comment]
Ah. That setting ("Lazy texture caching") is a bit of a speedhack, that can cause some artifacts like that. Keep it unchecked.

I'm considering removing it as in most games the speed improvement is very small.
