### ISSUE TITLE
LittleBigPlanet glitchy liquid textures

### ISSUE THREAD

**Issue by LuisFellp** [hrydgard/ppsspp#13664]
### What happens?
texture of liquids like lava are glitchy
https://youtu.be/JnVQ3D9-KpA
### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Exynos 7 Octa (7904), Android 10, v1.10.3-1204-g486a82331

**Comment by Panderner** [comment]
@LuisFellp Could you send me the screenshot from real hardware?

**Comment by LuisFellp** [comment]
> @LuisFellp Could you send me the screenshot from real hardware?

sorry but I don't own a psp

**Comment by hrydgard** [comment]
Yeah, that doesn't look right. Has it been like this for a long time or is it a new problem?

**Comment by LuisFellp** [comment]
the texture is fine in 1.10.3 from the ppsspp.org
![Screenshot_20201115-134834_PPSSPP](https://user-images.githubusercontent.com/33043774/99192412-1bf3f200-2749-11eb-9d3d-33808a54307d.png)

also, i noticed a strange line at loading screen
![Screenshot_20201115-134744_PPSSPP](https://user-images.githubusercontent.com/33043774/99192429-3201b280-2749-11eb-88b7-a8cca65b31df.png)

**Comment by LuisFellp** [comment]
v1.10.3-1204-g486a82331 have that strange line too

**Comment by hrydgard** [comment]
Could you try some builds in between 1.10.3 and current development build to figure out approximately when it broke?

**Comment by LuisFellp** [comment]
it starts between v1.10.3-910-g495fd9a13 and v1.10.3-912-g615e07ffc

**Comment by LuisFellp** [comment]
every version that ive tested above v1.10.3-912-g615e07ffc is broken

every version that ive tested below v1.10.3-910-g495fd9a13 works fine

**Comment by LuisFellp** [comment]
1.9.4 have that line too

**Comment by LuisFellp** [comment]
even 1.8.0 have that line
looks like it's an old bug

**Comment by hrydgard** [comment]
Seems this is the culprit, interesting: https://github.com/hrydgard/ppsspp/pull/13541

**Comment by hrydgard** [comment]
I think that might take care of it, please test when the builds are up.

**Comment by LuisFellp** [comment]
v1.10.3-1210-g90cc325b5 still having the same issue
![Screenshot_20201116-083312_PPSSPP](https://user-images.githubusercontent.com/33043774/99252993-4ba50780-27e6-11eb-86d8-182daf7167df.png)
![Screenshot_20201116-083325_PPSSPP](https://user-images.githubusercontent.com/33043774/99252997-4e076180-27e6-11eb-8805-83ead74eeb4c.png)

**Comment by hrydgard** [comment]
Thanks for testing, might just disable that optimization for now... Hm. Will think more about what it could be.

**Comment by hrydgard** [comment]
Alright, the renderpass merge optimization doesn't handle renderArea properly. I'll fix it.
