### ISSUE TITLE
Hajime no Ippo - character can't moving. (Android/Windows)

### ISSUE THREAD

**Issue by Saramagrean** [hrydgard/ppsspp#13671]
### What happens?
Hajime no Ippo -  character can't moving since v1.10.3-889-g291f17e27 (https://github.com/hrydgard/ppsspp/pull/13526).
![Ippo](https://user-images.githubusercontent.com/26355472/99414093-0d643100-2929-11eb-902c-a6f30ebfaec7.png)

### What *should* happen?
character can moving. :)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
happen on both Android/Windows.

**Comment by hrydgard** [comment]
Oh no, those instructions just keep on giving ...

**Comment by Saramagrean** [comment]
Okay, build v1.10.3-1245+ fixed. :)
![Ippo1](https://user-images.githubusercontent.com/26355472/100099308-d5616e80-2e91-11eb-9af3-c62a2c73ce19.png)
