### ISSUE TITLE
Black Screen On MHP3rd (English Patched)

### ISSUE THREAD

**Issue by Chriszxz** [hrydgard/ppsspp#13672]
# **What happened?**
Crash, black screen, or 0fps in loading screen (depends on the mission)

![Screenshot_2020-11-17-23-02-41-52](https://user-images.githubusercontent.com/68521956/99415812-2a056680-2933-11eb-9a83-be7688a3a212.png)

I think the last time it work was between 1.10.3-200-ish

# **What should happen?**
Must be able to load mission without crashing

# **What hardware, operating sytem, and PPSSPP version?**
Oppo A37
Qualcomm MSM8916 Snapdragon 410
Adreno 306
Android 5.1 (ColorOS 3)

**Comment by LunaMoo** [comment]
Just FYI: Pauth files are no longer needed.

AFAIK: This game pretty commonly crashes when you abuse savestates simulating never restarting psp.

**Comment by Chriszxz** [comment]
Even if non hd version?

**Comment by Chriszxz** [comment]
I'm not using savestate btw

**Comment by Chriszxz** [comment]
FYI: I know the limitation of savestates. I know when or not to savestate. Just saying

**Comment by Chriszxz** [comment]
I'm not just a normie playing ppsspp.

**Comment by Chriszxz** [comment]
It's a real issue on my perspective.

**Comment by Chriszxz** [comment]
> Just FYI: Pauth files are no longer needed.
> 
> AFAIK: This game pretty commonly crashes when you abuse savestates simulating never restarting psp.

I know what you are saying btw

**Comment by Chriszxz** [comment]
Are you happy now? 🙂

**Comment by Chriszxz** [comment]
Just to clarify things. I restarted my ppsspp before trying it again. No savestates. A clean startup.

**Comment by Chriszxz** [comment]
[recording.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/5555519/recording.ppdmp.zip)
Here's the dump if it would help.

**Comment by Chriszxz** [comment]
What else do I need to submit. I'm willing to comply.

**Comment by hrydgard** [comment]
If you can get ADB logs, there might be something useful there, but not super likely. I don't think there's anymore to submit, but there's not much to go on here... Does this game work for others, on other hardware, or does it crash for everyone?

**Comment by Chriszxz** [comment]
I think the problem was the phone's hardware. I'm also using Realme C2 and it worked fine.

**Comment by Chriszxz** [comment]
[logcat.txt](https://github.com/hrydgard/ppsspp/files/5555845/logcat.txt)
Here's the logs @hrydgard

**Comment by Chriszxz** [comment]
[demo.zip](https://github.com/hrydgard/ppsspp/files/5555849/demo.zip)
Here's a sample video.

**Comment by hrydgard** [comment]
OK so this does look very suspicious, like your ISO file is corrupted:

```
E/PPSSPP  (10815): [FILESYS] Could not read 4096 bytes from block
E/PPSSPP  (10815): [FILESYS] Could not read 8192 bytes from block
E/PPSSPP  (10815): [FILESYS] Could not read 131072 bytes from block
E/PPSSPP  (10815): [FILESYS] Could not read 131072 bytes from block
E/PPSSPP  (10815): [FILESYS] Could not read 131072 bytes from block
E/PPSSPP  (10815): [FILESYS] Could not read 131072 bytes from block
E/PPSSPP  (10815): [FILESYS] Could not read 131072 bytes from block
E/PPSSPP  (10815): [FILESYS] Could not read 131072 bytes from block
E/PPSSPP  (10815): [FILESYS] Could not read 131072 bytes from block
E/PPSSPP  (10815): [FILESYS] Could not read 131072 bytes from block
E/PPSSPP  (10815): [FILESYS] Could not read 131072 bytes from block
E/PPSSPP  (10815): [FILESYS] Could not read 71680 bytes from block
E/PPSSPP  (10815): [FILESYS] Could not read 10240 bytes from block
E/PPSSPP  (10815): [FILESYS] Could not read 6144 bytes from block
E/PPSSPP  (10815): [FILESYS] Could not read 71680 bytes from block
E/PPSSPP  (10815): [FILESYS] Could not read 4096 bytes from block
E/PPSSPP  (10815): [FILESYS] Could not read 14336 bytes from block
E/PPSSPP  (10815): [FILESYS] Could not read 28672 bytes from block
E/PPSSPP  (10815): [FILESYS] Could not read 16384 bytes from block
E/PPSSPP  (10815): [FILESYS] Could not read 131072 bytes from block
E/PPSSPP  (10815): [FILESYS] Could not read 102400 bytes from block
E/PPSSPP  (10815): [FILESYS] Could not read 30720 bytes from block
E/PPSSPP  (10815): [FILESYS] Could not read 18432 bytes from block
E/PPSSPP  (10815): [FILESYS] Could not read 20480 bytes from block
E/PPSSPP  (10815): [FILESYS] Could not read 131072 bytes from block
E/PPSSPP  (10815): [FILESYS] Could not read 131072 bytes from block
E/PPSSPP  (10815): [FILESYS] Could not read 131072 bytes from block
E/PPSSPP  (10815): [FILESYS] Could not read 131072 bytes from block
E/PPSSPP  (10815): [FILESYS] Could not read 131072 bytes from block
E/PPSSPP  (10815): [FILESYS] Could not read 131072 bytes from block
E/PPSSPP  (10815): [FILESYS] Could not read 120832 bytes from block
E/PPSSPP  (10815): [FILESYS] Could not read 24576 bytes from block
E/PPSSPP  (10815): [FILESYS] Could not read 24576 bytes from block
W/PPSSPP  (10815): [MEMMAP] Read Word: Invalid address 00000034 PC 09c86ed8 LR 088f5b5c (block 7136 at 0889c0ec)
W/PPSSPP  (10815): 007f5cb5f1ac ldr w22, [x21, #52]
W/PPSSPP  (10815): 
E/PPSSPP  (10815): [MEMMAP] Bad memory access detected! 00000034 (0x7e00000034) Stopping emulation. Info:
E/PPSSPP  (10815): (block 7136 at 0889c0ec)
E/PPSSPP  (10815): 007f5cb5f1ac ldr w22, [x21, #52]
E/PPSSPP  (10815): 
```

**Comment by Chriszxz** [comment]
It worked now. Seems like it's the iso's fault then. I'm closing this now
