### ISSUE TITLE
Failed graphics backends: VULKAN,OPENGL

### ISSUE THREAD

**Issue by clondy999** [hrydgard/ppsspp#13674]
It's a really cool project.

I am trying to compile this project to my device.

Now that the compilation is successful, there is a problem and I don't know how to solve it.

Error message:
root@odroid:~/ppsspp/build# ./PPSSPPSDL 
VulkanMayBeAvailable: Device allowed ('SDL:Linux')
VulkanMayBeAvailable: Library loaded ('libvulkan.so')
VulkanMayBeAvailable: Enumerating instance extensions
VulkanMayBeAvailable: Instance extension count: 18
VulkanMaybeAvailable: Instance extension found: VK_KHR_device_group_creation (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_external_fence_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_external_memory_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_external_semaphore_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_get_display_properties2 (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_get_physical_device_properties2 (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_get_surface_capabilities2 (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_surface (00000019)
VulkanMaybeAvailable: Instance extension found: VK_KHR_surface_protected_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_wayland_surface (00000006)
VulkanMaybeAvailable: Instance extension found: VK_KHR_xcb_surface (00000006)
VulkanMaybeAvailable: Instance extension found: VK_KHR_xlib_surface (00000006)
VulkanMaybeAvailable: Instance extension found: VK_KHR_display (00000017)
VulkanMaybeAvailable: Instance extension found: VK_EXT_direct_mode_display (00000001)
VulkanMaybeAvailable: Instance extension found: VK_EXT_acquire_xlib_display (00000001)
VulkanMaybeAvailable: Instance extension found: VK_EXT_display_surface_counter (00000001)
VulkanMaybeAvailable: Instance extension found: VK_EXT_debug_report (00000009)
VulkanMaybeAvailable: Instance extension found: VK_EXT_debug_utils (00000001)
VulkanMayBeAvailable: Calling vkCreateInstance
VulkanMayBeAvailable: Vulkan test instance created successfully.
VulkanMayBeAvailable: Failed to count physical devices (VK_ERROR_INITIALIZATION_FAILED)
VulkanMayBeAvailable: Destroying instance
DEBUG: Vulkan is not available, not using Vulkan.
Info: We compiled against SDL version 2.0.10 and we are linking against SDL version 2.0.10. :)
40:40:623 Core/Config.cpp:540 I[G3D]: Longest display side: -1 pixels. Choosing scale 1
40:40:657 UI/NativeApp.cpp:403 E[LOADER]: Failed graphics backends: VULKAN,OPENGL
40:40:658 Core/Config.cpp:622 E[LOADER]: Graphics backend failed for 0, trying another
40:40:658 Core/Config.cpp:647 E[LOADER]: All graphics backends failed
Pixels: 960 x 544
Virtual pixels: 960 x 544
SDL_CreateWindow failed for GL 4.6: SDL not configured with OpenGL/GLX support
SDL_CreateWindow failed for GL 4.5: SDL not configured with OpenGL/GLX support
SDL_CreateWindow failed for GL 4.4: SDL not configured with OpenGL/GLX support
SDL_CreateWindow failed for GL 4.3: SDL not configured with OpenGL/GLX support
SDL_CreateWindow failed for GL 4.2: SDL not configured with OpenGL/GLX support
SDL_CreateWindow failed for GL 4.1: SDL not configured with OpenGL/GLX support
SDL_CreateWindow failed for GL 4.0: SDL not configured with OpenGL/GLX support
SDL_CreateWindow failed for GL 3.3: SDL not configured with OpenGL/GLX support
SDL_CreateWindow failed for GL 3.2: SDL not configured with OpenGL/GLX support
SDL_CreateWindow failed for GL 3.1: SDL not configured with OpenGL/GLX support
SDL_CreateWindow failed for GL 3.0: SDL not configured with OpenGL/GLX support
NativeShutdown called
SDL_CreateWindow failed: SDL not configured with OpenGL/GLX support
GL init error ''
SDL: Trying a different audio device
Failed to open audio device: Audio subsystem is not initialized
loading control pad mappings from gamecontrollerdb.txt: SUCCESS!

My equipment:
ODROID C4

Equipment environment:
ubuntu Arm64

**Comment by unknownbrackets** [comment]
What compile flags did you use?

I think you might need to use USING_GLES.

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]

**Comment by gearcoded** [comment]
I had the same issue, but it was resolved after I updated system packages (even without a reboot).
