### ISSUE TITLE
Change Microphone test to the correct category

### ISSUE THREAD

**Issue by ppmeis** [hrydgard/ppsspp#13685]
https://github.com/hrydgard/ppsspp/blob/ff1b2fb8b804fbd9e304c0c6e1da6d1c4b839d4c/UI/GameSettingsScreen.cpp#L629

It affects also line 630

audioSettings->Add(new ItemHeader(gr->T("Microphone")));
		PopupMultiChoiceDynamic *MicChoice = audioSettings->Add(new PopupMultiChoiceDynamic(&g_Config.sMicDevice, gr->T("Microphone Device"), micList, nullptr, screenManager()));

changes "gr" to "a" to move translation line to the correct category:

audioSettings->Add(new ItemHeader(a->T("Microphone")));
		PopupMultiChoiceDynamic *MicChoice = audioSettings->Add(new PopupMultiChoiceDynamic(&g_Config.sMicDevice, a->T("Microphone Device"), micList, nullptr, screenManager()));

**Comment by hrydgard** [comment]
Fixed.
