### ISSUE TITLE
Make line 843 translatable

### ISSUE THREAD

**Issue by ppmeis** [hrydgard/ppsspp#13686]
https://github.com/hrydgard/ppsspp/blob/ff1b2fb8b804fbd9e304c0c6e1da6d1c4b839d4c/UI/GameSettingsScreen.cpp#L843

networkingSettings->Add(new ItemHeader(n->T("Misc (default = compatiblity)")));

I think it shoud be:

networkingSettings->Add(new ItemHeader(n->T("Misc", "Misc (default = compatiblity)")));

**Comment by hrydgard** [comment]
Thanks, fixed.
