### ISSUE TITLE
Make line 784 translatable

### ISSUE THREAD

**Issue by ppmeis** [hrydgard/ppsspp#13687]
https://github.com/hrydgard/ppsspp/blob/ff1b2fb8b804fbd9e304c0c6e1da6d1c4b839d4c/UI/GameSettingsScreen.cpp#L784

networkingSettings->Add(new ChoiceWithValueDisplay(&g_Config.proAdhocServer, n->T("Change proAdhocServer Address (localhost = multiple instance)"), (const char*)nullptr))->OnClick.Handle(this, &GameSettingsScreen::OnChangeproAdhocServerAddress);

I think it should be:

networkingSettings->Add(new ChoiceWithValueDisplay(&g_Config.proAdhocServer, n->T("Change proAdhocServer Address", "Change proAdhocServer Address (localhost = multiple instance)"), (const char*)nullptr))->OnClick.Handle(this, &GameSettingsScreen::OnChangeproAdhocServerAddress);

**Comment by hrydgard** [comment]
Thanks, fixed.
