### ISSUE TITLE
Disable on screen messages

### ISSUE THREAD

**Issue by fefo-dev** [hrydgard/ppsspp#13682]
Found no way to disable on-screen messages, such as from folder/filename after a capture or state saved/loaded when using savestates. Is there any?

Thanks.

**Comment by Panderner** [comment]
Screenshot?

**Comment by fefo-dev** [comment]
https://images2.imgbox.com/af/38/q7aRMYL8_o.jpg
Taken with PPSSPP after creating a save state. Doing so displayed a second message with the full adress of the screenshot location. As shown it can be an annoyance while capturing stuff.

**Comment by hrydgard** [comment]
I see, yeah. Ideally I guess we could hide those messages on the frame of the screen capture (or take the capture before they are drawn)...

**Comment by fefo-dev** [comment]
Dunno about the internal recording, but my request came after trying to record gameplay (with external tools) for further editing. In my head I could use savestates to segment it and add the "branch" I want latter without showing any disruption, but the messages got in the way. Then I remembered that other emulators thath do the same often let you disable it in a menu toogle or config.ini edit.

A limited workaround I found was to remove the line from whatever locale I'm using, but savestates still show its enumerator. Screenshots have no prefix/suffix, so no fix here.

**Comment by hrydgard** [comment]
I see.

I think I'm just gonna make a toggle that hides them entirely. Maybe stick it in Developer Tools in the settings initially.

**Comment by fefo-dev** [comment]
Thanks for the crazy fast support @hrydgard, I was legit scared! Working just as expected.

**Comment by MiguelCardonaG** [comment]
I think this option should be extended, that is, that the user should be able to choose which messages they do not want to see or whether to see. Because now if it is activated all messages are hidden on the screen and I think there should be some options that you want to hide or not.

What do you think?

**Comment by hrydgard** [comment]
That's definitely something to think about. Please file a new issue, proposing some of the options you would want it to be split into.

**Comment by MiguelCardonaG** [comment]
> That's definitely something to think about. Please file a new issue, proposing some of the options you would want it to be split into.

Is there a list of all messages on the screen of problems or no problem?
