### ISSUE TITLE
[Featuer Request] A choice point is memorized in "Game List".

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#13699]
### What happens?
Large capacity device and low-price Memory card are the mainstream recently.
So,A lot of users are carring around many games on self device.

So, I have a suggestion.
If choose a game In the "Game List" then the game will start.
And, If you finish and back to the "Game List" then the "top of the game list" will appear.
I think at point of here.

I think about that the "Game List" should memory the "last choosen point."
"Recentry"?
um... It's not same meaning.
Different approach to userbility?I think.

**Comment by iota97** [comment]
Doesn't Recent tab already does this? It sort the game by most recently used.

**Comment by hrydgard** [comment]
It's a reasonable idea, though yeah, if you just wanna play the last game you played, the Recent tab does that for you.

**Comment by nassau-tk** [comment]
Yes, Exactly.
But, I said about "play style".
Recently is just Recently.

Maybe,Many "Old games fun" want play "Game of a memory".
So, They will play "seriese of favorite games".
Like a this....
Play FinalFantasy 1 a few minutes and play FinalFantasy 2 a few minutes and play FinalFantasy 3 a fewminutes.
It's troublesome to look for a series again from a top line one by one at such time.
It was mounted on several emulators and was comfortable using something I need, so I proposed.
Offcourse, this one is a example & just propose.

**Comment by nassau-tk** [comment]
I think this idea doesn't compete with Recently.

**Comment by iota97** [comment]
So you want Game list to remember the scroll position right?

**Comment by nassau-tk** [comment]
Yes! That's right!

**Comment by nassau-tk** [comment]
Wao!
Really?!
I'm surprised that so quick your work.

**Comment by hrydgard** [comment]
iotas's work, not mine :)

**Comment by nassau-tk** [comment]
> iota97's work, not mine :)

Yes, I know!!
Great.

**Comment by nassau-tk** [comment]
Report!

If closed PPSSPP by task kill on Android then PPSSPP select the root directry of storage at next boot. 

When in game & menu  screen both.

**Comment by hrydgard** [comment]
Is that new with this commit fix? Otherwise please create a new issue :)

**Comment by nassau-tk** [comment]
Oh!

Sorry!
I will create new issue!
