### ISSUE TITLE
Add xbox series s/x support

### ISSUE THREAD

**Issue by abasgames** [hrydgard/ppsspp#13692]
### What happens?
Xbox series s/x just got dev mode allow for UWP apps to loaded

### What *should* happen?
We should have ppsspp port for the new xbox platform

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Xbox new series and operating system is sandbox version of windows i guess

**Comment by hrydgard** [comment]
Shouldn't the existing UWP port already work?

(Though, it currently has some bad audio issues unfortunately)

**Comment by MojoJojoDojo** [comment]
it actually should work with the existing UWP port I think.
That's how it works with Retroarch UWP.
