### ISSUE TITLE
(Libretro) No rule to make target '../GPU/Directx9/VertexShaderGeneratorHLSL.o'

### ISSUE THREAD

**Issue by bslenul** [hrydgard/ppsspp#13696]
Hey!

Build fails for Libretro core: http://paste.libretro.com/219048

> make: *** No rule to make target '../GPU/Directx9/VertexShaderGeneratorHLSL.o', needed by 'ppsspp_libretro.dll'.  Stop.

This file doesn't exist anymore, I got the core to compile by removing it from libretro/Makefile.common:
```diff
diff --git a/libretro/Makefile.common b/libretro/Makefile.common
index 2fb57db46..c14fde255 100644
--- a/libretro/Makefile.common
+++ b/libretro/Makefile.common
@@ -670,8 +670,7 @@ SOURCES_CXX += \
        $(GPUDIR)/Directx9/StateMappingDX9.cpp \
        $(GPUDIR)/Directx9/StencilBufferDX9.cpp \
        $(GPUDIR)/Directx9/TextureCacheDX9.cpp \
-       $(GPUDIR)/Directx9/TextureScalerDX9.cpp \
-       $(GPUDIR)/Directx9/VertexShaderGeneratorHLSL.cpp
+       $(GPUDIR)/Directx9/TextureScalerDX9.cpp

 SOURCES_CXX += \
        $(GPUDIR)/D3D11/DepalettizeShaderD3D11.cpp \
```
But I'm not a dev, I have no clue if it can break anything, if it needs to be replaced by something else, etc... So it would be nice if someone who actually knows what he's doing could make a proper PR :p 

Because of this, PPSSPP core available is from November 3rd and some games are broken with this version (The Warriors for example #13595).

**Comment by hrydgard** [comment]
Apologies! That's absolutely a correct fix, I'll commit it.

**Comment by bslenul** [comment]
Wow that was quick, thank you so much! 👍
