### ISSUE TITLE
Accel World vs. Sword Art Online: Millennium Twilight can't open the .APK files!!! HELP!!!

### ISSUE THREAD

**Issue by QBASpriteFinder** [hrydgard/ppsspp#13693]
No matter what I seem to do I can't seem to open the .APK files in this game! Is there any to extract the .APK file from this game so that I can get the 2D Sprites!?

**Comment by Panderner** [comment]
It's not a PSP game @QBASpriteFinder. . APK files is only for installing android apps not PSP games.
Closing this for off-topic.
