### ISSUE TITLE
PSPo2 and PSPo2I blackscreen after intro

### ISSUE THREAD

**Issue by CrimsonSZ-Q** [hrydgard/ppsspp#13707]
### What happens?
I tested on new version, 1.7, 1.7.4, 1.2.2, and 1.3 
I got blackscreen on Phantasy Star Portable 2 and Phantasy Star Portable 2 Infinity after intro
My device info :
DROID INFO REPORT

DEVICE
Model: RMX1941 (RMX1941)
Manufacturer: Realme
Baseband Version: M_V3_P10,M_V3_P10
RIL Version: android reference-ril 1.0
Build Number: RMX1941EX_11_A.29
Build Fingerprint: Realme/RMX1941/RMX1941:9/PPR1.180610.011/1597734015:user/release-keys
Bootloader: unknown
Java VM: ART 2.1.0
OS Version: P (9)
SDK: 28

DISPLAY
Resolution: 720x1560 pixels
Software Density: 320 dpi (xhdpi)
Refresh Rate: 59.79 Hz

PROCESSOR
CPU Architecture: AArch64 Processor rev 4 (aarch64)
Board: RM6762_18540
Chipset: MT6762V/WR
Cores: 8
Clock Speed: 2001 MHz - 2001 MHz
Instruction Sets: arm64-v8a
CPU Features: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU Governor: Not Available
Kernel Version: 4.9.117+
Kernel Architecture: aarch64

GRAPHICS
Renderer: PowerVR Rogue GE8320
Vendor: Imagination Technologies
OpenGL Version: OpenGL ES 3.2

RAM
Total: 2818 MB
Java Heap: 256 MB

STORAGE
Internal: 23 GB
External: 29.7 GB

PRIMARY CAMERA
Resolution: 13 MP
Flash: Yes
Video Resolution: Full HD, 1920x1080
Supported Resolutions: 
    Image:
    4160x3120
    4096x2304
    4160x1920
    3120x3120
    3264x2448
    3840x2160
    2560x1920
    1920x1088
    1920x1080
    1560x720
    1280x720
    960x720
    720x720
    720x480
    640x480
    352x288
    320x240
    176x144

    Video:
    1920x1080 (Full HD)
    960x540 (qHD)
    1560x720
    1280x720 (HD)
    960x720
    720x720
    720x480
    720x336
    640x480 (VGA)
    352x288
    320x240
    176x144

SECONDARY CAMERA
Resolution: 5 MP
Video Resolution: qHD, 960x540
Supported Resolutions: 
    Image:
    2592x1944
    1944x1944
    2592x1200
    2560x1920
    1920x1088
    960x540
    1560x720
    1280x720
    960x720
    720x720
    640x480
    320x240

    Video:
    960x540 (qHD)
    1920x1080 (Full HD)
    1560x720
    1280x720 (HD)
    960x720
    720x720
    720x480
    640x480 (VGA)
    352x288
    320x240
    176x144

FEATURES
Bluetooth: Yes
Bluetooth LE: Yes
GPS: Yes
NFC: No
USB Accessory: Yes
WiFi: Yes
WiFi Direct: Yes

BATTERY
Technology: Li-ion
Health: Good

SENSORS
ACCELEROMETER
MAGNETOMETER
ORIENTATION
GYROSCOPE
LIGHT
PROXIMITY
GRAVITY
LINEARACCEL
ROTATION_VECTOR
UNCALI_MAG
GAME_ROTATION_VECTOR
SIGNIFICANT_MOTION
STEP_DETECTOR
STEP_COUNTER
GEOMAGNETIC_ROTATION_VECTOR
TILT_DETECTOR
WAKE_GESTURE
GLANCE_GESTURE
PICK_UP
DEVICE_ORIENTATION
STATIONARY_DETECT
MOTION_DETECT
STEP_DETECTOR_WAKEUP

Created by Droid Info

**Comment by Panderner** [comment]
Maybe your ISO is corrupted.

**Comment by Panderner** [comment]
or duplicate of #13680

**Comment by Chriszxz** [comment]
You don't need to give the full specs. Gpu and cpu are enough.

**Comment by Chriszxz** [comment]
PPSSPP logs would help.

**Comment by CrimsonSZ-Q** [comment]
> Maybe your ISO is corrupted.

I copy the ISO to my PC, and it run well without any issues

**Comment by CrimsonSZ-Q** [comment]
> You don't need to give the full specs. Gpu and cpu are enough.

Sorry lmao

**Comment by Chriszxz** [comment]
Can you send the logs?

**Comment by CrimsonSZ-Q** [comment]
> Can you send the logs?

How to get the log ?

**Comment by Chriszxz** [comment]
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump
There is a console below when frame dumping and that's the logs of ppsspp just copy it and it's done.

**Comment by CrimsonSZ-Q** [comment]
> https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump
> There is a console below when frame dumping and that's the logs of ppsspp just copy it and it's done.


Debugger connected
38:48:686 root         N[G3D]: GLES/ShaderManagerGLES.cpp:899 Precompiling the shader cache from '/data/user/0/org.ppsspp.ppssppgold/cache/ULUS10529.glshadercache'
38:48:687 root         N[G3D]: GLES/ShaderManagerGLES.cpp:980 Precompile: Compiled and linked 4 programs (4 vertex, 4 fragment) in 1.2 milliseconds
38:48:687 root         N[BOOT]: UI/EmuScreen.cpp:299 Loading /storage/F87A-BCEF/PSP/Phantasy_Star_Portable_2_USA_PSP-pSyPSP.iso...
38:49:472 user_main    E[SCEKERNEL]: HLE/sceKernel.cpp:681 UNIMPL sceKernelReferGlobalProfiler(deadbeef)
38:49:882 fio_th       E[SCEIO]: HLE/sceIo.cpp:1487 80010002=sceIoOpen(disc0:/sce_lbn0x32d00_size0x36930800, 00000001, 000001ff)
38:50:056 fio_th       E[SCEIO]: HLE/sceIo.cpp:1487 80010002=sceIoOpen(disc0:/sce_lbn0x32d00_size0x36930800, 00000001, 000001ff)
38:50:096 fio_th       E[SCEIO]: HLE/sceIo.cpp:1487 80010002=sceIoOpen(disc0:/sce_lbn0x32d00_size0x36930800, 00000001, 000001ff)
38:50:192 fio_th       E[SCEIO]: HLE/sceIo.cpp:1487 80010002=sceIoOpen(disc0:/sce_lbn0x32d00_size0x36930800, 00000001, 000001ff)
38:50:312 fio_th       E[SCEIO]: HLE/sceIo.cpp:1487 80010002=sceIoOpen(disc0:/sce_lbn0x32d00_size0x36930800, 00000001, 000001ff)
38:50:394 fio_th       E[SCEIO]: HLE/sceIo.cpp:1487 80010002=sceIoOpen(disc0:/sce_lbn0x32d00_size0x36930800, 00000001, 000001ff)
38:50:526 fio_th       E[SCEIO]: HLE/sceIo.cpp:1487 80010002=sceIoOpen(disc0:/sce_lbn0x32d00_size0x36930800, 00000001, 000001ff)
38:50:626 fio_th       E[SCEIO]: HLE/sceIo.cpp:1487 80010002=sceIoOpen(disc0:/sce_lbn0x32d00_size0x36930800, 00000001, 000001ff)
38:50:728 fio_th       E[SCEIO]: HLE/sceIo.cpp:1487 80010002=sceIoOpen(disc0:/sce_lbn0x32d00_size0x36930800, 00000001, 000001ff)
38:50:860 fio_th       E[SCEIO]: HLE/sceIo.cpp:1487 80010002=sceIoOpen(disc0:/sce_lbn0x32d00_size0x36930800, 00000001, 000001ff)
38:50:961 fio_th       E[SCEIO]: HLE/sceIo.cpp:1487 80010002=sceIoOpen(disc0:/sce_lbn0x32d00_size0x36930800, 00000001, 000001ff)
38:51:062 fio_th       E[SCEIO]: HLE/sceIo.cpp:1487 80010002=sceIoOpen(disc0:/sce_lbn0x32d00_size0x36930800, 00000001, 000001ff)
38:51:163 fio_th       E[SCEIO]: HLE/sceIo.cpp:1487 80010002=sceIoOpen(disc0:/sce_lbn0x32d00_size0x36930800, 00000001, 000001ff)
38:51:294 fio_th       E[SCEIO]: HLE/sceIo.cpp:1487 80010002=sceIoOpen(disc0:/sce_lbn0x32d00_size0x36930800, 00000001, 000001ff)
38:51:395 fio_th       E[SCEIO]: HLE/sceIo.cpp:1487 80010002=sceIoOpen(disc0:/sce_lbn0x32d00_size0x36930800, 00000001, 000001ff)
38:51:496 fio_th       E[SCEIO]: HLE/sceIo.cpp:1487 80010002=sceIoOpen(disc0:/sce_lbn0x32d00_size0x36930800, 00000001, 000001ff)
38:51:627 fio_th       E[SCEIO]: HLE/sceIo.cpp:1487 80010002=sceIoOpen(disc0:/sce_lbn0x32d00_size0x36930800, 00000001, 000001ff)
38:51:728 fio_th       E[SCEIO]: HLE/sceIo.cpp:1487 80010002=sceIoOpen(disc0:/sce_lbn0x32d00_size0x36930800, 00000001, 000001ff)
38:51:829 fio_th       E[SCEIO]: HLE/sceIo.cpp:1487 80010002=sceIoOpen(disc0:/sce_lbn0x32d00_size0x36930800, 00000001, 000001ff)

**Comment by Chriszxz** [comment]
Are you using the latest build when it happened?

**Comment by Chriszxz** [comment]
https://buildbot.orphis.net/ppsspp/index.php?m=dl&rev=v1.10.3-1218-g1e5e0e20d&platform=android
This is the current build i'm using.

**Comment by Chriszxz** [comment]
So I tried using the latest build and it also worked. Did you check the hash of your iso?

**Comment by CrimsonSZ-Q** [comment]
I already use the latest version and hasn't changed at all :'(

PSPo2I (eng patch) SHA-256 checksum : 97e46b370ae99a291b9999601f3199e5820575dbd88beaf031d76d3455057316

PSPo2 USA SHA-256 checksum : 46c68dc831c5357044e336fb4065da5d6a1bd835d61bd03faade46012ac60d58

Calculate with hash droid

**Comment by Panderner** [comment]
Works fine for me running on Realme C2. @CrimsonSZ-Q maybe your ISO is likely to be corrupted.

**Comment by CrimsonSZ-Q** [comment]
> Works fine for me running on Realme C2. @CrimsonSZ-Q maybe your ISO is likely to be corrupted.

if my ISO is corrupt, why when I copy it to PC, it can be played

**Comment by Panderner** [comment]
> > Works fine for me running on Realme C2. @CrimsonSZ-Q maybe your ISO is likely to be corrupted.
> 
> if my ISO is corrupt, why when I copy it to PC, it can be played

are you using internal storage or SD Card?

**Comment by CrimsonSZ-Q** [comment]
> > > Works fine for me running on Realme C2. @CrimsonSZ-Q maybe your ISO is likely to be corrupted.
> > 
> > 
> > if my ISO is corrupt, why when I copy it to PC, it can be played
> 
> are you using internal storage or SD Card?

Sd Card

**Comment by CrimsonSZ-Q** [comment]
After I use V.1.8 and clean some file in my internal storage, the game is no longer blackscreen, thank you all
