### ISSUE TITLE
Cho Aniki Zero hangs on loading again

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#13705]
Test using v1.10.3-1234-g16e54c630-windows-amd64

can't load since v1.10.3-889-g291f17e27 (#13526).

similar #13671

**Comment by hrydgard** [comment]
Okay, seems I'm gonna have to revert that again, or make a game specific version of the functions.

Will at some point try to reverse engineer these in detail but it will not be easy.

**Comment by sum2012** [comment]
Can we use round method ?
etc 0.006 = 0.01 , 0.3001 = 0.3

**Comment by hrydgard** [comment]
seems whatever we do, some game has a problem with it...

**Comment by sum2012** [comment]
https://github.com/sum2012/ppsspp/commit/61a97f1e6d2b35a4a0d95fee3437846a5325e0af
Fixed the loading problem.But 
in opengl,vulkan the enemy invisible so that it kill player,
in soft gpu , ppsspp hang when meet enemy

**Comment by hrydgard** [comment]
that change is actually not giving any extra precision, rather it's removing precision. Still, interesting that it makes a difference.

soft gpu hang is interesting. Can you make a ge dump in gl or vulkan such that it hangs if you load it in software? 

But yeah I think I need to

**Comment by sum2012** [comment]
Do you mean the hang place that soft gpu  run ?
If yes,attach opengl ge dump .
[recording.zip](https://github.com/hrydgard/ppsspp/files/5583981/recording.zip)

In soft gpu in the hang place, cannot  make a ge dump

**Comment by hrydgard** [comment]
Huh, running that dump in software mode is interesting. It appear to render a completely enormous triangle of around 16 trillion pixels that wasn't clipped so it spends eternity doing that. Maybe fallout of my removal of the viewport clipping a while ago, but some new kind of clipping is necessary to at least limit rasterization to the 4096x4096 virtual box... hm.

**Comment by hrydgard** [comment]
Try #13706 please..

**Comment by sum2012** [comment]
sorry,i have to go out for work now

在 2020年11月24日週二 上午7:11，Henrik Rydgård <notifications@github.com> 寫道：

**Comment by hrydgard** [comment]
I mean, when you have time :)

**Comment by sum2012** [comment]
v1.10.3-1245-g51b213e68 fixed.
Closing

**Comment by sum2012** [comment]
I try to use long double instead of float\double (do not use pow() )
In game but  enemy invisible so that it kill player,
This time soft gpu no problem

**Comment by unknownbrackets** [comment]
> Huh, running that dump in software mode is interesting. It appear to render a completely enormous triangle of around 16 trillion pixels that wasn't clipped so it spends eternity doing that. Maybe fallout of my removal of the viewport clipping a while ago, but some new kind of clipping is necessary to at least limit rasterization to the 4096x4096 virtual box... hm. you'd think the scissor would take care of it, but it seems to trigger some overflow and escape it, not sure yet.

Hm.  That sounds funny.  Definitely possible we have overflow issues...

-[Unknown]
