### ISSUE TITLE
Patapon 3 Freezes in Opening FMV after fixes for Xyanide Resurrection

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#13700]
After reading terms of service for Patapon 3 selecting accept or decline it freezes to black screen for opening FMV. 

After fixes for Xyanide Resurrection, Patapon 3 broke this issue.
The last build worked is v1.10.3-1204-g486a82331 and the issue started in v1.10.3-1207-ge01d53870

v1.10.3-1209-ge1f56b109 works fine for Patapon 3 but Xyanide Resurrection Broken
and v1.10.3-1220-g5c4a227b7 fixed for Xyanide Resurrection but broke Patapon 3 Again

**Comment by shenweip** [comment]
Ok, I will fix this.
