### ISSUE TITLE
Ultimate Ghouls'n Ghosts (and Goku Makaimura) with graphics problems.

### ISSUE THREAD

**Issue by vanderleivieirainacio** [hrydgard/ppsspp#13717]
The Ultimate Ghouls'N Ghosts game (and its Japanese versions Goku Makaimura and Goku Makaimura Kai) are presenting graphical problems in all APIs (OpenGL, Vulkan, DirectX 11, DirectX 9) where textures disappear and a black background is left with some objects from game, and even in the Vulkan API, error messages appear several times presented by the emulator.

![Captura de tela 2020-11-23 161755](https://user-images.githubusercontent.com/46516229/100330955-57df5080-2fae-11eb-9503-06a75244b6e8.png)
![Captura de tela 2020-11-23 161702](https://user-images.githubusercontent.com/46516229/100330970-5c0b6e00-2fae-11eb-9d05-d9aa909d0039.png)

My PC:
Graphics: Sapphiretech Radeon RX 580 4GB
Operating System: Windows10 20H2 64bit

**Comment by vanderleivieirainacio** [comment]
It worked great for Ultimate Ghouls'n Ghosts and Goku Makaimura, thank you very much! However, the Japanese special edition Goku Makaimura Kai still presents the problems I described.

**Comment by hrydgard** [comment]
@vanderleivieirainacio Can you check its "game id"? like NPJH12345 or whatever.

**Comment by vanderleivieirainacio** [comment]
Ah yes! Goku Makaimura Kai's ID is ULJM05265.

**Comment by vanderleivieirainacio** [comment]
Just to make clear the ID I referred to, Goku Makaimura Kai (ULMJ05265) is the one that is having problems. The problems still remain in that ID.

**Comment by vanderleivieirainacio** [comment]
Thank you!! I was rushed and didn't realize that you were still fixing the problems! Thank you very much! You are the man!!

**Comment by chinarut** [comment]
@vanderleivieirainacio have you tried to build from source with this patch in place to verify it works with Goku Makaimura Kai?

I ask because I had the same exact issue with Ultimate Ghosts & Goblins (**ULUS10105**) and my workaround is to roll back to v1.6.3. I verified I do see this game_id in the patch:

# Ultimate Ghosts & Goblins
 ULJM05147 = true
 **ULUS10105** = true
 ULES00419 = true
 NPJH50235 = true

However, I do **not** see any reference to your game_id: ULMJ05265 so i thought I’d ask before v1.11.0 rolls out!

**Comment by hrydgard** [comment]
I assume that's meant to be ULJM05265, not ULMJ05265 ? That has already been added, right below in compat.ini.

**Comment by chinarut** [comment]
@hrydgard hey excuse the delay - good catch - I was copying and pasting from the previous comment and this explains why I couldn’t find it in compat.ini!

I just upgraded from v1.6.3 to PPSSPP_v1.10.3-1722-gb7e1e9a06 and it reintroduces the graphics issue from Ultimate Ghosts & Goblins on iPadOS 14.3. It appears to be something specific to iOS as I do **not** experience this issue with the v1.10.3 release on Android 11 (Pixel 3a).

What information may I provide that will help troubleshoot why Ultimate Ghosts & Goblins (ULUS10105) on iPadOS 14.3 (iPad Pro 12.9” 2018) still exhibits the graphics issue in v1.10.3 but not v1.6.3 as described (and accurately screenshot) by the OP?

**Comment by hrydgard** [comment]
If you're gonna compare with Android, better compare with the latest APK from https://buildbot.orphis.net/ppsspp/ . 

What specifically are you seeing on iOS? Black screen like the first post here?

I think it might be related to an unreported issue I've noticed, where the car reflections from Outrun are not working on iOS, it ends up using the same "color reinterpret" functionality as nowadays.

Still, I'm not gonna let this hold up the release for Android if it works there, so I'm reopening this and targeting 1.12 for a fix.

**Comment by chinarut** [comment]
ok - I’ll post back if the latest release on Android reintroduces the issue.

On iOS/iPadOS - yes, exactly like the screenshots above with the black screen.  Audio keeps going and you can still move the character around - it’s like the color palette is mostly black.

Let me know how I can help you troubleshoot what’s going on with iOS.

If you can recommend a git command that allows me to download/clone the source code for v1.10.3 patched with the code you wrote for #13717, I’d be happy to give building it a shot and confirm whether or not the black screen still exists.

**Comment by chinarut** [comment]
ok updated to the most recent build for Android (v1.10.3-1731-g5babc1af2) and UGnG (ULUS10105) looks great - no black screen issues on Android 11 (Pixel 3a)

again, happy to learn how to build a #13717 patched v1.10.3 in Xcode if someone can teach this github noob how to clone custom configurations (i really want to learn how hard/easy it is :)

**Comment by ToniBC** [comment]
Apparently in the version of libretro 1.11-196 the error is still present, the screen continues to remain black.

All these with the latest versions of Retroarch under Windows 10 x64 and Vulkan.

**Comment by LunaMoo** [comment]
Compat hacks are activated through external ini file, with third party builds make sure you have the PPSSPP assets.

**Comment by ToniBC** [comment]
True, I did not remember to update the configuration files, now it seems to work correctly. I think the error can now be closed.

Thanks.
