### ISSUE TITLE
help! me please!...only in game Water surface  Draw and disappear.!!

### ISSUE THREAD

**Issue by tee4341** [hrydgard/ppsspp#13714]
help! me please!...only in game Water surface  Draw and disappear.!!
But game is drawing a surface of The earth is normally and The other part of the game are perfect.

0027 - Soukyuu no Fafner (Japan)
![GifMaker_lowquality14](https://user-images.githubusercontent.com/48321898/100226015-ab6f8100-2f51-11eb-9df5-7977aea224ce.gif)

please fix to me please!.....!!!!....

**Comment by sum2012** [comment]
At least need do it.
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

**Comment by Panderner** [comment]
@tee4341 I can't produce this issue on my Realme C2. and what device are you using?

**Comment by Left4Joker** [comment]
I'm having the same problem with MANY games. With DBZ Another Road and Asphalt GT2 backgrounds for example. First time I saw it was on PC Retroarch. I tried downloading the stand-alone version, same issue. Tried older versions and the newer one that this does not happen this to me is PPSPP 1.6.3.

**Comment by Panderner** [comment]
@Left4Joker what device are you using?

**Comment by Left4Joker** [comment]
@Panderner PC

**Comment by Panderner** [comment]
> @Panderner PC

@Left4Joker specs?

**Comment by Left4Joker** [comment]
@Panderner AMD Ryzen 5 3500X Hexacore 3.6 Ghz
16GB Ram
Radeon RX 570 8GB

**Comment by sum2012** [comment]
@Left4Joker 
OpenGL and Vulkan same issue ?

**Comment by sum2012** [comment]
Also please check this version 
https://www.ppsspp.org/files/1_7_4/ppsspp_win.zip

**Comment by Left4Joker** [comment]
@sum2012 yes, I tried all video drivers, same issue.

Same problem with this version.

**Comment by sum2012** [comment]
how about v1.7.1
https://www.google.com.hk/amp/s/www.filehorse.com/download-ppsspp-psp-emulator/37279/%3famp

在 2020年12月30日週三 上午8:15，Left4Joker <notifications@github.com> 寫道：

**Comment by Left4Joker** [comment]
Same issue. With bohth OpenGL and Vulkan.

**Comment by sum2012** [comment]
so the problem is betweem v1.6.5  and v1
7.1

i am at work so that i cannot give you more build to test

在 2020年12月30日週三 上午8:21，Left4Joker <notifications@github.com> 寫道：

**Comment by Panderner** [comment]
@Left4Joker maybe your ISOs are corrupted.

**Comment by sum2012** [comment]
VS2019 doesn't support compile these old version
Hope I can solve later

**Comment by Left4Joker** [comment]
@Panderner if that's the case, why would it work fine with PPSPP 1.6.3?

**Comment by Panderner** [comment]
> @Panderner if that's the case, why would it work fine with PPSPP 1.6.3?

@Left4Joker but how about latest version?

**Comment by Left4Joker** [comment]
@Panderner it was the first one I tested.

**Comment by sum2012** [comment]
@Left4Joker Please test v1.6.3-303 https://gofile.io/d/Gv1rRo

**Comment by Left4Joker** [comment]
Can't open the .exe. It's saying I don't have permission for it.

**Comment by Left4Joker** [comment]
At first it game me "Memory could not be read", now I can't open it.

**Comment by sum2012** [comment]
How about
v1.6.3-150
https://gofile.io/d/jb3LrS

v1.6.3-454
https://gofile.io/d/gUes3K

**Comment by Left4Joker** [comment]
Are you sure those aren't update packs? I can't load any of them.

**Comment by sum2012** [comment]
You are using windows 32 bit or 64 bit ?

在 2020年12月31日週四 上午7:08，Left4Joker <notifications@github.com> 寫道：

**Comment by Left4Joker** [comment]
64 bit

**Comment by Left4Joker** [comment]
So I threw them inside a copy of 1.6.3 and I managed to make 1.6.3.454 work.
1.6.3.454 works fine
The other one I'm not able to load.

**Comment by tee4341** [comment]
android 64bit

**Comment by tee4341** [comment]
my roms is cso,iso any site , bug is very longtime

**Comment by Panderner** [comment]
> android 64bit

@tee4341 what device are you using?

**Comment by sum2012** [comment]
What is your phone model ?

在 2020年12月31日週四 上午11:06，tee4341 <notifications@github.com> 寫道：

**Comment by sum2012** [comment]
@Left4Joker  I hope I have fixed assets
Please check ppssppv1.6.3-530
https://gofile.io/d/XPy3Fi

**Comment by sum2012** [comment]
@Left4Joker please also check
v1.6.3-492
https://gofile.io/d/6KRvgQ

v1.6.3-568
https://gofile.io/d/qgItRy

**Comment by sum2012** [comment]
@Left4Joker 
Please test
ppssppv1.6.3-530
https://gofile.io/d/XPy3Fi

v1.6.3-492
https://gofile.io/d/6KRvgQ

v1.6.3-568
https://gofile.io/d/qgItRy

**Comment by Left4Joker** [comment]
Are you sure those are clean? Avast keeps blocking them.

**Comment by sum2012** [comment]
Yes,Microsoft Security Essentials said no virus
![1](https://user-images.githubusercontent.com/2177532/103473115-e1651800-4dcf-11eb-8b5e-c5782bb7c90e.png)

**Comment by unknownbrackets** [comment]
A frame dump as noted earlier would really help to confirm this issue.  Perhaps you could ask a friend who also sees this problem to create one?

-[Unknown]

**Comment by Gamemulatorer** [comment]
> help! me please!...only in game Water surface Draw and disappear.!! But game is drawing a surface of The earth is normally and The other part of the game are perfect.
> 
> 0027 - Soukyuu no Fafner (Japan) ![GifMaker_lowquality14](https://user-images.githubusercontent.com/48321898/100226015-ab6f8100-2f51-11eb-9df5-7977aea224ce.gif)
> 
> please fix to me please!.....!!!!....

Cannot reproduce this on my phone.
![Screenshot_2021-10-15-08-15-21-232_org ppsspp ppssppgold](https://user-images.githubusercontent.com/37603562/137412506-2bbfd5f1-8229-45cd-a791-9cbe988e2e49.jpg)

**Comment by hrydgard** [comment]
There's good reason to believe this might be fixed now, including @Gamemulatorer 's testing above. I'm closing.
