### ISSUE TITLE
[Suggestion][Solved to Latin Font issue] I will try make Font File. [ltn8~15.pgf]

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#13718]
### What happens?
I will try make ltn8~15.pgf.

- [ltn8.pgf] Qix++ will OK.
- [ltn12.pgf] Lunar has a line spaces problem.
- [ltn9/11/13/15?] SnakeWarriors Training has position & line spaces problem.

I have many problem yet.
Most important problem is "Line Spaces".

I tested changing "Win Ascent & Win Descent" on TTF.
But, I can't getting good result.

If anyone have a informations or advices.
Please, Give me the hints!!

[QIX++ (ltn8.pgf)]
![image](https://user-images.githubusercontent.com/48179091/100331505-978c5380-3013-11eb-8934-d1f94683d309.png)
![image](https://user-images.githubusercontent.com/48179091/100331573-abd05080-3013-11eb-8b05-093d248f8118.png)
![image](https://user-images.githubusercontent.com/48179091/100331595-b559b880-3013-11eb-958c-e8efdc8235b8.png)
![image](https://user-images.githubusercontent.com/48179091/100331626-bee32080-3013-11eb-98f6-ed1ebd0b78e6.png)
![image](https://user-images.githubusercontent.com/48179091/100331685-d28e8700-3013-11eb-9a60-52bacf26b320.png)
![image](https://user-images.githubusercontent.com/48179091/100333061-7cbade80-3015-11eb-865a-2df84dca9b10.png)

[Lunar] (Real PSP ltn12.pgf)
![image](https://user-images.githubusercontent.com/48179091/100330128-e6d18480-3011-11eb-9386-b5f290613bf1.png)
![image](https://user-images.githubusercontent.com/48179091/100330163-f355dd00-3011-11eb-8c0a-af1fabb48f92.png)

[Lunar] ("Maked ltn8.pgf" rename to ltn12.pgf)
![image](https://user-images.githubusercontent.com/48179091/100330439-4c257580-3012-11eb-9337-47da95f60f0d.png)
![image](https://user-images.githubusercontent.com/48179091/100330496-5f384580-3012-11eb-818f-2d5b9cd8bc5e.png)

I think "Warning screen" will looks good size.
But,The  line spaces to large that In game conversation window.

[SnakeWarriors] (test by maked ltn8.pgf "sans-serif".)
![image](https://user-images.githubusercontent.com/48179091/100337464-c0641700-301a-11eb-9ad9-7e6115a0a96c.png)

**Comment by nassau-tk** [comment]
https://drive.google.com/file/d/1gbaAyve4lH9-pWMb1jELlRYLgVB6HFvN/view?usp=sharing

"Glyph Width & Glyph Hight Size Tuned ltn8.pgf"
But,Ascender is couldn't fix.

I asked for @tpunix that how to make "small latin pgf".

>@tpunix said below.
you can change ascender/decsender value and test again.
the offset in pgf file:
0xd4: ascender
0xd8: descender
this value are in fixed 26.6 format.
Use a hexedit tool. Modify the generated pgf file.

I don't have a information of about Hexedit tool (equal to binary Editor?).
So, I was checked by myself, but it wasn't imagined at all. (By google.)

Please, Someone teach me....How to fixed PGF's Ascender & Descender by "binary editor".

[I want change Ascender "15.828125" to "9.000000"]
![image](https://user-images.githubusercontent.com/48179091/100469725-2edbce80-311a-11eb-8fe8-edfd30ea3e54.png)

**Comment by sum2012** [comment]
online hex editor
https://hexed.it/
![3](https://user-images.githubusercontent.com/2177532/100483457-0234b080-3134-11eb-9949-30d4560ae53d.png)

But 15.828125 don't find in 0xd4 's position

**Comment by nassau-tk** [comment]
Is it right?!
I couldn't find too.
I was convinced.

Um...

**Comment by nassau-tk** [comment]
BUT!!
I try chnaged the value then!!!

Wao!!
![image](https://user-images.githubusercontent.com/48179091/100489672-0de69e00-3159-11eb-83ce-11a34ea9fdf8.png)

**Comment by nassau-tk** [comment]
It looks good?

![image](https://user-images.githubusercontent.com/48179091/100489969-17710580-315b-11eb-8c70-f1dee83a2038.png)

**Comment by nassau-tk** [comment]
OK.
I will finished making for ltn8.pgf/ltn10.pgf/ltn12.pgf/ltn14.pgf.

![ltn8_10_12_14_LUNAR](https://user-images.githubusercontent.com/48179091/100493492-9fb2d300-317a-11eb-8483-4c5cf7cea39f.gif)

Next!! Making for ltn9/11/13/15.pgf.

**Comment by hrydgard** [comment]
Awesome :)

**Comment by nassau-tk** [comment]
Note: This Address & This value
Ascender    : 10.000000  /  Descender  :-2.000000
Real is 9.00000 & -2.000000
![image](https://user-images.githubusercontent.com/48179091/100499479-5760d880-31ad-11eb-9bd2-55c2f8d96d4a.png)

**Comment by nassau-tk** [comment]
@hrydgard 
@sum2012 
and all.

OK!!
I will finished making for ltn9.pgf/ltn11.pgf/ltn13.pgf/ltn15.pgf.

![ltn9_11_13_15_LUNAR](https://user-images.githubusercontent.com/48179091/100514242-584a3800-31b6-11eb-84ed-ef3fc124abb4.gif)

But,These are not **"perfectly work"**.
Because, **"line spaces"** are  not correctly on some games yet.

[Real PSP ltn9.pgf]
![image](https://user-images.githubusercontent.com/48179091/100495598-540b2400-3190-11eb-89db-0393f139ca22.png)

[My Created ltn9.pgf]
![image](https://user-images.githubusercontent.com/48179091/100514300-d60e4380-31b6-11eb-8fc2-b55cec2577f1.png)
![image](https://user-images.githubusercontent.com/48179091/100514305-ddcde800-31b6-11eb-9b0e-801cf519fe9f.png)

But sentences can be read now by many games.
It will become to working like a QiX++.
I think it becomes quite better than the current state now.

How do you think about this?

I think about this.
"OK! Let's make Pull Request!"
(But, If I find a solved line spaces problem then let's Remake PL soon.)

**Comment by sum2012** [comment]
@nassau-tk  can you ask again @tpunix that where is the address of the  "line spaces" of the font ?

**Comment by nassau-tk** [comment]
Yeeees,Of course. I 'm already ask to @tpunix about it.:wink:
https://github.com/tpunix/pgftool/issues/3

**Comment by nassau-tk** [comment]
:My Note:

[1st  Step]
Convert to PGF from TTF by [pgftool](https://github.com/tpunix/pgftool).
And check the pgf files by dump_pgf(-h option).
Important value is below.
>max glyph width 16
>max glyph hight 14

If not match the value then resize TTF and reconvert.
Do Try and Error.

[2nd Step]
ltn8.pgf to ltn15.pgf (Small Latin).
It must need change value by binary editor(hexeditor).
Change to below wrote value on the address.
The purpose is changing value for "Ascender & Descender".
Target value of Ascender is "9.000000"~"10.000000".
Target value of Descender is "-2.000000".
if fixed&saved  the pgf files.
Re check by dump_pgf by pgftool.

![image](https://user-images.githubusercontent.com/48179091/100517326-390ad500-31cd-11eb-89c4-bbbd2da9e8d0.png)

[Japanese memo]
ltn8～15.pgfはpgfファイルをpgftool（C言語）で作成後
バイナリエディターで開き上記のアドレスを
上記の数値に変更することにより、PGFフォントの
Ascenderを10.000000
Descenderを-2.000000
に修正できる。
※オリジナルPGFはAscenderが9.000000なので
　それに合わせる場合は 80 02 ==> 40 02 に変える。
　これは使用しているTTFの形状や、形状の編集により変更する。

この変更を行わないと行間が縮まらない。
LUNAR(ltn12使用)などのゲームで表示が正しく行われない。
QIX++(ltn8使用)は改行がないので問題なく表示される。
上記を行ってもSnake Warriorsでは行間が広いままで修正されない。
h_size　v_size　の問題なのか？調査中。(2020/11/28)

**Comment by nassau-tk** [comment]
This will be solved the few part of #2788 .

**Comment by nassau-tk** [comment]
@tpunix gave me advice.
>try "max glyph height"? offset is 0xfe.

I tried it.
But, It's not good result.(No change any.)

**Comment by nassau-tk** [comment]
Ok.
It was merged.
But, this one not close yet.

**Comment by nassau-tk** [comment]
@hrydgard 

By the way.
Please tell me about below.
PPSSPP for Windows is overwrite font files every install timing.
So,PPSSPP Font files will update allways automatically.
But,PPSSPP for Android is not overwrite it?
Is it Right?

**Comment by Panderner** [comment]
@nassau-tk how about this for Snake Warriors: Training?

v1.10.3-1268-gb5e230077 font:
![Screenshot_2020-11-29-22-24-59-42_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/100544668-49d14e80-3292-11eb-9def-1c1c024678cc.png)

Real PSP font:
![Screenshot_2020-11-29-22-24-34-14_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/100544678-548be380-3292-11eb-83c7-9bea8d7b3e19.png)

**Comment by nassau-tk** [comment]
@Panderner 

Yes,I said above that "It has a problem yet".
It is your asked one.
But,We merged it.
Because,It has many merit even if there is problem.

Modify is continued.

**Comment by hrydgard** [comment]
@nassau-tk On Android, the PPSSPP font files are hardwired into the APK. they will be updated when a new APK is installed.  However! You can also make a /flash0 folder on your device and put font files there. Actually, looking at the code I'm not sure that still works... Hm

**Comment by nassau-tk** [comment]
Oh...I don't knew that system!
OK!! I understood it.
Thank you.

Note : I was creating flash0.So,I couldn't feel font update on Android.:sweat_smile:

**Comment by nassau-tk** [comment]
There are still problem.

"LineSpace&Width"
- Snake Warriors Training
- Eragon

**Comment by Panderner** [comment]
There's an overlap for Dragon Ball Z: Shin Budokai:

Current PPSSPP font
![Untitled6_20201202201420](https://user-images.githubusercontent.com/37503397/100871676-9e1b3f00-34db-11eb-9ca8-6fb9e0b49a4c.png)

Real PSP font:
![Screenshot_2020-12-02-20-16-44-44_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/100871538-69a78300-34db-11eb-9cb7-64437966c102.png)

**Comment by Panderner** [comment]
@nassau-tk Fieldrunners and Eragon uses ltn8.pgf

**Comment by nassau-tk** [comment]
@hrydgard 
@Panderner 

A door of a possibility was opened?
![image](https://user-images.githubusercontent.com/48179091/100883972-4937f280-34f4-11eb-98cc-acb246787df2.png)

But,Maybe the goal is far....
(I think the adjustment of width is serious hopelessly.)
![image](https://user-images.githubusercontent.com/48179091/100884723-265a0e00-34f5-11eb-8176-10b142780851.png)

Long time is needed.
Please wait a moment patiently.
・・・・・NOW LOADING・・・・・(My brain Stucking.)

:My Note:
Important points(need more inspect)
![image](https://user-images.githubusercontent.com/48179091/100885522-1858bd00-34f6-11eb-979e-155237899ee5.png)

**Comment by Panderner** [comment]
> * Dragon Ball Z : Shin Budokai (ltn0 or ltn6? little w left margin?)

jpn0.pgf @nassau-tk

**Comment by Panderner** [comment]
@nassau-tk there's some graphical glitches for PC Engine games released on PSN store.

The aspect ratio menu and software manual word is glitched on new font but not on old font.

New pgf:
![Screenshot_2020-12-04-12-02-38-54_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/101122302-1a716780-362d-11eb-8201-a02476e31bc2.png)
![Screenshot_2020-12-04-12-37-35-05_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/101122462-8c49b100-362d-11eb-93b5-b9e0c943a03d.png)

Old pgf:
![Screenshot_2020-12-04-12-29-58-48_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/101122487-9d92bd80-362d-11eb-9001-21d738a804c0.png)
![Screenshot_2020-12-04-12-30-27-24_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/101122520-a97e7f80-362d-11eb-875b-9831766cb6c6.png)
#

**Comment by nassau-tk** [comment]
@Panderner 
I tried fixed All PGF.
Pease test it.
https://drive.google.com/drive/folders/1TDzZLMDGiNTwlljyLlihiCYn-3AVj4_G?usp=sharing

**Comment by nassau-tk** [comment]
@Panderner 

OK.
https://drive.google.com/drive/folders/1TDzZLMDGiNTwlljyLlihiCYn-3AVj4_G?usp=sharing

PLease Test it.

**Comment by Panderner** [comment]
Eragon, Fieldrunners, and Snake warriors are fixed but official PC Engine games released on PSN are not fixed.
![Screenshot_2020-12-06-06-58-59-88_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/101267134-97692200-3790-11eb-83af-34376c367ece.png)
![Screenshot_2020-12-06-06-58-50-02_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/101267135-99cb7c00-3790-11eb-8cb3-60e71562daf3.png)

**Comment by nassau-tk** [comment]
@Panderner 
Plaease Retest it.
https://drive.google.com/file/d/1I3apVxhluV2HR_qHQvIpvBIBowjDEfsz/view?usp=sharing

**Comment by nassau-tk** [comment]
@Panderner 

Did you install All fixed PGF?
jpn0.pgf
kr0.pgf
ltn0~15.pgf

**Comment by Panderner** [comment]
> @Panderner
> 
> Did you install All fixed PGF?
> jpn0.pgf
> kr0.pgf
> ltn0~15.pgf

yes

**Comment by nassau-tk** [comment]
@Panderner 
Please,tell me If you can.
How to boot "PC-Engien Archive Games"?
If my memories right then these software has copy guard.

![image](https://user-images.githubusercontent.com/48179091/101269192-677d4700-37af-11eb-9efa-c8771a981d23.png)

**Comment by LunaMoo** [comment]
They don't have any copy guard, they come as an app(emulator) and DLC(game). See [here](https://forums.ppsspp.org/showthread.php?tid=23467&pid=128330#pid128330).

**Comment by Panderner** [comment]
> @Panderner
> Please,tell me If you can.
> How to boot "PC-Engien Archive Games"?
> If my memories right then these software has copy guard.
> 
> ![image](https://user-images.githubusercontent.com/48179091/101269192-677d4700-37af-11eb-9efa-c8771a981d23.png)

You need a DLC, Please put the DLC to PSP/game directory as long as same game id

**Comment by Panderner** [comment]
PC engine games will not boot without a DLC.

**Comment by nassau-tk** [comment]
@Panderner 
@LunaMoo 

Thank you !!
I understood it.

**Comment by nassau-tk** [comment]
@Panderner 

Re fixed All PGF.
https://drive.google.com/drive/folders/1TDzZLMDGiNTwlljyLlihiCYn-3AVj4_G?usp=sharing

NOTICE : Download & install "All PGF Files".

**Comment by Panderner** [comment]
> @Panderner
> 
> Re fixed All PGF.
> https://drive.google.com/drive/folders/1TDzZLMDGiNTwlljyLlihiCYn-3AVj4_G?usp=sharing
> 
> NOTICE : Download & install "All PGF Files".

PC Engine font issue is now fixed and same as fixed games above.

**Comment by nassau-tk** [comment]
@hrydgard 

I finished modifide to all PGF font files.
And,I made a new Pull Request.
Please,Check & merge it.

**Comment by nassau-tk** [comment]
OK.

It merged by @hrydgard .

I will close this topic.

Thank you for @sum2012  & @Panderner  & @LunaMoo & everyone!!

**Comment by GBOATET** [comment]
Can anyone help me with trying to simply convert a TTF using TTFtoPGF?

Both FontHacks and TTFtoPGF crash for me no matter what and lag my PC like crazy. It takes forever to get an error message, and it usually hangs for like 10 minutes.

**Comment by nassau-tk** [comment]
@GBOATET 

Probably, You should not ask on closed post.
But, I think no one can answer even if it's asked on the forum, so I answer.

You will not can make pgf files by those applications on my knowledge.

You must these.
1. Build working [pgftool](https://github.com/tpunix/pgftool) which moves on your PC.
2. Get some font create application. 
    [Like this](https://www.high-logic.com/font-editor/fontcreator)
3. Get some HexEditor or use some [web service](https://hexed.it/).

And, You must get the original pgf files from your own real PSP.

These step will ready to make font and convert to pgf and dump the pgf.
These were a needed matter in case of me.

But, If you have not knowledge of font creating then you must study about font create.
Because, You can't make pgf files by only convert TTF to pgf.

You must change size & position & shape the TTF.
And, must change & fix other values the TTF.
And, convert TTF to pgf by pgftool.
And, dump the pgf files to change some value to correct value.

When you have these knowledge, I'll recommend to try it.

Last....
I'm not good at English.
So, I can't teach about more than above.
