### ISSUE TITLE
[Feature request] Please add vulkan support for iOS/macOS

### ISSUE THREAD

**Issue by Halo-Michael** [hrydgard/ppsspp#13728]
Vulkan has now added official SDK support for iOS/macOS, so ppsspp should now be able to use vulkan on iOS/macOS.

https://vulkan.lunarg.com/sdk/home#mac

![D34E847F8FF6016C137EA834BD4C01EA](https://user-images.githubusercontent.com/45062120/100646292-cdfe0180-3378-11eb-97d1-7596dcd88422.png)

**Comment by hrydgard** [comment]
It is already supported on macOS, you just need to install MoltenVK (the Vulkan on Metal wrapper).

As for iOS, this has already been requested: #10654
