### ISSUE TITLE
Midnight Club 3 - DUB Edition (Europe) (En,Fr,De,Es,It) (v1.02) missing some module 

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#13723]
ppsspp-v1.10.3-1257-g6bf9f20f5-windows-amd64
log:
https://gist.github.com/sum2012/b3fb7aa3eb0f12bb8a71ba5d3b00b797

tag @Askmewho 
my todo list: https://gist.github.com/sum2012/bcf722731d865230cf4aadafc97c8a9e

@ANR2ME  The game might not be multi player because of missing network module.
Do you interest to add support t? Thanks. 

47:03:549 user_main    I[LOADER]: hle\scekernelmodule.cpp:1326 Module sceNetIfhandle_Service: 08232fd0 0822a9c4 0822aa0c

47:03:637 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceWlanDrv_lib,5e7c8d94) unresolved in 'sceNetAdhoc_Library', storing for later resolving
47:03:637 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceWlanDrv_lib,5ed4049a) unresolved in 'sceNetAdhoc_Library', storing for later resolving
47:03:637 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceWlanDrv_lib,b4d7cb74) unresolved in 'sceNetAdhoc_Library', storing for later resolving
47:03:637 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceWlanDrv_lib,a447103a) unresolved in 'sceNetAdhoc_Library', storing for later resolving
47:03:637 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,1858883d) unresolved in 'sceNetAdhoc_Library', storing for later resolving
47:03:637 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,25cc373a) unresolved in 'sceNetAdhoc_Library', storing for later resolving
47:03:637 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,a8b6205a) unresolved in 'sceNetAdhoc_Library', storing for later resolving
47:03:637 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,a93a93e9) unresolved in 'sceNetAdhoc_Library', storing for later resolving
47:03:637 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,6b294ee4) unresolved in 'sceNetAdhoc_Library', storing for later resolving
47:03:637 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,f6db0a0b) unresolved in 'sceNetAdhoc_Library', storing for later resolving
47:03:637 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,7574fda1) unresolved in 'sceNetAdhoc_Library', storing for later resolving
47:03:637 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,ca3cf5eb) unresolved in 'sceNetAdhoc_Library', storing for later resolving
47:03:637 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,757085b0) unresolved in 'sceNetAdhoc_Library', storing for later resolving
47:03:637 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,94b44f26) unresolved in 'sceNetAdhoc_Library', storing for later resolving
47:03:637 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,515b2f33) unresolved in 'sceNetAdhoc_Library', storing for later resolving
47:03:637 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,05d525e4) unresolved in 'sceNetAdhoc_Library', storing for later resolving
47:03:637 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,d60225a3) unresolved in 'sceNetAdhoc_Library', storing for later resolving
47:03:637 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,2e005032) unresolved in 'sceNetAdhoc_Library', storing for later resolving
47:03:637 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,33b230bd) unresolved in 'sceNetAdhoc_Library', storing for later resolving
47:03:637 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,1f94afd9) unresolved in 'sceNetAdhoc_Library', storing for later resolving
47:03:637 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,0a5a8751) unresolved in 'sceNetAdhoc_Library', storing for later resolving
47:03:637 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,b3a48b7f) unresolved in 'sceNetAdhoc_Library', storing for later resolving
47:03:637 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,949f1fbb) unresolved in 'sceNetAdhoc_Library', storing for later resolving

47:03:637 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceWlanDrv_lib,482cae9a) unresolved in 'sceNetAdhocctl_Library', storing for later resolving
47:03:637 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceWlanDrv_lib,c9a8cab7) unresolved in 'sceNetAdhocctl_Library', storing for later resolving
47:03:637 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceWlanDrv_lib,5baa1fe5) unresolved in 'sceNetAdhocctl_Library', storing for later resolving
47:03:637 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceWlanDrv_lib,2d0fae4e) unresolved in 'sceNetAdhocctl_Library', storing for later resolving
47:03:637 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceWlanDrv_lib,56f467ca) unresolved in 'sceNetAdhocctl_Library', storing for later resolving
47:03:637 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,5216cbf5) unresolved in 'sceNetAdhocctl_Library', storing for later resolving
47:03:637 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,d2422e4d) unresolved in 'sceNetAdhocctl_Library', storing for later resolving
47:03:638 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,d1be2ce9) unresolved in 'sceNetAdhocctl_Library', storing for later resolving
47:03:638 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,ab7dd9a5) unresolved in 'sceNetAdhocctl_Library', storing for later resolving
47:03:638 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,7ba3ed91) unresolved in 'sceNetAdhocctl_Library', storing for later resolving
47:03:638 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,03164b12) unresolved in 'sceNetAdhocctl_Library', storing for later resolving
47:03:638 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,389728ab) unresolved in 'sceNetAdhocctl_Library', storing for later resolving
47:03:638 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,d5b64e37) unresolved in 'sceNetAdhocctl_Library', storing for later resolving
47:03:638 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,da02f383) unresolved in 'sceNetAdhocctl_Library', storing for later resolving
47:03:638 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,afa11338) unresolved in 'sceNetAdhocctl_Library', storing for later resolving
47:03:638 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,b20f84f8) unresolved in 'sceNetAdhocctl_Library', storing for later resolving
47:03:638 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,a55c914f) unresolved in 'sceNetAdhocctl_Library', storing for later resolving
47:03:638 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,0d633f53) unresolved in 'sceNetAdhocctl_Library', storing for later resolving

**Comment by sum2012** [comment]
Tag @MojoJojoDojo 
I don't have time to test  multi player.Can you help me to test this game(If you have this game) ? Thanks.

**Comment by MojoJojoDojo** [comment]
@sum2012 according to the list I helped create and made it should work but maybe it needs a recheck.

**Comment by sum2012** [comment]
@MojoJojoDojo What is your name in
https://forums.ppsspp.org/ ?

**Comment by ANR2ME** [comment]
Based on the logs it seems this game is loading prx files similar to the one from official firmware (ie. ifhandle.prx) instead of using the HLE version (not sure if PPSSPP have this module as HLE or not tho), which is why it leads to internal/driver syscalls.

Currently PPSSPP doesn't supports official firmware's prx as i know as it will requires a large part of the code to be rewritten to supports driver/internal syscalls.

**Comment by MojoJojoDojo** [comment]
> @MojoJojoDojo What is your name in
> https://forums.ppsspp.org/ ?

it's Zinx777.
I helped with testing most of the ad-hoc games this year.

**Comment by sum2012** [comment]
I will close this issue when I finish my interest part.

**Comment by benderscruffy** [comment]
Is this still a problem

**Comment by sum2012** [comment]
I forget to go my homework.
And I lost the iso,closing this one
