### ISSUE TITLE
[Android][Text Input Screen] Text color should be change light color on Text input screen

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#13731]
### What happens?
Text color should be change light color on "Text input screen".
I think that current color seems too much difficult to look.(VALUE)
![Text Input Dialog](https://user-images.githubusercontent.com/48179091/100734206-a52a4a80-3412-11eb-8978-7633769328d3.jpg)

**Comment by Panderner** [comment]
@nassau-tk are you using dark mode in android's system settings?

**Comment by nassau-tk** [comment]
No.l'm not set dark mode.

Is your text color not dark???

**Comment by hrydgard** [comment]
That might be some of android theme files interacting in some bad way (try to set some colors so you don't get a flash of white starting up and stuff like that). 

Definitely not intended to be this way!

**Comment by nassau-tk** [comment]
What?
Ah....How should I do?
Xperia XZ1compact & Galaxy S20 same color.
 I'm using "Nova Launcher". (Android Home app)
But,Not change...
OK.
I will check more!

**Comment by hrydgard** [comment]
Yeah it's not your or your device's fault, I'm saying it's PPSSPP's themes messing it up. See android/res/values/styles .  However I don't know what in the style xmls would screw this up... Doesn't see anything obvious

**Comment by nassau-tk** [comment]
Um...
I tried changing default home app and other app.
But, It's not change text color.

"DARK TEXT"

**Comment by nassau-tk** [comment]
Oh!?Really!?
I see! :smile: :

**Comment by ANR2ME** [comment]
I wonder if this is only happened with Android 9 (API 28) or newer? 
something similar to this may be https://stackoverflow.com/questions/54392418/android-9-app-menu-is-dark-text-on-dark-background

**Comment by nassau-tk** [comment]
Um...
Yes,Yes,Yes.

My Xperia is Android 9 and Galaxy S20 is Android10.

**Comment by hrydgard** [comment]
Should be fixed now, let me know how it works for you.

**Comment by nassau-tk** [comment]
@hrydgard 

Perfect work!!
The text color was changed to white.
I checked light & dark both mode on Android.
It seems same appearance.

![Screenshot_20201220-223238_PPSSPP](https://user-images.githubusercontent.com/48179091/102714694-c85e6080-4313-11eb-8f1b-0ecd130284bd.jpg)
![Screenshot_20201220-223314_PPSSPP](https://user-images.githubusercontent.com/48179091/102714701-c8f6f700-4313-11eb-96a9-a6f87c4bbce8.jpg)
