### ISSUE TITLE
Graphical Problem in Cars

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#13735]
There's a graphical artifacts in Cars
![Screenshot_2020-12-03-14-28-48-15_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/100972654-16354380-3574-11eb-9c8f-69bc299f69ad.png)

Here's a GE Dump:
[Cars.zip](https://github.com/hrydgard/ppsspp/files/5634090/Cars.zip)

**Comment by Panderner** [comment]
there's workaround to fix this graphical glitch by enable disable slower effects

**Comment by Panderner** [comment]
it seems https://github.com/hrydgard/ppsspp/commit/3b5406395552b332edfc6df17ecb60cf3a7959eb Fixed Graphical Glitches in Cars.
![Screenshot_2020-12-16-14-46-49-45_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/102337149-12221080-3fcd-11eb-88ea-89fae7ad0036.png)
Closing this now

**Comment by hrydgard** [comment]
Oh good, thanks for testing!
