### ISSUE TITLE
[SaveData] All save data date & filesize is not appear correctly.

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#13756]
### What happens?
All savedata date is not overwrite.
Those data is saving correctly.
Maybe,just appearance of date?
~~Because,The old savedata was changed to the date.~~
~~The data was not saving after the date.~~

It will happen Windows & Andoroid.

### What *should* happen?
Appear the date correctly.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
PPSSPP Ver.：1.10.3-1308
OS：Windows10（64-bit）Japanese
CPU：Ryzen7 3800X（8-core）
GPU：RADEON RX5700XT
Resolution：2560×1440
RAM：32GB

PPSSPP Ver.：1.10.3-1308
OS：Android 10.0
DeviceName：Samusung Galaxy S20 / SC-51A
CPU：Snapdragon865（Octa-core）
GPU：Adreno 650
Resolution：3200 x 1440 (Max)
RAM：12GB
ROM：128GB
ExternalStrage：microSDXC 512GB

[These game were saved at 2020/12/09 but it was not change date.]
![Screenshot_20201209-073949_PPSSPP](https://user-images.githubusercontent.com/48179091/101550448-b109a400-39f2-11eb-996e-dcc25ded11a8.jpg)

![Screenshot_20201209-073940_PPSSPP](https://user-images.githubusercontent.com/48179091/101550479-b961df00-39f2-11eb-8e61-dfe4d36a9101.jpg)

![Screenshot_20201209-074018_PPSSPP](https://user-images.githubusercontent.com/48179091/101550512-c67ece00-39f2-11eb-8f6e-f4709f69ff01.jpg)

But,I don't have memory that this game is saved the near the day.
Strange...
![Screenshot_20201209-073909_PPSSPP](https://user-images.githubusercontent.com/48179091/101550536-d1d1f980-39f2-11eb-8a6f-e58c73f6c798.jpg)

**Comment by nassau-tk** [comment]
It will happen on "Screen of PSP's Save".
Because,It will not happen on original save screen like below.

![image](https://user-images.githubusercontent.com/48179091/101563060-ef5f8d00-3a0b-11eb-94b5-563b7b815904.png)

**Comment by nassau-tk** [comment]
I tested 2 things.

[Patern 1]
I will create a new save data and check the date.
**Result : It made right date.But,If overwrite the saved data then date is not renew.**

[Patern2]
I over write the save data from other device.(Other date data)
Android(2020/11/01) overwrite to PC(2020/10/26).
**Result : The save data can load correctly. But,The date is not change!**

**Comment by sum2012** [comment]
Do  v1.10.3-1306-g31648acc2 or older version no problem ?

**Comment by nassau-tk** [comment]
I would found the it.
- v1.10.3-828-g58776927a is correct time stamp & data size.
- v1.10.3-833-gf82754e8b is not correct time stamp & data size.

If boot by v1.10.3-828 then time stamp & size appear correctly that if check with same save data.

**Comment by nassau-tk** [comment]
And,Real time stamp & filesize on Windows Explorer is match with v1.10.3-828.

**Comment by shenweip** [comment]
So very likely due to 81ad9a9, I will fix this then.

**Comment by shenweip** [comment]
Please try #13764.

**Comment by nassau-tk** [comment]
If merge it then l will check it!

**Comment by nassau-tk** [comment]
@shenweip 

It's working good!!

![Screenshot_20201224-071642_PPSSPP](https://user-images.githubusercontent.com/48179091/103040865-14313400-45b8-11eb-9f0a-ecf4520ba24c.jpg)
![Screenshot_20201224-071333_PPSSPP](https://user-images.githubusercontent.com/48179091/103040869-15626100-45b8-11eb-8937-92376040ca68.jpg)
