### ISSUE TITLE
The Letter I is missing in BlazBlue Continuum Shift II

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#13767]
AFAIK the letter i in BlazBlue Continuum Shift II is missing in victory quotes and in-game cutscenes:
![Screenshot_2020-12-14-14-29-00-420_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/102065084-11ee0d80-3e33-11eb-8099-34405e059ad3.jpg)
![Screenshot_2020-12-14-14-30-45-090_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/102065112-19adb200-3e33-11eb-98d0-2e7a333b2601.jpg)
![Screenshot_2020-12-14-14-33-13-721_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/102065117-1ca8a280-3e33-11eb-8964-287a05b61da3.jpg)

Although Main menu, Pause menu and Story Cutscenes fine though:
![Screenshot_2020-12-14-17-32-49-115_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/102065317-5da0b700-3e33-11eb-9ef4-eb852043e26d.jpg)
![Screenshot_2020-12-14-17-39-18-736_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/102065326-61343e00-3e33-11eb-96cf-38e4ff8cc7f5.jpg)

**Comment by nassau-tk** [comment]
@Panderner 

OK!! Thanks!
I'll try check and fixed it.
Please, Give me a time!

**Comment by nassau-tk** [comment]
Um...
I must chek some patern.
Possibility 1 : kr0.pgf fix.(Balance of Korean caracters saize & Latin characters size.)
Possibility 2 : Possibility of Other Font loading.

**Comment by nassau-tk** [comment]
It's very very very strange system this is.
Exactly,This game loading PGF files.
But,Those PGF fonts shapes are changed in the game I think.
And," i & l " width is transform to thin.(Maybe.)
And," b & d & h " higth are transform to high.(a part of character.)

[**Real PSP** Screen Shot.](PSP Language Setting : English)
![BBCS2_RealPSP_FontCheck](https://user-images.githubusercontent.com/48179091/102085380-e3375d80-3e59-11eb-9477-406af5bf1600.png)

Maybe,I need many time for control to character bold & width & hight.

**Comment by nassau-tk** [comment]
Yes, If I wide "i" width then appear on the screen.
But, It will brake the size balance with other character.
I must find the good balance point .:scream:

**Comment by nassau-tk** [comment]
@Panderner 

https://drive.google.com/file/d/1Jt1LUnOymyvI6TMs9yVZVBSNaoTQFHJY/view?usp=sharing

Please test it....
Good night...zzz

**Comment by hrydgard** [comment]
There's something about per character fractional pixel offsets, I wonder if that aligns just wrong to skip the pixels of the I or something... I don't know how it works though :(

**Comment by nassau-tk** [comment]
I have no choice but to hope that there will be no such strange patterns any more.~( ´•︵•` )~

**Comment by Panderner** [comment]
Thanks @nassau-tk for fixing letter i issue closing this now:
![Screenshot_2020-12-17-17-18-52-928_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/102468130-1c571400-408c-11eb-960b-650f7888d9c5.jpg)
