### ISSUE TITLE
Soul Calibur Broken Destiny

### ISSUE THREAD

**Issue by andy0232** [hrydgard/ppsspp#13768]
Heya folks, I'm back, so its quite simple. When you finish your creation, it asks you to take a photo of the character (its like a character portrait ingame yknow) I do that but the photo stays black, I have no idea how to resolve this. There are screenshots below

Android Samsung Galaxy s6
PPSSPP Version: 1.10.3

Before photo is taken
![Screenshot_20201214-133029](https://user-images.githubusercontent.com/66369667/102120632-d2162e80-3e10-11eb-9b61-efbe84b2a737.png)

After Photo is taken
![Screenshot_20201214-133037](https://user-images.githubusercontent.com/66369667/102120680-e4906800-3e10-11eb-8fe3-1667356180a7.png)

**Comment by sum2012** [comment]
I test in phone Black shark 3 no problem , maybe only Mali gpu bug.

![Screenshot_2020-12-15-22-19-04-477_org ppsspp ppsspp](https://user-images.githubusercontent.com/2177532/102226766-c0717b80-3f23-11eb-86bc-b9ed989d3eb8.jpg)

**Comment by andy0232** [comment]
That's possible but, is there any workaround?

**Comment by sum2012** [comment]
I don't expert on it.
wait @hrydgard @unknownbrackets or other people help

**Comment by hrydgard** [comment]
Default settings? Did you turn off "slow effects" or something?

**Comment by andy0232** [comment]
Need a brief graphics screenshot, here ya go!
![Screenshot_20201217-203953](https://user-images.githubusercontent.com/66369667/102563780-0fe0b480-40a8-11eb-9b4a-af146af34e71.png)
![Screenshot_20201217-203946](https://user-images.githubusercontent.com/66369667/102563787-14a56880-40a8-11eb-895d-911ede605250.png)
![Screenshot_20201217-203937](https://user-images.githubusercontent.com/66369667/102563806-1e2ed080-40a8-11eb-84bd-1e0c9fb2920b.png)
![Uploading Screenshot_20201217-203930.png…]()

**Comment by andy0232** [comment]
@hrydgard the issue was the simulate block effects, thanks for the suggestion,  I'm going to close this issue after you respond

**Comment by hrydgard** [comment]
Yeah. PPSSPP's UI should probably be clearer about which settings are speedhacks that can break graphics, and which ones are actual quality settings.
