### ISSUE TITLE
No Ignore camera notch when centering option for some devices

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#13774]
Some devices like Realme C2 doesn't have Ignore camera notch when centering option while other phones with notches have.

Realme C2:
![Screenshot_2020-12-16-18-33-25-80](https://user-images.githubusercontent.com/37503397/102337494-7f35a600-3fcd-11eb-9ac2-d4fbb25ee04c.png)

POCO M3:
![Screenshot_2020-12-16-18-36-13-509_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/102337626-ae4c1780-3fcd-11eb-9751-871d62975e09.jpg)

**Comment by hrydgard** [comment]
That option shows if (a) Android version >= 29  and (b) any notch was detected.

Looks like the check should be >= 28, I'll fix.
