### ISSUE TITLE
Error in shader compilation for postshader. (OpenGL/Android)

### ISSUE THREAD

**Issue by Saramagrean** [hrydgard/ppsspp#13779]
### What happens?
Since v1.10.3-1330-g73da378ef show error message always if use OpenGL + any Shader, sound still playing but blackscreen unplayable. happen on OpenGL only, on Vulkan is fine.

![131389501_725465475055485_8791172735214334650_n](https://user-images.githubusercontent.com/26355472/102446314-10555d00-4060-11eb-94bf-859be3101e84.jpg)
(use Natural color shader.)

### What *should* happen?
Can playable game with OpenGL+Shader.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Redmi Note 8 (Snapdragon 665, Adreno 610, Ram 3, Android 10, OpenGL 3.2)

**Comment by hrydgard** [comment]
Oops. I'll get that fixed soon.
