### ISSUE TITLE
Cannot connect to server which is able to be connected by a previous build

### ISSUE THREAD

**Issue by 9tin9tin9** [hrydgard/ppsspp#13787]
### What happens?
The GvG Next Plus atwiki page says that in order to play online using their specified server, that specific build is required (LunaMoo/ppsspp  tag v1.9.3-950-g4debff114). I don't understand why this is the case. I tried using your build (v1.10.3) (installed using homebrew). After selecting multiplayer mode, it freezes at loading screen and terminal stops at

58:25:521 task         I[SCENET]: HLE/sceNetAdhoc.cpp:188 sceNetAdhocctlInit(8192, 48, 08b53674) at 0885bfa8

After a while, ppsspp closed and terminal logged

59:40:596 task         E[SCENET]: HLE/proAdhoc.cpp:1501 Socket error (60) when connecting to 25.13.223.176/25.13.223.176:27312
59:40:596 task         W[SCENET]: HLE/sceNetAdhoc.cpp:201 sceNetAdhocctlInit: Failed to init the network but faking success
59:40:596 task         W[SCENET]: HLE/sceNetAdhoc.cpp:1027 UNTESTED sceNetAdhocctlAddHandler(885b974, 0): added handler 0
59:40:598 user_main    I[SCENET]: HLE/sceNetAdhoc.cpp:867 sceNetAdhocctlScan() at 0885173c
59:40:598 user_main    E[SCENET]: HLE/sceNetAdhoc.cpp:882 Socket error (32) when sending

This means that ppsspp cannot connect to that server right?
I have followed straightly to their instructions (expect using their build) and tried to connect to a Japanese server (provided in their discord), but of course failed. I also tried using VPN but it didn't work.
For reference: https://w.atwiki.jp/gundam-nextplus/pages/198.html. <-- Next Plus atwiki page, if you know Japanese.
https://github.com/LunaMoo/ppsspp/releases   <-- the build which they specified
They actually provided a pre-built exe file of that specific build, but I am using Mac. I tried to compile that build but failed(that is another topic already)

note: ppsspp can connect to www.myneighborsushicat.com

### What *should* happen?
ppsspp should not freeze, get pass the loading screen, and connect to the server.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
MacBook Pro, 2.3 GHz Dual-Core Intel Core i5, 8 GB 2133 MHz LPDDR3, Catalina 10.15.7, Intel Iris Plus Graphics 640 1536 MB.

**Comment by LunaMoo** [comment]
My build had a hack for that game, but it's supposed to not be requires anymore, try latest ppsspp from master(1.10.3 is NOT latest, it's just last release). I didn't really updated my branch from some time and builds are even older.

**Comment by 9tin9tin9** [comment]
Oh problem solved! Thank you!
