### ISSUE TITLE
Can add pull #7276 in latest version?

### ISSUE THREAD

**Issue by leoxxx** [hrydgard/ppsspp#13788]
https://github.com/hrydgard/ppsspp/pull/7276
https://forums.ppsspp.org/showthread.php?tid=16972
Find one version in up url, but it's too old.

**Comment by hrydgard** [comment]
This support already exists in the latest builds.

**Comment by leoxxx** [comment]
Which version?
I test 1.10.3-1258, but can't link and not found options.

**Comment by hrydgard** [comment]
If you're on Windows, just use File->Open new Instance. they will be able to play with each other.

**Comment by MojoJojoDojo** [comment]
use "localhost" and enable "built-in proadhocserver" in one or both PPSSPPs instances for it to work.

**Comment by hrydgard** [comment]
Right, should have mentioned that too, thanks. I'll add it to the FAQ on the site (damn, that needs updating....)
