### ISSUE TITLE
Graphic glitch in PSP2:IN & Nayuta no Kiseki (Vulkan/Android)

### ISSUE THREAD

**Issue by Saramagrean** [hrydgard/ppsspp#13782]
### What happens?
PSP2:IN & Nayuta no Kiseki show graphic glitch since v1.10.3-1191-g34efa1281, Vulkan only.

Phantasy Star Portable 2: Infinity.
![Screenshot_20201217-110509694](https://user-images.githubusercontent.com/26355472/102460824-21ab6300-407a-11eb-9a39-b2d1c593c937.jpg)
![Screenshot_20201217-110519898](https://user-images.githubusercontent.com/26355472/102460873-2ff97f00-407a-11eb-81ba-ae1e0e0f0eb5.jpg)

Nayuta no Kiseki.
![Screenshot_20201217-150233303](https://user-images.githubusercontent.com/26355472/102461154-97173380-407a-11eb-8e20-1976451c3757.jpg)
![Screenshot_20201217-150315244](https://user-images.githubusercontent.com/26355472/102461315-ca59c280-407a-11eb-8438-4ab4e5e87a6b.jpg)

### What *should* happen?
Graphic can render correct with Vulkan.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Redmi Note 8 (Snapdragon 665, Adreno 610, Ram 3, Android 10, Vulkan v1.1.128)

Dump from v1.10.3-1335.
[GE Dump.zip](https://github.com/hrydgard/ppsspp/files/5707875/GE.Dump.zip)

**Comment by Panderner** [comment]
Works fine for me for POCO M3 using Vulkan.
![Screenshot_2020-12-18-13-22-05-426_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/102578056-4532e400-4134-11eb-9d40-2bf66ef693e1.jpg)
![Screenshot_2020-12-18-13-22-44-535_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/102578059-482dd480-4134-11eb-9437-acc088346d2b.jpg)
![Screenshot_2020-12-18-13-21-51-588_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/102578069-4cf28880-4134-11eb-9886-0c5db373a470.jpg)
![Screenshot_2020-12-18-13-21-32-652_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/102578075-4ebc4c00-4134-11eb-816f-4c9d7d33c586.jpg)

**Comment by Panderner** [comment]
@Saramagrean have you tried unpatched iso for these games?

**Comment by hrydgard** [comment]
Doesn't look like an ISO patching bug to me. However I'm curious if you're using the very latest builds?

**Comment by Panderner** [comment]
I'm using latest build of PPSSPP (v1.10.3-1339-g738d9c81d)

**Comment by hrydgard** [comment]
Alright, thanks for the info.

**Comment by Saramagrean** [comment]
Okay, this problem it cause by driver bug.

I use custom driver from here https://forum.xda-developers.com/t/driver-10-0-adreno-600-series-opengl-vulkan-drivers-v-0481-0-1-1-128.4089967/

After restore to original driver (Vulkan v1.1.87) graphic can rendering correct with Vulkan backend.

So I closing, sorry for wasting your time. 😂
