### ISSUE TITLE
"Change Pro Adhoc server IP address" doesn't let you enter a DNS name on iOS

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#13790]
It's only possible to enter digits, which is not ideal.

**Comment by ANR2ME** [comment]
Yeah, i only added the "Edit" button for Android since i don't have iOS to test with.

**Comment by MojoJojoDojo** [comment]
Wanna add to that is that on Linux you cant use the "Toggle List" button to get private IPs about your network including VPN IP addresses. (running as sudo won't help).
It works on every other OS as far as I can tell.

**Comment by hrydgard** [comment]
I'm merging this into #13716
