### ISSUE TITLE
[Vulkan] Intense Flickering in WWE Smackdown vs. RAW 2006

### ISSUE THREAD

**Issue by meowthed** [hrydgard/ppsspp#13797]
### What happens?
Screen constantly flickers in-game.

### What *should* happen?
It should not flicker at all. this issue doesn't persist in OpenGL

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
NVIDIA Geforce 740m
Windows 10 x64
v1.10.3-1359-gaa2f102a0

* Tested with a Redump-verified ISO.

**Comment by sum2012** [comment]
Not sure Frame dump useful or not,
[recording.zip](https://github.com/hrydgard/ppsspp/files/5720833/recording.zip)

 v1.10.3-1359-gaa2f102a0 
Info log: https://gist.github.com/sum2012/a5f798786c4599550faee6171bb2acf4
media log: https://gist.github.com/sum2012/7ab91266b34848d2a2fe96019f03893d

@hrydgard From Info Log: 
22:53:424 WWESMACKDOWN E[JIT]: jitcommon\jitstate.h:166 S: unknown  (000000e4 0)
22:53:424 WWESMACKDOWN E[JIT]: jitcommon\jitstate.h:166 T: unknown  (000000e4 0)
22:53:424 WWESMACKDOWN E[JIT]: jitcommon\jitstate.h:175 D: unknown (00000000 0)

**Comment by hrydgard** [comment]
Is this new? Happened in 1.10.3?

**Comment by sum2012** [comment]
v1.7.3 also have problem

**Comment by hrydgard** [comment]
Oh, okay. I might let this slide to 1.12 then, I have enough issues already and I want to get 1.11 out soon... Still, not good.

**Comment by Panderner** [comment]
Screen flickering issue also affects Direct3D 11.

**Comment by Gamemulatorer** [comment]
Vulkan flickering the whole screen

https://user-images.githubusercontent.com/37603562/134391326-2481cd19-4c95-40b1-92b9-647c93e23fcb.mp4

OpenGL flickering the audience only but I notice that if I minimize ppsspp and go back to the emulator fixes this issue 🤔

https://user-images.githubusercontent.com/37603562/134391479-6024ce2e-00a4-4414-86a8-ff563d784d42.mp4

ge dump
[vulkan.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/7212641/vulkan.ppdmp.zip)
[opengl.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/7212644/opengl.ppdmp.zip)

**Comment by Gamemulatorer** [comment]
@meowthed how about this now? still an issue.

**Comment by meowthed** [comment]
yeah it's still an issue.

**Comment by Gamemulatorer** [comment]
How about in in the latest build
https://buildbot.orphis.net/ppsspp/

**Comment by Gamemulatorer** [comment]
***SplitFramebufferMargin*** can fix the flickering 🎉

**Comment by Gamemulatorer** [comment]
@Panderner can you test on your devices?

**Comment by hrydgard** [comment]
@Gamemulatorer wow that's surprising! Going to have to look into this properly at some point..

**Comment by Gamemulatorer** [comment]
> @Gamemulatorer wow that's surprising! Going to have to look into this properly at some point..
> 
> Do all the graphics look correct with that?

The intense flickering is gone and also performance is a bit improve but still there's a minor graphics error that happens both software and hardware mode.

Hardware:
![Screenshot_2022-09-14-17-19-36-32](https://user-images.githubusercontent.com/37603562/190116541-c2fb24e4-ca3e-41b7-abba-718d25a21c96.png)

Software:
![Screenshot_2022-09-14-17-23-30-99](https://user-images.githubusercontent.com/37603562/190116653-f322bdd1-8dfe-45f1-9816-b606456f8023.png)

**Comment by Gamemulatorer** [comment]
What's the plan for this?
SplitFramebufferMargin can't be a good workaround for this game?

**Comment by hrydgard** [comment]
Turns out a newer compat setting did the trick here - really don't want to merge one of the mini render targets rendered in the margin of one of the main framebuffers with that big framebuffer, bad things happen. See #18009 .

**Comment by leviskata** [comment]
WWE SmackDown vs. RAW 2007 is suffering from the same thing.
Will u also fix that?
