### ISSUE TITLE
[UI Glitch] Inavalid Access Error Appearance collapses.

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#13808]
### What happens?
The Text on Text!

![image](https://user-images.githubusercontent.com/48179091/103056391-3048cb80-45e0-11eb-8b37-22d1dd4a1b57.png)

**Comment by sum2012** [comment]
Where is the game crash ?

**Comment by sum2012** [comment]
I get it now , Lang change to Japan  will crash the game

**Comment by sum2012** [comment]
v1.10.3-1382-gb40385396 
bad japan log:
https://gist.github.com/sum2012/da0eeeafa47bec7556bc59ba81e053d8
good -english log:
https://gist.github.com/sum2012/bc98c0222aa43d02c716b1ea3f87831d

**Comment by hrydgard** [comment]
Thanks, I'll fix the layout. Dunno about the crash though :)

**Comment by nassau-tk** [comment]
@sum2012 

> v1.10.3-1382-gb40385396
> bad japan log:
> https://gist.github.com/sum2012/da0eeeafa47bec7556bc59ba81e053d8
> good -english log:
> https://gist.github.com/sum2012/bc98c0222aa43d02c716b1ea3f87831d

Is this for #12730 ?

**Comment by sum2012** [comment]
@nassau-tk  Yes
