### ISSUE TITLE
L3R3 doesn’t work on iOS build

### ISSUE THREAD

**Issue by DamnBoi706** [hrydgard/ppsspp#13805]
L3R3 doesn't seem to work on PPSSPP iOS i can't map to anything (in control setting) it won't register and if you ask about compatibility yes iOS does support L3R3 on 12.1 or later and there nothing wrong with my controller L3R3 work just fine in games

**Comment by hrydgard** [comment]
Is L3/R3 the same as pushing the sticks in?

**Comment by DamnBoi706** [comment]
Yes
