### ISSUE TITLE
Gripshift crashes a lot

### ISSUE THREAD

**Issue by eltomas2003** [hrydgard/ppsspp#13801]
### What happens?
It randomly crashes when selecting continue stage during gameplay.

### What *should* happen?
It should continue onto the next stage

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Ryzen 5 3500u with vega graphics, windows 10, 
ppsspp 1.10.3

**Comment by Panderner** [comment]
Duplicate of #7601

**Comment by hrydgard** [comment]
Yeah unfortunately this game still doesn't run well.
