### ISSUE TITLE
[Feature Request] Default enable USING_GLES2 for arm linux

### ISSUE THREAD

**Issue by catsout** [hrydgard/ppsspp#13815]
``` cmake
if(NOT ANDROID AND NOT IOS) 
	 if(ARM_DEVICE OR SIMULATOR)
		set(USING_EGL ON)
+              set(USING_GLES2 ON)
	endif()
endif()
```

**Comment by hrydgard** [comment]
I don't know, I'm sure this fixes some devices but probably not appropriate for all? 

We should probably dynamically handle the distinction inside the emulator instead at some point...
