### ISSUE TITLE
PPSSPP-iOS Buildbot issue

### ISSUE THREAD

**Issue by DamnBoi706** [hrydgard/ppsspp#13823]
the latest version of PPSSPP (1.10.3-1399) (iOS) is only available in dev file which only usable for jailbroken device can you fix it pls it used to have the ipa file which work on any device without need to jailbreak but now it disappeared from https://p.xx.wtf I know It might be the bot issue but pls fix it

**Comment by hrydgard** [comment]
Not sure what the issue might be. That site is run by @W-MS by the way, not by the project (but appreciated!)

**Comment by DamnBoi706** [comment]
Yeh I think it wasn't the issue on your side also but I'm reporting it anyway

**Comment by DamnBoi706** [comment]
But should I report the issue to their GitHub instead?

**Comment by W-MS** [comment]
Currently working on it.

**Comment by DamnBoi706** [comment]
Thank for replying i didn't expect that

**Comment by W-MS** [comment]
I've paused the buildbot and reverted the version to 1.10.3-1380.  This issue could be closed now.
The reason here #13824 .

**Comment by hrydgard** [comment]
I reverted it, you should be able to resume your buildbot now.

**Comment by W-MS** [comment]
v1.10.3-1400-gc4d6c1972 built successfully.
