### ISSUE TITLE
TALES OF PHANTASIA ULJS00079 video don't auto close to return menu

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#13820]
Last work v1.10.3-1055-gee11f6af7
log: https://gist.github.com/sum2012/cabc6ff0f25bb31c5fa4d945a2697111

edit2:Need Retest,Sorry

PPSSPP v1.10.3-1395-g1ba290a45 Windows 64 bit bad log:
https://gist.github.com/sum2012/3800cd2099c45d46b5d7e82c13e3d85e

**Comment by sum2012** [comment]
Redo again
Last work  v1.10.3-1218-g1e5e0e20d
First bad v1.10.3-1220-g5c4a227b7
That mean @shenweip 
https://github.com/hrydgard/ppsspp/pull/13673

 v1.10.3-1218-g1e5e0e20d log: https://gist.github.com/sum2012/68949857460f8e74cd44a9e74c6d8a2b 
 v1.10.3-1220-g5c4a227b7 log: https://gist.githubusercontent.com/sum2012/09c718746add4e47eceeabb9758ac9d6/raw/977f4eb547f7f858266a3ae31e0bdb7b63cb1847/gistfile1.txt
v1.10.3-1395-g1ba290a45 log:  https://gist.githubusercontent.com/sum2012/3b9dcde92cdcbc40f6fd0b85e59e4442/raw/e5621abb1dbfbb089b2619d3142a057784c29293/gistfile1.txt

**Comment by shenweip** [comment]
Well, could you make a JpcspTrace to log out the return value of `sceMpegRingbufferPut`? That will be useful,thanks.

**Comment by sum2012** [comment]
I cannot log sceMpegFinish.,Not sure ok
https://gist.githubusercontent.com/sum2012/872194fea4e4b4d151c753f5ca4827cc/raw/4ad880a9cb9ac07bb55358b33e389b3466b3f911/gistfile1.txt

**Comment by shenweip** [comment]
Great! I get some point to fix now.

**Comment by sum2012** [comment]
Great @shenweip 
v1.10.3-1402-g8bc1f3ee9-windows-amd64 log:
https://gist.githubusercontent.com/sum2012/6dfb92cb1232a1ef0f030d207d9e833d/raw/48c0cd5526852c4f33d1fdc73eb14b32f3e32740/gistfile1.txt

Hope do not have any regression of other games.
