### ISSUE TITLE
WWE SmackDown vs. RAW 2006 2D Crowds flickering in OpenGL

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#13822]
There's a bug in WWE SvR 2006 where the 2d crowds are flickering in OpenGL.
![103162383-e99ae180-482a-11eb-86be-87c58bb77ba9](https://user-images.githubusercontent.com/37503397/103169998-ab79de00-487b-11eb-9be8-a668549c58f6.gif)

**Comment by hrydgard** [comment]
Hm, you don't need to make a new issue, we already have #13797.

**Comment by Panderner** [comment]
but it's different issue in vulkan it's entire screen flickers

**Comment by hrydgard** [comment]
Oh, sorry, you are right. Might be related but I'll reopen.

**Comment by sum2012** [comment]
@Panderner You need make a frame dump to let @hrydgard debug
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

**Comment by Panderner** [comment]
Here's a GE Dump:
[dump.zip](https://github.com/hrydgard/ppsspp/files/5745581/dump.zip)

**Comment by unknownbrackets** [comment]
Did this start happening recently?  If you try the builds in #13941 (click Checks tab -> Artifacts in top right -> download whichever you want), does it still happen?

If not, does this happen with default settings (including block transfer on, buffered rendering on, vertex cache off, etc.?)

-[Unknown]

**Comment by hrydgard** [comment]
Since it's flickering, can you take a pair for framedumps, one where the audience is visible, and one where it's not? Might need to compare things.

**Comment by Gamemulatorer** [comment]
No flickering using your ge dump 🤔
![Screenshot_2021-05-07-09-02-56-497_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/117383348-2c747080-af13-11eb-9a13-d733e49fc957.jpg)
No feedback @Panderner

**Comment by Panderner** [comment]
> No flickering using your ge dump 🤔
> ![Screenshot_2021-05-07-09-02-56-497_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/117383348-2c747080-af13-11eb-9a13-d733e49fc957.jpg)
> No feedback @Panderner

Can you test this game instead of GE Dump?

**Comment by Gamemulatorer** [comment]
This game is super lag on my Redmi Note 9 using OpenGL backend with lots of graphics flickering while on Vulkan the game is smooth but also have a dark overlay flickering.

**Comment by Panderner** [comment]
@Gamemulatorer can you please check your frame rate?

**Comment by Gamemulatorer** [comment]
In PPSSPP v1.0 this game is smooth on OpenGL backend with less graphics issue
![Screenshot_2021-05-08-12-06-41-550_org ppsspp ppssppgold](https://user-images.githubusercontent.com/37603562/117526180-fcea6480-aff5-11eb-8f8a-5f467255b396.jpg)
![Screenshot_2021-05-08-12-06-26-894_org ppsspp ppssppgold](https://user-images.githubusercontent.com/37603562/117526182-01af1880-aff6-11eb-9840-03d8d2b34f20.jpg)

**Comment by Panderner** [comment]
> In PPSSPP v1.0 this game is smooth on OpenGL backend with less graphics issue
> ![Screenshot_2021-05-08-12-06-41-550_org ppsspp ppssppgold](https://user-images.githubusercontent.com/37603562/117526180-fcea6480-aff5-11eb-8f8a-5f467255b396.jpg)
> ![Screenshot_2021-05-08-12-06-26-894_org ppsspp ppssppgold](https://user-images.githubusercontent.com/37603562/117526182-01af1880-aff6-11eb-9840-03d8d2b34f20.jpg)

Did you mean the latest builds? @Gamemulatorer

**Comment by Panderner** [comment]
Crowds Flickering also in Direct3D 9.

**Comment by benderscruffy** [comment]
Is this still a problem ??

**Comment by Gamemulatorer** [comment]
***SplitFramebufferMargin*** can also fix this issue 🎉

https://user-images.githubusercontent.com/37603562/190021310-6c9d55a1-5db8-4753-8662-25dc9bf3cf33.mp4

**Comment by hrydgard** [comment]
Should be fixed by #18009 .
