### ISSUE TITLE
[Android 11][Sdcard] Android 11 is can't find the SDcard.

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#13827]
### What happens?
My Galaxy S20 is updated to **Android11** a few days ago.

The problem has coming after format & remount the SDcard.
Then PPSSPP can't be find the SDcard.
Is this a specification of Android11's isn't it?
(I inspected about the problem.Maybe,right.)

**Is it possible that PPSSP get an access right?**

Maybe,Related #10199 .
But, This issue should not left to future.

### What *should* happen?
Access to SDcard correctly.

**Comment by nassau-tk** [comment]
Please, Tell me If there is any idea for avoidance the problem.

**Comment by nassau-tk** [comment]
Maybe, Name of SDcard will change per format.
It's not fixed name.
So, Best countermeasure is getting PPSSPP acquires a right of access.

I don't have a knowledge of any programming but I found the info.
I paste the URL for reference.
https://takusan23.github.io/Bibouroku/2020/04/19/Android11-DP2-%E3%81%A7%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E4%BF%9D%E5%AD%98%E3%81%BE%E3%81%A8%E3%82%81/

**Comment by nassau-tk** [comment]
By the way, when preserving a apk file of PPSSPP in on-chip memory, it can be installed, but when I try to preserve and install in SDCARD, it'll be an error, and it can't be installed.

**Comment by jcchikikomori** [comment]
> Maybe, Name of SDcard will change per format.
> It's not fixed name.
> So, Best countermeasure is getting PPSSPP acquires a right of access.
> 
> I don't have a knowledge of any programming but I found the info.
> I paste the URL for reference.(Sorry,Japanese.
> )
> https://takusan23.github.io/Bibouroku/2020/04/19/Android11-DP2-%E3%81%A7%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E4%BF%9D%E5%AD%98%E3%81%BE%E3%81%A8%E3%82%81/

I kinda gets your point. Maybe we should have the option to regain access to SDCard, since this will be a velocity issue to all Android 10 ones that are available to upgrade for 11

**Comment by nassau-tk** [comment]
Yes, I thought so too.
But, Sorry I couldn't find it on device setting.
And, I have installing kind of  2 filemanager app.
One of app is missing SDcard root. (It can't apper in the menu.)
Other app is appear the SDcard but It can access only limited folders.

**Comment by nassau-tk** [comment]
I keep wishing that this is my misunderstanding.....

**Comment by unknownbrackets** [comment]
This is probably #11997.  The solution will likely be a somewhat confusing mess.  Welcome to the future of Android.

-[Unknown]

**Comment by nassau-tk** [comment]
Oops.....
I didn't also think that the latest device was a hellish entrance....
(I'll sit down here until the time is coming. Quietly...):scream:

**Comment by nassau-tk** [comment]
I got avoidance by manually.
This is only respecification of a folder of ROM.
I don't use memorystick save  on Sdcard.

1 Open "Chrome".
2 Open "Setting".
3 Open "Download".
4 Tap the "Place of Download folder".
5 Change to the "SDcard".
6 See the path of stoarge/xxxx-xxxx/~~~~~ and memo it.
7 Open PPSSPP.ini and rewrite to the ""CurrentDirectory = /storage/xxxx-xxxx/".
8 Save it.

Open PPSSPP and tap "GAME List".
It will open the SDcard root directory.

xxxx-xxxx is different per user.

**Comment by unknownbrackets** [comment]
Ah, okay, not quite all of #11997 then - just that the sd card folders are no longer listable, sounds like.

-[Unknown]

**Comment by nassau-tk** [comment]
Yes,I see.
But, The light user will confuse by it. (like me):sweat:

**Comment by nassau-tk** [comment]
should I close this topic??

**Comment by ANR2ME** [comment]
btw @nassau-tk After upgrading to Android 11 when you launched PPSSPP for the first time, did it ask for storage access?
As i remembered some app need to have their permission to be revoked (ie. through App Info) after upgrading Android in order to work properly.

**Comment by nassau-tk** [comment]
@ANR2ME 

No, I was not asked accept for access from device.

**Comment by hrydgard** [comment]
Yeah the #11997 problem doesn't strike yet since I have requested the old behavior through AndroidManifest.xml - the hammer drops on Android 12 which will ignore that request.

However it does seem that Android 11 starts locking down a few things, and separate SD cards in addition to the "external memory" have always been annoying and badly supported through Android file systems...

**Comment by hrydgard** [comment]
If anyone know working paths to their SD cards, feel free to report them here. I'm thinking of making a button that tries a few common paths and see if we can access them...

**Comment by unknownbrackets** [comment]
I think the problem is that it generates a random string or something after /storage/....

-[Unknown]

**Comment by ANR2ME** [comment]
If we only need to get the hexadecimal Sdcard's Volume ID (ie. xxxx-xxxx) on `storage/xxxx-xxxx/` can't we just extracted it from `myappcontext.getExternalCacheDirs()` like this? https://stackoverflow.com/questions/50132764/getting-the-path-to-sd-card/50211328

**Comment by nassau-tk** [comment]
My using Comic Viewer can be selecte the Internal & External(SD) root dir.
["Perfect Viewer"](https://play.google.com/store/apps/details?id=com.rookiestudio.perfectviewer)

The way to avoidance is there. But I don't have a knowledge...

![Screenshot_20210105-163005_Perfect Viewer](https://user-images.githubusercontent.com/48179091/103619378-f3cc8680-4f74-11eb-957b-78029947b6b2.jpg)

![Screenshot_20210105-163020_Perfect Viewer](https://user-images.githubusercontent.com/48179091/103619460-24acbb80-4f75-11eb-9833-17da54b16dd7.jpg)


![Screenshot_20210105-164010_Perfect Viewer](https://user-images.githubusercontent.com/48179091/103619402-ff1fb200-4f74-11eb-9895-d21f8c2567b5.jpg)

**Comment by hrydgard** [comment]
@nassau-tk , now that #13885 is merged, can you try and see if the new SD card button shows up on the game browser, and if it works for you?

**Comment by nassau-tk** [comment]
@hrydgard 

OMG.
It's can't work on my phone.
Even a splash screen isn't indicated.

v1.10.3-1507 & 1509 both.

**Comment by hrydgard** [comment]
Wait, what? It doesn't even start anymore?

I'll try on my Pixel which has Android 11...

**Comment by hrydgard** [comment]
OK, I've fixed the crash, but I suspect you still won't be able to see the SD card..

**Comment by hrydgard** [comment]
Unfortunately I don't have any phones that both have Android 11 and an SD card slot... I'm thinking of getting an S21 but only the Ultra model will have SD it seems, and otherwise I don't really want the Ultra one. Argh...

**Comment by Tanari-de** [comment]
> 
> 
> @hrydgard
> 
> OMG.
> It's can't work on my phone.
> Even a splash screen isn't indicated.
> 
> v1.10.3-1507 & 1509 both.
> 
> If revert to v1.10.3-1496 then working.

Same Problem on Poco X3 with CrDroid Android 11: v1.10.3-1496  is the last working Version. I also have (or better: had) the problem with no access to my ROMS on the external SD, but since editing the ini file i can access the external SD Card.

Anyway, a working SD-Card Button in PPSSPP would be nice :-)

**Comment by hrydgard** [comment]
1510 will get things back to working, but I'm still looking for a reliable way to programmatically get the SDCARD path. Google is intentionally making it difficult, which annoys me.

**Comment by Tanari-de** [comment]
> 
> 
> Unfortunately I don't have any phones that both have Android 11 and an SD card slot... I'm thinking of getting an S21 but only the Ultra model will have SD it seems, and otherwise I don't really want the Ultra one. Argh...

Using a rooted Poco X3 with SD Card and Android 11 here. Let me know if i can help somehow..

**Comment by nassau-tk** [comment]
(^o^;) Um... It's not smart choice.(About S21 Ultra)
If you want test about like a it then I will help anytime.  (^v^)b

**Comment by hrydgard** [comment]
I could make a silly workaround that lets you manually put the path to your SD card in the ini file, and it will then assign that to the button...  But it will only help very technical users like you guys :)

**Comment by nassau-tk** [comment]
> I could make a silly workaround that lets you manually put the path to your SD card in the ini file, and it will then assign that to the button... But it will only help very technical users like you guys :)

When my memory is right.
Probably, I laughed most in "this year".:satisfied:

**Comment by nassau-tk** [comment]
OK.

I tested v1.10.3-1510.
Ahhh....Where is SD button???

**Comment by hrydgard** [comment]
Yeah, I guess my solution doesn't work on Android 11 :(   It does work on Android 10 and below.

I have some more ideas to try. There's something called the Intent.ACTION_OPEN_DOCUMENT_TREE which pops up a system folder browser. Not sure if it will allow choosing the SD card on Android 11, but I'm gonna try to implement support.

**Comment by nassau-tk** [comment]
https://qiita.com/wa2c/items/6e085d1cd1daffb3b632

If you can translate from Japanese to your lang.

**Comment by Tanari-de** [comment]
Lemuroid does access the external SD-Card in the following way: If you select the "Directory" Button in that App it does start the android file manager and in that file manager i can select the external SD Card. Maybe this is a solution for PPSSPP also?

The standard Android File Manager is named "Dateien" on my german device, i guess its "Data" on english ones?

**Comment by hrydgard** [comment]
Yeah, that's the solution I'm thinking of implementing now. Maybe even, if the path looks like it's to an SD card, just save the beginning of the path and map it to the SD card button from there on.

**Comment by hrydgard** [comment]
Experimenting with OPEN_DIRECTORY_TREE, I get a path that looks like this on my Android 10 device when picking the root of an SD card:

`content://com.android.externalstorage.documents/tree/134A-DCC9%3A`

That does contain 134A-DCC9, so we could guess that the correct path is /storage/134A-DCC9. The alternative is probably to use Java Android Storage Framework APIs from there on out, which will be a pain (but will be required anyway for #11997 ).

I'll also look at how Lemuroid does it.

Might end up with a hacky way for 1.11 and more "proper" methods later.

**Comment by unknownbrackets** [comment]
`EXTRA_LOCAL_ONLY` looks at least somewhat interesting, I didn't realize that exists.  That might make the "guess again, idiot" problem much better than I expected (though likely not eliminate it.)

-[Unknown]

**Comment by hrydgard** [comment]
With #13898 merged, there should now be a working Browse... button that lets you select the SD card if you wish.

Let me know if it works on Android 11!

**Comment by nassau-tk** [comment]
@hrydgard 

No,l can't select the SD...

**Comment by hrydgard** [comment]
What happens when you do? Do you see anything in the log?

**Comment by hrydgard** [comment]
Huh, on my Android 10 phone, it looks quite different, I have a choice of the SD card there...

**Comment by hrydgard** [comment]
I wonder how your comic viewer is working...

**Comment by nassau-tk** [comment]
oh!!!
sorry!!!
I misstook the tap!!

It can work!!!

**Comment by hrydgard** [comment]
Great! And it works to play games from it?

**Comment by nassau-tk** [comment]
Yes!!!
I can play the game from SD!

You got it!!

**Comment by nassau-tk** [comment]
Thank you every one!!
