### ISSUE TITLE
Insufficient Storage for Street Fighter Alpha 3 Max

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#13829]
Even I have 32+ GB of free storage for my phone Street Fighter Alpha 3 Max displays insufficient storage
![Screenshot_2020-12-28-19-01-49-232_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/103210053-8cdd1b00-493f-11eb-9471-3d3dd9e519a3.jpg)

**Comment by shenweip** [comment]
How about increasing simulated memory stick size by "System->Change Memory Size"?

**Comment by LunaMoo** [comment]
This game has a bug(NOT an emulation bug) and doesn't recognize large memsticks. It was added to compat.ini for a hack that should intentionaly reduce visible memstick size/free space, so either it doesn't work anymore or you have different gameID.

**Comment by hrydgard** [comment]
Can you check the gameid of your copy? ULUS/ULES... etc

**Comment by Panderner** [comment]
> How about increasing simulated memory stick size by "System->Change Memory Size"?

Even I changed the memory stick size to 1 GB still happens

**Comment by Panderner** [comment]
> Can you check the gameid of your copy? ULUS/ULES... etc

I'm using ULUS10062

**Comment by shenweip** [comment]
Well, so I guess your SAVEDATA folder is larger than 1GB?

**Comment by Panderner** [comment]
When the SAVEDATA folder below 1GB: Works
![Screenshot_2020-12-29-14-49-08-402_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/103264221-0a0e9b80-49e5-11eb-8f17-01e65dad8f98.jpg)

When the SAVEDATA folder exceeds 1GB: insufficient storage appear
![Screenshot_2020-12-28-19-01-49-232_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/103264274-30ccd200-49e5-11eb-9a34-89fbdd3d12ae.jpg)

**Comment by hrydgard** [comment]
Huh, seems we didn't consider the case of SAVEDATA being that large. This will take some more logic in the hack I guess...

**Comment by Unknow0059** [comment]
> How about increasing simulated memory stick size by "System->Change Memory Size"?

I had this issue with Coded Arms and it resolved.
