### ISSUE TITLE
[Android][Vulkan] Gun Showdown

### ISSUE THREAD

**Issue by MiguelCardonaG** [hrydgard/ppsspp#13825]
### What happens?

Hello! 

When the character approaches a building or tree and you lift the camera in a slightly different position, a graphic error appears. Like this:

![IMG_20201227_182224](https://user-images.githubusercontent.com/65356692/103176257-8cc21a00-4870-11eb-9896-402739f3f665.jpg)

I just found out by chance, I ranked under a tree and lifted up the camera and that came out.

### What *should* happen?

Let it look "bonito" 😉

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Samsung Galaxy Note 10 Plus Exynos.
ppsspp-v1.10.3-1400-gc4d6c1972-android.apk

I have had to install Samsung's web browser to be able to dump the file, I hope it is correct and I was wrong.

[ULES00484_0001.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/5744870/ULES00484_0001.ppdmp.zip)

**Comment by MiguelCardonaG** [comment]
Oh!! I forgot to comment that if you switch to "jump bufer effects" that doesn't happen.

**Comment by unknownbrackets** [comment]
This looks fine on Windows, so it may be Mali specific or may require dual source blending or something.  There is some blur/bloom happening in the sky in that area which might be related, and alpha/stencil seems to matter.

-[Unknown]

**Comment by hrydgard** [comment]
Is there a difference between Vulkan and OpenGL here?

Lack of dual src blending support seems like a likely cause if it works on Adreno for example .. Mali still doesn't support it while the other mobile GPU vendors now generally do.

**Comment by Panderner** [comment]
I can't produce graphical glitches for me using POCO M3 in Vulkan.

**Comment by MiguelCardonaG** [comment]
> Is there a difference between Vulkan and OpenGL here?
> 
> Lack of dual src blending support seems like a likely cause if it works on Adreno for example .. Mali still doesn't support it while the other mobile GPU vendors now generally do.

I've tried it again (now on Android 11) and the same thing happens.

![Screenshot_20210209-174617_PPSSPP](https://user-images.githubusercontent.com/65356692/107399277-d012d800-6b00-11eb-86fd-e15eb6a80e64.jpg)

**Comment by Panderner** [comment]
@MiguelCardonaG can you send me the video?

**Comment by Gamemulatorer** [comment]
> ![Screenshot_2021-10-19-01-52-32-363_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/137782532-5910e602-53e6-4e38-a27f-c73c3f2a613d.jpg) [gun_showdown.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/7367536/gun_showdown.ppdmp.zip)
> 
> **Issue still present on v1.12.2**

I can no longer reproduce this issue on my phone 🎉
![Screenshot_2022-07-22-23-35-51-842_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/180474200-d41c9a36-db91-4041-a08b-cc0e48faeb71.jpg)

**Comment by unknownbrackets** [comment]
This was probably the Mali bug then.  Thanks for confirming.

-[Unknown]
