### ISSUE TITLE
OpenGL post shader error

### ISSUE THREAD

**Issue by Lemoncak3** [hrydgard/ppsspp#13839]
i am using 1404 build and when i switch from vulkan to openGL in the top screen there is text "post shaders error see log details" and my entire post shader will be disabled. It works in vulkan though and in previous version i don't know remember when it works too in OpenGL 

Now it works when i switch from vulkan to openGL but my other handphone that didn't support vulkan still have this error. Could you look into it? I can't produce it anymore on my max pro M2 but in my other phone it still have this error.

Update : After clear running program i opened ppsspp in openGL setting and it appears again. Aparently after i using vulkan and switch to openGL it could repair it temporarily. But when i closed the running program and opened it again in openGL it appears again.

![Screenshot_20201230-093532](https://user-images.githubusercontent.com/67026697/103326366-991dc100-4a82-11eb-83fa-59b05cfeceec.png)

**Comment by Panderner** [comment]
you need to reset the settings to default

**Comment by Lemoncak3** [comment]
I have reset to default the error still there.

**Comment by nassau-tk** [comment]
What?

The issue was solved by #13779 wasn't it?
I'm using v1.10.3-1413.
But, The issue is not happen.

**Comment by hrydgard** [comment]
Yeah, that should have fixed it, but maybe there's some more case?

Can you post the ADB log? 

(I'm also gonna make it show more information on-screen...)

**Comment by Lemoncak3** [comment]
I am using android and don't know where the log is. I am using the latest build 1417 but still have same error.
![Screenshot_20201231-160806](https://user-images.githubusercontent.com/67026697/103404840-99ec4b00-4b87-11eb-9eab-71689c7d16e2.png)
![Uploading Screenshot_20201231-160822.png…]()
![Screenshot_20201231-160750](https://user-images.githubusercontent.com/67026697/103404848-9fe22c00-4b87-11eb-9536-297eb6d34a51.png)

**Comment by nassau-tk** [comment]
Oh, I could reproduce it.
The trigger is "Task Kill".
If kill the task after seted "OpenGL" then appear the shader error when next boot PPSSPP.

Sorry, l can't get log now.

**Comment by Panderner** [comment]
@Lemoncak3 Can you find where the last build worked?

**Comment by Lemoncak3** [comment]
Sorry @Panderner i forgot which version before worked since i update from github regularly and just notice now when i switch to OpenGL

**Comment by Lemoncak3** [comment]
I am using the latest one and now the error shows explanation like this, hope this helps since i can't give log of my ppsspp
![Screenshot_20210105-050850](https://user-images.githubusercontent.com/67026697/103584711-6bb69480-4f14-11eb-9079-3df94fd51824.png)

**Comment by hrydgard** [comment]
I was able to reproduce this yesterday but then suddenly wasn't. I think there's something really weird going on...

Either way, I'm gonna try to improve the displayed error message, I think.

**Comment by Lemoncak3** [comment]
I am able to reproduce it though, first my backend was openGL so i changed it to vulkan and the error vanished. Then i changed back to openGL, exit from PPSSPP and then kill the process of PPSSPP after that reopened the PPSSPP and the error will show up again.

**Comment by nassau-tk** [comment]
@hrydgard 

1. Start PPSSPP.
2. Set OpenGL.
3. Finish PPSSPP.
4. Kill the background task of PPSSPP.
5. Re-start PPSSPP & game.

If you use Vulkan then error massage will not appear when switch to OpenGL.

**Comment by Lemoncak3** [comment]
Okay thank you will wait for the next android build
