### ISSUE TITLE
[Android] OpenGL crash

### ISSUE THREAD

**Issue by LanceReborn** [hrydgard/ppsspp#13836]
### What happens?
When I use OpenGL the games crash And the emulator closes

### What *should* happen?
Games should go normal without crashing

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Samsung A01

Dimensions: 70.86 x 146.3 x 8.34 mm

SoC: Qualcomm Snapdragon 439 CPU: 4x 1.95 GHz ARM Cortex-A53, 4x 1.45 GHz ARM Cortex

A53, Cores: 8

GPU: Qualcomm Adreno 505, 650 MHz

RAM: 2 GB, 933 MHz

Storage: 32 GB

Memory cards: microSD, microSDHC, microSDXC

Display: 5.7 in, TFT, 720 x 1560 pixels, 24 bit Battery: 3000 mAh, Li-Ion

OS: Android 10

Camera: 4160 x 3120 pixels, 1920 x 1080 pixels, 30 fps

SIM card: Nano-SIM

Wi-Fi: b, g, n, Wi-Fi Hotspot

USB: 2.0, Micro USB

Bluetooth: 4.2

Positioning: GPS, A-GPS, GLONASS

PPSSPP versión:1.10.3

### Other information
The reason I use openGL is because it has less lag than vulkan i was playing kingdom hearts when i got to the first boss with aqua when the boss hit me the screen started to flicker and the emulator crashed.
I was playing dissidia 012 with kuja when I made an attack the game crashed instantly, I think it was a random OpenGL crash because other times it crashed out of nowhere.
I think other games crash too but I don't know because I don't have them
Sorry but can't put pictures I deleted kingdom Hearts and I don't know how to recreate it in dissidia 012

**Comment by Panderner** [comment]
@LanceReborn have you tried latest builds of PPSSPP?

**Comment by LanceReborn** [comment]
> @LanceReborn have you tried latest builds of PPSSPP?

you mean the latest version? yes 1.10.3

**Comment by Panderner** [comment]
> > @LanceReborn have you tried latest builds of PPSSPP?
> 
> you mean the latest version? yes 1.10.3

Do you mean the latest builds of PPSSPP. Download latest builds of PPSSPP here: https://buildbot.orphis.net/ppsspp/index.php?m=fulllist

**Comment by LanceReborn** [comment]
> > > @LanceReborn have you tried latest builds of PPSSPP?
> > 
> > you mean the latest version? yes 1.10.3
> 
> Do you mean the latest builds of PPSSPP. Download latest builds of PPSSPP here: https://buildbot.orphis.net/ppsspp/index.php?m=fulllist

I tried but it says it couldn't install

**Comment by LunaMoo** [comment]
You need to uninstall the version from the store first since they're signed differently and can't co-exist.

**Comment by LanceReborn** [comment]
Now that I tried this build it seems that it is solved Thanks!
