### ISSUE TITLE
Text upscaling issue in Brave Story - New Traveler (US)

### ISSUE THREAD

**Issue by Tiberius1437** [hrydgard/ppsspp#13844]
Vulkan at native resolution

![Capture](https://user-images.githubusercontent.com/68873449/103417922-cb453500-4be0-11eb-9d2c-f8a9b2a4899a.PNG)

Vulkan at x4. Notice the black lines in between the dots?

![Capture2](https://user-images.githubusercontent.com/68873449/103417929-d7c98d80-4be0-11eb-852b-712a630d00ec.PNG)

**Comment by Panderner** [comment]
@Tiberius1437 OpenGL?

**Comment by hrydgard** [comment]
This is the same old issue with rendering games at higher resolutions that are not ready for it, that we've seen a gazillion times before.

It's not really fixable other than running 1:1 or possibly using texture upscaling.

**Comment by Tiberius1437** [comment]
Sorry.

**Comment by hrydgard** [comment]
no need to be sorry.
