### ISSUE TITLE
error: ‘glGetError’ was not declared in this scope

### ISSUE THREAD

**Issue by dicotom** [hrydgard/ppsspp#13840]
When compiling ppsspp under odroid xu4 -> RetroPie, it fails with error:

/home/odroid/RetroPie-Setup/tmp/build/lr-ppsspp/ppsspp/Common/GPU/OpenGL/GLDebugLog.cpp: In function ‘bool CheckGLError (const char*, int)’:
/home/odroid/RetroPie-Setup/tmp/build/lr-ppsspp/ppsspp/Common/GPU/OpenGL/GLDebugLog.cpp:38:15: error: ‘glGetError’ was not declared in this scope
38 | GLenum err = glGetError();
make[2]: *** [CMakeFiles/Common.dir/build.make:622: CMakeFiles/Common.dir/Common/GPU/OpenGL/GLDebugLog.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:425: CMakeFiles/Common.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

Odroid xu4 

Ubuntu 20.04 minimal

**Comment by unknownbrackets** [comment]
This sounds like some sort of system headers problem... are you using USING_GLES2?  You should be getting that frmo one of these headers:

https://github.com/hrydgard/ppsspp/blob/dd5a459e001df45fa556a50a9ba12094efe748e1/Common/GPU/OpenGL/GLCommon.h#L8-L20

-[Unknown]

**Comment by dicotom** [comment]
Yes, I got that.

**Comment by unknownbrackets** [comment]
Maybe try without USING_GLES2?  I don't know if the device supports desktop GL, but something is definitely wrong if your GLES2 system headers don't have glGetError in them.

-[Unknown]

**Comment by dicotom** [comment]
Yes it has GLES2
/usr/share/mali/headers/GLES2
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/uikit/GLES2
/usr/include/GLES2

**Comment by ANR2ME** [comment]
Have you tried using `grep` to find out where in the headers is this `glGetError` existed? it might be on a different header/path.
Doing something like this may be `grep -r "glGetError" /usr/include/`

**Comment by dicotom** [comment]
Yes, already done everything, glGetError are in gl2.h in /usr/include/GLES2
I spent a lot of time on line before opening this ticket.
I do not understand why it does not find glGetError in gl2.h and there are no errors about not finding gl2.h or gl2ext.h

**Comment by ANR2ME** [comment]
In the past someone had similar issue on odroid-c1 (ie. `error: ‘glClear’ was not declared in this scope`) on a different project.
```
I have isolated the issue described. It is due to the fact that the GLES2/gl2.h headers are different from the Ubuntu version. The version shipped with the jessie distribution requires "GL_GLEXT_PROTOTYPES" to be defined before it will work.
```
So he added `#define GL_GLEXT_PROTOTYPES 1` and able to compile it.
But he also had issue related to minimal Ubuntu (need additional packages to be installed)

**Comment by dicotom** [comment]
Where did he added #define GL_GLEXT_PROTOTYPES 1 ?

**Comment by ANR2ME** [comment]
it should be before importing any GL headers, so it can recognize the definition.

**Comment by dicotom** [comment]
well I put it in gl2.h and gl2ext.h and those not declared in this scope errors went away, but now I have: 

/home/odroid/RetroPie-Setup/tmp/build/ppsspp/ppsspp/Common/GPU/OpenGL/gl3stub.h:                                                   511:136: error: ‘void (* glBufferStorageEXT)(GLenum, GLsizeiptr, const void*, GL                                                   bitfield)’ redeclared as different kind of entity
/home/odroid/RetroPie-Setup/tmp/build/ppsspp/ppsspp/Common/GPU/OpenGL/gl3stub.h:                                                   515:289: error: ‘void (* glCopyImageSubDataOES)(GLuint, GLenum, GLint, GLint, GL                                                   int, GLint, GLuint, GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsize                                                   i)’ redeclared as different kind of entity

**Comment by ANR2ME** [comment]
Someone who had similar issue on odroid-c2 got this kind of reply:
```
It seems to require OpenGL ES 3.x while ODROID-C2 Mali-450 can support only OpenGL ES 2.0.
Can you check OpenToons' minimum GPU OpenGL ES version?
```
https://forum.odroid.com/viewtopic.php?t=33053

**Comment by dicotom** [comment]
According to the system.sh of RetroPie the flag should be applied:
function platform_odroid-xu() {
    __default_cpu_flags="-marm -mcpu=cortex-a7 -mfpu=neon-vfpv4"
    # required for mali-fbdev headers to define GL functions
    __default_cflags="-DGL_GLEXT_PROTOTYPES"
    __platform_flags+=(arm armv7 neon mali gles)
}

but is not, so I had to comment out ifdefine GL_GLEXT_PROTOTYPES in gl2.h and also delete:

#ifndef GL_EXT_buffer_storage
#ifndef ......  related to glCopyImageSubDataOES

**Comment by priiduneemre** [comment]
Stumbled into the same issue yesterday while building `lr-ppsspp` on the ODROID-XU4 (also via RetroPie).

@dicotom: The reason why the snippet from `system.sh` is ignored is [this commit|https://github.com/RetroPie/RetroPie-Setup/commit/102e25a809605f8b280f7092f5c7782d9dfd4bf6].
Basically, the `DGL_GLEXT_PROTOTYPES` _IS_ included at first but then gets stripped out by the downstream `ppsspp.sh` installation script.
Looking at the commit message, I suppose it was meant to fix the second issue we encountered (`glBufferStorageEXT` and `glCopyImageSubDataOES` header conflict).

Seems to be a case of throwing out the baby with the bath water though, as it introduces a new issue earlier in the build chain. 
I assumed maybe it fixes stuff on newer kernel/Ubuntu versions (I'm on 18.04 & 4.14), but apparently not.

Either way, I solved it by reversing the changes in `ppsspp.sh`, _i.e._ to this:
```
  params+=(-DCMAKE_C_FLAGS="${CFLAGS}")
  params+=(-DCMAKE_CXX_FLAGS="${CXXFLAGS}")
```

And temporarily commenting out the `GL_EXT_buffer_storage` and `GL_OES_copy_image` blocks in `/usr/include/GLES2/gl2ext.h`.
(Similar approach is mentioned in [this|https://magazine.odroid.com/article/building-ppsspp-for-ubuntu-on-the-odroid-xu3-xu4/] article)

After that, I managed to build it successfully, so seems like a viable workaround.

Not sure if there's a general way to fix this on PPSSPP/RetroPie's side.

**Comment by dicotom** [comment]
Yes, that is almost what I did, but instead of reversing the changes in ppsspp.sh I have comment out the  ifdefine GL_GLEXT_PROTOTYPES in gl2.h only for the functions it was complaining about

**Comment by unknownbrackets** [comment]
Is there actually some safe define we can use on these systems to target a workaround to just these systems?  It really sounds like the system headers are messed up and that's where the fix needs to be.

-[Unknown]

**Comment by gouchi** [comment]
We don't have issue building PPSSPP libretro core for Odroid Xu3|4 using GLES on Lakka.

FWIW our [package recipe](https://github.com/libretro/Lakka-LibreELEC/blob/master/packages/libretro/ppsspp/package.mk).

We are using almost the [same options](https://github.com/RetroPie/RetroPie-Setup/blob/master/scriptmodules/emulators/ppsspp.sh#L138-L141).

**Comment by priiduneemre** [comment]
I built the latest `ppsspp` again today (via RetroPie) and still got the same error. Luckily, I was able to bypass it with my workaround above.

I guess it would be fair to close this issue, since it's more an issue with faulty system headers on Hardkernel/ODROID side and a poor workaround on RetroPie side (_i.e._ the installation script).
