### ISSUE TITLE
Switching from Vulkan to a different backend makes an error message pop up

### ISSUE THREAD

**Issue by Tiberius1437** [hrydgard/ppsspp#13842]
Using the very latest version of PPSSPP

![Capture](https://user-images.githubusercontent.com/68873449/103412647-523ae300-4bca-11eb-8d6c-7acb3d08d059.PNG)

My computer specs

![Capture2](https://user-images.githubusercontent.com/68873449/103412660-67177680-4bca-11eb-97c4-0e07ecea6f47.PNG)

**Comment by ANR2ME** [comment]
I can't reproduce this on PPSSPP v1.10.3-1417-g38cfb019e Win64 build 
Could you elaborate more in step-by-step how to reproduce this?

**Comment by Tiberius1437** [comment]
I switched from OpenGL to Vulkan and then back to OpenGL. That's it.

**Comment by ANR2ME** [comment]
I tried that, i also tried d3d11->vulkan->d3d11 but never saw this error.

**Comment by Tiberius1437** [comment]
I have the rendering resolution at x4 but other than that I think my settings are all default.

**Comment by hrydgard** [comment]
Were you ingame when you switched? any particular game?

**Comment by Tiberius1437** [comment]
No I wasn't in a game. I'm using the regular version of the emulator.

**Comment by MojoJojoDojo** [comment]
I also get errors when switching between renderers.

**Comment by unknownbrackets** [comment]
I'm using a similar device and couldn't reproduce.  Here's what I did:

1. Started PPSSPP (latest git build - https://buildbot.orphis.net/ppsspp/.)
2. Settings -> changed backend from Vulkan to Direct 3D 11.
3. Changed again back to Vulkan.
4. Now to OpenGL.
5. Back to Vulkan.

Didn't experience any problems.  Are there steps I'm missing?  Or are you perhaps using PPSSPP v1.10.3?  That version is from July, I'm only testing in what will soon be v1.11.0.

-[Unknown]

**Comment by ANR2ME** [comment]
Okay, i managed to reproduce this issue.
1. Start PPSSPP in fullscreen using 4x or higher rendering resolution
2. Continuously switching from OpenGL->Vulkan->OpenGL->Vulkan->OpenGL ->so on, until it eventually shows this popup
![image](https://user-images.githubusercontent.com/7974720/104114315-baf62e00-5335-11eb-804c-c8233c49fee0.png)

Running it on Fullscreen seems to be an important factor to bump into this issue faster, probably ti make sure PPSSPP to use high amount of VRAM.
So may be there is memory leaks on VRAM?

**Comment by unknownbrackets** [comment]
I tried switching back and forth about 20 times (total 40 switches) in full screen.  I didn't start any game or anything.  No errors popped up.

Perhaps this was #13933?  Is it still reproducible?

-[Unknown]

**Comment by ANR2ME** [comment]
I can't reproduce this either, i guess that commit fixed this.
