### ISSUE TITLE
Some FMV Cutscenes crash on kingdom hearts birth by sleep Final Mix

### ISSUE THREAD

**Issue by zakilj3** [hrydgard/ppsspp#13851]
### What happens?
When finishing the final episode or starting the secret episode,the game instantly crash when a prerended cutscene play(this happen as well in the theater mode)
### What *should* happen?
Normally it shouldn't crash and its not even possible to just skip the cutscenes,those scenes does work on the vanilla version of birth by sleep

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
I m on Android 10 ,but it happen as well on pc windows 10, I was using the latest ppsspp build 1.10.3-1445

**Comment by Panderner** [comment]
Duplicate of #12539
