### ISSUE TITLE
There's a bit of graphical garbage on the save screen in Space Invaders Extreme (US) when upscaling

### ISSUE THREAD

**Issue by Tiberius1437** [hrydgard/ppsspp#13854]
I'm not sure if this is fixable or not. It happens with both OpenGL and Vulkan.

Native resolution

![Capture2](https://user-images.githubusercontent.com/68873449/103459528-366b4480-4d64-11eb-9531-d235b4c494fa.PNG)

x4

![Capture](https://user-images.githubusercontent.com/68873449/103459539-4f73f580-4d64-11eb-8368-7aafd24c71a4.PNG)

**Comment by Panderner** [comment]
I can't see the difference

**Comment by Tiberius1437** [comment]
There's a line of garbage under the word "Extreme"

**Comment by Panderner** [comment]
PSP renders at 480x272. Regarding this comment in https://github.com/hrydgard/ppsspp/issues/13844#issuecomment-753001461 upscaling might cause some graphical artifacts as the 2d textures are rendered at low resolution in most PSP games.

**Comment by Panderner** [comment]
and then Darkstalkers are forced to use Software Renderer so we can't upscale the games in Software Renderer mode

**Comment by hrydgard** [comment]
Since it's us doing this drawing I think, this should be fixable. Marking for 1.12.

**Comment by Panderner** [comment]
They confirmed that https://github.com/hrydgard/ppsspp/pull/13868 fixes garbage bleeding issue.
![IMG_20210104_165128](https://user-images.githubusercontent.com/37503397/103517735-94f00a00-4ead-11eb-89d0-ea0ff216578a.jpg)
