### ISSUE TITLE
Phantasy Star Portable 2 Infinity / Host party loading bug loop (only for windows 7 users)

### ISSUE THREAD

**Issue by SoulOfRock** [hrydgard/ppsspp#13873]
### What happens?
Im a user of win7 64bits, i cant change the windows system because my pc is old and my brother have and old pc too, so we try to play on party lan,he can join me,we see each other at the lobby, but when is time to go for a missión,after i start the missión a loading loop keeps and nothing happend, just loading... at battle (pvp) we can join and play but at regular quests, the loop loading bug still happend. I have read so many people saying windows 7 users cant host,that is a crap TnT.

### What *should* happen?
The Windows 7 user should be able to host without the loop loading error and just be able to play.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

PPSSPP 1.10.3
Windows 7 Home premium (i try Windows 7 Ultimate too,but nothing change)
Y try on 3 computers whit = Core I3, Quad Core 9800, and Core 2 Duo.
My graphic card is : Geforce GT 720 2gb DDR3

**Comment by ANR2ME** [comment]
@SoulOfRock 
Are you using the latest build from here https://buildbot.orphis.net/ppsspp/ ?
Did you see any red message on screen when starting the mission and stuck?
Have you tried changing port offset value?

PS: There shouldn't be any API difference between Win7 or newer one, so it's strange if it only happened on Win7.

**Comment by ANR2ME** [comment]
Something feels odd with this game and VPN on Win7 after reading an old post here http://www.pso-world.com/forums/showthread.php?226499-How-to-NETPLAY-Phantasy-Star-Portable-2-For-PPSSPP-emulator/page2
```
Hey there Blade,

In the video I was running Windows 8. JCGamer is also running Windows 8. The other folks I've played with I'm unsure.

(Regarding the issue with infinite load screen when going from Clad 6 --> mission when hosting)

That was me who mentioned there may be an issue with Windows 7 and PPSSPP online. (MunchMonkii). It IS working on Windows 7, but it seems, at least from the experience I've had w/ my machines, that Win7 machines are more likely to have the issue. What is causing the issue, I have no idea.

I'd like you to know that
= a fresh install of Windows 7 (64-bit) had the issue
= a fresh install of Windows 8 (64-bit) worked fine
* This is using the exact same hardware and PPSSPP version/folder.

Lumune over at PPSSPP has mentioned that he had WinPcap installed on his Win7 machine, and he was able to get it working.

I'll try fiddling with PPSSPP on my Win7 machines that have the issue to see if I can pinpoint the problem.
```
I wonder why WinPCap can make it works... as far as i know PPSSPP doesn't use it, may be the VPN needed it?


```
Thanks for the feedback. I thought it was just me who was having the issue there for a bit. Lol If you can figure out a solution to the problem, that would be badass. The only way I know how to get it to run correctly as of this moment, is by running Windows XP in VirtualBox, starting a party and passing leader to the player using Windows XP to start missions. After that, it'll work apparently. But that's an insane step to take just for it to work.
```
It's also strange that running WinXP virtual machine on Win7 makes it works

```
Coincidentally I've been messing around with it last night / today. Borrowed my uncle's machine for testing.


fresh install of Win 8 x64 - worked
fresh install of Win 10 tech preview x64 - worked
fresh install of Win7 Home Premium + SP1 x86 - no go
resh install of Win7 Home Premium + SP1 x86 + ALL Windows updates available - no go

* Also tried the latest version of PPSSPP that was release today (1.0), but same results.

I have no idea what could be causing the issue.

Keep in mind, that if you have that infinite loading glitch, you CAN still play with others. It's just that you can't be the host if you have that glitch.

I have Win8 on my personal machines, but if I were in your shoes and wanted to host games, I would seriously install Win8 or Win10 tech preview (available free) at least as a 2nd OS on your machine. 
```

So the issue seems to happen only when you're the host or mission leader on Win7 (and Vista too seems to have similar issue), and all the post discussing this seems to be using VPN, and not sure if it have the same issue without VPN or not.

**Comment by MojoJojoDojo** [comment]
Well it was before Upnp was a thing and localhost was less common so makes sense.
I heard someone on discord said its less common but still happens on the latest dev builds though so maybe its random? dunno.

**Comment by SoulOfRock** [comment]
Now you can close this.
