### ISSUE TITLE
Adjust github action to upload full build artifact

### ISSUE THREAD

**Issue by kaiomatico** [hrydgard/ppsspp#13879]
### What happens?
Downloading the build artifacts for linux from the bottom of this [page](https://github.com/hrydgard/ppsspp/actions/runs/463785378) only downloads the headless test version, because the github actions are configured to only upload these build and NOT the QT build.
```
➜  ubuntu-latest build chmod +x PPSSPPSDL     
➜  ubuntu-latest build ./PPSSPPSDL      
VulkanMayBeAvailable: Device allowed ('SDL:Linux')
VulkanMayBeAvailable: Library loaded ('libvulkan.so')
VulkanMayBeAvailable: Enumerating instance extensions
VulkanMayBeAvailable: Instance extension count: 18
VulkanMaybeAvailable: Instance extension found: VK_KHR_device_group_creation (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_display (00000017)
VulkanMaybeAvailable: Instance extension found: VK_KHR_external_fence_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_external_memory_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_external_semaphore_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_get_display_properties2 (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_get_physical_device_properties2 (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_get_surface_capabilities2 (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_surface (00000019)
VulkanMaybeAvailable: Instance extension found: VK_KHR_surface_protected_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_wayland_surface (00000006)
VulkanMaybeAvailable: Instance extension found: VK_KHR_xcb_surface (00000006)
VulkanMaybeAvailable: Instance extension found: VK_KHR_xlib_surface (00000006)
VulkanMaybeAvailable: Instance extension found: VK_EXT_acquire_xlib_display (00000001)
VulkanMaybeAvailable: Instance extension found: VK_EXT_debug_report (00000008)
VulkanMaybeAvailable: Instance extension found: VK_EXT_direct_mode_display (00000001)
VulkanMaybeAvailable: Instance extension found: VK_EXT_display_surface_counter (00000001)
VulkanMaybeAvailable: Instance extension found: VK_EXT_debug_utils (00000002)
VulkanMayBeAvailable: Calling vkCreateInstance
VulkanMayBeAvailable: Vulkan test instance created successfully.
INTEL-MESA: warning: Vulkan is not yet fully supported on gen12
INTEL-MESA: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

VulkanMayBeAvailable: Found working Vulkan API!
VulkanMayBeAvailable: Destroying instance
DEBUG: Vulkan might be available.
Info: We compiled against SDL version 2.0.8, but we are linking against SDL version 2.0.12., be aware that this can lead to unexpected behaviors
49:57:808 Core/Config.cpp:542 I[G3D]: Longest display side: -1 pixels. Choosing scale 1
Pixels: 960 x 544
Virtual pixels: 960 x 544
OpenGL 2.0 or higher.
loading control pad mappings from gamecontrollerdb.txt: gamecontrollerdb.txt missing
SUCCESS!
49:57:858 UI/NativeApp.cpp:840 E[G3D]: Failed to load ui_atlas.meta - graphics will be broken.
49:57:859 UI/TextureUtil.cpp:154 E[IO]: Failed to read file 'ui_atlas.zim'

```

### What *should* happen?
Maybe also upload an artifact of a full build and then link it here for [download](https://buildbot.orphis.net/ppsspp/index.php)

If this is something you also feel would be nice to have I can fork and adjust the github action on an own repo and then send a pull request. Thanks in advance and thanks for the great emulator (and have a nice new year :+1:  )

**Comment by hrydgard** [comment]
Feel free to send a pull request indeed!

**Comment by unknownbrackets** [comment]
To run tests, an archive *must* be created.  The "test" job cannot access files generated by previous jobs.

That said, it is including PPSSPPSDL (which is not headless - it just doesn't have a menu bar.)  We could also package PPSSPPQt, but note that this would have to be a separate download since it's generated by a separate job.  Two jobs cannot access each other.  So it could maybe be "ubuntu-latest Qt build"?  There'd be no need to run pspautotests on this build.

More importantly, the PPSSPPSDL package (and any PPSSPPQt package, for that matter) should include assets, which is probably why your PPSSPPSDL run didn't work.  Forgot about that.  If you copy the assets in it may work.

-[Unknown]

**Comment by kaiomatico** [comment]
Thank you for your comments, it was really enough to just add the assets, then everything works fine :) I made an PR: https://github.com/hrydgard/ppsspp/pull/13891 (I tested the github action in a different local PPSSPP fork before, it works fine). I just don't know how to add the latest artifact to the ppsspp download page.
Best Regards

**Comment by kaiomatico** [comment]
Thank you for merging. I did some research and it seems so that it is currently not possible to get a predictable "latest artifact" url. But someone made a github app beause of this lacking feature, maybe we can use this to put the download links for the latest linux builds on the ppsspp homepage:   
https://nightly.link/  
https://github.com/oprypin/nightly.link

**Comment by unknownbrackets** [comment]
Hm, potentially we could use that indeed.  GitHub Actions builds only last for 90 days, though, so the best thing might be to upload them somewhere else.

All the git downloads are actually built by a separate CI currently, but I think they're hosted on a separate server.  Maybe there's a way to push the actions builds there.  That said, I think Linux builds get a bit endless - there's always another distro or arch to build for.

-[Unknown]

**Comment by kaiomatico** [comment]
Okay thank you for the Information. I agree with the endlessness for linux builds, so I guess we just leave it like this for the moment and I could experiment with flatpaks or App mages in the coming week - these should work on all distros and we could build and upload it on the seperate CI server :-)

**Comment by kaiomatico** [comment]
Oh wow now I feel really stupid, there is already a great working up2date flatpak available on flathub, see:  
- https://flathub.org/apps/details/org.ppsspp.PPSSPP
- https://github.com/flathub/org.ppsspp.PPSSPP

So I guess it would be great to update this PPSSPP download site: https://www.ppsspp.org/downloads.html to link to this flatpak:  https://flathub.org/apps/details/org.ppsspp.PPSSPP  in my opinion :+1:  I will close this issue now, thank you all

**Comment by hrydgard** [comment]
Thanks @kaienfr , I've added a link.
