### ISSUE TITLE
Kurohyou : Ryu ga gotoku shinshou fps drop and weird texture

### ISSUE THREAD

**Issue by Lemoncak3** [hrydgard/ppsspp#13882]
when play this game sometimes in battle scene fps can drop to 16 fps and i can feel the fps drop in some scene too. When i go to supermarket my char can walk throigh the rack not behind which make it weird.

![Screenshot_20210106-144811](https://user-images.githubusercontent.com/67026697/103744677-c2b18c00-5030-11eb-95b5-0ff22b9c6bf4.png)

**Comment by Saramagrean** [comment]
Similar https://github.com/hrydgard/ppsspp/issues/9576?

**Comment by Lemoncak3** [comment]
I close mine then sorry, the name is a bit weird so i didn't search for it. Thanks
