### ISSUE TITLE
Gradius Collection graphical glitches in vulkan

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#13887]
There's a lot of graphical glitches in gradius for all games (except Gradius 4) In Vulkan

The numbers in Gradius 1 is not transparent
![Screenshot_2021-01-07-10-51-41-852_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/103845648-6eadb280-50d7-11eb-9d86-5c7c4fb6c85f.jpg)

Also Logo and numbers in Gradius 2 title screen is not transparent
![Screenshot_2021-01-07-10-51-52-512_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/103845683-7ec59200-50d7-11eb-8a01-a4f92305b3f1.jpg)

Missing backgrounds in Gradius 3 opening sequence too
![Screenshot_2021-01-07-10-53-07-510_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/103845762-ad436d00-50d7-11eb-8892-6bec482f3bc6.jpg)

Gradius 2 and 3 are unplayable in Vulkan
![Screenshot_2021-01-07-10-55-54-038_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/103845486-21314580-50d7-11eb-968f-6f1f2126238f.jpg)
![Screenshot_2021-01-07-10-56-02-903_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/103845489-22fb0900-50d7-11eb-9fa6-f019b9ce4929.jpg)

There's a lot of graphical artifacts in Gradius Gaiden
![Screenshot_2021-01-07-10-53-59-566_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/103845601-576ec500-50d7-11eb-931e-be281d968bff.jpg)

**Comment by Panderner** [comment]
Although OpenGL works fine for all games

**Comment by sum2012** [comment]
I test no problem in my desktop computer 
BUT it HAPPENED my phone black shark 3.

**Comment by sum2012** [comment]
Frame dump of Gradius 2 
[recording.zip](https://github.com/hrydgard/ppsspp/files/5792494/recording.zip)

**Comment by sum2012** [comment]
work in v1.10.2
don't work in v1.10.3

**Comment by sum2012** [comment]
@hrydgard 
Last work v1.10.3-987-g327eb21e0
First bad v1.10.3-1000-g349fc7071

That mean #13576 
Do you want to fix before release ?

**Comment by unknownbrackets** [comment]
> Frame dump of Gradius 2
> [recording.zip](https://github.com/hrydgard/ppsspp/files/5792494/recording.zip)

On my Pixel in Vulkan, this looks about the same as on my desktop.  What am I looking for?

-[Unknown]

**Comment by sum2012** [comment]
@unknownbrackets I redo frame dump from android
[recording_from_andriod.zip](https://github.com/hrydgard/ppsspp/files/5793320/recording_from_andriod.zip)

**Comment by sum2012** [comment]
@hrydgard your change #13924 make this game worse.
Keep in "Now-loading" screeen after slect "Gradius  2"
My phone is black shark 3,gpu: Adrene 650 driver:512.44.0

**Comment by hrydgard** [comment]
That's weird. I'll look into it.

**Comment by sum2012** [comment]
@hrydgard Sorry,I cannot reproduce again "Keep in "Now-loading" " and it seem fixed this issue.
@Panderner can you test v1.10.3-1556-ge51317e26 ?

**Comment by Panderner** [comment]
> @hrydgard Sorry,I cannot reproduce again "Keep in "Now-loading" " and it seem fixed this issue.
> @Panderner can you test v1.10.3-1556-ge51317e26 ?

I tried v1.10.3-1556-ge51317e26 but the loading screen flickers for all games except Gradius 3

**Comment by sum2012** [comment]
@Panderner does it have same issue as v1.10.3-1554-g13e7de1b8 ?

**Comment by Panderner** [comment]
> @Panderner does it have same issue as v1.10.3-1554-g13e7de1b8 ?

Same issue but Gradius 3 is the same for previous builds until v1.10.3-1556-ge51317e26

**Comment by sum2012** [comment]
@Panderner please make flickers frame dump for @hrydgard debug

**Comment by Panderner** [comment]
I forgot to turn on Simulate block transfer effects and it works fine for all games.
![Screenshot_2021-01-17-07-23-25-088_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/104827081-17f16700-5895-11eb-9bbf-d45035854ff0.jpg)

**Comment by hrydgard** [comment]
OK, so no problems anymore?

**Comment by sum2012** [comment]
I do not have problem anymore .
Snapdragon 865 is new but still have that Adreno driver bug.

**Comment by Panderner** [comment]
> I do not have problem anymore .
> Snapdragon 865 is new but still have that Adreno driver bug.

@sum2012 Do you enabled simulate block transfer effects?

**Comment by sum2012** [comment]
@Panderner Yes, I usually enable simulate block transfer effects
