### ISSUE TITLE
Add a setting for mipmapping

### ISSUE THREAD

**Issue by jamezhidayat** [hrydgard/ppsspp#13888]
please add mipmaping in game setting like ppsspp v 1.4.1

**Comment by hrydgard** [comment]
a better version of this setting is coming back in 1.12.

Do you have a specific usecase or problem you want to solve?

**Comment by Panderner** [comment]
@jamezhidayat no feedback?

**Comment by UbiSergei** [comment]
Mip Map I'm A Mipmap

Why Use It If U Can.. Party?

**Comment by XiaomiRedmi9** [comment]
https://github.com/hrydgard/ppsspp/labels/Mipmaps
