### ISSUE TITLE
Power Stone Collection black boxes inside now loading

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#13881]
Look at the screenshot below:

OpenGL:
![Screenshot_2021-01-06-12-11-17-942_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/103734607-4bc3c580-5027-11eb-97f5-d845e6cbd554.jpg)

Vulkan:
![Screenshot_2021-01-06-12-11-45-278_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/103734620-52ead380-5027-11eb-9e27-56b8f6db34dd.jpg)

GE dump: 
[ULUS10171_0001.zip](https://github.com/hrydgard/ppsspp/files/5774116/ULUS10171_0001.zip)

**Comment by hrydgard** [comment]
Works on PC. This is almost certainly one of those wacky Adreno stencil/discard driver bugs.

Which GPU does your device have again?

**Comment by Panderner** [comment]
> Works on PC. This is almost certainly one of those wacky Adreno stencil/discard driver bugs.
> 
> Which GPU does your device have again?

I'm using POCO M3

**Comment by brujo5** [comment]
Specifically is Adreno 610

**Comment by hrydgard** [comment]
Actually this one is weirder than I first thought ...   It is not using any wacky stencil tricks (that Adreno has had several bugs with). The draw that erroneously shows up as a black box is drawn with regular alpha blending. The only even slightly out of the ordinary thing about it is that it uses the RGBA4444 texture format (by using a CLUT8 format with a 4444 palette) but that's not THAT unusual..

**Comment by hrydgard** [comment]
OK, this has something to do with very tiny differences in depth testing (zbuffer).

Not gonna be able to dig into this for 1.11.

**Comment by Panderner** [comment]
This must be Adreno CPU specific

**Comment by sum2012** [comment]
@Panderner can you test again with latest version with enable "simulate black transfer effects" ?
As we are re-apply the old Adreno driver bug workaround.

**Comment by Panderner** [comment]
Even I turned off simulate block transfer effects the works fine for latest builds of PPSSPP in Vulkan
![Screenshot_2021-01-17-21-47-36-659_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/104844931-c46f2f80-590d-11eb-9236-154f6409fea5.jpg)

**Comment by hrydgard** [comment]
Oh, then I was wrong about depth/Z. Good to know!
