### ISSUE TITLE
The ini files in PSP\CHEATS increase in size

### ISSUE THREAD

**Issue by jojorne** [hrydgard/ppsspp#13880]
### What happens?
The ini files in PSP\CHEATS increase in size (new line at the end) each time a cheat checkbox is changed or each time the file is saved by the emu.

### What *should* happen?
Probably when ppsspp saves the files, it adds a new line at the end by mistake.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
PPSSPP v1.10.3

PS.: Also while we are at it, I want to add that the "[cheat.db](https://github.com/Saramagrean/CWCheat-Database-Plus-)" file does NOT loaded on Android but loads on Windows.

**Comment by eqprog** [comment]
So that explains it. I was figuring out some cheats to make testing my texture pack easier and every time I disabled/reenabled the cheat my text editor would prompt me to reload the file because another program had changed it.

**Comment by jojorne** [comment]
Ah, yes. When you change the checkbox, it saves the file, changing _CX to _C0 or _C1 but it also adds a double new line at the end of the file.
