### ISSUE TITLE
Make resume button (or play button) not 2x faster button, but as a working button, mostly games request that

### ISSUE THREAD

**Issue by Gusety** [hrydgard/ppsspp#13890]
I think the play button should be the working button due to issues in game, which is uncomfortable in games, when a game request a play button I press it is just speed it. Which is not ok. Please fix that, I know you replaced play button with right button of the controller, but still it's an issue, mostly on Dual shock where l2 and R2 is speed buttons and if you place dual chock on the table it maybe makes those buttons activate, and it speeds up all progress where is all important,

Op, sys: Android 10 On oneGui by samsung

you should solve this

**Comment by unknownbrackets** [comment]
It's not very clear what you're saying, but controls are configurable.  You're perfectly welcome to map the Start button or Speed Toggle / Unthrottle buttons to any buttons you want.

Does "play button" mean the Start button?

I do not recommend mapping Start and Unthrottle to the same button.  That said, I don't think we need to make PPSSPP force you to map them to different buttons.  It's your choice.

-[Unknown]

**Comment by Gusety** [comment]
Thing is: recume button, start is dosent go ahead as inneeded

**Comment by hrydgard** [comment]
I am extremely confused. Please explain more clearly.

**Comment by ANR2ME** [comment]
May be he had the L2 and R2 assigned by default, and those buttons getting pressed when he put the controller on a table.

**Comment by Nicholas-Steel** [comment]
My translation of what they're saying:

>     I think the play button should be the working button due to causing uncomfortable issues in games. When a game requests a play button I press it but it only adjusts the game speed which is not ok, please fix that. I know you replaced play button with right button of the controller, but still it's an issue, mostly on Dual shock where l2 and R2 is speed buttons and if you place dual shock gamepad on the table those buttons may accidentally momentarily activate, and it speeds up the game.

Another words they simply need to rebind the gamepad buttons.

**Comment by unknownbrackets** [comment]
Sounds like this isn't an issue.  You're welcome to change the button mapping in the settings.  Unthrottle doesn't need to be mapped to anything at all.

If you have more information and we've misunderstood you, please reply to this issue and it can be reopened.

-[Unknown]
