### ISSUE TITLE
Ppsspp Android Gensou Suikoden: Tsumugareshi Hyakunen no Toki character models not showing 

### ISSUE THREAD

**Issue by learnfromearl** [hrydgard/ppsspp#13896]
Can anyone help me? loaded the game and its working but the problem is the character models are not showing. no problem with other games just this one.

![Screenshot_20210109_103200_org ppsspp ppssppgold](https://user-images.githubusercontent.com/55720273/104080937-4a341080-5266-11eb-8eae-fc7ab9fd2f04.jpg)
Just down
![Screenshot_20210109_103213_org ppsspp ppssppgold](https://user-images.githubusercontent.com/55720273/104080943-54eea580-5266-11eb-9bff-8a46659ce58d.jpg)
![Screenshot_20210109_103328_org ppsspp ppssppgold](https://user-images.githubusercontent.com/55720273/104080946-5750ff80-5266-11eb-9970-04b3d4cf7fee.jpg)
![Screenshot_20210109_103309_org ppsspp ppssppgold](https://user-images.githubusercontent.com/55720273/104080947-591ac300-5266-11eb-9be2-2838f76feb09.jpg)

![Screenshot_20210109_102353_org ppsspp ppssppgold](https://user-images.githubusercontent.com/55720273/104080877-ced25f00-5265-11eb-8791-425e8a880c06.jpg)
![Screenshot_20210109_102341_org ppsspp ppssppgold](https://user-images.githubusercontent.com/55720273/104080878-d1cd4f80-5265-11eb-8711-25db237ec4bd.jpg)

**Comment by Panderner** [comment]
@learnfromearl what device are you using?

**Comment by learnfromearl** [comment]
Im using a Huawei Y9 2019. All games are working fine, God Eater 2, P3P, Kingdom hearts, FF Type 0, no problems, no lags, no texture issues except this game Suikoden. Tried the unpatched japanese iso still the same. Using PPSSPP Gold paid from playstore.

**Comment by Panderner** [comment]
@learnfromearl have you tried a latest PPSSPP build?

**Comment by learnfromearl** [comment]
Im sorry Im not familiar with "builds" or something. All I know is I just recently updated the app in playstore.

**Comment by learnfromearl** [comment]
So I just downloaded the newest build for ppsspp android like you said. It still the same thing. Still no character models appearing in cutscenes or in battle

![Screenshot_20210109_163329_org ppsspp ppsspp](https://user-images.githubusercontent.com/55720273/104087151-9f891580-5298-11eb-9025-0b385db57bfe.jpg)
![Screenshot_20210109_163359_com android chrome](https://user-images.githubusercontent.com/55720273/104087153-a31c9c80-5298-11eb-8761-490300a28c47.jpg)

**Comment by learnfromearl** [comment]
Tried the oldest 2019 build still the same. Does anyone have the same problem when playing this game in Android?

**Comment by Panderner** [comment]
Have you tried OpenGL and Vulkan?

**Comment by learnfromearl** [comment]
Yes, tried both openGL and Vulkan still the same no character models. I just don't know what happened. Did you try this yourself? Did it work for you?

**Comment by Panderner** [comment]
> Yes, tried both openGL and Vulkan still the same no character models. I just don't know what happened. Did you try this yourself? Did it work for you?

Can you create GE Dump?

**Comment by Panderner** [comment]
This game works fine for me I'm using Xiaomi POCO M3.
![Screenshot_2021-01-09-18-25-55-266_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/104089258-5fca2a00-52a8-11eb-850d-364bcdfb6073.jpg)
![Screenshot_2021-01-09-18-26-58-690_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/104089261-622c8400-52a8-11eb-8785-8eae94727390.jpg)

**Comment by sum2012** [comment]
@learnfromearl please try enable "simulate block transfer  effects"

**Comment by learnfromearl** [comment]
im sorry for the late reply. Just woke up. I did what you asked @Panderner. Did 2 Ge dumps.

**Comment by learnfromearl** [comment]
[Uploading Download.zip…]()

**Comment by learnfromearl** [comment]
[Download.zip](https://github.com/hrydgard/ppsspp/files/5791342/Download.zip)

**Comment by learnfromearl** [comment]
Already enabled simulate block transfer but still the same. 

![Screenshot_20210109_234749_org ppsspp ppssppgold](https://user-images.githubusercontent.com/55720273/104096060-396eb380-52d5-11eb-999a-2751176a1998.jpg)

![Screenshot_20210109_234740_org ppsspp ppssppgold](https://user-images.githubusercontent.com/55720273/104096064-3ecbfe00-52d5-11eb-9dc6-7b5d50ee963c.jpg)

**Comment by learnfromearl** [comment]
There should be 3 character models there. But mine doesn't have. This is the same as in the battles. No enemies, no characters. I just dont know whats happening.

@Panderner, thank you for taking the time to help me with this I know its a hassle but I do appreciate the help so much. I hope we can fix this :(

**Comment by Panderner** [comment]
@learnfromearl have you tried to disable frame skip?

**Comment by learnfromearl** [comment]
@Panderner yes I did but unfortunately its still the same. 

![Screenshot_20210110_002140_org ppsspp ppssppgold](https://user-images.githubusercontent.com/55720273/104102854-f5ca7880-52d9-11eb-96dc-44ce911b473d.jpg)

**Comment by learnfromearl** [comment]
![Screenshot_20210110_002053_org ppsspp ppssppgold](https://user-images.githubusercontent.com/55720273/104102871-1266b080-52da-11eb-963a-61c78b8f9a96.jpg)
![Screenshot_20210110_002140_org ppsspp ppssppgold](https://user-images.githubusercontent.com/55720273/104102877-1a265500-52da-11eb-943b-660351830ea0.jpg)

**Comment by learnfromearl** [comment]
Heres the GE Dump you asked for

[Download.zip](https://github.com/hrydgard/ppsspp/files/5791391/Download.zip)

**Comment by Panderner** [comment]
@learnfromearl can you check where the ISO is corrupted?

**Comment by learnfromearl** [comment]
The iso is corrupted? I checked in Winrar and its working fine. I actually downloaded both the English translated and the original jap version to see if maybe the prob is with the ISO or what but nope both ISO is working fine, both ISO english trans. and Jap ver. are having the same issue

![Screenshot_20210110_011152_com rarlab rar](https://user-images.githubusercontent.com/55720273/104104146-40032800-52e1-11eb-9887-d85716035cba.jpg)

**Comment by learnfromearl** [comment]
Downloaded the translated game from cdromance

**Comment by Panderner** [comment]
Sorry @learnfromearl piracy is not allowed here.

**Comment by learnfromearl** [comment]
Oh sorry about that. Deleted it already. but yeah both ISO has the same problem. Both the translated one and the clean one.

**Comment by Panderner** [comment]
@learnfromearl Have you tried check the ISO size and CRC if is not corrupted?

**Comment by learnfromearl** [comment]
The file size is this. I don't know how to do the CRC.

![Screenshot_20210110_014046_com huawei hidisk](https://user-images.githubusercontent.com/55720273/104104764-0d5b2e80-52e5-11eb-9fd2-6caa67057aaa.jpg)

**Comment by learnfromearl** [comment]
Everything's working fine now. I was able to fix it by deleting all my save files. I dont know why that file is messing up with suikoden though.

![Screenshot_20210110_015851_org ppsspp ppssppgold](https://user-images.githubusercontent.com/55720273/104105280-0255cd80-52e8-11eb-965f-c8dde01caf27.jpg)
![Screenshot_20210110_015800_org ppsspp ppssppgold](https://user-images.githubusercontent.com/55720273/104105288-071a8180-52e8-11eb-8085-f6984cf0fc4b.jpg)
![Screenshot_20210110_015734_org ppsspp ppssppgold](https://user-images.githubusercontent.com/55720273/104105291-097cdb80-52e8-11eb-8733-6ba17b63bacb.jpg)

**Comment by hrydgard** [comment]
That is weird. But don't know what can be done here, maybe if you still have the old save files that caused it, someone could take a look. If you do, please reopen.

**Comment by tahubakso112** [comment]
> Everything's working fine now. I was able to fix it by deleting all my save files. I dont know why that file is messing up with suikoden though.
> 
> ![Screenshot_20210110_015851_org ppsspp ppssppgold](https://user-images.githubusercontent.com/55720273/104105280-0255cd80-52e8-11eb-965f-c8dde01caf27.jpg) ![Screenshot_20210110_015800_org ppsspp ppssppgold](https://user-images.githubusercontent.com/55720273/104105288-071a8180-52e8-11eb-8085-f6984cf0fc4b.jpg) ![Screenshot_20210110_015734_org ppsspp ppssppgold](https://user-images.githubusercontent.com/55720273/104105291-097cdb80-52e8-11eb-8733-6ba17b63bacb.jpg)

Thats work hahaha. Thank you
