### ISSUE TITLE
LittleBigPlanet - Game Not Loading, Blue Screen (iOS, Unplayable)

### ISSUE THREAD

**Issue by Ultra24** [hrydgard/ppsspp#13897]
### What happens?
On the game littlebigplanet, after the opening cinematic is done and you load into the game, the whole screen is just a blurry light blue colour which is just the background and the actual game textures does not load making it unplayable. You are still able to go in the in-game settings menu but none of the game's actual gameplay will load.  (see video for details) 

https://user-images.githubusercontent.com/62357227/104081249-6e0e3c80-51fb-11eb-8f84-3201ea567ac7.mov

### What *should* happen?
The game should load all of its contents and not just the blue background behind the character and ground and not have a permanent blue screen (see image for how it should look like) 
![littlebigplanetnormal](https://user-images.githubusercontent.com/62357227/104081412-5aafa100-51fc-11eb-972c-8dc5e6778eae.png)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
iPhone 8, iOS 14.3 (non-jailbroken), v1.10.3

**Comment by Panderner** [comment]
@Ultra24 are you using IR Interpreter?

**Comment by Ultra24** [comment]
> @Ultra24 are you using IR Interpreter?

Yes, I am because I'm on iOS 14 and JIT (Dynarec) Doesn't work without Jailbreaking.

**Comment by hrydgard** [comment]
Quite likely to be an IR Interpreter bug then... Can someone try if the same happens with the IR interpreter on PC?

**Comment by Ultra24** [comment]
yep, you're right. it's an IR interpreter problem. tried it on my pc with IR interpreter instead of JIT (see image)
![LBP IR Interpreter](https://user-images.githubusercontent.com/62357227/104105375-98074380-527b-11eb-8196-069cd22a0eb1.png)

**Comment by hrydgard** [comment]
Okay, good to confirm!

**Comment by unknownbrackets** [comment]
Seems to be a problem in PurgeTemps somewhere.  Looking.

-[Unknown]
