### ISSUE TITLE
Lord of Arcana (EU) have invisible bottom part of model on D3D9/D3D11

### ISSUE THREAD

**Issue by ANR2ME** [hrydgard/ppsspp#13903]
### What happens?
I'm using the SaveData from GameSpot (the one saying female character), when i continue the data it's showing this:
![image](https://user-images.githubusercontent.com/7974720/104114582-99e30c80-5338-11eb-8420-df5805fd289f.png)
Frame dump: 
[ULES01507_0001.zip](https://github.com/hrydgard/ppsspp/files/5792476/ULES01507_0001.zip)

Only happened on D3D9 & D3D11, while OpenGL/Vulkan are fine.

### What *should* happen?
Shows the character model correctly just like OpenGL/Vulkan
![image](https://user-images.githubusercontent.com/7974720/104114710-0f031180-533a-11eb-9b82-942e7c4f29c1.png)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Laptop with Win10 64bit v20H2 fully updated, Intel Core i5-8250U, Geforce MX150 driver v460.89 whql, also tested with Intel UHD Graphics 620

**Comment by sum2012** [comment]
Can you help to post the SaveData from GameSpot in here ?

**Comment by ANR2ME** [comment]
> 
> 
> Can you help to post the SaveData from GameSpot in here ?

Here it is 
[lord-of-arcana.21578.zip](https://github.com/hrydgard/ppsspp/files/5792585/lord-of-arcana.21578.zip)

The frame dump on my fist post can also be used to reproduce

**Comment by sum2012** [comment]
I test no problem in windows 7 NVIDIA   GeForce  710  Driver version : 456.55
graph maybe corrupt from old save , or some DX feature don't support in  Geforce MX150 
![1](https://user-images.githubusercontent.com/2177532/104124313-24545c00-538b-11eb-82f3-a2bd3b49374c.jpg)

**Comment by ANR2ME** [comment]
@sum2012 Have you tried to replay the GE frame dump i uploaded? Did it shows correctly?

I don't think it's unsupported feature, since most GPU supporting DX12 should fully supports all features from DX9

**Comment by sum2012** [comment]
I don't have problem in your frame dump.
Other reason maybe windows 10

**Comment by ANR2ME** [comment]
I see, may be it's also driver issue.

**Comment by ANR2ME** [comment]
PPSSPP v1.10.3 from http://www.ppsspp.org/downloads.html doesn't have this issue.

**Comment by sum2012** [comment]
Have you tried to save again to fix savedata ?

**Comment by ANR2ME** [comment]
> 
> 
> Have you tried to save again to fix savedata ?

Yes, but have no difference.

Anyway, it seems
The first broken one is v1.10.3-1098-g34874238a
The last working one is v1.10.3-1086-g105a6ce92

**Comment by sum2012** [comment]
You can git checkout
v1.10.3-1093-gf1dbd25de and
v1.10.3-1092-g642f2004d
to ensure the problem is "Share the uniform buffer declarations between D3D11 and VK"

**Comment by hrydgard** [comment]
Oh interesting! that's a good starting point for debugging this. I'll take a look soon.

**Comment by ANR2ME** [comment]
v1.10.3-1094-g17778131b doesn't even show the character at all, i can only see the sword

**Comment by unknownbrackets** [comment]
The dump doesn't reproduce this in the latest build for me either.  Just to confirm:

 * If you try the dump (not the game) in the latest git build, does it reproduce for you?  Maybe there's a bug with the dump/compat flags.
 * If you try with default settings (easy way: put PPSSPP and assets in a new folder and run the game there), is it the same?  Maybe somehow dependent on a setting?

Just trying to figure out what's different.  Seems like some kind of testing, so maybe it has to do with alpha or depth (though based on your latest update, lighting could be suspect too.)  I tried on Direct3D 11 with both NVIDIA and Intel.

-[Unknown]

**Comment by ANR2ME** [comment]
Ah you're right, i can't reproduce it with the dump on a new folder, i was testing it directly from ppsspp project before.

**Comment by unknownbrackets** [comment]
That doesn't mean it's not a bug.  If it's a setting, it might be a bug in that setting.  Maybe the vertex shader changes improperly accounted for that setting.

-[Unknown]

**Comment by ANR2ME** [comment]
Software Skinning is affecting it if i disabled it i can reproduce it.

**Comment by unknownbrackets** [comment]
This is caused by expandAllWeightsToFloat, which I'm thinking we might just enable everywhere.  Downside: we haven't jitted the ARM funcs for this in the vertex decoder (because they were unused.)

-[Unknown]
