### ISSUE TITLE
Relocate folders on a Mac?

### ISSUE THREAD

**Issue by tycooko** [hrydgard/ppsspp#13919]
Is it possible to change the software's folders location on a Mac? Especially considering that their current default position is hidden and it's not super easy/comfortable/practical to save ROMs in PPSSPP's root (or did I miss an "import" feature somewhere?)  and that all other emulators save everything in [user]/Library/Application Support.

**Comment by hrydgard** [comment]
Yeah, the choice we made to put it in .config/ is maybe not right for Mac.

**Comment by unknownbrackets** [comment]
There are pros and cons to it being shared between installs on Linux/macOS, but I'd think it might be better to put it in Documents than in Library/Application Support.  Similar to Windows, where we don't put it in App Data.

-[Unknown]
