### ISSUE TITLE
[Android]Higher GPU usage on Vulkan

### ISSUE THREAD

**Issue by GuilhermeGS2** [hrydgard/ppsspp#13913]
I noticed OpenGL API perform better than Vulkan on both my devices, S10 Lite with Snapdragon 855 and Redmi Note 6 Pro with Snapdragon 636. After updating my S10 Lite for Android 11 with latest Vulkan drivers, my Vulkan performance improved very much, but Vulkan still has higher GPU usage compared to OpenGL.

I use Midnight Club 3 to test performance as it's a very demanding title, on Android 10 I had no problem to run at 60 FPS with OpenGL while Vulkan was running with 40 FPS, even at 1xPSP resolution. After the update, it runs at 60 FPS with both APIs, but I get like 55% GPU usage on OpenGL and 60% on Vulkan (4xPSP resolution) for same sceene. On Note 6 Pro I get like 50-55 FPS at 2xPSP resolution running with OpenGL and 45-50 FPS with Vulkan (using 1.1.128 Vulkan drivers, was worse with 1.1.87), the GPU usage on OpenGL is 80% and Vulkan is 90%. 

God of War Chains of Olympus's main menu runs with 40% GPU usage with OpenGL and 50% with Vulkan (also 4xPSP) on S10 Lite, both run at full speed. On Note 6 Pro I have 60% of GPU usage on OpenGL and 85% on Vulkan (2xPSP resolution), also full speed. 

Both devices are on Android 11, the S10 Lite has official Android 11 update while Note 6 Pro uses AOSP. S10 Lite has latest OpenGL driver V@502 and I use magisk driver V@474 for Note 6 Pro. Both devices are running Vulkan 1.1.128.

I don't think Vulkan should be the default API on Android, at least not for Adreno GPUs. I don't know about Mali and PowerVR, but Vulkan drivers are still too buggy on Adreno, even OpenGL drivers aren't too good.

EDIT: I couldn't measure CPU usage on Redmi Note 6 Pro, but on S10 Lite the GPUWatch reports pretty much same CPU usage for both APIs, the difference stands on GPU usage.

**Comment by unknownbrackets** [comment]
It's very likely this is down to drivers on the device.  I don't know that we can do anything about this.

There are differences in Vulkan vs OpenGL features and we may actually be using more features on Vulkan (such as depth clamp or dual source alpha.)  This is just up to what your drivers can expose to PPSSPP.  That could impact speed too.

-[Unknown]

**Comment by hrydgard** [comment]
Since the actual difference in performance is rarely very strongly in favor of OpenGL, I want Vulkan to be the default, in order to exercise it as much as possible. It is the API "of the future" for PPSSPP.

That said, there are few optimizations left that the OpenGL driver might be doing that we are missing out on in Vulkan since we'd need to do it manually, such as not having a depth buffer at all in some render passes (so it doesn't need to be written back), etc.

**Comment by UbiSergei** [comment]
It Uses More Power..

Vulkan Is Better Now.

**Comment by Gamemulatorer** [comment]
Vulkan on my Redmi Note 9 is perform better compare to OpenGL also VK use less power unlike OGL.

**Comment by Gamemulatorer** [comment]
This still valid as an issue?

**Comment by hrydgard** [comment]
Hopefully recent improvements should have gotten us to parity or better even on those Adrenos. I don't have any more obvious big improvements planned, so closing.
