### ISSUE TITLE
Mhfu sound squeaking sound and fps drops in snapdragon 636 4Gb ram

### ISSUE THREAD

**Issue by Davidcard22** [hrydgard/ppsspp#13912]
### What happens?
the emulator is experiencing FPS drops in the game Monsters Hunter freedom United, FPS is stable but all of a sudden it feeds at 35fps it causes little lag but bothers during fights against Monst
### What *should* happen?
Perhaps it would be good to add an option to leave games with a maximum of 31 FPS, not least because most of them run at this speed, but it is possible to increase the FPS using 333+ settings But all Monster Hunter games run only at 30fps
### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

My system is Android 10, ppsspp v1.10.3
 Snapdragon 636 1.8ghz 4gb Ram

**Comment by Davidcard22** [comment]
when the FPS goes up from 30 ~ 31 FPS to 35fps there is a slight crash and usually disappears when we enter the training area  Or when a monster arrives on the map

**Comment by Panderner** [comment]
@Davidcard22 can you record the internal sound?

**Comment by Davidcard22** [comment]
https://youtu.be/agEocsX5bLk

**Comment by Davidcard22** [comment]
[recording.zip](https://github.com/hrydgard/ppsspp/files/5810728/recording.zip)

**Comment by unknownbrackets** [comment]
PSP games produce sound in tiny bursts while they are doing other things, like rendering.  If the game isn't running at full speed, it won't produce sound properly, and you'll get weird sound problems.

You should enable frameskip if necessary to keep speed up.  Make sure texture scaling and other heavy settings are disabled.  Several settings (especially that one) make things slower when things come on screen or animations show, but don't have a constant FPS impact.  You're probably dropping frames and then seeing a spike when it gets faster.

This may also be related to device thermal throttling.  The best solution to this is to enable "sustained performance" mode.

-[Unknown]

**Comment by Gamemulatorer** [comment]
@Davidcard22 what graphics backend are you using OpenGL or Vulkan?

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
