### ISSUE TITLE
resistance retribution (stays on checking memory stick)

### ISSUE THREAD

**Issue by brujo5** [hrydgard/ppsspp#13917]
resistance retribution it stays in verifying memory stick and does not go from there. If I remember correctly, this game worked perfectly before. some recent change related to storage caused it. 
for now it is unplayable.
![Captura de pantalla (72)](https://user-images.githubusercontent.com/4172898/104521159-990cdd80-55b9-11eb-8570-5a64e5062518.png)

ppsspp log 
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/5811469/ppsspplog.zip)

windows 8.1 pro
intel hd
ppsspp v1.10.3-1552-g19313aaab

**Comment by Panderner** [comment]
@brujo5 can you find out where the last build worked?

**Comment by Panderner** [comment]
@brujo5 why are you closing this?

**Comment by brujo5** [comment]
I forgot I had a specific setting in that game. Sorry it was my mistake.

**Comment by hrydgard** [comment]
What specific setting?

**Comment by brujo5** [comment]
I had forgotten that I had assigned the buttons to my right stick (more comfortable for FPS games) and that is why when I pressed the x button nothing happened. I thought it was another problem lol. sorry for the confusion.
