### ISSUE TITLE
Rockman Dash 1 and 2 graphics broken since v1.10.3-1000-g349fc7071

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#13910]
This issue has graphics glitches for Rockman Dash games for Vulkan.

Rockman Dash 1:
![Screenshot_2021-01-12-07-40-42-992_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/104251492-d0d92f80-54aa-11eb-8ab9-bd653dd6bc03.jpg)
![Screenshot_2021-01-12-07-47-05-463_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/104251511-dafb2e00-54aa-11eb-8199-36cd3be02946.jpg)
![Screenshot_2021-01-12-07-47-14-876_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/104251526-e2bad280-54aa-11eb-96c4-0821300b7a78.jpg)

Rockman Dash 2:
![Screenshot_2021-01-12-07-40-54-143_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/104251566-f82ffc80-54aa-11eb-843d-65d5b1d06dfa.jpg)
![Screenshot_2021-01-12-07-41-13-345_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/104251578-ffefa100-54aa-11eb-969a-f41821bb5a4f.jpg)
![Screenshot_2021-01-12-07-47-31-385_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/104251586-0716af00-54ab-11eb-85f3-144a08697363.jpg)

Last build work: v1.10.3-987-g327eb21e0
First bad: v1.10.3-1000-g349fc7071

**Comment by ANR2ME** [comment]
I think you need to mention your device model too, just in case it's specific to certain GPU brand/type.

**Comment by Panderner** [comment]
I'm using POCO M3 and here's a GE Dumps: 
[Rockman Dash 1.zip](https://github.com/hrydgard/ppsspp/files/5799279/Rockman.Dash.1.zip)
[Rockman Dash 2.zip](https://github.com/hrydgard/ppsspp/files/5799280/Rockman.Dash.2.zip)

**Comment by Panderner** [comment]
This only happens in Vulkan but it does not happen in OpenGL

**Comment by ANR2ME** [comment]
I can't reproduce this issue using default graphic settings on Windows/Geforce's Vulkan, i guess it's specific for certain GPU

**Comment by Panderner** [comment]
> I can't reproduce this issue using default graphic settings on Windows/Geforce's Vulkan, i guess it's specific for certain GPU
> 
> ![image](https://user-images.githubusercontent.com/7974720/104265447-37b51380-54c0-11eb-9190-c75c45ac837b.png)
> ![image](https://user-images.githubusercontent.com/7974720/104265460-3f74b800-54c0-11eb-816f-2c4016b3c2b8.png)
> 
> Btw, does GE frame dump can be loaded/replayed using Android version? How?

I used http://ppsspp-debugger.unknownbrackets.org/ to create GE dumps using Android device and I uploaded to this issue

**Comment by hrydgard** [comment]
That commit range makes https://github.com/hrydgard/ppsspp/pull/13576 likely.

**Comment by hrydgard** [comment]
So the fragment state for the drawn stuff is that it's using color test != 0, and color doubling. It's using a CLUT4 texture with an 1555 palette, so we'll end up using a 1555 vulkan texture. We compile the color test to repeated comparison < 1/255. 

I guess the way we compile color tests on vulkan changed, to be more sensitive to a color precision issue in the shader.

We probably should do like Dolphin and change all in-shader color computation to integer to avoid this kind of issue, but it would probably lose us performance on some chips.... In the meantime, I'm gonna see if I can figure out how to restore the old behavior.

POCO M3 has an Adreno phone so next I'll try to use one to reproduce.

**Comment by sum2012** [comment]
@ANR2ME  load GE frame dump file as iso

**Comment by hrydgard** [comment]
Ok, on the F1, I can reproduce perfectly. Disabling 16-bit texture formats doesn't help so it's likely not a precision issue, but a shader compiler bug that we're triggering.

I'm going to reapply the old workaround that we had in the Vulkan shader generator - summing together r,g,b before comparing, instead of comparing the rgb components one by one. This should actually be perfectly fine, but I'll selectively apply it only for Vulkan to avoid any other wacky breakage...
