### ISSUE TITLE
Space Invaders Extreme Sprites are not transparent for Vulkan

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#13923]
Look at the screenshot below:
![Screenshot_2021-01-16-18-30-54-425_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/104809566-3faae580-5829-11eb-91f9-c6c4b994ca5b.jpg)

Last build work: v1.10.3-987-g327eb21e0
First bad: v1.10.3-1000-g349fc7071

**Comment by hrydgard** [comment]
GE dump?

Seems likely to be the same issue as #13910 .

**Comment by Panderner** [comment]
Oh here's a GE dump: 
[Dump.zip](https://github.com/hrydgard/ppsspp/files/5824218/Dump.zip)
