### ISSUE TITLE
can't create assets when building in iOS

### ISSUE THREAD

**Issue by Richter-Ko** [hrydgard/ppsspp#13934]
### What happens?

the error will be shown when building in iOS:

PhaseScriptExecution CMake\ PostBuild\ Rules /Users/xxx/Documents/Xcode/ppsspp/ppsspp/build-ios/PPSSPP.build/Debug-iphoneos/PPSSPP.build/Script-85919161E6AF40CDAAC21D52.sh (in target 'PPSSPP' from project 'PPSSPP')
    cd /Users/xxx/Documents/Xcode/ppsspp/ppsspp
    /bin/sh -c /Users/xxx/Documents/Xcode/ppsspp/ppsspp/build-ios/PPSSPP.build/Debug-iphoneos/PPSSPP.build/Script-85919161E6AF40CDAAC21D52.sh

/Users/xxx/Documents/Xcode/ppsspp/ppsspp/build-ios/PPSSPP.build/Debug-iphoneos/PPSSPP.build/Script-85919161E6AF40CDAAC21D52.sh: line 5: TARGET_BUILD_DIR: command not found
/Users/xxx/Documents/Xcode/ppsspp/ppsspp/build-ios/PPSSPP.build/Debug-iphoneos/PPSSPP.build/Script-85919161E6AF40CDAAC21D52.sh: line 5: FULL_PRODUCT_NAME: command not found
/Users/xxx/Documents/Xcode/ppsspp/ppsspp/build-ios/PPSSPP.build/Debug-iphoneos/PPSSPP.build/Script-85919161E6AF40CDAAC21D52.sh: line 6: TARGET_BUILD_DIR: command not found
/Users/xxx/Documents/Xcode/ppsspp/ppsspp/build-ios/PPSSPP.build/Debug-iphoneos/PPSSPP.build/Script-85919161E6AF40CDAAC21D52.sh: line 6: FULL_PRODUCT_NAME: command not found
assets/: Can't create 'assets'
assets/Icon.png: Failed to create dir 'assets'
assets/compat.ini: Failed to create dir 'assets'
assets/rargray.png: Failed to create dir 'assets'
assets/zip.png: Failed to create dir 'assets'
assets/Icon-72@3x.png: Failed to create dir 'assets'
assets/sfx_confirm.wav: Failed to create dir 'assets'
assets/sfx_back.wav: Failed to create dir 'assets'
assets/unknown.png: Failed to create dir 'assets'
assets/sfx_toggle_on.wav: Failed to create dir 'assets'
assets/flash0/: Failed to create dir 'assets'
assets/Icon-72.png: Failed to create dir 'assets'
assets/Roboto-Condensed.ttf: Failed to create dir 'assets'
assets/Icon-72@2x.png: Failed to create dir 'assets'
assets/icon_regular_72.png: Failed to create dir 'assets'
assets/Icon@2x.png: Failed to create dir 'assets'
assets/lang/: Failed to create dir 'assets'
assets/logo.png: Failed to create dir 'assets'
assets/ui_atlas.zim: Failed to create dir 'assets'
assets/shaders/: Failed to create dir 'assets'
assets/sfx_select.wav: Failed to create dir 'assets'
assets/Icon@3x.png: Failed to create dir 'assets'
assets/ppge_atlas.zim: Failed to create dir 'assets'
assets/ppge_atlas.meta: Failed to create dir 'assets'
assets/sfx_toggle_off.wav: Failed to create dir 'assets'
assets/ui_atlas.meta: Failed to create dir 'assets'
assets/langregion.ini: Failed to create dir 'assets'
assets/gamecontrollerdb.txt: Failed to create dir 'assets'
assets/7z.png: Failed to create dir 'assets'
assets/shaders/videoAA.fsh: Failed to create dir 'assets'
assets/shaders/5xBR-lv2.fsh: Failed to create dir 'assets'
assets/shaders/fxaa.fsh: Failed to create dir 'assets'
assets/shaders/upscale_spline36.vsh: Failed to create dir 'assets'
assets/shaders/vignette.fsh: Failed to create dir 'assets'
assets/shaders/bloom.fsh: Failed to create dir 'assets'
assets/shaders/cartoon.fsh: Failed to create dir 'assets'
assets/shaders/naturalA.vsh: Failed to create dir 'assets'
assets/shaders/4xhqglsl.vsh: Failed to create dir 'assets'
assets/shaders/colorcorrection.fsh: Failed to create dir 'assets'
assets/shaders/aacolor.fsh: Failed to create dir 'assets'
assets/shaders/natural.vsh: Failed to create dir 'assets'
assets/shaders/5xBR.fsh: Failed to create dir 'assets'
assets/shaders/crt.fsh: Failed to create dir 'assets'
assets/shaders/upscale_spline36.fsh: Failed to create dir 'assets'
assets/shaders/GaussianDownscale.fsh: Failed to create dir 'assets'
assets/shaders/4xhqglsl.fsh: Failed to create dir 'assets'
assets/shaders/naturalA.fsh: Failed to create dir 'assets'
assets/shaders/cartoon.vsh: Failed to create dir 'assets'
assets/shaders/inversecolors.fsh: Failed to create dir 'assets'
assets/shaders/fxaa.vsh: Failed to create dir 'assets'
assets/shaders/grayscale.fsh: Failed to create dir 'assets'
assets/shaders/scanlines.fsh: Failed to create dir 'assets'
assets/shaders/defaultshaders.ini: Failed to create dir 'assets'
assets/shaders/psp_color.fsh: Failed to create dir 'assets'
assets/shaders/aacolor.vsh: Failed to create dir 'assets'
assets/shaders/natural.fsh: Failed to create dir 'assets'
assets/shaders/sharpen.fsh: Failed to create dir 'assets'
assets/shaders/tex_4xbrz.csh: Failed to create dir 'assets'
assets/shaders/5xBR.vsh: Failed to create dir 'assets'
assets/lang/it_IT.ini: Failed to create dir 'assets'
assets/lang/ja_JP.ini: Failed to create dir 'assets'
assets/lang/fa_IR.ini: Failed to create dir 'assets'
assets/lang/vi_VN.ini: Failed to create dir 'assets'
assets/lang/ro_RO.ini: Failed to create dir 'assets'
assets/lang/es_ES.ini: Failed to create dir 'assets'
assets/lang/pl_PL.ini: Failed to create dir 'assets'
assets/lang/th_TH.ini: Failed to create dir 'assets'
assets/lang/nl_NL.ini: Failed to create dir 'assets'
assets/lang/fr_FR.ini: Failed to create dir 'assets'
assets/lang/gr_EL.ini: Failed to create dir 'assets'
assets/lang/tg_PH.ini: Failed to create dir 'assets'
assets/lang/xxx_KR.ini: Failed to create dir 'assets'
assets/lang/de_DE.ini: Failed to create dir 'assets'
assets/lang/he_IL.ini: Failed to create dir 'assets'
assets/lang/en_US.ini: Failed to create dir 'assets'
assets/lang/sv_SE.ini: Failed to create dir 'assets'
assets/lang/id_ID.ini: Failed to create dir 'assets'
assets/lang/jv_ID.ini: Failed to create dir 'assets'
assets/lang/zh_TW.ini: Failed to create dir 'assets'
assets/lang/ms_MY.ini: Failed to create dir 'assets'
assets/lang/fi_FI.ini: Failed to create dir 'assets'
assets/lang/zh_CN.ini: Failed to create dir 'assets'
assets/lang/hr_HR.ini: Failed to create dir 'assets'
assets/lang/az_AZ.ini: Failed to create dir 'assets'
assets/lang/uk_UA.ini: Failed to create dir 'assets'
assets/lang/README.md: Failed to create dir 'assets'
assets/lang/es_LA.ini: Failed to create dir 'assets'
assets/lang/hu_HU.ini: Failed to create dir 'assets'
assets/lang/no_NO.ini: Failed to create dir 'assets'
assets/lang/dr_ID.ini: Failed to create dir 'assets'
assets/lang/da_DK.ini: Failed to create dir 'assets'
assets/lang/pt_BR.ini: Failed to create dir 'assets'
assets/lang/gl_ES.ini: Failed to create dir 'assets'
assets/lang/he_IL_invert.ini: Failed to create dir 'assets'
assets/lang/ru_RU.ini: Failed to create dir 'assets'
assets/lang/ar_AE.ini: Failed to create dir 'assets'
assets/lang/tr_TR.ini: Failed to create dir 'assets'
assets/lang/cz_CZ.ini: Failed to create dir 'assets'
assets/lang/lo_LA.ini: Failed to create dir 'assets'
assets/lang/lt-LT.ini: Failed to create dir 'assets'
assets/lang/ca_ES.ini: Failed to create dir 'assets'
assets/lang/pt_PT.ini: Failed to create dir 'assets'
assets/lang/bg_BG.ini: Failed to create dir 'assets'
assets/flash0/font/: Failed to create dir 'assets'
assets/flash0/font/ltn12.pgf: Failed to create dir 'assets'
assets/flash0/font/ltn13.pgf: Failed to create dir 'assets'
assets/flash0/font/ltn11.pgf: Failed to create dir 'assets'
assets/flash0/font/ltn10.pgf: Failed to create dir 'assets'
assets/flash0/font/ltn14.pgf: Failed to create dir 'assets'
assets/flash0/font/ltn9.pgf: Failed to create dir 'assets'
assets/flash0/font/ltn8.pgf: Failed to create dir 'assets'
assets/flash0/font/ltn15.pgf: Failed to create dir 'assets'
assets/flash0/font/kr0.pgf: Failed to create dir 'assets'
assets/flash0/font/jpn0.pgf: Failed to create dir 'assets'
assets/flash0/font/ltn6.pgf: Failed to create dir 'assets'
assets/flash0/font/ltn7.pgf: Failed to create dir 'assets'
assets/flash0/font/ltn5.pgf: Failed to create dir 'assets'
assets/flash0/font/ltn4.pgf: Failed to create dir 'assets'
assets/flash0/font/ltn0.pgf: Failed to create dir 'assets'
assets/flash0/font/ltn1.pgf: Failed to create dir 'assets'
assets/flash0/font/ltn3.pgf: Failed to create dir 'assets'
assets/flash0/font/ltn2.pgf: Failed to create dir 'assets'
Default-568h@2x.png: Can't create 'Default-568h@2x.png'
Default-568h@3x.png: Can't create 'Default-568h@3x.png'
tar: Error exit delayed from previous errors.
Command PhaseScriptExecution failed with a nonzero exit code

### What *should* happen?
build successfully

### What hardware, operating system, and PPSSPP version?  On desktop and mobile phone, GPU matters for graphical issues.
Xcode 12.3
masOS catalina
PPSSPP 1.10.3

**Comment by hrydgard** [comment]
I merged a fix for this.
