### ISSUE TITLE
scooby doo who's watching who (perfomance issue OpenGL vs DX11)

### ISSUE THREAD

**Issue by brujo5** [hrydgard/ppsspp#13942]
As the title says there is a performance problem where opengl wins by 10-15fps + over dx11.

opengl defaul settings
![Captura de pantalla (78)](https://user-images.githubusercontent.com/4172898/104946032-bacde200-5976-11eb-91fe-bc1ab38316fa.png)

dx11 default settings
![Captura de pantalla (80)](https://user-images.githubusercontent.com/4172898/104946067-c4574a00-5976-11eb-9d9f-3572b3ea4be1.png)

dx11 frame drops log [ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/5831659/ppsspplog.zip)

ppsspp v1.10.3-1594-gd70214ce7
windows 8.1 pro
intel hd
8 gb ram

**Comment by unknownbrackets** [comment]
Isn't this the same as #13871?  I realize it doesn't affect all games evenly.

It may just be the Intel driver being terrible.

-[Unknown]

**Comment by brujo5** [comment]
i would say no.
 #13871 it is due to hardware transform.

**Comment by UbiSergei** [comment]
OpenGL Has Trinagle Skuares

Page Microsoft

**Comment by unknownbrackets** [comment]
Is performance any better now in this game in recent git builds, with lighting and other changes?

-[Unknown]

**Comment by brujo5** [comment]
I no longer have this hardware so I close it. Thank you
