### ISSUE TITLE
Split-Second Missing HUD for 3rd person view

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#13957]
I tried OpenGL and Vulkan the HUD for 3rd person view in Split-Second is broken in latest builds of PPSSPP

Here's a comparison:

v1.10.3-352-gd90630c26 and newer: 
![Screenshot_2021-01-22-12-49-33-907_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/105448302-0c48da80-5cb1-11eb-8c26-43d93719b20e.jpg)

v1.10.3-348-gdd79d33f1 and older: 
![Screenshot_2021-01-22-12-40-31-719_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/105448338-1f5baa80-5cb1-11eb-8a26-d53f0b41616e.jpg)

Here's a GE dump: 
[ULUS10513_0001.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/5853665/ULUS10513_0001.ppdmp.zip)

**Comment by hrydgard** [comment]
Thanks for the nice bug report :)

**Comment by hrydgard** [comment]
Changing

```
WARN_LOG_ONCE(diffFormat1, G3D, "Texturing from framebuffer with reinterpretable format: %s != %s", GeTextureFormatToString(entry.format), GeBufferFormatToString(framebuffer->format));
return FramebufferMatchInfo{ FramebufferMatch::VALID, 0, 0, true, TextureFormatToBufferFormat(entry.format) };
```
to
```
return FramebufferMatchInfo{ FramebufferMatch::VALID };
```
in MatchFramebuffer "fixes" the issue. Hm.

**Comment by hrydgard** [comment]
OK this is another game that renders reflections to spheremaps like Outrun, and it does it in the same render target it uses to render the 3D HUD thing. The rendering results in lots of "color reinterprets", some wastefully large due to the detected render target size. Anyway, doing it fixes the game so I'm just gonna enable it. I don't think the performance hit will be that bad....

(Curiously, enabling ShaderColorBitmask too breaks transparency of the 3D HUD... very odd, should probably be investigated at some point).

**Comment by UbiSergei** [comment]
OpenGL Can't firm Like Vulcan..

**Comment by Panderner** [comment]
Enabling ReinterpretFramebuffers for this game makes the graphics worse but the HUD displays
![Screenshot_2021-01-24-02-53-21-585_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/105611341-9434fe80-5def-11eb-9161-740fe3dfdce7.jpg)

**Comment by hrydgard** [comment]
Worse in what way? I don't see much of a difference..

**Comment by Panderner** [comment]
This how it looks like in real hardware
![IMG_20210124_114735](https://user-images.githubusercontent.com/37503397/105620642-fd416400-5e39-11eb-88b2-c7bffc33f94f.jpg)

**Comment by ANR2ME** [comment]
> 
> 
> Enabling ReinterpretFramebuffers for this game makes the graphics worse but the HUD displays
> ![Screenshot_2021-01-24-02-53-21-585_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/105611341-9434fe80-5def-11eb-9161-740fe3dfdce7.jpg)

Is this screenshot taken on Vulkan? Does OpenGL didn't show the bloom either?

**Comment by unknownbrackets** [comment]
Hm, this dump doesn't play back correctly on a PSP:
![playback expected](https://user-images.githubusercontent.com/191233/105645070-3683cf00-5e4e-11eb-93fc-b69f1ca1e25a.png)

I do see the circles below the car though.  I can't tell if the shading is also wrong because of the dump problem.  The tool I use to playback the frame dumps can't handle dumps that take too much RAM well, and I suspect that's what happened here.

-[Unknown]

**Comment by Panderner** [comment]
> > Enabling ReinterpretFramebuffers for this game makes the graphics worse but the HUD displays
> > ![Screenshot_2021-01-24-02-53-21-585_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/105611341-9434fe80-5def-11eb-9161-740fe3dfdce7.jpg)
> 
> Is this screenshot taken on Vulkan? Does OpenGL didn't show the bloom either?

Yes, I'm using Vulkan for this screenshot and also OpenGL

**Comment by hrydgard** [comment]
It uses exactly the same trick as Outrun to draw into the alpha channel of the reflection map that it (very inefficiently) builds. Additionally, it uses it to draw alpha masks into the HUD digits which are in the same texture used for the reflection map. Our in-shader blending used when masking is on seems to screw something up there and write full blue instead of a gradient, resulting in ugly black boxes if I turn on masking. Maybe we don't handle the case of blend+mask yet. Lots going on.

I don't know how to rescue this for 1.11 without awful hacks...

**Comment by Panderner** [comment]
Software Rendering looks like this:
![Screenshot (6)](https://user-images.githubusercontent.com/37503397/113670558-de880500-96e7-11eb-8feb-b86d38e9f023.png)

**Comment by Gamemulatorer** [comment]
Added this game id to ReinterpretFramebuffers fixes the hud but still not look rights compare to psp.

**Comment by hrydgard** [comment]
yeah, it's doing a lot of wacky stuff with framebuffer format reinterpretation (rendering to a RGBA4444 framebuffer as if it was 565 with a mask to render to alpha which the PSP doesn't support, just like outrun, and that's just the start - it does other stuff as well). Previously it mostly worked by accident.

**Comment by Gamemulatorer** [comment]
Just for comparison 🤔

**Comment by Gamemulatorer** [comment]
Is https://github.com/hrydgard/ppsspp/pull/5679/commits/9a4c17e2eefaaab9c2d01f57288523816d35b5a8 could maybe help this issue but why it wasn't merge 🤔

**Comment by unknownbrackets** [comment]
That's a very old commit that attempted to "fix" this by just tracking different framebuffers with different formats completely separately.  Especially now, it would break a lot of things, including depal, render to texture, and block transfer.  I also don't think that would fix this issue.

-[Unknown]

**Comment by DAZ3R** [comment]
How this bug? 
Sorry I'am new

**Comment by XiaomiRedmi9** [comment]
> How this bug?
> Sorry I'am new

Try this game using the latest ppsspp development apk.

**Comment by kkp9199** [comment]
> > How this bug?
> > Sorry I'am new
> 
> Try this game using the latest ppsspp development apk.

Not fixed yet in latest development build.

**Comment by hrydgard** [comment]
Right, it's not fixed yet. It's a complicated one.

**Comment by hrydgard** [comment]
Unfortunately this will have to wait for later, any fix for this will be too risky for 1.12, I think (risk of breaking other games)

**Comment by Gamemulatorer** [comment]
Put this game id again in ReinterpretFramebuffers as a temporary solution?

**Comment by hrydgard** [comment]
Doesn't quite solve it, or does it for you?

**Comment by Panderner** [comment]
Unfortunately enabling ReinterpretFramebuffers cause graphical glitches for this game still happens in latest build:
![Screenshot (15)](https://user-images.githubusercontent.com/37503397/132949115-05f6f7af-fbe2-4654-b14d-a0f5b17b98e4.png)

**Comment by Gamemulatorer** [comment]
SW Rendering is also glitchy.
![Screenshot_2021-09-11-21-50-37-894_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/132950185-dde2239d-aaec-4b78-b46d-650c0eaa0cd8.jpg)

**Comment by Gamemulatorer** [comment]
> ReinterpretFramebuffers + ShaderColorBitmask
**OpenGL**
 ![Screenshot_2021-10-07-00-03-03-302_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/136241522-ac1b7a74-92a8-40cf-9ff4-0f127ea4cb2c.jpg)

Vulkan is crashing if ShaderColorBitmask+ReinterpretFramebuffers is enable on this game.
[Uploading logcat_10-07-2021_00-10-28.txt…]()

**Comment by Panderner** [comment]
When i enabled ShaderColorBitmask and ReinterpretFramebuffers for this game it doesn't crash for my PC using Vulkan but there are an odd chance to critical textbox to appear:
![Screenshot (37)](https://user-images.githubusercontent.com/37503397/136246592-fa33b7e5-8ba4-4459-b031-c7c0dbcd3bd5.png)

**Comment by Gamemulatorer** [comment]
I don't know why this game hang in race and I also remove all compatibility tweaks 🤔
Im using the latest ppsspp build for android.

https://user-images.githubusercontent.com/37603562/145676493-0d62188c-6b14-4fa5-8c26-a5ada59f0ef2.mp4

Vulkan backend and default settings.

**Comment by hrydgard** [comment]
bumping to 1.13.0 for the crash, maybe will get to fixing the HUD too, let's see.

**Comment by Ac-Gamer** [comment]
So like, how do I fix this bug? im in version 1.12.3, is the HUD issue resolved in the latest version?

**Comment by Scar557** [comment]
Not fixed yet.

**Comment by Panderner** [comment]
It's now fixed in latest builds:
![Screenshot_2022-04-29-14-55-31-786_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/165898497-630fd15b-a3f3-478d-9221-eaab3246fc19.jpg)

**Comment by Gamemulatorer** [comment]
> It's now fixed in latest builds: ![Screenshot_2022-04-29-14-55-31-786_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/165898497-630fd15b-a3f3-478d-9221-eaab3246fc19.jpg)

Can you test the latest build @Panderner?
