### ISSUE TITLE
Ppsspp is unable to read externa sd card/memory card fix it

### ISSUE THREAD

**Issue by tausifj15** [hrydgard/ppsspp#13955]

**Comment by hrydgard** [comment]
It an issue with Android 11. We have a fix in the newest version from https://buildbot.orphis.net/ppsspp/ . Use the browse button to select your SD card.

Please re-open if that doesn't work for you. 1.11 with the fix will be released soon.

**Comment by tausifj15** [comment]
I'm already on latest build it's not working when i choose storage it
doesn't show anything only internal storage

**Comment by hrydgard** [comment]
You sure? Take as screenshot.

Anyway, if that doesn't help, there's nothing else we can do as far as I know...

**Comment by tausifj15** [comment]
Are you talking about yesterday's build?

**Comment by hrydgard** [comment]
any from the last few days

**Comment by tausifj15** [comment]
Working on yesterday's build thanks
Once again hrydgard saves the day
