### ISSUE TITLE
Not sure if this has been asked if it is please tell me and im sorry

### ISSUE THREAD

**Issue by Doom306** [hrydgard/ppsspp#13966]
When I run GTA LCS PPSSPP (free) on my phone It lags a lot..... Though in my android it works smoothly.
So does any of you know the best setting..

Another one is when we start the game (gta lcs) multiplayer in PPSSPP it say disconnected and sometimes it crashes.... Does any of you know what settings to use?

The phone is apple iphone 8.
The android is Samsung J8

Thanks!
Sorry if this has been asked

**Comment by ANR2ME** [comment]
Please use the latest version from https://buildbot.orphis.net/ppsspp/ it's has more adhoc fixes.

Regarding performance on iphone, not sure, but you can try getting a more recent dev builds (i think someone host it somewhere)

**Comment by unknownbrackets** [comment]
It's better to ask questions like this on [the forum](http://forums.ppsspp.org/) or [Discord](https://discord.gg/5NJB6dD).

PPSSPP is not really "allowed" to run on iOS by the maker of iOS.  There are often fixes to the iOS operating system that make PPSSPP run worse.  So unfortunately it's to be expected that it won't run as well, in general.

-[Unknown]

**Comment by Doom306** [comment]
Thx yall

**Comment by ANR2ME** [comment]
@Doom306  you can refer to the tutorial here http://forums.ppsspp.org/showthread.php?tid=26826 
or ask in PPSSPP discord #multiplayer channel https://discordapp.com/channels/293316141479362560/508350481437818880

**Comment by Doom306** [comment]
Thx
