### ISSUE TITLE
Remove #include <KHR/khrplatform.h>

### ISSUE THREAD

**Issue by glebm** [hrydgard/ppsspp#13978]
I've noticed that PPSSPP includes the `<KHR/khrplatform.h>` header in 2 places.
This header should not be included directly.

1. https://github.com/hrydgard/ppsspp/blob/1b843ef8ccc41f41e1437751712c816a6fef77b3/Common/GPU/OpenGL/GLCommon.h#L12

2. https://github.com/hrydgard/ppsspp/blob/a1964ca1a108b1340e54ae30262f317c9dd6999b/ext/glew/GL/eglew.h#L106

Source: https://github.com/rockchip-linux/libmali/issues/66#issuecomment-767218749

**Comment by unknownbrackets** [comment]
The second looks to be upstream:
https://github.com/nigels-com/glew/blob/8c88a0858f33879ea693f89ef43b3d77c968806e/auto/src/eglew_head.h#L27

But the first is easy enough to remove.  And not every platform uses glew.

-[Unknown]

**Comment by unknownbrackets** [comment]
Does it compile now on that device?  I assume Mali means it's not gonna use glew.

-[Unknown]

**Comment by glebm** [comment]
I'm testing the build now and I've filed an issue in GLEW (https://github.com/hrydgard/ppsspp/issues/13991)

**Comment by glebm** [comment]
It builds (we don't use GLEW)

**Comment by glebm** [comment]
Oh I filed the issue in the wrong repo :facepalm:

**Comment by glebm** [comment]
Filed https://github.com/nigels-com/glew/issues/295

**Comment by hrydgard** [comment]
Don't think there's more to do here for us, closing.
