### ISSUE TITLE
Ys Seven missing save icon screenshot

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#13975]
After enabled BlockTransferAllowCreateFB for Ys Seven it cause graphical glitch that save icon screenshot appears to be black screen

BlockTransferAllowCreateFB on:
![IMG_20210125_171929](https://user-images.githubusercontent.com/37503397/105685870-8c7d7300-5f31-11eb-8cbf-3107708dc0a1.jpg)

BlockTransferAllowCreateFB off:
![IMG_20210125_172257](https://user-images.githubusercontent.com/37503397/105686285-07468e00-5f32-11eb-9de0-64137d71321b.jpg)

**Comment by Gamemulatorer** [comment]
@unknownbrackets already mention that enable block transfer effects has a negative effects on save icon image.

https://github.com/hrydgard/ppsspp/issues/11669#issuecomment-450014049

**Comment by hrydgard** [comment]
Yeah, that's a natural consequence of only doing the block transfer on the GPU and not reading the data back to RAM where it can be used to make a thumbnail.

It might help to use IntraVRAMBlockTransferAllowCreateFB instead, try that.

Does BlockTransferAllowCreateFB give you a big speedup on this game or why do you want to enable it?

**Comment by Panderner** [comment]
> It might help to use IntraVRAMBlockTransferAllowCreateFB instead, try that.

Enabling IntraVRAMBlockTransferAllowCreateFB for this game had no effect.

**Comment by hrydgard** [comment]
Okay, well, then we can't use the "AllowCreateFB" hacks in this game.

**Comment by Panderner** [comment]
Why do you close this?

**Comment by hrydgard** [comment]
Is there anything more to talk about? Using the allowcreatefb hack broke the game. I don't know if we can distinguish savedata image copies from other uses of block transfer.

If you want to make a case for that, give me some numbers of the speedup you get with allowcreatefb.

**Comment by unknownbrackets** [comment]
The "BlockTransferAllowCreateFB" hack specifically means "do block transfers in a way that save icons etc. cannot work to make them faster."  If it was free, we'd just enable it everywhere.

In this specific case, the savedata icon might use a specific function we could hook to override BlockTransferAllowCreateFB.  But we'd need to check different areas, especially the magma area iirc.

-[Unknown]
