### ISSUE TITLE
[Windows/Android]Pro Yakyu Spirits 2011/2012/2013/2014 some graphics missing.

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#13980]
### What happens?
This Base Ball game appear the little field map on bottom of right side.
If there is runner on base then it will appear the yellow dot on it.
But, It's not appear correctly. 
Please, See attached screenshots & GEdump below.

GEdump here: [NPJH50336_0002.zip](https://github.com/hrydgard/ppsspp/files/5878252/NPJH50336_0002.zip)

### What *should* happen?
It should appear the mark correctly.

### Please test newest version in https://buildbot.orphis.net/ppsspp/

PPSSPP Ver.：1.10.3-1645
OS：Windows10（64-bit）Japanese
CPU：Ryzen7 3800X（8-core）
GPU：RADEON RADEON RX5700XT
Resolution：2560×1440
RAM：32GB

PPSSPP Ver.：1.10.3-1645
OS：Android 10.0
DeviceName：Samusung Galaxy S20 / SC-51A
CPU：Snapdragon865（Octa-core）
GPU：Adreno 650
Resolution：3200 x 1440 (Max)
RAM：12GB
ROM：128GB
ExternalStrage：microSDXC 512GB

**[Real PSP's ScreenShot.]**
![pro_yakyu_sprits_2011_missdot](https://user-images.githubusercontent.com/48179091/105952463-f2463800-60b4-11eb-9f04-e2ee4bab5a8f.png)

[Vulkan/Buffered rendering/Simulate Block Transfer On.]
![image](https://user-images.githubusercontent.com/48179091/105953017-d4c59e00-60b5-11eb-9401-96b9fe0a711d.png)

[It will happen the issue on "SoftwareRendering/Vulkan" too.]
![image](https://user-images.githubusercontent.com/48179091/105952676-3fc2a500-60b5-11eb-8a30-5b94629a5dde.png)

[StepDraw 197/224]
 (This point including runner's dot mark.)
![image](https://user-images.githubusercontent.com/48179091/105953447-8795fc00-60b6-11eb-97ce-880ed6916b63.png)

**Comment by unknownbrackets** [comment]
It draws the minimap BG at 187/224 and 188/224.

It uses the yellow dot portion of the texture at 199/224 (and a triangle at 198/224), But it changes the view matrix beforehand.  If I force it to skip the view matrix update it draws fine:

![forced render of yellow dots](https://user-images.githubusercontent.com/191233/112786823-f2f34000-900b-11eb-9316-1b91493fdd2e.png)

Not sure if this is some sort of CPU issue or if it's trying to use readback or something...

-[Unknown]

**Comment by nassau-tk** [comment]
@unknownbrackets 

Oh... I overlooked another.
It's a "Wind mark".
![pro_yakyu_sprits_2011_missdot](https://user-images.githubusercontent.com/48179091/112841417-6912a800-90db-11eb-83a2-f6e5b886337a.png)

Is this same cause?

**Comment by unknownbrackets** [comment]
Ah that's the triangle.  But hm.  The view matrix update definitely had it down in the bottom right corner, not over up there.

Just to confirm this the PSP renders the dump the same way:
![NPJH50336_#13980_pro_yakyu_spirits_minimap](https://user-images.githubusercontent.com/191233/112930721-ac671980-90cf-11eb-8c87-30213b32ee4b.png)

The dump only records the path taken, so it's possible this is a CALL or BJUMP or similar and the problem is there.

-[Unknown]

**Comment by unknownbrackets** [comment]
Has this changed at all?  Can you create a new frame dump either way?  The new frame dump might handle matrix updates or BJUMP more correctly given recent fixes.

-[Unknown]

**Comment by nassau-tk** [comment]
I don't know when this issue solved.

I got GE dump now.
*Pro Yakyu Spirits 2012
[NPJH50520_0001.zip](https://github.com/hrydgard/ppsspp/files/9996549/NPJH50520_0001.zip)

**Comment by unknownbrackets** [comment]
Ah, so it is working now?  Thanks.  The new frame dump renders properly on a PSP, and in software rendering / Vulkan as well.

I'm going to mark this fixed.  I suspect it might've been fixed the handling the matrix number registers more correctly, but didn't bisect or anything to check.

-[Unknown]
