### ISSUE TITLE
N.O.V.A (NOVA) -  Near Orbit Vanguard Alliance flickers

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#13989]
The game is playable but flickers, reported on Discord by Aarshayan.

Known so far:

Works on 1.3.0

Doesn't work on 1.10

**Comment by Panderner** [comment]
I can't reproduce flickering issue for this game except sky glitches
![Screenshot_2021-01-28-19-20-21-151_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/106131695-f9954080-619d-11eb-9f94-c622d9f081f7.jpg)

**Comment by Aarshayan** [comment]
I reported the flickering on discrd.
For you only the sky is glitching but for me all the surroundings glitch. I have reset the settings to default and yet the problem persists.

**Comment by Aarshayan** [comment]
I will shortly upload a clip of the problem.

**Comment by Aarshayan** [comment]
Unable to post clip but what I can say is :
Works on : 1.6.3
Flickering start from : 1.7
Glitching on : 1.8

**Comment by Aarshayan** [comment]
I am unable to upload the clip.
Works perfectly on v.16
Starts flickering slightly on v.1.7
Beyond that it flickers way to much.

**Comment by Gamemulatorer** [comment]
> I can't reproduce flickering issue for this game except sky glitches ![Screenshot_2021-01-28-19-20-21-151_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/106131695-f9954080-619d-11eb-9f94-c622d9f081f7.jpg)

Please @hrydgard add this game id to DisableRangeCulling

**Proof**
DisableRangeCulling OFF

https://user-images.githubusercontent.com/37603562/136507518-d1f49dbc-f9c6-42d9-986e-44ae4a367996.mp4

DisableRangeCulling ON

https://user-images.githubusercontent.com/37603562/136507561-84c4e29f-7c1a-479c-a268-a9b7aa7c60b8.mp4

**Comment by Gamemulatorer** [comment]
@Aarshayan try this game now using the ppsspp latest build your issue may solve.
