### ISSUE TITLE
Generating mips after a compute shader upscale causes Vulkan validation errors

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#13987]
compute leaves the textures in GENERAL layout, it seems, while GenerateMip expects TRANSFER_DST.

```
ERROR(validation:307231540) Validation Error: [ VUID-VkImageMemoryBarrier-oldLayout-01197 ] Object 0: handle = 0x18eeee3cb88, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x124ffb34 | vkCmdPipelineBarrier(): For VkImage 0x2a0b96000000d164[texture_041d7f00_CLUT4] you cannot transition the layout of aspect=1 level=0 layer=0 from VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL when the previous known layout is VK_IMAGE_LAYOUT_GENERAL. The Vulkan spec states: If srcQueueFamilyIndex and dstQueueFamilyIndex define a queue family ownership transfer or oldLayout and newLayout define a image layout transition, oldLayout must be VK_IMAGE_LAYOUT_UNDEFINED or the current layout of the image subresources affected by the barrier (https://vulkan.lunarg.com/doc/view/1.2.162.0/windows/1.2-extensions/vkspec.html#VUID-VkImageMemoryBarrier-oldLayout-01197)
```

We could probably just stick to GENERAL for uploads and mip generation. Unlikely to have a major impact on any platform.

The reason we end up generating mips in the first place is the following:

```

	// TODO
	if (scaleFactor > 1) {
		maxLevel = 0;
	}
```

We should probably upscale the mips individually instead anyway (though arguments could be made either way, I think...)

**Comment by unknownbrackets** [comment]
I guess there are three major options:
 * Upscale each level by the same factor.
 * "Push" the new layer on and "pop" the worst layer off, possibly upscaling different levels (or don't pop, adding a new mip level?)
 * Just regenerate from the upscaled version.

Upscaling each level is probably the most accurate option.  Adding new mip levels (when using > 1 level already) could be interesting, but could also expose weird bugs if there's any Peach/Bowser portrait shenanigans.

-[Unknown]

**Comment by hrydgard** [comment]
We've seen very few Peach/Bowser issues on PSP fortunately, I think one so far? (a barrier in Miami Vice). So generating mips from the top level like we do now is not unreasonable really... will probably give the best mip transitions.

So I'm probably just gonna fix the validation issue and leave the rest as is for now.

**Comment by iota97** [comment]
Out of curiosity was trying to figure out what the "Peach/Bowser portrait" was. It was like a changing portrait based on player distance so I guess it abused the mipmap by putting the 2 image as different level and make the HW interpolate? I can't really find anything online so I was wondering if my guess is right, sorry for the OT :)

**Comment by hrydgard** [comment]
That is exactly it!
