### ISSUE TITLE
Street Supremacy [ULUS10069] - black screen on latest nightly

### ISSUE THREAD

**Issue by arnoldsecret** [hrydgard/ppsspp#13996]
### What happens?
After the initial logos, it's stuck on a black screen. It's persistent on all backends.

### What *should* happen?
It should play video and go to menus as normal. Possible regression due to the game fully working on previous versions of PPSSPP.

### What hardware, operating system, and PPSSPP version?  On desktop and mobile phone, GPU matters for graphical issues.
NVIDIA Geforce 740m
Windows 10 x64
v1.10.3-1659-gbcd7856aa

**Comment by arnoldsecret** [comment]
A couple other games like EA Replay and After Burner exhibit the same issue of not going far to the menus.

**Comment by ANR2ME** [comment]
Do you know which version was the last working one? it could helped the devs to locate which commit causing the issue.

**Comment by arnoldsecret** [comment]
@ANR2ME I know that the latest stable version (1.10.3) works with Street Supremacy.

**Comment by arnoldsecret** [comment]
Last working version is v1.10.3-1389-ga13b4f751. v1.10.3-1393-g990c9650d is when it starts to get broken.

**Comment by ANR2ME** [comment]
Looks like this commit causing this issue https://github.com/hrydgard/ppsspp/commit/990c9650da32226a0fdf169390fcda7ea621af34
May be @sum2012 can figured out what's happening?

**Comment by hrydgard** [comment]
Oh no :)

**Comment by sum2012** [comment]
three log of
13:04:714 user_main    W[ME]: HLE\sceMpeg.cpp:443 sceMpegInit(): already initialized
maybe also have problem

**Comment by sum2012** [comment]
06:01:406 playThread   D[ME]: hle\scempeg.cpp:1690 sceMpegGetAtracAu(08a0dd44, 00000002, 08a0dc98, 09f93a40): warming up
06:01:406 readThread   D[ME]: hle\scempeg.cpp:1547 sceMpegRingbufferPut(08a0dd48, 32, 4800)
06:01:407 readThread   I[ME]: hle\scempeg.cpp:366 Stream offset: 2048, Stream size: 0xAF5000
06:01:407 readThread   I[ME]: hle\scempeg.cpp:367 First timestamp: 90000, Last timestamp: 7657560
06:01:411 readThread   D[ME]: hle\scempeg.cpp:1509 packetAdded: 32 packetsRead: 32 packetsTotal: 4800
06:01:411 playThread   D[ME]: hle\scempeg.cpp:1589 sceMpegGetAvcAu(08a0dd44, 00000001, 08a0dc80, 09f93a44): warming up

warming up should be once is my original  mind.
I will try to delete one

**Comment by sum2012** [comment]
No easy method to make both game happy.
Some games doesn't allow return two times ERROR_MPEG_NO_DATA
I try to use mpeg version to solve

**Comment by ANR2ME** [comment]
> 
> 
> No easy method to make both game happy.
> Some games doesn't allow return two times ERROR_MPEG_NO_DATA
> I try to use mpeg version to solve

May be some games didn't handle ERROR_MPEG_NO_DATA error code?

This is an example of `sceMpegGetAvcAu` i found on the internet:
```c
            retVal = sceMpegGetAvcAu(&D->m_Mpeg, D->m_MpegStreamAVC, D->m_MpegAuAVC, &unknown);   
            if((SceUInt32)retVal == 0x80618001)   // SCE_MPEG_ERROR_NOT_COMPLETED
            {   
                if(!IsRingbufferFull(D->Reader))   
                {   
                    sceKernelWaitSema(D->Reader->m_Semaphore, 1, 0);   
   
                    if(D->Reader->m_Status == READER_ABORT)   
                        break;   
                }   
            }   
            else if(retVal != 0)   
            {   
                sprintf(D->m_LastError, "sceMpegGetAvcAu() failed: 0x%08X", retVal);   
                break;   
            }   
            else   
            {   
                if(m_iVideoCurrentTimeStamp >= D->m_iLastTimeStamp - D->m_iVideoFrameDuration)   
                    break;   
   
                retVal = sceMpegAvcDecode(&D->m_Mpeg, D->m_MpegAuAVC, BUFFER_WIDTH, &D->Video->m_pVideoBuffer[D->Video->m_iPlayBuffer], &iVideoStatus);
                ...
            } 
```

**Comment by sum2012** [comment]
Do anyone one know "After Burner exhibit " firmware ?
It can been seen by JPCSP emulator
![1](https://user-images.githubusercontent.com/2177532/106292566-ee1e4400-6287-11eb-988c-4fc9e8656fa3.png)

**Comment by ANR2ME** [comment]
![image](https://user-images.githubusercontent.com/7974720/106293679-ddb69b00-6280-11eb-95a2-1ab3cbf62e61.png)

**Comment by sum2012** [comment]
I think that 100% safe for that code only run on firmware 3.0 or above

**Comment by sum2012** [comment]
Final Fantasy tactics Firmware 3.0.3 ,the game work without the change

**Comment by sum2012** [comment]
Thanks @arnoldsecret report,
I only avoid error on megaman power up which firmware 2.6
I didn't test other games which firmware below 3 (EA Replay,After Burner)

**Comment by arnoldsecret** [comment]
Game now works aside from time attack freezing, but I think it's unrelated.

**Comment by unknownbrackets** [comment]
I'm pretty sure firmware tests have shown this warm up delay across versions, but the error code or semantics of it may differ...

-[Unknown]
