### ISSUE TITLE
[Windows]Screen Black out when use some shaders.

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#14045]
### What happens?
If use the 3-kind of shaders then the screen black out. (Game is working)
The issue will happen by these shaders below.
- Spline36 Upscaler
- 5xBR
- 5xBR-lv2

Android is not became black out.
but, I don't know that shaders working or not.

### What *should* happen?
It Should work shaders correctly.

### Please test newest version in https://buildbot.orphis.net/ppsspp/

PPSSPP Ver.：1.10.3-1714
OS：Windows10（64-bit）Japanese
CPU：Ryzen7 3800X（8-core）
GPU：RADEON RADEON RX5700XT
Resolution：2560×1440
RAM：32GB

**Comment by ANR2ME** [comment]
Hmm.. i can't reproduce this with Geforce on OpenGL backend.
![image](https://user-images.githubusercontent.com/7974720/106427662-53498380-649a-11eb-9a52-295af2a9a67a.png)
![image](https://user-images.githubusercontent.com/7974720/106427724-6e1bf800-649a-11eb-8af0-80e7ad425f4c.png)

**Comment by nassau-tk** [comment]
What!
Yes,,,,Oh,,,, I can't reproduce now!

um... I close this.
I will more check once more.

**Comment by Panderner** [comment]
> Hmm.. i can't reproduce this with Geforce on OpenGL backend.
> ![image](https://user-images.githubusercontent.com/7974720/106427662-53498380-649a-11eb-9a52-295af2a9a67a.png)
> ![image](https://user-images.githubusercontent.com/7974720/106427724-6e1bf800-649a-11eb-8af0-80e7ad425f4c.png)

Wait @ANR2ME have you tried in all backends?

**Comment by ANR2ME** [comment]
OpenGL, D3D9, D3D11, Vulkan all visible, but i haven't try it on OpenGL ES (mobile) tho
