### ISSUE TITLE
x64Emmiter issue on Windows 32-bit build

### ISSUE THREAD

**Issue by ANR2ME** [hrydgard/ppsspp#14048]
### What happens?
A critical popup appearing when launching a game (ie. Metal Slug XX)
![image](https://user-images.githubusercontent.com/7974720/106474225-45662380-64d7-11eb-9d94-d7a7d4845f1e.png)
```
47:34:291 user_main    E[FILESYS]: filesystems\directoryfilesystem.cpp:62 DirectoryFileSystem::OpenFile: FAILED, 3 - access = 1
47:34:364 user_main    E[SYSTEM]: common\log.cpp:49 (c:\buildagent\work\abdf5c0a9353d117\common\x64emitter.cpp:Gen::OpArg::WriteRex:186) Critical: [(customOp & 8) == 0 || customOp == -1] *** Assertion ***
```

### What *should* happen?
Runs normally

### Please test newest version in https://buildbot.orphis.net/ppsspp/

PPSSPP Windows 32-bit build v1.10.3-1717-g30b6f1f86
OS: Win64 v20H2

**Comment by unknownbrackets** [comment]
Oops, sorry.  Fixed in c1fa4958d.

-[Unknown]
