### ISSUE TITLE
Last minute china tieba baidu  feed back before v1.11

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#14047]
以前0.99玩cps1、neogeo模拟器的时候还能看清游戏选择的字，现在是糊的
![1](https://user-images.githubusercontent.com/2177532/106460097-c4eef500-64cd-11eb-810d-3a8d7a11d6c5.jpg)

translate:
In v0.99 Play with cps1、neogeo emulator can see clear the game font,now is blurry.

(Choose important thing)

sd gundam g generation overworld opening now is obviously slow down  ,in v1.10.3 no problem
Dai-2-Ji Super Robot Taisen Z Saisei-hen title sound is poor,in v1.10.3 no problem
@hrydgard maybe let them fix in v1.11.1 ?

**Comment by hrydgard** [comment]
Need more details for most of these - for the neogeo emulator font blur, would be nice with screenshots before/after. And for the others, screenshots or video clips of what it was before and how it is now, for example - whatever we can get. Hard to say how important these are otherwise.

**Comment by sum2012** [comment]
Ok transale the first point
In Warriors Orochi 2 ,opening is wrong 
In v1.10.3 have in-game vision have problem

**Comment by sum2012** [comment]
It feed back the slow down issue is his' weak phone.
But use v1.10.3 no problem

**Comment by chinalhx** [comment]
> Need more details for most of these - for the neogeo emulator font blur, would be nice with screenshots before/after. And for the others, screenshots or video clips of what it was before and how it is now, for example - whatever we can get. Hard to say how important these are otherwise.

btw,i hope v1.11.0 can emulator PS1 games,cuz I'm using  iOS14  as free account ,only can install 2emulators
edit:altstore need take up one

**Comment by hrydgard** [comment]
1.11 will not be able to run PS1 games, sorry. It's still a PSP emulator, it doesn't have a PS1 emulation core and we cannot run the original PS1 emulator that was in the real PSP.

**Comment by chinalhx** [comment]
> 1.11 will not be able to run PS1 games, sorry. It's still a PSP emulator, it doesn't have a PS1 emulation core and we cannot run the original PS1 emulator that was in the real PSP.

fine,ok:( awww! I remember last use version is 0.9.But,now 1.11 incoming.i'm so happy to u:)

**Comment by sum2012** [comment]
Can we use PSP for PS plugin -Popsloader to play PS1 games ?

**Comment by sum2012** [comment]
No more feed back from tieba ,
I might research on neogeo emulator on future

**Comment by sum2012** [comment]
The mpeg video problem and slow down is (99.9%) due to MIUI 12 (Android 10) System CPU  Qualcomm 865.
I will open another issue for "the slow down problem" when reporter upload video,

**Comment by unknownbrackets** [comment]
Should this be closed now, (keeping #14090 open until it's fixed)?

-[Unknown]
