### ISSUE TITLE
OpenGL issue on Run CPU Tests

### ISSUE THREAD

**Issue by ANR2ME** [hrydgard/ppsspp#14052]
If i build PPSSPP my self i'm seeing this "Run CPU tests" in Developer Tools
![image](https://user-images.githubusercontent.com/7974720/106562178-83595b00-655c-11eb-957f-34432cdf9ce2.png)

But if i extract the latest dev build from https://buildbot.orphis.net/ppsspp/ on a new folder, the "Run CPU tests" is being grayed out.
![image](https://user-images.githubusercontent.com/7974720/106562922-97518c80-655d-11eb-97ab-6d5a5162e61b.png)

### What happens?
If i clicked "Run CPU tests" from my build, i'm getting this popup
![image](https://user-images.githubusercontent.com/7974720/106562458-e814b580-655c-11eb-9b13-71ba8d8e0e69.png)
```
44:47:997 idle0        E[SYSTEM]: Common\Log.cpp:49 (C:\Users\AdamN\Documents\Projects\ppsspp\Common\GPU\OpenGL\GLRenderManager.cpp:GLRenderManager::BindFramebufferAsRenderTarget:298) Critical: [insideFrame_] *** Assertion ***
```
Btw how do i enable "Run CPU tests" so it won't be grayed out?

### What *should* happen?
Not sure whether this is a bug or not since i don't know how to enable/disable "Run CPU tests"

### Please test newest version in https://buildbot.orphis.net/ppsspp/
PPSSPP Win64 v1.10.3-1720-gd73456e93

**Comment by sum2012** [comment]
Choice *cpuTests = new Choice(dev->T("Run CPU Tests"));
	list->Add(cpuTests)->OnClick.Handle(this, &DeveloperToolsScreen::OnRunCPUTests);

	cpuTests->SetEnabled(TestsAvailable());

bool TestsAvailable() {
#ifdef IOS
	std::string testDirectory = g_Config.flash0Directory + "../";
#else
	std::string testDirectory = g_Config.memStickDirectory;
#endif
	// Hack to easily run the tests on Windows from the submodule
	if (File::IsDirectory("../pspautotests")) {
		testDirectory = "../";
	}
	return File::Exists(testDirectory + "pspautotests/tests/");
}

Seem need clone pspautotests

**Comment by ANR2ME** [comment]
So the test only comes with repo?

**Comment by hrydgard** [comment]
yeah there's no use for this button if you haven't got the pspautotests because it uses them.

Should probably hide it or disable it if the directory is not there, but we should also make it not crash.
