### ISSUE TITLE
K-On! Houkago Live! main menu music stops playing after first loop

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#14058]
Here's a video for this issue:

https://streamable.com/16tbcy

**Comment by Panderner** [comment]
Here's a log when this message spams when the main menu music stops playing:
```
CRI ADX Audi E[ME]: HLE/sceAtrac.cpp:571 avcodec_decode_audio4: Error decoding audio -1094995529 / bebbb1b7
```

**Comment by ANR2ME** [comment]
Error `-1094995529` = `AVERROR_INVALIDDATA` https://stackoverflow.com/questions/22944133/how-can-i-find-out-what-this-ffmpeg-error-code-means

**Comment by sum2012** [comment]
Maybe fix by #13793
But It is wrong

**Comment by sum2012** [comment]
Firmware 6.31
 v1.10.3-1731-g5babc1af2 log: https://gist.githubusercontent.com/sum2012/7fe15c28500fe3e3d7c5382dae9a5941/raw/a18440e76c210f7ec102741af756c13d37936ca5/gistfile1.txt

**Comment by benderscruffy** [comment]
v1.13.2-2323-ge3105955e
still a problem but it usually cuts out after the 3rd or 4th loop
just tested it on my psp and it keeps on looping continually

**Comment by sum2012** [comment]
Update the log to v1.16.6-280-g6d063ce3e-windows-amd64
https://gist.github.com/sum2012/deb2073cf56d5864ded551b4217fbf84

JPCSPTrace log: https://gist.githubusercontent.com/sum2012/deb2073cf56d5864ded551b4217fbf84/raw/f00f1cfd2918e44bcaffff2391a12673b92201a0/gistfile1.txt

**Comment by sum2012** [comment]
Just a note, this hack still not work in 4 loop
if (atrac->bufferState_ == ATRAC_STATUS_STREAMED_LOOP_FROM_END && atrac->currentSample_ > 0.9 * atrac->endSample_) {
				atrac->ForceSeekToSample(0);
}

**Comment by sum2012** [comment]
This work but need  clean up
https://github.com/hrydgard/ppsspp/commit/9293744e3f71538e887472c84cf09814b2ad4cd4
