### ISSUE TITLE
Launching games directly from the Homebrew Store doesn't work

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#14054]
Something has broken, it says "just a directory".

If you exit the store back to the homebrew menu, though, it works just fine. Very odd.

**Comment by unknownbrackets** [comment]
Is this Android 11 only?

It seems to work on Android 10.  At least, I launched an already installed game fine, then uninstalled it and reinstalled it, and launched it again fine without leaving and returning after the install.

-[Unknown]

**Comment by hrydgard** [comment]
Yes, it might be, this was on an Android 11 device. 

Will look into it more soon.

**Comment by hrydgard** [comment]
Hm, seems I had some weird failure installing some games, the EBOOT and more files were missing in the games that failed to launch. No idea what caused that though...

I could reproduce a weird issue where I was able to launch the game before it had finished installing, or at least before the files where visible just after installing. Some wacky stuff going on in the background... Maybe storage is already "emulated" through some java hell, even in the old-storage-compatibility mode of Android 11.
