### ISSUE TITLE
GTA Liberty City Stories: Weird sound bug

### ISSUE THREAD

**Issue by Back2Life888** [hrydgard/ppsspp#14057]
### What happens?

There will be weird sounds happening.. Occurs everytime for me..

### What *should* happen?

The weird sounds will not happen..

### What hardware, operating system, and PPSSPP version?  On desktop and mobile phone, GPU matters for graphical issues.
PPSSPP 1.10.2
NViDiA GTX 1650
Intel i7-6700

**Comment by Back2Life888** [comment]
i cant give further details.. The sound bug is very odd..

**Comment by Panderner** [comment]
@Back2Life888 can you record the video?

**Comment by Back2Life888** [comment]
nevermind, seems to be its fixed on the latest BuildBot PPSSPP..

**Comment by DavidTamas** [comment]
Is this the same as  #12377 ?
Which build is it fixed in, exactly?
