### ISSUE TITLE
Request for PPSSPP 1.10.4 stable release

### ISSUE THREAD

**Issue by TheRealDannyyy** [hrydgard/ppsspp#14068]
The dev builds seem to have a lot of important ad hoc fixes and I would very much appreciate, if they could be merged into a **PPSSPP v1.10.4 stable (+gold)** build soon.

(Not sure if this is the right place to request builds. I'm used to doing it with issues in other software repositories.)

_Cheers!_

**Comment by unknownbrackets** [comment]
This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  Releases are made when they're made.  We do plan to have a release soon, which would likely be v1.11.0, but there's no reason to open an issue about it.

Also, the latest git builds are essentially the same as what will be the next release.  You might just want to use a git build.

-[Unknown]
