### ISSUE TITLE
[Future Request] Easy search & copy Save data system.

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#14075]
### What happens?
Maybe, I think that many user playing on PC & portable device both.
But, If play on PC and saved data then the user must move & copy the save data to portable device.
When the user want do that it must search the save data manualy by "Game ID".

It should be access more easy.
For example.
Add, "Search Savedata position" button in game info page.
(Right click and open the page of the game in Recent or Games.)
![image](https://user-images.githubusercontent.com/48179091/107152041-25d46c80-69a9-11eb-9a79-e0ffae612c12.png)

And, Open Explorer window at the folder position.
Like below. (Must need the folder was selected & highlight.)
![image](https://user-images.githubusercontent.com/48179091/107152127-7c41ab00-69a9-11eb-8615-392240cc7ac9.png)

If it can do that from portable device too then it's great.
But, I don't have knowledge.
So, I can't think that.

**Comment by unknownbrackets** [comment]
I think this might essentially be #1019.

Since games can have multiple save directories, it's going to be confusing to link to them in the file manager of their OS.  Android is making this harder anyway.

-[Unknown]

**Comment by ANR2ME** [comment]
True, it 's probably better/easier for common users to use cloud to sync their data, and may be syncing cross-platform settings too (ie. Some savedata might be locked to a certain MAC address and won't work on a different MAC address)

On cloud, we can even create a separate saves for each platform (PC, Android, iOS, Linux, etc.) and let user choose which savedata they wanted to download from upon syncing if there are multiple platforms saved on cloud.

**Comment by nassau-tk** [comment]
Yes. That's perfect style.
And, I learn that on #1019 many user will want save data link system.

Thank you @unknownbrackets  & @ANR2ME .

We should disscuss at #1019 .

This request close.:grin:
