### ISSUE TITLE
Keyboard still not appearing - 1.11

### ISSUE THREAD

**Issue by EX-e-LD** [hrydgard/ppsspp#14097]
### What happens?
Keyboard still won't appear after "fix" from previous issue,certain points like Ports for Ad-Hoc / Remote Disc Streaming / Controls sensitivity

### What *should* happen?
They should appear

### What hardware, operating system, and PPSSPP version?  On desktop and mobile phone, GPU matters for graphical issues.
Honor 9S
OpenGL
Keyboard - GBoard

**Comment by hrydgard** [comment]
Duplicate of #13716
