### ISSUE TITLE
Musou Orochi: Maou Sairin Enhanced Version video

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#14090]
(Only reporter phone have problem
v1.10.3 no problem ,a problem from #14047  )

https://youtu.be/yGaOnJVnTdA

**Comment by sum2012** [comment]
Reporter system: MIUI 12 (Android 10) System  CPU: Qualcomm 865

![1](https://user-images.githubusercontent.com/2177532/107382123-80e19d00-6b2a-11eb-9049-9610088853bf.jpg)
![2](https://user-images.githubusercontent.com/2177532/107382134-850dba80-6b2a-11eb-80c7-d3756269e376.jpg)
![3](https://user-images.githubusercontent.com/2177532/107382144-87701480-6b2a-11eb-82ef-c503681dbf0b.jpg)
![4](https://user-images.githubusercontent.com/2177532/107382153-89d26e80-6b2a-11eb-86d6-2999e3e5b05b.jpg)

**Comment by unknownbrackets** [comment]
I think the issues in the video with the vertical strips are known and caused by either the vertex cache, lazy texture caching, or retain changed textures.  Turn off those speed hacks for proper graphics.

-[Unknown]

**Comment by sum2012** [comment]
Thanks,that is retain changed textures.
Let's solve it programly

**Comment by sum2012** [comment]
Sorry, is lazy texture caching setting

**Comment by hrydgard** [comment]
As was mentioned in https://github.com/hrydgard/ppsspp/pull/14099 , the game copies a part of the video to a texture address using the CPU, draws using that, waits for the GPU to finish, then copies another part of the video frame to the very same address, draws using that, etc. Does not work with the lazy texture cache as it works now, so the workaround is to turn off that option.

The texture cache is due for a rewrite so a proper fix is pending that...

**Comment by benderscruffy** [comment]
is this still a problem ??

**Comment by sum2012** [comment]
v1.13.1-583-g1653dcdc1 enable lazy texture caching no problem
Closing
