### ISSUE TITLE
Sound cracking when UI sound enabled + game background - 1.11

### ISSUE THREAD

**Issue by EX-e-LD** [hrydgard/ppsspp#14096]
Sorry for wrong wording of english in advance!!
### What happens?
When you go to game menu with UI sound enabled,music is cracking

### What *should* happen?
Sound should not crack under any circumstances

### What hardware, operating system, and PPSSPP version?  On desktop and mobile phone, GPU matters for graphical issues.
Honor 9S
OpenGL
- PowerVR GE8320
- Mediatek MT6762 Helio P22
-  Android 8.1.0 - MIUI 10
-  PPSSPP 1.11

**Comment by Panderner** [comment]
Last build worked?

**Comment by EX-e-LD** [comment]
> Last build worked?

Same,literally

**Comment by hrydgard** [comment]
Hm, doesn't seem to happen to me..

**Comment by Panderner** [comment]
Umm yes here's a crackling video.

https://user-images.githubusercontent.com/37503397/107402886-7087ed00-6b3f-11eb-9272-9ba1e128bb30.mp4

**Comment by hrydgard** [comment]
Okay, clearly happening to you then :)  I'll try on some devices. So this does not crackle if UI sound is off?

**Comment by Panderner** [comment]
> Okay, clearly happening to you then :) I'll try on some devices. So this does not crackle if UI sound is off?

Even UI sound is turned off it does not help.

**Comment by hrydgard** [comment]
Okay, he said "When you go to game menu with UI sound enabled,music is cracking"

**Comment by Panderner** [comment]
See? I turned off UI sound
![IMG_20210210_013804](https://user-images.githubusercontent.com/37503397/107403962-b1343600-6b40-11eb-9aa8-b9e3a476e066.jpg)

**Comment by hrydgard** [comment]
I believe you, I'm just confused by the original poster since it's hard to imaging why the UI sound setting should matter.

**Comment by EX-e-LD** [comment]
> I believe you, I'm just confused by the original poster since it's hard to imaging why the UI sound setting should matter.

Oh,i'm sorry,saw changelog and thought this would impact it.Guess i was wrong.Sorry again

**Comment by sum2012** [comment]
My chinese friend also suffer this issue

**Comment by hrydgard** [comment]
My old Galaxy S3 also has the same issue, indeed. Hm.

**Comment by hrydgard** [comment]
I got it.
