### ISSUE TITLE
[Request] Remove mentions of Ubuntu PPA from downloads section of official site

### ISSUE THREAD

**Issue by Leopard1907** [hrydgard/ppsspp#14104]
https://www.ppsspp.org/downloads.html

### What happens?

Mentioned page advertises two PPA's that are not maintained ( last update was 119 weeks ago)

### What *should* happen?

Removing them while keeping Flatpak link intact because it is still live and probably much better than what Debian/Ubuntu repos offers.

**Comment by hrydgard** [comment]
Done
