### ISSUE TITLE
FlatOut saving issue

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#14102]
Reported on Discord by te_lanus.

Seems similar to previous issues like #13316  - we should probably just add Flatout to the list for workarounds?

![image](https://user-images.githubusercontent.com/130929/107490233-e749d800-6b89-11eb-8c56-9986ef0dba35.png)

**Comment by Panderner** [comment]
Umm Saving works fine for me I'm using POCO M3

**Comment by hrydgard** [comment]
The user reported having 41gb free, might only break at really large amounts or specific amounts.

**Comment by Panderner** [comment]
I have 10 GB of free space and saving works fine.

**Comment by Panderner** [comment]
@hrydgard I have 42+ GB of free storage and it's still working fine.

**Comment by hrydgard** [comment]
Okay, maybe something about a very full save directory... Weird. Or just a broken ISO. I'm gonna untag this for 1.11.1.

**Comment by hrydgard** [comment]
More notes from conversation:

> if I clean out my save dir flatout saves, but with all the other saves it won't save

> size of the savedir is 460mb and no haven't touched that setting (MemStickSizeGB)

**Comment by telanus** [comment]
OK. Was able to kill the bug that I had with flatout. And it seems that there was a save that I linked from an old install. and that link was no longer pointing to anything as I removed the old install. Not sure why only Flatout wouldn't save as every other game saved perfectly that I tried. So not sure if it's a bug (that's linux only) but think you can close the bug report on github

**Comment by hrydgard** [comment]
OK!
