### ISSUE TITLE
Debugger memory dumps are always corrupted for specific instructions

### ISSUE THREAD

**Issue by Scusaa** [hrydgard/ppsspp#14111]
Memory dumps created with the debugger are corrupted.
An instruction after a delay slot under a jump or branch instruction *randomly* gets corrupted.

Here's an example with a dump taken with the debugger:
```
#1  OK    03e00008  jr ra
#2  OK    27bd0030  addiu sp, sp, $0030
#3  WTF   6804df0a  ldl a0, $df0a(zero)
```
Same code with a dump taken with an actual PSP using a cheatdevice:
```
#1  OK    03e00008  jr ra
#2  OK    27bd0030  addiu sp, sp, $0030
#3  OK    27bdfff0  addiu sp, sp, $fff0
```

More examples can be found in [this screenshot](https://imgur.com/a/R6tuOtd).

This issue has existed for as long as I can remember.
Observations:
* Happens to every game I tested
* Happens for each Debug/release x32/x64 PPSSPP build
* Tested only under Win7 x64 with different PPSSPP versions
* Tested with both cheats disabled, and enabled (same result)
* Graphics backend is Vulkan

I've looked at file `Windows/Debugger/DumpMemoryWindows.cpp`, more precisely at this line:
`fwrite(Memory::GetPointer(bp->start), 1, bp->size, output);`
It doesn't seem to be the cause.

That's annoying...

**Comment by unknownbrackets** [comment]
Hm, possibly something isn't accounting for jit memhacks when dumping.

-[Unknown]

**Comment by Scusaa** [comment]
> Hm, possibly something isn't accounting for jit memhacks when dumping.
> 
> -[Unknown]

The issue happens with JIT and IR Interpreter.
However, it disappears with Interpreter. That's interesting

**Comment by unknownbrackets** [comment]
Right, that's not surprising due to how jit and IR work.

When a basic block is compiled, it replaces the first instruction of the basic block with an invalid MIPS instruction to indicate which jit code to run.  We may change this to not actually alter PSP memory, although few games notice (see #3365 for one, though.)  It's convenient because it catches self-modifying code.

Interpreter doesn't compile basic blocks, so it doesn't do this.  It still uses replacements, which are a similar concept, though.

Decided to just add a checkbox to choose what you want for now.

-[Unknown]

**Comment by Scusaa** [comment]
I didn't know about this emu hack. That makes sense now, thank you.

I'm working on an anticheat which regularly computes hashes of the game's text section.
Considering this emu hack is active, are the expected hashes expected to fail? Similarily to issue #3365
If so, is there any workaround?

**Comment by unknownbrackets** [comment]
Well, I think that's effectively what's happening in #3365 too, yes.

We may change the way it works to have a separate buffer for the jit block codes, and simply check the first op matches to catch self modifying code.  It'd involve another memory read per block but it wouldn't necessarily be much slower, not sure.

But for the time being, are you running this within PSP code or as some modification to PPSSPP?  You can use `Memory::Read_Instruction()` or the clear & restore to check from PPSSPP.  From PSP code, you could maybe invalidate the icache, although it'd have a perf hit.  Anyway, all someone would need to do is a cheat to disable your check and it'd be disabled...

-[Unknown]

**Comment by Scusaa** [comment]
It's running as a kernel plugin, which on a side note detects when it's run with an emu or an actual PSP. The game code is also patched. The anticheat is network-based. Basically, all peers send their own game computed hash to each other. Everyone checks everyone's hash. Any invalid hash or non-received hash after a timeout will result in the peer to be ejected from the game.

**Comment by Scusaa** [comment]
It's running as a kernel plugin, which on a side note detects when it's run with an emu or an actual PSP. The game code is also patched. Basically, the anticheat is network-based. There are several strategies, and challenges to prevent malicious from reverseing, disabling or spoofing the patch mechanism.
