### ISSUE TITLE
GPU driver test fail in Black shark 3 (Adreno 650)

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#14110]
Seem better result by my older phone asus zenfone 3

Opengl
![Screenshot_2021-02-11-09-25-00-476_org ppsspp ppsspp](https://user-images.githubusercontent.com/2177532/107594433-e2019180-6c4c-11eb-9d8b-e5ec83181ba5.jpg)
![Screenshot_2021-02-11-09-25-09-755_org ppsspp ppsspp](https://user-images.githubusercontent.com/2177532/107594446-e62daf00-6c4c-11eb-8501-a14d9c5fe109.jpg)
![Screenshot_2021-02-11-09-25-17-661_org ppsspp ppsspp](https://user-images.githubusercontent.com/2177532/107594448-e6c64580-6c4c-11eb-8bce-c60a60fccc78.jpg)
![Screenshot_2021-02-11-09-25-25-743_org ppsspp ppsspp](https://user-images.githubusercontent.com/2177532/107594451-e7f77280-6c4c-11eb-9a13-d1f9bfd933fa.jpg)
![Screenshot_2021-02-11-09-26-09-895_org ppsspp ppsspp](https://user-images.githubusercontent.com/2177532/107594453-e9289f80-6c4c-11eb-9125-45417e94e952.jpg)
![Screenshot_2021-02-11-09-26-18-215_org ppsspp ppsspp](https://user-images.githubusercontent.com/2177532/107594454-e9c13600-6c4c-11eb-9815-6f2534c2da85.jpg)

Vulkan
![Screenshot_2021-02-11-09-32-19-704_org ppsspp ppsspp](https://user-images.githubusercontent.com/2177532/107594471-f2197100-6c4c-11eb-9306-51501298a30b.jpg)
![Screenshot_2021-02-11-09-32-27-542_org ppsspp ppsspp](https://user-images.githubusercontent.com/2177532/107594482-f5acf800-6c4c-11eb-9217-f8a5436869d5.jpg)
![Screenshot_2021-02-11-09-32-37-722_org ppsspp ppsspp](https://user-images.githubusercontent.com/2177532/107594483-f6de2500-6c4c-11eb-828b-cbf31963d27a.jpg)
![Screenshot_2021-02-11-09-32-41-954_org ppsspp ppsspp](https://user-images.githubusercontent.com/2177532/107594485-f6de2500-6c4c-11eb-9f9f-31f3317b35b0.jpg)

**Comment by zminhquanz** [comment]
Same on Adreno 540 of my GG Pixel 2 , Android 11 ( GPU Driver version v490 )

**Comment by hrydgard** [comment]
Let's keep these to one thread: #14110. Also, the GPU test shows a bug in the driver, which we are demonstrating. It's not a bug in PPSSPP.
