### ISSUE TITLE
Will it work in macOS High Sierra

### ISSUE THREAD

**Issue by ramabhishek** [hrydgard/ppsspp#14114]

**Comment by unknownbrackets** [comment]
This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).

There's no reason PPSSPP wouldn't work on High Sierra.  That said, I believe Apple has stopped releasing security updates for macOS 10.13, so it may fall out of support.  It's possible you may have trouble installing or compiling dependencies.  But this is all better for the forum.

-[Unknown]
