### ISSUE TITLE
God of War: Ghost Of Sparta black screen when jump the hole

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#14119]
I don't know how to play from beginning to error place.
Don't affect Simulate UMD delay.
save status: https://drive.google.com/file/d/10bJYLFHcNSAbWgN_DKdavXHxkAuZM1tw/view?usp=sharing
 v1.11-25-g2cfcd34c4-windows-amd64 debug log: https://drive.google.com/file/d/1jFS5YOCHI7ec2XH-FGL9AHA2b2wIejp6/view?usp=sharing 
03:47:659 user_main    W[FILESYS]: filesystems\isofilesystem.cpp:324 Unable to open raw sector, out of range: '/sce_lbn0xc1ba0_size0x1cf5800', sector 000c1ba0, max 000c1ad6
force sectorStart = 0 ,it would error in scempeg

**Comment by unknownbrackets** [comment]
Are you sure this isn't just a bad ISO?  The numbers you've quoted indicate the ISO is about 1.513 GB.  That's the size of the Russia / Poland release, which probably isn't the one you're using.

-[Unknown]

**Comment by sum2012** [comment]
My iso is 1,624,682,496 byte.
This iso is from my friend.
I will tell him dump again.

**Comment by sum2012** [comment]
http://redump.org/discs/system/psp/ don't have data for asia version NPHG00092

**Comment by unknownbrackets** [comment]
Another site says that should be 1.59 GB, which is approximately 1,707,249,500.  Even if it's not 1024 and is 1000, it would be approximately 1,590,000,000.  So it does seem like the size is wrong.

-[Unknown]

**Comment by sum2012** [comment]
I get another people of same game id on size on 1,709,441,024 byte
I have given original reporter to test again.
I think that the save status is also wrong ?
I have told the  original reporter to start from beginning

**Comment by Gamemulatorer** [comment]
Using the savestates above yes the game is black screen and crash.

https://user-images.githubusercontent.com/37603562/134569388-9b4f4f46-4075-45e7-bd58-6bf8fce734f5.mp4

Maybe he's using a cheat that cause this issue the savestate has 999999 points? 🤔...
![Screenshot_2021-09-24-03-10-08-531_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/134569518-b6076534-73a3-4949-9787-085912fa2006.jpg)

**Comment by ResurrectionRedmi9** [comment]
@sum2012 no feedback/outdated?

**Comment by Gamemulatorer** [comment]
How about this now.

**Comment by Gamemulatorer** [comment]
@sum2012 no feedback/outdated.

**Comment by sum2012** [comment]
@Gamemulatorer I have lost the original reporter contact
It is  okay to close the issue ?
