### ISSUE TITLE
Danganronpa 1 & 2 run slower in 11.1 

### ISSUE THREAD

**Issue by Lemoncak3** [hrydgard/ppsspp#14122]
I have this oppo phone with ram 3 gb but with low graphic chipset and when running danganronpa 1 & 2 in 11.1, it runs slow and i tried the official build 10.3. It has better perfomance than 11.1 (there is almost no warning of game running slower while in 11.1 that message pop up almost all the time). So i just wonder what's changed that make the performance of danganronpa slower in 11.1?

**Comment by hrydgard** [comment]
Do you actually feel slowness, or maybe the warning has become too sensitive somehow?

**Comment by Lemoncak3** [comment]
It's slower because in 11.1 the cursor runs slow and audio was rigged. But when 10.3 the audio plays fine and the cursor isn't slow.

**Comment by hrydgard** [comment]
Alright, that sounds like a real problem. Any difference between GL and Vulkan?

**Comment by Lemoncak3** [comment]
Well i can only test open GL since there is no vulkan in my other HP which i use to play danganronpa. Since my main HP already used for other apps. Must i try it with my main then? But usually in my main almost every game runs smoothly though.

**Comment by hrydgard** [comment]
Nah, I was just wondering about the device where it has slowed down.

**Comment by Panderner** [comment]
@Lemoncak3 what device are you using?

**Comment by unknownbrackets** [comment]
It would help a lot to narrow this down to the first version that was slow, and the last version that was fast.

You can do this by halves.  If you go here:
https://buildbot.orphis.net/ppsspp/index.php?m=fulllist

You'll see v1.10.3-1755-ged8188e82, which is basically the same version as v1.11.0.  This one is probably still slow, and it must've changed somewhere in those 1,755 commits.  Seems like a lot, right?  But there's a trick.

If you try v1.10.3-898-gcccdfe414 or so and it's slow, that means you've just knocked out half of those changes - the problem was introduced in those first 898 changes.  If it's fast then, we know none of those 898 changes could be it.

Even if I carefully looked through each of 800 changes one by one, I might still never guess at the right one.  I could spend weeks or months dissecting the code and never get anywhere.

After that, you could go half way again and cut out another 450 or so changes.  With even just 6 tries like this, you could narrow it down fairly well.  It'd take at most 11 tries to narrow it down completely.

It might still be complex to fix even if we knew exactly which change introduced it, but a lot of the time that makes it much, much easier to fix.

-[Unknown]

**Comment by Lemoncak3** [comment]
Now i tried it in my max pro m2 which almost run every game at full speed in 3x resolution but only get 20 - 40 fps ingame, it runs full speed only in conversation.
![Screenshot_20210304-120253](https://user-images.githubusercontent.com/67026697/109914039-b15bc780-7ce1-11eb-8bce-42761957bf87.png)
When i run it at 1x resolution i only get around 50 fps and in some area it can get down to 33 fps 
![Screenshot_20210304-115843](https://user-images.githubusercontent.com/67026697/109914094-ce909600-7ce1-11eb-995f-26410ad058c4.png)
![Screenshot_20210304-120001](https://user-images.githubusercontent.com/67026697/109914097-d2241d00-7ce1-11eb-87e0-d8e3cf94c814.png)
At first i thought it running really slow in my other phone because it's older but it seems to have same issues too in my max pro m2.

**Comment by unknownbrackets** [comment]
The game performs readback to make investigation work, which can be slow.  But if this got slower compared to an older version, trying a few version in between to confirm when would help a lot.

-[Unknown]

**Comment by kage2051** [comment]
I think it has to do with #14156, but with the option item still visible since it is a stable build. Some games may experience slowdowns without that speed 'boost' on OGL.

**Comment by Lemoncak3** [comment]
Update to 312 and it has a improvement to performance in 1x resolution in my max pro m2, but in my other device it still very very lag only 17 fps. But in 3x resolution it still lag. It didn't happen in my other game in pro m2, does it has somekind of bug or something?

**Comment by unknownbrackets** [comment]
I believe you.

The game does things when it renders that are bad.  Modern game developers would laugh at this game.  PSP games in general often do things that modern game developers would think are really dumb.  But, they were written over 10 years ago.

In this case, we know both Danganronpa games (both 1 and 2) do something that was fast on PSPs, but isn't really as fast on modern devices - especially phones.  Phones really don't like the way it renders.

We know this and we believe you.  It's not necessary to convince us.  Even if you keep trying, it won't change anything.  We already believe you.

What we're asking for, and you are still not helping with, is when it got worse.  We didn't do anything knowingly to make it worse.  Like I described, you can try a few versions and narrow down what changed.  I don't have this particular game, so I can't.

We made over 1000 changes between the versions you're talking about.  I have no idea which one could've made this slower.  If you could narrow it down to 100, I could probably guess, but 1000 is just too many.

-[Unknown]

**Comment by Lemoncak3** [comment]
Sorry if i made you misunderstand, just wanna saying that something you do until version 312 has improve the game even it's still not in fullest performance. Will try another version when i have the time. It already in 53 to 58 fps in 1x resolution which a lot better than before that only run between 33 to 50 fps. Thanks again will inform if i already tried which version before that works best and when it getting worse and narrow it down as best as i can

**Comment by Lemoncak3** [comment]
Sorry i think i made a grave error in this. I tried it in both my current ohone and my old phone and become confused by it. I tried all official version and realize that in 3x resolution in my pro m2 danganronpa 2 always run around 37 to 50 fps in some area while in other area it can runs above 50 fps. So it's not always in full speed, maybe because what unknown said about how danganronpa 2 being developed that isn't like other psp game. But in my old phone it does run very slow in 11.1 and will download few version from github and tried it down to narrow it.

**Comment by Gamemulatorer** [comment]
Danganronpa 1 is super smooth on my Redmi Note 9 at 5X rendering resolution idk about danganronpa 2 I will test it later.
![Screenshot_2021-05-03-17-41-08-988_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/116862166-e8dde600-ac36-11eb-8df9-aedc1ca7a06a.jpg)

**Comment by hrydgard** [comment]
Well, I don't think it's likely that we're gonna investigate this more - game runs fine on most modern phones after all. So I'm gonna close.

**Comment by Gamemulatorer** [comment]
Danganronpa 2 related issue is here https://github.com/hrydgard/ppsspp/issues/13321#issuecomment-740587181
