### ISSUE TITLE
Just add pictures for wiki

### ISSUE THREAD

**Issue by leoxxx** [hrydgard/ppsspp#14121]
https://github.com/hrydgard/ppsspp/wiki/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8PPSSPP%E5%A4%9A%E4%BA%BA%E8%81%94%E6%9C%BA%E6%B8%B8%E6%88%8F
<details>
<summary>Screenshots</summary>

![QQ截图20210212181723](https://user-images.githubusercontent.com/5364709/107762262-b45d3b00-6d67-11eb-961c-e95f5872f969.png)  
![QQ截图20210212195021](https://user-images.githubusercontent.com/5364709/107766299-351f3580-6d6e-11eb-91e5-ff8946b103f1.png)  
![QQ截图20210212200437](https://user-images.githubusercontent.com/5364709/107766328-45371500-6d6e-11eb-972d-d426434ddac0.png)
![QQ截图20210212213937](https://user-images.githubusercontent.com/5364709/107775195-f348bc00-6d7a-11eb-9122-5bd6d89eb577.png)  
![QQ截图20210212214543](https://user-images.githubusercontent.com/5364709/107775802-c0eb8e80-6d7b-11eb-97b6-1b2de2f123c5.png)
</details>

**Comment by ANR2ME** [comment]
We should use screenshot with a more common language isn't? like English for example

**Comment by leoxxx** [comment]
https://github.com/hrydgard/ppsspp/wiki/How-to-play-multiplayer-games-with-PPSSPP
MojoJojoDojo do it.

**Comment by leoxxx** [comment]
@ANR2ME 
Then, please tell me  the code for expand.

**Comment by ANR2ME** [comment]
> 
> 
> @ANR2ME
> Then, please tell me the code for expand.

This https://gist.github.com/jbsulli/03df3cdce94ee97937ebda0ffef28287

**Comment by leoxxx** [comment]
I try the code, but can't display the pictures.
Can you show the https://github.com/hrydgard/ppsspp/issues/14121#issuecomment-778152548 code for me?

**Comment by ANR2ME** [comment]
> 
> 
> I try the code, but can't display the pictures.
> Can you show the [#14121 (comment)](https://github.com/hrydgard/ppsspp/issues/14121#issuecomment-778152548) code for me?

i added the code at bottom

**Comment by leoxxx** [comment]
I see.

**Comment by unknownbrackets** [comment]
Going to close this - you should be able to add additional images here as needed, just keeping the issue list clean.

-[Unknown]
