### ISSUE TITLE
pursuit force extreme justice glitching road

### ISSUE THREAD

**Issue by crazyrexz** [hrydgard/ppsspp#14120]
first thanks for make this games playable, last time i check on my redmi note 4 this game is lag, vulkan and open gl is same, now this games is running smooth, fast forward touching 300-400/500, cool

### What happens?
as title, roads is glitching , makes vehicle looks drowned , on next level on boat is fine

### What *should* happen?
car is visible

### Please test newest version in https://buildbot.orphis.net/ppsspp/

snapdragon, on nightly build ppsspp-v1.11-20-g7095115d4-android
thanks

**Comment by Panderner** [comment]
You need to set the Spline/Bezier curves quality to high to fix road glitches.

**Comment by crazyrexz** [comment]
thanks , did it impact on performance and battery usage?

**Comment by crazyrexz** [comment]
yes it fixed, but took performance hit even on medium, on some locations frame dropping... i stick to low again
