### ISSUE TITLE
Some Chinese translation issue

### ISSUE THREAD

**Issue by leoxxx** [hrydgard/ppsspp#14125]
> AdhocServer Failed to Bind Port = Ad hoc 服务器绑定端口失败
Failed to Bind Localhost IP = 绑定本地主机IP失败
Failed to Bind Port = 绑定端口失败
Failed to connect to Adhoc Server = 无法连接服务器
Failed to load state = 无法载入即时存档
Failed to save state = 无法保存即时存档
Failed to load state. Error in the file system. = 无法载入即时存档。文件系统出错。
Failed to save state. Error in the file system. = 无法保存即时存档。文件系统出错。
Failed to identify file = 无法识别文件。
Failed to load executable: = 无法加载可执行文件：

I think  all "failed to" should be translated  into Chinese "无法".

So
AdhocServer Failed to Bind Port = 无法绑定Adhoc服务器端口
Failed to Bind Localhost IP = 无法绑定本地主机IP
Failed to Bind Port = 无法绑定端口

Failed to connect to Adhoc Server = 无法连接Adhoc服务器
Disconnected from AdhocServer = 与Adhoc服务器断开连接

**Comment by hrydgard** [comment]
Please submit a pull request to https://github.com/hrydgard/ppsspp-lang with your change.s

**Comment by sum2012** [comment]
Let me do it.
No one keep do chinese translation so that I do myself.
My chinese translation is not good.
90% from https://translate.google.com

**Comment by sum2012** [comment]
@leoxxx 
I have merged your change.

**Comment by leoxxx** [comment]
@hrydgard 
Sorry, I can't submit pull request.
@sum2012 
Thanks.
