### ISSUE TITLE
GachiTora! Abarenbou Kyoushi in High School

### ISSUE THREAD

**Issue by IrfanH495** [hrydgard/ppsspp#14136]
### What happens?
without simulate block transfer effects
![Screenshot_20210214-085922](https://user-images.githubusercontent.com/78854859/107866423-5897cc80-6ea3-11eb-8096-db9a247fd2f0.png)

simulate block transfer effects on
![Screenshot_20210214-085942](https://user-images.githubusercontent.com/78854859/107866505-4bc7a880-6ea4-11eb-8563-e2b2f59340f6.png)
Game running slowly
### What *should* happen?
can it be fixed like a game naruto sippudent ninja inpact 

### What hardware, operating system, and PPSSPP version?  On desktop and mobile phone, GPU matters for graphical issues.
Sharp SH-04H
Adreno 530
Snapdragon 820

**Comment by Panderner** [comment]
I'll add this game to RequireBlockTransfer because shadows won't work properly if you turn off simulate block transfer effects.
![Screenshot_2021-02-14-15-09-54-742_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/107871200-7a607600-6eda-11eb-9d16-62c14e22210a.jpg)

**Comment by hrydgard** [comment]
There's nothing to fix here since removing block transfers is just a hack and you can't expect everything to work. However with #14137 PPSSPP will at least warn about it.

**Comment by IrfanH495** [comment]
thanks for your reply.  games will be better when I add compat.ini
[BlockTransferAllowCreateFB]
NPJH50409 = true # GachiTora! .
Shadows only broken when pressing unthrottle.  if released will return to normal.  even without simulate Block Transfer effects Off.  I follow https://github.com/hrydgard/ppsspp/issues/11669
![Screenshot_20210214-202308](https://user-images.githubusercontent.com/78854859/107878044-b3144580-6f02-11eb-8966-e861e474ed0c.png)
![Screenshot_20210214-202312](https://user-images.githubusercontent.com/78854859/107878082-ebb41f00-6f02-11eb-9931-adfe4976e424.png)
Terimakasih banyak

**Comment by IrfanH495** [comment]
@Panderner sorry if I can ask about shadow problem now it's better but there is another problem.
Vukan 
![Screenshot_20210214-205927](https://user-images.githubusercontent.com/78854859/107878891-34220b80-6f08-11eb-9088-e920adac65fd.png)
OpenGL
![Screenshot_20210214-205958](https://user-images.githubusercontent.com/78854859/107878916-5582f780-6f08-11eb-828a-a954bad5e299.png)
is it a bug or backend issue.

**Comment by Panderner** [comment]
> @Panderner sorry if I can ask about shadow problem now it's better but there is another problem.
> Vukan
> ![Screenshot_20210214-205927](https://user-images.githubusercontent.com/78854859/107878891-34220b80-6f08-11eb-9088-e920adac65fd.png)
> OpenGL
> ![Screenshot_20210214-205958](https://user-images.githubusercontent.com/78854859/107878916-5582f780-6f08-11eb-828a-a954bad5e299.png)
> is it a bug or backend issue.

Can you produce the GE dump?

**Comment by IrfanH495** [comment]
@Panderner 
[recording.zip](https://github.com/hrydgard/ppsspp/files/5977890/recording.zip)
what like that
