### ISSUE TITLE
Co-op issue on MGS:PW

### ISSUE THREAD

**Issue by ANR2ME** [hrydgard/ppsspp#14130]
Reported through forum's PM, MGS:PW can't play Android vs PC, and after trying to reproduce it i found 2 issues

### What happens?
1). If PC host, Android can't see the game room because for some unknown reason the one on Android is always using port 1024 regardless of Port Offset
```
37:33:582 idle0        D[SCENET]: hle\scenetadhoc.cpp:6015 HELLO Dump:
          00000000  04 01 02 00 be 09 00 00 49 4d 41 4e 4f 5f 4b 00  ........IMANO_K.
          00000010  00 00 00 00 00 00 00 00 3b b5 32 01 1b ff        ........;.2...
37:33:582 idle0        D[SCENET]: hle\scenetadhoc.cpp:1572 sceNetAdhocPdpSend[1:14099](BC): Sent 35 bytes to 192.168.8.102:14099
37:33:582 idle0        D[SCENET]: hle\scenetadhoc.cpp:1572 sceNetAdhocPdpSend[1:14099](BC): Sent 1 bytes to 192.168.8.102:14099
37:33:817 idle0        D[SCENET]: hle\scenetadhoc.cpp:1743 sceNetAdhocPdpRecv[1:14099]: Received 1 bytes from 192.168.8.102:1024
37:34:084 idle0        D[SCENET]: hle\scenetadhoc.cpp:1572 sceNetAdhocPdpSend[1:14099](BC): Sent 1 bytes to 192.168.8.102:14099
37:34:330 idle0        D[SCENET]: hle\scenetadhoc.cpp:1743 sceNetAdhocPdpRecv[1:14099]: Received 1 bytes from 192.168.8.102:1024
37:34:588 idle0        D[SCENET]: hle\scenetadhoc.cpp:6015 HELLO Dump:
          00000000  04 01 02 00 be 09 00 00 49 4d 41 4e 4f 5f 4b 00  ........IMANO_K.
          00000010  00 00 00 00 00 00 00 00 3b b5 32 01 1b ff        ........;.2...
```

2). If Android host, and PC joined, the one on PC failed to start the mission, seems to be AdhocMatching issue

### What *should* happen?
Multiplayer co-op should works

### Please test newest version in https://buildbot.orphis.net/ppsspp/
PPSSPP v1.11.1-4-gd23bef152

**Comment by ANR2ME** [comment]
This port 1024 is really weird... because the socket is created within AdhocMatchingStart and it was created the same way as host & join, so i wondered why it use different port between host & join on android side...

**Comment by MojoJojoDojo** [comment]
Versus also is not working PC to PC but only if there is some lantancy involved (?) not sure .
Coop just straight disconnects though.

**Comment by ANR2ME** [comment]
It's strage that i can't see anything in the Logcat when debugging from Android Studio... i'm getting this error
```
23:24	Error running 'android'
			Invalid argument : Argument invalid
			[port]
```

**Comment by ANR2ME** [comment]
This is the log from Android, it's sending data from port 14099 to PC port 14099 which is correct
```
2021-02-14 01:01:34.534 20496-24474/org.ppsspp.ppsspp I/PPSSPP: [SCENET] HELLO Dump:
              00000000  04 01 02 00 a2 45 00 00 49 4d 41 4e 4f 5f 4b 00  .....E..IMANO_K.
              00000010  00 00 00 00 00 00 00 00 3b b5 32 01 04 ff        ........;.2...
2021-02-14 01:01:34.535 20496-24474/org.ppsspp.ppsspp I/PPSSPP: [SCENET] sceNetAdhocPdpSend[1:14099](BC): Sent 35 bytes to 192.168.8.101:14099
2021-02-14 01:01:34.535 20496-24474/org.ppsspp.ppsspp I/PPSSPP: [SCENET] sceNetAdhocPdpSend[1:14099](BC): Sent 1 bytes to 192.168.8.101:14099
2021-02-14 01:01:35.357 20496-24474/org.ppsspp.ppsspp I/PPSSPP: [SCENET] sceNetAdhocPdpSend[1:14099](BC): Sent 1 bytes to 192.168.8.101:14099
```
04:47:754 idle0        D[SCENET]: HLE\sceNetAdhoc.cpp:1575 sceNetAdhocPdpSend[1:14099](BC): Sent 1 bytes to 192.168.8.102:14099
04:47:765 idle0        D[SCENET]: HLE\sceNetAdhoc.cpp:1746 sceNetAdhocPdpRecv[1:14099]: Received 35 bytes from 192.168.8.102:1024
04:47:765 idle0        D[SCENET]: HLE\sceNetAdhoc.cpp:7274 InputLoop[1]: Unknown Port[70:7b:67:74:51:21:56560] (Recved=0, Length=35)
04:47:776 idle0        D[SCENET]: HLE\sceNetAdhoc.cpp:1746 sceNetAdhocPdpRecv[1:14099]: Received 1 bytes from 192.168.8.102:1024
04:47:776 idle0        D[SCENET]: HLE\sceNetAdhoc.cpp:7274 InputLoop[1]: Unknown Port[70:7b:67:74:51:21:56560] (Recved=0, Length=1)
04:48:251 idle0        D[SCENET]: HLE\sceNetAdhoc.cpp:1575 sceNetAdhocPdpSend[1:14099](BC): Sent 1 bytes to 192.168.8.102:14099
04:48:582 idle0        D[SCENET]: HLE\sceNetAdhoc.cpp:1746 sceNetAdhocPdpRecv[1:14099]: Received 1 bytes from 192.168.8.102:1024
04:48:582 idle0        D[SCENET]: HLE\sceNetAdhoc.cpp:7274 InputLoop[1]: Unknown Port[70:7b:67:74:51:21:56560] (Recved=0, Length=1)
04:48:753 idle0        D[SCENET]: HLE\sceNetAdhoc.cpp:1575 sceNetAdhocPdpSend[1:14099](BC): Sent 1 bytes to 192.168.8.102:14099
```
But for some reason, upon arrival, the one on PC is detecting the source port to be 56560 (where it should be 14099), thus when replied the one on android never received the reply because it's going to the wrong port.

I have no idea how the port 14099 ended became 56560, and it seems to only happened when receiving data from android, while PC to PC have the correct port being detected.

**Comment by ANR2ME** [comment]
> 
> 
> Versus also is not working PC to PC but only if there is some lantancy involved (?) not sure .
> Versus works Android to PC but Android got to host.
> Coop just straight disconnects though.

I'm not sure whether the issue resides on Windows or Android, but detecting the wrong port like this will certainly cause communication issue on all games that use PDP/UDP be cause after receiving data the game will send the reply to the wrong port thus that reply ended never received, since AdhocMatching is using PDP it will certainly have issue too, although it's a bit random where sometimes it can detects the port correctly.

I will try to create test build later that will shows warning on screen if there is incoming AdhocMatching data that came from a wrong port, and tester will need to test this on PC vsPC, and Android vs Android, so we can at least know whether this wrong detection only happened on windows or android too.

**Comment by MojoJojoDojo** [comment]
I wonder if this is why Patapon 3 and God Eater got issues with the port offset too...
At least with God Eater this happened with multiple instances on 1 PC.
Patapon 3 needs a port offset above 5000 last time I tried.

**Comment by ANR2ME** [comment]
This wrong port detection have nothing to do with port offset, changing it will still be detected as 1024, even when MGS:PW create the 2nd socket (which is port 4100) the data also detected as coming from 1024, just like the one from the other socket (port 4099), so this 1024/56560 seems to be fixed number not sure where it came from.

**Comment by MojoJojoDojo** [comment]
> This wrong port detection have nothing to do with port offset, changing it to any value will still be detected as 1024, even when MGS:PW create the 2nd socket (created when the mission started, which use port 4100) the data also detected as coming from 1024, just like the one from the other socket (AdhocMatching socket that use port 4099), so this 1024/56560 seems to be fixed number not sure where it came from.
> 
> I've tried to zeroing/memset the `sockaddr_in` arg and set it's length correctly upon calling `recvfrom` but the output source port is still wrong :( this is confusing...

From the PR it seems that it is port offset related...
Using 10000 as a port offset does seem like a good choise but its a really high number for some routers to open.

**Comment by ANR2ME** [comment]
Routers should have any issue opening any port, unless that port is already used for something else.
And port offset related issue mean's it's restricted by the OS (requires admin) or the port is exclusively taken by other app. 

But the issue i had is a bit strange, if port offset is 5000 using 'bind' on a specific port will be success and retrieving the binded port using `getsockname` will also shows that specific port. 
However, when the socket is used for sending UDP data, the source port ended to be a different port (a random high port, usually used when using port 0 which let the system assign any available port), and i can't find any documentation that mentions this behavior where requested port being replaced with a random port, usually `bind` will return an error if the requested port can't be binded instead of silently replacing the port with a random port.
I'm not sure if this issue only happened on my OS (Realme's OS based on Android 10) or other Android variant too.
