### ISSUE TITLE
[Suggestion] Change Touch Control Button Positioning

### ISSUE THREAD

**Issue by NABN00B** [hrydgard/ppsspp#14141]
Hello Team.

Currently the touch control layout positions elements relative to the top left corner of the view.
This makes it impossible to move elements to the center (unless you manually calculate the numbers for your window size and write them directly into the config file).

I propose the positioning of the elements to be relative to the center of the screen. The change should also be made for the grid visualisation and the center lines should be highlighted with eg a thicker line or red color.

**Comment by ResurrectionRedmi9** [comment]
This should improve now.

**Comment by unknownbrackets** [comment]
This was changed by #14747.  It was not actually relative to the top left, but the sizes weren't proportional so it was confusing (see #14743.)

-[Unknown]
