### ISSUE TITLE
(libretro) Framerate/pacing is broken in all games v.1.11.2-85-g19bd943

### ISSUE THREAD

**Issue by BParks21** [hrydgard/ppsspp#14158]
### What happens?
Since this version mentioned above framerate is broken. For instance VP is a 60fps game and it's reporting in the 30's with RTSS. The game appears to be still running at full game speed with no visible or audio slowdown. Turning duplicate frames on or off has no effect on 60 or 30fps games now. View my screenshot of VP, It is a 60fps game. Frame duplication no longer does what it's intended for 30fps games, see Daxter screenshot. 
![Screenshot (67)](https://user-images.githubusercontent.com/12180630/108127037-a0238180-7078-11eb-8fad-ecd3374f6d14.png)

![Screenshot (65)](https://user-images.githubusercontent.com/12180630/108126769-373c0980-7078-11eb-918a-629118c408e4.png)
 Framerate is fine on ppsspp (1.11.2-75-gb0fdc7a) 

### What *should* happen?
Smooth framerate and target framerates. 

### What hardware, operating system, and PPSSPP version?  On desktop and mobile phone, GPU matters for graphical issues.
i7 8086k, GTX 1080 ti, Windows 10 2004, v.1.11.2-85-g19bd943.

**Comment by hrydgard** [comment]
So between 75 and 85.  Could you narrow it down some more?

Candidates: #13865 , #14156 , #14154  or #14152  .. none look super likely. hm.

**Comment by BParks21** [comment]
@hrydgard How would I go about testing these builds with these merges in RA? I don't know where to find older PPSSPP cores and unfortunately idk how to build the core.

**Comment by unknownbrackets** [comment]
I guess it must be the unthrottle mode.  Does libretro just like always unthrottle maybe?  We can switch it back to CONTINUOUS for everyone.

-[Unknown]

**Comment by hrydgard** [comment]
Or we could use the libretro ifdef to only use it for that. It does make sense that retroarch might be handling its own throttling...

**Comment by Veritas83** [comment]
I did notice I'm losing about 20 FPS in builds since 85+, but I only play one title. Ridge Racer 2. (This is only in RetroArch) I haven't found standalone dev builds anywhere yet...

**Comment by Veritas83** [comment]
Found the dev builds :P

https://github.com/hrydgard/ppsspp/actions/runs/574342727#artifacts

Issue is not present in standalone

<img src="https://gyazo.com/30e3b464b64ac0f496f42a42d754313c.png">

**Comment by unknownbrackets** [comment]
e4ef9cd will probably fix this.

-[Unknown]

**Comment by Veritas83** [comment]
RetroArch hasn't made that build avail yet, Just checked it updates to f7f2d51 - still present in that build.

**Comment by Tasosgemah** [comment]
Yeah, i was playing Outrun 206 and the frame rate seems very low and uneven. On standalone it's smoother.

**Comment by hrydgard** [comment]
no need to add more comments until you have actually tried the potential fix, e4ef9cd.

**Comment by Tasosgemah** [comment]
Sorry, i don't know how to use these fixes.

I'll wait for the next version then, i did a mistake and didn't backup version 1.11-1.

**Comment by BParks21** [comment]
Fixed!

**Comment by Veritas83** [comment]
RetroArch finally pushed an updated build :)

<img src="https://i.gyazo.com/7f546c950998dbf2a6fffe448facf2de.png">
