### ISSUE TITLE
Crisis Core locks up after loading save file (recent builds)

### ISSUE THREAD

**Issue by BParks21** [hrydgard/ppsspp#14159]
### What happens?
Every time I try to load my save file the game freezes. RA remains responsive. I'm sure when it was working correctly but it was sometime around 1.11.2 or maybe before. Edit: Just updated the official PPSSPP to the latest dev build and it's also occurring.

### What *should* happen?
Make it past loading a save file. 

### What hardware, operating system, and PPSSPP version?  On desktop and mobile phone, GPU matters for graphical issues.
i7 8086k, GTX 1080 ti, Windows 10 2004, v.1.11.2-85-g19bd943

**Comment by BParks21** [comment]
@hrydgard 
Just updated the official PPSSPP to the latest dev build and it's also occurring. Sorry for that.

**Comment by hrydgard** [comment]
No need to be sorry, that's good info.

**Comment by Panderner** [comment]
Is the older versions worked?

**Comment by kage2051** [comment]
On Android, I could only test 1.11.2-20 and 1.11.2-69. The first build loads the save as usual, but then updated to the second build which fails to load that save. So yeah, any builds from yesterday will expose the issue.

**Comment by unknownbrackets** [comment]
This appears to be related to #13943.

-[Unknown]
