### ISSUE TITLE
Texture scaling causes audio stuttering in Saint Seiya: Ultimate Cosmo

### ISSUE THREAD

**Issue by LOuroboros** [hrydgard/ppsspp#14155]
### What happens?
Whenever clips of audio are played while setting texture scaling to anything above native *(off)*, there's noticeable cracking and stuttering in the game's audio tracks.

### What *should* happen?
The clips should play without stuttering.

### Please test newest version in https://buildbot.orphis.net/ppsspp/
**CPU**: i3 2120
**GPU**: Gigabyte's NVIDIA GeForce GT 1030, Driver Version 461.40
**RAM**: 4GB running in single channel for reasons.
**OS**: Windows 10 x64 v2004
**PPSSPP Version**: v1.11.2-75-gb0dfc7a30 x64

Video showing the problem in action:

https://user-images.githubusercontent.com/4485172/108025326-0a024380-7005-11eb-843a-f607f2802308.mp4

Here's my ppsspp.ini file in case there's something wrong with my configuration.
https://pastebin.com/K77wL12k

**Comment by unknownbrackets** [comment]
Currently, texture scaling runs on the CPU and is very expensive.  It's a lot better on multicore processors, but your device may not be powerful enough.

I recommend trying Vulkan and enabling the hardware texture scaling option.  This uses the GPU.

-[Unknown]

**Comment by LOuroboros** [comment]
> I recommend trying Vulkan and enabling the hardware texture scaling option. This uses the GPU.

Alrighty. How do I enable hardware texture scaling though. Is that just the way texture scaling works when Vulkan is set as the graphics renderer or something?

**Comment by unknownbrackets** [comment]
There's a "Texture Shader" setting that will show up near the other settings on the Settings screen.  Select something other than off to use hardware scaling.

-[Unknown]

**Comment by LOuroboros** [comment]
> 
> 
> There's a "Texture Shader" setting that will show up near the other settings on the Settings screen. Select something other than off to use hardware scaling.
> 
> -[Unknown]

Alright.
Even without using Hardware Shader, switching to Vulkan solved the issue somehow. After setting Texture Scaling to 2x or 3x while using Vulkan as the graphics renderer, the audio clips no longer stutter, though I'll still stick to your recommendation of using a hardware shader anyway.

Thank you!
