### ISSUE TITLE
Car reflections in Outrun don't work in libretro

### ISSUE THREAD

**Issue by Tasosgemah** [hrydgard/ppsspp#14166]
Latest version (1.11) fixed this in the standalone version.

Libretro version (1.11-2) still doesn't show reflections.

I'm using RetroArch in Windows 10.

**Comment by Panderner** [comment]
You need a compat.ini from latest builds of standalone PPSSPP. Put the compat.ini to /retroarch/system/ppsspp directory.

**Comment by Tasosgemah** [comment]
> 
> 
> You need a compat.ini from latest builds of standalone PPSSPP. Put the compat.ini to /retroarch/system/ppsspp directory.

Thank you! This solved a few other problems i has as well (like the screen turning black in Ghosts n Goblins).

All this time i was updating the core but i had the PPSSPP system folder untouched... from 2017! So stupid.
