### ISSUE TITLE
Wall-E Black screen after save screen

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#14164]
Last build work: v1.11.2-20-g1c3c38428
Issue started: v1.11.2-20-g1c3c38428-android

I've tried to create a save file for WALL-E but it stuck at black screen

**Comment by unknownbrackets** [comment]
Did #14163 help?  Likely a shared cause.

-[Unknown]

**Comment by Panderner** [comment]
Nevermind #14163 fixed this and the game working fine, Closing this.
