### ISSUE TITLE
[Android] Pro Yakyu Spirits 2010 (NPJH50234): Rendering errors with hardware transform off

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#14167]
### What happens?
Some Graphics are not appear correctly only Android. (EDIT: Turned out to be with hw transform off)
But, This issue will happen only Android.
(OpenGL & Vulkan both.)
Windows10 is not happen.

GEdump here(Got from Android).
 But, If you open the file on Windows  then it will seems correctly.
[NPJH50234_0004.zip](https://github.com/hrydgard/ppsspp/files/5993698/NPJH50234_0004.zip)

So, Please see attache screenshot.

**[Windows10 appear the Left & Right Team symbols correctly.]**
![image](https://user-images.githubusercontent.com/48179091/108165524-0e7a4980-7136-11eb-85c9-799ee5cd4238.png)

**[Android is missing the Left & Right Team symbols.]**
![Screenshot_20210217-115050_PPSSPP](https://user-images.githubusercontent.com/48179091/108165427-e7bc1300-7135-11eb-9f00-bd1e0d268900.jpg)

This BaseBall game has a other series.
- Pro Yakyu Spirits 2011
- Pro Yakyu Spirits 2012
- Pro Yakyu Spirits 2013
- Pro Yakyu Spirits 2014
**This problem** is not happen other series. Only 2010.
And, 2010 has a another graphic issue. #13391 

Plus,Other series(2011~2014) has another graphic glitch. #13980 :grin:

### What *should* happen?
Appear the graphic correctly.

### Please test newest version in https://buildbot.orphis.net/ppsspp/

I tested Windows & Android.

**[No Problem]**
PPSSPP Ver.：1.11.2-85
OS：Windows10（64-bit）Japanese
CPU：Ryzen7 3800X（8-core）
GPU：RADEON RADEON RX5700XT
Resolution：2560×1440
RAM：32GB

**[Have a Problem]**
PPSSPP Ver.：1.11.2-85
OS：Android 11.0
DeviceName：Samusung Galaxy S20 / SC-51A
CPU：Snapdragon865（Octa-core）
GPU：Adreno 650
Resolution：3200 x 1440 (Max)
RAM：12GB
ROM：128GB
ExternalStrage：microSDXC 512GB

**Comment by Panderner** [comment]
Have you tried OpenGL and Vulkan for your PCs?
It seems it doesn't occur for D3D9 and D3D11

**Comment by nassau-tk** [comment]
Hey! @Panderner 👍 ✨ 

I said ==> "This issue happen only Android". :laughing:
So, Any backend has no problem on Windows PC.

**Comment by Panderner** [comment]
Hmm this GE Dump looks right for my Realme C2
![Screenshot_2021-02-17-15-55-14-10_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/108173078-a11be800-7138-11eb-974b-27f502ff8f4e.png)

**Comment by nassau-tk** [comment]
@Panderner 

Ooooops!!!
Sorry and Thanks!!
My Phone was turning off on "Hardware Transform"!

Close!!

**Comment by hrydgard** [comment]
Although that's still a bug! we want both on and off to work the same. I'm reopening, it's probably worth fixing.

**Comment by nassau-tk** [comment]
Really? 😮 wao...

**Comment by Panderner** [comment]
If you turn off hardware transform the team symbols disappears.

Hardware transform on:
![Screenshot_2021-02-17-17-48-15-677_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/108186579-7fc2f800-7148-11eb-965e-f2c3c56f1f12.jpg)

Hardware transform off:
![Screenshot_2021-02-17-17-48-21-929_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/108186601-86516f80-7148-11eb-808c-044a2fda36dd.jpg)

**Comment by Panderner** [comment]
@nassau-tk have you tried to turn off hardware transform for your PC?

**Comment by nassau-tk** [comment]
@Panderner 

Yes, I did it.
Result is  same yours.

**Comment by unknownbrackets** [comment]
If I disable light 0, it works, so it's definitely related to that.  Software rendering is fine, only software transform effected.  Disabling alpha blend/test makes it fully black, so it's turning to zero.

The issue here is that `normal * world` ends up as a zero vector, and `normalize(vec3(0))` ends up as NaN.  It seems like glsl is handling this better, but I could imagine different drivers / implementations handling differently.

It seems clear from this case that the PSP considers `normalize(vec3(0))` to equal `vec3(0, 0, 1)` or similar, and we've seen this before elsewhere.

-[Unknown]
