### ISSUE TITLE
ios touch flicking bug

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#14178]
Report from my chinese friend
Happened when more 2 touch
https://youtu.be/uJvCwg8vqMY

**Comment by hrydgard** [comment]
That's interesting results, probably we are not dealing with iOS touch events correctly. I'm happy I made that touch tester so we could see how bad it is :)

I'm gonna investigate at some point soon.

**Comment by unknownbrackets** [comment]
This is probably a duplicate of #5099, and maybe related to https://github.com/hrydgard/ppsspp/issues/5099#issuecomment-293453497.

-[Unknown]

**Comment by sum2012** [comment]
Close this one
