### ISSUE TITLE
Loading SaveState issue on MGS:PW

### ISSUE THREAD

**Issue by ANR2ME** [hrydgard/ppsspp#14194]
### What happens?
Loading a SaveState that was created on Oct 10th 2020 is showing this popup
![image](https://user-images.githubusercontent.com/7974720/108626820-c2f0d400-7484-11eb-8a1f-f87d591ecc5b.png)
Answering "No" will crashes PPSSPP, while answering "Yes" will load the savestate successfully... but will it cause any issue later?

This is the screen after loaded from SaveState successfully
![image](https://user-images.githubusercontent.com/7974720/108626915-37c40e00-7485-11eb-8e2e-fb4ae8838bec.png)

### What *should* happen?
Load StateState normally as usual (like a few days ago i think) when possible that is :)

### Please test newest version in https://buildbot.orphis.net/ppsspp/
Tested on PPSSPP v1.11.2-184-ga062c177a

**Comment by sum2012** [comment]
Please test
v1.11.2-69-g71b1c9dfe
v1.11.2-71-g93fd62f54
May related to this
Merge: 71b1c9dfe 06f8ab5a4 Merge pull request #13832 from unknownbrackets/events SaveState: Make event restoring more obvious

**Comment by ANR2ME** [comment]
> 
> 
> Please test
> v1.11.2-69-g71b1c9dfe
> v1.11.2-71-g93fd62f54
> May related to this
> Merge: [71b1c9d](https://github.com/hrydgard/ppsspp/commit/71b1c9dfea4c98525424ac927e6155b365a9f7c3) [06f8ab5](https://github.com/hrydgard/ppsspp/commit/06f8ab5a499a2ed5235f62389f88386c60f4bc43) Merge pull request #13832 from unknownbrackets/events SaveState: Make event restoring more obvious

i think this issue pretty recent, as i remembered it was working fine a few days ago.
I'll check the more recent one.

**Comment by hrydgard** [comment]
@unknownbrackets  wanna take a look? or should I?

**Comment by unknownbrackets** [comment]
Yeah, dumb mistake.

-[Unknown]

**Comment by Ocatopuss** [comment]
This also occur on Gradius Collection (ULES00381_1.00) and Salamander Portable (ULJM05219_1.01).

And if you try to overwrite the state (by answering "Yes" to load it successfully), it will occur the same issue.

Hmm they are all KONAMI games...

**Comment by unknownbrackets** [comment]
Try the build here under "Artifacts":
https://github.com/hrydgard/ppsspp/pull/14197/checks

-[Unknown]
