### ISSUE TITLE
text is not shown on PPSSPP ios

### ISSUE THREAD

**Issue by gailboss** [hrydgard/ppsspp#14193]
I used the latest version of PPSSPP on the 14.4 ios

The application runs pretty fine. But when I was playing the game( yugi gx tag3), the text is not shown up how to solve this pls help.

**Comment by gailboss** [comment]
![Uploading 0F626636-4DE6-4806-8CF3-7F1CBE6EB2F0.png…]()

**Comment by gailboss** [comment]
![3761F56D-A011-4309-ADE7-372D16DC8D01](https://user-images.githubusercontent.com/79407582/108626942-2d5e4000-7496-11eb-88f7-5249231ef039.png)

**Comment by hrydgard** [comment]
Are you sure you're using the latest build? This looks familiar to #13573 , which is due to a bug in iOS 14, which the latest builds of PPSSPP can work around.

**Comment by gailboss** [comment]
Oops. I found I did not use the latest version. Now, I reinstall it, and it now works. Thank alot

**Comment by Nick78d** [comment]
HI, 

Having the same issue with last build  (v1.13.2-1976) with ppsspp for iOS installed with altstore.
no text is shown on games like metal gear acid 1 and 2, metal gear portable ops, peace walker.

Tried to add the assets file on to the PPSSPP folder on IOS files app but nothing help.

Any idea ? 

Thanks 
![Capture d’écran   2022-11-20 à 21 24 42 png](https://user-images.githubusercontent.com/118691074/202924563-92a2231e-0222-422f-a4a0-e437b3a3a4bf.png)
![Capture d’écran   2022-11-20 à 21 25 10](https://user-images.githubusercontent.com/118691074/202924568-9acd6c65-a911-4349-84fd-78d354fc2859.png)

**Comment by unknownbrackets** [comment]
Can you try other games such as Crisis Core or Lunar: Silver Star Harmony?  The former doesn't use fonts, and the latter does.  If both work, but Metal Gear games don't, we'd probably rule out it being anything font related.

Also, does this happen with both "IR Interpreter" and "Interpreter" in the CPU core settings?

-[Unknown]

**Comment by unknownbrackets** [comment]
#16424 should at least fix that.

You can alternatively try going to Settings -> Tools -> Developer tools -> JIT debug tools, and then click Disable all.  It will likely be slow, but if this fixes it, it would help to figure out what is the minimum necessary to disable to reproduce the problem.

-[Unknown]

**Comment by unknownbrackets** [comment]
Does it work now using the Interpreter?  And just to confirm, you're using the latest git build (it should show on the main screen what version you're using.)  If you're still using v1.13.2, there have already been many IR fixes since then.

-[Unknown]

**Comment by Nick78d** [comment]
It works now with VFPU_XFER deactived.
I'm using the very last build
thanks

**Comment by Gamemulatorer** [comment]
This should be move to future-prio milestone?
