### ISSUE TITLE
[Android] Building on Android gets Snappy error

### ISSUE THREAD

**Issue by ANR2ME** [hrydgard/ppsspp#14215]
### What happens?
I'm getting this error when rebuilding Android version (NormalOptimized, armeabi-v7a)
```
C:\Users\AdamN\Documents\Projects\ppsspp\ext\snappy\snappy.cpp:1033:36: error: invalid output constraint '=@ccz' in asm
```
Do i need to change or update anything else, other than the submodule?

### What *should* happen?
Build successfully as usual.

### Please test newest version in https://buildbot.orphis.net/ppsspp/

Attempt to build the latest master branch using my usual configuration: 
Android Studio 4.1.2, Gradle model version=6.1.1, NDK version=20.1.5948944

**Comment by unknownbrackets** [comment]
https://github.com/hrydgard/ppsspp/blob/0cd561384862d9e964166355a2ddbc13a7d59c2e/ext/snappy/snappy.cpp#L1029

Hm, that shouldn't get compiled outside x64... maybe it's trying to build all ABIs and there's a problem building Android x64?

-[Unknown]

**Comment by ANR2ME** [comment]
This issue seems to happen after Snappy update

**Comment by hrydgard** [comment]
can always revert that temporarily... 

Or, looks to me that it would be safe to just remove that ifdef and the assembly line. It seems to be some kind of micro-optimization.

**Comment by unknownbrackets** [comment]
Does #14217 help?

-[Unknown]

**Comment by ANR2ME** [comment]
Yes, it's working fine now. Thanks!

Btw, i have another question (unrelated to the issue),
when i opened ppsspp project i'm seeing this in Event Log:
```
23:19	NDK Resolution Outcome: Gradle model version=6.5, NDK version=20.1.5948944
```
But when i select a different "Active Build Variant" or "Active ABI" this will shows up in Event Log:
```
23:20	NDK Resolution Outcome: Gradle model version=6.1.1, NDK version=20.1.5948944
```
Does Gradle version supposed to change like that when choosing different Build Variant?

**Comment by unknownbrackets** [comment]
That's weird.

I'm still most of the time using ant, just because I can easily build specific archs only, manage threads, and build headless that way which all help maintain a reasonable workflow.  It does seem like recent gradle exposes build logs better now (should check CI...), but I don't use it enough to know why the above would be happening...

-[Unknown]

**Comment by hrydgard** [comment]
That is wacky, I haven't seen that. Maybe upgrade Android Studio to 4.1.2, unlike 4.1.0 it's not as full of terrible bugs anymore.

**Comment by ANR2ME** [comment]
Looks like i need to do Gradle Sync first (haven't do that for a long time), after doing that changing Build Variant will always shows Gradle version 6.5

Thanks guys.
