### ISSUE TITLE
NotEqual/!= is no longer supported in post process effects

### ISSUE THREAD

**Issue by LunaMoo** [hrydgard/ppsspp#14213]
Didn't had much time, but trying to figure out why my effects started failing for someone in recent version found out that "!=" errors as unsupported(in OGL, in other backends the log seems kind of useless). This also means "notEqual" function is unsupported which causes failure in both 5xBR effects shipped with PPSSPP.

 We can't check !=, but can > and < and if possible even check for the opposite exact value, so a custom function to replace notEqual is possible workaround, but would be cool if workarounds were not necessary.

 From forum seems the issue is very fresh, probably started with recent glslang update, but untested, I'm kind of rushing to post now due to lack of time.

Edit: https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/notEqual.xhtml notEqual requires a minimum version of 1.30 in case a version was changed differently causing this problem.
 Also since I forgot to mention, I reproduced the issue on rtx 3060ti / win 64.

**Comment by unknownbrackets** [comment]
Ah, I think this is because glslang changed `!=`: https://github.com/KhronosGroup/glslang/pull/2260
And we didn't update SPIRV-Cross: https://github.com/KhronosGroup/SPIRV-Cross/pull/1175

-[Unknown]

**Comment by LunaMoo** [comment]
Yup, that was it, thanks [Unknown] :3
