### ISSUE TITLE
Tekken Dark Resurrection stuck at black screen after exiting the game

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#14212]
After exiting arcade mode match or game over screen it stuck at black screen. Although exiting the match via return to mode select works fine.

**Comment by unknownbrackets** [comment]
When did this last work?  Is this only when wifi is enabled?

-[Unknown]

**Comment by Panderner** [comment]
Last build worked is v1.11.2-20-g1c3c38428
The issue started in v1.11.2-64-geed70fc31

**Comment by ANR2ME** [comment]
v1.11.2-20-g1c3c38428 to v1.11.2-64-geed70fc31 is quite a large gap, nothing worked in between? or because you only tested this on Android?

**Comment by Panderner** [comment]
I only tested on Android since the v1.11.2-20-g1c3c38428 to v1.11.2-64-geed70fc31 gap is not available on Android.

**Comment by unknownbrackets** [comment]
It could be several commits:
https://github.com/hrydgard/ppsspp/compare/1c3c38428...eed70fc315

Has anything changed in the latest git builds?  Maybe it was related to the GTA issue.

-[Unknown]

**Comment by Panderner** [comment]
Nope still happens in latest version.

**Comment by sum2012** [comment]
I test from windows 7 64 bit.
Last work
v1.11.2-44-g9b13220f4
First bad
v1.11.2-54-g5d62610a9
It is #13943 
The  volatile memory thing still have regression

v1.11.2-355-g7db53d2f0-windows-amd64 Log:
https://gist.github.com/sum2012/9c90ae6f1dcd4af9737c37cd9e7152b1

**Comment by Panderner** [comment]
Thank you @sum2012

**Comment by Panderner** [comment]
As confirm that #14364 fixes freezes at black screen after exiting the game.
