### ISSUE TITLE
Chili Con Carnage black screen before Eidos logo

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#14219]
It seems #14205 broke Chili Con Carnage, It result of black screen before Eidos logo FMV for v1.11.2-209-g39198b53a and newer.

**Comment by unknownbrackets** [comment]
Any log messages or errors?

That should've fixed some edge cases in buffer management.  If that resulted in a game breaking, maybe it was having buffer management problems and they were working around another bug.

-[Unknown]

**Comment by Panderner** [comment]
```
58:43:194 Sound        E[ME]: HLE/sceAtrac.cpp:1053 80630010=sceAtracGetRemainFrame(0, 09fab9d0[00000001]): no data
58:43:194 Sound        E[ME]: HLE/sceAtrac.cpp:1053 80630010=sceAtracGetRemainFrame(1, 09fab9d0[00000001]): no data
```
Yes it seems this log is spamming when I launching the game

**Comment by unknownbrackets** [comment]
sceAtrac is not affected by this code so I assume that was being logged beforehand too (and is likely just a game bug.)

I guess it can only be caused by the buffer allowing one less byte.

-[Unknown]

**Comment by unknownbrackets** [comment]
When the build for #14234 is available, does that fix it?

-[Unknown]

**Comment by Panderner** [comment]
Thanks @unknownbrackets #14234 fixed this issue, closing this.
