### ISSUE TITLE
GTA LCS & VCS stucks at loading screen

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#14216]
According to https://github.com/hrydgard/ppsspp/pull/13943#issuecomment-783530171 this comment leads that GTA LCS & VCS stucks at loading screen.

**Comment by ANR2ME** [comment]
This kinda issue i guess... 
![image](https://user-images.githubusercontent.com/7974720/109016416-bd93c380-76e8-11eb-954f-309960c3e9de.png)
![image](https://user-images.githubusercontent.com/7974720/109016483-cd130c80-76e8-11eb-9c1b-37447f969d65.png)

**Comment by djdarko** [comment]
Here is a bit of extra information:

It also causes the "Loading from Memory Stick" text to be missing from both games:

![missing text](https://user-images.githubusercontent.com/79668403/109223603-0c3c6e80-7778-11eb-872d-8101c8e606cf.png)

Those screens are shown at startup if save data is present.

The first release with the issue:
ppsspp-v1.11.2-52-g5ed594780-windows-amd64

The last release without the issue:
ppsspp-v1.11.2-44-g9b13220f4-windows-amd64

**Comment by hrydgard** [comment]
Yeah, as mentioned in https://github.com/hrydgard/ppsspp/pull/13943#issuecomment-783839963 , the cause is the new handling of the volatile memory, which fixed that NBA game.

We'll either fix or revert.

**Comment by sum2012** [comment]
Please note that jpcsp run the game no problem
ppsspp v1.11.2-226-g35ad3106f-windows-amd64 log
https://gist.github.com/sum2012/51d0f4c849930975254f3adb5b4b151c

**Comment by unknownbrackets** [comment]
Currently in PPSSPP (ticks):

```
At 59172090 shutdown start
At 59194006 try lock
At 59616091 volatile unlock
```

So it's attempting to unlock after 98us. but we don't unlock for 2000us.  After more tests, I see it unlocking BEFORE shutdown finishes, about 27614 cycles (124us.)  We probably have some things running too fast, so I'll just make it delayed, but differently delayed.

-[Unknown]

**Comment by unknownbrackets** [comment]
Correction: for savedata generally, it's indeed tied to thread priority.  Both access and graphics threads must run (so the worst of their priorities matter), and they block on SIZES for around 4000us for me.  Status does not change until those threads run (i.e. if I block them from running by doing other stuff, the status takes longer to change.)

-[Unknown]
