### ISSUE TITLE
Unable to load states for 我的妹妹不可能这么可爱 (ULJS00358_1.0.1)

### ISSUE THREAD

**Issue by Halo-Michael** [hrydgard/ppsspp#14244]
### What happens?
Failed on load states, happened on both Windows and iOS.
![$JCV6{TZOA~)HX10NG`%B}0](https://user-images.githubusercontent.com/45062120/109622487-1d6dec80-7b77-11eb-822e-545c9550c923.png)
On iOS, it shows "Failure at ISOFileSystem" or just crash.

### What *should* happen?
Load states succesful.

It seems to behave normally in version 1.11.2(Release).

### What hardware, operating system, and PPSSPP version?  On desktop and mobile phone, GPU matters for graphical issues.
Windows and iOS.

**Comment by Halo-Michael** [comment]
I have installed five games, only this game can’t load states.

**Comment by Panderner** [comment]
Chinese patched ISO? Have you tried to test unpatched japanese ISO?

**Comment by Halo-Michael** [comment]
> Chinese patched ISO? Have you tried to test unpatched japanese ISO?

No, but since it can work normally in the previous version of ppsspp, I think it should be a problem with ppsspp.

**Comment by sum2012** [comment]
What ppsspp version of your old status made ?

**Comment by unknownbrackets** [comment]
Can you attach the save state in a zip here?

-[Unknown]

**Comment by Halo-Michael** [comment]
[PPSSPP_STATE.zip](https://github.com/hrydgard/ppsspp/files/6069586/PPSSPP_STATE.zip)

> Can you attach the save state in a zip here?
> 
> -[Unknown]

**Comment by unknownbrackets** [comment]
Seems like the state was created with c0a5fa3 (possibly from a previous state.)

The state says it has 0x25 registered event types, but it does not have any type IDs saved for 0x1e and above.  So it starts registering new events at 0x24, but runs out of space because there are 6 slots that remain empty.

This happens in sceNetAdhoc, but there were duplicate event IDs, which causes confusion... I think there were multiple duplicates, possibly from multiple rounds of save states.  I'm just going to add some workaround code.

-[Unknown]

**Comment by Halo-Michael** [comment]
I just tried more on iOS. On iOS, PPSSPP will just crash at first time when try to load old states. If I discard the old states and start playing from the beginning, after about two minutes of playing, save the states and load the new states, then PPSSPP will not crash, but it may still fail to load the states and prompt "Failure at ISOFileSystem".

**Comment by unknownbrackets** [comment]
Was that even with the #14249 change?  It might've caused weird corruption if it ignored the assert.

-[Unknown]

**Comment by Halo-Michael** [comment]
> Was that even with the #14249 change? It might've caused weird corruption if it ignored the assert.
> 
> -[Unknown]

Seems #14249 fixed that.
