### ISSUE TITLE
[FPS Changing?] Minna no Golf (Everybody Golf) Max FPS change from 30fps to 60fps.

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#14245]
### What happens?
Max FPS is changing from 30fps to 60fps when process of shot.
I can't judge that this one is issue or not or some seed of trouble.

[Why I open the issue?]
I have a feeling of strange point.
My PC (Win10/RADEON) & AndroidTablet (MediaPad M5 Lite Kirin710/Android9.0) is not smooth work the game on OpenGL.
It's very goes down  the fps at process of shot.
But, It will not worry other scene on Win10.
MediaPad has a little lag.

Win10 is working smooth on Vulkan. 
Maybe MediaPad is not enough spec for Vulkan.
But,The fps change same timing Vulkan too.
(It difficult to find because it will work smooth on vulkan.)

Is this normaly?

Log is here. https://gist.github.com/nassau-tk/632b70e8c93a3936bbbab3109a6c344b

And, Please see the fps in the movie.
(Windows10/Ryzen/RADEON/OpenGL)
https://user-images.githubusercontent.com/48179091/109660172-e6fe9480-7bab-11eb-9831-6b9c1a3a3037.mp4

### What *should* happen?
Please judge this.

### Please test newest version in https://buildbot.orphis.net/ppsspp/

PPSSPP Ver.：1.11.2-273
OS：Windows10（64-bit）Japanese
CPU：Ryzen7 3800X（8-core）
GPU：RADEON RADEON RX5700XT
Resolution：2560×1440
RAM：32GB

PPSSPP Ver.：1.11.2-273
OS：Android 9.0 Media Pad M5 Lite 8
CPU：Kirin710
GPU：Mali-G51 MP4
Resolution：1920x1200
RAM：3GB

**Comment by unknownbrackets** [comment]
This is the way the game works.  While you're shooting, it takes a screenshot of the scene, then draws it and some UI over the top of it.  It renders this at 60 FPS, even though not much else is moving.

The performance issue is as described here:
https://github.com/hrydgard/ppsspp/issues/12355#issuecomment-602156987

It's not actually from the FPS, but from how it's drawing this screenshot of the scene.

-[Unknown]

**Comment by nassau-tk** [comment]
In other words, are you saying that FPS doesn't fall because of this?

**Comment by hrydgard** [comment]
It slows down for you because the game is rendering the captured image in a very inefficient way. Not much that can be done, except possibly some awful game specific hack.

**Comment by nassau-tk** [comment]
Oh, I understood it!!
This one should close!!
