### ISSUE TITLE
Boku no natsuyasumi (UCJS10038) rendering problem

### ISSUE THREAD

**Issue by Jefelin** [hrydgard/ppsspp#14259]
### What happens?

The game isn't being rendered right, rendered resolution is set to x5 but the game has still the same resolution.

### What *should* happen?

The game should improve render right the 3D models to up the x1 original

### Rendering backend used (Direct3D 9, Direct3D 11, Vulkan, OpenGL)

No matter which one you choose, they all work the same 

### LINKS

https://forums.ppsspp.org/showthread.php?tid=5634
https://puu.sh/dPW5F/1a0f170ed6.png

**Comment by hrydgard** [comment]
Maybe the game just doesn't have higher resolution graphics, and only uses bitmaps? Are there any polygon graphics? It's hard to tell from the screenshot.

**Comment by hrydgard** [comment]
Could you take a GE frame dump that we can analyze, of a scene where higher resolution would be expected? See https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

**Comment by LunaMoo** [comment]
This is a PSOne port which uses similar technique to Test Drive Unlimited, to stretch and fit the image on the PSP screen. Althrough most of it's graphics are just prerendered images to begin with and would not benefit from higher render res, pretty much this game is kind of like FFVII in the matter that some basic polygon characters are walking over pre-rendered backgrounds.

**Comment by hrydgard** [comment]
Oh, if it's similar to TDU, it might fixable with compat.ini settings IntraVRAMBlockTransferAllowCreateFB or BlockTransferAllowCreateFB .

**Comment by LunaMoo** [comment]
Yeah I was just testing it, the game seems to have one minor probably block transfer glitch when entering desk(menu) and going through some options then going back which glitches the picture on a desk(made of in-game screenshot), but it seems to happen with as well as without this hack, so I'll open a PR adding those games to compat.ini.
