### ISSUE TITLE
GTA: Vice City Stories broken in Vulkan on Adreno 630

### ISSUE THREAD

**Issue by d00maz** [hrydgard/ppsspp#14269]
![Screenshot_2021-03-06-16-32-54-787_org ppsspp ppsspp](https://user-images.githubusercontent.com/1444582/110210376-0f330f80-7e9a-11eb-86ab-c8d0e55b1408.jpg)
![Screenshot_2021-03-06-16-28-08-268_org ppsspp ppsspp](https://user-images.githubusercontent.com/1444582/110210381-16f2b400-7e9a-11eb-8110-46ae43b7d160.jpg)
![Screenshot_2021-03-06-16-32-41-212_org ppsspp ppsspp](https://user-images.githubusercontent.com/1444582/110210384-1eb25880-7e9a-11eb-9826-488bf316b00e.jpg)
![Screenshot_2021-03-06-16-32-47-903_org ppsspp ppsspp](https://user-images.githubusercontent.com/1444582/110210388-283bc080-7e9a-11eb-80ff-9c0b46c9a2bb.jpg)

Android 10 845 snapdragon,1.11.3 works fine,latest dev build v1.11.2-299-g71707b510 has this issue

Supposed to look like this 
![Screenshot_2021-03-06-16-38-36-724_org ppsspp ppsspp](https://user-images.githubusercontent.com/1444582/110210464-8072c280-7e9a-11eb-8ef6-5ea915da5a59.jpg)

**Comment by crazyrexz** [comment]
try opengl, vulkan causing issues on some game, like pursuit force was like this on vulkan

**Comment by d00maz** [comment]
Its a new bug introduced in the git version.

**Comment by hrydgard** [comment]
Can you try a few slightly older builds to see more precisely when this started to happen?

**Comment by d00maz** [comment]
At v1.11.2-228-ge12888844 it starts to crash and doesnt load at all and continues down to v1.11.2-85-g19bd943ad,havent tested more yet.

**Comment by hrydgard** [comment]
Yeah, the game is indeed completely busted on my Pocophone F1.

Something has broken badly in Vulkan, likely the glslang upgrade triggered a driver bug, or something like that.

Getting lots of `03-07 23:21:43.693 17444 17611 E PPSSPP  : [G3D] Failed creating graphics pipeline! result='VK_INCOMPLETE'`

**Comment by hrydgard** [comment]
Bisected this, went pretty smoothly. The culprit is:

```
bf6efd0316d89bbe7e70c8581cf0b707d0a4af38 is the first bad commit
commit bf6efd0316d89bbe7e70c8581cf0b707d0a4af38
Author: John Kessenich <cepheus@frii.com>
Date:   Fri Jun 26 09:05:31 2020 -0600

    SPV: Fix #2293: keep relaxed precision on arg passed to relaxed param

    When arguments are copied to make space for a writable formal parameter,
    and the formal parameter is relaxed precision, make the copy also
    relaxed precision.

 SPIRV/GlslangToSpv.cpp                          |  2 +
 Test/baseResults/spv.forwardFun.frag.out        |  1 +
 Test/baseResults/spv.noDeadDecorations.vert.out |  1 +
 Test/baseResults/spv.precisionArgs.frag.out     | 91 +++++++++++++++++--------
 Test/baseResults/spv.switch.frag.out            |  6 ++
 Test/spv.precisionArgs.frag                     |  8 ++-
 6 files changed, 77 insertions(+), 32 deletions(-)

```

**Comment by hrydgard** [comment]
I tried to revert just that commit, but the code has changed drastically since then, so it's not really possible to do a straight revert. Need to figure out what actually went wrong here..

**Comment by hrydgard** [comment]
Removing the following line from the Vulkan fragment shader preamble in Common/GPU/ShaderWriter.cpp fixes it:

```"precision lowp float;\n"```

So it does seem to be some kind of linker precision mismatching, though logging the shaders, the GLSL looks fine...

**Comment by hrydgard** [comment]
This restored the behavior in glslang master, although it doesn't seem right:

```
diff --git a/SPIRV/GlslangToSpv.cpp b/SPIRV/GlslangToSpv.cpp
index 28a1ffed..2bcebe55 100644
--- a/SPIRV/GlslangToSpv.cpp
+++ b/SPIRV/GlslangToSpv.cpp
@@ -5538,7 +5538,7 @@ spv::Id TGlslangToSpvTraverser::handleUserFunctionCall(const glslang::TIntermAgg
             ++lValueCount;
         } else if (writableParam(qualifiers[a])) {
             // need space to hold the copy
-            arg = builder.createVariable(function->getParamPrecision(a), spv::StorageClassFunction,
+            arg = builder.createVariable(spv::NoPrecision, spv::StorageClassFunction,
                 builder.getContainedTypeId(function->getParamType(a)), "param");
             if (qualifiers[a] == glslang::EvqIn || qualifiers[a] == glslang::EvqInOut) {
                 // need to copy the input into output space
```

**Comment by hrydgard** [comment]
Please try again on a build after the #14273 merge.

**Comment by d00maz** [comment]
Got it,thanks,ill try the build when the fix gets implemented and report back.

**Comment by hrydgard** [comment]
Builds with the fix are available now at https://buildbot.orphis.net/ppsspp/

**Comment by d00maz** [comment]
Yeah,poco f1 works now,thanks for the fix hrydgard.
