### ISSUE TITLE
[Windows/Android][InvalidMemoryAccess] Dragon Ball Z Shin Budokai (ULJS00049)

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#14267]
### What happens?
This game will happen invalid memory access error.
![image](https://user-images.githubusercontent.com/48179091/110147986-9e4f1180-7e1f-11eb-948e-5a8041148de5.png)

Log is here.
"If stay opening menu screen then appear red code."
https://gist.github.com/nassau-tk/3d4e7e35edd09e09f03773a555883e24
[Red code]
![image](https://user-images.githubusercontent.com/48179091/110146964-80cd7800-7e1e-11eb-8a0d-6829c5385676.png)

"If select and start playing game screen."

https://gist.github.com/nassau-tk/a99ead85f1477c3a68f2c9cd8ff113a8
[Red code]
![image](https://user-images.githubusercontent.com/48179091/110147413-fa656600-7e1e-11eb-8d03-241d419e5cab.png)

https://gist.github.com/nassau-tk/3aa846692b4ce4e9ade7eb4c3d88c182
[Red code]
![image](https://user-images.githubusercontent.com/48179091/110146386-d9504580-7e1d-11eb-845e-79226c49874f.png)
![image](https://user-images.githubusercontent.com/48179091/110146407-e10fea00-7e1d-11eb-9f10-6373d2f60d86.png)

**Comment by ANR2ME** [comment]
And the last working version? :)

**Comment by nassau-tk** [comment]
Um...
I can't find it still now.
I tested these ver. but l couldn't got it.

1.11.2
1.11.1
1.11
1.10.3

And, I want sleep....
See you later...zzZ

**Comment by ANR2ME** [comment]
wow not even 1.10.3 worked.. O.o

**Comment by MojoJojoDojo** [comment]
ULJS00049 ... thats the Japanese version of the game...
The European and USA versions work alright but I didnt try beyond stable build 1.11 etc

**Comment by Panderner** [comment]
Japanese version (ULJS00049) works fine for me. It doesn't crash.

**Comment by nassau-tk** [comment]
@Panderner 

OK!
I will check CRC later.

**Comment by Panderner** [comment]
Note: the disc CRC for japanese version of this game is F646B1E9

**Comment by nassau-tk** [comment]
Oh....It's so sorry everyone!!

My iso was corrupt!!

Close!!
