### ISSUE TITLE
Field Commander blue screen when skipping the first video

### ISSUE THREAD

**Issue by ANR2ME** [hrydgard/ppsspp#14266]
I saw someone asking about this game at reddit, so i gave it a try today.

### What happens?
Apparently if i skipped the first (S.O.E) video right after launching the game, it will get blue screen.
![image](https://user-images.githubusercontent.com/7974720/110116753-86a96600-7dea-11eb-805c-c65a1b56882e.png)
![image](https://user-images.githubusercontent.com/7974720/110116696-709ba580-7dea-11eb-9112-00c3634c4c10.png)

Going to Campaign will also gets blue screen.
![image](https://user-images.githubusercontent.com/7974720/110116924-ca9c6b00-7dea-11eb-8c32-b23480039f93.png)
![image](https://user-images.githubusercontent.com/7974720/110116976-da1bb400-7dea-11eb-9e57-1e77e9fe503d.png)

PS: Adhoc multiplayer seems to work fine, probably because it doesn't have intro video.

### What *should* happen?
Worked properly

### Please test newest version in https://buildbot.orphis.net/ppsspp/

Tested with v1.11.2-299-g71707b510

**Comment by Panderner** [comment]
Duplicate of #10209

**Comment by ANR2ME** [comment]
Ah it was an old bug, i'll close this one then
