### ISSUE TITLE
Error when building for UWP: HLSL files missing

### ISSUE THREAD

**Issue by Nun-z** [hrydgard/ppsspp#14263]
### What happens?

When attempting to build the PPSSPP_UWP.sln solution for UWP Gold x64, the following fatal errors are displayed:

##[error]c1xx(0,0):` Error C1083: Cannot open source file: '..\..\ext\glslang\glslang\HLSL\hlslAttributes.cpp': No such file or directory
##[error]c1xx(0,0): Error C1083: Cannot open source file: '..\..\ext\glslang\glslang\HLSL\hlslGrammar.cpp': No such file or directory
##[error]c1xx(0,0): Error C1083: Cannot open source file: '..\..\ext\glslang\glslang\HLSL\hlslOpMap.cpp': No such file or directory
##[error]c1xx(0,0): Error C1083: Cannot open source file: '..\..\ext\glslang\glslang\HLSL\hlslParseables.cpp': No such file or directory
##[error]c1xx(0,0): Error C1083: Cannot open source file: '..\..\ext\glslang\glslang\HLSL\hlslParseHelper.cpp': No such file or directory
##[error]c1xx(0,0): Error C1083: Cannot open source file: '..\..\ext\glslang\glslang\HLSL\hlslScanContext.cpp': No such file or directory
##[error]c1xx(0,0): Error C1083: Cannot open source file: '..\..\ext\glslang\glslang\HLSL\hlslTokenStream.cpp': No such file or directory

### What *should* happen?

Msbuild.exe should be able to compile the source code without producing errors.

### Please test newest version in https://buildbot.orphis.net/ppsspp/

I'm building this in a Windows VM for an Azure Pipeline.

**Comment by Florin9doi** [comment]
git submodule update --init --recursive

**Comment by unknownbrackets** [comment]
Yeah, this is definitely caused by using the old submodule.  We're building UWP with each commit, ARM64 and AMD64, via GitHub Actions now so it definitely builds.

-[Unknown]

**Comment by Nun-z** [comment]
My bad.  Thanks.
