### ISSUE TITLE
Hot Shots Golf: Open Tee 2 - crash on "Leaving"

### ISSUE THREAD

**Issue by telanus** [hrydgard/ppsspp#14270]
### What happens?
Crashes after choosing Leaving for the course. There is a blue info screen that comes up, and when it's suppose to go to the course it crashes. Tried it with Challenge, Stroke and Practice Mode

### What *should* happen?
It should not crash

### Please test newest version in https://buildbot.orphis.net/ppsspp/
**PPSSPP Version**: v1.11.2-299-g71707b510

**Model Phone**: Samsung Galaxy A2 Core 
**OS**: Android 8.0 Oreo (Go edition)
**Chipset**:  Exynos 7870 Octa (14 nm)
**CPU**: Octa-core 1.6 GHz Cortex-A53
**GPU**: Mali-T830 MP1

**Comment by ANR2ME** [comment]
Do you remember the last working version?

**Comment by telanus** [comment]
> Do you remember the last working version?

I know it was working with 1.9.4/5, think it ran with 1.10.3. But will have to test that, once I get free time again

**Comment by sum2012** [comment]
Test no problem on windows and black shark 3 phone.
90% Samsung issue,

**Comment by unknownbrackets** [comment]
Does it show a blue screen now in the latest git builds?  If yes, a screenshot of that may help.

If you're able to get an adb logcat, that might help too.
https://github.com/hrydgard/ppsspp/wiki/How-to-get-an-adb-logcat-from-a-PC

-[Unknown]

**Comment by telanus** [comment]
Got a new Samsung A02 with Android 10, tested again with the latest git, same crash. Then tested with RetroArch and it crashes there also, on the same spot.

Enabled logging in RA and got this in the log file: 

SYSTEM] (ArmEmitter.cpp:VMOV_neon:1674) Critical: [(Size & (I_UNSIGNED | I_SIGNED | F_32)) != 0] Must specify I_SIGNED or I_UNSIGNED in VMOV, unless F_32

So not sure if that's the bug that's stopping the game from working

**Comment by Gamemulatorer** [comment]
@telanus savetstate of the crash area?

**Comment by telanus** [comment]
[broken.zip](https://github.com/hrydgard/ppsspp/files/7189745/broken.zip)

It crashes right after this. If I load the save it crashes without displaying anything

**Comment by Gamemulatorer** [comment]
> [broken.zip](https://github.com/hrydgard/ppsspp/files/7189745/broken.zip)
> 
> It crashes right after this. If I load the save it crashes without displaying anything

Step to reproduce the crash?

**Comment by telanus** [comment]
For me, I start the game create/load user, then press x right thru to where you leave the clubhouse to go to the course, this screen will come up 

![UCUS98693_1 00_0](https://user-images.githubusercontent.com/19357986/133886818-90436e42-b6bc-4fac-8b2e-e50c4a7ee002.jpg)

Then when this screen is suppose to be replaced with you getting to the course, it crashes

**Comment by Gamemulatorer** [comment]
Can't reproduce.

https://user-images.githubusercontent.com/37603562/133888327-79fd4b23-bb2f-451b-8d5c-25539096416d.mp4

**Comment by hrydgard** [comment]
That is a very curious emitter error, that should be investigated.

However, if the game works for others, you might simply have a broken ISO file. Can you check the CRC?

**Comment by telanus** [comment]
> That is a very curious emitter error, that should be investigated.
> 
> However, if the game works for others, you might simply have a broken ISO file. Can you check the CRC?

Hi
I'm using this dump: http://redump.org/disc/21033/, my hashes is the same as this entry in redump. Also tested with Minna no Golf Portable 2 and it also display the same error as the English version

The iso works on my Linux machine.

**Comment by hrydgard** [comment]
Ok, thanks for reporting that. Might be some bug in PPSSPP that's 32-bit ARM specific then (I deduce your device is running 32-bit PPSSPP from the emitter error)...

**Comment by Gamemulatorer** [comment]
I can reproduce this crash on my Excite Prime phone mt6592 mali-450 gpu

```

[09-18 22:41:23.353 16244:16244 I/PPSSPPNativeActivity]
Setting shuttingDown = true and calling Finish

[09-18 22:41:23.406 16244:16244 I/PPSSPPNativeActivity]
onPause

[09-18 22:41:23.418 16244:16291 I/DefaultContextFactory]
eglDestroyContext = 1873, this = org.ppsspp.ppsspp.NativeGLView{301f6bc2 V.E..... ........ 0,0-1280,720}

[09-18 22:41:23.425 16244:16244 I/PPSSPPNativeActivity]
onPause completed

[09-18 22:41:23.540 16244:16244 D/PPSSPPSizeManager]
checkDisplayMeasurements: checking now

[09-18 22:41:23.669 16244:16244 I/PPSSPPNativeActivity]
onStop - do nothing special

[09-18 22:41:23.671 16244:16244 I/PPSSPPNativeActivity]
onDestroy

[09-18 22:41:24.324 16244:16244 I/PPSSPP]
EARLY: NativeApp.shutdown() -- end

[09-18 22:41:41.742 16534:16534 W/linker]
libppsspp_jni.so: unused DT entry: type 0x6ffffef5 arg 0x1acabc

[09-18 22:41:41.742 16534:16534 W/linker]
libppsspp_jni.so: unused DT entry: type 0x6ffffffe arg 0x20b018

[09-18 22:41:41.742 16534:16534 W/linker]
libppsspp_jni.so: unused DT entry: type 0x6fffffff arg 0x3

[09-18 22:41:41.846 16534:16534 I/PPSSPP]
EARLY: JNI_OnLoad

[09-18 22:41:41.857 16534:16534 E/PpssppActivity]
Got ACTION_VIEW without a valid uri, trying param

[09-18 22:41:41.857 16534:16534 E/PpssppActivity]
Shortcut missing parameter!

```

**Comment by Gamemulatorer** [comment]
Doesn't crash on my ancient phone using IR Interpreter.
![Screenshot_2021-09-18-23-00-04](https://user-images.githubusercontent.com/37603562/133893246-d2c8db15-5836-4121-abe1-8e641cb09924.png)
[logcat_09-18-2021_23-00-35.txt](https://github.com/hrydgard/ppsspp/files/7190132/logcat_09-18-2021_23-00-35.txt)

**Comment by hrydgard** [comment]
Ok, I think we can pretty safely conclude that we have a problem in the ARM32 JIT then.

**Comment by unknownbrackets** [comment]
Can you try this again in recent git builds?  I think this was just a problem with the assert.  In much older versions, these asserts were essentially ignored on some platforms.  I'm hoping the game will run fine now.

-[Unknown]

**Comment by telanus** [comment]
> Can you try this again in recent git builds? I think this was just a problem with the assert. In much older versions, these asserts were essentially ignored on some platforms. I'm hoping the game will run fine now.
> 
> -[Unknwn]
I was using ppsspp-v1.11.3-1427-gd944c254c-android.apk yesterday for my test, but will download the latest git
¹

**Comment by Gamemulatorer** [comment]
Confirm fixed via https://github.com/hrydgard/ppsspp/pull/14879

**Comment by Gamemulatorer** [comment]
Remaining issue portrait missing graphics of this game is related to https://github.com/hrydgard/ppsspp/issues/4179

**Comment by telanus** [comment]
> Confirm fixed via #14879

Can confirm that fixed my error

**Comment by ResurrectionRedmi9** [comment]
v1.12.0 milestone

**Comment by hrydgard** [comment]
@ResurrectionRedmi9 thanks.
