### ISSUE TITLE
[DX11] Shattered Memories - mirror and flashlight interacting crashes PPSSPP

### ISSUE THREAD

**Issue by themanwiththeplan911** [hrydgard/ppsspp#14281]
### What happens?
PPSSPP crashes when pointing a flashlight to a few specific mirrors using the DX11 renderer.

### What *should* happen?
Well, it shouldn't crash. What's funny is Vulkan and OGL not only do not crash but partially fix this specific mirror and it actually works when the flashlight is on, doesn't fix all of the mirrors though.
Vulkan:
![gif](https://user-images.githubusercontent.com/75482550/110778733-67d42500-826b-11eb-95ae-4c0e3e4e84d0.gif)
DX11:
![jif](https://user-images.githubusercontent.com/75482550/110781095-23965400-826e-11eb-96e0-7d3cb64d62ac.gif)

### Please test newest version in https://buildbot.orphis.net/ppsspp/
Ryzen CPU
Nvidia Pascal GPU
W10
g98f593fd5

**Comment by unknownbrackets** [comment]
If you make a GE frame dump (https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump) while pointing at the mirror in Vulkan, and then load that same GE frame dump file after switching to Direct3D 11 - does that also crash?

If yes, that file would be really useful.  If not, it probably won't be, but it might still be helpful to post it here.

-[Unknown]

**Comment by RIKLAVIEGASINTRODUCTION** [comment]
I think this can be closed doesn't crash on DX11 anymore:
![Untitled](https://user-images.githubusercontent.com/92535412/208418605-2fc6ac76-35bf-451e-afb7-eaef65fc70c2.png)

**Comment by unknownbrackets** [comment]
Do the mirrors look more correct too?  There were several fixes made for these games.

Thanks for confirming.

-[Unknown]
