### ISSUE TITLE
(Feature Request) Original PSP XMB for nostalgia purposes

### ISSUE THREAD

**Issue by Back2Life888** [hrydgard/ppsspp#14286]
Yeah, yeah.. I know about the copyright but RPCS3 did the same thing with the PS3 XMB.. That was like a whole year ago and Sony had a lot of time of copyright striking RPCS3 but they did nothing about it.. And probably they wouldn't care if PPSSPP would do the same thing.. RPCS3 also even included the actual XMB file but it is very unstable.. It crashes a lot and stuff.. So basically, I want the XMB to be runnable and to be included in PPSSPP.. I'm pretty sure all of us wouldn't get in trouble since RPCS3 still hasn't been noticed by it..

**Comment by unknownbrackets** [comment]
If you want to build it, perhaps it'll be considered as an addition.  However, the XMB really doesn't lend itself to the range of devices PPSSPP is run on - especially touch controlled devices.

If we tried to run the original XMB in PPSSPP, I guarantee it would also crash a lot and stuff.  The XMB uses a huge library of internal features of the PSP firmware that we don't emulate - it's a silly amount of work for a smally nostalgia trip that can mostly be satisfied using YouTube.

That said, if you're really excited to devote countless hours of your life to getting the XMB working - all the power to you.  I'm sure a handful of people will be really happy and spend about 5 minutes looking at it before going back to better UI, and those people will surely thank you.

-[Unknown]

**Comment by dobkun** [comment]
>  for a smally nostalgia trip that can mostly be satisfied using YouTube.
Yeah, especially the inner system software workings.
They can be seen on YouTube, right?

**Comment by hrydgard** [comment]
The fact remains that getting the original XMB to run is quite a large amount of work that would be better spent on other things.

And the current UI is just fine, and better than the XMB on touch screens.

**Comment by dobkun** [comment]
> And the current UI is just fine, and better than the XMB on touch screens.
I have meant an ability to boot into VSH from the menu, not VSH as a main menu
vita3k already implements a similar feature, and LiveArea definitely won't replace their main menu.

**Comment by hrydgard** [comment]
Again, it's not a priority. You're very welcome to help implement it if you like.

**Comment by dobkun** [comment]
alright, here you win.
but at least implement an ability to import system sounds and fonts from a firmware file, so it can be done using only the emulator, without any other tools.
