### ISSUE TITLE
PPSSPP 1.11.3 - Gran Turismo Fast Memory Huge FPS Drop

### ISSUE THREAD

**Issue by Back2Life888** [hrydgard/ppsspp#14285]
### What happens?
![hell](https://user-images.githubusercontent.com/76780043/111025945-803a7000-8422-11eb-9b4d-bbee1ddda77b.png)

Here is the image.. As you can see, there are no text that loads up.. And it also lags very extremely.. Disabling Fast Memory fixes that lag but the text still doesn't load.. I tried every settings but the text won't show up.. I think it's a Vulkan problem since I never change the renderer to anything other than Vulkan.. If I do change it to other than Vulkan, Gran Turismo will be extremely laggy.. Some text do load ingame but the menu text doesn't load at all..

Here is the list of texts that appear:

- The 3, 2, 1, and START text
- Some texts on the in-game dashboard (Time, Week, Car Speed, etc.)
- The time for Gold, Silver, or Bronze (Applies to license tests only)

### What *should* happen?

Text should appear.. Previous versions can load up Gran Turismo texts ***with any kind of settings*** so it should be clear when I say "Text should appear" Lol.. But Overall, the game plays fine in 60 FPS with Fast Memory disabled.. It's just hard to navigate.. A lot of games have problems with Fast Memory enabled like God of War but that's another story..

**Comment by Panderner** [comment]
@Back2Life888 did you disabled lazy texture caching option?

**Comment by Back2Life888** [comment]
Lazy texture caching doesn't do anything.. Disabled or enabled, text is still nothing..

**Comment by Panderner** [comment]
How's the older versions worked?

**Comment by Back2Life888** [comment]
![HFTHSRJG](https://user-images.githubusercontent.com/76780043/111028762-a61c4080-8433-11eb-8147-66b02f82f877.PNG)

Like this

**Comment by Panderner** [comment]
Did you installed real PSP fonts?

**Comment by Back2Life888** [comment]
There is no such thing as "real PSP" in PPSSPP.. PPSSPP is for emulating PSP games.. Not a PSP.. So I can't install PSP fonts.. Its not like that..

**Comment by Panderner** [comment]
> There is no such thing as "real PSP" in PPSSPP.. PPSSPP is for emulating PSP games.. Not a PSP.. So I can't install PSP fonts.. Its not like that..

It's important for some games that requires real PSP fonts to render properly like Jeanne d'Arc.
You can install real PSP fonts by putting /PSP/flash0 file.

**Comment by Back2Life888** [comment]
The thing is how do I install it??

**Comment by Back2Life888** [comment]
Nevermind, works again BUT There is a lag when Fast Memory is enabled so.. Don't close this as I mentioned the Fast Memory lag..

**Comment by hrydgard** [comment]
fast memory should not cause lag, that's very unexpected... 

Also I don't think this game uses the built-in PSP fonts. Besides, thanks to work by nassau-tk, our font problems are much smaller than they used to be.

**Comment by Back2Life888** [comment]
enabling Fast Memory will make Gran Turismo a f***ing slideshow lol

**Comment by hrydgard** [comment]
That is very strange to hear and is not supposed to happen at all.

**Comment by hrydgard** [comment]
How is it now in the latest build from https://buildbot.orphis.net/ppsspp/ ?

**Comment by nassau-tk** [comment]
>fast memory should not cause lag, that's very unexpected...
>
>Also I don't think this game uses the built-in PSP fonts. Besides, thanks to work by nassau-tk, our font problems are much smaller than they used to be.

@hrydgard 

NoNoNo~~!
Gran Turismo use the PGF fonts at many scene.
If you rename to other name the PPSSPP font folder then GT can't boot.
It make happen Invalid memory access error.

Probably....
If system language setting to Japanese then it will use jpn0.pgf & ltn4.
If system language setting to English then it will use ltn0.pgf & ltn4. 

And, It will affected at lazy texture caching.


I tested on ｖ1.12.2-333 on select "English Language" at PPSSPP on Windows10(64-bit) with Vulkan.
It appear the text.
![image](https://user-images.githubusercontent.com/48179091/111056459-4ae55f00-84c2-11eb-8072-f0cc1ebd0814.png)
![image](https://user-images.githubusercontent.com/48179091/111056490-7ff1b180-84c2-11eb-9920-82478c290cc3.png)

And, I tested on v1.11.3 (Stable) on Windows10(64-bit) with Vulkan.
![image](https://user-images.githubusercontent.com/48179091/111056636-e4614080-84c3-11eb-961f-31595b39b7cb.png)

It appear the text too.

for reference.

(Oops... ltn's side space is too nalow...)

**Comment by nassau-tk** [comment]
@Back2Life888 

Did you try to latest build?
And, Please tell us your hardware.(PC?orAndroid?or iPhone....etc)

**Comment by Back2Life888** [comment]
Yes I tried the latest build from ppsspp.org and turns out that didn't have the PSP font files from the directory "PPSSPP/assets/flash0".. flash0 is just empty with no files in it.. When I added the files back from the old PPSSPP versions that has the PSP fonts installed, the text reappeared.. But that doesn't stop the lag from Fast Memory.. I literally set the graphics to the lowest and still lags.. My hardware is a PC.. And nassau-tk, why TF is the Mercedes cars so expensive??

**Comment by nassau-tk** [comment]
@Back2Life888 

I tested extracting 3 files of latest PPSSPP.

1. v1.11.3 of stable "zip file".
2. v1.11.3 of stable "installer file."
3. v1.11.3-381 of Git build.(Win 64-bit & 32-bit both)

These files included font files. 
jpn0.pgf & kr0.pgf & ltn0~15.pgf all.
(PPSSPP>assets>flash0>font)
Why your extracted file is not included font files?
I don't know...

>why TF is the Mercedes cars so expensive??

What does it mean "TF"???

**Comment by Back2Life888** [comment]
TF means "the f**k"

**Comment by nassau-tk** [comment]
@hrydgard 
I tested delete all pgf files on v1.11.3(Installer ver. default).
And booted the GT.
The result is below.
The game is start up normaly but not appear any text and the lagging happen when move to menu screen.

The log is here.
https://gist.github.com/nassau-tk/345bbc6c69f505ad41794e0d56b7ff19


@Back2Life888 
Wao...I learned new word.

**Comment by nassau-tk** [comment]
@hrydgard 
WHat!?
Why can boot the game that I deleted font files!?
Git ver is can't boot it.
Stable ver is can boot! why!?

**Comment by Back2Life888** [comment]
The Sauber C9 cost 3,000,000 but in the Japan release, its 300,000,000. That's what I want to know the reason. Why the hell all cars in the GTPSP release is super expensive?

**Comment by nassau-tk** [comment]
Oh...sorry I don't know the reason.:sweat:

**Comment by unknownbrackets** [comment]
Is this still a problem in the latest git build?

Can you try disabling fast memory and enabling "show debug statistics" (end of graphics settings)?  This will show some text on screen that says what's slow or fast, and may help us narrow down what's taking the time.

-[Unknown]

**Comment by nassau-tk** [comment]
On my case.
V1.11.3-1094
Intel Core i7 4770K
RAM 16GB
GeForce 750ti
Option : Disabling fast memory / Window Size x2


[Vulkan]
![image](https://user-images.githubusercontent.com/48179091/128812955-1913471d-3f27-48ee-8d96-1ff114980744.png)

[OpenGL]
![image](https://user-images.githubusercontent.com/48179091/128813003-a15223dd-1bd7-4c0a-a1a1-8a3f92286673.png)

for reference.

**Comment by nassau-tk** [comment]
By the way....
I'm posting this issue from before.
https://github.com/hrydgard/ppsspp/issues/13460
Maybe, It will happend by some RADEON + OpenGL.

And.....
@Back2Life888 said only "PC".
So,We don't know his machine spec.
What's kind of CPU? What's kind of GPU? What's kind of graphics backend?
Probably, We need his specifacation more.

**Comment by Back2Life888** [comment]
> @Back2Life888 said only "PC".
> So,We don't know his machine spec.
> What's kind of CPU? What's kind of GPU? What's kind of graphics backend?
> Probably, We need his specifacation more.

My CPU is a i7-6700 and my GPU is GTX 1650. I was using Vulkan at the time.

**Comment by nassau-tk** [comment]
@unknownbrackets 
Probably, I think that his machine specification has not problem.

@Back2Life888 
If your issue still happen now then let's try the test that Unknowbrackets said it.

1. Install latest buid. (v1.11.3-1094)

2. Turn off "Fast memory (unstable)".
![image](https://user-images.githubusercontent.com/48179091/128851153-bc4f1ec7-822e-4d71-aefe-d74bfec1fce5.png)

3. Turn on "Show debug statistics".
![image](https://user-images.githubusercontent.com/48179091/128851320-a9f5a2d0-4145-4032-9ff8-749cc4b02a2f.png)

And, Start Gran Tourismo and get screenshot.
![image](https://user-images.githubusercontent.com/48179091/128851805-da7ebada-3409-480e-a7ba-c5c2db1e5c53.png)

NOTICE: This screenshot's spec is below.
Ryzen7 3800X
RADEON RX5700XT
RAM32GB

**Comment by Back2Life888** [comment]
Weird it isn't happening anymore. Oh well its fixed.

**Comment by nassau-tk** [comment]
> Weird it isn't happening anymore. Oh well its fixed.

Is it means not happen the issue when "Fast memory (unstable)" On & Off both?

**Comment by Back2Life888** [comment]
> > Weird it isn't happening anymore. Oh well its fixed.
> 
> Is it means not happen the issue when "Fast memory (unstable)" On & Off both?

Yeah the lag is gone.
