### ISSUE TITLE
Secret Agent Clank: Garbage characters

### ISSUE THREAD

**Issue by Anuskuss** [hrydgard/ppsspp#14297]
### What happens?
In the save dialog, the game uses `53 65 63 72 65 74 20 41 67 65 6E 74 20 43 6C 61 6E 6B E2 84 A2 C0 80 45 4E 54 52` as the title, which should be rendered as `Secret Agent Clank™` but it shows `Secret Agent Clank™��ENTR` instead.

### What *should* happen?
PPSSPP should treat `C0 80` as `NUL` and terminate the string.

#### What PPSSPP version (standalone/official), and did it work before?
1.11.3

#### Which game or games?
Secret Agent Clank (all variants)

#### Checklist
 - [x] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [x] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [x] Try resetting settings or older versions and include if the issue is related.
 - [ ] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment]
Hmm.. may be the title buffer is fully filled and it doesn't have enough space to put null to terminate the string?

**Comment by unknownbrackets** [comment]
`C0 80` is definitely a questionable encoding of NUL, we should probably make a test to be sure.  In the worst case, this could actually be a bug in sceCcc and I'd rather fix it there if so.

Do saves created on PSPs include this in the SFO (i.e. from gamefaqs)?  Do PPSSPP created saves show as expected on PSPs?

I could see the utf-8 decoder in the PSP firmware treating this as a NUL, but still storing it in the SFO.  If yes, we should have the same behavior so we show PSP-created saves correctly.

-[Unknown]

**Comment by Anuskuss** [comment]
@unknownbrackets Grabbing a save from GameFAQs includes the same string so it's definitely not a PPSSPP bug. Creating a new game on my PSP displays it correctly (cut-off). Also even though `C0 80` is illegal (because it's longer than necessary), [it should be interpreted as `NUL`](https://dwheeler.com/secure-programs/Secure-Programs-HOWTO/character-encoding.html#UTF8-LEGAL-VALUES).

**Comment by Panderner** [comment]
Buzz!: Master Quiz also affected this issue
![IMG_20210316_120048](https://user-images.githubusercontent.com/37503397/111254157-6cc01c80-864f-11eb-80dd-10ffdd5a58a0.jpg)

**Comment by Anuskuss** [comment]
Not the same issue, but interesting nevertheless:
```
42 75 7A 7A 21 F0 82 84 A2 3A 20 4D 61 73 74 65 72 20 51 75 69 7A
B  u  z  z  !  � � � �  :     M  a  s  t  e  r     Q  u  i  z
```
™ in UTF-8 is `E2 84 A2` but it's `(F0) 82 84 A2` here. Maybe they mistyped it or it's some other encoding. What does it look like on a PSP?

**Comment by ANR2ME** [comment]
Probably just a different representation of the same symbol in 3-bytes and 4-bytes, just like Euro sign here https://en.wikipedia.org/wiki/UTF-8#Examples

>
>**Overlong encodings**
>
>In principle, it would be possible to inflate the number of bytes in an encoding by padding the code point with leading 0s. To encode the Euro sign € from the above example in four bytes instead of three, it could be padded with leading 0s until it was 21 bits long – `000 000010 000010 101100`, and encoded as `11110000 10000010 10000010 10101100` (or `F0 82 82 AC` in hexadecimal). This is called an overlong encoding.
>
>The standard specifies that the correct encoding of a code point uses only the minimum number of bytes required to hold the significant bits of the code point. Longer encodings are called overlong and are not valid UTF-8 representations of the code point. This rule maintains a one-to-one correspondence between code points and their valid encodings, so that there is a unique valid encoding for each code point. This ensures that string comparisons and searches are well-defined. 
>

**Comment by hrydgard** [comment]
Right, so illegal encodings according to the standard, but as we are an emulator and games are using them and the real PSP handles them, we should support them too indeed... Fun.

**Comment by hrydgard** [comment]
The ENTR thing is very curious. In the bottom left corner where it shows save data size after saving, it draws this string:

![image](https://user-images.githubusercontent.com/130929/111867090-2251df00-8972-11eb-9304-683a45df2834.png)

![image](https://user-images.githubusercontent.com/130929/111867093-2847c000-8972-11eb-82f4-e0c8e15c715b.png)

If I just re-encode the overlong encodings to short ones, 0xC0 0x80 (192 128) becomes a null, and we lose the lines about the date and size.

Maybe 0xC0 0x80 ENTR has a special meaning? Just removing those six characters fixes it, but it's kinda ...weird.

**Comment by ANR2ME** [comment]
Hmm.. may be `ENTR` translated to ASCII code 13 (CR) and combined with the next ASCII code 10 (LR) ?

**Comment by hrydgard** [comment]
Possible. But extremely odd! I've never seen string-encoded characters like that.

**Comment by ANR2ME** [comment]
Btw is the Date and Size information supposed to be printed together with the "Save" text? or it was supposed to be printed separately? (ie. using smaller font size)

**Comment by hrydgard** [comment]
It's printed together with the same font on the real PSP.

**Comment by unknownbrackets** [comment]
I'll try to do some testing later to see what it does with different encodings and if it consistently ignores the next 4 bytes after a NUL.  I could imagine it being a lot of different things.

It does seem likely based on the recent examples that it's an escape code to the PPGe drawing system...

-[Unknown]

**Comment by hrydgard** [comment]
Well, it's not called PPGe on the actual PSP, that's just how I named our corresponding thing :) but yeah.

**Comment by unknownbrackets** [comment]
Sorry, that's what I meant, the PSP's version of PPGe, whatever it is (but it may not even have a unified way...)

Some test results with MsgDialog specifically (not savedata):
 * MsgDialog interprets C0 80 as the end of string, even if more characters follow ENTR.
 * C0 A0 and C1 81 are also interpreted as end of string.
 * F0 82 84 A2 is supported and renders "™" without skipping any additional bytes.
 * F0 61 61 61 61 renders "_a", which is identical to the rendering of F0 A1 A1 A1 61.
 * F0 02 04 22 and F0 C2 C4 E2 each render "™" (i.e. identical to F0 82 84 A2.)
 * Non-printable chars (i.e. 0x01-0x1F, except 0x0A) are ignored, including 0x09.
 * F0 80 80 A1 61 renders "!a", i.e. the same as 21 61.
 * F5 80 80 A1 61 61 61 61 (or even more 61s) renders as "", while F4 80 80 A1 61 61 61 61 renders as "_a".
 * C2 B0 61 and C2 F0 61 both render as "°a".

Based on the above, MsgDialog seems to validate the first byte, and then simply mask 0x3F of all following bytes.  If the first byte is invalid, it terminates the string (or is ignored, if control code.)  Overlong encodings are treated naively and no escape sequences or special handling appears present.

It's like sceCcc simply works this same way.

Will do some testing of PARAM.SFO string display next in the savedata section.

-[Unknown]

**Comment by unknownbrackets** [comment]
TIL pressing X on savedata starts the game that made the savedata.  Not sure how I never knew this before.

SAVEDATA using Mana Khemia, just as an example, seems to follow the same rules as above.  The "\xC0\x80ENTR" sequence resulted in truncation.  The other bytes were treated as above, i.e the bits of continuation bytes outside 0x3F were ignored.

Do we know for sure that the data after ENTR (albeit useful) actually shows up on a PSP?

Thinking we just specifically nuke "\xC0\x80ENTR" and then normalize overlong encodings.  I suspect this is just a game bug that accidentally resulted in truncation on real PSPs and no one noticed.

-[Unknown]

**Comment by hrydgard** [comment]
@unknownbrackets Yes, the data does show up on the real PSP. Although potentially it might come from other fields in the structs that we miss?

**Comment by hrydgard** [comment]
![image](https://user-images.githubusercontent.com/130929/112798675-8b6ddc80-906d-11eb-867f-f8ef92088d93.png)

**Comment by unknownbrackets** [comment]
Ah, I missed that it was just the date.  That's a different field indeed, we just concatenated.

To be fair, I didn't try different firmware versions.  I also know that firmware does have some workarounds for game bugs in a few specific cases.  I think Xele02 posted a list of game IDs found in firmware once years ago... but it wasn't a long list iirc.

-[Unknown]

**Comment by Panderner** [comment]
Hmm save file issue for secret agent clank is fixed but Buzz: Master Quiz still not fixed.
