### ISSUE TITLE
(Linux/SDL) How to map keyboard keys to dpad diagonals?

### ISSUE THREAD

**Issue by clort81** [hrydgard/ppsspp#14305]
I built PPSSPPSDL for Maemo-Leste (linux) on Droid 4!   It's an OMAP4 device with powervr SGX 540 

'Trails' runs geat with with opengl-es2 with frameskip 1 and CPU ~ 150mhz!  Woo!

This and other games really need diagonal dpad though.  My thumb can mash down-diagonals by combining down and left|right.  This can't be done for up since the up key is one row up.

![d4_keyboard](https://user-images.githubusercontent.com/51511737/111822752-7ada9b00-88e4-11eb-9d23-a181468c06ad.jpg)

I'd like to map "." to PAD_BUTTON_UP | PAD_BUTTON_LEFT 
and "OK" (right_alt) to PAD_BUTTON_UP | PAD_BUTTON_RIGHT   

... to get up-diagonals.  In controls.ini, I don't see button mappings for diagonals, only:
 ```
[ControlMapping]
Up = 1-19,10-19
Down = 1-20,10-20
Left = 1-21,10-21
Right = 1-22,10-22
```
What modification would be needed to allow mapping keyboard keys to diagonals?
I'm' looking at KeyCodes.h and InputState.h and haven't figured out how to add this.

**Comment by LunaMoo** [comment]
No modifications are needed, you can map multiply keys to same PSP buttons, but you can also map same key to different PSP buttons, just map whatever you want to both up and right and a different one for up and left.

**Comment by clort81** [comment]
What then, is the string for UpLeft and UpRight under [ControlMapping] ?

**Comment by hrydgard** [comment]
No just add additional mappings to Up and to Right.

**Comment by clort81** [comment]
Thank you.  Trying this.

**Comment by hrydgard** [comment]
Uh, that shouldn't happen. Bizarre :( Gonna have to look into that

**Comment by clort81** [comment]
I also tried:
```
Up = 1-19,10-19,1-56,1-58
Down = 1-20,10-20
Left = 1-21,10-21,1-56
Right = 1-22,10-22,1-58
```

**Comment by clort81** [comment]
This works!!
```
[ControlMapping]
Up = 1-19,1-56,1-58
Down = 1-20
Left = 1-21,1-56
Right = 1-22,1-58
```

**Comment by LunaMoo** [comment]
Why did you even edited ini file instead of just using UI? You should know that, if you press the "+" near the PSP button, you can add new mapping without replacing one of the existing ones.

**Comment by clort81** [comment]
Did not know this, thanks.

**Comment by hrydgard** [comment]
corrupted linked list error is a sign of memory corruption and thus pretty serious. wonder how it could be related to this

**Comment by clort81** [comment]
Seems like a closed issue to me (?) Closing.
