### ISSUE TITLE
Cutscene lags when it starts

### ISSUE THREAD

**Issue by Alexuwu52** [hrydgard/ppsspp#14303]
As soon as a video starts, it lags, only during the start
I already tried to fix it by changing the settings several times, and that doesn't fix anything
Curiously, it is solved using a previous version, so it seems that the problem has to do with how the videos are played (with version 1.2 the videos play well, with their default configuration)

My laptop is an Acer Aspire Series 3 A315-51 Processor Intel i3 7020U 2.30GHz
4GB of RAM

The version of ppsspp that I was using when I noticed the error was the last one, 1.11.3 
The games that I know have this problem is Ben 10 Protector of Earth and Corpse Party
(although I really feel that this happens with any other game that has a pre-rendered video)

I was using Directx11 as a renderer (Although I repeat, it does not seem to be a problem with the configuration, rather it seems to be a problem related to how the videos are played)

#### Checklist
 - [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [X] Try resetting settings or older versions and include if the issue is related.
 - [X] Try changing graphics settings to determine if one causes the bug.
 - [ ] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment]
Version 1.2 to 1.11.3 is kinda wide, it would be nice if you can shorten the range to last working version as close as possible :)
Not even 1.10 worked fine? you can find all the version here https://buildbot.orphis.net/ppsspp/index.php?m=fulllist

**Comment by unknownbrackets** [comment]
Are you sure you're not using texture upscaling or any other non-default settings when seeing this?  Maybe it tries to upscale the first frame or two and then realizes it's a video.

-[Unknown]

**Comment by Alexuwu52** [comment]
I was using 0.11.3
The new developer version corrected the scenes, which is a bit weird, because it does not seem that they have modified anything related to how the scenes are played
Anyway, I'll close this because the problem disappeared
It seems that it was the program itself, because I tried again with 0.11.3, and the problem continued to occur

**Comment by unknownbrackets** [comment]
Ah, we made a change to better identify videos drawn as strips, so it might've been that.  Before, we'd try to upscale each strip except the first.  Now we identify them all as part of the video and do not upscale.

-[Unknown]
