### ISSUE TITLE
CWCheats broken by "Automatically fix duplicate event types"

### ISSUE THREAD

**Issue by LunaMoo** [hrydgard/ppsspp#14308]
Reverting 365d6d44c6e01f794e35edeb23067719128b559b causes cheats to work again.

**Comment by unknownbrackets** [comment]
Is this always or only when a save state has been loaded?  And if save states, does it happen for new save states or only ones created in a certain range?

If there were duplicated event type ids, this tries to recover but the previous state was corrupted.  So it might not bring back the cheat event type the same way (for example, if a non-cheat event type was accidentally triggering cheat callbacks, but being scheduled to trigger audio or something.)

-[Unknown]

**Comment by LunaMoo** [comment]
Oh yeah it's only for savestates and doesn't happen for new ones. Not sure what savestate versions this might affect as I had a some critical covid cases in close family from some time and probably wasn't keeping up to date.

 Should I just close this? I'm not even sure if the savestates I used are from official version, plus if it only affects those old savestates it's not much of an issue, wouldn't use old savestate to begin with if I wasn't just trying to check something quickly in game where I had a bunch of patches applied and cheats to turn them off weren't modifying memory.

**Comment by unknownbrackets** [comment]
If you have an affected save state, it contains the git version to confirm if it's a proper version.

I suppose we could explicitly reschedule cheat events if none is scheduled.  That said, if this was just a dev build maybe we should just close it.

-[Unknown]
