### ISSUE TITLE
Linux variant - random startup success (Docker container)

### ISSUE THREAD

**Issue by DoganM95** [hrydgard/ppsspp#14319]
I wrote a docker image to build ppsspp for linux and run it in a container to serve as a remote disc server and nothing more.
This works so far, except for some random stability issues when (re-) starting PPSSPPSDL binary.

### What happens?

When restarting the PPSSPP application (Ubuntu docker container) using 
```
    echo "Restarting PPSSPP.."

    # Kill PPSSPP process
    pkill Xvfb
    pkill PPSSPPSDL
    rm /tmp/.X99-lock

    # Restart PPSSPP
    xvfb-run --server-args="-screen 0, 1024x680x24" "/usr/src/app/build/PPSSPPSDL" &
```

It randomly gives me one of exactly three different possible outputs. Two outputs indicate a working instance, one not.
The first ouput i sometimes get is a successfull one, which also shows remote iso's on e.g. my Android client:
```
Restarting PPSSPP..
rm: cannot remove '/tmp/.X99-lock': No such file or directory
12:45:426 Core/Config.cpp:544 I[G3D]: Longest display side: -1 pixels. Choosing scale 1
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
12:45:473 SDL/SDLMain.cpp:121 E[AUDIO]: Failed to open audio device: ALSA: Couldn't open audio device: No such file or directory
VulkanMayBeAvailable: Device allowed ('SDL:Linux')
VulkanMayBeAvailable: Library loaded ('libvulkan.so')
VulkanMayBeAvailable: Enumerating instance extensions
VulkanMayBeAvailable: Instance extension count: 18
VulkanMaybeAvailable: Instance extension found: VK_KHR_device_group_creation (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_external_fence_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_external_memory_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_external_semaphore_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_get_display_properties2 (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_get_physical_device_properties2 (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_get_surface_capabilities2 (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_surface (00000019)
VulkanMaybeAvailable: Instance extension found: VK_KHR_surface_protected_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_wayland_surface (00000006)
VulkanMaybeAvailable: Instance extension found: VK_KHR_xcb_surface (00000006)
VulkanMaybeAvailable: Instance extension found: VK_KHR_xlib_surface (00000006)
VulkanMaybeAvailable: Instance extension found: VK_KHR_display (00000017)
VulkanMaybeAvailable: Instance extension found: VK_EXT_direct_mode_display (00000001)
VulkanMaybeAvailable: Instance extension found: VK_EXT_acquire_xlib_display (00000001)
VulkanMaybeAvailable: Instance extension found: VK_EXT_display_surface_counter (00000001)
VulkanMaybeAvailable: Instance extension found: VK_EXT_debug_report (00000009)
VulkanMaybeAvailable: Instance extension found: VK_EXT_debug_utils (00000001)
VulkanMayBeAvailable: Calling vkCreateInstance
VulkanMayBeAvailable: Vulkan test instance created successfully.
VulkanMayBeAvailable: Failed to count physical devices (VK_ERROR_INITIALIZATION_FAILED)
VulkanMayBeAvailable: Destroying instance
DEBUG: Vulkan is not available, not using Vulkan.
Info: We compiled against SDL version 2.0.10 and we are linking against SDL version 2.0.10. :)
Pixels: 960 x 544
Virtual pixels: 960 x 544
OpenGL 2.0 or higher.
loading control pad mappings from gamecontrollerdb.txt: SUCCESS!
```

The second output (also working) is:
```
Restarting PPSSPP..
X connection to :99 broken (explicit kill or server shutdown).
terminate called without an active exception
rm: cannot remove '/tmp/.X99-lock': No such file or directory
Aborted
error: XDG_RUNTIME_DIR not set in the environment.
Failed to initialize SDL with joystick support. Retrying without.
32:38:148 Core/Config.cpp:544 I[G3D]: Longest display side: -1 pixels. Choosing scale 1
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
32:38:199 SDL/SDLMain.cpp:121 E[AUDIO]: Failed to open audio device: ALSA: Couldn't open audio device: No such file or directory
```

The third possible output of the three, after which the remote discs are not accessible is the following:

```
Restarting PPSSPP..
X connection to :99 broken (explicit kill or server shutdown).
terminate called without an active exception
rm: cannot remove '/tmp/.X99-lock': No such file or directory
error: XDG_RUNTIME_DIR not set in the environment.
Failed to initialize SDL with joystick support. Retrying without.
error: XDG_RUNTIME_DIR not set in the environment.
Unable to initialize SDL: No available video device
VulkanMayBeAvailable: Device allowed ('SDL:Linux')
VulkanMayBeAvailable: Library loaded ('libvulkan.so')
VulkanMayBeAvailable: Enumerating instance extensions
VulkanMayBeAvailable: Instance extension count: 18
VulkanMaybeAvailable: Instance extension found: VK_KHR_device_group_creation (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_external_fence_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_external_memory_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_external_semaphore_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_get_display_properties2 (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_get_physical_device_properties2 (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_get_surface_capabilities2 (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_surface (00000019)
VulkanMaybeAvailable: Instance extension found: VK_KHR_surface_protected_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_wayland_surface (00000006)
VulkanMaybeAvailable: Instance extension found: VK_KHR_xcb_surface (00000006)
VulkanMaybeAvailable: Instance extension found: VK_KHR_xlib_surface (00000006)
VulkanMaybeAvailable: Instance extension found: VK_KHR_display (00000017)
VulkanMaybeAvailable: Instance extension found: VK_EXT_direct_mode_display (00000001)
VulkanMaybeAvailable: Instance extension found: VK_EXT_acquire_xlib_display (00000001)
VulkanMaybeAvailable: Instance extension found: VK_EXT_display_surface_counter (00000001)
VulkanMaybeAvailable: Instance extension found: VK_EXT_debug_report (00000009)
VulkanMaybeAvailable: Instance extension found: VK_EXT_debug_utils (00000001)
VulkanMayBeAvailable: Calling vkCreateInstance
VulkanMayBeAvailable: Vulkan test instance created successfully.
VulkanMayBeAvailable: Failed to count physical devices (VK_ERROR_INITIALIZATION_FAILED)
VulkanMayBeAvailable: Destroying instance
DEBUG: Vulkan is not available, not using Vulkan.
```

### What *should* happen?

Instead of randomly getting one of the three results, it should output the first (successful) one, every time the application/process is restarted.

### What are you using?
- libgl1-mesa-dev, libsdl2-dev, build-essential, cmake, libgl1-mesa-dev, libsdl2-dev, libvulkan-dev  (as written in wiki)
- xvfb (to run ppsspp without a display/emulate one to enable startup)

#### What hardware / device and operating system?
- Docker (FROM ubuntu:latest)

#### What graphics card (GPU) or mobile phone model?
- Xvfb (X virtual framebuffer), an in-memory display server for UNIX-like operating system (e.g., Linux). Enables running graphical applications without a display (e.g., browser tests on a CI server). - Cite from http://elementalselenium.com/

#### What PPSSPP version (standalone/official), and did it work before?
- 1.11 (i guess, it is cloned directly from your master branch each time there is a new version)

#### Checklist

 - [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [X] Try resetting settings or older versions and include if the issue is related.
 - [X] Include logs or screenshots of issue.

**Comment by DoganM95** [comment]
For now i will try implementing a workaround (which restarts the server until the output is one of the successful ones).
Solving this issue could however fix other problems, other users are getting.

**Comment by LunaMoo** [comment]
Does it always work if you change backend to just use OGL? It looks like Vulkan detection fails with that Xvfb.

 Probably better for you would be to request a feature for remote disc server to work with headless(if it doesn't already), as yes, PPSSPP does have headless build, so you shouldn't need third party software just to run it without graphics and sound which is supported natively, just not sure if it works with remote disc server as I use neither.

**Comment by unknownbrackets** [comment]
To me, this sounds like some sort of X race condition in your scripts, and not really much to do with PPSSPP itself.

`rm /tmp/.X99-lock` makes me think you're either uncleanly killing some X thing or not giving it enough time to asynchronously close down.  I know at least when using multiple dependent containers, waiting for proper startup is sometimes an issue.

If you add a simple `sleep 30` before the start, does it change the incidence?

You can just run a simple nginx or httpd docker container to serve, by the way.  PPSSPP just uses standard HTTP/1.1 range requests.  Any decent webserver should support it.  You'll just need an index file for it to know what to browse, and you can point it at the host in settings.

Currently headless will only listen for the debugger HTTP websocket requests, but I suppose we could make it run a little http server or possibly better yet make a separate one.  But you could easily achieve the same using something like https://github.com/vercel/serve (see https://github.com/vercel/serve/pull/465.)  I haven't tested it, but really, it just needs HTTP/1.1.

The auto-discovery registration could be implemented in nodejs or w/e too, but isn't really necessary.  Just put the hostname in the settings.

-[Unknown]

**Comment by DoganM95** [comment]
Thanks for your suggestions!

@LunaMoo Vulkan detection fails in any case, even if the RDS is working. I looked into the headless folder after building ppsspp initially but the contents look like a work in progress right now.

@unknownbrackets I also tought of some race condition and put a `sleep 30` between killing and starting, result unchanged.
The info about rds just being a http server simplifies things, i will just write a dockerized http server for that, thanks!

**Comment by unknownbrackets** [comment]
Headless is used mainly for automated testing.  It's not a work in progress - it works fine and has been used for many years to make sure various parts of PPSSPP function the same as a PSP using https://github.com/hrydgard/pspautotests.  It's the worst kept secret of how fast PPSSPP was able to achieve high compatibility.  Headless, though shunned by many, is very important.

Of course, every part of the emulator is always a work in progress.

Do you have a dockerfile that repros?  Something easy to test / iterate on?

-[Unknown]

**Comment by DoganM95** [comment]
I tried implementing your suggestion (http server to serve games), but it wasn't as simple as creating a html file next to the isos and serving it via node.js, unfortunately (tested and didn't work).
To analyze the mechanics of serving a remote disc, i started sharing games on my smartphone and accessed its ip:port via browser & postman. The only thing i got was a <pre> tag with text in it, no href or anything which i assumed is used to serve the games. 
The http headers also had no Ranges inside, which i hoped to see.

So i ended up continuing the dockerfile & shell variant. I will make the repository public and share the link here, once i find time to finish it :)

**Comment by unknownbrackets** [comment]
That's just the list of files.  The actual access to the data is using range requests.

You can create a simple index.txt file with filenames, i.e. "/mygame.cso".  It's not actually a pre tag.

Someone did add really basic support for parsing an Apache httpd index html doc.  It would only try this if the response content-type was text/html.

-[Unknown]

**Comment by unknownbrackets** [comment]
I'm not sure why X is failing like that, but I suspect it's not specifically related to PPSSPP as much as X.

Threw together a quick webserver:
[ppsspp-webserver.zip](https://github.com/hrydgard/ppsspp/files/6254071/ppsspp-webserver.zip)

Something like:
```sh
docker run --read-only -v /my/games:/var/isos -p 8300:8300 -d whatever-tag
```

This example is node.js and will automatically build the index list for you.

-[Unknown]

**Comment by DoganM95** [comment]
Thanks for your example server, works great!

I will  "fork" your attached zip, and put it in my repo (perhaps with some small changes), giving credit to you.

**Comment by unknownbrackets** [comment]
Glad to hear it.

Considering this is seemingly related to X / SDL issues (Unable to initialize SDL: No available video device) and specific to this docker use case, I'm going to close it given the more lightweight server exists.

That said, if someone from the future is reading this message and seeing errors like this in more typical usage, where other SDL and X programs work fine, please comment here or create a new issue.

-[Unknown]
