### ISSUE TITLE
Select game Language independently from the language menu

### ISSUE THREAD

**Issue by JaegerFox** [hrydgard/ppsspp#14318]
In my personal experience it seems much more comfortable to use any software in English, since it is a much easier way to understand certain options or parameters... but when playing I would like to play in my native language

For example :
```
PSP language = Latin Spanish
Menu language = English
```
I know that the language file can be replaced, but every time I update PPSSPP I have to do the process again.

**Comment by ANR2ME** [comment]
LOL i'm also one of those that always feels weird whenever i saw Window's menu items in my native language (non-english), probably because i'm used to see English menu.

**Comment by hrydgard** [comment]
This has been implemented in #17764 , I happened to closed a duplicate instead of this one.
