### ISSUE TITLE
Need For Speed Carbon: Own The City - Music bug

### ISSUE THREAD

**Issue by Back2Life888** [hrydgard/ppsspp#14323]
### What happens?
The music sometimes won't play when it needs to play.. For Example: I go to a race and the music somehow doesn't play.. Pausing the game is a workaround..

### What *should* happen?
The music should play everytime and should never go silent at all..

#### What hardware / device and operating system?
Windows 10H2
CPU: Intel i7-6700
GPU: Listed at the bottom
RAM: 34 Gigs

#### What graphics card (GPU) or mobile phone model?
GTX 1650

#### What PPSSPP version (standalone/official), and did it work before?
PPSSPP 1.11.3
I never played this game on any version but this..

**Comment by unknownbrackets** [comment]
Does anything show up in the log console when the music stops?

-[Unknown]

**Comment by Back2Life888** [comment]
> Does anything show up in the log console when the music stops?
> 
> -[Unknown]

How do I enable the log console?

**Comment by unknownbrackets** [comment]
On Windows, Ctrl-L or Debug -> Log Console.

On other platforms, the easiest way is the debugger: http://ppsspp-debugger.unknownbrackets.org/

-[Unknown]

**Comment by Back2Life888** [comment]
Weird. The issue suddenly stopped. I'll notify you if it happens again. For now, let's close the issue.
