### ISSUE TITLE
Audio Reverb Level Adjustment for Users

### ISSUE THREAD

**Issue by rkguy** [hrydgard/ppsspp#14328]
https://github.com/hrydgard/ppsspp/issues/10246

Reverb in some games drives a lot of people insane if there's a lot of it, making it unplayable for some including myself. 
I understand that it's basically impossible for you guys to adjust it perfectly for every game, which is why I'd like to propose a reverb level adjustment feature in the settings menu (maybe in audio or developer tools) to let users choose how much reverb there is/other parameters related to reverb. That way it's possible to let the devs work on the major problems and the users can spend the time fine tuning reverb levels/parameters per game.

**Comment by unknownbrackets** [comment]
I think reverb is still a bit inaccurate and it'd be nice to fix it.  An option to disable or reduce it manually might be nice though and is something we can consistently implement.  It's another setting but it wouldn't really affect actual emulation behavior.

-[Unknown]
