### ISSUE TITLE
Need a better background Adhoc Control reconnection attempts.

### ISSUE THREAD

**Issue by ANR2ME** [hrydgard/ppsspp#14333]
Based on announcement on Hunterverse discord
![image](https://user-images.githubusercontent.com/7974720/113349633-8f964480-9362-11eb-8832-5e7b37d9baf6.png)
There seems to be an issue of flooded logs on Adhoc Server side when connections attempts got refused, which could happened due to:
1. The player's IP still exists on Adhoc Server side (ie. due to PPSSPP crashing and unable to logout from Adhoc Server properly), players usually need to wait for 15 seconds for the IP to be removed from Adhoc Server (default timeout on Adhoc Server side is 15 sec, but they might also increased this timeout)
2. They implement banning system and the player is being banned.

I tried to simulate it on localhost by increasing the timeout to 150 sec and forcing non-first instance to use 127.0.0.2
![image](https://user-images.githubusercontent.com/7974720/113350241-675b1580-9363-11eb-83f1-da57e1083469.png)
With current implementation, PPSSPP will try to reconnects to Adhoc Server every 2 seconds in the case it lost connectivity to Adhoc Server to simulate what happened on a real PSP (based on @adenovan test where connection to adhoc control will be restored in background)

### What should happen?
Not to reconnect on interval based

### Who would benefit from it?
Adhoc Server hosters

#### Checklist

 - [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
 - [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by ANR2ME** [comment]
I'm thinking to improve it by reconnecting only when the game is trying to Create/Join/Connect to a group, and also Scan for groups instead of using interval.

**Comment by MojoJojoDojo** [comment]
I guess the fix not being on 1.11.3 stable release (because its on dev) caused sushicat to get ddosed and now its down lol.
rip.

**Comment by ANR2ME** [comment]
sushicat is online with 75 players right now, they probably had maintenance earlier.

And the flooding connection attempt shouldn't be as bad as ddos, since it have 2 seconds interval, compared to ddos which could flood many packets within few milliseconds.

**Comment by MojoJojoDojo** [comment]
No the sushicat owner ctually told me its because of this or fake games keep connecting and disconnecting.
But maybe.

**Comment by hrydgard** [comment]
Ah, that's not good - should improve once PPSSPP 1.13 is out though..
