### ISSUE TITLE
Castlevania SOTN (Dracula X Chronicles US) visual glitch and wrong behaviour

### ISSUE THREAD

**Issue by relu419** [hrydgard/ppsspp#14343]
**Everything was tested with US version of the game and OpenGL API + Original Internal Resolution**

1) During a specific death frame of Fire Demon on Castlevania SOTN, the sprite issue occurs. Sadly, the LOG doesn't have any useful information, but here the screenshot of the problem: https://ibb.co/F5XwJ1m

![image](https://user-images.githubusercontent.com/130929/113489510-f3d11980-94c4-11eb-9e0d-ca44148561de.png)

2) The behaviour of Fire Demon is wrong, too. The fire doesn't show up and instead of properly behaviour, only fade in black. The real behaviour on PSP is here: https://ibb.co/YR2hZXR 
![image](https://user-images.githubusercontent.com/130929/113489514-ffbcdb80-94c4-11eb-846a-28ec9208500e.png) 

The PPSSPP behaviour for comparison: https://ibb.co/QbCyVrv
![image](https://user-images.githubusercontent.com/130929/113489519-09deda00-94c5-11eb-83e0-e95d5a703968.png)

**Comment by unknownbrackets** [comment]
This is probably a missing block transfer.  I'd guess it's run properly (but much slower) in the software renderer.

-[Unknown]

**Comment by relu419** [comment]
> This is probably a missing block transfer. I'd guess it's run properly (but much slower) in the software renderer.
> 
> -[Unknown]

I've tried with software mode. The bahaviour is the same.

**Comment by unknownbrackets** [comment]
That's interesting.  Did you try from a ways before (I know it's slow), or just right at the glitch?  It could be that the game draws something earlier and uses it for effects later on, so loading a save state with the software renderer right when the glitch is visible might not be enough to confirm.

If it happens even from i.e. the start of the level, then it's hard to say what it might be.  Maybe a timing glitch even.  Could also confirm if it happens in JPCSP.

-[Unknown]

**Comment by relu419** [comment]
> That's interesting. Did you try from a ways before (I know it's slow), or just right at the glitch? It could be that the game draws something earlier and uses it for effects later on, so loading a save state with the software renderer right when the glitch is visible might not be enough to confirm.
> 
> If it happens even from i.e. the start of the level, then it's hard to say what it might be. Maybe a timing glitch even. Could also confirm if it happens in JPCSP.
> 
> -[Unknown]

I just used clean load with software render. Looks like some specific frame (sprite draw). This gitch repeats in the same frame everytime with the same enemy. Furthermore, any another API results in the samething.

**Comment by Gamemulatorer** [comment]
@relu419 can you upload your save state on that area?

**Comment by relu419** [comment]
> @relu419 can you upload your save state on that area?

I can send the save. It's better the save instant of save state to properly check, but it's next to the area.

**Comment by Gamemulatorer** [comment]
> > @relu419 can you upload your save state on that area?
> 
> I can send the save. It's better the save instant of save state to properly check, but it's next to the area.

Ok 👍
I will try your save please share.

**Comment by relu419** [comment]
> > > @relu419 can you upload your save state on that area?
> > 
> > 
> > I can send the save. It's better the save instant of save state to properly check, but it's next to the area.
> 
> Ok 👍 I will try your save please share.

I forgot. I just deleted the PPSSPP folder, but you'll have here:
https://gamefaqs.gamespot.com/psp/938141-castlevania-the-dracula-x-chronicles/saves

**Comment by Gamemulatorer** [comment]
> > > > @relu419 can you upload your save state on that area?
> > > 
> > > 
> > > I can send the save. It's better the save instant of save state to properly check, but it's next to the area.
> > 
> > 
> > Ok 👍 I will try your save please share.
> 
> I forgot. I just deleted the PPSSPP folder, but you'll have here: https://gamefaqs.gamespot.com/psp/938141-castlevania-the-dracula-x-chronicles/saves

What stage/part are you there?

**Comment by relu419** [comment]
> > > > > @relu419 can you upload your save state on that area?
> > > > 
> > > > 
> > > > I can send the save. It's better the save instant of save state to properly check, but it's next to the area.
> > > 
> > > 
> > > Ok 👍 I will try your save please share.
> > 
> > 
> > I forgot. I just deleted the PPSSPP folder, but you'll have here: https://gamefaqs.gamespot.com/psp/938141-castlevania-the-dracula-x-chronicles/saves
> 
> What stage/part are you there?

Inverted Laboratory.

**Comment by Gamemulatorer** [comment]
@relu419 what device/platform are you using?

**Comment by relu419** [comment]
> @relu419 what device/platform are you using?

Core I7 3.4/3.8GHz (PC). Any renderer/software mode. Same error.

**Comment by Panderner** [comment]
@relu419 GPU?

**Comment by unknownbrackets** [comment]
Interestingly, in #16045 this was reported fixed.  I wonder what it was, considering it was happening in software too - if anyone has time to test a few git builds to narrow it down, it might be really interesting and also help us make sure this stays fixed in the future.

That said, if this is fixed I'm going to close it.  If you're still able to reproduce this in the latest git build, please comment with more information, and ideally a GE frame dump.  Also might be worth double checking the disc CRC to make sure it's got no corruption.

-[Unknown]
