### ISSUE TITLE
Shinobido - Tales of the Ninja music problems in first level

### ISSUE THREAD

**Issue by MTR77** [hrydgard/ppsspp#14352]
Hello,

when playing the first level (Prologue) in the game (both European and Japanese versions) the music plays and loops correctly the first two times, then gets all stuttery and choppy the third time. After that it just stops completely. In the next level the music seems to be working and looping correctly.
The bug doesn't seem to happen on youtube playthroughs that I've watched so it might be recent issue.
Tested on pc (standalone & Retroarch) and android (Nvidia SHIELD - Retroarch).

Thanks in advance.

MTR77

**Comment by unknownbrackets** [comment]
If you can upload a log from when it happens, it may help.

-[Unknown]

**Comment by sum2012** [comment]
This is v1.16.6-249-ga9d2ff29e Windows 64 bit log:
https://gist.githubusercontent.com/sum2012/882b904710ce0e846a097616b525c1ab/raw/6ecc2190c61d7c7d6a29b1f083807c2733cb40c4/gistfile1.txt

It is same with K-on use sceAtracGetNextSample
