### ISSUE TITLE
PPSSPP now uses pic1.png instead of pic0.png for some games

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#14350]
### What happens?
In the screenshot of some PSP game for example Gundam vs. Gundam Next Plus uses pic1.png as a background in v1.11.2-422-g19e079a08 and newer
![Screenshot_2021-04-05-11-38-52-913_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/113534854-6b599280-9604-11eb-9cbf-7848f5df9518.jpg)

### What *should* happen?
In v1.11.2-418-g6f795fc12 and older this should like this:
![Screenshot_2021-04-05-11-47-21-951_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/113534992-bffd0d80-9604-11eb-961c-9f908e03bd4d.jpg)

#### What hardware / device and operating system?
Android 10
#### What graphics card (GPU) or mobile phone model?
POCO M3
#### What PPSSPP version (standalone/official), and did it work before?
Latest builds between v1.11.2-418-g6f795fc12 and v1.11.2-422-g19e079a08
#### Which game or games?

Any games that has pic1.png inside the ISO's directory
#### Checklist

 - [x] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [x] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [x] Try resetting settings or older versions and include if the issue is related.
 - [x] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
Oops, somehow swapped the lines.  I remember making sure I had pic1 first, so not sure what happened.  Sorry.

-[Unknown]

**Comment by Panderner** [comment]
This isn't right for older versions of PPSSPP and v1.11.2-426-g0081924fc
this should how it look:
![2021-04-05](https://user-images.githubusercontent.com/37503397/113542171-4d952900-9616-11eb-9132-d3f8d89f1ba5.png)

**Comment by unknownbrackets** [comment]
Right.  But it's kinda the same problem as then:

> Hm. PIC1 is also used during game loading, which is why we prefer it. We don't draw PIC0 on top currently, because it's often text or an ugly box that doesn't make for a good UI background behind touchable buttons and things.

> Thinking about touch wasn't something the designers of the PSP UI were very worried about.

> I'll note that the Vita doesn't even show either image, AFAIK.

-[Unknown]
