### ISSUE TITLE
PPSSPP Gta: Vice City Stories radar bug

### ISSUE THREAD

**Issue by metehan989** [hrydgard/ppsspp#14360]
### What happens?
The radar shows me some bugged map. See picture below ![image](https://user-images.githubusercontent.com/82084917/113832990-6eca5680-9789-11eb-8996-f7ff642e375e.png)

### What *should* happen?
The radar should show me the map of the game. See picture below. ![image](https://user-images.githubusercontent.com/82084917/113833170-9de0c800-9789-11eb-8775-9717628d6094.jpeg)

#### What hardware / device and operating system? 
An iPhone XR IOS non-jailbroken
Latest software

#### What graphics card (GPU) or mobile phone model?
1100 MHz 
#### What PPSSPP version (standalone/official), and did it work before? 
I have latest version. I have tried multiple versions but the same problem occurs

#### Which game or games?

Gta: Vice City Stories 
Game id: ULUS10160

#### Checklist

 - [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [X] Try resetting settings or older versions and include if the issue is related.
 - [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
This does look suspiciously like the iOS 14 bug that we worked around a while ago.

Which version of PPSSPP are you running exactly? You can see in the upper right corner of the main screen.

**Comment by metehan989** [comment]
Im now running on V1.9.2 . It runs the smoothest on my device.

**Comment by hrydgard** [comment]
Yeah, like I said, it's a bug in iOS 14 that we worked around in newer versions of PPSSPP (1.10 something, I think). So not surprising that you hit this bug in an old version like 1.9.2. 

Thus, all we can hope for is for Apple to fix their bug in the next iOS (I have reported it), or you'll have to upgrade to the latest PPSSPP.

**Comment by metehan989** [comment]
Thanks :)
