### ISSUE TITLE
CSO Reader crashes in Birth By Sleep[ULUS10505] FMV after starting new game.

### ISSUE THREAD

**Issue by Squall-Leonhart** [hrydgard/ppsspp#14373]
### What happens?
When running a CSO compressed image of Birth By Sleep[ULUS10505] the second FMV crashes as the character says "This world is too small"

### What *should* happen?
It should not crash.

### What are you using?
Xeon x5690 / Xeon E5-1680v2 | Windows 7 / 10

#### What graphics card (GPU) or mobile phone model?
GTX 1080 / GTX 1060

#### What PPSSPP version (standalone/official), and did it work before?
https://github.com/hrydgard/ppsspp/commit/0328a0d550840687b55f45dddcc0838b2c670aeb

#### Which game or games?
Birth By Sleep[ULUS10505]
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/6293316/ppsspplog.zip)

Things tried
Using a lower compression
Changing the UMD Padding

What Works
An ISO image, yes, even one made from the CSO that isn't working.

**Comment by unknownbrackets** [comment]
I'm using a CSO and receive no crash.  What did you use to create your CSO?

If you download [maxcso](https://github.com/unknownbrackets/maxcso) and run `maxcso --crc` on the cso file, is it 40430710?  This is the same CRC I have from my original disc.

-[Unknown]

**Comment by Squall-Leonhart** [comment]
UMDGen v4, 
This is a regression in PPSSPP,
I've always used these iso's and i've played through the aqua story entirely on ppsspp in the past (2013ish)

**Comment by unknownbrackets** [comment]
Nothing in PPSSPP's CSO handling has changed in a while.  The only change in the past ~5 years has been 931dff6, which shouldn't affect files generated by UMDGen unless they're corrupt.  That was also over a year ago, and I'd like to think someone would've reported this game being broken in that time if so.

-[Unknown]

**Comment by Squall-Leonhart** [comment]
Crash happens in maxcso created CSO as well.

**Comment by unknownbrackets** [comment]
Hm, the hash of the underlying data (what maxcso reports) should not be different.  The hash of the cso itself will be different as the maxcso file is probably smaller.

Are you using any cheats, replacements, or plugins?  Trying to understand why it'd affect you but not me.  You're also using the 64-bit version of PPSSPP?

-[Unknown]

**Comment by Squall-Leonhart** [comment]
No cheats, replacements, plugins and occurs in both 32bit and 64bit versions.

I'm trying to determine why the ISO is fine since i made it from the CSO.

UMDGen CSO
4349534F0000000000285969000000000008000001000000

Maxcso
4349534F1800000000285969000000000008000001000000

**Comment by unknownbrackets** [comment]
If you disable fast memory and disable ignore bad memory access, does it show any kind of error instead of crashing - or still crash?

If you pause your virus scanner or allow PPSSPP / the CSO file to be excluded, does that change anything?  (I do run a virus scanner, just trying to come up with differences that would prevent me from seeing your problem.)

If you try another couple games with CSO, and just start them, fast forward, and mash X... do they run fine or do you get any other crashes?

-[Unknown]

**Comment by Squall-Leonhart** [comment]
Still crashes,

I'm going to go grab the game storage and try dumping it clean.

**Comment by Squall-Leonhart** [comment]
Apparently I made these back when modifying the Boot and Eboot contents was still the norm, the total sector count and image size were lower than what a clean image would be. (JPSP days)

The modifications may have thrown off the CSO readers expected LBA's but not affect the ISO reader

Ok, i can replicate the crash from a clean ISO only if I use the Optimize Image feature in UMDGen\UMD Properties, so it looks like scrubbing this particular game causes the problem.

**Comment by Squall-Leonhart** [comment]
Closed as bad/modified dump.
