### ISSUE TITLE
7th Dragon 2020-II [NPJH50716] (English Patch) - Bad Execution Address when attempting to attack or buff

### ISSUE THREAD

**Issue by arnoldsecret** [hrydgard/ppsspp#14381]
### What happens?
![Untitled](https://user-images.githubusercontent.com/41223243/114952612-344b7280-9e89-11eb-81b4-427de9d01815.png)
![Untitled2](https://user-images.githubusercontent.com/41223243/114952639-43322500-9e89-11eb-9161-0a5644f962e1.png)

### What *should* happen?
Attacks and buffs should work as normal 

### What are you using?
A patched version of said game above.
#### What hardware / device and operating system?
Windows 10 Pro
#### What graphics card (GPU) or mobile phone model?
NVIDIA Geforce 740m
#### What PPSSPP version (standalone/official), and did it work before?
g74f08bee2, same issues as latest standalone. Previous PPSSPP versions work before though.
#### Which game or games?
7th Dragon 2020-II [NPJH50716] (English Patch)

I've attached a save state just before the first enemy encounter. It works from 1.11 onward.
[PPSSPP_STATE.zip](https://github.com/hrydgard/ppsspp/files/6321662/PPSSPP_STATE.zip)

**Comment by arnoldsecret** [comment]
Took the time to test out stable versions and it turns out this issue has been present since 1.11
1.11 - Invalid Memory Access
1.10.3 - Works

**Comment by Panderner** [comment]
Can you please test the unpatched japanese version?

**Comment by arnoldsecret** [comment]
The unpatched Japanese version works fine, in fact loading a game using a save file from an unpatched game seems to work fine.
![Untitled3](https://user-images.githubusercontent.com/41223243/114965224-c744d680-9ea2-11eb-99fe-7257548d93b2.png)

**Comment by Panderner** [comment]
Have you tried to test older builds of PPSSPP?

**Comment by arnoldsecret** [comment]
The problem seems to go deeper, and really so, It seems to be in relation to my new game being an import save from my previous 7th Dragon 2020 system data and save, but I couldn't do it in the latest build, I could in previous builds.
I'm moving this issue to https://github.com/hrydgard/ppsspp/issues/14382.

**Comment by arnoldsecret** [comment]
after a bit of thorough testing, I've concluded that it's because of a particular cheat in this https://github.com/Saramagrean/CWCheat-Database-Plus-, specifically the HP doesn't decrease cheat. Closing for now.
