### ISSUE TITLE
Medievil Resurrection - Black screen

### ISSUE THREAD

**Issue by bslenul** [hrydgard/ppsspp#14380]
Medievil Resurrection doesn't work properly atm, it only shows a black screen:

```
46:53:343 hle\scenet.cpp:213 N[SCENET]: LocalHost IP will be 127.0.0.1 [a3:a4:e6:bf:05:b1]
46:53:396 root         N[G3D]: vulkan\shadermanagervulkan.cpp:424 Loaded 2 vertex and 2 fragment shaders
46:53:396 root         N[G3D]: vulkan\pipelinemanagervulkan.cpp:756 Creating 2 pipelines...
46:53:400 root         N[G3D]: vulkan\pipelinemanagervulkan.cpp:792 Recreated Vulkan pipeline cache (2 pipelines, 0 failed).
46:53:408 root         N[BOOT]: ui\emuscreen.cpp:298 Loading F:/Roms/Sony - PlayStation Portable/MediEvil Resurrection (USA).cso...
46:53:523 BootTh       E[SCEIO]: hle\sceumd.cpp:306 UNTESTED 0=sceUmdDeactivate(2, disc0:)
46:53:523 BootTh       E[HLE]: hle\hle.cpp:729 Unimplemented HLE function sceKernelStopUnloadSelfModule
46:53:531 idle0        E[SCEKERNEL]: hle\scekernelthread.cpp:1243 __KernelGetWaitID ERROR: thread 278
46:59:675 vulkan\shadermanagervulkan.cpp:446 N[G3D]: Saved 2 vertex and 2 fragment shaders
46:59:675 vulkan\pipelinemanagervulkan.cpp:697 N[G3D]: Saved Vulkan pipeline ID cache (2 unique pipelines/2).
```
Windows 10 / i5-4670k / GTX 970, tried with OpenGL, D3D11 and Vulkan, same results.

Already bisected, looks like the first "bad" commit is 871a0f94922cb35aea62e85bb13ba37fa339a6cd.

**Comment by hrydgard** [comment]
Thanks for bisecting!

While it looks like the commit is from January, it's really from https://github.com/hrydgard/ppsspp/pull/13970 which I merged 5 days ago (I had somehow forgotten about it).

Anyway, the culprit commit indeed seems plausible - games are so sensitive to timing details like this.

Looks like the game calls sceKernelStopUnloadSelfModule which is often a sign of the game just giving up - maybe we returned a wrong error code somewhere?

**Comment by unknownbrackets** [comment]
Oops.  Not sure about the unload self, but pushed 74f08bee2 quickly - dumb mistake, I flipped that when testing something and really thought I'd flipped it back.

-[Unknown]

**Comment by bslenul** [comment]
Works like a charm, thanks for the quick fix! 👍 

> Not sure about the unload self

Do you want me to leave this issue open for this? FYI the line `E[HLE]: hle\hle.cpp:729 Unimplemented HLE function sceKernelStopUnloadSelfModule` was already appearing before #13970 was merged (tested with 6f332dd66).

**Comment by bslenul** [comment]
Closing, feel free to reopen if you want me to test anything about that unload self thing! Thank you again for the fix, and for your work overall ❤️

**Comment by hrydgard** [comment]
Was probably not relevant after all. Thanks!
