### ISSUE TITLE
background is always missing or back to default

### ISSUE THREAD

**Issue by IrfanH495** [hrydgard/ppsspp#14384]
### What happens?
background is always missing or back default
From ver v1.11.2-382-gee641c1ed & v1.11.2-487-gf52bef701
Open gl
https://drive.google.com/file/d/16aITfYb9FlIk_R4mp7oXG7A7Un9M9udp/view?usp=drivesdk
Vulkan
https://drive.google.com/file/d/16TwPBOIAwQbaqXKUav2udYjEmlFSNUZG/view?usp=drivesdk
#### Checklist

 - [x] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [x] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [ ] Try resetting settings or older versions and include if the issue is related.
 - [ ] Include logs or screenshots of issue.

**Comment by IrfanH495** [comment]
Ppsspp v1.11.2-488-g74f08bee2 I've tried it and it's the same as in video

**Comment by Panderner** [comment]
Here's an another video for this issue:

https://user-images.githubusercontent.com/37503397/115095301-5ad5e000-9f53-11eb-88db-441c3851af5b.mp4

**Comment by unknownbrackets** [comment]
Oops, broken by #14313.  Will fix.

-[Unknown]

**Comment by Panderner** [comment]
Please note that this issue does not occur for my Windows PC.
