### ISSUE TITLE
7th Dragon 2020-II [NPJH50716] - Can't import system data

### ISSUE THREAD

**Issue by arnoldsecret** [hrydgard/ppsspp#14382]
### What happens?
![Capture](https://user-images.githubusercontent.com/41223243/114987849-34b72e00-9ec8-11eb-987e-a2ffd4344f99.PNG)

### What *should* happen?
It should import the system data and save successfully.

### What are you using?
A patched version of said game above.
#### What hardware / device and operating system?
Windows 10 Pro
#### What graphics card (GPU) or mobile phone model?
NVIDIA Geforce 740m
#### What PPSSPP version (standalone/official), and did it work before?
g74f08bee2. It works on the official release (1.11).
#### Which game or games?
7th Dragon 2020-II [NPJH50716] both English patched and unpatched.

**Comment by unknownbrackets** [comment]
That folder looks wrong.  Shouldn't it be NPJH50716DATA?

NPJH50459 is the previous game:
https://report.ppsspp.org/game/NPJH50459_1.01

Did you try creating the system data?

-[Unknown]

**Comment by LunaMoo** [comment]
He's importing previous game data for bonuses so the ID is ok.
Seems to be a regression seeing his crossed text in other issue https://github.com/hrydgard/ppsspp/issues/14381#issuecomment-820977284

**Comment by arnoldsecret** [comment]
It last worked on gbc4963b40, g6f332dd66 and newer builds exhibit this issue.

**Comment by arnoldsecret** [comment]
It last worked on gbc4963b40, g6f332dd66 and newer builds exhibit this issue.

**Comment by unknownbrackets** [comment]
Hm, maybe be volatile related: bc4963b40...6f332dd66.

Are any errors shown in the log?

-[Unknown]

**Comment by arnoldsecret** [comment]
I can only find these errors in the log.
```
	Line 196: 43:58:206 hle\scekernelmodule.cpp:382 D[LOADER]: Importing sceAtracGetInternalErrorInfo : 08a44728
	Line 224: 43:58:209 hle\scekernelmodule.cpp:382 D[LOADER]: Importing sceUmdGetErrorStat : 08a445e0
```
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/6373556/ppsspplog.zip)

**Comment by unknownbrackets** [comment]
When #14413 finishes building, can you try the build there (go to the Checks tab and check the Artifacts button)?

-[Unknown]

**Comment by arnoldsecret** [comment]
The newest build has it successfully imported. Closing.
