### ISSUE TITLE
Crash screen should display whether cheats are enabled

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#14396]
See #14381, and possibly others. Cheats can easily randomly break stuff, so blue screen crashes should include information about enabled cheats.

**Comment by ANR2ME** [comment]
True, sometimes we forgot that we had cheat enabled

**Comment by ANR2ME** [comment]
Btw, does disabling "Ignore bad memory accesses" supposed to prevent this blue screen from appearing?
Which is why i keeps getting a frozen blank white screen instead of blue screen while testing the issue on Yu-gi-oh Tag Force 2

**Comment by ANR2ME** [comment]
Hmm.. apparently Enabling Fast memory could prevent this blue screen from appearing, and ended with frozen PPSSPP where i need to force-closing it during my test on Yu-gi-oh Tag Force 2 issue.
