### ISSUE TITLE
Some tests fail (can't locate fullbench)

### ISSUE THREAD

**Issue by lgbaldoni** [hrydgard/ppsspp#14402]
### What platform, compiler, and build tools?

openSUSE Tumbleweed, gcc 10, x86_64.
Latest (20210422) git commit.

### What happens (don't forget logs)?

The build completes regularly. Some tests fail:

```
0% tests passed, 4 tests failed out of 4

Label Time Summary:
Medium    =   0.00 sec*proc (3 tests)

Total Test time (real) =   8.64 sec

The following tests did not run:
          5 - playTests (Disabled)

The following tests FAILED:
          1 - glslang-testsuite (Failed)
          2 - fullbench (Not Run)
          3 - fuzzer (Not Run)
          4 - zstreamtest (Not Run)
Errors while running CTest
```

See full [build log](https://github.com/hrydgard/ppsspp/files/6366947/ppsspp_TW_test_failure.txt.gz).

Is this `fullbench` supposed to be built among the tests themselves?

**Comment by unknownbrackets** [comment]
These are actually coming from dependencies (glslang, zstd, etc.)  From a quick look, it looks like it just couldn't run `glslangValidator`.

-[Unknown]

**Comment by hrydgard** [comment]
These are not tests we ever look at. I don't think there's any need for concern here.

**Comment by lgbaldoni** [comment]
I see now they are not being built at all, and if you say so I'm just going to exclude them.

**Comment by hrydgard** [comment]
Yes, that seems fine.
