### ISSUE TITLE
😩Crash BLUE screen Yu Gi Oh!😩

### ISSUE THREAD

**Issue by DavidSilvadeSa** [hrydgard/ppsspp#14400]
![Screenshot_20210422-224606](https://user-images.githubusercontent.com/82737672/115821366-09a57080-a3d9-11eb-8230-3a921f524a9a.jpg)

**Comment by ANR2ME** [comment]
Please give more information on how to reproduce this issue, otherwise the devs won't be able to investigate it.

**Comment by unknownbrackets** [comment]
Locked CPU Frequency and cheats are known to cause crashes.  Try without cheats and set the CPU speed to default.

-[Unknown]

**Comment by DavidSilvadeSa** [comment]
Sorry

:OLD ver... •WORK•:
((
... ✅WORK✅
.
... ✅WORK✅
.
v1.11.2-514-g50b0e8411 🗓️2021-04-17🗓️ ✅WORK✅
.
v1.11.2-516-g199735203 🗓️2021-04-18🗓️ ✅LAST WORK✅
))

+----------------------------------------------------------------------------+

:NEW ver... •NOT WORK•:
((
... ❌NOT WORK❌
.
... ❌NOT WORK❌
.
v1.11.2-519-g036efc24a 🗓️2021-04-18🗓️ ❌NOT WORK❌
.
v1.11.2-540-g8d0ca1e4f 🗓️2021-04-22🗓️ ✍️LAST UPDATE✍️ ❌NOT WORK❌
))

:IN GAME:
Config DEFAULT - "Original Config" ❌NOT WORK❌

Config CUSTOM ❌NOT WORK❌

;;

open PPSSPP / select game "YU GI OH 1, 2, 3..." / •in game• ✅LOAD MEMORY STICK✅. ✅SCREEN START✅. ❌❌LOAD GAME or START NEW GAME❌❌.

✍️Independent ir what i do does NOT WORK✍️

📳•SCREEN BLUE•📳

**Comment by ANR2ME** [comment]
Hmm.. that is strange, between `v1.11.2-516-g199735203` to `v1.11.2-519-g036efc24a` there is only miniupnp fork update

**Comment by DavidSilvadeSa** [comment]
I don't use cheat

:GAME ver ULUS10302_1.02 🇺🇲USA🇺🇲:

Android PPSSPP any CONFIG original or custom ❌NOT WORK❌

📳BLUE SCREEN📳

**Comment by unknownbrackets** [comment]
Thanks for testing the ranges.  That does indeed only show a miniupnpc change:
https://github.com/hrydgard/ppsspp/compare/19973520...036efc24

Does this crash only occur with networking/wlan features enabled?  Does it crash while you are using network features, or always?

-[Unknown]

**Comment by DavidSilvadeSa** [comment]
I just re-install PPSSPP last UPDATE 🧬v1.11.2-540-g8d0ca1e4f🧬 100%ORIGNAL config and CLEAR cache/dados WLAN-On WLAN-Off WIFI-On WIFI-Off and............... ❌NOT WORK❌

TEST in
Samsung j600 Android 10Q
.
Galaxy 01 Core
❌NOT WORK❌

**Comment by ANR2ME** [comment]
Is this only happening on Yu-gi-oh games? or other games also having blue screen?

**Comment by DavidSilvadeSa** [comment]
MONSTER HUNTER GAMES Original Config/Custom Config ✅WORK✅

about
YU GI OH GX TAG FORCE 1 2 ❌NOT WORK❌

and

IN GAME/MENU/NETWORK MODE "ERRO PORT OFFSET'
![Screenshot_20210424-033143](https://user-images.githubusercontent.com/82737672/115949845-0e882400-a4ae-11eb-9e5c-0456c18f063b.jpg)

**Comment by ANR2ME** [comment]
> 
> 
> Sorry
> 
> :OLD ver... •WORK•:
> ((
> ... ✅WORK✅
> .
> ... ✅WORK✅
> .
> v1.11.2-514-g50b0e8411 🗓️2021-04-17🗓️ ✅WORK✅
> .
> v1.11.2-516-g199735203 🗓️2021-04-18🗓️ ✅LAST WORK✅
> ))
> 
> +----------------------------------------------------------------------------+
> 
> :NEW ver... •NOT WORK•:
> ((
> ... ❌NOT WORK❌
> .
> ... ❌NOT WORK❌
> .
> v1.11.2-519-g036efc24a 🗓️2021-04-18🗓️ ❌NOT WORK❌
> .
> v1.11.2-540-g8d0ca1e4f 🗓️2021-04-22🗓️ ✍️LAST UPDATE✍️ ❌NOT WORK❌
> ))
> 
> :IN GAME:
> Config DEFAULT - "Original Config" ❌NOT WORK❌
> 
> Config CUSTOM ❌NOT WORK❌
> 
> ;;
> 
> open PPSSPP / select game "YU GI OH 1, 2, 3..." / •in game• ✅LOAD MEMORY STICK✅. ✅SCREEN START✅. ❌❌LOAD GAME or START NEW GAME❌❌.
> 
> ✍️Independent ir what i do does NOT WORK✍️
> 
> 📳•SCREEN BLUE•📳

Based on this post, you can only reach the "New Game" or "Continue" selection after pressing Start, right? 
and choosing any of them will get you blue screen, right?
So, how did you managed to get to multiplayer?

PS: Android need port offset higher than 1024, but if you're not playing multiplayer try disabling WLAN, disable UPnP, disable built-in AdhocServer

**Comment by ANR2ME** [comment]
**Update1:** I tested Yugioh 2 on Windows build, and just by idling on Press Start screen for a while, PPSSPP frozen with this in the log
![image](https://user-images.githubusercontent.com/7974720/115952750-0bbf1a80-a512-11eb-9e87-3a8322af873f.png)
![image](https://user-images.githubusercontent.com/7974720/115952765-25606200-a512-11eb-8765-6920f5a9fedc.png)
![image](https://user-images.githubusercontent.com/7974720/115952783-39a45f00-a512-11eb-88ac-a1dc482a793f.png)
I wondered why it's showing blank white screen instead of blue screen... ~~and it seems to be random, or~~ may be a cutscene supposed to shows up after idling for too long?

**Update2:** After idling for too long on Press Start screen, an animation will shows up, and after a few seconds later PPSSPP frozen, and this issue really did started from `v1.11.2-519-g036efc24a`
![image](https://user-images.githubusercontent.com/7974720/115953059-93595900-a513-11eb-998a-5023bf212acf.png)

**Update3:** `v1.11.2-516-g199735203` didn't have this issue
![image](https://user-images.githubusercontent.com/7974720/115953309-e089fa80-a514-11eb-9c3b-58db00cf305a.png)
PS: Both of these logs are tested with WLAN, UPnP, and built-in AdhocServer being disabled

It's strange that updating miniupnp could do this, the library is not even initialized

**Comment by unknownbrackets** [comment]
If you set a breakpoint on the lw above the jalr, and make it log (but not break) something like: `{v0+0x6EC0}={[v0+0x6EC0]}`, what's the last address logged before it crashes?  Most likely, something is overwriting that memory.

Then I'd compare a build before the change the same way (maybe log all the values if there aren't a crazy number of them) and see if it's the same address.

If it's the same addresses both times, that's easier and we just need to figure out what's modifying that memory.  If it's different addresses, we have to follow the thread farther.

-[Unknown]

**Comment by ANR2ME** [comment]
i'm not sure i know how to log an instruction :)

Btw, i tried to reverse both commits from miniupnp fork update, and also making sure the submodule's head is pointing on an old commit from Dec 24, 2019 (which is the first time i forked miniupnp) and rebuild the solution, but the issue is still exist :(

**Comment by unknownbrackets** [comment]
Ah, darn.  If it's not new, might be trickier.

For logging, simply set a breakpoint (double click in the debugger) on an instruction.  Then, press ctrl-e to edit the breakpoint.  Uncheck Break and check Log, then paste the log format `{v0+0x6EC0}={[v0+0x6EC0]}`,  This will log the address it read from = what it read so we can see when the 00000055 is read and from where.

You could also use a condition to only break when the value is 55, but I feel like it might be useful to be aware of other values (in case the address previously had good data - that would be suggestive of something overwriting it.)

-[Unknown]

**Comment by ANR2ME** [comment]
Hmm. this is strange, i tried to start from `v1.11.2-516-g199735203` which worked fine, and then i update miniupnp submodule to the latest master, which will cause ppsspp to get error due to missing `addr_is_reserved.h/.c`, so i added those 2 files to miniupnp project.
Clean and Rebuild Solution, when i test again this issue didn't happened O.o why it have a different result compared to https://github.com/hrydgard/ppsspp/pull/14390 ? 
Does updating the submodule to the latest master which fixed it?

**Comment by hrydgard** [comment]
Bizarre! Really should have had the same result..

**Comment by ANR2ME** [comment]
Could someone try to revert https://github.com/hrydgard/ppsspp/pull/14390 to see whether it can fix this issue?
Because when i tried to revert it, the issue still exist :( or may be i'm doing it incorrectly?

**Comment by hrydgard** [comment]
It just seems so obviously unrelated :(

But OK, I'll revert it.

**Comment by hrydgard** [comment]
https://github.com/hrydgard/ppsspp/pull/14405

**Comment by ANR2ME** [comment]
Thanks for the experimental PR :)

Since the experimental PR have no difference, i'll try to start from `v1.11.2-516-g199735203` and cherry-picking the commits to skip PR https://github.com/hrydgard/ppsspp/pull/14390

**Comment by ANR2ME** [comment]
i tried cherry-picking up to v1.11.2-497-g086b8229f GE Debugger: Keep dump generation deterministic. (which is the last commit of PR at v1.11.2-529-g8e953b2a9) followed by git submodule update --init (probably not needed)
Clean & Rebuild Solution and the issue starting to happen again...

**Comment by unknownbrackets** [comment]
The rc_version.h file seems to be generated and should be in .gitignore.  Might be when you go back to the old version it's no longer ignored.

-[Unknown]

**Comment by ANR2ME** [comment]
Yes, that seems to be the case.

Btw, i tried to revert PR https://github.com/hrydgard/ppsspp/pull/14383 from the latest version, to see whether it's really the cause of this blue screen, but ended with `Error	C2065	'm_pPhysicalVRAM1': undeclared identifier	Core	C:\Users\AdamN\Documents\Projects\ppsspp\Core\MemMap.cpp	397`
And i can't search this `m_pPhysicalVRAM1` on ppsspp github

**Comment by unknownbrackets** [comment]
I changed that to an array:

https://github.com/hrydgard/ppsspp/blob/fd2ff87dcb423ffa3ab2df49de8638ecda4f0735/Core/MemMap.cpp#L71

`git bisect` can usually manage reverting things, essentially, automatically.

-[Unknown]

**Comment by ANR2ME** [comment]
Okay, reverting PR #14383 seems to fix this issue.
Well, at least we now know which PR that make sense to cause a blue screen :)

**Comment by unknownbrackets** [comment]
Can you bisect the commits in there?  I kept them separate in case there was any issue.

I could imagine something with the memory stick free space, maybe?  Otherwise it would have to be the relocations somehow.  There shouldn't be any overlapping...

-[Unknown]

**Comment by ANR2ME** [comment]
I'm not familiar with `git bisect`, what i did was reverting each commit in that PR in reversed order, using `v1.11.2-536-g0919f8a95` as the base.

**Comment by unknownbrackets** [comment]
What you can do is this:

First, be prepared with a commit you know is working (let's say 036efc24ae3367dc88c5e4455ab493556babe454) and a commit you know isn't working (let's say a3680ca3cbc5d53c2377b4160136ae94c661e239.)  It may be good to try them separately first to be sure, but sounds like you already have.

Then:

```
git bisect start
big bisect good 036efc24ae3367dc88c5e4455ab493556babe454
git bisect bad a3680ca3cbc5d53c2377b4160136ae94c661e239
```

After this, git will automatically find a commit half way between and checkout for you.  You'll still need to run `git submodule update --recursive`, build, and test.

Once you're done, run `git bisect good` if it's working (no need for any other argument), or `git bisect bad` if it's bad.  If it can't build or there's another, different bug run `git bisect skip`.

This way, git will help you test the least number of times to figure out when some problem was introduced.

-[Unknown]

**Comment by ANR2ME** [comment]
Is this a sign for the end of bisect?
```
git bisect bad
4f961693573221af316cae64e5221b5bab04bfa8 is the first bad commit
commit 4f961693573221af316cae64e5221b5bab04bfa8
Author: Unknown W. Brackets <checkins@unknownbrackets.org>
Date:   Fri Apr 16 00:53:50 2021 -0700

    Core: Init memory on multiple threads.
    
    Also init volatile at the same time for consistency.

 Common/Thread/ThreadPool.cpp | 7 +++++++
 Common/Thread/ThreadPool.h   | 1 +
 Core/HLE/sceKernelMemory.cpp | 7 ++++---
 Core/MemMap.cpp              | 9 ---------
 Core/ThreadPools.cpp         | 5 +++++
 Core/ThreadPools.h           | 1 +
 6 files changed, 18 insertions(+), 12 deletions(-)
```

So that mean commit https://github.com/hrydgard/ppsspp/pull/14383/commits/4f961693573221af316cae64e5221b5bab04bfa8 is the issue?

**Comment by unknownbrackets** [comment]
If you revert just these two lines does it help?

https://github.com/hrydgard/ppsspp/commit/4f961693573221af316cae64e5221b5bab04bfa8#diff-c5e136f3a3467a5e023f7a85ae0f235b9323b337765038b56b6f2cec8e8fa096L433

The only difference of those lines ought to be that it also sets volatile memory to 0, outside the parallelization.

-[Unknown]

**Comment by ANR2ME** [comment]
> 
> 
> If you revert just these two lines does it help?
> 
> [4f96169#diff-c5e136f3a3467a5e023f7a85ae0f235b9323b337765038b56b6f2cec8e8fa096L433](https://github.com/hrydgard/ppsspp/commit/4f961693573221af316cae64e5221b5bab04bfa8#diff-c5e136f3a3467a5e023f7a85ae0f235b9323b337765038b56b6f2cec8e8fa096L433)
> 
> The only difference of those lines ought to be that it also sets volatile memory to 0, outside the parallelization.
> 
> -[Unknown]

Yes, reverting those 2 lines fixed this on the latest version.

**Comment by unknownbrackets** [comment]
What if you make it...

```
Memory::Memset(PSP_GetKernelMemoryBase(), 0, PSP_GetUserMemoryEnd() - PSP_GetKernelMemoryBase(), "MemInit");
NotifyMemInfo(MemBlockFlags::WRITE, PSP_GetKernelMemoryBase(), PSP_GetUserMemoryEnd() - PSP_GetKernelMemoryBase(), "MemInit");
```

That would still clear volatile memory, but would not use threads.  If this works and using a thread doesn't, then there's a deeper problem with the threadpool handling...

-[Unknown]

**Comment by ANR2ME** [comment]
> 
> 
> What if you make it...
> 
> ```
> Memory::Memset(PSP_GetKernelMemoryBase(), 0, PSP_GetUserMemoryEnd() - PSP_GetKernelMemoryBase(), "MemInit");
> NotifyMemInfo(MemBlockFlags::WRITE, PSP_GetKernelMemoryBase(), PSP_GetUserMemoryEnd() - PSP_GetKernelMemoryBase(), "MemInit");
> ```
> 
> That would still clear volatile memory, but would not use threads. If this works and using a thread doesn't, then there's a deeper problem with the threadpool handling...
> 
> -[Unknown]

This changes also worked fine

**Comment by unknownbrackets** [comment]
Strange.  I can't see what's wrong with the loop.  If you put both versions in either order, it still works right?

If so, then it must somehow either not be memsetting all the RAM properly, or not waiting properly for it to complete before continuing, I suppose.

I tried making it 0xCC and it seemed to fill all the memory for me... hm.  What is your `g_Config.iNumWorkerThreads`?

-[Unknown]

**Comment by ANR2ME** [comment]
> 
> 
> Strange. I can't see what's wrong with the loop. If you put both versions in either order, it still works right?
> 
I'm not quite sure what this mean..
Both version as in `GlobalThreadPool::Memset` vs `Memory::Memset` ?
Either order as swapping the lines of `Memset` and `NotifyMemInfo`?

>
> If so, then it must somehow either not be memsetting all the RAM properly, or not waiting properly for it to complete before continuing, I suppose.
> 
> I tried making it 0xCC and it seemed to fill all the memory for me... hm. What is your `g_Config.iNumWorkerThreads`?
> 
I didn't recognize this `g_Config.iNumWorkerThreads` settings, probably the default value.
How do i checked it's value? do i need to put breakpoint somewhere and watched the value?

**Comment by unknownbrackets** [comment]
> Both version as in GlobalThreadPool::Memset vs Memory::Memset ?

Sorry yes, both those lines.  Does it work with `GlobalThreadPool::Memset` and then `Memory::Memset`?  If `GlobalThreadPool::Memset` is partially memsetting, this would "fix" it.

Then does it work swapping the memsets?  If `GlobalThreadPool::Memset` is afterward, does that affect anything differently?

> I didn't recognize this g_Config.iNumWorkerThreads settings, probably the default value.

Just in the ini as NumWorkerThreads.  So it should be 4 or 8 on your system (you'll likely get best performance with 8 or perhaps 7.)  Hmm.

-[Unknown]

**Comment by ANR2ME** [comment]
> 
> 
> > Both version as in GlobalThreadPool::Memset vs Memory::Memset ?
> 
> Sorry yes, both those lines. Does it work with `GlobalThreadPool::Memset` and then `Memory::Memset`? If `GlobalThreadPool::Memset` is partially memsetting, this would "fix" it.
> 
> Then does it work swapping the memsets? If `GlobalThreadPool::Memset` is afterward, does that affect anything differently?
> 
I'm still confused... do i need to combine `GlobalThreadPool::Memset` with `Memory::Memset`? That's kinda redundant isn't?
Is the code to be like this?
```c++
GlobalThreadPool::Memset(Memory::GetPointer(PSP_GetKernelMemoryBase()), 0, PSP_GetUserMemoryEnd() - PSP_GetKernelMemoryBase());
Memory::Memset(PSP_GetKernelMemoryBase(), 0, PSP_GetKernelMemoryEnd() - PSP_GetKernelMemoryBase(), "MemInit");
Memory::Memset(PSP_GetUserMemoryBase(), 0, PSP_GetUserMemoryEnd() - PSP_GetUserMemoryBase(), "MemInit");
NotifyMemInfo(MemBlockFlags::WRITE, PSP_GetKernelMemoryBase(), PSP_GetUserMemoryEnd() - PSP_GetKernelMemoryBase(), "MemInit");
```
This will get blue screen.
Moving `GlobalThreadPool` to be on top of `NotifyMemInfo` will also get blue screen

> 
> Just in the ini as NumWorkerThreads. So it should be 4 or 8 on your system (you'll likely get best performance with 8 or perhaps 7.) Hmm.
> 
Yes, the default on my ini is 4, changing it to 7 seems to work, but changing it to 8 get blue screen, so probably worked by chances.
I don't think it's a good idea to relies on number of threads to fix this, since different user might have different logical CPU(s).

**Comment by unknownbrackets** [comment]
Sorry I'm just trying to figure out the issue and haven't been able to reproduce anything.  Obviously I wouldn't fix it by changing thread counts, it should work for any number of threads.

In Common/Thread/ThreadPool.cpp, what if you use:
```c++
void ThreadPool::ParallelMemset(void *dest, uint8_t val, int size) {
	static const int MIN_SIZE = 128 * 1024;
	NOTICE_LOG(HLE, "START clearing %p sz=%d to %02x", dest, size, val);
	ParallelLoop([&](int l, int h) {
		memset((uint8_t *)dest + l, val, h - l);
		NOTICE_LOG(HLE, "CLEAR %p %d -> %d to %02x", dest, l, h, val);
	}, 0, size, MIN_SIZE);
	NOTICE_LOG(HLE, "END clearing %p sz=%d to %02x", dest, size, val);
}
```

For me, with 12 threads this logs pretty orderly data.  With 4 threads I get:

```
START clearing 000002B1555C0000 sz=33554432 to 00
CLEAR 000002B1555C0000 25165824 -> 33554432 to 00
CLEAR 000002B1555C0000 0 -> 8388608 to 00
CLEAR 000002B1555C0000 16777216 -> 25165824 to 00
CLEAR 000002B1555C0000 8388608 -> 16777216 to 00
END clearing 000002B1555C0000 sz=33554432 to 00
```

This looks right.  The order doesn't matter, and the end number is exclusive, so we can see this just did 4 parallel memsets of the same size.

I also tried 7, in case something funky was up with an uneven division.  In this case, I've resorted the log so we can verify any gaps or errors:

```
START clearing 000002DB01220000 sz=33554432 to 00
CLEAR 000002DB01220000 0 -> 4793490 to 00
CLEAR 000002DB01220000 4793490 -> 9586980 to 00
CLEAR 000002DB01220000 9586980 -> 14380470 to 00
CLEAR 000002DB01220000 14380470 -> 19173960 to 00
CLEAR 000002DB01220000 19173960 -> 23967450 to 00
CLEAR 000002DB01220000 23967450 -> 28760940 to 00
CLEAR 000002DB01220000 28760940 -> 33554432 to 00
END clearing 000002DB01220000 sz=33554432 to 00
```

No issues, everything ran fine.  I don't see any corruption in memory (unfortunately I don't have this particular game to verify this particular bug.)

It sounds like the order doesn't matter, and if the threaded memset runs, things get corrupted and the game breaks.  My best guesses are:

1. Somehow, the memsets on these threads are touching other memory than they're supposed to.
2. This is not actually the problem, but warming these threads up at memset time changes the later threading order and exposes the bug or makes it much more likely.
3. There's some sort of crazy cache invalidation issue only being exposed on certain devices when using multiple threads here.

The second seems most likely from what I can tell so far.  Does it help at all to go to latest master, clean everything up (i.e. `git stash` any changes), and then revert only e7012f8f886d341ad7fbf9790fe02dabb6a9caec using `git revert e7012f8f886d341ad7fbf9790fe02dabb6a9caec`?  This seems like the next most likely commit to cause problems, if somehow the relocations have interdependencies outside HI16/LO16, or maybe a bug in how I considered HI16/LO16 handling.

-[Unknown]

**Comment by ANR2ME** [comment]
With 4 threads (blue screen) this is the log i get:
```
25:31:315 Thread\ThreadPool.cpp:139 N[HLE]: START clearing 27000000 sz=33554432 to 00
25:31:325 Thread\ThreadPool.cpp:142 N[HLE]: CLEAR 27000000 25165824 -> 33554432 to 00
25:31:325 Thread\ThreadPool.cpp:142 N[HLE]: CLEAR 27000000 8388608 -> 16777216 to 00
25:31:326 Thread\ThreadPool.cpp:142 N[HLE]: CLEAR 27000000 0 -> 8388608 to 00
25:31:326 Thread\ThreadPool.cpp:142 N[HLE]: CLEAR 27000000 16777216 -> 25165824 to 00
25:31:326 Thread\ThreadPool.cpp:144 N[HLE]: END clearing 27000000 sz=33554432 to 00
```

With 7 threads (worked) this is the log i get:
```
32:17:783 Thread\ThreadPool.cpp:139 N[HLE]: START clearing 25C00000 sz=33554432 to 00
32:17:791 Thread\ThreadPool.cpp:142 N[HLE]: CLEAR 25C00000 28760940 -> 33554432 to 00
32:17:791 Thread\ThreadPool.cpp:142 N[HLE]: CLEAR 25C00000 0 -> 4793490 to 00
32:17:791 Thread\ThreadPool.cpp:142 N[HLE]: CLEAR 25C00000 23967450 -> 28760940 to 00
32:17:791 Thread\ThreadPool.cpp:142 N[HLE]: CLEAR 25C00000 9586980 -> 14380470 to 00
32:17:792 Thread\ThreadPool.cpp:142 N[HLE]: CLEAR 25C00000 14380470 -> 19173960 to 00
32:17:792 Thread\ThreadPool.cpp:142 N[HLE]: CLEAR 25C00000 19173960 -> 23967450 to 00
32:17:792 Thread\ThreadPool.cpp:142 N[HLE]: CLEAR 25C00000 4793490 -> 9586980 to 00
32:17:792 Thread\ThreadPool.cpp:144 N[HLE]: END clearing 25C00000 sz=33554432 to 00
```
I'll try reverting that later, i don't have anything else changed other than this `void ThreadPool::ParallelMemset` function.

**Comment by ANR2ME** [comment]
Hmm.. i'm getting conflicts when reverting it
```
git revert e7012f8f886d341ad7fbf9790fe02dabb6a9caec
Auto-merging Core/ELF/ElfReader.cpp
CONFLICT (content): Merge conflict in Core/ELF/ElfReader.cpp
error: could not revert e7012f8f8... Module: Process relocations using unchecked reads.
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
```
I need to use the one without `Unchecked` for this test, right?
And what should i do with this?
```c++
			Memory::WriteUnchecked_U32(op, addr);
			NotifyMemInfo(MemBlockFlags::WRITE, addr, 4, "Relocation");
		}
<<<<<<< HEAD
	}, 0, numRelocs, 32);

=======
		Memory::Write_U32(op, addr);
		NotifyMemInfo(MemBlockFlags::WRITE, addr, 4, "Relocation");
	}
>>>>>>> parent of e7012f8f8 (Module: Process relocations using unchecked reads.)
	if (numErrors) {
		WARN_LOG(LOADER, "%i bad relocations found!!!", numErrors);
	}
	return numErrors == 0;
```
To be like this? This feels wrong...
```c++
			Memory::WriteUnchecked_U32(op, addr);
			NotifyMemInfo(MemBlockFlags::WRITE, addr, 4, "Relocation");
		}
		Memory::Write_U32(op, addr);
		NotifyMemInfo(MemBlockFlags::WRITE, addr, 4, "Relocation");
	}
```

**Comment by unknownbrackets** [comment]
Sorry, let's try reverting 6ee944a0a639d00be24f1f40172673f15ec2fcee and e7012f8f886d341ad7fbf9790fe02dabb6a9caec (you can just put both shas on.)  It's confused because of the indentation.  Doing both should be most likely to find the issue, sorry for my mistake.

-[Unknown]

**Comment by unknownbrackets** [comment]
> Btw, i don't know what this <paths> mean...
> 'git add <paths>' or 'git rm <paths>'

It means, once you have fixed the conflict.  You can just `git reset HEAD` and `git revert --abort` to undo, and then revert both.  It's saying you should `git add Core/ELF/ElfReader.cpp` once the conflict is fixed.

I just realized from your log that this is happening on a 32-bit build.  Is it only happening on 32-bit and not 64-bit?  I have not actually tried 32-bit.

-[Unknown]

**Comment by ANR2ME** [comment]
Okay, i'm using this to revert it
`git revert 6ee944a0a639d00be24f1f40172673f15ec2fcee e7012f8f886d341ad7fbf9790fe02dabb6a9caec`

I was using 64bit when testing it using builds from orphis, but i use 32bit when building locally, both have the same issue.
I'll try building both 32bit and 64bit just to make sure.

**Comment by unknownbrackets** [comment]
Okay, I tried 32-bit and couldn't find any issues on my side.  Strange - sorry just hunting for what could be happening.  Seems really weird.

-[Unknown]

**Comment by ANR2ME** [comment]
Reverting those 2 commits seems to fix this issue (tested on both 32bit and 64bit)
Nice findings! :D

**Comment by unknownbrackets** [comment]
Does #14412 help?

-[Unknown]

**Comment by unknownbrackets** [comment]
I'm assuming it does, so marked this as fixing it.  If it doesn't fix the problem, please still comment and we'll reopen.

-[Unknown]
