### ISSUE TITLE
Test Drive Unlimited not displaying

### ISSUE THREAD

**Issue by telanus** [hrydgard/ppsspp#14415]
### What happens?
When you start Test Drive Unlimited, it'll boot but then show a black screen.

### What *should* happen?
it should boot completely

### Include a GE frame capture
[recording.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/6375752/recording.ppdmp.zip)

#### What hardware / device and operating system?
Dual Core E5300, 4GB ram. 
OS: Kubuntu 18.04.5 64bit

#### What graphics card (GPU) or mobile phone model?
GPU: GeForce GT 630, 
Driver: NVIDIA 390.143 

#### What PPSSPP version (standalone/official), and did it work before?
https://github.com/hrydgard/ppsspp/commit/233b0a87c19ae4e85b5b72cbb5d265a94f6b09ae Self-compiled

#### Which game or games?
ULUS10249 - Test Drive Unlimited

#### Graphics backend (Vulkan, OpenGL, etc.)?
OpenGL, as my system isn't Vulkan capable

#### Checklist
https://pastebin.ubuntu.com/p/3TNQk9K76K/

**Comment by ANR2ME** [comment]
You should try building debug version so that the log can shows debug channel.

**Comment by telanus** [comment]
Also tried it now on my phone, with the same results. loading screen then goes black. Using PPSSPP v1.11.2-540-g8d0ca1e4f

### What are you using?
#### What hardware / device and operating system?
Phone: Samsung Galaxy A2 Core
OS: Android 8.1

#### What graphics card (GPU) or mobile phone model?
GPU: Mali-T830 MP1

#### Graphics backend (Vulkan, OpenGL, etc.)?
I tried Both, Both end up giving the same result

**Comment by telanus** [comment]
> You should try building debug version so that the log can shows debug channel.

Will try building the debug build
