### ISSUE TITLE
Crash of the Titans level 7 end it pauses with a resume button that doesn’t do anything

### ISSUE THREAD

**Issue by SucksAtStuffs** [hrydgard/ppsspp#14419]
### What happens?

At level 7 in crash of the Titans at the tiger guy the game pauses with a resume button that doesn’t work
### What *should* happen?
It’s supposed to play a cutscene 

#### What hardware / device and operating system?
windows 10 
With an Acer laptop that has a intel i3

#### What graphics card (GPU) or mobile phone model?
I don’t know what GPU it is but it also does it on my desktop that has a GTX 1080

#### What PPSSPP version (standalone/official), and did it work before?
1.11.3

#### Which game or games?

Crash of the Titans ULUS10304

#### Checklist

 - [X ] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [X ] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [ X] Try resetting settings or older versions and include if the issue is related.
 - [ X
![C4E9ED3E-11DE-4DC4-9B42-C2D5C1062886](https://user-images.githubusercontent.com/83475732/116751136-e0ea3000-aa03-11eb-8b89-ba2fea547f34.jpeg)
] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment]
Is this happening recently? if it is, can you findout which build was the last working version from https://buildbot.orphis.net/ppsspp/index.php?m=fulllist

Btw, if you disable Fast Memory will it get blue screen?

Also, can you run `DebugLog.bat` to play this game, so that it will generate `ppsspplog.txt`. 
You can zip that file and upload it here, so the devs can investigate the logs.

**Comment by SucksAtStuffs** [comment]
I don’t know if it’s recent but every time I’ve tried to get past there it does that and how do I disable fast memory

**Comment by SucksAtStuffs** [comment]
> Is this happening recently? if it is, can you findout which build was the last working version from https://buildbot.orphis.net/ppsspp/index.php?m=fulllist
> 
> Btw, if you disable Fast Memory will it get blue screen?
> 
> Also, can you run `DebugLog.bat` to play this game, so that it will generate `ppsspplog.txt`.
> You can zip that log file and upload it here, so the devs can investigate the logs.


I don’t know if it’s recent but every time I’ve tried to get past there it does that and how do I disable fast memory

**Comment by ANR2ME** [comment]
Fast memory is at PPSSPP's System settings

**Comment by SucksAtStuffs** [comment]
> Fast memory is at PPSSPP's System settings.
> 
> Disable it, and run DebugLog.bat (which is located at the same folder with PPSSPP exe) to generate log file

I disabled it but I can’t find the debug log.bat

**Comment by ANR2ME** [comment]
If you're using the latest version from https://buildbot.orphis.net/ppsspp/index.php?m=fulllist
There should be DebugLog and InfoLog in ppsspp folder.
![image](https://user-images.githubusercontent.com/7974720/116760035-14e24700-aa3e-11eb-8d13-bb7c121f474a.png)

Btw, is this happening when you're loading from SaveState? or loading it from memory stick will also have the same issue?

**Comment by SucksAtStuffs** [comment]
> If you're using the latest version from https://buildbot.orphis.net/ppsspp/index.php?m=fulllist
> There should be DebugLog and InfoLog in ppsspp folder.
> ![image](https://user-images.githubusercontent.com/7974720/116760035-14e24700-aa3e-11eb-8d13-bb7c121f474a.png)
> 
> Btw, is this happening when you're loading from SaveState? or loading it from memory stick will also have the same issue?

I tried with save state and memory stick and yes it happens also does 1.11.3 count as the newest version

**Comment by ANR2ME** [comment]
It's better to use the latest version (ie. `v1.11.3-574-g8c72cc119`) to find out whether it got fixed or not, it might be similar issue to the cutscene on Yu-gi-oh game that got fixed recently.

**Comment by SucksAtStuffs** [comment]
> It's better to use the latest version (ie. `v1.11.3-574-g8c72cc119`) to find out whether it got fixed or not, it might be similar issue to the cutscene on Yu-gi-oh game that got fixed recently.

I will try that also just to be sure when you save a game it saves within the iso file right?

**Comment by ANR2ME** [comment]
No, savedata is stored in `\ppsspp\memstick\PSP\SAVEDATA` folder, you can find the game title id in there.
You can zip the game title id folder and upload here for the devs to test it.

**Comment by SucksAtStuffs** [comment]
> No, savedata is stored in `\ppsspp\memstick\PSP\SAVEDATA` folder, you can find the game title id (ie. ULUS10304) in there.
> You can zip the game title id folder and upload here for the devs to test it.

[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/6408395/ppsspplog.zip)
i downloaded the new version and here is the log file ill see if the issue is still there

**Comment by SucksAtStuffs** [comment]
> No, savedata is stored in `\ppsspp\memstick\PSP\SAVEDATA` folder, you can find the game title id (ie. ULUS10304) in there.
> You can zip the game title id folder and upload here for the devs to test it.

It worked the cutscene was a little broken but it at least didn’t freeze

**Comment by ANR2ME** [comment]
You should upload it after you managed to get to the issue, so it will logs the problem

**Comment by SucksAtStuffs** [comment]
> You should upload it after you managed to reach the issue, so it will logs the problem

The issue was gone tho

**Comment by ANR2ME** [comment]
I see, it might be similar issue to Yu-gi-oh 1 & 2 game https://github.com/hrydgard/ppsspp/issues/14400
