### ISSUE TITLE
Deleting ppdmp files inside ppsspp can cause crash

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#14428]
![Screenshot_2021-05-03-20-51-59-832_com mi android globallauncher](https://user-images.githubusercontent.com/37603562/116878359-ce653600-ac51-11eb-84f6-b9a716e8459d.jpg)

My phone is Redmi Note 9 Android 10 with Mediatek Helio G85 and Mali G52 MC2 GPU.

**Comment by Panderner** [comment]
Are you using older version of PPSSPP? I deleted the ppdmp files inside /PSP/SYSTEM/DUMP Works fine and doesn't crash.

**Comment by Gamemulatorer** [comment]
Im using latest git build but it appears now that it didn't crash again maybe just a random crash so closing..

**Comment by unknownbrackets** [comment]
That's odd.  If you see it again, a crash log from adb logcat might be really helpful.

-[Unknown]
