### ISSUE TITLE
Brave Story New Traveler slow down during fight scene on my Redmi Note 9

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#14426]
### What games and where in them does it happen?

Brave Story New Traveler ULUS10279

### What speed are you getting with PPSSPP speed display enabled?
15 - 20 fps during the fight scene and main menu on OGL but in VK only happen on fight scene using default settings.
![Screenshot_2021-05-02-16-30-09-390_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/116807335-4144b300-ab65-11eb-8ebe-9cc589b847e7.jpg)
![Screenshot_2021-05-02-15-56-36-882_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/116807338-443fa380-ab65-11eb-8061-2163de2b7f5d.jpg)

### Include a GE frame capture and debug stats

[ge dump.zip](https://github.com/hrydgard/ppsspp/files/6411016/ge.dump.zip)

#### What hardware / device and operating system?
Android 10 Helio G85 2.0Ghz Octacore
#### What graphics card (GPU) or mobile phone model?
Mali G52 MC2 1.0Ghz
#### What PPSSPP version (standalone/official), and did it work before?
Tried in ppsspp playstore version and the latest git build same issue
#### Graphics backend (Vulkan, OpenGL, etc.)?
Vulkan and OpenGL
#### Checklist

 - [✓ ] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [✓ ] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [ ✓] Try resetting settings or older versions and include if the issue is related.
 - [✓ ] Try changing graphics settings to determine if one causes the slowdown.
 - [✓ ] Include logs of screenshots of issue.

**Comment by Panderner** [comment]
@Gamemulatorer are you using 1x resolution in this screenshot?

**Comment by Gamemulatorer** [comment]
> @Gamemulatorer are you using 1x resolution in this screenshot?

X1 resolution improve a little bit but still lag
![Screenshot_2021-05-02-17-27-12-818_org ppsspp ppssppgold](https://user-images.githubusercontent.com/37603562/116808518-d054c980-ab6b-11eb-9124-8d503c093751.jpg)

**Comment by ANR2ME** [comment]
Is this performance issue consistently happening (ie. can always be reproduced) or it's happening occasionally/randomly?

I remembered getting FPS slowdown on a few games (MH 3rd HD, DBZ TTT, GTA VCS) on WIndows but it happened randomly and couldn't be reproduced at will.

For example what happened on MH 3rd HD, the game was running full speed up to loading save data, but once the character entered the village/town the FPS dropped and making the movement look like a slow motion for the rest of the game play.
But this happened only once and i haven't been able to reproduce it, but similar things happened on other games, so i wondered if it's related to the slowdown you're having.

**Comment by Gamemulatorer** [comment]
> Is this performance issue consistently happening (ie. can always be reproduced) or it's happening occasionally/randomly?
Always happen during the fight scene :(

**Comment by ANR2ME** [comment]
Being able to reproduce it is nice, so now we just need to find out since when is this happening :)
Do you know which build was the last working version?

**Comment by Gamemulatorer** [comment]
I tried ppsspp v1.9, v1.10 and v1.11 still lag I will try the old version tomorrow.

**Comment by Gamemulatorer** [comment]
Some of my games also lag like FMA brotherhood and POP Forgetten Sand both OGL and VK.

**Comment by Gamemulatorer** [comment]
In PPSSPP v1.0 this game is super smooth on battle scene.
![Screenshot_2021-05-03-20-01-14-307_org ppsspp ppssppgold](https://user-images.githubusercontent.com/37603562/116873607-8f7fb200-ac4a-11eb-9899-5210682f13e7.jpg)

**Comment by Gamemulatorer** [comment]
My issue solve by doing this :)
![Screenshot_2021-05-08-20-07-49-301_com android chrome](https://user-images.githubusercontent.com/37603562/117538560-588a1180-b039-11eb-9b6f-b99998140aad.jpg)
So this is Confirmed Driver Bug
