### ISSUE TITLE
Moving the finger from an empty area in the screen onto the DPAD doesn't work

### ISSUE THREAD

**Issue by Leopard20** [hrydgard/ppsspp#14429]
For every key, it is possible to touch and hold on an empty area in the screen and move the finger onto a key and the key fires.

This is not the case with the DPAD keys. If you miss the key, you'll have to lift your finger and put it back again.

**Comment by radityaargap** [comment]
with the latest version, you can now achieve the same result by making custom buttons and set them up to look like the dpads. i made a quick showcase here. regular dpads on the right and custom buttons on the left.

https://user-images.githubusercontent.com/79243430/132972153-4f26764c-5e78-4e40-af5d-a28838969b20.mp4

**Comment by Leopard20** [comment]
no

**Comment by radityaargap** [comment]
well, please explain what the problem is then. so that people can help.

**Comment by hrydgard** [comment]
I think he did explain the problem pretty well, and it's real.

**Comment by iota97** [comment]
I think this should be address like this:
- make the dpad accept input when finger get dragged into it (this should be really easy)
- make any input dragging an analog not activating any other button (on small device this bug was a life saver with default config)
