### ISSUE TITLE
Should default some Android TV devices to OpenGL

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#14439]
Or maybe should we default on all Android TV devices?

I've collected the following that does not seem to work with Vulkan (black screen):

```
Sony:BRAVIA VH1
```

(more to be added as we find them)

**Comment by MojoJojoDojo** [comment]
IMO all Android TV devices should default to OpenGL.
Most of then even use a 32 bit os and for the most part they are weak devices comparably.

**Comment by unknownbrackets** [comment]
Since we now default to OpenGL for a lot of older devices, in 37b78fd, is this still an issue?  Doesn't seem like it's really come up in a while.

-[Unknown]

**Comment by hrydgard** [comment]
Let's close this for now, reopen if any reports come in.
