### ISSUE TITLE
ppsspp with a PSP UI

### ISSUE THREAD

**Issue by uwuAngelo** [hrydgard/ppsspp#14432]
### What should happen?
ppsspp should be able to mimic the UI of an actual psp (with sound effects and stuff) to achieve a more immersive experience

### Who would benefit from it?
players

#### Checklist

 - [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
 - [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
This has been brought up many times, and the reason PPSSPP is not mimicking the PSP UI, besides possible legal reasons like the patent on XMB, is that it's just not a good UI for touch and mouse, it's only really suitable for gamepad. And PPSSPP's UI is meant to be the same everywhere, so it won't work.
