### ISSUE TITLE
Up not working for SN30 Pro+, both D-Pad and Analog, when in Android mode/B-input

### ISSUE THREAD

**Issue by bbilford83** [hrydgard/ppsspp#14449]
Hi All,

Brand new to github, apologies if I leave anything out.

### What happens?

Both in-menu and in-game, my SN30 Pro+ won't let me use the Up D-pad button or the Analog Stick pushed up.

### What *should* happen?

Uh, I should be able to push up :).

### What are you using?

PPSSPP (maybe I am misunderstanding the question).

#### What hardware / device and operating system?

Raspberry Pi4B with 4GB ram, SN30 Pro+, Retropie.

#### What PPSSPP version (standalone/official), and did it work before?

Standalone, still works.

#### Which game or games?

All.

#### Checklist

 - [ X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [ X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [ X] Try resetting settings or older versions and include if the issue is related.
 - [ ] Include logs or screenshots of issue.

Other info: I found lots of folks dealing with the SN30 Pro+ not being properly mapped by PPSSPP when in Android mode (like, with nothing mapped right at all, d-pad not working).  It apparently works better in Windows mode, but Retropie seems to really not like that (it creates huge load times for each game).   I thought I'd found a solution to make it work in Android mode by searching specifically for the GUID and replacing that in my gamecontrollerdb.txt file.  This is what I put in there:

05000000c82d00000261000000010000,8BitDo SN30 Pro+,a:b1,b:b0,back:b10,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b12,leftshoulder:b6,leftstick:b13,lefttrigger:b8,leftx:a0,lefty:a1,rightshoulder:b7,rightstick:b14,righttrigger:b9,rightx:a2,righty:a3,start:b11,x:b4,y:b3,platform:Linux,

Unfortunately, that's where I'm stuck.  I confirmed in the es_input.cfg file that, at least for the D-pad, this should be right.  It lists up as 1 (and the others all track the numbers above).  Any help would be much appreciated - I'm new to this but really don't want to switch to lr-ppsspp for reasons that are probably obvious.

TIA!

**Comment by bbilford83** [comment]
All, I figured out my problem.  I had apparently tried to map up at some point in the internal mapping system and screwed it up. That mapping reflects in the controls.ini file located at \\retropie\configs\psp\PSP\SYSTEM. Deleting those files, uninstalling, and reinstalling PPSSPP, THEN doing what I typed above (replacing the SN30 Pro+ entry in the controller file) solved all my problems.

**Comment by unknownbrackets** [comment]
Ah - thanks for noting the solution here.

-[Unknown]
