### ISSUE TITLE
Gamepad stopped working in rom

### ISSUE THREAD

**Issue by Dragotiger** [hrydgard/ppsspp#14459]

**Comment by unknownbrackets** [comment]
Make sure the control mapping settings are set the way you want.

Even if you delete those, some of the mappings are forced in the menu.  When you go into the game, it stops forcing them.  That's probably the issue.

-[Unknown]

**Comment by unknownbrackets** [comment]
Is this working fine now?

-[Unknown]

**Comment by Dragotiger** [comment]
Yep, Should be all good besides this is an old post
