### ISSUE TITLE
Ad-hoc netplay bug between androids in TF/RK

### ISSUE THREAD

**Issue by samosaphile** [hrydgard/ppsspp#14452]
### What happens?
In yu gi oh gx tag force 1 (probably applies to rest of other tag force games too on psp) when both players are online in ad-hoc mode. There is a message error, data coming from incorrect port, the standard ppsspp error message. We also cannot see each others games, whether I host them or the player on other end.
Similar behaviour is observed in Rurouni Kenshin games aswell. Please note that this issue only seems to effect when both players are on mobile android. If one is on a Windows PC ppsspp build, it works fine then no issues.
### What *should* happen?
We should be able to see hosted games and join them. There should not be any data from incorrect port error either. Android-to-android should work just like windows-to-android.

#### What hardware / device and operating system?
Pixel 4a. StockOS (android 11).
#### What graphics card (GPU) or mobile phone model?
Sunfish. Adreno 618.
#### What PPSSPP version (standalone/official), and did it work before?
1.11.2-432 Dev build, and it only works when one client / user is on an x86 build (windows, Linux, etc).
#### Which game or games?

It's the USA version. (Well for tag force 1)
The other game, rurouni kenshin is japan only region anyway.
#### Checklist

 - [ ] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [ ] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [ ] Try resetting settings or older versions and include if the issue is related.
 - [ ] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment]
Have you tried using Port Offset 10000 ?
I think this kind of thing could happen when you're using Port Offset 5000 or lower

**Comment by samosaphile** [comment]
Forgot to take a screenshot when I did this test, so don't recall the exact numbers in the error. I think it was something like 13000ish -> 1. I used port 2500 and 1500 (same problem for both)

In tag force 1, I didn't (or maybe I did long ago but can't remember) try higher port numbers because usually when I did try doing this, it doesn't help. The only few situations I saw this helping is when someone behind a NAT / firewall / something blocking ports - so they need to use a VPN like ZeroTier. In these cases, using a high enough port helped resolve the connection issues. 

I believe I've tested Rurouni Kenshin games at 10k and 60k ports. 60k port did fix issue. But again it was when the other player was on pc only. So it was android-to-pc. When other player went on android, it failed even at 60k and 10k.

I think you're spot on about the binding to random ports causing confusion and happening occasionally randomly. Because I notice certain games where I was once able to connect to a player (whom I usually always connect to) and then another day, I can't connect to the very same person at all. There was no change on either of our setups. This sometimes happens to me in Tekken 6 but also sometimes in Rurouni Kenshin games. (And probably many other games too, in my testing I had more issues with RK2 than RK1 but unsure if I'm just imagining things and need to do further tests. It's kinda hard tho as there's barely anyone who has this or even wants to play this game as it's all in Japanese, there is a language barrier)

I will try to get back to you, after doing some more testing and provide more details on exact error message numbers.

**Comment by ANR2ME** [comment]
Yeah, it's an issue i haven't figured out what actually happening, one thing i know is that the one having the issue is the sender (based on wireshark logs).
At first i thought it only happened when sending data from Android to PC(Win10) because that message never appeared on Android side, but later i found out it also happening on Win7 vs Win10.

**Comment by MojoJojoDojo** [comment]
My friend got it when he played GTA with someone.
He uses Win8 while the other uses Linux.
Even port offset 10k didn't help.

**Comment by samosaphile** [comment]
So the guy I was playing with these games with has recently gone AWOL and dunno what happened to him or if he coming back. 

So far I've tested tag force 1 with someone else (also on android) and I didn't get the error anymore. And it actually did work. (Used port 2500)

Not sure what going on exactly, maybe that previous guy just had issues. Or maybe just was my lucky day today with ports binded correctly...

I'll test tomorrow hopefully the Rurouni Kenshin games with someone, see how that goes.

P.S.: forgot to mention when we did tag force 1 test today, when the other player hosted I was unable to join his game. However, when I hosted everything worked smoothly. I am unable to confirm if this is actually a real issue tho, as maybe his router was acting up, which happens and quite common too. Will try to do some more testing, maybe try and see if I am able to join his hosted games on higher ports (10k, 60k) tomorrow.

**Comment by ANR2ME** [comment]
Btw, using too high Port Offset like 60k might be a bad idea on some games (ie. PSP2/PSP2i) because such games already used a high port originally (above 20k as i remembered), and ports range are 0 to 65535 (a total of 65536 ports) on most/all OS, thus adding the original with a high port offset could ended with restricted/reserved port (0 to 1023)

For example, if original port is 6000 with port offset 60000 the resulting port will be 66000, since the highest number a 16-bit port can fit is 65535, it will ended with `port 66000 modulo 65536 = port 464`

**Comment by MojoJojoDojo** [comment]
Games that got both infrastructure mode as well as adhoc use ports that are high relatively (i guess same ports as infra).
Also they are sometimes good to play without UPNP or VPN if at least 1 player is hosting with UPNP (sometimes without it at all).

**Comment by samosaphile** [comment]
I'm not sure what to do with this post/thread. I thought these games had issues but it seems they're sensitive to people who just have crap routers. 

A friend who I was having issues with earlier on TF 1 with android-2-android, after he made some changes to his router. I could play with him and no longer get data coming from incorrect port error.

I discovered another bug in tag force 1 tho (but it's not a online ad-hoc netplay specific one) and happens offline too. 

![Screenshot_20210522-184159](https://user-images.githubusercontent.com/30265284/119277792-89fa0400-bc19-11eb-9c58-b9d01c3932e9.png)
![Screenshot_20210521-195549](https://user-images.githubusercontent.com/30265284/119277804-a0a05b00-bc19-11eb-985a-923f25720010.png)
![Screenshot_20210521-204237](https://user-images.githubusercontent.com/30265284/119277826-bca3fc80-bc19-11eb-8e62-7a873a52e113.png)

The above screenshots are where the game seems to quite commonly get stuck in a loop. Sometimes it's when attacking the opponent. Other times when selecting a card from graveyard or something. Pretty random. 

I still get issues with some people in these games but the people I do, I seem to have issues in many games. So it might be just them. The wierd thing is, some games do work with them. I've a friend who I can't play any other games with except hot shots golf open tee 1. Idk how that's even possible.

**Comment by samosaphile** [comment]
Another thing which I see quite often is in network chat, it'll display "PPSSPP" twice or sometimes 4x. Is this a bug? I'm quite sure I've changed my name in ppsspp settings. And I'm quite sure my friends have on their side aswell. (Because in some games ive seen it correctly display our names with no "ppsspp" showing) but I see this quite often and it's kinda annoying. (Especially when it starts to spam chat with like 8x "ppsspp" displayed). 

This isn't a bug specific to these games tho and happens in any and all...

**Comment by ANR2ME** [comment]
May i know what kind of changes did your friend made to his router? We might be able to find some clue what's causing this incorrect port issue from his changes.

Regarding the issue on single player, you can submit a separate issue and tell us how to reproduce it.

Regarding the chat issue, it was ported from https://github.com/adenovan/amultios-ppsspp/commits/rechat which is quite old (early stage of chat implementation) and nobody is maintaining it on official PPSSPP.
@adenovan might have a newer/better chat feature on amultios by now, but unfortunately it's no longer compatible with official PPSSPP.

**Comment by EX-e-LD** [comment]
Hi,me again.I'm friend that @samosaphile is playing with most of time.

Interesting thing is,restarting fixes this error,but i think my public IP has something to do with it,since delays are not happening.

**Comment by samosaphile** [comment]
@ANR2ME 

The very same issue that happens in offline single player also happens on online ad-hoc netplay, so it's okay to report here no? If not, guess I'll make another thread then.

And I've no idea how to reproduce it, seems like something that happens pretty randomly. (Another possible random race condition maybe?)

**Comment by samosaphile** [comment]
This issue can be closed now.  After further testing I was able to get both TF games working and RK1 too. RK2 seemed most problematic and buggy but tested today and it worked.

**Comment by MajinDipu** [comment]
Bruuuh, you closed already? Coz RK2 still doesn’t work android to android :(

**Comment by MojoJojoDojo** [comment]
> May i know what kind of changes did your friend made to his router? We might be able to find some clue what's causing this incorrect port issue from his changes.

Too bad he never actually told what he did with the router lol.
Could be something similar here that I got with the firewall though:
![image](https://user-images.githubusercontent.com/33392696/126889397-2ee718c1-52e5-43b8-9af9-e573f3bf9d0c.png)

**Comment by samosaphile** [comment]
Tf1 with @itsXPCT  was a uPnP issue related I think. 

RK2 is just a buggy game. I don't think I ever got this to work with ppl I had connection issues with in past, only people who I never have issues with. So it wasn't really a change so much as, just doing it with right people (and keep trying repeatedly, kinda like Def jam decline bug)

**Comment by ANR2ME** [comment]
Router have a firmware, and the UPnP feature is a part of the firmware, you may need to update your firmware if your router is having an issue.
