### ISSUE TITLE
UDP Hole punching 

### ISSUE THREAD

**Issue by samosaphile** [hrydgard/ppsspp#14454]
#### Checklist

 - [ ] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
 - [ ] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by MojoJojoDojo** [comment]
To be honest if you are on Windows etc you got this software you can use:
https://autopunch.delthas.fr/
Source code could be found here:
https://github.com/delthas/autopunch
So someone could use it to get hole punching to work but I never tried it myself.

**Comment by ANR2ME** [comment]
Someone at socom.cc is working on a new Adhoc Server implementation, which have STUN feature, where STUN is using hole punching.

**Comment by samosaphile** [comment]
Is there anyway I can reach or contact this person?

**Comment by ANR2ME** [comment]
> 
> 
> Is there anyway I can reach or contact this person?

@Linblow is the owner of socom.cc

**Comment by samosaphile** [comment]
Can close this issue. I did talk with @Linblow recently on discord. And yep, he's working on a bunch of stuff.
