### ISSUE TITLE
Trying to run the latest PPSSPP dev build on Linux will yield a "Floating Point exception"

### ISSUE THREAD

**Issue by MojoJojoDojo** [hrydgard/ppsspp#14450]
### What happens?

PPSSPP shows this error : "Floating point exception (core dumped)"
### What *should* happen?
PPSSPP should run fine.

#### What hardware / device and operating system?
OS:Linux Pop OS latest LTS distro
#### What graphics card (GPU) or mobile phone model?
Radeon 530 and Intel UHD 620
#### What PPSSPP version (standalone/official), and did it work before?
Latest stable PPSSPP should work fine.
#### Which game or games?

not relevant

#### Checklist

 - [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [X] Try resetting settings or older versions and include if the issue is related.
 - [ ] Include logs or screenshots of issue.

**Note: Used the Github Actions binary and didnt compile it from source.**

**Comment by unknownbrackets** [comment]
Which commit specifically - do you mean the sin/cos changes?  Is this before any UI?

-[Unknown]

**Comment by MojoJojoDojo** [comment]
Yeah the sin/cos changes.
Before it it worked fine.
