### ISSUE TITLE
Kao Challengers causes emulator to crash after host leaves the ad-hoc room - 1.11.3

### ISSUE THREAD

**Issue by EX-e-LD** [hrydgard/ppsspp#14463]
Witnessed and tested by @[deleted] (me) @ocn and @RageXbox on PPSSPP Discord
Wanted to report it since obviously wasn't reported before

### What happens?
That's the problem.Whenever someone who joined the game (guest) left,they would
get back on title screen.If host leaves his party either to title screen or lobby,PPSSPP
automatically crashes.

### What *should* happen?
Host should leave in-game without having his emulator crashed

### What are you using?
I used:
Honor 9S
GPU - PowerVR GE8320
CPU - Mediatek Helio P22
PPSSPP is 1.11.3

PC
GPU - Intel (R) HD Graphics
PPSSPP 1.11.3

ocn used:
PPSSPP 1.11.2.432 devbuild
#### What hardware / device and operating system?
PC
GPU - Intel (R) HD Graphics
Windows 8.0

Honor 9S
GPU - PowerVR GE8320
Android 8.1.0
#### What PPSSPP version (standalone/official), and did it work before?
Game wasn't even fixed before 1.11.3 because of BSOD error that @ANR2ME fixed
#### Which game or games?

Kao Challengers
ULUS10085
USA

#### Checklist

 - [x] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [x] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [x] Try resetting settings or older versions and include if the issue is related.
 - [ ] Include logs or screenshots of issue.

**Comment by MojoJojoDojo** [comment]
I think thats the crashing issue that got fixed by a later dev build.
on 1.11.3 the crashing issue is still there.

**Comment by EX-e-LD** [comment]
@MojoJojoDojo Well,i close this or what @unknownbrackets

**Comment by MojoJojoDojo** [comment]
You should always test on latest dev builds to be sure there are no issues.

**Comment by EX-e-LD** [comment]
I will,just in case.You think or you know that crashing got fixed @MojoJojoDojo

**Comment by MojoJojoDojo** [comment]
Try and see.
I know that problem existed in 2 games but @ANR2ME fixed it already.

**Comment by MojoJojoDojo** [comment]
.Its this issue btw https://github.com/hrydgard/ppsspp/issues/14337

**Comment by EX-e-LD** [comment]
UPDATE:Tested on latest build,not fixed at all,and game crashes instantly

**Comment by MojoJojoDojo** [comment]
Yeah seems to happen still at least on Windows 10.

**Comment by ANR2ME** [comment]
By "crash" did you mean a blue screen?

May i know how to reproduce this crash i step-by-step on what should i choose? the last time i tested this (yesterday) i didn't see any blue screen

**Comment by ANR2ME** [comment]
Please try again after PR https://github.com/hrydgard/ppsspp/pull/14466 got merged, or you can use the artifact from that PR to test

**Comment by EX-e-LD** [comment]
Doesn't crash anymore,thanks man
