### ISSUE TITLE
Both analog sticks not working for dualshock 3 on v1.11.3

### ISSUE THREAD

**Issue by feiplane** [hrydgard/ppsspp#14461]
### What happens?
The newest android v1.11.3 version does not recognize both analog sticks of dualshock 3.

### What *should* happen?
All other buttons have no issue to register just both the analog sticks no response at all.

### What are you using?
Ppsspp v1.11.3 with Dualshock 3 controller

#### What hardware / device and operating system?
Poco X3 Pro (Snapdragon 860) 8/256
Android 11

#### What graphics card (GPU) or mobile phone model?
Poco X3 Pro (Snapdragon 860/adreno 640)

#### What PPSSPP version 
v1.11.3 android, not so sure if worked in the past

**Comment by feiplane** [comment]
solution found, just toggle on/off accessibility will do the trick, solved

**Comment by unknownbrackets** [comment]
Yeah this is a known Android bug right now, unfortunately.

-[Unknown]
