### ISSUE TITLE
Can't compile as libretro core on RPi 4

### ISSUE THREAD

**Issue by vjarskee** [hrydgard/ppsspp#14477]
### What platform, compiler, and build tools?
Retroarch on Raspbian

### What happens (don't forget logs)?
```
[ 56%] Building CXX object CMakeFiles/Core.dir/GPU/Common/ShaderUniforms.cpp.o
/tmp/ccZsGHcE.s: Assembler messages:
/tmp/ccZsGHcE.s:37: Error: selected processor does not support `movw r0,0xc00b' in ARM mode
/tmp/ccZsGHcE.s:38: Error: selected processor does not support `movt r0,0x9bd9' in ARM mode
/tmp/ccZsGHcE.s:39: Error: selected processor does not support `movw r1,0x4b73' in ARM mode
/tmp/ccZsGHcE.s:40: Error: selected processor does not support `movt r1,0xb651' in ARM mode
/tmp/ccZsGHcE.s:42: Error: selected processor does not support `movw r0,0x4d9b' in ARM mode
/tmp/ccZsGHcE.s:43: Error: selected processor does not support `movt r0,0x4309' in ARM mode
/tmp/ccZsGHcE.s:44: Error: selected processor does not support `movw r1,0x0083' in ARM mode
/tmp/ccZsGHcE.s:45: Error: selected processor does not support `movt r1,0x0001' in ARM mode
/tmp/ccZsGHcE.s:47: Error: selected processor does not support `movw r0,0x2455' in ARM mode
make[2]: *** [CMakeFiles/Core.dir/build.make:3209: CMakeFiles/Core.dir/GPU/Common/TextureDecoderNEON.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:689: CMakeFiles/Core.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

### What are you using?
RPi 4, Raspbian 10

**Comment by unknownbrackets** [comment]
https://github.com/hrydgard/ppsspp/blob/master/GPU/Common/TextureDecoderNEON.cpp#L44

Sounds like it's somehow causing PPSSPP_ARCH_ARMV7 to be defined.  What compile flags / command are you using?

-[Unknown]

**Comment by vjarskee** [comment]
> https://github.com/hrydgard/ppsspp/blob/master/GPU/Common/TextureDecoderNEON.cpp#L44
> 
> Sounds like it's somehow causing PPSSPP_ARCH_ARMV7 to be defined. What compile flags / command are you using?
> 
> -[Unknown]

./b.sh --libretro

**Comment by i30817** [comment]
I'm not sure about this because it's been a while since i built ppsspp but i think i recall you shouldn't use the cmake build file for libretro but the one inside the libretro dir only. For instance i use (checks):

    make -j2 DEBUG=[0 or 1] DYNAFLAGS="-DHAVE_OPENGL_CORE"

for opengl and

    make -j2 DEBUG=[0 or 1] DYNAFLAGS="-DUSING_GLES2"

for GLES devices.

**Comment by gouchi** [comment]
FWIW, this is how we [compile PPSSPP libretro core](https://github.com/libretro/Lakka-LibreELEC/blob/master/packages/libretro/ppsspp/package.mk) on Lakka using CMake. No compilation issue so far.

**Comment by unknownbrackets** [comment]
Are you trying to build an older version, or the latest git?

Does it help to add the arch flag like Lakka does?  It shouldn't be needed.
https://github.com/libretro/Lakka-LibreELEC/blob/master/packages/libretro/ppsspp/package.mk#L69-L73

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
