### ISSUE TITLE
Texture replacement glitch (Android)

### ISSUE THREAD

**Issue by Saramagrean** [hrydgard/ppsspp#14485]
### What happens?

![Screenshot_20210528-204655829](https://user-images.githubusercontent.com/26355472/119993714-129bea00-bff6-11eb-8947-a1af8ba48e81.jpg)

Since v1.11.3-677-g5fa1af6ef and up, when enabled texture replacement (use texture pack), it show graphic glitches. if texture pack convert to zims, graphics is fine. this issue happen on Android only

### What *should* happen?

![Screenshot_20210528-195504645](https://user-images.githubusercontent.com/26355472/119993753-1e87ac00-bff6-11eb-859b-51cb2a411dab.jpg)

Graphics rendering correct when use texture pack

#### What graphics card (GPU) or mobile phone model?

- Redmi Note 8 (Snapdragon 665, Adreno 610, Ram 3, Android 11) 
- Redmi Note 9S (Snapdragon 720, Adreno 618, Ram 4, Android 11)

#### What PPSSPP version (standalone/official), and did it work before?
- Last work: v1.11.3-672.

#### Which game or games?
- Everygame if use texture pack.

#### Graphics backend (Vulkan, OpenGL, etc.)?
- Happen on both OpenGL/Vulkan.

**Comment by LunaMoo** [comment]
Does the label "GE emulation" really fits this? It's just a broken PNG decode on android after libpng17 update.

 Might be something to do with NEON optimization as there seem to be a lot of mentions of that within the updated files, would explain why it works fine on PC.

**Comment by unknownbrackets** [comment]
If that's the cause, adding `-DPNG_ARM_NEON_OPT=0` here:
https://github.com/hrydgard/ppsspp/blob/master/CMakeLists.txt#L274

Might prevent it from using the NEON optimizations.

https://github.com/hrydgard/ppsspp/blob/master/ext/libpng17/arm/neon.h#L35

-[Unknown]

**Comment by unknownbrackets** [comment]
Reopening - we should confirm if #14501 fixed this.  If so, it may be needed on non-Android ARM as well.

-[Unknown]

**Comment by Saramagrean** [comment]
Comfirm, It fixed.

**Comment by unknownbrackets** [comment]
Thanks for confirming, I'll close again then.  Added a small change as well to disable NEON on iOS / Linux ARM too.

-[Unknown]
