### ISSUE TITLE
Fading Shadows - Game stucks in loop while in Ad-Hoc session - 1.11.3

### ISSUE THREAD

**Issue by itsXPCT** [hrydgard/ppsspp#14487]
Hi,me again,with new bug that i thought could be useful being reported
(Forgot Screenshots,will post them later)
### What happens?
Game gets stuck in loop when joining / hosting Ad-Hoc session

### What *should* happen?
Game shouldn't be stuck in loop

#### What hardware / device and operating system?
Honor 9S
CPU:Mediatek Helio P22
GPU:PowerVR GE8320

PC
GPU:Intel (R) HD Graphics
CPU:Intel Pentium N3520 - 2.16Ghz
#### What graphics card (GPU) or mobile phone model?
Honor 9S - PowerVR GE8320
PC - Intel (R) HD Graphics
#### What PPSSPP version (standalone/official), and did it work before?
1.11.3 on both devices
#### Which game or games?

Fading Shadow
ULUS10344
USA

#### Checklist

 - [x] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [x] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [x] Try resetting settings or older versions and include if the issue is related.
 - [ ] Include logs or screenshots of issue.
 

**NOTE**
- tested UMD Delay
- de-sync doesn't appear to impact loop
- tried CPU CLOCK SPEED - 100
- backend doesn't seem to impact it
- tried freezing thinking this was Atrac3+ bug,it is not

TIA

**Comment by MojoJojoDojo** [comment]
Game last worked at version 1.10.3-712 apparently.
So in-between that and 1.11.3 and up something happened I guess.

**Comment by ANR2ME** [comment]
Hmm this game is using GameMode and it seems it uses different buffer size on Master (ie. Sender) and Replica (ie. Receiver), thus one of them unable to receive the packet as it's bigger than it's buffer size.

Currently, i'm using a single socket for sending and receiving because most of the games i've tested GameMode with are using the same buffer size for Master and Replica.
If there are games that use different buffer size like Fading Shadows.. i guess i'll need to use a separate socket for sending and receiving data.

**Comment by MojoJojoDojo** [comment]
Well I only tried over a public server and it worked there.
Curious.

**Comment by ANR2ME** [comment]
@EX-e-LD could you try the artifact from PR https://github.com/hrydgard/ppsspp/pull/14492 to see if it fixed the issue or not on your side?

But i don't think there is android version on the artifacts https://github.com/hrydgard/ppsspp/pull/14492/checks?check_run_id=2706178823

**Comment by MojoJojoDojo** [comment]
That PR fixes it so I dunno why its not merged yet.
Hopefully it does not affect other GameMode games tho lol.

**Comment by itsXPCT** [comment]
@ANR2ME This fixes it,thank you!!

@MojoJojoDojo Try some game that uses it and report the rest so i can close it up!

TIA

**Comment by MojoJojoDojo** [comment]
Nah I think I did enough reporting on adhoc stuff.
More focused on infrastructure now as it feels better for online play.
