### ISSUE TITLE
Models from Ben 10: Alien Force (Video Game)

### ISSUE THREAD

**Issue by BenFourArms39023** [hrydgard/ppsspp#14482]
I got the Ben textures but I need the model.
Anyone ripped some models from Ben 10 Alien Force the game for PSP, PS2 and Wii and given me a download link for some models yet? Here are some textures.

![ben](https://user-images.githubusercontent.com/80484262/119569734-0e2dc200-bda7-11eb-81bc-ab0267be18e8.png)
![ben1](https://user-images.githubusercontent.com/80484262/119569735-0f5eef00-bda7-11eb-98b6-fd6545555461.png)
![omnitrix](https://user-images.githubusercontent.com/80484262/119569738-0ff78580-bda7-11eb-8c82-908124fd966b.png)

**Comment by Gamemulatorer** [comment]
This is an issue tracking not a ppsspp forums 🤦
Visit https://forums.ppsspp.org/forumdisplay.php?fid=36

**Comment by BenFourArms39023** [comment]
Okay, issue is being deleted
