### ISSUE TITLE
The Sims 2: Crash on Ritual

### ISSUE THREAD

**Issue by Wolfst0rm** [hrydgard/ppsspp#14508]
### What happens?
Whenever we do the Kine Dairy Ritual (Beelzebeef) in The Sims 2, the game crashes as it can not find an IO Device 

### What *should* happen?
The Game should be able to find the IO, and continue to run normally. 

### Screenshot or Video of the Error?
https://www.twitch.tv/videos/1047588785 - Video of the Crash

#### What hardware/device and operating system?
Windows 10

#### What graphics card (GPU) or mobile phone model?
Nvidia GTX 1060 6GB

#### What PPSSPP version (standalone/official), and did it work before?
PPSSPP Gold 1.11.3

#### Which game or games?
The Sims 2
ULUS10031

#### Checklist

 - [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [X] Include logs or screenshots of issue. - VODs of the issue that has been Reproduced have been attached to the report.

**Comment by Wolfst0rm** [comment]
If it helps when it goes to activate the cutscene, its complaining about an IO Device not being found:

`41:21:805 user_main    E[SCEIO]: HLE\sceIo.cpp:1494 80020321=sceIoOpen(tty0:, 2, 0): device not found`

**Comment by unknownbrackets** [comment]
#14510 may help.  When it's done building, you can try one of the artifacts under the Checks tab.

-[Unknown]

**Comment by Wolfst0rm** [comment]
Confirming that #14510 fixes the issue. Thanks!

**Comment by unknownbrackets** [comment]
Going to keep this open a bit until that's actually merged.  Thanks for confirming.

-[Unknown]

**Comment by Gamemulatorer** [comment]
May I ask if you also experience this issue #8999
