### ISSUE TITLE
NPJH50276 Adhoc Performance Regression (>=1.11.0)

### ISSUE THREAD

**Issue by Schtolteheim** [hrydgard/ppsspp#14506]
### What games and where in them does it happen?

Ys vs. Sora no Kiseki (NPJH50276) during 4-player adhoc multiplayer (4 instances on 1 machine, in my case)

### What speed are you getting with PPSSPP speed display enabled?
Host's framerate slows to 24, while guests remain at 30. Tested on 1.11.0, 1.11.3, and 1.11.3-729-g69fa20744. Last observed build with full speed was 1.10.3-873-g6ec4e012e, where host and guests maintained stable 30. All settings remained the same between all builds, to my knowledge.
![image](https://user-images.githubusercontent.com/30302862/120901270-bba2a000-c607-11eb-8165-d7ea5b60abc5.png)
![image](https://user-images.githubusercontent.com/30302862/120901325-1805bf80-c608-11eb-982b-679447ba5ad7.png)

#### What hardware / device and operating system?
Windows 10 64-bit, Ryzen 9 5900X; also tested with i7 6700K
#### What graphics card (GPU) or mobile phone model?
RTX 2080Ti; also tested with GTX 970M
#### Graphics backend (Vulkan, OpenGL, etc.)?
Direct3D 11

#### Checklist

 - [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [X] Try resetting settings or older versions and include if the issue is related.
 - [X] Try changing graphics settings to determine if one causes the slowdown.
 - [X] Include logs of screenshots of issue.

**Comment by unknownbrackets** [comment]
Given that it still says 100%, this means something is consuming more cycles than before.  Presumably incorrectly, though it would be ideal to verify the framerate on a PSP with a CFW plugin.

-[Unknown]

**Comment by ANR2ME** [comment]
I couldn't find `1.10.3-873-g6ec4e012e` at https://buildbot.orphis.net/ppsspp/index.php?m=fulllist
Are you using test build?

Could you try a few version after `1.10.3-873` from https://buildbot.orphis.net/ppsspp/index.php?m=fulllist to find out the latest official dev build that worked full speed?

**Comment by Schtolteheim** [comment]
I was using the build from #13519: https://github.com/hrydgard/ppsspp/pull/13519

Will test those builds shortly.

**Comment by Schtolteheim** [comment]
Last adhoc-related build that ran at full speed was 1.10.3-965-gd738c9b78 (1.10.3-1026-g36a614072 also ran fine).

All builds from 1.10.3-1044-ga4a0b4ba0 onward seem to have this issue.

**Comment by unknownbrackets** [comment]
That points to #13579.  Perhaps 3020efdbe was aggressive and could be reduced.

-[Unknown]

**Comment by ANR2ME** [comment]
Yeah, those `hleEatMicro` might be too much, since there is already an overhead on the actual socket it self.

**Comment by ANR2ME** [comment]
Please try the artifacts on this PR later https://github.com/hrydgard/ppsspp/pull/14513/checks?check_run_id=2760683525
