### ISSUE TITLE
HLEHelperThread issue

### ISSUE THREAD

**Issue by xnplasma** [hrydgard/ppsspp#14516]
#### Checklist
 - [ ] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [X] Try resetting settings or older versions and include if the issue is related.
 - [ ] Include logs or screenshots of issue.

![Screenshot 2021-06-07 4 19 44 PM](https://user-images.githubusercontent.com/48888884/121089053-31e00780-c7ac-11eb-874c-af29e23029c5.png)

**Comment by Gamemulatorer** [comment]
Maybe this is related to #11355

**Comment by xnplasma** [comment]
> Maybe this is related to #11355

it doesnt close, it just stays on the blank screen.

**Comment by Gamemulatorer** [comment]
Try to reset your ppsspp settings to default or try older version

**Comment by xnplasma** [comment]
I tried resetting the settings, didnt work. I’m using the android appstore version, so there is no older version

**Comment by Panderner** [comment]
> so there is no older version

@xnplasma you can download older versions her:
http://ppsspp.org/downloads_all.html#android

**Comment by ANR2ME** [comment]
Is this only happened when you load from SaveState? does loading it from savedata/memorystick worked fine?

**Comment by unknownbrackets** [comment]
It'd help if you attached your save state in a zip file.  I'm wondering what version of PPSSPP that save state was created in.

-[Unknown]

**Comment by xnplasma** [comment]
sorry for answering late, but i’m not sure which version it was made in, and it doesn’t load from memory stick

**Comment by unknownbrackets** [comment]
The save state file contains the version that created it, so if you upload it inside a zip file to this issue in a comment, I'll be able to tell.

-[Unknown]

**Comment by Gamemulatorer** [comment]
This is also happen if you savestate using ppsspp github apk and then reload using ppsspp playstore.
![Screenshot_2021-06-08-11-02-37-382_org ppsspp ppssppgold](https://user-images.githubusercontent.com/37603562/121116569-5807b500-c849-11eb-8724-bdc177892d2d.jpg)

**Comment by hrydgard** [comment]
Well, that error is kinda expected, and self explanatory. Savestates are backwards compatible but not forwards compatible, it would probably take an impractical amount of work and testing to make them so.

**Comment by unknownbrackets** [comment]
Failure at HLEHelperThread sounds like #14564, if you were using a git build to create the save state.  If the game was hacked or a different region, that could also prevent the save state from loading properly.

Please try the latest git.  Without the save state file, we can't really investigate this more and changes have been made to the latest git that may fix it.

I'm closing this issue, but if you're still seeing it feel free to comment with more detail, and we'll reopen.  If you're just seeing a different save state issue, please open a new issue.

-[Unknown]
