### ISSUE TITLE
[ULES01500] Tactics Ogre showing endless "now loading" notification

### ISSUE THREAD

**Issue by stuken** [hrydgard/ppsspp#14517]
Build v1.11.3-777-gcdaf53391 has regressed Tactics Ogre from properly booting to showing an endless now loading notification.

Build v1.11.3-742-g084f97c6c works correctly.

Tested with both standalone and libretro Windows 10 x64 builds.
![image](https://user-images.githubusercontent.com/8155719/121352703-046a9980-c925-11eb-9342-971e9faa2e1d.png)

**Comment by hrydgard** [comment]
Thanks for catching this! I'll have it fixed soon.

**Comment by unknownbrackets** [comment]
Fixed by 84036fa76.

-[Unknown]
