### ISSUE TITLE
"home" directory is being cutoff as "ome" on Linux build causing save faliures

### ISSUE THREAD

**Issue by artlan** [hrydgard/ppsspp#14519]
System - Linux 
Build - Release 1.11.3 (f7ace3b)
All games

Unable to save settings, states or savegame.

### What happens?
Fail to save error

### What *should* happen?
Data should be saved

### What are you using?
RetroPie - Rpi4

#### What PPSSPP version (standalone/official), and did it work before?
Noted above

#### Which game or games?
After debugging I found that the issue is that folders were not getting created.
I was able to manually create the needed folders for most things - but save games were still failed.
That's when I found this in the log files

01:01:527 root         E[COMMON]: File/FileUtil.cpp:438 CreateDir: mkdir failed on //ome: Permission denied
01:01:527 root         E[COMMON]: File/FileUtil.cpp:438 CreateDir: mkdir failed on //ome/pi: No such file or directory
01:01:527 root         E[COMMON]: File/FileUtil.cpp:438 CreateDir: mkdir failed on //ome/pi/.config: No such file or directory
01:01:527 root         E[COMMON]: File/FileUtil.cpp:438 CreateDir: mkdir failed on //ome/pi/.config/ppsspp: No such file or directory
01:01:527 root         E[COMMON]: File/FileUtil.cpp:438 CreateDir: mkdir failed on //ome/pi/.config/ppsspp/PSP: No such file or directory
01:01:527 root         E[COMMON]: File/FileUtil.cpp:438 CreateDir: mkdir failed on //ome/pi/.config/ppsspp/PSP/SYSTEM: No such file or directory
01:01:527 root         E[COMMON]: File/FileUtil.cpp:438 CreateDir: mkdir failed on //ome/pi/.config/ppsspp/PSP/SYSTEM/CACHE: No such file or directory

For some reason the FileUtil.ccp is truncating the 'home' directory as 'ome' and then failing to create any of the needed locations.
When saving a game, the same lines appear

03:35:321 user_main    E[COMMON]: File/FileUtil.cpp:438 CreateDir: mkdir failed on //ome/pi/.config/ppsspp/PSP/SAVEDATA: No such file or directory
03:35:321 user_main    E[COMMON]: File/FileUtil.cpp:438 CreateDir: mkdir failed on //ome/pi/.config/ppsspp/PSP/SAVEDATA/UCUS987000000: No such file or directory
03:35:344 user_main    E[FILESYS]: FileSystems/DirectoryFileSystem.cpp:66 DirectoryFileSystem::OpenFile(/PSP/SAVEDATA/UCUS987000000/PARAM.SFO): FAILED, 2 - access = 26 ''
03:35:344 user_main    E[FILESYS]: FileSystems/DirectoryFileSystem.cpp:66 DirectoryFileSystem::OpenFile(/PSP/SAVEDATA/UCUS987000000/JEANNE.SAV): FAILED, 2 - access = 26 ''
 

This also occurred when I compiled from source

**Comment by unknownbrackets** [comment]
84036fa76 may have improved things here, but probably didn't fix it - I'm not sure what might be changing your HOME path.  To be sure, your HOME env var is correct right?

-[Unknown]

**Comment by artlan** [comment]
![Home Env](https://user-images.githubusercontent.com/1160344/121472227-bfbb1e80-c975-11eb-87ae-c26e838dd630.PNG)

Yes, it looks correct. The emulator also correctly set all it's other path variables, this only seems to impact however it's generating it's path for folder creation. 
I tested making a "ome" directory - and the emu would successfully create all folders there, but read/write all data from the "home" directory structure
