### ISSUE TITLE
JIT for Substitute

### ISSUE THREAD

**Issue by fivesec5** [hrydgard/ppsspp#14525]
when will JIT work on substitute?

**Comment by Panderner** [comment]
What?

**Comment by unknownbrackets** [comment]
If an iOS hack enables jit, it should in theory work - it should make the process debuggable and things should show up.  If it doesn't, you should ask the people involved in iOS hacks about it.  This project isn't a project about iOS hacking, it's an emulator.

If anything needs to be done in PPSSPP, it's probably #14196, so closing this as a duplicate.

-[Unknown]
