### ISSUE TITLE
v1.11.3-777-gcdaf53391 regression that all games cannot be saved

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#14521]
### What happens?
In v1.11.3-777-gcdaf53391 Scoped Storage update that all games are cannot be saved
![Screenshot_2021-06-10-14-05-41-391_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/121474550-cf2e7c00-c9f6-11eb-92cb-8d9461b553c6.jpg)
![Screenshot_2021-06-10-14-18-36-772_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/121474558-d190d600-c9f6-11eb-8025-e819401ba442.jpg)
And also error message too
![Screenshot_2021-06-10-14-06-33-244_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/121474641-ecfbe100-c9f6-11eb-873d-cfb2797d22c0.jpg)

### What *should* happen?
v1.11.3-742-g084f97c6c and older saves works properly

#### What hardware / device and operating system?
Android 10
#### What graphics card (GPU) or mobile phone model?
POCO M3
#### What PPSSPP version (standalone/official), and did it work before?
v1.11.3-742-g084f97c6c - last work
v1.11.3-777-gcdaf53391 - first bad
#### Which game or games?

All games I tested

#### Checklist

 - [x] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [x] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [x] Try resetting settings or older versions and include if the issue is related.
 - [x] Include logs or screenshots of issue.

**Comment by Panderner** [comment]
My Windows 10 PC works fine for me in latest build but not my Android Phone

**Comment by hrydgard** [comment]
Thanks, will fix soon

**Comment by Panderner** [comment]
And here's another one:
Change the Memory stick folder then browse, Choose any folder and use this folder.

Conclusion PPSSPP Save Settings errors are fixed but not the games.

**Comment by Gamemulatorer** [comment]
Try the latest ppsspp github apk
this should probably fixed by https://github.com/hrydgard/ppsspp/commit/84036fa765726bb02c12418e1f92fb15040f660f

**Comment by Panderner** [comment]
> Try the latest ppsspp github apk
> this should probably fixed by [84036fa](https://github.com/hrydgard/ppsspp/commit/84036fa765726bb02c12418e1f92fb15040f660f)

I'm using latest build @Gamemulatorer still not fixed.

**Comment by Gamemulatorer** [comment]
Are you using an SDcard and your game settings are their?

**Comment by Panderner** [comment]
Oh https://github.com/hrydgard/ppsspp/commit/39f479025ec6231fb2957f869ba66991c2e05e19 fixed saving issue for all games for my android phone 
I'm using v1.11.3-779-g39f479025 and it's now fixed i'm closing this.
