### ISSUE TITLE
UNO - android and ios crossplay problem

### ISSUE THREAD

**Issue by BTFighter** [hrydgard/ppsspp#14526]
When 2 androids connect to each other on a local network, they are able to see each other. However, when an android plays UNO with an iPhone, they cannot see each other. Other games like Tekken 6 and Platypus works.

#### What hardware / device and operating system?
2 Androids (both are vivo phones)
1 iPhone

#### What graphics card (GPU) or mobile phone model?
vivo y55L
vivo y91i
iPhone 7 Plus

#### What PPSSPP version (standalone/official)
All three phones use PPSSPP version 1.11.3-779-g39f47902

#### Which game or games?
UNO
Platypus (works)
Tekken 6 (works)

**Comment by Panderner** [comment]
This should be related to #9035

**Comment by BTFighter** [comment]
Okay
