### ISSUE TITLE
[Android][UI text] Some UI text is too much large and bad position in Japanese.

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#14522]
### What happens?
Some UI text is too much large and bad position in Japanese.

![ppsspp_chat](https://user-images.githubusercontent.com/48179091/121606363-fc2b6f00-ca88-11eb-83f5-ff479c7ab40e.png)

![ppsspp_nameid (2)](https://user-images.githubusercontent.com/48179091/121607643-5d544200-ca8b-11eb-9b60-569b1f8ab217.png)

ID should set position to rightside.
![ppsspp_nameid (1)](https://user-images.githubusercontent.com/48179091/121606981-29c4e800-ca8a-11eb-8fbc-9c5a54707d1b.png)

Probably, All font size over large in japanese.

### What *should* happen?
It should be set good small size and set good position.

#### What hardware / device and operating system?
PPSSPP Ver.：1.11.3-777
OS：Android 11.0
DeviceName：Samusung Galaxy S20 / SC-51A
CPU：Snapdragon865（Octa-core）
GPU：Adreno 650
Resolution：3200 x 1440 (Max)
RAM：12GB
ROM：128GB
ExternalStrage：microSDXC 512GB

#### Checklist

 - [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [ ] Try resetting settings or older versions and include if the issue is related.
 - [ ] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
I wonder if something is subtly different/wrong in the sizing vs drawing code, or maybe this is a negative kerning issue or something.

-[Unknown]

**Comment by nassau-tk** [comment]
Um...l don't know why.
But, Maybe it needs size down more 2or3 points?
Or if can do that auto size?

And, Windows chat counter too.
If conut the message stock over 10 then become below.

チャット  0
become below.
チャッ   10
ト

**Comment by unknownbrackets** [comment]
The chat one I think might be specifically sized that wide - I think it's a fixed 130 units wide right now.  Probably not great for a few other languages too.

-[Unknown]

**Comment by nassau-tk** [comment]
Related #14913 .

**Comment by unknownbrackets** [comment]
How is this now?  The chat icon should be better.  I didn't reproduce the others.

-[Unknown]

**Comment by nassau-tk** [comment]
Yes! It seems good about below UI!
![image](https://user-images.githubusercontent.com/48179091/135070614-2628729f-e380-4175-bd1a-fcace4fab390.png)
![image](https://user-images.githubusercontent.com/48179091/135070639-4ed674ff-d51f-49fe-83dc-7870af6a3b45.png)

But,Games tab is not good yet.
![image](https://user-images.githubusercontent.com/48179091/135071641-695bb579-3090-43cd-a417-c8f5e7d9d32e.png)
