### ISSUE TITLE
PPSSPP v1.11.777 regression

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#14520]
### What happens?
Since https://github.com/hrydgard/ppsspp/commit/cdaf5339131a15ea3b38074c4df9ff98b22a0d3e
KILLZONE LIBERATION crashing out the emulator and GOD EATER BURST hang on loading ingame save.
### Screen Record
[Screenrecorder-2021-06-10-10-56-09-304.zip](https://github.com/hrydgard/ppsspp/files/6628331/Screenrecorder-2021-06-10-10-56-09-304.zip)

### What *should* happen?
PPSSPP v.1.11.742 No such issue on this Killzone Liberation is not crashing and God Eater Burst is loading save game without hang.

#### What hardware / device and operating system?
Redmi Note 9 Mediatek Helio G85 Mail GPU Android 10

#### What PPSSPP version (standalone/official), and did it work before?
Yes working on PPSSPP v1.11.742 development version apk

#### Checklist

 - [ ✓] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [ ✓] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [✓ ] Try resetting settings or older versions and include if the issue is related.
 - [✓ ] Include video as evidence.

**Comment by unknownbrackets** [comment]
This is probably fixed by 84036fa76.

-[Unknown]

**Comment by Gamemulatorer** [comment]
Confirm fixed by https://github.com/hrydgard/ppsspp/commit/84036fa765726bb02c12418e1f92fb15040f660f
