### ISSUE TITLE
need mipmaping

### ISSUE THREAD

**Issue by jamezcook** [hrydgard/ppsspp#14535]
dear @hrydgard
Currently PPSSPP is very smooth but leaves unsatisfactory graphics.
in the future, please add the mimaping feature like the previous version, because this feature is very important for a games

thanks

**Comment by LunaMoo** [comment]
Mipmapping exists and is active by default as there's no reason to disable it, hence the option for it doesn't exist.

 That being said, there are some cases where mipmapping might be used in special way which is not implemented outside of software renderer like #6357

 Some normal modes of mipmapping might also not be working yet in the exact same way it does on real PSP and might work differently as it was years ago as we have some other issues opened althrough it doesn't affect that many games and isn't really as bothersome as special case mentioned above.

 Take note that using texture scaling disables mipmapping and that was always the case, even before the option to disable mipmaps was removed.
