### ISSUE TITLE
[OpenGL]Auditorium can't start - 1.11.3

### ISSUE THREAD

**Issue by itsXPCT** [hrydgard/ppsspp#14532]
Hi,me again.Found other bug,no clones so
i figured to open out

### What happens?
Game doesn't go any further than Memory Stick message

![Screenshot_2021-06-13-20-50-36-975_org ppsspp ppssppgold](https://user-images.githubusercontent.com/67833785/121818793-93f7ab80-cc89-11eb-9323-e809970bb51c.png)

### What *should* happen?
Game should proceed fine after Memory Stick message

### What are you using?
Honor 9S - Phone

#### What hardware / device and operating system?
Android 8.1.0

#### What graphics card (GPU) or mobile phone model?
Honor 9S
GPU - PowerVR GE8320

#### What PPSSPP version (standalone/official), and did it work before?
None,game never worked as far as i can tell
#### Which game or games?

Auditorium
NPUH10069
USA

[recording.zip](https://github.com/hrydgard/ppsspp/files/6644452/recording.zip)

#### Checklist

 - [x] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [x] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [x] Try resetting settings or older versions and include if the issue is related.
 - [x] Include logs or screenshots of issue.
 - [x] Simulate UMD Delay on I/O
 - [x] Save / Load to confirm isn't Atrac3 issue
 
TIA

**Comment by unknownbrackets** [comment]
This seems related to #9213.  Using Simulate UMD Delays causes this game to boot very very slowly.  If you turn that off, does it run better?  Maybe give it a good 60 seconds to start - based on that issue, this at least used to go in game.

Someone must've thought this ran well back in older versions:
https://report.ppsspp.org/game/NPUH10069_1.00

-[Unknown]

**Comment by LunaMoo** [comment]
Sorry if my wording in #9213 was confusing, the game never started booting again, hence why I said the issue didn't changed, the boot time increase with "simulate umd delay" was with a simple patch that works around the issue and was also mentioned in it(returning fail/error for sceUmdActivate is enough to make it boot and I created a cwcheat patch for it ~ https://github.com/LunaMoo/PPSSPP_workarounds).

 As such I would say it's exactly same issue and will close this as a duplicate.

**Comment by unknownbrackets** [comment]
Ah that's right, sorry.

-[Unknown]

**Comment by itsXPCT** [comment]
Sorry as well,didn't try to understand your issue properly

TIA
