### ISSUE TITLE
PPSSPP v1.11.815 New ThreadManager regression

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#14531]
### What happens?
Loading a game instantly crash the emulator.

### What *should* happen?
Should load the game properly without crash.
### What are you using?
Mobile Phone
#### What hardware / device and operating system?
Android 10 MIUI 12.0.8
#### What graphics card (GPU) or mobile phone model?
Redmi Note 9 Mediatek Helio G85 Mali-G52 MC2
#### What PPSSPP version (standalone/official), and did it work before?
Issue started in https://github.com/hrydgard/ppsspp/commit/87716a158fc2d8cebee1947d73a1c6d82fc562d9 previously work in ppsspp v1.11.787 development apk
#### Checklist

 - [✓ ] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [ ✓] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [✓ ] Try resetting settings or older versions and include if the issue is related.
 - [✓ ] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
Seems to be a range loop problem.

-[Unknown]

**Comment by unknownbrackets** [comment]
Should be fixed by 8ae3f5eb.  I'm not quite sure why, but `numComputeThreads_` was 0, and this somehow wasn't a divide by zero error and led to `numTasks` of 256.  Then it hit an assert, so go asserts.

-[Unknown]
