### ISSUE TITLE
Read-only sdcard inserted on android 5.0 can instantly crash PPSSPP if sdcard is set as default storage.

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#14544]
### What happens?
PPSSPP instantly crash after clicking
![Screenshot_2021-06-19-20-51-13](https://user-images.githubusercontent.com/37603562/122643102-78384d80-d140-11eb-9a53-56681d2e4284.png)
[VID_20210619_204941.zip](https://github.com/hrydgard/ppsspp/files/6680686/VID_20210619_204941.zip)

### What *should* happen?
Not crashing

#### What graphics card (GPU) or mobile phone model?
Cloudfone Excite Prime Android Lollipop
#### What PPSSPP version (standalone/official), and did it work before?
PPSSPP latest dev apk
#### Checklist

 - [ √] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [ ✓] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [ ✓] Try resetting settings or older versions and include if the issue is related.
 - [ √] Include logs or screenshots of issue.

**Comment by Panderner** [comment]
@Gamemulatorer are you using internal storage?

**Comment by ANR2ME** [comment]
Hmm.. it said "Read-only file system" O.o `sdcard0` shouldn't be read-only if you already gave PPSSPP permission to access storage isn't?

**Comment by Gamemulatorer** [comment]
> Hmm.. it said "Read-only file system" O.o `sdcard0` shouldn't be read-only if you already gave PPSSPP permission to access storage isn't?

But on my android 10 phone even if it's read-only sdcard I can use it.

**Comment by hrydgard** [comment]
Hm, why close?

**Comment by Gamemulatorer** [comment]
My sdcard write protection is read-only I think this not related to pppsspp

**Comment by hrydgard** [comment]
I still think we should try to survive and not crash.

**Comment by Gamemulatorer** [comment]
Doesn't crash on PPSSPP Gold 🤔

**Comment by Gamemulatorer** [comment]
It doesn't crash now on my old android lollipop using the latest ppsspp development version for android.

**Comment by Gamemulatorer** [comment]
It doesn't crash now on my old android lollipop using the latest ppsspp development version for android.

**Comment by hrydgard** [comment]
Thanks for testing!

**Comment by Gamemulatorer** [comment]
This issue totally fixed by https://github.com/hrydgard/ppsspp/commit/db21d0e7fcc60cd86f8a20e72e7805d457cf6759

**Comment by Gamemulatorer** [comment]
I can reproduce this issue again since https://github.com/hrydgard/ppsspp/pull/15686/commits/656576c2838c33b3c138f496f6d936a3a82a085b but it's ok I am not using my android lollipop for ppsspp 😅

**Comment by hrydgard** [comment]
Huh, that is quite surprising! Are you able to get adb logs? If so I'd suggest the following:

```adb logcat -s AndroidRuntime DEBUG PPSSPPNativeActivity PPSSPP NativeGLView NativeRenderer NativeSurfaceView PowerSaveModeReceiver InputDeviceState PpssppActivity```

**Comment by Gamemulatorer** [comment]
> Huh, that is quite surprising! Are you able to get adb logs? If so I'd suggest the following:
> 
> `adb logcat -s AndroidRuntime DEBUG PPSSPPNativeActivity PPSSPP NativeGLView NativeRenderer NativeSurfaceView PowerSaveModeReceiver InputDeviceState PpssppActivity`

Ok I will try to do this next time.

**Comment by Gamemulatorer** [comment]
I cannot report any further about this issue in the future because my android lollipop is near EOL 😢
![IMG_20220718_031531](https://user-images.githubusercontent.com/37603562/179421643-7947a803-9bcb-49ae-be74-f95aec42d882.jpg)
Might be better to move this to future milestone 😟

**Comment by Gamemulatorer** [comment]
Unexpectedly my android 5 phone works again with read-only sdcard 🎉🎉🎉
![IMG_20220805_132600](https://user-images.githubusercontent.com/37603562/183242617-c6e16e15-3b50-4d12-84bd-291ed37d5ffb.jpg)
![IMG_20220805_132543](https://user-images.githubusercontent.com/37603562/183242625-e62623ed-19d6-4f43-b43f-ce430d6c725f.jpg)

I'm using PPSSPP V1.13.1-171 build.

**Comment by Gamemulatorer** [comment]
But almost all games is crashing when I'm using buffered rendering.
This warning always show 🤔
![IMG_20220806_114151](https://user-images.githubusercontent.com/37603562/183242716-7bcf4fca-7812-47ab-92ae-39a2315bb8af.jpg)

**Comment by ANR2ME** [comment]
hmm.. may be similar issue to this https://stackoverflow.com/questions/64686342/opengl-es-shader-compilation
> It turned out that the problem is in the last character \0. Should be used instead \n

**Comment by Gamemulatorer** [comment]
Closing this since the issue is about the sdcard storage crash.

**Comment by hrydgard** [comment]
That shader compilation bug is bad though! I'm gonna fix that.

**Comment by hrydgard** [comment]
@Gamemulatorer Fixed.

**Comment by Gamemulatorer** [comment]
Will report back later

**Comment by Gamemulatorer** [comment]
> @Gamemulatorer Fixed, or at least should be.

Still crashing using buffered rendering v1.13.1-207

**Comment by Gamemulatorer** [comment]
I created a separate issue about the crashing when using buffered rendering https://github.com/hrydgard/ppsspp/issues/15800
