### ISSUE TITLE
Outrun has graphical issues (flickering rectangles) in latest update on pi 4 

### ISSUE THREAD

**Issue by akamming** [hrydgard/ppsspp#14549]
### What happens?

I have not updated PPSSPP for a long time (more than half a year), but after i updated i played some games and noticed an graphical issue in Outrun 2006: There are now flickering rectangles on the lower part of the screen. Before upgrade this was not the case:

![image](https://user-images.githubusercontent.com/30364409/122729189-2e9f4e00-d279-11eb-8eb9-579c573427e9.png)

other games seem to work fine

### What *should* happen?

no graphical issue (the road should be drawn there)

### What are you using?

PPSSPP version "b07d907"  according to the main menu screen

#### What hardware / device and operating system?
Using PPSSPP as part of a (standard) retropie installation on a raspberry pi 4 (2GB)

#### What graphics card (GPU) or mobile phone model?
default GPU in a pi 4

#### What PPSSPP version (standalone/official), and did it work before?
standalone, installed by retropie

#### Which game or games?
ULUS10064

#### Checklist
 - [ X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [ X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [ X] Try resetting settings or older versions and include if the issue is related. (don't know how to get an older version. It worked on the version about half a year ago)
 - [X ] Include logs or screenshots of issue.

**Comment by Gamemulatorer** [comment]
related https://github.com/hrydgard/ppsspp/issues/12222

**Comment by hrydgard** [comment]
That looks strange, kinda like the range culling errors but this game needs range culling to work. Weird...

**Comment by Gamemulatorer** [comment]
b07d907

**Comment by unknownbrackets** [comment]
I think we had to disable the culling on rpi GPUs because of broken NaN handling?

-[Unknown]

**Comment by akamming** [comment]
played on my pi again for a long time, but before that i updated to latest version. Issue is fixed in that version!
