### ISSUE TITLE
Dirt 2 crashing

### ISSUE THREAD

**Issue by samosaphile** [hrydgard/ppsspp#14552]
### What happens?
When you switch to other apps on android while this game is running, then switch back to ppsspp emu, causes the entire emu to force close / crash instantly. 

You don't even need to switch apps to trigger / cause it to happen. Simply putting ppsspp in background using that multitasking gesture, then returning back to it does the exact same thing.

### What *should* happen?
Resume gracefully.

#### What hardware / device and operating system?
Pixel 4a on stockOS android 11.
#### What graphics card (GPU) or mobile phone model?
Adreno 618 / sunfish.
#### What PPSSPP version (standalone/official), and did it work before?
1.11.3-742, don't know tbh.
#### Which game or games?

ULUS10471
ULES01301
#### Checklist

 - [ ] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [ ] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [ ] Try resetting settings or older versions and include if the issue is related.
 - [ ] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment]
Is this only happened on Dirt 2 ? or other games have similar issue?

**Comment by Gamemulatorer** [comment]
@samosaphile this doesn't happen on a stable version 1.11.3 from playstore?

**Comment by Panderner** [comment]
Works fine for me for my phone.
I switched to other app while running this game and switch back to PPSSPP it didn't crashed.

**Comment by samosaphile** [comment]
> Is this only happened on Dirt 2 ? or other games have similar issue?
> 
> You will probably need to check the Logcat to findout why it crashed.

Yup, only this game causes the emu to do this. 

> @samosaphile this doesn't happen on a stable version 1.11.3 from playstore?

I no longer use this version and haven't done so in ages.

> Works fine for me for my phone.
> I switched to other app while running this game and switch back to PPSSPP it didn't crashed.

I think some parts of the game don't for me. Like if I do it in the beginning (when loading CGI movie clip) but pretty much every other spot in game causes it to happen.

**Comment by Gamemulatorer** [comment]
Doesn't also crash on my phone dirt 2 europe cso

**Comment by unknownbrackets** [comment]
If you can, a logcat as mentioned would really help:
https://github.com/hrydgard/ppsspp/wiki/How-to-get-an-adb-logcat-from-a-PC

It may also be sensitive to what part of the game you're switching during.  Can you be specific about a place in the game you do it from that always crashes?

-[Unknown]

**Comment by Gamemulatorer** [comment]
> Doesn't also crash on my phone dirt 2 europe cso

Hmm. 😶
I can now reproduce this issue 😅

**Comment by Gamemulatorer** [comment]
I discover that the crash can only reproduce on vulkan backend opengl backend didn't crash maybe this issue is related to https://github.com/hrydgard/ppsspp/issues/13800

**Comment by Gamemulatorer** [comment]
![Screenshot_2021-06-28-20-12-06](https://user-images.githubusercontent.com/37603562/123634713-609e4a80-d84d-11eb-99c8-27adcf205ae2.png)
On my old phone (Mali-450 GPU) this game has a gfx issue..

**Comment by Gamemulatorer** [comment]
a GE dump. It will download as a file.
Recording...
Debugger connected
18:56:130 user_main    N[SYSTEM]: Debugger/Record.cpp:523 Recording starting on display...
18:56:130 user_main    N[SCEDISP]: HLE/sceDisplay.cpp:530 Dropping frames - budget = 16.68ms / 59.9fps, actual = 8702.30ms (+8685.61ms) / 0.1fps
Kernel processing time: 40.52 ms
Slowest syscall: __KernelReturnFromInterrupt : 19.83 ms
Most active syscall: __KernelReturnFromInterrupt : 38.49 ms
DL processing time: 38.28 ms
Draw calls: 12406, flushes 665, clears 4 (cached: 0)
Num Tracked Vertex Arrays: 0
Commands per call level: 14245 28398 6488 0
Vertices: 87196 cached: 0 uncached: 181122
FBOs active: 3 (evaluations: 35)
Textures: 131, dec: 0, invalidated: 0, hashed: 9256 kB
Readbacks: 0, uploads: 0
GPU cycles executed: 2499327 (27.536411 per vertex)
Vertex, Fragment, Programs loaded: 22, 32, 61

21:00:983 user_main    N[SYSTEM]: Debugger/Record.cpp:546 Recording complete on display
21:00:987 user_main    N[G3D]: Debugger/Record.cpp:117 Recording filename: /storage/sdcard0/PSP/SYSTEM/DUMP/ULES01301_0001.ppdmp
21:01:212 user_main    N[SYSTEM]: Debugger/Record.cpp:410 Recording finished
21:01:212 user_main    N[SCEDISP]: HLE/sceDisplay.cpp:530 Dropping frames - budget = 16.68ms / 59.9fps, actual = 125173.93ms (+125157.25ms) / 0.0fps
Kernel processing time: 124833.08 ms
Slowest syscall: __KernelReturnFromInterrupt : 42629.47 ms
Most active syscall: __KernelReturnFromInterrupt : 124832.73 ms
DL processing time: 124832.47 ms
Draw calls: 12406, flushes 671, clears 4 (cached: 0)
Num Tracked Vertex Arrays: 0
Commands per call level: 29954 30158 3582 0
Vertices: 87196 cached: 0 uncached: 181122
FBOs active: 2 (evaluations: 155)
Textures: 120, dec: 120, invalidated: 0, hashed: 9256 kB
Readbacks: 2, uploads: 2
GPU cycles executed: 2528453 (27.536411 per vertex)
Vertex, Fragment, Programs loaded: 15, 25, 37

21:01:872 user_main    N[SCEDISP]: HLE/sceDisplay.cpp:530 Dropping frames - budget = 16.68ms / 59.9fps, actual = 751.48ms (+734.80ms) / 1.3fps
Kernel processing time: 302.23 ms
Slowest syscall: __KernelReturnFromInterrupt : 255.93 ms
Most active syscall: __KernelReturnFromInterrupt : 301.84 ms
DL processing time: 301.62 ms
Draw calls: 12406, flushes 665, clears 4 (cached: 0)
Num Tracked Vertex Arrays: 0
Commands per call level: 14245 28398 6488 0
Vertices: 87196 cached: 0 uncached: 181122
FBOs active: 3 (evaluations: 36)
Textures: 121, dec: 1, invalidated: 0, hashed: 9256 kB
Readbacks: 1, uploads: 1
GPU cycles executed: 2499327 (27.536411 per vertex)
Vertex, Fragment, Programs loaded: 15, 26, 38

21:01:955 user_main    N[SCEDISP]: HLE/sceDisplay.cpp:530 Dropping frames - budget = 16.68ms / 59.9fps, actual = 174.81ms (+158.12ms) / 5.7fps
Kernel processing time: 66.55 ms
Slowest syscall: __KernelReturnFromInterrupt : 29.31 ms
Most active syscall: __KernelReturnFromInterrupt : 64.32 ms
DL processing time: 64.00 ms
Draw calls: 12407, flushes 665, clears 4 (cached: 0)
Num Tracked Vertex Arrays: 0
Commands per call level: 14245 28398 6488 0
Vertices: 87204 cached: 0 uncached: 181140
FBOs active: 3 (evaluations: 37)
Textures: 123, dec: 2, invalidated: 0, hashed: 9256 kB
Readbacks: 0, uploads: 0
GPU cycles executed: 2499487 (27.535721 per vertex)
Vertex, Fragment, Programs loaded: 15, 26, 38

21:02:020 user_main    N[SCEDISP]: HLE/sceDisplay.cpp:530 Dropping frames - budget = 16.68ms / 59.9fps, actual = 156.27ms (+139.59ms) / 6.4fps
Kernel processing time: 50.75 ms
Slowest syscall: __KernelReturnFromInterrupt : 21.45 ms
Most active syscall: __KernelReturnFromInterrupt : 50.03 ms
DL processing time: 49.75 ms
Draw calls: 12259, flushes 652, clears 4 (cached: 0)
Num Tracked Vertex Arrays: 0
Commands per call level: 14218 27807 6306 0
Vertices: 85799 cached: 0 uncached: 177813
FBOs active: 3 (evaluations: 35)
Textures: 123, dec: 0, invalidated: 0, hashed: 8919 kB
Readbacks: 0, uploads: 0
GPU cycles executed: 2462687 (27.576370 per vertex)
Vertex, Fragment, Programs loaded: 15, 26, 38

21:02:082 user_main    N[SCEDISP]: HLE/sceDisplay.cpp:530 Dropping frames - budget = 16.68ms / 59.9fps, actual = 154.04ms (+137.36ms) / 6.5fps
Kernel processing time: 44.68 ms
Slowest syscall: __KernelReturnFromInterrupt : 23.08 ms
Most active syscall: __KernelReturnFromInterrupt : 44.30 ms
DL processing time: 44.01 ms
Draw calls: 12260, flushes 652, clears 4 (cached: 0)
Num Tracked Vertex Arrays: 0
Commands per call level: 14231 27808 6306 0
Vertices: 85800 cached: 0 uncached: 177810
FBOs active: 3 (evaluations: 35)
Textures: 123, dec: 0, invalidated: 0, hashed: 8920 kB
Readbacks: 0, uploads: 0
GPU cycles executed: 2462755 (27.576515 per vertex)
Vertex, Fragment, Programs loaded: 15, 26, 38

21:28:086 user_main    N[SYSTEM]: Debugger/Record.cpp:523 Recording starting on display...
21:28:087 user_main    N[SCEDISP]: HLE/sceDisplay.cpp:530 Dropping frames - budget = 16.68ms / 59.9fps, actual = 26096.52ms (+26079.84ms) / 0.0fps
Kernel processing time: 41.76 ms
Slowest syscall: __KernelReturnFromInterrupt : 20.76 ms
Most active syscall: __KernelReturnFromInterrupt : 39.64 ms
DL processing time: 39.46 ms
Draw calls: 12268, flushes 653, clears 4 (cached: 0)
Num Tracked Vertex Arrays: 0
Commands per call level: 14231 27808 6306 0
Vertices: 85826 cached: 0 uncached: 177840
FBOs active: 3 (evaluations: 35)
Textures: 123, dec: 0, invalidated: 0, hashed: 8920 kB
Readbacks: 0, uploads: 0
GPU cycles executed: 2463635 (27.578415 per vertex)
Vertex, Fragment, Programs loaded: 15, 26, 38

**Comment by Gamemulatorer** [comment]
Here's the crashlog captured using matlog app
[logs-2021-07-11-05-13-22.zip](https://github.com/hrydgard/ppsspp/files/6795957/logs-2021-07-11-05-13-22.zip)

@unknownbrackets please tell us what is wrong 🙂

**Comment by crazyrexz** [comment]
also dirt 2 has some extra power usage than other games, my back case get warm and battery drained quick, maybe just me

**Comment by Gamemulatorer** [comment]
> also dirt 2 has some extra power usage than other games, my back case get warm and battery drained quick, maybe just me

@crazyrexz What's is your phone brand name and specifications?

**Comment by unknownbrackets** [comment]
This happens from `SetTextureFramebuffer()` -> `ReinterpretFramebuffer()` -> `VKContext::Draw()`.  This is a relatively new path.

My suspicion is that we're crashing without a vertex buffer or with an old invalid one:
https://github.com/hrydgard/ppsspp/blob/630f071d536a0d13efb49e84726ee2848e5185bb/GPU/Common/FramebufferManagerCommon.cpp#L653-L654

-[Unknown]

**Comment by hrydgard** [comment]
That will probably have fixed it - give it a try.

**Comment by Gamemulatorer** [comment]
I will try the latest build later 😁

**Comment by Gamemulatorer** [comment]
Yes https://github.com/hrydgard/ppsspp/pull/14702/commits/4cb69760297dc7c915e8383892c0984f27510d14 fix this issue

**Comment by hrydgard** [comment]
Cool, thanks for testing.
