### ISSUE TITLE
Rurouni Kenshin 2 multiplayer doesn't work android to android.

### ISSUE THREAD

**Issue by MajinDipu** [hrydgard/ppsspp#14554]
### What happens?
The game's full name is Rurouni Kenshin Meiji Kenkaku Romantan Kensai. It's a japanese only game. So the games multiplayer works fine PC to PC or Android to PC crossplay. But whenever I try to play Android to Android it doesn’t work. Both of us can see each other and accept challenge. Look

![Screenshot_20210622_235743_org ppsspp ppsspp](https://user-images.githubusercontent.com/75547787/122998327-b5b20a80-d3ce-11eb-8151-4274516fd459.jpg)
But when I try to move forward to the character select screen the host sees loading for like 30 sec.
![Screenshot_20210622_235754_org ppsspp ppsspp](https://user-images.githubusercontent.com/75547787/122998595-104b6680-d3cf-11eb-957c-fad6cb347ae9.jpg)
Then the host screen shows this msg in japanese after like 30 secs.
![Screenshot_20210622_235820_org ppsspp ppsspp](https://user-images.githubusercontent.com/75547787/122998681-29ecae00-d3cf-11eb-9583-eda63774aec5.jpg)
The client's screen is interesting because instead of a 30 seconds loading screen it instantly shows an error message like this:
![Screenshot_20210623_000240_org ppsspp ppsspp](https://user-images.githubusercontent.com/75547787/122998785-4c7ec700-d3cf-11eb-80fd-6ba6c81c75df.jpg)

Since the game is in Japanese here's how to play multiplayer:- Select the 5th option (going down) in the main menu. You will see 4 options there. The top one is for hosting and the 2nd one is for joining. Challenge with O and accept with O.

### What *should* happen?
It just should work! The error should not be there! And the host should not have 30 seconds loading screen. In crossplay between PC-Android, the lobby progresses to character select screen instantly.

#### What hardware / device and operating system?
2 Androids.
Used localhost on single PC and PC-Android crossplay before then it worked. It just Won't work in mobile-mobile situation. 
#### What graphics card (GPU) or mobile phone model?
Huawei Y9 and Huawei Y11 Prime. I also tried with a foreign dude. He was on android but I dunno what was his device.
#### What PPSSPP version (standalone/official), and did it work before?
v1.11.3-832
It always worked in android to PC crossplay and PC to PC but never worked mobile to mobile in previous versions. Didn’t even work with the stable versions.
#### Which game or games?
NPJH50658

#### Checklist
Note anything else you tried. --> I tried all methods like locally with hotspot, being in the same WiFi router network and online. Online with public server and with Zerotier.
Tried with both Fast memory on and off. Tried changing who hosts.
Tried disabling built in PRO ad-hoc server etc.
Results were always the same. Please fix this since I love this game so much but can't play on Go :(
 - [x] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [X] Try resetting settings or older versions and include if the issue is related.
 - [X] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment]
Thanks for providing the step-by-step guide to go into multiplayer, unfortunately i don't have 2 android phone to test this at the moment.

However, games that wasn't stable when playing with android can also be aftected by performance, usually if the host is running slower than the joining one it will have a higher chance for player to join and start the mission successfully.

May be you can try hosting the game on the slower device, or under clocking the host for a bit, usually only needed until everyone joined and multiplayer game has started.

**Comment by MajinDipu** [comment]
> Thanks for providing the step-by-step guide to go into multiplayer, unfortunately i don't have 2 android phone to test this at the moment.
> 
> However, games that wasn't stable when playing with android can also be aftected by performance, usually if the host is running slower than the joining one it will have a higher chance for player to join and start the mission successfully.
> 
> May be you can try hosting the game on the slower device, or under clocking the host for a bit, usually only needed until everyone joined and multiplayer mission started.

Thanks for the advice. But if my phone was slower than how can it crossplay with PC with no problem at all?

**Comment by ANR2ME** [comment]
Was the host on your phone or PC? because usually CPU emulation runs a bit better on a PC than a phone (PC's CPU usually have 2+ ghz clock while mobile CPU on a phone is a bit lower)

**Comment by MajinDipu** [comment]
Both. It works if android is the host and it also works when PC is the host.

**Comment by ANR2ME** [comment]
Hmm that is strange..
Have you make sure both Android device have the same settings on Networking and System settings?
Have you tried switching side on who Host and who Joined?

**Comment by MajinDipu** [comment]
Yes they are same. And I already mentioned that I tried changing who host.

**Comment by MojoJojoDojo** [comment]
Try to modify the timeout option on PPSSPP Networking settings.
You need to mess with it and increase it until it will work tho.

**Comment by MajinDipu** [comment]
So this issue is added to the future milestone. What does that mean? No fix anytime soon?

**Comment by hrydgard** [comment]
The milestones are mainly my own to-look-at-list. All it means is that I don't plan to look at this myself anytime soon, but of course anyone else is free to work on it.

**Comment by MajinDipu** [comment]
Please someone fix this! Please! OH DAMN IT!!

**Comment by ANR2ME** [comment]
Btw, does the other Rurouni Kenshin (ULJS-00360) have similar issue?

**Comment by ANR2ME** [comment]
Btw, error 80410718 = ERROR_NET_ADHOC_CONNECTION_REFUSED, which only triggered when a PTP 'connect' attempts got rejected/refused by the Host for some reason.. i hope you're not using the same MAC address on both side? sometimes using the same save data could be refused too.

May be try enabling "Force First Connect" on networking setting? if you're already not using the same savedata and not using the same MAC address.

**Comment by MajinDipu** [comment]
> Btw, does the other Rurouni Kenshin (ULJS-00360) have similar issue?
> 
Haven’t tested That. probably yes since both games have same engine?

**Comment by MajinDipu** [comment]
> Btw, error 80410718 = ERROR_NET_ADHOC_CONNECTION_REFUSED, which only triggered when a PTP `connect` attempts got rejected/refused by the Host for some reason.. i hope you
> May be try enabling "Force First Connect" on networking setting? if you're already not using the same savedata and not using the same MAC address.
Interesting. I used Force First Connect with same result. mac address was definitely different but I think we shared savedata each and everytime of tesing. But even having same savedata was no issue on PC.

btw, what is this log thing? maybe I can pull out the log and send a screenshot of it?

**Comment by ANR2ME** [comment]
On android there are app to get the "logcat" (something like Logcat Reader), you will need to filter it to separate PPSSPP logs from others.
But i'm not sure which app is the best one (the one with a lot of filtering method) since i'm not familiar with these app.

**Comment by MajinDipu** [comment]
Sounds too complex for me

**Comment by MajinDipu** [comment]
OK so I realized this problem still occurs without using same savedata. So it happens even if 2 players have different saves

**Comment by ANR2ME** [comment]
I wonder if this issue can be reproduced on Linux vs Linux too.. may be @MojoJojoDojo could test this with multiple instance on Linux?

**Comment by MojoJojoDojo** [comment]
> I wonder if this issue can be reproduced on Linux vs Linux too.. may be @MojoJojoDojo could test this with multiple instance on Linux?

Yeah it happens there but I have no idea how these logs gonna help you lol.

One side:
`39:39:784 user_main    I[SCENET]: HLE/sceNetAdhoc.cpp:2768 sceNetAdhocctlJoin(08af3a04) at 08903b14
39:39:797 idle0        I[SCENET]: HLE/proAdhoc.cpp:1457 Received 146 Bytes of Data from Adhoc Server
39:39:797 idle0        I[SCENET]: HLE/proAdhoc.cpp:1562 FriendFinder: Incoming OPCODE_CONNECT [dc:08:41:74:f1:f6][127.0.0.1][PPSSPP]
39:39:797 idle0        W[SCENET]: HLE/proAdhoc.cpp:225 Friend Peer Already Existed! Updating [dc:08:41:74:f1:f6][127.0.0.1][PPSSPP]
39:39:807 idle0        I[SCENET]: HLE/proAdhoc.cpp:1476 FriendFinder: Incoming OPCODE_CONNECT_BSSID [dc:08:41:74:f1:f6]
39:40:367 user_main    I[SCENET]: HLE/sceNetAdhoc.cpp:3153 sceNetAdhocPtpOpen(00:02:02:02:02:02, 0, dc:08:41:74:f1:f6, 777, 8880, 200000, 300, 0) at 08902278
39:40:367 user_main    E[SCENET]: HLE/sceNetAdhoc.cpp:3583 sceNetAdhocPtpConnect[1]: Socket Error (115) to 127.0.0.1:777
39:40:383 user_main    I[SCENET]: HLE/sceNetAdhoc.cpp:3648 sceNetAdhocPtpConnect(1, 0, 1) at 089023e8
39:40:383 user_main    E[SCENET]: HLE/sceNetAdhoc.cpp:3583 sceNetAdhocPtpConnect[1]: Socket Error (111) to 127.0.0.1:777
39:40:383 user_main    E[SCENET]: HLE/sceNetAdhoc.cpp:3619 80410718=sceNetAdhocPtpConnect(1, 0, 1): connection refused

Other side:
`39:39:142 user_main    W[SCENET]: HLE/sceNetAdhoc.cpp:4556 UNTESTED sceNetAdhocMatchingDelete(1) at 08901610
39:39:151 user_main    I[SCENET]: HLE/sceNetAdhoc.cpp:2416 Marked for Timedout Peer List (1)
39:39:151 user_main    I[SCENET]: HLE/sceNetAdhoc.cpp:2452 00000000=sceNetAdhocctlDisconnect() at 08901784 [group=]
39:39:154 idle0        I[SCENET]: HLE/proAdhocServer.cpp:1007 AdhocServer: PPSSPP (MAC: dc:08:41:74:f1:f6 - IP: 127.0.0.1) left NPJH50658 group 
39:39:284 user_main    W[SCENET]: HLE/sceNetAdhoc.cpp:4600 UNTESTED sceNetAdhocMatchingTerm() at 08901670
39:39:499 idle0        I[SCENET]: HLE/proAdhocServer.cpp:1105 AdhocServer: PPSSPP (MAC: 00:02:02:02:02:02 - IP: 127.0.0.2) requested information on 0 NPJH50658 groups
39:39:536 user_main    I[SCENET]: HLE/sceNetAdhoc.cpp:2743 sceNetAdhocctlCreate(g) at 08903b14
39:39:550 idle0        I[SCENET]: HLE/proAdhocServer.cpp:911 AdhocServer: PPSSPP (MAC: dc:08:41:74:f1:f6 - IP: 127.0.0.1) joined NPJH50658 group g
39:39:553 idle0        I[SCENET]: HLE/proAdhoc.cpp:1457 Received 7 Bytes of Data from Adhoc Server
39:39:553 idle0        I[SCENET]: HLE/proAdhoc.cpp:1476 FriendFinder: Incoming OPCODE_CONNECT_BSSID [dc:08:41:74:f1:f6]
39:39:642 idle0        I[SCENET]: HLE/proAdhocServer.cpp:1105 AdhocServer: PPSSPP (MAC: 00:02:02:02:02:02 - IP: 127.0.0.2) requested information on 1 NPJH50658 groups
39:39:794 idle0        I[SCENET]: HLE/proAdhocServer.cpp:911 AdhocServer: PPSSPP (MAC: 00:02:02:02:02:02 - IP: 127.0.0.2) joined NPJH50658 group g
39:39:796 idle0        I[SCENET]: HLE/proAdhoc.cpp:1457 Received 139 Bytes of Data from Adhoc Server
39:39:796 idle0        I[SCENET]: HLE/proAdhoc.cpp:1562 FriendFinder: Incoming OPCODE_CONNECT [00:02:02:02:02:02][127.0.0.2][PPSSPP]
39:39:796 idle0        W[SCENET]: HLE/proAdhoc.cpp:225 Friend Peer Already Existed! Updating [00:02:02:02:02:02][127.0.0.2][PPSSPP]
39:42:009 user_main    I[SCENET]: HLE/sceNetAdhoc.cpp:3727 sceNetAdhocPtpListen(dc:08:41:74:f1:f6, 777, 8880, 200000, 300, 1, 0) at 0890223c
39:42:010 user_main    I[SCENET]: Util/PortManager.cpp:206 PortManager::Add(TCP, 10777, 10777)
`

**Comment by ANR2ME** [comment]
Thanks for testing. 
I guess something on android/linux have a different reaction when communicating with other android/linux versus windows..

Btw, If PPSSPP is frozen to the point where you can't even goes back to PPSSPP settings by pressing ESC, it could be a race condition, can you still gets to PPSSPP settings on Hokuto no Ken?

**Comment by MojoJojoDojo** [comment]
Yeah tried everything with RK nothing really works for resolving that issue.
This game inits the ad-hoc in the very beginning of the game instead of the adhoc menu and I always noticed there are issues it casues for Android players etc.
For Hokuto , no its just progressing sometimes further and sometimes not and if it doesnt progress further it saves the game and gets back to the main menu...

**Comment by ANR2ME** [comment]
I made a small homebrew to test `PtpConnect` on Windows without anyone `PtpListen`ing on the port.
Apparently on Windows it never get `ECONNREFUSED` unless someone is listening on the port and intentionally refusing the connection, thus there is no way to simulate `ERROR_NET_ADHOC_CONNECTION_REFUSED` on Windows with non-blocking socket (since we're simulating blocking with non-blocking) because it will keeps returning `EWOULDBLOCK`.
While on JPCSP+prx it will return `ERROR_NET_ADHOC_CONNECTION_REFUSED` on non blocking, and also when it reached the timeout on blocking socket, which is similar behavior to Linux.

So, the conclusion is, the issue on this game happened because the Joining side is progressing faster than the Host side, and ended with trying to Connect before the Host ready to Listen, which can be considered as Timing issue.

There are 2 ways to solve this:
1. Returning `ERROR_NET_ADHOC_WOULD_BLOCK`(non-blocking) or `ERROR_NET_ADHOC_TIMEOUT`(blocking) instead of `ERROR_NET_ADHOC_CONNECTION_REFUSED` similar to Windows, However:
- This is not the accurate error code, since the accurate one is `ERROR_NET_ADHOC_CONNECTION_REFUSED`
- This will make PPSSPP to have the same behavior across platforms, since there is no way to simulate `ERROR_NET_ADHOC_CONNECTION_REFUSED` on Windows.
- This will make some games to work because `ERROR_NET_ADHOC_WOULD_BLOCK` will trigger the game to try again (depends on the game's netcode tho), But this is considered a Workaround instead of a proper Fix, and only worked for games that use PTP.
2. Try to detects a re-group done by the game, and synchronize the timing by blocking the thread when Creating/Joining a Group until everyone previously in the same group have all rejoined the new group before resuming the thread, However:
- This will only works if all players are running at the same pace/speed, otherwise there is a chance for the Joining side to resume the thread first and progressing faster than the Host, but the time difference shouldn't be as large as before.
- If we failed to detects a re-group and couldn't differentiate between a re-group done by the game when multiplayer mission started and a re-group done by the player himself, the game could ended frozen because the thread will be blocked until a timeout reached.
- This will solves many other timing issue that happened during a re-group (when multiplayer mission started), including on games that use PDP.

So, i'm having a dilemma on what would be the best solution LOL

**Comment by MajinDipu** [comment]
Wow! Is there any way to combine both solutions? 

And if I understand correctly then 1st solution doesn’t need bith device to have exact same speed right? Would not that be the best solution then? (I understand nothing about coding. So apology in advance)

**Comment by MojoJojoDojo** [comment]
You know , I understand why neither Citra or Dolphin implements Netplay in their Android builds (althought it works in Linux).
It's just too much to handle all the various platform differences.

**Comment by MajinDipu** [comment]
Shut Up Mojo! You will demotivate him!

**Comment by ANR2ME** [comment]
> 
> 
> Wow! Is there any way to combine both solutions?
> 
> And if I understand correctly then 1st solution doesn’t need bith device to have exact same speed right? Would not that be the best solution then? (I understand nothing about coding. So apology in advance)

That would be mixing workaround with a proper fix, although it can improve user experience with higher success rate by preventing the game to stop retrying to Connect while waiting for the other side getting ready to Listen.
However, most of the time we removes workaround after having a proper fix, but in this case a proper fix is hard to get as different players may use different devices from a low performance on low-end devices to high performance on high-end devices could cause the faster one to progress too far from the slower one, especially when it takes a really long time for the slower one during "Loading.." screen.

**Comment by MojoJojoDojo** [comment]
I am in for replacing "force first connect" with whatever the new workaround would be.

**Comment by ANR2ME** [comment]
I guess we can start with implementing the workaround first since we're running out of time for 1.12, and try the 2nd method for version 1.13

Btw, "Force First Connect" have it's own purpose, which is used on games that will only try to connect once per socket, but i only know one game that have such method to connect, which is GvG Next Plus, not sure if there are other games that use the same method with GvG.
And the reason why i put that workaround in networking settings is to find out whether there are games that will be affected by it (assuming it use similar method to GvG) so i can fix that game properly.
But apparently we never received any reports about games that makes a different when FFC enabled or not, or may be most players likes to enable all the settings even without knowing what it's used for LOL and didn't realized whether the game need FFC or not because they always enabled it.
Also, based on what i found from Shinseiki GPX Cyber Formula VS recently, is that there are games that will only try once and didn't do a re-try, which is similar to GvG but in this case it use PDP instead of PTP, thus not affected by FFC.

**Comment by MajinDipu** [comment]
> 
> The 1st one is easier to implement and have minimal risk of freezing the game, this will make the game to keep trying to connect until the other side is ready to listen, but some games are calculating their own timeout, so they may only wait for a short time, while the time gap between the slowest one vs the fastest one may still be large enough for some games to consider it as reaching the timeout.
> 
Yeah go with the first one

**Comment by MajinDipu** [comment]
> I guess we can start with implementing the workaround first since we're running out of time for 1.12, and try the 2nd method for version 1.13
> 
This sounds like a wise start

**Comment by MojoJojoDojo** [comment]
> I guess we can start with implementing the workaround first since we're running out of time for 1.12, and try the 2nd method for version 1.13
> 
> Btw, "Force First Connect" have it's own purpose, which is used on games that will only try to connect once per socket, but i only know one game that have such method to connect, which is GvG Next Plus, not sure if there are other games that use the same method with GvG or not. And the reason why i put that workaround in networking settings is to find out whether there are games that will be affected by it (assuming it use similar method to GvG) so i can fix that game properly. But apparently we never received any reports about games that makes a different when FFC enabled or not, or may be most players likes to enable all the settings even without knowing what it's used for LOL and didn't realized whether the game need FFC or not because they always enabled it. Also, based on what i found from Shinseiki GPX Cyber Formula VS recently, is that there are games that will only try once and didn't do a re-try, which is similar to GvG but in this case it use PDP instead of PTP, thus not affected by FFC.

You dont need it in gundam next plus anymore...
Tried it recently lol.
i tried all of the gundam games recently and they all work fine :S

**Comment by ANR2ME** [comment]
> 
> 
> > I guess we can start with implementing the workaround first since we're running out of time for 1.12, and try the 2nd method for version 1.13
> > Btw, "Force First Connect" have it's own purpose, which is used on games that will only try to connect once per socket, but i only know one game that have such method to connect, which is GvG Next Plus, not sure if there are other games that use the same method with GvG or not. And the reason why i put that workaround in networking settings is to find out whether there are games that will be affected by it (assuming it use similar method to GvG) so i can fix that game properly. But apparently we never received any reports about games that makes a different when FFC enabled or not, or may be most players likes to enable all the settings even without knowing what it's used for LOL and didn't realized whether the game need FFC or not because they always enabled it. Also, based on what i found from Shinseiki GPX Cyber Formula VS recently, is that there are games that will only try once and didn't do a re-try, which is similar to GvG but in this case it use PDP instead of PTP, thus not affected by FFC.
> 
> You dont need it in gundam next plus anymore... Tried it recently lol. i tried all of the gundam games recently and they all work fine :S

Of course you won't needed it anymore on GvG because i already properly fix games that known to connect once per socket, what i need to know is other games using similar method with GvG, so i can fix them too just like GvG.

**Comment by ANR2ME** [comment]
Please try the artifacts from PR https://github.com/hrydgard/ppsspp/pull/14969 if it's helps or not for this issue.

**Comment by MojoJojoDojo** [comment]
Can confirm that this workaround made the game work now at least on Linux multiple instances.
I thought maybe it gonna help Hokuto but nope.

**Comment by MajinDipu** [comment]
> Can confirm that this workaround made the game work now at least on Linux multiple instances. 

Wow! really? Is this the version 1.11.3-1654 that you used?

**Comment by ANR2ME** [comment]
I haven't checked Hokuto no Ken because the logs you provided wasn't as informative as your Rourouni Kenshin 2 logs :)
Things like socket error can be informative, i'll post it on the other thread when i found something about it.

**Comment by MojoJojoDojo** [comment]
I think its a timing issue like you said because one instance go faster then the other and inputs are delayed on one instance as well.

**Comment by MajinDipu** [comment]
This thing can be considered fixed by now. Thanks @ANR2ME for finding the problem and solving it. Also shoutout to @MojoJojoDojo for his log contribution
