### ISSUE TITLE
Transfer save files between PPSSPP and OpenEmu

### ISSUE THREAD

**Issue by Roanoke2015** [hrydgard/ppsspp#14568]
Hey there! Does anyone know if it's possible to transfer PPSSPP save files to OpenEmu? OpenEmu uses PPSSPP core so it should be possible, but so far I did not manage to do it. Thanks!

Note: Using macOS Big Sur 11.4

**Comment by ANR2ME** [comment]
Copying the game's title folders inside SAVEDATA folder should be enough isn't?

**Comment by hrydgard** [comment]
Yeah. Don't think there's much else to discuss here, closing.
