### ISSUE TITLE
some korean characters are not shown in settings

### ISSUE THREAD

**Issue by british-choi** [hrydgard/ppsspp#14579]
### What happens?
some korean characters are not shown in settings

### What *should* happen?
all korean characters should be shown in settings

#### What hardware / device and operating system?
Odroid Go Advance / EmuELEC

#### Which game or games?
all

korean.txt is very old file.
After running make-font-textfiles.sh, need to create a new zim file.

**Comment by hrydgard** [comment]
Yeah, it's fallen behind, sorry. Mostly because we use native fonts instead on many platforms now so it's not as noticeable...

**Comment by hrydgard** [comment]
I updated the atlas with the current lang file, so should be ok or at least better now.

**Comment by british-choi** [comment]
> I updated the atlas with the current lang file, so should be ok or at least better now.

Sorry, I checked in commit ID eb0f0d3
However, it was not modified.
please tell me how can I generate the zim file

**Comment by hrydgard** [comment]
Hm, I'll look into that. If you have built the atlas generator, you should be able to run the script buildatlas.sh , which is supposed to learn the required characters from korean.txt, but apparently that didn't work then somehow...

**Comment by british-choi** [comment]
I'm so sorry. I made a mistake.
This issue is fixed.
The ui_atlas files in my device were not updated.
I tested it again. Works fine.
Thanks.

**Comment by hrydgard** [comment]
ok. thanks for reporting!
