### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by imad17** [hrydgard/ppsspp#14595]
C/C++ normalDebug|arm64-v8a : CMake Error at C:/Users/fhjuk/AppData/Local/Android/Sdk/cmake/3.10.2.4988404/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PythonInterp: Found unsuitable version "1.4", but required
  is at least "3" (found
  C:/Users/fhjuk/AppData/Local/Microsoft/WindowsApps/python3.exe)
Call Stack (most recent call first):
  C:/Users/fhjuk/AppData/Local/Android/Sdk/cmake/3.10.2.4988404/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:376 (_FPHSA_FAILURE_MESSAGE)
  C:/Users/fhjuk/AppData/Local/Android/Sdk/cmake/3.10.2.4988404/share/cmake-3.10/Modules/FindPythonInterp.cmake:152 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  ext/glslang/CMakeLists.txt:297 (find_package)

**Comment by hrydgard** [comment]
you need to install Python to build. Sorry, this should indeed be added to the build instructions.

**Comment by unknownbrackets** [comment]
This is noted in the instructions:
https://github.com/hrydgard/ppsspp/wiki/Build-instructions#prerequisites

-[Unknown]
