### ISSUE TITLE
[Windwos][Graphic Glitch] Monster Hunter 3rd HDver. (NPJB40001)

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#14601]
### What happens?
Monster Hunter Portable 3rd HDver.(NPJB40001)
Graphic Glitch happen since v1.11.3-853.
Please see attached GEdump.
[NPJB40001_0003.zip](https://github.com/hrydgard/ppsspp/files/6795318/NPJB40001_0003.zip)

![image](https://user-images.githubusercontent.com/48179091/125163997-ccc46b00-e1ca-11eb-95d0-f19db49b50ce.png)

### What *should* happen?
Fix the glitch.

#### What hardware / device and operating system?
OS：Windows10（64-bit）Japanese
CPU：Ryzen7 3800X（8-core）
Resolution：2560×1440
RAM：32GB
#### What graphics card (GPU) or mobile phone model?
GPU：RADEON RX5700XT
#### What PPSSPP version (standalone/official), and did it work before?
v1.11.3-849
#### Checklist

 - [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [X] Try resetting settings or older versions and include if the issue is related.
 - [X] Include logs or screenshots of issue.

**Comment by Gamemulatorer** [comment]
What gfx backend are you using?
Vulkan,OpenGL or Direct3D?

**Comment by nassau-tk** [comment]
Oh,Thanks.

This issue will happen Vulkan.

**Comment by Gamemulatorer** [comment]
![Screenshot_2021-07-10-22-13-11-127_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/125166000-1a8da300-e1cc-11eb-8a55-96570604aedb.jpg)
Can't reproduce on my Redmi Note 9 Vulkan

**Comment by nassau-tk** [comment]
@Gamemulatorer 

Yes, My Galaxy S20 too.

**Comment by hrydgard** [comment]
Thanks for reporting, this is definitely #14588 . I seem to have missed something ...

**Comment by hrydgard** [comment]
I reverted the change for now in 7e048db . Will try again later.
