### ISSUE TITLE
[Android] Broken Games List sorting

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#14607]
### What happens?
On Android Device.
"Games List" is not sorting correctly.(Maybe)
I was teach about sort rule in "Discord".
"It is alphabetically of Game Title."(Not Filename)
But, My phone is not do it now.

Top of  list ==> Kanji Title Game   (Equal to filename = Kanji)
2nd of list  ==> Number title Game (Equal to filename = Number)
![498507](https://user-images.githubusercontent.com/48179091/125282243-1e4b3200-e352-11eb-9e6e-c4d4900aa6bf.jpg)

### What *should* happen?
I want know that "What rule is correctly on sorting".
And, fix it.
#### What hardware / device and operating system?
PPSSPP Ver.：1.11.3-901
OS：Android 11.0
DeviceName：Samusung Galaxy S20 / SC-51A
CPU：Snapdragon865（Octa-core）
GPU：Adreno 650
Resolution：3200 x 1440 (Max)
RAM：12GB
ROM：128GB
ExternalStrage：microSDXC 512GB

#### Checklist

 - [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [X] Try resetting settings or older versions and include if the issue is related.
 - [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
It is sorted by filename indeed currently.

A problem with sorting it by anything else is that when the list is loaded, we might not yet have loaded the actual game titles. So as they are loaded we would have to re-sort the list over and over, and it could look odd indeed.

**Comment by nassau-tk** [comment]
Oh... Exactly....
My phone is very long loading time when choose SD card at ROM path select.

**Comment by hrydgard** [comment]
I have some ideas to possibly make it a bit faster. But yes, it's related to all that stuff.

**Comment by nassau-tk** [comment]
Probably, The Broken list loading was solved by v1.11.3-906.

Of course, If startup PPSSPP and touch  Games then re-loading for ROM path every time (about 5sec.).

**Comment by hrydgard** [comment]
5 sec is a lot longer than I would have expected :( 

I hope to improve on this with a few methods in the future though.

In the meantime, you could try splitting your games into subfolders....
