### ISSUE TITLE
Merge assets/lang back into the main repo?

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#14612]
The volume of commits to assets/lang is very small these days, it no longer makes much sense to keep them separate. If there are no objections, I'll merge it next week.

**Comment by nassau-tk** [comment]
Is it means "not enough speed" on UI translation?

Exactlly, I feel too that not enough speed on translation.

**Comment by unknownbrackets** [comment]
My only concern with this is bisecting / updates of existing repos.  It gets annoying when the same path has submodules in a previous commit but real files in a later commit.  But otherwise I have no strong opinion on this either way, it probably makes sense.

-[Unknown]
