### ISSUE TITLE
how to disable "ctrl" hotkey ?

### ISSUE THREAD

**Issue by littlefunny233** [hrydgard/ppsspp#14615]
### What should happen?
disable it while binded to a psp button. or other options to disable it.

### Who would benefit from it?
won't trigger hot key, such like "ctrl + w"

#### Checklist

 - [ ] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
 - [ ] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by unknownbrackets** [comment]
There's already an option for this in the latest git build.  That's why the template encourages you to check.  See #14229.

-[Unknown]

**Comment by littlefunny233** [comment]
> There's already an option for this in the latest git build. That's why the template encourages you to check. See #14229.
> 
> -[Unknown]

as you see, there are many "lazy" end users at every projects, i just role play as one of them this time, to see how the attitude
 of dev. group :)
