### ISSUE TITLE
the problem with driver76 ppsspp

### ISSUE THREAD

**Issue by kirby-es-pedofilo** [hrydgard/ppsspp#14610]
### What happens?
whre play driver 76 something happens there closed the windows automatic

### What *should* happen?
open the gmae

#### What hardware / device and operating system?
windows 10 may 2020
#### What PPSSPP version (standalone/official), and did it work before?
13.3
#### Which game or games?

idk
#### Checklist

 - [x ] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [ ]x [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [ x] Try resetting settings or older versions and include if the issue is related.
 - [ x] Include logs or screenshots of issue.
![ULUS10235_00010](https://user-images.githubusercontent.com/85515664/125376749-86911800-e340-11eb-8d2e-76bcefaffb11.jpg)

**Comment by Gamemulatorer** [comment]
Related https://github.com/hrydgard/ppsspp/issues/12054

**Comment by unknownbrackets** [comment]
This seems likely to be the same issue as #12054 - there seems to be an issue in this game related to IO timing.  Once that's fixed, we'll validate other backends.  If changing IO timing settings as a workaround now doesn't help, comment and we can reopen.

-[Unknown]
