### ISSUE TITLE
I can't see folder

### ISSUE THREAD

**Issue by IrfanH495** [hrydgard/ppsspp#14629]
### What happens?
v1.11.3-931-g6daa18cca 
I can't see my folder
https://drive.google.com/file/d/1-2zygYzxAyXmLjQFBpfd6PzNiECIQitG/view?usp=drivesdk
#### What hardware / device and operating system?
Sharp sh04h
Oreo 8.0.0
Adreno 530
#### Checklist

 - [ ] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [ ] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [ ] Try resetting settings or older versions and include if the issue is related.
 - [ ] Include logs or screenshots of issue.

**Comment by Gamemulatorer** [comment]
Wait for the next build development apk on ppsspp buildbot https://buildbot.orphis.net/ppsspp/index.php?m=fulllist

**Comment by hrydgard** [comment]
Hm, should not be related ... Weird. I'll look into it, did this just start happening in the latest builds?

**Comment by IrfanH495** [comment]
v1.11.3-942-g87dcf60ed still bug
![Screenshot_20210720-013843](https://user-images.githubusercontent.com/78854859/126210298-acce9014-4193-49db-8345-6a8deff0f541.png)

v1.11.3-930-gf18a5ed6c
![Screenshot_20210720-013536](https://user-images.githubusercontent.com/78854859/126210399-2c13548f-ecff-4048-b615-dc476f0d80e7.png)

**Comment by hrydgard** [comment]
I fixed a bug that I think might have caused this in 9640636, please try when the build is up.

Sorry for the trouble.

**Comment by IrfanH495** [comment]
it works, thanks
