### ISSUE TITLE
[Libretro] English replaced by Vietnamese for some reason

### ISSUE THREAD

**Issue by bslenul** [hrydgard/ppsspp#14633]
### What happens?
English language is replaced with Vietnamese, the PSP texts I mean, not the ingame language:

![image](https://user-images.githubusercontent.com/33353403/126678180-02f9f0aa-1d80-440c-ab64-b71ebf4f09b2.png)

The other languages don't seem affected, just English. And deleting `lang/vi_VN.ini` fixes the issue:

![image](https://user-images.githubusercontent.com/33353403/126678456-fc93c836-196a-4d28-b43f-004c0c70c56e.png)

### What *should* happen?
English should display in English :p 

#### What hardware / device and operating system?
Windows 10 / i5-4670K / GTX 970

#### What PPSSPP version (standalone/official), and did it work before?
Libretro core, latest version from the core updater (~~e3c748c~~ **edit:** 868f5f6 now, but the issue is still here). Yes it worked before, I've seen that "lang" isn't a submodule anymore, idk if it's related or not.

#### Which game or games?
Any game.

#### Checklist

 - [x] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [x] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [x] Try resetting settings or older versions and include if the issue is related.
 - [x] Include logs or screenshots of issue.

**Comment by bslenul** [comment]
Hm, noticed that in the standalone, if I set the language to English I have this in my `ppsspp.ini`:
```
Language = en_US
Language = 1
```
and if I set it to Vietnamese I have:
```
Language = vi_VN
Language = 1
```
So it looks like if multiple languages use the same value, the libretro core picks the last one or something like this?

**Comment by stuken** [comment]
Introduced with https://github.com/hrydgard/ppsspp/commit/19721a0a5f2cf3bede5b0a323a681cccd4894a77
This probably should be rolled back until a proper solution is implemented to map RETRO_ENVIRONMENT_GET_LANGUAGE to the i18n managed text.

**Comment by bslenul** [comment]
Thanks for the fix, once again! ❤️
