### ISSUE TITLE
Is AMD FSR feasible in PPSSPP?

### ISSUE THREAD

**Issue by Leopard20** [hrydgard/ppsspp#14630]
I'm assuming due to the bad quality of PSP games it may not work well, and I'm not sure about the performance either, but still I figured maybe I should ask anyway.

**Comment by hrydgard** [comment]
It does look like it might be possible, but I don't know if there would be any real benefit compared to just increasing the rendering resolution.

**Comment by mlwj1993** [comment]
Might be useful for running 4k on a GPU that can't always handle it. For anything else likely niche usecases.

**Comment by hrydgard** [comment]
Closing this in favor of #14689 . (Yes, this one is older, but the other hsa a better title).
