### ISSUE TITLE
Autogenerated CWCheat .ini files are corrupted

### ISSUE THREAD

**Issue by NABN00B** [hrydgard/ppsspp#14635]
### What happens?
When I launch a game for the first time with the build-in CWCheat support enabled, the generated .ini file becomes corrupted. This renders the first cheat in the file invalid, even though the code for it is correct (literally copy-pasted from another file in which it works). Duplicating the entire cheat entry, even when separated by other entries, will make the duplicate work as intended.
![kép](https://user-images.githubusercontent.com/22328803/126840247-853ca8e8-fd20-4e59-b90c-5c65cbf21cda.png)
Screenshot 1: first cheat appears as invalid (and gets ticked automatically) in PPSSPP interface.
![corrupt1](https://user-images.githubusercontent.com/22328803/126840282-bdb88e34-b89f-427d-a284-070897cd0221.png)
Screenshot 2: An autogenerated .ini file viewed in hex editor.

### What *should* happen?
Generated file should be clean (0 bytes).

#### What hardware / device and operating system?
Win10 x64

#### What PPSSPP version (standalone/official), and did it work before?
v1.11.3

#### Checklist

 - [ ] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [X] Try resetting settings or older versions and include if the issue is related.
 - [X] Include logs or screenshots of issue.

**Comment by Linblow** [comment]
Looks like UTF-8 with BOM

**Comment by Linblow** [comment]
I tested with the latest commits, and the UTF-8 BOM sequence is properly ignored with these tests in `CwCheats.cpp`:
```
if (line.length() >= 5 && line[0] == '_') {
...
```
Now, we still should properly detect that UTF-8 sequence.
Will post PR

**Comment by Linblow** [comment]
I tested with the latest commits, and the UTF-8 BOM sequence is properly ignored with these tests in `CwCheats.cpp`:
```
if (line.length() >= 5 && line[0] == '_') {
...
```
Now, we still should properly detect that UTF-8 sequence.
Will post PR

**Comment by unknownbrackets** [comment]
Is this no longer an issue in #14648?

It's probably not an issue for the new file to have a BOM, in case someone's system is configured to use another character set by default, such as Big-5 or Shift-JIS.

-[Unknown]

**Comment by Linblow** [comment]
Afaik, it's no longer an issue. Note this PR didn't fix anything, it only explicitly detects the BOM, and ignores it, in case the parsing algorithm changes in the future.

**Comment by NABN00B** [comment]
Just tested it, the issue seems to be gone.
