### ISSUE TITLE
Sonic Rivals 2 Multiplayer not working "Failed to bind port 1, Please change your port offset"

### ISSUE THREAD

**Issue by Jerdo32** [hrydgard/ppsspp#14640]
### What happens?
When I go to Multiayer, then Wireless Play, "Network Initialized" appears, and then "Failed to bind port 1, Please change your port" appears in red. If I try creating and joining a game, nothing happens. (Done with 2 Samsung phones using same IP Adress and wifi)

### What *should* happen?
Only "Network Initialized" should appear and I should create and join with both mobile phones.

#### What hardware / device and operating system?
Mobile Phone (Android)
#### What graphics card (GPU) or mobile phone model?
Samsung Galaxy A32 5G
#### What PPSSPP version (standalone/official), and did it work before
1.11.3 (Not sure if it worked before)
#### Which game or games?
SONIC RIVALS 2 (ULUS10323)

#### Checklist

 - [ ] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [x] Try resetting settings or older versions and include if the issue is related.
 - [X] Include logs or screenshots of issue.
![Screenshot_20210724-210826_PPSSPP](https://user-images.githubusercontent.com/53071715/126884563-b0e57625-cc3a-48e6-aa46-a1cfe6a27e87.jpg)

**Comment by MojoJojoDojo** [comment]
Well it tells you to change the port offset.
Never got why it never tells you it needs to be above 1024 though.
The default port offset is 10000 now so people should get less issues like that lol.

**Comment by Jerdo32** [comment]
> Well it tells you to change the port offset.
> Never got why it never tells you it needs to be above 1024.
> The default port offset is 10000 now so people should get less issues like that lol.
> This is one of the games I remembered getting the incorrect port issue with someone tho.
> i guess that anoher issue is that the port offset is too low now in the Networking options so no one sees it now...

I had already tried changing the port (over 1024), but it still gave me the messages. However, the game was already running. I closed the emulator, reopened it, changed the port offset, and then I opened the game. This time it didn't give me the message and I was able to play a few multiplayer rounds.
