### ISSUE TITLE
Multiplayer nicknames may need a size limit?

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#14643]
This was posted on Discord:

![image](https://user-images.githubusercontent.com/130929/126904531-29ee47b0-0a10-495c-80f6-734efd623496.png)

:)

**Comment by Linblow** [comment]
An adhocctl nickname is 128-bytes max in the official PSP API, and proAdhoc. 
Surely, the name displayed in the chat could be truncated. May be 16 chars max?

**Comment by hrydgard** [comment]
Ah, if the protocol supports 128 we should probably stick to that internally and just truncate in chat. I feel 20-24 might be a good limit...
