### ISSUE TITLE
Game ISOs get unmounted on sceKernelLoadExec (new bug)

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#14650]
Since #14638, once the executable gets unloaded in preparation for loading a new one, we lose the ISO mount because sceKernelLoadExec ends up shutting down and restarting the I/O subsystem, and we now unmount all filesystems, which is a mistake (or we should auto-remount the ISO after).

This of course breaks games that do this like Power Stone Collection.

Will fix soon, thanks Sorer for reporting.

**Comment by MojoJojoDojo** [comment]
Does this mean that the bug won't happen if you got the game in a PBP format?

**Comment by hrydgard** [comment]
Don't think it matters. I'm just gonna fix it anyway, stay tuned.
