### ISSUE TITLE
Square shape for custom buttons

### ISSUE THREAD

**Issue by Leopard20** [hrydgard/ppsspp#14657]
A square shape would be very neat.

**Comment by XiaomiRedmi9** [comment]
Related https://github.com/hrydgard/ppsspp/issues/14515?

**Comment by Leopard20** [comment]
I'll put it there for now.

**Comment by iota97** [comment]
I'm having quite some problem building the atlas tool on widows too, gotta fix that build environment when I get the time eheh.

Anyway [this](https://github.com/iota97/ppsspp/tree/square-shape) should work once the atlas file get rebuild...

**Comment by Leopard20** [comment]
Wat?! You're posting in the wrong place!
