### ISSUE TITLE
Add another custom analog for touch controls

### ISSUE THREAD

**Issue by radityaargap** [hrydgard/ppsspp#14654]
I think having the option to add another custom analog would be great for touch screen users. Especially for those who don't like visual clutter and set button opacity to zero, like me 😅.

Personally I would map the custom analogs to the action buttons and L/R.

Because with the buttons being invisible, I feel that it's so much easier to do a swipe gesture than to press on a small button on a specific place on the screen.

### What should happen?
Having one more custom analog for touch controls

### Who would benefit from it?
Android, iOS users

#### Hardware, device, or operating system?
Snapdragon 450, Redmi 5, Android Pie

#### Specific games?

All games in general

### Does anything else have a similar feature?
Adaptive buttons on ePSXe gave me this idea

#### Checklist

 - [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
 - [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by radityaargap** [comment]
On second though, please add TWO more custom analogs 😁
I would set them up like this:
![ppsspp](https://user-images.githubusercontent.com/79243430/127274588-0179801c-7572-42a4-a763-a4d99d0905d0.png)
I'm sure swipe gestures will feel so much more natural on a touch screen than small buttons.

**Comment by iota97** [comment]
I think having 4 analog might be quite confusing for the end user, not sure if is a good option to have. 

Anyway I quickly make a build to test it if you like: [download apk](https://drive.google.com/file/d/1fPZTlSjy1V8ibQqyI6CeWLRiQdXJiIWs/view?usp=sharing) and [source code](https://github.com/iota97/ppsspp/tree/4-analog).

**Comment by radityaargap** [comment]
Wow, you are amazing, thanks a lot. I've tried the build and it's just what I wanted.

Some things that would improve this would be:

1. Adding the option to disable diagonal input. Because when I map the analog to the action buttons I accidentally do a combo often.

2. Marking the analog icons with numbers to avoid confusion figuring which analog is which.

But even without the things I mentioned, just adding one more custom analog would be good enough for most games, no need to put 4 😅.

I hope it's not too much work and I would love to see it being implemented in the stable build.

**Comment by iota97** [comment]
Quite simple things to do and it's a rainy holiday day so why not eheh :)

I updated the APK ([same download link as before](https://drive.google.com/file/d/1fPZTlSjy1V8ibQqyI6CeWLRiQdXJiIWs/view?usp=sharing)) with the change from #13107 too, you may find these new setting in the control tab in the "Gesture Mapping" menu below the "Button Style" setting. They are far from great, but you may find them handy (the double tap one at least).

About them being 4 is just that while you add 2 adding 4 is just a bit more copy paste.

For the stable build much depends on what hrydgard think about this, I can open a PR if he likes.

**Comment by radityaargap** [comment]
Oh, man. This is just too good. Without diagonal inputs, the custom analogs work perfectly now. And your implementation of gesture mapping is exactly what I wanted in the first place! 😁 This is how adaptive buttons in ePSXe works.

This will make playing with touch controls so much easier. Please @hrydgard, these features need to be implemented 😁.

**Comment by XiaomiRedmi9** [comment]
You can't enjoy playing with too many buttons on screen 👎

**Comment by radityaargap** [comment]
Well, if you had spent some time to read the whole thing, you'll find that I said I always set button opacity to zero. So, I don't see any buttons.

Nevertheless, who are you to decide what I enjoy and what I don't?

**Comment by radityaargap** [comment]
the new touch gesture is a good enough subtitute for this.

**Comment by pandji007** [comment]
can i ask for this issue to be reopened please? i also wanted to request just 1 more custom analog.

i tried iota's build above and it's very useful in games that use so many button combo like L+dpad, L+action button, R+action button.for example: justice league heroes, xmen legends and marvel ultimate alliance 1&2.

if i were to use the regular combo buttons i would end up with too many buttons on the screen. unfortunately the build iota made was based on an older version without #14843 implemented. that is all, thanks.
