### ISSUE TITLE
"tap to customize" string not translatable

### ISSUE THREAD

**Issue by ppmeis** [hrydgard/ppsspp#14668]
I'm trying to add some strings inside Controls - Customize Touch Controls - Customize. I can't translate "tap to customize" in any why. I tried adding on MappableControls section the strings below, but nothing works:

(tap to customize) = 
 (tap to customize) = # This one with an space at the beginning of the string
' (tap to customize)' =

Any more ideas?

Here is the line
https://github.com/hrydgard/ppsspp/blob/8d7f57c4721e450a94c04238c8db3b39ca8f6a72/UI/TouchControlVisibilityScreen.cpp#L141

Also Right Analog Stick (tap to customize) =  is no longer translating anything.

**Comment by iota97** [comment]
Mhhh sorry this is my bad, should have thought ini is parsed ignoring leading space.

After #14671 is merged you should be able to use `tap to customize = ...`
