### ISSUE TITLE
Build fails on Debian 10 aarch64

### ISSUE THREAD

**Issue by vanfanel** [hrydgard/ppsspp#14665]
### What platform, compiler, and build tools?

Debian 10 aarch64 running on Raspberry Pi 4.
GCC version 8.3.0

### What compile flags or command did you run specifically?
`cmake .. -DUSING_X11_VULKAN=OFF -DUSING_GLES2=ON -DUSE_FFMPEG=OFF -DUSE_MINIUPNPC=OFF -DUSE_DISCORD=OFF -DCMAKE_C_FLAGS="-DEGL_NO_X11" -DCMAKE_CXX_FLAGS="-DEGL_NO_X11"`

### What happens (don't forget logs)?
```
[ 72%] Building CXX object CMakeFiles/Core.dir/Core/HLE/sceAtrac.cpp.o
/home/pi/src/ppsspp/Core/HLE/sceAtrac.cpp: In function 'u32 _AtracDecodeData(int, u8*, u32, u32*, u32*, int*)':
/home/pi/src/ppsspp/Core/HLE/sceAtrac.cpp:1221:30: error: 'struct Atrac' has no member named 'packet_'
      int packetSize = atrac->packet_->size;
```

#### What hardware / device and operating system?
Raspberry Pi 4 running Debian 10 aarch64, gcc 8.3.0

#### What PPSSPP version (standalone/official), and did it work before?
Current GIT code

#### Checklist

 - [ X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [ X] Don't forget `git submodule update --init --recursive`.
 - [ X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [ X] Try deleting the build directory and starting fresh.
 - [ X] Include logs and help us reproduce.
 - [ X] Check GitHub Actions, which builds every merge and PR.

**Comment by unknownbrackets** [comment]
Building without FFmpeg is no longer really supported and we should probably just remove the option.  We could make it work, but there will be game bugs (outside of videos, music, voices, and some sound effects not working.)

-[Unknown]

**Comment by vanfanel** [comment]
@unknownbrackets I have removed `-DUSE_FFMPEG=OFF`
and I am now trying to configure build with:
`
cmake .. -DUSING_X11_VULKAN=OFF -DUSING_GLES2=ON -DUSE_DISCORD=OFF -DCMAKE_C_FLAGS="-DEGL_NO_X11" -DCMAKE_CXX_FLAGS="-DEGL_NO_X11"`

But I get this:```

CMake Error: File /home/pi/src/ppsspp/ext/miniupnp/miniupnpc/miniupnpcstrings.h.cmake does not exist.
CMake Error at CMakeLists.txt:2007 (configure_file):
  configure_file Problem configuring file
```

I DID run `git submodule update --init --recursive`, but still I am missing `ext/miniupnp/miniupnpc/miniupnpcstrings.h.cmake`

Any ideas?

**Comment by vanfanel** [comment]
@unknownbrackets I removed 

now I am configuring build with

`cmake .. -DUSING_X11_VULKAN=OFF -DUSING_GLES2=ON -DUSE_DISCORD=OFF -DCMAKE_C_FLAGS="-DEGL_NO_X11" -DCMAKE_CXX_FLAGS="-DEGL_NO_X11"
`
and now I get this at the linking phase:

```
[100%] Linking CXX executable PPSSPPSDL
/usr/bin/ld: ../ffmpeg/linux/aarch64/lib/libavformat.a(avienc.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `__stack_chk_guard@@GLIBC_2.17' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../ffmpeg/linux/aarch64/lib/libavformat.a(avienc.o)(.text+0xc): unresolvable R_AARCH64_ADR_PREL_PG_HI21 relocation against symbol `__stack_chk_guard@@GLIBC_2.17'
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
```

**Comment by unknownbrackets** [comment]
You may need to recompile FFmpeg.  All you should need to do is run:

```sh
pushd ../ffmpeg
./linux_arm64.sh
popd
```

If that doesn't work, you can try system FFmpeg as a backup plan, using `-DUSE_SYSTEM_FFMPEG=ON`.  That said, I recommend trying a compile first as this most likely will use a newer FFmpeg that has removed APIs some PSP games need to run properly (although many popular games work fine with a workaround we have, so maybe you won't notice.)

-[Unknown]

**Comment by vanfanel** [comment]
@unknownbrackets That worked! I got the PPSSPP executable to link!
Any idea on why is that manual ffmpeg building necessary?

**Comment by unknownbrackets** [comment]
Different compiler versions and glibc versions link differently.  I think it should just always rebuild FFmpeg on Linux, and reuse the prebuilt only on Android and Windows where building is a bit more of a pain.  I think we already have another issue for that...

-[Unknown]

**Comment by vanfanel** [comment]
@unknownbrackets Ah, so whats happening here is that it was trying to use a prebuilt version. I see. I think this issue can be closed now, after all I got PPSSPP to build and link! :)

Thanks a lot for your patient help.
