### ISSUE TITLE
[Libretro] With Vulkan driver, RetroArch crashes when fast-forwarding

### ISSUE THREAD

**Issue by bslenul** [hrydgard/ppsspp#14675]
### What happens?

While making the 2 videos for https://github.com/hrydgard/ppsspp/issues/13115#issuecomment-890869162 , I've noticed that RetroArch crashes a lot while fast-forwarding when using Vulkan (I had to switch to GLcore), it can happen after a second, sometimes after 30 seconds, it's a bit random. Seems to only happen with Vulkan, I couldn't trigger the crash with GLcore and D3D11.

This is what I get in the logs: `[libretro ERROR] [SYSTEM] (../Common/GPU/Vulkan/VulkanRenderManager.cpp:VulkanRenderManager::Submit:1258) Critical: [false] Lost the Vulkan device in vkQueueSubmit! If this happens again, switch Graphics Backend away from Vulkan`

And the crash log:
```
retroarch_drmingw.exe caused a Breakpoint at location 00007FFDFB2F666D in module ppsspp_libretro.dll.

AddrPC           Params
00007FFDFB2F666D 00000222ED598E18 00000222E4B9DCB0 0000022200000400  ppsspp_libretro.dll!retro_load_game_special
00007FFDFB2F5E80 00000000000003E0 0000000000000301 0000000000000002  ppsspp_libretro.dll!retro_load_game_special
00007FFDFB2F6820 00000222DC4E9300 0000000000000000 0000000000000000  ppsspp_libretro.dll!retro_load_game_special
00007FFDFB2F0E3F 00000222E3CE0150 0000000000000000 0000000000000000  ppsspp_libretro.dll!retro_load_game_special
00007FFDFBA5D4F4 0000000000000000 0000000000000000 0000000000000000  ppsspp_libretro.dll!retro_set_video_refresh
00007FFE3DDD7034 0000000000000000 0000000000000000 0000000000000000  KERNEL32.DLL!BaseThreadInitThunk
00007FFE3E4C2651 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlUserThreadStart
```

### What *should* happen?

We should be able to fast-forward without crashing, Vulkan or not.

#### What hardware / device and operating system?

Windows 10 / i5-4670K / GTX 970

#### What PPSSPP version (standalone/official), and did it work before?

Libretro core / e5a8f20

#### Which game or games?

Any, AFAICT.

#### Checklist
 - [x] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [x] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [x] Try resetting settings or older versions and include if the issue is related.
 - [x] Include logs or screenshots of issue.

**Comment by i30817** [comment]
You should open this in retroarch itself probably.

**Comment by bslenul** [comment]
Oops, duplicate of #14675 , my bad I missed it!
