### ISSUE TITLE
Auto-load of save data in Puyo Puyo 20th Anniversary doesn't work

### ISSUE THREAD

**Issue by ArMM1998** [hrydgard/ppsspp#14687]
### Game or games this happens in

NPJH-50492 - ぷよぷよ！！

### What area of the game / PPSSPP

The game doesn't auto-load the save data at the start of the game, resulting in the game always prompting you (in japanese) to create a new empty save file:

![image](https://user-images.githubusercontent.com/33059861/128288155-bca927f4-b4c7-477f-9059-59a5763d83b8.png)

Which translates to:
![image](https://user-images.githubusercontent.com/33059861/128288192-4e5eb547-4259-4206-bcf9-8b6ab4d79ea5.png)

It doesn't matter how many times you create or import a save file, it will never read it unless done manually in the options menu. (purple button on title screen > 4th button)

### What should happen

It should load the save data automatically at the beginning, after the first message popup like it does on real hardware.

### Platform

Windows

### Mobile phone model or graphics card

AMD Radeon R7 Graphics

### PPSSPP version affected

1.11.3 and below

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by Gamemulatorer** [comment]
https://buildbot.orphis.net/ppsspp/

**Comment by unknownbrackets** [comment]
Logs would help.  It would show information in the log if it tried to save but failed for some reason.

Once you actually have a save, this doesn't show and everything works fine, right?

-[Unknown]

**Comment by ArMM1998** [comment]
> https://buildbot.orphis.net/ppsspp/

I did check in the latest build and it still doesn't work.



> Logs would help. It would show information in the log if it tried to save but failed for some reason.

The log doesn't seem to be showing a whole lot. Unless i'm looking at the wrong log? (I used the Ctrl + L shortcut)
![image](https://user-images.githubusercontent.com/33059861/128401588-0ada68a2-eb08-4c41-8d6e-d75c6f295940.png)
(This is after prompting the message saying that it couldn't find a save file)

> Once you actually have a save, this doesn't show and everything works fine, right?

Once it has a save, the game will auto-save normally as you play, so no issues there. But it will still never load that save upon booting the game.
To load it you have to do so manually in the game's options.

**Comment by ArMM1998** [comment]
After investigating a little i got a log that is probably more useful than what i posted.

> 24:11:128 user_main    D[SCEUTIL]: HLE\sceUtility.cpp:245 sceUtilitySavedataGetStatus(): wrong dialog type
> 24:11:128 user_main    D[SCEUTIL]: HLE\sceUtility.cpp:413 00000000=sceUtilityMsgDialogGetStatus()
> 24:11:144 user_main    D[SCEUTIL]: HLE\sceUtility.cpp:245 sceUtilitySavedataGetStatus(): wrong dialog type
> 24:11:161 user_main    D[SCEUTIL]: HLE\sceUtility.cpp:245 sceUtilitySavedataGetStatus(): wrong dialog type
> 24:11:182 user_main    D[SCEUTIL]: Dialog\SavedataParam.cpp:1523 Save data exists:  = ms0:/PSP/SAVEDATA/NPJH50492
> 24:11:182 user_main    I[SCEUTIL]: Dialog\PSPSaveDialog.cpp:93 sceUtilitySavedataInitStart(089f1bc0) - AUTOLOAD (0)
> 24:11:182 user_main    I[SCEUTIL]: Dialog\PSPSaveDialog.cpp:94 sceUtilitySavedataInitStart(089f1bc0) : Game key (hex): 779177ED8858A07FDC6F1F1A1D20034D
> 24:11:182 user_main    D[SCEUTIL]: Dialog\PSPSaveDialog.cpp:150 Loading. Title: NPJH50492 Save:  File: SAVEDATA.DAT
> 24:11:182 user_main    D[SCEUTIL]: HLE\sceUtility.cpp:222 00000000=sceUtilitySavedataInitStart(089f1bc0)
> 24:11:182 user_main    D[SCEUTIL]: HLE\sceUtility.cpp:253 00000001=sceUtilitySavedataGetStatus()
> 24:11:377 user_main    D[SCEUTIL]: HLE\sceUtility.cpp:253 00000002=sceUtilitySavedataGetStatus()
> 24:11:377 user_main    D[SCEUTIL]: HLE\sceUtility.cpp:268 00000000=sceUtilitySavedataUpdate(1)
> 24:11:380 CRI ADX Audi I[SCEUTIL]: Dialog\SavedataParam.cpp:652 Loading file with size 4 in ms0:/PSP/SAVEDATA/NPJH50492/SAVEDATA.DAT
> 24:11:394 user_main    D[SCEUTIL]: HLE\sceUtility.cpp:268 00000000=sceUtilitySavedataUpdate(1)
> 24:11:411 user_main    D[SCEUTIL]: HLE\sceUtility.cpp:253 00000003=sceUtilitySavedataGetStatus()
> 24:11:412 user_main    D[SCEUTIL]: HLE\sceUtility.cpp:237 00000000=sceUtilitySavedataShutdownStart()
> 24:11:412 user_main    D[SCEUTIL]: HLE\sceUtility.cpp:253 00000004=sceUtilitySavedataGetStatus()
> 24:11:428 user_main    D[SCEUTIL]: HLE\sceUtility.cpp:253 00000000=sceUtilitySavedataGetStatus()
> 24:11:445 user_main    I[SCEUTIL]: HLE\sceUtility.cpp:369 00000000=sceUtilityMsgDialogInitStart(0902d648)
> 24:11:445 user_main    D[SCEUTIL]: HLE\sceUtility.cpp:245 sceUtilitySavedataGetStatus(): wrong dialog type
> 24:11:445 user_main    D[SCEUTIL]: HLE\sceUtility.cpp:413 00000001=sceUtilityMsgDialogGetStatus()
> 24:11:464 user_main    D[SCEUTIL]: HLE\sceUtility.cpp:245 sceUtilitySavedataGetStatus(): wrong dialog type

**Comment by hrydgard** [comment]
Hm. Wonder if maybe sceUtilitySavedataGetStatus() is special with regards to the other dialog types, and shouldn't return "wrong dialog type" if savedata is in a mode where there's no UI.  Not sure we have a test for that.

**Comment by unknownbrackets** [comment]
`sceUtilitySavedataGetStatus()` returns wrong dialog type if you try to call it before initializing a savedata dialog, or after initializing another dialog.  Always, even if there's no UI.

In the log, we do later see it returning statuses so I think everything is working correctly there.  Some games simply call `sceUtilitySavedataGetStatus()` or `sceUtilityMsgDialogGetStatus()` as part of their normal loop whenever any dialog is open (we can see that a message dialog is open at that time.)

> Loading file with size 4 in ms0:/PSP/SAVEDATA/NPJH50492/SAVEDATA.DAT

This seems like an awfully small file.  I wonder if we're somehow loading the wrong filename or save name...

-[Unknown]

**Comment by hrydgard** [comment]
Hm, yeah, that file size is indeed more suspicious...

**Comment by unknownbrackets** [comment]
Sounds like JPCSP has the same problem?
http://www.emunewz.net/forum/showthread.php?tid=17827&page=2

I couldn't find savedata online.  Do you have a PSP with savedata or know someone who does for this game (ideally straight away after creating savedata)?  If yes, attaching it here and also the PPSSPP generated savedata would help.

A few interesting questions that may answer:
 * Is the file actually 4 bytes, or is it only loading 4 bytes of it for some reason?
 * Are the filesizes different?
 * Do the first 4 bytes of the raw savedata match between the two?
 * Is there some metadata in PARAM.SFO that's significantly different?
 * Does this work in JPCSP now, or still not work there?

It'd also be useful to get a [JpcspTrace log](https://github.com/unknownbrackets/JpcspTrace) of the savedata funcs on a real to confirm if it loads 4 bytes, although that's a bit more involved.

-[Unknown]

**Comment by ArMM1998** [comment]
I tried setting up JpcspTrace but i'm not sure what to do with the config file, so far it just freezes the system.

Something to note is that SAVEDATA.DAT always seems different every time i create a new one, even on real hardware. I'm not sure if it's compressed and it just results in it looking seemingly random in a hex editor?
I attached two saves for real hardware and two for emulator
https://drive.google.com/file/d/1k34jdG10Iyjvskoyk117jlqo-UywrUtm/view?usp=sharing

**Comment by sum2012** [comment]
I upload both ppsspp (v1.13.1-722-g49d5b6447) and real psp save in here (firmware 6.60 pro c2)
[ppsspp-NPJH50492.zip](https://github.com/hrydgard/ppsspp/files/9484413/ppsspp-NPJH50492.zip)
[Real-psp-NPJH50492.zip](https://github.com/hrydgard/ppsspp/files/9484416/Real-psp-NPJH50492.zip)

ppsspp v1.13.1-722-g49d5b6447 create log:  https://gist.github.com/sum2012/58b70801837a0a7756a131bbc1e55d00
Real psp log for create: https://gist.github.com/sum2012/ecf5405abebbde35ea12980698f93af0

**Comment by sum2012** [comment]
Real psp can load ppsspp's save so that the problem is loading the save
Loading log for both using ppsspp 's save
ppsspp load fail log:  https://gist.github.com/sum2012/1e432f39166898030bb9f338b6301482
Real psp load okay log: https://gist.github.com/sum2012/0af549d880eb92646246fee08e4fe1ab

**Comment by sum2012** [comment]
Same situation as jpcsp emulator (ddf9061)

**Comment by unknownbrackets** [comment]
The file size in the attached zip looks correct (same size), so it's not actually 4 bytes.

Hmm:
```
42:17:505 CRI ADX Audi E[FILESYS]: FileSystems\DirectoryFileSystem.cpp:57 DirectoryFileSystem::OpenFile('/PSP/SAVEDATA/NPJH50492/PARAM.SFO'): FAILED, 2 - access = 1 '系統找不到指定的檔案。
'
42:17:506 CRI ADX Audi I[SCEUTIL]: Dialog\SavedataParam.cpp:531 Saving file with size 4112 in ms0:/PSP/SAVEDATA/NPJH50492/SAVEDATA.DAT
42:17:521 user_main    D[SCEUTIL]: Dialog\SavedataParam.cpp:1544 Save data exists:  = ms0:/PSP/SAVEDATA/NPJH50492
```

That's a ERROR_FILE_NOT_FOUND for READ... wonder why.  Anyway, there it saves with the correct size and all is well.  This is create.

On load fail we get:

```
10:49:639 CRI ADX Audi I[SCEUTIL]: Dialog\SavedataParam.cpp:642 Loading file with size 4 in ms0:/PSP/SAVEDATA/NPJH50492/SAVEDATA.DAT
```

Apparently this is param->dataBufSize.  I wonder if it's changing.  Could you try something like this?

```
diff --git a/Core/Dialog/PSPSaveDialog.cpp b/Core/Dialog/PSPSaveDialog.cpp
index 9c1edd649..45c48dfc9 100755
--- a/Core/Dialog/PSPSaveDialog.cpp
+++ b/Core/Dialog/PSPSaveDialog.cpp
@@ -1086,6 +1086,14 @@ void PSPSaveDialog::ExecuteNotVisibleIOAction() {
        switch ((SceUtilitySavedataType)(u32)param.GetPspParam()->mode) {
        case SCE_UTILITY_SAVEDATA_TYPE_LOAD: // Only load and exit
        case SCE_UTILITY_SAVEDATA_TYPE_AUTOLOAD:
+               if (requestAddr != 0) {
+                       auto ptr = PSPPointer<SceUtilitySavedataParam>::Create(requestAddr);
+                       if (param.GetPspParam()->dataBufSize == ptr->dataBufSize) {
+                               NOTICE_LOG(SCEUTILITY, "Data buf size = %d, matching... dataSize=%d", ptr->dataBufSize, ptr->dataSize);
+                       } else {
+                               NOTICE_LOG(SCEUTILITY, "Data buf size CHANGED - %d => %d", param.GetPspParam()->dataBufSize, ptr->dataBufSize);
+                       }
+               }
                result = param.Load(param.GetPspParam(), GetSelectedSaveDirName(), currentSelectedSave);
                break;
        case SCE_UTILITY_SAVEDATA_TYPE_SAVE: // Only save and exit
```

-[Unknown]

**Comment by sum2012** [comment]
param->dataBufSize seem did not changed
![1](https://user-images.githubusercontent.com/2177532/188334937-8fe6098b-1d80-49b4-8dd9-327c5accc400.png)

**Comment by unknownbrackets** [comment]
0x00000000, 0x09035180, 0x00000004, 0x00000000  >.....Q..........<

Well, 4 seems correct here.  Later ones have enough space:

0x00000000, 0x09035180, 0x00001000, 0x00000000  >.....Q..........<

Maybe there's supposed to be some error result when the dataBufSize isn't large enough, but I thought not...

-[Unknown]

**Comment by sum2012** [comment]
@unknownbrackets  I report to jpcsp forum https://www.emunewz.net/forum/showthread.php?tid=17827&pid=366683#pid366683
 gid15 fix in https://github.com/jpcsp/jpcsp/commit/cb3768652bcc4744db0bfab37f95ccb93bc03bd1

**Comment by sum2012** [comment]
This hack code work

int SavedataParam::Load(SceUtilitySavedataParam *param, const std::string &saveDirName, int saveId, bool secureMode) {
	if (!param) {
		return SCE_UTILITY_SAVEDATA_ERROR_LOAD_NO_DATA;
	} 
	if (param->dataBufSize == 4)
		return SCE_UTILITY_SAVEDATA_ERROR_LOAD_DATA_BROKEN;

**Comment by hrydgard** [comment]
Thanks, yeah, I think we can do it a bit more nicely. I'll pick this up in a while if nobody beats me to it.

**Comment by unknownbrackets** [comment]
Hm, I thought I'd tested some time ago and smaller buffers didn't fail?  Maybe there's more rules or sdk version dependency to it.  Will test in a bit.

-[Unknown]

**Comment by unknownbrackets** [comment]
Okay, I don't see any tests for it.  Savedata is always a pain because it's slow and I can lock up my PSP testing it, but I checked this across SDK versions and it seems consistent.  Also fixed how it loads metadata and other fields on errors like this, which could matter.

-[Unknown]
