### ISSUE TITLE
MGS PW weird model error

### ISSUE THREAD

**Issue by LaoHeShaJu** [hrydgard/ppsspp#14693]
### Game or games this happens in

NPJH50045 Metal gear solid peace walker

### What area of the game / PPSSPP

Don’t know how to describe it just take a look of the screenshots. It effects every character’s model

### What should happen

The model should be displayed correctly 

### Logs

![Uploading F85036E7-8E4E-4D96-96BB-1149B4C248D2.png…]()
![Uploading E84C83C0-8412-48E8-9406-6B74413BC419.png…]()
![Uploading CA7790BF-D9A0-4CCB-AFAD-0885862714E7.png…]()
![Uploading AE54F455-811C-4F98-835C-2C37C456CDD6.png…]()

### Platform

iOS

### Mobile phone model or graphics card

iPhone 6s Plus

### PPSSPP version affected

v1.11.3-1003-gb89c70a6e

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by Gamemulatorer** [comment]
You did not upload the screenshot images properly.

**Comment by LaoHeShaJu** [comment]
![Uploading 0531C096-2A3C-421F-B5A7-12E8627308C8.png…]()

**Comment by LaoHeShaJu** [comment]
Wait a sec let me google how to do that

**Comment by LaoHeShaJu** [comment]
![](https://s3.bmp.ovh/imgs/2021/08/57f589ebd6f47ce0.png)

**Comment by Gamemulatorer** [comment]
Maybe this is a duplicate issue of https://github.com/hrydgard/ppsspp/issues/14514
What is your ios version? 14.1?

**Comment by LaoHeShaJu** [comment]
the latest iOS14.7.1 same issue also occurs in 14.6

**Comment by LaoHeShaJu** [comment]
I have also tested with PPSSPPv1.9.3 but the problem was still there…strange

**Comment by Saramagrean** [comment]
seem like https://github.com/hrydgard/ppsspp/issues/10650.

**Comment by LaoHeShaJu** [comment]
Yeah same issue. Thx bro it’s now fixed
