### ISSUE TITLE
[Feature Request] Expand Recent Games List

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#14707]
### What should happen

PPSSPP recent games list capacity is max to 30 only, maybe is good to expand it to 50? or more?
![Screenshot_2021-08-09-14-18-24-048_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/128666822-26b9673f-590e-4460-8679-3f2002b7f064.jpg)

### Who would this benefit

Everyone? Because some of my games are located to external sdcard and some is in internal storage. I want to put them all on recent games list so that I don't need to browse the storage directory from internal or external storage to search games because my android version is 11 😅

Hope you understand me I'm not really good at english hehe ✌️

### Platform (if relevant)

Android

### Games this would be useful in

None

### Other emulators or software with a similar feature

None

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by unknownbrackets** [comment]
You can increase it in the ini file to whatever you want.

That said, it's a fair point that with scoped storage, maybe a higher max makes sense.  I cranked it up pretty high, myself.

-[Unknown]

**Comment by Gamemulatorer** [comment]
> You can increase it in the ini file to whatever you want.

I didn't know that thanks!!!

**Comment by Gamemulatorer** [comment]
This was fixed by https://github.com/hrydgard/ppsspp/pull/14718
