### ISSUE TITLE
GAME list was not memory last position. [Win/Android]

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#14710]
### What should happen

#13699 &Relate #13710 

@iota97 maked last playing game's memory on game list.

Now, This memory was changed to not work???

If it right by some reason then I will understand it.
*When it was excluded consciously.

### Who would this benefit

every one.

### Platform (if relevant)

Android

### Games this would be useful in

every game (gamer).

### Other emulators or software with a similar feature

Majority's emulator is so, I think.

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by unknownbrackets** [comment]
Most likely, because the game list loads asynchronously now, setting the scroll position immediately after init doesn't work.

-[Unknown]

**Comment by nassau-tk** [comment]
Okey!

It means "Now,PPSSPP is can't do it" isn't it?
I undestood it!!
Thank you @unknownbrackets 

I'll Close this post!!

**Comment by unknownbrackets** [comment]
Well, it is possible to fix - just noting what I assume broke this.

-[Unknown]

**Comment by nassau-tk** [comment]
Oops!
Thank you master.
