### ISSUE TITLE
Crash on exit on NV Shield

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#14719]
### Game or games this happens in

None

### What area of the game / PPSSPP

When exiting PPSSPP, a crash gets logged to the console.

(It's pretty clear that the Tegra VK and GL drivers share some code....)

### What should happen

No crash.

### Logs

```
08-11 23:41:14.884 16118 16118 F DEBUG   :     #00 pc 0000000000a2e1bc  /vendor/lib64/libglcore.so (__glCheckCacheHashed+44)
08-11 23:41:14.885 16118 16118 F DEBUG   :     #01 pc 0000000000a2ec24  /vendor/lib64/libglcore.so (__glCheckCache+164)
08-11 23:41:14.885 16118 16118 F DEBUG   :     #02 pc 0000000000f50bf4  /vendor/lib64/libglcore.so (TrackSetClear(__GLNVstateRec*, __GLcacheRec*, int, __GLdata*, __GLzbcTableType)+68)
08-11 23:41:14.885 16118 16118 F DEBUG   :     #03 pc 0000000000f52848  /vendor/lib64/libglcore.so (__glGF100TrackSetClearDepth(__GLGF100stateRec*, __GLdata, __GLFormatTypeRec)+312)
08-11 23:41:14.885 16118 16118 F DEBUG   :     #04 pc 0000000001039a40  /vendor/lib64/libglcore.so (__VkCommandBuffer::ClearSubpass()+608)
08-11 23:41:14.885 16118 16118 F DEBUG   :     #05 pc 0000000001038db4  /vendor/lib64/libglcore.so (__VkCommandBuffer::BeginSubpass()+2004)
08-11 23:41:14.885 16118 16118 F DEBUG   :     #06 pc 0000000001015e2c  /vendor/lib64/libglcore.so (__VkCommandBuffer::CmdBeginRenderPass(VkRenderPassBeginInfo const*, VkSubpassContents)+604)
08-11 23:41:14.885 16118 16118 F DEBUG   :     #07 pc 0000000000699374  /data/app/org.ppsspp.ppsspp-emhj6FwZJR63SHjujXpCgQ==/lib/arm64/libppsspp_jni.so (VulkanQueueRunner::PerformBindFramebufferAsRenderTarget(VKRStep const&, VkCommandBuffer_T*)+628)
```

### Platform

Android

### Mobile phone model or graphics card

NVIDIA Shield 2017

### PPSSPP version affected

1.11.3-1112

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Seem to be getting something similar in the following conditions:

* Windows, debug build
* OpenGL
* Chat window open

Appears we still have a shutdown race condition.

**Comment by domb84** [comment]
ppsspp also crashes retroarch on RPi4 when closing content or exiting ppsspp. Same as logged here (seems to be across all platforms)

[https://forums.libretro.com/t/ppsspp-core-freezes-when-closing-content/24964](url)

Only fix is to disable audio synchronisation in retroarch.

**Comment by unknownbrackets** [comment]
The threading issues with how libretro/retroarch manages contexts, audio, and save state data aren't related to this.  Multiple things can theoretically cause crashes in shutdown and still be unrelated.

-[Unknown]

**Comment by unknownbrackets** [comment]
Does this still happen?  I seem to recall that we fixed some shutdown issue.

-[Unknown]

**Comment by Gamemulatorer** [comment]
This still an issue?

**Comment by hrydgard** [comment]
Let's close it. I'm gonna do another round of Shield TV testing and optimization at some point maybe, if it's still an issue then I'll re-open.
