### ISSUE TITLE
YuGiOh Arc V Tag Force Special - crash during save

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#14727]
Reported by @Gamemulatorer in #13847 .

The important part of the log is here:
```
08-14 18:09:33.338 F/g.ppsspp.ppssp(10208): runtime.cc:655]   native: #08 pc 00000000006b7034  /data/app/~~XnqZgVAIeeS_ihHj-rJcZw==/org.ppsspp.ppsspp-lGEdC6MC-6LTF4JrtfLgZg==/lib/arm64/libppsspp_jni.so (HandleAssert(char const*, char const*, int, char const*, char const*, ...)+248)
08-14 18:09:33.338 F/g.ppsspp.ppssp(10208): runtime.cc:655]   native: #09 pc 000000000051a3bc  /data/app/~~XnqZgVAIeeS_ihHj-rJcZw==/org.ppsspp.ppsspp-lGEdC6MC-6LTF4JrtfLgZg==/lib/arm64/libppsspp_jni.so (UtilityDialogInitialize(UtilityDialogType, int, int)+408)
08-14 18:09:33.338 F/g.ppsspp.ppssp(10208): runtime.cc:655]   native: #10 pc 00000000004176c8  /data/app/~~XnqZgVAIeeS_ihHj-rJcZw==/org.ppsspp.ppsspp-lGEdC6MC-6LTF4JrtfLgZg==/lib/arm64/libppsspp_jni.so (PSPSaveDialog::Init(int)+936)
```

There's an assert there: `_assert_(accessThread == nullptr);` on line 300, but I don't see how that could possibly be hit, given what CleanupDialogThreads does? Weird... Unless there's an assert in some function it calls that got inlined, like HLEHelperThread::HLEHelperThread or HLEHelperThread::Start ...

Doesn't really feel related to scoped storage? But could be, of course.

Unknown comments:

> Hm, could it be related to the "YugiohSaveFix" hack?

> Seems like maybe sceUtilitySavedataInitStart called twice, the second time while accessThread is still running?

**Comment by unknownbrackets** [comment]
Did #14728 fix this @Gamemulatorer?

-[Unknown]

**Comment by Gamemulatorer** [comment]
Still crash :/ loading from savestate and then try to save the game data crashing out the emulator.
[logcat.txt](https://github.com/hrydgard/ppsspp/files/6987959/logcat.txt)

**Comment by hrydgard** [comment]
Looks like it's still hitting that assert? Weird.

```
libppsspp_jni.so (HandleAssert(char const*, char const*, int, char const*, char const*, ...)+248)
libppsspp_jni.so (UtilityDialogInitialize(UtilityDialogType, int, int)+392)
libppsspp_jni.so (PSPSaveDialog::Init(int)+936)
```

**Comment by Gamemulatorer** [comment]
I forget to say that may savestate has a cheat enable 😅 so even if i disable it before loading the savestate the cheat is still in effect? maybe that the cause of issue 🤔

**Comment by Gamemulatorer** [comment]
I can't not reproduce this anymore with cheat saving the game work fine again :)
[logcat_08-24-2021_09-59-33.txt](https://github.com/hrydgard/ppsspp/files/7035898/logcat_08-24-2021_09-59-33.txt)

**Comment by unknownbrackets** [comment]
Glad to hear it - not sure why the initial fix didn't work, though.

-[Unknown]
