### ISSUE TITLE
Prevent analogs from triggering other buttons (touch controls)

### ISSUE THREAD

**Issue by pandji007** [hrydgard/ppsspp#14721]
### What should happen

This is a very specific problem and very minor, but I often drag the analog button too far and it triggers the unthrottle button. Also happens when sliding the right analog up and down because there is very small space.

I could always rearrange the position but, I wonder wether it's possible to prevent the analogs from trigerring other buttons when dragged (just like how it doesn't trigger the dpads).

doesn't trigger dpads:
![Screenshot_20210812-123005](https://user-images.githubusercontent.com/88570864/129143168-bc4ff24b-26d7-4355-8229-f2d2fb9e731c.jpg)
but triggers other buttons:
![Screenshot_20210812-123019](https://user-images.githubusercontent.com/88570864/129143199-46d716bf-7298-4c67-b93e-eee003c0376b.jpg)
right analog:
![Screenshot_20210812-123524](https://user-images.githubusercontent.com/88570864/129143545-45d4dab5-b251-4dad-a0a8-2c0329acd6f6.jpg)

Thank you.

### Who would this benefit

Android

### Platform (if relevant)

Android

### Games this would be useful in

Any

### Other emulators or software with a similar feature

None

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by pandji007** [comment]
although it might conflict with this #14429 because it's the exact opposite.

**Comment by radityaargap** [comment]
i think it's a valid point. especially now that ppsspp has touch gestures. i keep accidentally triggering the action buttons. there could be a toggle that makes the buttons behave like the dpads. because the dpad is the only one that doesn't get triggered while swiping the screen.
