### ISSUE TITLE
building the core on rpi 4

### ISSUE THREAD

**Issue by i8890321** [hrydgard/ppsspp#14734]
### Platform

Rpi4

### Compiler and build tool versions

clang version 7.0.1-8+rpi3+deb10u2 

### Operating system version

rpi4

### Build commands used

make platform=rpi4

### What happens

I receive the following when using the make command
../Common/Data/Format/ZIMLoad.cpp
../Common/Data/Format/ZIMLoad.cpp:4:10: fatal error: zstd.h: No such file or directory
 #include <zstd.h>
          ^~~~~~~~
compilation terminated.
make: *** [Makefile:618: ../Common/Data/Format/ZIMLoad.o] Error 1

### PPSSPP version affected

v1.11.3-1140-ga1ce13a2f

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] Make sure to run `git submodule update --init --recursive` before building.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try deleting the build directory and running the build again.
- [ ] Check GitHub Actions, which builds every merge and PR.
- [ ] Include logs and help us reproduce.

**Comment by unknownbrackets** [comment]
Hm, maybe this is an include path issue.

If you install libzstd-dev, does that workaround the issue?  If yes, that's probably the right fix, but would indicate the fix.

-[Unknown]
