### ISSUE TITLE
Please help with specific code for Vulkan on TTY (no X11/Wayland)

### ISSUE THREAD

**Issue by vanfanel** [hrydgard/ppsspp#14738]
### Platform

GNU/Linux

### Compiler and build tool versions

gcc 9.3.0 / 8.3.0, cmake version 3.16.3

### Operating system version

Ubuntu Linux 20.04 / Debian 10

### Build commands used

git clone https://github.com/vanfanel/ppsspp.git
git submodule update --init --recursive

cmake -DUSING_KMSDRM=OFF -DUSING_X11_VULKAN=OFF -DUSING_GLES2=ON -DUSE_DISCORD=OFF -DCMAKE_C_FLAGS="-DEGL_NO_X11" -DCMAKE_CXX_FLAGS="-DEGL_NO_X11"

### What happens

I have added the necessary code to support Vulkan on the TTY (no X11/Wayland needed!), but I am still unable to make it work after many efforts, possibly due to my partial knowledge on the subject.

The problem is that `vkQueuePresentKHR()` throws an `VK_ERROR_SURFACE_LOST_KHR` error.

Theorically, everything is correct. This is a checklist of what I have already in place, so I would need to be pointed at missing parts, if any:

[X] The `VK_KHR_display` extension, which is needed for Vulkan on the TTY, is activated here so the Vulkan instance is created with the necessary extension active:
https://github.com/vanfanel/ppsspp/blob/7607f303d41d5ee38fe4eb0d7c6afb67ff9aace2/Common/GPU/Vulkan/VulkanContext.cpp#L119

[X] The Vulkan surface creation code, specific to `VK_KHR_display`, is here:
https://github.com/vanfanel/ppsspp/blob/7607f303d41d5ee38fe4eb0d7c6afb67ff9aace2/Common/GPU/Vulkan/VulkanContext.cpp#L779
For now, it's using the current video mode, which is retrieved here from the array of available video modes:
https://github.com/vanfanel/ppsspp/blob/7607f303d41d5ee38fe4eb0d7c6afb67ff9aace2/Common/GPU/Vulkan/VulkanContext.cpp#L854
This surface creation code seems to work well.

[X] Swapchain creation on the aforementioned surface seems to work well (no errors that I can see) so I haven't modified anything on `InitSwapchain()`:
https://github.com/vanfanel/ppsspp/blob/7607f303d41d5ee38fe4eb0d7c6afb67ff9aace2/Common/GPU/Vulkan/VulkanContext.cpp#L1020

[X] I inhibited `SDL_Window` creation because Vulkan context initialization is not compatible with SDL2 KMSDRM backend SDL_Window creation (Vulkan and SDL2 would be trying to access the same resources):

https://github.com/vanfanel/ppsspp/blob/7607f303d41d5ee38fe4eb0d7c6afb67ff9aace2/SDL/SDLVulkanGraphicsContext.cpp#L36

As a result of all this, Vulkan should be working on the TTY, but it's not and I don't know why.

So I am requesting help, in case someone can shed some light on this and we can complete implementation of this small but important feature: not depending on any windowing system will be great!

Thanks!

### PPSSPP version affected

Current GIT

### Last working version

None

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] Make sure to run `git submodule update --init --recursive` before building.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try deleting the build directory and running the build again.
- [X] Check GitHub Actions, which builds every merge and PR.
- [X] Include logs and help us reproduce.

**Comment by hrydgard** [comment]
Closed? Figured it out? When closing issues, usually we post a quick explanation why.

**Comment by vanfanel** [comment]
@hrydgard I closed this in favor of a WIP PR that I have just done here:

https://github.com/hrydgard/ppsspp/pull/14758

I think this is better code and a better place to figure out with the needed help.

**Comment by hrydgard** [comment]
Yeah sure, that's fine.
