### ISSUE TITLE
Street Riders - Graphics flickering and other issues

### ISSUE THREAD

**Issue by MojoJojoDojo** [hrydgard/ppsspp#14746]
### Game or games this happens in

ULES00276 - Street Riders

### What area of the game / PPSSPP

In-game when you are racing you could see that graphics sometimes flicker and that lights are misplaced or bleed over.
Reported this as a Vulkan issue but it appears on every backend (except OpenGL because I don't use it).
Screenshots:
![image](https://user-images.githubusercontent.com/33392696/130197297-767fac36-7c27-410f-941f-6ef52fe7522d.png)
![image](https://user-images.githubusercontent.com/33392696/130197388-5e94f268-098f-4098-9d86-bbb3f0ab93d9.png)

### What should happen

The graphics should be well and without issue.

### Platform

Windows

### Mobile phone model or graphics card

Intel UHD 620

### PPSSPP version affected

1.11.3-1134

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
Can you include a GE frame dump?  My guess is this involves culling.

-[Unknown]

**Comment by hrydgard** [comment]
I would bet this is two separate issues (far lights bleeding through, vs culled polygons at the edge of the screen).

**Comment by unknownbrackets** [comment]
> 
> 
> Well I did 2 recordings because I was not sure if I reproduced it correctly on the first one.
> [street riders.zip](https://github.com/hrydgard/ppsspp/files/7056219/street.riders.zip)

Unfortunately, these frame dumps don't contain any drawing commands.  Please make sure frameskip is disabled while making the GE frame dump.

I'm hopeful this may be related to the changes being discussed in #12058, and a frame dump would help verify this and ultimately the fix.

-[Unknown]

**Comment by MojoJojoDojo** [comment]
OK here is take 2.
[street riders.zip](https://github.com/hrydgard/ppsspp/files/7133646/street.riders.zip)

**Comment by MojoJojoDojo** [comment]
Tried the latest dev builds and it doesnt seems like anything changed...
If it helps , the game seems like a almost direct PS2 port of a game called 187 Ride or Die.

**Comment by MojoJojoDojo** [comment]
Slightly unrelated but I think that DisableRangeCulling ON needs to be applied to TOCA Race Driver 3 as well because it also got a similar issue here.

**Comment by hrydgard** [comment]
I thought we already did that, what game IDs are missing from compat.ini ?

**Comment by unknownbrackets** [comment]
DisableRangeCulling no longer does anything on most devices outside Mali and Apple, iirc.  I thought Intel supported the culling features.  Outside those devices, I would expect the missing panels no longer to be an issue.

Is this still an issue with Vulkan and GL?  Do you have shaderClipDistance and shaderCullDistance (Vulkan) or GL_ARB_cull_distance (GL)?

-[Unknown]

**Comment by MojoJojoDojo** [comment]
Seems like some of the graphics are fine now last I tried.
The lighting issues still appear though.

**Comment by MojoJojoDojo** [comment]
Others have reported me that if you got an NVIDIA GPU the game seems to be slower by a lot of frames.
Getting 10-20 frames.
I am on an AMD GPU and the game runs fine (althought on LInux) so I wonder if its a driver issue...

**Comment by Gamemulatorer** [comment]
The light misplace is finally fixed now!
***PPSSPP v1.13.1-63***
![Screenshot_2022-07-31-20-16-59-751_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/182026074-4ed8ebb4-5eff-4f27-b623-329448627b13.jpg)

***PPSSPP v1.13.1 Stable***
![Screenshot_2022-07-31-20-16-43-213_org ppsspp ppssppgold](https://user-images.githubusercontent.com/37603562/182026146-c8b05f1b-2c89-4502-960d-26d361c910a4.jpg)

Fixed by https://github.com/hrydgard/ppsspp/commit/8260b4667dd11941c4bbfbf1f121397571bed664

**Comment by hrydgard** [comment]
Great, thanks for testing!

I'm gonna close this issue because I believe the other bug was already fixed.
