### ISSUE TITLE
[libretro] error building for arm64 platform

### ISSUE THREAD

**Issue by vanfanel** [hrydgard/ppsspp#14742]
### Platform

Other

### Compiler and build tool versions

gcc 8.3.0

### Operating system version

Debian aarch64

### Build commands used

```
cd libretro
make platform=arm64 -j4
```

### What happens

During build, I receive the following error:
```
make: *** No rule to make target '../Common/math/fast/fast_matrix_neon.o', needed by 'ppsspp_libretro.so'.  Stop.
make: *** Waiting for unfinished jobs....
```

### PPSSPP version affected

Latest GIT

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] Make sure to run `git submodule update --init --recursive` before building.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try deleting the build directory and running the build again.
- [X] Check GitHub Actions, which builds every merge and PR.
- [X] Include logs and help us reproduce.

**Comment by hrydgard** [comment]
Strange, some env variable not set? Other ARM64 builds seem to integrate and build this file correctly now..

**Comment by vanfanel** [comment]
@hrydgard What enviroment variable could be at play?
All LibRetro cores build fine here except this one.

**Comment by hrydgard** [comment]
I don't know, maybe look at the cmake. All i know is that this is normally not a problem so I'm a little baffled.

**Comment by vanfanel** [comment]
@hrydgard I looked at CMakeLists.txt before posting the issue (I don't want to waste anybody's time).
Does it build for you using the arm64 platform?

**Comment by hrydgard** [comment]
Oh I see, yeah maybe it's just missing from Makefile.common. Try to add it there.

It's the only pure assembly-source file that we use, and it's part of a library, libpng. We could probably also flip a switch and get it to use the non-assembly version.

**Comment by vanfanel** [comment]
I would like to add it to Makefile.common, but it's already there:
`
https://github.com/hrydgard/ppsspp/blob/005f145fbc6a6b8a6a9e8198c1df45a8430a6e7e/libretro/Makefile.common#L627`

**Comment by vanfanel** [comment]
Ok, there are errors on Makefile.common

https://github.com/hrydgard/ppsspp/blob/0c34c939ad0c8d543c2f791ad348410df32a9a4c/libretro/Makefile.common#L656

...should have `Math` instead of `math`.

That let's the build continue.

But then there's also this:
```
/libpng17/arm/filter_neon.o ../ext/libpng17/arm/filter_neon.S
as: unrecognized option '-O2'
```

**Comment by vanfanel** [comment]
So, should the assembler receive the CFLAGS?
Shouldn't it have a separate ASMFLAGS instead?

**Comment by hrydgard** [comment]
Yeah, seems weird that the assembler would get CFLAGS...

**Comment by gouchi** [comment]
Libretro core build fine for arm64 using CMake.

Indeed the Makefile will need some update.

Libretro project is using [Makefile](https://github.com/hrydgard/ppsspp/blob/master/.gitlab-ci.yml) for Win 32|64 and MacOS 64.

**Comment by vanfanel** [comment]
What should ASFLAGS include, if anything?

@gouchi Having a Windows & MacOS Makefile for a libretro core doesn't make any sense, I think. So yes, this definitively needs some work.

**Comment by vanfanel** [comment]
Well, got it to build with this:
`
cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_WAYLAND_WSI=ON -DUSING_X11_VULKAN=OFF -DUSING_GLES2=ON -DUSE_DISCORD=OFF -DCMAKE_C_FLAGS="-DEGL_NO_X11 -march=armv8-a+crc+simd -mtune=cortex-a72" -DCMAKE_CXX_FLAGS="-DEGL_NO_X11 -march=armv8-a+crc+simd -mtune=cortex-a72"
`

So I got to finally see PPSSPP running on Vulkan on the Pi4, using the Libretro core (standalone doesn't work).
Not-so-surprisingly, PPSSPP on Vulkan as a Libretro core is slower than standalone PPSSPP on GLES2.

I tried to fix PPSSPP on Vulkan without X11 / Wayland / Libretro (using the vk_khr_display extension) but failed.

**Comment by gouchi** [comment]
Hi @vanfanel if you succeed to compile it, we may close this issue ?

Also I forgot we have this patch for arm64 [01-fix-atomics-arm64.patch](https://github.com/libretro/Lakka-LibreELEC/blob/139b8c19dec564e63b31d9ecf4e894e3a4232cc5/packages/lakka/libretro_cores/ppsspp/patches/01-fix-atomics-arm64.patch).

> I tried to fix PPSSPP on Vulkan without X11 / Wayland / Libretro (using the vk_khr_display extension) but failed.

It should work using `-DUSE_VULKAN_DISPLAY_KHR=ON -DUSING_X11_VULKAN=OFF`  [Source](https://github.com/libretro/Lakka-LibreELEC/blob/139b8c19dec564e63b31d9ecf4e894e3a4232cc5/packages/lakka/libretro_cores/ppsspp/package.mk#L35).

Thank you.

**Comment by vanfanel** [comment]
@gouchi yes, this can be closed. Thanks for reminding me!
