### ISSUE TITLE
Touch Control customization screen is super buggy

### ISSUE THREAD

**Issue by Leopard20** [hrydgard/ppsspp#14743]
The Touch Controls customization screen is a buggy mess and it's impossible to use:
1. You can move and resize **hidden buttons**: sometimes you may notice that a button you're dragging is not moving at all. It's because a hidden button overlapping with it is moving instead!

2. The edit area doesn't match the actual in-game area: How is one supposed to know if the control setup is right when the edit area doesn't even match the actual in-game controls?! 
Solution: remove the side bar and put it at the top instead. Almost no one uses that area. Make it super small, and preferably even hideable.

3. You can't put controls off the edit area: Believe it or not, some people like to put the controls at the edge of the screen. It's impossible to do rn. You should only make sure that the control doesn't go completely off-screen (at least one vertex must be inside the edit area in a way that it can be dragged)

Bugs 1 and 3 are easy to fix. But 2 may need some deep changes in UI.

**Comment by iota97** [comment]
1. Does it happen only with the action button being the hidden one? If so I found the problem, if other button give the same problem let me know tho' as there might be something else as well.

2. It should be stretched but still the same area I think, like the corner is the corner and the center is the center (I still use the top area for button I press once in a while like savestate and such). If is not like that could you tell me your phone screen rateo, might be a bug only on some screen.

3. I see, got it to half the size off screen (I think it should be enough without losing the button, not sure if u have some use case it need more tho').

**Comment by Leopard20** [comment]
1. Not sure. I'll test the new version to see if the problem is resolved.
2. I'll send a screenshot.
3. Thanks. Will test.

**Comment by Leopard20** [comment]
Ok so issues 1 and 3 seem to be fixed. Thanks.
This is what I mean for issue 2. Look at the position of buttons and relative distance between them:
![Screenshot_2021-08-20-10-31-13-222_org ppsspp ppsspp](https://user-images.githubusercontent.com/16115820/130187351-5b90404d-8325-4b12-a8a4-f5f13e696df7.jpg)
![Screenshot_2021-08-20-10-31-29-568_org ppsspp ppsspp](https://user-images.githubusercontent.com/16115820/130187358-e455fcbc-112a-4b6d-9f07-427a4455e249.jpg)

**Comment by unknownbrackets** [comment]
I think it's scaling just as described.  The reason it kinda looks like it isn't is that the size of the buttons is not being adjusted.  For example, that's why L and R don't look the same between the two.  Your brain isn't measuring the centers of the objects when judging distance.

I guess we could use a gesture to show/hide the sidebar.

-[Unknown]

**Comment by Leopard20** [comment]
> 
> 
> I think it's scaling just as described. The reason it kinda looks like it isn't is that the size of the buttons is not being adjusted. For example, that's why L and R don't look the same between the two. Your brain isn't measuring the centers of the objects when judging distance.
> 
> I guess we could use a gesture to show/hide the sidebar.
> 
> -[Unknown]

> I think it's scaling just as described

No they're both the same scale. The width of the edit area is smaller. You're using percentages for positioning the center of buttons. Thus they become lumped in the edit area. For example:
Edit Area:
```cpp
center_x = side_bar_width + button_x * edit_area_width;
```
Actual result (in-game):
```cpp
Edit Area:
```cpp
center_x = button_x * screen_width; //button_x * screen_width > button_x * edit_area_width
```

**Comment by hrydgard** [comment]
Yeah, that's right. It's a compromise to fit those controls on the side of the screen.

It's a valid point that we should probably scale them down accordingly in the edit mode, and also fix the aspect ratio. It's not a huge issue though unless you're a perfectionist with your control positioning.

**Comment by Leopard20** [comment]
> It's not a huge issue though unless you're a perfectionist with your control positioning.

Actually, the reason you see that my control setup is so big and weird is because I like to position the buttons very accurately based on my muscle memory. I always set my controls alpha to 5-10%, so I don't really see anything in the game! ;)

**Comment by Gamemulatorer** [comment]
This should 1.12.0 milestone.
