### ISSUE TITLE
Android controller bugs introduced in v1.11.3-1122-gb4361fe2a

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#14761]
### What happens?
It seems v1.11.3-1122-gb4361fe2a changed the default controller config it will result of controller bugs for Android devices.

Known Bugs:
Pressing Android's Back Button is maps Select Button.
My Android Controller's select does not press Select Button. Pressing Select goes to home button.

### What *should* happen?
v1.11.3-1114-g6e0da89c3 and older works properly in default settings

#### What hardware / device and operating system?
Android

#### What graphics card (GPU) or mobile phone model?
POCO M3

#### What PPSSPP version (standalone/official), and did it work before?
Last version work: v1.11.3-1114-g6e0da89c3
Issue Started: v1.11.3-1122-gb4361fe2a

#### Checklist

 - [x] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [x] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [x] Try resetting settings or older versions and include if the issue is related.
 - [ ] Include logs or screenshots of issue.

**Comment by XiaomiRedmi9** [comment]
> Should probably always display the iOS on-screen back button if the controller back button is mapped?

@hrydgard yes that's a good idea 💡

**Comment by hrydgard** [comment]
Apparently from Kitkat there's a way to check if keycodes are supported on a controller, https://developer.android.com/reference/android/view/InputDevice#hasKeys(int...) . As it's also possible to get the list of motion axis, I think, we could probably do something smart and use the Xbox controller layout only if it has enough buttons and axis, and otherwise use the standard layout.

But for now, I'm just gonna restore the default layout for generic controllers, and maybe try to detect Xbox controllers by name and default to an appropriate layout for them if you press Auto configure.

**Comment by IrfanH495** [comment]
me too, i don't use a gamepad.
https://user-images.githubusercontent.com/78854859/131216150-a383eff4-1163-4db2-be83-e00fe03b701a.mp4

**Comment by hrydgard** [comment]
Yeah, okay. I didn't expect that effect! Will fix.

**Comment by IrfanH495** [comment]
work now, i have to set it using gamepad.
![Screenshot_20210828-190415](https://user-images.githubusercontent.com/78854859/131217246-16740cfa-09eb-4248-b89a-a5eea7af4b72.png)

**Comment by hrydgard** [comment]
Yeah, well, a proper fix is coming soon.

**Comment by hrydgard** [comment]
Please test once there's a build with https://github.com/hrydgard/ppsspp/pull/14764 .

**Comment by Gamemulatorer** [comment]
Confirm fixed by https://github.com/hrydgard/ppsspp/commit/fdf8484e624c689918f180e84b0275b5b43c6f0a

**Comment by Panderner** [comment]
Wait what is pad1.TriggerL+ used for?

**Comment by hrydgard** [comment]
To pause. More convenient than pushing in the right stick, which was the old shortcut on xbox controllers.

**Comment by hrydgard** [comment]
Anyway, I'm closing this - if things aren't working, please re-open.

**Comment by Panderner** [comment]
Thanks but it seems pad1.TriggerL+ and pad1.L2 are different buttons. I'm unable to exit PPSSPP using a controller.

**Comment by hrydgard** [comment]
If you have a button mapped that doesn't exist, you'll have a problem, yes.

Please try to use the Auto configure feature in Control mappings. Do you still end up with a problem?

**Comment by hrydgard** [comment]
Oh yeah, I forgot that I was gonna show the touch screen back button...

**Comment by hrydgard** [comment]
Actually not any new criteria should show the on-screen pause button. On touch screen Android devices you'll always be able to use built-in back functionality of the screen anyway, so it's not really needed.

Tweaking the defaults a bit more. But to test if this fixed anything, please reset mappings to default so you'll actually see the new defaults. If you don't have back mapped to anything that exists on your gamepad, you're screwed...

**Comment by hrydgard** [comment]
With the latest change, and resetting to defaults / auto config, are things OK now?

**Comment by Panderner** [comment]
The L2 is now working for pausing for my controller. So I'm closing this.
