### ISSUE TITLE
(android) enable rendering duplicate frames causing lag on brave story new traveller.

### ISSUE THREAD

**Issue by ghost** [hrydgard/ppsspp#14762]
### Game or games this happens in

ULUS10279

### What area of the game

![Screenshot_2021-08-26-18-39-03-345_org ppsspp ppsspp](https://user-images.githubusercontent.com/78680959/130948753-239dcd4f-246c-4a06-aca3-d873760582c8.jpg)

### What happens

The option render duplicate frames can make brave story new traveller lag instead of fast/smooth.
![Screenshot_2021-08-26-18-35-06-594_org ppsspp ppsspp](https://user-images.githubusercontent.com/78680959/130948874-f7b349cf-3281-40f4-8d74-d5a9df13894b.jpg)

### What should happen

Should make the game run fast/smooth.

### GE frame capture

[brave_story.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/7056605/brave_story.ppdmp.zip)

### Platform

Android

### Mobile phone model or graphics card

Redmi 9 Android 11 Helio G80

### PPSSPP version affected

v1.11.3-1184 buildbot

### Last working version

none

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
Since this isn't a bug and the reporter closed their account, I'm going to close this.

-[Unknown]
