### ISSUE TITLE
No Text In Games, iPhone X IOS: 14.1

### ISSUE THREAD

**Issue by KayK567** [hrydgard/ppsspp#14760]
When playing Sims 2 Castaway there is no font present for the game. The graphics are perfect, but I’m unsure of how to play the game with words.

**Comment by Gamemulatorer** [comment]
Screenshot of the issue?

**Comment by KayK567** [comment]
> Screenshot of the issue?

Sure here's a few.. ![image](https://user-images.githubusercontent.com/36699746/130585263-e40c2c92-ccdb-43ff-9e35-19e5889511b9.png)
-
![image](https://user-images.githubusercontent.com/36699746/130585328-62a161dc-e59d-4640-977f-4d3d5c0f0166.png)
-
![image](https://user-images.githubusercontent.com/36699746/130585363-69f84041-5d37-41bb-bb4b-0d894866d1db.png)

**Comment by hrydgard** [comment]
What version of PPSSPP are you using?

**Comment by KayK567** [comment]
> What version of PPSSPP are you using?

I'm using v1.6.3-456-g6d0ed4a .

**Comment by hrydgard** [comment]
That's probably your problem then. There's a rendering bug in iOS 14, that we introduced a workaround for sometimes in the 1.11 series of builds. 1.6.3 is ancient.
