### ISSUE TITLE
Infinite loop and overflow in `memory.disasm` WebSocket API

### ISSUE THREAD

**Issue by kotcrab** [hrydgard/ppsspp#14773]
### Game or games this happens in

Any game

### What area of the game / PPSSPP

Sending a very specific request to the WebSocket API causes infinite loop in `memory.disasm` handler. API stops responding to further requests. Attempt to exit or restart game will lock up the emulator.

To reproduce start any game and send request:
```
{"address":4294927295,"end":4294967295,"displaySymbols":true,"event":"memory.disasm"}
```
The issues is here: this line will calculate `end` to be 0xFFFFFFFF
https://github.com/hrydgard/ppsspp/blob/2735b09ebc5b3fe41161143cdb60bcd48b6108cf/Core/Debugger/WebSocket/DisasmSubscriber.cpp#L323

Then infinite loop happens here:
https://github.com/hrydgard/ppsspp/blob/2735b09ebc5b3fe41161143cdb60bcd48b6108cf/Core/Debugger/WebSocket/DisasmSubscriber.cpp#L333-L335

There is also less important issue with overflow in this expression ` start + MAX_RANGE * 4` it prevents disassembling of memory addresses greater than 0xFFFF63BF. Then `end` is greater than `start` so the loop I mention above is skipped completely and `count` is 0. API response `lines` array is empty.

As a side node this also causes some issues in ppsspp-debugger with disassembly list when going to address >0xFFFF63BF and trying to scroll the list.

### What should happen

API should gracefully handle requests with any data. Even though it doesn't really make sense to disassemble such high memory address I'd still expect the API to behave the same for the entire range. At least it shouldn't lock up the emulator.

### Logs

The only relevant line is
```
Debugger\WebSocket.cpp:103 Waiting for debugger to complete on shutdown
```
when trying to exit the game.

### Platform

Windows

### Mobile phone model or graphics card

Not relevant

### PPSSPP version affected

v1.11.3-1203-g2735b09eb

### Last working version

Probably none

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Yeah, you definitely found some good bugs here :) Shouldn't be too hard to fix when I or unknown get around to it.

**Comment by unknownbrackets** [comment]
I think I noticed this bug at one point when making ppsspp-debugger, but then couldn't reproduce (it was jumping to outer space because of another bug related to scrolling) and forgot about it.  Shouldn't be hard to fix.

-[Unknown]
