### ISSUE TITLE
[Libretro] Frozen image when frameskip is set to anything above 0 or 1 (depending on game framerate)

### ISSUE THREAD

**Issue by bslenul** [hrydgard/ppsspp#14783]
### Game or games this happens in

All

### What area of the game / PPSSPP

So with the libretro core, frameskip only works if it's set to 0 or 1 for 30fps games and only if set to 0 for 60fps games, anything above will just give you a frozen image. The game keeps running in the background, you can still hear the audio and your can move. As soon as you set frameskip back to 0/1 everything goes back to normal.

After bisecting, it looks like it started happening with b41d20dd8265b82352a760a56336459dc06ce43f, so this is not something new but I've never noticed it before because I don't use frameskip.

This is happening with Vulkan/D3D11/GLcore. Tested on Windows but a Linux user confirmed it was happening for him too.

### What should happen

Game should display properly no matter what's the current frameskip value.

### Logs

Nothing helpful in logs.

### Platform

Windows

### Mobile phone model or graphics card

GTX 970

### PPSSPP version affected

6fbc73e

### Last working version

93d8bbc

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by bslenul** [comment]
Ah looks like it depends on the game, just tried with Mega Man Powered Up and Tekken 6 (both 60fps games), the issue happens even with a frameskip value of "1". I'll update the description and title.

**Comment by i30817** [comment]
I'd forgotten about this one, never ended up reporting it. Yes, it happens in linux.

**Comment by bslenul** [comment]
> I think you could use even or odd number of frameskips and the behavior changed

In the few games I've tested it didn't matter, frameskip just didn't work with 60fps games (frozen image even at "1") and only worked with a value of "1" for 30fps games.

Example with Crisis Core and Mega Man Powered Up (best to watch with audio so you can hear the game while the image is frozen):

https://user-images.githubusercontent.com/33353403/131394638-cdea7e32-5d27-4c1d-8067-9e01238b3566.mp4

**Comment by i30817** [comment]
Ah that's actually different from what i remember. You could go in game in what i recall, you just had a black screen.

**Comment by bslenul** [comment]
OK so it looks like my bisect is only correct for GLcore driver, frameskip was already broken in the "last working commit" I mentioned with D3D11 (crashes with Vulkan so I couldn't test that...), I went further and it was already broken in 0b17dd0 too, I'll go deeper, I'm now curious to see if it ever worked properly with D3D11 with the core... 😅

**Comment by hrydgard** [comment]
Maybe just not expose frameskip to retroarch at all?

As time goes on and platforms grow more powerful, the need to support frameskip is reduced..

**Comment by i30817** [comment]
That would more or less the equivalent to saying 'every pc from before 2009 and every mobile from before 20-something' is no longer supported, so if you go that way you can break backwards compatibility on a lot more than just frameskip.

**Comment by hrydgard** [comment]
Yeah, I mean just for retroarch, indeed. I care about supporting old devices in the standalone builds, all the way back to Android Gingerbread. But most people running Retroarch do so on pretty capable machines, I would think?

**Comment by ghadiri1380** [comment]
thank s

**Comment by unknownbrackets** [comment]
I seem to remember suspecting that libretro runs PPSSPP on constant fast forward, to disable PPSSPP's timing or something.  Maybe that is part of the puzzle.

I'd say PPSSPP on libretro already runs slower and buggier than standalone, based on the reports I've seen.  I doubt anyone is running it in retroarch for the performance.  I'd say it's better to not have a broken setting.

-[Unknown]

**Comment by stuken** [comment]
I've taken a look at the fast forward thing. It looks like it was hard enabled because during the initial porting work there was no way for a core to know if the frontend was fast forwarding. This is now exposed through an experimental callback.
I did some quick wiring up of that and the ppsspp fastforward and it doesnt seem to have regressed any timings. I've got a bit of a patch in the works to clean up a few things, including that. But thats an aside.

Anyway, this looks like your culprit:
https://github.com/hrydgard/ppsspp/blob/ae9bf279910dc380183168f340665587a020b1d9/libretro/LibretroGraphicsContext.h#L54

I've not investigated all the permutations but removing that if check appears to fix things. If it's safe accross all the drivers I will add it to the rest of my patch.

**Comment by bslenul** [comment]
Damn, nice find! 👍 I messed a bit with this change, AFAICT it works like a charm with GLcore and D3D11 on Windows 10! It kinda works with Vulkan too but I'm getting a lot of crashes when changing value :/ Probably related to all the other Vulkan crashes that happen with the core tho. And for some reason, no matter how hard I try, I can't trigger the crash with RA attached to a debugger 😓

**Comment by unknownbrackets** [comment]
I don't know why you'd want to avoid swapping buffers when the skip draw flag is set (note: it's set to skip DRAWING for the *next frame*, so that indeed might cause problems.)  Standalone doesn't do that.

-[Unknown]
