### ISSUE TITLE
(Android)(Mali) Blackscreen using vulkan backend on some games

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#14796]
### Game or games this happens in

ULJM05404

### What area of the game

Hakuto No Ken Raoh Gaiden
![Screenshot_2021-09-06-17-23-43-569_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/132193710-acdbd853-73da-428f-ab3f-34d937f452ea.jpg)

![Screenshot_2021-09-05-19-46-49-651_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/132125595-caac8c04-add7-4ca2-83b2-161c126113fe.jpg)

Slender Portable 0.4
![Screenshot_2021-09-06-17-22-04-557_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/132193495-51e60514-2a94-4474-aa49-04f1a5ec619b.jpg)

![Screenshot_2021-09-06-17-02-12-854_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/132191127-4ee3cb06-119d-4c9e-833d-a5b34c817f7f.jpg)
OpenGL work fine
![Screenshot_2021-09-06-17-03-06-010_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/132191798-abc7889b-4d68-4037-8d28-b2c950ce7c22.jpg)

### What happens

Blackscreen using vulkan but I can hear sound of the game.

### What should happen

No blackscreen

### GE frame capture

[Hakuto No Ken Raoh Gaiden.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/7111513/recording.ppdmp.zip)
[slender_portable.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/7114750/slender_portable.ppdmp.zip)

### Platform

Android

### Mobile phone model or graphics card

Redmi Note 9 Android 11 Helio G85 Mali-G52 GPU

### PPSSPP version affected

v1.11.3-1241

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by Panderner** [comment]
How about other games working on vulkan?

**Comment by Gamemulatorer** [comment]
Only those two games got a blackscreen using vulkan backend.

**Comment by Panderner** [comment]
> Only those two games got a blackscreen using vulkan backend.

But how about other games?

**Comment by unknownbrackets** [comment]
Does your device show support for depthClamp in the settings?  I'm not sure if this is actually different from #7932, which is already for a subset of devices.

-[Unknown]

**Comment by Gamemulatorer** [comment]
![Screenshot_2021-09-07-01-27-09-623_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/132249073-efeb9564-8de3-4ee2-a7fb-60e892d40394.jpg)
My device doesn't support :( that's the reason why I got blackscreen on those two games?

**Comment by Gamemulatorer** [comment]
I'm not sure if this is actually different from #7932, which is already for a subset of devices.
> 
> -[Unknown]

Ok closing in favor of #7932
