### ISSUE TITLE
[Scoped storage] Shortcut activity broken

### ISSUE THREAD

**Issue by iota97** [hrydgard/ppsspp#14797]
Creating a game shortcut open a file picker that doesn't show any file on master, but was working in 1.11.3 (probably scoped storage permission related).

It uses this file picker: https://github.com/hrydgard/ppsspp/blob/master/android/src/org/ppsspp/ppsspp/SimpleFileChooser.java

**Comment by hrydgard** [comment]
Yeah, I've missed that. That file picker will never work on scoped storage, will need to replace it when it's enabled.

**Comment by hrydgard** [comment]
So much stuff was broken with shortcuts, heh. https://github.com/hrydgard/ppsspp/pull/14813 should fix most of it up... Not tested on very old devices though yet.
