### ISSUE TITLE
(Android)[Feature Request] A Way To Create Homescreen shortcuts and open a game directly from the android launcher

### ISSUE THREAD

**Issue by AnSmileyFace** [hrydgard/ppsspp#14791]
In the game menu (when you tap and hold a game cover)

There would be a new option saying "Create Homescreen Shortcut"

When you click it a shortcut will appear on your home screen with the game's name and icon

That would be very nice feature to have

**Comment by Gamemulatorer** [comment]
Dup https://github.com/hrydgard/ppsspp/issues/10885

**Comment by XiaomiRedmi9** [comment]
Close this as a duplicate mention above 👆
