### ISSUE TITLE
An option to sort games by name instead of recent

### ISSUE THREAD

**Issue by radityaargap** [hrydgard/ppsspp#14809]
### What should happen

or, the ability to set "games" or "homebrew" tab as default. curently i have to keep switching tab to find games easily. it's easier to find games in alphabetical order when i have plenty of them. thanks.

### Who would this benefit

anyone

### Games this would be useful in

Any

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by Gamemulatorer** [comment]
https://github.com/hrydgard/ppsspp/issues/14607#issuecomment-878262835

**Comment by radityaargap** [comment]
how is that relevant?

**Comment by Gamemulatorer** [comment]
> how is that relevant?

Read it!

**Comment by Gamemulatorer** [comment]
Games are already in alphabetical order.
![Screenshot_2021-09-08-21-01-16-771_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/132514137-fd21fd7a-68fd-4fdc-8e36-094e3cdd2559.jpg)
Recent games in alphabetical list? No Sense!!!

**Comment by radityaargap** [comment]
you are confused. just stop replying.

**Comment by iota97** [comment]
You can disable the Recent tab by setting `MaxRecent = -1` in `ppsspp.ini` if you wish. Then it will open on Games tab by default.

**Comment by radityaargap** [comment]
that's awesome. thank you.
