### ISSUE TITLE
Binaries for macOS

### ISSUE THREAD

**Issue by vit9696** [hrydgard/ppsspp#14815]
### Platform

macOS

### Compiler and build tool versions

Xcode 12

### Operating system version

macOS 11

### Build commands used

brew install ppsspp

### What happens

Hello,

Recently I stumbled with an issue within PPSSPP packaging in Homebrew[1], which does not feel too easy to address.

I contacted you in the past through the bugtracker that it would be great to provide macOS binaries over the CI but that did not move much since then. I believe doing that should address all the parties' needs and simplify my own life with installing and updating :) To speedup the process I could provide at least some of the changes in PPSSPP to make that happen.

Namely:

1. Having SDL2 either statically or dynamically bundled, so we do not require brew installation.
2. Updating MoltenVK to be compatible with Apple Silicon.
3. Uploading the commits from GitHub Actions somewhere so that they can be downloaded as nightly.
4. Uploading stable releases from GitHub actions.
5. Perhaps signing the binaries.

For (4) I am thinking of GitHub releases as it is a reasonably common place to grab the files, but it can (also?) be some custom place. For (3) it can remain the per-commit artifacts section, but the website has a dedicated section for the dev builds, so it may be reasonable to use.

Looking forward to hearing your opinion. CC @hrydgard @unknownbrackets 

[1] https://github.com/Homebrew/homebrew-core/pull/84738

### PPSSPP version affected

master

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] Make sure to run `git submodule update --init --recursive` before building.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try deleting the build directory and running the build again.
- [ ] Check GitHub Actions, which builds every merge and PR.
- [ ] Include logs and help us reproduce.

**Comment by unknownbrackets** [comment]
The buildbot at https://buildbot.orphis.net/ppsspp/ doesn't really have a macOS runner and I'm not sure it is able to build any working macOS binaries.

> Having SDL2 either statically or dynamically bundled, so we do not require brew installation.

This was suggested elsewhere and seems fine.

> Updating MoltenVK to be compatible with Apple Silicon.

Sounds like #13708, I know there was a pull request recently closed (don't know why) for this.  I can't currently test any MoltenVK related changes, so any pull requests are welcome.

> Uploading the commits from GitHub Actions somewhere so that they can be downloaded as nightly.

Well, you can download them already, as long as you login.  They do expire after 90 days, though.

It's probably a bit tricky to connect those to Orphis' buildbot (which is not only used for PPSSPP, fwiw.)  The git builds on the PPSSPP homepage actually just show the Orphis page inside an iframe (which is basically how you embed another website into your own.)

> Perhaps signing the binaries.

I don't know what's involved in this, but is Apple more supportive of emulators on macOS than iOS?  Everything I've heard about them suggests to me that they're trying to move macOS more to follow the iOS model, and eventually the same rules.

-[Unknown]
