### ISSUE TITLE
(Vulkan) replace textures + auto high quality texture = crash

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#14814]
### Game or games this happens in

UCJS10110 (Bleach heat the soul 7)

### What area of the game / PPSSPP

At the start of the game instantly crash.
Video recording
[Screenrecorder-2021-09-09-12-22-09-914.mp4.zip](https://github.com/hrydgard/ppsspp/files/7133369/Screenrecorder-2021-09-09-12-22-09-914.mp4.zip)

### What should happen

No crash?

### Logs

[logcat_09-09-2021_12-27-12.txt](https://github.com/hrydgard/ppsspp/files/7133403/logcat_09-09-2021_12-27-12.txt)

### Platform

Android

### Mobile phone model or graphics card

Redmi Note 9 Android 11 Helio G85 Mali-G52 GPU

### PPSSPP version affected

v1.11.3-1280-g5e4c478f4

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by Gamemulatorer** [comment]
Found the cause of this is because of the textures.ini
![Screenshot_2021-09-09-12-02-14-289_com estrongs android pop](https://user-images.githubusercontent.com/37603562/132625115-1ed5e238-ad78-4238-b414-75412488fd8d.jpg)

**Comment by unknownbrackets** [comment]
Ah, that's helpful, but I don't think it should crash.

-[Unknown]

**Comment by Gamemulatorer** [comment]
My replace textures location
![Screenshot_2021-09-09-15-50-37-183_com estrongs android pop](https://user-images.githubusercontent.com/37603562/132645530-1a3e57a1-b1b4-4a92-8f3b-a20be446fcb0.jpg)

**Comment by hrydgard** [comment]
Found a problem with auto-mip generation for non-rectangular textures, fix for that coming up. Hope that will take care of it.

**Comment by hrydgard** [comment]
Please let me know if it works, once that build is available.

**Comment by Gamemulatorer** [comment]
Confirm fixed by https://github.com/hrydgard/ppsspp/commit/46ada8649cf3166db3676f62e0b21b2b69a5bd8b

**Comment by hrydgard** [comment]
thanks for testing!
