### ISSUE TITLE
Crash when selecting memory stick on sdcard (Android Lollipop)

### ISSUE THREAD

**Issue by KaiFujiro** [hrydgard/ppsspp#14821]
### Game or games this happens in

I haven't played game

### What area of the game / PPSSPP

I haven't played game

### What should happen

Why in ppsspp version v1.11.3-1293-g16e820eda Can't select sdcard as memory stick? when i choose on the menu "create or choose psp a folder" my ppsspp crashes immediately. In build version v1.11.2-309-g8e90d0644 you can choose by typing the location to be created on the memory stick. Example set like this: Storage/ExtSdCard/android/data/org.ppsspp.ppsspp

I try it on Android 5.1.1

### Platform

Android

### Mobile phone model or graphics card

J1 Ace J111F

### PPSSPP version affected

v1.11.3-1293-g16e820eda 

### Last working version

v1.11.2-309-g8e90d0644

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Thanks for reporting, this is very useful!

I'm going to test on some old phones, and see if I can reproduce this. If you can figure out how to get ADB logs from the crash, those could also be useful.

**Comment by KaiFujiro** [comment]
I'll take the logcat

**Comment by Gamemulatorer** [comment]
I also have this problem before https://github.com/hrydgard/ppsspp/issues/14544
I will try the latest build again on my ancient phone and see if I can reproduce this.

**Comment by hrydgard** [comment]
Thanks, please do.

Maybe for some older devices, we're gonna end up having to add back the option to type the path in...

**Comment by KaiFujiro** [comment]
I'll take the logcat

**Comment by KaiFujiro** [comment]
Here is the logcat

https://drive.google.com/file/d/1-bgM9d-AKXRbQJdxlro8zgPMTd6AUQk3/view?usp=drivesdk

**Comment by KaiFujiro** [comment]
> Thanks, please do.
> 
> Maybe for some older devices, we're gonna end up having to add back the option to type the path in...

Yes, I like it

**Comment by Gamemulatorer** [comment]
Crashes again.
![Screenshot_2021-09-10-19-36-44](https://user-images.githubusercontent.com/37603562/132848271-b9ae34d9-e937-46b7-bafb-acfc9d74b655.png)

**Comment by KaiFujiro** [comment]
> Crashes again.
> ![Screenshot_2021-09-10-19-36-44](https://user-images.githubusercontent.com/37603562/132848271-b9ae34d9-e937-46b7-bafb-acfc9d74b655.png)

Just be patient, we wait for the bot to make a new build

**Comment by Gamemulatorer** [comment]
> > Crashes again.
> > ![Screenshot_2021-09-10-19-36-44](https://user-images.githubusercontent.com/37603562/132848271-b9ae34d9-e937-46b7-bafb-acfc9d74b655.png)
> 
> Just be patient, we wait for the bot to make a new build

IKT lol 😁

**Comment by hrydgard** [comment]
Ok, thanks for testing and the logs!

I'll get this fixed later.

**Comment by KaiFujiro** [comment]
> Ok, thanks for testing and the logs!
> 
> I'll get this fixed later.

Thx <3

**Comment by ResurrectionRedmi9** [comment]
Change title to (Android) (Lollipop) crash when selecting external sdcard path.

**Comment by hrydgard** [comment]
Super confusing stack traces in that logcat!

I'm charging up some old devices to try to repro...

**Comment by unknownbrackets** [comment]
It did seem like half a stack trace, strangely.  An adb logcat from a PC would probably be more detailed...

With that change merged, is it still crashing?

-[Unknown]

**Comment by KaiFujiro** [comment]
> It did seem like half a stack trace, strangely. An adb logcat from a PC would probably be more detailed...
> 
> With that change merged, is it still crashing?
> 
> -[Unknown]

My ppsspp doesn't crash anymore, but why can't the file path be found?
I wrote it right
"/storage/extsdcard/android/data/org.ppsspp.ppsspp" even by adding
/storage/extsdcard/android/data/org.ppsspp.ppsspp/files.
Still same

**Comment by KaiFujiro** [comment]
Here

[logcat_09-11-2021_10-28-42.txt](https://github.com/hrydgard/ppsspp/files/7147146/logcat_09-11-2021_10-28-42.txt)

**Comment by Gamemulatorer** [comment]
> > It did seem like half a stack trace, strangely. An adb logcat from a PC would probably be more detailed...
> > With that change merged, is it still crashing?
> > -[Unknown]
> 
> My ppsspp doesn't crash anymore, but why can't the file path be found?
> I wrote it right
> "/storage/extsdcard/android/data/org.ppsspp.ppsspp" even by adding
> /storage/extsdcard/android/data/org.ppsspp.ppsspp/files.
> Still same

Try this if its work /storage/sdcard1/android/data/org.ppsspp.ppsspp

**Comment by KaiFujiro** [comment]
oh no, it crashes again, when I select a specific folder outside of android/data.
Examples like this:
storage/extsdcard/PSP.
the "PSP" folder I made myself, maybe it can be detected, even crash

**Comment by KaiFujiro** [comment]
> > > It did seem like half a stack trace, strangely. An adb logcat from a PC would probably be more detailed...
> > > With that change merged, is it still crashing?
> > > -[Unknown]
> > 
> > 
> > My ppsspp doesn't crash anymore, but why can't the file path be found?
> > I wrote it right
> > "/storage/extsdcard/android/data/org.ppsspp.ppsspp" even by adding
> > /storage/extsdcard/android/data/org.ppsspp.ppsspp/files.
> > Still same
> 
> Try this if its work /storage/sdcard1/android/data/org.ppsspp.ppsspp
still undetected

**Comment by Gamemulatorer** [comment]
change sdcard1 to sdcard0 still undetected?
Maybe try to put your sdcard number instead of sdcard? example mine is /storage/3136-6161/PSP

**Comment by KaiFujiro** [comment]
> change sdcard1 to sdcard0 still undetected?
> Maybe try to put your sdcard number instead of sdcard? example mine is /storage/3136-6161/PSP

Well, it works, but there are no folders like textures or save data

**Comment by KaiFujiro** [comment]
> change sdcard1 to sdcard0 still undetected?
> Maybe try to put your sdcard number instead of sdcard? example mine is /storage/3136-6161/PSP

Also on my phone, "sdcard0" and "ExtSdCard" are different.

what I see in the root folder, sdcard0 is still in device storage, and not on the external sdcard

**Comment by Gamemulatorer** [comment]
Still crashing on my ancient phone :(
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.ppsspp.ppsspp/org.ppsspp.ppsspp.PpssppActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2521)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2601)
	at android.app.ActivityThread.access$800(ActivityThread.java:178)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5637)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
	at org.ppsspp.ppsspp.NativeActivity.Initialize(NativeActivity.java:403)
	at org.ppsspp.ppsspp.NativeActivity.onCreate(NativeActivity.java:602)
	at org.ppsspp.ppsspp.PpssppActivity.onCreate(PpssppActivity.java:120)
	at android.app.Activity.performCreate(Activity.java:6100)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2468)
	... 11 more
```

**Comment by KaiFujiro** [comment]
@hrydgard 
Wow, I found the solution, so now the letters we type must match the name of the storage location.
correct example like this:
/storage/extSdCard/Android/data/org.ppsspp.ppsspp

not like this:
storage/extsdcard/android/data/org.ppsspp.ppsspp.

The key is in the name "extSdCard"
If you write it wrong, then it won't be detected

**Comment by KaiFujiro** [comment]
In the past in version v1.11.2-309-g8e90d0644  just writing it like "storage/extsdcard/android/data/org.ppsspp.ppsspp" it worked immediately, as long as you know what your sdcard's name is, some only have the name "extsdcard" and have a number.

**Comment by hrydgard** [comment]
Oh, I suppose it would be possible to automatically match the case... The check might have gotten a little too strict (previously no check was done at all, which also had issues of course)

**Comment by hrydgard** [comment]
Merged a fix for that, it should now work at least as well as before.

**Comment by Gamemulatorer** [comment]
My ancient phone still crashing.
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.ppsspp.ppsspp/org.ppsspp.ppsspp.PpssppActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2521)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2601)
	at android.app.ActivityThread.access$800(ActivityThread.java:178)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5637)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
	at org.ppsspp.ppsspp.NativeActivity.Initialize(NativeActivity.java:403)
	at org.ppsspp.ppsspp.NativeActivity.onCreate(NativeActivity.java:602)
	at org.ppsspp.ppsspp.PpssppActivity.onCreate(PpssppActivity.java:122)
	at android.app.Activity.performCreate(Activity.java:6100)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2468)
	... 11 more
```

**Comment by Gamemulatorer** [comment]
Last working build
https://github.com/hrydgard/ppsspp/commit/c7d344875d6d20f4d386defa4e074b7e3c7fa064
![Screenshot_2021-09-12-10-34-20](https://user-images.githubusercontent.com/37603562/132969550-3004d685-cd43-41ad-a078-2922e0ecd820.png)


First break build
https://github.com/hrydgard/ppsspp/commit/35ad3106ff89d8c5a73e09fdca5d291e755f35a1
![Screenshot_2021-09-12-10-32-59](https://user-images.githubusercontent.com/37603562/132969535-3a048380-a81e-4a89-b88f-16761499d683.png)

My sdcard is read-only but it shouldn't crash

**Comment by unknownbrackets** [comment]
Thanks, that's helpful.  Try again after db21d0e builds.

-[Unknown]

**Comment by Gamemulatorer** [comment]
Confirmed fixed by https://github.com/hrydgard/ppsspp/commit/db21d0e7fcc60cd86f8a20e72e7805d457cf6759
