### ISSUE TITLE
Application launches with a black screen for half a minute before the splash screen shows up

### ISSUE THREAD

**Issue by Splatert** [hrydgard/ppsspp#14831]
### Game or games this happens in

None

### What area of the game / PPSSPP

I've never had any problems with PPSSPP until recently. Whenever I want to launch PPSSPP to test out homebrew that I'm working on, nothing is shown but a black screen for nearly half a minute before getting to the splash screen.

https://user-images.githubusercontent.com/82643571/132963340-51fc7489-ff1a-4148-baa0-34ec2b06470c.mp4

PPSSPP then loads up just fine.

### What should happen

PPSSPP shouldn't take a minute to load up.

### Platform

Windows

### Mobile phone model or graphics card

NVIDIA Geforce RTX 2060 Super

### PPSSPP version affected

v1.11.3

### Last working version

v1.11.3 several days ago

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Super weird!

Can you try some older builds and try to narrow down when this started happening? buildbot.orphis.net/ppsspp/

**Comment by Splatert** [comment]
I've just tried to launch PPSSPP on many of the previous builds (stopped around1.10.3) and I'm still having this problem.

This started happening today as I got home to continue working on my homebrew for the PSP. The emulator was working fine all day yesterday. Today I've launched the emulator in order to test my homebrew but this strange delay keeps on occurring whenever I open PPSSPP.

**Comment by iota97** [comment]
Did your homebrew wrote some weird file in PSP folder that we are parsing maybe? Does it happen with a "clean installation" of PPSSPP?

**Comment by Splatert** [comment]
I don't think so. I've uninstalled the emulator, deleted any remaining folders (PPSSPP in My Douments folder unless it left many more folders somewhere that I'm unaware of), and tried many previous builds but I'm still getting this problem. The homebrew I'm working on is just lua code that's ran by a lua interpreter called OneLUA.

**Comment by unknownbrackets** [comment]
Things that can cause this:
 * Graphics, audio, or USB drivers.  Try updating (or downgrading if you recently upgraded.)
 * Pending installations or driver updates.  Have you tried turning it off and back on again?
 * Game center or customization features, such as Windows game recording, GeDoSaTo, Reshade, NVIDIA, etc.
 * Outdated drivers from a previously installed device, especially a graphics card when you switch vendors (i.e. ATI vs NVIDIA.)

You may be able to try disabling audio or switching graphics backends and restarting to narrow this down.

You can also try pressing Ctrl-Win-Shift-B which restarts your graphics driver.  Sometimes this helps.

-[Unknown]

**Comment by Splatert** [comment]
I wasn't able to solve this issue but it's okay. I can live with that.
