### ISSUE TITLE
Storage selection screen on first start needs better design

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#14830]
Just a reminder to myself to myself to take a look at this before the release, and some notes.

There's been a concern that the back button and its column takes too much space, so long strings in the Thai (and probably other) translations don't fit, so need to make sure word wrapping works.

It should also be clearer what the best/default choice is, the text needs some editing, and the design just needs to look cleaner.

**Comment by unknownbrackets** [comment]
It's very wall of text, currently.  i would suggest:

1. Switch to an accordion UX, with one option pre-selected and recommended.  Only that option would show details, while the other would be a title only.
2. For "Create or choose a PSP folder", show a clear CTA to the right like "Continue".  Users typically "get their barings" on a new screen, and when there's no clear terminator (thing at the end where buttons usually appear), it's already stressful.
3. Try to make sure at least 20% of the screen vertically is blank so it doesn't feel "packed with information".

Splash pages in general aren't great, though.  I'm sure if I asked any UX friend for their ideas that's the first thing they'd say, but not sure what choices we have...

-[Unknown]

**Comment by hrydgard** [comment]
Yeah the current one is very unsuitable to being the first thing the user sees, and needs visual cleanup either way. Accordion is certainly one option.

Sketch of much simple very first screen:

Welcome to PPSSPP!

  * > Set up PSP save data storage (memory stick)
  * Do later

  [ What is this ] -> leads to explanation on PPSSPP's website

The first choice ("Set up...") just leads to a visually cleaner version of the current screen. It'll also have a link to the explanation page.

The second choice ("Do later") just defaults to the external private directory ( Android/data/org.ppsspp.ppsspp/ etc) and goes to the main screen. Then we might need a nudge later to get the user to actually choose a folder for the storag, but not sure what that should look like.

I know splash screens aren't good, but I do want to nudge the user pretty hard to at least build some awareness about the problem. Otherwise, I fear lots of support email about lost savegames where people have uninstalled and reinstalled. Or maybe that's just expected behavior these days...  But it might not be for old users.

I mean ideally we should probably "just" add cloud save support and the whole proplem of persistence mostly goes away.

**Comment by unknownbrackets** [comment]
Yeah, I think the other option from a splash screen is pretty much to default to private storage, but show an obnoxious warning (like we do on Windows when you're in TEMP - it's even named `storageIsTemporary`) that they can dismiss or tap to do something about it.

In some ways that may be better, but I also think a lot of people who have used PPSSPP previously will be confused...

-[Unknown]

**Comment by iota97** [comment]
With the current logic if a user press a physical back button he go back to `LogoScreen` and then into `MainScreen` skipping the setup.

I think it should switch to `MemStickScreen` after showing `LogoScreen` anyway, would be a less painful welcome with that.

**Comment by hrydgard** [comment]
This is quite a bit better now with #14875 merged.

Of course there's more to be done and more polish to add but the critical parts are fixed now (except translations...)
