### ISSUE TITLE
The keyboard does not appear when typing in the menu like cpu clock

### ISSUE THREAD

**Issue by KaiFujiro** [hrydgard/ppsspp#14834]
### Game or games this happens in

Not a game

### What area of the game / PPSSPP

Not a game

### What should happen

So usually in menus such as cpu clock, mem hog, there is a menu that we can add and subtract by pressing the + & - buttons.
But it can also be done by typing the number we want, and usually the keyboard will appear to enter that number into the menu, but this is not

### Logs

Only screenshots of the menu in question
![Screenshot_2021-09-12-10-05-57](https://user-images.githubusercontent.com/71515107/132970659-ac7c2ed3-ca78-4be4-b42b-c1b91094a5ee.png)

### Platform

Android

### Mobile phone model or graphics card

J1 Ace J111F

### PPSSPP version affected

v1.11.3-1341-gf1c05b039

### Last working version

v1.11.2-309-g8e90d0644

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by Gamemulatorer** [comment]
That's also happen on stable version ppsspp gold v1.11.3 CPU Clockspeed, Memory Hog, Display Editor Zoom, Global Volume and Alternative Speed etc...

And you said that's your keyboard show up and version 1.12.309?

**Comment by KaiFujiro** [comment]
> That's also happen on stable version ppsspp gold v1.11.3 CPU Clockspeed, Memory Hog, Display Editor Zoom, Global Volume and Alternative Speed etc...
> 
> And you said that's your keyboard show up and version 1.12.309?

Yes, when version 1.11.2 can appear the keyboard, although I know this is only a minor bug

**Comment by KaiFujiro** [comment]
Better tell him right?

**Comment by Gamemulatorer** [comment]
Well this also can reproduce on older v1.10.3 ppsspp :/

**Comment by Gamemulatorer** [comment]
This is not really implemented even on version v1.11.2-309-g8e90d0644 you said.
I don't think this is a bug this is a feature request instead :)

**Comment by KaiFujiro** [comment]
> This is not really implemented even on version v1.11.2-309-g8e90d0644 you said.
> I don't think this is a bug this is a feature request instead :)

Hmmm maybe

**Comment by Gamemulatorer** [comment]
Why closing? This is still a feature request.
