### ISSUE TITLE
UI Misc Issue I Found

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#14844]
### What should happen

The enable compatibility server reports get UNCHECK when I choose ui background animation.
https://user-images.githubusercontent.com/37603562/133083063-5c39be01-296b-4ca2-9eb4-b0dccb8e87dd.mp4

Suddenly I cannot change ui background wallpaper on my android 11 but on my ancient phone no problem.
https://user-images.githubusercontent.com/37603562/133083671-d16d39e8-a78a-45c1-993c-4ad55b182e1a.mp4

Analog stick stuck on press down when I choose it in tilt type input.
https://user-images.githubusercontent.com/37603562/133084032-5b246aa6-a8c2-475b-96ab-ac63eab85c6f.mp4

### Who would this benefit

Everybody

### Platform (if relevant)

Android

### Games this would be useful in

User Interface

### Other emulators or software with a similar feature

None

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by unknownbrackets** [comment]
I'd guess the tilt thing means we're reading a value that's constantly pointing some direction from some sensor.  Probably not a new issue and probably needs better configuration...

-[Unknown]

**Comment by Gamemulatorer** [comment]
> I'd guess the tilt thing means we're reading a value that's constantly pointing some direction from some sensor. Probably not a new issue and probably needs better configuration...
> 
> -[Unknown]

Yes you're right 👍

**Comment by Gamemulatorer** [comment]
My last concern is the word load... in the main menu I'm confused about that but I know that is load the game so why not change it to load game? or load iso? IMO :)
![IMG_20210914_014808](https://user-images.githubusercontent.com/37603562/133132062-5dfc8cf2-4e38-4e0d-96f5-30d10c8a6bc5.jpg)

**Comment by unknownbrackets** [comment]
I'm moving the rest of this to Future-Prio - doesn't mean it will or won't still happen for v1.12.x, just that I don't think the rest blocks v1.12.x - tilt is existing, Load is a good thing to consider but not a blocker.

I could see "Load..." being "Load game...", although I think "Load..." is clear enough and there's something to be said for keeping it terse.  As long as it doesn't take away from understanding, shorter looks visually better.

-[Unknown]

**Comment by ANR2ME** [comment]
Btw, not sure if this can be considered an UI issue or not, but the X and O button during Save/Load Data can be confusing.

For example, on most Japanese region's games, O button usually used for OK while X for Cancel, but during Save/Load Data the X button is always the OK button, while O can be used to Cancel it.

**Comment by unknownbrackets** [comment]
It's because it uses system settings (this problem actually happened on real PSPs too.)  A few PSP games actually use the system setting to determine which of X/O to use outside savedata, but most don't.

-[Unknown]

**Comment by Gamemulatorer** [comment]
Yes the confirmation button in system kinda useless in Japanese Games.
![Screenshot_2021-09-14-09-17-26](https://user-images.githubusercontent.com/37603562/133178787-0ef5545e-4759-4a5d-87cb-ede55cfe86fb.png)

**Comment by Gamemulatorer** [comment]
Closing this, not really important.
