### ISSUE TITLE
[Android] [Regression] Tom Clancy Ghost Recon Crashing

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#14864]
### Game or games this happens in

ULES01350

### What area of the game / PPSSPP

Crash after entering name.
https://user-images.githubusercontent.com/37603562/133541472-2a97f603-550a-4b14-8bdd-4219ab1b0977.mp4

### What should happen

No crash 🤔

### Logs

[logcat_09-16-2021_10-45-29.txt](https://github.com/hrydgard/ppsspp/files/7174570/logcat_09-16-2021_10-45-29.txt)

### Platform

Android

### Mobile phone model or graphics card

Redmi Note 9 Android 11 Helio G85 Mali-G52 GPU

### PPSSPP version affected

v1.11.3-1402

### Last working version

Stable version

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by Panderner** [comment]
@Gamemulatorer find the older build when the issue started on.

**Comment by Gamemulatorer** [comment]
Also crashing on my ancient phone mali-450 gpu.

I will try to find the build where this issue started.

**Comment by unknownbrackets** [comment]
Looks like a crash in an assert for UtilityDialogInitialize, because the PSPThread wasn't stopped yet.  I'm not sure how this can happen.  I don't think finding the specific build will tell me much more.

It was a msgdialog being init, but that shouldn't happen when another init is in progress.

There must be some case that's allowing it to get here during another dialog or the same dialog's init or shutdown...

-[Unknown]

**Comment by unknownbrackets** [comment]
A log from trying the artifacts from #14865 (once it builds) would be helpful.  Or just run that build with compatibility reporting on.

I'm wondering if maybe there's a window - theoretically - after init finish where thread scheduling could've just not shut down the thread yet from its return.  If that's what it is, I can fix it properly - the logging should tell me.

-[Unknown]

**Comment by Gamemulatorer** [comment]
Confirmed fixed by https://github.com/unknownbrackets/ppsspp/commit/570d84fb8632d101e107a481f12e39c1d44229a0
![Screenshot_2021-09-16-15-37-24-951_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/133570778-df0096d2-0c5c-47e1-a47b-3e94d3b88c4b.jpg)
