### ISSUE TITLE
(Libretro) Expose "Backend" in core options

### ISSUE THREAD

**Issue by BParks21** [hrydgard/ppsspp#14866]
### What should happen

Users should be able to override retroarch's global video driver with a per core option. 

### Who would this benefit

People who want to set a global video driver in retroarch but prefer to use something specific in the ppsspp core.

### Platform (if relevant)

libretro / Retroarch

### Games this would be useful in

Any

### Other emulators or software with a similar feature

Some cores already give us this option. Like Beetle PSX, Mupen, and PCSX2. Hopefully this hasn't been requested already. If it has I apologize.

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by BParks21** [comment]
Would it be possible to add every video driver option in the core options? For instance if I wanted to force ppsspp to use glcore instead of just gl or vice versa I could just select one or the other in the core options? I honestly wish every core could do this. That way a whole separately saved RA core override isn't necessary just to load a core with a specific video driver.

**Comment by Sanaki** [comment]
Technically, probably. I have no idea why anyone would ever choose gl over glcore if their system supports both though, so adding a core option to enable that seems rather pointless.

**Comment by BParks21** [comment]
> Technically, probably. I have no idea why anyone would ever choose gl over glcore if their system supports both though, so adding a core option to enable that seems rather pointless.

Well right now using glcore for ppsspp instead of gl causes issues going in and out of fullscreen.

**Comment by sonninnos** [comment]
Unfortunately it was not possible to add both gl and glcore due to the way the frontend will return the offer, but hopefully it won't even matter anymore.
