### ISSUE TITLE
List of Konami games not smooth using opengl backend in mali gpu

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#14861]
### Game or games this happens in

ULUS10301 & ULES00718

### What area of the game

Hellboy - The Science of Evil

https://user-images.githubusercontent.com/37603562/133390786-77fb89be-c831-48f2-ad84-7b044e30247f.mp4

Coded Arms - Contagion

https://user-images.githubusercontent.com/37603562/133390870-318f2bb3-7e17-4316-a8b6-c9112534d24e.mp4

https://user-images.githubusercontent.com/37603562/133390893-7206e48c-b00f-454c-93dc-c2f064500cb1.mp4

### What happens

Hellboy - The Science of Evil and Coded Arms - Contagion is not smooth on OpenGL backend.

### What should happen

Smooth performance like in Vulkan backend. 

### GE frame capture

[contagion.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/7167825/contagion.ppdmp.zip)
[hellboy.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/7167826/hellboy.ppdmp.zip)

### Platform

Android

### Mobile phone model or graphics card

Redmi Note 9 Android 11 Helio G85 Mali-G52 GPU

### PPSSPP version affected

v1.11.3-1380-github

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
So how big is the difference compared to Vulkan? 

This might be a fundamental performance limitation in the drivers on the device, or it's of course possible that we do something silly in OpenGL, hard to say without investigating.

**Comment by Gamemulatorer** [comment]
> So how big is the difference compared to Vulkan?

Full performance on vulkan backend while on OGL is 40/60 FPS Hellboy The Science of Evil and Coded Arms Contagion is Half the performance on Vulkan.
Hope you will find a way to make OGL as fast as vulkan.
Thanks for making PPSSPP and God Bless!

**Comment by Panderner** [comment]
@Gamemulatorer can you make the difference by lowering the resolution to 1x?

**Comment by Panderner** [comment]
Hellboy and Coded Arms Contagion had better performance for my phone using OpenGL:

Hellboy - The Science of Evil:
![Screenshot_2021-09-15-20-15-56-256_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/133432065-fae4b160-1606-4bf1-a84e-bf4997c49b6b.jpg)
![Screenshot_2021-09-15-20-16-48-011_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/133432081-6956cf65-9cd1-4f70-bfa5-d61ede6a296a.jpg)

Coded Arms Contagion:
![Screenshot_2021-09-15-20-14-30-316_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/133432179-e9c45e3e-6c2a-4288-92ff-b7f2d7c0d1c6.jpg)
![Screenshot_2021-09-15-20-14-53-139_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/133432191-65420168-5a15-4060-b60f-6e79c0540e69.jpg)

The screenshots attached are using OpenGL at the top and Vulkan at the bottom.

**Comment by Gamemulatorer** [comment]
> Hellboy and Coded Arms Contagion had better performance for my phone using OpenGL:
> 
> Hellboy - The Science of Evil:
> ![Screenshot_2021-09-15-20-15-56-256_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/133432065-fae4b160-1606-4bf1-a84e-bf4997c49b6b.jpg)
> ![Screenshot_2021-09-15-20-16-48-011_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/133432081-6956cf65-9cd1-4f70-bfa5-d61ede6a296a.jpg)
> 
> Coded Arms Contagion:
> ![Screenshot_2021-09-15-20-14-30-316_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/133432179-e9c45e3e-6c2a-4288-92ff-b7f2d7c0d1c6.jpg)
> ![Screenshot_2021-09-15-20-14-53-139_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/133432191-65420168-5a15-4060-b60f-6e79c0540e69.jpg)
> 
> The screenshots attached are using OpenGL at the top and Vulkan at the bottom.

You already said that here lol
https://github.com/hrydgard/ppsspp/issues/11953#issuecomment-851090150

**Comment by Panderner** [comment]
I know @Gamemulatorer that means Adreno GPU on Vulkan is slower than OpenGL, and I tested both games using both OpenGL and Vulkan it ran full speed for my PC.

**Comment by Panderner** [comment]
Feel free to close this because OpenGL & Vulkan are performance dependent, If the Adreno phone performance for Vulkan is slower than OpenGL and then the Mali phone performance for OpenGL is slower than Vulkan because you increased the resolution. If the game doesn't ran at full speed in your display's native resolution you have to lower the resolution.

**Comment by Gamemulatorer** [comment]
So if I close this issue GoW OpenGL performance decrease should also be close https://github.com/hrydgard/ppsspp/issues/11953#issuecomment-851090150
This is a Mali GPU performance problem on OpenGL and I don't care about adreno gpu :P

**Comment by hrydgard** [comment]
Well, a decrease in performance, where it used to be faster before, is more interesting that just seeing that OpenGL is slower than Vulkan in some specific situation. Anyway, I don't really have a problem with leaving these open, but they of course aren't gonna be highest priority, and in many cases there might not be much to do.

**Comment by Panderner** [comment]
Since I don't have any PowerVR device that supports Vulkan (My Realme C2 doesn't support Vulkan) we need to test PowerVR devices that affects performance for both OpenGL or Vulkan. Thank you @hrydgard!

**Comment by Gamemulatorer** [comment]
> Anyway, I don't really have a problem with leaving these open, but they of course aren't gonna be highest priority, and in many cases there might not be much to do.

Yes thanks for understanding also tag this as mali gpu only.

**Comment by Panderner** [comment]
As I mentioned here: https://github.com/hrydgard/ppsspp/issues/14954#issuecomment-935321722 

It means flagship chipsets such as Samsung Exynos, HiSilicon Kirin and Mediatek Dimensity series can run these games at full speed on OpenGL. This mean your phone CPU is weak to run at full speed for higher resolutions.

**Comment by Gamemulatorer** [comment]
> As I mentioned here: [#14954 (comment)](https://github.com/hrydgard/ppsspp/issues/14954#issuecomment-935321722)

That's is Vulkan

**Comment by Panderner** [comment]
> That's is Vulkan

Can you increase the resolution higher until the game starts slowdown?

**Comment by Gamemulatorer** [comment]
This is ok now using the recently build.
![Screenshot_20221113-212620](https://user-images.githubusercontent.com/37603562/201524080-c14be82b-dca1-4b94-a16a-273b25c0c31f.png)
