### ISSUE TITLE
Video rendering glitches/stuttering in Valkyria Chronicles 2

### ISSUE THREAD

**Issue by vit9696** [hrydgard/ppsspp#14873]
### Game or games this happens in

ULUS-10515 Valkyria Chronicles II

### What area of the game / PPSSPP

During the Valkyria Chronicles II intro section prior to the main menu there is a video, which does not seem to be playing correctly even with the stock (PPSSPP-provided) version of ffmpeg. I am aware of https://github.com/hrydgard/ppsspp/issues/11490 and https://github.com/hrydgard/ppsspp/pull/14188, but this one should not be the same thing as I am using the builtin ffmpeg version, i.e. a relatively old one.

Does everyone observe this behaviour: [recording.mp4.zip](https://github.com/hrydgard/ppsspp/files/7190237/recording.mp4.zip)? The issue is particularly noticeable during the logo stage at 00:25 of the video. My primary worry is whether it is macOS-specific or not.

### What should happen

The video should play smoothly.

### Logs

I can only observe the following logs right before video startup:
```
00:33:229 Odin_Main    E[ME]: HLE/sceMpeg.cpp:1386 UNIMPL sceMpegAvcDecodeFlush(08d571f0)
00:33:330 Odin_Main    E[ME]: HLE/sceMpeg.cpp:1386 UNIMPL sceMpegAvcDecodeFlush(08d571f0)
```

### Platform

macOS

### Mobile phone model or graphics card

Radeon RX 590 8 GB

### PPSSPP version affected

v1.11.3-1427-gd944c254c

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by LunaMoo** [comment]
Probably specific to MacOS. Can't reproduce on Windows.

**Comment by unknownbrackets** [comment]
How confident are we that it's using the correct headers *and* the correct library for ffmpeg?  Maybe one of them somehow was wrong.

-[Unknown]

**Comment by vit9696** [comment]
The library is definitely correct, because I checked it with `otool -L` (like `ldd` on Linux), and there are no dynamic imports for ffmpeg.

The headers should be correct, but I am only 99% sure. I can check. It is harder to do it on the CI (any suggestions?). However, I have a self-compiled version, where it also is reproducible. Here I believe I simply do not have ffmpeg installed at the moment.

**Comment by vit9696** [comment]
I am confident that the builtin headers are used:

```C
#define LIBAVCODEC_VERSION_MAJOR  57
#define LIBAVCODEC_VERSION_MINOR  24
#define LIBAVCODEC_VERSION_MICRO 102
```

**Comment by vit9696** [comment]
Caused by `TextureBackoffCache. I am not sure whether it should work with it, but at the very least it is disabled by default. Not sure why I had it enabled. Closing.
