### ISSUE TITLE
[libretro] somehow make assets not required 

### ISSUE THREAD

**Issue by InfamousKnight** [hrydgard/ppsspp#14878]
In the libretro guide, for some reason an assets folder is needed. While it's not that big of a deal, it's just inconvenient.

**Comment by unknownbrackets** [comment]
This is really a duplicate of #12820, which itself was closed as a duplicate of https://github.com/libretro/retroarch-assets/issues/356.  This is really a flaw in libretro.

For example, many games, programs, utilities, etc. I use require various files.  If I tried to install Photoshop by only copying over the exe file, it wouldn't work.  That'd be my fault (or libphotoshop's fault), not anything to do with Photoshop itself.

-[Unknown]
