### ISSUE TITLE
zim texture replacement doesn't work in latest build

### ISSUE THREAD

**Issue by eleriaqueen** [hrydgard/ppsspp#14877]
### Game or games this happens in

NPJH50332 / UCUS98612

### What area of the game / PPSSPP

Bleeding edge PPSSPP build (1.11.3-1427) seems to ignore *.zim files, doesn't seem to produce any error in the log that's available at runtime, tested switching Texture Replacement on / of on all backends in Phantasy Star Portable 2 - Infinity. I also tried an HD texture pack for Wipeout Pure someone made and was supposed to work but it didn't. Then I tried PPSSPP 1.11.3-1362 and both packs worked fine.

(Link to the WipeOut Pure pack -> https://github.com/NR74W/WipEout-Pure-HD-Texture-Pack )
(Link to the Phantasy Star Portable 2 Infinity pack -> https://mega.nz/file/fph0TTpY#mgaTe95SNWqcoiazFzAvZcsaxfjhNLoxwedeFbKU10M )

### What should happen

*.zim should be loaded / should replace game textures.

### Platform

Windows

### Mobile phone model or graphics card

NVIDIA GeForce 1660 Ti

### PPSSPP version affected

ppsspp-v1.11.3-1427-gd944c254c-windows-amd64

### Last working version

ppsspp-v1.11.3-1362-gbb3a03ada-windows-amd64

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
Oops, that was a dumb mistake.  Should be fixed now.  Thanks for reporting.

-[Unknown]

**Comment by unknownbrackets** [comment]
By the way, how has your experience been, performance-wise, with ZIM textures compared to PNG textures?

-[Unknown]

**Comment by eleriaqueen** [comment]
I've only done quick tests, but zim seems pretty useful to have smoother performance, I like it !
