### ISSUE TITLE
[Android] [Input/Controller] Touch Controller Issue. 

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#14898]
Sometimes dpad stuck on touch 🤔
this video will tell the issue

https://user-images.githubusercontent.com/37603562/134115137-598cdf9e-c2c9-4cf3-9376-be8b3ed5616f.mp4

Correct behavior.

https://user-images.githubusercontent.com/37603562/134115169-7f73dc3c-8dbb-4ffe-9b57-e37047da9dfa.mp4

Last working build.
https://github.com/hrydgard/ppsspp/commit/92a888cd2da96de7b880b94c780f6c26828a8133

Issue started in @iota97 dpad drag fix commit.
https://github.com/hrydgard/ppsspp/commit/98a0d7189ebf7d09426925067cdcf312431518f6

**Comment by hrydgard** [comment]
@iota97  hm? Is this something that only happens if you overlap the stick and dpad?

**Comment by iota97** [comment]
Yeah, I was ignoring the input that involved the analog on all event, gotta change to only "drag over", I really didn't expect this use case :/

**Comment by hrydgard** [comment]
It is a bit odd, I've never tried to do that :) Oh well.
