### ISSUE TITLE
PPSSPP is resolving the DNS "myneighborsushicat.com" even when WLAN is off

### ISSUE THREAD

**Issue by ppssppoff-unique** [hrydgard/ppsspp#14899]
### Game or games this happens in

Any

### What area of the game / PPSSPP

When the game inits sceNetAdhoc.

### What should happen

Even if the configuration "Enable networking/WLAN" is off PPSSPP will try to resolve the DNS mentioned above. It should not do this since WLAN is off.

### Logs

sgx-psp-pcm- E[SCENET]: HLE/proAdhoc.cpp:1328 DNS Error Resolving myneighborsushicat.com

### Platform

Linux / BSD

### Mobile phone model or graphics card

Any

### PPSSPP version affected

v1.11 to v1.11.3

### Last working version

v.1.10.3

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [x] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by antipirgos** [comment]
Same problem with ppsspp v1.12.3 and latest Android version when i try to play Tenchu 4 Plus co-op multiplayer missions

**Comment by hrydgard** [comment]
12.3 can't be fixed.

Can you show the log you get in tenchu from a recent version @antipirgos ?
