### ISSUE TITLE
Midnight Club 3 - Detroit

### ISSUE THREAD

**Issue by ADP-Mini-Z** [hrydgard/ppsspp#14896]
### Game or games this happens in

ULUS10021 - Midnight Club 3

### What area of the game

38% done with Career, beat Leo twice and Maria no times. On the second victory, the game slowed down to 0/60 (0.2%). Since then whenever I load into Detroit, it goes to 0/60 (0.1/2/3%) Rarely it'll hit 0.7 or 0.9%, but it won't really be any faster. Load into the ATL, it works fine. Movers to San Diego, it runs well. Movers into the Motor City from either ATL or SD, and there comes that frame drop again. Load into the menu, go to the Detroit garage it'll run fine, but once I exit garage and it finishes loading, frames drop harder then the bass in a Skrillex song. It only seems to get triggered by entering Detroit from anywhere. Didn't have a SINGLE problem before beating Leo for the second time. Some help would be nice because my last save is midway through ATL and I really don't wanna have to go through all that again

[ULUS10021000.zip](https://github.com/hrydgard/ppsspp/files/7199791/ULUS10021000.zip)
Save File ^^^

### Speed seen in PPSSPP

0/60 (0.[varies]%)

### GE frame capture and debug statistics

![Screenshot (657)](https://user-images.githubusercontent.com/91104613/134102311-5ea3118c-d150-4f5e-a2f8-3284fa4658ea.png)
![Screenshot (655)](https://user-images.githubusercontent.com/91104613/134102314-41d5108e-ead8-4060-a7b0-fd26fe424c9d.png)

### Platform

Windows

### Mobile phone model or graphics card

20.19.15.5058

### PPSSPP version affected

v1.11.3

### Graphics backend (3D API)

Direct3D 11

### Any other notes or things you've tried

Renaming my cars, entering from every different possible location, loading a savestate from DT lowering graphics to the absolute minimum, I've yet to load a state from ATL and progress back to DT, but that's what I'm doing now

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [x] Try changing graphics settings to determine if one causes the slowdown.
- [x] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment]
For 0 FPS issue, you will probably need to provide the debug logs too, in case there are some heavy I/O things happening

**Comment by unknownbrackets** [comment]
__KernelReturnFromInterrupt being the slowest syscall is interesting.  I guess it must just be GE callbacks, though.

Lots of draw calls and verts, I wonder if it's failing to flip for some reason...

-[Unknown]

**Comment by ADP-Mini-Z** [comment]
> For 0 FPS issue, you will probably need to provide the debug logs too, in case there are some heavy I/O things happening

Alright, where might I find those?

**Comment by ANR2ME** [comment]
> 
> 
> > For 0 FPS issue, you will probably need to provide the debug logs too, in case there are some heavy I/O things happening
> 
> Alright, where might I find those?

if you run PPSSPP using the provided Debug Log.bat file it will generate ppsspplog.txt file

**Comment by ADP-Mini-Z** [comment]
> > > For 0 FPS issue, you will probably need to provide the debug logs too, in case there are some heavy I/O things happening
> > 
> > 
> > Alright, where might I find those?
> 
> if you run PPSSPP using the provided Debug Log.bat file it will generate ppsspplog.txt file
Ran the file, not seeing the log. Is there a certain location It's supposed to appear in, or anything specific I'm supposed to to?

**Comment by ADP-Mini-Z** [comment]
Solved the issue by doing a fresh installation and copying my saves over.
