### ISSUE TITLE
Android creating default /PSP folder on every launch even after moving Memstick Folder in Settings

### ISSUE THREAD

**Issue by headHz** [hrydgard/ppsspp#14893]
### Game or games this happens in

None

### What area of the game / PPSSPP

On first launch of v1.11.3-1485-gd31eddf41 on android, I went to Settings>System>Memory Stick Folder, selected Create or Choose a PSP folder, then OK. I selected 0/PPSSPP, which already existed and was populated by v1.11.3 Gold to appear as 0/PPSSPP/PSP/GAME and so on. I keep my games at 0/PPSSPP/ISO so everything is easy to move between phones. Restarting v-1485 all my settings were read successfully and all game-specific configs work as intended. However, after deleting the 0/PSP folder created when I first opened v-1485, each time v-1485 is opened (as in from the App Drawer, or from Recent Apps) it creates a new 0/PSP folder, with empty subfolders with just .nomedia files, no .ini files.

### What should happen

The app should respect the change in Memory Stick Location, and only write to the new location specified by the setting as shown at Settings>System without creating a redundant folder at the default location of 0/PSP. This doesn't affect the operation of the app(s), so there's no rush since I just have the redundant folder hidden in my file explorer so I don't put saves/DLC in the wrong place by accident.

### Platform

Android

### Mobile phone model or graphics card

Samsung Galaxy Note 9 (Snapdragon version)

### PPSSPP version affected

v1.11.3-1485-gd31eddf41

### Last working version

v1.11.3 Gold PlayStore release

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
What Android version is your Note 9 running?

I guess we might have some issues if you move the folder on older Android versions that don't support scoped storage.. yeah, makes sense. I'll look into it.

**Comment by headHz** [comment]
Android 10. Forgot to put that, sorry.

**Comment by hrydgard** [comment]
Thanks, that makes sense. I'll get this fixed soon.

**Comment by nassau-tk** [comment]
@hrydgard 
My Galaxy S20 (Android11) too.

**Comment by hrydgard** [comment]
It'll be fixed, don't worry. Just don't have much time until next week

**Comment by unknownbrackets** [comment]
Is this still happening?

-[Unknown]

**Comment by nassau-tk** [comment]
My Galaxy S20 Android11 is not happen!
v1.11.3-1583

**Comment by unknownbrackets** [comment]
Thanks for confirming, I'll close.  If anyone's still seeing this, please comment and we'll reopen.

-[Unknown]
