### ISSUE TITLE
[Translation] Report on "ja_JP.ini".

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#14905]
### What should happen

I cant find some keywords in ja_JP.ini.

In "Control" section.

Eng)　Hide touch analog stick background circle
Jap )　タッチ用アナログスティックの外周円を非表示にする

Eng)　Gesture mapping
Jap)　ジェスチャー操作の設定をする

Eng)　Gesture
Jap)　ジェスチャー

Eng)　Enable gesture control
Jap)　ジェスチャー操作を有効にする

Eng)　Swipe
Jap)　スワイプ

Eng)　Swipe Up
Jap)　スワイプ【上】

Eng)　Swipe Down
Jap)　スワイプ【下】

Eng)　Swipe Left
Jap)　スワイプ【左】

Eng)　Swipe Right
Jap)　スワイプ【右】

Eng)　Swipe sensitivity
Jap)　スワイプの感度

Eng)　Swipe smoothing
Jap)　スワイプの滑らかさ

Eng)　Double tap
Jap)　ダブルタップ

Eng)　Double tap button
Jap)　ダブルタップ時の設定

### Who would this benefit

All Japanese user.

### Platform (if relevant)

Android

### Games this would be useful in

All gesture controlable games.

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
Yes, with my new langtool I'm going to automatically insert the missing strings for translation into all the language files later today, just gonna fix a couple of issues with it.

**Comment by nassau-tk** [comment]
Great!
