### ISSUE TITLE
Custom button shape is not match on Arrow Up/Down/Right/Left.

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#14915]
### What should happen

Custom button shape is not match on Arrow Up/Down/Right/Left.

In Custom key setting.
If you choose Arrow Up in shape then appear "D-pad Down shape".
If you choose Arrow Down in shape then appear "D-pad Up shape".
If you choose Arrow Right in shape then appear "D-pad Left shape".
If you choose Arrow Left in shape then appear "D-pad Right shape".

It's not meaning "Icon".
It's meaning "Shape".

Designation in left, right, up or down should be reversed.

### Who would this benefit

All

### Games this would be useful in

All

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
@iota97 , wanna take this one? :)

**Comment by iota97** [comment]
It's easy to fix, but it was intentional tbh, an arrow looking up is the DPAD down button indeed as the external shape have the arrow head in the DPAD center.

**Comment by nassau-tk** [comment]
@iota97 
yes, You right.
But!!!!
Icon & Shape is using same "Text".
So, If you choose Arrow Up in Icon then appear △.
And, If you choose Arrow Up in Shape then appear Dpad-Down.
It should be separate or reverse Dpad shape.
I think✨

**Comment by hrydgard** [comment]
Hah, yeah, I guess because of the weird shapes of the DPAD buttons they look like arrows pointing the opposite direction... Hm.
