### ISSUE TITLE
Emulator buttons doesn't move even when pressed hard it touches when i do not expect 

### ISSUE THREAD

**Issue by Sommyrex** [hrydgard/ppsspp#14926]
### What should happen

PPSSPP button should be fix for Techno spark5pro,and should be enhanced properly so that when the buttons are pressed it will apply in order,and also when in full screen mode the buttons are hard that i even have to force my hand to press the button which is not enjoyable please fix the issue of PPSSPP button controls to work properly 

### Who would this benefit

Many people have been complaining about the same issue please fix this.

### Games this would be useful in

No

### Other emulators or software with a similar feature

No

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by Panderner** [comment]
@Sommyrex any emulators or games affected?

**Comment by ResurrectionRedmi9** [comment]
The the latest git build on ppsspp buildbot.
https://buildbot.orphis.net/ppsspp/index.php?m=fulllist

**Comment by unknownbrackets** [comment]
Can you explain your problem with more short sentences?  Here's what I understood:

> PPSSPP button should be fix for Techno spark5pro,

"Hello, I am using PPSSPP on a Tecno Spark 5 Pro."

> and should be enhanced properly so that when the buttons are pressed it will apply in order,

"I have a problem with touch screen controls.  When I press multiple buttons something doesn't work.  It has to do with the order I press the buttons in.  I don't want to explain what order I pressed them and what result I got.  But this should be fixed."

>and also when in full screen mode the buttons are hard that i even have to force my hand to press the button

"My phone's screen protector also has reduced the sensitivity of my touch screen.  When I gently touch buttons, it's not always detected.  This might happen in other apps too, not just PPSSPP."

> which is not enjoyable please fix the issue of PPSSPP button controls to work properly

"In summary, I have two issues: touch sensitivity and the order I touch buttons.  It would be great if these could both be fixed."

--

> Many people have been complaining about the same issue please fix this.

It would help if you could link to their feedback.  I suspect I don't understand your problem.  If others have explained with pictures or more detail, that would help.

If I do understand your problem:
 * Please see this to increase your touch sensitivity: https://www.androidauthority.com/android-11-increased-touch-sensitivity-1085295/
 * How hard you press is outside our control.  When Android tells PPSSPP you pressed the screen, we ignore how hard.  As long as Android tells us, even a gentle touch will press buttons.
 * Low price phones often have worse touch screen sensors.  It may only be able to track a few fingers at the same time.  PPSSPP can only react to the fingers your hardware supports.

-[Unknown]

**Comment by justafella** [comment]
OS: Android 10, HIOS 6.1
Chipset: MediaTek Helio A25 (12 nm)
CPU: Octa-core (4x1.8 GHz Cortex-A53 & 4x1.5 GHz Cortex-A53)
GPU: PowerVR GE8320

These are specs for Tecno Spark 5 Pro. At fisrt glance, it doesn't seem so bad that can't handle PPSSPP.

**Comment by Sommyrex** [comment]
Here is a video clip

**Comment by Gamemulatorer** [comment]
@Sommyrex feedback about using the latest ppsspp gitbuild?

**Comment by Sommyrex** [comment]
Let me explain better,ppsspp button works fine at first but stops all of a sudden during gameplay in my phone but when i play other non psp game,i mean android games like militia that uses analog i enjoy the game no analog issue that's all .

**Comment by LunaMoo** [comment]
Please elaborate.

 What do you mean PPSSPP button stops and do you mean actual buttons or analog as you later mentions "if using non psp game that uses analog" as if that was the important part, but without you meantioning of it earlier.

 Do you mean touch controls? Or physical button on a gamepad connected to your device?

 What game are you trying to play and what action you're doing in the game where it stops.

 Does the game run at full speed when the problem happens?(You can enable FPS counter under PPSSPP's graphics settings.)

 Where did you saw "many people complaining" about same thing? An opened issue in here? Play store? Some old forum post? Where exactly?

 What PPSSPP version are you using? (By version we mean the exact/full version number, not "gold/free" as that's completely irrelevant, they're exactly the same thing other than color.)


 Without at least as much information, you're just leaving people to guess what's your problem.

 There were some other guesses, mine would be that you're trying to run some popular game which requires much more powerful device and your fps drops soo much the game becomes poorly responsive and everything comes with a delay which isn't really an PPSSPP issue, but you could at least somewhat improve the situation by reducing your graphics options and/or using some speedhacks(but those aren't free and might as well break the game completely). Playing less popular, less demanding games would also help as each PSP game has it's own requirements and that's as normal as trying to run PC games on a hardware listed below the minimum requirements, the difference is we don't know and can't tell you what hardware each game requires to run smoothly from start to finish, to make things worse it can also heavily differ between one place in game and another even if they appear to the eye as similar.

**Comment by Sommyrex** [comment]
Sorry to disturb you all,it seems that my issue have no solution,i think is my phone issue and not the emulator because have tried different version of the ppsspp and i was actually using the buttons in the emulator and not a controller attached to my phone,i will get a new device i think it will work better.

**Comment by justafella** [comment]
How much time of gameplay you get before the touch buttons stop working? Is it only the analog button that breaks? Which games are trying to play? Have you tried lowering graphic settings? Is the game lagging, stuttering, hanging or whatever? Is there any message on the screen? It still might be a bug, but the developers need you to be as much specific as you can to investigate.

**Comment by ResurrectionRedmi9** [comment]
@Sommyrex no feedback/outdated!

**Comment by Sommyrex** [comment]
I was actually playing pes2018 the game runs smoothly through out,no lagging issue at all,just that when i start playing the game at first the emulator button works fine for like 1min then later on the R and the analog button when dragged will return back once to it position making the players to stand still but other button work well.
That's the issue R and analog works well at first and breaks later it will refuse to respond to touch ,no lagging issue at all

**Comment by justafella** [comment]
As far as I know, PES series goes until 2014 on the PSP. Your problem might actually be related to bad game modding. Try an official PSP title and see if the issue persists.

**Comment by Sommyrex** [comment]
I notice something recently if i use the Dpad and other button like R and X to play the football in the emulator it works fine through out but if i rotate the analog button and i hold my R and X button they all misalign and am use to the analog button already is there a way to fix it.

**Comment by Sommyrex** [comment]
I know it's not the emulator problem but any good setting or upgrade regarding this issue 
Dpad works perfect with the R and X button when pressed but am not used to it.
The analog button when rotated and the R and X button are pressed they all misalign and stops suddenly then i have to wait for like 5secs before the button gains itself again

**Comment by Sommyrex** [comment]
https://youtu.be/tfBtYjAlEWs this video explains everything

**Comment by Sommyrex** [comment]
https://youtu.be/d4Reg4wRQ8Y here is another video of the touch screen button issue in the emulator,from the video you will see that the analog and X button stops during the gameplay
 At times the analog and the R button stops, it's just vice-versa please help me out,am begging.

**Comment by Sommyrex** [comment]
Am using the lastest version of ppsspp1.11.3 have tried other iso games like Spiderman3 and god of war still the same touch issue my android version is 10 3g ram powerful enough to operate ppsspp so why this button issue now.

**Comment by LunaMoo** [comment]
The first video with dude not knowing what's the problem seems to be old missallignment issue, but this changed quite a lot and should no longer be an issue.

 The second video title is pointing to missallignment issue, but whenever the "dot" indicating touch activation shows up, the key under it also is activated, which means there is no actual alignment issue there, in fact it's very unclear to find any issue whatsoever in that second video aside from performance as the game doesn't seem to be running smooth, but that could be just  hardware being too weak.

 If you press the screen, but the dot isn't recorded, it probably just means your touch screen is awful at detecting touch or the detection get's awful with high enough load on your phone occasionally failing to detect your touch completely. Emulation is easily more demanding than way even much prettier looking native games.

**Comment by Sommyrex** [comment]
But i recently erase my phone data and everything that has to do with touch screen works perfectly fine even normal android app games that have to do with analog too works okay,i don't think it's any hardware issue the phone is still new and has enough space am not saying it's the emulator fault and only asking if there is a setting for this.

**Comment by Sommyrex** [comment]
So when is the release date of the new version of ppsspp emulator coming out in google playstore let me try it out.

**Comment by Sommyrex** [comment]
> This is not an issue on ppsspp side this is technically a phone touch issue 🤷 Because on my ancient phone this is also sometimes happen and I understand that this is my phone fault touch panel is problematic 🤦
> 
> The work around on this is use combo button Combine R+X or anything you want and your good to go👍

so what you are saying is that it may be the phone 
panel touch issue,how about this user that face the same problem such as mine from a different android here is the video below and for the combo button it doesn't work it still gets stuck and touches again https://youtu.be/Dc6gnBMDIJU but there is more to that,android varies and there are many users still complaining about the same issue and u are saying the same thing over that it's just the phone issue and the problem still remains there,i could even show more videos regarding touch control issue from different android phone of higher grade since you saying that cheap phones doesn't have the capacity to work properly in ppsspp emulator please fix this issue,i know you can,if you go to playstore see the comment then you know what am talking about.

**Comment by Sommyrex** [comment]
Thanks hrydgard the issue is solved i will rate the PPSSPP 5 star due to the lastest version i was enable to set the analog stick button in the emulator on my android and it's working fine on touchscreen thanks to the developers.

**Comment by Sommyrex** [comment]
Have fixed this issue,it has to do with the date and time in system setting,by clicking on it i saw this feature (use network-provided time) and i toggle it off then i went back to my ppsspp and it's working fine now but this looks strange although but it worked but next time try to make the ppsspp apk to accept all the feature in android thanks for your suggestions 👍.

**Comment by unknownbrackets** [comment]
Thanks for sharing your solution.  Strange that had an effect, maybe it has something to do with power management or other hardware on your device.

Since this is resolved now for you, and we don't know a way for PPSSPP to solve this itself, I'll close.

-[Unknown]

**Comment by Sommyrex** [comment]
It's still malfunction,it my device hardware problem but i will soon get a new device.

**Comment by Sommyrex** [comment]
It's still malfunctioning,is my device hardware problem,i will soon get a new device
