### ISSUE TITLE
Latest android buildbot build freezes when tapping sort by date in tools>save manager

### ISSUE THREAD

**Issue by headHz** [hrydgard/ppsspp#14922]
### Game or games this happens in

None

### What area of the game / PPSSPP

In v1.11.3-1549-g61d73e46e android version. Settings>Tools>Save Manager tapping Date on the top right corner causes a lockup. Usually have to tap around to get the 'Not Responding click here to close' popup. Once, all the taps suddenly went through, including a tap on Back, so that time it escaped. Cannot replicate that escape.

### What should happen

Should let me change sort method so I can view latest saves.

### Platform

Android

### Mobile phone model or graphics card

Samsung Galaxy Note 9 (Android 10)

### PPSSPP version affected

v1.11.3-1549-g61d73e46e

### Last working version

v1.11.3 Gold PlayStore release

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Thanks for reporting, I fixed one issue around this a while ago, but seems there's more to find.

**Comment by unknownbrackets** [comment]
I think it was broken by scoped storage...

-[Unknown]
