### ISSUE TITLE
[Android] [Performance] Star Wars: The Force Unleashed - Historic Mission - Slowdown/Lag/Not Enough FPS

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#14941]
### Game or games this happens in

ULUS10345

### What area of the game

At the historic mission the game is very slow on both OpenGL and Vulkan but most noticable on OGL.

# OpenGL
![Screenshot_2021-09-28-00-30-50-631_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/134950564-e033881b-bd3b-4994-b720-761ace6d5fe6.jpg)
![Screenshot_2021-09-28-00-31-03-554_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/134950568-e4c4439c-42ef-49bf-8848-98f4ae5ced6a.jpg)

# Vulkan
![Screenshot_2021-09-28-00-32-54-306_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/134950626-7ce1fc86-8a93-4b67-88c5-b3e5804048d8.jpg)
![Screenshot_2021-09-28-00-31-55-690_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/134950631-a460fc06-c98a-4d9a-8376-c29e353efbb0.jpg)

### Speed seen in PPSSPP

60% (34/55)

### GE frame capture and debug statistics

[dump.zip](https://github.com/hrydgard/ppsspp/files/7237983/dump.zip)

### Platform

Android

### Mobile phone model or graphics card

Redmi Note 9 Android 11 Helio G85 Mali-G52 GPU

### PPSSPP version affected

v1.11.3-1583

### Graphics backend (3D API)

OpenGL / GLES

### Any other notes or things you've tried

Default settings only other speedup settings doesn't help even lowering rendering resolution.

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the slowdown.
- [X] Include logs or screenshots of issue.

**Comment by Panderner** [comment]
@Gamemulatorer can you lower the resolution to 1x please?

**Comment by Gamemulatorer** [comment]
> @Gamemulatorer can you lower the resolution to 1x please?

Doesn't help as stated above in "Any Other Notes or Things You've Tried".

**Comment by Panderner** [comment]
@Gamemulatorer can you upload savestate for that area?

**Comment by Gamemulatorer** [comment]
> @Gamemulatorer can you upload savestate for that area?

[PPSSPP_STATE.zip](https://github.com/hrydgard/ppsspp/files/7290794/PPSSPP_STATE.zip)

**Comment by Panderner** [comment]
Thanks @Gamemulatorer here's a result:
![Screenshot_2021-10-06-13-47-53-436_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/136147524-3a1ce9d8-808b-4607-b5d8-686b2e522462.jpg)

**Comment by Gamemulatorer** [comment]
PSP console black afterglow is present but not glitchy.

![psp_console](https://user-images.githubusercontent.com/37603562/137747949-81b6b78f-a203-4b97-a732-3679646b0501.gif)

**Comment by Panderner** [comment]
> PSP console black afterglow is present but not glitchy.
> 
> ![psp_console](https://user-images.githubusercontent.com/37603562/137747949-81b6b78f-a203-4b97-a732-3679646b0501.gif)

Umm it's using a PS Vita Console. A real hardware screenshot is needed.

**Comment by Gamemulatorer** [comment]
No improvement over this one after recently vulkan improvement.
![Screenshot_2022-04-16-12-09-16-422_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/163660895-413abd54-2136-4232-9515-05cac425f2d1.jpg)
1X Resolution but still lag.
[star wars the force unleashed.zip](https://github.com/hrydgard/ppsspp/files/8499228/star.wars.the.force.unleashed.zip)

**Comment by Gamemulatorer** [comment]
After updating to android 12 and the recent fix for this game graphics issue
https://github.com/hrydgard/ppsspp/pull/15696
![Screenshot_2022-07-22-18-33-37-622_com android settings](https://user-images.githubusercontent.com/37603562/180421588-ecb13142-63ad-440e-aeb0-f7b37eab08aa.jpg)

The performance is improve on this area of this game so closing...
