### ISSUE TITLE
DarkStalkers / Vampire Chronicles performance regression after softgpu crashfix

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#14953]
I guess it wasn't able to evade the checks added in https://github.com/hrydgard/ppsspp/pull/14952 to fix the Burnout Dominator soft-gpu crash. 

Will need to find some solution here.

**Comment by unknownbrackets** [comment]
A frame dump would help.

-[Unknown]

**Comment by hrydgard** [comment]
There's one in this old issue: https://github.com/hrydgard/ppsspp/issues/12911

**Comment by unknownbrackets** [comment]
In that case, probably fixed by b1009f70f9badba5b06ee3f75a8856aed1606d8e.

-[Unknown]

**Comment by Gamemulatorer** [comment]
> In that case, probably fixed by [b1009f7](https://github.com/hrydgard/ppsspp/commit/b1009f70f9badba5b06ee3f75a8856aed1606d8e).
> 
> -[Unknown]

Confirm it's fast again 👍
![Screenshot_2021-09-30-22-29-02-424_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/135474871-1674858c-e511-4116-8718-013cac98a4c3.jpg)

But some graphic settings should be grey out when software rendering is use IMOO :)
