### ISSUE TITLE
[Android] [GLES2.0] Crash™ Tag Team Racing Game Freeze/Hang With FrameSkipping 1x Cause By #14856

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#14959]
### Game or games this happens in

ULUS10044

### What area of the game / PPSSPP

![IMG_20211003_104437](https://user-images.githubusercontent.com/37603562/135737585-5531f58f-82b3-4357-91e0-9e8609fbd654.jpg)

At the start of the mission the game instantly crash with fast memory enable.

### What should happen

No crash just like on my redmi note 9 phone.

### Logs

```
[10-03 07:57:31.764 28563:28605 F/PPSSPP]
(MemoryUtil.cpp:AllocateAlignedMemory:251) Critical: [ptr != nullptr] Failed to allocate aligned memory
```

### Platform

Android

### Mobile phone model or graphics card

Cloudfone Excite Prime Android 5.1 Mali-450 GPU MT6592 Octacore Processor

### PPSSPP version affected

v1.11.3-1630-github

### Last working version

v1.11.3 playstore

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
This could mean your device was out of RAM.  Does it only happen with OpenGL?  It'd help if we can narrow down when it started.

Are you using texture replacements or texture upscaling?

Seems like this would mainly either be push buffer space, or texture decoding.  Those are the places that call thjs func.  But maybe it ran out of memory somewhere else.

-[Unknown]

**Comment by Gamemulatorer** [comment]
> This could mean your device was out of RAM. Does it only happen with OpenGL?

Well my ancient phone only support OpenGL.

> It'd help if we can narrow down when it started.

I will try later.

> Are you using texture replacements or texture upscaling?

No default settings only because my ancient phone can't handle that.

> Seems like this would mainly either be push buffer space, or texture decoding. Those are the places that call this func. But maybe it ran out of memory somewhere else.
> 
> -[Unknown]

Maybe 🤔😅

**Comment by Gamemulatorer** [comment]
I found out that clearing cache and rebooting my ancient phone fix the fast memory enable issue but I discover a new issue by using FrameSkipping 1x or more the game is freeze sometimes the whole ppsspp app is freeze.
![Screenshot_2021-10-03-15-21-26](https://user-images.githubusercontent.com/37603562/135744415-345a2f38-5929-4518-ae31-e56e2478228c.png)

**Interesting logs**
```
<<< log_count = 1923 >>>
[10-03 15:20:30.212 6054:7902 W/PPSSPP]
[HLE] sceKernelVolatileMemLock(0, 08dc2e4c, 08dc2e50) - already locked, waiting

[10-03 15:20:30.213 6054:7902 I/PPSSPP]
[HLE] KernelVolatileMemUnlock(0) handed over to another thread

[10-03 15:20:30.219 6054:7902 W/PPSSPP]
[SCEIO] 80010002=sceIoOpen(art/animation/crash_onfoot_animations.p3d, 1, 0): file not found

[10-03 15:20:30.226 6054:7902 I/PPSSPP]
[SCEDISP] !!! Dropping frames - budget = 16.68ms / 59.9fps, actual = 47.97ms (+31.28ms) / 20.8fps
Kernel processing time: 9.50 ms
Slowest syscall: __UtilityFinishDialog : 4.82 ms
Most active syscall: __UtilityFinishDialog : 4.82 ms
DL processing time: 0.04 ms
Draw calls: 0, flushes 0, clears 1 (cached: 0)
Num Tracked Vertex Arrays: 0
Commands per call level: 183 0 0 0
Vertices: 0 cached: 0 uncached: 0
FBOs active: 2 (evaluations: 0)
Textures: 52, dec: 0, invalidated: 0, hashed: 0 kB
Readbacks: 0, uploads: 0
GPU cycles executed: 366 (0.000000 per vertex)
Vertex, Fragment, Programs loaded: 7, 8, 10

[10-03 15:20:30.625 6054:7902 E/PPSSPP]
[ME] 80630006=sceAtracSetDataAndGetID(098865c0, 00014000): invalid RIFF header

[10-03 15:20:30.626 6054:7717 D/libc-netbsd]
[getaddrinfo]: hostname=report.ppsspp.org; servname=80; cache_mode=(null), netid=0; mark=0
```

[logcat_10-03-2021_15-22-37.txt](https://github.com/hrydgard/ppsspp/files/7272900/logcat_10-03-2021_15-22-37.txt)

**Comment by Gamemulatorer** [comment]
Fix by https://github.com/hrydgard/ppsspp/pull/14962/commits/4c0951eb93a0032ccc6f25d940beb05db5a2f2d6
Cause by https://github.com/hrydgard/ppsspp/pull/14856
