### ISSUE TITLE
[PSMF/MPEG] Prince Of Persia Revelation - video playback has no audio.

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#14967]
### Game or games this happens in

ULES00223

### What area of the game / PPSSPP

During the cutscenes in the warrior within chapter there's no audio.

https://user-images.githubusercontent.com/37603562/136047586-019c17a4-633a-4720-9b17-75a996ba8162.mp4

### What should happen

Correct behavior

https://user-images.githubusercontent.com/37603562/136048211-65db4e16-cbd9-420e-bb89-f7bb8629a7e9.mp4

### Platform

Android

### Mobile phone model or graphics card

Redmi Note 9 Android 11

### PPSSPP version affected

v1.11.3-1648-github

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by Gamemulatorer** [comment]
> Does it happen in other cutscenes?

Untested on other scene.

**Comment by unknownbrackets** [comment]
Did you mean to close?

-[Unknown]

**Comment by Gamemulatorer** [comment]
Oops..
I test as of now on other scene still no audio.

https://user-images.githubusercontent.com/37603562/136137691-30e728fe-3764-4ae7-a904-d70dd31016e9.mp4

**Comment by Panderner** [comment]
But how about cutscenes at the start of the game?

**Comment by Gamemulatorer** [comment]
> But how about cutscenes at the start of the game?

Do I need to screen record all the cut-scene to prove to you that there's no audio?

**Comment by sum2012** [comment]
Can test again in newest git version ?

**Comment by Gamemulatorer** [comment]
I will try again later

**Comment by Gamemulatorer** [comment]
Fix now on the latest build 😊

https://user-images.githubusercontent.com/37603562/190185298-a156ac05-bddb-4d16-8cc0-b710997cd566.mp4
