### ISSUE TITLE
Missing letters in MSG peace walker and fps dropped in valkyria chroni 1 

### ISSUE THREAD

**Issue by miss1433** [hrydgard/ppsspp#15006]
### Game or games this happens in

MSG , VALKYRIA CHRONICLES 1[openGL]

### What area of the game

In the tuturial of MSG peace walker, some letters are missing and then pop up a moment later. Its the first time I'm playing this so i don't know if this is a known issue. 

### Speed seen in PPSSPP

60

### GE frame capture and debug statistics

![Screenshot_2021-10-10-11-08-32-682_org ppsspp ppsspp](https://user-images.githubusercontent.com/28482555/136680956-d162721f-f3f6-4e11-b1c7-57fd4e552100.jpg)

### Platform

Android

### Mobile phone model or graphics card

Miui 12 android 11

### PPSSPP version affected

Ver 1.12

### Last working version

1.11

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the slowdown.
- [X] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
A frame dump would be helpful:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

Maybe this is an issue with the internal font, though?

-[Unknown]

**Comment by miss1433** [comment]
I have this flash 0 file folder . I'll delete it and see what may happened

**Comment by miss1433** [comment]
> A frame dump would be helpful: https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump
> 
> Maybe this is an issue with the internal font, though?
> 
> -[Unknown]

I have this flash 0 file folder . I'll delete it and see what may happened

**Comment by Gamemulatorer** [comment]
Cannot reproduce this
![Screenshot_2021-10-10-12-26-28-102_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/136682072-3cf68fc6-257f-488f-a01e-27e8304e73a2.jpg)
