### ISSUE TITLE
List of games with graphics rendering issues using mali gpu with vulkan backend

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#15016]
### What should happen

Some games have graphics glitch on mali-gpu using **vulkan** backend but I found a workaround to fix them.

Map Graphics Issue Affected Games Using **Vulkan** Only.
Midnight Club L.A Remix
![Screenshot_2021-10-14-08-49-18-082_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/137234149-6d2960cd-0d1c-470c-a450-c8af7303e3d6.jpg)

Midnight Club 3 Dub Edition
![Screenshot_2021-10-14-08-48-14-272_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/137234188-1d19ec0c-1775-4fdb-8e4e-eda4dcb3aa96.jpg)

Gensou Suikoden
![IMG_20211014_091325](https://user-images.githubusercontent.com/37603562/137234237-81f2a1b4-1e97-47c7-a43e-40ef98747e70.jpg)

Surf's Up™
![Screenshot_2021-10-14-08-44-21-508_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/137234262-f15dafae-8e0d-4ab4-a0bb-da6265f8b3b5.jpg)

**The Simpsons Game** Also Have Graphics Glitch Using Vulkan.
![Screenshot_2021-10-14-08-38-56-700_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/137234423-975db19f-fd4f-4c86-9e4d-1e031cc8b0d0.jpg)

***WorkAround*** I found to help those games is by adding them to compat.ini **PixelDepthRounding**
Midnight Club L.A Remix
![Screenshot_2021-10-14-08-48-53-196_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/137234820-37949ce2-d476-477d-9356-899e0d8a37b0.jpg)

Midnight Club 3 Dub Edition
![Screenshot_2021-10-14-08-46-08-214_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/137234850-e9f53d0d-38f7-4fb7-af90-f9d7ed1cf433.jpg)

Gensou Suikoden
![IMG_20211014_091402](https://user-images.githubusercontent.com/37603562/137234872-3b2063ed-8a7a-40f9-b2d7-c9b12d041a48.jpg)

Surf's Up™
![Screenshot_2021-10-14-08-43-53-882_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/137234881-e5b089ec-6dcb-4685-b169-bf916f515175.jpg)

The Simpsons Game
![Screenshot_2021-10-14-08-39-23-520_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/137234952-d03fbe42-23a2-4ccd-955e-47b67f0fa251.jpg)

Silent Hill Shattered Memories also have problem using vulkan the flashlight doesn't shine the road.

![Screenshot_2021-10-11-05-21-36-260_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/136713363-a18283d7-a481-4e9e-8b04-298e960cf7e8.jpg)

Workaround is to add this game to **ReinterpretFramebuffers** fix the flashlight
![Screenshot_2021-10-11-05-20-44-424_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/136713357-f4f687a9-1127-48d8-93a5-54e01f4cbb73.jpg)

### Who would this benefit

**All android phones with mali gpu** (vulkan supported only)

### Platform (if relevant)

Android

### Games this would be useful in

NPJH50535

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by ANR2ME** [comment]
Are PixelDepthRounding and ReinterpretFramebuffers supposed to affects Vulkan only? or will it cause issue on other Renderer?
Because if the Mali bugs exist on Vulkan only.. may be you shouldn't choose Vulkan on these buggy GPU?

**Comment by Gamemulatorer** [comment]
> Are PixelDepthRounding and ReinterpretFramebuffers supposed to affects Vulkan only? or will it cause issue on other Renderer or Non-Mali?

I don't know other gpu if affected by this issue.

> Because if the Mali bugs exist on Vulkan only.. may be you shouldn't choose Vulkan on these buggy GPU?

Vulkan perform better on my phone :)

> But it's nice to know what's fixed them :) so may be the devs can make a better workaround specific for these GPU

Yes I hope hrydgard and unknown find a proper fix so that I don't need to use those workaround.

**Comment by Gamemulatorer** [comment]
Peter Jackson KingKong also having flickering issue but fix by adding this game to PixelDepthRounding.

PixelDepthRounding **OFF**

https://user-images.githubusercontent.com/37603562/137424252-a6698c58-f9a1-4c3c-ac7f-d86b26fdd7cd.mp4

PixelDepthRounding **ON**

https://user-images.githubusercontent.com/37603562/137424322-5a08b8c4-478b-4aee-85ce-999b9f3f7149.mp4

[kingkong.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/7350539/kingkong.ppdmp.zip)

**Comment by ANR2ME** [comment]
That flickering on the terrain textures looks like z-fighting, it's common to happen even on PC games

**Comment by Gamemulatorer** [comment]
The most broken graphics on mali-gpu vulkan is The Simpsons Game but fixes by using **PixelDepthRounding**

**opengl**
![Screenshot_2021-10-17-13-49-33-155_org ppsspp ppssppgold](https://user-images.githubusercontent.com/37603562/137613666-59601f16-c731-4f54-9444-19dacea4554b.jpg)

**vulkan**
![Screenshot_2021-10-17-13-48-58-029_org ppsspp ppssppgold](https://user-images.githubusercontent.com/37603562/137613671-44c7f46f-878c-4b4d-ac85-7468f7363e09.jpg)

**vulkan with pixeldepthrounding enable**
![Screenshot_2021-10-17-13-50-26-533_org ppsspp ppssppgold](https://user-images.githubusercontent.com/37603562/137613693-1dd813f3-9d53-48a7-b8ad-69e8c1d18443.jpg)

**Comment by Gamemulatorer** [comment]
New discover game that glitch using vulkan

MegaMind Blue Depender minimize glitch using PixelDepthRounding
https://github.com/hrydgard/ppsspp/issues/13846

Worms Open Warfare 1 and 2 background glitch using vulkan can be fixed by DisableAccurateDepth
https://github.com/hrydgard/ppsspp/issues/12380

**Comment by Gamemulatorer** [comment]
MotorStorm Artic Edge overlay graphic glitches.

https://user-images.githubusercontent.com/37603562/163578345-f9e2e51b-6b05-4883-9755-e1da5c88362b.mp4

Can be work around via DisableAccurateDepth.

**Comment by Gamemulatorer** [comment]
The new compat.ini MaliDepthStencilBugWorkaround fixes the Simpsons Game and Suikoden: Woven Web of The Centuries but didn't fix Magical Girl Lyrical Nanoha and Surf Up :(

**Comment by Gamemulatorer** [comment]
I cannot test ***Megamind*** and ***BadAss Rumble*** because I don't have those games anymore.

**Comment by hrydgard** [comment]
Alright, I managed to improve the workaround it to make it work with Surf's Up too.

**Comment by Gamemulatorer** [comment]
> @Gamemulatorer Can you check if it works with Suikoden and Magical Girl Lyrical Nanoha too, and if so, make me some compat.ini entries? Don't have frame dumps of those.

Yes it also fixes magical girl thank you so much 🎉

**Comment by hrydgard** [comment]
Thanks!

I'm taking this one off the 1.13 milestone now then.

**Comment by hrydgard** [comment]
Hm, but does it? When I tried the flashlight was still pretty bad. Though, I might have tried the other Silent Hill game.

Either way those games need a lot more work, which I do plan to do.

**Comment by Gamemulatorer** [comment]
> Hm, but does it? When I tried the flashlight was still pretty bad. Though, I might have tried the other Silent Hill game.

Yes it's fixes the flashlight issue atleast on my phone.

**Comment by Gamemulatorer** [comment]
All of the games I mentioned here is now finally fixed so closing this..
