### ISSUE TITLE
MPO+ Japan "functions" disassembly tab does not list __sceUtilitySaveDatainitStart

### ISSUE THREAD

**Issue by xor32dotcom** [hrydgard/ppsspp#15019]
### What should happen

There should be a search box that allows the user to search for a specific module whenever it is not listed on the functions tab.

In this case **the emulator does know where to find __sceUtilitySaveDatainitStart**, however it doesnt not list it for some strange reason.

ps. of course im referring to the stub which looks like this

jr ra
syscall sceFunctionGoesHere

### Who would this benefit

Anyone who happens to be looking for a specific module "stub"

### Platform (if relevant)

Windows

### Games this would be useful in

ULJM-05261

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by ANR2ME** [comment]
Hmm.. i didn't know we can remove a syscall function O.o 
What's the purpose or effect of removing the function when the game tries to call it? will a crash occurred?

**Comment by unknownbrackets** [comment]
Normally, zz_sceUtilitySavedataInitStart is what would show up.  You can type this in the left panel, and it will scroll as you type - as this Windows control normally does.  But there's currently no filtering.

If you use the web debugger, it does indeed have a filter:
http://ppsspp-debugger.unknownbrackets.org/

Is there a particular game you're seeing a missing func in?  Is it always the last one?  I don't think I've ever reproduced this, and I use the functions list quite often.  If I can reproduce, I imagine it'd be relatively straight-forward to fix.

-[Unknown]

**Comment by ANR2ME** [comment]
does the function list have a limit on the number of functions? may be that game have too many functions exceeding the limit

**Comment by unknownbrackets** [comment]
I wonder if this was #15265.  Are you still seeing this in the latest git builds?

-[Unknown]

**Comment by GabrielReyes136** [comment]
> I wonder if this was #15265. Are you still seeing this in the latest git builds?
> 
> -[Unknown]

It's a hit and miss it seems.

i typed it manually and i found it on the display list. rebooted the emulator, and then it failed to find it until I removed a function label which mysteriously refreshes the list and adds the missing functions
