### ISSUE TITLE
Unable to enter shift key for some games

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#15010]
### What happens?
In All Kamen Rider: Rider Generation 2 the final option is listed in title screen and select enter password button. and there is no select button to shift keys 
![Screenshot (46)](https://user-images.githubusercontent.com/37503397/136740263-8bfbd252-b19e-4d9d-949a-222d99a8d6fc.png)
Captital letters are required in order to unlock Kamen Rider Wizard in All Kamen Rider: Rider Generation 2.

### What *should* happen?
In other games like Monster Hunter has select button to shift keys.
![Screenshot (45)](https://user-images.githubusercontent.com/37503397/136740354-a12a6d19-4a21-442d-ace6-4a7c1c6ccc72.png)

#### What hardware / device and operating system?
Windows 10 Pro

#### What graphics card (GPU) or mobile phone model?
NVIDIA GeForce GTX 1050Ti

#### What PPSSPP version (standalone/official), and did it work before?
V1.12.2

#### Which game or games?
NPJH50617 - All Kamen Rider: Rider Generation 2

#### Checklist

 - [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [ ] Try resetting settings or older versions and include if the issue is related.
 - [ ] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
Games can specify what keys should be allowed, and we intend to limit the same way a real PSP would.  We must be getting it wrong here, if it's supposed to only show uppercase characters for example...

There's no demo or anything that shows this behavior, right?  I'd really want to see what the inputtype is, and if any of the other values in the struct are set...

-[Unknown]

**Comment by unknownbrackets** [comment]
Can you try the test build here?  This will write the parameters for the OSK to the log.  That's what I'm after:

https://github.com/unknownbrackets/ppsspp/actions/runs/1350677194

Please paste (ideally) the log lines starting with "OSK params:" or "OSK fields:" here, or screenshot them.

-[Unknown]

**Comment by Panderner** [comment]
Here's a log for OSK using unknownbrackets's artifact build:
```
50:48:263 user_main    I[SCEUTIL]: Dialog\PSPOskDialog.cpp:332 OSK params: sz=64, fields=1, state=0, unk=00000000
50:48:263 user_main    I[SCEUTIL]: Dialog\PSPOskDialog.cpp:333 OSK fields: unk00=00000000, unk04=00000000, lang=0, unk_12=00000000
50:48:263 user_main    I[SCEUTIL]: Dialog\PSPOskDialog.cpp:334 OSK fields: type=4, lines=1, unk_24=00000001, outlen=18/0
50:48:265 user_main    I[SCEUTIL]: HLE\sceUtility.cpp:594 00000000=sceUtilityOskInitStart(09d05df0)
```

and Here's a screenshot using a same build above:
![Screenshot (47)](https://user-images.githubusercontent.com/37503397/141690369-ebf640b6-c665-44bd-977a-142cdd460b63.png)

**Comment by unknownbrackets** [comment]
So, inputtype is indeed PSP_UTILITY_OSK_INPUTTYPE_LATIN_LOWERCASE.  However, an unexpected field unk_24 is 1.

It's possible this field could mean to allow uppercase or force uppercase in some way.

-[Unknown]

**Comment by unknownbrackets** [comment]
I'm having trouble testing the unk_24 field - it just locks up my PSP because the OSK never comes up, and there's no way to exit.  Have to hard reset.  Maybe it's a flag to hide the OSK display or something, but it's annoying to test with hard resets...

-[Unknown]

**Comment by hrydgard** [comment]
This should be better now with #15698.

**Comment by Panderner** [comment]
Now it worked.
![Screenshot (58)](https://user-images.githubusercontent.com/37503397/179407380-f3cf0fd7-68ea-4fa4-8ff1-79890a7ca85c.png)
