### ISSUE TITLE
[Regression!][Android] SplinterCell hang/freeze at the end of mission one. 

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#15020]
### Game or games this happens in

ULUS10070

### What area of the game / PPSSPP

At the end of mission 1 after pressing X the game is freeze/hang cannot continue using ppsspp v1.12.2-9

https://user-images.githubusercontent.com/37603562/137416594-c50af22b-2f80-4593-bb87-909073ac4a9c.mp4

### What should happen

The game should play cutscene and proceed to mission 2 using ppsspp v1.11.3

https://user-images.githubusercontent.com/37603562/137416773-a2714523-b650-4101-a6ab-22f727edbb51.mp4

### Logs

[splinter cell.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/7350187/splinter.cell.ppdmp.zip)

### Platform

Android

### Mobile phone model or graphics card

RN9 Android11 Helio G85 Mali-G52 GPU

### PPSSPP version affected

v1.12.2-9

### Last working version

v1.11.3

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment]
You will also need to get the logs

**Comment by Gamemulatorer** [comment]
![Screenshot_2021-10-16-19-35-34-547_com android chrome](https://user-images.githubusercontent.com/37603562/137585824-c3e99ab7-9ee8-458b-b369-f72e30d7245f.jpg)

**Comment by Gamemulatorer** [comment]
I think I'm wrong this game really doesn't work in v1.11.3 😅
Closing as duplicate of https://github.com/hrydgard/ppsspp/issues/13055
