### ISSUE TITLE
What happen to combo keys? The feature gone now

### ISSUE THREAD

**Issue by th0rig** [hrydgard/ppsspp#15033]
### What should happen

Combo keys  feature  shouldn't be removed because that feature useful for games that requires multiple inputs at same times if you play with Touchscreen please bring back that feature

### Who would this benefit

This feature will benefit touchscreen users

### Platform (if relevant)

Android

### Games this would be useful in

Games that requires multiple inputs at some point during gameplay

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by unknownbrackets** [comment]
From the README of changes in v1.12.x:

> Improved combo button and moved settings to Customize Touch Control -> Customize -> Custom button (#13869)

-[Unknown]
