### ISSUE TITLE
Texture glitch in persona 3 (vertex cache)

### ISSUE THREAD

**Issue by KaiFujiro** [hrydgard/ppsspp#15032]
### Game or games this happens in

ULUS-10512 - Persona  3 Portable (UNDUB)

### What area of the game / PPSSPP

When I was in tartarus Tziah 147F

https://user-images.githubusercontent.com/71515107/137906226-587319e4-de04-4be7-944d-a48499fbd4b3.mp4

### What should happen

the texture should be normal and there should be no glitch there

### Logs

[log.txt](https://github.com/hrydgard/ppsspp/files/7373043/log.txt)

### Platform

Android

### Mobile phone model or graphics card

J1 Ace J111F (Android 5.1.1)

### PPSSPP version affected

v1.12.3-39-g16bf5197e

### Last working version

v1.12.2-11-g7ba8ef3d3 

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by Gamemulatorer** [comment]
Unfortunately that save state doesn't work on me 🤔

**Comment by KaiFujiro** [comment]
> Unfortunately that save state doesn't work on me 🤔

because you need the same save data as the save state

**Comment by Gamemulatorer** [comment]
> > > Unfortunately that save state doesn't work on me 🤔
> > 
> > 
> > because you need the same save data as the save state
> 
> or you can download save data from the internet and go to Tziah 147F with the save data you downloaded

I already have save data but when I load your save state it just return to start of the game.
do you have any cheats enable when you save that save state?

**Comment by KaiFujiro** [comment]
> > > > Unfortunately that save state doesn't work on me 🤔
> > > 
> > > 
> > > because you need the same save data as the save state
> > 
> > 
> > or you can download save data from the internet and go to Tziah 147F with the save data you downloaded
> 
> I already have save data but when I load your save state it just return to start of the game. do you have any cheats enable when you save that save state?

I didn't use the cheat when the save state was created

**Comment by KaiFujiro** [comment]
or you can go to a different floor and use alice, then use the skill "Di3 for Me!", see if it works or not to see the glitch

**Comment by KaiFujiro** [comment]
error when uploading to github, so I uploaded this to google drive

https://drive.google.com/file/d/1gAxTBa_wS6_ttBc_nANrZPsSvtbkrFEc/view?usp=drivesdk

**Comment by KaiFujiro** [comment]
Here: 

https://drive.google.com/file/d/1ghfpYRoyQ3VqGtx72DifEzlTnCIOOONi/view?usp=drivesdk

**Comment by Gamemulatorer** [comment]
> Here:
> 
> https://drive.google.com/file/d/1ghfpYRoyQ3VqGtx72DifEzlTnCIOOONi/view?usp=drivesdk

Your ge dump capturing the wrong scence.
![Screenshot_2021-10-20-17-00-35-955_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/138062813-cab4915a-6bcd-41ab-82a1-075d2f27d4d9.jpg)

This is the right scence you need to capture using ge dump.
![Screenshot_2021-10-20-17-01-26-296_com android chrome](https://user-images.githubusercontent.com/37603562/138063028-27e78419-90db-4dae-8889-738f38eeca77.jpg)

**Comment by KaiFujiro** [comment]
> > Is it like this?
> > [ULUS10512_0001.zip](https://github.com/hrydgard/ppsspp/files/7379891/ULUS10512_0001.zip)
> 
> Here's the result opengl ![Screenshot_2021-10-20-17-33-32-531_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/138068248-7474d534-3f5c-41dd-9c86-0be8b39c688c.jpg)

how can it be like that, I'm sure that at that time the texture had a glitch

**Comment by KaiFujiro** [comment]
> KaiFujiro Can you share your save data on this game?

Yeah, sure

[ULUS10512DATA00.zip](https://github.com/hrydgard/ppsspp/files/7380092/ULUS10512DATA00.zip)

**Comment by KaiFujiro** [comment]
> > > > Is it like this?
> > > > [ULUS10512_0001.zip](https://github.com/hrydgard/ppsspp/files/7379891/ULUS10512_0001.zip)
> > > 
> > > 
> > > Here's the result opengl ![Screenshot_2021-10-20-17-33-32-531_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/138068248-7474d534-3f5c-41dd-9c86-0be8b39c688c.jpg)
> > 
> > 
> > how can it be like that, I'm sure that at that time the texture had a glitch
> 
> Because my redmi note 9 is using opengl 3.2 that's why there's no glitch.
> 
> Here's the result using my **mali-450** gpu phone. ![Screenshot_2021-10-20-17-55-01](https://user-images.githubusercontent.com/37603562/138072092-24ff9e9d-5505-415e-af48-f51a501a366c.png)

ah like that

**Comment by KaiFujiro** [comment]
just waiting for hrydgard/unknown to make it

**Comment by Gamemulatorer** [comment]
> Does the Vertex Cache setting affect the way it glitches?

Yes vertex cache can cause this issue.
Here's the screenshot without vertex cache on my mali-450 gpu.
![Screenshot_2021-10-20-19-29-15](https://user-images.githubusercontent.com/37603562/138084878-49b52749-d1ec-47f2-8a42-04bce9ba6e64.png)

**Comment by unknownbrackets** [comment]
I seem to recall there was some worry that the way we were uploading into the GL vertex cache might be unsafe, although was probably fine.  It's been forced off until now.

-[Unknown]

**Comment by hrydgard** [comment]
I removed the vertex cache again in OpenGL, so this should no longer be an issue.

**Comment by Gamemulatorer** [comment]
> I removed the vertex cache again in OpenGL, so this should no longer be an issue.

This glitch can only reproduce in opengl 2.0 might be good to restore this in opengl 3.0+? ヽ⁠(⁠｡⁠◕⁠o⁠◕⁠｡⁠)⁠ﾉ⁠.
