### ISSUE TITLE
Cannot build libretro ppsspp for arm64

### ISSUE THREAD

**Issue by asdone7** [hrydgard/ppsspp#15046]
### Platform

libretro / Retroarch

### Compiler and build tool versions

gcc 9.3.0+cmake 3.16.3

### Operating system version

ubuntu20.04

### Build commands used

PROJECT=Amlogic-ng ARCH=aarch64 DISTRO=EmuELEC make image

### What happens

Who can help me solve this problem? Thank you!
The error message :
[504/761] Building CXX object CMakeFiles/Core.dir/Core/PSPLoaders.cpp.o
../Core/PSPLoaders.cpp: In function 'void InitMemoryForGamePBP(FileLoader*)':
../Core/PSPLoaders.cpp:190:10: warning: unused variable 'updateTitle' [-Wunused-variable]
     bool updateTitle = false;
          ^~~~~~~~~~~
At global scope:
cc1plus: warning: unrecognized command line option '-Wno-tautological-pointer-compare'
cc1plus: warning: unrecognized command line option '-Wno-deprecated-register'
[505/761] Building CXX object CMakeFiles/Core.dir/Core/MIPS/MIPSTables.cpp.o
ninja: build stopped: subcommand failed.
FAILURE: scripts/install ppsspp has failed!
[393/486] [FAIL] install ppsspp

The following logs for this failure are available:
  stdout: /home/pp/Downloads/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4.3/.threads/logs/369/stdout
  stderr: /home/pp/Downloads/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4.3/.threads/logs/369/stderr

### PPSSPP version affected

7d94f3777edf97de676a126d81281bfa8fa0c44a

### Last working version

9de9420878df6805a1db40ede7bd264499cb1425

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] Make sure to run `git submodule update --init --recursive` before building.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try deleting the build directory and running the build again.
- [X] Check GitHub Actions, which builds every merge and PR.
- [ ] Include logs and help us reproduce.

**Comment by gouchi** [comment]
I don't recall we have issue building for aarch64 using [v1.12.3](https://github.com/hrydgard/ppsspp/releases/tag/v1.12.3). FWIW the [recipe](https://github.com/libretro/Lakka-LibreELEC/blob/master/packages/libretro/ppsspp/package.mk)  we are using to build libretro ppsspp.

This is issue should be renamed something like  `Cross compiling issue building libretro ppsspp for arm64`.
