### ISSUE TITLE
Toca Race Driver 2 (Guardband glitch again)

### ISSUE THREAD

**Issue by MiguelCardonaG** [hrydgard/ppsspp#15049]
### Game or games this happens in

ULES-00040 - Toca Race Driver 2

### What area of the game / PPSSPP

When starting a race.

![PPSSPP_2021-10-23-13-23-13](https://user-images.githubusercontent.com/65356692/138554636-aec754bf-884e-4d5e-a894-b75fb62a5a4f.jpg)

https://github.com/hrydgard/ppsspp/issues/11999

### What should happen

In version 68 there is no on-screen error.

### Platform

Android

### Mobile phone model or graphics card

Samsung Galaxy Note 10 plus exynos

### PPSSPP version affected

ppsspp-v1.12.3-74-g7d94f3777-android.apk

### Last working version

ppsspp-v1.12.3-68-g4bd4cde4a-android.apk

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by ThePhoenixRises** [comment]
Hi Developers,
Seems this games banding problem is back from 1.14.04 
![photo_2022-12-18_19-48-41](https://user-images.githubusercontent.com/6565304/208348687-1920f511-52ed-43a4-b5f5-2cdd1fd26a19.jpg)
But is the only one i have come across.

**Comment by unknownbrackets** [comment]
Are you sure you're using v1.14.0?  Is this with software transform on or off?  Does it change anything?

You said it did and did not happen on Vulkan, maybe you meant it doesn't happen on Windows + Vulkan.

-[Unknown]

**Comment by ThePhoenixRises** [comment]
No sorry Unknown, i meant this seems to be only a problem on Android, using that version 1.14.0.

**Comment by Gamemulatorer** [comment]
> No sorry Unknown, i meant this seems to be only a problem on Android, using that version 1.14.0.

Did you enable geometry culling in graphics setting?

**Comment by hrydgard** [comment]
Geometry-shader culling should not be needed for this issue, the vertes-shader based range culling should be enough.

**Comment by Gamemulatorer** [comment]
ok

**Comment by ThePhoenixRises** [comment]
Hi sorry i was a busy, but no culling on, just trying 1.14.1-8 to see if any change.
Nope no lucky, same problem guys, banding is still there.

**Comment by Gamemulatorer** [comment]
I guess this issue should be reopened?

**Comment by Gamemulatorer** [comment]
I cannot reproduce this issue in my vivo y11 vulkan backend and I also notice that this game performance is decrease.
![Screenshot_20221222_124730_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37603562/209061401-34775c05-a400-44bf-b836-8e81f488e538.jpg)

**Comment by MiguelCardonaG** [comment]
Yes, I confirm that it fails again.

![Screenshot_20221222-111347_PPSSPP](https://user-images.githubusercontent.com/65356692/209112080-d49aad40-18c4-4986-a106-fa6735fdfdb8.jpg)

![Screenshot_20221222-111219_PPSSPP](https://user-images.githubusercontent.com/65356692/209112129-f93c3803-fe38-44e7-bc26-d9007bbf2629.jpg)

![Screenshot_20221222-111343_PPSSPP](https://user-images.githubusercontent.com/65356692/209112199-af399e9f-297e-4835-991c-64ae414f1782.jpg)

Samsung Galaxy Note 10 plus exynos. Android 12. ppsspp-v1.14.1-9-gf65a8aa74-android

**Comment by hrydgard** [comment]
I will look into this.

**Comment by Gamemulatorer** [comment]
Safe to tag as MALI GPU issue only?

**Comment by hrydgard** [comment]
I believe what's happening is that we now prefer the geometry shader path to fix this on Mali, but if that's turned off, we just don't do anything, instead of using the vertex shader method. Should be easy to fix.

**Comment by Gamemulatorer** [comment]
> I cannot reproduce this issue in my vivo y11 vulkan backend and I also notice that this game performance is decrease. ![Screenshot_20221222_124730_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37603562/209061401-34775c05-a400-44bf-b836-8e81f488e538.jpg)

About the performance skip gpu readbacks should be on.

**Comment by ThePhoenixRises** [comment]
Thanks guys, this now runs perfect again, using Android 11 on my Retroid Pocket 3+ with its annoying Mali GPU, but somehow runs this game at 2 x texture upscaled, plus 2 x hardware scaled, and plays at a solid 40 fps.
Fantastic emulator, on this awesome handheld, for its price.
![Toca Race Driver 2](https://user-images.githubusercontent.com/6565304/209269166-47458580-f0b3-47af-96db-f64eb711b3a5.jpg)

**Comment by Duglor** [comment]
This is occuring in the latest version of PPSSPP for Toca Racer 2 and 3 for the RetroPie 4.X.   Is there a setting in the lr-ppsspp or the standalone ppsspp that should be changed to fix this guardband glitch?

**Comment by hrydgard** [comment]
Did you turn on the speedhack "Disable culling"?

**Comment by Duglor** [comment]
> Did you turn on the speedhack "Disable culling"?

Yes

**Comment by hrydgard** [comment]
Well then turn it off. It's not compatible with this game

**Comment by Duglor** [comment]
Oh, sorry.lol. It is off.  That's what I meant, This is for lr-ppsspp
