### ISSUE TITLE
libretro core graphical glitches with OpenGL driver

### ISSUE THREAD

**Issue by ner00** [hrydgard/ppsspp#15056]
### Game or games this happens in

ULUS-10277 - Castlevania - The Dracula X Chronicles
ULES-00910 - SEGA Rally
ULUS-10246 - Virtua Tennis 3

### What area of the game / PPSSPP

Just in-game, generally, when using gl or glcore drivers - D3D11 works fine.

A few screenshots demonstrating the issue:

![ULES-00910 - SEGA Rally](https://i.imgur.com/n8PDVJD.png)

![ULUS-10246 - Virtua Tennis 3](https://i.imgur.com/V3IdGOK.png)

![ULUS-10277 - Castlevania - The Dracula X Chronicles](https://i.imgur.com/ShQI7x7.png)

![ULUS-10277 - Castlevania - The Dracula X Chronicles](https://i.imgur.com/RzMzipU.png)

![ULUS-10277 - Castlevania - The Dracula X Chronicles](https://i.imgur.com/B1Chdr2.png)

### What should happen

Not have graphical glitches or crash.

### Platform

libretro / Retroarch

### Mobile phone model or graphics card

Intel UHD Graphics 630

### PPSSPP version affected

v1.13.3-80-g59f3d4b

### Last working version

74f08be

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [x] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
#15109 improved texture scaling on Mali, is it possible it fixed this issue too?

It seems like there haven't been many reports of issues like this recently.

-[Unknown]

**Comment by unknownbrackets** [comment]
There haven't been any new reports of the OpenGL crash or any comments since my last comment, so I'm going to close this.  The primary issue was definitely fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
