### ISSUE TITLE
[Software Rasterizer] Frame-skipping doesn't work in some games can cause freeze/hang. 

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#15062]
### Game or games this happens in

ULJM05404

### What area of the game

At the fight scene.

### What happens

I try software rendering to Hokuto no Ken Raoh Gaiden
but using frame skipping x1 freeze the game.

https://user-images.githubusercontent.com/37603562/138047489-5b7da6fd-118b-446c-84e3-7c50545bb769.mp4

### What should happen

No freeze like in Vampire Chronicles.

### GE frame capture

[software.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/7379042/software.ppdmp.zip)

### Platform

Android

### Mobile phone model or graphics card

RN9 Android11 Helio G85 Mali-G52 GPU

### PPSSPP version affected

v1.12.3-100

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
Has this gotten better?  I don't think I've made any changes yet that would fix this.

I think it's down to misdetecting when it's actually modified the framebuffer...

-[Unknown]

**Comment by Gamemulatorer** [comment]
No, frameskipping still doesn't work with this game using software rendering. But only on this game.

**Comment by Gamemulatorer** [comment]
The latest build have this issue using software mode.
![Screenshot_2022-01-16-14-54-03-848_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/149650425-4dde7af1-f0d0-4926-8128-af2b2347c165.jpg)

**Comment by unknownbrackets** [comment]
Thanks, that should be fixed in fc292b127 / #15311.

-[Unknown]

**Comment by Gamemulatorer** [comment]
This is normal?
![Screenshot_2022-01-20-17-18-04-825_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/150309832-278c8321-346a-4f01-b51b-1477894cc447.jpg)
![Screenshot_2022-01-20-17-18-19-957_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/150309840-63fd4e84-541f-437a-9780-8a6620d807dc.jpg)
**Software Skinning OFF**

But Vampire Chronicles doesn't behave if I turn off sw skinning.

**Comment by Gamemulatorer** [comment]
Nice improvement on the software rendering mode unknownbrackets 👍
Before I only got 15-20 fps on this game but now I got 40-50fps during fighting scene.
![Screenshot_2022-01-24-18-13-45-415_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/150764659-3247415a-d138-485c-a2d2-8e2d514ac9ee.jpg)

Also about the characters invisible issue if I turn off software skinning is also fix.

**Comment by Gamemulatorer** [comment]
I also notice if I don't use auto frameskipping the game is freezing but if I enable it the game is not freezing but running like this.

https://user-images.githubusercontent.com/37603562/150765284-89871be9-77b7-4b65-97c8-440ee56730e0.mp4

**Comment by unknownbrackets** [comment]
Fixed by #15400.

-[Unknown]
