### ISSUE TITLE
MotorStorm®: Artic Edge black box in logo

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#15063]
### Game or games this happens in

UCES01250

### What area of the game

At the loading screen before the racing.

![black box logo](https://user-images.githubusercontent.com/37603562/139178788-2eed1717-6da2-4399-96fa-2921c5cdb171.gif)

### What happens

Black box behind logo.

### What should happen

No black box like in real psp
https://youtu.be/wJrDTPAYqAs

### GE frame capture

[recording.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/7430743/recording.ppdmp.zip)

### Platform

Android

### Mobile phone model or graphics card

Redmi Note 9 Android 11 Helio G85 Mali-G52 GPU

### PPSSPP version affected

v1.12.3-100

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
If this doesn't happen with default settings (i.e. simulate block transfer on), then I would say it's not a bug.  It seems silly that the game is using block transfers for this effect, of course, but that's really a criticism on how the game was built by its developers.

I'm not really a huge fan of haphazardly enabling game-specific hacks, but I'd recommend testing all the different areas and tracks with and without that setting (at least different types of tracks, weather, etc.)  It may just as easily cause an issue like a black box around something, if the developers chose to do something similarly silly.  To me, that the developers would use a block transfer for this animation at all already makes me question how safe BlockTransferAllowCreateFB would be with their style of coding.

-[Unknown]

**Comment by Gamemulatorer** [comment]
> If this doesn't happen with default settings (i.e. simulate block transfer on), then I would say it's not a bug. It seems silly that the game is using block transfers for this effect, of course, but that's really a criticism on how the game was built by its developers.

Simulate Block Transfer Effects makes this game super lag both ogl and vk :(

**Comment by Gamemulatorer** [comment]
Closing in favor of #15136
