### ISSUE TITLE
iOS jailbreak version crash

### ISSUE THREAD

**Issue by rllbe** [hrydgard/ppsspp#15074]
Hello I found that the latest iOS jailbreak version of PPSSPP(version 0v1.6.3-456-g6d0ed4ad0) crashes on launch, both on my iPhone 12 iOS 14.2.7 and iPhone 7 iOS 14.3

https://github.com/hrydgard/ppsspp/blob/16bf5197e4accf36f4e198a2b099985c0bbb3929/Common/GPU/OpenGL/GLFeatures.cpp#L142
https://github.com/hrydgard/ppsspp/blob/16bf5197e4accf36f4e198a2b099985c0bbb3929/Common/GPU/OpenGL/GLFeatures.cpp#L276
`versionStr` would be NULL after this line and `strstr` with this variable below would cause the crash

**Comment by rllbe** [comment]
Just found that it's not the latest version. Install version from https://p.xx.wtf/ fixes it for me

**Comment by Gamemulatorer** [comment]
Yeah v1.6.3 is ancient as hrydgard comment here https://github.com/hrydgard/ppsspp/issues/14760#issuecomment-904447877

**Comment by rllbe** [comment]
> Yeah v1.6.3 is ancient as hrydgard comment here [#14760 (comment)](https://github.com/hrydgard/ppsspp/issues/14760#issuecomment-904447877)

Wonder why they don't update the official jailbreak repo. Been using it since ~6 years ago and just learned that it became ancient
