### ISSUE TITLE
SOCOM U.S. Navy SEALs: Tactical Strike  NVG not work in the night all always Black screen

### ISSUE THREAD

**Issue by DDJock** [hrydgard/ppsspp#15071]
### Game or games this happens in

UCUS98649 ：SOCOM U.S. Navy SEALs: Tactical Strike

### What area of the game

I just recently started playing from ver1.10 to ver1.12.3, all can not work. 
OS Win 10
ALL Rendering backend ：not work  

Mission 04 06 09 is a night battle, NVG does not work, always black screen, can not start the mission

### What happens

always black screen Just start mission 04 06 09 like this：
![02](https://user-images.githubusercontent.com/45682743/139584193-3ae9d5cb-44d0-45c2-812f-f1b4ab070c2b.png)

### What should happen

this is Normal：
![51EpXsnQs0L](https://user-images.githubusercontent.com/45682743/139584235-ec617f3e-7597-4637-ac0d-199b98b9f3fb.jpg)
Video ：
https://www.youtube.com/watch?v=rBy14ebYQrg

### Platform

Windows

### Mobile phone model or graphics card

NVIDIA 750TI

### PPSSPP version affected

 1.12.3 -113-ga3a6bdc19

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by Gamemulatorer** [comment]
Related https://github.com/hrydgard/ppsspp/issues/6963#issuecomment-530477890?

**Comment by Gamemulatorer** [comment]
Can you upload ge dump in that issue @DDJock?
See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

**Comment by DDJock** [comment]
I hope I did the ge dump right
[UCUS98649_0001.zip](https://github.com/hrydgard/ppsspp/files/7451221/UCUS98649_0001.zip)

**Comment by Gamemulatorer** [comment]
Can you try the latest git build of ppsspp
https://buildbot.orphis.net/ppsspp/index.php?m=fulllist

Can you also reproduce this in other graphics backend?

**Comment by DDJock** [comment]
I try the lastest ver v1.12.3-140-g7ba8cf63b, still not work, but  Software Rendering is work  ,FPS too slow.
Software Rendering ge dump:
[Software Rendering UCUS98649_0001.zip](https://github.com/hrydgard/ppsspp/files/7453588/Software.Rendering.UCUS98649_0001.zip)
![SR](https://user-images.githubusercontent.com/45682743/139680264-beefaaec-cafc-4886-baa3-782ba78fc466.png)
Vulkan Rendering  ge dump:
[UCUS98649_0001.zip](https://github.com/hrydgard/ppsspp/files/7453599/UCUS98649_0001.zip)

**Comment by Gamemulatorer** [comment]
Can you upload your save state file?

**Comment by DDJock** [comment]
here .
[M09 save state.zip](https://github.com/hrydgard/ppsspp/files/7453832/M09.save.state.zip)

**Comment by Gamemulatorer** [comment]
I cannot experience the blackscreen issue but loading your save state can cause graphical glitches.

https://user-images.githubusercontent.com/37603562/139687413-10ded5eb-722a-4fdb-b5a8-a7d3a31550c2.mp4

@hrydgard this is similar to https://github.com/hrydgard/ppsspp/issues/11814 workaround DisableFirstFrameReadback

**DisableFirstFrameReadback** Enable

https://user-images.githubusercontent.com/37603562/139687570-043d3fea-968e-4c85-b4df-d4b5ee5efb0c.mp4

**Comment by DDJock** [comment]
DisableFirstFrameReadback  Where is this setting ？

**Comment by Gamemulatorer** [comment]
> DisableFirstFrameReadback Where is this setting ？

In compat.ini it's hidden.

**Comment by DDJock** [comment]
Thank you very much, I don't have the SEAL 3 screen problem, 
it's just that the Night vision startup doesn't work.

**Comment by Gamemulatorer** [comment]
Another issue is about the light depth/z related?
[light_overlay.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/7461492/light_overlay.ppdmp.zip)
![Screenshot_2021-11-02-22-36-35-346_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/139868931-1d71c604-94c6-4977-8e83-cd120fa9f74c.jpg)

**Comment by unknownbrackets** [comment]
Does the software renderer look / run better now?  It may still be slow, I'm wondering more if it's as grainy or if it should be that grainy.

It seems like there's some CPU upload happening in the frame dump.

-[Unknown]

**Comment by EternalsDarkhole** [comment]
@DDJock no feedback?

**Comment by Raymondic** [comment]
Press the 🔽 button on your emulator screen as soon as you see the black screen and every time you go into camera zoom and sniper mode press it again to return to normal night view.

**Comment by Gamemulatorer** [comment]
This game require ***Simulate Block Transfer Effects*** to make night vision work but sadly introduce new issue :(

***Simulate Block Transfer Effects OFF***

https://user-images.githubusercontent.com/37603562/195418245-356bf2c7-d986-4aba-b45e-e6bb31620cbd.mp4

***Simulate Block Transfer Effects ON***

https://user-images.githubusercontent.com/37603562/195418329-49f0e149-0b11-43cf-aa4b-ed2b4d61dee0.mp4

**Comment by hrydgard** [comment]
Hm, we might be able to improve this with the fix for #16210 , that is, #17297 .

**Comment by hrydgard** [comment]
Trying DDJock's dump above ([UCUS98649_0001.zip](https://github.com/hrydgard/ppsspp/files/7451221/UCUS98649_0001.zip)) , the post processing stuff starts at step 31369 (!) with the same CLUT8 trick, however here it doesn't seem to work and turns things black?

More stuff happens afterwards, though, I believe it's a bloom effect.

**Comment by hrydgard** [comment]
By hacking up the depal so we get some brighter stuff, I can tell that the green color is not applied in depal, it's applied after computing the bloom by a simple colored fullscreen draw, using alpha blending (modulate src by dest color, everything else zero), just before then adding the bloom and striped noisy lines on top.

All the bloom and stuff seems to work fine, so the problem is working out why the output of the CLUT8 step is overly dark...

**Comment by hrydgard** [comment]
Alright, I found it, fix coming up.
