### ISSUE TITLE
Backend gets changed to OpenGL inadvertently on Android

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#15079]
Some report it's when restarting the device, but I've seen it when debugging too, where PPSSPP ends up reverting to OpenGL. Likely we don't successfully save the fact that we started successfully with Vulkan.

The stability check is probably not needed anyway anymore, at least from say Android 11, now that Vulkan is at least as stable as OpenGL on Android.

**Comment by Gamemulatorer** [comment]
Yes sometimes I experience this issue 😃

**Comment by unknownbrackets** [comment]
Perhaps related to permissions or scoped storage somehow?  It should just always be saved in a file on internal storage...

Not sure I've seen this, but I switch backends a lot so may not have noticed.  After it happens, is FailedGraphicsBackends set to something other than blank in ppsspp.ini?

-[Unknown]

**Comment by unknownbrackets** [comment]
Should we close this now, or have there been further reports?

-[Unknown]

**Comment by hrydgard** [comment]
This can't happen anymore after #15118, so let's close it.
