### ISSUE TITLE
Balinese for PPSSPP

### ISSUE THREAD

**Issue by PutuDesca** [hrydgard/ppsspp#15114]
Hi, may I add Balinese to PPSSPP, if I may, what should I prepare and do?

Bali = ba_ID

**Comment by hrydgard** [comment]
Absolutely. Just make a new ini file, and to test it and when you submit it, add the Balinese language to assets/langregion.ini, and it will show up in PPSSPP.

**Comment by PutuDesca** [comment]
Okay, I'm working on it now
