### ISSUE TITLE

Cancellation of Balinese translation

### ISSUE THREAD

**Issue by PutuDesca** [hrydgard/ppsspp#15117]
Sorry Henrik, I canceled the Balinese translation for PPSSPP because there was an error

![IMG_20211109_214423.JPG](https://user-images.githubusercontent.com/93461649/140938652-6db4f7ec-ca73-4d6a-a8f3-b542eea5a7bd.JPG)

**Comment by hrydgard** [comment]
Where did you see this error?

**Comment by PutuDesca** [comment]
yup, maybe it doesn't support translation

**Comment by PutuDesca** [comment]
Next time i will try again

**Comment by hrydgard** [comment]
PPSSPP supports adding as many languages as you want. I don't understand what could have possibly gone wrong.

**Comment by PutuDesca** [comment]
It worked but when i use the phone

![IMG_20211110_073136.JPG](https://user-images.githubusercontent.com/93461649/141022480-defeef73-8794-4474-a693-b50d0d1d101f.JPG)

**Comment by PutuDesca** [comment]
Maybe the Balinese language doesn't support to be translated

**Comment by unknownbrackets** [comment]
If you can create a ba_ID.ini that has the new text, it can be translated.  It is supported.

-[Unknown]
