### ISSUE TITLE
When you re-install the app in android, IT will delete some folder such as Cheats, Game, Plugin

### ISSUE THREAD

**Issue by lishaoxia1985** [hrydgard/ppsspp#15113]
When you re-install the app in android, IT will delete some folders such as Cheats, Game, Plugin, in which some dlc/mod/cheatcode need special files placed.
IT is a very bad bug, some days ago it deletes my savedata😥

**Comment by hrydgard** [comment]
I don't think it deletes it? Maybe you chose a different PSP folder that doesn't have the files, they're surely around somewhere?

What exactly did you do setting up the new version?

**Comment by lishaoxia1985** [comment]
This problem occurs recently, in the branch which you add the choice about external storage and inter storage, IT will delete all data. In the later branch, IT seems to delete only cheat and some folder relative with dlc, none deletes savadata.

**Comment by hrydgard** [comment]
What exactly did you do that caused it to delete data? The only case where it deletes files is when you choose to move the contents of your directory, but then again, even when it does that, it confirms that it has successfully written the file to the new location before it deletes the old one.

**Comment by ANR2ME** [comment]
There is also a possibility of corrupted filesystem or damaged SDCard/eMMC if the missing files were inconsistent (ie. sometimes all of them missing and sometimes only some of them missing)

He/She didn't mention his/her device either, so that others who have similar model can try to reproduce it.

**Comment by lishaoxia1985** [comment]
Some minutes ago, I test this.
Sorry, I can't repeat this bug, so I close this issue.
I always pursue the latest branch, so repeating the bug is an impossible work.
