### ISSUE TITLE
Indian language

### ISSUE THREAD

**Issue by PutuDesca** [hrydgard/ppsspp#15122]
Added indian language in ppsspp 
still in progress...

![IMG_20211110_192949.JPG](https://user-images.githubusercontent.com/93461649/141105802-1112fbf1-cb6f-4e3f-beee-8b27fba04a01.JPG)

**Comment by hrydgard** [comment]
You can just make a pull request instead of creating an issue first, although I guess that's fine too.

**Comment by PutuDesca** [comment]
Ok...
