### ISSUE TITLE
Failure extracting texture pack 

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#15121]
Got this reported on Discord. 

Almost certainly, if this is reproducible, it's some mistake with paths after the big Android storage refactor (despite it happening on PC). 

(Or the texture pack zip file is not organized right)

**Comment by Back2Life888** [comment]
It's not android. This occurs on PC.

**Comment by LunaMoo** [comment]
@Back2Life888 please write steps how to reproduce it.

**Comment by unknownbrackets** [comment]
Which texture pack?  I'm pretty sure I tried installing the Ys vs Trails one, even gave some instructions on fixing the ini which was broken.  That wasn't long ago.

-[Unknown]

**Comment by unknownbrackets** [comment]
Sounds like the user may have followed up on Discord to clarify they meant "save new textures" wasn't working when they said "extract", but other users are reporting it working.

It might simply be a problem of expectations, i.e. "extract" may imply they think it somehow searches and decodes textures stored in any possible compression format, no matter how custom, and puts every single possible one in the texture folder, using its appropriate palette using a large fleet of machine learning servers crunching away.  It doesn't do this.

-[Unknown]

**Comment by hrydgard** [comment]
Yeah. I'm gonna close this.
