### ISSUE TITLE
Bleach: Soul carnival 2 - hang/crash in main menu (Android/Windows)

### ISSUE THREAD

**Issue by Saramagrean** [hrydgard/ppsspp#15123]
### Game or games this happens in

Bleach: Soul Carnival 2 (UCJS10106)

### What area of the game / PPSSPP

Hang and crash in main menu. (all backends)

![BSC2](https://user-images.githubusercontent.com/26355472/141230975-96ef9be0-3701-47be-9141-02832dd6aab9.png)

### What should happen

Can access into main menu.

![BSC2-0](https://user-images.githubusercontent.com/26355472/141231335-bb006640-6dc5-424b-95e9-65e93d6b9537.png)

### Logs

Windows.
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/7517437/ppsspplog.zip)

Android.
...Soon...

### Platform

Other

### Mobile phone model or graphics card

Redmi Note 8 (Android 12, Snapdragon 665, Adreno 610) /// Windows 10 (Intel i5 6200U, Intel HD Grahpics 520)

### PPSSPP version affected

v1.12.3-61-g11eb5fa0c

### Last working version

v1.12.3-43-g593241b50

### Graphics backend (3D API)

Other

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
This is caused by a06efdd222e291434ce28825c4aca1cce3368fda, two things in the stack are locking the mutex.  Just need to separate out the callbacks.

-[Unknown]

**Comment by Saramagrean** [comment]
Can confirm it fixed by https://github.com/hrydgard/ppsspp/pull/15124.
