### ISSUE TITLE
Autoframeskip skips frame at fullspeed

### ISSUE THREAD

**Issue by Stizzie** [hrydgard/ppsspp#15130]
As i know auto frameskip suppose to skip in games that could not keep full speed and stop skipping at 30fps or when full speed is archieved.
It works nicely in this case.
Midnight club 3 DUB auto skip off
![Screenshot_2021-11-12-13-05-44-551_org ppsspp canary](https://user-images.githubusercontent.com/80938076/141421983-2c36e630-4036-4edf-855c-6aa548833987.jpg)

Auto skip on
![Screenshot_2021-11-12-13-10-32-173_org ppsspp canary](https://user-images.githubusercontent.com/80938076/141422238-4a447542-20f8-4562-99b3-20a581273c86.jpg)

However it is not perfect. In some cases it skips 1 frame anyway while the gamespeed is still full causing these micro-drops that otherwise dont happen when auto skip is off
![Screenshot_2021-11-12-13-18-43-974_org ppsspp canary](https://user-images.githubusercontent.com/80938076/141422689-217e9193-1275-4537-9d9d-94a9a3559158.jpg)

Happens to games that already run well too. It will occasionally skip 1 frame while the game is running at full speed.

**Comment by Gamemulatorer** [comment]
Related https://github.com/hrydgard/ppsspp/issues/14315
https://github.com/hrydgard/ppsspp/issues/12313
