### ISSUE TITLE
Motostorm ArticEdge Vulkan Performance

### ISSUE THREAD

**Issue by Stizzie** [hrydgard/ppsspp#15136]
### Game or games this happens in

UCES12051 - Motostorm ArticEdge

### What area of the game

Beginning of races, moments when there is lots of racers on the frame.

### Speed seen in PPSSPP

80% 25 

### GE frame capture and debug statistics

[recording.zip](https://github.com/hrydgard/ppsspp/files/7532452/recording.zip)

### Platform

Android

### Mobile phone model or graphics card

Poco M3

### PPSSPP version affected

Latest git

### Last working version

None

### Graphics backend (3D API)

Vulkan

### Any other notes or things you've tried

Not happening in OpenGL

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try changing graphics settings to determine if one causes the slowdown.
- [ ] Include logs or screenshots of issue.

**Comment by Gamemulatorer** [comment]
Did you enable simulate block transfer effects?
See 👉 https://github.com/hrydgard/ppsspp/issues/15063

**Comment by Stizzie** [comment]
> Did you enable simulate block transfer effects? See 👉 #15063

no block effect is off. box logo bug happened but besides that no considerable graphic bug so...
Frame drops only happen in Vulkan. OpenGL runs much faster

**Comment by Panderner** [comment]
@Stizzie performance comparison? Your phone is same as my phone.

**Comment by Stizzie** [comment]
> @Stizzie performance comparison? Your phone is same as my phone.

You meant comparison between the 2 APIs ? 
Just pretty much OGL works and Vulkan has slowdowns under exact same settings

**Comment by Panderner** [comment]
> You meant comparison between the 2 APIs ?

Umm yes please screenshot for performance comparison if the game lags in Vulkan.

**Comment by Stizzie** [comment]
OGL
![20211114_190601](https://user-images.githubusercontent.com/80938076/141680340-a239a6c9-0ac1-49b8-970e-3f6e15b88080.gif)

Vulkan
![20211114_190504](https://user-images.githubusercontent.com/80938076/141680358-1d449a18-a006-4fea-bea1-22a506f1afef.gif)

**Comment by Gamemulatorer** [comment]
> OGL ![20211114_190601](https://user-images.githubusercontent.com/80938076/141680340-a239a6c9-0ac1-49b8-970e-3f6e15b88080.gif)
> 
> Vulkan ![20211114_190504](https://user-images.githubusercontent.com/80938076/141680358-1d449a18-a006-4fea-bea1-22a506f1afef.gif)

I forgot but already mentioned the performance issue here 😅👉 https://github.com/hrydgard/ppsspp/issues/12363#issuecomment-934138090

**Comment by Gamemulatorer** [comment]
Didn't feel any improvement after https://github.com/hrydgard/ppsspp/pull/15474 is merge vulkan still slow on my phone.

**Comment by Gamemulatorer** [comment]
@hrydgard this can be close now performance improvement after https://github.com/hrydgard/ppsspp/commit/9b25093585faaa5e3c06e7347cc4d01553748102 on my phone using Vulkan.

**Comment by hrydgard** [comment]
Not sure how that one improved so much over #15474, but if it's fixed, it's fixed.

**Comment by Stizzie** [comment]
> [@hrydgard](https://github.com/hrydgard) this can be close now performance improvement after [9b25093](https://github.com/hrydgard/ppsspp/commit/9b25093585faaa5e3c06e7347cc4d01553748102) on my phone using Vulkan.

Maybe this feedback is placebo. This isssue still persist and were not fixed (1.18.1)
