### ISSUE TITLE
Ampersand values inside param.sfo / save data title + detail

### ISSUE THREAD

**Issue by JulianoW** [hrydgard/ppsspp#15167]
### Game or games this happens in

ULJM05086 (sort of)

### What area of the game / PPSSPP

Note: I say ULJM05086 but the original Japanese version displays the fixed width ampersand (U+FF06) rather than 0x26. I'm not sure what game might actually display this issue.

Ampersands (ascii 0x26) are not displaying in the save menu (param.sfo data). I found issue [3523](https://github.com/hrydgard/ppsspp/issues/3523) while searching, which stated a double ampersand was needed for UI stuff. I attempted editing my title to include a double ampersand, and it displayed correctly, but this is clearly unintended behavior inside of a game. (I think? Because otherwise it would display both ampersands on hardware.)

Screenshots:
Using "Suikoden I & II" as the title results in the ampersand not displaying:
![image](https://user-images.githubusercontent.com/6155506/143322126-667a5736-1613-428c-9792-93b2912e09ee.png)

If I edit the title to "Suikoden I && II", it "displays correctly":
![image](https://user-images.githubusercontent.com/6155506/143322234-513485a2-def0-4105-9c02-1e5ce410fba6.png)

Memory view of what is being written to the param.sfo:
![image](https://user-images.githubusercontent.com/6155506/143322409-c111caac-4fe1-4c2f-aaeb-6385d6adde0d.png)

Note: This happens in all portions of this menu - game title, save title, details, etc.

But this isn't an acceptable solution as that would cause the double ampersand to display when running on hardware.

### What should happen

The save/load menu should be able to display single ampersands. (which is what the original hardware does)

### Platform

Windows

### Mobile phone model or graphics card

GTX 1080

### PPSSPP version affected

v1.12.3-276-gfb755bac1

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
When #15168 finishes building, let me know if that fixes it (you can download the build under Artifacts on the Checks tab.)

-[Unknown]

**Comment by JulianoW** [comment]
Just tested it and confirm it's working correctly now. Thanks! 👍
