### ISSUE TITLE
Need help removing rolling bar effect from crt shader by KillaMaaki

### ISSUE THREAD

**Issue by ryzenvideous** [hrydgard/ppsspp#15173]
The rolling bar effect for me is a little visually obstructive and I would like to find a way to remove it. On the issue #12546 I came across, a user helped by guiding on how to remove by removing lines of code from the fsh file and even presented the full code with the concerned lines removed. 

What I did is I created a text file, copied and pasted the code, saved it as crt.fsh and created a shaders folder within the psp folder to move it there but it seems that the rolling bar effect still remains unchanged for some reason. Could someone please help me out with this?

Also, I'm using PPSSPP for Android.

**Comment by iota97** [comment]
On android you can't edit shader file as you don't have access to them but you may just add a new one.

You will need a `.ini` file that describe the shader with a `.fsh` and a `.vsh` in the shaders folder like this: [shaders.zip](https://github.com/hrydgard/ppsspp/files/7611469/shaders.zip)

After this you should see a new shader in the list named `CRT Scanlines - not moving`.

**Comment by ryzenvideous** [comment]
> On android you can't edit shader file as you don't have access to them but you may just add a new one.
> 
> You will need a `.ini` file that describe the shader with a `.fsh` and a `.vsh` in the shaders folder like this: [shaders.zip](https://github.com/hrydgard/ppsspp/files/7611469/shaders.zip)
> 
> After this you should see a new shader in the list named `CRT Scanlines - not moving`.

Dude, you're a legend 😄

I tried other ways like finding the ini which includes the lines for the crt shader from Mr Hrydgard's own list of files, downloaded the concerned fsh and vsh and changed the code and text accordingly but it somehow couldn't work, but the files you provided do!

Once again you're a legend, and playing ULUS10176, or any other PSP titles will be even more enjoyable! The shader looks almost like how the original PSP screen looked! Or at least that's how I recall it.. regardless it just looks great!

Happy Thanksgiving to you, Sir.
