### ISSUE TITLE
[Translation] Tagalog language update

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#15189]
### What should happen

I don't know how to make a pull request so I make this issue so that anyone who know how to submit a pr for this please do it 🙏😁

Here's the file zip.
[tg_PH.ini.zip](https://github.com/hrydgard/ppsspp/files/7634252/tg_PH.ini.zip)

### Who would this benefit

All Filipino

### Platform (if relevant)

Android

### Games this would be useful in

All

### Other emulators or software with a similar feature

All

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
Merged it directly for you!
