### ISSUE TITLE
shm not cleaned correctly

### ISSUE THREAD

**Issue by nadenislamarre** [hrydgard/ppsspp#15195]
### Game or games this happens in

any

### What area of the game / PPSSPP

any

### What should happen

the files /ppsspp_0.ram /ppsspp_1.ram are created and never cleaned.
(probably due to a recent modification, less than 3 months)

i've done a temporary patch here 
https://github.com/batocera-linux/batocera.linux/blob/master/package/batocera/emulators/ppsspp/004-fix-ppssppramclean.patch

### Platform

Linux / BSD

### Mobile phone model or graphics card

any

### PPSSPP version affected

v1.12.3

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
Oops, see #15197.

-[Unknown]

**Comment by nadenislamarre** [comment]
thanks a lot. it works perfectly.
