### ISSUE TITLE
driver 76 mission crash

### ISSUE THREAD

**Issue by masonreiss** [hrydgard/ppsspp#15192]
### Game or games this happens in

driver 76 USA

### What area of the game / PPSSPP

The first race you do for the main missions crashes over 50 yards away from the starting line and I cant progress any further, is there a way to fix this?

### What should happen

it shouldnt crash

### Platform

Windows

### Mobile phone model or graphics card

nvidia geforce rtx 3080

### PPSSPP version affected

v1.12.3

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [x] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment]
By crash, do you mean PPSSPP got forced close like https://github.com/hrydgard/ppsspp/issues/14610? or the game shows a blue screen?
Or may be freezes like https://github.com/hrydgard/ppsspp/issues/12054 ?

**Comment by masonreiss** [comment]
Yh it freezes for a few seconds then force closes out of the game, the other missions seem to be fine at the moment but this 1 will crash it to my desktop and its a main mission

**Comment by ANR2ME** [comment]
It seems you haven't try it without cheat or savestate, right? since the "Try without any cheats and without loading any save states." didn't get checklisted?

Cheats could cause a crash too, so please try without cheats or savestate to find out whether the issue related to them or not.

**Comment by ANR2ME** [comment]
Btw, in my case it crashed not long after i choose "Continue" from the main screen, which leads to "Loading" screen and then crashed, not even racing yet LOL
![image](https://user-images.githubusercontent.com/7974720/144665340-fd1a260e-d2d6-4bc8-88f7-4b8c1823ab55.png)

**Comment by masonreiss** [comment]
Ah sorry thought I mentioned that i haven't used cheats, I'll try the save states and there isn't a debuglog.bat in my folder, is there a way to do it in the pps itself?

**Comment by ANR2ME** [comment]
The issue seems to be related to D3D11, have you tried using other 3D Graphic Renderer?

**Comment by masonreiss** [comment]
Just tried them all and it still crashes

**Comment by masonreiss** [comment]
Not sure if showing you the debug console will help but
![Uploading 16385665317023371701206754511579.jpg…]()

**Comment by ANR2ME** [comment]
On a crash, PPSSPP might not even have the chance to print the log on Debug Console, it usually something that haven't been printed yet.

**Comment by masonreiss** [comment]
It showed alot of errors on the debug console a min ago while I had it active it crashed but stayed on the screen repeating the messages, dunno if this can be fixed had this same bs on the psp to but on a different mission 🤣

**Comment by ANR2ME** [comment]
Well your Debug Console's screenshot didn't get uploaded, so we'll never know :) 
Try to screenshot it right before PPSSPP force closed (while it still freezes) it may shows something.

**Comment by unknownbrackets** [comment]
It sounds like this is probably either a fixed D3D11 issue, or the same underlying issue with IO timing as #12054.

I'm going to close this as a duplicate, and when verifying that other is fixed I'm sure people will check the first mission in different backends.

-[Unknown]

**Comment by trentsylvania** [comment]
driver 76 mission crash (SOLVED)

I tried both the USA and Europe version same issue, but after reading the mission script I had an idea 💡 upon starting the race allow the first two drivers to get ahead of you a bit, take them out with your pistol before reaching the crash line, TURN AROUND and drive to Manhattan island using the first or second bridge (stay on the outskirts of Brooklyn) you'll have to take the third bridge from Manhattan back to Brooklyn and retrieve the car, after doing so drive the outskirts of Brooklyn back to the finish line, kinda time consuming but it works, I'm unsure after retrieving the vehicle if the bug still exist or not, I wasn't willing to find out, cheers 😉

Alternatively: you could wait and allow one of the two racers to retrieve the car and bring it to you allowing you to take them out before they reach the finish line, I haven't tried this method personally but in theory it will work, you'll just have to wait for them to return to the start of the race area 
 😉

**Comment by trentsylvania** [comment]
![Screenshot_20221129-234002](https://user-images.githubusercontent.com/119473169/204709268-37da3bfc-3595-4f58-8232-38ea70af1733.png)
![Screenshot_20221129-234210](https://user-images.githubusercontent.com/119473169/204709290-75f53f8d-414a-4e4a-ab0d-b44542678b4b.png)
