### ISSUE TITLE
Tekken 5 AdHoc Multiplayer doesn't work

### ISSUE THREAD

**Issue by ANR2ME** [hrydgard/ppsspp#15196]
### Game or games this happens in

ULUS10139 Tekken Dark Resurrection

### What area of the game / PPSSPP

It seems there is an issue where a game called sceNetAdhocctlDisconnects multiple times, causing the AdhocServer to drop the connection (socket error 10053) when a game is trying to leave a group (Disconnect) when not in a group, ended loosing the connection to the AdhocServer instead of just leaving the group, thus unable to join another group (due to "busy" while waiting for Disconnect's reply from AdhocServer)
![image](https://user-images.githubusercontent.com/7974720/144673151-e16a7429-c05d-44aa-9222-2125b1749581.png)
Based on the logs, the Adhocctl's State supposed to be 0 after Disconnected successfully, but for some reason it remains 1, thus triggering another "Disconnect" attempt. 
The "busy" state should also be updated properly after receiving a reply from AdhocServer, so the next Adhocctl syscall can be used (ie. AdhocctlConnect in this case)

### What should happen

Should disconnect/leave a group properly.

### Platform

All

### Mobile phone model or graphics card

Intel UHD Graphics 620 + Nvidia Geforce MX150 (default for PPSSPP)

### PPSSPP version affected

1.12.x or might be even much older version

### Last working version

Not sure, i just noticed it recently

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by MojoJojoDojo** [comment]
Pretty sure it worked fine on 1.11+ (localhost at least) just not 1.12 but not sure.
I did see some videos of people playing this game recently (even online) :
https://www.youtube.com/watch?v=v_WPYnFYGBE
Dunno the version though.
