### ISSUE TITLE
Viewport-related assert in Vulkan backend

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#15207]
![image](https://user-images.githubusercontent.com/130929/145021626-1f1cac9b-edc3-4dc1-a63b-6de5484f08e4.png)

Reported on Discord by Vinnie, in assassin's creed bloodlines with non-buffered rendering.

**Comment by Gamemulatorer** [comment]
Just OT why I cannot join in the discussion/comment in ppsspp discord? :(

**Comment by hrydgard** [comment]
Don't know, sounds weird :(

**Comment by ANR2ME** [comment]
> Just OT why I cannot join in the discussion/comment in ppsspp discord? :(

Try leaving ppsspp server first and rejoining again from the invitation link

**Comment by Gamemulatorer** [comment]
> > Just OT why I cannot join in the discussion/comment in ppsspp discord? :(
> 
> Try leaving ppsspp server first and rejoining again from the invitation link

I already did that :(
This is only my view in ppsspp discord.
![Screenshot_2021-12-07-22-59-46-639_com discord](https://user-images.githubusercontent.com/37603562/145053107-a63c723b-9e50-4c14-95a9-524dfeb72659.jpg)

**Comment by iota97** [comment]
@Gamemulatorer, you may be missing the verification? The instruction are in `server_rules` (scroll to top, you may have missed the first part).

**Comment by hrydgard** [comment]
@Gamemulatorer what's your username on Discord? I'll fix it.

**Comment by Gamemulatorer** [comment]
> @Gamemulatorer what's your username on Discord? I'll fix it.

Emulatorer#9023
