### ISSUE TITLE
No video only sound

### ISSUE THREAD

**Issue by navy1978** [hrydgard/ppsspp#15234]
### Game or games this happens in

all

### What area of the game

all

### What happens

 I’m using retrorun a very small front-end  that uses ppsspp (ARM) libretro core and the emulations works but without video and I’m getting this error message : ```

[err] [IO] Couldn't read data for 'ppge_atlas.zim'
[err] [SCEGE] Failed to load ppge_atlas.zim.

Place it in the directory "assets" under your PPSSPP directory.

PPGe stuff will not be drawn.
```
Any idea?

### What should happen

it should display the video

### GE frame capture

_No response_

### Platform

libretro / Retroarch

### Mobile phone model or graphics card

RG351P

### PPSSPP version affected

824805ec1e60568a9c68c525245882df553c7427

### Last working version

none

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [ ] Include logs or screenshots of issue.

**Comment by Panderner** [comment]
Do you put PPSSPP assets in RetroArch/system/PPSSPP directory?

**Comment by navy1978** [comment]
this is the current situation:
![image](https://user-images.githubusercontent.com/13300861/145991017-ecabe42f-26e2-4188-b9f5-affd99f0b0c8.png)

**Comment by gouchi** [comment]
Hi,

Is it still an issue ? You will need the [assets](https://docs.libretro.com/library/ppsspp/#bios) indeed.

If not, please close this issue.

Thank you.
