### ISSUE TITLE
Mix of case insensitivity/sensitivity causing problems when memstick folder ends with PSP

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#15236]
Reported by mrfixit2001 on discord.

Not entirely clear what's going on but apparently when he named his memstick folder "psp" (on a Linux machine), the hack we use to strip off the PSP prefix to the path (added for Android scoped storage support) seems to activate while still not being able to access the files, which is weird.

Additionally, seems when he named it PSP instead it segfaults, while other names work.

So this is all a little confusing but should be looked into.

**Comment by MojoJojoDojo** [comment]
it's basically what I reported here in a way:
https://github.com/hrydgard/ppsspp/issues/15052

**Comment by mrfixit2001** [comment]
I saw other similar issues reported regarding all the saves being corrupt. Some games report missing files as corruption, which I observed on Burn Out in this case.

The technical detail behind this is that when FixPathCase calls FixFilenameCase it passes two paths, and when the mem stick directory included PSP then both paths that are passed include PSP. An example from my build:
"/rcade/share/saves/psp"  and   "/PSP/SAVEDATA/ULUS10025SAVE006"

This causes FixPathCase to return false, which then causes DirectoryFileHandle::Open to exit early also returning false and not properly create the files.

**Comment by hrydgard** [comment]
Likely fixed by #15237 ?

**Comment by unknownbrackets** [comment]
I don't think we've seen any further reports about this - absent of any confirmation, perhaps we should close?  It ought to be fixed, and that no one has complained may be the most confirmation we'll see.

-[Unknown]

**Comment by unknownbrackets** [comment]
I'm going to close this - there have been no new reports of these issues since that was merged and there was a comment in Discord I believe that it fixed the initial problem.

-[Unknown]
