### ISSUE TITLE
macOS Monterey - PPSSPPSDL.app is damaged and can't be opened

### ISSUE THREAD

**Issue by e-maximilian** [hrydgard/ppsspp#15248]
### Game or games this happens in

None

### What area of the game / PPSSPP

Not Game

### What should happen

Crash when opening PPSSPP on macOS Monterey

### Logs

![PPSSPP Crash macOS Monterey](https://user-images.githubusercontent.com/2749152/147036645-8092e721-5562-4cd8-91f4-3c98684352d0.png)

### Platform

macOS

### Mobile phone model or graphics card

MacBook Pro (13-inch, M1, 2020)

### PPSSPP version affected

1.12.3

### Last working version

1.11 from Brew.sh https://formulae.brew.sh/formula/ppsspp

### Graphics backend (3D API)

Other

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by pete1302** [comment]
Also Crashing when opening PPSSPP on macOS Big Sur.

**Comment by unknownbrackets** [comment]
I wonder if something about the SDL2 packaging is not working on these newer OS versions?  Or maybe the version of macOS that Actions is building on changed?

-[Unknown]

**Comment by pete1302** [comment]
I tried brew install ppsspp and it worked for me .

**Comment by e-maximilian** [comment]
Yes brew one can, but it's not latest version.

Sent from iPhone
________________________________

**Comment by pete1302** [comment]
Does any one know a brew or direct version of pcsx2 for mac without wineskin ?

**Comment by Jayark365** [comment]
Fixed it by removing the check.
`sudo xattr -cr /Applications/PPSSPPSDL.app`

**Comment by unknownbrackets** [comment]
Oh, it's because it doesn't have a valid code signature.

-[Unknown]

**Comment by pwatk** [comment]
> > Fixed it by removing the check.
> > sudo xattr -cr /Applications/PPSSPPSDL.app
> 
> I'm experiencing this as well, even if I do right click -> open it still does it. `brew install ppsspp --cask` also does the same thing.
> 
> The suggestion above worked.

Same here

**Comment by dimovich85** [comment]
Yes, homebrew + sudo xattr -cr /Applications/PPSSPPSDL.app works

**Comment by mygizli04** [comment]
You should be able to right click and click open on the app to bypass this without any terminal commands.

**Comment by shinra-electric** [comment]
Just to bump this, the builds on GitHub Actions are working fine. 

This issue could be closed if the 1.12.3 release is re-posted, or if a new release is posted.
