### ISSUE TITLE
Monster Hunter Freedom Unite

### ISSUE THREAD

**Issue by inukaze** [hrydgard/ppsspp#15266]
### Game or games this happens in

ULES01213

### What area of the game

Hi there, i had compile the RetroCore for Use inside RetroArch v1.9.0, i notice the Follow with Monster Hunter Freedom Unite. (the next next year i upgrade it)

1 - Does not connecting to retroachivements (i don't know if possible when is compile from this github)

2 - Graphical Errors on libretro core version
![PPSSPP-v1 12 3-libretrocore-001](https://user-images.githubusercontent.com/1647332/147843634-480372f4-8b99-4a4b-8e11-5d7c5209cf84.png)
![PPSSPP-v1 12 3-libretrocore-002](https://user-images.githubusercontent.com/1647332/147843639-8efa9f22-9094-4b4c-8b11-03a96c82e4e0.png)
![PPSSPP-v1 12 3-libretrocore-004](https://user-images.githubusercontent.com/1647332/147843641-55d2329d-c691-47ab-8a43-6009a6c95554.png)

3 - in StandAlone version not happen with same game : 
![PPSSPP-v1 12 3-001](https://user-images.githubusercontent.com/1647332/147843655-9843be76-5732-4ff1-955f-2b7b8d74cc68.png)
![PPSSPP-v1 12 3-002](https://user-images.githubusercontent.com/1647332/147843657-022af01d-5dce-4917-b17d-30b6839362d6.png)
![PPSSPP-v1 12 3-003](https://user-images.githubusercontent.com/1647332/147843659-23b61842-0f86-4190-a0bc-3c9fb1cefaad.png)

Well happy new year 2022

### What happens

Text is wrong rendered

### What should happen

Show text correctly

### Platform

libretro / Retroarch

### Mobile phone model or graphics card

Nvidia GeForce GT 620

### PPSSPP version affected

v1.12.3

### Last working version

Unknow

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by iota97** [comment]
Could you provide some log? Might be some missing font atlas issues.

Also make sure the assets you are using in retroarch are from the right version as they got changed in the git version recently.

**Comment by inukaze** [comment]
i can provide some logs, just tell me which logs are neccesary, and i share it :D.

**Comment by edumj** [comment]
Hola,

I'm in Batocera linux but I had the same problem, and I just fixed it by creating a folder named "flash0" and copying "font" folder from standalone PPSSPP, inside.

In my case, from:
/usr/share/ppsspp/PPSSPP/flash0/font
to:
/userdata/saves/psp/PSP/flash0/font

But, I doesn't solve otther problems with fonts in Memory Stick warnings or Metal Gear Solid...

**Comment by iota97** [comment]
Did you install assets as mentioned in BIOS section [here](https://docs.libretro.com/library/ppsspp/#bios)?

There is also the problem that guide mention latest asset from master that might not be the ones your version need if it's 1.12.3 stable. If that's the case download the Windows zip [here](https://www.ppsspp.org/downloads.html) and get assets from it.

I'm not really sure why they don't suggest to download from there to avoid having user to download an entire repo just for the assets tbh, I guess they don't want user to just have the stable version...

About logs it should log in the shell if you ran from it, but I'm not used to retroarch.

**Comment by edumj** [comment]
Hi, I ended up copying the full content from standalone folder (after getting the real PSP fonts):
/usr/share/ppsspp/PPSSPP
to:
/userdata/bios/PPSSPP

Because in retroarchcustom.cfg it says it's the system directory:
system_directory = "/userdata/bios/"

And now it works! Because, as you say, it doesn't work with the assets from the latest build.

**Comment by inukaze** [comment]
Sorry for take to long on answer. i just busy with another things. i just enter on GitHub some days ago for feature request on mupen64plus () and i see i have notifications but i forget after i post on that proyect XD

@edumj : Thank you very much, that example resolve the problem.

I just put the folders/file on where i need, after i make a symbolic link, and put on the ".hidden" file the folder named "PPSSPP" (for it hide after i restart, because i really prefer my system folder organizate).

https://i.postimg.cc/CFK0zdb4/RAPSP-001.png

My browser don't want attach the image directly to GitHub ¬¬

Well the issue is solve : 
https://i.postimg.cc/sfMqrhdM/RAPSP-002.png
https://i.postimg.cc/jq3g3dDR/RAPSP-003.png
https://i.postimg.cc/q7QXtjnp/RAPSP-004.png

Well the unique thing i need to do, is change the defaults Keys of RetroArch because the PPSSPP use a lot of keys and that make a conflict with RetroArch keys. i don't know if RetroArch support change "F" by "Alt+Enter" to change to "FullScreen Toggle" i need change almost RetroArch defaults keys, becuase conflict with the user keyboard configuration except F2,F3,F4 (Save State, Show FPS, and Load State) the rest i need change every default key on retroarch.

-------------- The no important part for this thread -----------
well i still not had upgrade retroarch to latest version yet, because i need near 40GB for compile each core by myself, the mayority of precompiled cores doesn't work for me because ever are compile against libraries, in more newer version the Slackware(64) 14.2 had. 

like the follow list (give more segmentation fault or the libc version requiere is superior) :
00_example
3dengine
4do
81
2048
advanced_tests
bk
blastem
bluemsx
bnes
boom3
boom3_xp
bsnes2014_accuracy
bsnes2014_balanced
bsnes2014_performance
bsnes_cplusplus98
bsnes_hd_beta
bsnes
bsnes_mercury_accuracy
bsnes_mercury_balanced
bsnes_mercury_performance
cannonball
cap32
chailove
citra_canary
citra
craft
crocods
cruzes
daphne
dinothawr
dolphin_launcher
dolphin
dosbox_core
dosbox
dosbox_pure
dosbox_svn_ce
dosbox_svn
duckstation
easyrpg
ecwolf
emux_chip8
emux_gb
emux_nes
emux_sms
fbalpha2012_cps1
fbalpha2012_cps2
fbalpha2012_cps3
fbalpha2012
fbalpha2012_neogeo
fbneo
fixgb
fixnes
flycast_gles2
flycast
flycast_wince
fmsx
freechaf
freeintv
frodo
fsuae
gambatte
gearboy
gme
gpsp
gw
handy
hatari
hbmame
higan_sfc_balanced
higan_sfc
imageviewer
ishiiruka
lowresnx
lutro
mame2000
mame2003
mame2003_midway
mame2003_plus
mame2009
mame2010
mame2015
mame2016
mamearcade
mame
mednafen_lynx
mednafen_ngp
mednafen_pce_fast
mednafen_pcfx
mednafen_psx_hw
mednafen_supafaust
mednafen_supergrafx
mednafen_vb
mednafen_wswan
melonds
mesen
mesen-s
mess2015
meteor
mpv
mrboom
mu
nekop2
neocd
nestopia
np2kai
nxengine
o2em
oberon
openlara
opentyrian
opera
pascal_pong
pcem
pcsx1
pcsx2
pcsx_rearmed_interpreter
pcsx_rearmed_neon
play
pocketcdg
pokemini
potator
prboom
px68k
quasi88
quicknes
race
redbook
reminiscence
remotejoy
retrodream
rustation
sameboy
scummvm
simcp
smsplus
snes9x2002
snes9x2005
snes9x2005_plus
snes9x2010
squirreljme
stonesoup
tempgba
testaudio_callback
testaudio_no_callback
testaudio_playback_wav
testgl_compute_shaders
testgl_ff
testgl
testinput_buttontest
test
test_netplay
testretroluxury
testsw
testsw_vram
testvulkan_async_compute
testvulkan
tgbdual
theodore
thepowdertoy
tic80
tyrquake
uae4arm
ume2015
uzem
vecx
vemulator
vice_x64
vice_x64sc
vice_x128
vice_xcbm2
vice_xcbm5x0
vice_xpet
vice_xplus4
vice_xscpu64
vice_xvic
virtualjaguar
vitaquake2
vitaquake2-rogue
vitaquake2-xatrix
vitaquake2-zaero
vitaquake3
vitavoyager
x1
x64sdl
xrick
yabasanshiro
yabause

i had compile some cores by myself like :
atari800
desmume2015
desmume
fceumm
ffmpeg
flycast_wince
freej2me
fuse
gearsystem
genesis_plus_gx
kronos
mednafen_gba
mednafen_pce
mednafen_psx
mednafen_saturn
mednafen_snes
mgba
mupen64plus
pcsx_rearmed
picodrive
ppsspp
prosystem
puae
retro8
snes9x
stella2014
stella
vbam
vba_next
