### ISSUE TITLE
Frameskip issue [Super Dangan-Ronpa 2]

### ISSUE THREAD

**Issue by Nabokov86** [hrydgard/ppsspp#15276]
### Game or games this happens in

NPJH50631 - スーパーダンガンロンパ２　さよなら絶望学園

### What happens

When frame skipping starts, everything starts to flicker a lot. Watch the video, please.

**The video contains flickering, be careful if you are sensitive.**

https://user-images.githubusercontent.com/26260168/147911805-c099512a-9975-40ca-9929-fbd5839b029d.mp4

Also, if you skip frames in constant (manual) mode, the game freezes.

### GE frame capture

Please tell me if you need it.

### Platform

Windows, Android 9

### Mobile phone model or graphics card

GTS450

### PPSSPP version affected

v1.12.3-570-gb2bb0be05
V1.12.3
V1.11.3
V1.10.3

### Last working version

Unknown

### Graphics backend (3D API)

OpenGL / GLES
Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by Gamemulatorer** [comment]
Can you try the v1.12.3-570 build apk here https://buildbot.orphis.net/ppsspp/index.php?m=fulllist

**Comment by Nabokov86** [comment]
> v1.12.3-570 build

@Gamemulatorer Same problem with this build, too.

**Comment by ANR2ME** [comment]
> Also without autoskip, PPSSPP freezes.
>

This is probably need to be fixed first, if the game frozen without frame skipping O.o

Btw, are you using the default settings on Graphic settings? 
because some of the option could cause flickering issue if you changed them, so make sure you tested it using the default settings too to make sure it wasn't because of the setting you've changed.

**Comment by ANR2ME** [comment]
Btw, does using a fixed/constant frame skipping of 1 and 2 will shows the same freezing effect?

I wondered if the game were switching between 2 frames but only one of them got updated, and with a certain fixed number of frame skipping it ended rendering the frame that didn't get updated, thus looked like frozen.

**Comment by Nabokov86** [comment]
Very weird.

The image freezes only if I walk in a certain direction (left or right). The picture just completely freezes while I walk to the left (or right) in the game. This is so weird.
And it happens only if the frame skip is an odd number (1, 3, 5).
On Android, it causes the PPSSPP itself to freeze if you switch to another app.

2, 4 frame skipping doesn't seem to cause this.

**Comment by Nabokov86** [comment]
Also skipping 2 or 4 frames doesn't cause that much flickering in the area where you need to walk between locations. But still, some of the frames are twitching/repeating.

And the flickering remains in the locations themselves.

**Comment by hrydgard** [comment]
Got to be something to do with the game running at half framerate but not the traditional way somehow, confusing the frameskipping logic.

I would recommend in general to never use frameskipping if at all possible. I am soon going to reorganize the settings based on safety/risk for glitches, and frameskipping is going in the pile of unsafe ones.

**Comment by Gamemulatorer** [comment]
I can reproduce this on this game and also on the King of Fighters Orochi Saga Collection JAP SW Rendering.
[recording.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/8495824/recording.ppdmp.zip)

**Comment by Nabokov86** [comment]
Some recent changes between **v1.13.1-600** and **v1.13.1-603** fixed the issue. No more flickering or freezing :rocket:

I noticed something else between these versions. The fps counter now shows 30, it used to be 60. But it feels the same. I wonder if this could be related to what solved this issue.

**Comment by Nabokov86** [comment]
![PPSSPP v1 13 1-600-g3e865abae - NPJH50631 _ スーパーダンガンロンパ２　さよなら絶望学園 2022_09_08 14_55_36](https://user-images.githubusercontent.com/26260168/189127386-d1e786db-f18b-4d78-a4a5-7ed92e479d43.png)
![PPSSPP v1 13 1-603-g59cb7a075 2022_09_08 14_54_07](https://user-images.githubusercontent.com/26260168/189127408-29528f08-f1d9-4009-bdd2-38e675897d27.png)

**Comment by hrydgard** [comment]
Yeah, seems plausible we misdetected some drawing before, I tightened up some checks in that commit. I'm gonna go ahead and close, thanks for testing!
