### ISSUE TITLE
Little Big Plannet Multiplayer

### ISSUE THREAD

**Issue by XDe0** [hrydgard/ppsspp#15278]
### Game or games this happens in

UCES01264

### What area of the game / PPSSPP

When I want to open "Community Planet" in LBP it's don't showing. And I have same situation in "My Pod" with news.
In nutshell i have a problems with Internet. I tried tips from "Ad-Hos GitHub Wiki" but it doesn't help.
![Screenshot_20220104-002152_PPSSPP](https://user-images.githubusercontent.com/82376990/147986979-a22033fc-2169-4b3e-b8dc-a4d2223d40d6.jpg)

### What should happen

It should work Internet conection and show "Communty Planet" and "News".

### Platform

Windows

### Mobile phone model or graphics card

Intel(R) Iris(R) Xe Graphics

### PPSSPP version affected

v1.12.3

### Graphics backend (3D API)

Direct3D 12

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
Unfortunately, this is a dead end.  They shut down the servers for this game in 2016 I believe.

That's what happens when content is housed outside of the installed data / disc / etc.  In the future, it'll just be gone.  Looking forward to the all streaming future yet?  Sigh.

-[Unknown]

**Comment by MojoJojoDojo** [comment]
Hopefully someone gonna make a server replacement solution that is open source like RPCN but for PSP...
I know someone gonna make a private server for LBP but on the Vita/PS4 side...
