### ISSUE TITLE
Android performance worse than Linux performance on some device

### ISSUE THREAD

**Issue by clondy999** [hrydgard/ppsspp#15281]
### What should happen

The performance of ppsspp under Linux is very good.
However, under Android, the performance is about 15% lower than that of Linux.
What's the problem?
The device is the same, so is the game.
The version used is: v1.12.3

### Who would this benefit

anybody

### Platform (if relevant)

Android

### Games this would be useful in

Any game

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by Gamemulatorer** [comment]
What is the specifications of your android?
What game did you compare?

**Comment by clondy999** [comment]
Android 6.1
The game is Tekken 6

**Comment by hrydgard** [comment]
Probably comes down to worse graphics drivers, which usually is the bottleneck in games like Tekken 6 with advanced grpahics.

**Comment by Panderner** [comment]
what device are you using?

**Comment by clondy999** [comment]
Amlogic S905M

**Comment by clondy999** [comment]
I've seen that the Android kernel is 3.14
The Linux kernel is also 3.14
But the graphics driver is beyond my scope.

**Comment by ANR2ME** [comment]
It have Mali-450 GPU right? I don't think it's a good GPU for gaming.

And also, Vulkan is not available on Android 6 yet, so you're limited to OpenGL, may be try using Android 7.1 to get access to Vulkan (not sure whether Mali 450 supports vulkan or not tho)

**Comment by Panderner** [comment]
@clondy999 Are you using the same processor on linux?

**Comment by clondy999** [comment]
Yes

**Comment by clondy999** [comment]
@ANR2ME Linux also does not support Vulkan, but it runs very well

**Comment by unknownbrackets** [comment]
It could even come down to thermal throttling configurations.  It's likely Android would be configured differently there, even on the same device.  Furthermore, there are background processes on Android and it has its own compositor.  It's hard to say if those might be affecting performance.

I would agree it's probably graphics drivers, though.  Graphics drivers are often not updated on phones, even when the OS is upgraded.

Under Settings -> Tools -> System information, you should see a field for "Driver version".  Compare this between Android and Linux.

-[Unknown]

**Comment by Gamemulatorer** [comment]
@clondy999 can you screenshots your linux and android system information just like this:
![Screenshot_2022-01-09-11-23-15-249_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/148668001-d6465b9e-8161-47ec-8947-4eee1a93e52b.jpg)

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
