### ISSUE TITLE
Cannot set PSP Model on RetroArch, Toukiden does not work properly~！

### ISSUE THREAD

**Issue by xiejinglan** [hrydgard/ppsspp#15306]
### Game or games this happens in

ULJM06290 - Toukiden 

### What area of the game / PPSSPP

![QL4(8IRD)7}FKJWLS@E{QTU](https://user-images.githubusercontent.com/14818166/149636926-c539b877-8d92-47cb-a0c6-38c86d844b2b.png)

### What should happen

Hope to be able to set PSP Model

### Platform

libretro / Retroarch

### Mobile phone model or graphics card

Pixel 4a

### PPSSPP version affected

RetroArch 1.9

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by iota97** [comment]
I wonder if we should just default to PSP-2000 rather than adding another option.

Not sure if this game is going to work anyway, for reference the message is "Ad hoc play on PSP-1000 not available." (OCR + Google translate).

**Comment by Panderner** [comment]
It's looks like they forgot to add PSP Model selection for RetroArch core.

**Comment by xiejinglan** [comment]
@iota97 
I tried setting g_Config.iPSPModel=PSP_MODEL_SLIM in retro_init and recompiling it, but it doesn't seem to have any effect, the error message still exists, so I wonder if there is something else that affects this field instead of just changing this field worth it

**Comment by iota97** [comment]
AFAIK that should be it. However if you load a savestate it will reset the PSP model (if I'm not mistaken) so be sure to restart the game and load a game save for testing.

Would be nice to know if it work on standalone version too.

**Comment by unknownbrackets** [comment]
`g_Config.iPSPModel` is processed whenever the CPU is initialized, and can't be changed while emulation is running.  Retroarch isn't really built for emulators as optimized as PPSSPP (it's built for things like the SNES, which is 1% as powerful as the PSP), and runs into lots of conflicts and performance issues.  It might be that timing of updating that value is one of them.

-[Unknown]

**Comment by iota97** [comment]
If that the case I think he could test changing it from here: https://github.com/hrydgard/ppsspp/blob/aeb81c3cb261be2861c97085c0b866953afff1b5/Core/System.cpp#L232

Why does a game check for PSP model for AdHoc anyway? I thought there weren't many difference beside the UMD cache.

**Comment by unknownbrackets** [comment]
Somewhere I've read that the PSP-1000 chipset had issues running the wifi chip while the CPU was clocked at 333 Mhz.  Might've been a voltage issue.

-[Unknown]

**Comment by xiejinglan** [comment]
I've tested setting g_Config.iPSPModel= PSP_MODEL_SLIM in CPU_Init; but still nothing changes.

**Comment by a7150607** [comment]
@unknownbrackets has nay way to fix it?

**Comment by xiejinglan** [comment]
It's my own problem, set in the wrong place！
