### ISSUE TITLE
Can't choose folders on NVIDIA Shield

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#15315]
Should probably report this somewhere else, either to NVIDIA or to Google. Maybe @nic0lette knows something?

This is what I see on my NVIDIA Shield TV when trying to choose a folder, after it upgraded itself to Android 11:

![20220116_172615](https://user-images.githubusercontent.com/130929/149670073-dfbf24aa-8d6b-4149-955f-8b5b6cc44e64.jpg)

It seems this is A-OK, just like on a phone, and it looks like you could pick an existing folder just fine - BUT, arrow key navigation is 100% broken here, so since you don't have touch, you can't navigate this screen - the only thing you can do is to choose New Folder. From there on, everything is OK, but it means you can't take over an existing PSP folder, and also in the game browser, you can't pick a folder to browse, you have to choose ISOs one by one manually using Load...

So it's almost there, but just beyond reach...

Related to #11997

**Comment by BAD-AL** [comment]
One thing to note is that you can plug in a usb mouse and navigate the menus with the mouse for just this screen to get it setup.

**Comment by magearden** [comment]
> One thing to note is that you can plug in a usb mouse and navigate the menus with the mouse for just this screen to get it setup. 

To add to that if you have the Nvidia Shield Remote app on your phone, you can use the trackpad in the app to also navigate the menu to get it set up

**Comment by hrydgard** [comment]
This is fixed in the latest Shield TV update, 9.0.1, although still a bit awkward if you're already in the folder you want (have to back out, then go into the folder, since you can't otherwise reach or see the "Use this folder" button).
