### ISSUE TITLE
Screen Cracking

### ISSUE THREAD

**Issue by juanroman74454811** [hrydgard/ppsspp#15329]
### What should happen

ppsp should have a button where all the screen is broken

### Who would this benefit

Me

### Games this would be useful in

Homebrew Games, Actual sony games, more,

### Other emulators or software with a similar feature

This emulator is so nice.

### Checklist

- [x] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by Gamemulatorer** [comment]
What?

**Comment by ANR2ME** [comment]
I think simulating a broken screen can be done by using post-processing effect

**Comment by juanroman74454811** [comment]
> I think simulating a broken screen can be done by using post-processing effect, but why using a button? and what is the purpose to have your screen cracked?

well the purpose is because i wanna make it so like you just smashed the screen  and then kaboom the screen is broken

**Comment by Panderner** [comment]
@juanroman74454811 is your phone screen's cracked

**Comment by hrydgard** [comment]
I don't understand the purpose of this, and yeah, if you really want the screen to look cracked, develop a post processing effect to do it. Not an interesting feature for PPSSPP.

**Comment by unknownbrackets** [comment]
I took this as a joke; it seems like a nostalgia feature that's about as useful as emulating the XMB user interface.

-[Unknown]

**Comment by hrydgard** [comment]
Yeah probably :)

**Comment by juanroman74454811** [comment]
> @juanroman74454811 is your phone screen's cracked?

no,
