### ISSUE TITLE
Plugin doesn't work properly on android

### ISSUE THREAD

**Issue by Nugss** [hrydgard/ppsspp#15387]
### Game or games this happens in

ULUS10213 - The warriors

### What area of the game / PPSSPP

I use some plugin that allows the right analog to control the camera movement. And for some reason, it doesn't work properly. It works fine on pc but on android when I move the left analog it controls the camera movement while the right analog doesn't work.

Here's my record:

https://user-images.githubusercontent.com/97185681/153262786-9532b90b-b4ac-44a0-b855-f9b952f505a9.mp4

Here's the link of plugin: https://ci.appveyor.com/api/projects/ThirteenAG/widescreenfixespack/artifacts/TheWarriors.PPSSPP.FusionMod.zip

### What should happen

The analog should work properly.

### Platform

Android

### Mobile phone model or graphics card

Oppo a3s

### PPSSPP version affected

V1.12.3

### Last working version

None

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [x] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by Nugss** [comment]
@hrydgard , hello sir, i hope you may notulice it.

**Comment by hrydgard** [comment]
Weird that it would be different between PC and Android, don't have an explanation for that. Same version of PPSSPP on both?

**Comment by Nugss** [comment]
Yes sir, I use the version available from playstore and  the latest git build. Both of them has the same problem.

It's really weird because it works fine on pc but on android I don't know what just happen.

Anyway, I tried to change cpu core to interpreter. I changed it before and it's laggy and slow. But when I use that plugin and and change the cpu core, laggy and slow as I expected and now the camera moves counterclockwise.

Maybe it's depends on CPU??

**Comment by LunaMoo** [comment]
Maybe a silly question, but do you have right analog enabled or custom right analog? Since custom right analog does not use right analog input.

**Comment by Nugss** [comment]
Maybe the CWCheat will work fine for it. I hope someone made it.

**Comment by ThirteenAG** [comment]
@hrydgard I've got a confirmation that it works fine on android:

https://user-images.githubusercontent.com/4904157/155139411-3d2b8b8d-98d0-4814-a710-117df06a9de1.mp4

**Comment by Nugss** [comment]
@ThirteenAG wow it works fine on you sir, but why it doesn't work on mine? I reset/restore the game and PPSSPP sittings and i also try it on other devices and same thing happens.

Maybe the problem is on my installation??

How did you install it sir?

**Comment by ThirteenAG** [comment]
I can't answer that, personally I don't have android. This plugin was made by request of a person who does, and it works for him [on android].

**Comment by ThirteenAG** [comment]
@Nugss I think I've figured out the cause of your problem, redownload plugin. This issue may be closed.

**Comment by Nugss** [comment]
@ThirteenAG it works now, thanks sir👍. I really love this game so much since when i was a kid and this is great for me great work sir thanksss❤️.

I'll close it now.

**Comment by EternalsDarkhole** [comment]
Since this is close now safe to remove from future-prio milestone.
