### ISSUE TITLE
i would like to join

### ISSUE THREAD

**Issue by juanroman74454811** [hrydgard/ppsspp#15395]
### Platform

Windows

### Compiler and build tool versions

Notepad

### Operating system version

20H2

### Build commands used

i dont know

### What happens

idk

### PPSSPP version affected

1.1.2.3

### Checklist

- [x] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] Make sure to run `git submodule update --init --recursive` before building.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try deleting the build directory and running the build again.
- [X] Check GitHub Actions, which builds every merge and PR.
- [X] Include logs and help us reproduce.

**Comment by hrydgard** [comment]
Join what? This doesn't seem like a meaningful issue report, closing.

**Comment by juanroman74454811** [comment]
> Join what? This doesn't seem like a meaningful issue report, closing.

the ppsspp team i want to contribute in it

**Comment by unknownbrackets** [comment]
Start here:
https://github.com/hrydgard/ppsspp/wiki/Build-instructions

The forum or Discord is more appropriate for getting started on contributing than this issues list.  The best thing is to find something you want to fix and try your hand at it.

-[Unknown]
