### ISSUE TITLE
kidousenshi GUNDAM senjou no kizuna save not systemsave

### ISSUE THREAD

**Issue by ipv6hack** [hrydgard/ppsspp#15429]
### Game or games this happens in

kidousenshi GUNDAM senjou no kizuna save not systemsave

### What area of the game / PPSSPP

kidousenshi GUNDAM senjou no kizuna save not systemsave
I'm not good at English
System data save fails when registering the first name of the game

### What should happen

System data save fails when registering the first name of the game

### Platform

Raspberry Pi

### Mobile phone model or graphics card

none

### PPSSPP version affected

2022-02-17T10

### Last working version

2022-02-17T10

### Graphics backend (3D API)

Other

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment]
Might be timing issue.
Have you tried changing I/O Timing Method from System Settings?

**Comment by ipv6hack** [comment]
solved
I made a folder, put it in it, and started it, and it worked for some reason.
thank you

**Comment by ANR2ME** [comment]
> solved I made a folder, put it in it, and started it, and it worked for some reason. thank you

Hmm... might be similar issue to https://github.com/hrydgard/ppsspp/issues/15068 where it failed to create PPCD00001DLS001 folder.
