### ISSUE TITLE
Vulkan doesn't work on adreno v611 drivers yet theres no problems in any others apps 

### ISSUE THREAD

**Issue by Cooley30** [hrydgard/ppsspp#15425]
### Game or games this happens in

Midnight club 3 others 

### What area of the game / PPSSPP

When the gane loads, and I game black screen and glitching 

### What should happen

The msi. Menu should not be bla nk

### Platform

Android

### Mobile phone model or graphics card

Poco F3 adreno v611 driver 

### PPSSPP version affected

V1. 12.3

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by EternalsDarkhole** [comment]
@Cooley30 try to use the latest build of ppsspp from buildbot.
https://buildbot.orphis.net/ppsspp/index.php?m=fulllist

**Comment by Cooley30** [comment]
Tried the new version menu not displaying in vulkan

**Comment by EternalsDarkhole** [comment]
Maybe because you're using a custom gpu?
Poco F3 default gpu is adreno 650 not v611

**Comment by Cooley30** [comment]
Not I'm using adreno 650 custom v,611 drivers , il just stick to open gl
for the mean time performance still good there

**Comment by EternalsDarkhole** [comment]
This is a driver bug not by ppsspp emulator.
![IMG_20220306_224842](https://user-images.githubusercontent.com/37603562/156928372-8874b2b3-c849-4c4e-9541-30ac7dfdf983.jpg)
https://forum.xda-developers.com/t/adreno-driver-for-poco-f3-and-sm8xxx-sm7xxx-sm6xxx.4392655/page-3

**Comment by unknownbrackets** [comment]
I'm going to close this as there's not necessarily much we can do.  I think there's another issue about potentially embedding the latest Adreno driver in PPSSPP to work around people with older drivers, but I don't know that there's a lot we can do about unofficial driver versions with bugs.

That said, if there's more specifics - like specific shader code that's known to be causing a problem, etc. - we could work around.

-[Unknown]
