### ISSUE TITLE
3D support for Oculus Quest

### ISSUE THREAD

**Issue by crtro** [hrydgard/ppsspp#15427]
### What should happen

Currently you can choose to play in "VR" with cardboard support, but it doesn't work for the Quest. Android apps in the Quest look like normal apps, so there needs to be a specific setting to "overlap" the images. Not sure if it's feasible or if it would require working with Oculus APIs.

### Who would this benefit

Everyone that plays PSP via Oculus Quest. It's a rising community, and I predict it will be pretty huge in just a few years.

### Games this would be useful in

All

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
Better VR support would be cool I guess, there was an earlier attempt with OpenVR, which had licensing issues. Now that OpenXR exists, it would be possible to pick this up again.

But I still have a hard time seeing the attraction of running PSP games on Oculus. The controllers aren't that suitable (although I guess you can just hook up a PS/Xbox controller), and the games will never have a large enough field of view to look good in VR. Plus, the stereo effect is likely going to need per-game adjustment. 

Not saying it won't ever happen though!

**Comment by rosts** [comment]
With an Xbox controller it's in my opinion the best way to play emulators. You can resize the "TV" to any size you please, and the resolution on the Quest is great, so it looks very crisp.

I play all my emulation on the Quest now and encourage everyone to try it so they can see how great it looks and works. I really think down the line that it will be very popular as VR keeps growing.

That being said, I have no idea how feasible it is, I just wanted to throw out the idea.

**Comment by unknownbrackets** [comment]
#15901 was just merged and marked as resolving this, so I'm going to close.  It probably needs to be allowed on more platforms, but the initial work is there.  Thanks @lvonasek.

-[Unknown]
