### ISSUE TITLE
Multiplayer offline android 11   

### ISSUE THREAD

**Issue by Alaaaliz** [hrydgard/ppsspp#15436]
### Game or games this happens in

ULES-01596

### What area of the game / PPSSPP

Indonesia 

### What should happen

Play multiplayer offline 

Can't play multiplayer offline hotspot and WiFi
After upgrading phone from android 10 to 11
I tried many phone with android 11 but not contact multiplayer
To play multiplayer hotspot must be on phone how have android 10 or less 9.8.7.6
Any android version work very well
But not android 11 

### Logs

![Screenshot_2022-03-13-01-14-02-98_74c288e31530b9e5d0ca749a600f3e41](https://user-images.githubusercontent.com/101315695/158038250-14bbe76e-6af7-422a-8c3f-735476c57a6d.jpg)

### Platform

Android

### Mobile phone model or graphics card

Realme6i 

### PPSSPP version affected

1.12.3

### Last working version

16/5/2021

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by Alaaaliz** [comment]
Any help

**Comment by Alaaaliz** [comment]
Edit any games not play multiplayer

**Comment by EternalsDarkhole** [comment]
I can play multiplayer in my android 11 via local lan or online using vpn zerotier, maybe you don't know how to set up multiplayer settings properly better to ask on discord of ppsspp :/

**Comment by Alaaaliz** [comment]
> 

I said after upgrading phone to android 11
I doing all setting  the same 
I tried many mobile have android 11 but the same problems  in android 11
If you solve this tell me what I do

**Comment by Alaaaliz** [comment]
> I can play multiplayer in my android 11 via local lan or online using vpn zerotier, maybe you don't know how to set up multiplayer settings properly better to ask on discord of ppsspp :/

I said after upgrading phone to android 11
I doing all setting the same
I tried many mobile have android 11 but the same problems in android 11
If you solve this tell me what I do

**Comment by Alaaaliz** [comment]
> I can play multiplayer in my android 11 via local lan or online using vpn zerotier, maybe you don't know how to set up multiplayer settings properly better to ask on discord of ppsspp :/

Multiplayer offline hotspot Lan
Your mobile android 11 or older

**Comment by ANR2ME** [comment]
Are you using the correct hotspot IP?
On Android 10 or lower the hotspot IP of the phone that do tethering is always 192.168.43.1, but on Android 11 or newer the IP is dynamic 192.168.x.x

And make sure you've followed the guide here https://github.com/hrydgard/ppsspp/wiki/How-to-play-multiplayer-games-with-PPSSPP

**Comment by Alaaaliz** [comment]
> Are you using the correct hotspot IP? On Android 10 or lower the hotspot IP of the phone that do tethering is always `192.168.43.1`, but on Android 11 or newer the IP is dynamic `192.168.x.x`
> 
> And make sure you've followed the guide here https://github.com/hrydgard/ppsspp/wiki/How-to-play-multiplayer-games-with-PPSSPP

I us 192.168.43.1

**Comment by ANR2ME** [comment]
> > Are you using the correct hotspot IP? On Android 10 or lower the hotspot IP of the phone that do tethering is always `192.168.43.1`, but on Android 11 or newer the IP is dynamic `192.168.x.x`
> > And make sure you've followed the guide here https://github.com/hrydgard/ppsspp/wiki/How-to-play-multiplayer-games-with-PPSSPP
> 
> I us 192.168.43.1

This is probably why it doesn't work on Android 11 or newer, because they rarely have this IP when doing tethering.
You should use the IP shown from "Toggle List" button instead of assuming it as `192.168.43.1`

**Comment by Alaaaliz** [comment]
> > > Are you using the correct hotspot IP? On Android 10 or lower the hotspot IP of the phone that do tethering is always `192.168.43.1`, but on Android 11 or newer the IP is dynamic `192.168.x.x`
> > > And make sure you've followed the guide here https://github.com/hrydgard/ppsspp/wiki/How-to-play-multiplayer-games-with-PPSSPP
> > 
> > 
> > I us 192.168.43.1
> 
> This is probably why it doesn't work on Android 11 or newer, because they rarely have this IP when doing tethering. You should use the IP shown from "Toggle List" button instead of assuming it as `192.168.43.1`, which is the wrong IP in your case.

![Screenshot_2022-03-12-23-24-29-58_8ecb18ff21726a42693957ff5a148085](https://user-images.githubusercontent.com/101315695/158111321-6237a595-c19e-426c-89c8-268779892fa0.jpg)

**Comment by Alaaaliz** [comment]
> > > > Are you using the correct hotspot IP? On Android 10 or lower the hotspot IP of the phone that do tethering is always `192.168.43.1`, but on Android 11 or newer the IP is dynamic `192.168.x.x`
> > > > And make sure you've followed the guide here https://github.com/hrydgard/ppsspp/wiki/How-to-play-multiplayer-games-with-PPSSPP
> > > 
> > > 
> > > I us 192.168.43.1
> > 
> > 
> > This is probably why it doesn't work on Android 11 or newer, because they rarely have this IP when doing tethering. You should use the IP shown from "Toggle List" button instead of assuming it as `192.168.43.1`, which is the wrong IP in your case.
> 
> ![Screenshot_2022-03-12-23-24-29-58_8ecb18ff21726a42693957ff5a148085](https://user-images.githubusercontent.com/101315695/158111321-6237a595-c19e-426c-89c8-268779892fa0.jpg)

U mean type IP in mobile Lan setting router

**Comment by ANR2ME** [comment]
You IP seems to be 192.168.43.141
Can you show me the screenshot of the IP list from "Toggle List" button, that shows 192.168.

**Comment by Alaaaliz** [comment]
> > > > Are you using the correct hotspot IP? On Android 10 or lower the hotspot IP of the phone that do tethering is always `192.168.43.1`, but on Android 11 or newer the IP is dynamic `192.168.x.x`
> > > > And make sure you've followed the guide here https://github.com/hrydgard/ppsspp/wiki/How-to-play-multiplayer-games-with-PPSSPP
> > > 
> > > 
> > > I us 192.168.43.1
> > 
> > 
> > This is probably why it doesn't work on Android 11 or newer, because they rarely have this IP when doing tethering. You should use the IP shown from "Toggle List" button instead of assuming it as `192.168.43.1`, which is the wrong IP in your case.
> 
> ![Screenshot_2022-03-12-23-24-29-58_8ecb18ff21726a42693957ff5a148085](https://user-images.githubusercontent.com/101315695/158111321-6237a595-c19e-426c-89c8-268779892fa0.jpg)

This picture for phone have android 10

**Comment by ANR2ME** [comment]
I mean this IP List from PPSSPP, it should shows the correct IP
![image](https://user-images.githubusercontent.com/7974720/158111822-654700bb-42c0-4736-9eab-37cb6817b0c5.png)

**Comment by Alaaaliz** [comment]
> I mean this IP List from PPSSPP, it should shows the correct IP you can use as pro-AdhocSever ![image](https://user-images.githubusercontent.com/7974720/158111822-654700bb-42c0-4736-9eab-37cb6817b0c5.png) And also, please use the latest (top most) dev build from https://buildbot.orphis.net/ppsspp/
> 
> Btw, why are you showing a screenshot of Android 10 where this issue didn't exist, instead of the screenshot of Android 11 where this issue exist?

![Screenshot_2022-03-14-07-53-37-55_74c288e31530b9e5d0ca749a600f3e41](https://user-images.githubusercontent.com/101315695/158113351-edfc18c4-60cc-4f71-b4ee-042b09bd8278.jpg)

This in my phone

**Comment by ANR2ME** [comment]
Please show the IP with 192.168.x.x in the list, scroll it down to the bottom
If you can't find 192.168.43.1 in the list, that means you are using the wrong IP if you are the one who hist the built-in Adhoc Server.

**Comment by EternalsDarkhole** [comment]
@Alaaaliz  You better ask this on discord rather than creating this issue on github this is non sense 😅

**Comment by Alaaaliz** [comment]
> Please show the IP with 192.168.x.x in the list, scroll it down to the bottom (under the `localhost`) If you can't find `192.168.43.1` in the list, that means you are using the wrong IP if you are the one who host the built-in Adhoc Server.

Thanks for your help  you help me to fixed 👍👍👍

**Comment by Alaaaliz** [comment]
> @Alaaaliz You better ask this on discord rather than creating this issue on github this is non sense 😅

Thank you bro you help me problem fixed

**Comment by Alaaaliz** [comment]
> Please show the IP with 192.168.x.x in the list, scroll it down to the bottom (under the `localhost`) If you can't find `192.168.43.1` in the list, that means you are using the wrong IP if you are the one who host the built-in Adhoc Server.

Thanks allot bro ،

**Comment by unknownbrackets** [comment]
Closing this as it seems like a bug.  There's a [forum if you want to discuss things](http://forums.ppsspp.org/), which is better for this sort of thing.

-[Unknown]
