### ISSUE TITLE
[Feature Request] Display a bit more info on game details screen

### ISSUE THREAD

**Issue by NABN00B** [hrydgard/ppsspp#15432]
### What should happen

Since #12646 umd serial and umd version fields can be displayed on game thumbnails. However, there is still no way to view the umd version when you right click on the game to see more information.

Another useful detail would be displaying the exact size of the game in bytes. Currently you need to open the file details through Windows explorer to check this.

It could look something like this:
```
 _______________ 
|               |
|   thumbnail   |
|_______________|

Grand Theft Auto: Vice City Stories
ULUS10160   1.03
location on storage
Size: 1617.4 MB (1 696 006 144)
Savedata: 2.44 MB
Region: USA
```

or 

```
 _______________ 
|               |
|   thumbnail   |
|_______________|

Grand Theft Auto: Vice City Stories
Serial: ULUS10160
Region: USA
Version: 1.03
location on storage
Size: 1617.4 MB (1 696 006 144)
Savedata: 2.44 MB
```

### Who would this benefit

Mostly people who have multiple copies of the same game or are confused about which version of a specific game they have.

### Games this would be useful in

games with multiple versions

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
Version, sure, that we can add and makes sense.

Exact number of bytes, though, seems like a very esoteric need? Of course can add it, but I don't quite understand why it's important.

**Comment by NABN00B** [comment]
> Exact number of bytes, though, seems like a very esoteric need? Of course can add it, but I don't quite understand why it's important.

I thought it would help identifying versions, but upon closer inspection that does not seem to be the case.
It could be used to compare against records in online databases but we already have CRC-32 hash which fulfills this purpose better. Might be useless after all.
