### ISSUE TITLE
The force unleashed- weird visual bug

### ISSUE THREAD

**Issue by Neros858** [hrydgard/ppsspp#15451]
### Game or games this happens in

Star wars: the force unleashed

### What area of the game

From the beginning of the game

### What happens

When ever i swing my lightsaber or use the force the effect is replaced with black trail/smoke

### What should happen

It should look like this
![Screenshot_20220320-024325_YouTube](https://user-images.githubusercontent.com/101955932/159143257-ecef52ea-fc67-4990-b014-68837479f14f.jpg)

### GE frame capture

![Screenshot_20220320-024551_PPSSPP](https://user-images.githubusercontent.com/101955932/159143333-87bc8974-eaea-489b-a7a6-3bf7dbc2f8aa.jpg)
![Screenshot_20220320-024555_PPSSPP](https://user-images.githubusercontent.com/101955932/159143335-abc67fcc-5f73-4e6a-999d-19d3040984bc.jpg)
![Screenshot_20220320-024526_PPSSPP](https://user-images.githubusercontent.com/101955932/159143336-b2fefe2b-0f90-4adc-a51f-ac27f11623ae.jpg)
![Screenshot_20220320-023425_PPSSPP](https://user-images.githubusercontent.com/101955932/159143427-7dfc25dc-5c2d-4b1c-85e1-e2caf4ff0ae6.jpg)

### Platform

Android

### Mobile phone model or graphics card

Android-A51

### PPSSPP version affected

V1.12.3

### Last working version

Never

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by EternalsDarkhole** [comment]
I can't reproduce this on my phone with Mali-G52 gpu also.
Make sure ppsspp is in default settings and also try the latest build of ppsspp.

**Comment by Neros858** [comment]
> try

I found the cause, i had to turn non buffered rendering off, which is quite a shame because without it the game is very laggy...

**Comment by hrydgard** [comment]
Ah, it's indeed required for many games to function, can't get around the speed hit :/  Try frameskipping..

**Comment by EternalsDarkhole** [comment]
> > try
> 
> I found the cause, i had to turn non buffered rendering off, which is quite a shame because without it the game is very laggy...

This game on my phone is only laggy on this area/stage https://github.com/hrydgard/ppsspp/issues/14941
