### ISSUE TITLE
Possible crash issue due to SIGPIPE error on MacOS

### ISSUE THREAD

**Issue by ANR2ME** [hrydgard/ppsspp#15459]
### Game or games this happens in

Any multiplayer games

### What area of the game / PPSSPP

I was testing multiple instance multiplayer on a hackintosh (10.8 Mountain Lion) VM, and PPSSPP crashed after showing Socket error 32 (SIGPIPE) in the log when sending ping packet to AdhocServer.

According to this https://makedist.com/posts/2014/01/16/porting-msg_more-and-msg_nosigpipe-to-os-x/
It seems `MSG_NOSIGNAL` flag  doesn't exist on MacOS, so we may need to use the alternative way, which is the `SO_NOSIGPIPE` socket option.

Not sure, whether this issue also occurred on iOS too or not.

PS: it seems multiple instance doesn't work on MacOS either, since both instance have the same IP (127.0.0.1) probably due to having the same Instance ID

### What should happen

Shouldn't crash due to SIGPIPE error.

### Platform

macOS

### Mobile phone model or graphics card

Apple Software Renderer

### PPSSPP version affected

1.12.3

### Last working version

Not sure, i just noticed it recently

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Unknown's possible fix has been merged (#15467) , can your try the latest build with it when it's up on https://buildbot.orphis.net/ppsspp/ ?

**Comment by ANR2ME** [comment]
I will give this a try, but i might be mistaken about the crash main issue.
Since PPSSPP was able to print the socket error for the SIGPIPE it probably wasn't the source of the crash (otherwise PPSSPP won't be able to print the log)

**Comment by ANR2ME** [comment]
Looks like it's no longer crashing after printing the Socket error 32 in the SCENET Log
![VirtualBox_VB1_04_04_2022_12_11_33](https://user-images.githubusercontent.com/7974720/161478250-6e40063b-d7ac-4bf0-b389-6efb2775d4c8.png)

**Comment by ANR2ME** [comment]
I also notice that closing down the SDL Window using the red button on the top left often cause PPSSPP Window to freeze (forever or a very long time may be), where i need to close down the Log Console window in order to force close the freezing SDL window.
