### ISSUE TITLE
PPSSPP libretro core for RetroArch does not expose WLAN switch

### ISSUE THREAD

**Issue by Junohea** [hrydgard/ppsspp#15461]
### What should happen

The PPSSPP libretro core for RetroArch should have an exposed option to enable the PSP's "WLAN switch" in the same manner the standalone version provides.

The standalone version of PPSSPP has an option to toggle the "WLAN switch" state
Settings > Networking > "Enable networking/WLAN"
![image](https://user-images.githubusercontent.com/13029766/160466066-bd2ab8c3-d77e-4aa7-8cb2-22551ab904ea.png)

Games such as Phantasy Star Portable 2 require this value and will show it in-game (PPSSPP standalone with networking enabled)
![image](https://user-images.githubusercontent.com/13029766/160466182-db1655e5-158f-4645-832b-4ba0e5449a4c.png)

...and will not allow you to proceed if they do not detect the WLAN switch as enabled 
(shown: PPSSPP libretro core in RetroArch, all available netplay or networking options produce the following)
![image](https://user-images.githubusercontent.com/13029766/160470936-a635c291-164f-4794-b33d-90c9ab8a6ee1.png)
![image](https://user-images.githubusercontent.com/13029766/160467542-4395cda4-cd4e-43be-82c2-2a5a9c548b97.png)

- [x] This issue has shown up previously but was closed at the time
https://github.com/hrydgard/ppsspp/issues/2201
- [x] Tested latest nightly PPSSPP core in RetroArch. Also tested a few different older builds of the PPSSPP core.

### Who would this benefit

Anyone that would like to use RetroArch to play PSP games, specifically for games that perform checks against the state of the WLAN switch

### Platform (if relevant)

libretro / Retroarch

### Games this would be useful in

ULUS-10529 - Phantasy Star Portable 2, NPJH-50332 - Phantasy Star Portable 2 Infinity

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by johannes21j** [comment]
when i open the game it is normal when i play it kick me out then i delete Textures configuration setting then it stop kick me out please help

**Comment by BunnyCinnamon** [comment]
I don't know the difference between libreto core and standalone, but I would assume networking is something only the standalone launcher can do?

**Comment by ANR2ME** [comment]
is this still an issue after https://github.com/hrydgard/ppsspp/pull/15538 ? probably already fixed right?

**Comment by hrydgard** [comment]
Indeed that should do it, closing.
