### ISSUE TITLE
Reading game files from folder

### ISSUE THREAD

**Issue by Leafdomain** [hrydgard/ppsspp#15462]
### What should happen

It would be nice if the emulator could read the extracted files of a game from a folder instead of a rom, i.e., run the game from a folder instead of a iso.

### Who would this benefit

The reason for this would be easy modding, being able to access and switch files fast etc.

### Platform (if relevant)

Windows

### Games this would be useful in

any

### Other emulators or software with a similar feature

I know the iso has the files in a certain order and it needs to be like that in order to be read by the emulator. But maybe there can be a way to generate a file list or something for the emulator to read.

For the Gamecube, the files also need to be like that, but yet Dolphin can read game files from a folder and run the game.

So I would hope that maybe PCSX2 can do it as well.

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by unknownbrackets** [comment]
The emulator already can, but I'm not sure it's doable on Android.

On desktop platforms, simply select File -> Open directory... and choose the folder containing the files extracted from the ISO.

Many games may expect files to be in very specific positions within the ISO (some games hardcode this within the game binary), so indeed an index file is also supported.  This tool can be used to generate that index from an ISO:
https://github.com/unknownbrackets/ppsspp-virtfs-tools/tree/master/gen-index

You can also add dll (Windows) or so (Linux) files to the index, to hook access to those files and handle them specially.  This can be useful if the game has an archive file you want to modify: your hook could generate the archive on the fly from underlying files.  See here for a basic example:
https://github.com/unknownbrackets/ppsspp-virtfs-tools/tree/master/passthru

For more questions around this, I'd recommend posting on the forum.

-[Unknown]
