### ISSUE TITLE
Texture dumping is much slower in 1.12 vs 1.11 on Android (scoped storage)

### ISSUE THREAD

**Issue by kongmao45678** [hrydgard/ppsspp#15478]
### Game or games this happens in

all games

### What area of the game

all games

### Platform

Android

### Mobile phone model or graphics card

redmi K20P

### PPSSPP version affected

1.12

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try changing graphics settings to determine if one causes the slowdown.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Sorry, do you mean when dumping textures is enabled? Could be due to how we're now forced to use "scoped storage" on Android, though there's plenty to improve here (we could write textures to disc asynchronously)..

**Comment by kongmao45678** [comment]
yes,dumping textures is enabled.1.12 is very stuck, 1.11 is normal, what is the solution?

**Comment by hrydgard** [comment]
Wait for me to see if we can improve performance I guess.. Probably no immediate solution :(

**Comment by hrydgard** [comment]
#15487 + #15489 should have improved this noticeably.

Don't think there are any more "easy" gains to be had, so moving any additional work on this to a later milestone.

**Comment by unknownbrackets** [comment]
Is performance good / about the same as before?  If this is resolved by those changes, even better to close it.

-[Unknown]

**Comment by kongmao45678** [comment]
Thanks, it's alright.
