### ISSUE TITLE
(UWP) Crashes When Trying To Load Any Game from usb

### ISSUE THREAD

**Issue by dominater01** [hrydgard/ppsspp#15479]
### Game or games this happens in

all

### What area of the game / PPSSPP

ppsspp crashes when loading an iso or cso etc. this issue happens on both xbox and windows 11 when loading an iso from a usb

internal ppsspp location seems to work fine

### What should happen

it should load and not crash

### Platform

Windows

### Mobile phone model or graphics card

NVIDIA Geforce GTX 1060

### PPSSPP version affected

v1.12.3

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by Gamemulatorer** [comment]
Duplicate
https://github.com/hrydgard/ppsspp/issues/15346
