### ISSUE TITLE
Texture dumping broken when texture upscaling is enabled

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#15488]
As it says on the tin, the math goes wrong. Should be a pretty simple fix.

**Comment by unknownbrackets** [comment]
Originally, it definitely did work, and it could be used to save upscaled textures to reduce CPU usage.  Maybe this is only when GPU upscaling is used?  Or in all cases?

-[Unknown]

**Comment by hrydgard** [comment]
tbh I only tested on top of #15487 , but did seem broken in both cases. Ran out of time to look into it today but will soon.

**Comment by unknownbrackets** [comment]
Right, there's already code to save the original size when using a shader for upscaling.  Both paths seem to be working on Windows with Vulkan.

-[Unknown]

**Comment by hrydgard** [comment]
Gonna close this, doesn't seem to be an issue.
