### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by Washong** [hrydgard/ppsspp#15497]
### Game or games this happens in

No Game

### What area of the game / PPSSPP

Help me I was hacked I think and I got banned btw this is LunaMoo
![gdhr0fj9k8u51](https://user-images.githubusercontent.com/104286034/164953977-31913059-5978-4f4b-a3d8-d293d296029d.jpg)

### What should happen

Idk

### Logs

nothing

### Platform

Android

### Mobile phone model or graphics card

None

### PPSSPP version affected

noyb

### Last working version

None

### Graphics backend (3D API)

Other

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
This appears to be some attempted scam.  Thanks as well for the heads up, @Margen67.  Closing as irrelevant.

-[Unknown]
