### ISSUE TITLE
Wipeout Pulse crashing on opening movie

### ISSUE THREAD

**Issue by stuken** [hrydgard/ppsspp#15492]
### Game or games this happens in

UCES-00465

### What area of the game / PPSSPP

#15489 has caused a regression on loading wipeout pulse under vulkan with a crash just as it displays the opening movie.

It's dying at PPSSPPDebug64.exe!CopyAndSumMask32(unsigned int * dst, const unsigned int * src, int width, unsigned int * outMask) Line 759
	at C:\Users\Stuart\Documents\GitHub\hrydgard\ppsspp\GPU\Common\TextureDecoder.cpp(759)

Root cause is PPSSPPDebug64.exe!TextureCacheVulkan::LoadTextureLevel(TexCacheEntry & entry, unsigned char * writePtr, int rowPitch, int level, int scaleFactor, VkFormat dstFmt) Line 978
	at C:\Users\Stuart\Documents\GitHub\hrydgard\ppsspp\GPU\Vulkan\TextureCacheVulkan.cpp(978)

getTextureAddress is getting called with level = 1, gstate is returning 0 and everything falls over.

Reproducable on windows, linux with all default settings.

### What should happen

Display opening movie and continue on.

### Platform

Windows

### Mobile phone model or graphics card

rtx3090, steam deck

### PPSSPP version affected

83b8211abf

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Thanks for reporting, I'll have a look soon!

**Comment by hrydgard** [comment]
Got a fix incoming, #15493.
