### ISSUE TITLE
(Xbox/UWP) Broken Menu.

### ISSUE THREAD

**Issue by GABO1423** [hrydgard/ppsspp#15496]
### Game or games this happens in

None.

### What area of the game / PPSSPP

When booting up PPSSPP, the menu is completely broken and very difficult to navigate. This was caused by commit https://github.com/hrydgard/ppsspp/commit/13fcff328ca9cdb5f581f84258b56bccd81fa2a7.

Before:
![4-23-2022_10-38-07_PM-fnfstqsb](https://user-images.githubusercontent.com/35014183/164953725-0d816155-1b76-4a54-aeaf-2f844195e8d1.png)

After:
![4-23-2022_9-41-33_PM-e0gwrplx](https://user-images.githubusercontent.com/35014183/164952243-e06777d1-7b02-432a-947f-8b73288783db.png)

### What should happen

The menu should be more than a black abyss with no cursors.

### Platform

Other

### Mobile phone model or graphics card

Xbox Series X GPU (SraKmd_arden Vendor)

### PPSSPP version affected

v1.12.3-1093-g13fcff328

### Last working version

v1.12.3-1091-g3d4c4aa5b

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Weird, it seems to work fine on PC... Wonder what broke.

@iota97 , any ideas?

**Comment by hrydgard** [comment]
Never mind, it's broken on Windows as well, I just hadn't properly updated.

I'll take a look

**Comment by hrydgard** [comment]
OK, fix committed, please test.

**Comment by GABO1423** [comment]
@hrydgard Saw the commit, that was fast!
I just woke up so I might take a bit of time making a build to test it. I'll get back to you as soon as possible.

**Comment by GABO1423** [comment]
I can confirm this issue is now fixed. Thanks again!
![4-24-2022_5-53-11_PM-xj1ymrxy](https://user-images.githubusercontent.com/35014183/164998227-bf09f77d-04a0-4732-b31c-ea644c2b109e.png)
