### ISSUE TITLE
3rd birthday blue icon graphic bug

### ISSUE THREAD

**Issue by bwitch** [hrydgard/ppsspp#15506]
### Game or games this happens in

ULUS-10567 - Parasite Eve 3rd Birthday

### What area of the game

After new game / any time.

### What happens

When I overdive the icons stay on the screen.

### What should happen

Soldiers icons don't stay on the screen like that.

### GE frame capture

![01](https://user-images.githubusercontent.com/58442111/165305396-70e2261a-213c-47a6-a867-80e6bc44cca8.png)

### Platform

libretro / Retroarch

### Mobile phone model or graphics card

NVIDIA GeForce 540M

### PPSSPP version affected

The latest version core retroarch.

### Last working version

I don't know if there is a version that works better.

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [ ] Include logs or screenshots of issue.

**Comment by bwitch** [comment]
**PPSSPP 6227537 // translate LIGADO = ON // DESLIGADO = OFF |
I tried to change between them but it didn't work.. My settings:**
![001](https://user-images.githubusercontent.com/58442111/165307398-fa025676-5f42-4568-9602-9503f44d28fa.png)
![002](https://user-images.githubusercontent.com/58442111/165307414-014ed44c-4516-4c5f-9b28-694696f7a640.png)

**Comment by Gamemulatorer** [comment]
***Disable Slower Effects*** is the cause of the issue see 👉https://github.com/hrydgard/ppsspp/issues/11092#issuecomment-392821212

**Comment by bwitch** [comment]
> I would expect this to happen with "Disable slower effects" enabled. Turning it off won't immediately stop it, you have to have it off the whole time. You also don't want retain changed textures.
> 
> If that doesn't help, does this happen in PPSSPP proper? Retroarch has a lot of limitations because it was designed for weaker systems (the PSP is ~93x as powerful as a SNES, ~10x as a PS1), and naturally has more bugs, worse performance, and missing features as a result.
> 
> -[Unknown]



> _**Disable Slower Effects**_ is the cause of the issue see 👉[#11092 (comment)](https://github.com/hrydgard/ppsspp/issues/11092#issuecomment-392821212)

thank you guys problem solved, I needed to restart to become active.
