### ISSUE TITLE
MGS:PW - Graphic Bug (Android/Windows)

### ISSUE THREAD

**Issue by Saramagrean** [hrydgard/ppsspp#15519]
### Game or games this happens in

Metal Gear Solid: Peace Walker (ULUS-10509)

### What area of the game

Can notice in Mother base screen. It happen in Vulkan backend only. (OGL & D3D is woke fine)

### What happens

Missing dialogue new recruit.

![MGS-PW-1084](https://user-images.githubusercontent.com/26355472/166253801-dcb8bbed-a13b-4ea5-aa02-eca0bbcd9633.png)

### What should happen

Graphics should rendering correct like in v1.12.3 Build 102 (Last Work).

![MGS-PW-102](https://user-images.githubusercontent.com/26355472/166254072-46679860-c83a-41ed-b2d0-d04779faccce.png)

### GE frame capture

Windows: [DUMP.zip](https://github.com/hrydgard/ppsspp/files/8608728/DUMP.zip)
Android: [DUMP.zip](https://github.com/hrydgard/ppsspp/files/8619699/Dump.New.Recruit.zip)

### Platform

Windows

### Mobile phone model or graphics card

- Windows 10 (x64), Intel i5 6200U, Intel HD Graphics 520 (with latest graphic driver include Vulkan v1.3.205).
- Redmi Note 8 (Snapdragon 665, Adreno 610, Android 13 Beta 1, Vulkan v1.1.128).

### PPSSPP version affected

v1.12.3-113-ga3a6bdc19.	

### Last working version

v1.12.3-102-ga9d7948f7.

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Curiously, the range points to #15069 ...

**Comment by hrydgard** [comment]
Can you try to re-upload the frame capture? Seems to have failed (saved the post before it was finished).

**Comment by Saramagrean** [comment]
Done. :)

**Comment by LunaMoo** [comment]
Maybe new versions triggers some driver bug. I can't reproduce on windows with nvidia using vulkan.
![menu](https://user-images.githubusercontent.com/5485237/166429952-67a27978-5d2c-49e6-988d-59be97944b08.png)

**Comment by hrydgard** [comment]
Hm. Here's what the framedumps look like for me:

First four look about like this:

![image](https://user-images.githubusercontent.com/130929/166434402-fd933709-6f49-4092-9680-80b6a4c376d1.png)

Fifth:

![image](https://user-images.githubusercontent.com/130929/166434440-fc0063e2-d3db-422c-89a6-c44110096d39.png)

Regardless of backend.

**Comment by Saramagrean** [comment]
First four - when replay frame dump file, I got same result as above too. (on All backends).

Fifth - It's look like this (happen in Vulkan only).
![MGS-PW-1140](https://user-images.githubusercontent.com/26355472/166437298-132eb373-42df-4652-9145-c9493d7b568a.png)

**Comment by Saramagrean** [comment]
Try reset settings again. graphic is rendering correct (no giltchs), except missing some textures in new recruit has joined screen.

Example video.
https://youtu.be/TIxeUe0qpRU

**Comment by Saramagrean** [comment]
Graphics rendering correctly after turn off Hardware Transform.

![DHWT](https://user-images.githubusercontent.com/26355472/180998294-117130e7-e105-4ce5-97e0-e7240042d3ae.jpg)

**Comment by Gamemulatorer** [comment]
HW Transform is kinda buggy on vulkan backend..

**Comment by unknownbrackets** [comment]
This might be helped by #15870.

-[Unknown]

**Comment by Saramagrean** [comment]
Confirmed, it fixed on both Android/Windows.
