### ISSUE TITLE
Tales of Phantasia Cross Edition: missing some layers in vulkan on MTK device

### ISSUE THREAD

**Issue by leoxxx** [hrydgard/ppsspp#15526]
### Game or games this happens in

ULJS00293 Tales of Phantasia Narikiri Dungeon X 

### What area of the game

All

### What happens

Missing some layers.

![2022-05-08-15-36-08](https://user-images.githubusercontent.com/5364709/167287635-58a2072e-dfdb-4566-a32f-3b6c50a1189e.png)
![2022-05-08-15-36-21](https://user-images.githubusercontent.com/5364709/167287626-744dd9fa-312d-46a8-837d-b2b4078ef324.png)

Tales of Phantasia Cross Edition is inclueded in Tales of Phantasia Narikiri Dungeon X.
Error in vulkan, but O.K. in opengl on my MTK device. 
It's O.K. in vulkan on my Snapdragon(855) device and PC.
Tales of Phantasia Narikiri Dungeon X is O.K. in vulkan.

### What should happen

![1](https://user-images.githubusercontent.com/5364709/167288142-1996f517-557a-4d69-92c8-c32d3c9c3ae6.png)
![2](https://user-images.githubusercontent.com/5364709/167288147-2cb9eee0-ed9d-4f2e-ade4-4d7d59b0ae66.png)

### Platform

Android

### Mobile phone model or graphics card

Helio X20 (MT6797+Mali-T880 MP4) Android Tablet

### PPSSPP version affected

V1.12.3

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by Gamemulatorer** [comment]
Might be related to https://github.com/hrydgard/ppsspp/issues/12890

**Comment by leoxxx** [comment]
Maybe.
Tales of Phantasia Full Voice Edition
Tales of Phantasia Cross Edition
They are not same.

**Comment by Gamemulatorer** [comment]
How about the latest build
https://buildbot.orphis.net/ppsspp/

**Comment by leoxxx** [comment]
g045709dbc still error.

**Comment by Gamemulatorer** [comment]
Can you upload ge dump
https://ppsspp-debugger.unknownbrackets.org/gpu

**Comment by leoxxx** [comment]
[148552195.zip](https://github.com/hrydgard/ppsspp/files/8649426/148552195.zip)

**Comment by leoxxx** [comment]
I found the sound more lag in opengl. It's better in vulkan on my android device. It's O.K. in PC.

**Comment by hrydgard** [comment]
I believe this to indeed be the same issue as #12890, and actually also #13833. 

I'm preparing a workaround, still considering whether to apply widely or only on 

In the meantime, can you check in Settings / Tools / System Information for Driver Version under the GPU Information section?

It should be something like 16.0.0 .

**Comment by leoxxx** [comment]
![2022-05-09-16-00-25](https://user-images.githubusercontent.com/5364709/167367258-41ceeeeb-368e-46ac-9caa-0fad174e94d9.png)
![2022-05-09-15-59-38](https://user-images.githubusercontent.com/5364709/167367167-14168adc-44bb-4222-85f0-a4a198dcb9d8.png)

a hash

**Comment by hrydgard** [comment]
Thanks, that's means it's one of the older drivers from before ARM started to report proper version numbers. That I can easily detect, so that's good to know.

**Comment by leoxxx** [comment]
@hrydgard 
Can add a feature for export the information to txt?
I think it's helpful to report issue.

**Comment by hrydgard** [comment]
Not a bad idea! Thanks for mentioning it, will get it done at some point.

That's quite an unfortunate refresh rate by the way, 57.250 Hz...

**Comment by leoxxx** [comment]
Haha, it's a imitation. Called it "山寨货" in my country.
So, don't mind it.

**Comment by hrydgard** [comment]
This should be fixed now that #15611 is in, please test on your device.

**Comment by leoxxx** [comment]
ge942ba680 still error.

**Comment by hrydgard** [comment]
@leoxxx  what is your device? Can you post a system info screenshot just like Gamemulatorer?

**Comment by Gamemulatorer** [comment]
> [148552195.zip](https://github.com/hrydgard/ppsspp/files/8649426/148552195.zip)

Can you try to upload again a ge dump that is readable via ppsspp.

**Comment by leoxxx** [comment]
@hrydgard 
It' O.K. in v1.13.1.
