### ISSUE TITLE
About modifying native resolution

### ISSUE THREAD

**Issue by clondy999** [hrydgard/ppsspp#15539]
### Game or games this happens in

Any game

### What area of the game / PPSSPP

I have a TV box. Its CPU is Amlogic 812 with a resolution of 1920x1080. I found that the game was stuck, and then I replaced 1280x720. I was surprised to find that the game ran smoothly, but now my box has a problem after changing the resolution of 1280x720. It won't be full screen. I want to manually modify the source code of ppsspp and directly change it to 1280x720. Where should I change it? I have successfully compiled ppsspp

### What should happen

The effect I want is: the Android system is 1920x1080 (because I can have a full screen), and ppsspp runs at a resolution of 1280x720

### Platform

Android

### Mobile phone model or graphics card

Amlogic 812

### PPSSPP version affected

v1.12.3

### Last working version

null

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment]
1280x720 should be the same as using Rendering Resolution of 2.6, so why not changing the Rendering Resolution to 2 or 3 instead of Auto?

**Comment by clondy999** [comment]
Do you mean to change the local resolution to 2x PSP?

**Comment by ANR2ME** [comment]
not sure what is "local resolution", but probably yes, 2x PSP or 3x PSP
![image](https://user-images.githubusercontent.com/7974720/168474417-de309af5-d5a5-49ef-9c0a-346f52264bec.png)

**Comment by clondy999** [comment]
I've always been a 2x PSP here
At present, my situation is that when the resolution of Android is 1280x720, I can run the game smoothly
But when my android resolution was 1920x1080, I was slow to run the game

**Comment by unknownbrackets** [comment]
On Android there are two settings:

Rendering resolution - affects the rendering speed and VRAM requirements
Display resolution (HW scaler) - affects the blitting time

If I understood correctly, you have rendering resolution set to 2x PSP.  Have you tried changing the display resolution in PPSSPP?  On newer Android or Android TV, it defaults to "Native device resolution" which means it'll change to 720p if your device is set to 720p.  You might try "Auto" or "2x PSP".  This may give you the same performance without having to have your display actually set to 720p.

-[Unknown]

**Comment by ANR2ME** [comment]
Ah Display Resolution, that is probably what @clondy999 is looking for :) i didn't aware of such settings before.

Btw, what happen when Rendering Resolution being set to Auto(1:1) and Display Resolution also set to Auto?
Auto on Display Resolution seems to refer to Rendering Resolution, but what was the Auto(1:1) on Rendering Resolution refer to? was it Native resolution?

**Comment by unknownbrackets** [comment]
I'm going to assume the above helped since there hasn't been any feedback.

If you're still seeing something you think is a bug, please comment with more detail.  If you want to discuss or have more questions, the best places are Discord or [the forum](forums.ppsspp.org/).

-[Unknown]
