### ISSUE TITLE
Can't delete iso in sdcard on android

### ISSUE THREAD

**Issue by leoxxx** [hrydgard/ppsspp#15532]
### What happens

Click delete, the iso still exisit.

### Platform

Android

### PPSSPP version affected

v1.12.3

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by Gamemulatorer** [comment]
Full spicefications of your android phone? like android version?

**Comment by leoxxx** [comment]
android 7.1.1

**Comment by ANR2ME** [comment]
Please try the latest dev build to see whether this issue has been fixed or not, from https://buildbot.orphis.net/ppsspp/

**Comment by leoxxx** [comment]
Haha, don't worry. It will be confirmed after you click delete.

**Comment by leoxxx** [comment]
gb93be29a3 still error.
Suggestion, change android revision package name. It can't be installed on andriod directly because the signature isn't same as release's signature.  I have to uninstall realease, then install revision.Changing package name can install both revision and release.

**Comment by leoxxx** [comment]
Delete iso is O.K. in windows.

**Comment by unknownbrackets** [comment]
Maybe this is related to scope storage in some way.  Did it work in PPSSPP v1.11.x on the same device?

-[Unknown]

**Comment by leoxxx** [comment]
1.10 1.11 1.11.3 all error.

**Comment by Gamemulatorer** [comment]
I cannot reproduce this on my phone with android lollipop and android red velvet cake.

**Comment by Gamemulatorer** [comment]
Can still reproduce this issue?

**Comment by leoxxx** [comment]
Yes. My android 9 device is O.K. It's no TF card. But 7.1.1 device still error. It has a TF card, my iso in the TF card.

**Comment by Gamemulatorer** [comment]
> Yes. My android 9 device is O.K. It's no TF card. But 7.1.1 device still error. It has a TF card, my iso in the TF card.

If you use your tf card in your android 9 and delete iso then what's happen?

**Comment by leoxxx** [comment]
This device can't install TF card, so I don't know.

**Comment by leoxxx** [comment]
So strange, it's O.K on my 4.4.4 device. I give it up.

**Comment by unknownbrackets** [comment]
There have been a few people using versions in that range reporting strange issues with storage, such as #16590.  Not sure what's going on.

-[Unknown]
