### ISSUE TITLE
PPSSPP is skipping the first press of a circle button after unpausing the game.

### ISSUE THREAD

**Issue by Hasster1** [hrydgard/ppsspp#15530]
### Game or games this happens in

Anything. Even homebrews.

### What area of the game / PPSSPP

After pausing and unpausing the game, PPSSPP skips the first press of a circle button. 
It seems that config doesn't matter. 
The input method doesn't matter as well, because i have tried it on my keyboard and gamepad.

And the worst thing, is that it's even present in stable versions starting from 1.12. It's not present in 1.11.3.

### What should happen

The button shouldn't be skipped.

### Logs

Do you really need them?

### Platform

Windows

### Mobile phone model or graphics card

Nvidia GeForce 840m

### PPSSPP version affected

Since 1.12. It might've happened somewhere between 1.11.3 and 1.12.

### Last working version

1.11.3

### Graphics backend (3D API)

Other

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [x] Include logs or screenshots of issue.

**Comment by Hasster1** [comment]
Quitting the pause menu using the circle button does not trigger the skipping.

**Comment by Hasster1** [comment]
No wait, it's not really skipping, it's just delaying the press of a button

https://user-images.githubusercontent.com/20757715/167585273-c3d74640-8a9e-4119-879b-e985ab8133cb.mp4

.

**Comment by unknownbrackets** [comment]
It'd help if you could test git builds between v1.11.3 and and v1.12.  Unfortunately, it seems like the builds are gone, but if you're willing to try with Visual Studio (don't worry, you don't need to be a programmer), see here:
https://github.com/hrydgard/ppsspp/wiki/How-to-bisect-to-find-what-broke-a-game

If you try one version half way between, it'll narrow down the possible causes by half.  I know there were changes to the control mapping screen in v1.12.x, but I don't remember any that would've affected keyboard input.

In case compiling isn't an option, another thing that might help to verify is trying an even older version, such as v1.9.3: http://ppsspp.org/downloads_all.html#windows

That might at least confirm if there's something flaky or more complex at play here.

-[Unknown]

**Comment by Hasster1** [comment]
Yes, i would like to help with that. The faster this issue gets fixed, the easier it will be for me to play some patapons. I'll try my best.

**Comment by Hasster1** [comment]
Using git bisect i found out that
v1.11.3-1357-gab4dcebd5
Broke it.

v1.11.3-1353-gc8204a24e
Is the last build where this bug does not happen.

In 1353, the selection is staying after you quit the menu and go back into the menu, while in 1357 it automatically disappears once you leave the menu.

**Comment by hrydgard** [comment]
That means it's #14841 . Maybe the view eats a keypress somehow? Should be fixable with a bit of investigation..

**Comment by unknownbrackets** [comment]
Ah, I see.  When a child view switches back to EmuScreen, we're not calling `UI::EnableFocusMovement(false);`, only when creating a new view.  My bad.

-[Unknown]

**Comment by unknownbrackets** [comment]
I think #15560 fixes this, but I don't know what's going on with any delay, so if you could try that build once it's done (under Checks -> Artifacts) or a build after it's merged, that'd be helpful to confirm this is fixed.

Thanks for narrowing down the range.  As you can see, it's extremely helpful to figure out a fix (sometimes it's still hard, but it always helps.)

-[Unknown]

**Comment by Hasster1** [comment]
Yup! It's fixed now!
The delay is probably another small bug or might not be a bug at all, it only happens on the keyboard, and only when you hold the circle button to exit the pause menu - it autopresses the circle button after a second, unlike a gamepad, which does not autopress the circle button.
