### ISSUE TITLE
Broken lines in Echochrome.

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#15556]
### Game or games this happens in

UCES-01011 - Echochrome

### What area of the game

During in-game the lines disappear when rotating the camera.

### What happens

This how looks like in Latest Build:
![Screenshot (54)](https://user-images.githubusercontent.com/37503397/170419480-19608f5c-a29b-4e41-a4d5-460d50e85f4d.png)

### What should happen

This how it looks like in stable v1.12.3:
![Screenshot (52)](https://user-images.githubusercontent.com/37503397/170419593-877c5c24-c159-4195-91d2-0929d84040b4.png)

And it looks like for Vulkan v1.12.3:
![Screenshot (53)](https://user-images.githubusercontent.com/37503397/170419668-201c4cf6-5c65-449a-bd64-922d79ebeb85.png)

### GE frame capture

[recording.zip](https://github.com/hrydgard/ppsspp/files/8776429/recording.zip)

### Platform

Windows

### Mobile phone model or graphics card

NVIDIA GTX 1050Ti

### PPSSPP version affected

Latest Builds

### Last working version

Since v1.12.3-136-g17d807197

### Graphics backend (3D API)

Other

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment]
Is this issue only occurred on vulkan or all of renderer backends?

**Comment by Panderner** [comment]
Latest Build Vulkan:
![Screenshot (55)](https://user-images.githubusercontent.com/37503397/170479285-60cf5738-f0de-4882-a18d-0a4727b9505a.png)

V1.12.3 Vulkan:
![Screenshot (56)](https://user-images.githubusercontent.com/37503397/170479334-6a7830fa-a644-4af9-8e89-a88f736b1cf2.png)

Prior to v1.12.3-136-g17d807197 the lines are thicker in Vulkan than other backends.

**Comment by hrydgard** [comment]
As mentioned in #8276, we changed the line drawing algorithm to one that gave more accurate results in some games (by splitting lines into triangles manually instead of using native GPU lines, which aren't always available in wide versions), but apparently not in this one. Might be a bug that only happens with reversed viewports, or only with certain diagonals. Will look into it.
