### ISSUE TITLE
Black Screen in Dragon Ball Z Tenkaichi Tag Team while using Skip buffer effects

### ISSUE THREAD

**Issue by MajinDipu** [hrydgard/ppsspp#15610]
### Game or games this happens in

ULES01456 - Dragon Ball Z Tenkaichi Tag Team

### What area of the game

Upon booting the game the screen is pitch black and it remains black the whole time. You can clearly hear the audio tho.

### What happens

The game ULES01456 - Dragon Ball Z Tenkaichi Tag Team is facing black screen problem in latest dev builds using Skip buffer effects. Audio can be heard. It works fine on stable 1.12.3 build. Using buffered rendering is no good as this is one of those games that is darkish during matches using buffered rendering. Not uploading pics as you can imagine what black screen means.

### What should happen

It should work fine duh. I just want it fixed before the next stable release so it will make me cry less. 

### Platform

Android

### Mobile phone model or graphics card

It is happening on all platform and on all devices. I already tested on multiple device,

### PPSSPP version affected

1.12.3-1156-g4423.... (Definitely happens on newer ones too)

### Last working version

1.12.3 stable (as far as I know)

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
The game should not be dark in buffered rendering, it should work correctly with outlines and has in the past. Does it not on your device?

**Comment by ANR2ME** [comment]
The US version (ULUS10537) didn't have black screen issue with "Skip buffer effects" tested on v1.12.3-1272 on all backend on Android and Windows.

Is this issue only affects the EU version?
Or may be "Skip buffer effects" no longer working properly when combined with other settings?
Have you tried resetting the settings to default and only changed to "Skip buffer effects" (leaving the rest as default)?

**Comment by unknownbrackets** [comment]
Are you using "host" IO mode?  Without that, emulation behavior shouldn't be any different with remote disc streaming or not.  That said, there may be stalls while it downloads content.

"Host" will make it probably show loading screens like a PSP would if the disc was seeking, but could mean bugs that only happen during remote disc streaming.

"Fast" should make emulation work the same way, but maybe drop frames or lag a bit while data is being transmitted over the network.

If your network connection is poor and data can't be transmitted even after multiple retries, you might also get different emulation behavior since the data simply won't be available.  It doesn't hang indefinitely for unlimited retries until it gets the data, and will log an error message in that case.

-[Unknown]

**Comment by ANR2ME** [comment]
Ah yes, i was using Host, changing it to Fast worked better now.

Btw, as i remembered when i was testing multiplayer(Android vs Windows) with 200ms simulated latency using `clumsy a few days ago`, remote disc keeps showing "Bad request" in the logs. 
How does latency causes Bad request? the packet shouldn't be corrupted with simulated latency, especially on TCP.

**Comment by MajinDipu** [comment]
> 

Only the gameplay is dark in buffered rendering. Everything else works fine. Skip buffer effects cause black screen with working audio right from the get go. Also why is it android platform specific? Same things happen on Windows 10 too

**Comment by hrydgard** [comment]
That just doesn't seem to match up with other reports. You likely have a broken ISO or some weird setting or cheat code enabled, since all other reports are saying that the game works fine on both Android and PC, without any darkening ingame.

**Comment by unknownbrackets** [comment]
Maybe it's related to "disable slower effects"?  Or maybe a post-shader is enabled?

-[Unknown]

**Comment by MajinDipu** [comment]
Ahh man. Sorry for wasting your time. It's working fine in the very latest dev build. There were several dev builds in continuous succession which had this issue but not anymore
