### ISSUE TITLE
UWP - (Feature Request) Add ability to change games directory within the PPSSPP menu.

### ISSUE THREAD

**Issue by Player1LoginXBOX** [hrydgard/ppsspp#15616]
### What should happen

This is currently only possible by editing the ini to read the games directory from the external HD location. A menu option to read the games list from the external HD would be nice QOL feature. Saving to External HD would also be a plus addition it currently requires saving to local state on UWP platform.

### Who would this benefit

All users would be able to easily change the games directory showing all images and music easily rather than having to edit the ini.

### Platform (if relevant)

Other

### Games this would be useful in

All

### Other emulators or software with a similar feature

Xbox

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
Is there a list of fixed paths that will be the same on every Xbox that we could pop up, in place of the Browse button that we show on other platforms?

**Comment by Player1LoginXBOX** [comment]
> Is there a list of fixed paths that will be the same on every Xbox that we could pop up, in place of the Browse button that we show on other platforms? What paths do you usually put in your ini?

For developer mode the directory path would be E drive...However on the retail version (more popular) it would be the D drive.

[Ex. Flycast has an option where you can load (browse) from external like PPSSPP currently offers but it also has the ability to change the directory path to any open directory.]

**Comment by Player1LoginXBOX** [comment]
This may be Flyinghead's code for directory listing info.
"it basically replace fopen globally with a "uwp-friendly" version"

https://github.com/flyinghead/flycast/blob/05961ac8837da2299383c2fdd55ad4fff44f758d/core/windows/winmain.cpp#L777

**Comment by hrydgard** [comment]
I'm really just looking for exact strings I can plug in, since I don't have an xbox to test on.  So just having an option to go directly to "E:/" would be enough for most people?

Though I guess I really should get an Xbox Series S for testing I guess.. 

I didn't know about `CreateFile2FromAppW`, if we could use that to get around the need for our horrible async I/O wrapper we're having to use, that would be quite easy to plug in since we already wrap fopen.

**Comment by Player1LoginXBOX** [comment]
> I'm really just looking for exact strings I can plug in, since I don't have an xbox to test on. So just having an option to go directly to "E:/" would be enough for most people?
> 
> Though I guess I really should get an Xbox Series S for testing I guess..
> 
> I didn't know about `CreateFile2FromAppW`, if we could use that to get around the need for our horrible async I/O wrapper we're having to use, that would be quite easy to plug in since we already wrap fopen.

* E drive is the external drive for developer mode however I'd say you'd also 100% want an option for the D drive as well.

*Unnecessary however it is a very solid value all in 1 box with the ability play new software, entertainment in 4k, & all new published games.

*Flyinghead did say he was open to any quick questions you may have regarding the uwp environment. All things considered ppsspp is quite impressive for uwp tbf.

**Comment by Player1LoginXBOX** [comment]
Also. D & E are just the root. You probably want to allow the user to select the directory within that drive. Ex. Currently my ppsspp.ini directory is set to D/Sony - PlayStation Portable

**Comment by Player1LoginXBOX** [comment]
Also you'd probably want to let the user select the directory within the E or D drive. Example my ppsspp.ini currently is set to D:/Sony - PlayStation Portable as an example

**Comment by hrydgard** [comment]
Well if we add an easy way to go directly to the D or E root, assuming we are able to list the directories there, they'll just show up and the user can easily pick their "PSP Games" directory or whatever, so the experience will be ok that way too (and it'll save for the next time)

**Comment by Player1LoginXBOX** [comment]
> Well if we add an easy way to go directly to the D or E root, assuming we are able to list the directories there, they'll just show up and the user can easily pick their "PSP Games" directory or whatever, so the experience will be ok that way too (and it'll save for the next time)

Sounds like a great QOL feature. I'd say most users wouldn't know to edit the ini to make the games easily selectable from external drives and are instead using the load from file so this will be a welcome improvement. If you see a easy way to also save to external drives that be great too.

**Comment by unknownbrackets** [comment]
Well, once you get there you can just pin it and easily browse back there.  It still shows D: and E: if you click up a number of times, right?

-[Unknown]

**Comment by Player1LoginXBOX** [comment]
> Well, once you get there you can just pin it and easily browse back there. It still shows D: and E: if you click up a number of times, right?
> 
> -[Unknown]

This feature request is for the ability to show and select the games with their respective eboot images w/ music from the games tab on the main menu. On UWP currently this is only possible by editing the ini I requested an option be added to get to the externsl directories where you can store games on uwp rather than on the internal ssd

**Comment by Player1LoginXBOX** [comment]
Closing. Thanks @tunip3 @hrydgard
