### ISSUE TITLE
PPSSPP dev builds should allow installing beside/over the Google Play version

### ISSUE THREAD

**Issue by ghost** [hrydgard/ppsspp#15612]
### What should happen

If you wanna update from a stable build to a dev build you need to remove the stable build each time.
For example AetherSX2 provides alpha/betal/dev builds that do sync up with its Google Play release.
Would that be possible here too?
Thanks.

### Who would this benefit

Not having to remove the stable build each time and vice versa.
This may also could help for keeping the PSP folder files on scoped storage i think 

### Games this would be useful in

None

### Other emulators or software with a similar feature

AetherSX2

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by unknownbrackets** [comment]
I could've sworn there was already some issue for this...

-[Unknown]

**Comment by hrydgard** [comment]
It's been talked about before for sure. But I'm not sure I want to have my Play signing keys on Orphis' server. Something to think about though.

**Comment by MojoJojoDojo** [comment]
I thought you could download apk from Github Actions as well but you have to manually generate the apk each time...


> I could've sworn there was already some issue for this...
> 
> -[Unknown]

Well there is an issue about an auto updater which comes close...

**Comment by MojoJojoDojo** [comment]
I thought you could download apk from Github Actions as well but you have to manually generate the apk each time...


> I could've sworn there was already some issue for this...
> 
> -[Unknown]

Well there is an issue about an auto updater which comes close...

**Comment by ANR2ME** [comment]
Te manually generated apk action can be modified to input the keys also, but it won't be automatic like what buildbot do.
Official private keys are not supposed to be put on public place, for security reason.

**Comment by MojoJojoDojo** [comment]
> Te manually generated apk action can be modified to input the keys also, but it won't be automatic like what buildbot do. Official private keys are not supposed to be put on public place, for security reason.

AetherSX2 already provides signed google play apks on its site.
Play! also got a similar thing on its Github Actions but this time you can decide if you want signed or unsigned APKs:
https://github.com/jpd002/Play-/actions/runs/2517313178 (for example).
It also got an automatic apk generator it seems.

**Comment by MojoJojoDojo** [comment]
Forgot to tell that if you got a PPSSPP Gold version from google play you can still maintain a dev build from orphis....
I guess they got different signing keys.
But that just means people will prefer to pirate the gold version to also run the dev builds lol.

**Comment by unknownbrackets** [comment]
What if we just changed the ID of the dev builds so it's different from the stable PPSSPP one (like Gold)?

-[Unknown]

**Comment by hrydgard** [comment]
That would be one way, indeed. I guess we can add a fourth configuration type to the gradle file, and have Orphis use that...

**Comment by MojoJojoDojo** [comment]
> What if we just changed the ID of the dev builds so it's different from the stable PPSSPP one (like Gold)?
> 
> -[Unknown]

Sounds good too , by having both stable and dev builds side by side at least.
Having up to 3 PPSSPPs apps could be funny though lol.

**Comment by ANR2ME** [comment]
Should also have a different icon for dev builds to differentiate with normal PPSSPP may be, like adding the word "dev" on the icon may be.

Btw, if there are 3 different PPSSPP apps installed on Android, and the user is using the default folder for the memstick/PSP, will the memstick/PSP folder be shared for all 3 of them? or each PPSSPP will have their own memstick/PSP foder?

**Comment by hrydgard** [comment]
Development builds (from the new buildbot) are now compatible with release APKs from the website.

However, they are still not compatible with Google Play builds, and as mentioned I'm not even sure that's possible to arrange anymore.

Anyway, that's as far as we're gonna get with this one, so I'm closing.
