### ISSUE TITLE
Zettai Zetsumei Toshi 3 Game Bug

### ISSUE THREAD

**Issue by IrfanH495** [hrydgard/ppsspp#15638]
### Game or games this happens in

ULJS-00191

### What area of the game / PPSSPP

if i use save data from gamefaqs, then in super magoya has fc/freezes
[zzt3 bug super magoya.zip](https://github.com/hrydgard/ppsspp/files/9014747/zzt3.bug.super.magoya.zip)
that bug is also a lot of people experience it on psp, if i search it on google by keyword 絶体絶命都市3 バグ
I will look for other bugs
https://sp.jp.wazap.com/cheat/%E9%80%B2%E8%A1%8C%E3%81%8C%E4%B8%8D%E5%8F%AF%E3%81%AA%E3%83%90%E3%82%B0+/464914/

### What should happen

but if i play from the beginning without save data from gamefaqs it avoids fc i also don't know about that, all this time i play zettai zetsumei toshi 3 always watch videos avoiding bugs in magoya
https://youtu.be/LgJ7PQjIGgE

### Platform

Android

### Mobile phone model or graphics card

Sharp Sh04h

### PPSSPP version affected

ppsspp-v1.12.3-1319-g419692832-android

### Last working version

ppsspp-v1.12.3-1319-g419692832-android

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment]
If you start a new game and then save the game, and then load it again, will it have the same issue? in case the save data on gamefaq were broken

**Comment by IrfanH495** [comment]
> If you start a new game and then save the game, and then load it again, will it have the same issue? in case the save data on gamefaq were broken

I'm not sure about that, this game has a lot of options for players to choose from, but a lot of people are experiencing it and some other bugs.  this is a bug i got yesterday
![Screenshot_20220628-123357](https://user-images.githubusercontent.com/78854859/176590257-a56b6142-37e3-4e6f-8b67-8134c203dbae.png)
video from 12 years ago
https://youtu.be/hGTDSbMau5A
 when i try it again it looks normal
![Screenshot_20220628-123550](https://user-images.githubusercontent.com/78854859/176590333-9dc059cf-98c0-4cfd-b083-b07c1fee756e.png)

**Comment by IrfanH495** [comment]
in my save data the other one I downloaded in the same place gamefaqs.  I've finished it and got 5 endings and I only had one bug, one on Magoya and another on the bridge where Ishizawa seemed to be floating, if I finished the new game+ continued playing when I looked for it again, the bug was not found.
the bug has been acknowledged here
https://www.weblio.jp/wkpja/content/%E7%B5%B6%E4%BD%93%E7%B5%B6%E5%91%BD%E9%83%BD%E5%B8%823+-%E5%A3%8A%E3%82%8C%E3%82%86%E3%81%8F%E8%A1%97%E3%81%A8%E5%BD%BC%E5%A5%B3%E3%81%AE%E6%AD%8C-_%E4%B8%8D%E5%85%B7%E5%90%88

**Comment by IrfanH495** [comment]
it's good if the bug is gone.  I played the new game 3 times and tried several routes I didn't find any bugs.  there is only 1 bug ending 9
sorry 🙏🙏🙏

**Comment by IrfanH495** [comment]
this appears again where ishizawa is seen floating, on youtube live 2 days ago.
https://youtu.be/qXKiDYBMVWg on time 2:14:08
new game without saving data.

**Comment by hrydgard** [comment]
Ok, well, seems those are actual game bugs that happen on the real PSP from the information you posted? Or maybe not the floating Ishizawa thing?

**Comment by IrfanH495** [comment]
looks like ishizawa is also floating on psp https://youtu.be/hGTDSbMau5A
I will play from the beginning without saving data in the latest ppsspp build to ensure the 3 bugs above.
