### ISSUE TITLE
✨ADD BUTTON FOR CREATE FILE "textures.ini" in all ANDROID Ver...✨

### ISSUE THREAD

**Issue by DavidSilvadeSa** [hrydgard/ppsspp#15644]
### Game or games this happens in

ALL

### What area of the game / PPSSPP

ALL

### What should happen

#THIS IS VER... PC WINDOWS

![IMG_20220704_131257](https://user-images.githubusercontent.com/82737672/177192018-2767a835-803a-4e1d-a229-aebb48009cbe.png)

### Platform

Android

### Mobile phone model or graphics card

POCO X3 PRO GPU: ADRENO

### PPSSPP version affected

ALL

### Last working version

ALL

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by Gamemulatorer** [comment]
Duplicate https://github.com/hrydgard/ppsspp/issues/9989

**Comment by hrydgard** [comment]
Ah, nice catch with the duplicate. Closing this one, do keep track of #9989 for updates.
