### ISSUE TITLE
In Chinese traslation, if need a space or not between Chinese and English word｜在中文翻译里，中文与英语单词之间是否需要空格。

### ISSUE THREAD

**Issue by leoxxx** [hrydgard/ppsspp#15660]
For example.
English: Chinese PPSSPP
Chinese: 中文PPSSPP
~I think it's not necessary a space between Chinese and PPSSPP.~
I think it's not necessary a space between "中文" and "PPSSPP".

举个例子。
英语：Chinese PPSSPP
中文：中文PPSSPP
我认为在中文和PPSSPP之间的空格是没必要的。

**Comment by ANR2ME** [comment]
Do you mean it should be `ChinesePPSSPP` instead of `Chinese PPSSPP`? 

That doesn't make any sense, because PPSSPP is a product, if there is ever a product called ChinesePPSSPP it would be a fork of PPSSPP which is a different/unofficial product compared to official PPSSPP.

**Comment by unknownbrackets** [comment]
I've normally seen Latin letters and CJK generally next to each other in text, without any spaces - unless there's multiple Latin words that include punctuation.

Most important is to stay largely consistent IMHO, and after that to use whatever is most common or most readable for Chinese users.

-[Unknown]

**Comment by leoxxx** [comment]
No.
It's meaning: "Chinese PPSSPP" translate into "中文PPSSPP" in Chinese traslation.
I think it's not necessary a space between "中文" and "PPSSPP"

**Comment by leoxxx** [comment]
@hrydgard
Here is the lang file, it's edited by me.
[zh_CN.zip](https://github.com/hrydgard/ppsspp/files/9109659/zh_CN.zip)

**Comment by hrydgard** [comment]
Thanks @leoxxx , I'll apply it.

**Comment by leoxxx** [comment]
If you think need do it , I can do it.
But I am not familiar with some zh_TW words (some words' expression are diffrent from zh_CN ones), so I just can delete some sapces.

**Comment by leoxxx** [comment]
If you think need do it , I can do it.
But I am not familiar with some zh_TW words (some words' expression are diffrent from zh_CN ones), so I just can delete some sapces.

**Comment by hrydgard** [comment]
Merged.

I'm gonna close this now.
