### ISSUE TITLE
Shining Ark - circle press ignored

### ISSUE THREAD

**Issue by IrfanH495** [hrydgard/ppsspp#15663]
### Game or games this happens in

NPJH-50717

### What area of the game / PPSSPP

Sorry I don't know what to title this issue.
if i talk to a character or select an option there should press circle but it's not working,
https://drive.google.com/file/d/1Awg6EIptU0r24xn1PH7HhQgvPJJ0m4-4/view?usp=drivesdk
And one more if I open a gallery of images like this.
https://drive.google.com/file/d/1AiWGhS7PdeUpdSm-ZJ7kOewjgRpSyTlA/view?usp=drivesdk
For the gallery I used cheat I was looking for save data but didn't find it.

### What should happen

this issue has been going on for a long time i just forgot to report

### Platform

Android

### Mobile phone model or graphics card

sharp Sh04H

### PPSSPP version affected

v1.12.3-1358-gdca637d8d

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by Gamemulatorer** [comment]
Maybe Opengl 2.0 phone has a bug on this like Jean D' Arc? 🤔

**Comment by Gamemulatorer** [comment]
How about this now @IrfanH495?

**Comment by IrfanH495** [comment]
> How about this now @IrfanH495?

still same

**Comment by Gamemulatorer** [comment]
> > How about this now @IrfanH495?
> 
> still same

GE dump?

**Comment by IrfanH495** [comment]
@Gamemulatorer 
[NPJH50717.zip](https://github.com/hrydgard/ppsspp/files/9671688/NPJH50717.zip)

**Comment by unknownbrackets** [comment]
If it's not responding to pressing a button, it's probably not graphics related.  It could, be, just seems unlikely.

Has this never worked?  Does it work in JPCSP?

-[Unknown]

**Comment by IrfanH495** [comment]
sorry for the gallery display, it's like that if use cheats.
for control I don't know why it can be like that.

**Comment by IrfanH495** [comment]
can use the circle button, if i set the confirm button to O and restart the game.

**Comment by unknownbrackets** [comment]
This is a Japanese game, so that would be the most common configuration.  Could this just be a game bug?

-[Unknown]

**Comment by hrydgard** [comment]
Hm, if so, we should probably use a compat flag to switch the confirm button to O unconditionally for this game.

**Comment by IrfanH495** [comment]
thanks
ppsspp-v1.13.2-2120-g612d2181a-android fix
nice feature, very helpful for me to read the subtitles in the cutscenes.
![Screenshot_20221128-181133_PPSSPP](https://user-images.githubusercontent.com/78854859/204267099-2d5e5cda-f8af-49f9-9d14-be7ba7f9bf70.png)
so can't wait for the play store version to release
