### ISSUE TITLE
Valkyrie Profile: Lenneth Freezing

### ISSUE THREAD

**Issue by levelxplane** [hrydgard/ppsspp#15672]
### Game or games this happens in

ULUS - 10107 - VP

### What area of the game / PPSSPP

Chapter 3 Unable to enter Camille Village dungeon.
On Switch: Performance in dungeon drops to the point of being unplayable.
On PC: Game freezes when trying to enter dungeon.

### What should happen

The dungeon should be able to be entered and be completed at a somewhat playable framerate.

### Logs

This is from the PC version.
07:55:856 ModuleThread E[ME]: HLE\sceMpeg.cpp:1386 UNIMPL sceMpegAvcDecodeFlush(08e9de40)
07:55:890 idle0        E[FILESYS]: FileSystems\BlockDevices.cpp:101 Could not read 2048 bytes from block
07:55:973 idle0        E[FILESYS]: FileSystems\BlockDevices.cpp:101 Could not read 2048 bytes from block
07:56:056 idle0        E[FILESYS]: FileSystems\BlockDevices.cpp:101 Could not read 2048 bytes from block
07:56:140 idle0        E[FILESYS]: FileSystems\BlockDevices.cpp:101 Could not read 2048 bytes from block
07:56:223 idle0        E[FILESYS]: FileSystems\BlockDevices.cpp:101 Could not read 2048 bytes from block
07:56:306 idle0        E[FILESYS]: FileSystems\BlockDevices.cpp:101 Could not read 2048 bytes from block
07:56:391 idle0        E[FILESYS]: FileSystems\BlockDevices.cpp:101 Could not read 2048 bytes from block
07:56:473 idle0        E[FILESYS]: FileSystems\BlockDevices.cpp:101 Could not read 2048 bytes from block
07:56:558 idle0        E[FILESYS]: FileSystems\BlockDevices.cpp:101 Could not read 2048 bytes from block
07:56:641 idle0        E[FILESYS]: FileSystems\BlockDevices.cpp:101 Could not read 2048 bytes from block
07:56:723 idle0        E[FILESYS]: FileSystems\BlockDevices.cpp:101 Could not read 2048 bytes from block
07:56:807 idle0        E[FILESYS]: FileSystems\BlockDevices.cpp:101 Could not read 2048 bytes from block
07:56:891 idle0        E[FILESYS]: FileSystems\BlockDevices.cpp:101 Could not read 2048 bytes from block
07:56:975 idle0        E[FILESYS]: FileSystems\BlockDevices.cpp:101 Could not read 2048 bytes from block
07:57:058 idle0        E[FILESYS]: FileSystems\BlockDevices.cpp:101 Could not read 2048 bytes from block
07:57:140 idle0        E[FILESYS]: FileSystems\BlockDevices.cpp:101 Could not read 2048 bytes from block
07:57:224 idle0        E[FILESYS]: FileSystems\BlockDevices.cpp:101 Could not read 2048 bytes from block

### Platform

Windows

### Mobile phone model or graphics card

PC Nvidia GTX1080Ti, Switch GM20B 

### PPSSPP version affected

v1.12.3

### Graphics backend (3D API)

Direct3D 9

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
The log message indicates that it's likely reading off the end of the ISO file, which means it's likely truncated or corrupt.

Could you check a fresh dump of the game, to see if you have the same problem?

**Comment by levelxplane** [comment]
That was it! thank you!

**Comment by hrydgard** [comment]
I think it might be worth considering detecting this type of error and reporting to the user, as the symptoms are pretty obvious. I'll file an issue.
