### ISSUE TITLE
Could detect reads off the end of an ISO and report as broken ISO to user

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#15674]
See issue #15672 , which is a typical instance.

I think it might be worth considering detecting this type of error and reporting to the user, as the symptoms are pretty obvious.

Of course there are many other possible ways an ISO can be corrupt, but this has got to be one of the most common ways.

Actually, in some cases we can probably detect this when traversing the ISO file system on startup... But not for some games that use various types of raw sector I/O, I guess.

**Comment by hrydgard** [comment]
Hm, right... that can't be a lot of games though. Could even consider whitelisting.

Ha, completely forgot we already had that check. But yeah, might need some tweaks to catch some cases indeed, so leaving the issue open, and as you say, maybe needs to be louder.

**Comment by unknownbrackets** [comment]
#15677 should cover this, so I'm going to close it.

-[Unknown]
