### ISSUE TITLE
Texture transparency

### ISSUE THREAD

**Issue by AnimeAnalPRO** [hrydgard/ppsspp#15699]
### Game or games this happens in

ULES00719 v1.01 - Asphalt Urban GT 2

### What area of the game

Many routes have a problem with texture transparency and other objects are visible through them.

### What happens

![reporting](https://user-images.githubusercontent.com/109460250/179392777-0179d122-e5a2-4e3f-8c7d-10f0ce3da7a4.jpg)
![Screenshot_2022-07-17-12-46-13-147_org ppsspp ppsspp](https://user-images.githubusercontent.com/109460250/179392781-e1641fc1-7fab-4f3b-abdf-40d3b993bcb3.jpg)
![Screenshot_2022-07-17-12-45-36-879_org ppsspp ppsspp](https://user-images.githubusercontent.com/109460250/179392783-d4bd720b-428f-44ba-82fc-b4dd1f90c866.jpg)
![Screenshot_2022-07-17-12-44-53-387_org ppsspp ppsspp](https://user-images.githubusercontent.com/109460250/179392786-f8c03fc4-8432-466d-a180-3453439c305d.jpg)

### What should happen

-

### Platform

Android

### Mobile phone model or graphics card

Poco X3 Pro

### PPSSPP version affected

v1.12.3-1413-g829cb7432

### Last working version

-

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
This seems to be a duplicae of #14299, closing.

**Comment by Gamemulatorer** [comment]
Still open 🤔

**Comment by hrydgard** [comment]
Weird, I know I pressed close...
