### ISSUE TITLE
Gripshift Texture Problem / Crash (sceSas?)

### ISSUE THREAD

**Issue by ghost** [hrydgard/ppsspp#1569]
Gripshift Textures and rendering problem
It starts almost without problem.but assets doesn't drawing to screen perfectly...
Hope you fix that.

![gripshift render](https://f.cloud.github.com/assets/272574/435613/630c95d6-afef-11e2-9f27-2c3ad971c758.PNG)

**Comment by livisor** [comment]
The game goes in-game but freezes. This issue is not up to date anymore.Closing
