### ISSUE TITLE
Stuttering MP3 playback in WipEout Pulse

### ISSUE THREAD

**Issue by bonkmaykrQ** [hrydgard/ppsspp#15703]
### Game or games this happens in

UCES00465 Wipeout Pulse

### What area of the game / PPSSPP

Settings menu > music
Place an MP3 file inside of the folder /PPSSPP/MUSIC/WIPEOUT. 

### What should happen

The audio should play without any skips or cuts.

Instead the game will play custom tracks at the correct speed but it will sound like there are a bunch of holes in it.

For demonstration I've linked a video: [https://media.discordapp.net/attachments/699015866519650377/998475663457652746/Screen_Recording_20220718-012512_PPSSPP.mp4](https://media.discordapp.net/attachments/699015866519650377/998475663457652746/Screen_Recording_20220718-012512_PPSSPP.mp4) 

### Platform

Android

### Mobile phone model or graphics card

Samsung Galaxy S22 SM-S901U

### PPSSPP version affected

v1.12.3

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [x] Try without any cheats and without loading any save states.
- [x] Include logs or screenshots of issue.

**Comment by Gamemulatorer** [comment]
This issue is already fixed via https://github.com/hrydgard/ppsspp/pull/15355 download the latest ppsspp build android from https://buildbot.orphis.net/ppsspp/

**Comment by hrydgard** [comment]
Or just wait for the upcoming official release, which will of course include the fix. Closing.

**Comment by Gamemulatorer** [comment]
> Or just wait for the upcoming official release, which will of course include the fix. Closing.

ETA of the next official release of ppsspp? First week of August?

**Comment by hrydgard** [comment]
Last week of July.
