### ISSUE TITLE
Update Development Build in PPSSPP Menu

### ISSUE THREAD

**Issue by Danik2343** [hrydgard/ppsspp#15715]
### What should happen

Update Development Build in PPSSPP Menu

### Who would this benefit

Will save more time for game testers on dev builds.
You will not need to manually download several times when the build is updated.

### Platform (if relevant)

Windows

### Games this would be useful in

-

### Other emulators or software with a similar feature

DuckStation.
PCSX2 (1.7 dev, with QT)

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by MojoJojoDojo** [comment]
I agree about that but I think there is also an issue about this lol.
SImilar to Dolphin maybe have ano option to choose the release channel like : dev,stable etc.

**Comment by Gamemulatorer** [comment]
Duplicate https://github.com/hrydgard/ppsspp/issues/10002

**Comment by LunaMoo** [comment]
Closing as a duplicate.


 Personally I don't really think it's that usefull, I build PPSSPP on my own, but even when downloading from buildbot I'd rather see commit titles as a bare minimum before deciding about updating. No reason to redownload PPSSPP to for example android for each commit affecting other platforms.
