### ISSUE TITLE
Split second graphics problem ver. 1.13

### ISSUE THREAD

**Issue by 71knight** [hrydgard/ppsspp#15732]
### Game or games this happens in

Split / second

### What area of the game

At the car select screen.

### What happens

The ryback brawler yellow car is missing its textures.  It is just chrome.

### What should happen

The yellow car should have texture logos on it.

### Platform

Android 11

### Mobile phone model or graphics card

OnePlus 7t with adreno 640

### PPSSPP version affected

1.13

### Last working version

1.12.3 1116

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by Panderner** [comment]
Here's a screenshot for reference:
![ULUS10513_00001](https://user-images.githubusercontent.com/37503397/181174206-241bf0e7-8d90-438f-a33c-0d192610b746.jpg)

**Comment by ANR2ME** [comment]
May need GE dump for the devs to investigate rendering issue.

**Comment by Panderner** [comment]
GE dump here;
[ULUS10513.zip](https://github.com/hrydgard/ppsspp/files/9196568/ULUS10513.zip)

**Comment by hrydgard** [comment]
Alright, I got it. #15733
