### ISSUE TITLE
Weird sky glitch in Monster Hunter Portable 3 HD

### ISSUE THREAD

**Issue by Deka710** [hrydgard/ppsspp#15745]
### Game or games this happens in

NPJB40001 - Monster Hunter Portable 3 HD ver

### What area of the game

area 3 & 8 in sandy plains

### What happens

https://user-images.githubusercontent.com/97207704/181738028-b0a7c3b2-dd42-4334-a652-7e7c39efc6fa.mp4

weird glitch happen in the sky when moving the camera
edit : doesnt happen at 1x res,only happens when upscaling the res

### What should happen

.

### GE frame capture

[NPJB40001.zip](https://github.com/hrydgard/ppsspp/files/9218907/NPJB40001.zip)

### Platform

Android

### Mobile phone model or graphics card

Xiaomi Poco F3

### PPSSPP version affected

1.13.1

### Last working version

.

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by Gamemulatorer** [comment]
There's also a glitch on some monsters in Sandy Plains area.
![Screenshot_2022-09-12-15-39-33-28](https://user-images.githubusercontent.com/37603562/189609678-52b91e46-6612-4af0-b14b-d37b8d3af2a9.png)
![Screenshot_2022-09-12-15-33-08-78](https://user-images.githubusercontent.com/37603562/189609708-448720cb-54d3-4684-bf00-cbec7288283a.png)
![Screenshot_2022-09-12-15-27-36-27](https://user-images.githubusercontent.com/37603562/189609731-1326d959-b7b1-4e19-bbb6-df4a3c424feb.png)

**Comment by Gamemulatorer** [comment]
I cannot reproduce this Sky Glitch on my Oppo a3s adreno 506 gpu.

https://user-images.githubusercontent.com/37603562/190052543-69a8e42a-e9d5-4495-bac6-a38b72af5581.mp4

**Comment by unknownbrackets** [comment]
Has this changed at all in recent git builds?  This game uses `<=` tests, so it'll do clears a different way now and we've also affected depth clamp/clip.

The draws that look like they'd be affected do use depth clamp, and compare against an initialized 1.0 (65535) depth.

If you open the same frame dump you attached like it was a game, do you see the glitch?

-[Unknown]

**Comment by Deka710** [comment]
> Has this changed at all in recent git builds? This game uses `<=` tests, so it'll do clears a different way now and we've also affected depth clamp/clip.
> 
> The draws that look like they'd be affected do use depth clamp, and compare against an initialized 1.0 (65535) depth.
> 
> If you open the same frame dump you attached like it was a game, do you see the glitch?
> 
> -[Unknown]

still the same

**Comment by Gamemulatorer** [comment]
@Deka710 A savestate near Sandy Plains I will try to reproduce this on my Vivo Y11

**Comment by Gamemulatorer** [comment]
No feedback/outdated?

**Comment by Deka710** [comment]
fixed with turnip driver

**Comment by hrydgard** [comment]
OK, we'll chalk this down as a driver bug then. Not much point in digging deep into it.
