### ISSUE TITLE
Crash when import cheat.db

### ISSUE THREAD

**Issue by endrare** [hrydgard/ppsspp#15742]
### Game or games this happens in

None

### What area of the game / PPSSPP

version 1.13 has problems importing cheat.db, when I click import from cheat.db ppsspp freezes and a forced close popup appears

### What should happen

It shouldn't

### Platform

Android

### Mobile phone model or graphics card

Redmi note 8

### PPSSPP version affected

v1.13

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment]
You didn't mention the last working version, is this a regression or it have been like that for you even on older version?

**Comment by endrare** [comment]
I think it's the problem of the cheat.db file, I tried another version and it's no problem

**Comment by Gamemulatorer** [comment]
**Not a bug**
