### ISSUE TITLE
Lost DualShock4 support in 1.13

### ISSUE THREAD

**Issue by kathyrollo** [hrydgard/ppsspp#15741]
### Game or games this happens in

All

### What area of the game / PPSSPP

DualShock4 is not responding on 1.13. The controller works on 1.12.3 and other emulators like PCXS2 and DuckStation.

### What should happen

Usual external controller support (DualShock4).

### Platform

Windows

### Mobile phone model or graphics card

GTX 1650 Ti

### PPSSPP version affected

v1.13

### Last working version

v1.12.3

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
Both a DS4 and DualSense controller still work fine for me (not using any unusual drivers or mapping software, just DirectInput.)

There's no response when you try to map buttons in Control Mapping?

-[Unknown]

**Comment by hrydgard** [comment]
Strange, very little has changed around control mapping in Windows...

**Comment by kathyrollo** [comment]
Hey @hrydgard , thanks for your quick response. DS4 was spazzing randomly upon further testing, so figured to just poke the hole. Looks to be behaving correctly again. Don't have DualSense so unfortunately can't check that. Closing this ticket for the moment. Cheers!

**Comment by hrydgard** [comment]
Great, thanks for letting us know!
