### ISSUE TITLE
Can't use Vulkan

### ISSUE THREAD

**Issue by leoxxx** [hrydgard/ppsspp#15766]
### Game or games this happens in

All

### What area of the game / PPSSPP

Choose Vulkan to run games, then PPSSPP display a black screen. Close the window, but the process is still running.
It's O.K. in v1.12.3. 

### What should happen

Can run games.

### Platform

Windows

### Mobile phone model or graphics card

HIS 7850 1G

### PPSSPP version affected

v1.13.1

### Last working version

v1.12.3

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by LunaMoo** [comment]
Use https://buildbot.orphis.net/ppsspp/index.php?m=fulllist or your own builds and bisect which commit exactly broke it.

 Most people doesn't use Win 7 anymore and can't even test it anymore due to lack of win 7 support for modern hardware, it's getting less and less compatible with time especially with lower level apis like vulkan.

**Comment by leoxxx** [comment]
ppsspp-v1.12.3-257-gb3bd06805-windows-amd64 can run games.
ppsspp-v1.12.3-263-g712b87ae5-windows-amd64 can't run games.

**Comment by hrydgard** [comment]
Thanks, that's good info!

The culprit is, somehow, this:

- #12108

So it doesn't like creating the pipelines on a background thread, which seems very weird. But something we can fairly easily work-around, I think.

**Comment by Gamemulatorer** [comment]
This might be related to this https://github.com/hrydgard/ppsspp/issues/15744?

**Comment by jvhellraiser** [comment]
Unable use Vulkan on Windows 11 either..
![Screenshot 2022-08-04 085838](https://user-images.githubusercontent.com/16488761/182853823-54ce3240-b3b4-434a-baa5-44a4348bdd26.jpg)

**Comment by hrydgard** [comment]
@jvhellraiser is that right at the start when starting the game?

**Comment by leoxxx** [comment]
I found his title display "instance:2", so two processes are running. And this game is 1 player game.

**Comment by jvhellraiser** [comment]
> @jvhellraiser is that right at the start when starting the game?

That is correct once you select Vulkan API and load any the game the error appear.

**Comment by hrydgard** [comment]
that error is super unexpected. will have to look into it

**Comment by jvhellraiser** [comment]
> I found his title display "instance:2", so two processes are running. And this game is 1 player game.
![Screenshot 2022-08-06 204312](https://user-images.githubusercontent.com/16488761/183270445-2f5fc652-9db5-4168-b274-914e56361c1d.jpg)
 yeah here is one without the  instance 2, by the way not to brag about it but i can run multiple ppsspp at once
![Screenshot 2022-08-06 205012](https://user-images.githubusercontent.com/16488761/183270588-02f3ba42-525d-4eec-886b-ac2ff7f2dee9.jpg)

**Comment by leoxxx** [comment]
I know PPSSPP can run multiple instances and 1 player game needn't run multiple processes.
I just explain another process is running and you issue is the same as mine.

**Comment by leoxxx** [comment]
https://github.com/hrydgard/ppsspp/pull/16256
[v1.13.2-1605-gceb4186d0](https://github.com/hrydgard/ppsspp/commit/ceb4186d0ffc26091bb3fc25a1e71bce15b8902d)
Can run game, but still popup 2 error dialogboxes after close.
![2022-10-20_102649](https://user-images.githubusercontent.com/5364709/196842860-b737a61e-935e-4b7d-8e66-a81d65fff04d.png)
![2022-10-20_102719](https://user-images.githubusercontent.com/5364709/196842865-fb4e0a14-f1dc-4940-bffc-d78708a6a0c3.png)
@hrydgard 
Should I close the issue?

**Comment by unknownbrackets** [comment]
If we call `vkQueuePresentKHR` during shutdown for cleanup we probably should ignore errors, even device lost.  Maybe a validation error is happening, though.

Does this happen even if you only open PPSSPP, and then close it?  Or do you only get those errors if you open a game?

-[Unknown]

**Comment by leoxxx** [comment]
Only closing.
