### ISSUE TITLE
Star Ocean - First Departure: map error in battle with D3D

### ISSUE THREAD

**Issue by leoxxx** [hrydgard/ppsspp#15767]
### Game or games this happens in

ULJM-05290 Star Ocean - First Departure

### What area of the game / PPSSPP

![Snap1](https://user-images.githubusercontent.com/5364709/182021578-753a799d-201d-4a33-a138-7e842cd10572.png)
It's error with D3D 9 and 11. I can't run games with Vulkan in v1.13.1. So I can't test with Vulkan.
It's O.K. in v1.12.3.

### What should happen

![Snap2](https://user-images.githubusercontent.com/5364709/182021670-cf695d22-6e58-4115-8b1e-c825bde883f3.png)
It's O.K. with OpenGL in v1.13.1.

### Platform

Windows

### Mobile phone model or graphics card

HIS 7850 1G

### PPSSPP version affected

v1.13.1

### Last working version

v1.12.3

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment]
The devs may need a GE dump to investigate rendering issue.

**Comment by leoxxx** [comment]
v1.12.3-102-ga9d7948f7 is O.K. 
This error appear after v1.12.3-113-ga3a6bdc19.

**Comment by Gamemulatorer** [comment]
Where's the ge dump??

**Comment by leoxxx** [comment]
> Where's the ge dump??

I add it just now.

**Comment by hrydgard** [comment]
Thanks, I'll investigate sometime soon.
