### ISSUE TITLE
(Vulkan) Using any texture shader will show warning "Video memory FULL, switching to slow caching mode" and then crash ppsspp. 

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#15778]
### Game or games this happens in

Any games

### What area of the game / PPSSPP

At the start of the game

### What should happen

Using texture shader 4xBRZ can crash any games.

https://user-images.githubusercontent.com/37603562/182168051-2079e232-643f-4a3f-b005-6f5009611bc0.mp4

### Logs

None

### Platform

Android

### Mobile phone model or graphics card

Redmi Note 9 Android 12 Helio G85 Mali-G52 GPU

### PPSSPP version affected

v1.13.1-118

### Last working version

1.13.1-63

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by Gamemulatorer** [comment]
Tekken 6 is instantly crashing me out the emulator!


https://user-images.githubusercontent.com/37603562/182259678-680b657c-2d10-4b9d-81c6-894b7aa150ab.mp4

**Comment by Panderner** [comment]
Same happens for me for my PC:
![Screenshot (10)](https://user-images.githubusercontent.com/37503397/182265974-7489e079-ef91-4f7c-a1b7-0fd67b837ff3.png)

**Comment by LunaMoo** [comment]
Not sure if I should open a new issue, since this is possibly caused by same thing, but on Vulkan when not using max quality filtering while using texture scaling I hit assert from this line:
https://github.com/hrydgard/ppsspp/blob/9437d5e3b00ac69c8b2593115190527a2e9ee8db/GPU/Vulkan/TextureCacheVulkan.cpp#L899
doesn't really crash through and doesn't happen with max quality filtering selected.

**Comment by Gamemulatorer** [comment]
This also can reproduce using any texture shader ***TexMMPX*** ***Tex2xBRZ*** and ***Tex4xBRZ***

**Comment by hrydgard** [comment]
I'll get it fixed shortly.
