### ISSUE TITLE
UI issue on UWP build

### ISSUE THREAD

**Issue by ANR2ME** [hrydgard/ppsspp#15771]
### Game or games this happens in

PPSSPP UI

### What area of the game / PPSSPP

Some text/number input only shows a thin horizontal line
![image](https://user-images.githubusercontent.com/7974720/182043892-3e0c208c-62c2-4ea6-bc89-8efbc8ef9822.png)
![image](https://user-images.githubusercontent.com/7974720/182043902-5a708800-d6e2-4bb2-bfda-5a6f883b0af7.png)

Nickname can't be changed using keyboard (not even the cursor can moves), while UI navigation worked fine using keyboard
![image](https://user-images.githubusercontent.com/7974720/182043927-a4badc7a-a9e6-4677-b9dd-759788e70e3d.png)

PS: I only tested this on Win11 using UWP x64, not sure about Xbox

### What should happen

Behave similarly to Windows build when possible

### Platform

UWP / Xbox

### Mobile phone model or graphics card

Intel UHD Graphics 620

### PPSSPP version affected

v1.13.1

### Last working version

Not sure, i just noticed it recently

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by GABO1423** [comment]
Can confirm all of these problems are present on Xbox.

**Comment by hrydgard** [comment]
That should have taken care of it.
