### ISSUE TITLE
Prince of Persia: Revelations crashes after playing for a while

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#15776]
Got an email report that this game crashes after like 10 minutes on Android.

Could be some kind of memory or resource leak, not sure what else could cause this...

But should be investigated.

**Comment by hrydgard** [comment]
Might also be related to #15795 and #15788

**Comment by Gamemulatorer** [comment]
So the crash can only reproduce in Europe Version https://github.com/hrydgard/ppsspp/issues/15824#issuecomment-1214210180

**Comment by Gamemulatorer** [comment]
@Sommyrex at exactly start of the game after 50 seconds the game is crash?

**Comment by hrydgard** [comment]
This is likely related to #15788. I'm gonna close, let's re-open if we get new reports.

**Comment by Gamemulatorer** [comment]
@Sommyrex can you still reproduce the crash using the latest build?
