### ISSUE TITLE
CPU texture upscaling broken in latest version with Vulkan

### ISSUE THREAD

**Issue by LunaMoo** [hrydgard/ppsspp#15779]
### Game or games this happens in

<s>not related / all</s> more related to texture formats I suppose than a game, but some I could find it include:
Gladiator Begins, Zettai Zetsumei Toshi 3, God of War: Ghost of Sparta, Harvest Moon.

### What area of the game / PPSSPP

The problem is only present(or at least appear more often) when "Auto Max Quality" filtering is disabled, but Auto Max Quality results in more ugly texture scaling via CPU, at least from what I checked in maybe one game.

 As noted here: 
https://github.com/hrydgard/ppsspp/issues/15778#issuecomment-1201902325
it stucks at assert for format check
dstFmt = VK_FORMAT_B4G4R4A4_UNORM_PACK16 or VK_FORMAT_A1R5G5B5_UNORM_PACK16 or possibly others when it fails. When pressing OK on the assert message it continues to run until it hit a texture in unexpected format to scale again, the texture if upscaled that way will appear glitched in various ways.

### What should happen

It should work as in the past <s>*will bisect a bit later if needed*.</s> done, first broken build was v1.13.1-40-g3e39f62c3

### Logs

![cpu scaling bug](https://user-images.githubusercontent.com/5485237/182404496-e399e7e9-75f3-4da5-9531-18909f880864.png)

![cpu scaling bug2](https://user-images.githubusercontent.com/5485237/182404523-3d513bf2-dc79-4e28-8b6e-6a7dcc04385f.png)

### Platform

Windows

### Mobile phone model or graphics card

RTX 3060Ti

### PPSSPP version affected

[v1.13.1-40-g3e39f62c3](https://github.com/hrydgard/ppsspp/commit/3e39f62c3d4d96e676051d9e2ff7f5b9930510f2) and newer

### Last working version

[v1.13.1-23-gd6e699aa5](https://github.com/hrydgard/ppsspp/commit/d6e699aa5629f806983f680b894fca1d79e19093)

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [x] Include logs or screenshots of issue.

**Comment by Gamemulatorer** [comment]
CPU texture upscaling broken in latest version with opengl also.
![Screenshot_2022-08-06-23-28-08-354_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/183255564-5d455294-5eef-437a-af27-663df3ab84d9.jpg)
[NPJH50686.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/9275340/NPJH50686.ppdmp.zip)

**Comment by hrydgard** [comment]
I'll fix it up.

**Comment by hrydgard** [comment]
done.
