### ISSUE TITLE
Simulate Block Transfer Effects is broken in the latest build with OpenGL.

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#15799]
### Game or games this happens in

Games that benefits from simulate block transfer effects

### What area of the game

At the start of the games like the intro video of God Eater Burst, Sun in Burnout Legend, HUD in Naruto Shippuden Ultimate Ninja Impact and MotorStorm Artic Edge white background during loading of the game.

### What happens

Graphics issues in the ff games.
***God Eater Burst***
![Screenshot_2022-08-07-12-34-05-388_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/183275618-08eddaa5-7bac-4eac-9999-4884836c1cc9.jpg)
***Burnout Legends***
![Screenshot_2022-08-07-12-32-37-938_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/183275628-667f790a-d8a8-4870-b301-b7cca48e9adf.jpg)
***Naruto Shippuden Ultimate Ninja Impact***
![Screenshot_2022-08-07-12-36-10-008_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/183275635-e5026bba-46c3-4a4b-aca5-97322f9a293c.jpg)
***MotorStorm Artic Edge***
![Screenshot_2022-08-07-12-36-49-653_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/183275643-aa3131e3-1025-4d04-a78b-3d7879abad9b.jpg)

### What should happen

No graphics issues rendering like in the stable version 1.13.1

### GE frame capture

Here's the ge dump of all the games I mentioned.
[UCES01250.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/9276198/UCES01250.ppdmp.zip)
[ULUS10025.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/9276200/ULUS10025.ppdmp.zip)
[ULUS10582.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/9276201/ULUS10582.ppdmp.zip)
[ULUS10563.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/9276202/ULUS10563.ppdmp.zip)

### Platform

Android

### Mobile phone model or graphics card

Redmi Note 9 Android 12 Helio G85 Mali-G52 GPU

### PPSSPP version affected

v1.13.1-207

### Last working version

1.13.1

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by Gamemulatorer** [comment]
Here's the ge dump of all the games I mentioned above.
[UCES01250.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/9276198/UCES01250.ppdmp.zip)
[ULUS10025.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/9276200/ULUS10025.ppdmp.zip)
@
[ULUS10582.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/9276201/ULUS10582.ppdmp.zip)
[ULUS10563.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/9276202/ULUS10563.ppdmp.zip)

**Comment by unknownbrackets** [comment]
Right, the semantic name thing.  Confused me when I was doing Presentation...

-[Unknown]

**Comment by Gamemulatorer** [comment]
Thanks unknownbrackets!
But unfortunately Burnout Legends issue still present both opengl and vulkan :(
![Screenshot_2022-08-07-14-00-02-964_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/183277638-514ac75d-3c59-4ba2-9d99-861221051953.jpg)
ppsspp v1.13.1-209

**Comment by unknownbrackets** [comment]
Okay, maybe that's separate from the general "DrawActiveTexture doesn't work at all."

-[Unknown]

**Comment by hrydgard** [comment]
Will be fixed by #15804
