### ISSUE TITLE
Buffered Rendering is broken can cause crashing in the latest version with OpenGLES 2.0 device

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#15800]
### Game or games this happens in

Almost all 3D games I tested

### What area of the game / PPSSPP

At the start of the game when loading and then crash.

https://www.kapwing.com/videos/62ef3f2a3fcf7500e86510b3

### What should happen

Not crashing like in skip non-buffered rendering.

### Platform

Android

### Mobile phone model or graphics card

Cloudfone Excite Prime Android 5.1 Mali-450 GPU

### PPSSPP version affected

v1.13.1-207

### Last working version

1.13.1

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Will be fixed by #15804

**Comment by Gamemulatorer** [comment]
Sad to say Tekken 6 still crashing and Burnout Legends have black textures environment.

Will upload a screen video recorded and screenshots later..

**Comment by Gamemulatorer** [comment]
Watch here.

https://user-images.githubusercontent.com/37603562/183442397-8834c5ad-6e88-41d3-b75a-9412d8f357ee.mp4

**Comment by hrydgard** [comment]
ADB logs are better than screenshots and videos when it comes to crashes...

**Comment by Gamemulatorer** [comment]
Hard to get adb logs on my android 5 phone 😅

**Comment by hrydgard** [comment]
Not if you have a PC with adb installed and a usb cable.

**Comment by Gamemulatorer** [comment]
Will I don't have pc XD
I will try sometime later since my android 5 is rooted ;)

**Comment by hrydgard** [comment]
Not much in those logs, for whatever reason.

Anyway, I've fixed a few things, please try again.

**Comment by unknownbrackets** [comment]
Reported fixed in 1913930, so I'm going to close this.

-[Unknown]
