### ISSUE TITLE
(UI) Crash of The Titans some feature/settings missing, also cannot delete game configuration

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#15806]
### What should happen

Game details should be display correctly and also game config can be deleted.

Something wrong in the game after converted from **iso** to ***cso*** using maxcso.
![Screenshot_2022-08-07-22-06-50-246_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/183294878-7fbaedfa-475e-405e-9931-b7a131a5ddf6.jpg)

Calculate CRC still work
https://www.kapwing.com/videos/62efc4eaa6d2ae0092a4001e

### Who would this benefit

Everybody

### Platform (if relevant)

Android

### Games this would be useful in

ULUS-10304

### Other emulators or software with a similar feature

None

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by unknownbrackets** [comment]
If you run `maxcso --crc` on it, does the CRC come out right?

This basically means it's never parsing out the game ID properly from the ISO.  Does the game still start correctly?

-[Unknown]

**Comment by Gamemulatorer** [comment]
> Does the game still start correctly?
> 
> -[Unknown]

Yes the game still start good no problem at all.

**Comment by Gamemulatorer** [comment]
I think this issue is not related to ppsspp so closing...
