### ISSUE TITLE
Simpsons OpenGL rendering regression 

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#15818]
Just keeping track of it here. The OpenGL rendering broke (only on Android!) in this commit:

8aebf0dca4e38f010b716d966b5716583a198f19   (Port the OpenGL depal path to thin3d)

Which is perhaps not a surprising culprit.

**Comment by hrydgard** [comment]
Seems to be a case of shader version mismatch, need to switch depal to use the ShaderWriter to make things consistent between fs/vs.

**Comment by Panderner** [comment]
Here's a screenshot:
![Screenshot_2022-08-09-17-23-28-203_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/183614017-9e47b109-7cdb-409e-8102-199a04983a67.jpg)

**Comment by hrydgard** [comment]
Thanks, not needed, i found the problem. Fix coming later today

**Comment by hrydgard** [comment]
The burnout issue is different, I'm on that next

**Comment by hrydgard** [comment]
Burnout issue should be fixed now.
