### ISSUE TITLE
Hunter x Hunter: Wonder Adventure missing shadows 

### ISSUE THREAD

**Issue by benderscruffy** [hrydgard/ppsspp#15813]
### Game or games this happens in

Hunter x Hunter: Wonder Adventure NPJH50624	

### What area of the game / PPSSPP

during gameplay missing shadows
![PPSSPP v1 13 1-234-g5434bd83e - NPJH50624 _ HUNTER×HUNTER　ワンダーアドベンチャー (instance_ 12) 8_08_2022 2_20_42 PM](https://user-images.githubusercontent.com/2696404/183355507-3d512823-7133-4eac-a8b2-0f66d741ddfc.png)

here is a GE dump
[NPJH50624.zip](https://github.com/hrydgard/ppsspp/files/9279358/NPJH50624.zip)

### What should happen

shadows should be present
this is how it should look
![02989-12](https://user-images.githubusercontent.com/2696404/183355137-1c0d7a2e-b035-4265-b159-00725f3ad81d.jpg)

### Platform

Windows

### Mobile phone model or graphics card

AMD RX 580

### PPSSPP version affected

PPSSPP v1.13.1-234-g5434bd83e

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Had a cursory look. Some notes:

At step 2900 the following curious CLUT setup is used while reading a 64x64 texture:

![image](https://user-images.githubusercontent.com/130929/183422210-f9077ccf-9815-428b-a3e3-1a66dc3607f9.png)

Which is, use a CLUT32 format, and extract the alpha channel and use that to do a lookup with its bottom bits (mask 0x1f) into a palette. The CLUT has a weird choppy alpha/gray gradient. Unlike my first instinct told me, stencil tricks do not seem to be involved here though, if there are tricks, it's how they fill alpha.

And indeed, right before drawing the shadow, it draws stuff to the top left 64x64 of the main framebuffer, drawing a hidden image which is the shadow, into the alpha bits, using alpha bit masking (a PSP-specific feature):

![image](https://user-images.githubusercontent.com/130929/183423717-67e5081a-6858-465f-aed8-6292505db2d6.png)

Note that e0 is the inverse mask of 1f, which matches the depal setup.

We do have a compat feature to (slowly) simulate bitmasking, let's see if it helps...

**Comment by unknownbrackets** [comment]
The stencil test is not supposed to be applied in clear.  However, the stencil/alpha write mask is supposed to be applied, always.  That is not an error.

-[Unknown]

**Comment by unknownbrackets** [comment]
Looking at the dump, it does work in software rendering.  The first draw to 64x64 is 2761/2926 in this frame dump.

At this point (in softgpu), the stencil values are zero before the clear, so it doesn't actually do anything or matter.  Vulkan seems to be the same.

At 2900 in Vulkan, I see stencil values in the buffer but the alpha value is still zero.  Then we sample from alpha.  But that's without the shader bitmask.

-[Unknown]

**Comment by hrydgard** [comment]
Hm, right. There's at least some weird interaction between the alpha mask and the stencil test that we don't get right ... and the reason the ref value is 0 during the clear (setting the stencil value to that) is that software transform of the clear sets result->setStencil to the color value of a corner. The vertex indeed contains a 0 alpha value so that seems right, but it seems to me to preclude the rest of the shadow rendering from doing anything.

The software renderer does render the shadow correctly. 

I'm moving on from this for today (will get back to it at some point of course), but feel free to have a look if you like a little stencil mystery.

**Comment by hrydgard** [comment]
The shader bitmasking emulation does seem to want to set the right bits, I think, but the EQUAL stencil test fails the draw.

**Comment by hrydgard** [comment]
Please test again on a build where #15822 is merged, should work. Thanks @unknownbrackets ! Tricky stuff due to the stencil/alpha conflation.

**Comment by benderscruffy** [comment]
[v1.13.1-249-gf80dd088b](https://github.com/hrydgard/ppsspp/commit/f80dd088b83a62500434a206213f762eb2d6bbf0)
![Capture](https://user-images.githubusercontent.com/2696404/183911177-7fb6626f-37a0-4a9d-b3fc-cf6e045b0bb3.PNG)
fixed
