### ISSUE TITLE
[MSVC] ppsspp project failed with running tests on Windows

### ISSUE THREAD

**Issue by shizhuoer** [hrydgard/ppsspp#15817]
### Game or games this happens in

None

### What area of the game / PPSSPP

Hi All,

The MSVC team recently test Ppsspp project failed to run "python test.py --graphics=software 2>&1" test on windows platform. Could you please help look at this issue? Thanks in advance.

**Repro steps:**
git clone https://github.com/hrydgard/ppsspp F:\gitP\hrydgard\ppsspp
mkdir build_amd64 & cd F:\gitP\hrydgard\ppsspp\build_amd64
msbuild /m /p:Platform=x64 /p:Configuration=Release ../Windows/PPSSPP.sln /t:Rebuild /p:OutDir=F:\gitP\hrydgard\ppsspp\build_amd64 2>&1
cd F:\gitP\hrydgard\ppsspp
python test.py --graphics=software 2>&1

**Error Info:**
Please check the test.log for the details.

Failed tests:
  cpu/fpu/fcr
  cpu/vfpu/convert
  cpu/vfpu/prefixes
  cpu/vfpu/vector
  cpu/vfpu/vregs
  audio/atrac/replay
  audio/atrac/second/resetting
  audio/sceaudio/datalen
  audio/sceaudio/output
  audio/sceaudio/reserve
  audio/sascore/setadsr
  audio/mp3/infotoadd
  audio/mp3/init
  audio/mp3/notifyadd
  audio/output2/frequency
  audio/output2/release
  audio/output2/rest
  ccc/convertstring
  display/hcount
  font/fonttest
  font/charglyphimage
  font/charglyphimageclip
  font/charinfo
  font/newlib
  font/open
  font/openfile
  font/openmem
  font/shadowglyphimage
  font/shadowglyphimageclip
  font/shadowinfo
  gpu/clipping/guardband
  gpu/commands/cull
  gpu/commands/light
  gpu/complex/complex
  gpu/depth/precision
  gpu/displaylist/state
  gpu/filtering/linear
  gpu/filtering/nearest
  gpu/filtering/precisionlinear2d
  gpu/filtering/precisionlinear3d
  gpu/filtering/precisionnearest2d
  gpu/filtering/precisionnearest3d
  gpu/ge/get
  gpu/primitives/bezier
  gpu/primitives/continue
  gpu/primitives/invalidprim
  gpu/primitives/lines
  gpu/primitives/linestrip
  gpu/primitives/points
  gpu/primitives/rectangles
  gpu/primitives/spline
  gpu/reflection/reflection
  gpu/rendertarget/rendertarget
  gpu/signals/continue
  gpu/signals/jumps
  gpu/signals/simple
  gpu/simple/simple
  gpu/triangle/triangle
  gpu/vertices/colors
  gpu/vertices/texcoords
  intr/registersub
  intr/releasesub
  intr/waits
  io/directory/directory
  io/file/file
  io/file/rename
  io/io/io
  io/iodrv/iodrv
  io/open/tty0
  net/http/http
  net/primary/ether
  power/freq
  rtc/convert
  sysmem/partition
  threads/callbacks/cancel
  threads/callbacks/count
  threads/callbacks/notify
  threads/scheduling/dispatch
  threads/scheduling/scheduling
  threads/threads/create
  threads/threads/terminate
  threads/tls/get
  threads/vpl/create
  umd/io/umd_io
  umd/raw_access/raw_access
  umd/wait/wait
  utility/msgdialog/dialog
  utility/savedata/getsize
  utility/savedata/idlist
  utility/savedata/secureversion
  utility/savedata/sizes
  utility/systemparam/systemparam
  video/mpeg/basic
  video/pmf/pmf
  video/pmf_simple/pmf_simple
  video/psmfplayer/basic
  video/psmfplayer/configplayer
  video/psmfplayer/getvideodata
  video/psmfplayer/playmode
  video/psmfplayer/selectstream
  video/psmfplayer/setpsmfoffset
  video/psmfplayer/start
  video/psmfplayer/update

### What should happen

These failed tests should be run pass.

### Logs

[test.log](https://github.com/hrydgard/ppsspp/files/9287749/test.log)

### Platform

Windows

### Mobile phone model or graphics card

None

### PPSSPP version affected

None

### Last working version

None

### Graphics backend (3D API)

Other

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
Please use the `-g` flag.  See here:
https://github.com/hrydgard/ppsspp/blob/4a29b67dad345e36fed16a93d3603729c2be21ac/.github/workflows/build.yml#L111

These tests are generated on real PSP devices and some of the tests still don't match exactly.  `-g` runs only known passing tests.

Generally, these have issues already.  I don't think it's useful to have a separate meta-issue, so I'm going to close this.

-[Unknown]
