### ISSUE TITLE
Boku no Natsuyasumi 4: Setouchi Shounen Tanteidan missing part of the title screen

### ISSUE THREAD

**Issue by benderscruffy** [hrydgard/ppsspp#15816]
### Game or games this happens in

Boku no Natsuyasumi 4: Setouchi Shounen Tanteidan UCJS10095

### What area of the game / PPSSPP

bottom part of the title screen is missing
![PPSSPP v1 13 1-237-g9a678406b 9_08_2022 10_42_42 AM](https://user-images.githubusercontent.com/2696404/183552581-bc96d910-bdeb-4f0c-9d92-f7461cc8826c.png)

here is a GE dump
[UCJS10095.zip](https://github.com/hrydgard/ppsspp/files/9286364/UCJS10095.zip)

### What should happen

here is what it is supposed to look like
![01852-01](https://user-images.githubusercontent.com/2696404/183552670-6471b761-cf69-4d9f-9ba9-4724ddc8d570.jpg)

### Logs

[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/9286377/ppsspplog.zip)

### Platform

Windows

### Mobile phone model or graphics card

AMD RX 580

### PPSSPP version affected

PPSSPP v1.13.1-237-g9a678406b

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
The lower part is drawn at 2/31 - 8/31, and the vertices each have a 0 value for Z.  This transforms to 65514.000000.  Max Z is set to 65530 (0xFFFA.)

For some reason, this causes it not to draw.  Obviously, there's something wrong with the depth comparison here.

Notably, the minz is 0, and depth clamp is off.  So it should be killing all values outside the [0, 65530] range.  Instead, 0xFFFC fails even, and 0xFFFD (65533) finally allows the draw.  So the error is not small (19.)

I haven't looked into it more than that, but this happens in both Direct3D 11 and Vulkan, but does not happen in OpenGL or Direct3D 9.  Software renderer is fine as well.

-[Unknown]

**Comment by unknownbrackets** [comment]
273b9a3dc161cf18629dfc8a4077e475803bb7da introduced this problem for Vulkan, so it's an accuracy issue with that.

The prims in question are triangle strips, so not sure if it could be a precision issue (it doesn't happen in OpenGL...) or some kind of math issue.

-[Unknown]

**Comment by benderscruffy** [comment]
if you don't press start and watch the demo when it comes back to the title screen nothing is wrong
![PPSSPP v1 13 1-247-g3edaeae81 - UCJS10095 _ ぼくのなつやすみ®４ 10_08_2022 2_22_36 PM](https://user-images.githubusercontent.com/2696404/183830029-e4285f1b-39a2-4d09-ae0c-59391b6ce423.png)
