### ISSUE TITLE
Ppsspp crashing

### ISSUE THREAD

**Issue by Sommyrex** [hrydgard/ppsspp#15824]
### Game or games this happens in

Prince of persia revelation 

### What area of the game / PPSSPP

The game starts normally but after like 50 sec ppsspp crash,please 🥺 solve this issue 

### What should happen

It shouldn't crash anymore 

### Platform

Android

### Mobile phone model or graphics card

Techno Camon18i 

### PPSSPP version affected

1.13.1

### Last working version

1.12.3

### Graphics backend (3D API)

Vulkan

### Checklist

- [ ] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [x] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by Sommyrex** [comment]
I love everything about the new version including color tint you guys are the best,but please solve the issue of crashing while playing prince of persia revelation that's all👍.

**Comment by Gamemulatorer** [comment]
Dup of https://github.com/hrydgard/ppsspp/issues/15776

**Comment by Gamemulatorer** [comment]
@Sommyrex I tried this didn't crash for 60 seconds of playing.
Can you show us the CRC of your game?
![Screenshot_2022-08-12-22-34-45-374_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/184377242-6316b937-bbb4-4100-befc-11ce6032261d.jpg)

**Comment by Sommyrex** [comment]
![Screenshot_20220813-201931](https://user-images.githubusercontent.com/91244272/184507834-ba8e7d71-b94f-4cc8-869f-f4b5ec24205b.jpg)
Here it is

> @Sommyrex I tried this didn't crash for 60 seconds of playing. Can you show us the CRC of your game? ![Screenshot_2022-08-12-22-34-45-374_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/184377242-6316b937-bbb4-4100-befc-11ce6032261d.jpg)
