### ISSUE TITLE
Hot Pixel graphic glitches

### ISSUE THREAD

**Issue by benderscruffy** [hrydgard/ppsspp#15827]
### Game or games this happens in

Hot Pixel ULUS10298

### What area of the game / PPSSPP

after each mini game the picture of the guy is glitchy
here is a GE Dump
[ULUS10298.zip](https://github.com/hrydgard/ppsspp/files/9300224/ULUS10298.zip)
![PPSSPP v1 13 1-247-g3edaeae81 - ULUS10298 _ Hot Pixel 10_08_2022 8_25_54 PM](https://user-images.githubusercontent.com/2696404/183908358-f84617c6-0599-489b-b370-b3af38f0f58c.png)
![PPSSPP v1 13 1-247-g3edaeae81 10_08_2022 8_24_58 PM](https://user-images.githubusercontent.com/2696404/183908364-aa9a61f8-4f3e-48cc-b97f-f22763c64aaa.png)
![PPSSPP v1 13 1-247-g3edaeae81 10_08_2022 8_24_58 PM (3)](https://user-images.githubusercontent.com/2696404/183908378-bb6c9424-38df-4e42-a68b-cddf9bdaedd7.png)
![PPSSPP v1 13 1-247-g3edaeae81 10_08_2022 8_24_59 PM](https://user-images.githubusercontent.com/2696404/183908382-c64476ba-5a7f-4aca-bf71-143597ca6466.png)
![PPSSPP v1 13 1-247-g3edaeae81 10_08_2022 8_25_17 PM (2)](https://user-images.githubusercontent.com/2696404/183908385-5f45910b-8432-4131-853e-1274fee0b199.png)

### What should happen

guy is not glitchy

### Platform

Windows

### Mobile phone model or graphics card

AMD RX 580

### PPSSPP version affected

PPSSPP v1.13.1-247-g3edaeae81

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Hm, can't reproduce this at all, at least not on the latest builds.

![ULES00642_00000](https://user-images.githubusercontent.com/130929/188392160-e8ce54d9-52ed-465d-b77c-9ff06381835a.jpg)
[hot pixel ge dump.zip](https://github.com/hrydgard/ppsspp/files/9487601/hot.pixel.ge.dump.zip)

**Comment by benderscruffy** [comment]
https://github.com/hrydgard/ppsspp/commit/0126bc181c92cc63dbfa923ddc7b589c56a840ba
still an issue for myself 
doesn't happen in software renderer
maybe an AMD problem ???

**Comment by benderscruffy** [comment]
Closing as have new system and cannot test on old pc
