### ISSUE TITLE
Dream C Club Portable missing background

### ISSUE THREAD

**Issue by benderscruffy** [hrydgard/ppsspp#15823]
### Game or games this happens in

Dream C Club Portable ULJS00333	

### What area of the game / PPSSPP

as you talk to the first lady the background is missing
![PPSSPP v1 13 1-247-g3edaeae81 - ULJS00333 _ ドリームクラブ Portable 10_08_2022 4_26_47 PM](https://user-images.githubusercontent.com/2696404/183854575-be68a9b8-52df-4308-aa7b-71ab5dec74ea.png)

here is a GE dump
[ULJS00333.zip](https://github.com/hrydgard/ppsspp/files/9298278/ULJS00333.zip)

### What should happen

here is how it should look
![02390-04](https://user-images.githubusercontent.com/2696404/183854890-439775eb-ebc9-4959-bc88-63b0587474aa.jpg)

### Logs

[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/9298305/ppsspplog.zip)

### Platform

Windows

### Mobile phone model or graphics card

AMD RX 580

### PPSSPP version affected

PPSSPP v1.13.1-247-g3edaeae81

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
This seems to be a depal issue.  Introduced in one of these commits from a quick bisect (#15789):

4e3c2581404fceb65b2f15096b267ae2f0db005d
81c36578ca78f0b68e5b5e829573a1e316053caa
92a3d4534021f7f12881b4b3e46dbc1af12ef700
b5597d10134d9c084b7450136a703036187cf032
45def772eeb3ed908ebb9cd478504db8ffd80461
de10c1fddd18ed09a89c5883dc9b87509f2da4f4
87b128ecaf1e98b156613544d39e69957036aa5a
9a5893ce6ef79fcf8185d07198c9da60f7b0c6f9
ded8ba8806b7818457ad7b705046136d6fb2fc2b

The source framebuffer shows transparent in these areas in the GE debugger when texturing from them (but it is using a CLUT.)  It has both alpha test (> 0) and standard alpha blend, but it ends up drawing a solid brownish color.

-[Unknown]
