### ISSUE TITLE
"Star Wars - The Force Unleashed" pseudo crt lines graphics glitch (now: performance issue)

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#15832]
### Game or games this happens in

ULUS10345

### What area of the game

After fixing the red overlay graphics glitches here's a new graphic issue the pseudo crt line that produce on some stages as mentioned here https://github.com/hrydgard/ppsspp/issues/9572
![Screenshot_2022-08-11-22-59-33-064_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/184165244-0383485d-e63b-4828-9367-44a64ba6253a.jpg)

### What happens

Pseudo CRT Line Graphics Rendering Glitch.
![Screenshot_2022-08-11-23-06-30-755_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/184166869-d8c456c4-0f65-4734-8822-c749b48a3149.jpg)

### What should happen

No pseudo CRT line graphics issue
Also can be workaround by ***lower resolution for effects*** set to aggresive but can still notice some white line.
![Screenshot_2022-08-11-23-06-42-765_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/184166372-5e8fef90-bb77-48e5-a112-db3642ac3cf6.jpg)

### GE frame capture

[ULUS10345.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/9309738/ULUS10345.ppdmp.zip)

### Platform

Android

### Mobile phone model or graphics card

Redmi Note 9 Android 12 Helio G85 Mali-G52 GPU

### PPSSPP version affected

v1.13.1 above

### Last working version

1.12.3

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by Gamemulatorer** [comment]
***Software***
![Screenshot_2022-08-12-23-27-07-976_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/184388273-95d6c6a2-e7bf-43e6-aa7f-a7d81722bd7c.jpg)

***Hardware (skip-buffer effects)***
![Screenshot_2022-08-12-23-27-31-162_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/184388425-fae1757f-3f54-4c9d-9512-e0ce6b955380.jpg)

**Comment by Gamemulatorer** [comment]
OpenGL shader compilation error
![Screenshot_2022-08-26-18-51-03-625_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/186895629-c05d7cc4-03f5-444a-a37d-0f71786c620f.jpg)

**Comment by hrydgard** [comment]
@Gamemulatorer thanks for reporting, I'll fix right away

**Comment by hrydgard** [comment]
Fixed

**Comment by Gamemulatorer** [comment]
![Screenshot_2022-09-01-10-43-26-969_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/187820981-6e0cb35f-cb8d-448b-83b7-a277192c360d.jpg)
Cannot reproduce this on snapdragon 680 adreno 610 gpu

**Comment by Gamemulatorer** [comment]
@SilentMRG can you still repruduce?

**Comment by SilentMRG** [comment]
> @SilentMRG can you still repruduce?

To be honest, I haven't tested it yet. I'm using version 1.13, and when I have some time to spare I'll update and retest this title. At the moment, I'm out of time. Thanks for asking!

**Comment by unknownbrackets** [comment]
Any fixes would be in the latest git build - no retroactive changes are made to released versions.  This is known broken on v1.13.1 and will always be broken on that version.  However, recent git builds may have improved things.

-[Unknown]

**Comment by Gamemulatorer** [comment]
This issue I can only reproduce on mali gpu's adreno gpu's cannot reproduce this.

**Comment by SilentMRG** [comment]
> can you still repruduce?

I just tested on version 1.13.2 and the pseudo CRT filter is still there. The only good thing I noticed is that there was a noticeable performance gain and I didn't need to activate frame skipping.

**Comment by Gamemulatorer** [comment]
> > can you still repruduce?
> 
> I just tested on version 1.13.2 and the pseudo CRT filter is still there. The only good thing I noticed is that there was a noticeable performance gain and I didn't need to activate frame skipping.

Can you test the latest build https://buildbot.orphis.net/ppsspp/index.php?m=fulllist

**Comment by SilentMRG** [comment]
> Can you test the latest build

Apparently in the build: v1.13.2-1013-gc80cc1e87 - 2022-09-17 23:35:15

The pseudo CRT filter has been fixed!!! \o/ HOWEVER, the frame rate is the opposite of version 1.13.2, to give you an idea, it was around 15 fps. And not even skipping 8 frames solved it. XD

**Comment by Gamemulatorer** [comment]
> > Can you test the latest build
> 
> Apparently in the build: v1.13.2-1013-gc80cc1e87 - 2022-09-17 23:35:15

Nice!

> The pseudo CRT filter has been fixed!!! \o/ HOWEVER, the frame rate is the opposite of version 1.13.2, to give you an idea, it was around 15 fps. And not even skipping 8 frames solved it. XD

What is your device?

**Comment by hrydgard** [comment]
Such a slowdown is surprising, gonna need to investigate that.

**Comment by SilentMRG** [comment]
> What is your device?

Windows 7 Ultimate 64 bit
i5 2.67 GHz
4 GB DDR3
Intel HD Graphics 1000
It's an 11-year-old Laptop Grandpa! XD

And yes... I know it's a potato device, but I think the problem, in this case, is not on my side.

**Comment by hrydgard** [comment]
No, I don't think so either.

**Comment by Gamemulatorer** [comment]
Changing from skip buffer to buffer rendering causes this.
![Screenshot_20221108_092617_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37603562/200451309-6831cd92-5b66-4c58-960b-917b5c16ad93.jpg)

**Comment by SilentMRG** [comment]
On Windows and version 1.14 (except the backend, all settings are at default), using DirectX 9, I got this...

![0](https://user-images.githubusercontent.com/62117728/208008483-25c5a744-2035-447d-8992-b496021f3639.png)
![1](https://user-images.githubusercontent.com/62117728/208008544-ea4c4c9f-8493-495f-b2fb-697b755dbc17.png)
![2](https://user-images.githubusercontent.com/62117728/208008611-12acbfed-e31a-4cf6-aa79-2628f67f7d7a.png)

I confess that I liked the lightning effect! It even looks like a high definition effect. XD

**Comment by Gamemulatorer** [comment]
@SilentMRG how about the performance?

**Comment by SilentMRG** [comment]
> how about the performance?

FPS goes from 30 to 45/60, and drops to 30 and back to 45.

**Comment by Gamemulatorer** [comment]
> > how about the performance?
> 
> FPS goes from 30 to 45/60, and drops to 30 and back to 45.

What is the performance now using recently build PPSSPP?

**Comment by Gamemulatorer** [comment]
Closing this performance is acceptable on my phone :)

**Comment by Gamemulatorer** [comment]
> > how about the performance?
> 
> FPS goes from 30 to 45/60, and drops to 30 and back to 45.

I discover that if you change emulated psp cpu clock speed to 666mhz this game will lock to 60fps.
