### ISSUE TITLE
Texture dumping glitch.

### ISSUE THREAD

**Issue by Saramagrean** [hrydgard/ppsspp#15831]
### Game or games this happens in

ULJM06097 - Musou Orochi 2 Special (Japan)

### What area of the game

In-gameplay.

### What happens

Texture in-gameplay and GE debugger is look correct. but when enabled "Save new textures" is always dump (weapon)texture glitch. (show green color only), it happem on all backends.

![GE0](https://user-images.githubusercontent.com/26355472/186454034-fe67ac40-3d26-46c0-b4ec-ef577b4d2342.png)

### What should happen

Can dump (weapon)texture without glitch.

![GE1](https://user-images.githubusercontent.com/26355472/186454429-28b6dcfc-1537-4721-81d2-939fd6876ea1.png)

### GE frame capture

Texture in-game is look fine, It happen when dump textures.

### Platform

Windows

### Mobile phone model or graphics card

Intel HD Graphic 520.

### PPSSPP version affected

v1.13.1-17-g7d4d925a3.

### Last working version

v1.13.1-12-g512382c4d.

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
Based on the image, I assume this is from ef4a6cf873412c220272b49950fa4741a33d326d.  I don't see anything in that commit that ensures decoded images are always decoded to 8888 before being sent to NotifyTextureDecoded, i.e. if `scaleFactor` was 1 and `replaced` was not valid (because it needs to be saved.)

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, quite clearly missed accounting for this in my refactor. Gonna fix it, but a bit differently.

**Comment by Saramagrean** [comment]
Found another problem, if use OpenGL + texture pack. texture preview is alway zoom. 😅
