### ISSUE TITLE
[Regression] Crisis Core FMVs showing a black screen

### ISSUE THREAD

**Issue by bslenul** [hrydgard/ppsspp#15867]
### Game or games this happens in

ULUS10336 - Crisis Core

### What area of the game / PPSSPP

FMVs just show a black screen, simply boot the game and you'll see that the background is entirely black:

![image](https://user-images.githubusercontent.com/33353403/185723252-adda117e-5a3e-4a19-8449-a2f35ff8e689.png)

### What should happen

The FMV should be playing in the background:

![image](https://user-images.githubusercontent.com/33353403/185723261-892d06d3-b14a-450d-b1d6-332f2cca80ea.png)

### Platform

Windows

### Mobile phone model or graphics card

GTX 970

### PPSSPP version affected

Already bisected, the first bad commit is fde369332bb5f2b8948229554f2f1cb85a03e476

### Last working version

Last working commit is 31773b42bad5202402f0ed8af577f3bdceb1c2ae

### Graphics backend (3D API)

Vulkan / D3D11 / GL

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Thanks, I'll look into it.

**Comment by bslenul** [comment]
Thank you for the quick fix!
