### ISSUE TITLE
Android 11 Vulkan problem

### ISSUE THREAD

**Issue by clondy999** [hrydgard/ppsspp#15864]
### Game or games this happens in

Any game

### What area of the game / PPSSPP

I use ppsspp on tablets using A133 SOC. The Android version is 11, but why is there no Vulkan option? Only OpenGL

### What should happen

Can choose Vulkan

### Logs

null

### Platform

Android

### Mobile phone model or graphics card

Allwinner A133 SOC

### PPSSPP version affected

1.12.3

### Last working version

1.12.3

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment]
Allwinner A133 SoC have PowerVR GE8300 GPU right? 
it should support Vulkan 1.1 according to https://www.notebookcheck.net/PowerVR-GE8300-GPU-Benchmarks-and-Specs.420311.0.html

**Comment by Gamemulatorer** [comment]
@clondy999 can you try devcheck and screenshots your hardware info.
https://play.google.com/store/apps/details?id=flar2.devcheck

**Comment by unknownbrackets** [comment]
Do other apps, emulators, or games support Vulkan on your same device?

Some manufacturers provide Android OS updates without driver updates - you might be using ancient graphics drivers that don't support Vulkan.  This is unfortunately up to whoever is delivering the OS updates for your phone.  If your device doesn't have Vulkan-supporting graphics drivers, it can't use Vulkan.

-[Unknown]

**Comment by Gamemulatorer** [comment]
@clondy999 no feedback?

**Comment by clondy999** [comment]
I'll try to install the application you provided
I have no Internet these days, so I have no feedback. Sorry

**Comment by clondy999** [comment]
@ANR2ME YES~

**Comment by clondy999** [comment]
I follow the software prompts. Prompts my hardware to support Vulkan @Gamemulatorer

**Comment by Gamemulatorer** [comment]
> I follow the software prompts. Prompts my hardware to support Vulkan @Gamemulatorer

How about now?

**Comment by Gamemulatorer** [comment]
No feedback/outdated?

**Comment by unknownbrackets** [comment]
Going to close this assuming it's an OS driver issue.  If you've got more detail, please comment and we'll reopen.

-[Unknown]
