### ISSUE TITLE
Dream C Club Portable (Japan)  glitchy woman in software renderer

### ISSUE THREAD

**Issue by benderscruffy** [hrydgard/ppsspp#15876]
### Game or games this happens in

Dream C Club Portable (Japan) (v1.01)

### What area of the game / PPSSPP

in software renderer the black lines around the woman like the face is broken 
here is a ge dump
[Uploading ULJS00333.zip…]()

![ULJS00333_00000](https://user-images.githubusercontent.com/2696404/185782112-d020df24-d8d9-4cd9-8357-8894d3a0d665.jpg)

### What should happen

solid black lines around the woman

### Platform

Windows

### Mobile phone model or graphics card

AMD RX 580

### PPSSPP version affected

PPSSPP v1.13.1-391

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
The dump didn't upload but I think it's the same scene as #6497 which has a frame dump.

Strangely, the character is invisible running from headless (which should not be...), but renders fine within PPSSPPWindows64.  I don't know why this is, and it seems a bit concerning... softjit and threading seem unrelated, though.  Will have to come back to that...

As for the character, she is drawn through 1295/1533 to 0x040cc000.  It then textures from there, using a CLUT, to draw the outline around the character.  This uses through, X=-0.5, Y=0.25 compared to the texture.  At 1336/1533, it does another outline pass, this time X=-1.6, Y=1.25 (again, through.)  Then yet another pass at 1376/1533, this time X=0.6, Y=-1.25.  Finally, at 1416/1533 it draws the character with X=0, Y=0.

From what I can tell, the X=0.6 draw doesn't really draw to the right enough.

If I disable `RectangleFastPath()`, it seems to correct it (but not headless...):
![Outline without RectangleFastPath](https://user-images.githubusercontent.com/191233/185805094-f925bd83-c95c-4a2a-9c54-4b20143e304e.png)

Which looks similar to the PSP rendering (the left side looks perhaps still a bit too thick):
![#6497_ULJS00333_dreamclub_depth_girl](https://user-images.githubusercontent.com/191233/185805118-d8270810-f5f0-4483-95b3-ae1a3ee15ffb.png)

This draw is CLUT16/5551, simple alpha test and blend, modulate, and no depth test - and the target is 5551 too.  Basically `DrawSprite()`'s favorite thing.  I think it ends up with s/t slightly off.

-[Unknown]

**Comment by unknownbrackets** [comment]
Just for posterity, the headless issue is also fixed, I think it was 05ad644 or similar.

-[Unknown]
