### ISSUE TITLE
IL-2 Sturmovik - Birds of Prey graphic glitches in software renderer

### ISSUE THREAD

**Issue by benderscruffy** [hrydgard/ppsspp#15875]
### Game or games this happens in

IL-2 Sturmovik - Birds of Prey (USA)

### What area of the game / PPSSPP

just start a new game in software renderer mode and on the left hand side of the screen is white glitchy flashing lines and when you turn your plane to the left it shows even more
doesn't happen in the other modes
here is a ge dump 
[ULUS10476.zip](https://github.com/hrydgard/ppsspp/files/9388656/ULUS10476.zip)
dont know if it captured it
![PPSSPP v1 13 1-391-g5097a6a8f - ULUS10476 _ IL-2 STURMOVIK_ BIRDS OF PREY 21_08_2022 3_48_09 PM](https://user-images.githubusercontent.com/2696404/185781411-a352b938-25ea-4c3b-8db9-ce3872030258.png)
![ULUS10476_00000](https://user-images.githubusercontent.com/2696404/185781412-d4eb81d6-45f3-42bd-8a4b-4cdee1882630.jpg)
![ULUS10476_00003](https://user-images.githubusercontent.com/2696404/185781413-f503fa4f-19c9-45b2-a02b-3946dc35ac7a.jpg)
![ULUS10476_00005](https://user-images.githubusercontent.com/2696404/185781414-0763fbbc-8b58-485c-8353-25daf21c533b.jpg)

### What should happen

no flashing glitchy lines

### Platform

Windows

### Mobile phone model or graphics card

AMD RX 580

### PPSSPP version affected

PPSSPP v1.13.1-391

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
These artifacts are introduced at 1490/1954 in this frame dump.  They're meant to be clouds.

All the x/y coordinates are well outside the screen, but not far enough to be culled.  Depth is fine, depth testing is off, and minz/maxz allow all Z values involved.

We're probably just slightly off in where we think these pixels fit and they shouldn't end up getting drawn at all.

-[Unknown]

**Comment by unknownbrackets** [comment]
This is actually similar to the issue seen in #16207.  In this case, the verts are such that a positive w becomes negative during clipping, which inverts these triangles that would otherwise be offscreen.

Clipping against `w >= 0` would solve this one, although it seems like that's not correct (although my tests produced positive values from `z > -w` clipping, so maybe it discards or clips when w is negative in that result?)  That would not explain #16207, though, and I suspect whatever should be clipping or culling those triangles is most likely what should be doing so for these.

-[Unknown]

**Comment by hrydgard** [comment]
Re-opening since #16470 only fixed this for the software renderer.

However, #21715 fixes this for all renderers.
