### ISSUE TITLE
Rendering issues in Tantalus Media games (Spongebob, MX ATV, etc)

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#15898]
As Gamemulatorer pointed out in https://github.com/hrydgard/ppsspp/issues/9018#issuecomment-911914556 , these games have weird rendering techniques in common.

All except MegaMind (and it seems MX vs ATV: On The Edge) render a very complicated striped post-processing effect, that doesn't actually seems to do very much (EDIT: it applies textured depth fog).

The details seem to vary a bit from game to game but all have in common copying the screen in small stripes to a temporary and doing strange processing there, involving depth texturing and reinterpret between 16 and 32-bit formats. I created this common issue where I'll write up any progress and link PRs to.

We are currently very unsuccessful emulating this, but I think it's not quite as hard as it looks.

Features I think we need to implement for this to work: 

- [x] #15892
- [x] Detect use of a framebuffer living in the "stride gap" of another one and adjust its width accordingly (and make sure it doesn't get detected as the same texture as the big one)
- [x] Probably smarter interactions between block copies and framebuffers, taking the new sequence numbers into account etc. In the end, we might to share framebuffer match detection logic between block copies, textures and framebuffers...
- [x] 32-bit<->16-bit format reinterpret: #15907

Still will likely not perform very well, but better than nothing.

Details are in the various sub-issues:

- #9850
- #9604
- #9018

**Comment by Panderner** [comment]
It's seems MX vs. ATV On the Edge working fine
![Screenshot_2022-08-24-19-06-53-321_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/186404108-ac5abfcb-a24c-4383-b05c-01cf9d3d8e35.jpg)

**Comment by hrydgard** [comment]
I'm starting to understand the idea of the effect in Spongebob, although I'm currently getting this:

![image](https://user-images.githubusercontent.com/130929/186889479-268a90c2-30bd-4849-b235-3b6ee2ccef1a.png)

The whole idea is to get depth into the alpha bits of the main RGBA8888 framebuffer, so that at the end, a background image can be blended to it using destination alpha, giving a "textured fog" effect (in the distance, things will fade into the image instead of just a single color).

The screen is processed in 16-pixel-wide vertical strips, first every other strip, then it fills in with the second set.

There's a special strip buffer, 16 pixels wide, which is used both as an 8888 buffer or a 32-pixel-wide 565 buffer as required.

First, depth is copied into the strip and stretched twice as wide, using CLUT16 depal texturing from Z. There seems to be something going wrong here, since we get a quickly repeating gradient instead of a single one. Anyway, the depal puts the gradient into blue and red bits of each 16-bit, as follows:

```
16-bit 2 pixels:
BBBBBGGGgggrrrrrBBBBBGGGgggrrrrr  where capitals are set bits
32-bit 1 pixel:
AAAAAAAArrrrrrrrGGGGGGGGbbbbbbbb
```

When reinterpreted as halfwidth 32-bit 8888, these blue and green bits end up in alpha (!) and green (ignored), as seen above.

Next, the main color buffer is drawn on top, writing only to R G and B. As a result, in our thin stripe, we now have A=depth while RGB comes from the main buffer.

This stripe is now copied back into position in the main image using a block transfer.

Repeat until the whole image is processed. One more pass is done across the screen whose purpose I haven't yet determined (but it seems to only affect sky pixels), then as stated above, a large image is blended on top of the screen, with blend mode set t DST_ALPHA / ONE_MINUS_DST_ALPHA.

As can be seen in the above screenshot, not all of that is working perfectly, but the process is now partially working, just need to figure out the remaining issues...

**Comment by hrydgard** [comment]
Just noticed that the depth texturing is done from 0x288000, not 0x688000 which we might have expected if the game used the full swizzle from +6MB. So the game is actually reading the depth buffer in the +2MB format seen here, where 32-pixel-wide columns are swapped around: http://hitmen.c02.at/files/yapspd/psp_doc/chap10.html#sec10.2 

Maybe they just didn't know about the full swizzle at +6MB?

Either way, that means that we have to emulate the column-swapping swizzle during depth depal.

**Comment by hrydgard** [comment]
I think we can conclude that on the PSP, to find the corresponding Z pixel from a FB pixel coordinate when rasterizing, the following transforms are applied, forming the "Swizzle":

1. Bit 4 and 8 of the X coordinate are swapped with each other
2. The Y coordinate is xor-ed by 3
3. Possibly a byteswap, upper/lower? to be confirmed, but would explain the wacky shift somewhat

Since this was annoying when doing depth effects, hardware was added to the read path, to:

* if address & 0x200000, do 2 in reverse
* if address & 0x600000 == 0x60000, do 1, 2, and 3 in reverse

Since we don't store our Z buffers swizzled, we simply have to reverse these when the two address rules would have been applied.

**Comment by hrydgard** [comment]
![image](https://user-images.githubusercontent.com/130929/186924295-da84cba9-90ce-40a9-87f7-e42cb3e59769.png)

Most of the swizzle seems to be right. Still having the weird issue with the lookup.

**Comment by hrydgard** [comment]
Note to self: The missing stripe is because due to the swizzle, we need to expand the depal surface all the way out to 512 (or beyond?) in width, since the last column won't be in the expected place...

**Comment by hrydgard** [comment]
![image](https://user-images.githubusercontent.com/130929/186936408-8833b71c-2a32-4068-9ef6-4157b62a4122.png)

That's better.

Now only the weird color ramp repeat left... I'm stumped there.

**Comment by hrydgard** [comment]
On real hardware, the gradient is not actually visible, at leats not in this scene, maybe because it's very small at the horizon. If I change the code to clamp instead of wrap during the lookup, I get an image that matches hardware.

However, that's just a wild guess. Think I'm gonna have to dust off the PSPSDK and write a hardware test...

**Comment by hrydgard** [comment]
No, I think there's another step that fails. Towards the end, just before blending the background, the game attempts to initialize the stencil buffer from a depth test, I think (red/green mask is depth test results in RenderDoc):

![image](https://user-images.githubusercontent.com/130929/186997588-40ec57a1-2fe6-4070-83f5-545b4505313d.png)

![image](https://user-images.githubusercontent.com/130929/186997644-2cef6de3-475e-4a40-a6bd-85592acbaa1e.png)

However, for some reason, the stencil buffer is left unchanged, maybe some slight difference in semantics or we're wrapping it wrong? Need to check in PSP debugger as well. But what ALSO doesn't happen here is that said stencil test should also write zero to alpha! This is similar to the recent shadowing issue in #15813 .

**Comment by hrydgard** [comment]
Yup, that did it. 

![image](https://user-images.githubusercontent.com/130929/187022034-7d4d0216-d0ea-459d-aeda-5b361465f1b8.png)

Still some brokenness to debug on OpenGL and D3D9, but Vulkan and D3D11 look perfect now in Spongebob.

**Comment by hrydgard** [comment]
Cars' solution for the same thing does work on PC GPUs already, it already flips it around to the easy way. However it breaks earlier in a different way, we are texturing from the wrong framebuffer at one point, missing out on a necessary 32->16 reinterpret.

**Comment by hrydgard** [comment]
One trivial bug fix later:

![image](https://user-images.githubusercontent.com/130929/187029515-29d52ab7-4937-4461-909b-4455ad7619fe.png)

Only the stripes left, maybe some precision issue, it's kinda weird.

**Comment by hrydgard** [comment]
Getting closer, 2x:

![image](https://user-images.githubusercontent.com/130929/187034888-676beabc-62e1-400b-a8fc-f5f76eac6b96.png)

1x: 

![image](https://user-images.githubusercontent.com/130929/187034896-72895f06-e3b2-420c-8d8e-847de6b4da49.png)

Note how there's weird yellow fringes in the sky.

Anyway, that might be good enough to get it in, for further improvement afterwards...
