### ISSUE TITLE
Kurohyou2 various graphic glitches and gles crash during loading save in recent version 

### ISSUE THREAD

**Issue by lim2222** [hrydgard/ppsspp#15896]
### Game or games this happens in

NPJH-50562 kurohyou 2

### What area of the game

![Screenshot_2022-08-24-11-27-46-481_org ppsspp ppsspz](https://user-images.githubusercontent.com/35925370/186325355-165d387c-ef85-46c7-85a3-0c7034b11cfc.jpg)
Gles with ppsspp-v1.13.1-438-g15f51c306-android.apk onwards

![Screenshot_2022-08-24-11-28-02-213_org ppsspp ppsspz](https://user-images.githubusercontent.com/35925370/186325367-5e600e8b-51a0-415c-82ac-2932e14adb81.jpg)
Gles with ppsspp-v1.13.1-438-g15f51c306-android.apk onwards

![Screenshot_2022-08-24-11-33-52-945_org ppsspp ppsspz](https://user-images.githubusercontent.com/35925370/186325370-6bd20747-5503-4240-b899-76d32b0a8e15.jpg)
Vulkan with ppsspp-v1.13.1-438-g15f51c306-android.apk onwards

![Screenshot_2022-08-24-11-34-05-064_org ppsspp ppsspz](https://user-images.githubusercontent.com/35925370/186325372-a498c821-230f-4a06-a518-aabba6eee33d.jpg)
Vulkan with ppsspp-v1.13.1-438-g15f51c306-android.apk onwards

![IMG_20220824_113903](https://user-images.githubusercontent.com/35925370/186325375-8bf4b515-4fa5-4a4b-b169-89018a73a50b.jpg)
Vulkan with ppsspp-v1.13.1-438-g15f51c306-android.apk onwards

![IMG_20220824_114025](https://user-images.githubusercontent.com/35925370/186325377-05a3d066-3fac-4b49-8140-029d4aa858f6.jpg)
Vulkan with ppsspp-v1.13.1-438-g15f51c306-android.apk onwards

![IMG_20220824_114137](https://user-images.githubusercontent.com/35925370/186325381-127b8049-8e62-480f-8bed-5505f5faf0cd.jpg)
Gles and vulkan with ppsspp-v1.13.1-380-g044b8d647-android onwards

### What happens

Gles crash during loading save starting from ppsspp-v1.13.1-372-g21cf6a6f0-android .apk

### What should happen

Screenshots from ppsspp-v1.13.1-347-g6cc8ca517-android.apk
![Screenshot_2022-08-24-11-37-14-822_org ppsspp ppsspy](https://user-images.githubusercontent.com/35925370/186325719-3c306ba3-2730-4591-9ecf-626d9e4103ac.jpg)
![Screenshot_2022-08-24-11-37-29-642_org ppsspp ppsspy](https://user-images.githubusercontent.com/35925370/186325740-7328b9e0-34ee-4dbd-8edc-4874659492d9.jpg)
![Screenshot_2022-08-24-11-37-50-636_org ppsspp ppsspy](https://user-images.githubusercontent.com/35925370/186325762-85940ec5-0386-4c6b-ac88-540572158aeb.jpg)

### GE frame capture

[NPJH50562 (1).zip](https://github.com/hrydgard/ppsspp/files/9412755/NPJH50562.1.zip)

### Platform

Android

### Mobile phone model or graphics card

xiao mi 10t pro 

### PPSSPP version affected

v1.13.1-372-g21cf6a6f0

### Last working version

v1.13.1-347-g6cc8ca517

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Thanks for the detailed report, I'll get this fixed. Lots of moving parts right now, but for good reason, as fixes will be coming for a number of long standing issues once I'm done.

**Comment by hrydgard** [comment]
#15897 should have fixed crashes and GL-specific issues. It also contains modified checks for the smooth color ramp, which might help with the weird colors, not sure. Please test!

**Comment by lim2222** [comment]
GL crash and error message fixed by #15897 ,color issues still remain.

**Comment by hrydgard** [comment]
could you get a GE frame dump when the bad colors are showing, or a savestate, and upload here? (zip and drag into the post editor)?  frame dump instructions here: https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

**Comment by lim2222** [comment]
[NPJH50562.zip](https://github.com/hrydgard/ppsspp/files/9416917/NPJH50562.zip)
GE frame dump at convenient store.

[NPJH50562 (1).zip](https://github.com/hrydgard/ppsspp/files/9417009/NPJH50562.1.zip)
GE where by the table of restaurant not cover player's foot.

[PPSSPP_STATE.zip](https://github.com/hrydgard/ppsspp/files/9416949/PPSSPP_STATE.zip)

[PPSSPP_STATE2.zip](https://github.com/hrydgard/ppsspp/files/9416967/PPSSPP_STATE2.zip)

**Comment by hrydgard** [comment]
Thanks, perfect.

**Comment by hrydgard** [comment]
Ok, the game uses color ramps that look like this:

![image](https://user-images.githubusercontent.com/130929/186453835-689f547f-9104-4a65-9572-802f4206bc6a.png)

When we try to filter them smoothly at the top, we end up in trouble. Some slight offset or clamping should fix it, or we should use the mask as part of the CLUT texture key, then we can shrink the texture and use texture clamping directly.

Just had a realization though that we can actually filter these really cheaply when doing shader depal

**Comment by hrydgard** [comment]
Ah, I had the scale factors off-by-one. Should be fixed now.

**Comment by lim2222** [comment]
v1.13.1-471-g67c911d13 fixed color issue,the table see through part can be fixed by turn off upscale level.

**Comment by hrydgard** [comment]
Oh, yeah texture upscale can screw up the depth trickery that this game does. I think we might need a compat flag and some checks to disable upscaling of this type of texture...
