### ISSUE TITLE
Rendering glitches (Monster Hunter) with texture replacement (delayed load)

### ISSUE THREAD

**Issue by Gelo021** [hrydgard/ppsspp#15931]
hi @hrydgard 

Just wanna ask if this is normal 

https://user-images.githubusercontent.com/67460268/187458041-67226b44-948d-4c47-8d7d-144319bf3fec.mp4

**Comment by hrydgard** [comment]
That looks extremly abnormal. That's Monster Hunter, right?

What hardwawre are you playing on? Which version of PPSSPP?

**Comment by Gelo021** [comment]
@hrydgard its a custom texture 
 
When enabling Texture replacement, kindda glitchi

All of the games i think if tried it on Gundum Next plus same thing happen

**Comment by Gelo021** [comment]
Uploading Record_2022-08-30-22-50-35_2f85358b2198d26f8aca533d68bee793.mp4…

**Comment by Gelo021** [comment]
https://user-images.githubusercontent.com/67460268/187470230-d371d238-aa55-40e5-992e-fcb224f9a443.mp4

**Comment by hrydgard** [comment]
Can you try the latest Android build from https://buildbot.orphis.net/ ?

**Comment by Gelo021** [comment]
Yes, btw im currently using 1.13.1.547

Trying the latest build

**Comment by Gelo021** [comment]
Same 
[GE Dump.zip](https://github.com/hrydgard/ppsspp/files/9454578/GE.Dump.zip)


https://user-images.githubusercontent.com/67460268/187486513-71fb5f69-ddff-4c11-b54e-88d5c9037dea.mp4

**Comment by hrydgard** [comment]
That looks so bizarre! But it must have something to do with replacement texture loading going weirdly wrong. Will look into it.

**Comment by iota97** [comment]
Does [build v1.13.1-425](https://buildbot.orphis.net/ppsspp/index.php?m=dl&rev=v1.13.1-425-g39cb2f184&platform=android) make any difference? If so #15884 is likely the culprit.

**Comment by hrydgard** [comment]
OK, thanks. So the question is why the textures turn black while waiting for the replacement ot load, must be some tiny logic bug..

**Comment by Gelo021** [comment]
Maybe like ive tried to smap sa the texture replacement and then some texture goes every where, its gone wild

**Comment by Gelo021** [comment]
@unknownbrackets thank for the fix
