### ISSUE TITLE
Go!Explore - kicks back to PPSSPP home screen

### ISSUE THREAD

**Issue by meowthed** [hrydgard/ppsspp#15932]
### Game or games this happens in

Go!Explore

### What area of the game / PPSSPP

Currently, running any of the Go!Explore discs would boot up before kicking back to the PPSSPP menu screen. These titles require the use of a NavNGo GPS, attached to the USB.

### What should happen

I don't have real hardware to test in hand but I assume that once the title finds the GPS device, it would work fine, just like in this video: https://www.youtube.com/watch?v=o2IHJBbdqfA

### Logs

[ppsspplog.txt](https://github.com/hrydgard/ppsspp/files/9453983/ppsspplog.txt)

### Platform

Other

### Mobile phone model or graphics card

OPPO:CPH2349, Nvidia Geforce GT 740M

### PPSSPP version affected

1.13.1

### Graphics backend (3D API)

Other

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by meowthed** [comment]
yeah, I need someone with a real PSP to test if it does exit to menu if it doesn't find the USB device.

**Comment by sum2012** [comment]
I test Europe version.
From full debug
https://gist.github.com/sum2012/3dcbd12fa1e2796a97470a7014060b66
It do not have sceusb something.
Just like it is missing DLC

**Comment by sum2012** [comment]
Full full debug log ,https://gist.github.com/sum2012/3dcbd12fa1e2796a97470a7014060b66
I only see this usb thread
54:10:418 user_main    D[SCEKERNEL]: HLE\sceKernelEventFlag.cpp:241 291=sceKernelCreateEventFlag(DTECT_USB_GPS_SUSPEND, 00000000, 00000000, 00000000)

**Comment by sum2012** [comment]
It can run in Jpcsp emulator
![1](https://user-images.githubusercontent.com/2177532/187794492-3904b462-ee15-4aa8-b0cc-1946c698ca48.jpg)
From jpcsp log
https://gist.github.com/sum2012/2062c43bb5830b921a25f9bff93720ca
06:03:55  WARN hle.ThreadManForUser - user_main - hleKernelWaitEventFlag already another thread waiting on it

**Comment by ANR2ME** [comment]
Do you also have the logs from real PSP @sum2012 ?

**Comment by ANR2ME** [comment]
> 0x800201b0 = this event flag cannot accept waits with multiple threads
is this mean race condition?
Does the app freezes on real PSP while getting those errors? or you can still see something changes on the screen?

**Comment by sum2012** [comment]
No problem
>Does the app freezes on real PSP while getting those errors? or you can still see something changed on the screen?

**Comment by Florin9doi** [comment]
Currently GoExplore not only that fails to start, but crashes the emulator completely. The crash is observed at this line : https://github.com/hrydgard/ppsspp/blob/cd8b79ff59daaef85ceb695196ab98afe05a58cc/Core/FileSystems/ISOFileSystem.cpp#L654

![image](https://github.com/hrydgard/ppsspp/assets/2995486/8837bda3-30c4-4415-9ee5-21e39655e331)

**Comment by anr2me** [comment]
Did you know what was the value returned from `entry->children.size()` ?

**Comment by hrydgard** [comment]
Fixed the crash. However, this thing is weird. Additionally to the weirdness mentioned above, it tries, and fails, to open the paths "/filelist.txt" and "/READHELPER.idx", which we interpret as references to the memory stick, but presumably it means the UMD. I think it's likely we're just handling paths starting with "/" wrong.

**Comment by Florin9doi** [comment]
On PSP, `READHELPER.DAT` and `READHELPER.IDX` are created in the memory card's root during every start.
![image](https://github.com/hrydgard/ppsspp/assets/2995486/0aec37c1-7fad-46a0-90e6-5a0b45cab9f9)

**Comment by anr2me** [comment]
> On PSP, `READHELPER.DAT` and `READHELPER.IDX` are created in the memory card's root during every start. ![image](https://private-user-images.githubusercontent.com/2995486/293672740-01dc4ef1-323c-4485-9892-5833abc58518.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxOTQwNzAsIm5iZiI6MTcwNDE5Mzc3MCwicGF0aCI6Ii8yOTk1NDg2LzI5MzY3Mjc0MC0wMWRjNGVmMS0zMjNjLTQ0ODUtOTg5Mi01ODMzYWJjNTg1MTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDJUMTEwOTMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODUxZDhlZjZlNGJjNzQ0ODkzMDU1MWI3MzBjMGM3MTFjZGNiZGMwNjRjNzg0MDFiNGIxODYwMjJiNGYyMWU5ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZopCBtzCdcAeQyXvgyB1pWopY6mbC4n827H-SMTfX30)
> 
> They are created on PPSSPP also, but they are empty: ![image](https://private-user-images.githubusercontent.com/2995486/293673019-bf125e79-10ba-4867-83b0-4fef9628c465.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxOTQwNzAsIm5iZiI6MTcwNDE5Mzc3MCwicGF0aCI6Ii8yOTk1NDg2LzI5MzY3MzAxOS1iZjEyNWU3OS0xMGJhLTQ4NjctODNiMC00ZmVmOTYyOGM0NjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDJUMTEwOTMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGEwNGYwNjFhYjQ5YTA4ZWIxMmQ0YmMzMzZlNmMyNTlkMjFjZWMxZDhiMjYxNDgzMzFlZTA3ZmYyMmJhZjhkOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Zy2pVh0LBP1pK9VVlN9ytvqmX0UT84wwJ2-NR06rcJI)

According to [this](https://www.serialstation.com/discs/0a3144a2-2eec-43f2-92f5-eff34b3b36d7), those files also exist in the disc.

**Comment by Florin9doi** [comment]
`sceIoDread` doesn't work for `disc0:/` paths ? 
jpcsp returns `PSP_GAME` and then all its subdirs.

<table>
<tr><th>jpcsp</th><th>ppsspp</th></tr>
<tr>
<td> 

```text
DEBUG hle.IoFileMgrForUser - user_main - sceIoChdir path=0x08C60CD4('disc0:/')
 INFO hle.IoFileMgrForUser - user_main - pspiofilemgr - filepath disc0
DEBUG hle.IoFileMgrForUser - user_main - sceIoChdir returning 0x0
DEBUG hle.IoFileMgrForUser - user_main - sceIoDopen dirname=0x08C60CDC('/')
DEBUG hle.IoFileMgrForUser - user_main - sceIoDopen - isofilename = 
DEBUG hle.IoFileMgrForUser - user_main - sceIoDopen returning 0x3
DEBUG hle.IoFileMgrForUser - user_main - sceIoDread id=0x3, direntAddr=0x09FFF290
DEBUG hle.IoFileMgrForUser - user_main - sceIoDread id=0x3 #1 dir='disc0', dir='PSP_GAME'
DEBUG hle.IoFileMgrForUser - user_main - sceIoDread returning 0x1
DEBUG hle.IoFileMgrForUser - user_main - sceIoDopen dirname=0x09FFF190('/PSP_GAME/')
DEBUG hle.IoFileMgrForUser - user_main - sceIoDopen - isofilename = PSP_GAME
```

</td>
<td>

```text
12:19:440 user_main    D[SCEIO]: HLE\sceIo.cpp:2124 sceIoChdir(disc0:/)
12:19:471 user_main    D[SCEIO]: HLE\sceIo.cpp:2409 sceIoDopen("/")
12:19:471 user_main    D[SCEIO]: HLE\sceIo.cpp:2471 sceIoDopen ret = 283
12:19:471 user_main    D[SCEIO]: HLE\sceIo.cpp:2497 sceIoDread( 283 09fff490 ) - end
12:19:472 user_main    D[SCEIO]: HLE\sceIo.cpp:2552 sceIoDclose(283)
12:19:472 user_main    D[SCEIO]: HLE\sceIo.cpp:2409 sceIoDopen("/")
12:19:472 user_main    D[SCEIO]: HLE\sceIo.cpp:2471 sceIoDopen ret = 284
12:19:472 user_main    D[SCEIO]: HLE\sceIo.cpp:2497 sceIoDread( 284 09fff490 ) - end
12:19:473 user_main    D[SCEIO]: HLE\sceIo.cpp:2552 sceIoDclose(284)
```

</td>
</table>

**Comment by Florin9doi** [comment]
![image](https://github.com/hrydgard/ppsspp/assets/2995486/fa1563f5-b394-4034-b785-29fe9c26d6ec)

**Comment by Florin9doi** [comment]
```diff
diff --git a/Core/HLE/sceIo.cpp b/Core/HLE/sceIo.cpp
index 8102c84944..fb100fb185 100644
--- a/Core/HLE/sceIo.cpp
+++ b/Core/HLE/sceIo.cpp
@@ -2410,7 +2410,13 @@ static u32 sceIoDopen(const char *path) {
        double startTime = time_now_d();

        bool listingExists = false;
-       auto listing = pspFileSystem.GetDirListing(path, &listingExists);
+       std::vector<PSPFileInfo> listing;
+       if (strcmp(path, "/") == 0) {
+               listing = pspFileSystem.GetDirListing("disc0:/", &listingExists);
+       }
+       else {
+               listing = pspFileSystem.GetDirListing(path, &listingExists);
+       }

        if (!listingExists) {
                return SCE_KERNEL_ERROR_ERRNO_FILE_NOT_FOUND;
```

**Comment by Florin9doi** [comment]
v2
```diff
diff --git a/Core/FileSystems/MetaFileSystem.cpp b/Core/FileSystems/MetaFileSystem.cpp
index 5dece8e210..2f36663e2f 100644
--- a/Core/FileSystems/MetaFileSystem.cpp
+++ b/Core/FileSystems/MetaFileSystem.cpp
@@ -372,7 +372,13 @@ std::vector<PSPFileInfo> MetaFileSystem::GetDirListing(const std::string &path,
        std::lock_guard<std::recursive_mutex> guard(lock);
        std::string of;
        IFileSystem *system;
-       int error = MapFilePath(path, of, &system);
+
+       int error;
+       if (path == "/") {
+               error = MapFilePath(currentDir[__KernelGetCurThread()], of, &system);
+       } else {
+               error = MapFilePath(path, of, &system);
+       }
        if (error == 0) {
                return system->GetDirListing(of, exists);
        } else {
```

**Comment by hrydgard** [comment]
Huh, interesting. Looks like we're indeed missing some handling there. Although, '/' should probably not be relative to currentdir but to the root of the currentdir.

**Comment by Florin9doi** [comment]
This issue is observed only for ISOs and not for memstick.

1. `MetaFileSystem::MapFilePath(_inpath="/")` is mapped to prefix: "disc0:", path: "" https://github.com/hrydgard/ppsspp/blob/1f8191ec9bdd81190addf90e2fc7d7bfe2bf8032/Core/FileSystems/MetaFileSystem.cpp#L243
2. `ISOFileSystem::GetDirListing(path="")` is called https://github.com/hrydgard/ppsspp/blob/1f8191ec9bdd81190addf90e2fc7d7bfe2bf8032/Core/FileSystems/ISOFileSystem.cpp#L642
3. `ISOFileSystem::GetFromPath(path="")` returns `&entireISO` https://github.com/hrydgard/ppsspp/blob/1f8191ec9bdd81190addf90e2fc7d7bfe2bf8032/Core/FileSystems/ISOFileSystem.cpp#L264
4. `entireISO` doesn't have any children and `ISOFileSystem::GetDirListing(path="")` returns an empty vector https://github.com/hrydgard/ppsspp/blob/1f8191ec9bdd81190addf90e2fc7d7bfe2bf8032/Core/FileSystems/ISOFileSystem.cpp#L654


v3
```diff
diff --git a/Core/FileSystems/ISOFileSystem.cpp b/Core/FileSystems/ISOFileSystem.cpp
index 4fb682684e..f070ff362f 100644
--- a/Core/FileSystems/ISOFileSystem.cpp
+++ b/Core/FileSystems/ISOFileSystem.cpp
@@ -647,6 +647,9 @@ std::vector<PSPFileInfo> ISOFileSystem::GetDirListing(const std::string &path, b
                        *exists = false;
                return myVector;
        }
+       if (entry == &entireISO) {
+               entry = GetFromPath("/");
+       }

        const std::string dot(".");
        const std::string dotdot("..");
```

Can I submit a PR with this patch?
