### ISSUE TITLE
Digimon Adventure PSP NPJH-50686 Crashes PPSSPP When using Vulkan Backend

### ISSUE THREAD

**Issue by LPatamon** [hrydgard/ppsspp#15937]
### Game or games this happens in

Digimon Adventure PSP NPJH-50686

### What area of the game / PPSSPP

I downloaded build v1.13.1-633-g437d6d30a and when trying to enter into a battle the game crashes as shown on the following screenshot:

![crash](https://user-images.githubusercontent.com/6118529/187824754-7aae1b35-ab35-4136-92c8-3ede09cc6a3e.jpg)

### What should happen

Before it didn't crash. Vulkan always worked flawlessly. Also I noticed that on Direct 3D 11 Backend, while game works and I can enter into a battle, it doesn't makes the transition animation to enter into a battle. Instead screen goes black and then you appear in the battle which shouldn't be like that. 

When you touch an enemy yo get a transition effect to enter into battle.

I did some investigation and the issue must be on the changes made between build v1.13.1-624-g987bfc79e and v1.13.1-633-g437d6d30a since last build I tested in which game works fine (aside the other issues I reported long ago which are minor things) is build ppsspp-v1.13.1-623-gdaa62beb3. 

Also after build v1.13.1-623-gdaa62beb3 the following commits have no download links till build v1.13.1-632-g3168f8d11 which also has the crash issue on Vulkan when going into battle and the no transition effect when going into battle on Direct 3D 11 backend

All this on Windows 7 32 bits.

### Platform

Windows

### Mobile phone model or graphics card

GeForce 1030

### PPSSPP version affected

v1.13.1-633-g437d6d30a

### Last working version

v1.13.1-623-gdaa62beb3

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Sorry, small oversight in the Killzone work. Fixed.

**Comment by LPatamon** [comment]
Thanks. Now to wait for the build with the fix to appear available to download :)

And I figured it had to do with the Killzone work since it appeared mentioned on a few of the builds that had no download links on the buildbot

**Comment by Gamemulatorer** [comment]
***Vertex Cache*** is broken!


https://user-images.githubusercontent.com/37603562/187933097-dd603ed7-738d-4dff-9d6f-12d554099217.mp4



https://user-images.githubusercontent.com/37603562/187933187-9c4b6bef-cd39-4d41-8b49-846f248e7f11.mp4

**Comment by Gamemulatorer** [comment]
NVM it was ok now using build https://github.com/hrydgard/ppsspp/commit/b5e5f780f24bb434a6739850a8a5fc867ba6a0db
