### ISSUE TITLE
Up and Left key-binds not working [SOLVED]

### ISSUE THREAD

**Issue by OmnipotentMango** [hrydgard/ppsspp#15945]
### Game or games this happens in

Not game specific

### What area of the game / PPSSPP

When holding [kdb.Up] and [kdb.Left] simuteniously then the following key-binds become unresponsive. (Tested on multiple keyboards.)
![1180_43](https://user-images.githubusercontent.com/112726231/188225651-f8b17aae-dc26-4919-8cc8-38fc602d1172.png)
(Alt Graph is affected aswell)

Issue does not occure if input of any key comes from more then one keyboard.

### What should happen

Combiantion of every keybind should be input into the emulation.

### Platform

Windows

### Mobile phone model or graphics card

GTX 950

### PPSSPP version affected

v1.13.1

### Last working version

None

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
Noted on Discord that this was related to Dell keyboards.

-[Unknown]
