### ISSUE TITLE
The volume shortcuts besides Mute don't function

### ISSUE THREAD

**Issue by Daisouji** [hrydgard/ppsspp#15941]
### Game or games this happens in

None

### What area of the game / PPSSPP

No, any game.

### What should happen

Volume should change.

### Platform

Windows

### Mobile phone model or graphics card

GTX 1050

### PPSSPP version affected

1.13.1

### Last working version

1.13.1

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
They were only added for cheats.  There's a possibility people who use them for cheats may be unhappy if they actually affect volume.

-[Unknown]

**Comment by LunaMoo** [comment]
I guess we could disable mapped keys for non-essential psp keys when they're used by any cwcheat on the list.
