### ISSUE TITLE
 Resistance Retribution video flicker

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#15959]
### Game or games this happens in

UCES01184

### What area of the game / PPSSPP

Start video

https://user-images.githubusercontent.com/2177532/188297776-001949cd-8907-4cc6-a48d-cdc0ba47fff0.mp4

### What should happen

No flicking

### Logs

(Frame dump seem not work)
[UCES01184.zip](https://github.com/hrydgard/ppsspp/files/9484048/UCES01184.zip)
https://gist.github.com/sum2012/ad04fddce03cd73ed30280e37e935a01

seem this pr has problem
https://github.com/hrydgard/ppsspp/pull/15892

### Platform

Windows

### Mobile phone model or graphics card

Nvidia GetForce 710

### PPSSPP version affected

ppsspp-v1.13.1-475-g853a2df06

### Last working version

ppsspp-v1.13.1-471-g67c911d13

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

edit : reupload video

**Comment by sum2012** [comment]
Upload the video in youtube
https://youtu.be/0pDyz2o63Xc

**Comment by hrydgard** [comment]
Thanks, I'll look into it. Looks like several games started to have issues back there.
