### ISSUE TITLE
❗❗INVISIBLE SCREEN SAVE/LOAD and INVISIBLE SCREEN ADHOC START NETWORK❗❗

### ISSUE THREAD

**Issue by DavidSilvadeSa** [hrydgard/ppsspp#15954]
### Game or games this happens in

all

### What area of the game

save/load
network mode adhoc pro

https://user-images.githubusercontent.com/82737672/188289150-294412e6-a786-4260-b723-f40b196926c5.mp4

### What happens

regardless of the game, all save and load screens and the screen that shows before the online mode have rendering problems

https://user-images.githubusercontent.com/82737672/188289303-f7929df3-3e22-481d-93ea-7f003a9d8adf.mp4

### What should happen

in past versions this problem did not happen

### Platform

Android

### Mobile phone model or graphics card

POCO X3 PRO 8GBRAM GPU ADRENO

### PPSSPP version affected

v1.13.1-708-g14465cee1

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Yeah, something has broken, noticed it in a save dialog today.

Will track it down tomorrow.

**Comment by hrydgard** [comment]
Actually went ahead and did a quick bisection. The culprit is 867eb995055b532c05185c701c60be3980f883ae , part of #15950 .

Will see if I can do a quick fix.
