### ISSUE TITLE
Cannot see chinese font of hint

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#15955]
### Game or games this happens in

ALL GAME

### What area of the game / PPSSPP

Soft GPU ,interpreter 

### What should happen

Show correct font
Chinese font
![1](https://user-images.githubusercontent.com/2177532/188290800-3106b96d-881d-4e87-b075-25118b0aa35c.jpg)
English font
![2](https://user-images.githubusercontent.com/2177532/188290803-3260c7e1-ad8a-438b-8248-7ce04ded931a.jpg)

### Logs

None

### Platform

Windows

### Mobile phone model or graphics card

Nvidia Geforce 710

### PPSSPP version affected

v1.13.1-710-g65c016d15

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
This is probably from the ASCII flag in 58de891f57299a2fd919e20f7e5499c7f32fba92.

-[Unknown]

**Comment by sum2012** [comment]
Yes,remove the flag fix the issue

**Comment by unknownbrackets** [comment]
Alright, simple solution added in #15958 - didn't carefully test, but that ought to use the flag at the right times.

-[Unknown]

**Comment by sum2012** [comment]
Confirm fixed in v1.13.1-722-g49d5b6447
