### ISSUE TITLE
Cheat not working on version 1.13.1

### ISSUE THREAD

**Issue by revan9112** [hrydgard/ppsspp#15961]
### Game or games this happens in

ULES00789 Dragon Ball Z - Shin Budokai - Another Road (Europe)

### What area of the game / PPSSPP

When I try to use cheat´s on this game in the latest version doesn't work. I update from version 1.6, long time since then, but there in Android, windows and Linux work great. I try this on Android and WIndows with version 1.13.1, the only game I have is Dragon Ball Z - Shin Budokai - Another Road. I will leave the cheat codes bellow.

_C1 Infinite Health Player 1
_L 0x60299FE0 0x453B8000
_L 0x00020001 0x0000041C
_L 0x60299FE0 0x453B8000
_L 0x00020001 0x00000424
_C1 Quicker Character Player 1
_L 0x602C23C0 0x3FC00000
_L 0x00020001 0x00000810
_C1 Ki Player 1
_L 0x602C23C0 0x460CA000
_L 0x00020001 0x000004EC
_L 0x602C23C0 0x460CA000
_L 0x00020001 0x000004F0

### What should happen

The cheat's should give the character the hability to be faster, have more energy and infinite health

### Platform

Android

### Mobile phone model or graphics card

Realme X2 Pro

### PPSSPP version affected

v1.13.1

### Last working version

1.6

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [x] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by LunaMoo** [comment]
The game you're mentioning is multilanguage, it's very possible you used different language than the cheat author - that's enough for such basic cheats to not work.

 As far as I quickly tested them, they do work fine with english language inside arcade mode in latest PPSSPP versions.

 Those are really simple cheats through, they do use pointers, but pointer locations can also vary between different game modes and as mentioned languages so such cheats are not guarantee to work everywhere, the game allocation can also change by progress etc.. The only way to improve such cheats for them to work everywhere is to write them differently by hooking custom scripts to actual game functions that are used in all of those game modes, that's not a job for emulator, but to someone who cares about creating cheats for it.

 As such closing it as a non issue.
