### ISSUE TITLE
libretro jni compile failed

### ISSUE THREAD

**Issue by hsoftxl** [hrydgard/ppsspp#15964]
### Platform

libretro / Retroarch

### Compiler and build tool versions

cmake version 3.16.3

### Operating system version

windows11 sub system ubuntu 20.04.4

### Build commands used

ndk-21e/ndk-build

### What happens

[arm64-v8a] Compile        : retro <= inffast.c
[arm64-v8a] Compile        : retro <= inflate.c
/home/xielei/ppsspp/libretro/jni/../../ext/zlib/inflate.c:1507:61: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    if (strm == Z_NULL || strm->state == Z_NULL) return -1L << 16;
                                                        ~~~ ^
1 warning generated.
[arm64-v8a] Compile        : retro <= inftrees.c
[arm64-v8a] Compile        : retro <= trees.c
[arm64-v8a] Compile        : retro <= uncompr.c
[arm64-v8a] Compile        : retro <= zutil.c
[arm64-v8a] Compile        : retro <= fast_matrix_neon.S
[arm64-v8a] Compile        : retro <= filter_neon.S
make: *** No rule to make target '/home/xielei/ppsspp/libretro/jni/../../Common/math/fast/fast_matrix_neon.S', needed by '/home/xielei/ppsspp/libretro/obj/local/arm64-v8a/objs/retro/__/__/Common/math/fast/fast_matrix_neon.o'.  Stop.

### PPSSPP version affected

latest

### Last working version

_No response_

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] Make sure to run `git submodule update --init --recursive` before building.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try deleting the build directory and running the build again.
- [ ] Check GitHub Actions, which builds every merge and PR.
- [ ] Include logs and help us reproduce.

**Comment by unknownbrackets** [comment]
Is this using build files outside this project?

It seems you have a typo: Common/math should be Common/Math.  I don't see any cases of Common/math in this repo, so it appears to be in some other build files.

-[Unknown]

**Comment by hsoftxl** [comment]
@hrydgard 
libretro/Makefile.common  line 662 is wrong , i change to Math , is ok. 
thanks

**Comment by hrydgard** [comment]
cool, I'll get that fixed.

**Comment by unknownbrackets** [comment]
Ah darn it, I didn't realize there'd be a variable for Common, sorry.

-[Unknown]
