### ISSUE TITLE
[Windows] Black Screen on open

### ISSUE THREAD

**Issue by rnel76** [hrydgard/ppsspp#16017]
### Game or games this happens in

Before any game can be played

### What area of the game

games cannot be played

### What happens

im on windows 10 64 bit, and when i open ppsspp i get a black screen, using the games setting interface to change the back end does nothing. there is no ini to edit, as i deleted it when i first got this problem, assuming i needed a fresh install. however installs and portable versions did nothing. i have tried 1.13.2 installer and zip, 1.9.3,1.7.4,1.0. the only thing that changed in theses is that 1.0 went to not responding. according to the game settings interface, it is set to opengl and i cannot change it. i have an amd rx580 card, cpu ryzen 3 3200, 16gb ram. it does the same thing with the git version i tried, https://github.com/hrydgard/ppsspp/commit/125b76e9d56d296daba9bc7ba804d4e3e2ba1c38
![ppsspp](https://user-images.githubusercontent.com/39530327/189735684-7f228c51-3327-49e6-bbb1-169020a5cafa.png)

### What should happen

ppsspp should run...this has always been one of the best out of the box emulators out there

### Platform

Windows

### Mobile phone model or graphics card

AMD RX580

### PPSSPP version affected

1.13.2 and below

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment]
Have you tried updating your AMD graphics driver to the latest version? i heard it have better opengl support on recent version

**Comment by rnel76** [comment]
my drivers are up to date already, do you happen to know why i cant switch to another backend?

**Comment by unknownbrackets** [comment]
I would:
1. Restart your computer.  Try running PPSSPP before running any other programs and see if the same thing happens.
2. Unplug all optional devices connected to your computer - for example, any USB devices or removable storage, game controllers, headsets, etc.  See if it still happens in this case.
3. Run a driver utility to remove graphics drivers from old graphics cards, if you've ever installed a new card.  Some people have run into driver issues when old drivers for an old card are still technically installed in Windows (usually this happens AMD -> NVIDIA, though.)
4. Create a new folder on your desktop and extract the latest git build into it.  Try starting the PPSSPP from here.  This will use its own ini and files, in case there are permission issues.  Even if you get the problem, if you don't even get an ini file created there's a problem.
5. Try running another emulator such as DuckStation, Dolphin, or PCSX2 and see if it works or has similar problems.

-[Unknown]

**Comment by rnel76** [comment]
THANK YOU!!!!! unplugging my external drive seems to have fixed it, not sure why it interfered to begin with tho?

**Comment by unknownbrackets** [comment]
I'm not sure - sometimes USB devices have issues and can cause problems like this.  It might be fine to plug it back in, but if it keeps happening when it's plugged in, you should have the drive checked or stop using it.

-[Unknown]

**Comment by rnel76** [comment]
I have ran it with it plugged back in, so far so good... But it'll be my go
to fix if it happens agsin
