### ISSUE TITLE
GTA: VCS does not work on Xiaomi Redmi 9A (dandelion).

### ISSUE THREAD

**Issue by Android-squeak** [hrydgard/ppsspp#16010]
### Game or games this happens in

ULUS-10160 - Grand Theft Auto: Vice City Stories

### What area of the game / PPSSPP

After the introductory cinematic (credits) the game crashes and the "Resume" and "Reset" buttons appear.  Pressing the "Resume" button does nothing.  Here are two screenshots (in the PPSSPP settings I set it to not ignore bad memory accesses):
![Screenshot_2022-07-26-19-46-56-288_org ppsspp ppsspp](https://user-images.githubusercontent.com/101500792/189577106-8c1ae9eb-6963-460a-9622-291ff3622914.jpg)
![Screenshot_2022-07-26-19-46-43-984_org ppsspp ppsspp](https://user-images.githubusercontent.com/101500792/189577115-5139a446-698f-43c9-8e15-9bed840b2699.jpg)

### What should happen

It shouldn't crash.

### Platform

Android

### Mobile phone model or graphics card

Xiaomi Redmi 9A (dandelion)

### PPSSPP version affected

v1.12.3

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
This usually means a bad disc file if the game works for other people and you're on default settings.  You can check the CRC in the menu and then google that CRC to see if it's a normal good CRC for the disc.

-[Unknown]

**Comment by Panderner** [comment]
@Android-squeak Please try the latest build.

**Comment by sum2012** [comment]
@unknownbrackets 
static void DrawCrashDump(UIContext *ctx) {
	uint32_t crcvalue = Reporting::RetrieveCRC(loadedFile->GetPath);
VS2019 complain loadedFile "C++ disallows metrics with incomplete category types"

**Comment by Android-squeak** [comment]
> This usually means a bad disc file if the game works for other people and you're on default settings. You can check the CRC in the menu and then google that CRC to see if it's a normal good CRC for the disc.
> 
> -[Unknown]

I checked the ISO file with "ZArchiver", it is sure that the file has no error.  Thanks.

**Comment by Android-squeak** [comment]
> @Android-squeak Please try the latest build.

On another lower capacity device, on an older PPSSPP build, the game work perfectly.  Thanks.

**Comment by Android-squeak** [comment]
> 

I need help for Android. Thanks.

**Comment by Android-squeak** [comment]
> @unknownbrackets static void DrawCrashDump(UIContext *ctx) { uint32_t crcvalue = Reporting::RetrieveCRC(loadedFile->GetPath); VS2019 complain loadedFile "C++ disallows metrics with incomplete category types" edit:I know now, seem need make g_config.loadedgamepath

I need help for Android. Thanks.

**Comment by Android-squeak** [comment]
Xiaomi Redmi 9A have a PowerVR graphics card.

**Comment by unknownbrackets** [comment]
What's the other device?  System information would help.

It seems like your device is a 64-bit processor but it's running PPSSPP in 32-bit mode, maybe due to an older operating system.  This is not as well tested, because most people using 64-bit processors are using 64-bit mode.  Maybe there's some CPU cache bug (like we've seen before) but only when running at 32-bit.

Does this happen if you change the CPU to "IR Interpreter" instead of "Jit" in the Developer settings?  It will be a bit slower, though.

-[Unknown]

**Comment by Android-squeak** [comment]
I played GTA: VCS in PPSSPP on Windows, then I play in PPSSPP in Android with the same ISO file and the problem was solved. Thank you all.
