### ISSUE TITLE
Texture replacement 

### ISSUE THREAD

**Issue by Nugss** [hrydgard/ppsspp#16028]
### Game or games this happens in

ULUS10213 - The warriors or possibly the other games too

### What area of the game / PPSSPP

So I try to replace the textures of clouds on The warriors using the PS2 textures that I dump using AETHERSX2 emu of the same game, when I launch the PPSSPP, the texture doesn't load as is and it shows like this

![Screenshot_2022-09-16-02-11-44-26](https://user-images.githubusercontent.com/97185681/190479760-07f6f387-2ff7-4025-84a6-73f3b9e28634.png)

And when I play for long enough it will load properly

![Screenshot_2022-09-16-02-10-00-71](https://user-images.githubusercontent.com/97185681/190480744-2f07317f-75aa-4410-bc50-aacf9024ee93.png)
From this second pic, it's just a savestate that I save before. When the moment that the texture loads property I just savestate it, and when I loadstate it, it shows properly even without playing for long enough.

### What should happen

I don't think what the problem is but it's either the emulator or the texture i use.

Probably its the texture I replace, because I using ps2 textures on peds and it works fine.

Here's the texture:
![ulap1](https://user-images.githubusercontent.com/97185681/190481501-a64af914-7bf4-4a48-90cb-93a8413da1be.png)
![coneyclouds](https://user-images.githubusercontent.com/97185681/190481619-0117bc93-c4eb-43bc-9208-29c52009924e.png)

What you think guys? If the texture is the problem, can you give me some advice?

### Platform

Android

### Mobile phone model or graphics card

Oppo a3s

### PPSSPP version affected

Latest

### Last working version

None

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by LunaMoo** [comment]
If you need to "play long enough" for the replaced texture to appear it can mean two things:
 - you have a slow device and the texture is loaded with a delay(but that would only be a second or few at max),
 - the way you're identifying the texture doesn't work, ie. if you identify it by address_clut_hash_texture_hash it's possible address or clut hash changes even if texture hash is the same and often texture hash as well might change when the image is smaller than PSP texture size cause PSP games like to re-use that otherwise wasted memory for random data in which case you can try reducing hash in the textures.ini.

**Comment by Nugss** [comment]
Thanks @LunaMoo. If my device is the problem maybe i should reduce the quality or resolution of the texture

**Comment by IrfanH495** [comment]
I tried it too the result is transparent
https://youtu.be/AKw73qSU3Y0

**Comment by LunaMoo** [comment]
@IrfanH495 Lol. You can't just expect to replace opaque texture with a transparent one without making the object transparent.

**Comment by IrfanH495** [comment]
sorry if i ask too many questions.
about this part I don't understand
# Ignore the intro video textures.
099bf1c000000909 =
0993698000000909 =
09a47a0000000909 =
09ad024000000909 =
![Screenshot_20221002-010305_Chrome](https://user-images.githubusercontent.com/78854859/193422762-6f823a14-b504-4fe6-a5c7-266677ee001b.jpg)
is it for video editing.?
How to save it.?
Can someone give me an example.?

**Comment by unknownbrackets** [comment]
If you explicitly set a hash to an empty string like that, it won't save it or try to replace it.  It's just a way of skipping a texture.

-[Unknown]

**Comment by IrfanH495** [comment]
@unknownbrackets 
thanks for explaining.
I think it's to replace the edited mp4/pmf video, it was not.
very cool if can change the video like changing the texture, can replace it with HD quality or add subtitles.

**Comment by Nugss** [comment]
@IrfanH495 
Or you can modify the game instead, by replacing the pmsf using ps2 version of the game.

**Comment by Nugss** [comment]
Do you guys have plugin or cheat that fix the cutscene of this game?

**Comment by LunaMoo** [comment]
I don't, however my custom builds do include a compat hack which restores old functionality for videos to make them run smooth in this game.

**Comment by Nugss** [comment]
-Off topic-
Is it possible for this game to have "cheat device" similar to GTA VCS and LCS?

**Comment by Gamemulatorer** [comment]
There's many improvements in texture replacement https://github.com/hrydgard/ppsspp/issues?q=label%3A%22Texture+replacement%22+is%3Aclosed
How about this now?

**Comment by IrfanH495** [comment]
in the latest version
I can't save the texture if I delete the folder/file.png which is written in texture.ini

**Comment by hrydgard** [comment]
Oh, that might be an undesirable change in behavior, yeah. I'll get that fixed soon.

**Comment by hrydgard** [comment]
I'm going to close this issue because a number of problems have been fixed. #17182 is the new issue about saving.

**Comment by rorowong888** [comment]
Hey, bro
Since , most of the dumped texture from ps2 even both pcsx2 , Aethersx2 is transparents alpha level.
So that you should recover to normal via some retouching software like ps gimp if thta is use for others emulator like ppsspp
(But that would be find if use for ps2 emulator)
See this tutorial...on 03:00
https://youtu.be/uCnrzV8ZL1w
