### ISSUE TITLE
Everybody's tennis soft gpu problem

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#16040]
### Game or games this happens in

UCAS40307 - Everybody's tennis

### What area of the game

After menu

### What happens

Softgpu 
![2](https://user-images.githubusercontent.com/2177532/190880267-33b22d17-46fc-4116-b001-c09a2983fe33.png)

### What should happen

OpenGL
![1](https://user-images.githubusercontent.com/2177532/190880160-fd15ecd2-fe08-4613-ad33-4119bf3662a4.png)

### GE frame capture

[UCAS40307.zip](https://github.com/hrydgard/ppsspp/files/9592798/UCAS40307.zip)
v1.13.2-987-g02793375a Log: https://gist.github.com/sum2012/07acd25dde81478efa0717b91051b49b

### Platform

Windows

### Mobile phone model or graphics card

Nvidia Geforce 710

### PPSSPP version affected

v1.13.2-987-g02793375a

### Last working version

None

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [ ] Include logs or screenshots of issue.

**Comment by sum2012** [comment]
Test v1.13.2-1013-gc80cc1e87 fixed

**Comment by unknownbrackets** [comment]
Most likely this was some rectangle drawn underneath with 9b01fce.

-[Unknown]

**Comment by sum2012** [comment]
Yes fixed in v1.13.2-1008-gcd2c97783 #16039
