### ISSUE TITLE
Am I even supposed to be able to download ppsspp in an ipad pro?

### ISSUE THREAD

**Issue by Joakwin** [hrydgard/ppsspp#16057]
### What happens?
When I download it, the files are just useless. No apps, nothing. Its just a file in my folders that I can’t do anything with.

### What *should* happen?
I’m kind of sure i should be able to download the ppsspp app and then I’d go forward with the installation of the games i want.

### What are you using?
iPad Pro 2nd gen 

#### What PPSSPP version 
Just the ios version that is on the site right now as you’re reading.

**Comment by ANR2ME** [comment]
As mentioned in the unofficial iOS build download website https://p.xx.wtf/
> IPAs need to be signed (Developer cert or Cydia Impactor) on computers before install. DEBs require jailbroken devices. IPA is preferred. You can use Cydia Impactor to sign an ipa archive.
So try to find more info about Cydia Impactor, and AltStore or TrollStore

**Comment by unknownbrackets** [comment]
Unfortunately, PPSSPP doesn't run well on iOS devices.  This is probably more an issue for [the forum](https://forums.ppsspp.org/) or discord, but generally Apple doesn't allow PPSSPP to officially run on iOS devices so it's not as well supported.

I think some have had luck with AltStore.  Personally, I just switched to Android.

-[Unknown]
