### ISSUE TITLE
(Regression) (OpenGL) Burnout Legends too much bright with shader compilation error.

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#16119]
### Game or games this happens in

ULUS-10025

### What area of the game

At the start of the mission.

### What happens

Using OpenGL backend
![Screenshot_2022-09-27-19-58-41-79](https://user-images.githubusercontent.com/37603562/192519368-d0dbd19d-7246-4b21-afd6-24c879ced3bc.png)
![Screenshot_2022-09-27-19-58-46-73](https://user-images.githubusercontent.com/37603562/192519379-0c54d4be-78a0-436c-b6d3-00c58808e6b9.png)

### What should happen

Using vulkan backend.
![Screenshot_2022-09-27-20-00-00-60](https://user-images.githubusercontent.com/37603562/192519552-34980c83-0312-4744-90fa-7ca1ad520385.png)

### GE frame capture

[ULUS10025.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/9655191/ULUS10025.ppdmp.zip)

### Platform

Android

### Mobile phone model or graphics card

OPPO s3s Snapdragon 450 Adreno 506

### PPSSPP version affected

v1.13.2-1258

### Last working version

v1.13.2

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Oh, oops. easy one, I'll take care of it later today.
