### ISSUE TITLE
Tenchu Kurenai (Fatal Shadows) opening FPS drop

### ISSUE THREAD

**Issue by IrfanH495** [hrydgard/ppsspp#16113]
### Game or games this happens in

ULJM-05598

### What area of the game

Opening fps drop bolt vulkan & opengl
vulkan
https://user-images.githubusercontent.com/78854859/192249829-8a2167f0-cc40-4759-a2ce-bc78c3a92dad.mp4

open gl
https://user-images.githubusercontent.com/78854859/192250030-5b1a5410-d10b-41e8-b2cc-d261c6ea19a1.mp4

for the Playstore version I got 30fps

### Speed seen in PPSSPP

9/9

### Platform

Android

### Mobile phone model or graphics card

Samsung m20

### PPSSPP version affected

ppsspp-v1.13.2-1228-g94e439280-android

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the slowdown.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Oh, that's not good. 

Could you try a bunch of versions between 1.13.1 and current, and see if you can narrow down a range for when it broke?

**Comment by IrfanH495** [comment]
ppsspp-v1.13.2-1056-g913ba9de8-android
ppsspp-v1.13.2-947-g7b47ba802-android
I've tried both versions above still experiencing a decrease in fps.
i will try again.

**Comment by hrydgard** [comment]
yeah, you can start in the middle (-500), then if it's still slow, go down to 250, or up to 750 if it's not slow, etc..

**Comment by IrfanH495** [comment]
ppsspp-v1.13.1-693-gb92ea74fb-android- 30fps

**Comment by IrfanH495** [comment]
ppsspp-v1.13.1-708-g14465cee1-android-drop fps
ppsspp-v1.13.1-704-g6783ecd72-android-drop fps

**Comment by IrfanH495** [comment]
ppsspp-v1.13.1-702-g91ff603fd-android- drop fps

**Comment by hrydgard** [comment]
Cool, thanks for testing!

That means it slowed down (or whatever is happening) with this PR:

- #15950

**Comment by hrydgard** [comment]
Since this is during video, my guess is something went wrong in this commit: https://github.com/hrydgard/ppsspp/pull/15950/commits/8b41178cb8b2f29d3c784f7dc1a7dcfcafae9d6e 

Though that's just speculation so far.

**Comment by IrfanH495** [comment]
ppsspp-v1.13.2-1236-g2097a9c39-android 30fps
thanks

**Comment by hrydgard** [comment]
thanks for reporting!
