### ISSUE TITLE
Glitch during FMV in Way of The Samurai Portable cause by #15920

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#16124]
### Game or games this happens in

ULJS00155

### What area of the game

Glitchy FMV using ppsspp build https://github.com/hrydgard/ppsspp/commit/ebbd17540c54c2015f7cd9fae73d4125ad4007ff

https://user-images.githubusercontent.com/37603562/192705994-bad33e05-73d1-4817-afba-c8199aba65c5.mp4

### What happens

There's a glitch in intro movie of Way of The Samurai Portable but minimizing ppsspp can make the glitch gone.

### What should happen

No glitch during fmv.
ppsspp v1.13.2

https://user-images.githubusercontent.com/37603562/192706192-84682b17-f606-4fa1-94ac-530ffd110356.mp4

### GE frame capture

[ULJS00155.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/9662191/ULJS00155.ppdmp.zip)

### Platform

Android

### Mobile phone model or graphics card

OPPO s3s Snapdragon 450 Adreno 506

### PPSSPP version affected

https://github.com/hrydgard/ppsspp/commit/ebbd17540c54c2015f7cd9fae73d4125ad4007ff

### Last working version

v1.13.2

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by Panderner** [comment]
Unpatched Japanese version also affected.

**Comment by Gamemulatorer** [comment]
Ok finally track the culprit https://github.com/hrydgard/ppsspp/commit/59cb7a075fce5f44917908394e0ddf649cf5452c

**Comment by Gamemulatorer** [comment]
Confirm fix via https://github.com/hrydgard/ppsspp/pull/16139

**Comment by hrydgard** [comment]
Thanks for testing!
