### ISSUE TITLE
linux (Qt): unable to detect controller (dualshock 3)

### ISSUE THREAD

**Issue by gucio321** [hrydgard/ppsspp#16144]
### Game or games this happens in

<not related>

### What area of the game / PPSSPP

I'm unable to use my Dualshock 3 controller in simulator.
The Settings->Controls page doesn't seem to detect it at all.

I'm connecting my DS3 controller using USB cable.

### What should happen

controller should work OR at least be detected in order to be mapped in settings.

I suppose, this bug is related to PPSSPP's input management. I'm sure that my linux detects the controller (device is in /dev/input/js1). I can also us `qjoypad` to map the keys (note, that qjoypad is Qt app)

### Logs

nothing interessting in logs tbh.
It just says that there is no window opened for PPSSPP
```console
[ppsspp (0) ]$ PPSSPPQt 
ThreadManager::Init(compute threads: 10, all: 20)
QObject::connect: No such slot MainWindow::frameSkippinGroup_triggered(QAction *)
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
```

### Platform

Linux / BSD

### Mobile phone model or graphics card

Fedora release 36 (Thirty Six); Intel AlderLake-S GT1

### PPSSPP version affected

current master (10b226367341dcf259f4439721d89ae1a449a4ce)

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by Gamemulatorer** [comment]
Related https://github.com/hrydgard/ppsspp/issues/15112

**Comment by gucio321** [comment]
@Gamemulatorer thank you for really fast answer!

So I'm closing this for now and watching #15112 .
