### ISSUE TITLE
Bluetooth controller on Android 11

### ISSUE THREAD

**Issue by Mesho39** [hrydgard/ppsspp#16158]
i did check the wiki and internet for solution but nothing worked

### What happens?
the d pad and anlog sticks don't work with Bluetooth controller and when i searched why it turns out its a problem with android os and people recommend to turn of gesture but it didn't work i turned of everything nothing worked i have realme 8 phone 
ps : for some reason controller works with aethersx 2 wich is psp emulater 

### What *should* happen?
the controls should work normaly

### What are you using?
ppsspp latest version on Android 

#### What hardware / device and operating system?
realme 8 android 11

#### Checklist

 - [ X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [X ] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [ X] Try resetting settings or older versions and include if the issue is related.
 - [ ] Include logs or screenshots of issue.

**Comment by Mesho39** [comment]
> Similar #15763 ?

i dont have the setting he is talking about since my phone is deferent and i tried disableing everything also didn't work do you have an old ppsspp version that didn't have this problem

**Comment by Mesho39** [comment]
> Similar #15763 ?

i finally found the solution on another site you need to turn off any accessibility app like auto clicker and everything is good

**Comment by Gamemulatorer** [comment]
Issue resolve now?

**Comment by unknownbrackets** [comment]
This sounds like a well known Android 11 bug, I'm going to close it.  The accessibility thing is the most common workaround, and it's fixed in newer versions of Android.

-[Unknown]
