### ISSUE TITLE
Feature request: implement trilinear filtering

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#16151]
### What should happen

Trilinear filtering OFF
![Screenshot_2022-10-03-09-36-56-745_xyz aethersx2 android](https://user-images.githubusercontent.com/33152267/193526237-a34680e2-7260-4432-adda-4fb1b36a9c3b.jpg)
![Screenshot_2022-10-03-09-37-21-566_xyz aethersx2 android](https://user-images.githubusercontent.com/33152267/193526434-1a28ef60-591f-474d-9df5-c92a5d15d4e5.jpg)
Trilinear Filtering ON
It's about screen filtering not about ingame filtering. It have nothing to do with anisotrophic

### Who would this benefit

This thing can be good for slower mobiles or as some sort of antialiasing option. I took the screenshots from AetherSX2.
+ Remove jagged edges on lower resolutions
- can make the game look a bit too blurry on lower resolutions (like PSPx1) but ± this can look good by using sharpen shader or different filter (PSPx2 and PSPx3 will mostly benefit). On extremely high resolutions it's not pretty much noticable
+ No perfomance regression
Can look better than FXAA shader

### Games this would be useful in

Mostly 3D games

### Other emulators or software with a similar feature

Took from AetherSX2 PS2 emulator (it's actually trilineared nearest Neighbor filter)

### Checklist

- [ ] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [ ] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by Gamemulatorer** [comment]
I don't think that's a good features for ppsspp 🤔

**Comment by hrydgard** [comment]
Trilinear implies interpolation in three directions, not two, such as in mip levels on in 3d textures. You seem to advocate bilinear, which we already support. Not really sure what exactly is being asked here, and the screenshot is not from PPSSPP.

**Comment by marosis** [comment]
![Screenshot_2022-10-03-10-51-37-536_xyz aethersx2 android](https://user-images.githubusercontent.com/33152267/193537701-bd3f7149-dc07-4f4b-be85-bbfe391d3ebb.jpg)
Took screenshot of my settings in AetherSX2. I think it lookslike that you can use anisotrophic and trilinear filtering at the same time. You can use anisotrophic, linear or nearest neighbor for filtering textures but trilinear is used for pixels on the screen

**Comment by marosis** [comment]
You can actually trilinear lineared or nearest neighbored screen pixels

**Comment by hrydgard** [comment]
Trilinear screen pixels just don't make sense, it's bilinear. And we already support it.

**Comment by marosis** [comment]
Yeah i've noticed that. It looks like bilinear is automaticaly turned on when trilinear is aplicated. I'm closing this

**Comment by Gamemulatorer** [comment]
MSAA is better filter for lowend devices https://github.com/hrydgard/ppsspp/issues/6218
