### ISSUE TITLE
Feature Request [Add Achievements login from Retroachievements.org]

### ISSUE THREAD

**Issue by dochankpin** [hrydgard/ppsspp#16169]
### What should happen

Hello developer friend, greetings!
I am sending you this message,
to ask you if it is possible for you to add the option / function ,
of logging in with the website account: retroachievements.org
so that PSP games can unlock / unlock achievements?
Thank you very much in advance for all your dedication to the project.
Congratulations!
And thank you very much in advance for your attention and understanding.
See you soon friend.
Bye.

### Who would this benefit

I believe that this function would benefit all players in the community,
and also, in a way, would attract more people to get to know the project.
Since playing PSP games with achievements to be unlocked is an innovative and very attractive process.

### Platform (if relevant)

Android

### Games this would be useful in

All Games

### Other emulators or software with a similar feature

Some examples of emulators for Android with the achievements feature are:
Duckstation (PS1 Emulator),
we have also recently added the emulator:
AetherSX2 (PS2 Emulator),
among several other emulators that also already have this beautiful feature.

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by marosis** [comment]
Omg this is epic idea!

**Comment by ANR2ME** [comment]
Btw how does achievements worked on emulators? 
Does the emulator can detects a certain scene (ie. when a game cleared) by using a plugin or something?

**Comment by LunaMoo** [comment]
It's more likely to just read variables stored in user memory like our vibration/shader PPSSPP specific cwcheats. Meaning it can't track anything which isn't tracked by the game itself without modifying the game functions. It's a system that can be easily abused and with achievements, people will often just use cheats to unlock them.

**Comment by bardemz** [comment]
Would love to see this, as I use an Android device for my ppsspp playtime, a platform where the ppsspp retroarch core is  bugged at the moment (at least for me).

Duckstation and now Aethersx2 have implemented them in their standalones, fingers crossed that maybe there is a workaround regarding Luna's point above!

**Comment by RenanSD007** [comment]
It would be great to add support for achievements because playing through RetroArch is a bad experience on Android when you have a weak phone (and I believe that even more powerful cell phones may have problems with the PPSSPP core)

**Comment by hrydgard** [comment]
Wait, have people already made retroarchievements for PSP and enabled them in retroarch?

Retroachievements have to be manually constructed per game, as PSP games just don't have achievements by themselves. If that job is already done somewhere, certainly, could look at some and see how hard it would be to integrate with PPSSPP.

**Comment by Blackbird88** [comment]
> Wait, have people already made retroarchievements for PSP and enabled them in retroarch?

I see some on the website at least
https://retroachievements.org/game/3185

**Comment by hrydgard** [comment]
Oh, indeed!

Well, next step would be to figure out how to actually implement support for them in an emulator. I don't see anything about that in their developer guide: https://docs.retroachievements.org/Developer-docs/

**Comment by ANR2ME** [comment]
> Oh, indeed!
> 
> Well, next step would be to figure out how to actually implement support for them in an emulator. I don't see anything about that in their developer guide: https://docs.retroachievements.org/Developer-docs/

may be looking at Duckstation's code might helped https://github.com/stenzek/duckstation/blob/4c4e62cee668b62f354b08600c3dc418356d8d96/dep/rcheevos/README.md

**Comment by bardemz** [comment]
Reconfirming the above; RetroAchievements were implemented for PSP via the Retroarch core around this time last year; https://retroachievements.org/viewtopic.php?t=14016&o=0

There are currently 146 supported games and growing: https://retroachievements.org/gameList.php?c=41

**Comment by dochankpin** [comment]
I'm very happy to one day be able to play PSP Games with Achievements.

**Comment by leandrodeassis** [comment]
It would be wonderful to have this functionality implemented.

**Comment by dochankpin** [comment]
Yeah bro!

**Comment by Elbearno** [comment]
It would be nice to add this feature ! I cant play psp games with RA on my odin pro with ppsspp core on retroarch.

**Comment by priiduneemre** [comment]
+1, this currently the only feature lr-ppsspp has that standalone ppsspp doesn't (IMHO). Indeed, duckstation solved it pretty much perfectly for the PS1.

**Comment by ygordreyer** [comment]
It's actually funny that I came into this Issue with the same problem. PPSSPP Core of RA it's broken on Androids. So I can't play on my Odin.
Standalone runs 10/10, but without achievements it's sad.

**Comment by Captainquill** [comment]
Any update on this? Is this still being worked on?

**Comment by rvreq** [comment]
Come on guys, I wish I could just use the standalone PPSSPP and not mess with RetroArch just for one platform. :p

**Comment by kensher0** [comment]
plz make this happen.

**Comment by dochankpin** [comment]
Greetings dear friend developer hrydgard.
All good?
Do you intend to or are you already working on
to implement the retro achievements function to PPSSPP?
Thank you very much in advance for your attention and dedication to the great work you have been doing at PPSSPP.
I am eternally grateful.
See you buddy.

**Comment by clorophilla** [comment]
I hope this gets implemented someday, as RetroArch's core is still pretty bad (crashes a lot, missing effects etc on Android). The standalone version works like a charm on my phone, but it doesn't feature achievements.

**Comment by ThePixelJunkie** [comment]
Yeah I would much prefer using the standalone PPSSPP than RetroArch, for achievements. I already use DuckStation and PCSX2 for PS1 and PS2 achievements and it's wonderful. RetroArch is great, but the PPSSPP core has its issues. Also the standalone is much easier on the eyes and better UI imo

I would want this for the PC version tho, more-so than Android, personally. But either/both would be amazing.

**Comment by hrydgard** [comment]
Work on this has started: #17589 

However it'll be a while before it's usable, it needs plenty of UI work, mainly!

**Comment by ScottCarammell** [comment]
oh hell YES! God I love this community

**Comment by bardemz** [comment]
Thanks hrydgard!  Very excited for this!

**Comment by hrydgard** [comment]
This has now been merged! (#17589 )

Get a build from https://buildbot.orphis.net/ppsspp/ . Log in at Game Settings/System/Retroachievements, then it should just work on games that support it. And create new issue reports here if you have any problems.

**Comment by RenanSD007** [comment]
I've waited so long for this day, thank you so much for it @hrydgard  😁

**Comment by bardemz** [comment]
This is great!

I noticed there isn't a selection for hardcore mode (disable save states, cheats, rewind) - will that be implemented as well?  I presume since the selection isn't available, only softcore achievements are currently possible?

**Comment by FrenchPrick** [comment]
Has any of you been able to login for some odd reason I can't no matter
what I tried.

**Comment by Elbearno** [comment]
Tested on my Odin pro (android) , it works very well ! I unlock 3 achievements on 2 different game. Now, i just wait for the hardcore mode. Great job ! Thanks a lot !

**Comment by hrydgard** [comment]
@FrenchPrick Logging in should work. What happens when you try? (yes I need to add some proper error reporting...)

**Comment by FrenchPrick** [comment]
Nothing really it's appears to login but when I press back and re-enter the
menu it's look like the login didn't work.

**Comment by dochankpin** [comment]
@hrydgard Thank you so much man !!
Great Work !!
Congratulations !!

**Comment by Krisk1111** [comment]
> This has now been merged! (#17589 )
> 
> Get a build from https://buildbot.orphis.net/ppsspp/ . Log in at Game Settings/System/Retroachievements, then it should just work on games that support it. And create new issue reports here if you have any problems.

Anyway to make this work in gold?

**Comment by hrydgard** [comment]
> > This has now been merged! (#17589 )
> > Get a build from https://buildbot.orphis.net/ppsspp/ . Log in at Game Settings/System/Retroachievements, then it should just work on games that support it. And create new issue reports here if you have any problems.
> 
> Anyway to make this work in gold?

Yes, it will be in the next official release

**Comment by dochankpin** [comment]
@hrydgard Hello dear developer friend.
The next update of the Gold version of PPSSPP there on the Google Play Store, which will come with support for retroachievements.
Is this update close to being released?
Thank you so much in advance for all your excellent work with this project my friend.
Congratulations!
And see you later.

**Comment by dochankpin** [comment]
Cool.
Thank you very much!
