### ISSUE TITLE
(Vulkan) GoW Ghost of Sparta graphics regression (now; corrupted tex4xBRZ)

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#16170]
### Game or games this happens in

UCUS98737

### What area of the game

Nexus of Atlantis

### What happens

***Vulkan***
![Screenshot_2022-10-07-02-28-35-50](https://user-images.githubusercontent.com/37603562/194391308-f43c89c4-4c5e-4697-a46e-ad07cd33233b.png)

***Opengl***
![Screenshot_2022-10-07-02-28-49-96](https://user-images.githubusercontent.com/37603562/194391363-dfd69954-ba77-44c0-9057-dfb44f476cf1.png)

### What should happen

Both backend should render the game the same with no graphic error.

### GE frame capture

[UCUS98737.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/9727592/UCUS98737.ppdmp.zip)

image during recording of ge dump.
![Screenshot_2022-10-07-02-33-09-84](https://user-images.githubusercontent.com/37603562/194391941-7768a3c7-afee-48ea-9123-959c36985f43.png)

### Platform

Android

### Mobile phone model or graphics card

oppo a3s snapdragon 450 adreno 506

### PPSSPP version affected

v1.13.2-1395

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by Gamemulatorer** [comment]
Indiana Jones and the Staff of Kings
Vulkan lost bloom effects.
![Screenshot_2022-10-07-02-47-35-98](https://user-images.githubusercontent.com/37603562/194394281-61457e3c-7fde-4034-8552-92d419fc1227.png)

**Comment by hrydgard** [comment]
Thanks for reporting, can you go back and check which version these problems started in?

**Comment by Gamemulatorer** [comment]
Oh! Accidentaly fix in https://github.com/hrydgard/ppsspp/commit/131c1ca79e33a0ab169b0c20aa24a6b0c288fd1f?
![Screenshot_2022-10-07-07-51-15-40](https://user-images.githubusercontent.com/37603562/194438509-606589db-779b-4305-b9e1-68fb376966dd.png)

**Comment by Gamemulatorer** [comment]
Found a new graphics bug related to this game.
![Screenshot_2022-10-08-23-03-08-25](https://user-images.githubusercontent.com/37603562/194714143-46dc9596-95cc-400d-9129-ece299e99ff1.png)
[UCUS98737.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/9739563/UCUS98737.ppdmp.zip)

**Comment by unknownbrackets** [comment]
Hmm, it looks okay on desktop Vulkan with Tex4xBRZ:

![Image with smooth colors](https://user-images.githubusercontent.com/191233/194731221-d902bfad-bfeb-46b3-91b4-ce554e1310a6.png)

Your screenshot sorta looks like what might happen if it didn't actually upscale.  I wonder if you ran out of VRAM or something else caused it to decide not to upscale, but it didn't treat it uniformly as unscaled...

-[Unknown]

**Comment by Gamemulatorer** [comment]
Can easily reproduce this with hw transform off and change texture shader from 2xBRZ > MMPX > 4xBRZ multiple times.

**Comment by hrydgard** [comment]
Does it really only happen in this game? I'd expect a bug like that to be kinda universal..

**Comment by Gamemulatorer** [comment]
I will test other games and give feedback.

**Comment by Gamemulatorer** [comment]
Can also reproduce this in Tekken6.
![Screenshot_2022-10-10-01-22-05-06](https://user-images.githubusercontent.com/37603562/194770669-9543c736-f86e-4b34-bc1c-04c41344841c.png)

**Comment by hrydgard** [comment]
OK, then it doesn't really belong here in the GoW issue.

Could you create a new issue with some steps to reproduce in Tekken 6?
