### ISSUE TITLE
(OpenGL) (Direct3D9) Brave Story: New Traveler graphics regression black enemy texture.

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#16176]
### Game or games this happens in

ULUS10279

### What area of the game

During battle scene.

### What happens

Enemy is black in opengl backend.
***OPENGL***
![Screenshot_2022-10-08-00-26-33-62](https://user-images.githubusercontent.com/37603562/194602554-35d1781c-f3c2-45e0-bc81-5684187c2800.png)

***VULKAN***
![Screenshot_2022-10-08-00-26-17-24](https://user-images.githubusercontent.com/37603562/194602613-86f25e51-f337-4f8e-ab40-4e360d0691ac.png)

***Software***
![Screenshot_2022-10-08-00-26-58-12](https://user-images.githubusercontent.com/37603562/194602663-1fd9dace-4c37-4914-9b32-d650d9df3634.png)

### What should happen

Enemy should render correctly.

### GE frame capture

[BraveStory.zip](https://github.com/hrydgard/ppsspp/files/9735617/BraveStory.zip)

### Platform

Android

### Mobile phone model or graphics card

oppo a3s snapdragon 450 adreno 506

### PPSSPP version affected

v1.13.2-1406

### Last working version

v1.13.2

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by Gamemulatorer** [comment]
Issue can still reproduce.
![Screenshot_2022-10-09-16-46-44-60](https://user-images.githubusercontent.com/37603562/194747189-46dd01ee-7476-480e-829c-ef2dddfb478c.png)
[ULUS10279.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/9741118/ULUS10279.ppdmp.zip)

**Comment by hrydgard** [comment]
Most likely it was fixed on many devices, but still seems to have a problem on yours. So reopening.

**Comment by Gamemulatorer** [comment]
Fix via https://github.com/hrydgard/ppsspp/commit/49de375bff6784782d340082738c3c47c9ebcb24

**Comment by hrydgard** [comment]
That's interesting, thanks for checking.
