### ISSUE TITLE
MGS: Peace Walker won't read my controller's right analog stick inputs 

### ISSUE THREAD

**Issue by Sulfurico-One64** [hrydgard/ppsspp#16216]
### What should happen

First of all, I'm a complete layman when it comes to coding, and I just follow instructions online for what I want to play and emulate.

I finally got myself a new Dualshock 4 to play Peace Walker on my phone, as I've been playing it on the touchscreen controls after my older joystick died. I binded the controls nicely to resemble the MGS4 scheme. In Peace Walker's traditional control scheme, the X, O, square and triangle buttons controlled the camera on the PSP. 

I simply binded those buttons to my new wireless controller's 4 axis/directions of its right analog stick. X = Down. O = Right. △ = Up. □ = Left. Everything's well, except... PPSSPP can't interpret diagonal inputs for the life of it. 

When controlling the camera and aiming, with the DS4's right analog stick, the camera can only mechanically go left or right, up or down, which makes it a pain in the ass to play specially during bosses and a terrible wonky experience overall that could easily be fixed. I messed around the app's Controls settings endlessly, but to no avail. 

There's no option that enables us to combine two different PSP inputs, such as pressing O and X at the same time to make the camera turn diagonally to the lower right, for example. Gestures are useless. There's no accessibility options AFAIK. 

Funnily enough, you *can* set up a right analog stick that you can bind to Peace Walker's camera controls and it reads them diagonally... Except it's only the optional touchscreen right stick, which can command the camera perfectly in 360 degrees, while the right analog stick in my actual physical controller that I bought just for my enjoyment and ease of life, can't create those inputs in PPSSPP's settings. 

Below is a video where I demonstrate this. All of PSP's touchscreen buttons are visible, but I'm playing with a PS4 controller. Notice the X O △ □  buttons receiving input. That's actually me controlling the camera via my joystick's right analog stick, but sadly it only inputs one button at a time, even when I tilt the stick in a completely diagonal direction. 

https://streamable.com/vjpoad

When you see the digital right analog stick receiving input, that's actually me using the touchscreen right stick. Notice how it easily moves the camera diagonally without any trouble. Now, why can't I just bind my physical controller's right stick to this thing? The left analog stick has no problem being in complete sync with it's digital touchscreen counterpart, so it's ridiculous that we can't set this up. 

Take a look at the video above, and please help me if you can. What must I do to get Peace Walker's camera to move diagonally using my DS4's right stick? Not the digital touchscreen one, the real one. If there's a plugin to fix it out there somewhere, or a trick in button mapping needed for the diagonal camera inputs to work in my DS4, just let me know. I'm desperate, and no one else in any other forums paid any attention to my help request, understandably, it's a lot of text.

### Who would this benefit

Anyone who wants to play MGS: Peace Walker on Android with a physical wireless controller and map the controls so it's similar to MGS4, but can't stand that the native emulator can't allow for a camera with diagonal 8 direction inputs using the controller's joystick, and the only way to play with a diagonal camera is using the optional digital right stick on the touchscreen, which is completely against the point of having a wireless controller to play these games.

### Platform (if relevant)

Android

### Games this would be useful in

ULUS-10509 v1.01 - METAL GEAR SOLID PEACE WALKER 

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by LunaMoo** [comment]
It's possible android specific or even specific to your setup, can't reproduce such problem on windows.

 As a workaround that might even improve over what you desire you could try my right analog cheat for this game as it implements real right analog support(which is definitely smoother than 8 direction digital). You can find it in https://github.com/LunaMoo/PPSSPP_workarounds or in PPSSPP forums in this game's thread - it's a cwcheat which when used will modify the game code to read real right analog input(you will also have to map your right analog to RightAn. keys in PPSSPP control mapping), the cheat comes with it's own settings to control it's deadzone, speed and other things.

**Comment by Sulfurico-One64** [comment]
> It's possible android specific or even specific to your setup, can't reproduce such problem on windows.
> 
> As a workaround that might even improve over what you desire you could try my right analog cheat for this game as it implements real right analog support(which is definitely smoother than 8 direction digital). You can find it in https://github.com/LunaMoo/PPSSPP_workarounds or in PPSSPP forums in this game's thread - it's a cwcheat which when used will modify the game code to read real right analog input(you will also have to map your right analog to RightAn. keys in PPSSPP control mapping), the cheat comes with it's own settings to control it's deadzone, speed and other things.

**Comment by Sulfurico-One64** [comment]
> It's possible android specific or even specific to your setup, can't reproduce such problem on windows.
> 
> As a workaround that might even improve over what you desire you could try my right analog cheat for this game as it implements real right analog support(which is definitely smoother than 8 direction digital). You can find it in https://github.com/LunaMoo/PPSSPP_workarounds or in PPSSPP forums in this game's thread - it's a cwcheat which when used will modify the game code to read real right analog input(you will also have to map your right analog to RightAn. keys in PPSSPP control mapping), the cheat comes with it's own settings to control it's deadzone, speed and other things.

Thank you so much! I have never used cheats in PPSSPP but I will read up about it and try to implement your solution. Will report results as soon as I have the time to do it.

**Comment by Sulfurico-One64** [comment]
It worked! Thanks so much! I activated all the quality of life cheats for PW except for the one with the extra shirts, cause it unlocked some random itens in R&D. Now I'm having some issues with the game crashing at random times, but I'll make some other thread for that
