### ISSUE TITLE
GTA Chinatown Wars crashing when checking mail or stats in game

### ISSUE THREAD

**Issue by ANR2ME** [hrydgard/ppsspp#16215]
### Game or games this happens in

ULUS10490

### What area of the game / PPSSPP

Reported by Bizz91 at discord https://discord.com/channels/293316141479362560/480103153803460614/1030448275662327870

SaveData: 
[ULUS10490L0.zip](https://github.com/hrydgard/ppsspp/files/9786775/ULUS10490L0.zip)

### What should happen

Shouldn't crashed on both Vulkan and OpenGL, just like v1.13.2 release

### Platform

Android

### Mobile phone model or graphics card

Samsung Galaxy A32 4g

### PPSSPP version affected

v1.13.2-1460-g5b919dcf1

### Last working version

v1.13.2-1456-gbc9215ca9

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by bizz91** [comment]
I am here.

**Comment by hrydgard** [comment]
From that range, it's either #16194 , #16193 or #16192, I think...

**Comment by hrydgard** [comment]
Wonder if this is another downcounter related issue. Though in ARM64, Save/LoadStaticRegisters save/load a lot more than the downcounter, so if one of those calls were missing, things would likely go bad fast, unlike the ARM32 case (#16205)..

**Comment by bizz91** [comment]
It could be related to changes made for arm32 stuff. Maybe thats causing it to crash.

**Comment by bizz91** [comment]
Its even crashing on Windows 7 64 bit.
Intel gma 4500 gpu.
Last working build 1456.
Crash occuring from 1465.

**Comment by unknownbrackets** [comment]
Apparently this crashes in #16215 and then it's noted that #16221 just crashes for many stable versions, so I'm not sure if there's something else going on in this range.  It doesn't sound like it's related to the downcount.

-[Unknown]

**Comment by hrydgard** [comment]
OK. I'll do some bisection tomorrow.

**Comment by unknownbrackets** [comment]
Does this happen in Liberty City Stories or any other game?

-[Unknown]

**Comment by bizz91** [comment]
Haven't checked and not interested in gta lcs or vcs. Sorry, don't meant to be rude.

**Comment by hrydgard** [comment]
Should be fixed now with #16234 , thanks @unknownbrackets . Please test.

**Comment by bizz91** [comment]
Tested and still crashes.

**Comment by hrydgard** [comment]
Note that the earliest build with the possible fix is 1546.

**Comment by bizz91** [comment]
Android link plz.

**Comment by sum2012** [comment]
@bizz91 https://buildbot.orphis.net/ppsspp/index.php?m=dl&rev=v1.13.2-1546-g0719f1d4e&platform=android

**Comment by bizz91** [comment]
Its working. Now the other bug still exists.

**Comment by bizz91** [comment]
Requesting dev flatpak for Linux please.

**Comment by hrydgard** [comment]
@bizz91 that belongs in a separate issue.

**Comment by bizz91** [comment]
Its done. Close this thread please.
