### ISSUE TITLE
No water effects in Outrun 2006

### ISSUE THREAD

**Issue by dronrvgl** [hrydgard/ppsspp#16212]
### Game or games this happens in

ULUS10064 - Outrun 2006 Coast 2 Coast

### What area of the game

At the "National Park" track only

### What happens

There are no water effects on the highway of the National Park, instead of them there is an incomprehensible white shroud. On all other tracks (Outrun2 and Outrun2SP), the water effects look correct. The problem is present on both OpenGL ES and Vulkan.
![1s](https://user-images.githubusercontent.com/75202477/195652244-1e5f6328-b805-41c0-ab05-0ed308e9a3bf.jpg)
![2s](https://user-images.githubusercontent.com/75202477/195652274-fd4f6412-d7c0-46af-a0bf-275cd19b56ab.jpg)

### What should happen

Water effects should be displayed correctly

### GE frame capture

[ULUS10064.zip](https://github.com/hrydgard/ppsspp/files/9778673/ULUS10064.zip)

### Platform

Android

### Mobile phone model or graphics card

Redmi 5 (Adreno 506)

### PPSSPP version affected

v1.13.2-1517

### Last working version

-

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Well I didn't know about this specific water body, maybe it's a different effect? 

What does it look like on real hardware?

**Comment by dronrvgl** [comment]
I don't have a PSP console right now. I don't rule out that this is how it looks on a real console, but I can't confirm it. Maybe it's a bug of the game itself.

**Comment by RIKLAVIEGASINTRODUCTION** [comment]
I found some footage of the PSP version running on real hardware and it seems like correct behavior.
https://youtu.be/ZdoWzcWoENI?t=702

**Comment by hrydgard** [comment]
Thanks, closing.
