### ISSUE TITLE
Gta Chinatown wars crashes on the way to uncle Kennys in the beginning in new game.

### ISSUE THREAD

**Issue by bizz91** [hrydgard/ppsspp#16221]
Crashes on all apis on pc and phone.

**Comment by ANR2ME** [comment]
If it didn't crashed before, you need to tell us the last working version.
If the last working version is v1.13.2-1456-gbc9215ca9 it probably the same issue with https://github.com/hrydgard/ppsspp/issues/16215 in this case you don't need to open a new issue and should just post it there

**Comment by bizz91** [comment]
I have been in alot of crashes since 1.12.
1.11.1 was last one. It will take me a long time to test all dev builds, I managed to make my mind for this account.

**Comment by hrydgard** [comment]
Please test again in the newest build (with 16234 merged, when it's available)

**Comment by bizz91** [comment]
Still occurs on Android, tested 1544.

**Comment by bizz91** [comment]
The cwcheats are actually causing to stutter my game. It works fine without them.

**Comment by hrydgard** [comment]
Please note that it has to be the build that includes PR #16234, it was not up at the time I wrote. The build to test is number 1546.

**Comment by bizz91** [comment]
No download link available on ppsspp site for android build 1546.

**Comment by hrydgard** [comment]
It will be there soon.

**Comment by bizz91** [comment]
Alright. Will let you know later. Thanks.

**Comment by bizz91** [comment]
It still crashes after police cars go by near the docks in beginning, the mail bug is fixed.

**Comment by bizz91** [comment]
Tried other ways from the docks.
It shows Rockstar logo at bottom right corner. When I disable cheats, it loads fine.

**Comment by hrydgard** [comment]
If it only breaks with cheats, then the cheats aren't compatible with PPSSPP. 

(Sometimes PPSSPP allocates things in memory a bit differently than the real PSP due to missed things in the emulation, this can break certain types of cheats).

**Comment by bizz91** [comment]
Guess I have to maybe enable and disable cheats by game basis on the go.

**Comment by bizz91** [comment]
I am still keeping this thread open since maybe some volunteer would fix this.

**Comment by bizz91** [comment]
I created a thread on cwcheat repo regarding Gta Chinatown Wars.

**Comment by unknownbrackets** [comment]
I'm going to close this - if there was a cheat that worked in an older version but stopped working in a newer version, and never worked on a real PSP, it just means that we fixed something PPSSPP was doing differently from a real PSP.

Unfortunately, some types of cheats have to be updated when emulation accuracy improves.

-[Unknown]
