### ISSUE TITLE
Replace glew with libeporxy or glad

### ISSUE THREAD

**Issue by catsout** [hrydgard/ppsspp#16237]
### What should happen

Compile ppsspp with both x11 and wayland support (opengl).  

GLEW issues:  
- doesn't support OpenGL ES.  
- cannot be built with GLX and EGL  
- cannot dynamically open GL libraries without linking  

Replacement choice:  
https://github.com/Dav1dde/glad  
https://github.com/anholt/libepoxy  

Related problem on other soft:  
https://developer.blender.org/T90676
https://github.com/blender/blender/commit/a296b8f694d1a93d40da78312758580f69b43be7

### Who would this benefit

*

### Platform (if relevant)

Linux / BSD

### Games this would be useful in

*

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by unknownbrackets** [comment]
I think we already have an issue on this?  Unfortunately this is the sort of thing that just needs someone motivated to actually do it, test it on multiple platforms (Linux, BSD, macOS, iOS, Windows, etc.)

-[Unknown]

**Comment by hrydgard** [comment]
To clarify, it's closed because glew works out after all with the correct, unintuitive error checking, not because it's replaced.
