### ISSUE TITLE
libretro jni can't compile

### ISSUE THREAD

**Issue by hsoftxl** [hrydgard/ppsspp#16269]
### Compiler and build tool versions

ndk 21e

### Operating system version

ubuntu 20.04

### Build commands used

ndk-build

### What happens

[armeabi-v7a] SharedLibrary  : libretro.so
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: multiple definition of 'XrVector3f_Add(XrVector3f, XrVector3f)'
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: previous definition here
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: multiple definition of 'XrPosef_Inverse(XrPosef)'
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: previous definition here
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: multiple definition of 'XrPosef_Identity()'
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: previous definition here
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: multiple definition of 'XrPosef_Multiply(XrPosef, XrPosef)'
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: previous definition here
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: multiple definition of 'XrPosef_Transform(XrPosef, XrVector3f)'
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: previous definition here
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: multiple definition of 'XrVector3f_Length(XrVector3f)'
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: previous definition here
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: multiple definition of 'ovrMatrix4f_Minor(ovrMatrix4f const*, int, int, int, int, int, int)'
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: previous definition here
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: multiple definition of 'ovrMatrix4f_Inverse(ovrMatrix4f const*)'
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: previous definition here
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: multiple definition of 'XrQuaternionf_Rotate(XrQuaternionf, XrVector3f)'
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: previous definition here
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: multiple definition of 'ovrMatrix4f_Multiply(ovrMatrix4f const*, ovrMatrix4f const*)'
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: previous definition here
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: multiple definition of 'XrQuaternionf_Inverse(XrQuaternionf)'
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: previous definition here
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: multiple definition of 'XrVector3f_Normalized(XrVector3f)'
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: previous definition here
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: multiple definition of 'XrQuaternionf_Multiply(XrQuaternionf, XrQuaternionf)'
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: previous definition here
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: multiple definition of 'XrVector3f_LengthSquared(XrVector3f)'
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: previous definition here
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: multiple definition of 'XrVector3f_ScalarMultiply(XrVector3f, float)'
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: previous definition here
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: multiple definition of 'ovrMatrix4f_ToEulerAngles(ovrMatrix4f const*)'
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: previous definition here
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: multiple definition of 'ovrMatrix4f_CreateRotation(float, float, float)'
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: previous definition here
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: multiple definition of 'XrQuaternionf_ToEulerAngles(XrQuaternionf)'
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: previous definition here
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: multiple definition of 'XrVector4f_MultiplyMatrix4f(ovrMatrix4f const*, XrVector4f const*)'
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: previous definition here
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: multiple definition of 'XrVector3f_GetAnglesFromVectors(XrVector3f, XrVector3f, XrVector3f)'
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: previous definition here
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: multiple definition of 'ovrMatrix4f_CreateProjectionFov(float, float, float, float, float, float)'
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: previous definition here
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: multiple definition of 'ovrMatrix4f_CreateFromQuaternion(XrQuaternionf const*)'
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: previous definition here
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: multiple definition of 'XrQuaternionf_CreateFromVectorAngle(XrVector3f, float)'
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: previous definition here
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: multiple definition of 'ToDegrees(float)'
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: previous definition here
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: multiple definition of 'ToRadians(float)'
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/Common/VR/VRMath.o: previous definition here
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/home/xielei/ndk/android-ndk-r21e/build/core/build-binary.mk:725: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/libretro.so] Error 1
xielei@DESKTOP-T3240L7:~/ppsspp/libretro/jni$

### PPSSPP version affected

commit b9b07e0537e3b0bf2d3a6101d22641b55155a247

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] Make sure to run `git submodule update --init --recursive` before building.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try deleting the build directory and running the build again.
- [ ] Check GitHub Actions, which builds every merge and PR.
- [ ] Include logs and help us reproduce.

**Comment by bugalo** [comment]
I have the same issue in Gentoo Linux trying tho build the PPSSPP libretro core. I found that file libretro/Makefile.common includes $(COMMONDIR)/VR/VRMath.cpp twice, and thus this error. Removing line 324 from libretro/Makefile.common fixes the issue for me.

**Comment by hrydgard** [comment]
Alright, should be fixed now.

**Comment by bugalo** [comment]
That was really fast. It works now, thanks a lot.
