### ISSUE TITLE
Remote Streaming scan for URLS in  html response doesn't properly escape characters

### ISSUE THREAD

**Issue by bengalih** [hrydgard/ppsspp#16263]
### Game or games this happens in

ALL

### What area of the game / PPSSPP

When hosting Remote Streaming from a non PPSSPP server, the URL scan from html response does not seem to properly escape all characters.

I'm not sure of the full extent, but can confirm that any titles with an ampersand (&) in them will not properly display in the list of games or stream when selected.

### What should happen

It appears that when PPSSPP generates the remote streaming index file that it only escapes space characters with a %20 encoding.  Other URL characters like brackets and ampersands do not seem to be encoded.

When a web server like IIS or apache creates a directory listing of URLs, these are not normally escaped in the dir listing.
The feature of the PPSSPP client which can parse out these URLs needs to be optimized to deal properly with special characters.

### Platform

Android

### Mobile phone model or graphics card

Pixel 3 XL

### PPSSPP version affected

1.13.2

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment]
So the html can contains something like `&amp;` in it and didn't get decoded correctly by PPSSPP?
If so, the PPSSPP will need to supports all kind of HTML entities in order to fully support html response from common web servers.
May be using a lightweight xml parser like https://github.com/zeux/pugixml

**Comment by bengalih** [comment]
So far the only character that appears to be an issue is "&".  Because this is actually a valid character in several PSP games, I believe code should be introduced to handle _at least_ this scenario.

For example, the following file containing the de-facto title:

"Ratchet & Clank Size Matters [UCUS-98633] (UMD).cso"

PPSSPP's remote streaming server would encode this file by simply replacing spaces with %20 so the output in it's index file will appear as:

"Ratchet%20&%20Clank%20Size%20Matters%20[UCUS-98633]%20(UMD).cso"

It is important to note that the index file created by PPSSPP is not an HTML file per-se, but simply a text file with a list of the relative file names and does not contain any encoded HREFs

On the other hand, a directory browsing listing created dynamically by a web server will create an HTML file with the following:

```
<A HREF="/Ratchet%20&amp;%20Clank%20Size%20Matters%20[UCUS-98633]%20(UMD).cso">
Ratchet &amp; Clank Size Matters [UCUS-98633] (UMD).cso
</A>
```

The above would be considered standard encoding for each HREF, not only replacing the spaces with `%20`, but yes replacing an `&` with `&amp;`

Based upon the success of all files except those containing `&`, it would appear the PPSSPP client is attempting to parse out the HREF target and not the text.  Because it doesn't expect the `&` to be encoded and only the spaces, it will fail on all these files.

A failure on a specific file does not however prevent it from parsing the rest of the document.  So, in my list of ~135 games, only 3 fail to load because of this issue.

**Comment by unknownbrackets** [comment]
Well, the parsing of the HTML that was contributed was pretty simple.  I think simple additions are fine, but technically there's a range of entities (including ones outside standard HTML) which should be decoded.

For example, `&#65;` should be "A", and `&aacute;` should be "á".  It'd be perfectly reasonable for a filename to have either of those letters, but luckily most webservers won't encode those as entities unnecessarily.  More likely might be `&amp;`, `&quot;`, or `&apos;` which one could more easily imagine a webserver encoding when generating an index file.

I haven't really looked at the HTML parsing code much, but I'd guess it could just do a simple `ReplaceAll()` to swap out those entities.

-[Unknown]

**Comment by hrydgard** [comment]
If noone beats me to it, i'll take care of this in the near future, not like it's difficult :)

**Comment by ANR2ME** [comment]
> Thanks for tagging it. My point above is that `&` is _definitely_ a character in multiple PSP game names. While there are many characters that _should_ be encoded properly as they _could_ exist in a file name, I was just pointing out that priority should go to properly reading the characters that will _definitely_ be in a file name if the file is named with the official game title.
> 
> Apart from `&`, I believe `@` is in some titles as well as `:` . I would expect those might be the most problematic as off-hand I know those can be used to denote user/pass strings in a URL.

`dash` symbol might also be part of title, right? for example in this PSP game list (which seems to be taken from redump.org) contains `–` (dash) https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/redump/Sony%20-%20PlayStation%20Portable.dat

**Comment by hrydgard** [comment]
Did a quick hack: #16340
