### ISSUE TITLE
Ppsspp failed to build with error C2440, error C2131 on MSVC

### ISSUE THREAD

**Issue by fangzhouxia** [hrydgard/ppsspp#16282]
### Game or games this happens in

None

### What area of the game / PPSSPP

Hi all,
PPsspp fails to build on MSVC due to error C2440, error C2131. Could you help look?

**Repro steps**
1. git clone https://github.com/hrydgard/ppsspp F:\gitP\hrydgard\ppsspp
2. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=amd64 & set _CL_= /permissive-
3.  mkdir build_amd64 & cd F:\gitP\hrydgard\ppsspp\build_amd64
4.  msbuild /m /p:Platform=x64 /p:Configuration=Release ../Windows/PPSSPP.sln /t:Rebuild /p:OutDir=F:\gitP\hrydgard\ppsspp\build_amd64 2>&1
**error info** 
F:\gitP\hrydgard\ppsspp\GPU\GeDisasm.cpp(98,3): error C2440: 'initializing': cannot convert from 'const char [7]' to 'char *const ' [F:\gitP\hrydgard\ppsspp\GPU\GPU.vcxproj
F:\gitP\hrydgard\ppsspp\GPU\GeDisasm.cpp(97,40): error C2131: expression did not evaluate to a constant [F:\gitP\hrydgard\ppsspp\GPU\GPU.vcxproj]

### What should happen

Build successfully

### Logs

[build (31).log](https://github.com/hrydgard/ppsspp/files/9850831/build.31.log)

### Platform

Windows

### Mobile phone model or graphics card

None

### PPSSPP version affected

None

### Last working version

None

### Graphics backend (3D API)

Other

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
It looks like you're not using the latest git build.  The errors and warnings in your log are from 2 months ago and are not present in the latest git.  We were - for a short period of time - using `static constexpr char *[]` there (intended to indicate the array and values were all const), which was changed 2 months ago to `static const char *const []`.

Closing this as outdated.

-[Unknown]
