### ISSUE TITLE
[MSVC][permissive-] Ppsspp failed to build with msvc due to error C2039, error C2065...... on Windows

### ISSUE THREAD

**Issue by fangzhouxia** [hrydgard/ppsspp#16285]
### Game or games this happens in

None

### What area of the game / PPSSPP

Hi all,
PPsspp fails to build on MSVC due to error C2039, error C2065, error C2923 error C2976, error C2641, error C2371, error C2955, error C2780. Could you help look?

we use commit is 91886be.

**Repro steps**
1. git clone https://github.com/hrydgard/ppsspp F:\gitP\hrydgard\ppsspp
2. set _CL_= /permissive-
3. mkdir build_amd64 & cd F:\gitP\hrydgard\ppsspp\build_amd64
4. msbuild /m /p:Platform=x64 /p:Configuration=Release ../Windows/PPSSPP.sln /t:Rebuild /p:OutDir=F:\gitP\hrydgard\ppsspp\build_amd64 
**error info**
F:\gitP\hrydgard\ppsspp\ext\armips\Parser\DirectivesParser.h(16,51): error C2039: 'string': is not a member of 'std' (compiling source file armips\Parser\DirectivesParser.cpp) [F:\gitP\hrydgard\ppsspp\ext\libarmips.vcxproj]
F:\gitP\hrydgard\ppsspp\ext\armips\Parser\DirectivesParser.h(16,57): error C2065: 'string': undeclared identifier (compiling source file armips\Parser\DirectivesParser.cpp) [F:\gitP\hrydgard\ppsspp\ext\libarmips.vcxproj]
F:\gitP\hrydgard\ppsspp\ext\armips\Parser\DirectivesParser.h(16,27): error C2923: 'std::unordered_multimap': 'string' is not a valid template type argument for parameter '_Kty' (compiling source file armips\Parser\DirectivesParser.cpp) [F:\gitP\hrydgard\ppsspp\ext\libarmips.vcxproj]
F:\gitP\hrydgard\ppsspp\ext\armips\Parser\DirectivesParser.h(16,27): error C2976: 'std::unordered_multimap': too few template arguments (compiling source file armips\Parser\DirectivesParser.cpp) [F:\gitP\hrydgard\ppsspp\ext\libarmips.vcxproj]

### What should happen

Build successfully

### Logs

[build (13).log](https://github.com/hrydgard/ppsspp/files/9868325/build.13.log)

### Platform

Windows

### Mobile phone model or graphics card

None

### PPSSPP version affected

None

### Last working version

None

### Graphics backend (3D API)

Other

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment]
did you forgot to do `git submodule update --init --recursive` after git clone?

**Comment by unknownbrackets** [comment]
Thanks, these are reasonable - seems to just be a missing `#include <string>`.  Actually a problem in a library, but easy enough to fix:
https://github.com/Kingcom/armips/pull/233

-[Unknown]

**Comment by fangzhouxia** [comment]
Add the git submodule update --init --recursive problem still exists.
Steps to reproduce the behavior:
1. git clone --recurse https://github.com/hrydgard/ppsspp.git F:\gitP\hrydgard\ppsspp_new
2. set _CL_= /permissive-
3. makir build_amd64
4. cd F:\gitP\hrydgard\ppsspp_new\build_amd64
5. msbuild /m /p:Platform=x64 /p:Configuration=Release ../Windows/PPSSPP.sln /t:Rebuild /p:OutDir=F:\gitP\hrydgard\ppsspp_new\build_amd64

**Comment by unknownbrackets** [comment]
Should be working in latest git now.

-[Unknown]
