### ISSUE TITLE
Outrun 2006. PPSSPP crashes on extended  ending movie

### ISSUE THREAD

**Issue by dronrvgl** [hrydgard/ppsspp#16297]
### Game or games this happens in

ULUS10064 - Outrun 2006 Coast 2 Coast

### What area of the game / PPSSPP

On the "Legend" stage, on the extended ending movie. (Vulkan/OpenGL)
[save.zip](https://github.com/hrydgard/ppsspp/files/9894324/save.zip)

### What should happen

It shouldn't crash.

### Logs

[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/9894347/ppsspplog.zip)
This is a log from Windows, where the emulator also crashes with an error.

### Platform

Android

### Mobile phone model or graphics card

Redmi 5 (Adreno 506)

### PPSSPP version affected

v1.13.2-1705-g375f2433f

### Last working version

-

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by sum2012** [comment]
The game get struck after this logging
48:37:015 idle0        E[G3D]: GPU\GPUCommon.cpp:1396 CALL to illegal address 00000000 - ignoring! data=000000
v1.13.2-1734-gcf27d1413 full log
https://gist.github.com/sum2012/b9123f284cb722f4781c8e9ba4457d89

**Comment by sum2012** [comment]
In soft gpu,simulator logging 
55:58:289 idle0        E[G3D]: Software\SoftGpu.cpp:1218 CALL to illegal address 00000000 - ignoring! data=000000

**Comment by unknownbrackets** [comment]
Does this work on JPCSP or an older stable version?  Or it's just never worked?

-[Unknown]

**Comment by dronrvgl** [comment]
This was also the case on the previous stable versions of PPSSPP.

**Comment by sum2012** [comment]
@unknownbrackets Maybe the garbage came from this 
47:56:885 user_main    W[LOADER]: HLE\sceKernelModule.cpp:795 Unknown syscall from known module 'SysMemForKernel': 0x7b749390 (import for 'sceUSB_PSPComm_Driver')
47:56:885 user_main    W[LOADER]: HLE\sceKernelModule.cpp:795 Unknown syscall from known module 'SysMemForKernel': 0xeb7a74db (import for 'sceUSB_PSPComm_Driver')
47:56:908 sceUSB_PSPCo W[JIT]: x86\CompBranch.cpp:802 Encountered bad syscall instruction at 0822b430 (03ffffcc)
47:56:908 sceUSB_PSPCo E[HLE]: HLE\HLE.cpp:671 Unknown syscall: Module: (unknown) (module: 255 func: 4095)
47:56:908 sceUSB_PSPCo E[HLE]: HLE\HLE.cpp:671 Unknown syscall: Module: (unknown) (module: 255 func: 4095)

**Comment by unknownbrackets** [comment]
Which module is it importing when it hits that?  We could probably allow those nids in SysMemForKernel since I think they're Heap related.  But we probably should be HLEing whatever module imported them.

-[Unknown]

**Comment by sum2012** [comment]
@dronrvgl how to reproduce from beginning without "Save state" ?

**Comment by dronrvgl** [comment]
> @dronrvgl how to reproduce from beginning without "Save state" ?

Start the game, select "Outrun 2SP" (enjoy the original Outrun 2SP), then select Heart attack mode. You need to go to the goal "B" (3 times to the left, 1 time to the right). But for an extended video, you need to perform all tasks with the rank of AAA.

**Comment by sum2012** [comment]
@dronrvgl  Thanks for information
@unknownbrackets I cannot reproduce in JPCSP emulator because it is hard to reproduce from beginning,

**Comment by sum2012** [comment]
I still get "Encountered bad syscall instruction"
Seem need add sceUsbBus_driver

**Comment by sum2012** [comment]
@dronrvgl Do you know that this game whether have usb game protect ?

**Comment by dronrvgl** [comment]
> Do you know that this game whether have usb game protect ?

No.

**Comment by sum2012** [comment]
@dronrvgl please test this build from beginning, I added the above 2 patches and dummy sceUsbBus_driver
[PPSSPPWindows64-test.zip](https://github.com/hrydgard/ppsspp/files/9909998/PPSSPPWindows64-test.zip)

**Comment by dronrvgl** [comment]
> please test this build from beginning

Unfortunately, the emulator crashes at the same moment (

**Comment by sum2012** [comment]
@dronrvgl  Can you try jpcsp emulator ? (Another PSP emulator )
First use official build, https://github.com/jpcsp/jpcsp/suites/8933779382/artifacts/409823041
You need o install  JAVA whether you do not have it.
Move (Or copy) you iso into umdimages folder.
Run start-windows-amd64.bat

**Comment by dronrvgl** [comment]
> Can you try jpcsp emulator ?

I've tried Opengl and Software mode, but I can't configure it so that I can see the route clearly. Half of the screen is blocked from below by an incomprehensible blue stripe, on some routes almost the whole picture is white, only cars are visible. Compared to PPSSPP, it is almost unplayable, especially since it needs a rank not lower than AAA. In addition, the emulator with this game sometimes crashes.

**Comment by sum2012** [comment]
@dronrvgl how about this build ? (The first patch)
[PPSSPPWindows64-test2.zip](https://github.com/hrydgard/ppsspp/files/9929477/PPSSPPWindows64-test2.zip)

**Comment by sum2012** [comment]
@dronrvgl try update graphic driver

**Comment by sum2012** [comment]
@dronrvgl I forget to tell you that you need turn off fast memory

**Comment by dronrvgl** [comment]
> turn off fast memory

Yes, great! Now it works! However, for some reason there is no golden rain over the characters)) But that's another question.

**Comment by sum2012** [comment]
ppsspp-v1.16.6-280-g6d063ce3e-windows-amd64
Trying Sim UMD delay and Sim slow umd speed also fail

**Comment by sum2012** [comment]
suddenly get atrac error 
![2](https://github.com/hrydgard/ppsspp/assets/2177532/6ddb77d0-2a64-4f52-a8bd-7ee647bf1ded)

**Comment by sum2012** [comment]
Her hair have problem even in softgpu , maybe need a error code in gpu ?
![2](https://github.com/hrydgard/ppsspp/assets/2177532/2741c94a-9ef7-4d3e-8298-13e0c9a7bbb1)

**Comment by sum2012** [comment]
Not sure related this jpcsp change
https://github.com/jpcsp/jpcsp/commit/93744e0181a6087a49ace4d7921a00cb093e8ea7
