### ISSUE TITLE
[PGF-font] Incorrect display of Japanese characters

### ISSUE THREAD

**Issue by Nabokov86** [hrydgard/ppsspp#16292]
### Game or games this happens in

ULJM06233 - Grisaia no Kajitsu

### What happens

The most noticeable is the dot "。". But other characters are displayed differently, too.

v1.13.2-1656
![v1 11 3-GP](https://user-images.githubusercontent.com/26260168/198594074-c075e1a5-f143-4f05-950c-810286c79ca6.png)
v1.11.3-GP
![v1 13 2-1656](https://user-images.githubusercontent.com/26260168/198594132-2982f41c-d126-4e56-9211-6c4c34d80728.png)

Video comparison

https://user-images.githubusercontent.com/26260168/198601395-9915643f-397e-4a5d-934b-80f9a268ad92.mp4

### GE frame capture

[ULJM06233_0001.zip](https://github.com/hrydgard/ppsspp/files/9890472/ULJM06233_0001.zip)

### Platform

Windows, Android

### PPSSPP version affected

v1.13.2-1656

### Last working version

v1.11.3-GP

### Graphics backend (3D API)

OpenGL
Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment]
It would be nice if you can provide a GE frame dump when reporting graphical issue https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump
Because the devs might not have the game, but can still analyze the issue from the GE dump.

**Comment by Nabokov86** [comment]
@ANR2ME GE frame dump [ULJM06233_0001.zip](https://github.com/hrydgard/ppsspp/files/9890472/ULJM06233_0001.zip)

**Comment by ANR2ME** [comment]
Hmm the last dot "。" is also truncated even with software rendering
![image](https://user-images.githubusercontent.com/7974720/198701952-21e8555e-26bd-4f61-a92f-6dff4e299929.png)

**Comment by unknownbrackets** [comment]
This looks like a PGF font issue.  Are both versions using the same assets / flash0?

-[Unknown]

**Comment by Nabokov86** [comment]
@unknownbrackets You are right! The Japanese fonts are different in these versions. 

Moved fonts from v1.11.3, now the characters are displayed correctly.

**Comment by nassau-tk** [comment]
@unknownbrackets 
How do you think about it?
1. Issue of  PGF data.
2. Othere.

**Comment by hrydgard** [comment]
Hm. here are the last list of changes to our PGF data, all by you:

082bf0d67cbdf7d359fa12c24ca4600819d00ad2
09f90969ecf0c02271149062e6167fbc13cd4f26
a384b62247f1971555fb68f796c01df8fb8f984a
848142d2aca94eb9d7178ee28f17aa0c4ea1a94f
41927a5c39951cb068805b86d3dcd74417e40845
42f28ce41ef9964d616cdc09379dd982e1e33943

So you seem to be the expert already @nassau-tk  :)

**Comment by nassau-tk** [comment]
Oops!!

OK, I will check the data.
Give me time!!

**Comment by hrydgard** [comment]
Haha, no rush. 1.14 will probably be in about 2 weeks.

**Comment by nassau-tk** [comment]
I'm listening that you say "Hurry up!!". lol

OK,I will try to fix it!

**Comment by unknownbrackets** [comment]
My guess is that it's a metrics issue, and some character on that line (probably the period) has metrics that confuse the game.  It shows the previous period correctly though, so I'm not completely sure.

-[Unknown]

**Comment by Nabokov86** [comment]
> It shows the previous period correctly

No, all the dots are displayed in the wrong position.

The dot should be displayed in the lower left corner, but instead it is displayed in the center. It looks like the last dot is truncated because of the text box.
![198594074-c075e1a5-f143-4f05-950c-810286c79ca6](https://user-images.githubusercontent.com/26260168/204724660-4124ae09-7831-49aa-b3ac-1cf489462962.png)

**Comment by Nabokov86** [comment]
Same issue with the comma.
![ULJM06233_](https://user-images.githubusercontent.com/26260168/204726135-c76a1f50-c52d-40c6-8947-024dac38bdc5.png)

**Comment by unknownbrackets** [comment]
Well, you're comparing with an old version that also uses an incorrect font.  You could actually use fonts from a real PSP, and both versions would display text the same way.  The issue is that the old version used a custom font (not a copyrighted one) that was wrong, and the new version uses an updated custom font that has many fixes - and fixed problems in games that need the font to be more like the real PSP font - but has this problem.

The spacing should ideally look however it looked on a real PSP with real fonts.  The old version with its wrong font may not have this bug, but that doesn't mean it's how it should have looked.

-[Unknown]

**Comment by Nabokov86** [comment]
@unknownbrackets I know all that. I'm not comparing with the old version of the font. I'm just saying how it should look and how it looked on the real PSP too.

With the original PSP fonts:
![ULJM06233_00006](https://user-images.githubusercontent.com/26260168/204734849-c38f44ad-2c07-455a-9038-6b9ff450e26b.png)

Video recorded from the original PSP:
https://youtu.be/batYerZNPJQ

**Comment by hrydgard** [comment]
Seems then that all that needs to be done for a decent result is to tweak the metrics/position for the dot character in our current japanese font?

**Comment by Nabokov86** [comment]
Yes. I don't see any other significant problems with the current fonts.

**Comment by Nabokov86** [comment]
Oh no, there are other characters with this problem. 

I need time to test it. All punctuation marks seem to have this problem, but I'm not sure.

**Comment by Nabokov86** [comment]
@nassau-tk Could you please check these characters: 「。」、「、」、「❝」、「❞」

These four characters are all displayed in the wrong position and sometimes displayed truncated.

❝❞ original font:
![ULJM06233_Original](https://user-images.githubusercontent.com/26260168/204763093-379f14d1-2c5c-4d76-a11d-c5d29b97d97c.png)

❝❞ custom font:
![ULJM06233_Custom](https://user-images.githubusercontent.com/26260168/204763159-97391d62-89fe-47ad-963d-84fab8f0a0b1.png)

Truncated comma and dot:
![ULJM06233_dot_comma](https://user-images.githubusercontent.com/26260168/204763246-5667435f-60f4-4673-8146-6b66959b7334.png)

**Comment by nassau-tk** [comment]
oK!
Thanks!

**Comment by Nabokov86** [comment]
> If you are Japanese

Haha, I'm not Japanese, but I know the language a little.

Good luck with this font!

**Comment by nassau-tk** [comment]
OK
I fixed it.
[jpn0.zip](https://github.com/hrydgard/ppsspp/files/10123440/jpn0.zip)

**Comment by Nabokov86** [comment]
Everything is displayed correctly now :sparkles: @nassau-tk Thank you for your work!
