### ISSUE TITLE
Crash when clicking "Settings" in home screen and in game 

### ISSUE THREAD

**Issue by yaringal** [hrydgard/ppsspp#16317]
### Game or games this happens in

All

### What area of the game / PPSSPP

Settings menus doesn't load and instead freezes app

### What should happen

Should not crash

### Platform

Android

### Mobile phone model or graphics card

Pico 4

### PPSSPP version affected

v1.10 onwards

### Last working version

v1.9.4

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by lvonasek** [comment]
Hi, the versions you tested are very old and unlikely to work on Pico 4. I would recommend to try the latest version made for your headset:
https://drive.google.com/drive/folders/1GgyJqk6WTYGTFfQF6kojJMIHItdzrjaM?usp=sharing

**Comment by lvonasek** [comment]
I guess something went wrong with the settings file. Could you try to delete ppsspp.ini from the filesystem and then open the latest VR version?

**Comment by yaringal** [comment]
Yep I tried that (deleted the entire psp folder between testing different versions)

**Comment by lvonasek** [comment]
Could you try this build?
https://drive.google.com/file/d/19iiE5W7AYsXCjI_VaCZl1xL6x4jRexf9/view?usp=sharing

**Comment by yaringal** [comment]
I just tried the version you shared - it still crashes the same way when clicking Settings

**Comment by lvonasek** [comment]
Ok thanks. I will try to fix it one more time. I might be able to share an APK tonight.

**Comment by lvonasek** [comment]
I am sorry, I am not able to easily resolve it. I will take a look into this again, once I get Pico 4 myself (in about 2 weeks).

**Comment by yaringal** [comment]
I can confirm this works now - many thanks!
