### ISSUE TITLE
all games force close on Exynos 7904

### ISSUE THREAD

**Issue by IrfanH495** [hrydgard/ppsspp#16315]
### Game or games this happens in

ULUS10567 - The 3rd Birthday

### What area of the game / PPSSPP

after loading the game.
all games i have force close
https://youtu.be/0Nilq1a2tCo

I tried already tried version
ppsspp-v1.13.2-1723-g1d97e7d03-android
ppsspp-v1.13.2-1726-gba32ef5ea-android
ppsspp-v1.13.2-1734-gcf27d1413-android
but still force close

### What should happen

no FC

### Platform

Android

### Mobile phone model or graphics card

SamsungM20

### PPSSPP version affected

ppsspp-v1.13.2-1723-g1d97e7d03-android

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
Does v1.13.2 (stable) still work?  Or any other version?

-[Unknown]

**Comment by IrfanH495** [comment]
@unknownbrackets 
ppsspp-v1.13.2-1697-g109db81ec-android all games are still normal no fc
ppsspp-v1.13.2-1703-gac818d963-android starting to experience force close, I just tried a few games.

**Comment by unknownbrackets** [comment]
Thanks, that points to #16291, which indeed only affected Vulkan.  Strange, I wonder if there's a driver issue or if we missed something following the spec there...

-[Unknown]

**Comment by IrfanH495** [comment]
can play in vulkan without force close after geometry shader culling is disabled.
if the issue name is not good, you can change it.
and if this is not an issue you can close it.

**Comment by hrydgard** [comment]
I forgot to update one line in the geo shader generator. Will fix later today

**Comment by hrydgard** [comment]
That should take care of it, hopefully.

**Comment by IrfanH495** [comment]
thank you very much, I will try it later tonight, my internet data is low. 😀
