### ISSUE TITLE
Build fails on KDE Neon

### ISSUE THREAD

**Issue by Blad3forc3** [hrydgard/ppsspp#16334]
### Platform

Linux / BSD

### Compiler and build tool versions

GCC-10

### Operating system version

KDE Neon 22.04

### Build commands used

./b.sh --release

### What happens

Generating for x86, Release
Generating for x86_64, Release
CMake Error at ext/armips/CMakeLists.txt:78 (add_subdirectory):
  The source directory

    /media/ade/Temp/ppsspp/ext/armips/ext/filesystem

  does not contain a CMakeLists.txt file.

### PPSSPP version affected

Latest git

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] Make sure to run `git submodule update --init --recursive` before building.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try deleting the build directory and running the build again.
- [ ] Check GitHub Actions, which builds every merge and PR.
- [ ] Include logs and help us reproduce.

**Comment by unknownbrackets** [comment]
This simply means you didn't use `--recursive` on the submodule update, as was noted in the checklist.  The armips submodule itself contains a submodule.

-[Unknown]

**Comment by unknownbrackets** [comment]
Closing this as not an issue - cloning and submodule updates are documented in the build instructions as well as in the issue reporting.  It's a common mistake, though.

-[Unknown]
