### ISSUE TITLE
(Adreno)(Vulkan) King of Fighters '96 broken graphics

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#16335]
### Game or games this happens in

NPUH10119

### What area of the game

Menu selection

### What happens

Broken graphics on vulkan
![Screenshot_20221106_022740_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37603562/200135457-4eed0340-9854-43ad-99fe-4b05c9e3da4d.jpg)

### What should happen

Good graphics on opengl
![Screenshot_20221106_022715_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37603562/200135472-a53e442a-c87d-4c9e-bdac-ece13f63e670.jpg)

### GE frame capture

[NPUH10119.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/9944491/NPUH10119.ppdmp.zip)

### Platform

Android

### Mobile phone model or graphics card

Vivo Y11 Android 11 Snapdragon 439 Adreno 505

### PPSSPP version affected

v1.13.2-1770

### Last working version

1.12

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by Panderner** [comment]
Vulkan for my PC is not affected:
![NPUH10119_00000](https://user-images.githubusercontent.com/37503397/200158442-880c130d-60c3-49b2-a28e-28a877ddd13e.jpg)

**Comment by Gamemulatorer** [comment]
> Vulkan for my PC is not affected: ![NPUH10119_00000](https://user-images.githubusercontent.com/37503397/200158442-880c130d-60c3-49b2-a28e-28a877ddd13e.jpg)

How about in your poco phone?

**Comment by Panderner** [comment]
Same happen for my phone:
![Screenshot_2022-11-06-19-21-03-506_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/200167680-5403be9d-0158-4d2c-8837-6b79095a111a.jpg)

I need a Mali device for testing.

**Comment by Gamemulatorer** [comment]
> Same happen for my phone: ![Screenshot_2022-11-06-19-21-03-506_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/200167680-5403be9d-0158-4d2c-8837-6b79095a111a.jpg)
> 
> I need a Mali device for testing.

Yes agree Mali GPU with vulkan supported must be try.

**Comment by unknownbrackets** [comment]
Draw is pretty simple except the CLUT usage:
 * Alpha blend (standard src.a / 1 - src.a), test (a > 0)
 * No mask, logic op, etc. on 565 target.
 * From texture with 5551 using CLUT start pos.

If the device in question has limited 16-bit texture support, this looks like the #16358 case, so I suspect #16358 will fix this.  This would explain why it doesn't reproduce on all devices.

-[Unknown]

**Comment by Gamemulatorer** [comment]
Safe to tag this as adreno gpu issue only because this was fix via https://github.com/hrydgard/ppsspp/pull/16358 🎉

**Comment by Gamemulatorer** [comment]
> > Same happen for my phone: ![Screenshot_2022-11-06-19-21-03-506_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/200167680-5403be9d-0158-4d2c-8837-6b79095a111a.jpg)
> > I need a Mali device for testing.
> 
> Yes agree Mali GPU with vulkan supported must be try.

Confirm cannot reproduce in MALI GPU Vulkan.
![Screenshot_20221113-220438](https://user-images.githubusercontent.com/37603562/201525945-66d59bb6-ff10-4e14-a1b4-7ca558235840.png)
