### ISSUE TITLE
(GE Emulation)(PSMF/MPEG) Monster Hunter 3rd HD Video Double Image Glitch

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#16360]
### Game or games this happens in

NPJB40001 - Monster Hunter 3rd HD

### What area of the game

During first cut scene

### What happens

https://user-images.githubusercontent.com/37603562/200479242-812581ea-ebb1-402d-b094-23f0ce21c25f.mp4

### What should happen

No glitches during cut scene.

https://user-images.githubusercontent.com/37603562/200479792-44e0e928-634f-471b-9af0-6708eb6ecb7a.mp4

### GE frame capture
[NPJB40001.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/9957779/NPJB40001.ppdmp.zip)

### Platform

Android

### Mobile phone model or graphics card

Vivo Y11 Android 11 Snapdragon 439 Adreno 505

### PPSSPP version affected

v1.13.2-1861

### Last working version
v1.13.2

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
Can you test a version around -900 or -1000 to narrow down when this started a bit?

I wonder if this is sceJpeg and maybe for HD remasters or something it behaves differently?

-[Unknown]

**Comment by hrydgard** [comment]
Yeah very much looks like a glitch in YUV->RGB conversion...

**Comment by Gamemulatorer** [comment]
Issue started in build https://github.com/hrydgard/ppsspp/commit/76be009b4113703f07ad09c243cf4246fcbb8fd1
Last build without double image issue https://github.com/hrydgard/ppsspp/commit/a081d684ee3a6dcda655ff1ccfbccfa73a8e9c49
Might be the culprit is https://github.com/hrydgard/ppsspp/commit/af28a3d497bc9149c70284eb2e6cc881843e9966

**Comment by unknownbrackets** [comment]
A log with ME set to Debug or Verbose would probably help.  I guess we could chnange the planar order just on HD remasters, though...

-[Unknown]

**Comment by Gamemulatorer** [comment]
> A log with ME set to Debug or Verbose would probably help. I guess we could chnange the planar order
just on HD remasters, though...
> 
> -[Unknown]

How to get log with ME set to debug using android?

**Comment by unknownbrackets** [comment]
You could use the debugger: http://ppsspp-debugger.unknownbrackets.org/

Under PPSSPP's developer tools you can set ME log level, and then it'll send log messages to the browser you have connected, which you can copy and paste into a message here or into https://gist.github.com/.

But I think maybe based on #3821 I have a theory, the sceMpegAvcConvertToYuv420() function is probably wrong and needs to be corrected.  I should probably do some tests to be safe... wonder if I have any games that use it.

-[Unknown]

**Comment by Gamemulatorer** [comment]
I don't know if this right.
https://gist.github.com/Gamemulatorer/c5e2cb54244aec6fbd99486bf6cb32e1

**Comment by Gamemulatorer** [comment]
Thanks
