### ISSUE TITLE
Jeanne D'Arc corrupted graphics

### ISSUE THREAD

**Issue by NineKain** [hrydgard/ppsspp#16377]
### Game or games this happens in

UCUS98700: JEANNE D'ARC

### What area of the game

Just start a new game, skip the starting cutscene.

### What happens

![image](https://user-images.githubusercontent.com/72826232/201446683-0bee94d3-1046-46e8-98cb-79ddfdef0e82.png)

### What should happen

Not be scrambled and weird.

### GE frame capture

[UCUS98700.zip](https://github.com/hrydgard/ppsspp/files/9993715/UCUS98700.zip)

### Platform

Windows

### Mobile phone model or graphics card

3060ti

### PPSSPP version affected

v1.13.2-1900-g7c5ddcecb

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
This game reuses depth between framebuffers.  Your screenshot looks like what might happen if it was copied incorrectly.

Have you updated your graphics drivers?  It's not happening for me on NVIDIA.

If you download the latest git build into a new directory (so it has new settings) and switch to Vulkan only, does it still happen?  If not, there may be some setting at play.  The game definitely won't work with "skip buffer effects" or some other speed hacks.

-[Unknown]

**Comment by Panderner** [comment]
Hmm it's working fine for me i'm using GTX 1050 Ti with latest GPU drivers installed.
![UCUS98700_00000](https://user-images.githubusercontent.com/37503397/201454008-902ea35a-f974-47ee-928e-313aa1b8e0b4.jpg)

**Comment by NineKain** [comment]
I have 526.47 drivers, can I post a log?

**Comment by NineKain** [comment]
Fresh ppsspp build from latest buildbot also has this issue with default settings and Vulkan

**Comment by unknownbrackets** [comment]
Strange.  I'm not sure a log would tell anything.

If you change the rendering resolution temporarily to 1x and run the game that way, does it render correctly?  Just trying to figure out where the bug is.

And it works fine using OpenGL (which does the exact same depth copying) at any resolution?

-[Unknown]

**Comment by LunaMoo** [comment]
Latest Nvidia driver is 526.86 I'll update my own to it in a bit, it apparently includes a fix for previously reported corruption issues, so maybe that's what you're experiencing with 526.47.

**Comment by LunaMoo** [comment]
Disabling both works around the problem, disabling just useCopy keeps the glitch.

**Comment by unknownbrackets** [comment]
I created #16395 to just do that, although I'm worried there's some hazard we're somehow not handling here with the depth?  May just be a driver bug, though.

-[Unknown]

**Comment by unknownbrackets** [comment]
Is this working now in the latest git builds?

-[Unknown]

**Comment by NineKain** [comment]
100% fixed, thanks
