### ISSUE TITLE
Add options when reseting PPSSPP settings to default

### ISSUE THREAD

**Issue by ANR2ME** [hrydgard/ppsspp#16381]
### What should happen

For example selecting parts that will be reset.

- [x] Settings
- [ ] Controller mappings
- [ ] Recent history

### Who would this benefit

People who don't want to loose their recent history, especially when testing for bugs, player often asked to reset their settings.

### Games this would be useful in

None

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by iota97** [comment]
Control mapping aren't restored afair, are they? If so I think we should just don't reset recent game list (that's what you mean with history right?) rather than making the menu more complicated.

**Comment by hrydgard** [comment]
Actually, it would be pretty easy to spawn a list of checkboxes with the sections to reset. Could probably get away with not adding any translation strings by just using the section names..

**Comment by iota97** [comment]
Sections in the ini doesn't really match setting menu sections (i.e. they are Generals, CPU, Systems and so on)

That being said if you want that check list this code should make the restore more flexible (untested for custom game configs, but should do):
```
void Config::RestoreDefaults(const std::vector<std::string> &keep) {
	Save("Restoring defaults...");
	Path iniPath = bGameSpecific ? Path(getGameConfigFile(gameId_)) : iniFilename_;
	IniFile iniFile;
	if (iniFile.Load(iniPath)) {
		std::vector<std::string> sections;

		for (auto &s : iniFile.Sections()) {
			if (std::find(keep.begin(), keep.end(), s.name()) == keep.end()) {
				sections.push_back(s.name());
			}
		}

		for (auto &s : sections) {
			iniFile.DeleteSection(s.c_str());
		}
		iniFile.Save(iniPath);
	}
	Load();
}
```

**Comment by hrydgard** [comment]
That's true that the sections and categories don't match - although arguably they should!

But maybe the suggestion in the OP is enough - just separating the three: controls, settings, recent.

**Comment by iota97** [comment]
The 3 seems fine, there's only the problem of my mistake about few control settings being in general (same problem of controls profile).

I guess we can workaround that with a bit of code complexity, we should probably decide if we want to have the code complexity (that won't be much) or move once for all.

Resetting controls should reset key binds too at that point I think.

**Comment by hrydgard** [comment]
How many, and which, control settings are in the wrong category? I think we might just want to go ahead and move them before adding the dialog, to make this clean. We can add a few lines of code to migrate the old settings to g_Config load.

And yeah, it doesn't make much sense to clear recent history when clearing settings at all. We even have a separate option for that.

**Comment by iota97** [comment]
As in #15406 they are:
```
        "RightAnalogUp",
	"RightAnalogDown",
	"RightAnalogLeft",
	"RightAnalogRight",
	"RightAnalogPress",
	"SwipeUp",
	"SwipeDown",
	"SwipeLeft",
	"SwipeRight",
	"DoubleTapGesture",
	"SwipeSensitivity",
	"SwipeSmoothing",
	"RightAnalogCustom",
	"RightAnalogDisableDiagonal",
	"GestureControlEnabled"
```

The one before the last commit have the port on load (sadly with settings version for the reasons you can see in the conversation between me and unknown).

We should probably have that PR in one way or another and then do this issue I think.

**Comment by Arashvscode** [comment]
Hello, dear developer, I request you to restore the hacker time feature, because it is compatible with 91% of games, which is a good statistic, without hacker time, in most phones, games run slowly, like God of war.
