### ISSUE TITLE
TwinBee portable regression

### ISSUE THREAD

**Issue by tondo82** [hrydgard/ppsspp#16382]
After the konami logo the problems start, both on Windows and Android!

31:36:558 Core\System.cpp:417 N[BOOT]: PPSSPP v1.13.2-1917-g1ae6047da Windows 64 bit
31:36:577 Core\Compatibility.cpp:129 N[G3D]: UnitsPerMeter for ULJM05221: 0.000000
31:36:671 root         N[BOOT]: UI\EmuScreen.cpp:356 Loading C:/Users/lucag/Desktop/cvn-twinp.iso...
31:37:179 user_main    E[SCEIO]: HLE\sceIo.cpp:2301 80020323=sceIoPollAsync(-1, 09fff5c0[0000000000000000]): invalid fd
31:42:118 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 000001e9 (0000013D254101E9)
31:42:118 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000003 (0000013D25410003)
31:42:118 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 000001e5 (0000013D254101E5)
31:42:118 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 2afab8b8 (0000013D503BB8B8)
31:42:118 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 2afab8b8 (0000013D503BB8B8)
31:42:118 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000003 (0000013D25410003)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 961afbee (0000013DBB5BFBEE)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 961afbec (0000013DBB5BFBEC)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000005 (0000013D25410005)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 000001e1 (0000013D254101E1)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 961afbf0 (0000013DBB5BFBF0)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000007 (0000013D25410007)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 000001e3 (0000013D254101E3)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000009 (0000013D25410009)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 0000000b (0000013D2541000B)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 000001e5 (0000013D254101E5)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 0000000d (0000013D2541000D)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 0000000f (0000013D2541000F)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000011 (0000013D25410011)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000009 (0000013D25410009)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000011 (0000013D25410011)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 0000000b (0000013D2541000B)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000015 (0000013D25410015)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 000001e5 (0000013D254101E5)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000015 (0000013D25410015)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000017 (0000013D25410017)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 000001e1 (0000013D254101E1)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000019 (0000013D25410019)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 000001e3 (0000013D254101E3)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 0000001b (0000013D2541001B)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 0000001d (0000013D2541001D)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 000001e5 (0000013D254101E5)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 0000001f (0000013D2541001F)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000021 (0000013D25410021)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000023 (0000013D25410023)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 0000001b (0000013D2541001B)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000023 (0000013D25410023)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 0000001d (0000013D2541001D)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000027 (0000013D25410027)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 000001e5 (0000013D254101E5)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000027 (0000013D25410027)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000029 (0000013D25410029)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 000001e1 (0000013D254101E1)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 0000002b (0000013D2541002B)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 000001e3 (0000013D254101E3)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 0000002d (0000013D2541002D)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 0000002f (0000013D2541002F)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 000001e5 (0000013D254101E5)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000031 (0000013D25410031)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000033 (0000013D25410033)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000035 (0000013D25410035)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 0000002d (0000013D2541002D)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000035 (0000013D25410035)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 0000002f (0000013D2541002F)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000039 (0000013D25410039)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 000001e5 (0000013D254101E5)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000039 (0000013D25410039)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 0000003b (0000013D2541003B)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 000001e1 (0000013D254101E1)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 0000003d (0000013D2541003D)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 000001e3 (0000013D254101E3)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 0000003f (0000013D2541003F)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000041 (0000013D25410041)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 000001e5 (0000013D254101E5)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000043 (0000013D25410043)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000045 (0000013D25410045)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000047 (0000013D25410047)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 0000003f (0000013D2541003F)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000047 (0000013D25410047)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000041 (0000013D25410041)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 0000004b (0000013D2541004B)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 000001e5 (0000013D254101E5)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 0000004b (0000013D2541004B)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 0000004d (0000013D2541004D)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 000001e1 (0000013D254101E1)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 0000004f (0000013D2541004F)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 000001e3 (0000013D254101E3)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000051 (0000013D25410051)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000053 (0000013D25410053)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 000001e5 (0000013D254101E5)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000055 (0000013D25410055)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000057 (0000013D25410057)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000059 (0000013D25410059)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000051 (0000013D25410051)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000059 (0000013D25410059)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000053 (0000013D25410053)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 0000005d (0000013D2541005D)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 000001e5 (0000013D254101E5)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 0000005d (0000013D2541005D)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 0000005f (0000013D2541005F)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 000001e1 (0000013D254101E1)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000061 (0000013D25410061)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 000001e3 (0000013D254101E3)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000063 (0000013D25410063)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000065 (0000013D25410065)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 000001e5 (0000013D254101E5)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000067 (0000013D25410067)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 00000069 (0000013D25410069)
31:42:119 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 0000006b (0000013D2541006B)
32:38:632 thread se (g E[JIT]: x86\CompBranch.cpp:644 Jump to invalid address: 03357e30 PC 08810a30 LR 08810a2c
32:38:632 thread se (g E[JIT]: x86\CompBranch.cpp:644 Jump to invalid address: 03357fb0 PC 08810a38 LR 08810a2c
32:38:632 thread se (g E[JIT]: x86\CompBranch.cpp:644 Jump to invalid address: 03358130 PC 08810a40 LR 08810a2c
32:38:632 thread se (g E[JIT]: x86\CompBranch.cpp:644 Jump to invalid address: 033582b0 PC 08810a48 LR 08810a2c
32:38:632 thread se (g E[JIT]: x86\CompBranch.cpp:644 Jump to invalid address: 03358430 PC 08810a50 LR 08810a2c
32:38:632 thread se (g E[JIT]: x86\CompBranch.cpp:644 Jump to invalid address: 033585b0 PC 08810a58 LR 08810a2c
32:38:632 thread se (g E[CPU]: MIPS\MIPSTables.cpp:916 MIPSCompileOp: Invalid instruction 00004828
32:38:632 thread se (g E[CPU]: MIPS\MIPSTables.cpp:916 MIPSCompileOp: Invalid instruction 00004828
32:38:632 thread se (g E[JIT]: x86\CompBranch.cpp:644 Jump to invalid address: 03358730 PC 08810a60 LR 08810a2c
32:38:632 thread se (g E[JIT]: x86\CompBranch.cpp:644 Jump to invalid address: 033588b0 PC 08810a68 LR 08810a2c
32:38:632 thread se (g E[JIT]: x86\Jit.cpp:658 Trying to compile instruction 00004834 that can't be interpreted
32:38:632 thread se (g E[JIT]: x86\Jit.cpp:658 Trying to compile instruction 00004834 that can't be interpreted
32:38:632 thread se (g E[JIT]: x86\CompBranch.cpp:644 Jump to invalid address: 03358a30 PC 08810a70 LR 08810a2c
32:38:632 thread se (g E[CPU]: MIPS\MIPSTables.cpp:916 MIPSCompileOp: Invalid instruction 0000483a
32:38:632 thread se (g E[CPU]: MIPS\MIPSTables.cpp:916 MIPSCompileOp: Invalid instruction 0000483a
32:38:632 thread se (g E[JIT]: x86\CompBranch.cpp:644 Jump to invalid address: 03358bb0 PC 08810a78 LR 08810a2c
32:38:632 thread se (g E[JIT]: x86\CompBranch.cpp:644 Jump to invalid address: 03358d30 PC 08810a80 LR 08810a2c
32:38:632 thread se (g E[JIT]: x86\CompBranch.cpp:644 Jump to invalid address: 03358eb0 PC 08810a88 LR 08810a2c
32:38:632 thread se (g E[HLE]: HLE\HLE.cpp:679 Syscall had bad function number 289 in module 0 - probably executing garbage

**Comment by unknownbrackets** [comment]
This just looks like a corrupt ISO file.

What's the last version of PPSSPP where this worked with your ISO file?  There's a reason for all the questions in the issue report template.

-[Unknown]

**Comment by tondo82** [comment]
i saw a video on youtube where it was played with version 0.91, i tried with this version and it works, with the latest versions i have problems after the konami logo! i tried various dumps and the result is always the same!

**Comment by Panderner** [comment]
@tondo82 Can you check the CRC for your ISO file?

**Comment by tondo82** [comment]
i have two versions:

9E6996A3

6AFB1450

both behave in the same way!

**Comment by Panderner** [comment]
It's working fine for my PC and my android phone.

@tondo82 have you tried to reset to default settings?

**Comment by tondo82** [comment]
yes with the app just installed by default, this difference is driving me crazy, other people say it works, I can't on both android and windows, only with an older version I can

**Comment by tondo82** [comment]
found it! since it works for everyone and you too, the only difference I thought is the language, if the system language is in Italian the problem occurs, if I set it to English the game starts normally

**Comment by hrydgard** [comment]
Wow, that's pretty interesting and weird. Can anyone test if that happens on PSP hardware too? Maybe it's an unusal enough case to run a japanese game on a console set to Italian that it wasn't caught.. And if it is indeed a gamebug, we should probably create a compat setting that forces English and/or Japanese for this game, since crash from such a cause is really annoying.

**Comment by unknownbrackets** [comment]
Yeah, this is a case where I'd support a compat flag.

-[Unknown]

**Comment by Panderner** [comment]
The game crashes if you set the ui language to spanish, german, french, and italian.

**Comment by sum2012** [comment]
I take a search , real psp need to set to english
![1](https://user-images.githubusercontent.com/2177532/201546445-a894780b-7019-42ae-913a-6fea1fc91e31.png)

**Comment by unknownbrackets** [comment]
Does this work now with v1.13.2-1932-g4219cfb66?

-[Unknown]

**Comment by tondo82** [comment]
affirmative, waiting for the stable version on Android, thanks a lot guys

**Comment by Gamemulatorer** [comment]
Very similar issue https://github.com/hrydgard/ppsspp/issues/15471
