### ISSUE TITLE
add more TAS support 

### ISSUE THREAD

**Issue by dananothername** [hrydgard/ppsspp#16391]
### What should happen

many people request TAS features 
PPSSPP should have a button for
- rewind frame and not rewind last save state 
- a pannel or something for input recording and then to switch for reading like in bizhawk
- while input recording can be enabled before starting the game 
here the emulator should store the same hash to keep the same RNG (random numbers generator ) this is very important for the TAS match each time opening the game 
a note : while encoding the frame rate was set to 30 fps while playing 50 fps it gives a weird behavior like the game glitch frame backward 
### Who would this benefit

the TASers from TASvideos and Reddit 

### Platform (if relevant)

Windows

### Games this would be useful in

any game 

### Other emulators or software with a similar feature

-retroarch support some of TAS features( tbh it needs to be easier )
-using ppsspp in libTAS in pain and i don't recommend it 
but you can see how the emulator work with TAS and make ppsspp work like it
- the best emulator for TAS is bizhawk 
tbh i want a  ppsspp core in libTAS

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by Gamemulatorer** [comment]
Dup https://github.com/hrydgard/ppsspp/issues/15617

**Comment by hrydgard** [comment]
Closing as duplicate.

**Comment by dananothername** [comment]
what about encoding issue 
it's  30 fps while the game is 50/60

**Comment by unknownbrackets** [comment]
Linked by mistake, reopening.

-[Unknown]

**Comment by Gamemulatorer** [comment]
> Duplicate #15617 

This is a dup ☝️

**Comment by unknownbrackets** [comment]
Derp, my bad.  Still linked by mistake, but not closed by mistake.

-[Unknown]
