### ISSUE TITLE
MotorStorm Arctic Edge texturing issue

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#16429]
Reported by Panderner on Discord:

Apparently there's some issue that can be worked-around by using "Lower resolution for effects". Not sure if it's new?

Lower resolution for effects to Balanced/Aggressive:

![image](https://user-images.githubusercontent.com/130929/203788170-3ad9200e-9f9a-4cbb-9414-027a2e97ca4c.png)

Lower resolution for effects to Off/Safe:

![image](https://user-images.githubusercontent.com/130929/203788216-f76fb2a9-45d9-41fe-843d-5343b7a15085.png)

Got a frame dump Panderner?

**Comment by Panderner** [comment]
> Got a frame dump Panderner?

Yes: 
[UCES01250.zip](https://github.com/hrydgard/ppsspp/files/10084706/UCES01250.zip)

**Comment by hrydgard** [comment]
Hm, running the frame dump, I get the same broken output in both cases. Though could be that the textures are assembled on some previous frame...

**Comment by Gamemulatorer** [comment]
I can also reproduce this even in software rendering.
[UCES01250.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/10085530/UCES01250.ppdmp.zip)

**Comment by hrydgard** [comment]
Huh. I can't seem to reproduce this at all, starting the game from scratch, using Vulkan.

Any particular level or mode I need to go into?

**Comment by hrydgard** [comment]
That said, forcing lower res for effects on for this game doesn't seem to have any ill effects, so we could just do it anyway...
