### ISSUE TITLE
Modified Game works on Desktop, Crashes on Android

### ISSUE THREAD

**Issue by GtaFreak95** [hrydgard/ppsspp#16473]
### Game or games this happens in

ULUS-10160 - GTA Vice City Stories

### What area of the game / PPSSPP

During initial loading screen (after intro FMV plays)

### What should happen

The game should load normally like it does on Desktop but on android it just hangs at 0-1% performance and does not move.

### Platform

Android

### Mobile phone model or graphics card

AYN Odin Pro

### PPSSPP version affected

1.13.2

### Last working version

works on desktop 1.13.2

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Does it work on the latest builds? https://buildbot.orphis.net/ppsspp/

**Comment by GtaFreak95** [comment]
so basically, i've modified Vice City Stories using the mod found here
https://gtaforums.com/topic/930285-lcsvcsrel-ps2-assets-for-psp/#comments

i've also added custom radio music which i've successfully converted over, increasing the overall file size of the .iso to 2.1gb in size

the modified iso loads/works on every and all recent windows builds of ppsspp but does not work on android

i've tried that build above and still hangs

**Comment by hrydgard** [comment]
Hm, if the ISO passed 2147483648 bytes in size, maybe it's somehow a 64-bit I/O issue...

**Comment by GtaFreak95** [comment]
i compressed the iso to a cso making the file size 1.6gb but it still hangs like this, so i'm not sure what else it could be.

**Comment by ANR2ME** [comment]
May be the mod uses a very large textures and there isn't enough memory? (since we've seen 10gb memory usage before on one of the issue)

**Comment by GtaFreak95** [comment]
i don't think the mod is using very large textures, afaik it's using map models/textures ported from the ps2 version of the game, which shouldn't be an issue as it does work on windows ppsspp

**Comment by hrydgard** [comment]
Texture sizes cannot possibly be the cause if it works on PC, since they still have to be small enough to work on the PSP, and Android devices have enough memory to emulate any regular PSP game.

Also doubt I/O timing. GtaFreak95, can you confirm if the unpacked size of your ISO is larger than 2147483648 bytes? If it is, what if you remove some stuff to make it fit under that limit? I do think some kind of integer overflow-related thing is more likely than the other proposed explanations.

**Comment by GtaFreak95** [comment]
2,059,413,504.00 bytes on disk is the full size of the iso, so it is under that threshold, the 2.1gb was a rounding up estimate i did.

**Comment by hrydgard** [comment]
Alright, then it simply isn't that. Then I'm out of ideas...

**Comment by GtaFreak95** [comment]
hey look, i don't know why this worked now, but i restored PPSSPP to default settings (must've been a badly configured .ini that wasn't replaced) and now the game is working perfectly. 

thanks for the help though much appreciated!
