### ISSUE TITLE
Strange code fragments

### ISSUE THREAD

**Issue by mjunix** [hrydgard/ppsspp#16490]
(I have no experience with this code base so these may not be actual bugs.)

1. Identical expressions on both sides of or-operator: https://github.com/hrydgard/ppsspp/blob/c9c4a7ef7dd05e51024392d150fe9bb74c85f01b/Core/HLE/scePsmf.cpp#L754
2. If `data_index_ == 0` in if-condition on line 568 then for-loop will not be executed on line 573 because loop counter `i` is initialized to zero so for-loop condition `i < data_index_` will be false: https://github.com/hrydgard/ppsspp/blob/c9c4a7ef7dd05e51024392d150fe9bb74c85f01b/GPU/Software/TransformUnit.cpp#L568-L573
3. if-condition is always false on line 1023 because `texHeight == 1` is always false as a result of the strictly-greater check `texHeight > 1` on line 1020: https://github.com/hrydgard/ppsspp/blob/c9c4a7ef7dd05e51024392d150fe9bb74c85f01b/GPU/Common/TextureCacheCommon.cpp#L1020-L1023
4. Potential index out of bounds? Wouldn't it be possible for `numCmdBufs` to have the value 2 here while the `cmdBufs` is of size 2 (meaning last valid index is 1)? https://github.com/hrydgard/ppsspp/blob/c9c4a7ef7dd05e51024392d150fe9bb74c85f01b/Common/GPU/Vulkan/VulkanFrameData.cpp#L158
5. Potential index out of bounds where `n` could reach value 2? https://github.com/hrydgard/ppsspp/blob/c9c4a7ef7dd05e51024392d150fe9bb74c85f01b/GPU/Vulkan/VulkanUtil.cpp#L174
6. Intentional assignment instead of comparison? https://github.com/hrydgard/ppsspp/blob/c9c4a7ef7dd05e51024392d150fe9bb74c85f01b/GPU/Directx9/StateMappingDX9.cpp#L102

**Comment by unknownbrackets** [comment]
I changed some of these in #16491, good catches.

For 2, I wrote that and just wasn't sure if I might want to allow data_index != 0, then decided to not tempt the uncommon case iirc.  I guess we could remove.

3, I think we should take off the == 1 check, but not certain if there was something else there.

-[Unknown]

**Comment by hrydgard** [comment]
Huh, I'll take a look at 3. Apparently the special case is not needed since things are working even if it can't get into the if.

Were these found with some static analyzer?

**Comment by hrydgard** [comment]
Ah, 3 became obsolete in a6d6e0a3cc . I'll just delete that special case check.
