### ISSUE TITLE
DarkStalkers / Vampire Chronicles : fell off the fast path again?

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#16510]
These are impossible to emulate using hardware so we force them to software rendering, where we have a fast path (rectangle optimization) that makes them playable even on very low-end.

When making changes to the software render it's easy to accidentally break the optimization though, which seems to have happened again: https://github.com/hrydgard/ppsspp/pull/16509#issuecomment-1339049118

Need to be looked into.

**Comment by Gamemulatorer** [comment]
Still even with
https://github.com/hrydgard/ppsspp/pull/16512
![Screenshot_20221207_072351_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37603562/206046919-5ae27c38-6fc1-4fd0-b8c5-045e5e8fdb38.jpg)

**Comment by hrydgard** [comment]
OK, I guess some case is still not hitting the fast path then. Will help look into it tomorrow.

**Comment by Gamemulatorer** [comment]
Now it's fast again. Thanks!
![Screenshot_20221207_104049_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37603562/206074731-4789265a-fc84-40eb-8109-339138a0129f.jpg)

**Comment by unknownbrackets** [comment]
Hm, the framedump didn't seem to enter or not enter that path, but glad it's faster again.  Probably some tweaks to the sampler are the best way to make this any faster.

What's the title screen like?  A framedump might be interesting.

-[Unknown]

**Comment by Gamemulatorer** [comment]
Yes title screen still slow.
![Screenshot_20221207_124359_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37603562/206090566-2ce59301-06ff-475b-8ffa-e404c03d16ae.jpg)
[ULJM05005.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/10172851/ULJM05005.ppdmp.zip)

**Comment by hrydgard** [comment]
That's the character selector, not the title screen (although it apparently is also slow for you?)

The title screen is the only scene I can find in the game that doesn't render like an old school sprite/tile machine that the game was presumably ported from.

![ULES00016_00006](https://user-images.githubusercontent.com/130929/206120103-daea1790-c5d6-4246-9f16-b43d5ccb7156.jpg)


[darkstalkers_title.zip](https://github.com/hrydgard/ppsspp/files/10173855/darkstalkers_title.zip)

**Comment by unknownbrackets** [comment]
Hm, the first draw should be a clear, maybe we could optimize it into an actual clear which might be faster.  It uses alpha test and blend pointlessly which we hopefully already optimize off.  The next draws ought to use the fastpath already, so main thing would be samplerjit for arm64.

I'd guess sampler is the main reason for the slowness now.  It's at least not swizzled, but it is using CLUT4.

-[Unknown]

**Comment by hrydgard** [comment]
Those could be nice to do, but also I think it'll be enough to just NEON-ify the SSE optimizations we have on the fastpath already since it is mostly hitting it, to get a pretty good boost (it's reasonably fast on PC). 

Also, just noting, in-game is just fine, so the urgency of this isn't super high, and not a regression.

**Comment by Gamemulatorer** [comment]
> That's the character selector, not the title screen (although it apparently is also slow for you?)
> 
> The title screen is the only scene I can find in the game that doesn't render like an old school sprite/tile machine that the game was presumably ported from.
> 
> ![ULES00016_00006](https://user-images.githubusercontent.com/130929/206120103-daea1790-c5d6-4246-9f16-b43d5ccb7156.jpg)
> 
> [darkstalkers_title.zip](https://github.com/hrydgard/ppsspp/files/10173855/darkstalkers_title.zip)

Sorry I'm wrong 😂
This is the title screen performance on my phone.
![Screenshot_20221207_161038_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37603562/206124311-c1e53677-20d1-471c-a22e-cad473dc3d8d.jpg)

**Comment by unknownbrackets** [comment]
> Those could be nice to do, but also I think it'll be enough to just NEON-ify the SSE optimizations we have on the fastpath already since it is mostly hitting it, to get a pretty good boost (it's reasonably fast on PC).

Fair, probably worth checking if clang is doing any already, because I've found recent versions to be not so terrible at vectorizing (but have continued to be unimpressed by MSVC... though haven't tried newer than 2019...)

Hm, the title screen looks pretty similar between the regions, but maybe worth comparing frame dumps.

-[Unknown]

**Comment by Gamemulatorer** [comment]
Europe region.
![Screenshot_20221207_180317_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37603562/206149954-5cbe09d3-4468-4a79-b09e-49aee2e3ddde.jpg)
![Screenshot_20221207_180347_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37603562/206149979-1d1568f0-9253-475e-8807-9ebb7f9b82ec.jpg)
![Screenshot_20221207_180359_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37603562/206150010-f24249f3-f608-4003-9e93-05b84d8a88e4.jpg)

**Comment by Gamemulatorer** [comment]
> Hm, the title screen looks pretty similar between the regions, but maybe worth comparing frame dumps.
> 
> -[Unknown]

Here's for japan region.
[ULJM05005.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/10174989/ULJM05005.ppdmp.zip)
