### ISSUE TITLE
【Win/Android】Tactics Ogre Text(Kanji) are not diplayed correctly 【Android】Goes down FPS

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#16534]
### Game or games this happens in

ULJM-05753 Tactics Ogre -Unmei no Wa-

### What area of the game

Probably, All scene.

### What happens

Windows10
Ryzen7 3700X
Nvidia Geforce RTX3060
RAM 32GB

Android12
Galaxys20 Snapdragon865 RAM12GB
*iso stay on external microSD

The Kanji are displayed correctly until v1.12.3-1084.
![Tactics Ogre_v1 12 3-1084_Good](https://user-images.githubusercontent.com/48179091/206808494-127585b4-ecae-4c44-82c9-09876b7bec3e.jpg)

The Kanji are not displayed correctly since v1.12.3-1087.
It's meaning "Kanji are Changed wrong kanji character."
![Tactics Ogre_v1 12 3-1087_NG](https://user-images.githubusercontent.com/48179091/206808502-255c2c09-d323-4260-a985-6f8639ab29a3.jpg)

Probably, Latest build will displayed more strange...
![image](https://user-images.githubusercontent.com/48179091/206809922-32350d76-7839-42c5-afb7-2bdcae5eed12.png)

And, Android goes down FPS on title.
Noticeable FPS drop on the title screen. 
Impossibly long load times.

### What should happen

The text should displayed right characters.

And, Performance will fix on Android.

### GE frame capture

[ULJM05753_0001.zip](https://github.com/hrydgard/ppsspp/files/10198660/ULJM05753_0001.zip)

### Platform

Windows / Android

### Mobile phone model or graphics card

Nvidia Geforce RTX3060 / Adreno650

### PPSSPP version affected

v1.12.3-1087

### Last working version

v1.12.3-1084

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Hm, this is the "fake mipmap" thing, I think, must have broken... Need to fix this regression.

**Comment by nassau-tk** [comment]
Oh....I checked about backend.
1. v1.12.3-1087 is displayed correctly on OpenGL.
2. v1.13.2-2079 is not displayed correctly on OpenGL.
???
This issue has more problem???

**Comment by hrydgard** [comment]
Thanks for your testing! I'll take a proper look tomorrow and hopefully fix it.

**Comment by hrydgard** [comment]
#16536 should take care of it.

As for the slowdown, it's probably the unnecessary readback the game does every frame, and you can get rid of it by enabling the "Disable GPU readbacks" speedhack option (previously, block transfer option).

I don't remember, did we figure out what the readback was for, or if we can just skip it?
