### ISSUE TITLE
(OpenGL 3.0+) AA-color shader rendering issue 

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#16549]
### Game or games this happens in

ULUS10466

### What area of the game

Noticable in dark stages see https://github.com/hrydgard/ppsspp/pull/4191#issuecomment-1345461164

### What happens

Graphics rendering issue using AA-Color shader on android with opengl backend.

### What should happen

No rendering issue like in vulkan backend.

### GE frame capture

[ULES01376.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/10202923/ULES01376.ppdmp.zip)
![Screenshot_20221212_023140_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37603562/206922036-04de970f-7f0e-4e3b-8269-7f128295e08e.jpg)

### Platform

Android

### Mobile phone model or graphics card

Vivo Y11 Android 11 Snapdragon 439 Adreno 505

### PPSSPP version affected

v1.13.2-recently build

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by Gamemulatorer** [comment]
I cannot reproduce this issue on my phone with mali 450 GPU 🤔

**Comment by LunaMoo** [comment]
Can't reproduce on desktop, but try this if you have some time:

````
// AA-Color shader, Modified to use in PPSSPP. Grabbed from:
// http://forums.ngemu.com/showthread.php?t=76098

// by guest(r) (guest.r@gmail.com)
// license: GNU-GPL

// Color variables

#ifdef GL_ES
precision mediump float;
precision mediump int;
#endif

const vec3 c_ch = vec3(1.0,1.0,1.0);  //  rgb color channel intensity
const float   a = 1.20 ;              //  saturation 
const float   b = 1.00 ;              //  brightness 
const float   c = 1.25 ;              //  contrast   

// you can use contrast1,contrast2...contrast4 (or contrast0 for speedup)

float contrast0(float x){
	return x;
}

float contrast1(float x){
	x = x*1.1547-1.0;
	return sign(x)*pow(abs(x),1.0/c)*0.86 +  0.86;
}

float contrast2(float x){
	return normalize(vec2(pow(x,c),pow(0.86,c))).x*1.72;
}

float contrast3(float x){
	return 1.73*pow(0.57735*x,c);
}

float contrast4(float x){
	return clamp(0.866 + c*(x-0.866),0.05, 1.73);
}

uniform sampler2D sampler0;

varying vec4 v_texcoord0;
varying vec4 v_texcoord1;
varying vec4 v_texcoord2;
varying vec4 v_texcoord3;
varying vec4 v_texcoord4;
varying vec4 v_texcoord5;
varying vec4 v_texcoord6;

void main()
{
	vec3 c10 = texture2D(sampler0, v_texcoord1.xy).xyz; 
	vec3 c01 = texture2D(sampler0, v_texcoord4.xy).xyz; 
	vec3 c11 = texture2D(sampler0, v_texcoord0.xy).xyz; 
	vec3 c21 = texture2D(sampler0, v_texcoord5.xy).xyz; 
	vec3 c12 = texture2D(sampler0, v_texcoord2.xy).xyz; 

	vec3 dt = vec3(1.0,1.0,1.0);
	float k1=dot(abs(c01-c21),dt);
	float k2=dot(abs(c10-c12),dt);

	vec3 color;
	if (k1 != 0.0 || k2 !=0.0) {
		color = (k1*(c10+c12)+k2*(c01+c21))/(2.0*(k1+k2));
	} else {
		color = c11;
	}

	float x = sqrt(dot(color,color));

	if (color.r > 0.0) color.r = pow(color.r,a);
	if (color.g > 0.0) color.g = pow(color.g,a);
	if (color.b > 0.0) color.b = pow(color.b,a);

	gl_FragColor.rgb = contrast4(x)*normalize(color*c_ch)*b;
	gl_FragColor.a = 1.0;
}

````

Untested, but this just replaces adding tiny values with actual checks to avoid undefined results.
