### ISSUE TITLE
Manual MAC-address selection

### ISSUE THREAD

**Issue by LentCrown** [hrydgard/ppsspp#16546]
### What should happen

It would be cool if you would had option to manually enter MAC-address.

Recently, i wanted to play SOCOM Fireteam Bravo 2, but it doesn't wanted to load save from my actual PSP memory stick, because "it was from other PSP system".
![image](https://user-images.githubusercontent.com/48063871/206910242-48099ef9-9e11-421d-91fb-07f4d14c23d0.png)

Some 14 year topic on some psp site told that probably that save contains PSP MAC-address too. (https://gamefaqs.gamespot.com/boards/932644-socom-us-navy-seals-fireteam-bravo-2/40863546)

I checked latest auto-build (https://buildbot.orphis.net/ppsspp/). It only contains warning about MAC-address generation, but there are still no manual input option,

### Who would this benefit

All users which will have same problem as i had - savedata which contains MAC-address will normally load in emulator.

### Platform (if relevant)

None

### Games this would be useful in

UCUS98645 - SOCOM: U.S. Navy SEALs Fireteam Bravo 2

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
If you can figure out the needed MAC address, you can manually enter it in memstick/PSP/SYSTEM/ppsspp.ini already.

But you're right that we should have UI for this.

**Comment by Linblow** [comment]
@LentCrown I made a patched ISO for `SOCOM FTB 1/2 US` which, among other things, allows you to load savedata from any device (i.e bypass MAC check). Consequently, it lets you load your PSP savedata, and whenever you save your profile, it will "resign" it to whatever MAC address your PPSSPP config file is set to. In other words, you can use that patched ISO to resign your savedata, then use the original ISO just fine, or keep using the patched one. Join the SOCOMPSP discord, and I'll send you the link there.

**Comment by hrydgard** [comment]
This is now possible on platforms that allow text input, which is most of them.
