### ISSUE TITLE
Some dependencies are getting really outdated

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#16559]
Will try to upgrade these after the 1.14 release process is done. Especially glslang, an IHV commented that the SPIR-V we're generating has some minor, well not quite issues, but things that there are better ways of doing.

Checklist:

- [x] glslang
- [x] SPIRV-cross
- [x] Vulkan headers (well, not so outdated, just good to keep up)

There are also others that we might consider upgrading, though hardly critical:

* libpng
* zlib
* libzip
* miniupnp

**Comment by unknownbrackets** [comment]
I suppose I last updated some of these last year, forever in the world of bits and bytes.  Probably not hard to update again, maybe worth looking at libzstd or xxhash.

-[Unknown]

**Comment by hrydgard** [comment]
Yeah I didn't mean to say those were really outdated, just that I spotted them when looking through the project, and to remind myself to go look at which ones actually do need updating. I think they're much lower priority anyway than glslang/SPIRV-Cross.
