### ISSUE TITLE
Postshader parameter default values not quite working

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#16562]
I added two new parameters to the Vignette shader but if I now add the Vignette shader on a device that already had an ini, the two parameters, which have very non-zero default values, still default to 0.0 for some reason. Needs fixing because that's not always a working value.

Will fix tomorrow.

**Comment by Gamemulatorer** [comment]
Might take a look also https://github.com/hrydgard/ppsspp/issues/16549
