### ISSUE TITLE
When I go to the "autoconfigure" option it does nothing (GameSir X3 Type-C)

### ISSUE THREAD

**Issue by MiguelCardonaG** [hrydgard/ppsspp#16582]
### What should happen

I enter the emulator settings, I go to the controls section, within that section there is one that says "autoconfigure" when pressed the emulator does not put the buttons of my controller (GameSir X3 Type-C) automatically. I have to do it manually.

![Screenshot_20221214-185420_PPSSPP](https://user-images.githubusercontent.com/65356692/207670668-a252bfc8-0afc-4db0-97da-4626e61c69f4.jpg)

### Who would this benefit

Everyone who has this bluetooth controller.

### Platform (if relevant)

Android

### Games this would be useful in

Controls

### Other emulators or software with a similar feature

Aethersx2, It sets the buttons on your Bluetooth remote automatically.

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by Panderner** [comment]
Using auto configure on DualSense controller gets the mapping wrong for examples square and triangle buttons are swapped (Pressing square button registers triangle and Triangle button registers square) and L and R buttons uses L2 and R2 triggers.
