### ISSUE TITLE
Impossible jump 

### ISSUE THREAD

**Issue by Heyimfranco** [hrydgard/ppsspp#16581]
### Game or games this happens in

UCES01401 God Of War Ghost Of Sparta

### What area of the game / PPSSPP

Temple of Thanatos

### What should happen

Kratos has to jump off the chains and hold on to the large block of stone, but falls for no reason... 

### Logs

https://user-images.githubusercontent.com/120583748/207652166-2e5eed8c-0dc9-447c-870f-a53748381817.mp4

### Platform

Android

### Mobile phone model or graphics card

SM-G610M 

### PPSSPP version affected

1.13.2

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by Gamemulatorer** [comment]
So the old bug is back https://github.com/hrydgard/ppsspp/issues/7411?
Can you try the recently build PPSSPP from automated PPSSPP buildbot?

**Comment by Heyimfranco** [comment]
> What is that? I'm new here

**Comment by Heyimfranco** [comment]
> 

What's that? I'm new here

**Comment by hrydgard** [comment]
https://buildbot.orphis.net/ppsspp/

**Comment by Heyimfranco** [comment]
> So the old bug is back #7411? Can you try the recently build PPSSPP from automated PPSSPP buildbot?

Install the latest version for Android, no changes, do I have to do something with this version?

**Comment by LunaMoo** [comment]
I can only test the savedata from #7411 which is from similar jump in a different spot and it works fine with default settings.
@Heyimfranco if you're using any non default settings(especially different CPU clock) please restore default settings abandon your savestates and reload from normal in-game savedata, as long as it's same problem affecting different place that should help.

**Comment by Heyimfranco** [comment]
> I can only test the savedata from #7411 which is from similar jump in a different spot and it works fine with default settings. @Heyimfranco if you're using any non default settings(especially different CPU clock) please restore default settings abandon your savestates and reload from normal in-game savedata, as long as it's same problem affecting different place that should help.

I fixed the bug, using cpu clock, I put that at 1000 and Kratos grabbed the block

**Comment by LunaMoo** [comment]
Looking at your video low framerate I suspect you did used non-default cpu clock to begin with causing the problem. That option should really not be touched for GOW, but unfortunately there are a lot of youtubers and other self proclaimed experts that know better bombarding people to use it.

**Comment by Gamemulatorer** [comment]
This issue must belong to https://github.com/hrydgard/ppsspp/issues/12811

**Comment by unknownbrackets** [comment]
Alright, if this is a problem of using hack settings, I'll close it as not an actual bug.  We already have #12811.

-[Unknown]
