### ISSUE TITLE
can't enter the emulator's menu with vulkan render selected

### ISSUE THREAD

**Issue by yasabaka** [hrydgard/ppsspp#16588]
### Game or games this happens in

yes

### What area of the game / PPSSPP

with opengl i can do this, but not with vulkan

### What should happen

yes

### Platform

Android

### Mobile phone model or graphics card

xiaomi redmi note 4

### PPSSPP version affected

1.14 ppsspp website 

### Last working version

1.13.2

### Graphics backend (3D API)

Vulkan

### Checklist

- [x] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by yasabaka** [comment]
installed 1.14 from website and tried to change the graphics backend from opengl to vulkan but then it's just shows black screen on launch

**Comment by Gamemulatorer** [comment]
Try deleting ppsspp.ini inside psp>system folder.

**Comment by hrydgard** [comment]
Hm that is really not good... Can you try a few versions in between from https://buildbot.orphis.net/ppsspp/index.php?m=fulllist and see how long ago it broke?

**Comment by yasabaka** [comment]
> Hm that is really not good... Can you try a few versions in between from https://buildbot.orphis.net/ppsspp/index.php?m=fulllist and see how long ago it broke?

v1.13.2-1697-g109db81ec last working version. next one doesn't work (1703)

**Comment by hrydgard** [comment]
That makes it seem like it's this one, then: https://github.com/hrydgard/ppsspp/pull/16291

Haven't had any other report that it would break stuff, so that's a bit surprising. I have been thinking of reverting it though since I didn't have as much use for that restructuring as I first thought..

Let's do some googling, Xiaomi Redmi Note 4, that's from Januar 2017, and with an Adreno 506, and one of the first generation of phones to support Vulkan as it's on Android 7. There were some really iffy Vulkan drivers in that generation. But of course, I do try to keep things working as much as possible..

Anyway, thanks for reporting. I think I'll just revert that change tomorrow, which hopefully should fix it, and do a 14.1 early next week. Though, a bit of a shame if we can't make use of multiple descriptor sets, I have other ideas about uses for it.

**Comment by hrydgard** [comment]
Does Vulkan provide much benefit on your device by the way? I've been thinking about just locking it out from devices with Android 7 or older since generally the implementations weren't very good.

Or have you installed some newer OS on your device than Android 7?

**Comment by Gamemulatorer** [comment]
@yasabaka does your Redmi note 4 using custom rom?

**Comment by Gamemulatorer** [comment]
> Does Vulkan provide much benefit on your device by the way? I've been thinking about just locking it out from devices with Android 7 or older since generally the implementations weren't very good.

Yes I agree increase to android 8.0 (oreo) that can use vulkan.

**Comment by hrydgard** [comment]
@yasabaka when you choose Vulkan and get a black screen, and then restart the emulator, does it start working in Vulkan after that, or reverts to OpenGL, or does it stay black and you have to delete the ini to continue? Which one is it?

**Comment by yasabaka** [comment]
> @yasabaka when you choose Vulkan and get a black screen, and then restart the emulator, does it start working in Vulkan after that, or reverts to OpenGL, or does it stay black and you have to delete the ini to continue? Which one is it?

i have to delete it to continue

**Comment by hrydgard** [comment]
Oops, didn't mean to autoclose as it's not confirmed.

But hopefully, builds after the merge of #16599 will work again, please test.

**Comment by hrydgard** [comment]
Thanks for testing!

Gonna need more info to figure out the performance drop. How big is it? Does it affect all games you are playing? Did it get slower than OpenGL? Did it slow down before or after the commit that broke it before?

**Comment by Gamemulatorer** [comment]
Yes I also notice that in v1.14 there's a performance drop like https://github.com/hrydgard/ppsspp/issues/16537#issuecomment-1345875393
Also Tekken 6 and any other 3D games.

**Comment by yasabaka** [comment]
> Thanks for testing!
> 
> Gonna need more info to figure out the performance drop. How big is it? Does it affect all games you are playing? Did it get slower than OpenGL? Did it slow down before or after the commit that broke it before?

i tried to make a video, but somehow vulkan backed worked better this time, and for some reason opengl showed me 10 fps
https://youtu.be/Rjxfz45maZ8

**Comment by hrydgard** [comment]
Ok. Yeah a tricky thing with Android is that perf can be very variable, depending on battery level, temperature, background apps and probably the phase of the moon :p

**Comment by Gamemulatorer** [comment]
This can be close now since the original issue is finally fixed.
