### ISSUE TITLE
How to use old style pasue background?

### ISSUE THREAD

**Issue by leoxxx** [hrydgard/ppsspp#16593]
### Game or games this happens in

ALL

### What area of the game / PPSSPP

I want to use old style pasue background. Now the pause  background is transparent.
![2022-12-16_124852](https://user-images.githubusercontent.com/5364709/208025768-ba50aeb4-ceae-410b-a83b-8b5890488caa.png)

### What should happen

As the picture shown. Like this.
![2022-12-16_124708](https://user-images.githubusercontent.com/5364709/208025855-9e82a3f7-1f8d-4fc6-9144-cf4980ad416d.png)
![2022-12-10_224856](https://user-images.githubusercontent.com/5364709/208027538-b0e24984-9861-4b01-a496-81358a59be0c.png)

### Platform

Windows

### Mobile phone model or graphics card

7850 1G

### PPSSPP version affected

1.14

### Last working version

1.13.2

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [ ] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Hm, yeah, I guess not everyone likes the game showing through, although personally I much prefer it...

I'll make it an option.
