### ISSUE TITLE
NFSMW 5-1-0 crashes

### ISSUE THREAD

**Issue by Heyimfranco** [hrydgard/ppsspp#16591]
### Game or games this happens in

ULES00196 Need For Speed Most Wanted 5-1-0

### What area of the game / PPSSPP

[ULES00196001.zip](https://github.com/hrydgard/ppsspp/files/10241622/ULES00196001.zip)
In the last blacklist available, I do not know if in the other blacklist the game crashes

### What should happen

It shouldn't crash

### Logs

![Screenshot_20221215-205733_Device maintenance](https://user-images.githubusercontent.com/120583748/207993185-7e7b411c-f839-4e0d-a8e3-c14a6debfd21.jpg)

https://user-images.githubusercontent.com/120583748/207993203-243e6f7d-1a8e-4d21-b136-d50e5534c575.mp4

The screenshot is to show all crashes by the game 

### Platform

Android

### Mobile phone model or graphics card

SM-G610M 

### PPSSPP version affected

1.14

### Last working version

1.13.2

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by Gamemulatorer** [comment]
Can you narrow down which build this issue started https://buildbot.orphis.net/ppsspp/index.php?m=fulllist

**Comment by hrydgard** [comment]
Also, is this only with Vulkan or also with GL? Does it happen on any particular tracks?

**Comment by Heyimfranco** [comment]
> Also, is this only with Vulkan or also with GL? Does it happen on any particular tracks?

I was playing for 25 minutes with GL, and it seems that the game does not have problems with that, the game doesn't crash, but I will continue to use GL with NFSMW, if the game crashes many times I will say it

**Comment by Gamemulatorer** [comment]
> > Also, is this only with Vulkan or also with GL? Does it happen on any particular tracks?
> 
> I was playing for 25 minutes with GL, and it seems that the game does not have problems with that, the game doesn't crash, but I will continue to use GL with NFSMW, if the game crashes many times I will say it

Remember to use default settings without cheats code when you testing this.

**Comment by Gamemulatorer** [comment]
@Heyimfranco no feedback/outdated?

**Comment by Heyimfranco** [comment]
> @Heyimfranco no feedback/outdated?

Ah, sorry for not responding, I use the default settings and the game works with opengl and I don't use hacks with the game

**Comment by Gamemulatorer** [comment]
So no more crashing?

**Comment by Heyimfranco** [comment]
> So no more crashing?

I formatted my phone and I'm not having crashes with the game these days

**Comment by unknownbrackets** [comment]
Hm, it's possible this was a bug we fixed or maybe a driver problem.  If you're not experiencing crashes anymore, that's great.

-[Unknown]

**Comment by Gamemulatorer** [comment]
This should safe to close then?
