### ISSUE TITLE
Creating game configs on iOS seems to cause crashes

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#16607]
Don't really have any theory about why this happens, but seems likely to be related to some file permission issue and us not handling errors well somewhere. It's been reported by multiple people.

**Comment by kquayle19** [comment]
Just confirming this is still causing issues. The app is crashing immediately when trying to launch any game with a saved game config. Deleting the game config solves the issue.

**Comment by hrydgard** [comment]
Still getting reports of this. Indeed likely JIT-related..

**Comment by hrydgard** [comment]
This should be fixed now with #16925, thanks unknown. Let's see if we get any more reports, otherwise I'll close this soon.

**Comment by unknownbrackets** [comment]
I'm going to close this for now, since I haven't seen people noting anything.  We'll reopen if there are further reports.

-[Unknown]
