### ISSUE TITLE
Google Play unusual permissions warning - consider or ignore?

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#16637]
In the Google Play console, it shows this warning:

```
Anomalous Permission Usage
Your app is requesting permissions which are used by less than 1% of functionally similar apps:

android.permission.ACCESS_FINE_LOCATION
android.permission.CAMERA
android.permission.RECORD_AUDIO
Users prefer apps that request fewer permissions and requesting unnecessary permissions can affect your app's visibility on the Play Store. If these permissions aren't necessary, you may be able to use alternative methods in your app and request fewer permissions. If they are, we recommend providing an explanation to users of why you need the permissions.

Note: This guidance is based on a comparison with functionally similar apps, which change over time as new apps get published and existing apps change behavior. Therefore the warning may change even if you don't change your permission usage.
```

Well, of course we can't get rid of camera and record-audio if we want to support the games that make use of those features, but maybe COARSE_LOCATION would be enough for the barely tested GPS emulation (or we get rid of it, like, there's practically no use for it). And on newer devices we can request the permission at runtime instead (as far as I know these on-install permission requests no longer work anyway?)

Though on the other hand, I don't know if we need to consider this warning much anyway. Downloads are stable and not going down.

**Comment by ANR2ME** [comment]
Yeah, might be better to request at runtime when the game is using it or enabled by the user.

**Comment by unknownbrackets** [comment]
As a user, I feel like scoped storage restrictions were invented to punish me for caring about privacy.  In comparison, runtime requests for camera/recording/gps feel like they were actually designed to make me happy.

In theory, we might be able to detect that a game imports the camera or gps modules, and request the permission before actually starting the game.  Not sure if there would be any false positives with that approach.

I think the GPS thing is only really used by some GPS app that existed for the PSP?  It's also been reported with UCJS10041_1.00, which typically means some homebrew.  Not sure it's actually useful indeed...

-[Unknown]

**Comment by Florin9doi** [comment]
These permissions are already requested at runtime and only when they are actively used by any application

**Comment by unknownbrackets** [comment]
Ah, you're right, and we're already using https://developer.android.com/guide/topics/manifest/uses-permission-sdk-23-element.  Not sure what else we'd do then.

-[Unknown]

**Comment by ANR2ME** [comment]
As i remembered there is another way to request permission using java code, since permissions on manifest file might be detected as too many by google play.

**Comment by hrydgard** [comment]
I think we'll just keep doing what we're doing then.

**Comment by ANR2ME** [comment]
We probably just need to explain why we need those permissions on some games (ie. mentioning at least one game that needed those permission) on the description at play store, so people would feel at ease when installing PPSSPP on their devices.
