### ISSUE TITLE
Analog stick stuck - MFHU - multiinstance - x360

### ISSUE THREAD

**Issue by Dschogo** [hrydgard/ppsspp#16643]
### Game or games this happens in

ULES01213 - Monster Hunter Freedom Unite (EUR)

### What area of the game / PPSSPP

When multiple instances are open in-game (2-4 tested), sometimes the right analogstick (which is bound to the d-pad to look around) gets stuck. It only happens if multiple instances are active. Flicking the stick/d-pad in the same direction again stops it. - I assume the mapped "key up" event gets "lost" somewhere? PPSSPP gets confused with the multiple-nearly parallel controller inputs, since it only happens if other player are actively playing/fighting

(controllers working fine in other non PPSSPP games like Movin out, emulated switch via yuzu, gampad-tester.com also shows no "stuck" xinput)

The four instances of PPSSPP are seperate portable installs, for individual saves.
Controlmappings are completly cleared except for the specific controller in each instance. (x360_something in the first, x360_1_somthing in second, etc)
Analog-Stick calibration doesn't help.

Emulation settings are default - except Adhoc to local and PostFX (Natural Color).

Additionally, is there a start parameter or setting to disable auto-muting other instances? I get the Idea but in MHFU its possible to disable the background music and we like the FX from every player. RN i made an ahk script with quickly pushes the volume to 10 after an instance gets booted.

### What should happen

Stick/cam shouldnt "stick"/ cam should stop spinning.

### Logs

Since it's no crash - don't think there is value - i'll still attach one in the following days

### Platform

Windows

### Mobile phone model or graphics card

win10 (22h2) - GTX1060 (517.56) - ryzen 1700 - 4 x360 controller

### PPSSPP version affected

1.14.1 (2d1f8f0)

### Last working version

none - issue already persisted in 1.7 (tested the custom adhoc build)

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [x] Include logs or screenshots of issue.

**Comment by Dschogo** [comment]
Example video of three instances:

- Controller 1 and 2 right analog stick random movement (by me for simulating ingame camera movement)
- Instance 3 gets stuck at second ~3 even seen on the right - there is no input
- On the right is the gamepad tester website for every controller

https://user-images.githubusercontent.com/36862419/209171158-06f52359-6219-44d8-a84d-d1c2840d327d.mp4

A log (not the one from the video - issue occured in the last ~7 seconds before shutdown):
[https://raw.githubusercontent.com/Dschogo/Dschogo/main/ppsspplog.txt](https://raw.githubusercontent.com/Dschogo/Dschogo/main/ppsspplog.txt)

(bigger than 25mb (28) so had to do it like that - prob so big because i had to enter the game and every load is captured)

**Comment by Dschogo** [comment]
A bit of new information:

- it also happens when the left analog stick is bound to the d-pad (in both instances) 
- To reproduce: its enough to flick the stick at the same time once (on both controllers, direction doesnt matter - the "end" of the flick seems to be the issue (when it centers back)

**Comment by Dschogo** [comment]
Hey there, 

tested the current nightly (v1.16.6-760-geabcd5d8a | 2023-12-31 09:55:36) and seems to work now.
I've seen in the merge #18407 , it could still happen, tried to break it for 15mins, wasn't able to stick any analog->digital "key".(Previously usually after 1 min) 

If you need it as a reminder, for hardening the conversion with explicit Key evaluation, feel free to reopen :D

Thanks for the work :heart:

**Comment by hrydgard** [comment]
Thanks for testing! Yeah, it might have been fixed by a change I did a while ago to solve a different issue.
