### ISSUE TITLE
The warriors: cheat/plugin request

### ISSUE THREAD

**Issue by Nugss** [hrydgard/ppsspp#16650]
### What should happen

Hello, I just want to request a cheat or plugin for this game. A cheat/plugin that turn this game just like PS2. Because on PSP version they decrease a lot of stuff just like the number of peds and weapons.

Cheat request:
*Max to 5v5 on war-party.
*Max to 9v9 on army-ing, and battle royal.
*Also, to play the unplayable characters and rumble maps.

I really love this game. I'd try to extract and modify the scripts of this game but sadly it crushed :(.

### Who would this benefit

Other gamers who play this game

### Platform (if relevant)

None

### Games this would be useful in

ULUS10213 - The warriors

### Other emulators or software with a similar feature

The PS2 version of this game

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by unknownbrackets** [comment]
You've opened this in the wrong GitHub.

PPSSPP is not a project where a bunch of people rewrite games from scratch, port them from one platform to another, or create exciting game hacks for that.  There are projects for that, and they're usually game-specific.  The amount of work that goes into hacking an individual game is often significant - there are well over one thousand PSP games.

Instead, PPSSPP is a project to emulate the PSP and its firmware and execute games as they were.  Of course, where possible we make it possible to enhance them - better graphics, texture replacements, cheat support, etc.  However, even the creation of a texture pack isn't really part of this GitHub - just the capability to.

It's feasible to use PPSSPP's debugging capabilities, cheats, plugins, etc. to accomplish this, at least in theory.

For game customization, a good place to look is romhacking.net.  You can also discuss it on PPSSPP's forum or Discord.  It's just not really a bug or a feature.

Also a warning: most game hacking communities react poorly to someone asking, "please spend hundreds of hours of your life making this thing I just decided I wanted, and please give it to me for free when you're done, kthx."  Usually the best reaction is when you ask for technical help but show that you're willing to invest the hundred hours for the idea you're passionate about - sometimes you'll even find others who love the same game, and will put hundreds of hours in for free too.  But that's almost always a reaction to seeing your passion and drive.

Anyway, this isn't a PPSSPP issue, so I'm closing it.

-[Unknown]

**Comment by Nugss** [comment]
Thanks for letting me know
