### ISSUE TITLE
More line drawing issues

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#16653]
In the homebrew app "Webfest" (a clone of Tempest) available in the PPSSPP Homebrew Store, line drawing has multiple bugs:

 - [x] In the hardware renderer, the lines going "into" the screen are simply missing (fixed in #16656)
 - [ ] In the software renderer, these lines get culled too early during the level transition

There might be more, not sure yet.

**Comment by unknownbrackets** [comment]
Hm, where can I see the culled lines?  The first three levels didn't look obviously bad, although I see some lines after beating the enemies that looked a bit questionable - as if they should've been culled and weren't.

The logo looks terrible, but it seems like this is probably not a problem of culling and more of line drawing?

How it should look:
![#16653_Webfest_bad_lines](https://user-images.githubusercontent.com/191233/210273709-5e98df0f-1ff1-4bf8-906f-1e2c1bd74e9d.png)

How it looks in software:
![#16653_Webfest_bad_lines_software](https://user-images.githubusercontent.com/191233/210273719-cee345d3-4c11-4c33-a288-a5fb27004ec9.png)

How it looks in Vulkan:
![#16653_Webfest_bad_lines_vulkan](https://user-images.githubusercontent.com/191233/210273742-927ffcfa-396d-4f2a-8404-ea813aead9b0.png)

Well... it tried.  These are indeed transformed lines (even for text) and end up with subpixel offsets.  Likely some things not exactly right there.

-[Unknown]

**Comment by hrydgard** [comment]
You can find the culled lines during the transition from one level to the next, when the camera zooms past the scene and into the next one, the "inwards" lines get culled in software (and somewhat flickery in Vulkan, strangely).

The Vulkan lines indeed don't look amazing at 1x, but now with centering enabled, they look good at 2x and really nice at 3x and above in the game, so that's something at least. MSAA can help too.

Possibly should turn off centering at 1x, non-MSAA.

**Comment by unknownbrackets** [comment]
Ah okay, will look again.

Vulkan is still off even with centered lines forced off:
![#16653_Webfest_bad_lines_vulkan](https://user-images.githubusercontent.com/191233/210280100-802fc897-cfcf-4935-b87e-9169bd800d88.png)

Not critical or anything, just noting for later.

-[Unknown]

**Comment by unknownbrackets** [comment]
As far as the stage exit lines, I think it's actually a bug in the homebrew that software rendering is finally simulating accurately.

Here's a frame dump:
[#16653_Webfest_line_end_stage.zip](https://github.com/hrydgard/ppsspp/files/10367751/16653_Webfest_line_end_stage.zip)

This is how the frame dump shows on a PSP:
![#16653_Webfest_line_end_stage](https://user-images.githubusercontent.com/191233/211181173-84f915de-df44-4f79-92ee-a1010e0558b8.png)

And here's how it shows in Vulkan:
![#16653_Webfest_line_end_stage_vulkan](https://user-images.githubusercontent.com/191233/211181190-4aa078fa-525a-4270-a60b-668ab218d2e8.png)

Here's a gif that shows actual, software, and Vulkan in a loop so one can see software is still a bit inaccurate but mostly right:
![#16653_Webfest_line_end_stage](https://user-images.githubusercontent.com/191233/211181276-fb54c920-ad37-43b2-8b72-9b144eae0a25.gif)

Of course, it looks better without the culling...

-[Unknown]

**Comment by hrydgard** [comment]
Okay, I guess I'll just close this then.

I don't think it's worth trying to emulate that culling in the hardware renderers, since it looks better the way it is - unless we find a game it somehow breaks.
