### ISSUE TITLE
Broken menus after using Break on Load 

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#16674]
This only happens in D3D11.

To repro, just enable Debug/Break On Load on Windows and start some game.

The pause menu gets broken, as if we don't rebind some state properly.

![image](https://user-images.githubusercontent.com/130929/210094078-f42c59a6-adc5-45b2-a0d8-73749c7f2675.png)

**Comment by Nemoumbra** [comment]
I didn't see anything in the version which goes by the commit 4a967966ef6f09b4d1e9fb3c74c06d919d7f08fd, if this helps.
That's ~ the middle of October.

**Comment by unknownbrackets** [comment]
Introduced by 63cbd9c79bb8, so definitely some state.  `thin3d->InvalidateCachedState();` makes it work but maybe I can find what's getting set the wrong way...

-[Unknown]
