### ISSUE TITLE
Sometimes character have map error in Street Fighter Zero 3 Double Upper

### ISSUE THREAD

**Issue by leoxxx** [hrydgard/ppsspp#16679]
### Game or games this happens in

ULJM05082 Street Fighter Zero 3 Double Upper

### What area of the game / PPSSPP

Sometimes character have map error. As shown in the picture.
![11](https://user-images.githubusercontent.com/5364709/210122707-f7c4be8b-4f25-438a-a9de-8a5fc03a7fd2.gif)

### What should happen

No map error.

### Platform

Windows

### Mobile phone model or graphics card

7850 1G

### PPSSPP version affected

v 1.14.2

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
Is this with vertex cache, lazy texture caching, and all other speedhacks off?  Frameskip off as well?

If it happens even with those off, does it happen in the software renderer?  Or does it only happen in D3D11 and not Vulkan/etc.?

-[Unknown]

**Comment by leoxxx** [comment]
Off "lazy texture caching", no map error. Then should I close the issue?

**Comment by unknownbrackets** [comment]
Unfortunately yes.  It's a natural effect of lazily checking for texture changes.  Open to ideas to make it catch changes better, but it already tries to be pretty smart about it.  The only way to be safe every time is to check every time.

-[Unknown]
