### ISSUE TITLE
Toca race driver 2 and toca race driver 3 challenge speed issues

### ISSUE THREAD

**Issue by Roman56rus** [hrydgard/ppsspp#16713]
### Game or games this happens in

ULES-00040,ULES-00613

### What area of the game

This games used to run much better on previous versions on Adreno 610(Redmi 9T),it was 4x resolution with 40/40 frames and full speed. Now(in 1.14.X) i can't get full speed and decent framerste using any settings 

### Speed seen in PPSSPP

35%(15/40)

### Platform

Android

### Mobile phone model or graphics card

Redmi 9T

### PPSSPP version affected

1.14

### Last working version

1.12

### Graphics backend (3D API)

OpenGL / GLES

### Any other notes or things you've tried

In vulkan and opengl it runs nearly the same

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the slowdown.
- [ ] Include logs or screenshots of issue.

**Comment by Gamemulatorer** [comment]
Just enable skip gpu readbacks in speedhack settings

**Comment by hrydgard** [comment]
I'm considering getting rid of the readbacks in these games with [BlockTransferAllowCreateFB] in compat.ini, but I'm not sure if anything breaks by doing that.

Are all the graphics there properly with readbacks disabled?

**Comment by Roman56rus** [comment]
> Are all the graphics there properly with readbacks disabled?
Yes,it renders properly both with enabled and disabled "Skip GPU readbacks". I think it was enabled by default in previous versions,but not in 1.14. Thanks for reply!

**Comment by hrydgard** [comment]
OK then it should be safe to set that compatibility option. I'm gonna set it by default once the 1.14 release process is done, and then close this again.

**Comment by Gamemulatorer** [comment]
> I'm considering getting rid of the readbacks in these games with [BlockTransferAllowCreateFB] in compat.ini, but I'm not sure if anything breaks by doing that.
> 
> Are all the graphics there properly with readbacks disabled?

On my short testing yes no graphics issue.
