### ISSUE TITLE
Narikiri Dungeon X - performance problem with battle transition

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#16714]
Mikio reported this through e-mail, with good info.

> Tales of Phantasia: Narikiri Dungeon X lags when using overbrave while the "Simulate block transfer effects" is turned on.
It lags but when I swipe the screen of my phone the lag stops. I'm using redmi note 10 pro which is more than enough to run the game.

> I need to turn on Simulate block transfer effects because the battle transition becomes glitchy when it is turned off.

The game is thus very likely doing readbacks during these battle transitions, which often cause devices to downclock, touching the screen can work around that.
![ULJS00293_1 01_4](https://user-images.githubusercontent.com/130929/210392782-16c72841-8c5e-4eae-a1b0-9094054b2523.jpg)

https://user-images.githubusercontent.com/130929/210392835-c737b5cb-a603-49a9-888a-210abea0df65.mp4

https://user-images.githubusercontent.com/130929/210393010-f0cf1bed-cc73-4678-a908-352c0e6afc3b.mp4

savestate:

[ULJS00293_1.01_4.zip](https://github.com/hrydgard/ppsspp/files/10337962/ULJS00293_1.01_4.zip)

We might be able to get rid of the readbacks using [BlockTransferAllowCreateFB] or similar tricks, needs to be looked into.

**Comment by Noneplayingplayer** [comment]
What time this will done?

**Comment by hrydgard** [comment]
@Noneplayingplayer Can you try this, if you are on a Windows machine:

Under the section `[BlockTransferAllowCreateFB]` in assets/compat.ini, add the following lines:

```
# Narikiri Dungeon X
ULJS00293 = true
```

Alternatively (say if you're on Android), put the following in a new text file named compat.ini which you put in your PSP/SYSTEM directory:

```
[BlockTransferAllowCreateFB]
# Narikiri Dungeon X
ULJS00293 = true
```

Does that help?
