### ISSUE TITLE
Killzone - Liberation: crash after initial cinematic

### ISSUE THREAD

**Issue by MarcoEstevez** [hrydgard/ppsspp#16727]
### Game or games this happens in

UCES00279 v1.00 (Killzone - Liberation)

### What area of the game / PPSSPP

Before starting a new game, if you wait for the initial fmv to end without skipping it (cause you can skip it, and in such case you can workaround the issue) the game crashes and PPSSPP shows blue crash info window.

![image](https://user-images.githubusercontent.com/3447089/210654788-99ff391c-180b-404c-b02e-23d3dd073152.png)

### What should happen

Video should end normally and show the main menu screen

![image](https://user-images.githubusercontent.com/3447089/210655034-85cb1cf1-d98b-49de-8bc7-491b91039a92.png)

### Logs

[ppsspplog.txt](https://github.com/hrydgard/ppsspp/files/10347710/ppsspplog.txt)

### Platform

Windows

### Mobile phone model or graphics card

NVIDIA GeForce RTX 2060

### PPSSPP version affected

1.14.4

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment]
Looks like this issue also happened on PPSSPP v1.3.2 might be an old issue nobody noticed before?
![image](https://user-images.githubusercontent.com/7974720/210681024-d44620b9-4396-459e-a575-93e89ed94b66.png)
![image](https://user-images.githubusercontent.com/7974720/210681051-a7105a63-44c9-43f3-a97a-a3846fc2a543.png)

**Comment by Gamemulatorer** [comment]
![Screenshot_20230105_102449_74c288e31530b9e5d0ca749a600f3e41](https://user-images.githubusercontent.com/37603562/210688519-265ceb04-fe22-4907-abb5-586bd30de281.jpg)
Can also reproduce this on my vivo phone also tried MpegAvcWarmUp doesn't help.

**Comment by Panderner** [comment]
This what happens when i press fast forward button during crash screen it reaches title screen.
https://user-images.githubusercontent.com/37503397/210693418-613583d3-62f4-443c-a845-fee90e6668d5.mp4

**Comment by ANR2ME** [comment]
Hmm.. i didn't know that Fast forward can be used to resume emulation O.o 
It probably ignores a lot of bad/invalid memory addresses until it eventually reached the title screen.

**Comment by unknownbrackets** [comment]
Fast forward is used to leave the STEPPING CPU execution mode.  Maybe we could change it, but it's really convenient when debugging.

-[Unknown]

**Comment by sum2012** [comment]
PPSSPP v1.14.4-96-g9953809dc log:
https://gist.githubusercontent.com/sum2012/780f78d3b66cd35136eeadcf0fc112b1/raw/8141c27d303b47039282d44a824560164fffc2b9/gistfile1.txt

The crash may cause from 
59:16:081 user_main    D[ME]: HLE\sceMpeg.cpp:1790 80618001=sceMpegGetAtracAu(08e4e308, 00000002, 08e4e3d8, 08e4e428)
59:16:081 user_main    D[ME]: HLE\sceMpeg.cpp:1695 0=sceMpegGetAvcAu(08e4e308, 00000001, 08e4e390, 08e85550)
59:16:081 user_main    D[ME]: HLE\sceMpeg.cpp:1149 video: bufferAddr = 08e8556c, *buffer = 04044000, *init = 00000000
59:16:081 user_main    I[ME]: HW\MediaEngine.cpp:87 FF: error while decoding MB 8 9, bytestream -18
59:16:081 user_main    D[ME]: HLE\sceMpeg.cpp:1210 sceMpegAvcDecode(08e4e308, 08e4e390, 512, 08e8556c, 08e85570)

**Comment by sum2012** [comment]
JPCSP emulator has similar video issue but no problem 
161337 [user_main] ERROR atrac3plus - Invalid gain location: ch=0, sb=0, pos=1, val=0
162810 [user_main] INFO  hle.ModuleMgrForUser - IGNORING:sceKernelStopModule HLE module 'sceMpeg_library'
