### ISSUE TITLE
Slowdown when using ultimates in Naruto heroes 3

### ISSUE THREAD

**Issue by Weizhy** [hrydgard/ppsspp#16733]
### Game or games this happens in

ULUS10518 - Naruto ultimate ninja heroes 3

### What area of the game

When using Kakashi and Neji ultimates

### Speed seen in PPSSPP

57% (17/30)

### GE frame capture and debug statistics

![Screenshot_2023-01-03-20-10-30-126_org ppsspp ppsspp](https://user-images.githubusercontent.com/105612808/210785150-4dfc7ed6-fc0e-409f-bd8c-18a7342bc4b6.jpg)
![Screenshot_2023-01-03-20-09-19-436_org ppsspp ppsspp](https://user-images.githubusercontent.com/105612808/210785168-18ca389f-ba11-44b9-845f-200c00b6b589.jpg)
[ULUS10518.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/10352302/ULUS10518.ppdmp.zip)

### Platform

Android

### Mobile phone model or graphics card

Poco x3 NFC

### PPSSPP version affected

v1.14.4-67-g389c7bf44

### Graphics backend (3D API)

Vulkan

### Any other notes or things you've tried

The only way I found to fix this is enabling "skip gpu readbacks" but then it have graphical issues, the game uses less than 20% of my CPU and GPU during the slowdowns so I think it's not my phone. when I do other things while playing, like recording the screen it runs almost full speed

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the slowdown.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
![image](https://user-images.githubusercontent.com/130929/210799692-40f543f1-c199-451a-b534-30f809890e6d.png)

Yeah, it's another GPU readback case. Might be solved by adding the game ID to [BlockTransferAllowCreateFB] or [IntraVRAMBlockTransferAllowCreateFB], if we're lucky.

**Comment by Weizhy** [comment]
> ![image](https://user-images.githubusercontent.com/130929/210799692-40f543f1-c199-451a-b534-30f809890e6d.png)
> 
> Yeah, it's another GPU readback case. Might be solved by adding the game ID to [BlockTransferAllowCreateFB] or [IntraVRAMBlockTransferAllowCreateFB], if we're lucky.

I did it using a compat.ini file and it's fixed 😁 thanks

**Comment by hrydgard** [comment]
@Weizhy Sorry, I forgot to follow up here.

Did you try both BlockTransferAllowCreateFB and IntraVRAMBlockTransferAllowCreateFB ? Do either solve the problem, or only BlockTransferAllowCreateFB ?

Just so I know which one to enable by default.

**Comment by Gamemulatorer** [comment]
I cannot really notice framedrops using default settings vulkan backend.

btw my vivo y11 is snapdragon 439 adreno 505 only.

https://user-images.githubusercontent.com/37603562/219600004-1ab697a0-b2da-47d2-9eca-801a80c643f5.mp4

But adding this game to IntraVRAM might also be a good idea.

**Comment by hrydgard** [comment]
Alright, thanks for testing!

**Comment by hrydgard** [comment]
I added the compat.ini lines, so it should perform well by default now.
