### ISSUE TITLE
Several missing graphics on D3D9 after merge #16730

### ISSUE THREAD

**Issue by TengaiHH** [hrydgard/ppsspp#16739]
### Game or games this happens in

Phantasy Star Portable 2 Infinity, Toukiden Kiwami, Hatsune Miku - Project Diva, Puyo Puyo 20th Anniversary, others

### What area of the game

In some games, like Phantasy Star Portable 2 Infinity and Hatsune Miku - Project Diva, the issue is already visible during the intro, and in others, like Toukiden Kiwami, it is only visible after loading a save. Certain areas seem to not be affected, like Toukiden's town.

### What happens

Phantasy Star Portable 2 Infinity (in-game):
![NPJH50332_00026](https://user-images.githubusercontent.com/65472318/210977867-f2120fb2-2bdd-4383-a709-583b2d9ef8c1.jpg)

Toukiden Kiwami (in-game):
![NPJH50878_00000](https://user-images.githubusercontent.com/65472318/210977950-82b14be1-eac3-481b-b553-aaf076404280.jpg)

Also several black screens during intros and in other games. No noticeable issues in certain games, like Ace Combat X - Skies Of Deception or Gladiator Begins, as far as I can tell. Started after #16730.

### What should happen

Phantasy Star Portable 2 Infinity:
![NPJH50332_00024](https://user-images.githubusercontent.com/65472318/210978147-9db5c0df-5d23-46b8-b253-f8c2973ab48e.jpg)

Toukiden Kiwami:
![NPJH50878_00001](https://user-images.githubusercontent.com/65472318/210978172-a59c9b46-13db-4614-9eb8-610e5e07345b.jpg)

### Platform

Windows

### Mobile phone model or graphics card

NVIDIA GeForce 210

### PPSSPP version affected

v1.14.4-74-g5f10cabe5

### Last working version

1.14.4

### Graphics backend (3D API)

Direct3D 9

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
This is related to #16628, not #16730.  For some reason, it's always taking the `else` case.  Reversing the if condition "fixes" it but presumably means no fog ever.

-[Unknown]

**Comment by hrydgard** [comment]
Ah okay. Might need to sacrifice another uniform for a bool instead, in case this is some wacky precision issue.
