### ISSUE TITLE
Tony Hawk Project 8 Crash

### ISSUE THREAD

**Issue by Blacob777** [hrydgard/ppsspp#16736]
### Game or games this happens in

ULES00625

### What area of the game / PPSSPP

![Qu_KT2d498o](https://user-images.githubusercontent.com/29165096/210901999-f45c9abd-3e2c-4e2e-b1f0-30ec9ac1865b.jpg)

### What should happen

Just crashed atfer 1 minutes 

### Platform

Android

### Mobile phone model or graphics card

POCO F3

### PPSSPP version affected

v1.14.4-74

### Last working version

v1.13.4

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by LunaMoo** [comment]
Possibly will need similar JIT refresh hack as the other Tony Hawk game or wait to a proper fix for that problem.

 Could also be just a crash related to cheats or whatever unsafe settings used since that's what purple crash screen would point to.

**Comment by hrydgard** [comment]
I see you are using some kind of cheat, it's likely the cause? Or possibly #16719 caused something to change in an unfortunate way here..

**Comment by sum2012** [comment]
@hrydgard Yes
v1.14.4-42-g4e30c5c0c good
v1.14.4-44-g248ea42a5  bad
It mean #16719
ppsspp-v1.14.4-96-g9953809dc-windows-amd64 log:
https://gist.github.com/sum2012/cd4db8070ee97ca977ddc59553aa7a97

**Comment by hrydgard** [comment]
Thanks for testing! 

OK, I'll consider reverting it - but I'm pretty sure it right, it's just some interaction with other problems we have with our instruction cache emulation, I guess.

**Comment by unknownbrackets** [comment]
Maybe we should always invalidate a larger range - farther back and forward?  Maybe it'd be best to create some tests and see what exactly gets invalidated by this instruction and how well it works in PPSSPP.

-[Unknown]
