### ISSUE TITLE
Custom touch buttons getting stuck?

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#16748]
Reported on Discord by `Lester!`

> Anyone have a fix for stuck custom buttons?
> It doesn't happen when I do it on normal buttons though, I tried it when I was playing pop n music portable, when I do it on the dpad and face buttons it's fine, but the custom buttons het stuck

**Comment by iota97** [comment]
Mhhh, he opened a thread with:
>Whenever I play rhythm games on the PSP, I usually use custom buttons in order to make it easier for me. One thing that bothers me though is that when I press three or more custom buttons at the same time, they get stuck. What is the cause of this?

This could be the usual problem with 3 touch getting stuck with gesture? I can't find the issues but I have some memory of it...

**Comment by Gamemulatorer** [comment]
https://github.com/hrydgard/ppsspp/issues/12025

**Comment by unknownbrackets** [comment]
Yeah, if it's three or more buttons, sounds like it's just a device issue and not a PPSSPP issue.

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, pretty likely actually.
