### ISSUE TITLE
OpenGL shader linking crash after clearing cache

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#16764]
We get a bunch of OpenGL validation errors when reaching in-game in Wipeout Pure running in debug mode and then it crashes.

Seems we're trying to link a program with already deleted or outdated shaders. Culprit is https://github.com/hrydgard/ppsspp/commit/5749b5a825f0d30a14a305b5cdb2a73a80323cbc from https://github.com/hrydgard/ppsspp/pull/16577 - clearing the cache after the useflag changed is new. 

I guess we have some work to do on runtime OpenGL shader cache clearing as well, similar to #16762

**Comment by hrydgard** [comment]
Culprit is 5749b5a825f0d30a14a305b5cdb2a73a80323cbc  from #16577 .  I guess we have some work to do on OpenGL shader cache clearing as well.

**Comment by unknownbrackets** [comment]
I'll look into this more in a bit less than a day - sorry.  I'm tempted to just use a refcount here on `GLRShader` since it has a competing lifetime.

-[Unknown]

**Comment by hrydgard** [comment]
I think that would be totally fine.
