### ISSUE TITLE
Add auto-save or automatic save when exiting the game

### ISSUE THREAD

**Issue by MiguelCardonaG** [hrydgard/ppsspp#16766]
### What should happen

You can add an option so that every time you leave a game the emulator has an option of an automatic save. When we play again, the emulator will ask you if you want to continue with that same previous save or with the main one.

The AetherSX2 emulator has the option:

![Screenshot_20230109-172221](https://user-images.githubusercontent.com/65356692/211356898-02c3542a-f1ab-4708-bfb8-cf4aaccf933b.jpg)

### Who would this benefit

All!! Especially for those users who leave without saving the game.

### Platform (if relevant)

Android

### Games this would be useful in

All

### Other emulators or software with a similar feature

Aethersx2.

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by Gamemulatorer** [comment]
Dup of https://github.com/hrydgard/ppsspp/issues/8661 please close.

**Comment by hrydgard** [comment]
Yup, good idea, but a duplicate.
