### ISSUE TITLE
EMUELEC 4.6 build error since commit GPU: Use NEON for vector length/normalize on odroid n2+

### ISSUE THREAD

**Issue by Kelvfimer** [hrydgard/ppsspp#16772]
### Platform

Linux / BSD

### Compiler and build tool versions

CMAKE 3.24.2

### Operating system version

Ubuntu 20.04 + toolchain

### Build commands used

PROJECT=Amlogic-ce DEVICE=Amlogic-ng ARCH=aarch64 DISTRO=EmuELEC ./scripts/build PPSSPPSDL

 cmake -GNinja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_TOOLCHAIN_FILE=/home/kelv/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/toolchain/etc/cmake-aarch64-libreelec-linux-gnueabi.conf -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=MinSizeRel -DUSE_SYSTEM_FFMPEG=ON -DUSING_FBDEV=ON -DUSING_EGL=ON -DUSING_GLES2=ON -DUSING_X11_VULKAN=OFF -DUSE_DISCORD=OFF -DARM64=ON /home/kelv/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/PPSSPPSDL-d90aec6f63acca69f8806a685e9fb0aa26f26ff1
Normal Build
NOT using X11 for Vulkan
CMAKE_SYSTEM_PROCESSOR: aarch64
Generating for ARMv8, MinSizeRel

### What happens

/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/PPSSPPSDL-d90aec6f63acca69f8806a685e9fb0aa26f26ff1/GPU/Software/RasterizerRectangle.cpp:83:55: error: cannot convert 'uint16x4_t' to 'int16x4_t'

[615/815] Building CXX object CMakeFiles/Core.dir/GPU/Software/RasterizerRectangle.cpp.o
FAILED: CMakeFiles/Core.dir/GPU/Software/RasterizerRectangle.cpp.o
[buildfailed.txt](https://github.com/hrydgard/ppsspp/files/10381951/buildfailed.txt)

### PPSSPP version affected

d90aec6f63acca69f8806a685e9fb0aa26f26ff1

### Last working version

1f91993e7d38f8c76b510b997a0508dd1fca7771

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] Make sure to run `git submodule update --init --recursive` before building.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try deleting the build directory and running the build again.
- [ ] Check GitHub Actions, which builds every merge and PR.
- [X] Include logs and help us reproduce.

**Comment by hrydgard** [comment]
Just a signed-ness typo that some compilers are apparently ignoring. Fixed.
