### ISSUE TITLE
EMUELEC 4.6 build error Rasterizer error: cannot convert 'const float32x4_t' to 'int32x4_t' on Rasterizer.cpp:780:78

### ISSUE THREAD

**Issue by Kelvfimer** [hrydgard/ppsspp#16777]
### Platform

Linux / BSD

### Compiler and build tool versions

CMAKE 3.24.2

### Operating system version

Ubuntu 20.04 + toolchain

### Build commands used

cmake -GNinja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_TOOLCHAIN_FILE=/home/kelv/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/toolchain/etc/cmake-aarch64-libreelec-linux-gnueabi.conf -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=MinSizeRel -DUSE_SYSTEM_FFMPEG=ON -DUSING_FBDEV=ON -DUSING_EGL=ON -DUSING_GLES2=ON -DUSING_X11_VULKAN=OFF -DUSE_DISCORD=OFF -DARM64=ON /home/kelv/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/PPSSPPSDL-d90aec6f63acca69f8806a685e9fb0aa26f26ff1
Normal Build
NOT using X11 for Vulkan
CMAKE_SYSTEM_PROCESSOR: aarch64
Generating for ARMv8, MinSizeRel

### What happens

There are more signed-ness typo as the one solved in this issue https://github.com/hrydgard/ppsspp/issues/16772

Now on /home/kelv/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/PPSSPPSDL-384cd91400570da0719efa18926f2e70bfaa35b2/GPU/Software/Rasterizer.cpp:780:78: error: cannot convert 'const float32x4_t' to 'int32x4_t'

### PPSSPP version affected

d90aec6f63acca69f8806a685e9fb0aa26f26ff1

### Last working version

https://github.com/hrydgard/ppsspp/commit/1f91993e7d38f8c76b510b997a0508dd1fca7771

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] Make sure to run `git submodule update --init --recursive` before building.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try deleting the build directory and running the build again.
- [ ] Check GitHub Actions, which builds every merge and PR.
- [X] Include logs and help us reproduce.

**Comment by hrydgard** [comment]
This time it's not signedness but confusion between float32x4 and int32x4, according to your error. Will take a look soon.

**Comment by hrydgard** [comment]
Ah, it's using ".vec" instead of ".ivec" when accessing the vector union. Fixing.
