### ISSUE TITLE
Mac os controller bindings wrong

### ISSUE THREAD

**Issue by dravpin** [hrydgard/ppsspp#16788]
### Game or games this happens in

None/all games

### What area of the game / PPSSPP

issue dpad unrecognized and buttons arent recognized properly
in version ppsspp v1.14.3-28-gcd535263c buttons are wrong but in latest build
nothing is detected

controller: xbox one
mac os: 13.01

in ppsspp version v1.14.3-28-gcd535263c

the buttons are detected as follows

D-Pad
Up - nothing
Down - nothing
Left - nothing
Right - nothing

Left Analog
Up - Y Axis-
Down - Y Axis+
Left - X Axis-
Right - X Axis+

Right Analog
Up - Pressure-
Down - Pressure+
Left - Touch Major+
Right - nothing

Buttons
Triangle - b2
circle - b3
cross - b1
square - b4
L1 - b6
L2 - b5
R1 - b5 (same as L2)
R2 - ThumbL
L3 - Back
R3 - ThumbL (same as R2)
Start - b10
Select - b9

### What should happen

Button bindings should be accurate

### Platform

macOS

### Mobile phone model or graphics card

Apple M1 13-inch, M1, 2020

### PPSSPP version affected

v1.14.4-191-gaad07fc4

### Last working version

Cant remeber

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Related to #10679 

I'm guessing the controler somehow got a new name, making it so it doesn't find the right entry in gamecontrollerdb.txt...

**Comment by dravpin** [comment]
woah quick reply sorry update i just compiled latest and now instead of the bindings being wrong its just not detected at all

**Comment by dravpin** [comment]
i sadly dont understand how to use the jstest-sdl tool

**Comment by hrydgard** [comment]
Should be fixed by #18491.
