### ISSUE TITLE
Resolution 

### ISSUE THREAD

**Issue by Gelo021** [hrydgard/ppsspp#16792]
Yow again, just wanna ask if changing Display Resolution to Any Resolution or Any Resolution to native, kinda misplace ?
![Screenshot_2023-01-12-02-25-46-92_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/67460268/211889221-872cb24b-2509-4053-9d1b-c69a7fe3387a.jpg)
After Changing...
![Screenshot_2023-01-12-02-26-07-02_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/67460268/211889287-a3290156-7c94-48cb-8639-47924e634c7d.jpg)

Pressing Reset wont change, restarting the game make it normal again kindda wierd 🤔

**Comment by hrydgard** [comment]
I would recommend not changing the display resolution at all. But yeah, there seems to still be some bugs...

**Comment by Gelo021** [comment]
> I would recommend not changing the display resolution at all. But yeah, there seems to still be some bugs...

Okay hrydgard, im back at reporting bugs hihi
