### ISSUE TITLE
God Eater 2 v1.40 crash

### ISSUE THREAD

**Issue by Gelo021** [hrydgard/ppsspp#16801]
![Screenshot_2023-01-12-22-25-10-27_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/67460268/212092223-f599a462-2f29-4cc8-9e42-b7bd2c76667a.jpg)

Here's the GEdump

[NPJH50832.zip](https://github.com/hrydgard/ppsspp/files/10402513/NPJH50832.zip)

**Comment by hrydgard** [comment]
I don't expect a GE dump to help much here. What are you doing in the game when the crash happens, is it consistent? Savegame nearby?

**Comment by Gelo021** [comment]
https://user-images.githubusercontent.com/67460268/212093984-c5bf29ae-a991-4515-adf4-42feccbbd66e.mp4

**Comment by Gelo021** [comment]
Its a fresh save, just played it now

**Comment by hrydgard** [comment]
Thanks, that helps! Very strange...

**Comment by ANR2ME** [comment]
Probably related to https://github.com/hrydgard/ppsspp/issues/8075

PS: As i remembered GE2 tried to allocate a lot of memory during loading scene, and many of them failed

**Comment by Gelo021** [comment]
> Probably related to #8075
> 
> PS: As i remembered GE2 tried to allocate a lot of memory in many chunks during loading scene, and some of them failed

Just found out that the Jp v1.40 make error but the one with the English patch works hmmm. I think the DLC might be the problem 🤔🤔🤔

**Comment by unknownbrackets** [comment]
> Probably related to #8075
> 
> PS: As i remembered GE2 tried to allocate a lot of memory in many chunks during loading scene, and some of them failed

As I recall, the game does this on a real PSP and relies on the allocation failures to know when to free old allocations.  This makes it tricky to figure out what's wrong and what's right.

I do think someone said this crashes if you use the DLC without the game update patch or something.

-[Unknown]

**Comment by Gamemulatorer** [comment]
This should remove from 1.15 milestone

**Comment by Lumino5501** [comment]
this should be closed as GE2v1.40 now works on latest build versions

**Comment by hrydgard** [comment]
It is already closed.
