### ISSUE TITLE
ppsspp v1.14.4 ULJM05428 (Kiniro no Corda 2f) rendering error (CLUT misdetection)

### ISSUE THREAD

**Issue by android-1995** [hrydgard/ppsspp#16819]
### Game or games this happens in

ULJM05428 V1.01 金色のコルダ 2 f / Kiniro no Corda 2f

### What area of the game

You can reproduce at the beginning of the game

### What happens

![Screenshot_2023-01-19-15-21-13-787_org ppsspp ppsspp](https://user-images.githubusercontent.com/35674533/213381070-69719086-d05b-4540-a443-41d16b7810d6.jpg)
The name display is abnormal. The picture below is a screenshot of the game of V1.13.2 PPSSPP
![Screenshot_2023-01-19-15-25-07-523_org ppsspp ppsspp](https://user-images.githubusercontent.com/35674533/213381319-acd17a09-4797-4cba-b6c2-f1fe92a3aac6.jpg)

### What should happen

![Screenshot_2023-01-19-15-25-07-523_org ppsspp ppsspp](https://user-images.githubusercontent.com/35674533/213381357-7a2caefd-ed39-49ff-beda-4855544d82bd.jpg)
This picture is a screenshot of the game of V1.13.2 PPSSPP

### Platform

Android

### Mobile phone model or graphics card

redmi  k40 

### PPSSPP version affected

v1.14.4

### Last working version

V1.13.2

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [x] Try resetting settings or older versions and include if the issue is related.
- [ ] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [x] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
A GE frame capture (https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump) would help immensely to debug this.

**Comment by sum2012** [comment]
I test windows 64 bit.
It effect opengl,d3d9,d4d11,valkun
softgpu no problem.
@hrydgard @unknownbrackets 
Opengl and softgpu 's   GE frame capture  is not equal this time ?
[ULJM05428-opengl.zip](https://github.com/hrydgard/ppsspp/files/10472125/ULJM05428-opengl.zip)
[ULJM05428-softgpu.zip](https://github.com/hrydgard/ppsspp/files/10472127/ULJM05428-softgpu.zip)

**Comment by sum2012** [comment]
@hrydgard @unknownbrackets 
v1.13.2-959-g1b9bc141f good
v1.13.2-981-gca2962bea bad
It mean #16014

**Comment by hrydgard** [comment]
Thanks! Guess maybe we are misdetecting clut-from-framebuffer mode, or leaving it on for a draw that shouldn't have it. Will be easy to investigate now with the capture.

**Comment by sum2012** [comment]
Just a question ,why do we default 16gb free space ?

**Comment by sum2012** [comment]
Git bisect result https://github.com/hrydgard/ppsspp/pull/16014/commits/1f6d27bd552ecc1bfdae916288df88802b61da29
