### ISSUE TITLE
Dynamic left analog stick

### ISSUE THREAD

**Issue by anomalchik** [hrydgard/ppsspp#16820]
### What should happen

I propose to make a dynamic left stick.

I imagine this as some area where the stick can work(Stick area). Pressing in this zone will be considered the center of the stick (zero point), and any deviation from the center will already work as a classic stick.(move area)

![1](https://user-images.githubusercontent.com/3417567/213404762-87a803fd-b34c-4dab-b811-fb1bf4d22dfe.png)
![2](https://user-images.githubusercontent.com/3417567/213404763-e253cf23-3e1b-4892-bfdc-a64bad6192a5.png)
![3](https://user-images.githubusercontent.com/3417567/213404742-a3f55323-cb8e-4187-be31-17673d39affb.png)

In input settings make ability to change size for stick area and move area. 

Stick icon and areas doesn't draw in touchscreen input ui. (Draw only in settings)

### Who would this benefit

In shooters, you will no longer need to try to aim at the stick or select its optimal settings for a long time

### Platform (if relevant)

Android

### Games this would be useful in

any shooters

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
This is already implemented, the option is called "Auto-centering analog stick". Could be that we should make the touch area larger though.

**Comment by anomalchik** [comment]
> This is already implemented, the option is called "Auto-centering analog stick". Could be that we should make the touch area larger though. And maybe it should be the default?

this option still forces you to apply to the area of ​​the stick icon itself. It would be nicer to see an area where he can spawn without compromising linear movement.

**Comment by anomalchik** [comment]
later I can send a video example with an implementation from another project.

**Comment by anomalchik** [comment]
https://youtu.be/NdQATzFlklM

**Comment by anomalchik** [comment]
in this example for sticks, the screen is divided into two parts, but I suggest leaving the area that the user can choose themselves
 ![Screenshot_20230119-110221_Source Engine~2](https://user-images.githubusercontent.com/3417567/213417094-58379d3d-60fa-428b-a9ed-f74a1bc2bf0d.png)

**Comment by hrydgard** [comment]
Yeah I got it. But it's really the same feature, just with a much bigger area.

Which is probably a good idea indeed. I'm putting it on the list.

**Comment by hrydgard** [comment]
Yeah the UI is of course the tricky part, the rest is just a small change in checks..

**Comment by yasabaka** [comment]
https://youtu.be/EgjFZZUhlp0
video just in case
