### ISSUE TITLE
Warriors Orochi don't enough free space to save

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#16827]
### Game or games this happens in

ULUS10341 - Warriors Orochi

### What area of the game / PPSSPP

At the beginning
I tried [ReportSmallMemStick] and [MemstickFixedFree] in compat.ini still fail
![1](https://user-images.githubusercontent.com/2177532/213894697-6bf79f6e-995e-4966-a8a7-8b999eb41175.jpg)

### What should happen

No problem
like jpcsp emulator

### Logs

psspp-v1.14.4-253-g03f64a021-windows-amd64 log: https://gist.github.com/sum2012/62b3d5f1e0c59f37209b8327bb475774
Real PSP log: https://gist.github.com/sum2012/1e8e6f5f2249c5a818a0c313e8c7121b

### Platform

Windows

### Mobile phone model or graphics card

Nvidia Geforce 710

### PPSSPP version affected

v1.14.4-253-g03f64a021

### Last working version

None

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
If you change `listEmptyFile` to false in the case of SIZES, does it work?

-[Unknown]

**Comment by sum2012** [comment]
@unknownbrackets Can you give me more detail to change ? Thanks

**Comment by sum2012** [comment]
@unknownbrackets Do you mean in HW\MemoryStick.cpp
Change bool listEmptyFile = true; to bool listEmptyFile = false; ?
The change not work

**Comment by sum2012** [comment]
@unknownbrackets in HW/MemoryStick.cpp
u64 MemoryStick_FreeSpace() 
force return 1024*1024 fix the issue

**Comment by sum2012** [comment]
my bad should be ULJS10341 ->ULUS10341
