### ISSUE TITLE
UI scissor out of bounds in MainScreen (crash)

### ISSUE THREAD

**Issue by Nemoumbra** [hrydgard/ppsspp#16837]
### Game or games this happens in

Not game-specific

### What area of the game / PPSSPP

The non-client window area at top of the screen where the menu and window resizing buttons are places is clickable.
Doubleclicking on it makes the window go full screen and back.
Unfortunately, going back results in this:
![image](https://user-images.githubusercontent.com/62447396/214078814-476eabc7-ac11-4f8e-b15f-ab65f3122811.png)
If the graphical backend is Direct3D 11, this makes the app crash.
D3D11DrawContext::SetScissorRect() is the function called before the crash occurs.
Yes, this output happens in all backends, but only Direct3D 11 dies.

### What should happen

If "UI scissor" is allowed to be out of bounds, at least don't crash. If not, this should be also looked at.

### Platform

Windows

### Mobile phone model or graphics card

AMD Radeon(TM) Graphics

### PPSSPP version affected

Self-built version (one of the lastest)

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Was fixed by 91cca1c980428988934b938a8e1de81c463ea823 , forgot to link.
