### ISSUE TITLE
Unhandled exception after resetting the game

### ISSUE THREAD

**Issue by Nemoumbra** [hrydgard/ppsspp#16836]
### Game or games this happens in

Patapon 3 (EUR)

### What area of the game / PPSSPP

Enable "break on load".
Place a breakpoint at 0890a7e8, then Go, select a language, select "Understood", wait for stepping.
Then Step Into once and put a default memory breakpoint at address 08A5B78C. When I reset the game after doing all of this, PPSSPP crashes with an unhandled exception of read access violation.
Memory::GetPointerUnchecked(...) (line 105 of the MemmapFunctions.cpp)
This function was called from Read_U32. Later in the stack trace I saw the function MIPSStackWalk::ScanForEntry.

### What should happen

Crashing is a no-no.

### Platform

Windows

### Mobile phone model or graphics card

AMD Radeon(TM) Graphics

### PPSSPP version affected

Self-built version (one of the lastest)

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
I don't have the EU version to try this, and it doesn't happen in the US version.  That said, did #16988 help?

-[Unknown]

**Comment by Nemoumbra** [comment]
I think it did help! Issue closed.
