### ISSUE TITLE
[Feature Request] Add crc in the crash screen

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#16840]
### What should happen

Display crc of the iso

### Who would this benefit

To confirm the disc dump correctly

### Platform (if relevant)

None

### Games this would be useful in

ALL GAME

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
This is a very good idea, will implement.
