### ISSUE TITLE
Regression in Shinobido - Tales of the Ninja

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#16845]
Reported by email:

> When I OPEN the GAME "Shinobido - Tales of the Ninja" it has a bug that all the Texts are Missing and Completely Dissappeared, and the Game is always Crashing.. unlike before I could play it No Problem and Beat the Game without resting.

> Please FIX this Bug, so I could Played it again, before this 1.14.4 version udpate came and the bugs showed up.

**Comment by sum2012** [comment]
v1.13.2-2456-gc33f732cc good
v1.13.2-2458-gc1c5c6cb8 bad
It mean #16554
As I excpect,It is scefont issue
tag @nassau-tk 
@hrydgard how do we solve it ?

**Comment by sum2012** [comment]
This is real PSP 's image, Not sure it use which font
![pic_0000](https://user-images.githubusercontent.com/2177532/214560492-1edf0751-73e9-467b-a3a6-af84641e8ea4.png)

**Comment by nassau-tk** [comment]
Uuuum....
I must adjust the Jpn0.pgf.
I will back to home on sunday.
Please, Give me a time!

**Comment by sum2012** [comment]
@nassau-tk don't hurry, We only need to fix it before v1.15.0 :)

**Comment by sum2012** [comment]
Another option is that force don't use jpn0.pgf for UCESXXXX 's games

**Comment by hrydgard** [comment]
Hm, that could be a possibility. Does the real PSP do something like that?

**Comment by sum2012** [comment]
Real psp log:
00:05.260 user_main - sceFontFindOptimumFont 0x8B7B730, 0x9FF9B88, 0x09FF9B5C(0x0) = 0x0
So that It really return Jpn0.pgf ? (arib.pgf and gb3s1518.bwfon don't count of 0 ?)

**Comment by unknownbrackets** [comment]
I have seen no evidence that the PSP sceFont library does any weird logic like that.  I'm pretty sure it doesn't care what game you're playing, it just tries to match the requested style.  I think I have games that correctly use jpn0.

"Glyph with negative size, not rendering" seems weird, though.

-[Unknown]

**Comment by nassau-tk** [comment]
Same issue happened Shinobido Homura(Japan ver.).
OKOK〜✨

**Comment by nassau-tk** [comment]
Hello~!!

I fixed jpn0.pgf.
Text will appear on 忍道 焔(JP ver.) too.

[jpn0.zip](https://github.com/hrydgard/ppsspp/files/10528694/jpn0.zip)

ｖ1.14.4-322 Original (Not appear the font)
![image](https://user-images.githubusercontent.com/48179091/215298149-b3052731-5ad4-4141-8184-fb7df0079304.png)

v1.14.4-322 change fixed jpn0.pgf
![image](https://user-images.githubusercontent.com/48179091/215298188-13e8983b-d2fe-4458-89c1-7d9bf5ccb272.png)

This isseu reported by e-mail.
And, Idk that how to check on English ver.(Shinobido - Tales of the Ninja)

I will make PR soon.

**Comment by sum2012** [comment]
This is  English ver.(Shinobido - Tales of the Ninja) 
@nassau-tk 's font
![1](https://user-images.githubusercontent.com/2177532/215299767-c9bac838-4b06-404c-aa9f-036dc14233b2.png)

**Comment by nassau-tk** [comment]
@sum2012 

Gooooooo:D  !!

**Comment by nassau-tk** [comment]
@hrydgard 
This isuue solved by fixed jpn0.pgf.
Normaly, This topic will close.
Do you have any problem?

**Comment by Ndron** [comment]
@nassau-tk
Did nt get where is original jpn0.pgf ? Or where I should place  jpn0.pgf ?

**Comment by sum2012** [comment]
@Ndron  nassau-tk in #16859 have update jpn0.pgf which merged.

**Comment by nassau-tk** [comment]
@sum2012 
> @Ndron nassau-tk in #16859 have update jpn0.pgf which merged.

Probably, Stable ver. user.
