### ISSUE TITLE
Build error with libretro in cpu_features library (mac only)

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#16869]
Weirdly, on x86 mac only, we're getting this:

https://git.libretro.com/libretro/ppsspp/-/jobs/3094055/raw

(the error messages are mangled due to parallel build, the error is not glew-related).

`./ext/cpu_features/src/impl_x86_macos.c: "Darwin needs support for sysctlbyname"`

This error message comes from here:
https://github.com/google/cpu_features/blob/main/src/impl_x86_macos.c#L22

so for whatever reason, HAVE_SYSCTLBYNAME is not defined.

That one is set like this, in ext/cmake/cpu_features:

```cmake
if(PROCESSOR_IS_X86)
  if(APPLE)
    target_compile_definitions(cpu_features PRIVATE HAVE_SYSCTLBYNAME)
  endif()
endif()
```

And processor_is_x86 looks to be set correctly too, I believe.

```
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "(x86_64)|(AMD64|amd64)|(^i.86$)")
  set(PROCESSOR_IS_X86 TRUE)
```

So I'm not really sure what's going on. When I do a normal build of PPSSPP on my x86 mac, having no problems.

**Comment by unknownbrackets** [comment]
Apparently libretro only uses cmake for Android and uses the other makefile for everything else.  I think.  Different people say different things and I haven't cared enough to look hard.

-[Unknown]

**Comment by hrydgard** [comment]
I believe this is fixed, closing.
