### ISSUE TITLE
[MSVC][std:c++latest] ppsspp failed to build due to error C2280 with msvc on Windows

### ISSUE THREAD

**Issue by Zhaojun-Liu** [hrydgard/ppsspp#16886]
### Game or games this happens in

None

### What area of the game / PPSSPP

Hi,
We update the commit of ppsspp recently, and it failed to build due to error C2280: 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>::basic_string(std::nullptr_t)': attempting to reference a deleted function (compiling source file UI\PopupScreens.cpp) [F:\gitP\hrydgard\ppsspp\Common\Common.vcxproj]. Could you please take a look? Thanks.

The commit of ppsspp we used: 12f219f695a3b53c2f707d4363a1e60ecde6141f

**Repro steps:**
1. git clone --recurse https://github.com/hrydgard/ppsspp.git F:\gitP\hrydgard\ppsspp
2. git -C "F:\gitP\hrydgard\ppsspp" fetch --recurse-submodules=no --force
3. git -C "F:\gitP\hrydgard\ppsspp" reset --hard 12f219f
4. git -C "F:\gitP\hrydgard\ppsspp" remote prune origin
5. git -C "F:\gitP\hrydgard\ppsspp" submodule sync
6. git -C "F:\gitP\hrydgard\ppsspp" submodule foreach git reset --hard
7. git -C "F:\gitP\hrydgard\ppsspp" submodule foreach git clean -xdf
8. git -C "F:\gitP\hrydgard\ppsspp" submodule update --init --recursive
9. set _CL_= /std:c++latest
10. mkdir F:\gitP\hrydgard\ppsspp\build_amd64 and cd F:\gitP\hrydgard\ppsspp\build_amd64
11. msbuild /m /p:Platform=x64 /p:Configuration=Release ../Windows/PPSSPP.sln /t:Rebuild /p:OutDir=F:\gitP\hrydgard\ppsspp\build_amd64

**Error info:**
`F:\gitP\hrydgard\ppsspp\Common\UI\PopupScreens.h(117,23): error C2280: 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>::basic_string(std::nullptr_t)': attempting to reference a deleted function (compiling source file UI\PopupScreens.cpp) [F:\gitP\hrydgard\ppsspp\Common\Common.vcxproj]`

**More:**
I tried the commit f57cb5e, it built ok.

### What should happen

Build successfully

### Logs

[build_ppsspp.log](https://github.com/hrydgard/ppsspp/files/10555130/build_ppsspp.log)

### Platform

Windows

### Mobile phone model or graphics card

None

### PPSSPP version affected

master branch, and commit is 12f219f

### Graphics backend (3D API)

Other

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Which version of Visual Studio? Might wanna upgrade.

Still, this is a bit unexpected, I'll try to fix it soon.

**Comment by Zhaojun-Liu** [comment]
> Which version of Visual Studio? Might wanna upgrade.
> 
> Still, this is a bit unexpected, I'll try to fix it soon.

Thanks for your reply.
VS version is: 16.11.22, but we use the inner latest compiler build to replace the related files in installed VS

**Comment by hrydgard** [comment]
This was a bug, my bad, with an easy fix. Thanks!
