### ISSUE TITLE
Does ppsspp support gbm backend +vulkan?

### ISSUE THREAD

**Issue by zack-huangzihan** [hrydgard/ppsspp#16899]
### Game or games this happens in

games

### What area of the game / PPSSPP

In the code: https://github.com/hrydgard/ppsspp/blob/ceb4186d0ffc26091bb3fc25a1e71bce15b8902d/SDL/SDLVulkanGraphicsContext.cpp

We can see that there is some support for the back end: WINDOWSYSTEM_WAYLAND  WINDOWSYSTEM_XLIB  WINDOWSYSTEM_XCB WINDOWSYSTEM_METAL_EXT and so on, Can gbm+vulkan render?

Here's how I changed it：

```
diff --git a/SDL/SDLVulkanGraphicsContext.cpp b/SDL/SDLVulkanGraphicsContext.cpp
index 433f35b03..e08c30578 100644
--- a/SDL/SDLVulkanGraphicsContext.cpp
+++ b/SDL/SDLVulkanGraphicsContext.cpp
@@ -105,8 +105,9 @@ bool SDLVulkanGraphicsContext::Init(SDL_Window *&window, int x, int y, int mode,      
 #endif
 #endif
        default:
-               fprintf(stderr, "Vulkan subsystem %d not supported\n", sys_info.subsystem);
-               exit(1);
+               vulkan_->InitSurface(WINDOWSYSTEM_DISPLAY, nullptr, nullptr);
+               //fprintf(stderr, "Vulkan subsystem %d not supported\n", sys_info.subsystem);
+               //exit(1);
                break;
        }
```
But it can't work. Do you have any advice for me?

### What should happen

On a lot of embedded linux platforms, probably most of the way to use kms, hopefully can support

### Platform

Linux / BSD

### Mobile phone model or graphics card

arm mali

### PPSSPP version affected

latest

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
GBM = https://www.reddit.com/r/linuxquestions/comments/ss4vhj/whats_the_gbm_api/ ?

I guess this hasn't been worked on yet, no. Feel free to help out.

**Comment by zack-huangzihan** [comment]
Maybe my description is not correct enough. Can kms+vulkan be implemented? 

As shown in the code above:

vulkan_->InitSurface(WINDOWSYSTEM_DISPLAY, nullptr, nullptr);  
Common/GPU/Vulkan/VulkanContext.h:

```
enum WindowSystem {
#ifdef _WIN32
        WINDOWSYSTEM_WIN32,
#endif
#ifdef __ANDROID__
        WINDOWSYSTEM_ANDROID,
#endif
#ifdef VK_USE_PLATFORM_METAL_EXT
        WINDOWSYSTEM_METAL_EXT,
#endif
#ifdef VK_USE_PLATFORM_XLIB_KHR
        WINDOWSYSTEM_XLIB,
#endif
#ifdef VK_USE_PLATFORM_XCB_KHR
        WINDOWSYSTEM_XCB,
#endif
#ifdef VK_USE_PLATFORM_WAYLAND_KHR
        WINDOWSYSTEM_WAYLAND,
#endif
#ifdef VK_USE_PLATFORM_DISPLAY_KHR
        WINDOWSYSTEM_DISPLAY,
#endif
};
```
 Is there any reason why only WINDOWSYSTEM_DISPLAY is not called？

**Comment by amverweij** [comment]
I would like to see this support too. The libretro core works perfectly well on gbm/kms. However standalone ppsspp is supposed to be more efficient. I believe there is an earlier attempt to implement this here:

https://github.com/hrydgard/ppsspp/pull/14758

The initial comments suggest the work isn't complete yet.

**Comment by zack-huangzihan** [comment]
hello, all @hrydgard @amverweij @vanfanel 
I'm so glad I realized this thing! 
The implementation here is referenced：https://github.com/vanfanel/ppsspp
For the call to vulkan interface in kms on the arm linux system, I changed the changes inside to the form of dlopen，Let me explain how this code works:

First of all, in linux system, vulkan implementation is not open in the source code provided by gpu manufacturers, they use a hook called "vulkan loader", used to parse the ***.so of different manufacturers，It's usually "libvulkan.so"，So I need to read it with dlopen needed to sign, and then in "SDL/SDLVulkanGraphicsContext CPP" add a WINDOWSYSTEM_DISPLAY implementation.

These implementations are in Common/GPU/Vulkan/VulkanContext.cpp

![YKS@NSH$GM100({C8CNE~{E](https://user-images.githubusercontent.com/44903277/216978804-8685852d-e643-4e8b-bf03-1400bf8f95ba.jpg)

![B4SN0@VP({_Q999 @N{}Q@K](https://user-images.githubusercontent.com/44903277/216978867-fbc70ac6-0c3f-4ad3-ab12-754c15017a80.png)

Both ui and game rendering worked well, so I submitted my code:

https://github.com/hrydgard/ppsspp/pull/16921

**Comment by hrydgard** [comment]
Thank you @zack-huangzihan for implementing this initialization.

Can we consider this closed now?

**Comment by zack-huangzihan** [comment]
ok
