### ISSUE TITLE
When it is adapted to our vr products, the screen remains black after opening, please help to confirm

### ISSUE THREAD

**Issue by chengzeyuan** [hrydgard/ppsspp#16897]
### Game or games this happens in

None

### What area of the game / PPSSPP

none

### What should happen

the screen should not remains black，and no frames submitted

### Logs

[2.log](https://github.com/hrydgard/ppsspp/files/10564393/2.log)

02-01 10:21:38.364  5248  5248 E PPSSPP  : [LOADER] zeyuantest -----g_Config.sFailedGPUBackends = data data = OPENGL,ALL
02-01 10:21:38.364  5248  5248 E PPSSPP  : [LOADER] Failed graphics backends: OPENGL,ALL
02-01 10:21:38.364  5248  5248 E PPSSPP  : [LOADER] Graphics backend failed for 0, trying another
02-01 10:21:38.364  5248  5248 E PPSSPP  : [LOADER] All graphics backends failed

Filtered log: 

[yvr_psp.log](https://github.com/hrydgard/ppsspp/files/10567315/yvr_psp.log)

also I find the data was null on PICO 

### Platform

Android

### Mobile phone model or graphics card

android 10

### PPSSPP version affected

none

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by chengzeyuan** [comment]
![image](https://user-images.githubusercontent.com/86513446/216222572-ce79b1be-87ea-4ceb-abb5-bc4f65d1a0c1.png)

I just started adapting our VR device. I'm not sure whether not submitting the frame is related to this error, please help to confirm，thx

**Comment by lvonasek** [comment]
Hi, I see in your log these errors:
* Framebuffer is not initialized (the same issue Pico introduced with PicoOS 5.3). I have a workaround for that here: https://github.com/lvonasek/ppsspp/commit/6dc264e7e5868e6084d574f5029bdd87b0fe2f15
* The controller mapping is failing (I cannot say more about it as I don't know anything about your device)

On PicoOS 5.3 are additionally these issues:
* In Common/VR/VRRender.cpp variable `shouldRender` is incorrectly false (fix by removing the usage of it)
* In Common/VR/VRBase.cpp getting already initialized EGL doesn't work (workaround would be to reinitialize it but I am against doing such a dirty workarounds)

**Comment by chengzeyuan** [comment]
[yvrtest.log](https://github.com/hrydgard/ppsspp/files/10567776/yvrtest.log)
Hi，@lvonasek  I had modify as https://github.com/lvonasek/ppsspp/commit/6dc264e7e5868e6084d574f5029bdd87b0fe2f15 ,but still black screen.
Also, our controller config is same as OC, the code I modify as a.patch ,help to check it, thx
[a.patch](https://github.com/hrydgard/ppsspp/files/10567828/a.patch)
![image](https://user-images.githubusercontent.com/86513446/216299419-3ae93308-2a74-464d-ad40-479ee14d8587.png)
![image](https://user-images.githubusercontent.com/86513446/216299536-9011b155-1c49-44c3-b00f-90cf21a49871.png)

**Comment by lvonasek** [comment]
The controller is a minor problem, it shouldn't cause black screen. From the logs it indicates this:
```
oxr_error: oxr_error:XR_ERROR_PATH_UNSUPPORTED
oxr_logger: (suggestedBindings->suggestedBindings[7]->binding == "/user/hand/left/input/squeeze/value") is not a valid binding path for profile "/interaction_profiles/yvr/touch_controller"
```

However the framebuffer seems to be initialized correctly now. Only the game is not submitting any frames. I cannot check the patch right now. Did you try to remove shouldrender in common/VR/VR renderer.cpp?

**Comment by chengzeyuan** [comment]
HI @lvonasek  controller error had fixed. VRRenderer.cpp had remove shouldrender as following PIC, still black screen.
Also I find some error as(test.log):
02-02 09:12:23.450 25817 25817 E PPSSPP  : [LOADER] zeyuantest -----g_Config.sFailedGPUBackends = data data = OPENGL
02-02 09:12:23.450 25817 25817 E PPSSPP  : [LOADER] Failed graphics backends: OPENGL
02-02 09:12:23.450 25817 25817 E PPSSPP  : [LOADER] zeyuantest------sFailedGPUBackends = OPENGL
02-02 09:12:23.450 25817 25817 E PPSSPP  : [LOADER] Graphics backend failed for 0, trying another
02-02 09:12:23.450 25817 25817 E PPSSPP  : [LOADER] All graphics backends failed
![image](https://user-images.githubusercontent.com/86513446/216318038-11e91a49-a028-4416-833c-22743270f0af.png)
[test.log](https://github.com/hrydgard/ppsspp/files/10568663/test.log)

**Comment by lvonasek** [comment]
The error seems to be not VR relevant. Does you headset have an option to run 2D android apps? It might be worth trying PPSSPP for mobile there.

**Comment by ANR2ME** [comment]
Based on the logs, his device seems to be YVR 2 (with Adreno 650 GPU) https://vr-compare.com/headset/yvr2

Btw, since it failed to detect/initialize all GPU backends, it's normal to show black screen isn't?

**Comment by hrydgard** [comment]
Even if it somehow believes all the backends are broken, it will try with OpenGL anyway.

But, presumably it does detect failure later since it remains thinking it's broken on the next boot.

**Comment by unknownbrackets** [comment]
Basically what happens is, it tries to load and if it's never able to successfully render a frame (typically due to a driver crash that brings down the entire app), it remembers the failure and considers the backend "failed."  It will preference another backend (i.e. Vulkan, etc.) in some cases on the next start, which helps people with broken drivers recover from the situation.  We don't have a ton of better options when buggy drivers just crash out the entire app.

In this case, it may be related more to whatever else is preventing the rendering.

You can change ppsspp.ini to have `FailedGraphicsBackends = IGNORE`.  This special value will ignore any driver crashes and you won't get any log messages or preferenced change in backend.  It probably won't change anything here, but at least you won't be worried about that error message anymore.

Am I correct to assume this is in the menu, even before trying to start any game?  Or are you only getting a black screen when you start an actual game?

-[Unknown]

**Comment by chengzeyuan** [comment]
The error seems to be not VR relevant. Does you headset have an option to run 2D android apps? It might be worth trying PPSSPP for mobile 

> we have no option to run 2D, but we can run 2D app like mobilephone.

Based on the logs, his device seems to be YVR 2 (with Adreno 650 GPU) https://vr-compare.com/headset/yvr2

> Yes , it is our device. 

Am I correct to assume this is in the menu, even before trying to start any game? Or are you only getting a black screen when you start an actual game?

> When I build normalDebug, app display and start the game normally, build vr_yvrDebug or vr_yvrRealse can not.  

Black screen occur after open app, nothing to do with the games.

**Comment by chengzeyuan** [comment]
> The error seems to be not VR relevant. Does you headset have an option to run 2D android apps? It might be worth trying PPSSPP for mobile
we have no option to run 2D, but we can run 2D app like mobilephone.

> Based on the logs, his device seems to be YVR 2 (with Adreno 650 GPU) https://vr-compare.com/headset/yvr2
Yes , it is our device.

> Am I correct to assume this is in the menu, even before trying to start any game? Or are you only getting a black screen when you start an actual game?
When I build normalDebug, app display and start the game normally, build vr_yvrDebug or vr_yvrRealse can not.
Black screen occur after open app, nothing to do with the games.

**Comment by chengzeyuan** [comment]
> The error seems to be not VR relevant. Does you headset have an option to run 2D android apps? It might be worth trying PPSSPP for mobile

we have no option to run 2D, but we can run 2D app like mobilephone.

> Based on the logs, his device seems to be YVR 2 (with Adreno 650 GPU) https://vr-compare.com/headset/yvr2

Yes , it is our device.

> Am I correct to assume this is in the menu, even before trying to start any game? Or are you only getting a black screen when you start an actual game?

When I build normalDebug, app display and start the game normally, build vr_yvrDebug or vr_yvrRealse can not.
Black screen occur after open app, nothing to do with the games.

**Comment by lvonasek** [comment]
If normalDebug works then it must be a VR specific issue. I see in the log that OpenXR successfully initializes but then go directly into pause mode.

Not much ideas what could go wrong there. Do you have in PPSSPPVR.cpp this for your headset?
```
VR_SetPlatformFLag(VR_PLATFORM_INSTANCE_EXT, true);
```

**Comment by chengzeyuan** [comment]
> Not much ideas what could go wrong there. Do you have in PPSSPPVR.cpp this for your headset?
VR_SetPlatformFLag(VR_PLATFORM_INSTANCE_EXT, true);

Yes, code has config it. and logs all print it out.
02-03 14:37:39.573 17711 17711 E PPSSPP  : [COMMON] zeyuantest-----11111111
02-03 14:37:39.573 17711 17711 E PPSSPP  : [COMMON] zeyuantest-----2222222222
[test2.log](https://github.com/hrydgard/ppsspp/files/10576210/test2.log)

**Comment by lvonasek** [comment]
What I see in the logs repeating is this:
```
02-03 14:37:43.021  1809  2048 E DynamicLog: TimeWarp.cpp::addHeuristicPredictData: LayerType:1 Heuristic a invalid predict dlt value : 9995594.000000 ms pred:9995593.832137 ms fetch:0.000000 ms
02-03 14:37:43.022 17711 17757 V OpenXR  : Stage bounds query failed: using small defaults
02-03 14:37:43.022 17711 17757 V OpenXR  : Stage bounds: width = 1.000000, depth 1.000000
```

The not working stage should be fine (just no 6DoF tracking) but the prediction time might be the reason for a black screen. Just for a test I would try in VRRenderer.cpp to modify somehow the frame prediction (that should remove the repeating error and it might enable rendering).

**Comment by chengzeyuan** [comment]
`02-03 14:37:43.021  1809  2048 E DynamicLog: TimeWarp.cpp::addHeuristicPredictData: LayerType:1 Heuristic a invalid predict dlt value : 9995594.000000 ms pred:9995593.832137 ms fetch:0.000000 ms
02-03 14:37:43.022 17711 17757 V OpenXR  : Stage bounds query failed: using small defaults
02-03 14:37:43.022 17711 17757 V OpenXR  : Stage bounds: width = 1.000000, depth 1.000000`
the logs repeating is this because the frame has not updated for a long time, and the earliest frame will be used. 
Confirmed, no frame is submitted during the whole black screen process.
And the prediction time is limited, if the prediction time is too long, the frame will be submitted normally.

**Comment by chengzeyuan** [comment]
@lvonasek @unknownbrackets Any other suggestions, or something to try to debug. I can provide more logs for debug.

**Comment by lvonasek** [comment]
I am out of ideas. Probably good to ask someone in the headset engineering team. What could go wrong there.

I fixed the Pico version so you have a working reference:
https://github.com/hrydgard/ppsspp/pull/16901

**Comment by lvonasek** [comment]
@chengzeyuan could you try it again with https://github.com/hrydgard/ppsspp/pull/17034 ?

Note that I changed the way the libopenxr is loaded to be able to have one APK for multiple platforms: https://github.com/hrydgard/ppsspp/pull/16936

**Comment by lvonasek** [comment]
@hrydgard I would consider closing this as not planned.

The requirement is that the headset supports the [official OpenXR SDK](https://github.com/KhronosGroup/OpenXR-SDK) and runs on Android 10 or higher.

AFAIK the @chengzeyuan's headset doesn't support the official SDK (the headset is using a custom XR loader).

Technically it would be possible to add a third-party loader but I would like to avoid it to prevent proprietary dependencies in the repository (and its licenses).
