### ISSUE TITLE
Tilt sensitive setting not work for D-pad and action keys

### ISSUE THREAD

**Issue by Narugakuruga** [hrydgard/ppsspp#16909]
### Game or games this happens in

Games that use D-pad or action keys for camera 

### What area of the game / PPSSPP

Tilt setting after the refactor 

### What should happen

If you set Y axis sensitive to 0. 
Up and down D-pad won't be triggered. 

### PPSSPP version affected

1.14.422 dev

https://user-images.githubusercontent.com/31060534/216792677-0b9d9e24-12ed-499a-aec5-dddec13f75b2.mp4

Last working 

https://user-images.githubusercontent.com/31060534/216792672-b99c20a3-bd21-4f79-b281-b565632a993c.mp4

**Comment by hrydgard** [comment]
Oh, that is weird. Might be that increasing the deadzone fixes this, not sure. But definitely needs fixing.
