### ISSUE TITLE
libretro compile so command

### ISSUE THREAD

**Issue by hsoftxl** [hrydgard/ppsspp#16913]
### Platform

libretro / Retroarch

### Compiler and build tool versions

ndk 21e

### Operating system version

ubuntu 20.04

### Build commands used

NDK21/ndk-buld

### What happens

build error.

https://buildbot.libretro.com/nightly/android/latest/arm64-v8a/ppsspp_libretro_android.so.zip
i want know how build this so.
what is command?

after add cpu-feature lib, ndk-build command is erro.   i want use another way to build libretro so.

### PPSSPP version affected

dd64fe8

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] Make sure to run `git submodule update --init --recursive` before building.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try deleting the build directory and running the build again.
- [ ] Check GitHub Actions, which builds every merge and PR.
- [ ] Include logs and help us reproduce.

**Comment by ANR2ME** [comment]
I also wondered why we're missing the Build instructions related to libretro at wiki :thinking: while at libretro repo (which seems to fall behind) is pointing the build instructions to our wiki https://github.com/libretro/ppsspp

**Comment by hrydgard** [comment]
I guess nobody wrote them down? Feel free to do so :)

**Comment by unknownbrackets** [comment]
What are the build commands you're using that are failing and worked before?  What directory do you run them in?

-[Unknown]

**Comment by hsoftxl** [comment]
i execute $NDK/ndk-build at  ppsspp/libretro/jni

it worked before.  at least 97b65156b01783336698ad0c767cc8c8b7f85343 is well.

**Comment by unknownbrackets** [comment]
Does #16918 help then?

-[Unknown]

**Comment by hsoftxl** [comment]
armeabi-v7a is ok.  but v8a not.



[armeabi-v7a] Install        : libretro.so => libs/armeabi-v7a/libretro.so

[arm64-v8a] SharedLibrary  : libretro.so

ld: error: relocation R_AARCH64_ADR_PREL_PG_HI21 cannot be used against symbol 'ff_h264_idct_dc_add_neon'; recompile with -fPIC

>>> defined in /home/xielei/ppsspp/libretro/jni/../../ffmpeg/android/arm64/lib/libavcodec.a(h264idct_neon.o)

>>> referenced by h264idct_neon.S:109 (libavcodec/aarch64/h264idct_neon.S:109)

>>>               h264idct_neon.o:(ff_h264_idct_add16_neon) in archive /home/xielei/ppsspp/libretro/jni/../../ffmpeg/android/arm64/lib/libavcodec.a



ld: error: relocation R_AARCH64_ADD_ABS_LO12_NC cannot be used against symbol 'ff_h264_idct_dc_add_neon'; recompile with -fPIC

>>> defined in /home/xielei/ppsspp/libretro/jni/../../ffmpeg/android/arm64/lib/libavcodec.a(h264idct_neon.o)

>>> referenced by h264idct_neon.S:109 (libavcodec/aarch64/h264idct_neon.S:109)

>>>               h264idct_neon.o:(ff_h264_idct_add16_neon) in archive /home/xielei/ppsspp/libretro/jni/../../ffmpeg/android/arm64/lib/libavcodec.a



ld: error: relocation R_AARCH64_ADR_PREL_PG_HI21 cannot be used against symbol 'ff_h264_idct_add_neon'; recompile with -fPIC

>>> defined in /home/xielei/ppsspp/libretro/jni/../../ffmpeg/android/arm64/lib/libavcodec.a(h264idct_neon.o)

>>> referenced by h264idct_neon.S:110 (libavcodec/aarch64/h264idct_neon.S:110)

>>>               h264idct_neon.o:(ff_h264_idct_add16_neon) in archive /home/xielei/ppsspp/libretro/jni/../../ffmpeg/android/arm64/lib/libavcodec.a



ld: error: relocation R_AARCH64_ADD_ABS_LO12_NC cannot be used against symbol 'ff_h264_idct_add_neon'; recompile with -fPIC

>>> defined in /home/xielei/ppsspp/libretro/jni/../../ffmpeg/android/arm64/lib/libavcodec.a(h264idct_neon.o)

**Comment by hsoftxl** [comment]
add  -fPIC , is same error

**Comment by hrydgard** [comment]
I'd suggest you try some commits and see what broke this. This is weird though, I thought our android 64-bit ffmpeg binaries were PIC already. Might need to rebuild them again...

**Comment by hsoftxl** [comment]
how to rebuild ffmpeg?

**Comment by hrydgard** [comment]
https://github.com/hrydgard/ppsspp-ffmpeg/blob/master/PPSSPP-README.md  see "new" underneath Windows in the file.

Every time I do this I tend to run into some new problem though :P

**Comment by hsoftxl** [comment]
i rebuild ffmpeg in ndk r25, compile sucess.  but when i use this lib.so in retro,  no video, 
i am finding why, do you have any idea? @hrydgard

**Comment by hsoftxl** [comment]
https://github.com/hrydgard/ppsspp/pull/16964

please help me, 
i don't know how to fix build script. 
thanks.

**Comment by hsoftxl** [comment]
it is work.
