### ISSUE TITLE
Shade Boost

### ISSUE THREAD

**Issue by Deka710** [hrydgard/ppsspp#16917]
### What should happen

hello,
out of curiousity its possible to implemented shade boost or whatever it called on PPSSPP?,
![Screenshot_2023-02-06-11-22-37-920_xyz aethersx2 android](https://user-images.githubusercontent.com/97207704/216883483-145e2f35-f14a-4e1f-a004-694baab4a57a.png)

### Who would this benefit

.

### Platform (if relevant)

None

### Games this would be useful in

the games that looks too dark u can adjust the brightness for example

### Other emulators or software with a similar feature

AetherSX2 and PCSX2

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by Gamemulatorer** [comment]
PPSSPP already have this feature please close this.
![Screenshot_20230206_132948_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37603562/216891079-4a506fb0-133f-4f13-b95e-631a4f6b76c0.jpg)

**Comment by Deka710** [comment]
> PPSSPP already have this feature just go to display layouts and effects > postprocessing shader > select color correction. ![Screenshot_20230206_132948_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37603562/216891079-4a506fb0-133f-4f13-b95e-631a4f6b76c0.jpg) You can close this now.

oh didnt know that, thanks!!!
