### ISSUE TITLE
Is asynchronous audio processing possible ?

### ISSUE THREAD

**Issue by GTAVCSFAN** [hrydgard/ppsspp#16920]
### What should happen

In order for the sound to be processed despite the speed of the game , then there may be no sound wheezing and it will be more pleasant to play

### Who would this benefit

Game sound improvement

### Platform (if relevant)

Windows

### Games this would be useful in

All Games

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
We had this in very early version of PPSSPP and it resulted in a lot of problems with games going out of sync in various ways.

I think an audio timestretching algorithm would be more appropriate to cover gaps in audio, although those can sound a bit weird and metallic. I find it more meaningful though to work on improving the overall performance of the emulator so the sound gaps won't happen as much. Though yes, we'll never fully get there on slower devices and an algorithm to cover gaps would indeed have some purpose.

**Comment by GTAVCSFAN** [comment]
> 

can you return this option to the new version as a separate item in the settings ?

**Comment by Gamemulatorer** [comment]
Duplicate https://github.com/hrydgard/ppsspp/issues/8412

**Comment by hrydgard** [comment]
Good catch, yes duplicate issue.
