### ISSUE TITLE
Direct 10 support ?

### ISSUE THREAD

**Issue by Gamer1hg** [hrydgard/ppsspp#16926]
### What should happen

Ppsspp support direct 10 and can you add this support ? 

### Who would this benefit

Players

### Platform (if relevant)

Windows

### Games this would be useful in

Games

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by Gamemulatorer** [comment]
https://forums.ppsspp.org/showthread.php?tid=21102

**Comment by hrydgard** [comment]
Adding additional backends is a huge amount of work to both add and maintain, and I don't think D3D10 would really add much value. So this will not happen, sorry.
