### ISSUE TITLE
UI font not rendering on Poco c40 phone

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#16931]
Reported through e-mail.

This is a weird one, never seen us have problems with this on any device with stock Android, which the reporter says it has.

![Screenshot_2023-02-07-23-36-44-951_org ppsspp ppsspp](https://user-images.githubusercontent.com/130929/217364779-931b7c81-b830-4c8f-97c3-2d43000a623b.jpg)

Very odd. Maybe we can detect this and fallback to atlas fonts, but this really shouldn't be happening,..

It's a Poco C40, with these specs:

![image](https://user-images.githubusercontent.com/130929/218317227-a43970a4-2a32-4778-80ce-ed3d2b24a83e.png)

Seems normal...

**Comment by unknownbrackets** [comment]
I suppose if we drew an A with the font drawer and all 0 bits, we could fall back to the atlas.

-[Unknown]

**Comment by hrydgard** [comment]
Sure, but it's an Android device, it can surely draw fonts. So I just don't get this ... Maybe it just can't load our .ttf for some reason?

**Comment by unknownbrackets** [comment]
I feel like it makes the flash on the device is acting up or something...

-[Unknown]

**Comment by Negan145** [comment]
edit ppsspp.ini
GraphicsBackend = 3 (VULKAN)
to
GraphicsBackend = 0 (OPENGL)

**Comment by hrydgard** [comment]
@Negan145 Does that really help?

I got another report of this, also on Poco C40.

**Comment by Negan145** [comment]
@hrydgard 5 months ago, someone posted on facebook group, same issue like this.
then, i searched what the problem is.

-
This is because the JR510 uses Google SwiftShader, a software tool to use the CPU for graphics rendering via a graphics library Volcano. The problem is that, being the CPU of the JR510 and therefore of POCO C40 definitely poco performing, any app or game that uses Vulkan libraries is likely to prove unusable.

And the anomalous is that the Mali-G52 GPU supports the Vulkan APIs, but Xiaomi or JLQ have decided not to implement them on the software side and prefer the Google tool instead.

source: gizchina
-

**Comment by hrydgard** [comment]
OK, I guess we need to reject Vulkan on this phone then. I'm not sure exactly how to best detect it. Maybe the string in System Name (Settings/Tools/System Information in PPSSPP) will be unique enough...

**Comment by hrydgard** [comment]
Keep getting reports of this. To make sure we get it right, I've ordered one of these devices to test on, not very expensive. So expect some kind of fix in the near future.

**Comment by hrydgard** [comment]
OK, I've got an affected device (C40) now, and can reproduce. OpenGL is fine, so how can it be ttf rendering? Turns out it's not.

So we have a bit of a discrepancy between our "VulkanLoader" which tried to detect eligible devices, and the actual choosing later. We initially reject SwiftShader, but if the shader backend is set to Vulkan, we still push ahead and create it anyway. Turns out it's not only a slow software driver which can just about play Cave Story, but also badly deficient in other ways:

```
02-27 23:18:10.248  4512  4761 E PPSSPP  : [G3D] VKDEBUG: ERROR(validation:-1094930823) Validation Error: [ VUID-VkImageCreateInfo-imageCreateMaxMipLevels-02251 ] Object 0: handle = 0xb400007b7e6cecc8, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xbebcae79 | vkCreateImage(): Format VK_FORMAT_R4G4B4A4_UNORM_PACK16 is not supported for this combination of parameters and VkGetPhysicalDeviceImageFormatProperties returned back VK_ERROR_FORMAT_NOT_SUPPORTED. The Vulkan spec states: Each of the following values (as described in Image Creation Limits) must not be
02-27 23:18:10.248  4512  4761 E PPSSPP  :  undefined : imageCreateMaxMipLevels, imageCreateMaxArrayLayers, imageCreateMaxExtent, and imageCreateSampleCounts (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkImageCreateInfo-imageCreateMaxMipLevels-02251)
```

So yeah, that's not great. It does seem we might not be properly checking for the R4G4B4A4 format (though I thought we did already for MoltenVK?), but we also should simply not decide to use Vulkan in this case.

Will fix both issues.

**Comment by unknownbrackets** [comment]
That's terrible.  I suppose it's useful to at least allow Debug to use software.  I have seen reports including SwiftShader... let's see if it's any other phones so far.

Some stats:
 * There are 12 game playability reports, Android and Windows.  Some of the Windows ones are rated positively, but the Android ones are all poor marks.
 * Some of the reports are with a JLQ JR510, which is the one mentioned here.  Everything else is Intel, and clearly older devices lacking AVX and often lacking SSE4.
 * Vulkan, GLES (ANGLE), and Direct3D are all represented in Swiftshader reports.
 * Logs have been reported for 125 games with Swiftshader in use, 842 total reports (that's not that many.)
 * Most of the reports look like Direct3D.

-[Unknown]
