### ISSUE TITLE
Regression in Outrun's environment mapping, assert hit

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#16941]
Outrun builds a sphere map by first drawing most of a cube map and then converting to a sphere map which PSP's env map can handle. The middle map seems to get stuck with some noise, which isn't very pretty.

There's also an assert that we hit, the new FB_USAGE_COLOR_MIXED_DEPTH flag prevents downsizing buffers but not completely, this fails for example:

```
			if (vfb->usageFlags & FB_USAGE_COLOR_MIXED_DEPTH) {
				ResizeFramebufFBO(vfb, vfb->width, vfb->height, true);
				_assert_(vfb->renderScaleFactor != 1);
			}
```

We hit the assert since Resize ends up its force1x path, so the image remains 1x after the resize, hitting the assert.

In this case, it's about a 64x64 texture, and FB_USAGE_COLOR_MIXED_DEPTH comes from DrawPixels with channel == DEPTH, which happens on the first frame for this texture due to lack of clearing it seems. There's no actual color/depth mixed usage going on.

Here's where the code was added that sets FB_USAGE_COLOR_MIXED_DEPTH: 

https://github.com/hrydgard/ppsspp/commit/e5d67119a8#diff-66fdbd9653ac45b624beb6fb8f2259fc5a13b83a25f48a89383145cafd58ba43R1155

I guess that's needed for the Burnout lens flare effect...

**Comment by unknownbrackets** [comment]
Well, this is caused by #16908 because it made the assert stop passing.  The goal of that assert was to ensure we're not needlessly resizing the framebuffer all the time, so it's a good thing it tripped.

-[Unknown]

**Comment by hrydgard** [comment]
Oh yeah, good point that the assert did catch something really undesirable!

**Comment by hrydgard** [comment]
The garbage in the environment map is because of some noise that the depth buffer of it (which it makes no use of, but tests against with GREATER_EQUAL, probably a bug) gets initialized with. The Z and W of the vertices are all set to 1, so would figure it would pass but it doesn't... It looks like it's using a compressed depth range (ACCURATE_DEPTH style), but the depth buffer initialization doesn't use it. So that's a bug - if the depth noise was in the correct range, it would work, so that's what we should fix.

**Comment by hrydgard** [comment]
#16947 will fix it once finished.

**Comment by hrydgard** [comment]
Actually, this is at least superficially fine now with clearing, so I'm closing this specific issue. A depth calculation cleanup is coming.
