### ISSUE TITLE
iOS Libretro core seems capped at 45 FPS

### ISSUE THREAD

**Issue by trotsky40** [hrydgard/ppsspp#16940]
### Game or games this happens in

Jetpack Joyride (PSP Minis)

### What area of the game

The new iOS core seems to be limited to 45FPS. Tested in several game (Tekken 6, God of War Ghost of Sparta) and see the same behavior. In Tekken and GOW, this did not cause issues with the game but in Jetpack Joyride it causes pacing issues (small freezes in the graphics). Same behavior is not observed with the standalone. Used Vulkan graphics for both and all other settings default (standalone and core)

### Platform

iOS

### Mobile phone model or graphics card

iPad Pro M2 (2022 model)

### PPSSPP version affected

v1.14.4-608-g9b86000 (version from libretro core)

### Last working version

N/A

### Graphics backend (3D API)

Vulkan

### Any other notes or things you've tried

I adjusted all of the exposed setting in the libretro core and none improved the frame rate. Interestingly, turning the resolution up did not further impact the frame rate. I was able to maintain the 45 FPS at 1920x1088 on Tekken and GOW, so doesn't appear to be a device/hardware limitation. 

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the slowdown.
- [X] Include logs or screenshots of issue.

**Comment by trotsky40** [comment]
Standalone screenshot
![IMG_1642](https://user-images.githubusercontent.com/25250513/217668954-2f177025-fc0d-49cc-8650-0330470d53cf.PNG)

**Comment by trotsky40** [comment]
Libretro core screenshot
![IMG_1643](https://user-images.githubusercontent.com/25250513/217669048-150400dd-dcdf-4961-8959-6d3fe81fdb63.PNG)

**Comment by hunter1026** [comment]
im also running the same core on ios and can confirm it lags on retroarch but on the standalone ppsspp app it runs smoothly.

**Comment by trotsky40** [comment]
Resolved by: https://github.com/hrydgard/ppsspp/commit/58174e9aef1666c52e32b4576379101c5145dcfe
