### ISSUE TITLE
Starry Sky - disappearing music

### ISSUE THREAD

**Issue by pinkie14** [hrydgard/ppsspp#16950]
### Game or games this happens in

ULJM05683 - Starry Sky In Spring Portable and the rest of Starry Sky games

### What area of the game / PPSSPP

after a few minutes the music starts glitching and turns off until the music track changes. voices work as they should

### What should happen

the music should play without breaks until the music track changes

### Logs

![image](https://user-images.githubusercontent.com/45291085/218266063-d50d4570-48f4-4035-a0db-2499555aa52f.png)
can't find debuglog.bat so here's a screenshot

### Platform

Windows

### Mobile phone model or graphics card

NVIDIA GeForce 920M

### PPSSPP version affected

v1.14.4

### Graphics backend (3D API)

Direct3D 9

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by sum2012** [comment]
@pinkie14 
Please test latest version in https://buildbot.orphis.net/ppsspp/
I have fixed a scempeg problem in #16765

**Comment by sum2012** [comment]
@pinkie14 sorry, it should be atrac problem more like to mpeg problem

**Comment by sum2012** [comment]
@pinkie14 where do the music have problem ? I test in the beginning no problem

**Comment by pinkie14** [comment]
@sum2012 any scene in the game - just wait for a few minutes. for example, any time the characters are in class

**Comment by pinkie14** [comment]
tested it in the latest git build again. everything works fine now. thank you so much ^___^

**Comment by hrydgard** [comment]
Interesting, not sure what recent change could have fixed it. But I'll take it. Closing.
