### ISSUE TITLE
The PPSSPP folder doesn’t show up on my files ios 15.4.1

### ISSUE THREAD

**Issue by Ward777** [hrydgard/ppsspp#16956]
### Game or games this happens in

None

### What area of the game / PPSSPP

When I instill PPSSPP with Trollstore 1.5.0, the PPSSPP folder doesn’t appear on my files app. I can see it on iTunes, but I cannot import any files. There is a loading sign on iTunes. Also, when I change the setting of PPSSPP, it cannot be saved.

![PPSSPP ISSUE](https://user-images.githubusercontent.com/107338890/218343412-b9d6760c-4d8c-4560-87bd-40cc62f1907f.png)

I also tried the previous PPSSPP version, but the issue was repeated. 
Moreover, when I try to download Homebrew games from Homebrew & Demos to see if that could help to make the PPSSPP folder show up, the grams cannot be instilled. 

### What should happen

When I clicked the folder icon from the PPSSPP home screen, the app crashed.

### Platform

iOS 15.4.1

### Mobile phone model or graphics card

iPhone XR

### PPSSPP version affected

v1.14.521-g2d0252feb

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by Ward777** [comment]
Just tested it, this problem could be solved by using Certificates. But still wondering how to solve this issue when the app is installed with trollstore.

**Comment by ANR2ME** [comment]
May be newer iOS is just being stricter, is this issue also occurred on older iOS version?

**Comment by Ward777** [comment]
> May be newer iOS is just being stricter, is this issue also occurred on older iOS version?

I remember clearly that there was no issue on ios 15.3 or 15.3.1 (same device; installed via older trollstore version). However, due to lack of storage space, I had to delete it.

**Comment by Halo-Michael** [comment]
It's not PPSSPP's bug. TrollStore will load apps as "system app", which won't show files up in iTunes, or preferences in Settings. you guys can close this thread.

**Comment by Ward777** [comment]
> It's not PPSSPP's bug. TrollStore will load apps as "system app", which won't show files up in iTunes, or preferences in Settings. you guys can close this thread.

The Delta emulator works perfectly under the same situation.

**Comment by Halo-Michael** [comment]
> > It's not PPSSPP's bug. TrollStore will load apps as "system app", which won't show files up in iTunes, or preferences in Settings. you guys can close this thread.
> 
> The Delta emulator works perfectly under the same situation.

TrollStore installed PPSSPP is unsandboxed, which save files in /var/mobile/Documents, iTunes can't write in.
