### ISSUE TITLE
Please tell me how to use theme feature in ppsspp 1.14.4

### ISSUE THREAD

**Issue by SohamRoy20Gaming** [hrydgard/ppsspp#16977]
### What *should* happen? 
Please tell me how to use theme feature in ppsspp 1.14.4

### What are you using? 
Mobile

#### What hardware / device and operating system?
Operating System :- Android 7.1.1

#### What graphics card (GPU) or mobile phone model? 
Moto E4 Plus

#### Checklist

 - [ ] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [ ] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [ ] Try resetting settings or older versions and include if the issue is related.
 - [x] Include logs or screenshots of issue.

**Comment by SohamRoy20Gaming** [comment]
![Screenshot_20230217-130154](https://user-images.githubusercontent.com/109818645/219579317-3f2b8326-784e-45a0-bca7-2d0946680bc6.png)

**Comment by Gamemulatorer** [comment]
Better ask this on discord or read here https://github.com/hrydgard/ppsspp/pull/15394

**Comment by SohamRoy20Gaming** [comment]
But, please tell me how to use that ?

**Comment by Gamemulatorer** [comment]
> But, please tell me how to use that ?

https://github.com/hrydgard/ppsspp/pull/15394#issuecomment-1042835691

**Comment by SohamRoy20Gaming** [comment]
Thanks @Gamemulatorer for this
