### ISSUE TITLE
Add some fun little Easter Eggs

### ISSUE THREAD

**Issue by jistjak** [hrydgard/ppsspp#16979]
### What should happen

Maybe start a tiny game (ie PONG) or show a joke or do whatever your imagination can come up with when say like idk I rapidly press a crtain button 5 times in settings or somewhere else. Or some other not so obvious criteria ie 1 in 1000 chance check at startup.

some ideas for you:
- the tiny pong game idea (it's tiny so it doesn't affect system requirements)
- Ponder the intention of the domesticated jungle-fowl on the act of cross-transitioning the paved foundation for which a box for the conveyance of people and objects may utilize. Then render forth a statement that adequately encompasses the resulting outcome of the previous statement.
- why did the chicken cross the road?
- A tiny game that uses A.I. to auto-generate game maps, objectives, NPCs, music, dialog, and everything else a game needs so we never run out of game to play. LOL just kidding.
- subtly change the floating O [] X /\ to something sneaky in the background ie. like put a ;) inside one of the O on rare occasions.

### Who would this benefit

No one really, it'll be just a fun thing to eventually stumble across. or kinda reward those who at least look  the code. or spoil depending on if they prefer to have found it the legitimate way.

### Platform (if relevant)

None

### Games this would be useful in

main menu

### Other emulators or software with a similar feature

idk. maybe the android os itself. Lolipop had a hidden minigame within the settings if you tap android version rapidly. Other versions also included easter eggs but lolipop was the best. all others were lame.

BTW one of the checkboxes says check latest git if it's already implemented. well since E.Eggs are naturally obscure I dont know if that's really feasible for me. Sorry I couldn't scour over many KLOC's for something hidden. So if you have eggs already then just close me with a note that says they exist so others can see if they exist when they search "Easter Eggs"

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
I think easter eggs are fun too, but not as fun in open source software since they're so easy to find. I'm not saying I won't add any, maybe I will, but having an issue open about adding them also doesn't feel very easter-egg-like :)  So I'm gonna close this.
