### ISSUE TITLE
[Request] PCSX2's Debugger features in PPSSPP

### ISSUE THREAD

**Issue by Scalerize** [hrydgard/ppsspp#16975]
### What should happen

The debugger is nice, but honestly it's missing some features that PCSX2 has that i consider highly valuable.

And that includes:

1. a "Go to address" Button in the mouse's right click just like PCSX2 does as that'll be more beneficial to me than what we currently have.

2. a "Nop selected addresses" Button in the mouse's right click just like PCSX2.

3. When you select more than one address it should copy all of them when you select the "Copy address" option rather than just the first one.
### Who would this benefit

Modders, Developers, Individuals like me who love to create patches, you name it.

### Platform (if relevant)

Windows

### Games this would be useful in

/

### Other emulators or software with a similar feature

PCSX2

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
You are very welcome to add these, a PR will be accepted. Should be pretty easy!

Alternatively I'll add these when I get around to it..

**Comment by hrydgard** [comment]
Implemented 2 and 3.

As for 1, you can just write your address in this box and press Enter, don't see why a right click option would be better.

![image](https://user-images.githubusercontent.com/130929/222442425-3886718b-9880-41c1-aefa-8527d55be415.png)

**Comment by Scalerize** [comment]
> Implemented 2 and 3.
> 
> As for 1, you can just write your address in this box and press Enter, don't see why a right click option would be better.
> 
> ![image](https://user-images.githubusercontent.com/130929/222442425-3886718b-9880-41c1-aefa-8527d55be415.png)

Good enough for me! Thank you so much!
