### ISSUE TITLE
Android: Landscape Improvement

### ISSUE THREAD

**Issue by soundsnow** [hrydgard/ppsspp#16985]
Move Logo, Credit, Load, Setting, Exit to Top Area of Screen
![image85](https://user-images.githubusercontent.com/109885044/219990488-6e2045ba-73a2-4d19-a308-6a509e7f1eb0.png)

**Comment by soundsnow** [comment]
![image86](https://user-images.githubusercontent.com/109885044/219997369-0193ef9f-be23-414f-887c-0cb71702c402.png)

**Comment by Gamemulatorer** [comment]
This is technically the same as https://github.com/hrydgard/ppsspp/issues/16789?!

**Comment by hrydgard** [comment]
I don't think this is better in any way. On touchscreens, in landscape, it's much easier to reach the sides of the screen than the top, unless you're holding the phone in some really strange way. No plans for this.
