### ISSUE TITLE
What doing new function GPU skip read back?

### ISSUE THREAD

**Issue by Gamer1hg** [hrydgard/ppsspp#16980]
### What should happen

Please answer to question

### Who would this benefit

Me

### Platform (if relevant)

Windows

### Games this would be useful in

Games

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by Gamemulatorer** [comment]
You can close this now
See >> https://github.com/hrydgard/ppsspp-site/commit/5322e4e852069065696cd8fc9d5a2f1f7682de85#commitcomment-101102717

**Comment by hrydgard** [comment]
See https://www.ppsspp.org/docs/reference/settings .
