### ISSUE TITLE
New crashing issue on M1 Macs

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#16986]
See the last comments to #16376 .

**Comment by unknownbrackets** [comment]
By the way, I recently saw a git build (fairly recent, newer than 1.14.4 at least) running fine on M2.  That said, Vulkan (MoltenVK) for some reason did not run well (seemed to be force capped at the monitor Hz, which was 50 Hz for some reason.)  At the same time I was able to see if it worked on a recent iOS device, which it did - but only GL.  Vulkan just crashed.

Didn't do any debugging but may be a reference datapoint.

Also the software renderer ran decently well on the M2 (achieved full speed in at least one game, fairly comfortably.)

-[Unknown]

**Comment by hrydgard** [comment]
Hm, with https://github.com/hrydgard/ppsspp/commit/bec429ed72049c8e2aba8842ac155c7cc77024d9 in (some linker error, maybe only in debug mode), I can make a fresh build and it seems to be running just fine on my M1, which now runs Ventura 13.2.1.

**Comment by unknownbrackets** [comment]
Yeah, I think that linker error was why they were just constants in the cpp before.

-[Unknown]

**Comment by hrydgard** [comment]
@jacksonbenete and @DerinHalil from #16376, do you see a crash in the very latest Mac builds? I don't..

**Comment by hrydgard** [comment]
I dunno what to do about this, can't repro...

**Comment by jacksonbenete** [comment]
Sorry about that, I wasn't around for those last weeks.
Let me try the latest build and I'll get back to you.

**Comment by jacksonbenete** [comment]
I just compiled from the latest version on master branch.
```
const char *PPSSPP_GIT_VERSION = "v1.14.4-766-g625d93a2a";
```

Building using a M1, on Ventura 13.2.1 (22D68)
Works for me. :)

**Comment by hrydgard** [comment]
Aight, gonna go ahead and close.
