### ISSUE TITLE
Patapon 3, texture replacement regression

### ISSUE THREAD

**Issue by TehPlayer14** [hrydgard/ppsspp#16991]
### Game or games this happens in

UCES1421

### What area of the game / PPSSPP

Tested on both 1.14.4 and 1.14.6+git 617

Textures get incorrectly replaced/glitched or are straight up missing

During normal gameplay, occurs more often if used with increased emulation speed/fast forward 

### What should happen

Texture should be replaced correctly

### Platform

Windows

### Mobile phone model or graphics card

GTX 980

### PPSSPP version affected

1.14.4, 1.14.4+617

### Last working version

1.10.3

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [x] Try resetting settings or older versions and include if the issue is related.
- [x] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by TehPlayer14** [comment]
> Got a link to the texture replacement pack that you used?

It can be downloaded here, https://forums.ppsspp.org/showthread.php?tid=26747 (Note only uptobox link works: https://uptobox.com/ihr47sc5iin9)

**Comment by efonte** [comment]
I have updated the gdrive link (I don't know how long the link will be online as I have it uploaded on a shared drive)

**Comment by TehPlayer14** [comment]
> I have updated the gdrive link (I don't know how long the link will be online as I have it uploaded on a shared drive)

Thank you

**Comment by TehPlayer14** [comment]
![obraz](https://user-images.githubusercontent.com/7756773/222465876-eec0b374-459c-4066-851a-bb05f645cba7.png)
This can sometimes get as bad as this but basically yeah wrong replace or invisible texture

**Comment by hrydgard** [comment]
Yeah, something is clearly not right heh.

**Comment by hrydgard** [comment]
I'm gonna assume this is the same as #16966 , let's move any further discussion there.
