### ISSUE TITLE
Games show black screen on iOS

### ISSUE THREAD

**Issue by IceKareemCheese** [hrydgard/ppsspp#17005]
### Game or games this happens in

NPJH-50494/NPJH-50475/NPJH-50465/NPJH-00039/NPJH-00040

### What area of the game / PPSSPP

On the main menu.

### What should happen

After launching a game, there isn't anything shown, but the audio and controls work. I have tried editing and resetting all my settings, but nothing has worked.

### Logs

https://user-images.githubusercontent.com/125942904/221380081-ea3c41b8-2f33-40b2-8692-c1886df2ec82.MOV

### Platform

iOS

### Mobile phone model or graphics card

iPhone 14 Pro (MQ1D3LL/A)

### PPSSPP version affected

v1.14.4-648-g59236dc71/v1.14.4-668-g3e942f6b7

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [x] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Does switching backend to OpenGL help?

**Comment by IceKareemCheese** [comment]
All backends don’t work

**Comment by ANR2ME** [comment]
Is this a regression that worked before? or may be corrupted iso (if it never worked)?

Are you using JIT or IR? if you're using JIT try changing it to IR interpreter.

**Comment by IceKareemCheese** [comment]
I'm not sure about the first question since this is my first time trying it on my iPhone. I noticed that when I looked at the IPA page on my iPhone, it seemed like a new version released after I already downloaded it on my computer and installed it, so that's why I listed two versions because both haven't worked. I checked all the ISO CRCs and they match with other ones so they're not corrupted. I'm using the IR interpreter and software rendering didn't work either.

**Comment by unknownbrackets** [comment]
That's weird, I saw a recent build working just fine on an iPhone (installed via macOS compile + Xcode, no trollstore/altstore/jailbreak/etc.)  However, Vulkan/MoltenVK was not working.

I wonder if this is only an issue with the builds someone has produced, or if this issue happens only with certain installation methods.

-[Unknown]

**Comment by IceKareemCheese** [comment]
I installed the latest build and this seems to be fixed now, both Vulkan and OpenGL work, thank you everyone.
