### ISSUE TITLE
Could support the "Buffer graphics commands" setting for D3D11

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#17009]
Turns out there's actually a function to set it for D3D11 through DXGI, `SetMaximumFrameLatency`. Might require some checks as it's not supported on all Windows versions that we support.

https://learn.microsoft.com/en-us/windows/win32/api/dxgi/nf-dxgi-idxgidevice1-setmaximumframelatency

**Comment by ANR2ME** [comment]
The minimum seems to be Windows Vista with Service Pack 2 (SP2) instead of Win7 based on the remarks.

> This method is not supported by DXGI 1.0, which shipped in Windows Vista and Windows Server 2008. DXGI 1.1 support is required, which is available on Windows 7, Windows Server 2008 R2, and as an update to Windows Vista with Service Pack 2 (SP2) ([KB 971644](https://support.microsoft.com/topic/application-compatibility-update-for-windows-vista-windows-server-2008-windows-7-and-windows-server-2008-r2-february-2010-3eb7848b-9a76-85fe-98d0-729e3827ea60)) and Windows Server 2008 ([KB 971512](https://support.microsoft.com/kb/971512/)).
