### ISSUE TITLE
White Knight Chronicles: Strange transform issues

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#17019]
https://user-images.githubusercontent.com/130929/221592539-5d9a94d1-97bf-4a7f-b692-56392420ad7d.mp4

Supposed to look like:

https://cdn.discordapp.com/attachments/480103153803460614/1079739527154901113/Screenrecording_20230227_201652.mp4 

This doesn't quite look right.

Not sure if it only happens on Android / ARM64 or also on x86-64 and so on...

**Comment by unknownbrackets** [comment]
Duplicate of #10979.

-[Unknown]

**Comment by hrydgard** [comment]
Ah, didn't find that with the new GitHub search (beta feature). It seems kinda meh.
