### ISSUE TITLE
Should add a compat.ini setting for games that do EQUAL depth tests but don't rely on it

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#17014]
Automatically switching to lower depth buffer resolution when we detect games using EQUAL (or LEQUAL/GEQUAL) depth testing (`everUsedExactEqualDepth_`) has caused some flickering to appear in a few games, like Outrun and Cars. This flickering also happens on the real PSP, but is absent when we allow high precision depth, while not breaking anything.

So a compat.ini setting for these seems appropriate.

Reported by Gσиzαlσ on Discord (though I've seen it too, adding this as a reminder).

**Comment by unknownbrackets** [comment]
What equal tests are these games using?  Is it only equal zero or something that maybe we could adjust the heuristic for?  Equal zero/one is a bit dangerous, but the most important ones are the ones in between.

-[Unknown]

**Comment by hrydgard** [comment]
Just regular GEQUAL ( >= ) when drawing 3D geometry, testing against other 3D geometry, as far as I've seen.

**Comment by unknownbrackets** [comment]
Ah, well there are two things here.

 * If we see an exact equal (==), then we switch to lower resolution depth.  This only happens for exact equal, not for NOTEQUAL or GEQUAL or etc.
 * If we see an equal-ish compare (==, >=, <=, !=) we force clears to use triangles instead of real clears, so the depth values match more exactly.

If the game is ONLY using GEQUAL, it should never trigger lower precision depth.  So either it's not being triggered, or there is an actual exact equal.

https://github.com/hrydgard/ppsspp/blob/a18b7a8d38830a3644d688412beb617fc58ec0d2/GPU/Common/DrawEngineCommon.h#L158-L174

-[Unknown]

**Comment by hrydgard** [comment]
Oh, right. I guess they are using EQUAL somewhere too, then. Forgot that the heuristic distinguishes between Exact and not.

**Comment by hrydgard** [comment]
Alright, Outrun is using DepthEqual early in the frame while rendering some shadow overlay onto asphalt. Seems pointless, but also, the geometry is exactly the same as in the previous draw calls, so the rounding is not needed, as the depths will match exactly. So quite hard to make a reliable heuristic here...

**Comment by Goblan** [comment]
> Alright, Outrun is using DepthEqual early in the frame while rendering some shadow overlay onto asphalt. Seems pointless, but also, the geometry is exactly the same as in the previous draw calls, so the rounding is not needed, as the depths will match exactly. So quite hard to make a reliable heuristic here...

If it's of any use, Split Second is another game with this issue (apart from Test Drive Unlimited and Outrun)

**Comment by unknownbrackets** [comment]
> Alright, Outrun is using DepthEqual early in the frame while rendering some shadow overlay onto asphalt. Seems pointless, but also, the geometry is exactly the same as in the previous draw calls, so the rounding is not needed, as the depths will match exactly. So quite hard to make a reliable heuristic here...

Well, I'm not against a flag if we know some games are fine without.  Although I hope there's not some snowy area or something that behaves differently.

Also you have more trust in graphics drivers than me.  I would be slightly impressed and mildly surprised if, say, PowerVR drivers accurately produced the same depth values between two draws with different, I don't know, alpha blending options and identical geometry and everything else.  But perhaps I'm just a cynic in this regard.

-[Unknown]
