### ISSUE TITLE
[cpu_features] Needs set EXCLUDE_FROM_ALL

### ISSUE THREAD

**Issue by sl1pkn07** [hrydgard/ppsspp#17010]
Hi

https://github.com/hrydgard/ppsspp/blob/e685dc910ff325393102745eb610538632899581/ext/CMakeLists.txt#L25

if not, cpu_features is installed when doing `make install` / `cmake --install foo`

greetings

**Comment by hrydgard** [comment]
Hm, can you clarify the actual change we need to make?
