### ISSUE TITLE
DAXTER crash in softgpu, when frameskip is enabled

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#17021]
### Game or games this happens in

NPUG80329

### What area of the game / PPSSPP

After loading rom

### What should happen

Don't crash

### Logs

![1](https://user-images.githubusercontent.com/2177532/221685517-e07fe4b7-86b6-4aba-b98a-053995671488.png)
![2](https://user-images.githubusercontent.com/2177532/221685539-a507af0e-47f8-4075-80df-757e7959448b.png)

### Platform

Windows

### Mobile phone model or graphics card

Nvidia Geforce 710

### PPSSPP version affected

v1.14.4-690-g2dc3a6b05-windows-amd64

### Last working version

None

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
I can't reproduce in other games - this is a bit strange.  Can you try a Solution -> Clean, and then build again?  Sometimes after refactoring, things get messed up.

Doe sit happen in any other games?

-[Unknown]

**Comment by sum2012** [comment]
Yes,I try rebuild same,I forget another line of useful of crash trace.
I tested 20 games,only this game crash
![3](https://user-images.githubusercontent.com/2177532/221871242-8d3a6854-d7a9-4725-b269-697614d0621d.png)

> I can't reproduce in other games - this is a bit strange. Can you try a Solution -> Clean, and then build again? Sometimes after refactoring, things get messed up.
> 
> Doe sit happen in any other games?
> 
> -[Unknown]

1

**Comment by sum2012** [comment]
@hrydgard 
frame skip 1 to 9
frame skip type:both type

**Comment by hrydgard** [comment]
Yup, that does blow up immediately. Weird!

(Though frameskipping with the software renderer is kind of a weird combination, given how the software renderer is focused on accuracy, and skipping stuff certainly isn't accurate, and can break things... Maybe we shouldn't allow it)

**Comment by hrydgard** [comment]
Heh, some .. interesting memory corruption is happening.

This is the SoftGPU object viewed in the debugger:
![image](https://user-images.githubusercontent.com/130929/221992388-1b239880-6c70-4e59-8031-4da6270533f5.png)


Something overwrote a whole bunch of pointers with 0303030303...

**Comment by hrydgard** [comment]
It's the memset in SoftGPU::MarkDirty, for whatever reason it stomps outside the vramDirty_ array:

![image](https://user-images.githubusercontent.com/130929/221993083-bff70602-7e4b-4dd8-87b9-2f2006ae040d.png)

It's only 2048 bytes long, but it writes 2048 bytes into it at an offset of 560.

**Comment by sum2012** [comment]
Thanks @hrydgard
