### ISSUE TITLE
CpuCore choose issues

### ISSUE THREAD

**Issue by Halo-Michael** [hrydgard/ppsspp#17025]
### Game or games this happens in

*

### What area of the game / PPSSPP

When Set CpuCore to JIT once, CpuCore will force lock to IRJIT when reboot PPSSPP. but ppsspp.ini will always host CPUCore as 1(That means CpuCore is hosted as JIT). In this status, I can't even switch CpuCore to INTERPRETER.
When Set CPUCore=2 or CPUCore=0 in ppsspp.ini, everything works fine again.

https://user-images.githubusercontent.com/45062120/221879340-2ae7942f-a92a-4b65-87cd-8dbe7fe872d6.mp4

### What should happen

*

### Logs

*

### Platform

iOS

### Mobile phone model or graphics card

*

### PPSSPP version affected

v1.14.4-698-g23fd9907e

### Last working version

*

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by Gamemulatorer** [comment]
See https://github.com/hrydgard/ppsspp/pull/16925

**Comment by sum2012** [comment]
According the comment 
https://github.com/hrydgard/ppsspp/pull/17026#issuecomment-1448645383 
Can close it ?
