### ISSUE TITLE
Gran Turismo 7

### ISSUE THREAD

**Issue by Adilabdh** [hrydgard/ppsspp#17029]
With over 420 cars available at Brand Central* and the Used Car Dealership* from day one, Gran Turismo 7 recreates the look and feel of classic motors and bleeding-edge supercars alike in unparalleled detail. Each car handles differently and feels unique as you navigate over 90 track routes in dynamic weather conditions, including classic courses from GT history.

 https://play.google.com/store/apps/details?id=ps5.games.simulator.android

**Comment by hrydgard** [comment]
What's this garbage and how the hell did it get on the play store? Not relevant, closing.
