### ISSUE TITLE
Android App Icon Colors

### ISSUE THREAD

**Issue by soundsnow** [hrydgard/ppsspp#17037]
Android 12: you can change wallpaper, OS will auto-detect its color
Android 13: you can pick your favorite colors
Android 14: I don't have any device installed Android 14

![image116](https://user-images.githubusercontent.com/109885044/222360865-82a2786d-eef5-48d2-91c1-d6c40dee5780.png)

**Comment by Gamemulatorer** [comment]
Duplicate https://github.com/hrydgard/ppsspp/issues/11996?

**Comment by Gamemulatorer** [comment]
Duplicate https://github.com/hrydgard/ppsspp/issues/11996?

**Comment by hrydgard** [comment]
yes, closing
