### ISSUE TITLE
Dante's Inferno FMV cut sound issue

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#17058]
### What should happen

No cut sound during fmv

https://user-images.githubusercontent.com/37603562/223079952-1f59604b-5628-4bdc-a439-7d7ec3ba6963.mp4

Cannot reproduce this in playstore version.

### Who would this benefit

Everyone.

### Platform (if relevant)

Android

### Games this would be useful in

ULUS10469

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by Panderner** [comment]
@Gamemulatorer last build work?

**Comment by Gamemulatorer** [comment]
> @Gamemulatorer last build work?

I don't know what build is the last working but I'm using the recently build https://github.com/hrydgard/ppsspp/commit/ebd8a639147c1157a653b78de1a6b4cb6f2aad9b

**Comment by hrydgard** [comment]
Would help a lot if you could try some builds in between to see when it broke...

**Comment by Gamemulatorer** [comment]
> Would help a lot if you could try some builds in between to see when it broke...

Will try later.

**Comment by sum2012** [comment]
@Gamemulatorer 
You can go to 
https://www.ppsspp.org/download  click  "Previous releases" to see older build

**Comment by Gamemulatorer** [comment]
Closing this because the issue is related to 30fps cheat code that I use before saving this ingame.
