### ISSUE TITLE
[Feature Request] [Hack] Add option to force skip fmv

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#17059]
### What should happen

I'd like to add option in PPSSPP to skip fmv to avoid waiting for some long cutscenes:/
Just like a cheat in Naruto Ultimate Heroes 3 https://github.com/hrydgard/ppsspp/issues/9591#issuecomment-313239145

### Who would this benefit

Everyone who don't want to watch long cutscenes or this might help some games that crashes during cutscenes 🙂

### Platform (if relevant)

None

### Games this would be useful in

All

### Other emulators or software with a similar feature

Citra mmj?

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by ANR2ME** [comment]
Just like cheats, this is probably going to be game-specific, or as part of compat.ini if there is a way to make the skipping code to be general (there might be some games that could breaks when skipped improperly tho)

Meanwhile, fast forward can be used in general cases (and safer too), although can't be called skipping.

**Comment by hrydgard** [comment]
Yeah, I don't think this is a good idea. It might be possible to trick many games that the video is over, but it's quite risky to subvert their logic like this, and could lead to very hard-to-diagnose misbehaviors.

So, as ANR2ME says, fast-forward is gonna remain the best way to get past videos quickly.

**Comment by iota97** [comment]
There was some more dangerous but faster frameskipping technique who got set off as default if I don't miss remember. It could be possible to have a option to use them during video detecting them like post shaders do?

Probably more harm than good even if this can be done tho' :)

Even stop frameskipping at videos end might be a cool feature to not over skip anything...
