### ISSUE TITLE
Add teleport option to VR build for locomotion so not to become sick

### ISSUE THREAD

**Issue by necros2k7** [hrydgard/ppsspp#17051]
### What should happen

Add teleport option to VR build for locomotion so not to become sick

### Who would this benefit

VR build users

### Platform (if relevant)

Android

### Games this would be useful in

Medievil Resurrection, almost any 3D game

### Other emulators or software with a similar feature

Don`t know

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by lvonasek** [comment]
That's technically impossible.

**Comment by necros2k7** [comment]
Maybe as a workaround increase inner game cycles during locomotion to boost time? Like in NES, SNES emulators?

**Comment by lvonasek** [comment]
Nope, it would lead to a huge lag and you would end on a different position than you choose.
