### ISSUE TITLE
Where are Layout.xml and buttons XML files located, As I want to modify to give a modern fresh look

### ISSUE THREAD

**Issue by Hidte09** [hrydgard/ppsspp#17066]
### Platform

None

### Compiler and build tool versions

Clang+cmake in Android studio 

### Operating system version

Windows 10

### Build commands used

-

### What happens

Couldn't able to find Ui or display layout XML files and button icons, I want to give buttons fresh and moder look for seamless user experience, but couldn't able find those layout files and buttons 

### PPSSPP version affected

V1.14.4

### Last working version

V1.14.1

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] Make sure to run `git submodule update --init --recursive` before building.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try deleting the build directory and running the build again.
- [ ] Check GitHub Actions, which builds every merge and PR.
- [ ] Include logs and help us reproduce.

**Comment by hrydgard** [comment]
There aren't any, PPSSPP's UI is coded in C++ directly.

If you have ideas for design improvements, please feel free to make mockup screenshots and post them here - no guarantee they'll be implemented, but ideas are always welcome.
