### ISSUE TITLE
Setup Orphis' Buildbot for VR builds

### ISSUE THREAD

**Issue by necros2k7** [hrydgard/ppsspp#17065]
@hrydgard , @Ivonasek
### What should happen

Add dev VR builds to Buildbot

### Who would this benefit

VR community

### Platform (if relevant)

Android

### Games this would be useful in

Medievil Resurrection,Motostorm Arctic, etc...

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
@Orphis should be fairly easy, just need to trigger the "vrRelease" Android build, similar to how we now build "normalRelease".

**Comment by lvonasek** [comment]
@hrydgard this isn't needed anymore.

**Comment by hrydgard** [comment]
Right, closing.
