### ISSUE TITLE
Wants to add new button layout like this

### ISSUE THREAD

**Issue by Hidte09** [hrydgard/ppsspp#17068]
### Platform

None

### Compiler and build tool versions

Clang+cmake in Android studio 

### Operating system version

Windows 10

### Build commands used

-

### What happens

These are the png photos of custom button layout to implement in ppsspp controller
![IMG_20230227_162721](https://user-images.githubusercontent.com/124633547/223375993-1a2f3939-1d75-4f9b-bcc9-10060b8dd910.png)
![IMG_20230227_162733](https://user-images.githubusercontent.com/124633547/223376006-9ff8012d-9ac3-45bf-910d-3b6bc47f5d8b.png)
![IMG_20230227_162748](https://user-images.githubusercontent.com/124633547/223376016-4a3fa511-dd4e-409b-95d4-2f1c3a7dec54.png)
![IMG_20230227_162801](https://user-images.githubusercontent.com/124633547/223376024-09a69b52-0f5a-4dd2-950b-88faa0800d4c.png)
![IMG_20230227_162824](https://user-images.githubusercontent.com/124633547/223376030-6d36ada1-83b3-4258-b9ed-6f530e9b445a.png)

### PPSSPP version affected

V1.14.4

### Last working version

V1.14.1

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] Make sure to run `git submodule update --init --recursive` before building.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try deleting the build directory and running the build again.
- [ ] Check GitHub Actions, which builds every merge and PR.
- [ ] Include logs and help us reproduce.

**Comment by hrydgard** [comment]
To be a bit more clear, sorry, like, show these they way they would look in the emulator if you want to sell your vision, put them together into a design.

A bunch of gigantic button images isn't a design.
