### ISSUE TITLE
Deleaker 5/4073 report of v1.14.4-766-g625d93a2a

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#17077]
### Game or games this happens in

All

### What area of the game / PPSSPP

In-game then exit

### What should happen

No problem

### Logs

version v1.14.4-766-g625d93a2a

ossource.cpp, line 116 (E:\project\1\ppsspp_sum2012\ext\glslang\glslang\OSDependent\Windows\ossource.cpp)	0x0000000000000324	1	Mutex handle	PPSSPPDebug64.exe	E:\project\1\ppsspp_sum2012\PPSSPPDebug64.exe	<Not Available>	8112	2023/3/8 20:27:08.0170000	325966	7228	
utils.c, line 80 (c:\msys64\home\chris\ppsspp-ffmpeg\libavcodec\utils.c)	0x000000001c2816a0	1	Critical section	PPSSPPDebug64.exe	E:\project\1\ppsspp_sum2012\PPSSPPDebug64.exe	<Not Available>	8112	2023/3/8 20:29:03.6410000	4413022	9300	
TouchInputHandler.cpp, line 108 (E:\project\1\ppsspp_sum2012\Windows\TouchInputHandler.cpp)	0x000000000000c01a	1	Atom	PPSSPPDebug64.exe	E:\project\1\ppsspp_sum2012\PPSSPPDebug64.exe	<Not Available>	8112	2023/3/8 20:27:06.4450000	279499	9172	
debug_heap.cpp, line 450 (minkernel\crts\ucrt\src\appcrt\heap\debug_heap.cpp)	0x000000001c281660	1	Heap memory	PPSSPPDebug64.exe	E:\project\1\ppsspp_sum2012\PPSSPPDebug64.exe	139	8112	2023/3/8 20:29:03.6410000	4413021	9300	
ossource.cpp, line 116 (E:\project\1\ppsspp_sum2012\ext\glslang\glslang\OSDependent\Windows\ossource.cpp)	0x000000000000029c	1	Mutex handle	PPSSPPDebug64.exe	E:\project\1\ppsspp_sum2012\PPSSPPDebug64.exe	<Not Available>	8112	2023/3/8 20:27:06.4890000	280303	7228	

![1](https://user-images.githubusercontent.com/2177532/223715643-6bafbaac-dce7-4a72-99e9-8f71eda16f6c.png)
![2](https://user-images.githubusercontent.com/2177532/223715664-1ee14fbe-e7e0-402a-9b68-fda9f04d88c1.png)
![3](https://user-images.githubusercontent.com/2177532/223715675-d824ea58-26e6-46ff-b5f5-0f86d0b35d8b.png)
![4](https://user-images.githubusercontent.com/2177532/223715689-d7f28a80-91d5-4425-9cb1-f55fd5f520be.png)
![5](https://user-images.githubusercontent.com/2177532/223715735-cd0ab04d-4a25-4021-94b9-e99dd49ce333.png)

### Platform

Windows

### Mobile phone model or graphics card

Nvidia Geforce 710

### PPSSPP version affected

v1.14.4-766-g625d93a2a

### Last working version

none

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment]
Interesting, as i remembered VS2022 also detecting memory leaks on my infrastructure code when i'm done debugging it from VS, but it was a pain to figured out the source code location as VS only shows the allocation block number (and it's address) as a clue (which different on each run), thus memory breakpoints can't help.
So i would like to fix the leaks on my branch first before making a PR.

Unfortunately, Deleaker is a paid app. Is there any other good leaks detector that are free?

**Comment by sum2012** [comment]
wonderleak
http://www.relyze.com/wonderleak.html
Seem only support Visual Studio 2017 and Visual Studio 2019.
I do not test VS2022 as I am using windows 7

**Comment by MarcoEstevez** [comment]
Same problem here, updating PPSSPP to lates build makes the application closes itself after trying to launch any game

**Comment by hrydgard** [comment]
@MarcoEstevez , that is unrelated to this issue.

My texture replacement rework is causing some issues, they'll all be fixed shortly, don't worry.

**Comment by sum2012** [comment]
I buy a new desktop computer with amd cpu 7900 with amd integrated graphics card.
I don't use Deleaker anymore.
