### ISSUE TITLE
Heatseeker Missing Dialogues and audio problems

### ISSUE THREAD

**Issue by German-Herrador** [hrydgard/ppsspp#17094]
### Game or games this happens in

ULES-00760 Heatseeker

### What area of the game / PPSSPP

Easy to reproduce. Cutscenes and in-game doesn't have dialogues and the other sound effects sound strange/broken.

The captions shows that there's indeed dialogue but isn't reproducing:
https://user-images.githubusercontent.com/109971356/224507631-8b788691-9744-43a9-b4f9-86615d8e02e7.mp4

### What should happen

The game should have dialogues. I can't test it in real hardware but here's a [gameplay](https://youtu.be/2pz8FJk7qcs) on real hardwares.

Older gameplays (5-3 years) that use the emulator instead also have this problem.

### Platform

Android

### Mobile phone model or graphics card

Huawei Y9 2019 Mali-G51

### PPSSPP version affected

v1.14.0

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by LunaMoo** [comment]
Heatseaker didn't had VO on PSP, you're looking at video from PS2 version which had some major differences and should not be compared to look for problems.

  As for other problem, #12534 suggests it's working as on the real hardware, not sure what exactly you're experiencing through.

**Comment by German-Herrador** [comment]
Yeah, you're right. Thanks for the information.
