### ISSUE TITLE
IR Interpreter broken in Outrun 2006

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#17109]
Disabling VFPU_VEC in the JIT debug tools fixes it, so it's quite likely to be some VFPU register allocation issue or similar.

It's instantly bad as soon as you boot the game up, the very first logo screen looks like this: 

![image](https://user-images.githubusercontent.com/130929/224782866-6d217ebc-986f-4e0c-ad25-1a5a23d10ec1.png)

instead of showing a proper SEGA logo.

Tested on Mac M1, but likely affects all platforms.

**Comment by ANR2ME** [comment]
Is this only happened on US version (the strange SEGA logo i mean)? 
because when i tested this game (EU version) using IR interpreter (on PPSSPP v1.14.4-880), it immediately crashing PPSSPP before showing anything on screen, with or without disabling VFPU_VEC both crashed.

**Comment by hrydgard** [comment]
Huh, weird, I'm getting the same as you on Windows... So somehow it's different on Mac. Fun.

**Comment by hrydgard** [comment]
That change seems to have fixed Outrun on Mac too. Unclear why it ran before, while crashing on Windows. Oh well.

**Comment by unknownbrackets** [comment]
I think only Windows had an issue with memory allocation and was separate.

-[Unknown]

**Comment by hrydgard** [comment]
Oh right, that part was the one causing the crash, yeah.
