### ISSUE TITLE
Some pspautotests/tests/rtc/ failures

### ISSUE THREAD

**Issue by fp64** [hrydgard/ppsspp#17119]
### Platform

Linux / BSD

### Compiler and build tool versions

cmake version 3.23.3, g++ (Debian 10.2.1-6) 10.2.1 20210110

### Operating system version

Linux

### Build commands used

```
./b.sh --headless
python3 test.py -g --graphics=software
```

### What happens

Was interested why it kept failing rtc tests:
```
Failed tests:
  rtc/arithmetic
  rtc/lookup
```

It looks like `time_t` is signed 32-bit integer on my system (32-bit Linux). And 2^32 seconds is just ~136.102208 years, hence failing bunch of tests, since `__RtcTicksToPspTime` and `__RtcPspTimeToTicks` just use `time_t` to adjust things (extra 400 years adjustment messes up?).

Logs of a test run:
[rtc.txt](https://github.com/hrydgard/ppsspp/files/10970548/rtc.txt)

Not sure if any games are affected.

### PPSSPP version affected

v1.12.3-5098-g3a6e48a9b

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] Make sure to run `git submodule update --init --recursive` before building.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try deleting the build directory and running the build again.
- [ ] Check GitHub Actions, which builds every merge and PR.
- [ ] Include logs and help us reproduce.

**Comment by fp64** [comment]
And, according to both [manual](https://www.gnu.org/software/libc/manual/html_node/64_002dbit-time-symbol-handling.html) and experiments, things like `__localtime64` aren't exposed to user code.
See also https://stackoverflow.com/questions/57198602/how-to-use-mktime64-time64-and-localtime64-function-with-32-bit-time-libr .
Note, that in my case:
```
$ uname -r
5.10.10
$ ldd --version
ldd (Debian GLIBC 2.31-9) 2.31
```
And, apparently, on 32-bit versions `time_t` was changed to 64-bit in `glibc 2.32`.

**Comment by hrydgard** [comment]
2.32 is already almost 3 years old, but it may indeed still make sense to support earlier versions...

**Comment by fp64** [comment]
At least `__RtcTicksToPspTime` and `__RtcPspTimeToTicks` should be possible implement in (relatively simple) pure integer math, with no library calls.
The code from http://howardhinnant.github.io/date_algorithms.html (`days_from_civil`, `civil_from_days`) looks promising.

**Comment by fp64** [comment]
Yes, match `gmtime` on 0001-01-01 .. 9999-12-31:
https://godbolt.org/z/b7aaKbGWr
