### ISSUE TITLE
Deadlock in release mode, related to pipeline creation

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#17124]
I'm trying to debug a weird threading issue causing a deadlock, taking notes here.

Here are the conditions, which repros 90% or so:

* Release mode build (Visual Studio 2022)
* Run under the debugger ONLY
* Wipeout Pure (euro) with a high-res texture replacement pack

It happens when loading the first race, when fast-forwarding through the menus mashing keys to quickly get going.

Observations:

* In g_threadManager, multiple threads have a queue_size atomic set to 1, even though their queues are empty and they're not doing anything at all. Though debug info is always iffy in release builds. This doesn't happen in debug.
* The deadlock always happens in this wait in `VulkanQueueRunner.cpp`: `VkPipeline pipeline = graphicsPipeline->pipeline[(size_t)rpType]->BlockUntilReady();`. Nothing ever arrives. The above `graphicsPipeline->Create` is not called.
* The pipeline compiler queue thread seems empty
* Disabling parallel memcpy in `ReplacedTexture::CopyLevelTo` doesn't fix it
* Changing task priority in `ReplacedTextureTask` to High appears to fix it

**Comment by unknownbrackets** [comment]
What if you put `#pragma optimize("", off)` at the top of ThreadManager.cpp only?  Still Release, though.  Does it still happen?

-[Unknown]

**Comment by hrydgard** [comment]
Doesn't seem to make a difference. However, #17126 does! Quite odd. I guess the linker gets confused between two types and screws things up? Not sure. Not 100% sure yet it doesn't repro anymore, but did 10 tries and it didn't happen.

**Comment by hrydgard** [comment]
I'm starting to actually believe this is some kind of really wacky misbehavior caused by MSVC's debugger confusing two struct types as described above. But I've never quite seen anything like it.

**Comment by hrydgard** [comment]
Huh. I take that back, it's not gone - the threaded copy seems to make it worse somehow. I flipped the ifdefs in #17126, helpfully pointed out by @iota97 .

**Comment by hrydgard** [comment]
Here's an interesting one, I added this assert in `WorkerThreadFunc`, and it fires:

```
			// Reduce the queue size once complete.
			thread->queue_size--;
			_assert_(thread->queue_size == thread->private_queue[0].size() + thread->private_queue[1].size() + thread->private_queue[2].size());
```

**Comment by hrydgard** [comment]
Hah, I found it. PR coming
