### ISSUE TITLE
Hammerin Hero Black Screen

### ISSUE THREAD

**Issue by Neeekoo-Chan** [hrydgard/ppsspp#17127]
### Game or games this happens in

ULUS10392 - Hammerin Hero

### What area of the game

In Under Fukie bay when you go to water it become black 

### What happens

![Screenshot_2023-03-16-05-09-10-60_74c288e31530b9e5d0ca749a600f3e41](https://user-images.githubusercontent.com/52073886/225446267-e70085d1-6ecc-4cca-ae39-3b1dfa1b7aac.jpg)

Black screen 

### What should happen

Well in a previous version is work but lag when i play this but i dont know what version is that so i hope will fix this in latest version 

### Platform

Android

### Mobile phone model or graphics card

RMX2185

### PPSSPP version affected

1.14.4

### Graphics backend (3D API)

Other

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by sum2012** [comment]
Please test newest version in
https://buildbot.orphis.net/ppsspp/index.php

**Comment by Gamemulatorer** [comment]
This game kinda slow on my vivo y11 snapdragon 439 adreno 505 gpu.

Vulkan 30/60 FPS
OpenGL 40/60 FPS
PPSSPP v1.14.4-909-gfcf895fe1

![Screenshot_20230316_074040_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37603562/225468993-72e93718-4a53-4da0-8e9d-2a8260a03649.jpg)

[ULUS10392.zip](https://github.com/hrydgard/ppsspp/files/10985394/ULUS10392.zip)

**Comment by Gamemulatorer** [comment]
Closing? This is fix using the recently build PPSSPP from buildbot?

**Comment by hrydgard** [comment]
Sometimes we can avoid GPU readbacks. You got a GE dump of the problematic level in the game?

https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

**Comment by Gamemulatorer** [comment]
Might be a good idea if this is added to [RequireBlockTransfer] compat.ini to warn users.

Also just a suggestion block transfer shoul be change to gpu readbacks in compat.ini?
