### ISSUE TITLE
Resistance Retribution Crashing 

### ISSUE THREAD

**Issue by chrisleigh-stack** [hrydgard/ppsspp#17135]
### Game or games this happens in

Resistance Retribution 

### What area of the game / PPSSPP

Some areas 

### What should happen

It's crashing 

### Platform

Android

### Mobile phone model or graphics card

Adreno 650

### PPSSPP version affected

1.14.4

### Last working version

1.14.4

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by sum2012** [comment]
#4626 still have it , closing

**Comment by Gamemulatorer** [comment]
Try the extracted iso
https://youtu.be/StYrmR0PHEg

**Comment by chrisleigh-stack** [comment]
No i don't want that shit, not the game iso format is the problem, the
emulator it self
