### ISSUE TITLE
Org.ppsspp.ppsspp don't have gamesettingactivity.java class

### ISSUE THREAD

**Issue by Hidte09** [hrydgard/ppsspp#17142]
### Platform

None

### Compiler and build tool versions

Clang+cmake in Android studio 

### Operating system version

Windows 10

### Build commands used

-

### What happens

SettingsActivity.java missing from source code.

### PPSSPP version affected

V1.14.4

### Last working version

V1.14.1

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] Make sure to run `git submodule update --init --recursive` before building.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try deleting the build directory and running the build again.
- [ ] Check GitHub Actions, which builds every merge and PR.
- [ ] Include logs and help us reproduce.

**Comment by hrydgard** [comment]
I don't understand what you mean, I don't remember that we ever had such a java file or activity.
