### ISSUE TITLE
Opengl graphick problem 

### ISSUE THREAD

**Issue by GAmeuser2203** [hrydgard/ppsspp#17145]
### Game or games this happens in

Opengl 

### What area of the game

why does the picture on open gl look cut , well , as if the ghz monitor is not enough , it looks good on dirext 11. it is possible to enable vertical synchronization , but this is not necessary on dirext 11 , unlike open gl.

### What happens

it is possible to enable vertical synchronization , but this is not necessary on dirext 11 , unlike open gl.

### What should happen

Maybe fix this

### GE frame capture

the picture looks cut

### Platform

Windows

### Mobile phone model or graphics card

gtx 1050ti 

### PPSSPP version affected

latest 

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by GAmeuser2203** [comment]
some kind of stripe is especially noticeable when I rotate the camera in the game and the picture looks cut

**Comment by hrydgard** [comment]
This is called tearing.

I think we actually get vsync automatically on D3D11, and that's why the setting doesn't make a difference there.

Just use VSync on OpenGL if you need it, and in general, just use what works best.

**Comment by GAmeuser2203** [comment]
> This is called tearing.
> 
> I think we actually get vsync automatically on D3D11, and that's why the setting doesn't make a difference there.
> 
> Just use VSync on OpenGL if you need it, and in general, just use what works best.

I note that vsync in opengl reduces performance on weak video cards

**Comment by GAmeuser2203** [comment]
although you claim that open gl is the best

**Comment by hrydgard** [comment]
I don't claim that OpenGL is the best - or maybe I do somewhere, but it's outdated - where?. Generally Vulkan and D3D11 will perform better than OpenGL (there are exceptions though).

**Comment by GAmeuser2203** [comment]
thanks for the answer , I thought so , just a friend claimed that opengl is better because it is the native psp backend , and dirext is alien

**Comment by hrydgard** [comment]
Neither is native on the PSP - the PSP hardware doesn't conform to any API, there's always a lot of translation involved.
