### ISSUE TITLE
left click is broken with a macro, when I press the key left click is macro'ed to it works but the emulator only registers 1/10 of the inputs randomly when it's on left click. Makes no sense how can the emulator know that im pressing left click when it's bound to a key for all of my computer?

### ISSUE THREAD

**Issue by pataponplayer** [hrydgard/ppsspp#17148]
### Game or games this happens in

None

### What area of the game / PPSSPP

all of PPSSPP

### What should happen

https://youtu.be/g4fAHFxekjY : me spamming the keys, only left click not working after changing macro 3 times

PPSSPP should allow full customziation of keybinds. It's like a game where you can't rebind movement keys

### Platform

Windows

### Mobile phone model or graphics card

gtx 1060

### PPSSPP version affected

1.14.4

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by LunaMoo** [comment]
It's really hard to understand what's the actual issue you're experiencing. Title is very long, but you fail to explain what you're trying to do, how you're trying to do it and what exactly fails.

 All I can see is you're trying to spam keys in Patapon game which requires rhytm and spamming as fast as you can will NEVER work, also if you'd experience any frame drop this will affect rhytm making it harder to follow as well.

 As for mouse button not triggering your third party software it seems to be your third party software problem, not PPSSPP itself. You can enable mouse control in PPSSPP and map mouse keys directly to PSP buttons and it should work just fine as long as no third party software is messing with it.

**Comment by pataponplayer** [comment]
oh yeah turning mouse control solved it, thank you. I know how to patapon lol. Yesterday I did a boss staying in hero mode for 40+ inputs. My problem was that I could bind any mouse buttons exepct for left click. I used a macro and was puzzled has too how it didn't work.
