### ISSUE TITLE
ThrillVille graphics corruption

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#17169]
This game has been notorious in the past for weird clearing issues due to its use of immediate mode draws for that (which hardly any other games use). Seems the issues are back, and it happens immediately when starting a game:

![image](https://user-images.githubusercontent.com/130929/227259436-c6bc3442-68bb-4b52-b7c8-e00fb3837196.png)

Reported by meteb on Discord, plus a couple of users on e-mail.

I'll see if I can take some GE snapshots. EDIT: here's one, but can't see the issue in the dump since it seems to forget to clear the Z buffer, and if you just render the same frame over and over, that doesn't matter. 

[ThrillvilleULES00889_0002.zip](https://github.com/hrydgard/ppsspp/files/11052963/ThrillvilleULES00889_0002.zip)

**Comment by Panderner** [comment]
Screenshot for this GE dump:
![ULES00889_00000](https://user-images.githubusercontent.com/37503397/227262997-93a4f44f-17a9-4216-86f3-7670d291e336.jpg)

**Comment by hrydgard** [comment]
Hm, there's some weird stuff going on. There never is a depth clear, but a copy early in the frame from the previous frame's framebuffer. But that happens as the second draw because the first draw ignores depth. Depth is marked as DONT_CARE which is a good optimization in this case. but the missing clear is, well, missing.

![image](https://user-images.githubusercontent.com/130929/227262844-9bcee142-4580-4942-ae01-b41b3da81405.png)

To be continued...
