### ISSUE TITLE
PPSSPP bluescreens while debugging

### ISSUE THREAD

**Issue by Nemoumbra** [hrydgard/ppsspp#17179]
### Game or games this happens in

Patapon 3 Overhaul Demo v1.6.2

### What area of the game / PPSSPP

When the game is run without enabling a breakpoint at 0x08DD4660 (size 0x100), it runs fine. When I enable said breakpoint and do a few steps in the debugger, the game does an illegal access shown on the screenshot.
![image](https://user-images.githubusercontent.com/62447396/227647487-86f06db9-6b52-4204-9f70-97a094d54bc9.png)

The issue may be related to the fact that the breakpoint was triggered a few times by the memcmp as seen in the video.

### What should happen

The debugger mustn't make the game run differently.

### Logs

That's not a log, but a video showing how to reproduce the bug.
When it comes to acquiring Overhaul of this version... The ISO can be downloaded from the Overhaul Discord server. 

https://user-images.githubusercontent.com/62447396/227647887-9d8ff2e2-1dbd-4f53-8f74-154fb49bed1d.mp4

### Platform

Windows

### Mobile phone model or graphics card

AMD Radeon(TM) Graphics

### PPSSPP version affected

Self-built version (one of the lastest)

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by Nemoumbra** [comment]
Now that the crash logs have become more verbose, I've got a new blue screen image.
![image](https://user-images.githubusercontent.com/62447396/229276618-7f65ae18-29bb-4a1b-abd2-78f8e0444cd4.png)

**Comment by unknownbrackets** [comment]
It seems strange that sp is such an invalid value, maybe this is related to the stack trace thing?  Since you can reproduce it, it'd be helpful if you could set a breakpoint inside Core/Core.cpp within Core_MemoryException and Core_MemoryExceptionInfo.  Then reproduce it, and see the C++ stack trace in Visual Studio.  That would tell us where this is coming from for sure.

Also in programming text is usually better than images, better to paste a snippet from a log rather than a screenshot.

-[Unknown]

**Comment by Nemoumbra** [comment]
The crash is gone now! I don't know what change fixed it, but I can't reproduce it anymore! I guess, time to close this.
