### ISSUE TITLE
(UWP) Broken Controller Inputs

### ISSUE THREAD

**Issue by GABO1423** [hrydgard/ppsspp#17187]
### Game or games this happens in

All

### What area of the game / PPSSPP

PPSSPP does not respond to controller inputs at all, only way to control it now is via a keyboard. This is not game specific as not even the UI can be controlled now.

### What should happen

I press A on the controller, something happens.

### Logs

N/A

### Platform

UWP / Xbox

### Mobile phone model or graphics card

Xbox Series X GPU

### PPSSPP version affected

v1.14.4-1053-gafb17119b

### Last working version

v1.14.4-1031-ge71be8af

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
My bad, will fix shortly.
