### ISSUE TITLE
Original PC-Engine Chi no Rondo [ULJM05287] Black background Software rendering issues

### ISSUE THREAD

**Issue by RokkumanX** [hrydgard/ppsspp#17213]
### Game or games this happens in

ULJM05287

### What area of the game

The issue is present on the Title screen, menus and ingame.

### What happens

This happens with OpenGL, Direct3D9, Direct3D11 and Vulkan using Software rendering.

**Title screen (Software rendering):**

![Chi no Rondo Title](https://user-images.githubusercontent.com/85066613/229267303-1824c0d5-3c65-4d30-ba1d-f08e8f081422.png)

**Menu 1 (Software rendering):**

![Chi no Rondo Menu 1](https://user-images.githubusercontent.com/85066613/229267363-c7fc39a7-3c81-4ea4-a26a-0a8c93ee5348.png)

**Menu 2 (Software rendering):**

![Chi no Rondo Menu 2](https://user-images.githubusercontent.com/85066613/229267386-49b39ff3-1af3-4547-a08d-69bfdb3edfcf.png)

**Ingame (Software rendering):**

![Chi no Rondo Ingame](https://user-images.githubusercontent.com/85066613/229267407-63750583-6115-4912-bae7-4cd9bb72be6e.png)

### What should happen

This is screenshots with Software rendering disabled and what I expect the game to look like with Software rendering fully functional.

**Title screen (No Software):**

![Chi no Rondo Title (No software)](https://user-images.githubusercontent.com/85066613/229267527-b64d8d61-d4bb-4fa2-ae7c-915284c1ba3b.png)

**Menu 1  (No Software):**

![Chi no Rondo Menu 1 (No software)](https://user-images.githubusercontent.com/85066613/229267537-06cafc8f-1a7a-432c-ac4c-6d80a5269a0f.png)

**Menu 2  (No Software):**

![Chi no Rondo Menu 2 (No software)](https://user-images.githubusercontent.com/85066613/229267553-b8a4dc29-7f3e-43ba-a149-0ae796bab70d.png)

**Ingame  (No Software):**

![Chi no Rondo Ingame (No software)](https://user-images.githubusercontent.com/85066613/229267571-b21397ac-f3dd-471f-b9fb-edb45978016f.png)

### GE frame capture

I'm not sure about GE frame capture but I'll provide some settings and such.

![PPSSPP Settings 1](https://user-images.githubusercontent.com/85066613/229267797-532f04cb-cd1d-44ec-94a6-81bbbc8810e3.png)

![PPSSPP Settings 2](https://user-images.githubusercontent.com/85066613/229267799-b240e63f-e36b-48b9-9b7a-8d81baf6bf2f.png)

![PPSSPP Settings 3](https://user-images.githubusercontent.com/85066613/229267800-d0374488-9d58-421e-bfe7-5a084c73355e.png)

![PPSSPP Settings 4](https://user-images.githubusercontent.com/85066613/229267801-1f742485-baad-45eb-bb78-cd579351a7e4.png)

Game is 100% verified here http://redump.org/disc/24765/

![HashCalc](https://user-images.githubusercontent.com/85066613/229267849-d5177190-bcee-4919-ba53-22102b0e5b9f.png)

### Platform

Windows

### Mobile phone model or graphics card

NVIDIA GeForce GTX 1070

### PPSSPP version affected

v1.14.4-1152-g2814668cf

### Last working version

Don't know unfortunately

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
This sounds like a state handling bug.  Could you try exporting a GE frame dump?  These help a lot.  Just make sure to export it when you see the issue - it's almost like a screenshot.  If you make it while the issue isn't happening, it won't help.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by RokkumanX** [comment]
Thank you for your quick response, I'll try doing it right now.

**Comment by RokkumanX** [comment]
OK, here goes, it produced a bunch of .ppdmp files and I made sure the issue was present at all times,

[GE Frame dumps.zip](https://github.com/hrydgard/ppsspp/files/11128560/GE.Frame.dumps.zip)

**Comment by RokkumanX** [comment]
I just noticed something else and I might have to create a new issue for it altogether, Gekka no Yasoukyoku (SotN) is flickering like crazy ingame with Software rendering disabled but works great with it enabled.

Weird, Chi no Rondo plays ok without Software rendering but SotN absolutely needs it because of epileptical flickering.

**Comment by unknownbrackets** [comment]
Thanks.  The flickering doesn't sound great - normally that would happen with frameskip or the skip buffer effects speedhacks enabled.  It might help for that one to try a few old stable versions to see if it's new - I'm a bit surprised if that's not new and hasn't been reported before.

-[Unknown]

**Comment by RokkumanX** [comment]
Thank you very much for all your help!

I usually disable all hacks and such to make sure my experience is as close to the original console as possible and I pretty much always strive for playing on native resolution.

The flickering in SotN might be something new as I don't recall it happened in 1.13.2

I will try older releases later this day to make sure, the 1.14.4-1152 update is the first one in a long while I'm using right now since 1.13.2 and much have happened since.

I'll be sure to report back then.

**Comment by RokkumanX** [comment]
This issue is 100% fixed in 1.14.4-1178

Many thanks
