### ISSUE TITLE
crash stack

### ISSUE THREAD

**Issue by hsoftxl** [hrydgard/ppsspp#17226]
### Game or games this happens in

1.14.4

### What area of the game / PPSSPP

builde libretro core 

### What should happen

$NDK/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-addr2line -C -f -e arm64-v8a/libretro.so  881c14

MIPSState::RunLoopUntil(unsigned long long)

/home/xielei/StudioProjects/ppsspp/libretro/jni/../../Core/MIPS/MIPS.cpp:341

$NDK/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-addr2line -C -f -e arm64-v8a/libretro.so  869658

MIPSComp::JitAt()

/home/xielei/StudioProjects/ppsspp/libretro/jni/../../Core/MIPS/JitCommon/JitCommon.cpp:56

### Platform

Android

### Mobile phone model or graphics card

samsung s20f

### PPSSPP version affected

1.14.4

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
This stack trace isn't very interesting - it's just saying something crashed within jitted code.  Since there's no game or anything listed, there's literally nothing to go on here.

-[Unknown]
