### ISSUE TITLE
SOCOM: Tactical Strike Crash

### ISSUE THREAD

**Issue by TheRhysWyrill** [hrydgard/ppsspp#17233]
### Game or games this happens in

UCUS-98649 - SOCOM: Tactical Strike

### What area of the game / PPSSPP

When trying to start a new game and loading into the first level the game crashes with the following error.

![2023-04-04 19_06_46-](https://user-images.githubusercontent.com/27123572/229880115-bf1162ca-b2cc-4e41-b639-bd974aeae949.png)

### What should happen

It shouldn't crash.

### Platform

Windows

### Mobile phone model or graphics card

NVidia Geforce RTX 2060

### PPSSPP version affected

v1.14.4

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment]
Does the latest dev build from https://buildbot.orphis.net/ppsspp/ also crashed?

**Comment by sum2012** [comment]
I test no problem,My iso CRC As below
![2](https://user-images.githubusercontent.com/2177532/230884450-56bb3db8-1f6d-4bdd-b545-d082b83d2ede.png)

**Comment by TheRhysWyrill** [comment]
> I test no problem,My iso CRC As below ![2](https://user-images.githubusercontent.com/2177532/230884450-56bb3db8-1f6d-4bdd-b545-d082b83d2ede.png)

Interesting, I decided to try again with a fresh dump and yeah, can confirm the game is working, even when the iso is optimized, not entirely sure why my initial dump was crashing, either way, in the end it seems like it was an issue with my iso and not PPSSPP, closing issue.
