### ISSUE TITLE
Post-shader stretching problems

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#17249]
The post shader pipeline seems to do some stretching that shouldn't be there, if the source buffer isn't sized 480x272. I've been testing with 1x rendering, nearest filtering and a simple vignette post shader effect, and getting artifacts whenever the final framebuffer has been detected at other sizes. For example, in psp-flower homebrew from the store, the framebuffer is detected as 480x274 and then there's a stretch to 480x272 during application of the effect, causing a couple of horizontal line artifacts.

Similarly, in games that use 512x272 framebuffers (like often seen in FMV playback), we instead get a horizontal stretch causing vertical artifacts.

**Comment by LunaMoo** [comment]
I recall issues with effects in games that switched framebuffer sizes every frame causing flickering of effects that left any pattern, but I don't remember a fix for those causing other problems. Just mentioning in case the stretch is related to that old problem fix.

**Comment by unknownbrackets** [comment]
I think you're referring to this change or similar:
https://github.com/hrydgard/ppsspp/pull/12894

Which was more about how the delta values were not even aligned to the size of things.  This however is probably just about setting the UVs such that it's always the top left of the buffer (which would necessarily adjust texelDelta as well.)

-[Unknown]

**Comment by hrydgard** [comment]
That's right, I have a WIP fix already.
