### ISSUE TITLE
Sun still shining through solid objects in split second

### ISSUE THREAD

**Issue by 71knight** [hrydgard/ppsspp#17243]
### Game or games this happens in

Split / second

### What area of the game

At various points in the game.

### What happens

You can see the sun and lens flare shining through solid objects.  Looks like GPU readbacks option doesn't work.  I know developer previously said he had fixed this.

### What should happen

Should not be able to see the sun/lens flare through solid objects.

### Platform

Android 11

### Mobile phone model or graphics card

OnePlus 7t SD 855+ with adreno 640.

### PPSSPP version affected

14.4 1199 development build

### Last working version

?

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [ ] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment]
A GE frame dump might be needed to be investigated, in case the devs don't have the game.

**Comment by hrydgard** [comment]
This is just a duplicate report of #15785 .

Split/Second uses depth buffer reads using the CPU, just like Wipeout. We don't have a working good solution for this yet, even though some ground work has been laid. Also see the high level issue #15923 .
