### ISSUE TITLE
Retrieve Pointer to Emulated PSP Memory Base Address via WebSocket API

### ISSUE THREAD

**Issue by NABN00B** [hrydgard/ppsspp#17253]
### What should happen

Currently with the WebSocket API we can only retrieve the Base Address of the emulated PSP's memory. This is fine when doing a quick check in memory for something. However, for scripts and other tools it would be more beneficial to request the address containing the Base Address.

See: https://github.com/hrydgard/ppsspp/commit/6f9d6c6c5fa333059d4cfed1f68e7121db8e7e6e

I would be thankful if this still managed to get into 1.15 so it can debut with the commit above. 🙏 
Thank you in advance!

### Who would this benefit

Game hackers

### Platform (if relevant)

None

### Games this would be useful in

-

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by unknownbrackets** [comment]
It's event based.  Just listen for the "game.start" event, and when it's fired, request the pointer event again.

-[Unknown]
