### ISSUE TITLE
Memory.base retrieval returns too many bytes from 32bit PPSSPPWindows process under 64bit Windows

### ISSUE THREAD

**Issue by NABN00B** [hrydgard/ppsspp#17266]
### Game or games this happens in

-

### What area of the game / PPSSPP

When retrieving memory.base of a 32bit PPSSPPWindows process under 64bit Windows
- via the newly added menu item under the options menu
- or via the WebSocket API
the returned address is 8bytes long instead of 4bytes.

Related commits:
https://github.com/hrydgard/ppsspp/commit/cd6be61d98b66e6b4a20186e933820cd01fac974
https://github.com/hrydgard/ppsspp/pull/16994/commits/aab4a3034c4f611d47dd7250c6ec7e6774dc2515

### What should happen

If PPSSPPWindows is a 32bit process running on 64bit Windows, the returned address should be 4bytes long.
Alternatively, the upper 32 bits could be nulled.

### Logs

![](https://cdn.discordapp.com/attachments/478294170662862852/1094693880798134352/image.png)

Top: PSP base address as returned by Window Messages (`(address) Lower 32 bits` and `PSP Memory Base Address` values). Confirmed with Cheat Engine to be the correct address.
Middle: PSP base address as returned by the WebSocket API.
Bottom: PSP base address as copied to clipboard by the Debug menu item.

### Platform

Windows

### Mobile phone model or graphics card

-

### PPSSPP version affected

see links above

### Graphics backend (3D API)

Other

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Yeah, I'll get this fixed soon.

**Comment by hrydgard** [comment]
This should be fixed now with #17263 I believe, please re-open if not.

**Comment by NABN00B** [comment]
Also by https://github.com/hrydgard/ppsspp/commit/8a74d95eb2bfbd8c17c09036257c6ae6f85283b3 
Thanks!
