### ISSUE TITLE
Invizimals runs slow when opening back camera

### ISSUE THREAD

**Issue by Costa1005** [hrydgard/ppsspp#17283]
### Game or games this happens in

Invizimals and Invizimals the shadow zone

### What area of the game

So everytime i have to capture an invizimal and use the camera it is very laggy, not the game itself but the camera frames, this makes it impossible for me to capture the second invizimal that needs to be scartched cuz it does not detect the movement (i think) however if I user the frontal camera it is not laggy, and while the back camera is laggy , the game UI still runs at a very smooth FPS

### Platform

Android

### Mobile phone model or graphics card

Redmi 11 PRO 5g

### PPSSPP version affected

1.14.4

### Graphics backend (3D API)

OpenGL / GLES

### Any other notes or things you've tried

I changed a lot of graphical settings and disaled MIUI battery optimizations since its known to affect some stuff, clear camera cache but the camera lag only happens in game

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the slowdown.
- [ ] Include logs or screenshots of issue.

**Comment by Panderner** [comment]
Can you screenshot to compare the frame rate difference for front and back camera?

**Comment by Costa1005** [comment]
> Can you screenshot to compare the frame rate difference for front and back camera?

You will not notice difference in actual frame rate, its actually 60fps in both cases, the UI elemtens of the game that overlay the camera image run smoothly, its the camera back camera  itself that preforms very laggy in the app

**Comment by hrydgard** [comment]
Ok, good that the UI is keeping up at least. I guess it's possible that we're requesting images of an excessive resolution, or something like that. Haven't looked at the camera code in years... Needs investigating

**Comment by Costa1005** [comment]
I guess that would make sense, since back camera has much bigger resolution than front, and my phone as mentioned is a Redmi 11 pro 5g, it has 105 MP in the back camera

**Comment by hrydgard** [comment]
Hm, for some reason our logic chooses the slowest framerate available for previews, which is probably not ideal. For 1.15, I'm not gonna go deep into investigating here, but I'll make it pick the framerate closest to 30fps, which should be good enough.

There's also lots of scope for optimizing the surrounding code, but that's for later. (we do image processing in Java here, for example, just to utilize Android's JPEG encoder (the game expects JPEG images) ). But again, for later.

**Comment by Costa1005** [comment]
Is ther a target date/range to expect the update?

**Comment by hrydgard** [comment]
I just merged the fix, so builds should start appearing soon (newer than 1.4.4-1346).

**Comment by Costa1005** [comment]
Will there be an android build in the automated builds for this fix?

**Comment by hrydgard** [comment]
Yes, you'll find it here soon (1349): https://buildbot.orphis.net/ppsspp/

**Comment by Costa1005** [comment]
Thanks, ill be sure to test and close the issue if fixed

**Comment by Costa1005** [comment]
Worked like a charm, camera runs smoothly
