### ISSUE TITLE
Control refactoring broke something on Steam Deck?

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#17284]
Might also apply to other platforms, this was just reported as a steam deck issue on Discord.

![input](https://user-images.githubusercontent.com/130929/232112474-761c0b52-8a53-490e-b365-a6233945402a.jpg)

**Comment by hrydgard** [comment]
Hm, really strange - with the same parameters, I see this on PC (windows, x360 controller):

![image](https://user-images.githubusercontent.com/130929/232197519-01f9b347-62a9-4bb3-9b0c-6e4cac944cf0.png)

**Comment by hrydgard** [comment]
Hm, in MapAxisValue, we use the abs function on a floating point value. Might be that we're getting the integer one, changing it to fabsf...

**Comment by hrydgard** [comment]
I believe this is fixed now, but you'll need to confirm :)

**Comment by stuken** [comment]
Can confirm its working as normal now.
