### ISSUE TITLE
libretro so crash

### ISSUE THREAD

**Issue by hsoftxl** [hrydgard/ppsspp#17313]
### Game or games this happens in

unknow

### What area of the game / PPSSPP

ppsspp\Core\Dialog\PSPOskDialog.cpp

line:  775

void PSPOskDialog::RenderKeyboard()
{
        
	int selectedRow = selectedChar / numKeyCols[currentKeyboard];
	int selectedCol = selectedChar % numKeyCols[currentKeyboard];

	char16_t temp[2];
	temp[1] = '\0';

	std::string buffer;

	static const u32 FIELDDRAWMAX = 16;
	u32 limit = FieldMaxLength();
	u32 drawLimit = std::min(FIELDDRAWMAX, limit);   // Field drew length limit.

	const float keyboardLeftSide = (480.0f - (24.0f * numKeyCols[currentKeyboard])) / 2.0f;
	const float characterWidth = 12.0f;
	float previewLeftSide = (480.0f - (12.0f * drawLimit)) / 2.0f;
	float title = (480.0f - (0.5f * drawLimit)) / 2.0f;

### What should happen

int selectedRow = selectedChar / numKeyCols[currentKeyboard];
	int selectedCol = selectedChar % numKeyCols[currentKeyboard];

these code has crash, Do you need to verify this code before using it？

### Platform

libretro / Retroarch

### Mobile phone model or graphics card

    motorola hawao (moto g42)

### PPSSPP version affected

39d765186697c3454df85b88bd6789025d6375f0

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Huh, interesting. Looks like this can happen if PSPOskDialog::RenderKeyboard is somehow called before PSPOskDialog::Init. But RenderKeyboard is called from ::Update , which really shouldn't be called before Init, plus, it checks for SCE_UTILITY_STATUS_RUNNING...

Still, I'll add some checks to prevent it from crashing.

**Comment by hrydgard** [comment]
I added the checks in #17318 , which is now merged. Can you check that it's fixed for you?

Also, when did it happen, playing which game?

**Comment by hsoftxl** [comment]
this is reported from carsh logs. i did not get other info.

**Comment by hrydgard** [comment]
Ok, that's alright. Pretty sure this fixes it anyway.
