### ISSUE TITLE
DUMP IMAGE - because the images are coming with 0kb

### ISSUE THREAD

**Issue by DavidSilvadeSa** [hrydgard/ppsspp#17320]
### Game or games this happens in

all

### What area of the game / PPSSPP

https://user-images.githubusercontent.com/82737672/233704958-b1a30c61-385b-41a6-8916-037648b53065.mp4

### What should happen

I've always been one to use this feature. today I had the idea of ​​making some DUMP of the textures of the games and I came across this BUG. this didn't happen before.

### Platform

Android

### Mobile phone model or graphics card

POCO X3 8GB RAM 

### PPSSPP version affected

last

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Hm, was working last I tried on PC, but haven't checked it on Android for some time. Will do.

**Comment by DavidSilvadeSa** [comment]
✨you are incredible✨

**Comment by hrydgard** [comment]
Alright, I got a repro on my S21. Looking like at least a filename mangling issue with scoped storage, it seems.  (that weird %2 at the end of filenames is related), and possibly some more trouble. Will fix tomorrow.

**Comment by hrydgard** [comment]
Should be fixed now. Thanks for spotting this one!
