### ISSUE TITLE
Can you improve the performance for GTA Vice city stories and Liberty Stories at 60 fps

### ISSUE THREAD

**Issue by Gamer123dsg** [hrydgard/ppsspp#17330]
### Game or games this happens in

GTA VCS LCS

### What area of the game / PPSSPP

When there is 60 fps , the sound slows down a lot , when 30 the game is going fine, there are a lot of fixes for the game and I wanted to play 60 fps without glitches with drops fps 

### What should happen

Fix fps drop 60 fps 

### Platform

Windows

### Mobile phone model or graphics card

gtx 1050ti 

### PPSSPP version affected

latest 

### Graphics backend (3D API)

Other

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
The game doesn't run at 60 fps normally. Are you using some cheat to get to that framerate? The slowdowns may be related to that, rather than PPSSPP itself, and if so it may help to do stuff like increasing the CPU frequency on the System tab.

**Comment by Gamer123dsg** [comment]
> The game doesn't run at 60 fps normally. Are you using some cheat to get to that framerate? The slowdowns may be related to that, rather than PPSSPP itself, and if so it may help to do stuff like increasing the CPU frequency on the System tab.

although gta 5 goes 60 fps at high settings and this is a 2006 game farts sound strange

**Comment by Panderner** [comment]
@Gamer123dsg what CPU are you using? and did you use the 60 FPS cheat?

**Comment by Gamer123dsg** [comment]
> @Gamer123dsg what CPU are you using? and did you use the 60 FPS cheat?

xeon x5450 but this game 2006 year and gta 5 hugh settings , but I will say that it used to be worse on this emulator, before the sound was very hoarse and now not so often

**Comment by Panderner** [comment]
Both GTA games are capped at 30 FPS where the most PSP games also runs at 30 FPS.

**Comment by Panderner** [comment]
> xeon x5450 but this game 2006 year and gta 5 hugh settings , but I will say that it used to be worse on this emulator, before the sound was very hoarse and now not so often

Unfortunately your CPU is too old and weak single thread performance, A recent CPU is recommended for good single thread performance.

**Comment by hrydgard** [comment]
The game is written to run at 30fps, and that's what the logic inside the game expects. Likely, your 60fps patch that you are using is missing something that needs to be changed, and it's thus a question of game logic, not performance.

60fps patches are not guaranteed to be perfect in any way.

**Comment by Gamer123dsg** [comment]
Lol widescreenifx fixes 60 fps or cleo

**Comment by Gamer123dsg** [comment]
most likely , you did not make the game work with such fps , because there is no fart sound at 30

**Comment by hrydgard** [comment]
You seem to fundamentally misunderstand how an emulator works. We run games as-is, that were written for a soon 20-year old console (the PSP). If the game runs at 30fps (syncs to the display twice per frame) on the real hardware, it will also do so on the PSP. We don't always get the exact emulated performance right, but it's about being as close as possible to the real hardware, in order to ensure compatibility with the maximum number of PSP games.

Now, some people have made hacks that disable frame syncing and maybe change some parameter for the game to run at a framerate it was not designed for. These hacks are often incomplete and don't change everything that needs to be changed.

Thus, the problem is with the 60fps cheat/hack, not the emulator.
