### ISSUE TITLE
libretro crash

### ISSUE THREAD

**Issue by hsoftxl** [hrydgard/ppsspp#17339]
### Game or games this happens in

Tekken 6 (USA)

### What area of the game / PPSSPP

![image](https://user-images.githubusercontent.com/6965803/234842875-8c4d5682-26fc-45e2-bcb2-5d76ba542dba.png)
![image](https://user-images.githubusercontent.com/6965803/234842983-299a13dd-d1f0-4045-8bac-ea0bbb416cf7.png)

### What should happen

when start game(Tekken 6 (USA)) , it crashed. i tried other game, that's well.

### Platform

libretro / Retroarch

### Mobile phone model or graphics card

VIVO IQOO NEO 5

### PPSSPP version affected

26d01288968238382d5a6fa0bcbe3dd26fb770d3

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by gouchi** [comment]
Hi,

Is it still an issue using latest update for the core ?

Also you should rename the issue to `Crash on Android ARMv8-A using Adreno 650` ?

Thank you.

**Comment by hsoftxl** [comment]
which version fixed ?

**Comment by hsoftxl** [comment]
i will check in lastest version.

**Comment by gouchi** [comment]
Yes you should check with [RetroArch](https://f-droid.org/fr/packages/com.retroarch/) from [F-droid](https://f-droid.org/F-Droid.apk).

Then Main menu > Online Updater > Download cores.

Thank you.
