### ISSUE TITLE
Edit controls for the PPSSPP menu

### ISSUE THREAD

**Issue by odeyity** [hrydgard/ppsspp#17363]
### What should happen

My controller I use has a broken down d-pad, this means that in the ppsspp menu, I can't go down so I have to use my mouse, this is fine but I would like to only use my controller. I have a button bound to pause, and want to navigate to exit and click it but I can't get there. It would be good if I could make the navigate down action a different button to the d-pad.

### Who would this benefit

People who want different controls for the PPSSPP menu

### Platform (if relevant)

None

### Games this would be useful in

None

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by NABN00B** [comment]
For quite some time now, it is also possible to navigate the menus with the left analog stick of controllers.
