### ISSUE TITLE
Syphon Filter: Logan's Shadow (NTSC & PAL) Lights Flickering

### ISSUE THREAD

**Issue by LeyoSFO** [hrydgard/ppsspp#17378]
### Game or games this happens in

UCUS98606 & UCES00710

### What area of the game

Episode 1, Part 4, The start of the level

### What happens

As shown in the video, the lights flicker in this level on both NTSC & PAL versions

https://user-images.githubusercontent.com/71053461/235503086-79d11de7-4aa5-4f21-a312-8a5c39ca3068.mp4

### What should happen

this is how it should look like on PSP

https://user-images.githubusercontent.com/71053461/235503148-cda684b4-1be6-45ef-82ff-7c091d9095e2.mp4

### Platform

Windows

### Mobile phone model or graphics card

NVIDIA 2070 Super

### PPSSPP version affected

v1.15

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Let's combine this with #17371 as the issues are likely related.

**Comment by LeyoSFO** [comment]
> Let's combine this with #17371 as the issues are likely related.
alright, thank you

**Comment by hrydgard** [comment]
Uncombining as this seems separate.

**Comment by AgentLogan1** [comment]
Turning off "Hardware Transform" stops the flickering for this mission, not sure if this workaround affects the game in other places.
