### ISSUE TITLE
Syphon Filter: Logan's Shadow (US) No Water Sound Effects

### ISSUE THREAD

**Issue by LeyoSFO** [hrydgard/ppsspp#17372]
### Game or games this happens in

UCUS98606

### What area of the game / PPSSPP

Training mission No. 5

Details:
Single Player - Training Mode - Training 5

### What should happen

When diving in water in the 5th training mission, there are no water sound effects, as opposed to every other water level in the game (Such as Episode 6 Part 1), this bug occurs on the NTSC version only, the PAL version doesn't seem to have it

### Platform

Windows

### Mobile phone model or graphics card

NVIDIA 2070 Super

### PPSSPP version affected

v1.15

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
This sounds so weirdly specific that it's probably worth checking if it's actually a game bug that also happens on real hardware, rather than an emulator bug. Have you checked?

**Comment by LeyoSFO** [comment]
> This sounds so weirdly specific that it's probably worth checking if it's actually a game bug that also happens on real hardware, rather than an emulator bug. Have you checked?

I just checked, this issue happens on real PSP as well, good call
