### ISSUE TITLE
Tilt control of D-pad is broken 

### ISSUE THREAD

**Issue by Narugakuruga** [hrydgard/ppsspp#17384]
### What should happen

Left and right D-pad should be reset in neutral tilt position 
They're the only pair of button effected by this bug. Other button is normal. 
### video

https://user-images.githubusercontent.com/31060534/235562730-8b042a3d-518a-44d5-ad74-6efea70ced28.mp4

### Platform

Android

### Mobile phone model or graphics card
Every model

### PPSSPP version affected
1.15

### Last working version
1.14

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Thanks for reporting this, confirmed. Will fix.
