### ISSUE TITLE
Star Ocean: Second Evolution: map errors with Vulkan

### ISSUE THREAD

**Issue by leoxxx** [hrydgard/ppsspp#17386]
### Game or games this happens in

ULJM-05325 Star Ocean: Second Evolution

### What area of the game / PPSSPP

As shown in the picture, map error in battle and world map with Vulkan in v1.15. I'm not sure if there are other map errors.
![V](https://user-images.githubusercontent.com/5364709/235640352-4104ed13-dea4-4962-80e4-bf3a84e72c1e.png)

![www](https://user-images.githubusercontent.com/5364709/235676919-b7117752-1cca-4e5c-8f7f-79bd6f914f59.png)

It's O.K in v1.14.

### What should happen

It's O.K. with OpenGL.
![O](https://user-images.githubusercontent.com/5364709/235640797-05019049-2e80-42c8-98d6-f9396ccf43db.png)

### Platform

Android

### Mobile phone model or graphics card

Helio X20 (MT6797+Mali-T880 MP4) Android Tablet

### PPSSPP version affected

v1.15

### Last working version

v1.14

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by leoxxx** [comment]
> Interesting! Can you get a [GE frame capture](https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump) ?

I will try it later. Now the tablet is charging.

**Comment by leoxxx** [comment]
@hrydgard 
Here is the new map error dump, it's in world map.
[1569474716.zip](https://github.com/hrydgard/ppsspp/files/11373564/1569474716.zip)

Here is the battle map error dump.
[1034509260.zip](https://github.com/hrydgard/ppsspp/files/11373581/1034509260.zip)

**Comment by hrydgard** [comment]
Both render OK on PC, gonna have to test on some phones..

**Comment by hrydgard** [comment]
Both render fine on:

- Mali G71 (Galaxy S8).
- Mali G78 (Galaxy S21).

T880 is a fairly old Mali GPU and the drivers are likely not very up to date, so I'm guessing we're hitting some depth-related driver bug. I don't think I'll be able to fix this for 1.15.1 as I might need to get a device, so re-tagging to the potential 1.15.2.

Though, there's one remaining chance to figure it out: Try various builds from https://buildbot.orphis.net/ppsspp/index.php?m=fulllist  and see what change broke it. If you start by large steps and go narrower and narrower, you should be able to find what change broke it within 10-11 tries (bisection).

**Comment by leoxxx** [comment]
[v1.14.4-188-g350cb55c6](https://github.com/hrydgard/ppsspp/commit/350cb55c63cec326a3c32dff64664fcdaa02d6cc) It's last working version.

[v1.14.4-191-g8d3a3285d](https://github.com/hrydgard/ppsspp/commit/8d3a3285daed4e73372140838c9ede0e9ad3707e) No bird. Only a shadow.
![no bird ](https://user-images.githubusercontent.com/5364709/235873801-d3bfba2e-b75d-4bca-a738-cbcbca7c1795.png)

[v1.14.4-197-g30586be75](https://github.com/hrydgard/ppsspp/commit/30586be75fc4b0a170ac4e6a0bd6cce8daca7a31) Map error is the same as v1.15.

[v1.14.4-772-gdc7f461b](https://github.com/hrydgard/ppsspp/commit/dc7f461bf77f8050ae8ae5fc4c927406298d6deb)—[v1.14.4-790-g938230e7d](https://github.com/hrydgard/ppsspp/commit/938230e7d64fe5a1826a825d42b72eef91ba615b) All game crash when start.

And I found OpenGL also have map error.
![no shadow](https://user-images.githubusercontent.com/5364709/235876648-52c23b67-918e-443b-9cc1-f37034eb105f.png)
No shadow under the bird.

![1111](https://user-images.githubusercontent.com/5364709/235876942-32ecc924-c6b1-4bdd-946a-16b38ded41d7.png)
Have shadow.

**Comment by hrydgard** [comment]
Thanks, that's useful. Can you explain what you mean by "map error"? I don't see something specifically wrong with the map?

**Comment by hrydgard** [comment]
Alright, so this is definitely a case of an old GPU driver not handling even pretty simple shader code correctly, these bugs have later been fixed obviously since on newer phones this works correctly.

The two changes are: 

- 191 https://github.com/hrydgard/ppsspp/pull/16787
- 197 https://github.com/hrydgard/ppsspp/pull/16791

The first one we've previously seen similar problems with in Raspberry Pi drivers. Might try to apply the same workaround.

Can you go into Settings/Tools/System Information and check the exact Vulkan driver version and device name (take a screenshot where it's visible)?

**Comment by leoxxx** [comment]
O.K.
![222](https://user-images.githubusercontent.com/5364709/235881737-2adc87e3-6a8e-44cc-a65c-0f8f53e88918.png)
I marked the picture. 
No shadow with OpenGL.
Have shadow with Vulkan.

**Comment by hrydgard** [comment]
Oh right, I thought you meant by "map" the overlay map on the bottom right:

<img width="235" alt="image" src="https://user-images.githubusercontent.com/130929/235882644-9d4771bc-4d53-4b99-b849-0efa650efc62.png">

Didn't see anything wrong with that.

**Comment by leoxxx** [comment]
> Alright, so this is definitely a case of an old GPU driver not handling even pretty simple shader code correctly, these bugs have later been fixed obviously since on newer phones this works correctly.
> 
> The two changes are:
> 
> * 191 [Vertex shaders: On platforms with uniform buffers, use indexing and loop over the lights. #16787](https://github.com/hrydgard/ppsspp/pull/16787)
> * 197 [Lighting code cleanup and optimization #16791](https://github.com/hrydgard/ppsspp/pull/16791)
> 
> The first one we've previously seen similar problems with in Raspberry Pi drivers. Might try to apply the same workaround.
> 
> The second one I'm surprised makes a difference.
> 
> Can you go into Settings/Tools/System Information and check the exact Vulkan driver version and device name (take a screenshot where it's visible)?

https://github.com/hrydgard/ppsspp/issues/15526
You can see them in this issue.

**Comment by hrydgard** [comment]
perfect, thanks for the link.

**Comment by hrydgard** [comment]
Alright, there should be a new build up in maybe half an hour on the buildbot with the above workaround, please test when available.

**Comment by leoxxx** [comment]
[v1.15-42-gec10c73a8](https://github.com/hrydgard/ppsspp/commit/ec10c73a85b2cdbdaa7b0b01de5e390c97bd1a1b) It's O.K.
But still no shadow with OpenGL.

**Comment by hrydgard** [comment]
Cool, thanks for testing!

We can look into OpenGL later. Can you post your system information page the way it looks if you switch to OpenGL? (The information strings are different than in Vulkan).

**Comment by leoxxx** [comment]
![Screenshot_20230503-191501](https://user-images.githubusercontent.com/5364709/235901705-0ca8f226-09a7-45dd-8af7-fa21369d2193.png)
![Screenshot_20230503-191524](https://user-images.githubusercontent.com/5364709/235901723-ca339e65-6d25-40e8-9378-16bf67ec2c45.png)

**Comment by leoxxx** [comment]
@hrydgard 
So, need I open a new issue?

**Comment by hrydgard** [comment]
Thanks!

Yeah, I guess that would make sense. I'm not likely to work on it for a while though.
