### ISSUE TITLE
Vulkan linux: selected device is ignored

### ISSUE THREAD

**Issue by thesourcehim** [hrydgard/ppsspp#17410]
### Game or games this happens in

None

### What area of the game / PPSSPP

Selecting a device for Vulkan in graphics settings seems not to have any effect on which device is really used. Judging by vulkan extension list displayed in Tools->System info->Vulkan info, ppsspp uses NVIDIA card even if Intel UHD is selected in graphics settings.

### What should happen

ppsspp should use selected device, not the default one (or whatever method used to choose the device).

### Platform

Linux / BSD

### Mobile phone model or graphics card

NVIDIA GeForce RTX 3060 Laptop GPU / Intel(R) UHD Graphics (CML GT2)

### PPSSPP version affected

v.1.15.2

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
That's weird, I know this worked a while ago. I'll take a look soon.

(Reminder to self: To get a test case, can just allow lavapipe so we have two backends to switch between)
