### ISSUE TITLE
Audio crackling with flatpak version

### ISSUE THREAD

**Issue by omanwhatiscomputer** [hrydgard/ppsspp#17418]
### Game or games this happens in

Systemwide

### What area of the game / PPSSPP

Hi, I'm running Pop OS 22.04. Running the flatpak version results in systemwide audio crackling. The audio goes back to normal after closing the application. 

However, running the application from the terminal with `PULSE_LATENCY_MSEC=60 flatpak run org.ppsspp.PPSSPP` seems to fix the issue.

Is there a way to set this option by default when I run it from GUI? (Sorry if this is a very basic question. I'm new to Linux)

Running the command `sudo flatpak override --env=PULSE_LATENCY_MSEC=60 org.ppsspp.PPSSPP` does not work.

### What should happen

Audio without crackling sound. 

Its runs fine on Windows 11.

### Platform

Linux / BSD

### Mobile phone model or graphics card

Nvidia Geforce RTX 3060

### PPSSPP version affected

v1.15.2

### Last working version

n\a

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [x] Try resetting settings or older versions and include if the issue is related.
- [x] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
This seems like a system issue rather than an emulator issue? I don't think we do anything weird in our SDL audio code.

**Comment by omanwhatiscomputer** [comment]
Fixed it by adding the environment variable  `PULSE_LATENCY_MSEC=60` using flatseal.

I really appreciate what you. Thank you.
