### ISSUE TITLE
CROSS SAVESTATE/SAVE on PC to moblie

### ISSUE THREAD

**Issue by EPIC3477** [hrydgard/ppsspp#17419]
### What should happen

Hello. Can you add a cross save between PC and moblie, because Im playing MHFU in PC and my savestate in MHFU is in my mobile device. Can you add it on next update or in future update...

### Who would this benefit

...

### Platform (if relevant)

Android

### Games this would be useful in

ULUS-10391 -  Monster Hunter Freedom Unite

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by ANR2ME** [comment]
You can just copy your savestate from your mobile phone to your PC (or vice versa).

But if you mean to have syncing feature (ie. through cloud storage or LAN) it won't be coming anytime soon i guess, since that feature was already requested long ago as i remembered.

**Comment by hrydgard** [comment]
See #1019 for the original feature request and some discussion. Not an easy one.
