### ISSUE TITLE
Include logs or screenshots of issue.

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#17417]

**Comment by unknownbrackets** [comment]
I think this was created by mistake (probably some auto-subtask-to-issue thing.)

-[Unknown]

**Comment by hrydgard** [comment]
Uh yeah, dunno what happened here

**Comment by unknownbrackets** [comment]
I think it's this, it's not my favorite new GitHub feature:
![Convert to issue button near tasks](https://user-images.githubusercontent.com/191233/236646809-5a3750cc-4ff7-4760-9fce-ee43c4bb4ed8.png)

-[Unknown]

**Comment by hrydgard** [comment]
Ah, that'd do it. Darn
