### ISSUE TITLE
Custom touch buttons can't control analog directions

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#17428]
Kind of obscure, but this seems to have broken, I thought it worked.

**Comment by iota97** [comment]
Did a quick bisect:

```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
38f4cc4cc97baf1e7c8abe1ee0ba8bb21471c863
8dabcaea7d043bea9ee07d894e959105ea987bf6
526b4f782de8226bc72389b79067b93ab0b41f35
We cannot bisect more!
```

**Comment by hrydgard** [comment]
Found two bugs here, first an oversight that was easy to fix (the actual functionality), then I found that the following doesn't work to print uint64_t values on Windows:  `StringFromFormat("0x%016lx", newValue)`. It chops off the upper 32 bits, which is where the analog direction bits were stored in the config... Fixing.
