### ISSUE TITLE
Game crashed Blue Screen 

### ISSUE THREAD

**Issue by mobileandroidpsp** [hrydgard/ppsspp#17458]
### Game or games this happens in

ULUS10438 - PANGYA Fantasy Golf

### What area of the game / PPSSPP

![Screenshot_20230514-130056](https://github.com/hrydgard/ppsspp/assets/133598682/7d3c502f-32d8-4bb3-a40b-ecae53541c34)
When I open the game, this error occurs.

### What should happen

Should play the game normally, like other games. 

### Platform

Android

### Mobile phone model or graphics card

Schok Volt SV55 v30 (armeabi-v7a)

### PPSSPP version affected

V1.15.3

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by mobileandroidpsp** [comment]
Fixed issue by disabling fast memory and enabling Simulate UMD delays. The game now plays but experiences slowdowns during gameplay. 50-70% FPS.

**Comment by Saramagrean** [comment]
Disable software skinning, can improve performance in this game.

**Comment by mobileandroidpsp** [comment]
Disabling software skinning has improved performance to 99%-100% FPS. Greatly reduced slowdowns during tutorial part, now playable to 95%-100% FPS during tuorial in game.

**Comment by hrydgard** [comment]
Did disabling Fast Memory really make a difference or was it all Simulate UMD Delays? If the latter, we should just force them on in this game.

**Comment by mobileandroidpsp** [comment]
> Did disabling Fast Memory really make a difference or was it all Simulate UMD Delays? If the latter, we should just force them on in this game.

Good question, using factory defaults with software skinning disabled and fast memory disabled, it seems that simulating UMD delays allows the game to be played without the blue error screen. Enabling fast memory and software skinning can help with performance but are not required to run the game. I used version v1.15.3.

**Comment by hrydgard** [comment]
Disabling fast memory should make it very slightly slower if anything. But often there's simply no difference and any difference could be measurement error - performance on Android is

But thanks for confirming the fast-memory setting doesn't interact with the crash. I will add this game to compat.ini to the ones that need slower disc reads, so it'll be on automatically.
