### ISSUE TITLE
Should deal with odd/little-used key mappings, add a few new ones.

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#17464]
Our current list of keymappings is getting very long. It was also recently discovered by Doolan and his friend on Discord that there are a few additional keys that presumably were available on certain devkits when plugging in a PS2 controller or similiar:

<img width="165" alt="image" src="https://github.com/hrydgard/ppsspp/assets/130929/2b975f9d-d409-4836-81e7-6a9e9d44fe82">

These can be used to enable a debug menu in Castlevania: SOTN , which was impossible to reach on the real PSP without code patches. For anyone reading this in the future, note that the debug menu requires the software renderer due to how it works.

It's possible that other games will react to these extra button inputs as well in various ways, this is not yet known.

Anyway, adding those will just increase the count even further.

The following bindings are barely used at all: CTRL_BACK, CTRL_HOLD, CTRL_REMOTE_HOLD, CTRL_VOL_UP, CTRL_VOL_DOWN, CTRL_NOTE, CTRL_DISC, CTRL_PLAYPAUSE and probably a few more.

I'd like to hide those by default, but still make it possible to map them for anyone who really wants to.

So either, we put a "Show More..." section at the end of the list (to make it feel more managably long by default), or we make it a developer option whether to show them or not, I guess.

**Comment by unknownbrackets** [comment]
I think it might be nice to categorize them, similar to how settings themselves are categorized.

It could be even in these categories, for example:
 * PSP controls (analog, d-pad, face buttons, etc.)
 * Emulator shortcuts (fast forward, pause, save states, full screen, etc.)
 * Developer tools (devmenu, texture shortcuts, frame advance)
 * Uncommon controls (PS3 only analog, L3/R3, note, screen, play/pause, etc.)

That would probably make the list easier to understand anyway.  Many other emulators completely separate this, with a dedicated interface for controls (usually only allowing 1:1 mappings, though, I think our system is better) and a separate list of shortcuts.

Potentially, we could have tabs on the left and things like auto configure, clear, etc. could be buttons under a tab as well.

That said, "show more" also seems pretty reasonable.  From my perspective, the main (only?) use of most of those you listed is for cheats or I guess plugins.  Though maybe CTRL_DISC should be involved for disc swapping...

-[Unknown]

**Comment by hrydgard** [comment]
I've added the categories, just forgot to close this.

**Comment by NABN00B** [comment]
> I've added the categories, just forgot to close this.

You've added the categories, but not the new control mappings.

**Comment by hrydgard** [comment]
Mm, fair enough. Re-opening.
