### ISSUE TITLE
Black Screen at the Credits in MGS:PW

### ISSUE THREAD

**Issue by tutasmaster** [hrydgard/ppsspp#17482]
### Game or games this happens in

ULUS10509 v1.01 Metal Gear Solid Peace Walker

### What area of the game / PPSSPP

In the `[026]Peace Walker Battle 03` boss fight, the game plays the first two cutscenes and ends on a screen that shows a quote from Immanuel Kant and loading icon. 
![image](https://github.com/hrydgard/ppsspp/assets/20562339/c6032a63-0311-4d37-a865-164fde607a57)
As the loading icon fades away, the game cuts to black with no response whatsoever.
What's interesting about this bug is that i've tried a few older versions of PPSSPP, 1.10.4, 1.14.1 and it doesn't seem to occur there.
So far I've tried:
- Resetting all of PPSSPPs System/Graphics Settings
- Disabled all cheats and ran the game without resorting to a savestate or fast forward
- Enabled/Disabled Networking settings (given the first time this happened was during CO-OP)
I cannot provide a log through Github because there seems to be a 25MB file limit, but I can send both the log (200mb) and both my Savefile and my CO-OP Buddy's savefile (around 600MBs each) that are stuck in this situation through other means if necessary.

### What should happen

The game should go along, play the credits and boot us back to motherbase.

### Logs

Debug log was too large to be sent here (around 200MB using DebugLog.bat)

### Platform

Android

### Mobile phone model or graphics card

RTX 3060Ti

### PPSSPP version affected

v1.15.3

### Last working version

v1.14.1

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment]
Instead of providing such a large logs file, you can provide a save state before the scene/location of the issue (if this also happened on single player).

**Comment by tutasmaster** [comment]
[ULUS10509_1.01_1.zip](https://github.com/hrydgard/ppsspp/files/11522086/ULUS10509_1.01_1.zip)
Thank you so much, here is a savestate as the cutscene for the mission starts. You can just skip it by pressing START and X twice, which will take you to the loading screen that appears to be freezing/black screen.

**Comment by sum2012** [comment]
You do not need to install full Data Package
you have to play from beginning.

**Comment by tutasmaster** [comment]
Woops, sorry, didn't realize that the save and the Data Package were two different files in the memory card. My bad.
Here's my finished savefile that has access to mission [026]Peace Walker 03 where the black screen occurs.
You can easily just use it
- go straight to the mission [026],
- fire a few shots at the walker in front of you,
- wait for the cutscene to start
- you can then either wait the cutscene out or skip the next two following ones
[SAVE.zip](https://github.com/hrydgard/ppsspp/files/11575926/SAVE.zip)

**Comment by unknownbrackets** [comment]
Can you try a few git builds between the two versions as well?

https://buildbot.orphis.net/ppsspp/index.php?m=fulllist

If you tried v1.14.4-768-gad5f1e633 or so, it'd be halfway between the two versions.  A few tries by halves might narrow down when it started happening by a lot.

-[Unknown]

**Comment by tutasmaster** [comment]
I tried the following versions (pardon the lack of IDs it's just downloaded whatever was available on the website):
- 768 - CRASH
- 385 - CRASH
- 191 - CRASH
- 96 - SUCCESS
- 142 - CRASH
- 119 - SUCESS
- 131 - SUCESS
- 136 - SUCESS
- 138 - FAIL

That narrows it down to a crash caused by the v1.14.4-137-gd02a79400 / v1.14.4-138-gfb0ed6e16 version with the following commit log: `Merge: 0f528204f d02a79400 Merge pull request #16765 from sum2012/mpeg-patch Trying to improve sceMpegAvcDecode`

**Comment by sum2012** [comment]
@tutasmaster how to "go straight to the mission [026]" ?

**Comment by tutasmaster** [comment]
You can use the savefile i've sent 2 comments ago, alternatively any 100% savefile of the game should do. 

- Open the game
- Select Load Game
- Once you pick the save file, the game will ask you if you want to go to mission select or to mother base, you can pick the option to go to Mission Select. (Alternatively, you can go to Mission select through Motherbase)
- From there, pick mission [026] Peace Walker 03 from the main mission list (you change lists by pressing L and R)
- Pick either the Solo or Coop option to proceed
- Pick Start Mission
- Once you load in, use whatever weapons at your disposal to do some damage to the Machine in front of you
- Wait for around 3-5 minutes for the cutscene to start 
- You can now either watch both cutscenes, or skip them both
- You should now be at the screen shown in the screenshot from the issue. As it fades to black it will either load into the credits (if it is works) or it will cut to a black screen (if it doesn't)

Sorry if I've been unclear about the issue so far. Feel free to ask me anything about it. 😅
Also worth noting I was able to replicate this issue in the 2.0 version of the game too.

**Comment by sum2012** [comment]
This one no  [026]
![1](https://github.com/hrydgard/ppsspp/assets/2177532/21684ba8-48e4-4f6c-91de-764e76c6cf79)

This one no playing,just watch video and no problem
![2](https://github.com/hrydgard/ppsspp/assets/2177532/49fa0330-d4ac-43a0-a610-770bf6e20854)

**Comment by tutasmaster** [comment]
It should be in the first tab. You showed both the 2nd and the 4th tabs respectively. In the tab where tou saw mission [028], press L once. Mission [026] should be on that list with the name "Peace Walker 03"

**Comment by sum2012** [comment]
I get game stuck in mission in the first tab "Peace Walker Battle 3" ,same instruction with @tutasmaster 
![3](https://github.com/hrydgard/ppsspp/assets/2177532/8b079bad-86d8-47f0-b491-d47b1a39d3d0)
Just a record.
A unusual log:15:03:070 Main         I[ME]: HLE\sceMpeg.cpp:462 sceMpegInit(), mpegLibVersion 0x10a, mpegLibcrc 0

**Comment by sum2012** [comment]
@tutasmaster 
I do not get blue screen but fix a freeze problem.
Please test  v1.15.4-87-g7912eef0b or newer version

**Comment by tutasmaster** [comment]
Can confirm, it fixed the issue exactly as described. Thank you very much!

**Comment by sum2012** [comment]
The video code is still a guess work, fix a game then break other games.

**Comment by calzoniemalonie** [comment]
> Can confirm, it fixed the issue exactly as described. Thank you very much!

I'm having the exact same issue, was the solution just to update the emulator? I'm already on the latest version (1.15.4) and I've tried loading my save on both Windows and the android app with no luck.

**Comment by hrydgard** [comment]
yes, you'll need to switch to a development build from https://buildbot.orphis.net/ppsspp/ or wait for 1.16.

**Comment by calzoniemalonie** [comment]
> yes, you'll need to switch to a development build from https://buildbot.orphis.net/ppsspp/ or wait for 1.16.

that worked, thanks so much!
