### ISSUE TITLE
dbz budokai another road always crashes on a certain mission

### ISSUE THREAD

**Issue by barp0** [hrydgard/ppsspp#17481]
### Game or games this happens in

dragon ball z shin budokai another road ulus10234 v1.00

### What area of the game / PPSSPP

it's the fifth part of chapter 5, when you're playing as bardock and fighting pikkon, on the loading screen. this is the first time i've played as or fought bardock, so i assume it's something that happens when loading his model or data or something?

i'm using the latest version of ppsspp on android 13, and i tried it with both rendering backends. (i tried to use the latest build too, but when i tried to update it to that it said it couldn't because it "conflicts with an existing package")

edit: updated it to the latest build properly, still doesn't work.

save data: [ULUS102340000.zip](https://github.com/hrydgard/ppsspp/files/11513666/ULUS102340000.zip)

### What should happen

it shouldn't crash.

### Platform

Android

### Mobile phone model or graphics card

32.1.0 (08001000)

### PPSSPP version affected

v1.15.3

### Graphics backend (3D API)

Other

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment]
You need to uninstalled the stable release first before installing the latest dev build.

**Comment by unknownbrackets** [comment]
This is a fairly popular game, so it's surprising to me that no one has reported this before.  I'd also recommend checking your disc CRC, in case something is corrupt on it.  You can look at the CRC and just google it to see if it's correct often enough.  It should probably be 90444e43 based on this:

https://report.ppsspp.org/game/ULUS10234_1.00

You can also see that some people have different CRCs, I think there are a lot of hacked versions of this game floating around.  Some may have bugs or problems that have nothing to do with PPSSPP.

-[Unknown]

**Comment by barp0** [comment]
yeah it doesn't match. my iso is pretty old.
