### ISSUE TITLE
Tactics Ogre LUCT Text/Font no longer dump or replace on newer versions

### ISSUE THREAD

**Issue by Serbagz** [hrydgard/ppsspp#17491]
### Game or games this happens in

ULUS-10565 Tactics Ogre: Let Us Cling Together

### What area of the game

I recently made a texture pack for Tactics Ogre LUCT and for some reason the text refuses to dump or upscale on newer versions of ppsspp. On 1.13.2 my pack works in its entirety. I tried to pinpoint the earliest version this started happening in and it is as early as the oldest build on the old build list here: https://buildbot.orphis.net/ppsspp/index.php?m=fulllist (v1.13.2-1353-g35dfd85ce)

This is the pack in case anyone would like to check on it themselves: https://forums.ppsspp.org/showthread.php?tid=26100

Upon posting about this in the ppsspp discord I was told to make an issue here on github. I have tried changing graphics api's, and nearly all forms of graphics settings already. The pack simply works perfect on 1.13.2 and simply does not upscale any of the text at all in any version after.

### What happens

The text does not dump/replace at all

### What should happen

the text should dump/replace

### Platform

Windows

### Mobile phone model or graphics card

RTX 3070TI

### PPSSPP version affected

v1.13.2-1353-g35dfd85ce and later

### Last working version

1.13.2

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [ ] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
From what I recall, this game uses mip levels for its font.  I think I'd fixed that in 39d6dc174095b3ced866fb10f2ae312253c2d5a9 (v1.13.x), but maybe it's been broken since.

-[Unknown]

**Comment by hrydgard** [comment]
Just to make this really easy to repro, could you take a [Frame dump](https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump) of a screen in the game where the saving/replacement fails?

**Comment by Serbagz** [comment]
It happens in a few places but here is the frame dump file from the name entry screen.
[ULUS10565ppdmp.zip](https://github.com/hrydgard/ppsspp/files/11541632/ULUS10565ppdmp.zip)
