### ISSUE TITLE
Using a Post processing filter will make the image to stop stretching to the max of the monitor

### ISSUE THREAD

**Issue by mcabel** [hrydgard/ppsspp#17499]
### Game or games this happens in

ULUS-10005-Darkstalkers Chronicle (usa)

### What area of the game

Anywhere in the game. It happened with other games. This seems to be emulator related.

### What happens

When changing the postprocessing filter the image will stop stretching to the extent of the monitor.

![](https://cdn.discordapp.com/attachments/480103153803460614/1110980809395028058/image.png)

I have tested wtih xbr and other filters and had the same results.

![](https://cdn.discordapp.com/attachments/480103153803460614/1110980485145956452/image.png)

### What should happen

The screen should stretch to fit. Clicking reset does not help. Resizing manually leaves black bars and possibly unevenness.

I also tested on ppsspp core on Retroarch. The result is the same, altough it resizes better (still leaving black bars).

### Platform

Android

### Mobile phone model or graphics card

nvidia 3080 ti, Windows 11

### PPSSPP version affected

ppsspp-v1.15.4-50-g12106ceb7-windows-amd64

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Yeah, I can repro this. It's specific to the specialized display method we use for this game only (due to its own stretch to the PSP's resolution, which we bypass to preserve image quality). We're indeed not correctly handling that, if the first post-processing filter is an upscaling filter, needs fixing.
