### ISSUE TITLE
Slow direction mode (Analog Limiter) for keyboard analog stick not obvious enough

### ISSUE THREAD

**Issue by UserGame3022** [hrydgard/ppsspp#17507]
### What should happen

Mode slow direction stick, example GTA vice city stories you can walk if you slow direction stick, but keyboard this impossible. Do if pressed button, stick move slow function.

### Who would this benefit

Games

### Platform (if relevant)

Windows

### Games this would be useful in

All games 

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
This exists already, it's the control mapping "Analog limiter".

However, it's not very obvious, so this is a user interface issue.

**Comment by UserGame3022** [comment]
Ok thanks

**Comment by hrydgard** [comment]
#18589 puts this in the "Control modifiers" category, making it a bit more obvious. Good enough.
