### ISSUE TITLE
Somes cutscenes are getting stuck in Metal Gear Solid Peace Walker

### ISSUE THREAD

**Issue by The-Devilman** [hrydgard/ppsspp#17512]
### Game or games this happens in

ULUS10509 V2.00 Metal Gear Solid Peace Walker

### What area of the game / PPSSPP

Some cutscenes are getting stuck but the game (sound, button functions) continue to work.
![image](https://github.com/hrydgard/ppsspp/assets/68765530/1ee7055f-5531-4522-9c55-cfa8c9bc7f36)
(In the screenshot, a snake panel was supposed to appear on the side)

Tested in all Graphics backend and still the same

Save Data:
[ULUS10509001.zip](https://github.com/hrydgard/ppsspp/files/11568785/ULUS10509001.zip)

### What should happen

The cutscene was supposed to play normally, with the other parts of the cutscene loading.

### Platform

Windows

### Mobile phone model or graphics card

Nvidia GTX 1060

### PPSSPP version affected

v1.15.2

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by sum2012** [comment]
Related to
https://github.com/hrydgard/ppsspp/issues/17482
Closing this.
The fix is coming

**Comment by sum2012** [comment]
In-case you can test my build.
[PPSSPPWindows64m.zip](https://github.com/hrydgard/ppsspp/files/11583588/PPSSPPWindows64m.zip)

**Comment by sum2012** [comment]
Just a note my fix is merged in v1.15.4-87-g7912eef0b
