### ISSUE TITLE
[Post-Processing]Supersampling AA (Gauss) squishing games to the left in certain cases

### ISSUE THREAD

**Issue by AkiraJkr** [hrydgard/ppsspp#17516]
### Game or games this happens in

Any game?

### What area of the game

More in What happens.

### What happens

https://github.com/hrydgard/ppsspp/assets/27028529/f67afee2-f20a-42e0-b678-ef3cab464197

Fast-forwarded in video, but has no effects on the end result.

Some elements of the game are squished to the left, either a video, or the rendering of the game.

Happens in all backends.
Games tested(and with issues):
Kingdom Hearts - Game always squished to the left
Phantasy Star Portable 2 - Videos squished to the left
[Black Rock Shooter - Gameplay and cutscenes squished to the left](https://i.imgur.com/Urya5Kr.png)
[Monster Hunter 3rd - Videos squished to the left](https://i.imgur.com/rBh6feo.png)
[Metal Gear Solid Peace Walker - Game squished to the left](https://i.imgur.com/J0Bsts8.png)

### What should happen

Image should fill the entire native PSP aspect ratio even with Post-Processing on.

### GE frame capture

[ULJM05775.zip](https://github.com/hrydgard/ppsspp/files/11576257/ULJM05775.zip)

### Platform

Windows

### Mobile phone model or graphics card

NVIDIA GeForce GTX 1650

### PPSSPP version affected

v1.15.4-68-g9379a6be3

### Last working version

v1.14.4-1309-gb3b8f63e5

### Graphics backend (3D API)

Other

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Does it matter which post-filter you're using? (it probably will)

**Comment by AkiraJkr** [comment]
Here's the filters where the problem exists:
- Pixel art upscalers
- Bicubic Upscaler
- PSP Color
- Scanlines (CRT)
- Spline36 Upscaler
- Video Smoothing AA

**Comment by hrydgard** [comment]
I believe that #17513 will fix at least some types of this problem, just merged it. Please test the upcoming builds.

**Comment by AkiraJkr** [comment]
Just tested in all of the post processing filters with the latest build(1.15.4-68) and nothing seems to have changed with any of the filters or games.

**Comment by hrydgard** [comment]
-68 is not enough, that commit got in in -75.

**Comment by AkiraJkr** [comment]
Fixed with -75, closing the issue!
