### ISSUE TITLE
Castlevania Symphony of the Night Flickering

### ISSUE THREAD

**Issue by AcerUp** [hrydgard/ppsspp#17517]
### Game or games this happens in

ULUS-10277 Castlevania: The Dracula X Chronicles

### What area of the game / PPSSPP

• PPSSPP version: 1.15.4
• Device used : PC
• Device Operating System: Windows 11
• Device specs : Ryzen 7950X, Gigabyte 4090, 128 gb DDR5
• Game(s) you experience the issue with: SOTN - Castlevania: The Dracula X Chronicles version
• Rendering Backend used : All three, but currently Vulkan
• General list of PPSSPP settings used: Default
• The last PPSSPP version that worked correctly: Cannot remember
• The issue itself in detail: If one closes the game and restarts it, every now and then the screen graphics (besides alucard) will flicker. This also leaves "artifacts" of damage numbers on the screen if a monster is attacked wherever the flickering takes place. Sometimes it works perfectly, other times the flickering happens on the moment of loading a save.
<img width="1713" alt="part 4" src="https://github.com/hrydgard/ppsspp/assets/121002936/065d74bb-e497-424d-a71a-e1e43d761fea">
<img width="1847" alt="part 3" src="https://github.com/hrydgard/ppsspp/assets/121002936/02070bc4-562b-48a9-a0eb-d5c15250ec53">

### What should happen

The flickering should not be present upon loading and reloading a save repeatedly.

### Platform

Windows

### Mobile phone model or graphics card

GeForce RTX™ 4090 GAMING OC 24G (rev. 1.0 / 1.1) 

### PPSSPP version affected

1.15.4

### Last working version

1.15.4

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
Not saying it should be required, but does this work better under the software renderer, or does the same thing happen?

You noted "The last PPSSPP version that worked correctly: Cannot remember".  Do you remember if this wasn't happening before (even if you don't remember when)?  Or are you not sure if it was happening before as well?

If it was working at some point and some change made it stop working, it's usually easier to find a way to fix it.  If it was never working, that doesn't mean it's always harder - but it often is.

-[Unknown]

**Comment by Fivavoa** [comment]
Thankfully someone ran into this issue as I am also having this issue. I'm using nightly 1.15.4-121-g27b8d27ef

Every single Hardware rendererer has the flickering issue and has equally an inconsistent time fixing itself. Sometimes it eventually does after messing around with settings somehow. Unsure what triggers it being fixed, however for some reason if you die at all after it's fixed or reset in some way (I guess going to the title or menu triggers it?) it returns to being broken and flickers.

This does not happen whatsoever on the software renderer.

**Comment by hrydgard** [comment]
Any chance you could try a bunch of versions in betwee, from https://buildbot.orphis.net/ppsspp/index.php?m=fulllist , and see approximately when it started happening?

**Comment by AcerUp** [comment]
Looking through the builds, I confirm that v1.13.2-2148-gf4ea78c03 does not have the issue at all. I'm currently sifting through the builds to see the patest verison that still works after that.

**Comment by AcerUp** [comment]
Identified the culprit: ppsspp-v1.14.4-604-g99b2349d6-windows-amd64 is the first one that causes the flickering.

**Comment by hrydgard** [comment]
Very nice to have that narrowed down!

Thus, this PR is the culprit:

https://github.com/hrydgard/ppsspp/pull/16971

I wonder how that one interacts with this game ...

**Comment by Fivavoa** [comment]
Also, ppsspp-v1.14.4-602-g5a39ad31b-windows-amd64 being without issue isn't 100% accurate. Testing on hardware causes the BORDER to flicker now, not the gameplay. At least it only happens when you load a state.

Another unfortunate issue is that some kind of sprite warping affect is corrupted.
![ULUS10277_00000](https://github.com/hrydgard/ppsspp/assets/29827600/ba637397-786e-49d3-ab8f-f225bab0dd0b)
It sometimes gets fixed somewhat (where instead it just copies some visual state the game was before for some reason? Like it saves a snapshot and that snapshot is what gets warped. A good example is if your afterimage was near the center of the screen, and you did the ability initially there, and then try it again nowhere near the center, that afterimage will show up every time in the center in that small warp effect box.) But I'm unsure the exact settings/scenarios that cause this as it feels inconsistent whether it works or not.
