### ISSUE TITLE
Combo keys for keyboard 

### ISSUE THREAD

**Issue by UserGame3022** [hrydgard/ppsspp#17510]
### What should happen

If I pressed one button, pressed combo keys 

### Who would this benefit

All 

### Platform (if relevant)

Windows

### Games this would be useful in

All games 

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
This is already possible. You can map the same key to two things, try it!
