### ISSUE TITLE
Armored Core Last Raven Portable stuck at "Now Loading" screen in some missions

### ISSUE THREAD

**Issue by Algester** [hrydgard/ppsspp#17526]
### Game or games this happens in

NPUH-10024

### What area of the game / PPSSPP

When accepting the Seize the Airstrip mission in Last Raven the game will just be stuck in a "now loading" loop

however destroy the ECM generators mission loads fine
[NPUH10024ACLRSAVELIST00.zip](https://github.com/hrydgard/ppsspp/files/11584184/NPUH10024ACLRSAVELIST00.zip)
uploaded is my savefile

tested in 1.15.4 release and liberto release to the same issue

now I tried to use some debug options and nothing shady seems to be happening or that I do not know how to use the logs

### What should happen

normally the mission should load but there might be other things at play

### Platform

Windows

### Mobile phone model or graphics card

nVidia RTX 3050

### PPSSPP version affected

v1.15.4

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by sum2012** [comment]
I test no problem,make sure the ISO of CRC same as mine
![1](https://github.com/hrydgard/ppsspp/assets/2177532/fb7df51f-7481-459e-bd12-e0ee8ed0dfb4)

**Comment by Algester** [comment]
Ok will do I was playing with the undub version so that might have been the issue
