### ISSUE TITLE
PPSSPP private keys

### ISSUE THREAD

**Issue by gameblabla** [hrydgard/ppsspp#17521]
As some of you may be aware,  the Dolphin project got a DMCA takedown from Nintendo through Valve/Steam due to it (allegedly) shipping the Wii common key in hardcoded form.

I was looking through PPSSPP to see if it was using private keys as alleged by some people and it appears that it does here through libkirk :
https://github.com/hrydgard/ppsspp/blob/0c40e918c92b897f745abee0d09cf033a1572337/ext/libkirk/kirk_engine.c#L36

Perhaps someone should do something about it to avoid potential issues in the future, no ?

**Comment by hrydgard** [comment]
We have not had any issues with Sony about these, and don't expect to. 

Additionally, we have no ambitions to get on Steam.
