### ISSUE TITLE
Need for Speed Carbon OTC (USA) - graphics glitch when "overspeed" effect shows up

### ISSUE THREAD

**Issue by DavidSilvadeSa** [hrydgard/ppsspp#17522]
### Game or games this happens in

ULUS-10114

### What area of the game

I remember a period when this problem was actually happening.

and I remember that ❤️Henrik Rydgård❤️ identified this problem and soon after the problem was solved.

I downloaded the latest update v1.15.4-83-gc533187e2 and I noticed that there is a regression in NEED FOR SPEED CARBON OTC.

https://github.com/hrydgard/ppsspp/assets/82737672/c90186c6-ecea-4b09-8b57-352586d4e2e5

### What happens

the moment the car is too fast the game's graphics start to break.

when using NITRO the graphic problem gets better.

### What should happen

So far the only problem I've encountered is the graphics crashing when the car is too fast.

### Platform

Android

### Mobile phone model or graphics card

POCO X3 PRO 8GB RAM

### PPSSPP version affected

v1.15.4-83-gc533187e2

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
#15940 is the old issue, though a bit of a different visual glitch.

That already contains a nice couple of .ppdmp that we can use to debug. However, none of those reproduce this new bug, at least on PC. Could you grab another framedump?  https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

**Comment by DavidSilvadeSa** [comment]
[ULUS10114.zip](https://github.com/hrydgard/ppsspp/files/11614739/ULUS10114.zip)

**Comment by BiZkViT96** [comment]
Not exclusive to Android and Carbon, on Windows Vulkan backend another NFS games has the same bug. Here is dump from Need for Speed Underground Rivals on Windows, Vulkan API, Intel UHD 770, driver v4382. OpenGL doesn't have this bug.

![ULUS10007_00000](https://github.com/hrydgard/ppsspp/assets/88586431/0e6a1aab-cffc-49c6-a37f-9fd460f8dc08)
[ULUS10007_0001.zip](https://github.com/hrydgard/ppsspp/files/11702132/ULUS10007_0001.zip)

ppsspp-v1.15.4-133-g733b7b0de-windows-amd64

**Comment by hrydgard** [comment]
I think this will have been fixed with #17582, please test when the builds with it are out.
