### ISSUE TITLE
Metal Gear Peace Walker Black Screen

### ISSUE THREAD

**Issue by Tuxino** [hrydgard/ppsspp#17550]
### Game or games this happens in

ULUS10509 v2.00

### What area of the game / PPSSPP

Hi, I think I have discovered a game breaking bug in Peace Walker that occurs just before the ending credits.

This happens in the cut-scenes that occur after the "Peace Walker Battle 3" mission

The last thing I see is this text before the screen fades to black and doesn't recover.

![image](https://github.com/hrydgard/ppsspp/assets/9896576/4688c77d-0644-42bd-8d3c-7763fac180c5)

### What should happen

Should allow the credits to roll and progress to the end of the mission

### Platform

Android

### Mobile phone model or graphics card

Lenovo K5 Pro (Snapdragon 636, Android 8)

### PPSSPP version affected

v1.15.4

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [x] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment]
It never worked before? (since you didn't mentioned the last working version)

Have you tried the latest git/dev build from https://buildbot.orphis.net/ppsspp/ ? (you may need to uninstalled the release version first before installing git/dev build)

**Comment by Tuxino** [comment]
Hello,

Yes I am quite new to the emulator and have never had this problem before.

I tried to install the build ppsspp-v1.15.4-131-g1ff579e53-android.apk
earlier today and got an error when installing it. I did not realize that I
needed to uninstall previous versions to use this build.

In any case, good news. This build does in fact fix the bug I raised!
Please close this at your convenience.

For now I will stick with this build. How will I know when I can use the
one from the Play store again?

Thanks for the help and the awesome emulator. I recently purchased the gold
version and world like to install it again when I can.

David

**Comment by sum2012** [comment]
It should fixed in #17524  (v1.15.4-87-g7912eef0b )

**Comment by hrydgard** [comment]
The next play store update will likely be sometime after the summer.

Thanks by the way!

**Comment by Tuxino** [comment]
Thank you I will look forward to it
