### ISSUE TITLE
add an option to overclock emulated GPU?

### ISSUE THREAD

**Issue by Deka710** [hrydgard/ppsspp#17551]
### What should happen

theres an option to overclock emulated CPU so why not adding for the GPU one? or maybe its not needed

### Who would this benefit

.

### Platform (if relevant)

None

### Games this would be useful in

.

### Other emulators or software with a similar feature

.

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by unknownbrackets** [comment]
The GPU seems to always run at about half the mhz of the CPU, which is what we simulate.  So the current setting changes the clock of both.  We don't currently simulate GPU timing very well, so currently a setting to separately under/overclock the GE would just result in disappointment....

-[Unknown]

**Comment by hrydgard** [comment]
Actually, I kinda disagree - while setting the frequency exactly isn't very meaningful, most games mainly control their timing by counting frames and not timing the GPU, and having an option to overclock the GPU by some arbitrary large amount for example could be interesting to play with, in cases where the GPU not keeping up causes dropped frames. That said, the design of such a feature needs some consideration, if it is to be implemented, and a problem is that some games really do work best when the GPU speed isn't way off.
