### ISSUE TITLE
PPSSPP automatically launch as superuser in Linux

### ISSUE THREAD

**Issue by Higxyz** [hrydgard/ppsspp#17576]
### Game or games this happens in

none

### What area of the game / PPSSPP

I recently installed PPSSPP from the Software Manager as a flatpack in Linux Mint 20.1. The application never wanted any elevated privileges, not even for the installation, but still always runs as superuser, at least that shows at the top of the applications windows (after the apps name). But according to the Task Manager, PPSSPP is not running as superuser. So maybe it is just a wrong display, or my system "randomly" gives privileges to apps (I tried multiple apps, but just PPSSPP has that problem).
So it is a bug, a "feature" or I just broke my system?

### What should happen

it shouldn't open as superuser

### Platform

Linux / BSD

### Mobile phone model or graphics card

intel HD

### PPSSPP version affected

v1.15.4

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Really no idea. Nothing is intentionally done that sounds anything like this.

**Comment by unknownbrackets** [comment]
Normally if you're not running using privileges, wouldn't this require the executable to be setuid?  It sounds like some packaging issue.

Does it happen if you compile PPSSPP?

-[Unknown]

**Comment by Higxyz** [comment]
It seem the issue is with the marco windows manager, which detects random flatpacks as superuser. Changing the windows manager (to metacity or compiz) solves the problem.
