### ISSUE TITLE
Hw scaler not displaying full

### ISSUE THREAD

**Issue by Gelo021** [hrydgard/ppsspp#17586]
Hello again just gonna ask if its normal for the hw scaler to zoom and out of the screen see the video

https://github.com/hrydgard/ppsspp/assets/67460268/6167922d-d294-480c-8e78-17375fb244d6

**Comment by Gelo021** [comment]
@hrydgard

**Comment by hrydgard** [comment]
Yeah, it has some bugs and is quite complex. That's why I tried to remove the feature but had too many complaints when I did...

Will look at it again in the near future.
