### ISSUE TITLE
Final fantasy type 0

### ISSUE THREAD

**Issue by IrfanH495** [hrydgard/ppsspp#17581]
### Game or games this happens in

NPJH50443 - FINAL FANTASY 零式 ディスク１

### What area of the game

main menu & new game

### What happens

![Screenshot_20230615-101613_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/fa4ba740-7670-4974-816f-902092d5cc76)

### What should happen

last time I tried version 1.15.3-54
both games are fine.
![Screenshot_20230615-102942_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/1e635caa-aedf-4533-9b1e-be3e40b430dc)
![Screenshot_20230615-103016_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/3b527028-c9a8-4770-8aa4-a5d2d78fa6c6)

I've tried looking for the first issue that appears but can't find it.
I don't know the title for the issue, so please change it.
![Screenshot_20230615-102829_ZArchiver](https://github.com/hrydgard/ppsspp/assets/78854859/894c4bdb-b276-4fbb-80b1-928a126ce212)

### Platform

Android

### Mobile phone model or graphics card

samsung m20

### PPSSPP version affected

ppsspp-v1.15.4-166-g22632b82b-android

### Last working version

1.15.3-54

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by IrfanH495** [comment]
lego pirates of the caribbean
![Screenshot_20230615-101639_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/fe2e9379-1003-41b1-bf0b-44b133c3b51f)

**Comment by IrfanH495** [comment]
GE frame capture
[lego pirates of the caribbean ULUS10575.zip](https://github.com/hrydgard/ppsspp/files/11752855/lego.pirates.of.the.caribbean.ULUS10575.zip)
[final fantasy type 0 NPJH50443 (1).zip](https://github.com/hrydgard/ppsspp/files/11752857/final.fantasy.type.0.NPJH50443.1.zip)

**Comment by IrfanH495** [comment]
in version 1.15.4-35 both games are still normal,
my internet data package is exhausted
![Screenshot_20230615-145952_Chrome](https://github.com/hrydgard/ppsspp/assets/78854859/33c0439a-bf1f-4111-ab3b-8a56c3c4d531)
i will try again later.🙏🙏🙏🙏

**Comment by hrydgard** [comment]
Thanks, that already helps a lot! Don't have to test more :)

**Comment by IrfanH495** [comment]
last info 
in version 1.15.4-51 everything is still normal.
in version 1.15.4-71 issues have started in both games,I didn't try the version below 71.

**Comment by hrydgard** [comment]
Yeah, I've figured out what the problem is. Fix coming soon
