### ISSUE TITLE
Controller not working properly

### ISSUE THREAD

**Issue by Gelo021** [hrydgard/ppsspp#17585]
As you can see on the video only analog and direction button is working even tho i set up the buttons according to my controller

https://github.com/hrydgard/ppsspp/assets/67460268/f979f1ec-6706-4eb0-bfac-e60cd658c186

Other buttons are not responding

**Comment by hrydgard** [comment]
Hm, it looks like you're unintentionally getting multi-mappings... that's not good. Do you have another controller connected?

**Comment by Gelo021** [comment]
No @hrydgard,ive been using this controller seen, i only get this problem now i also notice that other keymap been add dont know why, its only pad last time then it has other key

**Comment by Gelo021** [comment]
I dont have this issue lat time hmmm

**Comment by Gelo021** [comment]
Ill try older one

**Comment by Gelo021** [comment]
https://github.com/hrydgard/ppsspp/assets/67460268/5826f444-fa9b-44a4-9b1d-64bf5ea8d8b8

Found out that v1.15.4 dnt have this issue

**Comment by GoldenPPSSPP** [comment]
I have the same issue with gold ppsspp v1.15.4 when I try to map L2 and R2 triggers, using a ps4 controller on windows.
I tested lower versions... v1.13.XX and v1.14XX and I don't have any issues while mapping the controller.

**Comment by Jetup13** [comment]
Tested both dev and stable builds on the Retroid Pocket 3+. Seems to only happen on dev builds. In-fact, controlling the UI with controls doesn't work as intended:
 
> L1 & R1 = Skips tabs twice

> A button = Backs out

> D-Pad, Analog Sticks, Start, Select, & B/X/Y = Don't work

Navigating & changing controls in Settings > Controls > Control Mapping shows triple or double input on some buttons

Triple input:

> Face buttons, L2. R2, Start, & Select

Double input:

> L1 & R1

In game controls work fine.

Stable release is fine 🤷

**Comment by IrfanH495** [comment]
> Tested both dev and stable builds on the Retroid Pocket 3+. Seems to only happen on dev builds. In-fact, controlling the UI with controls doesn't work as intended:
> 
> > L1 & R1 = Skips tabs twice
> 
> > A button = Backs out
> 
> > D-Pad, Analog Sticks, Start, Select, & B/X/Y = Don't work
> 
> Navigating & changing controls in Settings > Controls > Control Mapping shows triple or double input on some buttons
> 
> Triple input:
> 
> > Face buttons, L2. R2, Start, & Select
> 
> Double input:
> 
> > L1 & R1
> 
> In game controls work fine.
> 
> Stable release is fine 🤷
> 
> * Haven't tested my other controllers/devices

I also experienced it on samsung m20 android 10.

**Comment by IrfanH495** [comment]
@hrydgard 
ppsspp-v1.15.4-50-g12106ceb7-android all controls are still normal
ppsspp-v1.15.4-105-g487d7856a-android i can't control ppsspp menu using gamepad
i didn't try below version

**Comment by IrfanH495** [comment]
I think it's a different issue I just can't control the ppsspp menu all Control Mapping everything works normally

**Comment by IrfanH495** [comment]
@Gelo021 I mean comment Jetup13 moving the ppsspp menu using the d-pad.
by the way what device are you using.?

**Comment by Gelo021** [comment]
> @Gelo021 I mean comment Jetup13 moving the ppsspp menu using the d-pad. by the way what device are you using.?

Yes thats what i mean too. Cant controll at menu, old verson do so just waiting for hrydgard to fix this im gonna stick on the older once

**Comment by IrfanH495** [comment]
i don't know this helps or not
ppsspp-v1.15.4-71-gc2fb81572-android still able to control menu using gamepad
ppsspp-v1.15.4-80-g4704bc92a-android the ppsspp menu cannot be controlled using a gamepad.

**Comment by IrfanH495** [comment]
it's a different issue i tried the version ppsspp-v1.15.4-80-g4704bc92a-android does not experience multi-mappings.
@hrydgard sorry, do I have to create a new issue.

**Comment by hrydgard** [comment]
Nah it's alright. I'll look at this soon, just very busy with retroachievements. You can use an older version in the meantime.

**Comment by Gelo021** [comment]
/

**Comment by sekushi18** [comment]
haven't tried dev build. but since 1.13 even 14 and 15. retried my ps5 controller has been also getting this issue some have triple, double buttons as well. hopefully next version/revision fixes this. as it's my only PlayStation controller. I don't want to re tape paper PS buttons on my xb360 again. Sorry to add more to this.

**Comment by IrfanH495** [comment]
just info might help.
ppsspp-v1.15.4-150-g5ae9c9c64-android still normal
ppsspp-v1.15.4-154-g10ae6f099-android getting multi-mappings.
for L2 & R2 I don't know, never tried to use it.

**Comment by hrydgard** [comment]
Interesting, then #17570 likely affects it. Also possibly related to #17641.

I will fix all of this up soon.

**Comment by Gelo021** [comment]
Thank for your hard work @hrydgard

**Comment by hrydgard** [comment]
cheers, thanks for reporting the problem.

**Comment by sekushi18** [comment]
(sorry to necro this closed, mine is by info added x64 pc sorry.)

**Comment by hrydgard** [comment]
@sekushi18 please file a new issue instead.
