### ISSUE TITLE
Browse button not showing UI on some devices

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#17590]
I've gotten a few reports of this lately, latest one was a Galaxy A13 on Discord, upgraded to Android 13.

Apparently this is what happens when you press browse:

> well, the screen does pause like for like maybe a second when i press the browse button, but other than that, nothing else. 

really not sure what could be the cause here..

**Comment by ANR2ME** [comment]
I wondered whether they use File Managers that took advantage of the SAF loophole which got fixed on Android 13 https://blog.esper.io/android-dessert-bites-28-file-manager-loophole-closed-73891524/

**Comment by hrydgard** [comment]
Without a concrete way to reproduce this, I don't really know what to do here. Moving this to 1.18..

**Comment by hrydgard** [comment]
So the issue where it just pauses is fixed, but the similar issue where you get a Java exception is still a problem.

I documented it here: https://www.ppsspp.org/docs/troubleshooting/cant-pick-folder/

But I don't think there's much we can really do, the problem is outside of the emulator. Closing.
