### ISSUE TITLE
Tales of the World Radiant Mythology 2 stuck on "Now Loading"

### ISSUE THREAD

**Issue by KoopersKuzunoha** [hrydgard/ppsspp#17593]
### Game or games this happens in

ULJS00175 - TALES OF THE WORLD RADIANT MYTHOLOGY

### What area of the game / PPSSPP

Whenever I enter a new area/exit an area in the game, the game just hangs on the "NOW LOADING" screen.

### What should happen

The game should let me progress as normal or let me return to the world map.

### Logs

[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/11779658/ppsspplog.zip)

### Platform

Windows

### Mobile phone model or graphics card

AMD radeon  Vega 8 Graphics

### PPSSPP version affected

v1.15.4

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by sum2012** [comment]
[ULJS00175-000.zip](https://github.com/hrydgard/ppsspp/files/11780186/ULJS00175-000.zip)
I test no problem in v1.15.4-190-g5b4fa06b0-windows-amd64 using my save
![1](https://github.com/hrydgard/ppsspp/assets/2177532/dc65d7b5-460c-4509-abb3-2a0aeb7521dd)
What is your crc of your game ?

**Comment by sum2012** [comment]
I assume @KoopersKuzunoha is using English patched ISO.

**Comment by sum2012** [comment]
I test english patch v0.3 no problem,I am closing the issue,
