### ISSUE TITLE
Danball Senki Boost some buttons swapped X/O

### ISSUE THREAD

**Issue by IrfanH495** [hrydgard/ppsspp#17622]
### Game or games this happens in

ULJM05990 - ダンボール戦機ブースト

### What area of the game / PPSSPP

menu and several other places

https://github.com/hrydgard/ppsspp/assets/78854859/8bc9d47a-da54-4140-81f8-a0bf7d1743aa

### What should happen

The button should work normally, the issue is similar #15663

### Platform

Android

### Mobile phone model or graphics card

Samsung M20

### PPSSPP version affected

ppsspp-v1.15.4-267-gf02ccfc6d-android

### Last working version

.

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by IrfanH495** [comment]
can use the circle button, if i set the confirm button to O and restart the game.

**Comment by hrydgard** [comment]
What happens on the real PSP? Does the game respect the O/X setting properly?

**Comment by unknownbrackets** [comment]
I would guess this is just exactly what happens on an actual PSP.

-[Unknown]

**Comment by hrydgard** [comment]
That said, if the game misbehaves with the accept option set to X, we might want to enforce the other way around. Think we already have a compat flag for that.

**Comment by hrydgard** [comment]
I set the option to enforce circle as confirm. Should resolve the issue, please try the latest build from https://buildbot.orphis.net/ppsspp/ when available and confirm.

**Comment by IrfanH495** [comment]
try on version ppsspp-v1.15.4-268-g5e565cff3- it worked, thanks.

**Comment by Panderner** [comment]
They forgot original Danball Senki (ULJS00361)

**Comment by IrfanH495** [comment]
@Panderner create a new issue, I found another game with a similar issue.

**Comment by hrydgard** [comment]
@IrfanH495 Just post the ID here, it's such a small thing. Though if you want to create a new issue, that's fine too.

**Comment by hrydgard** [comment]
I pushed a change to do this in original Danball Senki too.

**Comment by IrfanH495** [comment]
@hrydgard Shining Blade NPJH50530

https://github.com/hrydgard/ppsspp/assets/78854859/a18ea166-b493-4fff-bc31-06eff923759d

**Comment by hrydgard** [comment]
Done.
