### ISSUE TITLE
(Xbox UWP) On-screen Keyboard is not working

### ISSUE THREAD

**Issue by GABO1423** [hrydgard/ppsspp#17639]
### Game or games this happens in

None

### What area of the game / PPSSPP

When trying to change certain settings that require the user to type something (like changing the nickname of the PSP, or logging into RetroAchievements), no keyboard appears on screen. A USB Keyboard was tested and while it could control the UI just fine, it also did not work for typing stuff in. This issue occurs on the UWP port when used on an Xbox console, but I can't say if it works on Windows computers or not.

### What should happen

We can type when needed, with a USB keyboard or a controller.

### Logs

N/A

### Platform

UWP / Xbox

### Mobile phone model or graphics card

Xbox Series X GPU

### PPSSPP version affected

v1.15.4 (Commit c66182a)

### Last working version

None.

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment]
Does enabling "Use system native keyboard" from System setting makes a difference?

**Comment by GABO1423** [comment]
Can confirm the keyboard does not work on Windows either.

**Comment by Keviddle** [comment]
Can confirm that this problem also exists on iOS. I can't login to RetroArch because there is no on screen keyboard and physical keyboards like bluetooth keyboards get ignored

**Comment by MelvinSmiley** [comment]
Still doesn't work om 1.17.1-933 in monster hunter pr3rd for example, no idea why this is closer.
