### ISSUE TITLE
Menu navigation regression

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#17641]
Just a reminder to fix. Renan007 reported on Discord:

> I don't know why but when I try to navigate the menu using the controller (GameSir T3s) it doesn't work but in the game it works, before it was working but I don't know from which version it stopped working, my device is Moto G5

> I tested it in this version (https://buildbot.orphis.net/ppsspp/index.php?m=dl&rev=v1.15.4-71-gc2fb81572&platform=android) and menu navigation still works but in this version (https://buildbot.orphis.net/ppsspp/index.php?m=dl&rev=v1.15.4-80-g4704bc92a&platform=android) it stopped working

**Comment by IrfanH495** [comment]
similar issue #17585

**Comment by hrydgard** [comment]
So this is either #17514 or #17375 , can't tell from that range. I'll investigate.
