### ISSUE TITLE
Add nomedia flags to PPSSPP Homebrew Store titles

### ISSUE THREAD

**Issue by Jaffacakelover** [hrydgard/ppsspp#17711]
### What should happen

When a game is installed from the PPSSPP Homebrew Store, several of the titles add their images into the Android Gallery.
A minor annoyance; could this be fixed by adding a `.nomedia` file into the pack's image directories?

<table>
    <tr>
        <td><b>Title</b></td>
        <td><b>Gallery files?</b>*</td>
        <td><b>PPSSPP.dl?</b>**</td>
    </tr>
    <tr>
        <td>Cave Story</td>
        <td>No</td>
        <td>No</td>
    </tr>
    <tr>
        <td>Ozone</td>
        <td>No</td>
        <td>Yes</td>
    </tr>
    <tr>
        <td>Kosmodrones</td>
        <td>No</td>
        <td>No</td>
    </tr>
    <tr>
        <td>Webfest</td>
        <td>No</td>
        <td>Yes</td>
    </tr>
    <tr>
        <td>Battlegrounds 3</td>
        <td>No</td>
        <td>Yes</td>
    </tr>
    <tr>
        <td>Mega Drops</td>
        <td>No</td>
        <td>Yes</td>
    </tr>
    <tr>
        <td>Mega Drops 2</td>
        <td>No</td>
        <td>Yes</td>
    </tr>
    <tr>
        <td>PSP-Flower</td>
        <td>No</td>
        <td>No</td>
    </tr>
    <tr>
        <td>rROOTAGE</td>
        <td>Yes</td>
        <td>No</td>
    </tr>
    <tr>
        <td>Yellow Rose of Texas</td>
        <td>No</td>
        <td>No</td>
    </tr>
    <tr>
        <td>Planet Hively</td>
        <td>No</td>
        <td>No</td>
    </tr>
    <tr>
        <td>Suicide Barbie</td>
        <td>No</td>
        <td>Yes</td>
    </tr>
    <tr>
        <td>Trigonometry Wars</td>
        <td>Yes</td>
        <td>No</td>
    </tr>
    <tr>
        <td>Chuckie Egg</td>
        <td>No</td>
        <td>No</td>
    </tr>
    <tr>
        <td>Breakout</td>
        <td>Yes</td>
        <td>No</td>
    </tr>
    <tr>
        <td>Attack of the Mutants</td>
        <td>Yes</td>
        <td>No</td>
    </tr>
    <tr>
        <td>LameCraft Mod 0.8</td>
        <td>Yes</td>
        <td>No</td>
    </tr>
    <tr>
        <td>Psp Revolution 0.3a</td>
        <td>Yes</td>
        <td>No</td>
    </tr>
</table>

	
\* Adds image files in a game-specific folder
** Adds /Internal storage/PPSSPP/PPSSPP.dl

### Who would this benefit

Android users.

### Platform (if relevant)

Android

### Games this would be useful in

Ozone, Webfest, Battlegrounds 3, Mega Drops, Mega Drops 2, rROOTAGE, Suicide Barbie, Trigonometry Wars, Breakout, Attack of the Mutants, LameCraft Mod 0.8, Psp Revolution 0.3a

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
Yes, this we should absolutely do. Though, .nomedia are recursive, or at least should be. So putting one in /PSP/GAME might be enough?

**Comment by Jaffacakelover** [comment]
Yes, that would catch everything except PPSSPP.dl.

I've also done a quick check, and I'm glad that texture dumping doesn't add hundreds of files to the Gallery!

**Comment by hrydgard** [comment]
Oh, the download temp file? That one shouldn't be much of an issue, should it?

**Comment by Deka710** [comment]
yeah i had to create .nomedia file on android to prevent texture pack flooded my gallery

**Comment by Deka710** [comment]
like this
![Screenshot_2023-07-14-15-08-08-162_com mi android globalFileexplorer](https://github.com/hrydgard/ppsspp/assets/97207704/e743ef19-3b80-48ad-886b-f2b271f52f18)

**Comment by hrydgard** [comment]
I'm gonna make it auto-create one inside the PSP directory directly. I don't think you ever want media scanners anywhere in there...

**Comment by hrydgard** [comment]
Unknown made a good point that users might want the screenshots directory to show up. So I've simply made sure we create .nomedia files in a few more directories instead.

If someone is missing screenshots in their gallery, just delete /PSP/.nomedia.
