### ISSUE TITLE
Launching ppspp from intent , causing iso corrupt

### ISSUE THREAD

**Issue by topanrizkyr** [hrydgard/ppsspp#17733]
### Platform

Android

### Compiler and build tool versions

Cmake  3.22.1

### Operating system version

Windows 11

### Build commands used

-

### What happens

I receive the following error

![IMG-20230716-WA0009](https://github.com/hrydgard/ppsspp/assets/93650443/b2b0bf77-016b-4fbc-8f96-3d115841e063)

When launching ppsspp from intent , using shorcut_param with path to iso from storage as mentioned here #11967

### PPSSPP version affected

1.15.4

### Last working version

-

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] Make sure to run `git submodule update --init --recursive` before building.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try deleting the build directory and running the build again.
- [ ] Check GitHub Actions, which builds every merge and PR.
- [ ] Include logs and help us reproduce.

**Comment by ANR2ME** [comment]
Have you tried using the full path? like `/storage/emulated/0/Download/`

**Comment by hrydgard** [comment]
Due to scoped storage restrictions since Android 11 (for apps that target API 30 or later, which we have to do to be on Play), we can't open files by path like that anymore. Instead I think you need to send the ISO as some sort of document URI that gives PPSSPP permission to read it. You're gonna have to do your own research - but when you figure it out, please do post here :)

**Comment by topanrizkyr** [comment]
> Due to scoped storage restrictions since Android 11 (for apps that target API 30 or later, which we have to do to be on Play), we can't open files by path like that anymore. Instead I think you need to send the ISO as some sort of document URI that gives PPSSPP permission to read it. You're gonna have to do your own research - but when you figure it out, please do post here :)
> 
> Although, I should fix that error message, it's wrong.

Okay its seems like hars to implement , but thanks maybe i will not implementing it yet , it really hard for me as new programmer xD

**Comment by hrydgard** [comment]
@topanrizkyr  Actually I don't think it's that difficult. Follow the example in the last post in #17416 , you'll just have to figure out how those command line parameters translate to an intent.

I asked ChatGPT how to do it, see here: https://chat.openai.com/share/2b64ea9d-9a42-4415-bee5-253f848b96ae 

Its output:

```java
import android.content.Intent;
import android.net.Uri;

public class MyActivity extends Activity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        // ...
        openPpssppActivityWithFileUri(fileUri);
    }

    private void openPpssppActivityWithFileUri(Uri fileUri) {
        Intent intent = new Intent(Intent.ACTION_VIEW);
        intent.setClassName("org.ppsspp.ppsspp", "org.ppsspp.ppsspp.PpssppActivity");
        intent.addCategory(Intent.CATEGORY_DEFAULT);
        intent.setDataAndType(fileUri, "application/octet-stream");
        
        // Add the flags
        intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TASK);
        intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
        intent.addFlags(Intent.FLAG_ACTIVITY_NO_HISTORY);

        startActivity(intent);
    }
}
```

So maybe something like that?

**Comment by topanrizkyr** [comment]
> @topanrizkyr Actually I don't think it's that difficult. Follow the example in the last post in #17416 , you'll just have to figure out how those command line parameters translate to an intent.
> 
> I asked ChatGPT how to do it, see here: https://chat.openai.com/share/2b64ea9d-9a42-4415-bee5-253f848b96ae
> 
> Its output:
> 
> ```java
> import android.content.Intent;
> import android.net.Uri;
> 
> public class MyActivity extends Activity {
>     @Override
>     protected void onCreate(Bundle savedInstanceState) {
>         super.onCreate(savedInstanceState);
>         // ...
>         openPpssppActivityWithFileUri(fileUri);
>     }
> 
>     private void openPpssppActivityWithFileUri(Uri fileUri) {
>         Intent intent = new Intent(Intent.ACTION_VIEW);
>         intent.setClassName("org.ppsspp.ppsspp", "org.ppsspp.ppsspp.PpssppActivity");
>         intent.addCategory(Intent.CATEGORY_DEFAULT);
>         intent.setDataAndType(fileUri, "application/octet-stream");
>         
>         // Add the flags
>         intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TASK);
>         intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
>         intent.addFlags(Intent.FLAG_ACTIVITY_NO_HISTORY);
> 
>         startActivity(intent);
>     }
> }
> ```
> 
> So maybe something like that?

Thanks you so much , my bad I just figured it out i will try that

**Comment by hrydgard** [comment]
Of course, ChatGPT is very likely wrong in some details, but who knows :)
