### ISSUE TITLE
Naruto: Ultimate Ninja Heroes 2: Flicker on story mode videos 

### ISSUE THREAD

**Issue by angeluskun** [hrydgard/ppsspp#17740]
### Game or games this happens in

Naruto: Ultimate Ninja Heroes 2: The Phantom Fortress

ULES-01088 V1.0

### What area of the game

Story mode or any área that plays a video like naruto's house for example

### What happens

When i start story mode or a video of naruto's house it starts to flickering a Lot, anyways you can fix (kinda) if you change backend from vulkan to OpenGL but as soon as another video scene starts flickering occours again and you need to change backend again too in general you can see every scene with this method and complete the game but it's a Little tedious

### What should happen

Tested on latest pstore gold version and latest dev versión too
![Screenshot_2023-07-19-02-08-19-148_com miui securitycenter](https://github.com/hrydgard/ppsspp/assets/23154910/c09472ac-a3d1-4ebc-b813-f6f86a199603)
And a video with problem too
Gold playstore versión: 
https://cdn.discordapp.com/attachments/480103153803460614/1131128022351745066/Screenrecorder-2023-07-19-01-36-07-80.mp4

Dev versión v1.15.4-571-g16ee5a50c: https://cdn.discordapp.com/attachments/480103153803460614/1131132296762761356/Screenrecorder-2023-07-19-01-53-08-979.mp4

### Platform

Android

### Mobile phone model or graphics card

Poco F4 5g Android 13 miui 14.0.7

### PPSSPP version affected

1.15.4 gold playstore versión and  dev build v1.15.4-571-g16ee5a50c

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Maybe you can tell us which game this is about?

**Comment by hrydgard** [comment]
Re-opening due to revert. Will redo #18008, and test it better.
