### ISSUE TITLE
Linux build log spam (_BSD_SOURCE)

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#17746]
Our Linux build logs are spammed with:

```
In file included from /home/runner/work/ppsspp/ppsspp/ext/cpu_features/src/stack_line_reader.c:15:
In file included from /home/runner/work/ppsspp/ppsspp/ext/cmake/cpu_features/../../cpu_features/include/internal/stack_line_reader.h:23:
In file included from /home/runner/work/ppsspp/ppsspp/ext/cmake/cpu_features/../../cpu_features/include/internal/string_view.h:21:
In file included from /usr/include/string.h:26:
In file included from /usr/include/x86_64-linux-gnu/bits/libc-header-start.h:33:
/usr/include/features.h:194:3: warning: "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-W#warnings]
# warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
```

We do define -D_BSD_SOURCE in a couple of places - probably shouldn't then? I don't really know what this does.

**Comment by ANR2ME** [comment]
At mozilla, they use _DEFAULT_SOURCE on top of _BSD_SOURCE https://bugzilla.mozilla.org/show_bug.cgi?id=1461614
```c++
#ifdef LINUX
 #define _BSD_SOURCE
+#define _DEFAULT_SOURCE
 #endif
```

**Comment by fp64** [comment]
I'll point out that `_BSD_SOURCE` is used in 2 places in `CMakeLists.txt`, and in one it is already accompanied by `_DEFAULT_SOURCE`:
https://github.com/hrydgard/ppsspp/blob/master/CMakeLists.txt#L2267-L2267
but not the other:
https://github.com/hrydgard/ppsspp/blob/master/CMakeLists.txt#L409-L409

Also seen https://stackoverflow.com/questions/29201515/what-does-d-default-source-do which recommends `_DEFAULT_SOURCE` plus `_BSD_SOURCE` as well (haven't looked at it closely).

**Comment by hrydgard** [comment]
It seems likely to me that we should be able to get away with just _DEFAULT_SOURCE for these now... Maybe there's some weird platform that needs _BSD_SOURCE as well.
