### ISSUE TITLE
All the 3D game graphics are completely broken on Intel Iris Xe Graphics, with Vulkan, Skip buffer effects and No buffer

### ISSUE THREAD

**Issue by djlain** [hrydgard/ppsspp#17741]
### Game or games this happens in

All the 3D games, like UCES-00001 - WipEout Pure & NPJH-50475 - Hatsune Miku: Project Diva 2nd

### What area of the game / PPSSPP

All the 3D game graphics are completely broken with Vulkan / Skip buffer effects [on] / Buffer graphics commands [No buffer] / all other settings keep the default, on any Intel Iris Xe Graphics devices. There're some samples:

![UCES00001_00000](https://github.com/hrydgard/ppsspp/assets/98971315/81e9af10-d964-4d4a-bbd1-2c4424c34e53)
UCES-00001 - WipEout Pure

![NPJH50475_00000](https://github.com/hrydgard/ppsspp/assets/98971315/8b1cbd78-ae60-493c-9f32-58fcd022239d)
NPJH-50475 - Hatsune Miku: Project Diva 2nd

I tried on a Core i5-1135G7 and a Core i7-1165G7 device, also latest driver (101.4502) and an older driver (101.1191), still got the same result. All the build after 1.14 stable (including the latest nightly build) will have the issue. Also, if you take a snapshot during the broken graphics, the PPSSPP will crash. 

I use the settings for better input lag and vulkan works better on Intel Iris Xe Graphics, so it would be nice if this can be fixed.

### What should happen

On 1.13.2 stable and older, it's totally no problem with same settings:

![UCES00001_00000](https://github.com/hrydgard/ppsspp/assets/98971315/53f3c304-6488-4a3b-adf2-840c2d1e2a69)
UCES-00001 - WipEout Pure

![NPJH50475_00000](https://github.com/hrydgard/ppsspp/assets/98971315/d063e7ea-a2ff-49b4-ba21-4adb830a849a)
NPJH-50475 - Hatsune Miku: Project Diva 2nd

### Platform

Windows

### Mobile phone model or graphics card

Core i7-1165G7 with Intel Iris Xe Graphics

### PPSSPP version affected

from 1.14 stable to v1.15.4-571-g16ee5a50c

### Last working version

1.13.2 stable

### Graphics backend (3D API)

Vulkan

### Checklist

- [x] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Curious, haven't seen this on my Xe laptop. Will check again soon, and check my driver version.

**Comment by hrydgard** [comment]
Is this a discrete Xe card? 

Here's what see in Settings/Tools/System Information:

![image](https://github.com/hrydgard/ppsspp/assets/130929/f92effdd-a214-4f02-8459-970454fb1cb4)

So driver is 0.404.2079, which doesn't look anything like your driver versions...

Does enabling/disabling the MSAA setting change anything? Works, or changes the nature of the glitches?

On my laptop, I don't see this issue at all.

**Comment by djlain** [comment]
It's not a discrete card, it's integrated Iris Xe graphics of Core i5-1135G7 / Core i7-1165G7

This is my syetem info:
![0721184658](https://github.com/hrydgard/ppsspp/assets/98971315/f32832da-b79c-473e-896a-65e2e1164938)

And my driver is from intel official page, which the version is like 31.0.101.xxxx (already tried the latest one, but still no fix and more unstable for other games, so I back to the old version)
https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html

MSAA setting did not change anything. My devices are all 11th Gen and on Win10 so I'm not sure if it matters. For testing, I installed a fresh ppsspp, only change backend to Vulkan / Skip buffer effects [on] / Buffer graphics commands [No buffer], and did not touch any other option, then I will get the problem.

**Comment by hrydgard** [comment]
Oh, I missed that this was with Skip buffer effects only. I would highly recommend to not use that option, basically ever. For what reason are you using it?

Still, we should of course get this fixed if we can figure it out.

I tried again with skip buffer effects on my laptop, and I did not get the glitches. Indeed MSAA doesn't do anything, because it doesn't work in skip buffer effects mode.

I'm testing on WIndows 11.

**Comment by hrydgard** [comment]
Oh! The No buffer thing is interesting. I'm gonna have to give that a try.

Theoretically skip buffer shouldn't really affect input lag, at least if the game manages its rendering the normal way.. Hm.

**Comment by hrydgard** [comment]
Indeed, when I run with no buffer, I even get a Vulkan validation error if I have that enabled. Something is wrong.

Let's see in release... 

Anyway, I'll tackle this as part of the upcoming timing rework: #17685 

I'm gonna start working in that direction once I'm done with all the RetroAchievement and related networking stuff.

**Comment by djlain** [comment]
Thanks very much for your testing, take all the time you need please!

**Comment by hrydgard** [comment]
@djlain Can you try the latest build now from https://buildbot.orphis.net/ppsspp/ ?

**Comment by djlain** [comment]
Tested many 3d games on the lastest build, it's totally fixed now! Thanks for the quick fixing!!!

**Comment by hrydgard** [comment]
Thanks for testing!
