### ISSUE TITLE
Should make the default language configurable separately from UI language

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#17762]
We'll just add a list of the standard languages and have an AUTO setting, which will be the default, preserving current behavior.

This is a common feature request that should be simple to implement.

**Comment by unknownbrackets** [comment]
Well, I thought we actually used to and you removed it in the name of removing "useless options."  I'm not really against keeping it.  I guess it'll be gone again in a few years, and then back a couple after that...

-[Unknown]

**Comment by hrydgard** [comment]
I don't think we ever had this separate?

And I've given up the fight against this kind of option. I am still on the crusade against options that can break things like some of our rendering options.
