### ISSUE TITLE
Add a feature to adjust the speed of button repeat mode in the control section. 

### ISSUE THREAD

**Issue by MajinDipu** [hrydgard/ppsspp#17761]
### What should happen

The turbo mode or repeat mode in the control section is too slow. Would be helpful if we could just adjust the speed of the interval between button repetition. 

### Who would this benefit

Me. And also many other people who wants to use the turbo button at their advantage. 

I feel like it's a feature that should have been on the emulator from a long time ago.

### Platform (if relevant)

Android

### Games this would be useful in

ULUS10544 - WWE All Stars

### Other emulators or software with a similar feature

A discontinued  MAME emulator on android. Also I think ePSXe has it.

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by MajinDipu** [comment]
Can we make the speed even faster? Currently it's not that fast at all so we can't even call it *rapid fire*

**Comment by MajinDipu** [comment]
> Can we make the speed even faster? Currently it's not that fast at all so we can't even call it _rapid fire_

Can we?

**Comment by hrydgard** [comment]
Currently its max speed turns on and off every frame. I don't know if it's possible to make it faster in a way that games will recognize.

Do you have an example of a game where it's not fast enough, but you can actually shoot faster manually?

**Comment by MajinDipu** [comment]
> Currently its max speed turns on and off every frame. I don't know if it's possible to make it faster in a way that games will recognize.
> 
> Do you have an example of a game where it's not fast enough, but you can actually shoot faster manually?

Well maybe not in the way you’re looking for but in Street Fighter Alpha 3 Max there is a built in "Rapid" mode where it toogles turbo mode inside the game and does about 60 input in one frame. Its purpose was to make 1 hit frame combos easier.

Making rapid/turbo mode even faster in PPSSPP will make doing combos in fighting games easier

**Comment by hrydgard** [comment]
Well games don't generally sample input more than once per frame (with rare exceptions). It's not possible to create a general feature that will work like that.
