### ISSUE TITLE
Toggle screenshot crash.

### ISSUE THREAD

**Issue by Saramagrean** [hrydgard/ppsspp#17781]
### Game or games this happens in

All game.

### What area of the game / PPSSPP

when use toggle screenshot.

![Screenshot_16](https://github.com/hrydgard/ppsspp/assets/26355472/43fd4f65-c503-4f1c-bb36-17e5d8b9f72e)

### What should happen

Not crash. :)

### Logs

[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/12160193/ppsspplog.zip)

### Platform

Windows

### Mobile phone model or graphics card

Intel HD Graphic 520.

### PPSSPP version affected

v1.15.4-231-g9df01a5bf

### Last working version

v1.15.4-225-gd7e4055c4	

### Graphics backend (3D API)

Other

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Yup, we're hitting an assert now:

(/Users/hrydg/ppsspp/Common/GPU/Vulkan/VulkanRenderManager.h:Draw:383): [curRenderStep_ && curRenderStep_->stepType == VKRStepType::RENDER && curStepHasViewport_ && curStepHasScissor_] (CAVE00992 Cave Story) Assert!

So there's a bug somewhere with the timing of how we take the screenshot, I guess.

**Comment by Saramagrean** [comment]
I notice crash when toggle replacement textures in some game too. (eg. SAO-IM [JP])

Step to repro.
--> enable Replace textures --> enable Save new textures --> disable Replace textures --> Crash.

Log.
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/12168816/ppsspplog.zip)

**Comment by hrydgard** [comment]
#17961 should fix the screenshot crash. That replacement crash is probably something else, I'll play around with replacements a little and see if I can repro.
