### ISSUE TITLE
Crash during startup for Win32 Debug build with OpenGL

### ISSUE THREAD

**Issue by Nemoumbra** [hrydgard/ppsspp#17787]
### Game or games this happens in

Not game-specific

### What area of the game / PPSSPP

Just starting the emulator with OpenGL causes an unhandled exception in atioglxx.dll (read access violation).
This time just skipping through the error doesn't help as it is rethrown all the time.

### What should happen

No doubt, that's not a desirable behaviorr.

### Logs

The top of the stacktrace:
```
atioglxx.dll!1207cb67()
External code
GLQueueRunner::RunInitSteps(const FastVec<GLRInitStep> & steps, bool skipGLCalls) Line 480
GLRenderManager::Run(GLRRenderThreadTask & task) Line 432
GLRenderManager::ThreadFrame() Line 160
WindowsGLContext::ThreadFrame() Line 496
MainThreadFunc() Line 293
```

VS2017 says the symbols for atioglxx.dll are not loaded so some frames may be missing or invalid.

### Platform

Windows

### Mobile phone model or graphics card

AMD Radeon(TM) Graphics

### PPSSPP version affected

Self-built version (one of the lastest)

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Indeed, this is weird:

![image](https://github.com/hrydgard/ppsspp/assets/130929/2d738287-c945-4704-8578-b6c1828b6e6e)

I think I'll just disable debug groups in this configuration.

**Comment by hrydgard** [comment]
That takes care of this.
