### ISSUE TITLE
Feature Request: Right Stick Bindings (Toggleable, set as face buttons with adjustable overlap)

### ISSUE THREAD

**Issue by Semaze** [hrydgard/ppsspp#17792]
### What should happen

So this is a suggestion for a feature. 
I'll use Ghostbusters for my explanation, however this can apply to other games with different camera controls.

So Ghostbusters uses the action buttons for camera control/aiming your proton pack. You can pretty easily set up the right analogue stick to input the face buttons. However, I find this feels very rigid as you cannot easily input diagonals, without perfectly having the analogue stick in the corner. 

My suggestion is to have a way to map the right stick of a controller to either the Action Buttons or D-Pad, but most importantly having an adjustable "overlap", so you can increase (or decrease) the space in which diagonal inputs are pressed. 

Whilst right stick mods cheats, if certain games don't have right stick cheats, this can act in it's stead.

### Who would this benefit

Anyone playing a game with strange camera controls, and need more dynamic input that is unable to use a right stick cheat.

### Platform (if relevant)

Windows

### Games this would be useful in

Ghostbusters, Me & My Katamari

### Checklist

- [ ] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [ ] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
We translate each stick direction directly to buttons in this case, which is convenient, but does have the issue with the diagonals. We should probably special case the handling to be easier on the corners when two directions from the same joystick are mapped to adjacent buttons, to fix this...

**Comment by iota97** [comment]
I wonder if checking "Circular stick input" in "Calibrate analog stick" helps with this.

**Comment by HFPasfho** [comment]
> I wonder if checking "Circular stick input" in "Calibrate analog stick" helps with this.

It does not

**Comment by hrydgard** [comment]
Right, it doesn't. This will need some special casing.

**Comment by hrydgard** [comment]
I'm going for a simple solution, where we gradually decrease the threshold on the joystick y-axis if the x-axis is being used, and vice versa. This seems to work really well, and should solve this with no additional configuration needed.

**Comment by HFPasfho** [comment]
@hrydgard When can we expect the new version to be released? I'm really looking forward to this feature. This and the support for CHD format.

**Comment by hrydgard** [comment]
Late january.

**Comment by HFPasfho** [comment]
@hrydgard Unfortunately I can't. I just get a package installer error message "the application has not been installed" with no details.

**Comment by HFPasfho** [comment]
@hrydgard Judging by milestone this feature should be implemented in version 1.17 but I don't see any difference compared to 1.16.6. Producing diagonal input on analog stick mapped to face buttons (circle, cross etc.) is still almost impossible. You have to make a very precise input for emulator to register it as two face buttons pressed simultaneously. On the other hand if you add custom right analog stick in touch control layout and bind it to face buttons, diagonal inputs are very easy to make. It would be great if gamepad analog stick could work like this additional touchscreen analog.

I even tried to:
1. Add right analog stick to touch control layout
2. Check "custom" option and bind it to face buttons
3. Map gamepad right analog stick to PPSSPP right analog in Controls > Control mapping
but such two-layer mapping doesn't work.

**Comment by hrydgard** [comment]
I was a bit too cautious maybe with how strong to make the effect. I'll strengthen it for 1.17.1.

As-is it takes it from "impossible" to "can do it but need to aim carefully" for me - which I would agree isn't quite ideal.

**Comment by HFPasfho** [comment]
Maybe add option to customize "overlap" size?

PS. Selecting circular stick input doesn't seem to help. Does it even work for right stick?
