### ISSUE TITLE
Zettai Zetsumei Toshi 3: Major slowdown reported since 1.15.4

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#17797]
Reported through e-mail.

Samsung M20  (Mali-G71 MP2, Exynos 7904)
OpenGL

1.15.4:

https://drive.google.com/file/d/1LsRo3PtpbE9kRbwUXbWOiIsQjCx2IRhD/view?usp=drivesdk

Latest:

https://drive.google.com/file/d/1LmQ2Jrpr6IFnO6Nw7KjVYpAqtDdjUNez/view?usp=drivesdk

Asked the reporter to try some builds in between, let's see.

**Comment by IrfanH495** [comment]
issues start at v1.15.4-175- OpenGL
For vulkan I don't know, on ppsspp v1.15.4 already feels heavy
Save Data
https://drive.google.com/file/d/1L6G5FCsFR--e7ISifJU-Ntyv0lqoWnBY/view?usp=drivesdk

**Comment by unknownbrackets** [comment]
Was https://github.com/notifications the one before that which was fast?  Or v1.15.4-174-g8eb55a6fd?

If the former, I guess it points to #17573.  If the latter... well, not sure.  Very strange.

-[Unknown]

**Comment by hrydgard** [comment]
The only other suspect looks like #17575 but that's just removing unused code... or should be.

**Comment by hrydgard** [comment]
@IrfanH495 could you get a frame dump on some slow area?

**Comment by IrfanH495** [comment]
@hrydgard this is taken from the last build of android
[ULJS00191 frame dump.zip](https://github.com/hrydgard/ppsspp/files/12208724/ULJS00191.frame.dump.zip)

**Comment by IrfanH495** [comment]
@unknownbrackets in version ppsspp-v1.15.4-166-g22632b82b-android the speed is still normal
![Screenshot_20230730-150850_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/95da1f98-3f8c-4252-926e-9efe1e93a62a)
![Screenshot_20230730-152731_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/d65bbe2f-6edb-4e72-a425-3e476253ba4d)

**Comment by hrydgard** [comment]
@IrfanH495 what phone are you testing on? Or are you the original reporter?

**Comment by IrfanH495** [comment]
I reported it via email, I think it's not an issue if I report it directly here.  and I've created a lot of issues.

**Comment by hrydgard** [comment]
It's fine to create a lot of issues :)

**Comment by hrydgard** [comment]
Here's the most suspicious thing I'm finding, looking at the frame debug stats:

![image](https://github.com/hrydgard/ppsspp/assets/130929/ff64510e-5a2d-40d2-9433-bb45a2859f0a)

It seems to be drawing a sprite off-screen, each time causing a copy of the background. In RenderDoc, for some reason, it shows that there's no vertex shader? Can't be right.

Not sure why the way any of that works would have changed in the suspected PRs though..

Will dig more.

**Comment by hrydgard** [comment]
Yeah, here's the problem:

https://github.com/hrydgard/ppsspp/pull/17575/files#diff-0c18165f9b1eb610c2107a72e22e9dec1871a3e73f03d073a684c34115d470feL610

Accidentally disabled framebuffer fetch in all backends. Will fix.

Still, this is a very problematic scene when we can't use that.

**Comment by hrydgard** [comment]
This should be back to the old behavior in -756, although I have an experimental change that'll greatly improve performance here in Vulkan in the future (though maybe not if the view changes to actually look at those off-screen fire sprites, if that's possible...)

**Comment by IrfanH495** [comment]
sorry for the slow response.
i tried in v1.15.4-758-g36951a0b9 it runs smoothly openGL
![Screenshot_20230730-203313_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/8fc777e6-0890-4305-bda2-29a890146762)
![Screenshot_20230730-203332_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/0cbc7920-0eab-44ff-ab9f-d52010412fdc)
Thank you very much.

**Comment by IrfanH495** [comment]
@hrydgard sorry I'm embarrassed if I make issues in the same game again
This actually happened a long time ago I didn't report it, but the target of this version is performance, so i report it.
Zettai Zetsumei Toshi 3 when the character is on fire, the fps will drop.
i don't know about performance but can be solved using IntraVRAMBlockTransferAllowCreateFB

Without IntraVRAMBlockTransferAllowCreateFB
https://youtu.be/MOpYS7d-AMs
Use IntraVRAMBlockTransferAllowCreateFB
https://youtu.be/q_0xHeupAuc

**Comment by hrydgard** [comment]
That sounds like an unrelated issue to the other one, which benefits from culling. 

That flag can potentially cause other problems though, such as missing images on save icons and stuff in some games.

If the game seems completely normal throughout with the flag enabled, I'm happy to enable it by default. Let me know.

**Comment by IrfanH495** [comment]
I don't really understand, this is a save state if needed.
[Zettai zetsumei Toshi save state.zip](https://github.com/hrydgard/ppsspp/files/12364168/Zettai.zetsumei.Toshi.save.state.zip)

**Comment by hrydgard** [comment]
No i mean that while the flag fixes the performance issue, there is a possibility (although small) that other things elsewhere in the game will break from having the flag enabled. If you enable it yourself, and play for a bit and everything seems normal, I'll just enable it for everyone in this game.

**Comment by IrfanH495** [comment]
ahh, I myself have never played normally, always use the cpu clock to lock the fps30/30, my device is not very strong.
I think it's just, BlockTransferAllowCreateFB could damage the image but that's not all.

**Comment by IrfanH495** [comment]
sorry, just ignore this.
these are all default settings.
fps also drops if the player's health is low.

https://github.com/hrydgard/ppsspp/assets/78854859/4f4c6866-9145-46b0-a641-fbe585ca2787


if this has been around for a long time, don't know when.

https://github.com/hrydgard/ppsspp/assets/78854859/98e4b297-3f12-47b9-8e50-6f2252413791


i checked all compasses out of 126 only 1 had this, if the player's health is low.
![Screenshot_20230826-032843_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/67e629ef-cec8-4c97-afcb-6a3a548ce3d6)
![Screenshot_20230826-032906_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/2c016831-1c62-42f7-bc5c-3553e84e2571)

**Comment by hrydgard** [comment]
Hm, that's quite an unexpected amount of slowdown for such a small-looking effect. Can you enable debug log in the last case too?

**Comment by IrfanH495** [comment]
ppsspp-v1.15.4-1217-g564c4b38b-
OpenGL
![Screenshot_20230826-034556_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/759f7cac-fff4-4e2a-955e-56615057b1dc)
[ULJS00191_0001.zip](https://github.com/hrydgard/ppsspp/files/12443440/ULJS00191_0001.zip)

**Comment by hrydgard** [comment]
Yeah, there's a readback slowing it down. Can this one also be solved with IntraVRAMBlockTransferAllowCreateFB or the other similar one?

**Comment by IrfanH495** [comment]
can be solved with IntraVRAMBlockTransferAllowCreateFB

https://github.com/hrydgard/ppsspp/assets/78854859/8792cdc9-2b3b-4215-869a-35bc7096fe99

**Comment by IrfanH495** [comment]
Sorry, don't add to IntraVRAMBlockTransferAllowCreateFB or BlockTransferAllowCreateFB.

i played from the beginning without save data found this if added to IntraVRAMBlockTransferAllowCreateFB or BlockTransferAllowCreateFB
only when the player takes the costume, I didn't notice, in my save data all the costumes have been obtained.

IntraVRAMBlockTransferAllowCreateFB OFF
![Screenshot_20230827-015116_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/6e909565-1aca-4666-a784-233f6545036b)
IntraVRAMBlockTransferAllowCreateFB ON
![Screenshot_20230827-015144_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/5bdeec52-0e76-4e74-a421-35d01a4a3d89)

**Comment by hrydgard** [comment]
OK, looks like it's not safe enough to enable then unfortunately..

**Comment by IrfanH495** [comment]
Just close this issue, this is already a different issue.
sorry to mess up your plans, I'll look where the issue started.
this happened a long time ago, i wish i remembered it.

**Comment by hrydgard** [comment]
I don't think that readback is caused by some newer change, and if so it's a fix, because it seems it's needed for correct emulation..

**Comment by IrfanH495** [comment]
yes, i didn't find it, after i remember i always use unlimited health cheat, to avoid lag 😄😄😅

**Comment by hrydgard** [comment]
This should now run with good performance in Vulkan as well, hopefully.

**Comment by IrfanH495** [comment]
ppsspp-v1.16.6-469-g27e47d989-android
Yes, it's fast, but where are the cars here?

https://github.com/hrydgard/ppsspp/assets/78854859/4d51f547-59e5-4378-b79f-563e9138e0d0


I'll find out in which version the car is missing.
In an instant the car was gone

**Comment by hrydgard** [comment]
Huh what, same in OpenGL?

Also might want to try the very latest build -473 or later.

**Comment by IrfanH495** [comment]
it looks like both, I forget
ppsspp-v1.16.6-456-g3e20fab38-android
the car is still there
![Screenshot_20231210-005400_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/1f401884-029d-461f-8d1c-bdeaf191fcf2)

**Comment by IrfanH495** [comment]
yes, openGl too
![Screenshot_20231210-010307_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/d7498e4f-e3a0-4504-b6ae-534693162268)
I can fly
![Screenshot_20231210-010406_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/039397e6-7302-4af7-8c14-14c4f819f9b3)

Luckily, just experiment

**Comment by hrydgard** [comment]
ok, well, likely it will be fixed in 473, but we'll see..

**Comment by IrfanH495** [comment]
Yes, it's been fixed in the version 
ppsspp-v1.16.6-473-g904ce4f7e-android
Vulkan and openGl
![Screenshot_20231210-012909_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/69758285-9465-49ca-a5af-fa663d30f03c)
thanks, This is smoother on Vulkan I think, getting around 40/50 fps on my weak device.

near the fire it feels a bit heavy, Even so, I am very grateful to have been able to play it.
https://github.com/hrydgard/ppsspp/assets/78854859/5cf08ca7-8d78-4add-80a4-9cdea88d7944


the rest I just set the CPU clock to make the game run smoother

**Comment by hrydgard** [comment]
Alright, well at least it's playable. Unfortunately the fire is using a wacky blend mode that we need to emulate in a shader in an expensive way in Vulkan, while there's the possibility to directly readback from the framebuffer in OpenGL.

Here's the display of the expensive things:

![image](https://github.com/hrydgard/ppsspp/assets/130929/2c74e16a-0d47-40f2-a408-fa545aa2a0f8)

There should at least be less of them now than before, but not when looking directly at the fire I suppose.

**Comment by hrydgard** [comment]
Can I trouble you once more, by asking for a GE framedump right at that slow moment with the fire?

Maybe there are more optimizations we can do somehow.

**Comment by IrfanH495** [comment]
ok
[ULJS00191_0001.zip](https://github.com/hrydgard/ppsspp/files/13625493/ULJS00191_0001.zip)

**Comment by hrydgard** [comment]
Thanks! It'll be very useful next time I look at this.
