### ISSUE TITLE
Bleach: Soul Carnival [freezing]

### ISSUE THREAD

**Issue by brujo5** [hrydgard/ppsspp#1782]
all graphics are fixed but again it's 'freezing' at this point(music keep playing) 

console image

http://forums.ppsspp.org/attachment.php?aid=4611

http://forums.ppsspp.org/attachment.php?aid=4610

thx.

**Comment by sum2012** [comment]
Update debug log to v0.9.9.1-1574-gfeeb3c9
https://drive.google.com/file/d/0B3OaSdeV0L8kUWE0azRFS3c3REU/view?usp=sharing

**Comment by unknownbrackets** [comment]
What if you apply this ugly hack in Core/HLE/sceSas.cpp?

```c++
#include <Windows.h>

static u32 sceSasGetAllEnvelopeHeights(u32 core, u32 heightsAddr) {
	DEBUG_LOG(SCESAS, "sceSasGetAllEnvelopeHeights(%08x, %i)", core, heightsAddr);

	if (!Memory::IsValidAddress(heightsAddr)) {
		return ERROR_SAS_INVALID_PARAMETER;
	}

	for (int i = 0; i < PSP_SAS_VOICES_MAX; i++) {
		int voiceHeight = sas->voices[i].envelope.GetHeight();
		Memory::Write_U32(voiceHeight, heightsAddr + i * 4);
	}

	if (GetAsyncKeyState(VK_DECIMAL)) {
		for (int i = 0; i < PSP_SAS_VOICES_MAX; i++) {
			int voiceHeight = sas->voices[i].envelope.GetHeight();
			NOTICE_LOG(HLE, "Replacing voice height %d of %d with 0", i, voiceHeight);
			Memory::Write_U32(0, heightsAddr + i * 4);
		}
	}

	return 0;
}
```

When the freeze happens, try pressing the "." key (on the numpad I think.)  You can replace with another key if you like, but I'm wondering both: what it logs (what are the heights), and whether forcing it to zero helps.

That should at least answer if it's waiting for a height.  You can also try forcing the value to 0x40000000 instead of 0.  If neither works then probably it's not waiting on heights.

-[Unknown]

**Comment by daniel229** [comment]
log of Bleach: Soul Carnival 2, 0 or 0x40000000 did not help.
https://gist.github.com/daniel229/9202a11960d14a69bc0d

**Comment by daniel229** [comment]
Revert back these 2 lines https://github.com/hrydgard/ppsspp/commit/4561440df795e80dcd217d5b72c0fe183cd8f234#commitcomment-6889647 fixes this issue and the Armored Core series

**Comment by sum2012** [comment]
Update debug log to v1.0.1-799-gb5f7d93
https://drive.google.com/file/d/0B3OaSdeV0L8kcF9EZ3pNdG9uNmc/view?usp=sharing
The GPU sign handling is still wrong

**Comment by sum2012** [comment]
The GPU sign handling in JPCSP 's code is in
https://github.com/jpcsp/jpcsp/blob/master/src/jpcsp/graphics/VideoEngine.java#L3644

**Comment by heireaper** [comment]
Any way to fix this issue on iOS? Bleach soul carnival still freezes when I talk to rukia. As for bleach soul carnival 2, the game will load but, when I get to rukia it freezes again... Any solution for iOS?

**Comment by sum2012** [comment]
@heireaper The easy method compile with this change (hack) https://github.com/sum2012/ppsspp/commit/07b5c98ec9dae11dca356d5bf72be812b14c5bb4

The hard (best) method translate jpcsp 's code to ppsspp
https://github.com/jpcsp/jpcsp/blob/master/src/jpcsp/graphics/VideoEngine.java#L3644
and
https://github.com/jpcsp/jpcsp/blob/master/src/jpcsp/HLE/modules150/sceGe_user.java#L177

**Comment by brujo5** [comment]
@sum2012 

do you have an save state after the hang problem (working)?

**Comment by sum2012** [comment]
@brujo5 
Bleach Soul Carnival 1 's  save state 
https://drive.google.com/file/d/0B3OaSdeV0L8kejE3Z0pyUVUwRG8/view?usp=sharing
![1](https://cloud.githubusercontent.com/assets/2177532/9262544/354fa2c6-4248-11e5-91bb-75de7a78270b.jpg)

**Comment by brujo5** [comment]
@sum2012

Thank alot!!

There is a chance that hang again later or only happens at the beginning?

**Comment by sum2012** [comment]
@brujo5 it will hang again when you return to map,then go to menu.
The only solution is compiler ppsspp with the hack change https://github.com/sum2012/ppsspp/commit/07b5c98ec9dae11dca356d5bf72be812b14c5bb4

(If you compile ok,can you share with me with your ios port of this hack ? Thanks)

**Comment by brujo5** [comment]
ok,thanks:)

**Comment by sum2012** [comment]
v1.2.2-176-gb0329e8
GPU sign handling is still wrong
https://drive.google.com/file/d/0B3OaSdeV0L8kX0lLcVZKZDJod2c/view?usp=sharing

**Comment by brujo5** [comment]
@sum2012 

Do you have an apk with the hack change? Thx

**Comment by sum2012** [comment]
@brujo5 a bit old
http://pan.baidu.com/s/1bs2mEM

**Comment by LunaMoo** [comment]
@brujo5 in case you just want to play and missed it - a while ago I made cwcheat version of that hack. It's posted in each of those game's thread ~ [here](http://forums.ppsspp.org/showthread.php?tid=1492&pid=110655#pid110655) and [here](http://forums.ppsspp.org/showthread.php?tid=2965&pid=111349#pid111349) - can be used in any ppsspp version on any platform(assuming cwcheats work everywhere).
 Note that as long as [Disable] cheat is not used or emulation is restarted, the hack will continue to work even if you completely turn off cheats.

**Comment by brujo5** [comment]
@sum2012 
@LunaMoo 

Sorry for delay thank you.

**Comment by M3gaGamer** [comment]
@Sum2012 Can you upload a Ppsspp that has the bleach soul carnival menu fix compiled in it?
Tnx

**Comment by sum2012** [comment]
@m3gaGamer windows 32 bit or windows 64 bit?

**Comment by M3gaGamer** [comment]
64Bit

**Comment by M3gaGamer** [comment]
Oh nvm i figured a way to get pass it using cheats
Thanks for helping anyways

**Comment by Darkjuda** [comment]
I'd like to comfirm that the issue is still happening in the latest build (1.2.2-948-g79f1b19), nonetheless the cheats provided by LunaMoo seem to work. They could be added automaticaly to the code as an hack in the options, or, in a more easy way, as regular cheat file that downloads directly with the builds.
The only issue with this is if the players uses cheats for these two games, he will have to re-write them each time he makes ppsspp updates.

**Comment by sum2012** [comment]
@unknownbrackets will test new signal handle in
https://github.com/hrydgard/ppsspp/issues/5999#issuecomment-504849191
Maybe affect this game too

**Comment by unknownbrackets** [comment]
With #12160, I'm able to complete the SC 2 demo, so I'm hopeful this is fixed.

-[Unknown]

**Comment by sum2012** [comment]
Well done @unknownbrackets 
Tested SC1 and SC2 are fixed
