### ISSUE TITLE
Spiderman3

### ISSUE THREAD

**Issue by Gelo021** [hrydgard/ppsspp#17829]
Hi again @hrydgard 
![Screenshot_2023-08-01-23-35-26-71_2f85358b2198d26f8aca533d68bee793](https://github.com/hrydgard/ppsspp/assets/67460268/5fa18308-bb9c-4e5a-99ee-690c5e655ed1)

**Comment by Gelo021** [comment]
I've tried twice to confirm, same scene at the tutorial when square, square, triangle pops up this happens

**Comment by hrydgard** [comment]
This is a duplicate of #10196 , an old mystery we haven't solved :(
