### ISSUE TITLE
automaticly launch game when launching PPSSPP.

### ISSUE THREAD

**Issue by Hidte09** [hrydgard/ppsspp#17820]
### What should happen

I'm trying to make ppsspp apk directly using iso in asset folder
I want to automaticly launch game while launching PPSSPP and load from iso in asset folder without select it in main menu for to use in blue stack Android emulator android, just like apk with ppsppp iso directly playing,
I want to build with android studio.

### Who would this benefit

To harness true potential of pc emulation to get more fps in Android version of ppsspp in Pc Emulation

### Platform (if relevant)

Android

### Games this would be useful in

-

### Other emulators or software with a similar feature

-

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
Will not help you with this, sorry.

And it's not gonna get you any more FPS.
