### ISSUE TITLE
PPSSPPHeadless SDL2_ttf undefined reference to TextDrawerSDL

### ISSUE THREAD

**Issue by noabody** [hrydgard/ppsspp#17832]
### Platform

Linux / BSD

### Compiler and build tool versions

clang 15.0.7, cmake 3.27.0

### Operating system version

Manjaro Uranos 23.0.0

### Build commands used

```
  cmake -S ppsspp -B build-sdl \
    -Wno-dev \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_SKIP_RPATH=ON \
    -DHEADLESS=ON \
    -DOpenGL_GL_PREFERENCE=GLVND \
    -DUSE_SYSTEM_FFMPEG=OFF \
    -DUSE_SYSTEM_MINIUPNPC=OFF \
    -DUSE_SYSTEM_LIBZIP=ON \
    -DUSE_SYSTEM_SNAPPY=ON \
    -DUSE_SYSTEM_ZSTD=ON \
    -DUSING_QT_UI=OFF
  cmake --build build-sdl -j$(nproc)
```

### What happens

```
[ 96%] Building CXX object CMakeFiles/PPSSPPSDL.dir/UI/MiscScreens.cpp.o
/usr/bin/ld: lib/libCommon.a(draw_text.cpp.o): in function `TextDrawer::Create(Draw::DrawContext*)':
draw_text.cpp:(.text+0x674): undefined reference to `TextDrawerSDL::TextDrawerSDL(Draw::DrawContext*)'
1 warning generated.
[ 96%] Building CXX object CMakeFiles/PPSSPPSDL.dir/UI/PauseScreen.cpp.o
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/PPSSPPHeadless.dir/build.make:189: PPSSPPHeadless] Error 1
make[1]: *** [CMakeFiles/Makefile2:858: CMakeFiles/PPSSPPHeadless.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```
PPSSPPHeadless build will fail to link if SDL2_ttf is found - which requires files `Common/Render/Text/draw_text_sdl.cpp Common/Render/Text/draw_text_sdl.h` to be part of libCommon.a.  Due to PR #17824, which changed `find_package(SDL2_ttf)`, SDL2_ttf can never be found (would need to be `SDL2_ttf_FOUND` instead of `SDL2_TTF_FOUND`) and avoids the issue entirely.

In order to reproduce the failure, `USE_SDL2_TTF` must be true which triggers this in draw_text.cpp:
```
#elif USE_SDL2_TTF
	drawer = new TextDrawerSDL(draw);
```
This is our point of failure as our reference is defined in draw_text_sdl.h (which is never actually built into libCommon.a as evidenced by `CMakeFiles/Common.dir/build.make` which does not contain `draw_text_sdl.h`):

### PPSSPP version affected

v1.15.4-813-g7538807ee7

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] Make sure to run `git submodule update --init --recursive` before building.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try deleting the build directory and running the build again.
- [X] Check GitHub Actions, which builds every merge and PR.
- [ ] Include logs and help us reproduce.

**Comment by noabody** [comment]
A diff like this 'sort of' resolves the issue but not really:
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 5588287f1c..1d9f9a271d 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -754,6 +754,8 @@ add_library(Common STATIC
 	Common/Render/Text/draw_text_win.h
 	Common/Render/Text/draw_text_uwp.cpp
 	Common/Render/Text/draw_text_uwp.h
+	Common/Render/Text/draw_text_sdl.cpp
+	Common/Render/Text/draw_text_sdl.h
 	Common/System/Display.cpp
 	Common/System/Display.h
 	Common/System/System.h
@@ -1319,7 +1321,7 @@ else()
 			SDL/SDLVulkanGraphicsContext.cpp
 		)
 	endif()
-	if(SDL2_TTF_FOUND)
+	if(SDL2_ttf_FOUND)
 		add_definitions(-DUSE_SDL2_TTF)
 		set(nativeExtraLibs ${nativeExtraLibs} SDL2_ttf::SDL2_ttf)
 ```
CMakeLists.txt already has an entry for the missing files:
```
add_library(native STATIC
	${nativeExtra}
	Common/Render/Text/draw_text_qt.cpp
	Common/Render/Text/draw_text_qt.h
	Common/Render/Text/draw_text_sdl.cpp
	Common/Render/Text/draw_text_sdl.h
	ext/jpge/jpgd.cpp
	ext/jpge/jpgd.h
	ext/jpge/jpge.cpp
	ext/jpge/jpge.h
)
```
The actual command to build PPSSPPHeadless is also there:
```
target_link_libraries(PPSSPPHeadless ${COCOA_LIBRARY} ${QUARTZ_CORE_LIBRARY} ${IOKIT_LIBRARY} ${LinkCommon})
```
Maybe the command needs to look like this?
```
target_link_libraries(PPSSPPHeadless ${COCOA_LIBRARY} ${QUARTZ_CORE_LIBRARY} ${IOKIT_LIBRARY} ${LinkCommon} ${nativeExtraLibs})
```

**Comment by noabody** [comment]
This diff might be better:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 5588287f1c..ff17119473 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -1319,7 +1319,7 @@ else()
 			SDL/SDLVulkanGraphicsContext.cpp
 		)
 	endif()
-	if(SDL2_TTF_FOUND)
+	if(SDL2_ttf_FOUND)
 		add_definitions(-DUSE_SDL2_TTF)
 		set(nativeExtraLibs ${nativeExtraLibs} SDL2_ttf::SDL2_ttf)
 
@@ -2561,6 +2561,12 @@ if(HEADLESS)
 			Windows/W32Util/Misc.cpp
 			Windows/W32Util/Misc.h
 		)
+	if(USE_SDL2_TTF)
+		list(APPEND HeadlessSource
+			Common/Render/Text/draw_text_sdl.h
+			Common/Render/Text/draw_text_sdl.cpp
+		)
+
 	endif()
 	add_executable(PPSSPPHeadless ${HeadlessSource})
 	target_link_libraries(PPSSPPHeadless ${COCOA_LIBRARY} ${QUARTZ_CORE_LIBRARY} ${IOKIT_LIBRARY} ${LinkCommon})
```

**Comment by unknownbrackets** [comment]
Hm, I'm okay with that, but I suppose draw_text_sdl.* really belong in Common along with draw_text_android.cpp, draw_text_win.cpp, etc.  Instead of `set(nativeExtraLibs ${nativeExtraLibs} SDL2_ttf::SDL2_ttf)`, does `target_link_libraries(Common SDL2_ttf::SDL2_ttf)` work?  And same for Fontconfig?

-[Unknown]

**Comment by noabody** [comment]
I don't entirely understand but my testing suggests I shouldn't mess with the `target_link_libraries` command at all.  The most elegant solution, that deals just with the missing files for PPSSPPHeadless, is the second diff and that works.

I agree that we should move the missing files out of nativeExtra and into Common.  Will test.

**Comment by noabody** [comment]
This diff is the simplest one that works:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 5588287f1c..fea39ff50e 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -1319,7 +1319,7 @@ else()
 			SDL/SDLVulkanGraphicsContext.cpp
 		)
 	endif()
-	if(SDL2_TTF_FOUND)
+	if(SDL2_ttf_FOUND)
 		add_definitions(-DUSE_SDL2_TTF)
 		set(nativeExtraLibs ${nativeExtraLibs} SDL2_ttf::SDL2_ttf)
 
@@ -2563,7 +2563,7 @@ if(HEADLESS)
 		)
 	endif()
 	add_executable(PPSSPPHeadless ${HeadlessSource})
-	target_link_libraries(PPSSPPHeadless ${COCOA_LIBRARY} ${QUARTZ_CORE_LIBRARY} ${IOKIT_LIBRARY} ${LinkCommon})
+	target_link_libraries(PPSSPPHeadless ${COCOA_LIBRARY} ${QUARTZ_CORE_LIBRARY} ${IOKIT_LIBRARY} ${LinkCommon} Common)
 	setup_target_project(PPSSPPHeadless headless)
 endif()
 ```
So I've offered up a few of the tests I've run that were successful and could make a PR for any of them.  Problem for me is that I don't understand what the intent was.  Why didn't we want PPSSPPHeadless to link to Common when others do.  

Hopefully someone with a better grasp of the intent can direct the appropriate solution.

**Comment by hrydgard** [comment]
I think we do always want PPSSPPHeadless to link directly to Common. I assume not doing that was some kind of old workaround? Not sure.

If you can get that to work, then this problem should go away, right? Not sure why we have this separate LinkCommon thing..

**Comment by hch12907** [comment]
@noabody I agree with the `SDL2_ttf_FOUND` fix (I just noticed it earlier when I actually ran the compiled binary - yesterday I only did a compilation smoke test). 

Why would PPSSPPHeadless link to TextDrawerSDL in the first place though? It doesn't render any text at all.

**Comment by hch12907** [comment]
The following diff builds for me:

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 5588287f1..fd59d0b8c 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -750,6 +750,8 @@ add_library(Common STATIC
        Common/Render/Text/draw_text.h
        Common/Render/Text/draw_text_android.cpp
        Common/Render/Text/draw_text_android.h
+       Common/Render/Text/draw_text_sdl.cpp
+       Common/Render/Text/draw_text_sdl.h
        Common/Render/Text/draw_text_win.cpp
        Common/Render/Text/draw_text_win.h
        Common/Render/Text/draw_text_uwp.cpp
@@ -1319,7 +1321,7 @@ else()
                        SDL/SDLVulkanGraphicsContext.cpp
                )
        endif()
-       if(SDL2_TTF_FOUND)
+       if(SDL2_ttf_FOUND)
                add_definitions(-DUSE_SDL2_TTF)
                set(nativeExtraLibs ${nativeExtraLibs} SDL2_ttf::SDL2_ttf)
 
@@ -1469,8 +1471,6 @@ add_library(native STATIC
        ${nativeExtra}
        Common/Render/Text/draw_text_qt.cpp
        Common/Render/Text/draw_text_qt.h
-       Common/Render/Text/draw_text_sdl.cpp
-       Common/Render/Text/draw_text_sdl.h
        ext/jpge/jpgd.cpp
        ext/jpge/jpgd.h
        ext/jpge/jpge.cpp
```

**Comment by hrydgard** [comment]
I'm OK with that.

**Comment by unknownbrackets** [comment]
Headless still runs PPGe, and therefore might still render text within a dialog that you could screenshot.  So it wouldn't get eliminated, I don't think.

-[Unknown]

**Comment by noabody** [comment]
FYI, it's counterintuitive but my testing suggests that:
`${LinkCommon}` evaluates to `libCommon.a`
`Common` evaluates to `libnative.a`

**Comment by hrydgard** [comment]
Yeah, might be. "native" is a remnant of a previous way of organizing things, it's been removed / merged into Common in the msvc project, but not completely in cmake.

**Comment by noabody** [comment]
Works like a treat, thanks!
