### ISSUE TITLE
PPSSPP Retroarch Graphical Glitches on 2D Game Sprites 

### ISSUE THREAD

**Issue by yudhiyou** [hrydgard/ppsspp#17848]
### Game or games this happens in

ULUS-10062 - Street Fighter Alpha 3 MAX

### What area of the game / PPSSPP

Graphical glitches on 2D sprite games like Street Fighter Alpha 3 and Guilty Gear XX Accent Core. The glitches will be happening on the char sprite randomly when playing some matches. 
On my testing this is happening on all platforms PC and Android.

This issue isn't happening on PPSSPP standalone app. It is only happening on Retroarch.

### What should happen

The glitch shouldn't be happened.

### Platform

libretro / Retroarch

### Mobile phone model or graphics card

Windows PC and Android Vivo V9

### PPSSPP version affected

ece6a50

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
These sprite-based games are not compatible with running at higher resolution.

Try changing the resolution to PSP 1x, or whatever it's called in retroarch.

**Comment by yudhiyou** [comment]
> These sprite-based games are not compatible with running at higher resolution.
> 
> Try changing the resolution to PSP 1x, or whatever it's called in retroarch.

I am already using 1x psp resolution when playing. It will be happening randomly on char sprite when playing some matchs.

**Comment by yudhiyou** [comment]
I just remember this issue wasn't happened before @warmenhoven fixed ppsspp core abysmal performance on android case. After the fix, this graphical glitches is happening.

So this is new issue.

**Comment by yudhiyou** [comment]
I hope this isn't side effects of ppsspp android performance fix. But this glitches issues is happening on all platforms.

**Comment by yudhiyou** [comment]
Is it because my pc and phone specs are too potato?

**Comment by LunaMoo** [comment]
Texture cache related settings and texture upscaling are two things which can easily cause such artifacts while in use in some tile-based 2d games.

**Comment by yudhiyou** [comment]
> Texture cache related settings and texture upscaling are two things which can easily cause such artifacts while in use in some tile-based 2d games.

I am not enabling texture upscaling at all.

**Comment by yudhiyou** [comment]
Just tried playing using gl driver on retroarch android, this 2d sprite glitches is not happening anymore. So it's confirmed this is vulkan driver issue.

**Comment by yudhiyou** [comment]
Sorry... For this case already found the cause. It is caused by vertex cache and lazy texture catching setting. So case closed.
