### ISSUE TITLE
Vulkan isn't working on Intel GPU (Windows)

### ISSUE THREAD

**Issue by Saramagrean** [hrydgard/ppsspp#17858]
### Game or games this happens in

All game.

### What area of the game / PPSSPP

Can't switching to Vulkan backend.

![Screenshot_50](https://github.com/hrydgard/ppsspp/assets/26355472/7481cb39-7763-4b96-85d6-d8767e097c9e)

### What should happen

Vulkan should work properly on latest build. (870)

![Screenshot_51](https://github.com/hrydgard/ppsspp/assets/26355472/3fe25d3f-f2a5-46c6-ab2d-f6bd87d64324)

### Platform

Windows

### Mobile phone model or graphics card

Intel HD Graphic 520.

### PPSSPP version affected

v1.15.4-838-g175def777

### Last working version

v1.15.4-836-ge15c45d9e

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment]
Yeah, it crashed too on my Intel UHD Graphoc 620 with v1.15.4-876

**Comment by qazxsw4320** [comment]
Same on my uhd graphics 600

**Comment by qazxsw4320** [comment]
Same on mine on uhd graphics 600 ever since 15.0 came out. 14.4 was the last working for me.

**Comment by hrydgard** [comment]
As for this particular problem, that means it's #17840 . I guess VK_KHR_present_wait isn't working on these, I'll disable it.

Can you check your GPU driver version @Saramagrean ? It's visible in system info (you can use the older working build to check this)

**Comment by Saramagrean** [comment]
Here, My driver version and device model.

![Screenshot_52](https://github.com/hrydgard/ppsspp/assets/26355472/0f9a6f86-304a-4dbc-a71e-b720de503a84)
![Screenshot_53](https://github.com/hrydgard/ppsspp/assets/26355472/aca6de94-4516-4e23-aa76-2ef60ec8501d)

**Comment by hrydgard** [comment]
Thank you. Turns out it reproduces even on my Xe with fresh drivers. Something is wrong with either my use of or Intels implementation of the VK_KHR_present_wait extension.

**Comment by Saramagrean** [comment]
it's working fine now, Thanks!

![Screenshot_55](https://github.com/hrydgard/ppsspp/assets/26355472/fb9a1842-c532-4634-bb57-c5f8a48b5784)

**Comment by hrydgard** [comment]
Thanks for checking!
