### ISSUE TITLE
ridge racer weird reflections on screen

### ISSUE THREAD

**Issue by ppsspp-gamer** [hrydgard/ppsspp#17869]
### Game or games this happens in

ULUS10001 ridge racer 1

### What area of the game

Any track for every car.

### What happens

reflections not only on cars but also on screen.

### What should happen

reflections should only on car.

### Platform

Windows

### Mobile phone model or graphics card

nvidia gtx 1080ti

### PPSSPP version affected

v1.15.4-895-g2990fe48c

### Last working version

v1.15.4-851-gdfabad8d2

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [ ] Include logs or screenshots of issue.

**Comment by ppsspp-gamer** [comment]
![ULUS10001_00000](https://github.com/hrydgard/ppsspp/assets/8726272/93592b5e-6ce8-4d69-b3bf-10f010e02cbf)
![ULUS10001_00001](https://github.com/hrydgard/ppsspp/assets/8726272/9ef2c0d1-6014-4188-aa4e-720441428b05)

**Comment by ppsspp-gamer** [comment]
this issue happened after this request was merged:
[[Micro-optimize SubmitPrim, remove outdated mitigation #17838](https://github.com/hrydgard/ppsspp/pull/17838)]

**Comment by hrydgard** [comment]
@unknownbrackets looks like you were right, heh. I somehow thought we had that handled.

Will revert that part.
