### ISSUE TITLE
Some Keyboard inputs causes analog-binds to gradually stop working

### ISSUE THREAD

**Issue by AFrameWorker** [hrydgard/ppsspp#17860]
### Game or games this happens in

Every game in existence

### What area of the game / PPSSPP

So I've made a keyboard and mouse configuration for PPSSPP to use for playing Liberty City Stories and Vice City Stories, although the configuration of course works globally for any game. In prior versions of PPSSPP (1.14 and below), this config would work fine. But ever since 1.15, I'm having a bizarre issue where pressing a certain key, will make analog binds stop functioning properly.

For example:
if i run forward by holding W, and press 3 (which is my "next weapon" button), my character will slow down in running speed. if i press it again, my character starts walking. if i press it again, my character stops. 

Similarly, while I'm driving and steering right (holding D), then pressing space (accelerate), the car will suddenly steer less until it stops steering entirely after a few space presses
rebinding the keys to other buttons 'fixes' the issue, but that's pain and I'd very much like to use the layout I've always used. 

### What should happen

It shouldn't.

### Platform

Windows

### Mobile phone model or graphics card

GTX 960

### PPSSPP version affected

1.15 and above

### Last working version

1.14 and below

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
That sounds extremely weird, but has to be related to some of the changes I made to control mapping to fix some different problems (where you had a keyboard and gamepad fighting each other)... You don't also have a gamepad plugged in by any chance? Either way, gotta find a better way....

**Comment by hrydgard** [comment]
OK I think I know the behavior that causes this, it's something I added to try to combat the problem where if you map both digital and analog inputs to the same thing, they clash in various interesting ways and even if you leave a small analog offset, it's supposed to return to digital behavior after you've used those controls for a while. 

However, the logic isn't very smart and needs improvement. I'll fix it up before the release.

**Comment by hrydgard** [comment]
I improved the logic in #17960, there should be new builds up for testing soon. Hopefully that will resolve this issue.
