### ISSUE TITLE
PPSSPP Retroarch jiust displays black screen but has sound

### ISSUE THREAD

**Issue by Lufims** [hrydgard/ppsspp#17864]
### Game or games this happens in

ULUS-10540 - The Legend of Heroes Trails in the Sky

### What area of the game

On the main menu, I just load the game with Retroarch and then it just displays a black screen

### What happens

I looked on the version of the core and in the game it says 1.14, but in the retroarch menu says 1.15
![ScreentRetroarch1](https://github.com/hrydgard/ppsspp/assets/73536178/2d397d28-6d5a-4aa4-8227-c4f0ccfc7a45)
![ScreenRetroarch2](https://github.com/hrydgard/ppsspp/assets/73536178/5239fd62-0a07-4a85-bcfc-93445e2d7cc8)

### What should happen

See the menu of the game

### Platform

libretro / Retroarch

### Mobile phone model or graphics card

intel g33/g31 express chipset family

### PPSSPP version affected

1.15 I think

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
We don't support the retroarch integration directly here (although will fix obvious issues and take pull requests). And especially we can't support it when it's not even clear which core version is being used...

**Comment by Lufims** [comment]
> We don't support the retroarch integration directly here (although will fix obvious issues and take pull requests). And especially we can't support it when it's not even clear which core version is being used...

I see, the core I downloaded from Libretto, and I have this issue just when I try to play in RetroArch, in the standalone version the game works fine (but I want to use RetroAchievements, that's because I'm trying to use RetroArch)

**Comment by hrydgard** [comment]
But we have RetroAchievement support in the standalone builds now, although not yet in the official release (will happen in a few weeks).

**Comment by Lufims** [comment]
> But we have RetroAchievement support in the standalone builds now, although not yet in the official release (will happen in a few weeks).

Cool, I didn't know that, I'll wait then
