### ISSUE TITLE
EMUELEC 4.6 odroid n2+ build issue Common/TimeUtil.cpp:102:9: error: '__builtin_arm_isb' was not declared in this scope; did you mean '__builtin_va_list'? 

### ISSUE THREAD

**Issue by Kelvfimer** [hrydgard/ppsspp#17877]
### Platform

Linux / BSD

### Compiler and build tool versions

CMAKE 3.24.2

### Operating system version

ubuntu 22.04 toolchain Emuelec Odroid n2+

### Build commands used

PROJECT=Amlogic-ce DEVICE=Amlogic-ng ARCH=aarch64 DISTRO=EmuELEC ./scripts/build ppsspp 
PROJECT=Amlogic-ce DEVICE=Amlogic-ng ARCH=aarch64 DISTRO=EmuELEC ./scripts/build PPSSPPSDL

### What happens

When compiling PPSSPPSDL retroarch and regular version it is failing compiling with following error starting on commit 

https://github.com/hrydgard/ppsspp/commit/096c168dd7afe82a174e4df1bf548ba495672624

on ubuntu 22.04 using toolchain for odroid n2+ for emuelec 4.6

[2/717] Building CXX object CMakeFiles/Common.dir/Common/TimeUtil.cpp.o
FAILED: CMakeFiles/Common.dir/Common/TimeUtil.cpp.o
/home/kelv/clone/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/toolchain/bin/ccache /home/kelv/clone/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/toolchain/bin/aarch64-libreelec-linux-gnu-g++ -DASSETS_DIR=\"/usr/share/ppsspp/assets/\" -DEGL_NO_X11 -DGLEW_NO_GLU -DHTTPS_NOT_AVAILABLE -DMINIUPNPC_SET_SOCKET_TIMEOUT -DMINIUPNP_STATICLIB -DPNG_ARM_NEON_OPT=0 -DSHARED_ZLIB -DSTACK_LINE_READER_BUFFER_SIZE=1024 -DUSING_EGL -DUSING_FBDEV -DUSING_GLES2 -DWITH_UPNP -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE=1 -D_POSIX_C_SOURCE=200112L -D_XOPEN_SOURCE=700 -D_XOPEN_SOURCE_EXTENDED -D__BSD_VISIBLE=1 -D__LIBRETRO__ -D__STDC_CONSTANT_MACROS -I/home/kelv/clone/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/ppsspp-2342c4522c881f405f1290d37a7c7bea2a9c1780/ext/glslang -I/home/kelv/clone/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/ppsspp-2342c4522c881f405f1290d37a7c7bea2a9c1780/ext/glew -I/home/kelv/clone/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/ppsspp-2342c4522c881f405f1290d37a7c7bea2a9c1780 -I/home/kelv/clone/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/ppsspp-2342c4522c881f405f1290d37a7c7bea2a9c1780/ext/openxr -I/home/kelv/clone/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/ppsspp-2342c4522c881f405f1290d37a7c7bea2a9c1780/Common -I/home/kelv/clone/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/ppsspp-2342c4522c881f405f1290d37a7c7bea2a9c1780/ext/libzip -I/home/kelv/clone/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/ppsspp-2342c4522c881f405f1290d37a7c7bea2a9c1780/ext/libpng17 -I/home/kelv/clone/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/ppsspp-2342c4522c881f405f1290d37a7c7bea2a9c1780/ext/zstd/lib -I/home/kelv/clone/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/ppsspp-2342c4522c881f405f1290d37a7c7bea2a9c1780/.aarch64-libreelec-linux-gnu -I/home/kelv/clone/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/ppsspp-2342c4522c881f405f1290d37a7c7bea2a9c1780/ext/snappy/. -I/home/kelv/clone/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/ppsspp-2342c4522c881f405f1290d37a7c7bea2a9c1780/ext/cmake/cpu_features/../../cpu_features/include -march=armv8-a+crc+fp+simd -mabi=lp64 -Wno-psabi -mtune=cortex-a73.cortex-a53 -mno-outline-atomics -Wall -pipe  -O2 -fomit-frame-pointer -DNDEBUG -DDUMMYOPT -Os -D_NDEBUG   -Wformat -Wno-multichar -Wno-psabi -fPIC -fPIC -fno-strict-aliasing -std=gnu++17 -MD -MT CMakeFiles/Common.dir/Common/TimeUtil.cpp.o -MF CMakeFiles/Common.dir/Common/TimeUtil.cpp.o.d -o CMakeFiles/Common.dir/Common/TimeUtil.cpp.o -c /home/kelv/clone/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/ppsspp-2342c4522c881f405f1290d37a7c7bea2a9c1780/Common/TimeUtil.cpp
/home/kelv/clone/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/ppsspp-2342c4522c881f405f1290d37a7c7bea2a9c1780/Common/TimeUtil.cpp: In function 'void yield()':
/home/kelv/clone/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/ppsspp-2342c4522c881f405f1290d37a7c7bea2a9c1780/Common/TimeUtil.cpp:102:9: error: '__builtin_arm_isb' was not declared in this scope; did you mean '__builtin_va_list'?

### PPSSPP version affected

2342c4522c881f405f1290d37a7c7bea2a9c1780

### Last working version

1f3136155b8dd455abb503246eda4ef78f634aa7

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] Make sure to run `git submodule update --init --recursive` before building.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try deleting the build directory and running the build again.
- [X] Check GitHub Actions, which builds every merge and PR.
- [X] Include logs and help us reproduce.

**Comment by hrydgard** [comment]
Hm, maybe the compiler just isn't aware of the built-in. I'll just take it out for now, we're not really using it.

**Comment by Kelvfimer** [comment]
Thx for the prompt answer and fix. it works again :)
