### ISSUE TITLE
Vulkan: Textures break sometimes when "save new textures" is enabled.

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#17881]
Reported by VeryMelon on Discord.

I guess we have some confusion about the texture format.

Expected:

![image](https://github.com/hrydgard/ppsspp/assets/130929/1041c10f-82a3-4cfc-9734-210901fba5c3)

Result:

![image](https://github.com/hrydgard/ppsspp/assets/130929/3875fa3f-5f7a-4a93-8ab9-8d726c313559)

**Comment by hrydgard** [comment]
Tried some various games but haven't been able to repro, strange. Tagging it for the next version instead.

**Comment by Saramagrean** [comment]
Intel specific?

![Screenshot_81](https://github.com/hrydgard/ppsspp/assets/26355472/e257709c-ed4c-492d-9665-9855feecf9f1)

**Comment by unknownbrackets** [comment]
Are we sure these aren't people running out of VRAM?

-[Unknown]

**Comment by hrydgard** [comment]
Could be of course, but I don't feel it's the likeliest explanation.

**Comment by hrydgard** [comment]
I cannot repro this even on intel after merging #18534. Closing, please re-open if you see this again.
