### ISSUE TITLE
Ppsspp on Retroarch Android Crash After Couple Minutes using GL Driver 

### ISSUE THREAD

**Issue by yudhiyou** [hrydgard/ppsspp#17889]
### Game or games this happens in

All Games

### What area of the game / PPSSPP

Emergency need help! After update this morning ppsspp core keep crashing after playing several minutes. I am using gl driver. 😣
Now I can't play ppsspp on my android phone at all. Using vulkan will crash. Using gl will crash after several minutes. 🥺
Yesterday before update was still great using gl driver.

### What should happen

Not crash. 

### Platform

Android

### Mobile phone model or graphics card

Vivo v9 

### PPSSPP version affected

Latest 

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
I'm reworking how display presentation works right now. Don't just update to the latest development build all the time, it won't always be fully stable.

**Comment by yudhiyou** [comment]
I see. I thought the latest build is meant the greatest version. :(

**Comment by hrydgard** [comment]
Latest build is not always greatest. It often is, but during heavy development it can break for a while. I do try to avoid it, but it's just unavoidable in software development.

That's why we have official releases from time to time, where I put in a lot of effort to make really sure things are stable.

**Comment by yudhiyou** [comment]
> Do all games end up crashing or just a certain one, and if so which one?

All games especially 3d games when entering the gameplay. So it can load the start menu but will crash when entering the gameplay.

**Comment by yudhiyou** [comment]
Ok, after couple of crash and trying today I can enter into Tekken 6 gameplay but the performance is very slow now compared with before this crash issue happened.
So this crash issue is happening on all 3d games frequently and if can enter the gameplay after couple of tries the performance is very slow compared before crash issue.
I am using gl driver on retroarch android phone vivo v9 with android 9.

**Comment by yudhiyou** [comment]
Correction... It happens on all games even 2d games also. :(
On Blazblue and Guilty Gear are crash entering start menu.
On Fate Unlimited Codes crash entering char select menu.

**Comment by hrydgard** [comment]
That's great, thanks for reporting. Still not sure what fixed it, heh.

**Comment by yudhiyou** [comment]
> That's great, thanks for reporting. Still not sure what fixed it, heh.

I see something like gl codes revert on ppsspp core git activities. Maybe that is the fix?
