### ISSUE TITLE
Textures missing detail. (Mipmap?)

### ISSUE THREAD

**Issue by Saramagrean** [hrydgard/ppsspp#17891]
### Game or games this happens in

Toukiden Kiwami.

### What area of the game

In-game. 

### What happens

Textures is missing detail with ktx2 format. It happen on Vulkan and D3D9/11 backend only, OpenGL is look fine.

![NPJH50878_00017](https://github.com/hrydgard/ppsspp/assets/26355472/7fe56e0a-1ffc-43f6-a6c8-d8198ef20a98)

### What should happen

Should rendering texture detail correct with ktx2 format like OpenGL backend.

![NPJH50878_00016](https://github.com/hrydgard/ppsspp/assets/26355472/fdafa989-7641-46d6-8aab-3d5e6737b0fd)

### GE frame capture

I tried but seem like can't capture textures missing detail issue. 

[DUMP.zip](https://github.com/hrydgard/ppsspp/files/12318683/DUMP.zip)

### Platform

Windows

### Mobile phone model or graphics card

Intel HD Graphic 520.

### PPSSPP version affected

v1.14.4-941-g37c1e17dc	

### Last working version

v1.14.4-938-ge6ceaa541	

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Turn up anisotropic filtering to max, and it should look better. Mipmapped textures need that to look sharp at angles like that.

**Comment by Saramagrean** [comment]
I use default settings, anisotropic filtering it set 16x already but texture still missing detail.

Note: I convert png to ktx2 without mipmap.

> for %%f in (*.png) do (
>    basisu "%%f" -ktx2
> )

**Comment by hrydgard** [comment]
Well on the screenshot it does look like mipmapping without anisotropic filtering is happening(and possibly with a wrong detail bias)! Very odd...

**Comment by bslenul** [comment]
Tested out of curiosity using https://github.com/Saramagrean/TKD_KWM-HD-Texture-Pack

Unlike OP I'm getting the same results with any renderer, including GL 🤔 

Without custom textures:

![image](https://github.com/hrydgard/ppsspp/assets/33353403/57ac12db-9170-481f-9978-ce7b3389faec)

Textures in .ktx2 format:

![image](https://github.com/hrydgard/ppsspp/assets/33353403/1a24a917-d7ae-421d-8e15-913e8146ada1)

Textures in .png format:

![image](https://github.com/hrydgard/ppsspp/assets/33353403/d25a1d17-cdf3-4edc-ba37-5ac54edfbb52)

So looks like it's an issue with .ktx2 format?

The aniso setting doesn't seem to change anything for me, no difference between off and 16x (with or without custom textures), idk if I'm doing anything wrong or if it depends on the games but it's been a while: https://forums.ppsspp.org/showthread.php?tid=27860

**Comment by hrydgard** [comment]
In the png case it's clear that it gets a bit grainy in the distance, so presumably there are no mipmaps being used there, leading to the sharpness:

![image](https://github.com/hrydgard/ppsspp/assets/130929/49806a00-8691-445a-b455-4721575313c7)

While the KTX2 case sure look mipmapped (without aniso, for whatever reason) to me, despite @Saramagrean saying they're not used...

**Comment by bslenul** [comment]
Ah yeah indeed, when I type `basisu -info room35.ktx2` for example I get this:

> Mipmap Levels: 10

 😅 

Also just noticed but there's `ignoreMipmap = true` inside textures.ini, is this not working or does it have another purpose than the name suggests?

**Comment by hrydgard** [comment]
ignoreMipmap there is only for the purpose of saving images.

**Comment by hrydgard** [comment]
I have found a bug though, we fail to enable aniso in the case of replacement textures with mipmaps. I'll fix that.

**Comment by bslenul** [comment]
> ignoreMipmap there is only for the purpose of saving images (whether to save mipmaps in separate little files)

Ah I see! Thanks for the explanation.

> I have found a bug though, we fail to enable aniso in the case of replacement textures with mipmaps. I'll fix that.

Nice, at least I didn't waste your time for nothing with my questions :p

**Comment by hrydgard** [comment]
https://github.com/hrydgard/ppsspp/pull/17930 should take care of it.

Thanks for asking the questions - when something looks wrong, there often is something wrong :)

**Comment by hrydgard** [comment]
Please test build 1074 or later once they appear on the buildbot.

**Comment by hrydgard** [comment]
Great, thank you for testing!
