### ISSUE TITLE
sceKernelFindModuleByName is misaligned by 4 bytes

### ISSUE THREAD

**Issue by xan1242** [hrydgard/ppsspp#17894]
### Game or games this happens in

Any

### What area of the game / PPSSPP

`sceKernelFindModuleByName` returns an `SceModule` pointer that seems to be off by 4 bytes according to the [PSPSDK structure](https://github.com/pspdev/pspsdk/blob/e20ebe38220705abcbd6693ee2161170fb9665f1/src/kernel/psploadcore.h#L30).

(Yes, I see the note in PSPSDK code, but considering there are no new firmware revisions, this should be OK)

Here's the output as [per my plugin](https://github.com/xan1242/PSPModBase/blob/master/source/PSPModBase/main.c) (compensated for [here on this line](https://github.com/xan1242/PSPModBase/blob/a976e3fd2a6961577e63031b91fbfb7e1fe079bb/source/PSPModBase/main.c#L105)).

```
00:58:333 PSPModBase   I[SCEKERNEL]: HLE\sceKernelMemory.cpp:1214 sceKernelPrintf: Found module modehsys
00:58:333 PSPModBase   I[SCEKERNEL]: HLE\sceKernelMemory.cpp:1214 sceKernelPrintf: text_addr: 0x88E9410
text_size: 0x8804000
00:58:333 PSPModBase   I[SCEKERNEL]: HLE\sceKernelMemory.cpp:1214 sceKernelPrintf: PRX module PSPModBase
00:58:333 PSPModBase   I[SCEKERNEL]: HLE\sceKernelMemory.cpp:1214 sceKernelPrintf: text_addr: 0x8E3AE50
text_size: 0x8E1D700
```

![image](https://github.com/hrydgard/ppsspp/assets/8014093/d4ab3226-f038-4fe1-a2db-7e9d184160fd)

This same function call was tested on real hardware (in kernel mode) and it worked fine.

### What should happen

Pointer should return 4 bytes later.

Example:

text_addr should be 0x8804000 for modehsys

text_addr should be 0x8E1D700 for PSPModBase

### Platform

Windows

### Mobile phone model or graphics card

-

### PPSSPP version affected

v1.15.4-956-g094c43299

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by xan1242** [comment]
This will need a second opinion...

I've ran into the same issue with this function on real hardware actually!

I'm not entirely sure what went out of order, but I don't remember this being a problem before... I suspect it has something to do with the SDK but I checked with both a Linux and Windows toolchain (that I built myself recently) in both kernel and user mode.

In any case - as far as PPSSPP is concerned, I don't think this is a bug related to it, but rather something wacky going on with PSPSDK (or my setup in particular), so I'll check in with the PSPDEV Discord folks to see if they have anything to add.

**Comment by xan1242** [comment]
Yep, sorry about the confusion, I'm having growing pains.

It's actually a SceModule2.

https://github.com/PSP-Archive/ARK-4/blob/9db91e12f6c20f3771d263da8f27527c12a93ab8/common/include/module2.h#L23

Didn't expect so much trouble from this...

In any case, not a bug. Closing.

**Comment by hrydgard** [comment]
Thanks for checking again :) Tagging with Not a bug, indeed.
