### ISSUE TITLE
The Warriors Stage 7 fps drop

### ISSUE THREAD

**Issue by IrfanH495** [hrydgard/ppsspp#17915]
### Game or games this happens in

ULES00483 - The Warriors

### What area of the game

Vulkan
at the start of the 7th mission and several stages
![Screenshot_20230816-093932_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/a3c9a164-7ed4-4f1d-9b54-d0f2051365f4)
OpenGL
![Screenshot_20230816-095130_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/ff483c44-9e60-4147-a904-16cfe89ca722)
here is the video With debug statistics
https://youtu.be/CdG3hk9vnsM

### Speed seen in PPSSPP

20/30

### GE frame capture and debug statistics

i am having ppsspp freeze while trying to record GE frame capture 🙏🙏🙏🙏

### Platform

Android

### Mobile phone model or graphics card

Samsung M20

### PPSSPP version affected

ppsspp-v1.15.4-1043-g8e013b310-android

### Last working version

.

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the slowdown.
- [X] Include logs or screenshots of issue.

**Comment by IrfanH495** [comment]
This is recorded from the beginning of the mission with debug stats ON OpenGL
https://youtu.be/Gqk_BteO-9k

**Comment by IrfanH495** [comment]
in ppsspp v1.15.4 also experienced it only opengl, vulkan is better although sometimes the fps drops.
maybe my device is not strong enough to run it.

**Comment by IrfanH495** [comment]
It's been better in the last build

**Comment by hrydgard** [comment]
Better or perfect?

**Comment by IrfanH495** [comment]
I think it's perfect, I record,vulkan default settings
https://youtu.be/lpmXXNy8SAo
Of the many games I have, in my opinion this game is very heavy, would you like to see it.
Gachitora
https://youtu.be/jTnK1579gb0
