### ISSUE TITLE
Dragon ball z Tenkaichi tag team fps drop

### ISSUE THREAD

**Issue by qazxsw4320** [hrydgard/ppsspp#17918]
### Game or games this happens in

Dragon ball z tenkaichi tag team 

### What area of the game

Any time you transform as Goku or use a super attack as Goku or other characters as well.

### Speed seen in PPSSPP

70% (21/30)

### GE frame capture and debug statistics

![Screenshot_20230816-233152](https://github.com/hrydgard/ppsspp/assets/122139385/dc1030fb-5406-4dc9-8480-c26441764eb2)
![Screenshot_20230816-233138](https://github.com/hrydgard/ppsspp/assets/122139385/158028e3-73b4-49a7-acc4-3abc487c5e81)
![Screenshot_20230816-232419](https://github.com/hrydgard/ppsspp/assets/122139385/3118be4c-f3f3-4515-9e5f-ac67e85439a0)

### Platform

Android

### Mobile phone model or graphics card

Moto g pure

### PPSSPP version affected

15.4

### Last working version

14.4

### Graphics backend (3D API)

Vulkan

### Any other notes or things you've tried

I tried the latest build as well and the performance is even worse. Also the 14.4 version wasn't perfect and still got frame drops but they weren't as bad as 15.4 and the slow down wasn't as bad.

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the slowdown.
- [X] Include logs or screenshots of issue.

**Comment by qazxsw4320** [comment]
Here you go. Also I'm not sure if I did it right because it downloaded 2 times for some reason and hopefully I did. Also thank you for the hard work you guys do. 
[ULUS10537 (1).zip](https://github.com/hrydgard/ppsspp/files/12369335/ULUS10537.1.zip)
[ULUS10537.zip](https://github.com/hrydgard/ppsspp/files/12369338/ULUS10537.zip)

**Comment by qazxsw4320** [comment]
Here is the frame dumps. Thank you for the hard work you guys do.
[Uploading ULUS10537.zip…]()

**Comment by qazxsw4320** [comment]
Here is the frame dump. Thank you for the hard work you guys do.
[ULUS10537.zip](https://github.com/hrydgard/ppsspp/files/12369450/ULUS10537.zip)

**Comment by qazxsw4320** [comment]
[dbz save states.zip](https://github.com/hrydgard/ppsspp/files/12369720/dbz.save.states.zip)

Here are my save states. I added 3 of them.

**Comment by qazxsw4320** [comment]
Hopefully they helped

**Comment by hrydgard** [comment]
Thanks, they will help when I investigate it. I'm gonna try running on some of my devices that have the same GPU as yours.

**Comment by hrydgard** [comment]
I'm messing around on my Redmi 9X which is a slow device with the same GPU as yours. I'm trying various tweaks to make things similar to the past versions, but not seeing much difference.

At 1x, everything is fast enough in Vulkan at least, and at 2x, things indeed slow down like you say, in both GL and Vulkan. Really not sure what might have made such a difference... Hm.

**Comment by hrydgard** [comment]
@qazxsw4320 I think I'm gonna have to compare a bunch of old builds.

Could you provide the same or similar savestates, but made with 14.4 or earlier? Unfortunately states from newer versions in PPSSPP can't be loaded in older ones..

**Comment by hrydgard** [comment]
note to self, hold down L and R and press triangle to get and repeat a fairly big attack that slows down a bit.

Honestly I'm seeing very little performance difference between 14.4 and 15.4. I tested a change that disables "ubershaders" on this GPU (makes more but simpler shaders, so more shader stutter but a bit more performance) and it does seem to recover an FPS or two in this case, but nothing huge. Also, the device seems to go in and out of a higher power state so measurements are very inconsistent...

I'm considering adding the ubershader thing as an option for you and other people to play with to see if it makes a difference, because it's the only major change to GPU usage between 1.14 and 1.15. Maybe I'll just put it in developer settings as "Disable ubershaders".

**Comment by qazxsw4320** [comment]
Alright cool, thank you very much👍

**Comment by hrydgard** [comment]
Feel free to check the two new developer options I added in #17922 as well, see if they help (try turning off the two ubershader options and see if you get some speed back or not). They're in Tools / Developer Tools, scroll down.

**Comment by qazxsw4320** [comment]
Iv tried them and it's a TINY bit faster but not a major difference. I have been using the skip buffer effects option and I seem to get a bit better performance there

**Comment by hrydgard** [comment]
Yeah I thought they would have a bigger impact, either faster or slower. But something else seems to be the bottleneck, just can't figure out what..

**Comment by qazxsw4320** [comment]
@hrydgard Also I had performance problems on star wars battlefront elite squadron. But when I underclocked the cpu on that game I actually got a huge performance boost and same with battlefront 2. I hoped if I underclocked cpu on dragon ball z tenkaichi tag team I'd get the same results but it didn't make a difference

**Comment by qazxsw4320** [comment]
@hrydgard I didn't know If you make a new issue or not but I wanted to let you know the latest version, heavily slows the game in the main menu. It was normal in 16.6 but after the latest version when you go the main menu the game heavily slows down and when your in any menu but the gameplay runs at ok speed.

**Comment by hrydgard** [comment]
That's a surprise, odd. I guess you're still on the Moto G Pure?

**Comment by qazxsw4320** [comment]
@hrydgard yeah but i tried it with 2 other phones I have as well aich as a Samsung galaxy a12 and Samsung galaxy achieve, which I know is an older phone but like I said once you press start and go tot the menu it slows down heavily in newer versions and this didn't happen in 16.6. The game play did also get bit slower at 2x resolution but it runs full speed at 1x.

**Comment by hrydgard** [comment]
OK, I'll look into it soon.

**Comment by qazxsw4320** [comment]
@hrydgard ok thank you. Let me know if you need any save States or something.

**Comment by hrydgard** [comment]
@qazxsw4320 The menu slowdown should be fixed now in the latest builds, since #18505.

Can you try a [new build](https://buildbot.orphis.net/ppsspp/) and verify, and Is the in-game slowdown still there?

**Comment by qazxsw4320** [comment]
@hrydgard the slow down is fixed. However on opengl the it's a black screen with sound. In vulkan it works.

**Comment by hrydgard** [comment]
Ok, I'll look into that.

**Comment by qazxsw4320** [comment]
@hrydgard sorry, I forgot to mention on my laptop i Also get black screen on open gl,  Direct3d 11 and Direct3d .

**Comment by hrydgard** [comment]
black screen fix is in, build will be ready soon.

I think I'm going to close this, don't know if there's more we can do here.

**Comment by qazxsw4320** [comment]
@hrydgard ok everything is good now thank you very much.
