### ISSUE TITLE
NFS - Underground Rivals (Error 80110309)

### ISSUE THREAD

**Issue by basharast** [hrydgard/ppsspp#17951]
### Game or games this happens in

ULUS-10007001 - NFS - Underground Rivals

### What area of the game / PPSSPP

I went into this error accidentally when memstick files wasn't fully copied,
usually this error appear if game folder is created at `SAVEDATA` but empty
I tested on some games and they display another dialog after the error to skip
but this game will stuck at load screen.

<details>
<summary>
Screenshot
</summary>
<img src="https://github.com/hrydgard/ppsspp/assets/3244951/220279ca-2298-4dcc-bd40-16cb6a35d3c4"/>

</details>

### What should happen

It should display another dialog after this error to skip, or re-create the missing files

<details>
<summary>
Screenshot (Tekken)
</summary>
<img src="https://github.com/hrydgard/ppsspp/assets/3244951/0a50fcec-42cd-4ff7-9b5c-00cdd970bf94"/>

</details>

### Logs

[ppsspplog.txt](https://github.com/hrydgard/ppsspp/files/12408254/ppsspplog.txt)

### Platform

Windows

### Mobile phone model or graphics card

PC

### PPSSPP version affected

1.15.4-1152-g11c40e688

### Last working version

None

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
This is on the game for not error checking things properly - most likely the same thing will happen with broken savedata on a real PSP. Thus, not a PPSSPP issue. What exactly should we do here? Delete any empty folder in SAVEDATA? And if so when? Maybe a game creates it, and don't write stuff into it until later, and deleting it would break things - we can't know what all the thousands of games expect.

So, not a bug.
