### ISSUE TITLE
4 way dpad touch is not working properly i tried to turn on and off but result is same

### ISSUE THREAD

**Issue by tausifj15** [hrydgard/ppsspp#17950]
### Game or games this happens in

Tekken 6 tekken 5 

### What area of the game / PPSSPP

![Screenshot_20230822-132649](https://github.com/hrydgard/ppsspp/assets/20368006/c7882a18-eacd-4f82-a969-fde0e3bd3d77)
Whenever i try to use rising son move of jin kazuya any fighter the 4 way d pad is not working properly i thought there's something wrong with my device but it happening in other devices too but in previous version there was no issues kindly fix it

### What should happen

Whenever i try to use rising son move of jin kazuya any fighter the 4 way d pad is not working properly i thought there's something wrong with my device but it happening in other devices too but in previous version there was no issues kindly fix it

### Platform

Android

### Mobile phone model or graphics card

Poco m2 pro and redmi 10

### PPSSPP version affected

Latest builds and playstore stable version 

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
What do you mean with not working properly? Not at all, or something strange happens?

I just tried it for a bit and it seems to work fine..

**Comment by tausifj15** [comment]
I want to say that when we have to perform a move suppose we have to
perform a move which needs to press two d-pad together or three so when i
press that it doesn't work
I'm attaching a picture kindly see it it works perfectly in version 1.11.1
Is there any way I can send you a short video?

**Comment by hrydgard** [comment]
I don't see a picture, I don't think e-mail attachments work. But you can just drag small video files and images into the text edit box if you post directly on github.

**Comment by tausifj15** [comment]
Ok sir let me try

**Comment by tausifj15** [comment]
I attached video if it doesn't appear here's the link of drive
https://drive.google.com/file/d/1-0IBYGAniYLeTtAJt9RpEqTSWe1eOzb1/view?usp=drivesdk


https://drive.google.com/file/d/1-3_ni5P7hffWbN4eCo2nzMb8NCI959W7/view?usp=drivesdk

1st link for working version and second is for non working version

**Comment by hrydgard** [comment]
@tausifj15 you need to set the permission on the videos to allow everyone with a link to see them. I can't open them.

<img width="413" alt="image" src="https://github.com/hrydgard/ppsspp/assets/130929/fc8d6429-5b9c-4ef7-b8a9-7ed4c3357d93">

**Comment by tausifj15** [comment]
I updated the permission kindly check it

**Comment by hrydgard** [comment]
The Before video still won't open, but I see that four-way behavior indeed doesn't seem to work in the new video clip. Weird.

**Comment by tausifj15** [comment]
Yes it's not working in any version after 1.11.1

**Comment by hrydgard** [comment]
This is very weird. I tried:

![image](https://github.com/hrydgard/ppsspp/assets/130929/a265005f-5574-4f87-bb17-a1d2042c514f)

and no matter how hard I try, I can't get any bad diagonals to appear.


https://github.com/hrydgard/ppsspp/assets/130929/8bead83c-4cd0-418b-a035-de89bcc61240



I also tried on Pocophone F1, and it worked as expected - when the option is checked, only one of the four main directions is active at a time.

**Comment by tausifj15** [comment]
Then how it works in 1.11.1 how did you manage that time

**Comment by hrydgard** [comment]
I don't understand? It's working perfectly as designed in the videos I posted. What is wrong with them?

Also, please fix the access rights to your 1.11 video, I still can't see it. Maybe I'll understand what you mean then.

**Comment by tausifj15** [comment]
Ok, I will check.

**Comment by tausifj15** [comment]
I have changed kindly check it

**Comment by hrydgard** [comment]
Your 1.11 video does not show 4-way input, it shows 8-way, and I don't see a difference to the other video.

Let's describe the feature as designed:

If 4-way is not checked, all 8 directions are possible: Up, Up+Left, Right, Down+Right, Down, Down+Left, Left, Up+Left.

If 4-way is checked, only 4 directions are possible: Up, Right, Down, Left.

In both of your videos, I see 8 directions of input, often Down+Right are active for example. So you have not checked the 4-way option?

I really don't see what the problem is?

**Comment by hrydgard** [comment]
OK, then you formulated the issue weirdly because you're implying that the option "4-way input" is broken, which it isn't.

I think what we actually have here is some change in sensitivity for reaching the diagonals. 

I will go look for possible changes in the code that could have caused it.

**Comment by tausifj15** [comment]
It's i tried with checked or not checked both result is same. Right+down
not working together like you saw in new video

**Comment by hrydgard** [comment]
Here's a list of the changes that touch GamepadEmu.cpp between 1.11. Of course, it could also be something else, but I'll check these first, moving the probably irrelevant ones to the bottom as I go.

# Changes to check

commit fc7033318fa0088aefbd645ff6c4e083101c62db
Author: iota97 <giovi.cocco@gmail.com>
Date:   Tue Sep 21 10:35:39 2021 +0200

    Fix dpad analog overlap interaction

commit c333e2b8798e58d2124b55ec7371e4a3ee9e22ef
Merge: 3829ca067 d0af5275b
Author: Henrik Rydgård <hrydgard@gmail.com>
Date:   Mon Sep 13 22:39:18 2021 +0200

    Merge pull request #14480 from iota97/analog-head
    
    Configurable analog head size

commit 4ec1a8d12a3d4667a60c0c6ff0a69d6a342fb4af
Author: iota97 <giovi.cocco@gmail.com>
Date:   Mon Sep 13 13:22:27 2021 +0200

    Allow drag over touch DPAD and avoid analog drag to trigger other button

commit f417bb93d43a7b323b7ed153f2e091472187d559
Author: iota97 <giovi.cocco@gmail.com>
Date:   Mon Aug 30 13:13:09 2021 +0200

    Reuse translation

commit 2821035b1dce157184e855fbe82816c029c7117c
Author: iota97 <giovi.cocco@gmail.com>
Date:   Mon Aug 30 12:26:13 2021 +0200

    Support virutal button in touch gesture

commit 1d29060c3b594bd7b6f22c150bba724dd1a2d735
Merge: 6af6e3c8c ad29e5237
Author: Henrik Rydgård <hrydgard@gmail.com>
Date:   Sun Aug 29 21:39:42 2021 +0200

    Merge pull request #13107 from iota97/touch-gesture
    
    Basic mappable motion gesture

commit 58e7b6bec224195fdeb2e69d95499d7cfccaa978
Author: Henrik Rydgård <hrydgard@gmail.com>
Date:   Sat Aug 28 20:06:05 2021 +0200

    Tweak defaults some more (no L2 on xbox pads..). Minor code cleanup.

commit de68436084786708b1e6dee97be3a1ef01916795
Author: iota97 <giovi.cocco@gmail.com>
Date:   Sun Jul 11 17:51:10 2021 +0200

    Configurable analog head size

commit 928bc88b0112b7a4afcc9cb38db3973a6292abdb
Author: Henrik Rydgård <hrydgard@gmail.com>
Date:   Tue Aug 17 16:48:47 2021 +0200

    Rename Unthrottle to Fast-forward globally

commit ad29e5237e34abe19b4510b83879cc4d1e5d9c93
Author: iota97 <giovi.cocco@gmail.com>
Date:   Tue Aug 17 09:17:37 2021 +0200

    Basic mappable gesture

commit bac96bd47c12414ead56bb52544f409ea421eff5
Author: iota97 <giovi.cocco@gmail.com>
Date:   Sat Aug 7 12:47:50 2021 +0200

    Allow to disable right analog diagonal

commit 0ae0d307512c313e1242440f9455bc882bb68c6b
Author: iota97 <giovi.cocco@gmail.com>
Date:   Wed Aug 4 09:18:23 2021 +0200

    Allow to invert context dimension for combo button

commit c6ad871865e7ce856943ee6dfce5d009ec54862e
Author: Henrik Rydgård <hrydgard@gmail.com>
Date:   Mon Jul 19 10:31:28 2021 +0200

    Warning fix

commit 498878267a3bd1f552e8d027ccd9114a68dace63
Author: iota97 <giovi.cocco@gmail.com>
Date:   Thu Mar 4 10:37:35 2021 +0100

    Customizable touch control (rebased with label)

commit cd8cfcfcd729ea292fc6fc922fdcaccab0aef799
Author: Henrik Rydgård <hrydgard@gmail.com>
Date:   Fri Jul 9 10:41:26 2021 +0200

    Merge __CtrlSetAnalogX/Y into one function. Always called together.

# Changes that are likely not the cause

commit 3c778f567c7d0f1ef93e543238beae1fa091c76d
Author: Unknown W. Brackets <checkins@unknownbrackets.org>
Date:   Sun Feb 21 16:38:02 2021 -0800

    UI: Add text description for all views.

commit f32f89dd902eed360999cf64f50ee30ef073ec56
Author: Unknown W. Brackets <checkins@unknownbrackets.org>
Date:   Mon Feb 15 09:28:07 2021 -0800

    Global: Remove some unused variables.

**Comment by hrydgard** [comment]
I think the most likely culprit is commit

 https://github.com/hrydgard/ppsspp/commit/4ec1a8d12a3d4667a60c0c6ff0a69d6a342fb4af 

which maybe made it easier to "fall off" the dpad while dragging on it for the purposes of making a combo.

Later today I will experiment with changing the behavior.

**Comment by tausifj15** [comment]
Sounds like a plan!

**Comment by hrydgard** [comment]
I've added a "Sticky D-Pad" feature which I think will improve this. Check it out in buildbot version -1355 once the build is available.

**Comment by tausifj15** [comment]
It will be available in github?

**Comment by tausifj15** [comment]
Ok so i tried build 1355 which the issue is same in it but in 1360 it have
kinda fixed but not properly it's still need to be fixed if you want I can
send video again

**Comment by hrydgard** [comment]
So obvious question, did you try to check the new option "Sticky D-PAD" in 1360? I think that should help a lot in pulling off those combos.

And feel free to upload a new video, but also try please to explain in words exactly what your problem after 1.11 really is, because I still don't quite understand it.

**Comment by tausifj15** [comment]
There's a option of sticky dpad? I will send you video

**Comment by hrydgard** [comment]
@tausifj15 It would help very much if you actually read my comments. 

I wrote a few posts up that I've added a "Sticky D-Pad" feature. That's what I'm hoping for you to test, to see if it helps your problem. It's a checkbox in the control settings.

**Comment by tausifj15** [comment]
Let me try

**Comment by tausifj15** [comment]
After turning on that option it starts working perfectly like 1.11.1 thanks
for the fix

**Comment by hrydgard** [comment]
Great! Thank you for testing.
