### ISSUE TITLE
Tactics Ogre texture pack only working on 1.13.2 - needs investigation

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#17980]
Reported by CoffeePotatio on Discord.

"
This is the mod in question: https://forums.ppsspp.org/showthread.php?tid=26100 . When used in the latest, which I think is 1.15.4 on Steam Deck, most of the textures don't work. 

It will replace the cursor, as well as some text, but also turn any wavy effects into really blocky looking ones, and plain not replace the portraits, map tiles, equippable item text, most effect icons,  or background art. 

I have videos of it working and not working under the same settings on both versions, if that helps.

When I dropped 1.13.2 files into the same settings, it worked fine.
"

**Comment by CaffinatorPotato** [comment]
It's me, but apparently I forgot my old logins or something. Anyhow, here is a video of the issue.
Really hoping it can be fixed!
[https://youtu.be/xJPhofiEHd4](url)

**Comment by CaffinatorPotato** [comment]
Thank You for looking into this.

**Comment by hrydgard** [comment]
Realized that this is likely a duplicate of #17980 . Either way, I'll investigate both in just a bit.

**Comment by hrydgard** [comment]
Thanks for your nice video @CaffinatorPotato . Fix coming up.
