### ISSUE TITLE
Zettai Zetsumei Toshi 3 / Disaster Report 3 when the character has low Health fps drops

### ISSUE THREAD

**Issue by IrfanH495** [hrydgard/ppsspp#17987]
### Game or games this happens in

ULJS00191 Zettai Zetsumei Toshi 3 

### What area of the game

story mode, when the character has low Health fps drops.

### Speed seen in PPSSPP

17FPS

### GE frame capture and debug statistics

![Screenshot_20230827-161420_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/4d8e1f07-584c-48fe-a1bd-dcf0bf2c8c7a)
![Screenshot_20230827-162025_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/e3659030-f3a7-43eb-9952-32efd9a8274b)
[ULJS00191_0001.zip](https://github.com/hrydgard/ppsspp/files/12447678/ULJS00191_0001.zip)

### Platform

Android

### Mobile phone model or graphics card

Samsung M20

### PPSSPP version affected

1.13 & v1.14.1-16- & v1.15.4-1247- already tried, but it's the same

### Last working version

not found, after i remembered, i used cheat to avoid lag

### Graphics backend (3D API)

OpenGL / GLES

### Any other notes or things you've tried

try adding to compat, but generates another bug.

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the slowdown.
- [X] Include logs or screenshots of issue.

**Comment by IrfanH495** [comment]
tried it on sharp sh04h but its the same, and notice the shape of the fire there is something wrong.
![IMG-20230827-WA0002](https://github.com/hrydgard/ppsspp/assets/78854859/1ad24f41-959f-48d7-8219-8fa19f60decd)
![IMG-20230827-WA0003](https://github.com/hrydgard/ppsspp/assets/78854859/c7864c28-2b56-4563-ba69-3f8f904de7a8)

**Comment by hrydgard** [comment]
#18539 might be useful to work around this. And if that works reliably, we can add it to compat.ini.

**Comment by IrfanH495** [comment]
Yes, I really hope that 
Hopefully it's also useful in games
gachitora
Tokimeki Memorial: Forever With You
Maid Paradise

**Comment by IrfanH495** [comment]
I try 
Skip and copy to texture
readbacks become 0
![Screenshot_20231214-015915_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/e6512f23-2a56-41c2-bfde-8fd6816f4786)
but it's still there
![Screenshot_20231214-015958_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/4152e793-a942-465e-95ee-3ee1ca94db80)
that's not a problem for me, but I don't know for the developers
for gachitora!  he also readbacks became 0 character photos turned black

**Comment by hrydgard** [comment]
OK. Well, it's supposed to have the same effect as the old compat flag, just easier to experiment with.

I'll take a closer look at the GE dump sometime soon.

**Comment by IrfanH495** [comment]
![Screenshot_2024-05-27-05-10-16-101](https://github.com/hrydgard/ppsspp/assets/78854859/f042ee92-e44e-490d-a5bb-000ffa9e5a33)

sorry for bothering you all this time, now I understand it's just my device is not strong.
