### ISSUE TITLE
Ppsspp.ini file location?

### ISSUE THREAD

**Issue by Hidte09** [hrydgard/ppsspp#18000]
### What should happen

Where is ppsspp.ini file located in GitHub?

### Who would this benefit

-

### Platform (if relevant)

None

### Games this would be useful in

-

### Other emulators or software with a similar feature

-

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
It is not on github. It's created at runtime by the emulator, in the subdirectory PSP/SYSTEM inside the memstick directory of PPSSPP. Where that is depends on the platform.

The code that manages the ini file is in `Core/Config.cpp` and `.h`.

**Comment by Hidte09** [comment]
Yeah, understood
