### ISSUE TITLE
Rear view mirror glitch in Ridge Racer 2 (AMD-only issue in latest builds)

### ISSUE THREAD

**Issue by kristianity77** [hrydgard/ppsspp#18002]
### Game or games this happens in

Ridge racers 2

### What area of the game

In any race, there are now visual glitches when looking in the rear view mirror.  Happens on all renderers.  It used to work fine but am not sure which version, it's been a good few months since I last played.

### What happens

Garbled graphics where the mirror should be. You can part see the reflections but they are innacurate.

### What should happen

Should look correct 

### Platform

Android

### Mobile phone model or graphics card

AMD (Aya neo) and desktop Nvidia 3070ti

### PPSSPP version affected

Latest official and latest dev build

### Last working version

Not sure

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Hi, I don't see any problems at all with the rearview mirror. Could you upload a screenshot here? Just drag into the edit textbox when you write a comment.

**Comment by kristianity77** [comment]
![P_20230829_200013](https://github.com/hrydgard/ppsspp/assets/41517063/0c773e14-8e61-40dd-a9aa-3fb25e9b5f3a)

**Comment by kristianity77** [comment]
![P_20230829_200328](https://github.com/hrydgard/ppsspp/assets/41517063/200e5e01-df02-4577-8491-786b8b0f7d6a)

Clearer on this pic.  There is a tiny bit of the rear view mirror at the top which appears to be correct, but all at the bottom is messed up

**Comment by hrydgard** [comment]
Ok, that's weird. I don't see that at all on Windows, but will try other platforms shortly.

**Comment by kristianity77** [comment]
Just to be clear this is windows I'm using, not sure why it says android in my original post.  The error occurs no matter what renderer I use also.  This is on an Aya neo 2 device and also my desktop which are both windows 11 latest updates. One is amd 6800u with on board and graphics, the other is a 3070ti GPU

**Comment by kristianity77** [comment]
It even occurs in software rendering which surprised me

**Comment by hrydgard** [comment]
Is it on some specific track? With some specific car?

**Comment by kristianity77** [comment]
Any track, with any car

**Comment by kristianity77** [comment]
Ok to try and help I have rolled back to v1.14.2 and the issue isn't there.  It seems it's somewhere after this point it was introduced.

**Comment by hrydgard** [comment]
What about 1.15.4 ? 

I'm still really baffled, I only see correct graphics in the mirrrors, in the latest builds. Of course, some detail is dropped as it is on the real PSP, but no real glitches.

<img width="536" alt="image" src="https://github.com/hrydgard/ppsspp/assets/130929/c8364858-f25b-4880-9d15-8e259a9de908">

**Comment by kristianity77** [comment]
The latest official version works on my Nvidia card, but gives the mirror issue on my AMD card.

The AMD card version works from anything prior to 1.14.2, but not anything afterwards. I can switch between the two versions on the same system and one works, the other doesn't.  

It seems it's an issue with AMD GPUs and something has changed from the version of ppsspp a few months back to the latest ones

**Comment by hrydgard** [comment]
ok, I will check on AMD tomorrow.

**Comment by kristianity77** [comment]
![P_20230829_205210](https://github.com/hrydgard/ppsspp/assets/41517063/c7801bb4-6333-411d-b9f3-8404109266b2)

**Comment by kristianity77** [comment]
That's AMD on 1.14.2

**Comment by kristianity77** [comment]
So just one more thing to note.  I've tested quite a few of the older versions of ppsspp and the last official build that is bug free is 1.15.3.  it works perfectly on that build.  Sorry I couldn't be more help!

**Comment by hrydgard** [comment]
So you're saying that 1.15.4 is buggy then, while 1.15.3 is fine? Surprising given the small amount of differences between 1.15.3 and 1.15.4, but if that's the case, could be a useful bit of information.

**Comment by hrydgard** [comment]
Tested, my AMD RX480 renders this perfectly well, too, in both Vulkan and OpenGL (haven't yet tested the other backends)

**Comment by unknownbrackets** [comment]
Software rendering can't really be related to the graphics card, so if it happens there too it seems like it must be either related to some setting, or some different ISO...?  Or else it always happens in software rendering.

-[Unknown]

**Comment by hrydgard** [comment]
Oh yeah, forgot that the problem was reported with software too. Can we have a screenshot of that as well? Because that does seem unlikely...

**Comment by hrydgard** [comment]
I'm unable to reproduce this on anything, including on software rendering. So I'm going to post-pone further work until after 1.16.

**Comment by kristianity77** [comment]
I can reproduce this and I now know what causes it and I apologise as it seems it's not directly related to ppsspp as such.  It was a cheat I had enabled for the game unknowingly.  When I disabled it it went away. So yes, apologies!

**Comment by hrydgard** [comment]
Could you paste the particular cheat that caused it here? Maybe someday we'll add warnings for known bad cheats, and in that case it's good to have it. Though, not likely anytime soon.

**Comment by kristianity77** [comment]
It's the cheat for extended rendering distance of the mirror
