### ISSUE TITLE
AVI Recording Or Sequential Image Capture

### ISSUE THREAD

**Issue by xnamkcor** [hrydgard/ppsspp#1800]
Could we add an option for capturing frames to a series of images or an AVI file? Audio is unimportant.

**Comment by RisingFog** [comment]
Implemented in PR #8945 (based on Dolphin's implementation)

**Comment by unknownbrackets** [comment]
Is this sufficiently implemented to close or is there something still pending?

-[Unknown]

**Comment by LunaMoo** [comment]
The feature might still not work correctly, (might be buggy with non-60fps games?) but it has it's own issue for that #10632

**Comment by unknownbrackets** [comment]
Fair - since we already have issues for its bugs, I'm going to go ahead and close this one.

-[Unknown]
