### ISSUE TITLE
don't want to show pop up " choose where to keep PSP data" instead use by default app private data.

### ISSUE THREAD

**Issue by hidte9** [hrydgard/ppsspp#18021]
### What should happen

how to disable pop up " choose where to keep PSP data" and choose 'app private data' by default, cause on every launch after clearing data or cache it's askig for this

### Who would this benefit

-

### Platform (if relevant)

None

### Games this would be useful in

-

### Other emulators or software with a similar feature

-

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
This is unfortunately, as far as I known, completely impossible to implement. Due to Android's new restrictions, there's nowhere that PPSSPP could save the information about your choice that wouldn't also disappear on the re-install / uninstall.

If you know a way to do it, let me know.
