### ISSUE TITLE
Package Renaming Issue: References Not Updating Properly

### ISSUE THREAD

**Issue by FtxDev** [hrydgard/ppsspp#18035]
### Game or games this happens in

None

### What area of the game / PPSSPP

I've encountered an issue after renaming the package name from org.ppsspp.ppsspp to org.newpsp.newplay in my Android project. The problem is that some references throughout the codebase are not updating correctly to the new package name. This is causing errors in my project.

### What should happen

After renaming the package, all references to the old package name should be automatically updated to the new package name. The project should build and run without errors, but Some references are not updating to the new package name,leading to compilation errors and other issues. Even after cleaning project and rebuild project.

### Platform

Android

### Mobile phone model or graphics card

None

### PPSSPP version affected

V1.15.4

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
You're on your own on this kind of thing, sorry - this is not really something we care about working.
