### ISSUE TITLE
Daxter UI partially broken by Save New Textures setting in Vulkan without texture scaling

### ISSUE THREAD

**Issue by JimScript** [hrydgard/ppsspp#18079]
### Game or games this happens in

NPUG80329 - Daxter

### What area of the game

After new game, right in the pause screen.

### What happens

When you play it in Vulkan without texture scaling, it looks like this:
![NPUG80329_00000](https://github.com/hrydgard/ppsspp/assets/66685584/ee254792-b6f1-4195-a506-5e455f16aadb)
But when you turn on texture scaling the textures start to look like they should again:
![NPUG80329_00001](https://github.com/hrydgard/ppsspp/assets/66685584/c2624a5a-5e0f-49f5-8863-d19d247a3e55)

### What should happen

It should just look like the texture scaled one but without the scaling:
![NPUG80329_00002](https://github.com/hrydgard/ppsspp/assets/66685584/758ace33-d189-4a16-bd02-ac76b1d129fa)

### GE frame capture

No scaling:
[NPUG80329_0001.zip](https://github.com/hrydgard/ppsspp/files/12528864/NPUG80329_0001.zip)
Scaling:
[NPUG80329_0002.zip](https://github.com/hrydgard/ppsspp/files/12528866/NPUG80329_0002.zip)

### Platform

Windows

### Mobile phone model or graphics card

'NVIDIA GeForce RTX 2070 SUPER' running on driver 522.25.0.0

### PPSSPP version affected

v1.15.4-1452-g828328b50

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Hm, I can't seem to get this to happen at all. Menus work fine for me.

**Comment by JimScript** [comment]
Oh, apparently it's actually caused by the "Save New Textures" setting, but it's odd that it's not the replace textures that does it.

**Comment by JimScript** [comment]
If the texture saving system is suppose to be glitchy like that, then I guess this should be closed.

**Comment by hrydgard** [comment]
Oh, no, it's not supposed to be glitchy like that.

**Comment by hrydgard** [comment]
I still had problems reproducing until I noticed that I had texture filtering set to "Auto max quality". Having that enabled accidentally fixes the problem, so I didn't see it. Now I can repro (and hopefully fix tomorrow).
