### ISSUE TITLE
Should not try to identify homebrew for RetroAchievements

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#18074]
Currently, if you have RetroAchievements enabled, you get this when you try to launch homebrew:

"Failed to identify game. Achievements will not unlock"

Since achievements are [not supported for homebrew yet](https://github.com/RetroAchievements/rcheevos/issues/244), this is kind of unnecessary.

**Comment by ANR2ME** [comment]
The logs also flooded with warnings even when i haven't run any games yet
![image](https://github.com/hrydgard/ppsspp/assets/7974720/8ce31c7a-a6ad-42ff-bd75-1fd255561822)

**Comment by unknownbrackets** [comment]
Yeah, it's pretty annoying.  At least most of them go away if you explicitly disable achievements.

For this issue: would a popular homebrew ever be supported?

-[Unknown]

**Comment by hrydgard** [comment]
I know this is annoying, I'm gonna fix it today.

@unknownbrackets Here's the issue I created about the lack of a reliable hashing method for homebrew - if you have input, please add: https://github.com/RetroAchievements/rcheevos/issues/244
