### ISSUE TITLE
(Xbox/UWP) Most Inputs are now broken

### ISSUE THREAD

**Issue by GABO1423** [hrydgard/ppsspp#18070]
### Game or games this happens in

None

### What area of the game / PPSSPP

Trying to use the app is impossible since both the controller and any USB Keyboards are unresponsive.

### What should happen

I press a button, and the app does something.

### Platform

UWP / Xbox

### Mobile phone model or graphics card

Xbox Series X GPU

### PPSSPP version affected

v1.15.4-1437-g6d449139

### Last working version

v1.15.4-1422-g9690a71a1

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Hm, that's not good.

There is, however, nothing between 1422 and 1437 that would be a plausible cause for this. Are you sure about those numbers?

**Comment by GABO1423** [comment]
> Hm, that's not good.
> 
> There is, however, nothing between 1422 and 1437 that would be a plausible cause for this. Are you sure about those numbers?

Yes, I also looked at the commits to try and find a possible cause but nothing made sense, so I made a lucky guess and manually reverted this commit: https://github.com/hrydgard/ppsspp/commit/412c3a0cd9acfdd6caad595f0393c685645f3ce2

**Comment by hrydgard** [comment]
Huh, okay. I'll look into it.
