### ISSUE TITLE
Unable to make field private final java.lang.String java.io.File.path accessible

### ISSUE THREAD

**Issue by hidte9** [hrydgard/ppsspp#18085]
### Platform

None

### Compiler and build tool versions

-

### Operating system version

-

### Build commands used

-

### What happens

getting erros while checking out version v1.11.2 Unable to make field private final java.lang.String java.io.File.path accessible: module java.base does not "opens java.io" to unnamed module @55fc126a

### PPSSPP version affected

v1.11.2

### Last working version

-

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] Make sure to run `git submodule update --init --recursive` before building.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try deleting the build directory and running the build again.
- [ ] Check GitHub Actions, which builds every merge and PR.
- [ ] Include logs and help us reproduce.

**Comment by hrydgard** [comment]
Old versions like v1.11.2 are not supported, and there's not much we can do with a build error. Maybe newer compilers just don't like the old code, I don't know.

You're on your own with this one, sorry. And I highly suggest that you don't bother with such old versions at all - if something is not working in the newest, please report so we can fix it.
