### ISSUE TITLE
Tiger Woods PGA Tour 10 - strange striped backgrounds in UI windows (DXT5 issue?)

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#18108]
Reported by djfil007 on Discord (reported on OpenGL, Android, but also reproduces on other platforms). Can be seen in the compat reports:

https://report.ppsspp.org/game/ULUS10420_1.00#report-compat-686272

GE frame dump: [tiger ULUS10420.zip](https://github.com/hrydgard/ppsspp/files/12561427/tiger.ULUS10420.zip)

![image](https://report.ppsspp.org/uploads/ULUS10420_1.00/compat-686272.jpg)

With 2x texture scaling:

![image](https://report.ppsspp.org/uploads/ULUS10420_1.00/compat-686311.jpg)

**Comment by hrydgard** [comment]
The texture used when drawing the striped UI is a 2x32 DXT5 texture. Might be some odd behavior there.

**Comment by DjFIL007** [comment]
Thanks again for creating this.

![compat-285595](https://github.com/hrydgard/ppsspp/assets/14816160/5fd5f017-b99c-4397-93de-517673b7d4de)

above screenshot was shared by another user on https://report.ppsspp.org/game/ULUS10420_1.00#report-compat-285595 (they were back on 2019-09-02 version v1.8.0... but on a windows device... however it shows the intended result)

**Comment by hrydgard** [comment]
Yeah, indeed, hm, that's interesting.

Also, looking at the DXT5 code we do seem to handle small widths correctly - at least it looks like it.

**Comment by hrydgard** [comment]
It was a bug in the DXT5 decoder. fixed.
