### ISSUE TITLE
Hot Shots Golf Open Tee 2 readback bug

### ISSUE THREAD

**Issue by jp952000** [hrydgard/ppsspp#18117]
### Game or games this happens in

UCUS98693 V1.00

### What area of the game / PPSSPP

After starting a shot during while the power meter is going up the screen goes black on the first shot of the round. The next shot during the power meter reverts to an image of the previous shot making it impossible to stop the gauge at the correct position as you have old data on screen. This did not happen in version 1.15.4 

### What should happen

The image should stay on screen with the current shot. 

### Platform

Android

### Mobile phone model or graphics card

Google Pixel 7

### PPSSPP version affected

v 1.16

### Last working version

v 1.15.4

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
I was able to reproduce this with the European version called Everybody's Golf 2, but only every few shots, and I didn't get the black screen very often either. Still, this needs fixing - however, might have to wait until 1.16.2 as it's pretty urgent to get 1.16.1 out to fix the GL hang.

**Comment by hrydgard** [comment]
Prime suspect is #17534 . Will investigate more tonight.

**Comment by jp952000** [comment]
I'm glad you were able to identify the issue. Thank you so much for all the incredible work on this emulator.
