### ISSUE TITLE
Can't edit wiki?

### ISSUE THREAD

**Issue by leoxxx** [hrydgard/ppsspp#18118]
I can't find "eidt" on wiki page.

**Comment by hrydgard** [comment]
Had to lock it down for people not in the main contributor list due to sabotage. I guess I could add you, or if you just want to make a small change, post it here and I'll do it.

**Comment by leoxxx** [comment]
I see.
https://github.com/hrydgard/ppsspp/wiki/如何使用PPSSPP多人联机游戏
Before: 有部分游戏需要设1024上
After: 有部分游戏需要设置大于1024

**Comment by hrydgard** [comment]
Thanks, I made the edit.

I'm gonna close this, but feel free to post again in this issue anyway if you want some other small change made.
