### ISSUE TITLE
There is no update for PPSSPP on Linux

### ISSUE THREAD

**Issue by mckrvss** [hrydgard/ppsspp#18120]
Hello, when new version of PPSSPP will be available on flathub (and Discover app for Steam Deck)? Many hours after release, it is still not possible to play with RetroAchievements on Linux devices 🫤

**Comment by hrydgard** [comment]
The flatpak was added by someone unaffiliated with the project and I'm right now trying to figure out who that was...

**Comment by j8r** [comment]
There is currently this build error blocking the update for https://github.com/flathub/org.ppsspp.PPSSPP/pull/56:
```
[ 85%] Building CXX object CMakeFiles/Core.dir/Core/MIPS/MIPSDis.cpp.o
In file included from /run/build/ppsspp/Core/MIPS/MIPSCodeUtils.cpp:19:
/run/build/ppsspp/Core/MIPS/MIPSTables.h:120:54: error: ‘uint32_t’ has not been declared
  120 | typedef void (CDECL *MIPSDisFunc)(MIPSOpcode opcode, uint32_t pc, char *out, size_t outSize);
      |                                                      ^~~~~~~~
make[2]: *** [CMakeFiles/Core.dir/build.make:3464: CMakeFiles/Core.dir/Core/MIPS/MIPSCodeUtils.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:759: CMakeFiles/Core.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
Error: module ppsspp: Child process exited with code 2
```

I'll make a PR to fix it.

**Comment by hrydgard** [comment]
@j8r Thanks but as commented there, already fixed.

I'll close this as the build problem is fixed, just waiting for a new tag, which will happen today.

**Comment by hrydgard** [comment]
Tagging is done.

**Comment by hrydgard** [comment]
@j8r Tagging is done, so it should be possible to update the flathub now.
