### ISSUE TITLE
Changing the "Buffer graphics command" setting causes hangup in 1.16

### ISSUE THREAD

**Issue by NABN00B** [hrydgard/ppsspp#18122]
### Game or games this happens in

-

### What area of the game / PPSSPP

In v1.16 changing the "Buffer graphics command" setting from 1 to none, while using OpenGL, causes the emulator to hang up on every restart afterwards.

One time I did manage to get the popup with the 32bit executable saying that the OpenGL backend crashed.

### What should happen

-

### Logs

[ppsspplog.txt](https://github.com/hrydgard/ppsspp/files/12570180/ppsspplog.txt)

### Platform

Windows

### Mobile phone model or graphics card

NVIDIA GeForce GTX 1060 3GB

### PPSSPP version affected

v1.16

### Last working version

v1.15.4

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Thanks NABNOOB, I'll get this fixed tomorrow.
