### ISSUE TITLE
Unable to find which jdk version does v1.11 uses

### ISSUE THREAD

**Issue by FtxDev** [hrydgard/ppsspp#18146]
### Game or games this happens in

-

### What area of the game / PPSSPP

How to find which jdk version does v1.11 uses

### What should happen

-

### Logs

-

### Platform

Android

### Mobile phone model or graphics card

-

### PPSSPP version affected

V1.11.1

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Why would this be an interesting thing to know?

**Comment by ANR2ME** [comment]
The only JDK version i remembered using was 1.8, 1.11, and 1.13 :D it probably works with 1.8 or newer
