### ISSUE TITLE
D3D11 makes PPSSPP crash when exiting

### ISSUE THREAD

**Issue by A096** [hrydgard/ppsspp#18148]
### Game or games this happens in

None

### What area of the game / PPSSPP

Open PPSSPP, select D3D11 renderer, press Alt key and wait 3 seconds then exit, the emulator will crash.

### What should happen

It shouldn't crash.

### Platform

Windows

### Mobile phone model or graphics card

NVIDIA GeForce GTX 1050

### PPSSPP version affected

v1.14 and above

### Last working version

v1.13.2

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment]
Hmm.. i tried running PPSSPP v1.15.4 (Release x64 and also Win32) and switched from Vulkan to D3D11, but both doesn't seems to crash when i exited.

Have you tried to update your Geforce driver?

PS: I 'm using driver v536.99

**Comment by A096** [comment]
I always use latest driver(version is now 537.34), and I've tried on Win7 SP1/Win10 22H2/Win11 22H2, all of them were fresh install, but the problem is still there.

**Comment by ANR2ME** [comment]
Btw are you using SLI ?
If you are, have you try disabling it to see whether this issue related to SLI.

**Comment by A096** [comment]
No, I'm not using SLI.

**Comment by A096** [comment]
Maybe it's random crash, PPSSPP x64 build is trying to access an address that does not exist in memory sometimes, another method is changing renderer from D3D11 to any other, it'll restart the emulator, but the emulator may also crash at this moment(tested with VS2022).

**Comment by ANR2ME** [comment]
Well if you have VS2022 you can try running the Debug x64 from VS, it will shows you the location of the crash in the source code, which will be helpful in figuring out what causing it to crash.

When VS shows you the location, you can screenshot the location in the source code that also shows the call stacks (bottom right) and the auto-watches (bottom left).

**Comment by A096** [comment]
Debug build will sometimes make an instance when changing renderer backend(does not crash), only release build will crash(does not make any instance).

**Comment by A096** [comment]
Some news here... PPSSPP x64 will crash when changing renderer backend from D3D11 to any other form menu bar, changing from UI will not crash.
(Another bug... changing renderer backend from menu bar also makes PPSSPP x64 opening an instance?)

**Comment by hrydgard** [comment]
Hm, I don't see a crash myself. I do on the other hand also experience the instance thing, need to fix that at a minimum..

**Comment by hrydgard** [comment]
In the latest builds now, there should be no "instance" thing happening anymore.

**Comment by A096** [comment]
> In the latest builds now, there should be no "instance" thing happening anymore.

Thank you! 😊

**Comment by GamingDucking** [comment]
Is this issue going to close now?

**Comment by hrydgard** [comment]
I don't know, I don't think I ever got the crash so hard to verify that it's gone..

**Comment by A096** [comment]
Still crash with the latest graphic driver, if I use built-in graphic driver on Windows 10, PPSSPP will not crash.

**Comment by RokkumanX** [comment]
Yes I can confirm this issue 100 percent.

I'm using ppsspp v1.16.6-925-g789c7e503 on my i7 13700K, 64GB Ram and a RTX 4070 machine running Windows 11 Enterprise 23H2 22631.2861 on NVIDIA 546.33 Studio drivers which is a more stable GPU driver branch.

When I open ppsspp for the very first time, Direct3D 11 is set to default and as soon as I close without changing anything it's a crash to desktop.

Once I change Direct3D 11 to OpenGL in the ppsspp.ini ppsspp works perfectly again.

I always use OpenGL anyway because of my shaders.

Maybe OpenGL should be the default renderer because this issue ain't new.

**Comment by anr2me** [comment]
I just tried `v1.16.6-935-g99cf2f88f` extracted to a new folder, exiting using the [X] button nor [Exit] Button seems to be okay, but when i use File Menu -> Exit, it felt different (like a crash is occurred), doesn't always happened tho, i think i need to wait for about 4 seconds after the Games tab appeared before i Exit using Menu to trigger this crash.

**Comment by RokkumanX** [comment]
I completely forgot to mention that I'm always use the method File Menu -> Exit to exit ppsspp.
Old habit since way back with most of the software I'm using.

Like you say, it felt different (like a crash occurred) and you are exactly right on that because if you check the built in Reliability Monitor tool under Control Panel\System and Security\Security and Maintenance you'll see that ppsspp crashed to desktop.

As I mentioned earlier, once I change from Direct3D 11 to OpenGL there is no more crashing when File Menu -> Exit

**Comment by hrydgard** [comment]
Thanks, I'll look into it again soon. 

Just curious, what's the reason you're not using Vulkan? That'll get you MSAA antialiasing, for example.

If you have custom shaders that work with OpenGL and don't work with Vulkan, I'd like to have a look at them. Can you zip them up and drag into a post here?

**Comment by anr2me** [comment]
I think it's just being slow to exit sometimes when exiting using Alt-F4. 
If i set all channel to Debug level, PPSSPP freezes for a few seconds before exiting after the `NativeShutdownGraphics` shows up in the logs.
![image](https://github.com/hrydgard/ppsspp/assets/7974720/ad176548-b8af-4777-866b-771afb4124e9)

**Comment by RokkumanX** [comment]
> Thanks, I'll look into it again soon.
> 
> Just curious, what's the reason you're not using Vulkan? That'll get you MSAA antialiasing, for example.
> 
> If you have custom shaders that work with OpenGL and don't work with Vulkan, I'd like to have a look at them. Can you zip them up and drag into a post here?

I'm not really interested of using MSAA antialiasing or any other fancy stuff to enhance the image quality.

I use OpenGL in combination of the Software Renderer because I just like the look of authentic PSP rendering with dithering and I use a PSP color shader to mimic the colors of a PSP Phat screen.

One might think it's stupid that I not use my powerful hardware to it's fullest and crank the image quality up, but I'm dead set about my standards and preferals.

Even PS3 (rpcs3), Wii U (Cemu) and Switch (yuzu and Ruyjinx) get's the same treatment, it must look as authentic as possible.

Accuracy before eye candy at all costs.

**Comment by LunaMoo** [comment]
Just so you know. The only way to get authentic PSP experience is to play at tiny screen, the real deal looks nothing like software renderer and especially nothing like software renderer running on full screen of modern display. In PPSSPP software renderer was always just something to test against hardware renderer to figure out bugs of stuff that's hard to do on hardware, never something like in older emulators a choice for accuracy.
 Also if you use software renderer, your "hardware" backend setting doesn't matter at all.

**Comment by RokkumanX** [comment]
I'm not saying you are wrong or anything, I must just have been mislead or something when I gathered the information that's all.
As long as my games work the way they should and look the way they should, I don't really complain.

**Comment by hrydgard** [comment]
Yeah let's not judge anyone on what settings they like :) If you're running the software renderr, the backend does indeed not really matter.

**Comment by A096** [comment]
Some news here, I found that if I run PPSSPP, select D3D11 renderer, press Alt key and wait 3 seconds then exit PPSSPP, the emulator will crash, both 32-bit and 64-bit, Nvidia graphic cards only, PPSSPP 1.14 and above have this issue.

**Comment by anr2me** [comment]
> Some news here, I found that if I run PPSSPP, select D3D11 renderer, press Alt key and wait 3 seconds then exit PPSSPP, the emulator will crash, both 32-bit and 64-bit, Nvidia graphic cards only, PPSSPP 1.14 and above have this issue.

Apparently, when the renderer is set to D3D11, if i close down PPSSPP (tested with v1.17.1-823) using the [X] button a few (ie. 3+) seconds after the recently played games appeared, it will crashed too. Doesn't even need to press Alt key.

PS: strange, the latest devbuild only have WindowsARM version?

**Comment by A096** [comment]
I didn't update Nvidia graphic driver for a long time, stuck at v555.99.
It may just need to wait for 3 seconds to reproduce the crash, but sometimes if I close PPSSPP immediately, it will crash, too.

**Comment by hrydgard** [comment]
Hm, looks like the buildbot got stuck, I'll try to fix it.

OK, that's a nice repro, I'll check it out soon.

**Comment by fjtrujy** [comment]
> Hm, looks like the buildbot got stuck, I'll try to fix it.
> 
> OK, that's a nice repro, I'll check it out soon.

Not sure if it is 100% related but I can reproduce the same issue using software rendering in MacOS...

**Comment by anr2me** [comment]
> > Hm, looks like the buildbot got stuck, I'll try to fix it.
> > OK, that's a nice repro, I'll check it out soon.
> 
> Not sure if it is 100% related but I can reproduce the same issue using software rendering in MacOS...

Have you tried with this[ commit](https://github.com/hrydgard/ppsspp/pull/19410/files)? even though the title mentioned Windows, but the fix itself doesn't seems to be Windows-specific, it's a case suspected to tried to lock an already destroyed lock at shutdown.

**Comment by hrydgard** [comment]
I think this may be fixed. Please re-open if not.

**Comment by A096** [comment]
Thanks for the fix! Now PPSSPP never crash!
