### ISSUE TITLE
Which c++ file responsible for showing pop up screen with storage permission.

### ISSUE THREAD

**Issue by FtxDev** [hrydgard/ppsspp#18150]
### Game or games this happens in

None

### What area of the game

Which c++ file responsible for showing pop up screen with storage permission, and which class handles those permissions, can we show first boot memstick screen before logo screen.

### Speed seen in PPSSPP

None

### GE frame capture and debug statistics

None

### Platform

Android

### Mobile phone model or graphics card

None

### PPSSPP version affected

V1.15.4

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try changing graphics settings to determine if one causes the slowdown.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
THe code for that screen is UI/MemStickScreen.cpp / h.

What difference would it make if it was shown before the logo?

**Comment by Hidte09** [comment]
Not as much, but it would provide more seamless experience if those permission were asked before entering into emulator, like during first launch show pop up then start logo then emulator.
