### ISSUE TITLE
Using the new JIT IR engine causes some funny glitches

### ISSUE THREAD

**Issue by aeiouaeiouaeiouaeiouaeiouaeiou** [hrydgard/ppsspp#18159]
### Game or games this happens in

NPJH-50333 - Kurohyou Ryu ga Gotoku Shinshou (original/translation patch)

### What area of the game

Select the JIT IR engine in settings, every scene with 3D objects

### What happens

![Screenshot (238)](https://github.com/hrydgard/ppsspp/assets/69355938/47b13bc4-4189-4954-8a19-089a0b392d53)

### What should happen

![Screenshot (237)](https://github.com/hrydgard/ppsspp/assets/69355938/a8fd1d9e-42aa-4919-b295-18222bd32e78)

### Platform

Windows

### Mobile phone model or graphics card

AMD Radeon 6630M

### PPSSPP version affected

1.16.1

### Last working version

1.15.4 (where is not available)

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
It also affects NPJH-50562 (Kurohyou 2 Ryu ga Gotoku Ashura Hen).

![Screenshot (239)](https://github.com/hrydgard/ppsspp/assets/69355938/d9c4cfa4-7649-4b8f-b8e0-b7feafd588a4)

![Screenshot (240)](https://github.com/hrydgard/ppsspp/assets/69355938/4167b547-94d5-4fc8-aa39-3b9d656ba74d)

**Comment by unknownbrackets** [comment]
Hm, on Windows I'm not seeing these issues at all in the demo for Kurohyou 2.  Walking around and getting into a fight all look fine.  Maybe the full game does something differently.

Are you seeing this in any other games?

Under Developer tools -> JIT debug tools, does disabling any of the VFPU ones, regalloc, etc. help?

-[Unknown]

**Comment by unknownbrackets** [comment]
New information: seems this only happens for devices lacking BMI2, which narrows the possible issue a good bit.

-[Unknown]

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
Tried the nightly build, it's fixed now. Thanks!
