### ISSUE TITLE
Consider -fno-math-errno

### ISSUE THREAD

**Issue by fp64** [hrydgard/ppsspp#18156]
### Platform

Linux / BSD

### Compiler and build tool versions

GCC 10.2.1

### Operating system version

GNU/Linux

### Build commands used

./b.sh

### What happens

Unlike the value-changing optimizations (`-ffast-math`), the `-fno-math-errno` is widely considered a good idea (see e.g. [here](https://stackoverflow.com/a/57674631) for a nice write-up).
The C++ Standard doesn't even *guarantee* math functions set `errno` in the first place, and, as far as I can tell, PPSSPP does not check the math errno in any way (I'm surprised `errno` is used as much as it is, in other places).
The most obvious difference is that `sqrtf` [compiles](https://godbolt.org/z/qodYxszb4) to `sqrtss  xmm0, xmm0` rather than
```
        pxor    xmm1, xmm1
        ucomiss xmm1, xmm0
        ja      .L10
        sqrtss  xmm0, xmm0
        ret
.L10:
        jmp     sqrtf
```
but some other functions are also affected (`lrintf`, etc.). The example is x86, but ARM is similar.

Unfortunately, there does not seem to be a similar option for MSVC.

Adding `-fno-math-errno` to CMakeLists.txt did not cause any obvious problems, and seems to improve performance a bit, when tested in Ridge Racer on SoftGPU on my system (or it might have been noise).

Planning to add it, if there are no objections.

Note: it apparently also [messes with errno of malloc](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=88576), which should not be problematic.

### PPSSPP version affected

v1.16-4-gd4365c6ae

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] Make sure to run `git submodule update --init --recursive` before building.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try deleting the build directory and running the build again.
- [ ] Check GitHub Actions, which builds every merge and PR.
- [ ] Include logs and help us reproduce.

**Comment by unknownbrackets** [comment]
Yeah, I don't really see a downside.  In theory, we might someday want to more accurately (read: at all) update the fcr31 exception bits, but I don't think I've ever seen a game read them.  Doesn't mean it can't happen, though...

-[Unknown]
