### ISSUE TITLE
Libretro Netplay Support

### ISSUE THREAD

**Issue by thealidev** [hrydgard/ppsspp#18153]
### What should happen

Well
PPSSPP is my fav emulator
But it doesn't have Netplay Support in libretro cores

I recerched on core building and get known that i need to contribute/open issue here
So kindly can you add Netplay on RetroArch
I will be thankful 😁🙏

### Who would this benefit

Everyone

### Platform (if relevant)

None

### Games this would be useful in

Tekken 6 , and many more

### Other emulators or software with a similar feature

PPSSPP (Without Core)

### Checklist

- [x] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by ANR2ME** [comment]
As i remembered libretro core have multiplayer support (since it have multiplayer settings exposed too), what kind of netplay do you mean?

**Comment by thealidev** [comment]
RetroArch Netplay

**Comment by thealidev** [comment]
![Screenshot_20230915-163509_RetroArch](https://github.com/hrydgard/ppsspp/assets/84855696/8b59ac01-c1ab-4369-b7ff-223856f94cd2)
Here is proof 🧾

**Comment by ANR2ME** [comment]
Well if you read at the FAQ https://docs.libretro.com/guides/netplay-faq/

It seems to be a limitation from RetroArch implementation.
> Can I play GB / GBC / GBA / PSP / 3DS games with multiple people via RetroArch Netplay?[¶](https://docs.libretro.com/guides/netplay-faq/#can-i-play-gb-gbc-gba-psp-3ds-games-with-multiple-people-via-retroarch-netplay)
>
>    No, RetroArch's netplay is not link-cable emulation, GB, GBA, PSP netplay are currently not possible with our implementation. One notable exception is same game GB/GBC Netplay via the TGB-Dual and Sameboy cores.

**Comment by thealidev** [comment]
Bye

**Comment by thealidev** [comment]
So
Anyone here know any free libretro frontend with good Netplay

**Comment by thealidev** [comment]
That supports ppsspp
