### ISSUE TITLE
Enabling minifying, proguard, app gets crashed.

### ISSUE THREAD

**Issue by Hidte09** [hrydgard/ppsspp#18160]
### What should happen

How to Obfuscate ppsspp classes, codebase to use R8 without breaking ppsspp app main functionality to avoid crashing app.

### Who would this benefit

To avoid unused methods, fields, and to identify and remove dead code

### Platform (if relevant)

None

### Games this would be useful in

Many

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
No.
