### ISSUE TITLE
UI fonts are not loaded in Vulkan

### ISSUE THREAD

**Issue by dirctbe** [hrydgard/ppsspp#18163]
### Game or games this happens in

UI

### What area of the game

UI

### What happens

When I change to Vulkan:

![ppsspp3](https://github.com/hrydgard/ppsspp/assets/145274554/d2f7dee3-b961-4d12-b38f-34d7d85d3776)
![ppsspp4](https://github.com/hrydgard/ppsspp/assets/145274554/d77d6738-0426-43ee-8b90-0efdb932f662)

### What should happen

In OpenGL:

![ppsspp1](https://github.com/hrydgard/ppsspp/assets/145274554/a5c0b015-34bb-44d3-9cbb-e7ea1c15326f)
![ppsspp2](https://github.com/hrydgard/ppsspp/assets/145274554/d8f217b6-ed47-4e45-9f5c-e4d08486d06e)

### Platform

Linux / BSD

### Mobile phone model or graphics card

Intel HD Graphics 4000

### PPSSPP version affected

v1.16.1

### Last working version

v1.15.4

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Hm, fixed a similar issue recently, I guess it somehow hurt this GPU... Quite odd..

**Comment by dirctbe** [comment]
Thank you for your support

**Comment by hrydgard** [comment]
https://vulkan.gpuinfo.org/displayreport.php?id=21421 should be the same one, though driver version can differ. Notably, it doesn't support the R4G4B4A4_UNORM_PACK16 which is the only format we currently use in SDLTextDrawer, so that's the problem.

A fairly easy fix, I'll get it done tomorrow.
