### ISSUE TITLE
Mali-400 max shader complexity error

### ISSUE THREAD

**Issue by unknownbrackets** [hrydgard/ppsspp#1816]
From reporting, it looks like sometimes we generate very complex shaders.  Affected games seem to include Assassin's Creed: Bloodlines™, The 3rd Birthday, Tony Hawk's Underground 2 Remix, and SOULCALIBUR: Broken Destiny.  This may be responsible for missing or broken graphics that occur only on Mali-400 GPU devices (although maybe other mobile GPUs may have a similar issue.)

```
Error in shader compilation: info: 0:1: F0003: Shader too long. This shader is 541 instruction words long, but
            Mali-400 GP only supports up to 512 instruction words.
 / code: precision highp float;
attribute vec4 a_weight0123;
attribute vec4 a_weight4567;
attribute vec3 a_position;
attribute vec2 a_texcoord;
attribute mediump vec3 a_normal;
uniform mat4 u_proj;
uniform lowp vec4 u_matambientalpha;
uniform vec2 u_fogcoef;
uniform mat4 u_world;
uniform mat4 u_view;
uniform vec4 u_uvscaleoffset;
uniform mat4 u_bone0;
uniform mat4 u_bone1;
uniform mat4 u_bone2;
uniform mat4 u_bone3;
uniform mat4 u_bone4;
uniform mat4 u_bone5;
uniform mat4 u_bone6;
uniform mat4 u_bone7;
uniform lowp vec4 u_ambient;
uniform lowp vec3 u_matdiffuse;
uniform lowp vec4 u_matspecular;
uniform lowp vec3 u_matemissive;
uniform vec3 u_lightpos0;
uniform vec3 u_lightdir0;
uniform vec3 u_lightatt0;
uniform float u_lightangle0;
uniform float u_lightspotCoef0;
uniform lowp vec3 u_lightambient0;
uniform lowp vec3 u_lightdiffuse0;
uniform lowp vec3 u_lightspecular0;
uniform vec3 u_lightpos1;
uniform vec3 u_lightdir1;
uniform vec3 u_lightatt1;
uniform float u_lightangle1;
uniform float u_lightspotCoef1;
uniform lowp vec3 u_lightambient1;
uniform lowp vec3 u_lightdiffuse1;
uniform lowp vec3 u_lightspecular1;
uniform vec3 u_lightpos2;
uniform vec3 u_lightdir2;
uniform vec3 u_lightatt2;
uniform float u_lightangle2;
uniform float u_lightspotCoef2;
uniform lowp vec3 u_lightambient2;
uniform lowp vec3 u_lightdiffuse2;
uniform lowp vec3 u_lightspecular2;
varying lowp vec4 v_color0;
varying vec2 v_texcoord;
varying float v_fogdepth;
void main() {
  vec3 worldpos = vec3(0.0);
  vec3 worldnormal = vec3(0.0);
  worldpos += a_weight0123.x * (u_bone0 * vec4(a_position.xyz, 1.0)).xyz;
  worldnormal += a_weight0123.x * (u_bone0 * vec4(a_normal, 0.0)).xyz;
  worldpos += a_weight0123.y * (u_bone1 * vec4(a_position.xyz, 1.0)).xyz;
  worldnormal += a_weight0123.y * (u_bone1 * vec4(a_normal, 0.0)).xyz;
  worldpos += a_weight0123.z * (u_bone2 * vec4(a_position.xyz, 1.0)).xyz;
  worldnormal += a_weight0123.z * (u_bone2 * vec4(a_normal, 0.0)).xyz;
  worldpos += a_weight0123.w * (u_bone3 * vec4(a_position.xyz, 1.0)).xyz;
  worldnormal += a_weight0123.w * (u_bone3 * vec4(a_normal, 0.0)).xyz;
  worldpos += a_weight4567.x * (u_bone4 * vec4(a_position.xyz, 1.0)).xyz;
  worldnormal += a_weight4567.x * (u_bone4 * vec4(a_normal, 0.0)).xyz;
  worldpos += a_weight4567.y * (u_bone5 * vec4(a_position.xyz, 1.0)).xyz;
  worldnormal += a_weight4567.y * (u_bone5 * vec4(a_normal, 0.0)).xyz;
  worldpos += a_weight4567.z * (u_bone6 * vec4(a_position.xyz, 1.0)).xyz;
  worldnormal += a_weight4567.z * (u_bone6 * vec4(a_normal, 0.0)).xyz;
  worldpos += a_weight4567.w * (u_bone7 * vec4(a_position.xyz, 1.0)).xyz;
  worldnormal += a_weight4567.w * (u_bone7 * vec4(a_normal, 0.0)).xyz;
  worldpos = (u_world * vec4(worldpos * 1.992188, 1.0)).xyz;
  worldnormal = (u_world * vec4(worldnormal, 0.0)).xyz;
  worldnormal = normalize(worldnormal);
  vec4 viewPos = u_view * vec4(worldpos, 1.0);
  lowp vec3 unlitColor = u_matambientalpha.rgb;
  lowp vec4 lightSum0 = u_ambient * u_matambientalpha + vec4(u_matemissive, 0.0);
  lowp vec3 lightSum1 = vec3(0.0);
  vec3 toLight0 = u_lightpos0;
  float dot0 = dot(normalize(toLight0), worldnormal);
  float distance0 = length(toLight0);
  float lightScale0 = 0.0;
  float angle0 = 0.0;
  lightScale0 = 1.0;
  vec3 diffuse0 = (u_lightdiffuse0 * u_matdiffuse) * max(dot0, 0.0);
  lightSum0 += vec4((u_lightambient0 + diffuse0)*lightScale0, 0.0);
  vec3 toLight1 = u_lightpos1;
  float dot1 = dot(normalize(toLight1), worldnormal);
  float distance1 = length(toLight1);
  float lightScale1 = 0.0;
  float angle1 = 0.0;
  lightScale1 = 1.0;
  vec3 diffuse1 = (u_lightdiffuse1 * u_matdiffuse) * max(dot1, 0.0);
  lightSum0 += vec4((u_lightambient1 + diffuse1)*lightScale1, 0.0);
  vec3 toLight2 = u_lightpos2;
  float dot2 = dot(normalize(toLight2), worldnormal);
  float distance2 = length(toLight2);
  float lightScale2 = 0.0;
  float angle2 = 0.0;
  lightScale2 = 1.0;
  vec3 diffu
```

(unfortunately, the full shader is truncated, but it seems relatively clear why it is so many instructions.)

-[Unknown]

**Comment by cmrhere2play** [comment]
is there a solution this only happens with MHP3 HD

**Comment by IDSG** [comment]
I am getting a lot of "hardware transform error - failing back to software" when playing Persona 3, my GPU is a mali 400MP2, runing CM10.2, this is the only game that have this problem, i know this is Mali 400 driver issue

**Comment by unknownbrackets** [comment]
I think there might not be much else we can do here, except:
1. Expand software skinning to handle morph + skin, which happens but is uncommon.
2. Ignore user settings and force software skinning on when we detect this.

Or should we just close this?  We're pretty much limited on what we can do on the GPU with these drivers.

-[Unknown]

**Comment by unknownbrackets** [comment]
So, actually, there are some reports of shader failures even without any bones.  So software skinning doesn't solve this completely, although it does help it.

One failing shader had all 4 lights enabled, diffuse, fog, and u_uvscaleoffset (so maybe prescale would help, at least shave off one vec4.)

-[Unknown]

**Comment by hrydgard** [comment]
@unknownbrackets  hm. At least it would probably reduce the impact of the problem to force software-skinning on 400MP or less...

**Comment by unknownbrackets** [comment]
Yeah, that might be a good idea.  Or we could try forcing it on before falling back to software?  Though the first draw would likely fail.

-[Unknown]

**Comment by VtrFarias** [comment]
mr. hrydgard, i'm stuck in Ghost of Sparta. Everytime i try to play a quicktime event the moment Erinys in her giant bird form attacks me, the PPSSPP suddenly stops recognizing the analog and starts acting like i'm pressing the wrong commands, be it on the gamepad or the buttons of keyboard. This only happens in this game. And i've tried to do with the on-screen controls, also. Every option was a failure. Does anybody here know if this is a glitch? I've even tried to accept death in the game and quit it, restarting both the emulator and the game and going again all the way between the savepoint and her. Even this didn't work. Is this a glitch?

**Comment by hrydgard** [comment]
@VtrFarias Sounds a bit like a problem we've seen earlier in the game where if you change the PSP CPU clock, either under or overclock, things related to the analog stick go wrong. Can you set the PSP clock frequency to 0 (default) in the settings and try again?

**Comment by unknownbrackets** [comment]
It turns out a very similar error occurs on Intel cards with Direct3D:

X4004: program too complex; there are more active values than registers

http://report.ppsspp.org/logs/kind/687

-[Unknown]

**Comment by hrydgard** [comment]
That's not just @xebra's spline shaders? Because that's the reason we don't have support for those in D3D, IIRC (or it was some similar error).

**Comment by unknownbrackets** [comment]
Well, it was reported before hardware tessellation was even implemented, and in stable versions presumably without that change merged...

-[Unknown]

**Comment by unknownbrackets** [comment]
As this issue is now 5 years old, and the affected devices are becoming less common.  We've tried many things to reduce the complexity, some with success, but I think our fallback to software transform will have to due for the remaining cases.

-[Unknown]

**Comment by anarsoul** [comment]
If anyone's still interested in Mali4x0: vertex shader compilation error cause isn't bad compiler, it's actually hardware limitation. Utgard has different ISAs for GP (vertex processor) and PP (pixel processor), and unfortunately GP has hard limit of 512 instructions (single instruction can actually hold multiple ops, but it's different story). PP is a lot more flexible. I'm not sure if it helps you anyhow - but if you can move some calculations from vertex shader into fragment shader (e.g. v_texcoord?) it should help.

**Comment by xsacha** [comment]
@anarsoul
Thanks for that. I don't think any effort should be made to accommodate insufficient hardware to the detriment of modern hardware. Or any time wasted for that matter.
