### ISSUE TITLE
Should refactor text rendering to share texture management

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#18167]
Similar issues keep turning up in multiple backends, see #18163 . There's really no reason to duplicate the texture format detection and management across our multiple text renderers.

Will do a quickfix for #18163 now, and refactor after 1.16.x is done.

Additionally, should ship the Mac version with SDL2_ttf, dmg here: https://github.com/libsdl-org/SDL_ttf/releases

Additonally, for some reason I can't get PPSSPP to use SDL2_ttf on my Linux laptop:

```
CMake Warning at CMakeLists.txt:263 (find_package):
  By not providing "FindSDL2_ttf.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "SDL2_ttf",
  but CMake did not find one.

  Could not find a package configuration file provided by "SDL2_ttf" with any
  of the following names:

    SDL2_ttfConfig.cmake
    sdl2_ttf-config.cmake

  Add the installation prefix of "SDL2_ttf" to CMAKE_PREFIX_PATH or set
  "SDL2_ttf_DIR" to a directory containing one of the above files.  If
  "SDL2_ttf" provides a separate development package or SDK, be sure it has
  been installed.
```

Shouldn't CMake include a FindSDL2_ttf by now?

**Comment by hch12907** [comment]
I have a commit for the CMake problem. Ubuntu and Debian aren't updated enough to include the .cmake files

https://github.com/hch12907/ppsspp/commit/fa8d054b08823e3beb59bd280374c0426bc5947d

**Comment by hrydgard** [comment]
Ah, okay. Feel free to PR that!

**Comment by hrydgard** [comment]
This is done.
