### ISSUE TITLE
A vertical line shows up in the main menu when using SDL Vulkan

### ISSUE THREAD

**Issue by hch12907** [hrydgard/ppsspp#18178]
### Game or games this happens in

None

### What area of the game / PPSSPP

![image](https://github.com/hrydgard/ppsspp/assets/7030150/4df94e06-bd7e-46a1-aefb-5d535034f0d0)

Zoomed in:
![image](https://github.com/hrydgard/ppsspp/assets/7030150/7f46bd5c-4ad6-4126-bbb5-29401d06a710)

Reproducing this bug is fairly annoying: you have to horizontally resize the window until you see a line pop up. Unless you have a 1080p screen, in which case running `PPSSPPSDL --dpi 1.3` (giving you 1477px window width when maximized) reproduces the bug consistently.

The OpenGL backend doesn't seem to have this bug.

### What should happen

The line shouldn't be there

### Platform

Linux / BSD

### Mobile phone model or graphics card

AMD Renoir

### PPSSPP version affected

master

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment]
I remembered seeing such line on an old PC game (Carmageddon 2) which occurred when i use enhancement from AMD driver settings (like sharpening or something, i forgot since i don't have AMD GPU anymore)

Do you perhaps have enhancement being enforced at AMD driver settings?

**Comment by hrydgard** [comment]
Hm, that's quite curious - do you see this with the other background settings, or with a background image?

**Comment by hch12907** [comment]
Doesn't seem to happen with other background settings, only when using Waves does this problem occur.

**Comment by hrydgard** [comment]
OK, I think it might just be a bug in waves then. Should be relatively easily fixable, I'm leaving this tagged for 1.17.
