### ISSUE TITLE
the retroachievements function does not work

### ISSUE THREAD

**Issue by BENDER35** [hrydgard/ppsspp#18171]
### Game or games this happens in

all

### What area of the game / PPSSPP

retroachievements log area

### What should happen

When trying to log in to retroachievements I get the error in the image

![Captura de pantalla -2023-09-18 22-34-40](https://github.com/hrydgard/ppsspp/assets/62604047/506813e8-ccc9-4b58-9ae3-59bbe71cb624)

I have Ubuntu Mate 22.04 LTS and the flatpak installed is the one from the PPA, is there a way to solve this error? And if I have to install something from Flatpak, what package should I install?

waiting for a response, receive a greeting

### Platform

Linux / BSD

### Mobile phone model or graphics card

intel graphics 2000

### PPSSPP version affected

1.16.1

### Last working version

1.16.1

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
This is both known, reported and fixed already (#18161). 1.16.2 going out tomorrow most likely.
