### ISSUE TITLE
God of War: GoS 1.16.2 crash

### ISSUE THREAD

**Issue by ripcord95** [hrydgard/ppsspp#18188]
### Game or games this happens in

UCES01401 - God of War - Ghost of Sparta

### What area of the game / PPSSPP

starting the game, ppsspp crashes after clicking the game.

### What should happen

it should work. works well on 1.16.1 then i updated today, now it keeps crashing.

### Platform

Android

### Mobile phone model or graphics card

Poco X3 Pro

### PPSSPP version affected

1.16.2

### Last working version

1.16.1

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by ripcord95** [comment]
crashes on vulkan, opengl works

**Comment by ANR2ME** [comment]
Could you try the dev builds between v1.161 and v1.16.2 from here https://buildbot.orphis.net/ppsspp/index.php?m=fulllist to find out which changes causing it to crash so it can be fixed sooner.

You can bisect it by starting from the middle and goes up/down halfway until you can shorten the gap and found the exact build that starts crashing.

**Comment by hrydgard** [comment]
Also could you try a very fresh build, from the same lists? v1.16.2-22 or newer?
