### ISSUE TITLE
People for BootPSP needed

### ISSUE THREAD

**Issue by mmoeller86** [hrydgard/ppsspp#18196]
### Platform

None

### Compiler and build tool versions

GCC or CLANG

### Operating system version

All

### Build commands used

Hello dear PPSSPP Team,

I have a new project called BootPSP which allows you to boot the PSP Operating System using Emulation.
It is based on this Project.
The aim is to enable the Emulator to boot to the PSP Operating System.

The URL is: https://github.com/mmoeller86/BootPSP
There also are other projects to which you can also contribute.
Have a look at: https://github.com/mmoeller86

Greets,
Martin

### What happens

None.

### PPSSPP version affected

All

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] Make sure to run `git submodule update --init --recursive` before building.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try deleting the build directory and running the build again.
- [ ] Check GitHub Actions, which builds every merge and PR.
- [ ] Include logs and help us reproduce.

**Comment by hrydgard** [comment]
Recruiting for other projects is not a valid issue for the issue tracker.

Also, feel free to simply contribute the needed code directly to the PPSSPP project.
