### ISSUE TITLE
Toca 2006 crash reported with OpenGL

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#18191]
Unclear what other versions of PPSSPP are affected, apparently not new. This was reported through e-mail.

Affected device: "Sony Xperia XZ1, Android 9, SD835, Adreno 540, 4GB RAM. "

https://github.com/hrydgard/ppsspp/assets/130929/84610a59-42d7-4297-95ad-7ac1971e7307

Leaning towards that this might just be a broken ISO?

**Comment by unknownbrackets** [comment]
This could also be that Adreno resource deadlock issue in some new way.  There was another issue about Persona 3 recently (#18177), which was also affected by the resource deadlock in the Adreno 3xx and 5xx drivers.

-[Unknown]

**Comment by hrydgard** [comment]
I'm gonna chalk this up to being the persona driver bug.. closing.
