### ISSUE TITLE
Legend of Heroes: Trails in the Sky 1.16.3 crash

### ISSUE THREAD

**Issue by chia97** [hrydgard/ppsspp#18202]
### Game or games this happens in

ULUS-10540 - The Legend of Heroes: Trails in the Sky (UNDUB)

### What area of the game / PPSSPP

Game immediately crashed after launching it in Vulkan backend, but still able to launch in OpenGL backend. This does not happen in PPSSPP 1.16.1 and lower. Bug still present in 1.16.2 and 1.16.3.

### What should happen

It shouldn't crash.

### Platform

Android

### Mobile phone model or graphics card

Xiaomi Redmi Note 9S

### PPSSPP version affected

v1.16.3

### Last working version

v1.16.1

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by Chronosomber** [comment]
Unrelated game, but can confirm that this also happened with Final Fantasy Type-0

**Comment by hrydgard** [comment]
Thanks for reporting. Could you guys try the latest build from https://buildbot.orphis.net/ppsspp/ ?

I will also do some testing myself, I'm trying on a bunch of my phones but am having problems reproducing these new crashes, unless it was the geometry shader thing that I fixed yesterday..

**Comment by chia97** [comment]
> Thanks for reporting. Could you guys try the latest build from https://buildbot.orphis.net/ppsspp/ ?
> 
> I will also do some testing myself, I'm trying on a bunch of my phones but am having problems reproducing these new crashes, unless it was the geometry shader thing that I fixed yesterday..

I tried the latest build v1.16.3-32-g559cc60a6. The game is running properly on Vulkan backend, thank goodness. The problem is likely the geometry shader you mentioned.

**Comment by hrydgard** [comment]
@chia97 thank you very much for reporting. 

I am going to release a new version with the latest changes today or tomorrow.
