### ISSUE TITLE
PPSSPP data move to SD problem 

### ISSUE THREAD

**Issue by EPIC3477** [hrydgard/ppsspp#18253]
### Game or games this happens in

N/A

### What area of the game / PPSSPP

N/A

### What should happen

![Screenshot_2023_0927_202407](https://github.com/hrydgard/ppsspp/assets/91116523/e97348f4-915d-4fa9-bfa9-0a74b9fb43b0)

I tried to move my data on my sdcard and I wait for a minute but it's stuck on texture for a long time and I wait for an hour but not change still on texture

(Sorry for bad English XD)

### Platform

Android

### Mobile phone model or graphics card

Vivo y91 - android8 - snapdragon 439

### PPSSPP version affected

V1.16.3

### Last working version

V1.16.3

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Should be fixed by #18744, hopefully.
