### ISSUE TITLE
Crash loading specific texture pack on iOS (Valkyria Chronicles 3)

### ISSUE THREAD

**Issue by ilego1** [hrydgard/ppsspp#18259]
### Game or games this happens in

ULJM05781

### What area of the game / PPSSPP

PPSSPP Version 1.15
Device Used: Tablet
OS: iOS
Technical specifications of device: Doesn’t exactly tell me but here is link https://support.apple.com/kb/SP849?locale=en_US
Game: Valkyria Chronicles 3 (190394DE)
Rendering Backend used: Vulkan
List setting used: Default values
What version was it last successfully run: None
Issue: Crash when using custom textures once I press start on UI or controller to either skip opening video or at main menu.

### What should happen

Shouldn’t crash

### Platform

iOS

### Mobile phone model or graphics card

iPad 9th generation

### PPSSPP version affected

1.15

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [x] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Do you know if this happens on PC too with this texture pack?

It's possible that compressed textures aren't working on iOS for whatever reason. Does the pack use .dds or .ktx2 textures?

Can you link to the pack?

If this is iOS-specific, this won't be very high priority due to Apple's policies.

**Comment by ilego1** [comment]
I understand and apologies for spamming https://forums.ppsspp.org/showthread.php?tid=26728 is link I can check on computer and to be clear it seems to work on the program but not in Retroach but I have not fully played it on the program

**Comment by hrydgard** [comment]
Hm, it's a fairly old pack so it won't have the new formats. Then I don't have any idea... Does backend matter (opengl vs vulkan?)

**Comment by ilego1** [comment]
I can confirm it does crash on IOS will try different backend

**Comment by ilego1** [comment]
OpenGL seems to have fixed but will do more in depth testing  to be sure

**Comment by ilego1** [comment]
> Hm, it's a fairly old pack so it won't have the new formats. Then I don't have any idea... Does backend matter (opengl vs vulkan?)

I don’t know. If i mentioned but selecting a unit now causes the crash
