### ISSUE TITLE
What does buffer graphics command do? Can it increase FPS?

### ISSUE THREAD

**Issue by Gtauser123** [hrydgard/ppsspp#18265]
### Game or games this happens in

Null

### What area of the game

Null

### What happens

What does buffer graphics command do? Can it increase FPS if you do up to 2?

### What should happen

Can it increase FPS if you do up to 2?

### Platform

Android

### Mobile phone model or graphics card

Gts 450

### PPSSPP version affected

1.16

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment]
This kind of question should be asked through [PPSSPP Forum](https://forums.ppsspp.org/forumdisplay.php?fid=1) or [PPSSPP Discord Server](https://discord.com/invite/5NJB6dD).

**Comment by hrydgard** [comment]
https://www.ppsspp.org/docs/reference/settings#buffer-graphics
