### ISSUE TITLE
Texture crash on RA

### ISSUE THREAD

**Issue by ilego1** [hrydgard/ppsspp#18260]
### Game or games this happens in

UJM05781

### What area of the game / PPSSPP

RA version: latest
Core used: PPSSPP
Device Used: Tablet
OS: iOS
Technical specifications of device: Doesn’t exactly tell me but here is link https://support.apple.com/kb/SP849?locale=en_US
Game: Valkyria Chronicles 3 (190394DE)
Rendering Backend used: Vulkan
List setting used: Default values
What version was it last successfully run: None
Issue: Crash when using custom textures once I press start on UI or controller to either skip opening video or at main menu.

### What should happen

Shouldn’t crash

### Platform

libretro / Retroarch

### Mobile phone model or graphics card

iPad 9th generation

### PPSSPP version affected

Latest

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Let's combine this with #18259 .

**Comment by ilego1** [comment]
K
