### ISSUE TITLE
Crazy Taxi Fare Wars graphical glitches on IR Interpreter / JIT Using IR

### ISSUE THREAD

**Issue by ANR2ME** [hrydgard/ppsspp#18263]
### Game or games this happens in

ULUS10273

### What area of the game / PPSSPP

The models feels like being rendered to the center
![image](https://github.com/hrydgard/ppsspp/assets/7974720/ee69e154-c93a-4745-8b5c-640f479d39de)
Tested on the top most game Mode (Around Apple) of Crazy Taxi 2, but Crazy Taxi also have similar issue.

Frame Dump: (pretty much useless as it already rendered wrong and show the same thing regardless of CPU Core)
[ULUS10273_0002.zip](https://github.com/hrydgard/ppsspp/files/12753693/ULUS10273_0002.zip)

### What should happen

Should be like Interpreter or Dynarec(JIT)
![image](https://github.com/hrydgard/ppsspp/assets/7974720/f67f44ab-3e79-4cc9-af21-23131e979970)

### Platform

Windows

### Mobile phone model or graphics card

Geforce MX150

### PPSSPP version affected

v1.16.4-48-g9dcaf4e76

### Last working version

not sure, never tested this game before

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
Does disabling any of the IR instructions in IRCompVFPU help?

-[Unknown]

**Comment by ANR2ME** [comment]
> Does disabling any of the IR instructions in IRCompVFPU help?
> 
> -[Unknown]

Through source code? i'm not sure i remember/know how to do that.
However, disabling VFPU_MTX_VTFM from JIT functionality seems to fix this issue.

**Comment by unknownbrackets** [comment]
Well, there's a mistake in that, oops: https://github.com/hrydgard/ppsspp/pull/18266

Does that help?

-[Unknown]

**Comment by ANR2ME** [comment]
> Well, there's a mistake in that, oops: #18266
> 
> Does that help?
> 
> -[Unknown]

Yes, it's fixed now
