### ISSUE TITLE
UI background animation - Waves

### ISSUE THREAD

**Issue by Jeslenz** [hrydgard/ppsspp#18270]
### Game or games this happens in

Interface 

### What area of the game / PPSSPP

UI background 

### What should happen

When I move in the interface using a gamepad, using the option: System>UI background animation>Waves 
![Screenshot_20230929-224638_PPSSPP](https://github.com/hrydgard/ppsspp/assets/124852300/7fcee6b6-4a0c-47e0-88a5-82b9ea4233db)
Moves erratically
![Screenshot_20230929-225014_PPSSPP](https://github.com/hrydgard/ppsspp/assets/124852300/0521caee-2d39-486a-9235-3caba44ab6bc)
1.16.4  too
![Screenshot_20230929-225834_PPSSPP](https://github.com/hrydgard/ppsspp/assets/124852300/dbe4802a-11ea-4f70-afe6-1a5ff3a32383)
But in version 1.16.3 everything was fine
![Screenshot_20230929-230248_PPSSPP](https://github.com/hrydgard/ppsspp/assets/124852300/3962746b-c874-4682-aaf1-42cf2a198301)
It's my favorite interface setup.
If there is any way to correct it in future versions I would appreciate it. 

### Platform

Android

### Mobile phone model or graphics card

All

### PPSSPP version affected

v1.16.5

### Last working version

v1.16.3

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Seems to have gotten broken in #18210 somehow.

I'm going to try my alternate idea for that.
