### ISSUE TITLE
driver 76 crashed

### ISSUE THREAD

**Issue by forz0i** [hrydgard/ppsspp#18273]
### Game or games this happens in

ULES00740 v.1.01

### What area of the game / PPSSPP

in game party l'ambulance transportant
crash in game after line lift the train  pursuit police  

### What should happen

in game party l'ambulance transportant
crash in game after line lift the train  pursuit police  

### Platform

Windows

### Mobile phone model or graphics card

NVIDIA GEFORCE GT 740 M

### PPSSPP version affected

 1.16.5

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by sum2012** [comment]
@forz0i 
Before  line lift the train pursuit police, can you zip the save status, then upload it in here ?

**Comment by sum2012** [comment]
maybe related to 
https://github.com/hrydgard/ppsspp/issues/16904 ?

**Comment by sum2012** [comment]
@hrydgard @unknownbrackets 
I get crash from beginning.
Attach full debug log v1.16.6-260-ga4d667caf (Vukan)
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/13231890/ppsspplog.zip)

crash stack
![1](https://github.com/hrydgard/ppsspp/assets/2177532/059c5c9d-b844-467c-9406-b7f7427d1750)
![2](https://github.com/hrydgard/ppsspp/assets/2177532/f00398e7-b89b-49f6-9594-aadf7f1a454a)
![3](https://github.com/hrydgard/ppsspp/assets/2177532/e62d6576-4ae4-4a91-97d8-65ebe24de36e)
![4](https://github.com/hrydgard/ppsspp/assets/2177532/2de914ea-54a7-4bd8-8227-2ef5f0501e8e)
![5](https://github.com/hrydgard/ppsspp/assets/2177532/bfc9d59d-e706-412b-b02c-f1b58b6bdae2)
![6](https://github.com/hrydgard/ppsspp/assets/2177532/38545bae-aaba-4cdd-b0ba-e0067ef222f8)
![7](https://github.com/hrydgard/ppsspp/assets/2177532/9bc465e2-6835-4409-8335-7255b15cd7ef)
![8](https://github.com/hrydgard/ppsspp/assets/2177532/8512cbe5-28ca-410c-9e76-b54a348d4d48)
![9](https://github.com/hrydgard/ppsspp/assets/2177532/f9b20eeb-ea93-4f42-a37e-944c11c52a15)
![10](https://github.com/hrydgard/ppsspp/assets/2177532/fe7ddcce-d589-410b-aa0e-f4ee0dccddc8)
![11](https://github.com/hrydgard/ppsspp/assets/2177532/8f9dd861-ba2a-4043-9d9e-f9b05baf26fe)

**Comment by hrydgard** [comment]
Hm, interesting crash. numBytes for the index buffer space allocation looks way of, like it's gone negative somehow..

**Comment by hrydgard** [comment]
Ah, we will end up with a negative index count if a triangle strip is drawn with too few vertices, due to the `	int numTris = numVerts - 2;` calculation in IndexGenerator::AddStrip, and the following `	inds_ += numTris * 3;
`. We're gonna have to protect against that.

**Comment by sum2012** [comment]
Yes fixed the crash v1.16.6-263-g157fabf91. 
@forz0i please test v1.16.6-263-g157fabf91 or newer version in https://buildbot.orphis.net/ppsspp/index.php

**Comment by sum2012** [comment]
@forz0i v1.16.6-341-g4d7f00f96  have merged fix for crash in-game. Please comment with you have another problem. We will re-opening the issue
