### ISSUE TITLE
Custom texture

### ISSUE THREAD

**Issue by Gelo021** [hrydgard/ppsspp#18275]
Hello again @hrydgard i just notice that the customtexture is not functioning properly like not all the texture are loaded heres the vid 

https://github.com/hrydgard/ppsspp/assets/67460268/23969b46-623e-4bdc-a7c8-56182c10e5bc

 Please fix

**Comment by LunaMoo** [comment]
In some cases a word can mean more than video, can't even tell what textures you mean, nor whenever that texture actually is a part of texture pack you're using. If I recall toukiden character texture can be colored(might confuse it with MH), so if you mean that, texture pack creator probably didn't include replacement for it.

**Comment by Gelo021** [comment]
> In some cases a word can mean more than video, can't even tell what textures you mean, nor whenever that texture actually is a part of texture pack you're using. If I recall toukiden character texture can be colored(might confuse it with MH), so if you mean that, texture pack creator probably didn't include replacement for it.

U mean even 1gb of texture file wont replce just texture, u can clearly see at the viideo from the start like if u spam the replace texture, it wont load the entire texture like font is missing some furnitures, even the rag si missing i've downloaded the full pack btw 😥

**Comment by Gelo021** [comment]
![Screenshot_2023-10-01-09-34-19-40_2f85358b2198d26f8aca533d68bee793](https://github.com/hrydgard/ppsspp/assets/67460268/a7c4da08-4d1a-43ee-9d1d-a2245d79d8c8)

Like this

**Comment by LunaMoo** [comment]
1gb isn't really much for a quality texture pack to include all textures. If you're just the end user, you should ask the texture pack creator and if there's an actual issue he'll be able to investigate it better. There are cases where textures can't be easily replaced due to how PSP games work and it might require more work from the creator of that texture pack.
