### ISSUE TITLE
Mouse on Android 

### ISSUE THREAD

**Issue by Merljn777** [hrydgard/ppsspp#18288]
Hi, if someone could tell me how to use mouse on Android. Which part of the code do I have to change, and how to. Thanks

**Comment by hrydgard** [comment]
What's the problem? I just paired a Bluetooth mouse to my Android phone, and it worked just fine. You don't need to change any code.

**Comment by Merljn777** [comment]
Hi. The problem is probably because i use Ppsspp from playstore, i connect bluetooth mouse on my phone, launch the game then check keys settings, can't find the option to use mouse... 
Thanks for your support

**Comment by hrydgard** [comment]
Oh, no, there's not really any special support for mapping the mouse as an input, you can navigate the menu though.

PSP games don't generally have mouse control anyway, so I'm not really convinced that it makes a lot of sense to build some special support for this.. Do you imagine that relative mouse movements should be routed to the analog stick, for example?

**Comment by iota97** [comment]
We do have mouse support for both Windows and SDL, don't we? Should probably just add Android to the same path somehow.

**Comment by hrydgard** [comment]
True but I have no idea if it actually works, I've never used it :D  But yeah, if there are some simple blocks we can remove, we can of cousre do that.

**Comment by Merljn777** [comment]
Hi. For FPS players from computer (CS 1.6) like me, the mouse to control is the best. Can I do something to help?

**Comment by fp64** [comment]
One thing that annoyed me while playing "Phantasy Star Portable 2 Infinity" is how inconvenient it is to control movement+camera with keyboard only (or maybe I'm just bad at it).
So, I tried keyboard+mouse just now, and it seems... usable? Probably better, after some practice.
Note, that this game is weird in that movement is analog, and camera is D-pad, so I mapped mouse to D-pad. The games that have it the other way around are probably better off.
It might be even better with a 4-button mouse.
The default mouse sensitiviy seems too high: the lowset positive value UI can display is "0.01", which feels *ok* - strange for something on edge of the range.

**Comment by LunaMoo** [comment]
> (...)I mapped mouse to D-pad.(...) The default mouse sensitiviy seems too high: the lowset positive value UI can display is "0.01", which feels _ok_ - strange for something on edge of the range.

 How ok it feels will widely depend on your actual mouse, but mapping analog input to a digital one just doesn't translate well and wasn't even made with that in mind, through you can also change smoothing. To be fair most PSP games doesn't have analog support even when they map controls to thumbstick(and even if they use it in analog mode so it's nothing that can be detected), works nicer for games patched to support right analog stick with an actual range instead of 0/1.

**Comment by fp64** [comment]
Yes, I'm kind of surprised it works as well as it does (not great, mind you, but workable), in this usecase.
Still this is a data point in favor of "mapping mouse is not completely useless".

**Comment by LunaMoo** [comment]
If/when PPSSPP get's some scripting system integrated to expand cheats/fan made patches, it might become quite easy to just patch games to use real analog range or even extend it to a more native support of various controllers as modifying things like camera speed and similar tends to be easy and bug free in pretty much any game where it seems useful, but requires writing long assembly functions full of basic math that could be replaced by one-liners in any high level language.

**Comment by Merljn777** [comment]
Hi, I'm happy to see that my post isn't "dead", and I hope this comment will help you : for Metal Gear Solid, or socom, or all FPS (first person shooter) games, if we could aim with mouse the pleasure to play would be great! I don't have computer, so if you know how I could do let me know, otherwise i'll wait for the next PPSSPP update on playstore. Best regards, and thanks.

**Comment by Merljn777** [comment]
Could someone explain me how to code it by myself or is it forbidden because of copyrights or something? Thanks. My deep intention is also to find a way to completly change control systems in games, just said for good ears :)

**Comment by hrydgard** [comment]
Thanks for the reminder, went ahead and implemented mouse support, identical to what we have on Windows. Had to change the mouse smoothing algorithm slightly though to make it sharable between the platforms (previously it was running on a polling thread that we only use on Windows).

**Comment by hrydgard** [comment]
This is now done - please try it out and let me know how it works for you.
