### ISSUE TITLE
Another Harvest Moon misplacement bug

### ISSUE THREAD

**Issue by justafella** [hrydgard/ppsspp#18287]
### Game or games this happens in

ULUS-10458 - Harvest Moon: Hero of Leaf Valley

### What area of the game / PPSSPP

Whenever I finish horse training races, main character is misplaced over the fence at Starling Ranch. You can still move until you reach the area exit, and then everything comes back to normal. Changing CPU Core doesn't fix this issue. This happens since I can remember using the emulator, so it is very likely to have never been a version where this doesn't happens. Here is a save state right after I won a training race:
[PPSSPP_STATE.zip](https://github.com/hrydgard/ppsspp/files/12782511/PPSSPP_STATE.zip)

### What should happen

I haven't checked what should happen in real hardware yet, but I'm pretty sure main character shouldn't be wandering over seas.

### Platform

Android

### Mobile phone model or graphics card

Redmi 9 

### PPSSPP version affected

1.16.5-83

### Last working version

None

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by IrfanH495** [comment]
As far as I remember, the Europa version doesn't experience this.
https://gamefaqs.gamespot.com/boards/955342-harvest-moon-hero-of-leaf-valley/54716008?page=1

**Comment by justafella** [comment]
> As far as I remember, the Europa version doesn't experience this. https://gamefaqs.gamespot.com/boards/955342-harvest-moon-hero-of-leaf-valley/54716008?page=1

As far as I can tell then it is supposed to be like that. Nothing wrong with emulation, looks like it the game was released with those giltches. I'll close this issue.

**Comment by justafella** [comment]
I'm reopening to say that enabling Simulate UMD Delays fixes it (and probably everything else mentioned on the forum link). I'll leave it open in case of devs want to add something to the discussion .

**Comment by hrydgard** [comment]
We could add it to [ForceUMDDelay] in compat.ini, seems like a valid use case. 

The possibly affected IDs seems to be only ULUS-10458 ?

**Comment by IrfanH495** [comment]
Japanese version also experienced, ULJS00188
![Screenshot_20231002-232154_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/58de6afd-8e37-42fa-babb-43e4cd1b4b24)
@justafella how many fps do you get when training.?

**Comment by hrydgard** [comment]
Alright. Wanna do a PR adding it to compat.ini or should I?

**Comment by IrfanH495** [comment]
I don't have save data for the European version, in GameFaqs the save data contents are changed for the USA.

**Comment by hrydgard** [comment]
We're not gonna need save data to investigate this one, no worries.

**Comment by IrfanH495** [comment]
Europe is experiencing it too🤔🤔🤔,. ULES01489 
![Screenshot_20231002-235851_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/cde08cd2-d727-47d0-b621-b889206ec20c)

**Comment by justafella** [comment]
> Alright. Wanna do a PR adding it to compat.ini or should I? Does the PSN version have another ID?

I don't know how to do a PR. About the IDs, they are the same for US UMD dump and PSN versions. This probably means the other regions ID ARE same for UMD dump and PSN too.

**Comment by hrydgard** [comment]
compat.ini update submitted, sorry I forgot about it for a while.
