### ISSUE TITLE
How to Link external libraries

### ISSUE THREAD

**Issue by FtxDev** [hrydgard/ppsspp#18285]
### Game or games this happens in

---

### What area of the game / PPSSPP

target_link_libraries(native-lib ${external-lib} ${lib})
In 'native-lib' which native lib should be replaced?

### What should happen

When I use ppsspp_jni all jni files are getting removed while target_link_libraries(ppsspp_jni ${external-lib} ${lib})

### Platform

Android

### Mobile phone model or graphics card

No

### PPSSPP version affected

V1.15.4

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
What are you trying to do?  From your issues, it seems like you are planning to create a fork of PPSSPP.  Are you planning to correctly and steadfastly adhere to all the terms of the GPL license as is required for such a project?  Where are you releasing the source code you're required to release?

-[Unknown]

**Comment by FtxDev** [comment]
Thanks for jumping in! Could you share a bit more detail about your thoughts on the native external library?  target_link_libraries(ppsspp_jni ${external-lib} ${lib}) what should replaced ppsspp_jni

**Comment by FtxDev** [comment]
Yeah! That's correct
