### ISSUE TITLE
Manhunt 2 brightness issue

### ISSUE THREAD

**Issue by KINGJIN2008** [hrydgard/ppsspp#18295]
### Game or games this happens in

ULUS-10280

### What area of the game

After new game

### What happens

the game become extremely bright in both cutscene and gameplay(i didn't take cutscene screenshots), also the brightness setup in settings is not working
![Screenshot_2023-10-03-16-58-42-286_org ppsspp ppsspp](https://github.com/hrydgard/ppsspp/assets/119515989/5c285147-2132-4432-9f27-5da37d96f29c)
![Screenshot_2023-10-03-17-00-19-051_org ppsspp ppsspp](https://github.com/hrydgard/ppsspp/assets/119515989/a2d80d83-b246-40b4-b758-5fc0daed1080)
![Screenshot_2023-10-03-17-03-08-468_org ppsspp ppsspp](https://github.com/hrydgard/ppsspp/assets/119515989/28210550-9548-40df-af71-19c640396785)
![Screenshot_2023-10-03-17-03-28-015_org ppsspp ppsspp](https://github.com/hrydgard/ppsspp/assets/119515989/dcb52b48-94ab-4405-bc31-9c1e24b9ccd7)

### What should happen

the game should look like this, i used an early cwcheat by LunaMoo.
![Screenshot_2023-10-03-17-06-09-306_org ppsspp ppsspp](https://github.com/hrydgard/ppsspp/assets/119515989/a4ca8d13-4445-439a-adce-a080a7d12da5)
![Screenshot_2023-10-03-17-01-16-375_org ppsspp ppsspp](https://github.com/hrydgard/ppsspp/assets/119515989/0bde5f8b-9ed4-4bda-b082-b5201a1479a8)
![Screenshot_2023-10-03-17-02-32-996_org ppsspp ppsspp](https://github.com/hrydgard/ppsspp/assets/119515989/e651ac54-1046-432c-90ef-d6527b34a4e0)
![Screenshot_2023-10-03-17-01-20-818_org ppsspp ppsspp](https://github.com/hrydgard/ppsspp/assets/119515989/40f0a935-3b90-4381-91be-efaedbda2925)

### Platform

Android

### Mobile phone model or graphics card

Redmi 10X 4G

### PPSSPP version affected

v1.16.5

### Graphics backend (3D API)

Vulkan

### Checklist

- [x] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
It's possible that this was fixed by #18304 

Let me know, if not I'll check on some phones and see if I can reproduce.

**Comment by hrydgard** [comment]
@KINGJIN2008 did you already check that it works? When you close issues, please confirm in text.

**Comment by KINGJIN2008** [comment]
> @KINGJIN2008你已经检查过它是否有效吗？当您关闭问题时，请以文字形式确认。

welp, i know nothing about coding so i don't know how to test it, but i believe it's fixed, notice my edited comment in the other thread

**Comment by hrydgard** [comment]
Oh I see, but there was a real issue over in #18300  even with all the cheats turned off. You'll find that color precision will be a bit better in the upcoming builds (less banding).

**Comment by KINGJIN2008** [comment]
> Oh I see, but there was a real issue over in #18300 even with all the cheats turned off. You'll find that color precision will be a bit better in the upcoming builds (less banding).

thanks for your hard work, i always wanted to play mh2 without bugs
