### ISSUE TITLE
another Manhunt 2 issue - color

### ISSUE THREAD

**Issue by KINGJIN2008** [hrydgard/ppsspp#18300]
### Game or games this happens in

ULUS-10280

### What area of the game

After new game

### What happens

the psp ver of manhunt 2 lacks of color
![Screenshot_2023-10-03-22-12-05-137_org ppsspp ppsspp](https://github.com/hrydgard/ppsspp/assets/119515989/81825598-f821-4a10-a0a0-be4b5098ca68)
 and the game looks pretty bad, you can notice in the screenshot

### What should happen

LunaMoo made a cwcheat to fix the color and that's what it supposed to look like
![Screenshot_2023-10-03-22-12-54-511_org ppsspp ppsspp](https://github.com/hrydgard/ppsspp/assets/119515989/6ce93e4d-598a-4ce6-aaf5-fcac712431bf)
![Screenshot_2023-10-03-22-12-13-631_org ppsspp ppsspp](https://github.com/hrydgard/ppsspp/assets/119515989/cadf5fb8-3499-4f45-bb7a-18d775f73cea)

### Platform

Android

### Mobile phone model or graphics card

Redmi 10X 4G

### PPSSPP version affected

v1.16.5

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
I guess that it's doing a color ramp lookup from a 16-bit image, just like Test Drive. So it seems like CanUseSmoothDepal might need some updates to its logic...

Can we get a GE frame capture please?

**Comment by hrydgard** [comment]
The technique can be seen in the dump though. It processes the screen in strips, r g an b separately. It uses three ramps for R G and B packed in the same palette, which our ramp detector rejects:

![image](https://github.com/hrydgard/ppsspp/assets/130929/c00acde4-25d4-474e-ac25-9c82f5c61936)

I think we can just add some extra logic here to make this type of texture pass the check..

**Comment by hrydgard** [comment]
With #18304, the restore-colors cheat will no longer be needed.

**Comment by KINGJIN2008** [comment]
> 嗯，帧转储似乎显示了一个非常暗的暂停屏幕？有更像上面的屏幕截图的东西吗？

this issue's pretty weird, sometimes it appears while sometimes not, i guess it's because im using the 'destroy brightness' hack, ill give you one with that issue later

**Comment by KINGJIN2008** [comment]
![Screenshot_2023-10-04-14-16-00-419_org ppsspp ppsspp](https://github.com/hrydgard/ppsspp/assets/119515989/e24c2091-2ca3-4783-b0b3-8fa9f8c3d29f)

**Comment by hrydgard** [comment]
New build with the fix is now available, let me know how it works for you: https://buildbot.orphis.net/ppsspp/

**Comment by KINGJIN2008** [comment]
> New build with the fix is now available, let me know how it works for you: https://buildbot.orphis.net/ppsspp/

it's working! the game now looks pretty beautiful, without any graphics issue
![Screenshot_2023-10-05-05-46-22-492_org ppsspp ppsspp](https://github.com/hrydgard/ppsspp/assets/119515989/214c4ffa-f272-4a17-9755-e111cb10f7f5)
