### ISSUE TITLE
Naruto UH3 got bug with software skinning

### ISSUE THREAD

**Issue by Gelo021** [hrydgard/ppsspp#18318]
@hrydgard  heres the vid
https://github.com/hrydgard/ppsspp/assets/67460268/0a7af8f0-3d74-4114-9881-71d18925d03b

**Comment by hrydgard** [comment]
Likely related to a similar issue in Monster Hunter I'm looking at.

That one I just confirmed broke in 4d952500521c7d2d2bb4c002cad9f20df0d672d5.

That one can be reproduced with these frame dumps:

[mhrepro.zip](https://github.com/hrydgard/ppsspp/files/12840643/mhrepro.zip)

![image](https://github.com/hrydgard/ppsspp/assets/130929/e9599dc6-77af-4acf-bb19-5fbda620201e)
