### ISSUE TITLE
"Rewrite" (visual novel game) shows black screen

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#18312]
Reported by ヒリツキ on discord.

![image](https://github.com/hrydgard/ppsspp/assets/130929/d4ee13fe-81f4-45a6-8f77-810e151a0a8d)
![image](https://github.com/hrydgard/ppsspp/assets/130929/daad3d32-21a4-4231-8beb-2999c25ebcd9)

**Comment by sum2012** [comment]
I test no problem
![1](https://github.com/hrydgard/ppsspp/assets/2177532/ecdd1c66-b133-46d4-8361-07a8ae674432)
![2](https://github.com/hrydgard/ppsspp/assets/2177532/a40c4191-4d26-4239-a9c0-f13103bb9282)

**Comment by sum2012** [comment]
It is missing this switch umd message (after data install in disc 1 ) in the new version
![1](https://github.com/hrydgard/ppsspp/assets/2177532/6d774d01-1b39-4e3a-ad6f-5cd95bd90774)

**Comment by hrydgard** [comment]
Hm, that's weird. Does it still continue playing properly?

**Comment by sum2012** [comment]
Yes

**Comment by sum2012** [comment]
I get a covid-19 virus,I don't update until I recover

**Comment by Sukotto-1999** [comment]
> It is missing this switch umd message (after data install in disc 1 ) in the new version ![1](https://user-images.githubusercontent.com/2177532/273204582-6d774d01-1b39-4e3a-ad6f-5cd95bd90774.jpg)

To make the game boot properly, after data install, when prompt appears, switch the game to Disc 2, and then remove memory stick, once the game boots up, insert back the memory stick. Worked for me on PPSSPP.

**Comment by sum2012** [comment]
From officials old build, 
Last good v1.13.2
First bad v1.14 
maybe some commit of
https://github.com/hrydgard/ppsspp/commits/v1.14/Core/Dialog/PSPGamedataInstallDialog.cpp

**Comment by sum2012** [comment]
I forget to post log  (officials old build do not include Infolog.bat)
v1.13.2 good log
https://gist.github.com/sum2012/98cf2508e9a514ff73f861ed0aea58b2
v1.16.6-222-g1e6142d99 
https://gist.github.com/sum2012/107e633958029380c9e9a9721e241a5d
Main difficult
38:44:128 user_main    D[SCEUTIL]: HLE\sceUtility.cpp:764 3=sceUtilityGamedataInstallGetStatus()
38:44:128 user_main    D[SCEUTIL]: HLE\sceUtility.cpp:745 00000000=sceUtilityGamedataInstallShutdownStart()
38:44:145 user_main    D[SCEUTIL]: HLE\sceUtility.cpp:764 4=sceUtilityGamedataInstallGetStatus()
38:44:163 user_main    D[SCEUTIL]: HLE\sceUtility.cpp:764 0=sceUtilityGamedataInstallGetStatus()

v1.16.6-222-g1e6142d99 
35:14:785 user_main    D[SCEUTIL]: HLE\sceUtility.cpp:805 3=sceUtilityGamedataInstallGetStatus()
35:14:785 user_main    D[SCEUTIL]: HLE\sceUtility.cpp:785 00000000=sceUtilityGamedataInstallShutdownStart()
35:14:801 user_main    D[SCEUTIL]: HLE\sceUtility.cpp:800 80110005=sceUtilityGamedataInstallGetStatus(): wrong dialog type

It is missing 4=sceUtilityGamedataInstallGetStatus()

**Comment by sum2012** [comment]
As I expect,
Last good v1.13.2-1033-gf0afc9724
First bad v1.13.2-1032-gf2beafe76
It mean https://github.com/hrydgard/ppsspp/commit/f0afc97247a3dd69af86711686516ced891c0cce (#16051)
@unknownbrackets ,please help to solve

**Comment by sum2012** [comment]
#18363 fixed
Thanks @unknownbrackets
