### ISSUE TITLE
Changing to vulkan crash the emulator

### ISSUE THREAD

**Issue by DmdHoH000** [hrydgard/ppsspp#18327]
### Game or games this happens in

All games

### What area of the game / PPSSPP

When i try to change from opengl to vulkan the emulator crash

### What should happen

The emulator shouldn't crash when changing

### Platform

Android

### Mobile phone model or graphics card

Lg k40s

### PPSSPP version affected

v1.16.5-161-g5a29ebfe6 to v1.16.5-153-g43cdb88ac

### Last working version

v1.16.5-146-g5bb1db557

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
#18333 might fix this, let's see.

**Comment by DmdHoH000** [comment]
I tested and still crash

**Comment by hrydgard** [comment]
Well I haven't merged the change yet. I'll post here when builds are ready.

**Comment by DmdHoH000** [comment]
Sorry for the mistake

**Comment by DmdHoH000** [comment]
Issue fixed thanks
