### ISSUE TITLE
PPSSPP Homebrew Store button cause crash in iOS

### ISSUE THREAD

**Issue by Halo-Michael** [hrydgard/ppsspp#18322]
### Game or games this happens in

-

### What area of the game / PPSSPP

-

### What should happen

Get Store in

### Platform

iOS

### Mobile phone model or graphics card

iPhone7 / SE 2

### PPSSPP version affected

v1.16.5-153-g43cdb88ac

### Graphics backend (3D API)

Other

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by Halo-Michael** [comment]
![DEFF73CA-AA4D-406A-B609-D2C08FB98A24](https://github.com/hrydgard/ppsspp/assets/45062120/303e2a44-6bdf-41d9-b439-bc53268d86de)

**Comment by hrydgard** [comment]
I think I'm gonna turn off the HTTPS support on iOS, should resolve this issue.

**Comment by Halo-Michael** [comment]
> I think I'm gonna turn off the HTTPS support on iOS, should resolve this issue.

Not help, but it do only happened on iOS

**Comment by Halo-Michael** [comment]
@hrydgard Turn off HTTPS support do works, but MACOSX flag of cmake include iOS infact
