### ISSUE TITLE
Switching from Vulkan to OpenGL/D3D crashed(?) after using SaveState

### ISSUE THREAD

**Issue by ANR2ME** [hrydgard/ppsspp#18345]
### Game or games this happens in

Any games

### What area of the game / PPSSPP

How to reproduce it:
1. Run any game using Vulkan (tested with MGS:PW, Crazy Taxi, DBZ SB2, LittleBigPlanet)
2. Load SaveState 
3. Exit to Menu
4. Change GPU backend from Vulkan to OpenGL/D3D11/D3D9, it supposed to restart PPSSPP but didn't, probably due to a crash.

PS: It also happened even when it failed to load save state because you don't have a save state.
PPS: I can't reproduce this using Debug build, so i'm not sure whether it really crashed or just failed to restart PPSSPP somehow.

### What should happen

Should restart PPSSPP just like switching from OpenGL/D3D to Vulkan

### Platform

Windows

### Mobile phone model or graphics card

Geforce MX150

### PPSSPP version affected

v1.16.5-207-ge26bf611e

### Last working version

not sure, i couldn't run any game using Vulkan on v1.15.4 after using the latest dev build (even after deleting .vkshadercache)

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Hm, that's a weird one. I'll look into it.

**Comment by hrydgard** [comment]
Tried a bunch but couldn't reproduce. The only odd behavior I saw was that sometimes the restarted PPSSPP spawned below other windows, so it looked hidden. Which isn't good, no, but at least it started.

**Comment by ANR2ME** [comment]
Apparently i couldn't reproduce it using the builds i built my self too, but reproducible when using builds from build bot.

**Comment by ANR2ME** [comment]
Hmm.. apparently i can't reproduce this when using my Intel UHD 620 GPU, so i guess this is driver issue
