### ISSUE TITLE
Force install Texture Packs in android/data/

### ISSUE THREAD

**Issue by CristobalManga** [hrydgard/ppsspp#18342]
### What should happen

This will sound like a dictator, but it is possible that Android users, when clicking on the "load" section when installing a texture pack, will force these packs to be moved to the android/data/ path. regardless of whether the user chose to install the PPSSPP data on SD or root storage.

As you know, any texture pack that is compressed or uncompressed will have stuttering and even make the game unplayable due to having the pack in the root of the cell phone or MicroSD. For the simple reason that Android decided to limit storage or protect it.

But in the android/data/ path it reads the files at maximum speed with millisecond stutters.

These will benefit users who are unaware of the subject and have PPSSPP in root and then wonder why their game is slow.

### Who would this benefit

All

### Platform (if relevant)

Android

### Games this would be useful in

All

### Other emulators or software with a similar feature

aaaaaaaaaaaa

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by ANR2ME** [comment]
I think the reason of the slow file access is due to scoped storage, where accessing a single zip file will be much faster than accessing many smaller files.

**Comment by CristobalManga** [comment]
> Colaborador

Yes, but for some reason even though the pack is in a zip, Android reads it slowly when this zip is in the root of the storage, but in Android/Data it does not happen.

So the option would be that when installing the pack, it gives a notice where the user wants to install the texture pack, but warning them that in SD or Root storage, it will be slow.

**Comment by unknownbrackets** [comment]
A problem is that some users may have limited space there.  Definitely forcing it without an option seems bad for this reason.  Maybe suggesting installing it in local storage wouldn't be bad.

The performance problems you describe are probably device specific; for most devices, once you get a file descriptor, accessing it is plenty fast.  At least when I initially added zip support, I intentionally made sure it didn't reopen the zip for this reason.

-[Unknown]

**Comment by CristobalManga** [comment]
What you just said is totally true, I just checked it on another device with Android 11, the previous one had Android 12.
With Android 11 on Pixel 2, there is no stuttering when the HD texture pack is in the root storage.
