### ISSUE TITLE
add "none" to button style: shape

### ISSUE THREAD

**Issue by AlkasaZ** [hrydgard/ppsspp#18356]

**Comment by ANR2ME** [comment]
If you mean the demo cube.iso that came with PPSSPP, it's working fine for me.
![image](https://github.com/hrydgard/ppsspp/assets/7974720/9d22251f-9380-4d24-89ae-15a735d544b2)

**Comment by hrydgard** [comment]
What are you talking about with regards to "none" and the button style? is that something on the website? PPSSPP doesn't use CSS internally.

**Comment by ANR2ME** [comment]
If you want to use "none" to hide the button, you can use the "Visible" checkbox to do that isn't?

**Comment by hrydgard** [comment]
Thanks, now I understand what you mean. Yeah, I guess that's a legitimate feature request and does seem like it can be made to work well.

What should they look like in the "pressed" state? Some kind of glow so you can see that you press them even if the finger is covering the display?
