### ISSUE TITLE
Using the debugger before loading a game causes uncaught exceptions and more

### ISSUE THREAD

**Issue by Nemoumbra** [hrydgard/ppsspp#18383]
### Game or games this happens in

Not game-specific

### What area of the game / PPSSPP

Before any game is loaded into PPSSPP, its UI for the debugger is still somewhat usable.
![image](https://github.com/hrydgard/ppsspp/assets/62447396/ff62d91d-9aa3-4ab2-a9c3-e1da84e062aa)

Using any of the "Rename/Add/Remove function" options kills PPSSPP because the symbol map is not initialized yet (uncaught expection `this was nullptr`).
The `Edit symbols...` window also doesn't account for that and just forwards the order to `MIPSAnalyst::ScanForFunctions(...)` which fails with read access violation. The action to remove the symbols fails because of the symbol map again.

`Assemble opcode` shows this: 
![image](https://github.com/hrydgard/ppsspp/assets/62447396/949d3eeb-7060-4406-b5fe-8a79314fc914)

This makes me believe PPSSPP is very confused about what's going on.
I've also managed to crash PPSSPP by using the GE Debugger (`Copy instruction (hex/disasm)`, `Jump to cursor`, `Set stall`, `Go to address...`).

### What should happen

The simple solution would be to carefully disable the context menus in the GE and Disasm views. Of course, it doesn't have to be done this way, but it *seems* logical to me. If we can't do that, it means we'll have to carefully check the game's state and display an error or something.

### Platform

Windows

### Mobile phone model or graphics card

AMD Radeon(TM) Graphics

### PPSSPP version affected

Self-built version (one of the lastest)

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
I think disabling the context menus is indeed the way to go.

**Comment by Nemoumbra** [comment]
Then I guess this is where checks need to be inserted:  https://github.com/hrydgard/ppsspp/blob/master/Windows/Debugger/CtrlDisAsmView.cpp#L956
https://github.com/hrydgard/ppsspp/blob/master/Windows/GEDebugger/CtrlDisplayListView.cpp#L311

**Comment by Nemoumbra** [comment]
Well, what checks do we want here? What's the API for checking if there's a game loaded?
