### ISSUE TITLE
texture replacement filtering mode not working

### ISSUE THREAD

**Issue by Mr-Beacon00** [hrydgard/ppsspp#18398]
### Game or games this happens in

NPJH-50045

### What area of the game / PPSSPP

I add a line in textures.ini's filtering section. weapon icon should be "nearest" filtering, but it still linear, 
filtering doesn't work anymore after 1.15
I also tried v1.16.6-280-g6d063ce3e. it still not working, 
texture replace is okay, just filtering not working.
![ini](https://github.com/hrydgard/ppsspp/assets/73895438/5c896c50-dc0a-406d-be0b-200d29251c33)
![1](https://github.com/hrydgard/ppsspp/assets/73895438/53253ae9-6186-4d7a-a3cc-abc0ddcb18c2)

### What should happen

this is nearest icon
![2](https://github.com/hrydgard/ppsspp/assets/73895438/e8957650-5144-4ef7-8434-150256fe0ae2)

### Platform

Windows

### Mobile phone model or graphics card

NVIDIA GeForce GTX 1650

### PPSSPP version affected

v1.16.6

### Last working version

v1.14.4

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by Schrottvogel** [comment]
Same here with 1.16.6. Installed HD Textures are ignored on Windows 11. 
Everything is fine on MacOS.
Tested on Win11 with an old 1.10.3 version works fine.

**Comment by hrydgard** [comment]
@Schrottvogel This issue is not about ignored textures, just ignored filtering options.

Anyway, I'm gonna fix this one, and there have been some other fixes lately, you might want to try the newest builds: https://buildbot.orphis.net/ppsspp/

**Comment by hrydgard** [comment]
Oh I see, this has stopped working unless you actually replace the texture, you can't change just the filtering by hash anymore.

I'll fix that, as that's quite a useful feature that I missed testing when refactoring the texture cache a while ago.

**Comment by Schrottvogel** [comment]
Tested with V1.16.6-514 works perfect.

**Comment by hrydgard** [comment]
Might later make it so it works even without an entry in [hashes]. But for now, this at least fixes the regression. Thanks for testing!
