### ISSUE TITLE
Tilt control deadzone + circular low end radius bug

### ISSUE THREAD

**Issue by rankcody** [hrydgard/ppsspp#18399]
### Game or games this happens in

None

### What area of the game / PPSSPP

On Android, the analog stick tilt controls are a bit buggy. I noticed three bugs.

The bug occurs when both a deadzone radius value and circular low end radius is set. Whenever the stick is in the deadzone radius, it shoots all the way to the top left corner.

I used the following settings:
Tilt input type: Analog
Deadzone radius: 0.20
Low end radius: 0.00
Circular low end radius: On
Tilt sensitivity along X axis: 70
Tilt sensitivity along X axis: 70
Invert tilt along X axis: Off
Invert tilt along X axis: Off

I also noticed a different bug. Start from the above settings, then set the low end radius value. Then, turn off circular low end radius. The stick's resting position will shift slightly up and to the right, seemingly proportional to how high you set the low end radius. This causes drift since the stick's resting position is off center.

I used the following settings:
Tilt input type: Analog
Deadzone radius: 0.20
Low end radius: 0.20
Circular low end radius: Off
Tilt sensitivity along X axis: 70
Tilt sensitivity along X axis: 70
Invert tilt along X axis: Off
Invert tilt along X axis: Off

Third bug is a minor bug, you can't use the +/- buttons to adjust the low end radius in the popup. Doing so simply sets the value to n/an.

### What should happen

When inside the deadzone, the stick should remain at rest.

Turning off circular low end radius should not alter the stick's resting position.

The +/- in the low end radius popup dialog box should allow one to adjust the value instead of returning n/an.

### Platform

Android

### Mobile phone model or graphics card

1.300.2589 (0052ca1d)

### PPSSPP version affected

v.1.16.6-283-g949dc97e3

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Thanks for your detailed report, I'll get these fixed fairly soon.

**Comment by Gamernumber1** [comment]
> Thanks for your detailed report, I'll get these fixed fairly soon.

I don't know why, but in previous versions the stick is managed better, in the last build it is very crooked and like some kind of inversion

**Comment by hrydgard** [comment]
For me the old type of tilt control (1.14 and earlier) was harder to calibrate and felt worse. You are using the calibrate button correctly, right? (Hold phone at your preferred neutral angle and click calibrate)
