### ISSUE TITLE
 Xinput triggers mapped to analog sticks could pollute internal analog sticks state

### ISSUE THREAD

**Issue by Kethen** [hrydgard/ppsspp#18404]
### Game or games this happens in

all games, if triggers were mapped under xinput

### What area of the game / PPSSPP

It seems that Xinput devices would not send trigger values unless it's over XINPUT_GAMEPAD_TRIGGER_THRESHOLD

https://github.com/hrydgard/ppsspp/blob/2036f1c36a4023c2e4525002a3817f0d93a4ab83/Windows/XinputDevice.cpp#L240

So it never sends anything under XINPUT_GAMEPAD_TRIGGER_THRESHOLD after a higher value was sent, leaving a stuck analog value > `30.f/255.0f ~ 0.1176` on internal state

The stuck value can then further affect analog normalizing on control mapper

### What should happen

Idle trigger should not maintain an analog value

Maintaining a value could also be the cause of #16643

Perhaps when XINPUT_GAMEPAD_TRIGGER_THRESHOLD is not met, it should gradually send values until 0 so that control mapper can also drop back to under deadzone? Or maybe send `clamp((x - 30.0f)/(255.0f - 30.0f), 0.0, 1.0)` as trigger input and skip the check

### Platform

Windows

### Mobile phone model or graphics card

Not relevant

### PPSSPP version affected

v1.16.6 release, v1.16.6-290-g2036f1c36

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.

**Comment by Kethen** [comment]
Since https://github.com/hrydgard/ppsspp/commit/633a6f612b44b36e12ba34c7ded3147897d7e3af, it might make sense to just skip the deadzone checking for triggers as well

**Comment by hrydgard** [comment]
Fixed by #18407.
