### ISSUE TITLE
MatchingHandler: Callback Failed to Return within 250ms

### ISSUE THREAD

**Issue by Mr-Lars** [hrydgard/ppsspp#18412]
### Game or games this happens in

Patapon 3 

### What area of the game / PPSSPP

Whenever a friend of mine joins a lobby, another friend (who has the issue) crashes instantly.
We have looked at the logs and we believe it's this error that causes the crash:

50:06:890 user_main    E[SCENET]: HLE\proAdhoc.cpp:978 MatchingHandler: Callback Failed to Return within 250ms!

### What should happen

It shouldn't crash

### Logs

44:05:377 Core\Config.cpp:1642 E[LOADER]: Failed to read C:\Users\RevSt\Downloads\ppsspp_win\memstick/PSP/SYSTEM/controls.ini. Setting controller config to default.
44:06:037 Core\Config.cpp:1284 E[LOADER]: Error saving config - can't read ini 'C:\Users\RevSt\Downloads\ppsspp_win\memstick/PSP/SYSTEM/ppsspp.ini'
44:06:043 Core\Config.cpp:1343 E[LOADER]: Error saving config - can't read ini 'C:\Users\RevSt\Downloads\ppsspp_win\memstick/PSP/SYSTEM/controls.ini'
44:22:042 root         N[BOOT]: UI\EmuScreen.cpp:299 Loading C:/Users/RevSt/Downloads/UCES01422.iso...
44:23:317 user_main    E[FILESYS]: FileSystems\DirectoryFileSystem.cpp:62 DirectoryFileSystem::OpenFile: FAILED, 3 - access = 1
44:23:317 user_main    E[SCEIO]: HLE\sceIo.cpp:2079 00000006=sceIoOpenAsync(ms0:/PSP/SAVEDATA/UCES01422_INSDIR/DATA_MS.BND, 1, 0): file not found
44:23:350 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(148470552)
44:56:099 Thread.cpp   E[ME]: HLE\sceMpeg.cpp:1987 UNIMPL sceMpegAvcInitYCbCr(0947d370, 1, 480, 272, 097e4aa0)
44:56:099 Thread.cpp   E[ME]: HLE\sceMpeg.cpp:1987 UNIMPL sceMpegAvcInitYCbCr(0947d370, 1, 480, 272, 09814850)
44:56:099 Thread.cpp   E[ME]: HLE\sceMpeg.cpp:1987 UNIMPL sceMpegAvcInitYCbCr(0947d370, 1, 480, 272, 09844600)
44:56:099 Thread.cpp   E[ME]: HLE\sceMpeg.cpp:1987 UNIMPL sceMpegAvcInitYCbCr(0947d370, 1, 480, 272, 098743b0)
45:01:957 Thread.cpp   E[ME]: HLE\sceMpeg.cpp:1259 UNIMPL sceMpegAvcDecodeStopYCbCr(0947d370, 09fada7c, 09fada78)
45:01:964 Thread.cpp   E[ME]: HLE\sceMpeg.cpp:1987 UNIMPL sceMpegAvcInitYCbCr(09478050, 1, 480, 272, 097df760)
45:01:964 Thread.cpp   E[ME]: HLE\sceMpeg.cpp:1987 UNIMPL sceMpegAvcInitYCbCr(09478050, 1, 480, 272, 0980f510)
45:01:964 Thread.cpp   E[ME]: HLE\sceMpeg.cpp:1987 UNIMPL sceMpegAvcInitYCbCr(09478050, 1, 480, 272, 0983f2c0)
45:01:964 Thread.cpp   E[ME]: HLE\sceMpeg.cpp:1987 UNIMPL sceMpegAvcInitYCbCr(09478050, 1, 480, 272, 0986f070)
46:57:146 Thread.cpp   E[ME]: HLE\sceMpeg.cpp:1987 UNIMPL sceMpegAvcInitYCbCr(098e7730, 1, 480, 272, 09c4ee60)
46:57:146 Thread.cpp   E[ME]: HLE\sceMpeg.cpp:1987 UNIMPL sceMpegAvcInitYCbCr(098e7730, 1, 480, 272, 09c7ec10)
46:57:146 Thread.cpp   E[ME]: HLE\sceMpeg.cpp:1987 UNIMPL sceMpegAvcInitYCbCr(098e7730, 1, 480, 272, 09cae9c0)
46:57:146 Thread.cpp   E[ME]: HLE\sceMpeg.cpp:1987 UNIMPL sceMpegAvcInitYCbCr(098e7730, 1, 480, 272, 09cde770)
46:59:967 user_main    E[FILESYS]: FileSystems\DirectoryFileSystem.cpp:62 DirectoryFileSystem::OpenFile: FAILED, 3 - access = 1
46:59:967 user_main    E[SCEIO]: HLE\sceIo.cpp:2079 00000006=sceIoOpenAsync(ms0:/PSP/GAME/UCES01422/C1B37181.EDAT, 1073758209, 0): file not found
46:59:969 user_main    E[FILESYS]: FileSystems\DirectoryFileSystem.cpp:62 DirectoryFileSystem::OpenFile: FAILED, 3 - access = 1
46:59:969 user_main    E[SCEIO]: HLE\sceIo.cpp:2079 00000006=sceIoOpenAsync(ms0:/PSP/GAME/UCES01422/B6B44117.EDAT, 1073758209, 0): file not found
46:59:970 user_main    E[FILESYS]: FileSystems\DirectoryFileSystem.cpp:62 DirectoryFileSystem::OpenFile: FAILED, 3 - access = 1
46:59:970 user_main    E[SCEIO]: HLE\sceIo.cpp:2079 00000006=sceIoOpenAsync(ms0:/PSP/GAME/UCES01422/2FBD10AD.EDAT, 1073758209, 0): file not found
46:59:971 user_main    E[FILESYS]: FileSystems\DirectoryFileSystem.cpp:62 DirectoryFileSystem::OpenFile: FAILED, 3 - access = 1
46:59:971 user_main    E[SCEIO]: HLE\sceIo.cpp:2079 00000006=sceIoOpenAsync(ms0:/PSP/GAME/UCES01422/58BA203B.EDAT, 1073758209, 0): file not found
46:59:972 user_main    E[FILESYS]: FileSystems\DirectoryFileSystem.cpp:62 DirectoryFileSystem::OpenFile: FAILED, 3 - access = 1
46:59:972 user_main    E[SCEIO]: HLE\sceIo.cpp:2079 00000006=sceIoOpenAsync(ms0:/PSP/GAME/UCES01422/C6DEB598.EDAT, 1073758209, 0): file not found
46:59:973 user_main    E[FILESYS]: FileSystems\DirectoryFileSystem.cpp:62 DirectoryFileSystem::OpenFile: FAILED, 3 - access = 1
46:59:973 user_main    E[SCEIO]: HLE\sceIo.cpp:2079 00000006=sceIoOpenAsync(ms0:/PSP/GAME/UCES01422/B1D9850E.EDAT, 1073758209, 0): file not found
46:59:974 user_main    E[FILESYS]: FileSystems\DirectoryFileSystem.cpp:62 DirectoryFileSystem::OpenFile: FAILED, 3 - access = 1
46:59:974 user_main    E[SCEIO]: HLE\sceIo.cpp:2079 00000006=sceIoOpenAsync(ms0:/PSP/GAME/UCES01422/28D0D4B4.EDAT, 1073758209, 0): file not found
46:59:974 user_main    E[FILESYS]: FileSystems\DirectoryFileSystem.cpp:62 DirectoryFileSystem::OpenFile: FAILED, 3 - access = 1
46:59:974 user_main    E[SCEIO]: HLE\sceIo.cpp:2079 00000006=sceIoOpenAsync(ms0:/PSP/GAME/UCES01422/5FD7E422.EDAT, 1073758209, 0): file not found
46:59:975 user_main    E[FILESYS]: FileSystems\DirectoryFileSystem.cpp:62 DirectoryFileSystem::OpenFile: FAILED, 3 - access = 1
46:59:975 user_main    E[SCEIO]: HLE\sceIo.cpp:2079 00000006=sceIoOpenAsync(ms0:/PSP/GAME/UCES01422/CF68F9B3.EDAT, 1073758209, 0): file not found
46:59:976 user_main    E[FILESYS]: FileSystems\DirectoryFileSystem.cpp:62 DirectoryFileSystem::OpenFile: FAILED, 3 - access = 1
46:59:976 user_main    E[SCEIO]: HLE\sceIo.cpp:2079 00000006=sceIoOpenAsync(ms0:/PSP/GAME/UCES01422/B86FC925.EDAT, 1073758209, 0): file not found
46:59:977 user_main    E[FILESYS]: FileSystems\DirectoryFileSystem.cpp:62 DirectoryFileSystem::OpenFile: FAILED, 3 - access = 1
46:59:977 user_main    E[SCEIO]: HLE\sceIo.cpp:2079 00000006=sceIoOpenAsync(ms0:/PSP/GAME/UCES01422/77BEEEA7.EDAT, 1073758209, 0): file not found
47:00:500 Thread.cpp   E[ME]: HLE\sceMpeg.cpp:1987 UNIMPL sceMpegAvcInitYCbCr(09574630, 1, 480, 272, 098e1ea0)
47:00:500 Thread.cpp   E[ME]: HLE\sceMpeg.cpp:1987 UNIMPL sceMpegAvcInitYCbCr(09574630, 1, 480, 272, 09911c50)
47:00:500 Thread.cpp   E[ME]: HLE\sceMpeg.cpp:1987 UNIMPL sceMpegAvcInitYCbCr(09574630, 1, 480, 272, 09941a00)
47:00:500 Thread.cpp   E[ME]: HLE\sceMpeg.cpp:1987 UNIMPL sceMpegAvcInitYCbCr(09574630, 1, 480, 272, 099717b0)
47:10:681 Thread.cpp   E[ME]: HLE\sceMpeg.cpp:1259 UNIMPL sceMpegAvcDecodeStopYCbCr(09574630, 09fada7c, 09fada78)
47:26:291 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167765440)
47:26:292 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167765440)
47:26:292 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167765440)
47:26:292 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167765440)
47:26:292 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167765440)
47:26:292 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167765440)
47:26:292 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167765440)
47:26:292 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167765440)
47:26:292 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167765440)
47:26:292 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167765440)
47:26:292 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167765440)
47:26:292 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167765440)
47:26:292 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167765440)
47:26:292 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167765440)
47:26:292 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167765440)
47:26:292 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167765440)
47:26:292 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167765440)
47:26:292 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167765440)
47:26:292 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167765440)
47:26:292 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167765440)
47:26:292 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167765440)
47:26:292 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167765440)
47:26:292 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167765440)
47:26:799 Thread.cpp   E[ME]: HLE\sceMpeg.cpp:1987 UNIMPL sceMpegAvcInitYCbCr(0957bbd0, 1, 480, 272, 098e32a0)
47:26:799 Thread.cpp   E[ME]: HLE\sceMpeg.cpp:1987 UNIMPL sceMpegAvcInitYCbCr(0957bbd0, 1, 480, 272, 09913050)
47:26:799 Thread.cpp   E[ME]: HLE\sceMpeg.cpp:1987 UNIMPL sceMpegAvcInitYCbCr(0957bbd0, 1, 480, 272, 09942e00)
47:26:799 Thread.cpp   E[ME]: HLE\sceMpeg.cpp:1987 UNIMPL sceMpegAvcInitYCbCr(0957bbd0, 1, 480, 272, 099a6110)
47:28:391 Thread.cpp   E[ME]: HLE\sceMpeg.cpp:1259 UNIMPL sceMpegAvcDecodeStopYCbCr(0957bbd0, 09fada7c, 09fada78)
49:21:632 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167769008)
49:21:632 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167769008)
49:21:632 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167769008)
49:21:632 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167769008)
49:21:632 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167769008)
49:21:632 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167769008)
49:21:632 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167769008)
49:21:632 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167769008)
49:21:632 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167769008)
49:21:632 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167769008)
49:21:632 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167769008)
49:21:632 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167769008)
49:21:632 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167769008)
49:21:632 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167769008)
49:21:632 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167769008)
49:21:632 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167769008)
49:21:632 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167769008)
49:21:632 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167769008)
49:21:632 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167769008)
49:21:632 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167769008)
49:21:632 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167769008)
49:21:632 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167769008)
49:21:632 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(167769008)
49:52:080 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10035)
49:52:110 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:52:143 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:52:178 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:52:210 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:52:243 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:52:277 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:52:311 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:52:345 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:52:377 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:52:410 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:52:443 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:52:477 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:52:511 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:52:543 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:52:578 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:52:611 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:52:643 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:52:678 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:52:710 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:52:744 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:52:778 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:52:811 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:52:845 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:52:878 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:52:911 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:52:946 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:52:977 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:53:010 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:53:045 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:53:079 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:53:111 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:53:145 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:53:179 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:53:211 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:53:245 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:53:278 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:53:311 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:53:344 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:53:380 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:53:411 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:53:445 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:53:479 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:53:511 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:53:544 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:53:578 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:53:612 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:53:645 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:53:678 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:53:711 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:53:746 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:53:778 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:53:813 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:53:846 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:53:879 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:53:912 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:53:946 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:53:978 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:54:013 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:54:046 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:54:079 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:54:112 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:54:146 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:54:178 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:54:212 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:54:246 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:54:279 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:54:313 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:54:347 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:54:379 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:54:413 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:54:446 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:54:479 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:54:512 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:54:545 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:54:579 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:54:613 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:54:645 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:54:679 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:54:713 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:54:746 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:54:781 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:54:814 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:54:846 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:54:880 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:54:913 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:54:945 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:54:979 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:55:013 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:55:048 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:55:079 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:55:112 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:55:148 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:55:179 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:55:213 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10037)
49:55:248 user_main    E[SCENET]: HLE\sceNetAdhoc.cpp:1963 sceNetAdhocPtpConnect[1]: Socket Error (10056)
50:49:013 user_main    E[SCENET]: HLE\proAdhoc.cpp:978 MatchingHandler: Callback Failed to Return within 250ms!
50:50:741 user_main    E[SCEKERNEL]: HLE\sceKernelThread.cpp:1229 __KernelGetWaitID ERROR: thread 428
50:50:741 user_main    E[SCEKERNEL]: HLE\sceKernelThread.cpp:1209 __KernelGetWaitValue ERROR: thread 428

### Platform

Windows

### Mobile phone model or graphics card

NVIDIA RTX 3060

### PPSSPP version affected

1.10.3

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Please don't report issues in versions of PPSSPP as old as 1.10.3. 

Try with a newer version, then report the bug. The line number for the problem here, for example, is way off from the current code.

**Comment by Mr-Lars** [comment]
> Please don't report issues in versions of PPSSPP as old as 1.10.3.
> 
> Try with a newer version (1.16.6 or newer), then report the bug. The line number for the problem here, for example, is way off from the current code.

thank you but i didn't ask for this because i am too lazy to upgrade. This is the only version that works for my friend (who is on windows 11). If we could we would've been on 1.16 already

**Comment by hrydgard** [comment]
Again, we do not go back and fix things. 

Instead, report whatever problem makes the new version not work for your friend, so we can fix it.

I'll be super clear: We do not fix bugs in old versions. We fix bugs on the latest code to make new versions.

**Comment by ANR2ME** [comment]
It's an old bug where AdhocMatching's callback was running on any random PSP thread and could cause a crash. On newer version it ran on it's own thread now, so this issue shouldn't happening anymore.

Anyway, if you aren't planning to update your PPSSPP, you will never have the fix, because whenever we fix something it will be on a newer version.
