### ISSUE TITLE
libretro : Text not show

### ISSUE THREAD

**Issue by hsoftxl** [hrydgard/ppsspp#18415]
### Game or games this happens in

Tekken 6

### What area of the game / PPSSPP

Tekken 6
![80a35737f1d80e96167c114674acde7](https://github.com/hrydgard/ppsspp/assets/6965803/2baa6510-7469-4426-8f11-6b75ae169ef0)

SD GUNDAM G GENERATION World
SD GUNDAM G GENERATION OVER World
![image](https://github.com/hrydgard/ppsspp/assets/6965803/d1a3abd9-c3e1-452b-b6a0-7f800ca9c8be)

### What should happen

it looks like fonts problem.

### Platform

libretro / Retroarch

### Mobile phone model or graphics card

VIVO NEO 5

### PPSSPP version affected

1.6.6

### Last working version

forget

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
You're simply missing files, the "assets" subdirectory from PPSSPP needs to be installed somewhere in the libretro tree, not sure where.

**Comment by hsoftxl** [comment]
after add assets, it worked.
