### ISSUE TITLE
[Feature Request] Track Play Time

### ISSUE THREAD

**Issue by djlain** [hrydgard/ppsspp#18410]
### What should happen

It would be very useful if ppsspp can track play time for each game. It can be displayed when people select a game, or on the game info page. For example:
![202311112232361](https://github.com/hrydgard/ppsspp/assets/98971315/05e5e7e9-d87f-4f1a-a657-d376611ffcd5)
![20231111223220](https://github.com/hrydgard/ppsspp/assets/98971315/8bddae30-731a-4f0e-8629-6f198ab59d18)

Looking forward to seeing the function if possible, thanks very much!

### Who would this benefit

People who want to know how many hours they've spent on certain games.

### Platform (if relevant)

None

### Games this would be useful in

All games

### Other emulators or software with a similar feature

In PCSX2, play time was displayed on the pause menu (upper right corner):
![PCSX2 Nightly - v1 7 5095 2023_11_11 22_41_30](https://github.com/hrydgard/ppsspp/assets/98971315/35a37355-4407-4519-9bc7-458b5ac80ea8)

In Retroarch, play time was displayed on the game select screen:
![60 04 2023_11_11 22_43_53](https://github.com/hrydgard/ppsspp/assets/98971315/d4c3557c-5066-4df1-b43c-edb6efde9cbf)

Additionally, if you're using Retroachievements, it will show the current play time when you master a game, which is also very cool:
![RetroArch Beetle Saturn v1 22 2 f509c39 __ FPS_ 197 54 2022-12-09 08-33-54 mp4_20231007_132836 285](https://github.com/hrydgard/ppsspp/assets/98971315/804c2075-37b7-47c8-a422-dcb7704a4084)

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
I suppose this could be cool.

This would be global for each game, so if you play on multiple saves, it would simply be the total time played regardless of current progress or player etc.

Design issues:

* Where to store the data? We could simply have a section in ppsspp.ini looking like this:

```
[TimePlayedSeconds]
ULUS12345=1321
NPJH00001=4593
```

It would grow over time but likely would also not be a problem.  Or we could have a separate ini file.

Some players would like to transfer their play times between systems, they'd have to manually copy the ini file entries since we still don't have any kind of cross platform sync, see #1019 .

How does PCSX2 save the times?

**Comment by djlain** [comment]
Thanks very much for quick replying! PCSX2 save the times in a similar way, by a file called playtime.dat in the inis folder, it's like this:

> SLPM-65358                       5057                 1699377967          
> SLUS-21216                       119                  1670548388          
> SLUS-21672                       104                  1670548514          
> SLUS-20916                       20                   1670558736          
> SLPM-66930                       167062               1699470236          
> SLPM-66742                       21275                1699470437          
> SLPM-65593                       93                   1696958126          
> SLPM-55117                       25                   1696958165          
> SLPM-55221                       88                   1696958285          
> 20040614-100905                  87                   1699277904          
> SLPM-55147                       2981                 1699643447          

The 2nd column was time played seconds.

**Comment by hrydgard** [comment]
Makes sense. Just curious, what's the third column? Some kind of integrity hash to prevent trivial tampering?

**Comment by djlain** [comment]
I'm also curious about the third column but unfortunately did not find any info about it yet...

And about slow / fast forward (and even frame forward or something), they did not matter in all my mentioned emulators, so only real time will be tracked. And when people pause the game, play time will be paused as well.

**Comment by hrydgard** [comment]
Hm, the last column there are unix timestamps, it turns out. Maybe just recording the last time the game was played.

**Comment by djlain** [comment]
Thanks for the explaining! Just found PCSX2 also displayed the play time and last played time when you select a game on the big picture mode:
![PCSX2 Nightly - v1 7 5095 2023_11_12 17_35_15](https://github.com/hrydgard/ppsspp/assets/98971315/e078e886-fe1e-47a6-b41a-fb3cbf90335f)

Never used this mode before so I missed it.

**Comment by hrydgard** [comment]
Ah, that makes sense!

Yeah, I guess that's pretty neat.
