### ISSUE TITLE
Juiced 2: Car decal editor not working as expected

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#18423]
Reported by forest on Discord.

![image](https://github.com/hrydgard/ppsspp/assets/130929/1cecc966-ac38-4fb9-ac3f-8ec59b89a496)

Apparently, car decals are not visible in the editor, but work outside?

Probably some framebuffer management issue, or possibly gpu memory copy issue...

**Comment by sum2012** [comment]
Does the game ID is ULUS10312 ?
I cannot find the option.

**Comment by hrydgard** [comment]
Maybe it needs to be unlocked? Savegames can be downloaded at https://gamefaqs.gamespot.com/psp/938453-juiced-2-hot-import-nights/saves

I'll look at this in a while.

**Comment by sum2012** [comment]
ok, About "car decals are not visible in the editor" I don't mean it.
![1](https://github.com/hrydgard/ppsspp/assets/2177532/99211025-a6d3-4444-b355-ccf463f6a871)

**Comment by sum2012** [comment]
@hrydgard I search "GPUReadbackRequired" (from .ini) but now there is no code in ppsspp ?

**Comment by hrydgard** [comment]
Well the game is still playable without it, not completely broken. But it maybe would be good to warn indeed.

**Comment by sum2012** [comment]
I think that force GPUReadback for this game better

**Comment by hrydgard** [comment]
Yeah, that could be an option. Especially since readbacks aren't slowing down gameplay since they presumably just happen on startup and in the decal editor.
