### ISSUE TITLE
Mouse faster look like pc games

### ISSUE THREAD

**Issue by Gamernumber1** [hrydgard/ppsspp#18422]
### What should happen

Is it possible to make the mouse rotation speed like on pc games? Whatever settings I make it looks like a gamepad

### Who would this benefit

Gamers

### Platform (if relevant)

Windows

### Games this would be useful in

all 

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
The PSP has a gamepad, not a mouse, and the games thus expect gamepad input - they don't know what a mouse is.

So, the only way to fix this is to hack every game separately to accept mouse input and do something with it, which is not something the emulator can do automatically.

**Comment by Gamernumber1** [comment]
maybe you can speed up to swipe the mouse faster, I swipe on the spot it's fine, swipe to the side slower
