### ISSUE TITLE
Tekken 6 ad hoc problem

### ISSUE THREAD

**Issue by BellaFigura** [hrydgard/ppsspp#18429]
### Game or games this happens in

ULES-01376 Tekken 6

### What area of the game / PPSSPP

When I go back main menu from battle lobby(network), I can't go back and do anything. I'm stuck so I have to restart Tekken 6.

This is the screen shot.
![Screenshot_20231117_165503_PPSSPP](https://github.com/hrydgard/ppsspp/assets/151126699/7dc52e67-1752-43c1-8f72-3afa23c4a24a)

### What should happen

Well... I don''t know how to call this problem.

Bug? Or Loading?

It happens frequently but barely work correctly.

If I go back main menu, it shows like this.
![Screenshot_20231117_170333_PPSSPP](https://github.com/hrydgard/ppsspp/assets/151126699/3241f342-9d42-4ea8-8cd2-6d7e30897c8f)

### Platform

Android

### Mobile phone model or graphics card

Galaxy s10 5g/ LG g7

### PPSSPP version affected

v1.16.6

### Last working version

v1.16.6

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment]
Were you able to connect to adhoc server without issue? (indicated by seeing "Network initialized" message on screen)

As i remembered this kind of issue usually when an error occurred on something that should never return an error in normal condition, so the game will keeps trying endlessly resulting to freezes, for example when the game unable to communicate with adhoc control (on emulator it's when it failed to communicate with adhoc server, on a real PSP probably a condition where the wireless adapter hardware is broken)

**Comment by ANR2ME** [comment]
Okay, after i lost all my partitions due to bad sectors, and reinstalling Windows for days trying not to get corrupted file system, i'm finally able to test this game and able to reproduce it using socom.cc as adhoc server.

I'll try to fix it directly from github later when i found out what actually happened (since i kinda hesitate to install anything big such as Visual Studio due to my Windows often corrupted and need to be reinstallet)

**Comment by ANR2ME** [comment]
This is the logs when it managed to exit the Lobby (kinda rare to happen)
![image](https://github.com/hrydgard/ppsspp/assets/7974720/fa17dad2-4a9d-44fa-ba27-fddb3f8c7944)

This is the logs when it stuck unable to exit the Lobby (happened pretty often)
![image](https://github.com/hrydgard/ppsspp/assets/7974720/d0399ea0-b389-4d3c-a55e-cbcc370b3979)
