### ISSUE TITLE
Mouse input behavior (mapped to right stick using mod) has changed in the latest builds

### ISSUE THREAD

**Issue by Gamernumber1** [hrydgard/ppsspp#18427]
### Game or games this happens in

all 

### What area of the game / PPSSPP

In the new version, you messed up something with moving the stick it looks like some kind of inversion , moving to the side

### What should happen

fix bug

### Platform

Windows

### Mobile phone model or graphics card

gtx 1050ti

### PPSSPP version affected

latest

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by Gamernumber1** [comment]
the stick behavior itself is better in previous versions.

**Comment by Gamernumber1** [comment]
The latest version where the stick worked well is ppsspp-v1.16.6-238-ge2f6b36a1. Since the ppsspp-v1.16.6-240-ge93f9f64c version, the stick works strangely, Inversion move around and so in the latest version

**Comment by hrydgard** [comment]
You're gonna have to describe your problem better. Is this still about tilt control? Touch control joystick? Controller input?

You may want to record a video comparing the behavior. For me, the current behavior seems fine in all cases.

**Comment by Gamernumber1** [comment]
https://youtu.be/0QzBJ4lgGHs

**Comment by Gamernumber1** [comment]
In latest version https://www.youtube.com/watch?v=0QzBJ4lgGHs&feature=youtu.be

**Comment by Gamernumber1** [comment]
in old build https://www.youtube.com/watch?v=SBsMHKSV0OE

**Comment by Gamernumber1** [comment]
the game settings are used, the new version has a very bad rotation and I can't rotate around

**Comment by Gamernumber1** [comment]
> You're gonna have to describe your problem better. Is this still about tilt control? Touch control joystick? Controller input?
> 
> You may want to record a video comparing the behavior. For me, the current behavior seems fine in all cases.

the game settings are used, the new version has a very bad rotation and I can't rotate around

**Comment by hrydgard** [comment]
This is very weird and it's not super obvious, but it kinda looks like the new one only rotates on the diagonal, odd.

Also the PSP does not have a "right stick", does this refer to using cheats or a plugin? Do they seem to work differently?

Also you haven't explained if you're using a pad, a keyboard, a touch screen or mouse or what your input device is.

**Comment by Gamernumber1** [comment]
i use mouse and right analog patch, but in latest version this not work corrcet.  ppsspp-v1.16.6-238-ge2f6b36a1 working corrcet. All setting all settings are identical.

**Comment by hrydgard** [comment]
Hm, now we're getting somewhere! Does -240 work, or is that exactly where it breaks? thanks!

**Comment by Gamernumber1** [comment]
> Hm, now we're getting somewhere! Does -240 work, or is that exactly where it breaks? thanks!

**Comment by Gamernumber1** [comment]
> Hm, now we're getting somewhere! Does -240 work, or is that exactly where it breaks? thanks!

ppsspp-v1.16.6-240-ge93f9f64c Starting from 240, maybe 239 doesn't work anymore. I can't install version 239 because it's not publicly available

**Comment by hrydgard** [comment]
It's OK not to test 239.

But you confirm that things are broken in 240 and work in 238? That's very strange, but I'll look into it soon.

**Comment by Gamernumber1** [comment]
Oh no, there is an error in 239, the camera involuntarily rises at running. I think it's better to rely on an older build from September. I've only discovered it now

**Comment by Gamernumber1** [comment]
I can say for sure that the September version works fine. I'll clarify later which one

**Comment by Gamernumber1** [comment]
ppsspp-v1.16.5-34-gdea038a91 the latest version where everything worked correctly

**Comment by Gamernumber1** [comment]
in latest build all good but the camera involuntarily rises up scrolling if we look slightly up

**Comment by Gamernumber1** [comment]
the camera moves by itself, I didn't do anything, there is no such thing on the old version

https://www.youtube.com/watch?v=xHir9_ireBE

**Comment by hrydgard** [comment]
@Gamernumber1 Can't see that video, it's private.

**Comment by Gamernumber1** [comment]
> @Gamernumber1 Can't see that video, it's private.

sorry https://www.youtube.com/watch?v=xHir9_ireBE

**Comment by hrydgard** [comment]
Thanks, that's certainly looking odd..

**Comment by Gamernumberone** [comment]
> Thanks, that's certainly looking odd..

The bug is due to the circular stick input in setting.

**Comment by Gamernumberone** [comment]
> Thanks, that's certainly looking odd..

High sensivite in new build 
https://youtu.be/uxgOT9o3gwQ

Normal sensivity in verison ppsspp-v1.16.6-473-g904ce4f7e-windows-amd64 (latest good version)
https://youtu.be/6-RPR7GbHas

**Comment by Gamernumberone** [comment]
circular input bug appeared with version ppsspp-v1.16.5-34-gdea038a91

https://www.youtube.com/watch?v=tMn6lkd9UOQ

**Comment by Gamernumberone** [comment]
How it worked in ppsspp-v1.16.5-34-gdea038a91. I think all the errors started with version v1.16.5-40-g8eefb9f93, it says in the build information that you changed something

https://youtu.be/RqkujrIm41c

**Comment by Gamernumberone** [comment]
ppsspp-v1.16.6-503-g03bd7c1ca-windows-amd64 there is no bug with circular input, but for some reason the sensitivity or speed is higher with the same settings

**Comment by Gamernumberone** [comment]
ppsspp-v1.16.6-503-g03bd7c1ca circular input bug and hight sensivity compared with ppsspp-v1.16.6-473-g904ce4f7e
https://youtu.be/7Wxo9-XWQSA

**Comment by hrydgard** [comment]
Alright, I want to try this for myself to eliminate any sources of confusion.

Can you confirm that this is the plugin you're using for GTA? https://github.com/Freakler/ppsspp-GTARemastered/releases/tag/1.0 

When you record videos, it could be interesting to display the right analog stick as a touch control, to see what's happening with it.

**Comment by Gamernumberone** [comment]
> Хорошо, я хочу попробовать это сам, чтобы исключить любые источники путаницы.
> 
> Можете ли вы подтвердить, что используете именно этот плагин для GTA? https://github.com/Freakler/ppsspp-GTARemastered/releases/tag/1.0
> 
> Когда вы записываете видео, может быть интересно отобразить правый аналоговый джойстик в качестве сенсорного управления, чтобы посмотреть, что с ним происходит.

yes. any patch on the right stick. I don't know, I do not know, I think it is related to the version, because when I change the ppsspp version, bugs occur. In version ppsspp-v1.16.5-34-gdea038a91 it worked well as before in all versions

**Comment by Gamernumberone** [comment]
this does not happen immediately, after 4-5 seconds the camera will scroll around.

**Comment by Gamernumberone** [comment]
in touch control 
![O7OtrE0LCq8](https://github.com/hrydgard/ppsspp/assets/153068073/a62e72fd-cb92-4e74-bfe5-1424ea447de5)

**Comment by Gamernumberone** [comment]
Thank you this has been fixed in the version Thank its fixed in version v1.16.6-588-g58e12acee
