### ISSUE TITLE
Blue screen after first save (UCJS10002 : Doko Demo Issho)

### ISSUE THREAD

**Issue by kedamohno** [hrydgard/ppsspp#18420]
### Game or games this happens in

UCJS10002 : どこでもいっしょ(Doko Demo Issho)

### What area of the game / PPSSPP

After I saved my game for the first time, I can't open the game without a savestate. It has a blue screen every time. (thats very bad since the games whole point is checking on toro everyday :()

<img width="944" alt="Screen Shot 2023-11-13 at 2 12 16 PM" src="https://github.com/hrydgard/ppsspp/assets/124019772/496aac36-7d28-4f65-9822-211654041490">

heres my savedata: 

[UCJS10002000.zip](https://github.com/hrydgard/ppsspp/files/13340817/UCJS10002000.zip)

### What should happen

It should just open to the screen that asks if you want to continue. I can get to that screen via savestate: 
<img width="942" alt="Screen Shot 2023-11-13 at 2 19 42 PM" src="https://github.com/hrydgard/ppsspp/assets/124019772/2347aa66-3960-4db5-a45c-1ba72d0ca021">
(thats how it looks) But the crash makes it so I can't progress in the game. this crash never happened until I actually saved the game, and there was a continue button. 

### Logs

sadly I can't figure out where my dumped logs are on mac :,(

### Platform

macOS

### Mobile phone model or graphics card

Intel(R) Iris(TM) Graphics 6100

### PPSSPP version affected

v1.16.6

### Last working version

v1.16.6

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by sum2012** [comment]
english name:Doko Demo Issho

**Comment by ANR2ME** [comment]
The game will also crashed not long after running it, if a savedata is present (using the savedata provided in the first post, may be the savedata didn't get fully saved and corrupted?)
![image](https://github.com/hrydgard/ppsspp/assets/7974720/52a8b885-068f-448a-941f-2a1edb250f63)

Debug Logs: 
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/13342833/ppsspplog.zip)

**Comment by kedamohno** [comment]
thats true, and really interesting! do you think I should try maybe deleting my savestates and trying again?

**Comment by sum2012** [comment]
@kedamohno Yes,I do thing so

**Comment by IrfanH495** [comment]
I'm not experiencing a blue screen or maybe not yet.  I don't understand the time difference here.
https://drive.google.com/file/d/1XmTvb-FSyuTH4kft4vJDzmuBBac5a1hO/view?usp=drivesdk
Sorry, I uploaded this image via the link, I can't upload the image here, I don't know why.

**Comment by IrfanH495** [comment]
after adding to compat ReportSmallMemStick  I can load games without problems on Android, I don't know how on other devices
https://youtu.be/NaV5LtxGxPg?si=QkIPzHV4HIHpTCWF

**Comment by IrfanH495** [comment]
@kedamohno save data above leaving me trapped in the room and out of character

**Comment by kedamohno** [comment]
thank you all!!!!! I deleted the first save, started a new game, and dont seem to have any issues after i close and open again. i do recall instead of using esc and pressing "exit game" I think i closed the ppsspp tab which was probably a terrible idea and might have corrupted the save. i'm going to wait until tomorrow to see if theres any issues, but I think it might be fixed! :)

**Comment by hrydgard** [comment]
I went ahead and added it under [ReportSmallMemstick] too.

**Comment by IrfanH495** [comment]
I don't use last build, it's really random, sometimes the game loads itself, sometimes it won't load .
exit the application and enter it again while the game loads itself.
I will try last build.

**Comment by IrfanH495** [comment]
@hrydgard sorry, I think my suggestion is wrong.
in the last build it looks like this.
https://youtu.be/hEINCwAwM7E?si=BhrlgW8TIbGkBHv1
the game loads as usual

**Comment by hrydgard** [comment]
well, that setting usually doesn't really hurt anyway, so i'll keep it.

**Comment by kedamohno** [comment]
sad update... i checked on toro last night and he was fine, but now its crashed again. im not sure what to do to keep the file from corrupting?   :(

**Comment by kedamohno** [comment]
also im not sure what a reportsmallmemstick is. is there something i should download?

**Comment by IrfanH495** [comment]
@kedamohno Are you stuck again where the characters are not visible in the room? 
you left him he seems quite long read this
https://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q12122249467
Just like your save data above, I also experience it but it doesn't become a blue screen.
this game follows our time in the real world I tried changing the time to 1 pm and in the game to noon

**Comment by hrydgard** [comment]
> also im not sure what a reportsmallmemstick is. is there something i should download?

No, it's a per-game compatibility setting. I've set it on now for all future versions. It tricks games that your memory stick is smaller than available disk space, because some games can't handle modern disk sizes...

**Comment by IrfanH495** [comment]
I didn't mean to spam
@kedamohno I tried saving your data above, and found the pet had gone and left a letter
Goodbye•••
I go on a journey to find a way to become human...
I wanted to talk more...
https://youtu.be/_QGvog9p5s8?si=bqn03aj5MEZ2abFf
so I guess the game crashes after the pet leaves or is this a different issue

**Comment by kedamohno** [comment]
@IrfanH495 I do believe thats a game feature if you leave him alone too long. maybe thats because the save youre using is mine from a while ago...hopefully that shouldn't be an issue for me, my time seems to be synced correctly! I tried the save again, im deleting my old save, my savestates, and trying again fully! if it crashed tomorrow, i'll have to keep investigating :,)

**Comment by kedamohno** [comment]
> > also im not sure what a reportsmallmemstick is. is there something i should download?
> 
> No, it's a per-game compatibility setting. I've set it on now for all future versions. It tricks games that your memory stick is smaller than available disk space, because some games can't handle modern disk sizes...

oh, i see! thank you! i'll make sure to check whether i have that on or off...

**Comment by ANR2ME** [comment]
Changing CPU clock to 55 seems to be works for me, so there might be timing issue here.

**Comment by sum2012** [comment]
@ANR2ME Maybe we need a compat setting for the status.

**Comment by sum2012** [comment]
@ANR2ME Change timing setting to  Simulate UMD  slow reading speed work !!!

**Comment by kedamohno** [comment]
> Changing CPU clock to 55 seems to works for me, so there might be timing issue here instead of corrupted savedata.
> 
> I'm able to run the game with savedata present ![image](https://user-images.githubusercontent.com/7974720/283636452-1c24fe15-d266-44bc-b039-e809ef5a53e8.png)
> 
> PS: the thread that crashed is probably audio-related thread since it use "pcm" (ie. "sgx-pcm-th") in the thread name, and the last file being loaded before the crash is `5=sceIoOpen(disc0:/PSP_GAME/USRDIR/data/sound/bgm/hiru1.sgd, 1, 0)`
> 
> Edit: This could also be timing issue with `sceUtilitySavedataInitStart/sceUtilitySavedataShutdownStart` dialog, just like the msg dialog at #15304 where changing the CPU clock could prevent a crash.
> 
> Edit2: based on the logs the status being retrieved by the game seems to be missing the 4 status (ie. 3 -> 0, instead of 3 -> 4 -> 0), so this could also be similar issue to [#15068 (comment)](https://github.com/hrydgard/ppsspp/issues/15068#issuecomment-1185311485) (but since i've lost all my partitions due to bad sector, so i can't test whether that fix worked for this game too or not)

im sorry, i still new to emulators so im confused. is there anything i should edit in ppsspp settings? do i need to edit the files in ppsspp or do something to my computer? I still feel like I have no clue how to prevent this crash :(

**Comment by sum2012** [comment]
here is easier solution


在 2023年11月22日週三 下午12:36，kedamohno ***@***.***> 寫道：

**Comment by anr2me** [comment]
@sum2012 i think you forgot to write the solution :)

**Comment by sum2012** [comment]
@anr2me I have attach image to Email but don't work here. Anyway v1.16.6-341-g4d7f00f96 have merged Simulate UMD slow reading. I test it also load the first post of save  in android no problem
