### ISSUE TITLE
Jeanne Darc , skills stones are not  showing, cannot equip it.

### ISSUE THREAD

**Issue by joaodefariajunior** [hrydgard/ppsspp#18431]
### Game or games this happens in

UCUS98700_1.00

### What area of the game

Since, the beginning I cant equip the skill stones

### What happens

When I click on equip skill stones, it doesn't show, but if I click on time list it shows.
![UCUS98700_00000](https://github.com/hrydgard/ppsspp/assets/54619148/63cc2d08-81e5-4ce8-adee-572f82ac7937)
![UCUS98700_00002](https://github.com/hrydgard/ppsspp/assets/54619148/85d63cc4-7b65-4e50-b915-25032abb0b91)
the 

### What should happen

I should appear the skill stone and I should be able to equip them.

### Platform

Windows

### Mobile phone model or graphics card

Nvidia Geforce RTX 4050 laptop

### PPSSPP version affected

v1.16.6

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [ ] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment]
Does using software renderer makes a difference?

**Comment by joaodefariajunior** [comment]
nope, tried...same result

**Comment by ANR2ME** [comment]
Hmm.. i guess it's not a visual/graphical glitches but more of a logical error.

Does changing the CPU Core to Interpreter makes a difference? (in case it was JIT/IR issue).

And, you're not using any cheat, right? if you're, please disable all the cheat when testing.

**Comment by anr2me** [comment]
The default CPU core is usually JIT (dynarec), so you need to change it to Interpreter for testing purpose, since Interpreter usually more accurate in emulating the CPU (but the slowest one too)

**Comment by joaodefariajunior** [comment]
And how can I do that? (Sorry,for my ignorance)

Em seg., 20 de nov. de 2023 11:31, AdamN ***@***.***>
escreveu:

**Comment by anr2me** [comment]
To change CPU Core, go to Settings -> Tools -> Developer Tools -> CPU core
To change CPU clock, go to Settings -> System -> Change emulated PSP's CPU clock

**Comment by joaodefariajunior** [comment]
No deal, I´ve changed all the CPUs core....and nothing, same result....

**Comment by hrydgard** [comment]
Has this worked in some previous version? Did you check exactly what happens on a real PSP?

**Comment by joaodefariajunior** [comment]
I´ve installed previous versions and still the same...I dont have a PsP ....

**Comment by hrydgard** [comment]
I'm really surprised nobody has reported it before, if it's an actual emulation issue. Could someone check what happens on a real PSP in this case?

**Comment by joaodefariajunior** [comment]
guess what? I´ve installed a texture pack...and now it works! thank you for
the support, I almost lost hope on this game!

**Comment by hrydgard** [comment]
That is extremely weird, a texture pack shouldn't affect functionality. For the revird

**Comment by LunaMoo** [comment]
I don't think this is an actual problem, more likely user not knowing what to do.
To equip skills you need to enter the menu that the first screenshot in this issue shows, but then select slot and confim. Even through it feels natural, the game UI doesn't tell that like modern games would, which might where the confusion comes from. Texture pack would make no difference, he probably tried pressing X only after obtaining texture pack. Works fine without anything for me.
