### ISSUE TITLE
making archive in xcode results an 4kb archive that is almost empty...

### ISSUE THREAD

**Issue by SohrabIranpak** [hrydgard/ppsspp#18451]
### Platform

iOS

### Compiler and build tool versions

Apple clang version 15.0.0 + cmake version 3.27.7

### Operating system version

macos 14

### Build commands used

i have used xcode 15 -> products -> archive
results an 4kb archive that is almost empty

### What happens

results an 4kb archive that is almost empty

### PPSSPP version affected

latest version

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] Make sure to run `git submodule update --init --recursive` before building.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try deleting the build directory and running the build again.
- [X] Check GitHub Actions, which builds every merge and PR.
- [ ] Include logs and help us reproduce.

**Comment by anr2me** [comment]
Btw, before making the archive, were you able to build both the Debug and Release version successfully?

**Comment by SohrabIranpak** [comment]
yes i can build release and debug version successfully

**Comment by SohrabIranpak** [comment]
found the solution
set skip intall for all targets to YES  (except main target PPSSPP)
set installation Directory to  "$(LOCAL_APPS_DIR) (/Applications)" for all targets
and that should do the job!
