### ISSUE TITLE
Unable to make diagonal inputs with controller's analog stick

### ISSUE THREAD

**Issue by HFPasfho** [hrydgard/ppsspp#18459]
### Game or games this happens in

many 3d games

### What area of the game / PPSSPP

PSP 3D games had to be creative with hardware with only one analog stick. Some let you control camera with dpad or square/circle/cross/triangle buttons. Using such controls on touchscreen is ok. If you make circles with you finger the camera makes similar movement in the game. But this doesn't work with external controllers. Binding these keys to right analog results in bad experience. Making circles with analog stick the camera movement follow a square shape in the game. It looks like you can't make diagonal inputs with bluetooth controller. 

Simple mapping controller right analog to dpad keys didn't work. I tried to calibrate analog stick in control options. I tried every combination of these options e.g. increasing sensitivity, changing input to circular etc. but I was unable to make diagonal input e.g. up and right at the same time. I also tried to add custom right analog stick in touch screen controls, bind it to dpad and then map bluetooth controller right analog to this but it didn't work at all. I even experiment with combo mappings but no matter what I was unable to make diagonal input. Even tried second controller thinking maybe it's of low quality but dualshock 4 didn't work either. I tested them both on the testing website and their analogs works fine and can make all range of inputs. At this point I'm certain this is a bug in PPSSPP.

### What should happen

Using controller right stick should give same experience as using touchscreen controls which allow diagonal inputs with ease.

### Platform

Android

### Mobile phone model or graphics card

Samsung S9

### PPSSPP version affected

v1.16.6-372-gc3f881b7

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
It's not really a bug, as much as there being no special case code for this. If you map an analog stick to the four face buttons or the d-pad, we treat it as four individual analog inputs, and when you hold it diagonally it doesn't reach the threshold to consider the buttons pressed.

We might need to detect this case in the mapping logic, or do something more clever..

**Comment by HFPasfho** [comment]
I think it's an important use case since mapping such inputs to additional analog stick that psp hardware didn't offer is probably the biggest quality of life improvement an external controller could bring. It already works nice on touchscreen where we can draw circles with our finger on dpad so it shouldn't be too much trouble to implement it. Would be really nice to see this in ppsspp. Thank you for the quick replay and for all your amazing work! This is the best mobile emulator in the world by far!

**Comment by hrydgard** [comment]
Yes, I agree that it's an important use case, and it would be really nice if this worked well.

**Comment by hrydgard** [comment]
Realized that this is exactly the same as #17792 , closing (while keeping that one open).
