### ISSUE TITLE
Enabling disabling the mouse by pressing the button, also for showing touch control. 

### ISSUE THREAD

**Issue by Gamernumber1** [hrydgard/ppsspp#18464]
### What should happen

So that we can bind these functions in the settings and turn them on or off when pressed.

### Who would this benefit

Ppsspp

### Platform (if relevant)

Windows

### Games this would be useful in

Ppsspp

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by Gamernumber1** [comment]
Well, I noticed that you added exit the app by pressing the button, I would like you to add this to turn or off on the mouse and show the touch control. In my opinion, this is faster and more convenient than turning it off individually all the time in the settings. I want you to add in the control settings the ability to add buttons for these functions.

**Comment by hrydgard** [comment]
OK. Toggle-bindings (single button for on/off) would seem appropriate here, right?

**Comment by Gamernumberone** [comment]
> OK. Toggle-bindings (single button for on/off) would seem appropriate here, right?
> 
> Also I'm not really seeing the case for a toggle button for touch controls, again, like, if you have bindable buttons, you wouldn't be playing with touch, would you..

I have lost the passwords to my pc, I am writing to you from another account. Well, the function of turning on and off the mouse is convenient for debugging. And the shows of touch controls is convenient for quickly entering cheat codes in the game when you forget which buttons.

**Comment by Gamernumberone** [comment]
I decided to play a new build, as for me, the sensitivity has become very fast compared to the previous ones, it is not very convenient.

**Comment by hrydgard** [comment]
You can turn down the sensitivity in the mouse section of control settings. If you let me know what setting value matches the old setting values, I can fairly easily change it to be similar at least.

**Comment by Gamernumberone** [comment]
> You can turn down the sensitivity in the mouse section of control settings. If you let me know what setting value matches the old setting values, I can fairly easily change it to be similar at least.

ppsspp-v1.16.6-473-g904ce4f7e-windows-amd64 the latest version where it was convenient for me, on newer ones I can no longer aim and I can't adjust how it was.

**Comment by Gamernumberone** [comment]
In my opinion, the speed of the stick is better in the old version. But there's still a problem associated with the input stick that the camera moves by itself

**Comment by hrydgard** [comment]
I have made some improvements in the latest builds that should restore the speed to something very similar as before.

However, I have not been able to reproduce the problem with moving by itself - it doesn't do that for me. You didn't enable tilt input or something, right?

**Comment by Gamernumberone** [comment]
I turned on the circular input and it turns the camera on itself. I check new build later

**Comment by hrydgard** [comment]
Circular input? What option is that? We don't have a circular option for mouse input, at least not yet.

**Comment by Gamernumberone** [comment]
Thanks, everything is fixed in the latest version! At least I haven't noticed any mistakes yet.
