### ISSUE TITLE
[Regression] GTA LCS textures problem on hw renderer starting with v1.16.6-222-g1e6142d99

### ISSUE THREAD

**Issue by amadeuskurisu02** [hrydgard/ppsspp#18467]
### Game or games this happens in

ULUS10041

### What area of the game

Many areas. Can't list them all

https://github.com/hrydgard/ppsspp/assets/152798631/139714db-88a0-4ab4-9e56-72a399f6f427

### What happens

Textures switches between mip ones and normal on hw renderer depending on the camera angle. It doesn't depend on player's distance from object.

### What should happen

Textures shouldn't do that. As they didn't do that on sw and v1.16.6 and earlier on hw.

https://github.com/hrydgard/ppsspp/assets/152798631/50fdfc93-331a-4bc8-8288-c9aba4146a52

https://github.com/hrydgard/ppsspp/assets/152798631/2b9d29f2-d01f-4fb3-8c5e-4c68b69a8d4b

### GE frame capture

[ULUS10041_0001.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/13539513/ULUS10041_0001.ppdmp.zip)

### Platform

Android

### Mobile phone model or graphics card

Xiaomi Poco F3, Redmi Note 8T

### PPSSPP version affected

Every version after v1.16.6

### Last working version

v1.16.6

### Graphics backend (3D API)

Vulkan, OpenGL

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [ ] Include logs or screenshots of issue.

**Comment by amadeuskurisu02** [comment]
I didn't tried to load frame dump, cuz I didn't know how to. But now when I know and I've tried. For some reason it dosen't shows when you load a frame dump.

**Comment by hrydgard** [comment]
Found the problem, but I've got a couple of options for the fix. Anyway, there will be a fix soon.
