### ISSUE TITLE
RetroArch save game & other PSP menu text is not rendered, black boxes are rendered instead of letters

### ISSUE THREAD

**Issue by Ejurety** [hrydgard/ppsspp#18479]
### Game or games this happens in

All tested

### What area of the game

anytime a menu is loaded that would be from the PSP OS menu/interface, e.g. save menus or popup system messages

tested on RetroArch on Linux, and RetroArch on Android. Same result with any game tested

WHAT I HAVE TRIED:
- installing the assets folder from RetroArch online updater
- installing the assets folder from the master branch on Github
- installing the assets folder from v1.16.6 on Github
- tried changing a load of core settings
- tried Vulkan (crashes on Android, makes no difference on Linux)

none of this made any difference

### What happens

![Coded Arms-231206-003041](https://github.com/hrydgard/ppsspp/assets/99275419/72605371-ccda-42b0-ac5f-c92e28bdfa6e)
![GTA Liberty City Stories-231206-003234](https://github.com/hrydgard/ppsspp/assets/99275419/5536b628-e950-4615-b608-95fdefae9e27)
![GTA Liberty City Stories-231206-003245](https://github.com/hrydgard/ppsspp/assets/99275419/1946efe6-8a22-46a6-93cc-c0dd237c996e)
![Guilty Gear X-231206-003424](https://github.com/hrydgard/ppsspp/assets/99275419/3da1e9eb-03fe-45ea-ad87-8ca72337e411)
![Gun Showdown-231206-003522](https://github.com/hrydgard/ppsspp/assets/99275419/369a38bd-dd54-4b64-a92e-a12928a1d002)
![PPSSPP](https://github.com/hrydgard/ppsspp/assets/99275419/c41b6949-eae7-4074-9345-1ae03d40ca25)

### What should happen

text should be rendered and readable

### Platform

Android

### Mobile phone model or graphics card

Moto G50 5G

### PPSSPP version affected

1.16.0 - PPSSPP (v1.16.6-199-g256d670) on Android, 1.15.0 - PPSSPP (81d741a) on Linux)

### Last working version

no idea, never used PPSSPP before

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by Ejurety** [comment]
> Hmm.. might be similar issue to #18474
> 
> Btw which language are you using?

It was on automatic, swapped to English in an attempt to fix it, made no difference

**Comment by IrfanH495** [comment]
ppsspp-v1.16.6-420-g45980671f-android 
On Samsung M20 Android 10 it also happens but only X&O
Openg GL
![Screenshot_20231206-235459_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/f47ef29b-c65f-42aa-af6e-d3bf91fba69a)

Vulkan
![Screenshot_20231206-235524_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/577b20d4-8d72-46eb-9b8f-0212975bb830)

**Comment by bslenul** [comment]
Bisected, it started to happen pretty recently, with commit 5373b8c5b3838aa22bccb2f3e181d2684ca00aea

![image](https://github.com/hrydgard/ppsspp/assets/33353403/a8f29c38-09c4-472c-8b7a-fc1e21fc07c4)

No issue with the previous commit (fb8ad0c33a5ea173d0cb3289b3773492f976d9e7)

![image](https://github.com/hrydgard/ppsspp/assets/33353403/71bcc65b-70ca-4f83-8745-396f914feba9)
