### ISSUE TITLE
Device Adaptive Refresh Rate Ruins PPSSPP Performance

### ISSUE THREAD

**Issue by Crocodi13** [hrydgard/ppsspp#18480]
### Game or games this happens in

In every 60 FPS games

### What area of the game / PPSSPP

I have an 90hz display Android 13 device with "Adaptive Refresh Rate' feature which for some reason cannot be disabled even though I use the default 60hz option which still drops to 50hz.

It drags the FPS down when it kicks in ( from 60hz to 50hz when you're not touching the screen for about a 40sec/1minute in PPSSPP) it's noticeable when running 60 FPS game.

After a cutscene ends or just being idle for a sec the FPS runs 50/60 instead of 60/60 which can be fixed by touching the screen again but it's so annoying.

### What should happen

I would like to ask for an option or setting to make PPSSPP demand 60hz refresh rate or force the device to use 60hz refresh rate all the time so that Adaptive Refresh rate will not kick in and ruin the performance.

### Platform

Android

### Mobile phone model or graphics card

Poco M5

### PPSSPP version affected

v1.16.6

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by Crocodi13** [comment]
My device has high performance mode but even it's toggled the issue is still present

**Comment by anr2me** [comment]
Well Poco F1 also have similar issue based on this post https://xdaforums.com/t/poco-f1-cpu-throttling-custom-rom-and-kernel-related-questions.4617653/

**Comment by Crocodi13** [comment]
I hope I find a fix only ppsspp is suffering from this other emulators are fine on this same device

**Comment by Crocodi13** [comment]
A workaround would be appreciated 🙏

**Comment by anr2me** [comment]
> A workaround would be appreciated 🙏

Btw, did you enable "render duplicate frame to 60hz" ? if you are, try disabling it.

**Comment by Crocodi13** [comment]
> > A workaround would be appreciated 🙏
> 
> Btw, did you enable "render duplicate frame to 60hz" ? if you did, try disabling it.

No I always disable it

**Comment by Crocodi13** [comment]
> I'll try to add the new checkbox with the possible workaround tonight or tomorrow, stay tuned.

Thank you, thank you so much 🙏

**Comment by hrydgard** [comment]
I've added a new option in Tools/Developer Tools: "Framerate Mode". Try the various modes and see if they help.

Unfortunately on my 120hz Poco F4 it doesn't seem to have much of an effect. But let me know.

**Comment by Crocodi13** [comment]
It Works! Thanks Sir 🙏🫡

**Comment by Crocodi13** [comment]
Update: After testing and playing with the setting for a while I found out that "Request 60hz" and "Force 60hz 1" works really well while "force 60hz 2" seems unstable.

The Frame rate of 60fps game now locks properly even after a cutscene or being idle for a while it stays 60 with the refresh rate!

Sometimes I still notice some little dips in frame rate around 57/60 when not interacting with the screen but the refresh remains constant 60hz and it's a much better experience than before thank you 🙏🤍🫡

Req: I think you should prevent the access of the setting while ingame it causes the UI to go white but other than that it's pretty perfect! Thank you very much sir Henrik 🫡🫡🫡

**Comment by hrydgard** [comment]
Thank you for testing!

I am simply going to default it to Request then.
