### ISSUE TITLE
Juiced 2: Decals are not rendered

### ISSUE THREAD

**Issue by stefan-girlich** [hrydgard/ppsspp#18482]
### Game or games this happens in

ULES-00928 - Juiced 2

### What area of the game

Race, decal editor or in-career menu - basically anytime a 3D car is shown 

### What happens

![Screenshot_20231206-212657](https://github.com/hrydgard/ppsspp/assets/1755315/30599e25-bf41-4605-b06f-bedc9e7ae1e2)
Cars do not have decals, dirt/surface texture on road is missing 

### What should happen

Cars should have decals, see example: https://www.gamezone.de/screenshots/662x/2007/10/screen2_large_10_.jpg

Using the most recent Git build fixed the missing road texture, but not missing car decals.
Restarting the game and creating a new save game fixes both issues

### Platform

Android

### Mobile phone model or graphics card

Nothing Phone 1

### PPSSPP version affected

V1.16.6

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by anr2me** [comment]
Similar issue to https://github.com/hrydgard/ppsspp/issues/18423

**Comment by sum2012** [comment]
@stefan-girlich Can you also upload the game save ? Thanks

**Comment by stefan-girlich** [comment]
[202312091126_ULES00928.zip](https://github.com/hrydgard/ppsspp/files/13623814/202312091126_ULES00928.zip)
This contains the PSP save game, the PPSSPP save game and a frame dump at the time of the PPSSPP save.
Note: Theoretically there could be cars without any decals at all, but the ones captured in the dump/save are all AI cars which are usually heavily decorated with decals:
![ULES00928_1 00_1](https://github.com/hrydgard/ppsspp/assets/1755315/710a87c9-1d2d-49db-a12b-44ca7e88bc8e)


Thanks for the quick responses!!

**Comment by sum2012** [comment]
@stefan-girlich You may need money to buy a decal
![1](https://github.com/hrydgard/ppsspp/assets/2177532/83d4e852-ab73-453e-852f-1592af6e48a7)
[juiced-2-hot-import-nights.21963.zip](https://github.com/hrydgard/ppsspp/files/13624221/juiced-2-hot-import-nights.21963.zip)

**Comment by stefan-girlich** [comment]
I tried, but decals are not visible in the editor/shop either. Also, decals on other cars should be visible regardless of my own car. I'll  try the save state you provided.

**Comment by hrydgard** [comment]
Okay, so without "skip gpu readbacks" all is well? If so I'll close this. It's expected that skipping GPU readbacks can cause problems like these.

**Comment by stefan-girlich** [comment]
Yeap, let's close this one. Thanks for the guidance!
