### ISSUE TITLE
Slow down when not interact the screen for a few seconds

### ISSUE THREAD

**Issue by WarmestKrafter** [hrydgard/ppsspp#18514]
https://github.com/hrydgard/ppsspp/assets/112315947/7a0cde66-c10c-4667-b891-281839b4edff

**Comment by hrydgard** [comment]
Need more details, hardware etc.

Might be related to the recent report about some Android phones dropping down to 45 or 50hz after a while, and forcing the display rate to 60hz might help.

**Comment by WarmestKrafter** [comment]
> Need more details, hardware etc.
> 
> Might be related to the recent report about some Android phones dropping down to 45 or 50hz after a while, and forcing the display rate to 60hz might help.

I found out that turning off "render duplicate frame to 60hz" fixes it, but the game still has some micro stutters.

**Comment by hrydgard** [comment]
Can you please tell me what device you have?

**Comment by WarmestKrafter** [comment]
> Can you please tell me what device you have?

A POCO M5 with Helio G99

**Comment by hrydgard** [comment]
Thanks, that has a 90hz screen, which seems like a common denominator in these latest reports of slowdowns.

**Comment by Crocodi13** [comment]
> > Need more details, hardware etc.
> > Might be related to the recent report about some Android phones dropping down to 45 or 50hz after a while, and forcing the display rate to 60hz might help.
> 
> I found out that turning off "render duplicate frame to 60hz" fixes it, but the game still has some micro stutters.

This game is running 30 fps so you won't notice the dips on frame rate occasionally but if you run a 60 fps game like Tekken 6 you would see that the refresh rate dipping really ruins the performance.

**Comment by hrydgard** [comment]
I've added a new option in Tools/Developer Tools: "Framerate Mode". Try the various modes and see if they help.

Unfortunately on my 120hz Poco F4 it doesn't seem to have much of an effect. But let me know.

**Comment by hrydgard** [comment]
Please try again with the latest build. Also see the last posts in #18480.

**Comment by hrydgard** [comment]
I'm gonna close this on the basis that it's indeed likely the same as #18480. Please reopen if the problem persists in new builds.
