### ISSUE TITLE
F-droid release: Touch is inaccurate

### ISSUE THREAD

**Issue by davidhedlund** [hrydgard/ppsspp#18522]
### Game or games this happens in

*

### What area of the game / PPSSPP

* Start PPSSPP
* In the f-droid release: Settings -> System -> Screen rotation: Select "Auto"

Issues:
* Hold the phone vertically to set the screen rotation to portrait. Touch the menus and observe that the entry set above your touch zone will be hit.
* Hold the phone horizontally to set the screen rotation to landscape. Touch the menus and observe that the entry set to the left of your touch zone will be hit.

### What should happen

What you click on should be activated, not something else.

### Platform

Android

### Mobile phone model or graphics card

* tested 2 totally different models

### PPSSPP version affected

1.1.1

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Don't open issues on ancient versions of PPSSPP please.

The f-droid release is not managed by the PPSSPP project, it's some volunteer who hasn't bothered to update it in a long time.

I just don't have time to manage yet another release platform.

**Comment by davidhedlund** [comment]
* https://github.com/hrydgard/ppsspp/issues/9112
