### ISSUE TITLE
Better support from exiting directly from the pause menu

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#18528]
When running from frontends, we already support --pause-menu-exit as a command line argument, to exit directly from the in-game pause menu.

But in case of non-cooperating frontends, we could also simply have an option for it. 

Also, we should change the caption on the button and maybe ask for confirmation.

**Comment by Jetup13** [comment]
Is there a way we can have this run through command (adb or frontends) on android? I've tried the following but it doesn't work:

`--ez pause-menu-exit true`

**Comment by hrydgard** [comment]
Actually, here's how to do it @Jetup13  (after some digging, heh):

```
adb shell am start -n org.ppsspp.ppsspp/org.ppsspp.ppsspp.PpssppActivity --es org.ppsspp.ppsspp.Args "--pause-menu-exit"
```

**Comment by Jetup13** [comment]
Thanks! Seem like I can get that to work through adb but not through Daijishou or other frontends with this: 

```
-n org.ppsspp.ppsspp/.PpssppActivity
-a android.intent.action.VIEW
-c android.intent.category.DEFAULT
-d {file.uri}
--es org.ppsspp.ppsspp.Args "--pause-menu-exit"
-t application/octet-stream
--activity-clear-task  
--activity-clear-top  
--activity-no-history
```

Nothing seems out of the ordinary in adb logcat too.

**Comment by hrydgard** [comment]
Hm, that's very strange. I could make it take --ez arguments too, if you think that would help.. but I don't really undrestand why it wouldn't work.

**Comment by Jetup13** [comment]
Ya, I'm not sure too why its not doing it from a frontend. 

Here's the log if needed. 

<details>
<summary>ADB Log</summary>

12-14 14:18:24.184 32597 32597 D daijishou_debug: AmStart args: [-n, org.ppsspp.ppsspp/.PpssppActivity, -a, android.intent.action.VIEW, -c, android.intent.category.DEFAULT, --es, org.ppsspp.ppsspp.Args, "--pause-menu-exit", -d, content://com.android.externalstorage.documents/tree/primary%3Aroms%2FPSP/document/primary%3Aroms%2FPSP%2FWipEout%20Pure%20(USA)%20(En%2CFr%2CEs)%20(v2.00).cso, -t, application/octet-stream, --activity-clear-task, --activity-clear-top, --activity-no-history]
12-14 14:18:24.186   894  1514 I ActivityTaskManager: START u0 {act=android.intent.action.VIEW cat=[android.intent.category.DEFAULT] dat=content://com.android.externalstorage.documents/tree/primary:roms/PSP/document/primary:roms/PSP/WipEout Pure (USA) (En,Fr,Es) (v2.00).cso typ=application/octet-stream flg=0x54008001 cmp=org.ppsspp.ppsspp/.PpssppActivity (has extras)} from uid 10131, pid 32597
12-14 14:18:24.191   894  1514 I ActivityTaskManager: ->startActivity for ActivityRecord{495787 u0 org.ppsspp.ppsspp/.PpssppActivity t840} result:START_SUCCESS
12-14 14:18:24.196  1401 18017 I ForegroundAppMonitor: Current package: org.ppsspp.ppsspp
12-14 14:18:24.208   894  1901 D WindowManager:  update app focus from ActivityRecord{a8c22f3 u0 com.magneticchen.daijishou/.activities.MainActivity t838} to ActivityRecord{495787 u0 org.ppsspp.ppsspp/.PpssppActivity t840}
12-14 14:18:24.208   547   547 D vendor.unisoc.hardware.power-service: Enter getSceneIdByName: sceneName:org.ppsspp.ppsspp
12-14 14:18:24.215   529  1926 I gralloc4: allocate: id=21100000c87, hal_format=RGBA8888, mali_format=RGBA8888, afbc=false, usage=CPU_RW|GPU_R|HWC, size=1336x752, stride=1344, name=Splash Screen org.ppsspp.ppsspp#0
12-14 14:18:24.226   337   337 I PPSSPPNativeActivity: Ext files dir: /storage/emulated/0/Android/data/org.ppsspp.ppsspp/files
12-14 14:18:24.223   337   337 I androidInit: type=1400 audit(0.0:6663): avc: denied { getattr } for path="/mnt/media_rw/01D9039160859A10" dev="mmcblk1p1" ino=5 scontext=u:r:untrusted_app:s0:c2,c257,c512,c768 tcontext=u:object_r:unlabeled:s0 tclass=dir permissive=1 app=org.ppsspp.ppsspp
12-14 14:18:24.247   337   337 I PPSSPP  : EARLY: Reading '/data/user/0/org.ppsspp.ppsspp/files/memstick_dir.txt' to find memstick dir.
12-14 14:18:24.307   337   337 I chatty  : uid=10258(org.ppsspp.ppsspp) androidInit identical 1 line
12-14 14:18:24.329   337   337 I chatty  : uid=10258(org.ppsspp.ppsspp) androidInit identical 1 line
12-14 14:18:24.385   894  1901 I MediaFocusControl: requestAudioFocus() from uid/pid 10258/337 clientId=android.media.AudioManager@7428079org.ppsspp.ppsspp.AudioFocusChangeListener@10bc1be callingPack=org.ppsspp.ppsspp req=1 flags=0x0 sdk=33
12-14 14:18:24.393   337   337 D SensorManager: registerListenerImpl sensor = {Sensor name="Accelerometer Sensor", vendor="Sprd Group Ltd.", version=1, type=1, maxRange=78.45375, resolution=0.01, power=0.17, minDelay=10000}, delayUs = 20000, latencyUs = 0, listener = org.ppsspp.ppsspp.NativeSurfaceView{410ea04 V.E...... ......I. 0,0-0,0}
12-14 14:18:24.396   894  1251 I MediaFocusControl: requestAudioFocus() from uid/pid 10258/337 clientId=android.media.AudioManager@7428079org.ppsspp.ppsspp.AudioFocusChangeListener@10bc1be callingPack=org.ppsspp.ppsspp req=1 flags=0x0 sdk=33
12-14 14:18:24.401   337   337 I AudioTrack: start  mClientUid:10258 mClientPid:337  mSessionId:1089 app name:org.ppsspp.ppsspp
12-14 14:18:24.423   894 12654 I WindowManager: Input focus has changed to Window{f403657 u0 org.ppsspp.ppsspp/org.ppsspp.ppsspp.PpssppActivity}
12-14 14:18:24.423   894   913 D WindowManager: update input focus to Window{f403657 u0 org.ppsspp.ppsspp/org.ppsspp.ppsspp.PpssppActivity} , run:true
12-14 14:18:24.426   894  1514 D WindowManager: after addSurfaceViewPkg packageName = org.ppsspp.ppsspp count:1
12-14 14:18:24.428   529  1926 I gralloc4: allocate: id=21100000c89, hal_format=RGBA8888, mali_format=RGBA8888, afbc=SPLIT, usage=GPU_RW|HWC|BACKBUF, size=752x1336, stride=752, name=org.ppsspp.ppsspp/org.ppsspp.ppsspp.PpssppActivity#0
12-14 14:18:24.429   529  1926 I gralloc4: allocate: id=21100000c8a, hal_format=RGBA8888, mali_format=RGBA8888, afbc=SPLIT, usage=GPU_RW|HWC, size=752x1336, stride=752, name=SurfaceView - org.ppsspp.ppsspp/org.ppsspp.ppsspp.PpssppActivity#0
12-14 14:18:24.431   529  1926 I gralloc4: allocate: id=21100000c8b, hal_format=RGBA8888, mali_format=RGBA8888, afbc=SPLIT, usage=GPU_RW|HWC, size=752x1336, stride=752, name=SurfaceView - org.ppsspp.ppsspp/org.ppsspp.ppsspp.PpssppActivity#0
12-14 14:18:24.433   529  1926 I gralloc4: allocate: id=21100000c8c, hal_format=RGBA8888, mali_format=RGBA8888, afbc=SPLIT, usage=GPU_RW|HWC, size=752x1336, stride=752, name=SurfaceView - org.ppsspp.ppsspp/org.ppsspp.ppsspp.PpssppActivity#0
12-14 14:18:24.441   894   918 D ArtManagerInternalImpl: /data/misc/iorapd/org.ppsspp.ppsspp/116060347/org.ppsspp.ppsspp.PpssppActivity/compiled_traces/compiled_trace.pb doesn't exist
12-14 14:18:24.442   894   918 I ActivityTaskManager: Displayed org.ppsspp.ppsspp/.PpssppActivity: +250ms
12-14 14:18:24.452   894 20451 I InputDispatcher: Focus entered window: Window{f403657 u0 org.ppsspp.ppsspp/org.ppsspp.ppsspp.PpssppActivity} in display 0
12-14 14:18:24.457  1669  1669 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1894 onStartInput(EditorInfo{EditorInfo{packageName=org.ppsspp.ppsspp, inputType=0, inputTypeString=NULL, enableLearning=false, autoCorrection=false, autoComplete=false, imeOptions=0, privateImeOptions=null, actionName=UNSPECIFIED, actionLabel=null, initialSelStart=-1, initialSelEnd=-1, initialCapsMode=0, label=null, fieldId=-1, fieldName=null, extras=null, hintText=null, hintLocales=[]}}, false)
12-14 14:18:26.192   529  1926 I gralloc4: allocate: id=21100000c8d, hal_format=RGBA8888, mali_format=RGBA8888, afbc=SPLIT, usage=GPU_RW|HWC|BACKBUF, size=752x1336, stride=752, name=org.ppsspp.ppsspp/org.ppsspp.ppsspp.PpssppActivity#0
12-14 14:19:04.645   894  3899 I MediaFocusControl: abandonAudioFocus() from uid/pid 10258/337 clientId=android.media.AudioManager@7428079org.ppsspp.ppsspp.AudioFocusChangeListener@10bc1be
12-14 14:19:04.645   337   337 I AudioTrack: stop  mClientUid:10258 mClientPid:337  mSessionId:1089 app name:org.ppsspp.ppsspp
12-14 14:19:04.648   337   337 D SensorManager: unregisterListenerImpl sensor = null, listener = org.ppsspp.ppsspp.NativeSurfaceView{410ea04 V.E...... ........ 0,0-1336,752}
12-14 14:19:04.661   894  1514 D WindowManager:  update app focus from ActivityRecord{495787 u0 org.ppsspp.ppsspp/.PpssppActivity t840 f}} to ActivityRecord{a8c22f3 u0 com.magneticchen.daijishou/.activities.MainActivity t838}
12-14 14:19:04.667   894  1907 I InputDispatcher: Focus left window: Window{f403657 u0 org.ppsspp.ppsspp/org.ppsspp.ppsspp.PpssppActivity} in display 0
12-14 14:19:05.435   894 12654 D WindowManager: after removeSurfaceViewPkg packageName = org.ppsspp.ppsspp count:0
12-14 14:19:05.439   572   599 E BufferQueueProducer: [org.ppsspp.ppsspp/org.ppsspp.ppsspp.PpssppActivity#0](id:23c000001fb,api:0,p:-1,c:572) disconnect: not connected (req=1)

</details>
