### ISSUE TITLE
F-droid release: Cannot browse games on other drives (USB, microSD card) than the internal storage

### ISSUE THREAD

**Issue by davidhedlund** [hrydgard/ppsspp#18521]
### Game or games this happens in

*

### What area of the game / PPSSPP

*

### What should happen

* Add a game to a microSD card
* Insert the microSD card in the phone
* Start the phone
* Open PPSSPP. The Games tab that will pop-up. However, the microSD card icon (or other external devices) is not visible.

### Platform

Android

### Mobile phone model or graphics card

*

### PPSSPP version affected

1.1.1

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Don't open issues on ancient versions of PPSSPP please.

The f-droid release is not managed by the PPSSPP project, it's some volunteer who hasn't bothered to update it in a long time.

I just don't have time to manage yet another release platform.

**Comment by davidhedlund** [comment]
> Don't open issues on ancient versions of PPSSPP please.
> 
> The f-droid release is not managed by the PPSSPP project, it's some volunteer who hasn't bothered to update it in a long time.
> 
> I just don't have time to manage yet another release platform.

There's no contact information to any maintainer at https://f-droid.org/en/packages/org.ppsspp.ppsspp/. Instead, someone added your mail, github repo link, etc. Do you want me to request the F-Droid team to remove your mail?

Also, I found this https://gitlab.com/fdroid/fdroiddata/-/issues/2861, and it points to an open F-Droid package for request:
https://github.com/hrydgard/ppsspp/issues/9112

**Comment by davidhedlund** [comment]
* https://github.com/hrydgard/ppsspp/issues/9112

**Comment by hrydgard** [comment]
That's really not my problem. I have never interacted with f-droid in any way and I have no plans to.

I don't know who added those links, but it wasn't me or anyone affiliated directly with the project.

Please stop posting about f-droid.

**Comment by hrydgard** [comment]
Also I should clarify one thing. If you are willing to volunteer to maintain PPSSPP on f-droid, I'm fine with that, and that's the only f-droid discussion here I'm ok with.

**Comment by davidhedlund** [comment]
> That's really not my problem. I have never interacted with f-droid in any way and I have no plans to.
> 
> I don't know who added those links, but it wasn't me or anyone affiliated directly with the project.
> 
> Please stop posting about f-droid.



> That's really not my problem. I have never interacted with f-droid in any way and I have no plans to.
> 
> I don't know who added those links, but it wasn't me or anyone affiliated directly with the project.

I just submitted this to f-droid to avoid confusion: [Please add a F-droid data maintainance link on the app pages](https://gitlab.com/fdroid/fdroid-website/-/issues/766)

> 
> Please stop posting about f-droid.

Sure, I'll post to https://gitlab.com/fdroid/fdroiddata/ next time.

**Comment by davidhedlund** [comment]
It's amazing how stable your emulator is. I didn't know that the current f-droid version was released back in 2015 because it didn't crash even for high-end games.

Good work.
