### ISSUE TITLE
F-droid release: Display resolution (HW scaler) is not set to "Native device resolution"

### ISSUE THREAD

**Issue by davidhedlund** [hrydgard/ppsspp#18523]
### Game or games this happens in

*

### What area of the game / PPSSPP

*

### What should happen

Graphics -> Display resolution (HW scaler) is set to "2x PSP" which gives bad screen resolution. You have to set it to "Native device resolution" like in the Google Play release to make it look normal.

### Platform

Android

### Mobile phone model or graphics card

*

### PPSSPP version affected

1.1.1

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Don't open issues on ancient versions of PPSSPP please.

The f-droid release is not managed by the PPSSPP project, it's some volunteer who hasn't bothered to update it in a long time.

I just don't have time to manage yet another release platform.

**Comment by davidhedlund** [comment]
* https://github.com/hrydgard/ppsspp/issues/9112
