### ISSUE TITLE
Cpu thread affinity mask before Windows 11

### ISSUE THREAD

**Issue by GermanAizek** [hrydgard/ppsspp#18531]
### Problem

https://stackoverflow.com/questions/76317127/windows-11-thread-affinities-spanning-multiple-processor-groups-explicitly

Is there a problem in the project at the moment that on Windows new created thread does not use more than 64 logical cores? This is a very old problem that was solved after Windows 11, by default in Windows 11, thread using all logical processor groups, before it is necessary to manually assign mask all group logical processors to each new created thread.

More info in this my commit: https://github.com/OpenXRay/xray-16/pull/1514/commits/02aaaf9caa53ff6c8099f9e392f9f5be5162a9ef

### Platform

Any Windows

**Comment by hrydgard** [comment]
We don't use CPU affinity at all, so I'm not too worried about this. Also, 64 cores should be sufficient anyway :)

**Comment by unknownbrackets** [comment]
I actually tried a little back some affinity stuff for the software renderer.  It becomes more relevant on x86 with P/E cores.  AMD is doing that now too, but I don't know how that'll matter.  But anyway, we would use the new APIs.

-[Unknown]
