### ISSUE TITLE
GE Debugger crashes

### ISSUE THREAD

**Issue by Nemoumbra** [hrydgard/ppsspp#18569]
### Game or games this happens in

Not game-specific

### What area of the game / PPSSPP

The GE debugger menus can lead to crashes:

![image](https://github.com/hrydgard/ppsspp/assets/62447396/9937196c-0c23-467e-a6b4-efbe26ab7e90)

1) When the debugger is in this "uninitialized" state, a lot of global objects are not ready to be used, but the context menus expose an interface for using them. `CDCDCDCD` is the "address" that I've just copied from the first menu item. If I try to copy instruction, it'll make an unchecked read into a segfault. Or better yet, it can crash the game, because `ReadFromHardware` thinks it's only called from the emulation code.
![image](https://github.com/hrydgard/ppsspp/assets/62447396/2d13ba31-99a5-431f-8ca2-cf3fa7367472)

2) Even if the debugger is working, some parts of it may still be scary to use... For instance, this crashes because in `PreviewToClipboard(secondBuffer_, true);` the first argument is nullptr.
![image](https://github.com/hrydgard/ppsspp/assets/62447396/346bb686-b4a9-4cd6-ad61-99c184db4825)

### What should happen

We need some protection against the incorrect uses of the debugger. Perhaps, disable some context menu items, or maybe not just items, but the menus as a whole.
I don't know what checks need to be made for each of cases to work without crashes. I also don't want the code to resemble a patched blanket (stuff like "it shouldn't be nullptr by design at this point, but it somehow is, so let's make an early return if it's nullptr" instead of fixing the issue with it being uninitialized in the first place), so it has to be done carefully.

### Platform

Windows

### Mobile phone model or graphics card

AMD Radeon(TM) Graphics

### PPSSPP version affected

Self-built version (one of the lastest)

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [x] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
I think it's reasonable to do nullchecks for secondBuffer_ / primaryBuffer_ in the rightclick menu handlers. 

Since this debugger isn't really for end users, having items accidentally enabled but not doing anything is ok. Carefully adding enabling/disabling logic isn't really worth it here.

**Comment by Nemoumbra** [comment]
Load a game, then "step into" in the GE debugger, then F8 to resume the CPU, then copy image with alpha.
This sequence of actions is what I used to crash PPSSPP (Patapon 1 EU) again.

![image](https://github.com/hrydgard/ppsspp/assets/62447396/6cc0db91-20ec-432a-82ba-36a0102c377b)

It's because the `image->width` field is zero. And that is because `Save8888ARBGScreenshot` was called with `w` equal to zero.
The value of `w` comes from `ConvertBufferToScreenshot`:
```w = std::min(w, buf.GetStride());```
`w` is initially -1, but the stride is 0.

The PNG library assumes the width is not zero => I think it'd be wise to make a check in `Save8888ARBGScreenshot`.
