### ISSUE TITLE
DBZ Tenkaichi Tag Team: Textures disappear on modded maps

### ISSUE THREAD

**Issue by TagTeamEstudios** [hrydgard/ppsspp#18561]
### Game or games this happens in

ULUS10537 - Dragon Ball Z Tenkaichi Tag Team 

### What area of the game

Acontece nos

https://github.com/hrydgard/ppsspp/assets/106892701/40e12069-c249-497c-a6b4-1879a35a45ab

Anexarei um vídeo.

> Mapas que são editados por fãs, mapas mods. Os mapas originais não ocorrem esse bug apenas nos mapas que são mods. Observe o vídeo e verá os bugs nas texturas dos mapas.

Maps that are edited by fans, mod maps. This bug does not occur on original maps, only on maps that are mods. Watch the video and you will see the bugs in the map textures.

### What happens

>Bug na renderização das texturas dos mapas "Mods", do jogo Dragon Ball Z Tenkaichi Tag Team. Ao usar um mapa modificado no jogo, na gameplay as texturas dos mapas tendem a ficarem desaparecendo e reaparecendo conforme o personagem se movimenta na arena de batalha

Bug in the rendering of the textures of the "Mods" maps, from the game Dragon Ball Z Tenkaichi Tag Team. When using a modified map in the game, in gameplay the map textures tend to disappear and reappear as the character moves in the battle arena

![Screenshot_2023-12-16-16-57-56-059_org ppsspp ppsspp](https://github.com/hrydgard/ppsspp/assets/106892701/38117262-cc41-41a3-a033-94cb7c4f9504)
![Screenshot_2023-12-16-16-57-46-237_org ppsspp ppsspp](https://github.com/hrydgard/ppsspp/assets/106892701/f48fa274-e4e9-40a3-adba-6720f94140a7)
![Screenshot_2023-12-16-16-57-38-313_org ppsspp ppsspp](https://github.com/hrydgard/ppsspp/assets/106892701/50bb4e76-4d2a-4f61-a1c6-b8e506b9e4de)
![Screenshot_2023-12-16-16-57-30-251_org ppsspp ppsspp](https://github.com/hrydgard/ppsspp/assets/106892701/f3d58c29-0294-49bf-88e6-5989912edc57)

### What should happen

>Nas versões atuais do PPSSPP sempre acontece esse tipo de bug, porém, a versão do emulador 1.6.3 (A testada por mim), não acontece esse problema de texturas nos mapas mods, elas não desaparecem como nas versões atuais!

In current versions of PPSSPP this type of bug always occurs, however, in the emulator version 1.6.3 (the one tested by me), this problem with textures in mod maps does not occur, they do not disappear like in current versions!

### Platform

Android

### Mobile phone model or graphics card

Poco F4

### PPSSPP version affected

V1.16.x

### Last working version

V1.6.3

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [ ] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [x] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Please write issues in English. It's not practical to have multiple languages here - while I can guess my way through Portuguese thanks to a bit of Spanish knowledge, it slows things down.

Also, please take a "GE frame dump" exactly when there's a hole in the map. It's done like this: https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

**Comment by TagTeamEstudios** [comment]
Many thanks for the reply! I apologize in advance if my English seems strange as I am using the translator. Well, in the version I mentioned, which is version 1.6.3, this doesn't happen, it's absolutely perfect, I tested it just now in version 1.6.3 and the textures didn't disappear, I tested it on all maps, and all modified maps in version 1.6.3 they were perfect without this problem, but in the most current versions, all modified maps have this problem.

**Comment by TagTeamEstudios** [comment]
[ULUS10537_0001.zip](https://github.com/hrydgard/ppsspp/files/13693996/ULUS10537_0001.zip)

I did the dump I mentioned in "Debug/Debbuger GE/Actions/Record Next Frame.

I hope I did it correctly, I apologize in advance, as I'm a bit of a layman here.

**Comment by TagTeamEstudios** [comment]
> Por favor, escreva questões em inglês. Não é prático ter vários idiomas aqui - embora eu consiga adivinhar o português graças a um pouco de conhecimento de espanhol, isso torna as coisas mais lentas tanto para mim quanto para outros leitores.
> 
> Além disso, faça um "despejo de quadro GE" exatamente quando há um buraco no mapa. É feito assim: https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump
> 
> Eu adicionei tradução automática.
> 
> De qualquer forma, é muito provável que este seja um problema de seleção de alcance. Você sabe se isso também acontece com mapas modificados no PSP real? Desde 1.6.3, nossa emulação é mais precisa para o hardware, mas se os mods foram feitos para rodar em versões mais antigas, talvez eles não levassem essa peculiaridade em consideração. Uma maneira de consertar isso é provavelmente subdividir o solo em triângulos menores.

I don't have a physical console to test, however, I saw other people testing mods on the game and the maps remained without problems

**Comment by TagTeamEstudios** [comment]
In fact, just out of curiosity. Is there any way to fix it using the "compat.ini" file?
