### ISSUE TITLE
Trying to build for Raspberry Pi get cmake error

### ISSUE THREAD

**Issue by TotalCoolness** [hrydgard/ppsspp#18583]
### Platform

Raspberry Pi

### Compiler and build tool versions

Clang 14.0.6 / 3.25.1

### Operating system version

Debian GNU/Linux 12 (bookworm)

### Build commands used

 ./b.sh --rpi64

### What happens

Im trying to compile a binary for my raspberry pi 5. But I get this error when doing
 ./b.sh --rpi64

`CMake Error at cmake/Toolchains/raspberry.armv8.cmake:8 (message):
  RaspberryPI platform not recognized
Call Stack (most recent call first):
  /usr/share/cmake-3.25/Modules/CMakeDetermineSystem.cmake:124 (include)
  CMakeLists.txt:3 (project)

CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
`

### PPSSPP version affected

1.16.6

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] Make sure to run `git submodule update --init --recursive` before building.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try deleting the build directory and running the build again.
- [ ] Check GitHub Actions, which builds every merge and PR.
- [ ] Include logs and help us reproduce.

**Comment by sizmos** [comment]
Just facing the same issue, and looking at the cmake files for armv7 and v8, there are code blocks to cause it to break if it is anything other than a Raspberry Pi 4. Could probably update those, though not sure what other parts would need to be updated for the various Environment variables to support the Raspberry Pi 5/
https://github.com/hrydgard/ppsspp/blob/f65c84f4cb8117b273e7fa2ab578c95aedc6dd56/cmake/Toolchains/raspberry.armv7.cmake#L3-L9

**Comment by sizmos** [comment]
Tried updating the Model to `5` locally, though got an exception when linking at the last step:
```
[ 98%] Building CXX object CMakeFiles/PPSSPPSDL.dir/UI/RetroAchievementScreens.cpp.o
[100%] Linking CXX executable PPSSPPSDL
/usr/bin/arm-linux-gnueabihf-ld: ffmpeg/linux/aarch64/lib/libavformat.a: error adding symbols: file format not recognized
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/PPSSPPSDL.dir/build.make:715: PPSSPPSDL] Error 1
make[1]: *** [CMakeFiles/Makefile2:987: CMakeFiles/PPSSPPSDL.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Comment by TotalCoolness** [comment]
I did manage to compile it shortly after posting.
I cant remember what I did think it was:

Compile using ./b.sh --rpi64

If it doesn’t work:

Cmake .

Then

Make

**Comment by hrydgard** [comment]
OK, i'm gonna close then. if there are other issues or reasons to keep it open, post below.
