### ISSUE TITLE
Please replace "Mobile phone model or graphics card" with "Mobile device model or graphics card"

### ISSUE THREAD

**Issue by davidhedlund** [hrydgard/ppsspp#18594]
### What should happen
* Mobile devices can be both mobile phones (smartphones in this context) and tablets. PPSSPP can be installed on both smartphones and tablets.
* A chipset, also known as an SoC (System-on-a-Chip), is a single-integrated circuit (IC) that combines multiple electronic components into a single package. This typically includes the CPU (Central Processing Unit), GPU (Graphics Processing Unit), modem, Wi-Fi, and Bluetooth.

Thus, it would be consistent to replace "Mobile phone model or graphics card" with "Mobile device chipset or graphics card" in the [Bug, crash, or compatibility issue](https://github.com/hrydgard/ppsspp/issues/new?assignees=&labels=&projects=&template=bug.yml) template.

### Who would this benefit

It will protect people from giving out their phone model, which may be good for privacy reasons.

### Platform (if relevant)

None

### Games this would be useful in

-

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by anr2me** [comment]
> It will protect people from giving out their phone model, which may be good for privacy reasons.

Why would anyone want to hide the device model? especially when reporting bugs, it doesn't even shows their name or phone number.

One reason why we need the device models is because there could be more than one device that use the same SoC or GPU, and some of them might not shows the same symptoms (depends on their OS/kernel/driver or some other factors which can be varies on different model/brand)

**Comment by davidhedlund** [comment]
> > It will protect people from giving out their phone model, which may be good for privacy reasons.
> 
> Why would anyone want to hide the device model? especially when reporting bugs, it doesn't even shows their name or phone number.
> 
> One reason why we need the device models is because there could be more than one device that use the same SoC or GPU, and some of them might not shows the same symptoms (depends on their OS/kernel/driver or some other factors which can be varies on different model/brand)

Alright, but should not "Mobile phone" be replaced with "Mobile device" since PPSSPP can be installed on tablets too?

**Comment by davidhedlund** [comment]
Thank you, @hrydgard
