### ISSUE TITLE
Final fantasy type 0 strange character

### ISSUE THREAD

**Issue by IrfanH495** [hrydgard/ppsspp#18608]
### Game or games this happens in

NPJH50444 - FINAL FANTASY 零式 ディスク２

### What area of the game

after passing through a door or light
bolt opengl and vulkan

### What happens

![Screenshot_20231225-130311_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/f3137953-e8b4-4f99-87f5-12442542f108)
![Screenshot_20231225-130408_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/e43ea77a-fe8d-4513-9091-1840bb834327)

### What should happen

This was taken from PPSSPP Play Store version.
![Screenshot_20231225-124223_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/54854fb1-ce94-4aab-a688-db1a082a89e5)

### GE frame capture

I always fail to take it
![Screenshot_20231225-131240_ZArchiver](https://github.com/hrydgard/ppsspp/assets/78854859/d25f46f0-31af-4ef0-b932-9777029e3969)

### Platform

Android

### Mobile device model or graphics card (GPU)

samsung m20 & sharp sh04h

### PPSSPP version affected

i just tried the last build version,I will search it

### Last working version

1.16.6

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by IrfanH495** [comment]
I just found this
ppsspp-v1.16.6-620-gd9c6d0931-
![Screenshot_20231225-143017_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/48e5e3ac-570c-417d-b671-b83914539c0b)
![Screenshot_20231225-143027_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/240f952d-15c3-4038-9cd6-e02c9a6e8d9a)
ppsspp-v1.16.6-629-ga9553f4ee-
![Screenshot_20231225-143137_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/b7c10883-edd5-4c17-a4ce-c97bf6a1273e)
![Screenshot_20231225-143157_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/3d57d568-17eb-4f93-9c7b-7c80d3df8697)

sorry to disturb your holiday

**Comment by hrydgard** [comment]
Thanks, that's great that you narrowed it down! Almost certainly #18587  .. I'll fix it.
