### ISSUE TITLE
Add a title to the quick menu

### ISSUE THREAD

**Issue by davidhedlund** [hrydgard/ppsspp#18626]
### What should happen

# Current
![image](https://github.com/hrydgard/ppsspp/assets/6416073/de519c3e-4f45-46ee-a2a3-01b8d6ee284a)

# Suggested
![image](https://github.com/hrydgard/ppsspp/assets/6416073/06a8042e-6c1a-40d8-a0f1-0682ddbd81aa)

### Who would this benefit

It's more convenient for people to be able to identify the title of the window.

### Platform (if relevant)

None

### Games this would be useful in

*

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
Very small UI changes like this don't really need issue reports, start by taking them up in the development channel on the discord please. Or gather a number of small ideas into one issue.

**Comment by davidhedlund** [comment]
> Very small UI changes like this don't really need issue reports, start by taking them up in the development channel on the discord please.

Alright, but I don't use Discord, because it's proprietary software. I guess I could use https://forums.ppsspp.org/, but it would be nice if you set up an IRC channel. Have you considered it?

**Comment by davidhedlund** [comment]
> Also, I don't think this change is needed, we already have very limited space on mobile devices.

Just a suggestion but I respect if you still decline it: A very small font could be used.
