### ISSUE TITLE
Suggestion: Video demonstration of PPSSPP on a smartphone connected to a second screen

### ISSUE THREAD

**Issue by davidhedlund** [hrydgard/ppsspp#18623]
### Who would this benefit

It would be nice with a  published a video on https://www.ppsspp.org/ where a smartphone is connected to a TV with a USB-C to DisplayPort or HDMI cable, or perhaps with a USB multiport hub that has a PD port that will charge the phone.

This setup can be used to play PPSSPP while you are on vaccation. For example if you have rent a hotel room that has a TV, or to introduce PPSSPP to a friend that you are visiting.

Check this video for example: https://www.youtube.com/watch?v=pHG3pDFyuOE 

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
Website suggestions belong on the website issue tracker:

https://github.com/hrydgard/ppsspp-site/issues

**Comment by davidhedlund** [comment]
> Website suggestions belong on the website issue tracker:
> 
> https://github.com/hrydgard/ppsspp-site/issues

Sorry:
* https://github.com/hrydgard/ppsspp-site/issues/23
