### ISSUE TITLE
Midnight Club L.A. Remix sun flare goes through solid objects

### ISSUE THREAD

**Issue by SixelAlexiS90** [hrydgard/ppsspp#18625]
### Game or games this happens in

ULES-01144 - Midnight Club L.A. Remix | ULUS-10383 - Midnight Club L.A. Remix

### What area of the game

The sun flare goes through solid objects no metter the position or time of day, light in bright day or sunset.
In this case I've took screenshots right after the garage in sunset time.
I've tested it with all backend and it's the same, while it doesn't happen in "Software rendering".

Any Graphics backend (D11 in this case):

![Screenshot (3470)](https://github.com/hrydgard/ppsspp/assets/63536218/74558a57-96f9-446f-bfc5-842e002ee395)

Software rendering:

![Screenshot (3469)](https://github.com/hrydgard/ppsspp/assets/63536218/f873c94b-7821-402b-8d9a-6f5e897b1bda)

### What happens

The sun flare goes through solid objects.

Any Graphics backend (D11 in this case):

![Screenshot (3470)](https://github.com/hrydgard/ppsspp/assets/63536218/74558a57-96f9-446f-bfc5-842e002ee395)

### What should happen

The sun flare should be blocked by solid objects, like it's seen via the "Software rendering":

![Screenshot (3469)](https://github.com/hrydgard/ppsspp/assets/63536218/f873c94b-7821-402b-8d9a-6f5e897b1bda)

### GE frame capture
[ULES01144_lensflare2.zip](https://github.com/hrydgard/ppsspp/files/13789153/ULES01144_lensflare2.zip)

[ULES01144000.zip](https://github.com/hrydgard/ppsspp/files/13788737/ULES01144000.zip)

### Platform

Windows

### Mobile device model or graphics card (GPU)

NVIDIA GeForce RTX 2060

### PPSSPP version affected

v1.16.6-688-g62019c9a9

### Graphics backend (3D API)

Other

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Could you get a GE frame dump of exactly this position? See https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

**Comment by hrydgard** [comment]
Additionally, this is another case of #15923 , adding it to the list.

**Comment by SixelAlexiS90** [comment]
> Could you get a GE frame dump of exactly this position? See https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

Done, let me know if I didn't messed up :'D

**Comment by hrydgard** [comment]
Hm, that GE dump is only 1kb and empty, sometimes that happens depending on frame timing and so on. Try a couple more times, it should be at least a few hundred kb if valid...

**Comment by hrydgard** [comment]
Turns out that ca94de8d4b1e53b7d596d31e7336ac5133a32a7c broke frame dumps. Fix coming up.

**Comment by hrydgard** [comment]
Both in software renderer and hardware renderer, the flare draw is performed. The only difference seems to be vertex colors:

![image](https://github.com/hrydgard/ppsspp/assets/130929/8bd6674c-b97f-447e-bdde-67671ffd5ffc)

hardware:

![image](https://github.com/hrydgard/ppsspp/assets/130929/4dd1ff15-7a2b-4df6-902b-c2ab1a5c916d)

The vertex data is coming from RAM so it seems the CPU is involved in detecting the coverage, or at least writing the result. So this might be one of the depth-buffer-peeking games, not confirmed yet though.

**Comment by hrydgard** [comment]
There's some strange stuff going on with the framedumps. the hw one doesn't fully render in software, it seems to stop halfway through, while it renders fine on hw. 

Loading a savestate with the flare visible into software fades the lens flare out gradually.

**Comment by SixelAlexiS90** [comment]
@hrydgard Hello and happy new year 💯 !
I've find out a similar issue about street lights as well. 
When you drive on high roads you will see all street lights through them, see here:

![Screenshot (3498)](https://github.com/hrydgard/ppsspp/assets/63536218/63ab4d40-e0a0-4243-8763-fa536727d8e8)

It doesn't happen in software mode (I've tested it on real hardware as well, it's the same):

![Screenshot (3503)](https://github.com/hrydgard/ppsspp/assets/63536218/18bccc89-74be-4785-a99e-430de73e7826)

Here a GE frame dump done in this spot:

[ULES01144_0012.zip](https://github.com/hrydgard/ppsspp/files/13804230/ULES01144_0012.zip)

And a save state as well:

[MCLARemixEU - City lights through highway.zip](https://github.com/hrydgard/ppsspp/files/13804241/MCLARemixEU.-.City.lights.through.highway.zip)

Btw these are the city light you see through the highway:

![Screenshot (3508)](https://github.com/hrydgard/ppsspp/assets/63536218/3927131b-90ac-4e36-9ad9-1deb9b6a3ad1)

GE frame dump done in this spot:

[ULES01144_0012.zip](https://github.com/hrydgard/ppsspp/files/13804247/ULES01144_0012.zip)

A save state for this spot as well, maybe it will help:

[MCLARemixEU - City lights on ground level.zip](https://github.com/hrydgard/ppsspp/files/13804251/MCLARemixEU.-.City.lights.on.ground.level.zip)


Let me know if it's fine to leave all of this here or I need to modify the title/make a different report about it :)

**Comment by hrydgard** [comment]
Absolutely fine to leave it all here, it's very likely to be the same issue.

**Comment by hrydgard** [comment]
I've confirmed that #19748 together with its upcoming followup changes is going to fix this. It needs more performance work first, though.

**Comment by SixelAlexiS90** [comment]
> I've confirmed that #19748 together with its upcoming followup changes is going to fix this. It needs more performance work first, though.

Hi! First of all thank you for this update, amazing job on the emulator as always!
I've tested the `v1.18.1-522-g4b4d30e587` and I can confirm that both the sun and street lights aren't visible anymore behind buildings/roads!

Then I noticed something weird, the car lights still showed up under the roads:

https://github.com/user-attachments/assets/c72b0485-0e78-4b82-8ebe-f2af4d335523


So I checked on a real PSP to be sure it wasn't a game issue and the car lights gets under the road on a real PSP as well for some reasons :'D

https://github.com/user-attachments/assets/b3be6d64-b81b-45eb-a2e2-4d7a9b401b02


I wanted to put it here to document it for any eventual future report on this "issue" that's in reality a game's issue.

Let me know if you need more info/testing and thank you again for this update!

**Comment by hrydgard** [comment]
Great! I assume you added the game to compat.ini manually? because it shouldn't have been enabled yet :) (though I'll enable it soon, together with a "speed hack" to turn if off if needed).

**Comment by SixelAlexiS90** [comment]
> Great! I assume you added the game to compat.ini manually? because it shouldn't have been enabled yet :) (though I'll enable it soon, together with a "speed hack" to turn if off if needed).

Yes, I've put the MC:LA list that was already available in the compat.ini and placed it under `[SoftwareRasterDepth]` like this:

```
[SoftwareRasterDepth]
# Midnight Club: LA Remix
ULUS10383 = true
ULES01144 = true
ULJS00180 = true
ULJS00267 = true
ULJM05904 = true
NPJH50440 = true
```
Without it the sun and street lights were still clipping of course.
Good to know about future features :'D

**Comment by hrydgard** [comment]
Great!

Now it's enabled by default.
