### ISSUE TITLE
Suggestion: Rename "Pause" to "Quick Menu"

### ISSUE THREAD

**Issue by davidhedlund** [hrydgard/ppsspp#18624]
### What area of the game / PPSSPP

Settings - Controls - Control mapping: Pause:

![image](https://github.com/hrydgard/ppsspp/assets/6416073/a40f4784-f353-4447-8c10-95695dc7d741)

It looks like this when it's activated:
![image](https://github.com/hrydgard/ppsspp/assets/6416073/6d73140d-641e-49e8-8c3c-96198983ae8f)

So I suggest that you rename "Pause" to "Quick Menu", because when you activate the entry you will access so many features. Also, in RetroArch this area is called "Quick Menu".

You could start by renaming it to "Quick Menu/Pause" and then change it to just "Quick Menu" after a few versions so people get the chance to recognize the change.

It took me a while of experimentation to figure out how to remap the menu button, since it is titled Pause.

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by LunaMoo** [comment]
How about not copying naming of functions we had since the beginning from an awfuly bloated gui for a third party project which leeches it's existence from many proper emulator projects?

**Comment by hrydgard** [comment]
Regardless of the merits of retroarch which I don't think we need to debate in the issue tracker, there's no need to copy all naming from it. Pause is fine.

**Comment by davidhedlund** [comment]
> How about not copying naming of functions we had since the beginning from an awfuly bloated gui for a third party project which leeches it's existence from many proper emulator projects?

I just referred to it as "Quick Menu", but just "Menu" would be an improvement in my opinion, because it does more than just pause.

**Comment by davidhedlund** [comment]
> How about not

How about growing up and response in a polite way to strangers?

**Comment by davidhedlund** [comment]
> Regardless of the merits of retroarch which I don't think we need to debate in the issue tracker, there's no need to copy all naming from it. Pause is fine.

 My final suggestion: "Pause menu"

**Comment by davidhedlund** [comment]
The Pause entry is a hotkey, not an emulator hardware button for the PSP. It would be less confusing if the Pause button was placed under a "Hotkey" sub-section in the Control mapping, don't you think so? @hrydgard
