### ISSUE TITLE
Breath of Fire III has started flickering

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#18649]
Just a reminder to self to fix it soon. It now flickers, a bisect should find it easily.

**Comment by hrydgard** [comment]
Oops, faulty testing, only in #18646 . Odd.

**Comment by Unknowncat1991** [comment]
I can now reproduce this issue also switching backend while ingame can instantly crashing ppsspp.
Currently using the latest build https://github.com/hrydgard/ppsspp/pull/21859

**Comment by Unknowncat1991** [comment]
https://github.com/user-attachments/assets/b9d0384e-534b-4208-a418-be2a06ae4dc9
ppsspp v1.20.4-450
