### ISSUE TITLE
i beat the game, with fast memory checked, and no changes in clock speed..

### ISSUE THREAD

**Issue by Knownnonymous** [hrydgard/ppsspp#18641]
i beat the game, with fast memory checked, and no changes in clock speed..

Tip: install the latest git build for ppsspp
don't save your game in ppsspp buggy save states instead in game save and when you are jumping in "noa" you should backward a little and facing the left, then jump.. and after that no issues will arise. 

_Originally posted by @Knownnonymous in https://github.com/hrydgard/ppsspp/issues/14958#issuecomment-1872103712_

**Comment by hrydgard** [comment]
Sorry, is there a problem? What game? This isn't a discussion forum, it's an issue tracker.

**Comment by Knownnonymous** [comment]
I am sorry, I was just trying to reference a tip resolution for GOW, and accidentally made this...
