### ISSUE TITLE
Libretro Android Vulkan crash

### ISSUE THREAD

**Issue by lim2222** [hrydgard/ppsspp#18656]
### Game or games this happens in

Every games 

### What area of the game / PPSSPP

Every games crashed with vulkan backend.

### What should happen

Shouldn't crash

### Platform

Android

### Mobile device model or graphics card (GPU)

Xiaomi 10t android 10

### PPSSPP version affected

4b027bae 

### Last working version

74a33ab9

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by anr2me** [comment]
Does other backends works fine?
I don't see anything related to Vulkan between `v1.16.6-703-g74a33ab98` and `v1.16.6-710-g4b027baeb`

**Comment by lim2222** [comment]
Gles works fine,and miui give me some this in the crash log.

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/apollopro_global/apollo:10/QKQ1.200419.002/V12.0.11.0.QJDMIXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2024-01-02 08:03:29+0800
pid: 28353, tid: 28397, name: Thread-3  >>> com.retroarch <<<
uid: 10285
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x30
Cause: null pointer dereference
    x0  0000000000000000  x1  0000000000000000  x2  0000007d9361f204  x3  0000000000000000
    x4  ffffffffffffffff  x5  0000007d3744c370  x6  0000007e264a8000  x7  000000000135f288
    x8  0000000000000000  x9  0000000300000000  x10 0000000000000001  x11 0000000000000000
    x12 000000003b9aca00  x13 00000000659352d1  x14 0000000000000001  x15 0000150473d532e6
    x16 0000007e22279c70  x17 0000007e234dfd9c  x18 0000007d361fa000  x19 0000007d9361f204
    x20 0000007d4329dbc0  x21 0000007d4329e1e8  x22 0000000000000000  x23 0000000000000000
    x24 00000002fffffffc  x25 0000007e2381e028  x26 0000007d93620018  x27 0000007d9361f178
    x28 00000000ffffffff  x29 0000007d9361f1f0
    sp  0000007d9361f150  lr  0000007e222731b0  pc  0000007e222731b0

backtrace:
    NOTE: Function names and BuildId information is missing for some frames due
    NOTE: to unreadable libraries. For unwinds of apps, only shared libraries
    NOTE: found under the lib/ directory are readable.
      #00 pc 00000000000241b0  /system/lib64/libvulkan.so (vulkan::driver::GetPastPresentationTimingGOOGLE(VkDevice_T*, VkSwapchainKHR_T*, unsigned int*, VkPastPresentationTimingGOOGLE*)+560) (BuildId: b25b8c943a2fd672457aac6e4fe0ad03)
      #01 pc 0000000000880e04  /data/data/com.retroarch/cores/ppsspp_libretro_android.so
      #02 pc 000000000088104c  /data/data/com.retroarch/cores/ppsspp_libretro_android.so
      #03 pc 0000000000878fa4  /data/data/com.retroarch/cores/ppsspp_libretro_android.so
      #04 pc 000000000051e408  /data/data/com.retroarch/cores/ppsspp_libretro_android.so
      #05 pc 000000000051e040  /data/data/com.retroarch/cores/ppsspp_libretro_android.so
      #06 pc 00000000009481e4  /data/app/com.retroarch-zZdC3B1EAAnn5SPEJltnJA==/lib/arm64/libretroarch-activity.so (core_run+196) (BuildId: cb333c2003a7b0ebb58a67ffb3d6a17c3261d89f)
      #07 pc 000000000093ce08  /data/app/com.retroarch-zZdC3B1EAAnn5SPEJltnJA==/lib/arm64/libretroarch-activity.so (runloop_iterate+12124) (BuildId: cb333c2003a7b0ebb58a67ffb3d6a17c3261d89f)
      #08 pc 0000000000939b08  /data/app/com.retroarch-zZdC3B1EAAnn5SPEJltnJA==/lib/arm64/libretroarch-activity.so (rarch_main+692) (BuildId: cb333c2003a7b0ebb58a67ffb3d6a17c3261d89f)
      #09 pc 0000000000a92d88  /data/app/com.retroarch-zZdC3B1EAAnn5SPEJltnJA==/lib/arm64/libretroarch-activity.so (BuildId: cb333c2003a7b0ebb58a67ffb3d6a17c3261d89f)
      #10 pc 000000000097f874  /data/app/com.retroarch-zZdC3B1EAAnn5SPEJltnJA==/lib/arm64/libretroarch-activity.so (BuildId: cb333c2003a7b0ebb58a67ffb3d6a17c3261d89f)
      #11 pc 00000000000e7480  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+36) (BuildId: 6dc18c350dc6bdab66bd0af0dcfd6e4c)
      #12 pc 000000000008522c  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 6dc18c350dc6bdab66bd0af0dcfd6e4c)

**Comment by lim2222** [comment]
Fixed by 7f2885e0
Thanks
