### ISSUE TITLE
Standalone PPSSPP flatpak on Steam Deck showing blank squares instead of Japanese characters

### ISSUE THREAD

**Issue by sweetsosweet** [hrydgard/ppsspp#18659]
### Game or games this happens in

none and NPJH50459 v1.01

### What area of the game / PPSSPP

Either in the save game data or when trying to name a new character, I only get blank squares in the translated version of 7th Dragon 2020 instead of English/Japanese text. It works fine on Android as well as in the PPSSPP core for retroarch on Steam Deck, but in the standalone app it only shows empty squares.

I've added the font files to the asset folder. Before adding this my list of UI languages under system settings was only English, and after adding this it populated multiple languages, however the language is still black squares even in the UI. 

When I switch to Japanese (I think) from this list the system starts loading very slowly until I switch back to English. 

I'm not sure if this is system related, because I can see Japanese text in the actual JP ini file, but it just doesn't show up in the standalone app. Not sure what I may be doing wrong. 

Also note I would prefer to use the standalone so I can use the same savestates across my android devices and Steam Deck.

Here are some screenshots from the Deck:

![Screenshot_20240101_122802](https://github.com/hrydgard/ppsspp/assets/15041593/64cc1858-adb9-4972-b7d5-3760b905fb43)
![Screenshot_20240101_120221](https://github.com/hrydgard/ppsspp/assets/15041593/65fe8608-6aad-42f2-ad63-68151f1da999)
![Screenshot_20240101_120313](https://github.com/hrydgard/ppsspp/assets/15041593/582e0240-6801-4f99-ae10-76e2a60a0b0f)
![Screenshot_20240101_120323](https://github.com/hrydgard/ppsspp/assets/15041593/b91081fe-d86c-4516-b9ac-8515813e8139)
![Screenshot_20240101_120346](https://github.com/hrydgard/ppsspp/assets/15041593/2459961e-1df8-4d5d-ac5f-d3f9c3c52111)

Here is a screenshot from the Retroarch core on Steam Deck (Edited to add):

![Screenshot_20240101_123605](https://github.com/hrydgard/ppsspp/assets/15041593/a982c049-c2e8-4a3d-8d99-55012e0b403b)

Here are some screenshots from Android for comparison:

![Screenshot_20240101-115631](https://github.com/hrydgard/ppsspp/assets/15041593/076281c7-6adc-469e-b41b-2ffd4af98acf)
![Screenshot_20240101-120417](https://github.com/hrydgard/ppsspp/assets/15041593/0627b7a5-6697-4743-a454-76abf22a53bc)
![Screenshot_20240101-120428](https://github.com/hrydgard/ppsspp/assets/15041593/8e38df33-cb81-49e2-a4ac-85bb6afd21a9)

### What should happen

The Japanese text should be in Japanese, but only shows open squares

### Platform

Linux / BSD

### Mobile device model or graphics card (GPU)

Steam Deck

### PPSSPP version affected

v1.16.6

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
I think this is the same issue with the flatpak as #18474

**Comment by sweetsosweet** [comment]
Oh I see thank you, I couldn't find the same issue in a search...

**Comment by sweetsosweet** [comment]
Wanted to add that I do have the fonts installed by default on my system, hope there's a fix soon:

![Screenshot_20240101_131728](https://github.com/hrydgard/ppsspp/assets/15041593/839f500a-7ce3-402e-89c5-bfd3e7124b6b)

**Comment by Mr-Beacon00** [comment]
try to replace default ttf font?
it's located in /var/lib/flatpak/app/org.ppsspp.PPSSPP/x86_64/stable/"numbers"/files/share/ppsspp/assets/Roboto-Condensed.ttf

**Comment by LunaMoo** [comment]
Roboto-Condensed.ttf doesn't contain japanese we use inside PPSSPP UI and changing it will not do much, we generate japanese font from ARIALUNI.ttf into font_atlas.zim where it's used from, possibly someone generated the font atlas without having that font and potentially used replacement which is missing kanji or maybe even removed unicode fonts altogether.

 Flatpack isn't really official release, and not sure about it's changes and limitations, but if that's possible within your platform, try copying assets from official release. or generate new font_atlas adding your choice of japanese font.

**Comment by hrydgard** [comment]
@LunaMoo I don't think that's what's happening. If the current platform appears to support "native" font rendering (or rather, if we have written support for it, which we have for Linux now), we don't use the atlas for general text rendering at all, instead we render text block by text block and cache them. 

Unfortunately it seems that one some systems we fail to pick a font that has the symbols we need when doing this, or we fail in some other way and fall back to just the small atlas. Not sure what the case is here.

**Comment by LunaMoo** [comment]
Isn't flatpak "sandboxed" which would make system fonts unavailable?

**Comment by LunaMoo** [comment]
Maybe this: https://github.com/NixOS/nixpkgs/issues/119433

**Comment by Mr-Beacon00** [comment]
![Ubuntu 64 位-2024-01-03-15-26-32](https://github.com/hrydgard/ppsspp/assets/73895438/95904c8b-262b-4f4c-9602-20a7f069eaf6)
I don't have Steam Deck, but i test it on Ubuntu. replaced default font with japanese font. at least UI text is okay now.

**Comment by hrydgard** [comment]
I think it's the font detection that isn't working then...  

See USE_SDL2_TTF_FONTCONFIG in the code, I guess if that isn't set in the build, we won't detect fonts properly.

**Comment by kaishin** [comment]
I have the same issue on both Steam Deck and Pop_OS! 
Happy to help with testing or providing additional details.

**Comment by thesourcehim** [comment]
I have the same issue with UI in Fedora 39, built from source, not flatpack. I see the following in font_atlasscript.txt:
font UBUNTU24 C:/Windows/Fonts/ARIALUNI.ttf UWEhkcRGHKVTe 30 0

So does this mean if I build under linux, I can't have unicode fonts? I have ARIALUNI.ttf, but build system does not look for it?

**Comment by hrydgard** [comment]
@thesourcehim I think there's just something screwed up in the build process for flatpaks, leading us to not look for fonts properly. Because this does work on plain linux when self-built.

**Comment by thesourcehim** [comment]
But I build from source using b.sh (release 1.16.6), I don't use flatpack, and yet Japanese characters are broken. I have Microsoft fonts installed and configured in fontconfig. Text editors and other office applications can use them.

**Comment by hrydgard** [comment]
might be that you have to install sdl2-ttf, and then build..

**Comment by thesourcehim** [comment]
I have it installed along with it's development package:
SDL2_ttf-2.20.2-2.fc39.x86_64
SDL2_ttf-devel-2.20.2-2.fc39.x86_64

Can I gather some verbose build log to see what goes wrong?

**Comment by hrydgard** [comment]
In https://github.com/hrydgard/ppsspp/pull/18732 I'm adding "Droid Sans Fallback" to the list of fonts we try to load. This seems to be present on a very regular Ubuntu install, and can easily be installed as described in the PR if not.

can someone check if this font is pre-installed on Steam Deck?

**Comment by sweetsosweet** [comment]
Doesn't look like it's on Steam Deck by default I think?

![Screenshot_20240119_182301](https://github.com/hrydgard/ppsspp/assets/15041593/f4f3f979-17fe-412f-92c3-be552d643d3f)

**Comment by hrydgard** [comment]
Hm, ok. But presumably we can figure out one that will work if we add it to the list. Though, it does feel like there should be a better way to do this..

@sweetsosweet can you check which one of these fonts are quite large on disk? Or see if there's another one named something like Fallback.

**Comment by sweetsosweet** [comment]
Ok, I couldn't find anything including Fallback, and most fonts are a few hundred kbs. I found the Noto fonts are all very large though, 16-25 mbs:

![Screenshot_20240119_213607](https://github.com/hrydgard/ppsspp/assets/15041593/c7b2b505-9ca8-494e-a7cd-ad81cb563532)

/usr/share/fonts/TTF/DejaVuSans.ttf is about 740kb

**Comment by thesourcehim** [comment]
Just tested with [9fdcef9](https://github.com/hrydgard/ppsspp/commit/9fdcef9a0f11f6d3fdd74a5d7c1c753f96209195)
My UI problem is solved, Japanese characters are ok.

**Comment by hrydgard** [comment]
Thanks for testing. I'm gonna close this, please re-open if it happens again (I dunno, maybe they change the names for the font files...)
