### ISSUE TITLE
I can't see the controls without a game running

### ISSUE THREAD

**Issue by DmdHoH000** [hrydgard/ppsspp#18652]
### Game or games this happens in

All games

### What area of the game / PPSSPP

When I try to configure the controls without having a game running, the buttons don't appear
![Screenshot_20231230-195011](https://github.com/hrydgard/ppsspp/assets/44216669/a855eb5c-1d61-44ae-889d-3b81e6233b5a)

### What should happen

I can only configure the controls with a game running
![Screenshot_20231230-202030](https://github.com/hrydgard/ppsspp/assets/44216669/69486adc-3200-43e1-b3bd-594bc270c2f6)

### Platform

Android

### Mobile device model or graphics card (GPU)

Lg k40s

### PPSSPP version affected

v1.16.6-751-gde0d82d02

### Last working version

v1.16.6-714-g5b0e82115

### Graphics backend (3D API)

Other

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Oh, thanks for reporting. I'll fix it shortly.
