### ISSUE TITLE
We could map right analog to left analog 

### ISSUE THREAD

**Issue by Narugakuruga** [hrydgard/ppsspp#18658]
### What should happen

![Screenshot_2024-01-02-00-32-41-167_org ppsspp ppsspp](https://github.com/hrydgard/ppsspp/assets/31060534/37e99561-59cd-45f2-b7af-2ff8deb4b29c)
Right analog stick can combine with one long press key, therefore in games that requires left analog with key pressed to perform actions, it's convenient to use right analog instead. 

### Who would this benefit

Touch screen user 

### Platform (if relevant)

None

### Games this would be useful in

Monster hunter series, GTA series 

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
#19327 should be good enough, closing.
