### ISSUE TITLE
CHD files not fetching RetroAchievement hash [RetroArch Core]

### ISSUE THREAD

**Issue by TheRhysWyrill** [hrydgard/ppsspp#18679]
### Game or games this happens in

All

### What area of the game / PPSSPP

When loading a game known to have achievements they don't appear to load and when checking file information the Hash is simply `N/A`.

### What should happen

For achievements to load as they would when using an ISO file.

### Platform

Linux / BSD

### Mobile device model or graphics card (GPU)

Radeon 680m

### PPSSPP version affected

RetroArch Core 0f01aa6

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
This is a bug in retroarch / rcheevos, not in PPSSPP. I think it's just that retroarch doesn't know that PSP games can be chd yet, and thus falls back to just hashing the first 64MB which will be wrong.

@Jamiras I think we talked about this once, maybe in the context of CSOs?

**Comment by Jamiras** [comment]
Yea. rcheevos was updated to allow for that on 7 October, and that, and that was merged into RetroArch on 2 Nov via #15859, so it should work in any nightly after 2 Nov. There hasn't been an official release yet since then.

**Comment by hrydgard** [comment]
Alright, I'll close this as fixed then since it's been fixed in code, just not in an official release yet.
