### ISSUE TITLE
Unable to set-read from external memory as game folder

### ISSUE THREAD

**Issue by hispanico957** [hrydgard/ppsspp#18675]
### Game or games this happens in

Games

### What area of the game / PPSSPP

Selectin game folder

### What should happen

On the new FireStick 4K Max (2* gen 2023) it is not possible to set the external memory of the USB stick as the games folder. 
I think it's due to an Android restriction. Is there a way to overcome this limit?
I arrive always here and i cannot select USB Stick..only internal folder

### Platform

Android

### Mobile device model or graphics card (GPU)

NVidia Shield PRO

### PPSSPP version affected

1.16.6

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Probably related to, or the same as, #16865 ..

**Comment by hispanico957** [comment]
Yes mate thank for reply, more or less is the same....but is related on
version of Android, others emu as Dolphin show same problem.
For your infromation i think that the problme it concerns the use of the
Android file explorer which does not allow (privacy) reading from USB
sticks or external disks.
it concerns the use of the Android file explorer which does not allow
(privacy) reading from USB sticks or external disks.
From the tests I have done, this does not happen for example with RetroArch
emu which in fact does not use the Android explorer but its own explorer to
search for the path of the games and this problem does not arise.
I hope you find a solution
Thank and good day

*Marco Silvestrini   *

***@***.*** ***@***.***>*

*Questo messaggio contiene informazioni riservate e privilegiate destinate
soltanto per l'uso dei singoli, o entità sopra citati. Se il lettore di
questo messaggio non è il destinatario, siete avvertiti del fatto che ogni
divulgazione non autorizzata, la copia, la distribuzione o l'assunzione del
contenuto di questo messaggio è severamente proibito. Se avete ricevuto
questo messaggio per errore, vi prego di informarmi immediatamente per
telefono al numero 335.352093 o per mail.** Prima di stampare, pensa
all'ambiente.*



Il giorno lun 8 gen 2024 alle ore 23:19 Henrik Rydgård <
***@***.***> ha scritto:

**Comment by hrydgard** [comment]
We now have a solution for annoying problems like this, although you'll have to install an APK: The [legacy edition](https://www.ppsspp.org/docs/reference/legacy-edition/).

Not sure if there's anything better we can do..
