### ISSUE TITLE
Exit Hotkey

### ISSUE THREAD

**Issue by dragoonDorise** [hrydgard/ppsspp#18674]
### What should happen

PPSSPP is missing the ability to be closed using a hotkey. You can do this in windows with ALT F4, but in Linux PPSSPP just ignores both ATL F4 or CTRL Q.

### Who would this benefit

Everybody.

### Platform (if relevant)

Linux / BSD

### Games this would be useful in

All

### Other emulators or software with a similar feature

Citra, Retroarch, Dolphin, Duckstation, RPCS3, Yuzu, ScummVM, Vita3K, Xemu

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
![image](https://github.com/hrydgard/ppsspp/assets/130929/fb6a6e1b-6306-4e91-bc9d-072f55afecec)

This functionality already exists in Control Bindings.
