### ISSUE TITLE
Binding Analog speed crashes emu on latest dev build

### ISSUE THREAD

**Issue by NABN00B** [hrydgard/ppsspp#18689]
### Game or games this happens in

None

### What area of the game / PPSSPP

When assigning an analog stick to the Analog speed control option, the emulator crashes when backing out of the control rebind menu.

### What should happen

Emulator shouldn't crash.

### Platform

Windows

### Mobile device model or graphics card (GPU)

NVIDIA GeForce GTX 1060 3GB (driver 545.84.0.0)

### PPSSPP version affected

v1.16.6-820-gb86e190e5

### Last working version

1.16.6

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
That's bad, I'll take a look very soon.

**Comment by NABN00B** [comment]
Some more info, don't know if they're helpful (probably not)
- used DualShock 4, tried to bind it to Right Analog stick that had already been bound to adequate right analog controls (made sure to test this in 1.16.6 release and this wasn't an issue there)
- happened regardless whether a game had been launched or not
