### ISSUE TITLE
Harvest Moon: Hero of Leaf Valley: Wrong in-game date on native save file

### ISSUE THREAD

**Issue by justafella** [hrydgard/ppsspp#18687]
### Game or games this happens in

ULUS-10458 - Harvest Moon Hero of Leaf Valley

### What area of the game / PPSSPP

Save file data shows in-game date of the very first time it was saved in that slot.

Native save info:
![Screenshot_2024-01-13-12-37-08-452_org ppsspp ppsspp](https://github.com/hrydgard/ppsspp/assets/65559598/e20b2599-be3a-4fd3-8b0f-a537b64f66ca)

Save state info:
![Screenshot_2024-01-13-12-37-14-735_org ppsspp ppsspp](https://github.com/hrydgard/ppsspp/assets/65559598/af3e8f16-e4c1-4224-b242-c42af5ab02bf)

Native save file for testing:
[ULUS10458_SUGARMIN_0001.zip](https://github.com/hrydgard/ppsspp/files/13928916/ULUS10458_SUGARMIN_0001.zip)

Native save loads correctly on Year 1 Summer 7, but still show Year 1 Spring 21 on save file manager

### What should happen

Should show actual date on save file manager

### Platform

Android

### Mobile device model or graphics card (GPU)

Redmi 9 (lancelot)

### PPSSPP version affected

latest git

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by anr2me** [comment]
in-game saves are what the game are using (similar to real PSP), while Savestates are what emulator use, since they are not related to each other, so it's normal to have a different time isn't?

**Comment by justafella** [comment]
> This is probably why when using Savestates some games might think that the Save data got corrupted

Just to make things clear (for I read your edits for this answer), the issue here is, although I am already on Summer 7 (the date inside gameplay, as you save before going to sleepy), and although it loads correctly on Summer 7, the PPSSPP save file manager shows it as a save from Spring 21

I tested the native save data on the Play Store release version and it showed the correct in-game date after saving (Year 1 Summer 11, in this case, as I kept playing)

On latest git, it updates the in-game info on the date only if I save into a new slot (and then this new save will show this date without changing)

**Comment by hrydgard** [comment]
Hm, it might be some issue with savegame metadata that we don't handle correctly when overwriting existing saves. Should be investigated, tagging for 1.18. Fortunately this doesn't seem to affect gameplay so not super urgent.

**Comment by hrydgard** [comment]
This was caused by https://github.com/hrydgard/ppsspp/commit/652498e995a , part of #18430, an attempt by @Kethen to avoid overwriting PARAM.SFO with null data in ModNation Racers.

In this case, we do get valid data, so we should write PARAM.SFO. I'll try to come up with something better...
