### ISSUE TITLE
Add a toggle to preserve fullscreen aspect ratio in "Display Layout & effects"

### ISSUE THREAD

**Issue by dokur0chan** [hrydgard/ppsspp#18693]
### What should happen

With PPSSPP's current default behavior, the PSP's 30:17 DAR (1:1 PAR) gets squashed to 16:9 DAR from the top and bottom bezels of the screen when in fullscreen mode. There should be a toggle to disable this behavior and draw black bars instead.

### Who would this benefit

_Technically_ this is already possible by using the Resize feature, but having to slowly move the mouse until you get it _just right_ for each game is somewhat tedious, since the size of the black bars required to preserve the original DAR on a 16:9 display are very small to begin with. Having this relegated to a toggle would benefit users who also want to preserve the original PSP aspect ratio without wasting any screen real estate.

- In windowed mode, PPSSPP already preserves the 30:17 DAR, so having it get squashed when switching to fullscreen mode causes a bit of visual discontinuity. Integer scaling also preserves the 30:17 DAR (obviously), but it results in cropping.

- The only "downside" I can think of is that unlike with integer scaling, drawing black bars will result in some blurring since the output has to get downscaled to fit the screen. However this isn't much of a difference from the current status quo since squashing the image already results in blurring.

### Platform (if relevant)

None

### Games this would be useful in

Any

### Other emulators or software with a similar feature

At a cursory glance, the libretro core for PPSSPP seems to default to preserving the aspect ratio when using the "Core Provided" aspect ratio option.

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
I assume you're referring to how we automatically cut off one original-sized pixel from the bottom and top to turn 1920x1088 into 1920x1080 to fit? Is it really an issue to lose one row of pixels from the top and one from the bottom to achieve a perfect fit?

We could for sure add a toggle though, although every setting has a cost in terms of translation, screen space, confusion etc. I have been leaning more towards the side of adding actually useful settings rather than keeping it to a minimum like I tried before, though...

**Comment by hrydgard** [comment]
Hm, I'm confused right now. The intention is that the default should look like your retroarch example above, but if it doesn't (which I haven't even noticed, maybe because I run in a small window 99% of the time since it's easier to debug that way), it's a bug indeed. Will look into it.

**Comment by hrydgard** [comment]
Yup, I made a mistake in the last refactoring and implemented the auto-crop wrong, resulting in this poor result. Will fix soon so it will have the exact correct aspect ratio but cropped in this case, which will lead to the best pixel-mapping. Then the question is if we should add the option to turn it off, which will result in your retroarch image, but with an inexact pixel scale, making the image a little fuzzy.

**Comment by hrydgard** [comment]
Not much of a mistake from your side then, you found a bug that I caused :) 

Never assume that the current behavior is intentional, even if on master :D

**Comment by hrydgard** [comment]
Hm, seems I did an intentional switch at some point which I had forgotten. I prefer the crop solution anyway, so switching back to it and adding a hidden setting to turn it off, but I don't recommend that. See #18704.
