### ISSUE TITLE
CwCheats loading error after a while

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#18694]
This is a strange one, reported by DJ on Discord.

> After I've been playing for a while on my handheld device (Android), trying to go into the menu to toggle a cheat on leads me to a blank menu and I have to restart the app. Is that just a consequence of something, or might it be a bug?

> Playstore PPSSPP Golden on a [Retroid Pocket 3+](https://www.goretroid.com/products/retroid-pocket-3-handheld-retro-gaming-system-1) (Android 11). I tend to notice it after a handful of hours, but I've also gotten into the habit of saving in-game and then restarting the app when I know I need to toggle a cheat. It's the cheat menu itself that is blank. Let me see if I have screencaps. 

![image](https://github.com/hrydgard/ppsspp/assets/130929/3b8f0123-e42f-4f94-9595-33d94dde9945)
![image](https://github.com/hrydgard/ppsspp/assets/130929/25cfffa7-f670-480c-81f4-72b0a070facb)
![image](https://github.com/hrydgard/ppsspp/assets/130929/6529f55f-2506-4eef-b3ea-fd1068539d5b)
![image](https://github.com/hrydgard/ppsspp/assets/130929/50823747-b66a-49b5-a82d-62dc2c9b945f)

>  In this particular instance, I'm using HD texture packs but this was happening even before I found those packs to use in the first place. The game itself is Fate/Extra (ULUS10576) and then its sequel did the same. 

> I have a personal cheats file with the ones I personally think to use, and then the cheat.db to load from if I need one from the community list.

> I always have to hit "import" to load the cheat.db

> This is a copy of it. When I'm not experiencing this bug, it's just there automatically since I put it in PPSSPP\PSP\Cheats.

[ULUS10576.ini.zip](https://github.com/hrydgard/ppsspp/files/13936311/ULUS10576.ini.zip)

**Comment by biomagnet** [comment]
Seems to happen when I open the app panel (to swap to something else), or when I lock the device and reopen it. Can confirm the same thing happens on my Samsung Fold 5.

**Comment by hrydgard** [comment]
It's quite likely that #18736 fixed this - can you test?

**Comment by biomagnet** [comment]
I absolutely definitely forgot to say, but this seemed fixed as far as my Fold 5 goes. Haven't been able to install the dev build on my other device yet, but for now seems to work just fine.
