### ISSUE TITLE
No Beta program for PPSSPP Gold on Android

### ISSUE THREAD

**Issue by MrSujano** [hrydgard/ppsspp#18690]
### Game or games this happens in

PPSSPP Gold Android

### What area of the game / PPSSPP

I'm not certain if it's already planned or not, but the free version of PPSSPP on Android has the "Join the Beta" option whereas the PPSSPP Gold version on Android does not

### What should happen

Gold version should have "Join the Beta" program to retain parity with the free version

### Platform

Android

### Mobile device model or graphics card (GPU)

Pixel 7 Pro

### PPSSPP version affected

All

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
I will add this soon, I'm just starting to experiment with running a beta program. But this would obviously be a good thing.

**Comment by hrydgard** [comment]
This has now been rolled out, just waiting for approval. Already added the link in the meantime:

https://www.ppsspp.org/docs/development/beta-testing/
