### ISSUE TITLE
MIssing UI in pause screen. (Android)

### ISSUE THREAD

**Issue by Benda450** [hrydgard/ppsspp#18720]
### Game or games this happens in

All games

### What area of the game

In pause screen.

### What happens

Missing UI (black screen) It happen on Vulkan backend. (OGL is fine)

https://github.com/hrydgard/ppsspp/assets/79017876/05356553-60c2-4638-8276-9ce50e94fdfa

### What should happen

can access pause screen without problem.

### Platform

Android

### Mobile device model or graphics card (GPU)

Huawei P10 Plus (Mali-G71, Android 9.0)

### PPSSPP version affected

v1.16.6-490-g9f0166177 https://github.com/hrydgard/ppsspp/commit/9f016617748f28a971ae7c3a193a3bbd1815ca65

### Last working version

v1.16.6-482-g7605c2e4c

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by Benda450** [comment]
v1.16.6-887-g7affb1b8a is work great, thanks!

**Comment by hrydgard** [comment]
Thanks for testing!
