### ISSUE TITLE
"Refresh rate" setting wording under cheats could be misleading

### ISSUE THREAD

**Issue by Kethen** [hrydgard/ppsspp#18727]
### What should happen

With the wording "refresh rate", I'm not sure about everyone else but I was thinking Hz, but it seems that

https://github.com/hrydgard/ppsspp/blob/10d16ea48885fc0c65a070a2b3779af21b03167b/UI/CwCheatScreen.cpp#L112
->
https://github.com/hrydgard/ppsspp/blob/10d16ea48885fc0c65a070a2b3779af21b03167b/Core/CwCheat.cpp#L272-L285

is using the value as millisecond instead

I'm not sure if this is confusing others as well, or if I'm reading the code correctly

### Who would this benefit

(If I read the code correctly,)

If "refresh rate" would indeed lead to other people also thinking it as a per second rate, it could lead to users setting it to values like "1" expecting the emulator to only reapply CWCheat codes once a second, while in actuality does it 1000 times a second, degrading performance and battery life unintentionally

Given the value is used as a milisecond value, it might make more sense to rename the label to "Refresh Interval (ms)", or label it as "Refresh Rate (Hz)" and change to code to convert hertz to millisecond interval

### Platform (if relevant)

None

### Games this would be useful in

All games in general

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
Good point, people have also confused it with display refresh rate. This needs fixing.

**Comment by LunaMoo** [comment]
I think just adding "miliseconds" to slider itself would be enough or even the "ms" to avoid adding another translation since units are universal compared to full word.
