### ISSUE TITLE
We should warn about extracted ISOs

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#18735]
More and more people report problems that are caused by running games from extracted ISO. I guess they must have gotten into the habit of doing so from some other emulator, like maybe RPCS3? 

Either way, a lot of games won't work this way due to direct sector addressing, so we should forcefully warn about it. It can still be useful for modding some games, but in general it's not good practice.

**Comment by Panderner** [comment]
How about digital games extracted from PKGs?

**Comment by LunaMoo** [comment]
Extracting PSP's PKGs just leave you with a PBP(plus few extras files which aren't really used like manuals etc.) which is just a compressed container like CSO, it has nothing to do with extracted ISO's and if you extract game files from the PBP container, then it's exactly same as extracted from ISO or CSO.
