### ISSUE TITLE
(Feature Request) System Support

### ISSUE THREAD

**Issue by dobkun** [hrydgard/ppsspp#18761]
### What should happen

add some more support for PSP system software.
this includes XMB and font support
and yes hrygard, this is slightly more complex than just "bringing xmb for nostalgia trip".
this would allow putting an entire system together!
not just games!

### Who would this benefit

basically everyone, because now, most PSP-related stuff can be set in its system settings.
also, SKINS!
and another thing, FINALLY VIDEO PREVIEWS ON MENU SCREEN

### Platform (if relevant)

None

### Games this would be useful in

some games that display an FMV instead of static image when hovered over in menu

### Other emulators or software with a similar feature

JPCSP - an ultimate PSP emulator for debugging purposes

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by LunaMoo** [comment]
Was requested already, but the answer is always - do it yourself, it's not worth the time, PPSSPP is hle, doesn't emulate hardware, can't just run the system.

Refer to https://github.com/hrydgard/ppsspp/issues/14286#issuecomment-798496414 for longer answer.
