### ISSUE TITLE
"Extended PSP controls" section folds after each action

### ISSUE THREAD

**Issue by HFPasfho** [hrydgard/ppsspp#18783]
### Game or games this happens in

None

### What area of the game / PPSSPP

1. Go to Options > Controls > Control mapping.
2. Click "Extended PSP controls" section to unfold it.
3. Add/delete mapping.
4. "Extended PSP controls" section folds.

This may also apply to other sections to some extent but I didn't test it.
I checked "Test in the latest git build in case it's already fixed." checkbox but actually [I'm still unable to install these builds](https://github.com/hrydgard/ppsspp/issues/17792#issuecomment-1879713094). Unfortunately this checkbox is mandatory so I had to lie about it.

### What should happen

"Extended PSP controls" section folds shouldn't fold after each action.

### Platform

Android

### Mobile device model or graphics card (GPU)

S9

### PPSSPP version affected

v.1.17

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Yup, you're right, this is a bit awkward. No need to test new builds since there hasn't been any change here since 1.17.

I'll fix this for 1.17.1.
