### ISSUE TITLE
Performance problems with CHD 

### ISSUE THREAD

**Issue by master1274** [hrydgard/ppsspp#18798]
### Game or games this happens in

1. Dante's Inferno 2. God of War - Chains of Olympus 3. God of War - Ghost of Sparta 4. Colin McRae Rally 2005 5. Tekken 5 Dark Resurrection 6. The Treasures of Montezuma (minis) (PSN) 7. N.O.V.A. Near Orbit Vanguard Alliance (minis) (PSN)

### What area of the game / PPSSPP

Some performance problems after converting to chd

### What should happen

Performance shouldn't suffer

### Platform

Android

### Mobile device model or graphics card (GPU)

Various devices 

### PPSSPP version affected

Since the launch of support chd, before the current build

### Last working version

Since the launch of support chd, before the current build

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
You tried the same game in both CHD and ISO, and you can measure a difference? You sure?

**Comment by master1274** [comment]
This list was compiled by several contributors. Of course, the games were initially tested in iso. There were no problems. I personally checked Tekken 5: Dark Resurrection and The Treasures of Montezuma. Tekken 5: Dark Resurrection was also checked in cso. There were no problems either. Because We don’t know the reasons for the problem, we just decided to pass the list here so we can check this observation.

**Comment by hrydgard** [comment]
How does the problem manifest itself? Are the framerates low? Choppy or slow loading of the next level?

I need to know what to look for in order to investigate. Got any video comparison?

The thing is, CHD should only affect the speed of UMD disc reading, and games are already tolerant of slow speed, so a bit of additional compression and hashing really shouldn't make much of a difference, other than slightly affecting load times maybe.

**Comment by hrydgard** [comment]
Seems very odd to me that CHD would cause that, and if it does, it's really libchd performing poorly. We use it just as if it was the CSO backend, no difference there.

I recommend you use CSO on lower powered devices.

**Comment by hrydgard** [comment]
Huh, that is really surprisingly bad. Still, I'd say the problem is probably in libchd, not PPSSPP.  But, probably worth looking into. Do you see this on PC as well?

**Comment by hrydgard** [comment]
Also, to be sure I'll be testing the same thing: Can you provide the exact command line you used to compress your GTA VCS ISO to CHD?

**Comment by HFPasfho** [comment]
I've never used PPSSPP or screen recording on PC. I'll try to investigate but won't be able before weekend.
About conversion to chd I used chdman without changing a thing. Default script looks like this
`for /r %%i in (*.cue, *.gdi, *.iso) do chdman createcd -i "%%i" -o "%%~ni.chd"`

**Comment by hrydgard** [comment]
I heard from others that the recommended command was `createdvd`, although it probably doesn't matter.

**Comment by hrydgard** [comment]
Ok, i've tested both now, and that's indeed your problem. 

Download a fresh version of mame and get chdman from there, then use `createdvd`. It now supports createdvd, which is what you should use for both PPSSPP and PCSX2.

I think maybe the sectors get misaligned if you use createcd, generating a lot of extra reads and work for the decompression.
