### ISSUE TITLE
small fault : savedata tool text overlap 

### ISSUE THREAD

**Issue by HM-TArraria** [hrydgard/ppsspp#18792]
### What should happen

![Uploading IMG_20240130_153931.jpg…]()

### Who would this benefit

Those with OCD.haha.

### Platform (if relevant)

Android

### Games this would be useful in

userinterface

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by HM-TArraria** [comment]
forget. The date and time below should also be a little to the left.

**Comment by hrydgard** [comment]
I did some small fixes, the latest build looks better, but I haven't tried with very many languages or platforms.
