### ISSUE TITLE
Guidance on Mapping Physical Buttons to Emulator Controls on a device with Modified Android System

### ISSUE THREAD

**Issue by Jack12xl** [hrydgard/ppsspp#18801]
Hello PPSSPP Team,

I am working on a personal project involving a **modified** Android system that has physical buttons layout similar to the original PSP. The default setup of PPSSPP on Android(this is how it looks when simply build the Android version) relies on virtual on-screen buttons. I am interested in mapping these physical buttons to correspond with the emulator controls for a more authentic gaming experience.

Could you please guide me on which parts of the PPSSPP codebase I should look into for implementing this feature? Specifically, I need to know where in the code the emulator handles input events and how I can intercept and map physical button presses to these events.

Don't know if this is the right format to ask for a guide... But any guidance or suggestions on where to start and which files or modules to focus on would be greatly appreciated. Thank you for your time and assistance!

Best regards,
Jack12xl

**Comment by hrydgard** [comment]
I don't know how you are planned to feed Android the input from your physical buttons, but I assume in the app eventually they'll come out as key/axis events (like if you had connected a Bluetooth gamepad). These can be mapped with PPSSPP's existing input mapping system. See `Core/KeyMapDefaults.cpp` , you should make one of these tables that fit your layout, then you can add a little snippet to autodetect, see the lower part of RestoreDefault() in `Core/KeyMap.cpp`.

**Comment by Jack12xl** [comment]
I don't know why for some magical reasons the emulator could automatically capture the input from the physical button. And the buttons work almost perfectly.

**Comment by Jack12xl** [comment]
Wonder in order to change the default on-screen touch control layout to adapt to my device(these virtual buttons on a Android phones), should I focus on this line?
https://github.com/hrydgard/ppsspp/blob/13abd4991a6e836afa5d92560a540b00e68900c6/UI/GamepadEmu.cpp#L658

**Comment by Jack12xl** [comment]
I noticed if I only change this function(by hardcoding the position within), the layout would only take affect after I hit `reset` manually. 
![image](https://github.com/hrydgard/ppsspp/assets/27931931/c19dd654-7b75-4929-a5f6-14bf3b804616)

**Comment by hrydgard** [comment]
Hm? If you have buttons on your device, why do you need touchscreen buttons too?

I don't remember exactly how that works, if you really need it I'll check.

**Comment by Jack12xl** [comment]
Ah. That's because the button like `select, start, throttle` is automatically mapped to buttons like `menu` and `R2`(the physical button got a layout like Sony dual sense). 
I simply want to prompt the user that these psp buttons are mapped to these virtual buttons by virtual buttons.

**Comment by AccountGc** [comment]
Do I have to purchase games?
