### ISSUE TITLE
MSAA unstable on Adreno

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#18818]
I have a reproducible case on my Poco 4 (Adreno 650) where Ridge Racer crashes with a lost device at the start of the race (Arcade race, default car), but only if MSAA is enabled.

I'm going to disable MSAA on Adreno until we've figured this out.

**Comment by Panderner** [comment]
Does it affect other games?

**Comment by hrydgard** [comment]
I don't know other examples, but if one game is affected, it's highly likely that others are too.

**Comment by hrydgard** [comment]
Should be fixed with #19487, probably combined with some earlier fixes.
