### ISSUE TITLE
Flashing to Black Screen in Tokimeki Memorial 4

### ISSUE THREAD

**Issue by NateTheL0ser** [hrydgard/ppsspp#18811]
### Game or games this happens in

NPJH-50127 Tokimeki Memorial 4

### What area of the game

Upon opening the game. 

### What happens

Konami logo and Memory Stick text box flash in and out, then turns to a black screen with no sound. This did not happen in 1.16, but began in 1.17.

### What should happen

The game should start and be functional.

### Platform

Windows

### Mobile device model or graphics card (GPU)

NVIDIA RTX 3060 Laptop GPU

### PPSSPP version affected

1.17

### Last working version

1.16.6

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [ ] Include logs or screenshots of issue.

**Comment by AccountGc** [comment]
Do I have to purchase games?

**Comment by sum2012** [comment]
D3D9.3D11,opengl
good 
v1.16.6-490-g9f0166177
bad
v1.16.6-495-g65081da7f

git bisect result https://github.com/hrydgard/ppsspp/pull/18515/commits/8d8ff5886bdc9cebed7b02e546f23c699a553b79 in #18515

Vulkan
good
v1.16.6-751-gde0d82d02
bad
v1.16.6-753-g3d08b14ac
That mean #18650

**Comment by hrydgard** [comment]
Hm, as for D3D11 and the others, that's surprising, I'll try to figure it out.

For the Vulkan change, that one fixed the GE frame dumps, but then theres' more to it...

**Comment by hrydgard** [comment]
@sum2012 thanks for the bisects, by the way. can you grab a couple of GE dumps of the bad rendering?

**Comment by sum2012** [comment]
I have grabed 3 times.It is black screen.
[NPJH50127_ppdmp.zip](https://github.com/hrydgard/ppsspp/files/14143465/NPJH50127_ppdmp.zip)

**Comment by hrydgard** [comment]
Thanks! I'll take a look at them soon.

**Comment by sum2012** [comment]
Just a test
Revert #18650 fix opengl,d3d9,d3d11,Vulkan

**Comment by hrydgard** [comment]
@sum2012 thanks, might do that for 1.17.1.

(But, it also will "unfix" the tokimeki bug with the weird bottom part of the screen in those framedumps, but better that than not being able to play, I guess...)

**Comment by sum2012** [comment]
@hrydgard No, it is still fix " the tokimeki bug with the weird bottom part of the screen.
Here is the the frame dump
[NPJH50127-arm.zip](https://github.com/hrydgard/ppsspp/files/14154645/NPJH50127-arm.zip)

**Comment by sum2012** [comment]
ppsspp-v1.17-115-gb28502a07-windows-amd64
Confirm fixed by #18822 
Closing
