### ISSUE TITLE
Translation Issues

### ISSUE THREAD

**Issue by xujibbs** [hrydgard/ppsspp#18827]
### Platform

Windows

### Compiler and build tool versions

None

### Operating system version

Windows 10

### Build commands used

None

### What happens

“Restart Graphics” on UI is untranslatable.

### PPSSPP version affected

v17.1

### Last working version

N/A

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] Make sure to run `git submodule update --init --recursive` before building.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try deleting the build directory and running the build again.
- [ ] Check GitHub Actions, which builds every merge and PR.
- [ ] Include logs and help us reproduce.

**Comment by NABN00B** [comment]
If we are talking about the menu bar list item, then this has been fixed.

**Comment by hrydgard** [comment]
Yeah, I'll close this.
