### ISSUE TITLE
New gamepad

### ISSUE THREAD

**Issue by appt2** [hrydgard/ppsspp#18839]
### What should happen

Hello, since ppsspp contains 2 gamepads and does not look very attractive, provide the possibility for the user to produce gamepads by himself through a file and in a special format.

### Who would this benefit

null

### Platform (if relevant)

Android

### Games this would be useful in

no game

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by IrfanH495** [comment]
I think this is similar #14515

**Comment by hrydgard** [comment]
Yeah, #14515 is similar enough. closing as dupe.
