### ISSUE TITLE
PPSSPP VR on Sidequest

### ISSUE THREAD

**Issue by lvonasek** [hrydgard/ppsspp#18834]
### What should happen

PPSSPP VR isn't updated on Sidequest to 1.17.x version.

### Who would this benefit

Meta Quest 3 users because 1.16 doesn't work well on that device.

### Platform (if relevant)

Other

### Games this would be useful in

A lot of games but e.g. Wipeout

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
Thanks for the reminder, this is now fixed.
