### ISSUE TITLE
Frame Advance sometimes advances more, starts running

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#18837]
Seems we have some small logic issue or race condition. Reported by NABN00B on Discord.

**Comment by hrydgard** [comment]
@NABN00B can you test #19473 ?

**Comment by NABN00B** [comment]
> @NABN00B can you test #19473 ?

Sure, I can try, but I don't understand how to reproduce the glitch in the first place (and whether it's consistent or not).

**Comment by hrydgard** [comment]
You reported it, right? :)  I guess just see if it still seems to be an issue at all (I doubt it).

**Comment by hrydgard** [comment]
I'm gonna consider this fixed unless anything else is reported.
