### ISSUE TITLE
emulators ui not being there at all

### ISSUE THREAD

**Issue by Twatsuya** [hrydgard/ppsspp#18849]
### Game or games this happens in

None

### What area of the game / PPSSPP

games work fine but ui in game escape menu where you can check settings and stuff its the same as the main menu aka bugged also i tried all backends and besides that most of my settings are default

### What should happen

menu should have the blue background and separations instead of just being just the words also some words and sentences straight up dont show up
![Screenshot 2024-02-10 165849](https://github.com/hrydgard/ppsspp/assets/159654172/7014ffef-8158-47b3-bb0b-39d4cc2d7611)
![Screenshot 2024-02-10 165813](https://github.com/hrydgard/ppsspp/assets/159654172/1828aa2c-60c0-4662-b20c-0e16372755b6)
![Screenshot 2024-02-10 165821](https://github.com/hrydgard/ppsspp/assets/159654172/dc42fab9-6da2-4b4c-aaa5-458461a4f8eb)

### Platform

Windows

### Mobile device model or graphics card (GPU)

Nvidia geforce rtx 4050

### PPSSPP version affected

latest stable as of 02/10/2024

### Last working version

cant say my pc is brand new i just installed for the first time

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Hm. Are you missing the assets/ folder from your install? Can you try to reinstall the app?

**Comment by Twatsuya** [comment]
it works now thanks maybe i deleted something without meaning to or sum 

but yea ty for the help glad it works now ^^

**Comment by Twatsuya** [comment]
![Screenshot 2024-02-10 174409](https://github.com/hrydgard/ppsspp/assets/159654172/fb509a89-b25c-4f20-9df6-5ffedf774c38)
when i launched the game from the installer it worked fine but later i opened the 64 bit .exe and this happened (i doubt its the exe because last time i opened both files and both had the graphical error

**Comment by LunaMoo** [comment]
Are you using Win 11 built in zip support and open exe from within the archive instead of extracting it first?

**Comment by Twatsuya** [comment]
im using the installer and yes im in win 11

**Comment by Twatsuya** [comment]
ill tell you exaclty what i do maybe itll help you find a clue 
i download ppsspp but the installer version cause im lazy like that
install it and then at the end i click off the readme and clicked on the open option and then finish the installation 
app opens and it works yay! (first picture) 
so i minimised it go to the folder it made with all the ppsspp things and make a shortcut of the 64 exe one 
into another folder in my desktop where i keep my emulators then open the shortcut and boom (second picture)

**Comment by hrydgard** [comment]
Okay, so it's not working from the shortcut. You sure you created a shortcut properly and didn't move the exe file itself? If you did, rightclick-properties on the shortcut, and check the working directory to match the exe location.

**Comment by Twatsuya** [comment]
yea i copy and paste the exe ill check rn

**Comment by Twatsuya** [comment]
i did it as a shortcut now cause apparently copying and pasting the exe doesn't make it a shortcut anymore its just a clone of the exe or something but its definitely not a shortcut if i do that

its fixed for now ill keep a lookout for any more errors thanks for the help hrydgard and LunaMoo

**Comment by LunaMoo** [comment]
Copy&Paste exe would never create shortcut, easiest to do that would be drag and drop with right click and choosing to create shortcut.
