### ISSUE TITLE
Sangokushi IX / Romance of the Three Kingdoms IX map black screen

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#18845]
### Game or games this happens in

ULJM05842

### What area of the game

ps: Original reporter in http://c.tieba.baidu.com/p/8888900309
Click on the city and the command page will appear, then press up and down and it will be black

### What happens

Only happen in Directx 11 and Vulkan
![3](https://github.com/hrydgard/ppsspp/assets/2177532/6301f90a-0978-43ce-9e91-fb602b7e8a56)

### What should happen

![4](https://github.com/hrydgard/ppsspp/assets/2177532/c6ce08b5-1a05-4064-b955-2f2a3df095a1)

### GE frame capture

[ULJM05842.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/14227042/ULJM05842.ppdmp.zip)

### Platform

Windows

### Mobile device model or graphics card (GPU)

Nvidia GeForce 710

### PPSSPP version affected

v1.16 and after

### Last working version

v1.15.4

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
I think we've had issues with this one before? thanks for the framedump!

**Comment by sum2012** [comment]
Yes, similar #2159

ppsspp-v1.15.4-62-gda3bd6785 bad
ppsspp-v1.15.4-60-ge1890b6a9 good

It mean #17505

**Comment by hrydgard** [comment]
Thanks for tracking the change down! Hm, must have missed something....

**Comment by sum2012** [comment]
V1.17.1-1024 the bug fixed

**Comment by hrydgard** [comment]
Great, thanks for testing.
