### ISSUE TITLE
Need for speed underground rivals Line bug

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#18846]
### Game or games this happens in

ULUS10007

### What area of the game

Original reporter in http://c.tieba.baidu.com/p/8880500610 9th floor
In the beginning

### What happens

All render engine
![3](https://github.com/hrydgard/ppsspp/assets/2177532/6d7ddd21-fd30-467d-9ac6-0358185d885b)

### What should happen

This is soft gpu
![4](https://github.com/hrydgard/ppsspp/assets/2177532/96fe831e-d7a8-4787-9a88-c2d0e0b95168)

### GE frame capture

[ULUS10007.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/14227351/ULUS10007.ppdmp.zip)

### Platform

Windows

### Mobile device model or graphics card (GPU)

Nvidia GeForce 710

### PPSSPP version affected

v1.16.6 and after

### Last working version

v1.16.5

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by sum2012** [comment]
good
v1.16.5-141-g15df71c02

bad 
v1.16.5-144-g3e63fe865

git bisect result [c7a3e7bc3282f4b64a1a5e3c897516c0f78013b6](https://github.com/hrydgard/ppsspp/commit/c7a3e7bc3282f4b64a1a5e3c897516c0f78013b6) in #18316

**Comment by sum2012** [comment]
Lucky revert the change https://github.com/hrydgard/ppsspp/commit/dea890718fbc68b5ce364a6a1dd63f8b54dd7128
Work in master

**Comment by hrydgard** [comment]
Huh, that's interesting. I'll look into it soon, thanks for tracking it down.
