### ISSUE TITLE
Retroachievements Stuck in Hardcore Mode

### ISSUE THREAD

**Issue by ripcord95** [hrydgard/ppsspp#18847]
### Game or games this happens in

Any games

### What area of the game / PPSSPP

N/A

### What should happen

hardcore mode should turn off if left unchecked in retroachievements settings

### Platform

Android

### Mobile device model or graphics card (GPU)

Poco X3 Pro

### PPSSPP version affected

1.17.1

### Last working version

1.16.6

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Hm, are you using game-specific settings? (little gear icon on the game)? 

If so, you'll need to go into the retroachievements settings from settings from the pause menu when the game is running, and change it there. Or remove the game-specific settings.

**Comment by ripcord95** [comment]
> Hm, are you using game-specific settings? (little gear icon on the game)?
> 
> If so, you'll need to go into the retroachievements settings from settings from the pause menu when the game is running, and change it there. Or remove the game-specific settings.

that was it, weird as i've never turned on hardcore mode
