### ISSUE TITLE
Final Fantasy Tactics: War of the Lions: Crash in Vulkan during intro

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#18850]
Needs investigation. Reported by Nez on github.

**Comment by sum2012** [comment]
Windows \ Android ?
gpu ?

**Comment by sum2012** [comment]
![3](https://github.com/hrydgard/ppsspp/assets/2177532/0c49e4cb-d569-435e-96f4-031cbd2883b4)

**Comment by sum2012** [comment]
![3](https://github.com/hrydgard/ppsspp/assets/2177532/775c631f-c8a1-403c-9ef9-23b032c46898)
![4](https://github.com/hrydgard/ppsspp/assets/2177532/c62c5eea-1d89-40ea-a8a3-fc4e4f1ee9d0)
![5](https://github.com/hrydgard/ppsspp/assets/2177532/01f5c3c9-148f-4c9b-8778-d3421c32a7b4)

**Comment by sum2012** [comment]
good
v1.17-63-gccaf2446e

bad
v1.17-66-gb0a9ef5aa

git bisect result: https://github.com/hrydgard/ppsspp/pull/18794/commits/76242cb9f768561723c13d35e4021b68d23e1662 in #18794

**Comment by sum2012** [comment]
![3](https://github.com/hrydgard/ppsspp/assets/2177532/3cdb228c-cffa-4156-a817-177a6f88a27a)

**Comment by hrydgard** [comment]
Thanks for tracking down the change - although, it's really weird if that one's the cause! Hm.

**Comment by sum2012** [comment]
I re-do git bisect, the result is not same
![3](https://github.com/hrydgard/ppsspp/assets/2177532/ec5758cd-9e0b-4d13-a628-f36b14f0738a)
![4](https://github.com/hrydgard/ppsspp/assets/2177532/d1767cee-98cf-4cb6-9e7f-18327a3b5f0a)

**Comment by sum2012** [comment]
So do we had some bug  before ?
We don't know the bug unless we added the debug-asserts ?

**Comment by hrydgard** [comment]
I'm not really sure, maybe the bug is kinda random... but, one of the asserts I added there does fire, with a different message than in your first screenshot. I think there is a real bug and will look into it.

**Comment by cmcglownjr** [comment]
I would also like to add that I am experiencing this. I am running this emulator on the Steam Deck (original 512 GB model). It also crashes if I were to press the TAB key to skip the intro (through keyboard or pressing the face buttons View or Menu). If there is anyway I can help you debug this then let me know.

**Comment by hrydgard** [comment]
I believe this was fixed a while ago. Closing.

**Comment by broFenix** [comment]
I actually am experiencing this issue currently. I just downloaded the latest PPSSPP version and started to play Final Fantasy Tactics the other day, and discovered that Vulkan was the only "Backend" setting that allowed my to upscale the graphics the way I was trying to. But I have experienced this crash as well, after watching the intro cutscene or skipping it by pressing Start, PPSSPP has a warning pop-up that basically states the emulator has crashed. No matter how many times I press "Yes" to this pop-up, the emulator never resolves the issue.

I have found a workaround, by checking "Skip buffer effects" in the Graphics Settings, skipping the intro cutscene, then unchecking "Skip buffer effects." So far it seems like the game plays afterwards, but I have only played the 1st battle and nothing afterwards.

May I ask if this issue can be re-looked at again, as I don't believe it has been fixed?

![PPSSPP Black Screen after Unchecking Skip buffer effects, and skipping intro cutscene](https://github.com/user-attachments/assets/6d8bfd67-d3cc-45b5-ba32-ccf08571dd2d)
![PPSSPP Crashing for Final Fantasy Tactics War of the Lions using Vulkan](https://github.com/user-attachments/assets/ea5dce72-f983-4475-b22e-fbaf84e20c76)
![PPSSPP Graphics Settings used When Emulator Crashes - 1](https://github.com/user-attachments/assets/adf7d1d2-80c8-42c9-89e9-384ac73eafb8)
![PPSSPP Graphics Settings used When Emulator Crashes - 2](https://github.com/user-attachments/assets/bcbddfff-3bfc-4e53-94a0-2e46473ad596)
![PPSSPP Graphics Settings used When Emulator Crashes - 3](https://github.com/user-attachments/assets/7b2f73c3-867a-4bec-9a6f-203d41efd02f)
![PPSSPP Unchecking Skip buffer effects, to Enable Emulator to Draw Graphics Again - 1](https://github.com/user-attachments/assets/a683ebdf-6daf-4c5b-9ace-b49b92024fc5)
![PPSSPP Unchecking Skip buffer effects, to Enable Emulator to Draw Graphics Again - 2](https://github.com/user-attachments/assets/f00c9798-b199-4895-a3c2-3c54429d34bf)

**Comment by hrydgard** [comment]
@broFenix  It seems you are using the latest official release, which unfortunately is too old to contain the bugfix. The fix is in the builds you can download from https://www.ppsspp.org/devbuilds/ , and will be in the upcoming 1.18 update in September.

**Comment by broFenix** [comment]
@hrydgard Thank you very much! I appreciate you letting me know about the devbuilds page. I tried the latest devbuild and you're right, the bug seems to be fixed :) Apologies if I missed the page and I appreciate all that you do :)
