### ISSUE TITLE
appendconfig does not seem to work

### ISSUE THREAD

**Issue by bmsuseluda** [hrydgard/ppsspp#18857]
### Game or games this happens in

None

### What area of the game / PPSSPP

Hello together,

thank you for this great emulator.
Im trying to append a config file via command line. In the [wiki](https://www.ppsspp.org/docs/reference/command-line/) i found the command line argument `--appendconfig` with the description `Merge a different config file into the current configuration.`

Therefore i created seperate ppsspp.ini with following content based on the general ppsspp.ini file from my home directory:
```
[Graphics]
FullScreen = True
```

Based on the description of the command line argument i would expect that the general ppsspp.ini and my simplified ppsspp.ini would be merged together.

When i try `flatpak run org.ppsspp.PPSSPP --appendconfig ppsspp.ini` i get the following error:

```
32:21:714 Core/Loaders.cpp:371 E[LOADER]: Unknown file type: ppsspp.ini ()
32:21:714 HLE/sceKernel.cpp:170 E[SCEKERNEL]: Can't shut down kernel - not running
32:21:715 UI/EmuScreen.cpp:356 E[BOOT]: InitStart bootGame error: Unknown file type: ppsspp.ini
```

When i try it together with a game `flatpak run org.ppsspp.PPSSPP --appendconfig ./ppsspp.ini "./MotorStorm - Arctic Edge (Europe) (PSP) (PSN).chd"
` i get the following error:

```
Can only boot one file
47:24:568 Common/Log.cpp:68 E[SYSTEM]: (/run/build/ppsspp/Common/Net/HTTPClient.cpp:~HTTPRequest:508): [joined_] (menu, 0.0s) Download destructed without join
```

I hope you can help me.
Thanks in regards

### What should happen

Based on the description of the command line argument `appendchild` i would expect that the general ppsspp.ini and my simplified ppsspp.ini would be merged together.

### Platform

Linux / BSD

### Mobile device model or graphics card (GPU)

Mesa Intel(R) Xe Graphics (TGL GT2)

### PPSSPP version affected

v1.17.1

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [x] Try resetting settings or older versions and include if the issue is related.
- [x] Try without any cheats and without loading any save states.
- [x] Include logs or screenshots of issue.

**Comment by anr2me** [comment]
Btw, is that `[Graphics] FullScreen = True` really a valid INI format?

Isn't it supposed to be like this?
```
[Graphics]
FullScreen = True
```

**Comment by bmsuseluda** [comment]
> Btw, is that `[Graphics] FullScreen = True` really a valid INI format?
> 
> Isn't it supposed to be like this?
> 
> ```
> [Graphics]
> FullScreen = True
> ```

Yes that is correct, my markdown was wrong

**Comment by hrydgard** [comment]
Looks to me in the code that appendconfig has to be used with a = sign, like, `--appendconfig=ppsspp.ini`

Which is another sign that we really need a better command line parser...

Anyway, confirmed that it does actually work with that syntax, so I added a better error message, closing.
