### ISSUE TITLE
Set gameplay screen as background when editing touch control layout

### ISSUE THREAD

**Issue by HFPasfho** [hrydgard/ppsspp#18863]
### What should happen

Currently, when editing the touch control layout, you can see a screenshot from the game in the background, but it does not coincide with the area where the button layout is being edited. The background screenshot (with letterboxing if necessary) should be scaled down to exactly cover this area.

### Who would this benefit

Touch screen users. This will avoid guessing whether a button is covering an element of the game interface, e.g. a map., and setting the button layout by trial and error.

### Platform (if relevant)

None

### Games this would be useful in

many

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
It's a good feature request, but a duplicate: #16228
