### ISSUE TITLE
High Contrast Fonts (Android system setting) results in weirdly glowy text

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#18860]
Reported by johnwildx on Discord.

The image speaks for itself - though, I have no idea how this is happening.

![image](https://github.com/hrydgard/ppsspp/assets/130929/b445ffd7-a15e-40a0-a4de-3c64bfdf43f3)

**Comment by anr2me** [comment]
Does a high contrast font supposed to have an outline like in this guide? https://mcmw.abilitynet.org.uk/how-to-make-text-easier-to-read-with-high-contrast-text-in-android-13
![image](https://github.com/hrydgard/ppsspp/assets/7974720/9a8d498b-9984-418d-9f84-bd470b8c0e36)

May be we use the same color on the outline, thus it became like glowing.

**Comment by hrydgard** [comment]
Ah good find! Yeah, I think that's exactly what happens...

**Comment by hrydgard** [comment]
There might be a potential solution here: https://stackoverflow.com/questions/54599485/how-to-ignore-high-contrast-accessibility-option-in-android-during-canvas-drawin
