### ISSUE TITLE
Building emscripten with GLES is broken

### ISSUE THREAD

**Issue by ethanaobrien** [hrydgard/ppsspp#18861]
### Platform

libretro / Retroarch

### Compiler and build tool versions

emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.53 (ce5114bdd2175c7297583d3c25a53ca95d22f4ce)

### Operating system version

Debian GNU/Linux bookworm 12.0 x86_64

### Build commands used

Using the patches mentioned [here](https://github.com/hrydgard/ppsspp/pull/17779) for sub modules, and [this commit](https://github.com/EmulatorJS/ppsspp/commit/b41753896aca4e275c873519839ce109cb095896), disabling `GLES`, then linking with RetroArch using gles2 causes PPSSPP to run almost flawlessly.

As far as I can tell the emulation itself runs perfectly, playable* as long as you don't need video. Much better than it was a few months ago when I originally tried getting it to run.

And here's the fun part, of course compiling without GLES and targeting gles2 wont work, that was just to get it to run at all.
Currently, if you build with `GLES` enabled (specifically if you pass the `USING_GLES2` definition) the page will freeze upon load. I traced the freeze [here](https://github.com/hrydgard/ppsspp/blob/f3635c4463f194b1908455b3d56080e368a6df7d/Common/GPU/OpenGL/GLRenderManager.cpp#L366) where it seems to be waiting on another thread. This only happens when `GLES` is enabled, with it disabled the emulation runs as well as the browser can handle it, which is suspiring.

To build this:
1. `git clone https://github.com/EmulatorJS/ppsspp.git`
2. `git clone https://github.com/EmulatorJS/RetroArch.git`
3. `git clone https://github.com/EmulatorJS/EmulatorJS.git`
4. `cd ppsspp/libretro/`
5. Apply patches mentioned in #17779
6. `emmake make clean && emmake make platform=emscripten -j$(nproc)`
7. `cp ppsspp_libretro_emscripten.bc ../../RetroArch/dist-scripts/`
8. `cd ../../RetroArch/dist-scripts/`
9. `emmake ./dist-cores.sh emscripten clean`
10. Open your file explorer and navigate to `EmulatorJS/data/cores/` and open the .data file with 7zip, open the `.js` file (not `.worker.js`( in a text editor and search for `asyncifyStubs`. Remove any definitions of this. This errors because of a [bug with emscripten](https://github.com/emscripten-core/emscripten/issues/21104) where its defined but does not do anything. Removing this definition will fix the issue.
11. Download [this zip](https://github.com/EmulatorJS/EmulatorJS/raw/5307e6294ed9df5daabd6958b2b307bae01f59f1/data/cores/ppsspp-assets.zip) to the `EmulatorJS/data/cores` folder
12. Launch your favorite web server pointing at the `EmulatorJS` folder. Be sure to set the headers mentioned [here](https://stackoverflow.com/a/68630724)
13. Edit the [core function](https://github.com/EmulatorJS/EmulatorJS/blob/507fdcd51de172596e84bf340c86fb3b9be44e2d/index.html#L136) to always return `psp`.
14. Open a web browser and go to [http://localhost:8080/index.html?debug=1&threads=1](http://localhost:8080/index.html?debug=1&threads=1). It should warn you if threads is not properly enabled.
15. Upload your rom to the page. It will automatically launch the game assuming you did step 13.

Through writing this (40-50 minutes) I've had ppsspp running in the browser with gles disabled (no video) and have had no crashes nor performance decreases (playing the title menu music). The only issue with the emscripten build target is gles.

A demo with gles disabled can be found [here](https://ethanthesleepy.one/EmulatorJS/?debug=1&threads=1).

### What happens

gles disabled log (working emulation, black screen): 
[gles--disabled.log](https://github.com/hrydgard/ppsspp/files/14255852/gles--disabled.log)

gles enabled log (freezes page):
[gles-enabled.log](https://github.com/hrydgard/ppsspp/files/14255824/gles-enabled.log)

### PPSSPP version affected

v1.17.1-11-gb41753896

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] Make sure to run `git submodule update --init --recursive` before building.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try deleting the build directory and running the build again.
- [ ] Check GitHub Actions, which builds every merge and PR.
- [X] Include logs and help us reproduce.

**Comment by hrydgard** [comment]
Emscripten isn't a platform that the project (or at least I) care about, you're on your own. I'll leave the issue open, though.

**Comment by btn0s** [comment]
@hrydgard Just curious do you have any interest in or knowledge of ways to get this running on web?

**Comment by hrydgard** [comment]
No interest

**Comment by btn0s** [comment]
Fair enough.

**Comment by ethanaobrien** [comment]
This was fixed at some point... PPSSPP now fully works in the web browser!

Unless requested, I don't plan on upstreaming the few changes I made (https://github.com/EmulatorJS/ppsspp/commit/7e9a311092186d5bb18bb0477f6857b6ab70b45d) because some things are done messily.
