### ISSUE TITLE
Bindable Reset key

### ISSUE THREAD

**Issue by NABN00B** [hrydgard/ppsspp#18869]
### What should happen

Currently the only fast way to reset/restart emulation is the hardcoded Ctrl+B hotkey combination, which requires the "Enable global hotkeys" setting to be enabled. Having a configurable key would make resetting more convenient by having to press only a single button which could even be one on the controller. (Plus not having to keep global hotkeys enabled is also a positive.)

I know it's a niche usecase but there's already a bunch of weird stuff in there so maybe.. 😛 

### Who would this benefit

speedrunners

### Platform (if relevant)

Windows

### Games this would be useful in

-

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
Certainly more motivated than some other ones.. tagging it.

**Comment by hrydgard** [comment]
Now implemented.
