### ISSUE TITLE
Adicionar suporte de GameBoot de qualquer plataforma para o ppsspp 

### ISSUE THREAD

**Issue by jpplayerBR** [hrydgard/ppsspp#18866]
Eu gostaria de ver no ppsspp sistema de GameBoot que tem no PSP no ppsspp por exemplo eu gostaria de rodar introdução do PS2 e possível no PSP utilizando GameBoot  mais o ppsspp não tem essa função gostaria de vocês adicionar essa função no ppsspp GameBoot são arquivo que você colocar no PSP para mudar a introdução do PSP para personalizar o PSP ou ppsspp esse e o meu feedback

**Comment by anr2me** [comment]
Are you talking about VSH support on PPSSPP?

**Comment by jpplayerBR** [comment]
Yes

**Comment by hrydgard** [comment]
English on the issue tracker please. And this has been asked about before, see #15270
