### ISSUE TITLE
Optimize allocation virtual memory in NUMA topology (Intel X79 X99 C741 C622 C621AE C612 C602 i5xxx iE75xx nForce 3xxx 2xxx and AMD SP5 SP4 SP3 G34 and old)

### ISSUE THREAD

**Issue by GermanAizek** [hrydgard/ppsspp#18862]
@hrydgard,
https://github.com/x64dbg/x64dbg/pull/3307
do you think such PR fix would be useful for PPSSPP? For NUMA users, use WINAPI NUMA functions, for regular users, standard will be used.

Platform: Windows

**Comment by hrydgard** [comment]
On pretty much any machine where NUMA is relevant, PPSSPP is already fast enough, as far as I know. I don't think it's possible to justify messing with this stuff, from a maintenance perspective.
