### ISSUE TITLE
crash at latest build

### ISSUE THREAD

**Issue by Gelo021** [hrydgard/ppsspp#18871]
startup crash

https://github.com/hrydgard/ppsspp/assets/67460268/80999076-6955-4114-b89b-e06d2bacb238

**Comment by Gelo021** [comment]
Why video is white 😞

**Comment by hrydgard** [comment]
hm, how come you closed it? 
was it fixed by moving some file, for example? if so, would be interested in what.

**Comment by Gelo021** [comment]
sorry i just fix it by installing previous version and installing again the latest one

**Comment by Gelo021** [comment]
@hrydgard just reinstall the latest build agail with overlapping a previous build and it crash

**Comment by Gelo021** [comment]
i think the setup cause the crash

**Comment by Gelo021** [comment]
v1.17.1-12-gf3635c446 so the issue starts with this build

**Comment by Gelo021** [comment]
@hrydgard 
duplicate #18872  so ill closed it
