### ISSUE TITLE
Help: Graphic issue in FF TYPE 0

### ISSUE THREAD

**Issue by MerkSin** [hrydgard/ppsspp#18879]
### Game or games this happens in

NPHJ 50443

### What area of the game

At the beginning and end of a battle 

### What happens

As seen in the image, when a critical hit is given, a red box or sometimes even red or blue letters appear.  
![Screenshot_2024-02-20-21-55-43-964_com miui gallery](https://github.com/hrydgard/ppsspp/assets/85376703/baf41fbb-9d92-4452-b721-edce04975277)
![Screenshot_2024-02-20-21-57-05-471_com miui gallery](https://github.com/hrydgard/ppsspp/assets/85376703/486d73b8-61aa-4702-bad9-8d72eb062584)
![Screenshot_2024-02-20-21-54-48-174_com miui gallery](https://github.com/hrydgard/ppsspp/assets/85376703/8945a4e4-134f-4b74-bb7d-08bf7c13977d)

### What should happen

This problem has always occurred, it has been going on for years and it has not been solved. I have tried it in different versions.

### GE frame capture

![Screenshot_2024-02-20-19-38-16-886_org ppsspp ppssppgold](https://github.com/hrydgard/ppsspp/assets/85376703/3513fd09-9068-43a9-8ea8-09c1035d5644)

### Platform

Android

### Mobile device model or graphics card (GPU)

POCO F5 SNAPDRAGON 7 GEN 2

### PPSSPP version affected

V1.17.1 versión gold 

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by sum2012** [comment]
@MerkSin You need to create a frame dump
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

**Comment by DmdHoH000** [comment]
@sum2012 Hello, I would like to provide the file since this problem is happening on my new cell phone, a Galaxy A14 5G.
This problem also occurs in opengl so I saved two files
[NPJH50443opengl.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/15021373/NPJH50443opengl.ppdmp.zip)
[NPJH50443vulkan.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/15021374/NPJH50443vulkan.ppdmp.zip)

**Comment by IrfanH495** [comment]
I added to AllowLargeFBTextureOffsets, I think that helps.
I haven't played it for a long time, does it really look like this after completing a mission?
AllowLargeFBTextureOffsets off

https://github.com/hrydgard/ppsspp/assets/78854859/e4eef951-9fb2-49d8-ba0e-230c07bbeb5e


AllowLargeFBTextureOffsets on

https://github.com/hrydgard/ppsspp/assets/78854859/3e7fed4d-9b6a-439e-8ebd-da112086bf86

**Comment by hrydgard** [comment]
Well, that definitely does look more correct. I'll add it.

**Comment by hrydgard** [comment]
I'm gonna close this, please re-open if it re-occurs, or to report any new graphical glitches that appear as a result of this change...
