### ISSUE TITLE
every game with the "autosave feature message" before the game start, are crashing right before the mesasage appears in retroarch

### ISSUE THREAD

**Issue by gabberhead** [hrydgard/ppsspp#18873]
### Game or games this happens in

for example: Indiana Jones and the Staff of Kings , Mega Man - Maverick Hunter X, Mega Man - Powered Up, Manhunt 2

### What area of the game / PPSSPP

crash right before this screen appers:

![20240217_204442](https://github.com/hrydgard/ppsspp/assets/42085140/de5bfb89-e5c4-47f7-9599-066f5605e4d9)

wiht the latest standalone programm of ppsspp all games are working. on retroarch i have the latest core downloaded. testet with vulkan, ogl and dx11. dont matter, the game always crashes. testes also with a fresh unmodified config with retroarch. i also updated the needed assets folder.

### What should happen

the screen must appear without crashing the game

### Platform

Windows

### Mobile device model or graphics card (GPU)

intel laptop gpu

### PPSSPP version affected

latest core on retroarch

### Last working version

i dont know

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by anr2me** [comment]
@gabberhead could you test again on the latest version? this issue might have been fixed by https://github.com/hrydgard/ppsspp/pull/18881

**Comment by gabberhead** [comment]
its working now again. thanx :) case closed ;)
