### ISSUE TITLE
ppsspp crashes on clean install if there is no data since v1.17.1-11

### ISSUE THREAD

**Issue by brujo5** [hrydgard/ppsspp#18872]
### Game or games this happens in

Emulator problem

### What area of the game / PPSSPP

Justo do a clean install of ppssppp v1.17.1-11 or newer

### What should happen

ppsspp crashes on clean install if there is no data since   v1.17.1-11. 
 v1.17.1-10 work fine with on clean instalation

the solution is to install v1.17.1-10 and select a directory to create data and then install the latest version v1.17.1-16-gf5450e40e so the emulator doesn't crash

### Logs

[Log_2024-02-16_22-23-24.txt](https://github.com/hrydgard/ppsspp/files/14317837/Log_2024-02-16_22-23-24.txt)

### Platform

Android

### Mobile device model or graphics card (GPU)

7+gen2, Adreno 725

### PPSSPP version affected

v1.17.1-11-gc5791764d up

### Last working version

v1.17.1-10-g9322b4c6d

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by sum2012** [comment]
Confirm my black shark 5 pro phone

**Comment by Gelo021** [comment]
setting up for the first time causes the issue ithink

**Comment by hrydgard** [comment]
hm not good, i'll look into this soon

**Comment by Hidte09** [comment]
Ppsspp crashes on every build even buildbot build versions too gets crash 

https://github.com/hrydgard/ppsspp/assets/124633547/6b8c068c-d42d-4f40-a64d-f447bf8e3139

es.

**Comment by Gelo021** [comment]
> Ppsspp crashes on every build even buildbot build versions too gets crash
> 
>  Record_2024-02-21-21-03-46.mp4 
> es.

yes just like we told, install first 1.17.1.10 then install the latest, latest clean installation is currently has some first time setup bug

**Comment by sum2012** [comment]
fixed bt v1.17.1-20-g539882086 https://github.com/hrydgard/ppsspp/commit/53988208677e4e36a62fc5502d0aabd13e121cae
