### ISSUE TITLE
Vulkan MSAA x8 on linux causes really big performance issues on latest build.

### ISSUE THREAD

**Issue by AmyRoxwell** [hrydgard/ppsspp#18878]
### Game or games this happens in

All 3D games (mostly tested on monster hunter games)

### What area of the game

On Monster Hunter Freedom: 
1. Start a new game or continue a savefile
2. Walk forward until you see the village chief (the old dude with red robes)
3. walk close to him, frames will dip

![Screenshot_02202024_160908](https://github.com/hrydgard/ppsspp/assets/89411895/2351a58f-5a3c-4eac-805f-3cb18ac6d16b)

On Monster Hunter Freedom Unite and Freedom 2:
1. Continue an already started savefile
2. once you load, performance tanks

![Screenshot_02202024_174340](https://github.com/hrydgard/ppsspp/assets/89411895/a8efb27a-0a0e-46b6-a8bd-b35d6a125532)

This issue is not present on v1.16 and also doesn't seem to affect on x4 and x2 values for MSAA

### Speed seen in PPSSPP

64% (20/30) and 52.4% (16/30)

### Platform

Linux / BSD

### Mobile device model or graphics card (GPU)

RX 6600

### PPSSPP version affected

v1.17.1 and latest git build

### Last working version

v1.16

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the slowdown.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
MSAA 8x can consume a lot more memory bandwidth than 4x, maybe you're running up against a limitation of your GPU? 

We configure it exactly the same way as we do the other MSAA variants (4x, 2x) so if something is wrong, it's probably not in PPSSPP, rather in the GPU driver. There'w nothing we can do differently here.

**Comment by AmyRoxwell** [comment]
> MSAA 8x can consume a lot more memory bandwidth than 4x, maybe you're running up against a limitation of your GPU?
> 
> We configure it exactly the same way as we do the other MSAA variants (4x, 2x) so if something is wrong, it's probably not in PPSSPP, rather in the GPU driver. There'w nothing we can do differently here. 4x looks pretty good, anyway.

Now that you mentioned it, my drivers got updated, so maybe its now working as intended on linux or maybe a driver bug? well, at least is good to know its not an PPSSPP issue!! (and well, i was not planning to use them cuz i don't notice a real difference haha!)
