### ISSUE TITLE
Ps3 controller maps both R1 and L2 to Pad1.b5

### ISSUE THREAD

**Issue by coffeebird** [hrydgard/ppsspp#18875]
### Game or games this happens in

none

### What area of the game / PPSSPP

At control mapping screen. Official Sony Dual Shock 3 PS3 controller plugged into USB or Bluetooth. Control mapping for either R1 or L2 returns the same input of Pad1.b5

![linuxr1l2mapping](https://github.com/hrydgard/ppsspp/assets/36798270/c86a0706-b0df-4bda-bb73-429bcf766105)

Effectively mapping both bottons to 1 input with no way to distinguish them. 

PSP of course doesn't have R2 or L2 but I'd like to use these for custom mappings

### What should happen

Should be able to map R1 and L2 as their own respective inputs

Running the windows version through lutris, R1 and L2 are mapped as x360.R1 and x360.TriggerL+ respectively
![mappedinwine](https://github.com/hrydgard/ppsspp/assets/36798270/10ab76cf-6f8b-4644-95a1-333b216f77e0)

### Logs

VulkanMayBeAvailable: Device allowed ('SDL:Linux')
Vulkan library loaded ('libvulkan.so.1')
VulkanMayBeAvailable: Enumerating instance extensions
VulkanMayBeAvailable: Instance extension count: 23
VulkanMaybeAvailable: Instance extension found: VK_KHR_device_group_creation (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_external_fence_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_external_memory_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_external_semaphore_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_get_physical_device_properties2 (00000002)
VulkanMaybeAvailable: Instance extension found: VK_KHR_get_surface_capabilities2 (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_surface (00000019)
VulkanMaybeAvailable: Instance extension found: VK_KHR_surface_protected_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_wayland_surface (00000006)
VulkanMaybeAvailable: Instance extension found: VK_KHR_xcb_surface (00000006)
VulkanMaybeAvailable: Instance extension found: VK_KHR_xlib_surface (00000006)
VulkanMaybeAvailable: Instance extension found: VK_KHR_display (00000017)
VulkanMaybeAvailable: Instance extension found: VK_KHR_get_display_properties2 (00000001)
VulkanMaybeAvailable: Instance extension found: VK_EXT_acquire_drm_display (00000001)
VulkanMaybeAvailable: Instance extension found: VK_EXT_acquire_xlib_display (00000001)
VulkanMaybeAvailable: Instance extension found: VK_EXT_debug_report (0000000a)
VulkanMaybeAvailable: Instance extension found: VK_EXT_debug_utils (00000002)
VulkanMaybeAvailable: Instance extension found: VK_EXT_direct_mode_display (00000001)
VulkanMaybeAvailable: Instance extension found: VK_EXT_display_surface_counter (00000001)
VulkanMaybeAvailable: Instance extension found: VK_EXT_surface_maintenance1 (00000001)
VulkanMaybeAvailable: Instance extension found: VK_EXT_swapchain_colorspace (00000004)
VulkanMaybeAvailable: Instance extension found: VK_KHR_portability_enumeration (00000001)
VulkanMaybeAvailable: Instance extension found: VK_LUNARG_direct_driver_loading (00000001)
VulkanMayBeAvailable: Calling vkCreateInstance
VulkanMayBeAvailable: Vulkan test instance created successfully.
VulkanMayBeAvailable: Eligible device found: 'AMD Radeon RX 580 Series (RADV POLARIS10)'
VulkanMayBeAvailable: Ineligible device found and ignored: 'llvmpipe (LLVM 17.0.6, 256 bits)'
VulkanMayBeAvailable: Found working Vulkan API!
VulkanMayBeAvailable: Destroying instance
DEBUG: Vulkan might be available.
Info: We compiled against SDL version 2.28.5 and we are linking against SDL version 2.28.5. :)
ThreadManager::Init(compute threads: 8, all: 16)
13:34:516 Core/Config.cpp:365 I[G3D]: Longest display side: 1920 pixels. Choosing scale 2
OpenGL 2.0 or higher.
loading control pad mappings from gamecontrollerdb.txt: SUCCESS!
found control pad: Sony PLAYSTATION(R)3 Controller, loading mapping: SUCCESS, mapping is:
0300afd34c0500006802000011810000,Sony PLAYSTATION(R)3 Controller,platform:Linux,x:b3,a:b0,b:b1,y:b2,back:b8,guide:b10,start:b9,dpleft:b15,dpdown:b14,dpright:b16,dpup:b13,leftshoulder:b4,lefttrigger:a2,rightshoulder:b6,rightshoulder:b5,righttrigger:a5,leftstick:b7,leftstick:b11,rightstick:b12,leftx:a0,lefty:a1,rightx:a3,righty:a4,
pad 1 has been assigned to control pad: Sony PLAYSTATION(R)3 Controller
found control pad: Sony PLAYSTATION(R)3 Controller, loading mapping: SUCCESS, mapping is:
0300afd34c0500006802000011810000,Sony PLAYSTATION(R)3 Controller,platform:Linux,x:b3,a:b0,b:b1,y:b2,back:b8,guide:b10,start:b9,dpleft:b15,dpdown:b14,dpright:b16,dpup:b13,leftshoulder:b4,lefttrigger:a2,rightshoulder:b6,rightshoulder:b5,righttrigger:a5,leftstick:b7,leftstick:b11,rightstick:b12,leftx:a0,lefty:a1,rightx:a3,righty:a4,
Leaving main

### Platform

Linux / BSD
OpenSuSE Leap 15.5 Plasma Wayland

### Mobile device model or graphics card (GPU)

RX 580 8GB

### PPSSPP version affected

1.17.1

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [x] Try resetting settings or older versions and include if the issue is related.
- [x] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by coffeebird** [comment]
**Update:** I seem to have solved it by replacing the gamecontrollerdb.txt with one form [github](https://github.com/mdqinc/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt).

I couldn't find wherever the ppsspp assets folder is located in the flatpak version so I installed the one from my repo and replaced the gamecontrollerdb.txt in usr/lib/ppsspp/assets and that seemed to work. 

L2 and R1 respective mappings

![ppssppmappingworking](https://github.com/hrydgard/ppsspp/assets/36798270/8e63ed5e-98f7-4683-bc2f-e1a4fcde3df6)

**Comment by hrydgard** [comment]
Reopening, we should at least copy the relevant line

**Comment by coffeebird** [comment]
Sure thing.

From my logs after replacing gamecontrollderdb.txt

`loading control pad mappings from gamecontrollerdb.txt: SUCCESS!
found control pad: PS3 Controller, loading mapping: SUCCESS, mapping is:
030000004c0500006802000011810000,PS3 Controller,a:b0,b:b1,back:b8,dpdown:b14,dpleft:b15,dpright:b16,dpup:b13,guide:b10,leftshoulder:b4,leftstick:b11,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b12,righttrigger:a5,rightx:a3,righty:a4,start:b9,x:b3,y:b2,platform:Linux,
pad 1 has been assigned to control pad: PS3 Controller
found control pad: PS3 Controller, loading mapping: SUCCESS, mapping is:
030000004c0500006802000011810000,PS3 Controller,a:b0,b:b1,back:b8,dpdown:b14,dpleft:b15,dpright:b16,dpup:b13,guide:b10,leftshoulder:b4,leftstick:b11,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b12,righttrigger:a5,rightx:a3,righty:a4,start:b9,x:b3,y:b2,platform:Linux,
`

Relevant line from gamecontrollerdb.txt

`030000004c0500006802000011810000,PS3 Controller,a:b0,b:b1,back:b8,dpdown:b14,dpleft:b15,dpright:b16,dpup:b13,guide:b10,leftshoulder:b4,leftstick:b11,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b12,righttrigger:a5,rightx:a3,righty:a4,start:b9,x:b3,y:b2,platform:Linux`

**Comment by hrydgard** [comment]
Thank you, updated the line.
