### ISSUE TITLE
Responding to ACTION_VIEW (Android TV)

### ISSUE THREAD

**Issue by tvdev7805** [hrydgard/ppsspp#18885]
### Game or games this happens in

None

### What area of the game / PPSSPP

When attempting to open a .iso or .cso file from the file listing of my saf file picker or a file manager, it employs ACTION_VIEW. On Android TV 9, I attempted to initiate an ACTION_VIEW intent with a URI from FileProvider. PPSSPP responds to this if the file is located in external storage (under /storage/emulated/0). However, when the file is on a USB disk, FileProvider cannot generate a URI for it because it's under /storage/xxxx-xxxx. In this scenario, I must return a content URI like content://media/external.... In such cases, PPSSPP's intent filter is not activated for this URI.

### What should happen

In this scenario, is there a method for PPSSPP to be included as an application capable of opening this file? Alternatively, is there a custom MIME file type available for these ROM files that PPSSPP can accommodate?

### Platform

Android

### Mobile device model or graphics card (GPU)

Fire TV cube gen 2

### PPSSPP version affected

1.17.1

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
If the issue is that our intent filter is not activated at all, I guess we need some change to that. If we do catch it and then mishandle the url, show me a full url and I'll try to figure out why. 

Looking at logs should make it possible to figure out which of the two scenarios are happening

**Comment by tvdev7805** [comment]
It's the first case, error message on fire tv is "no apps can perform this action", currently if I query mime type of these extensions, application/oct-stream is returned,
