### ISSUE TITLE
LOAD... game using SAF on FireTV 0S 7.6 (AndroidTV 9) issue

### ISSUE THREAD

**Issue by tvdev7805** [hrydgard/ppsspp#18884]
### Game or games this happens in

None

### What area of the game / PPSSPP

When using LOAD... to load a game (iso,cso) on FireTV cube 2nd gen which has a AndroidTV9 OS, there is a native FILE app to use (but that didn't work at all with remote anyway). When I use my own SAF file picker UI (S2X file manager), when my app returned an  uri with permission, the PPSSPP shows an error, 
"Could not load game. Unknown file type: content://media/external/file/32460"

### What should happen

The URI returned to PPSSPP should work, on another Android TV box like mi tv stick (android tv 11), mi box s gen 2 (google tv, android tv 12), the returned URI worked with PPSSPP.

I also tried to return a URI from a FileProvider but it's the same error "Unknown file type"

### Platform

Android

### Mobile device model or graphics card (GPU)

FireTV cube gen2 

### PPSSPP version affected

v1.12.2 gold (I can only find this in amazon store)

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by tvdev7805** [comment]
Apologies for any inconvenience caused. When I sideloaded the latest version of PPSSPP onto FireTV, it worked fine.

**Comment by hrydgard** [comment]
That's right, I fixed an issue related to failing to detect file extensions in similar cases to this a little while ago.
