### ISSUE TITLE
Mega Man Powered Up crashes on startup

### ISSUE THREAD

**Issue by bslenul** [hrydgard/ppsspp#18880]
### Game or games this happens in

ULUS10091 - Mega Man Powered Up

### What area of the game / PPSSPP

At launch, you can very briefly see the "now loading" text then PPSSPP shuts down completely.

### What should happen

It shouldn't crash.

### Logs

[ppsspplog.txt](https://github.com/hrydgard/ppsspp/files/14375145/ppsspplog.txt)

### Platform

Windows

### Mobile device model or graphics card (GPU)

RTX 3060 Ti

### PPSSPP version affected

v1.17.1-17-g9c2096b70

### Last working version

v1.17.1-10-g9322b4c6d

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by bslenul** [comment]
c5791764d844744ecda441e003fede16d6091bb0 seems to be the first "bad" commit, no crash with the previous ocmmit (9322b4c6dc9136eb6c5e751a56b078d013d96b6c).

**Comment by anr2me** [comment]
You may want to select tthe code on PPSSPP side (ie. the PSPMsgDialog::Update part) instead of the std library before making the screenshot

**Comment by gabberhead** [comment]
i have the same problem with the libretro core, but not only with this game. but with the standalone ppsspp, this and the other games which i have problems in retroarch, are loading without a problem

**Comment by bslenul** [comment]
> You may want to select the code on PPSSPP side on the call stack (ie. the PSPMsgDialog::Update part) instead of the std library before making the screenshot

Like this you mean (sorry I suck at debugging :D)?

![image](https://github.com/hrydgard/ppsspp/assets/33353403/2ae58a07-4452-4bb9-be1c-12d9ed8a2229)
