### ISSUE TITLE
Rename the option "Auto (same as rendering resolution)" to just "Same as rendering resolution"

### ISSUE THREAD

**Issue by WarmestKrafter** [hrydgard/ppsspp#18897]
### What should happen

The word "Auto" in that option is kinda excessive because it only makes the display resolution looks the same as rendering resolution and it doesn't have any automatic function in it, maybe?

### Who would this benefit

I don't know, maybe some people who have OCD or some people think that was poorly written

### Platform (if relevant)

None

### Games this would be useful in

None

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
IIRC, a long time ago it was just named "Auto" which was confusing so we added the rest of the name.

That said, you're right that it's kinds redundant and I guess this change would be reasonable.
