### ISSUE TITLE
can't build emulator in RetroPie Lubuntu

### ISSUE THREAD

**Issue by Remeedella** [hrydgard/ppsspp#18905]
### Platform

Linux / BSD

### Compiler and build tool versions

clang 6.0 lubuntu2 + cmaker 28

### Operating system version

Lubuntu 18.04.05

### Build commands used

I'm trying to install from source (updated packages) from within RetroPie setup , I guess that uses RetroArch, I try ppsspp and lr-ppsspp

I did not 'Make sure to run git submodule update --init --recursive before building.' because I don't know much about this and I'm trying to install it using the provided packages from RetroPie

### What happens

![PXL_20240303_221339467](https://github.com/hrydgard/ppsspp/assets/48421985/47791a98-8ee6-43e6-95d6-e29654ad7c8d)
Install from Source in RetroPie fails at around 57% with ppsspp or lr-ppsspp 'could not successfully build ppsspp - (*****/tmp/build/ppsspp/ppsspp/PPSSPPSDL not found)

I have attached the log below,
**
[rps_2024-03-03_170517.log](https://github.com/hrydgard/ppsspp/files/14474956/rps_2024-03-03_170517.log)

**

### PPSSPP version affected

looks to be v1.16.6 / is there newer available from RetroPie?

### Last working version

0

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] Make sure to run `git submodule update --init --recursive` before building.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try deleting the build directory and running the build again.
- [ ] Check GitHub Actions, which builds every merge and PR.
- [X] Include logs and help us reproduce.

**Comment by anr2me** [comment]
```
/home/jship/RetroPie-Setup/tmp/build/ppsspp/ppsspp/SDL/SDLVulkanGraphicsContext.cpp:117:67: error: ‘union SDL_SysWMinfo::<unnamed>’ has no member named ‘wl’
   vulkan_->InitSurface(WINDOWSYSTEM_WAYLAND, (void*)sys_info.info.wl.display, (void *)sys_info.info.wl.surface);
                                                                   ^~
```

Probably similar issue to https://github.com/anbox/anbox/issues/915
> Looks like you're building against a SDL version without wayland support.

**Comment by hrydgard** [comment]
SDL version mismatch. Not a problem with anything PPSSPP has in its repository, rather with whatever build script or similar you are using. And indeed you shouldn't be using one that builds an old PPSSPP. Closing.
