### ISSUE TITLE
add a native .pmf player (could work with .at3 files, etc)

### ISSUE THREAD

**Issue by xor32dotcom** [hrydgard/ppsspp#18902]
### What should happen

when a .pmf is dragged and dropped it should just be played by the emulator and probably a text notification informing the user they succesfully imported a valid .pmf 

### Who would this benefit

literally anyone who knows what a .pmf is

### Platform (if relevant)

None

### Games this would be useful in

all

### Other emulators or software with a similar feature

all emulators have functions that can easily handle this

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by LunaMoo** [comment]
Although in different issues, it was said many times that PPSSPP is not a video player and no work towards making it so will be done.

 There's some awful third party project that steals various emulator work and unifies them under awful UI together with other software like video players which you might be confusing you as it's not an emulator.
 Actual emulators doesn't do that and tend to have similar stance. 

 Just use dedicated video player and codecs for what you want.
