### ISSUE TITLE
Helicooter blade bug in GTA Vice City Stories

### ISSUE THREAD

**Issue by WarmestKrafter** [hrydgard/ppsspp#18901]
There's a bug in this game, I don't know how to fix this. Is this an in-game bug or the emulator rendering bug?

https://github.com/hrydgard/ppsspp/assets/112315947/97aa381e-65b7-460b-b4bb-2327bf7aea27

Device: POCO M5
Chipset: Helio G99
Backend: OpenGL

**Comment by LunaMoo** [comment]
Soo what's exactly the bug? Do you mean flatness of the blade texture?
 That would be normal in games from that era, don't expect it to look like modern games. Especially PSP versions of multiplatform games which had to deal with a lot of hardware limitations tend to be really ugly and also why PPSSPP has soo much support for making at least some things prettier(nothing going to change the blade flatness through as it's just a 2D animation on a flat surface).

**Comment by WarmestKrafter** [comment]
No, Don't you see the helicooter blade texture being squared up?

**Comment by WarmestKrafter** [comment]
> Soo what's exactly the bug? Do you mean flatness of the blade texture? That would be normal in games from that era, don't expect it to look like modern games. Especially PSP versions of multiplatform games which had to deal with a lot of hardware limitations tend to be really ugly and also why PPSSPP has soo much support for making at least some things prettier(nothing going to change the blade flatness through as it's just a 2D animation on a flat surface).

That not what I meant. Don't you see the curve of the helicopter blade looks squared instead of being a smooth circle?

**Comment by Sabirmd111** [comment]
> > Soo what's exactly the bug? Do you mean flatness of the blade texture? That would be normal in games from that era, don't expect it to look like modern games. Especially PSP versions of multiplatform games which had to deal with a lot of hardware limitations tend to be really ugly and also why PPSSPP has soo much support for making at least some things prettier(nothing going to change the blade flatness through as it's just a 2D animation on a flat surface).
> 
> That not what I meant. Don't you see the curve of the helicopter blade looks squared instead of being a smooth circle?

**Comment by hrydgard** [comment]
Hm, maybe the texture has mipmaps that look more squarish, which would be visible at such an angle.

Do you see this on a real PSP? Did you enable "Texture filtering: Auto max quality"?

**Comment by NABN00B** [comment]
Personally I find it difficult to tell, but I'll link some footage.

from PSTV https://youtu.be/54DmF-qzqFY?feature=shared&t=11072
from PSP https://youtu.be/1kRwOXdLkB4?feature=shared&t=8070

**Comment by NABN00B** [comment]
I've just charged my PSP to try this and due to the resolution it's really difficult to tell for sure. What I see is that as the heli blade texture comes closer to being horizontal on view, it is also becoming more and more distorted very long vertical line . This effect is also showcased in OP's video. The texture becoming square-ish could be part of this visual transition.

**Comment by hrydgard** [comment]
Yeah, I think we can conclude that this is likely simply a game "bug", if you can call it that since its hardly visible on the real PSP screen, likely as NABN00B says due to the low resolution. I'm going to close.
