### ISSUE TITLE
(Question) Does the "InternalResolution" variable support custom resolution?

### ISSUE THREAD

**Issue by hardBSDk** [hrydgard/ppsspp#18911]
I want to use a custom resolution (800x600, for example) in the INI file of my game, does it support it?

If the answer is "No", can you implement it?

**Comment by anr2me** [comment]
I think if it's not in the same aspect ratio to PSP native resolution, it can cause graphical glitches, and you will probably regrets using it :)

**Comment by hrydgard** [comment]
Yeah, it's not just the aspect ratio (480x272 is almost 16;9, but not quite), but also about some graphical tricks that PSP games are using. PSP games assume they are running at 480x272. Often what they do still works fine or at least well enough at double or triple the resolution (a notable exception is Cars Race-o-Rama which really can only work at 1x), but there are some tricks that break. So allowing say 1.5x or similar will create more unnecessary bug reports, which I don't want.

**Comment by hrydgard** [comment]
Though, if you all you want to do is chnage the aspect ratio:

![image](https://github.com/hrydgard/ppsspp/assets/130929/a1da387c-8a91-47f3-9aa7-48b7b6fe2d41)

(on the "Display layout and effects" scren)
