### ISSUE TITLE
(macOS) Unexpected Quit When Trying to Log in to Retroachievements

### ISSUE THREAD

**Issue by EddyStalin** [hrydgard/ppsspp#18955]
### Game or games this happens in

UCES00842 GOD OF WAR CHAINS OF OLIMPUS

### What area of the game / PPSSPP

When using RetroAchievements, the emulator closes itself

### What should happen

It should work normally as it worked correctly in version 1.6.0

### Platform

macOS

### Mobile device model or graphics card (GPU)

iMac (21.5-inch, Mid 2011) Radeon HD 6750M 512 MB

### PPSSPP version affected

v1.7.1

### Last working version

v1.6.0

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Hm, I tried, but I'm unable to reproduce this problem. It works just fine for me, whether I try to login when the game is already running or not.

I've been testing on the latest build though.

**Comment by EddyStalin** [comment]
https://github.com/hrydgard/ppsspp/assets/104610282/f4b1090d-612f-4a62-ba18-ef8c0c35e124

**Comment by hrydgard** [comment]
Could you try this with 1.17.1-74 from https://www.ppsspp.org/devbuilds/ ?

**Comment by danssmnt** [comment]
Not related, but wouldn't it be nice if it hid the password while you're typing it? I just feel it's a potential security risk.

**Comment by hrydgard** [comment]
@danssmnt yeah, that would be better, just haven't gotten around to adding a proper password input

**Comment by hrydgard** [comment]
Ok, implemented password masking on most platforms now: #19492

**Comment by hrydgard** [comment]
Also, I still can't reproduce this in the latest builds. Closing. Please re-open if it still happens.

(I'll run my sporadic Mac buildbot to produce some new builds shortly)
