### ISSUE TITLE
Strange redefine numBytesRendered in DSoundStream

### ISSUE THREAD

**Issue by GermanAizek** [hrydgard/ppsspp#18968]
@hrydgard,
why is there redefinition numBytesRendered in this section code?
Is it intentional to call callback with parameter?

https://github.com/hrydgard/ppsspp/blob/744678b5b32138953d9f6f3956ee2ba12d36e7bb/Windows/DSoundStream.cpp#L124-L131

**Comment by hrydgard** [comment]
That looks weird indeed. this is ancient code (10+ years old) so I don't remember if there was a reason. will look into it.

**Comment by hrydgard** [comment]
No, it's intentional, the comment (kind of) explains it - we intentionally ignore the return value.
