### ISSUE TITLE
(AUR) Cannot build the ppsspp-git package

### ISSUE THREAD

**Issue by Relwi** [hrydgard/ppsspp#18961]
### Platform

Linux / BSD

### Compiler and build tool versions

Clang 17.0.6 + Cmake 3.29.0

### Operating system version

Arch Linux x86_64

### Build commands used

Used in the [ppsspp-git](https://aur.archlinux.org/packages/ppsspp-git) package
```
export CC=clang
export CXX=clang++

# Rebuild ffmpeg locally
pushd ppsspp/ffmpeg
case "$CARCH" in
  x86_64)
    ./linux_x86-64.sh
    ;;
  aarch64)
    ./linux_arm64_native.sh
    ;;
esac
popd

cmake -S ppsspp -B build-sdl -G Ninja \
  -Wno-dev \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_SKIP_RPATH=ON \
  -DHEADLESS=ON \
  -DOpenGL_GL_PREFERENCE=GLVND \
  -DUSE_SYSTEM_FFMPEG=OFF \
  -DUSE_SYSTEM_MINIUPNPC=OFF \
  -DUSE_SYSTEM_LIBZIP=ON \
  -DUSE_SYSTEM_SNAPPY=ON \
  -DUSE_SYSTEM_ZSTD=ON \
  -DUSING_QT_UI=OFF
cmake --build build-sdl -v
cmake -S ppsspp -B build-qt -G Ninja \
  -Wno-dev \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_SKIP_RPATH=ON \
  -DHEADLESS=OFF \
  -DOpenGL_GL_PREFERENCE=GLVND \
  -DUSE_SYSTEM_FFMPEG=OFF \
  -DUSE_SYSTEM_MINIUPNPC=OFF \
  -DUSE_SYSTEM_LIBZIP=ON \
  -DUSE_SYSTEM_SNAPPY=ON \
  -DUSE_SYSTEM_ZSTD=ON \
  -DUSING_QT_UI=ON
cmake --build build-qt -v
```

### What happens

`/home/relwi/.cache/paru/clone/ppsspp-git/src/ppsspp/Common/VR/OpenXRLoader.h:46:10: fatal error: 'openxr/openxr.h' file not found`

### PPSSPP version affected

Latest versions

### Last working version

Don't remember well, but maybe 2~3 weeks ago

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] Make sure to run `git submodule update --init --recursive` before building.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try deleting the build directory and running the build again.
- [ ] Check GitHub Actions, which builds every merge and PR.
- [X] Include logs and help us reproduce.

**Comment by anr2me** [comment]
May be @lvonasek know

**Comment by lvonasek** [comment]
No idea what is the source of the issue but you could try to add -DOPENXR.

**Comment by lvonasek** [comment]
The file is for sure part of the submodule.

Redo `git submodule update --init --recursive`

**Comment by Relwi** [comment]
Aparently the AUR has to be updated because it doesn't cloning the OpenXR-SDK submodule. I changed the PKGBUILD and now it works. Thanks!
