### ISSUE TITLE
Question about SimulateLogicOpShaderTypeIfNeeded function

### ISSUE THREAD

**Issue by GermanAizek** [hrydgard/ppsspp#18988]
@hrydgard, I have question for you is it correct that case GE_LOGIC_INVERTED returns LOGICOPTYPE_ONE, after all, it refers to the inverted, or am I mistaken?

https://github.com/hrydgard/ppsspp/blob/62b14504145ff1676278f964c80ef2d73d33578f/GPU/Common/GPUStateUtils.cpp#L996-L1010

**Comment by hrydgard** [comment]
I think we do the rest of the inversion elsewhere, like in the shader, in this case. Been a while.

I'll try to look at it later and add a comment.

(as a side note, logic op render operations are super rare).

**Comment by hrydgard** [comment]
Yeah, this works together with SimulateLogicOpIfNeeded - by combining blend state tricks and some changes to shader output, we can simulate the effects of most common logic ops even when it's not supported. It's not a bug.
