### ISSUE TITLE
Strange enum value in D3D10_FILTER::D3D10_FILTER_TEXT_1BIT

### ISSUE THREAD

**Issue by GermanAizek** [hrydgard/ppsspp#18998]
@hrydgard, 
By default, enum is regular int, and it clearly goes beyond an integer and therefore it is negative.
But it's good that value `D3D10_FILTER_TEXT_1BIT = 0x80000000` is not used anywhere in code.

![image](https://github.com/hrydgard/ppsspp/assets/21138600/84a3fa9c-7695-4161-999f-29089ab40780)

**Comment by hrydgard** [comment]
Fortunately this is not something we use, at all, and is not even in our header.
