### ISSUE TITLE
Strange members overriden in subclasses

### ISSUE THREAD

**Issue by GermanAizek** [hrydgard/ppsspp#19003]
@hrydgard, is there difference between

1. View::DescripeLog() and UI::ScrollView::DescribeLog() ?

    https://github.com/hrydgard/ppsspp/blob/22fdf6624c7293930996b846edaea89981ffd10c/Common/UI/ScrollView.h#L21

2. View::DescripeLog() and  UI::ViewGroup::DescribeLog()?
    https://github.com/hrydgard/ppsspp/blob/22fdf6624c7293930996b846edaea89981ffd10c/Common/UI/ScrollView.h#L139

**Comment by hrydgard** [comment]
This is all intentional. DescribeLog is just debug output anyway.
