### ISSUE TITLE
Boku no Natsuyasumi crashing after playing a certain cinematic

### ISSUE THREAD

**Issue by GriffithVIII** [hrydgard/ppsspp#19011]
### Game or games this happens in

UCJS-10038 - ぼくのなつやすみ ポータブル (Boku no Natsuyasumi)

### What area of the game / PPSSPP

When watching a cinematic of some fireworks that only occurs on day 8 of the game (to see the cinematic you have to interact with the window in Boku's room at night. To pass the time one just need to go from a room to another. With turbo activated it would be faster). **After the cinematic finishes playing**, the emulator freezes on a black screen and I cannot even close the emulator.

- **This behavior doesn't happen when playing the intro and other cinematics.**
- All cinematics are in PMF format.
- Skipping the cinematic prevents the crash.

Video:

https://github.com/hrydgard/ppsspp/assets/51249452/b8a2727c-3b09-4099-b4d4-877538851c53

My savedata:
[UCJS10038S007N.zip](https://github.com/hrydgard/ppsspp/files/14894495/UCJS10038S007N.zip)

### What should happen

After playing the cinematic and showing the black screen, the game should go back to Boku's Room.

Gameplay video on real PSP:

https://github.com/hrydgard/ppsspp/assets/51249452/603c713c-c489-49b8-9150-a28b8037768e

### Logs

[ppsspplog.txt](https://github.com/hrydgard/ppsspp/files/14894617/ppsspplog.txt)

### Platform

Windows

### Mobile device model or graphics card (GPU)

AMD Radeon(TM) Vega 3 Graphics

### PPSSPP version affected

 v1.17.1-d479b74

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by sum2012** [comment]
@GriffithVIII can yo record how to go to Boku's room ?

**Comment by sum2012** [comment]
![3](https://github.com/hrydgard/ppsspp/assets/2177532/59b124e8-2849-45f4-9e13-6d85f444f1a0)

It seems never exit the loop

**Comment by hrydgard** [comment]
Hm, that loop needs a max number of retries before it gives up.. though, still seems like something is wrong, of course.

**Comment by sum2012** [comment]
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/14918552/ppsspplog.zip)
psmfplayer->mediaengine->stepVideo(videoPixelMode, true);
Seem don't change the value of getVideoTimeStamp 2177175, getAudioTimeStamp 2193534 psmfPlayerAvcAu 2174172
