### ISSUE TITLE
No korean fonts during save creation

### ISSUE THREAD

**Issue by ppmeis** [hrydgard/ppsspp#1904]
Title: Dj Max Portable
Region: KR
Format : CSO
Emu Version : v0.7.6-779-gb8c649b
Game ID : ULKS46050
OS : Windows 8 Pro 64Bits

While playing Dj Max Portable and maybe others there's a bug with fonts at save creation. PSP system menu is displayed and appears squares instead of korean fonts:

![koreanerror](https://f.cloud.github.com/assets/4381277/559962/2981e244-c462-11e2-9f4d-0edbbf407b79.png)

Logfile: http://goo.gl/3jnkc

**Comment by ppmeis** [comment]
Tested with latest build. Issue is present.

**Comment by ppmeis** [comment]
Tested with latest build. Same status.

**Comment by ppmeis** [comment]
Tested with latest build. Even with proper PSP fonts it happens.

**Comment by unknownbrackets** [comment]
Yeah, save screens do not actually use the flash0 fonts right now.

-[Unknown]

**Comment by ppmeis** [comment]
Tested with latest build. Same status.

**Comment by ppmeis** [comment]
Tested in latest build. It works fine in Dj Max Portable
![image](https://cloud.githubusercontent.com/assets/4381277/13197341/3ae1b58c-d7ec-11e5-929e-cce21d934891.png)

Unfortunately, a few fonts are still missing in Dj Max Portable 2:
![image](https://cloud.githubusercontent.com/assets/4381277/13197395/16ce7ee0-d7ed-11e5-8e46-875b3e7ffa92.png)

There's a huge progress. Keep fixing ;).

**Comment by unknownbrackets** [comment]
I think we pulled in more characters recently with an updated learning file.

-[Unknown]

**Comment by ppmeis** [comment]
Tested with latest build. Some characters are still missed:

![image](https://cloud.githubusercontent.com/assets/4381277/15275407/1cb7d07e-1acb-11e6-8f54-d8bdf9773118.png)

**Comment by ppmeis** [comment]
Tested with latest build. Same status:
![image](https://user-images.githubusercontent.com/4381277/33262231-e7167736-d365-11e7-91c3-dd82eb417052.png)

**Comment by Panderner** [comment]
In locoroco 2 I selected Korean language and there's no Korean characters except Punctuations and numbers:
![Screenshot_2020-03-11-18-48-46-69_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/76409358-39f2a100-63c9-11ea-8948-bb41d31f374d.png)

**Comment by hrydgard** [comment]
That's an unrelated and quite odd bug...  (this bug is about the PSP system dialogs)
