### ISSUE TITLE
PPSSPP Libretro building issue on Emuelec - > Core/FFMPEGCompat.h:5:17: error: duplicate 'const'     5 | #define AVCodec const AVCodec

### ISSUE THREAD

**Issue by Kelvfimer** [hrydgard/ppsspp#19049]
### Platform

libretro / Retroarch

### Compiler and build tool versions

CMAKE 3.24.2

### Operating system version

ubuntu 22.04 toolchain Emuelec Odroid n2+

### Build commands used

PROJECT=Amlogic-ce DEVICE=Amlogic-ng ARCH=aarch64 DISTRO=EmuELEC ./scripts/build ppsspp
PROJECT=Amlogic-ce DEVICE=Amlogic-ng ARCH=aarch64 DISTRO=EmuELEC ./scripts/build PPSSPPSDL

### What happens

When compiling PPSSPP Libretro or regular PPSSPPSDL starting on commit https://github.com/hrydgard/ppsspp/commit/c6f5ac0c81933dd6d3fdd37b0acc7a5062a500e3 it fails with error 

[557/960] Building CXX object CMakeFiles/Core.dir/Core/HW/SimpleAudioDec.cpp.o
FAILED: CMakeFiles/Core.dir/Core/HW/SimpleAudioDec.cpp.o

/home/kelv/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/PPSSPPSDL-71a6372ac587519c53e060ce48778b03489a3c05/Core/HW/SimpleAudioDec.cpp: At global scope:
/home/kelv/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/PPSSPPSDL-71a6372ac587519c53e060ce48778b03489a3c05/Core/FFMPEGCompat.h:5:17: error: duplicate 'const'
    5 | #define AVCodec const AVCodec

LOG FIles
[PPSSPP error duplicate const AVCODEC.txt](https://github.com/hrydgard/ppsspp/files/14960695/PPSSPP.error.duplicate.const.AVCODEC.txt)

### PPSSPP version affected

c6f5ac0c81933dd6d3fdd37b0acc7a5062a500e3

### Last working version

6575ba54874e1965f28d72fc85198f5f28724c85

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] Make sure to run `git submodule update --init --recursive` before building.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try deleting the build directory and running the build again.
- [X] Check GitHub Actions, which builds every merge and PR.
- [X] Include logs and help us reproduce.

**Comment by hrydgard** [comment]
Should be fixed in c2bcdd3

If not, please re-open.
