### ISSUE TITLE
[Win64] Local Windows Command Injection in cmdline parameters

### ISSUE THREAD

**Issue by GermanAizek** [hrydgard/ppsspp#19067]
### Happy example:

![image](https://github.com/hrydgard/ppsspp/assets/21138600/e9f8d6d6-486f-4ed6-9984-bcc40979e50b)

**Comment by anr2me** [comment]
btw does `!` also works?

**Comment by hrydgard** [comment]
uh, isn't this just shell tricks, given the pipe and & ?  Is it really PPSSPP that launches dir?

**Comment by GermanAizek** [comment]
@hrydgard, I experimented, yes, maybe it's because I run it under the shell, if I run exe debugging with arguments, this does not happen on F5 in Visual Studio, maybe I'm doing it wrong.

**Comment by GermanAizek** [comment]
It seems to me that shell itself specifically allows separation by such operators so that you can make several instructions in one line.
