### ISSUE TITLE
Lost camera support

### ISSUE THREAD

**Issue by GudraFree** [hrydgard/ppsspp#19068]
### Game or games this happens in

UCES-01241 - inviZimals

### What area of the game / PPSSPP

Camera is not being recognized. It has a set input, but the emulator doesn't appear to pick it up. Also, will crash when trying to create a savestate in this screen.

This is a screen where the supposed camera input should be, in the first instance it appears in the tutorial. Game replaces it by a blue-yellow gradient. The overlay is shown independently of if there is camera input or not:
![UCES01241_00000](https://github.com/hrydgard/ppsspp/assets/31284742/a192057c-5270-4875-bf6b-6e49619c8a91)

This is my camera in the settings (virtual camera software to use phone camera as input)
![imagen](https://github.com/hrydgard/ppsspp/assets/31284742/f3efad0b-6891-4869-a166-85c8cd077cfe)

### What should happen

This is the 
![UCES01241_00000](https://github.com/hrydgard/ppsspp/assets/31284742/2d086e84-b65a-4db7-bff3-b83edc2199e8)
same scenario but in stable version 1.17.1:

Same camera, same settings (except language because it picks my locale)
![imagen](https://github.com/hrydgard/ppsspp/assets/31284742/25f7dfae-9acf-4f4a-bcb1-b4e1e8cf9d7a)

### Platform

Windows

### Mobile device model or graphics card (GPU)

NVIDIA GeForce GTX 1060 6GB

### PPSSPP version affected

v1.17.1-317

### Last working version

v1.17.1

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Bisection says its one of:

c9029736886fef7463c4e2c1c7f0ec9ad1334876
fb906481cc9ed9e25793fdd69c5929686f71b1ff
8fbc4a33798f93d52142a8b31250753d0e3b8299

I think I accidentally disabled and never re-enabled some part of ffmpeg we use to convert camera images, during my recent refactorings. Will fix soon.
