### ISSUE TITLE
Why did the pictures wallpapers of the games in the pause menu disappear?

### ISSUE THREAD

**Issue by Playervcs** [hrydgard/ppsspp#19077]
### Game or games this happens in

GTA Vice City Stories 

### What area of the game

pause menu 
### What happens

There were unique wallpapers in the pause menu for each game, as for me it was more interesting than a blank screen.
![image](https://github.com/hrydgard/ppsspp/assets/165839620/159fbc07-62d0-4c0d-b889-88c3a4dca320)

### What should happen

Please return it as it was

### Platform

Windows

### Mobile device model or graphics card (GPU)

GTX 1050ti

### PPSSPP version affected

1.17.1

### Last working version

1.16.1

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by Playervcs** [comment]
in latest version just nothing 
![image](https://github.com/hrydgard/ppsspp/assets/165839620/e6787ed2-86df-40f1-81fd-de91324709e4)

**Comment by hrydgard** [comment]
in the latest version, assuming you have buffered rendering enabled, you should see a screenshot of the game as a background.

I'll take a look a the case of buffered rendering off, it shouldn't have changed.

**Comment by Playervcs** [comment]
> in the latest version, assuming you have buffered rendering enabled, you should see a screenshot of the game as a background.
> 
> I'll take a look a the case of buffered rendering off, it shouldn't have changed.

A screenshot of the game? And then why do I need the transparent background option? I didn't understand a bit

**Comment by hrydgard** [comment]
OK, I see the issue now. For some reason it seems to work once, and then not any more. I'll debug and fix it.
