### ISSUE TITLE
ppsspp from git does not build on Ubuntu 22.04 x86_64 (cmake fails)

### ISSUE THREAD

**Issue by joroOnLinux** [hrydgard/ppsspp#19078]
### Platform

Linux / BSD

### Compiler and build tool versions

gcc / cmake 

### Operating system version

Ubuntu jammy 

### Build commands used

mkdir builld && cd build && cmake ..

### What happens

Generating for x86_64, Release
CMake Error at ext/CMakeLists.txt:8 (add_subdirectory):
  The source directory

    /home/jochen/sources/ppsspp/ext/armips

  does not contain a CMakeLists.txt file.

CMake Error: File /home/jochen/sources/ppsspp/ext/cpu_features/cmake/CpuFeaturesConfig.cmake.in does not exist.
CMake Error at /usr/share/cmake-3.22/Modules/CMakePackageConfigHelpers.cmake:342 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  ext/cmake/cpu_features/CMakeLists.txt:181 (configure_package_config_file)

CMake Error at ext/CMakeLists.txt:29 (add_subdirectory):
  The source directory

    /home/jochen/sources/ppsspp/ext/glslang

  does not contain a CMakeLists.txt file.

-- Could NOT find Snappy (missing: SNAPPY_LIBRARIES SNAPPY_INCLUDE_DIR) 
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find FFmpeg (missing: FFmpeg_INCLUDE_avcodec
  FFmpeg_LIBRARY_avcodec FFmpeg_INCLUDE_avformat FFmpeg_LIBRARY_avformat
  FFmpeg_INCLUDE_avutil FFmpeg_LIBRARY_avutil FFmpeg_INCLUDE_swresample
  FFmpeg_LIBRARY_swresample FFmpeg_INCLUDE_swscale FFmpeg_LIBRARY_swscale
  avcodec avformat avutil swresample swscale)
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindFFmpeg.cmake:165 (find_package_handle_standard_args)
  CMakeLists.txt:955 (find_package)

-- Configuring incomplete, errors occurred!

### PPSSPP version affected

ppsspp from git

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] Make sure to run `git submodule update --init --recursive` before building.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try deleting the build directory and running the build again.
- [ ] Check GitHub Actions, which builds every merge and PR.
- [ ] Include logs and help us reproduce.

**Comment by anr2me** [comment]
why not building it using `./b.sh --release` command from the ppsspp directory ?

**Comment by sum2012** [comment]
@joroOnLinux 
git submodule update --init --recursive

**Comment by joroOnLinux** [comment]
@sum2012 thanks, cmake configures succesfully now.
Issue can be closed.

**Comment by joroOnLinux** [comment]
> why not building it using `./b.sh --release` command from the ppsspp directory ?

because it's not called 'build.sh' ?

**Comment by anr2me** [comment]
> > why not building it using `./b.sh --release` command from the ppsspp directory ?
> 
> because it's not called 'build.sh' ?

As mentioned at wiki https://github.com/hrydgard/ppsspp/wiki/Build-instructions#building-with-cmake-other-platforms-eg-linux
`./b.sh` should works on many platforms (ie. using --qt to build QT version, --ios to build iOS version, etc)
