### ISSUE TITLE
Gods Eater 2 Audio Bug

### ISSUE THREAD

**Issue by Gelo021** [hrydgard/ppsspp#19075]
Hi again @hrydgard i just notice that the latest 329 have a audio bug 
tested at 1.17.1
https://github.com/hrydgard/ppsspp/assets/67460268/7e184828-bc27-4e2a-9f4c-c23ac0930d5c

tested at 1.17.1-329
https://github.com/hrydgard/ppsspp/assets/67460268/fcc5e95e-b860-4f32-b030-6b2970108ea3

btw its Gods Eater 2

**Comment by sum2012** [comment]
@hrydgard No history build in https://www.ppsspp.org/devbuilds/ ?

**Comment by hrydgard** [comment]
Interesting! I'll look into it soon. Might be a regression from the Atrac refactorings.

**Comment by sum2012** [comment]
@hrydgard  The buildbot is slow ,I cannot download to test it.
![3](https://github.com/hrydgard/ppsspp/assets/2177532/d38c2ffd-179a-41ab-baf9-89caf07d655e)

**Comment by hrydgard** [comment]
Strange, I just downloaded a couple of builds and it was fine. But I'll look into it.

**Comment by Gelo021** [comment]
ill try the latest build again

**Comment by hrydgard** [comment]
Latest [build](https://www.ppsspp.org/devbuilds/) has the fix.
