### ISSUE TITLE
Marvel Ultimate Alliance ad hoc

### ISSUE THREAD

**Issue by CristobalManga** [hrydgard/ppsspp#19081]
### Game or games this happens in

ULES00542

### What area of the game / PPSSPP

I thought someone had reported this bug in the ad hoc, but no one has.

The ad hoc of this just doesn't work. When creating the room and clicking start, an error appears.

![image](https://github.com/hrydgard/ppsspp/assets/78171867/eb0c48a0-8853-48fa-b58b-d9961c920a42)

I don't know if the error is ad hoc or an error in the game emulation.

### What should happen

work

### Platform

Windows

### Mobile device model or graphics card (GPU)

i3 - 4160

### PPSSPP version affected

v1.17.1-329

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by anr2me** [comment]
Have you checked whether your ISO's CRC is valid or not? in case the ISO was corrupted

**Comment by CristobalManga** [comment]
I looked up how to check the CRC, and according to the results, it is the correct one.

**Comment by anr2me** [comment]
I'm seeing `Unimplemented HLE function sceAudioInputInitEx` on the Host/Join selection, and got blue screen when selecting Post Game on Host menu
![image](https://github.com/hrydgard/ppsspp/assets/7974720/8b4f0b21-f090-4168-a27c-c9947054d48b)

Crashes could have something to do with Unimplemented HLE, we should at least faking it to success may be.

**Comment by anr2me** [comment]
Okay, i've tried to add a few stubs to faking success on unimplemented HLE on this PR https://github.com/ANR2MERefork/ppsspp/pull/8
And was able to progress on Hosting Game without crashing.

**Comment by Kikieg** [comment]
> Okay, i've tried to add a few stubs to faking success on unimplemented HLE on this PR [ANR2MERefork#8](https://github.com/ANR2MERefork/ppsspp/pull/8) And was able to progress on Hosting Game without crashing.
> 
> ![image](https://private-user-images.githubusercontent.com/7974720/324158699-f137931c-d56b-4855-b3c1-fa3701552f58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyODQ3OTksIm5iZiI6MTcyNzI4NDQ5OSwicGF0aCI6Ii83OTc0NzIwLzMyNDE1ODY5OS1mMTM3OTMxYy1kNTZiLTQ4NTUtYjNjMS1mYTM3MDE1NTJmNTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjVUMTcxNDU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmU2NWFhZmQ5NTM4NjZkNzdmZDEwNGM1NGVmNzBlYjNkMjhkZjY3ODdiYTcyYTU3NTVmMzAyMTg1ODkzODJiNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.4lI_vVHmJDBxSTi_F4YkILsTaNvVW7kVJBL5R7w91h8) ![image](https://private-user-images.githubusercontent.com/7974720/324158794-b7c730db-ae7d-429a-aa47-fbf45befb69a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyODQ3OTksIm5iZiI6MTcyNzI4NDQ5OSwicGF0aCI6Ii83OTc0NzIwLzMyNDE1ODc5NC1iN2M3MzBkYi1hZTdkLTQyOWEtYWE0Ny1mYmY0NWJlZmI2OWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjVUMTcxNDU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGY1MDM5MTllMDVlMWZmM2NiZjRkY2E3OWQ2ODc4NDA1MzZjNTkzMmRlYjNmODc2YTVlNGY4YWI0NThhNzFlMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.J04jskbrV6BmEWmoyZRp5_jJucLtjPg_vOxo6VNWHX4)

Hello How do you do it? I want to play too:)

**Comment by hrydgard** [comment]
@anr2me  I'm happy to merge those stubs if you want to submit a PR. Or I can just merge it manually.

**Comment by hrydgard** [comment]
Oh wait, we already did that, never mind. @Kikieg  should be in the next release.

**Comment by Kikieg** [comment]
> anr2me I'm happy to merge those stubs if you want to submit a PR. Or I can just merge it manually.

How to submit a PR?😅 I don't understand hehe

**Comment by anr2me** [comment]
The fix is already merged in the latest dev build, you just need to play the game using the [latest dev build](https://www.ppsspp.org/devbuilds).

**Comment by Kikieg** [comment]
> The fix is already merged in the latest dev build, you just need to play the game using the [latest dev build](https://www.ppsspp.org/devbuilds).

Ohhh thank you I just found out🤣, btw I want to ask, sorry in advance, what do you mean by pr? I'm very curious

**Comment by Kikieg** [comment]
> The fix is already merged in the latest dev build, you just need to play the game using the [latest dev build](https://www.ppsspp.org/devbuilds).

![Screenshot_20240926-072029](https://github.com/user-attachments/assets/839e6c27-57b9-4c3f-8065-b6dea856db14)
 Thank you developer!! It works, I asked if this can also be used like Lego Indiana Jones 2?

**Comment by anr2me** [comment]
> I asked if this can also be used like Lego Indiana Jones 2?

Probably not. 

As i remembered LEGO Indiana Jones 2 use a very short timeout to send 1 byte of non-blocking UDP packet when the game started, and that packet is the only annoying packet since it doesn't works well over high latency connection such as internet, while the rest of the packets works over high latency due to using TCP. 
Probably need a cheat to tamper the timeout for that 1 byte packet (which is the only packet sent/received using that particular socket), since Minimum Timeout setting only works for tampering timeout on blocking sockets.

**Comment by Kikieg** [comment]
> > I asked if this can also be used like Lego Indiana Jones 2?
> 
> Probably not.
> 
> As i remembered LEGO Indiana Jones 2 use a very short timeout to send 1 byte of non-blocking UDP packet when the game started, and that packet is the only annoying packet since it doesn't works well over high latency connection such as internet, while the rest of the packets works over high latency due to using TCP. Probably need a cheat to tamper the timeout for that 1 byte packet (which is the only packet sent/received using that particular socket), since Minimum Timeout setting only works for tampering timeout on blocking sockets.

Thank you very much... this improved PPSSPP version will also be applied to the official Playstore version later, right?

**Comment by anr2me** [comment]
Yes, the latest dev build will become the next official release, but not sure when it will be released though :)

**Comment by Kikieg** [comment]
> Yes, the latest dev build will become the next official release, but not sure when it will be released though :)

I can't help anything, but keep going, ppsspp is getting more exciting, the performance is getting better, the multiplayer is getting better, I really like it!!!
