### ISSUE TITLE
 PPSSPP v1.17.1 crashes due to `sceGuCopyImage` being fed bad address

### ISSUE THREAD

**Issue by frabert** [hrydgard/ppsspp#19101]
### Game or games this happens in

Custom binary

### What area of the game / PPSSPP

Running a homebrew app I'm developing causes PPSSPP to crash when `sceGuCopyImage` is fed a bad address.
I can provide a binary that reproduces the issue, and the same binary with the address fixed, but I can't provide a minimal example at the moment.
[buggy_eboots.zip](https://github.com/hrydgard/ppsspp/files/15178927/buggy_eboots.zip)

### What should happen

It shouldn't crash. Or, well, at least it should handle the faulty access in a more graceful manner.

### Logs

[log.txt](https://github.com/hrydgard/ppsspp/files/15178888/log.txt)

### Platform

Windows

### Mobile device model or graphics card (GPU)

AMD Radeon RX570 8GB

### PPSSPP version affected

v1.17.1

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Thanks, those eboots should do, a minimal example is not needed.

**Comment by hrydgard** [comment]
We had a bug when computing the memory size of block transfers for checking, fixing in #19121.

Thanks again for reporting this!
