### ISSUE TITLE
Digimon Adventure PSP NPJH-50686 bad voices sound on non video cutscenes.

### ISSUE THREAD

**Issue by LPatamon** [hrydgard/ppsspp#19117]
### Game or games this happens in

NPJH-50686 - Digimon Adventure

### What area of the game / PPSSPP

The issue happens on PPSSPP 1.17.1-404 for Windows (32bits one, I still need to check on my 64 bits installation on this same machine, but I'm sure it is the same since nothing else is wrong with the game other than an old issue still on the works about a line on the bottom of this game videos and that is on any PPSSPP version)

The game works fine speedwise, menus, etc. but on cutscenes, the characters voices sound slow and kinda distorted as you can see on the following video:

[Youtube Link](https://www.youtube.com/watch?v=j3cIv_OW8HE)

### What should happen

The sound should sound normal as it used to be on previous ppsspp versions

### Logs

[ppsspplog.txt](https://github.com/hrydgard/ppsspp/files/15245780/ppsspplog.txt)

### Platform

Windows

### Mobile device model or graphics card (GPU)

GeForce GT1030 2GB GDDR5

### PPSSPP version affected

v1.17.1-404-g70394c14d

### Last working version

v1.17.1-186-g1bcb15576

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Thanks for reporting, this is likely another mistake in mono/stereo conversion.

The old code was a bit confusing, and it seems I didn't get everything right in the rewrite.
