### ISSUE TITLE
Regression - Game: "Gensou Suikoden - Tsumugareshi Hyakunen no Toki" Shows Black Squares in Some Text on Any Build Beyond 1.16.6

### ISSUE THREAD

**Issue by Kolrath** [hrydgard/ppsspp#19116]
### Game or games this happens in

NPJH50535: Suikoden: Woven Web of the Centuries

### What area of the game

One of the text / font characters is a centered period similar to a dash. This seems to specifically be the one that ends up being a black square. The easiest point to see it is immediately at the start of the game when it opens up into a tutorial fight against some boars. Select to use a Skill on the main characters turn and the only skill they have is "Form - Resolve" where the issue is present.

So far, the only place this occured outside of that skills name was in a conversation with an NPC where it was at the end of a sentence. I didn't have any convenient way at the time to retest that conversation in software rendering to see if it was the exact same center circular dash character but I suspect it was because regular periods have displayed fine in countless prior conversations.

### What happens

On build 1.16.6 and earlier (tested all builds back to 15) the circular dash shows correctly.
On the next available build of 1.17 and beyond the circular dash shows incorrectly as a black square.

![PPSSPP build 1 17 - Black Squares](https://github.com/hrydgard/ppsspp/assets/8617529/cc10c4bc-a254-42d6-869c-6dc47b1e9a40)
This is it displaying wrong in 1.17

### What should happen

![PPSSPP build 1 16 6 - No Black Squares](https://github.com/hrydgard/ppsspp/assets/8617529/3db9b415-0789-4295-8b9b-1765147460d1)
This is it displaying correctly in 1.16.6

**TESTING PERFORMED**
If you use Software Rending with any build from 1.17 and beyond the text will display correctly so the issue is only present when using hardware rendering and the regression occurred somewhere between builds 1.16.6 and 1.17.

I tested 1.17 with all available backends (OpenGL, Direct3d 9, Direct3d 11, Vulkan) and stepped through all the various graphics toggles, resolutions, and scaling options with each backend and in all cases the black squares are present so its not linked to any specific backend.

### Platform

Windows

### Mobile device model or graphics card (GPU)

NVIDIA GeForce RTX 4070 (Driver Version 552.22 - most recent)

### PPSSPP version affected

v1.17 and up

### Last working version

v1.16.6 and below

### Graphics backend (3D API)

Other

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by sum2012** [comment]
@Kolrath Please create a GE frame capture to let dev fix the problem
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

**Comment by Kolrath** [comment]
Dang it! I was trying to be thorough but thought I missed something. Thanks for pointing it out. Don't remember ever doing one of these in the past so I hope I did this right...

[NPJH50535_0004.zip](https://github.com/hrydgard/ppsspp/files/15241775/NPJH50535_0004.zip)

**Comment by sum2012** [comment]
@Kolrath Well done ,you do right, wait dev to fix it.

**Comment by LunaMoo** [comment]
It fails to set a texture due to wrong size of 512x2048, it works when it's set correctly to 512x512, no idea what would set such size if PSP textures can only be square and 512x512 max.

**Comment by sum2012** [comment]
It is interested to know the reason that old version 2048 change to 512 and next version don't do that.
On hand build test
good
v1.16.6-372-gc3f881b7a
bad
v1.16.6-499-g8f75649b4

**Comment by sum2012** [comment]
@hrydgard 
git bisect result https://github.com/hrydgard/ppsspp/commit/5373b8c5b3838aa22bccb2f3e181d2684ca00aea in #18475
