### ISSUE TITLE
GTA Chinatown Crash At Mails Or GPS

### ISSUE THREAD

**Issue by KOKSVLL** [hrydgard/ppsspp#19120]
### Game or games this happens in

ULUS10490

### What area of the game / PPSSPP

Save File [ULUS10490L0.zip](https://github.com/hrydgard/ppsspp/files/15267473/ULUS10490L0.zip)

### What should happen

I was playing normally and crashed when I tried to access the GPS or PDA to get Uncle Kenny's "Kenny Strikes Back" quest.

### Platform

Windows

### Mobile device model or graphics card (GPU)

3050 Ti

### PPSSPP version affected

1.17.1

### Last working version

This problem does not depend on the version, I also tried it on 1.15.

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by sum2012** [comment]
How to access the GPS or PDA ?

**Comment by Panderner** [comment]
It didn't crashed for me when i access PDA or GPS by pressing start button.

**Comment by hrydgard** [comment]
I think this might have been fixed sometime since 1.17.1. Can't reproduce in the EU version at least.
