### ISSUE TITLE
Crash in menu reported since v1.17.1-383 on some devices

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#19137]
Reported by JessCraft3D on Discord

"in my version v1.17.1-427 ppsspp began to crash on the screensaver and in older versions, for example, in versions somewhere from 1.17.1-379, everything worked. Version 1.17.1 of ppsspp is working.

My phone:
Infinix Hot 12 Pro
2.Unisoc T616
3.Mali-G57
4.Android 12
My other phone:
Oppo Reno 7 Pro 4G
2.Qualcomm Snapdragon 680
3.Adreno 610
4Android 14
And it has the same problem "

" it started with version v1.17.1-383 that crashes on the intro ppsspp"

-383 means https://github.com/hrydgard/ppsspp/pull/19104 which seems a bit unlikely to crash...

**Comment by ISASLIMBOY28** [comment]
#19144 also same as this

**Comment by hrydgard** [comment]
I think this was fixed along with #19144. Closing.
