### ISSUE TITLE
CPU at 100% in menu in Vulkan on Linux

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#19131]
As it says on the tin.

Reported to happen on NVIDIA by KickMeElmo on the discord.

**Comment by foxsevent** [comment]
Small clarification, it's not just in menus but everywhere at all times with the Vulcan backend, menus and games, a CPU core is being pushed to 100%, which core it is can switch while running.
https://ibb.co/58wN3Xy
https://ibb.co/8jzJRhv

**Comment by yannb2159** [comment]
Like @foxsevent said, it's on the menu of PPSSPP AND also in game, tested with Tekken 6, Medal Of Honor Heroes and PES 6, one core is locked at 100% for no apparent reason and the core used can change at any time.
The issue only happens with the native PPSSPP Vulkan renderer, I'm on Linux and it didn't happen when using the OpenGL renderer with the Zink driver(Zink is a translator that translate OpenGL calls to Vulkan).

Here is my specs and PPSSPP info :
CPU : Ryzen 7 7840HS 8C/16T 5.1GHz.
RAM : 64GB DDR5 4800MHz.
GPU : Radeon 780M 4GB VRAM set in UEFI.
OS : openSUSE Tumbleweed Linux, kernel version : 6.8.9.
PPSSPP Version : latest git revision, self compiled with Clang 18.1.5 and lld as the linker.
PPSSPP CPU Backend : IR Interpreter.
PPSSPP Render Resolution 4X (1080p).

**Comment by PhantomX** [comment]
Starts after [Some renaming, add a bunch of sanity debug-asserts ](https://github.com/hrydgard/ppsspp/commit/25a1e6aa1438570d6ab45c3510aa7d6bd3a978f1).

**Comment by hrydgard** [comment]
Thanks, that's interesting!

**Comment by hrydgard** [comment]
Hm, in my testing, I'm seeing 100% CPU in commits before that one. I'll bisect myself (maybe it's a different cause..)
