### ISSUE TITLE
PSP Dev Kit GPO support (for hidden features in retail games only accesible by a PSP DEV kit)

### ISSUE THREAD

**Issue by Sukotto-1999** [hrydgard/ppsspp#19132]
### What should happen

PPSSPP should have support in newer versions for emulating the GPI/GPO switches found on the PSP Dev kits, can be useful for hidden features in retail games. For example, Ghostbusters The Video Game should display some sort of Debug Information including the framerate, while PaRappa the Rapper uses the GPO as a metronome (for BPM). The GPO should be displayed in the bottom/top left/right of the screen. (more info here: https://www.youtube.com/watch?v=ioodSTApknM )

### Who would this benefit

Someone should reverse engineer the GPI/GPO and code those findings.

### Platform (if relevant)

None

### Games this would be useful in

Ghostbusters The Video Game, PaRappa the Rapper, etc.

### Checklist

- [X] Check the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
I don't think much reverse engineering is needed. GPI is a set of manual on/off switches, GPU is a bunch of LEDs, presumably. Each I believe is 8 bits in size, and the API is simply sceKernelSetGPO / sceKernelGetGPI functions.

It's just an implementation task, storing/loading the value, and adding some way to toggle the inputs and display the outputs.

Really not sure what kind of UI we'd want for this..

**Comment by hrydgard** [comment]
This was a fun one to code up. #19136 implements this, let me know what you think.

**Comment by Sukotto-1999** [comment]
All done!
