### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Adnan331-alqadi** [hrydgard/ppsspp#19145]
#### Checklist

 - [x] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [x] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [ ] Try resetting settings or older versions and include if the issue is related.
 - [ ] Include logs or screenshots of issue.

**Comment by LunaMoo** [comment]
Please don't post empty issues.
