### ISSUE TITLE
Why does the ppsspp downloaded from app store not support vulkan?

### ISSUE THREAD

**Issue by joze2016** [hrydgard/ppsspp#19146]
### Game or games this happens in

None

### What area of the game / PPSSPP

When I set up the rendering engine, there is only the OpenGL option

### What should happen

When I set up the rendering engine, there should be options for both OpenGL and Vulkan

### Platform

iOS

### Mobile device model or graphics card (GPU)

iphone

### PPSSPP version affected

v1.17.1-491

### Last working version

not app store version

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by Halo-Michael** [comment]
How about just unify vulkan loading behavior in (iOS AppStore version)/(iOS sideload version)/(macOS version) as just static build vulkan in? dynamic load vulkan framework doesn't seems necessary and make codes complicated. @hrydgard

**Comment by hrydgard** [comment]
Might very well do that later. I'm taking care not to break the non appstore build as I get things working on the app store build. I don't yet know how to test the other one.

**Comment by hrydgard** [comment]
For the record, this was fixed by #19166 .
