### ISSUE TITLE
Always crashing on startup after choosing PPSSPP Folder

### ISSUE THREAD

**Issue by ISASLIMBOY28** [hrydgard/ppsspp#19144]
### Game or games this happens in

None.

### What area of the game / PPSSPP

After choosing ppsspp folder, the app just crash. Only works on version 1.71.1-379 and below.

https://github.com/hrydgard/ppsspp/assets/70120519/85c493c1-3a73-4fcf-b80c-e19271424eb9
(Version 1.71.1-463)

https://github.com/hrydgard/ppsspp/assets/70120519/f264c2ae-aaed-40ba-82db-80d24fbd0f34
(Version 1.71.1-274)

### What should happen

It shouldn't crash and enter the ppsspp main menu.

### Platform

Android

### Mobile device model or graphics card (GPU)

Tecno Spark 10 Pro (Helio G88, 8gb)

### PPSSPP version affected

1.71.1-383 and so on

### Last working version

1.71.1-379

### Graphics backend (3D API)

Vulkan and OpenGL

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Hi, that's very strange. Is 274 the very last working version, that is, v1.17.1-276 exactly breaks?

**Comment by DavidSilvadeSa** [comment]
the same happens to me.
POCO X3 PRO stock device

**Comment by ISASLIMBOY28** [comment]
> Hi, that's very strange. Is 274 the very last working version, that is, v1.17.1-276 exactly breaks?

I haven't test -276, cause the development build show all button doesn't work

**Comment by ISASLIMBOY28** [comment]
> Hi, that's very strange. Is 274 the very last working version, that is, v1.17.1-276 exactly breaks?

I will test it soon

**Comment by ISASLIMBOY28** [comment]
tested from 1.17.1-274 to 1.17.1-463 (i download all of em)

no crash:
-274
-276
-282
-286
-289
-305
-307
-309
-314
-317
-319
-322
-324
-329
-332
-334
-336
-341
-343
-345
-350
-352
-354
-357
-360
-363
-372
-375
-377
-379

crash: (if you restart your phone, you can access main menu but crash after you browse your game)
-383
-385
-387
-389
-390
-397
-399
-404
-406
-408
-414
-417
-420
-422
-427
-431
-436
-437
-442
-446
-449
-451
-454
-457
-460
-463

**Comment by ISASLIMBOY28** [comment]
> Hi, that's very strange. Is 274 the very last working version, that is, v1.17.1-276 exactly breaks?

tested from 1.17.1-274 to 1.17.1-463 (i download all of em)

no crash:
-274
-276
-282
-286
-289
-305
-307
-309
-314
-317
-319
-322
-324
-329
-332
-334
-336
-341
-343
-345
-350
-352
-354
-357
-360
-363
-372
-375
-377
-379

crash: (if you restart your phone, you can access main menu but crash after you browse your game)
-383
-385
-387
-389
-390
-397
-399
-404
-406
-408
-414
-417
-420
-422
-427
-431
-436
-437
-442
-446
-449
-451
-454
-457
-460
-463
