### ISSUE TITLE
No option to change username on iOS

### ISSUE THREAD

**Issue by radityaargap** [hrydgard/ppsspp#19148]
### Game or games this happens in

None

### What area of the game / PPSSPP

I can't find the option in system

### What should happen

It should have an option to change username, which is required to connect to hunsterverse

### Platform

iOS

### Mobile device model or graphics card (GPU)

Iphone 11

### PPSSPP version affected

1.17.1

### Last working version

None

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by anr2me** [comment]
It should be in Settings -> System -> Change Nickname

As i remembered hunsterverse doesn't allow using "PPSSPP" as nickname

**Comment by hrydgard** [comment]
Part of #19141

**Comment by radityaargap** [comment]
> Part of #19141

Okay. I'm looking forward to the next update. Thank you for your work!

**Comment by hrydgard** [comment]
This is now fixed.

I'm going to roll out a build on TestFlight on Wednesday, aiming for full release by the weekend or next week.
