### ISSUE TITLE
Vulkan Lost Device Error if Frame Advance and Fast-Forward are being used together

### ISSUE THREAD

**Issue by NABN00B** [hrydgard/ppsspp#19147]
### Game or games this happens in

any

### What area of the game / PPSSPP

If you spam the Frame Advance and Fast-Forward buttons together, the Vulkan renderer throws up a "device lost" error and stop working. A silly little thing I discovered by accident.

### What should happen

The renderer should continue to work.

### Logs

![vulkan_lostdev2](https://github.com/hrydgard/ppsspp/assets/22328803/d824a7ee-2aa9-42f6-a5d2-1d6ad7552cf2)
![vulkan_lostdevice](https://github.com/hrydgard/ppsspp/assets/22328803/37831612-57e0-4e75-85cb-7cc45b0f0a0c)

### Platform

Windows

### Mobile device model or graphics card (GPU)

NVIDIA GeForce GTX 1060 3GB (driver 545.84.0.0)

### PPSSPP version affected

v1.17.1 release, v1.17.1-463

### Last working version

idk

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
This should be fixed now by #19209  , let me know if you still have problems.

**Comment by NABN00B** [comment]
Thanks! I'll test the build in a couple of days.
