### ISSUE TITLE
TV dimming with iPad OS using HDMI

### ISSUE THREAD

**Issue by jazzybuilds** [hrydgard/ppsspp#19151]
When connecting ipad to TV using hdmi the screen dims when there is no input. 

The only information i could find thats was related was a reddit post regarding another app where apple responded stating that it's likely due to screen sharing compatibility issue within the app.

Edit: Just to add this is on the iPad pro 2018 with the latest iPad OS 17.5 connecting to an Lg OLED C1. I'm not having this issue with delta emulator.

**Comment by anr2me** [comment]
May be related to this https://9to5mac.com/2023/01/04/ios-16-break-drm-content-hdmi/

I wondered, does PPSSPP streams even considered as DRM-content?

**Comment by Florin9doi** [comment]
Probably related to setIdleTimerDisabled which is currently called only when an external controller is connected : https://github.com/hrydgard/ppsspp/blob/dbcac0e48c769e4874028496c6d6f6ecc418e16f/ios/ViewController.mm#L593

**Comment by hrydgard** [comment]
Oh, good catch, if that's it. 

Hm, can we detect easily if an iPad is used like this? But, wouldn't it detect your touch input and prevent dimming anyway? I'm a bit unclear on iOS behavior here.

**Comment by Florin9doi** [comment]
I reproduce the dimming on a normal iPhone after 30 seconds of inactivity. On android the dimming is disabled all the time while ingame: https://github.com/hrydgard/ppsspp/blob/48993479978eb5e17ab1764c89a01683e2b78198/android/src/org/ppsspp/ppsspp/NativeActivity.java#L1636

**Comment by hrydgard** [comment]
Ah, good point. I guess I'll just switch the iOS code to the same behavior.
