### ISSUE TITLE
Problem with Arabic language in ios 

### ISSUE THREAD

**Issue by 7ROBE** [hrydgard/ppsspp#19150]
### Game or games this happens in

.

### What area of the game / PPSSPP

Ui
![IMG_0264](https://github.com/hrydgard/ppsspp/assets/75377870/e112bc8e-7202-4a8e-84f8-eb6342b86d93)

### What should happen

The arabic language appears

### Logs

.

### Platform

iOS

### Mobile device model or graphics card (GPU)

iPhone 13

### PPSSPP version affected

v1.17.1-491-g9cdd97c13b

### Last working version

.

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
This is fixed now.
