### ISSUE TITLE
IR Interpreter with Digimon Adventure: Crash on Kurugawon encounter

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#19164]
Reported happening on iOS by GiuFar49 on Discord. Kurugawon is the [red insect-like creature](https://digimon.fandom.com/wiki/Kuwagamon)  in the first chapter.

> Solution:
> Tools > Developer Tools > Cpu Core > Change from IR Interpreter to Interpreter
> Tools > Developer Tools > JIT Debug Tools > Check VFPU_VEC

This indicates that we have an IR interpreter bug related to the vector instructions (or one of the optimization passes..). Although the two solutions above should be independent since VFPU_VEC is not checked when running the regular interpreter.

**Comment by Panderner** [comment]
Typo: it was Kuwagamon

**Comment by Panderner** [comment]
After first encounter of Kuwagamon scene, there is a warning message.
![Warning](https://github.com/hrydgard/ppsspp/assets/37503397/816a44e3-94cb-49e8-ac1b-1b1bb2bf1ce1)

**Comment by hrydgard** [comment]
Thanks for reporting that, that's helpful info!
