### ISSUE TITLE
Native text rendering on macOS/iOS

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#19162]
We have native text rendering support for a number of platforms, including Windows, Android, and more.

On iOS (~~and macOS~~ actually on macOS we use SDL) though, we still use a precomputed texture atlas solution. This needs to change in order to support all the languages properly, and also to support emoji.

Here's some sample code that does part of the job: https://stackoverflow.com/questions/49931870/draw-text-into-cgbitmapcontext 

Alternatively, we could try compiling and linking fontconfig and FreeType and reuse some of the SDL code..

Either way, first we should simplify the text drawer interface a bit, it's unnecessarily complex.

**Comment by Halo-Michael** [comment]
https://github.com/hrydgard/ppsspp/commit/1f7310d4cf06fb3e76e4e4177441f614c634117f works very well! Can confirm works with zh-CN.
![3fba9bea54ef2c3851f8b6dbe611f476](https://github.com/hrydgard/ppsspp/assets/45062120/1f0458b6-d4d8-4de4-8ed6-d582728ec39a)

**Comment by hrydgard** [comment]
Thanks, there are a few minor glitches (not visible in these screenshots), but I'll close this.
