### ISSUE TITLE
Shin Sangoku Musou 5 crashes in-game

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#19172]
Reported by Xaryu on Discord.

Don't know much about device, or CPU core setting, but looks like iOS so likely IR Interpreter.

Might be related to #19164 

https://github.com/hrydgard/ppsspp/assets/130929/6e90b404-c237-4878-a330-5bf414fd4781

**Comment by foxsevent** [comment]
Similar issue happens on Windows version stable build using IR Interpreter, thou the emu does not completely crashes it shows these errors.
No such issues when using Dynarec or regular Intepreter
![rn_image_picker_lib_temp_022fce3d-c343-4ddd-b89f-5e2228445b8f](https://github.com/hrydgard/ppsspp/assets/64225743/a93062c5-5c61-4938-8978-c6b6a77ee45a)
![rn_image_picker_lib_temp_55756600-db0c-42ab-94a0-4b2fc381cf9c](https://github.com/hrydgard/ppsspp/assets/64225743/65bb660c-b131-48ee-9ef7-6b1434ac5275)
![rn_image_picker_lib_temp_fcf70d8c-86ed-459b-9d6f-7b49b676683b](https://github.com/hrydgard/ppsspp/assets/64225743/06b0347c-9981-4e5b-b591-c4a23280b995)

**Comment by hrydgard** [comment]
@foxsevent can you check if it's ok in the latest builds?

**Comment by foxsevent** [comment]
No issue with 589 build.

**Comment by hrydgard** [comment]
thanks!
