### ISSUE TITLE
Gundam Assault Survive crash when loading the game on iOS

### ISSUE THREAD

**Issue by Jacky10X** [hrydgard/ppsspp#19185]
### Game or games this happens in

ULJS00281 - Gundam Assault Survive

### What area of the game / PPSSPP

PPSSPP(App Store ver.) crashes when loading Gundam Assault Survive on iOS. PC can run the game. PPSSPP(App store ver.) can run Gundam Battle Universe.

### What should happen

It shouldn't crash.

### Platform

iOS

### Mobile device model or graphics card (GPU)

IPhone SE3

### PPSSPP version affected

1.17.1-491-g9cdd97c13b

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Might be the same as #19172, in that case it was fixed by #19173. The update is in the latest testflight build (though it's not recommended for use due to a soft-keyboard bug, stay tuned for another update tomorrow)
