### ISSUE TITLE
[iOS] Icon styles on iOS are not uniform

### ISSUE THREAD

**Issue by Halo-Michael** [hrydgard/ppsspp#19190]
### What should happen

Icon in [assets.xcassets](https://github.com/hrydgard/ppsspp/blob/master/ios/assets.xcassets/AppIconGold.appiconset/icon_gold_backfill_1024.png)
have yellow background, but in [assets](https://github.com/hrydgard/ppsspp/blob/master/ios/assets/IconGold%403x.png) have blue background. I think icon style should be uniform.

### Who would this benefit

assets in iOS

### Platform (if relevant)

iOS

### Games this would be useful in

-

### Checklist

- [X] Check the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by Halo-Michael** [comment]
Also, icon sizes are outdated, these are the template icon sizes from Xcode:
Icon-29@3x.png Icon-40@2x.png Icon-40@3x.png Icon-60@2x.png Icon-60@3x.png Icon-29.png Icon-29@2x.png Icon-40.png Icon-40@2x.png  Icon-76@2x.png Icon-83.5@2x.png
![0a75d3638a3aae3ad3cf46fdf5b13840](https://github.com/hrydgard/ppsspp/assets/45062120/80933984-195f-4a79-acca-addddde548e2)
Can create those icons with a simple script:
convert -resize 87x87 ios/assets.xcassets/AppIcon.appiconset/icon_backfill_1024.png ios/assets/Icon-29@3x.png
convert -resize 80x80 ios/assets.xcassets/AppIcon.appiconset/icon_backfill_1024.png ios/assets/Icon-40@2x.png
convert -resize 120x120 ios/assets.xcassets/AppIcon.appiconset/icon_backfill_1024.png ios/assets/Icon-40@3x.png
convert -resize 120x120 ios/assets.xcassets/AppIcon.appiconset/icon_backfill_1024.png ios/assets/Icon-60@2x.png
convert -resize 180x180 ios/assets.xcassets/AppIcon.appiconset/icon_backfill_1024.png ios/assets/Icon-60@3x.png
convert -resize 29x29 ios/assets.xcassets/AppIcon.appiconset/icon_backfill_1024.png ios/assets/Icon-29.png
convert -resize 58x58 ios/assets.xcassets/AppIcon.appiconset/icon_backfill_1024.png ios/assets/Icon-29@2x.png
convert -resize 40x40 ios/assets.xcassets/AppIcon.appiconset/icon_backfill_1024.png ios/assets/Icon-40.png
convert -resize 80x80 ios/assets.xcassets/AppIcon.appiconset/icon_backfill_1024.png ios/assets/Icon-40@2x.png
convert -resize 152x152 ios/assets.xcassets/AppIcon.appiconset/icon_backfill_1024.png ios/assets/Icon-76@2x.png
convert -resize 167x167 ios/assets.xcassets/AppIcon.appiconset/icon_backfill_1024.png ios/assets/Icon-83.5@2x.png
convert -resize 87x87 ios/assets.xcassets/AppIconGold.appiconset/icon_gold_backfill_1024.png ios/assets/IconGold-29@3x.png
convert -resize 80x80 ios/assets.xcassets/AppIconGold.appiconset/icon_gold_backfill_1024.png ios/assets/IconGold-40@2x.png
convert -resize 120x120 ios/assets.xcassets/AppIconGold.appiconset/icon_gold_backfill_1024.png ios/assets/IconGold-40@3x.png
convert -resize 120x120 ios/assets.xcassets/AppIconGold.appiconset/icon_gold_backfill_1024.png ios/assets/IconGold-60@2x.png
convert -resize 180x180 ios/assets.xcassets/AppIconGold.appiconset/icon_gold_backfill_1024.png ios/assets/IconGold-60@3x.png
convert -resize 29x29 ios/assets.xcassets/AppIconGold.appiconset/icon_gold_backfill_1024.png ios/assets/IconGold-29.png
convert -resize 58x58 ios/assets.xcassets/AppIconGold.appiconset/icon_gold_backfill_1024.png ios/assets/IconGold-29@2x.png
convert -resize 40x40 ios/assets.xcassets/AppIconGold.appiconset/icon_gold_backfill_1024.png ios/assets/IconGold-40.png
convert -resize 80x80 ios/assets.xcassets/AppIconGold.appiconset/icon_gold_backfill_1024.png ios/assets/IconGold-40@2x.png
convert -resize 152x152 ios/assets.xcassets/AppIconGold.appiconset/icon_gold_backfill_1024.png ios/assets/IconGold-76@2x.png
convert -resize 167x167 ios/assets.xcassets/AppIconGold.appiconset/icon_gold_backfill_1024.png ios/assets/IconGold-83.5@2x.png
mogrify -strip ios/assets/Icon*

**Comment by Halo-Michael** [comment]
Also, this is an icon mask from Apple: [iOS-16-Production-Templates-Photoshop.dmg](https://devimages-cdn.apple.com/design/resources/download/iOS-16-Production-Templates-Photoshop.dmg), we can use it cut icons as Apple round icon.

**Comment by Halo-Michael** [comment]
This is the assets I made from 
https://github.com/hrydgard/ppsspp/blob/master/ios/assets.xcassets/AppIcon.appiconset/icon_backfill_1024.png and
https://github.com/h
[assets.zip](https://github.com/hrydgard/ppsspp/files/15446784/assets.zip)
rydgard/ppsspp/blob/master/ios/assets.xcassets/AppIconGold.appiconset/icon_gold_backfill_1024.png:

**Comment by hrydgard** [comment]
There's no need to manually cut the corners. The new way is to specify a single 1024x1024 icon in an .xcassets, I had to do that to pass the App Store Validator.

I think we can just delete most of the other icons if we switch over the non-app-store builds to this method.

It's not something I want to spend time on right now, but well-tested PRs are appreciated.

**Comment by Halo-Michael** [comment]
I think it is a more reasonable method to separate the icon from the assets, because the sideload version directly uses fully filled rectangle icons, and iOS will not cut it, but surround it with an ugly black border.

**Comment by Halo-Michael** [comment]
But at least should uniform icon styles between AppStore version and sideload version.

**Comment by Halo-Michael** [comment]
Also consider a way to correctly differentiate between the Gold version and the normal version on the sideload version
eg: icons, bundle id
Will try to create a pull request later.

**Comment by anr2me** [comment]
> and iOS will not cut it, but surround it with an ugly black border.

The black border might be due to transparent edges on the icon, as mentioned here https://stackoverflow.com/questions/26016307/black-lines-around-icon-ios

**Comment by Halo-Michael** [comment]
Have created a pull request #19195 to fix this.

**Comment by hrydgard** [comment]
Fixed by #19195, closing.
