### ISSUE TITLE
Dante's Inferno crashes whenever I reach this part (regardless of version)

### ISSUE THREAD

**Issue by Kalex25678** [hrydgard/ppsspp#19199]
### Game or games this happens in

ULUS-10469 Dante's Inferno

### What area of the game / PPSSPP

whenever I get to this part the game causes this crash (regardless of the game version) www.twitch.tv/videos/2154430325?t=2h22m43s , I noticed in some old posts that this could be a piracy detection and because of that the game causes this crash every time I reach this part, I looked for the solution in several videos and forums and no one was able to help... Can anyone solve this error? Is there any program that can 'organize the memory' of PSP ISOs?

### What should happen

Nothing, the game should progress normally until the end.

### Platform

Windows

### Mobile device model or graphics card (GPU)

920MX

### PPSSPP version affected

v1.17.1-329-g7d46f5a0a

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by anr2me** [comment]
According to this https://report.ppsspp.org/game/ULUS10469_1.01 it's marked as Perfect, i wondered whether they succeed in completing the game or not.

Do you have the same CRC with those marked Perfect?

**Comment by Saramagrean** [comment]
maybe bad rip?

![Screenshot 2024-05-28 004943](https://github.com/hrydgard/ppsspp/assets/26355472/e54858cf-7fcc-40f6-9791-3f2441769ebc)

![Screenshot 2024-05-28 005019](https://github.com/hrydgard/ppsspp/assets/26355472/3fd85cd7-65c5-45a7-98e7-059d28dacc17)

**Comment by Kalex25678** [comment]
> According to this https://report.ppsspp.org/game/ULUS10469_1.01 it's marked as Perfect, i wondered whether they succeed in completing the game or not.
> 
> Do you have the same CRC with those marked Perfect? Edit: on your video the CRC is not recognized, may be you have a corrupted ISO? but such CRC is also marked as Perfect in the report.. (last reported Perfect was using v1.17.1)

I myself marked it as perfect because years ago the game was very slow on the emulator and at that time the same bug happened that happened in the video, after this bug happened I marked it as 'ingame' to show that there was some kind of 'error in the emulator' ... other than that the game is perfect.
Regarding the other versions with different CRC, I will test them one by one and see if they have any similarities with the achievements in retroachievements so that I can continue playing

**Comment by hrydgard** [comment]
You might also try the very latest version of PPSSPP, or go back to 1.17.1 - do those work?

**Comment by LunaMoo** [comment]
Just to clarify, this isn't a "piracy detection", but incorrectly dumped game copy that's shared by pirates since the game original release.
