### ISSUE TITLE
Vulkan: Some weird bugs reported on Windows

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#19209]
* In parappa the rapper, running in debug mode, we hit a validation error
* Lost device on "Pause emulator when not focused" option and the Vulkan rendering option are enabled, and then task switching (see https://github.com/hrydgard/ppsspp/issues/19199#issuecomment-2135833521)

**Comment by anr2me** [comment]
Sounds like a leaks at the driver level if it affects other 3D programs/games outside of PPSSPP too.
