### ISSUE TITLE
AI game maker

### ISSUE THREAD

**Issue by Merljn777** [hrydgard/ppsspp#19202]
Hi, it's huge. Do you know if a website exists wich hosts new games ISO only generated by AI ? Could you add this link in further update of PPSSPP?

I'm talking about an AI creating maps, gameplay, images, videos, scenario. A full AI game maker.

Thanks

**Comment by hrydgard** [comment]
Never heard of anything like that, AI can't generate ISOs with games, and I don't think they will be able to anytime soon.
