### ISSUE TITLE
Linux 32-bit and 64-bit Versions

### ISSUE THREAD

**Issue by sandboxgamedev123** [hrydgard/ppsspp#19212]
### What should happen

Providing Linux builds could be very beneficial.

### Who would this benefit

Linux users would benefit from Linux builds.

### Platform (if relevant)

Linux / BSD

### Checklist

- [X] Check the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

Versions of Linux tested:

 - [X] Linux Mint 21.2 Cinnamon 64-bit
 - [X] LMDE 6 Cinnamon 64-bit
 - [X] LMDE 6 Cinnamon 32-bit

Test systems:

 - [X] AMD Ryzen 5 5600H, NVIDIA GeForce RTX 3060 6 GB, 16 GB RAM, 1.5 TB NVMe SSD (in a VM using QEMU)
 - [X] Intel Core i5-7300HQ, NVIDIA GeForce GTX 1050 Ti 4 GB, 16 GB RAM, 512 GB SATA SSD

**Comment by anr2me** [comment]
It would be nice if you can provide the workflow to generate AppImage, for example like the Manual Generate workflows at https://github.com/hrydgard/ppsspp/actions

**Comment by hrydgard** [comment]
You are welcome to add git workflows (as mentioned by anr2me) or provide scripts, or whatever is appropriate.

**Comment by sandboxgamedev123** [comment]
I am not familiar with workflows in GitHub (I am rather new to certain aspects of GitHub). I modified the "makeappimage.sh" script from the Snes9x GitHub webpage.

Snes9x URL: https://github.com/snes9xgit/snes9x

I also edited /ppsspp//Qt/PPSSPP.desktop as well as copied "ppsspp.png" from /ppsspp/icons/hicolor/256x256/apps/ into the /ppsspp/Qt/ folder. A folder was created in /ppsspp/ called "scripts" and "makeappimage.sh" was placed into the folder.

After building in a command-line window with ~/ppsspp/build/ being the directory, I entered the following:

~/ppsspp/scripts/makeappimage.sh

There was an attempt to create an AppImage. A folder named "AppDir" was created. I placed "PPSSPP.desktop" and "ppsspp.png" into the "AppDir" folder.

"PPSSPP.desktop" was also placed into the following directory:

/ppsspp/build/AppDir/usr/share/applications/

"ppsspp.png" was also placed into the following directory:

/ppsspp/build/AppDir/usr/share/icons/hicolor/256x256/apps/

The program "PPSSPPQt" that was build was also placed in the following directory:

/ppsspp/build/AppDir/usr/bin/

"~/ppsspp/scripts/makeappimage.sh" was entered again into a command-line window and the AppImage file was created.

The modified "makeappimage" scripts and "PPSSPP.desktop" were uploaded to my repository if you would like to look.

As for how they were built, the 32-bit version was compiled in a VM (QEMU) with LMDE 6 Cinnamon 32-bit. The 64-bit version was compiled on Linux Mint 21.2 Cinnamon 64-bit which was the main OS. I made two separate "makeappimage" scripts for the repository as each was different for their respective architecture.

**Comment by anr2me** [comment]
If you use the Qt version of PPSSPP, it may have issue with Wayland as mentioned in https://github.com/hrydgard/ppsspp/issues/16254
Since the Qt version haven't been maintained for a long time.

**Comment by sandboxgamedev123** [comment]
I am not sure, it is possible. Linux Mint still uses X11 as the default and I did not notice the issue you referred to in my testing.

**Comment by sandboxgamedev123** [comment]
That is interesting but I do not have experience with that aspect of GitHub. When I create an AppImage file, I do not test the same file that is used for the release. Instead I save it to another drive and then copy it to the testing system and conduct tests on a copy. This might not matter but this is how I try to keep programs untouched when they are released.

I also consider optimizing file sizes for the AppImage files. I do not think this was an issue for PPSSPP since the file sizes were 67.5 MB for the 32-bit version and 63.8 MB for the 64-bit version which seem reasonable for PPSSPP.

I had an issue when I was creating a 32-bit AppImage of mGBA. The file size was over 100 MB. This also seemed to cause issues for Cinnamon (the desktop environment) on the following system:

Intel Celeron M 360 1.4 GHz, Intel GMA 900 128 MB, 1.25 GB RAM, 160 GB 5400-RPM HDD

I optimized the configuration for building the AppImage by excluding libraries that should not be required and I managed to produce an AppImage with the file size reduced to 29 MB. The new AppImage worked well on the Intel Celeron system and was able to play a game at full speed.

I also conduct general testing of the AppImage files such as playing a game, changing options in the emulator, saving game data, and restarting the program to check that it can load save game data.

One issue to note that I noticed with the 64-bit AppImage of PPSSPP is that the renderer did not change to Vulkan when I tried to change the renderer. The program showed a prompt to restart the program but the program did not restart. Instead the program closed. Opening the program showed that it was still using the OpenGL renderer. I tried changing the renderer in the configuration file but it still opens in OpenGL and changes the renderer in the configuration file to OpenGL.

I do not consider it a significant issue for PPSSPP because many low-end systems do not have Vulkan support anyway and if the system is new enough to support Vulkan, it should have enough resources to operate PPSSPP well in OpenGL. Regardless, it might be beneficial to have the option for Vulkan.

The 32-bit AppImage only has the option for OpenGL in the menu. This might be the case for the 32-bit Windows version as well but I do not know.

**Comment by anr2me** [comment]
Another interesting github action that be be used for cross-compiling without docker https://github.com/jirutka/setup-alpine

**Comment by anr2me** [comment]
btw @sandboxgamedev123 which packages do i need to install on Alpine in order to build ppsspp ?

These are the default packages installed from https://github.com/jirutka/setup-alpine
```
alpine-baselayout-3.6.5-r0 riscv64 {alpine-baselayout} (GPL-2.0-only) [installed]
alpine-baselayout-data-3.6.5-r0 riscv64 {alpine-baselayout} (GPL-2.0-only) [installed]
alpine-keys-2.4-r1 riscv64 {alpine-keys} (MIT) [installed]
alpine-release-3.21.0_alpha20240606-r0 riscv64 {alpine-base} (MIT) [installed]
apk-tools-2.14.4-r0 riscv64 {apk-tools} (GPL-2.0-only) [installed]
busybox-1.36.1-r31 riscv64 {busybox} (GPL-2.0-only) [installed]
busybox-binsh-1.36.1-r31 riscv64 {busybox} (GPL-2.0-only) [installed]
busybox-suid-1.36.1-r31 riscv64 {busybox} (GPL-2.0-only) [installed]
ca-certificates-bundle-20240226-r0 riscv64 {ca-certificates} (MPL-2.0 AND MIT) [installed]
libcrypto3-3.3.1-r0 riscv64 {openssl} (Apache-2.0) [installed]
libssl3-3.3.1-r0 riscv64 {openssl} (Apache-2.0) [installed]
musl-1.2.5-r1 riscv64 {musl} (MIT) [installed]
musl-utils-1.2.5-r1 riscv64 {musl} (MIT AND BSD-2-Clause AND GPL-2.0-or-later) [installed]
scanelf-1.3.7-r2 riscv64 {pax-utils} (GPL-2.0-only) [installed]
ssl_client-1.36.1-r31 riscv64 {busybox} (GPL-2.0-only) [installed]
zlib-1.3.1-r1 riscv64 {zlib} (Zlib) [installed]
```

**Comment by sandboxgamedev123** [comment]
Alpine Linux is considered lightweight, which means you might be required to install more packages to build on that distro.

I am not familiar with the packaging format for Alpine Linux but I can provide a list of packages I typically install on Linux Mint (based on Ubuntu and Debian) for building programs. Packages recommended for building other programs might be helpful.

The following is from the PPSSPP building wiki for CMake:

`sudo apt install libgl1-mesa-dev libsdl2-dev libsdl2-ttf-dev libfontconfig1-dev libcurl4-openssl-dev libglew-dev`

The following is from the Dolphin emulator building wiki:

`sudo apt install build-essential git cmake ffmpeg libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libevdev-dev libusb-1.0-0-dev libxrandr-dev libxi-dev libpangocairo-1.0-0 qt6-base-private-dev libqt6svg6-dev libbluetooth-dev libasound2-dev libpulse-dev libgl1-mesa-dev libcurl4-openssl-dev`

**Comment by anr2me** [comment]
Yeah, the PPSSPP wiki only have info for Debian and Fedora/RHEL
Anyway, i've found the packages needed from https://github.com/hrydgard/ppsspp/blob/master/Dockerfile

**Comment by sandboxgamedev123** [comment]
Okay. It seems like you found what you were looking for.

**Comment by sandboxgamedev123** [comment]
@hrydgard

I changed from Qt to SDL for the AppImages.

### CPU Checklist

 - [X] Intel Core i5-7300HQ
 - [X] AMD Ryzen 5 5600H

### GPU Checklist

 - [X] NVIDIA GeForce RTX 3060
 - [X] NVIDIA GeForce RTX 1050 Ti
 - [X] Intel HD Graphics 630
 - [X] AMD Radeon Vega 7

### API Checklist

 - [X] OpenGL
 - [X] Vulkan

@Samueru-sama helped as well regarding a change to a different "appimagetool".

**Comment by anr2me** [comment]
Btw, is there appimagetool that support riscv64 arch? 
both https://github.com/AppImage/appimagetool/releases and https://github.com/linuxdeploy/linuxdeploy/releases doesn't seems to have it.

**Comment by sandboxgamedev123** [comment]
I do not know if there is an "appimagetool" that supports "riscv64".

**Comment by sandboxgamedev123** [comment]
Based on the links you provided, I did not see an "appimagetool" you might be looking for.
