### ISSUE TITLE
Game Crashing on iOS

### ISSUE THREAD

**Issue by NolanAirbusA388** [hrydgard/ppsspp#19234]
### Game or games this happens in

ULUS-10006 - Metal Gear Acid

### What area of the game / PPSSPP

During the tutorial, the character goes down a hall. After that, a cutscene plays. Then the app crashes. We have tried the American and European ISO files.

### What should happen

It shouldn’t crash.
![IMG_2254](https://github.com/hrydgard/ppsspp/assets/171494435/54437473-8258-4d5e-b5fd-9c5ee8897e1d)

### Platform

iOS

### Mobile device model or graphics card (GPU)

iPad Pro (11-inch) (3rd generation)

### PPSSPP version affected

1.17.1-491-g9cdd97c13b

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [x] Include logs or screenshots of issue.

**Comment by anr2me** [comment]
Since the CRC is not recognized, there is a possibility that you're using a corrupted ISO or a bad dump.

**Comment by hrydgard** [comment]
Yeah, trying devbuilds with the IR Interpreter on non-iOS is now *nearly* equivalent to testing on iOS (except the NEON/SSE code which could have bugs in one or the other) - that is, if it's now working with IR in the latest builds on Windows, it's 99% sure it'll work on the next iOS release too.

**Comment by NolanAirbusA388** [comment]
I also have it with an iPhone 14 Pro.

**Comment by anr2me** [comment]
It's the same issue with https://github.com/hrydgard/ppsspp/issues/18371
Since Interpreter's FPU is causing the crash disabling JIT functionality won't works

I'll close this one since it's a duplicate.
