### ISSUE TITLE
Please allow .5 and .75 Rendering Resolution

### ISSUE THREAD

**Issue by slrgt** [hrydgard/ppsspp#19247]
### What should happen

I've been playing PSP games on the RG35XXH and a lot of games run great on it. Monster hunter runs almost perfectly but some games like Ratchet and Clank run very laggy. Ratchet and clank is much more high textured than monster hunter so I would like to downscale it to .5 or .75 rendering resolution so it can run better.

### Who would this benefit

Increase performance of games.

### Platform (if relevant)

Other

### Games this would be useful in

UCUS-98633 Ratchet & Clank: Size Matters

### Checklist

- [X] Check the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
It's unlikely that lowering the resolution below 1x will actually improve performance, unless you're on some very underpowered hardware, which probably will have other performance issues anyway. What device are you playing on?

**Comment by slrgt** [comment]
Im playing on the RG35XXH its not very powerful and the screen is small enough that lowering the resolution wont be noticeable, monster hunter runs great so i think lowering the resolution on ratchet and clank will be enough to get it running smoothly.

**Comment by hrydgard** [comment]
In addition to what LunaMoo says, adding a 0.5x mode would actually be a bit complex, and it's a change that would benefit extremely few users and the benefit would be near zero. Again, I doubt that at 480x272, lowering the resolution further will provide meaningful speed benefit on almost any hardware that can run PPSSPP at all. The problem with Ratchet might very well be something else.
