### ISSUE TITLE
A advice about action of Xbox button or PS button on IOS

### ISSUE THREAD

**Issue by HowQuitVim** [hrydgard/ppsspp#19259]
### What should happen

On iphone,if press xbox button (xbox controller) or PS button(dual sense controller),the default action is open game center of ios.but i think open pause menu of PPSSPP would be better, just like what retroarch does

### Who would this benefit

i think all ios user of ppsspp will be benefited

### Platform (if relevant)

iOS

### Games this would be useful in

all games

### Checklist

- [X] Check the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
This is already fixed and will be going out in the next update.

- #19254
