### ISSUE TITLE
Compilation failed on Raspberry Pi 

### ISSUE THREAD

**Issue by Srandista** [hrydgard/ppsspp#19258]
### Platform

Raspberry Pi

### Compiler and build tool versions

gcc 12.2.0 + cmake 3.25.1

### Operating system version

Raspberry Pi Bookworm 64-bit

### Build commands used

./b.sh --rpi64

### What happens

I was trying to compile PPSSPP on my RPi yesterday, but I got following error:

```
[ 90%] Building CXX object CMakeFiles/Core.dir/GPU/Common/VertexDecoderHandwritten.cpp.o
/home/rpi/Downloads/ppsspp/GPU/Common/VertexDecoderHandwritten.cpp: In function ‘void VtxDec_Tu8_C5551_Ps16(const u8*, u8*, int, const UVScale*)’:
/home/rpi/Downloads/ppsspp/GPU/Common/VertexDecoderHandwritten.cpp:241:60: note: use ‘-flax-vector-conversions’ to permit conversions between vectors with differing element types or numbers of subparts
  241 |                 uint8x8_t uv8 = vreinterpret_s8_u64(uv8_one);
      |                                                            ^
/home/rpi/Downloads/ppsspp/GPU/Common/VertexDecoderHandwritten.cpp:241:52: error: cannot convert ‘int8x8_t’ to ‘uint8x8_t’ in initialization
  241 |                 uint8x8_t uv8 = vreinterpret_s8_u64(uv8_one);
      |                                 ~~~~~~~~~~~~~~~~~~~^~~~~~~~~
      |                                                    |
      |                                                    int8x8_t
make[2]: *** [CMakeFiles/Core.dir/build.make:4430: CMakeFiles/Core.dir/GPU/Common/VertexDecoderHandwritten.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:875: CMakeFiles/Core.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

I can see, that there was a similar issue reported here earlier, but in different file, and it was fixed in code.
https://github.com/hrydgard/ppsspp/issues/18688

Is it possible to fix this by the same way? Also if you need something else from me (like additional logs or some other files), just let me know.

Thanks!

### PPSSPP version affected

v1.17.1-714-g3444c32097

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] Make sure to run `git submodule update --init --recursive` before building.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try deleting the build directory and running the build again.
- [ ] Check GitHub Actions, which builds every merge and PR.
- [ ] Include logs and help us reproduce.

**Comment by Srandista** [comment]
Just to clarify, with the "-flax-vector-conversions" flag it can compile past the mentioned error.

**Comment by hrydgard** [comment]
Oh, my bad again. The compilers I use somehow don't warn about this... but I did use the wrong type here. Fix coming.

**Comment by Srandista** [comment]
Just want to confirm, that with `v1.17.1-748-gef91fa8b4f`, it compiles just fine without any issues.

Thanks for quick fix!
