### ISSUE TITLE
PPSSPP (ios) closes itself/crashes when playing invizimals and invizimals shadow zone

### ISSUE THREAD

**Issue by mendesrr** [hrydgard/ppsspp#19263]
### Game or games this happens in

UCUS-98746-Invizimals; UCES-01411-Invizimals Shadow Zone

### What area of the game / PPSSPP

Basically when playing these games on my iphone 11 (ios 16.3.1), the games just crash after playing for a little bit. I’ve tried changing every possible setting in graphics and system but nothing works, hence why i assume its a ppsspp incompatibility with those games… 
*(Not related to the issue but microphone support is needed to catch some inzimals (https://github.com/hrydgard/ppsspp/issues/12336#issue-495176193))*

### What should happen

It shouldn’t close the emulator while playing.

### Platform

iOS

### Mobile device model or graphics card (GPU)

Iphone 11

### PPSSPP version affected

v1.17.1-669-gd298c6f6f5

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [x] Try resetting settings or older versions and include if the issue is related.
- [x] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by Panderner** [comment]
Maybe the camera is not implemented for iOS? (#12337)

**Comment by hrydgard** [comment]
There is some code for it but I haven't tested it myself yet. Will do soon.

**Comment by mendesrr** [comment]
> Maybe the camera is not implemented for iOS? (#12337)
It is implemented but not fully functional in some cases.

**Comment by mendesrr** [comment]
> There is some code for it but I haven't tested it myself yet. Will do soon.

Alright thanks for the attention!

**Comment by hrydgard** [comment]
Played around a bit but I can't get it to crash (in the newest builds).

As you say, unfortunately, we also need microphone support for these games to be fully playable.

**Comment by mendesrr** [comment]
> Played around a bit but I can't get it to crash (in the newest builds).
> 
> As you say, unfortunately, we also need microphone support for these games to be fully playable.

I haven't updated my iphone iOS version since i created this report, and just loaded up the game today to check if it was fixed... I gotta say i was pleasantly surprised to see that it worked flawlessly. Just need the microphone implemented to be fully playable :)
PPSSPP v1.17.4-1
