### ISSUE TITLE
JIT/Dynarec crash upon load on RISC-V

### ISSUE THREAD

**Issue by archanox** [hrydgard/ppsspp#19266]
### Game or games this happens in

ULUS-10093 - WRC

### What area of the game / PPSSPP

Upon loading the game.

### What should happen

Dynarec/JIT should be functional when running on RISC-V

### Logs
```
44:24:851 Core/System.cpp:428 N[BOOT]: PPSSPP v1.17-875-g5dec3ca2db
44:25:338 root         N[BOOT]: UI/EmuScreen.cpp:384 Booted /media/debian/Storage/Isos/World_Rally_Championship_USA_PSP-pSyPSP.iso...
44:25:339 root         E[SYSTEM]: Common/Log.cpp:73 (/media/debian/Storage/ppsspp/Core/MIPS/IR/IRNativeCommon.cpp:CompileIRInst:477): [false] (ULUS10093 WRC, 0.5s) Unexpected IR op 11
(/media/debian/Storage/ppsspp/Core/MIPS/IR/IRNativeCommon.cpp:CompileIRInst:477): [false] (ULUS10093 WRC, 0.5s) Unexpected IR op 11
Trace/breakpoint trap
```

### Platform

Linux / BSD

### Mobile device model or graphics card (GPU)

Radeon HD 7850

### PPSSPP version affected

v1.17-875-g5dec3ca2db

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by anr2me** [comment]
(Assuming your ISO CRC is good, and other CPU Cores are working fine)
Try disabling some of JIT functionality to find out which one causing the crash.

**Comment by hrydgard** [comment]
This seems related to my recent ir interpreter optimizations. Will look into it.

**Comment by archanox** [comment]
> (Assuming your ISO's CRC is good, and other CPU Cores are working fine)

Yeah it's the same CRC as my physical copy. It works fine on other platforms, and the it interpreter on RISC-V.

> Try disabling some of JIT functionality to find out which one causing the crash.

Can do if it helps narrow down the issue.

**Comment by archanox** [comment]
I just tested the JIT with everything disabled, and it errors mostly the same.

Now it says ```
59:19:621 user_main    E[SYSTEM]: Common/Log.cpp:73 (/media/debian/Storage/ppsspp/Core/MIPS/IR/IRRegCache.cpp:operator():806): [false] (ULUS10093 WRC, 0.4s) Unexpected type: ?
(/media/debian/Storage/ppsspp/Core/MIPS/IR/IRRegCache.cpp:operator():806): [false] (ULUS10093 WRC, 0.4s) Unexpected type: ?
Trace/breakpoint trap
```

**Comment by hrydgard** [comment]
Thanks, I'll get this fixed soon.

**Comment by hrydgard** [comment]
Hm? I thought it was only the actual IR JIT that was broken, did it also not run using the IR Interpreter previously? It should have.

**Comment by archanox** [comment]
Sorry @hrydgard, right you are.
Have opened the new linked issue anyway as the problem in the title still persists.
