### ISSUE TITLE
iOS App Store version’s category should be changed to Games, to enable iOS 18 Game Mode support

### ISSUE THREAD

**Issue by schm1dtxbox** [hrydgard/ppsspp#19267]
### What should happen

As the title suggests, iOS 18/iPadOS 18 brings over the Game Mode feature seen in macOS Sonoma to iPhones and iPads, and enabling it is likely the same as on macOS too, i.e. the application category type (LSApplicationCategoryType) should be set to something ending in ‘games’ for the feature to activate (e.g. http://public.app-category.games/). Currently PPSSPP appears to set this to ‘Developer Tools’ for the App Store build, hence Game Mode doesn’t currently kick in.

### Who would this benefit

This would particularly benefit those using wireless headphones (e.g. AirPods) or game controllers with PPSSPP, as Game Mode doubles the Bluetooth sampling rate when active, which should reduce latency for the above devices. Game Mode in theory may also provide sustained performance and frame time consistency improvements by prioritising the current game over background processes and by applying more aggressive scheduling (as was observed with macOS’s flavour of Game Mode at least).

### Platform (if relevant)

iOS

### Games this would be useful in

All titles (as this is an app-wide request)

### Other emulators or software with a similar feature

Any application on macOS/iOS with the app category set to something ending in games would be a good example of this, can be tested on the iOS 18 developer preview by launching said app and checking for a ‘Game Mode’ notification at the top of the screen.

### Checklist

- [X] Check the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by schm1dtxbox** [comment]
1.17.3 is out on the App Store now with all relevant changes (and more it turns out, very nice that Apple finally supports explicitly declaring Game Mode support with GCSupportsGameMode!) so should be safe to close this issue now.

**Comment by schm1dtxbox** [comment]
1.17.3 is out on the App Store now with all relevant changes (and more it turns out, very nice that Apple finally supports explicitly declaring Game Mode support with GCSupportsGameMode!) so should be safe to close this issue now.

**Comment by hrydgard** [comment]
Thanks for closing :)
