### ISSUE TITLE
ppsspp will crash if i open a specific box in god of war ghost of sparta

### ISSUE THREAD

**Issue by HowQuitVim** [hrydgard/ppsspp#19271]
### Game or games this happens in

NPHG00092

### What area of the game / PPSSPP

when i open a specific box， ppsspp crashed（i  tried several times），i will upload saved state file。
after load state file I uploaded，just open the box in front of kratos，and then crash should be happened.
[NPHG00092_1.00_0-savestate.zip](https://github.com/user-attachments/files/15796418/NPHG00092_1.00_0-savestate.zip)

### What should happen

ppsspp do not crash

### Platform

iOS

### Mobile device model or graphics card (GPU)

iPhone15 pro max

### PPSSPP version affected

V1.17.1-669-gd298c6f6f5

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by anr2me** [comment]
Have you tried the latest dev build?
There were IR interpreter issue recently and got fixed afterward, so may be the issue you have already fixed on the latest dev build.

**Comment by HowQuitVim** [comment]
last night，i tried to compile for linux  from master branch ，but i found ppsspp will be not responsable if i  load savestate file,so  i  do not  know  wheather problem  resolve .I think  this crash bug was caused by cheats，i used cheats to increase max heath  of kratos，and then ，when i open the box that rewards max heath increament，program crashed

**Comment by HowQuitVim** [comment]
and i tried testflight edition，i found crash was not resolved

**Comment by anr2me** [comment]
Well, you should disable all cheats first before testing, and also load it from save data instead of save state, because the changes done by the cheat might already affects the save state.

**Comment by HowQuitVim** [comment]
> Well, you should disable all cheats first before testing, and also load it from save data instead of save state, because the changes done by the cheat might already affects the save state.
> 
> You can then create a clean save state after loading it from save data without using any cheat for other people to test the save state.

i tried as what you said，still crash，i think the savedata was already Polluted by cheat

**Comment by LunaMoo** [comment]
Probably nothing to do here, if you patched your game memory with a cheat and it saved to savedata, it's not an emulator issue. Game might not be coded for situation where you collect a health upgrade after having it maxed already and the undefined result ends up with a crash.
 You should try to reach that chest without using such cheat to confirm, could also use some cheat which un-maximizes your hp upgrades or something to test.
