### ISSUE TITLE
App crash when starting any game when using "JIT Using IR"

### ISSUE THREAD

**Issue by zeraxx1** [hrydgard/ppsspp#19292]
### Game or games this happens in

All games

### What area of the game / PPSSPP

When starting any game with "JIT using IR" the app crash after like 1 second

### What should happen

The app doesn't crash and the game starts normally

### Platform

Android

### Mobile device model or graphics card (GPU)

Realme 3 (Mali-G72 MP3)

### PPSSPP version affected

All version after v1.17.1-730

### Last working version

v1.17.1-730

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Yeah, this is not good. However it doesn't affect all games, which confused me at first. One example affected game is Lumines (and there are indeed a lot more). Will fix shortly.

**Comment by hrydgard** [comment]
Bisected to find the culprit, it's d1a00f61de2b3d8ab62eddadf8d75cba07a9bd13 . Fix coming up.
