### ISSUE TITLE
When I press alt, the buttons is automatically pressed. 

### ISSUE THREAD

**Issue by Gamerppsspp** [hrydgard/ppsspp#19298]
### Game or games this happens in

All

### What area of the game / PPSSPP

When I press alt, the button is automatically pressed byttons.
I don't know if this is a bug? If this is a function, then please change the button in the settings. I need to name the action on alt, but I can't do it because of that.

### Platform

Windows

### Mobile device model or graphics card (GPU)

GTX 1050ti

### PPSSPP version affected

Latest build

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Mapping the Alt key indeed doesn't work very well because it'll activate/deactivate the window menu.

I don't understand what you are saying with this though: "When I press alt, the button is automatically pressed byttons"

**Comment by NABN00B** [comment]
Not sure if it's the same problem that op is having but inputting the analog stick while Alt is being held down, keeps the analog stick held in place.

> For now, I recommend just mapping another key. Using alt as a game key is not really done much these days..

As far as I know, it's a relic from the era of DOS gaming. While using Alt doesn't cause issues in games that run in true fullscreen, PPSSPP is not such an app. Maybe disabling keys like Alt, Win and Context Menu keys should be considered.

**Comment by anr2me** [comment]
Right, may be should only use mouse click to activate the menu, like https://stackoverflow.com/questions/9627379/how-to-disable-normal-behaviour-of-alt-key

**Comment by hrydgard** [comment]
Thanks @anr2me . I propose #19304, what do you guys think?

**Comment by Gamerppsspp** [comment]
> Thanks @anr2me . I propose #19304, what do you guys think?

Ok

> Thanks @anr2me . I propose #19304, what do you guys think?

I would also like to ask you if it is possible to slow down the keys as an analog limiter? It's just that if the control is on the dpad, then unfortunately the slowing will not be applied to it.

**Comment by hrydgard** [comment]
Well, the dpad is the dpad, can't be slowed down - it's either on or off.

**Comment by anr2me** [comment]
> Thanks @anr2me . I propose #19304, what do you guys think?

Looks good, the focus didn't goes to the menu bar and i can use the Alt button in game.
But the need to edit ppsspp.ini kinda troublesome :)

**Comment by Gamerppsspp** [comment]
It seems to work, but if we also press another button, then everything is as it was. I have a player running by himself, but if you only press alt, it's fine.

**Comment by Gamerppsspp** [comment]
If, for example, I run and press alt, then the player runs himself, for example.

**Comment by hrydgard** [comment]
Hm, ok. maybe there's some more trickery we need to do...
