### ISSUE TITLE
Gundam VS Gundam next plus crash on Direct3D 11 mode on specific level while enabling the texture pack.

### ISSUE THREAD

**Issue by Jacky10X** [hrydgard/ppsspp#19312]
### Game or games this happens in

NPJH50107

### What area of the game / PPSSPP

Enter Arcade mode -> A course B(Beta) route 2 (or 3?), it freezes and crashes when the Backend is set to Direct3D 11. It is no problem when the backend is set to Vulkan. 

### What should happen

It should not crash.

### Logs

[ppsspplog.txt](https://github.com/user-attachments/files/16052553/ppsspplog.txt)

### Platform

Windows

### Mobile device model or graphics card (GPU)

Geforce RTX 2060 Super

### PPSSPP version affected

1.17.1

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [x] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by anr2me** [comment]
Might be better to test it on the [latest dev build](https://www.ppsspp.org/devbuilds) first in case it's already fixed

**Comment by hrydgard** [comment]
That, and please provide a link to the texture pack used.

**Comment by Jacky10X** [comment]
> Might be better to test it on the [latest dev build](https://www.ppsspp.org/devbuilds) first in case it's already fixed
I tested it and it still crashed on the latest dev build.

> That, and please provide a link to the texture pack used.
link: https://drive.google.com/file/d/1o_HHQycu9NMOzDZ9R8kif5EB1izgiNqg/view?usp=sharing

I tested another texture pack and it works even on Direct3D 11 mode. I guess it may be the texture pack issue? And I found the texture pack sometimes weird in multiplayer mode. (The 3.0 one)

**Comment by hrydgard** [comment]
Nah, if a texture pack makes it crash it's an emulator issue. Could you also grab a savestate, right where the D3D backend crashes? Use Vulkan to do so so you won't get a crash.

**Comment by Jacky10X** [comment]
> Nah, if a texture pack makes it crash it's an emulator issue. Could you also grab a savestate, right where the D3D backend crashes? Use Vulkan to do so so you won't get a crash.

link: https://drive.google.com/file/d/1CCwh4TSs9XzY-jefsBfLWwOuagbPCSVR/view?usp=sharing

When entering the game stage, It freezes and crashes.

**Comment by hrydgard** [comment]
Ok, something goes wrong loading a 1x1 texture, will fix!
