### ISSUE TITLE
GOW Ghost of Sparta Vulkan Flickering

### ISSUE THREAD

**Issue by ripcord95** [hrydgard/ppsspp#19311]
### Game or games this happens in

UCES01401 - Ghost of Sparta

### What area of the game

Main menu and Temple of Odin

### What happens

flickering in vulkan mode, does not happen in opengl but opengl has its own issues such as shadows are just black circle now while in swimming sequences

https://github.com/hrydgard/ppsspp/assets/135776748/6334995e-6b4f-4397-96b6-974dde648d30

### What should happen

no flickering

### Platform

Android

### Mobile device model or graphics card (GPU)

Poco X3 Pro

### PPSSPP version affected

1.17.1

### Last working version

1.16 

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [x] Try resetting settings or older versions and include if the issue is related.
- [x] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [x] Include logs or screenshots of issue.

**Comment by ripcord95** [comment]
i tested 1.16.6 and it doesnt happen

**Comment by anr2me** [comment]
is it just me or the video is really showing freezes/lags?

**Comment by ripcord95** [comment]
ok i don't know what happened but its fixed. I uninstalled ppsspp, installed 1.16.6 no flickering issues, i then updated using playstore, tested it again and no more flickering.

**Comment by ripcord95** [comment]
and its back after opening and closing ppsspp

**Comment by ripcord95** [comment]
https://github.com/hrydgard/ppsspp/assets/135776748/b19e3dd2-440e-43ea-9eef-55f031dce047


https://github.com/hrydgard/ppsspp/assets/135776748/42ed980d-aa49-4898-b640-75068666a68e

**Comment by hrydgard** [comment]
Have you tried the latest builds? I fixed a depth buffer synchronization issue a while ago:

https://www.ppsspp.org/devbuilds/

**Comment by hrydgard** [comment]
I think we can probably guess that this is fixed in the latest builds. Closing. Please re-open if it's not.
