### ISSUE TITLE
Enable Saving States in RA Hardcore Mode (Just Save, not Load)

### ISSUE THREAD

**Issue by BlueCorallite** [hrydgard/ppsspp#19342]
### What should happen

Allow players to save a state while in RA Hardcore Mode. To clarify, I am only asking to SAVE not LOAD.

### Who would this benefit

It's useful to have savestates in the case of achievements not triggering and issues similar to that, and it can be used as proof for manual unlocks and to help fix the issue. Other emulators like Duckstation and PCSX2 allow saving states in Hardcore Mode.

### Platform (if relevant)

None

### Games this would be useful in

any game

### Other emulators or software with a similar feature

Duckstation
PCSX2
RALibretro

### Checklist

- [X] Check the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
This functionality already exists, but it needs to be explicitly enabled to reduce clutter on the pause screen in the normal case. Most people aren't interested in save-only states, so we hide it away a bit.

Last option here:

![image](https://github.com/user-attachments/assets/b80c8ff6-59be-45a4-aefd-c7ee830fcf16)

**Comment by BlueCorallite** [comment]
Oh, thanks. probably should've checked that.

**Comment by hrydgard** [comment]
I added a mention of it to https://www.ppsspp.org/docs/reference/retro-achievements/ . Not that many people read that, probably :)
