### ISSUE TITLE
[GNU/Linux] [Out Run 2006] Game crashes when starting a race.

### ISSUE THREAD

**Issue by vanfanel** [hrydgard/ppsspp#19351]
### Game or games this happens in

Ulus - 10064 Outrun 2006 Coast 2 Coast 

### What area of the game / PPSSPP

Just when a race begins, sometime as the countdown ends and sometimes just a couple of seconds after the player car appears on screen, the game crashes with a segfault.
-Both standalone and RetroArch core are affected. 
-Both OpenGL and Vulkan backens are affected.
-No special flags where passed to the compiler.

### What should happen

The race should work normally.

### Logs

Here's what GDB says with a libretro debug version (but as I said the game crashes in the same way with standalone PPSSPP):

[log.txt](https://github.com/user-attachments/files/16322068/log.txt)

### Platform

Linux / BSD

### Mobile device model or graphics card (GPU)

Intel XE graphics, latest stable MESA 24.1.3

### PPSSPP version affected

Latest GIT code

### Last working version

I don't know if this game has ever worked.

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by vanfanel** [comment]
Here's the GDB backtrace with PPSSPP standalone:

[log.txt](https://github.com/user-attachments/files/16322079/log.txt)

**Comment by anr2me** [comment]
May be related to this too https://github.com/hrydgard/ppsspp/issues/13015

**Comment by hrydgard** [comment]
Nope, this one is a SSE bug, my bad. Fix coming up

**Comment by vanfanel** [comment]
Fix confirmed working! The game can be completed to the finish line now! (It's a beautiful but easy game).

**Comment by hrydgard** [comment]
Thanks for testing!
