### ISSUE TITLE
PPSSPPSDL crash when compiled in Debug mode on EMUELEC

### ISSUE THREAD

**Issue by Kelvfimer** [hrydgard/ppsspp#19352]
### Game or games this happens in

None

### What area of the game / PPSSPP

When starting Emuelec after PPSSPPSDL being compile in debug mode -DCMAKE_BUILD_TYPE=Debug . Commit https://github.com/hrydgard/ppsspp/commit/5edd02ef0a81fec0b9f0e6423cbea96123af083f .

I want to have the debug binary as I'm having an issue with retroachievements reported on https://github.com/hrydgard/ppsspp/issues/19353

ERROR => (/home/XXXX/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/PPSSPPSDL-5edd02ef0a81fec0b9f0e6423cbea96123af083f/Common/UI/Context.cpp:RebindTexture:96): [uitexture_] (menu, 0.0s) Assert!

/emuelec/bin/ppsspp.sh: line 15: 19410 Trace/breakpoint trap   PPSSPPSDL --fullscreen "${ARG}"

### What should happen

It should start the emulator

### Logs

[PPSSPPcrashlog.log](https://github.com/user-attachments/files/16322957/PPSSPPcrashlog.log)

### Platform

Linux / BSD

### Mobile device model or graphics card (GPU)

odroidn2+

### PPSSPP version affected

v1.17.1-903-g5edd02ef0a

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Must be some initialization order issue. What is EMUELEC? Is there a specific build configuration for it?

**Comment by Kelvfimer** [comment]
Emuelec is a free distro. https://github.com/EmuELEC/EmuELEC

**Comment by hrydgard** [comment]
ok. anyway, could it be that it doesn't find the asset files? 

Should probably make it print a more graceful error in that case, though.

**Comment by hrydgard** [comment]
I take it that it's working now?

**Comment by Kelvfimer** [comment]
It is not. But I don't have time to test :)

**Comment by hrydgard** [comment]
ok. since this has not been reported by anyone else, I'll switch it to "Closed as not planned".
