### ISSUE TITLE
Ubershader - Vertex causing darker color in Yu-Gi-Oh Arc V Tag Force Special

### ISSUE THREAD

**Issue by Fatcat2024-cpu** [hrydgard/ppsspp#19365]
### Game or games this happens in

NPJH-00142

### What area of the game

In the versus screen

### What happens

![Screenshot_20240723_223305_org ppsspp ppsspp](https://github.com/user-attachments/assets/dbd4e4f3-6e5c-4244-9926-1b8d53274795)
![Screenshot_20240723_223124_org ppsspp ppsspp](https://github.com/user-attachments/assets/af45a2a4-c143-43d0-9ec5-8bcb0f9aa0ba)

### What should happen

No darker color 
![Screenshot_20240723_223158_org ppsspp ppsspp](https://github.com/user-attachments/assets/16f62218-b2a6-48ea-bf0f-a2610f1779e8)

### Platform

Android

### Mobile device model or graphics card (GPU)

Huawei Nova 3i

### PPSSPP version affected

v1.17

### Last working version

v1.16

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by Fatcat2024-cpu** [comment]
This issue can also reproduce in Vulkan

**Comment by hrydgard** [comment]
Interesting, I'd expect it to carry over to PC too then.

Could you get a [GE frame dump](https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump)?

**Comment by Fatcat2024-cpu** [comment]
Sorry I can't get GE DUMP at the moment will upload later.

**Comment by hrydgard** [comment]
@Fatcat2024-cpu can you try with the latest build from https://www.ppsspp.org/devbuilds/ ?

**Comment by Fatcat2024-cpu** [comment]
Fix via https://github.com/hrydgard/ppsspp/pull/19367
