### ISSUE TITLE
Textures Folder Has Permissions on Android TV

### ISSUE THREAD

**Issue by GronyRalph** [hrydgard/ppsspp#19381]
### Game or games this happens in

None

### What area of the game / PPSSPP

So I'm trying to sideload a texture pack I made to my Chromecast, which doesn't have a file manager as you may know

Adb works to push files and folders but I can only up to Android/data/org.ppsspp.ppsspp/files/PSP

That's where the texture folder is but I can't get access to it, whatever I try to do gives me a permission denied error, I'm guessing it's protected?

Why, what can I do?

I tried uninstalling, creating the folder with the texture pack and reinstall it but then PSP can't save data, no settings, no saves, no anything
It also can't read the texture pack

### What should happen

It shouldn't have permissions so I can use texture packs,
It's already hard by itself to get stuff in these folders and now is impossible with the permissions

### Platform

Android

### Mobile device model or graphics card (GPU)

Chromecast with Google TV

### PPSSPP version affected

v1.17.1

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by anr2me** [comment]
Permissions is not something created by PPSSPP, it's from the OS and required user's intervention to grants it.

From what i read at https://support.google.com/googletv/thread/185340949/no-native-file-manager-app-for-google-tv-on-android-12?hl=en

Third-party file manager used to be able to grants permission, but after upgrading to Android 12 granting permission can only be done using native file manager or rooted.

**Comment by GronyRalph** [comment]
> Permissions is not something created by PPSSPP, it's from the OS and requires user's intervention to grants it.
> 
> From what i read at https://support.google.com/googletv/thread/185340949/no-native-file-manager-app-for-google-tv-on-android-12?hl=en
> 
> Third-party file manager used to be able to grants permission to access "Android/Data", but after upgrading to Android 12 granting permissions can only be done using native file manager or rooted.
> 
> Btw, have you tried using a different folder outside of "Android/Data" for the PSP memstick location? like the sdcard for example.

Hi thanks for replying,
I'm afraid I haven't found a way to do that. Devices with Google TV don't include a file picker UI, so when trying to select a file or a folder in any program, you get a well known message that says "You don't have an app that can do this" and nothing else :(

It's also the reason most emulators have bad reviews on the platform, almost all of them are affected by this problem, sometimes not even allowing to open ROMs
The only way I know would be if PPSSPP had a way to pick the path from within the app
Maybe a modified apk that has another path for the Memstick by default but I don't know how to do that

**Comment by GronyRalph** [comment]
> Devices that don't include any kind of file picker UI are simply not compatible with PPSSPP as it exists today, unfortunately. Might partially work and there can be workaround but fundamentally we can't really support it :(
> 
> A built-in file picker doesn't solve the permission problem.

Hi Henrik! thanks for you reply
I believe there may have been a misunderstanding however

Google TV doesn't have an activity apps can invoke to pick files, but file managers do work
The problem is that the Android/Data path has restricted access, as you know

If there was a built-in way to change the memstick path, we could set it to a location file managers do have access to, fixing the problem

This happens on mobile as well, after Android 12 you can't make modifications to anything in the Android/Data folder but mobiles do have a folder picker, so changing the memstick location is possible, therefore changing the memstick to a folder file managers have access to is possible

Google TV does allow apps like ZArchiver to act as a file picker, that you can use on PPSSPP to load games for example,
but it doesn't allow any app to do the folder picking action, this has to be on PPSSPP side

PPSSPP is trying to call a feature Google TV doesn't have but it can have access to with the simple files permission
![image](https://github.com/user-attachments/assets/5a724967-97be-4f47-adae-19371e2f6a29)

An easier way would be in the "Choose where to keep PSP data" screen, to have the "Create or choose a PSP folder" create it for us in a path outside the Android/data folder, like a simple "PSP" folder outside, in the root path where Downloads, documents, music and pictures folders are

**Comment by anr2me** [comment]
PPSSPP already do that when the first time you launch PPSSPP after installing it, PPSSPP will ask you to choose whether you want to use internal data (which is located at "Android/Data"), or select a folder anywhere in the storage for the memstick (which will brings you to a file/folder picker).
Most people choose to select the folder themself so it can be access by file manager too.

PS: You can also changed the memstick location from Settings->System on PPSSPP

**Comment by GronyRalph** [comment]
> You should create the folder first using a file manager somewhere outside Android/Data, and then select that folder when PPSSPP asked you for the memstick/PSP folder location.
> 
> PS: as i remembered sometimes you can also create a new folder from within the file picker, and then select that new folder you just created.

I think you're missing the problem here, the platform doesn't have a system folder picker PPSSPP can use

**Comment by anr2me** [comment]
> > You should create the folder first using a file manager somewhere outside Android/Data, and then select that folder when PPSSPP asked you for the memstick/PSP folder location.
> > PS: as i remembered sometimes you can also create a new folder from within the file picker, and then select that new folder you just created.
> 
> I think you're missing the problem here, the platform doesn't have a system folder picker PPSSPP can use

Then it's not supported by PPSSPP, because PPSSPP doesn't use [MANAGE_EXTERNAL_STORAGE](https://developer.android.com/training/data-storage/manage-all-files) permission like what File Manager apps use to access the root directory, thus PPSSPP can only access file/folder it have permission for, which granted by users through the file/folder picker (except for the `Android/data/<app_id_here>/` directory, which is the only accessible private area for each app by default).

**Comment by GronyRalph** [comment]
> > > You should create the folder first using a file manager somewhere outside Android/Data, and then select that folder when PPSSPP asked you for the memstick/PSP folder location.
> > > PS: as i remembered sometimes you can also create a new folder from within the file picker, and then select that new folder you just created.
> > 
> > 
> > I think you're missing the problem here, the platform doesn't have a system folder picker PPSSPP can use
> 
> Then it's not supported by PPSSPP, because PPSSPP doesn't use [MANAGE_EXTERNAL_STORAGE](https://developer.android.com/training/data-storage/manage-all-files#all-files-access-google-play) permission like what File Manager apps use to access the root directory, thus PPSSPP can only access file/folder it have permission for (the `Android/data/<app_id_here>/files` directory is the only accessible private area for each app by default).
> 
> Probably only native file/folder picker that can be used to grants access permission to an app on Android 12+ Well, you can try installing Google Files or Google Drive to see whether their file picker can be used to grants permission or not, since they're made by google, should've better chance than using file picker from a third-party company.
> 
> Related issue [#11997 (comment)](https://github.com/hrydgard/ppsspp/issues/11997#issuecomment-588535408)

These also don't have the capability of choosing folders I'm afraid
Is there a reason to avoid using that permission?

**Comment by anr2me** [comment]
> These also don't have the capability of choosing folders I'm afraid Is there a reason to avoid using that permission?

Quoted from that related issue:
> There's also a new MANAGE_EXTERNAL_STORAGE permission, that will be very cumbersome to explain to users how to enable though, which makes things easier for us if enabled. There's also support to use raw paths to read "external media libraries" whatever that is, might possible be useful?

There might also be approval issue when publishing the app at play store only allowing `MANAGE_EXTERNAL_STORAGE` for app in certain categories:
> If your app includes a use case similar to any of the following, it's likely that it can request the MANAGE_EXTERNAL_STORAGE permission:
>
>    - File managers
>    - Backup and restore apps
>    - Anti-virus apps
>    - Document management apps
>    - On-device file search
>    - Disk and file encryption
>    - Device-to-device data migration
>

Meanwhile, PPSSPP is more suitable for `game` category, especially if it wanted to take advantage of [Game Mode](https://developer.android.com/games/optimize/adpf/gamemode/gamemode-api) on Android 12+

**Comment by GronyRalph** [comment]
> > These also don't have the capability of choosing folders I'm afraid Is there a reason to avoid using that permission?
> 
> Quoted from that related issue:
> 
> > There's also a new MANAGE_EXTERNAL_STORAGE permission, that will be very cumbersome to explain to users how to enable though, which makes things easier for us if enabled. There's also support to use raw paths to read "external media libraries" whatever that is, might possible be useful?
> 
> There might also be approval issue when publishing the app at play store only allowing `MANAGE_EXTERNAL_STORAGE` for app in certain categories:
> 
> > To limit broad access to shared storage, the Google Play store has [updated its policy](https://support.google.com/googleplay/android-developer/answer/10467955) to evaluate apps that target Android 11 (API level 30) or higher and request all-files access through the MANAGE_EXTERNAL_STORAGE permission.
> > ...
> > If your app includes a use case similar to any of the following, it's likely that it can request the MANAGE_EXTERNAL_STORAGE permission:
> > 
> > * File managers
> > * Backup and restore apps
> > * Anti-virus apps
> > * Document management apps
> > * On-device file search
> > * Disk and file encryption
> > * Device-to-device data migration
> 
> Meanwhile, PPSSPP is more suitable for `game` category, especially if it wanted to take advantage of [Game Mode](https://developer.android.com/games/optimize/adpf/gamemode/gamemode-api) on Android 12+ (in the future may be?)

Thanks for the reply,
I understand the reason to try and keep it on the category, however I also believe this is a major issue that would make the change reasonable

It is important to have it properly displayed but what's the point of having it properly displayed if it doesn't work properly,
PPSSPP doesn't even have 3 stars on this platform Play Store because all the reviews point out this issue
I think the problem is that the scale of it hasn't come to your attention 
Just the first comment points out this issue and has 686 people agreeing with it
![PXL_20240807_004016750](https://github.com/user-attachments/assets/a56ca9d2-6fe9-4609-a5dd-d26ef8a55410)

And as time goes on and systems upgrade, more and more people will run into this issue, coming here and requesting for a fix
If the problem is that by making this change, it'd also affect mobile, I think the way would be making another store page, like other developers (Reelgood's for example) like "PPSSPP for Android TV"

**Comment by anr2me** [comment]
Btw, if your file manager couldn't access the "Android/data" folder, you can try using this FV File Manager mentioned in this video https://www.youtube.com/watch?v=-4H0K70WhDg
I heard NMM file explorer also works.

**Comment by hrydgard** [comment]
@GronyRalph I still don't understand what change exactly PPSSPP could make to fix this. We can't go back to the old permissions model because Google Play won't let us upload apps that target the older Android version. 

To start with I'd like to be able to inform users about what's going on but I don't even know a solid way to detect this type of device that doesn't have a file/folder picker. It's really frustrating to develop for a broken platform - the fault is really with the TV makers. Android TV on NVIDIA Shield *does* have a folder picker, for example!

We could make a separate APK that you'd have to sideload, that uses the old security model though, I've been considering that lately now that I have a solid buildbot again.

MANAGE_EXTERNAL_STORAGE  does not seem to be an option for us.

**Comment by GronyRalph** [comment]
> Btw, if your file manager couldn't access the "Android/data" folder, you can try using this FV File Manager mentioned in this video https://www.youtube.com/watch?v=-4H0K70WhDg I heard NMM file explorer also works.

Thanks for the reply but again, this is not a screen that's present in Google TV to allow access to it
![image](https://github.com/user-attachments/assets/4a0f8b51-8347-4538-bba8-30fca94cb58d)

**Comment by GronyRalph** [comment]
> @GronyRalph I still don't understand what change exactly PPSSPP could make to fix this. We can't go back to the old permissions model because Google Play won't let us upload apps that target the older Android versions.
> 
> To start with I'd like to be able to inform users about what's going on but I don't even know a solid way to detect this type of device that doesn't have a file/folder picker. It's really frustrating to develop for a broken platform - the fault is really with the TV makers. Android TV on NVIDIA Shield _does_ have a folder picker, for example!
> 
> We could make a separate APK that you'd have to sideload, that uses the old security model though, I've been considering that lately now that I have a solid buildbot again.
> 
> MANAGE_EXTERNAL_STORAGE does not seem to be an option for us.

I understand and we would appreciate a lot that release
But still I'm curious of what approach has again, Retroarch taken for example to be able to manage this

**Comment by anr2me** [comment]
> I understand and we would appreciate a lot that release But still I'm curious of what approach has again, Retroarch taken for example to be able to manage this

Based on their change logs:
> # 1.9.14
> - ANDROID/PLAYSTORE: Implement MANAGE_EXTERNAL_STORAGE permission
> - ANDROID/PLAYSTORE: Bump up SDK level to 30 to comply with Play Store policies
> ...

**Comment by hrydgard** [comment]
MANAGE_EXTERNAL_STORAGE  requires special permission from Google, and I don't think we can get it.

**Comment by anr2me** [comment]
True, which is why RetroArch at Play Store haven't been updated since 2021
But MANAGE_EXTERNAL_STORAGE should works on sideloaded APK, right? it seems to works on devices that use alternative stores too based on the commit at RetroArch.

**Comment by hrydgard** [comment]
For a sideloaded APK, we can just "target" (specify in the build.gradle file) old Android SDK versions and we'll get the old-school single-question permission model. Presumably that workaround will be removed from Android at some future time, but it's still possible.

**Comment by GronyRalph** [comment]
> For a sideloaded APK, we can just "target" (specify in the build.gradle file) old Android SDK versions and we'll get the old-school single-question permission model. Presumably that workaround will be removed from Android at some future time, but it's still possible.

So do you think you will release this workaround? 😢

**Comment by hrydgard** [comment]
@GronyRalph That's what this is: #19401 

I'll find some time soon to add it to the buildbot for easy download as well, but if you know how to build yourself with gradle, it's now `gradle assembleLegacyOptimized`

**Comment by hrydgard** [comment]
If you're able to sideload, you can now download the first PPSSPP Legacy APK from  https://www.ppsspp.org/devbuilds/ , should help. These will be available from 1.17.1-980 and forwards.

**Comment by GronyRalph** [comment]
> If you're able to sideload, you can now download the first PPSSPP Legacy APK from https://www.ppsspp.org/devbuilds/ , should help. These will be available from 1.17.1-980 and forwards.

Thank you so much Henrik, you've brought life back to this platform
I'll make sure to spread the word! such a legend
