### ISSUE TITLE
Disabling plugins and closing the emulator re-enable them

### ISSUE THREAD

**Issue by MrWrightyLC** [hrydgard/ppsspp#19380]
### Game or games this happens in

Any

### What area of the game / PPSSPP

Steps to reproduce it
1-Open PPSSPP and go to settings>system> and uncheck "enable plugins".
2-Close PPSSPP either from the exit option or close it by killing the process.
3-Reopen PPSSPP and go back to settings>system and see that "enable puglins" has been enabled by itself.

### What should happen

If the plugins are disabled they should stay that way

### Logs

https://github.com/user-attachments/assets/adf50007-9dcc-4f72-b817-8dc701229f40

### Platform

Android

### Mobile device model or graphics card (GPU)

Xiaomi Poco X5 5G

### PPSSPP version affected

[v1.17.1-957-52cf10247c](https://github.com/hrydgard/ppsspp/commit/52cf10274c342c1dd97d91c273b109d5c859d227)

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by anr2me** [comment]
I can confirm this, it's strange that a simple checkbox keeps using the default value when restarting PPSSPP.

May be it have something do to with the `CfgFlag::REPORT` flag?
```
        ConfigSetting("EnablePlugins", &g_Config.bEnablePlugins, true, CfgFlag::PER_GAME | CfgFlag::REPORT),
```

**Comment by iota97** [comment]
It seems that both `bEnablePlugins` and `bLoadPlugins` have the same ini key `"EnablePlugin"`. I guess changing the load one to a different one will fix the problem.

**Comment by anr2me** [comment]
Nice finding! 
Btw are they have different function? like "enable" doesn't always "load" the plugin?

**Comment by iota97** [comment]
Tbh I have no idea, load seems to affect only this:

https://github.com/hrydgard/ppsspp/blob/52cf10274c342c1dd97d91c273b109d5c859d227/Core/HLE/Plugins.cpp#L156-L159

Nevertheless, it is not exposed anywhere so it's like an ini only setting (and also a broken one). Maybe it's there for historical reason?
