### ISSUE TITLE
compile for aarch64 target,ld error undefined reference to `CpuFeatures_GetHardwareCapabilities'  undefined reference to `CpuFeatures_IsHwCapsSet'

### ISSUE THREAD

**Issue by sunqianGitHub** [hrydgard/ppsspp#19393]
### Platform

Linux / BSD

### Compiler and build tool versions

GGC 11.3.0 + cmake-3.27

### Operating system version

use host ubuntu cross compile for aarch64 target

### Build commands used

./b.sh --sl1620

### What happens

[100%] Linking CXX executable PPSSPPSDL
/opt/poky/4.0.9/sysroots/x86_64-pokysdk-linux/usr/libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/11.3.0/ld: lib/libcpu_features.a(impl_aarch64_linux_or_android.c.o): in function `GetAarch64Info':
impl_aarch64_linux_or_android.c:(.text+0x15b8): undefined reference to `CpuFeatures_GetHardwareCapabilities'
/opt/poky/4.0.9/sysroots/x86_64-pokysdk-linux/usr/libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/11.3.0/ld: impl_aarch64_linux_or_android.c:(.text+0x15d8): undefined reference to `CpuFeatures_IsHwCapsSet'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/PPSSPPSDL.dir/build.make:729: PPSSPPSDL] Error 1
make[1]: *** [CMakeFiles/Makefile2:1015: CMakeFiles/PPSSPPSDL.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Linking CXX static library ../../lib/libspirv-cross-msl.a
[100%] Built target spirv-cross-msl
make: *** [Makefile:146: all] Error 2

### PPSSPP version affected

const char *PPSSPP_GIT_VERSION = "v1.17.1-966-g1c5512a75d";

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] Make sure to run `git submodule update --init --recursive` before building.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try deleting the build directory and running the build again.
- [ ] Check GitHub Actions, which builds every merge and PR.
- [ ] Include logs and help us reproduce.

**Comment by sunqianGitHub** [comment]
sl1620 cmake file :
_set(USING_EGL ON)
set(USING_GLES2 ON)
set(USING_FBDEV ON)
set(USING_X11_VULKAN OFF)
set(USE_WAYLAND_WSI ON)
set(USE_VULKAN_DISPLAY_KHR OFF)

set(USE_CCACHE OFF)

set(ARM64  ON)
set(X86  OFF)
set(X86_64 OFF)
set(ARMV7 OFF)
set(ARM OFF)
set(MIPS OFF)
set(RISCV64 OFF)
set(LOONGARCH64 OFF)


set(USE_SYSTEM_SNAPPY ON)
set(USE_SYSTEM_LIBZIP ON)
set(USE_SYSTEM_LIBSDL2 ON)
set(USE_SYSTEM_LIBPNG ON)


set(ARCH_FLAGS "-march=armv8.2-a -mtune=cortex-a55 -funsafe-math-optimizations")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${ARCH_FLAGS}"  CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${ARCH_FLAGS}" CACHE STRING "" FORCE)
set(CMAKE_ASM_FLAGS "${CMAKE_ASM_FLAGS} ${ARCH_FLAGS}" CACHE STRING "" FORCE)

_

**Comment by anr2me** [comment]
hmm.. i didn't know that there is `--sl1620` parameter for `b.sh` O.o

**Comment by sunqianGitHub** [comment]
i resolve the buid error,
this is my build system issue
