### ISSUE TITLE
Java Exception Error

### ISSUE THREAD

**Issue by Harunz24** [hrydgard/ppsspp#19397]
### Game or games this happens in

None

### What area of the game / PPSSPP

![Screenshot_20240812_004056_PPSSPP](https://github.com/user-attachments/assets/c92353f8-cac1-4b2c-8bd7-fcdfcab8e161)

### What should happen

When i choose the "Create new PSP folder or choose" it should send me to Zarchiver

### Logs

![Screenshot_20240812_004325_PPSSPP](https://github.com/user-attachments/assets/0be0d528-7a1b-425d-ac8b-4932f72cf91c)

### Platform

Android

### Mobile device model or graphics card (GPU)

Samsung Galaxy a53

### PPSSPP version affected

1.17.1

### Last working version

I think 1.17

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by anr2me** [comment]
Btw, Samsung devices have a native file/folder picker isn't? How did you changed the default file/folder picker to Zarchiver?
Does it even works on other Apps that use file/folder picker like PPSSPP?

**Comment by Harunz24** [comment]
> Btw, Samsung devices have a native file/folder picker isn't? How did you changed the default file/folder picker to Zarchiver?
> Does it even works on other Apps that use file/folder picker like PPSSPP

Yes it has.But when you download zarchiver you can use it as default folder picker

I think it works but unfortunately i get this crash so idk it works or not but i think yes

**Comment by hrydgard** [comment]
Here's information about the error:

https://www.ppsspp.org/docs/troubleshooting/cant-pick-folder/

Do not change the folder picker. I had no idea you could use Zarchiver as one, it seems like an extremely bad idea - obviously it doesn't handle OPEN_DOCUMENT_TREE which is essential.

**Comment by Harunz24** [comment]
> Here's information about the error:
> 
> https://www.ppsspp.org/docs/troubleshooting/cant-pick-folder/
> 
> Do not change the folder picker. I had no idea you could use Zarchiver as one, it seems like an extremely bad idea - obviously it doesn't handle OPEN_DOCUMENT_TREE which is essential.

If i delete zarchiver will it work?

**Comment by Harunz24** [comment]
> Here's information about the error:
> 
> https://www.ppsspp.org/docs/troubleshooting/cant-pick-folder/
> 
> Do not change the folder picker. I had no idea you could use Zarchiver as one, it seems like an extremely bad idea - obviously it doesn't handle OPEN_DOCUMENT_TREE which is essential.

I deleted the Zarchiver and opened PPSSPP
It didnt work unfortunately.I dont know what is problem

**Comment by Harunz24** [comment]
> Here's information about the error:
> 
> https://www.ppsspp.org/docs/troubleshooting/cant-pick-folder/
> 
> Do not change the folder picker. I had no idea you could use Zarchiver as one, it seems like an extremely bad idea - obviously it doesn't handle OPEN_DOCUMENT_TREE which is essential.

Broo i fixed it thank you so much

**Comment by anr2me** [comment]
> Here's information about the error:
> 
> https://www.ppsspp.org/docs/troubleshooting/cant-pick-folder/
> 
> Do not change the folder picker. I had no idea you could use Zarchiver as one, it seems like an extremely bad idea - obviously it doesn't handle OPEN_DOCUMENT_TREE which is essential.

btw, i think there is a typo at this part
>  I'm considering making a special build for these older TVs that target **andolder** API version.

**Comment by Harunz24** [comment]
> > Here's information about the error:
> > https://www.ppsspp.org/docs/troubleshooting/cant-pick-folder/
> > Do not change the folder picker. I had no idea you could use Zarchiver as one, it seems like an extremely bad idea - obviously it doesn't handle OPEN_DOCUMENT_TREE which is essential.
> 
> btw, i think there is a typo at this part
> 
> > I'm considering making a special build for these older TVs that target **andolder** API version.

Thanks bro i did it 🫡
