### ISSUE TITLE
psspp vr with oculus quest 3 after updated v69 oculus - black screen or 3 dots, no loading

### ISSUE THREAD

**Issue by krzysiek13923** [hrydgard/ppsspp#19399]
### Game or games this happens in

- black screen on start

### What area of the game / PPSSPP

when i open psp vr emu, on oculus quest 3 i see black screen or 3 dots. i tested all version of psp emu, problem its on updated oculus quest 3 v69

### What should happen

opened app without crash

### Platform

Android

### Mobile device model or graphics card (GPU)

oculus quest 3

### PPSSPP version affected

all version

### Last working version

working before updated oculus quest 3

### Graphics backend (3D API)

Vulkan

### Checklist

- [ ] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
tested all versions? does that include the APKs from https://www.ppsspp.org/devbuilds/ ? ("AndroidVR")

**Comment by krzysiek13923** [comment]
Yes :( i tested also dev builds and doesnt work, also i tested version official from sidequest oculus and i have only 3 Dots loading all time, on Dec builds from 12.08.2024 r., i dont have loading Dots all time but i have Black screen only :/

**Comment by hrydgard** [comment]
Hm, @lvonasek , any idea? You had a Quest 3 to test on right?

**Comment by lvonasek** [comment]
I didn't get v69 on my Quest 2 or Quest 3. I could sideload v69 on Quest 2 and give it a try (I do not have access to v69 on Quest 3 yet).

Note that the bug might be fixed with next OS update as v69 is still on public testing channel only.

**Comment by lvonasek** [comment]
My Quest 2 refuses to sideload v69. I will look into this once the OS update is official.

**Comment by jesse-dot** [comment]
Sideloaded latest version of PPSSPP onto my quest 3, the infinite loading bug happened.

**Comment by krzysiek13923** [comment]
> Sideloaded latest version of PPSSPP onto my quest 3, the infinite loading bug happened.

where/when i can download ppssp ver. hotfix for v69?

**Comment by hrydgard** [comment]
@krzysiek13923 very soon on https://www.ppsspp.org/devbuilds/

**Comment by lvonasek** [comment]
Direct link to the the build:
https://builds.ppsspp.org/builds/v1.17.1-998-ge416ccf813/ppsspp_vr.apk

**Comment by lvonasek** [comment]
Final fix:
https://builds.ppsspp.org/builds/v1.17.1-1002-g5fd8fae8b5/ppsspp_vr.apk

The issue should be closed now.
