### ISSUE TITLE
Reports of plugins not working correctly

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#19395]
By e-mail: "I've been trying to get ThirteenAG's plugins for Chinatown Wars and Liberty City Stories to work, but even tho I followed the install instructions, they don't work AT ALL. And I can't find anything on this issue."

Trying to get clarification on device, but should take a proper look look before 1.18.

**Comment by LunaMoo** [comment]
Seeing how the install notes are just:

````
Supported version: ULUS-10490
Installation:
Download and extract the archive to the directory, where PPSSPP's memstick folder is located.
Check the download link below for all available features.
Launch the game.
````

There are at least a few things that could go wrong on the user side:
- user not knowing what game version does he own and trying to use plugin for unsupported version,
- user not knowing where his memstick folder is located and/or the compressed plugin has a folder structure that doesn't match where user wants to extract it,
- user not understanding what extracting the archive means to begin with,
- using PPSSPP version that doesn't support plugins.
