### ISSUE TITLE
Android 11 Google TV - MI TV 2nd Gen 

### ISSUE THREAD

**Issue by Ridwaan112** [hrydgard/ppsspp#19400]
ACTION_OPEN_DOCUMENT_TREE intent issue - not working in Google TV android 11 - please fix or provide solution

**Comment by hrydgard** [comment]
This is the same as https://github.com/hrydgard/ppsspp/issues/16865 , closing.

**Comment by Ridwaan112** [comment]
I know you busy with (IOS / Apple) but please don't forget that we android users are your true fans and have been supporting through thick and thin - a fix for the Google TV issue I'm facing would be appreciated or a work around to get games playing

**Comment by hrydgard** [comment]
Hi there, it's not a very solvable problem directly unfortunately. We can't publish new builds on Google Play that use the old methods of disk access.

But! You can now work around it using the new "PPSSPP Legacy" build, which you can now download as an APK from https://www.ppsspp.org/devbuilds/ ("AndroidLegacy").

See https://www.ppsspp.org/docs/reference/legacy-edition/

As I said though, unfortunately we can't put this build on Google Play, but it can still help people who know how to install APKs.

**Comment by Ridwaan112** [comment]
> Hi there, it's not a very solvable problem directly unfortunately. See the other issues about this. We can't publish new builds on Google Play that use the old methods of disk access.
> 
> But! You can now work around it using the new "PPSSPP Legacy" build, which you can now download as an APK from https://www.ppsspp.org/devbuilds/ ("AndroidLegacy").
> 
> See https://www.ppsspp.org/docs/reference/legacy-edition/ for more information.
> 
> As I said though, unfortunately we can't put this build on Google Play, but it can still help people who know how to install APKs.

Hi, once again I Thank you for the legacy build... It brings much joy that we are still able to enjoy ppsspp on android 11 - I have responded on another thread with regards to the issue im experienceing with the controller being non responsive - I've tried the same build on an older device and it works smoothly and the controller works perfectly fine... It's on the Mi TV box 2nd Gen Android 11 that the build loads and the game loads but the controller is non responsive. I'm stucked here... Please help
