### ISSUE TITLE
iOS PPSSPP keeps deleting settings on iOS App Store version.

### ISSUE THREAD

**Issue by gg-ez2005** [hrydgard/ppsspp#19412]
Also mentioned this on their Discord.
iOS PPSSPP keeps deleting settings issue: (graphics, controls, everything manual set by user) When deleting Saves/Save-States, while Playing a Game (playing game where settings defaults happens rarely on only specific games) PPSSPP forgets the PPSSPP folder in iOS Files and all returns back to default configuration. 
This is fixed temporarily by uninstalling and re-installing the App and making a backup of controls.ini and ppsspp.ini that came with the installation of the PPSSPP app on the iOS AppStore as these gets saved when a user manually changes settings.
Found a similar Reddit post about this issue. However it was also an issue from Android a year ago.

**Comment by hrydgard** [comment]
I don't understand this at all. The contents of the app's data folder (the one that contains the PSP folder) doesn't change when upgrading, and that's where the settings are stored.

Did you move the memstick folder somewhere? I don't know how else things could possibly break.

**Comment by anr2me** [comment]
> (playing game where settings defaults happens rarely on only specific games)

I'm a bit confused with this, you mean this issue only happened on game-specific settings?

**Comment by LunaMoo** [comment]
Maybe it's about removing saves, savestates via external program that messes up file access, directory ownership etc.? 🙃 Those were primary iOS issues in the old times where people stopped PPSSPP from being able to write to it's folders by copying games with some popular, but awful software.

**Comment by EJ-C** [comment]
Same issue here

**Comment by anr2me** [comment]
Did you delete or move the file/directory using external app?

May be show us a video of it?

**Comment by gg-ez2005** [comment]
> I don't understand this at all. The contents of the app's data folder (the one that contains the PSP folder) doesn't change when upgrading, and that's where the settings are stored.
> 
> 
> 
> Did you move the memstick folder somewhere? I don't know how else things could possibly break.
> 
> 
> 
> When exactly do you seem to lose settings?

Yep. I moved the memstick folder.
I was creating another memstick folder so I can easily delete save files before I found out I can do that on the PPSSPP app. 
Also. When I moved my memstick folder to SaveData, because I was wondering why my games aren't detecting a memstick. By moving the memstick folder to the SaveData folder inside PPSSPP. It created another folder called PPSSPP in the SaveData folder. Which caused all my settings to disappear.

**Comment by hrydgard** [comment]
For now, do not move the memstick folder on iOS. Seems to have issues indeed.

Did you move it somewhere outside the app folder somehow?

**Comment by gg-ez2005** [comment]
> For now, do not move the memstick folder on iOS. Seems to have issues indeed.
> 
> 
> 
> Did you move it somewhere outside the app folder somehow?

I created a folder a week ago to store my saves outside of the PPSSPP folder in iOS Files App. That caused PPSSPP to reset settings. 
I won't touch it ever again.
