### ISSUE TITLE
AchievementsEnableRAIntegration option in Linux 

### ISSUE THREAD

**Issue by Kelvfimer** [hrydgard/ppsspp#19424]
### Game or games this happens in

None

### What area of the game / PPSSPP

Hello

I would like to use the option AchievementsEnableRAIntegration however I see it doesn't appear in the Achievements menu, I was expecting to find it here RAIntegration support in Settings/Tools/RetroAchievements/Development/Enable RAIntegration as described https://www.ppsspp.org/docs/reference/retro-achievements/ . I enabled it via ppsspp.ini but doesn't work.

Besides reading the code I see it depends of RC_CLIENT_SUPPORTS_RAINTEGRATION and I don't see any parameter related to make it. https://github.com/hrydgard/ppsspp/blob/5fd8fae8b5bedafc97487d7bc004533d9612a6c7/Core/RetroAchievements.cpp#L626

I'm making PPSSPPSDL with these parameters PKG_CMAKE_OPTS_TARGET+="-DUSE_SYSTEM_FFMPEG=ON \
                        -DUSING_FBDEV=ON \
                        -DUSING_EGL=OFF \
                        -DUSING_GLES2=ON \
                        -DUSING_X11_VULKAN=OFF \
                        -DUSE_DISCORD=OFF"

### What should happen

Retroarch cheevos inegration

### Logs

No logs

### Platform

Linux / BSD

### Mobile device model or graphics card (GPU)

mali

### PPSSPP version affected

5fd8fae8b5bedafc97487d7bc004533d9612a6c7

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Uh what? RAIntegration is, as far as I know, still a Windows-only toolkit for developing retro-achievements. It's supplied as a Windows DLL.

Linux support therefore does not make sense, unless you're talking about running it in Wine, in which case you'll use the Windows build.

Closing, let me know if I got something wrong.

**Comment by Kelvfimer** [comment]
Ah sorry I didn't know.it was only related to Windows. My fault.

**Comment by hrydgard** [comment]
I'll add a quick note to the website to make it clearer.
