### ISSUE TITLE
Flatout Head On (1.02, Europe) - music playlist skipping track itself

### ISSUE THREAD

**Issue by GermanAizek** [hrydgard/ppsspp#19421]
https://github.com/user-attachments/assets/e6b90d46-6e6e-466e-9306-413504d612de

### Game or games this happens in

ULES00968 v 1.00

### What area of the game / PPSSPP

background music playlist switches itself without pressing the keys, the control settings have not changed and are by default

### Platform

Android

### Mobile device model or graphics card (GPU)

Andreno 618

### PPSSPP version affected

v1.17.1-975-g80e581a093

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.

**Comment by sum2012** [comment]
known issue in https://github.com/hrydgard/ppsspp/issues/6663
