### ISSUE TITLE
Burnout Dominator: Strange top-left border visible on iOS

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#19427]
Reported by RealisticArcadeSimulator on Discord:

![image](https://github.com/user-attachments/assets/38598267-e69b-4efe-83a4-193fda75abb8)

The border changes color a bit when saving/loading state, weirdly. Confirmed on iPhone 12, Vulkan.

**Comment by hrydgard** [comment]
Not happening on either Mac or Windows. Strange.

**Comment by csacskamacskamocska** [comment]
Sorry, It's me, who reported this stuff, just my handle is different here. I forgot to mention that the analog stick's background can't be turned on if the button style is set to classic. Can you please fix that as well? Thanks.

**Comment by hrydgard** [comment]
In the latest build, on iOS 18, this doesn't seem to be happening anymore. So either it's related to some other bug that's been fixed recently,  or it was a driver bug that's been fixed in iOS 18. Either way, nothing to do here, so I'm closing.
