### ISSUE TITLE
Distorted garbage textures in "Lick It" demo

### ISSUE THREAD

**Issue by worduk** [hrydgard/ppsspp#19435]
### Game or games this happens in

[Lick It](https://www.pouet.net/prod.php?which=25858)

### What area of the game

Everywhere

### What happens

Distorted garbage textures

### What should happen

Render correct textures

### GE frame capture

![Distorted garbage textures](https://github.com/user-attachments/assets/ff57060e-b694-4d1e-a2ee-3a574fc2eaa7)

### Platform

Linux / BSD

### Mobile device model or graphics card (GPU)

Mesa Intel(R) HD Graphics 520 (SKL GT2) or NVIDIA GeForce 940M/PCIe/SSE2

### PPSSPP version affected

v1.17.1-1018-g450ac75ee

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [ ] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by anr2me** [comment]
Wow even software renderer doesn't work for this game
![image](https://github.com/user-attachments/assets/f9490b8b-6cd6-4741-a1e6-dfc67cb3d761)
But that texture that looked like lines at the top right of the screen, looked similar to an image that have a different width with the visible framebuffer that being rendered as a continues pixel array (where pixels that supposed to go to the next row ended at the right side of the current row)

PS: I also saw this in the logs `Core\Compatibility.cpp:153 N[G3D]: UnitsPerMeter for EBOO00649: 0.000000` 
Does UnitsPerMeter allowed to be 0? (i don't know what is UnitsPerPeter)

**Comment by hrydgard** [comment]
UnitsPerMeter is only for VR, so it's not related.

This is really surprising, probably the game is doing something slightly invalid when specifying the texture that we are not handling the same as the hardware. Will need to investigate.

**Comment by hrydgard** [comment]
This is probably not a rendering problem, the log shows stuff like:

26:17:499 TRSI_LICK_IT I[PRINTF]: HLE\sceIo.cpp:1197 stdout: [DB] loading PNG ms0:/PSP/GAME/__SCE__LICKIT/data/textures/scene4_prod_noblur.png failed ! error -1
26:17:499 TRSI_LICK_IT I[PRINTF]: HLE\sceIo.cpp:1197 stdout: [scene4_preRender] load blurred production Texture
26:17:516 TRSI_LICK_IT I[PRINTF]: HLE\sceIo.cpp:1197 stdout: [DB] loading PNG ms0:/PSP/GAME/__SCE__LICKIT/data/textures/scene4_prod_blur.png failed ! error -1
26:17:516 TRSI_LICK_IT I[PRINTF]: HLE\sceIo.cpp:1197 stdout: [SCENE4_TEST] scene4_preRender ended

So it's just failing to load the textures, and texturing from garbage memory.

The question now is why it fails to load the texture. It uses the old PSP 1.5 "swap trick" with the real executable in `__SCE__LICKIT` and the icon and stuff in `%__SCE__LICKIT`, but I don't see how that would affect the texture loading.. maybe some relative path thing we're getting wrong, and it gets confused? 

Because it seems it doesn't even attempt to do any I/O, it just claims the texture loads failed!

**Comment by anr2me** [comment]
Right, after sceIoOpen it read from STDIN instead of the opened fd, and then close the fd and claimed it failed, strange indeed
```
01:36:389 TRSI_LICK_IT D[SCEIO]: HLE\sceIo.cpp:1284 21=sceIoWrite(1, 08b72fa0, 21)
01:36:390 TRSI_LICK_IT I[PRINTF]: HLE\sceIo.cpp:1197 stdout: [Drain_preRender] load Color texture
01:36:390 TRSI_LICK_IT D[SCEIO]: HLE\sceIo.cpp:1284 25=sceIoWrite(1, 08b72fa0, 25)
01:36:396 TRSI_LICK_IT D[SCEIO]: HLE\sceIo.cpp:1610 4=sceIoOpen(ms0:/PSP/GAME/__SCE__LICKIT/data/textures/start_logo1_color.png, 1, 438)
01:36:399 TRSI_LICK_IT D[SCEIO]: HLE\sceIo.cpp:1061 sceIoRead STDIN
01:36:399 TRSI_LICK_IT D[SCEIO]: HLE\sceIo.cpp:1156 0=sceIoRead(3, 0bfbfca8, 8)
01:36:399 TRSI_LICK_IT D[SCEIO]: HLE\sceIo.cpp:1616 sceIoClose(4)
01:36:399 TRSI_LICK_IT I[PRINTF]: HLE\sceIo.cpp:1197 stdout: [DB] loading PNG ms0:/PSP/GAME/__SCE__LICKIT/data/textures/start_logo1_color.png failed ! error -1
01:36:399 TRSI_LICK_IT D[SCEIO]: HLE\sceIo.cpp:1284 63=sceIoWrite(1, 08b72fa0, 63)
01:36:399 TRSI_LICK_IT I[PRINTF]: HLE\sceIo.cpp:1197 stdout: [Drain_preRender] load B&W texture
01:36:399 TRSI_LICK_IT D[SCEIO]: HLE\sceIo.cpp:1284 23=sceIoWrite(1, 08b72fa0, 23)
01:36:402 TRSI_LICK_IT D[SCEIO]: HLE\sceIo.cpp:1610 4=sceIoOpen(ms0:/PSP/GAME/__SCE__LICKIT/data/textures/start_logo1_nocolor.png, 1, 438)
01:36:403 TRSI_LICK_IT D[SCEIO]: HLE\sceIo.cpp:1061 sceIoRead STDIN
01:36:403 TRSI_LICK_IT D[SCEIO]: HLE\sceIo.cpp:1156 0=sceIoRead(3, 0bfbfca8, 8)
01:36:403 TRSI_LICK_IT D[SCEIO]: HLE\sceIo.cpp:1616 sceIoClose(4)
01:36:403 TRSI_LICK_IT I[PRINTF]: HLE\sceIo.cpp:1197 stdout: [DB] loading PNG ms0:/PSP/GAME/__SCE__LICKIT/data/textures/start_logo1_nocolor.png failed ! error -1
```

**Comment by hrydgard** [comment]
Oh, I guess I had my logging settings wrong, I didn't see the stdin read... I guess we'll need to api-trace this on hardware to get some clues.

Hm, that crash-upon-crash is unexpected...

**Comment by anr2me** [comment]
Btw, does reading STDIN means reading the last opened file? i don't understand why the game didn't use the outputted fd when reading it.

**Comment by sum2012** [comment]
(upload lickit here prevent lose)
[tt-lickit_psp.zip](https://github.com/user-attachments/files/17003958/tt-lickit_psp.zip)
Jpcsp run it no problem
jpcsp io debug log
[jpcsplog.zip](https://github.com/user-attachments/files/17003957/jpcsplog.zip)

**Comment by hrydgard** [comment]
seems the game just assumes the returned ID is 3, which JPCSP returns, while we return 4. So we probably have different behavior in file descriptor allocation... Maybe 3 should only be forced to be stdin after some function has been called?

```
06:10:15 DEBUG hle.IoFileMgrForUser - TRSI_LICK_IT - sceIoWrite returning 0x5A
06:10:15 DEBUG hle.IoFileMgrForUser - TRSI_LICK_IT - sceIoOpen filename=0x09FBF6E0('ms0:/PSP/GAME/tt-lickit_psp/__SCE__LICKIT/data/samples/thxmono22.wav'), flags=0x1, permissions=0x1B6
06:10:15  INFO hle.IoFileMgrForUser - TRSI_LICK_IT - hleIoOpen filename = ms0:/PSP/GAME/tt-lickit_psp/__SCE__LICKIT/data/samples/thxmono22.wav flags = 1 permissions = 0666
06:10:15 DEBUG hle.IoFileMgrForUser - TRSI_LICK_IT - PSP_O_RDONLY
06:10:15 DEBUG hle.IoFileMgrForUser - TRSI_LICK_IT - hleIoOpen assigned id=0x3
06:10:15 DEBUG hle.IoFileMgrForUser - TRSI_LICK_IT - sceIoOpen returning 0x3
06:10:15  INFO compiler - TRSI_LICK_IT - Replacing CodeBlock at 0x0897D6DC by Native Code 'memcpy'
06:10:15 DEBUG hle.IoFileMgrForUser - TRSI_LICK_IT - sceIoLseek id=0x3, offset=0x0, whence=0x1
```

**Comment by sum2012** [comment]
I fix the game :)
![3](https://github.com/user-attachments/assets/358e69dc-0a46-43a1-afb7-e4d46ff27bf5)

**Comment by hrydgard** [comment]
Yeah, that takes care of it indeed. Too bad this demo really isn't a great production though! :)
