### ISSUE TITLE
make Turbo and alternatice speeds toggle (at least optional)

### ISSUE THREAD

**Issue by natter1** [hrydgard/ppsspp#19433]
### What should happen

I can't imagine why anyone wants to permanently hold a key for a different speed. At least add an option that pressing the turbo key or key for alternative speed 1 and 2 simply changes the speed until pressed again. 

### Who would this benefit

In  my opinion everyone - I would even say it should be default behaviour. Never understood why some emulators think otherwise.

### Platform (if relevant)

None

### Games this would be useful in

all

### Checklist

- [X] Check the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by natter1** [comment]
Due to keyboard layout the toggle speed option didn't work for me so I overlooked that feature. Changing the key binding to something fitting for german layout solved the issue.

**Comment by hrydgard** [comment]
Great that it's working. Next time you think about a missing feature, think about the tone of your report. Not very pleasant, this one, but I'll let it slide.
