### ISSUE TITLE
[Android] Metal Gear Solid Peace Walker Freeze When Playing Extra Ops 38/67 And Main Mission Zadornov Search 3

### ISSUE THREAD

**Issue by FalloutClassicGamer** [hrydgard/ppsspp#19452]
i tried 2 different saves its just freeze when i play that mission

**Comment by hrydgard** [comment]
Can you post some saves that make it easy to get into these missions to try them?

**Comment by FalloutClassicGamer** [comment]
> Can you post some saves that make it easy to get into these missions to try them?

here is my save file and save state from zadornov search 3 mission ![PPSSPP_STATE.zip](https://github.com/user-attachments/files/16992771/PPSSPP_STATE.zip)

![ULUS10509003.zip](https://github.com/user-attachments/files/16992770/ULUS10509003.zip)
