### ISSUE TITLE
Metal Gear Acid 2 Character shadow rendering incorrectly in Vulkan

### ISSUE THREAD

**Issue by oldmario** [hrydgard/ppsspp#19451]
### Game or games this happens in

ULUS-10077 - Metal Gear Acid 2

### What area of the game

Any area of the game

### What happens

the black outline shadow stays in place despite rotation when it should be following the view 

i have posted a video of this in the server, i did try uploading the video but it's too big for Github to let me https://discord.com/channels/293316141479362560/480103153803460614/1137183413946818590

### What should happen

the shadow should follow the rotation of the character models in the game, it only seems to be affected with the Vulkan backend, playing on openGL makes the shadow display correctly, it should also be noted that the fast forward button can fix the shadow on Vulkan but when you rotate the camera the shadow is stuck again

### Platform

Android

### Mobile device model or graphics card (GPU)

Galaxy Z Fold 3

### PPSSPP version affected

this has been an issue since atleast last august when i first tried it out in the emulator

### Last working version

n/a

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
I believe this is fixed, possibly related to #19439 . Closing.
