### ISSUE TITLE
Splinter Cell Essentials: Night vision mode is black on some devices

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#19461]
Reported in #13035 by @antipirgos: [link](https://github.com/hrydgard/ppsspp/issues/13035#issuecomment-2350302545)

Specs: Opengl 3.0 on Huawei Mediapad T3 10 Android 8.0 Oreo (Adreno 308)

It's a quite basic CLUT lookup effect, making the screen monochrome using three passes, so not sure why it would fail.

(While debugging this, I also ran into an issue where savestates are broken :(   Not when loading them immediately but when starting over and loading them. )

**Comment by hrydgard** [comment]
Oh, well, skip buffer effects is in the Speedhack category, which means it may work but it can break graphics. This is not fixable.

**Comment by DomDMP** [comment]
I haven't messed around with the settings in ppsspp very much. How would I fix this?
