### ISSUE TITLE
[Feature Request] Limit vertical screenspace used by PPSSPP notification banners

### ISSUE THREAD

**Issue by Abbanon** [hrydgard/ppsspp#19479]
### What should happen

It's far too easy to completely drown out the game screen by spamming actions that bring up PPSSPP notification banners, for example when toggle spamming texture replacement (pictured below).
It would be much better overall if this were limited to 2-3 banners visible at one time, with an optional setting to toggle the appearance of certain notification banners entirely (such as disabling screenshot banners, and/or texture replacement banners, etc.)
Having these options and/or banner appearance limitations would greatly benefit texture pack developers who have to toggle their textures for development and comparison purposes.
![Screenshot_1](https://github.com/user-attachments/assets/6e2dd2a8-a58e-44ed-a083-63cb27b20903)

### Who would this benefit

More or less everyone, but primarily texture pack developers.

### Platform (if relevant)

None

### Games this would be useful in

Everything

### Checklist

- [X] Check the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
There's already a feature to deduplicate the same notifications, we should use that in more places such as this one, to start with.

May also indeed consider a vertical limitation..

**Comment by hrydgard** [comment]
#19485 should make this good enough. Closing.
