### ISSUE TITLE
[Bug Report] PPSSPP System keyboard has "&" shown as "&&"

### ISSUE THREAD

**Issue by Abbanon** [hrydgard/ppsspp#19477]
### Game or games this happens in

n/a

### What area of the game / PPSSPP

Using PPSSPP's system keyboard menu shows that `&` appears as `&&`
This does not impact any game, the issue is only within the system keyboard menu itself.
I have narrowed down the cause to be from Dev build `1.17.1-640-g7547126a7d`. 
The issue is not present in the previous Dev build of `1.17.1-638-g1f7310d4cf`.

![ULJM05500_00000](https://github.com/user-attachments/assets/64742a63-0e6e-410d-99d8-6df66c56aec0)

### What should happen

`&` should appear as `&`, instead of `&&`

### Platform

Windows

### Mobile device model or graphics card (GPU)

GTX 1660 Super

### PPSSPP version affected

1.17.1-640-g7547126a7d, and all builds afterwards

### Last working version

1.17.1-638-g1f7310d4cf

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by sum2012** [comment]
That  mean #19218

**Comment by hrydgard** [comment]
Oops, silly mistake. Will fix.
