### ISSUE TITLE
Love PPSSPP bugs/errors

### ISSUE THREAD

**Issue by Merljn777** [hrydgard/ppsspp#19483]
On patapon3 graphic bugs sometimes and it's BEAUTIFUL ! Doors are only full lights and colors, weapons are half transparent with lights.

Why not going on the other side, add a button to create PPSSPP bugs/errors ?

**Comment by anr2me** [comment]
Probably z/depth buffer issue on the glowing effects, you should create a GE frame dump so it can be fixed, since the bug could also affects other games too (in a weird way).

And not all bugs made the game looked beautiful, sometimes they look weird.

**Comment by hrydgard** [comment]
Screenshot and/or [GE dump](https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump) please, otherwise I'll just close this as it's not actionable.

**Comment by hrydgard** [comment]
No feedback, I'm closing.
