### ISSUE TITLE
unmappable touch controls  

### ISSUE THREAD

**Issue by MadameMalady** [hrydgard/ppsspp#19486]
### Game or games this happens in

None

### What area of the game / PPSSPP

When you go to map the touch controls, you can't map L +R, because the display frame for moving them around doesn't display them, they are probably out of frame i'm guessing.
(please ignore the window frame bar, the app fullscreens fine, just a bug of taking a screenshot on my device.)
![Screenshot from 2024-09-24 21-36-34](https://github.com/user-attachments/assets/12afde40-5091-4896-8a26-50be28efe5ad)

### What should happen

The window for moving the controls around either needs to be made a bit bigger, or the default positions of buttons needs to be shifted to a lower position so they are accessible and in-frame. 

### Platform

Linux / BSD

### Mobile device model or graphics card (GPU)

FD630

### PPSSPP version affected

v1.17.1 (latest arm64 flatpak version)

### Last working version

N.A.

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by MadameMalady** [comment]
Ahh, forgot to add, this is the arm64 flatpak this has been happening for.

**Comment by hrydgard** [comment]
I was able to reproduce this in a small window on a PC using the Reset button. It seems it acts very strangely here! It somehow doesn't take the squashed coordinate system into account.

Going to fix this.

**Comment by hrydgard** [comment]
Alright, committed a quick fix that makes sure that on Reset, no controls are initialized off screen. Should solve your problem.

**Comment by MadameMalady** [comment]
yay! thanks ^~^
