### ISSUE TITLE
Add F-Droid to the downloads page

### ISSUE THREAD

**Issue by licaon-kter** [hrydgard/ppsspp#19518]
### What should happen

here: https://www.ppsspp.org/download/

### Who would this benefit

-

### Platform (if relevant)

Android

### Games this would be useful in

-

### Checklist

- [X] Check the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
What link should I add?

**Comment by licaon-kter** [comment]
moved where it belongs: https://github.com/hrydgard/ppsspp-site/issues/33 thanks
