### ISSUE TITLE
Build number no longer fits on main screen

### ISSUE THREAD

**Issue by NABN00B** [hrydgard/ppsspp#19544]
### What area of the game / PPSSPP

Extremely minor thing and not sure if it's worth fixing, but the build number no longer fits in the upper right corner of the main screen in dev builds.
We should consider decreasing the font size or moving the version string to a new line (for dev builds).
![image](https://github.com/user-attachments/assets/a19c3bfc-9120-43a9-b43d-387db0cf7f9c)

### PPSSPP version affected

dev builds after .x updated/hotfix releases

**Comment by anr2me** [comment]
May be we should right aligned it?

Anyway, since the last part is a hash of the last commit, we can still tells whether it was a modified build or it was from upstream, and still able to search which commit it was even when the hash got truncated.

**Comment by hrydgard** [comment]
I'll fix it up soon. I'll remove the "v" at the start and squish it slightly horizontally, I think.

**Comment by hrydgard** [comment]
Fixed, closing
