### ISSUE TITLE
PlayStation Network Collection: Power Pack: Freeze after showing a brief logo animation

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#19571]
As it says on the tin, tested with UCES01160. Reported by Jack54guy on Discord.

It simply freezes after displaying an animated (sceMpeg) logo.

**Comment by anr2me** [comment]
The game is still running after the video finished, but only shows black screen with around 60~61 FPS
Debug Logs on all channels (followed with redundant patterns of the GE/Display/Kernel-related syscalls):
![image](https://github.com/user-attachments/assets/6b1fcba0-bc4e-47b3-8a8d-0c95610cef18)

Info Logs on all channels (no longer generate any logs):
![image](https://github.com/user-attachments/assets/d9245649-d65d-4909-998f-d794e9307476)

**Comment by sum2012** [comment]
Simulate UMD Delays fix it

**Comment by hrydgard** [comment]
nice find @sum2012 !

**Comment by Jack54guythecoder** [comment]
Also, found a report page for this game> https://report.ppsspp.org/game/UCES01160_1.02

MAYBE it will help? _sort of?_

**Comment by Jack54guythecoder** [comment]
Meaning that it used to work perfectly for one user.
but then something broke it, i guess?

**Comment by hrydgard** [comment]
Maybe, that report could also just be a mis-click, or the user identified the same workaround.

**Comment by hrydgard** [comment]
Wonder if this also applies to PlayStation Network Collection: Puzzle Pack ? 

I'll add compat.ini workaround for now.
