### ISSUE TITLE
Menu freeze upon browsing game directory

### ISSUE THREAD

**Issue by Starman99x** [hrydgard/ppsspp#19584]
### Game or games this happens in

none

### What area of the game / PPSSPP

In the Android version, after 1.18 update, the main menu will freeze upon browsing an SD card directory with psp games in chd format. The directory I tested has only one chd game which is Yu-Gi-Oh Arc-V Tag Force Special. This problem does not happen with the latest PC version, or with versions prior to 1.18 on Android.

### What should happen

It shouldn't freeze.

### Platform

Android

### Mobile device model or graphics card (GPU)

Redmi Note 11

### PPSSPP version affected

v1.18

### Last working version

v1.17.1

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
This is fixed in 1.18.1. sorry for the trouble.
