### ISSUE TITLE
Vulkan , TakeGameScreenshot is not working

### ISSUE THREAD

**Issue by android-1995** [hrydgard/ppsspp#19585]
### Game or games this happens in

None

### What area of the game / PPSSPP

None

### What should happen

When I set the Graphics backend to Vulkan, the screenshot failed. I also tried using Graphics backend with OpenGL, and it worked fine

### Logs

![Screenshot_2024-11-05-15-08-45-804_org ppsspp pps](https://github.com/user-attachments/assets/53b1fae3-b487-4fdc-a6bb-ef6fa8d20d7d)

### Platform

Android

### Mobile device model or graphics card (GPU)

redmi k40

### PPSSPP version affected

1.18.1

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Strange, I just tested it on an Android device and it worked fine (although it displayed the path in an unreadable format, will fix that). And probably we should store the image into the phone's media library instead of PSP/SCREENSHOT.

Anyway, I'll look into it at some point.

**Comment by Bonkistein** [comment]
I'm having the same problem as well.

**Comment by hrydgard** [comment]
That should take care of it.
