### ISSUE TITLE
Some button doesn't work anymore in macOS

### ISSUE THREAD

**Issue by Halo-Michael** [hrydgard/ppsspp#19593]
### Game or games this happens in

-

### What area of the game / PPSSPP

Some button doesn't work anymore in macOS.
Except for the buttons inside the red box, none of them work.
![c4c53a05b202ea461870ba33ee196c77](https://github.com/user-attachments/assets/f56599b3-11ac-43c9-bda8-6aae069fa5bb)
The last build I know works is the first release of 1.18.1.

### What should happen

Button works

### Platform

macOS

### Mobile device model or graphics card (GPU)

6750GRE

### PPSSPP version affected

1.18.1-40-gc9c543

### Last working version

1.18.1

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Oh, oops, I know what this is. Fix coming up.
