### ISSUE TITLE
Kurohyou 2: Ryu Ga Gotoku Ashura-hen: Enemies too fast, softlocking the game in chapter 5

### ISSUE THREAD

**Issue by Deka710** [hrydgard/ppsspp#19597]
### Game or games this happens in

NPJH50562

### What area of the game / PPSSPP

some enemy on the street are running too fast, especially it happen in chapter 5 and prevent you to progress further.

https://github.com/user-attachments/assets/d374ce4e-9aed-43b7-881d-e6f25789c986

its already reported few years ago but idk why it closed while the issue still persist, maybe regression? idk. #5703

### What should happen

the enemy should be slower or atleast equal to our main character like in the first game.

### Logs

.

### Platform

Android

### Mobile device model or graphics card (GPU)

Poco F3

### PPSSPP version affected

1.18

### Last working version

i don't know

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by sum2012** [comment]
same issue with https://github.com/hrydgard/ppsspp/issues/19541
Closing
