### ISSUE TITLE
Taiko no tatsujin portable DX missing text again.

### ISSUE THREAD

**Issue by lim2222** [hrydgard/ppsspp#19678]
### Game or games this happens in

NPJH-50426 Taiko no tatsujin portable DX

### What area of the game

User ID text missing,option text missing too.

### What happens

![Screenshot_2024-11-30-19-12-24-123_org ppsspp ppsspp](https://github.com/user-attachments/assets/ef75d7a8-23a7-4676-a51f-38b4968517a1)
![Screenshot_2024-11-30-19-12-43-913_org ppsspp ppsspp](https://github.com/user-attachments/assets/726f41fd-fd16-494f-a63e-f54a6038c58b)

### What should happen

![Screenshot_2024-11-30-19-11-41-761_org ppsspp ppsspp](https://github.com/user-attachments/assets/c5d54324-413e-465c-89a8-395f0be144f2)
![Screenshot_2024-11-30-19-11-29-955_org ppsspp ppsspp](https://github.com/user-attachments/assets/3e63ea56-bb21-4e82-a6e8-b9b0b491bb5b)

### Platform

Android

### Mobile device model or graphics card (GPU)

Xiaomi 10t

### PPSSPP version affected

ppsspp_v1.18.1-239-g7b0551fa0b.apk

### Last working version

ppsspp_v1.18.1-226-g5077c7ba3f.apk

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
can you get a framedump and upload it? https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

**Comment by lim2222** [comment]
[NPJH50426_0001.zip](https://github.com/user-attachments/files/17965385/NPJH50426_0001.zip)

**Comment by lim2222** [comment]
Report back that ppsspp_v1.18.1-246-gd6b90933f8.apk has fixed this issue.
