### ISSUE TITLE
The emulator is deleting the save files

### ISSUE THREAD

**Issue by DmdHoH000** [hrydgard/ppsspp#19675]
### Game or games this happens in

All Games

### What area of the game / PPSSPP

When I try to delete a save the emulator deletes all saves

https://github.com/user-attachments/assets/9f4a6df4-903a-4b2c-b65e-bb2006cb0992

### What should happen

Deleting using savedata manager works normally

### Platform

Android

### Mobile device model or graphics card (GPU)

Galaxy A14 5G

### PPSSPP version affected

ppsspp_v1.18.1-226-g5077c7ba3f

### Last working version

ppsspp_v1.18.1-209-gb15f7fd9fa

### Graphics backend (3D API)

Other

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Oh that's really not good. I'll fix.

**Comment by hrydgard** [comment]
Hm, I'm testing on the latest, seems to work as expected.. strange. will try on a few phones.

**Comment by hrydgard** [comment]
Hm yes, can repro on Android.
