### ISSUE TITLE
[Feature Request] Possibility of additional hashranges functionality?

### ISSUE THREAD

**Issue by chrisfand** [hrydgard/ppsspp#19714]
### What should happen

The Tag Force games are very popular and I've made several texture packs for them, but there's an issue where garbage data is left in the bottom right section of card images.

reduceHash is not an option as it breaks text rendering due to the game drawing letters one by one from a 512x512 buffer-like image of letters.

hashranges works, but it also ignores the bottom left corner of the card image which I need as it contains part of the card name image.

**My question would be: Would it be possible to specify multiple vertices for a hashrange or perhaps something like an inverted hashrange where I can specify a rectangle in the image to not hash?**

Here is an example of the garbage data in all the cards' bottom right corner.

![08f6029000000607cac0236b](https://github.com/user-attachments/assets/29fa21bd-32ce-464e-b69e-bf085351fdd6)
![08f6029000000607d1cef59c](https://github.com/user-attachments/assets/ed613b68-7bac-4e3d-a933-f0c754f6ecb3)

### Who would this benefit

- Anyone using Tag Force texture packs
- Games where reducehash breaks text rendering
- Games where images contain garbage data

### Platform (if relevant)

None

### Games this would be useful in

Tag Force 1, 2, 3, 4, 5, 6, and Special

### Frame dump

[ULUS10481_0001.zip](https://github.com/user-attachments/files/18075598/ULUS10481_0001.zip)

### Checklist

- [X] Check the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
Implemented the most straightforward workaround in #19717. If needed, we'll expand it with more options in the future, but the issue seems rare.
