### ISSUE TITLE
Type errors in CrossSIMD.h

### ISSUE THREAD

**Issue by hiroyuki177** [hrydgard/ppsspp#19767]
### Platform

Raspberry Pi

### Compiler and build tool versions

Clang 15.0.6 + CMake 3.25.1

### Operating system version

Debian 12 bookworm

### Build commands used

make -j 4

### What happens

Type errors:

1.  in the line Common/Math/CrossSIMD.h:269

```c++
		return Vec4F32{ vcvtq_f32_s32(vmovl_s16(value16)) };

```

2.  in the line Common/Math/CrossSIMD.h:369
```c++
		return Vec4U16{ vmovn_u32(vreinterpretq_u32_s32(v.v)) };
  
```

### PPSSPP version affected

v1.18.1-547-g5def50cca6

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] Make sure to run `git submodule update --init --recursive` before building.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try deleting the build directory and running the build again.
- [ ] Check GitHub Actions, which builds every merge and PR.
- [ ] Include logs and help us reproduce.

**Comment by hrydgard** [comment]
Thanks, I'll fix them. It's annoying that compilers are inconsistent with these checks.
