### ISSUE TITLE
MGS Peace Walker data install doesn't work

### ISSUE THREAD

**Issue by Antonio1994** [hrydgard/ppsspp#2040]
MGS PEACE WALKER DATA INSTALL DOESNT WORK despite the fact it always installs succesfully.Also,everytime a mission finishes,the game doesnt return to the menu,it only gets black screen-infinite loop.

**Comment by unknownbrackets** [comment]
Does this happen anymore?  I think the ndk has been updated.

-[Unknown]

**Comment by ppmeis** [comment]
Tested with latest build. Data installed correctly:
![image](https://cloud.githubusercontent.com/assets/4381277/7019799/fc61bf88-dd13-11e4-99bd-772f9f043253.png)
![image](https://cloud.githubusercontent.com/assets/4381277/7019803/030f076e-dd14-11e4-92e9-79f9305ecf06.png)
![image](https://cloud.githubusercontent.com/assets/4381277/7019807/09253c0e-dd14-11e4-90cc-526fb506687c.png)
![image](https://cloud.githubusercontent.com/assets/4381277/7019810/100d86c0-dd14-11e4-8ab3-260a855cd6a1.png)
![image](https://cloud.githubusercontent.com/assets/4381277/7019830/2e27d944-dd14-11e4-982f-4ab6b80ddb66.png)
![image](https://cloud.githubusercontent.com/assets/4381277/7019833/3bea2988-dd14-11e4-851a-37c8cb257f3a.png)

**Comment by hrydgard** [comment]
Thanks for testing, closing.

**Comment by thedax** [comment]
> Tested with latest build. Data installed correctly:

It was an Android issue from the beginning afaik, so testing Windows doesn't really mean a lot. Anyway, I can't really test the issue anymore, so if it's fixed on Android, that's great.

**Comment by unknownbrackets** [comment]
Well, it's probably fixed considering the NDK update.

-[Unknown]
