### ISSUE TITLE
Missing background : Romance Of Three Kingdom 9 PK 

### ISSUE THREAD

**Issue by raven02** [hrydgard/ppsspp#2159]
This missing background never worked before in any build .Just for record.

![screen00007](https://f.cloud.github.com/assets/3000282/725991/e8368562-e0c0-11e2-924c-138b758cd5fe.jpg)

**Comment by daniel229** [comment]
Still no change in v1.1.1-215-gd2701d7
![11](https://cloud.githubusercontent.com/assets/3481559/10961627/b4cee25e-83cb-11e5-9356-aa9bcfcdebd5.png)

**Comment by unknownbrackets** [comment]
Hrm.  If you save state / load state does it still display something?

When loading state, it loads whatever is in RAM behind the framebuffers.  That's why it implies to me that it has drawn something to RAM and the framebuffers are just black.  But if breakpoints don't trip...

We did fix some missing breakpoint checks, though.  Can you double check if they don't trip now?  Make sure to set the breakpoints before entering the scene, or else pan the view.  It may only redraw when there's a change (possibly...)

-[Unknown]

**Comment by daniel229** [comment]
save state it still displays the same screen,load state it display a blackscreen then the same bug screen. I set speed to 5%.
From entering to the scene,it's drawing the cloud,and than nothing more than later.
![13](https://cloud.githubusercontent.com/assets/3481559/10961932/9b095d1a-83ce-11e5-807e-038d41dbbab9.png)

**Comment by unknownbrackets** [comment]
And no hits on the memory breakpoint either?

Software rendering works right?  Maybe @raven02's savestate was from softgpu and that's why it worked for a second.  Hmm.

-[Unknown]

**Comment by daniel229** [comment]
breakpoint which address?

**Comment by unknownbrackets** [comment]
04000000 with size 0x110000.

-[Unknown]

**Comment by daniel229** [comment]
Not hit.

**Comment by sum2012** [comment]
update the log to v1.1.1-340-g01669cb 
https://gist.github.com/sum2012/0860d89bb54d08dbd39e
@unknownbrackets yes,it need soft gpu for work

**Comment by unknownbrackets** [comment]
I've gotten some GE debugger related info on this.  Dumping my observations from that data here:

Apparently, the game draws everything fine, until some point when it draws something on the framebuffer with blending.  This is when the framebuffer goes black.

This particular draw seems weird.  It seems it's drawing lines using rectangles, but:
 * Texturing is disabled.
 * Vertices include funky UV values.
 * There's an extra rectangle (by accident?) with XY 0,0 - 8000,4000.

The last thing is apparently the kicker.  By hacking it to avoid this last rectangle, the game seems to draw fine.  It's not a block transfer issue at all, then, but instead a clipping one.

On the PSP, per my earlier tests, anything drawn outside the 0,0 - 4096,4096 window coords (translated/scaled via the viewport) gets clipped entirely.  Therefore a draw of 8000,4000 should simply be skipped outright.  It's accidental and incorrect that it's even drawn.

IMHO, this is a bug in the game, though.  Assuming I'm understanding correctly.

-[Unknown]

**Comment by unknownbrackets** [comment]
I expect this to work now - on all backends - now that #11393 is merged.  How's it look now?

-[Unknown]

**Comment by sum2012** [comment]
v1.6.3-497-gead4946fd Win 7 64 bit
Opengl fixed.
Directx 9 fixed.
Directx 11 fixed.

**Comment by unknownbrackets** [comment]
Awesome - I'm going to assume Vulkan is fixed too and close this.  Thanks for verifying.

-[Unknown]
