### ISSUE TITLE
Project Cerberus (J) Weird control glitch and crash

### ISSUE THREAD

**Issue by Arylle** [hrydgard/ppsspp#2182]
Here's an interesting one. Project Cerberus is a fighting game I picked up at a con. On both ppsspp and jpcsp  on the character select screen pushing any directional key  will move the  cursor 1 space in that direction and select the character. After this, It goes into the character versus screen and  freezes  soon afterwards with the logger going crazy. I truncated the log because most of the lines that repeated seemed to be the same. Was just wondering if anyone would look at this issue.

Here's the log: http://pastebin.com/z5q6eLWB
(Sorry for bringing in these strange issues left and right. It just didn't seem like anyone was reporting this stuff)

**Comment by benderscruffy** [comment]
is this still an issue ??

**Comment by sum2012** [comment]
v1.13.1-722-g49d5b6447-windows-amd64 I think o problem
Closing it
![1](https://user-images.githubusercontent.com/2177532/188314442-b9d5b3dd-da6f-4232-bee1-a05d59f121f4.jpg)
