### ISSUE TITLE
Yu-Gi-Oh! 5D's Tag Force 5

### ISSUE THREAD

**Issue by POWERDRAGON6** [hrydgard/ppsspp#2486]
Please ppsspp developers PLEASE, update the compatibility for this game. 
The game IS playable. But

-Audio Sounds horrible and skips.
-Sometimes cards don't show up during the cut scene summons.
-Story mode is unplayable. (After choosing a location the game freezes)
-The frame rate could be better.

Please don't let my donations to you guys go in vain :(. I support you very much. Thank you.

**Comment by ppmeis** [comment]
Tested with latest build. Game works just fine.
