### ISSUE TITLE
Code Lyoko stuck at "No problem screen"

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#2539]
PPSSPP v0.8.1-109
![1](https://f.cloud.github.com/assets/2177532/726648/af1b42b6-e11c-11e2-9dc2-8028ec61b32b.jpg)
It just replay sound voice in the screen

JPCSP also have this probrem.
(and It can solved by disable decode audio by SonicStage)

PPSSPP Debug log:
(I have disabled log in hle\scekerneltime.cpp:67 /DEBUG_LOG(HLE, "sceKernelGetSystemTime(out:%16llx)", t);)

https://docs.google.com/file/d/0B3OaSdeV0L8kclhHR2czaGtuZGM/edit?usp=sharing

**Comment by sum2012** [comment]
Update debug log to v0.9.9.1-1576-g4100163
https://drive.google.com/file/d/0B3OaSdeV0L8kZXVDU21mMTRFdXc/view?usp=sharing

**Comment by metal5621** [comment]
Um, hi there. I just wanted to ask is there something that you can do to fix this problem? I would really love to play this game but it keeps occurring no matter what i try :(

**Comment by sum2012** [comment]
@metal5621 This is hacked version (without sound)
Need this setting
![1](https://cloud.githubusercontent.com/assets/2177532/5838228/e06d34a8-a1c0-11e4-959f-e51d42af6147.jpg)
Windows 32 bit
https://drive.google.com/file/d/0B3OaSdeV0L8kR1BpcURpcHpUNmM/view?usp=sharing
Windows 64 bit
https://drive.google.com/file/d/0B3OaSdeV0L8kcXZ5U25JR0t6Y2s/view?usp=sharing
Android
https://drive.google.com/file/d/0B3OaSdeV0L8kZldMWWt0ai0xeGc/view?usp=sharing

**Comment by metal5621** [comment]
Oh my god, thank you so much, i almost cried. You made one girl's day, sir.

**Comment by sum2012** [comment]
Update the log to v0.9.9.1-1599-g53510f5
https://gist.github.com/sum2012/838230d97693866924dc

**Comment by unknownbrackets** [comment]
Okay, so here's what's happening based on that log:

1. The game (like many others, I think) waits for "remaining frames" in the buffer to hit 0.  This is generally when it needs more data fed to it.

    1.1. Currently, PPSSPP tracks against a larger buffer, even when streaming, and generally gets this number wrong.

    1.2. When PPSSPP has seen all data, it returns -1, not 0, which is incorrect for streaming.  I think it ought to return -2 when not looping, in fact.

2. The game seems to check sceAtracGetStreamDataInfo after remain hits 0, to determine where to read from, which is normal.

    2.1. Since it's looping, this is probably how it can tell when the looping has happened (since remaining frames will hit 0 often and when looping, never be negative)

    2.2. In PPSSPP, the fileoffset never returns to the start when looping, because it still assembles the larger buffer and doesn't need the old data.

I suspect that's what's causing the hang here.

-[Unknown]

**Comment by sum2012** [comment]
@unknownbrackets 
1.2 is wrong,per jpcsptrace log https://gist.github.com/sum2012/341ec200de6b93405ef3
PSP really return 0 not -2 for streaming

**Comment by unknownbrackets** [comment]
As mentioned, I think it does -2 only when not looping.  I was just mentioning things from my testing.  In this case, the game enables looping for no good reason at all.

-[Unknown]

**Comment by sum2012** [comment]
@unknownbrackets ok

**Comment by sum2012** [comment]
I add this log in addition to #8105 in sceAtracGetRemainFrame
	if (atrac->bufferState == ATRAC_STATUS_STREAMED_LOOP_FROM_END)
		NOTICE_LOG(ME, "ATRAC_STATUS_STREAMED_LOOP_FROM_END");
	else if (atrac->bufferState == ATRAC_STATUS_STREAMED_LOOP_WITH_TRAILER)
		NOTICE_LOG(ME, "ATRAC_STATUS_STREAMED_LOOP_WITH_TRAILER");

it log "ATRAC_STATUS_STREAMED_LOOP_FROM_END"

**Comment by sum2012** [comment]
v1.1.1-101-gc14d1f7 full debug log:
(Just in case it is not only atrac case issue)
https://drive.google.com/file/d/0B3OaSdeV0L8kNU9KVEFZOGFtOWs/view?usp=sharing

**Comment by sum2012** [comment]
ppsspp-v1.1.1-223-ga581de7  same problem
log:
https://gist.github.com/sum2012/86f459b4e6cd4803ca03

**Comment by sum2012** [comment]
v1.1.1-240-gb9f703d still same problem
In the sceAtracDecodeData, remain not -1 now,but it the game still don't get signal to stop looping
full log:
https://gist.github.com/sum2012/f8c58e2e836287213494

**Comment by sum2012** [comment]
Compare again JpcspTrace log
Real psp (in this game) do not return "remain 3" in sceAtracDecodeData

**Comment by unknownbrackets** [comment]
That's because `sceAtracGetStreamDataInfo()` is supposed to request 0x438 bytes, but is requesting 0x800.  The remain frame value is correct based on the amount of data, but the amount of data is still incorrect.

-[Unknown]

**Comment by sum2012** [comment]
Update JPCSPTrace log with sceAtracGetRemainFrame 0x9ae849a7 2 xp
https://gist.github.com/sum2012/d9a19dc2abddf0fdc01f

**Comment by daniel229** [comment]
https://github.com/hrydgard/ppsspp/pull/8354 broke this game more,the bgm in other scene is missing.

**Comment by unknownbrackets** [comment]
Hmm.  Could you try an `#define HLE_LOG_FORCE` before and after for just that area (ideally including it loading the background and then playing)?

-[Unknown]

**Comment by daniel229** [comment]
after
https://gist.github.com/daniel229/e0d6ddbe2501f8609155

before
https://gist.github.com/daniel229/e0d6ddbe2501f8609155

**Comment by unknownbrackets** [comment]
Hmm.  What if you try this for `FillPacket()` instead?

```c++
	bool FillPacket() {
		u32 off = getFileOffsetBySample(currentSample);
		if (off + atracBytesPerFrame <= first.size) {
#ifdef USE_FFMPEG
			av_init_packet(packet);
#endif // USE_FFMPEG
			packet->data = data_buf + off;
			packet->size = atracBytesPerFrame;
			packet->pos = off;

			return true;
		} else {
			return false;
		}

		return true;
	}
```

Which might be more correct, I wasn't really sure.

-[Unknown]

**Comment by daniel229** [comment]
That sounds stuttering

**Comment by unknownbrackets** [comment]
Did #8361 fix that?  With #8361 + #8356, is this fixed?

-[Unknown]

**Comment by sum2012** [comment]
#8361 have been merged so that I just download v1.1.1-569-g1a6217b to test
 v1.1.1-569-g1a6217b  still stuck at "No problem screen" 
log:
https://gist.github.com/sum2012/eda3d1d8f3bcfc8cedfb

**Comment by unknownbrackets** [comment]
Okay, but it doesn't have stuttering / missing BGM in the other places?

#8356 isn't merged yet.

-[Unknown]

**Comment by sum2012** [comment]
Doesn't have stuttering / missing BGM
I am testing #8356

**Comment by sum2012** [comment]
Well done @unknownbrackets 
#8356 finally correctly fixed this crazy game
log:
https://gist.github.com/sum2012/97b695ee4f2c8ee5b629

**Comment by thedax** [comment]
Nice to see a two year old issue finally get fixed.

**Comment by LPatamon** [comment]
I say the same. At last we can go past the "no problem" part when starting a new game :D

**Comment by unknownbrackets** [comment]
Yep, it was "no problem" at all.  Okay, sorry.

-[Unknown]

**Comment by punysub** [comment]
can you just say very simple how to fix it,i dont understand what are all you saying to fix this game

**Comment by sum2012** [comment]
@punysub download newest version in http://buildbot.orphis.net/ppsspp/

**Comment by punysub** [comment]
the window become black,whats wrong?

**Comment by sum2012** [comment]
![1](https://cloud.githubusercontent.com/assets/2177532/22403679/d93f605e-e659-11e6-90e0-3c1b67608f39.jpg)

**Comment by sum2012** [comment]
@punysub 
Test on my phone,the screen is total bad,I will open a new issue

**Comment by Adeiyan** [comment]
hi
iam trying to play this game. but I get problem like this. and I try to searching for information in Google.  and this is only one information I can get. 
so...
is there any way to fix this bug? 
iam sorry I don't understand what u all talking about up there. 
can u make video how to fix it?
I want to playing this game. Please help me. 
thanks

**Comment by unknownbrackets** [comment]
Step 1: Update to PPSSPP v1.4.2, or at least v1.2.2 or higher.
Step 2: Play the game.
Step 3: Profit?

https://www.ppsspp.org/downloads.html

-[Unknown]
