### ISSUE TITLE
[Bug iOS] 2D sprites stretch to full screen even when full screen is disabled (Kingdom Hearts Birth by sleep)

### ISSUE THREAD

**Issue by BubblegumBalloon** [hrydgard/ppsspp#2746]
Here is an example of the bug in question:
![image](https://f.cloud.github.com/assets/1458314/779103/08acf0ca-e9c6-11e2-9f26-2d3b414ae700.jpg)

Here is what the game looks like with stretch enabled:
![image](https://f.cloud.github.com/assets/1458314/779124/82c22196-e9c6-11e2-8614-859c889719be.jpg)

The 2D HUD stretches outside of the game, this also applies to other 2D effects in the game. This should not be happening.

It may also be the cause of issues such as intense flickering in Loco Roco, a game which uses primarily 2D sprites.

**Comment by unknownbrackets** [comment]
I'm pretty sure this was a viewport issue.  Since there hasn't been any feedback in quite some time, and we fixed several viewport issues, I'm going to close this.

If it still happens, please comment with more information.

-[Unknown]
