### ISSUE TITLE
Android: Naruto Ultimate Ninja Heroes Black Screen

### ISSUE THREAD

**Issue by adriandennis17** [hrydgard/ppsspp#2748]
Android: doesn't show the game cutscene, doesn't show fight
Replace with blackscreen, lifebar and weapons are visible though Options menu is also blank,

Windows: everything is visible and working except, option menu is blank

Or has missing text, also for some sliding text, 

Working On Screenshots..... Will Update When I Have Them Up

**Comment by livisor** [comment]
Works on both windows and android as reported on forums. Closing
