### ISSUE TITLE
Kingdom Hearts Birth by Sleep Final Mix - Mysterious Figure goes invisible

### ISSUE THREAD

**Issue by gintoki147** [hrydgard/ppsspp#2836]
I'm having a problem.
When Mysterious Figure goes invisible, the screen gets all fucked up. I don't know how to explain it exactly, so here's a video:
http://www.youtube.com/watch?v=cmyETjjuvbM

Mysterious Figure is the guy in the black coat I'm battling with.

**Comment by unknownbrackets** [comment]
There hasn't been any news on this for well over a year.  It's quite possible it's been fixed, but we can't know without feedback.

That being said, it's a popular game, so the absence of complaints is feedback in itself.  So, I'm going to close this issue.  If it does still happen, please provide more info / savedata, and we'll reopen.

-[Unknown]
