### ISSUE TITLE
Allow / disallow / lock Android screen auto rotation / orientation

### ISSUE THREAD

**Issue by keylime-pie** [hrydgard/ppsspp#2898]
I understand why commit g81411a7 (Experimental: Make orientation change possible on Android) would be reverted if it leads to crashes. However, there are other options in PPSSPP that might also lead to crashes but are not removed because they are useful to other users.

I suggest  adding back the option for automatic orientation change as a "developer preview" feature, similar to the New UI that needs to be explicitly enabled for now. This can be done through a check box similar to the following: 

[ ] Enable auto rotate?

Also, I suggest an option for an orientation lock so the orientation won't suddenly change if the device is accidentally tilted. This function can be rolled into the same check box for enabling auto rotation (that is, PPSSPP will retain the orientation that was set before auto rotation is again locked.)

An alternative would be to provide static options for landscape, reverse landscape, portrait, reverse portrait.

**Comment by livisor** [comment]
Please create a new topic if issues persist this one is outdate.Closing

**Comment by FreePPSSPP** [comment]
I noticed that PPSSPP is a best emulator and it helps us to play amazing Android games on PC and vice versa. You can now read more details about [PPSSPP Games Download ](https://freeppsspp.info/ppsspp-games-download/) here it's more helpful for you.
