### ISSUE TITLE
Image issues with Ridge Racer 1 and 2

### ISSUE THREAD

**Issue by hdd60311** [hrydgard/ppsspp#2919]
Testing with 0.8.1-762, graphic issue with Buffered Rendering on is still not fixed, and rearview mirror still doesn't work.

![1](https://f.cloud.github.com/assets/5089290/855805/99db6f6c-f52f-11e2-867f-044edea73fda.jpg)

![2](https://f.cloud.github.com/assets/5089290/855807/9d235a86-f52f-11e2-8580-c505f7517e72.jpg)

**Comment by ppmeis** [comment]
Tested with latest build. Same status.

**Comment by ppmeis** [comment]
Tested in latest build. Same status:
![image](https://cloud.githubusercontent.com/assets/4381277/8891016/51632176-3317-11e5-8744-8055148c5acf.png)

**Comment by unknownbrackets** [comment]
I think the remaining issue here is the digital speedometer.  Since I've debugged that and it's a separate issue, I've created #8509 to separate it out.  The context isn't clear here, and there's a bunch of stuff above for fixed issues.

Closing.

-[Unknown]
