### ISSUE TITLE
 SD Gundam Generation Overworld & some other games can't load Custom BGM

### ISSUE THREAD

**Issue by codename1706** [hrydgard/ppsspp#2929]
To active Custom BGM, some games require to load the Music folder in root. For example, SD Gundam Generation Overworld requires user put mp3 files in memstick:\MUSIC\OVERWORLD.
I'm sorry for posting in wrong place last time.

**Comment by issuer** [comment]
Try enabling the Sound Speed Hack in Audio and see if it fixes it.

**Comment by Saramagrean** [comment]
SD Gundam Generation Overworld with v1.7.5 build 553, CustomBGM can load and playable.
![CustomBGM](https://user-images.githubusercontent.com/26355472/54182701-d3485800-44d4-11e9-8200-a797b8cc9545.png)
.

**Comment by hrydgard** [comment]
I'm gonna close this then.
