### ISSUE TITLE
screen rotation on desktop / windows / pc

### ISSUE THREAD

**Issue by benderscruffy** [hrydgard/ppsspp#297]
a fair few games need the screen to be rotated 90 degree's

**Comment by livisor** [comment]
This feature has been implemented.Closing

**Comment by LunaMoo** [comment]
@livisor was it really? This issue is about desktops, not mobiles(which does have the feature).

**Comment by thedax** [comment]
No it hasn't @livisor. Reopening.

**Comment by sum2012** [comment]
Add a game required it:Star Soldier  (ULJM05026)
![1](https://cloud.githubusercontent.com/assets/2177532/7217452/8d614cbc-e65e-11e4-8818-89e78ff239f5.jpg)

**Comment by sum2012** [comment]
Link to #7738 to let us easy to code.
Of course need fix #7738 first

**Comment by hrydgard** [comment]
#7738 does not really help, but screen rotation isn't hard anyway, just haven't gotten around to doing it. 

Now I did a simple version that works well in buffered rendering. Non-buffered will be much more tricky as we can't just rotate the framebuffer so I might not do it... See #7739

**Comment by unknownbrackets** [comment]
IMHO, screen rotation is a "buffer effect," which is skipped by "skip buffer effects."

So I'm going to close this as it's implemented.

-[Unknown]
