### ISSUE TITLE
Ghostbusters - bad textures

### ISSUE THREAD

**Issue by scraggles80** [hrydgard/ppsspp#3041]
all the developers screens are black but you can hear the music and sound fx
and the intro is a black screen aswell but you can hear the talking and it is in a differant language
changing the frame buffer does nothing 

keeps on printing out 
47:57:000 PSMF control W[HLE]: c:\buildagent\work\acf56f986e98e7c9\core\hle\sceKernel.h:466 Kernel: Wrong object type for 350 (0000015e)
47:57:000 PSMF control E[HLE]: HLE\sceKernelEventFlag.cpp:683 sceKernelReferEventFlagStatus(350, 09f88640): invalid event flag
47:57:011 PSMF control W[HLE]: c:\buildagent\work\acf56f986e98e7c9\core\hle\sceKernel.h:466 Kernel: Wrong object type for 350 (0000015e)
47:57:011 PSMF control E[HLE]: HLE\sceKernelEventFlag.cpp:683 sceKernelReferEventFlagStatus(350, 09f88640): invalid event flag

**Comment by ppmeis** [comment]
Tested with latest build. Same status:

OpenGL
![image](https://cloud.githubusercontent.com/assets/4381277/5994354/e1f03cd2-aa6f-11e4-9725-9b6b1a69673d.png)

D3D
![image](https://cloud.githubusercontent.com/assets/4381277/5994359/13ca3d66-aa70-11e4-99e3-6f2edb65b0fa.png)

SoftGPU works fine:
![image](https://cloud.githubusercontent.com/assets/4381277/5994356/fb5927ce-aa6f-11e4-80b7-950e8bd8f196.png)

**Comment by unknownbrackets** [comment]
Does this still happen in the very latest git build?

-[Unknown]

**Comment by ppmeis** [comment]
@unknownbrackets it works fine now:
![image](https://cloud.githubusercontent.com/assets/4381277/6548170/46b20e8e-c5f0-11e4-99d2-41a861317bf5.png)
![image](https://cloud.githubusercontent.com/assets/4381277/6548172/4d76e636-c5f0-11e4-812b-42f04c60f3b0.png)
![image](https://cloud.githubusercontent.com/assets/4381277/6548173/56cdff26-c5f0-11e4-844e-ea88d6169318.png)
![image](https://cloud.githubusercontent.com/assets/4381277/6548183/74f8e678-c5f0-11e4-88ac-7920146d68cc.png)

**Comment by unknownbrackets** [comment]
Hurray.

-[Unknown]
