### ISSUE TITLE
ios super rebot war z2 graphias error

### ISSUE THREAD

**Issue by zyjyeah** [hrydgard/ppsspp#3051]
ppsspp for ios is always has this error. every is good on pc.
![image](https://f.cloud.github.com/assets/5158752/906796/f9eb4d0e-fcdd-11e2-97fc-d84377dcd554.jpg)
![image](https://f.cloud.github.com/assets/5158752/906797/f9eb1fb4-fcdd-11e2-82d8-6767658bcaa2.jpg)
![image](https://f.cloud.github.com/assets/5158752/906797/f9eb1fb4-fcdd-11e2-82d8-6767658bcaa2.jpg)

**Comment by daniel229** [comment]
Someone said it's fixed in iphone 6 plus,iphone5s still buggy.

**Comment by unknownbrackets** [comment]
PowerVRs in general seem to have problems with precision or math or something.

There may be some things we can't make work on PowerVR, like the texture wrapping thing (which we disabled on PowerVR, and that will break e.g. Wild Arms XF iirc, but what else can you do?  PowerVR can't seem to do it, plain and simple, at least with the drivers we tested.)

Maybe there's some option or way we can write things in a PowerVR specific way, but it'd probably be a good thing to get someone involved who has a deeper understanding of the PowerVR idiosyncrasies.

-[Unknown]

**Comment by unknownbrackets** [comment]
This is basically the same as #1313, but hasn't gotten as much recent feedback, so I'm closing it.

-[Unknown]
