### ISSUE TITLE
(Android) Depth glitch in KHBBS when Buffered rendering

### ISSUE THREAD

**Issue by LinkEP** [hrydgard/ppsspp#3058]
This depth issue was already old and i just got to report it now because I got no time to post it. Anyway, this issue only occurs in Android. My android smartphone is Xperia S and its specifications: Adreno 220 GPU and 1.5GHz Dual core "Scorpion".

Non-buffered rendering shows a correct depth:
![screenshot_2013-08-05-14-18-10](https://f.cloud.github.com/assets/4035774/908737/3d24ed1a-fda5-11e2-9625-610a81f0f96b.png)

Buffered Rendering shows an incorrect depth:
![screenshot_2013-08-05-14-17-55](https://f.cloud.github.com/assets/4035774/908750/8add3e22-fda5-11e2-866b-da3d8f54c12a.png)

**Comment by unknownbrackets** [comment]
Just to be clear, this doesn't happen with buffers disabled, right?

Does this also happen with completely default settings - no speedhacks or etc.?

It may be a situation where it's relying on depth being copied between buffers.  Does this also happen on any GLES3 device?

-[Unknown]

**Comment by LinkEP** [comment]
@unknownbrackets 
sorry late response. I was busy from few months ago.
Wait, I'll try it again... I think I remember I tested w/o any hack options.. but I'll retest again today.

**Comment by LinkEP** [comment]
Back..
I reinstalled with the newest build and it seems the problem was still occuring. Even though I already turn-off the speedup options such as Lazy textures, Retain changed, coord speedhack, etc

**Comment by ofry** [comment]
Just for comment. I have same troubles even in start game Kingdom Hearts: Birth by Sleep Final Mix (ULJM05775).

Screen:
![glitch in start game](https://cloud.githubusercontent.com/assets/11790863/7442745/8111b06e-f126-11e4-99c3-4942a4d749bf.jpg)

**Comment by ofry** [comment]
After all videos in starting game I will see black screen if I switch to unbuffered rendering and turn back to buffered rendering.

This is unbuffered rendering:
![2015-07-06 07 17 11](https://cloud.githubusercontent.com/assets/11790863/8515640/425b4afe-23af-11e5-8d2a-880df304123f.png)

**Comment by ofry** [comment]
Now my issue with buffered rendering has solved after v1.0.1-769-gc4ea4e3

Please test it on Android smartphones...

**Comment by thedax** [comment]
@LinkEP or anyone else experiencing the depth issues: does this still happen in the latest git builds from the buildbot?

**Comment by unknownbrackets** [comment]
I wonder if this could even be the lack of depth blitting?

-[Unknown]

**Comment by ppmeis** [comment]
Tested with latest build. It works fine on my OnePlus Two:
![screenshot_2016-02-03-13-02-35](https://cloud.githubusercontent.com/assets/4381277/12781805/01570556-ca77-11e5-8e14-127faf90a341.png)

**Comment by unknownbrackets** [comment]
Okay, will close.  Can reopen if anyone who was previously experiencing the issue says it's still not working on GLES2 devices.

-[Unknown]
