### ISSUE TITLE
Force Unleashed graphic issues (and speed issue)

### ISSUE THREAD

**Issue by Solohack3r** [hrydgard/ppsspp#3064]
Reporting Star Wars: The Force Unleashed issues.

The game does run amazingly well on the v0.8.1-1076-g7a00891 (and the newer v0.8.1-1081-g73d7f49) build. UNTIL.. you actually try to play a level.

As you can see in the screenshots, the menu has zero issues. Even the pause menu works. It's the actual levels itself, where the graphics are completely messed up. You can basically pan around an empty world, with just the backdrop present. And.. it also has a red overlay.

Hope a solution can be figured out soon. It would be amazing to have this kind of game running on an android tablet.

Tested on a Galaxy Tab 2 7.

![screenshot_2013-08-05-04-19-03](https://f.cloud.github.com/assets/5171414/915041/5309d6d0-fe5a-11e2-87c4-8ebbcab370eb.png)
![screenshot_2013-08-05-04-18-49](https://f.cloud.github.com/assets/5171414/915040/530b4cf4-fe5a-11e2-8676-6ddbabea9f3d.png)
![screenshot_2013-08-05-04-17-22](https://f.cloud.github.com/assets/5171414/915042/530c5a0e-fe5a-11e2-8cf3-157e3d50c2ec.png)
![screenshot_2013-08-05-04-18-22](https://f.cloud.github.com/assets/5171414/915043/530c633c-fe5a-11e2-8311-aa41c21e28c2.png)
![screenshot_2013-08-05-04-18-29](https://f.cloud.github.com/assets/5171414/915045/530f43a4-fe5a-11e2-9bbc-66378277019a.png)
![screenshot_2013-08-05-04-17-48](https://f.cloud.github.com/assets/5171414/915044/530e8950-fe5a-11e2-8844-e2b8abae1754.png)

**Comment by unknownbrackets** [comment]
Hmm, this might be related to PowerVR issues that we recently improved.  But, since there's been no response in almost a year, we have no way to know if it's still an issue or not.

I'm going to close it.  If there's more info, we can reopen it.

-[Unknown]

**Comment by berk-can** [comment]
I fixed issue with starting ppsspp in opengl and sleecting vulkan which requires to restart ppsspp then voila, no red lines

**Comment by 2bndy5** [comment]
I recently ran into this issue about the red lines on windows 10. I was able to solve it by restarting my computer and  setting the render mode to directx11. This issue came up after I had changed the render mode, so it seems that it's caused by some residual data in memory somewhere. FWI, I was able to recreate this behavior with the latest git build as well
