### ISSUE TITLE
Problem in touchscreen control overlay

### ISSUE THREAD

**Issue by Fenrir007** [hrydgard/ppsspp#3112]
Summary: Please make the buttons retain transparency when pressed. Also, please allow us to set transparency to 0 in the menu instead of having to resort to ini modification.

The touchscreen overlay breaks transparency when a button is pressed.

When transparency is set to 15, for example (or 0 directly in the ini file), whenever you press a hardware button, the "button enlarging" animation for the on screen button is triggered, and while in that state, the button will be fully visible, disregarding any transparency you might have set.

This is especially annoying if you use a program such as gamekeyboard to play (Xperia Play users have been using it to get rudimentary touchpad controls working, for example). For that program to work, we need the buttons on screen, but invisible.

Emulator version: v0.8.1-1173-ge03acc4 for android

**Comment by unknownbrackets** [comment]
I'm going to close this since there's been no feedback for a year, and I think that it's essentially resolved.

-[Unknown]
