### ISSUE TITLE
Last Ranker crashes when battle in the Coliseum

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#3122]
disable atreac3+ plugin can "fix" this issue.

savedata
https://docs.google.com/file/d/0BzGZGDfFE68zNUZvdDIxMi1VbEU/edit?usp=sharing

**Comment by hrydgard** [comment]
Still happens?

**Comment by daniel229** [comment]
Yes,it still happens

**Comment by unknownbrackets** [comment]
So, just to be clear, does it still crash, or does it just not loop properly now?

-[Unknown]

**Comment by daniel229** [comment]
Not crash,just stop suddently in certain point of the bgm,not a loop,and sometime not happen.

**Comment by daniel229** [comment]
Still got "Error decoding audio" sometime in v1.0.1-224-g0978500 with default setting,but it won't happen when CPU clock change to 1000.

**Comment by unknownbrackets** [comment]
Is it affected by IO timing method?

-[Unknown]

**Comment by daniel229** [comment]
Yes,it is affected IO timing method.I usually try cpu clock 0 or 1000 with IO timing method fast.1000 always work.Just combined other IO timing method and got this result.

cpu clock 0
```
Fast not work
Host not work
Simulate UMD delays not work
```
cpu clock 1000
```
Fast work
Host work
Simulate UMD delays not work
```
