### ISSUE TITLE
Ys - The Oath in Felghana : texture clamping issue

### ISSUE THREAD

**Issue by raven02** [hrydgard/ppsspp#3196]
Just for record. I have really no idea how those circles below get rendered .Tried disable render-to-texure , alpha/stencil/color test also didn't help ....

Title : Ys - The Oath in Felghana
![screen00013](https://f.cloud.github.com/assets/3000282/977685/7eac3416-06a9-11e3-8855-2780987b591c.jpg)

**Comment by hrydgard** [comment]
This has been reported to happen again, see #8015.
