### ISSUE TITLE
zh_TW issue

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#3223]
It is chinese transation of Multithreaded (experimental)
![1](https://f.cloud.github.com/assets/2177532/982535/f0aff076-07fc-11e3-84a8-35fa87a47bff.jpg)
@hrydgard  please fix this before v0.9 .Thanks

**Comment by unknownbrackets** [comment]
It sounds like our current solution is largely working for zh_TW.  There hasn't been any feedback here for a while, so I'm going to close.

We might still benefit from moving away from the atlas and using freetype or something to render characters using system fonts.  But we have existing issues for those things.

-[Unknown]
