### ISSUE TITLE
Bilinear Filtering and Scanlines Options

### ISSUE THREAD

**Issue by shinra358** [hrydgard/ppsspp#3252]
I would like to request bilinear filter and scanline options because the current filters don't do justice for 2d lettering or whole 2d games. It is either very pixelated or play-doughy with the current shaders.

SFA3 on EPSXE:
http://imageshack.us/a/img812/9866/hbkr.jpg

SFA3 on PPSSPP:
http://img855.imageshack.us/img855/5125/ob08.jpg

See how the first one resembles a psp more than the 2nd while in 1080p resolution?
Please add. Thanks in advance.

**Comment by unknownbrackets** [comment]
We have that feature now, right?  "Screen Scaling Filter".

So, I think this is resolved, closing as such.

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, just didn't remember we had an issue when implementing, I guess.
