### ISSUE TITLE
scePower_469989ad not linked to scePowerSetClockFrequency

### ISSUE THREAD

**Issue by devnoname120** [hrydgard/ppsspp#331]
According to JCPSP:

NID: 0x469989AD
OS = 630

**Comment by benderscruffy01** [comment]
can this stay open ???

**Comment by unknownbrackets** [comment]
As far as I can tell, scePower_469989AD, scePower_EBD177D6, and scePowerSetClockFrequency behave the same way.  Validation, rescheduling, etc. all seem the same.  Tested with and without wlan switch on.

Maybe there's a difference depending on battery status/level, or in how it affects the timing of networking or whether networking is enabled.  Not sure.

We also do reschedule now, although it's not entirely accurate (which I'll be fixing soon.)  Going to close this.

-[Unknown]
