### ISSUE TITLE
Harukanaru Toki no Nakade - Hachiyoshou sound bug

### ISSUE THREAD

**Issue by gooseberry12** [hrydgard/ppsspp#3321]
This is one of those games that crashed on boot a few revisions ago and then ran without text and then crashed again, but I'm happy to report that it now goes in-game and is, if you mute your speakers, rather playable as far as I've tested. (Based on 9.1-15-g1ea0cd0 64 bit) Everything works except the sound, which is incredibly broken. I don't know how to capture sound and I don't know if I can explain it well enough, but it sounds like everything's playing at half speed at the two keys lower than it should be. I run a fairly decent i7 machine, so it's not my computer.

The logs seem to say that the game's asking for a second sound buffer. I have no idea if that's feasible to implement.

![error1](https://f.cloud.github.com/assets/4956767/1008174/29391572-0b1c-11e3-9870-aa47bebe1b1a.png)

A full log is a bit too long for pastebin, so I've uploaded on sendspace here : http://www.sendspace.com/file/kli95i

**Comment by benderscruffy** [comment]
no problem so far
can be closed
