### ISSUE TITLE
Ground/UI texture mixup in Gachitora

### ISSUE THREAD

**Issue by gooseberry12** [hrydgard/ppsspp#3323]
The game now runs with text and I'd say it's playable. But in-game there is a graphical glitch that covers the entire ground and some wall textures with UI elements and background textures which flicker like it hates every epilepsy victim ever. 

What textures got mixed up seems to depend on the rendering mode.

This is the effect we want (sans the jaggies, of course).
![screen1](https://f.cloud.github.com/assets/4956767/1008403/72ae0d3c-0b23-11e3-8c96-b4a814f55cc8.jpg)
![screen2](https://f.cloud.github.com/assets/4956767/1008404/72ae0210-0b23-11e3-8087-cfaecd14ec8d.jpg)

This is buffered rendering. (None-buffered looks the same without the red bits.)
![effect2](https://f.cloud.github.com/assets/4956767/1008294/14f9f730-0b20-11e3-9782-ed78cdc672b8.png)

This is read framebuffer to CPU/GPU. Please note that after reading framebuffer to CPU/GPU, changing it back to buffered rendering doesn't change the output.
![effect3](https://f.cloud.github.com/assets/4956767/1008405/82fcb454-0b23-11e3-8d3c-63f2b45fe03a.png)

This is the log of that particular time.
![effect5](https://f.cloud.github.com/assets/4956767/1008407/9f077328-0b23-11e3-8d64-3e2319bcbf4d.png)

And this is the full log : http://www.sendspace.com/file/mqgx71
I was running around a bit while testing, so the log may be......somewhat overly long. >_> Sorry about that.

**Comment by benderscruffy** [comment]
can be closed
has be fixed
