### ISSUE TITLE
MotorStorm Arctic Edge : game hangs after the sony logo

### ISSUE THREAD

**Issue by hdd60311** [hrydgard/ppsspp#3326]
Test 0.9.1-15, after logo page it got black screen and no response.

log : http://www.mediafire.com/?affmmid58a23vfm

**Comment by ppmeis** [comment]
Tested with latest build. Bloomy still present. But now music in menus are fine. When you enter to the race, all sound stops, just like before.

**Comment by daniel229** [comment]
The shadow in Gedebugger
![04](https://cloud.githubusercontent.com/assets/3481559/5717615/c07c30b4-9b3e-11e4-9f13-9362d9d1a1a3.png)
![05](https://cloud.githubusercontent.com/assets/3481559/5717616/c08294c2-9b3e-11e4-8d49-a1684174c713.png)

**Comment by hrydgard** [comment]
Closing in favor of #7445 as much of this report isn't relevant anymore, but the sound part, also mentioned there, is (and it still seems possible to trigger some hangs, plus overbloom).
