### ISSUE TITLE
Games that still hang or crash trying to play a video

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#3338]
Our video playback is now working pretty well but there are apparently a few edge cases left. Here are the ones I know of that likely have this problem, let's collect them here.

PSMF:

* <a href="http://forums.ppsspp.org/showthread.php?tid=6329">~~Ore no Dungeon~~</a> (PSMF)
* ~~[SBK-09 Superbike World Championship] (http://forums.ppsspp.org/showthread.php?tid=2728&pid=70799#pid70799)~~
* Hysteria Project (#3844)
* ~~Parappa The Rapper (PSMF, 448x240 video)~~
* ~~Crimson Room Reverse~~ (PSMF problem)
http://forums.ppsspp.org/showthread.php?tid=5877&pid=70999#pid70999

MPEG:

* Bust-a-Move Deluxe
* [Star Wars Lethal Alliance] (http://forums.ppsspp.org/showthread.php?tid=1789)
* Marvel Ultimate Alliance 2 (#4324, also uses scePsmf)
* Megaman Maverick Hunter X (#3318, but skippable)
* [Pacman World 3] (http://forums.ppsspp.org/showthread.php?tid=1276&pid=70885#pid70885)
* ~~Street Supremacy (#3342)~~
* ~~[Zero no Kiseki] (http://forums.ppsspp.org/showthread.php?tid=3258&pid=43778#pid43778)  (MPEG)~~
* ~~Motorstorm: Arctic Edge (#3326)~~
* ~~Obscure The Aftermath (#2203) (MPEG)~~
* ~~[Dead Head Fred] (http://forums.ppsspp.org/showthread.php?tid=615&pid=62906) (#5003)~~

Uncategorized:

* ~~UFC Undisputed 2010  (#5112)~~
* ~~Alien vs Predator: Requiem~~ (#4546)
* ~~[Heavens Will (ULJM05186)] (http://forums.ppsspp.org/showthread.php?tid=6002)~~
* ~~The Warriors~~
* ~~[Mai Hime - Senretsu Shin Fuuka Gakuen Gekitoushi] (http://forums.ppsspp.org/showthread.php?tid=5726)~~
* ~~<a href="http://forums.ppsspp.org/showthread.php?tid=643&pid=60123#pid60123">Heroes Phantasia</a>~~
* ~~Ace Combat X2 Joint Assault / [Ace Combat: Joint Assault] (http://forums.ppsspp.org/showthread.php?tid=666&pid=44991#pid44991)~~
* ~~Key of Heaven~~ (stuttering now though)
* ~~Naruto Shippuden Ultimate Ninja Heroes 3~~
* ~~[Final Fantasy IV] (https://github.com/hrydgard/ppsspp/issues/4550)~~
* ~~Lunar: The Silver Star~~
* ~~[World Neverland] (https://github.com/hrydgard/ppsspp/issues/2642)~~
* ~~Valkyrie Profile~~
* ~~TMNT (#3673)~~
* AVATAR _______(video broken).
* MX vs. ATV Reflex______(Game doesn't work).
* Silent_Hill_Shattered_Memories_______(Game doesn't work).
* MediEvilResurrection_______(Sound scraps).

**Comment by unknownbrackets** [comment]
I think we've resolved a large number of these, but some are left.  These are the ones I think are remaining:

Hysteria Project (#3844)
Bust-a-Move Deluxe
Star Wars Lethal Alliance
Megaman Maverick Hunter X (#3318, but skippable)
Pacman World 3 - **I think this is fixed?**
AVATAR _______(video broken).
MX vs. ATV Reflex______(Game doesn't work).
Silent_Hill_Shattered_Memories_______(Game doesn't work).
MediEvilResurrection_______(Sound scraps).

If anyone can confirm if any of these are no longer problems, maybe we should create a new issue indeed.

-[Unknown]

**Comment by daniel229** [comment]
Pacman World 3 and Silent_Hill_Shattered_Memories work fine.

**Comment by unknownbrackets** [comment]
@hrydgard this bug seems to have a lot of participants and a lot of images that make my browser slow on loading.  I'm thinking it might be better to have separate issues for remaining games at this point, and close this - what do you think?

-[Unknown]

**Comment by hrydgard** [comment]
I'm fine with that.

**Comment by unknownbrackets** [comment]
Okay, #8795 created for Bust-A-Move Deluxe - for the others, we don't have much detail, so I've instead reached out in the forum for more current information.  Note that MediEvil already had a note that videos were working.

Closing this.

-[Unknown]

**Comment by ToastedSyrup** [comment]
It's not an issue of handing but apparently the ability to disable media engine helps fix the audio bugs in twisted metal head on where only the special SFX can be heard.
