### ISSUE TITLE
Mytran wars freezes at intro

### ISSUE THREAD

**Issue by Superearth958** [hrydgard/ppsspp#3391]
I didn't find a issue here with this game so sorry if there is already a issue posted for this game.

Freezes at intro

Debug console:
E[HLE]: HLE\sceNet.cpp:170  UNIMPL sceNetInit<poolsize=131072, calloutpri=40, calloutstack=0, netintrpri=40, netintrstack=0>

E[HLE]: HLE\sceNet.cpp:187  UNIMPL scenetAdhocInit<>

E[HLE]: HLE\sceNet.cpp:410 UNIMPL scenetAdhocMatchingInit<00008000>

E[HLE]: HLE\sceKernelThread.cpp:2891 Failed to access deferred info for thread: user_main

E[HLE]: HLE\sceKernelThread.cpp:2891 Failed to access deferred info for thread: user_main

**Comment by ppmeis** [comment]
Tested with latest build. Same status, black screen during autosave option.

**Comment by daniel229** [comment]
Still freezing there,fps indicator locked up, Esc did not work.

**Comment by unknownbrackets** [comment]
Are there still problems here?

-[Unknown]

**Comment by daniel229** [comment]
works fine now.
