### ISSUE TITLE
BackSpace - weird behavior

### ISSUE THREAD

**Issue by vsub** [hrydgard/ppsspp#3396]
I know that the keys is hard codes as "go back" but on 0.9.1-134 x86 is doing two things
1.The key is not set as a pause hotkey but it does bring the ingame menu.
2.Pressing it once while ingame,bring the ingame menu,and pressing it the second time while you are in the ingame menu(not is some sub menu),it quickly resumes the game and shows the menu again...you could say that you can't exit the menu with that key because it's resuming the game and then pause it again on KeyUp
KeyDown - resume
KeyUp - pause

Key Hold - switching extremely fast between the game and the ingame menu

**Comment by unknownbrackets** [comment]
Does this still happen?  I don't think I've ever been able to reproduce.

-[Unknown]

**Comment by vsub** [comment]
Well not exactly...backspace works fine now but there is something else and I don't know if it deserves creating another issue(or if this is how it's supposed to work)

Esc works as "go back" one step from any menu but setting another key to the "Pause" will just bring the game menu and not exit from it when you press the same key again

**Comment by unknownbrackets** [comment]
I believe that's intentional.  In the UI, Esc also means cancel.  Therefore, because it is both pause and cancel, you get this behavior.  A dedicated pause key just pauses.

-[Unknown]
