### ISSUE TITLE
Async sound and blackscreen flashes in background videos (tested with Dj Max 2)

### ISSUE THREAD

**Issue by ppmeis** [hrydgard/ppsspp#3468]
Emulator: PPSSPP
Build: v0.9.1-259-g730f291
Game: Dj Max Portable 2 (ULKS46116)
Bugs: Pink transparency (already reported), async sound, black flashes on background videos.
http://youtu.be/EYxacCerBbY

**Comment by ppmeis** [comment]
Tested with latest build. Pink lines are still visible, but only using higher IR than native. To mitigate this issue, using any texture scaling helps a lot:

10x IR and xBRZ
![image](https://cloud.githubusercontent.com/assets/4381277/8891222/302cd9ac-3321-11e5-8c1b-96903dc5116f.png)

**Comment by unknownbrackets** [comment]
Well, higher resolutions are going to use filtering which makes the color test not work properly.  If you force nearest filtering, is the pink gone at higher IR?

-[Unknown]

**Comment by ppmeis** [comment]
@unknownbrackets yes, pink is gone using nearest (no filter scaling applied):

Nearest 10x IR:
![image](https://cloud.githubusercontent.com/assets/4381277/8891751/7c82d8e2-3335-11e5-9502-7ede9620496a.png)

Linear 10x IR:
![image](https://cloud.githubusercontent.com/assets/4381277/8891752/8bd64c70-3335-11e5-8e06-981e3b860543.png)

**Comment by unknownbrackets** [comment]
So at best we could be detecting this situation and forcing linear filtering off for such textures.  However this is directly at odds with issues like #4405.  We have to pick a poison here.

-[Unknown]

**Comment by ppmeis** [comment]
Tested with latest build. Same issues.

**Comment by hrydgard** [comment]
Most likely, but it's not really fixable on its own. Turn off filtering or run at 1x or live with pink lines.

I guess a compatibility flag that hacked up the color testing in this game could possibly work, but I don't really feel that it's worth it.
