### ISSUE TITLE
Hot Shots Tennis: Get a Grip UCUS98701 - Unimpletended Issue

### ISSUE THREAD

**Issue by Finkelstein** [hrydgard/ppsspp#3581]
Hi all,

Perhaps someone has an idea regarding this "little" but big bug within the game Hot Shots Tennis.

For some reason emulation of the Hot Shots series (Golf & Tennis on PS2 and PSP) appears to be generally not so easy and still the PS2 counterpart is facing alot of issues. That being said, the PSP port is nearly flawless and plays fantastically without any errors up until the end ... this is where the problem starts.

Once the regular storymode is completed and the credits start rolling, the game crashes right at the end of the credits and doesnt save any progress. Since the game "continues" and there is still alot to unlock and play, its not possible to get to that part of the game as the last save brings you back again to where the credits will start.

I attached a screenshot of the debug console right when it crashes. I reckon the 2 red lines are causing this crash. Perhaps anyone has an idea? Much appreciated.

Thanks,
Finkel
![hotshotstennis](https://f.cloud.github.com/assets/5368433/1069664/a897448c-1428-11e3-98ed-7d9b7478b0d0.jpg)

**Comment by unknownbrackets** [comment]
Has this improved?  It definitely may have with scePsmf improvements.

-[Unknown]

**Comment by ppmeis** [comment]
I think it's fixed. At least if I replay the credits it works:

![image](https://cloud.githubusercontent.com/assets/4381277/5822195/203f4d2c-a0d2-11e4-932d-b8b361c5d4ee.png)

**Comment by unknownbrackets** [comment]
Cool, I'll close this then.  If it's still happening with some method of reproduction steps, we can reopen.

-[Unknown]
