### ISSUE TITLE
Layering issues in Puyo Puyo Fever 2 (Windows x64 Build)

### ISSUE THREAD

**Issue by internetakias** [hrydgard/ppsspp#3663]
In PPF2, the layering is messed up when the renderer is set to OpenGL. Resulting in all the game objects besides the background being invisible. That is, util you wait long enough in the title screen for the demo puyo match to begin, then the game fixes itself for some reason.
Here are the display lists, one taken in the opening before a match and one taken after
https://gist.github.com/internetakias/6471825
As for screenshots, you can refer to this thread(Despite the big gap between the current version and the version used to take the screens, the bug remains the same): http://forums.ppsspp.org/showthread.php?tid=3858

**Comment by internetakias** [comment]
Not sure if this is even worth mentioning but the Dpeth range hack for PSP2 doesn't seem to work for this game.

**Comment by ppmeis** [comment]
Tested with latest build. Same status:
![image](https://cloud.githubusercontent.com/assets/4381277/8891349/079cd60e-3326-11e5-8e04-c458cfd74837.png)

**Comment by daniel229** [comment]
Fixed in #7920
