### ISSUE TITLE
prince of persia rival sword (black screen in game)

### ISSUE THREAD

**Issue by brujo5** [hrydgard/ppsspp#3723]
pop rival sword (black screen in game) android

tested in ppsspp-v0.9.1-752-g2745744-android

log file
http://www.sendspace.com/file/g9eyy1

thx

**Comment by ppmeis** [comment]
Tested with latest build. No blackscreen here under PowerVR:
![screenshot_2015-07-25-23-17-55](https://cloud.githubusercontent.com/assets/4381277/8891309/727d28b8-3324-11e5-9ec9-8ac5e88e4bbe.jpg)
![screenshot_2015-07-25-23-22-57](https://cloud.githubusercontent.com/assets/4381277/8891310/768d278c-3324-11e5-8543-854d935208b6.jpg)
![screenshot_2015-07-25-23-24-03](https://cloud.githubusercontent.com/assets/4381277/8891311/79a7f820-3324-11e5-9a66-d2f9bd95379f.jpg)

**Comment by hrydgard** [comment]
PowerVR driver quality seems to vary a lot, what works on my Nexus S doesn't work on my Intel and vice versa. A pain.

**Comment by ppmeis** [comment]
@hrydgard mine is an Asus Zenfone 2 with latest intel, It has a powerfull GPU but I think drivers are very bad...in all PowerVR in general.

Thanks @hrydgard

**Comment by brujo5** [comment]
my problem is like this http://tinypic.com/player.php?v=k9ud0o%3E&s=8#.VbRHprVezGs

**Comment by unknownbrackets** [comment]
Is this different in some useful way from #6399?

-[Unknown]

**Comment by ayusidrb** [comment]
Nexus 5x adreno 418 qualcomm snapdragon 808 1.44 ghz
Total black screen tried many settings, 
Yellow screen at default settings.

**Comment by leopard20** [comment]
In Snapdragon 821 the screen is yellow instead of black. (OpenGL)
However, switching to Vulkan fixes the issue. The game is playable @30 FPS at default settings except rendering resolution set to Auto 1:1 (FullHD)

**Comment by leopard20** [comment]
@hrydgard This issue can be closed now
