### ISSUE TITLE
"Low Latency Audio timing" causes audio too early

### ISSUE THREAD

**Issue by LinkEP** [hrydgard/ppsspp#3731]
I just accidentally use the "Low Latency" under Audio option.
Game tested: Project DIVA extend,
and played a song called "StargazeR" then at the middle of the rhythm game the audio was being too early, and so the rhythm game is not synchronized.

**Comment by unknownbrackets** [comment]
Since this option is now gone (replaced by new, better audio mixing), I'm going to close it.  If the new code has any issues, please create a separate issue (or search in case someone else already has.)

-[Unknown]
