### ISSUE TITLE
Left stick

### ISSUE THREAD

**Issue by sasha6282** [hrydgard/ppsspp#3745]
I often I miss a finger in a circle and push very close but it does not work. It may be necessary to do so to the touch near the left stick it worked how to play on Android. This idea applies only left stick. 
Sorry for my English. It's hard to describe it in a different language.

**Comment by ppmeis** [comment]
@hrydgard is this fixed?

**Comment by hrydgard** [comment]
There's a new option called auto centering, which moves the analog stick to where you pressed down. Makes some games easier to play.

**Comment by ppmeis** [comment]
So it could be closed I guess...Thanks @hrydgard
