### ISSUE TITLE
Dante Inferno blank level (Glutonny)

### ISSUE THREAD

**Issue by Demevil** [hrydgard/ppsspp#3788]
![01](https://f.cloud.github.com/assets/4152456/1145819/77055fc8-1e30-11e3-8b56-13138f4b02e0.png)
plzz fix
p
![02](https://f.cloud.github.com/assets/4152456/1145822/a5cf9c56-1e30-11e3-8c2e-cfd4ca2d483e.png)
please fixed game "dante's inferno" on Gluttony after fighting this enemy! were seen only black fully ...

test on laptop
: asus A45V

plz fix on android
prince of persia revelation test ppsspp
http://m.youtube.com/watch?v=j8tKLp_Hl4E
The 3rd Birthday Test PPSSPP
http://m.youtube.com/watch?v=qct8MHCSMS4

test on samsung galaxy sII GT-I9100

**Comment by unknownbrackets** [comment]
Since we haven't gotten feedback in quite some time (over a year), I'm guessing it's probably fixed.  If it's not, it could be it's been fixed and broken by something else since or anything.

If you're still experiencing this, please provide more detail in a commentm and we can reopen.

-[Unknown]
