### ISSUE TITLE
Audio problems with the hysteria project 1 and 2

### ISSUE THREAD

**Issue by pisti094** [hrydgard/ppsspp#3844]
Problems with the hysteria project psp game  the game load and start perfectly but  then game begin  the ppsspp show black screen  pls fix the problem

**Comment by unknownbrackets** [comment]
Apparently, this hack fixes the audio in the Last Promise Story video:

Core/HW/SimpleAudioDec.cpp, from:
```c++
	codecCtx_->channels = channels_;
	codecCtx_->channel_layout = channels_ == 2 ? AV_CH_LAYOUT_STEREO : AV_CH_LAYOUT_MONO;
	codecCtx_->sample_rate = sample_rate_;
```

To:
```c++
	codecCtx_->channels = 1;
	codecCtx_->channel_layout = AV_CH_LAYOUT_MONO;
	codecCtx_->sample_rate = sample_rate_ * 2;
```

This might mean we're not demuxing this properly or something (maybe our frame size is wrong?  or maybe it's actually mono or something?), not really sure.  It sounds like the channels are 2/STEREO by default and the sample rate is 44100 (so this sets it to 88200.)  Seems questionable, anyway...

If you extract the video and play it with this patch (not sure if you have a build with it?):
https://lists.ffmpeg.org/pipermail/ffmpeg-devel/2014-December/166169.html

Does it play correctly?  I know it's a pain to build ffmpeg/ffplay so if you don't already have it maybe we can find some other way.

Also, does such a thing help Hysteria Project?

-[Unknown]

**Comment by daniel229** [comment]
I had built ffplay with that patch long time ago and it play the sound.That hack also help Hysteria Project.

But not help Prince Of Persia Revelations
```
user_main    I[ME]: HW\MediaEngine.cpp:85 FF: Frame data doesn't match channel configuration!
user_main    E[ME]: HW\SimpleAudioDec.cpp:201 Error decoding Audio frame (744 bytes): -1094995529 (bebbb1b7)
user_main    E[ME]: HW\MediaEngine.cpp:803 Audio (AT3+) decode failed during video playback
```

**Comment by daniel229** [comment]
hysteria project 1 in ffplay
```
ffplay version N-68259-g7cdc997 Copyright (c) 2003-2014 the FFmpeg developers
  built on Dec  6 2014 20:25:24 with gcc 4.9.2 (GCC)
  configuration: --enable-gpl --enable-static --disable-shared
  libavutil      54. 15.100 / 54. 15.100
  libavcodec     56. 14.100 / 56. 14.100
  libavformat    56. 15.102 / 56. 15.102
  libavdevice    56.  3.100 / 56.  3.100
  libavfilter     5.  2.103 /  5.  2.103
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
Input #0, mpeg, from 'Z:\1.pmf':   0KB vq=    0KB sq=    0B f=0/0
  Duration: 00:00:42.17, start: 0.945211, bitrate: 393 kb/s
    Stream #0:0[0x1e0]: Video: h264 (Main), yuv420p(tv, smpte170m), 480x272 [SA
 1:1 DAR 30:17], 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
    Stream #0:1[0x1bd0]: Audio: atrac3p, 44100 Hz, mono, fltp, 33 kb/s
  19.53 A-V: -0.051 fd=  27 aq=    1KB vq=  403KB sq=    0B f=0/0
```

**Comment by unknownbrackets** [comment]
Interesting, it states that both are actually mono.  So, one way or another, we are misdetecting the audio.  This isn't shocking, since we always assume videos have stereo audio from what I can tell?

But, I wonder why the doubling of the sample rate is necessary then.  Maybe just that we demux mono incorrectly.

Prince of Persia - is it broken as well, without any hack?  Definitely that hack is not "right".  If it's also currently broken, what does ffplay say about it?  Is it also mono?

-[Unknown]

**Comment by daniel229** [comment]
JPCSP also think it's mono,some tool also tell it's mono. I think it's mono.
Prince of Persia is always broken.

**Comment by hrydgard** [comment]
Did #8472 help?

**Comment by daniel229** [comment]
Yes,it did.

**Comment by unknownbrackets** [comment]
How about Prince Of Persia Revelations?  Or is that a separate issue?

-[Unknown]

**Comment by daniel229** [comment]
Prince Of Persia Revelations the video sound is fixed, but the atrac has issue.

**Comment by unknownbrackets** [comment]
Darn, I guess we should create a new issue?  I suppose it's probably new since v1.1.1?

-[Unknown]

**Comment by daniel229** [comment]
Oh,no,the Prince Of Persia Revelations is still same as before,both video sound and the ingame sound have problem.
