### ISSUE TITLE
Tekken 6 stays on blackscreen if CPU is set to anything else than default.

### ISSUE THREAD

**Issue by VIRGINKLM** [hrydgard/ppsspp#3958]
I'm pretty sure that's not normal since on a real PSP it actually works if you over/underclock your CPU.
Log console gets violated by:
user_main    I[HLE]: HLE\scePower.cpp:382 501=scePowerGetPllClockFrequencyInt()

**Comment by Jinzombie** [comment]
I use this cheat code when I set the Emulated CPU ClockSpeed of Tekken 6 to 111Mhz=30fps lock but some animation/special effects is missing.

_C1 Custom CPU speed freeze-fix
_L 0xE0030004 0x001C6094
_L 0x201C6094 0x00000000
_L 0x201CFC28 0x00000000
_L 0x201CFE74 0x00000000
_C0 Custom CPU speed freeze [Default]
_L 0xE0030000 0x001C6094
_L 0x201C6094 0x10400004
_L 0x201CFC28 0x1443FFF5
_L 0x201CFE74 0x1443FFF5

**Comment by Panderner** [comment]
Note: Tekken 6 uses 333mhz, when I changed the CPU clock speed to 333 it won't work but when I change the CPU clock speed to 222mhz it works.

**Comment by ResurrectionRedmi9** [comment]
This should be listed here https://github.com/hrydgard/ppsspp/issues/13503

**Comment by Gamemulatorer** [comment]
> This should be listed here #13503

Or probably here https://github.com/hrydgard/ppsspp/issues/12811

**Comment by hrydgard** [comment]
Not really planning to do anything about this, except possibly blocking overclocking entirely for these games.
