### ISSUE TITLE
Suggest different decompressing programs based on operating system

### ISSUE THREAD

**Issue by carlosliam** [hrydgard/ppsspp#3982]
i.e. "try iFile or FileApp" for iOS devices, "try double-clicking file in Finder" on Macs, "try opening in a file manager" for Android devices.

**Comment by unknownbrackets** [comment]
Has this continued to be a major concern in email?

-[Unknown]

**Comment by Hydroque** [comment]
Most users install 7zip. You don't need a license to scan for a applicable program.

**Comment by unknownbrackets** [comment]
This hasn't gotten much attention for a while.  Should we close?

-[Unknown]
