### ISSUE TITLE
Graphical artifact in Phantom Brave (depth testing)

### ISSUE THREAD

**Issue by i30817** [hrydgard/ppsspp#4064]
![error](https://f.cloud.github.com/assets/757900/1278050/cd5cb6f2-2ef5-11e3-8402-f0877bd39108.png)

The sword draw order is wrong. Here is a savestate just before the cutscene (just confirm the attack and don't skip the cutscene when asked)

edit: replaced megafileupload link by google drive for permanence
https://drive.google.com/file/d/0BzxkBmaf1EiWSjc3QXpOelp3RXc/edit?usp=sharing

**Comment by daniel229** [comment]
Is this fixed in the latest build?I don't have a save for testing.

**Comment by thedax** [comment]
@i30817: Can you please tell us if this is fixed, or still an outstanding issue? I'm updating the depth issue and would like to know as well, thanks.

**Comment by i30817** [comment]
Unfortunately neither do i have a save anymore and the savestate doesn't load anymore, so checking this is quite impossible without replaying.
Even loading the old savestate and saving and then forwarding wouldn't help because the savestate is naturally before the end of the mission, where you can't save and the cutscene immediately comes after.

**Comment by unknownbrackets** [comment]
Here's a savestate:
https://drive.google.com/file/d/0B-yqKBEmUmsPbUdmdzk5UnlsM2M/view?usp=sharing

It seems like it works now.

-[Unknown]

**Comment by daniel229** [comment]
Yeah,Looks fine.
