### ISSUE TITLE
Discussion: Audio artefacts on Windows

### ISSUE THREAD

**Issue by bollu** [hrydgard/ppsspp#4075]
I think I figured out why audio was severely distorted on Windows. 

Before, when there was a recursive mutex, both ``` __AudioMix()``` as well as ```__AudioUpdate()``` would __always__ have access to the sound buffer - hence they would always fill it up with valid data.

When atomic locks were used, the buffers were written with 0's to indicate that no sound should be played. However, the [SDL_AudioSpec documentation](http://wiki.libsdl.org/SDL_AudioSpec) states: 

__1__ ```silence```: audio buffer ```silence``` value (calculated)
__2__ The value silence is calculated by ```SDL_OpenAudioDevice()```.
__3__ If there is nothing to play, the callback should fill the buffer with ```silence```. 

So, filling the buffer with zeroes was wrong. The buffer should have been filled with ```silence``` (whatever value that might have been initialized to by  ```SDL_OpenAudioDevice```).

Of course, if the value of silence is zero, then the hypothesis fails. But I strongly suspect that this is not the case. If the silence value was not zero, then it would obviously play noise (instead of not playing any sound at all). 

If the value of ```silence``` is not zero, then the atomic code can be rewritten so that the value of ```silence``` is passed into NativeApp. It can then write ```silence``` into the audio buffer rather than writing 0 into the buffer.

Unfortunately, I don't own a windows device (I have Ubuntu and android, and non-jailbroken iOS). So if someone could check this, It'd be a great help.

Thanks!

**Comment by unknownbrackets** [comment]
I think this is taken care of by #7317.  If there are things we should do for other platforms (like Linux or iOS), I think those should be considered separately and issues should be created if there's a clear path to improve them.  This was pretty much about Windows anyway.

-[Unknown]
