### ISSUE TITLE
Remaining lighting issues

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#4140]
Bugs probably caused by something wrong with our lighting equations (possibly edge cases, NaNs, whatnot):
- ~~Strong yellow light in Fired Up~~
- ~~Fish with the wrong color in Monster Hunter (reported in forums), also some pointer arrows  (FIXED)~~
- ~~Overly strong light in Virtua Tennis~~
- Black arms and legs in NBA Live 06 (also #4109)
- ~~Unexpected blue and banding in Blade Dancer ([ULUS10124_0001.zip](https://github.com/hrydgard/ppsspp/files/2320924/ULUS10124_0002.zip))~~

**Comment by unknownbrackets** [comment]
Does the GE debugger show anything when it's drawing the areas that are too bright?

-[Unknown]

**Comment by ppmeis** [comment]
@unknownbrackets here you have:
![image](https://cloud.githubusercontent.com/assets/4381277/6453468/87ce1806-c13e-11e4-98fd-4c18791c3571.png)
![image](https://cloud.githubusercontent.com/assets/4381277/6453471/8d718f04-c13e-11e4-922a-cb5e94ad48bc.png)

![image](https://cloud.githubusercontent.com/assets/4381277/6453459/6c5aedec-c13e-11e4-90ad-e4c841d0a66f.png)
![image](https://cloud.githubusercontent.com/assets/4381277/6453463/7619263c-c13e-11e4-8942-25116c09594e.png)

**Comment by unknownbrackets** [comment]
It's using color doubling but the texture already looks reasonable imho.  Unless we're doubling incorrectly (I don't think we are), not sure.  Though, it's using a texture level bias.  Does the other texture level look different, other than smaller?  e.g. is it darker?

-[Unknown]

**Comment by ppmeis** [comment]
@unknownbrackets no, other texture levels look the same color and brightness.

**Comment by unknownbrackets** [comment]
If you change "Light 0 enable" (by double clicking) to off right when it's sitting with the face highlighted in red, and then click "Step Draw", does it make it darker, or is it the same?

-[Unknown]

**Comment by unknownbrackets** [comment]
It would be interesting if these issues reproduce now in softgpu (especially starting from the beginning.)  If it's an issue of RAM not being updated somewhere, i.e. stencil or depth or w/e, then softgpu may handle it more correctly.

-[Unknown]

**Comment by hrydgard** [comment]
Apart from some black pixels (rounding issues) Virtua Tennis looks fine in the software renderer.

![tennis](https://cloud.githubusercontent.com/assets/130929/26101820/cbd4097e-3a32-11e7-8a73-af1adf1f5844.JPG)

It's actually really strange that this is still buggy in the hardware renderer... i wonder what it could be.

By the way I'm going to turn off the "slow" warning in the software renderer :)

**Comment by unknownbrackets** [comment]
Well, frameskip does still help in softgpu, but sure, heh.

-[Unknown]

**Comment by unknownbrackets** [comment]
Blade Dancer also has an issue - both in softgpu and GLES.

![ulus10124_00000](https://cloud.githubusercontent.com/assets/191233/26530806/ff2a0154-4390-11e7-9604-387be3620cf5.png)

Also, double-checked that this wasn't somehow a bug in the real game.  A few notes:
 * Incorrect blue is added by light 1.
 * Using flat shading (but gouraud shading looks wrong too.)
 * It's using separate specular colors (but doesn't matter either way.)

It uses the same lighting parameters for basically the entire scene.  Probably the lighting parameters are being calculated too close?

-[Unknown]

**Comment by hrydgard** [comment]
What's incorrect in the screenshot? The dark triangle? 

What do you mean by "calculated too close"? Sorry :)

**Comment by unknownbrackets** [comment]
Yes, the blue triangle is wrong.  It shouldn't be there at all.  Note that the same blue is darkening things like the steps, the walkway, the wall, etc.  The amount of blue is correct on those things.

-[Unknown]

**Comment by hrydgard** [comment]
Could always be some inf or nan interpreted differently than the PSP, but that's just speculation...

**Comment by unknownbrackets** [comment]
Here's all the tabs when it draws it (PRIM_TRIANGLE_STRIP):
https://gist.github.com/unknownbrackets/8f98e0511e1991932b21ef2cf565d974

Disabling the light 1 flag for only this draw makes it look approximately correct (but other things look wrong unless light 1 is manually re-enabled before continuing drawing.)  I don't see any inf/nans, but maybe it's guardband related or something...

-[Unknown]

**Comment by unknownbrackets** [comment]
See [ULUS10124_0001.zip](https://github.com/hrydgard/ppsspp/files/1151392/ULUS10124_0001.zip) for a dump of the Blade Dancer lighting issue.  Will also add to the issue description.

-[Unknown]

**Comment by marosis** [comment]
This issue have maybe Flat Out Head on too.

**Comment by unknownbrackets** [comment]
An interesting finding, the Blade Dancer bug doesn't happen in OpenGL in game... but it does happen from the dump.  This makes me think it's an alignment issue or something.

-[Unknown]

**Comment by hrydgard** [comment]
[vtennis.zip](https://github.com/hrydgard/ppsspp/files/2594174/vtennis.zip)

Virtua Tennis still has problems, so here's a couple of frame dumps. In the first one (03), the character lighting is normal. In the second one (04), the lighting is wrong and too bright. 

The change to the bad lighting happens when you hit X to start a ball strike, which shows the little meter. Presumably it sets some state that the rest of the drawing shouldn't care about but somehow does...

**Comment by unknownbrackets** [comment]
Texture for overly bright person: 0x04105720

For reference, the correct image for that frame:
![ules00126_ 4140_virtua_tennis_lighting](https://user-images.githubusercontent.com/191233/48711382-00889780-ebc0-11e8-9907-bf40dfac7488.png)

And the incorrect:
![virtua tennis wrong](https://user-images.githubusercontent.com/191233/48711397-067e7880-ebc0-11e8-852a-120e78e7e644.png)

Interestingly, softgpu also gets the lighting wrong and the shadows even worse.  It also has an easy to fix bug breaking clearing, which I'll fix soon.  What's interesting is: it used to work in the software renderer.  This implies it's not a state thing.

If I disable light 0 (the only enabled light), the characters are too dark.  This light uses powered diffuse + spec.  If I remove specular from the equation, it looks right.

The shadow uses color doubling + standard blend, and the same lighting parameters.  It also looks correct without specular.  Curiously, softgpu loses the shadow after the first frame.

The check from #8403 doesn't help.  Also, because getMaterialSpecularCoef is 1.0, pow doesn't really matter.

It's not possible that mode 2 is powered diffuse only, and not specular, is it?  Hm.

-[Unknown]

**Comment by unknownbrackets** [comment]
Hardware tests so far indicate that mode 2 is powered diffuse only, no specular.  Also makes this dump look perfect, except in softgpu (still not sure what's causing the shadow to evaporate after the first frame - it's drawn briefly... so weird.)

I'm seeing some other possible differences though.  For example, lightdir = (0, 0, 0) seems to normalize to (0, 0, 1) for spot lights, and a clamping issue for spot lightScale.

It also seems like lighting is generally rounding down, not up, but that's a fairly minor accuracy issue...

Need to check more and see how games react to this, but later.

-[Unknown]

**Comment by unknownbrackets** [comment]
Yeah - many of the tests I'm running are giving me colors that are off by one, e.g. `00471d1d` instead of `00461d1d` (diffuse.)  I'm running these tests with no texturing at all, actually.

Didn't create a test yet to confirm specular during diffuse + specular, still more to test...

-[Unknown]

**Comment by hrydgard** [comment]
Confirming that Virtua Tennis looks good now. For the record, it was the no-specular-during-powered-diffuse.

**Comment by ppmeis** [comment]
Tested with latest build. Now lightning seems to be fine, but now start menu has disappeared in some backends:

Vulkan:
![image](https://user-images.githubusercontent.com/4381277/48925041-d127a280-eebf-11e8-86bc-a8e632ed7056.png)

OpenGL seems to be fine:
![image](https://user-images.githubusercontent.com/4381277/48925061-f74d4280-eebf-11e8-846c-e3c81d5aa39e.png)

Direct3D9:
![image](https://user-images.githubusercontent.com/4381277/48925074-0d5b0300-eec0-11e8-864a-ea3808a6a581.png)

Direct3D11:
![image](https://user-images.githubusercontent.com/4381277/48925080-25cb1d80-eec0-11e8-844d-c53532f876f6.png)

**Comment by unknownbrackets** [comment]
Near texture 0x08973d00 + several draws to VAIDISOVA.  I think that's a separate issue related to depth.

It draws verts with a crazy high Z, depth clamp, and standard minz/maxz.  It uses `src >= depth` test.  This passes and it draws the BG and clamped depth.  Lighting is disabled.  Alpha test and blend, but 8c alpha sent.

Not clear what should be keeping it from drawing... it doesn't draw on a PSP running the same dump...

Should open a separate issue, since lighting is disabled.

-[Unknown]

**Comment by hrydgard** [comment]
As I don't think NBA Live 06 (#4109) is a lighting problem, I'm gonna close this. If we discover more lighting-related problems, let's open new game-specific issues.
