### ISSUE TITLE
Discussing Breakpoint improvements

### ISSUE THREAD

**Issue by mchubby** [hrydgard/ppsspp#4158]
PPSSPP has made huge leaps recently in the debugging department thanks to great contributions by @Kingcom and @unknownbrackets (#2584, #3366).

I'm opening this meta-issue to discuss what improvements could be made to make it even _awesomer_.
- What is your use case of bps, mem bps, ge bps?
- What feels the most usable, or conversely needs rework?

Feel free to input your opinion below.

Here is the current state of the Breakpoint Window:

> ![Breakpoint Dialog](http://i.imgur.com/XEqRnIO.png)
#1 - Improvements to breakpoints (logging, etc.)

Log breakpoints are not a specific type of breakpoint, rather it is a breakpoint which **triggers an action**, which is logging an expression.
They offer the choice to **not enter debug mode** when hit.

Let's review what options are offered in other debuggers:
- OllyDbg 1.x:
  OllyDbg offers to execute diverse actions depending on whether a condition is fulfilled, etc. It can also cast the logged expression to a struct/string/etc. pointer for proper display.

![Log bp in OllyDbg 1](http://i.imgur.com/yNcHGDO.png)
- OllyDbg 2.x:
  OllyDbg  goes a bit further, removes support for plugin (temp?) and is able to log several expressions

![Log bp in OllyDbg 2 ss1](http://i.imgur.com/C4GiUdl.png)
![Log bp in OllyDbg 2 ss2](http://i.imgur.com/gAAmoaf.png)
- Visual Studio:
  VS has more basic logging, but being a source-based debugger, can support symbols as well.

![Log bp in VS2010 ss1](http://i.imgur.com/jhYePuB.png)
![Log bp in VS2010 ss2](http://i.imgur.com/WdZoTRl.png)
### Actions
- Add a textedit for an expression. When bp is hit & conditions are met (in pseudo-language)

`if bp.expr.valid(): log(expr.eval(currMIPS))`
- Add a checkbox to continue execution
- Take screenshot on bp?
#2 - Enhancements to memory view
- Have the memory view set viewport at a particular expression (e.g. a1+4) when bp is hit
- Keep navigation stack so you can return to a previous location instead of typing it again.
- Right-click on location => in contextual menu, offer option to **set or modify a memory bp** / dump with this location as base address / **highlight** (change background color)
- location under cursor to be interpreted with **base conversion** (8-bit, 16-bit, 32-bit). Detect if it is an address pointing to a code / variable section
- select range (mouse selection or R-click, select x bytes from here) and ability to **copy / dump selection**, may be useful for tile extractors? Offer **inline string decoding** options (e.g. display converted SJIS)
- Enable more interactions with the symbols list?
### Actions
- Add a textedit for an expression. When bp is hit & conditions are met, update memory view
# Mockup

![mockup](http://i.imgur.com/VJBi6ga.png)
# Other improvements
- Auto-load (auto-save?) Map symbols
- Remember bps when emulator is restarted
- Label breakpoints / comment field?
- how to handle memory bps when a system library writes into a buffer? (no break currently)

Sorry if it looks like a wishlist of mine... Also, I do not use the Ge debugger so can't comment on it.

**Comment by unknownbrackets** [comment]
Log messages now exist - and now that we have a debugger API (#10909), a lot of these features could be automated via API client for specific use cases - which I think is more powerful.

We also do now have a navigation stack (so does the web debugger UI already.)

I'm going to close this - we can open specific issues for specific improvements.

-[Unknown]
