### ISSUE TITLE
(Android) Disabling Vertex Cache makes the certain character's textures into Psychedelic in Project DIVA 2nd/extend

### ISSUE THREAD

**Issue by LinkEP** [hrydgard/ppsspp#4199]
UPDATE (10-16-2013):
The graphic issue disappears when I...
Option 1.) Disabled Hardware Transform
Option 2.) Enabled Hardware Transform + Vertex Cache

![screenshot_2013-10-15-14-20-41](https://f.cloud.github.com/assets/4035774/1331693/ca6d60c0-3564-11e3-88a3-f405be31df50.png)
![screenshot_2013-10-15-14-25-01](https://f.cloud.github.com/assets/4035774/1331694/ca7025bc-3564-11e3-9a86-feb2697e5108.png)
![screenshot_2013-10-15-14-26-17](https://f.cloud.github.com/assets/4035774/1331695/ca769af0-3564-11e3-890a-241febf3e989.png)
![screenshot_2013-10-15-14-26-53](https://f.cloud.github.com/assets/4035774/1331696/ca79a1fa-3564-11e3-9d82-ade33638f909.png)

Note: Sometimes this glitch also occurs with their mic(s).

**Comment by unknownbrackets** [comment]
I wonder if the changes to the way we bind vbos and element buffers might have improved this somehow.  Does it still happen?

-[Unknown]

**Comment by LinkEP** [comment]
It still happens (v0.9.9.1-1585)
![screenshot_2015-01-23-19-33-51](https://cloud.githubusercontent.com/assets/4035774/5873945/1aebe74c-a337-11e4-8b9e-8e22c12b162d.png)

**Comment by Yoshitsune** [comment]
Still Hapens in 1.01-607 +,This Bug on all Adreno 430,420,405,330,320,306,305,304,302,225,220,205,203,200 if Hardwware Transform on...what to do? when fix it?

**Comment by Yoshitsune** [comment]
more,this have and other game...Persona 3 Portable 
![screenshot_2015-06-26_1650](https://cloud.githubusercontent.com/assets/7737766/8526189/cde2a528-240d-11e5-8405-f5d7030b4669.png)

**Comment by Yoshitsune** [comment]
Hello-o...

**Comment by Yoshitsune** [comment]
![screenshot_2015-06-26_1651_1](https://cloud.githubusercontent.com/assets/7737766/8535706/09af4d70-2451-11e5-8c04-238089f95177.png)

**Comment by Yoshitsune** [comment]
http://forums.ppsspp.org/showthread.php?tid=16033

**Comment by Yoshitsune** [comment]
enabling vertex cache not help,only hardware transform,but slide-show...

**Comment by unknownbrackets** [comment]
Since the latest updates, does this still happen?  Also, if it does and your device supports Vulkan, does it happen there?

-[Unknown]

**Comment by leopard20** [comment]
@hrydgard @unknownbrackets 
This was fixed a long time ago. Probably since 1.4. Surprised no one reported it! (plus Vertex cache is off by default now)

So you can go ahead and close it! :)

**Comment by unknownbrackets** [comment]
This definitely never happened on all devices, though.  It's entirely possible it's a driver bug even...

-[Unknown]

**Comment by hrydgard** [comment]
Either way, I think it's time to close...
