### ISSUE TITLE
PPSSPP should contain help or user guide

### ISSUE THREAD

**Issue by bhavin192** [hrydgard/ppsspp#4225]
As there are many changes in saving file I mean memstick folder
and cwcheat shaders etc.
It will hard to user to find all related posts from forum
so atleast one txt or pdf or links to all related post in forum

**Comment by ResurrectionRedmi9** [comment]
This is still an issue?

**Comment by hrydgard** [comment]
https://ppsspp.org/guides.html is meant to be this, although lots more to be written.
