### ISSUE TITLE
VS 2013 RTM,many games crash on startup with X64 release build

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#4241]
X64 debug build works fine,win32 release and debug build work fine.
crashed games list :
7th dragon 2020 2 JPN
Kingdom Heart BBS FM JPN
Fate Extra CCC JPN
Sword Art Online JPN
Dragon Ball Tag Versus JPN
ETC.
![01](https://f.cloud.github.com/assets/3481559/1365549/5e243f48-386f-11e3-862a-18eb3d37fc34.png)

**Comment by daniel229** [comment]
Fixed in update 5.

**Comment by GAMELASTER** [comment]
Yup, Fixed on Update 5/VS2015

**Comment by unknownbrackets** [comment]
Should we close this then?

-[Unknown]
