### ISSUE TITLE
Discussion: Atomic locks speed

### ISSUE THREAD

**Issue by bollu** [hrydgard/ppsspp#4255]
I've tested out the new FFMPEG changes by Maxim, and they seem to work __extremely__ well with the atomic locks. I'd like to see a more comprehensive test for this though. So if everyone would test out the games they have with the atomic locks (System->Atomic audio locks), it'd be a great help.

Thanks!

**Comment by unknownbrackets** [comment]
Since we no longer have any locks with resampling (just atomic access to a ringbuffer), I suppose this is not an issue anymore.

For XAudio2, there's still #4075 I suppose.

-[Unknown]
