### ISSUE TITLE
Keymapping (combo) feature request if possible

### ISSUE THREAD

**Issue by darkzer0** [hrydgard/ppsspp#4285]
Can I request combo button (for on screen pad) on future build. I think combo button will help to playing game which require hit multiple button at the same time (like disidia air dash "R1+triangle" and kamen rider ultimate attack "square+cross"). 

And I had a question, why when I try maped volume key (for R1 and L1 button) volume button still used as volume control? Because when i see on other emulator (like drastic, FPSE, and EPSXE) when volume button maped as L1 and R1 volume control become turned off (lost function as volume control). Thanks.

**Comment by unknownbrackets** [comment]
I believe this has been implemented in #8096.  If that's not a solution, please comment with more detail and this can be reopened.

-[Unknown]
