### ISSUE TITLE
[Monster Hunter Freedom Unite] Current errors (sceOpenPSIDGetOpenPSID)

### ISSUE THREAD

**Issue by vnctdj** [hrydgard/ppsspp#4366]
Tests done with https://github.com/hrydgard/ppsspp/commit/290958060fa32cd38d8abe7ee7eecc01b8c637aa.

I noticed some errors in the log while playing _Monster Hunter Freedom Unite_ (I noticed the ones which are written in red because I think they are the most important).

The first one appears right after the launch of the game : 
![1](https://cloud.githubusercontent.com/assets/3978690/12057077/a446aea6-af3d-11e5-9ada-00bcba639703.png)
(click on the image to enlarge it)

~~The second one appears right after the game has finished to load (when we can see our character in the village, I mean when you go out from the menus) :~~
![2](https://f.cloud.github.com/assets/3978690/1431387/ea830cba-40cd-11e3-8afb-d70554038645.png)
~~(click on the image to enlarge it)~~

~~For your information, this second error has already been mentioned here : https://github.com/hrydgard/ppsspp/issues/4248#issuecomment-26767977~~

I noticed a new error, let's call it the third error :
It happens while loading the next zone, and also when the reward screen appears :
![2](https://cloud.githubusercontent.com/assets/3978690/12057199/b25dca96-af3e-11e5-9b22-f94054d97504.png)
(click on the image to enlarge it)

I don't know what these errors can do in the game, but I'm reporting them in order to keep a trace of them :)

**Comment by unknownbrackets** [comment]
The second error should now be gone.  The other is still untested.

It may actually have something to do with netplay, I'm not really sure.

-[Unknown]

**Comment by vnctdj** [comment]
I have done some tests with the latest build and updated the first post accordingly :)
To sum up :
First error is still present (as I expected).
Second error has disappeared (yeah !).
Third error appeared, I have not bisected though... What do you think of this one ?

**Comment by unknownbrackets** [comment]
The third one is just a bug in the game, likely.  We can compare using JpcspTrace if you want, but a lot of games seem to call those funcs with invalid parameters sometimes.

-[Unknown]

**Comment by vnctdj** [comment]
Hmm, OK, let's forget this third error then.

About the first error : after a quick search of "sceOpenPSIDGetOpenPSID" in Google, I can't find more info than it could be related to a PSP id, maybe to authenticate against the PSN...
But this game only have **ad-hoc** multiplayer, isn't it strange ?

**Comment by unknownbrackets** [comment]
Yes, it's possible that it uses this in the savedata or something, though.

Do saves work between a real PSP and PPSSPP for this game?

-[Unknown]

**Comment by vnctdj** [comment]
Yes, I never had any problem transferring my save between my PSP and PPSSPP :)

**Comment by unknownbrackets** [comment]
Hmm, mysterious.  It could still be used for identifying players via adhoc, I guess.

-[Unknown]

**Comment by unknownbrackets** [comment]
The OpenPSID error is now a warning and not aware of any problems.

I believe the Atrac3 error has been resolved now.

The reverb type being set to that value has been tested and correctly errors.

Given that, I'm going to close this.  I think it's all resolved now.

-[Unknown]
