### ISSUE TITLE
storing each game configs (settings+controls) just like save state and load state

### ISSUE THREAD

**Issue by fastrizwaan** [hrydgard/ppsspp#4402]
There are many games which needs unique settings to work, and users need to have different key combinations for different games.

It would be really useful to have controls.ini+settings.ini for each game separately, so that loading a new game will not require deleting ~/.ppsspp folder.

it's just like we save multiple game "Save States" and "Load states" which are stored in pppsspp folder for every game played and state-saved! And mulitple save states of different games works just fine, so can these per-game settings too!

**Comment by unknownbrackets** [comment]
This was implemented in #7183, so closing.

-[Unknown]
