### ISSUE TITLE
Some sort of Netplay functionality with WinPCap

### ISSUE THREAD

**Issue by sooyong94** [hrydgard/ppsspp#4490]
Is it possible to implement some kind of netplay functionality through a software AP, for example WinPCap?  Some emulators like Desmume has been implementing such features.  
http://forum.romulation.net/index.php?topic=54397.0

**Comment by unknownbrackets** [comment]
Is this still relevant?  I mean, we have other bugs for network stuff, and I don't think we want/need to use winpcap.

-[Unknown]

**Comment by vnctdj** [comment]
I think we should answer to that :
What would be the benefits/drawbacks to use WinPcap ? Could it be useful ?

**Comment by Bigpet** [comment]
I don't know what we would use winpcap for. I mean you could use it outside of ppsspp with tools like wireshark but I think we should just do the tooling around networking without an extra library, just with bsd sockets.

**Comment by unknownbrackets** [comment]
I guess the benefit of winpcap would be emulating a protocol other than tcp/udp/etc.  However, I don't think the psp uses any such protocols.

-[Unknown]

**Comment by hrydgard** [comment]
Probably no longer relevant, closing.
