### ISSUE TITLE
ULUS10442 - Kenka Bancho Badass Rumble stuck

### ISSUE THREAD

**Issue by reiclone** [hrydgard/ppsspp#4523]
The game crashes at the loading after this scene(first fight with a bancho)
![before](https://f.cloud.github.com/assets/3243212/1535725/b6351314-4ca7-11e3-8e98-f2d54d42410c.jpg)

It gets stuck in the loading screen:
![stuck](https://f.cloud.github.com/assets/3243212/1535729/bd39899c-4ca7-11e3-804c-f910fcc337f0.png)

and it goes black after a while.

I tried it with PPSSPP v0.9.5-339 Windows7 64bit, but it's reported to happen at least since v0.7.6-816-g2c4254d on the forum thread.

Here is the log when it starts loading (taken with "Ignore Illegal Reads/Writes" off).
![start](https://f.cloud.github.com/assets/3243212/1527258/a1e13732-4bf1-11e3-9636-0df1ed70f013.png)
then there is a lot of "Invalid address" and it ends with:
![end](https://f.cloud.github.com/assets/3243212/1527260/bcb91c78-4bf1-11e3-8afa-71b14d9e0f46.png)

Full Log (35MB): http://www59.zippyshare.com/v/37371141/file.html
The game works great otherwise.

edit: Added some Images, modified the title and added full log.

**Comment by unknownbrackets** [comment]
Has there been any improvement with the various audio changes we've made since that version?

If not, an updated log might still help.

-[Unknown]

**Comment by reiclone** [comment]
No changes.
Last part from a debug log from v0.9.9.1-1576-g4100163-windows-amd64
With fast memory off and buffered rending.
http://pastebin.com/DXAvL2Fh

**Comment by issuer** [comment]
Still crashes in 1.0.

**Comment by rz5** [comment]
This is still happening in the latest git build. Tested with Fast Memory off, here are the last 20 lines of the debug console:

```
38:37:815 MyThread-Dis I[IO]: HLE\sceIo.cpp:2234 sceIoIoctl: Asked for size of file 4
38:37:964 MyThread-Dis W[FileSys]: FileSystems\ISOFileSystem.cpp:573 Reading beyond end of file, clamping size 196608 to 97823
38:38:110 MyThread-Dis I[IO]: HLE\sceIo.cpp:2234 sceIoIoctl: Asked for size of file 4
38:38:111 MyThread-Sou I[ME]: HLE\sceAtrac.cpp:991 0=sceAtracGetAtracID(00001000)
38:38:115 MyThread-Mai I[G3D]: GLES\ShaderManager.cpp:162 Linked shader: vs 38 fs 39
38:38:116 MyThread-Mai I[G3D]: GLES\ShaderManager.cpp:162 Linked shader: vs 41 fs 42
38:38:118 MyThread-Mai I[G3D]: GLES\ShaderManager.cpp:162 Linked shader: vs 41 fs 44
38:38:118 MyThread-Mai I[G3D]: GLES\ShaderManager.cpp:162 Linked shader: vs 41 fs 46
38:38:131 MyThread-Mai I[G3D]: GLES\ShaderManager.cpp:162 Linked shader: vs 48 fs 46
38:38:133 MyThread-Mai I[G3D]: GLES\ShaderManager.cpp:162 Linked shader: vs 12 fs 50
38:38:183 MyThread-Dis I[IO]: HLE\sceIo.cpp:2234 sceIoIoctl: Asked for size of file 4
38:38:288 MyThread-Dis I[IO]: HLE\sceIo.cpp:2234 sceIoIoctl: Asked for size of file 4
38:38:389 MyThread-Dis W[FileSys]: FileSystems\ISOFileSystem.cpp:573 Reading beyond end of file, clamping size 196608 to 148980
38:38:417 MyThread-Sou I[ME]: HLE\sceAtrac.cpp:1896 0=sceAtracSetData(0, 08400000, 000b45f4): atrac3+ stereo audio
38:38:782 idle0        I[G3D]: GLES\ShaderManager.cpp:1039 Saving the shader cache to 'C:\Users\rz5\Emulators\ppsspp\memstick/PSP/SYSTEM/CACHE//ULUS10442.glshadercache'
38:40:996 MyThread-Mai I[HLE]: HLE\scePower.cpp:369 scePowerSetClockFrequency(222,222,111)
38:41:002 MyThread-Mai I[HLE]: HLE\scePower.cpp:369 scePowerSetClockFrequency(333,333,166)
38:41:051 MyThread-Dis I[IO]: HLE\sceIo.cpp:2234 sceIoIoctl: Asked for size of file 4
38:41:251 MyThread-Dis W[FileSys]: FileSystems\ISOFileSystem.cpp:573 Reading beyond end of file, clamping size 196608 to 138642
38:41:438 MyThread-Sou E[MM]: MemmapFunctions.cpp:55 Unknown GetPointer 116ff1c8 PC 116ff1c8 LR 116ff1c8
```

**Comment by unknownbrackets** [comment]
Can you open Debug -> Disassembly..., and paste 0894fc28 in the top left under "Go to", and press enter?  And then take a screenshot and upload it here?

Not sure if it will help, but maybe if I can see the code in the area I can come up with some idea of why it's wigging out.

-[Unknown]

**Comment by daniel229** [comment]
Here
[1](https://cloud.githubusercontent.com/assets/3481559/12574642/d4b81fe4-c440-11e5-9f04-f7ab4dfd7a4b.png)

**Comment by daniel229** [comment]
This happen when the first cutscene finish and then load the second sutscene.https://github.com/hrydgard/ppsspp/issues/6813 is the same.The demos don't have the second cutscene,so it would hang.

**Comment by rz5** [comment]
My game crashes in a spot which is different from the OP, but the situation is the same: a cutscene reaches the end, I reach a 'Now Loading...' screen and the game freezes.

@unknownbrackets, here's the requested screenshot:
![image](https://cloud.githubusercontent.com/assets/8117159/12597022/eec7bd56-c47a-11e5-8143-56c5b2f2fdef.png)

**Comment by LunaMoo** [comment]
To shed a bit more light on this - direct/immediate reason of the freeze is pretty simple - the game goes through a function to generate pointers for cutscene dialogues starting from a table of offsets and adding base to those then writing resulting pointers at same address, we get bugged since the function runs again when pointers are already there and effectively breakes them by adding base to pointers again without checking it in any way, seems like a bad coding to me I mean game side.

 I'm able to hack it pretty easily to the point of loading map and dialogues alright, but still npc's are missing from the cutscene. My theory on it would be this is a timing issue which causes the game to load some cutscenes too fast - before freeing up memory for it and since it re-creates that pointer list(which has like 3600 positions, one for each dialogue box for all cutscenes) before every cutscene it must expect it to be cleared earlier. Missing npc's when trying code hacks like I did might just be result of not having enough memory as they likely to load last.
 Unfortunately no features related to cpu/io(or any other for that matter) we have affected it as of yet.

**Comment by unknownbrackets** [comment]
If you look at the memory those functions change - does any other function also change that memory?  Maybe we can find the cleanup function, at least, and figure out what's supposed to trigger it.

Do any memory allocations fail?  They should be logged.

-[Unknown]

**Comment by LunaMoo** [comment]
![clearing](https://cloud.githubusercontent.com/assets/5485237/13210157/9912f472-d92c-11e5-8702-bf3ee6d2b893.jpg)
Well the highlited opcodes in this function are writing FF clearing memory I guess and later also those offsets to the list I mentioned earlier, before the cutscene affected by this issue this function never runs which is causing all the problems.

 Also when I hack it in a way that it doesn't load npc's I just see a few read from and write to hardware invalid addresses which are all small numbers offsets to some pointer or other random values, without any hackery I just get the unknown get pointer as in the log above since it fails at those broken pointers.

**Comment by sum2012** [comment]
Update the log to v1.2.2-907-g2d838f7 
https://gist.github.com/sum2012/f427d9079e3874f2f99c64f04a842d5e

**Comment by LunaMoo** [comment]
Real psp with cfw when cpu clock get's forced to 333mhz apparently crashes in same places, treating it as a hint, we can see game quickly changes cpu clock twice right before the crash so maybe it could be something similar to #2104 ~ althrough that was already fixed long ago.

**Comment by sum2012** [comment]
Do we have a cpu clock check cfw plugin to check this game clock ?

**Comment by hrydgard** [comment]
So it's definitely some timing issue. I think we handle clock changes mostly correctly now, but it could be as simple as some Atrac or Mpeg function not taking enough time or taking more time than expected, or rescheduling when they shouldn't, etc. If there was a way to log all context switches on the real PSP that might help...

**Comment by sum2012** [comment]
Small finding from jpcsptrace of scePowerSetClockFrequency 
The timing is 0.150 second

07:13:11.471 MyThread-Main - scePowerSetClockFrequency 0x14D, 0x14D, 0xA6 = 0x0
07:13:11.621 MyThread-Main - scePowerSetClockFrequency 0x14D, 0x14D, 0xA6 = 0x0
07:13:16.362 MyThread-Main - scePowerSetClockFrequency 0xDE, 0xDE, 0x6F = 0x0
07:13:16.510 MyThread-Main - scePowerSetClockFrequency 0xDE, 0xDE, 0x6F = 0x0
07:13:17.777 MyThread-Main - scePowerSetClockFrequency 0x14D, 0x14D, 0xA6 = 0x0
07:13:17.927 MyThread-Main - scePowerSetClockFrequency 0x14D, 0x14D, 0xA6 = 0x0
07:13:40.634 MyThread-Main - scePowerSetClockFrequency 0xDE, 0xDE, 0x6F = 0x0
07:13:40.784 MyThread-Main - scePowerSetClockFrequency 0xDE, 0xDE, 0x6F = 0x0
07:13:40.817 MyThread-Main - scePowerSetClockFrequency 0x14D, 0x14D, 0xA6 = 0x0
07:13:40.967 MyThread-Main - scePowerSetClockFrequency 0x14D, 0x14D, 0xA6 = 0x0
07:13:44.908 MyThread-Main - scePowerSetClockFrequency 0xDE, 0xDE, 0x6F = 0x0
07:13:45.055 MyThread-Main - scePowerSetClockFrequency 0xDE, 0xDE, 0x6F = 0x0
07:13:46.272 MyThread-Main - scePowerSetClockFrequency 0x14D, 0x14D, 0xA6 = 0x0
07:13:46.422 MyThread-Main - scePowerSetClockFrequency 0x14D, 0x14D, 0xA6 = 0x0
07:15:18.099 MyThread-Main - scePowerSetClockFrequency 0xDE, 0xDE, 0x6F = 0x0
07:15:18.248 MyThread-Main - scePowerSetClockFrequency 0xDE, 0xDE, 0x6F = 0x0
07:15:18.281 MyThread-Main - scePowerSetClockFrequency 0x14D, 0x14D, 0xA6 = 0x0
07:15:18.431 MyThread-Main - scePowerSetClockFrequency 0x14D, 0x14D, 0xA6 = 0x0
07:15:23.073 MyThread-Main - scePowerSetClockFrequency 0xDE, 0xDE, 0x6F = 0x0
07:15:23.220 MyThread-Main - scePowerSetClockFrequency 0xDE, 0xDE, 0x6F = 0x0
07:15:23.246 MyThread-Main - scePowerSetClockFrequency 0x14D, 0x14D, 0xA6 = 0x0
07:15:23.386 MyThread-Main - scePowerSetClockFrequency 0x14D, 0x14D, 0xA6 = 0x0

**Comment by sum2012** [comment]
Yes, those in and out,gid15 's jpcsptrace don't have "<" ,">" for in & out.

OH Yes,I fix the game

**Comment by sum2012** [comment]
Thanks @LunaMoo for the hint

**Comment by rz5** [comment]
Congrats @sum2012 and everyone involved, this was a long standing bug  which affected a game I liked on the handheld.

**Comment by sum2012** [comment]
oop,find two problem

Case 1:
After kill enemy,
In the menu,press move ,Will raise invalid address.

Case 2:
Load save,Press move,Will get infinite loading

**Comment by LunaMoo** [comment]
Thanks for fixing it @sum2012, also "moves" menu is broken for people with bad dump so not an emulation problem anymore, this would happen on real psp as well.

 Works fine with correctly dumped iso's:
![ulus10442_00000](https://cloud.githubusercontent.com/assets/5485237/18295153/529e22dc-749f-11e6-879f-e2c33d0ebb17.jpg)

**Comment by sum2012** [comment]
@LunaMoo but I test real psp ,It can go inside  [move] menu,I will give you
more information when I back home

**Comment by LunaMoo** [comment]
Well by google about it, there're lots of people with the problem from before PSP emulation was a thing when there was some bug with iso dumping in cfw's.

 Here's some info about proper dump of UMD release:
 Iso size: 524 222 464 bytes
 CRC32: cd74299d
 MD5: a9f2095cd6120c5cd4f1964732773b80
 SHA-1: ef7fb4b5b0365dfce126e8b18c300fe51cb499b9

 The only file the game reads when entering this menu is disc0:/PSP_GAME/USRDIR/TESTDATA/WAZAEDIT.LZS which isn't very big, but checking with UMDGen it's the last file on the iso ~ easily broken by incomplete dumps, maybe even unfinished transfer when you copied it from your psp which would explain why works there and not on ppsspp. Don't know what else could be happening, also tried cso without problems.

**Comment by sum2012** [comment]
I redo jpcsptrace log:maybe I added scePowerGetCpuClockFrequencyInt 
now the timing is 139-142

19:51:20.085 MyThread-Main - scePowerGetCpuClockFrequencyInt = 0x0
19:51:20.085 MyThread-Main - scePowerGetCpuClockFrequencyInt = 0xDE
19:51:20.093 MyThread-Main - scePowerSetClockFrequency 0x14D, 0x14D, 0xA6 = 0x0
19:51:20.235 MyThread-Main - scePowerSetClockFrequency 0x14D, 0x14D, 0xA6 = 0x0
19:51:23.925 MyThread-Main - scePowerGetCpuClockFrequencyInt = 0x0
19:51:23.925 MyThread-Main - scePowerGetCpuClockFrequencyInt = 0x14D
19:51:23.934 MyThread-Main - scePowerSetClockFrequency 0xDE, 0xDE, 0x6F = 0x0
19:51:24.073 MyThread-Main - scePowerSetClockFrequency 0xDE, 0xDE, 0x6F = 0x0
19:51:25.340 MyThread-Main - scePowerGetCpuClockFrequencyInt = 0x0
19:51:25.340 MyThread-Main - scePowerGetCpuClockFrequencyInt = 0xDE
19:51:25.348 MyThread-Main - scePowerSetClockFrequency 0x14D, 0x14D, 0xA6 = 0x0
19:51:25.490 MyThread-Main - scePowerSetClockFrequency 0x14D, 0x14D, 0xA6 = 0x0

**Comment by sum2012** [comment]
I get correct dump of this game from my friend.Closing
