### ISSUE TITLE
Metal Gear Acid [ULUS10006] crash during level exit

### ISSUE THREAD

**Issue by i30817** [hrydgard/ppsspp#4536]
Seems to be repeatable on this computer if moving to the 'second' target circle on the save state provided. Which card or direction used doesn't seem to matter. The first circle works.

The log says:
10:19:017 idle0        I[COMMON]: /home/user/Documents/Netbeans_projects/ppsspp/Common/ChunkFile.h:600 ChunkReader: Done loading /home/user/.ppsspp/PSP/PPSSPP_STATE/ULUS10006_1.00_0.ppst
10:19:032 Main         I[SCEGE]: /home/user/Documents/Netbeans_projects/ppsspp/GPU/GLES/Framebuffer.cpp:748 Creating FBO for 00044000 : 480 x 272 x 1
10:19:214 Main         I[SCEGE]: /home/user/Documents/Netbeans_projects/ppsspp/GPU/GLES/Framebuffer.cpp:748 Creating FBO for 00000000 : 480 x 272 x 1
10:19:214 Main         W[SCEGE]: /home/user/Documents/Netbeans_projects/ppsspp/GPU/GLES/Framebuffer.cpp:758 FBO sharing existing depthbuffer (unsupported), 00000000/00088000 and 00044000/00088000
Segmentation fault (core dumped)

The savestate:
http://speedy.sh/9q7W7/ULUS10006-1.00-0.ppst.zip

**Comment by sum2012** [comment]
#5365 appear to fixed in v0.9.9.1-1505-gcf577e9
This one may also fix.
But need someone testing

**Comment by i30817** [comment]
Yes, it seems fixed. If you want to test it yourself, load the savestate linked in my google drive above and save with the ingame save option from the select menu, then quit, reload the game and 'continue'.
Fast memory and JIT enabled, no crash.

**Comment by unknownbrackets** [comment]
Glad it's fixed either way.  I'll mark this as closed.

-[Unknown]
