### ISSUE TITLE
God Eater 2 hangs with 1.01 update

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#4545]
@tpunix
God eater 2 just released 1.01 update,but it hangs when I move the player.
The update files(.sprx) have been decrypted,otherwise,It would not let you go ingame.

![01](https://f.cloud.github.com/assets/3481559/1549570/0811a9ee-4de9-11e3-9c35-52dca6aff313.png)
![02](https://f.cloud.github.com/assets/3481559/1549569/08119512-4de9-11e3-97a5-42da00cbb349.png)

**Comment by unknownbrackets** [comment]
Have any of the recent changes with memory allocation and IO timing helped?  Do different IO timing methods have any effect?

-[Unknown]

**Comment by benderscruffy** [comment]
No feedback/outdated?
