### ISSUE TITLE
Coded Arms vertice issue

### ISSUE THREAD

**Issue by piratefinn** [hrydgard/ppsspp#4551]
It appears to be when playing Coded Arms that it has some sort of vertice error which throws stuff around while playing. I would explain, but it is much better demonstrated with the video I recorded of gameplay (linked). This issue is both on Android and PC.
http://www.youtube.com/watch?v=Prze2K41Vus

I know this is not a glaring issue and there are probably better things to deal with this moment, so don't worry I won't chivvy people about it.

**Comment by ppmeis** [comment]
Tested in latest build. Same issues:
![image](https://cloud.githubusercontent.com/assets/4381277/8891464/3af5bb9c-332b-11e5-8282-f3aef8c9f5c3.png)
![image](https://cloud.githubusercontent.com/assets/4381277/8891465/3fe675a6-332b-11e5-9263-d9e2b7d5c2bd.png)

**Comment by Zetchzie** [comment]
issue is still present in latest git
