### ISSUE TITLE
Improving sceAtracGetBufferInfoForResetting (passes the resetting test)

### ISSUE THREAD

**Issue by xekarfwtos** [hrydgard/ppsspp#4553]
Hi,

I improved the sceAtracGetBufferInfoForResetting function (commit e051b8872b3103286c21b2cb9946cf14c45c8d4d) and PPSSPPHeadless passes the resetting test. 

But running the game "Tenchu: Shadow Assassins" freeze. It passes atracID = 0 and sample = 0 to this function.

So now, I need to add some instances in the resetting test and test it again, but first I should find out why the building of resetting test fails (I opened an issue on pspautotests).

**Comment by hrydgard** [comment]
This issue is probably a bit outdated, closing.
