### ISSUE TITLE
Turning "Texture coord speed hack" on by default

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#4583]
To get the full benefit of software skinning in some games like Tekken 6, the "Texture coord speed hack" needs to be on. And since sw skinning is on by default now, I would like to switch this to on too. 

Previously it was reported that 3rd Birthday has problems with it, is this still the case?

Please mention and preferably add screenshots of any issues you see when turning on "Texture coord speedhack".

**Comment by unknownbrackets** [comment]
Prescale UV against bezier/splines was easily fixed, but took a bit of confusion to realize that it's not working correctly for render-to-texture (specifically when the texture is not the size expected.)

-[Unknown]
