### ISSUE TITLE
Radiant Mythology 2 and 3 have incorrect music/voices

### ISSUE THREAD

**Issue by vsub** [hrydgard/ppsspp#4595]
Before when attrac was not part of ppsspp,ppsspp would randomly crash and I'll get the Send\Don't send dialog with at3plusdecoder.dll for the reason(doesn't happen with 0.9.1-452 or maybe it happens extremely rarely)

When I try something after 0.9.5(including),the music randomly disappear and  I'll randomly get this is the console
cSoundMusic  E[ME]: HLE\sceAtrac.cpp:602 avcodec_decode_audio4: Error decoding audio -1163346256

The only way to restore the music is by restarting ppsspp and load normal save(not save state)

**Comment by daniel229** [comment]
Music stop since https://github.com/unknownbrackets/ppsspp/commit/60378dd
```
16:50:501 cSoundMusic  I[ME]: HLE\sceAtrac.cpp:1436 sceAtracReleaseAtracID(1)
16:50:517 cSoundMusic  I[ME]: HLE\sceAtrac.cpp:1760 0=sceAtracSetDataAndGetID(08cb3040, 00020000)
16:50:517 cSoundMusic  W[ME]: HLE\sceAtrac.cpp:1652 This is an atrac3+ stereo audio
16:50:556 cSoundVoice  I[ME]: HLE\sceAtrac.cpp:1760 1=sceAtracSetDataAndGetID(08cdb080, 00002478)
16:50:556 cSoundVoice  W[ME]: HLE\sceAtrac.cpp:1650 This is an atrac3+ mono audio
16:50:658 cSoundVoice  I[ME]: HLE\sceAtrac.cpp:1436 sceAtracReleaseAtracID(1)
16:50:994 cSoundMusic  I[ME]: HLE\sceAtrac.cpp:1436 sceAtracReleaseAtracID(0)
16:51:042 cSoundMusic  I[ME]: HLE\sceAtrac.cpp:1760 0=sceAtracSetDataAndGetID(08cb3040, 00020000)
16:51:042 cSoundMusic  W[ME]: HLE\sceAtrac.cpp:1652 This is an atrac3+ stereo audio
16:51:043 cSoundMusic  I[ME]: HLE\sceAtrac.cpp:1157 0=sceAtracGetBufferInfoForResetting(0, 2096644, 09ffddd8)
16:51:044 user_main    I[SCEGE]: Common\FramebufferCommon.cpp:417 Creating FBO for 00155f80 : 128 x 128 x 3
16:51:045 cSoundMusic  I[ME]: HLE\sceAtrac.cpp:1506 0=sceAtracResetPlayPosition(0, 2096644, 131040, 0)
16:51:747 cSoundMusic  I[KERNEL]: HLE\sceKernelThread.cpp:1943 394=sceKernelCreateThread(StreamDataReader, 08a6f0b4, 00000014, 4096, 00000000, 0000000
0)
16:51:747 cSoundMusic  I[KERNEL]: HLE\sceKernelThread.cpp:2014 0=sceKernelStartThread(394, 16, 09ffddc8)
16:51:747 StreamDataRe I[KERNEL]: HLE\sceKernelThread.cpp:2066 sceKernelExitThread(1)
16:55:147 cSoundMusic  I[ME]: HW\MediaEngine.cpp:87 FF: Frame data doesn't match channel configuration!
16:55:147 cSoundMusic  E[ME]: HLE\sceAtrac.cpp:444 avcodec_decode_audio4: Error decoding audio -1094995529 / bebbb1b7
16:55:151 cSoundMusic  I[ME]: HLE\sceAtrac.cpp:1436 sceAtracReleaseAtracID(0)
```

**Comment by unknownbrackets** [comment]
If you revert the first two changes of 60378dd only, does it change it?

I'm guessing this is streaming.  Maybe it's related to the remaining frame number, then, but not sure why that commit would've altered it...

-[Unknown]

**Comment by daniel229** [comment]
Yeah,it works.

**Comment by daniel229** [comment]
it seems it was broken before https://github.com/unknownbrackets/ppsspp/commit/60378dd

**Comment by daniel229** [comment]
It seems it less happens in the old build.The new build often happen in 2,3 battles.
Get 1 music stop in 50 battles in v1.0.1-207-g79fc557
I don't get music stop in 50 battles in v1.0.1-170-g1f987ef and v1.0.1-52-g3773d25

**Comment by unknownbrackets** [comment]
Improved at all by #8189?  Sorry for so many battles, I know how it can be testing something that doesn't always happen...

-[Unknown]

**Comment by daniel229** [comment]
Looks good,without music stop in 50 battles.

**Comment by unknownbrackets** [comment]
Awesome.

Are the voices still wrong at the beginning?  Maybe we should create a separate bug for just that if it's all that left - it might have a separate cause, and there's lots of info here already.

-[Unknown]

**Comment by daniel229** [comment]
The voices is the same as https://github.com/hrydgard/ppsspp/issues/8156

**Comment by unknownbrackets** [comment]
Is the voice thing still happening or is that fixed now?

-[Unknown]

**Comment by daniel229** [comment]
Fixed.

**Comment by unknownbrackets** [comment]
Yay, this one's been a little bit of a journey.  Feels good to hit the close button.

-[Unknown]
