### ISSUE TITLE
Escape / Back allows gamepad/keyboard buttons to get stuck

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#4616]
UI dialogs don't send button presses to sceCtrl when they are
focused (including key releases.)

See video:
https://drive.google.com/file/d/0B3OaSdeV0L8kOGJ3eDhRX2RjY1k/edit?usp=sharing

Some code can reference to solve
https://github.com/hrydgard/ppsspp/pull/4613

**Comment by unknownbrackets** [comment]
So is there any reason why sending KEY_UP to the sceCtrl state tracking for ALL screen types wouldn't solve this?  We would only send key down from the EmuScreen.  This way it would know when you let go on the pause screen.

Alternatively, we could just send the ups on the pause screen.  Or we could queue them, but i don't think that's necessary.

-[Unknown]
