### ISSUE TITLE
Feature request: About not active window and gamepads

### ISSUE THREAD

**Issue by vsub** [hrydgard/ppsspp#4641]
Make it so that when you are not ingame(game not started or it's paused(screen menu)),the ability to control ppsspp with gamepad to not work if the window is not active.

It's a good feature to be able to play games without making the window active but it's a problem if you want to use your gamepad for something else while ppsspp is still working(the game is paused(Screen Menu))

The only "fix" for now is to suspend the emulation.

**Comment by unknownbrackets** [comment]
I realize this is slightly different, but is the problem solved by the "ignore when not focused" option?

Personally, I think adding the other feature would still need to be optional, given the use case I gave above.  I don't really think it's worth the extra option in the UI, when reasonable use cases are probably taken care of by the existing feature.

-[Unknown]

**Comment by vsub** [comment]
Well you could say that(because autohide was added recently to the onscreen controls)

**Comment by unknownbrackets** [comment]
Well, we don't want to create a maze of obscurely labeled options for the user to wind through.

I mean, sure, some who play video games like to use "galaxy" difficulty settings and such, and these people might prefer an extremely challenging emulator configuration experience.  But for most people, and me, "keep it simple, stupid."

So I'm going to close this.

-[Unknown]

**Comment by vsub** [comment]
Hmm I didn't saw that option "Auto-hide buttons after seconds" and now there is no need for what I suggested above but there is a problem with it and I'll create an issue about it
