### ISSUE TITLE
multiple disc issue

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#4644]
Cannot mutiple disc:
Shin Sangoku Musou 6 SP
FF Type-0 (HOME  button)
visual novel "rewrite" cannot change disc
Need only display the game 's other disc

no Kiseki SC  :done
Re-use "Cancel" transate in change umd : Done
No win32 menu:shenweip have done

**Comment by unknownbrackets** [comment]
#6646 is related to this.  Also, I have a branch there that allows reporting on the home button, but there are keymap issues.

If you use this branch:

https://github.com/hrydgard/ppsspp/compare/master...unknownbrackets:ctrl-extra

And then change this function in Core/HLE/sceCtrl.cpp:

```c++
void __CtrlButtonDown(u32 buttonBit)
{
	std::lock_guard<std::recursive_mutex> guard(ctrlMutex);
	ctrlCurrent.buttons |= buttonBit;
}
```

To:

```c++
void __CtrlButtonDown(u32 buttonBit)
{
	if (buttonBit & CTRL_START) {
		buttonBit |= CTRL_HOME;
	}

	std::lock_guard<std::recursive_mutex> guard(ctrlMutex);
	ctrlCurrent.buttons |= buttonBit;
}
```

It will make the start button ALSO trigger a home button press.  Then we can verify our assumption that triggering a home press would fix this.

-[Unknown]

**Comment by Smoker1** [comment]
Some Homebrew Apps need a Home Button in order to Access the PSP Emu Menu. Would be helpful to access Setting, Remap Controls, ect.

**Comment by unknownbrackets** [comment]
Has this improved at all with the builds in #4644?

-[Unknown]

**Comment by sum2012** [comment]
i think remain home button

**Comment by unknownbrackets** [comment]
I think it is possible to map Home now.  Does pressing it work?  If yes, maybe we could make selecting the menu item automatically trigger Home.

-[Unknown]

**Comment by benderscruffy** [comment]
is this still a problem ??

**Comment by sum2012** [comment]
VN rewrite issue refer to #15909
Close this issue

**Comment by IrfanH495** [comment]
![Screenshot_20221224-214134_PPSSPP](https://user-images.githubusercontent.com/78854859/209440990-1e514f11-89fa-4606-bd92-025670aac170.png)
I have set the home button to use volume still nothing happens.
maybe I set the wrong button, I don't have a gamepad to try it anymore.
