### ISSUE TITLE
Soul calibur Broken Destiny hangs at "Versus" menu

### ISSUE THREAD

**Issue by mrdendistyle** [hrydgard/ppsspp#4655]
Soul Calibur: Broken Destiny works fine for almost everything. But as soon as you enter the "Versus" part of the menu (Adhoc) the whole screen turns black + no sound without the emulator "freezing" meaning that I can still see fps and stuff.

Tried it on 0.8.1, 0.9.1 and 0.9.5.

ULES01298

**Comment by ppmeis** [comment]
Tested latest build. Still black screen.

**Comment by benderscruffy** [comment]
v1.8.0-2-g7f1e10a93
sits in the battle lobby now but it is empty
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/2966303/ppsspplog.zip)
![soul](https://user-images.githubusercontent.com/2696404/54356868-9aa4ac00-4697-11e9-831f-f00dd3c310b6.PNG)

**Comment by unknownbrackets** [comment]
Is this still an issue on the latest git build with recent networking improvements?

-[Unknown]

**Comment by ANR2ME** [comment]
As i remembered Soul Calibur already been fixed.
