### ISSUE TITLE
"Missing Key" in homebrew

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#4676]
There are some homebrew games (self-signed ones) that won't play because we seem to missing some decryption key. This must be out there as it's possible for homebrewers to sign with this key. We should figure out what it is and add it.

Example game: Touhou
http://kene-touhou-mohofu.googlecode.com/files/231_kene_r38.zip

**Comment by sum2012** [comment]
Just a news, Hykem is trying to fix "Bleach: Soul Carnival 2 Demo" loading which is also don't work on JPCSP

**Comment by LunaMoo** [comment]
Is this still a problem? I remember last update with keys we got included those keys together with pauth ones and only keys for the game updates(which is very unfortunate;c) are missing now.

 Most links here doesn't work, but the "Worm Warrior" from the second post here works as I tried now.

**Comment by benderscruffy** [comment]
this can be closed
worm warrior and mario boat 1.1 work 
haven't come across any other ones yet
