### ISSUE TITLE
Some homebrew games/software don't display anything or display incorrectly since the removal of Display Raw Framebuffers back in 0.9

### ISSUE THREAD

**Issue by thedax** [hrydgard/ppsspp#4685]
I'm just wondering if there's a better way to have these troublesome homebrews display anything rather than reviving the Display Raw Framebuffer hack that we used to have.

Example homebrews that need Display Raw Framebuffer to function:
- [Rhythm8](http://forums.ppsspp.org/showthread.php?tid=7573) (though it has other issues with hanging)
- Some versions of gPSP Kai need it for the menu
- Several other homebrews, according to [this thread](http://forums.ppsspp.org/showthread.php?tid=2616)

**Comment by hrydgard** [comment]
Closing this because I don't think we intend to take any more action here.
