### ISSUE TITLE
Debug idea/feature: FIFO player like Dolphin?

### ISSUE THREAD

**Issue by thedax** [hrydgard/ppsspp#4784]
Not sure how feasible this is for a PSP emulator, but I've noticed that Dolphin has a FIFO player, which seems to allow the emulator to dump almost everything that's going on, graphics wise, into a file, and can then play it back on another computer, even if the developer or person using the file doesn't have the game.

Could such a feature be useful for PPSSPP?

Note that I'm not volunteering to write it, that's way beyond me. It's merely an idea.

**Comment by unknownbrackets** [comment]
An initial stab:
https://github.com/hrydgard/ppsspp/compare/master...unknownbrackets:ge-record?expand=1

Technically, it might be best to push the initial VRAM as an INIT command, in case it affects rendering.  But this won't capture pokes anyway.  Hmm...

Have not tried to write any replay yet, so it may not work at all, possibly...

-[Unknown]

**Comment by hrydgard** [comment]
That will be great, would be cool to run our own instance of Dolphin's FifoCI for testing graphics. Well, technically maybe should push all of RAM, but mostly should be able to get away with all the memory that's actually referenced (texture, vertex and CLUT data).

I'll take a closer look at your code later.

**Comment by unknownbrackets** [comment]
It kinda works now (branch updated), but some things draw wrong.  The way it's allocating is definitely not optimal, and most vertices, indices, and textures are at the same address, so it may be a caching issue....

Some scenes render fine though, so it's progress...

PS: You have to add something like this to test it (haven't added a proper button yet, so many already...)
```diff
diff --git a/Windows/GEDebugger/GEDebugger.cpp b/Windows/GEDebugger/GEDebugger.cpp
--- a/Windows/GEDebugger/GEDebugger.cpp
+++ b/Windows/GEDebugger/GEDebugger.cpp
@@ -36,6 +36,7 @@
 #include "GPU/Common/GPUStateUtils.h"
 #include "GPU/GPUState.h"
 #include "GPU/Debugger/Breakpoints.h"
+#include "GPU/Debugger/Record.h"
 #include "GPU/Debugger/Stepping.h"
 #include "Core/Config.h"
 #include <windowsx.h>
@@ -817,6 +818,8 @@ void WindowsHost::GPUNotifyDisplay(u32 framebuf, u32 stride,
 void WindowsHost::GPUNotifyDraw() {
   if (breakNext == BREAK_NEXT_DRAW) {
     PauseWithMessage(WM_GEDBG_BREAK_DRAW);
+    // TODO
+    GPURecord::Activate();
   }
 }

```

-[Unknown]

**Comment by unknownbrackets** [comment]
Okay, it works now, I think.  A bit messy...

-[Unknown]
