### ISSUE TITLE
Compatibility Database

### ISSUE THREAD

**Issue by chris062689** [hrydgard/ppsspp#48]
Instead of using the forums as listing compatibility for each game, I can create a small PHP-based application that tracks compatibility between PPSSPP svn commits.

Users would search for the game, create a new test, enter information (what version, platform, etc) and list what works / doesn't work.
As well as the option to include a screenshot.

This would be very similar in vein to WineHqs appdb http://appdb.winehq.org 

I feel creating such a database will make it easier to keep track of test cases as well as regressions.

I will begin work on this and reply with a status update.  If others feel this is a good idea, or have suggestions, please feel free to comment.

**Comment by livisor** [comment]
I believe this project has been dropped(re-open if necessary). Closing

**Comment by unknownbrackets** [comment]
FWIW: http://report.ppsspp.org/games

Super basic but, data is reported firectly from within PPSSPP.

-[Unknown]
