### ISSUE TITLE
WWE All-Stars (ULUS10544) crashes when starting a fight on Windows (update: related to sceMPEG?)

### ISSUE THREAD

**Issue by thedax** [hrydgard/ppsspp#4808]
How to reproduce the crash (I think I'm the only contributor that has this game, but in any case):
1. Start the game in any PPSSPP revision since Fast Memory was turned on by default.
2. Go to Exhibition, Standard, 1 on 1, then pick whoever, and whatever stage you want (when I test I just use the defaults: Hogan, Cena, Smackdown arena).
3. Once the match cutscenes begin to play, just skip them with start.
4. On the next loading screen that actually heads into the match, the game will crash.

Here's a stack trace of the crash in interpreter mode (tested in v0.9.6-9-g9edf00e):

```
>	PPSSPPWindows64.exe!ReadVector(float * rd, VectorSize size, int reg) Line 101	C++
 	PPSSPPWindows64.exe!MIPSInt::Int_SVQ(Memory::Opcode op) Line 310	C++
 	PPSSPPWindows64.exe!MIPSInterpret_RunUntil(unsigned __int64 globalTicks) Line 1049	C++
 	PPSSPPWindows64.exe!EmuScreen::render() Line 577	C++
 	PPSSPPWindows64.exe!ScreenManager::render() Line 107	C++
 	PPSSPPWindows64.exe!NativeRender() Line 611	C++
 	PPSSPPWindows64.exe!Core_RunLoop() Line 168	C++
 	PPSSPPWindows64.exe!Core_Run() Line 215	C++
 	PPSSPPWindows64.exe!TheThread(void * __formal) Line 128	C++
```

No point posting a JIT stack trace when it only shows one jibberish entry. I know fast memory is "unstable", but if it produces a valid crash dump like this, maybe it's worth looking into?

**Comment by thedax** [comment]
Closing, this has long since been fixed.

**Comment by sum2012** [comment]
I test v1.0-80-ge89c881-windows-amd64
I still get Unknown GetPointer

11:39:269 DecodeXThrea E[MM]: MemmapFunctions.cpp:56 Unknown GetPointer 00000000 PC 08a89148 LR 08a89150

Info log:
https://gist.github.com/sum2012/57af2cb1f74884dcc0e7
Debug log:
https://drive.google.com/file/d/0B3OaSdeV0L8kQm50dGF0a3ZGUUU/view?usp=sharing

**Comment by thedax** [comment]
I do too, but it doesn't make the game crash.
