### ISSUE TITLE
Taiko DX (JP) Missing Text

### ISSUE THREAD

**Issue by skittyz321** [hrydgard/ppsspp#4836]
Happens in the mail
![screen00000](https://f.cloud.github.com/assets/4725578/1749835/da65a698-6545-11e3-85da-41a033bcb3ee.jpg)
and in the pause menu
![screen00001](https://f.cloud.github.com/assets/4725578/1749836/da660016-6545-11e3-8d51-a4df173b8c8e.jpg)

**Comment by unknownbrackets** [comment]
Has this changed at all with the new scaling of positions and the throughmode rounding change?  Try with hardware transform on and off.

-[Unknown]

**Comment by daniel229** [comment]
No change with hardware transform on or off.

**Comment by daniel229** [comment]
Fixed in https://github.com/hrydgard/ppsspp/pull/7920
