### ISSUE TITLE
Dante's Inferno - Graphics issue - Bloom

### ISSUE THREAD

**Issue by fastrizwaan** [hrydgard/ppsspp#4845]
The Game, Dante's inferno, plays fine but there's graphics issue:

The background seems to be mirrored in transparency, in the 1st screeshot, we can see the burning torches are shown, in the 2nd the "cross" on the wall is overlaid.

![screenshot from 2013-12-15 20 52 04](https://f.cloud.github.com/assets/1161682/1750553/b82993a8-659c-11e3-9fca-1b9fbe6356cd.png)
![screenshot from 2013-12-15 20 50 13](https://f.cloud.github.com/assets/1161682/1750554/bd3fd51e-659c-11e3-9f8d-22714892eea4.png)

Here's video too!
http://www.youtube.com/watch?v=AhJspRA6Og4

**Comment by ppmeis** [comment]
Tested with latest build. Same status.

**Comment by daniel229** [comment]
Missing bloom since https://github.com/hrydgard/ppsspp/pull/8130
![04](https://cloud.githubusercontent.com/assets/3481559/10901051/0a4f69b0-8223-11e5-9e33-397383536347.png)

**Comment by unknownbrackets** [comment]
I guess no bloom is better than wrong bloom, but it's still wrong.  What framebuf copies is this doing?  Same as [this logging](https://github.com/hrydgard/ppsspp/issues/7124#issuecomment-153236218).

-[Unknown]

**Comment by daniel229** [comment]
Log here
https://gist.github.com/daniel229/2448dc88c0397ced0037

**Comment by daniel229** [comment]
the incorrect bloom back since https://github.com/hrydgard/ppsspp/pull/8168

**Comment by unknownbrackets** [comment]
I wonder if this is somehow a stride issue.  Does the bloom seem to work (if anything works) in the softgpu?

-[Unknown]

**Comment by daniel229** [comment]
Yes,it works fine in softgpu.
![1](https://cloud.githubusercontent.com/assets/3481559/12603422/833e699a-c4ed-11e5-855f-a7f31c36fdf9.png)

**Comment by marosis** [comment]
In version 1.5.4 build 686 issue started

**Comment by marosis** [comment]
@Daniel 229 that Bloom is issue!

**Comment by Emulatorer** [comment]
The game is running smooth in Mali-T720 but sometimes there's a graphics issue (locking bloom) I need to savestates and then loadstates the graphics issue is gone so every time the graphics issue appears all I need to do is savestates and loadstates 😅 lol
Dantes Inferno Sample Gameplay
https://youtu.be/5FojzN_huJ0
Im using ppsspp buildbot 1.6.3-350

*sorry for my bad english 🙍

**Comment by Emulatorer** [comment]
![screenshot_2018-09-12-16-09-21](https://user-images.githubusercontent.com/37603562/45465872-bb02a680-b706-11e8-856a-c79aed874ff5.png)
Using ppsspp 1.6.3-445 
Mali-450 GPU

**Comment by Emulatorer** [comment]
Hoping this will fixed in ppsspp v2.0 😅

**Comment by Halo-Michael** [comment]
Still exists in v1.8.0

**Comment by hrydgard** [comment]
Could someone make a GE capture? See https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

Are the rainbow particles fixed?

**Comment by Halo-Michael** [comment]
> Could someone make a GE capture? See https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump
> 
> Are the rainbow particles fixed?

Here is the dump, hope it's helps.
Dumped from PPSSPP v1.8.0-112, from iPhone7(A10), iOS12.1.2 jailbroken device.
[ULES01384_0001.zip](https://github.com/hrydgard/ppsspp/files/3109272/ULES01384_0001.zip)

**Comment by Emulatorer** [comment]
Rainbow Particles still present in my Android Phone :(

**Comment by PilipinoAko** [comment]
This bug Have solution or MAKE A CHEAT TO REMOVE the glowing artifacts

**Comment by Emulatorer** [comment]
@PilipinoAko the only way you can play Dante's Inferno if your phone does support Vulkan this graphics bugs only present in OpenGL

**Comment by PilipinoAko** [comment]
Im no t u s i n g v u l k a n g p u
Im open gl DIO

**Comment by Halo-Michael** [comment]
> @PilipinoAko the only way you can play Dante's Inferno if your phone does support Vulkan this graphics bugs only present in OpenGL

On iOS, only OpenGL can be used

**Comment by PilipinoAko** [comment]
Hu hu Zuwardo will do cheat to remove the bugg tama yan

**Comment by Emulatorer** [comment]
@PilipinoAko who is Hu hu Zuwardo? He's making a cheat to fix this graphics glitches?

**Comment by PilipinoAko** [comment]
No thats is jojo bizzare line
Its need to remove the grapichs glich because ineed to play that without
Glowing grapics like GOW ITS NEED SKIP BUFFERD OR NEED TO FIX OR NEED
CHEATS

**Comment by PilipinoAko** [comment]
Aez TY channel is use full 
How date can you relaese the V2 ppsspp
Still waiting for updates

**Comment by Saramagrean** [comment]
Temporary fix: Use PPSSPP v1.7.1 Build 171 and enable BlockTransferCreateFB can play game full speed without lacking bloom. :)  (after v1.7.1 Build 181 this solution isn't work) 

![Screenshot_PPSSPP_20190712-025610](https://user-images.githubusercontent.com/26355472/61083325-a2ae0600-a455-11e9-9e83-86879067f2b3.png)

**Comment by Emulatorer** [comment]
@Saramagrean Can I know what's your phone hardware specifications??..

**Comment by Emulatorer** [comment]
This commit of sir @Hrydgard 442b570 has a fixed of Dantes Inferno @Saramagrean? 🤔
Can you give me the apk link seems that I can't connect right now in ppsspp buildbot 😔

**Comment by Saramagrean** [comment]
> @Saramagrean Can I know what's your phone hardware specifications??..

Huawei P9 Plus.

**Comment by Saramagrean** [comment]
> This commit of sir @hrydgard [442b570](https://github.com/hrydgard/ppsspp/commit/442b57033ff1e4aed602d954c61ed0b9b28ded3e) has a fixed of Dantes Inferno @Saramagrean? 🤔

I don't think so...

**Comment by Emulatorer** [comment]
Still the same in my phone (arm32/Mali-450/OpenGL)
### PPSSPP v1.7.1-171
![Screenshot_2019-07-12-14-00-54](https://user-images.githubusercontent.com/37603562/61107173-d4ed5100-a4b1-11e9-94d8-424f13e9b2eb.png)
![Screenshot_2019-07-12-14-18-00](https://user-images.githubusercontent.com/37603562/61107180-dc145f00-a4b1-11e9-839c-d85aa16399f2.png)
Locking bloom effects is worst in ppsspp last build v1.8.0-407 the game is super lag also 😔 
![Screenshot_2019-07-12-14-00-39](https://user-images.githubusercontent.com/37603562/61107278-24cc1800-a4b2-11e9-8b83-81075f4b79df.png)

**Comment by Saramagrean** [comment]
@Emulatorer ...with enabled BlockTransferAllowCreatdFB in compat.ini file?

**Comment by Emulatorer** [comment]
@Saramagrean Yes
![Screenshot](https://user-images.githubusercontent.com/37603562/61119379-45559b80-a4cd-11e9-9396-ad528b0d1e78.png)

**Comment by Emulatorer** [comment]
But it's ok now I just need to enable other speed up in graphics settings also I use force 30fps to make this game playable on my potato phone 😌
![Screenshot_2019-07-12-17-38-26](https://user-images.githubusercontent.com/37603562/61119518-8fd71800-a4cd-11e9-8d22-29c49500fdac.png)
![Screenshot_2019-07-12-17-37-51](https://user-images.githubusercontent.com/37603562/61119526-98c7e980-a4cd-11e9-92fc-d33b339a4458.png)
I will play this game for a while and see if the locking bloom effects will show or not until I finish this game :)

**Comment by Emulatorer** [comment]
@Saramagrean sad to say issue still persist in some area 🤷😔

**Comment by Levan7** [comment]
Still an issue on PC v1.8.0-414-g27608349e

**Comment by PilipinoAko** [comment]
How did you do that wow

**Comment by PilipinoAko** [comment]
This gloom is the one of the bug can't fix but in soft gpu can play it normal in open gl still not playable i hope can fix it

**Comment by Emulatorer** [comment]
### PPSSPPv1.9.3-465
![Screenshot_20200311-213236](https://user-images.githubusercontent.com/37603562/76422354-05d6aa80-63e0-11ea-8216-3b7d0b9018ca.png)

Can this issue label as GE Emulation or Opengl?, since this issue is a backend dependant. Some of my friends can play this without locking bloom effects using Vulkan backend in their android phones

**Comment by Emulatorer** [comment]
### GOOD NEWS!!!
No locking bloom effects on my tablet w/ mali-t720 gpu ogl 3.1 but still has a graphics issue though 😅
![Screenshot_20200311-230523](https://user-images.githubusercontent.com/37603562/76475752-e6b93680-643a-11ea-9f3e-781018296bf8.png)
![Screenshot_20200311-230743](https://user-images.githubusercontent.com/37603562/76475755-e91b9080-643a-11ea-8080-f51aa97546c2.png)
![Screenshot_20200311-230817](https://user-images.githubusercontent.com/37603562/76475759-eb7dea80-643a-11ea-8252-a2a5dffc9b03.png)
![Screenshot_20200311-230946](https://user-images.githubusercontent.com/37603562/76475760-ee78db00-643a-11ea-9440-25ac2be63531.png)

**Comment by Emulatorer** [comment]
### update
No locking bloom effects in OGL 3.1+ but characters image is transparent.

No changes in OGL 2.0+ this game always locking bloom effects so no chance for my phone w/ mali-450 gpu to play this game 😶

**Comment by Gamemulatorer** [comment]
> Here is the dump, hope it's helps.
> Dumped from PPSSPP v1.8.0-112, from iPhone7(A10), iOS12.1.2 jailbroken device.
> [ULES01384_0001.zip](https://github.com/hrydgard/ppsspp/files/3109272/ULES01384_0001.zip)

Using the dump above.
### HW rendering
![Screenshot_20200604-172317HW](https://user-images.githubusercontent.com/37603562/83739614-68aaab80-a688-11ea-864e-3dda7341594f.png)
### SW rendering
![Screenshot_20200604-172253SW](https://user-images.githubusercontent.com/37603562/83739646-74966d80-a688-11ea-853f-a68d15c46f11.png)

**Comment by Halo-Michael** [comment]
This is the graphical performance of ULES01384_1.00 in v1.9.3-975-g6f07e2b48 (A ppdmp file, and a screen recording file):
https://github.com/Halo-Michael/PPSSPP-ULES01384_0001
Dumped from SE2(A13) iOS13.5 jailbroken with Unc0ver.

**Comment by hrydgard** [comment]
Started looking into this (in the the Vulkan backend, using the GE debugger and RenderDoc)

The game does a fairly traditional bloom where you subtract some brightness from the game image, blurring that, and adding the result on top of the original image. It does this initial step by first drawing a gray rectangle, then using SUBTRACT blending. Unfortunately that gray clear malfunctions somehow and only clears the upper half of the image, leaving garbage from the previous frame behind. This garbage being subtracted from the previous frame's garbage causes the flickering. It seems a scissor rectangle cuts off the bottom part of the clearing draw.

Apart from that, the bloom effect seems to work ok now.

**Comment by hrydgard** [comment]
The remaining bloom flicker is now fixed.

**Comment by Panderner** [comment]
Good Job @hrydgard
![Screenshot_2020-08-07-09-39-37-30_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/89599404-0e011c00-d892-11ea-9cca-452ad9724801.png)
but this game needs to be set to buffered rendering

**Comment by hrydgard** [comment]
Yup, no way getting around that, I think.
