### ISSUE TITLE
Feature Request: Auto hide on screen controls?

### ISSUE THREAD

**Issue by bollu** [hrydgard/ppsspp#4855]
Would anyone be interested if the on-screen controls fade away after like 10 seconds or so of non-interaction? IMHO, It would make watching cutscenes way more enjoyable, but I want your opinion of it.

Thanks!

EDIT - is it I ```want your opinion of it.``` or ```want your opinion on it.```? (English is not my first language :) )

**Comment by ppmeis** [comment]
@hrydgard any interest about this? I think is not very usefull. Also we can config now opacity under screen control options.
