### ISSUE TITLE
Pursuit Force - Extreme Justice (bezier/spline with < 4 uv counts)

### ISSUE THREAD

**Issue by fastrizwaan** [hrydgard/ppsspp#4888]
As soon as we enter the Tunnel, the ppsspp crashes. Crash happens in Windows 32bit, Linux SDL and Qt versions.

![screenshot from 2013-12-20 23 27 30](https://f.cloud.github.com/assets/1161682/1792484/42228022-69a0-11e3-9a25-1466e8585276.png)

As per this post, version 0.9.1 did not crash but crashes in later versions.
http://forums.ppsspp.org/showthread.php?tid=371&pid=57578#pid57578

Kindly look into the issue, it's a fun action game.

Actual PSP gameplay:
http://www.youtube.com/watch?v=ysDMU-NFpoY&t=1m23s

**Comment by unknownbrackets** [comment]
It seems from my testing that 1x7 and similar doesn't draw anything.

Does this game still work fine without crashing with the latest code?  Any visible graphical issues?  If it's working, I think we're safe to close this.

-[Unknown]

**Comment by daniel229** [comment]
Everything still looks fine with master build.
