### ISSUE TITLE
MotoGP - halo effect - Android (texture coord / prescale)

### ISSUE THREAD

**Issue by ppsspp213** [hrydgard/ppsspp#4889]
Every so often when passing other bikers they have a white halo surrounding them, this might be a glitch related to showing the biker names, it only happens now and again though not for every biker you pass.

http://i44.tinypic.com/mc92mr.jpg

**Comment by ppmeis** [comment]
Tested with latest build. It works fine for me:
![image](https://cloud.githubusercontent.com/assets/4381277/5994495/5a4a8ff6-aa76-11e4-89c0-93f66227ba94.png)

**Comment by unknownbrackets** [comment]
This is wiht the texture coord hack on, right?  If it works on Windows it probably is good, then.

-[Unknown]

**Comment by ppmeis** [comment]
@unknownbrackets yes it is.
