### ISSUE TITLE
Hajime no Ippo Portable : Victorious Spirits - Sound and BGM issue

### ISSUE THREAD

**Issue by LosBadylos** [hrydgard/ppsspp#4894]
BGM in this game always suddenly stops playing during a fight, same happens to the sound effects like the crowd or the punches. Sometimes, or even most of the time, the music doesn't even start at all. It's a problem that has been there ever since the game started to work (few good months). I was testing the latest SVN, v0.9.6-160

**Comment by unknownbrackets** [comment]
Has this improved at all, or is it still happening?

-[Unknown]

**Comment by daniel229** [comment]
sound effects seem no problem, BGM is still stopped

**Comment by unknownbrackets** [comment]
Hmm.  Is it atrac?  Maybe a log would say something interesting.

-[Unknown]

**Comment by daniel229** [comment]
debuglog with enable Masterlog sceAudio Media Engine and HLE.
rename(jpg to 7z)
![ppsspplog 2](https://cloud.githubusercontent.com/assets/3481559/5810818/882c0d4e-a087-11e4-93cc-135ef83377d9.jpg)

**Comment by unknownbrackets** [comment]
Hmm, I didn't notice anything obvious... what about sceSas also (keep sceAudio and sceAtrac)?  I couldn't tell if it was actually mixing the audio, but I do see it decoding and then outputting something else that was probably mixed by sceSas.

-[Unknown]

**Comment by daniel229** [comment]
I don't see sceAtrac channel.

**Comment by unknownbrackets** [comment]
Oh sorry, I meant ME, as you had before.  Just also sceSas.

-[Unknown]

**Comment by daniel229** [comment]
Here it is
![ppsspplog](https://cloud.githubusercontent.com/assets/3481559/5811638/f0cfc48c-a094-11e4-9144-06988ed6bc21.jpg)

**Comment by unknownbrackets** [comment]
Hmm.  If you set a memory breakpoint at 08abf900, is it writing there via code or something?

It atrac decodes to 08abbda0, and sas mixes to 08ac4940.  sceAudio channel 4 is used for sas, so presumably channel 5 ought to be background music.  But it plays 08abf900 for channel 5, so presumably it must be filling that from somewhere else (maybe it's a buffer it means to collect sceAtrac decodes into?)

-[Unknown]

**Comment by daniel229** [comment]
Is it like this?
![01](https://cloud.githubusercontent.com/assets/3481559/5811820/cc8b3536-a097-11e4-9d35-ac730b3a077d.png)

**Comment by unknownbrackets** [comment]
Hmm, seems like that was a memset probably, does it break any more times after that?

-[Unknown]

**Comment by daniel229** [comment]
No break more after that.

**Comment by unknownbrackets** [comment]
Have any of the sceAtrac changes had any impact here?

-[Unknown]

**Comment by daniel229** [comment]
No.

**Comment by daniel229** [comment]
Freezing and music cut off fixed by https://github.com/hrydgard/ppsspp/pull/8782
