### ISSUE TITLE
UI suggestion: replace "Home" text on a button with an icon

### ISSUE THREAD

**Issue by adrian17** [hrydgard/ppsspp#4936]
Currently, the text can easily overlap the path, especially with some longer translations:

![be3vxkn](https://f.cloud.github.com/assets/4729533/1819702/a115e9fe-70ab-11e3-8f2d-124991cfab97.jpg)

It's possible to save a little bit of space if a home icon was used instead of text - like here:

![qlzn992](https://f.cloud.github.com/assets/4729533/1819704/a7709fb0-70ab-11e3-8929-01d2d827819c.jpg)

**Comment by unknownbrackets** [comment]
It'd be nice to have a thumbtack + and thumbtack - button too.  You don't want me to draw them, trust me, unless you have guaze prepared for your eyes.

-[Unknown]

**Comment by unknownbrackets** [comment]
This was implemented in #13885.

-[Unknown]
