### ISSUE TITLE
PPSSPP now crashing whenever I load any game (ATI OpenGL 2.0)

### ISSUE THREAD

**Issue by mr-chya** [hrydgard/ppsspp#4956]
So I hadn't updated the latest version of PPSSPP in a few weeks and decided to give it a try a few minutes ago only to have it crash on me every time I load any game. So after going through the different versions on the build bot I discovered the last one to work correctly for me was ppsspp-v0.9.6-210-g22b859a windowsx64 and the first broken one is the next one available ppsspp-v0.9.6-219-gc277fe3

My specs
![screen00007](https://f.cloud.github.com/assets/5421237/1828074/6e88911a-724c-11e3-8b9d-babcaac521dd.jpg)

and the a log file from 0.9.6-219
51:36:094 EmuThread.cpp:113 I[BOOT]: Done.
51:45:519 System.cpp:297 I[BOOT]: PPSSPP v0.9.6-219-gc277fe3
51:45:523 MemMap.cpp:126 I[MM]: Memory system initialized. RAM at 000000000C310000 (mirror at 0 @ 0000000087FF0000, uncached @ 00000000C7FF0000)
51:45:579 PSPLoaders.cpp:118 I[LOAD]: ULUS10396 : Class of Heroes
51:45:580 PSPLoaders.cpp:188 I[LOAD]: Loading disc0:/PSP_GAME/SYSDIR/EBOOT.BIN...
51:45:580 HLE\sceKernelMemory.cpp:213 I[KERNEL]: Kernel and user memory pools initialized
51:45:658 HLE\sceKernel.cpp:142 I[KERNEL]: Kernel initialized.
51:45:823 Util\BlockAllocator.cpp:379 I[HLE]: -----------
51:45:824 Util\BlockAllocator.cpp:383 I[HLE]: Block: 08800000 - 08804000 size 00004000 taken=0 tag=(untitled)
51:45:824 Util\BlockAllocator.cpp:383 I[HLE]: Block: 08804000 - 09c16e00 size 01412e00 taken=1 tag=ELF
51:45:824 Util\BlockAllocator.cpp:383 I[HLE]: Block: 09c16e00 - 0c000000 size 023e9200 taken=0 tag=(untitled)
51:45:824 Util\BlockAllocator.cpp:385 I[HLE]: -----------
51:45:890 HLE\sceKernelModule.cpp:835 I[LOAD]: Module TTM01_OS: 00000000 0899dd48 0899dd60
51:45:891 HLE\sceKernelModule.cpp:1033 I[LOAD]: Exporting ent 0 named TTM01_OS, 2 funcs, 4 vars, resident 0899e14c
51:45:892 HLE\sceKernelModule.cpp:1318 I[LOAD]: Module entry: 088e9938
51:45:926 root         N[BOOT]: EmuScreen.cpp:111 Loading C:/Users/Dale/Desktop/Me Folder/PSP ISO/Class_Of_Heroes_USA/psy-cohu.iso...
51:45:927 root         I[KERNEL]: HLE\sceKernelThread.cpp:2110 276=sceKernelCreateThread(name=user_main, entry=088e9a4c, prio=20, stacksize=262144)
51:45:927 root         I[KERNEL]: HLE\sceKernelThread.cpp:2161 sceKernelStartThread(thread=276, argSize=33, argPtr=0bfffed0)
51:45:927 root         I[KERNEL]: HLE\sceKernelThread.cpp:2241 __KernelReturnFromThread: 0
51:45:961 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2110 278=sceKernelCreateThread(name=HomePowerCB, entry=08886fc8, prio=1f, stacksize=32768)
51:45:961 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2161 sceKernelStartThread(thread=278, argSize=0, argPtr=00000000)
51:45:963 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2110 282=sceKernelCreateThread(name=Thread, entry=0880a4f4, prio=10, stacksize=32768)
51:45:963 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2161 sceKernelStartThread(thread=282, argSize=4, argPtr=0bfff610)
51:45:963 user_main    I[MODULE]: HLE\sceKernelModule.cpp:701 ~SCE module, skipping header
51:45:963 user_main    I[HLE]: ELF\PrxDecrypter.cpp:299 Missing key 5B, cannot decrypt module
51:45:963 user_main    I[MODULE]: HLE\sceKernelModule.cpp:1457 283=sceKernelLoadModule(name=disc0:/PSP_GAME/USRDIR/CDModules/libfont.prx,flag=00000000,00000014,00000002,00000002,position = 00000000)
51:45:964 user_main    I[MODULE]: HLE\sceKernelModule.cpp:1490 sceKernelStartModule(283,asize=00000000,aptr=00000000,retptr=0bfff630,00000000): faked (undecryptable module)
51:45:980 user_main    I[SCEGE]: GLES\Framebuffer.cpp:778 Creating FBO for 00000000 : 480 x 272 x 1
51:45:987 user_main    I[G3D]: GLES\ShaderManager.cpp:145 Linked shader: vs 13 fs 14
51:45:993 user_main    I[UTIL]: HLE\sceUtility.cpp:210 sceUtilityLoadModule(769)
51:46:005 user_main    I[UTIL]: HLE\sceUtility.cpp:210 sceUtilityLoadModule(768)
51:46:010 user_main    I[UTIL]: HLE\sceUtility.cpp:210 sceUtilityLoadModule(770)
51:46:041 user_main    I[UTIL]: HLE\sceUtility.cpp:210 sceUtilityLoadModule(771)
51:46:090 user_main    I[SCEGE]: GLES\Framebuffer.cpp:778 Creating FBO for 00044000 : 480 x 272 x 1
51:46:111 user_main    I[HLE]: HLE\scePower.cpp:345 scePowerSetClockFrequency(333,333,166)
51:46:184 user_main    I[SCESAS]: HLE\sceSas.cpp:99 sceSasInit(09b31980, 256, 32, 0, 44100)
51:46:185 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2110 296=sceKernelCreateThread(name=FMOD SAS update/mix thread, entry=08912fec, prio=8, stacksize=65536)
51:46:185 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2161 sceKernelStartThread(thread=296, argSize=12, argPtr=09368090)
51:46:191 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2110 305=sceKernelCreateThread(name=FMOD stream thread, entry=08912fec, prio=c, stacksize=16384)
51:46:194 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2161 sceKernelStartThread(thread=305, argSize=12, argPtr=0939d6d0)
51:46:196 user_main    I[ME]: HLE\sceAtrac.cpp:1374 sceAtracReinit(0, 3)
51:46:247 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2110 308=sceKernelCreateThread(name=TaskThread, entry=088baaf8, prio=3c, stacksize=20480)
51:46:247 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2161 sceKernelStartThread(thread=308, argSize=0, argPtr=00000000)
51:46:248 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2110 309=sceKernelCreateThread(name=TaskThread, entry=088ac338, prio=3e, stacksize=3072)
51:46:248 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2161 sceKernelStartThread(thread=309, argSize=0, argPtr=00000000)
51:46:261 user_main    I[G3D]: GLES\ShaderManager.cpp:145 Linked shader: vs 16 fs 17
51:46:327 user_main    I[G3D]: GLES\ShaderManager.cpp:145 Linked shader: vs 16 fs 14
51:46:565 TaskThread   I[UTIL]: Dialog\PSPSaveDialog.cpp:58 sceUtilitySavedataInitStart(09d1a320) : Mode = 11
51:46:565 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2425 sceKernelTerminateThread(309)
51:46:736 TaskThread   I[UTIL]: Dialog\PSPSaveDialog.cpp:58 sceUtilitySavedataInitStart(09d1a320) : Mode = 22
51:46:940 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2110 409=sceKernelCreateThread(name=TaskThread, entry=088ac338, prio=3e, stacksize=3072)
51:46:940 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2161 sceKernelStartThread(thread=409, argSize=0, argPtr=00000000)
51:47:136 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2425 sceKernelTerminateThread(409)
51:47:175 user_main    I[G3D]: GLES\ShaderManager.cpp:145 Linked shader: vs 16 fs 20
51:47:194 user_main    I[G3D]: GLES\ShaderManager.cpp:145 Linked shader: vs 22 fs 23

**Comment by unknownbrackets** [comment]
Should we still try to do something about this?  Maybe Direct3D covers it, at least to some degree?

-[Unknown]

**Comment by hrydgard** [comment]
Eh, for this old hardware Direct3D will have to do. Closing.
