### ISSUE TITLE
Lororoco 2's cutscenes don't play, although the audio works fine

### ISSUE THREAD

**Issue by DrewMathew** [hrydgard/ppsspp#4979]
![screenhunter_151 jan 02 12 26 2](https://f.cloud.github.com/assets/6305077/1833932/44592e80-73d3-11e3-8e68-147b09c2be6c.jpg)

**Comment by ppmeis** [comment]
Tested with latest build. Same status. Degublog while blackscreen:
![image](https://cloud.githubusercontent.com/assets/4381277/8891513/5dfc663e-332d-11e5-8e23-d43bf468fc9f.png)

**Comment by hrydgard** [comment]
This was fixed (in a rather hacky way but still) a long time ago, closing.
