### ISSUE TITLE
PPSSPPSDL - needs Toggle Fullscreen Shortcut 

### ISSUE THREAD

**Issue by fastrizwaan** [hrydgard/ppsspp#4981]
SDL version is almost complete,  the only missing piece is Fullscreen toggle feature. Save and Load also work great, just a toggle fullscreen will make it extremely useful.

Please consider adding "Toggle Fullscreen" Shortcut in SDL version - say F11. 

Starting with --fullscreen will not let us toggle to window or 2x mode.

Advantages:
1. Overcome Hangup: In Linux, if SDL hangs in fullscreen we can't do anything except to reset the computer :(, so switching to window mode would make the system shortcuts work again.
1. Sound Quality: SDL version has better quality sound, qt4 and qt5 both are not good with sound quality.
2. Autobuild becomes useful: auto build git version for linux only builds SDL, so SDL could be used easily by every linux distro easily, without needing Qt libraries.

Thanks.

**Comment by unknownbrackets** [comment]
Is this possible now that SDL2 is being used?

https://wiki.libsdl.org/SDL_SetWindowFullscreen

Anyone want to open a pull request?

-[Unknown]

**Comment by asl97** [comment]
The option to set it in the control mapping exists.
iirc, it isn't set by default.
