### ISSUE TITLE
UMD seek delay isn't emulated at all, causing some games not to boot

### ISSUE THREAD

**Issue by thedax** [hrydgard/ppsspp#4996]
This is a continuation of the discussion in https://github.com/hrydgard/ppsspp/pull/4887.

Some versions of Pangya: Fantasy Golf don't boot, but instead hang forever with sceKernelStopUnloadSelfModuleWithStatus.

What we know so far:
1. If sceIoRead's delay is increased to 19,999 microseconds or later (no less, else it won't boot, at all), the game will boot fine.
2. It could be a possible threading or schedule issue, where things aren't being ran at the expected time, so the game freaks and dies.
3. [Unknown's initial UMD seek delay emulation](https://github.com/unknownbrackets/ppsspp/tree/io-minor2) did seem to help, but broke other games (notably, Jeanne D'Arc's videos stopped playing IIRC), so it wasn't merged.

**Comment by unknownbrackets** [comment]
This is somewhat supported now with an option, though it's not perfect.  Should we keep this open?

-[Unknown]

**Comment by thedax** [comment]
I'll close this, the ISO I have of Pangya that exhibits the problem boots fine when the UMD seek delay is being used. I'll make a note of it in my Pangya thread on the forum, if nobody else has.

**Comment by unknownbrackets** [comment]
Cool.  It still needs work but apparently it helps other games too... Gotta figure out a good compromise because it breaks a few games also.

Long time no see.  Hope things are going well.

-[Unknown]

**Comment by thedax** [comment]
Likewise. I've been messing with 3DS homebrew lately, so I more or less vanished from the PSP scene..it looks like I've missed a hell of a lot since then.
