### ISSUE TITLE
DTM Race Driver 3; Toca 2 Graphic Problems

### ISSUE THREAD

**Issue by zschigi2** [hrydgard/ppsspp#5001]
in DTM Race Driver 3 and Toca 2 there are massive Graphic Problems ingame

(some kind of scan lines over the game-graphics)

**Comment by ppmeis** [comment]
Tested in latest build. Same status:
![image](https://cloud.githubusercontent.com/assets/4381277/8891522/f10e8cd6-332d-11e5-8ad6-a56093e1c935.png)

**Comment by ppmeis** [comment]
Tested with latest build. Same status.

**Comment by unknownbrackets** [comment]
Are you able to capture when the GE debugger's red overlaps with one of the red lines specifically (e.g. not just the full screen, but is only over the black line, or right at the black line?)

The earlier screenshot looks like a clear and is probably not related.

-[Unknown]

**Comment by hrydgard** [comment]
Probably broken geometry that gets discarded by the real PSP because the coordinates are way outside the guardband, and the PSP doesn't do proper triangle clipping. I'll send a pull request later with an experimental fix for D3D11 but it relies on undefined behaviour in vertex shaders to kill triangles, which isn't very nice. A "correct" fix will need geometry shaders.

**Comment by LunaMoo** [comment]
Works fine on windows at least, so that report might be another one from android where it might not had enough vertex registers or that's how the "optimization" fixing other games mentioned there is working aka it might be completely disabling the guardband fix.;]

**Comment by marosis** [comment]
It is working right on every backend? I tested it on OpenGL on android and it is not working for me

**Comment by marosis** [comment]
![screenshot_20180928-111700](https://user-images.githubusercontent.com/33152267/46199811-43409880-c310-11e8-805a-816cd9c8127b.png)

**Comment by hrydgard** [comment]
@unknownbrackets  maybe it would help to set all four parts of the position vector to NaN, not just w...

**Comment by marosis** [comment]
Now i tested on latest build if i didn't get Wrong info and yeah STILL SAME status.

**Comment by hrydgard** [comment]
Thanks marosis. Stay tuned, I'm going to try my idea in the weekend.

**Comment by marosis** [comment]
I will

**Comment by unknownbrackets** [comment]
That sounds worth trying.  The cull distance extension isn't supported by much other than Adreno, so that probably won't help.

Maybe the other option is to try to set depth to a value that would be (mostly?) clipped and then also discard in the frag shader, but that sounds pretty awful...

-[Unknown]

**Comment by hrydgard** [comment]
On Mali, those issues are still there underneath even if you use earlier versions with the stripe bug, right? If so they are definitely a separate issue..

**Comment by Emulatorer** [comment]
PPSSPP 1.6.3 Playstore
![screenshot_2018-09-29-17-55-03](https://user-images.githubusercontent.com/37603562/46244398-06d37200-c3ce-11e8-8589-02d0f4bfb718.png)

Yeah separate issue..

**Comment by Emulatorer** [comment]
Upon testing in my brother phone Kata Selfie Mali-T720 GPU MT6753 Hardware
![screenshot_20181007-104423](https://user-images.githubusercontent.com/37603562/46577686-c67e8000-c9db-11e8-83c4-6ae8a2df5a22.png)

But in my Cloudfone Excite Prime Mali-450 MP GPU MT6592 Hardware it's fixed the only issue I have is the small black square that also exist in MH3RD HD :/
![screenshot_2018-10-07-10-42-06](https://user-images.githubusercontent.com/37603562/46577709-38ef6000-c9dc-11e8-8ee5-71ae10732432.png)

**Comment by unknownbrackets** [comment]
I suppose that means Mali-T7xx doesn't support what we're trying to do.  The weird things is the lines are pretty much the same, but maybe it's because they're all nan.

-[Unknown]

**Comment by MJH1000** [comment]
The game can be made playable using this cheat, 'Graphical glitches partial FIX'.

ULES00615.ini

```
_S ULES-00615
_G DTM Race Driver 3 Challenge [EUR]
_C0 Graphical glitches partial FIX
_L 0xE0018C84 0x000AB7BA
_L 0x200AB7B8 0x34040000
_C0 Graphical glitches NO-FIX [Default]
_L 0xE0013404 0x000AB7BA
_L 0x200AB7B8 0x8C840000
```

**Comment by marosis** [comment]
Please do from it for me File. I did TXT, paste code, saved, renamed to ini and it is not working

**Comment by marosis** [comment]
All cheats are working from PPSSPP forum but that your not.

**Comment by MJH1000** [comment]
The cheat does not remove all the graphics glitches, only the worst ones.

**Comment by marosis** [comment]
No. I mean i can't launch it. He is not showing in the emulator

**Comment by benderscruffy01** [comment]
can the label android be add as this doesnt happen on windows

**Comment by LunaMoo** [comment]
No, it will still happen on windows, the feature fixing this issue is disabled on old gpu's. not just mobiles.

**Comment by benderscruffy01** [comment]
ok thanks for that

**Comment by unknownbrackets** [comment]
Maybe it makes more sense to close this and create a new issue (maybe referencing a list of the affected games for searchability) about guard band not working on older devices.

I don't have an affected device currently (except Vivante which can't handle a lot...) but some ideas collected from above:

 * Perhaps set more components of the vert to NAN.
 * Perhaps set w to 0 instead.
 * Perhaps send an interpolated value to the frag shader, and discard when `> 0` (won't be perfect, but might be better... that said, speed penalty.)
 * Perhaps handle in software transform path?  Maybe bigger speed penalty, and would require non-default setting or something...

-[Unknown]

**Comment by Emulatorer** [comment]
@hrydgard Thanks finally its totally fuxed ^^
![Screenshot_20190809-223330](https://user-images.githubusercontent.com/37603562/62787171-bd2bdb80-baf6-11e9-86ec-3e3c55a48e46.png)
•Mali-T720 MT8163 Android Phone Tablet
