### ISSUE TITLE
PPSSPP cannot read the game title showing the filename instead under rare circumstances

### ISSUE THREAD

**Issue by pal1000** [hrydgard/ppsspp#5030]
![notitle](https://f.cloud.github.com/assets/1138235/1849564/58ae30f6-76b7-11e3-9706-b6264987bfc1.png)

Initial requirements: 
-have at least a game ISO or demo/homebrew that contains an internal name (ex. ProQuake) in memstick\PSP\GAME;
-wipe recent games list or remove ppsspp.ini (wiping recent games list is enough to reproduce). 
Steps to reproduce:
-Wait for a new revision (required, it doesn't reproduce if you rewind your current branch repository head);
-Launch PPSSPP from repository manually or from VS2013 (doesn't seam to matter, also doesn't matter if you build the new PPSSPP revision or not), switch to homebrew / demos tab and witness the issue (PPSSPP will show the filename of the ISO file instead of it's internal name). 

Workarounds: Switch homebrew/demos to grid view and back to list view or restart PPSSPP.
Moving the executable. assets, flash0, lang and memstick folders to another location doesn't help.
Issue reproducing is certain for 32-bit Windows.
As per @ufdada's suggestion, here is a screenshot of the game details (the information is exact, but if I click 'Back' I get back to the state from screenshot above):   
![screen00000](https://f.cloud.github.com/assets/1138235/1851163/fdeb2890-76e3-11e3-8506-57eb5ecd8f62.jpg)

**Comment by unknownbrackets** [comment]
How many do you have to get to make it happen?  I'm pretty sure I have not seen this occur in quite a while, or possibly I've never seen it occur.

-[Unknown]

**Comment by daniel229** [comment]
Still happen.it's easy to reproduce,
Reset computer,then open ppsspp.exe and click games tab, and maybe need to scoll down.
