### ISSUE TITLE
SOCOM Tactical Strike fade effect issue

### ISSUE THREAD

**Issue by stranno** [hrydgard/ppsspp#5074]
Everything seems to work ok except the green/blue glow around the characters edge when you switch teams or give an order. Instead of glowing edge, entire screen glow for a second.

Buffer rendered. Non-buffered just dont show the glow at all.

Here's what happend.

![image](https://f.cloud.github.com/assets/6293197/1892632/9c46f5c2-7a55-11e3-8039-1ea46c32c533.png)

![image](https://f.cloud.github.com/assets/6293197/1892633/a1d80bc0-7a55-11e3-88dc-c30d2873cc60.png)

And here is what it should look like.

http://www.youtube.com/watch?v=1DeX6_vvgLw

**Comment by unknownbrackets** [comment]
I'm not sure what's going wrong here if it even doesn't work in the software renderer...

can you try catching this with the GE debugger?  I want the prim (red highlight) right before the green glow shows up, and all the tabs as well.

-[Unknown]

**Comment by daniel229** [comment]
![02](https://cloud.githubusercontent.com/assets/3481559/6438150/87d46c34-c101-11e4-82a7-b4fd5d38396d.png)

Before it turn green
GE debugger
![01](https://cloud.githubusercontent.com/assets/3481559/6438143/7d253a16-c101-11e4-89f2-4a26d2fc7ec9.png)

more tabs
https://gist.github.com/daniel229/de574c4283005154a317

**Comment by unknownbrackets** [comment]
Hmm, it's doing a fixed additive blend.  I'm not sure why that wouldn't work in software rendering or in OpenGL...

-[Unknown]

**Comment by unknownbrackets** [comment]
Well, the source texture is 040dc000.  I wonder if this is actually a stencil issue - maybe the a is wrong/incorrect.

Is this still wrong in software rendering?

-[Unknown]

**Comment by daniel229** [comment]
software rendering is still wrong.
![04](https://cloud.githubusercontent.com/assets/3481559/11933761/bd2eebce-a838-11e5-918c-e1499fe0d8d8.png)

**Comment by unknownbrackets** [comment]
I'm not sure if it will help in this case, but could you try exporting a GE frame dump?

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by benderscruffy** [comment]
this can be closed
software rendering works properly

**Comment by unknownbrackets** [comment]
Sweet.  Thanks for reporting.

-[Unknown]

**Comment by hrydgard** [comment]
Wait, what about the hardware renderers? Did it start working on those too?

**Comment by ppmeis** [comment]
Tested in latest Windows Build under Vulkan API, it seems to works fine:
![image](https://user-images.githubusercontent.com/4381277/71818459-57358700-3089-11ea-92ac-b3002d8bf1ad.png)

**Comment by hrydgard** [comment]
Thanks!
