### ISSUE TITLE
Hatsune Miku Project Diva Extend lag

### ISSUE THREAD

**Issue by 716Girl** [hrydgard/ppsspp#5105]
Well, when i'm pressing buttons it reacts only after some pause, and sometimes its just impossible to play.

**Comment by unknownbrackets** [comment]
Apparently increasing monitor refresh rate to 75 Hz can improve this for some people (this implies it's related to vsync.)  If you're using an LCD, I recommend always using 75 Hz, it's just better and its what I have always used.

I know that the WASAPI change also improved things for some users, and we've done a lot of work to try to improve the timing here.

I'm going to close this for lack of feedback and based on the above.

-[Unknown]

**Comment by hrydgard** [comment]
I don't know about 75 hz, I would still stick to 60hz for emulation, but whatever floats your boat :)

**Comment by GamerzHell9137** [comment]
Something's been changed in the new revisions.
The difference is visible btw 1405 and 1582. Played with default settings, no force lag sync and on 60H, Sync off. Simultaneously played same songs and the input feels smoother and faster on 1582 build. After that i changed to 75Hz and there's a difference in input in a good way in both revisions, same settings applied.

Only thing with the 1582 revision is that there are some stutters during the song and it seems like the music quality is lowered. Like somethings wrong with the SFX sounds.

**Comment by GamerzHell9137** [comment]
Cross that sound issues, it could be just me. Minor stutters are real thou, i guess something in the new revision was changed to trigger it(more I/O readings?)

**Comment by hrydgard** [comment]
The new resampler might very slightly muddy the sound. I will look into using a better quality filter (sinc or biquad or something) later. Worth it anyway for the decreased audio latency.

As for stuttering, no idea - did you turn up texture scaling too high or something?

**Comment by GamerzHell9137** [comment]
Scratch that, could be that my PC was doing something at the time, but yeah, the music sounds garbage-y.

**Comment by GamerzHell9137** [comment]
The input has been impacted again.
It got worse on 1599 revision and feels slower than on 1582.
And i've seen the new audio backend option but it didn't make much difference for me.
Have tried them both and still weren't as good as 1582 revision.
On both revisions real clock sync was forced and have been played on 75Hz monitor settings.

**Comment by hrydgard** [comment]
Nothing has changed in that range with regards to input or audio except in 1593 where I added a choice between WASAPI and DirectSound. Choose WASAPI or auto (will be wasapi on winver >= vista)

**Comment by GamerzHell9137** [comment]
This is confusing me thou. Playing simultaneously and getting different results.

WASAPI
![ss 2015-01-25 at 02 40 27](https://cloud.githubusercontent.com/assets/2002038/5889843/bed689e8-a43b-11e4-931d-5380d3eff5d8.png)

DirectSound
![ss 2015-01-25 at 02 45 53](https://cloud.githubusercontent.com/assets/2002038/5889848/685757c2-a43c-11e4-88de-598c02a7ee98.png)

DirectSound is more precise i guess but its still different.

**Comment by GamerzHell9137** [comment]
The music still sounds distorted so what i did is record it on 0.9.9.1 stock version and the new revision and it seems that the music is a bit louder on the newer version.

![ss 2015-01-26 at 11 06 38](https://cloud.githubusercontent.com/assets/2002038/5909383/631985ee-a5b0-11e4-8d97-9e060fe667d3.png)

Track 2 is 0.9.9.1
Track 1 is the new revisions of it
As you can see the volume bars below on Track 1 are more up than on Track 1,meaning that the sound is actually louder on the new revisions.

**Comment by hrydgard** [comment]
That's ... unexpected. Does that loudness effect remain if you switch back to DirectSound using the new option?

**Comment by GamerzHell9137** [comment]
Its already on DirectSound but iirc it sounds the same on both WASAPI and DirectSound.

**Comment by GamerzHell9137** [comment]
Here's an example.

https://www.youtube.com/watch?v=AH2WJOT26fM&feature=youtu.be

**Comment by hrydgard** [comment]
Thanks. I have a hard time hearing any loudness difference but there seems to be some kind of difference and maybe little glitches. The resampling may introduce a little roughness but the point is to reduce latency and glitches, not increase them, so I'm at a loss to explain it... :(

**Comment by GamerzHell9137** [comment]
I see, so is there a way to fix it without making latency?

**Comment by hrydgard** [comment]
I could try adding an option to turn the resampler off and just copy audio samples like before, but the point of it is to allow the latency to gradually drift to some kind of short sweet spot, and that isn't possible without it. I'll add it as an experiment later this week..

**Comment by daniel229** [comment]
Resampler make buzz noise occasionally in many gemes,it's good there is a option to turn off it.

**Comment by GamerzHell9137** [comment]
I've tested it.
Resampling lowers the quality but it syncs the music better, like you said hrydgard.
Disabling it makes the music better but it doesn't sync right with the input.

Ohh and should i make a new issues about the 60vs75Hz thing? Still playing on 75Hz is better than on 60.
