### ISSUE TITLE
Hajime no Ippo Portable can't save and dialogue issue

### ISSUE THREAD

**Issue by 716Girl** [hrydgard/ppsspp#5157]
After battle there is dialogues and sprites, background are not shown only text.
![screen00001](https://f.cloud.github.com/assets/6298017/1952143/3c12c938-819e-11e3-9726-46683656e7ef.jpg)
Save not working

**Comment by unknownbrackets** [comment]
Does this still happen in the latest git build?  Pretty sure a04af187ea055699cba72db093a78dead9656c72 will fix it.

-[Unknown]

**Comment by daniel229** [comment]
Perfect great.

**Comment by unknownbrackets** [comment]
It's somewhat satisfying when you fix a bug that has long perplexed you by changing only two characters.

-[Unknown]
