### ISSUE TITLE
Moga ace power

### ISSUE THREAD

**Issue by rubio164** [hrydgard/ppsspp#5164]
¿Alguien sabe si están trabajando en ello o sí saldrá pronto? Gracias ^^

**Comment by unknownbrackets** [comment]
Does this work any better now?  I think we implement the official game controller API and presumably controllers are now all implementing that?

-[Unknown]

**Comment by hrydgard** [comment]
We still have some support for Moga controller API I think, but I think all modern controllers can work with the platform APIs. Not likely that there's gonna be further work here, closing.
