### ISSUE TITLE
[Question] Log files on IOS

### ISSUE THREAD

**Issue by brujo5** [hrydgard/ppsspp#5191]
is possible add a option for psp emu,can create log files. whitout any external app?.

will be very usefull for ios.

i dont know how take logs on IOS whithout mac or developer tools.

**Comment by unknownbrackets** [comment]
The remote debugger is probably the best way to see these logs now on iOS for normal users?

-[Unknown]

**Comment by unknownbrackets** [comment]
Closing as per the above.  Use this to see logs on iOS:

http://ppsspp-debugger.unknownbrackets.org/

-[Unknown]
