### ISSUE TITLE
Gensou Suikoden blur screen

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#5205]
OpenGL Rendering
![01](https://f.cloud.github.com/assets/3481559/2000775/47eeff90-856a-11e3-98b5-9a21eb8afa55.png)

Software  Rendering looks similar to PSP
![02](https://f.cloud.github.com/assets/3481559/2000777/7da7a8bc-856a-11e3-9d66-4f6eeb50d107.png)

PSP
![201401250936_002](https://f.cloud.github.com/assets/3481559/2000779/8366017c-856a-11e3-9a04-794333ea8807.png)

A gif showing Gedebugger processing that from the clear screen to blur screen.
![1](https://f.cloud.github.com/assets/3481559/2000805/2ba0dfe6-856c-11e3-86cf-975c10cd67df.gif)

**Comment by sum2012** [comment]
In the directx 9 blur 
![2](https://cloud.githubusercontent.com/assets/2177532/5891037/e30832ee-a4b8-11e4-9446-3dfb18f70d07.jpg)
opengl do not blur
![1](https://cloud.githubusercontent.com/assets/2177532/5891035/bc8e35d2-a4b8-11e4-8f6e-0f422830dd0d.jpg)

GE debugger
![3](https://cloud.githubusercontent.com/assets/2177532/5891041/2599760e-a4b9-11e4-8760-359d57f1e27a.jpg)

v0.9.9.1-1601-gf1bca47 log:
https://gist.github.com/sum2012/32f2d7dd24309ade0f1f

**Comment by sum2012** [comment]
@unknownbrackets 
OpenGL fix in https://github.com/unknownbrackets/ppsspp/commit/b20cd3cba26e2d213bc1a064143a093186e8fd08

Does Directx 9 also some fix change ?

**Comment by unknownbrackets** [comment]
Does this work?  I have not really tested it at all.

https://github.com/hrydgard/ppsspp/compare/hrydgard:master...unknownbrackets:d3d9?expand=1

-[Unknown]

**Comment by sum2012** [comment]
Unlucky,it doesn't work

**Comment by Panderner** [comment]
Here's a GE Dump: 
[NPJH50535_0001.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/5761352/NPJH50535_0001.ppdmp.zip)

For me it's does not blur in OpenGL and Vulkan

**Comment by sum2012** [comment]
v1.10.3-1459-g678d881a1 only have problem in dx9
https://youtu.be/h15c5GbJcgQ

**Comment by ResurrectionRedmi9** [comment]
Maybe this can be fixed by https://github.com/hrydgard/ppsspp/pull/14833?

**Comment by hrydgard** [comment]
No, it's a different issue.

**Comment by hrydgard** [comment]
How is this now? Maybe the Kuroyou/Ratchet fixes were enough to fix this?

**Comment by Gamemulatorer** [comment]
Ca still reproduce using opengl ppsspp https://github.com/hrydgard/ppsspp/commit/bb6919ebcb1b849276eebf6db6c01bc80cb4300f

https://user-images.githubusercontent.com/37603562/191943931-0d4735dd-2f8e-4122-a127-d84846d4e610.mp4
