### ISSUE TITLE
Incorrect CPU Thread info

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#5220]
Should be 6 thread
![1](https://f.cloud.github.com/assets/2177532/2002958/392b692a-861f-11e3-88aa-5db29a86d41c.png)

**Comment by leopard20** [comment]
Is this issue really important?! Just wondering!

**Comment by unknownbrackets** [comment]
It will impact how many threads we kick up to upscale textures, run software rendering, and a few other things.  So it would negatively impact performance there since we would start too many threads.

That's aside from it obviously displaying misleading information to the user.

-[Unknown]

**Comment by hrydgard** [comment]
Read this and weep: https://twitter.com/rygorous/status/1004960175860506624

**Comment by unknownbrackets** [comment]
That's more about #10620 I guess, this one is more about misdetecting cores on AMD...

-[Unknown]

**Comment by hrydgard** [comment]
Ah, fair enough..

**Comment by unknownbrackets** [comment]
Maybe it'd make sense just to add reporting for all the cpu id values where it's not something standard, or where the result comes out to > 8 or something.

-[Unknown]

**Comment by LunaMoo** [comment]
![never too many](https://user-images.githubusercontent.com/5485237/45457089-a2d25d80-b6ed-11e8-9d6c-74e0866fd73c.png)
I think this might be pretty bad for Ryzen users:]
