### ISSUE TITLE
With "small display" option enabled the screen is too small (Android)

### ISSUE THREAD

**Issue by psennermann** [hrydgard/ppsspp#5227]
I have a tablet with  a 7 inch display and when I enable the option small display the part displayed is really too small (I think it's less than 3 inch), so at the moment it is pretty much useless.
It would be great to have a "medium" screen option or even better an option to resize the screen.
This option would be very useful on Android to speed up non-buffered rendering (due to its fixed resolution, enabling the small display option there's a huge speed boost, but as I said it's not much useful since the area displayed is really too small)
Having more option for resizing could give the possibility to better suit system specification with displayed area.

**Comment by unknownbrackets** [comment]
Is this still relevant with the hardware scaler option (which should work for non-buffered and buffered rendering alike)?

I realize that it's still not possible to select a different zoom level, but I think the primary reason for such a feature is either performance or 1:1 pixels.  The hardware scaler option addresses performance, and small display addresses 1:1.

-[Unknown]

**Comment by psennermann** [comment]
In my opinion Small display is too small:, on my 7' tablet is pretty much useless
For example a Medium display (or resizeable display) option would be useful to play at 1x with less pixelated graphic...

**Comment by unknownbrackets** [comment]
I believe this is fixed now, with @LunaMoo's work on the display layout editor.

-[Unknown]

**Comment by psennermann** [comment]
yes!!
