### ISSUE TITLE
Gundam Memories: Tatakai no Kioku radar does not work

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#5278]
Change rendering mode does not help,but works in software rendering.Tested several builds between 0.96 and 0.81,still the same broken.
![01](https://f.cloud.github.com/assets/3481559/2039354/84d1fbea-899f-11e3-9f40-2715a6d2b0e5.png)

psp
![201401301904_001](https://f.cloud.github.com/assets/3481559/2039343/610d592a-899f-11e3-9ece-4b69b4fc8ea4.png)

**Comment by unknownbrackets** [comment]
Does it keep drawing or is it just that one blip?  It looked like it would draw pie slices to set up the stencil.

Also, can you hover the mouse over that area after it draws (step draw after the first pie slice) and look at the alpha values it shows there?  It would also be useful to see the stencil values on the stencil tab, in that same area.

-[Unknown]

**Comment by daniel229** [comment]
What is keep drawing?It draws three red points per time and then draws the arrow in the middle.
![7](https://cloud.githubusercontent.com/assets/3481559/12059844/144987ea-af9e-11e5-9ac3-b7095dbede7c.png)
![8](https://cloud.githubusercontent.com/assets/3481559/12059845/14549810-af9e-11e5-8e8e-157febad7d8a.png)

**Comment by unknownbrackets** [comment]
So, here's what I'm expecting it to do:

![screenshot](https://camo.githubusercontent.com/480bb65e1df4bf112ec6d6b061d4b5993a5bbea2/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f333438313535392f323033393338362f35656132326531322d383961302d313165332d396134642d3539636434326662646633362e706e67)

In the above, the radar drawing goes outside the circle.  So my thinking is that it will do the following steps:

1. Draw the grid (like your GE debugger screenshots) background.
2. Set the stencil values for the circle, so it can avoid drawing outside the stencil.
3. Draw the blips of the map (some may fall outside the circle, but stencil testing will skip them.)
4. Cover the top with the pretty green circle and shading to make it look good.

![step 2 screenshot](https://cloud.githubusercontent.com/assets/3481559/3140794/172f6fec-e93e-11e3-9a33-b985025ea0a8.png)

This screenshot above shows it probably doing step 2.  I'm guessing it does that multiple times in a circle.  This "creates" the circle that it then uses to draw inside.  It uses ALWAYS 0x80 to fill the buffer with stencil values.

Then it says, "draw the blips only when the stencil test says that 0 < (what's there)".

So, to confirm my theory:

Does it draw the little triangle things in a circle?  Or is it just that one you showed?  Each should also have ALWAYS 0x80.

After it draws those (step draw) does the Stencil preview show a big red circle where they just drew, and where the radar is?  It should.  This is the circle used by step 3 to prevent drawing outside the radar.

Based on your screenshots above I *think* the ALWAYS 0x80 test is not properly filling stencil values, and it's staying 0 / black.  That would explain why it's not working, if so.

I'm also wondering what the alpha values are (after step 2.)  Does it also set those to 0, or do they properly get set to 128 or 255 (255 would be the most correct value)?

-[Unknown]

**Comment by daniel229** [comment]
Yes,it draws the little triangle things in a circle.
and Stencil test<code>>Stencil test	pass if (80 & 80) ALWAYS (a & 80)</code>

I don't see a big circle after it drew the little triangles.
and this is the GE debugger
![14](https://cloud.githubusercontent.com/assets/3481559/12060419/7b95f544-afaa-11e5-808e-0a20baa14d25.png)
![15](https://cloud.githubusercontent.com/assets/3481559/12060420/7b9ca1a0-afaa-11e5-84a6-dbb59e73ed3d.png)

**Comment by unknownbrackets** [comment]
Oh, so the stencil is 1.  Ah, right... hmm.  Tricky.

The problem is, we can't directly set stencil to 255.  I think we need to emulate stencil differently for 5551.

We ideally want to consider these tricky rules:

https://github.com/hrydgard/ppsspp/pull/4150#issuecomment-26211193

If we actually STORED 0/1, the tricky part is the clamping.  INCR twice + DECR once SHOULD be 0, but will actually be 1.  Anyway, we already have that problem.

Maybe the best improvement we could make is to rewrite a check that is `> (0-254)` or `>= (1-254)` to `> 0`, and the opposite for `<`.  That might resolve this particular issue...

Try this for the stencil test part of StateMapping.cpp (the one that starts with the same few lines):

```c++
		// Stencil Test
		if (gstate.isStencilTestEnabled() && enableStencilTest) {
			glstate.stencilTest.enable();
			glstate.stencilFunc.set(ztests[gstate.getStencilTestFunction()],
				gstate.getStencilTestRef(),
				gstate.getStencilTestMask());
			glstate.stencilOp.set(stencilOps[gstate.getStencilOpSFail()],  // stencil fail
				stencilOps[gstate.getStencilOpZFail()],  // depth fail
				stencilOps[gstate.getStencilOpZPass()]); // depth pass

			if (gstate.FrameBufFormat() == GE_FORMAT_5551) {
				glstate.stencilMask.set(abits <= 0x7f ? 0xff : 0x00);

				if (gstate.getStencilOpSFail() == GE_STENCILOP_KEEP && gstate.getStencilOpZFail() == GE_STENCILOP_KEEP && gstate.getStencilOpZPass() == GE_STENCILOP_KEEP) {
					switch (gstate.getStencilTestFunction()) {
					case GE_COMP_NEVER:
					case GE_COMP_ALWAYS:
					case GE_COMP_EQUAL:
					case GE_COMP_NOTEQUAL:
						break;
					case GE_COMP_LESS:
						if (gstate.getStencilTestRef() < 255) {
							// Any non-zero value in the buffer should be treated as 255.
							glstate.stencilFunc.set(GL_NOTEQUAL, 0, 255);
						} else {
							glstate.stencilFunc.set(GL_NEVER, 0, 255);
						}
						break;
					case GE_COMP_LEQUAL:
						if (gstate.getStencilTestRef() == 0) {
							glstate.stencilFunc.set(GL_ALWAYS, 0, 255);
						} else {
							// Any non-zero value in the buffer is "equal" to 255.
							glstate.stencilFunc.set(GL_NOTEQUAL, 0, 255);
						}
						break;
					case GE_COMP_GREATER:
						if (gstate.getStencilTestRef() > 0) {
							// If we have a 1 in the buffer, it's the same as 255, which > can never match.
							glstate.stencilFunc.set(GL_EQUAL, 0, 255);
						} else {
							glstate.stencilFunc.set(GL_NEVER, 0, 255);
						}
						break;
					case GE_COMP_GEQUAL:
						if (gstate.getStencilTestRef() == 255) {
							glstate.stencilFunc.set(GL_ALWAYS, 0, 255);
						} else {
							// If the buffer is non-zero, we treat as 255.  So only 0 can match.
							glstate.stencilFunc.set(GL_EQUAL, 0, 255);
						}
						break;
					}
				}
			} else {
				glstate.stencilMask.set(~abits);
			}
		} else {
			glstate.stencilTest.disable();
		}
```

-[Unknown]

**Comment by daniel229** [comment]
That works for it
![17](https://cloud.githubusercontent.com/assets/3481559/12061536/b5ae6e46-afc3-11e5-9e83-b49754e19017.png)

**Comment by unknownbrackets** [comment]
Underneath `if (gstate.FrameBufFormat() == GE_FORMAT_5551) {` in the above, if you comment out all of the `glstate.stencilFunc.set(...)` lines EXCEPT this one:

```c++
                    case GE_COMP_LESS:
                        if (gstate.getStencilTestRef() < 255) {
                            // Any non-zero value in the buffer should be treated as 255.
                            glstate.stencilFunc.set(GL_NOTEQUAL, 0, 255);
```

Does it still work?  That's the one that should be fixing this particular game.  #8346 is an attempt to make it more generic so it can possibly fix other games, not just this one.

-[Unknown]

**Comment by daniel229** [comment]
It still works.
