### ISSUE TITLE
moga pro(and possibly ace/power too) D-pad is ignored(mode A/native moga support)

### ISSUE THREAD

**Issue by thedicemaster** [hrydgard/ppsspp#5312]
a known issue, but apparently not marked as an issue here.
the D-pad on a moga pro is completely ignored in ppsspp.
the mapping settings act like no button is pressed at all.

this issue only exists in mode A.
in mode B the D-pad works fine(but another issue exists in that mode)

**Comment by hrydgard** [comment]
This now works in A-mode, so closing.
