### ISSUE TITLE
Boku no natsuyasumi 4 misplaced problem

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#5335]
misplaced boy

OpenGL
![02](https://f.cloud.github.com/assets/3481559/2075994/1b8f77e0-8d99-11e3-94d9-407d3dbefbb0.png)

Software 
![01](https://f.cloud.github.com/assets/3481559/2075995/1f9b5606-8d99-11e3-8c23-489b89d86908.png)

**Comment by unknownbrackets** [comment]
Does the black thing still happen with the sea?  If yes, does #7515 improve it at all?

-[Unknown]

**Comment by daniel229** [comment]
The sea is fine,just the misplace problem,Change the title name.

**Comment by unknownbrackets** [comment]
@daniel229 is this perhaps fixed?  Or maybe it doesn't happen on iOS / possibly even on Android?  See #7861.

-[Unknown]

**Comment by sum2012** [comment]
Test on v1.0.1-799-gb5f7d93 , still not fixed

**Comment by daniel229** [comment]
Not fixed yet at least on windows

**Comment by unknownbrackets** [comment]
Did anything change here?  #8149 makes me think it's possible.

-[Unknown]

**Comment by daniel229** [comment]
Fixed.

**Comment by unknownbrackets** [comment]
Wow.  Awesome.  I guess it was the matrix flip issue, probably?

-[Unknown]

**Comment by daniel229** [comment]
Another great thing,the game is pretty speed up by https://github.com/hrydgard/ppsspp/pull/7870 
![01](https://cloud.githubusercontent.com/assets/3481559/10932893/7c5b0536-830f-11e5-9279-a1384e032915.png)
![02](https://cloud.githubusercontent.com/assets/3481559/10932892/7c5a951a-830f-11e5-82f6-2bdd4a5a8005.png)

**Comment by hrydgard** [comment]
Yeah, the matrix flip not being complete was a bad bug... Seems very likely to have been the cause.

**Comment by unknownbrackets** [comment]
Yay, finally seeing some significant improvements from the tex split optimization.

-[Unknown]
