### ISSUE TITLE
Mipmapping issue:Tactics Ogre Let Us Cling Together JPN/Chinese translate displaying wrong characters 

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#5350]
wrong
![01](https://f.cloud.github.com/assets/3481559/2097195/521138ae-8f14-11e3-999c-e5b83603a6f8.png)

correct 
The JPCSP builds display the correct characters once was that before this commit merged http://code.google.com/p/jpcsp/source/detail?r=2351
![02](https://f.cloud.github.com/assets/3481559/2097196/52154926-8f14-11e3-9f09-30d4f57fea36.png)

**Comment by lockcole** [comment]
So is there no way to fix it?

I tried a recent build and I found that the problem still exists...

**Comment by xebra** [comment]
This issue is not fixed yet. Now I'm trying but...

![uljm05753_00000](https://cloud.githubusercontent.com/assets/1607422/22403217/fda6c3e8-e653-11e6-8d68-3d516aafa83c.jpg)
![uljm05753_00002](https://cloud.githubusercontent.com/assets/1607422/22403220/fda9abd0-e653-11e6-8f05-40609cb97890.jpg)
![uljm05753_00003](https://cloud.githubusercontent.com/assets/1607422/22403219/fda97a8e-e653-11e6-88dd-061b195868a7.jpg)
![uljm05753_00004](https://cloud.githubusercontent.com/assets/1607422/22403218/fda928a4-e653-11e6-952e-6fd62d695844.jpg)

**Comment by sum2012** [comment]
@hrydgard can we add this game in a compat system ?

**Comment by hrydgard** [comment]
yes, we may have to do that... :/

**Comment by sum2012** [comment]
So,let it fix in v1.5

**Comment by xebra** [comment]
I confirmed the codes by ghost is still working in latest revision.
That's great!

![uljm05753_00000](https://cloud.githubusercontent.com/assets/1607422/22583927/f437af92-ea32-11e6-8a5f-33f061349028.jpg)
![uljm05753_00001](https://cloud.githubusercontent.com/assets/1607422/22583926/f435bb56-ea32-11e6-9d85-550e25f5b7ac.jpg)

**Comment by hrydgard** [comment]
This is probably similar to that water blending issue we saw in another game, where a game set up multiple mipmap levels of the same size and uses mipmap bias to either blend or choose between them, in this case by explicitly setting the desired mipmap level for each character. ghost's code hacks around this by forcing a texture reload when the game chooses mipmap level. 

No modern graphics API supports having multiple equal-sized mipmaps but we can support it cleanly anyway by using either a number of separate textures or a 3D texture instead. This is a bit of work though and I probably won't get it done in the near future.

**Comment by hrydgard** [comment]
https://github.com/hrydgard/ppsspp/issues/6357 is the related issue, also #5559.

**Comment by xebra** [comment]
Yeah, you are right, I think so.
I had just been thinking we need "virutual mipmap system" or something else :p
Also, I think use 3D texture is good idea.

**Comment by hrydgard** [comment]
Only problem with 3D texture is that we won't be compatible with OpenGL ES 2.0 devices.

I wonder how many mipmaps this uses - can anyone run Ghosts' code and see what the highest value of "level" is that this game uses?

**Comment by daniel229** [comment]
level 5
![03](https://cloud.githubusercontent.com/assets/3481559/22594298/7aa1e82a-ea5d-11e6-9d1f-f38b1deeb047.png)

**Comment by daniel229** [comment]
I think @hrydgard  means the level in the code
```
	u8 level = ((gstate.texlevel >> 16) & 0xFF) / 16;
	NOTICE_LOG(G3D, "level:%d", level);
```
level 2 is the high
```
54:11:121 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:1
54:11:121 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:0
54:11:121 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:1
54:11:121 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:2
54:11:121 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:0
54:11:121 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:1
54:11:121 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:2
54:11:121 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:0
54:11:121 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:1
54:11:121 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:0
54:11:121 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:2
54:11:121 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:1
54:11:121 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:2
54:11:121 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:0
54:11:121 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:2
54:11:121 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:0
54:11:121 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:0
54:11:121 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:0
54:11:121 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:0
54:11:121 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:0
54:11:121 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:0
54:11:121 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:0
54:11:121 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:0
54:11:121 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:0
54:11:121 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:0
54:11:121 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:0
54:11:121 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:0
54:11:121 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:0
54:11:121 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:0
54:11:122 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:1
54:11:122 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:2
54:11:122 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:1
54:11:122 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:0
54:11:122 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:0
54:11:122 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:1
54:11:122 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:1
54:11:122 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:2
54:11:122 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:1
54:11:122 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:2
54:11:122 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:1
54:11:122 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:2
54:11:122 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:1
54:11:122 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:2
54:11:122 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:1
54:11:122 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:2
54:11:122 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:1
54:11:122 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:2
54:11:122 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:1
54:11:122 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:2
54:11:122 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:1
54:11:122 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:2
54:11:122 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:1
54:11:122 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:2
54:11:122 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:1
54:11:122 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:2
54:11:122 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:1
54:11:122 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:2
54:11:122 taco_thread  N[G3D]: GLES\TextureCache.cpp:1186 level:1
```

**Comment by hrydgard** [comment]
Actually there's a point to what you saw in the debugger too... if there are 6 (0-5) pages of actual font data there, then probably the rarer characters are in the later pages but we really need them all.

No cheap 2-texture solution here, we need a full 512x512x6 3D texture (or terrible, terrible hackery to simulate one with a big 2D texture but I really don't want to do that).

**Comment by xebra** [comment]
At least, in this game, in this scene, "virtual/fake(same size) mipmapping" uses only 3 levels(1, 2, 4) as far as I can see.
Here is the SS.
![-1](https://cloud.githubusercontent.com/assets/1607422/22616256/12bdb4c4-eaed-11e6-9ec4-e330d102b9b2.jpg)
![-3](https://cloud.githubusercontent.com/assets/1607422/22616254/12b9e06a-eaed-11e6-9385-a5eb7dc4aa42.jpg)
![-2](https://cloud.githubusercontent.com/assets/1607422/22616255/12badff6-eaed-11e6-8d1e-e85354601f65.jpg)
Texlevel offset 16 = level 1
Texlevel offset 32 = level 2
Texlevel offset 64 = level 4
Also, it has 6 texlevels but it seems has only 3 textures.
0,1 and 2,3 and 4,5 are using same texutre(same texaddress).
![-4](https://cloud.githubusercontent.com/assets/1607422/22616285/bab8710a-eaed-11e6-9099-da906a93ce96.jpg)

Sorry If I said something stupid because I don't know well this problem.

**Comment by xebra** [comment]
Texlevel 1 uses first texture, 2 uses second one, 4 uses third one.
It seems 0, 3 and 5 is never used(with only virtual/fake mipmapping).
Of course, level 0 is used always without mipmap.

**Comment by hrydgard** [comment]
Alright, the duplication makes some sense - they wanted to avoid accidental blending between layers (though they could have simply turned off mip filtering instead...).

I think stuffing the mips in a 3D texture is the best solution, but it'll be some work. I'll target it for 1.5, I still have some regressions to attend to for 1.4.

**Comment by xebra** [comment]
> Alright, the duplication makes some sense - they wanted to avoid accidental blending between layers (though they could have simply turned off mip filtering instead...).

Oh, I see.

> I think stuffing the mips in a 3D texture is the best solution, but it'll be some work. I'll target it for 1.5, I still have some regressions to attend to for 1.4.

I hope so.
Anyway, I'm searching more and trying to fix this if I can :)

**Comment by hrydgard** [comment]
The fake mipmap stuff should have taken care of this reasonably, right?
