### ISSUE TITLE
Excess use of VRAM in  NOVA  

### ISSUE THREAD

**Issue by bhavin192** [hrydgard/ppsspp#5351]
The mini game N.O.V.A. using a lot of GPU 
on my device I have 105 mb free from which some bytes or 0 remains when playing this game it causes the PPSSPP to work weird  

http://i.imgur.com/4aN6hYy.jpg
http://i.imgur.com/PmVXYXk.jpg

I have tried on other devices with more VRAM it works good but still uses more vram where CCFF VII uses only ~25 mb of vram

I have tried all texture related settings but it still using more GPU

**Comment by unknownbrackets** [comment]
There have been some changes to the way textures are invalidated.  Does this still happen?  Also, does it happen on Direct3D 9 or is it OpenGL specific?

-[Unknown]

**Comment by unknownbrackets** [comment]
I should clarify; I'm still not convinced that the usage is incorrect at all.  For example, this game could use a lot of PSP compressed textures, which we have to decompress to render on non-PSP devices.  In that case, it might use **significantly** more memory in PPSSPP than it really would on a PSP.  That's just life.

Crisis Core does not use heavily compressed textures, and generally works differently.  Whether NOVA uses compressed textures or not, the assumption that all games will use "approximately the same amount of vram" is, sorry to say, simply a bad one.  The assumption that better looking games will be the ones, if any, that use more vram is **definitely** a bad one.

400 MB however does seem surprisingly high.  Does it go down when you go to the pause screen?

Does it go back to normal levels when you quit the game?  Assuming it does, it's not a leak.  If that's the case, it may just be life.  Maybe it's using a bunch of 4-bit clut and DXT textures and texturing from offsets in them in a way that is simply not efficient.  Potentially we could detect overlapping textures like that, but it'd come at the cost of most likely making all games slower.

-[Unknown]

**Comment by bhavin192** [comment]
I agree with you, PPSSPP needs more VRAM to run NOVA.
The values are still high (little less usage though). Also when I pause game the usage remains same. If I pause game at 132mb it remains on 132mb.
should I close this?

**Comment by unknownbrackets** [comment]
If you close it and it doesn't go down, that's not good.  What if you play the game a little, save or something, close (don't exit PPSSPP), then relaunch the game, play some more, close, play again, etc. like 3-4 times?  Does the memory usage keep increasing?

If it keeps going up then it's a leak of some kind.

-[Unknown]

**Comment by bhavin192** [comment]
It goes on increasing if I do as you instructed.

**Comment by daniel229** [comment]
That vram increasing after closing a game seems to be an comom case,FF4 and Zero no Kiseki 7th dragon,all have the problem.

**Comment by unknownbrackets** [comment]
Hmm, that isn't good.  I'll try some, does it happen with v0.9.9.1?  I thought we didn't have any memory leaks (even gpu) at one point...

-[Unknown]

**Comment by unknownbrackets** [comment]
Yeah, something is definitely leaking:

mb - status
332 - not open
368 - menu
367 - ff4 load 1, not started
396 - ff4 save point 1
394 - stop 1
393 - ff4 load 2
395 - ff4 save point 2
393 - stop 2
408 - ff4 save point 3
406 - stop 3
422 - ff4 save point 4
419 - stop 4

-[Unknown]

**Comment by unknownbrackets** [comment]
I pushed some leak fixes to master, I guess it was always broken?  Anyway, after it's done building, I wonder if NOVA still leaks.

-[Unknown]

**Comment by ppmeis** [comment]
Tested with latest build. Game works fine for me.

**Comment by unknownbrackets** [comment]
Okay, cool.  Closing then.  Thanks for testing.

-[Unknown]
