### ISSUE TITLE
Tales of Radiant Mythology 2 Missing Map Graphic and some other issues

### ISSUE THREAD

**Issue by Sendayu** [hrydgard/ppsspp#5353]
Heya PPSSPP Team

i am writing this to let the team know of another bug with Tales of Radiant Mythology 2 game(The First one is the missing music bug that is being investigated here: https://github.com/hrydgard/ppsspp/pull/5323 )

This bug is where the in-game map in any area of the game never show no matter what the player do even if the player enable it in the option setting.Seeing how as more dungeon revealed and some share the same wall design without a map it;s very easy to get lost.Here;s a screen of it:
 
![nomap](https://f.cloud.github.com/assets/6491839/2099488/b9762b9e-8f3c-11e3-93ca-81291bea8db1.png)

How the map should show based on the trailer of the game:
 
![actual map](https://f.cloud.github.com/assets/6491839/2099494/d48915b8-8f3c-11e3-8924-b242b63111fc.png)

Is hard for me to trace what causing this issues as I don;t see any red word of the error though I did notice weird word when the in-game dungeon load : 
 
![map](https://f.cloud.github.com/assets/6491839/2099518/1173d922-8f3d-11e3-9585-e3191fb0bcf2.png)

There is other error that I found though I don;t know where this belong to so maybe this could help.

This word shows when the game load:
 
![reder](https://f.cloud.github.com/assets/6491839/2099557/962c6e40-8f3d-11e3-9a20-496638692ef6.png)

This error happen after game finish loading an in-game save:

![reder2](https://f.cloud.github.com/assets/6491839/2099568/bedd17fe-8f3d-11e3-9739-9db75daa13e8.png)

This error happen when the music gone missing bug happen(I don;t know whether this is the one caused the music to go missing or not as this error happen when the music go missing)

![redlogs](https://f.cloud.github.com/assets/6491839/2099587/ee1dd6a2-8f3d-11e3-8986-5f91f45b36c7.png)

Sorry for the long posts.hope this problem can be fixed.

**Comment by daniel229** [comment]
The music issue return broke by unknownbrackets@60378dd.

**Comment by unknownbrackets** [comment]
Is anything logged?

-[Unknown]

**Comment by daniel229** [comment]
```
28:20:843 cSoundMusic  I[ME]: HW\MediaEngine.cpp:87 FF: Frame data doesn't match channel configuration!
28:20:843 cSoundMusic  E[ME]: HLE\sceAtrac.cpp:442 avcodec_decode_audio4: Error decoding audio -1094995529 / bebbb1b7
28:20:847 cSoundMusic  I[ME]: HLE\sceAtrac.cpp:1413 sceAtracReleaseAtracID(0)
```

**Comment by unknownbrackets** [comment]
Actually, going to close this in favor of #4595.  I suspect #8176 will fix it anyway.

**Comment by daniel229** [comment]
https://github.com/hrydgard/ppsspp/pull/8176 does not fix it.
