### ISSUE TITLE
Metal Gear Acid (ULUS10006) :- Crashes during the introductory sequence in every build if Fast Memory is enabled.

### ISSUE THREAD

**Issue by solarmystic** [hrydgard/ppsspp#5365]
Possibly related to this closed older report by @avastia https://github.com/hrydgard/ppsspp/issues/2349 . Happens right before Teliko is about to meet Leone for the first time during the introductory sequence (just like https://github.com/hrydgard/ppsspp/issues/2349). 

All builds are affected, from v0.7.6 all the way to the current git release on the buildbot, v0.9.6-789-g3d3b0b1 but was not considered a legitimate issue since the Fast Memory option was deemed unstable until it was enabled by default from v0.9.5-759-gebdab9f https://github.com/hrydgard/ppsspp/commit/ebdab9f907c3884ad6cf6bf2c3689a281294cc10 onwards and is now part of the first boot configuration.

Reproduction Method:-

1. Boot up the game using any revision from v0.9.5-759-gebdab9f onwards with default settings (which already has Fast Memory enabled). Enable Fast Memory manually if attempting to reproduce the issue with v0.9.5-759-gebdab9f and below.

2. Start a New Game and let the introductory sequence play out.

3. Right before Teliko meets Leone for the first time, the game will crash, taking down the emulator with it.

MSVC 2013 Stacktrace was rather useless since it only points to the disassembly (similar to https://github.com/hrydgard/ppsspp/issues/4759 which is also an issue related to Fast Memory.)

Log console shows the following lines when the crash should occur if Fast Memory is disabled instead:-

![capture](https://f.cloud.github.com/assets/4345150/2117317/06ad223a-90c5-11e3-920b-0a9668160a4d.PNG)

Temporary solution:-
Play through that portion of the game (or indeed, the entire game, see https://github.com/hrydgard/ppsspp/issues/4536) with Fast Memory disabled.

**Comment by sum2012** [comment]
No invalid address in when Teliko meets Leone in v0.9.9.1-1505-gcf577e9-windows-amd64
log:https://gist.github.com/sum2012/413773470ee64e377170

**Comment by sum2012** [comment]
Need someone test #4536

**Comment by sum2012** [comment]
I think that can close this too
