### ISSUE TITLE
NBA street ballers graphic bugs 

### ISSUE THREAD

**Issue by wawan11** [hrydgard/ppsspp#5435]
Im sorry master , request fix graphic bugs Nba street ballers

**Comment by ppmeis** [comment]
Tested with latest build. Graphics glitches confirmed:
![ulus10078_00000](https://cloud.githubusercontent.com/assets/4381277/5670559/5cd6bd56-9781-11e4-962a-7242b911eec3.jpg)
![ulus10078_00003](https://cloud.githubusercontent.com/assets/4381277/5670560/5cdd8b86-9781-11e4-8106-e253d7208b70.jpg)

**Comment by unknownbrackets** [comment]
Hmm, could be vfpu or many things.  Does it happen even with vertex cache disabled and jit disabled?

-[Unknown]

**Comment by ppmeis** [comment]
@unknownbrackets yes it still present even disabling these options.

**Comment by unknownbrackets** [comment]
Is this NBA STREET Showdown or NBA BALLERS REBOUND?

If it's the latter:
http://report.ppsspp.org/logs/game/ULUS10078_1.05

VTYPE with morph used: THRU=0 TC=2 COL=0 POS=2 NRM=1 WT=1 NW=2 IDX=0 MC=2
VTYPE with morph used: THRU=0 TC=1 COL=0 POS=2 NRM=1 WT=1 NW=2 IDX=0 MC=2

Are the only slightly interesting ones, I see it's using morph and weights...

-[Unknown]

**Comment by ppmeis** [comment]
@unknownbrackets it's the latter one. NBA Ballers Rebound.

**Comment by ppmeis** [comment]
Tested with latest build. It seems to be fixed:
![nbaballersfixed](https://cloud.githubusercontent.com/assets/4381277/8889780/8288dc16-32e8-11e5-819f-df991cdeec6b.png)

**Comment by unknownbrackets** [comment]
I would love to know what fixed it.  Might've been something clut related.

Pretty nice to hear it's fixed.

-[Unknown]

**Comment by ppmeis** [comment]
@unknownbrackets yeah it's fixed and it look so nice. Thank you for your effor.
