### ISSUE TITLE
Crash Tag Team Racing reported stuck on memory stick screen

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#5468]
"After the android update crash tag team racing gets stuck at the memory stick screen. Any workaround for this?"

**Comment by ppmeis** [comment]
It works fine for me under Windows and Android, latest build:

Windows version
![image](https://cloud.githubusercontent.com/assets/4381277/8891556/473c8a76-332f-11e5-9a6a-4e59fa50b86f.png)

Android version
![screenshot_2015-07-26-00-58-36](https://cloud.githubusercontent.com/assets/4381277/8891613/ca01500c-3331-11e5-9b59-0b7f6e34bbde.jpg)

**Comment by unknownbrackets** [comment]
I wonder if the playstore version as of the last comment did not include the fix.  Otherwise maybe the issue is region specific...

-[Unknown]

**Comment by unknownbrackets** [comment]
Does this happen still on Android?

-[Unknown]

**Comment by sum2012** [comment]
I have no problem test on v1.2.2-821-geac1848 on asus zenfone 2

**Comment by ManDude** [comment]
Having this issue with 1.3 (stable), Windows.

**Comment by sum2012** [comment]
v1.3-144-g5df685f windows 64 bit do not work
debug log:
https://drive.google.com/file/d/0B3OaSdeV0L8kZk10MnBXVTZ4OUU/view?usp=sharing

**Comment by sum2012** [comment]
I know now.I was set cpu clok 1000 to test a game.
set back auto can in-game.

**Comment by ManDude** [comment]
A workaround is disabling memstick before the checking memory stick screen appears, then add the memstick back in after the main menu.

**Comment by sum2012** [comment]
@ManDude Did you changed cpu clock or something ?

**Comment by ppmeis** [comment]
Tested with latest build. It works just fine:
![image](https://cloud.githubusercontent.com/assets/4381277/21802480/33f6d83a-d726-11e6-979b-6162af86ae14.png)

**Comment by DjDiabolik** [comment]
OMG... simply found this thread by GOOGLE.
I have updated my version of ppsspp to 1.4.2 from 1.3......... on 1.3 all it's working but on 1.4.2 the games it's hang at same point.

At this point how i can fix or found a workaround ??

**Comment by ManDude** [comment]
Disable memstick before booting the game and enable it at the main menu.

**Comment by DjDiabolik** [comment]
@ManDude it's workaround.... but it's unfixable ?

**Comment by benderscruffy01** [comment]
goes ingame no problem
can this be closed now ???

**Comment by LunaMoo** [comment]
This was solved by an pretty incorrect hack making sceKernelVolatileMemLock eating lots of cycles later made into a slightly better compat.ini hack [DrawSyncEatCycles] that also solved issues in a bunch of other games pointing out that gpu timings should be improved, but yeah I guess this can be closed now.

**Comment by Panderner** [comment]
when I overclock this game above 266 MHz same happens

**Comment by hrydgard** [comment]
Yeah well, don't expect things to function correctly when overclocking - not all games can handle it.

**Comment by Panderner** [comment]
Here's a log when I overclock the PSP CPU above 266 MHz:

```
user_main    E[SCEUTIL]: Dialog/PSPSaveDialog.cpp:68 A save request is already running, not starting a new one
```

**Comment by unknownbrackets** [comment]
Maybe we should have a compat.ini setting that disables the cpu clock changes in some games?

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, that's reasonable.
