### ISSUE TITLE
Yu-Gi-Oh! Tag Force Series: Name and Attribute at the top of the Card is cut off

### ISSUE THREAD

**Issue by DragonNeos** [hrydgard/ppsspp#5470]
...when summoning a monster (Normal or Special Summon). This problem appears in every game in the series. This issue started appearing after hrydgard merged this Pull Request: (https://github.com/hrydgard/ppsspp/pull/2721) Before this Pull Request was merged, PPSSPP was not able to show the cards correctly (misaligned cards, cards displayed in black, etc.). After this Pull Request, cards are shown correctly except for cases when a monster is normal or special summoned (Name and Attribute are cut off from the top of the card that is in focus). When the effect of the monster is activated, the name and attribute of the card is shown.

OS: Windows 7 SP1 64-bit
PC: AMD Phenom II X4 810 @ 2.6 GHz, 8 GB DDR3 RAM, ATI Radeon HD 4200
Revision: PPSSPP v0.9.6-789-g3d3b0b1 64-bit

EDIT: @raven02 Save State Link for Tag Force 6: https://drive.google.com/file/d/0BxgBKNNFcTaAbjBCMUUtaW9hMzg/edit?usp=sharing

![screen00000](https://f.cloud.github.com/assets/5828320/2179007/34416c42-9688-11e3-8d55-441969243b93.jpg)

EDIT: Refer to the most recent issue (#7501)(only the first picture).

**Comment by DragonNeos** [comment]
@hrydgard @thedax Can you reopen this issue? This issue hasn't been fixed. There hasn't been any regressions between my last post and this one (ppsspp-v1.0.1-118-gc3f38f3). Here is an example of a video (Yu-Gi-Oh! GX Tag Force 3 - Beginning Story Mode Basement) from YouTube: https://www.youtube.com/watch?v=H8BBG7KjAEM&feature=youtu.be&t=23s
Between 0:23 - 0:26 in the video, I'm trying to normal summon a monster and the name and attribute of the card is cut off. On my opponent's turn, at 0:35 - 0:39 he tries to normal summon a monster and you will notice that the name and attribute of the card is cut off as well. At 0:40 in the video, the opponent activates the monster's effect and the whole card is shown.

**Comment by unknownbrackets** [comment]
Having multiple issues open for the same thing will only make it take longer to fix.  Would you still like it to be reopened?

-[Unknown]

**Comment by thedax** [comment]
@unknownbrackets: Wouldn't it make more sense to reopen this issue for the cut-off card problem, and then rename the other issue for the missing text problem? We don't even know if the two are related right now.

**Comment by DragonNeos** [comment]
@unknownbrackets Can you reopen this issue?

**Comment by unknownbrackets** [comment]
I don't really think so.  But sure, let's reopen all the issues so that we make sure things don't get fixed.  I'm certainly not going to mess with things that have duplicates and no clear information.

-[Unknown]
