### ISSUE TITLE
Outrun 2006 Lighting Bug: Every cars' colours are wrong

### ISSUE THREAD

**Issue by thedax** [hrydgard/ppsspp#5506]
As a continuation of https://github.com/hrydgard/ppsspp/issues/2603, it makes more sense to begin parsing out the game's remaining separate issues into their own issues instead of one mega issue for everything wrong.

In this particular instance, nearly all of the cars in the game have the wrong colours.

Screenshots of all of the cars (in their default colours) from RHW: http://min.us/mbwKK55M1pdsCm

Screenshots of all of the cars (in their default colours) from PPSSPP: http://min.us/mbqcmIXrarTMEs

I'm currently unaware if they've ever been correct. I need to investigate. From a few screenshots I've seen of the game in JPCSP, the car colours appear to be correct.

**Comment by thedax** [comment]
Quick update, this affects Direct3D9 as well, and the issue is still happening on the latest builds with both backends.

**Comment by thedax** [comment]
Yet another update: somewhere along the way, OpenGL lost the environment mapping on the cars, making them look dull and flatly shaded, while Direct3D9 continues to have shiny cars with the wrong colours. if you'd like me to bisect to find where OpenGL went astray, I can.

**Comment by thedax** [comment]
While I'm on the subject of updating some of my old issues, this one is still present, with one minor new piece of info: Vulkan suffers from the same missing environmental mapping as OpenGL (which is expected :) ). Direct3D9 still has shiny cars, but bad colours.

**Comment by ThePhoenixRises** [comment]
Same issue with Dirt 2 same problems with the skins of the cars showing incorrect colours.

**Comment by unknownbrackets** [comment]
Interesting.  I wonder when it improved - maybe whatever change fixed that could lead us to a reflection fix.

I am a fan of a new issue, to avoid getting lost on comments.  But I don't think it's important either way.  A GE debugger dump might help for the reflection issue.

Especially interesting: if you create the dump while on software, does it work on hardware?  If yes, it's almost definitely a framebuffer effect or upload/download.  If it still doesn't work, then it's some mishandled state.

-[Unknown]

**Comment by thedax** [comment]
From what i saw, yes, the dump made on software works on hardware. Here are two dumps I took, one on Vulkan (hardware) and one on Vulkan (software):

[DUMP.zip](https://github.com/hrydgard/ppsspp/files/2351358/DUMP.zip)

**Comment by unknownbrackets** [comment]
Yeah, the texture is blank.  It seems to use a 4444 texture using tex env mapping.  I'm guessing it's an upload of some kind - I'm not sure where, though.  It could be 0x040cc000.

-[Unknown]

**Comment by hrydgard** [comment]
Blank texture data in VRAM can of course also be caused by faulty render target downloads/writebacks...
