### ISSUE TITLE
Outrun 2006: Various tracks have graphical issues (black/missing geometry)

### ISSUE THREAD

**Issue by thedax** [hrydgard/ppsspp#5507]
As a continuation of https://github.com/hrydgard/ppsspp/issues/2603, it makes more sense to begin parsing out the game's remaining separate issues into their own issues instead of one mega issue for everything wrong.

In this issue's instance, the title explains it all. ~~The sky is black/missing on most stages, or~~ there is missing geometry/the geometry is black.

Like the car colour issue, I need to investigate if it's always been this way.

Affected courses:
~~\* Palm Beach: missing sky~~
~~\* Deep Lake: black/missing geometry in some areas, flickering on the screen, might need a video to explain it~~
~~\* Alpine: missing sky~~
~~\* Castle Wall: entire stage is black~~
~~\* Coniferous Forest: entire stage is black~~
- Cloudy Highland: black/missing geometry in some areas (when the car gets closer, the black "fills in" with the property geometry)

~~\* Industrial Complex: missing sky~~
~~\* Snow Mountain: missing sky~~
~~\* Tulip Garden: missing sky~~
~~\* Metropolis: missing sky~~
~~\* Ancient Ruins: missing sky~~
- Imperial Street: ~~missing sky~~, sometimes geometry/glitched polygons come up on the screen, covering it nearly completely
- Cape Way: ~~missing sky~~, sometimes geometry/glitched polygons come up on the screen, covering it in some areas

Here's a sample screenshot of what I mean by "polygons come up on the screen":
![Screenshot 01](http://i.minus.com/iKKeJ7c1nN2js.jpg)

**Comment by thedax** [comment]
There are only a couple issues remaining here:

* On the Imperial Avenue and Cape Way stages, the warped polygons that come up on the screen are still occurring in the latest builds on Windows with both OpenGL and D3D.
* The Cloudy Highland stage still has one or two spots with black geometry until the player gets close enough (affects both OGL and D3D).

Other than that the rest of them appear to be fixed.

**Comment by unknownbrackets** [comment]
Has any of this improved recently?  I wonder if it's using beziers or etc.

-[Unknown]

**Comment by hrydgard** [comment]
I don't think Outrun uses beziers - it's a port, so not that likely. I think those are a case of bogus geometry due to some bug that wasn't noticed because the vertices ended up outside the 4096x4096 coordinate box, and the triangles got discarded.

**Comment by unknownbrackets** [comment]
Hmm, in #2159 we have a bug because we /aren't/ discarding things outside the 4096x4096 box.  Maybe it's the same here, then?

-[Unknown]

**Comment by thedax** [comment]
@unknownbrackets, all of the remaining issues (e.g. wild polygons and the missing geometry/water) with the three tracks: Cloudy Highland, Cape Way, and Imperial Avenue still exist. However, they all have skies now and are looking better than I remember them looking a year ago.

**Comment by thedax** [comment]
Also worth mentioning is that Vulkan suffers from the same issues, so it's common to all three video backends.

**Comment by thedax** [comment]
Just a quick update to this, with the latest commit of PPSSPP ( https://github.com/hrydgard/ppsspp/commit/562c5f6485b5eba9ec49caa9cd05b658d2ed89b5 ): along with #9527 applied locally, the issues on Cloudy Highland, Cape Way, and Imperial Avenue no longer have the glitched polygons, and no UI elements are missing as far as I can tell. However, I only had time to test with the Vulkan renderer.

**Comment by unknownbrackets** [comment]
Are those additional issues gone without #9527 merged, or are they issues either way?

If the software renderer works (it's probably too slow to conclusively tell on all those tracks...), then it probably means the guardband approach in software (which is different from #9527) is a good way to go.

The approach is at the same time simpler and more complicated, but I think it may actually be how the hardware really does it.

-[Unknown]

**Comment by thedax** [comment]
From what I saw in testing, the issues exhibited by OpenGL, D3D9 and D3D11 were happening only with #9527 applied.

I can give the software renderer a try, but it'll take some time since I highly doubt it'll be very fast, haha.

**Comment by thedax** [comment]
Here's what I found with software rendering, with #9527 not applied (not that it should affect this anyhow, but I'm just keeping the build clean):
Imperial Highway: No glitched polygons
Cape Way: No glitched polygons
Cloudy Highland: No glitched polygons

The software renderer has other graphical issues with the game, but the main issue at hand doesn't seem to be present.

Off-topic: it actually wasn't that slow to be honest. I was getting around 17%-25% speed on these tracks, so while it took a significant amount of time, it wasn't unbearable.

**Comment by unknownbrackets** [comment]
I expect this to work now - on all backends - now that #11393 is merged.  How's it look?

-[Unknown]

**Comment by thedax** [comment]
Vulkan and Direct3D11: No issues. Glitched polygons are gone, and all UI elements are present.
OpenGL and Direct3D9: Glitched polygons are gone, but main menu is almost completely black, and in-game HUD elements are missing.

NB: The below information and screenshot are unrelated to the information above.
Interesting side note: the glitched polygons were actually part of the reflections on the water, at least in the Imperial Highway stage, see the below screenshot, though it's not the best demonstration of the former glitched polygons

![image](https://i.imgur.com/SL3vM36.png)

**Comment by thedax** [comment]
In the interest of posting more info, here are two framedumps from OGL:

[DUMP.zip](https://github.com/hrydgard/ppsspp/files/2401495/DUMP.zip)

**Comment by thedax** [comment]
This is 100% fixed on d3d9/opengl now, but the minor issue of water reflections on the Imperial Highway remains. I'll make a new issue about it when I get around to it (super low priority, lol).
