### ISSUE TITLE
PPSSPP:- Log Levels not saved in between sessions.

### ISSUE THREAD

**Issue by solarmystic** [hrydgard/ppsspp#5508]
Related to the original feature request here, https://github.com/hrydgard/ppsspp/issues/5477 and the pull request implemented here, https://github.com/hrydgard/ppsspp/pull/5479

Log Levels in a Release build are now by default set to "Info" since https://github.com/hrydgard/ppsspp/pull/5479 was merged to master, which is perfectly normal and non-detrimental to performance. Most users will be logging in this mode, unless explicitly instructed to produce a full debug by a developer.

Changing it to "Debug" in order to view the full Debug Log works as expected (you get the fast moving log spam as a result, with all of its verbosity) but the kicker is that the change to the global setting itself is not saved after you exit the emulator. 

Which means that one has to continuously change it to "Debug" everytime in between sessions. It'd be nice to make the global Log Level settings (and indeed the individual ones too) save an entry in ppsspp.ini which can be transfered in between sessions.

I checked the ppsspp.ini file for any references to the Log Levels and I couldn't find any.

Thanks for your time.

**Comment by unknownbrackets** [comment]
This was implemented in #9396.

-[Unknown]
