### ISSUE TITLE
Left/Right D-Pad Inputs not registering correctly

### ISSUE THREAD

**Issue by Kuralla** [hrydgard/ppsspp#5526]
I described the problem in greater detail on your forum at:

http://forums.ppsspp.org/showthread.php?tid=9461

Still no reply. I'm certain it's a bug with the emulator itself, since no other game/emulators are effected. It does it with both the d-pad with controller, and the keyboard arrow keys.

**Comment by unknownbrackets** [comment]
I'm pretty sure that will have fixed it, and no response in several months so let's assume yes.  If it hasn't, please comment.

-[Unknown]
