### ISSUE TITLE
MHP3rd HD RET: Stack empty error

### ISSUE THREAD

**Issue by hilesaz** [hrydgard/ppsspp#5555]
MHP3rd HD gives the error 'GPUCommon.cpp:768 RET: Stack empty!'  many times per frame.

![ge](https://f.cloud.github.com/assets/1079662/2242991/f2c16640-9d18-11e3-92e6-a4236c25bec9.png)
Here are 2 Bases in a row which makes no sense.  Below that is a couple bone data structures with the common
Bone data*12
Ret
format.  The flow through the bone data structures is what causes the spam.

![dis1](https://f.cloud.github.com/assets/1079662/2242993/fd365b9e-9d18-11e3-9120-cad2842a4d94.png)

This is the first place where the 2 base sequence is touched.  Blue underline is the first base and Red is the second base.
This actually sets the pair to
Base 0x000000
Jmp 0x000000

Later on in the same function, unconditionally:
![dis2](https://f.cloud.github.com/assets/1079662/2242996/0277e5aa-9d19-11e3-96b3-9c70fada050e.png)
Blue and red are as before and purple is used for both.
This shared section sets v0 to 0x10000000 | (t9 >> 8) & 0x00ff0000
where t9 points to the command after the bone structures (and s5 aliases 0x4(s2))

This looks pretty strongly to be a bug in the game itself and not of ppsspp.

As this is an HD rerelease it is quite possible that the game never worked on an actual psp.

It would be nice if someone has the original MHP3rd and can check whether it gives the same error.

It would also be nice if someone who knows how to write display lists can make a test for what a ret on an empty stack does on a real psp.

**Comment by unknownbrackets** [comment]
I can't remember if I pushed them to pspautotests, but I did do some tests and found that ret and call outside the stack limits are ignored.  Our limits are somewhat incorrect as there appear to be separate limits for call vs signal call, but we use just one:

https://github.com/hrydgard/ppsspp/blob/4b8d8c875d35aa101e1a425445474ca82005bd56/GPU/GPUInterface.h#L134

That said, this particular game bug (RET on stack empty) is ignored by the PSP, so I'm going to close this issue.

-[Unknown]
