### ISSUE TITLE
Macross water animation problem

### ISSUE THREAD

**Issue by LunaMoo** [hrydgard/ppsspp#5559]
Another one about Macross ~
 Water animation is just choppy in all 3 macross games it seems to change texture once every exactly 10 frames and it seems to show single texture which seems to be additionally incorrect.

 My thought on how it tries to work:
 The game is running at 30fps and there are 3 water textures, I don't understand all it tries to do, but the order of the 3 water textures does change every 10 frames by looking at GE debugger and it probably should blend/mix them to give a nice smooth water animation. In ppsspp the first texture is clearly visible, the other two which are processed after never affect the screen in any way until their turn comes after 10 frames.

 Tried all hacks and optional settings for it from the graphics tab, nothing seems to affect it, including software renderer.

 Not sure if this is related, but before v0.9.7.1-37-g9c4d946(Detect bad mipmap sizes, autogen mipmaps in this case.), we had to disable mipmaps to even see the water, it's animation was always choppy like that through.

 Here are the pictures of the 3 water textures in GE debugger, the first one is the one ending up visible on the screen with the second one, if you look at the 3rd one it should be affected by the second texture already, but still shows only the first one.

**Comment by unknownbrackets** [comment]
Has this changed at all with the depth changes?  Does it draw the water in multiple passes at all, or does it ever draw any part of the water with multiple mip levels?

The unknown commands may likely not be commands; often, data is "interleaved" into the display list, and JUMP commands are used to skip it.  The debugger will try to convert the data into commands.

-[Unknown]

**Comment by LunaMoo** [comment]
This game suffers from 2 opened issues so I check it pretty often, but nothing really affected either of those issues yet.

 Not sure if it's the exact same place I checked last time, but when drawing water GE now shows Tex mode as swizzled, 2 levels, CLUT per level when earlier it was having 2 levels, but mode was saying swizzled, 1 levels - so maybe that changed, however it does look exactly same as before in-game and just changes all water textures every 10 frames resulting in 3fps animation.
 I can also see now both levels change every 10 frames not just one, through one of them is always similar as it has to be for animation smoothness so maybe I just couldn't tell the difference previously from staring at it for too long.

Copy of ge debugger tabs - https://gist.github.com/LunaMoo/f85e88ee8ff515332d55

 When going step by step all the way, it does seem to do another pass on most of the water without doing any changes to the settings, but then something weird seems to happen as when you expect the closer things to get it's second pass it changes tex mode to swizzled, 1 levels and tex level/bias to slope + bias: 0.000000, and does say it draws things and shows selection on the texture itself but no selection is visible anywhere on the scene. Then it can return back to previous settings to draw some very distant water and while it was very microscopic I could see selection there at least as a few pixel dark line which makes me think the weird thing that's drawn earlier is completely out of the scene and potentially is what's missing here.

 I'm thinking maybe the effect actually works, but the distance is messing it up, I mean this game also suffers from #5549 which is messing vertices of some animations where they are drawn much closer to the camera than they should be resulting in stuff like big arms or transformation/some attacks covering up whole screen, possibly even going behind it. Maybe the water animation get's "behind" the camera or the opposite soo distant that doesn't even show selection on the scene.

**Comment by unknownbrackets** [comment]
It uses slope bias?  What is the `Tex lod slope 0.001333` value in that case?

Would be nice to see if the bias (from pass 1) or the slope (from pass 2) change each frame.  If so, both effects could create an animation.  Since both texture levels have the same size, we don't implement either one here.

Tactics Ogre, this game, and #6357 AFAIK all suffer from the issue of using miplevels as separate texture units.

-[Unknown]

**Comment by LunaMoo** [comment]
Tex lod slope is same always(well in this scene) 0.001333. When  Tex level/bias shows bias the value seems to increase every frame ie bias: 0.687500 then next frame bias: 0.750000.

**Comment by unknownbrackets** [comment]
Yeah, then that's exactly the same thing as #6357.  That would make the water appear to animate, because `min: linear, mipmap linear, mag: linear` would cause us to interpolate between the two by the bias.  So the first frame it would have 68.75% of level 2, and the next 75%.

The reason it changes abruptly every 10 frames is because that's when it switches to the next two mip levels, and starts the bias back at 0.

-[Unknown]

**Comment by LunaMoo** [comment]
Oh, cool at least it's not a mystery anymore, I think I will just close this in favor of the other one which has a demo.
