### ISSUE TITLE
Stuck Screen Def Jam Fight For Ny; Takeover Adhoc 

### ISSUE THREAD

**Issue by cmrhere2play** [hrydgard/ppsspp#5561]
I would get an error when trying to enter the lobby  like this then when i try to exit and return to the main screen it wont let me the screen isnt frozen at all either 
![20140224204646](https://f.cloud.github.com/assets/6509547/2253465/2f551542-9dbf-11e3-993b-ea88519cafe2.png)

![capture](https://f.cloud.github.com/assets/6509547/2253495/b1b2a8d8-9dbf-11e3-8823-848242bd1715.JPG)

**Comment by benderscruffy** [comment]
this is fixed
this can be closed

**Comment by 7oda797** [comment]
What is the solution for this problem please ? 

![68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f363530393534372f323235333436352f32663535313534322d396462662d313165332d393933622d6561383835313963616665322e706e67](https://user-images.githubusercontent.com/46852841/51432838-1f022200-1c47-11e9-8d04-194019cba245.png)
