### ISSUE TITLE
God Eater Burst Player disconnect

### ISSUE THREAD

**Issue by cmrhere2play** [hrydgard/ppsspp#5602]
When Trying to play multiplayer when either my friend or me make a room the other would join but disconnect while the other one doesnt

**Comment by unknownbrackets** [comment]
Is this still an issue?  May be impacted by latency - PSP games were not designed to be played over the internet with internet levels of latency.  They were designed to be played, for the most part, in the same room as the other person.

-[Unknown]

**Comment by MojoJojoDojo** [comment]
> Is this still an issue? May be impacted by latency - PSP games were not designed to be played over the internet with internet levels of latency. They were designed to be played, for the most part, in the same room as the other person.
> 
> -[Unknown]

If you played over on Xlink Kai on real PSP hardware you would be suprised at the amount of games you could play even over 200 ms and even sometimes 300 ms over the internet.
Anyway this game should work alright I think.
