### ISSUE TITLE
[iOS] PPSSPP crashes upon launch on iOS 5, also takes SpringBoard (launcher) with it.

### ISSUE THREAD

**Issue by angelXwind** [hrydgard/ppsspp#5613]
An user reported this problem to me, and I was able to successfully replicate it on an N81 (iPod touch 3) running iOS 5.1.1.

I haven't debugged the issue yet, but it's odd in that CrashReporter does not generate a crash log for PPSSPP, but rather for SpringBoard, which crashes right after PPSSPP.

**Comment by thedax** [comment]
Closing in favour of #7360.
