### ISSUE TITLE
Touchscreen button idea: Make buttons glow instead of growing to a large size?

### ISSUE THREAD

**Issue by thedax** [hrydgard/ppsspp#5624]
Could we perhaps change the touch buttons to glow or fill in solidly when touched, rather than growing to a huge size? I looked at a few other emulators on Android (Drastic, Retroarch), and they make the buttons glow or have a pressed down animation, rather than making their size grow huge.

**Comment by leopard20** [comment]
You can also add a slider to tweak the enlargement multiplier. There's a similar feature in ePSXe called "Button magnification on press".
The glow feature seems nice too.

**Comment by hrydgard** [comment]
Bumping any further improvements to 1.8.0.

**Comment by Emulatorer** [comment]
Can you add like this color button style? 
![1540852451418](https://user-images.githubusercontent.com/37603562/47684509-0c89c680-dbcb-11e8-86c0-dc73058f1620.jpg)

Because it's cool in the eye and my favorite color is blue 😎
I don't like the classic button even it is blue :/

**Comment by leopard20** [comment]
Is this from one of those PPSSPP clones or did you make it yourself?!
Nonetheless I like it better than the classic buttons too!

**Comment by unknownbrackets** [comment]
We actually could color the borders whatever.  I think that was the result of using an older PPSSPP version with the ini setting for border style set to glowing borders (because this causes it to use the standard thin borders, but with the blue color.)

-[Unknown]

**Comment by Emulatorer** [comment]
@unknownbrackets yeah your right 👍

**Comment by PilipinoAko** [comment]
You can add CUSTOM buttons/skin unknowbrackets?

**Comment by hrydgard** [comment]
Not yet.

**Comment by PilipinoAko** [comment]
Why?

**Comment by Emulatorer** [comment]
@iota97 can you make custom skin buttons for ppsspp like DraStic have?
![Screenshot_20200418-232830](https://user-images.githubusercontent.com/37603562/79641833-708fb880-81cc-11ea-843a-282936e8d1f6.png)

This is one of the features ppsspp don't have but others emulators already have..

**Comment by hrydgard** [comment]
this specific issue has been fixed for a long time, although a glow that extends outside the button is a future extension I'll add one day.

**Comment by EternalsDarkhole** [comment]
> Is this from one of those PPSSPP clones or did you make it yourself?! Nonetheless I like it better than the classic buttons too!

The latest version can now change the color of classic style buttons just change the system theme color setting :)
![Screenshot_2022-04-01-08-49-00-943_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/161173358-6ba78d3f-6d2b-4bca-af4f-a6c0859287c0.jpg)
![Screenshot_2022-04-01-08-40-55-236_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/161173369-b5d2bd70-b86d-4800-81e8-09ff024ff4ff.jpg)
