### ISSUE TITLE
Grand Theft Auto Vice City Stories Crashed after intro video (Chinese patched version)

### ISSUE THREAD

**Issue by kaienfr** [hrydgard/ppsspp#5638]
Unable to locate the source, but just crashed after video, the only screenshot in crash time is the asm debug as follows: 
![crash](https://f.cloud.github.com/assets/5306849/2406678/50fa3d30-aa76-11e3-8be5-01986a518b2c.JPG)

0x0000000013D4D9E5 exception (in PPSSPPDebug64.exe): 0xC0000005: access violation in reading location 0x000000007FFFC9E8.

**Comment by sum2012** [comment]
@unknownbrackets Do you remember your removed commits ?
I only remember one is sceUtility.cpp change

**Comment by unknownbrackets** [comment]
https://github.com/unknownbrackets/ppsspp/compare/modules

-[Unknown]

**Comment by sum2012** [comment]
Thanks @unknownbrackets

**Comment by sum2012** [comment]
@daniel229 Does God Eater 2 still have problem with this commit only ?
https://github.com/unknownbrackets/ppsspp/commit/8a012a9d785b56b9742d0550dd61222732a98440

**Comment by daniel229** [comment]
Yes,still hangs when entring the mission.

**Comment by sum2012** [comment]
Thanks @daniel229

**Comment by unknownbrackets** [comment]
Oh, I had misremembered this as breaking this game, rather than breaking God Eater 2.

Well, the numbers are all based on testing.  In `moduleLoadInfo`, if you make the second number zero in all cases, does it work?  That would probably mean it's just still a problem of memory allocation, and we've gotten closer but something else is wrong.

It may be that if something else allocates more (like sceNet) it will free a block earlier and work.  The reason is that Gods Eater Burst and God Eater 2 use a slab/pool based allocation model.  They actually keep free slabs allocated and deallocate them when there's memory "pressure."  So they keep very careful tabs on free memory and it's no surprise they break when memory isn't allocated the way they expect it to be.

Otherwise, is it one of the dependencies (the extra numbers listed after the second one)?  I'm pretty sure those are right, though.

-[Unknown]

**Comment by daniel229** [comment]
Make the second number zero in <code>moduleLoadInfo</code>,The GTA won't work,God Eater 2 works.

**Comment by sum2012** [comment]
@daniel229 
Can you try again God Eater 2 ?
https://github.com/unknownbrackets/ppsspp/commit/8a012a9d785b56b9742d0550dd61222732a98440
additional
https://github.com/sum2012/ppsspp/commit/57ed0a9d6bad126a672d7a67bdf935868299dd8d

**Comment by sum2012** [comment]
@daniel229 
sorry,updated my commit.
Can you try again God Eater 2 ?
https://github.com/unknownbrackets/ppsspp/commit/8a012a9d785b56b9742d0550dd61222732a98440
additional
https://github.com/sum2012/ppsspp/commit/2271d2abebfa1f22b29754bb97156e0c985f1ee9

**Comment by daniel229** [comment]
I merged https://github.com/unknownbrackets/ppsspp/commit/8a012a9d785b56b9742d0550dd61222732a98440 ,but some games include God Eater 2 and GTA would crash on start up. Apply https://github.com/sum2012/ppsspp/commit/2271d2abebfa1f22b29754bb97156e0c985f1ee9 still crash on start up

**Comment by sum2012** [comment]
OK,I re-write all code.
How about only this commit ?
https://github.com/sum2012/ppsspp/commit/156830811568a2f68ab2cf978cbf1cb773f7e21d

**Comment by daniel229** [comment]
Still breaks god eater 2 1.4

**Comment by sum2012** [comment]
@daniel229 Thanks your test.
@unknownbrackets gid15 believe your commit , but only alloc memory for Atrac3plus module
http://code.google.com/p/jpcsp/source/detail?r=3710

**Comment by unknownbrackets** [comment]
The numbers are all based on tests I made on a real psp, I am planning to clean it up at some point and put it on pspautotests.  Note that I'm also allocating the prx if it's loaded.

Maybe I'll make another build of JpcspTrace with cleaner memory measurements and we can just trace the games that have problems... need some way to match it up cleanly, though.

-[Unknown]

**Comment by sum2012** [comment]
@unknownbrackets 
I think that ppsspp need "support the loading of an EBOOT.BIN in kernel mode"
jpcsp commit
https://github.com/gid15/jpcsp/commit/bd063601bdd8c73d07e716ea11bfce7cbce13e51

**Comment by hrydgard** [comment]
@kaienfr @daniel229 is this still an issue?

**Comment by daniel229** [comment]
Yes,still an issue.

**Comment by sum2012** [comment]
@hrydgard this chinese patch game need alloc memory for unknown reason but alloc memory would break god eater 2 1.4

**Comment by sum2012** [comment]
Test again @unknownbrackets of modules branch.
crash :(
![2](https://cloud.githubusercontent.com/assets/2177532/10337452/4aedbc3e-6d32-11e5-9e94-9119e1baee01.png)

**Comment by hrydgard** [comment]
Try replacing

    *dep != 0; 

with 

    dep && *dep == 0

**Comment by sum2012** [comment]
@hrydgard Thanks,it work

**Comment by sum2012** [comment]
I test now no more break For god eater 2 1.4 with @hrydgard fix

**Comment by hrydgard** [comment]
@sum2012 so the game fully works now, with @unknownbrackets module fix and my little patch above?

**Comment by sum2012** [comment]
@hrydgard Yes :)

**Comment by sum2012** [comment]
Sorry :(
I only test name input screen.
Now raise invalid address\crash when finished loading the mission in GE 2 1.4

**Comment by sum2012** [comment]
GE 2 1.4 log
https://gist.github.com/sum2012/e690660dad36501ad295

**Comment by unknownbrackets** [comment]
Does it happen in the demo?

-[Unknown]

**Comment by sum2012** [comment]
No ,it does not happen in demo

**Comment by sum2012** [comment]
We get chance to fix from jpcsp
At first ,it alloc 0x00008000 memory for sceAtrac3plus , it has error on ge 2 1.4.
I need to find when it fixed

**Comment by sum2012** [comment]
Yeah I find it.I open new issue for GE 2 1.4
