### ISSUE TITLE
Kurohyou 2: Ryu ga Gotoku Ashura Hen,enemies running too fast

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#5703]
in chapter 5,the enemies running too fast and catch me everytime, so I can't get to the destination,setting whatever I set(software rendering,software transform read framebuffer to memory and so on),it won't help.Testing builds between 0.9.8-90~0.8.1 

In JPCSP,it works with software rendering,or disable saving GE screen to texture instead of memory with OpenGL rendering.

savestate
https://drive.google.com/file/d/0BzGZGDfFE68zUE5XdFlhWkNpTzA/edit?usp=sharing

savedata
https://drive.google.com/file/d/0BzGZGDfFE68zNjBfYi1lS3NpRW8/edit?usp=sharing

with savedata,load the auto save,and you must fight a battle.

**Comment by daniel229** [comment]
Change CPU clock to 25 helps the issue.

**Comment by daniel229** [comment]
ForceMaxEmulatedFPS = 20 also helps it.

**Comment by Gamemulatorer** [comment]
Cars is penetrating through buildings tried both ogl and vk backend.

https://user-images.githubusercontent.com/37603562/133915804-495b736e-a750-4457-9d05-77d6b9a14e0d.mp4

software rendering is correct

https://user-images.githubusercontent.com/37603562/133915862-4c3e41a5-e06a-423e-b796-8251722d13ad.mp4


[recording.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/7190986/recording.ppdmp.zip)

### Anyone with chapter 5 save state I want to test it?

**Comment by ResurrectionRedmi9** [comment]
This is a Graphics Emulation problem.

**Comment by unknownbrackets** [comment]
Yeah, that's #9576 - unrelated issue, except that it's the same game.  Well, probably unrelated - I guess there's some slight chance this behavior is affected by depth too.

-[Unknown]

**Comment by Gamemulatorer** [comment]
Enemy is not running too fast using the ppsspp latest git build.

https://user-images.githubusercontent.com/37603562/133947116-943db552-5c50-4950-b264-578d8ecd60ad.mp4

Also added this game id to ForceMax60FPS compatibility to slightly improve performance.

**Comment by Gamemulatorer** [comment]
This issue can be closed now because I cannot reproduce @daniel229 issue also the reporter is not active anymore.

**Comment by unknownbrackets** [comment]
Okay, going to close it hoping it's fixed.  Will be happy to hear from @daniel229 if it isn't (or if it is.)

I wonder if it's a timing issue we've improved.

-[Unknown]

**Comment by PFLI2** [comment]
> Enemy is not running too fast using the ppsspp latest git build.
> Screenrecorder-2021-09-20-07-55-05-624.mp4
> 
> Also added this game id to ForceMax60FPS compatibility to slightly improve performance.

This clip is from Kurohyou 1, the issue is in 2. The issue never existed in 1.

**Comment by Lockefinder1** [comment]
Chinese fans recently released a Chinese localization patch that seems to fix the problem by resetting enemies to normal speed.
I don't know how it works. I'll leave it to you. 
[https://drive.google.com/drive/folders/1RCBmnTNsQV6FL0H6Kqa3naUU67vr12f8?usp=drive_link](url)
