### ISSUE TITLE
Possible Tegra 2 problems  (lack of NEON, or GPU)

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#5714]
Got this report from someone with a LG P-999, which has Tegra 2, which is not exactly a very common SoC.

"I tried playing Kingdom Hearts : Birth by Sleep and a lot of graphic details were missing. Like the characters didn't have a body and the buildings and environments were missing."

Tegra 2 is noteworthy for being a relatively modern architecture EXCEPT that it lacks NEON. I think few of us have ARMv7 devices without NEON so it's possible that path may have issues. Could of course also be a shader compiler problem.

**Comment by unknownbrackets** [comment]
It's been a year and a half since this was filed.  In that time, the Tegra 2 became a year and a half older.  While it'd be nice to make sure we properly support this device, if we don't have one or a user who has one, should we keep this open?

-[Unknown]

**Comment by thedax** [comment]
I still have one, but nobody ever submitted a save for me to mess around with, so probably not.

**Comment by unknownbrackets** [comment]
Oh, sorry, it'd been too long since I read that comment above, heh.  I assume going into the game a bit, it works, right?

A good game, if you have it, to try would be Fat Princess (just start any game.)  But in general if games are working it can't be that bad.

-[Unknown]

**Comment by thedax** [comment]
I'll check the next time I get a chance.
