### ISSUE TITLE
Outrun 2006: several graphics issues occur when the rendering resolution is set to 5x or higher

### ISSUE THREAD

**Issue by thedax** [hrydgard/ppsspp#5726]
If the rendering resolution is set to 5x or higher, the following two problems occur:

* The in-game HUD disappears:
![Screenshot 01](http://i.minus.com/ibscaRzUzABea0.jpg)

How it's supposed to look:
![Screenshot 02](http://i.minus.com/ibqRTpt0BxMJkB.jpg)

* Most menu graphics disappear:
![Screenshot 03](http://i.minus.com/ibknrNd8y05f6u.jpg)

How it's supposed to look:
![Screenshot 04](http://i.minus.com/iYFwxB0FbwdWM.jpg)

As reported [on the forums](http://forums.ppsspp.org/showthread.php?tid=1814&pid=79589#pid79589).

**Comment by thedax** [comment]
Still happens for me on the latest build, 0.9.9-1571-g19b92a3.

**Comment by unknownbrackets** [comment]
Does this still happen for higher render resolutions than 5x?  It's possible that it may have been viewport related, especially if it affected different devices more than others (e.g. not @hrydgard.)

-[Unknown]

**Comment by thedax** [comment]
No, it's fixed for me now. The viewport changes were the solution.
