### ISSUE TITLE
Ram usage problem (Catalyst AI causes crazy memory usage and performance problems)

### ISSUE THREAD

**Issue by KkuriaNn** [hrydgard/ppsspp#5739]
Guys, i have 4gb of ram in my Windows 7 x64 bits, the emulator runs correctly in my pc but i have a one problem with my ram usage:

Emulator start monster hunter with 120mb ram usage, then in mission, this increment bit a bit and in 5 minutes of gameplay the ram level is in 2gb of ram usage, 10 minutes of gameplay emulator's ram usage is over 3gb of ram, then, emulator crash.

Anyone can help me pls?, btw, yesterday i did a fresh install of windows 7 x64 and official signed drivers (amd)

Sorry if my english is bad, obviously im not english.

**Comment by unknownbrackets** [comment]
I haven't heard about this problem in a while.  Did AMD fix it?

-[Unknown]

**Comment by hrydgard** [comment]
Presumably, let's assume so until it gets reported again.
