### ISSUE TITLE
LittleBigPlanet savedata issue

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#579]
If you don't have a save file, this just keeps showing up on startup:

![savedata_lbp](https://f.cloud.github.com/assets/130929/121671/04d3fc90-6ddf-11e2-9837-62172fee9736.png)

**Comment by ppmeis** [comment]
Tested with latest build. I download a 100% savefile and game works fine (EU version):
![image](https://cloud.githubusercontent.com/assets/4381277/6554802/ca722032-c65f-11e4-9aac-5d97fd5b928a.png)

**Comment by ppmeis** [comment]
@unknownbrackets you can close this I think.

**Comment by unknownbrackets** [comment]
Does it work with no savedata at all, though?  At least the original issue wasn't about having existing data.

-[Unknown]

**Comment by ppmeis** [comment]
@unknownbrackets Yes it does. I tried in both cases.

**Comment by mikeymop** [comment]
I do still experience this issue on 1.12.3 Android.

Tried wiping the save data and creating a new one and the issue persists.

**Comment by unknownbrackets** [comment]
Maybe better to create a new issue, but I'll reopen this just to make sure it's not lost.

My guess is this was broken by the Android content URI / storage changes.

-[Unknown]

**Comment by unknownbrackets** [comment]
I'm going to close this based on #15379.  Please comment if you're still seeing issues, or create a new issue.

-[Unknown]
