### ISSUE TITLE
Performance regressions in FF4 CC

### ISSUE THREAD

**Issue by pal1000** [hrydgard/ppsspp#5799]
There are plenty of performance regressions in this game surprisingly appeared and amplified progressively during alpha test optimizations!
Initial system configuration:
![screen00000](https://f.cloud.github.com/assets/1138235/1827284/57ba9a3c-722e-11e3-86e1-c57c3494f771.jpg)
Current system configuration:
![menu_00000](https://cloud.githubusercontent.com/assets/1138235/2541700/dabc48be-b5df-11e3-9678-a86b062902a5.jpg)
1. Zus are fading slower than other monsters.
<a href='http://pal1000.3x.ro/shared/bugreports/ppsspp/issue-5799/SAVEDATA-Zu.zip'>Here</a> is a game save data to reproduce. Select The After Years game, load file 6 and wander around for a bit, the chance to encounter Zus frequently in the area is high.  It can only be noticed on laptops with low frequency CPUs.
2. Audio shutter which occurs while game menus are on screen has gone worse. Can still workaround by setting frameskip to 1 or higher. It can only be noticed on laptops with low frequency CPUs.
3. Audio shutters happens in some dungeons even while no game menu is on screen, notably in Passage of Eidolons. <a href='http://pal1000.3x.ro/shared/bugreports/ppsspp/issue-5799/SAVEDATA-POE.zip'>Here</a> is game save data to reproduce. Select The After Years game and load file 6. It can only be noticed on laptops with low frequency CPUs.

**Comment by unknownbrackets** [comment]
Has the performance improved at all in the latest git builds (and with #7513)?

I'm guessing it's gotten slower mainly due to the GPU.  It would help if you could go back a bit and bisect to find where it dropped off in performance the most.

-[Unknown]

**Comment by unknownbrackets** [comment]
It's not clear if there's still a regression, but reportedly the fade out can still cause poor performance on some devices:

http://forums.ppsspp.org/showthread.php?tid=2108&pid=118327#pid118327

I think the fade out is being done via the CPU, which would make it a driver texture upload performance problem if so...

-[Unknown]

**Comment by unknownbrackets** [comment]
How is performance now with all the threading related changes in 1.6.0?

-[Unknown]

**Comment by pal1000** [comment]
Didn't see any performance difference, however the Meldown/spectre patches may be responsible. I'll try with them disabled soon.
