### ISSUE TITLE
DJMAX Portable 2 bugs

### ISSUE THREAD

**Issue by cyb3rm4n** [hrydgard/ppsspp#5837]
Just got two bugs. First is o video - flickering. Second - alternate bug - is with audio. Video with some logs: 
https://www.youtube.com/watch?v=B-BG1ZmRVu4&

Some PasteBin: 
http://pastebin.com/65EMF2XM

**Comment by ppmeis** [comment]
Tested with latest build. Simulate UMD Delays fix the issue. Dj Max Portable 2, 3 and Hot Tunes work fine without anti piracy protection bug.

**Comment by thedax** [comment]
Should we consider this as fixed then? Since we have a non-hacky workaround, I think it's safe to close.

**Comment by unknownbrackets** [comment]
I think we can, since we have #7647.  Would like to have it work by default for everyone.

-[Unknown]

**Comment by cyb3rm4n** [comment]
The bug is not present now. Thanks!

**Comment by Areidz** [comment]
Using latest build: https://www.youtube.com/watch?v=BM7Mf80XS6U

**Comment by ppmeis** [comment]
@Areidz did you enable "Simulate UMD delays"?

**Comment by Areidz** [comment]
@ppmeis I thought I had it enabled. I've re-enabled it and it seems to be working perfectly, sorry.
