### ISSUE TITLE
xbox 360 controller - Linux (buttons not assigned)

### ISSUE THREAD

**Issue by fastrizwaan** [hrydgard/ppsspp#5846]
Only the Axis buttons are assigned along with select (in LB) and start (RB) which are incorrect. The same controller works fine in Windows' PPSSPP.

Please consider assigning a,b,x,y, L,R, start, select, menu buttons for 360 (wired) controller in Linux.

Please consider this settings for xbox 360 controller in Linux
$HOME/.config/ppsspp/PSP/SYSTEM/controls.ini
﻿[ControlMapping]
Up = 10-4033
Down = 10-4032
Left = 10-4031
Right = 10-4030
Circle = 10-20
Cross = 10-19
Square = 10-21
Triangle = 10-22
Start = 10-193
Select = 10-192
L = 10-197
R = 10-196
An.Up = 10-4003
An.Down = 10-4002
An.Left = 10-4001
An.Right = 10-4000
Pause = 10-194
Save State = 1-132
Load State = 1-134
Next Slot = 1-133
Toggle Fullscreen = 1-141
RightAn.Up = 10-4035
RightAn.Down = 10-4034
RightAn.Left = 10-4029
RightAn.Right = 10-4028,10-4035

---

control.ini (windows 7)
---
﻿[ControlMapping]
Up = 1-19,20-19,10-19
Down = 1-20,20-20,10-20
Left = 1-21,20-21,10-21
Right = 1-22,20-22,10-22
Circle = 1-52,20-97,10-190
Cross = 1-54,20-96,10-189
Square = 1-29,20-99,10-191
Triangle = 1-47,20-100,10-188
Start = 1-62,20-108,10-197
Select = 1-50,20-109,10-196
L = 1-45,20-102,10-194
R = 1-51,20-103,10-195
An.Up = 1-37,20-4002,10-4003
An.Down = 1-39,20-4003,10-4002
An.Left = 1-38,20-4001,10-4001
An.Right = 1-40,20-4000,10-4000
RapidFire = 1-59
Unthrottle = 1-61,20-4036
SpeedToggle = 1-68,20-107
Pause = 1-111,20-4034,20-3
Rewind = 1-67
---

**Comment by cra0zy** [comment]
So.. this is literally impossible, why?

First there are 2 drivers for xbox 360 controllers, xpad(doesn't work correctly with wireless controller) and xboxdrv.

Second xboxdrv has a variety of options:
--trigger-as-button
--trigger-as-zaxis 
--dpad-as-button
--dpad-only 
--mimic-xpad
and a lot more....

**Comment by hrydgard** [comment]
It's surely possible, it's just that noone has figured it out a way to autoconfigure it yet. As I don't run Linux as a main OS on any of my boxes I'm not likely to do so either any time soon, pull requests accepted.

**Comment by cra0zy** [comment]
> It's surely possible, it's just that noone has figured it out a way to autoconfigure it yet.

True true... I should have said it's impossible for now. Even Steam does not have autoconfiguration for Xbox 360 controller when on Linux.

Anyway there were ideas like: https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt
which again does not work for all Xbox 360 controllers, just some.

**Comment by adamdmoss** [comment]
Not sure these assertions are currently accurate.  xpad supports wireless controllers.  Steam itself (big picture mode) and the majority of Linux games work out-of-the-box with xpad and the xbox 360 controller.  Just data points, not strictly relevant to the discussion.

SDL offers a pretty good abstraction for controllers - a bit low level, but it does seem to effectively hide the differences in axis and button mappings across drivers and operating systems for the xbox 360 controller.

Sadly, implementing out-of-the-box controller support for apps without the equivalent of SDL (or perhaps GLFW) or a gamecontrollerdb is a bit... annoying.

**Comment by cra0zy** [comment]
> xpad supports wireless controllers

I said doesn't work correctly, not doesn't support it. So with xpad middle lights are always blinking, which is really annoying, it's treated as 4 controllers, and you can't shut it down using xpad(you have to pull out the batteries).

> Steam itself (big picture mode) and the majority of Linux games work out-of-the-box with xpad and the xbox 360 controller.

It works accurate with xpad, but not with xboxdrv.

**Comment by adamdmoss** [comment]
Ah, I see.  steamos-xpad-dkms fixes the blinking lights - wonder when it's going to be upstreamed.

**Comment by cra0zy** [comment]
> Ah, I see. steamos-xpad-dkms fixes the blinking lights - wonder when it's going to be upstreamed.

I did not know that, thank you for the information good sir.

**Comment by unknownbrackets** [comment]
Centralizing this in #7847.  There's no reason to have multiple open, and that one has just a bit more recent discussion.  We'll move nowhere if we keep rehashing things we already discussed.

-[Unknown]
