### ISSUE TITLE
Why can't us play on wireless mode

### ISSUE THREAD

**Issue by ghost** [hrydgard/ppsspp#5850]
it would be great to play using wireless mode
Connecting PPSSPP to PSP
Connecting PPSSPP to a PPSSPP
And if you can then let us play online (not LAN)

**Comment by Hydroque** [comment]
This is dead but I don't know what a SEN server is? Like a gamespy?

**Comment by Sonickyle27** [comment]
@Hydroque Sony Entertainment Network.
