### ISSUE TITLE
Collect scePauth

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#5950]
Evangelion Jo #5810 
MH3P

**Comment by benderscruffy01** [comment]
can this stay open ???

**Comment by sum2012** [comment]
No

在 2019年4月2日週二 20:37，benderscruffy01 <notifications@github.com> 寫道：

**Comment by benderscruffy01** [comment]
you can close it then

**Comment by sum2012** [comment]
I mean leave it open

在 2019年4月3日週三 19:37，benderscruffy01 <notifications@github.com> 寫道：

**Comment by LunaMoo** [comment]
For the record Idolmaster games also used pauth files(for verification/anti-pirate protection).
This can be closed now through since PPSSPP can finally decrypt pauth files without workarounds.
