### ISSUE TITLE
Hammerin Hero text problem

### ISSUE THREAD

**Issue by ReyVGM** [hrydgard/ppsspp#5954]
The text in this game seem to be a bit too wide causing the words to be too close together. The game seems to be using its own custom font, so having the original PSP fonts doesn't do anything. 

Also notice how the text looks kind of... wrongly rendered or something.

I've tried buffered and non-buffered, double resolution, several hack options and nothing works. Changing to double resolution seems to help how the text looks, but it doesn't help the spacing issues.

The first image is how I see it:
![screen001](https://cloud.githubusercontent.com/assets/7338867/2802304/e7843b06-cc8c-11e3-88a4-a7d13808fa53.png)

This is how it should be:
![haherpsp0062](https://cloud.githubusercontent.com/assets/7338867/2802303/e7823ae0-cc8c-11e3-8f5f-064d80febf11.jpg)

This is how I see it:
![screen013](https://cloud.githubusercontent.com/assets/7338867/2802374/b3b3ff40-cc8d-11e3-9ff5-e065592dfed0.png)

This is how it should be:
![haherpsp0033](https://cloud.githubusercontent.com/assets/7338867/2802379/b99f8d52-cc8d-11e3-8009-957a2cfa0cd4.jpg)

**Comment by sum2012** [comment]
I notice the space issue in the menu
![2](https://cloud.githubusercontent.com/assets/2177532/6240470/09332a02-b74a-11e4-9d8d-bad7e9749c3e.jpg)

JPCSPtrace log:
https://drive.google.com/file/d/0B3OaSdeV0L8kYW51WjFUSHZvZkU/view?usp=sharing

**Comment by unknownbrackets** [comment]
Hmm, it probably will still be off, but has subpixel rendering improved this at all?

-[Unknown]

**Comment by sum2012** [comment]
Test with v1.1.1-855-g5a06439 , menu no improve

**Comment by benderscruffy01** [comment]
v1.8.0-17-g737be61f9
stil the same problem even when using  my original psp fonts
![hero](https://user-images.githubusercontent.com/48821663/54860534-71021980-4d56-11e9-9565-9ef6ccd12668.PNG)

**Comment by nassau-tk** [comment]
The font files were fixed on v1.10.3-1036 or later.
How do you seem now?

**Comment by nassau-tk** [comment]
@hrydgard 

It's maybe solved already.

![image](https://user-images.githubusercontent.com/48179091/104278245-a0fe4c00-54eb-11eb-98aa-475e5b4e4a58.png)

![image](https://user-images.githubusercontent.com/48179091/104278260-a6f42d00-54eb-11eb-89e8-de6a213c552d.png)

![image](https://user-images.githubusercontent.com/48179091/104278302-ba06fd00-54eb-11eb-8b89-ff6732ab53e1.png)

![image](https://user-images.githubusercontent.com/48179091/104278337-cab77300-54eb-11eb-8c21-89109ed54a80.png)

![image](https://user-images.githubusercontent.com/48179091/104278375-db67e900-54eb-11eb-9d8d-51f586b723b0.png)

**Comment by unknownbrackets** [comment]
That's great.  Does it work now both with our fonts AND with PSP official fonts?  Or only with our fonts?

It was strange it didn't work before with PSP official fonts.

-[Unknown]

**Comment by nassau-tk** [comment]
@unknownbrackets 

It's our font.(Above)

PSP Original font is below.(Maybe no problem.)
![image](https://user-images.githubusercontent.com/48179091/104279816-461a2400-54ee-11eb-9e3c-4671bafb44ba.png)

![image](https://user-images.githubusercontent.com/48179091/104280035-a4470700-54ee-11eb-966c-65b217710eb7.png)

![image](https://user-images.githubusercontent.com/48179091/104280048-ab6e1500-54ee-11eb-9a6f-071587fad8bd.png)

How do you think?:wink:

**Comment by nassau-tk** [comment]
Of course, "OpenGL/Vulkan/D3D11" all backends has no problem.

**Comment by unknownbrackets** [comment]
Looks fixed to me.  Great work.

-[Unknown]
