### ISSUE TITLE
Armored Core Last Raven - Possibly others - Emulator Crash

### ISSUE THREAD

**Issue by kingpinzero** [hrydgard/ppsspp#5999]
Version: v0.9.8-561-g2b50fcb
Emulator settings as default, so without Fast Memory or Multi Threaded.
Tested on Galaxy S2 (4.1.2) and Nvidia Shield (4.4).
Rendering methods doesnt affect the bug.

AC:LR freezes the whole emulator, but doesnt crash it.
Its easily reproducible. First mission in the mission map, on the far right. Rotate the camera until you almost look at the sun, positioned at the player's back.

It doesnt happen on windows: on windows instead, the sun makes hud, lighting and part of the graphics disappear while a grey "filter" appears.

**Comment by 4XPG** [comment]
On Armored Core: Silent Line: Using build v1.0.1-238-g6573bca, in the mission "Escort Transport" (one of the two second mission) hangs right after opening the first door.
http://i.imgur.com/yuUYqkP.png
On Armored Core 3: hangs while loading Prevent Capsule Theft (1st Layer: Nature Area) mission

I haven't tried AC:LR but I think Destroy Military Base still bugged too.

**Comment by 4XPG** [comment]
Here's an example of the sunlight effect that cause the hang.
http://i.imgur.com/34RDlF2.jpg

On the older build (I used 0.9.1) it completely removes the HUD and fills the screen with transparent grey filter instead of hang as mentioned before. I think the change that supposed to "fix" this issue made the hanging issue also persists on the Windows version.

**Comment by Krylia** [comment]
Identified interesting thing even though I probably am just mucking around, what I found probably isn't even anything, and I am just making a fool of myself. So, on those loading hangs, such as in AC3:SL on the "Distract Security Team" mission as well as AC3:P "Prevent Capsule Theft", in that oh so wonderful logging console you might see something about atrac setting a halfway buffer about the time of the hang, which is probably not so terrible, other than well, it is one of the few closest things to the the hang that cropped up whilst the loading screen was actually present.

You might also notice a bin code inside the message about that buffer thing, which you can pop into the find/goto field in disassembly. I am not sure if the codes in the log and the code in disassembly actually correlate but uh, the bin code that matched up to it in disassembly had no instructions set. None. Zip. Zilch. Zero. And alot of other bin codes up and down FROM that same code were in a similar situation. FUN!

**Comment by LionMagnus** [comment]
I found a old hack version of the emulator that works with Last Raven, only problem is the blackbox when boosting. Hopefully they will release a new version that fix this.

**Comment by dulsan** [comment]
I still have the same issue, In Armored core Silent line the game freezes at certain missions. Specially the space satellite mission with another raven. I tried everything and i have no progress. Any ideas of how this could have happened? My guess be a memory cashing problem, something to do with the loading of assets. As in my game the vertex's don't load neither does the textures, but the Kernel is processing the same data over and over again in a loop:
![image](https://user-images.githubusercontent.com/13959909/54517000-a4d6eb00-49b4-11e9-92bb-164fba0d56d3.png)

Here are the specs i am currently running:
![image](https://user-images.githubusercontent.com/13959909/54517090-e10a4b80-49b4-11e9-8d2c-ecfa48843317.png)
![image](https://user-images.githubusercontent.com/13959909/54517128-f4b5b200-49b4-11e9-931b-1a4d2d1c5dcf.png)

I am using the latest version of the software: v1.8.0

**Comment by unknownbrackets** [comment]
That it's spending all its time in delay thread seems to mean that it has hung...

I think we'll need to do more hardware tests on the GE signals to figure out what about the pause signal we still have wrong.  Maybe it's a firmware version difference...

-[Unknown]

**Comment by unknownbrackets** [comment]
It would be useful to know what code this game has in its signal handler - specifically, what HLE functions it calls from it.  I'll try to do some more tests soon.

-[Unknown]

**Comment by stonelike** [comment]
Thank you for your efforts.  If I can provide any useful logs or such, please let me know.

**Comment by hrydgard** [comment]
Please try again - unknown's latest finding has good chances of helping this.

**Comment by hrydgard** [comment]
No feedback? moving to v1.10.0 for now.

**Comment by unknownbrackets** [comment]
I think given that it fixed Bleach and the lines of code xsacha pointed at would've caused similar behavior in the buggy case (and wrong behavior in other cases), we should just mark it v1.9.0 and close it.

If this is still an issue in the latest git builds or in versions newer than v1.9.0, please comment with more information and we'll reopen.

-[Unknown]
