### ISSUE TITLE
Automatic mapping of IPs (WLAN)

### ISSUE THREAD

**Issue by Heoz** [hrydgard/ppsspp#6001]
It's not really a issue but i used jpcsp a little and realise that if you remove manually set of ip adress in system.ini or whatever the name was it can be possible to adhocing without WM ware or other virtual machines, if you get what i want to say there should be automatic mapping of ip adress you could consider this since wlan is still beta :P

**Comment by unknownbrackets** [comment]
This issue seems all over the place, but what I gather is that the subject is two clients on the same machine.  That seems to be covered by #7276.

-[Unknown]
