### ISSUE TITLE
Multiple games slow, choking video (texture scaling + lazy hashing applied!)

### ISSUE THREAD

**Issue by DarkD** [hrydgard/ppsspp#6031]
I've said about this issue in Blazing Souls Accelate comment, but as it have nothing to do with that issue I thought it desires for separated issue. Hadn't found it mentioned anywhere else, so I've tried to pinpoint build from which it all began.
v.0.9.8-357 working flawless.
v.0.9.8-365 video became the way it is now(though not exactly as there was swapped color channels in that build, but speed-wise exactly like there).

Issue - in multiple games video from perfect became slow, choking.
The ones I've tried - Dissidia Final Fantasy (ULUS10437), Fate/Tiger Colosseum Upper (ULJM05360), Lord of Arcana (ULUS10479), R-Type Command (ULUS10343), Tenchu: Shadow Assassins(ULUS10419) and the game I'm always checking if it started to work properly - Blazing Souls: Accelate (ULUS10527). Could be easily seen in intros and other movies in those games.

Note that same kind of issue present in SoulCalibur: Broken Destiny (ULUS10457), but it's not appearing on 365 it starts at 544 and last version without issue was 531.

As there's a gap with no builds by buildbot between 357 an 365, here's changelog(including 365):
-Merge: 7ef2678 c7aafadMerge remote-tracking branch 'origin/master' into Universal_Audio_Branch
-Fix wrong stretch in Wildarm XF (non-buffered mode)
-Fix texture cache invalidation.
-Add #extension GL_EXT_shader_framebuffer_fetch : require
-Avoid unbinding the current fbo on block transfer.Improves God of War performance by 25% (at least in the demo.)
-Optimize the case of a direct byte copy.Small improvement (like 3.5%) in God of War.
-Interpret iForceMaxEmulatedFPS based on 1.001 NTSC.
-Merge: dc0eea0 ed99c33Merge pull request #5877 from unknownbrackets/gpu-minorImprove God of War performance
-Merge: 4eedd7a e8d0cc6Merge remote-tracking branch 'origin/master' into Universal_Audio_Branch
-Support sceMp3LowLevel*Gundam G custom BGM is supported now :)
-Merge: 35a31cd ca6e463Merge pull request #5873 from unknownbrackets/texcacheFix texture cache invalidation...
-correct some comments.
-more cleanup
-Use GL_BGRA for 32 bit textures on Windows.25% improvement in Popolocrois, probably decent gains in other games using32-bit textures often. FF2 for example doesn't.
-implement sceMp3GetFrameNum
-Merge: a285d04 943353fMerge pull request #5874 from unknownbrackets/texcache2Use GL_BGRA for 32 bit textures on Windows.

Changelog between 531 and 544 including 544:
-Move POWER_VMEM_IN_USE to sceKernel.h
-Let desktop SDL builds see the fullscreen option, too. There's no reason they can't.
-Merge: 4eb7991 ed6ea61Merge pull request #5979 from unknownbrackets/multithreadFix deadlock in multithreading
-Merge: 56018fb e61a151Merge pull request #5964 from raven02/patch-26Add Vertex texture/color GE commands
-Merge: a799941 27fbf4cMerge pull request #5977 from unknownbrackets/psmfplayerFix video flicker, add memchecks and detect no audio better
-Merge: 7fd8404 21e4dc6Merge pull request #5973 from raven02/patch-30Move POWER_VMEM_IN_USE to sceKernel.h.

I know it's kinda late, it's already 594, but still hope that helps.

**Comment by unknownbrackets** [comment]
How about nowadays?  There were some improvements to how often we decimate and a few other things.

-[Unknown]

**Comment by DarkD** [comment]
Checked now.
Well, pretty much same - enabling scaling+LTC causes chocking in videos of those I've mentioned and FFT with Riviera same in same places(fade in/fade out) even without LTC.
Though it seems kinda faster than I remember, but maybe it's my imagination.

**Comment by unknownbrackets** [comment]
Has this improved now?  We only scale so many texels per frame now, and fixed an issue that would cause us to keep re-decoding a texture if it started changing frequently (which may have interacted badly with the lazy texture hashing method.)

-[Unknown]

**Comment by DarkD** [comment]
Man, how much I want to say it's resolved. Sadly, no, but it indeed looks like being faster than it was.

**Comment by unknownbrackets** [comment]
There's been another change (I think since last comment) where we only has some of larger textures that are used as videos, in many cases.  It may help.  Maybe we could use this even to scale only part of the texture, hmmm..

The other option, as I mentioned, is this:

```c++
				// Start it over from 0 (unless it's safe.)
				iter->second.numFrames = type == GPU_INVALIDATE_SAFE ? 256 : 0;
				if (type == GPU_INVALIDATE_SAFE) {
					u32 diff = gpuStats.numFlips - iter->second.lastFrame;
					if (diff < TEXCACHE_FRAME_CHANGE_FREQUENT) {
						iter->second.status |= TexCacheEntry::STATUS_CHANGE_FREQUENT;
					}
				}
```

It's probably the best solution, although I'd like the texel scaling limit to be good enough on its own...

-[Unknown]

**Comment by DarkD** [comment]
Sorry for being late with reply - checked games I've mentioned with scaling+LTC on v 1.1.1-500 and here's the results:
R-Type Command - no choking, normal speed, tiny 1px artifacts on bottom line;
Dissidia Final Fantasy - seems to be faster, but still choking;
Blazing Souls: Accelate - same as it was + large amount of 1px artifacts on top and bottom of screen;
Fate/Tiger Colosseum Upper - same as was;
Lord of Arcana - same;
Tenchu: Shadow Assassins - looks perfect to me.

**Comment by unknownbrackets** [comment]
How is this now, in the latest git build?

-[Unknown]

**Comment by DarkD** [comment]
OK, testing on v 1.1.1-523:
R-Type Command - perfect;
Dissidia Final Fantasy - perfect;
Blazing Souls: Accelate - artifacts on top and bottom 1px lines(scaling causing them, not LTC), playback is perfect;
Fate/Tiger Colosseum Upper - perfecto, gao!~
Lord of Arcana - perfect;
Tenchu: Shadow Assassins - perfect.
It didn't helped Reviera so it's probably different issue and this one should be closed as it's solved! Hoorays!

**Comment by unknownbrackets** [comment]
Cool, I'm going to close then.  I think the 1px lines are an artifact of scaling, not sure they are really fully solvable.

-[Unknown]
