### ISSUE TITLE
Dynasty Warriors Strikeforce Freeze

### ISSUE THREAD

**Issue by kraosdada** [hrydgard/ppsspp#6040]
In This game, after you complete Chapter 5 (at least as Shu) you cannot get past the end cutscene, when you wait for it to end or skip it, the emulator freezes and has to be taskkilled

i use a Galaxy S2 with Gingerbread, and PPSSPP V9.8-598-G7A69A6A

**Comment by ppmeis** [comment]
No reported again. Also, tehre's a lot of gameplays on Youtube from Windows and Android devices without issues. So LGTM.

**Comment by unknownbrackets** [comment]
Sounds good.  Closing based on that, we can reopen if someone's still able to reproduce without using a potentially broken savestate.

-[Unknown]

**Comment by nfjorgebueno** [comment]
thank you very much, works perfect
