### ISSUE TITLE
glGen* :  Allocate names in blocks, consider handling uniforms as large arrays

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#6045]
Epic Games have posted an interesting presentation on mobile graphics performance here:

https://developer.nvidia.com/sites/default/files/akamai/gameworks/events/gdc14/GDC_14_Bringing%20Unreal%20Engine%204%20to%20OpenGL.pdf

In the "Top Offenders" section, glGen* is mentioned as expensive. We call glGenBuffers a lot in the vertex cache, it might be worth allocating blocks of IDs and cache them before use.

Also, they have an interesting idea to not use individual uniforms at all in ES2 (where uniform buffers are not supported) but instead simply use a single array of vec4s per shader. These can be updated in large chunks, which may be cheaper than many individual glUniform calls. (on the other hand, the bulk of updates in most of the heavy games only update a single or a few uniforms per draw call so might not be much of a win for PSP games).

**Comment by unknownbrackets** [comment]
So the biggest thing remaining here is to see what the trade-off is in uploading an array of uniforms even when only one or two change?

We did some similar changes on Direct3D and it seemed to help there, I think?

-[Unknown]

**Comment by hrydgard** [comment]
Yes, although I don't think I'll work on this anytime soon. More likely I'll try a UBO solution for ES 3.0 and later - ES 2.0's market share is bound to slowly shrink.
