### ISSUE TITLE
Innocent Life textures flickering and incorrect light (vertex cache)

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#6066]
On the farm,the texture flickering with hw transform,sw transform is fine.if disable vertex cache,the ground would be darker,these cases alway happens,the oldest build i tested is 0.9.1-1963.much older build crashes.

hw transform flickering video
https://www.youtube.com/watch?v=SfMZSRkfA5w

vertex cache on
![01](https://cloud.githubusercontent.com/assets/3481559/2937665/63e8af7e-d8c2-11e3-942e-d9cf6b10d4c0.png)

vertex cache off
![02](https://cloud.githubusercontent.com/assets/3481559/2937667/6ed67876-d8c2-11e3-88f1-2d1af769dab6.png)

the following issue is fixed by https://github.com/hrydgard/ppsspp/pull/6082
~~outside the farm,hw transform is alway fine.with sw transform firckering and incorrect light happens~~ ~~sincehttps://github.com/hrydgard/ppsspp/commit/9b1302cf77dbbd0c108adaab2692508498ada3b8~~

~~sw transform flickering video~~
~~http://youtu.be/l39scfC2v7g~~

~~incorrect light~~
~~(https://cloud.githubusercontent.com/assets/3481559/2937681/81c6d876-d8c3-11e3-9f4f-adbdea2e2ff8.png)~~

~~correct light~~
~~(https://cloud.githubusercontent.com/assets/3481559/2937682/88cf80b4-d8c3-11e3-80a2-a2f3176e54d6.png)~~

**Comment by daniel229** [comment]
Marvel Ultimate Alliance 2's problem is since https://github.com/hrydgard/ppsspp/pull/6737

**Comment by unknownbrackets** [comment]
If I recall, the biggest difference is that the normals are not scaled in software transform the same way (127 vs 128.)  Maybe that indicates 127 is correct for normals?  Not sure.

-[Unknown]

**Comment by piau9000** [comment]
Can this be tested (the thing about 127/128?
Or does it requires a new build?

**Comment by unknownbrackets** [comment]
The 127/128 theory requires a code change.

-[Unknown]

**Comment by unknownbrackets** [comment]
Has this changed with the fix for #4155?

Could you try exporting a GE frame dump?  These help a lot.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by Panderner** [comment]
The daylight works fine either vertex cache on and off on OpenGL:
![Screenshot_2020-04-17-17-43-28-59_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/79557155-b0737480-80d4-11ea-8680-4725f27358e3.png)
