### ISSUE TITLE
Ikki Tousen Xross Impact load save wrong

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#6068]
v0.9.7.2-287-g78ce9b3 (Good)
![good](https://cloud.githubusercontent.com/assets/2177532/2938407/57657ac4-d909-11e3-9120-54380161e373.jpg)

v0.9.8-627-g155dcee(Wrong)
![wrong](https://cloud.githubusercontent.com/assets/2177532/2938409/896e589c-d909-11e3-9efa-57cbae9579a3.jpg)

Git bisect result
![1](https://cloud.githubusercontent.com/assets/2177532/2938410/9cd10470-d909-11e3-8f3e-8e64c9f7b875.png)

This commit
https://github.com/hrydgard/ppsspp/commit/ec4ce7e7e56000527d9fe2561d30acbc0f62d1a3

v0.9.7.2-287-g78ce9b3 log:
https://gist.github.com/sum2012/e86a3a7ea3a45fd06b76
v0.9.8-627-g155dcee log:
https://gist.github.com/sum2012/b51c055c0a2382282447

**Comment by daniel229** [comment]
Fixed.

**Comment by sum2012** [comment]
thanks test

**Comment by sum2012** [comment]
In my email.someone tell me that this game save data error again.
I need to work now,no time to test
