### ISSUE TITLE
Multithreaded option enabled crashes ppsspp

### ISSUE THREAD

**Issue by psennermann** [hrydgard/ppsspp#6096]
On Windows XP and Android with Multithreaded option enabled, games keep on crashing - tested with Assassin's Creed, Justice Hero League and 3rd birthday (this last one only on WinXP) on ppsspp 9.8.691 (XP) and 9.8.685 (Android):
On Android: games "close to Android desktop" without an error message
On Windows XP: games crash with a memory could not be read error
As soon as possible I'll try to find the revision that caused the issue

Assassin's Creed - WinXP

![image](https://cloud.githubusercontent.com/assets/6342467/3004883/7459a93a-ddc2-11e3-9941-5b66e1fcd640.png)

**Comment by zminhquanz** [comment]
some game is crash when i play at some distination in game , ex : The 3rd Birthday , Final Fantasy VII Crisis Core
