### ISSUE TITLE
God of War - "it is not possible save entry into the game on the save point" (save issue?) [user-reported]

### ISSUE THREAD

**Issue by angelXwind** [hrydgard/ppsspp#6118]
Received a report from an user saying how "save entries" and "save points" were both broken in God of War.

These are apparently native PSP save functions that cause PPSSPP to instantly crash.

His description:

"The issue is in the game GOD, is not possible save entry into the game on the save point, this make the ppspp close immediately."

User is using an iPhone 5s on iOS 7.0.6.

**Comment by unknownbrackets** [comment]
I think there was some struct alignment issue in an older version of PPSSPP.  I'm pretty sure we'd have heard if this was happening on other platforms, and I know there were iOS specific memory corruption problems, possibly related to jailbreak implementations.

As such, I'm closing this.  If it still happens, please comment with more information.

-[Unknown]
