### ISSUE TITLE
Super Robot Wars Z - Severe alpha blending/transparency issues described as "squares" [user-submitted]

### ISSUE THREAD

**Issue by angelXwind** [hrydgard/ppsspp#6124]
Got a submission about the game Super Robot Wars Z not working correctly on multiple iOS/Android devices.

The issue sounds like some sort of alpha blending/transparency issue, as the issue is described as "the pictures becoming a lot of squares".

...Or it could be a texturing issue. Asked for a screenshot, the guy replied without one.

Raw email below:

"boss'cannot run super robot war z.there r a lot of segment that shelter the pics in the war，make me crazy.update.beg u.

i use ipad3 ipad mini2 iPhone4s iPhone5s galaxy s3 also suffer this bug. run.oh no

it s the same situation.u can try.problems with super robot war og and z.when enter in war.the pics become  a lot of squares.make me crazy.

when will come out the new edition?"

**Comment by unknownbrackets** [comment]
We're getting reports that this is working, although of course it's not fast.  Unfortunately, that's hard to workaround since it's using max blending.

-[Unknown]
