### ISSUE TITLE
Black rock shooter (USA)

### ISSUE THREAD

**Issue by reyzon214** [hrydgard/ppsspp#6126]
It happens when battle starts. Sound is good. The only problem is this black screen. Non buffered rendering shows the scene for miliseconds and then goes to black.

![untitled](https://cloud.githubusercontent.com/assets/7686838/3073951/b3dc73e4-e317-11e3-9053-083586ca9ad7.jpg)

**Comment by unknownbrackets** [comment]
Does it work in Direct3D 9?  Usually Intel likes Direct3D better.

-[Unknown]

**Comment by ppmeis** [comment]
Tested in latest build. It works fine for me:
![image](https://cloud.githubusercontent.com/assets/4381277/11616599/5fc4fcea-9c7f-11e5-8d06-626ef2678516.png)
