### ISSUE TITLE
ProQuake 4.71 small glitches when rendering explosions

### ISSUE THREAD

**Issue by pal1000** [hrydgard/ppsspp#6187]
Requirements to reproduce:
-Create a subdirectory in PSP\GAME. I'll call it "UMD0:\".
-Get ProQuake 4.71: http://quakeone.com/proquake/proquake_471_psp.rar. Only EBOOT.PBP and m_bttns.lmp are necessary from the archive, the rest are just text and source code files. Extract EBOT.PBP in UMD0:\ and m_bttns.lmp in UMD0:\ID1\GFX creating the missing directories.
-Get the PAK0.PAK and PAK1.PAK  from the original PC version and put them in UMD0:\ID1.
-Put the save file from <a href='http://pal1000.3x.ro/shared/recover/entertain/Quake/PSP-debug/S1.SAV'>here</a> in UMD0:\ID1.

Load the game, pick up the rune and quickly hide from Chthon attack. Chthon will keep striking the other side of the wall with explosions causing the glitch.  
This glitch doesn't happen on JPCSP. The log console doesn't show any warnings.
If I turn on Anti-Aliasing in-game it reduces the glitch a bit but it causes small screen shaking.

**Comment by benderscruffy** [comment]
does this still happen in the latest version ??

**Comment by pal1000** [comment]
No it doesn't happen anymore so closing.
