### ISSUE TITLE
Gran Turismo theater mode video playback issue

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#6189]
Go to theater to play intro video,it is missing sound,and video speed is 2X fast forward for the first time,the second time and after it plays video normally.Tested builds between0.91 and 0.98-917,all have the bug.

debug log(rename jpg to rar)
log twice video playback. 
![ppsspplog](https://cloud.githubusercontent.com/assets/3481559/3130040/456d684a-e7f0-11e3-9e25-1231692b70f5.jpg)

**Comment by benderscruffy** [comment]
v1.8.0-3-gd6d6dbb77
still happens

**Comment by benderscruffy** [comment]
using https://github.com/hrydgard/ppsspp/commit/0126bc181c92cc63dbfa923ddc7b589c56a840ba
doesn't happen anymore 
can be closed
