### ISSUE TITLE
Bloom issues related to upscaling.

### ISSUE THREAD

**Issue by LunaMoo** [hrydgard/ppsspp#6192]
I'm not sure if this can be resolved, but I didn't saw it listed properly. Make note this issue is not not related to excessive bloom issue that some devices still have(?) even through same game was used as an example.

It can be easily reproduced in any game that uses bloom for example any of the game from God Eater series, Assassin's Creed etc. here's an example of how nice bloom looks like on x1 rendering res:
![npjh50832_00070](https://cloud.githubusercontent.com/assets/5485237/3134882/51018d90-e82b-11e3-943c-e143070b26be.jpg)
^ it's smooth, looks rounded, fits the whole screen and looks correctly, clearly seen as a light.

 However increasing rendering res pretty much breaks the whole idea of bloom, here's an example made at x10 just to clearly show what I mean:
![npjh50832_00071](https://cloud.githubusercontent.com/assets/5485237/3134941/1308e398-e82c-11e3-8efd-c06780fc2edc.jpg)
^ what we see here is sharp edges, squareish ugliness and doesn't even fit the screen correctly which can be seen by few lines from bottom right so I guess it has also offset issue.

 If the bloom affects whole character, face or anything else with details, normally it looses those details thanks to ultra low res used in creating it and we see nice bloom, however any kind of higher upscalling pretty much restores those details and bloom simply is not bloom anymore. Ends up nearly as sharp as the original object and looks like a ghost copy of the character, it's probably better seen in assassin's creed but I don't have it.

 I saw those issues in other emulators as well, bloom offset in pcsx2 for example is dealt with like 3 different offset hacks or blah removed completely:/. However never saw a single solution for the sharp bloom which is not a bloom anymore, don't have much hope for this since most people don't even seen this as issue in the first place:].

 I guess we can't really change how the game does it's bloom, but would it be possible to make some sort of hack/workaround for this which would restore x1 rendering res for the source that is taken for the bloom? Or at least divide the resolution of the effect by the rendering res multiplier used and then multiply it back with linear filtering to loose the details which should not be part of bloom. Anything like that possible? Can this be done during blending or not really?

 Currently there are no solution in ppsspp for those, most people just use a non-buffered rendering which has nothing to do with how those games should look like, maybe few others, like me end up using native res which looks perfect aside of being low res ofc:].

 x2 rendering res seems mostly acceptable as well, but already far from perfect:
![npjh50832_00072](https://cloud.githubusercontent.com/assets/5485237/3135448/5379547e-e833-11e3-9245-13c0f85fe094.jpg)
^ offset can be easily visible like here near light sources at the bottom/right side of the screen and the bloom layers start getting sharper which can be seen on the lights on the wall getting more recognizable squareish shapes, so it depends on the scene really, can get really ugly at times especially when affecting something that actually moves.

 Sorry for lenghty description of a kind of low priority issue:]. If this cannot be fixed in any way, I don't mind closing it, it's not much of an emulation bug, rather a feature issue.

**Comment by unknownbrackets** [comment]
Maybe a simple solution would just be to keep framebuffers smaller than a certain size at 1x (as an option??)  While this wouldn't add passes, it'd probably improve the issue.  Although games can of course use smaller buffers for other things (especially shadows), this would probably be an acceptable tradeoff?

-[Unknown]

**Comment by LunaMoo** [comment]
With non hd content, lots of things look better without visible details, so even if it would affect some other things like shadows or some other fx, it would still be a nice option to have.:)

**Comment by LunaMoo** [comment]
Tried to do it myself, took values out of the moon without checking anything and changed:
<pre><code>
		vfb->renderWidth = vfb->bufferWidth * renderWidthFactor;
		vfb->renderHeight = vfb->bufferHeight * renderHeightFactor;
</code></pre>
to:
<pre><code>
	if (vfb->bufferWidth < 300 || vfb->bufferHeight < 200)
	{
		vfb->renderWidth = vfb->bufferWidth;
		vfb->renderHeight = vfb->bufferHeight;
	} else {
		vfb->renderWidth = vfb->bufferWidth * renderWidthFactor;
		vfb->renderHeight = vfb->bufferHeight * renderHeightFactor;
	}
</code></pre>
under FramebufferManager::ResizeFramebufFBO in framebuffer.cpp, and the results are quite nice:)
Here's a comparism with hack vs without it, both using x10 rendering res:
![npjh50832_00001](https://cloud.githubusercontent.com/assets/5485237/5856739/2a9513fe-a246-11e4-92cd-ecb82257dc66.jpg)
![npjh50832_00002](https://cloud.githubusercontent.com/assets/5485237/5856741/2f311674-a246-11e4-9fd2-98930a9fd529.jpg)

Seems to work with Gladiator Begins shiny weapons as well, don't remember other games I have which I could check for it now, but I'm really happy with the result.:) Would be nice to test it with more games affected by the issue and then just make an option with something that works well.

**Comment by hrydgard** [comment]
That looks a lot nicer for sure, good idea.

Btw, to write code in github markdown, simply indent it with four spaces. I fixed up your post.

**Comment by LunaMoo** [comment]
Cool, thanks for the help:), oh and I did notice one side effect which I don't really know why happens, during some transition screens which should be completely black, with that code it get's:
![npjh50832_00003](https://cloud.githubusercontent.com/assets/5485237/5857199/024a2eee-a24a-11e4-9dd3-d0e80f8a7785.jpg)
it draws that glitchy line a few times from the top to bottom a few times. not sure why size change would make a color weirdness, maybe it tries to clear it or something.

**Comment by unknownbrackets** [comment]
Hmm, I would try for more like w<=200 / h<=100, since most bloom scales down multiple times, but not sure if we'd catch every smaller size properly.

-[Unknown]

**Comment by LunaMoo** [comment]
I just tested and unfortunately smaller range seems to give an ugly effect sometimes, here's an example from Gladiator Begins:
300 /  200
![ulus10528_00043](https://cloud.githubusercontent.com/assets/5485237/5864438/5f8cd8c6-a282-11e4-9c1c-91232e38cd86.jpg)

200 / 100
![ulus10528_00044](https://cloud.githubusercontent.com/assets/5485237/5864440/682262a8-a282-11e4-82a9-117a1f923b27.jpg)


Seems that it only looks good if it's resized for all steps, made me want to test the opposite:].

**Comment by unknownbrackets** [comment]
Another option might be stepping down the scale proportionately.  For example, for a 240x136 framebuffer, at 10x, make it only 5x or 3x.  Not sure that would work, though.  It might have less side effects on non-bloom-related framebuffers, though.

-[Unknown]

**Comment by LunaMoo** [comment]
Would it be a valid option to let it be customizable? With per-game settings now, people could tune it as much as they want.

 Althrough I must say, I just tested rather crazy 460 / 250 and didn't noticed anything rendering in lower res except bloom.:]

**Comment by hrydgard** [comment]
If we can find a couple of universal presets that work, that would be good of course. Fully customizable is a bit much I think...

**Comment by LunaMoo** [comment]
Gladiator Begins which had that problem with < 200 / 100 seems to be using size 256x272 for the first step of weapon bloom, Coded Arms which also have bloom effects(althrough they're rather ugly even on psp^^) used 256x256 for the first step, didn't saw any game with higher than those, but I don't have soo many games affected by this issue in the first place.
 I did tested more games by printing the size to the log, and aside from bloom, I saw it being used for blur, and at least with my testing nothing really else. Maybe it's actually rare.

 Any suggestions for the presets and hack name(Bloom hack?)? If nobody else wants, I could do it maybe tomorrow.
I would make it something like:
- aggressive < 480/272  //just in case some affected game use lots of steps or something
- balanced <= 256/128  //because 256 is highest I saw during my tests
- safe <=128/64 //that seems to be max I saw for GE2 and PE3:The Third Birthday
Does that seem reasonable?

**Comment by hrydgard** [comment]
"Bloom effect smoothing"? Maybe disable the setting if the users chooses 1x rendering, as then it does nothing?

**Comment by LunaMoo** [comment]
Borrowed Assassin's Creed just to check, and bloom looks nice with "Balanced" preset ~ seems to be using 242x138, 122x70 and 62x36.
![acb](https://cloud.githubusercontent.com/assets/5485237/5889143/d4ba6774-a419-11e4-955c-8fd075123b8d.jpg)

Should we keep this issue open just in case for some games this hack or it's presets wouldn't be enough? As far as I see, it works nice enough that it could be +1 to closed ones.:)
