### ISSUE TITLE
Patapon 3 adhoc not working 

### ISSUE THREAD

**Issue by Michal1324** [hrydgard/ppsspp#6203]
So I just tried to use with newest build of ppsspp adhoc with patapon 3 and I tried to play mission but I m keep geting connection error there is what console has wrote during it

33:21:118 user_main    E[NET]: HLE\sceNetAdhoc.cpp:2152 UNIMPL sceNetAdhocMatchingGetMembers(1, 0bfff41c, 00000000)
33:21:118 user_main    E[NET]: HLE\sceNetAdhoc.cpp:2152 UNIMPL sceNetAdhocMatchingGetMembers(1, 0bfff41c, 0bfff3bc)
33:21:118 user_main    W[MM]: MemmapFunctions.cpp:92 ReadFromHardware: Invalid address 3f800000
33:24:721 user_main    E[NET]: HLE\sceNetAdhoc.cpp:2152 UNIMPL sceNetAdhocMatchingGetMembers(1, 0bfff41c, 00000000)
33:24:721 user_main    E[NET]: HLE\sceNetAdhoc.cpp:2152 UNIMPL sceNetAdhocMatchingGetMembers(1, 0bfff41c, 0bfff3bc)
33:24:721 user_main    W[MM]: MemmapFunctions.cpp:92 ReadFromHardware: Invalid address 3f800000
33:28:325 user_main    E[NET]: HLE\sceNetAdhoc.cpp:2152 UNIMPL sceNetAdhocMatchingGetMembers(1, 0bfff41c, 00000000)
33:28:325 user_main    E[NET]: HLE\sceNetAdhoc.cpp:2152 UNIMPL sceNetAdhocMatchingGetMembers(1, 0bfff41c, 0bfff3bc)
33:28:325 user_main    W[MM]: MemmapFunctions.cpp:92 ReadFromHardware: Invalid address 3f800000
33:31:928 user_main    E[NET]: HLE\sceNetAdhoc.cpp:2152 UNIMPL sceNetAdhocMatchingGetMembers(1, 0bfff41c, 00000000)
33:31:928 user_main    E[NET]: HLE\sceNetAdhoc.cpp:2152 UNIMPL sceNetAdhocMatchingGetMembers(1, 0bfff41c, 0bfff3bc)
33:31:928 user_main    W[MM]: MemmapFunctions.cpp:92 ReadFromHardware: Invalid address 3f800000
33:35:532 user_main    E[NET]: HLE\sceNetAdhoc.cpp:2152 UNIMPL sceNetAdhocMatchingGetMembers(1, 0bfff41c, 00000000)
33:35:532 user_main    E[NET]: HLE\sceNetAdhoc.cpp:2152 UNIMPL sceNetAdhocMatchingGetMembers(1, 0bfff41c, 0bfff3bc)
33:35:532 user_main    W[MM]: MemmapFunctions.cpp:92 ReadFromHardware: Invalid address 3f800000
33:37:409 user_main    E[NET]: HLE\sceNetAdhoc.cpp:2103 UNIMPL sceNetAdhocMatchingStop(1)
33:37:409 user_main    E[NET]: HLE\sceNetAdhoc.cpp:2110 UNIMPL sceNetAdhocMatchingDelete(1)
33:37:409 user_main    E[NET]: HLE\sceNetAdhoc.cpp:1984 UNIMPL sceNetAdhocMatchingTerm()
33:37:410 user_main    W[NET]: HLE\sceNetAdhoc.cpp:932 UNTESTED sceNetAdhocctlDelHandler(0): deleted handler 0
33:37:411 user_main    E[NET]: HLE\sceNet.cpp:134 UNIMPL sceNetTerm()

**Comment by sum2012** [comment]
@Michal1324 can you re-test as network improved ?
PS: Current code cannot connect with same pc

**Comment by issuer** [comment]
Patapon 3 is working online on 1.0.

**Comment by unknownbrackets** [comment]
Okay, if there are more specific issues it might make more sense to report them separately.  Or really it's probably better to just keep similar adhoc issues in different games together since they're likely related.

-[Unknown]
