### ISSUE TITLE
Tales of Destiny 2 Black Screen On Android

### ISSUE THREAD

**Issue by mckimiaklopa** [hrydgard/ppsspp#6232]
Except on Battles,on the title screen and on FMVs,this game just displays a black screen sometimes overlayed with some objects(on dialogues,it is just a black screen with text)
![screenshot_2014-06-05-14-28-51](https://cloud.githubusercontent.com/assets/5818289/3183969/48c9c60c-ec7b-11e3-9ab8-a46282ba1ea2.png)
![screenshot_2014-06-05-14-29-17](https://cloud.githubusercontent.com/assets/5818289/3183972/536940d8-ec7b-11e3-9df2-3e5f9f9b6dc8.png)

I tried builds 0.9.8-48 and 0.9.8-1028 with all the possible settings I can think of and it does not change anything about the issue

My specs
http://www.gsmarena.com/samsung_galaxy_s_duos_2_s7582-5876.php

**Comment by unknownbrackets** [comment]
Has this changed at all?  I wonder if it was related at all to the PowerVR issue that had to do with using GL_CONSTANT_COLOR when not necessary.

-[Unknown]

**Comment by unknownbrackets** [comment]
Does this still happen in the latest version?  There was a problem related to viewport and render resolution that might've caused this on certain devices (and maybe on Broadcom even at 1x.)

-[Unknown]

**Comment by unknownbrackets** [comment]
Let's hope it has improved.  If it hasn't, we'll have to wait for more information to do anything about it.

Closing for now due to lack of updates / information.

-[Unknown]
