### ISSUE TITLE
Gundam AGE Universe Accel/Cosmic Drive - Characters transparent/spotty

### ISSUE THREAD

**Issue by AGXVoidBurner** [hrydgard/ppsspp#6243]
Same problem as #2579, but Force depth write doesn't "fix" the problem any more since around v0.9.8-966-g0c7c736 or so 
![npjh50566_00001](https://cloud.githubusercontent.com/assets/7819760/3206603/5deb444e-edc9-11e3-88f3-328c83e01e2e.jpg)

**Comment by benderscruffy** [comment]
v1.8.0-3-gd6d6dbb77
still happens
![gundam](https://user-images.githubusercontent.com/2696404/54484606-1de71d00-48a5-11e9-9043-ea62f907c885.PNG)
GE dump
[NPJH50566_0001.zip](https://github.com/hrydgard/ppsspp/files/2974727/NPJH50566_0001.zip)

**Comment by unknownbrackets** [comment]
Thanks.  The dump shows the same on a PSP, which means a missing block transfer or decimated FBO is probably to blame.

![NPJH50566_#6243_gundam_bg](https://user-images.githubusercontent.com/191233/54484795-3403c780-482a-11e9-801c-90afb51a34b6.png)
(I'm assuming the eyes are just from a slightly different frame.)

-[Unknown]

**Comment by benderscruffy** [comment]
yep the eyes from a different frame

**Comment by Panderner** [comment]
![Screenshot_2020-10-14-15-50-30-11_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/95960892-eb155a00-0e36-11eb-99a1-e90d133a60bd.png)
Character talking backgrounds are ok in recent versions of PPSSPP. but it breaks the background if you disable block transfer effects or using fast forwarding

**Comment by Gamemulatorer** [comment]
This still an issue?

**Comment by unknownbrackets** [comment]
I believe this game requires depth buffer copies, so it's an issue on GLES2.  But for GLES3/Vulkan/etc. it should be working fine.  I'm not sure if there's really any reasonable way to fix this on GLES2 except maybe some frankenstein of "skip buffer effects"... and not even sure that would work.

-[Unknown]

**Comment by Gamemulatorer** [comment]
Yes, this issue can't be fixed with opengl 2.0 just like hrydgard comment https://github.com/hrydgard/ppsspp/issues/10777#issuecomment-525257605

**Comment by hrydgard** [comment]
Alright. I don't think we'll get around to doing some kind of workaround here, and it's fixed on GLES3+. So I'll close.
