### ISSUE TITLE
Power Stone Collection - Missing Arrow / Gem Locator (depth testing related?)

### ISSUE THREAD

**Issue by Avastia** [hrydgard/ppsspp#6257]
The arrow that locates gems on the mini-map does not display properly.
Using PPSSP 9.8-1088, default settings.

![no-arrow](https://cloud.githubusercontent.com/assets/4729731/3212018/dcba9b90-ef3f-11e3-9ca3-cf5e1cc638e9.jpg)

**Comment by unknownbrackets** [comment]
Has anything changed here?

Can you try using the GE debugger to see what's going on when it is drawing in that area?  Is it ever drawing a shape that looks like an arrow there?

https://github.com/hrydgard/ppsspp/wiki/How-to-find-a-graphic-issue-with-the-GE-debugger

-[Unknown]

**Comment by Avastia** [comment]
I will try it later today. Sorry for the late response.

**Comment by Avastia** [comment]
![powerstone-bug-ppsspp](https://cloud.githubusercontent.com/assets/4729731/6588283/a9272736-c74c-11e4-8387-781c60542482.jpg)

Thanks for the link for using the GE debugger (that thing is amazing!). I've taken a screen shot or where-a-bout the triangle is supposed to appear. I played with the settings in ppsspp (direct3d9, opengl, buffed, non-buffed...) and none of them displayed the arrow. Please note I am playing this on my Windows 8.1 computer.

Here is the video of the arrow in action on a PSP: https://www.youtube.com/watch?v=Cq2pgPU_Y_k&t=87 (Go to 1:22)

**Comment by unknownbrackets** [comment]
Can you copy and paste the other tabs when it's just write there?

As far as I can tell, the texture has some data in it under the red - if you double click it, it will zoom, and you can drag it around to be sure.  And the red on the right side is highlighting the right area, so it *should* draw.

That means this is probably an issue with either depth, stencil, blending, lighting, or it's related to that mysterious but rare "things float in the wrong places" bug we still haven't been able to track down.  The "Settings" and "Lighting" tabs will show me what the game is doing with those things, to narrow it down.

For example, maybe it's doing a ">=" depth test, which might make this the same issue as Phantasy Star Portable.

Also, there's a "software renderer" option (at the very end of the graphics settings.)  It will be very slow, but if that displays the arrow then at least it's not something super weird.  I recommend taking a savestate when on that screen, switching the software rendering setting, and then loading the savestate, so you don't have to deal with the slowness.

-[Unknown]

**Comment by Avastia** [comment]
![power-stone-arrow](https://cloud.githubusercontent.com/assets/4729731/6588875/59d42d10-c755-11e4-93c6-d6f319cbb234.jpg)

It does show up in software render on the bottom of this screen shot. Below I'll have the GE Debugger screen with a zoom on the arrow, as well as the copied/pasted data.

![power-stone-more](https://cloud.githubusercontent.com/assets/4729731/6588921/e67a9984-c755-11e4-9bf8-5915e5059460.jpg)

* * * *
FLAGS
Name	Value
Lighting enable	1
Light 0 enable	0
Light 1 enable	0
Light 2 enable	0
Light 3 enable	0
Clip enable	1
Cullface enable	0
Texture map enable	1
Fog enable	1
Dither enable	0
Alpha blend enable	1
Alpha test enable	1
Depth test enable	1
Stencil test enable	0
Antialias enable	0
Patch cull enable	0
Color test enable	0
Logic op enable	0
Depth write disable	0
* * * *
LIGHTING
Name	Value
Ambient color	ffffff
Ambient alpha	0000ff
Material update	ambient, diffuse, specular
Material emissive	000000
Material ambient	ffffff
Material diffuse	ffffff
Material alpha	0000ff
Material specular	ffffff
Mat. specular coef	1.000000
Reverse normals	0
Shade model	1
Light mode	1
Light type 0	0 (disabled)
Light type 1	0 (disabled)
Light type 2	0 (disabled)
Light type 3	0 (disabled)
Light pos 0	-0.640564, 0.707092, -0.299438 (disabled)
Light pos 1	0.000000, 0.000000, 0.000000 (disabled)
Light pos 2	0.000000, 0.000000, 0.000000 (disabled)
Light pos 3	0.000000, 0.000000, 0.000000 (disabled)
Light dir 0	0.000000, 0.000000, 0.000000 (disabled)
Light dir 1	0.000000, 0.000000, 0.000000 (disabled)
Light dir 2	0.000000, 0.000000, 0.000000 (disabled)
Light dir 3	0.000000, 0.000000, 0.000000 (disabled)
Light att 0	0.000000, 0.000000, 0.000000 (disabled)
Light att 1	0.000000, 0.000000, 0.000000 (disabled)
Light att 2	0.000000, 0.000000, 0.000000 (disabled)
Light att 3	0.000000, 0.000000, 0.000000 (disabled)
Lightspot coef 0	0.000000 (disabled)
Lightspot coef 1	0.000000 (disabled)
Lightspot coef 2	0.000000 (disabled)
Lightspot coef 3	0.000000 (disabled)
Light angle 0	0.000000 (disabled)
Light angle 1	0.000000 (disabled)
Light angle 2	0.000000 (disabled)
Light angle 3	0.000000 (disabled)
Light ambient 0	000000 (disabled)
Light diffuse 0	ffffff (disabled)
Light specular 0	000000 (disabled)
Light ambient 1	000000 (disabled)
Light diffuse 1	000000 (disabled)
Light specular 1	000000 (disabled)
Light ambient 2	000000 (disabled)
Light diffuse 2	000000 (disabled)
Light specular 2	000000 (disabled)
Light ambient 3	000000 (disabled)
Light diffuse 3	000000 (disabled)
Light specular 3	000000 (disabled)
* * * *
TEXTURE
Name	Value
Tex U scale	1.000000
Tex V scale	1.000000
Tex U offset	0.000000
Tex V offset	0.000000
Tex mapping mode	gen: tex coords, proj: pos
Tex shade srcs	000000
Tex mode	swizzled, 1 levels
Tex format	CLUT8
Tex filtering	min: linear, mag: linear
Tex wrapping	wrap s, wrap t
Tex level/bias	000000
Tex lod slope	000000
Tex func	modulate, RGBA
Tex env color	000000
CLUT	040fae00, w=0
CLUT format	ABGR 4444 ind & ff
Texture L0 addr	040fb000, w=256
Texture L1 addr	00000000, w=0
Texture L2 addr	00000000, w=0
Texture L3 addr	00000000, w=0
Texture L4 addr	00000000, w=0
Texture L5 addr	00000000, w=0
Texture L6 addr	00000000, w=0
Texture L7 addr	00000000, w=0
Texture L0 size	256x256
Texture L1 size	1x1
Texture L2 size	1x1
Texture L3 size	1x1
Texture L4 size	1x1
Texture L5 size	1x1
Texture L6 size	1x1
Texture L7 size	1x1
* * * *
SETTINGS
Name	Value
Clear mode	0
Framebuffer	00000000, w=512
Framebuffer format	4444
Depthbuffer	00088000, w=512
Vertex type	float texcoords, float normals, float positions
Offset addr	08000000
Vertex addr	08b908c8
Index addr	00000000
Region	0,0 - 479,271
Scissor	0,0 - 479,271
Min Z	00e000
Max Z	00ffff
Viewport 1	240.000000, -136.000000, -4096.000000
Viewport 2	2048.000000, 2048.000000, 61439.000000
Offset	1808.000000x1912.000000
Cull mode	1 (disabled)
Color test	pass if (c & ffffff)  !=  (000000 & ffffff) (disabled)
Alpha test	pass if (a & ff) > (00 & ff)
Stencil test	pass if (00 & 00) NEVER (a & 00) (disabled)
Stencil test op	fail=KEEP, pass/depthfail=KEEP, pass=KEEP (disabled)
Depth test	pass if src >= dst
Alpha blend mode	add: src.a, 1.0 - src.a
Blend color A	000000
Blend color B	000000
Logic Op	clear (disabled)
Fog 1	99998320493394448000000000000000.000000
Fog 2	0.000000
Fog color	000000
RGB mask	000000
Stencil/alpha mask	000000
Morph Weight 0	0.000000
Morph Weight 1	0.000000
Morph Weight 2	0.000000
Morph Weight 3	0.000000
Morph Weight 4	0.000000
Morph Weight 5	0.000000
Morph Weight 6	0.000000
Morph Weight 7	0.000000
Patch division	001010
Patch primitive	000000
Patch facing	000001
Dither 0	001d0c (disabled)
Dither 1	00f3e2 (disabled)
Dither 2	000c1d (disabled)
Dither 3	00e2f3 (disabled)
Transfer src	00000000, w=0
Transfer src pos	0,0
Transfer dst	00000000, w=0
Transfer dst pos	0,0
Transfer size	0,0

* * * *
VERTICES
X	Y	Z	U	V	Color
226.000000	248.000000	1.000000	0.139258	0.998633	00000000
248.000000	229.000000	1.000000	0.001172	0.998633	00000000
233.000000	256.000000	1.000000	0.139258	0.958203	00000000
254.000000	237.000000	1.000000	0.001172	0.958203	00000000
* * * *
MATRICIES
Name	0	1	2	3
World 0	-0.035326	-0.030811	0.000000	0.030811
World 1	-0.035326	0.000000	0.000000	0.000000
World 2	1.000000	0.000000	-5.937500	-21.000000
View 0	1.000000	0.000000	0.000000	0.000000
View 1	1.000000	0.000000	0.000000	0.000000
View 2	1.000000	0.000000	0.000000	0.000000
Proj 0	1.515564	0.000000	0.000000	0.000000
Proj 1	0.000000	2.674500	0.000000	0.000000
Proj 2	0.000000	0.000000	-1.012054	-1.000000
Proj 3	0.000000	0.000000	-0.603607	0.000000
Texgen 0	0.000000	0.000000	0.000000	0.000000
Texgen 1	0.000000	0.000000	0.000000	0.000000
Texgen 2	0.000000	0.000000	0.000000	0.000000
Bone #0 row 0	0.000000	0.000000	0.000000	0.000000
Bone #0 row 1	0.000000	0.000000	0.000000	0.000000
Bone #0 row 2	0.000000	0.000000	0.000000	0.000000
Bone #1 row 0	0.000000	0.000000	0.000000	0.000000
Bone #1 row 1	0.000000	0.000000	0.000000	0.000000
Bone #1 row 2	0.000000	0.000000	0.000000	0.000000
Bone #2 row 0	0.000000	0.000000	0.000000	0.000000
Bone #2 row 1	0.000000	0.000000	0.000000	0.000000
Bone #2 row 2	0.000000	0.000000	0.000000	0.000000
Bone #3 row 0	0.000000	0.000000	0.000000	0.000000
Bone #3 row 1	0.000000	0.000000	0.000000	0.000000
Bone #3 row 2	0.000000	0.000000	0.000000	0.000000
Bone #4 row 0	0.000000	0.000000	0.000000	0.000000
Bone #4 row 1	0.000000	0.000000	0.000000	0.000000
Bone #4 row 2	0.000000	0.000000	0.000000	0.000000
Bone #5 row 0	0.000000	0.000000	0.000000	0.000000
Bone #5 row 1	0.000000	0.000000	0.000000	0.000000
Bone #5 row 2	0.000000	0.000000	0.000000	0.000000
Bone #6 row 0	0.000000	0.000000	0.000000	0.000000
Bone #6 row 1	0.000000	0.000000	0.000000	0.000000
Bone #6 row 2	0.000000	0.000000	0.000000	0.000000
Bone #7 row 0	0.000000	0.000000	0.000000	0.000000
Bone #7 row 1	0.000000	0.000000	0.000000	0.000000
Bone #7 row 2	0.000000	0.000000	0.000000	0.000000
* * * *
LISTS
Start PC	PC	Stall	State	Started	Interrupted
0x09186080	0x0943C1E8	0x00000000	Running	Yes	No

**Comment by unknownbrackets** [comment]
@hrydgard I don't know much about fog.  Is that fog value unusual?  It looks unusual.

Anyway, it's also using a >= depth test.  To just make sure it's not that, go back to software renderer off, and step there in the GE debugger right when it's about to draw the arrow.

Then go to the Flags tab, and double click "Depth test enable".  This will turn the depth test off.

After that, click "Step Draw".  If the arrow appears (on the right side preview), that means it's something to do with depth testing.  If it doesn't appear, everything else looks legit so my money's on fog for now.

-[Unknown]

**Comment by Avastia** [comment]
Placeholder: Testing it now...

**Comment by ppmeis** [comment]
Tested with latest build. There's no arrow in radar.

**Comment by daniel229** [comment]
Fixed in #7920
