### ISSUE TITLE
Games that still need "Framebuffer to memory"

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#6261]
Our new blocktransfer support (Thanks to @unknownbrackets for fixing tons of issues!) and related memcpy overrides fix most of the games that previously needed the "Framebuffer to memory" modes. 

Are there any games that still need them? Otherwise I would like to remove or at least hide them in developer options, as they are slow and often cause instability.

~~#2713~~
~~#4739~~
~~#7695~~
~~#6880~~
~~#6547~~

**Comment by daniel229** [comment]
Maho Shojo Lyrical Nanoha A's Portable missing saveicon because of age 6 Decimating FBO.
it create FBO in the beginning of the battle
```
58:46:412 idle0        I[SCEGE]: Common\FramebufferCommon.cpp:331 Creating FBO for 001eb800 : 256 x 272 x 3
```

and it download  it to memory after battle.
```
59:52:709 user_main    W[G3D]: Common\FramebufferCommon.cpp:534 Memcpy fbo download 041eb800 -> 045eb800
```

**Comment by hrydgard** [comment]
Time to revisit this, I really want to kill off these additional rendering modes and only have non-buffered/buffered left. 

@daniel229 what's the status of Maho Shojo? And if that's the only remaining problem, I think losing save icons in that game is worth getting rid of these confusing options.

**Comment by unknownbrackets** [comment]
Any remaining issues here?  I think there's a good chance #8757 helped that game and might've helped others.

-[Unknown]
