### ISSUE TITLE
Final Fantasy Type-0 issues (texture scaling, MT crash)

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#6268]
We've gotten an influx of new users thanks to the release of the translation patch and looking at various forum threads they're hitting the following pain points:

  * Texture scaling slows down unexpectedly much (perhaps they choose Auto? it really overdoes it) (IMPROVED)
  * Crashes due to multithreading:

    "Game keeps crashing at the same point for me, "This is recon, weve found one of the jammers" as soon as i walk to boss exe crashes (ppsspp latest build)
     edit: It seems multithreading caused it, turned that off :P"

  * Massive slowdowns at the end of the tutorials have been reported, not sure if related to texture scaling

Other bugs:

  * First (and second and probably more) cutscene after starting the game won't play (Android only, works on Windows)  (FIXED)

  * When having just defeated an enemy and when grabbing phantoma, the screen turns black for a second on Tegra.

  * Cracks in geometry + z-fighting on some hardware only

  * The Codex issue is a bug with the translation patch. Seems to usually work if you in-game save and load (not states). So not a bug in PPSSPP.

I think we need to change how we expose texture scaling in the interface. The slowdowns aren't as extreme anymore when texture scaling as I've added a hauristic that prevents more than a certain number of texels per frame to be scaled.

**Comment by daniel229** [comment]
That problem https://github.com/hrydgard/ppsspp/issues/6268#issuecomment-45570263 in star ocean was fixed in https://github.com/hrydgard/ppsspp/pull/6822

**Comment by unknownbrackets** [comment]
So what's left here?  z-fighting, black screen on tegra, and multithreaded?  Do we need to keep this open?

-[Unknown]
