### ISSUE TITLE
Feature Request: Crop to display (1:1 pixel mapping)

### ISSUE THREAD

**Issue by RadarNyan** [hrydgard/ppsspp#6272]
When playing games on 1080p display with 4xPSP resolution, the render resolution would be 1920x1088 then it would be resized to 1920x1080 with black borders on left and right side to keep aspect radio.

Currently, the only possible way to make game screen fill entire 1080p display is using Stretch to display, which isn't so noticeable since PSP resolution is very near 16:9. But there certainly is a better method: just crop the original screen (in this case, cut out 4 pixels on both top and bottom, 1088 -> 1080) to make it a true 16:9 resolution, then resize it (if necessary) to fill the display.

By this way, we would have game screen fill entire display and actually keep the aspect radio. If we're rendering at a proper resolution (eg: 4xPSP FHD, 8xPSP UHD) we would get 1:1 pixel mapping on a proper display.

**Comment by unknownbrackets** [comment]
I believe this is now implemented in the "display layout editor" by @LunaMoo.

If I'm mistaken please feel free to comment and we'll reopen.

-[Unknown]
