### ISSUE TITLE
Feature Request: xBRZ on whole PSP screen (for 2D games)

### ISSUE THREAD

**Issue by RadarNyan** [hrydgard/ppsspp#6280]
**In short**: render 2D games with 1xPSP resolution then upscale the entire screen with xBRZ for better performance and better image quailty comparing to texture scaling

I've searched and found this has been discussed before in #1468, which is closed with the conclusion of using texture scaling. This has been working great for most 3D games with 3xBRZ with a acceptable performance drop when rendering new textures.

Recently I've been playing around trying to make some of my loved 2D games work with 3xBRZ texture scale without too much performance drop. During the process, I found 3xBRZ is quiet high-performance - it even scales a video at full speed (60/60 fps, scaling one 512x512 texture per two frames) while there is a huge performance drop in another game (17/30 fps, two 512x512 textures getting scaled per frame)

So I'm thinking what if we just render 2D games at 1x PSP resolution and pass every frame through xBRZ before bilinear (I'm talking about the bilinear scale while doing rendering resolution -> screen resolution)

480x272 comparing to 512x512 in pixels is about 50% less, plus we only need to do xBRZ once (at most) per frame, this sure will increase performance in most 2D games comparing to texture scaling (tell me I'm wrong) and this method would provide better image quality since some 2D games rendering large objects with multiple textures, scaling them separately will make some glitches at texture borders.

**Pros:**
1. Better performance since we only need to do upscale on a 480x272 image once (at most) per frame.
2. Better final image quailty since there's no more glitches on edges caused by upscale textures separately.

**Cons:**
1. More cpu usage since we lost the ability to cache scaled textures separately. Truth we can only cache the entire screen if it doesn't move at all (title screen, pause screen)
2. xBRZ performance may not be enough for some games running at 60 fps, especially on mobile device.

I've seen other emulators (like DeSmuME) supporting xBRZ on the entire screen and even 5xBRZ doesn't lead to a noticeable performance drop, how do they do it?

**Comment by unknownbrackets** [comment]
Screen upscaling filters have been implemented in PPSSPP for a while now (see #8019), which is done on the GPU.  They can also be chained to apply multiple effects.

I'm going to close this as implemented.  If you're looking for specific shaders/filters, feel free to contribute them or look on the forum where people post them.

-[Unknown]

**Comment by shinra358** [comment]
This had to do with that bit you implemented that only applied xbrz to
certain sprites but not all. There was a thread about it years ago where i
showed sfa3max still having jaggy areas with xbrz on.

**Comment by hrydgard** [comment]
Right, and the 5x xBRZ post processing effect we have does it.
