### ISSUE TITLE
Can we kill the "Disable stencil test" option?

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#6288]
Now that Star Ocean has been fixed with @unknownbrackets clever stencil tricks, does anyone still have any use for these hacks?

**Comment by kliniki-online** [comment]
There is also #6265

**Comment by unknownbrackets** [comment]
Note: depth write option is gone now.

-[Unknown]

**Comment by hrydgard** [comment]
Thanks. 5278 mentioned above is solve, so only #6265 remains?

**Comment by unknownbrackets** [comment]
I think so.  IIRC it's either a mixed fb format issue or a rgb bitmasking issue or something...

-[Unknown]

**Comment by gahu777** [comment]
i used it for silent hillon android. With disabled stencil test game runs with 60 fps, when i switch to newest ppsspp version i cant get silent hill player flashlight

**Comment by spinktvis** [comment]
+1 
Silent Hill flashlight bugged.

**Comment by adventureFAN** [comment]
+1
Please activate this option or fix the flashlight bug in Silent Hill Origins.

**Comment by Serentty** [comment]
+1, I am running into this issue on Android in Silent Hill Origins.
