### ISSUE TITLE
Global Settings (suggested profiles)

### ISSUE THREAD

**Issue by LasagnaPie** [hrydgard/ppsspp#6292]
PPSSPP seems rather bloated with numerous options, maybe have some sort of  Global Setting..  alike "High Performance . High Accuracy" .

Does the Windows platform need so many hacks?

**Comment by Gamemulatorer** [comment]
PPSSPP default settings is now good and balanced
also some hack settings is remove now on the latest version.

**Comment by hrydgard** [comment]
Yeah, closing.
