### ISSUE TITLE
Sakura Sakura Haru Urara black screen after intro video

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#6301]
infinity 40:49:912 user_main    I[IO]: HLE\sceIo.cpp:844 stdout: 
debug log (rename jpg to rar)
![ppsspplog](https://cloud.githubusercontent.com/assets/3481559/3256302/75d22c84-f216-11e3-9667-199c0cefc924.jpg)

**Comment by daniel229** [comment]
still not working even force sceKernelDeleteThread return 0 since https://github.com/unknownbrackets/ppsspp/commit/50402a3d49b336d27d2b6643679faedcbb3e9167

debuglog(rename jpg to 7z)
![ppsspplog](https://cloud.githubusercontent.com/assets/3481559/5716207/b1b31e00-9b23-11e4-8f9d-7cb4ccd2e1d7.jpg)

**Comment by unknownbrackets** [comment]
Well, that's probably due to sceKernelRegisterThreadEventHandler.  I had some inprogress stuff to try to implement some of that but it was getting messy fast...

-[Unknown]

**Comment by unknownbrackets** [comment]
You can try this:
https://github.com/unknownbrackets/ppsspp/tree/threadevent

Or the commit proceeding (Add functions to manage thread event handlers.)

I doubt it'll work, especially the last commit is wrong (was just an attempt to see how far off the events are.)

-[Unknown]

**Comment by daniel229** [comment]
Yes,it does not hang on bootup,but like before hang after video.
debug log with threadevent commit(rename jpg to 7z)
![ppsspplog](https://cloud.githubusercontent.com/assets/3481559/5717517/e8f3f97a-9b3c-11e4-9d2d-9d17fbe870a6.jpg)

**Comment by daniel229** [comment]
Crashed after video with https://github.com/hrydgard/ppsspp/issues/8782
![02](https://cloud.githubusercontent.com/assets/3481559/15631747/7eed2f88-25ab-11e6-85b9-33b1f045fe9f.png)

**Comment by unknownbrackets** [comment]
Oops, updated the pull with what I hope will be a fix for that.

-[Unknown]

**Comment by daniel229** [comment]
Still crash
![03](https://cloud.githubusercontent.com/assets/3481559/15631880/8c8ca4ba-25b1-11e6-8f55-dc4a0dd64f3d.png)

**Comment by unknownbrackets** [comment]
Oops, I thought I'd removed that before, must've forgotten.  Updated again, sorry.

-[Unknown]

**Comment by daniel229** [comment]
The crash fixed

**Comment by daniel229** [comment]
Fixed by https://github.com/hrydgard/ppsspp/pull/8790

**Comment by unknownbrackets** [comment]
Does this go in game now or is it still stuck at intros (with video fixed)?

http://forums.ppsspp.org/showthread.php?tid=17375

-[Unknown]

**Comment by daniel229** [comment]
It's the same problem,it goes in game now.
