### ISSUE TITLE
Memory Stick root vs Internal storage

### ISSUE THREAD

**Issue by ppsspp213** [hrydgard/ppsspp#6307]
Noticed in a few homebrew it uses the root of a storage mirror

sdcard
mnt/sdcard
storage/sdcard0
storage/emulated/0
mnt/shell/emulated/0
storage/emulated/legacy

instead of root of the PSP/GAME folder

for instance in isotool pressing left brings me to one of the above storage mirrors,

edecrypt, GameZDecryptZ also dump their enc & Decrypted folders to one of the above storage mirrors instead of the root PSP/GAME folder and are fail to load their .prx files.

**Comment by unknownbrackets** [comment]
I don't think this is really an issue anymore, given #6307.  There are still things to improve, such as #11731 or #10199, but those are separate issues.  I'm going to close this.

-[Unknown]
