### ISSUE TITLE
Rapidly changing CLUTs cause out-of-control texture creation - proposed solution

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#6323]
The now-infamous ending of the tutorial in FF : Type-0 appears to change the CLUT of all textures on every frame for a little while, causing us to create ridiculous amounts of textures (5000+), consuming hundreds of megs of VRAM.

I've been thinking about a way to "fix" it. For the below, keep in mind that texture cache keys are (address << 32 | clut_hash).

If the amount of textures created > some_threshold, flip to CLUT-checking mode.

In this mode, in TextureCache.cpp:SetTexture, before the big if (iter != cache.end()) check, insert an additional check that looks for textures with the same address but different CLUT (cache.lower_bound(cachekey & 0xFFFFFFF00000000ULL) , checking the key of the iter returned, should do the trick), and in that case, remove and insert the cache entry with the new cache key, ensuring that we re-decode the texture into the same texture object instead of creating a new one.

Then, after a couple of frames with none of those happening, switch back to regular mode.

@unknownbrackets , seems like this should work, right? We'll still have decoding overhead but little VRAM waste.

**Comment by unknownbrackets** [comment]
I can try to dig up that savestate later, but if anyone can easily repro, how does this perform nowadays?  I think various improvements should've made this better.

-[Unknown]

**Comment by unknownbrackets** [comment]
Haven't heard of this being an issue for a while.  I'm going to close.

-[Unknown]

**Comment by hrydgard** [comment]
Digging up an old issue, but this is drastically improved with #21814 , and the later commit that enabled it for this game.
