### ISSUE TITLE
Disable screensaver when playing

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#6340]
Gamepads don't avoid the screensaver like keyboard and mouse do, so we may want to programmatically disable the screensaver when running. For some reason I thought we already did this, but I got an email requesting the feature so I guess not :P  Anyway, a reminder to look into it.

**Comment by unknownbrackets** [comment]
What else do we need to do on other platforms?  I guess it's not so much an issue for mobile, so it's mainly SDL and Qt.

Qt does it, it seems: https://github.com/hrydgard/ppsspp/blob/4c0051dcfb4a034c164758e93cc0ec6b9bb6251e/ext/native/base/QtMain.cpp#L165

SDL seems to do it by default, unless you explicitly allow the screensaver: https://wiki.libsdl.org/FAQUsingSDL#Why_does_SDL_disable_my_screensaver_by_default.3F

Therefore, I'm closing this.

-[Unknown]
