### ISSUE TITLE
[NPJH50832] GOD EATER 2: some problem with textures

### ISSUE THREAD

**Issue by RadarNyan** [hrydgard/ppsspp#6343]
**Some textures not getting scaled**
I've made my own build forced all textures to sacle and removed TEXCACHE_MAX_TEXELS_SCALED limit, it works fine with my other games.

![npjh50832_00003](https://cloud.githubusercontent.com/assets/2091529/3289544/ef3e0d5e-f56d-11e3-82df-261519151ce0.jpg)

3x Rendering Resolution & 3xBRZ Texture Scale
the background texture is not being scaled, and text textures are clearly just bilinear scaled

**... and that "equal sign" comes from nowhere...**

Screenshot from PSP:
![201406162329_001](https://cloud.githubusercontent.com/assets/2091529/3289532/d4a3ae86-f56d-11e3-9ee1-93c29ddc977d.jpg)

GE Debugger:
![snapcrab_ge_2014-6-16_23-30-36_no-00](https://cloud.githubusercontent.com/assets/2091529/3289535/db5fccdc-f56d-11e3-9c0e-4907fadce622.jpg)

(Really, we need the ability to set background color in GE debugger to check light colored / transparent textures)

That "equal sign" just showing there, no matter what rendering resolution / texture scale level is set, both my own build and official build.

**Comment by unknownbrackets** [comment]
Is it possible to reproduce this issue in the demo?

http://www.pspdemocenter.com/page.php?id=4018

-[Unknown]

**Comment by daniel229** [comment]
That is the new game begining.After creating the new face,skipping the video,you see the equal sign in the subtitle in the cutscene.unfortunately demo did not provide the subtitle.

**Comment by unknownbrackets** [comment]
I wonder if it's sceFont related.  Does the game draw the text differently if you replace all the pgf files or remove them temporarily or anything?

-[Unknown]

**Comment by daniel229** [comment]
flash0\font not affect the subtitle.

**Comment by unknownbrackets** [comment]
Has anything improved here?  I can imagine this might've been anything from an sceCcc bug to actual rendering bug.

Could you try exporting a GE frame dump?  These help a lot, and can be used to confirm if the drawing commands themselves cause the equals sign on a PSP.  If so, it means the drawing commands are wrong - if not, it means we're rendering this equals incorrectly (maybe it was a bug in the game, but not visible because of rendering settings.)

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by RadarNyan** [comment]
Unfortunately I don't have the game or my PSP on hand at the moment, I'll try get back to you later this month :)

**Comment by unknownbrackets** [comment]
Okay, thanks.  To clarify - a GE dump can be made just with PPSSPP.  It's sorta like a screenshot, but a "live" one that includes all the drawing commands.  Then PPSSPP or a PSP can be run on that screenshot to debug the rendering.

-[Unknown]

**Comment by RadarNyan** [comment]
(Finally I got back to my psp iso library, I'll try go through my old issues one by one and see if they're fixed.)

This one seems to be fixed, I believe this is the same point in GE debugger:
![image](https://user-images.githubusercontent.com/2091529/76650291-9b6f6700-65a5-11ea-956e-57852e75f7f1.png)
If I hit [step draw] it goes to next character and no longer draws that "equal sign".

[NPJH50832_0001.zip](https://github.com/hrydgard/ppsspp/files/4331108/NPJH50832_0001.zip)
Don't think it's relavent anymore but here's the GE dump.

**Comment by unknownbrackets** [comment]
Thanks for validating.  I looked at the dump, but don't see anything special about that draw.  We must've fixed something that made the texture correctly blank, I suppose.

Going to mark this closed now.

-[Unknown]
