### ISSUE TITLE
FF Type 0 Invalid Address issue

### ISSUE THREAD

**Issue by MistyMountainHop** [hrydgard/ppsspp#6352]
Not to pile on with the slew of recent FF Type-0 issues, but I was wondering if anyone would have any ideas about this. I was grinding levels on the world map for about an hour, then cleared the Corsi Cave. After exiting the cave I was running my way back to the academy to save, when a battle triggered. But for some reason the screen went black during the transition and ppsspp was just hanging. So I exited and relaunched (luckily I had made a save state 30 sec before the issue occurred) and continued.

But now the same thing happens. Every time the game needs to transition screens or load a new area, ppsspp with go black screen and hang. The log console just gets bombarded with an infinite amount of "Memmapfunctions.cpp:92 readfromhardware invalid address" when this happens. I tried every combination of settings (MT and fast mem off, restoring default settings, tons of combos of things off and on, different ppsspp builds.) to no avail. 

If it was just a case of a save state getting corrupted then I wouldn't be too worried, but the hanging screen didn't start when I loaded the state, it started before that. Even though the normal save data lets me enter/exit screens it's a bit worrying not knowing what caused the issue to begin with because I have no idea if I'll end up grinding for an hour on the world map and getting stuck there unable to go back to save at the academy again....

On an unrelated note, the characters sometimes look graphically incorrect during world map battles no matter the rendering mode (they looked normal during the prologue mission though). They sometimes look like Metal Cap Mario from SM64 (I don't know how else to describe it lol) I think this could be related to LunaMoo's Type-0 graphic issue; when I've ran the GE Debugger I've gotten similar results as him/her.

**Comment by sum2012** [comment]
#5365 appear to fixed in v0.9.9.1-1505-gcf577e9
This one may also fix.
But need someone testing

**Comment by unknownbrackets** [comment]
We haven't heard about this issue in a while.  Without feedback, we can't tell if things are still broken or if they've been fixed.

We've made a lot of changes that might've fixed this since the last comment (over a year), and it might've been a settings issue in the first place.

I'm going to close this.  If it is still happening in the latest build, please feel free to reply with more info and we'll reopen it.

-[Unknown]
