### ISSUE TITLE
Valkyria Chronicles 3 in-game media storage problem

### ISSUE THREAD

**Issue by aristerus** [hrydgard/ppsspp#6354]
For starters, I really don't know if what I'm doing is ok but whatever.
The game constantly shows a message of "extra content could not be read please insert media storage" with only options of reloading(which fails to do anything) and a retire button(basically terminate the mission thus getting stuck)
![Uploading ULJM05781_00000.jpg . . .]()

was able to get past some of these by changing builds but this recent one has been an issue with 5 different builds ive tried already

Any ideas guys?

**Comment by unknownbrackets** [comment]
I think this may have been an X/O issue (Japanese games use O as confirm, not X.)  I'm going to close it since there's been no response.

If there's more information, please comment and we'll reopen.

-[Unknown]
