### ISSUE TITLE
Diabolik Original Sin missing sound output in FMV and cut-scenes

### ISSUE THREAD

**Issue by psennermann** [hrydgard/ppsspp#6359]
As written in the issue title, Diabolik Original Sin on ppsspp (9.8-1235) has missing sound output during full motion videos and cut-scenes:

FMV muted
![ules01248_00002](https://cloud.githubusercontent.com/assets/6342467/3305463/3a73a3a4-f656-11e3-9112-42c3b82a601c.jpg)

Cut-scenes muted
![ules01248_00003](https://cloud.githubusercontent.com/assets/6342467/3305469/509ed374-f656-11e3-9112-81dd6c88d99a.jpg)

**Comment by nfjorgebueno** [comment]
no sound in the fmv and cut-scenes in latest builds 1.0.1 is a disappointment, thanks

**Comment by daniel229** [comment]
Those videos are mono seen in ffplay.

**Comment by hrydgard** [comment]
#8472 should have helped?

**Comment by daniel229** [comment]
Yes,fixed.Let me close it.
