### ISSUE TITLE
Gensou suikoden 1&2 new issues

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#6363]
~~1.a lot of Invalid address during gameplay,it would log too many,and crashes,~~
1.Missing BGM after the BGM changing

~~2.another black background,one is fixed before~~  fixed by the function replacement
~~https://cloud.githubusercontent.com/assets/3481559/3311862/f17432f8-f6c9-11e3-8ec1-74e40319fc4e.png~~

~~psp~~
~~https://cloud.githubusercontent.com/assets/3481559/3311864/fa58415c-f6c9-11e3-8dcd-15065b67a94b.png~~

~~that texture only appearing in Gedebugger every 5 frames(drawing a whole screen is one frame)~~
~~https://cloud.githubusercontent.com/assets/3481559/3311885/484bf3c2-f6ca-11e3-887a-3a59c61823c8.png~~

3.button sound effect laggy.
debuglog (rename jpg to rar)
![ppsspplog](https://cloud.githubusercontent.com/assets/3481559/3311914/b0626284-f6ca-11e3-8a3d-1d4f0eabce86.jpg)

**Comment by unknownbrackets** [comment]
Does #7344 happen to improve or log any more for the unknown format thing?

-[Unknown]

**Comment by daniel229** [comment]
BGM is still stopping with https://github.com/hrydgard/ppsspp/pull/7344

01:19:387 user_main    E[ME]: HLE\sceAtrac.cpp:526 Atrac buffer invalid RIFF header: 09704d00
01:19:387 user_main    E[ME]: HLE\sceAtrac.cpp:1574 sceAtracSetDataAndGetID(09704d00, 00071800): bad data
01:19:387 user_main    I[IO]: HLE\sceIo.cpp:906 stdout:                 SdDrv Error: 0xdeadbeef = sceAtracSetDataAndGetID()
01:19:387 user_main    I[IO]: HLE\sceIo.cpp:906 stdout:                 SdDrv: Error on At3InitFromCache()
01:19:387 user_main    I[IO]: HLE\sceIo.cpp:906 stdout:                 SND: Failed on snd_BgmLoad( 0x5a )

**Comment by unknownbrackets** [comment]
Hmm, so that means the data is definitely invalid at that address.  If you enable debug sceIo logging, does it read anything from a file into that address or something?

-[Unknown]

**Comment by daniel229** [comment]
Is the 09704d00?here is the log using that address.
https://gist.github.com/daniel229/67319665849f07d59b91

**Comment by daniel229** [comment]
when sound stopping it log like this.
38:01:918 user_main    D[IO]: HLE\sceIo.cpp:884 sceIoReadAsync(5, 09704d00, 20000): deferring result
38:12:151 At3ThreadFun D[IO]: HLE\sceIo.cpp:884 sceIoReadAsync(5, 09704d00, 34884): deferring result
38:14:665 user_main    D[IO]: HLE\sceIo.cpp:884 sceIoReadAsync(5, 09704d00, 20000): deferring result

if it does not stop,it log like this
45:03:309 user_main    D[IO]: HLE\sceIo.cpp:884 sceIoReadAsync(5, 09704d00, 20000): deferring result
45:09:348 user_main    D[IO]: HLE\sceIo.cpp:884 sceIoReadAsync(5, 09704d00, 20000): deferring result

**Comment by unknownbrackets** [comment]
Hmm, well, then it might be some other atrac3 function not failing with an expected error code or something... definitely caused by it filling the buffer from two different threads.

-[Unknown]
