### ISSUE TITLE
TENCHU 3 infinite loading

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#6370]
debug log(rename jpg to rar)
![ppsspplog](https://cloud.githubusercontent.com/assets/3481559/3323534/83f3638e-f764-11e3-8aff-80b1e46063c9.jpg)

**Comment by Aniark** [comment]
There still has not any code of ppsspp can play thenchu 3 and tenchu kurenai without infinite loading ,though the method of fix the bug was found

why the developers do not fix it?

**Comment by daniel229** [comment]
@Aniark 
If you are meaning my change above,that would break other games.If you are meaning the JPCSP,that is a big change,and PPSSPP is more different than JPCSP,that is not easy to port to PPSSPP.

**Comment by unknownbrackets** [comment]
Does #8105 help this at all?

-[Unknown]

**Comment by daniel229** [comment]
Unfortunately not.

**Comment by sum2012** [comment]
@daniel229  can help provide new save status ? Thanks

**Comment by daniel229** [comment]
In the title,go to options,after the first looping of the music then go to save/load->save

**Comment by sum2012** [comment]
Thanks @daniel229 ,it is very easy to reproduce

**Comment by sum2012** [comment]
This is @unknownbrackets  modify log:
https://gist.github.com/sum2012/43a9488f1c7e3c9a5131

**Comment by daniel229** [comment]
Fixed in https://github.com/hrydgard/ppsspp/issues/8189
