### ISSUE TITLE
Castlevania Dracula X Stage 6 missing audio/text in boss fight

### ISSUE THREAD

**Issue by gordonfreeman01** [hrydgard/ppsspp#6397]
The Shaft fight is missing audio and freezes at the first text box with no further scrolling text in the starting cutscene, pressing start allows skipping the scene as a workaround but if the level is restarted and all side roads are skipped (walk straight to the door), the scene plays normally. However, the Shaft cutscene in the final phase of this boss is missing audio and subtitles, could not find a workaround (maybe state saves have something to do with it).

**Comment by unknownbrackets** [comment]
Has 1.0.1 improved any of these issues with default settings?

If not, can you try to find if it's ever trying to draw it in the GE debugger?
https://github.com/hrydgard/ppsspp/wiki/How-to-find-a-graphic-issue-with-the-GE-debugger

Also, does it show up if you use the software renderer (last option in graphics settings)?  Do note that it will be unacceptably slow, most likely, but if it works there it may help us understand what is going wrong with OpenGL.

-[Unknown]

**Comment by daniel229** [comment]
seems same as https://github.com/hrydgard/ppsspp/issues/6587 ,I complete Stage 6 without any problem.

**Comment by unknownbrackets** [comment]
Awesome, thanks.

-[Unknown]
