### ISSUE TITLE
Pangya Fantasy Golf: Often crashes when changing equipment in "My Room".

### ISSUE THREAD

**Issue by thedax** [hrydgard/ppsspp#6398]
This crash goes as far back as 0.9.6.2 at least, so I think it's safe to assume it's always existed since the game has run in the emulator.

Steps to reproduce:
1. Load your save.
2. Go to Pangya Collection -> My Room.
3. Change any equipment, and one of two things will happen:
* The game will either outright crash with a useless stack trace (more on this in a moment)
* The game will continue as normal, with no crash, refreshing the character model preview with the desired item.

Now, about the stack trace: It doesn't matter if JIT is on or off, nor if fast memory is on or off, the emulator will crash with no usable stack trace. See below.

```C++
>	0000000004df090c()	Unknown
```

Here's the kicker: If I use softGPU, it does *not* crash at all. It only crashes with OpenGL.

**Comment by unknownbrackets** [comment]
What happens if you change this:

```c++
	if (g_Config.bSoftwareSkinning && (vertType & GE_VTYPE_WEIGHT_MASK)) {
		DecodeVertsStep();
		decodeCounter_++;
	}
```

To:
```c++
	if (g_Config.bSoftwareSkinning && (vertType & GE_VTYPE_WEIGHT_MASK)) {
		DecodeVertsStep();
		decodeCounter_++;
		Flush();
	}
```

Does it still crash, or not anymore?

-[Unknown]

**Comment by thedax** [comment]
@unknownbrackets: Adding a flush there seems to prevent the crash, at the "cost" of the game freezing for a few seconds while it frees (or tries to, anyhow) a bunch of memory.

**Comment by unknownbrackets** [comment]
Hmm, if you pause it while it's frozen, are any threads showing a useful stack trace?  What is it trying to free?

-[Unknown]

**Comment by unknownbrackets** [comment]
Does this still happen?  If yes (I'm assuming yes), what if you increase the buffer sizes in GPU/Common/DrawEngineCommon.cpp?  I just want to make sure it is overflowing the buffers.

These:
```c++
enum {
	VERTEX_BUFFER_MAX = 65536,
	DECODED_VERTEX_BUFFER_SIZE = VERTEX_BUFFER_MAX * 48,
	DECODED_INDEX_BUFFER_SIZE = VERTEX_BUFFER_MAX * 20,
	SPLINE_BUFFER_SIZE = VERTEX_BUFFER_MAX * 20,
};
```

Change to e.g.:
```c++
enum {
	VERTEX_BUFFER_MAX = 65536,
	DECODED_VERTEX_BUFFER_SIZE = VERTEX_BUFFER_MAX * 64,
	DECODED_INDEX_BUFFER_SIZE = VERTEX_BUFFER_MAX * 32,
	SPLINE_BUFFER_SIZE = VERTEX_BUFFER_MAX * 32,
};
```

-[Unknown]

**Comment by thedax** [comment]
Last time I checked (like 2 months ago, maybe?) it did. I'll try your change in a little while.

**Comment by sum2012** [comment]
Still crash in v1.0.1-52-g3773d25

**Comment by sum2012** [comment]
@unknownbrackets 
it is not in DrawEngineCommon.cpp
it is in DrawEngineCommon.h
Anyway it still crash.

**Comment by hrydgard** [comment]
The game appears to make a draw with bogus index buffer data, causing the vertex decoder to run on way too many vertices.

As the game has some rather severe memory management issues:

    09:56:380 user_main    W[KERNEL]: HLE\sceKernelMemory.cpp:1727 800201b6=sceKernelFreeVpl(288, 097e78b8): Unable to free
    09:56:380 user_main    W[KERNEL]: HLE\sceKernelMemory.cpp:1727 800201b6=sceKernelFreeVpl(278, 097e9c88): Unable to free
    09:56:380 user_main    W[KERNEL]: HLE\sceKernelMemory.cpp:1727 800201b6=sceKernelFreeVpl(288, 097e9c88): Unable to free
    09:56:380 user_main    W[KERNEL]: HLE\sceKernelMemory.cpp:1727 800201b6=sceKernelFreeVpl(278, 09914858): Unable to free
    09:56:380 user_main    W[KERNEL]: HLE\sceKernelMemory.cpp:1727 800201b6=sceKernelFreeVpl(288, 09914858): Unable to free
    09:56:380 user_main    W[KERNEL]: HLE\sceKernelMemory.cpp:1727 800201b6=sceKernelFreeVpl(278, 097e5448): Unable to free

this is probably not too surprising.

We might be able to get around the crash with some sanity checks in the drawing code.

**Comment by sum2012** [comment]
Use @unknownbrackets this change https://github.com/hrydgard/ppsspp/issues/6398#issuecomment-70602941
freeze 1-2 second,I try to pause
![1](https://cloud.githubusercontent.com/assets/2177532/6431138/c6291c24-c060-11e4-9fd9-d03bb583d7fe.png)


 	[External Code]	
	PPSSPPDebug64.exe!condition_variable::wait(recursive_mutex & mtx) Line 291	C++
 	PPSSPPDebug64.exe!PrioritizedWorkQueue::Pop() Line 45	C++
 	PPSSPPDebug64.exe!threadfunc(PrioritizedWorkQueue * wq) Line 76	C++
 	[External Code]	
 	PPSSPPDebug64.exe!std::thread::Func<std::_Bind<1,void,void (__cdecl*const)(PrioritizedWorkQueue * __ptr64),PrioritizedWorkQueue * __ptr64 & __ptr64> >::Run() Line 245	C++
 	PPSSPPDebug64.exe!std::thread::RunAndDelete<std::thread::Func<std::_Bind<1,void,void (__cdecl*const)(PrioritizedWorkQueue * __ptr64),PrioritizedWorkQueue * __ptr64 & __ptr64> > >(void * param) Line 286	C++
 	[External Code]

**Comment by hrydgard** [comment]
That should take care of it, can you test if it works for you @sum2012 ?

**Comment by sum2012** [comment]
OK,wait 30 minute

**Comment by sum2012** [comment]
I test v1.0.1-56-gbfa52e6 fixed
