### ISSUE TITLE
Kiniro no Corda 3 Full Voice Special videoes are skipped.

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#6401]
Test builds between 0.91 and 0.98-1351,none of these works.
info log
https://gist.github.com/daniel229/72205fe87a38f73f39b6

full debug log(rename jpg to rar)
![ppsspplog](https://cloud.githubusercontent.com/assets/3481559/3353545/9a7ea410-fa84-11e3-8c04-a93988770838.jpg)

**Comment by unknownbrackets** [comment]
Has this improved?

Also, does it delay or play any audio during the videos?  I see it full the entire buffer, or seem to, and it's doing Csc to decode the video at least.

-[Unknown]

**Comment by daniel229** [comment]
No video or audio playback.

**Comment by daniel229** [comment]
It does not play the video, all the Harukanaru Toki and Kiniro no Corda have the bug.
```
56:47:835 ScePsmfPlaye D[ME]: HLE\sceMpeg.cpp:1411 packetAdded: 4 packetsRead: 548 packetsTotal: 581
56:47:859 ScePsmfPlaye E[ME]: HLE\sceMpeg.cpp:1298 UNIMPL sceMpegAvcDecodeFlush(09eed6e8)
56:47:859 ScePsmfPlaye D[ME]: HLE\sceMpeg.cpp:1313 sceMpegInitAu(09eed6e8, 1, 09eecf9c)
56:47:892 MainThread   D[ME]: HLE\sceMpeg.cpp:709 sceMpegFreeAvcEsBuf(09eed6e8, 1)
56:47:892 MainThread   D[ME]: HLE\sceMpeg.cpp:540 sceMpegDelete(09eed6e8)
56:47:892 MainThread   D[ME]: HLE\sceMpeg.cpp:1843 sceMpegRingbufferDestruct(09efd700)
56:47:892 MainThread   I[ME]: HLE\sceMpeg.cpp:1541 sceMpegFinish(...)
```

**Comment by daniel229** [comment]
There are two videos in the log.The first one is good,and it's sceMpegAvcCsc.The second one is skipped and not sceMpegAvcCsc.

jpcsptrace
https://gist.github.com/daniel229/fe44c73e91ab2dc7ec82
the second video is start from 19:30:10.226333 MainThread - -> sceMpegInit = 0x0

**Comment by unknownbrackets** [comment]
I think `scePsmfSpecifyStreamWithStreamTypeNumber(09eeabf8, 0000000f, 00000000)` was the thing that wasn't working, FWIW.

-[Unknown]
