### ISSUE TITLE
Update ppsspp-ffmpeg to the stable 2.3.x branch

### ISSUE THREAD

**Issue by akien-mga** [hrydgard/ppsspp#6413]
Following discussions on issue #5772, I think it could be nice for ppsspp-ffmpeg to be updated to the stable 2.2.x branch.

For the record the current version of ppsspp-ffmpeg is a git snapshot of the pre-release 2.2 branch (made between the 2.1.2 and 2.1.3 releases in the beginning of January 2014).

The stable 2.2 version (which is the first release with native Atrac3+ support) was released on March 23rd. The latest stable release in the branch was 2.2.4 a couple of days ago.

I think using a stable version of ffmpeg would be better for ppsspp as a whole, especially if you want to update your snapshot from time to time: chances are that the current ppsspp code to handle Atrac3+ is not 100% compatible with what upstream ffmpeg deemed good for release in the 2.2 branch. So you would currently have a work-in-progress Atrac3+ support through ffmpeg.

**Comment by hrydgard** [comment]
Our FFMPEG has now been updated to master, plus a patch that enables GHA phase shifting.
