### ISSUE TITLE
Tony Hawk P8 Video Issues

### ISSUE THREAD

**Issue by djdor11** [hrydgard/ppsspp#6416]
Intro movies don't play, and when you get the "cellphone video messages" there's a black screen and only the subtitles show up, kind of:
![capture](https://cloud.githubusercontent.com/assets/6123743/3370985/33787708-fb99-11e3-811a-b2fa4ee63ca7.JPG)
Other than that, all seems pretty good.
Hope you fix it soon, thanks.

**Comment by unknownbrackets** [comment]
Well, we still don't know why it's not working for you.  It may work now in Direct3D 9, and there've been a lot of improvements in the last year.  Could you try again?

-[Unknown]

**Comment by djdor11** [comment]
Okay tried again with a US and a EU copies of the game, both latest gits and 1.1.1, both D3D and OGL with different settings and... no luck. Still no intro movies and the cellphone movies show up the same.

**Comment by daniel229** [comment]
Still no intro video,when you loading the iso,the first screen is same as that youtube video at 1:04 ,https://youtu.be/BqZChCZEHgs?t=1m4s
then PPSSPP skips everything go to 5:22 https://youtu.be/BqZChCZEHgs?t=5m22s

debug log
[ppsspplog.txt](https://github.com/hrydgard/ppsspp/files/75530/ppsspplog.txt)

**Comment by unknownbrackets** [comment]
Hmm.  In that log, it doesn't even try to call any mpeg or psmf function...

-[Unknown]

**Comment by daniel229** [comment]
But it works fine on PSP.
PPSSPP skips all five of intro videoes and the loading bar screen.

![8](https://cloud.githubusercontent.com/assets/3481559/12069704/dd6c0c64-b080-11e5-80b8-10156635427a.png)

**Comment by daniel229** [comment]
It works fine after change cpu clock <=40
![9](https://cloud.githubusercontent.com/assets/3481559/12069767/670b735c-b085-11e5-8d8c-668324c3d68f.png)

debugger log
https://gist.github.com/daniel229/86a559e49d78bf6c1a9c

**Comment by daniel229** [comment]
Set I/O timing method to Host also works,and better,at least it run at 30fps in game. set cpu clock to 40 make it run slow as 15fps in game

**Comment by daniel229** [comment]
@djdor11 
Where is the "cellphone video messages",how do I get there?

**Comment by daniel229** [comment]
some videoes are not working,but works fine in software rendering.
![16](https://cloud.githubusercontent.com/assets/3481559/12069936/5d026334-b08f-11e5-80f4-663803a1c751.png)
![17](https://cloud.githubusercontent.com/assets/3481559/12069937/5d0e5810-b08f-11e5-82c1-e581494738d5.png)

**Comment by daniel229** [comment]
Go to pause menu and come back,seems like it catches two of the video frames.

**Comment by unknownbrackets** [comment]
Sounds to me like we're missing a block transfer hook.  Can you try setting breakpoints on the FBOs it creates when you go to the pause menu and come back?  Do it right after going to the pause menu, and it should catch whatever writes the video.

-[Unknown]

**Comment by daniel229** [comment]
Is it this
![1](https://cloud.githubusercontent.com/assets/3481559/12072789/5782d69c-b12e-11e5-9c58-4729b1094f64.png)

```
54:57:031 user_main    I[SCEGE]: Common\FramebufferCommon.cpp:420 Creating FBO for 00000000 : 480 x 272 x 3
54:57:064 user_main    I[SCEGE]: Common\FramebufferCommon.cpp:420 Creating FBO for 00088000 : 480 x 272 x 3
54:57:065 user_main    W[SCEGE]: Common\FramebufferCommon.cpp:457 FBO reusing depthbuffer, 00088000/00110000 and 00000000/00110000
```

**Comment by unknownbrackets** [comment]
Yes, looks like it.  Here's a more readable version of that function AFAICT:

```c++
void WeirdVideoCopy(u8 *dst, const u8 *src) {
	// So much magic.
	static const u32 x1 = 76;
	static const u32 y1 = 37;
	static const u32 x2 = 404;
	static const u32 y2 = 256;
	static const u32 stride = 512;
	static const u32 bpp = 4;
	static const u32 baseOffset = 0x00012800;

	u32 offset = baseOffset;
	for (u32 y = y1; y < y2; ++y) {
		u32 xoff = offset + x1 * bpp;
		u8 *srcp = &src[xoff];
		u8 *dstp = &dst[xoff];

		for (u32 x = x1; x < x2; ++x) {
			for (u32 i = 0; i < bpp; ++i) {
				*dstp++ = *srcp++;
			}
		}

		offset += stride * bpp;
	}
}
```

-[Unknown]

**Comment by daniel229** [comment]
That sounds stuttering

**Comment by daniel229** [comment]
It seems works with this,it's a uploadframe it seems never do this before.
```
static int Hook_tonyhawkp8_upload_frame() {
	const u32 fb_address = currentMIPS->r[MIPS_REG_A0];
	if (Memory::IsVRAMAddress(fb_address)) {
		gpu->PerformMemoryUpload(fb_address, 0x00088000);
		CBreakPoints::ExecMemCheck(fb_address, true, 0x00088000, currentMIPS->pc);
	}
	return 0;
}
```
![01](https://cloud.githubusercontent.com/assets/3481559/12073244/f522b392-b14f-11e5-9216-e886ec5f93e7.png)

**Comment by unknownbrackets** [comment]
Okay, sounds reasonable.  It must be drawing the background in CPU as well, I guess.

Probably better to name it `Hook_tonyhawkp8_upload_tutorial_frame` if it's this function, since there might be another upload...

-[Unknown]

**Comment by daniel229** [comment]
Okay.There are 39 tutorial videoes there.

**Comment by daniel229** [comment]
The first frame is green,and also happen in software rendering,have not try PSP yet.

**Comment by daniel229** [comment]
Endless loop at the function start？
![03](https://cloud.githubusercontent.com/assets/3481559/12073564/9ff66cd8-b15e-11e5-91b0-7ab067d63dd4.png)

**Comment by unknownbrackets** [comment]
Weird, is it actually going there?  I've seen those sometimes in places where code is never meant to end up.

-[Unknown]

**Comment by daniel229** [comment]
I don't see it go there.

**Comment by unknownbrackets** [comment]
Are there any other issues here?  Or can we close this?

-[Unknown]

**Comment by daniel229** [comment]
intro video is still skipped.need to set a lower cpu clock to avoid it happen.

**Comment by daniel229** [comment]
Another strange issue,after you loading the game,you have to close PPSSPP to apply the cpu clock changing,just exit to the menu,changing cpu clock does not work.

**Comment by benderscruffy** [comment]
this can be closed no problems with it
anyone else having problems ??

**Comment by hrydgard** [comment]
Just gonna close it.
