### ISSUE TITLE
Dragon Ball Z Shin Budokai: Weird Character Body issue

### ISSUE THREAD

**Issue by GamerzHell9137** [hrydgard/ppsspp#6426]
For some reason when you pause the game and continue to play it, the bodies of characters "change"

Here's how it looks like

https://www.youtube.com/watch?v=3Fvnljwum7E

**Comment by unknownbrackets** [comment]
Does this happen even with vertex cache off?

-[Unknown]

**Comment by GamerzHell9137** [comment]
Just tested game, the issue has been fixed.
