### ISSUE TITLE
PPSSPP Interface reports incorrect buttons

### ISSUE THREAD

**Issue by ProfessorKaos64** [hrydgard/ppsspp#6473]
I go to configure start/select, but they are report as other things like pad.right
I don't think it's sixad, since I can use xbmc just fine, and the button mappings in xbmc are correct and have never moved an inch. Is there a log or anything I can give you? I have no helpers (i.e. qjoypad) running, so there is nothing else interfering. The rest of all my emulator controls still work just fine, so that is another reason I don't believe sixad to be at fault, or else my emulator games would have started to not work correctly.

This is only for the interface, as the game then functions fine, despite the wrong names. It does not however let me use the menu interface right unless I hard code the magic button number in the controls.ini file.

**Comment by unknownbrackets** [comment]
Centralizing this in #7847.  There's no reason to have multiple open, and that one has just a bit more recent discussion.  We'll move nowhere if we keep rehashing things we already discussed.

-[Unknown]
