### ISSUE TITLE
Summon Night 5 Only hand is wire frame. 

### ISSUE THREAD

**Issue by ghost** [hrydgard/ppsspp#6483]
Even if SoftwareSkining is OFF, a problem occurs. 
This problem is not related to Simulateblocktransfer. 
It occurs in all the rendering modes. 
They are all the versions from 9.5. 

log&save
https://drive.google.com/folderview?id=0By8WbS_hvsesalozUzJmN21wb00&usp=sharing
![9 8-1519_1](https://cloud.githubusercontent.com/assets/4569870/3456744/c2fd4db4-01f1-11e4-836c-c1f83e25db26.JPG)
![9 8-1519_2](https://cloud.githubusercontent.com/assets/4569870/3456745/c2fe1834-01f1-11e4-9671-e5732651725d.JPG)
![9 5](https://cloud.githubusercontent.com/assets/4569870/3456756/d264a2a2-01f1-11e4-916f-673756ace264.JPG)
![9 6 2](https://cloud.githubusercontent.com/assets/4569870/3456757/d2659b1c-01f1-11e4-9c9e-21f642ec14d9.JPG)
![9 7 2](https://cloud.githubusercontent.com/assets/4569870/3456758/d26a21aa-01f1-11e4-999e-55d4b1be355f.JPG)
![stepinto1](https://cloud.githubusercontent.com/assets/4569870/3456763/dd8d985a-01f1-11e4-976b-630f31f64008.JPG)
![stepinto2](https://cloud.githubusercontent.com/assets/4569870/3456764/dd8e14ec-01f1-11e4-9d1a-0179eea968ed.JPG)
![stepinto2 5](https://cloud.githubusercontent.com/assets/4569870/3456770/ea268446-01f1-11e4-81e1-a49d01b5eecc.JPG)
![stepinto3](https://cloud.githubusercontent.com/assets/4569870/3456773/ef0a3d2c-01f1-11e4-9a9b-b980b2093dbf.JPG)
![stepinto4](https://cloud.githubusercontent.com/assets/4569870/3456772/eeeec790-01f1-11e4-96f0-d1b81f1703ad.JPG)
#4838

**Comment by unknownbrackets** [comment]
I think this is another case of the antialiased lines thing.  I wonder what the game is even trying to do, still, because the texture seems correct without even any lines/antialasing there?

Would be useful to see the other tabs in the GE debugger when the lines are highlighted in red.

-[Unknown]

**Comment by daniel229** [comment]
GE debugger tabs
![01](https://cloud.githubusercontent.com/assets/3481559/11973149/26042278-a991-11e5-8cf9-6b443bfc0c3a.png)

others
https://gist.github.com/daniel229/4115049023432c0e33cb

**Comment by unknownbrackets** [comment]
Oh, okay.  It's doing a somewhat sane thing here actually, I guess.  It's texturing from the target to antalias those lines.  I guess it's just to blur along those lines.

I wonder actually why it doesn't work. Does it work at 1x?  Maybe switching lines to triangles will help this.

-[Unknown]

**Comment by daniel229** [comment]
No,it does not work at 1x either.

**Comment by daniel229** [comment]
Wire frame only on the edge since https://github.com/hrydgard/ppsspp/pull/8376,also the same result with the old depth range hack.
![1](https://cloud.githubusercontent.com/assets/3481559/12219326/e58a676a-b779-11e5-80a5-59fdc9b24e8b.png)

**Comment by unknownbrackets** [comment]
Great.  This makes a lot more sense.  So now we just need to see what antialias is supposed to do, maybe it automatically applies alpha even when blending is off?

-[Unknown]

**Comment by gueber** [comment]
Seems it was somewhat fixed in 1.1.1-647 but somewhere before 1.2.1 it regressed and never got better. Even in 1.3 the hands are wireframe again.

![npuh10198_00000](https://cloud.githubusercontent.com/assets/4224918/18974004/6f1a3fe6-8655-11e6-9220-88c06f58b314.jpg)

That's how it looks as of 1.3, also the wireframe around the halo was still there even in 1.1.1-647 were the hands were ok so that may be its own issue.

**Comment by hrydgard** [comment]
We should probably just kill all lines where the PSP's strange AA method is enabled, and properly implement multisampling instead...

**Comment by unknownbrackets** [comment]
Hmm, I think some game like Echochrome only drew with AA on or something, though?  But yeah

-[Unknown]

**Comment by unknownbrackets** [comment]
Notes on how antialias works on the PSP, from what I can tell:

1. For lines, antialias REPLACES the fragment alpha value with an "antialias" alpha factor.
2. In practice, all pixels seem to have an alpha of 0x80 or lower.
3. Additional pixels are not drawn; the existing line pixels just have adjusted alpha.
4. Alpha testing and blending act upon the replaced fragment alpha.  If neither is enabled, antialias will have no visual effect.
5. Vertex and texture alpha (including from lighting) is simply discarded, not blended.
6. Triangles and rectangles seem (?) to simply get a flat 0x7F alpha when antialias is enabled.  Importantly, this still replaces.

-[Unknown]

**Comment by unknownbrackets** [comment]
I updated the above comment with notes about how UVs are also replaced.

Practical use of antalias could involve:

 * Bind the target as a texture.
 * Draw lines over the areas you wish to adjust.
 * Enable blending and texturing.
 * Use vertex colors, lighting, or texture func to control the drawn colors.

Or, if you just want to draw lines, and you don't want them heavy, disable texturing and draw away.

This explains the hand.  Note the following:
 * Flags: texturing, alpha blend, alpha test, antialias.
 * Lighting enabled (but no lights, and REPLACE texfunc anyway...)
 * Framebuffer and texture are equal (and 5551.)
 * Tex func is REPLACE RGB.  This means the antialias alpha is used directly.
 * Vertex contains only positions.
 * Alpha test is just >= 0 (so not really enabled.)
 * Alpha blending is src.a, 1.0 - src.a.

From the above, it seems like this is a no-op.  The blend src color will ultimately have the same R, G, B so blending will have no effect.  I can only assume either the game sometimes varies the tex func, or this is a forgotten debugging feature (to show wireframes) that was only partially disabled.

Based on the above, I'd suspect we could harden our logic of when to skip and when not to.

-[Unknown]

**Comment by hrydgard** [comment]
Nice investigation. Yup, there's really not much point in trying to implement these properly. We'd better put more effort into supporting modern types of antialiasing like multisampling, and indeed try to filter these out.

**Comment by unknownbrackets** [comment]
Well, yes, except when texturing is disabled.  Using it to try to smooth edges is probably the main use (including Persona 3), but it can also be used to draw regular lines or outlines, which we shouldn't skip IMHO.

Basically, this is a terrible check:
```c++
		// Discard AA lines in DOA
		if (prim == GE_PRIM_LINE_STRIP)
			return;
		// Discard AA lines in Summon Night 5
		if ((prim == GE_PRIM_LINES) && gstate.isSkinningEnabled())
			return;
```

And it'd probably be much better to check whether texturing is enabled or not.

-[Unknown]

**Comment by unknownbrackets** [comment]
Could you try exporting a GE frame dump?  These help a lot.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by unknownbrackets** [comment]
In Echochrome:

 * Texturing IS enabled, and points to a 100% white texture.
 * Tex func: modulate RGB
 * alpha test: a > 0
 * depth test src <= dst
 * blend src.a / inverse src.a
 * All vertex colors are black (which is why the texture color doesn't matter.)

So based on Summon Night, Echochrome, and Persona - it seems like a heuristic could be if the tex func is set to REPLACE.  I'm not sure what DOA uses.

FWIW lighting is enabled both here and on Persona, so maybe it does do something...

-[Unknown]

**Comment by Panderner** [comment]
The hands are fixed in 12695:
![Screenshot_2020-03-26-18-55-05-85_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/77639209-5a0e8c80-6f93-11ea-81b3-f2ad64d558b1.png)
[recording.zip](https://github.com/hrydgard/ppsspp/files/4386674/recording.zip)
