### ISSUE TITLE
Request:Change the way RButton works

### ISSUE THREAD

**Issue by vsub** [hrydgard/ppsspp#6486]
Can it be change to execute the function set to that key on key up and only inside the game window

Currently if rbutton is set as pause and if you press anywhere(even if it's not on the ppsspp window),ppsspp will pause the game

**Comment by unknownbrackets** [comment]
So basically you want #7536, right?

-[Unknown]

**Comment by hrydgard** [comment]
Hm, I would guess vsub means the mouse rbutton, but not sure..

**Comment by unknownbrackets** [comment]
Oh, well, I don't think either left or right button should trigger ppsspp when the game is not focused...

-[Unknown]

**Comment by vsub** [comment]
yes,that's what I meant by rbutton(right click)and thanks for the fix
