### ISSUE TITLE
Ghost In A Shell - problems

### ISSUE THREAD

**Issue by brujo5** [hrydgard/ppsspp#6488]
those games are recently fixed 

splinter cell esensial working perfect.

ghost in a shell have problems

1.-the game crash at boot whit fastmem enabled
2.-the game crash at loading mission whit bufered rendering
3.-the game cause emulator freeze at loading mission in non bufered rendering
4.- Jit on/off no diference
5.-simulate block transfer on/off no differense

iphone 5S ios 7.1.1

**Comment by Solstar** [comment]
ghost in the shell still crashes in latest (07\01\2015)android version after main menu.same goes for ape academy 2.which runs flawlessly on the normal google play store version of ppsspp

**Comment by sum2012** [comment]
I test on USA version of android version on LG nexus 5 
v0.9.9 also crash after main menu
anyway,it is v0.9.9.1-1439-g01ff870 log
https://gist.github.com/sum2012/0f23847c6ff03b255aec

**Comment by hrydgard** [comment]
(in sum2012's log:) Fatal signal 5 ?? That's SIGTRAP. Not a standard signal 11 crash, weird....

**Comment by sum2012** [comment]
Windows log:(no problem)
https://gist.github.com/sum2012/ea36c3b509d1eb561b20

**Comment by sum2012** [comment]
I disable JIT,I can go inside the menu now (in android ).

**Comment by Solstar** [comment]
how can i disable jit?is that in "system" options?i use an nvidia shield btw and yes in windows version the game runs great

**Comment by Bigpet** [comment]
@Solstar it's in the developer options

**Comment by sum2012** [comment]
I try change source code  \MIPS\ARM\ArmComp*.cpp to CONDITIONAL_DISABLE .
But don't work.......

**Comment by sum2012** [comment]
Test with correct rip of eur version.
No problem with windows 64 bit and Android on v1.1.1-457-gda65116
log: https://gist.github.com/sum2012/95d765d1de01aa80b3ee

**Comment by unknownbrackets** [comment]
As I recall we did reverted BKPTs.  It currently has "break Yu-Gi-Oh 6 crash with edit card in Android version".

I'm still not sure what it means if it's hitting that code.

-[Unknown]

**Comment by sum2012** [comment]
@unknownbrackets you should talk that in #8104 as it is  the same game.
Any way ,we must fix #8104 

For this issue,need ios build recover first

**Comment by unknownbrackets** [comment]
Well, what I mean is that what likely broke this game was that change.  It's been reverted, but it *should* have been a correct change, so I wonder still why it wasn't working.

So if it's now working on Android, that's great, but we may break it again if we don't understand the problem.  I think it affects both this game and that one.

-[Unknown]

**Comment by sum2012** [comment]
@unknownbrackets 
I try revert BKPTs change #7327 ,this game still work on Android

**Comment by unknownbrackets** [comment]
So this works fine on Android and Windows now, we're just not sure about iOS?  It sounds likely it would've fixed it there, too.

-[UInknown]
