### ISSUE TITLE
Dai-2-Ji Super Robot Taisen Z Hakai-hen (Android)

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#6492]
Orignal reporter qq:俺が!ガンダムだ
Test in version v0.9.8-1537-gedd760f
![2](https://cloud.githubusercontent.com/assets/2177532/3471438/c1b22020-02c2-11e4-9bc3-ed64d1145b2c.jpg)
![3](https://cloud.githubusercontent.com/assets/2177532/3471442/c4d9f0b6-02c2-11e4-886a-80959857c9fd.jpg)
![4](https://cloud.githubusercontent.com/assets/2177532/3471445/c8229b24-02c2-11e4-9cfe-0d5e989baf29.jpg)

**Comment by unknownbrackets** [comment]
Any idea if this is with "disable slow effects" UNCHECKED and buffered rendering?  It should work with those settings, even on a Mali-400.  But if "disable slow effects" is checked or if "non-buffered rendering" is being used, it most likely will not work.

-[Unknown]

**Comment by sum2012** [comment]
I have told him to re-test again

**Comment by sum2012** [comment]
He "disable slow effects" is checked ,I have told him dsiable it,then re-test again

**Comment by unknownbrackets** [comment]
Yeah, the above screenshots are pretty much exactly what I'd expect with that checked.  This is a slow effect.

-[Unknown]

**Comment by sum2012** [comment]
He test ok now.but another phone (or tablet ?)  still have this problem.
I will post that in another thread.Hope don't confuse.
