### ISSUE TITLE
Jui Dr. Touma Jotarou hangs in the intro video.

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#6496]
FPS indicator stop and stuck in a black screen.
![02](https://cloud.githubusercontent.com/assets/3481559/3478391/1b18c294-0337-11e4-8a5b-e41778204796.png)

commit out this ,the video still black,but we can skip it and go ingame.
sceMpeg.cpp(1471):		
<code>return hleDelayResult(ERROR_MPEG_NO_DATA, "mpeg get avc", mpegDecodeErrorDelayMs);</code>
![01](https://cloud.githubusercontent.com/assets/3481559/3478376/c9615ccc-0336-11e4-9810-617e898314d9.png)

debug log(rename jpg to rar) 
![ppsspplog](https://cloud.githubusercontent.com/assets/3481559/3478397/324560f8-0337-11e4-82be-9b0da064466b.jpg)

**Comment by unknownbrackets** [comment]
How the investigate mode background problem?

-[Unknown]

**Comment by daniel229** [comment]
I would a replace function for the background.

**Comment by daniel229** [comment]
It's this function,is It a memcpy?
![01](https://cloud.githubusercontent.com/assets/3481559/5604707/2c950f1a-9409-11e4-83c3-ce7a65016397.png)

**Comment by unknownbrackets** [comment]
Hmm.  Without looking at it super hard, I think it's a memmove().  At least it seems to be paying attention to overlap somewhat.

-[Unknown]

**Comment by daniel229** [comment]
memmove() is still not working at the first time,but memcpy() works.

**Comment by daniel229** [comment]
Just do smoething wrong,memmove() is accurately working
