### ISSUE TITLE
Dream Club portable graphic issue

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#6497]
v0.9.8-1000-ga675c30 no problem
![1](https://cloud.githubusercontent.com/assets/2177532/3482158/84f6ff24-037c-11e4-9cde-1716cdcda01d.jpg)
v0.9.8-1018-g318f641 human some problem
v0.9.8-1020-gcda9833 cannot see human
v0.9.8-1061-gcda9833 cannot see human
v0.9.8-1142-g1415532-windows-amd64\ bg full black
v0.9.8-1206-g9503603 cannot see human
v0.9.8-1219-gf664979 cannot see human
v0.9.8-1235-gd1357e5 semi problem on human
v0.9.8-1282-g935f1cb semi problem on human
v0.9.8-1538-gbe0340b semi problem on human
![2](https://cloud.githubusercontent.com/assets/2177532/3482277/72efb864-037e-11e4-8e70-d9ecd37a4082.jpg)

v0.9.8-1018-g318f641 log:
https://gist.github.com/sum2012/13c11126d5b9add2ef81
v0.9.8-1538-gbe0340b log:
https://gist.github.com/sum2012/b8d15983366d98e19a7e

**Comment by sum2012** [comment]
I review the issue.
The first bisect result is
https://github.com/hrydgard/ppsspp/commit/32439bc0062e6627eb7c591d8de2792f5c8a3eae

**Comment by sum2012** [comment]
Hmm,Another good test

v0.9.8-1224-g43bddd8 Good
v0.9.8-1235-gd1357e5 semi problem on human

**Comment by sum2012** [comment]
@unknownbrackets git bisect result:
https://github.com/hrydgard/ppsspp/commit/a54cefc1389b3e22f1ae72548e77e55f590a97f1
Hope you have idea for correct fix.

Anyway,v1.0.1-857-g08b340f gpu debugger
![1](https://cloud.githubusercontent.com/assets/2177532/9606908/b09b4d04-50f8-11e5-82a9-9c22023aa139.png)

**Comment by sum2012** [comment]
No,The git bisect result is wrong :(

**Comment by unknownbrackets** [comment]
Has anything improved here recently?

-[Unknown]

**Comment by daniel229** [comment]
No.

**Comment by sum2012** [comment]
v1.1.1-760-g07a1670 same problem
soft gpu no missing element but ugly 

![1](https://cloud.githubusercontent.com/assets/2177532/12418043/9713b38c-bee7-11e5-822d-eae5d46b3a36.jpg)

Can we try some code of invalidate to fix it ?

**Comment by unknownbrackets** [comment]
Haha, wow that is bad.

I still really wonder if this is depth related.  If you change the StateMapping.cpp file, and find:

```c++
			glstate.depthFunc.set(ztests[gstate.getDepthTestFunction()]);
```

And replace it with:

```c++
			glstate.depthFunc.set(GL_ALWAYS);
```

Does it draw all parts of the character?  It'll probably draw them wrong, but I'm wondering if it will at least draw everything.

-[Unknown]

**Comment by sum2012** [comment]
Yes.It draw all parts of the character.
Just a little ugly
![2](https://cloud.githubusercontent.com/assets/2177532/12450599/b6b0ab90-bfbf-11e5-9d05-bcc72bcea818.jpg)

**Comment by unknownbrackets** [comment]
So, the reason estimation affected this is because we only blit the depth if the render width and height matched.

Find this in Framebuffer.cpp:

```c++
void FramebufferManager::BlitFramebufferDepth(VirtualFramebuffer *src, VirtualFramebuffer *dst) {
```

And add below:
```c++
if (src->z_address == dst->z_address && src->z_stride != 0 && dst->z_stride != 0) {
    NOTICE_LOG(HLE, "Framebuffer switch with same depth, %dx%d -> %dx%d", src->renderWidth, src->renderHeight, dst->renderWidth, dst->renderHeight);
}
```

What does it say?  Ideally, use the GE debugger to click "Step Frame" twice.  That will show only one frame of the log, which will be most ideal.

-[Unknown]

**Comment by unknownbrackets** [comment]
Actually, how about this function instead:

```c++
void FramebufferManager::BlitFramebufferDepth(VirtualFramebuffer *src, VirtualFramebuffer *dst) {
	bool matchingDepthBuffer = src->z_address == dst->z_address && src->z_stride != 0 && dst->z_stride != 0;
	bool matchingSize = src->width == dst->width && src->height == dst->height;
	if (matchingDepthBuffer && matchingSize) {
		int w = std::min(src->renderWidth, dst->renderWidth);
		int h = std::min(src->renderHeight, dst->renderHeight);

		if (gstate_c.Supports(GPU_SUPPORTS_ARB_FRAMEBUFFER_BLIT | GPU_SUPPORTS_NV_FRAMEBUFFER_BLIT)) {
			// Only use NV if ARB isn't supported.
			bool useNV = !gstate_c.Supports(GPU_SUPPORTS_ARB_FRAMEBUFFER_BLIT);

			// Let's only do this if not clearing depth.
			fbo_bind_for_read(src->fbo);
			glstate.scissorTest.force(false);

			if (useNV) {
#if defined(USING_GLES2) && defined(ANDROID)  // We only support this extension on Android, it's not even available on PC.
				glBlitFramebufferNV(0, 0, w, h, 0, 0, w, h, GL_DEPTH_BUFFER_BIT, GL_NEAREST);
#endif // defined(USING_GLES2) && defined(ANDROID)
			} else {
				glBlitFramebuffer(0, 0, w, h, 0, 0, w, h, GL_DEPTH_BUFFER_BIT, GL_NEAREST);
			}
			// If we set dst->depthUpdated here, our optimization above would be pointless.

			glstate.scissorTest.restore();
		}
	}
}
```

-[Unknown]

**Comment by sum2012** [comment]
Talk in the first change first

Find this in Framebuffer.cpp:

```c++
void FramebufferManager::BlitFramebufferDepth(VirtualFramebuffer *src, VirtualFramebuffer *dst) {
```

And add below:
```c++
if (src->z_address == dst->z_address && src->z_stride != 0 && dst->z_stride != 0) {
    NOTICE_LOG(HLE, "Framebuffer switch with same depth, %dx%d -> %dx%d", src->renderWidth, src->renderHeight, dst->renderWidth, dst->renderHeight);
}
```

The GE debugger graphic not same as the first time (Step Frame)
![1](https://cloud.githubusercontent.com/assets/2177532/12463966/99e3359a-c001-11e5-8878-11afdc1186fa.jpg)

There is invalid address in the log (in your change)!!!
![1](https://cloud.githubusercontent.com/assets/2177532/12463984/c76342b2-c001-11e5-9f41-d5dc38fd67ac.png)

**Comment by sum2012** [comment]
In your second change,

```c++
void FramebufferManager::BlitFramebufferDepth(VirtualFramebuffer *src, VirtualFramebuffer *dst) {
	bool matchingDepthBuffer = src->z_address == dst->z_address && src->z_stride != 0 && dst->z_stride != 0;
	bool matchingSize = src->width == dst->width && src->height == dst->height;
	if (matchingDepthBuffer && matchingSize) {
		int w = std::min(src->renderWidth, dst->renderWidth);
		int h = std::min(src->renderHeight, dst->renderHeight);

		if (gstate_c.Supports(GPU_SUPPORTS_ARB_FRAMEBUFFER_BLIT | GPU_SUPPORTS_NV_FRAMEBUFFER_BLIT)) {
			// Only use NV if ARB isn't supported.
			bool useNV = !gstate_c.Supports(GPU_SUPPORTS_ARB_FRAMEBUFFER_BLIT);

			// Let's only do this if not clearing depth.
			fbo_bind_for_read(src->fbo);
			glstate.scissorTest.force(false);

			if (useNV) {
#if defined(USING_GLES2) && defined(ANDROID)  // We only support this extension on Android, it's not even available on PC.
				glBlitFramebufferNV(0, 0, w, h, 0, 0, w, h, GL_DEPTH_BUFFER_BIT, GL_NEAREST);
#endif // defined(USING_GLES2) && defined(ANDROID)
			} else {
				glBlitFramebuffer(0, 0, w, h, 0, 0, w, h, GL_DEPTH_BUFFER_BIT, GL_NEAREST);
			}
			// If we set dst->depthUpdated here, our optimization above would be pointless.

			glstate.scissorTest.restore();
		}
	}
}
```

Well done,it fixed

**Comment by sum2012** [comment]
@unknownbrackets You forget to fix directx 9 as well

**Comment by unknownbrackets** [comment]
I don't know how to make direct3d 9 blit depth buffers, it doesn't seem to work.  Just like GLES2, I guess.

-[Unknown]

**Comment by unknownbrackets** [comment]
I lied.  Or rather was wrong.  It seems like depth blitting works now, probably some other bug was fixed since last time I tried... will push a fix soon.

-[Unknown]

**Comment by sum2012** [comment]
find:

```c++
			dxstate.depthFunc.set(ztests[gstate.getDepthTestFunction()]);```

And replace it with:

```c++
			dxstate.depthFunc.set(ztests[true]);
```



same opengl before same test https://cloud.githubusercontent.com/assets/2177532/12450599/b6b0ab90-bfbf-11e5-9d05-bcc72bcea818.jpg

**Comment by hrydgard** [comment]
That's not much of a solution for anything, such a change would break almost every other game...

**Comment by sum2012** [comment]
@hrydgard 
I just hope @unknownbrackets have idea to correcly fix

**Comment by sum2012** [comment]
v1.1.1-882-ga1ff899 Image
Missing memory copy ?
![2](https://cloud.githubusercontent.com/assets/2177532/12702400/f2ce63f0-c862-11e5-8993-a9c4e3145bdb.jpg)

**Comment by unknownbrackets** [comment]
Does PixelDepthRounding help here?  I realized that some areas of Jeanne are doing that weird blocky thing seen above, and I don't know why.  But per-pixel depth rounding (GPU_SCALE_DEPTH_FROM_24BIT_TO_16BIT) fixes it.

-[Unknown]

**Comment by sum2012** [comment]
Yes, fixed.
I will send pull request soon.

**Comment by unknownbrackets** [comment]
A GE dump of this would really help, if possible.

-[Unknown]

**Comment by sum2012** [comment]
Please note only DirectX 9 and directx 11 have problem.
https://drive.google.com/file/d/1JszflcLdmnOtaAwGAfU55teNwjDQS-aD/view?usp=sharing

**Comment by Saramagrean** [comment]
v1.9.3-500-ge14bf3bcc on Android (use OpenGL)
![Screenshot_PPSSPP_20200311-053554](https://user-images.githubusercontent.com/26355472/76762032-195c8980-67c3-11ea-9460-1d3386714511.png)
Dump.
[dream c_ppdump (ogl).zip](https://github.com/hrydgard/ppsspp/files/4338397/dream.c_ppdump.ogl.zip)

**Comment by sum2012** [comment]
v1.9.3-812-g6798d4887-windows-amd64

opengl fixed
directx 9 still wrong.
frame dump:
https://gist.github.com/sum2012/7f6f88cf4af9e2a0746cac66d18e24b0
directx 11 still wrong
frame dump:
https://gist.github.com/sum2012/3fccf452c68c39de137fadc8fe753588
Vulkan  still wrong
https://gist.github.com/sum2012/4a4093518818fad9cb8be0d49a35c6fa

**Comment by sum2012** [comment]
v1.9.3-830-g9e5be91bf android (Phone:LG v20, default setting + frame skip 2)

opengl fixed.
Vulkan still wrong

**Comment by unknownbrackets** [comment]
Hm, I wonder if it's just small issues in our rounding still.  Might even be working only on certain GL implementations...

-[Unknown]

**Comment by sum2012** [comment]
v1.10.3-712-g7ed1ade56-windows-amd64
opengl still no problem
Vulkan fix by  #13446
Directx 9 and 11 still have problem

**Comment by sum2012** [comment]
@hrydgard 
v1.10.3-1220-g5c4a227b7 test
Opengl become white girl


![1](https://user-images.githubusercontent.com/2177532/99532009-925d5200-29de-11eb-8089-62e06818ee51.jpg)

v1.10.3-1202-g668fca01a bad
v1.10.3-1196-gc483d3f06 good
It mean #13656 

[recording.zip](https://github.com/hrydgard/ppsspp/files/5560147/recording.zip)

**Comment by hrydgard** [comment]
thank you, i'll look into it

**Comment by sum2012** [comment]
git bisect result https://github.com/hrydgard/ppsspp/pull/13656/commits/e14437cb3f75149d04db3571ed1c17027074d372

**Comment by hrydgard** [comment]
Fixed it for OpenGL again. Moving further work to 1.12.

**Comment by sum2012** [comment]
Re-test in v1.10.3-1324-g226a8be1c
Yes,Remain Directx 9 and Direct 11 have problem

**Comment by unknownbrackets** [comment]
The frame dump here appears to work for me in Direct3D 11 and Direct3D 9.  Is this potentially fixed?  Or does it not reproduce in the dump now?

-[Unknown]

**Comment by sum2012** [comment]
in v1.12.3-607-g2d7a7fd34
Opengl and Vulkan fixed.
Dx9 and DX 11 girl disappear

**Comment by sum2012** [comment]
My harddisk die again :(
Now I focus in making game in renpy

**Comment by unknownbrackets** [comment]
With the recent changes to depth buffer copying, I think this is even more likely to be fixed.  The INTZ change may have helped D3D9, potentially.

-[Unknown]

**Comment by sum2012** [comment]
OpenGL , DX9,Valkun no problem
DX11 and Soft gpu have problem
DX11:
https://img.chkaja.com/92bde1cfd326de86.jpg
Softgpu a little problem:
![1](https://user-images.githubusercontent.com/2177532/194960263-321a4d5a-49dd-461f-9c16-7dedceda48dc.png)

Update frame dump 
[ULJS00333.zip](https://github.com/hrydgard/ppsspp/files/9749564/ULJS00333.zip)

**Comment by unknownbrackets** [comment]
The correct rendering:
![#6497_ULJS00333_dreamclub_depth](https://user-images.githubusercontent.com/191233/194976612-71dc9de0-c5a0-40ae-bea6-c7ea560056ee.png)

Software renders:
![#6497_ULJS00333_dreamclub_depth_softgpu](https://user-images.githubusercontent.com/191233/194976740-2f26a0a0-50ca-46f2-a8fb-689044107d11.png)

There's some precision issue with some coordinates.  But it's actually pretty close.

D3D11 does better with the accuracy:
![#6497_ULJS00333_dreamclub_depth_directx11](https://user-images.githubusercontent.com/191233/194976935-c42c66a6-062d-4a76-9d24-6a470094697f.png)

The frame dump works on Windows 10 / Direct3D 11 using both NVIDIA and Intel.  I wonder if some drivers don't support depth readback or require it in a different format.

-[Unknown]

**Comment by sum2012** [comment]
@unknownbrackets some graphic problem may only see by part of iso (umd bufer)
jpcsp made it in https://github.com/jpcsp/jpcsp/commit/c2d7c8097020bac0a76339f607a2bac1a5c7f3d4
Do you interest it ?

**Comment by unknownbrackets** [comment]
I'm not really sure what that is, but it seems like a tool to see what sectors of the UMD the game read from.  I don't think it's relevant here?

-[Unknown]

**Comment by sum2012** [comment]
@unknownbrackets I only mean that easier to reproduce the problem

**Comment by sum2012** [comment]
Test in v1.16.3-14-gc4ad32420 of AMD cpu 7900 of AMD Integrated graphics card in windows 11
All render mode okay now.
