### ISSUE TITLE
Ranshima Monogatari Rare Land Story crashes when using FuncReplacements

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#6512]
without FuncReplacements it's fine.
log
https://gist.github.com/daniel229/4282dcfffb6bf470c40d

debug log(rename jpg to rar)
FuncReplacements on
![ppsspplog_crashing](https://cloud.githubusercontent.com/assets/3481559/3490065/9235b95a-0557-11e4-90b3-b098107484b8.jpg)

FuncReplacements off
![ppsspplog_no crashing](https://cloud.githubusercontent.com/assets/3481559/3490066/9259feaa-0557-11e4-9632-d8ee4caaf382.jpg)

stacktrace

```
>   0000000004cf00c6()  未知
    0000000044535953()  未知
    ffffffffffd5fdff()  未知
    0000000040000000()  未知
```

**Comment by unknownbrackets** [comment]
I wonder if this was a different problem or timing related.

If you change `REPFLAG_DISABLED` back to `0` for strcmp, does it still crash?  If yes, does it help to increase this number?

```c++
return 10;  // approximation
```

-[Unknown]

**Comment by daniel229** [comment]
Still crash after enable for strcmp. Try returen integer between 10 to 20 still not help it either.

**Comment by unknownbrackets** [comment]
We should probably decide if we want to just not use replacements (only use hooks), or if we want to revive this effort.  If we want to remove them, we should do that and close this issue.

I know it caused problems for Jak as well.  I think part of it may be the inability to reschedule during a function like memcmp.

-[Unknown]

**Comment by unknownbrackets** [comment]
I'm going to close this now, we can revisit if we ever decide to try replacements again.  They might have to be done in some alternate way.

-[Unknown]
