### ISSUE TITLE
Danganronpa 2 investigate wrong thing.

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#6525]
even with framebuffer to memory,since https://github.com/hrydgard/ppsspp/commit/1a8369e51c30b8f4486e32c819f890f011adc637.

a video
https://www.youtube.com/watch?v=djTi8PUqvNA

**Comment by daniel229** [comment]
Fixed in https://github.com/hrydgard/ppsspp/pull/7365 when that option set to off.

**Comment by unknownbrackets** [comment]
Hmm, the Danganronpa hack should force the investigation framebuffer to 1x.  I wonder if something different is happening or it's not being triggered.

-[Unknown]
