### ISSUE TITLE
Videos too bright in Valkyrie Profile (probably all games)

### ISSUE THREAD

**Issue by unknownbrackets** [hrydgard/ppsspp#6528]
While testing scePsmf, I noticed all videos were being decoded a few percent too bright.  I didn't think it was a big issue.

Then I noticed that Valkyrie Profile's door opening animation is a video.  It draws a regular scene, and then superimposes a video over just the door.  This causes the wall around the door to have a brighter color while it's opening (in other words, an ugly visible box of brightness on top of the door while it opens - this box being the same size as the video.)

Maybe there's some ffmpeg option we can use to change the color range we decode to?  I recall that TVs don't go as white or as black (I think?), and maybe videos are decoded using this same range?  Although, I think blacks were black in my scePsmf testing.

-[Unknown]

**Comment by unknownbrackets** [comment]
I wonder if we just need to use a different colorspace like SWS_CS_ITU709?  I don't know anything about colorspaces.  Are any of these colorspaces more likely than SWS_CS_DEFAULT (same as SWS_CS_ITU601)?

https://www.ffmpeg.org/doxygen/0.6/swscale_8h.html

-[Unknown]

**Comment by hrydgard** [comment]
@unknownbrackets ITU601 is used by component and DVD video, and many older formats. "HD video" uses http://en.wikipedia.org/wiki/Rec._709 , and even though the PSP has a low resolution, it uses the comparatively modern h.264 encoding, so it probably counts. That would mean SWS_CS_ITU709 . 

If you switch to that, can you check the door in Valkyrie Profile, as mentioned above?
