### ISSUE TITLE
There is something weird with F4(probably other keys too)and messages

### ISSUE THREAD

**Issue by vsub** [hrydgard/ppsspp#6541]
Was this always like this?
If I set a custom hotkey,pressing that key on slot that don't have state created,no message will be displayed.
And now also if I set a hotkey(even if it's F4),I also won't get a message and if I don't set anything and press F4,I'll get a message

**Comment by vsub** [comment]
This seems to still exist.
The message "Failed to load state: Savestate doesn't exist" appear only if you did not set a hotkey for loading the save state

**Comment by hrydgard** [comment]
That was an easy fix. Sorry, I've missed this issue completely.
