### ISSUE TITLE
IL-2 Sturmovik - Birds of Prey: sceMpegGetPcmAu issue

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#6546]
It is problem of "UNIMPL sceMpegGetPcmAu"
(If I make sceMpegGetPcmAu return -1,it work)

v0.9.8-1590-g88cfcf7 Debug log:
https://drive.google.com/file/d/0B3OaSdeV0L8kZUlJR2ZCME9PMTQ/edit?usp=sharing

**Comment by unknownbrackets** [comment]
Hmm, 593eec0bbee6f566453760e209b3c0669c29f31d is not unbelievable or anything.  Did that fix it?

I've added some reporting for this func and a few others, maybe we can look at all the games that use this.

-[Unknown]

**Comment by sum2012** [comment]
Yes,I was test wrong.
Anyway,I re-test ignore invalid address can in-game
log:
https://gist.github.com/sum2012/1b61080535386377dfff

**Comment by unknownbrackets** [comment]
Maybe `attrAddr` is optional?  Try putting `if (Memory::IsValidAddress(attrAddr)) Memory::Write_U32(attr, attrAddr);`?

-[Unknown]

**Comment by QWEmct** [comment]
For me works in three steps:
![screenshot_2015-03-01-01-16-56](https://cloud.githubusercontent.com/assets/8009425/6428368/0b164d80-bfb1-11e4-86ce-fb26a2681169.png)
![screenshot_2015-03-01-01-17-07](https://cloud.githubusercontent.com/assets/8009425/6428371/1da98c64-bfb1-11e4-8d74-b2b1f3ed86c3.png)
![screenshot_2015-03-01-01-17-17](https://cloud.githubusercontent.com/assets/8009425/6428373/2cc68c56-bfb1-11e4-814b-30a35008498d.png)

**Comment by sum2012** [comment]
@QWEmct  Yes,I have mention "re-test ignore invalid address can in-game"

**Comment by sum2012** [comment]
@unknownbrackets Yes,add that check no more invalid address

**Comment by sum2012** [comment]
But It log full of
28:41:238 av::vdecodin W[ME]: HLE\sceMpeg.cpp:1720 sceMpegGetAtracAu(08c2a2d0, 00000003, 08c2a3a0, 00000000):  didn't get a fake stream

log:
https://gist.github.com/sum2012/b2111581d30383ed9553

**Comment by unknownbrackets** [comment]
Yeah, I don't think it needs a fake stream there, but streamUid just needs to be in the map.

-[Unknown]

**Comment by QWEmct** [comment]
And button animation, it is impossible to create?

**Comment by hrydgard** [comment]
Well, as the PSP never had any rumble/vibration support, PSP games do not send any signals we could use to trigger rumble in gamepads. It might be possible to hook up rumble to the cheat engine though, that way people could write custom rumble cheats that detect certain situation in games, but that's a lot of work for every game.

**Comment by QWEmct** [comment]
I understand you. 
Hoped that this opportunity once will appear, at least in the game SBK 9, at departure on a roadside.
Anyway, you do a good serious work and I am grateful to you for that that already works in this program.
