### ISSUE TITLE
ATV Offroad Fury Pro graphics problem

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#6547]
buffering
![1](https://cloud.githubusercontent.com/assets/2177532/3564048/0ca17c22-0a69-11e4-94e9-3cfc62d18912.jpg)

![1aa](https://cloud.githubusercontent.com/assets/2177532/3564080/e81dfbb2-0a6a-11e4-8cbb-4b1a230c0225.png)
![1b](https://cloud.githubusercontent.com/assets/2177532/3564081/ee8daa7e-0a6a-11e4-9b98-3a10a2d27ea6.png)

soft gpu work
![2](https://cloud.githubusercontent.com/assets/2177532/3564050/103ffb2e-0a69-11e4-8ce7-f8ee0c8183f7.jpg)

![2a](https://cloud.githubusercontent.com/assets/2177532/3564084/ff97b8e6-0a6a-11e4-9c76-c2b9c14bb9ad.png)
![2b](https://cloud.githubusercontent.com/assets/2177532/3564085/0485cc30-0a6b-11e4-8465-5784ff5b216b.png)

**Comment by unknownbrackets** [comment]
Any change here?  If not, I wonder if we can try using breakpoints or anything to find what's happening.

-[Unknown]

**Comment by QWEmct** [comment]
@unknownbrackets 
Buffer
![screenshot_2015-02-28-22-18-27](https://cloud.githubusercontent.com/assets/8009425/6427656/e4c432fa-bf97-11e4-988f-b5debbbea28a.png)
Non-buffer render...
![screenshot_2015-02-28-22-16-10](https://cloud.githubusercontent.com/assets/8009425/6427658/f5509e60-bf97-11e4-9b80-c2977e7896e9.png)
Android 5.0.2 cm12

**Comment by sum2012** [comment]
I test windows version same result.
I think can detail teach me of the replacement function.
I set a breakpoint address 0x04088000 size 88000
![1](https://cloud.githubusercontent.com/assets/2177532/6428200/0c73b9ec-bfd4-11e4-9188-790575a33c5f.png)

**Comment by unknownbrackets** [comment]
Well, I wonder if that's related, it's hard to tell.  The texture is at 0x09693780, so that's what is ultimately needing to be updated.

I'm not sure if the above is tripped on a framebuffer, since this is using 0x44000 sized buffers actually, and the second one is at 0x48000 it seems.  I wonder if it's hiding something in the stride like Moto GP was...

-[Unknown]

**Comment by QWEmct** [comment]
v1.0.1-35-g7d93712
GPU
![screenshot_2015-03-01-01-40-47](https://cloud.githubusercontent.com/assets/8009425/6428467/27bbc408-bfb4-11e4-85c8-0091c06dc43b.png)

**Comment by hrydgard** [comment]
I assume you mean "Read Framebuffers to memory (GPU)"?

If so, this game belongs in #6261

**Comment by sum2012** [comment]
Read Framebuffers to memory (GPU) work in Android
But freeze in windows.
Windows log:
https://gist.github.com/sum2012/c802e76778f32f744dd5

**Comment by QWEmct** [comment]
@hrydgard 
Yes,  "Read Framebuffers to memory (GPU)"

**Comment by unknownbrackets** [comment]
If "read framebuffers to memory" helps, it almost definitely implies that we're missing a memcpy.  

Interesting candidates:

```
54:16:522 idle0        I[SCEGE]: GLES\Framebuffer.cpp:993 Creating FBO for 00002000 : 480 x 272 x 1

55:11:212 idle0        I[SCEGE]: GLES\Framebuffer.cpp:993 Creating FBO for 00090000 : 256 x 256 x 3
55:12:144 idle0        I[SCEGE]: GLES\Framebuffer.cpp:2025 Decimating FBO for 00090000 (256 x 256 x 3), age 6
```

I'd try setting memory breakpoints for all of these ranges, and see if any are hit.  The ranges are:

0x04002000 size=0x00044000
0x04090000 size=0x00040000

-[Unknown]

**Comment by daniel229** [comment]
I get it
![01](https://cloud.githubusercontent.com/assets/3481559/12077945/7974e074-b237-11e5-8acc-350a090956cc.png)
![02](https://cloud.githubusercontent.com/assets/3481559/12077946/797697fc-b237-11e5-8ded-cc07e5f269ee.png)
