### ISSUE TITLE
Mahou Shoujo Madoka Magica Portable in-game problem

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#6557]
Load the save
https://drive.google.com/file/d/0B3OaSdeV0L8kb0ZRRTN2amltdDA/edit?usp=sharing

after die,W[MM]: MemmapFunctions.cpp:93 ReadFromHardware: Invalid address 00000000

v0.9.8-1614-g459e244
info log: 
https://gist.github.com/sum2012/654b7f4370045f5fa286
debug log:
https://drive.google.com/file/d/0B3OaSdeV0L8kcGRBOER1NXBhcEU/edit?usp=sharing

**Comment by unknownbrackets** [comment]
Reported not fixed by the async IO changes in #7636.

-[Unknown]

**Comment by Panderner** [comment]
Simulated UMD delays helps it to prevent crashes

**Comment by sum2012** [comment]
Update savedata to easier to reproduce.
https://drive.google.com/file/d/1wvDHLaYCReY0wmH6DZscW1hoWN3kcN4n/view?usp=sharing
v1.10.3-1639-g4eee5df2a
bad log: https://drive.google.com/file/d/1vOw7m5_kpIYehpA5dc9PnoXB1GI-83L-/view?usp=sharing
Simulate UMD delay good log: https://drive.google.com/file/d/1c03HMxkfaqopsUxKrT8QbnFz_H1knTnu/view?usp=sharing

The game maybe related to I\O add sceKernelUnlockMutex,sceKernelLockMutex staff

**Comment by sum2012** [comment]
@unknownbrackets There is two case that we need reschedule (from jpcsp)
https://github.com/jpcsp/jpcsp/blob/master/src/jpcsp/HLE/kernel/managers/MutexManager.java#L121
https://github.com/jpcsp/jpcsp/blob/master/src/jpcsp/HLE/kernel/managers/MutexManager.java#L155

**Comment by sum2012** [comment]
@unknownbrackets Can you try translate it ? seem ppsspp don't have it. https://github.com/jpcsp/jpcsp/blob/master/src/jpcsp/HLE/kernel/managers/MutexManager.java#L154

**Comment by benderscruffy** [comment]
is this still a problem??

**Comment by sum2012** [comment]
v1.13.1-603-g59cb7a075
Still need Simulated UMD delays

**Comment by unknownbrackets** [comment]
> @unknownbrackets Can you try translate it ? seem ppsspp don't have it. https://github.com/jpcsp/jpcsp/blob/master/src/jpcsp/HLE/kernel/managers/MutexManager.java#L154

Sorry, I think I never saw this before.  PPSSPP does do that, here:
https://github.com/hrydgard/ppsspp/blob/80e481bbdc4dd562714d3c395710c5a25f957279/Core/HLE/sceKernelThread.cpp#L3027

-[Unknown]

**Comment by sum2012** [comment]
I was too deep to jpcsp's code ,don't think the game's code itself

**Comment by sum2012** [comment]
Reopen as it is wrong change
