### ISSUE TITLE
xscreensaver is not inhibited

### ISSUE THREAD

**Issue by uberushaximus** [hrydgard/ppsspp#6563]
PPSSPP does not inhibit xscreensaver from running. This can cause issues as xscreensaver will try to run over ppsspp, will fail to grab the screen and instead grab keys leaving the user in an awkward position trying to save and close PPSSP. A workaround is to kill xscreensaver before running PPSSPP and launching it again afterwards.

**Comment by unknownbrackets** [comment]
According to SDL's documentation, the screensaver is disabled by default nowadays.  Therefore I'm closing.

If it's not working correctly, please feel free to comment with more detail.

-[Unknown]
