### ISSUE TITLE
PPSSPPSDL does not hide mouse pointer

### ISSUE THREAD

**Issue by uberushaximus** [hrydgard/ppsspp#6564]
When using PPSSPPSDL on linux the mouse is not captured and hidden, leaving the user to have to manually move it off screen rather than hiding it after a timeout.

**Comment by unknownbrackets** [comment]
Anyone want to submit a pull request to fix this now that we're living in SDL2 land?

-[Unknown]

**Comment by hrydgard** [comment]
Closing, remaining misbehaviours should be fixed when we fix #6564 .
