### ISSUE TITLE
Rockman Dash 2 GPU hungry in certain stage

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#6570]
since https://github.com/hrydgard/ppsspp/pull/6396
it's 2500% more stress for the GPU with that hack.

with that hack
12fps and 98% GPU usage
![01](https://cloud.githubusercontent.com/assets/3481559/3615424/7512c4a2-0dc8-11e4-9cf9-e197fc1e12ba.jpg)

without that hack
30fps and 9% GPU usage
![02](https://cloud.githubusercontent.com/assets/3481559/3615426/78910544-0dc8-11e4-8cfc-f6ec3d212e79.jpg)

**Comment by unknownbrackets** [comment]
Where is this game rendering when it renders to the same target as it's texturing from?  Some form of bloom?

-[Unknown]

**Comment by daniel229** [comment]
Fixed in https://github.com/unknownbrackets/ppsspp/commit/62de281e3580a27b7fa185e21a7a0b0d1639126b
