### ISSUE TITLE
If I receive SaveData from PSP and CPUSpeed =?

### ISSUE THREAD

**Issue by QWEmct** [hrydgard/ppsspp#6572]
I nevertheless do tests, and I am again convinced. My device can work faster, than actually.

FPS knee-bends, sound gnash:
![screenshot_2014-07-17-22-14-00](https://cloud.githubusercontent.com/assets/8009425/3618954/ac3ef046-0def-11e4-9b8e-c5eaffb0ecec.png)
There are no sound problems, game process, passes very much qualitatively and quickly:
![screenshot_2014-07-17-22-15-08](https://cloud.githubusercontent.com/assets/8009425/3618963/c0d2fb60-0def-11e4-86c1-266a3e45a1d4.png)
![screenshot_2014-07-17-22-15-34](https://cloud.githubusercontent.com/assets/8009425/3618972/d04a6eac-0def-11e4-914c-63728b9e8d94.png)
![screenshot_2014-07-17-22-18-23](https://cloud.githubusercontent.com/assets/8009425/3618975/e396b9a2-0def-11e4-8e70-42b7e798ad2b.png)
Samsung Galaxy Note 2. Android 4.3
________
Also I will add 19.07.14:
You see that the screen too dark.

**Comment by unknownbrackets** [comment]
Reducing the cpu speed will cause unpredictable bugs.  This isn't really something we can fix.

-[Unknown]

**Comment by QWEmct** [comment]
@unknownbrackets 
RetroArch the calculator is used:
![screenshot_2015-01-21-16-59-50](https://cloud.githubusercontent.com/assets/8009425/5837324/39c84eca-a18f-11e4-8cb5-1c05604233a7.png)
PPSSPP should be done manually what to pass jit and to accelerate work of many games.
(If you didn′t correct it).

**Comment by unknownbrackets** [comment]
If we add an option to calculate an ideal CPU speed to PPSSPP, the result will always be 0, automatic.  I will be strongly opposed to **recommending** users set it to especially some weird value like 90.

-[Unknown]
