### ISSUE TITLE
Mana Khemia 1 Chinese patch,video skiped during playback

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#6574]
Never works before.
debug log (rename jpg to rar)
![ppsspplog](https://cloud.githubusercontent.com/assets/3481559/3623670/132019b8-0e52-11e4-8b4f-2ebead7c7ea9.jpg)

**Comment by sum2012** [comment]
Update the log to v1.2.1-57-g3924d8b
https://gist.githubusercontent.com/sum2012/d671f413fbf098ea762f/raw/b112bf637f6115435ed840c3d7f4ed27b6fbc391/gistfile1.txt

@unknownbrackets 
I try ffplay,it played video without sound,no missing video.
Can we use ffmpeg of HasReachedEnd function  or HasReachedEnd  has something wrong ?

![1](https://cloud.githubusercontent.com/assets/2177532/13653349/2eda2b30-e68c-11e5-9fb9-d52011d0d221.png)

**Comment by unknownbrackets** [comment]
Well, ultimately sceMpeg has some of the issues sceAtrac used to... although they're different.

sceMpeg just plays the packets you give it, really.  Although it manages forward movement, you're welcome to loop a video by just feeding it packets from earlier in the stream.  It will just play them.

So, "has reached end" is kind of a wrong concept to begin with.  sceMpeg doesn't think about "end", it just knows when it has no more packets.  If I gave it the first half of a video's packets, and then stopped giving it new packets... the video "ended".  And if I loop the video, and keep giving it packets forever, it will never "end."

This issue may be similar to the Danball Senki issue - see #8464, e866d835472cb36f629343ced21d6cd7bdca7793, and #8437.  Does it work if you put that change back?

-[Unknown]

**Comment by sum2012** [comment]
@unknownbrackets No,it is psmf

**Comment by sum2012** [comment]
Hmm so that mean that real psp don't read the header of the video file.

**Comment by sum2012** [comment]
@unknownbrackets 
jpcsp can incrase video time by this change
https://github.com/sum2012/jpcsp-1/commit/48ca58019828fd9585a879e46714771a7c12efaa
Maybe ppsspp also this change ?

**Comment by unknownbrackets** [comment]
So basically, you're saying that the length value in the PSMF header is ignored, and it should just use the filesize instead?

That sounds like something we should test.

-[Unknown]

**Comment by sum2012** [comment]
@unknownbrackets Yes,that is my meaning.
@daniel229 Use what software to patch the .pmf file ? I tried to use umdgen but crash in saving.

**Comment by daniel229** [comment]
Try the WQSG_UMD.

**Comment by sum2012** [comment]
@daniel229 Thanks,it work

**Comment by sum2012** [comment]
@unknownbrackets please also test "timestamp value in the PSMF header is ignored" 
JPCSP fix it in https://github.com/jpcsp/jpcsp/commit/7e4a74d479c89ca35e021a2500e0776002ba9be0
and https://github.com/jpcsp/jpcsp/commit/2c0d219135a2821ab1e6c3e67dc47191f4ba4482

**Comment by unknownbrackets** [comment]
I used a short video with a header size (12 bytes into the file) of 0006A000.  I tried 0000A000 and 0003A000.  Both cutoff the video at different points and caused issues.  It did not play the entire video.

I tried this with `scePsmfPlayerSetPsmfCB`, `scePsmfPlayerSetPsmf`, and `scePsmfPlayerSetPsmfOffsetCB`.

What header length does it have in this game, and what is the actual file size?

What versions of libpsmfplayer.prx and psmf.prx does it use?  This is reported by PPSSPP in the log - you can also try giving me the crc of the files and I can compare with the ones I'm testing against.  Maybe this only affects certain psmf versions.

-[Unknown]

**Comment by sum2012** [comment]
Accordering my earily log: https://gist.githubusercontent.com/sum2012/d671f413fbf098ea762f/raw/b112bf637f6115435ed840c3d7f4ed27b6fbc391/gistfile1.txt

scePsmf_library with version 0101, devkit 03070010
scePsmfP_library with version 0101, devkit 03070010
psmf.prx Size:	7,056 CRC-32:	089F0C2E
libpsmfplayer.prx Size:	35,520 CRC-32:	BEE912BB

Chinese version header:
![1](https://cloud.githubusercontent.com/assets/2177532/17647869/e62782e0-6235-11e6-8d06-d746156fa116.png)

orignal version header(japanese)
![2](https://cloud.githubusercontent.com/assets/2177532/17647887/2b6799c6-6236-11e6-8e39-94d62c5cc1e1.png)

**Comment by unknownbrackets** [comment]
Is the Japanese version 16863232 bytes (~16.08 MB)?  How big is the Chinese version?  I'm guessing it's larger than 5935104 bytes (~5.66 MB.)

-[Unknown]

**Comment by sum2012** [comment]
Japense  Size:	16,863,232
Chinese Size:	17,039,360

**Comment by unknownbrackets** [comment]
Thanks - confirmed.  That version of the library doesn't have scePsmfPlayerSetPsmfOffset or scePsmfPlayerSetPsmfCB, and also doesn't seem to respect the stream size.  Let me check when it changed.

-[Unknown]

**Comment by unknownbrackets** [comment]
Okay, #8914 should give that behavior.  I'm not sure about the last timestamp handling.

-[Unknown]

**Comment by daniel229** [comment]
Still skiped later with https://github.com/hrydgard/ppsspp/pull/8914 merged.

**Comment by sum2012** [comment]
@unknownbrackets we cannot port JPCSP of "last timestamp" fix
https://github.com/jpcsp/jpcsp/commit/2c0d219135a2821ab1e6c3e67dc47191f4ba4482 ?

**Comment by sum2012** [comment]
hmm , I has idea ,just not sure right
I am going to pull request in unknownbrackets:psmf-size branch
