### ISSUE TITLE
Games which delete the "SAVEDATA" folder.

### ISSUE THREAD

**Issue by ghost** [hrydgard/ppsspp#6600]
These games delete the "SAVEDATA" folder, together with its contents.
![screenshot_2014-07-21-14-55-24](https://cloud.githubusercontent.com/assets/8009425/3642686/beea4e6a-10c5-11e4-9f09-fca2fcfe0957.png)
![screenshot_2014-07-21-15-49-17](https://cloud.githubusercontent.com/assets/8009425/3643074/267f28d2-10cd-11e4-9de1-fcd690d97886.png)
![2014-07-21 14 41 05](https://cloud.githubusercontent.com/assets/8009425/3642690/d181fca8-10c5-11e4-97b2-852f0315174e.png)

**Comment by unknownbrackets** [comment]
Has this been resolved now, or are there still cases where deleting in game can delete unexpected saves?

-[Unknown]

**Comment by Gamemulatorer** [comment]
Tried latest build.

https://user-images.githubusercontent.com/37603562/206863080-5f3338d7-8e21-4816-9a06-931d82c92d76.mp4

**Comment by unknownbrackets** [comment]
Okay, I'll close assuming it's resolved, we have several protections now against this iirc.

-[Unknown]
