### ISSUE TITLE
NBA 2K13 [ULES01578] - Menu glitches during save creation.

### ISSUE THREAD

**Issue by ppmeis** [hrydgard/ppsspp#6603]
When you create a V.I.P. profile, game shows menus overlapped:

![image](https://cloud.githubusercontent.com/assets/4381277/3649806/f2f2994c-1115-11e4-8e65-ae86d63254bf.png)

Softgpu looks the same:
![image](https://cloud.githubusercontent.com/assets/4381277/3649837/31b5ca8c-1116-11e4-974d-c3247649277e.png)

Real hardware:
![nba2k13](https://cloud.githubusercontent.com/assets/4381277/3649915/000b60f4-1117-11e4-8f2f-490b762abe6e.png)

GE Debugger:
![image](https://cloud.githubusercontent.com/assets/4381277/3649881/9f5dc2ba-1116-11e4-95a8-b8fe983158fa.png)
![image](https://cloud.githubusercontent.com/assets/4381277/3649885/a5cdf278-1116-11e4-91a9-d5f47879fac2.png)

**Comment by ppmeis** [comment]
tested latest build. Issue still present

**Comment by thedax** [comment]
@ppmeis: Just curious, but does anything change if you use the Phantasy Star hack with this game?

**Comment by ppmeis** [comment]
@thedax hack does not help:
![image](https://cloud.githubusercontent.com/assets/4381277/5821556/4f5c3f20-a0cd-11e4-9701-2ad3ac7f1320.png)

**Comment by thedax** [comment]
Thanks.

**Comment by ppmeis** [comment]
Tested with latest build. Same status.

**Comment by ppmeis** [comment]
Tested with latest build. Same status:
![image](https://cloud.githubusercontent.com/assets/4381277/6453629/42167612-c140-11e4-93d5-3209ed31a7ac.png)

**Comment by ppmeis** [comment]
Tested with latest build. Same status:
![image](https://cloud.githubusercontent.com/assets/4381277/8889827/97bf6bd4-32ea-11e5-85a0-b3a80f080c7c.png)

**Comment by daniel229** [comment]
Fixed in #7920
