### ISSUE TITLE
FPS at half speed when Multithread is enable

### ISSUE THREAD

**Issue by ppmeis** [hrydgard/ppsspp#6612]
Today I detect while playing Virtua Tennis: World Tour, if multithread option is enable game goes at exactly half speed when the match is ready:

Multithread disable:
![image](https://cloud.githubusercontent.com/assets/4381277/3663760/57522f22-11d6-11e4-99cc-69294ef9cdb3.png)

Multithread enable:
![image](https://cloud.githubusercontent.com/assets/4381277/3663772/6f40942a-11d6-11e4-86d4-72c1fe0e4e06.png)

**Comment by ppmeis** [comment]
Tested with latest build. Same issue.

**Comment by ppmeis** [comment]
Tested with latest build. Same status.

**Comment by ppmeis** [comment]
Tested with latest build. Same status:
![image](https://cloud.githubusercontent.com/assets/4381277/6453614/2063684a-c140-11e4-84a1-62e9655165fe.png)

**Comment by ppmeis** [comment]
Tested with latest build. Same status.

**Comment by ppmeis** [comment]
Tested with latest build. Same status.

**Comment by ppmeis** [comment]
Tested with latest build. Same status.

**Comment by ppmeis** [comment]
Tested latest buil. Same issue.

**Comment by hrydgard** [comment]
This won't be fixed, instead the existing multithread mode will go away after 1.2.0, and will be replaced with a different one later.

**Comment by ppmeis** [comment]
@hrydgard nice to know that. Should I close this issue then? estimated release date for 1.2.0?

**Comment by ppmeis** [comment]
Tested with latest build. It seems new Multithread mode is not implemented yet. @unknownbrackets

**Comment by unknownbrackets** [comment]
It's gonna take some commits and pull requests to implement.  The plan is basically to process GPU instructions but queue them, and then process them on a separate thread (or threads maybe even, in Vulkan.)

We'll still need barriers for some things, and there can still be glitches from memory getting modified, so it'll be tricky.  But at least we can have the timing predictable.

-[Unknown]

**Comment by ppmeis** [comment]
Tested with latest build. It seems when I load the game with Multithread enable it works fine:

![image](https://cloud.githubusercontent.com/assets/4381277/15275389/9ad820a4-1aca-11e6-97f7-ac121bd17787.png)

But if you go to PPSSPP menu and then back to the game without touching any option, FPS drops again:

![image](https://cloud.githubusercontent.com/assets/4381277/15275394/ce54702c-1aca-11e6-8c15-fbda8bbfc501.png)

**Comment by zminhquanz** [comment]
Project Diva Extend when enable Multithread is still half FPS , not boost performance , off multithread is normal
