### ISSUE TITLE
Dante's Inferno freezes and cannot be finished

### ISSUE THREAD

**Issue by nfjorgebueno** [hrydgard/ppsspp#6615]
21:51:015 Util\BlockAllocator.cpp:224 D[HLE]: Merging Blocks
21:51:015 Util\BlockAllocator.cpp:224 D[HLE]: Merging Blocks
21:51:015 Util\BlockAllocator.cpp:224 D[HLE]: Merging Blocks
21:51:015 Util\BlockAllocator.cpp:224 D[HLE]: Merging Blocks
21:51:015 Util\BlockAllocator.cpp:249 D[HLE]: Block Alloc found adjacent free blocks - merging
21:51:015 Util\BlockAllocator.cpp:224 D[HLE]: Merging Blocks
21:51:015 Util\BlockAllocator.cpp:229 D[HLE]: Block Alloc found adjacent free blocks - merging
21:51:015 Util\BlockAllocator.cpp:224 D[HLE]: Merging Blocks
21:51:015 Util\BlockAllocator.cpp:229 D[HLE]: Block Alloc found adjacent free blocks - merging
21:51:015 Util\BlockAllocator.cpp:249 D[HLE]: Block Alloc found adjacent free blocks - merging
21:51:015 Util\BlockAllocator.cpp:224 D[HLE]: Merging Blocks
21:51:015 Util\BlockAllocator.cpp:229 D[HLE]: Block Alloc found adjacent free blocks - merging
21:51:015 Util\BlockAllocator.cpp:249 D[HLE]: Block Alloc found adjacent free blocks - merging
21:51:015 Util\BlockAllocator.cpp:224 D[HLE]: Merging Blocks
21:51:015 Util\BlockAllocator.cpp:249 D[HLE]: Block Alloc found adjacent free blocks - merging
21:51:031 MemMap.cpp:377 D[MM]: Memory system shut down.
21:51:031 GLES\Framebuffer.cpp:2071 I[SCEGE]: Destroying FBO for 00000000 : 512 x 272 x 0
21:51:031 GLES\Framebuffer.cpp:2071 I[SCEGE]: Destroying FBO for 00088000 : 512 x 272 x 3
21:51:031 GLES\Framebuffer.cpp:2071 I[SCEGE]: Destroying FBO for 00110000 : 512 x 128 x 3
after hours of play happens in latest builds so can not play.thanks

**Comment by daniel229** [comment]
Which stage it freezes?

**Comment by daniel229** [comment]
I just finished the game JPN version with the recent builds(0.9.9.1-1503+) without any crash or freeze.

**Comment by unknownbrackets** [comment]
Sweet, closing.

-[Unknown]
