### ISSUE TITLE
Unexpected user-reported slowdowns in 0.9.9 after upgrading from 0.9.8

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#6617]
Naruto Shippuden Ultimate: http://forums.ppsspp.org/showthread.php?tid=1660&page=31

"Strangely this game's fps and speed decreased dramatically on my galaxy s4 mini ( only 20%speed WHAT THE HELL!!!!)....i was using new 0.99 but after i download older apk 0.98, it works again with about 100% speed...seriously how could this happened????"

I got another report but can't find it. Thought I'd try to collect them and see if there's a common cause (most likely something disabled by "Disable slow effects" but I want to be sure).

**Comment by unknownbrackets** [comment]
I think we've done mostly what we can do here.  We're always trying to improve performance.  Is there any value in keeping this open?

-[Unknown]
