### ISSUE TITLE
on screen touch button freeze

### ISSUE THREAD

**Issue by deckkun** [hrydgard/ppsspp#6618]
plz fix.this problam not happen on 0.9.8,on screen touch button keep freezing when i play game,running on sony xperia sola

**Comment by unknownbrackets** [comment]
Can you give more details?  Does it happen when you do certain things?  Does it still happen in the latest version?

-[Unknown]

**Comment by unknownbrackets** [comment]
Closing because we can't figure this out without more feedback.  Please comment with more detail if it's still happening, and we can reopen.

-[Unknown]
