### ISSUE TITLE
Difference btw PS3 and PPSSPP saves?

### ISSUE THREAD

**Issue by GamerzHell9137** [hrydgard/ppsspp#6623]
I have copied the PPSSPP saves to my PS3 so i can play the games on my PS3 but the thing is that the PS3 won't load the saves from PPSSPP and vice versa too, PS3 saves can't be loaded on PPSSPP.
The log and the screen look like this
![55](https://cloud.githubusercontent.com/assets/2002038/3687258/586807fc-1324-11e4-9614-a62aaf8805a7.png)
![56](https://cloud.githubusercontent.com/assets/2002038/3687257/5850aa58-1324-11e4-9f87-8e3366ef4d2c.jpg)

And then the game stucks on the loading screen and then PPSSPP crashes

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	PPSSPPWindows64.exe
  Application Version:	0.9.9.0
  Application Timestamp:	53ce798b
  Fault Module Name:	StackHash_f9d8
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	00000000
  Exception Code:	c0000005
  Exception Offset:	000000000f4bbdec
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	f9d8
  Additional Information 2:	f9d82b147b6ad3097a0d9c822ca02a2a
  Additional Information 3:	de0a
  Additional Information 4:	de0a40479120ea8170f842d4122846d6

**Comment by unknownbrackets** [comment]
Do the saves load and work on a PSP?  If they work there, then there may be some special thing the PS3 is doing.  If they don't work there, it's probably specific to the game.  You didn't even mention which game.

Also, if this PS3 has been hacked, does it work to copy saves from a real PSP on it, or does that fail in a similar way?  If that fails, then it may be an artifact of the PS3 being hacked.

-[Unknown]

**Comment by GamerzHell9137** [comment]
iirc it was fixed in later revisions.
I might be wrong but i didn't have issues copying saves from PPSSPP to PS3 this year..
