### ISSUE TITLE
Loco Roco 1 (and possibly 2)

### ISSUE THREAD

**Issue by Xemiru** [hrydgard/ppsspp#6626]
Issue in World 1 Stage 2.
![screenshot 2014-07-24 15 07 51](https://cloud.githubusercontent.com/assets/1240058/3695509/4ffe5872-137f-11e4-9c75-72d99109e8f2.png)
Getting to this part where the Roco's have to wake up this sleeping block, they don't seem to sing when they're supposed to. No sound or music comes in for them to sing along to, so its just awkward silence until its supposed to be done.

![screenshot 2014-07-24 15 10 13](https://cloud.githubusercontent.com/assets/1240058/3695515/727590f0-137f-11e4-9220-11defb9f44b6.png)
After that, the game just zooms in on the Roco's. creepily.
It takes awhile for the game to realize its over before letting you continue on to finish the stage. Throughout the rest of the stage however, you can clearly hear the songs desynced. If the Roco's sing, their singing's desynced with the music as well.

Windows 7 x64 - v0.9.9-20-g45263fd - Loco Roco (UCUS98662)

Audio speed hack is turned off.
Simulate block transfer is turned off.
Buffered rendering is used with 5x PSP resolution.
No speedup options are enabled.
Fast memory and real clock sync are disabled.

**Comment by s0r00t** [comment]
I know that this issue is pretty old, but it seems fixed here on Android.

**Comment by LunaMoo** [comment]
Thanks for the update:3, going to close it then, can always just reopen later if someone still has this problem.
