### ISSUE TITLE
Proper full-screen on Mac OS X 10.7+ for SDL frontend

### ISSUE THREAD

**Issue by tjg1** [hrydgard/ppsspp#6629]
Could we get native full-screen support on Mac so that PPSSPP occupies its own workspace (virtual desktop) in Mission Control (Expose) and can be ⌘-Tabbed out of?

Currently PPSSPP intercepts all keyboard input in fullscreen mode and it's impossible to switch to another app without first switching out of fullscreen mode (switching display size is really buggy and often results in the PPSSPP display turning solid blue, at least on OS X) or exiting it completely.

**Comment by vit9696** [comment]
This has been fixed years ago, as PPSSPP uses SDL2 on macOS at present.
