### ISSUE TITLE
Android 4.4.2 KitKat. Deleting files from the built-in memory stick.

### ISSUE THREAD

**Issue by QWEmct** [hrydgard/ppsspp#6631]
It isn't possible, to delete files ~iso & cso..., without built-in file manager.

Yesterday I received 4.4.2 KitKat. Now this function for me doesn't work.
![2014-07-25 15 40 13](https://cloud.githubusercontent.com/assets/8009425/3701928/e5cce8e0-13f8-11e4-8c53-36f9db6e4d5e.png)

**Comment by unknownbrackets** [comment]
This works fine for me on Android in Marshmallow.

-[Unknown]
