### ISSUE TITLE
line in buffered render

### ISSUE THREAD

**Issue by daniellegal** [hrydgard/ppsspp#6634]
during i play the emulator shows a line down in the screen while in buffered render
![npjh50686_00000](https://cloud.githubusercontent.com/assets/8229133/3709751/182252be-1460-11e4-8c04-0e2506410935.png)

**Comment by unknownbrackets** [comment]
Does this happen with default settings?  Does it happen with default settings + render resolution at 1x PSP?

-[Unknown]

**Comment by daniel229** [comment]
duplicate of https://github.com/hrydgard/ppsspp/issues/7470
