### ISSUE TITLE
Silent Hill Origins - ingame cutscenes don't work

### ISSUE THREAD

**Issue by ratfield** [hrydgard/ppsspp#6636]
Latest win32 build. Everything works fine, until the cutscene when you first meet Lisa. Cutscene just stops playng after few seconds, when Travis say "Well, I'm done here". Then game continues normally. All cutscenes after this point, acts the same way - stops playing after few seconds. This is very frustrating...

![cut](https://cloud.githubusercontent.com/assets/6744430/3711411/bf359722-14d4-11e4-8714-8e3c9293882c.jpg)

**Comment by Tahgira** [comment]
So.. Is there a way to get around this at all?

**Comment by ratfield** [comment]
No. There is no way, as far as I know...
