### ISSUE TITLE
Implement the remaining buttons (as stubs?)

### ISSUE THREAD

**Issue by Krude** [hrydgard/ppsspp#6646]
Most of the missing buttons don't serve a function (yet), like the Home button or the Hold switch, but they can be used in button combinations with Cwcheat. Since their button bit isn't defined yet, they will always report as off, though.

The WLAN toggle at least could report whether, well, the WLAN feature is set on or off. 
The Note and Volume keys could be tied to their audio functions, even though it's probably faster/more comfortable to set through PPSSPP's gui.

What would be nice are at least some stub keys you can bind, that report on/off to sceCtrl to be used in Cwcheat button combinations.

**Comment by unknownbrackets** [comment]
Hmm.  This might be a bit involved.

We currently map 0x00010000 and higher as "virtual keys".  This is how we handle speed toggle, etc.  As it happens, that's ALSO the home button, which can in cases we read by the usermode code.  So this means redoing the way we save mapped controls and handle virtkeys...

See here for the defines and basic handling:
https://github.com/hrydgard/ppsspp/compare/master...unknownbrackets:ctrl-extra

I'm not interested enough to mess with the control mapping conversion, though...

-[Unknown]

**Comment by LunaMoo** [comment]
I really don't understand what kind of "control mapping conversion" was needed for that "ctrl-extra" branch proposed in here.
 I might be missing something, but I merged it with just slight changes simply using higher numbers for virtual keys as can be seen here ~ https://github.com/LunaMoo/ppsspp/commit/48cf80f4fe652067941d0b02816f454ad38b1d91 (ignore KeyMap.cpp stuff - it's on my playground branch where I make lots of personal changes) ~ and everything(existing virtual and new psp keys) appears to work perfectly fine.

**Comment by hrydgard** [comment]
Yeah, I think you're right - there shouldn't be much more too it than that. Feel free to pull request without that KeyMap.cpp stuff - wouldn't you be better off keeping that in a controls.ini anyway? :)
