### ISSUE TITLE
God of War  Chains of Olympus flickering

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#6649]
Since https://github.com/hrydgard/ppsspp/pull/6326
The title or the sky of this screen would be more noticable.
![04](https://cloud.githubusercontent.com/assets/3481559/3734959/a0c243b6-171e-11e4-847a-380d16125d5b.jpg)

**Comment by unknownbrackets** [comment]
Is this still happening?

-[Unknown]

**Comment by ppmeis** [comment]
Tested on latest Windows build, default setting. No more flickering:

![image](https://user-images.githubusercontent.com/4381277/48318944-98f2ab00-e607-11e8-8547-acfee03d44b7.png)
