### ISSUE TITLE
Legend of Heroes Trails in the Sky (ULUS10540) : Extremely twitchy character arrow marker in the minimap when moving/facing northwards with Function Replacements and Simulate Block Transfers enabled.

### ISSUE THREAD

**Issue by solarmystic** [hrydgard/ppsspp#6652]
First "responsible" commit found via bisecting is https://github.com/hrydgard/ppsspp/commit/a7b9ce205b6c43b52c71ebaf95f9bf599b4ccc50 by @unknownbrackets which enabled function replacements (FR) by default.

![capture](https://cloud.githubusercontent.com/assets/4345150/3743136/b9f016f6-1773-11e4-9d47-eaa49929e4e1.PNG)

Last "unaffected" commit is https://github.com/hrydgard/ppsspp/commit/986d54039c450faf8945c06ab1527b88db979cd7

(I am aware that the issue lies with FR itself and only remained asymptomatic in previous revisions due to FR not being exposed in the options and enabled, hence the quotation marks.)

Short video demonstration of the issue:-
https://www.mediafire.com/?w02nn5textr4qmk

Savedata for issue reproduction (rename jpg to 7z and unzip using 7zip):-
![ulus105400004](https://cloud.githubusercontent.com/assets/4345150/3742814/4d940710-176e-11e4-9594-4d65297b2704.jpg)

Reproduction Method:-

1. Start the game using any revision from v0.9.8-1052-ga7b9ce2 onwards, ensuring that Simulate Block Transfers and Function Replacements are enabled.

2. Load the provided savedata.

3. Walk northwards (straight up).

4. Have a look at the minimap, and note that the arrow denoting your characters position is twitchy.

Caveats:-

1. Does not occur if either Simulate Block Transfers or Function Replacements is disabled. Incidentally, the game needs both options enabled for some of the advanced graphical effects to work with Buffered Rendering (e.g. the transparent status menu and save screenshots.)

2. Only occurs when using a particular in-game map orientation (as shown in the provided savefile)

3. Moving in other directions (west, east and south) does not elicit the issue.

Temporary Solutions:-

1. Disable function replacements in this game, which will result in the loss of certain other graphical functionality. (e.g. transparent status menu and savedata screenshot captures).

2. Alternatively, one of the 2 Read Framebuffers to Memory modes can be used to re-attain the lost graphical functionality (when FR's disabled) at heavily reduced performance. The arrow doesn't twitch when using those modes.

**Comment by unknownbrackets** [comment]
Well, we've left them all disabled for a while.  There are still potential gains in function replacements, but they can be tricky and dangerous.  I guess I'll close this for now.

-[Unknown]
