### ISSUE TITLE
Remaining issues with splines/bezier curves graphics glitches

### ISSUE THREAD

**Issue by thedax** [hrydgard/ppsspp#6659]
Let's use this as a meta-issue to collect games that still have problems with bad splines/beziers.

~~Kenka Banchou Bros.: https://github.com/hrydgard/ppsspp/issues/3548 (incorrect graphics)~~
~~Final Fantasy IV: https://github.com/hrydgard/ppsspp/issues/4132, https://github.com/hrydgard/ppsspp/issues/4234 (incorrect graphics, missing graphics when HQ or medium is picked)~~
Pursuit Force - Extreme Justice: https://github.com/hrydgard/ppsspp/issues/4888 (crashes)

If you know of others, please comment.

**Comment by unknownbrackets** [comment]
I think these are working pretty darn well now, except possibly performance.

There's only two remaining issues I know of (#4888 and #7111), and I don't think they're very related.  Based on that, I don't think we need a meta issue anymore, so I'm going to close this.

But, if I'm missing some bezier/spline issues or you disagree, feel free to reopen.

-[Unknown]
