### ISSUE TITLE
Phantom Kingdom Portable (NPJH50451) black screen on boot with Function Replacements enabled

### ISSUE THREAD

**Issue by Kalanyr** [hrydgard/ppsspp#6665]
First responsible commit (by bisection):
https://github.com/hrydgard/ppsspp/commit/a7b9ce205b6c43b52c71ebaf95f9bf599b4ccc50

Last unaffected commit is: https://github.com/hrydgard/ppsspp/commit/986d54039c450faf8945c06ab1527b88db979cd7

The cause is actually FuncReplacement so https://github.com/hrydgard/ppsspp/commit/a7b9ce205b6c43b52c71ebaf95f9bf599b4ccc50
is only "responsible" because it's the first build where FuncReplacement is enabled by default.

Reproduction Method: 
1) Boot Phantom Kingdom Portable with FuncReplacement enabled. 

Temporary Workarounds:
The issue is with FuncReplacement though, so even the latest build works if FunctionReplacement is set to False in ppsspp.ini.

**Comment by hrydgard** [comment]
@unknownbrackets well, we can differentiate different memset implementations with different estimates as they will have different hashes..  like my memcpy_jak

**Comment by daniel229** [comment]
These problematic games are using the same memcpy and memset as Jak and Daxter

**Comment by unknownbrackets** [comment]
Does this still happen now with the latest time estimate in those funcs, then?  It should match non-replacements.

-[Unknown]

**Comment by daniel229** [comment]
No more black screen at start up with the latest build.
