### ISSUE TITLE
Urakata Hakuouki hangs on certain chapter

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#6672]
after selecting this option.always hangs there.
![01](https://cloud.githubusercontent.com/assets/3481559/3788169/f8cd800e-1a55-11e4-9f08-71ed2b26028a.jpg)

debug log (rename jpg to rar)
![ppsspplog](https://cloud.githubusercontent.com/assets/3481559/3788171/009d0d90-1a56-11e4-9740-8249a1298eb2.jpg)

savedata(rename jpg to rar), the second slot,after loading press O button then select the second option.
![uljm06281playdata01](https://cloud.githubusercontent.com/assets/3481559/3788158/953cb24e-1a55-11e4-844b-2a715e6aa859.jpg)

**Comment by unknownbrackets** [comment]
How long after the video is this?  Or do you never see the video?

SAS is finishing, so it's not waiting on that.  It finishes playing some atrac, hopefully that went correctly... is it no longer playing any audio at this point?

It seems like it's done loading files, maybe.  FS stuff keeps waking up but not doing anything.

Not seeing any obvious cause, hmm...

-[Unknown]

**Comment by daniel229** [comment]
Only the intro video there,looks fine.When Pressing O button,there is a a sound effect,and then nothing.

**Comment by daniel229** [comment]
fixed by https://github.com/hrydgard/ppsspp/pull/8741

**Comment by unknownbrackets** [comment]
Woah.  @hrydgard maybe there's some value in getting the LO register correct in jit after all?

-[Unknown]

**Comment by hrydgard** [comment]
Sure seems so!
