### ISSUE TITLE
Adjust to non-60-fps devices by slowing down or speeding up audio accordingly

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#6677]
Quite a few Android devices have non-60hz framerates like 58hz, and these will get constant audio glitches if played at zero frameskip because we will then not generate enough audio samples. As it's possible to query for the framerate, we could simply take the ratio of framerate/60 and resample the output audio to 44100*that frequency.

We should also add such audio resampling for another reason - many Android devices require a samplerate of 48000hz in order to hit the "low latency path" in the audio driver.

**Comment by unknownbrackets** [comment]
Just noting, we now have resampling to the device rate, though this is not yet implemented.

-[Unknown]

**Comment by hrydgard** [comment]
Ah yes, this should be easy now. Will do soon, after I've messed around with WASAPI. My Nexus S really needs this.

**Comment by hrydgard** [comment]
Now done and helps a lot on the Nexus S!

**Comment by psennermann** [comment]
On my tablet I cannot hear any real differences: with the 60 fps games the music is still a bit crackling and the fps still show 58/60 (96,5%)...maybe my tablet is already too close to 60 hz to perceive some difference?

**Comment by hrydgard** [comment]
Is your tablet natively 58fps? Check in System Information in System/Developer Tools in settings, does it say 58 or 60 hz as refresh rate? We simply trust the value Android gives us, we don't try to measure it. The Nexus S correctly reports 55.7 FPS so we adjust to that.

**Comment by Bigpet** [comment]
@psennermann if you go to Settings->System->Developer Tools->System Information and then scroll down to see the refresh rate, what is the value of that on your tablet?

**Comment by psennermann** [comment]
In System/Developer Tools/System information there's written that the refresh rate is 57.790 hz

**Comment by hrydgard** [comment]
OK, then you should see some improvement... strange :/

**Comment by psennermann** [comment]
Must be game related, now I've tried some other games and although it's not perfect there's definitely some improvement.
Nice work

**Comment by twinaphex** [comment]
Its broken to rely on the SDK-provided value.

We already ran into this years ago. You will have to measure the refresh rate of the screen yourself if you want any reliable results.

**Comment by hrydgard** [comment]
@twinaphex ugh. Could try to time the splash screen I guess.. Or just make it adjustable, bleh.
