### ISSUE TITLE
Missing some languages in SDL version (should use system fonts)

### ISSUE THREAD

**Issue by sergiobenrocha2** [hrydgard/ppsspp#6681]
These languages have no entry in the SDL version:

ar_AE = "العربية"
fa_IR = "فارسی"  (appears in Qt version)
he_IL = "עברית"  --> maybe this is he_IL_invert ?

and in the sdl window, appears ????? After Español (América Latina). Maybe this ????? is fa_IR = "فارسی" ?

**Comment by unknownbrackets** [comment]
Going to close this as a duplicate of #9958.

-[Unknown]
