### ISSUE TITLE
Pangya Fantasy Golf (ULUS10438):- Non-responsive (or crashes) when pressing the X button at the Success screen after completing a License event since 0.9.6-724-gecdffab

### ISSUE THREAD

**Issue by solarmystic** [hrydgard/ppsspp#6682]
(Possibly related to https://github.com/hrydgard/ppsspp/issues/6057)

Issue is as stated in the title. First responsible commit found via bisecting is https://github.com/hrydgard/ppsspp/commit/ecdffab by @unknownbrackets 

![capture](https://cloud.githubusercontent.com/assets/4345150/3791774/9efa96a8-1b53-11e4-85c7-930ace70877b.PNG)

Last unaffected commit is 0.9.6-723-g4cec228 https://github.com/hrydgard/ppsspp/commit/4cec228 by @unknownbrackets 

Savedata for issue reproduction:- 
![ulus10438datc00](https://cloud.githubusercontent.com/assets/4345150/3791776/d80adcb4-1b53-11e4-8474-f3c6af5197af.jpg)
(rename jpg to 7z and unzip using 7zip)

Issue reproduction:-

a. Start the game using any build from 0.9.6-724-gecdffab onwards with default settings.

b. Load the provided savefile.

c. Head to Pangya Tour Mode, then License, followed by Blue Lagoon and finally Chip-in.

d. Playthrough the short challenge, and when the Results (Success) screen comes up, try pressing the X button.

![capture](https://cloud.githubusercontent.com/assets/4345150/3791818/5b76da2a-1b55-11e4-9843-dabea226a656.JPG)

e. One of two things will happen; you'll either hear the confirmation sound but the game will refuse to proceed onwards (spamming the X button will just produce the ding sound repeatedly but nothing else will happen), or the game (and PPSSPP) will just crash.

A proper debug logfile of the issue could not be obtained; the game/ppsspp would hang with a black screen when attempting to load a save file in order to reproduce the issue when Debug Logging to a file is active, which is probably another issue in itself. 

Here's what I managed to get until then:-
![ppsspplog pangya](https://cloud.githubusercontent.com/assets/4345150/3791841/c437f3c2-1b56-11e4-8698-90ecd596fa75.jpg)
(rename jpg to 7z and unzip using 7zip)

The stacktrace obtained from the instances when the game/ppsspp crashed was also rather useless and only pointed to the disassembly.

Caveat:-
1. Happens even when Fast Memory is disabled.

Thanks to Nightquaker and the others in the ppsspp.org forums for the initial discovery of the issue.

**Comment by rogerrr** [comment]
I have the same problem in PPSSPP for android.

**Comment by Saramagrean** [comment]
Temporary fix, After start game goto "Options" before play the other mode, Game is not crash or stuck when press "X" (Work on both Android/Windows)

Test clip use PPSSPP v1.6.3 latest build. 😉
https://youtu.be/91-tkHgGKMU

**Comment by unknownbrackets** [comment]
Has this improved? Some other Pangya issues have been resolved recently.

-[Unknown]

**Comment by Saramagrean** [comment]
This problem still exist.

**Comment by Saramagrean** [comment]
Logcat. (v1.9.3-500-ge14bf3bcc)
https://drive.google.com/open?id=1bmBeODmvLNWdzEgJBsXKDU1a896Fp5TN

**Comment by Saramagrean** [comment]
Can confirm it fixed by https://github.com/hrydgard/ppsspp/pull/12718 👍

**Comment by hrydgard** [comment]
Thanks for reporting!
