### ISSUE TITLE
Can't load save states while ppsspp freeze

### ISSUE THREAD

**Issue by vsub** [hrydgard/ppsspp#6683]
If you pause the emulation,load a save state for example and then resume the emulation,then it works.

Hack Link englich patched v0.2(pressing square in the characters status screens or in the mission result screen pressing square makes ppsspp to freeze)

Bleach Soul Carnival 2 - start new game and when you can actually play(move Ichigo),create a save state and press the pause button.This will make the game to freeze because of a bug and from then on,you can't load save sates unless you pause=>resume the emulation or stop it and run the game again(ppsspp will auto execute the last command executed before stopping the emulation)

You can't also access the pause menus(Esc)...it happens on any rev(including the latest)

There are other games too but I can't remember right now

**Comment by unknownbrackets** [comment]
I'm going to close this.  If you have "Ignore Illegal Reads/Writes", it won't drop to the debugger.  The debugging behavior is intentional, as mentioned above.

-[Unknown]
