### ISSUE TITLE
Simpson the video game (white Textures, iOS/Android)

### ISSUE THREAD

**Issue by brujo5** [hrydgard/ppsspp#6697]
Here screenshots from iPhone 5S.build 0.9.9-36

Bufered rendering
![image](https://cloud.githubusercontent.com/assets/4172898/3834583/077e4006-1db3-11e4-8a56-43276aded51e.jpg)

Read to menory cpu/gpu
![image](https://cloud.githubusercontent.com/assets/4172898/3834507/3c6e5342-1db2-11e4-840a-6e2563fc838e.jpg)

No bufered rendering
![image](https://cloud.githubusercontent.com/assets/4172898/3834510/4d3bc998-1db2-11e4-81f1-8a70a664e062.jpg)

**Comment by brujo5** [comment]
@unknownbrackets 
@hrydgard 

Fixed in android 7 nougat

Many games with texture bug fixed with GLES 3.2 + VULKAN
![screenshot_20170330-121030](https://cloud.githubusercontent.com/assets/4172898/24521844/c2157966-154a-11e7-819d-dd007f497812.png)

This bug still present in iOS. I think will be fixed when Apple add ES3.2 support.

**Comment by hrydgard** [comment]
Well, there's still a possibility that we could work around whatever was breaking it on these older devices. However, since it works with better drivers/hardware, not sure anyone will bother before most of the older devices have disappeared...

**Comment by iOS4all** [comment]
Me too I have graphic issues on my iPad Air 2

![img_0080](https://cloud.githubusercontent.com/assets/24762554/24531623/f95bc470-15c2-11e7-9ea2-ad978193c1c5.JPG)

**Comment by DarkLegend481** [comment]
@iOS4all Wow! Now, we can make a SIMPSONS.EXE game using your buggy Homer model... Kkkkkkkk

**Comment by unknownbrackets** [comment]
I wonder what in GLES 3.2 fixed this.  Looking at this list:

http://stackoverflow.com/questions/33135007/what-extensions-became-part-of-the-core-in-opengl-es-3-2

I suppose the thing we use is copy image, but I think that's only an optimization?

-[Unknown]

**Comment by brujo5** [comment]
I'm wonder with GLES 3.2 

Also fixed the outline character in dbz tag vs

"buffer _storage" this simple extensions cause massive speed up in dolphin emu.

Idk if ppsspp can use this?

**Comment by hrydgard** [comment]
buffer_storage could be used for vertex upload yes, and would probably help noticably with performance.

Though are there a lot of devices that support buffer_storage but not Vulkan? If not, it might make more sense to work on Vulkan instead.

**Comment by hrydgard** [comment]
@unknownbrackets , it's not unlikely that the newer drivers are simply less buggy. I can't think of any obvious one either.

**Comment by DarkLegend481** [comment]
I played on my mom's PC... Runs great.

**Comment by DarkLegend481** [comment]
Using the default settings

**Comment by DarkLegend481** [comment]
Using 1.4

**Comment by hrydgard** [comment]
Not sure it's worth supporting all these buggy old drivers.. The game certainly works on good drivers.

**Comment by brujo5** [comment]
Yeap game work great with opengl 3.2
