### ISSUE TITLE
Shin Megami Tensei: Persona 3 Portable (issue on 11/7)

### ISSUE THREAD

**Issue by milo-sama** [hrydgard/ppsspp#6698]
I am on android and using version 0.9.9-68-g404766c.

I was playing Persona 3 Portable using Female MC until the part where I got a new transfer student (Ryoji). Then after I finished the talk scene, everything went black but the music still can be heard. 

Any one can advice?

or maybe provide save file to skip the problem date? 

Thanks in advance.

Same case as here:-
http://forums.ppsspp.org/showthread.php?tid=1059&page=31

**Comment by unknownbrackets** [comment]
Savestates save bugs.  Can you reproduce this with a regular save?  And without using cheats?

-[Unknown]

**Comment by unknownbrackets** [comment]
No feedback, so we can't know if it's still happening.  I'm closing for now, we can reopen if there's more info.

-[Unknown]
