### ISSUE TITLE
Final Fantasy Tactics: War of the Lions & Ad Hoc Play

### ISSUE THREAD

**Issue by JoeOsborn** [hrydgard/ppsspp#6708]
Please replace this title with a better one!

I've been doing some investigation of why FFT:WOTL is stuck at the host/join menu for ad hoc play. The proximal cause seemed to be that the joining client sent the wrong group ID to the ad hoc server, as witnessed by this log (10.0.1.12 is the hosting player, and 127.0.0.1 is the joining player):

```
New Connection from 10.0.1.12.
PPSSPP (MAC: 9D:99:FB:C8:BB:40 - IP: 10.0.1.12) started playing ULUS10297.
PPSSPP (MAC: 9D:99:FB:C8:BB:40 - IP: 10.0.1.12) joined ULUS10297 group c8bb40cb.
New Connection from 127.0.0.1.
PPSSPP (MAC: AB:C3:B3:8F:BF:D7 - IP: 127.0.0.1) started playing ULUS10297.
PPSSPP (MAC: AB:C3:B3:8F:BF:D7 - IP: 127.0.0.1) requested information on 1 ULUS10297 groups.
PPSSPP (MAC: AB:C3:B3:8F:BF:D7 - IP: 127.0.0.1) attempted to join invalid ULUS10297 group 40cb????.
PPSSPP (MAC: AB:C3:B3:8F:BF:D7 - IP: 127.0.0.1) stopped playing ULUS10297.
PPSSPP (MAC: 9D:99:FB:C8:BB:40 - IP: 10.0.1.12) left ULUS10297 group c8bb40cb.
PPSSPP (MAC: 9D:99:FB:C8:BB:40 - IP: 10.0.1.12) stopped playing ULUS10297.
```

Note the "attempted to join invalid group" shows a group name which is offset to the left by four bytes. Indeed, in `sceNetAdhocctlJoin`, I placed some logging to determine whether the joining client was sending the wrong type of packet or something; as it turns out, interpreting the `scanInfoAddr` argument as a `SceNetAdhocctlScanInfo` immediately places the `group_name` four bytes later than it should be. So, either the `SceNetAdhocctlScanInfo` structure is four bytes smaller in memory on the PSP than expected, or the address being passed to that function was four bytes ahead of where it should have been.

I don't know where the PSP side of the world _gets_ the address that it passes to `sceNetAdhocctlJoin`, but I would think that is the most suspicious part of the story. I doubt it's a bug in the game itself (since I've played its ad hoc mode on real PSPs with other real PSPs), and the ad hoc server seems not to be implicated.

As a side note, manually decrementing that address by four bytes does align the group name properly, but then the emulator spins in these three calls until the player disconnects:

```
46:41:953 psx_main     I[NET]: HLE/sceNetAdhoc.cpp:2624 sceNetAdhocctlGetPeerList(0bff288c, 0bff28a0) at 08a1bcd4
46:41:970 psx_main     I[NET]: HLE/sceNetAdhoc.cpp:2624 sceNetAdhocctlGetPeerList(0bff320c, 00000000) at 08a1bc18
46:41:970 psx_main     I[NET]: HLE/sceNetAdhoc.cpp:2624 sceNetAdhocctlGetPeerList(0bff288c, 00000000) at 08a1bc18
```

Finally, I was concerned about a couple of places where buffers meant for/coming from packet transport are being assigned to other pointers instead of memcpy'd (lines 886, 1112, 1187). But changing those didn't seem to help anything, so I'm probably just misunderstanding your memory model. This is my first time looking at the code.

**Comment by unknownbrackets** [comment]
Has this improved?  I think the way the code uses real pointers isn't ideal, but it looks like SceNetAdhocctlScanInfoEmu was introduced to use correct offsets.  Also, there may have been a tsruct packing issue at some point.

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
