### ISSUE TITLE
Project Diva Extend crashes on PPSSPP Android version.

### ISSUE THREAD

**Issue by amirzaim** [hrydgard/ppsspp#6723]
Had been tested Project Diva Extend in PPSSP Android version and it crashes just after launching the game.

Phone model used for this issue: Asus Zenfone 4 (ASUS TOOI)

**Comment by tuankiet65** [comment]
Project Diva Extend boots flawlessly on Galaxy Note II with PPSSPP 1.0.1 from Google Play.

**Comment by thedax** [comment]
Sounds like we can close this then.

**Comment by unknownbrackets** [comment]
To be fair, I think this was reported about an Intel Android device?

-[Unknown]
