### ISSUE TITLE
Motto Nuga-Cel(ULJM05654):unable to show the map when taking actions

### ISSUE THREAD

**Issue by hys223344** [hrydgard/ppsspp#6736]
It happens on both Android and Windows. I`m using v.0.9.9-97-g78296d1.
When taking actions, it shows some strange shadows instead of the map. None of the four rendering mode helps.
![1](https://cloud.githubusercontent.com/assets/8475675/3947729/8789fe5a-2693-11e4-8884-c3d5438f2910.jpg)
![2](https://cloud.githubusercontent.com/assets/8475675/3947731/91ad09cc-2693-11e4-98c0-8caad9edd002.jpg)
When I use software rendering
![5](https://cloud.githubusercontent.com/assets/8475675/3947772/77ce4736-2694-11e4-90ea-b1c78f800524.png)
![6](https://cloud.githubusercontent.com/assets/8475675/3947773/7eefa65e-2694-11e4-810d-f3c1a0e3bfdb.png)

**Comment by unknownbrackets** [comment]
I wonder if this is a UV rotation issue.

-[Unknown]

**Comment by hrydgard** [comment]
Could very well be.

**Comment by daniel229** [comment]
No improvement from v1.0.1-857-g08b340f.

**Comment by unknownbrackets** [comment]
Did the depth changes help at all?

-[Unknown]

**Comment by hys223344** [comment]
Thanks, the map shows correctly now. But there is a strange shadow at the up left corner of the screen when viewing the map. I'm not in a good internet condition now, so I'll explain the problem later. However, since the map itself shows correctly ,maybe the issue should be closed and open a new one?

**Comment by unknownbrackets** [comment]
I agree, this is a long issue with lots of debugging information that probably isn't related to that other issue.  I'll close this but please do create the new issue for what's happening now.

-[Unknown]
