### ISSUE TITLE
Ys Seven (ULUS10551):- Screen turns completely white at random during a specific segment of the Flame Altar

### ISSUE THREAD

**Issue by solarmystic** [hrydgard/ppsspp#6740]
First actual responsible commit was almost impossible to obtain due to the highly randomized nature of the issue, but it roughly begins from 0.9.8-1000 onwards with the introduction of Simulate Block Transfers/Function Replacements.

I couldn't get it to happen on 0.9.8-900 and below. 

Short video showing the spreading white light phenomenon obtained using the latest master:-
(rename jpg to mp4)
![ys seven](https://cloud.githubusercontent.com/assets/4345150/3953934/c90733ae-26f0-11e4-8ef6-6fb7726a8c89.jpg)

Save file for reproduction (rename jpg to 7z and unzip using 7zip):-
![ulus105510004](https://cloud.githubusercontent.com/assets/4345150/3953534/e892c1ce-26ec-11e4-84e1-b318ec0bd99c.jpg)

Reproduction method (highly speculative, since it seems to be a randomly occuring phenomenon):-
(Warning:- WIll/May involve temporary whole system lockups)
1. Start any version of PPSSPP (roughly from 0.9.9 onwards) with default settings.
2. Boot up Ys Seven, and load the provided savefile.
3. If the phenomenon does not occur after a short while (which wil almost entirely be the case during the first boot of the game), close the game (Ctrl-W) and boot it up again. It may take up to 10 reboots to get the issue to appear.
4. When the phenomenon occurs, the light source from the upper middle potion of the screen will spread throughout the entire screen, turning it blinding white. It does not obscure the HUD elements, however.
5. If you then continue waiting at that screen, the emulator will eventually lock up, and the whole system with it, causing it to be completely unresponsive, which ultimately (after 30 seconds of nervous waiting and Ctrl-Alt -Deleting) pops up a "Wait for Emuthread" error, followed by an emulator crash.

Screenshot comparison:-

Problematic:-
![capture](https://cloud.githubusercontent.com/assets/4345150/3953225/8b06ab22-26e9-11e4-8a80-28b984b014f7.JPG)

Normal:-
![ys7](https://cloud.githubusercontent.com/assets/4345150/3953112/847f1c36-26e8-11e4-9314-4b4b1fcd9394.JPG)

Stacktrace from MSVC 2013:-
Could not be obtained since the issue never appears while debugging using MSVC 2013.

**Comment by unknownbrackets** [comment]
I can't remember ever being able to reproduce this.  It'd be great to know if this is still an issue in the latest git build with as up to date drivers as there are available.

-[Unknown]

**Comment by Gamemulatorer** [comment]
> First actual responsible commit was almost impossible to obtain due to the highly randomized nature of the issue, but it roughly begins from 0.9.8-1000 onwards with the introduction of Simulate Block Transfers/Function Replacements.
> 
> I couldn't get it to happen on 0.9.8-900 and below.
> 
> Short video showing the spreading white light phenomenon obtained using the latest master:-
> (rename jpg to mp4)
> ![ys seven](https://cloud.githubusercontent.com/assets/4345150/3953934/c90733ae-26f0-11e4-8ef6-6fb7726a8c89.jpg)
> 
> Save file for reproduction (rename jpg to 7z and unzip using 7zip):-
> ![ulus105510004](https://cloud.githubusercontent.com/assets/4345150/3953534/e892c1ce-26ec-11e4-84e1-b318ec0bd99c.jpg)
> 
> Reproduction method (highly speculative, since it seems to be a randomly occuring phenomenon):-
> (Warning:- WIll/May involve temporary whole system lockups)
> 
> 1. Start any version of PPSSPP (roughly from 0.9.9 onwards) with default settings.
> 2. Boot up Ys Seven, and load the provided savefile.
> 3. If the phenomenon does not occur after a short while (which wil almost entirely be the case during the first boot of the game), close the game (Ctrl-W) and boot it up again. It may take up to 10 reboots to get the issue to appear.
> 4. When the phenomenon occurs, the light source from the upper middle potion of the screen will spread throughout the entire screen, turning it blinding white. It does not obscure the HUD elements, however.
> 5. If you then continue waiting at that screen, the emulator will eventually lock up, and the whole system with it, causing it to be completely unresponsive, which ultimately (after 30 seconds of nervous waiting and Ctrl-Alt -Deleting) pops up a "Wait for Emuthread" error, followed by an emulator crash.
> 
> Screenshot comparison:-
> 
> Problematic:-
> ![capture](https://cloud.githubusercontent.com/assets/4345150/3953225/8b06ab22-26e9-11e4-8a80-28b984b014f7.JPG)
> 
> Normal:-
> ![ys7](https://cloud.githubusercontent.com/assets/4345150/3953112/847f1c36-26e8-11e4-9314-4b4b1fcd9394.JPG)
> 
> Stacktrace from MSVC 2013:-
> Could not be obtained since the issue never appears while debugging using MSVC 2013.

I can't download the savedata from your link to test If this issue still repro using latest ppsspp git build

**Comment by Gamemulatorer** [comment]
@solarmystic any mirror link for your savesdata so that I can repro this issue?

**Comment by vsub** [comment]
Shouldn't this be closed?
The last update from the op was almost 6 years ago and I clear the game multiple times already

**Comment by hrydgard** [comment]
Seems likely to have been fixed by now, I'll close it - please re-open if anyone finds a repro.

**Comment by unknownbrackets** [comment]
Here's the save data fwiw, although I think I wasn't able to reproduce.

[ULUS105510003.zip](https://github.com/hrydgard/ppsspp/files/4675232/ULUS105510003.zip)
[ULUS105510004.zip](https://github.com/hrydgard/ppsspp/files/4675236/ULUS105510004.zip)

-[Unknown]

**Comment by Gamemulatorer** [comment]
> Here's the save data fwiw, although I think I wasn't able to reproduce.
> 
> [ULUS105510003.zip](https://github.com/hrydgard/ppsspp/files/4675232/ULUS105510003.zip)
> [ULUS105510004.zip](https://github.com/hrydgard/ppsspp/files/4675236/ULUS105510004.zip)
> 
> -[Unknown]

Yes your right I can't repro this issue using your savesdata.
