### ISSUE TITLE
Pangya Fantasy Golf (ULUS10438):- Incorrect AI character behaviour/appearance during a particular match up in Story Mode since v0.9.7.2-154-gd7ba8f7

### ISSUE THREAD

**Issue by solarmystic** [hrydgard/ppsspp#6746]
(**Note**:- This is a completely seperate issue to https://github.com/hrydgard/ppsspp/issues/6682 which has a different point of origin)

First responsible commit found via bisecting is **v0.9.7.2-154-gd7ba8f7** https://github.com/hrydgard/ppsspp/commit/d7ba8f7312875cfcff725dc658bbd4732a4b6166

![pangyabisect](https://cloud.githubusercontent.com/assets/4345150/3965616/1ff7a100-2799-11e4-8a58-b3a4a686aa70.PNG)

**Video demonstration of the issue using v0.9.9.1-38-g2de6b47:-**

https://www.mediafire.com/?75752ly55rrqlq9

(Cecilia (player character) moves first, and then Bob (the AI rival) moves next. Skip to 00.14 to see the AI bit right away.)

**Save data for issue reproduction:-**

![ulus10438datc00](https://cloud.githubusercontent.com/assets/4345150/3791776/d80adcb4-1b53-11e4-8474-f3c6af5197af.jpg)

(rename jpg to 7z and unzip using 7zip)

**Issue reproduction:-**

a. Start the game using any revision from v0.9.7.2-154-gd7ba8f7 onwards with both Function Replacements and Fast Memory disabled, else the issue reprodcution will be impossible. All other settings can be left to the defaults.

(Loading up the specific matchup will crash the game and the emulator if those two options are not disabled, this is yet another seperate issue with the game and not the focus of this particular issue report.)

b. Load the provided save file.

c. Head to Story Mode, Episode 1, pick Cecilia (lady with the blonde hair) and then choose the 5th event.

d. Once you're into the match proper (skip the dialogue by hammering the Start button), just hit the ball anywhere you wish. (You will start first, press X to gain power, and X again to hit the ball)

e. When the it's the AI's turn (Bob) notice that he is semi-transparent (ghostly looking) and in a rather strange pose. The character does not visibly hit the ball, but eventually some sound effects are heard, and the ball flies off into the distance anyway. When the ball lands, it produces an incorrect out of bounds sound effect regardless of the actual ball position.

**Screenshot comparison:-**

Abnormal AI pose/behaviour/appearance

![panygabobproblem](https://cloud.githubusercontent.com/assets/4345150/3965745/7b1d020e-279a-11e4-908f-6e50d0c6f013.JPG)

Normal AI pose/behaviour/appearance

![panygabobokay](https://cloud.githubusercontent.com/assets/4345150/3965746/7dfac790-279a-11e4-83db-9c9353db0db2.JPG)

**Additional Note:-** Obtaining any form of logfile for this issue proved to be impossible; the game/emulator would lock up during a Loading screen in Logging Mode (Debug or otherwise) before the issue even occurs.

Thanks to Kordosa from the ppsspp.org forums for bringing the matter to my attention.

**Comment by unknownbrackets** [comment]
Does this still happen?

-[Unknown]

**Comment by Saramagrean** [comment]
Still the same with latest git buid.
![pangya](https://user-images.githubusercontent.com/26355472/48314302-30510180-e5fa-11e8-9b05-c6bef0d62162.jpg)

**Comment by Saramagrean** [comment]
Test with v1.9.3 latest git build 210, can comfirm this issue is fixed since v1.9.3 build 155. (Android/Windows). :)

![81988039_512658306048444_972338788602740736_n](https://user-images.githubusercontent.com/26355472/72376246-3a134f00-3740-11ea-847c-1fc856a2f458.png)
![82754532_1291779941030160_3937527726646231040_n](https://user-images.githubusercontent.com/26355472/72376258-3f709980-3740-11ea-83e4-fc27a7c5f7a4.png)

**Comment by unknownbrackets** [comment]
Reported fixed by #12509.

-[Unknown]

**Comment by solarmystic** [comment]
I've been out of the project for ages, but well done for fixing this really long standing issue with Pangya @unknownbrackets @hrydgard
