### ISSUE TITLE
ppsspp v0.9.9.1.54 can't play God Eater 2

### ISSUE THREAD

**Issue by jtliaw** [hrydgard/ppsspp#6761]
My pc system is lubuntu 14.04 , ppssppsdl v0.9.9 can play God Eater 2 but can't continuous play , one mission finish can't continus play second mission.
Now v0.9.9.1.54 can't play God Eater 2 !

**Comment by thedax** [comment]
This is a dupe of https://github.com/hrydgard/ppsspp/issues/5192, and appears to have been fixed.

Closing.
