### ISSUE TITLE
Framebuffer effects issues (Android)

### ISSUE THREAD

**Issue by 4ezahernya** [hrydgard/ppsspp#6768]
1).In Tron Legacy framebuffer effects don't clear every frame causing graphic artifacts and filling all the screen. Artifacts disappear with returning to the emulators menu.
Unbuffered render turns off all effects.

2) in several games (Sonic Rivals, JC Avatar), "disable slower effects" option makes picture overbright.
Unbuffered render gives a black screen in those (and others) games (Assassins Creed f.e.).

![screenshot_2014-08-23-14-09-37](https://cloud.githubusercontent.com/assets/8529795/4020411/a15cfb52-2ab7-11e4-8e15-f31e168662d6.jpg)

**Comment by unknownbrackets** [comment]
This is actually implemented now (FragmentTestCache), although I don't currently have a GLES2 device (or Tron) to test it with.  How does this work in the latest version?

-[Unknown]

**Comment by unknownbrackets** [comment]
We've implemented color masking, and any ideas are welcome for writing the effects in faster ways.  But short of that, it seems like this issue has run its course.

I'm going to close now.

-[Unknown]
