### ISSUE TITLE
pro yakyuu spirits 2014 missing shadows.

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#6778]
since the stencil-mask commits https://github.com/hrydgard/ppsspp/commit/eba821e676938cd1bb72971b7fb14f6cb9473b02 

![01](https://cloud.githubusercontent.com/assets/3481559/4025382/a5cd476a-2bf6-11e4-8c91-aba39a927c59.png)

before
![02](https://cloud.githubusercontent.com/assets/3481559/4025381/a5c70b2a-2bf6-11e4-9251-0121545106ad.png)

**Comment by unknownbrackets** [comment]
For 5551, >= 0x80 should mean no bit set, <= 0x7f should allow the stencil bit to be set.  It's all about the high bit.

This is fmt=1, or 5551.  So, what about this:
```c++
			if (gstate.FrameBufFormat() == GE_FORMAT_5551) {
				glstate.stencilMask.set(abits <= 0x7f ? 0xff : 0x00);
			} else {
				glstate.stencilMask.set(~abits);
			}
```

Technically, we should force the stencil bits better, and for 4444, but that gets messy...

-[Unknown]

**Comment by daniel229** [comment]
That fixes it
