### ISSUE TITLE
Musou orochi 2 special title missing background - UNIMPL sceJpegDecodeMJpegSuccessively

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#6779]
JPCSP works fine
![01](https://cloud.githubusercontent.com/assets/3481559/4025949/5275da74-2c09-11e4-9d9e-530821999e59.png)
![02](https://cloud.githubusercontent.com/assets/3481559/4025950/52789a2a-2c09-11e4-8f2e-ce63186c52a1.png)

JPCSP
![03](https://cloud.githubusercontent.com/assets/3481559/4025955/7f68dd60-2c09-11e4-9df6-b87e87bca85d.png)

**Comment by LunaMoo** [comment]
Would be nice if someone with the game checks it with the [recent PPSSPP](http://buildbot.orphis.net/ppsspp/), jpeg decoding should work fine now.

**Comment by sum2012** [comment]
![1](https://cloud.githubusercontent.com/assets/2177532/26758331/b076df8c-490d-11e7-9011-0a3273a7b73d.jpg)
Thanks @LunaMoo It work now.
Closing this issue
