### ISSUE TITLE
D3D9: Resizing window does not work with older devices

### ISSUE THREAD

**Issue by thedax** [hrydgard/ppsspp#6782]
I know it's still a WIP, but it might help to keep a list of what's still wrong with the UI (not games):
## Remaining

4) Changing the window size (whether clicking and dragging the edge, or going to Game Settings -> Window Size) results in the UI scaling incorrectly when it's larger than 1x:

![capture](https://cloud.githubusercontent.com/assets/4482745/4027497/a48fd4ec-2c2f-11e4-845b-522d6d51d558.PNG)
## Fixed

~~1) Depth/layering issue with game icons: When scrolling up or down, the icons will sit on top of the Recent/Games/Homebrew tabs (should be taken care of with https://github.com/hrydgard/native/pull/233):~~

![capture](https://cloud.githubusercontent.com/assets/4482745/4027323/d344603a-2c2c-11e4-82ad-e42b1c176f5d.PNG)

~~2) Sometimes text won't appear on folder rects:~~

![capture](https://cloud.githubusercontent.com/assets/4482745/4027329/e60dc2f6-2c2c-11e4-9c53-737300475965.PNG)

~~3) Zip/Rar icon rows are missing text completely:~~

![capture](https://cloud.githubusercontent.com/assets/4482745/4027332/fcc7c820-2c2c-11e4-871b-7b0df70b2803.PNG)

~~5) Not sure if this is just me, but it also looks like text rendering glitches slightly when changing menu tabs or screens, then it looks fine a split second later (almost like a texcache issue in games).~~

~~6) The UI "smears" icons after exiting games sometimes (seems to happen for me with FF Tactics and Tactics Ogre):~~
![capture](https://cloud.githubusercontent.com/assets/4482745/4027847/7693bfe4-2c35-11e4-95d0-e491cf9d5005.PNG)

**Comment by zackdreaver** [comment]
Does the issue i got from changing windows size is relevance with issue no.4 ?
![new picture](https://cloud.githubusercontent.com/assets/10024221/7683133/3dd812ec-fda7-11e4-981e-71f4fd9b7d3e.jpg)
Build: v1.0.1-478-g5b75d5d-windows-x86
Backend: d3d

**Comment by unknownbrackets** [comment]
Yes, basically, the way we're doing it now only works on certain systems (I suspect newer ones, not sure what the line is.)  The documentation states we're required to do something more complicated, which afaict your system is requiring.

However, if you resize the window and restart PPSSPP, it may work.

-[Unknown]

**Comment by ppmeis** [comment]
I tested latest build and I can resize the screen without problem under D3D9.

**Comment by unknownbrackets** [comment]
I think this might all be fixed now, but I'm not sure about older devices.

Is this still an issue?

-[Unknown]

**Comment by ppmeis** [comment]
Tested in latest build. Resizing works fine.

**Comment by thedax** [comment]
I don't have the old hardware in question anymore, so I'm unable to test.
