### ISSUE TITLE
Tomb Raider Anniversary graphics regression (post-0.9.9.1)

### ISSUE THREAD

**Issue by twinaphex** [hrydgard/ppsspp#6789]
This seems to have happened post-9.9.1, and it can be reproduced by going to the level 2 stage. It didnt' happen before some of the blending changes that were pushed these past few days.

If you jump in the water, you'll notice that while underwater it will show some screen residue from the framebuffer before you submerged.

Here are some screenshots showing this graphics regression -

http://imgur.com/qz8RiLd,JxKuFKb,4jhqnWM,QMICQDe#3

This is with rendering mode set to Buffered rendering.

**Comment by unknownbrackets** [comment]
Does this happen at 1x PSP render resolution?

-[Unknown]

**Comment by unknownbrackets** [comment]
Would be great to know more information about the regression range (first broken, first working), and how this looks in the latest version.  Also, 1x may affect it, which would help us narrow down the bug.

-[Unknown]

**Comment by ppmeis** [comment]
Tested in latest build. It works fine for me:
![image](https://cloud.githubusercontent.com/assets/4381277/11627041/ea7d0d1a-9ce7-11e5-8ec8-8f1d060e587c.png)

![image](https://cloud.githubusercontent.com/assets/4381277/11627052/0a726fac-9ce8-11e5-8e25-2a669e811b8b.png)
