### ISSUE TITLE
Prince of Persia Revelations [US] cwcheats game break

### ISSUE THREAD

**Issue by nfjorgebueno** [hrydgard/ppsspp#6798]
_S ULUS-10063
_G Prince of Persia Revelations [US]
_C0 Infinite Sands
_L 0x00C18224 0x00000006
_L 0x00C24DF4 0x00000006
_C0 Inifinite Health
_L 00C24524 0x000000C8
_C0 Real Infinite Time
_L 0x0058BCE2 0x00000087
_C0 Infinite Sands
_L 0x00C18224 0x00000006
_C0 Real Infinite Health
_L 0x00C24554 0x000000C8
The game normally start and I can fully play it but after a while ,black screen, lack of textures. instant game over,neither operates cwcheats,I had no problems in Prince of Persia: Rival Swords, and Prince of persia the forgotten sands, both fully playable with cwcheats

**Comment by nfjorgebueno** [comment]
because he says that nobody can help me, the game works perfectly with the correct codes, only death has no solution

**Comment by nfjorgebueno** [comment]
prince of persia revelations finish with the correct codes, thanks to friends of codemasters Project

**Comment by drag0nD** [comment]
How to put these codes please learn me or make video

**Comment by bckhhkcouufou-rgb** [comment]
> _S ULUS-10063 _G Prince of Persia Revelations [US] _C0 Infinite Sands _L 0x00C18224 0x00000006 _L 0x00C24DF4 0x00000006 _C0 Inifinite Health _L 00C24524 0x000000C8 _C0 Real Infinite Time _L 0x0058BCE2 0x00000087 _C0 Infinite Sands _L 0x00C18224 0x00000006 _C0 Real Infinite Health _L 0x00C24554 0x000000C8 

The game normally start and I can fully play it but after a while ,black screen, lack of textures. instant game over,neither operates cwcheats,I had no problems in Prince of Persia: Rival Swords, and Prince of persia the forgotten sands, both fully playable with cwcheats

#
