### ISSUE TITLE
Street Fighter Alfa 3 MAX sound stuttering

### ISSUE THREAD

**Issue by lucasgta95** [hrydgard/ppsspp#6799]
Device: Xperia SP
Specs:
CPU: 
Snapdragon Dual Core 1.7 Ghz
1GB RAM
GPU Adreno 320
PPSSPP v0.9.9.1-145 Android

Sound stutters on all screens, like the stutters is repeating (much annoying)

**Comment by unknownbrackets** [comment]
This sounds like it might just be performance.  If you're not getting 100% speed, you'll get bad sound.  Turning on frameskip may help.

I'm closing this based on that.  If this is still an issue, please respond with more detail.

-[Unknown]
