### ISSUE TITLE
God Eater 2 v1.4 needs to constantly pause and unpause

### ISSUE THREAD

**Issue by zachary822** [hrydgard/ppsspp#6806]
I am running v9.9.1-155 on wine-1.7.24 on my early-2011 13" macbook pro (Mac OS X 10.9.4) with Intel HD 3000 graphics.
The emulator gets stuck at random battle scenes, and I have to pause and unpause to continue where the log says "I[IO]: HLE\sceIo.cpp:845 stdout: cassert : src/god_g000_Field/status_pc.c 3617 :  : (N/A)
E[CPU]: Mips\MIPSInt.cpp:186 BREAK!"

ppsspp.ini as followed

[General]
FirstRun = False
Enable Logging = True
AutoLoadLast = False
AutoRun = True
Browse = False
ConfirmOnQuit = False
IgnoreBadMemAccess = False
CurrentDirectory = 
ShowDebuggerOnLoad = False
ReportHost = report.ppsspp.org
Recent = 
AutoSaveSymbolMap = False
TopMost = False
WindowX = 264
WindowY = 172
Language = en_US
NumWorkerThreads = 8
MaxRecent = 30
EnableCheats = False
ScreenshotsAsPNG = True
StateSlot = 0
GridView1 = True
GridView2 = True
GridView3 = True
ReportingHost = report.ppsspp.org
WindowWidth = 1448
WindowHeight = 862
PauseOnLostFocus = True
RewindFlipFrequency = 0
EnableAutoLoad = False
RunCount = 487
CheckForNewVersion = False
DumpDecryptedEboots = False
ForceLagSync = False
PauseWhenMinimized = False
[CPU]
Jit = True
SeparateCPUThread = False
SeparateIOThread = False
FastMemory = False
CPUSpeed = 0
AtomicAudioLocks = False
FastMemoryAccess = False
FuncReplacements = True
SetRoundingMode = True
[Graphics]
ShowFPSCounter = 3
ResolutionScale = 2
RenderingMode = 1
SoftwareRendering = False
HardwareTransform = True
TextureFiltering = 1
SSAA = False
FrameSkip = 1
FrameRate = 0
ForceMaxEmulatedFPS = 0
AnisotropyLevel = 0
VertexCache = True
FullScreen = False
FullScreenOnLaunch = False
StretchToDisplay = False
TrueColor = True
MipMap = False
TexScalingLevel = 0
TexScalingType = 0
TexDeposterize = False
VSyncInterval = False
DisableStencilTest = False
AlwaysDepthWrite = False
InternalResolution = 0
FrameSkipUnthrottle = True
LowQualitySplineBezier = False
FXAA = False
PostShader = Natural
VertexDecoderJit = True
SoftwareSkinning = True
TimerHack = False
PartialStretch = False
TextureBackoffCache = False
TextureSecondaryCache = False
SmallDisplay = False
AutoFrameSkip = True
ImmersiveMode = False
AlphaMaskHack = False
SplineBezierQuality = 2
BlockTransferGPU = False
MemBlockTransferGPU = True
DisableSlowFramebufEffects = False
AndroidHwScale = 1
BufferFiltering = 1
GPUBackend = 0
[Sound]
Enable = False
EnableAtrac3plus = True
VolumeBGM = 4
VolumeSFX = 4
LowLatency = False
AudioLatency = 1
SoundSpeedHack = False
[Control]
ShowStick = True
ShowTouchControls = False
AccelerometerToAnalogHoriz = False
TouchButtonOpacity = 65
ButtonScale = 1.150000
ShowAnalogStick = True
TiltSensitivity = 100
HapticFeedback = True
ShowTouchCross = True
ShowTouchCircle = True
ShowTouchSquare = True
ShowTouchTriangle = True
ShowTouchStart = True
ShowTouchSelect = True
ShowTouchLTrigger = True
ShowTouchRTrigger = True
ShowTouchUnthrottle = True
ShowTouchDpad = True
ActionButtonSpacing = 57
ActionButtonCenterX = 0.900000
ActionButtonCenterY = 0.838057
DPadX = 0.119167
DPadY = 0.611336
StartKeyX = 0.609167
StartKeyY = 0.906883
SelectKeyX = 0.500000
SelectKeyY = 0.906883
UnthrottleKeyX = 0.390000
UnthrottleKeyY = 0.906883
LKeyX = 0.066667
LKeyY = 0.060729
RKeyX = 0.942500
RKeyY = 0.060729
AnalogStickX = 0.119167
AnalogStickY = 0.875843
DisableDpadDiagonals = False
ActionButtonScale = 1.150000
ActionButtonSpacing2 = 1.000000
DPadScale = 1.150000
DPadSpacing = 1.000000
StartKeyScale = 1.150000
SelectKeyScale = 1.150000
UnthrottleKeyScale = 1.150000
LKeyScale = 1.150000
RKeyScale = 1.150000
AnalogStickScale = 1.150000
TouchButtonStyle = 1
IgnoreWindowsKey = False
ShowTouchPause = False
AnalogLimiterDeadzone = 0.600000
[SystemParam]
NickName = Zachary
Language = 1
TimeFormat = 2
DateFormat = 1
TimeZone = 0
DayLightSavings = False
ButtonPreference = 1
LockParentalLevel = 0
WlanAdhocChannel = 0
WlanPowerSave = False
EncryptSave = True
BypassOSKWithKeyboard = False
PSPModel = 1
proAdhocServer = localhost
MacAddress = 8c:58:59:16:cf:40
PSPFirmwareVersion = 150
[Debugger]
DisasmWindowX = 500
DisasmWindowY = 200
DisasmWindowW = 773
DisasmWindowH = 698
ConsoleWindowX = 0
ConsoleWindowY = 22
FontWidth = 8
FontHeight = 12
DisplayStatusBar = True
ShowDeveloperMenu = False
GEWindowX = 177
GEWindowY = 242
GEWindowW = 768
GEWindowH = 684
ShowBottomTabTitles = True
SkipDeadbeefFilling = False
FuncHashMap = False
[SpeedHacks]
PrescaleUV = False
DisableAlphaTest = False
[Upgrade]
UpgradeMessage = 
UpgradeVersion = 0.9.6
DismissedVersion = 
[Network]
EnableWlan = False
[PinnedPaths]
[JIT]

![screen shot 2014-08-30 at 11 33 00](https://cloud.githubusercontent.com/assets/4814373/4098031/c1d0136c-2ff6-11e4-857c-37fbfe5cff0a.png)
![screen shot 2014-08-30 at 11 33 08](https://cloud.githubusercontent.com/assets/4814373/4098032/c1d500fc-2ff6-11e4-9bc5-5923ab1b120e.png)

**Comment by unknownbrackets** [comment]
Based on reporting, it seems like this could no longer be happening.  Does it still happen when you have "Ignore Illegal Reads/Writes" disabled?

That setting is technically a hack, and makes the emulator slower.  Anything that requires that setting is simply a bug.

-[Unknown]

**Comment by benderscruffy** [comment]
please close  as it hasn't been updated in years
