### ISSUE TITLE
Kenka Banchou 4 crash in-game

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#6813]
![1](https://cloud.githubusercontent.com/assets/2177532/4100873/ca3f7398-30ba-11e4-937e-8bafd08f4965.jpg)
then
![2](https://cloud.githubusercontent.com/assets/2177532/4100874/d0592396-30ba-11e4-91bf-e48961ed339f.jpg)
go inside crash
I think the problem is
MyThread-Mai E[G3D]: GLES\VertexDecoder.cpp:788 Vertices without position found

info log:
https://drive.google.com/file/d/0B3OaSdeV0L8kcS1FUm1LRjIzVUE/edit?usp=sharing
debug log:
https://drive.google.com/file/d/0B3OaSdeV0L8kLUpmaUxwUWxVSTA/edit?usp=sharing
disassumble
![3](https://cloud.githubusercontent.com/assets/2177532/4100876/f81a8c9e-30ba-11e4-8e43-96dd18ef9473.png)

**Comment by sum2012** [comment]
Update debug log  v0.9.9.1-1574-gfeeb3c9
https://drive.google.com/file/d/0B3OaSdeV0L8kRkJJbk5Ja2FBQkU/view?usp=sharing

**Comment by adimetro00** [comment]
i have the same problem too! only it crashes after the following cutscene after entering the door the second time. can anyone fix it? i want to play this game so bad!

**Comment by sum2012** [comment]
Update the log to v1.2.2-907-g2d838f7-windows-amd64
https://gist.github.com/sum2012/bb6c228aa8000739338807212d5513cd
