### ISSUE TITLE
Monster Kingdom Jewel Summoner loose voice acting at certain point

### ISSUE THREAD

**Issue by vsub** [hrydgard/ppsspp#6820]
I cleared the game(USA version)while using 0.9.8-588 but it looks like the problem still exist on the latest beta.
Every time someone say something(in cut scene for example),something like this appear in the console

ATRAC3 play  W[ME]: HLE\sceAtrac.cpp:1205 This is an atrac3+ mono audio
ATRAC3 play  E[ME]: HLE\sceAtrac.cpp:955 sceAtracGetSecondBufferInfo(0, 0bfb7a78, 0bfb7a7c)
galArchiveWo W[IO]: HLE\sceIo.cpp:1826 SCE_KERNEL_ERROR_NOASYNC = sceIoWaitAsyncCB(4, 0bfbf900)
galArchiveWo W[IO]: HLE\sceIo.cpp:1826 SCE_KERNEL_ERROR_NOASYNC = sceIoWaitAsyncCB(4, 0bfbf8f0)
galArchiveWo W[IO]: HLE\sceIo.cpp:1826 SCE_KERNEL_ERROR_NOASYNC = sceIoWaitAsyncCB(4, 0bfbf900)
galArchiveWo W[IO]: HLE\sceIo.cpp:1826 SCE_KERNEL_ERROR_NOASYNC = sceIoWaitAsyncCB(4, 0bfbf8f0)
galArchiveWo W[IO]: HLE\sceIo.cpp:1826 SCE_KERNEL_ERROR_NOASYNC = sceIoWaitAsyncCB(4, 0bfbf900)
galArchiveWo W[IO]: HLE\sceIo.cpp:1826 SCE_KERNEL_ERROR_NOASYNC = sceIoWaitAsyncCB(4, 0bfbf8f0)
galArchiveWo W[IO]: HLE\sceIo.cpp:1826 SCE_KERNEL_ERROR_NOASYNC = sceIoWaitAsyncCB(4, 0bfbf900)
galArchiveWo W[IO]: HLE\sceIo.cpp:1826 SCE_KERNEL_ERROR_NOASYNC = sceIoWaitAsyncCB(4, 0bfbf8f0)
galArchiveWo W[IO]: HLE\sceIo.cpp:1826 SCE_KERNEL_ERROR_NOASYNC = sceIoWaitAsyncCB(4, 0bfbf900)
galArchiveWo W[IO]: HLE\sceIo.cpp:1826 SCE_KERNEL_ERROR_NOASYNC = sceIoWaitAsyncCB(4, 0bfbf8f0)

This is the save
http://www34.zippyshare.com/v/52247630/file.htm
1.Go to Saloon
2.Talk to Skipper and choose yes
3.After couple of cut scenes you will hear a monster cry

After that,voice acting will not work anywhere until you reach the next save point=>save=>restart the game=>load the save.

**Comment by daniel229** [comment]
Fixed in https://github.com/hrydgard/ppsspp/pull/6976
