### ISSUE TITLE
Ben 10 alien force: Vilgax attacks (ARM, both Android & iOS) Crash!

### ISSUE THREAD

**Issue by marioalex96** [hrydgard/ppsspp#6827]
When i try to Play its Crash on the Save/load screen !!!
Please help!

**Comment by unknownbrackets** [comment]
Does the Android crash still happen?  And, does it happen with jit disabled?

-[Unknown]

**Comment by sum2012** [comment]
v1.0-97-gf2cde73 in Android crash fixed.
Need @brujo5 test on iphone 5S

**Comment by brujo5** [comment]
Fixed on iOS to.
