### ISSUE TITLE
Persona 3 Portable (iOS 7.1.2, iPad Mini 1st Gen)

### ISSUE THREAD

**Issue by Alcatraz0890** [hrydgard/ppsspp#6829]
After playing this game for a period of time on the latest working build on the cydia.ppsspp.org repo The audio starts to stutter and will not go away. I have messed with every single setting and still the problem eventually occurs. This did not occur on the last build before that repo was brought back. I believe it is a glitch caused by frame rate drops that occur at specific areas in the game on this device. When it is loading areas and during battle sequences the frame rate drops a bit and the audio stutters then. After this occurs several times the audio then becomes permanently stuck in the low frame rate state while the rest of the game is still at stable 30 FPS during this.

**Comment by hrydgard** [comment]
Does this still happen?

**Comment by unknownbrackets** [comment]
No response in a long time.  Closing this since we've made various improvements in the year since the issue was created.

If it's still happening, please comment with more details (such as savedata or a savestate, possibly) and we'll reopen.

-[Unknown]
