### ISSUE TITLE
Error in Mortal Kombat Unchained Game - Konquest Mode

### ISSUE THREAD

**Issue by Prick1** [hrydgard/ppsspp#6845]
The game freeze in the cutscene after defeat Scorpion in final matches

![error](https://cloud.githubusercontent.com/assets/8678263/4175323/c73bf48e-35cc-11e4-9908-33b36627f6f5.PNG)

![error2](https://cloud.githubusercontent.com/assets/8678263/4175325/d804cb60-35cc-11e4-8e52-78a7df956310.PNG)

P.S.: The sound mutes moments before the error.

**Comment by daniel229** [comment]
Seems work fine in the US version after beating Scorpion.

![01](https://cloud.githubusercontent.com/assets/3481559/6268747/0bd6abe4-b88a-11e4-86dc-b4cbd393d68d.png)
![02](https://cloud.githubusercontent.com/assets/3481559/6268748/0bd6ce08-b88a-11e4-8e38-e346075e90aa.png)

**Comment by daniel229** [comment]
EU version is also good.
![03](https://cloud.githubusercontent.com/assets/3481559/6269638/79cf7856-b88f-11e4-9a90-e03ea13bb57b.png)

**Comment by thedax** [comment]
Looks like we can close this, then.
