### ISSUE TITLE
PPSSPP is ignoring "maximized" state set in the shortcut

### ISSUE THREAD

**Issue by vsub** [hrydgard/ppsspp#6893]
It's ok with
v0.9.8-1622-g8da08ea
and not with
v0.9.8-1628-gc338332

Probably related to this
https://github.com/hrydgard/ppsspp/pull/6651

**Comment by vsub** [comment]
Umm no offense @unknownbrackets but how exactly this is useful
Setting the startup mode to maximized start ppsspp in full screen and from then on if you never exit full screen(using the screen menus to alt+f4 to close ppsspp),that shortcut becomes useless.

It's like settings ppsspp to start in normal window and enabling full screen.
Why not just maximize the window if you set the shortcut to maximize the window

If we want to always go fullscreen from the shortcut,we can just use "--fullscreen"

**Comment by unknownbrackets** [comment]
I would actually argue that if someone maximized PPSSPP, we should probably switch to full screen.  Some apps do that, and it kinda makes sense.  I don't really see the utility of maximized without fake-fullscreen.

-[Unknown]
