### ISSUE TITLE
Suigetsu Portable no graphic if resolution greater than 2X

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#6894]
Gedebugger tabs seems no difference between 2X and 4X res
http://youtu.be/PwlucbotgH8

Gedebugger tabs at 4x res
![00](https://cloud.githubusercontent.com/assets/3481559/4259741/1ce17f88-3b10-11e4-8227-e76410fd26ce.png)
![01](https://cloud.githubusercontent.com/assets/3481559/4259742/1ce20ba6-3b10-11e4-9e35-174d90e3ffba.png)
![02](https://cloud.githubusercontent.com/assets/3481559/4259740/1ce12d62-3b10-11e4-86ca-23e808efdaea.png)
![03](https://cloud.githubusercontent.com/assets/3481559/4259739/1ce10436-3b10-11e4-837b-0a789d6a1462.png)
![04](https://cloud.githubusercontent.com/assets/3481559/4259743/1ceadb5a-3b10-11e4-9a2e-4b1a4b4e648a.png)

**Comment by unknownbrackets** [comment]
How is this now, e.g. in d3d9 with the scaling?  Does it work correctly there now, or is it the same as in opengl?

-[Unknown]

**Comment by daniel229** [comment]
same as OpenGL.only works in 1x 2x resolution.

**Comment by daniel229** [comment]
Fixed in https://github.com/hrydgard/ppsspp/pull/7629

**Comment by unknownbrackets** [comment]
Ah, thanks, I was trying to find this issue (I remembered there was another one), but I couldn't find the right search terms.  Glad it was the same issue.

But, is this still a problem in Direct3D 9, or is it fixed in both?

-[Unknown]

**Comment by daniel229** [comment]
Also fixed in Direct3D 9.
