### ISSUE TITLE
Touch controls can get cut off in non-buffered mode since 0.9.9.1-65 (user-reported)

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#6898]
"Look at Picture
Touch contol is strange on Non-buffered Rendering.

PPSSPP 0.9.9.1-65 is Not have Error,
but Higher is have error.

Appear Error Game-Tekken6"

![screenshot_2014-09-07-18-04-57](https://cloud.githubusercontent.com/assets/130929/4261267/b08557cc-3b66-11e4-981d-38de9a8e0d1e.png)

**Comment by hrydgard** [comment]
This now appears to work fine in Tekken, both Android and PC. Silly mistake from my side. Please comment or reopen if you see this in any more games.

**Comment by sum2012** [comment]
Great
