### ISSUE TITLE
Little busters video problems

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#6903]
1.The openning video show up when checking "Retain changed textures" or change rendering mode while playing.

2.Chinese translated video is skipped in the middle of the video.Like this https://github.com/hrydgard/ppsspp/issues/6574

The infolog of the video,no difference between the patched and the original
```
03:29:236 user_main    I[ME]: HLE\sceMpeg.cpp:412 sceMpegInit()
03:29:236 user_main    I[ME]: HLE\scePsmf.cpp:1018 scePsmfPlayerCreate(08b3f158, 08b3f14c)
03:29:253 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2178 376=sceKernelCreateThread(name=displayThread, entry=089acb74, prio=21, stacksize=2048)
03:29:253 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2178 377=sceKernelCreateThread(name=audioThread, entry=089ac0f8, prio=20, stacksize=2048)
03:29:253 user_main    W[ME]: HLE\scePsmf.cpp:1247 8192 = scePsmfPlayerGetAudioOutSize(08b3f158)
03:29:253 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2178 378=sceKernelCreateThread(name=naviThread, entry=089ad18c, prio=22, stacksize=2048)
03:29:253 user_main    I[ME]: HLE\scePsmf.cpp:1952 scePsmfPlayerConfigPlayer(08b3f158, loop, 1)
03:29:253 user_main    I[ME]: HLE\scePsmf.cpp:1960 scePsmfPlayerConfigPlayer(08b3f158, pixelType, 3)
03:29:268 user_main    I[ME]: HW\MediaEngine.cpp:85 FF: deprecated pixel format used, make sure you did set range correctly
03:29:268 user_main    I[ME]: HW\MediaEngine.cpp:85 FF: No accelerated colorspace conversion found from yuv420p to rgba.
03:29:276 user_main    I[ME]: HLE\scePsmf.cpp:1188 scePsmfPlayerSetPsmf(08b3f158, disc0:/PSP_GAME/USRDIR/X6MOVIE/OP00.pmf)
03:29:276 user_main    W[ME]: HLE\scePsmf.cpp:1341 scePsmfPlayerStart(08b3f158, 08b3f134, 0)
03:29:277 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2277 sceKernelStartThread(thread=376, argSize=4, argPtr=09fff130)
03:29:277 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2277 sceKernelStartThread(thread=377, argSize=4, argPtr=09fff134)
03:29:277 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2277 sceKernelStartThread(thread=378, argSize=4, argPtr=09fff138)
03:29:278 displayThrea I[G3D]: GLES\ShaderManager.cpp:139 Linked shader: vs 32 fs 45
03:29:278 naviThread   W[ME]: HLE\scePsmf.cpp:1634 scePsmfPlayerGetCurrentPts(08b3f158, 08b3f15c): no frame yet
03:29:278 displayThrea I[G3D]: GLES\ShaderManager.cpp:139 Linked shader: vs 35 fs 59
03:29:278 naviThread   W[ME]: HLE\scePsmf.cpp:1634 scePsmfPlayerGetCurrentPts(08b3f158, 08b3f15c): no frame yet
03:29:303 naviThread   W[ME]: HLE\scePsmf.cpp:1634 scePsmfPlayerGetCurrentPts(08b3f158, 08b3f15c): no frame yet
03:29:330 displayThrea I[G3D]: GLES\ShaderManager.cpp:139 Linked shader: vs 61 fs 62
04:45:097 displayThrea I[ME]: HLE\scePsmf.cpp:1430 scePsmfPlayerUpdate(08b3f158): video end scheduled
04:45:097 scePsmfPlaye I[ME]: HLE\scePsmf.cpp:1988 __PsmfPlayerFinish(08b3f158): video end reached
04:45:097 scePsmfPlaye I[KERNEL]: HLE\sceKernelThread.cpp:2318 __KernelReturnFromThread: 0
04:45:113 naviThread   I[ME]: HLE\scePsmf.cpp:1051 scePsmfPlayerStop(08b3f158)
04:45:130 displayThrea I[KERNEL]: HLE\sceKernelThread.cpp:2331 sceKernelExitThread(0)
04:45:130 naviThread   I[KERNEL]: HLE\sceKernelThread.cpp:2331 sceKernelExitThread(0)
04:45:196 audioThread  I[KERNEL]: HLE\sceKernelThread.cpp:2331 sceKernelExitThread(0)
04:45:196 user_main    W[ME]: HLE\scePsmf.cpp:1451 scePsmfPlayerReleasePsmf(08b3f158)
04:45:196 user_main    I[ME]: HLE\scePsmf.cpp:1405 scePsmfPlayerDelete(08b3f158)
04:45:197 user_main    I[ME]: HLE\sceMpeg.cpp:1533 sceMpegFinish(...)
```

**Comment by unknownbrackets** [comment]
What are the FBOs it deletes and creates when you change rendering mode during playback?

-[Unknown]

**Comment by daniel229** [comment]
Those。
···
33:53:946 idle0        I[SCEGE]: GLES\Framebuffer.cpp:1978 Destroying FBO for 00000000 : 480 x 272 x 3
33:53:948 idle0        I[SCEGE]: GLES\Framebuffer.cpp:1978 Destroying FBO for 00088000 : 480 x 272 x 3
33:53:956 idle0        I[G3D]: GLES\TextureCache.cpp:152 Texture cached cleared from 1 textures
33:53:958 displayThrea I[SCEGE]: Common\FramebufferCommon.cpp:417 Creating FBO for 00088000 : 480 x 272 x 3
33:53:977 displayThrea I[SCEGE]: Common\FramebufferCommon.cpp:417 Creating FBO for 00000000 : 480 x 272 x 3
33:53:977 displayThrea W[SCEGE]: Common\FramebufferCommon.cpp:454 FBO reusing depthbuffer, 00000000/00110000 and 00088000/00110000
···

**Comment by sum2012** [comment]
This is the chinese patch's save file to reproduce the problem
https://drive.google.com/file/d/0B3OaSdeV0L8kTlNlTnA2eEgydlk/view?usp=sharing

**Comment by unknownbrackets** [comment]
To confirm - if you disable this part, it doesn't work in D3D9 or OpenGL (change in both TextureCache files by making it `if (false) {`)?

```
				// Don't give up just yet.  Let's try the secondary cache if it's been invalidated before.
				// If it's failed a bunch of times, then the second cache is just wasting time and VRAM.
				if (g_Config.bTextureSecondaryCache) {
```

If you look at the separate video file, is it the entire video?  Or does it render subtitles on top or anything?

-[Unknown]

**Comment by sum2012** [comment]
@unknownbrackets Don't work in openGL, I said in #8639 that D3D9 no problem in  video show up ,
but anyway this change still work in D3D9
Yes,it is entire video (OP00.pmf )

oop,Yes,I also forget log file (v1.2.1-63-gb137bf1)
https://gist.githubusercontent.com/sum2012/c1edccaa61f9d5a43462/raw/1bcd7f141d97c529ba073f2956cbc35f20096782/gistfile1.txt

it render subtitles
![1](https://cloud.githubusercontent.com/assets/2177532/13812393/d38bcd1c-ebb6-11e5-9bba-826dd9f6d910.jpg)

**Comment by unknownbrackets** [comment]
I wonder if "4 and 8-bit CLUT format not supported for framebuffers" is somehow related...

-[Unknown]

**Comment by sum2012** [comment]
Follow that error is logo pmf video which is no problem

**Comment by daniel229** [comment]
Fixed in https://github.com/hrydgard/ppsspp/pull/8720

**Comment by sum2012** [comment]
The chinese translated video is still skipped in the middle of the video

**Comment by daniel229** [comment]
Video is still not displayed until recreate FBO in those games.
Flowers (ULJM06390)
Flowers - Natsu Hen
Gakuen Heaven 2 - Double Scramble!
Grisaia no Meikyuu (ULJM06382)
Grisaia no Rakuen (ULJM06395)
Sangoku Ren Senki - Omoide Gaeshi - CS Edition

**Comment by sum2012** [comment]
v1.2.2-870-g2184d37 video is fixed "skipped in the middle of the video"
Can close this issue.
Other video problem should open another issue

**Comment by daniel229** [comment]
Good, closed.
