### ISSUE TITLE
Shin Megami Tensei: Persona 3 Portable

### ISSUE THREAD

**Issue by KuroMii** [hrydgard/ppsspp#6928]
My problem is when I played as female protagonist, the screen became black but the music still on and the emulators not crashed. It's appeared to became black screen when Ryoji came to the school as a new student (11/9). After Ryoji done introduced himself, it's started to black after I choose one of the choices "Stay Awake, Doze off" (It's became black screen "After School" but the emulators not crashed and the musics still played on the emulators)... This problems has been appeared for a long time and I still not seeing any solutions that can fix this problems forever and ever. I'm using ppsspp emulator (0.9.9.1) on my android device.. I am really, really hope that you can fix and stop this problems from being permanent and unsolved. Thanks.

**Comment by unknownbrackets** [comment]
I've seen evidence that cheats or hacks cause this issue, but other bugs may persist.  Have not heard anything in over a year, though, and without data to test with it's hard to know if this is already fixed (by other changes) or not.

Closing this.  If it's still happening, please comment with more details and we'll reopen.

-[Unknown]
