### ISSUE TITLE
Wild ARMs XF DX9 mess

### ISSUE THREAD

**Issue by DarkD** [hrydgard/ppsspp#6936]
![wildarmsmessed](https://cloud.githubusercontent.com/assets/6061259/4356357/780bb0e6-4258-11e4-9692-1b7a7f9f557c.png)
I've took random screenshot from map, but whole game is like that from title to battles. On OGL there's no issues.
Was using build 522, hope that'll help to get rid of all DX9 bugs.

**Comment by unknownbrackets** [comment]
I think this is resolved now, or was last time I checked it.  If it's still a problem please comment with a new screenshot.

-[Unknown]
