### ISSUE TITLE
PES 2014 laggy

### ISSUE THREAD

**Issue by tiger2wander** [hrydgard/ppsspp#6944]
Android: phablet Pantech Sky A890 with Quad-Core Qualcomm 800 and 3GB of RAM, 1080P screen.

Lag occur more often when the ball is near goal or when many players come in the scene.

Is there any settings to solve this or is it incomplete implement in emulator for Android?

**Comment by unknownbrackets** [comment]
Does it happen with "disable slower effects" checked?

-[Unknown]

**Comment by ppmeis** [comment]
Tested with latest build. It works fine for me, even on Android device, always 30fps:
![image](https://cloud.githubusercontent.com/assets/4381277/11616647/f587d832-9c80-11e5-97b1-96a6875570eb.png)

**Comment by unknownbrackets** [comment]
Definitely might have improved.  Will assume so without feedback.

-[Unknown]
