### ISSUE TITLE
earh defense force portable 2 laggy on android

### ISSUE THREAD

**Issue by tiamat999** [hrydgard/ppsspp#6958]
on windows pc the game runs fine on android tablet it is really laggy is it that tablets are not powerful enough to play it or something else

**Comment by tiamat999** [comment]
When can we expect the work around just wondering

**Comment by tiamat999** [comment]
1.0 did nothing for it sadly come on I really want to play this on my tablet badly

**Comment by Elwood89** [comment]
I would not hold my breath... this is a niche game, and the devs probably have many more pressing problems to solve before they even get to work on this. So we can only hope that some day this might get fixed.

**Comment by daniel229** [comment]
Vertex Cache slow down the game 30%+

Vertex Cache on
![01](https://cloud.githubusercontent.com/assets/3481559/11974571/7ca0fffc-a9a0-11e5-9cc1-9168534c7108.png)

Vertex Cache off
![02](https://cloud.githubusercontent.com/assets/3481559/11974572/7ca1791e-a9a0-11e5-925d-849c65e03d6b.png)

**Comment by unknownbrackets** [comment]
Yeah, as I recall the issue here is that it brings almost no benefit - so it just hashes more, but never ends up caching or winning any speed.

-[Unknown]

**Comment by unknownbrackets** [comment]
With #10973, we should now be using larger vertex buffers and caching a lot better.  Also, vertex cache is off by default now.

As such, I'm going to close this - feel free to comment if performance hasn't improved in the latest git, and we'll reopen.  If you're reading this and the year isn't 2018, you're probably seeing a new issue so it'd be better to open a new issue than comment.

-[Unknown]
