### ISSUE TITLE
Eject/inject memorystick feature request 

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#6980]
This game requires the features "remove memorystick" and "insert memorystick".
![05](https://cloud.githubusercontent.com/assets/3481559/4524415/241561b6-4d44-11e4-8a7d-7eb63a9dc88e.png)

On PSP with 660pro-c2 you can go ingame by doing this.
Enable Inferno & NP9660 Use ISO Cache,and then follow the game's requset: "remove memorystick",press circle,and then"insert memorystick".

**Comment by daniel229** [comment]
Flowers has the same problem.
![02](https://cloud.githubusercontent.com/assets/3481559/5676288/41036484-980e-11e4-9362-faec469c8929.png)

**Comment by unknownbrackets** [comment]
What's a good UI for this feature?

We could sneak it into Tools or something.  Is there any benefit to having the ability to leave the memstick unplugged (theoretically preventing the game from saving)?  Or just reinsert?

There's a possibility this may help #7244 in some games, but would have to test to see if it would.

-[Unknown]

**Comment by hrydgard** [comment]
We could add a mappable button, but that wouldn't help touch-only devices.

Adding a button to the pause screen might be confusing for other games, but would work. Possibly we could white list these games that need it and only show the button when they are running? Still, a user encountering this might not figure it out ...

Can we detect that the game is waiting for memstick removal somehow, and conditionally show a prompt or button? Is it polling?

**Comment by sum2012** [comment]
I suggest add in  "Switch UMD" 's place
I also suggest use "white list",this gameid is  ULJM06364 and ULJM06365

**Comment by unknownbrackets** [comment]
Hmm.  A lot of games add a callback handler for memstick insert/removal events.  This gets called when the flag changes.  So, no, they aren't polling specifically I think... but I don't know about Rewrite specifically.

-[Unknown]

**Comment by firetomicbomb** [comment]
This protection is not only found in Rewrite (ULJM06364, ULJM06365), but (AFAIK) also in:
Flowers (ULJM06390)
Grisaia no Meikyuu (ULJM06382)
Grisaia no Rakuen (ULJM06395)

**Comment by daniel229** [comment]
Add a button to pause menu and win32 menu iis good.
Gakuen Heaven 2 also.

**Comment by daniel229** [comment]
Flowers - Natsu Hen

**Comment by unknownbrackets** [comment]
Is this working now that #8889 is implemented?  Note that it could still use other UI potentially.

-[Unknown]

**Comment by sum2012** [comment]
I test rewrite work

**Comment by daniel229** [comment]
Those games all work
Flowers (ULJM06390)
Flowers - Natsu Hen
Gakuen Heaven 2 - Double Scramble!
Grisaia no Meikyuu (ULJM06382)
Grisaia no Rakuen (ULJM06395)
Rewrite
Sangoku Ren Senki - Omoide Gaeshi - CS Edition
Walpurga no Uta - Walpurgisgedichte
