### ISSUE TITLE
"Rewrite" hangs on opening video

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#6981]
Since https://github.com/hrydgard/ppsspp/commit/e8803c4e9bc80b39262cf87b37155b458f257e99
revert <code>int sceKernelDelayThread(u32 usec){}</code>,it works fine.

debulog(rename jpg to rar)
![ppsspplog](https://cloud.githubusercontent.com/assets/3481559/4538528/23d7d988-4df1-11e4-9175-d09cbbb4984d.jpg)

**Comment by unknownbrackets** [comment]
As a test, does changing:

https://github.com/hrydgard/ppsspp/blob/c2f4fad56aada331bbd8dd7db99037285bab853f/Core/HLE/scePsmf.cpp#L1577

To `return hleDelayResult(ERROR_PSMFPLAYER_NO_MORE_DATA, "test", 100);` work as well?

I don't think that delays either, but I may have to retest it.

Also, it's strange that user_main is not waking up on the vblank.  A JpcspTrace of sceKernelChangeThreadPriority would be interesting.  I suspect since audioThread has a priority of 32, some other thread should eventually be scheduled, but I'm not sure what rule we're missing.

A JpcspTrace of scePsmfPlayerGetAudioData would also help.

-[Unknown]

**Comment by daniel229** [comment]
That's a help,but hang on the end of another video.

**Comment by daniel229** [comment]
JPCSPTRACE for scePsmfPlayerGetAudioData
https://gist.github.com/daniel229/d5d7495ba9aaa5205a5a

**Comment by unknownbrackets** [comment]
Hmm, in that we can see it rapidly calling it too.  Between 13:14:52.632479 and 13:14:53.018384 - that is, for 0.4 seconds.

What's interesting is there are a couple gaps:

```
13:14:52.637247 audioThread - -> scePsmfPlayerGetAudioData 0x9EA80E8, 0x90150C0 = 0x0
13:14:52.676139 audioThread - <- scePsmfPlayerGetAudioData 0x9EA80E8, 0x90150C0 = 0x8061600C

13:14:52.681521 audioThread - -> scePsmfPlayerGetAudioData 0x9EA80E8, 0x90150C0 = 0x0
13:14:52.715727 audioThread - <- scePsmfPlayerGetAudioData 0x9EA80E8, 0x90150C0 = 0x8061600C

13:14:52.719934 audioThread - -> scePsmfPlayerGetAudioData 0x9EA80E8, 0x90150C0 = 0x0
13:14:52.757990 audioThread - <- scePsmfPlayerGetAudioData 0x9EA80E8, 0x90150C0 = 0x8061600C

13:14:52.763438 audioThread - -> scePsmfPlayerGetAudioData 0x9EA80E8, 0x90150C0 = 0x0
13:14:52.805948 audioThread - <- scePsmfPlayerGetAudioData 0x9EA80E8, 0x90150C0 = 0x8061600C

13:14:52.809779 audioThread - -> scePsmfPlayerGetAudioData 0x9EA80E8, 0x90150C0 = 0x0
13:14:52.847407 audioThread - <- scePsmfPlayerGetAudioData 0x9EA80E8, 0x90150C0 = 0x8061600C

13:14:52.852346 audioThread - -> scePsmfPlayerGetAudioData 0x9EA80E8, 0x90150C0 = 0x0
13:14:52.913969 audioThread - <- scePsmfPlayerGetAudioData 0x9EA80E8, 0x90150C0 = 0x8061600C

13:14:52.918554 audioThread - -> scePsmfPlayerGetAudioData 0x9EA80E8, 0x90150C0 = 0x0
13:14:52.951243 audioThread - <- scePsmfPlayerGetAudioData 0x9EA80E8, 0x90150C0 = 0x8061600C

13:14:52.955468 audioThread - -> scePsmfPlayerGetAudioData 0x9EA80E8, 0x90150C0 = 0x0
13:14:52.990088 audioThread - <- scePsmfPlayerGetAudioData 0x9EA80E8, 0x90150C0 = 0x8061600C

13:14:52.995004 audioThread - -> scePsmfPlayerGetAudioData 0x9EA80E8, 0x90150C0 = 0x0
13:14:53.014354 audioThread - <- scePsmfPlayerGetAudioData 0x9EA80E8, 0x90150C0 = 0x8061600C
```

What this means to me is that something else is winning the scheduling war, somehow.  Maybe scePsmfPlayerGetAudioData is actually doing something that causes rescheduling... but only sometimes?

-[Unknown]

**Comment by daniel229** [comment]
JPCSPTRACE for sceKernelChangeThreadPriority 
https://gist.github.com/daniel229/753792cadb4b2463d59f

**Comment by daniel229** [comment]
Fixed.
