### ISSUE TITLE
Fate extra CCC crashing from changing Software Skinning on to off in game.

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#6990]
Turn Software Skinning on then go to the a specific place,change Software Skinning on to off,then press the "continue" tab,it crashes.If Software Skinning is off before,change on/off would not crash.
OpenGL only,D3D9 is fine.

stacktrace
![02](https://cloud.githubusercontent.com/assets/3481559/4601487/6dc04c3c-5103-11e4-8df1-07fed55b8da2.png)

**Comment by unknownbrackets** [comment]
Does vertex cache on/off affect this?

Unfortunately, this is a crash in the NVIDIA driver, so it's hard to tell what's wrong.

-[Unknown]

**Comment by sum2012** [comment]
Turn off vertex cache don't affect this

**Comment by unknownbrackets** [comment]
What if you change the `if (useElements) {` to `if (false) {`?  It will render everything broken, but does it crash still?

-[Unknown]

**Comment by daniel229** [comment]
Change 2 <pre>if (useElements) { </pre> to <pre>if (false) {</pre> in opengl.it's still crashing

**Comment by unknownbrackets** [comment]
If `vbo` is 0, and `useElements` doesn't matter, it seems like it's crashing because of one of:

1. The vertex data / pointer.
2. The vertex format.
3. Some other state.

And, it *only* crashes changing on -> off... hmm.

-[Unknown]

**Comment by unknownbrackets** [comment]
Just to be sure, this in TransformPipeline.cpp:

```c++
		// Also avoid caching when software skinning.
		if (g_Config.bSoftwareSkinning && (lastVType_ & GE_VTYPE_WEIGHT_MASK))
			useCache = false;
```

If you make it:
```c++
		// Also avoid caching when software skinning.
		if ((lastVType_ & GE_VTYPE_WEIGHT_MASK))
			useCache = false;
```

It still crashes right?

-[Unknown]

**Comment by daniel229** [comment]
Yes,still crashes

**Comment by unknownbrackets** [comment]
Does this still happen?

-[Unknown]

**Comment by unknownbrackets** [comment]
Given all the graphics backend changes, I suspect this is fixed now.  Maybe even from core profile related changes.

I'm going to close this.

-[Unknown]
