### ISSUE TITLE
Nvidia Shield Portable - the emulator crashes each time you choose a rendering mode.

### ISSUE THREAD

**Issue by kingpinzero** [hrydgard/ppsspp#6991]
This happens at least with the latest 10 commits.

Each time you choose a different rendering mode (the resolution and the Android scaler) the emulator crashes.

Modfying the INI by hand makes the desired settings stick, but they cannot be changed in emulator options as it crashes otherwise.

Tried to unistall, clean every folder related to PPSSPP, with no success.

Shield Portable is updated to last OTA, stock kernel and recovery, just rooted.

**Comment by unknownbrackets** [comment]
Any luck?  Does this still happen?

-[Unknown]

**Comment by hrydgard** [comment]
Nope, doesn't happen on mine..
