### ISSUE TITLE
Disc changing problem in "Gakuen Heaven" (user-reported)

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#6992]
Got an email:

"The game I am currently playing, which is called Gakuen Heaven, consists of two discs.
When I finished the first disc, a message popped up saying I need to switch to disc 2, which I did.
However, when I pressed 'Start' on disc 2, another message popped up, saying I need to switch to disc 1.
It was just endless loop between the two discs, and disc 2 never worked with nor without disc 1.
I tried switching UMD, but the app just froze and stopped working, kicking me out.
I tried combining the two iso files together, but that didn't work out either.
Please let me know what should I do, or please take this problem into account when you develop the next version."

![2014-10-05-01-31-41](https://cloud.githubusercontent.com/assets/130929/4602559/bee86206-5140-11e4-999a-e32411898bc3.jpg)

![2014-10-05-01-36-23](https://cloud.githubusercontent.com/assets/130929/4602560/c29584ce-5140-11e4-90b6-a09b749bd0c2.jpg)

**Comment by daniel229** [comment]
UMD switch is fine with the latest build v1.0.1-179-gb8d798c.Pressing circle button in the screen above,then it show up the screen like below.
![01](https://cloud.githubusercontent.com/assets/3481559/6702336/21aa8586-cd65-11e4-9838-326d1a1960e7.png)

Then go to pause menu and switch UMD to Disc 2,the last thing is pressing continue in the pause menu to play the game.

**Comment by unknownbrackets** [comment]
Great, so sounds like it works now.

-[Unknown]
