### ISSUE TITLE
Glyph mapping: ar-AE not loaded into map

### ISSUE THREAD

**Issue by Arthur2e5** [hrydgard/ppsspp#7002]
Maybe hrydgard/native should add support for those characters.

![2014-10-15 1 51 23](https://cloud.githubusercontent.com/assets/6459309/4641109/4d50b7bc-5431-11e4-8a6c-4f6ed21c42c0.png)

* * *
By the way, after the ppsspp-lang update, a few glyphs (e.g. 舍) showed up as question marks. 

Since copying the text can be somehow annoying, adding this to `b.sh` to automatically generate the TXTs may be better:
```Bash
# Version Detection needed? git log?
for i in zh ko; do grep -h $i assets/langregion.ini > $i.txt; sed -e 's/#.*$//g' lang/${i}_* >> $i.txt; done
mv zh.txt chinese.txt; mv ko.txt korean.txt
```
For Windows, things like `cp assets\langregion.ini+lang\zh_*.txt chinese.txt` should work.

**Comment by unknownbrackets** [comment]
I think we should consolidate this into #7126.  On Windows, we use native fonts where possible, but we don't currently on e.g. Mac or other platforms.

-[Unknown]
