### ISSUE TITLE
The Godfather video flickering

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#7008]
Memcpy fbo upload during the video playback.
info log
https://gist.github.com/daniel229/3c41117dc706bb11b743

**Comment by unknownbrackets** [comment]
This is suspicious:

23:08:755 godfather    N[G3D]: Common\FramebufferCommon.cpp:520 Memcpy fbo upload 08400000 -> 04000000
23:08:789 godfather    N[G3D]: Common\FramebufferCommon.cpp:520 Memcpy fbo upload 08488000 -> 04000000

Is it displaying 0x04088000?  Or always just 04000000?  Can you try changing this line:

WARN_LOG_ONCE(btucpy, G3D, "Memcpy fbo upload %08x -> %08x", src, dst);

To:

WARN_LOG(G3D, "Memcpy fbo upload %08x -> %08x (%d bytes / %d+%d height)", src, dst, size, dstY, dstH);

I'm wondering if it's copying in a way that should copy the other bytes to the other framebuffer.

-[Unknown]

**Comment by daniel229** [comment]
04088000 is black,040000000 is good.
here is the log
https://gist.github.com/daniel229/a75adf2249406fffc0d2

**Comment by unknownbrackets** [comment]
> Decimating FBO for 00000000 (480 x 272 x 0), age 6

Interesting.  If you set a breakpoint at 04088000, is it hit during the middle of the video at all?

-[Unknown]

**Comment by daniel229** [comment]
04088000 does not hit during the video.04000000 does

**Comment by daniel229** [comment]
Great, Seems fixed in https://github.com/hrydgard/ppsspp/pull/8341
