### ISSUE TITLE
Switch to Android Studio from Eclipse?

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#7012]
I've switched to Android Studio on another project and it really is quite a bit better than Eclipse (no more refreshing, for one thing!), so I guess no-one will mind if I switch PPSSPP for Android over as well?

If I switch it over, @angelXwind and @Orphis will have to update their buildbots to run this command instead of Ant:

./gradlew build

which I presume is not too much of a hassle.

**Comment by animaonline** [comment]
Any updates on this one? Eclipse ADT support has been deprecated, so it would make sense to switch now. :)

**Comment by unknownbrackets** [comment]
Well, I've just been using ant (don't use Android Studio or Eclipse), I suspect it would not be hard to switch to gradle, since I think it still uses the same ndk build system, it would probably just be the (relatively simple) Java stuff.

-[Unknown]

**Comment by Krakn** [comment]
@hrydgard 

I think you can close this one! ;)
