### ISSUE TITLE
Dbz Dx9

### ISSUE THREAD

**Issue by Heoz** [hrydgard/ppsspp#7016]
So when i turn dx9 on dbz tenkaichi tag team on buffered render i can only play normal on 1x resolution if i put it on bigger screen screen stays at 1x and ingame screen gets black on non buffering screen is normal speed is actually improved but black outlines on characters disappear :O and when will ad hoc be merged :O

**Comment by issuer** [comment]
The Adhoc branch has been merged in 1.0 and i could not replicate your issue, seems fixed on the Windows version of PPSSPP 1.0 since the resizing window bug on D3D9 Backend is now gone.
