### ISSUE TITLE
[Feature Request] Allow option to change save folder.

### ISSUE THREAD

**Issue by ppmeis** [hrydgard/ppsspp#7017]
I think It would be fine to PPSSPP to have the ability for change save folder to another place instead on force always PPSSPP folder. This will be very good for: a) keep game saves while removing old PPSSPP folder for a clean update/installation. b) Have the ability to save directly to a real PSP, I mean, on Memory stick, even more, PPSSPP could detect PSP usb connection automatically and request to user if he like to change/import save folder from/to real PSP.

Cheers.

**Comment by sum2012** [comment]
I think that we can check wether is a USB drive

**Comment by ppmeis** [comment]
I think this is already supported by installed.txt file, so I will close this.

**Comment by MarioMasta64** [comment]
https://github.com/MarioMasta64/EverythingPortable/releases/latest
https://github.com/MarioMasta64/EverythingPortable/blob/master/launch_ppsspp.bat
i made a ppsspp launcher for my suite with a special feature: memstick detection. memsticks will automatically be detected and set in quicklauncher mode and a menu will ask which you would like to use in launcher mode. you can type default in launcher mode to use data\ppsspp\ if no memstick is found in both modes it will simply launch using data\ppsspp\. it will cycle through all known "removable" drives that means no fixed drives and no cd or dvd drives

**Comment by MarioMasta64** [comment]
in response to hrydgard (owner's) post. showing that it can be done and pretty fastly too.
