### ISSUE TITLE
The Red Star: only the hud is visible when you actually start the game

### ISSUE THREAD

**Issue by vsub** [hrydgard/ppsspp#7024]
Tried OGL,DX9 and software mode and also check the GE Debugger but nothing other than the hud is rendered(you see the elements that are supposed to be loaded on the left side but they are not displayed on the right side of the GE Debugger)

**Comment by unknownbrackets** [comment]
Can you post screenshots / copy of tab contents for the GE debugger when trying to render some things?

When it shows something on the left, and highlights an area on the right where that thing should go, that's perfect.

https://github.com/hrydgard/ppsspp/wiki/How-to-find-a-graphic-issue-with-the-GE-debugger

-[Unknown]

**Comment by vsub** [comment]
Step Frame=>Step Prim once and this red overlay is shown.
After that it switch to black screen and it doesn't display anything until it start displaying what you see on the picture without the red(the hud)

When everything is loaded(the hud),the next step prim is again red screen and again black screen(all of the textures are visible on the left side...I think)

![2015-12-29_201610](https://cloud.githubusercontent.com/assets/5032540/12039625/9492f254-ae6a-11e5-96eb-464d0f6ca8ab.jpg)

Flags

Name	Value
Lighting enable	0
Light 0 enable	0
Light 1 enable	0
Light 2 enable	0
Light 3 enable	0
Clip enable	1
Cullface enable	1
Texture map enable	1
Fog enable	0
Dither enable	0
Alpha blend enable	0
Alpha test enable	0
Depth test enable	1
Stencil test enable	0
Antialias enable	0
Patch cull enable	0
Color test enable	0
Logic op enable	0
Depth write disable	0


Lighting

Name	Value
Ambient color	ffffff
Ambient alpha	0000ff
Material update	ambient
Material emissive	343434
Material ambient	ffffff
Material diffuse	ffffff
Material alpha	0000ff
Material specular	000000
Mat. specular coef	0.000000
Reverse normals	0
Shade model	1
Light mode	0 (disabled)
Light type 0	256 (disabled)
Light type 1	0 (disabled)
Light type 2	0 (disabled)
Light type 3	0 (disabled)
Light pos 0	-30.215332, -28.163574, 0.000000 (disabled)
Light pos 1	1.000000, 0.000000, 0.000000 (disabled)
Light pos 2	0.000000, 0.000000, 1.000000 (disabled)
Light pos 3	0.000000, 0.000000, 1.000000 (disabled)
Light dir 0	0.000000, 0.000000, -1.000000 (disabled)
Light dir 1	0.000000, 0.000000, -1.000000 (disabled)
Light dir 2	0.000000, 0.000000, -1.000000 (disabled)
Light dir 3	0.000000, 0.000000, -1.000000 (disabled)
Light att 0	0.000000, 0.034132, 0.000000 (disabled)
Light att 1	1.000000, 0.000000, 0.000000 (disabled)
Light att 2	1.000000, 0.000000, 0.000000 (disabled)
Light att 3	1.000000, 0.000000, 0.000000 (disabled)
Lightspot coef 0	0.000000 (disabled)
Lightspot coef 1	0.000000 (disabled)
Lightspot coef 2	0.000000 (disabled)
Lightspot coef 3	0.000000 (disabled)
Light angle 0	-1.000000 (disabled)
Light angle 1	-1.000000 (disabled)
Light angle 2	-1.000000 (disabled)
Light angle 3	-1.000000 (disabled)
Light ambient 0	000000 (disabled)
Light diffuse 0	161c88 (disabled)
Light specular 0	ffffff (disabled)
Light ambient 1	000000 (disabled)
Light diffuse 1	ffffcf (disabled)
Light specular 1	000000 (disabled)
Light ambient 2	000000 (disabled)
Light diffuse 2	000000 (disabled)
Light specular 2	000000 (disabled)
Light ambient 3	000000 (disabled)
Light diffuse 3	000000 (disabled)
Light specular 3	000000 (disabled)

Texture

Name	Value
Tex U scale	1.000000
Tex V scale	1.000000
Tex U offset	0.000000
Tex V offset	0.000000
Tex mapping mode	gen: tex coords, proj: uv
Tex shade srcs	000302
Tex mode	swizzled, 1 levels
Tex format	CLUT8
Tex filtering	min: linear, mag: linear
Tex wrapping	wrap s, wrap t
Tex level/bias	000000
Tex lod slope	3e4ccc
Tex func	modulate, RGBA
Tex env color	ffffff
CLUT	08f8fe70, w=0
CLUT format	ABGR 8888 ind & ff
Texture L0 addr	08f90270, w=16
Texture L1 addr	08f63180, w=32
Texture L2 addr	08f63580, w=16
Texture L3 addr	096cd080, w=16
Texture L4 addr	096c5a40, w=16
Texture L5 addr	00000000, w=0
Texture L6 addr	00000000, w=0
Texture L7 addr	00000000, w=0
Texture L0 size	8x8
Texture L1 size	32x32
Texture L2 size	16x16
Texture L3 size	16x16
Texture L4 size	16x16
Texture L5 size	1x1
Texture L6 size	1x1
Texture L7 size	1x1

Settings

Name	Value
Clear mode	1, write color, alpha/stencil, depth
Framebuffer	00000000, w=512
Framebuffer format	8888
Depthbuffer	00198000, w=512
Vertex type	through, ABGR 8888 colors, s16 positions
Offset addr	08000000
Vertex addr	08b2c100
Index addr	00000000
Region	0,0 - 479,271
Scissor	0,0 - 479,271
Min Z	000000
Max Z	00ffff
Viewport Scale	240.000000, -136.000000, 32767.500000
Viewport Offset	2048.000000, 2048.000000, 32767.500000
Offset	1808.000000x1912.000000
Cull mode	0
Color test	pass if (c & ffffff) NEVER (000000 & ffffff) (disabled)
Alpha test	pass if (a & 00) ALWAYS (00 & 00) (disabled)
Stencil test	pass if (ff & ff) == (a & ff) (disabled)
Stencil test op	fail=KEEP, pass/depthfail=KEEP, pass=KEEP (disabled)
Depth test	pass if src <= dst
Alpha blend mode	add: src.a, 1.0 - src.a (disabled)
Blend color A	000000 (disabled)
Blend color B	000000 (disabled)
Logic Op	copy (disabled)
Fog 1	0.000000 (disabled)
Fog 2	0.000000 (disabled)
Fog color	ffffff (disabled)
RGB mask	000000
Stencil/alpha mask	000000
Morph Weight 0	1.000000
Morph Weight 1	0.000000
Morph Weight 2	0.000000
Morph Weight 3	0.000000
Morph Weight 4	0.000000
Morph Weight 5	0.000000
Morph Weight 6	0.000000
Morph Weight 7	0.000000
Patch division	001010
Patch primitive	000000
Patch facing	000000
Dither 0	000000 (disabled)
Dither 1	000000 (disabled)
Dither 2	000000 (disabled)
Dither 3	000000 (disabled)
Transfer src	00000000, w=0
Transfer src pos	0,0
Transfer dst	00000000, w=0
Transfer dst pos	0,0
Transfer size	0,0

**Comment by unknownbrackets** [comment]
Sorry, that one is just it clearing the screen, it needs to be a later one (the red shouldn't be covering the ENTIRE screen.)

But, it's good to know it's clearing all the depth/stencil/color initially, as games don't always clear all three.  If you want to check, another interesting thing might be the "Vertices" when it's clearing.  If they don't all have the same color or don't all have the same depth, that might be why it's not working (since we don't clear exactly correctly in that specific case.)

-[Unknown]

**Comment by unknownbrackets** [comment]
I feel like there's a chance this is depth related.

When you step prim through, does it highlight in red any areas that it's not drawing?  Or does it only highlight the hud?

-[Unknown]

**Comment by vsub** [comment]
It took some time from Step frame to the next frame(Step Prim only the whole time)but the only thing that was highlighted in red was the hud elements.
When it wasn't drawing the hud,it was black screen all the time,nothing else appeared or was highlighted the whole time

**Comment by unknownbrackets** [comment]
Okay, that seems to indicate it's not related to a graphics test (like depth, alpha, etc.), or clipping, or anything like that.  It could mean we're mishandling the matrices, a vfpu bug, or something like that.

Did you ever see textures on the left side that looked like probably parts of the game?  Or did it not even have textures?

-[Unknown]

**Comment by vsub** [comment]
> Did you ever see textures on the left side that looked like probably parts of the game? Or did it not even have textures?

If you are talking about the upper left box in the GE debugger,then everything is displayed there but nothing other than the hud appear(or get highlighted)in he right box
