### ISSUE TITLE
Driver 76 lines bug

### ISSUE THREAD

**Issue by cerg2010cerg2010** [hrydgard/ppsspp#7026]
Screenshot: https://docs.google.com/file/d/0B89MjDzbWX2wZlNGdFpBbmxabm8/edit?usp=docslist_api

**Comment by unknownbrackets** [comment]
Does this still happen?  Also, does it happen in the software renderer?

-[Unknown]

**Comment by hrydgard** [comment]
Hm, might be the "continue" primitive type getting mishandled? Could of course also be a race condition / cache invalidation issue between the GPU and CPU causing the former to draw using garbage data.

**Comment by KabutoKun** [comment]
Using one of the latest builds from buildbot (ppsspp-v1.2.2-634-g606856c-winx86) the mentioned graphical glitches still happens with Driver 76, but it doesn't happen with the software renderer.

Another problem is that the game randomly crashes, especially if you are around an specific area of the game while playing the first mission/intro.

I have uploaded a simple log from the game after it crashed, might be useful to the devs.
http://pastebin.com/rCCzevEB

**Comment by unknownbrackets** [comment]
Does this still happen in the software renderer?  Just want to confirm that it's the frustum culling.

-[Unknown]

**Comment by weihuoya** [comment]
it doesn't happen if you use the software renderer.

**Comment by unknownbrackets** [comment]
I expect this to work now - on all backends - now that #11393 is merged.  How's it look?

-[Unknown]

**Comment by Saramagrean** [comment]
Lines bug is fixed. 👍 
![ppsspp v1 6 3-482-g025e478d2 - ulus10235 _ driver 76 9_19_2018 12_16_55 pm](https://user-images.githubusercontent.com/26355472/45733625-a85b0680-bc0b-11e8-8f54-963578745965.png)

But sometime sky is dark.
![ppsspp v1 6 3-482-g025e478d2 - ulus10235 _ driver 76 9_19_2018 12_22_52 pm](https://user-images.githubusercontent.com/26355472/45733680-d6d8e180-bc0b-11e8-89f8-c3b6b80a9130.png)

**Comment by unknownbrackets** [comment]
Does the sky thing happen on all backends, or just certain ones?

Could you try exporting a GE debugger dump of that on PC?

To do this, open the game and select Debug -> GE debugger..., then when it's displaying the scene, press Record in the top right.  After a second or so, it'll finish and save a trace of the drawing activity.

After that, check the memstick/PSP/SYSTEM/DUMP folder and it'll have created a file named something like "ULES12345_0000.ppdmp".  You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by Saramagrean** [comment]
Only in OpenGL & Vulkan, D3D11 did not found this problem. 

Here, GE dump from Vulkan. 
[ULUS10235_0001.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/2395905/ULUS10235_0001.ppdmp.zip)

**Comment by unknownbrackets** [comment]
That's actually a separate issue - might be ideal to use a separate issue to track it, since the lines are fixed.

Added a note in #11399 about it.  OpenGL and Vulkan have different bugs, actually - OpenGL is ignoring the maxz here, and Vulkan is clamping incorrectly to it.

-[Unknown]

**Comment by Emulatorer** [comment]
This issue still isn't fixed by #12227?
Someone commenting here https://github.com/hrydgard/ppsspp/pull/12227#issuecomment-519893177 that this game is now fixed

**Comment by hrydgard** [comment]
The original bug here should now be fixed on all non-ancient devices, so I'm closing.
