### ISSUE TITLE
Suzumiya Haruhi no Yakusoku charackter repositionating on wrong place dx9 

### ISSUE THREAD

**Issue by big200** [hrydgard/ppsspp#7037]
if i play Suzumiya Haruhi no Yakusoku the charackter image flicker up and down realy fast 

![image](https://cloud.githubusercontent.com/assets/8776330/4871423/d0e57dd0-61b3-11e4-9ec3-de170cd0b71f.png)

![image](https://cloud.githubusercontent.com/assets/8776330/4871426/07693cf2-61b4-11e4-9140-188d6c96d55d.png)

how the picture show the image change its location

**Comment by daniel229** [comment]
OpenGL and Directx9 both are fine now.
![01](https://cloud.githubusercontent.com/assets/3481559/6224463/2ff15ec2-b6b7-11e4-82f1-818b44c3474e.png)

**Comment by thedax** [comment]
Nice. Closing.
