### ISSUE TITLE
Kingdom Hearts Birth by Sleep USA [ULUS-10505] effekte bihind disney logo ar not visible in OopenGL mode

### ISSUE THREAD

**Issue by big200** [hrydgard/ppsspp#7040]
if i run Kingdom Hearts Birth by Sleep USA [ULUS-10505] the Background of logos is not visible.
OpenGl 
![image](https://cloud.githubusercontent.com/assets/8776330/4874838/147e3b24-6275-11e4-833f-dda8843badc9.png)

direct x9
![image](https://cloud.githubusercontent.com/assets/8776330/4874842/690f22fc-6275-11e4-9779-41bf6007fad0.png)

systeminfo
![image](https://cloud.githubusercontent.com/assets/8776330/4874856/5af568b0-6276-11e4-8b0c-23d3496be7d3.png)

**Comment by unknownbrackets** [comment]
Well, since this no longer happens, I don't think there's anything more to solve.  Texture scaling tries to smooth edges when scaling, and that results in these sort of problems when games draw things in the way this game does.

-[Unknown]
