### ISSUE TITLE
PPSPP doesn't withstand aero disabling/enabling while running in OpenGL backend

### ISSUE THREAD

**Issue by pal1000** [hrydgard/ppsspp#7057]
Direct3D9 is unaffected.
It doesn't matter if it's minimized or not.
It is reproducible in both ways from aero enabled to disabled and from aero disabled to enabled.
Video: http://www.youtube.com/embed/KEUQX7TjqWo
I expect it to recover after a minimize + restore if caught in normal window or maximized and right away on restore if caught minimized. In Direct3D9 it doesn't even needs these conditions to recover. 
System information:
![menu_00000](https://cloud.githubusercontent.com/assets/1138235/4937721/c8a5139a-65c5-11e4-833e-734667716d2b.jpg)
![menu_00001](https://cloud.githubusercontent.com/assets/1138235/4937722/c8ab7dfc-65c5-11e4-9ca4-49f868d2959e.jpg)

**Comment by thedax** [comment]
I can't reproduce this on my NVidia card in the latest builds. Perhaps it's yet another Intel issue?

**Comment by unknownbrackets** [comment]
I think so.  I once hit a weird situation like this testing on an Intel GPU but I no longer have access to it... But it wasn't that I turned off aero, the driver crashed or something, so I was not shocked things stopped working...

I wonder if we can listen for some event and trigger a resize.

-[Unknown]

**Comment by pal1000** [comment]
Still happens with latest driver 10.18.10.4061. I think I'll report this on Intel Community. I did the same with same with dual blending problem reported in #4848 and #4867 and now it's working properly.

**Comment by pal1000** [comment]
Reported this on Jan. 20 on Intel Graphics community forum and I can confirm it was fixed in latest driver 10.18.10.4176.
![menu_00000](https://cloud.githubusercontent.com/assets/1138235/7159467/f18e82ee-e38a-11e4-9db4-921412bfdd5f.jpg)
![menu_00001](https://cloud.githubusercontent.com/assets/1138235/7159468/f1b692ac-e38a-11e4-9feb-8179985efb4d.jpg)

**Comment by unknownbrackets** [comment]
Hurray.

-[Unknown]
