### ISSUE TITLE
Can't type katakana on on-screen keyboard

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#7084]
Apparently this is needed for some quest in Lord Of Apocalypse:

http://forums.ppsspp.org/showthread.php?tid=13809

**Comment by unknownbrackets** [comment]
Don't you just need to press R a few times?

-[Unknown]

**Comment by unknownbrackets** [comment]
Now that we show the game preferred keyboard by default, has this improved?  Not sure if it's worth keeping open if we don't know any details...

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, closing.
