### ISSUE TITLE
Crisis Core Crash on iOS (probably bad ffmpeg)

### ISSUE THREAD

**Issue by UoH** [hrydgard/ppsspp#7095]
When I want to start a new Game at Crisis Core it freezes at the first picture of the video. I'm using a iPad 4 32gb. With ppssp version 
![image](https://cloud.githubusercontent.com/assets/9783027/5061366/ae768386-6d91-11e4-9ef6-72853b1dbf11.jpg)
I need your help please.

**Comment by unknownbrackets** [comment]
Does this still happen?

-[Unknown]

**Comment by ehsmarinr** [comment]
I haven't tried again lately. I will give it a go later and let you know.

**Comment by unknownbrackets** [comment]
We've recently updated FFmpeg on iOS so I'm hopeful.  Thanks.

-[Unknown]

**Comment by ehsmarinr** [comment]
I am glad to tell you that I'm way past where the game would crash and
still going. Great job guys 👍👍 and thank you for yalls work!
