### ISSUE TITLE
Little JIT things

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#7097]
Just my todo list for minor JIT inefficiencies discovered when browsing the jit viewer on the train...
- ~~mtc1 zero, f12 doesn't generate optimal code~~ (done)
- Sort sequences of sw r2, 12(sp); sw r1, 8(sp); sw r0, 4(sp)    (will allow LDMIA/STDMIA)
- x86-32 JIT also needs "map-reg-as-address" to avoid repeatedly masking addresses in such cases

**Comment by unknownbrackets** [comment]
Are these still relevant?  I think we're doing the sorting in ir, right?

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, and I don't really care about the last one anymore.
