### ISSUE TITLE
Tegra K1

### ISSUE THREAD

**Issue by mailwl** [hrydgard/ppsspp#7105]
Dear hrydgard! Will you adapt your emulator for this processor? It has native OpenGL 4.1, as far as i know, maybe using this API will lead to great perfomance on devices with this processor?
Just checked the game "(ULJS-00132) Tales of Rebirth", I believe it will be playable on android Nvidia Shield Tablet, but no. slow

**Comment by unknownbrackets** [comment]
We've done work already to optimize for the Tegra K1 series of processors.  Most of the optimizations are common to desktop.

Although there's still work to be done enabling desktop OpenGL, that's not really the key here to opening up performance.  Ultimately, we render much the same way on desktop and mobile.  The GPU here is a lot better, and that is true for either interface.

As such, I'm going to close this.

-[Unknown]
