### ISSUE TITLE
Phantasy Star Portable 2 Chinese translation video missing text.

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#7110]
It never works either opengl or software gpu.
jpcsp fixed it in https://code.google.com/p/jpcsp/source/detail?r=3667

**Comment by daniel229** [comment]
Also happens in the demo.
http://www.pspdemocenter.com/page.php?id=2841

**Comment by hrydgard** [comment]
What's the game ID for this translated game? Does it still happen?

**Comment by benderscruffy** [comment]
Please close as this has not been updated in years
