### ISSUE TITLE
Phantasy Star Portable 2 

### ISSUE THREAD

**Issue by Heoz** [hrydgard/ppsspp#7119]
D3D9 have issues like overlighting like in Miami Vice and some strange screen on sonic but it gives a speed :O

**Comment by issuer** [comment]
Why is this still open? This issue was fixed.

**Comment by hrydgard** [comment]
"Fixed" with the depth hackfix ... but yeah, I'm not sure we can easily do better...

**Comment by issuer** [comment]
I believe he was already using the hack, this issue happened even with the PSP2 enabled.
