### ISSUE TITLE
Controller mapping issues on iOS 8.1 with sixaxis PS3 controller.

### ISSUE THREAD

**Issue by Healdb** [hrydgard/ppsspp#7142]
All attempts to map or use the down 
And left directIons on the right analog stick on a Sixaxis PS3 and a standard PS4 controller have failed. The right and up directions work fine however. Additionally, when testing the analog connection within PPSSPP, the right analog stick displays as N/A. I am connecting the controller using controllers4all, and I am able to use the aforementioned right analog directions in every other app except this.

**Comment by zaknafein777** [comment]
Just a little bump this issue is also happening with MFI controllers such as the moga rebel. Not sure if something change from iOS 7 to 8 that is mucking the controllers up or what.

**Comment by pralima87** [comment]
Yeah here to also report this issues with all Mfi controllers.
Also using "Controllers 4 All" (PS3/PS4/iPega).
Some users say that is happening only with iOS 8.x.
