### ISSUE TITLE
Fight night round 3 has a very low graphic quality Or pixelated on Ppsspp dev latest iOS 

### ISSUE THREAD

**Issue by jay-arco07** [hrydgard/ppsspp#7153]
Hi .. I just want help, I downloaded the Ppsspp dev latest and also I placed fight night round 3, nba 2k12 and dragon ball on my iPod touch 5g. Fortunately the 2 games are running smooth(dragon ball and nba 2k12) and the graphics are fine, but when I played fight night round 3 the graphics has a very low quality. I tried setting up the resolution to 1:1 but still there is no change. Although it is on full speed and lt runs smooth How can I improve the graphics just like the real game on the psp???..

**Comment by unknownbrackets** [comment]
So, is this resolved now?  As far as I understand, the iOS builds are not available for every version of PPSSPP.

-[Unknown]

**Comment by hrydgard** [comment]
If it wasn't solved already, #9258 will fix this.
