### ISSUE TITLE
Unreadable Menu when using Dexpot (DexControl)

### ISSUE THREAD

**Issue by Berrypicker** [hrydgard/ppsspp#7198]
Happens when using DexControl. Unusual because this never happens with any other program.

http://a.pomf.se/gfkqlg.webm

**Comment by unknownbrackets** [comment]
Strange.  But since we haven't received any further reports of this in a year, and an acceptable workaround was found, and moreover it seems like it might likely be a bug in an external software... I'm going to close this.

-[Unknown]
