### ISSUE TITLE
Can't play transferred save state from iOS to PC

### ISSUE THREAD

**Issue by senzubean** [hrydgard/ppsspp#7205]
I've been attempting to use my crisis core save state, copied over from iOS to PC to get past one of the spots it tends to freeze (right after you fight Bahamut and the movie scene freezes when Genesis opens his wings). However, I keep getting an error code, no matter which save states I use. 

It says - Error: After "CoreTiming", found 191837 (0x2ED5D) instead of save marker 66 (0x42). Aborting savestate load...

Can anyone help? I have the correct files from the correct filepaths.

**Comment by unknownbrackets** [comment]
I think the latest built versions are newer now, so you can try again.

-[Unknown]

**Comment by unknownbrackets** [comment]
No feedback, so we can't know if this is still happening.  Likely it has been fixed, and we fixed another savestate platform-dependent issue too, I believe.

Closing this.  If you're still experiencing, please feel free to comment and we'll reopen.

-[Unknown]
