### ISSUE TITLE
[linux] ppssppqt build error

### ISSUE THREAD

**Issue by SergeiAlekseev** [hrydgard/ppsspp#7221]
g++ -m64 -Wl,-O1 -o ppsspp .obj/ppsspp/SDLJoystick.o .obj/ppsspp/QtMain.o .obj/ppsspp/BackgroundAudio.o .obj/ppsspp/ControlMappingScreen.o .obj/ppsspp/CwCheatScreen.o .obj/ppsspp/DevScreens.o .obj/ppsspp/EmuScreen.o .obj/ppsspp/GameInfoCache.o .obj/ppsspp/GamepadEmu.o .obj/ppsspp/GameScreen.o .obj/ppsspp/GameSettingsScreen.o .obj/ppsspp/InstallZipScreen.o .obj/ppsspp/MainScreen.o .obj/ppsspp/MiscScreens.o .obj/ppsspp/NativeApp.o .obj/ppsspp/OnScreenDisplay.o .obj/ppsspp/PauseScreen.o .obj/ppsspp/ReportScreen.o .obj/ppsspp/Store.o .obj/ppsspp/TiltAnalogSettingsScreen.o .obj/ppsspp/TiltEventProcessor.o .obj/ppsspp/TouchControlLayoutScreen.o .obj/ppsspp/TouchControlVisibilityScreen.o .obj/ppsspp/ui_atlas.o .obj/ppsspp/TestRunner.o .obj/ppsspp/mainwindow.o .obj/ppsspp/qrc_desktop_assets.o .obj/ppsspp/ctrldisasmview.o .obj/ppsspp/ctrlmemview.o .obj/ppsspp/ctrlregisterlist.o .obj/ppsspp/ctrlvfpuview.o .obj/ppsspp/debugger_disasm.o .obj/ppsspp/debugger_displaylist.o .obj/ppsspp/debugger_memory.o .obj/ppsspp/debugger_memorytex.o .obj/ppsspp/debugger_vfpu.o .obj/ppsspp/moc_QtMain.o .obj/ppsspp/moc_mainwindow.o .obj/ppsspp/moc_ctrldisasmview.o .obj/ppsspp/moc_ctrlmemview.o .obj/ppsspp/moc_ctrlregisterlist.o .obj/ppsspp/moc_ctrlvfpuview.o .obj/ppsspp/moc_debugger_disasm.o .obj/ppsspp/moc_debugger_displaylist.o .obj/ppsspp/moc_debugger_memory.o .obj/ppsspp/moc_debugger_memorytex.o .obj/ppsspp/moc_debugger_vfpu.o .obj/ppsspp/qrc_desktop_assets.o    -L/home/serge/ppsspp/Qt -L/home/serge/ppsspp/Qt/../ffmpeg/linux/x86_64/lib/ -L/usr/lib/x86_64-linux-gnu -L/usr/X11R6/lib64 -lCore -lGPU -lCommon -lNative -ldl -lrt -lavformat -lavcodec -lavutil -lswresample -lswscale -lz -lSDL2 -lQtOpenGL -lQtGui -lQtCore -lGL -lpthread 
.obj/ppsspp/qrc_desktop_assets.o: In function `qInitResources_desktop_assets()':
qrc_desktop_assets.cpp:(.text+0x0): multiple definition of `qInitResources_desktop_assets()'
.obj/ppsspp/qrc_desktop_assets.o:qrc_desktop_assets.cpp:(.text+0x0): first defined here
.obj/ppsspp/qrc_desktop_assets.o: In function `qCleanupResources_desktop_assets()':
qrc_desktop_assets.cpp:(.text+0x30): multiple definition of `qCleanupResources_desktop_assets()'
.obj/ppsspp/qrc_desktop_assets.o:qrc_desktop_assets.cpp:(.text+0x30): first defined here
.obj/ppsspp/qrc_desktop_assets.o:(.bss+0x0): multiple definition of `qCleanupResources_desktop_assets__dest_instance__'
.obj/ppsspp/qrc_desktop_assets.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [ppsspp] Error 1
make[1]: Leaving directory `/home/serge/ppsspp/Qt'
make: *** [sub-PPSSPP-pro-make_default-ordered] Error 2

ppssppsdl build okay. Debian Wheezy.

**Comment by xsacha** [comment]
You are recompiling when the assets haven't been cleaned up is all that error is saying. If you do a clean build and recompile it will work.
Qmake is meant to do this automatically of course.
