### ISSUE TITLE
Having same issues as #1853, don't understand how to fix. Me & My Katamari on Android.

### ISSUE THREAD

**Issue by ElChupablabla** [hrydgard/ppsspp#7228]
Hi i know the issue was closed, however i am having the same exact problem and don't know how to fix it. Running on a Samsung Galaxy Tab 3. I am dead tired so i will be posting a log later. Someone said it was due to an iso compression issue but I don't know how to address that if it even is the same issue. #1853

**Comment by unknownbrackets** [comment]
The Play store only has stable versions.  I think the problem here was just that the latest buildbot version was not tried.  If you still experience this in 1.0 or in the latest buildbot versions (which will not be found on the Play store), please comment.

-[Unknown]

**Comment by SpawnHackk** [comment]
Me and My Katamari - hangs on all devices and on all versions of android emulator immediately after entering the name of the player.

**Comment by hrydgard** [comment]
@SpawnHackk If you mean when naming the first island, for some reason you can get past that by changing the rendering mode to Read Framebuffer, then afterwards switch back.
