### ISSUE TITLE
D3D is not working

### ISSUE THREAD

**Issue by Kazajin** [hrydgard/ppsspp#7230]
I can't see UI and when game is loaded ppsspp crushes
It's my log:

59:22:546 EmuThread.cpp:169 I[BOOT]: Done.
59:27:890 Config.cpp:1156 I[LOAD]: Failed to read C:\Documents and Settings\Admin\Рабочий стол\Новая папка\memstick/PSP/SYSTEM/UCES00356_ppsspp.ini. No game-specific settings found, using global defaults.
59:27:890 System.cpp:351 I[BOOT]: PPSSPP v0.9.9.1-1303-g442fe9c Windows 32 bit
59:27:890 MemMap.cpp:277 I[MM]: Found valid memory base at 08400000 after 30 tries.
59:27:890 MemMap.cpp:338 I[MM]: Memory system initialized. RAM at 05E60000 (mirror at 0 @ 10400000, uncached @ 10400000)
59:27:890 PSPLoaders.cpp:168 I[LOAD]: UCES00356 : TEKKEN DARK RESURRECTION
59:27:906 Config.cpp:1156 I[LOAD]: Failed to read C:\Documents and Settings\Admin\Рабочий стол\Новая папка\memstick/PSP/SYSTEM/UCES00356_ppsspp.ini. No game-specific settings found, using global defaults.
59:27:906 PSPLoaders.cpp:210 I[LOAD]: Loading disc0:/PSP_GAME/SYSDIR/EBOOT.BIN...
59:27:906 HLE\sceKernelMemory.cpp:431 I[KERNEL]: Kernel and user memory pools initialized
59:27:984 HLE\sceKernel.cpp:151 I[KERNEL]: Kernel initialized.
59:28:281 Util\BlockAllocator.cpp:381 I[HLE]: -----------
59:28:281 Util\BlockAllocator.cpp:385 I[HLE]: Block: 08800000 - 08804000 size 00004000 taken=1 tag=usersystemlib
59:28:281 Util\BlockAllocator.cpp:385 I[HLE]: Block: 08804000 - 09bbeb00 size 013bab00 taken=1 tag=ELF/tkpsp
59:28:281 Util\BlockAllocator.cpp:385 I[HLE]: Block: 09bbeb00 - 0c000000 size 02441500 taken=0 tag=(untitled)
59:28:281 Util\BlockAllocator.cpp:387 I[HLE]: -----------
59:28:687 HLE\ReplaceTables.cpp:961 I[HLE]: Replaced memcpy at 08a6a744 with hash 8c3fd997a544d0b1
59:28:687 HLE\sceKernelModule.cpp:1034 I[LOAD]: Module tkpsp: 08b7e390 08a77744 08a7775c
59:28:687 HLE\sceKernelModule.cpp:1235 I[LOAD]: Exporting ent 0 named tkpsp, 2 funcs, 3 vars, resident 08a77c1c
59:28:687 HLE\sceKernelModule.cpp:1557 I[LOAD]: Module entry: 089f38a8
59:28:687 root         W[G3D]: Directx9\TextureCacheDX9.cpp:89 Failed to get the device caps!
59:28:828 root         N[BOOT]: EmuScreen.cpp:138 Loading C:/Documents and Settings/Admin/Рабочий стол/PSP GAMEZ/tekkendr.cso...
59:28:828 root         I[KERNEL]: HLE\sceKernelThread.cpp:2176 276=sceKernelCreateThread(name=user_main, entry=089f3964, prio=20, stacksize=262144)
59:28:828 root         I[KERNEL]: HLE\sceKernelThread.cpp:2275 sceKernelStartThread(thread=276, argSize=33, argPtr=0bfffed0)
59:28:828 root         I[KERNEL]: HLE\sceKernelThread.cpp:2316 __KernelReturnFromThread: 0
59:28:875 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2176 280=sceKernelCreateThread(name=, entry=088a79a8, prio=10, stacksize=1024)
59:28:875 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2275 sceKernelStartThread(thread=280, argSize=4, argPtr=08b82df4)
59:28:875 user_main    W[LOAD]: HLE\sceKernelModule.cpp:1684 sceKernelLoadModule: unsupported options size=00000014, flags=00000007, pos=0, access=1, data=1, text=1
59:28:875 user_main    I[MODULE]: HLE\sceKernelModule.cpp:852 ~SCE module, skipping header
59:28:875 user_main    I[MODULE]: HLE\sceKernelModule.cpp:866 Loading module sceSAScore with version 0103, devkit 00000000
59:28:875 user_main    I[HLE]: ELF\PrxDecrypter.cpp:308 Missing key 59, cannot decrypt module
59:28:875 user_main    I[MODULE]: HLE\sceKernelModule.cpp:1727 282=sceKernelLoadModule(name=disc0:/PSP_GAME/USRDIR/sc_sascore.prx,flag=00000000,00000014,00000001,00000001,position = 00000000)
59:28:875 user_main    I[MODULE]: HLE\sceKernelModule.cpp:1761 sceKernelStartModule(282,asize=00000000,aptr=00000000,retptr=00000000,00000000): faked (undecryptable module)
59:28:875 user_main    W[LOAD]: HLE\sceKernelModule.cpp:1684 sceKernelLoadModule: unsupported options size=00000014, flags=00000007, pos=0, access=1, data=1, text=1
59:28:875 user_main    I[MODULE]: HLE\sceKernelModule.cpp:852 ~SCE module, skipping header
59:28:875 user_main    I[MODULE]: HLE\sceKernelModule.cpp:866 Loading module sceAudiocodec_Driver with version 0103, devkit 00000000
59:28:875 user_main    I[HLE]: ELF\PrxDecrypter.cpp:308 Missing key 59, cannot decrypt module
59:28:875 user_main    I[MODULE]: HLE\sceKernelModule.cpp:1727 283=sceKernelLoadModule(name=disc0:/PSP_GAME/USRDIR/audiocodec.prx,flag=00000000,00000014,00000001,00000001,position = 00000000)
59:28:875 user_main    I[MODULE]: HLE\sceKernelModule.cpp:1761 sceKernelStartModule(283,asize=00000000,aptr=00000000,retptr=00000000,00000000): faked (undecryptable module)
59:28:875 user_main    W[LOAD]: HLE\sceKernelModule.cpp:1684 sceKernelLoadModule: unsupported options size=00000014, flags=00000007, pos=0, access=1, data=2, text=2
59:28:875 user_main    I[MODULE]: HLE\sceKernelModule.cpp:852 ~SCE module, skipping header
59:28:875 user_main    I[MODULE]: HLE\sceKernelModule.cpp:866 Loading module sceATRAC3plus_Library with version 0103, devkit 00000000
59:28:875 user_main    I[HLE]: ELF\PrxDecrypter.cpp:308 Missing key 5B, cannot decrypt module
59:28:875 user_main    I[MODULE]: HLE\sceKernelModule.cpp:1727 284=sceKernelLoadModule(name=disc0:/PSP_GAME/USRDIR/libatrac3plus.prx,flag=00000000,00000014,00000002,00000002,position = 00000000)
59:28:875 user_main    I[MODULE]: HLE\sceKernelModule.cpp:1761 sceKernelStartModule(284,asize=00000000,aptr=00000000,retptr=00000000,00000000): faked (undecryptable module)
59:28:875 user_main    W[LOAD]: HLE\sceKernelModule.cpp:1684 sceKernelLoadModule: unsupported options size=00000014, flags=7f800001, pos=0, access=1, data=1, text=1
59:28:875 user_main    I[MODULE]: HLE\sceKernelModule.cpp:852 ~SCE module, skipping header
59:28:875 user_main    I[MODULE]: HLE\sceKernelModule.cpp:866 Loading module sceVideocodec_Driver with version 0103, devkit 00000000
59:28:875 user_main    I[HLE]: ELF\PrxDecrypter.cpp:308 Missing key 59, cannot decrypt module
59:28:875 user_main    I[MODULE]: HLE\sceKernelModule.cpp:1727 285=sceKernelLoadModule(name=disc0:/PSP_GAME/USRDIR/videocodec.prx,flag=00000000,00000014,00000001,00000001,position = 00000000)
59:28:875 user_main    I[MODULE]: HLE\sceKernelModule.cpp:1761 sceKernelStartModule(285,asize=00000000,aptr=00000000,retptr=00000000,00000000): faked (undecryptable module)
59:28:875 user_main    W[LOAD]: HLE\sceKernelModule.cpp:1684 sceKernelLoadModule: unsupported options size=00000014, flags=7f800001, pos=0, access=1, data=1, text=1
59:28:875 user_main    I[MODULE]: HLE\sceKernelModule.cpp:852 ~SCE module, skipping header
59:28:875 user_main    I[MODULE]: HLE\sceKernelModule.cpp:866 Loading module sceMpegbase_Driver with version 0103, devkit 00000000
59:28:875 user_main    I[HLE]: ELF\PrxDecrypter.cpp:308 Missing key 59, cannot decrypt module
59:28:875 user_main    I[MODULE]: HLE\sceKernelModule.cpp:1727 286=sceKernelLoadModule(name=disc0:/PSP_GAME/USRDIR/mpegbase.prx,flag=00000000,00000014,00000001,00000001,position = 00000000)
59:28:875 user_main    I[MODULE]: HLE\sceKernelModule.cpp:1761 sceKernelStartModule(286,asize=00000000,aptr=00000000,retptr=00000000,00000000): faked (undecryptable module)
59:28:875 user_main    W[LOAD]: HLE\sceKernelModule.cpp:1684 sceKernelLoadModule: unsupported options size=00000014, flags=7f800001, pos=0, access=1, data=2, text=2
59:28:875 user_main    I[MODULE]: HLE\sceKernelModule.cpp:852 ~SCE module, skipping header
59:28:875 user_main    I[MODULE]: HLE\sceKernelModule.cpp:866 Loading module sceMpeg_library with version 0104, devkit 00000000
59:28:875 user_main    I[HLE]: ELF\PrxDecrypter.cpp:308 Missing key 5B, cannot decrypt module
59:28:875 user_main    I[MODULE]: HLE\sceKernelModule.cpp:1727 287=sceKernelLoadModule(name=disc0:/PSP_GAME/USRDIR/mpeg.prx,flag=00000000,00000014,00000002,00000002,position = 00000000)
59:28:875 user_main    I[MODULE]: HLE\sceKernelModule.cpp:1761 sceKernelStartModule(287,asize=00000000,aptr=00000000,retptr=00000000,00000000): faked (undecryptable module)
59:28:875 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2176 290=sceKernelCreateThread(name=nuFileAsync, entry=08a20f40, prio=13, stacksize=4096)
59:28:875 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2275 sceKernelStartThread(thread=290, argSize=0, argPtr=00000000)
59:28:921 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2176 293=sceKernelCreateThread(name=, entry=088f2774, prio=3e, stacksize=6144)
59:28:921 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2275 sceKernelStartThread(thread=293, argSize=20, argPtr=08c39ff0)
59:28:921 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2176 296=sceKernelCreateThread(name=, entry=08951b88, prio=40, stacksize=7168)
59:28:921 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2275 sceKernelStartThread(thread=296, argSize=0, argPtr=00000000)
59:28:921 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2176 299=sceKernelCreateThread(name=, entry=088a735c, prio=42, stacksize=1280)
59:28:921 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2275 sceKernelStartThread(thread=299, argSize=4, argPtr=0bffea80)
59:28:937 user_main    E[HLE]: HLE\sceOpenPSID.cpp:25 UNTESTED sceOpenPSIDGetOpenPSID(201321040)
59:28:968 idle0        E[G3D]: Directx9\FramebufferDX9.cpp:190 Failed to create drawpixels texture
59:28:968 idle0        E[G3D]: Directx9\FramebufferDX9.cpp:331 DrawActiveTexture() failed: 8876086c
59:29:031 idle0        E[G3D]: Directx9\FramebufferDX9.cpp:190 Failed to create drawpixels texture
59:29:031 idle0        E[G3D]: Directx9\FramebufferDX9.cpp:331 DrawActiveTexture() failed: 8876086c
59:29:031 user_main    E[SCEGE]: Directx9\FramebufferDX9.cpp:437 Error creating FBO! 960 x 544
59:29:031 user_main    I[SCEGE]: Common\FramebufferCommon.cpp:329 Creating FBO for 00044000 : 480 x 272 x 1
59:29:031 user_main    W[G3D]: Common\FramebufferCommon.cpp:520 Memcpy fbo upload 04444000 -> 04044000
59:29:031 user_main    E[G3D]: Directx9\FramebufferDX9.cpp:190 Failed to create drawpixels texture
59:29:031 user_main    E[G3D]: Directx9\FramebufferDX9.cpp:331 DrawActiveTexture() failed: 8876086c
59:29:078 user_main    E[SCEGE]: Directx9\FramebufferDX9.cpp:437 Error creating FBO! 960 x 544
59:29:078 user_main    I[SCEGE]: Common\FramebufferCommon.cpp:329 Creating FBO for 00000000 : 480 x 272 x 1
59:29:078 user_main    E[G3D]: Directx9\FramebufferDX9.cpp:190 Failed to create drawpixels texture
59:29:078 user_main    E[G3D]: Directx9\FramebufferDX9.cpp:331 DrawActiveTexture() failed: 8876086c
59:29:156 user_main    I[SCESAS]: HLE\sceSas.cpp:106 sceSasInit(09bb8c80, 768, 32, 0, 44100)
59:29:156 user_main    W[SCESAS]: HLE\sceSas.cpp:484 sceSasRevEVOL(09bb8c80, 32767, 32767): invalid volume
59:29:156 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2176 315=sceKernelCreateThread(name=SasCore thread, entry=08a014bc, prio=10, stacksize=65536)
59:29:156 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2275 sceKernelStartThread(thread=315, argSize=0, argPtr=00000000)
59:29:156 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2176 317=sceKernelCreateThread(name=ATRAC3 play thread, entry=08a0524c, prio=11, stacksize=65536)
59:29:375 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2176 319=sceKernelCreateThread(name=, entry=088e7d50, prio=41, stacksize=2048)
59:29:375 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2275 sceKernelStartThread(thread=319, argSize=0, argPtr=00000000)
59:29:406 user_main    I[UTIL]: Dialog\PSPSaveDialog.cpp:85 sceUtilitySavedataInitStart(08b7ba10) - AUTOLOAD (0)
59:29:406 user_main    I[UTIL]: Dialog\PSPSaveDialog.cpp:86 sceUtilitySavedataInitStart(08b7ba10) : Game key (hex): 01AF6F00020070D52E2412C7E1FF83BA
59:29:453 user_main    E[G3D]: Directx9\TransformPipelineDX9.cpp:248 Failed to create vertex declaration!
59:29:453 user_main    I[G3D]: Directx9\TextureCacheDX9.cpp:1727 Failed to create D3D texture

**Comment by unknownbrackets** [comment]
There's been no feedback in a while - and it looks like that probably fixed the issue.  Closing.  If this is still an issue, please comment and we'll reopen.

-[Unknown]
