### ISSUE TITLE
2D Games Tends to Slow

### ISSUE THREAD

**Issue by RyanBram** [hrydgard/ppsspp#7238]
Hi, PPSSPP Developers,
This is my first time submitting issue for PPSSPP.

I tried PPSSPP for many games from resource hungry games such as Warriors Orochi series until simple 2D games such as Tales of Eternia. Generally all of the game that I tried is playable without major issues. The only thing that I found is generally PPSSPP will run very slow when I am playing 2D titles, such as Tales of Eternia and Harvest Moon Boy & Girl even with frameskip activated. This issue not appear if I am playing 3D title, such as Warriors Orochi or Final Fantasy III.

I tried any setting that I knew, but no big difference in performance.
## 

_Windows 7 - 64 bit
PPSSPP 0.9.9.1
Intel Core i3 2350M Sandy Bridge
Intel(R) HD Graphics Family GT2
500 GB HDD
6 GB of RAM_

**Comment by unknownbrackets** [comment]
Not sure what there is to do here.

The software renderer is more stable now, but still very slow.  It will likely only run a few games at or near full speed on a 2350M.  On faster processors with weak GPUs, it's possible it may outperform GLES for Final Fantasy 2.  It could get faster, but that's a separate effort.

It's possible the Direct3D 11 backend may work better for you on an Intel GPU.  It is in several cases faster than the GLES backend.

We already have issues about multithreading and about software rendering, so I'm closing this.

-[Unknown]
