### ISSUE TITLE
Support for CFW Plugins

### ISSUE THREAD

**Issue by thiagokokada** [hrydgard/ppsspp#724]
Support for XMB and VSH(?) plugins woudn't make sense, but support for GAME plugins would, so we can use plugins like CWCheat, translation projects like [this](http://projectdiva.wikispaces.com/Translation+Patch+%28extend%29) one for Project DIVA Extended or even bypass some nasty copy protection or anything like that.

**Comment by VeGas-Gh0st** [comment]
i  just need to english patch Earth Defence Forces 2 Portable (Jap)

here is an amazing writeup

http://zenade.angelfire.com/EDF/EDF2.html

**Comment by ToppestOfDogs** [comment]
Why was this closed? I was actually about to make an issue before I found this.
I'm hoping to be able to use these patches in PPSSPP: https://github.com/TheOfficialFloW/RemasteredControls
These plugins patch several games to use the right stick for the Vita. The Peace Walker plugin works better than the cheat codes for PPSSPP, and Portable OPS doesn't have a cheat code alternative at all. I really want to play through Portable OPS but not on a handheld.
