### ISSUE TITLE
[Feature Request] Allow Nvidia DSR technology

### ISSUE THREAD

**Issue by ppmeis** [hrydgard/ppsspp#7242]
Since the arrival of brand new 900 series of Nvidia graphic cards, there's a new technology avaible for all of us: Dynamic Super Resolution, known as DSR.

Basically DSR technology allows to use up to 4K resolution under a native 1080p display, as a result you will have better graphics experience.

Actually can't handle DSR because it detects native display resolution and we could only use this one on fullscreen.

For example, Dolphin can handle this, because you can choose fullscreen resolution. Here Nvidia "fakes" native resolution up to 4K, and the rescaling it to real native resolution. Even more, under opengl/d3d ini config file you can enable "custom" internal resolution.

So, is there any way to implement this to PPSSPP? If you need tester I could be one :).

Regards.

**Comment by ppmeis** [comment]
I figured out I can't compare between 4K and 1080p, because even if I set my desktop to 4k, emulator make fullscreen at 1080p :/.

**Comment by ppmeis** [comment]
Anyone could make a test build for me supporting custom fullscreen resolution for compare purpose? I think writing a function in the ini config file like FullScreenH and FullScreenW to set it is mor than enough for this test.

@hrydgard @unknownbrackets what do you think?

**Comment by ppmeis** [comment]
any one?

**Comment by DonelBueno** [comment]
PPSSPP already does this. 4x Internal resolution is 1080p, 8x internal resolution is 2160p (4k). Just set the internal resolution to 8x and your full screen resolution to 1080p. Take an screenshot of the emulator in full screen 1080p with 4x internal resolution and then 8x internal resolution to compare the effect.

**Comment by ppmeis** [comment]
@DonelBueno no it doesn't. Internally it scales up to 10x, but it not able to use more than 1080p fullscreen resolution, even by forcing it in desktop.

**Comment by DonelBueno** [comment]
Your talking about the window resolution, wich means the resolution of your display, I'm talking about the internal resolution, wich means the resolution the game is calculated in. What DSR does is render the game at a higher resolution than your display, that is, the internal resolution of game is rendered at 3840x2160 and then showed at 1920x1080, for example. In this way, the image is smoothed out. That is exactaly what PPSSPP does when you choose a higher rendering resolution than your display resolution. DSR is just a fancy name for downsampling.

**Comment by ppmeis** [comment]
When I rec a video with shadowplay with any other games at 4K, recorded video resolution is 4K. This does NOT happen with PPSSPP, even if I force desktop to show 4K, so when I rec at fullscreen it will be at 1080p. Maybe whe could add borderless fullscreen resolution like Dolphin does.

Oh an Dolphin rec at 4K.

**Comment by ppmeis** [comment]
Notice that I know it because a message is displayed on PPSSPP in the top of the screen ingame, it says internal resolution x10 and screen resolution 1920x1080.

**Comment by unknownbrackets** [comment]
Well, maybe someone will do something here eventually, but it's not super interesting to be honest - sorry.  Anyway, my card doesn't support it so it won't be fun to figure out if it's even working.

Just for a quick explanation of the differences, here's what PPSSPP does:

Render to ~4K  ->  Downsample this to window/screen resolution  ->  Display

Here's what this option would theoretically do (I'm just guessing from the documentation as my card does not support it, but it's an educated/informed guess):

Render to ~4K  ->  Copy (same res) to window/screen buffer  ->  Driver downsamples  ->  Display

The differences are as follows:

1. Programs that hook the backbuffer (presumably shadowplay) will get the smaller resolution with PPSSPP's approach.
2. The driver includes a dedicated shader to downsample with, which is supposed to be better quality.  Discussion here about this and using PPSSPP's post-shaders is relevant.
3. PPSSPP's approach is probably more efficient and presumably requires less VRAM.

Personally, I view the driver approach as a "hack" to basically slug the feature PPSSPP already has into software that wasn't designed to have the feature initially.

-[Unknown]

**Comment by DonelBueno** [comment]
PPSSPP uses bilinear filtering for downsampling? Bicubic would be a better choice, although it's probably a little bit heavier.

**Comment by unknownbrackets** [comment]
Well, PPSSPP just uses GL_LINEAR by default, but I think it might also use anisotropic filtering for those blits?  But sure, you can do anything you want with post shaders.

-[Unknown]

**Comment by DonelBueno** [comment]
Render to ~4K -> Downsample this to window/screen resolution -> Display
vs
Render to ~4K -> Copy (same res) to window/screen buffer -> Driver downsamples -> Display

Does anyone know if the later method increases the input lag compared to the first one?

**Comment by unknownbrackets** [comment]
I would assume that the copy at the same res would take longer than a copy that desamples, just because of the memory writes (we're talking 1/4 as much memory writes when downsampling, and the actual downsampling is probably practically free during that.)

But, can't say for sure without testing.  Driver might have some optimized path for it or who knows.

Either way, actual rendering (at ~4K) is probably a greater source of input lag than the display step.  And as long as you're getting 100% speed, slower might actually be *better* for input lag, unless you turn on "real time sync" in settings.

Please note that on Windows, real time sync will drink your battery on a laptop, and peg a single cpu core.  But it improves lag because otherwise you're playing in 16.66ms "buckets" of time (meaning if you have AWESOME hardware, you might have an input/network lag of >16ms.)  The real time sync option reduces this to a max lag of 2ms or so, iirc. (can't do much better on Windows, it isn't really designed for real time performance like a console is, after all - just doesn't have thread timing capable of better resolution.)

-[Unknown]
