### ISSUE TITLE
x86 jit bug in Monhun Nikki Poka Poka Ailu Mura G

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#7245]
enableVFPUSIMD = true;
![01](https://cloud.githubusercontent.com/assets/3481559/5586912/96018b18-9116-11e4-8220-ddcd978f2b36.png)

enableVFPUSIMD = false;
![02](https://cloud.githubusercontent.com/assets/3481559/5586914/9c246a2e-9116-11e4-89ff-0cca02d35300.png)

**Comment by daniel229** [comment]
It's case 0 in Comp_VPFX;Is it strange,not in your list?

**Comment by unknownbrackets** [comment]
No, that one isn't safe to disable, because it's prefix handling.  Most of the time that will cause other vfpu instructions to not use jit and fall back to the interpreter, because the prefix values will be unknown.

So, it wasn't any of the ones in my list?

-[Unknown]

**Comment by daniel229** [comment]
No.

**Comment by daniel229** [comment]
Double check,it's in your list,Comp_VecDo3

**Comment by unknownbrackets** [comment]
Okay, that's helpful.  I don't think vmul is broken so most likely the regcache still has an issue or two left.  I've disabled for now while we figure out what causes this issue and fix it.

-[Unknown]

**Comment by unknownbrackets** [comment]
Does this fix it?

https://github.com/unknownbrackets/ppsspp/compare/jit-minor?expand=1

-[Unknown]

**Comment by daniel229** [comment]
Great,that fixes it.
