### ISSUE TITLE
Linux  Ad-Hoc Multiplayer error: HLE/sceNetAdhoc.cpp:375 Socket error (13) when binding port 10

### ISSUE THREAD

**Issue by lightfirst** [hrydgard/ppsspp#7247]
some game  Ad-Hoc Multiplayer work on PPSSPP windows build but not Linux. 
Get this error:
27:14:513 user_main    E[NET]: HLE/sceNetAdhoc.cpp:375 Socket error (13) when binding port 10

**Comment by lightfirst** [comment]
anyone know how to run PPSSPP as root on android?

**Comment by i30817** [comment]
just change the port. Running anything as rot that doesn't need it is a bad idea.

**Comment by xiushudongfang** [comment]
Add this to src/org.ppsspp.ppsspp/PpssppActivity.java
public static boolean upgradeRootPermission(String pkgCodePath) {  
    Process process = null;  
    DataOutputStream os = null;  
    try {  
        String cmd="chmod 777 " + pkgCodePath;  
        process = Runtime.getRuntime().exec("su"); //切换到root帐号  
        os = new DataOutputStream(process.getOutputStream());  
        os.writeBytes(cmd + "\n");  
        os.writeBytes("exit\n");  
        os.flush();  
        process.waitFor();  
    } catch (Exception e) {  
        return false;  
    } finally {  
        try {  
            if (os != null) {  
                os.close();  
            }  
            process.destroy();  
        } catch (Exception e) {  
        }  
    }  
    return true;  
}  


public void onCreate(Bundle savedInstanceState) {  
    super.onCreate(savedInstanceState);  
    setContentView(R.layout.main);  
    //当前应用的代码执行目录  
    upgradeRootPermission(getPackageCodePath());  
}

**Comment by ANR2ME** [comment]
This is not really a bug, as the port binded by PSP's game are varies (depend on the game) and usually in reserved area (<1024) to maintain compatibility with the ports used on real PSP these port aren't mapped to a different port, otherwise they won't be able to communicate with each other.
These ports can't be changed by user as it's the game that decides which port they listen to.

**Comment by hrydgard** [comment]
Hm, does that "su" trick really work on rooted phones? Interesting. I could add it, it likely just does nothing on non-rooted phones.

With regards to games and ports, we could have a mode that isn't compatible with the real PSP but tunnels or remaps to different ports.

**Comment by unknownbrackets** [comment]
We should at least remap < 1024 to some other range, because that won't work on most platforms without privileges except Windows (e.g. Linux, Mac, Android, Symbian, etc.)

-[Unknown]

**Comment by lightfirst** [comment]
unfortunately xiushudongfang‘s code no help. I try change the port: can entry lobby but cant find player. perhaps tunnels or remaps to different ports will help.

**Comment by ernestbone** [comment]
how did u change the port @lightfirst

**Comment by Cloudef** [comment]
Never run complex programs, especially graphical ones as root. You can instead give ppsspp capability to bind < 1024 ports with `setcap 'cap_net_bind_service=+ep' /usr/bin/ppsspp`

**Comment by hrydgard** [comment]
We have a port offset option now, would recommend to use that instead.

**Comment by Cloudef** [comment]
Unless you want to play with real PSP :)
