### ISSUE TITLE
x86jit bug in Rockman Dash 2

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#7253]
affect both 32bit and 64bit build since https://github.com/unknownbrackets/ppsspp/commit/ddc90ee550567302c85fa3ee13a7c776f6cc9dbc

wrong
![01](https://cloud.githubusercontent.com/assets/3481559/5595710/5a93bc36-92b5-11e4-93c9-c5d7a8650dd9.png)

correct
![02](https://cloud.githubusercontent.com/assets/3481559/5595709/5a907aee-92b5-11e4-8af3-e7ee61758605.png)

**Comment by unknownbrackets** [comment]
Hmm, I dunno, could it be a sign issue?  Or NAN/INF in some way?  Maybe it needs to start at +0.00 and add the rest...

-[Unknown]

**Comment by unknownbrackets** [comment]
Sorry, vavg was just totally broken.  It should probably work now.

-[Unknown]

**Comment by daniel229** [comment]
Fixed.
