### ISSUE TITLE
Bokujou Monogatari small graphical glitch

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#7255]
The texture of now loading  is wrong in openGL and D3D9,test builds between the recently and 0.91,seem never work.
openGL
![01](https://cloud.githubusercontent.com/assets/3481559/5596643/7d3e0c8c-92ce-11e4-871c-3b9214576330.png)

software GPU
![02](https://cloud.githubusercontent.com/assets/3481559/5596647/891c1850-92ce-11e4-803b-0b5dee1c0822.png)

GEdebugger
![03](https://cloud.githubusercontent.com/assets/3481559/5596655/96e3494a-92ce-11e4-9d74-a8bdfdf44525.png)
![04](https://cloud.githubusercontent.com/assets/3481559/5596656/96e4d706-92ce-11e4-8f33-77c0aa26cbc0.png)
![05](https://cloud.githubusercontent.com/assets/3481559/5596654/96e2a4f4-92ce-11e4-99fa-0ba8184d991e.png)

**Comment by unknownbrackets** [comment]
Hmm.  Weird.  Can I see the vertices tab?  I note that nothing is lit up in red in the texture preview.

-[Unknown]

**Comment by daniel229** [comment]
vertices tab?
![01](https://cloud.githubusercontent.com/assets/3481559/5604275/faf5ce52-93ec-11e4-8b0a-4de218c3c6e1.png)

**Comment by daniel229** [comment]
Frame dump
https://gist.github.com/daniel229/aeffe8f9c6a1d2bbf8e9

**Comment by daniel229** [comment]
Step prim
https://cloud.githubusercontent.com/assets/3481559/5604326/c5fc0168-93f0-11e4-995d-c9147a8f46e5.png

https://cloud.githubusercontent.com/assets/3481559/5604327/c5fd31fa-93f0-11e4-8c7d-d6549e705545.png

![03](https://cloud.githubusercontent.com/assets/3481559/5604328/c5fec48e-93f0-11e4-854b-a4afbf29adfe.png

https://cloud.githubusercontent.com/assets/3481559/5604330/c5ffa872-93f0-11e4-85c5-cf00139c49f1.png

https://cloud.githubusercontent.com/assets/3481559/5604329/c5ff83f6-93f0-11e4-8b23-2dd18e287770.png

https://cloud.githubusercontent.com/assets/3481559/5604325/c5fbb4ce-93f0-11e4-90dc-549f6cec25c4.png

https://cloud.githubusercontent.com/assets/3481559/5604331/c622acc8-93f0-11e4-8b0c-70ecffb3fc86.png

**Comment by unknownbrackets** [comment]
Hmm, I somehow doubt it'll help, but turning off vertex cache doesn't do anything does it?

-[Unknown]

**Comment by daniel229** [comment]
No,it doesn't.
