### ISSUE TITLE
IOS 7.0.4 Jail Broken phone no longer able to play any game.

### ISSUE THREAD

**Issue by jianmingyong** [hrydgard/ppsspp#7259]
I have a iPhone 4S Jail Broken at ios 7.0.4.
It used to work smoothly until recent updates and the ios 8 release.

I could have update the phone but it is tedious to re-jail break again.

What happen is that the app crashes after I select any psp game.
I have also make the setting default and reinstall the app tons of time but no luck.

**Comment by brujo5** [comment]
update to ios 8.1.2, taig jalibreak is very stable.

**Comment by thedax** [comment]
Closing in favour of https://github.com/hrydgard/ppsspp/issues/7360.
