### ISSUE TITLE
Huge Crash Fix

### ISSUE THREAD

**Issue by zombieman998877** [hrydgard/ppsspp#7266]
Please fix this I am trying to play Dragon Ball Z: Shin Budokai and when I press on it the buttons graphics are missing and the app crashes. So Pleeease fix this

**Comment by hrydgard** [comment]
The game works fine on PC at least. What device are you running on?

**Comment by zombieman998877** [comment]
I'm running on iOS 7 jailbreak

**Comment by zombieman998877** [comment]
Now it crashes on startup

**Comment by thedax** [comment]
Closing in favour of https://github.com/hrydgard/ppsspp/issues/7360.
