### ISSUE TITLE
Soul Calibur BD white screen on critical finish

### ISSUE THREAD

**Issue by darkzer0** [hrydgard/ppsspp#7274]
Guys I detect a little problem in this game. When i try setsuka, casandra, and tira critical finish screen become white (with "disable slower effect" on). If i turn off "disable slower effect" character appear, but gameplay become very laggy.

**Comment by Bigpet** [comment]
I don't think there is much we can help you with. The option "disable slower effect" does exactly what the name says. It disables effects that are slow to execute on many devices. That means of course that there's some inaccuracies when you enable it. And when you disable it, it might get slower.

**Comment by darkzer0** [comment]
Yeah, but that slow very drastic. Near freeze. But after that, emulator goes fine. Thx for your attention.

**Comment by darkzer0** [comment]
Can u try that? Are this problem caused by my phone?

**Comment by Bigpet** [comment]
I'm sorry I don't own that game

**Comment by unknownbrackets** [comment]
Unfortunately, some of the slower effects really are, well, slower.  Especially on weaker GPUs.  There's a reason we made it an option.

The PSP has pretty bare-metal access to the hardware so it can do some things much faster than even modern GPUs can do.

It's possible that it could be optimized but it'll probably always be very slow.  Unfortunately, I don't have this game either.  You can try to help us by telling us what it's even doing using this tutorial:
https://github.com/hrydgard/ppsspp/wiki/How-to-find-a-graphic-issue-with-the-GE-debugger

-[Unknown]

**Comment by darkzer0** [comment]
Ok, thx for your attention.
