### ISSUE TITLE
To Heart 2 Portable graphical problem

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#7277]
1.The bottom part of the screen is no right after resize.
normal
![01](https://cloud.githubusercontent.com/assets/3481559/5608477/fe7c8182-94bf-11e4-9e88-a6b8a87d189a.png)

resize
![02](https://cloud.githubusercontent.com/assets/3481559/5608476/fe79c41a-94bf-11e4-9ed8-6874ea0377e8.png)

softwareGPU
![03](https://cloud.githubusercontent.com/assets/3481559/5608480/0b8eabac-94c0-11e4-94f7-36d0e0e7edaa.png)

2.Get blackscreen often,seems like a block transfer problem,JPCSP fixed in https://code.google.com/p/jpcsp/source/detail?r=3371,
set a breakpoint 0x04000000 size 0x00FFFFFF  only  hit gu_update_stall()

**Comment by unknownbrackets** [comment]
Oh no, it's using swizzled space?  Ugh.  Can you change this line in GLES_GPU.cpp to NOTICE_LOG?

DEBUG_LOG(G3D, "Block transfer: %08x/%x -> %08x/%x, %ix%ix%i (%i,%i)->(%i,%i)", srcBasePtr, srcStride, dstBasePtr, dstStride, width, height, bpp, srcX, srcY, dstX, dstY);

That will show what the transfers it's using are.

I guess the resize is guessing the wrong resolution.  When you say resize, is this a feature within the game, or are you resizing the window in the emulator/ppsspp?

For that one, it's FramebufferCommon.cpp:

DEBUG_LOG(G3D, "Est: %08x V: %ix%i, R: %ix%i, S: %ix%i, STR: %i, THR:%i, Z:%08x = %ix%i", gstate.getFrameBufAddress(), viewport_width,viewport_height, region_width, region_height, scissor_width, scissor_height, fb_stride, gstate.isModeThrough(), gstate.isDepthWriteEnabled() ? gstate.getDepthBufAddress() : 0, drawing_width, drawing_height);

-[Unknown]

**Comment by daniel229** [comment]
Block transfer log here during the balckscreen and something showup.
https://gist.github.com/daniel229/0fc0f24d4b18731883d0

it's the ingame resize feature,not ppsspp.
log in FramebufferCommon.cpp
https://gist.github.com/daniel229/a5910bab300b94f879db

**Comment by unknownbrackets** [comment]
That's weird, why is it transferring 360 pixels?  You can try changing this:

```c++
		// Sometimes region is set larger than the VRAM for the framebuffer.
		if (region_width <= fb_stride && region_width > drawing_width && region_height <= MAX_FRAMEBUF_HEIGHT) {
			drawing_width = region_width;
			drawing_height = std::max(drawing_height, region_height);
		}
```

To:

```c++
		// Sometimes region is set larger than the VRAM for the framebuffer.
		if (region_width <= fb_stride && (region_width > drawing_width || (region_width == drawing_width && region_height > drawing_height)) && region_height <= MAX_FRAMEBUF_HEIGHT) {
			drawing_width = region_width;
			drawing_height = std::max(drawing_height, region_height);
		}
```

Not sure if that might break any other games, though.

-[Unknown]

**Comment by daniel229** [comment]
Great,fixes these two issue.

**Comment by daniel229** [comment]
Tested hundreds games with that change,still not found any broken.

**Comment by unknownbrackets** [comment]
Well, that sounds pretty good.  The situation is pretty unlikely, so it's probably an okay heuristic change indeed.  Feels a bit hacky but the entire function does really...

-[Unknown]
