### ISSUE TITLE
The Simpsons Game  crash after title

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#7278]
since https://github.com/unknownbrackets/ppsspp/commit/398646411a1e1f5e03dbc636684e6852e05d8df0 in https://github.com/hrydgard/ppsspp/pull/6974

![07](https://cloud.githubusercontent.com/assets/3481559/5609347/5c78e8fc-94d9-11e4-9092-fd6178a7368b.png)

**Comment by unknownbrackets** [comment]
Does it log any errors?

-[Unknown]

**Comment by daniel229** [comment]
Error decodeing audio
![08](https://cloud.githubusercontent.com/assets/3481559/5609381/46b6d910-94da-11e4-9731-eeaf943bbaec.png)

**Comment by unknownbrackets** [comment]
And, did the title music play / any sound effects in that area correctly before?  Did it also log error decoding?

-[Unknown]

**Comment by daniel229** [comment]
Yes,it play sound before.No decode audio error
![09](https://cloud.githubusercontent.com/assets/3481559/5609539/af44ccbe-94dd-11e4-8f50-b01c87b2449d.png)

**Comment by unknownbrackets** [comment]
Does #6976 help (with latest updates)?

-[Unknown]

**Comment by daniel229** [comment]
Yes,it helps the game.

**Comment by daniel229** [comment]
Fixed in https://github.com/hrydgard/ppsspp/pull/6976
