### ISSUE TITLE
Doko Demo Issho hangs after load save

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#7279]
Looks like it happens in all build that can load save,the oldest build I tested was 0.9.6-53.the much older build can't load save,sometime get lucky it would not hang in release build,debug build always hang.

debug log
https://gist.github.com/daniel229/287aaf00f39513ed8dec

![21](https://cloud.githubusercontent.com/assets/3481559/5610352/02d2ddae-94f1-11e4-8cec-c96aedbc6f59.png)

**Comment by hrydgard** [comment]
Strange, the errors are not coming from the game thread that did the save/load but from "sgx-pcm-th" which sounds like an audio thread, so it's not certain that the problem is related to save/load functionality at all..

**Comment by unknownbrackets** [comment]
26:08:855 sgx-psp-sas- D[KERNEL]: HLE\sceKernelThread.cpp:3260 Context switch: main -> sgx-psp-sas-th (277->304, pc: 0889bae4->088bb81c, woke from hle delay) +240us
26:08:855 sgx-psp-sas- E[CPU]: Mips\MIPSTables.cpp:944 MIPSCompileOp: Invalid instruction 0010000e
26:08:855 sgx-psp-sas- E[MM]: MemmapFunctions.cpp:56 Unknown GetPointer 00000000 PC 00000000 LR 08d23610

It seems like it's going from 088bb81c to 08d23610?  Maybe set a breakpoint at 088bb81c?

-[Unknown]

**Comment by daniel229** [comment]
Seems like it would not hangs if the computer time past the savedata time less than 2 hours.The game has a feature to compare the psp time and the savedata time,if the savedata time older psp time,it would not let you load the save,and tell you to change psp time.After loading the save,it randomly play different BGM.

088bb81c disassembly
![22](https://cloud.githubusercontent.com/assets/3481559/5613552/eb49d36a-9520-11e4-8243-89c13e2c64bd.png)

**Comment by daniel229** [comment]
Follow the 088bb81c the last time hit 
![01](https://cloud.githubusercontent.com/assets/3481559/5622457/dc433826-957e-11e4-975b-32b180f6190c.png)
end here.

**Comment by unknownbrackets** [comment]
Hmm.  Is it calling that from within an interrupt?

-[Unknown]

**Comment by daniel229** [comment]
Sorry,I don't know what you mean.

**Comment by daniel229** [comment]
Fixed in https://github.com/hrydgard/ppsspp/pull/7359
