### ISSUE TITLE
Prince of Persia The Forgotten Sands JPN lockup problem

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#7282]
Since https://github.com/unknownbrackets/ppsspp/commit/0aa7247feaaec564a4233ff502189a97a229d731

Just lockup with Janpanese sound ,English sound is fine in the beginning scene.
![02](https://cloud.githubusercontent.com/assets/3481559/5622686/31d3b3da-9582-11e4-8527-502635a45bbf.png)

**Comment by unknownbrackets** [comment]
Well, #6976 fixes the start of the audio data.

-[Unknown]

**Comment by daniel229** [comment]
That would not help.

**Comment by unknownbrackets** [comment]
I've updated #6976 with some tweaks, can you try it again?

-[Unknown]

**Comment by daniel229** [comment]
Unfortunately,not help the game.

**Comment by unknownbrackets** [comment]
Does it log anything useful?

-[Unknown]

**Comment by daniel229** [comment]
Not seeing any different between the working and the not working one in info log.
Here is the debug log.(rename jpg to 7z)
![ppsspplog](https://cloud.githubusercontent.com/assets/3481559/7266276/d7a6c7d4-e8d9-11e4-9d59-e0e1cee88221.jpg)
