### ISSUE TITLE
Apportion of the menu of game.

### ISSUE THREAD

**Issue by QWEmct** [hrydgard/ppsspp#7291]
![screenshot_2015-01-07-18-29-45](https://cloud.githubusercontent.com/assets/8009425/5647967/98fd42e6-969b-11e4-890a-dd287352f960.png)
![screenshot_2015-01-07-18-29-39](https://cloud.githubusercontent.com/assets/8009425/5647972/a7bceeee-969b-11e4-8b48-04b2bb89d8d3.png)
To correct please.
Thanks.

**Comment by QWEmct** [comment]
~ Simple to forbid a screen turn, in this menu.

**Comment by hrydgard** [comment]
Thanks. I will try to make a better solution for the save UI soon.

**Comment by QWEmct** [comment]
Ok.
Thanks.
I close report, knowing that you is aware of a problem.
