### ISSUE TITLE
SIMD reg xx used as V reg (use VS instead)

### ISSUE THREAD

**Issue by issuer** [hrydgard/ppsspp#7292]
Juiced 2: Hot Import Nights [ULUS10312].

I did some testing and noticed that something between builds v0.9.9.1-1282-g102aa8e (the game still works) and v0.9.9.1-1285-g98f1ac9 (doesn't work anymore) broke the game completely.

The bug is as follows:
Upon any loading screen (except the first one) the emulator will stop the emulation and issue a pop-up warning saying:

SIMD reg 3 used as V reg (use VS instead)
SIMD reg 35 used as V reg (use VS instead)
SIMD reg 67 used as V reg (use VS instead)

and then it loops one more time, if you keep pressing OK.

After pressing OK several times the emulator gets past the loading screen but once you're in the race the game is completely broken, you can't see anything and all the cars spin like a tornado...

The game used to get past the loading screens just fine (v0.9.9.1-1282-g102aa8e and prior builds), only a small stutter would happen in the loading screens but no warnings whatsoever, the game was also playable.
I fear this change may also have broken other games, possibly Flatout Head On.

**Comment by unknownbrackets** [comment]
Just to clarify, it's still broken in v0.9.9.1-1437-g33f31b0 right?

Would you be willing to compile it and get a stack trace?  That would be super helpful if so.  There's a guide on the forum for Windows, but it's really pretty easy:
http://forums.ppsspp.org/showthread.php?tid=5231

If you do, once you have Visual Studio installed and have opened the project, press F5.  Then when you get that pop up (SIMD reg 3 used as V reg), click the pause icon in Visual Studio (it will be at the top in a toolbar.)

It will take a second to pause, and then it will show a small window in the bottom right with tabs.  One of the tabs should be "Call stack".  Select it and take a screenshot, and you'll be my hero.

-[Unknown]

**Comment by issuer** [comment]
Correct. It's still broken, rev v0.9.9.1-1282-g102aa8e broke it.
Sorry, this might take a while... GitBash is really slow getting the submodules.
As soon as it finishes i'll fire up VS and do exactly as you said.

**Comment by issuer** [comment]
Sorry, it was a first for me doing a stack trace. Is this what you wanted?
https://imagizer.imageshack.us/v2/858x483q90/901/ob6wuu.png

**Comment by unknownbrackets** [comment]
Oh, sorry, you did what I said but I forgot a step.

After you pause, near the top, there's a dropdown.  In your screenshot, it says "[1244] Input".  The number will vary, but from that dropdown select "Emu" (near the top.)  If you're using the multithreading option, select "CPU" instead (should be near the bottom.)

This will change the stack trace it's showing (for the right thread) and that'll be the one I'm after - sorry.

Thanks for grabbing the stack trace for me.

-[Unknown]

**Comment by issuer** [comment]
Here it goes. Since i don't use Multithreaded, selected Emu.

**Comment by unknownbrackets** [comment]
Hmm, that looks like either a clear or memset that didn't get to the framebuffer, or an alpha/stencil problem.  Hmm.

Is it supposed to be showing a map in the bottom left?  I'm wondering if that's where the red pattern is coming from.  We should create a new issue for it, but following these steps would help gather more information about it:
https://github.com/hrydgard/ppsspp/wiki/How-to-find-a-graphic-issue-with-the-GE-debugger
(you may also find seeing how it draws the scene interesting.)

Well, adhoc is pretty broken still, but any issues with adhoc are ultimately bugs.  The only cases of game specific adhoc issues that aren't bugs are ones that happen on real PSP devices as well, since our goal is to emulate the PSP.

Anyway, I'll mark this issue to be closed once the patch is reviewed and merged.

-[Unknown]

**Comment by issuer** [comment]
Thank you for fixing it.
Gameplay-wise the game is perfect, just like the real thing.

It does look like anpha/stencil problems since everytime any light sourcs move on the screen they leave white trails behind that stay forever on the screen.
Also, half of the asphalt is missing for some reason. Othen than that, the game is fine, everything you see on the screen is from the actual thing. The HUDS are all present, don't worry.

Gameplay video from PS2 version for reference: http://www.youtube.com/watch?v=1dCWDu6nYs0

The only time the screen goes white is when the PSP display the name of the opponents right before each race (its a visual effect). Maybe the emulator is applying stencils/alpha nonstop, and not just when the names of the opponents come into view.

I'll open another issue for it later, but the important thing is the game is playable yet again. Thank you.
