### ISSUE TITLE
V8 Supercars 3 Shootout artifacts issue

### ISSUE THREAD

**Issue by GamerzHell9137** [hrydgard/ppsspp#7294]
Not sure what's going on here but the screen is full of artifacts.
And i'm not sure if the minimap was supposed to look like that, it seems like a square border is missing (maybe not) and for some reason you gotta wait long for the game to load.(PPSSPP freezes and after 20-30 seconds the game continues)

https://www.youtube.com/watch?v=eQQ8V0DS_Ss

**Comment by unknownbrackets** [comment]
What does it show with the GE debugger when drawing those weird grey lines?

https://github.com/hrydgard/ppsspp/wiki/How-to-find-a-graphic-issue-with-the-GE-debugger

The long load time is odd.  I guess it's some HLE function probably?

-[Unknown]

**Comment by GamerzHell9137** [comment]
I have been clicking 10 minutes the Step buttons in GE Debugger but never to come to the problematic  place.... Is it possible to make it even faster? (It feels like its repeating the same textures)

And the long load issue can be fixed with changing the IO timing Host or Simulate UMD.

**Comment by GamerzHell9137** [comment]
Ahh here it is, found an other place with less stuff on screen.

http://puu.sh/eeLnX/d80c002fa7.png
http://puu.sh/eeLFL/dfd10384b6.txt

**Comment by GamerzHell9137** [comment]
Ohh sorry, it said it must be red.

http://puu.sh/eeNaf/22d918c151.png
http://puu.sh/eeNir/da88505183.txt

**Comment by unknownbrackets** [comment]
I wonder if it is mipmap related, probably not.  The UV coords seem odd for where it's drawing...

-[Unknown]

**Comment by hrydgard** [comment]
Might it be drawing geometry with a garbage matrix? It has the BOSCH texture selected on one of your shots, and draws a quite long triangle strip. So either the geometry or the transforms are garbage. Very strange-looking glitch.

**Comment by unknownbrackets** [comment]
Just marking this related to #9527.

Does it look correct (even if horribly slow) in the software renderer?  If so, that should confirm it.

-[Unknown]

**Comment by unknownbrackets** [comment]
I expect this to work now - on all backends - now that #11393 is merged.  How's it look?

-[Unknown]

**Comment by unknownbrackets** [comment]
Any feedback on how this looks now?

-[Unknown]

**Comment by benderscruffy01** [comment]
this can be closed
it has been fixed

**Comment by unknownbrackets** [comment]
Thanks for checking.

-[Unknown]
