### ISSUE TITLE
Soreyuke! Burunyanman Portable, boss battle BGM hangs on alarm SE

### ISSUE THREAD

**Issue by issuer** [hrydgard/ppsspp#7296]
![atracaudioissue](https://cloud.githubusercontent.com/assets/10441372/5671633/a9f631a4-9770-11e4-9696-98d8abcb029b.png)

The game has an issue transitioning from the alarm sound effect before the boss battle to the boss battle BGM. After the boss battle, the BGM resumes just fine and the next stage BGM plays as if nothing had happened.
Bottom line, PPSSPP doesn't play the boss battle BGM and gets stuck on a sound alarm that precedes every boss battle. Enabling the Sound Speed Hack in Audio has no effect.

The issue happens at 5:10 in the video. Warning, may be NSFW:
http://youtu.be/YIB1NuNRrNE

**Comment by issuer** [comment]
unknownbrackets@ad3ab88 has fixed this.

**Comment by unknownbrackets** [comment]
That's good to know, and interesting since it broke another game (which doesn't make sense to me.)  But, since it's not merged yet, I'm going to keep this open until it is.

-[Unknown]

**Comment by issuer** [comment]
Did you guys do something to Atrac on PPSSPP 1.0? Just tested this game and this issue is now fixed, the Boss battle BGM plays correctly. I'm closing it, thanks.
![npjh50656_00000](https://cloud.githubusercontent.com/assets/10441372/5995360/f181dc2a-aa77-11e4-923f-71c2367c7a78.jpg)
