### ISSUE TITLE
Crash in Patapon 3

### ISSUE THREAD

**Issue by BolverkWasAnyMore** [hrydgard/ppsspp#7297]
when i play patapon 3 it crash

**Comment by hrydgard** [comment]
Please add some more information. Were you playing on Android or PC? Where in the game did it crash?

**Comment by ppmeis** [comment]
Tested in Windows and Android with latest build. Seems to work fine for me.

**Comment by unknownbrackets** [comment]
Closing, in that case.  May be caused by cheats or something, but we can't do anything without more information.

-[Unknown]
