### ISSUE TITLE
Moga controller weirdness on PPSSPP-SDL in Linux

### ISSUE THREAD

**Issue by Joelgp83** [hrydgard/ppsspp#7300]
Moga on PPSSPP in Linux (ppsspp-sdl, can't get ppsspp-qt to recognize anything) is flippin' crazy.  Where to start?

As stated in the 1.0 regressions thread, Mode A is not seen as a joypad, but rather a phone/computer in linux mint, so I use mode B, pairing code 1234.  In game nearly all button/triggers work as designed once I remap them, better than windows (can't use triggers on windows, moga company devs are apparently not motivated enough to release proper driver support)!

However, the default guesses for button assignements are way off, and that's partly due to what linux is calling the buttons.  I've attached some screenshots below of my corrected control mapping, and they reveal some non-sensical button names, particularly for the A/B/X/Y buttons and Select/Back.  I don't know if this is the OSes fault or if key codes are being misunderstood, but sometimes select doesn't work in game, also.  And yes, my control mapping has the dpad mapped to both the controller's dpad and the right analog (in that order as seen on the screenshots) for more natural camera control purposes, as well as L and R being mapped to the triggers instead of the bumpers.

In-ui is where the most of the bugs are.  A/B/X/Y buttons are acting like a copy of the dpad, and even then, the dpad buttons are not navigating the ui correctly at all, especially in submenus like Settings.  Up is acting like Enter, Down is acting like ESC.  Left and Right seem mostly right.  A and B are not acting like Cancel/Confirm like they should be.

![screenshot from 2015-01-08 21 38 06](https://cloud.githubusercontent.com/assets/7368696/5675933/d2bcc328-977f-11e4-898f-faf89dad67c7.png)
![screenshot from 2015-01-08 21 38 16](https://cloud.githubusercontent.com/assets/7368696/5675932/d2bca082-977f-11e4-8c05-9687db186d56.png)
![screenshot from 2015-01-08 21 38 33](https://cloud.githubusercontent.com/assets/7368696/5675934/d2bd645e-977f-11e4-95a2-3fdb770bd71b.png)
![screenshot from 2015-01-08 21 39 34](https://cloud.githubusercontent.com/assets/7368696/5675935/d2c224e4-977f-11e4-8372-0eddf8c3ea7d.png)
![screenshot from 2015-01-08 21 39 37](https://cloud.githubusercontent.com/assets/7368696/5675936/d2c5ecb4-977f-11e4-9eba-a39be6b78c78.png)

**Comment by unknownbrackets** [comment]
I suppose the best way to try to do something about this would be trying to change the default keymap based on `SDL_JoystickName()`, but I bet there will be tons of different names so that could be quite a rabbit hole.

Anyway, I guess that would cover Android too, assuming the HID has a different name, doing it in `KeyMap::AutoConfForPad()`.  Maybe we should autoconf by default when creating a new config?

-[Unknown]

**Comment by Joelgp83** [comment]
Do you want/need a copy of my fixed controls.ini for autoconf purposes?  As long as you can get ingame, it works almost perfect.

**Comment by unknownbrackets** [comment]
Centralizing this in #7847.  It's really just the same problem, having a bunch of diverged discussions on it is only going to prevent it from ever getting any productive progress.

-[Unknown]
