### ISSUE TITLE
ubuntu qt full screen problem [user report]

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#7301]
![1](https://cloud.githubusercontent.com/assets/2177532/5680995/031c2412-984f-11e4-865e-daea0c45ba4e.png)
![2](https://cloud.githubusercontent.com/assets/2177532/5680998/0753a7f8-984f-11e4-96a7-9b0ee143561a.png)
![3](https://cloud.githubusercontent.com/assets/2177532/5681000/0a625944-984f-11e4-9ca9-ac5f69fb5fba.png)

**Comment by sum2012** [comment]
qt version have problem.
sdl  version no problem.

**Comment by sum2012** [comment]
@xsacha do you have idea ?

**Comment by sergiobenrocha2** [comment]
Are you using stable ppa?

I'm using Xubuntu 14.04 here, and Qt full screen works well. Maybe buggy Unity desktop?

**Comment by sum2012** [comment]
No feedback from the user,wait 2 week,I may close it.

**Comment by xsacha** [comment]
Could be distro-specific issue. I can't reproduce here. Qt makes window differently to SDL, so could expose an issue.

**Comment by sum2012** [comment]
I still no feedback.Closing
