### ISSUE TITLE
(iOS / iPad air 2) Final Fantasy Type-0

### ISSUE THREAD

**Issue by ppssppios** [hrydgard/ppsspp#7302]
When i try to start a "new game", PPSSPP will crash at the first loading screen. The version is 0.9.9.1 - 1437 tested on a iPad Air 2.

I tested on 0.9.9.1, and it works when i disable Hardware Transform, but if i disable Hardware Transform on 0.9.9.1 - 1437 it will still crash.

I tested on my iPad air 1st gen, and the game work perfectly with Hardware Transform enabled, so i think this is a iPad Air 2 specific issue.

Game: Final Fantasy Type-0
Device: iPad air 2
iOS version: 8.1.2
PPSSPP: 0.9.9.1 - 1437

**Comment by brujo5** [comment]
fastmem and multicore cause crash on this game.

**Comment by ppssppios** [comment]
Yepp, i know, but this problem is more specific to the iPad Air 2 when Hardware Transform is enabled. Im not getting the same issue on my iPad Air first gen or my iPhone 5s

**Comment by brujo5** [comment]
ipad air 2 very close to nvidia tegra K1
here some info about A8X gpu. It may be helpful for developers
http://www.anandtech.com/show/8716/apple-a8xs-gpu-gxa6850-even-better-than-i-thought

**Comment by ppssppios** [comment]
Anybody had a chance to look at this issue? Pretty sure some iPad Air 2 owners would love to play this game = )

**Comment by ppssppios** [comment]
Just tested 1.0.1 - 805. The game now works as it should. It dosnt crash directly at the first scene anymore. This issue can be closed.
