### ISSUE TITLE
x86 jit bug in Syphon Filter: Logan's Shadow

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#7305]
![01](https://cloud.githubusercontent.com/assets/3481559/5690220/4baad5fe-98b6-11e4-989a-0cdaadc58bb0.png)

disable either case 3 or case 7 in Comp_Mftv()
![02](https://cloud.githubusercontent.com/assets/3481559/5690221/4bafa656-98b6-11e4-9ccd-7b8b1200035c.png)

**Comment by daniel229** [comment]
x64 only, x86 is fine.

**Comment by unknownbrackets** [comment]
Hmm, Comp_Mftv is another one that can't be entirely safely disabled to find a problem (but only case 7.)  If case 3 fixes it, that's interesting.

If you disable inside `if (imm < 128) {` (e.g. both) does it still resolve it?  If no, how about inside `if (imm - 128 == VFPU_CTRL_CC) {` (again both)?  The latter is maybe the most likely, though I'm not sure what's wrong.  If it's neither of those, it's somehow prefix related I guess.

-[Unknown]

**Comment by daniel229** [comment]
disable inside<code>if (imm < 128) {</code> or disable inside <code>if (imm - 128 == VFPU_CTRL_CC) {</code> both help it.

**Comment by unknownbrackets** [comment]
In Core/MIPS/MIPSTables.cpp, try changing:
```c++
INSTR("mfv", JITFUNC(Comp_Mftv), Dis_Mftv, Int_Mftv, IN_OTHER|OUT_RT|IS_VFPU),
```

To:
```c++
INSTR("mfv", JITFUNC(Comp_Mftv), Dis_Mftv, Int_Mftv, IN_OTHER|IN_VFPU_CC|OUT_RT|IS_VFPU),
```

And:
```c++
INSTR("mtv", JITFUNC(Comp_Mftv), Dis_Mftv, Int_Mftv, IN_RT|OUT_OTHER|IS_VFPU),
```

To:
```c++
INSTR("mtv", JITFUNC(Comp_Mftv), Dis_Mftv, Int_Mftv, IN_RT|OUT_VFPU_CC|OUT_OTHER|IS_VFPU),
```

As well as:
```c++
INSTR("vmfvc", JITFUNC(Comp_Vmfvc), Dis_Vmftvc, Int_Vmfvc, IN_OTHER|OUT_OTHER|IS_VFPU),
```

To:
```c++
INSTR("vmfvc", JITFUNC(Comp_Vmfvc), Dis_Vmftvc, Int_Vmfvc, IN_OTHER|IN_VFPU_CC|OUT_OTHER|IS_VFPU),
```

Lastly:
```c++
INSTR("vmtvc", JITFUNC(Comp_Vmtvc), Dis_Vmftvc, Int_Vmtvc, IN_OTHER|OUT_OTHER|IS_VFPU),
```

To:
```c++
INSTR("vmtvc", JITFUNC(Comp_Vmtvc), Dis_Vmftvc, Int_Vmtvc, IN_OTHER|OUT_VFPU_CC|OUT_OTHER|IS_VFPU),
```

Well, I think that's right anyway, maybe it will be the bug.

-[Unknown]

**Comment by daniel229** [comment]
Yes,fixed.

**Comment by hrydgard** [comment]
Thanks for reporting and good catch @unknownbrackets !
