### ISSUE TITLE
If I open VS2013,Ben 10 Alien Force Vilgax Attacks crash

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#7308]
Look weird.
![01](https://cloud.githubusercontent.com/assets/3481559/5691191/7188637e-98f5-11e4-84fb-30f6e98752d1.png)

**Comment by daniel229** [comment]
![02](https://cloud.githubusercontent.com/assets/3481559/5691201/e238e8f0-98f5-11e4-9c0a-e43630a4ba19.png)

**Comment by hrydgard** [comment]
Seems like another issue with a crazy-sized read? But this one seems to come directly from the ISO file metadata. Corrupt ISO? Wonder why it would only happen in VS though...

**Comment by daniel229** [comment]
Look like RAM is not enough?When I open VS2013 RAM usage is 81%,after I close some programs,Ram usage down to 61%, then no crash.

**Comment by unknownbrackets** [comment]
1b7ee8c

-[Unknown]

**Comment by daniel229** [comment]
Thanks,fixed.try 92% ram usage no crash with that change,the previoous would crash.
