### ISSUE TITLE
Flatout Head On, skips BGMs after music popup window disappears

### ISSUE THREAD

**Issue by issuer** [hrydgard/ppsspp#7309]
Tested this game and graphically and gameplay-wise its perfect now with the #7292 fix.
However, i've noticed the BGMs are skipping to the next song right after the music window popup in-game disappears. Even in races it does this. Couldn't find anything in the logs.

http://youtu.be/VXnsq6h0R3k

**Comment by hrydgard** [comment]
Yeah, I think this is an old problem. Burnout used to do this too, but it got fixed somehow.

We know there are inaccuracies in sceAtrac, @unknownbrackets tried to improve it but it broke GTA so I'm going to merge that fix after 1.0, then we can fix the fallout... With luck it could help with this.

**Comment by unknownbrackets** [comment]
I suppose it likely won't make a difference, but does #6976 change this at all?

-[Unknown]

**Comment by issuer** [comment]
Do you mean with the latest orphis builds? If so, it didn't change anything, just tested v0.9.9.1-1462-g1b055fd.
Or, do you possibly mean compiling the atrac-minor branch from your repo?

**Comment by hrydgard** [comment]
Unknown means compiling his branch, yes.

**Comment by issuer** [comment]
I've just uninstalled VS.
Oh well, the things i do for love.

**Comment by issuer** [comment]
Unfortunately it didn't fix Flatout, the BGM still skip to the next song right after the window pop up disappears.
It has fixed #7296 though.

**Comment by issuer** [comment]
Closing this, it's a replicate of #6663. The issue is still not fixed.
