### ISSUE TITLE
Audio in emulator menu it self and in game is garbled and strange noises 

### ISSUE THREAD

**Issue by IceLancerSR** [hrydgard/ppsspp#7323]
Using Asus Xonar DG Win7 x64 8gb ram
upon starting emu there are some ugly crackling noises coming from emulator
game sounds are totally not recognizable as well
v0.9.9.1-1486-g7c3bc2b

**Comment by hrydgard** [comment]
Okay, got to be the new WASAPI audio backend. Works fine on my machine but I guess not everywhere. Maybe should just add an option to revert to DirectSound, or maybe can add a latency slider...

**Comment by unknownbrackets** [comment]
Can you turn on reporting in the System section of settings under "help the PPSSPP team"?  In case your audio driver is requesting a different format than float or something like that, it'll tell us.

-[Unknown]

**Comment by IceLancerSR** [comment]
i turned on that option now.Sound in emulator menu is buzzing static sound ears ripping..

**Comment by IceLancerSR** [comment]
x64 bit is not available yet, but i tested x86 ,sound distortion changed , now its circular buzzin sound but broken

**Comment by unknownbrackets** [comment]
Hmm, nothing got reported unfortunately (you may have to restart the emulator after enabling it, but it sounds like you already did.)  It's interesting that that change affected it, though, even if still wrong.

I wonder if `pDeviceFormat->Format.nChannels` is not 2 or something.

-[Unknown]

**Comment by hrydgard** [comment]
@IceLancerSR , do you have surround audio, or regular stereo?

**Comment by IceLancerSR** [comment]
surround 5.1
here is video/audio recorded sample of problem 4mb compressed mkv
https://mega.co.nz/#!XsNiCKhb!MTB-v9glrhd4h2bBGR1_oGjPIt_JQZhc3a5-Q8oDiws

**Comment by hrydgard** [comment]
Thank you, surround might be the explanation. Then we need to translate stereo into surround into a way that sounds good.. Maybe just fill out the first two channels? I'll try.

**Comment by IceLancerSR** [comment]
Yes indeed i switched to stereo and sound is fine!
5.1 is problem as i am using it as default.

**Comment by hrydgard** [comment]
Great! I just made a new commit that tries to simulate stereo on surround. It may come out of the completely wrong speakers though, please report when the build is ready :)

**Comment by IceLancerSR** [comment]
Alright ! That did the trick .No more distorted sounds ! Thanks you ! 
You are one hell of a fast coder !

**Comment by hrydgard** [comment]
Awesome! Does it sound correct though, with sounds that should be from the left coming out of the left speaker? Did it sound "fuller" (audio out of all speakers) with the old audio system we had? I want this to be good :)

**Comment by IceLancerSR** [comment]
Yes everything seems to be in order.Left is left right is right.All speakers have audio

**Comment by IceLancerSR** [comment]
P.S the only difference "minor" is when shutting down emu . There is high pop sound

**Comment by hrydgard** [comment]
Hm, ok, I'll see if I can get rid of that :)

**Comment by IceLancerSR** [comment]
ignore, deleted post.it was one time thing.It doesnt happen any more!
Excellent coding !

**Comment by IceLancerSR** [comment]
Alright one thing tho.
There is slight hickup that wasnt before.just left sound to go on and every two seconds or so a clear hickup is heard like emu is loosing fps,but it doesnt.

**Comment by IceLancerSR** [comment]
Tested , hickup is happening between ppsspp-v0.9.9.1-1439-g01ff870-windows-x86 and ppsspp-v0.9.9.1-1472-g82ccce9-windows-x86
1439 has no hickups at all.i will try to narrow bit more.

**Comment by IceLancerSR** [comment]
Got it. 1462 is last build before 1472.In 1462sound ie good no hickups.next build is 1472 and it has it.And all the way up to now.

**Comment by hrydgard** [comment]
Hm, okay, that's unfortunate, as 1472 is where we added Dolphin's resampler, and before the switch to WASAPI so it was still using dsound, so just adding a parameter to fallback to dsound wouldn't help. It works great here..

**Comment by IceLancerSR** [comment]
https://mega.co.nz/#!WwkXHYJT!8utMyj6hBSccbQgHWqbuunP0vySwiLopiZSjGsphmKY
here is sample of audio /video. its just standby (main menu screen of game with audio looping)
it is most observant after 13th second starts "clicking poping every second. Sounds like latency thing

**Comment by hrydgard** [comment]
Thanks, I hear it :/  Hm..

**Comment by vnctdj** [comment]
The music is played at insane speed on the menu, look at the video I made : https://www.youtube.com/watch?v=-E3MPA7u4xE

**Comment by hrydgard** [comment]
Yeah, that happens when you set the Windows sample rate to 192khz in the control panel :)

I will add resampling there too, although it's really pointless to have it set that high. 

https://forums.adobe.com/thread/973133 , but for Playback devices.

**Comment by IceLancerSR** [comment]
true 24/48k is top.and it doesnt go berserk .

**Comment by vnctdj** [comment]
@hrydgard 
Ahah ^^
I don't know why it was set that high on my panel O_o

Anyway, even if it's not related to WASAPI (it happens since always), it has remembered me that the music on the menu is not looped correctly, I mean, it restarts before the loop is finished :-/
I don't know if you have an idea where this problem could come from ?

**Comment by hrydgard** [comment]
I'm not quite sure what the problem is with that, but even on a real psp, many games have fairly short menu loops, some do sound cut down,..

**Comment by vnctdj** [comment]
Oh really ? Even on a real PSP for some games ?
With *Monster Hunter Freedom Unite*, the loop is not correct on PPSSPP but is correct on a real PSP...
I don't remember a game that was not correct on my PSP, maybe I haven't tested enough :)

**Comment by hrydgard** [comment]
Okay, well, there's probably some issue then :)

**Comment by vnctdj** [comment]
Maybe it's not related, but I sometimes see the following line in the log console :
> 03:01:756 user_main    E[ME]: HLE\sceAtrac.cpp:1592 sceAtracSetLoopNum(3, 0):no loop information

**Comment by unknownbrackets** [comment]
If you're talking about looping in game, it's definitely because of bugs in the sceAtrac implementation.  It drops frames when looping too right now, which I have an open pull request to improve (it breaks some music in GTA right now, though, at least much more frequently than without the change.)

-[Unknown]

**Comment by vnctdj** [comment]
You mean https://github.com/hrydgard/ppsspp/pull/6976, right ?
I will try to test it...

**Comment by tapcio** [comment]
I think that WASAPI is not best API for game or emulator, maybe some higher level API like XAudio2 instead? It works very well for me in PCSX2 and Dolphin, way better than DSound.

**Comment by Bigpet** [comment]
Both DirectSound and XAudio2 are just written on top of WASAPI after Windows Vista. It is the most low level sound API in windows and therefore it is the best audio API for emulators.

**Comment by IceLancerSR** [comment]
Well, what ever.i am getting crackings and hickups with sound on my 4ghz intel with hardware asus xonar sound card with games that simply should not be happening.Therefor I am staying to pre wasapi in order to play psp on pc.All works good on pre wasapi build

**Comment by Bigpet** [comment]
I'm not saying that the currently usage is perfect. I was merely commenting on the quality of the APIs themselves not how we use them. Also, it was not just WASAPI that was introduced but also some audio resampling if I saw that right, so it might well be the audio resampling that's not perfect yet.

**Comment by tapcio** [comment]
Yes, WASAPI will be better, but require much greater effort to make it work properly. XAudio2 have out-of-the-box features like mixing, multi channel support, ie. it require much less effort. It is a real DirectSound alternative, WASAPI is direct alternative for old Kernel Streaming.

**Comment by unknownbrackets** [comment]
But, we don't need any of those features (mixing, channels, etc.)  We already have to do those things anyway in various stages of HLE and for other platforms.

If you believe XAudio2 will be significantly better, provide a patch that uses XAudio2 and has demonstrably better quality.

-[Unknown]

**Comment by tapcio** [comment]
@IceLancerSR 
ASUS Xonar is good example only if you use ROG Phoebus, all other (know to me) uses non HDA architecture and have many problem with drivers on modern Windows (works fine on Linux !). Also EAX emulation included in ASUS drivers breaks some games (missing sounds, etc.). If not have Phoebus I recommend you to use modded "UNi Xonar Drivers" that fix many issues.

**Comment by hrydgard** [comment]
Are you getting like consistent crackling? If so we might need to increase the WASAPI buffer size already.

But really, for PPSSPP WASAPI is pretty much ideal, except that it's hard to predict the best buffer size for each machine... Like Unknown says, mixing etc is irrelevant because we have to do it ourselves the PSP way anyway.

**Comment by tapcio** [comment]
I sold my Xonar DX (because of driver problems) and now use a build-in HDA codec (AD2000B) using generic Windows 8.1 HDA driver (which is newer and better than manufacturer driver), and for me WASAPI is better that DirectSound, less cracking (crack only when loading new location/menu, or when FPS drops - but this is expected) and better latency. I can even run PEOPS DSound 1.10b on that old AD2000B with insane low latency without cracking, which is was absolutely not possible on Xonar DX. I was mentioning XAudio2 as possible alternative for some users with problems, or for additional features like surround upmixing.

**Comment by IceLancerSR** [comment]
@tapcio Thats nonsense.
I will just point out that i am EXP pc user , not your common noob from around corner.

As for rest , i already attached recorded cracklings with wasap above few posts link is still active.
I have said my piece.
https://github.com/hrydgard/ppsspp/issues/7323#issuecomment-69643804

**Comment by tapcio** [comment]
What is nonsense ? Maybe crappy C-Media rebranded ASUS Xonar drivers causing very high DPC latency - see here: http://maxedtech.com/the-case-of-dpc-latency/

**Comment by unknownbrackets** [comment]
Is this still an issue?  I think we may have already done the resampling needed?

As for WASAPI vs. etc., we still have an option for DirectSound.  If it still happens there, maybe it's an issue of a high sample rate not agreeing well with the resampler?  But in some cases, there may only be so much we can do.

-[Unknown]

**Comment by hrydgard** [comment]
Let's just call this outdated and close..
