### ISSUE TITLE
Sometime load a game,it display "Could not load game"

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#7330]
For example load a World Neverland The Nalulu KingDom Stories demo
![03](https://cloud.githubusercontent.com/assets/3481559/5736893/45f51f80-9c16-11e4-9f8e-c3b863525807.png)
![04](https://cloud.githubusercontent.com/assets/3481559/5736894/45f9512c-9c16-11e4-8f4d-d2fccd74649a.png)

**Comment by unknownbrackets** [comment]
I've never had this issue.  Does it show anything in the log?

It may be other software interfering or something.

-[Unknown]

**Comment by daniel229** [comment]
I produce a crash today
![01](https://cloud.githubusercontent.com/assets/3481559/5750617/57c58f7a-9c92-11e4-84be-bbd6f7d8f686.png)

**Comment by daniel229** [comment]
log
![02](https://cloud.githubusercontent.com/assets/3481559/5750720/a4970d50-9c93-11e4-9c00-4a56d59f3333.png)

**Comment by daniel229** [comment]
![04](https://cloud.githubusercontent.com/assets/3481559/5751011/48a20dd8-9c98-11e4-8092-e78bb8d6bc52.png)

**Comment by hrydgard** [comment]
Hm. ISO corrupted? Is it on your harddrive or some external drive? Either way it's not good that it crashes..

**Comment by daniel229** [comment]
I think It's not corrupted,it's on the harddriver.Possible since https://github.com/hrydgard/ppsspp/pull/7183 ,I can't reproduce on v0.9.9.1-1234-gcd573cf,it happen since v0.9.9.1-1237-ga074c06

**Comment by daniel229** [comment]
Here is a way to reproduce the problem.Don't know anyone could reproduce it.
download the latest build from http://buildbot.orphis.net/ppsspp/index.php ,current is v0.9.9.1-1503-gc250074
download World Neverland: The Nalulu Kingdom Stories demo from http://www.pspdemocenter.com/page.php?id=3990

Run PPSSPP,using "load.." to bootup the game.Don't let the game path stay in recent page and games page,if it stay there,just remove it and rerun PPSSPP.

Here is the video
http://youtu.be/UNGtwcX6ZGA

**Comment by daniel229** [comment]
Fixed by reverting UI/EmuScreen.cpp in https://github.com/hrydgard/ppsspp/pull/7183

**Comment by unknownbrackets** [comment]
And for sure, you don't have any game specific settings for it, right (no ini file at all)?

-[Unknown]

**Comment by daniel229** [comment]
No game specific setting.

**Comment by unknownbrackets** [comment]
When it crashes, is any other thread doing anything in the same area of the code (somewhere in ISOFileSystem or etc.)?

-[Unknown]

**Comment by daniel229** [comment]
msvcr120d.dll maybe.sometime got runtime error.
![01](https://cloud.githubusercontent.com/assets/3481559/5787043/abd8d92e-9e2b-11e4-830f-3aab0a54b81e.png)
![02](https://cloud.githubusercontent.com/assets/3481559/5787044/abdbf19a-9e2b-11e4-9846-c2d39e688cb1.png)

**Comment by vsub** [comment]
From the EmuScreen no matter what I tried,the game was always loaded but randomly(don't know the exact way to trigger it or if it's just on this game(I tried only this game))when I use File=>Load or the Load button and try to load the game,ppsspp will either crash(the Send\Don't Send dialog)or I'll get some kind of runtime error.

I never got the screen saying that ppsspp could not find the executable.

**Comment by vsub** [comment]
v0.9.9.1-1503 x86 on Win7 x64

**Comment by daniel229** [comment]
Yes,it only happen when using "Load..." click the icon from EmuScreen seems fine.I got some reports from people when they try load the iso,then got the "Could not load game" these days,and I only can reproduce this from this game.
Sometime got these error:
![01](https://cloud.githubusercontent.com/assets/3481559/5787986/bf496a02-9e56-11e4-805a-7d9f0605b9eb.png)
![02](https://cloud.githubusercontent.com/assets/3481559/5787985/bf47c206-9e56-11e4-8776-1afcfd7a229c.png)

**Comment by daniel229** [comment]
Frontier Gate Boost+ trial is also affected.

**Comment by unknownbrackets** [comment]
We should just mutex usage of that code.  I suspect that we have two threads reading at once - for example one thread reading in thumbnails.  Probably it's simply a thread safety issue.

-[Unknown]

**Comment by Arsh150** [comment]
;-; help. I spent the whole night to download the file and it finally happened but I cant load it in PPSSPP
![image](https://cloud.githubusercontent.com/assets/24221246/20661885/cb22b326-b572-11e6-9141-3745e6d2c0bf.png)

**Comment by hrydgard** [comment]
Then the game was not a PSP game, did you try to run a PSX or PS2 game?

**Comment by Gardezi1** [comment]
I'm also facing the same problem and I don't know what to do any help would be appreciated 

and if somebody know some good ps2  emulator which is free to please tell it's name. Thanks

**Comment by hrydgard** [comment]
@Gardezi1 Well, PPSSPP is a PSP emulator. If you're trying to run something that's not a normal PSP game it obviously will not work. PCSX2 is the emulator you want but it only exists for PC.

**Comment by ironnis** [comment]
Hello, can somebody help me?
I'm using PPSSPP android ver. 1.3.0.1. I had this problem on my other games too, but somehow I managed to worked my way out because apparently there are no answer to this problem on Google (but I forgot how *whoops). Game is Yugioh gx tagforce 2.
![screenshot_2017-10-21-02-42-47](https://user-images.githubusercontent.com/32967522/31839047-909282f2-b609-11e7-92a8-678b9b948567.png)

![screenshot_2017-10-21-02-38-07](https://user-images.githubusercontent.com/32967522/31839225-6224f1ce-b60a-11e7-8b6d-9e4074ee35d1.png)
