### ISSUE TITLE
PPSSPP hangs when "Browse..." button is pressed

### ISSUE THREAD

**Issue by issuer** [hrydgard/ppsspp#7334]
I've got PPSSPP v0.9.9.1-1498-gb9b96f1 from orphis builds and noticed this really strange bug. 
I was trying to find an .ISO file in a different folder and when i pressed the "Browse..." button the emulator just hang.
The emulator hangs on both x86 and x64 Windows builds.

**Comment by hrydgard** [comment]
Hm, indeed. Very strange, will investigate.

**Comment by hrydgard** [comment]
It works when I revert to DirectSound instead of WASAPI. What???

**Comment by hrydgard** [comment]
OK, got it. Thanks for reporting!

**Comment by issuer** [comment]
Thanks.
