### ISSUE TITLE
lenovo vibe x2 black boxes on textures problem

### ISSUE THREAD

**Issue by palinzm** [hrydgard/ppsspp#7335]
I just bought this phone. I been using zenfone 4 and 5 but there no such black boxes in the game. I just need some help. All setting have been tried but nothing change .

**Comment by palinzm** [comment]
Anyone please help me???

**Comment by unknownbrackets** [comment]
Some graphics drivers for low end devices have blending problems.  I would expect the PowerVR G600 in that to work, but maybe the drivers don't work.

If it happens in all games with default settings, then there's probably not much we can do.

-[Unknown]

**Comment by unknownbrackets** [comment]
It may be that this was affected by #7510?

-[Unknown]

**Comment by unknownbrackets** [comment]
That seems likely, and there's been no update to confirm or deny, so closing this.  If it's still happening, please feel free to comment with more detail - ideally what game, whether you've tried default settings, etc.
