### ISSUE TITLE
Power Stone Collection, spams error "bad thread id" in Console Log nonstop

### ISSUE THREAD

**Issue by issuer** [hrydgard/ppsspp#7337]
When i took a look at the console log i've noticed that Power Stone Collection spams this error in the console log nonstop from boot (1 error per second):

MoniMain     E[KERNEL]: HLE\sceKernelThread.cpp:2736 sceKernelWakeupThread(-1) - bad thread id

Fortunately the game seems alright, just dropping this here in case it may help solve other problems.
Full Debug Log:
https://www.dropbox.com/s/pm8ifn57ewhcemm/PowerStoneCollection_Error_badthread_ppsspplog.rar?dl=0

**Comment by unknownbrackets** [comment]
Can you try the game on a PSP with JpcspTrace?

https://github.com/unknownbrackets/JpcspTrace

You'll need to use this line in the config:

sceKernelWakeupThread 0xd59ead2f 1 x

It's very possible the game may simply generate this error on a real PSP.  -1 is not a valid thread.

-[Unknown]

**Comment by issuer** [comment]
Sorry, i'm afraid i can't do a JpcspTrace since i don't own a PSP.
I'm relieved though, knowing some games return errors like this by default (real PSP). Even spamming this error, the game seemed fine and ran without any problems. I just found it strange to be spamming it like crazy.

**Comment by daniel229** [comment]
jpcsptrace look like return 0x80020198
https://gist.github.com/daniel229/85b8c7e3dd9caeba0327

**Comment by unknownbrackets** [comment]
Yeah, that's SCE_KERNEL_ERROR_UNKNOWN_THID, so this is correct behavior that also happens on a PSP.  I guess we could tone down the error log but it's generally pretty useful...

-[Unknown]
