### ISSUE TITLE
"Error loading file: could not find executable"

### ISSUE THREAD

**Issue by XscypherX** [hrydgard/ppsspp#7338]
Every time I try to open Assassins Creed: Bloodline, this message shows up.    
![image](https://cloud.githubusercontent.com/assets/10575180/5789626/dc631c20-9e40-11e4-982b-aa9c94494cbf.jpg)

**Comment by unknownbrackets** [comment]
Rerip it.  This means your file is corrupt or hacked or something.

http://ppsspp.org/faq.html

-[Unknown]

**Comment by XscypherX** [comment]
What does rerip mean?

**Comment by unknownbrackets** [comment]
If you look at the first answer in the page I linked to, it answers your question.

-[Unknown]

**Comment by XscypherX** [comment]
Oh yeah, and thanks, the file was currupted. Coolrom, never again.

-[Lol idk why I did this]
