### ISSUE TITLE
Problem Loading Game.

### ISSUE THREAD

**Issue by XscypherX** [hrydgard/ppsspp#7343]
The game Assassins Creed: Bloodlines refuses to load immediately after startup and I can't identify the problem. The game doesn't close so the application CrashReporter doesn't identify it. It might be an installed application, maybe ControllersForAll. If you don't know it lets you use foreign controllers like dualshock 3 or 4 etc. for supported applications. Well, the times it did crash not because of the game these services were active...

![image](https://cloud.githubusercontent.com/assets/10575180/5790887/e1bcba46-9e7c-11e4-89e8-eb957c5b7bef.jpg)
![image](https://cloud.githubusercontent.com/assets/10575180/5790888/e1bff922-9e7c-11e4-9341-81951ca92b25.jpg)

**Comment by thedax** [comment]
Closing in favour of https://github.com/hrydgard/ppsspp/issues/7360.
