### ISSUE TITLE
Kidou Keisatsu Patlabor: Come Back Mini-Pato black screen since v0.9.1-485-gd9b529b

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#7345]
v0.9.1-485-gd9b529b log (work)
log:https://gist.github.com/sum2012/1c4f03adf0cd857d1195
v0.9.1-499-g361a6ea (black screen)
log:https://gist.github.com/sum2012/8f567aa5e8700a826201
v0.9.9.1-1503-gc250074 (black screen)
log:https://gist.github.com/sum2012/2d1bb15b145e1ca07c71

**Comment by Bigpet** [comment]
Weird, those seem to be mostly D3D changes, does this happen with both Direct3D and OpenGL?

**Comment by unknownbrackets** [comment]
Did e40bef6f177725af1936ae1a796aa1d417b6f4f1 fix it?  May have also affected Kinnikuman: Muscle Generations according to reporting.

-[Unknown]

**Comment by sum2012** [comment]
Yes fixed,Thanks
log:
https://gist.github.com/sum2012/dd875a45bab01d1a2a3a

**Comment by sum2012** [comment]
Kinnikuman: Muscle Generations work fine on v0.9.9.1-1503 and v0.9.9.1-1505
