### ISSUE TITLE
Eternal Etude Canvas 4 unable to load (thread event handlers)

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#7346]
v0.9.8-1599-gf1446f7 work
log:https://gist.github.com/sum2012/d04bd746129a1d53c0c1

v0.9.8-1610-gc4bebda black screen
log:https://gist.github.com/sum2012/188056b2bcc298c0d111

v0.9.9.1-1505-gcf577e9 black screen
log:https://gist.github.com/sum2012/1bbbddd1df48912d81d9
That mean #6549

**Comment by sum2012** [comment]
@unknownbrackets this commit
https://github.com/unknownbrackets/ppsspp/commit/50402a3d49b336d27d2b6643679faedcbb3e9167#diff-427634680812e6298c92898c2aa9146aR531

**Comment by unknownbrackets** [comment]
This is really the same as #6301.  Anyway, this never got past intro:
http://forums.ppsspp.org/showthread.php?tid=5971

-[Unknown]

**Comment by sum2012** [comment]
After merge your two commit.
Same as before:after intro video hang.
Info log:
https://drive.google.com/file/d/0B3OaSdeV0L8kcEhwOW1Zck5XR2M/view?usp=sharing
Debug log:(remove spam of sceGeListDeQueue log)
https://drive.google.com/file/d/0B3OaSdeV0L8kejdKVEhWcFVzRU0/view?usp=sharing

**Comment by unknownbrackets** [comment]
Games reported as using thread event handlers:

 * Jikkyou Powerful Pro Yakyuu series
 * FairlyLife: MiracleDays
 * Sakura Sakura: Haru Urara
 * Eternal Etude Canvas 4
 * Suigetsu Ni Portable
 * Pia Carrot e Youkoso!! 4 ~Natsu no Kioku
 * Pre-Pia ~ Prince Pia Carrot
 * SuGirly Wish Limited
 * Yaneura no Kanojo
 * GOLD STAR – NONSTOP GO GO!!
 * Battle Spirits: Kiseki no Hasha

-[Unknown]

**Comment by unknownbrackets** [comment]
How does this look with the latest event handler support?

Sounds like #6301 was helped so might help the other two.  Not sure about the remaining, maybe no one has tried, or they work so no one has reported.

-[Unknown]

**Comment by daniel229** [comment]
Eternal Etude Canvas 4 and GOLD STAR – NONSTOP GO GO!! also fixed。

**Comment by unknownbrackets** [comment]
Sweet.  I'm going to close this then, and if the other games are having problems we can reopen or create new issues as makes sense.

-[Unknown]
