### ISSUE TITLE
Qt build on Linux: fullscreen mode does not work in current master

### ISSUE THREAD

**Issue by akien-mga** [hrydgard/ppsspp#7351]
I experience what seems to be a regression in the current master branch since it was working fine with PPSSPP 0.9.9.1.

If I toggle fullscreen with F11 (or double-click), the client gets maximised to take the whole screen space, but the "content" part of the UI does not stretch. A fullscreen would explain it better:

![ppsspp](https://cloud.githubusercontent.com/assets/4701338/5794143/7fb76c48-9f61-11e4-9c26-2873b35f6ae3.jpg)

I could reproduce this issue with both my Intel HD 4000 chipset (open source driver) and my Nvidia GPU (proprietary driver, 340.65), on the same laptop.
I built 45ec0c8a14 against Qt 5.4.0, ffmpeg 2.4.5 and mesa 10.4.2.

**Comment by unknownbrackets** [comment]
Can you bisect when it stopped working?  Does it work if you restart after setting fullscreen?

-[Unknown]

**Comment by akien-mga** [comment]
The fullscreen parameter in the settings seems to have no influence. If I tick it, nothing happens, and after a restart it's unticked again. If I press F11, it gets ticked, but then it's the same display as in my screenshot.

I just built PPSSPPSDL and here the fullscreen works fine.

I'll try to do a bisect, even though I'm not particularly skilled at that. Should I just use the good ol' dichotomy method?

**Comment by unknownbrackets** [comment]
https://github.com/hrydgard/ppsspp/wiki/How-to-bisect-to-find-what-broke-a-game

Git makes it super easy.  If you know it worked in v0.9.9.1 it should take about 11 tries or so to find it.

-[Unknown]

**Comment by akien-mga** [comment]
Ah git is really awesome, and your howto is great. I'll bisect now and see what I get.

**Comment by akien-mga** [comment]
Here is the result of my bisection:

```
1a0f537967983ea5a64c61ad8d66a6b3a8b8e94a is the first bad commit
commit 1a0f537967983ea5a64c61ad8d66a6b3a8b8e94a
Author: Unknown W. Brackets <checkins@unknownbrackets.org>
Date:   Sun Dec 28 13:19:19 2014 -0800

    dx9: Avoid triggering reset when size unchanged.

:040000 040000 ad51fa8f950af1a46625b2c94ae0a33627b4cb9a acd890fb80d5fe85be3aadf85ac0b3885c5d9fcd M      Core
:040000 040000 f29b69de8d7be57c23bbbf0a5897a95f871d59fd d5c3e616ae8d627614d403bf88dd321e02bd4828 M      Windows
```
With this commit, when going in fullscreen the background colour is even brown instead of plain blue as shown in my screenshot above.

**Comment by akien-mga** [comment]
Here is the bisect log in case it could be of use:
```
$ git bisect log
git bisect start
# bad: [416093f2114282761f4b19f5a586fba7ecb0f538] Merge pull request #7350 from unknownbrackets/warnings
git bisect bad 416093f2114282761f4b19f5a586fba7ecb0f538
# good: [bf709790c4fed9cd211f755acaa650ace0f7555a] Update version to 0.9.9.1
git bisect good bf709790c4fed9cd211f755acaa650ace0f7555a
# skip: [f1d43e7e90bd3bfdaa21f472f9cd7d63b5b14b35] Merge pull request #7046 from unknownbrackets/perf
git bisect skip f1d43e7e90bd3bfdaa21f472f9cd7d63b5b14b35
# skip: [0fdebdc1caab4d91a34c785c6031b9f0ce0a6c12] Fix discardVS.
git bisect skip 0fdebdc1caab4d91a34c785c6031b9f0ce0a6c12
# good: [65e008f053b31d5b0eadcb7c1e0985c42c9af877] Implement a MipsJit.
git bisect good 65e008f053b31d5b0eadcb7c1e0985c42c9af877
# good: [9c73272604a130258da79adbf8341df9980a1310] Merge pull request #7178 from unknownbrackets/mips-emitter
git bisect good 9c73272604a130258da79adbf8341df9980a1310
# skip: [6ed15ab1f57bb63067bf7eb13725df9c7371ba16] Add EnableWlan check
git bisect skip 6ed15ab1f57bb63067bf7eb13725df9c7371ba16
# bad: [f288cd04a9ada30c1ed0bd6c94fcf0da96a42a9f] Replace frame download in Grisaia no Kajitsu La Fruit de la Grisaia
git bisect bad f288cd04a9ada30c1ed0bd6c94fcf0da96a42a9f
# bad: [b6b4a4f05e517949357848d8fc3069ea07ea7224] Avoid debug log spam in menu.
git bisect bad b6b4a4f05e517949357848d8fc3069ea07ea7224
# good: [241246606532e27c602b4e0cc5f9e1d9dd74290f] Allow an analog to press a button in any direction.
git bisect good 241246606532e27c602b4e0cc5f9e1d9dd74290f
# good: [6af7f4f7f3e897ed94b9d8fc10c6448ff7e991af] Merge pull request #7226 from xebra/dx9
git bisect good 6af7f4f7f3e897ed94b9d8fc10c6448ff7e991af
# good: [93fee10899da0a1c213430c6ab49c6f86cbc93c0] Typo.
git bisect good 93fee10899da0a1c213430c6ab49c6f86cbc93c0
# bad: [d254ec70884e1a6b8ff6a036c89b3a30aa5b32e7] Write screenshots using unicode-aware apis on win.
git bisect bad d254ec70884e1a6b8ff6a036c89b3a30aa5b32e7
# bad: [1a0f537967983ea5a64c61ad8d66a6b3a8b8e94a] dx9: Avoid triggering reset when size unchanged.
git bisect bad 1a0f537967983ea5a64c61ad8d66a6b3a8b8e94a
# good: [853e81cf03f0ca5d76f46b0dfa5165ff060c23e9] dx9: Explicitly specify the backbuffer size.
git bisect good 853e81cf03f0ca5d76f46b0dfa5165ff060c23e9
# good: [cb62468fb9fa9140fc636c720cc1dc2ff1264232] dx9: Fix a shadowing issue in D3D9_Init().
git bisect good cb62468fb9fa9140fc636c720cc1dc2ff1264232
# first bad commit: [1a0f537967983ea5a64c61ad8d66a6b3a8b8e94a] dx9: Avoid triggering reset when size unchanged.
```

**Comment by unknownbrackets** [comment]
Okay, I think hrydgard/native#258 will fix that once it is merged and the native submodule is updated.

-[Unknown]

**Comment by unknownbrackets** [comment]
Submodule has been updated, so latest should work.  I didn't actually test it though, but if it does we can close this.

-[Unknown]

**Comment by akien-mga** [comment]
I confirm the bug fixed in current master, thanks :)
