### ISSUE TITLE
Is this a memset()?

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#7353]
It fixes problem,found in Final FantasyTactics.
![01](https://cloud.githubusercontent.com/assets/3481559/5794784/83b85918-9fb8-11e4-918d-4df0b418a551.png)

**Comment by unknownbrackets** [comment]
Hmm, yes, looks like it is.  I have a memset that looks very similar in the US version, but there are a few differences.... it's already being recognized, though.

-[Unknown]

**Comment by daniel229** [comment]
Thanks,no memset recognized in the jpn version with current master build.
