### ISSUE TITLE
Wild ARMs XF DX9 small graphical bug

### ISSUE THREAD

**Issue by DarkD** [hrydgard/ppsspp#7356]
There's still one small graphical bug present.
![ulus10339_00000](https://cloud.githubusercontent.com/assets/6061259/5797080/d6498452-9fc4-11e4-9c93-0867d3b192d9.png)
Probably the last one if nobody will make new ones :) OGL have none, at least I hadn't encountered any.

**Comment by unknownbrackets** [comment]
Without checking, I'm pretty sure this is caused by Direct3D 9 not supporting dual alpha.

-[Unknown]

**Comment by hrydgard** [comment]
Should really get around to implementing dual alpha simulation (two draw calls with different color mask settings, and in some cases different shaders I think, it'll be messy...)

**Comment by tapcio** [comment]
Drop DX9 and switch to DX11 then :P

**Comment by Bigpet** [comment]
@tapcio The whole point of even bothering with DirectX was to support old Windows Drivers, if you can run DX11 then you should just use OpenGL.

**Comment by tapcio** [comment]
AMD OpenGL is terrible, slow and broken... DX9/DX11 works much better on all Radeon cards and IMHO supporting pre-Vista system/driver is pointless.

**Comment by Bigpet** [comment]
Yes I understand that you'd rather see people support your poor choice of hardware than other peoples poor choice of OS.

On a serious not, do you have actual numbers of AMD devices being significantly slower with PPSSPP OpenGL versus Direct3D?

**Comment by hrydgard** [comment]
DX9 is very highly optimized in some drivers so I could believe that it would win by quite some margin in some cases. However I don't think DX11 is worth the effort when we have OpenGL as all machines that are powerful enough to support DX11 properly will also work fine with GL.

**Comment by Bigpet** [comment]
Yeah DX12 has some potential. I mean it's basically like using Direct State Access and display lists in OpenGL. Only that it won't be deprecated and clunky (OpenGL display lists) and it will be mandated by a standard (DSA is only an optional extension in OpenGL).

**Comment by tapcio** [comment]
@Bigpet
Hym, good argument. 
My hardware is quite old Radeon HD6850, and I only written about that OpenGL is slow and broken in AMD drivers. Some older devices stuck at 13.9 or older drivers, so full working DX9 or DX10/11 for some of Radeon users will be great.

**Comment by acemod13** [comment]
How about having DX10 support?

**Comment by hrydgard** [comment]
DX10 is about as much work to add as DX11 and does not add any compatibility so it's totally pointless.

**Comment by unknownbrackets** [comment]
Actually, I'm not seeing the above happen.  It may have been fixed.

However, the letters are stil misplaced.  In this case, it's doing a render-to-texture, and then blitting that back to the main screen in vertical slices.  The slices end around where you see the text cut off.  This implies to me that it's a scaling issue of some kind, e.g. it's copying incorrectly from the source buffer.

But for me it's actually blending correctly.

-[Unknown]

**Comment by unknownbrackets** [comment]
So actually, the issue with the letters IS dual source related.  It's not scaling after all.

Here's what happens:

1. The screen is drawn, up until the scrolling area.
2. The background, headers, etc. of the scrolling area are drawn.
3. That section is copied (via texture) to another buffer.  This is done with stencil = REPLACE 0xFF, and comes through properly in Direct3D 9.
4. Each line is drawn: first a background (either transparent or the highlight) with is blended but also has stencil = REPLACE 0x00.  This does not come through in Direct3D 9.  Then the text is also blended, and ends up with wrong alpha AFAICT.
5. Once it has drawn all visible line items, it textures this back onto the screen, in vertical strips.  Each strip is drawn with blending, and it seems some of them overlap (accidentally?)  When it does this, it uses stencil = REPLACE 0x00.

If I force the blending on the strips to fixed 0xFFFFFF + fixed 0x000000, it draws the text fine.  However, in this case if there's an item scrolling off the bottom, it's not properly blended as fading out toward the bottom.

-[Unknown]

**Comment by benderscruffy** [comment]
is this still an issue ??

**Comment by DarkD** [comment]
Testing on v1.13.1-722-g49d5b6447. D11 - nonpresent, OGL - nonpresent, D9 - nonpresent, Vulkan - nonpresent. Looks like case closed, good ladies and gentlemen.
