### ISSUE TITLE
No windows 32-bit builds in automated build since v0.9.9.1-1535-g45ec0c8

### ISSUE THREAD

**Issue by Yuuyatails** [hrydgard/ppsspp#7357]
I noticed that since v0.9.9.1-1535-g45ec0c8, there are no 32-bit builds for ppsspp.

This makes me wonder if the support for 32-bit Windows was dropped.

**Comment by sum2012** [comment]
@unknownbrackets @hrydgard 
compile error
![1](https://cloud.githubusercontent.com/assets/2177532/5800245/31e327bc-a017-11e4-9e2a-9592bb7253c1.png)
