### ISSUE TITLE
iOS: Most games crash on loading.

### ISSUE THREAD

**Issue by thedax** [hrydgard/ppsspp#7360]
This is intended to be a blanket issue for all of the reports about games crashing when loading. We have a bunch of them open, and it's silly, so let's discuss causes, fixes, etc. here. I know we have no iOS maintainer, but that doesn't mean we can't keep the issue tracker organised.

**Comment by ppssppios** [comment]
Sound good to me.

Final Fantasy Type-0 crash directly after the first cutscene, when the 3 characters are standing in front of the suzaku gate. Shis only happens with my iPad Air 2, on the 5s it works fine.

iOS 8.1.2
PPSSPP Version 0.9.9.1 - 1572
iPad Air 2

**Comment by brujo5** [comment]
some problems on ios 7.1 - 8.0 are related to the pangu jalibreak (that change dinarec adress) and cause memory leaks.

ios 8.1.1+ is the best for emulator. (taig jalibreak is the most stable)

**Comment by XscypherX** [comment]
So basically if I change my jailbreak from Pangu's 8.1 jailbreak to Taig 8.1.1 jailbreak my problem loading with Assassins Creed: Bloodlines might be fixed. Also, running on iPod Touch 5g, idk if that makes a difference.

**Comment by ppssppios** [comment]
I'm trying to boot FF Type-0 on my iPad Air 2 and iPhone 5s, both on 8.1.2 and Jailbroken using Taig. On iPad Air 2 it crashes while 5s works as it should. Im using the same settings on both devices.

**Comment by jianmingyong** [comment]
Now I see that the app have somehow glitches when I keep on changing option and keep on letting the game run after many crashes.

Well, it kinda let me run my game once in a while messing with the options randomly.

In worst case, ALL words are messed up ( even the ui on the right panel ) and I crashes.

The debug stat also can't display properly, words jumble up and then crash in a sec. ( It only works after a few crashes again )

Something is really wrong and I don't get it. It crashes everytime and only sucess when I randomly play with options to let me run.

**Comment by jianmingyong** [comment]
I think I found my problem. Ios 7.0.4 sure still work but still unstable.

Here is my update:
After I switch my phone to safe mode ( it still crashes sometimes ) but it run my game after 2 to 3 crashes.

I can't see anymore odd text flying around as well. No more odd text after forcing it to pause the game.

So what I did is... I removed the SSL patch for ios 7.1 and below given in the trusted cydia tweak ( suppose to fix some security issue ) and what happen? Now it crash less often and able to let me play the any game after a few crash initially. It seem like the SSL patch broke something that causes my phone not able to display the graphic properly and the text.

Stupid featured tweak and now I am happy to say that it is working with occasional crash at start up a few times at least before it work fully.

**Comment by ppssppios** [comment]
Today i found a method to get ingame in FF Type-0(iPad Air 2 / iOS 8.1.2).

If i Disable Hardware Transform and Enable Software Rendering, the game will no longer crash infront of Suzaku Gate. The screen will be black and you will hear the sound. After 2-3 minutes i make a quicksave within PPSSPP, disable Software Rendering and load the quicksave.

The game wont run fast because Hardware Transform is disabled. If i enable Hardware Transform and load the game, the emulator will crash without showing a frame.

PPSSPP version: 1.0.1 - 343

**Comment by Theo1996** [comment]
ios 7.0.4 ppsspp 1.4.1 doesnt work at all with any games just freezes on game load.

**Comment by unknownbrackets** [comment]
I think games mostly work now in the latest git version / 1.6.x.  There's still issues with PPSSPP hanging after you quit, but at least you can play games.  going to close this.

-[Unknown]
