### ISSUE TITLE
[Feature Request] repair game 's save

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#7362]
Forward from chinese ppsspp forum
Sometime we use save status,but we may misuse so that game 's save is corrupt,cannot save it.
The correction:
Take Monster Hunter Portable 3rd  for example:Find .BIN file,edit it ,type some words,save it.
Return PPSSPP,load save status,use game save to save it,it will ask you game 's save is corrupt,do you want to delete it.Then it will save it.

I think that we can do this as a progammly way.
(I also think that delete the bin file rather than edit might be easier)
I test on Yu-Gi-Oh 6 , the game save 's file is "DATA0"

**Comment by unknownbrackets** [comment]
I don't know if there's any reasonable way for us to detect that the save has been edited / broken.  This seems like game-specific territory at best.

If this is about interaction with savestates, then it's a duplicate of #7244.

-[Unknown]

**Comment by sum2012** [comment]
OK.I close this one
