### ISSUE TITLE
Issues in Lego Harry Potter and other Lego games

### ISSUE THREAD

**Issue by PlayingGames** [hrydgard/ppsspp#7363]
I have been playing a lot on PPSSPP since the release of version 0.7. I have finished the popular games which I played (like LocoRoco and Lilittle big planet) without any problems. But there are some rarer games, in which I have found issues. I would like to help, so I try to report them.
1. Lego Harry Potter Years 1-4
   Save: http://www68.zippyshare.com/v/tKSrv05B/file.html
   The games works up to this point at full-speed without problems, but in this moment you cannot continue because it stops responding to the actions of the player. Tested on PC and Android.
2. Lego Harry Potter Years 5-7
   Save: http://www53.zippyshare.com/v/uTzl3Z4J/file.html
   The games works too up to this point at full-speed without problems, but when you start this stage, there is only a black screen. Only when you chose "read frame-buffers to memory" something is displayed. It appears only at Android, on the PC everything is correct.  
3. Lego Star Wars II: The Original Trilogy
   There are a lot of glitches and missing textures in many levels. The hub works ok.
   ![sw2_1](https://cloud.githubusercontent.com/assets/10484825/5855820/a530f84e-a23c-11e4-893d-2acd6a15624a.jpg)

The version 0.9.9 fixed the issues with menu scrolling, so I finished three Lego games (Star Wars III, Indiana Jones II, Pirates of the Caribbean) witch 100%, and began the ones mentioned above. They are NDS ports and run at full-speed. There are also three Lego games which are PS2 ports - Batman and Indiana Jones I are working without bug's, but on android they are working at half-speed so I didn't finish them (tested at Note 3 and Nexus 5). On windows  they work at full-speed. The Star Wars II seems to work fast enough on Android too, but it's buggy. 

![1408978164354](https://cloud.githubusercontent.com/assets/10484825/5856067/c3f2df24-a23f-11e4-8b54-858548bbef81.jpg)

![1416409631742](https://cloud.githubusercontent.com/assets/10484825/5856069/c842d43a-a23f-11e4-9d9d-4ee3afe6d578.jpg)

Sorry for very bad English. If what I wrote does not make sense, just remove it.

**Comment by daniel229** [comment]
The issue 1 seems not happen to me,I finished that mini game which loaded from your savestate.Did you try the latest git build.
![01](https://cloud.githubusercontent.com/assets/3481559/5868147/9c687fda-a2e0-11e4-888e-488a395af9b9.png)

Compare to the picture from the issue 3, the psp one like the following,also I found out it's flickering when HW transform off.
![201501230945_001](https://cloud.githubusercontent.com/assets/3481559/5868509/8fbdd5d2-a2e5-11e4-93ff-b820e536c7d0.png)

**Comment by daniel229** [comment]
Step Frame does not work for Lego Star Wars II: The Original Trilogy

**Comment by daniel229** [comment]
Software mode flickering since https://github.com/unknownbrackets/ppsspp/commit/0b9db176e933d8f44ab4467fbfe3b31a950d42c5

**Comment by PlayingGames** [comment]
I have tested everything on the stable 0.9.9 relase and newest build v0.9.9.1-1585-gcae58ca on Samsung Note 3, Nexus 5, and PC on default settings, and I cannot finish the mini-game. I have made a video to show it better.

http://www31.zippyshare.com/v/IQzehhma/file.html

Indiana Jones and Batman works on this also slow. The bug in Harry Potter Years 5-7 still happens.

**Comment by daniel229** [comment]
you can't finish the mini-game because you did not use the analog.
http://youtu.be/A955204gGKA.

**Comment by PlayingGames** [comment]
I'm just stupid :( Sorry for spam with the first issue.

**Comment by daniel229** [comment]
Many DRAW PRIM INVALID
https://cloud.githubusercontent.com/assets/3481559/5920459/a5512742-a677-11e4-993a-0d1470d7ff84.png
https://cloud.githubusercontent.com/assets/3481559/5920461/a5532bfa-a677-11e4-9785-ae49496102c8.png
https://cloud.githubusercontent.com/assets/3481559/5920458/a54f6aa6-a677-11e4-8d46-e0b0b553b38c.png
https://cloud.githubusercontent.com/assets/3481559/5920462/a55350d0-a677-11e4-85c5-e72592a92ec6.png
https://cloud.githubusercontent.com/assets/3481559/5920460/a551dc32-a677-11e4-97ca-abde26300f9e.png

**Comment by daniel229** [comment]
Lego Star Wars II: The Original Trilogy fixed in https://github.com/hrydgard/ppsspp/pull/8689
![04](https://cloud.githubusercontent.com/assets/3481559/15365632/92c04794-1d53-11e6-9762-ee025db724a7.png)

**Comment by hrydgard** [comment]
Do the other errors in this thread remain?

**Comment by daniel229** [comment]
Don't know about the second one in Android.

**Comment by unknownbrackets** [comment]
Most likely it was fixed by d920ffdcad86bf43d1e0aaef3cff92179d5bb417, cool.  Or boo, for the game using invalid commands.

I wonder what could cause downloading to be necessary on Android only... maybe an stencil -> alpha issue?

-[Unknown]

**Comment by Silent-Hunter** [comment]
LEGO Harry Potter Years 1-4 doesn't start for me at all with PPSSPP v1.3-705-gb94ad12.

```
OpenGL 2.0 or higher.
53:07:103 Core/Config.cpp:943 I[LOAD]: Loading controller config: /home/silent/.config/ppsspp/PSP/SYSTEM/controls.ini
Pixels: 960 x 544
Virtual pixels: 960 x 544
I: gpu_features.cpp:126: GPU Vendor : NVIDIA Corporation ; renderer: GeForce GTX 965M/PCIe/SSE2 version str: 4.5.0 NVIDIA 375.26 ; GLSL version str: 4.50 NVIDIA
loading control pad mappings from /home/silent/.ppsspp/assets/gamecontrollerdb.txt: SUCCESS!
53:49:562 Core/Config.cpp:1266 I[LOAD]: Failed to read /home/silent/.config/ppsspp/PSP/SYSTEM/ULUS10500_ppsspp.ini. No game-specific settings found, using global defaults.
53:49:562 Core/System.cpp:387 I[BOOT]: PPSSPP v1.3-705-gb94ad12
53:49:562 Core/MemMap.cpp:271 I[MM]: Memory system initialized. Base at 0x2300000000 (RAM at @ 0x2308000000, uncached @ 0x2348000000)
53:49:562 Core/PSPLoaders.cpp:188 I[LOAD]: ULUS10500 : LEGO® Harry Potter™: Years 1-4
53:49:563 Core/Config.cpp:1266 I[LOAD]: Failed to read /home/silent/.config/ppsspp/PSP/SYSTEM/ULUS10500_ppsspp.ini. No game-specific settings found, using global defaults.
53:49:563 Core/PSPLoaders.cpp:246 I[LOAD]: Loading disc0:/PSP_GAME/SYSDIR/EBOOT.BIN...
53:49:563 HLE/sceKernelMemory.cpp:436 I[KERNEL]: Kernel and user memory pools initialized
53:49:594 HLE/sceKernel.cpp:152 I[KERNEL]: Kernel initialized.
53:49:629 Util/BlockAllocator.cpp:391 I[HLE]: -----------
53:49:629 Util/BlockAllocator.cpp:395 I[HLE]: Block: 08800000 - 08804000 size 00004000 taken=1 tag=usersystemlib
53:49:629 Util/BlockAllocator.cpp:395 I[HLE]: Block: 08804000 - 08b14a00 size 00310a00 taken=1 tag=ELF/LEGOHarryPSP
53:49:629 Util/BlockAllocator.cpp:395 I[HLE]: Block: 08b14a00 - 0a000000 size 014eb600 taken=0 tag=(untitled)
53:49:629 Util/BlockAllocator.cpp:397 I[HLE]: -----------
53:49:631 HLE/sceKernelModule.cpp:1243 I[LOAD]: Module LEGOHarryPSP: 089de1e0 089aa0ac 089aa0c4
53:49:655 HLE/ReplaceTables.cpp:1341 I[HLE]: Replaced memcpy at 089a6b80 with hash b7d88567dc22aab1
53:49:655 HLE/sceKernelModule.cpp:1303 I[LOAD]: Exporting ent 0 named LEGOHarryPSP, 2 funcs, 4 vars, resident 089aa478
53:49:655 HLE/sceKernelModule.cpp:1605 I[LOAD]: Module entry: 08804108
53:49:656 root         N[BOOT]: UI/EmuScreen.cpp:219 Loading /home/silent/ROMs/PSP/LEGO_Harry_Potter_1-4.iso...
53:49:657 root         I[KERNEL]: HLE/sceKernelThread.cpp:1975 276=sceKernelCreateThread(user_main, 0880421c, 00000020, 262144, 80004000, 00000000)
53:49:657 root         I[KERNEL]: HLE/sceKernelThread.cpp:2064 0=sceKernelStartThread(276, 33, 09fffed0)
53:49:657 root         I[KERNEL]: HLE/sceKernelThread.cpp:2103 __KernelReturnFromThread: 0
53:49:659 user_main    W[DISP]: HLE/sceDisplay.cpp:757 Video out requested, not supported: mode=0 size=0,0
53:49:659 user_main    W[DISP]: HLE/sceDisplay.cpp:763 80000104=sceDisplaySetMode(0, 0, 0): invalid size
53:49:677 user_main    I[HLE]: HLE/scePower.cpp:384 scePowerSetClockFrequency(333,333,166)
53:49:827 user_main    I[KERNEL]: HLE/sceKernelThread.cpp:1975 286=sceKernelCreateThread(FUSION THREAD 0x88f4f78, 0892758c, 0000006e, 16384, 00004000, 00000000)
53:49:827 user_main    I[KERNEL]: HLE/sceKernelThread.cpp:2064 0=sceKernelStartThread(286, 4, 08c4b5b0)
53:49:828 user_main    I[UTIL]: HLE/sceUtility.cpp:306 0=sceUtilityLoadModule(00000300)
53:49:843 user_main    I[UTIL]: HLE/sceUtility.cpp:306 0=sceUtilityLoadModule(00000301)
53:49:876 user_main    I[SCESAS]: HLE/sceSas.cpp:250 sceSasInit(08b13b00, 256, 32, 0, 44100)
53:49:876 user_main    I[KERNEL]: HLE/sceKernelThread.cpp:1975 322=sceKernelCreateThread(FUSION THREAD 0x8922e5c, 0892758c, 0000006e, 65536, 00004000, 00000000)
53:49:876 user_main    I[KERNEL]: HLE/sceKernelThread.cpp:2064 0=sceKernelStartThread(322, 4, 08cf0900)
53:49:877 user_main    I[UTIL]: HLE/sceUtility.cpp:306 0=sceUtilityLoadModule(00000302)
53:49:893 user_main    I[ME]: HLE/sceAtrac.cpp:1001 0=sceAtracGetAtracID(00001000)
53:49:893 user_main    I[KERNEL]: HLE/sceKernelThread.cpp:1975 326=sceKernelCreateThread(FUSION THREAD 0x8926058, 0892758c, 0000006e, 65536, 00004000, 00000000)
53:49:893 user_main    I[KERNEL]: HLE/sceKernelThread.cpp:2064 0=sceKernelStartThread(326, 4, 08cf1730)
53:49:893 user_main    I[ME]: HLE/sceAtrac.cpp:1001 1=sceAtracGetAtracID(00001000)
53:49:893 user_main    I[KERNEL]: HLE/sceKernelThread.cpp:1975 329=sceKernelCreateThread(FUSION THREAD 0x8926058, 0892758c, 0000006e, 65536, 00004000, 00000000)
53:49:893 user_main    I[KERNEL]: HLE/sceKernelThread.cpp:2064 0=sceKernelStartThread(329, 4, 08cf1910)
53:49:894 user_main    E[FileSys]: FileSystems/ISOFileSystem.cpp:323 File /PSP_GAME/USRDIR/pspdata/legoharrypotterpsp.fib not found
53:49:894 user_main    E[IO]: HLE/sceIo.cpp:1385 ERROR_ERRNO_FILE_NOT_FOUND=sceIoOpen(disc0:/PSP_GAME/USRDIR/pspdata/legoharrypotterpsp.fib, 00000001, 00000000) - file not found
53:49:947 user_main    I[UTIL]: HLE/sceUtility.cpp:306 0=sceUtilityLoadModule(00000100)
53:49:973 user_main    I[UTIL]: HLE/sceUtility.cpp:306 0=sceUtilityLoadModule(00000101)
53:49:995 user_main    W[NET]: HLE/sceNet.cpp:129 sceNetInit(poolsize=524288, calloutpri=49, calloutstack=0, netintrpri=49, netintrstack=0) at 0891db84
53:49:995 user_main    I[NET]: HLE/sceNetAdhoc.cpp:166 sceNetAdhocInit() at 0891db94
53:49:995 user_main    W[KERNEL]: HLE/sceKernelThread.cpp:1962 sceKernelCreateThread(name=AdhocThread): unsupported options parameter 00001000
53:49:995 user_main    I[KERNEL]: HLE/sceKernelThread.cpp:1975 333=sceNetAdhocInit()
53:49:995 user_main    I[NET]: HLE/sceNetAdhoc.cpp:192 sceNetAdhocctlInit(6144, 50, 09fff570) at 0891dc2c
```

**Comment by unknownbrackets** [comment]
Are there still issues in the latest git build?

Note: if you are getting a crash, like the above, try disabling wifi and then restart.  It's not really related if wifi makes this game crash.

-[Unknown]

**Comment by Panderner** [comment]
Lego Harry Potter Years 1-4 reaches in-game and should be playable
![Screenshot_2020-09-27-11-40-13-17_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/94355385-482eb300-00b6-11eb-84aa-5ffc8247e0fa.png)

**Comment by unknownbrackets** [comment]
I'm going to close this then, sounds like it's working.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
