### ISSUE TITLE
Crash when playing YuGiOh TF Special

### ISSUE THREAD

**Issue by rarnu** [hrydgard/ppsspp#7368]
The new game YuGiOh Tag Force Special cannot be played in story mode on Android.

[cut]

Push the ISO into device and start it with any character, after a lone conversation(till the selection dialog appears) PPSSPP will crash.

Here is the crash log, only one line:
01-24 22:11:36.208: E/InputDispatcher(1250): channel '43660e20 org.ppsspp.ppsspp/org.ppsspp.ppsspp.PpssppActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

**Comment by Bigpet** [comment]
don't link to piracy sites please

**Comment by rarnu** [comment]
I'm so sorry but seems it's the only location for downloading this game now.

**Comment by Bigpet** [comment]
Dude, illegally downloading a game is illegal, you can't link to any site that hosts the game. Piracy is not OK.

**Comment by hrydgard** [comment]
Link removed.

Apparently it works fine on PC: http://forums.ppsspp.org/showthread.php?tid=14424  so this seems to be an android-only issue.

**Comment by sum2012** [comment]
@rarnu what is your PPSSPP version ?

**Comment by rarnu** [comment]
The last version I compiled myself. And my device is XiaoMI 4.

**Comment by sum2012** [comment]
Do you mean v0.9.9.1-1601-gf1bca47 ?

**Comment by sum2012** [comment]
I do not have problem,download ppsspp from http://buildbot.orphis.net/ppsspp/
PPSSPP v0.9.9.1-1601-gf1bca47 
Phone:LG nexus 5

![screenshot_2015-01-25-17-54-04](https://cloud.githubusercontent.com/assets/2177532/5891076/641d692e-a4bb-11e4-886e-1ac9a333f8b0.jpg)

**Comment by rarnu** [comment]
So strange,  I'm using Nexus5 now and it works good. Seems some compatibility issues happened on XiaoMi4.

Thanks a lot.

**Comment by unknownbrackets** [comment]
Is this working okay now in latest versions?  Might have been a driver bug, I suppose?

-[Unknown]

**Comment by Emulatorer** [comment]
Didn't experience this crash issue for a long time ago while playing YGO Tag Force Special in my android potato phone
### Screenshot
![Screenshot_2019-06-27-10-32-22](https://user-images.githubusercontent.com/37603562/60229001-0caba480-98c7-11e9-8a9a-ee932ad8e63c.png)
![Screenshot_2019-06-27-10-32-29](https://user-images.githubusercontent.com/37603562/60229014-16350c80-98c7-11e9-9096-64fe015c06c9.png)
![Screenshot_2019-06-27-10-32-44](https://user-images.githubusercontent.com/37603562/60229025-1d5c1a80-98c7-11e9-9384-bb770c4d4a0b.png)
![Screenshot_2019-06-27-10-33-00](https://user-images.githubusercontent.com/37603562/60229036-24832880-98c7-11e9-9d67-21b330861d82.png)

**Comment by unknownbrackets** [comment]
Thanks for the update - going to close this, then.

-[Unknown]
