### ISSUE TITLE
God Eater 2 - Sound drop/stuttering at 100% speed with the latest build

### ISSUE THREAD

**Issue by KenGodEaterwiki** [hrydgard/ppsspp#7370]
Like the title said, the sound randomly drop for no reason even at the Den (base)
This happen when the WASAPI is added. I also tried the new build where you can choose audio backend (pick DirectSound) and the thing still occur

I also hope that you guys can fix the NPC crash for v1.4 of the game...

**Comment by LunaMoo** [comment]
Starting from v0.9.9.1-1472-g82ccce9 ~ which added Dophin audio resampler -  I do hear small artifacts from time to time, but I'm unable to reproduce anything serious like sound dropping or stuttering.

**Comment by KenGodEaterwiki** [comment]
That probably because I'm using my laptop's speaker

As for artifacts, do heard some buzzing sound when things get chaotic (shooting bullet is the most obvious...)

**Comment by KenGodEaterwiki** [comment]
Hello?

**Comment by hrydgard** [comment]
That might help.

**Comment by LunaMoo** [comment]
Don't know if @KenGodEaterwiki issues were of same nature, but I don't hear any more artifacts, thanks.:)

**Comment by KenGodEaterwiki** [comment]
@hrydgard I'll test that later because I have school today

**Comment by KenGodEaterwiki** [comment]
The sound drop still occur but here what I gathered with the audio debug tool:

Overruns: 21754
It flat but randomly drop down right before an big audio drop (1-2 secs)

Sample rate: 44300
The same but causing a small audio drop (half of a second)

I hope @hrydgard  can figure out what going on :/

**Comment by KenGodEaterwiki** [comment]
Okey, I did some more observation

The sample rate goes crazy then overruns goes crazy and audio drop happen

**Comment by hrydgard** [comment]
Hm, that should not be possible :(  The whole point of the resampler is to eliminate (as long as there's enough CPU power) this type of glitches by covering them by slightly adjusting the sample rate... And it works great on my machines.

So, I'll need to know some details. What type of laptop is this? Are you running on battery or wall plug power when it happens, or doesn't it matter? Which version of Windows are you running on? If you change the audio backend to DirectSound in the settings, do the glitches get worse, better or disappear entirely?

**Comment by KenGodEaterwiki** [comment]
- wall plug power (the battery does not last long....)
- Window 7 Home Premium 32-bit
- I did restart the emu
- It just happen, even in a small place

Laptop's specs:
Radeon Mobility HD 7130
AMD E1-1200(@1400 MHZ)
Catalyst beta: 14.501.1003.0 (aka first Omega driver release)
2.5 GB DDR3 400MHZ

**Comment by vnctdj** [comment]
@hrydgard wrote :
> change the audio backend to DirectSound in the settings (and restart the emu! It does not take effect immediately, I do realize the UI does not make that clear)

So, should we create a prompt similar to the one we created for changing GPU backend ? I mean the following sentence : `Changing GPU backends requires PPSSPP to restart. Restart now? -> Yes/No`.

**Comment by KenGodEaterwiki** [comment]
Audio sync turned off and the audio drop still occur...
I guess I'll stick to 1462-g1b055fd

**Comment by KenGodEaterwiki** [comment]
The 1.0 seems to not having the problem anymore, I don't know what @hrydgard do or does but it's gone! Thank you Henrik :smile:

**Comment by unknownbrackets** [comment]
Hurray.

-[Unknown]

**Comment by snkagawa** [comment]
still can't bring npc :'3
ppsspp v1.0 default setting
