### ISSUE TITLE
Auto Assemble Error (Debugger)

### ISSUE THREAD

**Issue by Abystus** [hrydgard/ppsspp#7390]
The auto assembler within the debugger will always compile to a 'j' when specifying the branch always instruction 'b'.

Example Line:
```
0889E590 bne s0,zero,0x0889E5C8 (Instruction Bytes: 1600000D)
```

Auto Assemble:
```
b 0x0889E5C8 (Instruction Bytes: 1000000D)
```

Result:
```
j 0x0889E5C8 (Instruction Bytes: 0A227972)
```

They do relatively the same action, but it should be compiling to 1600000D instead of 0A227972 when specifying a 'b' instruction.

**Comment by LunaMoo** [comment]
if you want:
    b 0x0889E5C8 (Instruction Bytes: 1000000D)
try to write full opcode:
    beq zero,zero,0x0889E5C8
should work, althrough yeah, it would be nice to have it corrected

**Comment by Abystus** [comment]
Thanks for the reply LunaMoo. I'll use that syntax until things get corrected (seems like a simple change).

**Comment by unknownbrackets** [comment]
@Kingcom this seems not major, what's your opinion?

-[Unknown]

**Comment by Kingcom** [comment]
Hm, yeah, I guess b should be assembled to a branch type, even if it doesn't really make a difference. It's easy enough to change, so I'll do that in my Parser branch.
Not a PPSSPP specific issue, in any case.
