### ISSUE TITLE
Direct Sound backend make emulator crash on launch

### ISSUE THREAD

**Issue by zackdreaver** [hrydgard/ppsspp#7391]
So i tried to use direct sound because wasapi backend make crackling noise in crisis core.
i changed it ingame from auto to direct sound, and the crackling was gone, until i close the emulator,
then tried to launch it again, then it crash.
its crash after this window show up.
http://s13.postimg.org/taqilnrsn/New_Picture.jpg

Build: v0.9.9.1-1623-g2df04ba
Backend: d3d9
Os: WinXP
SoundDevice: Realtek HD

I tried to to changed "AudioBackend" to 1 inside PPSSPP.ini, and the problem was solved.

**Comment by hrydgard** [comment]
You say the crackling was gone? That's really strange as the audio backend change does not take effect until you restart the emulator..

DirectSound certainly shouldn't crash though. I'll have to look into it...

**Comment by zackdreaver** [comment]
yes the crackling noise when you in great cave mission

**Comment by zackdreaver** [comment]
i guess the latest build did the fix,
v0.9.9.1-1647-g6420f5f
