### ISSUE TITLE
Final Fantasy Dissidia 012: Ghosting issue

### ISSUE THREAD

**Issue by GamerzHell9137** [hrydgard/ppsspp#7392]
I remember posting already somewhere about it and it seems its still not fixed for w/e reason.
Here's what GE debugger says about it

![dis1](https://cloud.githubusercontent.com/assets/2002038/5985236/0116595c-a8e0-11e4-9609-a14826aea4fd.png)

http://puu.sh/ffLkj/dbdcb7d1fc.txt

![dis2](https://cloud.githubusercontent.com/assets/2002038/5985244/170dd4a6-a8e0-11e4-9f67-26c3eed80308.png)

http://puu.sh/ffLqz/c3e66529dc.txt

![dis3](https://cloud.githubusercontent.com/assets/2002038/5985248/2300f0d6-a8e0-11e4-80a4-7b7936c35725.png)

Changing rendering mode doesn't solve it.

**Comment by Bigpet** [comment]
Looks intentional to me. It may look a little different than on a real PSP because of the dithering but I don't think it's the result of inaccurate emulation.

**Comment by GamerzHell9137** [comment]
Is it? Doesn't look like it can be triggered in software rendering.

**Comment by GamerzHell9137** [comment]
In software rendering it looks the same.
If its intentional then could it be possible to upscale the ghost/shadow like things?

**Comment by LunaMoo** [comment]
It looks like a dark bloom of some kind, something to be fixed by "Lower resolution for effects" hack, however it doesn't seem to be using lower buffer size like most games using such effects, so the hack will not even detect it:|.

**Comment by hrydgard** [comment]
It's intentional and part of the game, it just doesn't look very good at higher resolutions than 1x..  Would need some kind of game specific hack to "fix".

**Comment by unknownbrackets** [comment]
Since it's drawing in throughmode, we're not even going to try shrinking the buffer, since if we did, we would break tons of games.  I don't really think this is fixable except by running at lower resolutions or a game specific hack, as you mentioned.

Given that, I think this is the realm of cheats or game hacks which belongs more on the forum, I think.

-[Unknown]
