### ISSUE TITLE
Fate/Extra graphical distorting v0.9.9.1

### ISSUE THREAD

**Issue by mikasa-su-casa** [hrydgard/ppsspp#7393]
Hi,

Using v0.9.9.1 and experiencing some graphical issues with Fate/Extra. After a couple weeks the usual background area starting looking warped, then the areas started disappearing entirely along with character models. 

What it's like normally:
![ulus10576_00011](https://cloud.githubusercontent.com/assets/10445833/5986346/7bb5f42e-a8a9-11e4-92c4-301e1be1aa6a.jpg)

Graphical distorting:
![ulus10576_00025](https://cloud.githubusercontent.com/assets/10445833/5986347/8ebee918-a8a9-11e4-822f-e2285f0b5173.jpg)

Dialogue filled parts of the game with black background and white text getting new backgrounds of the battle screen:
![ulus10576_00026](https://cloud.githubusercontent.com/assets/10445833/5986365/e16efdd8-a8a9-11e4-98ef-e25f15ca42fe.jpg)

Parts of the area missing: 
![ulus10576_00031](https://cloud.githubusercontent.com/assets/10445833/5986371/f8e2bf54-a8a9-11e4-871f-7ddb1a303ca0.jpg)
![ulus10576_00032](https://cloud.githubusercontent.com/assets/10445833/5986372/f8e31f1c-a8a9-11e4-9c17-66db5cbf87d4.jpg)

This happens consistently around the same phase in the game, even when starting over the game runs fine. Could the .iso be corrupt in some way given these symptoms?

If there's any further info I can provide to help debug, it would be much appreciated.

Thanks!

**Comment by daniel229** [comment]
Can you try the latest build http://buildbot.orphis.net/ppsspp/index.php?m=fulllist ,v0.9.9.1 is very old.

**Comment by mikasa-su-casa** [comment]
Wow, I had no idea that was such an old version! This resolved all the issues. Thank you for your help.
