### ISSUE TITLE
[MONSTER HUNTER FREEDOM UNITE] Plate didn't show

### ISSUE THREAD

**Issue by kanibaliz** [hrydgard/ppsspp#7396]
hey guys i am playing mhfu from my android my phone is samsung note 3 neo. playing mhfu great but one issue, some of my armour i can't see it.. even i press select it didn't show the image. and when i build that plate and use it my body is transparant and i it's so annoying to not build great plate just because i can't see it .. does anyone know this issue ?? my friend with another phone(xperia z) is works fine all items. and when i on the unstable memory the game crash because that plate. and if i turn it off the plate is invisible. thanks in advance :D

![2015-02-01-12-37-29 1](https://cloud.githubusercontent.com/assets/10793540/5991183/90193c7a-aa0f-11e4-87f5-f2dc27ba994e.png)

**Comment by Pajee** [comment]
Have you tried playing it on default settings? If not, go ahead. If it's the same, maybe it's a hardware problem.

You could also try to copy the settings that your friend uses and see if it works.

**Comment by unknownbrackets** [comment]
If it happens with default settings, try turning off hardware transform.  Might be related to the Mali 400 issues we've seen in the past, but your GPU is newer and shouldn't have those issues...

-[Unnown]

**Comment by vnctdj** [comment]
This seems really strange to me...
Are you sure your .iso file is not corrupted ? You should try to re-dump it cleanly.

**Comment by kanibaliz** [comment]
i already try default setting and try copy paste the iso again.
and none of them work. 
and i off the setting hardware transform too and didn't work..

maybe i will download the iso again, because i take iso from my psp friends.

vnctdj, how to redump ? is that same with copy paste the iso ?

**Comment by kanibaliz** [comment]
oh and btw i download version and try all of them .. and didn't work. my another friends with pad samsung got the same issue. is that all samsung phone maybe has this issue
but my friend xpria is works fine ...

**Comment by kanibaliz** [comment]
And i play together with friends in gathering hall.
When i use my invisible plate. In my xpria phone see the same. In his phone my plate is invisible too. But his plate is just fine

**Comment by kanibaliz** [comment]
FINALLY FOUND THE PROBLEM.. ON MY ISO. THE ARMOUR GUY IS MISSING I DON'T KNOW WHY..

when i create new character is woman. it's works fine...
what problem is this ??? can somebody help meee

**Comment by kanibaliz** [comment]
Finally done with this problem, i think there ia an error for male plate on Mhfu universal version so i change to europe and my save data still the same. Case closed
