### ISSUE TITLE
Auto configure in control mapping deletes all other configurations

### ISSUE THREAD

**Issue by GamerzHell9137** [hrydgard/ppsspp#7399]
The auto config is awesome but it deletes all other configurations like the keyboard or other controllers.
It would be a good thing that it leaves all of them and just adds the new controller.

**Comment by unknownbrackets** [comment]
It would have to at least delete any other controllers.  Unless this a request to support per-controller-id configs, but I'm not convinced there's a real need for that which isn't better served by game-specific configs.

-[Unknown]

**Comment by GamerzHell9137** [comment]
The only thing that annoys me is that i can't leave the game by pressing ESC on keyabord but gotta button it on the controller now. In all older revisions you would use ESC to leave. I normally use the keyboard and mouse to leave and set things up in the settings.
I guess i gotta get used to the new stuff and leave games with the controller.

**Comment by hrydgard** [comment]
Hm, ESC should work no matter what, let me see..

**Comment by hrydgard** [comment]
Does that change make you happy? :)

**Comment by GamerzHell9137** [comment]
More than you can imagine lol 
Thanks :D

**Comment by unknownbrackets** [comment]
Okay then, closing based on the last two comments.

-[Unknown]
