### ISSUE TITLE
Persona 3, black screen whenever I try to enter the dorm

### ISSUE THREAD

**Issue by kolbika** [hrydgard/ppsspp#7400]
Hi, on 7/11 as the male protagonist, I try to enter to the dorm after school but every time it gives me a black screen and the music is still playing. I tried multiple things but non of them worke. Can you help me? I hope I didn't wasted that 26 hours

**Comment by GamerzHell9137** [comment]
System,Build,Settings,etc

**Comment by unknownbrackets** [comment]
You will also want to try to avoid using savestates - save in game and load it.  Lastly, make sure you're using the latest git build (which will soon be 1.0.)

Does it still happen doing that?

-[Unknown]

**Comment by kolbika** [comment]
I somehow managed to make it work but thanks for the helping
