### ISSUE TITLE
The savestate slot did not complete show up in pause menu.

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#7402]
![01](https://cloud.githubusercontent.com/assets/3481559/5995044/326aa7b2-aac3-11e4-8830-76d9d0e10de5.png)

**Comment by unknownbrackets** [comment]
Well, it scrolls iirc, but yeah, was trying to think of good options to move things around so it could git on one screen...

-[Unknown]

**Comment by daniel229** [comment]
No scroll bar at the moment,even scrolls bar can't help the slot 5.

**Comment by hrydgard** [comment]
Argh :( I should know better than to make last-minute changes like that..

Okay, bugfix release it is. 1.0.1 tomorrow or wednesday.

**Comment by hrydgard** [comment]
@daniel229 Fixed in https://github.com/hrydgard/ppsspp/commit/9e162f30abd9869d804e24305e62d0caa1ffc3d7

**Comment by daniel229** [comment]
That's good.I found another bug in the slot icons,there's a black box in the middle of each icon.
![01](https://cloud.githubusercontent.com/assets/3481559/5997710/4cb14860-aafa-11e4-9afb-18e68f079f4f.png)

**Comment by hrydgard** [comment]
Oh, yeah, that's supposed to show the slot number. good catch, fixing.

**Comment by daniel229** [comment]
Perfect with the last change.Thanks.
