### ISSUE TITLE
PPSSPP 1.0 (OS X): "PPSSPPSDL cannot be opened because of a problem."

### ISSUE THREAD

**Issue by vanillagamer** [hrydgard/ppsspp#7403]
Having an issue when trying to run PPSSPP on OS X 10.10.2. I've installed Homebrew and SDL via the instructions on the download page (http://build.ppsspp.org/?page/downloads#osx).

When I attempt to launch PPSSPP, the app does not launch and I am told "PPSSPPSDL cannot be opened because of a problem."

Console.log reads as follows:

> 2/2/15 1:15:26.627 AM ReportCrash[405]: Attempt to read info_array in pid 404 failed, address was 7fff63bae4f0
> 2/2/15 1:15:26.628 AM ReportCrash[405]: Attempt to read info_array in pid 404 failed, address was 7fff63bae4f0
> 2/2/15 1:15:26.628 AM ReportCrash[405]: Attempt to read info_array in pid 404 failed, address was 7fff63bae4f0
> 2/2/15 1:15:26.630 AM ReportCrash[405]: Attempt to read info_array in pid 404 failed, address was 7fff63bae4f0
> 2/2/15 1:15:26.631 AM ReportCrash[405]: Attempt to read info_array in pid 404 failed, address was 7fff63bae4f0
> 2/2/15 1:15:26.632 AM ReportCrash[405]: Attempt to read info_array in pid 404 failed, address was 7fff63bae4f0
> 2/2/15 1:15:26.684 AM com.apple.xpc.launchd[1]: (com.apple.xpc.launchd.oneshot.0x10000004.PPSSPPSDL[404]) Service exited due to signal: Trace/BPT trap: 5
> 2/2/15 1:15:26.727 AM ReportCrash[405]: Saved crash report for PPSSPPSDL[404] version ??? to /Users/logan/Library/Logs/DiagnosticReports/PPSSPPSDL_2015-02-02-011526_Logans-MacBook-Air.crash
> 2/2/15 1:15:26.851 AM Problem Reporter[407]: Failed to connect (_imageWell) outlet from (ProblemReportWindowController) to (NSImageView): missing setter or instance variable

**Comment by ifonefox** [comment]
What does the log file "/Users/logan/Library/Logs/DiagnosticReports/PPSSPPSDL_2015-02-02-011526_Logans-MacBook-Air.crash" say? I had a similar crash, and it said

```
Dyld Error Message:
  Library not loaded: /usr/local/lib/libSDL2-2.0.0.dylib
  Referenced from: /Applications/PPSSPP.app/Contents/MacOS/PPSSPPSDL
  Reason: image not found
```
I fixed this by doing the command "brew install sdl2"

**Comment by angelXwind** [comment]
Yes, PPSSPP 1.0 (and the Dev versions of 0.9.9.1) requires SDL2. Forgot to mention that. Instructions have been updated accordingly.

**Comment by unknownbrackets** [comment]
I'll close this then, as the instructions were updated - thanks.

If it's still an issue with sdl2 installed, please comment and we'll reopen.

-[Unknown]

**Comment by rsdev69** [comment]
brew install sdl2 libzip
