### ISSUE TITLE
Running a game requires extra mouse click now (Linux, SDL2)

### ISSUE THREAD

**Issue by Pulfer** [hrydgard/ppsspp#7404]
Since PPSSPP 1.0 running a game requires extra mouse click (Linux, SDL2).

1. Click at any game title.
2. See game info screen with menu (run, configure etc)
3. Click "Run". The game doesn't run but the menu is no longer active (no highlighting on mouse over).
4. Click "Run" once more. The game runs.

**Comment by Pulfer** [comment]
Still happens with PPSSPP 1.0. Only pre-gameplay menu is affected, other screens' menus work with mouse clicks as they should.

**Comment by Pulfer** [comment]
Looks like the bug is caused by some choice being focused.

We have "Play" choice focused by default ("UI::SetFocusedView(play)" line) in GameScreen menu, that's why first I thought it's pre-game menu specific bug. But if I press keys to navigate choices in other menus (that applies focused state), the bug happens there as well. First click only disables focused state, second click does the real choice action.

**Comment by hrydgard** [comment]
Just clicking the game (left mouse button) at the main screen should go directly into the game though, not to the game info screen. Doesn't it?

**Comment by Pulfer** [comment]
In most cases both left and right button clicks go into the game info screen. But after clicking many times with left button I managed to go into the game (maybe some kind of events race here and usually right-click event wins).

**Comment by hrydgard** [comment]
That sounds wrong.. Works fine on Mac here (only left mouse button goes into the game screen menu) but we might be mishandling SDL mouse events somehow.

**Comment by Pulfer** [comment]
Looks like this doesn't work properly:

-------------
        void Update(const InputState &input_state) override {
                if (down_ && holdEnabled_)
                        holdFrameCount_++;
                else
                        holdFrameCount_ = 0;
                // Hold button for 1.5 seconds to launch the game options
                if (holdFrameCount_ > 90) {
                        TriggerOnHoldClick();
                }
        }
-------------

For me it seems that 1500, not 90 gives 1.5 seconds. So even plain click usually triggers the event, unless it's lighting fast.

Perhaps #7531 is caused by this too.

**Comment by hrydgard** [comment]
That means that you are running the menu at 1000 fps, which is wrong. It seems SDL is not being v-synced correctly.

**Comment by Pulfer** [comment]
BTW, do we need holdEnabled_ to be true on desktop?
