### ISSUE TITLE
Static Analysis

### ISSUE THREAD

**Issue by ElfoLiNk** [hrydgard/ppsspp#7407]
I have run a static analysis on the master branch with last commit https://github.com/hrydgard/ppsspp/commit/682ef7d083b30d398487a455ef512ce38bcf28d7.

The analysis was executed on Windows 8.1 x64 Build

https://drive.google.com/file/d/0B296LD22NB3ldnF0UkVEd0Z6TEU/view?usp=sharing

**Comment by hrydgard** [comment]
You've got some very picky settings there (for example, these are hardly important: "Incorrect index type: ThumbOpcodes[not a memsize-type]. Use memsize type instead."). 
 
But I'm sure there are one or two real issues in there, I'll take a look soon.

**Comment by unknownbrackets** [comment]
There's also a lot of "Dangerous magic number used" for "LEA(32, etc. etc.)".

I've filtered down the file to remove some external dependencies like libpng and glew.  From scanning through the file briefly, I didn't see anything major, but there indeed are likely at least a couple.

[PVS-Studio-log2.txt](https://github.com/hrydgard/ppsspp/files/67691/PVS-Studio-log2.txt)

-[Unknown]

**Comment by unknownbrackets** [comment]
A lot of our refactoring has changed code this points at.  I'm going to close this since we have made some changes based on static analysis, and the rest of the log is probably a bit far off from the current code.

-[Unknown]
