### ISSUE TITLE
Naruto Shippuuden Naltimate Impact small screen in non-buffered rendering in new version in Android

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#7408]
Only happen in Android,old version do not have probrem
![screenshot_2015-02-02-19-53-08](https://cloud.githubusercontent.com/assets/2177532/6000255/dde318f6-ab16-11e4-8f3d-c352842eb080.jpg)

**Comment by hrydgard** [comment]
Hm, can you bisect?

Does changing the display resolution in settings affect it?

**Comment by sum2012** [comment]
Changing the display to native not affect.
I get this bug report from chinese ppsspp forum.
Anyway,I can bisect,but need some times

**Comment by sum2012** [comment]
Today morning result:
good
v0.9.9.1-112-g7b30824
bad
v0.9.9.1-158-g5e07a40

**Comment by hrydgard** [comment]
Thanks, that's a more managable range.  7b30824 to 5e07a40

**Comment by unknownbrackets** [comment]
Maybe #6800 by not resetting the viewport somewhere?

-[Unknown]

**Comment by daniel229** [comment]
Desktop reproduce this by these setting
Non-buffered rendering on
Simulate block transfer on
resolution / windows size < 1
happen in v0.9.9.1-152-g413ea36 ,not in v0.9.9.1-145-g140eb82
![01](https://cloud.githubusercontent.com/assets/3481559/6012179/fc6a4dc6-ab7f-11e4-9056-9b50311edaa4.png)
![02](https://cloud.githubusercontent.com/assets/3481559/6012180/fc6a594c-ab7f-11e4-9078-06f7a61eef61.png)

**Comment by unknownbrackets** [comment]
So, that means yes, definitely #6800.

Well, since switching FBOs updates the viewport, maybe we should just do `glstate.viewport.restore();` in `RebindFramebuffer()` when buffered rendering is forced off.

-[Unknown]

**Comment by hrydgard** [comment]
That might do it?

**Comment by sum2012** [comment]
Test on v1.0-22-gca512ea in Android , fixed Thanks
