### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by MasterHalo** [hrydgard/ppsspp#7409]
the ppsspp emulator crashes when ever I reach a certain point in the game and the game is : Crash Of The Titans

**Comment by hrydgard** [comment]
What point in the game? Do you have a savegame file or a save state?

**Comment by sum2012** [comment]
What device ? (Windows 32 bit,64bit,Android,ios)

**Comment by MasterHalo** [comment]
Before a cutscene in crash of the Titans

**Comment by MasterHalo** [comment]
Yes I have a save file and it crashes before a cutscene in crash of the Titans and it's on iOS 8.1.2

**Comment by unknownbrackets** [comment]
Okay, then closing as a duplicate of #7360 (most all games crash on iOS, apparently depending on jailbreak used and possibly how many other apps you have running.)

-[Unknown]
