### ISSUE TITLE
Keyboard keys "e" & "c"

### ISSUE THREAD

**Issue by ImSpecial** [hrydgard/ppsspp#7410]
They seem to be used to navigate menus on the windows build, not sure if intentional or not as it makes changing your PSP nickname impossible if using the letter c, as c acts as an alternative "back" key it seems. Using the latest dev build v1.0-7-g682ef7d

**Comment by Bigpet** [comment]
Is that with default control keys? Or did you by any chance map those keys yourself

**Comment by ImSpecial** [comment]
They are not as my control.ini is the only file I bring over between builds, and "c" just happens to be my circle button for the keyboard, but I did "restore defaults" to see if that fixes things, it sets the "x" letter as circle by default, but the same problems as before but with "x" instead of "c". So typing a nickname with a letter "x" will just cancel out the screen.

**Comment by Bigpet** [comment]
Yep, that I can reproduce

**Comment by hrydgard** [comment]
Thanks for reporting, never noticed :) should be fixed now.
