### ISSUE TITLE
 Growlanser IV missing texture

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#7416]
Missing textures in the game pause menu,but sometime it show up some.No builds worked before,with changingsome setting still not work,openGL D3D,softwareGPU non of them worked.

PPSSPP
![02](https://cloud.githubusercontent.com/assets/3481559/6015090/3209e1e6-abab-11e4-9c71-7db2804025a7.png)

PSP
![201502031323_001](https://cloud.githubusercontent.com/assets/3481559/6015091/320d7b94-abab-11e4-8ce4-c9689d90fd17.png)

Sometime it shows up one.
![03](https://cloud.githubusercontent.com/assets/3481559/6015103/5ef68132-abab-11e4-80e8-4f2197a3251e.png)

GEdebugger
![01](https://cloud.githubusercontent.com/assets/3481559/6015105/6c78e7e6-abab-11e4-8296-e6494a56e709.png)

more tabs
https://gist.github.com/daniel229/b42f1deed015476b58ed

**Comment by unknownbrackets** [comment]
If it sometimes shows up, maybe it's rendered to a temporary surface once, and just depends on if we decimate the FBO or not before it's used as a texture.  Does the log look any different (especially FBO destruction) between it showing up and not showing?

-[Unknown]

**Comment by daniel229** [comment]
I don't konw how to trigger from showing up to not showing yet,but it won't show up after loading gamesave,and show up when I go into another area,during this time the info log not chang anything.

**Comment by daniel229** [comment]
Another graphical bug missing background.There is a block transfer right before .
openGL
![04](https://cloud.githubusercontent.com/assets/3481559/6017218/b863ddf8-abc6-11e4-8c76-ff5ec116e34c.png)

softwareGPU
![05](https://cloud.githubusercontent.com/assets/3481559/6017217/b8623764-abc6-11e4-8329-67923eed8c4e.png)

the log
![06](https://cloud.githubusercontent.com/assets/3481559/6017230/d8d35bfe-abc6-11e4-94d0-37ccff77ef7f.png)

**Comment by hrydgard** [comment]
hmm, skipped..

**Comment by daniel229** [comment]
After comment out that skipped check,it works right.

**Comment by daniel229** [comment]
Another game has the transfer download skip,Gakuoh -The Royal Seven Stars- +Meteor
```
W[G3D]: Common\FramebufferCommon.cpp:687 Block transfer download 04089800 -> 04110030 skipped, 384+1 is taller than 272
```
OpenGL
![01](https://cloud.githubusercontent.com/assets/3481559/6142502/4d1b4f36-b1f2-11e4-8f15-847256b2cdbd.png)

softwaregpu
![02](https://cloud.githubusercontent.com/assets/3481559/6142506/683b33f8-b1f2-11e4-8835-f7175c081266.png)

if don't skip (there is a small border on the top)
![03](https://cloud.githubusercontent.com/assets/3481559/6142509/7380e050-b1f2-11e4-9e09-7a19baf0b0a2.png)

**Comment by unknownbrackets** [comment]
Well, `384+1 is taller than 272` sounds very much like it ought to be skipped... (384 is the starting y coord, and 1 is the height.)

But then, why does it even think that framebuffer matches... hmm.

-[Unknown]

**Comment by unknownbrackets** [comment]
The original issue may be a timing issue.  Does IO timing affect it?  I didn't notice before you had mentioned it doesn't even always work in the software renderer.

How about this for the skip check?
```c++
		WARN_LOG_ONCE(btd, G3D, "Block transfer download %08x -> %08x", srcBasePtr, dstBasePtr);
		FlushBeforeCopy();
		if (g_Config.bBlockTransferGPU && !srcBuffer->memoryUpdated) {
			const int srcBpp = srcBuffer->format == GE_FORMAT_8888 ? 4 : 2;
			const float srcXFactor = (float)bpp / srcBpp;
			const bool tooTall = srcY + srcHeight > srcBuffer->bufferHeight;
			if (srcHeight <= 0 || (tooTall && srcY != 0)) {
				WARN_LOG_ONCE(btdheight, G3D, "Block transfer download %08x -> %08x skipped, %d+%d is taller than %d", srcBasePtr, dstBasePtr, srcY, srcHeight, srcBuffer->bufferHeight);
			} else {
				if (tooTall)
					WARN_LOG_ONCE(btdheight, G3D, "Block transfer download %08x -> %08x dangerous, %d+%d is taller than %d", srcBasePtr, dstBasePtr, srcY, srcHeight, srcBuffer->bufferHeight);
				ReadFramebufferToMemory(srcBuffer, true, static_cast<int>(srcX * srcXFactor), srcY, static_cast<int>(srcWidth * srcXFactor), srcHeight);
			}
		}
		return false;  // Let the bit copy happen
```

If `srcY` is 0, then even if the height is taller it may still be correct/safe.

-[Unknown]

**Comment by daniel229** [comment]
that fixes the Growlanser IV ,but not Gakuoh -The Royal Seven Stars- +Meteor which is 384+1 is taller than 272.

**Comment by unknownbrackets** [comment]
If you change this:
```c++
				} else {
					srcWidth = byteStride * height / vfb_bpp;
					srcHeight = 1;
				}
```

To like:
```c++
				} else {
					srcWidth = byteStride * height / vfb_bpp;
					srcHeight = 2;
				}
```

Does it change to 384+2?  Might be some tricky thing where it doesn't match at all.  Hard to detect transfers that shouldn't happen like in God of War.

-[Unknown]

**Comment by daniel229** [comment]
Yes, change to 384+2

**Comment by unknownbrackets** [comment]
What if you set `match = false;` after `srcHeight = 2;`?

Ugh, that stuff is tricky.  But it should be 1 because the byte strides match?  Or, I'm not so sure about `width == srcStride`...  can you use the debugger to log some of those values?  Just find:
```c++
void FramebufferManagerCommon::FindTransferFramebuffers(VirtualFramebuffer *&dstBuffer, VirtualFramebuffer *&srcBuffer, u32 dstBasePtr, int dstStride, int &dstX, int &dstY, u32 srcBasePtr, int srcStride, int &srcX, int &srcY, int &srcWidth, int &srcHeight, int &dstWidth, int &dstHeight, int bpp) const {
```

Add above that:
```c++
#pragma optimize("", off)
```

And you can run it in release mode and still get the values.

-[Unknown]

**Comment by daniel229** [comment]
Is it like this
```
#pragma optimize("", off)
void FramebufferManagerCommon::FindTransferFramebuffers(VirtualFramebuffer *&dstBuffer, VirtualFramebuffer *&srcBuffer, u32 dstBasePtr, int dstStride, int &dstX, int &dstY, u32 srcBasePtr, int srcStride, int &srcX, int &srcY, int &srcWidth, int &srcHeight, int &dstWidth, int &dstHeight, int bpp) const {
	NOTICE_LOG(G3D, "dstBasePtr = %08x dstStride = %08x dstX = %08x dstY = %08x srcBasePtr = %08x, srcStride = %08x, srcX = %08x, srcY = %08x, srcWidth = %08x, srcHeight = %08x, dstWidth = %08x, dstHeight = 08x, bpp = %08x ", dstBasePtr, dstStride, dstX, dstY, srcBasePtr, srcStride, srcX, srcY, srcWidth, srcHeight, dstWidth, dstHeight, bpp);
```

log
https://gist.github.com/daniel229/3f62da02b54a617a6a4b

**Comment by unknownbrackets** [comment]
Really seems like this game is doing the same sort of thing with the short width.  Well, I was wondering more about the values in the loop but this is okay.

Hmm...

-[Unknown]

**Comment by daniel229** [comment]
The missing texture problem was fixed in https://github.com/hrydgard/ppsspp/pull/7716 ,Looks perfect this game.

**Comment by unknownbrackets** [comment]
Sweet, it fixed something games actually did after all.

-[Unknown]
