### ISSUE TITLE
Controls>Edit touch control layout>Visibility>Toggle all broken

### ISSUE THREAD

**Issue by diedricm** [hrydgard/ppsspp#7417]
After checking some boxes and upon touching "toggle all" I could not check or uncheck any other box in this menu until I restarted ppsspp.

**Comment by hrydgard** [comment]
Hm, I can't reproduce this problem, it seems to work fine?

**Comment by diedricm** [comment]
Okay forgot to write that it only happens in the ingame settings menu. It does not happen if the settings screen is launched from the ppsspp main window. Does this change anything?

Maybe I should have also written that it happens on Android. Im using a Xperia Play with standard 2.4 Android. Logs did not show anything strange.
Sry for bad report.

**Comment by unknownbrackets** [comment]
Has this changed at all?

-[Unknown]

**Comment by diedricm** [comment]
Yes sorry just tested again now.
