### ISSUE TITLE
Directx 9 windows 32 bit crash all game when close since v1.0-3-g80d6109

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#7419]
@hrydgard 

Debug build only have this message
"E: gfx_es2\glsl_program.cpp:280: E: Deleting null GLSL program!"

Release build crash stuck
![1](https://cloud.githubusercontent.com/assets/2177532/6019720/9956a284-abde-11e4-9deb-8d24b1159664.png)

**Comment by sum2012** [comment]
![2](https://cloud.githubusercontent.com/assets/2177532/6019765/2c1fdc34-abdf-11e4-99b0-242258eafbc4.png)

**Comment by hrydgard** [comment]
Thanks, I'll take a look soon.

**Comment by hrydgard** [comment]
Can you check if this is fixed now?

**Comment by issuer** [comment]
Tested with 1.0-20 and it's fixed on Windows.

**Comment by hrydgard** [comment]
@sum2012 , please re-open if you still see problems.

**Comment by sum2012** [comment]
Yes,fixed,thanks
