### ISSUE TITLE
PPSSPP Windows 32 bit Crashes when switching backend from Direct3D9 to OpenGL

### ISSUE THREAD

**Issue by LPatamon** [hrydgard/ppsspp#7421]
Hello. I want to report an issue with the backend selection option on PPSSPP Windows 32bit.

When I switch from OpenGL to Direct3D9 all works fine. The emulator restarts itself and the backend gets switched to Direct3D9 succesfully, but when I try to switch the backend back to OpenGL, the emulator crashes.

The issue starts on build v1.0-3-g80d6109 which has the following log commit:

"Better error checking in D3D9 init"

I think something on that modification caused the current crashing when switching GPU backends. I can set the backend manually by editing the ppsspp.ini file and the emulator switches to opengl succesfully, but I can't do it through the emulator's option to change it, both the menu option and the settings section option (the one that gives you a prompt saying that PPSSPP has to restart in order to switch backends with a yes and no options for you to choose) end in crash when switching from Direct3D9 to OpenGL.

I tested builds before the one I mentioned and all works correctly with the backend switch. My PC is not even a year old and the graphics card is a very recent model (has the Windows 8 compatible logo), so is not on my side the problem.

Hope you can take a look at it. Guess something on the Direct3D9 error check improvement caused the issue.

Thanks in advance :)

**Comment by Bigpet** [comment]
probably the same underlying issue as #7419

**Comment by Bigpet** [comment]
Something is seriously fucking with either the optimizer or the stack  of the function https://github.com/hrydgard/ppsspp/blob/master/Windows/EmuThread.cpp#L86

The values for "nativeHost" (and when you change it then "oldHost") get overwritten in release mode. This can be changed by changing the declarations to `Host * volatile nativeHost` and `Host * volatile oldHost` (if they aren't volatile they may be optimized out, they don't show in the debugger and I'm too lazy to read the disasm).

So it's either the goto in the function or some rogue memory writes

**Comment by hrydgard** [comment]
Hm, scary..

**Comment by Bigpet** [comment]
written: 
![image](https://cloud.githubusercontent.com/assets/465677/6021885/3ff828c2-abb9-11e4-8015-da6c73483394.png)


read:
![image](https://cloud.githubusercontent.com/assets/465677/6021851/0e0fc3ce-abb9-11e4-98ae-6794b2ea3239.png)

something that's called inbetween is polluting ebx without restoring it?

**Comment by Bigpet** [comment]
Huh, EBX is callee saved and D3D9_Init does not correctly restore EBX

**Comment by hrydgard** [comment]
That's... bizarre. I'll dig into it tonight as well..

**Comment by Bigpet** [comment]
Stack is off by +8 bytes after `push ebx` compare to before `pop ebx`, not that it matters since the value on the stack is being overwritten anyway, I have no clue how this can happen

**Comment by hrydgard** [comment]
That seems to have taken care of it.
