### ISSUE TITLE
PPSSPP fails to build under OSX 10.7

### ISSUE THREAD

**Issue by CloudAndLeaf** [hrydgard/ppsspp#7423]
If I try to build version 1.0 under OSX 10.7 I receive the following error:

Linking CXX executable PPSSPPSDL.app/Contents/MacOS/PPSSPPSDL
Undefined symbols for architecture x86_64:
"___exp10", referenced from:
_av_strtod in libavutil.a(eval.o)
"___sincos_stret", referenced from:
_av_display_rotation_set in libavutil.a(display.o)
_ff_mdct_init in libavcodec.a(mdct_float.o)
_ff_ps_init in libavcodec.a(aacps.o)
"___sincosf_stret", referenced from:
_ff_ps_init in libavcodec.a(aacps.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

It's an error that already happened with previous versions and was fixed. I tried to search here on github and all the issues regarding this error or similar ones are closed.

**Comment by hrydgard** [comment]
Ugh, I forgot about that.. Sorry. Please build it and send a pull request with the results.

**Comment by CloudAndLeaf** [comment]
Thanks for the answer, unfortunately I tried to compile it myself but I get similar errors and the build fails.

Undefined symbols for architecture x86_64:
"_cmnMemAlloc", referenced from:_aac_encode_init in libavcodec.a(libvo-aacenc.o)
"_cmnMemCheck", referenced from:_aac_encode_init in libavcodec.a(libvo-aacenc.o)
"_cmnMemCopy", referenced from:_aac_encode_init in libavcodec.a(libvo-aacenc.o)
"_cmnMemFree", referenced from:_aac_encode_init in libavcodec.a(libvo-aacenc.o)
"_cmnMemSet", referenced from:_aac_encode_init in libavcodec.a(libvo-aacenc.o)

**Comment by unknownbrackets** [comment]
Did you compile it using this?
https://github.com/hrydgard/ppsspp-ffmpeg/blob/master/mac_x86-64.sh

Hmm, that's odd.

-[Unknown]

**Comment by unknownbrackets** [comment]
Does this work for you?

https://github.com/hrydgard/ppsspp-ffmpeg/compare/master...unknownbrackets:mac-10.6?expand=1

Would appreciate anyone who could test it on a version of Mac OS X that was released this decade.

-[Unknown]

**Comment by CloudAndLeaf** [comment]
I tried it on 10.7 and it worked, thanks!
