### ISSUE TITLE
God of War Ghost Of Sparta & Chains Of Olympus Mirror Effect, IPHONE

### ISSUE THREAD

**Issue by shae23** [hrydgard/ppsspp#7424]
There is a Mirror effect when playing on iphone, doesnt happen on android or windows, makes things really hard to see sometimes
![1](https://cloud.githubusercontent.com/assets/10815842/6025603/9e73b62c-ab88-11e4-9e7f-d1f650b1ceb6.jpg)
![2](https://cloud.githubusercontent.com/assets/10815842/6025602/9e71292a-ab88-11e4-90a5-89c51ab54fa1.jpg)
![3](https://cloud.githubusercontent.com/assets/10815842/6025604/9e7697e8-ab88-11e4-8612-4e02fc71a076.jpg)
![4](https://cloud.githubusercontent.com/assets/10815842/6025605/9e7c1e2a-ab88-11e4-8ee2-5251e98bcdc3.jpg)

**Comment by unknownbrackets** [comment]
Well, I guess this is probably more of the PowerVR GPU getting Fs on its maths tests.

Does it go away if you check the "disable slower effects" option?

-[Unknown]

**Comment by shae23** [comment]
yeah it happens just the same with it enabled

**Comment by brujo5** [comment]
Tried gow ghost of sparta 

No problem in my ip5S. Slower effects on/off fine.
![image](https://cloud.githubusercontent.com/assets/4172898/6034425/9fab1d4e-abdf-11e4-96ec-fbb10ea80e5c.jpg)

**Comment by brujo5** [comment]
Gow Chain of olimpus

Is fine to!!
![image](https://cloud.githubusercontent.com/assets/4172898/6034686/1beb214e-abe3-11e4-95f1-e01b513fa137.jpg)

**Comment by shae23** [comment]
iPhone 5, iOS 8.1.2, both games have the same issue even with the latest version of the emu

**Comment by brujo5** [comment]
both idevices have powervr gpu but ip5S support more extension in OGL 3.0 versus  ip5 use OGL 2.0

**Comment by unknownbrackets** [comment]
Well, the 5 has a PowerVR SGX543MP3 (which I know it or its drivers can't do at least some basic math properly), but the 5S has a PowerVR G6430 (which I think doesn't have that problem.)

-[Unknown]

**Comment by shae23** [comment]
I guess that means it's an iPhone 5 specific problem and the chances of seeing it fixed are very slim, sighs

**Comment by unknownbrackets** [comment]
Has anything improved here with v1.7.1?  If it only affects iPhone 5 (released 6 years ago) and lower, and seems to be a driver bug, maybe we should close at this point...

-[Unknown]

**Comment by hrydgard** [comment]
Closing because too old, only affects outdated devices.
