### ISSUE TITLE
Dpad down not working Linux

### ISSUE THREAD

**Issue by cra0zy** [hrydgard/ppsspp#7428]
Dpad down is not working with xbox 360 wireless controller on Linux, when trying to change controls it's like I'm not even pressing it. It also doesn't detect it on "test analogs".

Some notes:
<ul>
<li>Xbox 360 wireless controller</li>
<li>The controller is working</li>
<li>Ubuntu 14.04</li>
<li>sdl version</li>
<li>from ppa:ppsspp/testing</li>
</ul>

**Comment by aljen** [comment]
Same problem here with ps3 controller, I found that ppsspp with qt frontend (at least on my system) can't process all events from gamepads, if window was not created by sdl. Here is fix for it, add 
SDL_setenv("SDL_JOYSTICK_ALLOW_BACKGROUND_EVENTS", "1", 0);
right before SDL_Init(SDL_INIT_JOYSTICK | SDL_INIT_VIDEO); at 
https://github.com/hrydgard/ppsspp/blob/master/SDL/SDLJoystick.cpp#L16 and it should work fine.

**Comment by cra0zy** [comment]
That didn't really help. I am using xboxdrv as driver and it has a feature to mimic xpad, so I added "--mimic-xpad" and that did allow me to use dpad down. This still is a bug, but at least there is a way around it.

**Comment by chemstar** [comment]
i did have the problem that ABXY buttons have been used as up/down/left/right with the xboxdrv.
i fixed it changing SDLJoystick.h to

...
#else
		SDLJoyButtonMap[0] = NKCODE_BUTTON_2;
		SDLJoyButtonMap[1] = NKCODE_BUTTON_3;
		SDLJoyButtonMap[2] = NKCODE_BUTTON_4;
		SDLJoyButtonMap[3] = NKCODE_BUTTON_1;
		SDLJoyButtonMap[4] = NKCODE_BUTTON_7;
		SDLJoyButtonMap[5] = NKCODE_BUTTON_8;
		SDLJoyButtonMap[6] = NKCODE_BUTTON_5;
		SDLJoyButtonMap[7] = NKCODE_BUTTON_6;
		SDLJoyButtonMap[8] = NKCODE_BUTTON_9;
		SDLJoyButtonMap[9] = NKCODE_BUTTON_10;
		SDLJoyButtonMap[10] = NKCODE_BUTTON_11;
		SDLJoyButtonMap[11] = NKCODE_BUTTON_12;
		SDLJoyButtonMap[12] = NKCODE_BUTTON_13;
		SDLJoyButtonMap[13] = NKCODE_BUTTON_14;
		SDLJoyButtonMap[14] = NKCODE_BUTTON_15;
		SDLJoyButtonMap[15] = NKCODE_BUTTON_16;

		SDLJoyAxisMap[0] = JOYSTICK_AXIS_X;
		SDLJoyAxisMap[1] = JOYSTICK_AXIS_Y;
		SDLJoyAxisMap[2] = JOYSTICK_AXIS_Z;
		SDLJoyAxisMap[3] = JOYSTICK_AXIS_RZ;
		SDLJoyAxisMap[4] = JOYSTICK_AXIS_LTRIGGER;
		SDLJoyAxisMap[5] = JOYSTICK_AXIS_RTRIGGER;

**Comment by cra0zy** [comment]
@chemstar you misunderstood me, it's not that the controls are wrong, it's that the dpad down button is not detected. All the other buttons are working ok, and if I use --mimic-xpad, all the buttons are working.

**Comment by chemstar** [comment]
i will check it tomorrow to see if i can use it with the mimic-xpad option

**Comment by cra0zy** [comment]
Your problem has nothing to do with this... mimic-xpad will do nothing for you... there is a controls section in ppsspp settings...

**Comment by chemstar** [comment]
but if i remap buttons there i still cant use my controller inside ppsspp menue. it is jumping from left to right when using abxy buttons

**Comment by hrydgard** [comment]
I guess we were hoping that at least a few buttons, enough to navigate the menu, would always be consistently available and working on all platforms, but it is not turning out that way on Linux :(

**Comment by cra0zy** [comment]
So on Ubuntu 15.04 with newest ppsspp and xboxdrv this error is gone, and therefor I am closing this issue.

**Comment by mikebutash** [comment]
Curious, what versions of xboxdrv and ppsspp are you using now?  I get the missing down button with ppsspp refusing to see it (with or without mimic-xpad) issue using a ppa build as late a version as i can find (ppsspp-sdl-1.0.1+r71.f2.n1205.p2.l1607.a159.t83~19~ubuntu14.04.1).  Looks like 15.04 is using the same builds, unless canonical is fixing and patching something in their build for it.

My xboxdrv is 0.8.5, all other joystick tools show it fine.  Thanks!

**Comment by cra0zy** [comment]
I was using whichever version was the newest at that time.

Now I've switched to using xpad with steamos patch to get lights working.

**Comment by GAMELASTER** [comment]
i runned DPAD by using Libretro PPSSPP, but then i found the parameter on xboxdrv --use-dpas-as-buttons or similiar, what enable this :-)
