### ISSUE TITLE
Enabling cheat make emulator hang on win32

### ISSUE THREAD

**Issue by zackdreaver** [hrydgard/ppsspp#7430]
When i tried to run a game with cheat enabled,
my emulator hang (not even running with sound in background).
then i tried run the game withouth cheat enabled, game run just fine,
until i enabling the cheat, it hang again.
here's game menu SS, there is no cheat in the list.
http://s9.postimg.org/mhs4ti5wf/New_Picture.jpg
and this SS when i tried to close the emulator
http://s29.postimg.org/5ojblr8af/New_Picture2.jpg

first build known with this bug: 
v1.0-15-ge6d9bdb

**Comment by hrydgard** [comment]
Which game? Which cheat? This doesn't seem to be a universal issue.

**Comment by zackdreaver** [comment]
Crisis Core sir, usa region

**Comment by hrydgard** [comment]
That should take care of it.
