### ISSUE TITLE
Jokker commands issue. Jokker codes cease working when pressing any other keys.

### ISSUE THREAD

**Issue by AizerMortenort** [hrydgard/ppsspp#7431]
I don't know what causes this but if I have a jokker code with L+Circle+Triangle and press ANY other keys the code will stop working. This shouldn't happen as some codes require you doing certain actions while you activate them and doing this will cause them not to work unless you release all other buttons than the necessary jokker keys.

In one word every other non used for the jokker command buttons acts like REVERSE key and this should not happen unless stated in the codes part/lines. 

I was wondering all the time what makes most of my character moves not to work correctly and this is the issue...each key acts like a reverse jokker command and I have only to press the necessary buttons for jokker command to work while it shouldn't be like this.

**Comment by hrydgard** [comment]
What is "Jokker"?

**Comment by AizerMortenort** [comment]
Maybe i didn't wrote it correctly.
It is a code that requires certain condition to be met to execute the following lines after it or skip them.
In my case it a code that requires a key/s to be presses to skip or execute the following code lines after it. What I try to do is to execute them but if i press any other key than for example L+Circle+Triangle then the code suddenly stops working.

**Comment by LunaMoo** [comment]
0xD type:
Jocker Code 0xD00000dd 0x1nnnnnnn This command will check the psp controller for the combination specified by nnnnnnn.
If equal it will execute the next dd+1 code lines else it will skip them.
It can check for combinations of up to 3 buttons
and it can be used even with kernel mode only buttons (like note, screen, etc)
Combination are sums of the values found here: Button Codes
NOTE: remapsp remaps are ignored by this function.

Inverse Jocker Code 0xD00000dd 0x3nnnnnnn This command will check the psp controller for the combination specified by nnnnnnn.
If not equal it will execute the next dd+1 code lines else it will skip them.
It can check for combinations of up to 3 buttons
and it can be used even with kernel mode only buttons (like note, screen, etc)
Combination are sums of the values found here: Button Codes
NOTE: remapsp remaps are ignored by this function.

Button Codes:
SELECT 0x00000001
START 0x00000008
DPAD UP 0x00000010
DPAD RIGHT 0x00000020
DPAD DOWN 0x00000040
DPAD LEFT 0x00000080
L TRIGGER 0x00000100
R TRIGGER 0x00000200
TRIANGLE 0x00001000
CIRCLE 0x00002000
CROSS 0x00004000
SQUARE 0x00008000
HOME 0x00010000
HOLD 0x00020000
NOTE 0x00800000
SCREEN 0x00400000
VOLUME UP 0x00100000
VOLUME DOWN 0x00200000
WLAN UP 0x00040000
REMOTE HOLD 0x00080000

Currently it works when exact combination is pressed and nothing else, never was a fan of key activated cheats, so I don't know if on real psp it works when other buttons are pressed or not, I guess both would have positive and negative sides depending on what you're actually using it for.

**Comment by AizerMortenort** [comment]
Example :

_L 0xD0000003 0x10003100  (Left Trigger + Circle + Triangle) - Positive so it should execute the following 4 lines of codes so here it is:

_L 0xD0000003 0x10003100
_L 0x12345678 0x12345678
_L 0x12345678 0x12345678
_L 0x12345678 0x12345678
_L 0x12345678 0x12345678

This should work even if Press other keys than Left Trigger +Circle+Triangle but pressing any other keys cause it to skip the codes and not to work. In fact pressing any other keys reverses the code and it shouldn't be like that.

A reverse code example of this will be Press UP pad to reverse the following code lines and if Press Left Trigger +Circle + Triangle code will work but once I press UP Pad despite holding the above mentioned keys code should stop working.

This is a reversed joker command code. 
_L 0xD0000004 0x30000010 
_L 0xD0000003 0x10003100
_L 0x12345678 0x12345678
_L 0x12345678 0x12345678
_L 0x12345678 0x12345678
_L 0x12345678 0x12345678

Currently PPSSPP causes each button not mentioned in a joker command to act like reverse key despite this not being added to the codes as a function.

@LunaMoo 
Yes on real psp it works and it should be left to work,
This is why REVERSE joker is after all.

**Comment by AizerMortenort** [comment]
if (!executeNextLines)
SkipCodes(1);
}
break;
}
else if (arg >> 28 == 0x1 || arg >> 28 == 0x3) { // Buttons dependent ignore cheat code
// Button Code
// SELECT 0x00000001
// START 0x00000008
// DPAD UP 0x00000010
// DPAD RIGHT 0x00000020
// DPAD DOWN 0x00000040
// DPAD LEFT 0x00000080
// L TRIGGER 0x00000100
// R TRIGGER 0x00000200
// TRIANGLE 0x00001000
// CIRCLE 0x00002000
// CROSS 0x00004000
// SQUARE 0x00008000
// HOME 0x00010000
// HOLD 0x00020000
// WLAN 0x00040000
// REMOTE HOLD 0x00080000
// VOLUME UP 0x00100000
// VOLUME DOWN 0x00200000
// SCREEN 0x00400000
// NOTE 0x00800000
u32 buttonStatus = __CtrlPeekButtons();
int skip = (comm & 0xFF) + 1;
if (arg >> 28 == 0x1)
if (buttonStatus == (arg & 0x0FFFFFFF)) // cheat code likes: 0xD00000nn 0x1bbbbbbb;
break;
else
SkipCodes(skip);
else
if (buttonStatus != (arg & 0x0FFFFFFF)) // cheat code likes: 0xD00000nn 0x3bbbbbbb;
break;
else
SkipCodes(skip);
break;
}
else if (arg >> 28 == 0x4 || arg >> 28 == 0x5 || arg >> 28 == 0x6 || arg >> 28 == 0x7) {
int addr1 = GetAddress(comm & 0x0FFFFFFF);
int addr2 = GetAddress(arg & 0x0FFFFFFF);
code = GetNextCode();
if (true)
if (Memory::IsValidAddress(addr1) && Memory::IsValidAddress(addr2)) {
int comm2 = code[0];
int arg2 = code[1];
int skip = (comm2 & 0xFFFFFFFF);
int memoryValue1 = 0;
int memoryValue2 = 0;
switch (arg2 & 0xF) {
case 0x0: // 8Bit
memoryValue1 = Memory::Read_U8(addr1);
memoryValue2 = Memory::Read_U8(addr2);
break;
case 0x1: // 16Bit
memoryValue1 = Memory::Read_U16(addr1);
memoryValue2 = Memory::Read_U16(addr2);
break;
case 0x2: // 32Bit
memoryValue1 = Memory::Read_U32(addr1);
memoryValue2 = Memory::Read_U32(addr2);
break;
default:
break;
}
switch (arg >> 28) {
case 0x4: // Equal
if (memoryValue1 != memoryValue2)
SkipCodes(skip);
break;
case 0x5: // Not Equal
if (memoryValue1 == memoryValue2)
SkipCodes(skip);
break;
case 0x6: // Less Than
if (memoryValue1 >= memoryValue2)
SkipCodes(skip);
break;
case 0x7: // Greater Than
if (memoryValue1 <= memoryValue2)
SkipCodes(skip);
break;
default:
break;
}
}
}
else
break;

As far as I know there are two types of Joker codes one is 
D00000xx 0x1xxxxxxx - where it should be positive 
and 
D00000xx 0x3xxxxxxx where this is a reverse type.

from what i read in the script above you made is so it skips if any other button/s are pressed. This isn't right and should be modified so only when a reverse code is used to skip or when a CONDITIONAL/ test code isn't met . Jokker codes should be left to work despite any other keys being pressed. Imagine a game where you are to press only two keys to make a move and being able to walk around with Pad button, The same case is here my friends. This should be corrected lol ;)

**Comment by hrydgard** [comment]
Okay, now I understand what you mean :)

Shouldn't be super hard to fix the logic, why don't you have a go at it yourself? You seem to be able to read it :)

**Comment by AizerMortenort** [comment]
I am able to read most of it but I don't know what exactly to change. I have some ideas but I am afraid to try them out. 

If we press additional keys - the code gets added to it's value. 

Here is the case:

// SELECT 0x00000001
// START 0x00000008 

We have jokker command with select:
_L 0xD0000000 0x10000001
_L 0x12345678 0x12345678 this line is executed when select is pressed.

if we press both Select+Start then the jokker commands value will get:

 _D0000000 0x10000009 which is both Select+Start
the engine should still accept select as being pressed and execute the code

_L 0xD0000000 0x10000001
_L 0x12345678 0x12345678 
unless we strictly say it that pressing start button will reverse it.
_L 0xD0000001 0x30000008 - Start Button acts here as a reverse command. 
_L 0xD0000000 0x10000001
_L 0x12345678 0x12345678

we can also make START+Select as a reverse but that would be pointless as select button is already pressed

The code should continue to work BOTH reverse or positive despite pressing any other keys IF We still press select button. Only by pressing START will cause it to stop working. 



What i understand here:

if (arg >> 28 == 0x1) this must be for positive codes?
if (buttonStatus == (arg & 0x0FFFFFFF)) // cheat code likes: 0xD00000nn 0x1bbbbbbb; This should be the values of the buttons currently pressed?
break;  This should mean execute following lines?
else
SkipCodes(skip); This means the codes skips if any other buttons are pressed or value of the jokker command isn't equal to the pointed one. As luna moo said it is a strict check correct? 

Then the suggestion is it should be made to execute codes once the POINTED/Required buttons are pressed despite any other buttons are pressed or not and to skip if the POINTED/REQUIRED buttons aren't pressed.

**Comment by hrydgard** [comment]
OK, I think I got it. Let me know if that helps!

**Comment by AizerMortenort** [comment]
Alright I am gonna wait for you to merge it into a release. Care to send me a test one?

**Comment by AizerMortenort** [comment]
@hrydgard Works flawlessly! Perfect work. Still haven't tested reverse codes. If any issue I will report it back.
