### ISSUE TITLE
PPSSPP Gold Android Slows down on Xiaomi Redmi-1S for Monster Hunter Freedom Unite

### ISSUE THREAD

**Issue by pvrajeshkumar** [hrydgard/ppsspp#7432]
I have PPSSSPP Gold for Android.

I'm getting slowness when I play "Monster Hunter Freedom 2". Graphics Frames drop down very slow & audio is stuttering. Can be reproduced in Pokke Village or in "Yian-Kut-Ku Practice quests" in Grand Arena.

I'm using "Xiaomi Redmi-1S" mobile. Specifications are below.

OS:         Android OS, v4.3 (Jelly Bean)
Chipset:    Qualcomm MSM8228 Snapdragon 400
CPU:    Quad-core 1.6 GHz Cortex-A7
GPU:    Adreno 305

Please suggest best option or fix this slowness on Redmi-1S mobile ASAP.

**Comment by pvrajeshkumar** [comment]
Forgot the memory specification.
Redmi-1S has 1GB RAM.
Hope the specs & details are all clear.

**Comment by pvrajeshkumar** [comment]
Not looking into this?
It is purchased version of PPSSPP Android.
So, expecting some comment/fix for this. :)

**Comment by hrydgard** [comment]
If it's just a bit of slowness, there's not much to look into, not all games run full speed on all devices, that's just an unfortunate fact of emulation and varying Android performance..

If it suddenly drops very low though it might be some kind of bug..  Do you see this in other games too? Does it get down to single digit FPS?

**Comment by pvrajeshkumar** [comment]
Yes. GTA (GTA Liberty city) also sllows down very much. Can't play at all.
FPS as I remember, was below 30. 20 to 30.
Sound is stuttering, Graphics is also slow.

Seems like a bug for the above mentioned.

**Comment by Bigpet** [comment]
Haven't tested the game but that sounds rather normal to me. Did you try enabling auto frameskip?

**Comment by pvrajeshkumar** [comment]
Yes. I did those settings.
I have set the Auto Frame Skip.
I have set the alternate speed to 25.

FPS goes into single digit.

My game is Monster Hunter. When we enter the Grand Arena for Yian-Kut-Ku practice quests, always it slows down. Also in any quest, it slows down.
FPS is between "5" to "15". When we make the player to run, it drops down to 5 FPS. (You can check in Pokke village it self)
Audio gets choppy.
Graphics also makes the play slow. I mean, when we make the player to Run, player walks in a slow motion. In such games, slowness matters in fact.

I feel this is a bug on the Specifications mentioned above.

By the way, "Grand Theft Auto Liberty City" doesn't run on PC at all. I have good PC configuration in fact. Graphics & Audio both are very very slow. Can't play at all.

Please check it & get back.

**Comment by r1c4rd0** [comment]
> I have set the alternate speed to 25.

Wouldn't that cause the speed to slow down to 1/4 of the possible speed the game is able to achieve?
Why don't you leave alternate speed on 0?

**Comment by sum2012** [comment]
It might be same issue as #7336

**Comment by pvrajeshkumar** [comment]
I have upgraded to PPSSPP 1.0 latest version. Seems I don't have that issues on my Redmi-1S mobile. But, I just played for 1 mins only. Let me see how it works after some time. 

Last time, last version, I also saw that when we play for long period, it slows down.

I will check & report if I reproduce the issue again.

**Comment by leopard20** [comment]
@unknownbrackets I don't think this is an issue anymore because: A. No one has this phone anymore. B. It's most probably fixed by now

**Comment by unknownbrackets** [comment]
I know that Monster Hunter is still (unfortunately) faster with "software skinning" disabled, or at least so I'm told.

Other than that, agreed this is probably fixed - performance should be much better now.  Since we haven't received other reports, I'm going to mark it closed.  If it's still a problem feel free to comment.

-[Unknown]
