### ISSUE TITLE
OneLua Homebrew missing text

### ISSUE THREAD

**Issue by jkpwed** [hrydgard/ppsspp#7433]
OneLua Homebrew missing text (note: ltn0.pgf-ltn15.pgf fonts are working fine)

Settings:
Fast memory (unstable)          -Unchecked
Multithreaded (experimental)   -Checked *optional
Save path in My Documents    -Checked *optional

try this or the code below:
http://wololo.net/talk/viewtopic.php?f=2&t=40908

good
ppsspp-v0.9.9.1-1004-g14bb92c-windows-amd64

bad
ppsspp-v0.9.9.1-1005-g6760863-windows-x86
ppsspp-v0.9.9.1-1006-g25a8752-windows-amd64

http://onelua.x10.mx/
script.lua

font = font.load ("flash0:/font/ltn9.pgf");
black = color.new(0,0,0);
white = color.new(255,255,255)
while true do
screen.print(0,10,"Test:",0.4,color.new(250,0,0)) --this is missing text ppsspp-v0.9.9.1-1005 and up
screen.print(font,0,40,"Test 2",0.5,white,black,3) --this always works
screen.flip()
end

**Comment by hrydgard** [comment]
Interesting, that's this change: 

https://github.com/hrydgard/ppsspp/commit/67608639c53adb42020e131a9e85922947cd219f

Another SSE jit bug? :/   @unknownbrackets  :)

**Comment by jkpwed** [comment]
Sorry I checked again I replaced the fonts folder flash0 with my own now all this work good:
good:ppsspp-v0.9.9.1-1004-g14bb92c-windows-amd64
good:ppsspp-v0.9.9.1-1005-g6760863-windows-x86
good:ppsspp-v0.9.9.1-1006-g25a8752-windows-amd64
good:ppsspp-v1.0-49-g6cae957-windows-amd64
