### ISSUE TITLE
Project Diva Extend freezes after selecting any song.

### ISSUE THREAD

**Issue by Fowz** [hrydgard/ppsspp#7434]
Well, I lurked sometime here and didn't find anyone with the same problem then I created this.

After confirming the song and difficult:
![npjh50465_00000](https://cloud.githubusercontent.com/assets/10855150/6049313/732f6ca2-ac9d-11e4-9342-e08dc237a9d9.jpg)

The game literally freezes doing some kind of "beat" (like when you slap something) song and the speed drops to 5~15% but after a little time the PPSSPP doesn't even respond:
![issue](https://cloud.githubusercontent.com/assets/10855150/6049419/5b888736-ac9e-11e4-915e-f8df85b730b3.jpg)

As you can see I'm using the PPSSPP Gold 0.9.9.1 and the game version (?) is NPJH50465, I activated and disabled all the visual enhances and Fast Memory with no success.

**Comment by hrydgard** [comment]
Please upgrade to 1.0, I know this game works fine now (I thought it worked fine on 0.9.9.1 as well, but there you go..)

**Comment by GamerzHell9137** [comment]
Game worked fine on 0.9.9.1 but yeah, upgrade to 1.0 like Henrik said.

**Comment by Fowz** [comment]
Henrik you created a monster, on 0.9.9.1 I couldn't even use the anisotropic filtering because that would lag some games now I'm even activating an 2x anti-aliasing and the speed doesn't even budget, DUDE. Ah and the Project DIVA Extend runs smooth too, problem solved.

It's a bit off-topic but how could I show gratitude besides financial support? Man this is just... wow. I can't even express in words.

I'm making PPSSPP public at my circles, it's the least I can do, but get it as a big Thank You.
