### ISSUE TITLE
peace walker cutscene neverending loop

### ISSUE THREAD

**Issue by tiamat999** [hrydgard/ppsspp#7436]
It happens on the cutscene after beating the first mission can't even get to the Base

**Comment by hrydgard** [comment]
Which version of PPSSPP are you running? Android or PC?

**Comment by tiamat999** [comment]
im running on android 1.0

**Comment by unknownbrackets** [comment]
Are you using any cheats or anything?

Does this happen with default settings, no cheats, when starting over from a new game (no saves or savestates)?  That means no speedhacks (timer hack, cpu speed, etc.), etc.

-[Unknown]

**Comment by QuantumWings** [comment]
This is a QTE you need to hit R. The same thing will happen on a real PSP if you don't hit it.

**Comment by unknownbrackets** [comment]
Ah, thanks for that comment.  I'm going to close this issue then.

-[Unknown]
