### ISSUE TITLE
Should add some way to turn the emulated PSP's WIFI switch on/off

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#7439]
I keep hearing about obscure uses of it, such as having cheat codes triggered by it and whatnot. So might as well add it at some point, as it is freely toggle-able on the real hardware.

**Comment by unknownbrackets** [comment]
Isn't that what the existing wifi setting does (you know, the first checkbox in Networking)?

-[Unknown]

**Comment by hrydgard** [comment]
Eh, doh, yes it is. Forgot that actually handled the switch state too. Maybe should make it more obvious? dunno. Closing.

**Comment by hrydgard** [comment]
Although for some uses, maybe should make it bindable... Dunno

**Comment by unknownbrackets** [comment]
Well, as far as cheat codes, it's technically a "button" I think (like the mute button) and might actually be set in the Ctrl state flags (not sure if only kernel mode.)  So there is indeed no way to associate a cheat with it right now (or with mute, or with home either.)

-[Unknown]

**Comment by hrydgard** [comment]
Right.

Reopening it to make it more "button-like" at some point...

**Comment by unknownbrackets** [comment]
I guess that's actually #6646 though, so I'm going to close this as a duplicate.

-[Unknown]
