### ISSUE TITLE
Tekken 6 Jit Freeze 

### ISSUE THREAD

**Issue by AizerMortenort** [hrydgard/ppsspp#7442]
Tekken 6 ULUS10466
My Golden Mod for the game.

The game crashes sometimes just closing cheats menu when JIT is on. This is with the latest builds and was supposed to be fixed. Try just some background modifier code. OP Codes should have been fixed?

_C1 Must Be Always On!!!
_L 0x013DF038 0x00000045
_L 0x213DF034 0x4C545441
_L 0x213DF030 0x42204544
_L 0x213DF02C 0x41435241
_L 0x013DF62C 0x00000000
_L 0x213DF628 0x454C5454
_L 0x213DF624 0x41422059
_L 0x213DF620 0x524F5453
_L 0x013DF050 0x00000000
_L 0x213DF04C 0x454C5454
_L 0x213DF048 0x41422054
_L 0x213DF044 0x534F4847
_L 0x10158F18 0x00003F80
_L 0x102660F0 0x00003F80
_L 0x1014E73C 0x00003F80
_L 0x1014D00C 0x00003F80
_L 0x1015350C 0x00003F80
_C1 ENABLE ULTIMATE TEKKEN 6 MOD
_L 0xE1070001 0x00B031E0
_L 0xE1060001 0x0041B9B4
_L 0xD0000001 0x10000310
_L 0x6041B740 0x00000001
_L 0x00000003 0x00000078
_L 0xD0000001 0x10000340
_L 0x6041B740 0x00000000
_L 0x00000003 0x00000078
_L 0xE1010003 0x003E5C90
_L 0x00402186 0x00000010
_L 0x0086707D 0x00000001
_L 0xE10000E8 0x0040E3BE
_L 0xE1040000 0x103E5C90
_L 0xE1030052 0x004081EC
_L 0xE1020000 0x00408200
_L 0x004078D0 0x00000001
_L 0x00408200 0x00000001
_L 0xE1030052 0x004078BC
_L 0xE1020000 0x00408200
_L 0x004078D0 0x00000001
_L 0x00408200 0x00000001
_L 0xE10400E8 0x1040E3BE
_L 0xE1030000 0x00402186
_L 0xE10200B4 0x004078C2
_L 0x004078C3 0x00000001
_L 0x004078C7 0x00000001
_L 0xE10400E8 0x1040E3BE
_L 0xE1030000 0x00402186
_L 0xE10200F0 0x004078C2
_L 0x104078C3 0x0000028E
_L 0x104078C7 0x0000028E
_L 0xE10400E8 0x0040E3BE
_L 0xE1030000 0x00402186
_L 0xE10200E8 0x004078C2
_L 0x004078C3 0x00000005
_L 0x004078C7 0x00000005
_L 0xE1040052 0x104081EC
_L 0xE1030000 0x00402186
_L 0xE10200B4 0x004081F2
_L 0x004081F3 0x00000001
_L 0x004081F7 0x00000001
_L 0xE1040052 0x104081EC
_L 0xE1030000 0x00402186
_L 0xE10200F0 0x004081F2
_L 0x104081F3 0x0000028E
_L 0x104081F7 0x0000028E
_L 0xE1040052 0x004081EC
_L 0xE1030000 0x00402186
_L 0xE10200E8 0x004081F2
_L 0x004081F3 0x00000005
_L 0x004081F7 0x00000005
_L 0xE1070001 0x00B031E0
_L 0xE1060001 0x0041B9B4
_L 0xD0000001 0x10000100
_L 0x6041B740 0x00000052
_L 0x00020003 0x000000CC
_L 0xD0000001 0x10000200
_L 0x6041B740 0x00000044
_L 0x00020003 0x000000CC
_L 0xE0030001 0x00B031E0
_L 0xE1020003 0x103E5C90
_L 0x6041B740 0x0000FED5
_L 0x00020003 0x000000B0
_C0 ACTIVATE PSP CAMPAIGN MODE
_L 0xE1040001 0x003E5C90
_L 0xE103002E 0x20112798
_L 0xE1020001 0x00B031E0
_L 0x6041B740 0x00000000
_L 0x00020003 0x00000084
_L 0xE1140001 0x003E5C90
_L 0x2056F294 0x3E4FB35B
_L 0x1014D00C 0x00004010
_L 0x1015350C 0x00003F82
_L 0xE1030052 0x004078BC
_L 0x2056F294 0x3E6FB35B
_L 0x1014D00C 0x00004051
_L 0x1015350C 0x00003F83
_L 0xE1030044 0x004078BC
_L 0x2056F294 0x3E6FB35B
_L 0x1014D00C 0x0000401E
_L 0x1015350C 0x00003F83
_L 0xE1030044 0x004081EC
_L 0xE10200B4 0x0040E3BE
_L 0xE1010001 0x00407AC4
_L 0x1014D00C 0x00003F80
_L 0xE1030052 0x004081EC
_L 0xE10200B4 0x0040E3BE
_L 0xE1010001 0x00407AC4
_L 0x1014D00C 0x00003F80
_L 0xE002002E 0x00112798
_L 0xE1010003 0x004078D0
_L 0x004081E8 0x00000026
_L 0xE10B0001 0x003E5C90
_L 0xE10A0001 0x00B031E0
_L 0x6041B740 0x00000001
_L 0x00020003 0x00000098
_L 0xE0070030 0x00112798
_L 0xE1020044 0x004078BC
_L 0x6041B740 0x00000048
_L 0x00020003 0x000000CC
_L 0xE1020052 0x004078BC
_L 0x6041B740 0x00000029
_L 0x00020003 0x000000CC
_L 0x004081E8 0x00000026
_L 0xE1040001 0x003E5C90
_L 0xE1030001 0x00B031E0
_L 0xE1020030 0x00112798
_L 0x6041B740 0x00000030
_L 0x00020003 0x00000098
_L 0xE1040001 0x00B031E0
_L 0xE1010002 0x004078D0
_L 0x20867364 0x00000000
_L 0xE1010002 0x00408200
_L 0x20867364 0x00000000
_L 0xE1070001 0x003E5C90
_L 0xE1060001 0x00B031E0
_L 0xE1020000 0x30867364
_L 0x6041B740 0x00000001
_L 0x00000003 0x000000B4
_L 0xE1020000 0x00867364
_L 0x6041B740 0x00000000
_L 0x00000003 0x000000B4
_L 0xE0020006 0x00867364
_L 0x6041B740 0x00000100
_L 0x00020003 0x000000B4
_L 0xE1030001 0x003E5C90
_L 0xE1020000 0x00408200
_L 0x004078D0 0x00000001
_L 0x00408200 0x00000001
_L 0xE0050004 0x20867364
_L 0xE0040000 0x10867364
_L 0xE1030000 0x00402186
_L 0xE10200B4 0x004081F2
_L 0x004081F3 0x00000002
_L 0x004081F7 0x00000002
_L 0xE0040004 0x00867364
_L 0xE1030000 0x00402186
_L 0xE10200B4 0x004081F2
_L 0x004081F3 0x00000003
_L 0x004081F7 0x00000003
_L 0xE0080006 0x00867364
_L 0x102660F0 0x00004050
_L 0x004078B8 0x00000025
_L 0x004081E8 0x00000027
_L 0x10158F18 0x00001080
_L 0xE1030000 0x00402186
_L 0xE10200E8 0x004081F2
_L 0x004081F3 0x00000002
_L 0x004081F7 0x00000002
_L 0xE1330001 0x003E5C90
_L 0xE1020002 0x004078D0
_L 0x004078D0 0x00000003
_L 0x30100001 0x00112798
_L 0xE1010001 0x00445680
_L 0x10112798 0x00000000
_L 0xE12B0001 0x00445680
_L 0x10112798 0x00000000
_L 0x2138C0CC 0x0000293A
_L 0x2138C0C8 0x206E6F72
_L 0x2138C0C4 0x75654E20
_L 0x2138C0C0 0x3A6E6769
_L 0x2138C0BC 0x530A0A6B
_L 0x2138C0B8 0x63616220
_L 0x2138C0B4 0x73692065
_L 0x2138C0B0 0x646F6D20
_L 0x2138C0AC 0x676E6973
_L 0x2138C0A8 0x73696D20
_L 0x2138C0A4 0x77656E20
_L 0x2138C0A0 0x410A0A36
_L 0x2138C09C 0x6E656B6B
_L 0x2138C098 0x65542066
_L 0x2138C094 0x6F206B6F
_L 0x2138C090 0x6F6C2077
_L 0x2138C08C 0x656E2061
_L 0x2138C088 0x20676E69
_L 0x2138C084 0x7262206C
_L 0x2138C080 0x6C697720
_L 0x2138C07C 0x73696854
_L 0x2138C078 0x0A216E75
_L 0x2138C074 0x66207265
_L 0x2138C070 0x68746F6E
_L 0x2138C06C 0x6120756F
_L 0x2138C068 0x7920676E
_L 0x2138C064 0x69726220
_L 0x2138C060 0x6F742072
_L 0x2138C05C 0x6564726F
_L 0x2138C058 0x206E6920
_L 0x2138C054 0x64657461
_L 0x2138C050 0x65726320
_L 0x2138C04C 0x6C207369
_L 0x2138C048 0x68540A0A
_L 0x2138C044 0x20212121
_L 0x2138C040 0x2045444F
_L 0x2138C03C 0x4D204E47
_L 0x2138C038 0x4941504D
_L 0x2138C034 0x41432050
_L 0x2138C030 0x53502065
_L 0x2138C02C 0x68542079
_L 0x2138C028 0x6F6A6E45
_L 0x013DF62C 0x00000045
_L 0x213DF628 0x444F4D20
_L 0x213DF624 0x4E474941
_L 0x213DF620 0x504D4143
_L 0xE1FC0001 0x003E5C90
_L 0xE1FF0001 0x00B031E0
_L 0x6041B740 0x00000030
_L 0x00020003 0x00000094
_L 0xE0040000 0x00112798
_L 0x6041B740 0x0000001A
_L 0x00020003 0x000000C8
_L 0x6041B740 0x00000000
_L 0x00020003 0x000000D0
_L 0xE0040001 0x00112798
_L 0x6041B740 0x0000001B
_L 0x00020003 0x000000C8
_L 0x6041B740 0x00000002
_L 0x00020003 0x000000D0
_L 0xE0040002 0x00112798
_L 0x6041B740 0x0000001D
_L 0x00020003 0x000000C8
_L 0x6041B740 0x00000004
_L 0x00020003 0x000000D0
_L 0xE0040003 0x00112798
_L 0x6041B740 0x00000013
_L 0x00020003 0x000000C8
_L 0x6041B740 0x00000006
_L 0x00020003 0x000000D0
_L 0xE0040004 0x00112798
_L 0x6041B740 0x00000009
_L 0x00020003 0x000000C8
_L 0x6041B740 0x00000008
_L 0x00020003 0x000000D0
_L 0xE0040005 0x00112798
_L 0x6041B740 0x00000009
_L 0x00020003 0x000000C8
_L 0x6041B740 0x0000000A
_L 0x00020003 0x000000D0
_L 0xE0040006 0x00112798
_L 0x6041B740 0x0000000A
_L 0x00020003 0x000000C8
_L 0x6041B740 0x0000000C
_L 0x00020003 0x000000D0
_L 0xE0040007 0x00112798
_L 0x6041B740 0x00000014
_L 0x00020003 0x000000C8
_L 0x6041B740 0x0000000E
_L 0x00020003 0x000000D0
_L 0xE0040008 0x00112798
_L 0x6041B740 0x00000014
_L 0x00020003 0x000000C8
_L 0x6041B740 0x00000010
_L 0x00020003 0x000000D0
_L 0xE0040009 0x00112798
_L 0x6041B740 0x00000004
_L 0x00020003 0x000000C8
_L 0x6041B740 0x00000012
_L 0x00020003 0x000000D0
_L 0xE004000A 0x00112798
_L 0x6041B740 0x00000013
_L 0x00020003 0x000000C8
_L 0x6041B740 0x00000016
_L 0x00020003 0x000000D0
_L 0xE004000B 0x00112798
_L 0x6041B740 0x00000012
_L 0x00020003 0x000000C8
_L 0x6041B740 0x00000019
_L 0x00020003 0x000000D0
_L 0xE004000C 0x00112798
_L 0x6041B740 0x00000012
_L 0x00020003 0x000000C8
_L 0x6041B740 0x00000018
_L 0x00020003 0x000000D0
_L 0xE005000D 0x00112798
_L 0x20867364 0x00000001
_L 0x6041B740 0x00000003
_L 0x00020003 0x000000C8
_L 0x6041B740 0x0000001A
_L 0x00020003 0x000000D0
_L 0xE004000E 0x00112798
_L 0x6041B740 0x00000001
_L 0x00020003 0x000000C8
_L 0x6041B740 0x0000001C
_L 0x00020003 0x000000D0
_L 0xE004000F 0x00112798
_L 0x6041B740 0x00000013
_L 0x00020003 0x000000C8
_L 0x6041B740 0x0000001E
_L 0x00020003 0x000000D0
_L 0xE0040010 0x00112798
_L 0x6041B740 0x0000000A
_L 0x00020003 0x000000C8
_L 0x6041B740 0x00000020
_L 0x00020003 0x000000D0
_L 0xE0040011 0x00112798
_L 0x6041B740 0x0000000A
_L 0x00020003 0x000000C8
_L 0x6041B740 0x00000022
_L 0x00020003 0x000000D0
_L 0xE0040012 0x00112798
_L 0x6041B740 0x00000008
_L 0x00020003 0x000000C8
_L 0x6041B740 0x00000014
_L 0x00020003 0x000000D0
_L 0xE0040013 0x00112798
_L 0x6041B740 0x00000008
_L 0x00020003 0x000000C8
_L 0x6041B740 0x00000026
_L 0x00020003 0x000000D0
_L 0xE0040014 0x00112798
_L 0x6041B740 0x00000007
_L 0x00020003 0x000000C8
_L 0x6041B740 0x00000028
_L 0x00020003 0x000000D0
_L 0xE1040015 0x00112798
_L 0x6041B740 0x00000007
_L 0x00020003 0x000000C8
_L 0x6041B740 0x0000002A
_L 0x00020003 0x000000D0
_L 0xE1040016 0x00112798
_L 0x6041B740 0x00000006
_L 0x00020003 0x000000C8
_L 0x6041B740 0x0000001D
_L 0x00020003 0x000000D0
_L 0xE1040017 0x00112798
_L 0x6041B740 0x00000006
_L 0x00020003 0x000000C8
_L 0x6041B740 0x0000002C
_L 0x00020003 0x000000D0
_L 0xE1040018 0x00112798
_L 0x6041B740 0x00000005
_L 0x00020003 0x000000C8
_L 0x6041B740 0x0000002E
_L 0x00020003 0x000000D0
_L 0xE1040019 0x00112798
_L 0x6041B740 0x00000005
_L 0x00020003 0x000000C8
_L 0x6041B740 0x00000030
_L 0x00020003 0x000000D0
_L 0xE104001A 0x00112798
_L 0x6041B740 0x00000004
_L 0x00020003 0x000000C8
_L 0x6041B740 0x00000032
_L 0x00020003 0x000000D0
_L 0xE104001B 0x00112798
_L 0x6041B740 0x00000004
_L 0x00020003 0x000000C8
_L 0x6041B740 0x00000034
_L 0x00020003 0x000000D0
_L 0xE104001C 0x00112798
_L 0x6041B740 0x0000001C
_L 0x00020003 0x000000C8
_L 0x6041B740 0x00000036
_L 0x00020003 0x000000D0
_L 0xE105001D 0x00112798
_L 0x20867364 0x00000002
_L 0x6041B740 0x0000001C
_L 0x00020003 0x000000C8
_L 0x6041B740 0x00000025
_L 0x00020003 0x000000D0
_L 0xE104001E 0x00112798
_L 0x6041B740 0x00000000
_L 0x00020003 0x000000C8
_L 0x6041B740 0x0000003A
_L 0x00020003 0x000000D0
_L 0xE104001F 0x00112798
_L 0x6041B740 0x00000002
_L 0x00020003 0x000000C8
_L 0x6041B740 0x0000001E
_L 0x00020003 0x000000D0
_L 0xE1040020 0x00112798
_L 0x6041B740 0x00000013
_L 0x00020003 0x000000C8
_L 0x6041B740 0x0000003C
_L 0x00020003 0x000000D0
_L 0xE1040021 0x00112798
_L 0x6041B740 0x00000001
_L 0x00020003 0x000000C8
_L 0x6041B740 0x0000003E
_L 0x00020003 0x000000D0
_L 0xE1040022 0x00112798
_L 0x6041B740 0x00000000
_L 0x00020003 0x000000C8
_L 0x6041B740 0x00000040
_L 0x00020003 0x000000D0
_L 0xE1040023 0x00112798
_L 0x6041B740 0x00000008
_L 0x00020003 0x000000C8
_L 0x6041B740 0x00000042
_L 0x00020003 0x000000D0
_L 0xE1040024 0x00112798
_L 0x6041B740 0x00000009
_L 0x00020003 0x000000C8
_L 0x6041B740 0x00000046
_L 0x00020003 0x000000D0
_L 0xE1040025 0x00112798
_L 0x6041B740 0x00000009
_L 0x00020003 0x000000C8
_L 0x6041B740 0x00000048
_L 0x00020003 0x000000D0
_L 0xE1040026 0x00112798
_L 0x6041B740 0x0000000A
_L 0x00020003 0x000000C8
_L 0x6041B740 0x0000004A
_L 0x00020003 0x000000D0
_L 0xE1040027 0x00112798
_L 0x6041B740 0x00000010
_L 0x00020003 0x000000C8
_L 0x6041B740 0x0000004C
_L 0x00020003 0x000000D0
_L 0xE1040028 0x00112798
_L 0x6041B740 0x00000011
_L 0x00020003 0x000000C8
_L 0x6041B740 0x00000015
_L 0x00020003 0x000000D0
_L 0xE1040029 0x00112798
_L 0x6041B740 0x0000001E
_L 0x00020003 0x000000C8
_L 0x6041B740 0x0000004E
_L 0x00020003 0x000000D0
_L 0xE104002A 0x00112798
_L 0x6041B740 0x0000000C
_L 0x00020003 0x000000C8
_L 0x6041B740 0x00000050
_L 0x00020003 0x000000D0
_L 0xE104002B 0x00112798
_L 0x6041B740 0x0000000C
_L 0x00020003 0x000000C8
_L 0x6041B740 0x00000052
_L 0x00020003 0x000000D0
_L 0xE105002C 0x00112798
_L 0x20867364 0x00000003
_L 0x6041B740 0x0000000B
_L 0x00020003 0x000000C8
_L 0x6041B740 0x00000038
_L 0x00020003 0x000000D0
_L 0xE105002D 0x00112798
_L 0x20867364 0x00000004
_L 0x6041B740 0x0000001E
_L 0x00020003 0x000000C8
_L 0x6041B740 0x00000049
_L 0x00020003 0x000000D0
_L 0xE105002E 0x00112798
_L 0x20867364 0x00000005
_L 0x6041B740 0x0000000D
_L 0x00020003 0x000000C8
_L 0x6041B740 0x00000044
_L 0x00020003 0x000000D0
_L 0xE105002F 0x00112798
_L 0x20867364 0x00000006
_L 0x6041B740 0x0000001F
_L 0x00020003 0x000000C8
_L 0x6041B740 0x00000044
_L 0x00020003 0x000000D0
_L 0xE1040001 0x00B031E0
_L 0xE1030001 0x003E5C90
_L 0xE1020052 0x004078BC
_L 0x6041B740 0x00000101
_L 0x00020003 0x000000B4
_C1 ULTIMATE TEKKEN 6 MOD UPDATES
_L 0xE1040001 0x00B031E0
_L 0xE1030001 0x103E5C90
_L 0xE1020044 0x004078BC
_L 0x6041B740 0x00000100
_L 0x00020003 0x000000B4
_C1 UPDATES - MUST BE ON!!!
_L 0xE12D0001 0x00B031E0
_L 0xE1030001 0x00B031E0
_L 0xE1020052 0x004078BC
_L 0x6041B740 0x00000001
_L 0x00020003 0x000000B4
_L 0xE1040001 0x0041B9B4
_L 0xE1030001 0x014372BD
_L 0x1040936A 0x00003F80
_L 0xD0000000 0x10000300
_L 0x1040936A 0x00003F10
_L 0xE00E3F10 0x0040936A
_L 0xE1020000 0x00408200
_L 0x004078D0 0x00000001
_L 0x00408200 0x00000001
_L 0x004078B8 0x00000027
_L 0xE101002F 0x10112798
_L 0x004081E8 0x00000025
_L 0x6041B740 0x00000001
_L 0x00020003 0x000000B4
_L 0x10158F18 0x00001080
_L 0x6041B740 0x00000044
_L 0x00020003 0x000000CC
_L 0x102660F0 0x00004050
_L 0x6041B740 0x0000001F
_L 0x00020003 0x000000C8
_L 0xE1040004 0x003E6590
_L 0xE1010052 0x004078BC
_L 0x00407975 0x00000018
_L 0xE1010052 0x104081EC
_L 0x004082A5 0x00000018
_L 0xE1040001 0x00B031E0
_L 0xE1030052 0x104078BC
_L 0xD0000001 0x10000011
_L 0x6041B740 0x00000000
_L 0x00000003 0x000000B4
_L 0xE1030001 0x00B031E0
_L 0xD0000001 0x10000041
_L 0x6041B740 0x00000000
_L 0x00000003 0x000000B5
_L 0xE1060001 0x00B031E0
_L 0xD0000001 0x10000310
_L 0x6041B740 0x00000301
_L 0x00020003 0x000000BC
_L 0xD0000001 0x10000340
_L 0x6041B740 0x00000300
_L 0x00020003 0x000000BC
_C1 Camera Mode 1
_L 0x2056F294 0x3E5FB35B
_L 0x1014D00C 0x00004020
_L 0x1015350C 0x00003F83
_C0 Camera Mode 2
_L 0x2056F294 0x3DCBB35B
_L 0x1014D00C 0x00003F80
_L 0x1015350C 0x00003F7F
_C0 Camera Mode 3
_L 0x2056F294 0x3F6B0000
_L 0x1014D00C 0x0000402F
_L 0x1015350C 0x00003F75
_C0 Camera Mode 4
_L 0x2056F294 0x3DBB0000
_L 0x1014D00C 0x00003F80
_L 0x1015350C 0x00003F82
_C0 Infinite Time
_L 0xE1030001 0x00B031E0
_L 0xE1020003 0x103E5C90
_L 0x6041B740 0x0000FFFF
_L 0x00020003 0x000000B0
_C0 Guard Damage On/OFF
_L 0x003E6C50 0x00000000
_C0 Stage Mystical Forest
_L 0xE1020001 0x00B031E0
_L 0x6041B740 0x00000000
_L 0x00020003 0x000000C8
_C0 Stage High Roller's Club
_L 0xE1020001 0x00B031E0
_L 0x6041B740 0x00000001
_L 0x00020003 0x000000C8
_C0 Stage Temple Grounds
_L 0xE1020001 0x00B031E0
_L 0x6041B740 0x00000002
_L 0x00020003 0x000000C8
_C0 Stage Cemetery
_L 0xE1020001 0x00B031E0
_L 0x6041B740 0x00000003
_L 0x00020003 0x000000C8
_C0 Stage City After Dark
_L 0xE1020001 0x00B031E0
_L 0x6041B740 0x00000004
_L 0x00020003 0x000000C8
_C0 Stage Fiesta Del Tomate
_L 0xE1020001 0x00B031E0
_L 0x6041B740 0x00000005
_L 0x00020003 0x000000C8
_C0 Stage Rustic Asia
_L 0xE1020001 0x00B031E0
_L 0x6041B740 0x00000006
_L 0x00020003 0x000000C8
_C0 Stage Manji Valley
_L 0xE1020001 0x00B031E0
_L 0x6041B740 0x00000007
_L 0x00020003 0x000000C8
_C0 Stage Noh Theater
_L 0xE1020001 0x00B031E0
_L 0x6041B740 0x00000008
_L 0x00020003 0x000000C8
_C0 Stage Fallen Colony
_L 0xE1020001 0x00B031E0
_L 0x6041B740 0x00000009
_L 0x00020003 0x000000C8
_C0 Stage Urban War Zone
_L 0xE1020001 0x00B031E0
_L 0x6041B740 0x0000000A
_L 0x00020003 0x000000C8
_C0 Stage Gargoyle's Perch
_L 0xE1020001 0x00B031E0
_L 0x6041B740 0x0000000B
_L 0x00020003 0x000000C8
_C0 Stage Nancy-MI847J
_L 0xE1020001 0x00B031E0
_L 0x6041B740 0x0000000C
_L 0x00020003 0x000000C8
_C1 Stage Azazels's Chamber
_L 0xE1020001 0x00B031E0
_L 0x6041B740 0x0000000D
_L 0x00020003 0x000000C8
_C0 Black Stage, No Graphics,
_L 0xE1020001 0x00B031E0
_L 0x6041B740 0x0000000F
_L 0x00020003 0x000000C8
_C0 Stage Lightning Storm
_L 0xE1020001 0x00B031E0
_L 0x6041B740 0x00000010
_L 0x00020003 0x000000C8
_C0 Stage Tunnel Disaster
_L 0xE1020001 0x00B031E0
_L 0x6041B740 0x00000011
_L 0x00020003 0x000000C8
_C0 Stage Electric Fountain
_L 0xE1020001 0x00B031E0
_L 0x6041B740 0x00000012
_L 0x00020003 0x000000C8
_C0 Stage Anger of the Earth
_L 0xE1020001 0x00B031E0
_L 0x6041B740 0x00000013
_L 0x00020003 0x000000C8
_C0 Stage Hidden Retreat
_L 0xE1020001 0x00B031E0
_L 0x6041B740 0x00000014
_L 0x00020003 0x000000C8
_C0 Black Stage, No Graphics,
_L 0xE1020001 0x00B031E0
_L 0x6041B740 0x00000018
_L 0x00020003 0x000000C8
_C0 Stage Practice Mode 1
_L 0xE1020001 0x00B031E0
_L 0x6041B740 0x0000001A
_L 0x00020003 0x000000C8
_C0 Stage Practice Mode 2
_L 0xE1020001 0x00B031E0
_L 0x6041B740 0x0000001B
_L 0x00020003 0x000000C8
_C0 Stage Gym
_L 0xE1020001 0x00B031E0
_L 0x6041B740 0x0000001C
_L 0x00020003 0x000000C8
_C0 Stage Hidden Retreat2
_L 0xE1020001 0x00B031E0
_L 0x6041B740 0x0000001D
_L 0x00020003 0x000000C8
_C0 Stage Waterfall
_L 0xE1020001 0x00B031E0
_L 0x6041B740 0x0000001E
_L 0x00020003 0x000000C8
_C0 Stage Temple
_L 0xE1020001 0x00B031E0
_L 0x6041B740 0x0000001F
_L 0x00020003 0x000000C8
_C0 Main Character Azazel
_L 0x013DFD69 0x00000044
_L 0x0138AC5C 0x00000044
_C0 Main Character Nancy
_L 0x013DFD69 0x00000052
_L 0x0138AC5C 0x00000052

Turning JIT OFF fixes fixes this but slows the emulation.

**Comment by LunaMoo** [comment]
Your pointer codes are all broken.
 For example:
_L 0x6041B740 0x0000000D
_L 0x00020003 0x000000C8
should be:
_L 0x6041B740 0x0000000D
_L 0x00020001 0x000000C8

Because third argument should always be 1 for normal pointer codes(that points only once) as with the cw cheat format:
Pointer Commands
Code type Format Description

8-bit write 0x6aaaaaaa 0x000000vv
0x0000nnnn 0xiiiiiiii aaaaaaa = address to load 32-bit base from (25 bit)
vv = value to store at base + offset (8/16/32 bit)
qqq = offset to add to load the base(*4)
nnnn = number of times to point (16 bit) (must be 1 for normal pointer codes)
iiiiiiii = 32-bit offset to add to base (n = 1)

16-bit write 0x6aaaaaaa 0x0000vvvv
0x0001nnnn 0xiiiiiiii aaaaaaa = address to load 32-bit base from (25 bit)
vvvv = value to store at base + offset (8/16/32 bit)
qqq = offset to add to load the base(*4)
nnnn = number of times to point (16 bit) (must be 1 for normal pointer codes)
iiiiiiii = 32-bit offset to add to base (n = 1)

32-bit write 0x6aaaaaaa 0xvvvvvvvv
0x0002nnnn 0xiiiiiiii aaaaaaa = address to load 32-bit base from (25 bit)
vvvvvvvv = value to store at base + offset (8/16/32 bit)
qqq = offset to add to load the base(*4)
nnnn = number of times to point (16 bit) (must be 1 for normal pointer codes)
iiiiiiii = 32-bit offset to add to base (n = 1)

8-bit inverse write 0x6aaaaaaa 0x000000vv
0x0003nnnn 0xiiiiiiii aaaaaaa = address to load 32-bit base from (25 bit)
vv = value to store at base - offset (8/16/32 bit)
qqq = offset to add to load the base(*4)
nnnn = number of times to point (16 bit) (must be 1 for normal pointer codes)
iiiiiiii = 32-bit offset to subtract to base (n = 1)

16-bit inverse write 0x6aaaaaaa 0x0000vvvv
0x0004nnnn 0xiiiiiiii aaaaaaa = address to load 32-bit base from (25 bit)
vvvv = value to store at base - offset (8/16/32 bit)
qqq = offset to add to load the base(*4)
nnnn = number of times to point (16 bit) (must be 1 for normal pointer codes)
iiiiiiii = 32-bit offset to subtract to base (n = 1)

32-bit inverse write 0x6aaaaaaa 0xvvvvvvvv
0x0005nnnn 0xiiiiiiii aaaaaaa = address to load 32-bit base from (25 bit)
vvvvvvvv = value to store at base - offset (8/16/32 bit)
qqq = offset to add to load the base(*4)
nnnn = number of times to point (16 bit) (must be 1 for normal pointer codes)
iiiiiiii = 32-bit offset to subtract to base (n = 1)

Extra pointer line (n > 1)
type null 0x00000000 0x00000000 This will do absolutely nothing but it's required for n > 1.
You may need to use this if you want to use the qqq in normal pointer codes
Extra pointer line (n > 1)
type pointer walk 0xSppppppp 0xSppppppp This will make you able to go trough various level of pointers S indicates the type of offset to find the next pointer(0x2 +p 0x3 -p)
while p indicates the offset to find the next pointer.
Extra pointer line (n > 1)
type multi adress write 0x9sssssss 0xwwwwwwww sssssss = offset to add to base(*bytes of the code type, see above)
wwwwwwww = value to sum to starting value (vvvvvvvv) each time it's pointed

Extra pointer line (n = 2)
type copy byte 0x1sssssss 0x00000000 This extra pointer line will change sligtly the working of the pointer codes as specified above.
vvvvvvvv = bytes to be copied
aaaaaaa = address to load 32-bit base from (25 bit) (source)
iiiiiiii = 32-bit offset to add to base
qqq = offset to add to aaaaaaa to load the base(*4) (destination)
sssssss = 32-bit offset to add to base (destination)

**Comment by AizerMortenort** [comment]
This is how it is made and works on real psp, but then again why does it freeze with JIT?

**Comment by hrydgard** [comment]
Fixed the crash that could happen.
