### ISSUE TITLE
Support for xBRZ 1.2 ?

### ISSUE THREAD

**Issue by GoldWind** [hrydgard/ppsspp#7443]
PPSSPP seems to have xBRZ 1.1 but xBRZ 1.2 come out recently with over 30% performance boost.
http://sourceforge.net/projects/xbrz/files/xBRZ/

**Comment by GamerzHell9137** [comment]
Ohh that would be great.

**Comment by unknownbrackets** [comment]
I'll update it a bit later, we'll see if it's going to cause any new issues.

Hope our alphaBlend func is not dragging the perf down, maybe it's not needed anymore...

-[Unknown]

**Comment by GoldWind** [comment]
Thanks
