### ISSUE TITLE
E[NET]: HLE\sceNetAdhoc.cpp:1882 sceNetAdhocPtpAccept[1]: Failed (Socket Closed)

### ISSUE THREAD

**Issue by lightfirst** [hrydgard/ppsspp#7444]
Testing ppsspp-adhoclocal(#7367) Gundam VS Gundam Next Plus cant start  Multiplay mission.
some log
06:27:803 task         I[NET]: HLE\sceNetAdhoc.cpp:2087 sceNetAdhocPtpListen(̹𶏶,20001,8192,250000,100,3,0)
06:32:927 task         E[NET]: HLE\sceNetAdhoc.cpp:1882 sceNetAdhocPtpAccept[1]: Failed (Socket Closed)
06:46:340 task         E[NET]: HLE\sceNetAdhoc.cpp:1882 sceNetAdhocPtpAccept[1]: Failed (Socket Closed)
06:58:017 task         I[NET]: HLE\sceNetAdhoc.cpp:2039 sceNetAdhocPtpClose(1,0) at 0885b7ac

testing Multiplayer JPCSP with PPSSPP-adhoclocal, if jpcsp hosting mission, can start mission
26:45:721 task         I[NET]: HLE\sceNetAdhoc.cpp:2087 sceNetAdhocPtpListen(gᘮƬ20001,8192,250000,100,3,0)
26:51:828 task         I[NET]: HLE\sceNetAdhoc.cpp:1867 sceNetAdhocPtpAccept[1->2:20001]: Established (127.0.0.1:56210)
26:51:844 task         I[NET]: HLE\sceNetAdhoc.cpp:2039 sceNetAdhocPtpClose(1,0) at 0885b7ac
26:52:080 user_main    I[NET]: HLE\sceNetAdhoc.cpp:2348 sceNetAdhocPtpRecv[2:20001]: Received 5 bytes from 54:40:8F:03:5D:FF:56210
26:52:178 user_main    I[NET]: HLE\sceNetAdhoc.cpp:2260 sceNetAdhocPtpSend[2:20001]: Sent 5 bytes to 54:40:8F:03:5D:FF:56210
26:52:411 user_main    I[NET]: HLE\sceNetAdhoc.cpp:2260 sceNetAdhocPtpSend[2:20001]: Sent 16 bytes to 54:40:8F:03:5D:FF:56210
26:52:480 user_main    I[NET]: HLE\sceNetAdhoc.cpp:2348 sceNetAdhocPtpRecv[2:20001]: Received 16 bytes from 54:40:8F:03:5D:FF:56210

**Comment by issuer** [comment]
Nice catch!

**Comment by lightfirst** [comment]
esting Multiplayer JPCSP with 2 PPSSPP-adhoclocal, if jpcsp hosting mission, can start mission.
One PPSSPP get Established, another PPSSPP get Socket Error (10035)
E[UTIL]: HLE\sceUtility.cpp:425 UNIMPL 00000000=sceUtilityNetconfUpdate(2)
46:43:750 task         I[NET]: HLE\sceNetAdhoc.cpp:228 sceNetAdhocPdpCreate(JČEO=Ճ, 10000, 8192, 0) at 0885b804
46:50:963 idle0        I[NET]: HLE\proAdhoc.cpp:1052 Received 139 Bytes of Data from Adhoc Server
46:50:963 idle0        I[NET]: HLE\proAdhoc.cpp:1108 Incoming Peer Data...
47:31:299 task         I[NET]: HLE\sceNetAdhoc.cpp:2086 sceNetAdhocPtpListen(JČEO=,20002,8192,250000,100,3,0)
47:37:337 task         I[NET]: HLE\sceNetAdhoc.cpp:1866 sceNetAdhocPtpAccept[1->2:20002]: Established (127.0.0.1:49925)
47:37:655 task         I[NET]: HLE\sceNetAdhoc.cpp:1866 sceNetAdhocPtpAccept[1->3:20002]: Established (127.0.0.1:49929)
47:37:655 task         I[NET]: HLE\sceNetAdhoc.cpp:2038 sceNetAdhocPtpClose(0,0) at 0885b7ac
47:50:768 task         I[NET]: HLE\sceNetAdhoc.cpp:1866 sceNetAdhocPtpAccept[1->4:20002]: Established (127.0.0.1:49933)
48:01:362 task         I[NET]: HLE\sceNetAdhoc.cpp:2038 sceNetAdhocPtpClose(2,0) at 0885b7ac
48:01:362 task         I[NET]: HLE\sceNetAdhoc.cpp:2038 sceNetAdhocPtpClose(1,0) at 0885b7ac
48:23:565 idle0        I[NET]: HLE\proAdhoc.cpp:1052 Received 5 Bytes of Data from Adhoc Server
48:23:565 idle0        I[NET]: HLE\proAdhoc.cpp:1137 FriendFinder: Incoming Peer Data Delete Request...
48:25:741 idle0        I[NET]: HLE\proAdhoc.cpp:1052 Received 5 Bytes of Data from Adhoc Server
48:25:741 idle0        I[NET]: HLE\proAdhoc.cpp:1137 FriendFinder: Incoming Peer Data Delete Request...





46:31:586 user_main    E[UTIL]: HLE\sceUtility.cpp:425 UNIMPL 00000000=sceUtilityNetconfUpdate(2)
46:34:785 task         I[NET]: HLE\sceNetAdhoc.cpp:228 sceNetAdhocPdpCreate(Y'tì 10000, 8192, 0) at 0885b804
46:40:566 idle0        I[NET]: HLE\proAdhoc.cpp:1052 Received 139 Bytes of Data from Adhoc Server
46:40:566 idle0        I[NET]: HLE\proAdhoc.cpp:1108 Incoming Peer Data...
46:50:963 idle0        I[NET]: HLE\proAdhoc.cpp:1052 Received 139 Bytes of Data from Adhoc Server
46:50:963 idle0        I[NET]: HLE\proAdhoc.cpp:1108 Incoming Peer Data...
47:31:311 task         I[NET]: HLE\sceNetAdhoc.cpp:2086 sceNetAdhocPtpListen(Y'l20001,8192,250000,100,3,0)
47:37:332 task         I[NET]: HLE\sceNetAdhoc.cpp:1614 sceNetAdhocPtpOpen(Y'l0,JČEO=,20002,8192,250000,100,0)
47:37:333 task         I[NET]: HLE\sceNetAdhoc.cpp:1916 sceNetAdhocPtpConnect(2, 0, 00000001) at 0885af2c
47:37:333 task         E[NET]: HLE\sceNetAdhoc.cpp:1957 sceNetAdhocPtpConnect[2]: Socket Error (10035)
47:37:650 task         I[NET]: HLE\sceNetAdhoc.cpp:1866 sceNetAdhocPtpAccept[1->3:20001]: Established (127.0.0.1:49928)
47:40:702 task         I[NET]: HLE\sceNetAdhoc.cpp:2038 sceNetAdhocPtpClose(2,0) at 0885b7ac
47:50:762 task         I[NET]: HLE\sceNetAdhoc.cpp:1614 sceNetAdhocPtpOpen(Y'l0,JČEO=,20002,8192,250000,100,0)
47:50:762 task         I[NET]: HLE\sceNetAdhoc.cpp:1916 sceNetAdhocPtpConnect(2, 0, 00000001) at 0885af2c
47:50:762 task         E[NET]: HLE\sceNetAdhoc.cpp:1957 sceNetAdhocPtpConnect[2]: Socket Error (10035)
47:54:149 task         I[NET]: HLE\sceNetAdhoc.cpp:2038 sceNetAdhocPtpClose(2,0) at 0885b7ac
48:01:558 task         I[NET]: HLE\sceNetAdhoc.cpp:2038 sceNetAdhocPtpClose(3,0) at 0885b7ac
48:01:558 task         I[NET]: HLE\sceNetAdhoc.cpp:2038 sceNetAdhocPtpClose(1,0) at 0885b7ac
48:23:567 idle0        I[NET]: HLE\proAdhoc.cpp:1052 Received 5 Bytes of Data from Adhoc Server
48:23:567 idle0        I[NET]: HLE\proAdhoc.cpp:1137 FriendFinder: Incoming Peer Data Delete Request...

**Comment by Bigpet** [comment]
If you can't reproduce this without #7367 (on 2 seperate devices or a VM) then I don't think this is relevant

**Comment by lightfirst** [comment]
@Bigpet I also had test this game on 2 seperate devices or a VM, same as testing with adhoclocal.

**Comment by issuer** [comment]
I could also reproduce this issue countless times. I eventually gave up and just use JPCSP to play this game online.

Oddly, this game works online if JPCSP hosts to PPSSPP and can even be played.
But the emulators return an error due to desynching issues some time after someone receives an attack.

The main issue here is PPSSPP cannot start any Ad hoc battles due to an error, hopefully @lightfirst has found the main cause of the problem.

**Comment by lightfirst** [comment]
say by git15: if the game is exchanging values computed using VROT or VCOS through the network: both sides have to use the exact same algorithm.
Did JPCSP, PPSSPP use the exact same algorithm?

**Comment by unknownbrackets** [comment]
Does this still happen and is it different from #11497?  If yes, might be good to close one because maybe the vrot/vcos information is useful.

-[Unknown]
