### ISSUE TITLE
PPSSPPSDL not opening

### ISSUE THREAD

**Issue by FreakGamer** [hrydgard/ppsspp#7447]
When I try to open ppsspp, the following shows up:PPSSPPSDL cannot be opened because of a Problem.
If i click on show details,the following appears:

Process:         PPSSPPSDL [519]
Path:            /Applications/PPSSPP.app/Contents/MacOS/PPSSPPSDL
Identifier:      PPSSPPSDL
Version:         ???
Code Type:       X86-64 (Native)
Parent Process:  launchd [247]
Responsible:     PPSSPPSDL [519]
User ID:         501

Date/Time:       2015-02-07 13:27:01.776 +0530
OS Version:      Mac OS X 10.9.5 (13F34)
Report Version:  11
Anonymous UUID:  92354330-C276-4857-72F6-83D81494C982

Crashed Thread:  0

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/lib/libSDL-1.2.0.dylib
  Referenced from: /Applications/PPSSPP.app/Contents/MacOS/PPSSPPSDL
  Reason: no suitable image found.  Did find:
	/usr/local/lib/libSDL-1.2.0.dylib: mach-o, but wrong architecture
	/usr/local/lib/libSDL-1.2.0.dylib: mach-o, but wrong architecture

Binary Images:
    0x7fff668f0000 -     0x7fff66923817  dyld (239.4) <7AD43B9B-5CEA-3C7E-9836-A06909F9CA56> /usr/lib/dyld

Model: MacBookAir6,1, BootROM MBA61.0099.B12, 2 processors, Intel Core i5, 1.4 GHz, 4 GB, SMC 2.12f137
Graphics: Intel HD Graphics 5000, Intel HD Graphics 5000, Built-In
Memory Module: BANK 0/DIMM0, 2 GB, DDR3, 1600 MHz, 0x80CE, 0x4B3445384533303445452D45474345000000
Memory Module: BANK 1/DIMM0, 2 GB, DDR3, 1600 MHz, 0x80CE, 0x4B3445384533303445452D45474345000000
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x117), Broadcom BCM43xx 1.0 (6.30.223.154.65)
Bluetooth: Version 4.2.7f4 15112, 3 services, 23 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD TS0128F, 121.33 GB
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Air, Apple Inc., 23.6

**Comment by unknownbrackets** [comment]
```
Library not loaded: /usr/local/lib/libSDL-1.2.0.dylib
Referenced from: /Applications/PPSSPP.app/Contents/MacOS/PPSSPPSDL
Reason: no suitable image found. Did find:
/usr/local/lib/libSDL-1.2.0.dylib: mach-o, but wrong architecture
```

Well, it looks like you don't have SDL installed.  It also looks like you're using an old version of PPSSPP.  On Mac, you need to use `brew` to install SDL, and for the latest version, it has to be `brew install sdl2`.

-[Unknown]

**Comment by FreakGamer** [comment]
Thank you. I upgraded to PPSSPPSDL 1.0 from 0.9.9.1, and installed SDL2. 
Now,I can use it properly.
