### ISSUE TITLE
Adhoc - hack//LINK window pop up paradox

### ISSUE THREAD

**Issue by issuer** [hrydgard/ppsspp#7448]
Simply put, this game has a paradoxal Adhoc bug.
While the game joins the Host's Lobby, a pop up window that is supposed to show before said Host Lobby is shown at the same exact time and it never goes away, even worse it makes all controls unresponsive. This pop up window is supposed to just flash on screen for a while and then disappear, only then the Host's Lobby is supposed to appear afterwards. Like in this video: http://youtu.be/tf7zM20Jue0 (around 0:20)

This is not what happens, both windows appear at the same exact time (paradox) and since the pop up window at the center takes priority over all the other windows, it blocks all the buttons from working, making the game stuck and a PPSSPP reset the only remaining option. Note the game is actually hosting fine and other playes can even join in, it's just this pop up window of hell at the center that gets in the way and makes everything unresponsive and stuck forever.

Now comes the really weird part, JPCSP does the exact same thing when trying to connect to coldbird.net just like in PPSSPP. However, setting JPCSP's clock to 150% actually fixes the pop up window of hell and the game works online just fine if you set the clock back to normal (see SS below).
I had my hopes up and went to do some testing with PPSSPP, but it did not work. Even setting an alternate speed of a MAX 600% the pop up did not go away like JPCSP.

I'm only posting this issue because it "seems" an easy fix (hopefully), maybe some bad timing in the call of a thread or an ant that got somewhere in the code, i don't know.

150% clock speed JPCSP fix, all the buttons are responsive and the game can be started by pressing O
![fix1](https://cloud.githubusercontent.com/assets/10441372/6091329/6f5469aa-ae8e-11e4-8984-b21f3a21668f.png)

PPSSPP with the above fix (alternate speed to 150%), buttons still unresponsive
![uljs00266_00001](https://cloud.githubusercontent.com/assets/10441372/6091346/d0774572-ae8e-11e4-90ae-97e96c672727.jpg)

Log doesn't show any Errors either (apart from sceMpeg), just warnings:
![hackparadox](https://cloud.githubusercontent.com/assets/10441372/6091399/2d264456-ae91-11e4-85d7-5f7645bdf005.png)

**Comment by hrydgard** [comment]
It's probably an easy fix, but finding WHAT to fix can be really, really hard in these timing issues, and it might not be a single thing but several..

**Comment by issuer** [comment]
Sorry, i was being hopeful something of the likes of #7331 could be causing this.

**Comment by unknownbrackets** [comment]
Has this changed with in the latest git build?  There have been a number of changes to networking handling.  It might at least log more interesting things or the CPU clock may have some effect now.

-[Unknown]

**Comment by MojoJojoDojo** [comment]
Last time I checked it worked but I dont know which git build number it first worked on and if it broke later on with other ad-hoc changes.

**Comment by hrydgard** [comment]
Let's reopen if we get any more reports. Closing.
