### ISSUE TITLE
Brave Story will instantly crash if you switch to "Read framebuffers to memory cpu\gpu"

### ISSUE THREAD

**Issue by vsub** [hrydgard/ppsspp#7450]
Even if it's by accident(pressing F5)
I was trying 0.9.9-1-885 couple of weeks ago to see how my games works before I update and I notest this problem which exist on the latest beta too.

It doesn't matter if you start the game in that mode or switch to it while ingame,ppsspp will always crash.
This happens when I switch the mode
![2015-02-07_114347](https://cloud.githubusercontent.com/assets/5032540/6091673/16b0adb8-aec0-11e4-88a6-ca88004732a2.jpg)

**Comment by unknownbrackets** [comment]
Yes, we can call this intentional.

If you'd like, I can submit a pull request to change "read framebuffers to memory" to "please make games crash".  See #6261, this is why we want to remove the option entirely.

-[Unknown]
