### ISSUE TITLE
Graphics regression in MGS: Peace Walker between 0.9.9.1 and 1.0  (user report)

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#7452]
Reported through e-mail:

"I upgraded from PPSSPP 0.9.9.1 to 1.0 and noticed this texture issue in Metal Gear Solid: Peace Walker. Please see attached images for comparison. There are similar issues in various other places in the game, but this one can quickly be accessed from the mission "Locate the ID Card."

Windows 7 Professional, 64-bit (Service Pack 1)
NVIDIA GeForce GT 640, driver version 344.65
Direct X runtime version: 11.0"

0.9.9.1:
![0 9 9 1](https://cloud.githubusercontent.com/assets/130929/6092123/05963e12-aecf-11e4-836b-111acfedea54.jpg)

1.0:
![1 0](https://cloud.githubusercontent.com/assets/130929/6092124/06d8c826-aecf-11e4-9605-d6f0f065b44f.jpg)

**Comment by daniel229** [comment]
it's https://github.com/hrydgard/ppsspp/commit/e22fed8b9fd15ff4662a880c37ca38bd9b765049

**Comment by hrydgard** [comment]
Thanks @daniel229 !  Hm, that one should be harmless...

**Comment by hrydgard** [comment]
Hm, I'm wondering.. If you disable the vertex cache, does that fix it?

**Comment by daniel229** [comment]
Disable the vertex cache won't help.

v0.9.9.1-681-g87bcb56
![02](https://cloud.githubusercontent.com/assets/3481559/6092595/d461c044-af20-11e4-833d-997aff06ed24.png)


v0.9.9.1-683-ge22fed8
![01](https://cloud.githubusercontent.com/assets/3481559/6092597/dae5b1aa-af20-11e4-8053-c1953d9dc13d.png)

**Comment by unknownbrackets** [comment]
If you undo only `GPU/GLES/TransformPipeline.h`, it fixes it, right?  I assume if you undo only the `std::unordered_map<u32, VertexArrayInfo *> vai_;` change it fixes it?

-[Unknown]

**Comment by daniel229** [comment]
Sorry,it's https://github.com/hrydgard/ppsspp/commit/7cb5e7f53fd79ab4f5520e7caae4eb9f7131efe1
revert line 281,282 in <code> GPU/GLES/TransformPipeline.cpp </code> fixes it.

**Comment by unknownbrackets** [comment]
Okay, https://github.com/hrydgard/ppsspp/commit/7cb5e7f53fd79ab4f5520e7caae4eb9f7131efe1#diff-2be23d60bf0428c6d88dbfe4564bcb3bR281 makes way more sense.

Can you make it log?

```c++
if ((vertexCount < 2 && prim > 0) || (vertexCount < 3 && prim > 2 && prim != GE_PRIM_RECTANGLES)) {
   ERROR_LOG(HLE, "Incomplete prim: type=%d, count=%d", prim, vertexCount);
}
```

-[Unknown]

**Comment by daniel229** [comment]
19:19:671 Main         E[HLE]: GLES\TransformPipeline.cpp:275 Incomplete prim: type=4, count=2
19:19:679 Main         E[HLE]: GLES\TransformPipeline.cpp:275 Incomplete prim: type=4, count=2
19:19:685 Main         E[HLE]: GLES\TransformPipeline.cpp:275 Incomplete prim: type=4, count=2
19:19:691 Main         E[HLE]: GLES\TransformPipeline.cpp:275 Incomplete prim: type=4, count=2

**Comment by unknownbrackets** [comment]
So, that's GE_PRIM_TRIANGLE_STRIP with 2... if you step through or log all prim types, it's never using CONTINUE_PREVIOUS, right (pretty sure it's not since we reported that type)?  Hmm.

What if you make it `Flush(); return;` instead of logging?  Maybe it's just from flushing or something.

-[Unknown]

**Comment by daniel229** [comment]
Don't see CONTINUE_PREVIOUS in framedump.
Flush(); return;won't help.

**Comment by unknownbrackets** [comment]
What if you just move it down?  So these lines:
```c++
	if ((vertexCount < 2 && prim > 0) || (vertexCount < 3 && prim > 2 && prim != GE_PRIM_RECTANGLES))
		return;
```

Move them after this?
```c++
	*bytesRead = vertexCount * dec_->VertexSize();
```

Is there any difference?

Can you make it log vertType when it returns early like that?  I'm wondering if it's using weights or indexes or anything.

-[Unknown]

**Comment by daniel229** [comment]
That fixes the problem.

 log vertType
https://gist.github.com/daniel229/8725deeb9beed60e8883

**Comment by unknownbrackets** [comment]
How high can you put it with it still working?

So, that's s16 pos, s8 nrm, 4444 col, u16 tc, no through/index/weight.  Seems pretty ordinary...

-[Unknown]

**Comment by daniel229** [comment]
If it means less line number is high,above change is the high max.

**Comment by unknownbrackets** [comment]
So, even if it goes right above `bytesRead`, it doesn't work?

Oh, duh, that makes sense.  @hrydgard it's not increasing `gstate_c.vertexAddr` without `bytesRead` being set.  And so the bad verts are never being eaten.

-[Unknown]

**Comment by hrydgard** [comment]
Oh, of course! Good catch, I'll submit a fix.

**Comment by unknownbrackets** [comment]
Too late, already just added it to the minor pull #7534.

-[Unknown]

**Comment by hrydgard** [comment]
@unknownbrackets , alright :)
