### ISSUE TITLE
cwcheat not work on new ppsspp

### ISSUE THREAD

**Issue by onlygame** [hrydgard/ppsspp#7453]
cwcheat didn't work on phantasy star portable 2 and god eater burst, graphic problem on phantasy star portable 2 solved, but cwcheat not work, can you fix it?

**Comment by hrydgard** [comment]
Lots of CwCheat stuff works, you're going to have to be more specific.

**Comment by onlygame** [comment]
phantasy star portable 2

_S ULUS-10529
_G Phantasy Star Portable 2 [US]
_C1 9999999 Meseta
_L 0x2095CB94 0x0098967F
_L 0x20A4F5C4 0x0098967F
_C1 Inf PP
_L 0x201F9E88 0x24027FFF
_C1 Infinite HP
_L 0x015952B0 0x000000CA

not work

**Comment by LunaMoo** [comment]
Not sure about PSP2 situation, might be same thing as the pasted codes look all correct and use very basic code types, but psp cheats for God Eater Burst are surely having incorrect addresses on ppsspp, which for US/JP versions would be even more off by this offset https://github.com/hrydgard/ppsspp/blob/master/Core/CwCheat.cpp#L246 ~ through it's not like more or less off would make a difference.

**Comment by onlygame** [comment]
ok, thanks for your information

**Comment by disastranagant** [comment]
That God Eater Burst hack looks like someone tried to make it automatically convert codes but didn't maintain it between versions.

**Comment by leopard20** [comment]
Also you should reduce the refresh rate (a misnomer - it's the refreshing interval not rate) for some cheats to work properly. Not sure about PSP2.

**Comment by unknownbrackets** [comment]
Does this even still happen?

Also, to be able to do anything about an issue like this, it needs to be compared with a cheat that works on a real PSP.  Cheats that used to work in old PPSSPP versions but didn't ever work on a real PSP may be broken as a normal part of fixing emulation bugs.

-[Unknown]

**Comment by LunaMoo** [comment]
Many(but not all) cheats that worked on real PSP were never working on PPSSPP in affected games as memory allocation was never correct yet, In the distant past PPSSPP had a really awful offset hack which was making some of those cheats work in GEB, however it was also that eact offset that was breaking other cheats for same game aka such hacks should never return in any shape or form.
 I even made lots of cheats which aren't affected by the issue for many games to reduce number of constant complains about it.

 Also no, changing refresh rate is not an option to "fix" cheats and as I explained in the confusing thread that was unfortunately pinned on cheats subforum should not be advertised like that;p, that thread in general just an example on how cheats should never be done and the person opening it left after not being able to fix his cheats which aside from trying to change temporary vars(and that's his mistake) were also affected by memory allocation issues aka the general problem most people have with cheats.

 I think I'll open new issue about memory allocation and just close all those cheat issues.

**Comment by LunaMoo** [comment]
This will now be tracked in #11167 closing.
