### ISSUE TITLE
Some errors in some games

### ISSUE THREAD

**Issue by kirous** [hrydgard/ppsspp#7457]
Hello, returning here and seeing if the new version has improved a lot, and some games that have not yet upgraded from older versions, as some games are:

- PHOTOKANO (ULJS00378): contains some graphical error as seen in this image:

![imagen 01](https://cloud.githubusercontent.com/assets/5083411/6099502/321399cc-afc8-11e4-83aa-9373ab8f9eea.jpg)

I do not know where the error is, and also the characters when you leave, which does not do that, fade quickly disappear. In version 0.9.9 if it does, however this version, no.

Another thing is that some scenes to take the picture, the viewfinder of the camera does not move or does not rotate according to the operation control knob (GAMEPAD) or keyboard.

And finally, when I take a photo of any room, to check my files taken in the game, not shown, is displayed on a black screen with the exception of indications of pressing buttons control if displayed. Here the images:

![imagen 02](https://cloud.githubusercontent.com/assets/5083411/6099522/ef170130-afc8-11e4-9ac3-c1465c27e39d.jpg)

![imagen 03](https://cloud.githubusercontent.com/assets/5083411/6099526/fb585c46-afc8-11e4-954b-2dd7308777ce.jpg)

- DARKSTALKERS (ULUS10005): It has not improved in the options menu and other appear. As in the game. Only appears when you put in "framebuffers TO READ MEMORY". An image to see:

![imagen 04](https://cloud.githubusercontent.com/assets/5083411/6099541/4c0cd6e4-afc9-11e4-835f-44ef21f8dbdc.jpg)

- BLEACH HEAT OF SOUL 6 (UCAS40258): Still have problem INTRO restart the video. Here the images:

![imagen 05](https://cloud.githubusercontent.com/assets/5083411/6099561/9f4c5a5a-afc9-11e4-8372-df1077c93f16.jpg)

![imagen 06](https://cloud.githubusercontent.com/assets/5083411/6099576/06a6af7a-afca-11e4-9b29-67b5be5c36ee.jpg)

![imagen 07](https://cloud.githubusercontent.com/assets/5083411/6099578/0cc92cde-afca-11e4-822f-90ecf7e44cdb.jpg)

- NEED FOR SPEED MOST WANTED 5.1.0 (ULUS10036): Still no problem with the sound and the game freezes, when in chase mode. For this problem is still not playable game by having a huge sound power. And you can be that is.

Hopefully these details I'm telling you, may improve in the next version..... XD Sorry my bad english!!

**Comment by daniel229** [comment]
That black texture in PHOTOKANO is due to bug in Hardware Transform,disable Hardware Transform then it would be fine.Photo display seems easy to fix.
Gedebugger
![01](https://cloud.githubusercontent.com/assets/3481559/6101614/e758bf30-b061-11e4-996f-518740d831b3.png)

more tabs
https://gist.github.com/daniel229/64a8092745393583919d

DARKSTALKERS already a thread for it.https://github.com/hrydgard/ppsspp/issues/6647 ,and seems not easy to fix.

BLEACH HEAT OF SOUL 6 seems bugs in scefont
```
31:54:248 sgx-psp-at3- I[ME]: HLE\sceAtrac.cpp:750 2=sceAtracGetAtracID(4097)
31:54:264 sgx-psp-at3- I[ME]: HLE\sceAtrac.cpp:1544 sceAtracSetData(2, 08c141c0, 00040000)
31:54:264 sgx-psp-at3- W[ME]: HLE\sceAtrac.cpp:1462 This is an atrac3 stereo audio
31:56:318 Main         I[FONT]: HLE\sceFont.cpp:761 sceFontDoneLib(08e06ed0)
31:56:318 Main         I[IO]: HLE\sceIo.cpp:906 stderr: font_error:I, 08c70000
31:56:345 sgx-psp-at3- I[ME]: HLE\sceAtrac.cpp:1275 sceAtracReleaseAtracID(2)
31:56:345 Main         E[FONT]: HLE\sceFont.cpp:627 Font exists but is closed, which was not allowed in this call
31:56:345 Main         E[FONT]: HLE\sceFont.cpp:902 sceFontClose(8e06f1c) - font not open?
31:56:345 Main         E[FONT]: HLE\sceFont.cpp:627 Font exists but is closed, which was not allowed in this call
31:56:345 Main         E[FONT]: HLE\sceFont.cpp:902 sceFontClose(8e06f68) - font not open?
31:56:345 Main         I[FONT]: HLE\sceFont.cpp:761 sceFontDoneLib(08e06ed0)
31:56:345 Main         W[MM]: MemmapFunctions.cpp:93 ReadFromHardware: Invalid address 00000000
31:56:345 Main         W[MM]: MemmapFunctions.cpp:93 ReadFromHardware: Invalid address 00000004
31:56:345 Main         W[MM]: MemmapFunctions.cpp:130 WriteToHardware: Invalid address 0000000c
31:56:345 Main         W[MM]: MemmapFunctions.cpp:93 ReadFromHardware: Invalid address 00000000
31:56:345 Main         W[MM]: MemmapFunctions.cpp:93 ReadFromHardware: Invalid address 0000000c
31:56:345 Main         W[MM]: MemmapFunctions.cpp:93 ReadFromHardware: Invalid address 00000008
31:56:345 Main         W[MM]: MemmapFunctions.cpp:93 ReadFromHardware: Invalid address 00000008
31:56:345 Main         W[MM]: MemmapFunctions.cpp:93 ReadFromHardware: Invalid address 00000000
31:56:345 Main         W[MM]: MemmapFunctions.cpp:130 WriteToHardware: Invalid address 00000004
31:56:345 Main         W[MM]: MemmapFunctions.cpp:130 WriteToHardware: Invalid address 00000008
31:56:345 Main         W[MM]: MemmapFunctions.cpp:130 WriteToHardware: Invalid address 00000000
31:56:345 Main         W[MM]: MemmapFunctions.cpp:93 ReadFromHardware: Invalid address 0000000c
31:56:345 Main         W[MM]: MemmapFunctions.cpp:93 ReadFromHardware: Invalid address 00000008
31:56:345 Main         W[MM]: MemmapFunctions.cpp:93 ReadFromHardware: Invalid address 00000008
31:56:345 Main         W[MM]: MemmapFunctions.cpp:93 ReadFromHardware: Invalid address 00000000
31:56:345 Main         W[MM]: MemmapFunctions.cpp:130 WriteToHardware: Invalid address 00000004
31:56:345 Main         W[MM]: MemmapFunctions.cpp:130 WriteToHardware: Invalid address 00000000
31:56:345 Main         W[MM]: MemmapFunctions.cpp:130 WriteToHardware: Invalid address 00000008
31:56:345 Main         I[IO]: HLE\sceIo.cpp:906 stderr: font_error:I, 08c70000
```

NEED FOR SPEED MOST WANTED 5.1.0 thread here https://github.com/hrydgard/ppsspp/issues/4268

**Comment by sum2012** [comment]
BLEACH HEAT OF SOUL 6 (UCAS40258) thread here #6627

**Comment by sum2012** [comment]
@daniel229 
Can you help this to do "Replace frame download " ?
![1](https://cloud.githubusercontent.com/assets/2177532/6126955/bbe7ea2e-b160-11e4-8187-3b6009b7474f.jpg)

Only show word from software rendering.
![2](https://cloud.githubusercontent.com/assets/2177532/6126973/e97ac10a-b160-11e4-94fe-7875cfb32dd6.jpg)

**Comment by daniel229** [comment]
No,that seems like a depth issue.disable depth test,it shows up.
![01](https://cloud.githubusercontent.com/assets/3481559/6127296/37f8395e-b164-11e4-8e7e-f0a0619637ca.png)

**Comment by daniel229** [comment]
That graphical glitch did not happen in v0.9.1-1582-g061efd3,but happend in v0.9.1-1606-g2362640
https://github.com/hrydgard/ppsspp/compare/v0.9.1-1582-g061efd3...v0.9.1-1606-g2362640

**Comment by daniel229** [comment]
Not do optimization in <code>void IndexGenerator::TranslateList(int numInds, const u16 *_inds, int indexOffset) {</code>https://github.com/hrydgard/ppsspp/commit/af46d17b947a4c20c6e65ecf7244f3079a483802#diff-8c61923e7e4d2ddd5c294ee8c3645d06L250
the  graphical glitch is fixed.
![01](https://cloud.githubusercontent.com/assets/3481559/6147903/399a24f6-b237-11e4-82b5-b0e4d385b019.png)

Is this removed by accident?
https://github.com/hrydgard/ppsspp/commit/af46d17b947a4c20c6e65ecf7244f3079a483802#diff-8c61923e7e4d2ddd5c294ee8c3645d06L298

**Comment by hrydgard** [comment]
Hm, it appears so. Does fixing that fix the glitches?

**Comment by daniel229** [comment]
Not fix that glitch with the latest build unfortunately.

**Comment by daniel229** [comment]
Another color investigate game,only works fine in softwareGPU.
![01](https://cloud.githubusercontent.com/assets/3481559/6163029/1b2e1c26-b2c7-11e4-9a42-bfa3d3abf2b8.png)

**Comment by hrydgard** [comment]
Alright, that probably means another framebuffer download function to find... You know how it's done :)

I'll revert that optimization, I think, it's probably very minor.

**Comment by hrydgard** [comment]
@kirous , that should take care of the glitch.

**Comment by daniel229** [comment]
Yeah,a framebuffer download did the trick.

**Comment by hrydgard** [comment]
Anything left to fix here?

**Comment by daniel229** [comment]
PHOTOKANO is fixed.
DARKSTALKERS is duplticate of https://github.com/hrydgard/ppsspp/issues/6647
BLEACH HEAT OF SOUL 6 is duplticate  of https://github.com/hrydgard/ppsspp/issues/7649
NEED FOR SPEED MOST WANTED 5.1.0 is fixed.
I thnk should be closed.
