### ISSUE TITLE
choppy sound in many games [iOS + Sample] 

### ISSUE THREAD

**Issue by brujo5** [hrydgard/ppsspp#7460]
choppy sound in many games Like Dante inferno, Kingdom Heart Birt Sleep,etc

Audio sync on/off not help 
Here un example. Please up the volume to hear.
http://es.tinypic.com/r/2s10kmp/8

**Comment by hrydgard** [comment]
Is this a new problem?

**Comment by brujo5** [comment]
Think yes, had never happened in ios

**Comment by hrydgard** [comment]
Do you know when it started?

**Comment by brujo5** [comment]
I have some recent build (Backup)  Will try in New few hours.

**Comment by brujo5** [comment]
Sorry , after put my device in safe mode find the culprid is an tweak called equalizer everywere.xD
next time I'll be more careful!!
