### ISSUE TITLE
MIYAKO Awayuki no Utage have G3D error in 1.0 but not in 0.9.9.1

### ISSUE THREAD

**Issue by StephDC** [hrydgard/ppsspp#7461]
Title: 雅恋～ＭＩＹＡＫＯ～ あわゆきのうたげ MIYAKO Awayuki no Utage
Genre: Visual Novel, Otome Game
Region: JP
Format: ISO
Game ID: ULJM-06070
Version: v1.0
OS:
GNU/Linux Ubuntu 14.10 3.16.0-28-generic amd64
MAC OS X 10.10.2 (MBP 15'' Retina with nVidia GeForce GT 750M)
Windows 7 (this one not tested by me)
Compatibility: Crash
Notes:
It has some small display problems on something like 0.9.8 or 0.9.6, but works perfectly on 0.9.9.1.

Debug info from Mac:
Crashed Thread:        9

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00000023000000cc

The whole crash report text could be found at http://paste.ubuntu.com/10149983/

Last line of log:
16:39:891 user_main    E[G3D]: GPU/GPUCommon.cpp:226 sceGeListEnqueue: can't enqueue, stack address 0899DCB4 already used
zsh: segmentation fault  Downloads/ppssppbuildbot-org/PPSSPPSDL.app/Contents/MacOS/PPSSPPSDL

The last few lines of runtime log (as shown in Terminal, every logging channel are set to info) could be found at http://paste.ubuntu.com/10150999/

Seems like there is something wrong with the G3D...

Process to make the game crash (Worked on both GNU/Linux and Mac OS X):
1. Open PPSSPP
2. Open the game Miyako Awayuki no Utage
3. Start a new game
4.a Press start key so it plays automatically and wait for a while
4.b Press O for several times just to pretend you are playing the game
5. Boom.

**Comment by daniel229** [comment]
Revert https://github.com/unknownbrackets/ppsspp/commit/337b34ef6a03f56da3a402fab130545833694758 then works fine.

**Comment by StephDC** [comment]
@daniel229 Yes you are right. I have just compiled a new one without that 337b34e and everything was good now!

Will it be more helpful to not implement that 337b34e before it could work better on the main release?

**Comment by hrydgard** [comment]
337b34e has been measured to be very close to correct and fixed some other game probably - it's likely that it's the timing of something else that's wrong. Now, what that might be is the tricky question. Whatever it is, I would consider it a bug in the game to be so timing-dependent...

**Comment by unknownbrackets** [comment]
Well, whatever the game is doing between when it enqueues the list with that stack address, and tries to enqueue another one is where the problem lies.  Could be some HLE call.

-[Unknown]

**Comment by daniel229** [comment]
Setting CPU clock to 1000 is also a workaround for it.

**Comment by unknownbrackets** [comment]
Have any of the timing changes since improved things in this game?

-[Unknown]

**Comment by StephDC** [comment]
It seems that the game is running correctly with the default CPU clock = 0 (auto).

Tested on PPSSPP v1.9.4, macOS Mojave 10.14.6.

Closing the issue.

**Comment by unknownbrackets** [comment]
Glad to hear, thanks for reporting.

-[Unknown]
