### ISSUE TITLE
Weird sound (high pitched/distorted audio/music) when right clicking games in the emulator menu

### ISSUE THREAD

**Issue by vsub** [hrydgard/ppsspp#7472]
I'm using v1.0-38 x86.
1.For example if you right click on FF7CC\Hezyx Force,almost every time when the music start,you'll hear a weird sound(like the pitch is really high)and may be it's just me but I think the sound speed is also wrong during that time(I didn't do much testing but it happens on other games too)

2.Now this is related about the custom game settings:
Remove a game from Recent=>Start a game that have custom settings=>Emulation=>Stop=>the removed game is there again(if it was in the custom settings)

Or start a game that is not in Recent=>Emulation=>Stop=>Start another game from Recent that have settings=>the previous game will be gone from Recent

Or clear the games list and if you start a game that have settings,when you exit from the game=>it will not be in the recent list

Once you clear the list,even if you start all of your games that don't have settings one after another,once you start a game that have settings,it will clear the whole list

**Comment by hrydgard** [comment]
@Bigpet, wanna take a look at issue 2 above?

I'm going to release 1.0.1 this weekend so it would be good to have a fix in. I can try to debug it myself but I'll let you check first :)

**Comment by vsub** [comment]
Yes with DSound(I thought that option only for ingame,not for right click on the game too),there is an improvement.There is still a problem which is hard to be noticed but that problem don't exist on for example 0.9.9-27.
If you have FF7CC,try entering and exiting the game info screen(right click).At some point,you'll notest that something is wrong with the sound for a half a second.

One other thing is,that the game settings are also remembering the save state slot selected while creating it.
For example,the main settings file says 2 and the settings file will make ppsspp to auto select the second slot when you start the game.

And btw @hrydgard,did you notest that the first save state slot box in cut from the top(it's best visible on a game which don't have save state on the first slot)

**Comment by Bigpet** [comment]
Ok, unless I want to go hunting for every single `g_Config.xyz = ` that implicitly relies on the config being saved before it is loaded again or when the program closes, I'm just gonna instead have to save every time before a config is loaded. I'll probably get to that tomorrow since I'm kind of tired right now.

**Comment by hrydgard** [comment]
@vsub yeah I noticed the cut off slot, will fix.

**Comment by thedax** [comment]
Has this been completely fixed?

**Comment by vsub** [comment]
From what I tried,everything except the audio is fixed(you could say that dsound fix it at 99%)

**Comment by unknownbrackets** [comment]
Does the audio issue still occur?  I fixed something that sounds possibly like the same problem.

-[Unknown]

**Comment by ppmeis** [comment]
I tested with latest build. There is no stuttering or weird sound. I made right click in three different games (CCFF7 included) about ten times in a row without any issue.
