### ISSUE TITLE
The measure of fixed the bug of TENCHU 3 infinite loading

### ISSUE THREAD

**Issue by Aniark** [hrydgard/ppsspp#7474]
Here is it https://github.com/hrydgard/ppsspp/issues/6370

**Comment by unknownbrackets** [comment]
The only way I'm able to read this issue is "I want to annoy you so that you will never ever look at that issue.  Please promise me you'll never try to fix it."  If you want me to make that promise, please open another duplicate like this.

-[Unknown]
