### ISSUE TITLE
Windows:Lose keyboard control from menu to fullscreen

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#7480]
1:Go to full screen from menu as picture,
![2](https://cloud.githubusercontent.com/assets/2177532/6203747/d57901b2-b56b-11e4-9afa-5300037011f3.jpg)

2:use mouse click game

3:The keyboard would lost control

**Comment by vnctdj** [comment]
Indeed, I can reproduce the error.
However the keyboard is not totally blocked, F11 and F12 still work for example :)

**Comment by hrydgard** [comment]
Thanks, good find. Was a bit tricky to figure out but I got it :)  Not sure the PostMessage thing is needed (was the first thing I tried) but it can't really hurt.

**Comment by sum2012** [comment]
Thanks @hrydgard
