### ISSUE TITLE
PS3 joystick problem with noisy analog axis

### ISSUE THREAD

**Issue by sergiobenrocha2** [hrydgard/ppsspp#7482]
Impossible to configure a PS3 joystick, ppsspp receives some noisy from the analog axis.

Try to configure one button, and you get always "pad1.b8", even if joystick is stuck in the ground heh.

I don't know if it helps, but Cabrio FE which uses SDL 1.2 has this problem too, I tweaked a little bit and noticed that SDL was sending many events such as 0 value in axis 0, 1, 2 and 3 (right and left analog) and -32768 in axis 12 (maybe accelerometer?).

Dolphin emu 4.0 had this problem too, but in master branch it doesn't have anymore (possibly a fix from there?).

**Comment by hrydgard** [comment]
That's really weird, seems like a joystick driver issue more than a PPSSPP issue? However, 0-value events should not cause mapping an axis...

**Comment by xperia64** [comment]
Are you sure it's not a problem with the PS3 controller itself? Which driver are you using? And is this over USB or Bluetooth? My older DS3 is randomly 'noisy' when connected via USB with the motioninjoy drivers, while my newer one does not have this issue.

**Comment by sergiobenrocha2** [comment]
I'm using USB. Well, the problem seems to be with the PS3 controller, since I have one generic clone here that does not have this issue, but as I said, there is some way of get it working well, like in dolphin emu.

**Comment by wargnomes** [comment]
use the new scp driver, theres a version for  ps3 and ps4 wired or wireless.emulates the xbox controller
for all games.

**Comment by Bigpet** [comment]
@wargnomes he's obviously using a unix OS, so I don't think Windows drivers will help him

**Comment by unknownbrackets** [comment]
Is this still an issue?  Maybe it could've been related to gamecontrollerdb?

-[Unknown]
