### ISSUE TITLE
Controller can't navigate the menu properly (OS X)

### ISSUE THREAD

**Issue by LeonBlade** [hrydgard/ppsspp#7486]
Hello,

I have an issue with the DS4 controller on my system with PPSSPP when trying to navigate the Pause menu.  The dualshock 4's d-pad is recognized as a hat switch (which it is) and works fine, but the face buttons are recognized as Left/Right/Down/Up.

This isn't an issue when playing the game itself, but it becomes a problem when trying to navigate the pause menu, as the buttons are not being interpreted properly, so they just end up controlling directional buttons instead.

I'm not sure if this is a problem with the controllers on OS X or what the actual issue is, but I'm wondering if there would be an easy way to rectify this.  I was thinking if there was a separate section to bind inputs to the actual menu inputs that this could fix the problem?

I know that currently you are mapping what is supposed to be the Circle and Cross buttons to these inputs already, but because my values are coming back as 18-21, there isn't any way for me to override this without breaking other input support.

Is this something that should be looked into?  Or should I just create my own fix?  
I run OS X 10.10.2 (Yosemite), I've tried using both the DS4 and the DS3 and the DS3 still doesn't map the buttons properly either.

Sorry for this mess of an issue, I hope you understand what I'm trying to convey here.

**Comment by LeonBlade** [comment]
Okay, after looking into the root of the problem, it seems like this is something that's already kind of known internally with the state of how the controllers are handled and how their buttons are matched to key codes, in `input_state.h` there is mention of implementing NativeTouch/Key/Axis to extend support.

The mapping done for Xbox 360 controllers for the UI elements isn't enough in this case, I will create my own mapping.

**Comment by LeonBlade** [comment]
I did a hotfix for the problem, leonblade@7e289c37fea361e0ff8d6e1be834f6000b5b0384 leonblade/native@7fe620af5bc2050c62007450289083de8b3f4166 which basically just changes the key mappings to other values which fixed my problem.

Is this something that should be addressed for the actual project though?  It could just be a fluke with my environment, but I can see this being an issue for other people as well.

**Comment by unknownbrackets** [comment]
Does #8286 solve this for you?

Otherwise, I think we should probably close and generalize this into #7847, which is essentially the same issue.

-[Unknown]
