### ISSUE TITLE
A small problem Shining Hearts (NPJH50342)

### ISSUE THREAD

**Issue by kirous** [hrydgard/ppsspp#7488]
Hello, the problem come to be the box questions like the picture looks:

![box questions](https://cloud.githubusercontent.com/assets/5083411/6223869/4e3dc0e0-b640-11e4-9378-22dc8af0c9b4.png)

Since choosing either option automatically, you must disappear or fade, which rarely blinking box responses.

In PPSSPP v1.0 version has problems in the main menu options (flashes to enter and exit the options), as the response box.

Instead version PPSSPP V1.0-75-g635f43b, everything is OK, but the answer box.

Hopefully they can fix this little problem.

**Comment by daniel229** [comment]
It seems that the blink gone when turn off vertex cache.

**Comment by unknownbrackets** [comment]
I'm not sure there's much we can do about this.  Since the box remains active on screen for long enough, we start to think/hope that it's safe to cache, and then when it starts fading out we realize it's not true too late.

-[Unknown]

**Comment by unknownbrackets** [comment]
Vertex cache is now off by default, so this should be fixed.  Closing.

There's not a lot that can be done, as per above, when using caching.  Luckily, it's not as useful in backends like Vulkan anyway.

-[Unknown]
