### ISSUE TITLE
 No background sound game "LA PUCELLE Ragnarok (ULJS00244)" is heard

### ISSUE THREAD

**Issue by kirous** [hrydgard/ppsspp#7490]
In the gameplay. In version 1.0 and recent BUILD, No background noise is heard game. However in versions 0.9.8 to 0.9.9.1, if the background noise is heard at the time of the gameplay.

Here a picture on the part of the gameplay:

![lprns](https://cloud.githubusercontent.com/assets/5083411/6224500/d6f5a81c-b64a-11e4-9185-e7e642ae180b.jpg)

I hope they fix that little problem. Before take out the version 1.0.1

**Comment by sum2012** [comment]
Try newest version
http://buildbot.orphis.net/ppsspp/
I test that have  background noise in v1.0-80-ge89c881
I use default setting
I am using Windows 7

**Comment by kirous** [comment]
Follow on audio problems in version 1.0.1 for this game

Here a comparison image.

![v1 0 1](https://cloud.githubusercontent.com/assets/5083411/6407222/e4362152-be09-11e4-8e16-a42eceffbe45.jpg)

In red is the error (PPSSPP V1.0.1).

Instead of starting you told me the new version to BUILD V1.0-104, everything OK.

![vbuild1 0-104](https://cloud.githubusercontent.com/assets/5083411/6407231/077133be-be0a-11e4-812a-b7017ac11a08.jpg)

It would be good to come up again at version 1.0.1, or wait another improved version .... Waiting.

**Comment by sum2012** [comment]
I re-test no problem
Do you use english patch
Or enable "use Sound speed hack" etc option ?

**Comment by unknownbrackets** [comment]
Without feedback, we can't tell if there are still problems, but it sounds like this has been fixed.

If it's still an issue, please feel free to comment with more detail / answers to the above.

-[Unknown]
