### ISSUE TITLE
Final Fantasy Type 0 crash in-game

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#7494]
Load save status
https://drive.google.com/file/d/0B3OaSdeV0L8kaXpEUmRBYzdsOE0/view?usp=sharing

Request to investigate the story of a detonation device, immediately after the investigation calculus animation, and then raise crash

v1.0-77-g1d7b0ae debug log:
https://drive.google.com/file/d/0B3OaSdeV0L8kcjgzSFA3MTlacG8/view?usp=sharing

No useful crash strace (I have turned off fast memory)
![1](https://cloud.githubusercontent.com/assets/2177532/6236154/e663fb04-b722-11e4-8452-3a267b641449.jpg)

Seem this problem
56:12:908 user_main    D[G3D]: GPUCommon.cpp:690 Okay, starting DL execution at 0907c66c - stall = 0907c988
56:12:908 user_main    D[G3D]: Common\VertexDecoderCommon.cpp:856 VTYPE with morph used: THRU=0 TC=3 COL=1 POS=0 NRM=1 WT=3 NW=5 IDX=3 MC=4
56:12:908 user_main    E[G3D]: Common\VertexDecoderCommon.cpp:1009 Vertices without position found
56:12:908 user_main    D[G3D]: Common\VertexDecoderCommon.cpp:1040 SVT : size = 32, aligned to biggest 4
56:12:908 user_main    W[G3D]: Common\VertexDecoderCommon.cpp:1046 Vertex decoder JIT failed! fmt = 000f1e27

**Comment by unknownbrackets** [comment]
Does it work if you disable vertexjit / use the software renderer?

I didn't realize we still had vertex formats that we didn't jit.  Invalid maybe?  This wasn't corrupted by using "read framebuffers to memory" or cheats or anything, right?

-[Unknown]

**Comment by hrydgard** [comment]
It says "Vertices without position found", which isn't valid AFAIK.

However, we should be able to handle it better than crashing...

**Comment by sum2012** [comment]
It still doesn't work by disable vertexjit / use the software renderer

**Comment by sum2012** [comment]
This was reported by chinese ppsspp forum
http://tieba.baidu.com/p/3566734803?share=9105&fr=share
I am going to ask whether he use "read framebuffers to memory "

**Comment by daniel229** [comment]
That crash is due to multithreaded.Turn off multithreaded,load from game save it wouldn't crash.
