### ISSUE TITLE
glew.h compilation fail

### ISSUE THREAD

**Issue by GAMELASTER** [hrydgard/ppsspp#7495]
I gitted a fresh new PPSSPP project to my Raspberry, but today is writing me some errors at beggining of build:
http://pastebin.com/GqerC41b
(Adresár alebo súbor neexistuje == Directory or file not exists)

But yesterday fresh PPSSPP works good without any changes (only putting my compiled FFMPEG for ARMv7), but today is writing this error.

I tryied triple to build the newest version but failure. Now testing this in Ubuntu.

**Comment by GAMELASTER** [comment]
So, its doing probably only on Raspberry, i dont know how but its... Now i tried that on my Ubuntu but without problem. But as i said, its works yesterday

**Comment by GAMELASTER** [comment]
Reopening, miss click -_-

**Comment by hrydgard** [comment]
Looks like it can't find the path to glu.h? Where is that on your system?

**Comment by GAMELASTER** [comment]
On raspberry i use Raspbian what is modified Debian, but as i said upper, its started doing it only today, yesterday has been allright!

**Comment by GAMELASTER** [comment]
Okey, already i found trouble, its not about project, but for anyone who have too problem. U missing some OpenGL dev libraries on your Linux :-)
