### ISSUE TITLE
Metal Fear Solid Peace Walker

### ISSUE THREAD

**Issue by TrojanRanson** [hrydgard/ppsspp#7497]
the game crashes when playing a video in which you want to play. :(

**Comment by GAMELASTER** [comment]
Can u send the save profile before it crash or something more about crash? Its help to fix that bug :-)

**Comment by Bigpet** [comment]
duplicate of #7436 ?

**Comment by TrojanRanson** [comment]
where the file Crush game? ios 7.1.2 noob:-(

**Comment by unknownbrackets** [comment]
I suppose there's something wrong with ffmpeg on iOS.

Closing as duplicate of #7360.  Everything crashes on iOS and we don't have any iOS maintainers right now.

-[Unknown]
