### ISSUE TITLE
AdHoc on Linux Ubuntu bugging

### ISSUE THREAD

**Issue by gamelaster** [hrydgard/ppsspp#7499]
I wanted to try AdHoc on my Ubuntu, but anyway if i using AdHoc server or built in Adhoc server, the PPSSPP still reconnecting. Trying it on GTA Liberty City Stories.
Result from Server Console:

New Connection from 192.168.1.66.
PPSSPP (MAC: 3A:4F:4D:B5:64:82 - IP: 192.168.1.66) started playing ULUS10041.
PPSSPP (MAC: 3A:4F:4D:B5:64:82 - IP: 192.168.1.66) joined ULUS10041 group GTALCS00.
PPSSPP (MAC: 3A:4F:4D:B5:64:82 - IP: 192.168.1.66) left ULUS10041 group GTALCS00.
PPSSPP (MAC: 3A:4F:4D:B5:64:82 - IP: 192.168.1.66) stopped playing ULUS10041.
New Connection from 192.168.1.66.
PPSSPP (MAC: 3A:4F:4D:B5:64:82 - IP: 192.168.1.66) started playing ULUS10041.
PPSSPP (MAC: 3A:4F:4D:B5:64:82 - IP: 192.168.1.66) joined ULUS10041 group GTALCS00.
PPSSPP (MAC: 3A:4F:4D:B5:64:82 - IP: 192.168.1.66) left ULUS10041 group GTALCS00.
PPSSPP (MAC: 3A:4F:4D:B5:64:82 - IP: 192.168.1.66) stopped playing ULUS10041.

On Windows all works great!

**Comment by lightfirst** [comment]
try using sudo

**Comment by unknownbrackets** [comment]
It sounds like this is an issue with privileged ports - going to close in favor of #7268.  But this is likely still an issue, unless you and the other players all use the same "port offset" value.

-[Unknown]
