### ISSUE TITLE
Feature request:Add osm for record for graphic mode for save status

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#7500]
When load save status,it would display you saved in which graphic mode .
eg:Non-buffered render,Buffered rendering,Read framebuffersto memory(CPU),Read framebuffersto memory(GPU),software rendering
edit:for older version,can use "unknown graphic mode" message

@unknownbrackets said that framebuffers to memory would corrupt memory.

**Comment by unknownbrackets** [comment]
If you're not able to enable compatibility reports, it means some feature was used that corrupts things.

-[Unknown]
