### ISSUE TITLE
Jak & Daxter :  "Unknown GetPointer" and make the game run slow FPS.

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#7502]
DEMO,pressing triangle is to skip video.
https://drive.google.com/file/d/0BzGZGDfFE68zc3Raa2t2ZzBLcWM

![01](https://cloud.githubusercontent.com/assets/3481559/6261433/e7c60cc8-b829-11e4-9ccb-e9ca129b27ed.png)
![02](https://cloud.githubusercontent.com/assets/3481559/6261434/e7c77838-b829-11e4-8afc-6215abc57dce.png)

FuncReplacements = False 
normal FPS
![03](https://cloud.githubusercontent.com/assets/3481559/6261432/e7c5ea54-b829-11e4-9cf6-2ce7be15854e.png)

**Comment by hrydgard** [comment]
Commenting out

    { "memcpy", &Replace_memcpy, 0, 0 },

and 

    { "memset", &Replace_memset, 0, 0 },

fixes it. Strangely, only commenting out memcpy but not memset causes the game to crash in fast memory mode. Feels like it's relying on some return value from memcpy to then do a memset?

**Comment by hrydgard** [comment]
Rather scary this one - the game relies on some non-return registers to be set correctly after the function. Fixed, but there might be more of this kind of bug out there..

**Comment by daniel229** [comment]
Great,how about the "Unknown GetPointer" before intro,also not happen when FuncReplacements = False .
![01](https://cloud.githubusercontent.com/assets/3481559/6267359/337b06e2-b87e-11e4-99b5-ec81f350dbc7.png)

**Comment by hrydgard** [comment]
Oh, I missed that one. I'll check soon

**Comment by hrydgard** [comment]
Hm, starting to feel like a timing issue? None of the "thread not dormant" or ReferEventFlagStatus errors happen when not using function replacement...

**Comment by hrydgard** [comment]
Timing issue indeed, bleh.

**Comment by daniel229** [comment]
Not fix this game,but seems help https://github.com/hrydgard/ppsspp/issues/6695 and https://github.com/hrydgard/ppsspp/issues/6665

**Comment by brujo5** [comment]
since build 1.0-83 1ecfd6cebcd8bb97722be4dc6fbc48f3ea71fe56 Have slowdowns in the game Dante inferno, drop fps from 40/40 to 29/40

In build 1.0-80 is fine.no slowdown

**Comment by hrydgard** [comment]
Thanks @brujo5 

I'm starting to lean towards not replacing these functions that have highly variable timing, instead just hook and do the copy, then let them run.

**Comment by unknownbrackets** [comment]
Well, we will have to hook memcpy on enter and exit, but yeah, that may be the simplest thing.  I wonder what the perf impact is.

-[Unknown]

**Comment by brujo5** [comment]
@hrydgard 

Here other game that work in slowmov also in non-buffered rendering since 1.0-83 .
And cause overheat

before 1.0-81/82  60/60 fps
![image](https://cloud.githubusercontent.com/assets/4172898/6314848/e3b0eb52-b9ab-11e4-84d3-236ba429868e.jpg)
In 1.0-83 29/60fps overheat 
![image](https://cloud.githubusercontent.com/assets/4172898/6314855/240d168a-b9ac-11e4-9f42-b647b848f060.jpg)

**Comment by unknownbrackets** [comment]
Even using hooks, this game crashes.

More importantly, in interpreter, it works, but in jit it doesn't work.

So, it's almost definitely a bug in the jit.  I wonder if this happens on arm too?

-[Unknown]

**Comment by hrydgard** [comment]
@daniel229 how about build 1.0-84 in Tomb Raider?

Yeah, I don't get what's going on here...

**Comment by brujo5** [comment]
Will try later today. Hoop  the update come out in cydia very soon.

**Comment by daniel229** [comment]
@unknownbrackets Is it the crash not randomly happening?Those errors may sometime happen,sometime not.
@hrydgard I suppose you @brujo5

**Comment by unknownbrackets** [comment]
Yeah, I ended up getting random crashes in even interp with no replacements, but it didn't happen every time.  It seems way more likely with replacements enabled.

-[Unknown]

**Comment by brujo5** [comment]
In build 1.0-86 retest dante inferno/tomb raider legends, slowdowns still going on but not too much lower fps. 
Example in Dante inferno build 1.0-83
Slowdowns  29/40 fps
Now in 1.0-86 increase an bit 
slowdowns 34/40 fps

**Comment by hrydgard** [comment]
I think I'm gonna leave it like it is now for 1.0.1. We will have to look more into why replacements cause some misbehavior later..

**Comment by unknownbrackets** [comment]
I hope you're not using any adjusted cpu clock setting.  We've already confirmed through testing that the current speed is faster than on real hardware, and matches replacements being off.

-[Unknown]

**Comment by brujo5** [comment]
Nope never use cpu speed hack on this game because make sound very choppy.

**Comment by sum2012** [comment]
@daniel229 Does v1.3-540-g29739c8 or newer version fixed ?
I only tested beginning no problem

**Comment by benderscruffy01** [comment]
no problems so far
i think this can be closed
