### ISSUE TITLE
ICON1.PMF support in game settings?

### ISSUE THREAD

**Issue by Blackbird88** [hrydgard/ppsspp#7505]
I noticed only AT3 sound works for some reason. Is this hard to do, because I thought this video format is used by PSP games as well.

**Comment by hrydgard** [comment]
Totally possible, just a bit of work I haven't gotten around to yet...

**Comment by kirous** [comment]
Hello, I wanted to ask. I was watching the specifications of sound in real PSP, and there is a point that says there games that support 3D 7.1 sound, if not already included or will be included in future versions of the emulator?.

**Comment by unknownbrackets** [comment]
Closing as a duplicate of #2585.

The PSP's APIs and hardware are not capable of surround sound.  There were products for it which simulated surround sound, afaik.

-[Unknown]
