### ISSUE TITLE
Meizu MX4 (PowerVR). Problem with light or...

### ISSUE THREAD

**Issue by Sho0oT** [hrydgard/ppsspp#7510]
![s41126-194213](https://cloud.githubusercontent.com/assets/11142172/6317359/f1e32a74-ba5e-11e4-9f65-93e73b7e9991.jpg)
![s41126-194542](https://cloud.githubusercontent.com/assets/11142172/6317360/f1fe5ce0-ba5e-11e4-8541-6841d9319dbe.jpg)

**Comment by Sho0oT** [comment]
v0.91 last no errors

**Comment by sum2012** [comment]
Try to find out last no error version
http://pan.baidu.com/s/1hqqVjpE#path=%252FPPSSPP%252FOlder_Releases
![3](https://cloud.githubusercontent.com/assets/2177532/6317968/bd5588c2-bab0-11e4-9799-0c4f536666a5.png)

**Comment by Sho0oT** [comment]
0.9.5-1 - no error
0.9.5-996 - error
I will now clarify which version of precisely the error occurred...
p.s.: sorry for my terrible English

**Comment by hrydgard** [comment]
Thanks for testing! I will look into it soon.

**Comment by sum2012** [comment]
That is 
v0.9.5-955-gd5147c4 no error
v0.9.5-959-g4998044 have error
That mean #4747 pull request

**Comment by sum2012** [comment]
@Sho0oT 
What is your game in the first picture ?

**Comment by Sho0oT** [comment]
@sum2012  =) Tekken6

**Comment by hrydgard** [comment]
That commit should be pretty safe, if that breaks things like this, the device definitely has some seriously buggy OpenGL drivers :(

**Comment by Sho0oT** [comment]
"the device definitely has some seriously buggy OpenGL drivers"
Yes it is, at the level of the emulator can not be fixed? =(

**Comment by sum2012** [comment]
I don't have problem on my phone (lg nexus 5).
You need to do 2 more additional test for better bisect.

Do this build work ?
https://drive.google.com/file/d/0B3OaSdeV0L8kY1JuUVhaRklfblk/view?usp=sharing

**Comment by Sho0oT** [comment]
@sum2012
Yes, this works!
![s50223-162820](https://cloud.githubusercontent.com/assets/11142172/6328529/e11262e0-bb81-11e4-86e1-53111131e0e7.jpg)
You can fix this transfer to v1.0-xx?

**Comment by sum2012** [comment]
![1](https://cloud.githubusercontent.com/assets/2177532/6328568/c2b9e4ea-bba3-11e4-90f1-b4bba1236ad6.png)
That mean this commit https://github.com/unknownbrackets/ppsspp/commit/2df1db4c7ef30ebb87f4b9e45af9e0677a27f968

@Sho0oT 
I will give you last test (just revert that commit) within 30 minute

**Comment by Sho0oT** [comment]
Dear hrydgard, could you tell me what exactly is wrong with the OpenGL driver? So as I pointed out in a letter to the developers of the firmware of my device.
This problem happens on some games Android...

**Comment by sum2012** [comment]
@Sho0oT This is really last time to confirm which commit break it.
Do this build work ?
https://drive.google.com/file/d/0B3OaSdeV0L8kMEMyWUJSVklEajg/view?usp=sharing

**Comment by Sho0oT** [comment]
@sum2012 
Test ready as you need, the main thing is that everything worked in the future.
Thank you for your works.

This version again with the error.

**Comment by sum2012** [comment]
@Sho0oT This is really confirm this commit
https://github.com/unknownbrackets/ppsspp/commit/2df1db4c7ef30ebb87f4b9e45af9e0677a27f968
have problem with your phone.
I will make another build with revert that code

![2](https://cloud.githubusercontent.com/assets/2177532/6329088/596b69aa-bba8-11e4-9a2e-71a6c57ca43a.png)

**Comment by sum2012** [comment]
@Sho0oT This is v1.0-97-gf2cde73 with revert that commit.
Does this work ?
https://drive.google.com/file/d/0B3OaSdeV0L8kQWtiQnlCSjd5TG8/view?usp=sharing

**Comment by Sho0oT** [comment]
@sum2012 
Thank you, everything works.

**Comment by sum2012** [comment]
Let @hrydgard decide revert that commit https://github.com/unknownbrackets/ppsspp/commit/2df1db4c7ef30ebb87f4b9e45af9e0677a27f968
or add an option

**Comment by hrydgard** [comment]
So it seems GL_CONSTANT_COLOR misbehaves. We could detect PowerVR or this particular device and disable that code..  I will think about it.

Can you post the stuff you see in Settings/Developer Tools/System Information about system and graphics?

**Comment by Sho0oT** [comment]
@hrydgard 
You about this?
![s50223-182133](https://cloud.githubusercontent.com/assets/11142172/6330450/dfb0c7e2-bb91-11e4-8403-2f15f7dda919.jpg)
![s50223-182144](https://cloud.githubusercontent.com/assets/11142172/6330451/dfb206f2-bb91-11e4-95bd-4b3926f1ce11.jpg)
P.S.: I wrote to the developers of the firmware on the problem.
Added a bunch of screenshots of the problematic games and a link to this correspondence.

**Comment by Sho0oT** [comment]
Examples of problems in games
![w7wzj1a8dz4](https://cloud.githubusercontent.com/assets/11142172/6330554/cab8593a-bb92-11e4-9872-cc0ca0b4e1ac.jpg)
![wrf2yuhc7zk](https://cloud.githubusercontent.com/assets/11142172/6330555/cab85e08-bb92-11e4-86db-a26ad33e2275.jpg)
It seems to me that this is the same problem here.

**Comment by hrydgard** [comment]
No, I mean in PPSSPP's settings :)

**Comment by Sho0oT** [comment]
Pardon =)
![s50223-184431](https://cloud.githubusercontent.com/assets/11142172/6330817/f59feda0-bb94-11e4-8b92-39cf5f3d0c5d.jpg)
![s50223-184440](https://cloud.githubusercontent.com/assets/11142172/6330818/f5a0ea8e-bb94-11e4-9534-d51e5cea80f9.jpg)
![s50223-184452](https://cloud.githubusercontent.com/assets/11142172/6330815/f59cd994-bb94-11e4-92f0-b44e16137ad6.jpg)
![s50223-184456](https://cloud.githubusercontent.com/assets/11142172/6330819/f5a10dca-bb94-11e4-81f9-bb9725a5e28c.jpg)
![s50223-184506](https://cloud.githubusercontent.com/assets/11142172/6330820/f5a5c8a6-bb94-11e4-8c52-efd7cd19c44b.jpg)
![s50223-184511](https://cloud.githubusercontent.com/assets/11142172/6330816/f59d752a-bb94-11e4-905e-9e9ae2c9ff7f.jpg)
![s50223-184527](https://cloud.githubusercontent.com/assets/11142172/6330822/f5d43d6c-bb94-11e4-9004-b057d243cacc.jpg)
![s50223-184537](https://cloud.githubusercontent.com/assets/11142172/6330821/f5bb0bbc-bb94-11e4-93b5-cb0edb1b9365.jpg)
![s50223-184543](https://cloud.githubusercontent.com/assets/11142172/6330823/f5d52ed4-bb94-11e4-854f-83649cc4c121.jpg)
![s50223-184547](https://cloud.githubusercontent.com/assets/11142172/6330824/f5d528f8-bb94-11e4-9f81-0070e0b6b7ef.jpg)

**Comment by hrydgard** [comment]
Thanks. I guess we can detect "PowerVR Rogue" and turn that code off, or something...

These things are quite annoying :P

**Comment by Sho0oT** [comment]
@hrydgard Test the version laid out sum2012 ...
The problems described above are gone , only the playback speed dropped many times ... Unplayable .
Will wait for a response from the developers of firmware, hopefully fixed the problem.

**Comment by hrydgard** [comment]
Hm, wonder what could have caused a speed drop?

What's the speed like if you run the current 1.0 (even though graphics are broken)?

**Comment by hrydgard** [comment]
@Sho0oT , OK, test the very latest build now.

**Comment by Sho0oT** [comment]
@hrydgard 
All right, You are right. Faster was when not working graphics))
Set up, all is now well.
Thanks for a wonderful program.

**Comment by hrydgard** [comment]
Thanks for your testing!

It seems indeed that the "constant color" blend feature is broken on some powervr, possibly only the alpha channel. We now avoid using that feature as much as possible, which is probably good anyway...  As this solves this particular problem I'll close this issue for now, not much else that can be done probably.

**Comment by sum2012** [comment]
Well done @hrydgard 
and Well done @Sho0oT help himself to test many build :)

**Comment by hrydgard** [comment]
@sum2012 and well done @unknownbrackets too, don't forget he actually did the fix :)

**Comment by sum2012** [comment]
Yes , I forget  @unknownbrackets :)
