### ISSUE TITLE
Ad Hoc between PC-Emulator <-> Android/PC-Emulator loops forever

### ISSUE THREAD

**Issue by pvrajeshkumar** [hrydgard/ppsspp#7512]
When connected to play multiplayer (Monster Hunter Freedom) with Ad Hoc option set between PC-Emulator <-> Android/PC-Emulator, only one of them gets to proceed. Other one just stops at the same connecting message popping-up always & doesn't proceed further even after long time wait.

**Comment by pvrajeshkumar** [comment]
Both are connected under same router.
While one loops at same screen, other can proceed & play further.

**Comment by pvrajeshkumar** [comment]
![monster_hunter_freedom_adhoc](https://cloud.githubusercontent.com/assets/10847678/6319911/381803ca-baf5-11e4-9156-d2e66c328934.jpg)

**Comment by pvrajeshkumar** [comment]
Sorry for missing the debug logs.

51:24:377 user_main    W[ME]: HLE\sceAtrac.cpp:1462 This is an atrac3 stereo audio
51:24:466 user_main    I[G3D]: GLES\ShaderManager.cpp:140 Linked shader: vs 19 fs 32
51:30:063 user_main    I[G3D]: GLES\ShaderManager.cpp:140 Linked shader: vs 19 fs 75
51:30:080 user_main    W[NET]: HLE\sceNet.cpp:119 sceNetInit(poolsize=131072, calloutpri=32, calloutstack=0, netintrpri=32, netintrstack=0) at 0889ddc
c
51:30:084 user_main    I[NET]: HLE\sceNetAdhoc.cpp:151 sceNetAdhocInit() at 0889de78
51:30:084 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2176 306=sceKernelCreateThread(name=AdhocThread, entry=08000100, prio=10, stacksize=4096)
51:30:084 user_main    W[KERNEL]: HLE\sceKernelThread.cpp:2178 sceKernelCreateThread(name=AdhocThread): unsupported options parameter 00001000
51:30:116 user_main    I[NET]: HLE\sceNetAdhoc.cpp:177 sceNetAdhocctlInit(8192, 48, 098ec570) at 0889deec
51:30:604 CsePspAtrac3 I[NET]: HLE\proAdhoc.cpp:1003 FriendFinder: Begin of Friend Finder Thread
51:30:611 user_main    W[NET]: HLE\sceNetAdhoc.cpp:1017 UNTESTED sceNetAdhocctlAddHandler(889d8a8, 0): added handler 0
51:30:630 user_main    I[NET]: HLE\sceNetAdhoc.cpp:857 sceNetAdhocctlScan() at 0889f7ac
52:51:900 idle0        I[SCEGE]: GLES\Framebuffer.cpp:1865 Destroying FBO for 00044000 : 481 x 273 x 1
52:51:900 idle0        I[SCEGE]: GLES\Framebuffer.cpp:1865 Destroying FBO for 00000000 : 481 x 273 x 1
52:51:953 user_main    I[SCEGE]: Common\FramebufferCommon.cpp:331 Creating FBO for 00000000 : 481 x 273 x 1
52:51:972 user_main    I[SCEGE]: Common\FramebufferCommon.cpp:331 Creating FBO for 00044000 : 481 x 273 x 1


***************************************

Problem is here....

51:30:084 user_main    W[KERNEL]: HLE\sceKernelThread.cpp:2178 sceKernelCreateThread(name=AdhocThread): unsupported options parameter 00001000


![image](https://cloud.githubusercontent.com/assets/10847678/6319977/f6dff5ea-baf7-11e4-8db7-2a5ebac4e18f.png)

**Comment by unknownbrackets** [comment]
That is almost definitely not the problem.

-[Unknown]

**Comment by pvrajeshkumar** [comment]
Does that mean, not yet supported feature?
I'll check the code once after syncing to latest version.

**Comment by unknownbrackets** [comment]
The "unsupported options parameter" is only because the code (in PPSSPP) is trying to start the thread using the kernel thread option, which is indeed unsupported.  I don't think that's correct, because I think on a real PSP it's actually started as a user thread (and uses user heap as its stack), but I have not really messed with adhoc code much since it isn't super interesting to me.

In any case, this isn't going to create some incompatibility between Android and Windows or other platforms.

-[Unknown]

**Comment by pvrajeshkumar** [comment]
OK. So, on actual PSP it has started that thread & so it might work.
But, on PPSSPP, will there be plan to start that kernel thread?

@hrydgard : Could you comment on this?

**Comment by unknownbrackets** [comment]
It starts the thread anyway.  It's just a warning that it's probably doing the right thing when the sceNet code is actually wrong.  All I"m saying is that you said "I found the problem", but unfortunately you very likely have not yet found the problem.

Please try not to focus on the unimportant warning message.  I'm telling you that it's not causing the problems you observe.  If you don't want to believe me, good luck with that.

-[Unknown]

**Comment by pvrajeshkumar** [comment]
OK. Thanks for the information.
In such case, if I have to connect 2 PPSSPPs in Ad-Hoc to play multi player game, how should I do?
Any settings recommended on both PPSSPPs (One PC to another PC connected under same router)?

**Comment by pvrajeshkumar** [comment]
When I tried on both PCs with Network & Ad-HOC server selected, on one PC I get this error.
Any settings recommended on both PPSSPPs (One PC to another PC connected under same router) to get this Ad-HOC mode working?

![image](https://cloud.githubusercontent.com/assets/10847678/6357914/f4d1f6d0-bc8d-11e4-959e-c5aef5bfc477.png)

**Comment by pvrajeshkumar** [comment]
Any settings recommended on both PPSSPPs (One PC to another PC connected under same router) to get this Ad-HOC mode working?

**Comment by unknownbrackets** [comment]
Is this still an issue in the latest git builds?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
