### ISSUE TITLE
On small screens, System tab not visible in Portrait - so no way to switch back to Landscape

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#7521]
The new Networking tab has eaten up the space.

Not sure if I should make the tab bar wrap or scroll or what...

**Comment by unknownbrackets** [comment]
Hmm, this time it didn't auto-close.

-[Unknown]

**Comment by hrydgard** [comment]
Maybe because I wrote "fixing" instead of "fixed" ? hm
