### ISSUE TITLE
FF Type-0 crashes when Non-Buffered Rendering is selected

### ISSUE THREAD

**Issue by LegendOfAB** [hrydgard/ppsspp#7523]
If i launch the game while it's selected, PPSSPP freezes then knocks me out a few seconds later. If i switch to non-buffered rendering during the game, the screen starts blinking to a black screen every few seconds then freezes when i get to a certain scene in the tutorial. 

Also, has the problem that prevents you from mapping certain directions of the analog stick of a controller fixed yet? I would like to know before i buy the C4All tweak

**Comment by hrydgard** [comment]
Is this on iOS? Some tweaks and some jailbreak methods cause PPSSPP to be very unstable.

That depends, on Windows and Android mapping anything seems fine, on iOS I can't make any promises.

**Comment by LegendOfAB** [comment]
Sorry, forgot to mention i'm on IOS. 

And these problems aren't really affecting me too much, since if i really wanted to play Type-0 i could just use my PC. But i figured i'd bring it to your attention for other people who can't play it as easily (though i know the IOS side of ppsspp isn't as popular), you know?

**Comment by hrydgard** [comment]
IOS with all its jailbreak hacks is a very unstable platform so we don't officially support it. Thanks for reporting, but I think we'll just have to chuck this in with the other iOS issues in #7360
