### ISSUE TITLE
dai-2-ji super robot taisen z saisei-hen graphical problem (Bezier issue?)

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#7525]
It's always happening.

savestate(rename jpg to 7z)
after loading the savestate press circle button.
![ppsspp_state](https://cloud.githubusercontent.com/assets/3481559/6363643/cc9f4aa2-bcd6-11e4-94bf-7300c0edbf8c.jpg)

PPSSPP
![01](https://cloud.githubusercontent.com/assets/3481559/6363285/e58f0318-bcd1-11e4-9fb1-dfa319535acb.png)

PSP
![201502071625_002](https://cloud.githubusercontent.com/assets/3481559/6363287/eb0701f6-bcd1-11e4-91a3-433a61b68b8d.png)

GE debugger
![03](https://cloud.githubusercontent.com/assets/3481559/6363300/08009358-bcd2-11e4-933b-af4b4c9ecadb.png)
more tabs
https://gist.github.com/daniel229/913e8052f26d2814d7ec

**Comment by daniel229** [comment]
Spline/Bezier curves quality  Medium seems work fine.
![04](https://cloud.githubusercontent.com/assets/3481559/6363506/480f6aca-bcd5-11e4-94ad-1f45ab626cbe.png)

**Comment by unknownbrackets** [comment]
The texture is a render-to-texture, and it looks like it's mostly/fully transparent.  It's 8888 though, so I suppose #7509 won't likely help here...

Anyway, since it's modulate, it's weird that alpha is becoming anything but zero (unless it's not actually 0, just close, in the texture.)  It is using standard alpha blending, no logic ops or anything either.

So, I guess this may be somehow the reverse of the FF4 save bug: we're accumulating too much alpha?

-[Unknown]

**Comment by daniel229** [comment]
https://github.com/hrydgard/ppsspp/pull/7509 won't help.

**Comment by unknownbrackets** [comment]
So, here in GPU/Common/SplineCommon.cpp:
```c++
			if (origVertType & GE_VTYPE_COL_MASK) {
				patch.sampleColor(u, v, vert.color);
			} else {
				memcpy(vert.color, patch.points[0]->color, 4);
			}
```

If you add after:
```c++
vert.color[3] = 0;
```

Does it fix/affect it?  The control points do have colors...

-[Unknown]

**Comment by daniel229** [comment]
Bezier effect is missing.
![01](https://cloud.githubusercontent.com/assets/3481559/6425398/dc55d622-bf61-11e4-9af2-c741ccb131e2.png)

**Comment by unknownbrackets** [comment]
Okay.  What if you change it from 0 to like 0x80 or 0x40?

-[Unknown]

**Comment by daniel229** [comment]
0x80 get a little effect.
![02](https://cloud.githubusercontent.com/assets/3481559/6425470/ef866a06-bf64-11e4-934e-e430c8714e03.png)

0x40 even smaller
![03](https://cloud.githubusercontent.com/assets/3481559/6425471/f3d09730-bf64-11e4-8346-758b77ac2583.png)

**Comment by unknownbrackets** [comment]
Interesting, but none of them have any of the blue.  What if you make it 0xC0 or 0xE0?

-[Unknown]

**Comment by daniel229** [comment]
0xC0 or 0xE0 seems better.
0xC0
![04](https://cloud.githubusercontent.com/assets/3481559/6425509/417f7440-bf67-11e4-86d3-de87dc1f3550.png)

0xE0
![05](https://cloud.githubusercontent.com/assets/3481559/6425510/478b71d6-bf67-11e4-855a-4f1af20b1048.png)

**Comment by unknownbrackets** [comment]
Still no blue.  It's just a color, is it blue at 0xFF?  Or 0xF7?  When does the blue start?

-[Unknown]

**Comment by daniel229** [comment]
It's hard to tell at which start
0xFF
![ff](https://cloud.githubusercontent.com/assets/3481559/6425553/2d3dc304-bf69-11e4-8c25-24da4c2fa776.png)

0xFC
![fc](https://cloud.githubusercontent.com/assets/3481559/6425556/5e7a4942-bf69-11e4-8023-30f7a64d5980.png)

0xF7
![f7](https://cloud.githubusercontent.com/assets/3481559/6425557/6c07c6b6-bf69-11e4-8c29-852a4a4d2f97.png)

**Comment by unknownbrackets** [comment]
Okay, well, it seems to me like C0 or E0 is more correct looking anyway.  So sounds like we are getting some of the points' alpha wrong?

-[Unknown]

**Comment by daniel229** [comment]
A0 looks pretty match.
![a0](https://cloud.githubusercontent.com/assets/3481559/6425756/098bd6d8-bf75-11e4-86b1-853f88b0f53b.png)

PSP
![201502071625_002](https://cloud.githubusercontent.com/assets/3481559/6363287/eb0701f6-bcd1-11e4-91a3-433a61b68b8d.png)

**Comment by unknownbrackets** [comment]
So, then, if you log it instead of changing it, what values does it have?

-[Unknown]

**Comment by daniel229** [comment]
use many values
https://gist.githubusercontent.com/daniel229/273c3b62b526e88f2592/raw/srwz%20bezier

**Comment by unknownbrackets** [comment]
It probably won't, but this is something I messed with a little and haven't really tested properly:
https://github.com/hrydgard/ppsspp/compare/hrydgard:master...unknownbrackets:bezier-minor?expand=1

Does that make any impact?  It might retain better precision, but probably not much.

I wonder if the issue is that bilinear is not actually good enough?

-[Unknown]

**Comment by daniel229** [comment]
Seems not change anything

**Comment by daniel229** [comment]
So the 0xFF make the blue thing,and other value make the effect stronger than the one on PSP.

**Comment by hrydgard** [comment]
Yeah, it could be that we have to spline-interpolate the colors as well .. I don't know if the PSP does that or if it does them with bilinear interpolation. If so, that's annoying of a game to rely on it and not just look a tiny bit worse :P

**Comment by unknownbrackets** [comment]
When you say spline interpolate, do you mean like with positions - would that be a "4d" bernstein?

Maybe we only do it for "high" quality?

-[Unknown]

**Comment by hrydgard** [comment]
Well, 4x 1-d bernsteins, one for each color component.

**Comment by unknownbrackets** [comment]
Hmm, it'd still be of degree 3, right?  Meaning it'd still go from 0 to tess_u/tess_v.  Sorry I don't really understand this bernstein stuff well.

It seems like I'd pass in a Vec4f of the color, with the same 16 points, but their colors.  No need for derivatives, since I'm not computing a normal.  Or do you mean a bernstein between the control points, rather than lerp?

If it's true that colors are spline-interpolated, I wonder if UVs could be too.  Of course could be neither.

I wonder if there's a sane way for me to construct a test that would tell me... hmm.

-[Unknown]

**Comment by hrydgard** [comment]
Same degree, just one more component (color is RGBA, position is XYZ). And yeah, most likely the UVs are too.

I think just drawing a 4x4 patch with a high tesselation factor, and where the control points are positioned a bit irregularly and colored differently, would do as a test - image compares should make a difference visible.

**Comment by daniel229** [comment]
Since https://github.com/hrydgard/ppsspp/pull/8259 ,now is black,and there is a frame is not correct.

![01](https://cloud.githubusercontent.com/assets/3481559/12019593/fd248684-adac-11e5-9c08-eecd20d14e18.png)

![ppssppwindows64 2015-12-28 21-43-57-285 mp4_20151228_214611 796](https://cloud.githubusercontent.com/assets/3481559/12019594/fd2e11ea-adac-11e5-9329-512008ad6a79.png)

the video rename jpg to mp4.
![ppssppwindows64 2015-12-28 21-43-57-285](https://cloud.githubusercontent.com/assets/3481559/12019614/55f09b72-adad-11e5-91ee-8b48556ae1f9.jpg)

**Comment by unknownbrackets** [comment]
If you comment out this part, the black goes away?

https://github.com/hrydgard/ppsspp/pull/8259/files#diff-5b998bdeb6be184246bb712047ce81f7R540

If so, can you revert that, and then change this part here:
https://github.com/hrydgard/ppsspp/pull/8259/files#diff-29313f9f6ed28d0e24e6dac4e0db8933R1378
```c++
				glCopyImageSubData(
					fbo_get_color_texture(src->fbo), GL_TEXTURE_2D, 0, srcX1, srcY1, 0,
					fbo_get_color_texture(dst->fbo), GL_TEXTURE_2D, 0, dstX1, dstY1, 0,
					dstX2 - dstX1, dstY2 - dstY1, 1);
				return;
```

To:

```c++
				glGetError();
				NOTICE_LOG(HLE, "src %d,%d -> dst %d,%d  %dx%d", srcX1, srcY1, dstX1, dstY1, dstX2 - dstX1, dstY2 - dstY1);
				glCopyImageSubData(
					fbo_get_color_texture(src->fbo), GL_TEXTURE_2D, 0, srcX1, srcY1, 0,
					fbo_get_color_texture(dst->fbo), GL_TEXTURE_2D, 0, dstX1, dstY1, 0,
					dstX2 - dstX1, dstY2 - dstY1, 1);
				NOTICE_LOG(HLE, "glCopyImageSubData: %08x", glGetError());
				return;
```

I'm assuming the black means the copy is failing for some reason.

-[Unknown]

**Comment by unknownbrackets** [comment]
Oh, maybe try changing:

```c++
if (dstX2 - dstX1 == srcX2 - srcX1 && dstY2 - dstY1 == srcY2 - srcY1) {
````

To:

```c++
if (dstX2 - dstX1 == srcX2 - srcX1 && dstY2 - dstY1 == srcY2 - srcY1 && dst != src) {
````

Although, I thought I accounted for that already somewhere...

-[Unknown]

**Comment by daniel229** [comment]
Revert that part help.but I don't get any NOTICE_LOG in game.

Restore the revert,and then follow the change above does not help it.

**Comment by unknownbrackets** [comment]
How about around the `glCopyImageSubDataNV(` one instead?

-[Unknown]

**Comment by daniel229** [comment]
Still don't get any NOTICE_LOG

**Comment by daniel229** [comment]
I think you mean not commet out https://github.com/hrydgard/ppsspp/pull/8259/files#diff-5b998bdeb6be184246bb712047ce81f7R540
then I get this 
```
20:45:230 user_main    N[HLE]: GLES\Framebuffer.cpp:1391 src 0,0 -> dst 0,0  2048x1088
20:45:230 user_main    N[HLE]: GLES\Framebuffer.cpp:1396 glCopyImageSubData: 00000501
```

**Comment by unknownbrackets** [comment]
Ah, yes, sorry for being unclear.  Hmm, GL_INVALID_VALUE... this is at 4x, right?  Maybe the buffer is correctly 480x272, not 512x272.

Seems like glBlitFramebuffer doesn't range check.

So maybe replace:
```c++
		// Only if it's the same size.
		if (dstX2 - dstX1 == srcX2 - srcX1 && dstY2 - dstY1 == srcY2 - srcY1) {
```

With:

```c++
		// Only if it's the same size and inside the bounds.
		bool sameSize = dstX2 - dstX1 == srcX2 - srcX1 && dstY2 - dstY1 == srcY2 - srcY1;
		bool insideBounds = dstX2 <= dst->renderWidth && dstY2 <= dst->renderHeight && srcX2 <= src->renderWidth && srcY2 <= src->renderHeight;
		bool differentTargets = dst->fbo != src->fbo;
		if (sameSize && insideBounds && differentTargets) {
```

-[Unknown]

**Comment by daniel229** [comment]
Yeah,taht works for it.

**Comment by unknownbrackets** [comment]
It looks like they are spline interpolated - or, at the very least, trilinear or something.

For example, if I make the control points like this (I'm testing with flat shading, 0 = red, 9 = blue, just approximations):

```
CNTRL       PSP         PPSSPP
0000        0000        0000
9999   ->   5555   vs   7777
9999        8888        9999
9999        9999        9999
```

This is with neatly aligned control points in a grid (evenly spaced.)  It's more pronounced if only the top left value is red.

By the way, I'm seeing other issues.  For example, we should support divisions of 1 or 2, but seem to assume < 4 means 4.

-[Unknown]
