### ISSUE TITLE
Something is wrong with texture scaling(huge fps drop)

### ISSUE THREAD

**Issue by vsub** [hrydgard/ppsspp#7526]
I remember seeing some problem with it long time ago and that's why I never used it but now I need to use it(all textures looks bad at 1920x1080 if I don't use texture scaling)

There are probably other games affected by it but for now I notest it only on the both Star Ocean games.

1.Start either of those games
2.Set the Texture Scaling to any option other than off(on auto happens less often)
3.Try opening the menu(triangle)...try few times if the problem is not triggered

When the problem is not triggered,I have above 1300fps and when the problem is triggered,the speed drops by 100 times(all the way down to 13fps)

I'm using 1.0-75 x86 but I also tried the latest 1.0-105 x86

Edit:The problem seems to be really old...it started somewhere between
ppsspp-v0.9.8-1180-g5f6c083 - work fine
ppsspp-v0.9.8-1196-g59bef47 - huge fps drop in menus

**Comment by DeathOnADinosaur** [comment]
I'm having the same problem as it is. I'm running the nest version by the way. I can run at full settings all the way up to 10x resolution with no problem at all, even with texture filtering...that is until I enter the menu, where everything then goes to levels of slowness I've never experienced in a game. Menus seem to be a common issues with a lot of game. Xenosaga III on PCSX2 comes to mind.
