### ISSUE TITLE
MP3 playback problems in the game Bakemonogatari (NPJH50605)

### ISSUE THREAD

**Issue by kirous** [hrydgard/ppsspp#7529]
In version 1.0 and version 1.0.1 this is displayed in the "Debug Console":

![bakemono-error](https://cloud.githubusercontent.com/assets/5083411/6407405/991ba8dc-be0d-11e4-8363-7a1761c3eb6a.jpg)

![bakemono-error1](https://cloud.githubusercontent.com/assets/5083411/6407418/a7e07cf8-be0d-11e4-8def-af03e2d88ccc.jpg)

Browsing and playing, it goes infinite times.

Sometimes it disappears some graphics, as also the sound, but it is playable.

In version BUILD V1.0-107. It seems that this improved. But even still with this infinite LOOP.

I remember I was so few games. But with newer versions have improved greatly.

Hopefully they can fix this problem.

Note: Do not forget also the ISSUES # 7489, which is still no improvement.... Sorry my bad English XD !!

**Comment by sum2012** [comment]
There is no improve in scemp3 in a long time

**Comment by benderscruffy** [comment]
i have tested this on my psp and here is a jpcsp trace and ppsspp log
same on hardware and ppsspp
[jpcsp trace and ppsspp log.zip](https://github.com/hrydgard/ppsspp/files/530731/jpcsp.trace.and.ppsspp.log.zip)

**Comment by unknownbrackets** [comment]
Does this game give you a way to actually play MP3s?  Maybe as custom background music?

That jpcsptrace and log indicate that it isn't even trying to play an mp3 - it just has a thread waiting to see if there's an mp3 to play.  It's causing an error to be continuously logged, but it doesn't seem to actually try to play anything in either of those logs.

-[Unknown]
