### ISSUE TITLE
Keyboard menu controls broken on linux build directional movement is too fast

### ISSUE THREAD

**Issue by gusthe** [hrydgard/ppsspp#7531]
When navigating the main menu the directional keys are too fast. If I have recent tab highlighted on the top left of the main menu and I tap the right arrow key as quickly as I can it moves all the way to the right and highlights settings. It makes navigating the menus impossible with the keyboard.

I've narrowed the problem down to four commits. Three of them fail to build for me so I don't know if it's one of them, but the commit that was before them is fine and the commit after them is broken.

https://github.com/hrydgard/ppsspp/commit/4eed560e786324d0b0349f089f6b1b0544c5cf26
https://github.com/hrydgard/ppsspp/commit/2feae8d98e87b467c9e584117ae3713fbff4b1ac
https://github.com/hrydgard/ppsspp/commit/5c7f3b6995e3fc4693f6d21ab2e5f2eee1455197

Commit that comes after them that is broken.
https://github.com/hrydgard/ppsspp/commit/adef4c3b70f66f6419bc9c4a6cf5235e9b55f39b

**Comment by hrydgard** [comment]
Most likely the first one, the switch to SDL2. What platform/OS are you running on?

**Comment by gusthe** [comment]
Ubuntu 14.10 x64

**Comment by Pulfer** [comment]
I confirm this issue with ROSA 2014.1 i586 SDL2 build too.

**Comment by hrydgard** [comment]
As investigated in #7404, the likely cause is that PPSSPP is running at 1000+ fps in the menu instead of the intended 60 fps. Is vertical sync not working?

**Comment by Pulfer** [comment]
Vertical sync was turned off in driver settings. Turning it on fixes the issue. Perhaps it's better to force 60 fps in PPSSPP when vsync is off?

**Comment by hrydgard** [comment]
Yeah, I guess we should, or alternatively base the keyboard event timing on the clock instead of counting frames.

**Comment by hrydgard** [comment]
That should take care of it. If you find more things that run fast, open new issues.

Still rendering excessive amounts of frames, but that's just what you get if you disable vsync in the driver...

**Comment by Pulfer** [comment]
Fixed indeed, thanx :-)
