### ISSUE TITLE
Quicksave picture broken

### ISSUE THREAD

**Issue by StraightEdge** [hrydgard/ppsspp#7532]
I downloaded ppsspp-qt from a PPA on Ubuntu 14.10 64bit, and when I quicksave the game the picture of the game is all messy, I tried with FF I and FF II. 

Menu:
![n9u2cxq](https://cloud.githubusercontent.com/assets/1984423/6419053/6ba09cd4-beba-11e4-8f20-77beb3ebf3b1.png)
![0fjxmfu](https://cloud.githubusercontent.com/assets/1984423/6419054/6bb7c6d4-beba-11e4-9ad7-df802f016993.png)

Pictures in directory:
![ules00986_1 00_0](https://cloud.githubusercontent.com/assets/1984423/6419072/8d634600-beba-11e4-856e-742985e8950e.jpg)
![ules00987_1 00_0](https://cloud.githubusercontent.com/assets/1984423/6419073/8d65c4f2-beba-11e4-9738-94784c17cab0.jpg)

**Comment by hrydgard** [comment]
Huh, looks like RGB/RGBA confusion of some sort..

**Comment by unknownbrackets** [comment]
Someone needs to implement it still for Qt:
https://github.com/hrydgard/ppsspp/blob/master/Core/Screenshot.cpp#L237

I don't exactly know why it needs to be different on Qt, I guess some problem with libpng libraries or something.

-[Unknown]

**Comment by Pulfer** [comment]
> I don't exactly know why it needs to be different on Qt, I guess some problem with libpng 
> libraries or something.

Perhaps less low-level code, less build time, less dependencies. I just checked, Qt UI works fine with non-Qt screenshots code too.

As for the issue itself, the buffer wasn't converted to 888RGB with ConvertBufferTo888RGB (see https://github.com/hrydgard/ppsspp/blob/master/Core/Screenshot.cpp#L248 ), so creating 888RGB QImage was wrong.
