### ISSUE TITLE
Dengeki no Pilot: Tenkuu no Kizuna video flickering

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#7549]
Since https://github.com/hrydgard/ppsspp/pull/6100 ,reverted works fine.Revert that will break Bleach heat of soul 6

**Comment by hrydgard** [comment]
Okay, so we need to find a third way, or the timing is screwed up by some other bug..  nasty stuff.

**Comment by sum2012** [comment]
Anyway,this is v1.0.1-98-g98d7afa debug log
https://gist.github.com/sum2012/2ab93582a379d2f7a53f

**Comment by sum2012** [comment]
JPCSP r3711 also has the same flickering issue
