### ISSUE TITLE
Yu Gi Oh GX / Blazblue Broken font

### ISSUE THREAD

**Issue by NekoArcueid** [hrydgard/ppsspp#7550]
the font gets to big in yu gi oh and sometimes end out of the screen, also blazblue has same issue with the plus of many missing characters on screen

**Comment by Warriors-Blade** [comment]
Have you tried using the official PSP fonts?

That should fix any of those kinds of issues.

**Comment by NekoArcueid** [comment]
where i need to put them? and which format they're supposed to have? I get a bunch of *.pgf fonts

**Comment by Warriors-Blade** [comment]
You can get it off of your actual PSP or by doing a search, they are in .pgf format.

The reason they are not included is the official font is copyrighted they the PPSSPP team had to improvise , too bad most games kind of need the official fonts .

**Comment by NekoArcueid** [comment]
ohh I see, in android is the same?

**Comment by Warriors-Blade** [comment]
Here is where you can get the font ,

http://emulation-general.wikia.com/wiki/PPSSPP

Not sure if posting that is against any rules.

**Comment by unknownbrackets** [comment]
Closing this as a duplicate of #2788.

-[Unknown]
