### ISSUE TITLE
Agarest Senki Mariage Directx 9 graphic problem in the map

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#7555]
Load the save
https://drive.google.com/file/d/0B3OaSdeV0L8kZnpxOHA4N01SR28/view?usp=sharing

Directx 9
![1](https://cloud.githubusercontent.com/assets/2177532/6483617/f54f803e-c2ad-11e4-9c52-b75dc5561c18.jpg)

![1](https://cloud.githubusercontent.com/assets/2177532/6483619/faaf9730-c2ad-11e4-9489-6621711a7930.png)

OpenGL.
![2](https://cloud.githubusercontent.com/assets/2177532/6483620/fe9a0c2c-c2ad-11e4-8cc0-8536d88e340d.jpg)

**Comment by unknownbrackets** [comment]
Can you find the GE debugger pane when it's drawing the black bar?

But I suspect this is related to dual source alpha not being a thing on Direct3D 9.

-[Unknown]

**Comment by sum2012** [comment]
Test v1.1.1-440-g7eb662f fixed
