### ISSUE TITLE
No Graphics Output for all games on Android TV Box with Mali GPU from v1.0.1-97-g3e1e8f1 onward.

### ISSUE THREAD

**Issue by tabnk** [hrydgard/ppsspp#7559]
It's was fine on v1.0.1-12-gd990221 but problem arise from v1.0.1-97-g3e1e8f1 onward. Even latest version too v1.0.1-104-g3e272e4 for all games. Sound is ok. All Default Setting.

Windows Version is ok.

**Comment by unknownbrackets** [comment]
Most likely acdd0807f55128471007f9960cff4f1a718a0a22.

-[Unknown]

**Comment by tabnk** [comment]
I'm will try v1.0.1-93-gc0450f7 (1 version before 24-bit Z on mali) now, let's see if that is the case.

**Comment by tabnk** [comment]
Indeed, v1.0.1-93-gc0450f7 is fine. Any versions above will not have Graphics Output.

**Comment by hrydgard** [comment]
OK, will revert. It did not seem to have any benefit anyway.

**Comment by Mullin** [comment]
@tabnk : Which games ? I've no problems with mali400MP with this build and MHF3rd HD.

**Comment by tabnk** [comment]
FD Type 0, Tekken, Outrun, etc. My is Mali-T764. 

You try the latest v1.0.1.104 ?

**Comment by Mullin** [comment]
Mali-T764 ? Which mean the 24 bits Z buffer is not used in Mali400MP. So maybe this is why there is glitch in MHUF(16 bits Z buffer)

**Comment by tabnk** [comment]
Mali-T760 with 4 Core. Not sure about 24 bit Z buffer things. Maybe Dev can explain ?

**Comment by Mullin** [comment]
@tabnk I talking to myself ^^ @hrydgard @unknownbrackets : Somes informations here :)

**Comment by sum2012** [comment]
@Mullin 
Remember to re-test in\after v1.0.1-117-gc991dd7 as it fix important bug

**Comment by Mullin** [comment]
@sum2012 Okay @tabnk @hrydgard @unknownbrackets : Post updated.

**Comment by tabnk** [comment]
So 24-bit Z buffer fix Mali-400MP issue but also create new issue for Mali-T760 ?

**Comment by unknownbrackets** [comment]
Tekken 6 has some loop or something that checks the cpu speed.  It won't work unless you use the default.

-[Unknown]

**Comment by tabnk** [comment]
Tired v1.0.1-118-gc3f38f3 but same issue as before no graphic output even at 1x PSP.

**Comment by Mullin** [comment]
@unknownbrackets : Yeah i know this issue, tested with 333. @tabnk : No that's fix nothing but show the Mali400MP don't use 24 bits Z Buffer.

**Comment by brujo5** [comment]
some user report that for Dissidia 012: Duodecim Final Fantasy 

Adreno 330 gpu is affected to.

stuck on title screen on latest build v1.0.1-104, the menu disappeared
my device is lg nexus 4 adreno 320 gpu
the problem 1st appeared in build v1.0.1-97-g3e1e8f1

**Comment by LunaMoo** [comment]
@brujo5 unless there was a different problem on android - Dissidia problem was related to #7561 and already fixed in v1.0.1-117-gc991dd7, so just update.

**Comment by brujo5** [comment]
@LunaMoo 

Thanks for notifying me.

**Comment by sum2012** [comment]
@hrydgard I think it is the time to 
revert the change

**Comment by tabnk** [comment]
Yeah, time to revert back the change. :),

**Comment by unknownbrackets** [comment]
The change has actually already been reverted.

-[Unknown]

**Comment by tabnk** [comment]
Thank, tested ok too.
