### ISSUE TITLE
Neverland:The Nalulu KingDom Stories black screen on boot up

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#7561]
Since https://github.com/hrydgard/ppsspp/pull/7548 ,the demo is fine though.
Another game broken is Dissidia duodecim final fantasy,hang in intro

debug log(rename jpg to txt)
![ppsspplog](https://cloud.githubusercontent.com/assets/3481559/6504344/16e0ea8a-c371-11e4-99c0-197bef97eef1.jpg)

**Comment by unknownbrackets** [comment]
I think this was caused by a copy/paste mistake.  Does it work in c991dd7?

-[Unknown]

**Comment by daniel229** [comment]
Yeah,fixed.
