### ISSUE TITLE
PPSSPP won't start on winXP, build v1.0.1-114-g3df63fd-windows-x86

### ISSUE THREAD

**Issue by zackdreaver** [hrydgard/ppsspp#7562]
@hrydgard
![new picture](https://cloud.githubusercontent.com/assets/10024221/6505191/18ac4764-c372-11e4-8ba8-351d51e73f28.jpg)

**Comment by Bigpet** [comment]
you sure it's not v1.0.1-110-g45d8f02 ? because I don't think 114 is at fault here

**Comment by zackdreaver** [comment]
dunno sir, i just tried the latest build :)
