### ISSUE TITLE
Darkstalkers the chaos tower on Android only works with read framebuffer to cpu\gpu VERY slow

### ISSUE THREAD

**Issue by Solstar** [hrydgard/ppsspp#7564]
i have an nvidia shield,and 90% of psp games runs at basically full speed.i tried darkstalkers since last yera,for many ppsspp versions for android,and they all have same issue.basically with non-buffered rendering and buffered rendering the game loads up fine up to the character select screen.after that you can't see anything.you will still hear the sounds and music of the game,even choosing a character etc but the screen will stay stuck at the opening sequence of the char screen.

by setting it to read framebuffer to cpu\gpu it works as in"you can see what you're doing",but its insanely slow,even with audi and other things turned off.its been like this for months,but still no solution on new (nightly)ppsspp versions.any help?

**Comment by daniel229** [comment]
An old issue here https://github.com/hrydgard/ppsspp/issues/6647

**Comment by Solstar** [comment]
Ciao amico,

Mi sono improvvisamente  imbattuto  in un  articolo interessante, è incredibile! ti prego  di leggere qui  e dirmi cosa ne pensi <http://dario.roastreport.com/qny>

Saluti, LESSNDRO PERRICONE
