### ISSUE TITLE
[Feature Request] OpenGL 3.3 core profile support on AMD open source driver?

### ISSUE THREAD

**Issue by Joelgp83** [hrydgard/ppsspp#7570]
Ok, so recently I've been running PPSSP's linux version, on the AMD open source driver on Linux Mint 17.1.  The proprietary driver screws up my hdtv's resolution support something fierce, so I don't use that.

For the most part, it works fine, except the current profile is apparantly a compatibility context which limits us to Opengl 3.0 and shading language 1.30 support, as seen here:
![gallium info](https://cloud.githubusercontent.com/assets/7368696/6545042/a02b64aa-c524-11e4-95d2-8bf366d01037.png)

This prevents us from using stuff like Asmodean's shaders that are in the custom ppsspp shaders thread:
![glsl error](https://cloud.githubusercontent.com/assets/7368696/6545045/d64e9598-c524-11e4-81ce-980455a9cb09.png)

Anyway, in searching for a non-proprietary driver solution, I came across this thread, whereupon they seem to be managing to initialize the open source driver with full OpenGL 3.3 and shading language 1.50 support:  https://github.com/RobertBeckebans/RBDOOM-3-BFG/issues/137

I don't know if what they did is trivial enough to be adapted to PPSSPP for linux' case easily, but I would think that getting a little more power out of the same driver might be something you guys would be interested in.

**Comment by hrydgard** [comment]
I have been working on using the Core context on MacOSX, where it's also the only option if you want OpenGL beyond 3.0. About half-done but needs some more work, and now I managed to distract myself with the ARM64 JIT :) But it will happen, and the work should just transfer over fairly easily with a few checks.

**Comment by Joelgp83** [comment]
Very cool to hear you're already working on it.  I look forward to that. :)

**Comment by Joelgp83** [comment]
Curious.  Just tested Asmodean's shaders on my Samsung Galaxy Avant (Quad-core S4 chip/1.5GB RAM/Adreno 305 GPU / 4.4.2 Kitkat / OGL ES 3.00), and it errors out too, though it mentions something about OGL ES not supporting a #version declaration in the shader, period.  Not sure if that's supposed to happen, or if I just need to change it.

For what its worth, in that other thread I linked, in this post here https://github.com/RobertBeckebans/RBDOOM-3-BFG/issues/137#issuecomment-52644389

He mentions the existing GLSL 1.5 can/did compile under I would assume is whatever standard OpenGL ES shader language is (1.00?) as is, but again, that's a different game engine, and I don't know if that's a tweak that needs to be made to the shader itself to specify which SL is being used.

**Comment by unknownbrackets** [comment]
I'm going to close this in favor of #8277, even though technically #8277 is the duplicate.  There were some roadblocks in the effort before, and the new issue references the new effort (which is also hitting some roadblocks.)

-[Unknown]
