### ISSUE TITLE
Size mismatch error

### ISSUE THREAD

**Issue by gitbest** [hrydgard/ppsspp#7572]
Hello, I keep receiving the size mismatch error while downloading I think it's because the size is different from what is shown. Pls try to fix it thanks. I love your work

**Comment by Bigpet** [comment]
downloading what?

**Comment by gitbest** [comment]
I was downloading ppsspp v1.0.1 from ppsspp repo in cydia for iOS

**Comment by brujo5** [comment]
i have installed dev latest withou problems

**Comment by gitbest** [comment]
Thanks but how do I install those deb files is it with cydia or normal browsing. I clicked it but nothing seems to show or do you think it's my network

**Comment by gitbest** [comment]
What's the size of your ppsspp dev latest?

**Comment by brujo5** [comment]
10.1 mb

**Comment by gitbest** [comment]
Thanks for help. I have downloaded the deb file

**Comment by unknownbrackets** [comment]
This sounds like something that isn't an issue with PPSSPP.  Might be better to take this to the forum.

-[Unknown]
