### ISSUE TITLE
Atari 800 emulator freezes every 1 second on Android and PC

### ISSUE THREAD

**Issue by Elwood89** [hrydgard/ppsspp#7575]
The atari 800 emulator:
http://psp.akop.org/atari800
download here: http://psp.akop.org/atari800/download/2.1.0.1/1.00

Is running, but it seems to choke ~every second - goes about 1 sec fullspeed, and then locks up for another 1 sec on Android (tested on Xperia Play and a LG G3) as well as the PC build (latest git version).

The slowest/ most active syscall is: sceGeListUpdateStallAddr, which takes ~0.90 ms to complete when it's frozen (on PC, similar on adroid).

The reasons I'm asking about this at all are:
1. Although there IS a free android atari 800 emu, this one seems to actually run better than the native one, even on the xplay! When it's not freezing of course.
2. There is no atari 800 emulator on IOS, and this could serve as a very good alternative.

What do you think? And how can I help track the problem?

**Comment by LunaMoo** [comment]
This was another homebrew affected by time mismatch fixed recently, closing.
