### ISSUE TITLE
Star Ocean First Departure sprite overlaping backgrounds and other various bugs

### ISSUE THREAD

**Issue by Warriors-Blade** [hrydgard/ppsspp#7577]
Seems Star Ocean First Departure has a way to go still, Iv encountered various bugs through many builds and they have yet to be fixed.

 Sprites overlapping the backgrounds in OpenGL , there seems to be no fix for this yet.

 Going into the in game menu in OpenGL will cause extreme lag (somewhat random)

 Black flickering the the background moves in Direct3D, just noticed that one while tinkering around.

Got any insight on this issues?

**Comment by vsub** [comment]
The extreme lag in game menus is cause by Texture Scaling
https://github.com/hrydgard/ppsspp/issues/7526

Where exactly do you get those overlapping backgrounds?
What video card do you have?

**Comment by Warriors-Blade** [comment]
Well that is strange, would be nice if it gets fixed.

Well I ran Star Ocean FD on a few computers and they all have the same result, currently I'm on my laptop which uses intel chip set, my desktop has a radeon .

The sprites are above the backgrounds in opengl, just tried direct3d and its normal but way too much black screen flickering when the background scales .

I am still new to the bug reporting thing , sorry for any confusion.

**Comment by unknownbrackets** [comment]
Closing this in favor of #8244.  We don't need two issues open about the same thing.

-[Unknown]
