### ISSUE TITLE
Yu-Gi-Oh! GX Tag Force 1 Freezing after exiting card shop and graphical errors

### ISSUE THREAD

**Issue by Warriors-Blade** [hrydgard/ppsspp#7578]
When you buy a certain amount of cards in the card shop then exit the shop it will go to the card pack opening screen then it will show you your total lot of obtained cards and once you exit that the emu will lock up then crash, just tested it again and its random but frequent .

I figured the conditions for this second bug, in any Yu-Gi-Oh Tag Force games, if you have Texture Scaling on you will see lines in most of the text boxes, turn it off and the lines are gone, this is for both opengl and direct3d .

**Comment by sum2012** [comment]
let me watch this issue

**Comment by Bigpet** [comment]
@sum2012 you don't need to comment on each issue, that's what this button there is for: 
![image](https://cloud.githubusercontent.com/assets/465677/6641534/a8950e1a-c99e-11e4-8238-7c2f0c639c97.png)

**Comment by sum2012** [comment]
@Warriors-Blade 
Do v1.0.1-180-g9d52ee4 fixed ?
(Sorry,I don't have time to test myself)

**Comment by Warriors-Blade** [comment]
Well I just tested with the latest build and in the card shop I tried the usual of buying a bunch of packs and so far it has not crashed but the lines through the text boxes are still present.

Il test some more and see if it freezes.

**Comment by unknownbrackets** [comment]
The texture scaling issue is probably hard to fix.

I'm going to mark this closed based on the above comment - but if you're seeing it still, feel free to reply and we'll reopen.

-[Unknown]
