### ISSUE TITLE
Diactritic characters are displayed as "?" (Qt frontend)

### ISSUE THREAD

**Issue by akien-mga** [hrydgard/ppsspp#7581]
I've just built PPSSPP 1.0.1 with the Qt frontend, and I realised that diacritic characters (at least French accented characters like "é" and "É") are badly interpreted and displayed as "?" in the UI, see e.g. the message when saving a game state:
![ppsspp-font](https://cloud.githubusercontent.com/assets/4701338/6583060/eab1e456-c761-11e4-9b5f-2a8c04c611dc.jpg)

The corresponding string in lang/fr_FR.ini is:

```
Saved State = État sauvegardé !
```

**Comment by akien-mga** [comment]
I just tested PPSSPP 0.9.9.1, and the same issue appears, so at least it is not a recent regression.

**Comment by unknownbrackets** [comment]
Qt seems to pull the default font (I think?  I don't see where it grabs any specific font), so this might be related to the fonts installed on your system.

https://github.com/hrydgard/native/blob/21b0a2deb940ae2a39961b7b809d22007dbb0e4f/gfx_es2/draw_text.cpp#L232

Ideal would be using Roboto and dynamically falling back to system fonts for characters that are missing (such as kanji, etc.)

-[Unknown]

**Comment by unknownbrackets** [comment]
Want to try your hand at this?  It looks like:

1. Call `QFontDatabase::addApplicationFont()` passing in the path to the `assets/Roboto-Condensed.ttf` file.  I think this is somehow embedded in the Qt exe, so I don't know exactly how that works - maybe `QFontDatabase::addApplicationFontFromData()`.

2. Try loading a QFont with name "Roboto Condensed" as well as "Roboto".  It might be either one.  Even if the load in step 1 fails, it might be a system font.

3. Use that font here: https://github.com/hrydgard/native/blob/21b0a2deb940ae2a39961b7b809d22007dbb0e4f/gfx_es2/draw_text.cpp#L232

Googling tells me that fontconfig should be somehow involved in the fallback, and it sounds like it ought to be automatic.  I'm not really sure.

-[Unknown]

**Comment by unknownbrackets** [comment]
Does this still happen in the latest git?  Now it will use Roboto Condensed like described above.

-[Unknown]

**Comment by akien-mga** [comment]
Thanks, I can confirm it's fixed in the Qt build at 6c494c38.
