### ISSUE TITLE
Final Fantasy IV

### ISSUE THREAD

**Issue by LlamaD** [hrydgard/ppsspp#7583]
During the intro cutscenes of Final Fantasy IV, you see the guy cast the spell "Blue Fang" against Zu. The audio is distorted on the latest version of PPSSPP on my computer when he casts the spell. Just FYI. Don't know if there was a fix. I found that  this version v0.9.9.1-969-g804de50 doesn't distort the audio. Any version number above that, the audio is distorted. I've taken a screenshot, but can't find it.

**Comment by daniel229** [comment]
Set "Spline/Bezier curves quality" to "Medium" can help the speed.

**Comment by LlamaD** [comment]
That works! I'll keep this adjustment in mind anytime I play the early final fantasy games(I-VI). Conisder it resolved. I'm curious if there is a webpage that contain optimal setting for different games. Thank you!

**Comment by hrydgard** [comment]
What you're seeing, I mean hearing, is slowdown. Spline commands at full quality (same amount of triangles as on the PSP) can sometimes generate way more triangles than seems to be needed for things to look good, and that takes CPU power. However I wonder if we really have the rules right, the game looks fine with lower tesselation levels AFAIK...

**Comment by daniel229** [comment]
Medium looks fine in FFIV,but not good in Kenka Bancho.

PSP
![201503140915_001](https://cloud.githubusercontent.com/assets/3481559/6649660/71cefe1c-ca2b-11e4-8bb5-02fe9d646575.png)

High
![02](https://cloud.githubusercontent.com/assets/3481559/6649666/88bf9cb2-ca2b-11e4-9937-7625cbcba131.png)

Medium
![01](https://cloud.githubusercontent.com/assets/3481559/6649665/88b9eb3c-ca2b-11e4-9510-744894ee7c7f.png)
