### ISSUE TITLE
ppsspp multiplayer crash.

### ISSUE THREAD

**Issue by gitbest** [hrydgard/ppsspp#7585]
Hello, i always encounter a problem with ppsspp when i press the multiplayer key when network/WLAN is on, when i press the key,ppsspp crash. I have tried it in all my psp games but none seems to work (pes 2014 smackdown vs raw 2011, obscure the aftermath, splinter cell essentials tekken 6 undead knight) is there a possible solution or i have to configure the network before it wuld work? I use an ipad air and i try to connect to the laptop. The problem only occurs in the ipad air but it does not occur in the laptop.

**Comment by sum2012** [comment]
Try disable fast memory
![1](https://cloud.githubusercontent.com/assets/2177532/6627883/49708e12-c93c-11e4-9fe9-5b8f0df728a1.jpg)

**Comment by gitbest** [comment]
It didnt work, it still the same

**Comment by berk-can** [comment]
@sum2012 you are awesome man, thanks
( But still I can't see opponent on Tekken 6 :( )

**Comment by sum2012** [comment]
Try to set "port offset 15005" on both device

**Comment by berk-can** [comment]
@sum2012 man it was brilliant idea, I couldnt set 15005 but I set 15000 and voila, I am able to play, thank you so much

**Comment by berk-can** [comment]
@gitbest did you tried to enable both checkboxes in Netwoking tab, if you dont, game freezes, 
you can t"Try to set "port offset 15005" on both device" as @sum2012 says, but it is not the solution for freezing it is solution for not freezing but being unable to find other device,
I think that it might be an issue for iOS ?

**Comment by unknownbrackets** [comment]
Has this gotten any better given recent improvements to networking code?  Is it still only iOS?

-[Unknown]

**Comment by ANR2ME** [comment]
From the games mentioned here, i only know that Obscure the aftermath and Tekken 6 have no issue on LAN, at least on Windows & Android, not sure about iOS (never use iOS device)

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
