### ISSUE TITLE
[Ad Hoc] Power Stone Collection not working online

### ISSUE THREAD

**Issue by Warriors-Blade** [hrydgard/ppsspp#7603]
I have tested many games via PPSSPP ad hoc online play and this one seems to be strange since it does not seem to be complicated in that regard but you can not play online/multiplayer with it.

If you try you just hit the lobby and it will be empty so nothing can be done.

If this is not the correct place for Ad Hoc compatibility reporting please let me know.

Edit:  was informed it would be best to include a DebugLog, will attempt to get one and submit it.

**Comment by benderscruffy** [comment]
v1.8.0-2-g7f1e10a93
still happens
12:20:400 netAdhocThre E[HLE]: HLE\HLE.cpp:545 Unimplemented HLE function sceNetFreeThreadinfo
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/2966282/ppsspplog.zip)

**Comment by unknownbrackets** [comment]
Has this gotten better given recent improvements to networking code in PPSSPP?

-[Unknown]

**Comment by ANR2ME** [comment]
Power Stone Collection is working fine on LAN, not sure over the internet tho

**Comment by hrydgard** [comment]
I'm gonna close this anyway, let's open new issues if there's a problem becasue the main issue has been fixed.
