### ISSUE TITLE
Yu-Gi-Oh Tag Force series cut off card art (Issue occurs in the entire series)

### ISSUE THREAD

**Issue by Warriors-Blade** [hrydgard/ppsspp#7604]
I just tested it with the entire Tag Force series and this is a occurring problem, I made sure to make screenshots this time.

This occurs with opengl and direct3d, also reported that it happens on friends computers. 

In game it happens when you summon a card and it does its summon animation.

If any other info is needed please let me know and I will try my best to submit it.

![ygotf screenshot](https://cloud.githubusercontent.com/assets/11386743/6665804/b46fb56e-cbab-11e4-97f3-fe8ccc14d1e4.jpg)
![ygotf screenshot 2](https://cloud.githubusercontent.com/assets/11386743/6665811/c6756c86-cbab-11e4-9035-e9ad162df9e6.jpg)

**Comment by sum2012** [comment]
same with #7501

**Comment by thedax** [comment]
Closing as dupe.
