### ISSUE TITLE
Pangya Issues Again.

### ISSUE THREAD

**Issue by Xaelath** [hrydgard/ppsspp#7605]
After trying the latest git the (X) issues seems to be solved but after few of days playing i tried to finish a match with any character used or settings changed i always ended up stuck. Again.
Still have no idea what caused the problem, also i havent tried the old build i found on forum (that fix the issues) and i might do a test run later.

PPSSPP 1.0.1-159-gdad8f5c

**Comment by Bigpet** [comment]
is this different from https://github.com/hrydgard/ppsspp/issues/6057 and https://github.com/hrydgard/ppsspp/issues/6682 ? If not then please don't open duplicate issues

**Comment by Xaelath** [comment]
sorry i thought i already some search, yes its the same and its still happening. i will move to issues #6057

**Comment by Xaelath** [comment]
Fixes #7605
