### ISSUE TITLE
Tactics ogre stuterring

### ISSUE THREAD

**Issue by 716Girl** [hrydgard/ppsspp#7608]

**Comment by ppmeis** [comment]
@716Girl be more specific please: Game region, platform and device at least.

**Comment by 716Girl** [comment]
@ppmeis ULES01500
I'm playing on PC, everything is fine, but when it's my turn to select an action it's stuterring. I use opengl backend and buffered rendering.

**Comment by DonelBueno** [comment]
Do you have texture scaling turned on?

**Comment by DarkD** [comment]
I can confirm this with more specific details.
No texture scaling, any rendering resolution, no texture filtering, no shader.
When it's your turn and menu with actions and turn order opens fps drops from 60 to around 47(with multi-thread to 52). Same goes for situation where you only placed cursor on any character and turn order is shown or situation where you press Cross button to show tooltip on any tile(though fps drop is bit lower).
Might be low specs though, would be great if someone with PC that runs everything on full-speed can check that out. Mine: AMD Athlon II X4 635 (2.9 GHz, 4 cores), nVidia GeForce GTS 250, 12 GB RAM.

**Comment by ppmeis** [comment]
Tested with latest build. No stuttering at all, even with 10x internal resolution.

**Comment by DarkD** [comment]
v1.0.1-221-g62e621f - don't see any of those fps drops I mentioned in previous message (it was v1.0.1-207-g79fc557).
@716Girl please confirm if issue is also solved for you.

**Comment by DarkD** [comment]
Wrote that it works perfectly and as soon as I wrote it regressed to what it were... Don't know what to think about it. It starts up with no fps drops now, but wait a minute or two and there are the drops.
Aw, hell! Now it doesn't! And previous run it did.
Ah, now it does, a few minutes later.... Leak?
(sorry for the write style)

**Comment by unknownbrackets** [comment]
Not sure what to tell you.  A few things to try:

1. Turn off the vertex cache.
2. Disable "lazy texture hashing."
3. Turn off multithreading.

Does this still have unpredictable speed for you in the latest git build?  Also, I've heard that the Catalyst drivers have a "Catalyst AI" feature that can make PPSSPP perform poorly.

-[Unknown]

**Comment by unknownbrackets** [comment]
No feedback in a while, so closing.  If there's more information, feel free to comment and we'll reopen.

-[Unknown]
