### ISSUE TITLE
pressing two direction button at the same time

### ISSUE THREAD

**Issue by berk-can** [hrydgard/ppsspp#7609]
like i mention i cant do it and it was okay at old versions of ppsspp i cant play tekken please help

**Comment by Bigpet** [comment]
@berk-can which is the last version that it worked correctly for you?

In general I'm not sure what your problem is, you can press for example Down&Left by just using one finger in-between the two buttons. 

If you want to press Up&Down or Left&Right then no you can't but you can't do that on a real PSP either

**Comment by hrydgard** [comment]
Is this using keyboard on PC, touch controls on Android or something else?

**Comment by berk-can** [comment]
sorry for not giving all information, it is on android and i want to press with two fingers and the keys are cross keys i mean not up and down at the same time but left and up or right and down and i know that one finger can press two of them at some angle, but i want to know whether i can do it with to different fingers or not, thank you for answers

**Comment by sum2012** [comment]
Try this modify ppsspp from xiushudongfang
https://drive.google.com/file/d/0B3OaSdeV0L8kdjY3eEhXLTdHQTg/view?usp=sharing

You need change to english lang first.
Then click "CBK" in below picture
![screenshot_2015-03-18-22-27-52](https://cloud.githubusercontent.com/assets/2177532/6710897/a837fd78-cdbe-11e4-98e3-1b3b9b5366e6.jpg)
![screenshot_2015-03-18-22-34-42](https://cloud.githubusercontent.com/assets/2177532/6710968/1edccb5c-cdbf-11e4-9f16-0882b04432c5.jpg)

**Comment by berk-can** [comment]
OK, I will try, thank you so much btw I hope background will not be that hentai picture???

**Comment by sum2012** [comment]
Sorry our chinese people is lazy.
Anyway,You press lowmem_UI.
Then it will turn off that hentai picture

**Comment by RomanVasilov** [comment]
Hello! This modified ppsspp is very usefull, thank you! Can you tell only, where  updated versions of this mod can be taken? PPSSPP now is 1.0.1, but this mod is only 0.9.9.1. Thank you one more time!

**Comment by sum2012** [comment]
I find his version updated a bit (v1.0.1-237)
https://drive.google.com/file/d/0B3OaSdeV0L8kTVQ3TXNYQlpMdHM/view?usp=sharing

**Comment by xiushudongfang** [comment]
I am very sorry for this background .It is only a special build for some people.

**Comment by marvinaragon** [comment]
Como descargo los juegos

**Comment by sum2012** [comment]
@hrydgard 
I think can close this issue as v1.1.1-71-g624d900 has merged it.
