### ISSUE TITLE
iOS build broken - why this happens????

### ISSUE THREAD

**Issue by brujo5** [hrydgard/ppsspp#7611]
Here an example:
Update to ppsspp dev-latest 1.0.1-178 in cydia

![image](https://cloud.githubusercontent.com/assets/4172898/6693291/174ff232-cc8f-11e4-8e01-71884ae8e129.jpg)

But after open ppsspp, on menu show 1.0.1-138 installed

![image](https://cloud.githubusercontent.com/assets/4172898/6693303/3cac7668-cc8f-11e4-9081-b15d790e0cb6.jpg)

this problem has been present for several past updates.

**Comment by eddiebrook** [comment]
I'm having the same problem, and nobody says anything. No love for ios.
some research I think the problem is between 1.0.1-124 and 1.0.1-138. and certainly no builds available. hopefully one of the developers say something !!!

**Comment by brujo5** [comment]
angelXwind: repliied, Should be fixed now — cmake was being weird and trying to compile against iPhoneOS8.1.sdk (should be iPhoneOS8.2.sdk instead)
have to wait a bit, see if it solves

**Comment by brujo5** [comment]
Fixed thx to angelXwind
