### ISSUE TITLE
Dissidia 012 Final Fantasy gets invalid addresses after saving savestate in gateway

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#7612]
Since https://github.com/hrydgard/ppsspp/pull/3989
Go into the gateway,than press F2,it gets invalid addresses,if then load the savestate,if won't get invalid addresses,and F2 agains,it also won't get invalid addresses.

![01](https://cloud.githubusercontent.com/assets/3481559/6700946/aee32210-cd50-11e4-8743-7ae13030e062.png)

debuglog(rename jpg to 7z )
![ppsspplog](https://cloud.githubusercontent.com/assets/3481559/6700951/c4d8d696-cd50-11e4-91e4-fcf7bc743805.jpg)

**Comment by daniel229** [comment]
Reverting clear jit cache in case SAVESTATE_SAVE fixes the issue.

**Comment by unknownbrackets** [comment]
Is there any specific gateway I have to go into or anything?  I tried it just from the beginning and it didn't happen, unless I did it wrong.

I just entered, dismissed the dialog, and the hit F2.  Then I completed the gateway, and got no errors.

-[Unknown]

**Comment by unknownbrackets** [comment]
But, you can try this change, which might be safer at least?  I can't really tell without reproducing it.

```diff
diff --git a/Core/MIPS/JitCommon/JitBlockCache.cpp b/Core/MIPS/JitCommon/JitBloc
index 0843209..e41d186 100644
--- a/Core/MIPS/JitCommon/JitBlockCache.cpp
+++ b/Core/MIPS/JitCommon/JitBlockCache.cpp
@@ -483,12 +483,14 @@ void JitBlockCache::UnlinkBlock(int i) {
       continue;

     const u32 emuhack = GetEmuHackOpForBlock(block_num).encoding;
-    result[block_num] = emuhack;
     // The goal here is to prevent restoring it if it did not match (in case or
-    if (Memory::ReadUnchecked_U32(b.originalAddress) != emuhack)
-      b.originalFirstOpcode = INVALID_ORIGINAL_OP;
-    else
+    if (Memory::ReadUnchecked_U32(b.originalAddress) == emuhack)
+    {
+      result[block_num] = emuhack;
       Memory::Write_Opcode_JIT(b.originalAddress, b.originalFirstOpcode);
+    }
+    else
+      result[block_num] = 0;
   }

   return result;
@@ -502,7 +504,7 @@ void JitBlockCache::RestoreSavedEmuHackOps(std::vector<u32>

   for (int block_num = 0; block_num < num_blocks_; ++block_num) {
     const JitBlock &b = blocks_[block_num];
-    if (b.invalid)
+    if (b.invalid || saved[block_num] == 0)
       continue;

     // Only if we restored it, write it back.
```

Maybe it doesn't happen in the US version...

-[Unknown]

**Comment by daniel229** [comment]
It also happen in the beginning,so it probably not happen in the US version.And that change helps it.
