### ISSUE TITLE
Can not advance to next dialog in "Suzumiya Haruhi Chan no Mahjong"

### ISSUE THREAD

**Issue by jaejunks** [hrydgard/ppsspp#7630]
Host system:

Windows XP SP3 32-bit  

PPSSPP version:

1.0.1  

Description:

In "Suzumiya Haruhi Chan no Mahjong", conversation dialog can no longer be advanced to the next when run under PPSSPP 1.0.1. At most, it can only advance once or twice.  

Reason of submission:

It previously works in PPSSPP version 1.0.  

Current workaround:

Disable the "Enable sound" setting in the "Audio" section, or use PPSSPP version 1.0.

**Comment by daniel229** [comment]
That hang is randomly,and even happen in 0.9.6.
debug log(rename jpg to 7z)
![ppsspplog](https://cloud.githubusercontent.com/assets/3481559/6781209/e53d5a6a-d1a6-11e4-80bb-e724b9411ff6.jpg)

**Comment by daniel229** [comment]
Change I/O method would help it,and HOST method make it hang after loading.
Change CPU clock to 25 would help it.

**Comment by daniel229** [comment]
https://github.com/hrydgard/ppsspp/issues/4626 also would not crash when change cpu clock to 25.

**Comment by jaejunks** [comment]
Thanks for the pointers.

I've set the CPU clock to 66 since it seems to start causing the problem at 100 or higher.

Eabling the Multithread causes the graphics to flicker frequently, which is kind of bad trade off.

**Comment by daniel229** [comment]
ForceMaxEmulatedFPS = 20 also helps it.

**Comment by Panderner** [comment]
Hmm the recent versions of PPSSPP works fine when I advance next dialog in visual novel cutscenes and in game dialogue

**Comment by unknownbrackets** [comment]
Does it work with all IO method settings now?

-[Unknown]

**Comment by Panderner** [comment]
> Does it work with all IO method settings now?
> 
> -[Unknown]

Yes I've tested all I/O method settings and it's working fine

**Comment by unknownbrackets** [comment]
Okay, going to mark this fixed then.  Maybe the async IO changes helped.  Thanks for validating.

-[Unknown]
