### ISSUE TITLE
Mahou Shoujo Madoka Magica Portable: Problem

### ISSUE THREAD

**Issue by latot** [hrydgard/ppsspp#7632]
Hi, i try play this game but the game crash, in some parts are unimplemented functions and the aplication exit with segmentation fault.

Unimplemented functions:

sceIoChangeAsyncPriority
sceMpegAvcCopyYCbCr
sceMpegAvcDecodeFlush
sceMpegAvcInitYCbCr
sceMpegFlushAllStream

Log:

http://www.mediafire.com/download/m8nrn4k7mu8eegq/log

Well i don't know if the unimpl are the cause of the crash, the games crash in the first part of the game in the first chapter.

And when the game start, in the title part i get a black screen few secods.

I use gentoo 64 with ppssppsdl version 1.0.1-221-g62e621f

Thx

**Comment by sum2012** [comment]
Same as #6557
The soluton is set
System->I/O timing method->Host

**Comment by latot** [comment]
thx
