### ISSUE TITLE
List some games got "Error decoding audio" since #6976

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#7633]
Just tested the title.

Aoi Umi no Tristia Portable Nanoca Flanka Hatsumei Koubouki 
Beats
Clannad
CorpseParty
D.C III plus
Disgaea 2
Dungeon Travelers 2 Ouritsu Tokoshan to Manono no Fuuin
Gensou Suikoden 1 & 2
GTA:VCS
Gurumin
hakuoki
Hajime no Ippo Portable
Hanayaka Nari Wa ga Ichizoku
Harukanaru Toki No Naka de Hachiyoushou
Harukanaru Toki no Naka de 5 kazahanaki
Hayarigami 2
Ikki Tousen xross impact
Innocent Life
Kamigami no Itazura
KARAKURI
Kiniro no Corda 2f
Kiniro no Corda 3 series
Korohyou 2
Kyoukaisen-jou no Horizon Portable
Last Escort Club Katze
Little Big Planet
Loco Roco Midnight Carnival
Lost Hero
Musou Orochi 1
Musou Orochi 2sp
Prinny Ore ga Shujinkou de Iinsuka
prinny2
Shin Sangoku Musou: Multi Raid 2
Tenchu 3
Three Kingdom 9
Tokyo Mono Harashi

Antiphona no Seikahime - Tenshi no Score Op.A
Dengeki no Pilot: Tenkuu no Kizuna
Geten no Hana Yume Akari
Gradius Portable
La Pucelle: Ragnarok
Nano Diver
Phantom Kingdom Portable
Planetarian Chiisana Hoshi no Yume Charity Version
Pursuit Force: Extreme Justice
Riviera special edition
Shinigami to Shoujo
SOL Trigger
Star Soldier
Tales of Rebirth
Tenchu Kurenai
The Warriors
Toukiden
Toukiden Kiwami
Twelve Sengoku Fengshenden
Uta no Prince Sama
World Neverland Qukria Kingdom Stories
World Heroes
Tantei Jinguji Saburo Hai to Diamond

**Comment by vnctdj** [comment]
http://report.ppsspp.org/logs/kind/696 ?

**Comment by unknownbrackets** [comment]
The majority of those errors were reported long before that change was merged, though.

-[Unknown]
