### ISSUE TITLE
Warnings when building with clang on OSX

### ISSUE THREAD

**Issue by CarterLi** [hrydgard/ppsspp#7641]
May not be critical, but fixing them will improve code quality and may fix other hidden bugs

* [ppsspp/Core/HLE/HLE.cpp:622:23](https://github.com/hrydgard/ppsspp/blob/master/Core/HLE/HLE.cpp#L622)
```
ppsspp/Core/HLE/HLE.cpp:622:23: warning: format specifies type 'unsigned int' but the
      argument has type 'float' [-Wformat]
                        APPEND_FMT("%08x", PARAMF(regf++));
                        ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
                                    %08f
ppsspp/Core/HLE/HLE.h:86:19: note: expanded from macro 'PARAMF'
#define PARAMF(n) currentMIPS->f[12 + n]
                  ^
ppsspp/Core/HLE/HLE.cpp:569:37: note: expanded from macro 'APPEND_FMT'
                size_t c = snprintf(p, sz - used, __VA_ARGS__); \
```
__Solution__: Change %x to %f

* [ppsspp/Core/HLE/HLE.cpp:661:3](https://github.com/hrydgard/ppsspp/blob/master/Core/HLE/HLE.cpp#L661)
```
ppsspp/Core/HLE/HLE.cpp:661:3: warning: array index 4096 is past the end of the array
      (which contains 4096 elements) [-Warray-bounds]
                formatted_reason[sizeof(formatted_reason)] = '\0';
                ^                ~~~~~~~~~~~~~~~~~~~~~~~~
/Users/litongzhou/Documents/ppsspp/Core/HLE/HLE.cpp:654:2: note: array 'formatted_reason' declared here
        char formatted_reason[4096] = {0};
```
__Solution__: Remove this line, since we have initialized the whole array to zero before. 

* [ppsspp/Core/HLE/sceFont.cpp:942](https://github.com/hrydgard/ppsspp/blob/master/Core/HLE/sceFont.cpp#L942)
* [ppsspp/Core/HLE/sceFont.cpp:950](https://github.com/hrydgard/ppsspp/blob/master/Core/HLE/sceFont.cpp#L950)
* [ppsspp/Core/HLE/sceFont.cpp:1005](https://github.com/hrydgard/ppsspp/blob/master/Core/HLE/sceFont.cpp#L1005)
```
ppsspp/Core/HLE/sceFont.cpp:1005:19: warning: using integer absolute value function 'abs'
      when argument is of floating point type [-Wabsolute-value]
                                float hDist = abs(matchStyle.fontHRes * matchStyle.fontH - hRes * requestedStyle...
                                              ^
ppsspp/Core/HLE/sceFont.cpp:1005:19: note: use function 'std::abs' instead
                                float hDist = abs(matchStyle.fontHRes * matchStyle.fontH - hRes * requestedStyle...
                                              ^~~
                                              std::abs
```
__Solution__: Replace [abs](http://en.cppreference.com/w/c/numeric/math/abs) with overloaded function [std::abs](http://en.cppreference.com/w/cpp/numeric/math/fabs) as compiler suggested or [fabs](http://en.cppreference.com/w/c/numeric/math/fabs) which accept floats

**Comment by unknownbrackets** [comment]
Unfortunately, MSVC does not always null terminate, so removing the line can be tricky.

https://msdn.microsoft.com/en-us/library/1kt27hek.aspx

For these tricky reasons, it's often best to make sure there's a null at the end.

-[Unknown]
