### ISSUE TITLE
Crash: Mind Over Mutant - Eternal Loading Screen

### ISSUE THREAD

**Issue by wendersonp** [hrydgard/ppsspp#7645]
In the game, I'm trying to get back to Wumpa Island, but in the way, the game start a eternal loading, and I can't continue the game. I'm sending a State that you can check the issue and some screenshots of the game and the debug console. Please, check this.

https://drive.google.com/file/d/0B8T8bicNZm_RdWw0OEZUOS0wNTQ/view?usp=sharing
![ulus10377_00000](https://cloud.githubusercontent.com/assets/8678263/6919984/e13f9e32-d791-11e4-99bb-094affe963d6.jpg)
![error ppsspp](https://cloud.githubusercontent.com/assets/8678263/6920007/20334d5a-d792-11e4-960f-564d74f968f9.PNG)
OBS.: This codes in blue are shown when the loading screen appears.
ROM: ULUS10377

**Comment by sum2012** [comment]
v1.0.1-236-g1a384da debug log
https://drive.google.com/file/d/0B3OaSdeV0L8kNVk2Z2ZKXzVPVFk/view?usp=sharing

**Comment by daniel229** [comment]
Simulate UMD delays helps it.

**Comment by Prick1** [comment]
How can I simulate UMD delays?

**Comment by sum2012** [comment]
@Prick1 
System->I/O timing method->Simulate UMD delays 

@unknownbrackets 
v1.0.1-236-g1a384da debug log (simulate UMD delays ,work)
https://drive.google.com/file/d/0B3OaSdeV0L8kTjl2ek1SclBXcG8/view?usp=sharing

**Comment by hrydgard** [comment]
Are there still a lot of games that break when we enable Simulate UMD delays? We might want to consider flipping it on by default and trying to fix the fallout soon, right?

**Comment by daniel229** [comment]
Simulate UMD delays breaks these games which known before.
Radiant mythology2 (hang)
Ghost in the shell (hang)
Race Driver 2006 (hang)
world neverland (slow)

**Comment by Prick1** [comment]
Okay, the game works with Simulate auMD Delays setting, Thanks. Can I close this topic?

**Comment by unknownbrackets** [comment]
The simulate umd delays logic was based on testing, but is not really using anything near accurate logic.  Probably need to simulate actual rotation speed and the distance from the center and whatever.

Generally, I think whenever it helps it either means that timing in general is a problem or specifically IO timing is.  The setting as it is definitely is not perfect.

I suppose it'd probably be best to collect everything that's probably IO timing related into a single issue and close this.

-[Unknown]

**Comment by sum2012** [comment]
I totally forget how to reproduce the problem

**Comment by Gamemulatorer** [comment]
The savestate file from Gdrive can't load and crashing out the emulator using ppsspp latest development apk.

**Comment by ResurrectionRedmi9** [comment]
Cannot reproduce this using the latest git.

**Comment by unknownbrackets** [comment]
I wonder if this is related to the sceKernelVolatileMemTryLock hack, 5705496233d0d0aee5e495f7f3fc02537e7f351f.

That said, if this is working now, I'm going to close.  It could've also been a bad disc.

Confirmed also from reports:
https://report.ppsspp.org/game/ULUS10377_1.01

-[Unknown]

**Comment by Vitor23laser** [comment]
problem screen pink.

**Comment by natureisdead** [comment]
still a problem

changed I\o timings and game stops to run
