### ISSUE TITLE
Do not be improved restart video BLEACH SOUL HEAT 6 after version 0.9.5

### ISSUE THREAD

**Issue by kirous** [hrydgard/ppsspp#7649]
Hi, well, while I put some ISSUES, on that subject. As more and get a new BUILD Officer can always stops working when the game is restarted without being mode gameplay.

In this image the BUG supposedly the game stops working, using the DEBUG CONSOLE PPSSPP which can display looks.

![01](https://cloud.githubusercontent.com/assets/5083411/6971771/85d2a850-d944-11e4-9905-d99e92ed9580.jpg)

In the other image would be version 0.9.5, which this time there was to the game, is still in progress, simultaneously restarting the video input. It is displayed with the PPSSPP DEBUG CONSOLE.

![02](https://cloud.githubusercontent.com/assets/5083411/6971786/a2becaac-d944-11e4-9a14-d390ddb85b17.jpg)

![03](https://cloud.githubusercontent.com/assets/5083411/6971799/b1c3bdb4-d944-11e4-9b3d-a05a5c567557.jpg)

In summary:

In the PPSSPP DEBUG CONSOLE version 1.0.1 and BUILD out this error:

![04 resumen 1 0 1](https://cloud.githubusercontent.com/assets/5083411/6971810/c698999e-d944-11e4-900a-5fbfa953d8bb.jpg)

However, in the PPSSPP DEBUG CONSOLE version 0.9.5, is still ongoing, and no mistake about it:

![05 resumen 9 5 - 1](https://cloud.githubusercontent.com/assets/5083411/6971823/e0e7f240-d944-11e4-9a7f-5ee4c2307cd4.jpg)

![resumen 9 5 - 2](https://cloud.githubusercontent.com/assets/5083411/6971841/06642e94-d945-11e4-910b-b27d1e84ee1e.jpg)

If you arrive on improving that part, it automatically improves in other games, and one of them is the case Game NEED FOR SPEED MOST WANTED 5.0.1.

I've tried to Laptops and PCs, and the error would be the new version (PPSSPP 1.0.1 and later), whereas in version 0.9.5, it works correctly.

Sorry my bad English XD!!

**Comment by sum2012** [comment]
@kirous You turn off fast mempory ,then it would not crash
But of course ,we should fix the real issue (font)

**Comment by sum2012** [comment]
@unknownbrackets @hrydgard 
ppsspp-v1.0.1-236-g1a384da scefont debug log:
https://gist.github.com/sum2012/5d3612f4394cbd3134d3

JPCSP no problem
(3d32d04 version)
scefont debug log:
https://gist.github.com/sum2012/7e663716b22b2cb17411

03:02:967 Main         I[FONT]: HLE\sceFont.cpp:761 sceFontDoneLib(08e06ed0)
03:02:967 Main         I[IO]: HLE\sceIo.cpp:906 stderr: font_error:I, 08c70000

I just think that sceFontDoneLib do something wrong

**Comment by kirous** [comment]
Ok, thanks for the solution when the option "FAST MEMORY" is disabled, most games work properly, hopefully they can improve that option so you do not visualize as unstable.

is activated when the "FAST MEMORY" and try to have the much greater BUG, ​​some code which are not supported are:

57:43:270 Main         I[IO]: HLE\sceIo.cpp:906 stderr: font_error:I, 08c70000

Since using this code searches the file for proper function, if not tend to make a fully Crash game.

As there is also another that performs a search for a file:

56:59:977 Main         W[FONT]: HLE\sceFont.cpp:677 Font file not found: flash0:/font/zh_gb.pgf

Not if these two are important, as there are more errors, as also on sceFontClose or sceFontDoneLib as you say. Well it has to expect that they can solve.

Another thing I want to consult, because in games GOD OF WAR to start the menu after the presentations of the logos, the speed drops game, and when I do a "ESC" with the key and then click 'Continue' or "ESC" (again), the speed of the game menu is improved. And that I'm testing on a PC Core i5 with 8GB RAM and 1GB Radeon Ati video. Why be ?, I think the emulator is a little flawed. Do not know if will be able to improve the error.

Ah !! and JPCSP emulator is only for powerful PC, not as an emulator that if they are adaptable to a Pentium IV with any low-power game. Not much I use this emulator. Ok thanks anyway.

**Comment by unknownbrackets** [comment]
```
03:02:967 Main         D[FONT]: HLE\sceFont.cpp:896 sceFontClose(8e06f1c)
03:02:967 Main         D[FONT]: HLE\sceFont.cpp:896 sceFontClose(8e06f68)
03:02:967 Main         I[FONT]: HLE\sceFont.cpp:761 sceFontDoneLib(08e06ed0)
03:02:967 Main         I[IO]: HLE\sceIo.cpp:906 stderr: font_error:I, 08c70000
03:03:968 sgx-psp-at3- I[ME]: HLE\sceAtrac.cpp:1342 sceAtracReleaseAtracID(2)
03:03:985 Main         E[FONT]: HLE\sceFont.cpp:627 Font exists but is closed, which was not allowed in this call.
03:03:985 Main         E[FONT]: HLE\sceFont.cpp:902 sceFontClose(8e06f1c) - font not open?
03:03:985 Main         E[FONT]: HLE\sceFont.cpp:627 Font exists but is closed, which was not allowed in this call.
03:03:985 Main         E[FONT]: HLE\sceFont.cpp:902 sceFontClose(8e06f68) - font not open?
03:03:985 Main         I[FONT]: HLE\sceFont.cpp:761 sceFontDoneLib(08e06ed0)
```

```
07:21:21 DEBUG hle.sceFont - Main - sceFontClose fontHandle=0x8E06ED4
07:21:21 DEBUG hle.sceFont - Main - sceFontClose fontHandle=0x8E06ED8
07:21:21 DEBUG hle.sceFont - Main - sceFontDoneLib fontLibHandle=0x8E06ED0
07:21:22 DEBUG hle.sceFont - Main - sceFontClose fontHandle=0x8E06ED4
07:21:22 DEBUG hle.sceFont - Main - sceFontClose font already closed font=null
07:21:22 DEBUG hle.sceFont - Main - sceFontClose fontHandle=0x8E06ED8
07:21:22 DEBUG hle.sceFont - Main - sceFontClose font already closed font=null
07:21:22 DEBUG hle.sceFont - Main - sceFontDoneLib fontLibHandle=0x8E06ED0
07:21:22 DEBUG hle.sceFont - Main - sceFontDoneLib font lib already done 0x08E06ED0
```

Not allowing double-close is happening the same in both.  Maybe it's a timing thing?  Or maybe JPCSP's log just doesn't include stderr there?

What is the code around 08818328?

-[Unknown]

**Comment by sum2012** [comment]
I make screenshoot before crash
![1](https://cloud.githubusercontent.com/assets/2177532/12007677/c6238676-ac49-11e5-8e88-928ef89f696c.png)
![2](https://cloud.githubusercontent.com/assets/2177532/12007678/ca3e5088-ac49-11e5-9a0f-1ff8655993a7.png)

**Comment by unknownbrackets** [comment]
How about 088182c8?  That's the function that returned 0, so I'm wondering why it returned 0.

-[Unknown]

**Comment by sum2012** [comment]
![3](https://cloud.githubusercontent.com/assets/2177532/12007767/72c1dd84-ac4e-11e5-9cf6-e667b53f2cae.png)

**Comment by unknownbrackets** [comment]
Hmm, it definitely can return zero, mainly if a1 is zero.  But also in a more complicated case where something is not 3.  Hmm.

-[Unknown]

**Comment by unknownbrackets** [comment]
Recently, a double free issue with user defined memory management functions was fixed.  Has this issue improved?

-[Unknown]
