### ISSUE TITLE
15-30 fps in Final Fantasy 1 Anniversary Edition.

### ISSUE THREAD

**Issue by ofry** [hrydgard/ppsspp#7653]
In revision v1.0.1-243-g8fd9066 I have 15-30 fps in Final Fantasy Anniversary Edition all time (in video too).

If I choose Upscaling to Off or 2x, then all working fine (clear sound, no visible lags in video).
If I set Upscale to Auto, or at least 3x, then I got this problem.

Video card: ATI Radeon 7700 Series.
OS: Windows 7 Ultimate.
CPU: Intel Core 2 Quad Q9505

**Comment by ofry** [comment]
Info log of first seconds of playing Final Fantasy:

55:38:619 EmuThread.cpp:169 I[BOOT]: Done.
55:43:429 Config.cpp:954 I[LOAD]: Config saved: C:\ppsspp\ppsspp\memstick/PSP/SYSTEM/ppsspp.ini
55:43:431 Config.cpp:967 I[LOAD]: Controller config saved: C:\ppsspp\ppsspp\memstick/PSP/SYSTEM/controls.ini
55:43:433 System.cpp:348 I[BOOT]: PPSSPP v1.0.1-243-g8fd9066 Windows 64 bit
55:44:512 MemMap.cpp:338 I[MM]: Memory system initialized. RAM at 000000001BC50000 (mirror at 0 @ 0000000088000000, uncached @ 00000000C8000000)
55:44:513 PSPLoaders.cpp:168 I[LOAD]: ULES00986 : FINAL FANTASY
55:44:519 Config.cpp:954 I[LOAD]: Config saved: C:\ppsspp\ppsspp\memstick/PSP/SYSTEM/ppsspp.ini
55:44:522 PSPLoaders.cpp:210 I[LOAD]: Loading disc0:/PSP_GAME/SYSDIR/EBOOT.BIN...
55:44:522 HLE\sceKernelMemory.cpp:436 I[KERNEL]: Kernel and user memory pools initialized
55:44:558 HLE\sceKernel.cpp:151 I[KERNEL]: Kernel initialized.
55:44:590 Util\BlockAllocator.cpp:381 I[HLE]: -----------
55:44:590 Util\BlockAllocator.cpp:385 I[HLE]: Block: 08800000 - 08804000 size 00004000 taken=1 tag=usersystemlib
55:44:590 Util\BlockAllocator.cpp:385 I[HLE]: Block: 08804000 - 08b31100 size 0032d100 taken=1 tag=ELF/ff1psp
55:44:590 Util\BlockAllocator.cpp:385 I[HLE]: Block: 08b31100 - 0c000000 size 034cef00 taken=0 tag=(untitled)
55:44:590 Util\BlockAllocator.cpp:387 I[HLE]: -----------
55:44:615 HLE\ReplaceTables.cpp:1181 I[HLE]: Replaced memcpy at 0880f57c with hash 8c3fd997a544d0b1
55:44:615 HLE\ReplaceTables.cpp:1181 I[HLE]: Replaced memmove at 0880f6c0 with hash 368f6cf979709a31
55:44:615 HLE\ReplaceTables.cpp:1181 I[HLE]: Replaced memset at 0880f9c0 with hash 4bb677dace6ca526
55:44:615 HLE\ReplaceTables.cpp:1181 I[HLE]: Replaced ff1_battle_effect at 08920714 with hash e093c2b0194d52b3
55:44:615 HLE\sceKernelModule.cpp:1034 I[LOAD]: Module ff1psp: 089d2ee0 0893bf34 0893bf4c
55:44:616 HLE\sceKernelModule.cpp:1235 I[LOAD]: Exporting ent 0 named ff1psp, 2 funcs, 4 vars, resident 0893c2d4
55:44:616 HLE\sceKernelModule.cpp:1557 I[LOAD]: Module entry: 08939370
55:44:714 root         N[BOOT]: EmuScreen.cpp:141 Loading C:/Users/ofry/Downloads/Final Fantasy I + II Anniversary Edition PSP ISO/Final Fantasy 1.iso...
55:44:714 root         I[COMMON]: FileUtil.cpp:464 GetCreateTime: C:\ppsspp\ppsspp\memstick/PSP\PPSSPP_STATE\ULES00986_1.00_0.ppst: 1428037382
55:44:715 root         I[COMMON]: FileUtil.cpp:464 GetCreateTime: C:\ppsspp\ppsspp\memstick/PSP\PPSSPP_STATE\ULES00986_1.00_1.ppst: 1428027860
55:44:715 root         I[COMMON]: FileUtil.cpp:464 GetCreateTime: C:\ppsspp\ppsspp\memstick/PSP\PPSSPP_STATE\ULES00986_1.00_2.ppst: 1428036320
55:44:715 root         I[COMMON]: FileUtil.cpp:464 GetCreateTime: C:\ppsspp\ppsspp\memstick/PSP\PPSSPP_STATE\ULES00986_1.00_3.ppst: 1428036673
55:44:715 root         I[COMMON]: FileUtil.cpp:464 GetCreateTime: C:\ppsspp\ppsspp\memstick/PSP\PPSSPP_STATE\ULES00986_1.00_4.ppst: 1428037167
55:44:715 root         I[KERNEL]: HLE\sceKernelThread.cpp:2169 276=sceKernelCreateThread(user_main, 08939444, 00000020, 262144, 80000000, 00000000)
55:44:716 root         I[KERNEL]: HLE\sceKernelThread.cpp:2240 0=sceKernelStartThread(276, 33, 0bfffed0)
55:44:716 root         I[KERNEL]: HLE\sceKernelThread.cpp:2279 __KernelReturnFromThread: 0
55:44:720 user_main    I[UTIL]: HLE\sceUtility.cpp:220 sceUtilityLoadModule(768)
55:44:742 user_main    I[UTIL]: HLE\sceUtility.cpp:220 sceUtilityLoadModule(769)
55:44:771 user_main    I[UTIL]: HLE\sceUtility.cpp:220 sceUtilityLoadModule(770)
55:44:787 user_main    I[UTIL]: HLE\sceUtility.cpp:220 sceUtilityLoadModule(771)
55:44:821 user_main    I[ME]: HLE\sceMpeg.cpp:422 sceMpegInit()
55:44:839 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2169 284=sceKernelCreateThread(FF1, 088f36f4, 0000003c, 65536, 00204000, 00000000)
55:44:839 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2240 0=sceKernelStartThread(284, 0, 00000000)
55:44:839 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2169 285=sceKernelCreateThread(UncompThread, 088f4c5c, 00000016, 4096, 00200000, 00000000)
55:44:839 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2240 0=sceKernelStartThread(285, 4, 0bfff66c)
55:44:840 user_main    I[SCESAS]: HLE\sceSas.cpp:106 sceSasInit(08b2e700, 256, 32, 0, 44100)
55:44:841 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2169 288=sceKernelCreateThread(Atrac3PlayThread, 08902dd4, 00000014, 65536, 00200000, 00000000)
55:44:841 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2169 290=sceKernelCreateThread(Atrac3PlayThread, 08902dd4, 00000014, 65536, 00200000, 00000000)
55:44:841 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2169 291=sceKernelCreateThread(SoundThread, 088f4bd4, 00000012, 4096, 00200000, 00000000)
55:44:841 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2240 0=sceKernelStartThread(291, 4, 0bfff66c)
55:44:855 user_main    I[SCEGE]: Common\FramebufferCommon.cpp:331 Creating FBO for 00088000 : 1 x 1 x 3
55:44:856 user_main    I[G3D]: GLES\ShaderManager.cpp:140 Linked shader: vs 16 fs 17
55:44:871 user_main    I[SCEGE]: Common\FramebufferCommon.cpp:331 Creating FBO for 00000000 : 1 x 1 x 3
55:45:505 user_main    I[SCEGE]: GLES\Framebuffer.cpp:732 Resizing FBO for 00000000 : 480 x 272 x 3
55:45:506 user_main    I[G3D]: GLES\ShaderManager.cpp:140 Linked shader: vs 19 fs 20
55:45:521 user_main    I[SCEGE]: GLES\Framebuffer.cpp:732 Resizing FBO for 00088000 : 480 x 272 x 3
55:45:605 user_main    I[SCEGE]: GLES\Framebuffer.cpp:1884 Decimating FBO for 00000000 (1 x 1 x 3), age 6
55:45:622 user_main    I[SCEGE]: GLES\Framebuffer.cpp:1884 Decimating FBO for 00088000 (1 x 1 x 3), age 6
55:45:624 FF1          I[UTIL]: Dialog\PSPSaveDialog.cpp:85 sceUtilitySavedataInitStart(08c6faf4) - AUTOLOAD (0)
55:45:624 FF1          I[UTIL]: Dialog\PSPSaveDialog.cpp:86 sceUtilitySavedataInitStart(08c6faf4) : Game key (hex): 437BEAA762302FB7C8762C17CFF01460
55:45:823 idle0        I[UTIL]: Dialog\SavedataParam.cpp:586 Loading file with size 117760 in ms0:/PSP/SAVEDATA/ULES00986DATA00/SAVE.BIN
55:46:240 FF1          I[KERNEL]: HLE\sceKernelThread.cpp:2169 294=sceKernelCreateThread(MovieReadThread, 088e1c10, 0000001c, 4096, 00200000, 00000000)
55:46:240 FF1          I[ME]: HLE\sceMpeg.cpp:529 099c71b0=sceMpegCreate(08c52b80, 099c7180, 65536, 08c52db4, 512, 0, 0)
55:46:252 FF1          I[ME]: HLE\sceMpeg.cpp:647 sceMpegRegistStream(08c52b80, 0, 0)
55:46:252 FF1          I[KERNEL]: HLE\sceKernelThread.cpp:2169 297=sceKernelCreateThread(MovieDisplayThread, 088e0938, 0000001a, 4096, 00200000, 00000000)
55:46:253 FF1          E[ME]: HLE\sceMpeg.cpp:1893 UNIMPL sceMpegAvcInitYCbCr(08c52b80, 1, 480, 272, 099d7240)
55:46:253 FF1          E[ME]: HLE\sceMpeg.cpp:1893 UNIMPL sceMpegAvcInitYCbCr(08c52b80, 1, 480, 272, 09a07000)
55:46:253 FF1          E[ME]: HLE\sceMpeg.cpp:1893 UNIMPL sceMpegAvcInitYCbCr(08c52b80, 1, 480, 272, 09a36dc0)
55:46:253 FF1          E[ME]: HLE\sceMpeg.cpp:1893 UNIMPL sceMpegAvcInitYCbCr(08c52b80, 1, 480, 272, 09a66b80)
55:46:253 FF1          I[ME]: HLE\sceMpeg.cpp:647 sceMpegRegistStream(08c52b80, 1, 0)
55:46:253 FF1          I[KERNEL]: HLE\sceKernelThread.cpp:2169 299=sceKernelCreateThread(MovieSoundThread, 088e252c, 00000019, 4096, 00200000, 00000000)
55:46:253 FF1          I[KERNEL]: HLE\sceKernelThread.cpp:2169 300=sceKernelCreateThread(MoviePlayThread, 088de7f8, 0000001b, 8192, 00200000, 00000000)
55:46:254 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2240 0=sceKernelStartThread(300, 4, 0bfff63c)
55:46:254 MoviePlayThr I[ME]: HLE\sceMpeg.cpp:347 Stream offset: 2048, Stream size: 0x1077000
55:46:254 MoviePlayThr I[ME]: HLE\sceMpeg.cpp:348 First timestamp: 90000, Last timestamp: 10948848
55:46:254 MoviePlayThr I[ME]: HLE\sceMpeg.cpp:347 Stream offset: 2048, Stream size: 0x1077000
55:46:254 MoviePlayThr I[ME]: HLE\sceMpeg.cpp:348 First timestamp: 90000, Last timestamp: 10948848
55:46:254 MoviePlayThr I[KERNEL]: HLE\sceKernelThread.cpp:2240 0=sceKernelStartThread(299, 4, 0bf8aa7c)
55:46:254 MoviePlayThr I[KERNEL]: HLE\sceKernelThread.cpp:2240 0=sceKernelStartThread(294, 4, 0bf8aa7c)
55:46:254 MovieReadThr I[ME]: HLE\sceMpeg.cpp:347 Stream offset: 2048, Stream size: 0x1077000
55:46:254 MovieReadThr I[ME]: HLE\sceMpeg.cpp:348 First timestamp: 90000, Last timestamp: 10948848
55:46:267 MovieReadThr I[ME]: HW\MediaEngine.cpp:85 FF: deprecated pixel format used, make sure you did set range correctly
55:46:268 MovieReadThr I[ME]: HW\MediaEngine.cpp:85 FF: No accelerated colorspace conversion found from yuv420p to rgba.
55:46:930 user_main    I[G3D]: GLES\ShaderManager.cpp:140 Linked shader: vs 22 fs 23
55:47:058 user_main    I[SCEGE]: GLES\Framebuffer.cpp:1884 Decimating FBO for 00088000 (480 x 272 x 3), age 6
55:50:925 MoviePlayThr I[SCEGE]: GLES\Framebuffer.cpp:1884 Decimating FBO for 00088000 (480 x 272 x 3), age 6
55:51:525 MoviePlayThr I[SCEGE]: GLES\Framebuffer.cpp:1884 Decimating FBO for 00088000 (480 x 272 x 3), age 6
55:52:229 user_main    I[SCEGE]: GLES\Framebuffer.cpp:1884 Decimating FBO for 00088000 (480 x 272 x 3), age 6
55:55:369 user_main    I[SCEGE]: GLES\Framebuffer.cpp:1884 Decimating FBO for 00088000 (480 x 272 x 3), age 6
55:55:545 user_main    I[SCEGE]: GLES\Framebuffer.cpp:1884 Decimating FBO for 00088000 (480 x 272 x 3), age 6
56:30:994 idle0        I[KERNEL]: HLE\sceKernel.cpp:513 KO 272: Thread "idle0": pc= 08000000 sp= 083fff00 RUN      (wt=0 wid=0 wv= 00000000 )
56:30:995 idle0        I[KERNEL]: HLE\sceKernel.cpp:513 KO 273: Thread "idle1": pc= 08000000 sp= 083fef00  READY     (wt=0 wid=0 wv= 00000000 )
56:30:995 idle0        I[KERNEL]: HLE\sceKernel.cpp:513 KO 274: Module "ff1psp": name=ff1psp gp=089d2ee0 entry=08939370
56:30:995 idle0        I[KERNEL]: HLE\sceKernel.cpp:513 KO 276: Thread "user_main": pc= 088ea830 sp= 0bfff660  READY     (wt=0 wid=0 wv= 00000000 )
56:30:995 idle0        I[KERNEL]: HLE\sceKernel.cpp:513 KO 277: MemoryPart "UserSbrk": MemPart: 08b32000 - 09eac700	size: 0137a700
56:30:995 idle0        I[KERNEL]: HLE\sceKernel.cpp:513 KO 278: CallBack "exit": thread=276, argument= 00000000
56:30:995 idle0        I[KERNEL]: HLE\sceKernel.cpp:513 KO 279: CallBack "power": thread=276, argument= 00000000
56:30:995 idle0        I[KERNEL]: HLE\sceKernel.cpp:513 KO 280: CallBack "UMD Break Callback": thread=276, argument= 08b34e64
56:30:995 idle0        I[KERNEL]: HLE\sceKernel.cpp:513 KO 281: Semaphore "UMD_DEVICE_IO_SEMA": -
56:30:995 idle0        I[KERNEL]: HLE\sceKernel.cpp:513 KO 282: OpenFile "disc0:/PSP_GAME/USRDIR/data/ff1psp.dpk": Seekpos: 030e518c
56:30:995 idle0        I[KERNEL]: HLE\sceKernel.cpp:513 KO 283: EventFlag "SceGuSignal": init=00000001 cur=00000001 numwait=0
56:30:995 idle0        I[KERNEL]: HLE\sceKernel.cpp:513 KO 284: Thread "FF1": pc= 0891d778 sp= 0bfbfa30   WAIT    (wt=1 wid=0 wv= 00000000 )
56:30:995 idle0        I[KERNEL]: HLE\sceKernel.cpp:513 KO 285: Thread "UncompThread": pc= 08912270 sp= 0bfafaa0   WAIT    (wt=1 wid=0 wv= 00000000 )
56:30:995 idle0        I[KERNEL]: HLE\sceKernel.cpp:513 KO 286: Semaphore "SndpSystemSemaphore": -
56:30:995 idle0        I[KERNEL]: HLE\sceKernel.cpp:513 KO 287: EventFlag "AT3BGMFLAG": init=00000000 cur=00000040 numwait=0
56:30:995 idle0        I[KERNEL]: HLE\sceKernel.cpp:513 KO 288: Thread "Atrac3PlayThread": pc= 00000000 sp= 00000001     DORMANT  (wt=0 wid=0 wv= 00000000 )
56:30:995 idle0        I[KERNEL]: HLE\sceKernel.cpp:513 KO 289: EventFlag "AT3BGMFLAG": init=00000000 cur=00000040 numwait=0
56:30:995 idle0        I[KERNEL]: HLE\sceKernel.cpp:513 KO 290: Thread "Atrac3PlayThread": pc= 00000000 sp= 00000000     DORMANT  (wt=0 wid=0 wv= 00000000 )
56:30:995 idle0        I[KERNEL]: HLE\sceKernel.cpp:513 KO 291: Thread "SoundThread": pc= 08908dc8 sp= 0bf8ea90   WAIT    (wt=10 wid=5 wv= 00000100 )
56:30:995 idle0        I[KERNEL]: HLE\sceKernel.cpp:513 KO 292: EventFlag "controlFlag": init=00000000 cur=00000003 numwait=0
56:30:995 idle0        I[KERNEL]: HLE\sceKernel.cpp:513 KO 293: EventFlag "waitFlag": init=00000000 cur=00000001 numwait=0
56:30:995 idle0        I[KERNEL]: HLE\sceKernel.cpp:513 KO 294: Thread "MovieReadThread": pc= 088e1eac sp= 0bf8daa0   WAIT    (wt=2 wid=294 wv= 00000000 )
56:30:995 idle0        I[KERNEL]: HLE\sceKernel.cpp:513 KO 295: Semaphore "lock_sema": -
56:30:995 idle0        I[KERNEL]: HLE\sceKernel.cpp:513 KO 296: EventFlag "display_pause_flag": init=00000000 cur=00000001 numwait=0
56:30:995 idle0        I[KERNEL]: HLE\sceKernel.cpp:513 KO 297: Thread "MovieDisplayThread": pc= 00000000 sp= 00000000     DORMANT  (wt=0 wid=0 wv= 00000000 )
56:30:995 idle0        I[KERNEL]: HLE\sceKernel.cpp:513 KO 298: Semaphore "sound_lockSema": -
56:30:995 idle0        I[KERNEL]: HLE\sceKernel.cpp:513 KO 299: Thread "MovieSoundThread": pc= 08908dc8 sp= 0bf8ba90   WAIT    (wt=10 wid=6 wv= 00000800 )
56:30:995 idle0        I[KERNEL]: HLE\sceKernel.cpp:513 KO 300: Thread "MoviePlayThread": pc= 088df0d0 sp= 0bf8aa80   WAIT    (wt=4 wid=293 wv= 00000000 )
56:30:995 idle0        I[KERNEL]: HLE\sceKernel.cpp:513 KO 301: OpenFile "disc0:/PSP_GAME/USRDIR/movie/FF1_OP_Movie_MainUS.pmf": Seekpos: 00496800
56:30:995 idle0        I[KERNEL]: HLE\sceKernel.cpp:162 Shutting down kernel - 29 kernel objects alive
56:31:032 GLES\Framebuffer.cpp:1900 I[SCEGE]: Destroying FBO for 00088000 : 480 x 272 x 3
56:31:032 GLES\Framebuffer.cpp:1900 I[SCEGE]: Destroying FBO for 00000000 : 480 x 272 x 3
56:31:033 GLES\TextureCache.cpp:146 I[G3D]: Texture cached cleared from 4 textures
56:31:048 Config.cpp:954 I[LOAD]: Config saved: C:\ppsspp\ppsspp\memstick/PSP/SYSTEM/ppsspp.ini
56:31:048 Config.cpp:760 I[LOAD]: Loading config: C:\ppsspp\ppsspp\memstick/PSP/SYSTEM/ppsspp.ini
56:31:050 Config.cpp:868 I[LOAD]: Loading controller config: C:\ppsspp\ppsspp\memstick/PSP/SYSTEM/controls.ini
56:31:082 Config.cpp:954 I[LOAD]: Config saved: C:\ppsspp\ppsspp\memstick/PSP/SYSTEM/ppsspp.ini
56:31:083 Config.cpp:967 I[LOAD]: Controller config saved: C:\ppsspp\ppsspp\memstick/PSP/SYSTEM/controls.ini
56:31:219 Config.cpp:954 I[LOAD]: Config saved: C:\ppsspp\ppsspp\memstick/PSP/SYSTEM/ppsspp.ini
56:31:220 Config.cpp:967 I[LOAD]: Controller config saved: C:\ppsspp\ppsspp\memstick/PSP/SYSTEM/controls.ini

**Comment by ofry** [comment]
Huh, I found when this bug occurs.

If I choose Upscaling to Off or 2x, then all working fine (clear sound, no visible lags in video).
If I set Upscale to Auto, then I got this problem.

**Comment by GamerzHell9137** [comment]
Its not a problem, its dropping in frames because your PC can't handle it.
Turn it off and play the game without it.

**Comment by ofry** [comment]
But problem is "Auto" set me Upscaling to 3x, as I think. And game standing unplayable because awful video and sound lags.

**Comment by unknownbrackets** [comment]
Auto just matches your render resolution setting.  If you don't want the same upscale, don't select Auto.

I don't think this is an issue.  Auto isn't the default setting either.  Perhaps the utility of the Auto setting is limited, though.

-[Unknown]
