### ISSUE TITLE
PPSSPP does not build with either CMake or the standard build script on Linux with GCC 4.9.2.

### ISSUE THREAD

**Issue by MoochMcGee** [hrydgard/ppsspp#7655]
The commit that seems to have caused this is https://github.com/hrydgard/ppsspp/commit/b7498f4581e661aba9bd9b7ee0983597a82fe832

**Comment by MoochMcGee** [comment]
The lines with SetFocusable are the culprits.

**Comment by unknownbrackets** [comment]
Most likely you have not updated submodules, it's one of the first mistakes anyone makes using git with a project that uses them.  You need to run:

git submodule update --init

After git pull, or else it will have old submodules.  This change depends on a change that was made in a submodule, so you need to update for it to compile.

-[Unknown]

**Comment by MoochMcGee** [comment]
No, actually. I did update my submodules.

**Comment by unknownbrackets** [comment]
Well, this is working fine:
https://travis-ci.org/hrydgard/ppsspp/jobs/57164266

This is the commit to native that added that method:
https://github.com/hrydgard/native/commit/98083c8985ef52cb018fc8bd4ec89d2aaefccdd4

If you don't have it, you'll get errors.

-[Unknown]

**Comment by MoochMcGee** [comment]
Yes, this fixed it. Sorry for wasting your time.
