### ISSUE TITLE
Graphical Issues on Dante's Inferno

### ISSUE THREAD

**Issue by deadair3210** [hrydgard/ppsspp#7659]
Rainbow Distortions and Flickering occur throught play, expecially on the ground textures on the first level and rainbow coloration on the swing arc that comes from Dante's weapon.
ppsspp ver = ppsspp-v1.0.1-249-gd43368f-windows-amd64
Verified to not occur on a PSP 3000

**Comment by hrydgard** [comment]
Known issue, has already been reported. Duplicate of #6332 and #4845 .

**Comment by nfjorgebueno** [comment]
Has the same graphical problems from ppsspp-v1.3-469-g6680239-windows-amd64, thanks for your attention.sorry in the version of the emulator that I put looks perfect, that happened later, I do not know

**Comment by hrydgard** [comment]
Sorry @nfjorgebueno , not sure I understand. Are you saying that you're seeing rainbow effects in 1.3-469? Are you also seeing them in the latest build?
