### ISSUE TITLE
Final Fantasy Artifacting in the latest builds

### ISSUE THREAD

**Issue by GamerzHell9137** [hrydgard/ppsspp#7660]
For some reason the game is artifacting in the newest build(and on the older 1.0.1 builds)

![ppssppwindows64 2015-04-06 12-26-11-086](https://cloud.githubusercontent.com/assets/2002038/7003351/497f37e8-dc59-11e4-9741-8f665d1fed51.jpg)

https://youtu.be/NTbHxRal9cs

Check the weird pixel lines.

**Comment by daniel229** [comment]
Does uncheck Vertex Cache help it.

**Comment by GamerzHell9137** [comment]
It actually does, thanks for that.

**Comment by unknownbrackets** [comment]
Vertex cache if off by default now, so I'm going to close this.  On Vulkan, it's not as beneficial, and it's hard to avoid minor glitches like this with the vertex cache on.

-[Unknown]
