### ISSUE TITLE
100-in-1 Megamix can't load savedata

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#7676]
PPSSPP can't load the savedata created by either itself or PSP,but the savedata created by PPSSPP can be loaded in PSP.
Until I copied the savedata NPEH00068 and renamed to NPEH00068_GameData0,then it can be loaded.But PSP does not have NPEH00068_GameData0.

with NPEH00068
![01](https://cloud.githubusercontent.com/assets/3481559/7105244/ff3c8c92-e141-11e4-89f8-a5f49ff61a83.png)

with NPEH00068 + NPEH00068_GameData0
![02](https://cloud.githubusercontent.com/assets/3481559/7105245/ff3cf6dc-e141-11e4-8c94-3015e081dfe3.png)

jpcsptrace
https://gist.github.com/daniel229/d554b9775370ffc8bca9

debuglog (rename jpg to 7z)
with NPEH00068
![ppsspplog_notwork](https://cloud.githubusercontent.com/assets/3481559/7105249/334c0c88-e142-11e4-8d1e-f0907c185c88.jpg)

with NPEH00068 + NPEH00068_GameData0
![ppsspplog_work](https://cloud.githubusercontent.com/assets/3481559/7105250/3ebbefb6-e142-11e4-99a3-52665754ed7b.jpg)

**Comment by unknownbrackets** [comment]
Does it matter what it's named?  Like does it have to be _GameData0, or does anything work?

-[Unknown]

**Comment by daniel229** [comment]
If just NPEH00068_GameData0 in the folder,it show "Unable to load data.", NPEH00068 have to be there.NPEH00068_GameData1 won't work,neither does NPEH00068_GameData01.
![01](https://cloud.githubusercontent.com/assets/3481559/7172217/5e6bdcd2-e416-11e4-9485-0a84c6612f4d.png)

**Comment by unknownbrackets** [comment]
Is the JpcspTrace with or without a save?  It never seems to mention _GameData0, so I'm just wondering where it comes from.

-[Unknown]

**Comment by daniel229** [comment]
With a save.

**Comment by benderscruffy** [comment]
PPSSPP v1.5.4-997-g3472d62ff Windows 64 bit
still a problem
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/2029275/ppsspplog.zip)

**Comment by benderscruffy** [comment]
v1.8.0-2-g7f1e10a93
still happens

**Comment by sum2012** [comment]
Fixed in v1.10-695-f78c008a #13434
let @hrydgard or @unknownbrackets  change back old Milestone

**Comment by hrydgard** [comment]
Hm, we hide old milestones so no easy way to tag.. Oh well.
