### ISSUE TITLE
Major League Baseball 2K12 blue color

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#7682]
Looks similar to https://github.com/hrydgard/ppsspp/issues/4109

![01](https://cloud.githubusercontent.com/assets/3481559/7109068/cb334c06-e1c8-11e4-9587-12d05772ccff.png)

psp
![201504130000_001](https://cloud.githubusercontent.com/assets/3481559/7109076/fcef33cc-e1c8-11e4-9b8f-b8cdf94da437.png)

Gedebugger
![03](https://cloud.githubusercontent.com/assets/3481559/7109077/067db7ec-e1c9-11e4-9103-b5e49ed6dfaf.png)

more tabs
https://gist.github.com/daniel229/f3cd18200cb56a5c4f77

**Comment by unknownbrackets** [comment]
I think the CLUT looks suspect:

CLUT	04187ca1, w=0

Maybe it forces alignment?  Or maybe it's a render-to-clut?  Alignment seems likely to me.

Does anything change if you modify this line:
https://github.com/hrydgard/ppsspp/blob/be7d1d1169a555f9c8740424b88ae5f9d6e07b95/GPU/GPUState.h#L305

To, let's say:
```c++
u32 getClutAddress() const { return (clutaddr & 0x00FFFFFC) | ((clutaddrupper << 8) & 0x0F000000); }
```

Probably needs hardware testing.

-[Unknown]

**Comment by daniel229** [comment]
Looks good with that change
![01](https://cloud.githubusercontent.com/assets/3481559/7109342/8ee2bd44-e1ce-11e4-9d5a-30482f91ea97.png)
