### ISSUE TITLE
LocoRoco 1 crashed in certain stage with high quality Spline/Bezier curves.

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#7684]
Release builds crashed,but debug build is fine.
Low or Medium quality Spline/Bezier curves is fine.
After adding <code>#pragma optimize( "", off )</code> to anywhere(the first line or the last line) of SplineCommon.cpp,the release build is fine.

release build stacktrace
![02](https://cloud.githubusercontent.com/assets/3481559/7129535/47495fbc-e294-11e4-913d-5b418b73ec8c.png)

Crash in this stage
![01](https://cloud.githubusercontent.com/assets/3481559/7129511/fdf407d6-e293-11e4-8583-01cb3ff369ee.png)

savedata(rename jpg to 7z)
![ucas40063_gamedata0](https://cloud.githubusercontent.com/assets/3481559/7129521/1e9f4a9a-e294-11e4-9ba5-d151265dc89a.jpg)

**Comment by unknownbrackets** [comment]
What if you put `#undef _M_SSE` right before the first `#if defined(_M_SSE)`?  Does it not crash anymore?

-[Unknown]

**Comment by daniel229** [comment]
Still crashed.

**Comment by unknownbrackets** [comment]
Hmm, unfortunately I don't have the game.  What if you use `#pragma optimize("y", off)` or `#pragma optimize("g", off)`?  These might give better local variables, if they work.

-[Unknown]

**Comment by daniel229** [comment]
<code>#pragma optimize("y", off)</code> works

**Comment by sum2012** [comment]
@daniel229 Does https://github.com/sum2012/ppsspp/commit/227fc58d791148e9278b3fdc4bd27f0ab7729b0f fix ?

**Comment by daniel229** [comment]
Yes.

**Comment by unknownbrackets** [comment]
Well, that's just a y position.  Based on the matrix or whatever 10000 could be completely reasonable...

-[Unknown]

**Comment by sum2012** [comment]
Release build crash stace
I think there is a problem of #INF0000
![1](https://cloud.githubusercontent.com/assets/2177532/7157672/4aaa449e-e3a4-11e4-9e2a-22b591554870.png)

**Comment by unknownbrackets** [comment]
Infinity is infinity.  The problem is, since this is release, those are probably not real numbers... by which I mean, the value probably is not actually infinity.

Anyway, you can use `my_isinf()` or `isinf()` to check if it's infinity.  Either way, even if that value becomes infinity, that's not a good reason for it to crash.

-[Unknown]

**Comment by sum2012** [comment]
the value is actually infinity

						if (isinf(vert_pos.x)){
							ERROR_LOG(G3D, "Something went wrong infinity x");
							return;
						}

full log
https://gist.github.com/sum2012/6ba419ffec444af03b12

**Comment by hrydgard** [comment]
Hm, I see one way we could get infinities into the knots, but it requires that n or m == 0 (spline knot will initialize knot[0] to match knot[3] and then spline_n_4 will subtract them and divide a value by the result)

**Comment by daniel229** [comment]
No,it doesn't.When it crashes <code>n = 16,m = 3</code>
![01](https://cloud.githubusercontent.com/assets/3481559/7182507/70aa9898-e484-11e4-8a70-f4d69ca43439.png)

**Comment by hrydgard** [comment]
okay thanks, one more thing to try: In AccumulateWeighted, try removing the SSE stuff so it's just 	

    out += in * w.x;

Also do the same in spline_n_4().

**Comment by daniel229** [comment]
Still crashes,and I already tried removing all SSE stuff before.

**Comment by sum2012** [comment]
I think the crash is from above
SimpleVertex *a = spatch.points[idx];

**Comment by unknownbrackets** [comment]
Is infinity actually causing the crash?

```c++
if (isinf(vert_pos.x)) {
    vert_pos.x = 10000.0f;
}
if (isinf(vert_pos.y)) {
    vert_pos.y = 10000.0f;
}
if (isinf(vert_pos.z)) {
    vert_pos.z = 10000.0f;
}
```

-[Unknown]

**Comment by hrydgard** [comment]
Hm, I can repro this now. I will debug it.

**Comment by sum2012** [comment]
@unknownbrackets That change don't help
@hrydgard Thanks for trying to solve to unusal bug

**Comment by hrydgard** [comment]
@sum2012 well, this was a real bug that could affect any game with large spline draws. Thank you for reporting, please do some testing to confirm it's fixed for you as well :)

**Comment by unknownbrackets** [comment]
Yeah, thanks to both @daniel229 and @sum2012.

-[Unknown]
