### ISSUE TITLE
get new savedata / no savedata  Screen when trying delete savedata.

### ISSUE THREAD

**Issue by lightfirst** [hrydgard/ppsspp#7685]
some game allow me delete savedata, but PPSSPP show "new savedata" Screen or no savedata screen.

**Comment by vnctdj** [comment]
I think you should tell us which games are concerned... "Some games" is not very precise ^^

**Comment by lightfirst** [comment]
OK,
Project DIVE - extend [NPJH50465] : "NEW DATA"
Dragon Ball Z: Shin Budokai 2 (J) [ULJS00107] "There is no data"
Mahou Shoujo Lyrical Nanoha A's Portable: The Battle of Aces [ULJS00241]: success delete SAVEDATA.

**Comment by Panderner** [comment]
It seems Burnout Games are able to delete save files but it disguised as new data
![70370170-becbab80-18fe-11ea-93bc-47b81d55453e](https://user-images.githubusercontent.com/37503397/71675399-abeeae80-2db8-11ea-9a66-b14125e40ff5.gif)

**Comment by unknownbrackets** [comment]
Hm, that would mean that the save metadata isn't loading properly.  Is that the case for all games with this issue?

-[Unknown]

**Comment by Panderner** [comment]
Here's a log I've tried to delete save files:
```
user_main    E[SCEUTIL]: Dialog/SavedataParam.cpp:321 Bad param with gameName empty - cannot delete save directory
```

**Comment by Panderner** [comment]
I've tried to delete Save File in SpongeBob's Truth and Square The save file Cannot be deleted
Here's a log:
```
04:53:334 user_main    E[SCEUTIL]: Dialog/PSPSaveDialog.cpp:198 Load/Save function 9 not coded. Title: ULUS10478 Save: ULUS10478 File: SB09SAV0.DAT
```

**Comment by Panderner** [comment]
Nanoha The Battle of Aces and Crisis Core displays save file correctly and able to be deleted

**Comment by Panderner** [comment]
In Ghost in the Shell, only the first slot is able to delete it. I can't delete the rest of extra save slots

Save Screen:
![Screenshot_2020-04-17-19-57-37-35_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/79566891-dead8000-80e5-11ea-96c0-381a3b3a2bc2.png)

Delete screen:
![Screenshot_2020-04-17-19-59-11-91_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/79566955-f2f17d00-80e5-11ea-8828-f670eb02dcb7.png)

**Comment by hrydgard** [comment]
Please test again now that shenweip's #13507 is merged!

**Comment by Panderner** [comment]
After #13507 this will delete other save files instead.
![Screenshot_2020-10-05-08-31-25-39_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/95030953-ad515c80-06e5-11eb-92ac-21cda19ef5b4.png)

**Comment by shenweip** [comment]
@Panderner Weird as it may seem, but this is what PSP exactly does. If don't list all saves as the PSP does, there are still some bugs.

**Comment by Panderner** [comment]
and this one too.
![Screenshot_2020-10-05-13-51-20-29_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/95044428-f7503780-0711-11eb-85a4-1af61c4d31a2.png)

**Comment by shenweip** [comment]
This was closed by af43579, if there are still issues remaining, please reopen.

**Comment by Panderner** [comment]
@unknownbrackets why reopen?

**Comment by unknownbrackets** [comment]
Oops, I somehow misread the above comment and didn't see the "if".  I thought it was accidentally closed.

-[Unknown]
