### ISSUE TITLE
"One Piece - Romance Dawn - Bouken no Yoake" invalid addresses in battle

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#7686]
Since https://github.com/unknownbrackets/ppsspp/commit/7ea9bcbc13c5a68d3daf5861f1dbc7dfe15d5558 in https://github.com/hrydgard/ppsspp/pull/7672

**Comment by daniel229** [comment]
it's case 54: //lv.q

**Comment by unknownbrackets** [comment]
What's the invalid address?

Adding this back solves it `gpr.MapReg(rs, true, false);`?  That really should just be killing the immediate.

-[Unknown]

**Comment by daniel229** [comment]
Yes,adding that back solves it.
Log of invalid addresses
https://gist.github.com/daniel229/518e1847c7ddab4bd48f

**Comment by unknownbrackets** [comment]
Oh, wait, I think I know.  Something is abusing EAX.... got it.

-[Unknown]

**Comment by daniel229** [comment]
Fixed in the latest build.
