### ISSUE TITLE
eden Homebrew black screen

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#7687]
eden Homebrew download link:
https://drive.google.com/file/d/0B3OaSdeV0L8kYy1mWGh1eEtxLWs/view?usp=sharing

v1.0.1-424-gb818509
info log:
https://gist.github.com/sum2012/a30e44542aab08678bf0
debug log:
https://drive.google.com/file/d/0B3OaSdeV0L8kZUM1ZkRzeTlaeFE/view?usp=sharing

For 12:35:320 user_main    E[HLE]: Util\BlockAllocator.cpp:134 Block Allocator failed to allocate 262144 (00040000) bytes of contiguous memory

I think cfw should get more memory

**Comment by unknownbrackets** [comment]
It already has 56.19 MB allocated per the log, does it work differently with PSP-1000 mode?  I'm not sure you can even allocate the full 56 on CFW.

-[Unknown]

**Comment by sum2012** [comment]
It works same with PSP-1000 mode :black screen

**Comment by sum2012** [comment]
I try add dummy moule,still black screen.
log:
https://gist.github.com/sum2012/6c554a3fdaac8ed3f60a

I look more search PSP memory
PSP-2000/3000: 64 MB total, 32MB used for system, another 32mb used for UMD cache, available memory not changed for compatibility with 100x models.

I think some function can use up to 64 MB

**Comment by sum2012** [comment]
I try this code in System.cpp still fail

	if (g_Config.iPSPModel == PSP_MODEL_FAT)
		Memory::g_MemorySize = Memory::RAM_DOUBLE_SIZE;<--- change
	else
		Memory::g_MemorySize = Memory::RAM_DOUBLE_SIZE;

**Comment by unknownbrackets** [comment]
Some of that memory is called "volatile" memory, and some is dedicated for the kernel.  So games can never use all 64MB, not even homebrew, since otherwise all the syscalls would have to be deleted and they wouldn't even be able to draw things.

-[Unknown]

**Comment by sum2012** [comment]
JPCSP fix the issue in
https://github.com/gid15/jpcsp/commit/5c90f1b4334f86315dd9dadaa5310aaffa70aeba
Maybe ppsspp also need that change ?

**Comment by unknownbrackets** [comment]
Hmm, in theory we already allow them to be allocated in kernel memory...

-[Unknown]

**Comment by unknownbrackets** [comment]
This isn't about memory size, it's about kernel memory not being used for kernel threads.

-[Unknown]

**Comment by sum2012** [comment]
Well done @unknownbrackets 
Do I need to create another issue for the missing font ?

**Comment by unknownbrackets** [comment]
Well, we can, but I think it's because of how the game draws the font.  If you use software rendering, it shows fine.

I didn't look into how the game works, but this may be hard to fix if it draws things using pixel poking.

-[Unknown]
