### ISSUE TITLE
Still multiplayer issues in Dragonballz tag team tenkaichi

### ISSUE THREAD

**Issue by VoltTackle** [hrydgard/ppsspp#7691]
is there any way to improve adhoc connection is there a way so that i can help

**Comment by Fewer1432** [comment]
Como puedo jugar multiplayer al dragón ball tag team ten
kaichi

**Comment by VoltTackle** [comment]
can you help me, i also want to play it for multiplayer, which build and settings are you using..

**Comment by unknownbrackets** [comment]
Is this still an issue in recent git builds (https://buildbot.orphis.net/ppsspp/)?  Networking / adhoc functionality may have improved recently.

-[Unknown]

**Comment by hrydgard** [comment]
I think this is fixed, closing. Can reopen if needed.
