### ISSUE TITLE
D3D9: Ouka Sengoku Portable display nothing

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#7692]
Software rendering also have the same problem.OpenGL works fine.

OpenGL
![01](https://cloud.githubusercontent.com/assets/3481559/7197842/72c938c0-e518-11e4-9276-76fb5f2fda47.png)

D3D9 and Software rendering
![02](https://cloud.githubusercontent.com/assets/3481559/7197843/72d174d6-e518-11e4-9a19-f5df9b14cc8b.png)

GE debugger
![03](https://cloud.githubusercontent.com/assets/3481559/7197853/8a5e3206-e518-11e4-87e3-8893d35aacde.png)
more tabs
https://gist.github.com/daniel229/43c3adb51ebd2062f470

**Comment by daniel229** [comment]
It does not highlight when step prim in all mode OpenGL, D3D9 and software rendering.

**Comment by unknownbrackets** [comment]
Currently, beziers and splines don't highlight.

-[Unknown]

**Comment by unknownbrackets** [comment]
Has anything improved with depth changes here?  This did use a >= test.

We likely have bugs in the less tested paths that lead to bezier/spline in Direct3D9 and software... I guess that's the most likely explanation.

-[Unknown]

**Comment by daniel229** [comment]
Fixed.
