### ISSUE TITLE
tales of phantasia cross editon speed issues 

### ISSUE THREAD

**Issue by asbel123** [hrydgard/ppsspp#7701]
i tried to play it on windows still go slow alot tried to go battle ok speed but u cant run proplery on andriod can u make it faster speed for tales of phantasia  cross eediton and u fixing tales of destiny 2 speed problems on the town not the battle please. i  just wait for new version of ppsspp

**Comment by unknownbrackets** [comment]
Unfortunately, the battle entry effect is very demanding on modern gpus.  It performs better in Direct3D 9.  I think you can turn off "slow effects" to disable it.  I'm not sure a lot can be done here, but this isn't very constructive without information or ideas to lead to an optimization.

There's already an issue with actual useful information on Tales of Destiny 2.

So, closing this.

-[Unknown]
