### ISSUE TITLE
OpenGL 3D render issue

### ISSUE THREAD

**Issue by xiangzhai** [hrydgard/ppsspp#7703]
Hi ppsspp developers,

2D graphic render is perfect! shown as https://pbs.twimg.com/media/CDBmfuNVAAAAmZ3.png
But 3D is just so so, a little buggy ;P https://pbs.twimg.com/media/CDBmf97VIAAguO4.png

My OpenGL relatived thing shown as:

```
OpenGL 2.0 or higher.
...
Pixels: 960 x 544
Virtual pixels: 960 x 544
I: /data/project/ppsspp/native/gfx_es2/gl_state.cpp:133: I: GPU Vendor : Intel Open Source Technology Center ; renderer: Mesa DRI Mobile Intel® GM45 Express Chipset  version str: 2.1 Mesa 10.6.0-devel (git-6b722c3) ; GLSL version str: 1.20
I: /data/project/ppsspp/native/gfx_es2/gpu_features.cpp:20: I: Checking for GL driver bugs... vendor=0 model='Mesa DRI Mobile Intel® GM45 Express Chipset '
```

when playing the 3D game, it shown as:

```
19:22:525 user_main    I[SCEGE]: Common/FramebufferCommon.cpp:331 Creating FBO for 00044000 : 480 x 272 x 1
19:22:574 idle0        I[SCEGE]: GLES/Framebuffer.cpp:1818 Decimating FBO for 00088000 (480 x 272 x 3), age 9
19:40:432 user_main    I[SCEGE]: Common/FramebufferCommon.cpp:331 Creating FBO for 001fe000 : 64 x 64 x 0
19:40:516 user_main    I[SCEGE]: Common/FramebufferCommon.cpp:331 Creating FBO for 00088000 : 256 x 272 x 3
19:40:535 user_main    I[SCEGE]: GLES/Framebuffer.cpp:696 Resizing FBO for 00044000 : 512 x 272 x 1
19:40:555 user_main    I[SCEGE]: GLES/Framebuffer.cpp:696 Resizing FBO for 00000000 : 512 x 272 x 1
19:44:575 user_main    I[SCEGE]: GLES/Framebuffer.cpp:696 Resizing FBO for 00088000 : 256 x 273 x 3
19:44:578 user_main    I[SCEGE]: GLES/Framebuffer.cpp:696 Resizing FBO for 00000000 : 481 x 273 x 1
19:44:610 user_main    I[SCEGE]: GLES/Framebuffer.cpp:696 Resizing FBO for 00044000 : 481 x 273 x 1
21:15:517 user_main    I[SCEGE]: Common/FramebufferCommon.cpp:331 Creating FBO for 001fc000 : 64 x 273 x 3
21:15:529 user_main    I[SCEGE]: Common/FramebufferCommon.cpp:331 Creating FBO for 00195140 : 256 x 273 x 3
21:18:430 idle0        I[SCEGE]: GLES/Framebuffer.cpp:1818 Decimating FBO for 001fc000 (64 x 273 x 3), age 6
21:18:431 idle0        I[SCEGE]: GLES/Framebuffer.cpp:1818 Decimating FBO for 00195140 (256 x 273 x 3), age 6
```

Do I ***miss*** something? please someone give me some advice, thanks a lot!

Regards,
Leslie Zhai

**Comment by Bigpet** [comment]
Can you please clarify. What is the "issue"?

**Comment by 4XPG** [comment]
Uh, there are clearly a lot of artifact pixels in the second screenshot.

**Comment by hrydgard** [comment]
When posting pics that are wrong, it's good practice to also post a pic that's "right", which you could get by running the emu on the PC. Usually makes it easier to figure out what the issue might be.

In this case though, I really have no idea what it could be, this certainly doesn't happen on most hardware. Just looks weird...

**Comment by xiangzhai** [comment]
Hi @Bigpet sorry for my poor English ;P 
yup! @4XPG a lot of artifact pixels in the second screenshot, thanks for your clear description ;)

@hrydgard the game ridge racer 2 was able to run happily on my real PSP in 2006 ~ 2012, but my PSP`s battery was broken, so I am excited to experience ppsspp, it is awesome!
I am a Linux desktop developer, and I am clear the ***situation*** of graphic stack for Linux, for example:

1. failed to choose EGL config owing to Weston on DRM backend won't start with new version of mesa https://bugs.freedesktop.org/show_bug.cgi?id=89689
2. weston have not implemented mirroring mode yet http://lists.freedesktop.org/archives/wayland-devel/2015-April/021245.html

But I want (try) to fix it just for fun && learn ;-) it might be the Intel`s Graphics device driver, Mesa and other relative issue.

Regards,
Leslie Zhai

**Comment by xiangzhai** [comment]
I built the upstream kernel,

```
Linux archlinux 4.0.0+ #1 SMP Tue Apr 21 11:58:06 CST 2015 x86_64 GNU/Linux
```

then it is ok now https://pbs.twimg.com/media/CDGC5TGVAAEUFQN.png https://pbs.twimg.com/media/CDGC5qSVAAAX9E_.png
