### ISSUE TITLE
Tekken 6 is not booting

### ISSUE THREAD

**Issue by i30817** [hrydgard/ppsspp#7706]
Even with the clock speed set to auto (0)

Can someone else try it out?

**Comment by hrydgard** [comment]
Since what version? It certainly has been booting very recently.

Also, try to default settings (but save aside your ppsspp.ini first so we can figure out what differs!)

**Comment by i30817** [comment]
Git head. I am using the default settings (i created a per game config and reset it). I am however using a cso iso.

**Comment by i30817** [comment]
Also:
OpenGL 2.0 or higher.
Pixels: 960 x 544
Virtual pixels: 960 x 544
I: /home/i30817/Documents/projects/ppsspp/native/gfx_es2/gl_state.cpp:133: I: GPU Vendor : X.Org ; renderer: Gallium 0.4 on AMD RV710 version str: 3.0 Mesa 10.3.2 ; GLSL version str: 1.30
I: /home/i30817/Documents/projects/ppsspp/native/gfx_es2/gpu_features.cpp:20: I: Checking for GL driver bugs... vendor=0 model='Gallium 0.4 on AMD RV710'
E: /home/i30817/Documents/projects/ppsspp/native/base/PCMain.cpp:640: E: Output audio samples: 1024 (requested: 2048)
WriteRest: op out of range (0x20128920 uses 0x7f3da4006980)

This is a home portable built ppsspp not libretro or anything else (that last line leads me to a libretro ppsspp bug which they say 'doesn't happen in standalone' so i'm now thinking something in my system configuration like a not execute cpu flag or something.

**Comment by i30817** [comment]
https://github.com/dolphin-emu/dolphin/pull/942
https://github.com/libretro/libretro-ppsspp/issues/22

**Comment by i30817** [comment]
Adding "-fno-pie" to the cmake CXX options didn't made it work, no idea why:
cd ~/Documents/projects/ppsspp/ ; git pull && git submodule update --init && cmake -DCMAKE_CXX_FLAGS="-fno-pie" -DCMAKE_BUILD_TYPE=Release . && make -j2 && ./PPSSPPSDL --fullscree

**Comment by unknownbrackets** [comment]
#6694 should have made us look better for memory addresses.  A bt for that warning might be good, though, in case it's some specific variable.

You might have to make clean.

-[Unknown]

**Comment by i30817** [comment]
I don't have more than 4 gb phyisical ram. And i did make clean. This means you guys have no problem with it right?

**Comment by unknownbrackets** [comment]
Well, your operating system can manage address space any way it likes.  So it can still use more than 4gb of address space.

Seems a bit odd, though.

What distro is this?

-[Unknown]

**Comment by i30817** [comment]
Ubuntu 64 bits.

**Comment by unknownbrackets** [comment]
Have you customized make.conf or anything?  We run our tests on a Ubuntu 64-bit system (trusty), and they ought to generate the same error if they're having 64-bit problems...

-[Unknown]

**Comment by i30817** [comment]
No i have not edited make.conf i don't think, but i can delete it and pull. Before that thou:

Tekken 6 -> WriteRest: op out of range (0x212ea920 uses 0x7f5cbc18b920) - stops loading
Brandish -> WriteRest: op out of range (0x2488f6dc uses 0x7f5cbc18b730)  -  work fine
Echochrome -> WriteRest: op out of range (0x2b2a0580 uses 0x7f5cbe417090) -  work fine
LoH: Zero No Kiseki -> WriteRest: op out of range (0x2d640980 uses 0x7f5cbde83350)
 - works fine
LoH: Trails in the Sky -> WriteRest: op out of range (0x399a5e24 uses 0x7f5cbf307260) - works fine
Mana Khemia -> WriteRest: op out of range (0x3ab323f8 uses 0x7f5cbf307260) - works fine
**Metal Gear Acid -> SEGFAULT**
**Metal Gear Acid 2 -> SEGFAULT**
**Metal Gear Peace Walker -> SEGFAULT**
Nayuta no Kiseki -> WriteRest: op out of range (0x201487bc uses 0x7fcb68160300) - works fine
3rd birthday: starts with distorted 'save notification' screen, seems to work fine but then crashed... once - didn't print a warning
Persona 2 Innocent Sin -> WriteRest: op out of range (0x20109f5c uses 0x7f7d3408d570) - works fine
Persona 2 Eternal Punishement -> WriteRest: op out of range (0x20109f5c uses 0x7f7d3408d570) - works fine
Samurai Dou 1 -> WriteRest: op out of range (0x28f24b2b uses 0x7f7d3408d2f0) - works fine
Tactics Ogre -> flickering like hell, but no print
Valkyria Chronicles 3 -> WriteRest: op out of range (0x2f9d0638 uses 0x7f7d3408d2f0) - works fine

Where the "WriteRest: op out of range" appears it's always shortly after starting
I did however just tested this one after the other so allocation patterns might have influenced it. Except the crashes which are repeatable.

**Comment by i30817** [comment]
Oh doh, i moved the ~/config/ppsspp folder and the crashes disappeared and Tekken 6 started to work and even the WriteRest: op out of range warning disappeared.

Do you want a zip of it? I might have accidentally nuked a cache of something while backing up a while ago... i thought it wasn't important since it was a cache and would get recreated, but obviously not

**Comment by i30817** [comment]
Ok its something to do with the system config files:
![system zip](https://cloud.githubusercontent.com/assets/757900/7266593/2af84100-e8a4-11e4-8723-68b4a29ac445.jpg)

Save as and remove the jpg

**Comment by i30817** [comment]
specifically the ini:
![ppsspp ini](https://cloud.githubusercontent.com/assets/757900/7266675/3119b8d8-e8a5-11e4-9bfb-dd0aee3d1041.jpg)


Save as and remove the jpg

**Comment by i30817** [comment]
Mmmm i had ignore bad mem access set to false, probably because i forgot about it after testing - this prevents the crash but not the "WriteRest: op out of range". Unlike nuking everything it seems to me.

**Comment by DonelBueno** [comment]
Here it doesn't boot if multi-threaded is checked, otherwise it boots fine.

**Comment by i30817** [comment]
Oh there actually is a bug exposed in this bug report i think. I created a game config and reset it... but it didn't change a original setting - maybe because resetting game configs only resets the 'keys'/settings that are overridden on that config? When maybe it should reset everything? I dunno. But IgnoreBadMemAccess which is a hidden setting (to make it worse) didn't get reset.
