### ISSUE TITLE
 Prince of Persia: The Forgotten Sands [US] unplayable

### ISSUE THREAD

**Issue by nfjorgebueno** [hrydgard/ppsspp#7707]
the game freezes on the second level ethereal world ppsspp any version 1.0.1,the same goes for ppsspp 1.0
[HLE]: Merging Blocks
38:41:968 Util\BlockAllocator.cpp:229 D[HLE]: Block Alloc found adjacent free blocks - merging
38:41:968 Util\BlockAllocator.cpp:249 D[HLE]: Block Alloc found adjacent free blocks - merging
38:41:968 Util\BlockAllocator.cpp:224 D[HLE]: Merging Blocks
38:41:968 Util\BlockAllocator.cpp:249 D[HLE]: Block Alloc found adjacent free blocks - merging
38:42:015 MemMap.cpp:380 D[MM]: Memory system shut down.
38:42:015 GLES\Framebuffer.cpp:1856 I[SCEGE]: Destroying FBO for 00000000 : 480 x 272 x 3
38:42:015 GLES\Framebuffer.cpp:1856 I[SCEGE]: Destroying FBO for 00088000 : 480 x 272 x 3
38:42:015 GLES\Framebuffer.cpp:1856 I[SCEGE]: Destroying FBO for 00110000 : 256 x 256 x 3
38:42:015 GLES\Framebuffer.cpp:1856 I[SCEGE]: Destroying FBO for 00154000 : 128 x 128 x 3
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 23
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 37
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 25
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 57
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 24
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 56
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 17
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 42
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 35
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 19
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 84
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 60
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 36
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 59
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 58
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 63
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 88
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 31
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 82
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 34
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 90
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 87
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 85
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 83
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 33
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 103
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 108
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 96
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 86
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 70
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 32
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 107
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 102
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 79
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 78
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 89
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 77
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 93
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 94
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 95
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 20
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 44
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 43
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 22
38:42:031 GLES\TextureCache.cpp:134 D[G3D]: Deleting texture 48
38:42:031

**Comment by daniel229** [comment]
Is it freezing on the word "LOOK!THE GLOBE", that is https://github.com/hrydgard/ppsspp/issues/7282 ,and it should be playable on 0.9.9.1 or older versions.

**Comment by nfjorgebueno** [comment]
in older versions the screen flashes, stays dark, this is ramdon, plus the game is no sound, it seems playable, thanks for listening

**Comment by daniel229** [comment]
Or try the much older build v0.9.8-1450-g63bcb65 from http://buildbot.orphis.net/ppsspp/index.php?m=fulllist ,that build didn't flicker.

**Comment by nfjorgebueno** [comment]
thank you, thank you very much for your attention
