### ISSUE TITLE
ppsspp cheat.db not working.. new to this .. help out fam

### ISSUE THREAD

**Issue by arodjr** [hrydgard/ppsspp#7710]
Have version 1.0.1.0 on my galaxy s5. Got as far as enabling the cheats i want for the game im playing but dont know what to do from there. When i go back to the game none of them work.
Did this for dbz another road and god of war ghost of sparta.

**Comment by nfjorgebueno** [comment]
_S UCUS-98737
_G God of War: Ghost of Sparta [US]
_C1 Infinite Health
_L 0x204524BC 0x00000000
_C1 Infinite Magic
_L 0x204524C4 0x00000000
_C0 One Hit Kill
_L 0x204524C0 0x461C3C00
_C0 Normal Size
_L 0x20302F3C 0x3C043F80
_C0 Super Small Size
_L 0x20302F3C 0x3C043E80
_C0 Small Size
_L 0x20302F3C 0x3C043F00
_C0 Bigger Size
_L 0x20302F3C 0x3C043F90
_C0 Even Bigger Size
_L 0x20302F3C 0x3C043FA0
_C0 Normal Speed
_L 0x203FA2A8 0x000003E8
_C0 Super Slow Motion
_L 0x203FA2A8 0x00000140
_C0 Slow Motion
_L 0x203FA2A8 0x00000280
_C0 Quicker Game
_L 0x203FA2A8 0x000004E8
_C0 Hyper Mode
_L 0x203FA2A8 0x000006E8
_C0 Insane Speed
_L 0x203FA2A8 0x000009E8
_C0 x4
_L 0x204524B8 0x40800000
_C0 x16
_L 0x204524B8 0x41800000
_C0 x64
_L 0x204524B8 0x42800000
_C0 x128
_L 0x204524B8 0x43000000
_C0 Disable Orb Multiplier Codes
_L 0x204524B8 0x3F800000
_C0 All Skins Unlocked
_L 0x200F699C 0x10000007
_L 0x200F6A04 0x10000008
here are some cheats, many of cheat.db cheats do not work

**Comment by arodjr** [comment]
Preciate it bro

**Comment by arodjr** [comment]
Where'd you het these codes from ?

**Comment by arodjr** [comment]
*get

**Comment by nfjorgebueno** [comment]
I like sharing, searching the internet, I do not remember where I found these codes also searches forums ppsspp

**Comment by arodjr** [comment]
Alright , thanks again
