### ISSUE TITLE
tales of enternia speed problems on andriod

### ISSUE THREAD

**Issue by asbel123** [hrydgard/ppsspp#7711]
i just got new phone is huawei 730 i tried tales of enternia on it speed is better than samsung galaxy s4 19005 i see the differnce huawei using mail compare to snapdragon on samsung i think snapdragon problem.

**Comment by unknownbrackets** [comment]
Tales of Eternia does a lot of flushes in some spots, and is helped (currently) by multithreading.  We'll probably need to try a different "plan of attack" on multithreading to make a more stable feature, but ultimately the speed problems here are largely overhead / driver issues.

Closing this as it is not specifically a bug.  Performance is always something we're trying to improve.

-[Unknown]
