### ISSUE TITLE
[ios] Bluetooth handset issue

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#7714]
Report from my friend

If the game twice in a row button Square key mappings so Arrows and Triange loses effectiveness (other keys normally at this time), if the key is mapped continuously press the square button twice will return to normal

Other emulator don't have this problem

**Comment by sum2012** [comment]
He test in Windows no problem

**Comment by sum2012** [comment]
My other freind said that now IOS 8 need require external hardware devices through Apple's mfi verification.The solution may be make compatible icade verification version of IOS8
The tester asked whether he can get old version such as v0.9.9.1 version of ppsspp to test

**Comment by sum2012** [comment]
he tested v0.9.9.1-190-gbaf4655 also have problem

**Comment by unknownbrackets** [comment]
Is this still an issue with recent builds?  It sounds like this is a problem with the iCade mapping but newer iOS versions have more buttons mapped now.

-[Unknown]

**Comment by sum2012** [comment]
lost friend contract ,closing
