### ISSUE TITLE
Z.H.P Kernel Loading Savedata Error

### ISSUE THREAD

**Issue by Xaelath** [hrydgard/ppsspp#7718]
[quote]10:04:497 user_main    D[KERNEL]: HLE\sceKernelThread.cpp:3185 Context switch: Ss PlayThread -> user_main (289->276, pc: 088203d0->0885acc0, sas core) +27us
10:04:498 Ss PlayThrea D[KERNEL]: HLE\sceKernelThread.cpp:3185 Context switch: user_main -> Ss PlayThread (276->289, pc: 0885ac8c->088203d0, woke from hle delay) +240us
10:04:498 Ss PlayThrea D[SCESAS]: HLE\sceSas.cpp:528 sceSasGetAllEnvelopeHeights(08eb15c0, 167262736)
10:04:498 Ss PlayThrea D[KERNEL]: HLE\sceKernelSemaphore.cpp:304 sceKernelSignalSema(290, 1) (count: 0 -> 1)
10:04:498 Ss PlayThrea D[AUDIO]: HLE\sceAudio.cpp:167 sceAudioOutputPanned(00000004, 00008000, 00008000, 09f2dd40)
10:04:498 Ss PlayThrea D[KERNEL]: HLE\sceKernelThread.cpp:2596 sceKernelDelayThreadCB(1000 usec)
10:04:498 user_main    D[KERNEL]: HLE\sceKernelThread.cpp:3185 Context switch: Ss PlayThread -> user_main (289->276, pc: 08a06bd8->0885ac8c, thread delayed) +26us
10:04:498 Atrac3 Play  D[KERNEL]: HLE\sceKernelThread.cpp:3185 Context switch: user_main -> Atrac3 Play Thread (276->286, pc: 0885acc0->08a07720, thread delay finished) +15us
10:04:498 Atrac3 Play  D[AUDIO]: HLE\sceAudio.cpp:167 sceAudioOutputPanned(00000005, 00000000, 00000000, 09f91a80)
10:04:498 Atrac3 Play  D[KERNEL]: HLE\sceKernelThread.cpp:2596 sceKernelDelayThreadCB(500 usec)
10:04:498 user_main    D[KERNEL]: HLE\sceKernelThread.cpp:3185 Context switch: Atrac3 Play Thread -> user_main (286->276, pc: 08a07720->0885acc0, thread delayed) +21us
10:04:498 Atrac3 Play  D[KERNEL]: HLE\sceKernelThread.cpp:3185 Context switch: user_main -> Atrac3 Play Thread (276->286, pc: 0885acc0->08a07720, thread delay finished) +510us
10:04:498 Atrac3 Play  D[AUDIO]: HLE\sceAudio.cpp:167 sceAudioOutputPanned(00000005, 00000000, 00000000, 09f91a80)
10:04:498 Atrac3 Play  D[KERNEL]: HLE\sceKernelThread.cpp:2596 sceKernelDelayThreadCB(500 usec)
10:04:498 user_main    D[KERNEL]: HLE\sceKernelThread.cpp:3185 Context switch: Atrac3 Play Thread -> user_main (286->276, pc: 08a07720->0885acc0, thread delayed) +21us
10:04:498 Ss PlayThrea D[KERNEL]: HLE\sceKernelThread.cpp:3185 Context switch: user_main -> Ss PlayThread (276->289, pc: 0885ac78->08a06bd8, thread delay finished) +441us
10:04:498 Ss PlayThrea D[AUDIO]: HLE\sceAudio.cpp:167 sceAudioOutputPanned(00000004, 00008000, 00008000, 09f2dd40)
10:04:498 Ss PlayThrea D[KERNEL]: HLE\sceKernelThread.cpp:2596 sceKernelDelayThreadCB(1000 usec)
10:04:498 user_main    D[KERNEL]: HLE\sceKernelThread.cpp:3185 Context switch: Ss PlayThread -> user_main (289->276, pc: 08a06bd8->0885ac78, thread delayed) +21us
10:04:498 Atrac3 Play  D[KERNEL]: HLE\sceKernelThread.cpp:3185 Context switch: user_main -> Atrac3 Play Thread (276->286, pc: 0885ac78->08a07720, thread delay finished) +47us
10:04:498 Atrac3 Play  D[AUDIO]: HLE\sceAudio.cpp:167 sceAudioOutputPanned(00000005, 00000000, 00000000, 09f91a80)
10:04:498 Atrac3 Play  D[KERNEL]: HLE\sceKernelThread.cpp:2596 sceKernelDelayThreadCB(500 usec)
10:04:498 user_main    D[KERNEL]: HLE\sceKernelThread.cpp:3185 Context switch: Atrac3 Play Thread -> user_main (286->276, pc: 08a07720->0885ac78, thread delayed) +21us
10:04:499 Atrac3 Play  D[KERNEL]: HLE\sceKernelThread.cpp:3185 Context switch: user_main -> Atrac3 Play Thread (276->286, pc: 0885ac78->08a07720, thread delay finished) +510us
10:04:499 Atrac3 Play  D[AUDIO]: HLE\sceAudio.cpp:167 sceAudioOutputPanned(00000005, 00000000, 00000000, 09f91a80)
10:04:499 Atrac3 Play  D[KERNEL]: HLE\sceKernelThread.cpp:2596 sceKernelDelayThreadCB(500 usec)
10:04:499 user_main    D[KERNEL]: HLE\sceKernelThread.cpp:3185 Context switch: Atrac3 Play Thread -> user_main (286->276, pc: 08a07720->0885ac78, thread delayed) +21us
10:04:499 Ss PlayThrea D[KERNEL]: HLE\sceKernelThread.cpp:3185 Context switch: user_main -> Ss PlayThread (276->289, pc: 0885ac78->08a06bd8, thread delay finished) +410us
10:04:499 Ss PlayThrea D[AUDIO]: HLE\sceAudio.cpp:167 sceAudioOutputPanned(00000004, 00008000, 00008000, 09f2dd40)
10:04:499 Ss PlayThrea D[KERNEL]: HLE\sceKernelThread.cpp:2596 sceKernelDelayThreadCB(1000 usec)
10:04:499 user_main    D[KERNEL]: HLE\sceKernelThread.cpp:3185 Context switch: Ss PlayThread -> user_main (289->276, pc: 08a06bd8->0885ac78, thread delayed) +21us
10:04:499 Atrac3 Play  D[KERNEL]: HLE\sceKernelThread.cpp:3185 Context switch: user_main -> Atrac3 Play Thread (276->286, pc: 0885acc0->08a07720, thread delay finished) +78us
10:04:499 Atrac3 Play  D[AUDIO]: HLE\sceAudio.cpp:167 sceAudioOutputPanned(00000005, 00000000, 00000000, 09f91a80)
10:04:499 Atrac3 Play  D[KERNEL]: HLE\sceKernelThread.cpp:2596 sceKernelDelayThreadCB(500 usec)
10:04:499 user_main    D[KERNEL]: HLE\sceKernelThread.cpp:3185 Context switch: Atrac3 Play Thread -> user_main (286->276, pc: 08a07720->0885acc0, thread delayed) +21us
10:04:499 Atrac3 Play  D[KERNEL]: HLE\sceKernelThread.cpp:3185 Context switch: user_main -> Atrac3 Play Thread (276->286, pc: 0885acc0->08a07720, thread delay finished) +510us
10:04:499 Atrac3 Play  D[AUDIO]: HLE\sceAudio.cpp:167 sceAudioOutputPanned(00000005, 00000000, 00000000, 09f91a80)
10:04:499 Atrac3 Play  D[KERNEL]: HLE\sceKernelThread.cpp:2596 sceKernelDelayThreadCB(500 usec)
10:04:499 user_main    D[KERNEL]: HLE\sceKernelThread.cpp:3185 Context switch: Atrac3 Play Thread -> user_main (286->276, pc: 08a07720->0885acc0, thread delayed) +21us
10:04:499 Ss PlayThrea D[KERNEL]: HLE\sceKernelThread.cpp:3185 Context switch: user_main -> Ss PlayThread (276->289, pc: 0885ac78->08a06bd8, thread delay finished) +378us
10:04:499 Ss PlayThrea D[AUDIO]: HLE\sceAudio.cpp:167 sceAudioOutputPanned(00000004, 00008000, 00008000, 09f2dd40)
10:04:500 Ss PlayThrea D[KERNEL]: HLE\sceKernelThread.cpp:2596 sceKernelDelayThreadCB(1000 usec)
10:04:500 user_main    D[KERNEL]: HLE\sceKernelThread.cpp:3185 Context switch: Ss PlayThread -> user_main (289->276, pc: 08a06bd8->0885ac78, thread delayed) +21us
10:04:500 Atrac3 Play  D[KERNEL]: HLE\sceKernelThread.cpp:3185 Context switch: user_main -> Atrac3 Play Thread (276->286, pc: 0885ac78->08a07720, thread delay finished) +109us
10:04:500 Atrac3 Play  D[AUDIO]: HLE\sceAudio.cpp:167 sceAudioOutputPanned(00000005, 00000000, 00000000, 09f91a80)
10:04:500 Atrac3 Play  D[KERNEL]: HLE\sceKernelThread.cpp:2596 sceKernelDelayThreadCB(500 usec)
10:04:500 user_main    D[KERNEL]: HLE\sceKernelThread.cpp:3185 Context switch: Atrac3 Play Thread -> user_main (286->276, pc: 08a07720->0885ac78, thread delayed) +21us
10:04:500 user_main    D[DISP]: HLE\sceDisplay.cpp:611 Enter VBlank 1669
10:04:500 idle0        D[KERNEL]: HLE\sceKernelThread.cpp:3185 Context switch: user_main -> idle0 (276->272, pc: 0885ac78->08000000, interrupt) +433us
[/quote]
No idea why..

**Comment by sum2012** [comment]
Can you upload the save into  http://drive.google.com/ ?

**Comment by Xaelath** [comment]
https://drive.google.com/file/d/0B_0saQEB0kYKbG5ZTmc1bThYaGs/view?usp=sharing
its the data.bin
i cannot upload folder..

**Comment by sum2012** [comment]
Please zip the folder first

**Comment by Xaelath** [comment]
https://drive.google.com/file/d/0B_0saQEB0kYKTW9TMFhfeGZKOHc/view?usp=sharing
Here you go.

**Comment by sum2012** [comment]
I test on real PSP.
It show "Load failed.The data is corrupted".
@unknownbrackets said that
PPSSPP currently doesn't support save that run on 6.20 firmware that were hacked to run on 5.50 firmware

**Comment by Xaelath** [comment]
so do you mean i cant play it on ppsspp?
or the data is corrupted due hack or error?

**Comment by sum2012** [comment]
Just do not use that save.Play from beginning

**Comment by unknownbrackets** [comment]
It sounds like the issue here is a hacked firmware save.  Since this happens on a real PSP, our behavior is correct.  Maybe someone (even the CFW author?) can write a utility to fix the broken savedata - unfortunately it's hard for us to detect it's broken.  It always turns into gibberish for PPSSPP, only the game can tell if it makes sense.

-[Unknown]
