### ISSUE TITLE
Debugger request

### ISSUE THREAD

**Issue by Scorpeg** [hrydgard/ppsspp#7720]
Please, could anyone (Kingcom?) add possibility to do a conditional breakpoint if some memory value = X. So add some command like MB(0x8000000)/MW(0x8000000)/MH(0x8000000) [means memory_byte, memory_word, memory_halfword]. So to be able to stop when some value in some memory = some known value. It is very important feature for any debugger, by me.

**Comment by unknownbrackets** [comment]
This is already possible, using brackets.  So you do `[0x12345678]` for words, and I think `2,[0x12345678]` for halfwords (I have not actually used the sizes ever myself... not certain of syntax.)

Also, labels should be supported too, I believe.

Please comment if there are problems.

-[Unknown]
