### ISSUE TITLE
Texture glitch in Dan Ball Senki W

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#7722]
1. the "west gate station" texture is not drawn correct.it's missing the "west" part.and those texture look different between hardware transform on and off.
   hardware transform on
   ![01](https://cloud.githubusercontent.com/assets/3481559/7425444/694d7628-efe3-11e4-8d11-0e4e931a3b80.png)

hardware transform off
![02](https://cloud.githubusercontent.com/assets/3481559/7425445/6952413a-efe3-11e4-8304-435792bbad6d.png)

PSP
![201505010841_001](https://cloud.githubusercontent.com/assets/3481559/7425446/7dedfd0a-efe3-11e4-827b-62b8f9c5d0be.png)

"west gate station" texture drawn in GE debugger.
![03](https://cloud.githubusercontent.com/assets/3481559/7425457/a5ef6b5e-efe3-11e4-8e6b-87efdfb872fb.png)
more tabs
https://gist.github.com/daniel229/2065d6dc11cd58956068

2.the texture of the bottom right flickers with hardware transform on since https://github.com/hrydgard/ppsspp/commit/171629ba4824136539d7ba33ab241c0790e6b8f3
a video for the flickering(rename jpg to mp4)
![danball senki w](https://cloud.githubusercontent.com/assets/3481559/7425532/04df2644-efe5-11e4-8456-a3f5aa930049.jpg)

GE debugger
![04](https://cloud.githubusercontent.com/assets/3481559/7425499/8439a9f6-efe4-11e4-9dfa-a83f8663345a.png)
more tabs
https://gist.github.com/daniel229/e52f5c116de0a1c028d1

**Comment by Bigpet** [comment]
are you sure this didn't happen before https://github.com/hrydgard/ppsspp/commit/171629ba4824136539d7ba33ab241c0790e6b8f3 ? Because that looks like Z-flickering which I would expect to look a little different depending on whether the float math was done on the CPU or the GPU

**Comment by unknownbrackets** [comment]
In both cases using >= as a depth test, could definitely be z-fighting.

-[Unknown]

**Comment by daniel229** [comment]
The flickering start from the commit "Separate fbo resize logic from creation."
The commit "Oops, fix stencil upload at non-1x resolutions." and Merge pull request #6240 from pal1000/work did not happen.
even older build did not happen.
![05](https://cloud.githubusercontent.com/assets/3481559/7425770/ec2dabc0-efe9-11e4-911e-4bc9d574e851.png)

**Comment by unknownbrackets** [comment]
Does it happen both at 1x and at 2x?

-[Unknown]

**Comment by daniel229** [comment]
Also happen in 1x and 2x .But it stop flickering after coming back from pause menu or changing resolution or changing rendering mode.

**Comment by Bigpet** [comment]
so, what exactly changed here, the only thing I can see on first blush is that before it would upon resize set all these values here: https://github.com/hrydgard/ppsspp/commit/171629ba4824136539d7ba33ab241c0790e6b8f3#diff-29313f9f6ed28d0e24e6dac4e0db8933L831 but now it would not enter that if branch. Just not sure if these things like `z_address` and `z_stride` would even differ ever

**Comment by unknownbrackets** [comment]
Has anything improved with the depth rounding?  Most notably 1?

Yeah, that commit shouldn't have changed much, but might've affected when it resizes or how it blits from a resize.  If coming back form the pause menu stops the flicker, it means to me that it's a problem with the size of one of the framebuffers.

When switching to/from the pause menu, it should list "destroyed" and "created" framebuffers - can you paste that?  I'm wondering if any are destroyed at different sizes than they are created, or if some are destroyed and never recreated.

I could be remembering wrong, it wasn't the primary goal of the commit, which was just to make the logic clearer and avoid unintended side effects when resizing.

-[Unknown]

**Comment by unknownbrackets** [comment]
Any improvement here with depth rounding / per pixel depth?

Also, I'm thinking the the depth blitting could be a factor here.

-[Unknown]

**Comment by daniel229** [comment]
It draws more than before,still missing some.
![3](https://cloud.githubusercontent.com/assets/3481559/12527831/474e69f8-c1be-11e5-9473-f2984ac110eb.png)

**Comment by unknownbrackets** [comment]
Interesting.  Is the flickering gone?

If you use this change:
https://github.com/hrydgard/ppsspp/pull/8475#issuecomment-173948124

It will force it to have a wider depth range.  I'm wondering if that could be the problem here, since it got better, but not completely better.

-[Unknown]

**Comment by daniel229** [comment]
Yes,the flickeing is gone.
That chang does not help,seems no difference.
![7](https://cloud.githubusercontent.com/assets/3481559/12527886/6aae0424-c1c0-11e5-92b4-c92edbb4006b.png)

**Comment by unknownbrackets** [comment]
Hmm.  It's still wrong in both hw and sw transform, right?  Sounds like it might be the same wrong, though, at least?

How bad does it look in the software renderer?  Just wondering if that has the same glitch or not.  Probably it doesn't draw it right at all...

-[Unknown]

**Comment by daniel229** [comment]
both hw and sw transform are wrong.
Software renderer looks perfect.
![8](https://cloud.githubusercontent.com/assets/3481559/12527962/8b92763c-c1c2-11e5-9eca-2cf3cca09308.png)

**Comment by DanSenki** [comment]
I assume this thread is more active/have more people replying.

It's worth noting that PPSSPP version 1.0.1 has glitches with DSW while
![npjh50618_00000](https://cloud.githubusercontent.com/assets/15371521/13905782/bb8e81c8-ee86-11e5-9161-dc773b174eea.jpg)

PPSSPP 1.2.1 has less graphic glitches.
![npjh50618_00000](https://cloud.githubusercontent.com/assets/15371521/13905788/ef147e94-ee86-11e5-815b-aa7e26e9b105.jpg)

Still has cutscene issues, and a graphical glitch in the dialogue in some point but overall, it's all fine.

**Comment by DanSenki** [comment]
//double post

Also worth noting BOOST glitches for some reason

**Comment by unknownbrackets** [comment]
I suspect a lot of these issues have been fixed - I wonder if some of it was related to flat lighting issues, like Blade Dancer.

A frame dump would help for any of these issues that are still happening.  Since there haven't been any new ones for 4 years, I'm going to close this hoping it's resolved now.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
