### ISSUE TITLE
Tales of Eternia main menu 'customize' option submenu corrupts background texture

### ISSUE THREAD

**Issue by i30817** [hrydgard/ppsspp#7723]
Framebuffer cpu shenanigans?

**Comment by daniel229** [comment]
Any picture showing for us?

**Comment by i30817** [comment]
![screenshot from 2015-05-02 09 33 32](https://cloud.githubusercontent.com/assets/757900/7440476/661cf0d4-f0ae-11e4-9e11-12391bbd7072.png)

**Comment by daniel229** [comment]
What kind of the device and which version of PPSSPP are you using,it'd better to try the latest build downloaded from http://buildbot.orphis.net/ppsspp/index.php (if you are on android or windows) and with default setting.It looks good to me.
![01](https://cloud.githubusercontent.com/assets/3481559/7440533/5ca356b6-f0ee-11e4-82b0-5367c0d0c942.png)

**Comment by i30817** [comment]
I'm on git head. I recently nuked my settings so nothing is changed from defaults.

I'm on opengl 3.0 on mesa 10.3.2 on some ancient mobile 64 bits from 2008 using the Gallium Driver 0.4 on AMD RV710

There is a lot of info on the dev menu of the emulator but no way to paste it to clipboard so i'm not going to type no more.

**Comment by daniel229** [comment]
Seems like a driver problem.

**Comment by asbel123** [comment]
dont worry about it get samsung galaxy s6 edge it works perfect for tales of enternia u wont get grapichal problems it works perfect i put 5x resoultion no slow down and 2x scale better than pc 0 glitches. amd has lots driver problem just get samsung galaxy s6 edge beacuse works final fantasy 7 crisis core full speed no glitches i put 5x resoultion on it no slow down this is best andriod phone now.

**Comment by unknownbrackets** [comment]
I wonder if this is related to the similar issue we saw with GL_PACK_ROW_LENGTH defaulting unexpectedly to a non-zero value.  It certainly looks like that.

Has this improved in the latest git build?

-[Unknown]

**Comment by i30817** [comment]
Seems fixed.
