### ISSUE TITLE
Pinning a iso directory doesn't save

### ISSUE THREAD

**Issue by i30817** [hrydgard/ppsspp#7724]
I had to change another setting before quitting and starting the emulator showed the pinned directory by default instead of ~

**Comment by unknownbrackets** [comment]
How are you exiting the emulator?

-[Unknown]

**Comment by i30817** [comment]
Esc and clicking exit.

**Comment by i30817** [comment]
Yeah, it's either not working or i'm using it wrong.

1. started emulator with ~/Documents/projects/ppsspp/PPSSPPSDL --fullscreen
2. went to the 'games' tab that has the pin (funny enough this IS remembering the games dir, but not because of being 'pinned' - which i think is supposed to do this - but for another reason. Maybe starting the last game there.
3. click the 'arrow up' and click '+' to pin the parent dir
4. exit
5. start again, with ~/Documents/projects/ppsspp/PPSSPPSDL --fullscreen again
6. games tab is in the previous dir game (no parent) dir, unpinned (both unpinned actually).

**Comment by unknownbrackets** [comment]
Oh, okay, this is caused by the "faster exit" hack on Linux and Mac.  I'm not sure I see where Android is calling shutdown either.

-[Unknown]

**Comment by unknownbrackets** [comment]
Is this still a problem in the latest git build?

-[Unknown]

**Comment by i30817** [comment]
Fixed now. And as a bonus, i finally figured out what 'pin' does doh.

**Comment by unknownbrackets** [comment]
Heh, I think a thumbtack icon would make it clearer.  The +/- was always sorta placeholder.  But I don't hate anyone enough to subject them to my artistic skill.

-[Unknown]
