### ISSUE TITLE
My save data wont work

### ISSUE THREAD

**Issue by JhonN12** [hrydgard/ppsspp#7726]
ok so i downloaded Dbz renkaichi tag team iso 5 times from different places and everytime i try to put save data it says "save data failed" or "couldnt save, disk is full" i have an LG optimus I90, any ideas with whats wrong?

**Comment by JhonN12** [comment]
*dbz tenkaichi tag team

**Comment by unknownbrackets** [comment]
Sorry, but piracy isn't the way forward.  If you downloaded it, maybe it was hacked or something.  Anyway, disk full means... disk full.  So sounds like this isn't a bug in any case.  Maybe you should post on the forum after buying the game.

-[Unknown]

**Comment by JhonN12** [comment]
i figured out what i did wrong, i feel so stupid now, i had deleted the psp folder so it didnt have anywhere to save the data into, but i restarted my phone and now it works
