### ISSUE TITLE
Resolution incorrect when building with Qt 5.4.1

### ISSUE THREAD

**Issue by zhykzhykzhyk** [hrydgard/ppsspp#7729]
![image](https://cloud.githubusercontent.com/assets/3477952/7453106/5da999fc-f298-11e4-90b4-8a9e275445f6.png)

The grid system inside QGLWidget is different from the outside when devicePixelRatio is not 1.0.

**Comment by unknownbrackets** [comment]
Does this still occur?  I think we made some improvements to sizing in general.

-[Unknown]

**Comment by zhykzhykzhyk** [comment]
Uses mac, not linux. Still occurs on head.
![image](https://cloud.githubusercontent.com/assets/3477952/12939893/36f918ec-cfff-11e5-9436-60d45035091c.png)
