### ISSUE TITLE
Recent games tab losing contents on exit

### ISSUE THREAD

**Issue by keirlawson** [hrydgard/ppsspp#7730]
Using PPSSPP 1.0 on my LG G3 running Lollipop the recent games tab is always empty when I boot up the emulator.

**Comment by vsub** [comment]
If you have per game settings,try the latest beta(there was a bug related to this)

**Comment by hrydgard** [comment]
@keirlawson does this still happen in the latest builds?

**Comment by keirlawson** [comment]
Still have this issue with v1.0.1-2632-gdc4fb4c, games are sitting on my SD card which could be the issue?

**Comment by hrydgard** [comment]
Very strange. I can't see how this can possibly happen... 

@keirlawson If you play a couple of games, what does the [Recent] section in /PSP/SYSTEM/ppsspp.ini look like on your device?

**Comment by unknownbrackets** [comment]
I know we had a bug on Linux related to saving the ini during certain methods of exit.  It might've been related.

Any update here with the latest git build?

-[Unknown]

**Comment by unknownbrackets** [comment]
We've made changes which might've fixed this, as mentioned above.  No feedback in a while, so closing - but if there's more information or it's happening with the latest git build, feel free to comment and we'll reopen.

-[Unknown]

**Comment by G-Rath** [comment]
I've got what seems to be the same issue: Xiaomi: Redmi Note 3, v1.4-2-g648bc5d.

I've also got my games on my sd card - Whenever I open PPSSPP it always opens to /storage/emulated/0/ and my recent games list is empty.

All my save states, configuration and other such information is there. And it's only when I force close the application and then re-open it (i.e *not* just via resume from suspension).

**Comment by unknownbrackets** [comment]
Reopening.  Can you try the latest git build?

-[Unknown]

**Comment by unknownbrackets** [comment]
Have you experienced this in the latest git builds or 1.5.4?

-[Unknown]

**Comment by leopard20** [comment]
Looks to be the inverse of my problem! https://github.com/hrydgard/ppsspp/issues/11131

Though if you quit the game properly, it should save it to the Recents. I guess you should've asked them if they did this right before they bailed! :)

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
