### ISSUE TITLE
Texture Graphic Bug on Aya Character in The 3rd Birthday

### ISSUE THREAD

**Issue by zminhquanz** [hrydgard/ppsspp#7735]
![the 3rd birthday](https://cloud.githubusercontent.com/assets/11285640/7548435/b042d03c-f632-11e4-84ce-a71f5370a4dc.png)

When i'm overdive to kill Monster in game , and it have texture graphic glitch on Aya Character

**Comment by daniel229** [comment]
Is "Disable slower effects" checked? If so, just uncheck it.

**Comment by zminhquanz** [comment]
oh , I will try this :+1:

**Comment by zminhquanz** [comment]
![123456](https://cloud.githubusercontent.com/assets/11285640/7550785/a849b050-f699-11e4-93b5-913de68ed4b8.png)
![Uploading The 3rd Birthday.png…]()
So , I have untick Disable Slower Effect , it the problem does not fix it

**Comment by daniel229** [comment]
Overdive looks fine here.Did you try default setting and start from new game or game save,not savestate.And which video do you have?

**Comment by zminhquanz** [comment]
uh , I have config before i have play this game , can you check this problem i have

**Comment by zminhquanz** [comment]
i don't have start with save states

**Comment by zminhquanz** [comment]
oh, i see it problem , I have turn on multithread in System and it have bugs
