### ISSUE TITLE
Software Skinning Artifacts

### ISSUE THREAD

**Issue by ShadowsWarrior** [hrydgard/ppsspp#7746]
it seems like whenever the software skinning is active 
this game ( Shadow Of Destiny ) shows artifacts
when disabled the artifacts are gone as shown in screenshots
however disable of software skinning does not solve the problem
as it cause major slow down and lags in the game 
using  latest v.1.0.1-468-g5d0d671

with software skinning 
![ulus10459_00001](https://cloud.githubusercontent.com/assets/12467387/7663781/d587336e-fb79-11e4-9d56-fab14c816a7e.jpg)

without software skinning
![ulus10459_00002](https://cloud.githubusercontent.com/assets/12467387/7663783/e526b290-fb79-11e4-8b91-7337989a2bd4.jpg)

by the way great work on the emulator
been watching progress since it was first out 
it's made great progress and nearly perfect
great work

**Comment by unknownbrackets** [comment]
Hmm, I thought this was related to morphin and was already fixed.  Can you share savedata or a savestate that reproduces the issue quickly?  I have this game but haven't really ever played it.

It used to be the intro had really bad artifacts and I'm sure those were fixed, at least they were.

-[Unknown]

**Comment by ShadowsWarrior** [comment]
sorry for late reply 
actually the artifacts can be seen in all characters 
it starts out as you run near characters from distance with line artifact
connecting you and the other characters's head or eyes 
then when you get close enough the artifacts show on heads only 
as in pictures 
here is a pic of what i mean of line artifact

![ulus10459_00004](https://cloud.githubusercontent.com/assets/12467387/7668627/a82671b4-fc4b-11e4-8358-7f2710911f17.jpg)

and here is the savestate it was too big to upload here 19mb 
i uploaded on 4shared

http://www.4shared.com/file/6_3D6zWkce/ULUS10459_100_0.html

**Comment by unknownbrackets** [comment]
Okay, I see the cause.  I guess this was never fully fixed, because the intro works fine and that's all I tested before.  Maybe no one tested further into the game then...

The issue is simple.  FastLoadBoneMatrix() and friends skip flushing and dirtying the matrix in software skinning, since the matrix is used on the cpu.  If morphing is enabled, it will flush anyway.  Seems legit, right?

Except, the matrix is still not dirtied.  So it's still using a wrong (old) matrix at this point.

-[Unknown]

**Comment by ShadowsWarrior** [comment]
i have no idea what you talking about 
you're the developer am just the annoying guy with issue lol 
good work though
