### ISSUE TITLE
Volume Control for MAC version

### ISSUE THREAD

**Issue by superkhau** [hrydgard/ppsspp#7749]
Is there a way to control the volume for the MAC version of PPSSPP? Like an audio menu adjuster of some sort?

**Comment by thedax** [comment]
Not as far as I know, no. The volume adjustment stuff was removed a while back.

**Comment by superkhau** [comment]
Thanks for the response. +1 for OSX in-app volume support. ;)

**Comment by ivawzh** [comment]
+1

**Comment by MikeRavenelle** [comment]
Was there a reason the volume control was removed? Just curious before I look into adding it for OS X. It is annoying since OS X does not have a program volume mixer.

**Comment by hrydgard** [comment]
Yeah, I've realized that it would be quite useful on some platforms like the mac. It's coming back soon.

**Comment by unknownbrackets** [comment]
Let's just not add back the separate volume controls which won't work anyway.

-[Unknown]

**Comment by hrydgard** [comment]
Right, I didn't intend to.

**Comment by superkhau** [comment]
Can you release 1.2.0? It's not on the ppsspp website.

**Comment by hrydgard** [comment]
This weekend.

**Comment by superkhau** [comment]
@hrydgard Thanks! ;)

**Comment by superkhau** [comment]
Ping

**Comment by superkhau** [comment]
@hrydgard TY, it works great. ;)
