### ISSUE TITLE
Rotation screen ????

### ISSUE THREAD

**Issue by brujo5** [hrydgard/ppsspp#7754]
Rotation screen work perfect, but why touch control no autorotate for example portrait mode??

![image](https://cloud.githubusercontent.com/assets/4172898/7728840/a71d828c-fece-11e4-8227-442d2c2edb9d.jpg)

**Comment by hrydgard** [comment]
If you want the controls to rotate on your phone, use actual portrait mode in System settings. The point of the new screen rotation is to be able to play vertical shooters correctly with normal controls.

**Comment by brujo5** [comment]
Thank
