### ISSUE TITLE
[iOS] Sometimes unable to scroll in UI menus

### ISSUE THREAD

**Issue by angelXwind** [hrydgard/ppsspp#7757]
PPSSPP on iOS will sometimes suddenly refuse to scroll in the menus.

Unfortunately, I do not yet have a way to easily reproduce this bug, but perhaps someone else here has?

I believe it may be related to either receiving a notification and interacting with it (such as MobileSMS("Messages")'s actionable notifications) or receiving a phone/FaceTime call.

But I'm reporting it just to make it known.

**Comment by hrydgard** [comment]
Might be another "down-flag" getting stuck, similarly to 7758, but I'm not quite sure how it can happen and not resolve itself after a scroll attempt..

**Comment by angelXwind** [comment]
@hrydgard You are correct — this bug is caused by #7758. The "version 2" reproduction steps will also reproduce this bug, but there is no way to restore scroll functionality short of completely exiting the app.

That being said, I'm working on a fix to #7758's root problem, killing 2 birds with 1 stone.

**Comment by angelXwind** [comment]
@hrydgard Interesting — I fixed #7758, but the unable-to-scroll bug still happens. I think I'll submit the pull request that fixes #7758 first.

**Comment by angelXwind** [comment]
@hrydgard Reopen this issue, it's not yet fixed :P
