### ISSUE TITLE
[iOS] On-screen controls will stick if input is taken away from the game view

### ISSUE THREAD

**Issue by angelXwind** [hrydgard/ppsspp#7758]
Unable to test this on Android as I do not currently have my Android device with me.

On iOS, PPSSPP's on-screen controls will stick if input is taken away from the game view.

There are versions of this bug, one slightly more severe than the other.

How to reproduce ("version" 1):

1. Begin emulation
2. Hold down any button
3. Go to the menu
4. Resume emulation
5. The button you held is now stuck until you tap it again

How to reproduce ("version" 2):

1. Begin emulation
2. Hold down any button
3. Press the home button (or enter the app switcher by double-tapping home) — I believe the same thing also happens if you receive a phone/FaceTime call while having a button held down
4. Return to PPSSPP
5. The button you held is now stuck, and tapping it again won't do anything
6. In order to "un-stick" the button, you must enter the menu, resume emulation, THEN tap the button.

**Comment by hrydgard** [comment]
1 reproduces easily even on Windows, good find, I will have a look.

As for 2 I have no idea how we currently handle loss of app focus but I guess I will have to set up an iOS environment again ... Do you find this to be a major annoyance? I guess the call receiving thing might be a pain..

**Comment by hrydgard** [comment]
That takes care of 1, and also 2 on Windows. To fix 2 on iOS we need to do a NativeMessageReceived("lost_focus", "") from the appropriate place.

**Comment by Fadi5555** [comment]
Guys
Please can anyone how fix this bug on ios of ppsspp.
This bug is really making games boring.
The bug is on ps3/4 controller.
Actually every buttons works great but the right analog stick (down and left) not response at all. I really like your project and it is updating daily.
Please fix this issue.
This bug makes iOS version of ppsspp looking so sad.
Please it's small bug need to fix.

We all here to tell you what is the issues about your amazing project

**Comment by angelXwind** [comment]
@Fadi5555: That sounds like a separate issue. I'd advise filing a new issue ticket at https://github.com/hrydgard/ppsspp/issues/new

@hrydgard: I'll take a look at fixing this bug ("version 2") later today since I have some free time. I think I know what the issue is.

**Comment by Fadi5555** [comment]
@angelXwind please i think you know about this bug. because some users here talk about it.

Please can make a fix for it.
Specially it was for long time without fix

I tell you here because i found you here.
Please fix this bug for iOS version.
I really would be a grateful.

**Comment by angelXwind** [comment]
@Fadi5555 I actually have no idea what you're talking about — I don't use controllers when using PPSSPP on iOS, nor do I have a DualShock controller ;_;.

The right analog stick is not supposed to work because the PSP doesn't *have* a right analog stick. Though if you really want to, you can bind the right analog stick to the left one in the control settings if you so desire (for whatever reason).

Unless if this is some new bug? If it is, then you have to describe it in further detail, because I really have no idea what you're trying to say here.

Also, make a new issue ticket: https://github.com/hrydgard/ppsspp/issues/new

**Comment by Fadi5555** [comment]
@angelXwind I'm really happy to see that.
Thank you so much for trying to fix that bug.

Waiting for the deb fixed bulid to test it and give you my own report about that.

**Comment by Fadi5555** [comment]
@angelXwind I'm still waiting for the fixed deb bulid to see it.

Please keep your doing up.
Best of luck.
