### ISSUE TITLE
a Bug on iOS ppsspp need to fix (about PS3 controller buttons)

### ISSUE THREAD

**Issue by Fadi5555** [hrydgard/ppsspp#7762]
Hi all

The iOS version of ppsspp has a bug on PS3/4 controller buttons
This bug was not found on ios7 is start when I updated my iPad on iOS 8

All buttons works great except right analog stick only two buttons they are (left and down)
Also on android version all buttons on PS3 controller works great including right analog.

This is a image for more details.
![image](https://cloud.githubusercontent.com/assets/10546081/7778151/78962a86-00d1-11e5-9f58-88ca59828fd2.jpg)

Please make fix for it.

**Comment by angelXwind** [comment]
http://puu.sh/hZ3si/56fd195afb/ppssppbuildbot-org.ppsspp.ppsspp-0v1.0.1-496-gded92aa-1-dualshocktest-ios-fat.deb

Download this DEB file and install it — it should, in theory, fix the issues with the right analog stick on the DualShock controllers.

**Comment by Fadi5555** [comment]
Ok I'll test it now

**Comment by Fadi5555** [comment]
@angelXwind I download the file and try to installed through I file but I got an error

This is the picture of error
![image](https://cloud.githubusercontent.com/assets/10546081/7789551/1ccd5280-026e-11e5-944a-ef22321b6076.jpg)
Any solution for that?

I say if you can put this version on cydia like always
It'll be easier to install and test it.

**Comment by angelXwind** [comment]
Oh, oops. Accidentally created the DEB incorrectly. I'll give you another one in a bit.

**Comment by Fadi5555** [comment]
Ok I'll waiting for another one

**Comment by angelXwind** [comment]
This one should work http://puu.sh/hZ9WS/8df78de03b/ppssppbuildbot-org.ppsspp.ppsspp-0v1.0.1-496-gded92aa-1-dualshocktest-ios-fat.deb

**Comment by Fadi5555** [comment]
@angelXwind wow you are rock
The problem was solved.
Finally we can join to play.
Thank you so much for fixing that bug.

**Comment by angelXwind** [comment]
Thanks for testing. Submitting pull request.

I actually ended up writing my own fix for this (basically just treat the second analog stick the same way the left analog stick is treated).

**Comment by Fadi5555** [comment]
@angelXwind you can't imagine how i feel now.
Very happy with fix this horrible bug.
The playing now is much more comfortable. I if you want to try with controller. Believe me it would gives you a console experience.

Well now i have three questions if don't mind to answer. I know you are so kind as well as doing a big fever for us as ios user to fix that bug the right stick.

So my questions are:

1-tomb raider anniversary when i rolling up the framerate slow down and keep with slow speed. Even if i play without rolling it still with fullspeed but if start to rolling the speed slow down how can fix that?

2-i really like the homebrew which called (pspkvm) but I can't get run normally only if i run it it run for second after that is stock (freeze) however I saw on YouTube some people run it without any problems
Please tell me if you have that amazing homebrew. What is the settings that you doing on? If you don't have please download it and see what is the problem about it. This is important homebrew to me (it's to play jar files games)

3-can you make a port of dolphin emu on ios? I know you're interested in iOS improvement. Actually the creator of dolphin said he gonna help anyone to release iOS port of dolphin if he see the person who are interested in with dolphin.
Please just imagine. You as a professional of iOS. You could run resident evil 4 on your idevice. I'm sure if it released it could run more smoothly more than android port.

Please forgive if I make it so long my questions.

I asked that because you're so kind and professional as well. It's start from you to fix that bug.

That's all. Thanks again.
And keep your doing up
