### ISSUE TITLE
[Android] Screen resolution incorrect/blurriness?

### ISSUE THREAD

**Issue by xperia64** [hrydgard/ppsspp#7764]
In some recent build (can't remember which), the default resolution when a game is first booted appears incorrect. After the in game PPSSPP menu is accessed, it looks correct again. It's hard to tell, but either the resolution is lower, or it's slightly blurrier? Here are two screenshots, first before opening the menu, then after: http://imgur.com/VqpqDyz,KK9OiWu
It's more noticeable on a QHD screen. And the display is set to Auto (1:1) with hardware scaler set to native device resolution.

**Comment by asbel123** [comment]
which phone u using now  and which firmware u on now to. i can help u.

**Comment by xperia64** [comment]
It occurs on my LG G3 (5.0.1) and Shield Tablet (5.1).

**Comment by asbel123** [comment]
i used samsung galaxy s6 edge i have to put 5x resloution and 5x hardware scaler i never use auto it works perfect final fantasy 7 crisis core higest resloution and i put 2x upscale made the game higher deatil on ppsspp no slow down. try put 2 upscale if want high res. if want to fix thats problem use native hardware scaler it will fix the problem.

**Comment by xperia64** [comment]
Found something interesting in the logs. The created FBO is only 1440x900 on my 1920x1200 tablet and 960x577 on my 2560x1440 phone when the rendering resolution is 1:1 and the display resolution is set to native. When I go into the ppsspp menu and return to the game, the FBOs become the correct 1920x1088 and 2880x1632 respectively.

**Comment by unknownbrackets** [comment]
When rendering resolution is 1x, in buffered rendering, you should get FBOs that are 480x272.  The rendering resolution is not a multiplier of your physical device's resolution, but a multiplier of the PSP's.

Please note that the PSP's resolution was 480x272.  At 4x, that would be 1920x1088.  At 3x, that would be 1440x816.  At 6x, it's 2880x1632.

Are you using buffered rendering?

-[Unknown]

**Comment by xperia64** [comment]
I am using buffered rendering. Here is the relevant log after I boot a game and enter and return from the PPSSPP menu:
```
07-14 13:28:46.718: I/NativeApp(25122): Creating 960 x 540 FBO using DEPTH24_STENCIL8
07-14 13:28:46.726: I/NativeApp(25122): 28:46:726 user_main    I[SCEGE]: Common/FramebufferCommon.cpp:354 Creating FBO for 00000000 : 480 x 272 x 3
07-14 13:28:48.966: I/NativeApp(25122): Creating 960 x 540 FBO using DEPTH24_STENCIL8
07-14 13:28:48.980: I/NativeApp(25122): 28:48:980 user_main    I[SCEGE]: Common/FramebufferCommon.cpp:354 Creating FBO for 00088000 : 480 x 272 x 3
07-14 13:29:10.396: I/NativeApp(25122): 29:10:395 idle0        I[SCEGE]: GLES/Framebuffer.cpp:1837 Destroying FBO for 00000000 : 480 x 272 x 3
07-14 13:29:10.401: I/NativeApp(25122): 29:10:401 idle0        I[SCEGE]: GLES/Framebuffer.cpp:1837 Destroying FBO for 00088000 : 480 x 272 x 3
07-14 13:29:10.469: I/NativeApp(25122): Creating 2880 x 1632 FBO using DEPTH24_STENCIL8
07-14 13:29:10.482: I/NativeApp(25122): 29:10:482 idle0        I[SCEGE]: Common/FramebufferCommon.cpp:354 Creating FBO for 00088000 : 480 x 272 x 3
07-14 13:29:10.555: I/NativeApp(25122): Creating 2880 x 1632 FBO using DEPTH24_STENCIL8
07-14 13:29:10.570: I/NativeApp(25122): 29:10:570 idle0        I[SCEGE]: Common/FramebufferCommon.cpp:354 Creating FBO for 00000000 : 480 x 272 x 3
```

**Comment by unknownbrackets** [comment]
If you have render resolution set to 1x, it must be getting set to something else somehow.  Could you have a game-specific config?

-[Unknown]

**Comment by xperia64** [comment]
The issue isn't that it's not getting set to 1x, it's that it's not correctly detecting the Native Device resolution.
I just did a clean install of PPSSPP, set rendering resolution to Auto (1:1) and Display Resolution to Native device resolution and left everything else alone.

I did some digging and it looks like on boot, PPSSPP is using dp, not the actual number of pixels for the core config width and height. Line 113 of https://github.com/hrydgard/ppsspp/blob/master/UI/EmuScreen.cpp returns bounds that are 3/8 my actual screen dimensions, and those values are used until I enter/leave PPSSPP's menu.

While using dp is fine for the control layout and control scaling, it seems those values shouldn't be used for fbo_create in https://github.com/hrydgard/native/blob/master/gfx_es2/fbo.cpp and the actual number of pixels should be used instead.
I haven't found where they get reset to the correct values when entering and leaving the PPSSPP menu, but it's a start.

**Comment by hrydgard** [comment]
That sounds like a bug indeed, I will take a look.

**Comment by unknownbrackets** [comment]
My bad, I somehow read Auto (1:1) wrong since the start and thought you'd said 1x.

Okay, #7865 should fix this.  Upon resize `(PSP_CoreParameter().pixelWidth + 479) / 480` is used to calculate `PSP_CoreParameter().renderWidth` temporarily, and this makes the FBOs get recreated with the right size.  But new FBOs would still be created wrong since the renderWidth gets reset I'm pretty sure.

-[Unknown]
