### ISSUE TITLE
Street Fighter Alpha 3 Max Saving/Loading issues

### ISSUE THREAD

**Issue by Warriors-Blade** [hrydgard/ppsspp#7780]
In the latest builds of PPSSPP I just found out that street fighter 3 max is pretty glitchy with saving and loading.

When starting the game and it attempts to auto load it will say no memory stick found.

In Edit mode if you try to save it will get stuck in a infinite loop, have to reset the game.

in options you can save/load normally by selecting those options but if you try using auto save/load it will say there is no memory stick.

I hope this is not a dupe since I did a search before making this issue.

**Comment by thedax** [comment]
All of the features you mentioned work fine here on Windows. Can you be a little more specific? What platform are you running the game on?

**Comment by Warriors-Blade** [comment]
Sorry about that,

Windows 7 64

and I never tried SFA3 Max until I posted here when I noticed the problem.

Il do a bit more testing and see if I can get any more info.

**Comment by thedax** [comment]
You probably had it installed into a directory with no write permissions, such as your desktop (silly as it sounds, sometimes PPSSPP lacks the permissions to write there), or Program Files (and it wasn't installed properly, if so).

**Comment by Warriors-Blade** [comment]
It has full permission, its in my emulator folder on my desktop, its the only game with a strange error like that until I made another PPSSPP in the same directory that was clean/fresh.

Pretty strange though.

**Comment by Warriors-Blade** [comment]
OK I just updated to the latest build which is ppsspp-v1.0.1-559-g403f6ab-windows-amd64

And the saving/loading issues seems to be fixed, I just tried everything that was glitchy before, everything is perfectly normal now.

**Comment by Adnan1091** [comment]
I experience this on retroarch64Arm.Deleting save file doesn't work.I even tried old versions of ppsspp cores,no help.
