### ISSUE TITLE
Recording gameplay is very slow!

### ISSUE THREAD

**Issue by Pyroglyph** [hrydgard/ppsspp#7784]
I know that screen recording slows down some games but I don't understand why programs like Fraps and Dxtory absolutely wreck PPSSPP's framerate? I run at a solid 60fps most of the time and I have a high-end GPU. I would normally understand this and think that it's just the way the emulator is made BUT if I screenshare through Skype, I stay at about 60fps! I have no idea why dedicated recording software makes PPSSPP lag while 'recording' with Skype makes no difference!

**Comment by i30817** [comment]
It happens in most emulators because fraps wraps directx calls in order to record stuff, introducing latency.

**Comment by pal1000** [comment]
I personally prefer Open Broadcaster Software. It is very efficient. I tried many others and just like you I experienced poor performance on recording. An important note is that if you are running Windows Vista or 7 make sure to turn off Aero transparent glass before recording. It wastes 2x more resources than otherwise.

**Comment by unknownbrackets** [comment]
IMHO, rendering fast is PPSSPP's job.  It does that.  There's probably still things we could find to do that faster, and I'd rather go down that path than trying to find ways to make it slower just so recording software can work better.

Recording fast is the job of recording software.  Not only that, but this software (both FRAPS and Dxtory) is *paid* software.  We can't access the source code and don't have as much to go on to determine precisely why it's slow.

It sounds like Open Broadcaster Software is superior, at least when it comes to recording PPSSPP.  Either these softwares need to improve, or they aren't interested in supporting PPSSPP with good performance.  Either way, if some recording software runs better than others, this suggests to me that we might not be able to do much to solve these closed-source software's performance issues.

If you've paid for the software, you should let them know if you aren't satisfied with the software's performance when recording PPSSPP.

IMHO this issue report belongs in the bug trackers for those softwares.

-[Unknown]
