### ISSUE TITLE
BlockDevices.cpp 96: Could not read...

### ISSUE THREAD

**Issue by innocentius** [hrydgard/ppsspp#7787]
Have been playing through several games for a while but most of them encounter a common bug and become weird or just crash:

E[FileSys]: FileSysyem/BlockDevices.cpp:96 Could not read <number> bytes from block

I'm using the v1.0.1-547-gc5ea38f and I will try to update to the newest version, but I thought someone could have a solution to this.

Sorry if this issue is duplicated.

**Comment by Bigpet** [comment]
What device and OS are you running PPSSPP on? And what storage device do you store your games on?

**Comment by innocentius** [comment]
windows64bit, the game is stored in my portable storage device... I will try to move them into my harddisk.

**Comment by innocentius** [comment]
OUCH! that WDdisk is automaticlly locked! Now I need to wonder how could I even open that game with the read and write lock on.

Thanks for the help, this issue is fixed...(f&$@ me.)
