### ISSUE TITLE
Recent Tab no longer stores games

### ISSUE THREAD

**Issue by FreakGamer** [hrydgard/ppsspp#7790]
Upon exit of games the respective games don't show up in the recent tab. Only exception to this is PES 2012.
I have a Macbook Air with the latest version of PPSSPPSDL.

**Comment by ThePhoenixRises** [comment]
This is still happening it seems, that no games are showing up on the recent Tab any more, I play any game / Homebrew and it doesn't show on there.
Tested latest build: v1.1.0-19-g4aceb47 on my PC (x86 - 32bit).
Unsure when this started happening as I've not been keeping up to date with this emulator for a while. (Life got in the way).

**Comment by hrydgard** [comment]
@ThePhoenixRises or @FreakGamer , can you post the [Recent] section of your memstick/PSP/SYSTEM/ppsspp.ini ?

(on mac you can find the memstick directory in ~/.config)

**Comment by ThePhoenixRises** [comment]
[CODE][Recent]
MaxRecent = 30
FileName0 = C:/Users/Phoenix/Desktop/EMULATORS/PSP Games/Gran Turismo (U).iso
FileName1 = C:/Users/Phoenix/Desktop/EMULATORS/PSP Games/Ridge Racer 2.iso
FileName2 = C:/Users/Phoenix/Desktop/EMULATORS/ppsspp/memstick/PSP/GAME/TrigWars
FileName3 = C:/Users/Phoenix/Desktop/EMULATORS/ppsspp/memstick/PSP/GAME/flower
FileName4 = C:/Users/Phoenix/Desktop/EMULATORS/ppsspp/memstick/PSP/GAME/Breakout
FileName5 = C:/Users/Phoenix/Desktop/EMULATORS/PSP Games/FIFA 2005.cso
FileName6 = C:/Users/Phoenix/Desktop/EMULATORS/PSP Games/Taito Legends.iso
FileName7 = C:/Users/Phoenix/Desktop/EMULATORS/PSP Games/Star Wars - Battle Front 2.cso
FileName8 = C:/Users/Phoenix/Desktop/EMULATORS/ppsspp/memstick/PSP/GAME/ChuckieEgg
FileName9 = C:/Users/Phoenix/Desktop/EMULATORS/ppsspp/memstick/PSP/GAME/pspkvm
FileName10 = C:/Users/Phoenix/Desktop/EMULATORS/PSP Games/Street Fighter Alpha 3.iso
FileName11 = C:/Users/Phoenix/Desktop/EMULATORS/PSP Games/Puzzle Bobble.iso
FileName12 = C:/Users/Phoenix/Desktop/EMULATORS/PSP Games/Virtual Tennis.cso
[PinnedPaths][/CODE]

**Comment by unknownbrackets** [comment]
How are you exiting PPSSPP?

-[Unknown]

**Comment by unknownbrackets** [comment]
I noticed that SDL doesn't save the config on exit.  Is this a problem with #8307 merged?

-[Unknown]

**Comment by ppmeis** [comment]
Tested with latest build. It works fine on Windows and Android for me:
![image](https://cloud.githubusercontent.com/assets/4381277/12820675/6876bb7a-cb60-11e5-91a7-ec5d834de7b5.png)

Only a game doesn't shop up in recents tab when emulator forces close or freezes.

**Comment by unknownbrackets** [comment]
Okay, going to close and assume fixed, then.

-[Unknown]
