### ISSUE TITLE
Keseki series: BGM stop after combat

### ISSUE THREAD

**Issue by innocentius** [hrydgard/ppsspp#7794]
Affected games:
Sora no Kiseki (FC, SC, 3rd)
Zero no Kiseki
Ao no Kiseki

Affected OS: Windows x64
Affected Version: v1.0_547
Description: Immediately after combat, all sound of the games will stop, a quick s/l will solve the problem, but this happens so often (1 combat in 5) and if not solved properly the game would crash.
I would refer to #5286 to search for similar issues.

I suspect that this happens just as the reason #5286 said (sorry i'm not expert in this area). I turned Audio Latency to "Low", and lower my click speed, and the occurrence rate was significantly reduced (1 in 30) but it will still happen. I don't know if change Audio backend to DSound will help, but I did that also.

Because this problem happen to and only to Keseki series, I suspect all map background music are in the affected area, I do not know how to extract music out of the game and neither do I have time for it. 

Hopefully this will help you guys to update the simulator and I am looking forward to a solution.

**Comment by innocentius** [comment]
PS: A quick s/l probably will not solve the problem, neither do a reset. It will only temporarily get the sound back and the same problem will occur after another combat(this time it will 100% happen). The only way to solve this is to do a game save (the real save), close the game, reopen then read the save.

**Comment by daniel229** [comment]
I never saw this bug in Zero no Kiseki,did you with default setting in ppsspp?Or can you upload a savedata where you saw the bug.

**Comment by innocentius** [comment]
Basically i'm using the highest settings available (which is also stable) in ppsspp except DSound. Not sure what you are pointing to but I can tell that the savedata for the game will not cause a glitch.

**Comment by daniel229** [comment]
What does the log console say when BGM stopped? Does it hapeen before? You can find old builds here http://buildbot.orphis.net/ppsspp/index.php?m=fulllist

**Comment by innocentius** [comment]
SOUND_THREAD E[ME]: HLE\sceAtrac.cpp:422 avcodec_decode_audio4:Error decoding audio -1094995529 / bebbb1b7 (these two numbers are random numbers).

This problem happens only in kiseki series, as I know for now.

I have several friends using version 1.0.1 also have this problem, but they say 0.9.6 is fine.

PS: ao no kiseki is confirmed to have this problem too.

**Comment by unknownbrackets** [comment]
This issue predates #8093, but I saw that one first (sorry) and put more details about the issue there.  I'm going to close this as a duplicate.

FWIW, #8105 resolves this issue afaict.  It hasn't been merged yet, but if you can compile, please feel free to test and report if there are still issues.

-[Unknown]
