### ISSUE TITLE
Homebrew states naming

### ISSUE THREAD

**Issue by vnctdj** [hrydgard/ppsspp#7795]
When we save a state in a game, PPSSPP creates 2 files (a .jpg file and a .ppst file) which are named as the following : `"UMD serial" + "_#"`.
Given that each game has an unique UMD serial, there is no problem :)
But homebrews don't have an UMD serial, therefore when you save a state with homebrew *example1* PPSSPP names the 2 files `"_#"`. And when you save a state with homebrew *example2*, PPSSPP also names the 2 files `"_#"`.
It means that all homebrews will share the same states, which is incoherent...
We have to solve this issue : how should we name the 2 files created when we save a state in a homebrew ?

**Comment by hrydgard** [comment]
Yeah, this is definitely a real issue. Might name it after the directory the homebrew is in? Should at least be unique locally, as long as all homebrews run from the memstick directory..

**Comment by vnctdj** [comment]
Using the name of the directory should be enough, yes...
Anyway, considering the directory is named as the name of the homebrew : different homebrews should have different names :)

**Comment by pal1000** [comment]
Related to #6281.

**Comment by FireyFly** [comment]
How about checksumming (part of) the ROM and using the checksum as part of the filename? This also takes care of the case when you have different versions of the same homebrew (possibly with matching directory names)--presumably, if the checksum changes then savestates would be incompatible.

**Comment by hrydgard** [comment]
I'm going for a simple solution where we just extract part of the path name. See #7997.

**Comment by vnctdj** [comment]
I have seen your pull request, I will test it soon :)
