### ISSUE TITLE
I think waifu2x will improve the render affect

### ISSUE THREAD

**Issue by endlesstravel** [hrydgard/ppsspp#7796]
Here is raw 1x size,
![raw 1x](https://cloud.githubusercontent.com/assets/10757838/8018381/9987e3d0-0c4b-11e5-859b-1e7de0a2cf48.png)

here raw 2x size,with many serration on the Logo. [Click to explore large size]
![raw 2x](https://cloud.githubusercontent.com/assets/10757838/8018382/99b63460-0c4b-11e5-93f8-53f635cdb4dd.png)

And below use raw 1x upscale to 2x size with waifu2.
It does not use Noise Reduction (expect JPEG Artifact) function of waifu2.
![use waifu2](https://cloud.githubusercontent.com/assets/10757838/8018429/cf31753a-0c4d-11e5-9c19-6bc77f88143d.png)

Even have no serration on it Logo.

And here is waifu it web
https://github.com/nagadomi/waifu2x

**Comment by ppmeis** [comment]
It looks good, I check the website and is a Nvidia exclusive feature, is that right?

How about pc/vram consumption? Any comparison?

**Comment by endlesstravel** [comment]
Yes. It require NVIDIA GPU (Compute Capability 3.0 or later).
Think you remind, I did not think so much.
Oh, it may consume a lot hardware resource.
Well, I think it is unrealistic.
