### ISSUE TITLE
Constant reading in the games list if custom settings exist

### ISSUE THREAD

**Issue by vsub** [hrydgard/ppsspp#7807]
For some reason the more custom settings you have(settings per game)and the more of them are visible(maximized\full screen)the bigger will be the constant read.
If I create custom settings for all of my games,ppsspp will constantly do a 15mb read while I'm at the Games tab choosing a game(or in recent and there are a lot of games with custom settings)

I tried the latest beta but the problem still exist

**Comment by hrydgard** [comment]
Thanks for reporting, dunno how I missed this, but fixed now.

**Comment by vsub** [comment]
Yes,it works fine now,thanks
