### ISSUE TITLE
Video is incorrectly swizzled in Tengai Makyou 4

### ISSUE THREAD

**Issue by Kingcom** [hrydgard/ppsspp#7809]
http://puu.sh/imcuj/a04a3898e9.png

The frame is written to 0x04374000 by sceMpegAvcDecode, and is then deswizzled before displaying, resulting in the broken image. That was introduced in e979b3a, but that's likely only because it uncovered an issue. It's possible that it should be written in a swizzled state by sceMpegAvcDecode.

**Comment by unknownbrackets** [comment]
Does this fix it?

https://github.com/hrydgard/ppsspp/compare/hrydgard:master...unknownbrackets:video-swizzle

Although, this doesn't really swizzle it correctly.

-[Unknown]

**Comment by hrydgard** [comment]
Did swizzling textures read from &0x200000 addresses fix any games? As we are probably using the wrong swizzle anyway, I'm not sure about the point of that until we do.. 

But yeah, that seems like the right fix if we are actually going to swizzle those addresses.

**Comment by unknownbrackets** [comment]
I thought it did fix a game that used a texture from a swizzled address, I could be remembering wrong.

-[Unknown]

**Comment by Kingcom** [comment]
It looks good with that.
