### ISSUE TITLE
PPSSPP 1.0.1 Hardware Transform Problem In Mali 400MP GPU

### ISSUE THREAD

**Issue by hqhoangvuong** [hrydgard/ppsspp#7812]
I playing Persona 3 Portable in PPSSPP on my phone, everything run good until I go to the Tartarus. A message display on the screen noicted that "Hardware transform error - Failing back to software" and the game very lag after.Can you fix this error, my phone using Mali 400-MP GPU.And sorry for my bad English.

**Comment by unknownbrackets** [comment]
Duplicate of #1816.  Make sure you have software skinning enabled in settings.

-[Unknown]
