### ISSUE TITLE
Metal Gear Solid: Peace Walker excessive fog and text disappear if lazy texture caching is on

### ISSUE THREAD

**Issue by nfjorgebueno** [hrydgard/ppsspp#7813]
Metal Gear Solid: Peace Walker ULUS10509
lthe graphics look very bad and also the texts in windows x86 intersect any idea, thanks,sorry I forgot the game continues graphics regression

```
11:21:656 Util\BlockAllocator.cpp:249 D[HLE]: Block Alloc found adjacent free blocks - merging
11:21:656 Util\BlockAllocator.cpp:224 D[HLE]: Merging Blocks
11:21:656 Util\BlockAllocator.cpp:229 D[HLE]: Block Alloc found adjacent free blocks - merging
11:21:656 Util\BlockAllocator.cpp:224 D[HLE]: Merging Blocks
11:21:656 Util\BlockAllocator.cpp:229 D[HLE]: Block Alloc found adjacent free blocks - merging
11:21:656 Util\BlockAllocator.cpp:249 D[HLE]: Block Alloc found adjacent free blocks - merging
11:21:656 Util\BlockAllocator.cpp:224 D[HLE]: Merging Blocks
11:21:656 Util\BlockAllocator.cpp:229 D[HLE]: Block Alloc found adjacent free blocks - merging
11:21:656 Util\BlockAllocator.cpp:249 D[HLE]: Block Alloc found adjacent free blocks - merging
11:21:656 Util\BlockAllocator.cpp:224 D[HLE]: Merging Blocks
11:21:656 Util\BlockAllocator.cpp:249 D[HLE]: Block Alloc found adjacent free blocks - merging
11:21:687 MemMap.cpp:380 D[MM]: Memory system shut down.
11:21:687 GLES\Framebuffer.cpp:1833 I[SCEGE]: Destroying FBO for 00000000 : 480 x 272 x 1
11:21:687 GLES\Framebuffer.cpp:1833 I[SCEGE]: Destroying FBO for 00044000 : 480 x 272 x 1
11:21:687 GLES\Framebuffer.cpp:1833 I[SCEGE]: Destroying FBO for 00088000 : 64 x 64 x 3
11:21:687 GLES\Framebuffer.cpp:1833 I[SCEGE]: Destroying FBO for 000a2000 : 64 x 64 x 3
11:21:687 GLES\Framebuffer.cpp:1833 I[SCEGE]: Destroying FBO for 0008c000 : 64 x 64 x 3
11:21:703 GLES\TextureCache.cpp:136 D[G3D]: Deleting texture 108
11:21:703 GLES\TextureCache.cpp:136 D[G3D]: Deleting texture 328
11:21:703 GLES\TextureCache.cpp:136 D[G3D]: Deleting texture 109
11:21:703 GLES\TextureCache.cpp:136 D[G3D]: Deleting texture 103
11:21:703 GLES\TextureCache.cpp:136 D[G3D]: Deleting texture 104
11:21:703 GLES\TextureCache.cpp:136 D[G3D]: Deleting texture 337
11:21:703 GLES\TextureCache.cpp:136 D[G3D]: Deleting texture 307
11:21:703 GLES\TextureCache.cpp:136 D[G3D]: Deleting texture 306
11:21:703 GLES\TextureCache.cpp:136 D[G3D]: Deleting texture 272
11:21:703 GLES\TextureCache.cpp:136 D[G3D]: Deleting texture 322
11:21:703 GLES\TextureCache.cpp:136 D[G3D]: Deleting texture 262
11:21:703 GLES\TextureCache.cpp:136 D[G3D]: Deleting texture 325
11:21:703 GLES\TextureCache.cpp:136 D[G3D]: Deleting texture 245
```
## 

Metal Gear Solid - Peace Walker [USA 1.01](http://report.ppsspp.org/game/ULUS10509_1.01) / [USA 2.00](http://report.ppsspp.org/game/ULUS10509_2.00) / [JP 1.00](http://report.ppsspp.org/game/NPJH90063_1.00) / [JP 1.02](http://report.ppsspp.org/game/NPJH50045_1.02) / [EUR 1.01](http://report.ppsspp.org/game/ULES01372_1.01)

**Comment by nfjorgebueno** [comment]
from what I saw on the forums ppsspp many have the same problem in ppsspp 1.0.1, thanks for listening

**Comment by nfjorgebueno** [comment]
This is the best setup I could do
disable slow effects turned off (this is the problem with graphics if on)
mipnaping off
lazy texture caching turned off (this is the probem with the texts if it is turned on)
with this greatly improves the game but it is only a temporary solution, not concrete, thanks for listening

**Comment by unknownbrackets** [comment]
Does this still happen with 1.2.2?  You'll want vertex cache and lazy texture caching off (both are speed features that can cause graphical bugs.)  But it'd be good if the "slow effect" worked and did not need to be disabled.

-[Unknown]

**Comment by nfjorgebueno** [comment]
Sorry for not replying before The game looks a little better in ppsspp 1.3.0

**Comment by hrydgard** [comment]
Little better or good enough? If there are real problems, please reopen and post a screenshot.

**Comment by Kryse-777** [comment]
specifically, turning off the "lazy texture caching" was the one that worked for me

**Comment by hrydgard** [comment]
Can you test if that's still the case in the latest build, if you turn on lazy texture cache?

**Comment by hrydgard** [comment]
No response, closing.
