### ISSUE TITLE
X86 power vr broken animation and lag

### ISSUE THREAD

**Issue by shinemu** [hrydgard/ppsspp#7814]
Hello :) i would like to report that some games have broken animation like super robot wars Z1 and Z2 and also lagging plus sound seems broken on gulty gears,i'm using asus zenfone 2 2,3 ghz 4 gb ram android lolipop..i hope it can be fix soon on dev working version.thanks and keep up the good work ^_^ best regards

**Comment by unknownbrackets** [comment]
Closing as duplicate of #1313.  Duplicates only make things get fixed slower, just search first.

-[Unknown]
