### ISSUE TITLE
Tactics Ogre: Let Us Cling Together PSP Keyboard Crash

### ISSUE THREAD

**Issue by PhantomGamer** [hrydgard/ppsspp#7819]
Whenever I try to start a new game it will take me to the "What's your name?" thingy then the emulator would stop and crash.

I can play P3P and FFT with no problem though

Thanks in advance

**Comment by sum2012** [comment]
No problem on me in windows
in my phone (asus zenfone 2) graphic has problem

**Comment by sum2012** [comment]
@hrydgard @unknownbrackets 
v1.0.1-865-g825662d still same problem on my phone
![bad](https://cloud.githubusercontent.com/assets/2177532/9655164/d8135894-5261-11e5-90ca-4f93143c08d7.jpg)

My hack (?) https://github.com/sum2012/ppsspp/commit/c6c247a2371e6e4d9578bda297ac5b73dbb69e5a

![good](https://cloud.githubusercontent.com/assets/2177532/9655184/fa538064-5261-11e5-966a-bc51b6a5f9c5.jpg)

**Comment by hrydgard** [comment]
Okay, looks like we should just turn off shader framebuffer blending on gpus <= SGX 540, or so. Weird that it doesn't work....

**Comment by sum2012** [comment]
My phone now black screen in v1.0.1-880-g1fd6cf1
Now try bisect #7942

**Comment by sum2012** [comment]
Test from v1.0.1-881-gcfe4c03
The issue come back to 
https://cloud.githubusercontent.com/assets/2177532/9655164/d8135894-5261-11e5-90ca-4f93143c08d7.jpg

**Comment by sum2012** [comment]
@PhantomGamer  Does you still have the problem in the newest version ?
http://buildbot.orphis.net/ppsspp/

**Comment by ppmeis** [comment]
Tested on Windows and Android. On Windows it loads fine but ppsspp freezes when I go to this screen:
![image](https://cloud.githubusercontent.com/assets/4381277/12820216/71ced4a2-cb5e-11e5-92de-b67fe4ad28cf.png)
![image](https://cloud.githubusercontent.com/assets/4381277/12820222/78f16646-cb5e-11e5-8767-66bc4b568dcf.png)

Android only load when NFB is selected, otherwise emulator closes at the beginning of "Square Enix" intro movie. Also the game is sooo slow even at 1x PSP (15/60 fps):
![image](https://cloud.githubusercontent.com/assets/4381277/12820341/e81c10c0-cb5e-11e5-811d-fcf76fdb722e.png)

**Comment by sum2012** [comment]
What is "NFB" ?

**Comment by sum2012** [comment]
@hrydgard @unknownbrackets 
For bufffered rendering crash in android
Last work: v1.1.1-790-g24cad4c
First break : v1.1.1-797-gcd35684
It mean #8454

**Comment by ppmeis** [comment]
@sum2012 I mean Non Buffered Rendering.

**Comment by sum2012** [comment]
@ppmeis ok

**Comment by sum2012** [comment]
@hrydgard @unknownbrackets 
v1.1.1-931-g042bfe6 crash log
https://gist.github.com/sum2012/1f9722d4d8e6fc0f7f3a

**Comment by sum2012** [comment]
compile error on https://github.com/unknownbrackets/ppsspp/commit/0443fbebd07e2fed9c706b854f1f29e1684d2b45

![1](https://cloud.githubusercontent.com/assets/2177532/12990458/718073ec-d145-11e5-8e8f-dbed01d39cd0.png)

**Comment by hrydgard** [comment]
That crash log looks like either out of memory, or we try to allocate way too much somehow. Hm.

**Comment by hrydgard** [comment]
Attempted a workaround, although the actual bug is elsewhere, if that works.

**Comment by sum2012** [comment]
Well done @hrydgard 
v1.1.1-932-g5bfeafc fixed the crash
log:
https://gist.github.com/sum2012/978f7cff2cabb7d6c09f

**Comment by hrydgard** [comment]
Cool, thanks for testing.

 @unknownbrackets , feels like the math in the function is wrong. Output from my check from sum2012's log:

     PackFramebufferSync_: region out of range (x,y,w,h: 432,224,48,48)

That seems like a valid region to copy from..

**Comment by unknownbrackets** [comment]
Sorry, I think this is wrong:
https://github.com/hrydgard/ppsspp/commit/0443fbebd07e2fed9c706b854f1f29e1684d2b45#diff-29313f9f6ed28d0e24e6dac4e0db8933L1679

Should've just been `h`.  And we can revert 5bfeafc0377c7576ce570e357d4e056c5fd3d6d4.

I can do it later but pretty busy for several more hours.

-[Unknown]

**Comment by unknownbrackets** [comment]
Just to note, the issue we're discussing is assuredly different from the issue reported here, since this bug wasn't there in 2015.  But, it is possible that the change that introduced this new bug we are discussing also fixed the original bug this issue was about.

-[Unknown]

**Comment by sum2012** [comment]
Test on v1.1.1-934-gbc1ed6e in Android also no problem.
I agree to close this issue becuase no fed back back.
Closing
