### ISSUE TITLE
Please Close, Issue No Longer Evdient - Kingdom Hearts Birth by Sleep Final Mix Crash

### ISSUE THREAD

**Issue by deadair3210** [hrydgard/ppsspp#7830]
Was playing normally, tried to go into part of the journal and the emulator crashed.ISO is Kingdom Hearts Birth By Sleep Final Mix that has been english patched 

![untitled](https://cloud.githubusercontent.com/assets/1053504/8397358/48ee28ea-1d8e-11e5-836e-6cb084ae880e.png)

**Comment by ppmeis** [comment]
@deadair3210 could you share a savestate to check this issue?¿

**Comment by deadair3210** [comment]
Have not been able to reproduce it as of late. Must have been fixed. Ment to close this issue, Sorry
