### ISSUE TITLE
Hidden PPSSPPSDL consumes CPU resource on OSX

### ISSUE THREAD

**Issue by oscdis** [hrydgard/ppsspp#7833]
Just like this post http://forums.libsdl.org/viewtopic.php?t=7036&sid=5eb5805931b264ad6bdb57978e3afc2b

Ordinary SDL_GL_SwapWindow waits VSYNC.
But SDL_GL_SwapWindow returns immediately when PPSSPPSDL is hidden (or minimized).
I don't know whether this behavior occurs on other platforms.

Naive fix is putting the below after time_now in PCMain.cpp.

```
if (t - lastT < 1.0/60.0) {
    int delay_time = 1000 * (1.0/60.0 - (t - lastT));
    SDL_Delay(delay_time);
    time_update();
    t = time_now();
}
```

But I am not sure this has no problem...

**Comment by hrydgard** [comment]
Hm. It might be safer to wait say half a frame instead, but preferably there'd be a way to detect if we are hidden or minimized...

**Comment by unknownbrackets** [comment]
Does `SDL_GetWindowFlags()` give us any useful flags like `SDL_WINDOW_MINIMIZED` or `SDL_WINDOW_HIDDEN`?

IIRC, there was some minimize handling already right?

-[Unknown]

**Comment by HarukaMa** [comment]
Seems like an issue I've reported before, but in a lots of details.

On my phone now so can't remember the old issue ID...

iPhone$B$+$iAw?.(B

H27/06/29 20:25$B!"(Boscdis <notifications@github.com> $B$N%a%C%;!<%8(B:

**Comment by unknownbrackets** [comment]
#6276?

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, duplicate. Closing as such, but of course this needs to be fixed.

**Comment by oscdis** [comment]
@unknownbrackets 

SDL_GetWindowFlags() does not help us (maybe).

OSX has "hide a window" as OS function. if you use OSX, command+H will trigger this function. 
See: https://support.apple.com/en-us/HT201236

The state of SDL_WINDOW_HIDDEN means this hidden (maybe). but hidden of this issue is not. 

Hidden of this issue is the state of covering PPSSPPSDL window by others. for instance, dragging the corner of Chrome, and resize it widely as much as possible. Chrome will be hiding PPSSPPSDL. 

I have Google and Google, but couldn't find how to detect this hidden from programs...

**Comment by oscdis** [comment]
Oops. sorry for duplicate.
