### ISSUE TITLE
Map error

### ISSUE THREAD

**Issue by leoxxx** [hrydgard/ppsspp#7834]
Super Robot Taisen OG Saga Masou Kishin II Revelation of Evil God 
![snap2](https://cloud.githubusercontent.com/assets/5364709/8430403/a920d9c0-1f63-11e5-8275-8aa472f428b0.png)
In PPSSPP

![1](https://cloud.githubusercontent.com/assets/5364709/8430511/fc371b32-1f64-11e5-884e-02843e041dcf.jpg)
In PSP

Super Robot Taisen OG Saga: Masou Kishin - The Lord of Elemental 
![snap3](https://cloud.githubusercontent.com/assets/5364709/8430404/a9ce8372-1f63-11e5-8661-e1724b1e56c7.png)
In PPSSPP

![2](https://cloud.githubusercontent.com/assets/5364709/8430724/2979300c-1f66-11e5-8f01-3df87fa59102.jpg)
In PSP

The  block around the robot in these games.

**Comment by daniel229** [comment]
That looks like disabling alpha test.

**Comment by innocentius** [comment]
Disable alpha test in 'Sora no Kiseki' will result in similar problem.

**Comment by unknownbrackets** [comment]
Score another point for renaming the option to "Allow ugly boxes behind objects (PowerVR speedup)".

Pretty sure this is going to be that option, so I'm closing.  If it's not, please provide more detail on what device you're using and confirm that it happens with completely default settings (rename ppsspp.ini to be sure.)

-[Unknown]

**Comment by hrydgard** [comment]
@unknownbrackets as hardware is getting faster on average every year, it might make sense to start hiding these destructive options behind some very scarily-worded special speed hacks menu soon...

**Comment by leoxxx** [comment]
THX ALL.
I disable the option. The block disappear.

**Comment by unknownbrackets** [comment]
Yeah, I agree.  We could alternatively or additionally add an option to even enable those options in the UI, like "Allow enabling speedhacks (some major glitches)".  That way you can't space-case on the headers and just check a bunch of things without realizing as easily.

-[Unknown]
