### ISSUE TITLE
invisible characters ?[naruto ultimate ninja heroes 2]

### ISSUE THREAD

**Issue by coolmisty45** [hrydgard/ppsspp#7835]
In Naruto ultimate ninja heroes 2 when the characters use awakening parts of their body's turn invisible. I tried all the graphics options so I think its a bug with ppsspp not my settings 

P.s I am using the latest automated build

**Comment by coolmisty45** [comment]
And I might add I am on the android version

**Comment by unknownbrackets** [comment]
Could you try exporting a GE frame dump?  These help a lot.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by Emulatorer** [comment]
I tried that game in ppsspp v1.8.0 everything is finy now

**Comment by unknownbrackets** [comment]
Alright, I'll mark this closed then.  Thanks for verifying.

-[Unknown]
