### ISSUE TITLE
CW cheats not working!!

### ISSUE THREAD

**Issue by coolmisty45** [hrydgard/ppsspp#7838]
When I activate the cheats they don't take effect on any games!!

Info:
-using latest automated build
-Android version
-cheats not working on any game :(
-games I tested, 2 different naruto games, Harvest moon leaf village, bleach, and about 4 other random games

**Comment by nfjorgebueno** [comment]
cwcheats windows have some work others do not think the cwcheats code or other format worked well recently when ppsspp take the codes as a real psp, probe the god of war in the latest version of ppsspp and the codes work, probe the metal gear Acid 2 and the codes do not work, a greeting
