### ISSUE TITLE
Final Fantasy 2 Anniversary Edition (ULES00987) Soul of Rebirth Minwu glitch

### ISSUE THREAD

**Issue by ofry** [hrydgard/ppsspp#7845]
When player complete the main quest of Final Fantasy II Anniversary Edition, he can load bonus quest "Soul of Rebirth".

But sometimes I have Minwu texture glitch in dungeon when he moving from left to right.

![ules00987_1 00_3](https://cloud.githubusercontent.com/assets/11790863/8508122/6fcc0256-226c-11e5-85e4-aed67ff532f5.jpg)

**Comment by ofry** [comment]
It occurs in revision v1.0.1-694-g58e8b24, for sample.

**Comment by unknownbrackets** [comment]
Looks like lazy texture caching or vertex caching to me.

-[Unknown]

**Comment by ofry** [comment]
Yeah, when I off Vertex Cache and Lazy Texture Caching, all working fine :)

**Comment by unknownbrackets** [comment]
Right, I think that we can't really make this a ton better when those are on.  Probably it's mainly lazy texture caching, which is off by default anyway.

-[Unknown]
