### ISSUE TITLE
retro arch new version has is ppsspp on the core

### ISSUE THREAD

**Issue by asbel123** [hrydgard/ppsspp#7852]
i have to tell retro arch new verison was out on google play store they add new core is ppsspp i tried it one feature i like is extra top menu button right like retro arch has is fastword toogle and save states and load states next shader and u can choose save state slot. features i wish u add in andriod and iphone. 

retro arch is good touch screen menu they add on top right there two button is menu button and quick menu on next to it. 

please add that feature hrydgard in new version of ppsspp ok.

**Comment by ppmeis** [comment]
@asbel123 you should add a coment in your title to be more clear for developers, like "[Feature Request] Add Retroarch's top menu" or similar.

**Comment by vgturtle127** [comment]
@asbel123 I know English isn't your first language, but if you could please try to be more clear about what you want, then maybe we can better understand what you want.

From what I can decipher from your post, you wish to add features from RetroArch/libretro to PPSSPP, right?

**Comment by unknownbrackets** [comment]
I tried using RetroArch a while back, and the menu didn't really seem clearer or more user friendly to me.

Could you include a screenshot of what you're suggesting?  I'm not sure I see the value in switching shaders quickly or etc.  Maybe I just "don't get it."

The second thing I recommend, and no offense, but try to include more periods / punctuation in what you write.  Your spelling/etc. and word choice isn't bad, but it has no structure.  This makes it hard to understand you.

Let me write how I'm interpreting it (which may be wrong, I'm just guessing) for your benefit (again, no offense):

> A new version of RetroArch came out on Google Play.  They added PPSSPP as a new core.  I tried it and liked some features of it, which I thought I should tell you guys about.
>
> One feature of RetroArch that I like is an extra top menu button on the right.  This menu has lots of things:
>  * A fast-forward toggle feature.
>  * Quick access to save and load state.
>  * Selection of savestate slot.
>  * A button to cycle through post-rendering shaders.
>
> I feel these features should be added to PPSSPP on Android and iPhone devices.
>
> RetroArch has a good touch screen menu which made sense to me.  They have two buttons at the top right: one goes to the full menu, and the other is this "quick menu" I've described above.
>
> I would appreciate it if you would consider including these features in a new version, hrydgard.  Thank you.

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
