### ISSUE TITLE
should be watched on final version of windows 10 ppsspp do not recognice directx 

### ISSUE THREAD

**Issue by annahana** [hrydgard/ppsspp#7857]
in ppsspp run on windows 10 does not recocnice directx9 at the curent stage

![ppsspp device info intern 2](https://cloud.githubusercontent.com/assets/13276505/8625730/e244e37e-2740-11e5-95f6-51ac269dc7f9.PNG)
![ppsspp device info intern](https://cloud.githubusercontent.com/assets/13276505/8625731/e24716d0-2740-11e5-8235-62391d75609c.PNG)
![ppsspp](https://cloud.githubusercontent.com/assets/13276505/8625732/e24a668c-2740-11e5-936a-f150ca77589a.PNG)

**Comment by Bigpet** [comment]
Did you install the DX9 runtime?

**Comment by unknownbrackets** [comment]
Yeah, this is also the case on Windows 8.  You need to manually install DirectX 9, it no longer comes with Windows.  Think of it like sports games: FIFA 2014 might be better than FIFA 2012, but if you've got a game mod for FIFA 2012, you've gotta have FIFA 2012 or it won't work.

-[Unknown]

**Comment by annahana** [comment]
yes i know that and have instalet it afterwards with the webinstaler. but the most users will come from windows 7 and wil think it is a bug in the emulator becaus dx12 is the newest direct x. 
it would be be good fore users to see where theiy can downlode it. (and the full package dont instal becaus it see dx12 on mycomputer)

**Comment by hrydgard** [comment]
Hm, that's a bit of a pain. I guess we should start by improving the error message...

**Comment by GAMELASTER** [comment]
Well, i not installed the DirectX9 drivers, nothing, and PPSSPP works fine.. But already, on Windows 10 i see on almost all games the FPS down and bugs (on ppsspp i see some). Late i upload video..

**Comment by GAMELASTER** [comment]
Computer specifications (PPSSPP v1.0.1):
![2015-07-11_20-46-45](https://cloud.githubusercontent.com/assets/1665373/8634927/063a1cea-280e-11e5-9897-28cdc312527c.png)

Windows 10 Build 10130 x64 OpenGL:
http://screencast.com/t/UrUwO5N4yK
Windows 10 Build 10130 x64 DirectX9:
http://screencast.com/t/3GDHqSgThQXI

I know.. Its just only dont show one image.. I think is this do only on W10. BUt anyway.. P.S. Only changed renderer, not any settings...

**Comment by unknownbrackets** [comment]
It's known that there are things the Direct3D 9 backend cannot render properly which OpenGL can, because there are some features missing from Direct3D 9.  However, is there a reason you think these are Windows 10 specific?

-[Unknown]

**Comment by GAMELASTER** [comment]
Yes, i think i got more FPS on 8.1 ... Anyway i got a troubles on another games where running under DX9.. Like a GTA San Andreas, In 8.1 i runned it on FULL details (+ some edge "smoothers") and all 60 FPS (frame limiter of course), MTA ( Multi Theft Auto: San Andreas) runned too on 60 FPS on FULL, but now only 20 FPS. But, this is problem of Windows 10, not a application (i think). But anyway, a Counter Strike : Global Offensive has running really good (but that isnt work under DX9 i think). So, already, for this ISSUE is good to wait to RTM version Windows 10... :-)

**Comment by ppmeis** [comment]
I tested several games with D3D9 and latest Windows 10 build (10240 seems to be final release version for now) and I don't get any issue.

D3D9
![image](https://cloud.githubusercontent.com/assets/4381277/8890076/66d5e04e-32f3-11e5-887a-5f47234a50d7.png)

OpenGL
![image](https://cloud.githubusercontent.com/assets/4381277/8890084/b967ecc6-32f3-11e5-88cf-9bfbfa97cc91.png)

**Comment by unknownbrackets** [comment]
I'm not sure what we could do here.  Maybe add a warning to suggest the user install the runtime when D3D9 init fails?  But really, switching to OpenGL (or Vulkan, etc.) is probably going to be the better option.

I'm not sure we can do much for progressively improving Windows 10 drivers either.

Should we close this?

-[Unknown]
