### ISSUE TITLE
Birth by Sleep Control İssue

### ISSUE THREAD

**Issue by cherubeem** [hrydgard/ppsspp#7858]
When I open the Control Mapping, selector starts to move right like the right arrow button got stuck and I'm unable to pull it left by using the arrow keys. So I can't even save my game because the "yes" option is on the left

**Comment by unknownbrackets** [comment]
What device / platform is this?  What controls are you using - do you use a gamepad, keyboard, on-screen controls, or...?

-[Unknown]

**Comment by ppmeis** [comment]
Tested on Windows and Android, no way to reproduce this.

**Comment by unknownbrackets** [comment]
No feedback on device / controller, closing.  If there's more information, feel free to comment, and we can reopen.

-[Unknown]
