### ISSUE TITLE
Unable to save game/save state of any game (iOS)

### ISSUE THREAD

**Issue by sljtheultima** [hrydgard/ppsspp#7864]
Hi,

I just upgraded my iPhone from 8.1.2 to 8.3 recently. I have back up my save files previously and copy back. Upon loading any of the games and saving either from the game save or the save state. It will state that this on the top of the screen "unable to write savedata, disk may be full" when my phone does have sufficient space. 

Any solutions for this thanks!

**Comment by hrydgard** [comment]
Hm, the directory used for saves must have become write-protected somehow? strange..

**Comment by unknownbrackets** [comment]
I'm virtually certain that something some iOS users do makes the path owned by the wrong user and so not writable via unix permissions.  It's come up numerous times but only with iOS users.  However it also works for some other iOS users.

I think this "copy back" thing may be the cause.  @sljtheultima however you copied them back probably overwrote the permissions to make them only accessible e.g. by root / the program you uploaded them with, and no longer accessible from PPSSPP.

-[Unknown]

**Comment by brujo5** [comment]
@sljtheultima 

change permission whit ifile or mobile terminal

like this

**Comment by sljtheultima** [comment]
@brujo5 Thank You very much! That solves the issue!

**Comment by hrydgard** [comment]
We should probably improve the error message...
