### ISSUE TITLE
Does not work with homebrew games.

### ISSUE THREAD

**Issue by 133794m3r** [hrydgard/ppsspp#7872]
All homebrew will not run at all on this emulator. The emulator is not apparently familiar with how they work. It assumes umd0:/ for their root dir, whereas homebrew use ms0:/ for their root dir. So they won't work and end up crashing.

Biggest thing is the pspkvm since I know of no other way to run old java games anywhere in an open source way without it. Only bad thing is that the game runs like crap on the psp.

**Comment by hrydgard** [comment]
Lots of homebrew works just fine, you just need to put them in the right place for PPSSPP to do the right mounts. That is, in Memstick/PSP/GAME.

But yeah, there are some remaining directory issues. PSPKVM has a different problem though, timing related if I remember correctly.

**Comment by 133794m3r** [comment]
The error log all says file not found, and since there's nothing else out there hat can run j2me games it's the one software I was hoping to use somewhere else and get it running somehwat OK. It just locks up the emulator everytime it runs.

**Comment by LunaMoo** [comment]
This was fixed some time ago, homebrew nowadays only boot from memstick and see their root correctly - closing.

 Just note if anyone can't get this "PSPKVM" to work, make sure to place it's folder inside "/PSP/GAME" on memstick, note you install java apps for it you have to use "install from memory stick (ms0:/)" option and for that you also have to place the apps to install somewhere inside memstick folder:].
 Another thing - IOS platform might have some separate problem with it, most likely with file or folder access, just that this app lazily shows network-like messages even when browsing offline folders, either way that has it's own issue opened and possibly not even related to PPSSPP. but just iOS being iOS.

~tiny example of running some java test app:
![pspk00673_00000](https://cloud.githubusercontent.com/assets/5485237/26575227/a2eb28b0-4524-11e7-87cf-2d58e404e6c0.jpg)
