### ISSUE TITLE
App disappeared 

### ISSUE THREAD

**Issue by mclovin835** [hrydgard/ppsspp#7873]
was working fine. Games have some lag though, like dragon ball z it lags a lot. But since the update you sent out today the app has disappeared. I can no longer use the application

**Comment by hrydgard** [comment]
I have not sent out an update today.

**Comment by mclovin835** [comment]
IOS 8.4 iPhone 6 plus

**Comment by mclovin835** [comment]
And see there was a update today. I live in California July 22 there was a update. Do you have a email I could send you the screen shot of the update log?

**Comment by hrydgard** [comment]
Well *I* certainly didn't push any updates. Is your iPhone jailbroken? Did you install the app through Cydia?

@angelXwind , any idea?

**Comment by mclovin835** [comment]
Yes I am jailbroken and I did install it through Cydia

**Comment by mclovin835** [comment]
And in the change log ur picture and username is in it.

**Comment by hrydgard** [comment]
I made code commits, but it's @angelXwind 's system that pushes Cydia updates. I don't do iOS at the moment.

**Comment by angelXwind** [comment]
@hrydgard I think I may know what happened here... may.

@mclovin835 Do you have my [AppSync Unified](https://github.com/angelXwind/AppSync) installed?

**Comment by mclovin835** [comment]
Yes I do

**Comment by mclovin835** [comment]
Fixed. Just installed ur guys update and it fixed the probablem thank you

**Comment by angelXwind** [comment]
Oh. Okay, then. Wasn't the thing I was thinking of, then.

You can close this now, @hrydgard.
