### ISSUE TITLE
Visual Studio 2015 Community

### ISSUE THREAD

**Issue by pal1000** [hrydgard/ppsspp#7875]
I decided to give a try to the new VS2015. Performed a Release X64 build. Unfortunately it didn't went well. For some reason it can't find some headers:
corecrt.h, malloc.h, ctype.h, math.h, stdio.h, stdlib.h, string.h.
This appears to be the only issue.

Full output:

1>------ Build started: Project: GPU, Configuration: Release x64 ------
1>  xbrz.cpp
1>  DepalettizeShaderCommon.cpp
1>  DrawEngineCommon.cpp
1>  FramebufferCommon.cpp
1>Common\DepalettizeShaderCommon.cpp(18): fatal error C1083: Cannot open include file: 'stdio.h': No such file or directory
1>D:\Program Files\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory (compiling source file Common\FramebufferCommon.cpp)
1>D:\Program Files\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory (compiling source file Common\DrawEngineCommon.cpp)
1>  IndexGenerator.cpp
1>D:\Program Files\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory (compiling source file ..\ext\xbrz\xbrz.cpp)
1>  PostShader.cpp
1>  SplineCommon.cpp
1>D:\Program Files\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory (compiling source file Common\IndexGenerator.cpp)
1>  TextureScalerCommon.cpp
1>Common\SplineCommon.cpp(25): fatal error C1083: Cannot open include file: 'string.h': No such file or directory
1>D:\Program Files\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory (compiling source file Common\PostShader.cpp)
1>  TransformCommon.cpp
1>  SoftwareTransformCommon.cpp
1>  VertexDecoderCommon.cpp
1>D:\Program Files\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory (compiling source file Common\TextureScalerCommon.cpp)
1>Common\TransformCommon.cpp(18): fatal error C1083: Cannot open include file: 'stdio.h': No such file or directory
1>  VertexDecoderX86.cpp
1>Common\VertexDecoderCommon.cpp(18): fatal error C1083: Cannot open include file: 'stdio.h': No such file or directory
1>D:\Program Files\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory (compiling source file Common\SoftwareTransformCommon.cpp)
1>  Breakpoints.cpp
1>  Stepping.cpp
1>  DepalettizeShaderDX9.cpp
1>D:\Program Files\Microsoft Visual Studio 14.0\VC\include\xmmintrin.h(79): fatal error C1083: Cannot open include file: 'malloc.h': No such file or directory (compiling source file Common\VertexDecoderX86.cpp)
1>D:\Program Files\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory (compiling source file Debugger\Breakpoints.cpp)
1>  GPU_DX9.cpp
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\winnt.h(31): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file Debugger\Stepping.cpp)
1>  dx_state.cpp
1>D:\Program Files\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory (compiling source file Directx9\DepalettizeShaderDX9.cpp)
1>  fbo.cpp
1>D:\Program Files\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory (compiling source file Directx9\GPU_DX9.cpp)
1>  global.cpp
1>D:\Program Files\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory (compiling source file Directx9\helper\dx_state.cpp)
1>  PixelShaderGeneratorDX9.cpp
1>  FramebufferDX9.cpp
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\winnt.h(31): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file Directx9\helper\fbo.cpp)
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\winnt.h(31): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file Directx9\helper\global.cpp)
1>  ShaderManagerDX9.cpp
1>D:\Program Files\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory (compiling source file Directx9\PixelShaderGeneratorDX9.cpp)
1>  StateMappingDX9.cpp
1>  StencilBufferDX9.cpp
1>D:\Program Files\Development\projects\ppsspp\native\math/lin/vec3.h(4): fatal error C1083: Cannot open include file: 'math.h': No such file or directory (compiling source file Directx9\FramebufferDX9.cpp)
1>  TextureCacheDX9.cpp
1>D:\Program Files\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory (compiling source file Directx9\ShaderManagerDX9.cpp)
1>D:\Program Files\Development\projects\ppsspp\native\base/logging.h(17): fatal error C1083: Cannot open include file: 'stdio.h': No such file or directory (compiling source file Directx9\StencilBufferDX9.cpp)
1>  TextureScalerDX9.cpp
1>D:\Program Files\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory (compiling source file Directx9\StateMappingDX9.cpp)
1>  TransformPipelineDX9.cpp
1>  VertexShaderGeneratorDX9.cpp
1>D:\Program Files\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory (compiling source file Directx9\TextureCacheDX9.cpp)
1>D:\Program Files\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory (compiling source file Directx9\TextureScalerDX9.cpp)
1>D:\Program Files\Development\projects\ppsspp\native\base/logging.h(17): fatal error C1083: Cannot open include file: 'stdio.h': No such file or directory (compiling source file Directx9\TransformPipelineDX9.cpp)
1>  GeDisasm.cpp
1>  DepalettizeShader.cpp
1>  FragmentShaderGenerator.cpp
1>Directx9\VertexShaderGeneratorDX9.cpp(18): fatal error C1083: Cannot open include file: 'stdio.h': No such file or directory
1>D:\Program Files\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory (compiling source file GeDisasm.cpp)
1>  FragmentTestCache.cpp
1>D:\Program Files\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory (compiling source file GLES\DepalettizeShader.cpp)
1>  Framebuffer.cpp
1>D:\Program Files\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory (compiling source file GLES\FragmentShaderGenerator.cpp)
1>  GLES_GPU.cpp
1>  ShaderManager.cpp
1>D:\Program Files\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory (compiling source file GLES\FragmentTestCache.cpp)
1>D:\Program Files\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory (compiling source file GLES\Framebuffer.cpp)
1>  StateMapping.cpp
1>D:\Program Files\Development\projects\ppsspp\native\base/logging.h(17): fatal error C1083: Cannot open include file: 'stdio.h': No such file or directory (compiling source file GLES\GLES_GPU.cpp)
1>  StencilBuffer.cpp
1>  TextureCache.cpp
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\winnt.h(31): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file GLES\ShaderManager.cpp)
1>  TextureScaler.cpp
1>D:\Program Files\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory (compiling source file GLES\StencilBuffer.cpp)
1>D:\Program Files\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory (compiling source file GLES\TextureCache.cpp)
1>  TransformPipeline.cpp
1>  VertexShaderGenerator.cpp
1>D:\Program Files\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory (compiling source file GLES\TextureScaler.cpp)
1>D:\Program Files\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory (compiling source file GLES\StateMapping.cpp)
1>  GPUCommon.cpp
1>  GPUState.cpp
1>GLES\VertexShaderGenerator.cpp(18): fatal error C1083: Cannot open include file: 'stdio.h': No such file or directory
1>D:\Program Files\Development\projects\ppsspp\native\base/logging.h(17): fatal error C1083: Cannot open include file: 'stdio.h': No such file or directory (compiling source file GLES\TransformPipeline.cpp)
1>  Math3D.cpp
1>D:\Program Files\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory (compiling source file GPUCommon.cpp)
1>  NullGpu.cpp
1>D:\Program Files\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory (compiling source file GPUState.cpp)
1>  Clipper.cpp
1>D:\Program Files\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory (compiling source file Math3D.cpp)
1>  Lighting.cpp
1>  Rasterizer.cpp
1>D:\Program Files\Development\projects\ppsspp\Common/Common.h(23): fatal error C1083: Cannot open include file: 'stdlib.h': No such file or directory (compiling source file Null\NullGpu.cpp)
1>D:\Program Files\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory (compiling source file Software\Clipper.cpp)
1>  SoftGpu.cpp
1>D:\Program Files\Development\projects\ppsspp\native\base/basictypes.h(4): fatal error C1083: Cannot open include file: 'stdlib.h': No such file or directory (compiling source file Software\Rasterizer.cpp)
1>D:\Program Files\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory (compiling source file Software\Lighting.cpp)
1>  TransformUnit.cpp
1>  TextureDecoder.cpp
1>D:\Program Files\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory (compiling source file Software\SoftGpu.cpp)
1>D:\Program Files\Development\projects\ppsspp\ext/xxhash.h(70): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory (compiling source file Common\TextureDecoder.cpp)
1>D:\Program Files\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory (compiling source file Software\TransformUnit.cpp)
2>------ Build started: Project: PPSSPPHeadless, Configuration: Release x64 ------
3>------ Build started: Project: PPSSPPWindows, Configuration: Release x64 ------
4>------ Build started: Project: UnitTest, Configuration: Release x64 ------
2>  glew.c
2>C:\Program Files (x86)\Windows Kits\8.1\Include\um\winnt.h(31): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory
3>  stdafx.cpp
3>C:\Program Files (x86)\Windows Kits\8.1\Include\um\winnt.h(31): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory
4>LINK : fatal error LNK1181: cannot open input file 'D:\Program Files\Development\projects\ppsspp\Windows\x64\Release\GPU.lib'
========== Build: 0 succeeded, 4 failed, 7 up-to-date, 0 skipped ==========

**Comment by LunaMoo** [comment]
Try adding  $(UniversalCRT_IncludePath) to AdditionalIncludeDirectories
http://blogs.msdn.com/b/vcblog/archive/2015/03/03/introducing-the-universal-crt.aspx
https://msdn.microsoft.com/en-us/library/bb531344.aspx

**Comment by troopermax** [comment]
I was trying this too... I'm just getting back into Visual Studio development, so don't put too much stock in my experience - I was just trying to hack it to make it build, but not being able to find stdio.h and such is simply the first problem.

Adding an include directory can solve all those compile problems (for me it was C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt - I hardcoded it in, but probably good to try the variable LunaMoo mentioned).

Then came the link errors - I had a multiply defined symbol which I forced using /FORCE:MULTIPLE linker option to make it a warning:
libucrt.lib(hypot.obj) : warning LNK4006: hypot already defined in avutil.lib(display.o); second definition ignored

Then there were unresolved symbols, some of which I was able to resolve by linking against legacy_stdio_definitions.lib. I found a reference to some stdio functions being inlined now in 2015:
http://www.cmake.org/Bug/view.php?id=15659
"With Visual Studio 2015, those functions are now defined *inline* in stdio.h."
So that means if the library were built against 2015, it would have had those functions inlined into it, so it wouldn't have to look elsewhere for those symbols, so now those symbols aren't normally provided except that Microsoft realized this could be a problem, so they provided a .lib with the symbols for legacy support. (For reference, mine had various versions under C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\lib)

I may have manually added the ucrt.lib/libucrt.lib libraries too, which not sure if that should have been necessary.

Still have a couple unresolved symbols though:
1>avutil.lib(log.o) : error LNK2019: unresolved external symbol __iob_func referenced in function av_log_default_callback
1>avutil.lib(snprintf.o) : error LNK2019: unresolved external symbol _vacopy referenced in function avpriv_vsnprintf
1>avutil.lib(bprint.o) : error LNK2001: unresolved external symbol _vacopy
1>..\PPSSPPWindows64.exe : fatal error LNK1120: 2 unresolved externals 

I think the larger problem here though is that ffmpeg needs to be rebuilt with Visual Studio 2015, which it sounds like they are working on:
https://github.com/hrydgard/ppsspp/issues/7896

So I may just wait for that.

~Troop

**Comment by thedax** [comment]
@troopermax: You pretty much hit the nail on the head. FFMPEG needs to be recompiled, and a couple adjustments need to be made to one of the projects, as well as a couple lines of code in the software GPU need to be fixed up. Other than that, once we get around to it, it should compile without hassle.

**Comment by thedax** [comment]
I think we can safely roll this up into #7896. The errors mentioned in the first post by @pal1000 are solved by editing the PPSSPPWindows project, as I mentioned in the other issue.
