### ISSUE TITLE
iPhone 8.3 Jailbreak - PPSSPP not showing

### ISSUE THREAD

**Issue by DrKiddy** [hrydgard/ppsspp#7876]
After I downloaded PPSSPP from cydia, I looked for it and found no sign of it on my phone. I hope this can be fixed as I'm desperate to play a game. Please let me know if it's a problem I can fix on my own or if you are fixing it, thank you.

**Comment by brujo5** [comment]
install powerapp from cydia

open it
1 refresh cache
2 respring

**Comment by DrKiddy** [comment]
Thanks mate, this seems to be the trick :)

**Comment by hrydgard** [comment]
@angelXwind seems we're getting lots of reports of this, any idea why suddenly now?

**Comment by angelXwind** [comment]
@hrydgard I haven't changed anything in regards to the iOS build code.

What I think is happening is that a system daemon known as `installd` is crashing before it gets to cache PPSSPP for some people who have installed my [AppSync Unified](https://github.com/angelXwind/AppSync) package, and also some iOS piracy tools.

As a result, `installd` never gets a chance to write PPSSPP to the cache, and therefore never "appears."

Here's some information about that bug: https://www.reddit.com/r/jailbreak/comments/3dsp9b/update_release_appsync_unified_56_now_with_full/ct8alrt
