### ISSUE TITLE
Blazblue Continuum Shift 2 (ULUS10579) black screen in-game with buffered rendering.

### ISSUE THREAD

**Issue by ofry** [hrydgard/ppsspp#7877]
In battle screen (for sample, tutorial) if I set rendering to Buffered, I got black screen with 60 FPS (music still playing, game still running). If I set it to "Skip buffer effects", I got proper game screen back.

**Comment by ppmeis** [comment]
I tested same game a few minutes ago, no issues under Windows 10 x64. Which platform are you using? Which device? Please give us more information.

**Comment by ofry** [comment]
PC. Windows 7 Ultimate x64. CPU Core 2 Quad Q9505
GPU: ATI Radeon HD 7700 series

Renderer: OpenGL.

All start fine if I start new game, BUT if I go to battle and switch render type, make a screenshot, etc. I got black screen instead of game.

**Comment by ppmeis** [comment]
@ofry I tested changing between BR and NBR and everything works fine, even screenshot feature works well. Are you using latest svn version?

**Comment by ofry** [comment]
Yes. Maybe you used fonts came with PPSSPP? If I move original fonts from TA-088v3 PSP-2000, I got this behavior.

Yes, I always update PPSSPP from orphis buildbot.

**Comment by ofry** [comment]
Latest git version is v1.0.1-790-g07b1756

**Comment by ofry** [comment]
Tested with PPSSPP fonts. Same bug :(

What GPU you have?

**Comment by ofry** [comment]
Ah, found source of bug. If you turned ON "Multithreaded (experimental)" then you will get this behavior.

If you turned it "OFF", then all fine AND with "Skip buffer effects", and with "Buffered rendering".

**Comment by ppmeis** [comment]
@ofry there are bugs already using multithread, this option is in a very early state though. De recommend not to use by default.
