### ISSUE TITLE
Regression on iOS

### ISSUE THREAD

**Issue by dona12345** [hrydgard/ppsspp#7879]
I have to say that on iPad 1g ppsspp doesn't work since 1.0 there is any solution?

**Comment by brujo5** [comment]
ipad 1g is very old hardware.

**Comment by asbel123** [comment]
ipad 1 g is super weak u cant go to ios 6.0 firmware thats why ppsspp doesnt work.

**Comment by dona12345** [comment]
Thanks you both,so i Will just play ppsspp with my note 2 4g

Inviato da iPad

Il giorno 27/lug/2015, alle ore 10:27, "asbel123" <notifications@github.com> ha scritto:

**Comment by thedax** [comment]
There's not really anything to fix here, so closing this.
