### ISSUE TITLE
Compiling PPSSPP for iOS problems

### ISSUE THREAD

**Issue by dantheman213** [hrydgard/ppsspp#7880]
Hello,

I attempted to generated the iOS xcode project but received several errors. Here is the output from the terminal:

Daniels-MacBook-Pro:ppsspp dan$ ./b.sh --ios
Building for iOS
~/Desktop/src_projects/ppsspp/build-ios ~/Desktop/src_projects/ppsspp
Building for ARMv7, Release
CMake Warning (dev) at CMakeLists.txt:281 (get_property):
  Policy CMP0051 is not set: List TARGET_OBJECTS in SOURCES target property.
  Run "cmake --help-policy CMP0051" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Target "Core" contains $<TARGET_OBJECTS> generator expression in its
  sources list.  This content was not previously part of the SOURCES property
  when that property was read at configure time.  Code reading that property
  needs to be adapted to ignore the generator expression using the
  string(GENEX_STRIP) command.
Call Stack (most recent call first):
  CMakeLists.txt:1437 (setup_target_project)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at CMakeLists.txt:612 (add_library):
  Cannot find source file:

    native/ext/cityhash/city.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error at CMakeLists.txt:630 (add_library):
  Cannot find source file:

    native/ext/libzip/zip.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error at CMakeLists.txt:857 (add_library):
  Cannot find source file:

    native/math/fast/fast_matrix_neon.S

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error at CMakeLists.txt:701 (add_library):
  Cannot find source file:

    native/ext/libpng17/pngconf.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error at CMakeLists.txt:411 (add_library):
  Cannot find source file:

    native/ext/rg_etc1/rg_etc1.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error at CMakeLists.txt:416 (add_library):
  Cannot find source file:

    native/ext/stb_vorbis/stb_vorbis.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error at CMakeLists.txt:404 (add_library):
  Cannot find source file:

    native/ext/vjson/json.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

make: *** No targets specified and no makefile found.  Stop.
Daniels-MacBook-Pro:ppsspp dan$

**Comment by unknownbrackets** [comment]
You need to run `git submodule update --init`.  You don't have all the code.

-[Unknown]

**Comment by dantheman213** [comment]
ah, I didn't see the .gitmodules file initially. Thank you. I ran again and it did generate a xcodeproj in build-ios/ .

I attempted to build for the device. It said "Build Successful" but says there are 2 errors and doesn't install to my phone. I have a vanilla OS (not jailbroken) but I have a developer account.

I have attached a screenshot of what I'm seeing.
<img width="1440" alt="screen shot 2015-07-26 at 7 49 25 am" src="https://cloud.githubusercontent.com/assets/10934533/8894419/24adf9ae-336b-11e5-9efb-89990a6188d1.png">

**Comment by unknownbrackets** [comment]
Yeah, I'm not sure about that.  I know it was added here:

https://github.com/hrydgard/ppsspp/issues/6972#issuecomment-58841415
https://github.com/hrydgard/ppsspp/commit/31b07d557137aea204efe83dd0359d058eca8c76

And I'm not sure why it's needed.  It seems like it's caused a few people errors.  Reverting that commit may fix it for you.  I'm not sure if this means you've got gtar as your tar or what.

-[Unknown]

**Comment by dantheman213** [comment]
Okay, I was able to figure it out. OSX uses a different version of tar then what runs on most distributions of Linux. So what I did was basically install the GNU version of tar on OSX via brew and then move that into place of Apple's version. Here is what I did:

1. Get brew if you don't have it already ( http://brew.sh/ )
2. Open Terminal

brew install gnu-tar
cd /usr/bin
sudo su
[after becoming root user]
mv tar tar.old
ln -s /usr/local/opt/gnu-tar/libexec/gnubin/tar tar

Then I tried to build again and it worked.

**Comment by dantheman213** [comment]
And just for reference, I'm running the latest version of everything.
- XCode 6.3
- OSX 10.10.4
- iOS SDK 8.3

**Comment by dantheman213** [comment]
There was one additional step I had to take to get the app to build. Besides obvious errors like code signing (set your own up and select the latest SDK). I also would get it to build successfully but not execute the app on the device. You may encounter this if you attempt to build so follow this for remedy:
http://stackoverflow.com/questions/8244953/xcode-successfully-builds-my-target-but-does-not-run-the-product

**Comment by estherzinn** [comment]
@dantheman213 Hello! Had a question, when I try to mv tar tar.old after becoming the superuser, it says operation not permitted. How did you override that?
