### ISSUE TITLE
UI text regression

### ISSUE THREAD

**Issue by vnctdj** [hrydgard/ppsspp#7884]
**OldGamers** posted [this thread](http://forums.ppsspp.org/showthread.php?tid=16243&pid=109194) on the forum about the following regression in the UI.

It appears that https://github.com/hrydgard/ppsspp/commit/381e0c0fe372b69b01f0a8c86b373ac28e96775a is the culprit.

In these before/after screenshots, you can see that the text from the box is now "cropped" :
![good](https://cloud.githubusercontent.com/assets/3978690/8983746/0c01a724-36cd-11e5-8607-33b903b360a1.png)
![bad](https://cloud.githubusercontent.com/assets/3978690/8983750/1106eba8-36cd-11e5-8777-4a1e0033b292.png)

**Comment by hrydgard** [comment]
Thank you for finding the culprit, I'll take a look as soon as possible.

**Comment by hrydgard** [comment]
@vnctdj heh, that took a while for me to get around to it, but fixed now.

**Comment by vnctdj** [comment]
Nice !
Thank you :)
