### ISSUE TITLE
Scalling Issue

### ISSUE THREAD

**Issue by GamerzHell9137** [hrydgard/ppsspp#7886]
Its happening again
http://puu.sh/jlMCn/9dddd80cd4.jpg

Set screen size x1 and then maximize the screen, the UI will be the same size.
Using latest nightly build http://puu.sh/jlMJr/cd6951b5f1.png

**Comment by ppmeis** [comment]
Issue confirmed with latest build:
![image](https://cloud.githubusercontent.com/assets/4381277/9157617/1697cf34-3f05-11e5-9ca1-ddbfcd64c79c.png)
