### ISSUE TITLE
LocoRoco 2 video black screen

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#7887]
25:26:905 ptnPsmfVideo I[ME]: HW\MediaEngine.cpp:87 FF: Reference 2 >= 2
25:26:905 ptnPsmfVideo I[ME]: HW\MediaEngine.cpp:87 FF: error while decoding MB 2 0, bytestream 1541
25:26:905 ptnPsmfVideo I[ME]: HW\MediaEngine.cpp:87 FF: Cannot use next picture in error concealment
25:26:906 ptnPsmfVideo I[ME]: HW\MediaEngine.cpp:87 FF: Reference 2 >= 2

v1.0.1-799-gb5f7d93 full log:
https://gist.github.com/sum2012/15dee3192ef17361bbf8

**Comment by unknownbrackets** [comment]
If you copy out the `disc0:/PSP_GAME/USRDIR/data/movie/story_01.pmf` file from the debug menu and play with `ffplay`, does it play fine without any errors?

-[Unknown]

**Comment by sum2012** [comment]
No,it plays with error
![1](https://cloud.githubusercontent.com/assets/2177532/9027949/f76902e6-399a-11e5-88eb-52fbac80b0b1.png)

**Comment by SukharevAndrey** [comment]
It is still not fixed :(

**Comment by piau9000** [comment]
Yeah.
It seems that FFmpeg don't support the videos.
