### ISSUE TITLE
Multi controllers on ppsspp

### ISSUE THREAD

**Issue by Fadi5555** [hrydgard/ppsspp#7888]
Hi there.
Well I just wanna ask you can we play two controllers on one device like play tekken.
I have an iPad Air 2 if that help.
Thanks

**Comment by ppmeis** [comment]
No you can't. You need two consoles to play a multiplayer game. So it's impossible to play two players in one device.

**Comment by Fadi5555** [comment]
Thanks for replying.
But what about the video? He could connected until 4 controllers on one device. Is there any method?

**Comment by hrydgard** [comment]
Think about it. The PSP is a portable console, you could never play two players on one console on the real thing. Thus, the games don't support it, unlike games on the PS2 for example.
