### ISSUE TITLE
ios crash

### ISSUE THREAD

**Issue by shamel4700** [hrydgard/ppsspp#7889]
ppsspp crashes on ios5 when downloaded from official ppsspp repo

**Comment by asbel123** [comment]
u need ios 6 or ios 7 firmware stop asking for ppsspp support ios5 its finish go to andriod u need to complain go to somewhere elese.

**Comment by unknownbrackets** [comment]
If you would like to port to iOS 5, please feel free to do so.  However, it is unlikely to be very fast and AFAIU we've dropped support for iOS 5.

FWIW my 3GS was left behind on iOS 5 as well.  It barely works anymore anyway, and I've given up on any games really being playable on it, speed wise.

-[Unknown]

**Comment by shamel4700** [comment]
DUFFERS STUPID
