### ISSUE TITLE
Ghost In The Shell Stand Alone Complex locks up emulator when loading Mission 1.

### ISSUE THREAD

**Issue by acemod13** [hrydgard/ppsspp#7890]
After setting the up the equipment and selecting Start Mission, the emulator locks up, and I have to force shut down the emulator.

Hapens on version 1.0.1, builds 790 to 799.
It happens on the European version of the game.

**Comment by sum2012** [comment]
Are you tested on real psp ?

**Comment by acemod13** [comment]
Yeah, works fine.

**Comment by sum2012** [comment]
I see

**Comment by brujo5** [comment]
euro version is stuck for me but the usa version work fine

**Comment by nfjorgebueno** [comment]
It works very well for me in the official version 1.0.1 windows ppsspp

**Comment by unknownbrackets** [comment]
Does it work in the current version?

What's the first git build it stopped working in, and the last git build it did work in?

-[Unknown]

**Comment by sum2012** [comment]
I test with correct dump ,no problem
log: https://gist.github.com/sum2012/95d765d1de01aa80b3ee

**Comment by unknownbrackets** [comment]
Thanks, so sounds like it's either been fixed or that was a bad rip (or cheats or other settings are causing glitches.)  Closing.

-[Unknown]
