### ISSUE TITLE
My PS3 contoller is not recognize on Linux (ubuntu)

### ISSUE THREAD

**Issue by CalibanAngel** [hrydgard/ppsspp#7891]
Hello,

I'm trying to play on ppsspp with my PS3 controller on Ubuntu and when I want to configure the contole, the controller is not recognize. 
But when I test the controller with xboxdrv --detach-kernel-driver , all keys work.
Could you repaire the problem or should I configure something myself ?

Thanks you for your works

**Comment by lightfirst** [comment]
how to install xboxdrv --detach-kernel-driver ?
what are you using, USB or bluetooth

**Comment by lightfirst** [comment]
my control mapping. I installed qtsixa and connect using bluetooth.
![ubuntui-ppsspp](https://cloud.githubusercontent.com/assets/4612168/9134188/787d5d90-3d34-11e5-858b-36bece32bb16.png)

**Comment by CalibanAngel** [comment]
I use USB
For xboxdrv just install the package : sudo apt-get install xboxdrv
Next plug your controller and press the Playstation button.
Finally open a Terminal and enter the command : xboxdrv --detach-kernel-driver 
You can use xboxdrv --detach-kernel-driver --silent for hide events.

**Comment by CalibanAngel** [comment]
With few manipulation I succeed to connect my controller. I close the issue.
Thank you ppsspp developer for your work
