### ISSUE TITLE
Issues remaining with compiling under Visual Studio 2015

### ISSUE THREAD

**Issue by thedax** [hrydgard/ppsspp#7896]
PPSSPP won't compile with VS2015 under regular circumstances. Here's why:
* FFMPEG needs to be recompiled under VS2015 (I've done this with the latest snapshot as of today, for x86, but I saw a couple pull requests from a few months ago. Should I open a pull request once I have x64 done too? Or should I not bother for now?)
* dxerr.lib::DXGetErrorStringA can't be used anymore due to vsnprintf linker error: workaround is to use an alternate library provided by Microsoft: http://blogs.msdn.com/b/chuckw/archive/2012/04/24/where-s-dxerr-lib.aspx , or comment out the call to DXGetErrorStringA in D3D9Base, but that's just a hack.
* Software renderer won't compile because of unaligned parameter: 
```
>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\functional(483): error C2719: '_Func': formal parameter with requested alignment of 16 won't be aligned (compiling source file Software\Rasterizer.cpp)
6>  Software\Rasterizer.cpp(1348): note: see reference to function template instantiation 'std::function<void (int,int)>::function<Rasterizer::DrawTriangle::<lambda_1f80627eda2a032b9f43dd38a64e5b19>>(_Fx)' being compiled
6>          with
6>          [
6>              _Fx=Rasterizer::DrawTriangle::<lambda_1f80627eda2a032b9f43dd38a64e5b19>
6>          ]
```
Commenting those two lambda lines out compiles fine, but of course, it'll result in missing graphics or other problems when using the software GPU, so that's just a hack as well.

* The PPSSPPWindows project needs $(UniversalCRT_IncludePath) and $(UniversalCRT_LibraryPath_x86) / $(UniversalCRT_LibraryPath_x64) added to their respective areas and configurations

Aside from that, none of the other code needed to be changed on my end.

**Comment by unknownbrackets** [comment]
Hmm.  I guess we can just make v0/v1/v2 passed as VPackedf and convert.  My primary goal is to keep things SSE inside as much as possible.

Maybe we just use FormatMessage for the DX errors?

I guess we should think about updating to latest ffmpeg again and rebuilding for everyone.  I think there was a major release recently and it may have other improvements.

-[Unknown]

**Comment by thedax** [comment]
One weird thing is the alignment stuff was attempted to be addressed here: https://github.com/hrydgard/ppsspp/pull/7566 but it didn't really do anything.

**Comment by hrydgard** [comment]
I won't be fully available for another week, but after that I'll recompile FFMPEG in 2015, then we'll make the switch. Will have to figure out the alignment complaints of course...

**Comment by unknownbrackets** [comment]
It's possible that the alignment warnings are just newly reporting an existing issue.

-[Unknown]

**Comment by troopermax** [comment]
Glad to see y'all working on this - it'd be awesome in the future to also be able to build for both Windows and Android from Visual Studio 2015.

**Comment by hrydgard** [comment]
@thedax @troopermax This is now all done, VS2015 is now the only supported version of VS, and it works fine.

**Comment by thedax** [comment]
@hrydgard: Thanks for letting me know, and it's quite nice.
