### ISSUE TITLE
tearing with vsync on intel hd4600 (haswell) win7 

### ISSUE THREAD

**Issue by kevmitch** [hrydgard/ppsspp#7901]
First of all thanks for such a great emulator and making it open source. 

I've just started trying out ppsspp with FFI/II. I have found that in spite of enabling the vsync option within ppsspp, I still get tearing. It is most noticeable if in either of the starting castles you cause the player to continuously **run** left and right. It will be fine for the first couple of seconds until a tear appears at the top of the screen working its way down to the middle at which point there's a bit of judder and then a return to untorn frames after which the cycle repeats.

The Intel drivers themselves (I'm running the latest version - 10.18.14.4261 - 7/7/2015) don't seem to have any vsync related settings. I've observed the same behaviour in all four windows version [available for download](http://www.ppsspp.org/downloads.html) - namely 0.9.8, 0.9.9.1, 1.0, and 1.0.1.

Aside from configuring my controller, my only modification to the default settings is to enable vsync, as well as frame skipping and added audio latency to avoid stuttering. I have however experimented with choosing lower quality / faster settings for some the graphics processing settings that I remotely understood with the same results as above.

[my config](http://sprunge.us/KibP)

Interestingly, on my mobile HD4000 (Ivybridge Mobile) Linux machine I cannot spot any tearing with PPSSPPSDL (both git master and 1.0.1). When I try to reproduce it as above, I only get the frame drop judder from time to time, which I'm willing to accept as my graphics hardware not being cool enough.

**Comment by kevmitch** [comment]
I should add that I know that untorn vsync is possible on this windows machine as it is achived by [mpv-player/mpv](https://github.com/mpv-player/mpv) even when playing video at a variety of frame rates including those higher than that of the display.

**Comment by kevmitch** [comment]
ah, non-buffered rendering removes the judder on both platforms. tearing however remains on windows.

**Comment by kevmitch** [comment]
popped in an lubuntu 15.04 livecd to the haswell windows machine and indeed the PPSSPPSDL again exhibits no tearing there, so this appears to be a windows-specific, (not chip-set specific) issue.

**Comment by kevmitch** [comment]
1) For the record, apparently I'm an idiot and the intel driver **does** have a vsync setting (Intel Graphics Properties -> 3D -> General Settings -> Custom Settings -> Vertical Sync -> Application/Driver Settings) where Driver settings forces vsync on. This however Doesn't have any effect on this issue.

2) What does have an effect is switching to an aero theme. This results in no tearing! The tearing only happens when using a "basic" theme. I find this strange because I'm running in fullscreen, so should this even matter? This being the case, I'm not sure whether to consider this issue closed, or whether there should be some expectation that it should work without aero enabled.

**Comment by hrydgard** [comment]
Whatever the problem is, I don't think it's something PPSSPP has control over. Just run in Aero, I guess...
