### ISSUE TITLE
Sound going quiet in v1.0.1-809-gee2238d!

### ISSUE THREAD

**Issue by Joelgp83** [hrydgard/ppsspp#7902]
Hey guys, me again.  Been testing the windows x64 builds again, as I recieved a dualshock2-usb converter and wanted to test windows performance. :) 

The system is a laptop --  an AMD E1-1200 APU, so that's a dual-core 1.4ghz chip with a Radeon HD 7310 gpu, running latest catalyst on win8.1.

Anyway, been using v1.0.1-809-gee2238d, and as near as I can tell, ppsspp's own volume drops tremendously in the first half hour, and will not return to normal unless I exit and restart ppsspp.  Windows' own volume sliders indicate that no volume modification is being done, os-wise.

Games tested include FF Dissidia 012 and DBZ shin budokai another road.  Didn't really get a chance to test anything else.

Not sure if you guys would like/need logs in order to investigate, but I can get some if you want.

**Comment by Joelgp83** [comment]
So, possibly false alarm, guys.  Just encountered the same behaviour in Youtube, of all places.  This is starting to look like a Win8.1 / Realtek driver issue in general and not related to ppsspp.  This behaviour does not show up when running linux so it doesn't seem to be hardware fault, either.  Sorry guys.

**Comment by Joelgp83** [comment]
Ok, so research leads me to this solution: http://superuser.com/questions/504004/windows-8-turns-program-sound-volume-down-randomly

Apparantly something is causing windows to think I'm trying to use a mic during playback, and is triggering the auto-quiet-ing on its own.  Is there anything recent in ppsspp that's calling attention to the microphone?

**Comment by hrydgard** [comment]
No, we do not yet enable the microphone. However we did change audio backends fairly recently - added support for WASAPI and made that the default. You could try changing back to DSound in the settings.

I'll close this however as it's not really an issue with the emulator.
