### ISSUE TITLE
Final Fantasy IV The Complete Collection (ULUS10560) error code 80110326

### ISSUE THREAD

**Issue by ofry** [hrydgard/ppsspp#7903]
OS: Windows 8 Professional
PPSSPP v1.0.1-809-gee2238d

Way to reproduce:
1) Start the game, choose "Data install"
2) Try to launch Final Fantasy IV, go to Bestiary
3) Now you will get "error code 80110327" when trying to install system data.
4) Try to install data again. You will get "error code 80110326"

**Comment by ppmeis** [comment]
Tested with latest build and with EU version (ULES-01521). Also checked that the iso file is properly fixed (CRC 2BBFF0D5). Issue is present:
![image](https://cloud.githubusercontent.com/assets/4381277/9288803/a61fbc80-435a-11e5-94d1-faa39e4c5bc5.png)

**Comment by asbel123** [comment]
desnt need install data beacuse u using copied games it doesnt use umd u dont need to install u dumb. close that issue hygard.

**Comment by ppmeis** [comment]
@asbel123 emulator developers always try to do as accurate as possible. Intalla data is a PSP feature and it's working in a lot of games. So this is an issue to be fixed.
