### ISSUE TITLE
Dev-latest v1.0.1-811-g14fd313 on iOS: Tomb Raider Legend resumed to homescreen. 

### ISSUE THREAD

**Issue by scorpio16v** [hrydgard/ppsspp#7907]
https://github.com/hrydgard/ppsspp/commit/14fd3136b1220aefc93c89be591f3984224e47d7

This latest nightly caused Tomb Raider Legends to crash the emulator and it resumed to iOS home screen.
This didn't happen in the last nightly for iOS and before.
- device iPod Touch 6.gen iOS 8.4 jailbreaked
- PPSSPP dev-latest

- PPSSPP 1.0: game works fine like the previous dev-latest for iOS (can't remember the version number, sorry)

**Comment by unknownbrackets** [comment]
Unfortunately, "last nightly" isn't enough information.  The contributors here (including me) have no idea what the last nightly for iOS was, so it could have been broken 3 months ago.

If you or someone else can reproduce this problem on Windows, Mac, or Android, it would help a lot.  This would give us the actual version numbers where it worked and did not work.  If this problem only happens on iOS, it may be very hard to fix.

-[Unknown]

**Comment by brujo5** [comment]
No issue here!! Ip5S iOS 8.4

![image](https://cloud.githubusercontent.com/assets/4172898/9294857/e66bb6ba-4416-11e5-8749-2e41d12c17bb.jpg)
![image](https://cloud.githubusercontent.com/assets/4172898/9294858/e6893e74-4416-11e5-8d05-a1709e47a9ef.jpg)

**Comment by scorpio16v** [comment]
Can't explain what happened, but now the game starts fine.
I have redownloded this version of ppsspp. After the first start, the game caused the same error every time.
But after starting some other games, Tomb Raider Legends starts fine now.

So, you can marked the problem as solved.

**Comment by unknownbrackets** [comment]
Hmm, that doesn't really feel solved to me, but I'm thinking it might be a jailbreak stability issue, as we've seen other weird behavior on iOS.  I think we have an issue about that generally.

So okay, closing this.

-[Unknown]
