### ISSUE TITLE
Naruto  Ultimate Ninja Heroes 3 black screen

### ISSUE THREAD

**Issue by Slarker0k** [hrydgard/ppsspp#7909]
I have black screen when im trying to start Naruto Ultimate Ninja Heroes 3

**Comment by sum2012** [comment]
What device ? (Windows,Android,Ios ?)
What ppsspp version ?

**Comment by Slarker0k** [comment]
Windows 7 , ppsspp v1.0.1

**Comment by sum2012** [comment]
Try download newest version (v1.0.1-811-g14fd313)
in http://buildbot.orphis.net/ppsspp/

**Comment by sum2012** [comment]
If still fail (even not update ppsspp version),
Run InfoLog.bat
Start the game until black screen
Open ppsspplog.txt , plaste the content into http://gist.github.com/
Share the link

**Comment by Slarker0k** [comment]
https://gist.github.com/Slarker0k/36759fec8afacc4937b2

**Comment by sum2012** [comment]
Try this build
(If fail ,please post updated log,thanks)
https://drive.google.com/file/d/0B3OaSdeV0L8kWkhSbjZxX2VmYm8/view?usp=sharing

**Comment by Slarker0k** [comment]
thx

**Comment by sum2012** [comment]
No,the fix isn't merge , should re-open.
Anyway,PPSSPP doesn't really support patched iso.

**Comment by sum2012** [comment]
ok , now you can close this

**Comment by yihern0905** [comment]
wyh my naruto shippuden ninja heroes 3 is black screen also
how to fix?

**Comment by jack00** [comment]
You can use the skip intro movie code to solve the black screen problem. #9591

**Comment by Sailesh406** [comment]
I am having black screen problems on Naruto ultimate ninja heroes 3
