### ISSUE TITLE
Segfault on Raspberry Pi 2 B/Archlinux ARM

### ISSUE THREAD

**Issue by noroimusha** [hrydgard/ppsspp#7913]
Hello everyone,

I have built PPSSPPSDL using the method of mihailescu2m, but I can't start it.

The building steps are:

https://github.com/hrydgard/ppsspp/issues/7479#issuecomment-75403013 

What could be the reason? 

Thanks!

```
./PPSSPPSDL
Pixels: 1280 x 720
Virtual pixels: 1280 x 720
I: /home/konstantin/builds/ppsspp/native/thin3d/thin3d_gl.cpp:229: I: Vertex Shader compile error:

I: /home/konstantin/builds/ppsspp/native/thin3d/thin3d_gl.cpp:229: I: Vertex Shader compile error:

I: /home/konstantin/builds/ppsspp/native/thin3d/thin3d_gl.cpp:229: I: Fragment Shader compile error:

I: /home/konstantin/builds/ppsspp/native/thin3d/thin3d_gl.cpp:229: I: Fragment Shader compile error:

E: /home/konstantin/builds/ppsspp/native/thin3d/thin3d_gl.cpp:571: E: ShaderSet requires both a valid vertex and a fragment shader: (nil) (nil)
E: /home/konstantin/builds/ppsspp/native/thin3d/thin3d_gl.cpp:571: E: ShaderSet requires both a valid vertex and a fragment shader: (nil) (nil)
I: /home/konstantin/builds/ppsspp/native/gfx_es2/gl_state.cpp:137: I: GPU Vendor : (null) ; renderer: N/A version str: N/A ; GLSL version str: N/A
Segmentation fault (core dumped)

**Comment by GAMELASTER** [comment]
Wow, really good work, anyway, can u provide steps how u build that? :-)

Back to main, its looks is something with libraries or what, mainly, if its says is GPU Vendor and Renderer null.

**Comment by noroimusha** [comment]
@GAMELASTER the steps are taken from the topic which you have authored, you can find them by clicking the link in the 1st post. :D

Could my errors be related to a wrong X11 config?

**Comment by GAMELASTER** [comment]
@noroimusha i know its from my issue (topic) :D but i tested it do but for me its not work. But i still see all works on ArchLinuxARM, so its problem on Raspbian or with my build, i will now try it on ArchLinuxARM.

About X11, if it will be a trouble of wrong X11, the error says a SDL, not a PPSSPP "core".
But, just only for try (its not must be related), check CMakeLists and look RPI settings, you should a enable FBDEV, that helps to me, but its just my think :-)

**Comment by GAMELASTER** [comment]
#7815 Here have sergio same problem but on odroid

**Comment by noroimusha** [comment]
@GAMELASTER
yes, but it's unanswered :-(

**Comment by GAMELASTER** [comment]
@noroimusha try to wait to @sergiobenrocha2 , its little inactive these days i thought. Anyway, i too successfuly build a PPSSPP, and i have too trouble Segmentation Fault, but i have it so much earlier. Anyway, try this:
```
gdb PPSSPPSDL
run
bt full
quit
```
Then all what its output put here, you backtrace maybe useful than me :D

**Comment by unknownbrackets** [comment]
How is this different from #7479?  They both seem like issues with getting OpenGL working properly.

If there's unique information in this issue, wouldn't it help more for it to be in #7479?  I don't think having two, three, or more issues about the same problem will lead to a quicker resolution - it just means more spam and more people reading only one or the other and not bringing all the pieces together.

As such, I'm closing this.

-[Unknown]
