### ISSUE TITLE
"Please switch your display to 32-bit colour mode" error using front end

### ISSUE THREAD

**Issue by Carpariath** [hrydgard/ppsspp#7921]
Hello,
When I load PPSSPP (last build revision) from the explorer, or using a batch (this validates the right arguments - only a ISO name), everything works perfectly.
But when calling the emulator from the frontend "AtomicFE", the error "Please switch your display to 32-bit colour mode" displays 19/20 times. 1/20 it strangely works...
It seems related to the way AtomicFE calls executables, and maybe has something to do with the emulator GUI, but as AtomicFE doesn't fail on running other emulators (it runs 15 exe without any problem of this kind), I think something may be wrong with PPSSPP...
Do you have any idea?

**Comment by hrydgard** [comment]
Here's the relevant code:

	HDC dc = GetDC(NULL);
	u32 colour_depth = GetDeviceCaps(dc, BITSPIXEL);
	ReleaseDC(NULL, dc);
	if (colour_depth != 32){
		MessageBox(0, L"Please switch your display to 32-bit colour mode", L"OpenGL Error", MB_OK);
		ExitProcess(1);
	}

I think I'm just going to delete that check, seems fairly pointless. If people really want to run in low color modes (or future higher modes) they should be able to.

Now, I have no idea why GetDeviceCaps(dc, BITSPERPIXEL) would return a different value. But let's start with trying that...

**Comment by hrydgard** [comment]
@Carpariath  please test if the latest build still exhibits the issue.

**Comment by Carpariath** [comment]
Yep, we're done with it!
Without any surprises, it works now. But the mystery remains ;)
Thank you!
