### ISSUE TITLE
Dante's Inferno - Crash Issue

### ISSUE THREAD

**Issue by freyresoft** [hrydgard/ppsspp#7923]
Have tried stable and latest git version and still crash, here is the log

33:50:193 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2173 289=sceKernelCreateThread(FMOD SAS update/mix thread, 08b66a98, 00000008, 65536, 00004000, 00000000)
33:50:194 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2244 0=sceKernelStartThread(289, 12, 08c2df80)
33:50:195 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2173 296=sceKernelCreateThread(FMOD stream thread, 08b66a98, 0000000c, 16384, 00004000, 00000000)
33:50:195 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2244 0=sceKernelStartThread(296, 12, 08c31c10)
33:50:199 user_main    I[IO]: HLE\sceIo.cpp:916 stdout: Engine using EN for language path!
33:50:199 user_main    I[IO]: HLE\sceIo.cpp:916 stdout: Build Version 3.3.1756
33:50:199 user_main    I[HLE]: HLE\scePower.cpp:369 scePowerSetClockFrequency(333,333,162)
33:50:201 user_main    W[DISP]: HLE\sceDisplay.cpp:767 sceDisplaySetMode INVALID SIZE (0, 0, 0)
33:50:217 user_main    I[IO]: HLE\sceIo.cpp:916 stdout: <OK
33:50:243 user_main    I[IO]: HLE\sceIo.cpp:916 stdout: >L
33:50:245 user_main    I[KERNEL]: HLE\sceKernelMemory.cpp:1151 sceKernelPrintf: Logic relocation to 0x0b2348b0
33:50:251 user_main    I[IO]: HLE\sceIo.cpp:916 stdout: <OK
33:50:274 user_main    I[IO]: HLE\sceIo.cpp:916 stdout: >L
33:51:524 user_main    I[KERNEL]: HLE\sceKernelMemory.cpp:1151 sceKernelPrintf: Logic relocation to 0x0b24ed90
33:51:625 user_main    I[IO]: HLE\sceIo.cpp:916 stdout: <OK
33:51:691 user_main    I[SCEGE]: Common\FramebufferCommon.cpp:370 Creating FBO for 00000000 : 512 x 272 x 0
33:51:691 user_main    W[G3D]: Common\FramebufferCommon.cpp:561 Memcpy fbo upload 04400000 -> 04000000
33:51:701 user_main    I[SCEGE]: Common\FramebufferCommon.cpp:370 Creating FBO for 00088000 : 512 x 272 x 3
33:51:726 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2173 308=sceKernelCreateThread(Bink audio thread, 08b2830c, 0000000e, 32768, 00004000, 00000000)
33:51:726 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2244 0=sceKernelStartThread(308, 0, 00000000)
33:51:743 Bink audio t I[KERNEL]: HLE\sceKernelThread.cpp:2322 sceKernelExitDeleteThread(0)
33:51:743 user_main    W[KERNEL]: hle\sceKernel.h:460 Kernel: Bad object handle 308 (00000134)
33:51:743 user_main    E[KERNEL]: HLE\sceKernelThread.cpp:2769 sceKernelWaitThreadEnd - bad thread 308
33:51:743 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2173 311=sceKernelCreateThread(Bink audio thread, 08b2830c, 0000000e, 32768, 00004000, 00000000)
33:51:743 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2244 0=sceKernelStartThread(311, 0, 00000000)
33:51:744 Bink audio t I[KERNEL]: HLE\sceKernelThread.cpp:2322 sceKernelExitDeleteThread(0)
33:51:744 user_main    W[KERNEL]: hle\sceKernel.h:460 Kernel: Bad object handle 311 (00000137)
33:51:744 user_main    E[KERNEL]: HLE\sceKernelThread.cpp:2769 sceKernelWaitThreadEnd - bad thread 311
33:51:744 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2173 314=sceKernelCreateThread(Bink audio thread, 08b2830c, 0000000e, 32768, 00004000, 00000000)
33:51:744 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2244 0=sceKernelStartThread(314, 0, 00000000)
33:52:209 user_main    I[IO]: HLE\sceIo.cpp:916 stdout: >L
33:52:211 user_main    I[IO]: HLE\sceIo.cpp:916 stdout: >L
33:52:346 user_main    I[IO]: HLE\sceIo.cpp:916 stdout: <OK
33:52:347 user_main    I[IO]: HLE\sceIo.cpp:916 stdout: >L
33:52:601 user_main    I[IO]: HLE\sceIo.cpp:916 stdout: <OK
33:52:602 user_main    I[IO]: HLE\sceIo.cpp:916 stdout: >L
33:53:393 user_main    I[IO]: HLE\sceIo.cpp:916 stdout: <OK
33:53:396 user_main    I[IO]: HLE\sceIo.cpp:916 stdout: >L
33:53:543 user_main    I[IO]: HLE\sceIo.cpp:916 stdout: <OK
33:53:693 user_main    I[IO]: HLE\sceIo.cpp:916 stdout: <OK

**Comment by sum2012** [comment]
What is the gameID ? (Like NPJH50043)

**Comment by freyresoft** [comment]
52:44:333 PSPLoaders.cpp:168 I[LOAD]: ULUS10469 : Dante's Inferno™

**Comment by freyresoft** [comment]
I have uploaded the save state so you guys can test, it is located at http://www.freyre.com/psp/PPSSPP_STATE.rar , you need to jump and get into the moving wheels.

**Comment by sum2012** [comment]
Update save state
https://drive.google.com/file/d/0B3OaSdeV0L8kV0dSRC1EOXM2VTg/view?usp=sharing
Just move into wheels

**Comment by sum2012** [comment]
@freyresoft In the real psp,what will it expect after wheels ?

**Comment by sum2012** [comment]
@unknownbrackets 
v1.0.1-828-gf3e0029 debug log:
https://gist.githubusercontent.com/sum2012/ef32614fa65bcaa60765/raw/f3b7e6665ef5916416adf9b011f1709c024abcab/gistfile1.txt

**Comment by freyresoft** [comment]
I have tried your save state the the ppsspp crash as soon as it load, here are the last messages from the log, I think after wheels there is a door to open.

08:36:958 user_main    W[FONT]: HLE\sceFont.cpp:677 Font file not found: flash0:/font/zh_gb.pgf
08:36:988 user_main    I[COMMON]: 266e7aa46db16f98\Common/ChunkFile.h:644 ChunkReader: Done loading D:\ppsspp_win\memstick/PSP\PPSSPP_STATE\ULUS10469_1.01_0.ppst
08:37:025 user_main    I[SCEGE]: Common\FramebufferCommon.cpp:370 Creating FBO for 00000000 : 512 x 272 x 0
08:37:039 user_main    I[SCEGE]: Common\FramebufferCommon.cpp:370 Creating FBO for 00088000 : 512 x 272 x 3
08:37:203 idle0        I[SCEGE]: Common\FramebufferCommon.cpp:370 Creating FBO for 00110000 : 512 x 272 x 3
08:37:224 idle0        W[SCEGE]: Common\FramebufferCommon.cpp:406 FBO reusing depthbuffer, 00110000/00044000 and 00000000/00044000
08:37:241 idle0        W[G3D]: Directx9\TextureCacheDX9.cpp:414 Render to area containing texture at 00110000 +256x0
08:37:268 idle0        I[SCEGE]: Directx9\FramebufferDX9.cpp:1188 Destroying FBO for 00000000 : 512 x 272 x 0
08:37:268 idle0        I[SCEGE]: Directx9\FramebufferDX9.cpp:1188 Destroying FBO for 00088000 : 512 x 272 x 3
08:37:268 idle0        I[SCEGE]: Directx9\FramebufferDX9.cpp:1188 Destroying FBO for 00110000 : 512 x 272 x 3
08:37:304 user_main    I[SCEGE]: Common\FramebufferCommon.cpp:370 Creating FBO for 00000000 : 512 x 272 x 0
08:37:305 user_main    I[SCEGE]: Common\FramebufferCommon.cpp:370 Creating FBO for 00088000 : 512 x 272 x 3
08:37:317 idle0        I[SCEGE]: Common\FramebufferCommon.cpp:370 Creating FBO for 00110000 : 512 x 272 x 3
08:37:333 idle0        W[SCEGE]: Common\FramebufferCommon.cpp:406 FBO reusing depthbuffer, 00110000/00044000 and 00000000/00044000
08:37:443 user_main    I[IO]: HLE\sceIo.cpp:916 stdout: <OK
08:37:571 user_main    I[IO]: HLE\sceIo.cpp:916 stdout: >U
08:37:572 user_main    I[IO]: HLE\sceIo.cpp:916 stdout: >L
08:38:144 user_main    I[IO]: HLE\sceIo.cpp:916 stdout: <OK

**Comment by freyresoft** [comment]
An update, I have downloaded the EU version and used the USA save state in there and was able to get to the the door, probably the USA version is broken, dont know.

**Comment by freyresoft** [comment]
Other update, passing the door there was some walls to climb and after I go back to the floor the ppsspp crashed again, then I loaded the new save state on the USA version and was able to pass without crash, I guess for now the only way to play Dantes on ppsspp is having both versions and use the save states on the other version when it crash.

**Comment by sum2012** [comment]
@freyresoft do you have game 's save ? (not save status)
I want test in real psp.

**Comment by freyresoft** [comment]
Sadly no, I have continue with the game and overwrote it.

**Comment by unknownbrackets** [comment]
Have you checked that your iso is a clean rip?  For example checking the crc or pulling it off your disc again?

The EU version probably has slightly different files on the disc.  It could be a difference in audio files or something.  Not sure.

-[Unknown]

**Comment by daniel229** [comment]
ULUS10469 also crashes in PSP.

**Comment by LunaMoo** [comment]
Doesn't happen to me, loaded savestate, jumped on the wheels and passed it following up to next savepoint without any problems(not counting rainbow graphics:P).
![ulus10469_00000](https://cloud.githubusercontent.com/assets/5485237/9546912/d3124b04-4d96-11e5-8f38-a41df5186476.jpg)

 You might like to listen to [Unknown] and check your copy, since it loads some file/s there and for all of you it seems to be corrupted or something.

Here's some hashes from my clean US version iso made from umd:
CRC32: db54d4a0
MD5: ae91c5d0dcd933329b81efb5a194a227
SHA-1: 579df44399a0ecb16ffe4bd195e6afdf4b49b900

**Comment by daniel229** [comment]
The bad one CRC32 is 459AA5FE.
Another good one from PSN CRC32 is F6400FC2.

**Comment by unknownbrackets** [comment]
Okay, so it's a bad rip.  Better to rip from your own disc, and obviously to buy the game.  Unless you want them to make more Facebook and mobile games where you pay for every little thing, because people pay for those.

-[Unknown]
