### ISSUE TITLE
Try port proyect to x360

### ISSUE THREAD

**Issue by metalex10** [hrydgard/ppsspp#7926]
please friend port you proyect to x360?

check this:https://github.com/Ced2911/ppsspp

**Comment by hrydgard** [comment]
Yes, we had a 360 port earlier, but Ced didn't have time for it anymore and no one else had a hacked 360, so the port died. Ports, especially to platforms as exotic as the 360, need maintenance to keep up.

**Comment by unknownbrackets** [comment]
You are more than welcome to take over and fully maintain it.  It's not a small amount of work, though.

-[Unknown]
