### ISSUE TITLE
D3D vsync prevents unthrottle from working right (plus, fixed hotkey bug)

### ISSUE THREAD

**Issue by vsub** [hrydgard/ppsspp#7929]
1.If you set any hotkey for "Save State",pressing F2 anywhere except the game pause screen,it will bring the language selection menu(I check the source but I didn't find anywhere anything about hotkey and that many)

2.If VSync is enabled while the video backend is Direct3D9,the unthrottle\alternative speed will be limited to 200% on 30fps games and 100% on 60fps games and to disable the vsync effect,you have to disable it and restart ppsspp(it won't work by just disabling it).
In my nvidia control panel,vsync is set to "Use the 3D application settings")

**Comment by lordemort** [comment]
maybe you could try this
http://buildbot.orphis.net/ppsspp/
find the newest version
hope it helps

**Comment by vsub** [comment]
I always try the lasted version of anything before posting.
And yes,I did tried the lasted beta 2 days ago and the current latest beta but both problems still exist.

When vsync is enabled and direct3d9 is used while running the cube.iso demo,the unthrottle\alternative speed does nothing

**Comment by hrydgard** [comment]
The hotkey problem sounds really strange, I'll take a look soon.

D3D vsync problem is known, although I forgot about it, will see what I can do, might be tricky due to how D3D work. We might have to resort to the same type of unthrottle we use on Android, that is, to actually skip frames instead of just drawing them faster.

**Comment by hrydgard** [comment]
I've tried to reproduce the hotkey problem but have so far failed... It seems normal.

**Comment by vsub** [comment]
This is what I just did.
1.Downloaded the latest x86 and x64 versions(tried both and I didn't configure anything)
2.From the menu above Game Settings=>Control Mapping
3.Clear all and set F1 for Save State hotkey(I didn't configure any other key)

Now pressing F2 anywhere outside a game,ppsspp will display the language selection list.
It is also possible that ppsspp tries to display the list like ingame but since the list can't be displayed while ingame(Game Settings=>Language),nothing happens

It's possible to see what ppsspp tries to do while pressing the hotkey(what code is trying to execute)

**Comment by hrydgard** [comment]
Tagged to investigate for 1.8.0

**Comment by hrydgard** [comment]
Found the language menu issue, committing fix.

**Comment by hrydgard** [comment]
I'm bumping the D3D9 problem up to 1.9.0, many more issues have higher priority...
