### ISSUE TITLE
Win32:D3D9 cannot see ppsspp version since v1.0.1-579-g00e57b1

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#7931]
@hrydgard 
![1](https://cloud.githubusercontent.com/assets/2177532/9566578/811b2890-4f3d-11e5-8eed-4cdc0dd330dc.jpg)
![2](https://cloud.githubusercontent.com/assets/2177532/9566581/85b3d1e0-4f3d-11e5-8dea-8722020ea0a5.jpg)

**Comment by hrydgard** [comment]
That's really odd, I'll take a look.

**Comment by hrydgard** [comment]
OK, got it, D3D handles invalid scissor regions differently (we have a layout bug causing them).

For now, I did a quick workaround.

**Comment by sum2012** [comment]
Thanks
