### ISSUE TITLE
When PPSSPP v1.1 release ?

### ISSUE THREAD

**Issue by zminhquanz** [hrydgard/ppsspp#7938]
@hrydgard , when it release , sir ?

**Comment by unknownbrackets** [comment]
When it happens.  But if you want a sneak peek - most of the cool things that'll be in v1.1 have already been released in a super secret pre-release build:

http://buildbot.orphis.net/ppsspp/

-[Unknown]

**Comment by FireyFly** [comment]
See also https://github.com/hrydgard/ppsspp/issues/7783 for a roadmap for 1.1.
