### ISSUE TITLE
Texture glitch in CGI video

### ISSUE THREAD

**Issue by vnctdj** [hrydgard/ppsspp#7939]
I have spotted a texture glitch in *Monster Hunter Freedom Unite*.
It happens in a CGI video, since https://github.com/hrydgard/ppsspp/commit/12884eceb99ca4b46c0d12504178ffa08fbd3e53.
I have made a video which compares the previous commit with this one :
https://www.youtube.com/watch?v=jKE0NLZcWz0
As you can see, the bottom of the wings have now red flashes :-/

Here is a savedata which contains the video : https://www.sendspace.com/file/8c34w7
Start the game, choose "Gallery" on the game menu and play video 52.

How can I help more ?

**Comment by hrydgard** [comment]
Wow, that's one of the oddest issues I've seen... 

Does it happen both with OpenGL and Direct3D?

**Comment by vnctdj** [comment]
Yes, it happens in both of them.

**Comment by vnctdj** [comment]
I bisected inside https://github.com/hrydgard/ppsspp/pull/7920 and here is the result :
https://github.com/hrydgard/ppsspp/commit/a5fb4cffd5faa8ffe62fa086cdf610737e0961bc is the last "good" commit.
https://github.com/hrydgard/ppsspp/commit/9e18fb7e908a61f3a9b3637ff0fd92ee10ac298b is the first "bad" commit, which has caused the issue.

**Comment by hrydgard** [comment]
I don't think that's CGI video. To me it looks like realtime, and that the front of the wings is Z-fighting with the back. I don't see how those glitches could possibly arise in CGI.

If so it might be very hard to fix while still keeping the PSO fixes. @vnctdj , also, did you compare it to a real PSP? :)

**Comment by vnctdj** [comment]
CGI or not CGI ? I don't really know, actually I was just guessing ;)

What do you mean by "PSO fixes" ?

Holy s*** it happens that my real PSP is drawing these red flashes ! ^^
But in a more "fading" way, look at these screenshots I made :

![pic_0002](https://cloud.githubusercontent.com/assets/3978690/10058176/666493b4-6244-11e5-9dd9-c83bf601f7ee.png)
![pic_0003](https://cloud.githubusercontent.com/assets/3978690/10058178/6b2c009e-6244-11e5-91a6-c83d88ae0d9b.png)

**Comment by unknownbrackets** [comment]
The screen on the PSP doesn't have the best response time.  It could be that this is just not as noticeable on real hardware, but is "correct" behavior.

-[Unknown]

**Comment by vnctdj** [comment]
Oh ok...
So, what I thought was a regression is actually an "improvement"... I'm amazed !

But that's definitely not good-looking, why game developers didn't fixed that ?

**Comment by hrydgard** [comment]
They probably didn't notice, or it was far down on their long list of bugs to fix before their deadline :)

I'll close this. Possibly we can add some kind of game specific configuration that allows 24-bit Z in games that can handle it in the future, but for now, this is just how it is.

**Comment by vnctdj** [comment]
OK, thank you for your reply :)

**Comment by LunaMoo** [comment]
Guess it was about Phantasy Star Portable not Online(grandmother of hunting games lol:)), althrough yeah this game name abbreviation is kind of confusing without number ~ PSP, often want to call it PSO as well >.>
