### ISSUE TITLE
Tests from "Test analogs" screen are not visual anymore

### ISSUE THREAD

**Issue by vnctdj** [hrydgard/ppsspp#7940]
Since https://github.com/hrydgard/ppsspp/commit/bbde0919d8be42ff2b18754fb4eb887225568ff3, when you move your analogs some infos are written in a line of text but the cross doesn't move in the big square.

Here are 2 screenshots in order to demonstrate the issue :
-> before :
![g](https://cloud.githubusercontent.com/assets/3978690/9645212/8956f784-51ca-11e5-81ef-ec5aa0717d35.png)

-> after :
![b](https://cloud.githubusercontent.com/assets/3978690/9645272/d37eaf1e-51ca-11e5-8885-8e9ee35f376d.png)

**Comment by sum2012** [comment]
@FireyFly

**Comment by FireyFly** [comment]
Hm, whoops... will take a look tomorrow. It should be straightforward enough to fix, I hope.

**Comment by vnctdj** [comment]
Thanks :)

**Comment by hrydgard** [comment]
Simple thing, just went ahead and fixed it.

**Comment by vnctdj** [comment]
Thanks :)
