### ISSUE TITLE
v1.0.1-899-g1b4b60d Broken Hardware transform and Vsync

### ISSUE THREAD

**Issue by GamerzHell9137** [hrydgard/ppsspp#7949]
v1.0.1-899-g1b4b60d broke some stuff like Hardware transform and Vsync.
Once fullscreened Vsync won't work and while loading Project Diva Extend a message in red says " Hardware Transform error, falling back to software.

The error happens on PC.

**Comment by unknownbrackets** [comment]
#7950 fixes the hardware transform errors.  I never can reproduce vsync problems people have so probably can't help with that so much.

-[Unknown]

**Comment by hrydgard** [comment]
@GamerzHell9137 had to move some vsync code around, probably messed something up. I'll look into it.

**Comment by DonelBueno** [comment]
Vsync also doesn't work for me, and it has always worked before.

**Comment by vsub** [comment]
Same here...I thought something was wrong(because I see screen tearing when vsync is not enabled)and it looks like vsync was not working and the only way to not get screen tearing is to force it on from the nvidia control panel(adaptive also don't work)

**Comment by hrydgard** [comment]
ok, I will look into it.

**Comment by unknownbrackets** [comment]
Very good chance that will have helped it.

-[Unknown]

**Comment by vsub** [comment]
Yes,it works
Thanks

**Comment by DonelBueno** [comment]
Vsync now drops the frame rate when the speed is bellow 100%. This didin't happen in the old implementation. It's like the old implementation had Tripple-Buffering, but not the new one.

**Comment by hrydgard** [comment]
@DonelBueno  That's how VSync works. We use the same calls to enable VSync, nothing should have changed.
