### ISSUE TITLE
NFS MW hangs when police siren heard

### ISSUE THREAD

**Issue by jrancher** [hrydgard/ppsspp#7954]
Same issue as 4268, applies to arm64 (galaxy S6)

**Comment by unknownbrackets** [comment]
Untested fix:

https://github.com/hrydgard/ppsspp/compare/hrydgard:master...unknownbrackets:arm64-minor?expand=1

-[Unknown]

**Comment by sum2012** [comment]
How to compile arm64 build ?

**Comment by hrydgard** [comment]
All Android builds have been building for ARM64 since some time.

**Comment by unknownbrackets** [comment]
Should be fixed with #7956 merged (make sure to use a build from the buildbot after it shows that merge.)  If not, please comment and we'll reopen.

-[Unknown]

**Comment by jrancher** [comment]
Great! Would love to test, but buildbot is not displaying recent android builds (only windows).

**Comment by unknownbrackets** [comment]
It's there now.

-[Unknown]

**Comment by jrancher** [comment]
Confirmed fixed!
