### ISSUE TITLE
OpenGL Nvidia GPU Driver crashes while changing to fullscreen mode

### ISSUE THREAD

**Issue by GamerzHell9137** [hrydgard/ppsspp#7957]
For some reason when you sometimes change from Windowed to Fullscreen PPSSPP crashes
![14](https://cloud.githubusercontent.com/assets/2002038/9802195/d13f4a98-5818-11e5-8932-f85a4bfbeb8a.png)

**Comment by GamerzHell9137** [comment]
Doesn't happen on v1.0.1-860-gff3bb35
Happens on v1.0.1-880-g1fd6cf1
Not sure if it happens inbtw (am kinda busy to check out now)

**Comment by GamerzHell9137** [comment]
If you wanna as fast as possible to see what's going on Alt+Enter couple of times and the error will happen.
It started on v1.0.1-880-g1fd6cf1 and the last working version was v1.0.1-866-g86a02fe.
So something happened btw v1.0.1-867-ga71be3f and v1.0.1-880-g1fd6cf1 , dunno which one exactly caused it because there was no builds inbtw those.

**Comment by LunaMoo** [comment]
Amd doesn't seem affected, spammed alt+enter in both recent tab and running some games - no issue, same for recently added double click in-game.

**Comment by GamerzHell9137** [comment]
@LunaMoo Guess its Nvidia related then. Thanks for confirming.

**Comment by vsub** [comment]
I don't know if it's nvidia only related but the problem appeared here(GTX750TI)almost every time I try to enter full screen but ONLY while using OpenGL(with direct3d9 even holding F11(switching at least 3 times ever second),the problem didn't appear)
It's also fine when I use my build in HD4600

**Comment by GamerzHell9137** [comment]
Should be more specific, yes its OpenGL exclusive. Thanks for mentioning it vsub.

**Comment by thedax** [comment]
I can only reproduce this if I go extremely quickly while pressing alt-enter or f11 (or holding them down). Does this still happen for you guys if you slow the button presses down a little? I can't get it to crash simply by going fullscreen, back to windowed, going fullscreen, etc., over and over if I go slowly.

**Comment by vsub** [comment]
PPSSPP had this problem I since always.
Holding any of the hotkeys,it will rapidly execute the hotkey command.

F11 - constantly switching between full screen and window mode(as fast as your pc can do it)
F2,3,4,5,6,7 and so on - the same as above.
If you hold the key for more than a second,it will start rapidly executing the hotkey function.

I'm pressing F11 like I always do and it can also crash with double click(to enter\exit full screen)
With v1.0.1-866-g86a02fe I can even hold the F11 for a while(switching at least 1 times every second)and it will not crash but it will with v1.0.1-880-g1fd6cf1 usually after the third time entering full screen(and that's by normally pressing the key)

Currently I'm always afraid to enter\exit full screen,I have to always do a save state before entering\exiting full screen and I want to use the latest beta because it contains a fix for a bug that was bothering me for a while

**Comment by hrydgard** [comment]
That's just Windows' regular keyboard repeat functionality. We use normal Windows shortcut handling for these functions.

I have never been able to make fullscreen switching crash on my computer. I just held F11 down for half a minute and it flashed like crazy but kept going no problem...

**Comment by vsub** [comment]
I don't see anyone actually mentioning this but the problem happens only while playing some game,not in the menus\games list

**Comment by GamerzHell9137** [comment]
@hrydgard Just like vsub said, it happens in game and its still crashing when holding F11 on the newest nightly build.

**Comment by GamerzHell9137** [comment]
Here's how it looks on my end
https://youtu.be/rAPunpnPxNI

**Comment by hrydgard** [comment]
Scary. I can't get it to happen though, which would help debugging it :/   On Windows 10 64-bit here, nVidia 700-series.

**Comment by vsub** [comment]
And this is what I did just now
1.Start ppsspp and started a game
2.Switch to 1x internal resolution and go to full screen by using the menu(not hotkey)

And ppsspp crashed again

**Comment by thedax** [comment]
I updated my drivers to 355.82 and I can't get PPSSPP to crash anymore on Windows 7 x64, but it does hang the entire program if I sit there holding F11 while a game is running..

**Comment by GamerzHell9137** [comment]
I'm on 355.82 too. And can confirm that another person with GTX 960 with latest drivers crashes too.

**Comment by GamerzHell9137** [comment]
Another person tested on a GTX 750 Ti and says that it crashes on the latest nightly builds.
He's using the latest Nvidia drivers.

**Comment by GamerzHell9137** [comment]
Here's the log if that helps at all (GTX 960) https://mega.nz/#!F5A0GTaB!Pc1rSLI47YPN_fLmk3wrt0rPEDzmkN43iVXRdhXV7VA

**Comment by vnctdj** [comment]
Same as @hrydgard for me, I can't reproduce the issue by holding F11 down (on the menu as well as in a game).
GeForce GT 540M, driver v355.82, Windows 7 x64.

**Comment by vsub** [comment]
I using 353.30 and I just found something while trying the latest beta.
If "simulate block transfer" is disable,it's really hard to make it crash(I have to hold F11 for a while)but when it crashes,I get this error
![2015-09-18_185112](https://cloud.githubusercontent.com/assets/5032540/9964126/4a456372-5e37-11e5-9761-e762141a95fc.jpg)

I can't make it crash no matter what I do while using Direct3D9(it's switching between full screen and window mode even faster)when I use my GTX750TI and I also can't make it crash while using my HD4600 in both modes(OGL\D3D)

**Comment by hrydgard** [comment]
Very latest drivers.

**Comment by hrydgard** [comment]
Can any of you guys with problems try with #7984 ?

**Comment by vsub** [comment]
I'm not sure what to report.
1.In some weird combination of enabling certain options(Stretch to Display and Texture Scaling),opening menus,switching to fullscreen\window mode,ppsspp will start doing one of those or both
The message that appear at the top of the screen will become a mess of letters and images(the only fix is restarting ppsspp)
When going to the settings,the Back button at the bottom left is not visible

2.Before my pc freeze at back screen while trying the latest beta,I found that if "Stretch to Display" is enabled,ppsspp will crash every time I try to go fullscreen(with the hotkey,not the menu)and almost never if it's disabled(I have to hold F11 for a while)but after I restart it,it didn't crash for a while and then it started crashing again even with that option disabled.

Disabling each of those decreases more and more the possibility of crashing

Stretch to Display - especially this one
VSync
Texture Scaling

**Comment by hrydgard** [comment]
So, in https://github.com/hrydgard/ppsspp/commit/1410d7f6d5116d9f4500efc3e6a94934c3246ebe , I tried a little thing where we pause rendering completely while the size change is happening. I have some hope that it will reduce this problem but as always I have no idea if it helped, because it doesn't crash for me. So please test!

**Comment by vsub** [comment]
It does look like a solution and it's not crashing now(I can't be 100% sure(sometimes it was crashing randomly)but I think this is the fix)

**Comment by hrydgard** [comment]
Thanks @vsub, sounds promising.

**Comment by vsub** [comment]
Well here is one new problem.
In the screen menu the "Full Screen" button\checkbox in Graphics makes ppsspp to freeze even if no game is running.
PPSSPP was crashing when switching between modes only ingame and never in menus.

**Comment by hrydgard** [comment]
Oh! I know why that is. Will fix immediately.

**Comment by hrydgard** [comment]
That should do it. Thanks for the catch.

**Comment by vsub** [comment]
Here we go again :( but this time I don't know if it's related to some of the recent changes

1.Start ppsspp and enable any post processing shader(I usually use Natural Colors)
2.Start any game(you can also use the cube.iso),maximize the window and press F11 twice(you will notest that around 70px of the bottom are not visible when you exit full screen(I made a thread about this https://github.com/hrydgard/ppsspp/issues/7986 but is seems it's not just menus))
3.Minimize the window and when you restore it,ppsspp will always crash.

If I use the option "Pause when not focused",ppsspp will not crash and it will not crash if the window is not maximized

And yet again,nvidia ogl only problem

**Comment by unknownbrackets** [comment]
I am not able to reproduce this on my NVIDIA 9800 GT with the steps above with #7988.  Didn't try without it, but maybe it has the same cause.  Otherwise, I can't repro.

-[Unknown]

**Comment by vsub** [comment]
Seems that way,ppsspp is not crashing with that change

**Comment by hrydgard** [comment]
Alright, great. Let's await @GamerzHell9137 's testing, then close.

**Comment by hrydgard** [comment]
Ping @GamerzHell9137

**Comment by GamerzHell9137** [comment]
Sorry for being absent but i was changing towns for college so it took a while to move stuff. Didn't have internet connection so i couldn't test the new builds or anything and the new isp came the day when i was supposed to go back home. So yeah, im at home right now and my pc is at college place so i can't test it right now. Gonna report on sunday or monday, whenever i get on the PC. (College life is sure busy)

**Comment by GamerzHell9137** [comment]
@hrydgard Just checked v1.0.1-2783-g3c499fd and no crashes here. Good that this has been solved.
