### ISSUE TITLE
Tales of Phantasia with Chinese patch black screen.

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#7960]
log information

```
49:24:864 user_main    W[MM]: MemmapFunctions.cpp:130 WriteToHardware: Invalid address 0005fd36
49:24:864 user_main    W[MM]: MemmapFunctions.cpp:93 ReadFromHardware: Invalid address 0005fd38
49:24:864 user_main    W[MM]: MemmapFunctions.cpp:130 WriteToHardware: Invalid address 0005fd38
49:24:864 user_main    E[KERNEL]: HLE\sceKernelThread.cpp:668 ThreadQueueList should not be empty.
49:24:864 user_main    E[*]: MsgHandler.cpp:54 Warning: ThreadQueueList should not be empty.
```

JPCSP fixed it in https://github.com/jpcsp/jpcsp/commit/d458e1f3adc425474a2480628afb8f392e341a4c
![01](https://cloud.githubusercontent.com/assets/3481559/9829363/43196e02-5934-11e5-88e2-ab832583992a.png)

**Comment by hrydgard** [comment]
We must have some different issue than the one JPCSP fixed, I checked that we already parse right in https://github.com/hrydgard/ppsspp/commit/1e109a3b278ec09a8ac7a85b0720cd5472d1433c .

**Comment by unknownbrackets** [comment]
ThreadQueueList should never become empty.  That's basically brain death for the HLE.

Does this do anything?
https://github.com/hrydgard/ppsspp/compare/hrydgard:master...unknownbrackets:hle-minor

Most importantly, if you hit Yes, what does it log?

-[Unknown]

**Comment by daniel229** [comment]
Still got tha error,
```
39:48:211 user_main    W[MM]: MemmapFunctions.cpp:93 ReadFromHardware: Invalid address 0005fd38
39:48:211 user_main    W[MM]: MemmapFunctions.cpp:130 WriteToHardware: Invalid address 0005fd38
39:48:211 user_main    E[KERNEL]: ppsspp\Core/HLE/ThreadQueueList.h:85 ThreadQueueList should not be empty.
39:48:211 user_main    E[*]: MsgHandler.cpp:54 Warning: ThreadQueueList should not be empty.
```

After clicking "Yes" button,then a lot of Invalid addresses going on ,then pressing the circle button and wait a few seconds,it skips the language selection screen and go ingame.
```
41:55:013 user_main    W[MM]: MemmapFunctions.cpp:93 ReadFromHardware: Invalid address 0005fd36
41:55:013 user_main    W[MM]: MemmapFunctions.cpp:130 WriteToHardware: Invalid address 0005fd36
41:55:013 user_main    W[MM]: MemmapFunctions.cpp:93 ReadFromHardware: Invalid address 0005fd38
41:55:013 user_main    W[MM]: MemmapFunctions.cpp:130 WriteToHardware: Invalid address 0005fd38
41:55:013 user_main    E[HLE]: HLE\HLE.cpp:550 Unimplemented HLE function SysMemForKernel_c9805775
41:55:016 user_main    E[KERNEL]: HLE\sceKernelThread.cpp:2671 sceKernelResumeThread(273): thread not suspended
41:55:016 user_main    E[KERNEL]: HLE\sceKernelThread.cpp:2661 sceKernelResumeThread(276): cannot suspend current thread
```

**Comment by unknownbrackets** [comment]
Hmm, I was hoping for a `Failed to reschedule: out of threads on queue` log line...

Sounds like it's using kernel memory management functions and that's why it's got the invalid addresses.

-[Unknown]

**Comment by sum2012** [comment]
I told gid15 that try to fix this game in jpcsp.He did it.
Anyway we need Implement SysMemForKernel_1c1fbfe7 and SysMemForKernel_636c953b
Jpcsp source reference:
https://github.com/jpcsp/jpcsp/commit/3c25717e04c66a1f5a93e0cacc2c232ecf2d2453
full log: https://gist.github.com/sum2012/3b36c375c9e211d5f924

**Comment by sum2012** [comment]
We also need fix ModuleMgrForKernel_a1a78c58 (sceKernelLoadModuleDisc).
Jpcsp source reference:
https://github.com/jpcsp/jpcsp/commit/fccb74771e48b873cffe8c2c7e047a2c2f4c4f7c

**Comment by sum2012** [comment]
@daniel229 can you help to do "replace frame download" of https://cloud.githubusercontent.com/assets/2177532/9947780/761c3376-5dcf-11e5-9899-82e9f79a83f1.jpg
? Thanks.

You need merge #7965 first (Use soft gpu to see that picture)

**Comment by daniel229** [comment]
Great,that pr works pretty fine.
@unknownbrackets 
The hashes don't save to knownfuncs.ini since switch to VS 2015,the last working build is v1.0.1-891-g1c67de0

I catch these function and it's not like framebuffer download things.
![01](https://cloud.githubusercontent.com/assets/3481559/9974664/82551492-5ecd-11e5-93f5-a0f47f928e6c.png)
![02](https://cloud.githubusercontent.com/assets/3481559/9974665/825a739c-5ecd-11e5-8749-5e66e5bf2425.png)

**Comment by daniel229** [comment]
That screen works fine in D3D9.
![01](https://cloud.githubusercontent.com/assets/3481559/9974705/7be1c300-5ed0-11e5-95c4-f656169ed433.png)

**Comment by daniel229** [comment]
It just accidently works fine in D3D9,sometime blackscreen as in OpenGL.
It get this error in D3D9,not in OpenGL.
```
Directx9\FramebufferDX9.cpp:779 fbo_blit_color failed on display: 8876086c
```

**Comment by unknownbrackets** [comment]
On what OS is it not updating knownfuncs?  It seems to work for me.

-[Unknown]

**Comment by daniel229** [comment]
It's WIn7 x86-64 zh_CN

**Comment by sum2012** [comment]
Not sure why GE debugger not work (Step Frame) in https://cloud.githubusercontent.com/assets/3481559/9974705/7be1c300-5ed0-11e5-95c4-f656169ed433.png

**Comment by sum2012** [comment]
This is dircetx mode debug log
Hope @unknownbrackets can find something
good log:
https://gist.github.com/sum2012/fa1746010657b23f7364
bad log:(black screen)
https://gist.github.com/sum2012/3f835128d23200d491c1

**Comment by sum2012** [comment]
In the latest master (test in v1.1.1-383-gf434be3)
Apply my pr ,use opengl or d3d9 can see the screen now.
No more need soft gpu

**Comment by sum2012** [comment]
v1.9.3-731-gf82e7a4e7-windows-amd64 
in-game now bu no chinese menu 's picture
https://cloud.githubusercontent.com/assets/3481559/9974705/7be1c300-5ed0-11e5-95c4-f656169ed433.png

info log:
https://gist.github.com/sum2012/30ce482512773e4296216147e5ff3330

debug log :(attach)
[ppsspplog-2-v1.9.3-731-gf82e7a4e7.txt.zip](https://github.com/hrydgard/ppsspp/files/4556412/ppsspplog-2-v1.9.3-731-gf82e7a4e7.txt.zip)

**Comment by unknownbrackets** [comment]
Hm, what does a GE dump look like?  Is it drawing that menu using drawing commands?

Does software rendering work?

-[Unknown]

**Comment by sum2012** [comment]
We don't see that screen now.
(sorry, I uploaded wrong info log)
https://gist.github.com/sum2012/ac275856bd77cebb7b17d41139fd6e39

I see our code now passed the chinese 's patch 's module (sceKernelAllocHeapMemory).

Success old info log:  https://gist.github.com/sum2012/04b57eb492018d02ca29

**Comment by sum2012** [comment]
Sorry again,I load wrong rom (Two roms 's name are similar )

v1.9.3-731-gf82e7a4e7-windows-amd64 log:
https://gist.github.com/sum2012/fec1ab53c803081f4cb92b0748ec428f

08:50:509 user_main    E[SCEKERNEL]: util\blockallocator.cpp:140 Block Allocator (08800000-0a000000) failed to allocate 1300224 (0013d700) bytes of contiguous memory

**Comment by sum2012** [comment]
I have some update information from jpcsp:
Memory:
https://github.com/jpcsp/jpcsp/commit/eda291807b2d7168d6daf2303e09e0fc8af2e630
sceHeapCreateHeap: use the correct partition:
https://github.com/jpcsp/jpcsp/commit/27eb47f9db96a539e0f285296055057d0f444799

**Comment by unknownbrackets** [comment]
Hm, we should be using the right partition already, but allocations might still be off.

In that case, 0x00128000 is all that's free, and not even in a row.  The stack space for the game and for Cn_Plugin are huge.

The ELF (ELF/Cn_Plugin) goes in kernel, and things would be great if the stack was too.  Hm.  The thread create is:

```c++
276=sceKernelCreateThread(user_main, 08220c00, 00000020, 262144, 00000000, 00000000)
```

Attr is 00000000, which I thought meant a user thread.  But it doesn't explicitly say user thread...

What happens if you do this?
https://github.com/hrydgard/ppsspp/compare/master...unknownbrackets:kernel-thread?expand=1

-[Unknown]

**Comment by sum2012** [comment]
Seem no change
https://gist.github.com/sum2012/b57eae0ae3eec40fac27da72e88ee49a

**Comment by sum2012** [comment]
JPCSPTrace log:
Seem cannot log sceKernelCreateHeap 
https://gist.github.com/sum2012/83628449d87566e352d987dc796df31b

**Comment by unknownbrackets** [comment]
My change isn't triggering, hm.  This from that trace more or less confirms that it should be using kernel memory for the stack:

```
TotalFreeMem=0x17F7700, MaxFreeMem=0x17F6100
TotalFreeMem=0x17F7700, MaxFreeMem=0x17F6100
17:21:57.832 SceModmgrStart - sceKernelCreateThread 0x88208534('user_main'), 0x88204E00, 32, 0x40000, 0x0, 0x0 = 0x3F6A47D
TotalFreeMem=0x17F7700, MaxFreeMem=0x17F6100
```

And lower down, we get the correct allocation we want in PPSSPP:
```
TotalFreeMem=0x264300, MaxFreeMem=0x263100
TotalFreeMem=0x164300, MaxFreeMem=0x163100
17:21:58.425 SceModmgrStart - sceKernelCreateThread 0x08946C30('user_main'), 0x88040BC, 32, 0x100000, 0x80000000, 0x0 = 0x3F61F05
Starting module 'sceChnnlsv' at 0x881FD900
```

I updated the branch with more logging.  Since it's calling the usermode sceKernelCreateThread, and it has a user mode stack itself, I'm not sure how I would determine it should create a kernel thread...

-[Unknown]

**Comment by hrydgard** [comment]
Maybe some kind of flag on the code segment that contains the thread function in the binary? Just an idea..  Or is the top bit set of the code address maybe? That should normally not be set when creating a user thread...

**Comment by sum2012** [comment]
Only hit once
37:17:028 HLE\sceKernelModule.cpp:1596 W[SCEKERNEL]: Root thread attr: 80000000
full log:
https://gist.github.com/sum2012/b14277e1c55a605479198bfc8792047e

**Comment by unknownbrackets** [comment]
Hm, maybe it defaults based on the module.  Updated that branch again.

-[Unknown]

**Comment by sum2012** [comment]
The kernal memory seem work
But sceKernelAllocHeapMemory have problem
log:
https://gist.github.com/sum2012/c80413eae26dec9c2a62d78ea74e4812
Crash trace:
![1](https://user-images.githubusercontent.com/2177532/82810610-76f70b80-9ec1-11ea-920f-4a1cb959dc50.png)
![2](https://user-images.githubusercontent.com/2177532/82810620-7b232900-9ec1-11ea-8159-20cd13e83436.png)

**Comment by unknownbrackets** [comment]
What does it actually crash on?

-[Unknown]

**Comment by sum2012** [comment]
How to know that it actually crash on ?
Do crash trace not clear ?

**Comment by hrydgard** [comment]
No, in the last screenshot it looks like you're just stepping (F8). It's ok that heap is 0xcccccccc because it will be initialized that very line.

Something looks bad in the first screenshot though .... "t:  fromtop: true (30)". that's an invalid bool.

**Comment by sum2012** [comment]
I didn't  stepping (F8) .I used mouse to click the second trace

**Comment by unknownbrackets** [comment]
Heap doesn't currently have a fromtop member?  Maybe it's just not initialized?

-[Unknown]

**Comment by sum2012** [comment]
temp disable the check
https://github.com/sum2012/ppsspp/commit/6b9d21bb6a734ff20fcc7670f581705bca8d5c50
cause another crash
![3](https://user-images.githubusercontent.com/2177532/83329043-afc82380-a2b9-11ea-8baa-69a5b57890e9.png)
![2](https://user-images.githubusercontent.com/2177532/83329048-b48cd780-a2b9-11ea-94a3-f4d05971e562.png)
![1](https://user-images.githubusercontent.com/2177532/83329051-b8b8f500-a2b9-11ea-9599-811ee8534531.png)

**Comment by sum2012** [comment]
v1.10.3-184-gd9756e923 
VS2015 still don't work,same crash trace.
But buildbot is work , log: https://gist.github.com/sum2012/cdc82853cdf625ca82fda9ec6257f6e4
I might try to update to vs2018\2019  to test again

**Comment by sum2012** [comment]
@hrydgard @unknownbrackets VS2019 get another crash
please help
![1](https://user-images.githubusercontent.com/2177532/89730130-9cca9000-da6e-11ea-9649-4cba121e3ac0.png)

**Comment by sum2012** [comment]
https://github.com/hrydgard/ppsspp/commit/d7fa5928d4f7ff7d8b62d4619c987aa1808f5007 fix this
Thanks @unknownbrackets 
Closing

**Comment by hrydgard** [comment]
Cool! so the game works well now?

**Comment by sum2012** [comment]
Remain #6933
