### ISSUE TITLE
[Feature Request] Enabled some code on proAdhoc.cpp

### ISSUE THREAD

**Issue by lightfirst** [hrydgard/ppsspp#7962]
I don't know why disable it, but if it does n't breach something, I suggest enable it
what's more enable those code fixed "back loddy but can't plays” 

just remove /*  and  */
----------------
			// Multithreading Lock
			/*peerlock.lock();
			// Unlink Left (Beginning)
			if(prev == NULL)friends = peer->next;
			// Unlink Left (Other)
			else prev->next = peer->next;
			// Multithreading Unlock
			peerlock.unlock();
			// Free Memory
			free(peer);
			peer = NULL;*/

--------------

					// Should only add non-existing group (or replace an existing group) to prevent Ford Street Racing from showing a strange game session list
					/*SceNetAdhocctlScanInfo * group = findGroup(&packet->mac);

					if (group != NULL) {
					// Copy Group Name
					group->group_name = packet->group;

					// Set Group Host
					group->bssid.mac_addr = packet->mac;
					}
					else*/

-----------------

**Comment by hrydgard** [comment]
sum2012 made a pull request so let's move the discussion there, to #7963.
