### ISSUE TITLE
XP: game specific configs ignored in recent build ?

### ISSUE THREAD

**Issue by Trokinos** [hrydgard/ppsspp#7967]
Was using PPSSPP  1.0.1-830-gc671b07 on win32 (it was from 2015-08-27 15:13:05 ) and had no such problem.

Today i decided to give a try to the latest build and downloaded PPSSPP 1.0.1-2654-g315ff81 ( from the 2015-09-13 21:31:12 ) and after moving the memstick folder and the games into that new  PPSSPP directory, on the game list screen after launch i quickly noticed that the games i had a specific configs were missing their usual icon that tells they have a specific game config.

And holding a click to them confirmed that despite those specific configs are in the usual place , this version of PPSSPP was not considering there was a custom config as it asked if i wanted to create one.

I have used a lot of builds and that's the 1st time it's happening.

**Comment by Trokinos** [comment]
checked a few builds and it appears the 1st one i have this problem on my system is 
1.0.1-2631-g2eb45f5

with 1.0.1-2630-g487f184 being the last version that had the specific game config icon appearing on their related game picture.

**Comment by Trokinos** [comment]
After testing more, the problem is actually bigger than i thought , none of the games i launch are finding their save data (despite they're all there (i mean in ...\ppsspp\memstick\PSP\SAVEDATA\ )

1.0.1-2630-g487f184 seems to be the last version that work correctly on my win32 os (winxp)

**Comment by unknownbrackets** [comment]
Just to clarify, v1.0.1-2631-g2eb45f5 (2eb45f5016f777d786a0634169cf9a7f443d018b) doesn't work?

Are you trying with PPSSPP in the exact same folder?  You're sure you have free disk space?

-[Unknown]

**Comment by Trokinos** [comment]
I'm sorry, only the detection of the "game specific" .ini file is last correctly detected by
1.0.1-2630-g487f184
starting with 
v1.0.1-2631-g2eb45f5
the game specific ini files aren't detected anymore (and the save data are all undetected)

files are all in the correct memstick directory that i transfer from builds to builds, doing this has always worked for all the builds i have downloaded so far since i'm using ppsspp.
Hardrive space isn't a problem on my system, plenty gb free.

I'm downloading some past builds to see which one started to not find the save data , so far v1.0.1-857-g08b340f is correct, all the files are detected.
Will update this report when i find

**Comment by Trokinos** [comment]
Ok here is what i found after testing several builds

Up to v1.0.1-891-g1c67de0 on win32 PPSSPP does find the save data, game specific ini are found
In v1.0.1-899-g1b4b60d, on win32 PPSSPP does NOT find the save data, game specific ini are found

unfortunately between those 2 builds there's no win32 ones (x86), so i can't pinpoint which one started exactly.
Then starting with v1.0.1-2631-g2eb45f5 , on win32 PPSSPP does not find game specific ini

**Comment by unknownbrackets** [comment]
Okay, well, that range is the update to MSVC 2015.  Maybe there's a compatibility issue with Windows XP.

I think 2eb45f5 is a totally separate issue.  Not discounting it, just saying it doesn't seem related to the MSVC 2015 problem and probably is not Windows XP specific.

-[Unknown]

**Comment by sum2012** [comment]
I use vmware to confirm.
Yes cannot see "save" or "save status"
There is a file called _writable_test.$$$ in memstick folder after start ppsspp.

**Comment by hrydgard** [comment]
Seems like File::Exists must return the wrong result, otherwise the file would have been deleted. Might be some strange unicode issue? Hm..

**Comment by sum2012** [comment]
Let me try to rename the file in the code

**Comment by hrydgard** [comment]
@sum2012 can you try with #7994 ? Would be interesting if it worked.

**Comment by sum2012** [comment]
@hrydgard ok,try your method first.
If fail,I try to rename _writable_test.$$$ to _writable_test.aaa

**Comment by hrydgard** [comment]
ok, worth trying that too.

**Comment by sum2012** [comment]
@hrydgard Unfortunately,both method fail

**Comment by hrydgard** [comment]
Thanks for testing @sum2012 , this is very strange..

**Comment by hrydgard** [comment]
I have set up my own XP VM now, I will investigate in detail tomorrow. It seems IsDirectory is the problem.

**Comment by hrydgard** [comment]
https://connect.microsoft.com/VisualStudio/feedback/details/1557168/wstat64-returns-1-on-xp-always

That would explain it.

Will work around it tomorrow, by simply avoiding the function and calling native Windows functions instead.

**Comment by sum2012** [comment]
@hrydgard maybe there is additional bug in native
log:
https://gist.github.com/sum2012/972b298375d1d0cbb4c0
 
733 37:16:750 user_main    W[COMMON]: FileUtil.cpp:464 GetSize: failed C:\test\ppsspp-v1.0.1-2624-g936ccbf-windows-x86\ppsspp\memstick/PSP\SAVEDATA\ULJM05556\ICON0.PNG: No such file 

734 37:16:750 user_main    W[SCEGE]: Util\PPGeDraw.cpp:848 Bad PPGeImage - not a valid png 
735 37:16:765 user_main    W[COMMON]: FileUtil.cpp:179 IsDirectory: stat failed on C:\test\ppsspp-v1.0.1-2624-g936ccbf-windows-x86\ppsspp\memstick/PSP\SAVEDATA\ULJM05556\ICON0.PNG: 系統不支援這個功能。 (in english:system don't support this function)

**Comment by sum2012** [comment]
@hrydgard oh,I don't see your last comment,anyway good luck

**Comment by hrydgard** [comment]
https://github.com/hrydgard/ppsspp/pull/7994 should now fix all these issues.

**Comment by hrydgard** [comment]
It passed all checks so I merged it.

@Trokinos , can you re-test with the latest build when it's done?

**Comment by Trokinos** [comment]
Hello, 

I gave a test to v1.0.1-2768-gd8b43dd and noticed that with this version PPSSPP correctly detect both game specific configs and the saved game again, so it seems the problem is fixed

Thank you very much.

**Comment by sum2012** [comment]
@Trokinos 
Now you can close this issue

**Comment by Trokinos** [comment]
Didn't noticed i could do that, sorry, i thought it was only developers that closed issues.

**Comment by hrydgard** [comment]
@Trokinos great, thank you for reporting the issue and testing the fix.
