### ISSUE TITLE
crash in SVR2011 in the end of the Play -> 30 man Royal Rumble 

### ISSUE THREAD

**Issue by Trokinos** [hrydgard/ppsspp#7972]
When i use the Play menu to watch (not play) a 30 man (AI in fact) Royal Rumble, every time the last wrestler finally get rid of everyone else and is happy to be victorious alone on the ring, PPSSPP crash

As it takes a long time to watch an AI-only Royal Rumble, i made a save state before the last opponent fall from the ring, and indeed it crash again once the last standing guy is alone.

I am using the european version of SVR 2011
Here is the save state :
https://www.dropbox.com/s/yjpgbdsot5d0e1y/savestatesvr2011bug.7z?dl=0

And here is the game save for that saved state (required to use that save state as the last 2 wrestlers are CAWS on the ring) :
https://www.dropbox.com/s/mfu3vlm5md89kdv/saveforbugsvr2011.7z?dl=0

I'm currently using v1.0.1-899-g1b4b60d , win 32 (winxp) , but this kind of end game crash in a AI-only 30 men royal rumble has happened as long as i can remember (i don't watch AI-only 30 men royal rumble in svr2011 really often but the few time i did, it always crashed at the same point).

Here is a picture of the console log when the crash happens in case there's something obvious that does not require having to use the save state and the save to test :
http://i.imgur.com/0KcOpMt.gif

When i play a 30 men royal rumble (not watch the AI), usually i do not crash, after the victory there's a cutscene that play (the crash happens just before it in the AI-only case) with the winning character taking a pose and pointing the finger toward the title board.

**Comment by sum2012** [comment]
@Trokinos Rename the save state 's filename is wrong.
We cannot load it without rename it back correct's filename

**Comment by Trokinos** [comment]
It's strange, on my ppsspp after loading the game and waiting for the game save to be loaded, i can just do File -> Load State File and select it without a problem whatever the name i give to that save state file ?
I wonder why it's not working for you.

Anyways, the real state file name is
ULES01472_1.01_0.ppst
But strange that you can't load it with a custom name

**Comment by sum2012** [comment]
I always load\save from here
![1](https://cloud.githubusercontent.com/assets/2177532/9935013/f6dae406-5d86-11e5-99d8-092966ff55a0.jpg)

**Comment by sum2012** [comment]
The full info log:
https://gist.github.com/sum2012/9f1aa33b4ce0046cbe95
full debug log:
https://drive.google.com/file/d/0B3OaSdeV0L8kN0tuQXgybm5ROWc/view?usp=sharing
last hle log:
![1](https://cloud.githubusercontent.com/assets/2177532/9935209/edb02a48-5d87-11e5-8da1-ab1627228554.png)

Disassembly
![2](https://cloud.githubusercontent.com/assets/2177532/9935297/5f7680f0-5d88-11e5-9fe8-0d88b36851f4.png)

**Comment by unknownbrackets** [comment]
So, before `a0` was added, `v0` was `0x21B42FE0`, which was shifted right from `0x021B42FE`.  But v1 I can't see anymore, and I'm not seeing where it's populated.  It had to take that path, because that's the only path to the failing `sw`.

Maybe something is happening in sceCtrl to write memory it's not expecting?  Or maybe it's corrupted earlier.

With fast memory disabled, obviously it's still a bug, but does it no longer crash?

-[Unknown]

**Comment by sum2012** [comment]
No longer crash but blackscreen.
Just a feel,sceAtrac sometinhg wrong

ppsspp-v1.1.1-440-g7eb662f-windows-amd64 log:
https://gist.github.com/sum2012/12f7dc6bcfdc96c13a7a

**Comment by unknownbrackets** [comment]
Hmm, hard to tell.  Could be.  Can you try bisecting the black screen a bit?  Looks like it "worked" (at least no black screen) in v1.0.1-2678-ga3eb319.

-[Unknown]

**Comment by sum2012** [comment]
I cannot test before because ppsspp cannot load save status.
I don't mean @Trokinos  said that can watch video to reproduce this

**Comment by Trokinos** [comment]
A little update.
I checked a bit more about this and it appears this is not related to PPSSPP at all, but is  -yet another bug- of the game itself.

SVR2011 has a lot of problems, and apparently a CAWS-filled royal rumble crash is one of them, may or may not be related to other another known crashing bug related to CAWS with created finishers in the Road to Wrestlemania mode when doing the Undertaker one with your CAWS.

So it may be safe to close, as it's the game that's unfortunately just bugged.

**Comment by hrydgard** [comment]
So is it back to working again, with no blackscreen? Otherwise we should keep this issue open for that.

**Comment by unknownbrackets** [comment]
It sounds like PPSSPP is emulating this properly, and this was just a game bug - is that right?  Or is there still a problem getting PPSSPP to run the game?

-[Unknown]

**Comment by unknownbrackets** [comment]
Given there hasn't been any update in a while (5+ years), I'm going to assume this was a game bug indeed and close.

If you have more information or can confirm it still happens in the latest git builds and doesn't happen on a real PSP, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
