### ISSUE TITLE
Regression: Breath of Fire III now jumps up and down rapidly since a3078a6ae

### ISSUE THREAD

**Issue by thedax** [hrydgard/ppsspp#7974]
Ever since #7964 was merged, Breath of Fire 3 now jumbles up and down rapidly much like it used to a long time ago. More specifically,  a3078a6ae12255d0aa49691fbac9c4cbdb591d54 is the offending commit. If I revert to the one just before it, the game does not exhibit the issue.

**Comment by unknownbrackets** [comment]
So, not sure what's happening here, but tracing the logic, let me describe what happens and why it should work the way it is.  I don't know what's not working - maybe logging can help?

First - to remember what the game does:

```
AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA
BBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBB
```

Above, A is framebuffer/render target A, and B is framebuffer/render target B.  It uses A as a texture ALWAYS, and sends either UV coordinates pointing at A, or UV coordinates pointing at B.

Now, what should be happening:

Step 1. DoFlush is triggered for copying the render from A or B to the screen.
Step 2. ApplyDrawState(prim) always picks A, never B.
Step 3. Vertex shader, vertex decode, etc.
Step 4. SoftwareTransform - now we detect and set the **pending** texture to B.
Step 5. ApplyDrawStateLate binds the pending texture.
Step 6. ApplyFragmentShader shouldn't matter when this happens exactly...
Step 7. We actually draw.

So, I'm not sure what moving ApplyFragmentShader ought to matter.  The other one definitely needs to be down below, though.

I did find something, though... sometimes we refuse to resize down a framebuffer that was detected too tall but has been smaller consistently for a while.

-[Unknown]
