### ISSUE TITLE
Shield Controller not working in menu

### ISSUE THREAD

**Issue by fivefeet8** [hrydgard/ppsspp#7976]
With the latest dev. updates my Shield Controller no longer functions except for the back button in the emulator menus.  I can not move with the d-pad or analogs to select items.  This is running on my Shield Android TV.  The controller will work ingame though once a game has been loaded, but I have to use my mouse to select and load the game.  

I've already done a default reset and configured the controller which funny enough still picks up the inputs.

**Comment by hrydgard** [comment]
Thanks, just got another report of this by email, too. Fix coming soon.

**Comment by hrydgard** [comment]
That takes care of the main issue, however there's still some issues, key repeat doesn't work in the game selector for some reason. Will look into it.

**Comment by hrydgard** [comment]
Okay, key repeats don't work because the dpad events immediately send a keyup. We additionally get axis "hat" events, which are probably the ones we really should use for navigation. Will have to do some trickery to use them as navigation keys, although we have most of the mechanism already.

**Comment by hrydgard** [comment]
I'm closing this as the main issue is solved.
