### ISSUE TITLE
Patapon 3 Adhoc freeze on android

### ISSUE THREAD

**Issue by Michal1324** [hrydgard/ppsspp#7979]
Phone: Samsung S3
PPSSPP version v1.0.1

So I have tried multiple Ip's and every one does freeze the game for example

192.168.43.1
192.168.1.14 (actual phone ip)
localhost
127.0.0.1

**Comment by lightfirst** [comment]
It's known issue: Socket error when binding port  #7274

**Comment by Bigpet** [comment]
@lightfirst I think you linked to the wrong issue, that one doesn't seem related

**Comment by lightfirst** [comment]
@Bigpet  I don't know how to get log on android, but I try using osm.show to show it.
![screenshot_2015-09-24-18-45-50](https://cloud.githubusercontent.com/assets/4612168/10071565/5692085a-62ed-11e5-9fa7-87db982ae4f1.JPG)

**Comment by GamerzHell9137** [comment]
There was never progression in the multiplayer section of ppsspp so i guess this won't be fixed for a long while. Speaking of which, there was never a serious talk about it by the ppsspp developers.

**Comment by asl97** [comment]
This is just a case of privileged port and Patapon 3 uses port 555 which is an privileged port.

You just need to use an port offset.
