### ISSUE TITLE
Feature Request: Alternative speed improvements

### ISSUE THREAD

**Issue by lasers** [hrydgard/ppsspp#7981]
I'm playing a game right now and I find myself pausing, changing settings every time I wanted things to slow down to make it more easier to finish certain parts of the game. I would like to have a second alternative speed. We have standard speed. I used 150% on alternative speed. I would like to use 50% on the next alternative speed.

Perhaps we could have a way to add as many alternative speed as we want to... in case we wanted to try playing this game at 200% or a certain speed without pausing, going through the setting, etc...

What about having an option to do one thing? It could be...
1) Input a new alternative speed on-the-fly without going through the setting?
2) Increment/decrement the alternative speed on-the-fly without going through the setting?
3) Cycle the alternative speeds listed in the settings? 

Thank you for PPSSPP! It's the first time I actually played a PSP game although I have a real PSP myself for long long time. I like Xbox360 controller and a bigger screen way more than a PSP. ;-)

**Comment by lasers** [comment]
I'm favoring 3) because I think it would be useful to map "speed toggle" to Tab key/Guide button and it would only cycle the sensible speeds users wanted to use. They can add the new speed to the list in the setting.

**Comment by hrydgard** [comment]
Yeah, can simply add another mappable shortcut key that, as you say, cycles the alternative speed through the various settings. It'll be easy, I'll get to it soon.

Should the emulator drop out of the alternative speed and return to normal speed if it's already toggled to alternative speed, when you press this new button? Might be a good thing so you don't accidentally accelerate too much..

**Comment by lasers** [comment]
Sounds like you're going with 2)... which could be slightly difficulty to map two buttons on the controller without using some combos... or you're talking about 3) along with the standard speed? Yes, I think that would be a good idea.

The 3) idea is that I can add/subtract my sensible alternative speeds in the settings (similar to Controls). I would then use 50%, 100%, 125%, 150%, 200% ── then I would use Guide button to keep toggling to get the speed I wanted to use for this particular challenge in the game. I'm not sure how not to avoid going normal speed twice (with an input of 100% in the list).

Right now, I'm manually changing settings between standard speed, 50% and 150%.

50% -- 100% scenario without trying repeatedly-- for timed mini games or things where the devs wanted to rush you... Not wanting to go through this part repeatedly to get gold medals (ie about 200 times without failing). Think Dance Dance Revolution.

100% -- Standard gaming -- I would like to try it at 125% sometimes without manually changing settings just to speed things up a bit. Could PPSSPP check for 100% and marks it as a standard speed?

150% / 200% -- Speeding it up. Useful when you're failing repeatedly to obtain something like a floating orb that's too far right off the bridge and if you missed it, you have to go the long way with the scooter to get back to the said bridge or cliff for yet another attempt.. then you cycles the list to get your standard speed. Perfect for something that requires repeated attempts.

3) Toggling Tab key / Guide button could achieve something like... Speed: 50%, Speed: 100%, Speed: 125%, Speed 150%, Speed 200%... instead of Speed: standard, Speed: alternative.

2) Toggling Tab key / Guide button could achieve something like... Speed: standard, Speed: alternative (with new mappable button that does 50%, 100%, 125%, 150%, 200%) might be weird/not intuitive for a controller.

I look forward to test it out! :)

**Comment by vsub** [comment]
There is something related that I want to request.
Make the Unthrottle(I don't use the alternative speed,I just hold a button(L2)when I want to increase the speed)obey the alternative speed.

If it's set to 0,untrhottle will make the game run as fast as possible(which is a problem for me now since on my new pc,I get really high speed on any game which makes it unplayably fast),and when it's set to something other than 0,then to limit untrhottle to that speed(which will make that function useful to me again)

If someone don't like this change,make adding an ini option ObeyAlternativeSpeed will fix that.

**Comment by lasers** [comment]
I tried Unthrottle just now and I like this feature. I'm going to use that too now. Many thanks. We could use "Prevent Unthrottle from exceeding __%" option... I reached 1600%.

I also was wondering about the ability to map a Guide button as a modifier to increase/decrease alternative speeds (L2/R2) and to cycle user-defined speeds (L1/R1).... but mostly I wanted the latter. This would make it easier to map any other PPSSPP features without messing with the in-game controls.

**Comment by hrydgard** [comment]
Hm, yeah, maybe that would be enough. Don't want to make things too complex. As most of the time when you (in the general sense) want to speed up you want to do it temporarily, the unthrottle mechanism is the most convenient, and if we simply add an option to cap that, that takes care of it.

By the way do you have a better idea for a name for the unthrottle feature? Most people don't seem to understand what it means... "No speed limit"? hm.

**Comment by LunaMoo** [comment]
I have a feeling that if people confuse "unthrottle" they will think "no speed limit" will increase their speed on slow devices:P.

 Could key mapping popups get more info to add an optional brief explanation specific to the feature being mapped? It could be used only for more confusing settings and system like that maybe later could also be reused for other settings and replace a need for detailed help/guide which as of now all attempts failed.

**Comment by lasers** [comment]
Speed boost? Prevent speed boost from exceeding ___%?

It's easy and people could see its likely purpose.  It also could go hand in hand with the existing feature: Speed toggle. Speed boost is indeed not something to be toyed with.

I find speed boost mechanism convenient too. I think it's just too fast not to have some user-defined limitation (in %, 0 = unlimited). I could set it at 300%, 400% or 500% at most. I finished Daxter today and there was plenty of senseless deaths/mistakes/accidents from using speed boost for no more than a second or two. It is hard to hold it down for more than a few seconds and not screwing up something simple such as navigating your character to go in a straightforward direction. I made too many sharp turns.

Offtopic: PPSSPP does not render subtitles much for me in Daxter cutscenes. Random on/off. A sentence there in beginning... then nothing... then there it is. I tried to fiddle with fullscreen too to see if it would do something and I'm not sure if it does anything at all. It works, it does not work. Should I file an issue or is this somewhat a known issue and I should just brush it off?

**Comment by vsub** [comment]
Any update on this?

**Comment by JeffreyOrange** [comment]
Any way to cap the unthrottle by now?

**Comment by unknownbrackets** [comment]
I'm going to close this since #11187 was implemented.

-[Unknown]
