### ISSUE TITLE
Daxter -- Stuck halfway through the game

### ISSUE THREAD

**Issue by lasers** [hrydgard/ppsspp#7983]
The ice block will not move all the way to the end... making it impossible for me to casually jump across the gap and arrives at the hanging cage with floating orbs.

I was not able to make it across at all using Xbox360 controller (which is a better controller than PSP itself imo). Everything has been great until this part. I have been trying repeatedly and kept coming up just slightly short which is quite out of the character for this game until I realized it might be a bug with PPSSPP.

P.S. The plot for this game Daxter is that an old man named Osmo, whom Daxter meets, hires Daxter as an exterminator working in various parts of Haven City, and occasionally its environs, to exterminate bug-like Metal Heads referred to in-game as 'Metal Bugs'.

Could you please exterminate this bug so I may go on and exterminate the rest of the bugs in the game? Thank you. :-)
  
![output](https://cloud.githubusercontent.com/assets/852504/9975755/34ad1888-5e8d-11e5-898d-8b9c9b1e67e2.png)

**Comment by hrydgard** [comment]
Yeah, bugs like that are usually floating point precision bugs in the emulator. This one may prove tricky to find..

**Comment by lasers** [comment]
That's too big of a distance between the edge and the ice block... making it impossible for my character to arrive on the other side. Do you need anything from my side... such as logs or gamesave? I'm using ppsspp-git.

**Comment by hrydgard** [comment]
Yeah, a game save would be useful, for anyone who would like to look into this. Can't promise I'll get to it soon..

Have you checked if the same issue is present on both PC and Android?

**Comment by lasers** [comment]
SAVEDATA ── https://transfer.sh/a5sHL/ucus98618data00-tar-gz
More details... This is on ArchLinux. Can't test Android. Could test Macbook later.

**Comment by lasers** [comment]
Dude! Dude! I got it! After watching https://youtu.be/Ijo4-3QLYaM?t=27m45s ... I got it! Gotta hit the flamethrower much earlier than usual to get higher air... Right away after double jumps... Don't wait it out a bit... It does not looks like a bug after all. The ice block gap is also shown in the video. Closing! PPSSPP is :100: % perfect! Many thanks!

**Comment by hrydgard** [comment]
Haha, alright :)
