### ISSUE TITLE
Incorrectly resizing after exiting full screen

### ISSUE THREAD

**Issue by vsub** [hrydgard/ppsspp#7986]
1.Start ppsspp and maximize the window
2.Go to the settings
3.Press F11 twice(window to full screen and back to window)

The Back button at the lower left will not be moved to the correct position when you exit full screen it will stay like this(only visible in full screen and partly visible in window mode)until ppsspp is restarted or you restore=>maximize the window

This is not new problem but I wasn't able to find 100% reproducible method till now.

**Comment by vsub** [comment]
It seems it's not related to just menus...around 70px of the bottom of the window\screen are not visible

**Comment by unknownbrackets** [comment]
This one I can reproduce.

-[Unknown]
