### ISSUE TITLE
PPSSPP iPhone Dev-Latest Build - Broken

### ISSUE THREAD

**Issue by jianmingyong** [hrydgard/ppsspp#7990]
The PPSSPP Dev-Latest Build for iphone is broken, no icon to open with.

=> Tried reinstall, restart, rebuild ui cache and restart.

Absolutely nothing. The file size is so small too... Something isn't right.

**Comment by jianmingyong** [comment]
Using "http://cydia.ppsspp.org" repo that can be found on the PPSSPP website.

**Comment by hrydgard** [comment]
Indeed, build has broken somehow. Not sure what's going on.

**Comment by hrydgard** [comment]
There's a little bit more info in #7993, let's keep the discussion there, closing.
