### ISSUE TITLE
Version string corrupted

### ISSUE THREAD

**Issue by sergiobenrocha2** [hrydgard/ppsspp#7991]
Problem appears in both Qt and SDL on linux.

With SDL, with the string "unknown", only the "u" appears.

![version_string_corrupted](https://cloud.githubusercontent.com/assets/5431285/10006499/0f88c2c4-6094-11e5-9d35-4a147ea4cbc2.png)

*it's the git version

**Comment by hrydgard** [comment]
Did a quick workaround for now.
