### ISSUE TITLE
PPSSPP iOS fails to link against iconv — seems like CMake can't find it

### ISSUE THREAD

**Issue by angelXwind** [hrydgard/ppsspp#7993]
Relevant output:

```
Undefined symbols for architecture armv7:
  "_iconv_open", referenced from:
      _avcodec_decode_subtitle2 in libavcodec.a(utils.o)
      _avcodec_open2 in libavcodec.a(utils.o)
  "_iconv", referenced from:
      _avcodec_decode_subtitle2 in libavcodec.a(utils.o)
  "_iconv_close", referenced from:
      _avcodec_decode_subtitle2 in libavcodec.a(utils.o)
      _avcodec_open2 in libavcodec.a(utils.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
	Ld build-ios-fat/Release-iphoneos/PPSSPP.app/PPSSPP normal armv7
(1 failure)
```

As some of you may have noticed, the past few PPSSPP iOS builds have been failing to build successfully.

At this time, I am suspecting that this is actually the fault of CMake and not PPSSPP, after doing some testing with `CMakeLists.txt`. It seems like CMake can't even find iconv, for some reason.

Seeing as I am not experienced with CMake at all, does anyone have any ideas as to what could have caused this?

My guess is that there some sort of weird issue with CMake and iPhoneOS9.0.sdk.

**Comment by hrydgard** [comment]
Hm, what's the first build that started failing? Was it the debian fix?

**Comment by sergiobenrocha2** [comment]
Does it compiles ffmpeg or use from ios/universal ?
There's no way the debian fix broke it, unless you are compiling with a debian distro with ffmpeg installed I guess... https://github.com/hrydgard/ppsspp/blob/master/CMakeTests/FindFFMPEG.cmake#L33

**Comment by angelXwind** [comment]
I believe it should be using ios/universal — I'll check when I get home.

It's compiling on OS X 10.10.5 with Xcode 7, with iPhoneOS9.0.sdk

**Comment by eddiebrook** [comment]
Last build sucefully compiled in cydia is 1.0.1-2668.

**Comment by unknownbrackets** [comment]
Isn't this probably because of the change in the link order or something?

-[Unknown]

**Comment by hrydgard** [comment]
I can't get it to build at all on my mac.   ./b.sh --ios  just doesn't do anything: "No targets specified and no makefile found. Stop."

**Comment by brujo5** [comment]
same post https://github.com/hrydgard/ppsspp/issues/7990

**Comment by hrydgard** [comment]
@unknownbrackets what change in link order?

**Comment by unknownbrackets** [comment]
This one:
https://github.com/hrydgard/ppsspp/commit/c23f51480e4d05545e06406cfb509ce8fa8f69f8#diff-af3b638bc2a3e6c650974192a53c7291R1035

-[Unknown]

**Comment by unknownbrackets** [comment]
That's not it.  Seems like the current Xcode no longer builds even a version from April.  Another victory for auto updates.

-[Unknown]

**Comment by brujo5** [comment]
i think ppsspp for ios broken at this range (2015-09-16)  v1.0.1-2669-gc23f514  +.......

**Comment by unknownbrackets** [comment]
No, I mean I got someone I knew to bisect it for me and they couldn't get it to compile even going all the way back to commits from April.  This was with the latest auto-update Xcode version, which was released recently - Xcode 7.  That was released this month.

-[Unknown]

**Comment by asbel123** [comment]
look at this websiste why ios 9 game not support by campcom http://www.siliconera.com/2015/09/24/capcom-isnt-bothering-to-make-monster-hunter-freedom-unite-compatible-with-ios-9/

**Comment by angelXwind** [comment]
@unknownbrackets Xcode 7 isn't an "auto-update" — Xcode will only auto-update if you explicitly tell it to.

That being said, I think the issue lies more with CMake and Xcode 7/`iPhoneOS9.0.sdk`. I tested this by adding a line that told me if it found `iconv` or not, and it seems like CMake is failing to find `iconv`.

So...

**Comment by hrydgard** [comment]
But, um, it builds for me with Xcode 7, if I generate xcodeproj, open it and run...

**Comment by eddiebrook** [comment]
@hrydgard 

Could you upload the App?

Now that you have MAC and XCODE be possible to add an option to enable ARM64 GIT for iOS?

**Comment by hrydgard** [comment]
No, we need the automatic build to work. I can't manually keep updating it.

Possible yes but I have many other things to do first...

**Comment by angelXwind** [comment]
Huh. That's interesting, @hrydgard. Perhaps it's some weird issue with my setup then... :/

I'll look further into it.

**Comment by angelXwind** [comment]
Nope, still failing :/

I've completely reinstalled Xcode 7 and modified `SDKSettings.plist` in iPhoneOS9.0.sdk accordingly. CMake still can't find/link iconv.

How are you compiling, @hrydgard?

**Comment by hrydgard** [comment]
I did not modify SDKSettings.plist. I did:

    mkdir ios-build
    cd ios-build
    cmake -DCMAKE_TOOLCHAIN_FILE=../ios/ios.toolchain.cmake -GXcode ..
    open PPSSPP.xcodeproj/

Switched target to "IOS device" and pressed Command+B.

This takes me through the entire build up to the codesigning which fails, I haven't looked into that though, could be my expired dev account.

No iconv issues.

    cmake --version
    cmake version 3.2.2

I've installed cmake via brew.

**Comment by angelXwind** [comment]
@hrydgard: The codesigning fails because your `SDKSettings.plist` is not patched for app fakesigning, which is what `PPSSPP.xcodeproj` is configured to use.

I'm pretty sure that yours will fail to link against iconv as well, if you were to fix the codesigning issue. Here, do this:

```
sudo defaults write /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/SDKSettings.plist DefaultProperties -dict-add CODE_SIGNING_REQUIRED -string NO
sudo defaults write /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/SDKSettings.plist DefaultProperties -dict-add ENTITLEMENTS_REQUIRED -string NO
sudo defaults write /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/SDKSettings.plist DefaultProperties -dict-add AD_HOC_CODE_SIGNING_ALLOWED -string YES
```

Then try again from either the Xcode GUI or via `xcodebuild -configuration Release`.

**Comment by hrydgard** [comment]
After executing those lines, all targets disappeared except "My Mac" in XCode, a little thing came up in the error tree view saying "Update to recommended settings", and clicknig that crashes XCode hard. What? :)

**Comment by hrydgard** [comment]
xcodebuild -configuration Release -verbose

     === BUILD AGGREGATE TARGET ZERO_CHECK OF PROJECT PPSSPP WITH CONFIGURATION Release ===

    Check dependencies

    PhaseScriptExecution CMake\ Rules ios-build/PPSSPP.build/Release/ZERO_CHECK.build/Script-0313333335234509ABF92055.sh
        cd /Users/henrikrydgard/ppsspp
        /bin/sh -c /Users/henrikrydgard/ppsspp/ios-build/PPSSPP.build/Release/ZERO_CHECK.build/Script-0313333335234509ABF92055.sh
    echo ""

    make -f /Users/henrikrydgard/ppsspp/ios-build/CMakeScripts/ReRunCMake.make
    make[1]: `/Users/henrikrydgard/ppsspp/ios-build/CMakeFiles/cmake.check_cache' is up to date.

    === BUILD TARGET png17 OF PROJECT PPSSPP WITH CONFIGURATION Release ===

    Check dependencies
    No architectures to compile for (ARCHS=armv7, VALID_ARCHS=i386 x86_64).

    ** BUILD FAILED **


    The following build commands failed:
    	Check dependencies
    (1 failure)

**Comment by angelXwind** [comment]
Try running CMake again? Working fine for me here.

Your SDKSettings.plist should look like this: https://ghostbin.com/paste/f7awa

**Comment by angelXwind** [comment]
After some testing, I am mostly certain that the issue is caused by an incompatibility between CMake and Xcode 7 — CMake's `find_library` call fails, and therefore, `set(FFMPEG_LIBRARIES ${FFMPEG_LIBRARIES} ${ICONV_LIBRARY})` never gets executed.

I tested this by adding the following line right after the `find_library` call: `MESSAGE( STATUS "ICONV_LIBRARY_STATUS:         " ${ICONV_LIBRARY} )`

The generated output of that is: `-- ICONV_LIBRARY_STATUS:         ICONV_LIBRARY-NOTFOUND`

Unfortunately, I have no idea where to go from here. Any ideas?

**Comment by unknownbrackets** [comment]
Maybe iconv is not installed by default or something anymore with Xcode 7.  We're sure it's there to be found?

-[Unknown]

**Comment by hrydgard** [comment]
I tried installing iconv with brew, and it said that it was already installed. However it might be that brew just "knows" that, and now it isn't?

**Comment by HaniKazmi** [comment]
I'm having the same issue trying to build this. iconv.h IS present in /usr/include/, but I can't get cmake to pick it up.

**Comment by hrydgard** [comment]
Maybe we can hardcode the path to iconv somehow?

**Comment by Fadi5555** [comment]
@hrydgard me too having the issue for a while not able to install it because of its incorrect file size

Look at this
![image](https://cloud.githubusercontent.com/assets/10546081/10278455/273f58ba-6b66-11e5-97ec-ac50d2b0b932.jpg)
![image](https://cloud.githubusercontent.com/assets/10546081/10278456/278e7b70-6b66-11e5-9b06-5e4aaa545b9e.jpg)

Any idea how to fix that?

**Comment by JALsnipe** [comment]
For anyone having trouble with libiconv, I found that just adding an additional "Link Binary With Libraries" phase with libiconv2.tbd solved all build issues for me.

If you're getting code sign issues, Xcode 7 now lets developers make builds with a free account.  So click "Fix Issue" and a dev signing certificate should be generated for you locally.  You may need to change the bundle identifier if you get the error "`org.ppsspp.ppsspp` is not available" (I just made minde `org.ppsspp.ppsspp.jal`).

I'm not sure how I would PR the change to use the iOS SDK's version of libiconv, but that seemed to solve all issues for me.

**Comment by eddiebrook** [comment]
@JALsnipe 

Could you upload latest ppsspp.app here?

Thanks

**Comment by TheMarkSter1904** [comment]
I am getting an issue where the PPSSPP (Dev Latest) emulator is not appearing on my iPhone home screen, and the download was only 10.1kb. Is the file corrupted? Before, I remember it working just fine, but now, it is not there anymore.
Source: http://cydia.ppsspp.org/
Author: Henrik Rydgard

**Comment by Fadi5555** [comment]
@TheMarkSter1904 we have the same issue. Just see may comment above.

**Comment by hrydgard** [comment]
@JALsnipe Can you just paste the diff of your cmake change here, or simply post the whole edited CMake file on https://gist.github.com/ , if you're not sure how to make a pull request?

Thanks!

**Comment by JALsnipe** [comment]
I know how to make a pull request.  I'm just not sure how to change the cmake file since the changes I made were just in the generated Xcode project file.  I can look into this more today.

**Comment by hrydgard** [comment]
Cool, thanks.

**Comment by JALsnipe** [comment]
@hrydgard I'm a little lost, never used CMake with an iOS project before.  I'm looking in `ios.toolchain.cmake` but I'm not sure where exactly the command is that generates the Xcode project.  All I want to do is add an additional build action.  This is what it looks like in the `project.pbxproj` file in `PPSSPP.xcodeproj`:

```
/* Begin PBXFrameworksBuildPhase section */

/// ..

		6CAF472C1BC4ABA5005DC5D8 /* Frameworks */ = {
			isa = PBXFrameworksBuildPhase;
			buildActionMask = 2147483647;
			files = (
				6CAF472E1BC4ABAC005DC5D8 /* libiconv.2.tbd in Frameworks */,
			);
			runOnlyForDeploymentPostprocessing = 0;
		};

// ..

/* End PBXFrameworksBuildPhase section */
```

I may also need to add it further up the file chain as well:

```
/* Begin PBXBuildFile section */

// ...

6CAF472E1BC4ABAC005DC5D8 /* libiconv.2.tbd in Frameworks */ = {isa = PBXBuildFile; fileRef = 6CAF472D1BC4ABAC005DC5D8 /* libiconv.2.tbd */; };

// ...

/* End PBXBuildFile section */
```

and 

```
/* Begin PBXFileReference section */

// ..

6CAF472D1BC4ABAC005DC5D8 /* libiconv.2.tbd */ = {isa = PBXFileReference; lastKnownFileType = "sourcecode.text-based-dylib-definition"; name = libiconv.2.tbd; path = usr/lib/libiconv.2.tbd; sourceTree = SDKROOT; };

// ..

/* End PBXFileReference section */
```

**Comment by Fadi5555** [comment]
Please also make 64 bit support for iOS like on android

**Comment by unknownbrackets** [comment]
Does this help?

https://github.com/beardo/libgit2-iOS/blob/master/libgit2/cmake/Modules/FindIconv.cmake

-[Unknown]

**Comment by angelXwind** [comment]
I believe CMake version 3.3.2 (latest from Homebrew) has fixed this issue, as PPSSPP iOS now successfully links against iconv — and as I understand it, no changes were made to the PPSSPP repo regarding the code used to find the iconv library.

Not sure if I should close this or not?

**Comment by unknownbrackets** [comment]
#8038 fixed this, I think?

-[Unknown]

**Comment by angelXwind** [comment]
Ah, probably it then.

**Comment by Fadi5555** [comment]
Please add 64-bit OpenGL 3 for iOS devices
