### ISSUE TITLE
Changing rendering resolution while in-game has no effect

### ISSUE THREAD

**Issue by DonelBueno** [hrydgard/ppsspp#7995]
You have to exit to menu and then open the game again for the resolution change to take effect.

The last working build is v1.0.1-2719-g4c46c8a and the first problematic build is v1.0.1-2728-g54f7a93.

The PR is #7984. I don't have a compiler, so I can't know whick commit caused it.

System Specs:

Windows 10 Pro 64 bits
i7 980x @4.22 GHz
12 GB DDR3 @1766 MHz 7-7-720
Geforce GTX 770 2 GB with Drivers 355.98

**Comment by hrydgard** [comment]
OK, that should have fixed it.

**Comment by DonelBueno** [comment]
Fix confirmed, thanks.
