### ISSUE TITLE
"Load language ini" causes PPSSPP to crash

### ISSUE THREAD

**Issue by tuankiet65** [hrydgard/ppsspp#7996]
It's important that I can use the "load language ini" option when translating but every time I use it, PPSSPP would crash.

On Windows: It would either crash with the Windows crash window, or it would lock up and after that show a warning with the message "Wait for EmuThread timed out."

On Linux: "Segmentation fault (core dumped)"

v1.0.1 and later builds suffer from this bug. This bug also affects both Windows, Linux and Android. I did bisect once but I haven't been able to pinpoint the exact commit that cause this. 

How to reproduce:
- Open PPSSPP v1.0.1 or newer
- Go to Developer Tools
- Click on "Load language ini"
- Press back, it should crash after pressing back.
- If it doesn't, proceed to choose the Graphics/Audio/... submenu. It should crash.

**Comment by hrydgard** [comment]
Thanks for the report, I will take a look.

**Comment by hrydgard** [comment]
That seems to do the trick. Silly mistake by me...

**Comment by tuankiet65** [comment]
That was fast. Gonna test this out tonight.
