### ISSUE TITLE
Display resolution overlay

### ISSUE THREAD

**Issue by jrancher** [hrydgard/ppsspp#7999]
New win 32/64 builds display an overlay of info on screen resolution and window size that cannot be hidden/removed.

**Comment by jrancher** [comment]
went away when installed to different folder

**Comment by jrancher** [comment]
actually this is an issue, applies to directx9 only, not ogl

**Comment by unknownbrackets** [comment]
I guess that's from ec63663ad5a9ff2c7f2dd0659f3cc20f1ae293b2.

-[Unknown]

**Comment by hrydgard** [comment]
Silly mistake by me, fixed.
