### ISSUE TITLE
Auto rendering resolution is broken

### ISSUE THREAD

**Issue by vnctdj** [hrydgard/ppsspp#8002]
As the title says, automatic rendering resolution is not working as it should anymore.
It seems that https://github.com/hrydgard/ppsspp/commit/103b73db18c016f79b0dd81132b3f271311a5417 is the culprit.

What I have done :
1. Open PPSSPP, default window size.
2. Switch to fullscreen.
3. Switch back to small window.
The result :
![0](https://cloud.githubusercontent.com/assets/3978690/10081259/5c753ad8-62f4-11e5-9292-eb344c0eb18c.png)

**Comment by hrydgard** [comment]
Ah, doh. Fixing, another silly little mistake..

**Comment by vnctdj** [comment]
Not really fixed unfortunately...
The displayed message is now correct but it is actually lying !

How to reproduce : 
1. Start PPSSPP with default window size (x2).
2. Change window size (for example x4).
3. You can notice that the rendering resolution is still x2 even though the on-screen message has changed...

**PS :** It seems I can't re-open my own issue :/

**Comment by hrydgard** [comment]
Thank you for your patience @vnctdj , I really need to clean up this code :P  One more try coming soon...

**Comment by hrydgard** [comment]
OK, with that fix I can't reproduce anymore. Let me know if you find anything else..

**Comment by vnctdj** [comment]
I'm afraid this new commit hasn't changed anything for me...
Auto rendering resolution seems to keep the previous resolution :/
It's obvious when you look at an image which has precise details.

**Comment by hrydgard** [comment]
I don't know what to say. I tried both in D3D and GL.

I set window size to 1x and render resolution to auto. It's rendering at 480x272. Pressed F11. It's now fullscreen and is rendering at 2880xwhatever, and the picture is indeed sharp. Pressed F11 again. Back to a window, it's back to rendering at 480x272.

What are you doing?

**Comment by vnctdj** [comment]
Oh ! I have found the problem !
-> Auto rendering resolution is only broken when a postprocessing shader is enabled.

**Comment by LunaMoo** [comment]
There seems to be something fishy happening with postprocessing shaders even with manually selected rendering res, I made a very resolution sensitive scanline shader that simply darkens every second line going like this:

    vec3 color = texture2D(sampler0, v_texcoord0.xy).xyz;
    float SLsize = 1.0;
    vec3 colorSL = color * 2.0;
    float rey = (1.0 / SLsize / u_pixelDelta.y);
    float posSy = v_texcoord0.y*(rey/1.0);
    float lineSy = mod(posSy,2.0);
    color=color-lineSy;
    color=mix(color,colorSL,0.6);
    gl_FragColor.xyz=color;
    gl_FragColor.a = 1.0;

which uses "OutputResolution=True" and even with manually selected rendering resolution as soon as I change window size it get's messed up, it wasn't earlier:]. I have to manually select rendering res after changing window size to correct it again ~ that's with v1.0.1-2788-gd3b265a

**Comment by hrydgard** [comment]
Thanks for your investigation! That would explain why I couldn't reproduce it, I didn't try with post proc. I will investigate.

**Comment by hrydgard** [comment]
@vnctdj @LunaMoo  That should have taken care of the issue when postprocessing is enabled, too.

**Comment by LunaMoo** [comment]
Cool, thanks, can confirm it works fine here.:)

**Comment by vnctdj** [comment]
I confirm the fix too :)
Thank you @hrydgard !
And also thank you @LunaMoo for your testing !
