### ISSUE TITLE
Clannad ULJM05338  video black screen since v1.0.1-857-g08b340f in directx 9

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#8003]
@hrydgard 
this commit 
https://github.com/hrydgard/ppsspp/commit/08b340f423c5c4a09653cca345f4fd43297cffaa

If I enable back  viewZScale *= 2.0f; in GPU/Directx9/ShaderManagerDX9.cpp 
,it fixed

v1.0.1-2768-gd8b43dd  directx 9 log:
https://gist.github.com/sum2012/6f4305fb53b4b6889b57

**Comment by hrydgard** [comment]
Test Phantasy Star with that change too..

**Comment by unknownbrackets** [comment]
Has this improved at all with the latest depth changes?

-[Unknown]

**Comment by sum2012** [comment]
Test v1.1.1-715-gc19335f fixed
