### ISSUE TITLE
Final Night Round 3 missing UI in D3D9 , garbled menus in OpenGL

### ISSUE THREAD

**Issue by Trokinos** [hrydgard/ppsspp#8004]
Hello, 

On my WinXP (win32), while replaying FNR3 in the latest build ( v1.0.1-2772-geed2f9d ) i noticed a problem i didn't observed before.

In OpenGL the menus are garbled, but i was expecting it as they have always been garbled in FNR3 OGL as long as i can remember using PPSSPP  :
http://i.imgur.com/uWKrJca.jpg

But ingame the UI is correct (though in most arenas there's a garbled texture where there is an animated panel, in the screenshot you can see an example of this) :
http://i.imgur.com/97iAeW0.jpg

Now in D3D9, the new problem i never saw before, while the menu are as correct as they always had been :
http://i.imgur.com/2yVe9HF.jpg

Ingame you lose part of the UI :
http://i.imgur.com/jHg8T8O.jpg

The OpenGL problem i always had it since forever with PPSSPP, and why i was playing the game in D3D9 that was perfect so far (performance ingame is equal in D3D9 and OpenGL).

I tested older builds and noticed that the last version in which D3D9 was perfect is :
v1.0.1-832-ge99ba86

And the 1st version in which D3D9 has missing UI elements with the game is :
v1.0.1-849-g12884ec

Can't pinpoint more unfortunately as there's no win32 builds available between those 2

**Comment by sum2012** [comment]
That mean #7920 .
Fix 1 game then break 1 game......

**Comment by hrydgard** [comment]
OK, that does it. Depth is apparently completely impossible to emulate 100% accurately without doing it all in software, so we'll need flags to disable the depth rounding in some games. I'm on it.

Also the OpenGL issue is interesting..

**Comment by Trokinos** [comment]
The strange thing about opengl garbled menu is that it's the only game that does it on my system in opengl, even games with animated menus (Peace Walker or WWE All Stars) are rendered correctly.

**Comment by hrydgard** [comment]
OK, I'm turning off the depth fix in this game.

If that doesn't fix it, let me know the "game ID" of your copy of final night round 3 (rightclick the game in PPSSPP to find out).

The garbled menus are interesting, I think it's related to the pixellation issue we've seen before in this game, where the game uses projective texturing for no good reason and the fragment shader precision of the GPU isn't enough to calculate the texture coordinate properly.

**Comment by Trokinos** [comment]
I just gave a try to the latest build : v1.0.1-2782-g5ff5cf1 (win32) and the missing UI element in D3D9 problem is still there, for the game ID, you mean the Ublablabla code (as it's the only one i see if i right click the icon) ?
If it's the case, for my FNR3 (european version) it's ULES00270
In case you need it too, i googled and found that the US code for FNR3 is ULUS10066

**Comment by sum2012** [comment]
@Trokinos Please try again in v1.0.1-2783-g3c499fd
It now include compat.ini which fix this problem in D3D9

**Comment by Trokinos** [comment]
I downloaded latest version, v1.0.1-2787-g89513a3 , and the issue in D3D9 and FNR3 is fixed from what i just tested.

Thank you very much.
I' am not sure if i should close the issue or if i should left it open for the "opengl garbled menu" side , as only the D3D9 problem is no more.

**Comment by hrydgard** [comment]
Great!

The garbled thing is still a bit interesting. What GPU do you have?

**Comment by Trokinos** [comment]
It's a G41chipset  from Intel (GMA X4500) , and from what i read when using the GPU Caps Viewer, it's supporting OpenGL 2.1 

The most OpenGL-intensive program i'm using, Blender, works very nicely on it, but it's only requiring OpenGL 1.4 to OpenGL 2.1 at the time)
But i wouldn't be surprised if there are specific extensions from that version of OpenGL 2.1 that Intel didn't bothered to get right for that (now old) chipset, i remember Intel were not really having a good reputation with their windows drivers when it comes to OpenGL while this card had still drivers being released.
So in case FNR3 require one of those, it could explain the garbled menu (though the problem isn't happening for any other of my games on ppsspp with the OpenGL backend)

**Comment by unknownbrackets** [comment]
I wonder if the hack is only needed for older cards...

-[Unknown]
