### ISSUE TITLE
Switch to GPU backends bug since v1.0.1-579-g00e57b1

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#8009]
@hrydgard 
this pull commit #7808 
![2](https://cloud.githubusercontent.com/assets/2177532/10122261/92d7473a-6545-11e5-810e-56219dd88f2f.jpg)

If we make the words shorter,we might need to change all langs file .....

**Comment by hrydgard** [comment]
Hm, the text got too big? I'll take a look...

**Comment by sum2012** [comment]
Thanks @hrydgard

**Comment by thedax** [comment]
We should probably change that to one of those spiffy popup message boxes we have. I think a long time ago I had a patch ready for it, but I forget why I never opened a pull request..
