### ISSUE TITLE
Musou Orochi -Maou Sairin Enhanced Version black screen in D3D9 since v1.0.1-832-ge99ba86

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#8010]
Musou Orochi -Maou Sairin Enhanced Version black screen in D3D9 since v1.0.1-832-ge99ba86
as @hrydgard is changing compat.ini so that I don't make pull request
![2](https://cloud.githubusercontent.com/assets/2177532/10122779/10c4f5ec-6556-11e5-813c-5aff34bd9ff4.jpg)

**Comment by sum2012** [comment]
Same issue as nornal version 

![5](https://cloud.githubusercontent.com/assets/2177532/10123236/0b23fa8c-6567-11e5-851f-0be61affe7fc.jpg)

**Comment by GamerzHell9137** [comment]
Maybe you should do this
https://github.com/hrydgard/ppsspp/wiki/How-to-find-a-graphic-issue-with-the-GE-debugger
And post the details here.

**Comment by unknownbrackets** [comment]
Let's make sure there's not just a regular old bug here (exposed by those changes) before we give up and make the game do the other thing.  What kind of depth test is it using when it tries to draw the area that ends up black?

-[Unknown]

**Comment by sum2012** [comment]
I take nornal version.ULJM05402 as example
![1](https://cloud.githubusercontent.com/assets/2177532/10124412/24d41f8c-6587-11e5-98cf-dc824717dfff.jpg)

**Comment by sum2012** [comment]
@unknownbrackets depth test screen
![2](https://cloud.githubusercontent.com/assets/2177532/10124439/a54a774c-6587-11e5-872e-0b4f2a4adb80.png)

**Comment by unknownbrackets** [comment]
That depth test is disabled.  It needs to be right after clicking "step prim".  The highlighted red area should include the part that stays black.

-[Unknown]

**Comment by sum2012** [comment]
@unknownbrackets 
![3](https://cloud.githubusercontent.com/assets/2177532/10124515/421fbfd6-6589-11e5-9833-04cfa7631c54.png)

**Comment by unknownbrackets** [comment]
Does this work by default now?

-[Unknown]

**Comment by sum2012** [comment]
test v1.1.1-715-gc19335f ,fixed
