### ISSUE TITLE
Source code for advertisement handling in the free Android version

### ISSUE THREAD

**Issue by neobrain** [hrydgard/ppsspp#8018]
It recently came to my attention that the free PPSSPP Android version now comes bundled with ads, which by itself is okay, I suppose. However, I have not found any source code in the GitHub repository that deals with advertisements, and someone on IRC suggested it indeed is not available publicly. However, I'm sure people realize that technically, the GPL requires distributions of binaries to be accompanied with the **full** source code used to build the binary from.

This might naively be considered a minor issue, but I can see multiple issues with that (most importantly, I'd like to be able to inspect what kind of services are being communicated with, and in which way, and what kind of data third parties might gather from me running PPSSPP). Even without further reasoning though, this issue should be resolved or the bundled advertisements removed if full source code cannot be provided for legal reasons.

**Comment by hrydgard** [comment]
It's a trivial amount of code copy-pasted from a sample (it's just google admob, nothing else - it shows an ad once, after playing), but sure, I will push the branch shortly so you can have a look. You are right that for complete compliance it should be public. There are no legal or other issues really, the branch is just a mess of a series of merges right now so I'll clean it up first.

**Comment by neobrain** [comment]
I see. Thanks for the info, looking forward to it ;)

**Comment by hrydgard** [comment]
Here's a gist that contains the full code change (only redacted the ad ID) for the current ad in the Google Play build, which uses the recently deprecated AdMob library directly: 

https://gist.github.com/hrydgard/7000f745603a37cfe3ab

I'm considering dropping the ad in 1.1. Issues have been raised around the GPL library exception and Google Play Services.
