### ISSUE TITLE
Weird problem with the "Create game config" button

### ISSUE THREAD

**Issue by vsub** [hrydgard/ppsspp#8020]
It's not really a big deal because it appear on your second attempt.
This is what I do:
1.Download the latest beta and run any game
2.Exit the game and right click on it.

The weird thing is that on certain games,the button always appear when you start ppsspp and directly right click on a game,but on some games,you have to right click=>go back=>right click again to make the button to appear(it will always appear from then on on every game that needed doing this twice until you restart ppsspp)

It seems this problem happens on it the Recent tab or maybe if you have less games on it(it doesn't happen if you directly go to the games list(don't have anything in recent)or you go from recent to all games and go back to recent.

**Comment by hrydgard** [comment]
Hm, that one seems hard to repro, I failed. Found and fixed another couple of menu bugs when doing so though :)

https://github.com/hrydgard/ppsspp/commit/682472c5b59f8cc3e4bafff9e0b4f5dc1a2d4edd
https://github.com/hrydgard/ppsspp/commit/8ab0a3cf7c97735ddd7bcd02b4670f05d8326ccb

Do you think you could a bit more to find a solid repro?

**Comment by vsub** [comment]
Try this then(it seems 100% reproducible)

1.Start the latest beta without any settings
2.Run the cube.iso(I dropped the file)
3.Emulation=>Stop=>right click on the cube.iso icon and you will see that the button is missing and that it will appear if you exit that screen and enter again

It will also not appear if you do all that,then start ppsspp and directly right click on on the icon

**Comment by hrydgard** [comment]
Thanks, I got it. Now to investigate...

**Comment by unknownbrackets** [comment]
Does that mean this is false?

https://github.com/hrydgard/ppsspp/blob/8ab0a3cf7c97735ddd7bcd02b4670f05d8326ccb/UI/GameScreen.cpp#L90

-[Unknown]

**Comment by hrydgard** [comment]
Exactly, was reading data too soon, before the GetInfo background thread actually filled out the information - in case the case we hadn't read it before, which can be either the slashes the wrong way around (as mentioned on irc) or game not visible in gamelist or whatever. Now we wait first to be safe, but should fix the slash problem as well.

**Comment by vsub** [comment]
Fixed,thanks
