### ISSUE TITLE
Loading savestate JIT memory leak "Warning Failed to Allocate Executable Memory"

### ISSUE THREAD

**Issue by CarlKenner** [hrydgard/ppsspp#8021]
On Windows, if I press F4 to load a savestate about 50 times in a row, I get the warning "Warning Failed to Allocate Executable Memory" followed by a crash.

Unfortunately, I need to be able to load a savestate literally 10,000 times in a row, in order to bruteforce test which game function I need to disable to disable culling for Virtual Reality.

**Comment by unknownbrackets** [comment]
What Windows version?  32 or 64 bit?

I feel like loading a savestate 10,000 times is the wrong way.  Are you aware of the debugging features?  It's most likely writing the cull setting to a display list...?

-[Unknown]

**Comment by CarlKenner** [comment]
64 bit, Windows 10. I checked the functions which allocate executable memory, and allocate and release are both being called 4 times. So I think something else is using up the memory space. When I use Visual Studio 2013's memory profiling, memory usage increases every time I press F4, until it reaches about 512 Megabytes, then I get the warning and crash. It's very easy to replicate, just press F4 50 times.

Loading a savestate 10,000 times is what we do in Dolphin VR. It's necessary because we are disabling each of the game's functions in turn, which can do almost anything to the memory or other state, so we need to restore back to a known state each time. Admittedly, it still crashes so we have to relaunch the .exe occasionally. I did add some features to Dolphin's debugger to help with finding a matching version of the function in the different region, but that only works after we bruteforced the function in the first region.

I'm not talking about backface culling, that is easy to find with the debugger tools. I'm talking about finding a function that compares an object's bounding box to the view and projection matrices to see whether or not to draw it. Without the function names, that is hard. Are there any games that have map files with all the function names?

**Comment by hrydgard** [comment]
The only game I know that comes with symbols is a simple 2D game which is unlikely to have such a function, but there may of course be others.

If memory increases like that on state load we indeed must have a bug...

**Comment by CarlKenner** [comment]
If I disable destroying and recreating the JIT, then I can run it 4616 times before it crashes with std::bad_alloc on u8 *uncomp_buffer = new u8[header.UncompressedSize];

Which suggests either there are two leaks, one recreating the JIT, and one elsewhere, or the leak elsewhere steals memory from a limited location needed for recreating the JIT.

BTW, how do I temporarily modify a function in PSP memory, which I have the address for, to return 0 instead of running? I assume I need to somehow tell the JIT to reprocess it.

**Comment by hrydgard** [comment]
No, just overwriting the first instruction with anything will cause the JIT to reprocess it.

I assume it would be something like

    jr ra
    li v0, 0

(keep in mind the MIPS delay slot)

**Comment by i30817** [comment]
I've actually been getting crashes on linux 64 after loading (different) savestates a lot of times (because i'm cheating). I didn't report because frankly, i didn't want to bother regression testing. But yeah, savestates are probably screwy.

**Comment by unknownbrackets** [comment]
Okay, this is pretty simple an Windows only afaict.

-[Unknown]

**Comment by unknownbrackets** [comment]
@i30817 if this happens on Linux as well, there's a separate bug.  If it started recently, bisecting would be nice - even just a wide range, like 1.0.0 doesn't do it, since we don't change this code often.  The code involved here was Windows x64 specific.

That being said, if you're getting a different error, it can be all kinds of diferent things.  For example might be an issue with cheats + savestates.

-[Unknown]
