### ISSUE TITLE
Expand #7997 (save states files naming) to cheat files

### ISSUE THREAD

**Issue by pal1000** [hrydgard/ppsspp#8023]
I know this came at a really bad time, right after release. To be honest I didn't expect it to be today.
But without this #7997 looks like only half done and is a missed opportunity.

**Comment by hrydgard** [comment]
Yes, good point. The whole "game id" logic needs cleaning up.

There's always 1.2, and I'm hoping to release that a bit faster...

**Comment by unknownbrackets** [comment]
Heh, famous last words.

Are there any other things which use the game id?  There's the "fixes" and I think the savedata manageement (but the latter is a mostly lost cause with homebrew), and the title and UI.

We should probably have the logic in `GenerateSaveSlotFilename` moved to the gameinfo cache, and have that be one of the things it's responsible for - resolving the game id?  Then we just need "current gameinfo" somehow?

-[Unknown]

**Comment by hrydgard** [comment]
Yes, exactly my plan :)
