### ISSUE TITLE
Replacing emulator's font doesn't work

### ISSUE THREAD

**Issue by SukharevAndrey** [hrydgard/ppsspp#8024]
I tried to use modern version of Roboto Condensed (version 2.001201) font in PPSSPP (version 1.1 release), which is quite better than the bundled one (version 1). I replaced Roboto-Condensed.ttf in assets folder of emulator with the new one, but PPSSPP suddenly uses default system font (Arial) instead. It happens also with any other font.
If I write any font name (installed in system) in a language ini file, it does work.

**Comment by unknownbrackets** [comment]
The font name was changed - it's now "Roboto Condensed" instead of "Roboto", which is probably more correct.  That's why you're getting the problem.

-[Unknown]
