### ISSUE TITLE
Tekken 6 crash in Versus Screen (OpenGL only)

### ISSUE THREAD

**Issue by Combone** [hrydgard/ppsspp#8027]
I tested latest version and continue crash :(

But...

Direct3D9 works.

Note: My Video Card is Nvidia (GTX 550 TI).

**Comment by hrydgard** [comment]
Which screen is the "versus screen" ?

**Comment by Combone** [comment]
After choose character...In "Get Ready For The Next Battle".

Emulator crash.

**Comment by hrydgard** [comment]
Strange, I haven't had any problems with crashing in tekken. Geforce 7xx here (don't remember exactly which one)

**Comment by Combone** [comment]
Look Debug Console...

http://i.imgur.com/kQlSsC6.png?1

**Comment by unknownbrackets** [comment]
Could (unlikely but maybe given GL only?) be caused by the same as #8039?  Darn vertex cache... forgot to test with it at all.

-[Unknown]

**Comment by Combone** [comment]
Tested again and continue crash =/

But..I created Save State in Direct3D (During Battle) and load  in OpenGL game not crash.

Strange ~_~"

Another thing...With "Fast Memory" Off (OpenGL)
Tekken 6 freeze In "Get Ready For The Next Battle".

**Comment by sum2012** [comment]
Does v1.1.0-36-g06cbc31 or newer version fix it ?

**Comment by Combone** [comment]
Tested now and works perfect (OpenGL)

Thanks All ^_^
