### ISSUE TITLE
Fullscreen / Menu / MotorStorm

### ISSUE THREAD

**Issue by lasers** [hrydgard/ppsspp#8029]
1) Weird fullscreen issues. Fullscreen does not always work the same way. Terrible in GNOME. Almost fullscreen (90%) in i3wm. Sometimes perfect fullscreen. Fullscreen works 100% perfectly in the menu.
2) Glitchy PPSSPP Menu. Kept going down nonstop. Nothing occurred in xev to rule out any potential hiccups in physical / touchscreen / touchpad / other xinputs. 
3) MotorStorm renders the shadow for the vehicles as partially transparent blocks. Minor issue?

1) and 2) didn't occur for me in the past with Daxter.

Ignore the discolorations. That's just animated gifs.
PPSSPP v1.1.0-2-g94477df

![2015-10-05-071606_1366x768_scrot](https://cloud.githubusercontent.com/assets/852504/10280815/82fb093c-6b35-11e5-8424-3844c21bc52a.png)
![2015-10-05-074219_1366x768_scrot](https://cloud.githubusercontent.com/assets/852504/10280816/8815e090-6b35-11e5-8cda-9a157c15ae9a.png)
![omg](https://cloud.githubusercontent.com/assets/852504/10280779/414a9d36-6b35-11e5-964d-a9e7ebfdfa0c.gif)
![omg2](https://cloud.githubusercontent.com/assets/852504/10280780/414b320a-6b35-11e5-8d24-2f35e1d006a9.gif)

**Comment by hrydgard** [comment]
We recently did some refactoring of the resizing code but only tested it really on Android and Windows as those are the main platforms for the 1.1 release, so something must have been missed in the SDL build (that's what this is, right?)

I will take a look soon.

**Comment by lasers** [comment]
Yes. I don't have Windows / Android. The thing about this is that I tried this on a computer with non-gaming GPU and that (kept-going-down) menu does not occur here. I will investigate the laptop (Thinkpad Twist) some more as it could be the touchscreen / touchpad. I'm seeing some of the fullscreen effects though on the computer.

**Comment by lasers** [comment]
No more 1) and 2). I got rid of the glitchy menu by starting with a fresh copy of ~/.config/ppsspp -- This includes the fullscreen changes (if any) from default setting so I'm not seeing any odd fullscreen issues right now. I suppose you can close this issue. 3) still occurs though. :)

**Comment by hrydgard** [comment]
You don't happen to have the old  ~/.config/ppsspp/PSP/SYSTEM/ppsspp.ini around?

**Comment by lasers** [comment]
I think I'll stop playing this game. The emu pretty much froze on the second mission with a clean profile. Here's the ppsspp.ini -- https://gist.githubusercontent.com/anonymous/7fd468f1f0f0592d88b9/raw/64e0905557f30595f383b49d7dd266335cc321e9/ppsspp.ini

**Comment by hrydgard** [comment]
@lasers Thanks. Yeah, the game is one of the few high-profile games that just isn't working very well yet.
