### ISSUE TITLE
Compiling PPSSPP for iOS problems in IOS9?

### ISSUE THREAD

**Issue by uil330** [hrydgard/ppsspp#8030]
Hello
I attempted to generated the iOS xcode project but received several errors. Here is the output from the terminal:

```
Building for iOS
~/Documents/ppsspp/build-ios ~/Documents/ppsspp
Building for ARMv7, Release
make: *** No targets specified and no makefile found.  Stop.
```

But the folder "build-ios" is created. So I open PPSSPP.xcodeproj in xcode and build it , and I get an error:

```
clang: error: the clang compiler does not support '-march=armv7-a'
```

It seems that the problem is the archive which used in Android is using in IOS.  
Thanks a lot!

**Comment by hrydgard** [comment]
You have to switch to target "Device" instead of one of the simulator targets. PPSSPP does not currently support building for the simulator, although we should.

Still, there will be some issues building that we haven't currently solved :( 

If you manage to get it to build again, please tell us how :)

**Comment by uil330** [comment]
Thank you for your response. :)

I have tried it with my iPad but false. Now I try to read the makefile but until this weekend i haven't enough time to make sure why happened. :(

**Comment by unknownbrackets** [comment]
So, I think the issue here is that you may have set the build settings to compile for armv8 as well.  I don't know what needs to be done to make armv8 work, but it generates errors right now - and this is apparently one of them.

Might try from a clean cmake.

-[Unknown]

**Comment by unknownbrackets** [comment]
Going to close this assuming you got it working.  If there are still problems, feel free to comment, open a new issue, or post on the forum.

-[Unknown]
