### ISSUE TITLE
Ridge Racer polygon flickering on PPSSPP v1.1.0 

### ISSUE THREAD

**Issue by ppsspp-gamer** [hrydgard/ppsspp#8031]
Ridge Racer polygon flickering on v1.1.0 (both OpenGL and D3D9 backends)
![screen1](https://cloud.githubusercontent.com/assets/8726272/10285143/08ace6d4-6bba-11e5-8bf6-f442d5bb5fbf.png)

No this problem on v1.0.1
![screen2](https://cloud.githubusercontent.com/assets/8726272/10285014/94eb5b40-6bb9-11e5-9280-d3d60bb78b0d.png)

Tested with PPSSPP v1.1.0 win x64 build downloaded from PPSSPP web site, with default settings except 3x internal resolution. There are several locations on this track have this issue. 

Realtime save state can download from here: http://www.mediafire.com/download/7x9b3v3qle6oeth/ULUS10001_STATE.7z

**Comment by unknownbrackets** [comment]
I'm guessing this is also #8039.

-[Unknown]

**Comment by daniel229** [comment]
That is caused by https://github.com/hrydgard/ppsspp/pull/7920

**Comment by unknownbrackets** [comment]
Oh, right, okay.  Ugh, another one of these precision things.

-[Unknown]

**Comment by hrydgard** [comment]
As the game doesn't benefit from the rounding in #7920, I'll just add another entry in the compat.ini...

**Comment by ppsspp-gamer** [comment]
PPSSPP build v1.1.0-11-ge9d84b6 fixes this issue.
