### ISSUE TITLE
Shadow issue for God Of War on PPSSPP 1.1 for PC

### ISSUE THREAD

**Issue by zminhquanz** [hrydgard/ppsspp#8033]
There are show two shadow in this game , you can see the picture down there
![bug ppsspp 2](https://cloud.githubusercontent.com/assets/11285640/10314591/ce5a5086-6c7f-11e5-8720-d6206e7fe4ba.png)

**Comment by hrydgard** [comment]
Did you check if this does not happen on the real PSP? The game does not have 100% perfect shadows everywhere.

**Comment by zminhquanz** [comment]
Oh ! I See , on real PSP is similar bug

**Comment by unknownbrackets** [comment]
Then I'll close this.

-[Unknown]
