### ISSUE TITLE
p3p crash

### ISSUE THREAD

**Issue by gapdi** [hrydgard/ppsspp#8034]
persona 3 portable is crash in starting.

case korean version.

**Comment by hrydgard** [comment]
Yes, it seems it crashes on 64-bit ARM.

If you turn off the Dynarec (JIT) in Tools/Developer Tools, it will run, although slower. That means that it's a JIT bug, and I will investigate shortly.

**Comment by hrydgard** [comment]
This crash is related to "Static register allocation", a new optimization that we only enable on ARM64 so far. Disabling it in the source code (in JitState.cpp) lets the game start.

Stay tuned, more tomorrow :)
