### ISSUE TITLE
Dragon Ball Tag Versus crashed in battle

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8037]
Since https://github.com/unknownbrackets/ppsspp/commit/c7e6f051e429f3d8db17626556dd59ee943d585e in https://github.com/hrydgard/ppsspp/pull/7870

stack trace
![01](https://cloud.githubusercontent.com/assets/3481559/10355712/8136fb6a-6da1-11e5-9df4-a2203c82b0af.png)

**Comment by unknownbrackets** [comment]
This is with GLES?  Does disable slow effects affect it?

That stack trace is garbage.

-[Unknown]

**Comment by daniel229** [comment]
Yes,crash in OpenGL,D3D9 is fine,but a blackground, after disabling slow effects,it does not crash.

**Comment by unknownbrackets** [comment]
This does not crash for me in the Dragon Ball Z: Tenkaichi Tag Team Demo.  I do get black in Direct3D9, but I think that is not new.

If you leave slow effects on, but comment out this line (it appears twice), does it crash?

depal = depalShaderCache_->GetDepalettizeShader(clutFormat, framebuffer->drawnFormat);

-[Unknown]

**Comment by daniel229** [comment]
it does not crash.

**Comment by unknownbrackets** [comment]
I assume if you only comment out the one in `ApplyTextureFramebuffer`, it still doesn't crash?

So that means something inside the `if (depal) {` is crashing.  What if you take this entire part:

```c++
	shaderManager_->DirtyLastShader();

		glUseProgram(depal->program);

		glstate.arrayBuffer.unbind();
		glstate.elementArrayBuffer.unbind();
		glEnableVertexAttribArray(depal->a_position);
		glEnableVertexAttribArray(depal->a_texcoord0);

		glActiveTexture(GL_TEXTURE3);
		glBindTexture(GL_TEXTURE_2D, clutTexture);
		glActiveTexture(GL_TEXTURE0);

		framebufferManager_->BindFramebufferColor(GL_TEXTURE0, gstate.getFrameBufRawAddress(), framebuffer, BINDFBCOLOR_SKIP_COPY);
		glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST);
		glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST);

		glDisable(GL_BLEND);
		glColorMask(GL_TRUE, GL_TRUE, GL_TRUE, GL_TRUE);
		glDisable(GL_SCISSOR_TEST);
		glDisable(GL_CULL_FACE);
		glDisable(GL_DEPTH_TEST);
		glDisable(GL_STENCIL_TEST);
#if !defined(USING_GLES2)
		glDisable(GL_LOGIC_OP);
#endif
		glViewport(0, 0, framebuffer->renderWidth, framebuffer->renderHeight);

		glVertexAttribPointer(depal->a_position, 3, GL_FLOAT, GL_FALSE, 12, pos);
		glVertexAttribPointer(depal->a_texcoord0, 2, GL_FLOAT, GL_FALSE, 8, uv);
		glDrawElements(GL_TRIANGLE_STRIP, 4, GL_UNSIGNED_BYTE, indices);
		glDisableVertexAttribArray(depal->a_position);
		glDisableVertexAttribArray(depal->a_texcoord0);

		fbo_bind_color_as_texture(depalFBO, 0);
		glstate.Restore();
```

And replace with:

```c++
		framebufferManager_->BindFramebufferColor(GL_TEXTURE0, gstate.getFrameBufRawAddress(), framebuffer, BINDFBCOLOR_MAY_COPY_WITH_UV | BINDFBCOLOR_APPLY_TEX_OFFSET);
```

Does it also crash?  This will still create and bind the temp FBO, but won't use it.

If that does work, how much of the original code can you keep until it crashes?

-[Unknown]

**Comment by daniel229** [comment]
Only comment out the one in <code>ApplyTextureFramebuffer</code>,it does not crash.
Replace that code it won't crash.
keep the two lines it won't crash,after that it start crasing.
```
    shaderManager_->DirtyLastShader();

        glUseProgram(depal->program);
```

**Comment by daniel229** [comment]
Final Fantasy type 0 also crashed in world map or inside the building.

**Comment by daniel229** [comment]
Dragon Ball Z: Tenkaichi Tag Team Demo also crash
![02](https://cloud.githubusercontent.com/assets/3481559/10357630/e164e546-6db6-11e5-909f-43429f78c785.png)

**Comment by unknownbrackets** [comment]
And none of these give useful stack traces?

Hmm.  Maybe it's because I have vertex cache off.

-[Unknown]

**Comment by unknownbrackets** [comment]
Got it, crashes with vertex cache on, let's see.  Must need to have the verts bound afterward.

-[Unknown]
