### ISSUE TITLE
Gundam Vs. Gundam: Next Plus has more lag in v1.1.0-19-g4aceb47 than before version

### ISSUE THREAD

**Issue by leoxxx** [hrydgard/ppsspp#8044]
I enable the "Auto FrameSkip"。But it still has more lag.
In before version(1.0.1)，it has less lag.

**Comment by hrydgard** [comment]
What device are you running the emulator on?

**Comment by leoxxx** [comment]
@hrydgard
it be run in PC.
CPU:I5 3470
GPU:7850 1G

**Comment by unknownbrackets** [comment]
Does the speed improve (even ig the graphics are worse) with "disable slower effects", or does that option have no effect?  Also, do you use texture scaling?

-[Unknown]

**Comment by leoxxx** [comment]
@unknownbrackets
I don't know which option you say.
It's my ini file. I copy it from old version and it be used in last version
[General]
FirstRun = False
Enable Logging = True
AutoLoadLast = False
AutoRun = True
Browse = False
ConfirmOnQuit = False
IgnoreBadMemAccess = True
CurrentDirectory = F:/ppsspp/ROMS/
ShowDebuggerOnLoad = False
ReportingHost = default
Recent = F:/ppsspp/ROMS//gbu.ISO
AutoSaveSymbolMap = False
TopMost = False
WindowX = 153
WindowY = 73
Language = zh_CN
NumWorkerThreads = 8
EnableCheats = False
ScreenshotsAsPNG = True
StateSlot = 0
GridView1 = True
GridView2 = True
GridView3 = True
WindowWidth = 968
WindowHeight = 591
PauseOnLostFocus = False
RewindFlipFrequency = 0
EnableAutoLoad = False
RunCount = 221
CheckForNewVersion = False
DumpDecryptedEboots = False
ForceLagSync = False
PauseWhenMinimized = False
CacheFullIsoInRam = False
CwCheatRefreshRate = 77
InternalScreenRotation = 1
[CPU]
Jit = True
SeparateCPUThread = False
SeparateIOThread = False
FastMemory = False
CPUSpeed = 0
AtomicAudioLocks = False
FastMemoryAccess = False
FuncReplacements = True
SetRoundingMode = True
ForceFlushToZero = False
IOTimingMethod = 0
[Graphics]
ShowFPSCounter = 0
ResolutionScale = 2
RenderingMode = 1
SoftwareRendering = False
HardwareTransform = True
TextureFiltering = 1
SSAA = False
FrameSkip = 1
FrameRate = 0
ForceMaxEmulatedFPS = 0
AnisotropyLevel = 0
VertexCache = True
FullScreen = False
FullScreenOnLaunch = False
StretchToDisplay = True
TrueColor = True
MipMap = False
TexScalingLevel = 1
TexScalingType = 0
TexDeposterize = False
VSyncInterval = True
DisableStencilTest = False
AlwaysDepthWrite = False
InternalResolution = 0
FrameSkipUnthrottle = True
LowQualitySplineBezier = False
FXAA = False
PostShader = Off
VertexDecoderJit = True
SoftwareSkinning = True
TimerHack = False
PartialStretch = False
AutoFrameSkip = True
TextureBackoffCache = True
TextureSecondaryCache = False
SmallDisplay = False
ImmersiveMode = False
AlphaMaskHack = False
AndroidHwScale = 1
SplineBezierQuality = 0
MemBlockTransferGPU = True
DisableSlowFramebufEffects = False
GPUBackend = 0
BufferFiltering = 1
FragmentTestCache = True
DepthRangeHack = False
EnableCardboard = False
CardboardScreenSize = 50
CardboardXShift = 0
CardboardYShift = 0
BloomHack = 0
[Sound]
Enable = True
EnableAtrac3plus = True
VolumeBGM = 8
VolumeSFX = 8
LowLatency = False
AudioLatency = 1
SoundSpeedHack = True
AudioBackend = 0
AudioResampler = True
[Control]
ShowAnalogStick = False
ShowTouchControls = False
AccelerometerToAnalogHoriz = False
TouchButtonOpacity = 65
ButtonScale = 1.150000
TiltSensitivity = 100
HapticFeedback = True
ShowTouchCross = True
ShowTouchCircle = True
ShowTouchSquare = True
ShowTouchTriangle = True
ShowTouchStart = True
ShowTouchSelect = False
ShowTouchLTrigger = True
ShowTouchRTrigger = True
ShowTouchUnthrottle = True
ActionButtonSpacing = 57
ActionButtonCenterX = 0.928571#INF00#INF00
ActionButtonCenterY = 0.877925#INF00#INF00
DPadX = 0.085119#INF00#INF00
DPadY = 0.940997#INF00#INF00
StartKeyX = 0.578571#INF00#INF00
StartKeyY = 0.929807#INF00#INF00
SelectKeyX = 0.500000#INF00#INF00
SelectKeyY = 0.929807#INF00#INF00
UnthrottleKeyX = 0.420833#INF00#INF00
UnthrottleKeyY = 0.929807#INF00#INF00
LKeyX = 0.047619#INF00#INF00
LKeyY = 0.046796#INF00#INF00
RKeyX = 0.958929#INF00#INF00
RKeyY = 0.046796#INF00#INF00
AnalogStickX = 0.085119#INF00#INF00
AnalogStickY = 0.906409#INF00#INF00
ShowTouchDpad = True
DisableDpadDiagonals = False
ActionButtonScale = 1.150000
ActionButtonSpacing2 = 1.000000
DPadScale = 1.150000
DPadSpacing = 1.000000
StartKeyScale = 1.150000
SelectKeyScale = 1.150000
UnthrottleKeyScale = 1.150000
LKeyScale = 1.150000
RKeyScale = 1.150000
AnalogStickScale = 1.150000
TouchButtonStyle = 1
ShowTouchPause = False
IgnoreWindowsKey = False
AnalogLimiterDeadzone = 0.600000
GamepadOnlyFocused = False
AutoCenterTouchAnalog = False
DInputAnalogDeadzone = 0.100000
DInputAnalogInverseMode = 0
DInputAnalogInverseDeadzone = 0.000000
DInputAnalogSensitivity = 1.000000
XInputAnalogDeadzone = 0.240000
XInputAnalogInverseMode = 0
XInputAnalogInverseDeadzone = 0.000000
XInputAnalogSensitivity = 1.000000
[SystemParam]
NickName = PPSSPP
Language = 11
TimeFormat = 2
DateFormat = 1
TimeZone = 0
DayLightSavings = True
ButtonPreference = 0
LockParentalLevel = 0
WlanAdhocChannel = 0
WlanPowerSave = False
EncryptSave = True
BypassOSKWithKeyboard = False
PSPModel = 1
proAdhocServer = localhost
MacAddress = 74:69:8f:fd:45:22
PSPFirmwareVersion = 150
[Debugger]
DisasmWindowX = 500
DisasmWindowY = 200
DisasmWindowW = 773
DisasmWindowH = 700
ConsoleWindowX = 287
ConsoleWindowY = 475
FontWidth = 8
FontHeight = 12
DisplayStatusBar = True
ShowDeveloperMenu = False
GEWindowX = 322
GEWindowY = 278
GEWindowW = 768
GEWindowH = 686
ShowBottomTabTitles = True
SkipDeadbeefFilling = False
FuncHashMap = False
[Recent]
MaxRecent = 30
FileName0 = F:/ppsspp/ROMS/gvgnp.iso
FileName1 = F:/ppsspp/ROMS/牧场物语.iso
FileName2 = F:/ppsspp/ROMS/魔装机神2.iso
FileName3 = F:/ppsspp/ROMS/魔装机神1.iso
FileName4 = F:/ppsspp/ROMS/SEED.iso
FileName5 = F:/ppsspp/ROMS/GUNDAMAS.iso
FileName6 = F:/ppsspp/ROMS/粘土人世纪.iso
FileName7 = F:/ppsspp/ROMS/Battle Robot Damashii.ISO
FileName8 = F:/ppsspp/ROMS/ftpg.iso
[SpeedHacks]
PrescaleUV = False
DisableAlphaTest = False
[Upgrade]
UpgradeMessage = 
UpgradeVersion = 
DismissedVersion = 
[Network]
EnableWlan = False
EnableAdhocServer = False
[PinnedPaths]
[JIT]

**Comment by unknownbrackets** [comment]
Hmm, I see a couple options that might be worth changing.

图像设置 -> 停用较慢的渲染效果（提升速度） might make it faster.  If it does, that will help us find the problem.

图像设置 -> 多级纹理映射（Mipmap) may improve speed and graphics.  I recommend it.

系统设置 -> 快速内存访问（不稳定） may improve speed.  Sometimes there are bugs, but it gets better in each release.

图像设置 -> 减少缓存存取（提升速度） should likely be off for your CPU.  It may be faster.

Does changing 图像设置 -> 低品质样条函数/贝兹曲线（提升速度） to 低 change anything?  If not, leave it at 高 or 中.

Does the lag go away if you disable 图像设置 -> 纹理缩放?  Just wondering if it's related to that setting.

-[Unknown]

**Comment by leoxxx** [comment]
I'll try it.THX
BTW.
Can I delete the ini?
CAN I run the last version to create a new ini to resolve the issue?

**Comment by leoxxx** [comment]
I enable 图像设置 -> 停用较慢的渲染效果（提升速度][disable slower effects(speedup)] this option.
The issue be resolved.

**Comment by hrydgard** [comment]
Great, thanks for testing!
