### ISSUE TITLE
Persona 3 Portable crash on startup

### ISSUE THREAD

**Issue by zborowa** [hrydgard/ppsspp#8048]
I'm trying to start P3P for the first time and each time I get a glimps of onscreen controls and then PPSSPP crashes back to android screen. I don't know where the debug log is so if you need it please tell me where it is.
I have also tested Metal Gear solid Portable Ops and that works just fine.
I'm playing on Moto X Style (2015) Lollipop.

**Comment by unknownbrackets** [comment]
Duplicate of #8034.

-[Unknown]
