### ISSUE TITLE
CMake generates a Makefile that generates a PPSSPPSDL app bundle that is artificially restricted to OS X 10.11

### ISSUE THREAD

**Issue by angelXwind** [hrydgard/ppsspp#8049]
No idea what's causing CMake to do this — I believe it may have something to do with SDK 10.11?

The compiled binary still runs fine on OS X <10.11 (if you manually execute `PPSSPPSDL` inside the bundle), but the actual "PPSSPPSDL.app" will just throw this: 
![image](https://cloud.githubusercontent.com/assets/1980487/10413217/b2fff880-6f6e-11e5-9dc0-2083a64fafdf.png)

At first, I thought it was something wrong with the generated Info.plist, as that's generally the cause of such issues.

Upon further inspection of Info.plist, there's nothing there that should be artificially restricting it to 10.11. So... <_>

I'll look into the issue a bit more, but again — I'm rather inexperienced with CMake here... (and honestly the recent issues make me never want to ever use it ever again l o l)

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>English</string>
	<key>CFBundleExecutable</key>
	<string>PPSSPPSDL</string>
	<key>CFBundleGetInfoString</key>
	<string></string>
	<key>CFBundleIconFile</key>
	<string>ppsspp.icns</string>
	<key>CFBundleIdentifier</key>
	<string></string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleLongVersionString</key>
	<string></string>
	<key>CFBundleName</key>
	<string></string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string></string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string></string>
	<key>CSResourcesFileMapped</key>
	<true/>
	<key>LSRequiresCarbon</key>
	<true/>
	<key>NSHumanReadableCopyright</key>
	<string></string>
</dict>
</plist>
```

**Comment by hrydgard** [comment]
I wonder if a diff with the plist from an older build would show anything?

**Comment by angelXwind** [comment]
...Huh, that's interesting. The Info.plist from PPSSPP OS X 1.0 is the same as the one from the latest build (except for the icon name, but that's irrelevant).

...Now I'm confused. What's causing this, then? Some flag set in the PPSSPPSDL binary itself? If so, then why does PPSSPPSDL itself still execute and run fine on <10.11?

**Comment by angelXwind** [comment]
Fixed the issue — just run `export MACOSX_DEPLOYMENT_TARGET=10.7` before running CMake.

**Comment by hrydgard** [comment]
@angelXwind nice!
