### ISSUE TITLE
Hot Pixel USA DLC Not work

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#8050]
@hrydgard @unknownbrackets 
JPCSP fix it in 
https://github.com/jpcsp/jpcsp/commit/9009c2e538ded8076de82dab105cf50512bb7d89
and
https://github.com/jpcsp/jpcsp/commit/2e5617784f35f715f097dae550f1ea3290135111

Maybe PPSSPP also need same change ?
ppsspp-v1.1.0-36-g06cbc31-windows-amd64 log
https://gist.github.com/sum2012/1e1b1b284f49b098d007

**Comment by unknownbrackets** [comment]
We've implemented some changes a while back (I think after this issue, though) which handle uppercase more like it would be handled when Windows stores files on the memory stick.

Does this work now?

-[Unknown]

**Comment by benderscruffy01** [comment]
this can be closed
it is fixed
![hot](https://user-images.githubusercontent.com/48821663/54874667-d293b800-4e2a-11e9-9656-c951ac138edc.PNG)

**Comment by unknownbrackets** [comment]
Thanks for verifying.

-[Unknown]
