### ISSUE TITLE
Failed to make in xcode 7

### ISSUE THREAD

**Issue by xswqaz** [hrydgard/ppsspp#8056]
CodeSign error: code signing is required for product type 'Application' in SDK 'iOS 9.0'

Need to register Apple developer Program (99$)?

**Comment by hrydgard** [comment]
No, you don't, although it's set up like that right now.

This might help:
https://github.com/hrydgard/ppsspp/issues/7993#issuecomment-143441842

**Comment by xswqaz** [comment]
Success to fakesigning. But another error

No architectures to compile for (ARCHS=armv7, VALID_ARCHS=i386 x86_64).

**Comment by xswqaz** [comment]
e632b32be2e8d512eab0de3f2c68a8660201041e
