### ISSUE TITLE
Madoka Magica Portable: Softlock

### ISSUE THREAD

**Issue by Deyuil** [hrydgard/ppsspp#8058]
Trying to play this game, and am at the part of Madoka's route where she throws Sayaka's soul gem. The screen turns white after she throws it, and the game softlocks. I've seen this issue brought up a few times before, and yet no one has answered anywhere. Saw other questions about this game on here, so thought this would be the appropriate place to ask. Anyone have a fix to this?

**Comment by daniel229** [comment]
I think that is https://github.com/hrydgard/ppsspp/issues/6557 ,and I/O timing method set to Simulate UMD delays may help it.

**Comment by unknownbrackets** [comment]
Yes, looks like the same again.  Having two issues for one bug doesn't help, so closing.

-[Unknown]

**Comment by hrydgard** [comment]
Maybe it's time to default to Simulate UMD Delays now, and see if we can fix the resulting breakage?

**Comment by unknownbrackets** [comment]
Well, it can also cause noticeable delays sometimes... not sure.  Pretty sure all the different modes break different things.  I'm not sure what's best.  It makes me think we have other issues with io timing.

-[Unknown]

**Comment by Deyuil** [comment]
My emulator isn't allowing me to change I/O timing, it has it grey'd out.

**Comment by Deyuil** [comment]
No longer grey'd out, but still breakage after changing I/O Timing

**Comment by unknownbrackets** [comment]
I thought "Host" was the option that helped this game.

-[Unknown]
