### ISSUE TITLE
Please add UMD video player browser like as JPCSP

### ISSUE THREAD

**Issue by zminhquanz** [hrydgard/ppsspp#8060]
The next version of PPSSPP , please developer add this
![jpcsp12](https://cloud.githubusercontent.com/assets/11285640/10472935/8df58976-7250-11e5-8aad-06a807b7369e.png)

**Comment by LunaMoo** [comment]
Not exactly same, but you have an answer in #4902
~ devs are not interested in making video player out of PPSSPP.

**Comment by unknownbrackets** [comment]
Well, playing the little preview video might possibly be nice.  I think this is a duplicate of #2585.

-[Unknown]

**Comment by zminhquanz** [comment]
and some game not playing sound when show the game background by controller , keyboard
