### ISSUE TITLE
Request: Video Dumping

### ISSUE THREAD

**Issue by thecoreyburton** [hrydgard/ppsspp#8062]
I like to record high resolution gameplay footage regularly and I currently can't do that with the PSP. PPSSPP's internal resolution feature lets me make games look as beautiful as possible and I'd like to be able to save videos with those enhancements. A simple VFW dump-to-avi dialogue would do the trick, I could pick a lossless RGB codec (like Lagarith) and start dumping. Alternatively, FFMPEG would be a good solution too provided a similar solution could be achieved (lossless RGB colorspace dumping).

A lot of emulators have a video dumping option and it's something I really want to see in PPSSPP. 

Thank you for the consideration.

**Comment by unknownbrackets** [comment]
This is the same as #1800, so I'm closing this as a duplicate.

-[Unknown]
