### ISSUE TITLE
Crashing at opening-iOS 9.0.2

### ISSUE THREAD

**Issue by Juxen** [hrydgard/ppsspp#8068]
When you tap on ppsspp to open it soon closes on its own. Please fix it for iOS9-9.0.2. Older version did not work either. Thanks in advanced mr. Hrydgard

**Comment by thecoreyburton** [comment]
This is a problem present with a lot of emulators and software at the moment (like Retroarch, for example). I'd love to see this fixed too and opened a thread over at the Retroarch github, this was posted and may be relevant: https://twitter.com/saurik/status/654198997024796672

**Comment by hrydgard** [comment]
Already tracking this issue in #8066, the same thing was posted there. Will try it soon.
