### ISSUE TITLE
Sonic Rivals/Sonic Rivals 2 game "camera" problem

### ISSUE THREAD

**Issue by KingHamster678** [hrydgard/ppsspp#8069]
Hi everyone, i just recently got PPSSP 1.1.1 and putted alot of games here, with max performance settings
and its so fun XD no lag XD
However i have one problem with a game...
Thats Sonic Rivals and its sequel
I recently noticed that, unlike before, the camera that concentrates on my charcter doesnt work correctly (this didnt happened when i first loaded it)
http://ctrlv.in/648896 (click link for screenshot)
In the screenshot in the link you will notice that the camera does not point correctly to my character, which means that boss can only be seen in my gameplay
the same effect in this game also happens in Sonic Rivals 2
When am in a normal game (Race etc etc), i can only see half the body of my character
on some levels (Boss levels) i cant see my character, like in the screenshot i gave 
Any fixes or workarounds for this problem?
The game cant be playable on some moments (High "rolls", big jumps) due to this problem
I really enjoy this game and i want this to be fixed hope you guys will help me thanks in advanced

**Comment by hrydgard** [comment]
If you set Rendering Backend to Buffered Rendering, does that help? You might get other problems such as overbrightness though, this game is not friendly to emulators.

**Comment by KingHamster678** [comment]
It was at Buffered Rendering already, because if i set it to Non-buffered boom black screen

**Comment by daniel229** [comment]
Is "Disable slower effects" checked?then uncheck it.And savefiles provided may help,the gamesave is better.

**Comment by KingHamster678** [comment]
After disabling that option, the game gave me a black screen any more recommendations?

**Comment by daniel229** [comment]
Well,you can try the default setting.

**Comment by KingHamster678** [comment]
Can you give me the specific settings?

**Comment by daniel229** [comment]
Go to the System tab of PPSSPP's setting then find the option "Restore PPSSPP's settings to defoult".

**Comment by KingHamster678** [comment]
that will make my emulator very slow

**Comment by KingHamster678** [comment]
my gpu doesnt have opengl 2.0 thats why am getting mesa

**Comment by KingHamster678** [comment]
Also, this is a screen rotation bug (or something similar) so why change the render-related settings if it doesnt have anything related to this problem right?

**Comment by KingHamster678** [comment]
I think the emulator should implement a auto-adjustment setting. may help some games like this

**Comment by daniel229** [comment]
Does default setting help the "camera" problem?If you checking the speedup options or the hack options,it's faster though,may cause glitches.

**Comment by unknownbrackets** [comment]
> that will make my emulator very slow

If there were "better options" that were just **faster without bugs**, then why wouldn't they be the default ones?  You understand that some of the options may be things that break games and make them look like your screenshot, right?

-[Unknown]

**Comment by KingHamster678** [comment]
You dont understand, my laptop is not superb-ly fast my gpu is even so slow, then again i would remind you all that EVEN when i use the default settings, the bug still stays, let me remind you that this is not a render/graphical problem, this is a rotational/semi-visual problem

**Comment by unknownbrackets** [comment]
That's exactly why we're asking.  If it happens on default settings, that's important.  Especially if it's not happening for other users.  Again, it doesn't help to say, "trying on default settings is not an option because my computer is slow."  That's why I said settings **may** break games.

The only rotational code in PPSSPP rotates the entire display in a way that can't cause that.

Assuming your iso is clean (you can verify it's crc), if this is not happening to other users, then it is most likely a bug in your GPU driver.

Since you're using a laptop, I'll guess that it's Intel (please feel free to correct me with your actual specs.)  Intel cards, especially older ones, often fail to run OpenGL correctly.  You can try looking for driver updates, or switch to Direct3D in the settings.  Direct3D tends to work better on older Intel cards because it avoids Intel driver bugs.

-[Unknown]

**Comment by KingHamster678** [comment]
Actually,when i switched it to default settings, i turned out into black screen, but when i reconfigure it to my custom settings, everything is back to normal :/ (am using Direct3D9)
Yes your guess is correct, however, am using a modded driver of Intel GMA 3150
(Am actually having a problem trying to know my OpenGL tho, some say i got 1.1 some say i got 1.4 some say i got 2.0)
I even switched it to small display or small window resolution, but i really cant see my character still

**Comment by KingHamster678** [comment]
hope this gets fixed :P

**Comment by unknownbrackets** [comment]
Has this improved?  Does it happen in all backends - we now have Direct3D 11 and Vulkan on devices that support them.

-[Unknown]

**Comment by hrydgard** [comment]
I don't think this is still an issue, and if it is, it's only in non-buffered. Closing.
