### ISSUE TITLE
Shortcut actions bug

### ISSUE THREAD

**Issue by latot** [hrydgard/ppsspp#8070]
Hi ppl, this start when start using the state slots to test things in the game, the the game start auto-loading slots, i'm very bad explaning this so here a video:

http://www.mediafire.com/watch/n1nnnb2mqqz6emf/video.mp4

ppsspp config: http://www.mediafire.com/download/0gnqq33wtinmlrc/PSP.tar.gz

how you can see moving the cursor or alt+tab load the state.
i'm usings gentoo 64 and the sdl version

Log: https://gist.github.com/latot/58bdd8e113b3bd78f911

Thx.

**Comment by unknownbrackets** [comment]
Perhaps you set one of your shortcut keys to load a state?

-[Unknown]

**Comment by latot** [comment]
i don't press any key u.u

**Comment by latot** [comment]
it seems this is independent of the game, i use other and the effets continue, the game load the state when the cursor cross the screen with the top bar, in both sides, or when alt+tab, and when this happend i can resize the window but the screen don't is resized.

**Comment by latot** [comment]
okis, now i have clues, when we set the shortcut with some keys this happend, specify the keys ppsspp says this "kbd.??" and in the file all this keys are marked like this in controls.ini:

Load State = 1-0

when we use this shortcut for mistery reason the actions are executed when the cursor pass over the line betwen the screen and the top bar (that says "PPSSPP v1.1.1-4-g7924") or when we use alt+tab and avoid resize the screen when this happend, i test it with other other actions also the LoadState and was the same problem.

i use this key "{" (writed without modifier) the position is the "#" in this img 

https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Italian_Keyboard_layout.svg/2000px-Italian_Keyboard_layout.svg.png

but in my keyboard the "@" is the letter "ñ"
![captura de pantalla de 2015-10-16 11-56-25](https://cloud.githubusercontent.com/assets/10523095/10545048/5c00af3e-7405-11e5-8349-9aa2dee80d62.png)

**Comment by latot** [comment]
still some werid things resizing the windows (only to do the windows smaller)... for some reason says "No rewind save states available."

**Comment by unknownbrackets** [comment]
Hmm.  Maybe we should ignore NKCODE_UNKNOWN in mapping, or fix the mapping to include that key.  It could be that your window manager is delivering a keypress for certain resize or mouse events.

Can you try changing ext/native/base/PCMain.cpp, find this line (appears twice):

```c++
					key.keyCode = KeyMapRawSDLtoNative.find(k)->second;
```

Both times, change to:

```c++
					auto mapped = KeyMapRawSDLtoNative.find(k);
					if (mapped == KeyMapRawSDLtoNative.end() || mapped->second == NKCODE_UNKNOWN) {
						break;
					}
					key.keyCode = mapped->second;
```

Does that make this problem go away (after resetting the control mapping)?

-[Unknown]

**Comment by latot** [comment]
:O

it works! now i can't select now that unknow keys.
if its posible i prefer fix the map for a very simple reazon, exist a lot of keyboards!, and sadly this method will leave useless all other keys...

Thx!

**Comment by unknownbrackets** [comment]
Oh, resize problem continues?  So that means resize seems to trigger a keypress still?

What if you open the control mapping dialog, and then you try to map a key, like triangle, but instead of pressing a key, you resize the window?  What shows up?

I think we should just add the missing mappings to the array.  Instead of this:

```c++
					if (mapped == KeyMapRawSDLtoNative.end() || mapped->second == NKCODE_UNKNOWN) {
						break;
					}
```

You can add:

```c++
					if (mapped == KeyMapRawSDLtoNative.end() || mapped->second == NKCODE_UNKNOWN) {
						ILOG("Missing mapping for key=%d", k);
						break;
					}
```

And then tell me some key= values and what button you were actually pressing (ideally.)  Or even better, send a pull request with those added to ext/native/base/NKCodeFromSDL.h.

-[Unknown]

**Comment by latot** [comment]
Hi, well i don't know how to do this so i prefer ask (consider this like try and example), first i invertigate a little, and i found the sdl tables:
https://wiki.libsdl.org/SDL_Keycode
https://wiki.libsdl.org/SDLScancodeLookup
https://wiki.libsdl.org/SDLKeycodeLookup
https://wiki.libsdl.org/SDL_Scancode

the key printed in the log should be from this table:
https://wiki.libsdl.org/SDLKeycodeLookup

and there i'm lost, the keys like 123({) don't exist there D:
so i try adding this line only to test: 	(SDLK_KP_LEFTBRACE, NKCODE_PROG_GREEN)
but it continues without recognize the key.
and ¿what nkcode should be SDLK_KP_LEFTBRACE?

i prefer ask here how to do this.
Cya.

**Comment by unknownbrackets** [comment]
Okay so here's my theory: your keyboard layout is probably misconfigured.

For example, maybe you've specified that you have a German-style keyboard but you actually have a Slovak-style keyboard.  That could explain why the keycodes and scancodes are wrong.

I'm not an SDL / Linux desktop expert, though, so I'm not sure how exactly that is configured.  Or mayeb I'm just wrong.

As far as left brace, I think we only have `NKCODE_LEFT_BRACKET`.  On US style keyboards, Shift+NKCODE_LEFT_BRACKET is the left brace.  To handle keyboards which have a separate key, we should add a new NKCODE.  It should be at the end of the first list (next is 220), I believe.

-[Unknown]

**Comment by latot** [comment]
mm, i know my keyboard is right configured, or at least with the keys printed up, teory, multiples keyboards are used with differents countries but with differents letters and mixed codes, so when we try to match the codes its a mess.
I try this and the keys don't match with symbols on ppsspp.
D:

**Comment by unknownbrackets** [comment]
Hmm, see here:
https://forums.libsdl.org/viewtopic.php?t=8975&sid=16a0e60a27f020610620297b0ce4a1b7

It seems weird problems have occurred for others, although this one seems a bit different in a couple ways.  Don't see a solution, though...

-[Unknown]

**Comment by latot** [comment]
Hi, respect keys recognition,  are some nkcode to the application button?
sdl description
```
"Application" (the Application / Compose / Context Menu (Windows) key )
```

that button to open the submenu when we select files files

**Comment by unknownbrackets** [comment]
We intentionally skip that key, as it's often the way to get back to the operating system (for example, on Windows, the Windows key opens the start menu... on Mac OS X, the Apple key allows you to quit using Apple-Q.)

If you mean the context menu key ([the one that is like right clicking on Windows] (https://en.wikipedia.org/wiki/Menu_key)), we call that NKCODE_MENU.

-[Unknown]

**Comment by latot** [comment]
okidoki, tomorrow i'll send the pr.

Cya.

**Comment by latot** [comment]
what do you think inlcude this to the pr?

```
                    if (mapped == KeyMapRawSDLtoNative.end() || mapped->second == NKCODE_UNKNOWN) {
                                    if (mapped == KeyMapRawSDLtoNative.end()) {
                                               ILOG("Missing mapping for key=%d", k);
                                    }
                        break;
                    }
```

**Comment by unknownbrackets** [comment]
Well, it might be some setup may generate a lot of those, it could be a performance issue.  But yeah, it probably makes sense.

Definitely the current code there is wrong - using `->second` on a potentially invalid iterator should crash.

-[Unknown]

**Comment by latot** [comment]
mm, at least works to see the keys :D

**Comment by unknownbrackets** [comment]
SDLK_BACKSLASH doesn't work?

The width thing is crazy.  So you mean that if you size it to 300 wide, it sends a 300 button press?

-[Unknown]

**Comment by latot** [comment]
mm, the backslash works, but when we resize the windows to min, its executed that shortcut.

i think log will explain better thw width think:

moving windows:
```
I: PCMain.cpp:716: Key down: Missing mapping for key= 293
I: PCMain.cpp:716: Key down: Missing mapping for key= 305
I: PCMain.cpp:716: Key down: Missing mapping for key= 340
I: PCMain.cpp:716: Key down: Missing mapping for key= 355
I: PCMain.cpp:716: Key down: Missing mapping for key= 370
I: PCMain.cpp:716: Key down: Missing mapping for key= 382
I: PCMain.cpp:716: Key down: Missing mapping for key= 391
I: PCMain.cpp:716: Key down: Missing mapping for key= 396
I: PCMain.cpp:716: Key down: Missing mapping for key= 399
I: PCMain.cpp:716: Key down: Missing mapping for key= 401
I: PCMain.cpp:716: Key down: Missing mapping for key= 403
I: PCMain.cpp:716: Key down: Missing mapping for key= 405
I: PCMain.cpp:716: Key down: Missing mapping for key= 404
I: PCMain.cpp:716: Key down: Missing mapping for key= 403
I: PCMain.cpp:716: Key down: Missing mapping for key= 401
```

resize windows (select one corner and resize it)
```
I: PCMain.cpp:716: Key down: Missing mapping for key= 967
I: PCMain.cpp:716: Key down: Missing mapping for key= 967
I: PCMain.cpp:716: Key down: Missing mapping for key= 976
I: PCMain.cpp:716: Key down: Missing mapping for key= 976
I: PCMain.cpp:716: Key down: Missing mapping for key= 990
I: PCMain.cpp:716: Key down: Missing mapping for key= 990
I: PCMain.cpp:716: Key down: Missing mapping for key= 997
I: PCMain.cpp:716: Key down: Missing mapping for key= 997
I: PCMain.cpp:716: Key down: Missing mapping for key= 1001
I: PCMain.cpp:716: Key down: Missing mapping for key= 1001
I: PCMain.cpp:716: Key down: Missing mapping for key= 1007
I: PCMain.cpp:716: Key down: Missing mapping for key= 1007
I: PCMain.cpp:716: Key down: Missing mapping for key= 1017
I: PCMain.cpp:716: Key down: Missing mapping for key= 1017
I: PCMain.cpp:716: Key down: Missing mapping for key= 1027
I: PCMain.cpp:716: Key down: Missing mapping for key= 1027
I: PCMain.cpp:716: Key down: Missing mapping for key= 1037
I: PCMain.cpp:716: Key down: Missing mapping for key= 1037
I: PCMain.cpp:716: Key down: Missing mapping for key= 1042
I: PCMain.cpp:716: Key down: Missing mapping for key= 1042
I: PCMain.cpp:716: Key down: Missing mapping for key= 1045
I: PCMain.cpp:716: Key down: Missing mapping for key= 1045
```
from 967 width to 1045 (my screen max 1366)

**Comment by unknownbrackets** [comment]
Oh.  Darn, I wish I'd noticed that earlier, sorry.  See #8317.

-[Unknown]

**Comment by latot** [comment]
np :D
