### ISSUE TITLE
Resizing PPSSPP in OpenGL mode crashes it

### ISSUE THREAD

**Issue by GamerzHell9137** [hrydgard/ppsspp#8072]
When i try to resize PPSSPP during gameplay in OpenGL mode it crashes.
https://youtu.be/MX3Nh5EBo1A

**Comment by daniel229** [comment]
Looks fine in win7 64bit.You can find out which build broke it from http://buildbot.orphis.net/ppsspp/index.php?m=fulllist

**Comment by GamerzHell9137** [comment]
Cant right now thou. Im using Windows 10 x64 and GTX 960

**Comment by GamerzHell9137** [comment]
@hrydgard The issue is still there on the latest build.
Resizing the image on OpenGL crashes Nvidia Drivers.
http://puu.sh/lsajY/eb9d3ea8fb.png

**Comment by hrydgard** [comment]
@GamerzHell9137 It works perfectly on my nvidia and I've added all kinds of stuff to work around it. I just don't understand.

**Comment by GamerzHell9137** [comment]
@hrydgard Nor i, but i can confirm that its crashing.

**Comment by vsub** [comment]
Try disabling the post processing shader(if you are using one...I was using "Natural Colors" and it was one of the reason ppsspp to crash while resizing)and set the texture scaling to "Off"...it also makes ppsspp to crash but less often.

If nothing else works rigth click on My Computer=>Properties=>Advanced system settings=>Advanced=>Performance=>Settings=>Visual Effects=>disable "Show window contents while dragging"

I'm in Win7 x64 with GTX750TI...in the other issue I posted that this happens ONLY while using OGL with my nvidia card(it doesn't happen in D3D with OGL nor with HD4600 OGL\D3D)

**Comment by GamerzHell9137** [comment]
Issue still present in the latest build v1.1.1-340.

**Comment by GamerzHell9137** [comment]
The bug is still on the latest revision.
I guess this won't be fixed ever.

**Comment by daniel229** [comment]
I get it in windows 10
![01](https://cloud.githubusercontent.com/assets/3481559/11998938/6b2a2510-aaee-11e5-85bc-e542a5e3991d.png)

**Comment by daniel229** [comment]
Since https://github.com/hrydgard/ppsspp/pull/7942

**Comment by unknownbrackets** [comment]
A kernel exception is almost definitely a driver bug.  I'm still not getting it on Windows 7.

If you revert parts of that, what causes the crash?  Just make sure to revert the parts in GLES_GPU.cpp
 last.

My best suspects are either (a) somehow something in CheckGPUFeatures() is crashing it, since that's called on resize; or (b) glInvalidateFramebuffer is somehow becoming non-null and then crashing.

-[Unknown]

**Comment by daniel229** [comment]
Reverting (b)glInvalidateFramebuffer it works fine.

**Comment by unknownbrackets** [comment]
Does it help to add `fbo_unbind();` above the `glInvalidateFramebuffer(GL_FRAMEBUFFER, 2, attachments);` call?

If that doesn't help, can you try adding `Sleep(20);` above the call?  This will hurt FPS and responsiveness, but it might "cure" the resizing problem.  This is a quick way to "prove" if skipping the glInvalidateFramebuffer call during resize for one frame is likely to help.

-[Unknown]

**Comment by daniel229** [comment]
None of them helps.

**Comment by unknownbrackets** [comment]
What about a higher Sleep, like 100 (will be an awful game experience, heh.)

If not, then maybe it needs to render at least once before it becomes usable or something.  This sounds like probably a great bug report for NVIDIA.

-[Unknown]

**Comment by daniel229** [comment]
100 still not help.

**Comment by daniel229** [comment]
Has fixed in 361.43.

**Comment by daniel229** [comment]
but 361.43 may crash dx 9

**Comment by hrydgard** [comment]
Next thing I'm going to try is to pause the rendering thread entirely begin between WM_ENTERSIZEMOVE and WM_EXITSIZEMOVE. Will not be able to try it until after new years though.

**Comment by GamerzHell9137** [comment]
Thank @hrydgard 
Seems like the issue has been resolved(finally!)
Works fine now.
