### ISSUE TITLE
PPSSPP Tweak is not support to iOS 9.0.2

### ISSUE THREAD

**Issue by Monmichael** [hrydgard/ppsspp#8073]
Dear PPSSPP creator
Now iOS 9.0.2 have Jailbroken and PPSSPP (Dev working) not support for iOS 9.0.2.
I am waiting for PPSSPP update for iOS 9.0.2 
Thank a lot!

**Comment by hrydgard** [comment]
Already reported, see #8066 . Apple has been nasty this time.
