### ISSUE TITLE
PPSSPP cannot open

### ISSUE THREAD

**Issue by tumchinicious** [hrydgard/ppsspp#8079]
Hi,

this morning i try to JB my iphone 5C on iOS 9.0.2, and i trying to install PPSSPP and Retroarch. But when i open the app, it always close by itself.why did it happen?

awaiting for your help.
thanks

**Comment by HarukaMa** [comment]
#8066 .

2015-10-17 17:01 GMT+09:00 tumchinicious <notifications@github.com>:
