### ISSUE TITLE
build-x64.cmd for vs2015 fix

### ISSUE THREAD

**Issue by yxmline** [hrydgard/ppsspp#8081]
if not defined vs120comntools (
  echo "Visual Studio 2013 doesn't appear to be installed properly. Quitting."
  goto quit
  ) else (
    call "%vs120comntools%\vsvars32.bat" x86_amd64
)
Change
if not defined vs140comntools (
  echo "Visual Studio 2015 doesn't appear to be installed properly. Quitting."
  goto quit
  ) else (
    call "%vs140comntools%\ .. \ .. \VC\vcvarsall.bat"
)

ps:
Because github display bug
In the \ .. \ .. \ plus the space is actually no space

**Comment by hrydgard** [comment]
@yxmline thank you, fixed.
