### ISSUE TITLE
iOS 9.0.2 Not Working

### ISSUE THREAD

**Issue by 1921** [hrydgard/ppsspp#8085]
PPSSPP 1.1.1 not working for iOS 9.0.2 jailbroken iPod Touch (64GB, 6th Gen).
After install, when app is clicked, black screen shows for a second, then crashes.
Please fix PPSSPP for iOS 9, thank you very much!

**Comment by unknownbrackets** [comment]
Already known.  It's some incompatibility with the new jailbreak.  Closing as duplicate of #8066.

-[Unknown]
