### ISSUE TITLE
Emulator freezes while trying to load MGS:PW save game

### ISSUE THREAD

**Issue by SukharevAndrey** [hrydgard/ppsspp#8087]
In build v1.1.1-62-ge632b32 I'm trying to load MGS:PW save. PPSSPP should open PSP system loading screen but instead freezes (one should kill the process). Also loading MGS save states made in previous builds crashes the emulator.
All works fine in previous git build v1.1.1-48-gdb79e59.

**Comment by SukharevAndrey** [comment]
I'm not sure, but commit db79e596f05015419a4617a68e59d2a70f407f2c may be a reason for that.

**Comment by hrydgard** [comment]
What platform? Android, PC?

**Comment by SukharevAndrey** [comment]
PC, Windows 10 64-bit

**Comment by SukharevAndrey** [comment]
Checked GTA:VCS - save game loading screen works fine. The problem may be related only to MGS:PW.

**Comment by daniel229** [comment]
It's https://github.com/hrydgard/ppsspp/commit/60378dd59d3c72df9bb89db57540840b7da907a3

**Comment by unknownbrackets** [comment]
Where is it crashing?  Can you get a stack trace, or is it only when fast memory is on?

-[Unknown]

**Comment by daniel229** [comment]
Savestate looks fine for me,even from 1.01.

**Comment by unknownbrackets** [comment]
Well, if it's crashing due to an atrac change, it might matter what music is playing during your saved state.  But I don't see why the above should crash.... theoretically, it shouldn't do worse than play garbage.

A stack trace would really help.  I think there's a demo - does it replicate in that?  Does the save have to be any particular place?  Not sure if the demo can load saves.

-[Unknown]

**Comment by daniel229** [comment]
Do not need to load save,just hang at the title in a few seconds.

**Comment by unknownbrackets** [comment]
Strange, when resetting to 0?  Do these changes have any effect?

https://github.com/hrydgard/ppsspp/compare/hrydgard:master...unknownbrackets:atrac-parsing

-[Unknown]

**Comment by unknownbrackets** [comment]
Does f7fa0a06d484b4b7600277d2186f2f70ee22b723 help?

-[Unknown]

**Comment by SukharevAndrey** [comment]
Yeah, it seems to be fixed. Thank you.
