### ISSUE TITLE
Using PPSSPP with SwiftShader...

### ISSUE THREAD

**Issue by KingHamster678** [hrydgard/ppsspp#8088]
Hi hrydgard, i have a problem with PPSSPP again....
Its about using SwiftShader, a dll that can help D3D9 help render something...in otherwise, more performance (search about it in google)
When i use SwiftShader with PPSSPP, everything went black and even when i load something, nothing shows up but when i use the normal D3D9 everything is fine
So hrydgard, any suggestions or fixes?
If incase, can you please make PPSSPP be compatible with SwiftShader (not replacing the D3D9 compatibility itself, just make it work with this emulator)?
am sure the emulator will be much more closer to OpenGL when this happens
I know its hard but, hope you do this
Since the purpose of this dll is let you play high graphical games using D3D9

**Comment by hrydgard** [comment]
We don't do anything to block SwiftShader. I would argue that it is SwiftShader that needs to be fixed to be more compatible with PPSSPP, unless we are doing something particularly strange that can be easily fixed, which doesn't seem that likely. Either way, I don't think SwiftShader will be able to improve PPSSPP's performance, our shaders are fairly minimal.

**Comment by KingHamster678** [comment]
SwiftShader is not supported now
