### ISSUE TITLE
The Idolm@ster: Shiny Festa (NPJH50675) sound bad since v1.1.1-62-ge632b32

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#8089]
sound bad then no bgm.
last good:v1.1.1-48-gdb79e59
log: https://gist.github.com/sum2012/bad3525466ef44443adc

first bad:v1.1.1-62-ge632b32
log: https://gist.github.com/sum2012/195f8fbf42311c20124b

**Comment by sum2012** [comment]
@unknownbrackets this commit
https://github.com/unknownbrackets/ppsspp/commit/60378dd59d3c72df9bb89db57540840b7da907a3

**Comment by unknownbrackets** [comment]
Seems like there's an issue with resetting to 0.  See also #8087.  Any change from https://github.com/hrydgard/ppsspp/compare/hrydgard:master...unknownbrackets:atrac-parsing?

-[Unknown]

**Comment by sum2012** [comment]
No change.Log:
https://gist.github.com/sum2012/2ade9db27f6f914d93cd

**Comment by unknownbrackets** [comment]
Try f7fa0a06d484b4b7600277d2186f2f70ee22b723.

-[Unknown]

**Comment by sum2012** [comment]
You have commited into master.
Yes,v1.1.1-77-gf7fa0a0 fixed.Thanks
https://gist.github.com/sum2012/ed7584a88e38dfccea1c
