### ISSUE TITLE
Mahou Shoujo Nanoha As Portable The Gears of Destiny - Upscale Level - FPS low

### ISSUE THREAD

**Issue by n1dminhd** [hrydgard/ppsspp#8091]
My PC
- Intel Pentium G645 2,9GHZ
- Ram 4GB DRR3
- Nvidia GT 730 _ Latest Driver
- I shut the Upscale Level
- 7x native

![01](https://cloud.githubusercontent.com/assets/4449742/10633521/67276cc2-7815-11e5-9601-820582a323c7.jpg)
- I turned Upscale Level : 5
- 1x native

![02](https://cloud.githubusercontent.com/assets/4449742/10633163/29c89a1a-7813-11e5-94e2-31ec59bd358b.jpg)
- Ram up to 96 % and PC Lag
- But in battle normal

![05](https://cloud.githubusercontent.com/assets/4449742/10633390/8a4ea400-7814-11e5-9666-6279d6fdde19.jpg)
- I turned Upscale Level : 5
- 5x native
- Speed 100 %
- Dragon Ball Z Tenkaichi Tag Team 

![03](https://cloud.githubusercontent.com/assets/4449742/10633407/a3d9d75a-7814-11e5-8eea-7a431e2c62e9.jpg)
![04](https://cloud.githubusercontent.com/assets/4449742/10633406/a3d841e2-7814-11e5-9c0a-a9620ffea32f.jpg)
- Digimon World Re - Digitize (Eng Patch)

![06](https://cloud.githubusercontent.com/assets/4449742/10633448/f9f5b29e-7814-11e5-9418-24bcc2945cef.jpg)
![07](https://cloud.githubusercontent.com/assets/4449742/10633449/f9fb2710-7814-11e5-9aab-c6dd2f4093f2.jpg)

**Comment by 0990251748** [comment]
zaras1122@gmail.com

**Comment by unknownbrackets** [comment]
Certain areas and certain effects can take a lot of CPU for upscale at 5.  Try a lower level.

-[Unknown]

**Comment by n1dminhd** [comment]
- But Ram usage 96%
- And Cpu usage 100 %
- 3xnative
- Upscale Level : 2
- Fps unstable : 14/60; 48/60; 60/60; 65/60
- Before, I use intel hd 3000 speed stability (3xnative + Upscale Level auto), but Nvidia gt 730 fps low, ppsspp not compatible nvidia
- But Other games : 5xnative (or 3xnative) + Upscale Level  5  = fps 60/60
including God of war (80-100% speed)
Sorry I bag eng

**Comment by n1dminhd** [comment]
someone checked help me, Please !

**Comment by unknownbrackets** [comment]
Your processor is only 2 core, and xBRZ is a heavy operation.  Like I said, sometimes games will do things that requires a lot of scaling.

We've tried many things to optimize it, but some games just abuse textures in ways that are hard on emulation and hard on texture scaling.  PPSSPP generally works very well with NVIDIA, but texture scaling has a lot more to do with CPU power than GPU.

I'm surprised 2x still performs so poorly, though.  It may be that you're swapping, but I wouldn't expect us to need so much RAM in that case.  How much RAM is PPSSPP using according to the Task Manager?

-[Unknown]

**Comment by n1dminhd** [comment]
Task Manager : 90mb-150mb
But
Gatgets : 99-100%
And
PC is very lag, expression of ram is full, very strange

**Comment by unknownbrackets** [comment]
Okay, this probably means something external is using that RAM, maybe somehow based on PPSSPP?  I'm not sure what's happening.

You might try examining the running processes, quitting all programs, and trying again.  Maybe run an anti-spyware scan.  If you run task manager is admin mode, does it show ANY process using a ton of RAM?

If it doesn't, I guess it might be your video driver or something?  Seems weird.  Might try updating it?

-[Unknown]

**Comment by n1dminhd** [comment]
I just installed new windows few today
This situation has persisted since before installing new windows
I used ppsspp to play more games and totally normal (DB Shin Budokai 2, Phantasy Star Portable, ...)
Driver Nvidia : Always the latest
I will try again

**Comment by n1dminhd** [comment]
I tried again
- Ram Full but no public process consumes excessive
I tried both the GOW God of sparta
- Ram never exceed 24%
I tried to turn off or turn on kis 2015, are the same:
- Mahou Shoujo Full ram
- GOW very little ram (great)

**Comment by n1dminhd** [comment]
At first I thought that by Nvidia Driver
So I tried the older Driver, But no improvement
So after reinstalling win, I always use the latest Driver

**Comment by daniel229** [comment]
it seems memmory leak here with xbrz 3x and up.over 1GB ram take.

**Comment by daniel229** [comment]
xbrz off 594MB vram
2x 1270MB
3x over 2GB

**Comment by unknownbrackets** [comment]
Hmm, sounds to me like it's just scaling/caching a LOT of textures.  A likely story is that it's using one large texture, but offsetting it.

To explain, a texture normally looks like this:

```
ABCD
EFGH
IJKL
MNOP
```

If I want to draw the "ABEF" part, I can just use part of that texture.  But if I want to draw the "CDGH" part, I have two options.  I could use the above texture (the most normal thing to do), or I could point the texture differently:

```
CDEF
GHIJ
KLMN
OPXX
```

Here, the "XX" are garbage - I don't care what they are.  By moving forward two pixels, I've essentially shifted the part of the texture I care about left.

Right now, we don't detect such subsetting well for memory-only textures.  Maybe we should, but it could add danger to the texture cache...

Anyway, if you click "Step tex" a few times, do any of the texture addresses look very similar to each other?  With only the last 3 digits differing.

-[Unknown]

**Comment by daniel229** [comment]
No any only the last 3 digits differing.just saw there are two textures are the same.

**Comment by unknownbrackets** [comment]
Well, if the address is exactly the same, it should use the same texture, unless the clut hash is different.  Is the texture format using a clut?  If it's CLUT4/etc. then it is, otherwise it isn't.

Maybe it's using a bunch of different palettes just to make things crazy...

-[Unknown]

**Comment by daniel229** [comment]
Tex format	CLUT8

**Comment by unknownbrackets** [comment]
Is hardware texture scaling (available in Vulkan) effective for this game?  I think we have other related issues, so considering closing this.

-[Unknown]

**Comment by Gamemulatorer** [comment]
Backend **opengl**
Rendering resolution **5x**
Display resolution **native**
Upscale type **xBRZ**
Upscale level **3x**
![Screenshot_2021-11-09-15-51-00-015_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/140884052-6909dc23-2179-432f-91ce-ba9b5a34d440.jpg)

**Comment by hrydgard** [comment]
Closing this old performance issue, unlikely to see any specific work done.
