### ISSUE TITLE
Combo key scroll down bug

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#8097]
@hrydgard 
In windows,if you make width short,
you cannot scroll down 
@xiushudongfang said to me that if remove title,then solve this problem,but he doesn't want to do so,
Hope @hrydgard have idea to solve,thanks
![1](https://cloud.githubusercontent.com/assets/2177532/10710680/b21fa3ba-7a96-11e5-820e-73ad4616abc7.png)

**Comment by xiushudongfang** [comment]
The same bug also occurs on Android device。

**Comment by hrydgard** [comment]
I'll take a look soon.

**Comment by xiushudongfang** [comment]
Thanks a lot.
