### ISSUE TITLE
lack detail

### ISSUE THREAD

**Issue by n1dminhd** [hrydgard/ppsspp#8099]
I use PPSSPP v1.1.1-74 x64
GPU Nvidia

PPSSPP-v0.9.9.1 : top
PPSSPP-v1.1.1-74 : bottom

- Normal
![uljs00385_00000](https://cloud.githubusercontent.com/assets/4449742/10711224/071876a0-7a9f-11e5-9b3a-582b6ecfb9b8.jpg)
- No eye
![uljs00385_00001](https://cloud.githubusercontent.com/assets/4449742/10711228/21f594a8-7a9f-11e5-9e87-a7b755e93f42.jpg)

-Normal
![ulus10455_00000](https://cloud.githubusercontent.com/assets/4449742/10711270/0add27d0-7aa0-11e5-98fc-c694c44c77f5.jpg)

-No icon
![ulus10455_00001](https://cloud.githubusercontent.com/assets/4449742/10711273/1a9a5508-7aa0-11e5-9ec0-751c398642f9.jpg)

**Comment by sum2012** [comment]
What is the first picture of game id name ? (eg ULJM05940)

**Comment by daniel229** [comment]
Both broke by https://github.com/hrydgard/ppsspp/commit/87f45ed307aab80a10ea91d12e311b4bd9051bdc , same as https://github.com/hrydgard/ppsspp/issues/8071

**Comment by daniel229** [comment]
Still happens in v1.1.1-85-gb86394d .

**Comment by hrydgard** [comment]
@daniel229  thanks for testing, will look into it some more

**Comment by unknownbrackets** [comment]
Does 06f2c7f fix this?

-[Unknown]

**Comment by daniel229** [comment]
Yeah.

**Comment by n1dminhd** [comment]
@sum2012 id name : ULJS00385
![menu_00000](https://cloud.githubusercontent.com/assets/4449742/10714160/c2d770f4-7b11-11e5-84fe-2749a04ea962.jpg)

**Comment by n1dminhd** [comment]
it still bugs, not close
![uljs00385_00001](https://cloud.githubusercontent.com/assets/4449742/10714167/923d6a56-7b12-11e5-94c5-6997ff0a0408.jpg)

**Comment by unknownbrackets** [comment]
Was this also caused by the same commit?

-[Unknown]

**Comment by n1dminhd** [comment]
@unknownbrackets 
I do not understand
What "the same commit" ?
Sorry, I bad Eng !

**Comment by unknownbrackets** [comment]
Did it work in v1.1.1-4-g7924ccf?  Was it broken in v1.1.1-13-g09cc80f?

If yes, the same commits are the cause of the problem.

-[Unknown]

**Comment by n1dminhd** [comment]
v1.1.1-4-g7924ccf
v1.1.1-13-g09cc80f
Normal
![default 4](https://cloud.githubusercontent.com/assets/4449742/10714244/90154622-7b17-11e5-9233-d8e61aa3f84a.jpg)
![uljs00385_00002](https://cloud.githubusercontent.com/assets/4449742/10714249/9c2dbbb0-7b17-11e5-9ef1-9f11570dcbd5.jpg)

**Comment by unknownbrackets** [comment]
Okay, so it's something that was broken after those versions.

What version was the first one it stopped working in?  v1.1.1-94-g6b905e8 does not work.  Did v1.1.1-87-g488aec1 also not work?  I want to find which version caused the problem of the missing faces at the top.

-[Unknown]

**Comment by daniel229** [comment]
This https://github.com/hrydgard/ppsspp/commit/838e53f482d911231d7cee6f5e5070902f051672

**Comment by unknownbrackets** [comment]
Ah, okay, c41b981333a9d7fb5da74fd39c306a2b8f2d0918 will probably fix.  Sorry.

-[Unknown]

**Comment by daniel229** [comment]
Yeah.

**Comment by n1dminhd** [comment]
@unknownbrackets 
I try again
v1.1.1-4-g7924ccf: 
- opengl : normal
- direc3d9 : normal
v1.1.1-13-g09cc80f: 
- opengl : missing faces
- direc3d9 : normal

**Comment by daniel229** [comment]
@n1dminhd 
Try the latest build v1.1.1-96-gc41b981

**Comment by n1dminhd** [comment]
@unknownbrackets 
@daniel229 
v1.1.1-96-gc41b981 play ok
Thanks !
