### ISSUE TITLE
Yu-Gi-Oh! GX Tag Force 6 crash in-game in android

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#8104]
@hrydgard  @unknownbrackets 
Delete game save
Run the game
Make new save
Start main story
crash

good v0.9.8-594-gfe696dc
bad v0.9.8-826-g4873c5c
git bisect result:
https://github.com/hrydgard/ppsspp/commit/80cc9d8c0ee20a5c98ae59b0be4c62cf97ad45ef
#6037

last time fixed Symbian 
Now need fix android

**Comment by unknownbrackets** [comment]
Symbian was allocating a different and wrong way.

Does this work with fast memory off and/or jit off?

-[Unknown]

**Comment by sum2012** [comment]
fast memory off and jit off  not work

**Comment by sum2012** [comment]
v1.1.1-87-g488aec1 android crash log 
https://gist.github.com/sum2012/953d66297da89e2ffd83

**Comment by sum2012** [comment]
v1.1.1-457-gda65116 same crash

**Comment by unknownbrackets** [comment]
> RAM at 0xda204000 (mirror at 0 @ 0xd4104000, uncached @ 0xd4104000)
> Fatal signal 11 (SIGSEGV), code 1, fault addr 0xcc11b543 in tid 18063 (AndroidRender)

Hmm.  0xcc is less than 0xda.  The difference is 0x0E0E8ABD.  I guess this could mean an address of 0x8E0E8ABD, but that's definitely an invalid address.  And it's happening inside libc.  Does the logcat give you any sort of trace at all?

-[Unknown]

**Comment by sum2012** [comment]
https://gist.github.com/sum2012/104368a21211683557ba

**Comment by sum2012** [comment]
v1.1.1-458-g29eea47 
log (updated):
https://gist.github.com/sum2012/eef1f0f16de965bb2191

**Comment by unknownbrackets** [comment]
Oh, sceIoIoctl.  That's very interesting.

So let's try a few things.  First change this, in Core/HLE/sceIo.cpp:

```c++
	u32 error;
	FileNode *f = __IoGetFd(id, error);
	if (error) {
		ERROR_LOG(SCEIO, "%08x=sceIoIoctl id: %08x, cmd %08x, bad file", error, id, cmd);
		return error;
	}
```

To:

```c++
	u32 error;
	FileNode *f = __IoGetFd(id, error);
	if (error || !f) {
		ERROR_LOG(SCEIO, "%08x=sceIoIoctl id: %08x, cmd %08x, bad file", error, id, cmd);
		return error;
	}
	(void)hleLogWarning(SCEIO, 0, "in __IoIoctl");
```

Depending on what cmd is (second param), it's likely crashing inside one of the cases.  Most of them already log.  My top suspects are the PGD-related stuff and the catch-all default at the bottom.

-[Unknown]

**Comment by sum2012** [comment]
Still crash
https://gist.github.com/sum2012/af56d5dce7f6261e3e6b

**Comment by unknownbrackets** [comment]
Well, that address is invalid but probably was misdetected.  I've included a fix for the validation in #8317.  But, it may be an armjit bug that's even getting the wrong parameter value in the first place?

-[Unknown]

**Comment by sum2012** [comment]
When merge #8137 ,I will try again revert BKPTs change

**Comment by sum2012** [comment]
Good news,no crash when revert BKPTs change
Closing
