### ISSUE TITLE
Gang of London  : Out Game

### ISSUE THREAD

**Issue by n1dminhd** [hrydgard/ppsspp#8108]
Windows 7 64 bit
PPSSPP v1.1.1-103-g05687e6
often out when to
![ucus98617_00001](https://cloud.githubusercontent.com/assets/4449742/10725545/4ba93b7c-7bff-11e5-9871-211d9636c3f2.jpg)

sometimes in a game, load save - out game
sometimes in a game, new game - not out, playable

**Comment by sum2012** [comment]
same game as #7239
