### ISSUE TITLE
The Red Star - In game but black screen

### ISSUE THREAD

**Issue by n1dminhd** [hrydgard/ppsspp#8110]
Windows 7 64 bit
PPSSPP v1.1.1-103-g05687e6
In game, Select your character --> but black sreen
![npeh00024_00000](https://cloud.githubusercontent.com/assets/4449742/10726033/cf2b5d2e-7c02-11e5-9bc4-020a2d5d141d.jpg)
![npeh00024_00001](https://cloud.githubusercontent.com/assets/4449742/10726032/cf29727a-7c02-11e5-8057-f7691c008210.jpg)
![npeh00024_00002](https://cloud.githubusercontent.com/assets/4449742/10726034/cf2f5e10-7c02-11e5-83a6-96994275e501.jpg)
![npeh00024_00003](https://cloud.githubusercontent.com/assets/4449742/10726035/cf316002-7c02-11e5-922c-db5c04bfae2b.jpg)

**Comment by sum2012** [comment]
From the log,black sceen's reason (maybe?) is that failed to allocate memory
info log:
https://gist.github.com/sum2012/ec1499216a96c32c2f2f

debug log: https://drive.google.com/file/d/0B3OaSdeV0L8kVTkySU1salctb0k/view?usp=sharing

jpcsp old version work 
https://gist.github.com/sum2012/e69f82c66523a24c0aff

easy compare two log:
PPSSPP heap size: 52740 KB
JPCSP heap size:19972 KB

**Comment by unknownbrackets** [comment]
It would be better to compare to JpcspTrace.  But, it ultimately tries to allocate 03382500 when only 03382400 are available.  So close but so far.  It might be something is under or over allocating by 0x100 bytes, or is reporting its usage incorrectly.

This didn't work in 1.0.1 or anything, right?

-[Unknown]

**Comment by sum2012** [comment]
v1.0.1-24-g2cdb5a3 also not work

**Comment by n1dminhd** [comment]
I fear, is that it never worked in any version yet so far
Before very long, I have reported on ppsspp forum, but it has not been repaired

**Comment by sum2012** [comment]
@unknownbrackets how to compare real psp ?
Log what in JPCSPTrace ?

**Comment by unknownbrackets** [comment]
Log sceKernelCreateFpl 0xC07BB470.

-[Unknown]

**Comment by sum2012** [comment]
unlucky cannot log (jpcsptrace bug),

**Comment by sum2012** [comment]
Just a note jpcsp updated jpcsptrace 
But unlucky still cannot log 
https://github.com/jpcsp/jpcsp/commit/c2f7416b76746d1a035f7b89655112cc2b32241e

**Comment by sum2012** [comment]
@unknownbrackets Fixed jpcsptrace 
Log: https://gist.github.com/sum2012/c0c4e8925d678b5f0876

**Comment by unknownbrackets** [comment]
Can you give me a debug log when running with the PSP-1000 setting?

-[Unknown]

**Comment by sum2012** [comment]
This is PSP-1000 log:
info log:
https://gist.github.com/sum2012/9245497801ddd2758087
debug log:
https://drive.google.com/file/d/0B3OaSdeV0L8kdzAxLW1BMVk2RGM/view?usp=sharing

**Comment by unknownbrackets** [comment]
We are close.  We allow it to allocate just 0x100 too much.  It doesn't like like the allocation errors are related after all, but maybe it's broken due to the 0x100 off... seems unlikely.

-[Unknown]

**Comment by sum2012** [comment]
v1.2.2-821-geac1848 same problem
debug log:
https://drive.google.com/file/d/0B3OaSdeV0L8kV3Q3d0w5ejFqZzQ/view?usp=sharing

soft gpu also don't work

**Comment by LunaMoo** [comment]
What happens is the game writes a perfectly normal projection matrix with 16 elements, which would display graphics just fine, however later on right before vertices it get's additional projection matrix data of -0.0 value, eventually ending with whole projection matrix filled with (-0.0)'s.

 So there are two possibilities:
 - all projection matrix data after count 16 should be ignored and game expecting that stores some 1.0f there,
 - or it is a messup with memory allocation and game stores some floats in wrong place in memory.

 First possibility makes into potentially easy fix:
![npuh10040_00003](https://cloud.githubusercontent.com/assets/5485237/20709103/981bb920-b633-11e6-81f7-3b9b76018165.jpg)

 It also seems correct as Execute_ProjMtxNum already does that, Execute_ProjMtxData is our problem here, unsure how to pass the counter between those two:|.

**Comment by hrydgard** [comment]
Oh, that's really interesting. Maybe we should simply ignore writes if the proj mtx counter is above 15. In that case, something like this should work:

    int num = gstate.projmtxnum & 0x1F;    // NOTE: Changed from 0xF to catch overflows
    u32 newVal = op << 8;
    if (num < 0x10 && newVal != ((const u32 *)gstate.projMatrix)[num]) {
        ....
    }
    num++;		
    gstate.projmtxnum = (GE_CMD_PROJMATRIXNUMBER << 24) | (num & 0x1F);  // changed here too

Which would be a cleaner solution.

Presumably this would then also apply to the other matrices...  This needs testing on hardware I guess.

Nice digging.

**Comment by LunaMoo** [comment]
Looks nice, but unfortunately doesn't work by same reason I couldn't use it ~ num get's reset to 0, so all that unwanted data still get's used.

**Comment by hrydgard** [comment]
Hm, what is it that resets the counter to 0? As long as it's not that the game does another GE_CMD_PROJMATRIXNUMBER in between, this should be solvable. 

Oh, will probably need to change this too (note 1F), in Execute_ProjMtxNum:

	gstate.projmtxnum = (GE_CMD_PROJMATRIXNUMBER << 24) | ((op + count) & 0x1F);

**Comment by LunaMoo** [comment]
Aw why I couldn't see that^^, yeah of course it ends with 0x10 so we get 0. But blah even with that it only affects first projection matrix, so only character which is drawn first is visible.

**Comment by hrydgard** [comment]
Hm, ok. So maybe once the num overflows, no writes should be allowed at all. 

So, in addition to the previous changes, change in Execute_ProjMtxData:

            ...
        }
        num++;
        if (num <= 16)
            gstate.projmtxnum = (GE_CMD_PROJMATRIXNUMBER << 24) | (num & 0xF);
    }

That should prevent it from incrementing it further once it hits 16, and it should stay unwritable until the next proper GE_CMD_PROJMATRIXNUMBER...

**Comment by LunaMoo** [comment]
Yup works great. Should I open PR with this or it's too risky? Didn't really saw any problems, but again in most games that code will not even run.
Maybe also adding other matrices? ~ Through as far as this issue goes projection is all this game bugs out.

**Comment by hrydgard** [comment]
Seems clear that either this is how the hardware behaves, or the game is just buggy. I have a hard time seeing how it could break other games, unless there are games that rely on loading twice and then counts on the SECOND matrix to be the valid one ... But in that case, assuming there's not another emulation bug that break the matrices, Red Star shouldn't work.

Please make a pull request with this for now, so it's easy to play around with.

**Comment by Orphis** [comment]
It should be easy to make a test program and run it on the hardware to check the correct behavior too.
