### ISSUE TITLE
tactics ogre new issues on new dev version

### ISSUE THREAD

**Issue by ivyking007** [hrydgard/ppsspp#8113]
the fps and speed go down and then black screen freezing when ingame

**Comment by unknownbrackets** [comment]
Not very descriptive.  What device, and what is the first git build it started happening in, and the last one it didn't happen in?  This is with the exact same settings, right?

-[Unknown]

**Comment by ivyking007** [comment]
default setting , win 7 64bit , v1.1.1-103-g05687e6	 , both happening on this version

**Comment by ivyking007** [comment]
when on option to choose next step and setting the fps turn to 25 to 29 and then speed 50%  , after saving duke name the team it got black screen and freezing

**Comment by unknownbrackets** [comment]
What is the **first** git build it started happening in, and the **last one** it didn't happen in?

-[Unknown]

**Comment by sum2012** [comment]
@ivyking007 
Try this modify version https://drive.google.com/file/d/0B3OaSdeV0L8kR0Ffb2l6MDM1V2c/view?usp=sharing
I try turn off GPU_SUPPORTS_ANY_FRAMEBUFFER_FETCH

**Comment by ivyking007** [comment]
@sum2012 
thanks sum2012 i will try this first before the bugs has been fixed

**Comment by sum2012** [comment]
@ivyking007 do you mean my version fixed ?

**Comment by ivyking007** [comment]
@sum2012 

yes , the problem was fixed on your ppsspp version

**Comment by hrydgard** [comment]
Ok, I think I'll just turn that feature off for everyone soon...

**Comment by hrydgard** [comment]
Just did that. So closing this issue now.
