### ISSUE TITLE
Windows touch input slowdown

### ISSUE THREAD

**Issue by supadupaplex** [hrydgard/ppsspp#8115]
When on screen controls enabled if any button or stick is pressed for about 3-4 seconds then huge slowdown appears. As soon as touch controls are released then slowdown disappears.
With external gamepad (Dualshock 3) nothing like that happens.

Machine: Dell Venue 8 pro; OS: Windows 8.1; PPSSPP v1.1.1;

Before:
![24](https://cloud.githubusercontent.com/assets/15338328/10752045/89c3aeb2-7ca7-11e5-9448-58091ba3fbf1.png)
![26](https://cloud.githubusercontent.com/assets/15338328/10752051/9998985c-7ca7-11e5-9ed8-17ddee43125d.png)
After pressing L button:
![25](https://cloud.githubusercontent.com/assets/15338328/10752049/94186e98-7ca7-11e5-950d-f64056027ba8.png)
![27](https://cloud.githubusercontent.com/assets/15338328/10752054/a02c05dc-7ca7-11e5-89e1-25c7e0c7b74f.png)

**Comment by unknownbrackets** [comment]
Unfortunately, I don't think the code has ever been debugged on a device with actual touch controls.  I suspect it might be some sort of event spam issue, and debouncing may help, but not sure.

Are you able to install Visual Studio Community (it's free) and debug?

-[Unknown]

**Comment by supadupaplex** [comment]
Hello, unknownbrackets. OK, I will try to install Visual Studio and run debug on this week.
Also I did further investigation on this problem and found out, that slowdown appears even if touch controls are disabled and I press on areas, that not belong to ppsspp window. When slowdown appears CPU load decreases from 30% to 15-17%.

**Comment by unknownbrackets** [comment]
Did you have any luck at all?  Need some help?

-[Unknown]

**Comment by supadupaplex** [comment]
Hello. Sorry for big delay. I tried to debug it few times, I got some info, but don't know if this can help.
I tried to run source code in Visual Studio 2015. It looks like mess and runs with ~5 fps, so it's hard to track down slowdown, when whole program becomes an one huge slowdown. The only thing I tried was holding down touchscreen and after a while pressing break hotkey. It often brought me to line, shown on screenshot, but I don't know, if that the case (rather not, because comment is saying, that this code processes gamepad input).
I also tried running normal ppsspp in debug mode, results are in screenshots.
The only easy way to reduce the issue I found is setting process priority to high. Issue is reducing a lot, but it still costs ~3fps to press onscreen buttons.
I think that is all I can get. So if you think, that info has no use, you can close the issue, because that's unlikely, that I can get more, because I have no experience of debugging huge projects like that.

![d1](https://cloud.githubusercontent.com/assets/15338328/12007529/92fb4a1e-ac2a-11e5-825b-e120820c2dd8.png)
Odd
![d2](https://cloud.githubusercontent.com/assets/15338328/12007531/930340e8-ac2a-11e5-8011-056a4be005de.png)
I don't know why it so corrupted in VS
![d4](https://cloud.githubusercontent.com/assets/15338328/12007527/92fb18c8-ac2a-11e5-9ab9-d489ea142d51.png)
That line of code
![dt1r](https://cloud.githubusercontent.com/assets/15338328/12007530/92fd2fb4-ac2a-11e5-834a-7dd23880c52d.png)
Normal ppsspp before using touchscreen
![dt1p](https://cloud.githubusercontent.com/assets/15338328/12007570/24e42724-ac2c-11e5-8e06-cba515f4f9ee.png)
Normal ppsspp after using touchscreen
![dt2r](https://cloud.githubusercontent.com/assets/15338328/12007535/934a6130-ac2a-11e5-97df-b6f95f6f7e8c.png)
Normal ppsspp before using touchscreen
![dt2p](https://cloud.githubusercontent.com/assets/15338328/12007534/93498968-ac2a-11e5-97d8-81389845ebfa.png)
Normal ppsspp after using touchscreen
![dt3r](https://cloud.githubusercontent.com/assets/15338328/12007532/9325f926-ac2a-11e5-8b9a-bb1e85db25fb.png)
Normal ppsspp before using touchscreen
![dt3p](https://cloud.githubusercontent.com/assets/15338328/12007533/932b8828-ac2a-11e5-889f-d91841a03a85.png)
Normal ppsspp after using touchscreen

**Comment by unknownbrackets** [comment]
About the slowness: try setting that dropdown near the top that says "Debug" to "Release".  Debug is a lot slower than Release because it enables a lot of debugging features.  TBH, I rarely use it - I usually mark individual files as debug (by putting `#pragma optimize("", off)` at the top), because 100% debug is just so slow.

Anyway, now that you have it compiling, some ideas:

Open `Windows/TouchInputHandler.cpp`, and look for this line:

```c++
void TouchInputHandler::handleTouchEvent(HWND hWnd, UINT message, WPARAM wParam, LPARAM lParam)
```

This is where it handles touches.  So we can time this, and try to figure out if it's slow here.  Make that area look like this:

```c++
TouchInputHandler::~TouchInputHandler()
{
}

#include "base/timeutil.h"

void TouchInputHandler::handleTouchEvent(HWND hWnd, UINT message, WPARAM wParam, LPARAM lParam)
{
	double st = real_time_now();
	if (hasTouch()){
		UINT inputCount = LOWORD(wParam);
```

And then at the bottom of the function:

```c++
			// GetLastError() and error handling.
		}
		delete [] inputs;
	}

	double et = real_time_now();
	NOTICE_LOG(HLE, "Processing touches took %fms", (et - st) * 1000.0f);
}

// from http://msdn.microsoft.com/en-us/library/ms812373.aspx
// disable the press and hold gesture for the given window
void TouchInputHandler::disablePressAndHold(HWND hWnd)
{
```

Next, when you start PPSSPP, select "Debug" -> "Log Console" (second to last thing.)  When you touch, it should start logging numbers on the screen indicating how long processing the touches is taking.

If it looks like this:

Processing touches took 0.1234ms
Processing touches took 0.2534ms
Processing touches took 0.0834ms

Then we're probably okay.  The warning signs would be if: (a) there were a TON of these logged every time you touch, or (b) the numbers are >= 1.000ms.

That's probably the most likely problem.  If they are fine, then there could be other issues.

-[Unknown]

**Comment by supadupaplex** [comment]
Hello again. I tried out your new debug lines. Results are below in screenshots,
I also found out, that if I touch input is disabled and I press somewhere else (second screenshot) ppsspp still slows down. In that situation TouchInputHandler is not called at all.
![before](https://cloud.githubusercontent.com/assets/15338328/12009589/c88d5fb6-aca0-11e5-92bf-4479ddd6dbfb.png)
Before touching anything
![outofwindow](https://cloud.githubusercontent.com/assets/15338328/12009574/c898fd4a-ac9f-11e5-99a5-197529a8530a.png)
After touching space in between of ppsspp windows
![tw_before](https://cloud.githubusercontent.com/assets/15338328/12009575/c8d7fe32-ac9f-11e5-8522-50bd41da2175.png)
Touching ppsspp window before slowdown
![tw_after](https://cloud.githubusercontent.com/assets/15338328/12009576/c8d97c58-ac9f-11e5-871a-6ce84d56740c.png)
Touching ppsspp window after slowdown

**Comment by unknownbrackets** [comment]
Hmm.  I'm worried this might be some driver thing or something now.  The thing that's going up is processing of the graphics ("DL procesing time".)

Are you using multithreaded?  Can you turn it off just to make sure results are the same, if so?

If it keeps saying the sceGe* is the slowest syscall and DL processing time keeps being above 16ms, it seems like rendering is getting a hit when you touch the screen.  If you keep touching and moving your finger around, does that still happen?

Have you tried other applications (even video players, I guess) to see if they react to you touching the screen like this?

Maybe you can try running GPU-Z at the same time, and see if touching makes anything on it spike?

-[Unknown]

**Comment by supadupaplex** [comment]
I tried switching multithreaded on and off, to swipe finger all around screen and touching the same spot, result is the same.
I tried other apps: Hyper plays Youtube videos in fullhd no matter of what I do with screen. I also tried Max Payne 2 on high settings in hd. It does same CPU and GPU load, but FPS stays solid no matter what I do with screen (few month ago I played it through with touch controls only without any issue).
![8](https://cloud.githubusercontent.com/assets/15338328/12010328/75a8edba-acc3-11e5-813b-b7c7620b6b42.png)
MP2 before using touchscren
![9](https://cloud.githubusercontent.com/assets/15338328/12010326/75a81688-acc3-11e5-861f-27f2b88da49b.png)
MP2 after using touchscreen
![3_1](https://cloud.githubusercontent.com/assets/15338328/12010327/75a8cc18-acc3-11e5-9992-e736682557d1.png)
PPSSPP before using touchscreen
![4](https://cloud.githubusercontent.com/assets/15338328/12010329/75a9fd36-acc3-11e5-8cfc-82eaa739f135.png)
PPSSPP after using touchscreen

**Comment by unknownbrackets** [comment]
Woah, the "Core Speed" there is 500 Mhz.  It seems like it decided to downclock while you were touching... that could definitely cause the slowdown.  I wonder what would make it do that, though...

-[Unknown]

**Comment by supadupaplex** [comment]
Interesting. I tried to hold CPU speed by launching Max Payne 2 in background and ran PPSSPP in foreground. In that case core speed stays around 1333MHz and PPSSPP instead of dropping to 15fps drops only to 27-28fps.

**Comment by unknownbrackets** [comment]
Hmm:
http://stackoverflow.com/questions/30161529/minimizing-touch-latency-in-directx-opengl-applications
http://the-witness.net/news/2012/10/wm_touch-is-totally-bananas/

What happens if you simply comment out this line in Windows/MainWindow.cpp:

```c++
touchHandler.handleTouchEvent(hWnd, message, wParam, lParam);
```

And also change this line:

```c++
bool TouchInputHandler::hasTouch(){
```

To:

```c++
bool TouchInputHandler::hasTouch() { return false;
```

I think swipes may even continue working, but they may not.  What I'm most interested in is if the slowdown is gone.

-[Unknown]

**Comment by supadupaplex** [comment]
I tried that out, slowdown is still there.
I tried also to comment more input related functions, but it continues to slow down.
Looks like this issue is not directly related to touch input.
