### ISSUE TITLE
something wrong in PGF font code

### ISSUE THREAD

**Issue by tpunix** [hrydgard/ppsspp#8131]
log from PSP:
FontGetFontInfo: fid=08bdc8f8 size=00150015
FontGetCharInfo: uch=672c bw=17 bh=16 bx=0 by=14
FontGetCharInfo: uch=4f5c bw=17 bh=16 bx=0 by=14
FontGetCharInfo: uch=54c1 bw=15 bh=16 bx=1 by=14
FontGetCharInfo: uch=7eaf bw=17 bh=16 bx=0 by=14
FontGetCharInfo: uch=5c5e bw=16 bh=16 bx=0 by=14
FontGetCharInfo: uch=865a bw=17 bh=16 bx=0 by=14

log from ppsspp:
43:18:485 user_main    I[IO]: HLE\sceIo.cpp:848 stdout: FontGetFontInfo: fid=08bdc8e8 size=00150015
43:19:725 user_main    I[IO]: HLE\sceIo.cpp:848 stdout: FontGetCharInfo: uch=672c bw=17 bh=16 bx=0 by=14
43:19:726 user_main    I[IO]: HLE\sceIo.cpp:848 stdout: FontGetCharInfo: uch=4f5c bw=17 bh=16 bx=0 by=14
43:19:735 user_main    I[IO]: HLE\sceIo.cpp:848 stdout: FontGetCharInfo: uch=54c1 bw=15 bh=16 bx=1 by=14
43:19:735 user_main    I[IO]: HLE\sceIo.cpp:848 stdout: FontGetCharInfo: uch=7eaf bw=17 bh=16 bx=0 by=14
43:19:737 user_main    I[IO]: HLE\sceIo.cpp:848 stdout: FontGetCharInfo: uch=5c5e bw=16 bh=16 bx=0 by=14
43:19:769 user_main    I[IO]: HLE\sceIo.cpp:848 stdout: FontGetCharInfo: uch=865a bw=0 bh=0 bx=0 by=0

for unicode 0x865a, ppsspp return char info with all zero.

test iso file:
http://pan.baidu.com/s/1hqk6iAo

**Comment by unknownbrackets** [comment]
Are these all the same font?  Is the iso open source?  Don't want to download something I don't have license to.

-[Unknown]

**Comment by tpunix** [comment]
same iso run from psp and ppsspp. the font file is inside iso.

**Comment by tpunix** [comment]
I upload the font file to here: http://pan.baidu.com/s/1sjpD3zR

**Comment by tpunix** [comment]
OK, the problem is here:
When game call sceFontGetCharInfo(u32 fontHandle, u32 charCode, u32 charInfoPtr) with 0x865a, the charCode is 0xffff865a. 
after add "charCode &= 0xffff", the font display correctly.

**Comment by unknownbrackets** [comment]
It'd be nice to create more tests for this, but that change seems to make a lot of sense, given how the characters are even stored.  I'm going to close this.  Nice find.

-[Unknown]
