### ISSUE TITLE
some homebrews that dont load

### ISSUE THREAD

**Issue by scraggles80** [hrydgard/ppsspp#8132]
just come across a few homebrews that dont load in ppsspp

http://www.dcemu.co.uk/attachment.php?s=166b3892b0f14dedf78745f0e2388fc5&attachmentid=2328&d=1355089331

http://www.consolespot.net/uploads/downloads_downloads/ROTT_PSP_v101.zip

http://www.kosmodrones.com/downloads/Kosmodrones_v102.zip

these are just a few to name there is more

**Comment by LunaMoo** [comment]
![memo01340_00000](https://cloud.githubusercontent.com/assets/5485237/26570946/857699a6-4513-11e7-986a-5cdc52d540e9.jpg)

![rott01354_00000](https://cloud.githubusercontent.com/assets/5485237/26570955/89d5b496-4513-11e7-9b8a-b33ff310683e.jpg)

![kosm01172_00000](https://cloud.githubusercontent.com/assets/5485237/26570964/8d338eba-4513-11e7-9264-3cd5520f4ba6.jpg)

^ all works fine, "Memorama games" link has corrupted archive, got correct one from [here](http://wololo.net/talk/viewtopic.php?f=2&t=22637).
 If homebrew doesn't work make sure to run them from "/PSP/GAME" on memstick. They also can't be encrypted by any rare keys and preferably should be launched from homebrew tab.

 Anyway, closing.
