### ISSUE TITLE
[Enhancement] Horizontal text scrolling in settings

### ISSUE THREAD

**Issue by SukharevAndrey** [hrydgard/ppsspp#8136]
Please make all the text in settings menu automatically scrollable if it exceeds some predefined length (in my opinion text should scroll left and when it reaches the end of phrase - reset and do that again infinitely). Users with low resolution screens (mobile devices for example) have overlapping text everywhere in settings, especially in Russian language where correct translation requires much more space than in English.
![image](https://cloud.githubusercontent.com/assets/3942904/10869329/a120b0e0-80bd-11e5-9c36-6d2c15ecde9c.png)
This is a simulation of how it looks on that screens.
Also it would be great to see detailed explanation of every setting in application (like in Dolphin). For example it could be showed like Android toast on long press. It will eliminate a lot of comments in brackets.
![proposal](https://cloud.githubusercontent.com/assets/3942904/10869716/4a4f6c92-80c8-11e5-95c4-53895e11fdd5.png)
I thought I could do it myself but then realized that you are using your own custom UI framework done from scratch. I'm not so skilled programmer yet to customize such things :(

**Comment by VIRGINKLM** [comment]
I really like this idea.

**Comment by hrydgard** [comment]
Yes, adding explanations makes sense. I plan to redesign the UI a bit in the future to make space for them.

**Comment by zminhquanz** [comment]
good idea

**Comment by zminhquanz** [comment]
@hrydgard please redesign UI nearly XMB by Sony

**Comment by MarcoEstevez** [comment]
+1 zminhquanz suggestion

retroarch uses it and its great on PC with game controllers, not sure will fit well on phones, tablets touching fashion.

said that, ppsspp UI is also great, is one of the best original UI out there by far  :-D

**Comment by SukharevAndrey** [comment]
I think complete redesign is not needed, especially like XMB. RetroArch UI is not so suitable for touch control. Let the developers better focus on emulation.

**Comment by hrydgard** [comment]
XMB is not great for touch and there are patents around it, so that won't happen. More like changing the look of the existing interface a bit, maybe add an action bar, stuff like that.

**Comment by GamerzHell9137** [comment]
Ohhh~ UI change? Can't wait for that. find the PPSSPP UI pretty meh right now.

**Comment by unknownbrackets** [comment]
@hrydgard speaking of UI changes, what do you think of views having e.g. `std::vector<UI::Tween> tweens_`?  Could apply a matrix to bounds or maybe verts, as well as opacity, etc. based on a timer.  Trickiest part would want to make them cancel without fully reverting (e.g. to reverse or change a tween mid-swing.)

For explanation UI, getting touch right may take some thought.  I think the simplest thing is to show an explanation once they change the option, but how about dropdowns?  Of course, long-press could highlight without changing and that might not be too hard to discover.  It could even initially show the space (attached at bottom) with that CTA.

I'm not a huge fan of the horizontal scroll.  Personally, I'd rather we allow a certain % shrink in the text before we do that - it looks uneven when it shrinks, but less bad than when it moves.  Moving text is distracting.

Personally, I'd prefer it to wrap in the settings dialog, of the checkbox text is too long.  Still at maybe a certain % smaller font size and not too generous a line height.

-[Unknown]

**Comment by hrydgard** [comment]
Yes, some sort of animation system would be nice. 

To fit long strings, shrink to say 60% then wordwrap is probably the better idea, yes...
