### ISSUE TITLE
Remaining glitches in Blazing Souls Accelate

### ISSUE THREAD

**Issue by LunaMoo** [hrydgard/ppsspp#8145]
As mentioned in https://github.com/hrydgard/ppsspp/issues/4665#issuecomment-153156285 this game has some weird glitches which seems fixed by disabling slower effects, and appear differently depending if simulate block transfer is used or not. Screenshots made by PPSSPP will usually just make the glitch into completely black square, but they can be transparent gray as well as take shapes of elements they were under when the effect was created, like for example this:
![bsaartifacts](https://cloud.githubusercontent.com/assets/5485237/10903224/aa9b04e0-8207-11e5-83d2-22b3d1b3cb7e.jpg)
which was created under character and so still has an empty shape of character legs inside.
I copied contents of GEdebugger tabs while looking at that effect here: https://gist.github.com/LunaMoo/8378e6ec0641929cab78
You can see the texture used for this:
![texture](https://cloud.githubusercontent.com/assets/5485237/10903271/3e407af4-8208-11e5-937d-5e3044328489.jpg)
which is the blue frame on a black square, seems that the arrow to the right of it which is also on black square(all colors 0, a = 255) also causes those glitches while other things there are issue free.

 I really have no ideas what could it be, as mentioned disabling slower effects magically causes black/gray squares disappear and it shows normal graphics
![bsaslower effects disabled](https://cloud.githubusercontent.com/assets/5485237/10903366/2493bd36-8209-11e5-9735-fcf62df1d889.jpg)
.

**Comment by unknownbrackets** [comment]
unknown weights (1) hmm?

The blend mode is add: fixed, 1.0 - 2.0 * dst.a.  That means the destination alpha is very important.  This will require a framebuffer copy.

What does the stencil preview look like in this scene when it's drawing that graphic?

-[Unknown]

**Comment by LunaMoo** [comment]
![stencil](https://cloud.githubusercontent.com/assets/5485237/10903580/84f791c8-820b-11e5-95e5-239924cc0230.jpg)

**Comment by unknownbrackets** [comment]
After some debugging I'm pretty sure I know what the issue likely is here.

We don't handle alpha replacement correctly when doing framebuffer copies for bleinding.  I think this is causing alpha to be replaced by the output of the framebuffer copy.  Per your tabs, stencil test is disabled so it ought to retain the stencil value, but I don't think there's any code that actually retains right now.

Oops...

-[Unknown]

**Comment by unknownbrackets** [comment]
I was wrong, our strategy there is using a color mask, which ought to be working.  The problem was we lost the color mask during rendering.

-[Unknown]

**Comment by unknownbrackets** [comment]
Per:
https://github.com/hrydgard/ppsspp/issues/4665#issuecomment-153156285

This is using a 565 buffer.  What does `src * fixed + dst * (1.0 - 2 * dst.a)` mean when there are no `dst.a` bits?  It sounds like it means `src * fixed + dst * (1.0 - 2 * 0.0)` aka `src * fixed + dst * 1.0`.

Maybe we need to rewrite some blend modes in 565.  This doesn't even require shader blending.

-[Unknown]

**Comment by hrydgard** [comment]
Weird. Just goes to show how many bizarrely subtle behaviours there are to take care of in an emulator...

**Comment by LunaMoo** [comment]
Well #8158 did kind of fix it, as long as pause menu is not entered or if simulate block transfer is disabled.
 Nothing is really missing with disabled slower effects so it does pointless stuff ~ made in japan heh.
