### ISSUE TITLE
ys seven music isssues and speed issues no cutscene

### ISSUE THREAD

**Issue by asbel123** [hrydgard/ppsspp#8146]
i played ur new version ppsspp on automated buidls its says u did reverb psx sound on the build u did stuff up ys seven music when u play the game long its did bla bla music its means broken fix it hygard that was goood progreess for sound plugin it fix some games on speed like tales of phantasia.

i am using samsung galaxy s6 edge its fullspeed on the cutscene no frameskip just when no cutscene its go slow thats a bug.

**Comment by hrydgard** [comment]
Sorry I don't quite understand what you are saying. Are you saying that after the reverb was added, the music got "stuffed up" later in Ys Seven?

**Comment by unknownbrackets** [comment]
I don't know, but I haven't noticed any sound issues in Ys Seven really.

-[Unknown]

**Comment by asbel123** [comment]
its fullspeed on cutscence on my phone but music will stop working when u play the game longer after i speak the king in the beggning. i never put frameskip and without cutscence speed drop on the town.

**Comment by unknownbrackets** [comment]
If Ys Seven got slower recently, when did it get slower?  If it's been slower in all PPSSPP versions, then we're always trying to improve performance, but having a bug for every single game saying "it'd be nice if this game were faster" doesn't help us or anyone.

Does the music thing still happen in the latest builds?

-[Unknown]

**Comment by asbel123** [comment]
there is big bug when i load a save in the bar its fullspeed when go out in the town its fullspeed i walk around a bit in the town speed will decrase so much it werid bug there no  music problem u fix it.

**Comment by blackman91** [comment]
Try the latest ppsspp dev version and Select the option skip buffer effects in ppsspp settings to gain a performance boost in ys seven.

**Comment by asbel123** [comment]
i did that it fullspeed beacuase u disable the map display now u cant see it anymore why psp developer fixing map display on buffer rendering and hardware accurate.

**Comment by blackman91** [comment]
You can view the map by pressing select even if you skip buffer effects and like I said use the latest ppsspp dev version.

**Comment by blackman91** [comment]
Tip: With skip buffer effects on If you enable Buffered rendering in settings then go back to the game then go to settings again and select skip buffer effects again the minimap is now visible in skip buffered:
http://i1312.photobucket.com/albums/t539/talos910/Screenshot_2015-11-10-18-45-26_zps1uwf6mme.png

**Comment by unknownbrackets** [comment]
I'm not sure there's much to do here.  If it hasn't gotten slower recently, I don't think we need an issue for it.  We're always trying to improve performance.

-[Unknown]

**Comment by asbel123** [comment]
i find the problem is block trransfer rate fuck my speed ys seven turn it off its fullspeed
