### ISSUE TITLE
Motto Nuga-Cel(ULJM05654):shadow problems on the map

### ISSUE THREAD

**Issue by hys223344** [hrydgard/ppsspp#8148]
Test version: v1.1.1-188-g8692600
Platform: Windows 8.1 and Android
![uljm05654_00001](https://cloud.githubusercontent.com/assets/8475675/10905719/1c8f2348-8257-11e5-8518-d1e5c7491c66.jpg)
You can see the black shadow around the edge of the map. Actrually it is flashing. (won't flash if you set frameskip to 1,3,5 and so on) I think it is the wave effect(which is uncorrect?). And the problem is more complicated.
![uljm05654_00002](https://cloud.githubusercontent.com/assets/8475675/10905852/0d3749a6-8258-11e5-8aae-00b0bfac7e86.jpg)
As you can see, I changed the viewpoint, but the shadow that supposed to surround the edge didn't change synchronously. But if I press ESC to the setting ui and then resume the game,
![uljm05654_00003](https://cloud.githubusercontent.com/assets/8475675/10906133/feba3896-8259-11e5-8060-b48fd750e45b.jpg)
the shadow changed as you can see. So the problem is: there are strange shadows flashing around the map, and it won't change until you go to the setting ui and then resume.
PS: The problem won't happen when I disable slower effects.

**Comment by hys223344** [comment]
By the way, some special effect in battle shows black (and flashing too), and it can also be solved by disable slower effects.

**Comment by unknownbrackets** [comment]
I wonder if this is also alpha being handled wrong by shader blending...

-[Unknown]

**Comment by LunaMoo** [comment]
This could be same as #8145 both of those games were made by same company, and had same flipping issue as well.

**Comment by daniel229** [comment]
Fixed in https://github.com/hrydgard/ppsspp/issues/8148

**Comment by hrydgard** [comment]
@daniel229 #8158 is this issue, do you mean #8163?

**Comment by daniel229** [comment]
The previous one https://github.com/hrydgard/ppsspp/commit/606c57d478ccac7df29e317c521efc11aaf9c9ef

**Comment by daniel229** [comment]
and https://github.com/hrydgard/ppsspp/commit/8145cc789abb69a86dff6908dddde47a6dd37ed0

**Comment by hrydgard** [comment]
Alright, great.
