### ISSUE TITLE
Motto Nuga-Cel(ULJM05654):character's position is wrong in the battle

### ISSUE THREAD

**Issue by hys223344** [hrydgard/ppsspp#8149]
Test version: v1.1.1-188-g8692600
Platform: Windows 8.1 and Android
![uljm05654_00004](https://cloud.githubusercontent.com/assets/8475675/10907832/784cb02c-8268-11e5-89c8-2c04a087dc96.jpg)
The characters are supposed to stand in the circle, but they are not.

**Comment by unknownbrackets** [comment]
Can you post a screenshot of a PSP just so we can understand how they are off?

-[Unknown]

**Comment by hrydgard** [comment]
My guess would be that the blonde character is supposed to stand on the orange circle, so we're off vertically a bit.

**Comment by sum2012** [comment]
First of all,allthough I am Hong Kong people.
But I think that report chinese patch iso of problem is bad.
Anyway
@hrydgard @unknownbrackets 
It is broke by #8130 
v1.1.1-194-g44be9f2 GE debugger
![2](https://cloud.githubusercontent.com/assets/2177532/10924975/83f06240-82c5-11e5-8d02-c57440729e67.png)

**Comment by unknownbrackets** [comment]
Hmm, that draw shouldn't need shader blending or depal or anything, so I guess the main things would be viewport, range, etc.  Maybe matrices, but not sure.  Can you show the contents of the Settings tab?

-[Unknown]

**Comment by sum2012** [comment]
![1](https://cloud.githubusercontent.com/assets/2177532/10937038/44dda0ca-832b-11e5-9850-2176e149966b.png)
![2](https://cloud.githubusercontent.com/assets/2177532/10937043/48f07a0c-832b-11e5-8e2a-9bc3b5034991.png)
![3](https://cloud.githubusercontent.com/assets/2177532/10937047/4bd112f4-832b-11e5-94e2-9772957b384f.png)
![4](https://cloud.githubusercontent.com/assets/2177532/10937051/50705b1c-832b-11e5-8802-60f786e5bea1.png)

**Comment by unknownbrackets** [comment]
Well, those are definitely unusual viewport settings.

-[Unknown]

**Comment by hys223344** [comment]
Tested on the newest version. It's fixed. Thanks.
