### ISSUE TITLE
Danball Senki W background broken after going to the game menu

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8150]
Since https://github.com/hrydgard/ppsspp/pull/8130

Video (rename png to mp4) 
![danball senki w flickering](https://cloud.githubusercontent.com/assets/3481559/10909457/5fa5a37e-8274-11e5-896f-13ac9c2a5ab3.png)

**Comment by hrydgard** [comment]
As stated in #8168 , no longer flickering but background still broken.

**Comment by daniel229** [comment]
Fixed in https://github.com/hrydgard/ppsspp/commit/ac31c66a60135e773020d7f441f4de0b35d4a584
