### ISSUE TITLE
Chuumon Shiyouze! Oretachi no Sekai broken sound during loop

### ISSUE THREAD

**Issue by khanhhc12** [hrydgard/ppsspp#8156]
From v1.1.1-139-g9168af7, character voice glitch in duel.

**Comment by daniel229** [comment]
Look fine in v1.1.1-194-g44be9f2.

**Comment by daniel229** [comment]
Looks like the first word is shaking.

**Comment by unknownbrackets** [comment]
Does this problem not exist in v1.1.1-123-gf470ed8?  Are any errors logged?

-[Unknown]

**Comment by daniel229** [comment]
Not exist in v1.1.1-123-gf470ed8,logs seems normal.

**Comment by daniel229** [comment]
It's https://github.com/unknownbrackets/ppsspp/commit/7e05d0db4b513d1e9ac4b579d1854f37eb0f4f7b

**Comment by daniel229** [comment]
Ranshima Monogatari Rare Land Story is also broken.

**Comment by daniel229** [comment]
pro yakyuu spirits 2014 also has vioce problem.
In Chuumon Shiyouze! Oretachi no Sekai the title BGM has a broken sound when it looping. Reference to https://github.com/hrydgard/ppsspp/pull/8105

**Comment by daniel229** [comment]
also affects 
Ranshima Monogatari Rare Land Story
Kiniro no Corda 2
Resistance Retribution and demo

**Comment by unknownbrackets** [comment]
I think this may actually be the same as #8324, potentially.

If you revert the `getFileOffsetBySample` part of that commit, does it work?  Although, it seems like neither version is completely correct...

-[Unknown]

**Comment by daniel229** [comment]
Yes, it's that part just test the Yu-Gi-Oh though.

**Comment by daniel229** [comment]
All are fixed except the one Chuumon Shiyouze! Oretachi no Sekai on the title, seems not related to others.

**Comment by unknownbrackets** [comment]
Does it log anything interesting when it loops?

-[Unknown]

**Comment by daniel229** [comment]
09fbfa90[0000062d] is special,alway is 09fbfa90[00000800]
```
11:42:236 ATRAC3 play  N[ME]: HLE\sceAtrac.cpp:1132 00000000=sceAtracDecodeData(0, 08b034e8, 09fbfa90[00000800], 09fbfa94[00000000], 09fbfa9c[-1])
11:42:269 ATRAC3 play  N[ME]: HLE\sceAtrac.cpp:1132 00000000=sceAtracDecodeData(0, 08b054e8, 09fbfa90[00000800], 09fbfa94[00000000], 09fbfa9c[-1])
11:42:337 ATRAC3 play  N[ME]: HLE\sceAtrac.cpp:1132 00000000=sceAtracDecodeData(0, 08b074e8, 09fbfa90[00000800], 09fbfa94[00000000], 09fbfa9c[-1])
11:42:370 ATRAC3 play  N[ME]: HLE\sceAtrac.cpp:1132 00000000=sceAtracDecodeData(0, 08b034e8, 09fbfa90[0000062d], 09fbfa94[00000000], 09fbfa9c[-1])
11:42:436 ATRAC3 play  N[ME]: HLE\sceAtrac.cpp:1132 00000000=sceAtracDecodeData(0, 08b04d9c, 09fbfa90[00000800], 09fbfa94[00000000], 09fbfa9c[-1])
11:42:469 ATRAC3 play  N[ME]: HLE\sceAtrac.cpp:1132 00000000=sceAtracDecodeData(0, 08b06d9c, 09fbfa90[00000800], 09fbfa94[00000000], 09fbfa9c[-1])
11:42:504 ATRAC3 play  N[ME]: HLE\sceAtrac.cpp:1132 00000000=sceAtracDecodeData(0, 08b02d9c, 09fbfa90[00000800], 09fbfa94[00000000], 09fbfa9c[-1])
11:42:571 ATRAC3 play  N[ME]: HLE\sceAtrac.cpp:1132 00000000=sceAtracDecodeData(0, 08b04d9c, 09fbfa90[00000800], 09fbfa94[00000000], 09fbfa9c[-1])
```

**Comment by unknownbrackets** [comment]
I suspect the issue here is looping.  I think `Decode` is supposed to potentially join the samples of the before-end and after-start portions together, or something.  Even if it's not, it's possible it's returning samples before the start position, or something.

-[Unknown]

**Comment by daniel229** [comment]
Fixed.
