### ISSUE TITLE
Resistance retribution (UCUS98668) viewport shift since build v1.1.1-182

### ISSUE THREAD

**Issue by ppsspp-gamer** [hrydgard/ppsspp#8161]
Resistance retribution (UCUS98668) viewport shift since build v1.1.1-182, the last working build is ppsspp-v1.1.1-166.

screen shot from build v1.1.1-166
![correct](https://cloud.githubusercontent.com/assets/8726272/10932280/8ab935da-830a-11e5-8c75-959ff477b4d3.jpg)

screen shot from build build v1.1.1-182
![wrong](https://cloud.githubusercontent.com/assets/8726272/10932321/d5558f1c-830a-11e5-95fd-2abc6d305f93.jpg)

Testing on windows 8.1 x64 OpenGL backend with all default settings.

**Comment by daniel229** [comment]
ingame is flickering like https://github.com/hrydgard/ppsspp/issues/8150 .But the demo seems fine.

**Comment by daniel229** [comment]
The subtitle is flickering in the demo,maybe related.

**Comment by ppsspp-gamer** [comment]
upscale texture fixed the subtitle flickering, but don't know why.
