### ISSUE TITLE
Three Kingdom 9 missing BGM

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8162]
Since https://github.com/unknownbrackets/ppsspp/commit/5cc13c45f481197a0b67d1d43e21c5471ddfd97d

**Comment by unknownbrackets** [comment]
#8176 doesn't help, right?  This game never uses either Reset function?

The biggest concern in that game is the remain frame calculation, which is still off.  I think I need to get that one right next.

Can you post a log?

-[Unknown]

**Comment by daniel229** [comment]
https://github.com/hrydgard/ppsspp/pull/8176 does not help.
The log
```
12:14:761              I[ME]: HLE\sceAtrac.cpp:1785 0=sceAtracSetHalfwayBufferAndGetID(091e4a00, 00008000, 00080000)
12:14:761              W[ME]: HLE\sceAtrac.cpp:1652 This is an atrac3+ stereo audio
12:14:761              W[ME]: HLE\sceAtrac.cpp:1892 UNIMPL sceAtracIsSecondBufferNeeded(0)
12:14:762              I[ME]: HLE\sceAtrac.cpp:1436 sceAtracReleaseAtracID(0)
```

**Comment by unknownbrackets** [comment]
Does the log look the same before?  I'm wanting to see the differences in what the game does.

-[Unknown]

**Comment by daniel229** [comment]
This is the working one,it does not have <code>I[ME]: HLE\sceAtrac.cpp:1436 sceAtracReleaseAtracID(0)</code>
```
23:58:219              I[ME]: HLE\sceAtrac.cpp:1715 0=sceAtracSetHalfwayBufferAndGetID(091e4a00, 00008000, 00080000)
23:58:219              W[ME]: HLE\sceAtrac.cpp:1581 This is an atrac3+ stereo audio
23:58:222              W[ME]: HLE\sceAtrac.cpp:1821 UNIMPL sceAtracIsSecondBufferNeeded(0)
```

**Comment by unknownbrackets** [comment]
Hmm, okay, so then it almost must be the remaining frames value from Decode.

-[Unknown]

**Comment by unknownbrackets** [comment]
For posterity: it wasn't remaining frame values, it was that `end sample #` and `loop end sample #` didn't match up properly.

-[Unknown]
