### ISSUE TITLE
FF Type-0 shadow broken

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8169]
Since https://github.com/hrydgard/ppsspp/pull/8158
![01](https://cloud.githubusercontent.com/assets/3481559/10954991/e98d3648-838b-11e5-86a0-c99a228ad692.png)

**Comment by daniel229** [comment]
Dragon ball TAGVS is also broken by the same cause.
![03](https://cloud.githubusercontent.com/assets/3481559/10955240/70031a2a-838d-11e5-852e-483b4c0020ac.png)

**Comment by hrydgard** [comment]
So, depal effects. Interesting..

**Comment by daniel229** [comment]
The 3rd birthday also.
![06](https://github-cloud.s3.amazonaws.com/assets%2F3481559%2F10957344%2F59371592-839e-11e5-8d9f-dd4809c5387d.png)
