### ISSUE TITLE
Silent Hill Zero black rectangle on top left in the dark area.

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8173]
![07](https://cloud.githubusercontent.com/assets/3481559/10959764/8fdf0a32-83b7-11e5-84c3-b49ffeabbaf4.png)

GE debugger
![08](https://cloud.githubusercontent.com/assets/3481559/10959825/6685e3a8-83b8-11e5-9737-acbd0187a540.png)

other tabs
https://gist.github.com/daniel229/fe8a8c6a95ceaaea6e6e

**Comment by unknownbrackets** [comment]
Is this new?  This seems like a blending bug...

Anyway, I think your GE debugger screenshot is "too late".  It's just copying the issue from the left side to the screen at that point, I think.  I wonder what's causing the issue there...

-[Unknown]

**Comment by daniel229** [comment]
The first step prim is also like copy the screen.
![09](https://cloud.githubusercontent.com/assets/3481559/10959939/8f87524a-83b9-11e5-8d83-25958a362b98.png)

or this?
![10](https://cloud.githubusercontent.com/assets/3481559/10959959/c3693c5e-83b9-11e5-917c-5e2a724d57f8.png)

**Comment by LunaMoo** [comment]
Maybe check how that circle of the light is done, I mean it does look like a transparent rectangle would cover the light, but maybe there is no rectangle there at all and just something fails at those coordinates while drawing the light.

 Stencil related probably since people on the forum write it works fine after disabling stencil test.

**Comment by daniel229** [comment]
it's missing shadows,maybe taht is it.disabling stencil test no rectangular,also no shadow.
This part looks like it draws the shadows,and it does not draw when the flash light off.
![14](https://cloud.githubusercontent.com/assets/3481559/10966739/91e73136-83f0-11e5-894c-fa8351de1f93.png)

this is draw the light.
![15](https://cloud.githubusercontent.com/assets/3481559/10967115/3eb5f364-83f3-11e5-9f04-23e9b7d45c7b.png)
![16](https://cloud.githubusercontent.com/assets/3481559/10967116/3ebd2274-83f3-11e5-8d0b-4031632adfd1.png)

**Comment by hrydgard** [comment]
That looks a lot like a depth-based shadow map, a technique that's not used much on the PSP. Interesting.

**Comment by daniel229** [comment]
Got an error in texture upload: 00000501
![20](https://cloud.githubusercontent.com/assets/3481559/12061633/231d7628-afc6-11e5-878c-9caeb3a26250.png)

**Comment by unknownbrackets** [comment]
Well, that means something is generating an GL_INVALID_VALUE.  Would need to place a bunch of glGetError() logs in various places to track it down, OR use debug.  Debug is probably a bit easier.

First, set `GfxDebugOutput = True` under `[Graphics]` in ppsspp.ini.

Next, in Windows/GPU/WindowsGLContext.cpp, find:

```c++
OutputDebugStringA(finalMessage);
```

I recommend adding `DebugBreak();` after that.  I would also place `#pragma optimize("", off)` at the top of this file, as well as GPU/GLES/StateMapping.cpp, GPU/GLES/Framebuffer.cpp, and GPU/GLES/TextureCache.cpp.  Then run with the debugger, and hope it trips.

When it does, you can possibly see a better error message from the value of `finalMessage`.  And if you switch the thread to Emu (it will normally be on an nv thread), you might get lucky and be at least nearby the offending OpenGL function call.

-[Unknown]

**Comment by daniel229** [comment]
I get the GL_INVALID_VALUE,but it seems much earlier hapeen than the logs console.

tracestack
![01](https://cloud.githubusercontent.com/assets/3481559/12064175/4487ceae-aff7-11e5-9040-1b7f0494ade6.png)

**Comment by unknownbrackets** [comment]
Ah, sorry, click into ApplyTextureFramebuffer there - around where is it?

-[Unknown]

**Comment by daniel229** [comment]
Here
![2](https://cloud.githubusercontent.com/assets/3481559/12069215/21e4d564-b05f-11e5-98b4-1c05a3e3bc8d.png)

**Comment by daniel229** [comment]
demo and the savestate
https://drive.google.com/folderview?id=0BzGZGDfFE68zdXR6QVZNbGpkekE&usp=sharing

**Comment by benderscruffy** [comment]
this has been fixed as far as i can tell 
![silent](https://user-images.githubusercontent.com/2696404/56400031-28218000-6284-11e9-8bef-975a381fdbca.PNG)
can be closed

**Comment by unknownbrackets** [comment]
Glad to hear - thanks for testing.

-[Unknown]
