### ISSUE TITLE
How to handle savedata import from different games?

### ISSUE THREAD

**Issue by i30817** [hrydgard/ppsspp#8177]
Recently released game (in english) Legend of Heroes second chapter has a savedata import feature that is apparently not importing from the first game even though i have it and can load the clear save if i load that game.
Maybe it should be a function of the savedata manager?

BTW, this game (SC) comes in two cds/iso so if savedata doesn't import between titles, it's possible it might not be possible to change cd if it uses saves to carry over (and if it just prompts for cd change... well, ppsspp has no option for that either).

**Comment by unknownbrackets** [comment]
It's supposed to work and I thought it did for other games.  We'll have to debug why it doesn't work.

Can you post some clear data somewhere?  Sorry, I need to play the first one through all the way already.  Also, did you confirm that the clear data works on a real PSP, just to be sure?

-[Unknown]

**Comment by LunaMoo** [comment]
Works fine here.

 This could be another case of game modified to run on older firmware in which case psp would have same problems.

 As for changing UMD's there is an option for that on pause screen, it's just hidden until game requests the umd change.

**Comment by i30817** [comment]
![ules015560196 zip](https://cloud.githubusercontent.com/assets/757900/10991603/93a7d438-8456-11e5-9123-66102f8f04ca.png)

fake png zip savefile

**Comment by LunaMoo** [comment]
Well the name of the folder explains it all. Your save was from EU version of the first game.
 SC was released only in NA for now so you certainly can't have EU version of it and games detect only saves from their own region.

 You could try renaming your EU save from first game to how US version should be named(ie ULUS105400101), that doesn't work with all games through.

**Comment by i30817** [comment]
Ah, thanks.

**Comment by unknownbrackets** [comment]
Okay, going to close this until we have an issue.

-[Unknown]
