### ISSUE TITLE
legend of heros trials in the sky second chapter english music issues

### ISSUE THREAD

**Issue by asbel123** [hrydgard/ppsspp#8188]
played the game on andriod on my phone there is new bug is when u go to battle music is fine after battle music stop  working its weird bug  it will crash going new area.  i cant play the game anymore fix it please hygard its same problem did tales of the world radiant mthyology 2 and 3. i am using lastest git version on andriod.

**Comment by asbel123** [comment]
closed the issues its fixed lastes version of git.

**Comment by papel** [comment]
I am playing The Legend of Heroes - Trails in the Sky - Second Chapter (English version) in the first dungeon. When I finish a battle, the audio may disappear sometimes.

The problem occur on version 1.1.1. So I am using v1.1.1-340 and the problem hasn't occurred so far.
