### ISSUE TITLE
BGM stopped in Kurohyo 2

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8195]
Also happen in the Demo.
Load the savestate in the demo and wait a few seconds until the subtitle come up.
https://drive.google.com/file/d/0BzGZGDfFE68zaWxtT0F6UGdrcUk/view?usp=sharing

```
47:39:979 sgx-psp-at3- I[ME]: HW\MediaEngine.cpp:87 FF: Frame data doesn't match channel configuration!
47:39:979 sgx-psp-at3- E[ME]: HLE\sceAtrac.cpp:479 avcodec_decode_audio4: Error decoding audio -1094995529 / bebbb1b7
47:40:061 sgx-psp-at3- I[ME]: HLE\sceAtrac.cpp:1480 sceAtracReleaseAtracID(1)
```

**Comment by unknownbrackets** [comment]
Hmm, this is happening when it loops.  Adding a hack to make sceAtracGetStreamDataInfo() request more data when it loops (which is what should happen, but this was just a hack for this specific music) makes it work correctly.

-[Unknown]

**Comment by daniel229** [comment]
Seems like it's good before https://github.com/hrydgard/ppsspp/pull/6976

**Comment by unknownbrackets** [comment]
Most likely 7a974b364c26ba8566e09ef061c1c3fb8b47b514, but I think it was only accidentally working before.

-[Unknown]

**Comment by daniel229** [comment]
Reverting that and still get that error.
