### ISSUE TITLE
ios 1.1.1 can not  use 1.0.1 's   savestate?

### ISSUE THREAD

**Issue by xurayg** [hrydgard/ppsspp#8199]
When I load 1.0.1' savestate file . It  show me : Error: After "GPUCommon", found 0 (0x0) instead of save marker 66 (0x42). Aborting savestate load...  
anyone can help?

**Comment by sergiobenrocha2** [comment]
You should use the save inside game instead savestates before update any emulator...

**Comment by unknownbrackets** [comment]
Can you upload the savestate somewhere?

-[Unknown]

**Comment by xurayg** [comment]
Yes !
https://www.dropbox.com/s/eisikzspxbsbpdv/gameandsavestates.zip?dl=0
Thank you~

**Comment by unknownbrackets** [comment]
I've pulled the savestates, thanks, but I removed the link and am ignoring the game that was inside (I'm surprised it's so small.)  Not wanting to accidentally put transfer copyrighted content around.  The savestates alone are good enough to debug the issue (they won't actually let you play the game alone, though.)

Anyway, I've found the issue and it should be fixed soon in a git build.

-[Unknown]
