### ISSUE TITLE
Hard Coded MAC SDL to rpi2

### ISSUE THREAD

**Issue by Omnija** [hrydgard/ppsspp#8203]
Hard Coded SDL controls for mac screws up the xbox 360 controller on the rpi2. It causes many issues such as incorrect controller input and unable to remap without causes tons of glitching and wrong button spamming. Making it impossible to remap or use unless the setting below are changed.

http://forums.ppsspp.org/showthread.php?tid=2108&pid=111910#pid111910

**Comment by unknownbrackets** [comment]
Centralizing this in #7847.  There's no reason to have multiple open, and that one has just a bit more recent discussion.  We'll move nowhere if we keep rehashing things we already discussed.

-[Unknown]
