### ISSUE TITLE
LocoRoco 1 - can't delete loco houses

### ISSUE THREAD

**Issue by cdxemu** [hrydgard/ppsspp#8209]
Using PPSSPP 1.1.1 on Windows 7. I also use the "installed.txt" option to override the default save folder.

Steps to reproduce:
1. From the Main Menu, select Loco House.
2. Open the Menu (press Square).
3. Choose Data from the menu.
4. Choose Save to save your house. 
5. Choose Data from the menu again.
6. Press Square to open Delete menu.

Problem:
The file list for Delete will be blank instead of listing your saved house(s). (Unlike the Load menu, which works fine.)

The console output of Delete (followed by Load for comparison) seems to indicate that the game key passed to delete is blank:
![locoroco_deletehouse](https://cloud.githubusercontent.com/assets/15841485/11161223/16e0f4e6-8a34-11e5-9595-e47c03c9414e.jpg)

**Comment by cdxemu** [comment]
Didn't notice this at first, but the problem also occurs in the delete menu for save games, not just the houses.

**Comment by unknownbrackets** [comment]
I don't think the game key is necessary.  But, it could be we're handling the save name list wrong for LISTDELETE, or something.

Would you be able to compile PPSSPP with some changes?  It doesn't require anything but a little time and a few free downloads.  The instructions are here:

http://forums.ppsspp.org/showthread.php?tid=5231

If that sounds doable, let me know.  We can add some debugging code and try to figure this out.

-[Unknown]

**Comment by Panderner** [comment]
They reported that inability to delete multiple loco house save files due to #7685, in order to delete these save files go to PPSSPP's savedata manager and delete loco house save file

**Comment by unknownbrackets** [comment]
Delete has been implemented for a while now.  I'm going to close this assuming it's now fixed.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
