### ISSUE TITLE
Crash in shepard__s_crossing

### ISSUE THREAD

**Issue by Honcharuk** [hrydgard/ppsspp#8212]
After intro shepard__s_crossing.cso crashing i vait fix very long time.

**Comment by sum2012** [comment]
Does the game id is ULUS10499 ?

**Comment by Honcharuk** [comment]
"ULUS10499DATA00" have name save folder

Honcharuk

**Comment by sum2012** [comment]
Try newest version in
http://buildbot.orphis.net/ppsspp/

**Comment by Honcharuk** [comment]
I need iOS version, please.
Stable also crashes.

Honcharuk

**Comment by unknownbrackets** [comment]
iOS is broken right now.  See #8122.

-[Unknown]
