### ISSUE TITLE
QIX++ saving issue

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#8214]
edit ppsspp forum: http://forums.ppsspp.org/showthread.php?tid=6368&highlight=qix
It display "There is no data" screen rather than "Do you want create data ?"
It seem that try to forever load save data.
Last good v1.1.1-286-ge7081f8
First bad v1.1.1-287-g3acdd4e
this commit
https://github.com/hrydgard/ppsspp/commit/3acdd4e2372181ed493be86e756c3fd0e7896511
This is unusal that that commit do not change SceUtility.
v1.1.1-286-ge7081f8 log:https://gist.github.com/sum2012/a7028e781f5a9a57a5f4
v1.1.1-287-g3acdd4e log:https://gist.github.com/sum2012/61cf1bd37b8aca1719ca

**Comment by sum2012** [comment]
In v1.1.1-286-ge7081f8 ,after saving->Restart the game->cannot load data

**Comment by unknownbrackets** [comment]
So maybe this always happens, just didn't notice it before?

Does `ULJM056170000/QIXPP.SAV` exist?

-[Unknown]

**Comment by sum2012** [comment]
Yes,this also happens,I did not notice it before.
(Today I want to make font hack so that I notice it)
 ULJM056170000/QIXPP.SAV  exist
load save log: https://gist.github.com/sum2012/4a5c0bb041b169f4cd9b

**Comment by sum2012** [comment]
@unknownbrackets I know the first issue
If there is other game save,it will not ask to create game save's data

**Comment by sum2012** [comment]
@unknownbrackets This is JPCSPTrace log that have other game save first,then I choose save.
Hope you have idea.Thanks.
log: https://gist.github.com/sum2012/1c221ff26680375bb772

**Comment by sum2012** [comment]
v1.2.2-763-gdddb3c3  same problem
log:
https://gist.github.com/sum2012/7281562e7f49f54df4efffae11ce9e79

**Comment by Cibomatto2002** [comment]
This still happens on ppsspp-v1.5.4-820-g3f89cccd3-windows-x86. I'm using the real PSP Window 10
I have to delete the save file to play the game.

**Comment by unknownbrackets** [comment]
I'm hoping that #11215 may have helped this issue.  Is it working now?

-[Unknown]

**Comment by benderscruffy01** [comment]
v1.8.0-17-g737be61f9
still stuck in the loop as sum2012 first post explains
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/2999980/ppsspplog.zip)

**Comment by sum2012** [comment]
int SavedataParam::Save(SceUtilitySavedataParam* param, const std::string &saveDirName, bool secureMode) {
	NOTICE_LOG(SCEUTILITY, "secureVersion %d", param->secureVersion);

@unknownbrackets  The secureVersion is 0

**Comment by nassau-tk** [comment]
Sorry, this is Amateur's question.
There is 2 game ID on Qix++.
NPJH50199 & ULJM05617 are ID of Qix ++ both.
I don't known what kind of difference there is.

But, ID of NPJH50199 is create a save filename ULJM056170000.
This was also same in RealPSP.
Is this the case that nothing influences a solution of the issue?

**Comment by hrydgard** [comment]
One is probably a digital download release or similar. I'm not aware of any previous cases where the save directory is different though, odd. I don't think it's likely to help find a solution, either...

**Comment by hrydgard** [comment]
Please try again, now that #13434 is merged.

**Comment by nassau-tk** [comment]
@hrydgard 
Yes,This issue solved by v1.10.3-695.
And,New issue appear!!
It's a invalid memory access error!!
I will up the another report.

**Comment by sum2012** [comment]
> @hrydgard
> Yes,This issue solved by v1.10.3-695.
> And,New issue appear!!
> It's a invalid memory access error!!
> I will up the another report.

it is on #9466

**Comment by nassau-tk** [comment]
@sum2012 

Oh...Sorry.

**Comment by unknownbrackets** [comment]
> not aware of any previous cases where the save directory is different though, odd.

This is normal.  Dual release (physical and digital) games typically use their physical disc id for the save data.  This way if you bought it both ways (perhaps because your disc was lost), you wouldn't lose your progress.

-[Unknown]
