### ISSUE TITLE
MEMORIES OF 2nd missing audio from video

### ISSUE THREAD

**Issue by lightfirst** [hrydgard/ppsspp#8222]
the video using Mono AT3+ audio
14:14:361 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2019 0=sceKernelStartThread(331, 4, 0bfff590)
14:14:364 CRI ADX File I[IO]: HLE\sceIo.cpp:916 stdout: PSPCI: File cache was not hit. "disc0:/PSP_GAME/USRDIR/DATA/MOVIE/OP03.PMF"
14:14:364 CRI ADX File E[IO]: HLE\sceIo.cpp:1705 UNIMPL sceIoChangeAsyncPriority(11, 24)
14:14:365 CRI ADX File E[IO]: HLE\sceIo.cpp:1705 UNIMPL sceIoChangeAsyncPriority(11, 24)
14:14:365 CRI ADX File E[IO]: HLE\sceIo.cpp:1705 UNIMPL sceIoChangeAsyncPriority(12, 24)
14:14:381 SofdecThread I[ME]: HLE\sceMpeg.cpp:348 Stream offset: 2048, Stream size: 0xF71000
14:14:381 SofdecThread I[ME]: HLE\sceMpeg.cpp:349 First timestamp: 90000, Last timestamp: 10264164
14:14:381 SofdecThread I[ME]: HLE\sceMpeg.cpp:348 Stream offset: 2048, Stream size: 0xF71000
14:14:381 SofdecThread I[ME]: HLE\sceMpeg.cpp:349 First timestamp: 90000, Last timestamp: 10264164
14:14:381 SofdecThread I[ME]: HLE\sceMpeg.cpp:348 Stream offset: 2048, Stream size: 0xF71000
14:14:381 SofdecThread I[ME]: HLE\sceMpeg.cpp:349 First timestamp: 90000, Last timestamp: 10264164
14:14:390 SofdecThread I[ME]: HW\MediaEngine.cpp:87 FF: deprecated pixel format used, make sure you did set range correctly
14:14:391 SofdecThread I[ME]: HW\MediaEngine.cpp:87 FF: No accelerated colorspace conversion found from yuv420p to rgba.
14:14:392 SofdecThread I[ME]: HW\MediaEngine.cpp:87 FF: Frame data doesn't match channel configuration!
14:14:392 SofdecThread E[ME]: HW\SimpleAudioDec.cpp:175 Error decoding Audio frame (744 bytes): -1094995529 (bebbb1b7)
14:14:392 SofdecThread E[ME]: HW\MediaEngine.cpp:866 Audio (AT3+) decode failed during video playback
14:14:397 SofdecThread I[ME]: HW\MediaEngine.cpp:87 FF: Frame data doesn't match channel configuration!
14:14:397 SofdecThread E[ME]: HW\SimpleAudioDec.cpp:175 Error decoding Audio frame (744 bytes): -1094995529 (bebbb1b7)
14:14:397 SofdecThread E[ME]: HW\MediaEngine.cpp:866 Audio (AT3+) decode failed during video playback

**Comment by hrydgard** [comment]
Seems likely #8472 helped?

**Comment by daniel229** [comment]
Yes.
