### ISSUE TITLE
Blending bug in Heroes Phantasia

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8227]
Since https://github.com/hrydgard/ppsspp/pull/8213
![02](https://cloud.githubusercontent.com/assets/3481559/11269842/c4e481b0-8ef4-11e5-8e3d-b720194539a8.png)

Gedebugger
https://gist.github.com/daniel229/e3f45eb7e9bf41be5ca2

**Comment by unknownbrackets** [comment]
Oh, this is affected by removing the defaults.  This uses `0x3b` which is invalid but I think is treated as `0x3a`... bleh.

-[Unknown]
