### ISSUE TITLE
Paid clone of PPSSPP

### ISSUE THREAD

**Issue by SukharevAndrey** [hrydgard/ppsspp#8229]
Some russian team is currently making a paid clone of PPSSPP - https://play.google.com/store/apps/details?id=com.expertarts.sunshine.premium
There are no source codes, they have no provided change list (what approvements are made?). Discussion in russian can be found here - http://4pda.ru/forum/index.php?showtopic=394559&st=14020
Your license is GPL 2.0+ so they are violating license and must release source codes. Also they don't want to contribute to the original PPSSPP. What is your opinion about that?
P.S. That thread also contains links to other clones of emulator.

**Comment by hrydgard** [comment]
Thanks for letting me know. They must at a very minimum release the full
source code to their modified version. I've sent them an email, we'll see
if they do anything..

2015-11-21 17:08 GMT+01:00 Sukharev Andrey <notifications@github.com>:
