### ISSUE TITLE
Will this ever work on iOS 9

### ISSUE THREAD

**Issue by Kratos9803** [hrydgard/ppsspp#8231]
I have an iPhone 6 with iOS 9.0.2 and all it does is crash.

**Comment by unknownbrackets** [comment]
#8206.  I'm just going to close yours without reading or replying to them if you open another.

-[Unknown]

**Comment by Kratos9803** [comment]
Wow I asked a simple question just to see if you intend on fixing it for iOS 9 and all I get is I'm going to close your issues without reading or replying.  I don't know where to go to report bugs like the one I'm having trouble with.  If you won't help then GO FUCK YOURSELF ASSHOLE.

**Comment by deadair3210** [comment]
One - The devs are doing this all for free at their expense, and people like you flying off the handle after one response is not helping anything
Two - If you search for issues before making one like is normal for a person to do, you would not only find multiple other issues just like this one with the same outcome, but you would also find a issue that explains the issue in depth and acknowledges that the devs know about the issue and are working on it

**Comment by hrydgard** [comment]
@Kratos9803 Unknown linked you to a duplicate issue. Say anything like that again and I ban you forever. Oh and if Apple hadn't changed their security, PPSSPP would still work. You should have stayed at 8.1.

**Comment by Kratos9803** [comment]
Sorry I didn't know and I'm not familiar with github even though I've developed for the iOS platform I know how frustrating it must be to write code.  Sorry for the hostility and cursing.  I honestly like the feel of iOS 9 mostly because of the iCloud Drive app.  I hope this will work with iOS 9.0.2 sometime down the road.  I loved playing games like midnight club, God of war, etc.
