### ISSUE TITLE
Having problem when open project in Visual Studio 2015

### ISSUE THREAD

**Issue by zminhquanz** [hrydgard/ppsspp#8232]
![image](https://cloud.githubusercontent.com/assets/11285640/11356466/948dd9cc-9290-11e5-97a8-b89429590caa.png)
where i download this missing future

**Comment by unknownbrackets** [comment]
Probably your install didn't come with that.  Just click Install.

-[Unknown]

**Comment by unknownbrackets** [comment]
Closing this, reply if that doesn't do the trick.

-[Unknown]
