### ISSUE TITLE
ios 8.4 PPSSPP broke the game

### ISSUE THREAD

**Issue by jianmingyong** [hrydgard/ppsspp#8233]
ios 8.4 on my iphone 4s device is now unstable and unable to play.

The new update make my game stuck in main menu and crash.

Also load state also fails to work. Manual save load in main menu is a crash.

I have seen iOS 9 isn't able to play but why iOS 8.4 too?

The game that I was playing is "Class of heroes"

**Comment by asbel123** [comment]
iphone 4s is weak phone for now all developers of apps going iphone 5 and up just get andriod phone less issues u get sd card slot

**Comment by jianmingyong** [comment]
[Update] Dev - Latest and Dev - Working both crashing at main menu.
v1.1.1 build seem to work.

**Comment by unknownbrackets** [comment]
Does this still happen in the latest git build?

-[Unknown]

**Comment by jianmingyong** [comment]
It seem fixed in the latest dev build. Ah much better.

-Closed I guess-
