### ISSUE TITLE
ios sideloading issue

### ISSUE THREAD

**Issue by CoreCreator** [hrydgard/ppsspp#8238]
PhaseScriptExecution CMake\ PostBuild\ Rules build-ios/PPSSPP.build/Debug-iphoneos/PPSSPP.build/Script-83139402ED4F4D47856D0256.sh
    cd /Users/administrator/ppsspp
    /bin/sh -c /Users/administrator/ppsspp/build-ios/PPSSPP.build/Debug-iphoneos/PPSSPP.build/Script-83139402ED4F4D47856D0256.sh

tar -c -C . --exclude .DS_Store --exclude .git -H gnu assets *.png | tar -x -C '/Users/administrator/ppsspp/build-ios/Debug-iphoneos/PPSSPP.app'
tar: gnu: Cannot stat: No such file or directory
tar: Error exit delayed from previous errors.
Command /bin/sh emitted errors but did not return a nonzero exit code to indicate failure

edit: this doesnt seem to affect anything however the later errors do, my device is a 4s on 8.4.1 so no errors, however on 6s simulators the following errors occur

**Comment by CoreCreator** [comment]
i figure id point out my iphone is NOT jailbroken... will ppsspp even work or will dynamic recompiling screw it up?

**Comment by CoreCreator** [comment]
although i realize now that could be because i renamed my xcode to xcode-beta... and i belive thats when the clang errors occured, if no one else finds these errors please close this post, and i found the fix issue button, my appologies

**Comment by CoreCreator** [comment]
also, building on any 6s simulators causes this to appear multiple times

clang: warning: argument unused during compilation: '-headerpad_max_install_names'
clang: warning: argument unused during compilation: '-mfpu=neon'
clang: warning: argument unused during compilation: '-mcpu=cortex-a9'
in different areas

**Comment by unknownbrackets** [comment]
AFAIK, it doesn't work at all on a simulator.

The gnu thing, I don't know, I suspect it's been built for a different version of tar.  If you edit CMakeLists.txt, remove the `-H gnu` part, and re-run `cmake`, does it work?

-[Unknown]

**Comment by unknownbrackets** [comment]
I think `-H gnu` has been removed and this issue has been fixed for a little while.  Please comment if it's still an issue and we can reopen.

-[Unknown]
