### ISSUE TITLE
Love what you've done However

### ISSUE THREAD

**Issue by Dropp3dquick** [hrydgard/ppsspp#8239]
I enjoy Ppsspp very much, I use it on my phone and on my iPad. I was trying to improve my settings for a game by following YouTube videos. I followed one that had me change stuff around in all tabs which made it unplayable. I then followed another video that almost fixed everything. However the problems are still pretty bad. I'm using an iPad 4 I even deleted it and got the 11.1 version, with no luck I still have the same settings. My phone however is flawless zero problems won't touch the settings. What I suggest is either a YouTube channel (which would make you extra $$ from advertisers) or PDFs or videos on your website showing all tabs for different devices. Thank you for reading on considering. I love what's been done so far I never thought it would be possible

**Comment by Dropp3dquick** [comment]
* Thank you for reading and considering

**Comment by Dropp3dquick** [comment]
Forgot to mention my iPad is jail broken pretty sure I got it before it was available on App Store. I followed everythingapplepro s videos and only got the safe jailbreaks. Thank you again hope somebody can direct me on how to fix this, also any recommendations on rooting my note 5 so I can use a controller or any recommendations on syncing a controller with my iPad 4 would be appreciated I have PS3 controllers

**Comment by Dropp3dquick** [comment]
Saw good reviews on several such as six axis but I thought I would ask others what they think

**Comment by unknownbrackets** [comment]
If you are running iOS 9 or higher, it may not work in any game.  So if you upgraded recently, that's the problem.

Otherwise, for settings, our goal is to have the default settings be the best as defaults.  You can tweak some settings to make things faster and have more bugs, or make things slower and have less glitches, but the defaults are meant to be the "best of both worlds."  So my recommendation is to use the defaults if you have issues.

-[Unknown]

**Comment by Dropp3dquick** [comment]
Yeah the only reason I looked into changing the setting was to improve the gameplay for gow however that may have been fixed in the newer versions. I haven't updated to iOS 9 or If i have it still works maybe due to jail break. Is there anyway I can see all the tabs default for an IPad 4 or is there a way to reset to default settings?

**Comment by Dropp3dquick** [comment]
the video I followed had me change stuff in every tab. Another video helped me make it playable again but I still have some issues. If I knew what the defaults looked like on the new version on the iPad 4 I could make it fully functional again. I've tried looking on YouTube but have had zero luck

**Comment by unknownbrackets** [comment]
There's a button under Settings or Developer Tools to reset the settings to the defaults, if I remember correctly.

-[Unknown]

**Comment by Dropp3dquick** [comment]
Hahahah found it thank you very much!

**Comment by vgturtle127** [comment]
Can we close this? I don't think this is an issue, really.

**Comment by Dropp3dquick** [comment]
Yes my bad it was answered the next day

Sent from Yahoo Mail on Android 
 
  On Sun, Dec 6, 2015 at 10:06 AM, Unknown W. Brackets<notifications@github.com> wrote:   
Closed #8239.
