### ISSUE TITLE
Boku no Natsuyasumi 4 mini game hangs in the second time play.

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8241]
The first time going into the mini game without any problem,the second time it hanged.seems it never worked before after trying several old builds.
Debuglog (rename jpg to 7z)
![ppsspplog](https://cloud.githubusercontent.com/assets/3481559/11438327/23aed05c-952f-11e5-8ba8-6d04ed4fb5c2.jpg)

**Comment by daniel229** [comment]
Uncheck I/O on thread or choosing Host for I/O timing method,it hangs even in the first time play.

**Comment by unknownbrackets** [comment]
Hmm, my guess is that something isn't going correctly when unloading the bn4sub module.  Maybe it's zeroing out too much...

-[Unknown]

**Comment by unknownbrackets** [comment]
Nothing improves if you comment out this part of sceKernelModule.cpp, right?

```c++
	if (memoryBlockAddr != 0 && nm.text_addr != 0 && memoryBlockSize >= nm.data_size + nm.bss_size + nm.text_size) {
		DEBUG_LOG(HLE, "Zeroing out module %s memory: %08x - %08x", nm.name, memoryBlockAddr, memoryBlockAddr + memoryBlockSize);
		for (u32 i = 0; i < (u32)(nm.text_size + 3); i += 4) {
			Memory::Write_U32(MIPS_MAKE_BREAK(1), nm.text_addr + i);
		}
		Memory::Memset(nm.text_addr + nm.text_size, -1, nm.data_size + nm.bss_size);

		// Let's also invalidate, just to make sure it's cleared out for any future data.
		currentMIPS->InvalidateICache(memoryBlockAddr, memoryBlockSize);
	}
```

-[Unknown]

**Comment by daniel229** [comment]
It doesn't help.

**Comment by unknownbrackets** [comment]
I think we fixed a few things that didn't reset on restart - does this still happen?

-[Unknown]

**Comment by unknownbrackets** [comment]
I know we fixed the CPU hz not resetting, and I'm hopeful that was causing this issue.

-[Unknown]

**Comment by benderscruffy** [comment]
Doesn't happen any more 
Can be closed
