### ISSUE TITLE
Roms Stopped Loading 

### ISSUE THREAD

**Issue by PSPgamer** [hrydgard/ppsspp#8242]
My ISO files stopped loading up from their file directory, This happened a few days ago. I play the games my iPhone 6 Plus. Can somebody help me figure this out? I tried reinstalling the emulator a couple times and all I got are the same results.

**Comment by i30817** [comment]
Apple broke iOS ability to use JIT on purpose.

**Comment by PSPgamer** [comment]
So what you are telling me is we can no longer use the ppsspp emulator for any kind of Apple iDevices as in never?

**Comment by i30817** [comment]
I'm not a dev. The issue is tracked in #8122 
There are lots of duplicates in the bug tracker now (including yours).

**Comment by asbel123** [comment]
just get new andriod phone next year better than iphone 6s easy to use u can play nds emulator and ps1 and psp fullspeed about nds emulator andriod u can do high resloution.

**Comment by PSPgamer** [comment]
I know, I spent 1300 dollars on this phone and just hate to do all that fighting over a app just to play classic games. :(

**Comment by PSPgamer** [comment]
I'm still running iOS 8.3 and I didn't think iOS 9 app upgrades would effect the OS I run the ppsspp on. The games don't crash at all it's just when I go to games folder on the ppsspp app, they are all not there but they show up when I view them on ifile.

**Comment by PSPgamer** [comment]
I'm still running iOS 8.3 and I didn't think iOS 9 app upgrades would effect the OS I run the ppsspp on. The games don't crash at all it's just when I go to games folder on the ppsspp app, they are all not there but they show up when I view them on ifile.

**Comment by PSPgamer** [comment]
Oops sorry for the repeat.

**Comment by PSPgamer** [comment]
Let me ask you guys something,  are there any PPSSPP 1.1.1 non jail broken zip files that I can manually install myself using ifile or filza and  doesn't have to meet a repo source or anything.   The reason why I ask is because I installed  manually the Sega Saturn and super Nintendo emulator without a source manually.

**Comment by PSPgamer** [comment]
Nevermind I got the ppsspp emulator to work for me again.
