### ISSUE TITLE
Star Ocean First Departure longstanding graphical issues still persistent in vanilla PPSSPP yet nonexistent in Libretro port

### ISSUE THREAD

**Issue by Warriors-Blade** [hrydgard/ppsspp#8244]
I just tested Star Ocean First Departure in the Libretro port of PPSSPP which is a little old since its still on 1.0.1 and surprisingly in the libretro port ran via Retroarch Star Oceans FDs graphical issues regarding invisible sprites and choppy screen movement are nonexistent.

Those issues are still present in the latest vanilla build of PPSSPP in both OpenGL and Direct3D and I am posting this as I think it may be important info for any development for PPSSPP on intel chipsets.

Also the standard screen tearing in vanilla PPSSPP is nonexistent in Retroarch.

Tested on Windows 7 64
Intel chipset laptop

**Comment by unknownbrackets** [comment]
This is on an Intel video card with default settings?  The game works fine on an NVIDIA 9800 GT.

Retroarch just runs PPSSPP, possibly with slightly changed settings.  At most maybe they load OpenGL differently?

-[Unknown]

**Comment by unknownbrackets** [comment]
From discussion on IRC, it sounds like the GL context is created differently, glew is stubbed out, and the window is created differently.  Maybe one of these is making the Intel driver make better decisions.

-[Unknown]

**Comment by Warriors-Blade** [comment]
Yes this is on a Intel chipset laptop with default settings (really can't change anything honestly)

I thought it was important information and wanted to let you all know since I was pretty pleased seeing Star Ocean FD work as intended but it was not in vanilla sadly.

The Retroarch environment? seems to make emulators run better but I am not sure of the details.

**Comment by Hydroque** [comment]
Stencil test? #8171 may be the solution. Which is important to see if it is actually working.

**Comment by hrydgard** [comment]
Is this even still the case?

**Comment by unknownbrackets** [comment]
Even if it is, it might be resolved by Direct3D 11.  I've never experienced this issue, though.

There are reports of issues with Intel cards:
http://report.ppsspp.org/game/ULUS10374_1.00
http://report.ppsspp.org/game/ULJM05290_1.01
http://report.ppsspp.org/game/ULES01154_1.00

However, they give it full marks in graphics.

-[Unknown]

**Comment by hrydgard** [comment]
Alright. Doesn't seem worth investigating more since we indeed now a range of backends to try in case of buggy drivers - pretty sure the bug isn't in our code, anyway.
