### ISSUE TITLE
Brave Story crashed in boss fight

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8252]
Since https://github.com/hrydgard/ppsspp/pull/8240 ,fixed in https://github.com/hrydgard/ppsspp/pull/8246

master build crash and color is wrong
![01](https://cloud.githubusercontent.com/assets/3481559/11531718/dcee09d0-9939-11e5-913f-597eb7877b4b.png)

with https://github.com/hrydgard/ppsspp/pull/8246 ,color is correct.
![02](https://cloud.githubusercontent.com/assets/3481559/11531719/dcef99d0-9939-11e5-9196-8ebe93aa7ee2.png)

Stack trace
![03](https://cloud.githubusercontent.com/assets/3481559/11531854/d4fbcd1a-993a-11e5-9f65-6ebe686b55e1.png)

**Comment by asbel123** [comment]
i got no problem on my samsung galaxy s6 edge i use disable slow effects to speed this game crazy i finsh the game on the latest version no crashes on my phone.

**Comment by asbel123** [comment]
maybe its windows problem

**Comment by daniel229** [comment]
Right, disabling slow effects won't be affected.

**Comment by unknownbrackets** [comment]
Strange that the CLUT change would make splines crash.  Maybe `gpu->PerformMemoryDownload(clutAddr, bytes);` is somehow downloading too much (like the whole framebuf when sequential transfers are detected?)

In that case maybe we need another API; #8246 makes it do that less often but it doesn't make it impossible.  Specifically, if you use texture scaling it will still do it the old way.

If you remove this code in Framebuffer.cpp, does the problem go away?

```c++
			const static int FREQUENT_SEQUENTIAL_COPIES = 3;
			static int frameLastCopy = 0;
			static u32 bufferLastCopy = 0;
			static int copiesThisFrame = 0;
			if (frameLastCopy != gpuStats.numFlips || bufferLastCopy != vfb->fb_address) {
				frameLastCopy = gpuStats.numFlips;
				bufferLastCopy = vfb->fb_address;
				copiesThisFrame = 0;
			}
			if (++copiesThisFrame > FREQUENT_SEQUENTIAL_COPIES) {
				gameUsesSequentialCopies_ = true;
			}
```

I realize the color might still be wrong, but I'm more concerned about the crash.  Also, can you upload a save or savestate?

-[Unknown]

**Comment by daniel229** [comment]
save and the savestate
https://drive.google.com/folderview?id=0BzGZGDfFE68zM09hc2dKc1BSZkE&usp=sharing

**Comment by daniel229** [comment]
It's helped by removing that code.
