### ISSUE TITLE
(Since v1.1.1) All Sora no Kiseki/Trails in The Sky titles have been (conditionally) broken. 

### ISSUE THREAD

**Issue by sewer56lol** [hrydgard/ppsspp#8253]
Affects: All platforms/devices (tested 3).
Last version to work fine: 1.0.1

Old status: Perfect (0 emulation issues/perfect emulation)
New status: Playable (Critical bug)

Description: Engine emulation bug. Sound will often cut after battles. (Temporary fix is to save and load state when this occurs). Once this effect is triggered any new loads of 'crucial' data such as entering a new area never loaded before would cause game (and emulator) to hang due to load errors.

**Comment by daniel229** [comment]
It seems has been fixed recently,can you try the latest build from http://buildbot.orphis.net/ppsspp/index.php

**Comment by sewer56lol** [comment]
Didn't know of the buildbot (and am too lazy to build) - will test with nightly.
