### ISSUE TITLE
Screen rotation is not correct

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8255]
So the controller is wrong too.Since https://github.com/hrydgard/ppsspp/pull/8130

Portrait
the latest build
![02](https://cloud.githubusercontent.com/assets/3481559/11578797/8ac61122-9a63-11e5-98e6-f7cc681763d1.png)

old build
![03](https://cloud.githubusercontent.com/assets/3481559/11578798/8acf0a48-9a63-11e5-827b-30596e44e487.png)

**Comment by hrydgard** [comment]
Oh, I didn't notice. I'll fix it up soon. I assume it's just GL, not D3D?

**Comment by daniel229** [comment]
Right,just GL.

**Comment by unknownbrackets** [comment]
Is it just as simple as using:

```c++
		case ROTATION_LOCKED_HORIZONTAL180: rotation = 4; break;
		case ROTATION_LOCKED_VERTICAL: rotation = 6; break;
		case ROTATION_LOCKED_VERTICAL180: rotation = 2; break;
```

To flip the two?

-[Unknown]

**Comment by daniel229** [comment]
That works.
