### ISSUE TITLE
Burst Error Eve the First an underscore after a line

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8257]
Since https://github.com/hrydgard/ppsspp/pull/5581

![01](https://cloud.githubusercontent.com/assets/3481559/11582391/4ceabc60-9a89-11e5-8731-dafb2bf25d62.png)
![02](https://cloud.githubusercontent.com/assets/3481559/11582392/4cf4ceee-9a89-11e5-9122-162a893f301d.png)

**Comment by daniel229** [comment]
Another affected game.
![01](https://cloud.githubusercontent.com/assets/3481559/11606980/4d7573d6-9b70-11e5-92e2-8989d7d64b60.png)

**Comment by unknownbrackets** [comment]
Is this using PSP fonts?  Want to rule out different glyphs.

Are all of these supposed to show as spaces?  It could be a difference in the font libraries these particular games are using; maybe it's the error character and it defaults differently, or something.

-[Unknown]

**Comment by daniel229** [comment]
Burst Error Eve the First using the psp's font.
Zettai Zetsumei 3 using the iso's font.
Yes,it's supposed to show as spaces.

**Comment by unknownbrackets** [comment]
Well, http://www.fileformat.info/info/unicode/char/5f/index.htm

It seems like it's expecting the default alt char to be something different.  Maybe it depends on the font or game region.  Sounds like this calls for more tests.
