### ISSUE TITLE
Snapdragon 410 (64-bit cpu) , only running in ARMv7-compatibility mode

### ISSUE THREAD

**Issue by jumpertwo** [hrydgard/ppsspp#8260]
not really sure what goes wrong here
![screenshot_2015-12-07-12-23-01](https://cloud.githubusercontent.com/assets/3816337/11626105/6c66e7fe-9ce0-11e5-8c4a-87cf2db155d2.png)

**Comment by hrydgard** [comment]
Seems you closed before your screenshot upload finished?

That's odd, anyway...

**Comment by jumpertwo** [comment]
sorry, bad connection. Umh, I'm on Lollipop 5.1.1

**Comment by hrydgard** [comment]
custom rom or stock OS?

There's a comment here suggesting that it might run a 32-bit OS, and if so it will not be possible to run 64-bit PPSSPP:

http://laptopmedia.com/smartphone-review/motorola-moto-g-3rd-gen-2015-review-the-new-flagship-in-the-mid-range/

**Comment by jumpertwo** [comment]
not a real test but
checking some references, linker64 is missing
moto g : 
![screenshot_2015-12-07-13-19-46](https://cloud.githubusercontent.com/assets/3816337/11626716/3e3554e2-9ce5-11e5-97f7-b2ac2b910010.png)

**Comment by jumpertwo** [comment]
Samsung s6 : 
![img-20151207-wa0007](https://cloud.githubusercontent.com/assets/3816337/11626741/66b74f38-9ce5-11e5-9fe7-682830f99606.jpg)

I guess OS version is 32 bit. I don't really understand why using such a marketing strategy, anyway thank you for checking
