### ISSUE TITLE
Can't complete atlas build stage due to ARIALUNI.ttf

### ISSUE THREAD

**Issue by ProfessorKaos64** [hrydgard/ppsspp#8263]
[In this line](https://github.com/hrydgard/ppsspp/blob/624d9003a3ab32db46978b1619fa49d7b738873c/atlasscript.txt#L3) of the atlas script txt file, ARIALUNI is attempted to be loaded from C:\Windows?

Error:
```
Image source_assets/image/psp_display.png with effect copy (0)
TTF info: 1045 glyphs, 00000a19 flags, 2048 units, 0 strikes
Failed to load font file C:/Windows/Fonts/ARIALUNI.ttf
```

I am issuing the command:
```
./ext/native/tools/build/Atlas chair atlasscript.txt ui 8888
```

From [here](https://github.com/hrydgard/ppsspp/blob/master/buildatlas.sh). Am I missing something obvious here?  I am using the [Vivid PPA](https://launchpad.net/~ppsspp/+archive/ubuntu/testing) debian/ set of rules/control and so forth. 

* [build script](https://github.com/ProfessorKaos64/SteamOS-Tools-Packaging/blob/brewmaster/build-ppsspp.sh)
* [build log](http://sprunge.us/WFjT)

```
Image source_assets/image/5.png with effect copy (0)
Image source_assets/image/6.png with effect copy (0)
Image source_assets/image/psp_display.png with effect copy (0)
TTF info: 1045 glyphs, 00000a19 flags, 2048 units, 0 strikes
font rasterized.
Resolving...
Writing .ZIM 512x512 RGBA8888...
Writing .PNG ui_atlas.zim.png
Done. Outputting source files ui_atlas.cpp/h.
debian/rules:36: recipe for target 'override_dh_auto_build' failed
make[1]: Leaving directory '/home/desktop/build-ppsspp-temp/ppsspp'
debian/rules:29: recipe for target 'build' failed

```

**Comment by unknownbrackets** [comment]
The atlasscript.txt is not really meant to be a "works on every platform" type configuration, because 99% of the time you really have no need to build it whatsoever.

You'll need to modify the sample paths in that file if you want to compile it.  I don't think this is an issue really, so I'm going to close it.

My recommendation is to just use the shipped atlas files.  If that somehow seems terrible to you, keep in mind there's both ppge and ui.

-[Unknown]

**Comment by ProfessorKaos64** [comment]
Sorry to ask again since this closed, but is it then safe to omit that build step in rules file?

**Comment by Bigpet** [comment]
@ProfessorKaos64 that step is needed to build https://github.com/hrydgard/ppsspp/blob/master/assets/ui_atlas.zim and https://github.com/hrydgard/ppsspp/blob/master/assets/ui_atlas_lowmem.zim , so if any changes are made to the ui images/buttons and/or fonts they need to be rebuild, so a complete build can't skip that step.
You are free to use any font you want though. Roboto-Condensed is the main font for western scripts afaik. Arial is only used as a fallback for unicode glyphs not present in Roboto.

**Comment by ProfessorKaos64** [comment]
Ok, I'll modify that font path to one that works, maybe try out Roboto-Condensed in its place.

**Comment by ProfessorKaos64** [comment]
@Bigpet , so would it be best to substitute Roboto-Condensed in [atlasscript.txt](https://github.com/hrydgard/ppsspp/blob/624d9003a3ab32db46978b1619fa49d7b738873c/atlasscript.txt#L3) for ARIALUNI, comment the line out, or as you say, just skip that step (./ext/native/tools/build/Atlas chair atlasscript.txt ui 8888)? from the script file? I am just looking for the safest way to build, based off of the github master tree. I apologize for being a bit naive here on a proper solution.

**Comment by ProfessorKaos64** [comment]
@Bigpet , finally got around to trying this again. I applied [this patch](https://github.com/ProfessorKaos64/SteamOS-Tools-Packaging/blob/64e8245d188543814eeb57c71e8cd0cbb3d2556f/ppsspp/debian/patches/font-patch) that swapped the ARIALUNI font out, but I still get errors where in there is a lot of "can't find character XXXX". Is this patch wrong? I wasn't sure about the text after Roboto-Condensed.ttf

Build log:
http://sprunge.us/QiQF

**Comment by LunaMoo** [comment]
@ProfessorKaos64 in atlasscript.txt you've set a lot of different character sets, but provided a font that doesn't have most of them that's why you get those warnings.

 Just change "UWEhkcRGHKVTe" to "UWER" for roboto condensed or find a font that support all those character sets you want, I guess you could use multiply fonts as well setting different character sets for each. through frankly I never really tried as if I have any need for rebuilding atlas I tend to only use "U" for us ascii to keep it small and clean since althrough english not my native is really the only language I end up using in ppsspp anyway.

 In case you don't understand what those letters mean - check https://github.com/hrydgard/ppsspp/blob/master/ext/native/tools/atlastool.cpp#L718 and it should be clear.

**Comment by ProfessorKaos64** [comment]
@LunaMoo , thank you very much for your reply and the letter definitions, that was I was looking for so I can understand this. If you don't rebuild atlas, do you mind (if you do packaging) linking your rules file? Again, I appreciate the response.

**Comment by LunaMoo** [comment]
You're welcome. And sorry not really using linux, so I don't have any rules file.

 Not really sure why you're even trying to build atlas if the only change you're effectively making is removing of glyphs added from arial uni font. If you want to just build ppsspp with default fonts / images it comes with you shouldn't really need to use atlas tool at all as ppsspp source comes with all the assets it needs already.

**Comment by ProfessorKaos64** [comment]
[This](https://github.com/ProfessorKaos64/SteamOS-Tools-Packaging/edit/brewmaster/ppsspp/debian/rules) is the rules file, where the scripts are kicked off, as you can see. Wonder if I could just omit the step there for the atlas/zim operations. Unknownbrackets above said

>However you should be rather safe to ignore that step in a regular pull&build since the atlas in the repo should fit the generated header that's in the repo (otherwise windows builds would look wonky too).

Essentially that is what I am doing, rebuilding the git source (for Debian/SteamOS).

**Comment by LunaMoo** [comment]
Yeah well just skip it, we only keep fonts and some small images used in ui there and whenever it changes(which already is very rare) it will also come with new atlas so you will never have to rebuild it.

 Unless developing some changes that directly affects it on your own and for your own need/testing as if you would plan on opening a pull request with rebuilt atlas, someone else who has the fonts we're using now would have to do that part for you anyway.

**Comment by ProfessorKaos64** [comment]
```
g++ -c -m64 -pipe -Wno-unused-function -Wno-unused-variable -Wno-strict-aliasing -fno-strict-aliasing -Wno-unused-parameter -Wno-multichar -Wno-uninitialized -Wno-ignored-qualifiers -Wno-missing-field-initializers -msse2 -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -O3 -ffast-math -fPIC -std=c++0x -Wall -W -D_REENTRANT -DUSING_QT_UI -DUSE_FFMPEG -DSHARED_SNAPPY -DSHARED_ZLIB -DSHARED_LIBZIP -D_M_X64 -D_ARCH_64 -DPPSSPP_GIT_VERSION="\"1.2.1.0\"" -D__STDC_CONSTANT_MACROS -DQT_NO_DEBUG -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -I../Common -I../ffmpeg/linux/x86_64/include -I../../ppsspp-1.2.1+ds+bsos1 -I../ext/native -I../Core/MIPS -I../ext/xbrz -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I.moc/Core -o .obj/Core/PSPDialog.o ../Core/Dialog/PSPDialog.cpp
In file included from ../Core/Dialog/PSPDialog.cpp:23:0:
../../ppsspp-1.2.1+ds+bsos1/Core/Util/PPGeDraw.h:22:24: fatal error: ppge_atlas.h: No such file or directory
 #include "ppge_atlas.h"
                        ^
compilation terminated.
```

That file is in: `Core/Util/`.  Usually my guess is it is being stripped out somewhere. 

[build log](http://sprunge.us/QVeS)

**Comment by ProfessorKaos64** [comment]
Think I got it with overriding dh clean, since that is necessary for cleaning out those files for rebuilding, which I am not doing for those. I'll how this goes. Again, thank you for being kind and helping.
