### ISSUE TITLE
Bugs fix asap please

### ISSUE THREAD

**Issue by teengame12** [hrydgard/ppsspp#8264]
Ppsspp Dev latest and all other packages for ppsspp crash while game is installing/loading. This happened to naruto shippuden ultimate ninja impact and also dragon ball z shin

**Comment by ppmeis** [comment]
As I told you before:

Please don't use issue tracker for this kind of posts. You can use official forum instead.

@hrydgard this should be closed.

**Comment by hrydgard** [comment]
PPSSPP does not currently work on iOS 9.x.

**Comment by teengame12** [comment]
Okay thank you when it run on iOS 9.x.
