### ISSUE TITLE
Anti-piracy/CFW measure prevents iDOLM@STER SP's DLC and Office Mode from being accessed. 

### ISSUE THREAD

**Issue by internetakias** [hrydgard/ppsspp#8266]
![uljs00169_00008](https://cloud.githubusercontent.com/assets/5077063/11722192/27d0aa66-9f70-11e5-9ede-cef9c4164e86.png)
Like the title says, trying to access Office Mode in any of the iM@S SP games (Perfect Sun, Missing Moon and Wondering Star) that have the "Download Plus" update gives the error screen above, which translates to "Couldn't detect the system software. This game/software may run on system software that is not supported." (Translation was provided by a friend of mine).
After doing a bit of digging I discovered that the Download Plus update implements an anti-custom firmware mechanism that blocks CFW users from using Office Mode and DLC released after the update. (More info here: http://www.project-imas.com/wiki/THE_iDOLM@STER_SP_DLC)

EDIT: JPCSP is able to access the mode just fine, but like I say in the last comment, recent versions of the emulator can't load the DLC in both the base game and the updated version for some reason.

**Comment by ppmeis** [comment]
Did you try using I/O with simulate UMD Delay and force clock sync under settings? I now Dj Max has a cfw detection and is bypassed with these options.

**Comment by internetakias** [comment]
I'm afraid that didn't work. Thanks, though.

**Comment by ppmeis** [comment]
Checking about this game, all three games need to be patched on real PSP to run properly (talking about CFW, of course original UMD works well).

So I don't know if we could do anything with this issue.

**Comment by internetakias** [comment]
Really? I don't remember seeing anything about that.

**Comment by internetakias** [comment]
Anything on this?
Here's a log of launching the game and going into office mode
http://pastebin.com/X2cQsBxq

**Comment by internetakias** [comment]
Disabling DLC decryption fixes this on JPCSP
https://8ch.net/imas/res/674.html#4419

**Comment by internetakias** [comment]
Just tested myself on JPCSP v0.7 rev3736, and it tuns out disabling DLC decryption actually helps the DLC show up, and that the AP measure itslef is bypassed whether it's on or off.

**Comment by internetakias** [comment]
I forgot to mention that the JPCSP build I posted above was the last build I could find that loaded the DLC. While newer builds can still go into office mode just fine, they can't load the DLC itself in both the base game and the Download Plus update.
