### ISSUE TITLE
7th dragon 2020 input name not functions properly(android)

### ISSUE THREAD

**Issue by aki21** [hrydgard/ppsspp#8271]
7th dragon won't show let me input name for character,had this issue for a while.
![screenshot_2015-12-14-03-25-25](https://cloud.githubusercontent.com/assets/4054311/11768885/5e8f9092-a215-11e5-9207-929d27851a6e.png)
![screenshot_2015-12-14-03-25-16](https://cloud.githubusercontent.com/assets/4054311/11768887/73a44e32-a215-11e5-92b5-3c3ca05ba3f4.png)
![screenshot_2015-12-14-03-23-51](https://cloud.githubusercontent.com/assets/4054311/11768889/8247754a-a215-11e5-963e-bdcb5f9b132b.png)
As the pic attach,I can input the name but it won't show as pic 1,the name does exist in savedata
Sorry cause I'm using phone to post this,kinda messy and not enough info
,pls close issue if this had been post

**Comment by unknownbrackets** [comment]
You probably need to switch to "English full width" (press L) - does that make it work?

-[Unknown]

**Comment by aki21** [comment]
Yup it work like charm,thank,I don't know why I can input normally,but that setting work,can close if you like.
