### ISSUE TITLE
Directional keys in menu can get stuck

### ISSUE THREAD

**Issue by xperia64** [hrydgard/ppsspp#8275]
I have found that on my mouseless, touchscreenless, Nvidia Shield TV, if I hold any directional button in PPSSPP's in game menu, press back and return to the game, and open the menu again, PPSSPP thinks the button is pressed and the cursor continues to move in that direction. It is difficult to get out of once it happens. This is with a very recent buildbot build g99fe098

**Comment by unknownbrackets** [comment]
This is really the same as #4616, even though that is about keyboard access on Windows.  It's the same underlying problem.  I'm closing this as a duplicate.

-[Unknown]
