### ISSUE TITLE
Draw lines and points using triangles

### ISSUE THREAD

**Issue by unknownbrackets** [hrydgard/ppsspp#8276]
Some games use lines and points (not a ton.)  At higher resolutions than 1x, these draw incorrectly, especially on mobile.

We currently use glLineWidth and glPointSize to emulate these on desktop.  However, glLineWidth is deprecated - it won't work in Core Profile (Mac) and is unsupported in GLES.  Further, lines still draw incorrectly even with this - especially at non-even resolutions.

See #8270 for more discussion on how to technically construct lines/points using polygons.  Ideally some testing on how these work in transform mode (especially width) might make sense.

This would fix #3871 and #3332.

As noted in #3332, line caps can be a concern.

-[Unknown]

**Comment by ADormant** [comment]
@unknownbrackets @hrydgard 

I think it can be emulated with geometry shaders.

https://github.com/simias/rustation/commit/f6514ed5ad1459e7170c1d019dccff09f76ad986
https://github.com/dolphin-emu/dolphin/pull/1735
https://github.com/dolphin-emu/dolphin/pull/1706
https://github.com/dolphin-emu/dolphin/pull/2343
https://github.com/dolphin-emu/dolphin/pull/1735
https://github.com/dolphin-emu/dolphin/pull/1439
https://github.com/dolphin-emu/dolphin/pull/1788
https://github.com/dolphin-emu/dolphin/pull/1716
https://github.com/dolphin-emu/dolphin/pull/1612
https://github.com/dolphin-emu/dolphin/pull/1747

**Comment by unknownbrackets** [comment]
I think even GLES 3.1 doesn't include support for geometry shaders, so one way or another we need a solution that doesn't require them.  At that point the question is - do we build two solutions to this problem, or just one?

-[Unknown]

**Comment by ADormant** [comment]
Though OpenGL ES 3.2 does have geometry shaders.

**Comment by hrydgard** [comment]
That's true, but hardly any devices support ES 3.2 yet, there will be devices with ES 3.1 or lower around for the foreseeable future so we still need a non-geometry shader solution.

**Comment by ADormant** [comment]
https://github.com/simias/rustation/commit/f6514ed5ad1459e7170c1d019dccff09f76ad986

**Comment by ADormant** [comment]
What about this https://github.com/simias/rustation/commit/f6514ed5ad1459e7170c1d019dccff09f76ad986

**Comment by unknownbrackets** [comment]
Not really, that seems to be doing what we currently do: using glLineWidth or something, which is unsupported on GLES.  It also seems to be inaccurate for our needs.  Also it's written in Rust.

-[Unknown]

**Comment by hrydgard** [comment]
We already sort-of do this for RECT primitives, it would not be very hard to add triangulation of points and lines, a nice little project.

**Comment by hrydgard** [comment]
Geometry shaders are starting to show up on mobile devices using Vulkan (for example, my Galaxy S8 has them) but still, we probably shouldn't use them for this, instead we'll just do the same we do with rectangles - transform them in software and split into triangles, as discussed.

@unknownbrackets , you had some WIP code for this, right? You removed it from #8270 , and now I can't find it.

**Comment by unknownbrackets** [comment]
Oh, sorry, yes.  It's not doing many things, I was just trying to get it to draw the lines in Ridge Racer (#8509) as a test but didn't account for diagonal lines (perpendicular unit vector for width, I guess?), or more importantly transform (could possibly just multiply to get the perpendicular unit vector?)

Pushed it here after a quick rebase:
https://github.com/hrydgard/ppsspp/compare/master...unknownbrackets:lines

But the speedometer wasn't working iirc and I forgot about it...

-[Unknown]

**Comment by hrydgard** [comment]
Thanks.

Getting a perpendicular vector is very easy:   rotate90(x, y) = (-y, x). So not much complicated math needed really.

**Comment by unknownbrackets** [comment]
Right, but wasn't so sure about transform (since we want to do that in screen coordinates - which software transform doesn't do.)  I think you'd suggested just transforming the entire line into through, which I haven't really thought through.

-[Unknown]

**Comment by hrydgard** [comment]
Well we already do it with rectangles. We put the two points defining them through software transform and out they come in screen space, at which point we expand them in 2D. Same goes for lines and points.

**Comment by Panderner** [comment]
Hi there But how about Test Drive Unlimited minimaps lines?

Latest Build:
![Screenshot (49)](https://user-images.githubusercontent.com/37503397/142639160-6ff36a61-0a1c-4cf3-8533-2b431801abed.png)

Stable 1.12.3:
![Screenshot (50)](https://user-images.githubusercontent.com/37503397/142639247-24498a62-7274-41e8-9039-1cb5c7095721.png)

Vulkan 1.12.3:
![Screenshot (51)](https://user-images.githubusercontent.com/37503397/142639500-c6485b35-7b26-4444-b84a-374830cf0240.png)

**Comment by unknownbrackets** [comment]
I tried this frame dump on a PSP, but there's some post-processing at the end which seems to be pulling from a previously renderered frame, and so it's hard to compare.  Just noting for later.

-[Unknown]

**Comment by Panderner** [comment]
Drawing Lines using triangles is a bad idea for Echochrome and Test Drive Unlimited Mini-map, see (#15556)

**Comment by hrydgard** [comment]
Nah, it's a good idea, just seems like there's some bug to fix in the implementation.

**Comment by unknownbrackets** [comment]
Points and lines are drawn using triangles now.  There's still some things that could be improved, but there are already other issues open for them.  I'm going to close this.

-[Unknown]
