### ISSUE TITLE
Crashes/Turning Black Screen all Games Mac

### ISSUE THREAD

**Issue by akosimarvin** [hrydgard/ppsspp#8287]
hi, i just want to add this issue.

i downloaded the Dev-Latest for Mac, and when i try to play i keeps crashing or turning into black screen after i pause the applicatiion.

current version= v1.1.1-383-gf434be3

tnx.

**Comment by unknownbrackets** [comment]
I may have fixed this in 5ff7781a3c2ab10bf800767503019f785b0f1864, sorry.  Could you try again when that builds?

-[Unknown]

**Comment by unknownbrackets** [comment]
I'm pretty sure that was the fix.  If you're still experiencing this issue, please comment and we'll reopen.

-[Unknown]
