### ISSUE TITLE
Texture Scaling setting no longer works properly [affect only some games]

### ISSUE THREAD

**Issue by bennywan24** [hrydgard/ppsspp#8290]
In the newer version of PPSSPP (v 1.1.1), some part of a game's graphic (most noticeably Character Portrait Sprites) Texture Scaling does not apply itself when selected; no matter what associated settings are chosen (Upscale Level, Upscale Type, Deposterize). I've refreshed several times, move onto a different portrait, close the program etc., issue persist even with every other settings at default.

Seems to only affect some games. The game which I found this problem is at:
   Corpse Party: Book of Shadows (USA) , look for differences in the center girl's sprite.
      - Before:   http://imgur.com/gEpWJpt
      - After:   http://imgur.com/xFI1lbr

After some experimenting, I found out that the Texture Scaling over the character sprite does apply eventually, but take way TOO long in doing so.

Texture Scaling works no problem (where the effect was basically instant) in the earlier version that I was using (v1.0.1), I even tried copying my settings from the old version to the new version, but it didn't change the outcome at all.

Old settings for Texture Scaling are:
- Upscale Level : Auto
- Upscale type : xBRZ
- Deposterize : on

Computer:
Windows 8

Tried both
NVIDIA GeForce GTX 860M  &  Intel HD Graphic 4600
in OpenGL

EDIT: This issue only seem to be present when using OpenGL as backend, Direct3D9 is unaffected.

**Comment by unknownbrackets** [comment]
Do you have lazy texture hashing on or off?

Normally this means it has detected a frequent change in that texture, so it's avoiding rescaling it.  Do the character portraits move and animate at times?  It may even be changing a part of the texture not visible on screen.

Before, we were sometimes scaling too often, which in some games caused huge slowdowns.  So we did very intentionally make a change here.

-[Unknown]

**Comment by bennywan24** [comment]
Thanks for replying so quickly!

As for your questions:
" Do you have lazy texture hashing on or off? " - I didn't, but it didn't make a difference in this case.
" Do the character portraits move and animate at times? " - The character portraits themselves are static, they only change when a new portrait replace the old one.
" It may even be changing a part of the texture not visible on screen. " - that's interesting... could this maybe be a hint?

I did some more test, found out the debug statistics are MOSTLY the same BEFORE ( http://imgur.com/aIO71zJ ) the took effect Texture Scaling & AFTER ( http://imgur.com/2JHc40n ).



On a side note, I tested Texture Scaling with Lazy Texture Hashing on a game with rapidly moving sprites ( Dai-2-Ji Super Robot Taisen Z Hakai-hen ), it seems to be work fine... 

I've also tested (without Lazy Texture Hashing) that game under these conditions:
- Upscale Level : Auto
- Upscale type : xBRZ
- Deposterize : on
at Fullscreen (1920 x 1080), 
occasionally there will are some slow-down. However, they are very minor and only last like half a second. xBRZ seems to be the the least laggy Upscale type. Also, for that particular instance of Texture Scaling, there seems to be no differences between the two PPSSPP versions...?

**Comment by unknownbrackets** [comment]
Well, we already had heuristics to prevent rapidly changing textures from taking down your computer.  While zBRZ is fairly fast and optimized, it's still not something modern computers can handle doing for a bunch of textures every single frame.  We cache it heavily.  Where we can't cache, we disable.

It might be that we're misdetecting the height of the texture initially, like in #8012.  Hmm.

-[Unknown]

**Comment by unknownbrackets** [comment]
Has it improved now in the latest git build?

Sprites that move are not always an issue.  If the game uses a sprite map, it's fine.  The question is if the actual texture data is modified constantly by the game, because then it constantly needs to be uploaded.  Sometimes it's hard to tell from just looking at the results of the rendering.

-[Unknown]

**Comment by unknownbrackets** [comment]
I'm going to close this - we haven't heard back, and improvements have been made in this area.  If it's still happening, please feel free to comment and we'll reopen.

-[Unknown]

**Comment by bennywan24** [comment]
Hello, OP here. Sorry for the inactivity, it seems like I didn't notice you posted a response after 23 Dec 2015 and this issue just slipped off my mind.

And yes, the original issue was solved [ no texture up-scaling in Corpse Party: Book of Shadows (USA) ], thank you very much :)

**Comment by unknownbrackets** [comment]
Great, thanks for confirming.

-[Unknown]
