### ISSUE TITLE
Function Hash is not written to the knownfuncs.ini

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8295]
Last working build is v1.0.1-891-g1c67de0 , v1.0.1-898-gbb96478 is not working.

**Comment by unknownbrackets** [comment]
This must be somehow Windows 10 specific or something...?  It works for me.

For me, if I remove the memstick/PSP/SYSTEM/knownfuncs.ini file, it gets recreated when I load a game (as long as I have `FuncHashMap = True`.)  It also seems to get updated.

Is it logging anything, like "Could not store hash map" or similar?

-[Unknown]

**Comment by daniel229** [comment]
Windows 7 also not work for me.It just get knownfuncs.ini file modified time update but nothing written to it.I don't see any log like that。

**Comment by unknownbrackets** [comment]
So if you delete it, load a game, and name some functions things, it creates a 0 byte file but writes nothing?  Hmm.  That isn't happening for me.

Note that it won't save things that are already "known" in PPSSPP, hardcoded.

You can try changing this, in `Core/MIPS/MIPSAnalyst.cpp`:

```c++
		for (auto it = hashMap.begin(), end = hashMap.end(); it != end; ++it) {
			const HashMapFunc &mf = *it;
			if (!mf.hardcoded) {
				if (fprintf(file, "%016llx:%d = %s\n", mf.hash, mf.size, mf.name) <= 0) {
					WARN_LOG(LOADER, "Could not store hash map: %s", filename.c_str());
					break;
				}
			}
		}
```

To:

```c++
		for (auto it = hashMap.begin(), end = hashMap.end(); it != end; ++it) {
			const HashMapFunc &mf = *it;
			if (!mf.hardcoded) {
				NOTICE_LOG(HLE, "Writing line for hash=%016llx", mf.hash);
				if (fprintf(file, "%016llx:%d = %s\n", mf.hash, mf.size, mf.name) <= 0) {
					WARN_LOG(LOADER, "Could not store hash map: %s", filename.c_str());
					break;
				}
			} else {
				NOTICE_LOG(HLE, "SKIPPING line for hash=%016llx", mf.hash);
			}
		}
```

And see what it logs?

-[Unknown]

**Comment by daniel229** [comment]
After changing that code,it is working now.
log
https://gist.github.com/daniel229/4c1e4adc391497fae82c

**Comment by unknownbrackets** [comment]
Hmm... some kind of optimization issue?  What about:

```c++
		for (const HashMapFunc &mf : hashMap) {
			if (!mf.hardcoded) {
				int err = fprintf(file, "%016llx:%d = %s\n", mf.hash, mf.size, mf.name);
				if (err <= 0) {
					WARN_LOG(LOADER, "Could not store hash map: %s (write failure)", filename.c_str());
					break;
				}
			}
		}
```

-[Unknown]

**Comment by daniel229** [comment]
It seems the not working build is download from the buildbot,if build by myself and it's working.

**Comment by unknownbrackets** [comment]
Oh.  Well, that's not great.

Hmm, the buildbot is using 14.0.23107.0.  I don't know why this would be different, that's the same version I'm using locally.  Are you using 32 or 64 bit when you download?

-[Unknown]

**Comment by daniel229** [comment]
That code also works.

Or the vs2015 bug and fixed in the update1,I just update it a few date ago.

**Comment by unknownbrackets** [comment]
I'm not using Update 1 yet (and neither is the buildbot.)  Hmm.

-[Unknown]

**Comment by daniel229** [comment]
I am using 64bit build.

**Comment by daniel229** [comment]
Either 32bit or 64bit from buildbot is not working for me.

**Comment by unknownbrackets** [comment]
This problem seems to have mysteriously stopped happening, probably because of a buildbot update of some kind.

-[Unknown]
