### ISSUE TITLE
FF4 the BGM of the Chocobo forest has a noise when it looping

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8298]
Since https://github.com/hrydgard/ppsspp/pull/8190

**Comment by unknownbrackets** [comment]
Hmm, I'll probably need to create a test for it...

https://github.com/hrydgard/ppsspp/pull/8190/files#diff-a4d8150342953ac0053b961c4601e20fR739

Could you add a `NOTICE_LOG(HLE, "%08x and %08x", firstSampleoffset, largerOffset);` here?  Maybe my assumption that the second is always larger is wrong...

-[Unknown]

**Comment by daniel229** [comment]
It's
```
36:41:523 MyThread-Sou N[HLE]: HLE\sceAtrac.cpp:741 00000bee and 00000ca6
```

**Comment by unknownbrackets** [comment]
This sounds okay to me now in the latest git build, but I'm not always the best at hearing these things.

-[Unknown]

**Comment by daniel229** [comment]
Yeah,looks fixed now.
