### ISSUE TITLE
Depth Range Hack options is disappeared

### ISSUE THREAD

**Issue by zminhquanz** [hrydgard/ppsspp#8302]
![image](https://cloud.githubusercontent.com/assets/11285640/11998687/c7893a0a-aadd-11e5-99b2-bafe7fc02649.png)

Can you explain the problem to have do this ?

**Comment by vsub** [comment]
It's hardcoded since v1.1.1-302-g5b21c1a for the games that need it(one or two I think)
https://github.com/hrydgard/ppsspp/pull/8174

**Comment by hrydgard** [comment]
Do you still need it for some game? If so just add the game ID to assets/compat.ini as you can see in #8174 indeed, and send a pull request.
