### ISSUE TITLE
Sword Art Online- Character missing body parts

### ISSUE THREAD

**Issue by Mark9804** [hrydgard/ppsspp#8313]
![screenshot_2015-12-27-13-32-10](https://cloud.githubusercontent.com/assets/9006264/12008987/ef39eedc-ac9f-11e5-8cef-d286d4d2cc6c.png)
Tested in the latest version of PPSSPP gold from Google Play. Since it's a new game I'll try later if a equipment change can fix.

**Comment by unknownbrackets** [comment]
Try default settings.  Also, try 1x render resolution.  It's possible something like this could maybe happen if you ran out of video memory on your device.

-[Unknown]

**Comment by daniel229** [comment]
It's the disable alpha test problem if I recall correct.

**Comment by Mark9804** [comment]
After changing equipment the graphics are back. Maybe they just don't load
automatically?

**Comment by unknownbrackets** [comment]
Hmm, not sure.  If it requires changing equipment on the PSP it sounds like a bug in the game.

But yeah, disable alpha test could cause this, I think.  Going to close unless there are further reports.

-[Unknown]
