### ISSUE TITLE
Final Fantasy IV The Complete Collection (ULUS10560) error code 80110327

### ISSUE THREAD

**Issue by ofry** [hrydgard/ppsspp#8329]
OS: Windows 8.1 Professional.
PPSSPP v1.1.1-485-g84216ba

Now data install goes fine.

But I found another bug.

Steps to reproduce:

1) Start the game, choose "Data install"
2) Try to launch Final Fantasy IV, go to Bestiary
3) Now you will get "error code 80110327"

![ulus10560_1 00_1](https://cloud.githubusercontent.com/assets/11790863/12028565/3a6d3d14-adea-11e5-9bf8-2007be0c2ad8.jpg)

**Comment by ofry** [comment]
It's related to issue #7903

**Comment by unknownbrackets** [comment]
Delete the data first, it's corrupted by the earlier bugs.  That's what 0x80110327 essentially means.

Bestiary loads fine for me.  But ULUS10560Install (or similar, per region) must have a PARAM.SFO in it, etc.  Just delete the entire directory first, and then do the data install over again.

-[Unknown]

**Comment by ofry** [comment]
I tried it, nothing happened. Same error.

It not happened if you will start game, and make one save :) But in first launch (without any savedata) occurs this error.

**Comment by unknownbrackets** [comment]
How sure are we that this doesn't happen on a real PSP in that situation?  It looks like it's delivering an error code from the FFIV save not existing.

I guess the bestiary would be empty if you had no saves anyway?

-[Unknown]

**Comment by unknownbrackets** [comment]
Replicated on a real PSP.  Exactly the same behavior, so it's correct.  Or you could say it's a bug in the game, because it's not the most awesome experience really.

-[Unknown]
