### ISSUE TITLE
dragon ball z shin bukokai 2 run in black screen (iOS)

### ISSUE THREAD

**Issue by brujo5** [hrydgard/ppsspp#8331]
![image](https://cloud.githubusercontent.com/assets/4172898/12039939/f1cb8326-ae21-11e5-95d5-9d06331d8e3c.png)

another dbz games are not affected.

tested in latest build

the good news is that yo can go ingame/play without crash.

so ppsspp dev latest 1.1.1-488 is usable now (no jit) in ARM64 devices

**Comment by brujo5** [comment]
fixed after delete old save

**Comment by unknownbrackets** [comment]
Oh, crazy.  Good to know.

-[Unknown]
