### ISSUE TITLE
zh_gb.pgf missed?

### ISSUE THREAD

**Issue by latot** [hrydgard/ppsspp#8332]
Hi, some times i get this message:
```
W: file_util.cpp:178: IsDirectory: stat failed on /home/pipe/Documentos/git/ppsspp/assets/flash0/font/zh_gb.pgf
W: file_util.cpp:178: IsDirectory: stat failed on /home/pipe/Documentos/git/ppsspp/flash0/font/zh_gb.pgf
W: file_util.cpp:178: IsDirectory: stat failed on /usr/share/ppsspp/assets/flash0/font/zh_gb.pgf
W: file_util.cpp:178: IsDirectory: stat failed on /home/pipe/flash0/font/zh_gb.pgf
```

Then searching i found in this web the file (only 1 result on google D: with the file):
http://bbs.youxiri.cn/thread-481803-1-1.html

Its posible add the file?
(i don't know to much obout license and that things, so asking)
or even the file don't is needed

[zh_gb.pgf.zip](https://github.com/hrydgard/ppsspp/files/74476/zh_gb.pgf.zip)

**Comment by unknownbrackets** [comment]
I'm not really sure.  The font doesn't normally exist on PSPs.  My understanding is this was added to better support Chinese translations.

See #5422.

It's not required for non-Chinese games, and I think it's present on the disc for Chinese games.

-[Unknown]

**Comment by latot** [comment]
mm, readed!, but i have some questions, how i have the message i can suppose the font wasn't in the disc?
one of the game i try this ws in japan and translated to english, so why its requesting the chinese font? or maybe wanna use for something else?

Thx.

**Comment by unknownbrackets** [comment]
The change in #5422 makes every game (Chinese or not) attempt to load that font.  That error is generated pretty much everywhere, except on Chinese translated games that use the font.

-[Unknown]

**Comment by latot** [comment]
:o thats... interesting
its possible only load it when the game is chinese?, or hide it, but i think the cuestion hidding it is if hidde it don't affect logs in fonts issue.

**Comment by latot** [comment]
mm, better change the focus, ppsspp notice when its requested some symbol and it not exist?
if its posible notice that wwe can avoid this.

**Comment by sum2012** [comment]
Yes,I agree to remove the zh_gb.pgf log

**Comment by latot** [comment]
mm, only to be sure, if some game call some missed symbol in the font, we get some error?
