### ISSUE TITLE
Metal Gear Solid Peace Walker & God Eater Burst gonna break in android buildbot version 

### ISSUE THREAD

**Issue by HongVietNguyen** [hrydgard/ppsspp#8336]
Please fix it @.@

**Comment by latot** [comment]
D: whats the problem?

**Comment by unknownbrackets** [comment]
Gods Eater Burst seems to work fine for me.  Don't have the other game.  Without more details, we'll just have to close this.

What's happening?  What device are you using specifically?  What's the first git build it stopped working in?  Have you tried resetting your settings to defaults?

-[Unknown]

**Comment by HongVietNguyen** [comment]
My device  s galaxy note4 (octacore version) Android version 5.1.1
I tried many times from 142  to latest buildbot versions, but mgs Peace Walker sometimes make pspspp freeze when loading stages, change areas... God Earer Burst too, pspspp stoped when use charge crush, charge to devour...

**Comment by latot** [comment]
mm, i think can be good idea up the logs, if you don't like copy&past you can do this
```
./PPSSPPSDL --log=logs.log
```

**Comment by HongVietNguyen** [comment]
I downloaded latest (ver 523) and run... God Eater Burst s fine but MGS Peace Walker still errors @.@

**Comment by latot** [comment]
mm, @HongVietNguyen to other contributors can help you its nesesary some info, for example the type of problems and bugs, first i recomend you use a terminal from your android, when you execute the ppsspp in the terminal (actually are two gui available, SDL and QT) you will see a lot of info is printed like this (example):

https://gist.github.com/latot/689562e2539503c3a0c1

when are some errors, there are normally printed there (in red errors and some info yellow and you can change the vernosity of it in settings), its posible get some problems without clear log, so its recomended try print or get screens of the problem.
The past command:
```
./PPSSPPSDL --log=logs.log
```
it will execute the SDL version and all text info you probably will need will be save in the file logs.log.
When you have this data you need show it here, resume what you need post here:

Game: MGS Peace Walker (checked!)
Device:  galaxy note4 (octacore version) Android version 5.1.1 (checked!)
Logs: get the file logs.log and post the info
Screen: get some screen of the problem
What you can see its the problem: your experience with the problem.
PPSSPP version: 523 (checked!)
PPSSPP GUI: if its SDL or QT what are you ussing.

I hope this can help you.
Cya.

**Comment by unknownbrackets** [comment]
Well, I'm not sure SDL runs on Android.  But you can get the log using `adb logcat`.  Google has instructions for that:

https://www.google.com/search?q=how+to+adb+logcat&ie=utf-8&oe=utf-8

I think someone mentioned there might be an Atrac3+ related issue with Peace Walker, though.  Not sure.

-[Unknown]

**Comment by latot** [comment]
Thx to clear it i was worried for that :D

**Comment by HongVietNguyen** [comment]
Thanks u guys ;)

**Comment by HongVietNguyen** [comment]
Buildbot 608 
MGS PW has been fixed 
But GEB crush again, after few seconds when i hit enemies...

**Comment by SamueldeSena** [comment]
this problem has already been corrected in the new version of ppsspp v1.5.4 this topic can already be closed
