### ISSUE TITLE
Saving dialog messing up and slow with xbrz enable on v1.1.1-521-g37cfea0

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8339]
![1](https://cloud.githubusercontent.com/assets/3481559/12059389/503152a0-af95-11e5-8848-33f2ba9010b6.png)

**Comment by daniel229** [comment]
Ingame is also also broken.
![02](https://cloud.githubusercontent.com/assets/3481559/12059452/501b876c-af96-11e5-9102-e18e9957bb0c.png)

**Comment by unknownbrackets** [comment]
Does e3e8fbf fix this?

-[Unknown]

**Comment by daniel229** [comment]
Yes,fixed now.
