### ISSUE TITLE
The 3rd Birthday Upscale level issue

### ISSUE THREAD

**Issue by zminhquanz** [hrydgard/ppsspp#8342]
When i upscale level to 2x , it's have glitches text
![image](https://cloud.githubusercontent.com/assets/11285640/12060967/072ca448-afad-11e5-8bc2-f8d97f6eebfc.png)

and when I change upscale level to off , it's normal

![image](https://cloud.githubusercontent.com/assets/11285640/12060983/38c24562-afad-11e5-99cf-02590af3646d.png)

**Comment by zminhquanz** [comment]
and speed emulation is slowdown at load game and img is glitch when i upscale level to 2x , just see the picture bellow
![image](https://cloud.githubusercontent.com/assets/11285640/12061004/c14641c2-afad-11e5-9f5a-16e253dd6bb3.png)

**Comment by zminhquanz** [comment]
and slow down ingame when i upscale level to 2x
![image](https://cloud.githubusercontent.com/assets/11285640/12061018/3b5c5e7e-afae-11e5-8582-7a4db1884de4.png)
when i switch to off , it's normal
![image](https://cloud.githubusercontent.com/assets/11285640/12061020/4f11ab0e-afae-11e5-96ec-87fa079e1e14.png)

**Comment by zminhquanz** [comment]
and another game , ex : GOW Chains Of Olympus , have slowdown when i switch to upscale level 2x
![image](https://cloud.githubusercontent.com/assets/11285640/12061036/a3e5397a-afae-11e5-8625-51ff65df9fc2.png)
switch to off , it's normal
![image](https://cloud.githubusercontent.com/assets/11285640/12061039/af62d212-afae-11e5-8ac0-d5c999e426da.png)

**Comment by unknownbrackets** [comment]
Switch to v1.1.1-523-g1072028 or newer.

-[Unknown]

**Comment by zminhquanz** [comment]
the newer builds is have a bugs
