### ISSUE TITLE
MHFU Keeps crashing please help 

### ISSUE THREAD

**Issue by Hendex** [hrydgard/ppsspp#8352]
i have a imac osx and i run mhfu on ppsspp mac edition and the first day i played it worked well for like 6 hrs without any crashes and now when i play second day it starts to crash alot can someone please help me out the error keeps popping up is this i will paste here                                                                                                             Unhandled exception: page fault on read access to 0x00000008 in 32-bit code (0x99fafef0).
Register dump:
 CS:001b SS:0023 DS:0023 ES:0023 FS:101f GS:000f
 EIP:99fafef0 ESP:023cf350 EBP:023cf378 EFLAGS:00010206(  R- --  I   - -P- )
 EAX:00000000 EBX:492d772e ECX:00000000 EDX:0000a403
 ESI:40732b30 EDI:00000000
Stack dump:
0x023cf350:  4070c470 4070c690 023cf3ec 00000000
0x023cf360:  00000000 00000000 00000000 40732b30
0x023cf370:  00000030 492d772e 023cf408 492d796a
0x023cf380:  00000000 4070c690 023cf3ec 3bd30441
0x023cf390:  00000000 00000000 023cf3d8 950dfe8e
0x023cf3a0:  00003a13 0000030a 492e2601 492d79a0
0203: sel=101f base=81fd0000 limit=00000fff 32-bit rw-
Backtrace:
=>0 0x99fafef0 (0x023cf378)
  1 0x492d796a (0x023cf408)
  2 0x492d27d6 (0x023cf448)
  3 0x006067f3 in ppssppwindows (+0x2067f2) (0x023cf578)
  4 0x00616a7e in ppssppwindows (+0x216a7d) (0x023cf5ac)
  5 0x006a1d76 in ppssppwindows (+0x2a1d75) (0x023cf5c8)
  6 0x006a1c25 in ppssppwindows (+0x2a1c24) (0x023cf5e0)
  7 0x006a1b28 in ppssppwindows (+0x2a1b27) (0x023cf644)
  8 0x013bc01d in msvcr120 (+0x2c01c) (0x023cf67c)
  9 0x013bc001 in msvcr120 (+0x2c000) (0x023cf688)
  10 0x7bc6db6c (0x023cf698)
  11 0x7bc6ec1a (0x023cf718)
  12 0x7bc6db32 (0x023cf738)
  13 0x7bc7642c (0x023cff88)
  14 0x9b9f7c25 (0x023cffa8)
  15 0x9b9f7b9b (0x023cffc8)
  16 0x9b9f4e32 (0x023cffec)
0x99fafef0: movl    0x8(%edi),%edx
Modules:
Module  Address         Debug info  Name (31 modules)
PE    400000- 1385000   Export          ppssppwindows
PE   1390000- 147e000   Export          msvcr120
PE  10000000-10071000   Deferred        msvcp120
PE  405a0000-405ab000   Deferred        winmm
PE  42ad0000-42ad4000   Deferred        imm32
PE  44260000-4428e000   Deferred        user32
PE  443a0000-443a4000   Deferred        gdi32
PE  44520000-44524000   Deferred        advapi32
PE  445a0000-445a4000   Deferred        version
PE  445b0000-445b8000   Deferred        ole32
PE  44700000-44704000   Deferred        rpcrt4
PE  44790000-44794000   Deferred        msacm32
PE  447b0000-447b4000   Deferred        opengl32
PE  448d0000-448d4000   Deferred        dsound
PE  44920000-44940000   Deferred        comctl32
PE  44a30000-44a42000   Deferred        comdlg32
PE  44aa0000-44baf000   Deferred        shell32
PE  44ca0000-44ca4000   Deferred        shlwapi
PE  44d20000-44d26000   Deferred        winspool
PE  44d60000-44d64000   Deferred        ws2_32
PE  44da0000-44da4000   Deferred        dinput8
PE  44e60000-44e63000   Deferred        winemac
PE  46800000-46804000   Deferred        uxtheme
PE  492b0000-492b4000   Deferred        xinput1_3
PE  492c0000-492c4000   Deferred        dinput
PE  49320000-49323000   Deferred        usp10
PE  4a3c0000-4a3c4000   Deferred        mmdevapi
PE  4a510000-4a517000   Deferred        oleaut32
PE  4a640000-4a643000   Deferred        winecoreaudio
PE  7b810000-7b866000   Deferred        kernel32
PE  7bc10000-7bc14000   Deferred        ntdll
Threads:
process  tid      prio (all id:s are in hex)
0000000e services.exe
    0000001e    0
    0000001d    0
    00000014    0
    00000010    0
    0000000f    0
00000012 winedevice.exe
    0000001c    0
    00000019    0
    00000017    0
    00000013    0
0000001a plugplay.exe
    00000020    0
    0000001f    0
    0000001b    0
0000002d (D) C:\Program Files\ppsspp\PPSSPPWindows.exe
    00000038    0
    00000037    1
    00000036   15
    00000035    0
    00000034    0
    00000033    0 <==
    00000032    0
    0000002e    0
0000002f explorer.exe
    00000030    0
System information:
    Wine build: wine-1.7.12
    Platform: i386
    Host system: Darwin
    Host version: 14.5.0

**Comment by Nightbane112** [comment]
Why are using PPSSPP through Wine instead of using the OSX build from the downloads page? [http://build.ppsspp.org/?page/downloads#osx](url)

It would saved yourself from the hassle of setting up wine and remove any performance overhead present by running the emulator via Wine.

**Comment by GAMELASTER** [comment]
@Nightbane112 I'm little confused why you commenting a issue old a 4 months?

**Comment by Hendex** [comment]
Yeah i used to play the game when I was really young but my Mac doesn't
work anymore so it doesn't matter but that thanks for the advice

**Comment by Nightbane112** [comment]
@GAMELASTER Cause this bug issue was still marked as open and I'm trying to suggest a solution?

@Hendex If doesn't the bug issue doesn't concern you anymore, could you mark the issue as closed?

**Comment by unknownbrackets** [comment]
We've fixed various issues, and haven't had other reports of this particular crash.  It may be related to a bug fixed since 2016, but it's hard to tell when fixes in PPSSPP might fix other games.  Sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
