### ISSUE TITLE
Can't see any words on sd gundam g generation world

### ISSUE THREAD

**Issue by MatthewChin96** [hrydgard/ppsspp#8353]
Hi, when i play sd gen i the ppsspp cannot display the subtitle.Is it any way to fix it?
By the way,i using ppsspp Windows version

**Comment by unknownbrackets** [comment]
Are you using default settings?  There are a lot of settings that could prevent the subtitles from showing.

Could you try to find it attempting to draw the subtitles?
https://github.com/hrydgard/ppsspp/wiki/How-to-find-a-graphic-issue-with-the-GE-debugger

Note that you're not looking for a red mark covering the entire screen (that's probably the video, or clearing the screen for the next frame.)  You're looking for red just where the text would show.

-[Unknown]

**Comment by daniel229** [comment]
Since https://github.com/hrydgard/ppsspp/pull/8340
![02](https://cloud.githubusercontent.com/assets/3481559/12076627/3d75b6fa-b1ee-11e5-9ad4-dc926fc0de83.png)
![01](https://cloud.githubusercontent.com/assets/3481559/12076628/3d762b62-b1ee-11e5-99c6-fd564a45c65c.png)

**Comment by unknownbrackets** [comment]
If you change `nextTexture_->maxSeenV = std::max((u16)272, gstate_c.vertBounds.maxV);` to `nextTexture_->maxSeenV = std::max((u16)512, gstate_c.vertBounds.maxV);` it works fine?

It could be a hash collision...

-[Unknown]

**Comment by daniel229** [comment]
GE debugger
![03](https://cloud.githubusercontent.com/assets/3481559/12076681/72d6c90e-b1f0-11e5-8b41-cf8c6eafc032.png)

https://gist.github.com/daniel229/3dd8d831a9a65c0809d2

**Comment by daniel229** [comment]
Yes,it works fine.

**Comment by unknownbrackets** [comment]
Hmm.  I was thinking maybe the texture got taller and so it didn't notice right away, but that should fix it next frame.  What if you use `273` instead of `272`?

-[Unknown]

**Comment by daniel229** [comment]
Does not work.

**Comment by unknownbrackets** [comment]
If 273 doesn't work, it implies to me that it probably isn't hash collision related.  But since 512 works, something must be happening.

Can you log the `gstate_c.vertBounds.maxV` value before `nextTexture_->maxSeenV = std::max((u16)272, gstate_c.vertBounds.maxV);`?  Just wondering what it was before.

-[Unknown]

**Comment by daniel229** [comment]
Is it
<code>NOTICE_LOG(G3D,"gstate_c.vertBounds.maxV : %08x", gstate_c.vertBounds.maxV);</code>
```
57:00:796 UserMain     N[G3D]: GLES\TextureCache.cpp:863 gstate_c.vertBounds.maxV : 00000000
```

**Comment by unknownbrackets** [comment]
Hmm.  Can you try changing `if (nextTexture_->maxSeenV == 0) {` to `if (nextTexture_->maxSeenV == 0 && gstate_c.vertBounds.maxV > 0) {`?

Did I miss float uvs?  Hmm.  But the above is probably more correct anyway.

-[Unknown]

**Comment by daniel229** [comment]
Great,it works fine now.
