### ISSUE TITLE
Nana Subete wa Daimaou no Omichibiki freezing on title

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8355]
Since https://github.com/hrydgard/ppsspp/pull/8354
```
55:33:401 snd_thread_m N[ME]: HLE\sceAtrac.cpp:1133 80630024=sceAtracDecodeData(1, 08b0022c, 09fbca68[00000000], 09fbca64[00000001], 09fbca60[0])
```
full log (rename jpg to 7z)
![ppsspplog](https://cloud.githubusercontent.com/assets/3481559/12072887/31b2e48a-b137-11e5-9fb7-cffc928c8d04.jpg)

**Comment by daniel229** [comment]
before
[ppsspplog before.txt](https://github.com/hrydgard/ppsspp/files/76108/ppsspplog.before.txt)

**Comment by unknownbrackets** [comment]
Before, it has 0x03bb at the start, and 0x03c4 at the end.  Hmm.

Could you try to get a JpcspTrace of this game, specifically of sceAtracDecodeData?  I'm wanting to see what the correct samples are for this particular ATRAC3 file.  Maybe it's supposed to specify finish = 1 on the last one that returns > 0 samples...

-[Unknown]

**Comment by daniel229** [comment]
jpcsptrace for sceAtracDecodeData
https://gist.github.com/daniel229/5cdfec75add6557b918e

**Comment by unknownbrackets** [comment]
Oh, sorry, it should be:

sceAtracDecodeData 0X6A8C3CD5 5 dxppp

That will give the numSamples values.  But, this is useful in that it shows that sceAtracDecodeData  doesn't ever return an "end of data" error on a real PSP.

-[Unknown]

**Comment by daniel229** [comment]
Here it is
https://gist.github.com/daniel229/fc987e04d8984a32e976

**Comment by unknownbrackets** [comment]
Thanks.  Darn, though, it's truncated... so it doesn't show the ending sample size.

So far all the values confirm the values we're getting.

-[Unknown]

**Comment by unknownbrackets** [comment]
Did #8361 fix this?

-[Unknown]

**Comment by daniel229** [comment]
Fixed.
