### ISSUE TITLE
Bleach Heat Soul 6 Triangle Button Doesn't work 

### ISSUE THREAD

**Issue by AizerMortenort** [hrydgard/ppsspp#8360]
solved. Save file issue.

**Comment by daniel229** [comment]
Looks fine here with the latest build v1.1.1-579-g35930c4 on PC.What platform are you playing on?using a controller?

**Comment by unknownbrackets** [comment]
Also note that sometimes, if you have the same button mapped to triangle and also some other thing, it might not work.

-[Unknown]

**Comment by AizerMortenort** [comment]
No.
The attack which is Triangle by Default Does not work.
I tried remapping it in game to Square - stll does not work. 
Please check this out.

**Comment by AizerMortenort** [comment]
Will a Dev respond?

**Comment by unknownbrackets** [comment]
I already did respond.

Sounds like your system is broken.  Will you buy a new one?

-[Unknown]

**Comment by AizerMortenort** [comment]
I already answered.
as for system - Windows 7
Yes Pad I use joypad.
I already said changing IN-GAME buttons (not from emu but from the game's attack options) also doesn't work. Mapping said attack to square - doesn't work .

**Comment by hrydgard** [comment]
Just to be sure, try to reset PPSSPP's settings to defaults (move away PPSSPP.ini and controls.ini from Memstick/PSP/SYSTEM ), does it still not work?

**Comment by AizerMortenort** [comment]
Tried. No luck.

**Comment by unknownbrackets** [comment]
The initial issue description was changed to "solved. Save file issue."  I'm not sure what that means, but it could mean a corrupt save file - perhaps from cheats, or something?

Closing again.

-[Unknown]

**Comment by AizerMortenort** [comment]
Dunno. On PSP it works. On PPSSPP it doesn't - maybe issue between Firmwares on the console since 5.00 and above Saves on PSP are not compatible with older Firmwares.

**Comment by unknownbrackets** [comment]
PPSSPP is not always compatible with games hacked to run on lower version firmware.

For example, I don't have this game, but Wikipedia says it was released on May 14, 2009.  At that time, 5.50 was the most current version.  If your PSP save is from a console that runs an older firmware version, with hacks to make games that want newer firmware work (this was very popular with CFW), then your saves are actually being created incorrectly on your PSP.

In that scenario, you'll find that the saves don't work on a PSP running the latest version of official firmware either.  Whoever you got such hacks from is probably the right person to ask for some way to convert the broken saves they gave you to working saves.

-[Unknown]

**Comment by AizerMortenort** [comment]
My PSP is 6.60 Firmware. So hell no all works well there :)
