### ISSUE TITLE
ppsspp kingdom hearts bbs savedata

### ISSUE THREAD

**Issue by eldenisson** [hrydgard/ppsspp#8366]
when it comes the time i have to save with the normal saving method in a new game,
the emulator crashes saying that it stopped working....

someone know what's the problem?

**Comment by unknownbrackets** [comment]
Is this the same as #7244 / http://forums.ppsspp.org/showthread.php?tid=445&pid=106844#pid106844 ?

Does it happen when you don't use any savestates or cheats whatsoever (not even loading a savestate)?

-[Unknown]

**Comment by eldenisson** [comment]
no, i'm using the savestates, doing the tutorial again and again it's such a pain
i'm not using cheats, not for now, because it's a new game, i don't have other savedata
i have the cheat enabled, but i tried even with them disabled but it doesn't work

**Comment by unknownbrackets** [comment]
If you use cheats, and they break something, and then you turn off cheats... that thing is broken.  And savestates will memorialize that broken thing forever.

I just sped through the tutorial and saved in the first world you can get to - no issues.  I'm using a US region game.

-[Unknown]

**Comment by unknownbrackets** [comment]
So, does this happen even from clean?  And what device are you using?

-[Unknown]

**Comment by eldenisson** [comment]
Yes, it happens on my pc with windows 10....

I didn't try anymore as I started to use it on android, but it's a mistery....

maybe I have to try on another pc with windows 10 to see if it will have the same problem

**Comment by unknownbrackets** [comment]
You might try looking for an updated video card driver.  We've seen a lot of crash issues with Windows 10 that were related to bugs in drivers.

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
