### ISSUE TITLE
D3D Saving dialog missing font。

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8385]
Since https://github.com/hrydgard/ppsspp/pull/8368
![31](https://cloud.githubusercontent.com/assets/3481559/12092709/beae852a-b339-11e5-85c3-7363f8b778cd.png)

**Comment by unknownbrackets** [comment]
Hmm, it seems to be 249417691950c2ce93ebc774c2ac12b893f03559.

-[Unknown]
