### ISSUE TITLE
Coverity things

### ISSUE THREAD

**Issue by latot** [hrydgard/ppsspp#8386]
resume of resume

uu sorry it seems are already using, so change, add the icon to see the status in main page of ppsspp

probably you can use something like this:

```
[![Coverity Status](https://img.shields.io/coverity/scan/3955.svg)](https://scan.coverity.com/projects/hrydgard-ppsspp)
```

**Comment by latot** [comment]
uu sorry it seems are already using, so change, add the icon to see the status in main page of ppsspp

**Comment by unknownbrackets** [comment]
AFAICT Coverity doesn't seem to support Visual Studio 2015, it rejects all builds we upload.  The last build we put up was when we were still using Visual Studio 2013.  So we are not actively using it currently.

-[Unknown]

**Comment by latot** [comment]
mm, and the posibility to run coverity with travis?
https://scan.coverity.com/travis_ci

**Comment by hrydgard** [comment]
@latot , could you please remove the chatbot configuration in travis.yml in your fork of PPSSPP? our IRC channel is getting your build failures :)

**Comment by latot** [comment]
Ups, sorry i was experimenting how works it, ready!

**Comment by latot** [comment]
Hi, well testing this, i use the fork to see how works with coverity, and i get a lot of errors trying with travis, sadly the comunity page is down so i can't see the error description, but i make the tarball locally with the tools of coverity, then i upload in submit build and seems works, at least the scan works in that way.

**Comment by unknownbrackets** [comment]
I think Travis whitelisted us for a newer version of the Linux OS than their standard.  It may not work for forks.

-[Unknown]

**Comment by latot** [comment]
mm, in that case its posible test it direct here? sadly this only can be do probably for you or @hrydgard because you need acces to the token of coverity and maybe create a new branch to it.

**Comment by latot** [comment]
well now tested and works, example with fork:
https://scan.coverity.com/projects/latot-ppsspp

**Comment by unknownbrackets** [comment]
That has around half as many lines of analyzed code, though.

-[Unknown]

**Comment by unknownbrackets** [comment]
These results are pretty out of date now.  We might consider something like this:
https://securitylab.github.com/tools/codeql

But we also get decent compiler warnings, even in CI.

I'm going to close this since the Coverity details are out of date.  That said, we could implement it with CI:
https://github.com/ruby/actions-coverity-scan/blob/master/.github/workflows/coverity-scan.yml

-[Unknown]
