### ISSUE TITLE
psspp andriod problem

### ISSUE THREAD

**Issue by asbel123** [hrydgard/ppsspp#8387]
i start every game u get white screeen of death when i quit of game i try it agian psp games works now its werid bug on samsung galaxy s6 edge  i am using latest orphis build today fix it. i got no problem on old version 535 build

**Comment by sum2012** [comment]
What is the last version work and 
what is the first version have problem in http://buildbot.orphis.net/ppsspp/index.php?m=fulllist ?

**Comment by asbel123** [comment]
i am uplaoding pictures u see for it urself  in lastest version.

![img_20160107_101234 1](https://cloud.githubusercontent.com/assets/4496487/12157695/b29b3342-b527-11e5-9506-db51842d9608.jpg)

this is lastest version for andriod next picture when i play the game first time u get black screen and white screen.

![img_20160107_101305 1](https://cloud.githubusercontent.com/assets/4496487/12157715/d8d48360-b527-11e5-8a96-062607ba86fe.jpg)

![img_20160107_101312 1](https://cloud.githubusercontent.com/assets/4496487/12157723/e5b8e300-b527-11e5-9d82-0012f43ec77a.jpg)

when i quit the game first time i press second time for game its work perfect its a bug i upload next picutre.

![img_20160107_101324 1](https://cloud.githubusercontent.com/assets/4496487/12157740/0a13f582-b528-11e5-91f8-5f2b1a091b0e.jpg)

**Comment by asbel123** [comment]
this is my samsung galaxy s6 edge

**Comment by asbel123** [comment]
sum tell hygard to see this too.

**Comment by hrydgard** [comment]
I'll look into it soon. I have an S6.

**Comment by unknownbrackets** [comment]
It makes it a lot easier to have the FIRST git build that didn't work, and the LAST git build that did work.

Anyway, this was probably #8347, affecting GLES3 devices (GLES feature flags were wrong, detected before a call to GLExtensions, so shaders did not link.)

481be1c

-[Unknown]

**Comment by asbel123** [comment]
i played final fantasy 3 ppsspp latest build i load savestate went back to normal too.

**Comment by sum2012** [comment]
@asbel123 Does v1.1.1-645-g481be1c fixed ?

**Comment by asbel123** [comment]
tthank u sum its work perfect on latest version git build thank u unknowbrackets. i close this issues know.
