### ISSUE TITLE
Linux Armored Core 3 Portable Crash

### ISSUE THREAD

**Issue by Resharc** [hrydgard/ppsspp#8391]
When attempting to play the mission "Destroy Escaping MT" in Armored Core 3 Portable, it'll crash right after the opening cutscene (when it gives the player the control) on the latest dev build on Linux. My settings are as follows:

Graphics
* Rendering Mode - Buffered Rendering
* Simulate Block Transfer Effects - On
* Frameskipping - Off
* Auto Frameskipping - Off
* Prevent FPS from exceeding 60 - On
* Alternative Speed - Unlimited
* All Postprocessing Settings are Off
* Rendering Resolution - 1x PSP
* Display Rotation - Landscape
* Minmapping - Off
* Hardware Transform - On
* Software Skinning - On
* Vertex Cache - On
* Lazy texture caching - Off
* Retain Changed Textures - On
* Disable Slower Effects - Off
* Spline/Bezier Curves Quality - Low
* Texture Upscaling settings are all off, although Upscale Type is xBRZ
* Texture filtering is all default.
* None of the speedhacks are on, and the FPS is the only overlaid element.

System
* Last Memory - Off
* Multi-Threaded - On
* I/O Timing Method - Fast (lag on slow storage)
* Force Real Clock Sync - On
* Emulated PSP CPU Clock is on Auto
* Snapshot Frequency is Off

I attempted to get a log, but the method in a guide that I found didn't seem to work, so I'm not sure how to supply that. My distro is Lubuntu 15.10, and my specs are as follows

CPU - Intel(R) Celeron(R) CPU  N2930  @ 1.83GHz
RAM - 1880 MB
GPU - Intel Atom Processor Z36xxx/Z37xxx Graphics and Display

I hope this is enough information.

**Comment by unknownbrackets** [comment]
Try turning off multithreaded.  In general, it can cause crashes.

Not sure if this is the same as #5999.

-[Unknown]

**Comment by daniel229** [comment]
This game also freeze like https://github.com/hrydgard/ppsspp/issues/5999 does

**Comment by daniel229** [comment]
is It here?
![04](https://cloud.githubusercontent.com/assets/3481559/12111549/25ef6b54-b3d1-11e5-8a7e-e9e74104afa0.png)

**Comment by Resharc** [comment]
Yeah, that's the point when it crashes.

**Comment by daniel229** [comment]
So it's a duplication of https://github.com/hrydgard/ppsspp/issues/5999

**Comment by daniel229** [comment]
There is workaround here https://github.com/hrydgard/ppsspp/issues/5999#issuecomment-47958127
Since it 's the same as https://github.com/hrydgard/ppsspp/issues/5999, I close this now
