### ISSUE TITLE
Multi-pass CPU-based filter framework with Super xBR support.

### ISSUE THREAD

**Issue by ADormant** [hrydgard/ppsspp#8398]
Multi-pass cpu filter framework is required for a cpu based version of Super xBR which can work directly on textures.
https://github.com/libretro/common-shaders/tree/master/xbr
https://drive.google.com/file/d/0B_yrhrCRtu8GYkxreElSaktxS3M/view?pref=2&pli=1
Here are screenshots of RE Remake on GC with Super xBR applied with RetroArch's image viewer core.
Super xBR on textures looks phenomenal on digitized games and games with pre-rendered backgrounds.
![retroarch-0104-045603c2lwi](https://cloud.githubusercontent.com/assets/10523326/12136881/4974021c-b44c-11e5-8611-b333008b11f7.png)
![retroarch-0104-045626t3yf9](https://cloud.githubusercontent.com/assets/10523326/12136887/53f015b4-b44c-11e5-853e-18b585491b1f.png)
![retroarch-0104-050239cgzx3](https://cloud.githubusercontent.com/assets/10523326/12136892/5b4e5adc-b44c-11e5-9391-898f64299610.png)
![retroarch-0104-050309hrlvx](https://cloud.githubusercontent.com/assets/10523326/12137288/6826473a-b44f-11e5-862f-b0f4bb41b852.png)
![retroarch-0104-045826iplny](https://cloud.githubusercontent.com/assets/10523326/12137295/805b4b8e-b44f-11e5-985d-b7640ea6ac13.png)

**Comment by ADormant** [comment]
https://drive.google.com/file/d/0B_yrhrCRtu8GYkxreElSaktxS3M/view?pref=2&pli=1

**Comment by ADormant** [comment]
http://pastebin.com/cbH8ZQQT
@unknownbrackets

**Comment by unknownbrackets** [comment]
We have a multi-pass GPU based filter framework now.  It seems like these filters are generally available as shaders now.

Is there still a motivation to have CPU based filtering?

-[Unknown]

**Comment by hrydgard** [comment]
There's no reason to do filtering on CPU. We can close this since we now have pretty powerful GPU capabilities.
