### ISSUE TITLE
Yu-gi-oh Arc-V: Tag Force Special : Can't join/see a rom in it (PPSSPP 1.1.1)

### ISSUE THREAD

**Issue by Amaestris** [hrydgard/ppsspp#8400]
I've managed to play local multiplayer with my brother using this method : http://forums.ppsspp.org/showthread.php?tid=11321&pid=96846#pid96846 , which worked for previous yu-gi-oh tag force game and MHFU too.
This game is normally supported since the v0.9.9.1-1053 (source: http://forums.ppsspp.org/showthread.php?tid=9037 )
We are both using IOS devices
 Could you help me with this ?

**Comment by magma-blaziken** [comment]
Same problem with Tag Force 5 as well. Multiplayer on android for YGO is not working at all.

**Comment by sum2012** [comment]
@magma-blaziken try v1.1.1-861-g0550cd3 or newer version.
There is a new setting "port offset". 
Try set port offset of the same value of  both android  phone (The value need > 1024)
Other setting same as before in multiplayer.

**Comment by magma-blaziken** [comment]
It works now! Well haven't tested playing a multiplayer game but I can host and join with my android phone and tablet.
