### ISSUE TITLE
Windows High DPI Displays Scaling Issues

### ISSUE THREAD

**Issue by Ik2ari** [hrydgard/ppsspp#8411]
I have a Surface Pro 4 which has a display with a pretty high PPI ratio (267 PPI) so i have DPI Scaling turned to 200% .

When DPI Scaling is turned on the UI of PPSSPP ist not scaling properly which makes it hard or even impossible to change settings or navigate through the UI.

DPI Scaling 200% on Surface Pro 4:
![screenshot_01](https://cloud.githubusercontent.com/assets/16632036/12220835/d425c326-b782-11e5-974a-656398caa642.png)
![screenshot_02](https://cloud.githubusercontent.com/assets/16632036/12220837/d42d116c-b782-11e5-8a3f-ac8ea8597943.png)

High DPI Displays had an boom on mobile devices which is swapping over to Desktop PC's and these screens getting pretty common on Desktops an Laptops.

It's almost impossible to work without scaling on such a display because the UI elements are getting really small.

DPI Scaling 100% on Surface Pro 4:
(This is an 12" Display so you can imagine how small UI elements are with DPI Scaling set to 100%)
![screenshot_03](https://cloud.githubusercontent.com/assets/16632036/12220836/d429d1e6-b782-11e5-95b7-432ad5ba54eb.png)

**Comment by unknownbrackets** [comment]
Should we be calling this?  https://msdn.microsoft.com/en-us/library/windows/desktop/dn280510%28v=vs.85%29.aspx  @Bigpet or @thedax how do we get the dpi?  I know we marked the app as dpi aware.

I think our text renderer is the only thing using windows functions that will layout based on dpi....

-[Unknown]

**Comment by Bigpet** [comment]
@unknownbrackets yeah, as you can see per-monitor dpi was only introduced in Windows 8.1. so if we want to correctly support older systems then I guess it would be `float fScale = GetDeviceCaps(hdc, LOGPIXELSX) / 96.0f;` or something.

**Comment by hrydgard** [comment]
The text renderer is already computing the font height like this:

    	INT nHeight = -MulDiv( size, (INT)(GetDeviceCaps(ctx_->hDC, LOGPIXELSY) * textScale), 72 );

You'd think that would work at least in the common cases but I suppose we could try calling the function unknownbrackets linked to ...

**Comment by Bigpet** [comment]
I don't remember if we declared the application as "System DPI-Aware" (in which the current solution should work) or as "Monitor DPI-Aware". If it's the latter then I guess querying the Monitor DPI is what Needs to be done.

**Comment by unknownbrackets** [comment]
Well, the text renderer IS increasing the text size.  But don't we need g_dpi to match, so that the checkbox size and other things are also increased?

It's not the spoon that's wrong here, it's everything around the spoon.  The text is the only thing that's right in that screenshot, isn't it?

-[Unknown]

**Comment by Bigpet** [comment]
That sounds about right. I just tested GetDpiForMonitor and it gives me the same value as GetDeviceCaps on the one-monitor System that I am at right now

**Comment by hrydgard** [comment]
Ah, right, yeah. We want the text to be rendered at high res to match the high DPI, but not get blown up again as if the DPI was lower. We must adjust g_dpi indeed.

**Comment by unknownbrackets** [comment]
I think this might be improved now?

-[Unknown]

**Comment by hrydgard** [comment]
Yeah just forgot to close this.
