### ISSUE TITLE
Gakuen Heaven  video is not displayed

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8418]
but it works with non-buffered mode and read framebuffered to memory.

```
31:35:259 naviThread   W[ME]: HLE\scePsmf.cpp:1629 scePsmfPlayerGetCurrentPts(0908960c, 09089610): no frame yet
31:35:259 naviThread   W[ME]: HLE\scePsmf.cpp:1629 scePsmfPlayerGetCurrentPts(0908960c, 09089610): no frame yet
31:35:287 naviThread   W[ME]: HLE\scePsmf.cpp:1629 scePsmfPlayerGetCurrentPts(0908960c, 09089610): no frame yet
31:35:290 displayThrea W[G3D]: GLES\TextureCache.cpp:410 Render to area containing texture at 00110000 +0x136
31:35:291 displayThrea I[G3D]: GLES\ShaderManager.cpp:160 Linked shader: vs 15 fs 24
```

Debug log (rename jpg to 7z)
![ppsspplog](https://cloud.githubusercontent.com/assets/3481559/12228136/277f9fb6-b872-11e5-81d7-9ddabd143973.jpg)

**Comment by unknownbrackets** [comment]
Hmm, this seems odd:

Render to area containing texture at 00110000 +0x136

I wonder if it's misdetecting the height or if it's really tring to texture from there.  Does it change if you find `AttachFramebufferInvalid(entry, framebuffer, fbInfo);` in TextureCache.cpp and change it to `AttachFramebufferValid(entry, framebuffer, fbInfo);`?

-[Unknown]

**Comment by daniel229** [comment]
Still not display.

**Comment by daniel229** [comment]
Flowers Natsu Hen is the same.

**Comment by benderscruffy** [comment]
this can be closed the video plays
