### ISSUE TITLE
Ao no Exorcist - Genkoku no Labyrinth black boxes problem

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8419]
SInce https://github.com/hrydgard/ppsspp/pull/7768

![01](https://cloud.githubusercontent.com/assets/3481559/12231175/72517ef6-b890-11e5-8d14-5822bdc5f322.png)

GE debugger
![02](https://cloud.githubusercontent.com/assets/3481559/12231219/cdab3df0-b890-11e5-88f1-b9ff0b16c958.png)
https://gist.github.com/daniel229/0bad5ee22e030da2ba07

**Comment by unknownbrackets** [comment]
Does it help if you comment out `return CheckAlphaABGR4444SSE2(pixelData, stride, w, h);`?

It looks like that entire texture uses alpha=0, so I wonder what it could be misdetecting.

-[Unknown]

**Comment by daniel229** [comment]
Yes,it does.

**Comment by unknownbrackets** [comment]
What happens if you replace:

```c++
	// Use SIMD if aligned to 16 bytes / 8 pixels (usually the case.)
	if ((w & 7) == 0 && (stride & 7) == 0) {
#ifdef _M_SSE
		return CheckAlphaABGR4444SSE2(pixelData, stride, w, h);
```

With:

```c++
	// Use SIMD if aligned to 16 bytes / 8 pixels (usually the case.)
	CheckAlphaResult sseRes = CHECKALPHA_ZERO;
	if ((w & 7) == 0 && (stride & 7) == 0) {
#ifdef _M_SSE
		sseRes = CheckAlphaABGR4444SSE2(pixelData, stride, w, h);
```

And then replace this part just below:

```c++
				// We're done, we hit non-zero, non-full alpha.
				return CHECKALPHA_ANY;
			}
		}
		p += stride2;
	}

	if (hitZeroAlpha) {
		return CHECKALPHA_ZERO;
	} else {
		return CHECKALPHA_FULL;
	}
```

With:
```c++
				// We're done, we hit non-zero, non-full alpha.
if (sseRes != CHECKALPHA_ANY) {
NOTICE_LOG(HLE, "SSE said %d, but regular got ANY/%d", sseRes, CHECKALPHA_ANY);
}
				return CHECKALPHA_ANY;
			}
		}
		p += stride2;
	}

	if (hitZeroAlpha) {
if (sseRes != CHECKALPHA_ZERO) {
NOTICE_LOG(HLE, "SSE said %d, but regular got ZERO/%d", sseRes, CHECKALPHA_ZERO);
}
		return CHECKALPHA_ZERO;
	} else {
if (sseRes != CHECKALPHA_FULL) {
NOTICE_LOG(HLE, "SSE said %d, but regular got FULL/%d", sseRes, CHECKALPHA_FULL);
}
		return CHECKALPHA_FULL;
	}
```

It should log something, and hopefully that will help me see where the typo is.

-[Unknown]

**Comment by unknownbrackets** [comment]
Oops, just saw it.  Nevermind the above, #8421 should fix this I think.

-[Unknown]
