### ISSUE TITLE
FuncHashMap hangs Capcom Classics Collection Remixed

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8420]
debug log (rename jpg to 7z)
![FuncHashMap = True](https://cloud.githubusercontent.com/assets/3481559/12252837/b8e63016-b915-11e5-8826-7ac1730ba823.jpg)

![FuncHashMap = False](https://cloud.githubusercontent.com/assets/3481559/12252838/b8e81106-b915-11e5-9612-36df52a40c6c.jpg)

**Comment by unknownbrackets** [comment]
Does it matter if you use the default FuncHashMap or if you have a blank one?

Or just having it on does it?

The difference in the log seems to be that after sceKernelLoadExec, FuncHashMap=False doesn't re-replace the functions.  That is, you have:

```
12:43:113 user_main    I[HLE]: HLE\ReplaceTables.cpp:1290 Restored 3 replaced funcs between 08804000-08867c48
```

And then only True has:

```
12:43:153 HLE\ReplaceTables.cpp:1260 I[HLE]: Replaced memcpy_jak at 0885b2a8 with hash ade7c490bdbe15a2
12:43:153 HLE\ReplaceTables.cpp:1260 I[HLE]: Replaced memset_jak at 0885b2e8 with hash 850d724f60ceccf9
12:43:153 HLE\ReplaceTables.cpp:1260 I[HLE]: Replaced memmove at 08863c34 with hash 66df05c146ff46ed
```

After that.  But both initially replace those functions, the first time around.

-[Unknown]

**Comment by daniel229** [comment]
Commenting out <code>//{ "memmove", &Replace_memmove, 0, 0 },</code>,it works fine with FuncHashMap = True.

**Comment by unknownbrackets** [comment]
I think that `66df05c146ff46ed` is in your hashmap file, but it's nowhere in the GitHub repo.  Maybe it's a mistake and it's not actually memmove?

-[Unknown]

**Comment by daniel229** [comment]
66df05c146ff46ed also I don't see it on hashmap file.
![01](https://cloud.githubusercontent.com/assets/3481559/12258652/2754a462-b94b-11e5-803e-bbf8765e7cb4.png)

**Comment by daniel229** [comment]
When it load the iso the hashes are here.
```
49:55:601 HLE\ReplaceTables.cpp:1260 I[HLE]: Replaced memcpy_jak at 0885b2a8 with hash 0ffa5db8396d4274
49:55:601 HLE\ReplaceTables.cpp:1260 I[HLE]: Replaced memset_jak at 0885b2e8 with hash eabb9c1b4f83d2b4
49:55:601 HLE\ReplaceTables.cpp:1260 I[HLE]: Replaced memmove at 08863c34 with hash 5c0b3edc0e48852c
```
When load the game ,the memmove changed
```
51:29:507 HLE\ReplaceTables.cpp:1260 I[HLE]: Replaced memcpy_jak at 0885b2a8 with hash ade7c490bdbe15a2
51:29:507 HLE\ReplaceTables.cpp:1260 I[HLE]: Replaced memset_jak at 0885b2e8 with hash 850d724f60ceccf9
51:29:507 HLE\ReplaceTables.cpp:1260 I[HLE]: Replaced memmove at 08863c34 with hash 66df05c146ff46ed
```

**Comment by daniel229** [comment]
Castlevania: The Dracula X Chronicles also change the hash when go to the old games.

**Comment by unknownbrackets** [comment]
Hmm, this might mean it's retaining the same name even when the content changes, causing the problem.  I guess that is because the module name is the same.  Hmm.

-[Unknown]

**Comment by unknownbrackets** [comment]
Just to confirm, does it fix it if you remove this section of Core/MIPS/MIPSAnalyst.cpp?

```c++
			// Use pre-existing symbol map info if available. May be more reliable.
			SymbolInfo syminfo;
			if (addrNextSym <= addr) {
				addrNextSym = g_symbolMap->FindPossibleFunctionAtAfter(addr);
			}
			if (addrNextSym <= addr && g_symbolMap->GetSymbolInfo(&syminfo, addr, ST_FUNCTION)) {
				addr = syminfo.address + syminfo.size - 4;

				// We still need to insert the func for hashing purposes.
				currentFunction.start = syminfo.address;
				currentFunction.end = syminfo.address + syminfo.size - 4;
				// Re-add it to the map if the module address is not known yet (only happens from loaded maps.)
				currentFunction.foundInSymbolMap = syminfo.moduleAddress != 0;
				functions.push_back(currentFunction);
				currentFunction.foundInSymbolMap = false;
				currentFunction.start = addr + 4;
				furthestBranch = 0;
				looking = false;
				end = false;
				isStraightLeaf = false;
				decreasedSp = false;
				continue;
			}
```

-[Unknown]

**Comment by daniel229** [comment]
Yes.

**Comment by daniel229** [comment]
Seems like also hapeen in Secret Agent Clank,the cutscene from new game.

**Comment by unknownbrackets** [comment]
What if you change that removed section to this:

```c++
			if (insertSymbols) {
				SymbolInfo syminfo;
				if (addrNextSym <= addr) {
					addrNextSym = g_symbolMap->FindPossibleFunctionAtAfter(addr);
				}
				if (addrNextSym <= addr && g_symbolMap->GetSymbolInfo(&syminfo, addr, ST_FUNCTION)) {
					insertSymbols = false;
				}
			}
```

Still works fine, right?

I guess this means, if I know it's detecting wrong, I can't fix it.  But that might be okay...

-[Unknown]

**Comment by daniel229** [comment]
Yes.
