### ISSUE TITLE
Game browser missing some characters

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8423]
![01](https://cloud.githubusercontent.com/assets/3481559/12283822/58138d94-b9e5-11e5-9b15-4a90eefc2eda.png)

Win32 bar shows it as
![02](https://cloud.githubusercontent.com/assets/3481559/12283823/58148794-b9e5-11e5-9380-87bf3e27b735.png)

sound like it missing a full width character <code>・</code>
and half width characters <code>ｲﾝﾌｨﾆﾃｨ･ﾓｰﾒﾝﾄ</code>

**Comment by vsub** [comment]
This doesn't look like the default selected font for the text in ppsspp menus(maybe that font don't support those characters)
It looks fine here with the default font
![2016-01-13_073300](https://cloud.githubusercontent.com/assets/5032540/12285938/451fa294-b9c8-11e5-8c4c-12b79b22ad16.jpg)

**Comment by daniel229** [comment]
When choose English language the fonts is not correct.
![01](https://cloud.githubusercontent.com/assets/3481559/12286137/63651c8c-b9fc-11e5-995c-baa026071daf.png)

when choose Chinese language and reopen PPSSPP the font is correct.
![02](https://cloud.githubusercontent.com/assets/3481559/12286140/6814c03e-b9fc-11e5-9993-db25c8a3ad80.png)

choose English language and reopen PPSSPP the font is not correct agains.

**Comment by unknownbrackets** [comment]
Chinese overrides the font: https://github.com/hrydgard/ppsspp-lang/blob/master/zh_CN.ini#L90

Maybe we need to specify something more for fallback.

-[Unknown]

**Comment by unknownbrackets** [comment]
Even using the font from https://github.com/hrydgard/ppsspp-lang/commit/81b27e3d9c56cc7246f95cde9e4dd64cb5c2f7ce, I'm not seeing this issue.  I suspect it may be different fonts that come with Windows 10, but I also tried smaller fonts missing these characters (like Century Gothic.)

Checked specifically with the SAO game title as well.

AFAICT, font fallback cannot be configured by apps until Windows 8.1 using DirectWrite, and I'm assuming this was an issue in Windows 7.

Given that, I think this is a Windows font bug, and I'm going to close.  But if anyone is still seeing this on Windows, please comment and we'll reopen.

-[Unknown]
