### ISSUE TITLE
Pursuit Force: Two minor errors

### ISSUE THREAD

**Issue by Anuskuss** [hrydgard/ppsspp#8444]
#### 1. Graphical glitch when using OpenGL

**Before Loading**
![](http://imageshack.com/a/img910/1441/4MV9wa.png)

**OpenGL**
![](http://imageshack.com/a/img908/3316/EN0oWt.png)

**DirectX9**
![](http://imageshack.com/a/img903/2465/iOdn7y.png)

#### 2. Transparency issue when using more than 1x PSP (look at speech bubble)

**1x PSP**
![](http://imageshack.com/a/img910/4687/5HNRof.png)

**3x PSP**
![](http://imageshack.com/a/img908/1669/wPE5eW.png)

**Comment by daniel229** [comment]
Seems fine for me in OpenGL.
![04](https://cloud.githubusercontent.com/assets/3481559/12382531/d16c94da-bdd5-11e5-9468-ce96ff7b51c9.png)

**Comment by unknownbrackets** [comment]
I suspect it's settings (a hack for example) in OpenGL, or else a card/driver that doesn't support dual source blending or something.  Or just driver bugs.

The transparency issue is a typical upscaling problem that we can't do a ton to fix.  See here:
http://forums.ppsspp.org/showthread.php?tid=13556

-[Unknown]

**Comment by Anuskuss** [comment]
I'll try different settings and update my stuff, so plese be patient before closing this issue.

**Comment by Anuskuss** [comment]
I figured out that the loading glitch was caused by *Multithreaded (experimental)*, and it also occurs with this option enabled on my iPhone 6. I don't know if you can fix this and if it's worth it (it doesn't affect gameplay, it just looks ugly for 2 seconds). I could live without Multithreaded because I don't really know if I get a benefit on my computer at all.

**Comment by hrydgard** [comment]
Yeah, our current multithreading mode is very unreliable. I have plans for a quite different one that should be more stable in the future, but it will be a while.
