### ISSUE TITLE
Weird bug with Star Ocean First Departure and ppsspp pause screen(D3D)

### ISSUE THREAD

**Issue by vsub** [hrydgard/ppsspp#8445]
You can't actually play the game in non buffered rendering mode but this problem seems weird

1.Switch to Direct3D and use Non Buffered Rendering
2.Start a new game and when you can control the character(without exiting the house),he won't appear(that's normal)until you start moving(and disappear again when you stop)

Now look carefully at the onscreen messages and the fps counter...the text goes behind things while moving and completely disappear when you are not.
And also the pause screen(Esc)is not displayed at all(black screen)

If you press triangle to go to the game menus,then the text and the pause screen is visible

**Comment by hrydgard** [comment]
Anything can happen in non-buffered, it's a pretty gross hack that works for some games and speed things up on weak hardware by rendering directly to the backbuffer. If it works, great, if it doesn't, too bad, it's probably not fixable and you should use buffered rendering instead.
