### ISSUE TITLE
Crash Mind over Mutant does not show anything except the videos.

### ISSUE THREAD

**Issue by deadair3210** [hrydgard/ppsspp#8456]
When booting the game, nothing but the movies showing the companies that made the game will show. The game still seems to play fine, as you can here things like Crash's footsteps and the menu noises, but the screen will be completely black
[ppsspplog.txt](https://github.com/hrydgard/ppsspp/files/94922/ppsspplog.txt)
Using Version - ppsspp-v1.1.1-736-g14fb4f2-windows-amd64
Video - https://youtu.be/e1joKQIzhcU

**Comment by vsub** [comment]
rev responsible
v1.1.1-621-gf081229
https://github.com/hrydgard/ppsspp/pull/8376
works fine with 612

**Comment by unknownbrackets** [comment]
Can you use the GE debugger to identify the draws that are not succeeding?  I want to see mainly the Settings and Vertices tabs.

If it's a red box covering the entire screen, it's no good.  Try to get a red area that looks like a flat red version of part of the background or a character or something you do expect to show up on screen.  Things that would show off screen aren't useful.

https://github.com/hrydgard/ppsspp/wiki/How-to-find-a-graphic-issue-with-the-GE-debugger

-[Unknown]

**Comment by vsub** [comment]
This is the loading screen when you see "Loading" at the center and steps appearing
Every single "Step Prim" results in either red screen or black screen with single red element while using 621

The only difference between 612 and 621 in vertacles is the color
![2016-01-18_235341](https://cloud.githubusercontent.com/assets/5032540/12403787/23c23ef6-be3f-11e5-9c19-5361962cef8e.jpg)
![2016-01-18_235716](https://cloud.githubusercontent.com/assets/5032540/12403843/7bf22a46-be3f-11e5-9e22-7b7973b6c70b.jpg)

**Comment by unknownbrackets** [comment]
Okay, the depth is a crazy number.  Can I see the settings tab?  I need to see mainly the viewport, depth test, and minz/maxz values.  Oh, and the Flags tab - would be nice to see if Clipping is enabled.

-[Unknown]

**Comment by vsub** [comment]
Hmm,everything in both versions is 100% the same in flags and settings

Min Z	000000
Max Z	00ffff
Viewport Scale	240.000000, -136.000000, 65536.000000
Viewport Offset	2048.000000, 2048.000000, 0.000000
Offset	1808.000000x1912.000000

Clipping is enabled
Name	Value
Lighting enable	0
Light 0 enable	0
Light 1 enable	0
Light 2 enable	0
Light 3 enable	0
Clip enable	1
Cullface enable	0
Texture map enable	1
Fog enable	0
Dither enable	0
Alpha blend enable	1
Alpha test enable	0
Depth test enable	1
Stencil test enable	0
Antialias enable	0
Patch cull enable	0
Color test enable	0
Logic op enable	0
Depth write disable	1

**Comment by unknownbrackets** [comment]
I'm not expecting any of those values to have changed.  We handled the values differently now (more correctly, mostly.)

Okay, clip enable looks like the problem here.  It's using viewport of 0 +- 65536, but these values are negative.  And depth testing is enabled.  So OpenGL is (incorrectly but sanely) clipping everything.  And the game is (unintentionally?) drawing everything with a clamped 0 depth.

So yeah, this needs the depth clamping I only just discovered earlier.  @hrydgard heh, already found one that needs it...

If you can compile on desktop, try this.  In GPU/GLES/StateMapping.cpp, find:

```c++
if (gstate.isDepthTestEnabled()) {
```

And add above it:

```c++
		if (gstate.clipEnable & 1) {
			glEnable(GL_DEPTH_CLAMP);
		} else {
			glDisable(GL_DEPTH_CLAMP);
		}
```

I'm not sure if that will work or not, but I'm interested to know if it will.

-[Unknown]

**Comment by vsub** [comment]
Sadly I can't compile it,someone else have to try it.

**Comment by vsub** [comment]
Btw I can post a save statestate that you can use.
You just have to open the cube demo=>open the GE=>step frame=>dragdrop the save state=>frame state and this will display the same results are running the game

**Comment by daniel229** [comment]
No,it doesn't work with that change.

**Comment by unknownbrackets** [comment]
Does #8461 help this?  I think it will, because I think this is a clamping issue.

-[Unknown]

**Comment by deadair3210** [comment]
If someone can provide a binary, i can test it. Would compile it but not exactly sure how since its not merged with the main branch

**Comment by daniel229** [comment]
Yes,https://github.com/hrydgard/ppsspp/pull/8461 does help it
