### ISSUE TITLE
Secret Agent Clank hangs after saving savestate

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8459]
Also happen in the demo.
![01](https://cloud.githubusercontent.com/assets/3481559/12409700/82a91404-bea7-11e5-8c20-cceb2c1e7403.png)

demo and the savestate and the video for how to reproduce.
https://drive.google.com/folderview?id=0BzGZGDfFE68zVGpsYm1sbTVGZU0&usp=sharing

**Comment by unknownbrackets** [comment]
Sorry, thanks for the reproduction steps.  Found it, silly mistake that has been there quite some time.

-[Unknown]
