### ISSUE TITLE
help :c how i can fix this?

### ISSUE THREAD

**Issue by tobutox** [hrydgard/ppsspp#8460]
(https://cloud.githubusercontent.com/assets/16771772/12411156/d349665e-be5a-11e5-9206-81a767248795.png)

**Comment by tobutox** [comment]
![rtr](https://cloud.githubusercontent.com/assets/16771772/12411253/ddec6452-be5b-11e5-92a0-0605753b006d.png)
-another pic

**Comment by daniel229** [comment]
The game looks fine for me.
Try update PPSSPP to the latest version.http://buildbot.orphis.net/ppsspp/index.php
Try setting on default.

**Comment by unknownbrackets** [comment]
As I recall, Gundam AGE Universe won't render properly without being able to copy depth buffers.  It probably won't work with an OpenGL 2.0 card or using Direct3D 9.  I think this is already covered by #1808.  Closing.

-[Unknown]
