### ISSUE TITLE
Dragon ball Z Tenkachi Tag Team graphical issues on NV Shield Portable

### ISSUE THREAD

**Issue by rhc77721** [hrydgard/ppsspp#8463]
when you play buffered rendering the main characters look dark and when you play with skip buffer effects everything looks great but when transforming a black ring appears and looks horrible. I'm using NVIDIA SHIELD portable

**Comment by unknownbrackets** [comment]
Are you using the latest git build?  If you're using v1.1.1, try updating, because we may have already fixed this.

-[Unknown]

**Comment by rhc77721** [comment]
Yes I'm using the latest 1.1.1-776 and the problems is there with the black models, but if i use the 1.1.1 with gold ppsspp instead of having black models the stage goes all green but the models look fine.

**Comment by unknownbrackets** [comment]
Does this happen even with default settings?  Skip buffer effects, disable slower effects, etc. may all impact this in that way.

-[Unknown]

**Comment by rhc77721** [comment]
Yes it does happen even in defAult settings I would like to send an image of how it looks, so that you see the issue.

**Comment by hrydgard** [comment]
Since the game works great on most hardware this is likely a driver bug. And since the NV Shield Portable is no longer being updated, it won't ever be fixed. Working around it is probably quite a bit of effort, so unless someone steps up, this is a wontfix.
