### ISSUE TITLE
Patapon video ends improperly

### ISSUE THREAD

**Issue by unknownbrackets** [hrydgard/ppsspp#8464]
Caused by #8437, here:
https://github.com/hrydgard/ppsspp/pull/8437/files#diff-7569aff64133d9c49602eec78c0dfd5bR1620

It keeps calling this over and over.  It seems like an off-by-one issue, because this makes the problem go away:

```
	if (ctx->mediaengine->IsNoAudioData()) {
		static int j = 0;
		if (j++ > 1) {
			result = ERROR_MPEG_NO_DATA;
		}
	}
```

-[Unknown]

**Comment by hrydgard** [comment]
@unknownbrackets Should be enough to revert c03f6c2 right, no need to revert 74d4011 ?

**Comment by unknownbrackets** [comment]
Right.  Basically it waits for a final audio frame after the last video frame.  So:

Current -
Game asks for last audio frame -> we say not there
Game asks again for last audio frame -> we say not there
etc.

Before:
Game asks for last audio frame -> we say not there
Game asks again for last audio frame -> we lie and say we have one

What I think is supposed to happen:
Game asks for last audio frame -> we give the last one
(Hypothetical) Game asks for another frame -> we say not there
etc.

-[Unknown]
