### ISSUE TITLE
[Android, device-specific] Black screen when launching the PPSSPP application.

### ISSUE THREAD

**Issue by LegalSouls** [hrydgard/ppsspp#8469]
I don't know what happened, but starting with v1.1.1-370 build and up to the last one (v1.1.1-797), I can't even launch the emulator. It shows black screen right after I launch the PPSSPP application. 
When I install v1.1.1-360 build or below, everything works fine. Were there any critical changes between 360 and 370 build? 
My device is Motorola Droid Razr HD (Android).
Is there any method to define why this is hapenning? Technically, the application is not crashing when in black screen, so it isn't creating any tombstones logs :(

**Comment by hrydgard** [comment]
Yes, I changed our initialization code to do the OpenGL initialization in C++ instead of using some Java code that didn't do exactly what we wanted. The new code works as well or better on all of my devices so it's surprising to me that it would break.

Can you get ADB logs from starting PPSSPP on your device?

**Comment by LegalSouls** [comment]
Yes, here's ADB logcat of blackscreen launch of build v1.1.1-370 of PPSSPP.
https://gist.githubusercontent.com/LegalSouls/948bd9c49bf64cf9c93a/raw/2665c3cfd49773d2142368c10a5d56132a44fa9c/UNsuccessful-ppsspp-launch-v1.1.1-370
The error is probably situated in the few last lines, I see some EGL_BAD_ATTRIBUTE there, whatever that means..

And here's a successful launch log from build v1.1.1-360 just for comparison.
https://gist.githubusercontent.com/LegalSouls/0e35acc9fc3b85f87ac0/raw/c3157e54c61761434ffcc95cbf56a92918105a63/successful-ppsspp-launch-v1.1.1-360

**Comment by hrydgard** [comment]
Thanks, that helps. I will change it later to try a simpler EGL config if it gets EGL_BAD_ATTRIBUTE.

**Comment by LegalSouls** [comment]
That's great, looking forward for it!

**Comment by hrydgard** [comment]
@LegalSouls  Does that change help?

**Comment by LegalSouls** [comment]
Last v1.1.1-819 build still gives the black screen at launch, here's the log, it became bigger this time.
https://gist.githubusercontent.com/LegalSouls/4c5ddf0ca7b46226c7b8/raw/23d95660c5e7444c9220aff3c57d79e5e1580788/UNsuccessful-ppsspp-launch-v1.1.1-819

**Comment by hrydgard** [comment]
Thanks, that will be helpful.

Argh, this EGL stuff in Android is just so broken and inconsistent..

**Comment by hrydgard** [comment]
Added some more "intelligence" to the format selection. @LegalSouls can you try it and report back with a log? :)

**Comment by LegalSouls** [comment]
Build v1.1.1-855, and it's still pitch black :\
https://gist.githubusercontent.com/LegalSouls/0f489747aded7bb0569d/raw/a15d18a5052df625150c032b17148748ecdad738/UNsuccessful-ppsspp-launch-v1.1.1-855

**Comment by unknownbrackets** [comment]
"Setting RENDERABLE_TYPE to EGL_OPENGL_ES3_BIT_KHR"

Seems odd.  It looks like this is happening?

```
				if (attribVal & (1 << 6)) /* EGL_OPENGL_ES3_BIT_KHR */
					supportsGLES3 = true;
```

Maybe it's better to assume that could be a lie and attempt `ctx_attribs[1] = 2;` on failure?

-[Unknown]

**Comment by hrydgard** [comment]
Ah! Yeah, that GPU definitely does not support ES 3. Should probably look at alternate detection methods, or as you say just fall back...

**Comment by hrydgard** [comment]
Alright, tried to just fall back to ES2 if ES3 fails. Test? :)

**Comment by LegalSouls** [comment]
It works! Thanks very much. 
And here's the successful log:
https://gist.githubusercontent.com/LegalSouls/b024c868075f6a8fb43c/raw/40545f0c47c19c53aa3bcb1d8e9cf61189644ede/Successful-ppsspp-launch-v1.1.1-861

**Comment by hrydgard** [comment]
Excellent! Thank you all the testing and logs!
