### ISSUE TITLE
Prince Of Persia Revelations sound issue

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8474]
- video sound problem
```
27:47:175 readThread   I[ME]: HLE\sceMpeg.cpp:349 First timestamp: 90000, Last timestamp: 723633
27:47:179 readThread   I[ME]: HW\MediaEngine.cpp:87 FF: No accelerated colorspace conversion found from yuv420p to rgba.
27:47:950 user_main    E[ME]: HW\SimpleAudioDec.cpp:190 Error decoding Audio frame (744 bytes): -1094995529 (bebbb1b7)
27:47:950 user_main    E[ME]: HW\MediaEngine.cpp:873 Audio (AT3+) decode failed during video playback
27:49:586 idle0        W[FileSys]: FileSystems\ISOFileSystem.cpp:573 Reading beyond end of file, clamping size 8192 to 6144
27:51:086 user_main    W[ME]: HLE\sceMpeg.cpp:1617 Audio end reach. pts: 721118 dts: 633633
```

~~- ingame sound lost after a while~~

~~log~~
~~https://gist.github.com/daniel229/12b92166ddc54499cfd5~~

**Comment by yuya495** [comment]
dead or alive paradise also lost after a while the sound of the game

**Comment by unknownbrackets** [comment]
Does any of the sceAtrac sound in the log play?  It seems like it plays through to completion, and the ends.  Is it supposed to loop, maybe?

-[Unknown]

**Comment by yuya495** [comment]
dead or alive paradise log
[ppsspplog.txt](https://github.com/hrydgard/ppsspp/files/100990/ppsspplog.txt)

**Comment by daniel229** [comment]
Yes,the sceAtrac in the log is played until 0=sceAtracReleaseAtracID(0)

**Comment by yuya495** [comment]
dead or alive　paradise is　I'm not sure why, but trying to change songs while another is still playing seems to break music output entirely.

**Comment by daniel229** [comment]
That sound is same as psp.

**Comment by unknownbrackets** [comment]
Can you log the first bytes of each frame?

```c++
if (!m_audioContext->Decode(audioFrame, frameSize, buffer, &outbytes)) {
```

Add before:

```c++
			NOTICE_LOG(ME, "Audio frame first bytes: %02x %02x %02x %02x", audioFrame[0], audioFrame[1], audioFrame[2], audioFrame[3]);
```

Most of the time, the first byte will be 3a or 3f.  I just want to see if it looks like garbage.

-[Unknown]

**Comment by daniel229** [comment]
The log
https://gist.github.com/daniel229/9d784ac8ac799be95447

**Comment by unknownbrackets** [comment]
Oh, so some of the frames parse fine.  Well, that's interesting.

Does any of the video's sound play?  Could you try extracting the video file and playing it with ffplay - just to make sure it's not a glitch in the file (maybe our error handling is bad, but that one error is normal)?

It's frame 41.  We could try skipping just that one frame:

```c++
		static int frameNum = 1;
		if (frameNum++ != 41) {
			if (!m_audioContext->Decode(audioFrame, frameSize, buffer, &outbytes)) {
				ERROR_LOG(ME, "Audio (%s) decode failed during video playback", GetCodecName(m_audioType));
			}
		} else {
			memset(buffer, 0, 8192);
		}
```

That's definitely wrong, but just wondering if it will prevent the error / fix the playback at all to not process that frame.  If so, it could either be error handling or something causing that packet to be incomplete.

-[Unknown]

**Comment by daniel229** [comment]
Audio seems fine with that error.

**Comment by daniel229** [comment]
Still got the error with that change

**Comment by unknownbrackets** [comment]
Maybe I counted wrong.. can you try 40 or 42?

-[Unknown]

**Comment by daniel229** [comment]
There are other videos before it

**Comment by daniel229** [comment]
It's 319.the error gone,and sound is still good.

**Comment by hrydgard** [comment]
So if it's just the game trying to play broken data, does the codecCtx_ end up in some kind of error state it can't recover from? Should we try to forcibly restart the decoding?

**Comment by daniel229** [comment]
Fixed by https://github.com/hrydgard/ppsspp/pull/8867

**Comment by unknownbrackets** [comment]
Oh, that makes a lot of sense.  I should've realized that's what was happening.  Thanks for checking.

-[Unknown]
