### ISSUE TITLE
Two problems with the UI

### ISSUE THREAD

**Issue by vsub** [hrydgard/ppsspp#8477]
I don't know if this is intended but:
1.The Browse and View Mode buttons are in wrong place(on the latest beta too)
![2016-01-22_194701](https://cloud.githubusercontent.com/assets/5032540/12518527/d70806e4-c141-11e5-8118-d06a63879d61.jpg)
https://github.com/hrydgard/ppsspp/pull/8291
2.Resizing\Maximizing\Go in/out of fullscreen always changes the active tab to Recent(run ppsspp=>go to games\homebrews=>maximize the window)

**Comment by unknownbrackets** [comment]
This does not occur for me.  You're supposed to have a path on the left side.  Does this happen when you first start clean in the latest git build?

What shows below?  Are you able to browse into and out of folders?  Does it keep happening even when you click into folders?

-[Unknown]

**Comment by vsub** [comment]
You are talking about which problem?

This is how it looks like on clean start with nothing configured.
I have a path when I go somewhere but the buttons are still on the left side(not like before).They are moved a little to the right based on the path length.
They don't have a fixed position like before

**Comment by unknownbrackets** [comment]
Hmm, okay.  I meant the first one.  Maybe my paths are too long?  But it doesn't happen for me in full screen...

The second one is probably not ideal, but it's because it recreates the entire screen on resize.

-[Unknown]

**Comment by vsub** [comment]
Yes,the first one seems to be fixed.
And about the second...if this is how it works(recreates the entire screen on resize),then ok,it's not a big deal

**Comment by unknownbrackets** [comment]
See also #8482.

-[Unknown]
