### ISSUE TITLE
G Generation World: missing characters

### ISSUE THREAD

**Issue by LightVR0** [hrydgard/ppsspp#8478]
v1.1.1-808-gd5539c4: missing japanese characters and V1.1.1 missing turn a letter.

**Comment by hrydgard** [comment]
Screenshots?

**Comment by LightVR0** [comment]
![missing letters](https://cloud.githubusercontent.com/assets/16720683/12526257/565be084-c14a-11e5-8e58-014dc497b609.png)

**Comment by unknownbrackets** [comment]
This sounds like the same as #8353 and I thought it was already confirmed working.  Are you really sure you're using v1.1.1-808-gd5539c4?

-[Unknown]

**Comment by daniel229** [comment]
It works fine for me.
![1](https://cloud.githubusercontent.com/assets/3481559/12527785/60e6ba38-c1bd-11e5-8b23-4e83ace5c3ce.png)

**Comment by daniel229** [comment]
I know now,broken in D3D9
![2](https://cloud.githubusercontent.com/assets/3481559/12527802/ac9e9856-c1bd-11e5-8390-617f7103933a.png)
