### ISSUE TITLE
Final Fantasy X-2 International - Video Issue when playing japanese video on title screen

### ISSUE THREAD

**Issue by deadair3210** [hrydgard/ppsspp#8479]
When playing the International version of Final Fantasy X-2, there is a video on the title screen that is in Japanese. If you select it, the video will play but will have horizontal lines and possibly the Playstation 2 Logo overlayed on top of it.

Version - pcsx2-v1.5.0-dev-165-g6dd83d3-windows-x86
Video - https://youtu.be/BrZdg5Jl4hY
Log with speedhacks - [log.txt](https://github.com/hrydgard/ppsspp/files/101631/log.txt)
Log without speedhacks - [log.txt](https://github.com/hrydgard/ppsspp/files/101632/log.txt)

**Comment by unknownbrackets** [comment]
I think you've opened this issue for the wrong emulator.

-[Unknown]

**Comment by deadair3210** [comment]
Oops. Sorry, was looking at some issues for both PPSSPP and PCSX2 and thought I hit new issue on the other one
