### ISSUE TITLE
Is this Android-specific setting still useful ?

### ISSUE THREAD

**Issue by vnctdj** [hrydgard/ppsspp#8480]
Since https://github.com/hrydgard/ppsspp/commit/516147680c6d4f836556ea0773391189c1796983, the following strings :

```
"Landscape", "Portrait", "Landscape Reversed", "Portrait Reversed"
```

are translated under [Graphics] as you can see at [line 202](https://github.com/hrydgard/ppsspp/commit/516147680c6d4f836556ea0773391189c1796983#diff-4590fd13d1b9a2766a764addc7174ad2R202).

But the same strings are already translated in an Android-specific setting [here](https://github.com/hrydgard/ppsspp/blob/afc212b2287caae451142fedd81bb6ced74b0cd4/UI/GameSettingsScreen.cpp#L520-L521) under [Controls].

The fix would be to re-use these translations by changing the pointer from _gr_ to _co_ (as we were already doing before).

But here is a question which comes to my mind : is this Android-specific setting still useful ?
Maybe I'm wrong, but it seems to be redundant...

**Comment by unknownbrackets** [comment]
Well, one locks the screen, the other rotates the display.  I'm not sure how useful, but one will affect whether the controls are rotated, and the other won't.

-[Unknown]

**Comment by vnctdj** [comment]
Ok, thanks :)

So, should the controls rotate independently of the display ?
If not, I guess the Android-specific setting is not useful, nope ?

**Comment by unknownbrackets** [comment]
Well, "Screen rotation":
 * Has an Auto setting which is always Portrait for me (bug??)
 * Rotates the UI.
 * Rotates the control layout.
 * Basically allows me to play games using [VVS] (https://www.youtube.com/watch?v=Bt9zSfinwFA).

In constrast, "Display rotation":
 * Keeps the controls the "normal way" on my device, just rotates the display.
 * Doesn't change the UI at all.

So I'm not sure.  I think you'd end up wanting to change both to play a portrait game, and neither seems to be per-game...

-[Unknown]

**Comment by hrydgard** [comment]
I think screen rotation needs a bit of a rethink maybe, but what we have can be used to play pretty much any game you want the way you want but with a bit of fiddling...

**Comment by vnctdj** [comment]
Oh ok, there are much more things to take into account than what I expected, thanks @unknownbrackets :)

Indeed @hrydgard , maybe we could enhance some things in this scope...

Therefore, for the moment, we should change the pointer as I said in my first comment, in order to fix the translations. I will submit a pull request in a few minutes :)

**Comment by vnctdj** [comment]
I think this issue is no longer applicable since we got the new string "Landscape Auto" which is Android-specific.
Therefore we now have different strings.

https://github.com/hrydgard/ppsspp/blob/36fd2711d6846a09b99e3f62dc7f88c9b66de545/UI/GameSettingsScreen.cpp#L680

https://github.com/hrydgard/ppsspp/blob/3e56d8bbdf0adfa268ee0a74cbe03ca21d8be31a/UI/DisplayLayoutScreen.cpp#L259
