### ISSUE TITLE
Metal slug xx ULUS10495 Atrac sound will stop after menu

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#8498]
v1.1.1-855-g5a0643
In menu stop 10 second will stop sound
Seem loop have problem.
11:46:641 CRI ADX Audi E[ME]: HLE\sceAtrac.cpp:560 avcodec_decode_audio4: Error decoding audio -1094995529 / bebbb1b7

log:https://gist.github.com/sum2012/e4d0878c1930aea228c1

As a fast test v1.1.1-569-g1a6217b work
log:
https://gist.github.com/sum2012/9d303d27d3a99618efd9

**Comment by sum2012** [comment]
Hmm ,fast test
bad
v1.1.1-697-gb2140d7
good
v1.1.1-685-g82c1f44

**Comment by sum2012** [comment]
@unknownbrackets 
Break by https://github.com/unknownbrackets/ppsspp/commit/a2417b4779bdc0b30511506794910c56d81c9f68 in #8435

**Comment by unknownbrackets** [comment]
The issue here is around looping.  Basically, the data was filled to the end, and then the game prepared to loop by sending some additional data near the loop start.

Then we hit the actual loop, and this reset the file offset back to the loop - forgetting the extra data the game had already added.  Then the game tried to decode more, without adding, since the data ought to be there... and it wasn't.

I have a change that fixes it, but I'm not sure it's right...

-[Unknown]

**Comment by daniel229** [comment]
still getting the error when you waiting long enough.
```
21:30:500 CRI ADX Audi I[ME]: HW\MediaEngine.cpp:87 FF: Frame data doesn't match channel configuration!
21:30:500 CRI ADX Audi E[ME]: HLE\sceAtrac.cpp:560 avcodec_decode_audio4: Error decoding audio -1094995529 / bebbb1b7
```
![2](https://cloud.githubusercontent.com/assets/3481559/12579328/1eb3c7f8-c462-11e5-8de1-87d547f0303b.png)

**Comment by unknownbrackets** [comment]
Darn, I think it's still happening around the same time, just when it's right outside the buffer or something based on the size?

The only option is to track the buffer completely, which needs to be done anyway.

-[Unknown]

**Comment by daniel229** [comment]
K-On! Houkago Live!! also broken.
Log
https://gist.github.com/daniel229/756922e23ec0cd95eea9

**Comment by benderscruffy** [comment]
using v1.3-692-g4c8aa77
had no problem with the music it loops properly now

**Comment by Panderner** [comment]
No problem. The music it loops properly

**Comment by hrydgard** [comment]
Ok, I guess we can close then. If anyone still has issues please comment or reopen.
