### ISSUE TITLE
B-Boy bgm stopped and missing sound effect

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8501]
Demo download 
https://drive.google.com/file/d/0BzGZGDfFE68zaWpJU0V4R093cTg/view?usp=sharing

Log for the BGM
https://gist.github.com/daniel229/58c9854d6470c4c8f174

savestate for bgm
https://drive.google.com/file/d/0BzGZGDfFE68zbF9XMllaZ05HM3c/view?usp=sharing

after loading savestate, waiting it stpped.
BGM stopped here
![01](https://cloud.githubusercontent.com/assets/3481559/12542898/32ec081a-c364-11e5-9d3d-0acc14dde169.png)

Log for sound effect seems like SAS
https://gist.github.com/daniel229/ff603b89c128007bac42

savestate for bgm sound effect
https://drive.google.com/file/d/0BzGZGDfFE68zQjh0R0dxRGJzYkU/view?usp=sharing

after loading savestate and press X button,there is a soundeffect
![02](https://cloud.githubusercontent.com/assets/3481559/12542955/e9b1baa4-c364-11e5-9f81-b3cafdc8cf83.png)

**Comment by unknownbrackets** [comment]
Seems like a timing problem, maybe...

```
55:23:142 Atrac31      N[ME]: HLE\sceAtrac.cpp:1307 00000000=sceAtracDecodeData(2, 08a8fdb4, 09fefa78[00000400], 09fefa74[00000000], 09fefa70[-1])
55:23:159 user_main    W[KERNEL]: HLE\sceKernelThread.cpp:2006 800201a4=sceKernelStartThread(285, 4, 09ffebb0): thread already running
55:23:159 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2014 -2147352156=sceKernelStartThread(285, 4, 09ffebb0)
55:23:161 Atrac31      I[ME]: HLE\sceAtrac.cpp:1661 0=sceAtracReleaseAtracID(2)
55:23:161 Atrac31      I[KERNEL]: HLE\sceKernelThread.cpp:2066 sceKernelExitThread(0)
```

I'm not sure what's triggering user_main to decide to start, but it's happening a hair too early.  If it happened after the exit thread, the music would restart, which I guess is what it's going for...

-[Unknown]

**Comment by benderscruffy** [comment]
have no problem so far 
this can be closed
