### ISSUE TITLE
BACKGROUND PPSSPP ANDROID

### ISSUE THREAD

**Issue by Endarko** [hrydgard/ppsspp#8512]
I no input for ppsspp, background ppsspp think in 2016 there must be a
change, let the users ppsspp not bored.

**Comment by unknownbrackets** [comment]
I'm not sure I understand.  Are you talking about background music, background images, or input while the app is in the background?

-[Unknown]

**Comment by Endarko** [comment]
I mean, ppsspp changed color from blue to yellow or golden yellow color
