### ISSUE TITLE
[Enhancement req.] PPSSPPUpdater Dev Builds

### ISSUE THREAD

**Issue by RinMaru** [hrydgard/ppsspp#8515]
Could we get an auto updater that checks and installs updates upon startup? Could include dev builds as optional.

**Comment by ppmeis** [comment]
@Zetchzie there's an updater already. They could add dev builds though.

**Comment by Zetchzie** [comment]
Is the updater not in the latest builds? i could never find that option.

**Comment by vnctdj** [comment]
*System* settings >> *Check for new versions of PPSSPP* ?

**Comment by Zetchzie** [comment]
ok found it lol ^^; Still be nice to have dev builds

**Comment by vsub** [comment]
Can someone explain how exactly this work.
I just tried all of the official releases in the download page that are older than the latest version but I couldn't figure out how this works.

Do I get some message or something else?
No msgbox,nothing in the console,nothing on the screen...it's like that option don't work(at least here)

I mainly use dev builds but I've never seen that option doing something while using dev or official builds

**Comment by hrydgard** [comment]
Hm, it has worked in the past but looks like I've forgotten to update the version file on the server for a few releases... I'll update it properly in 1.2.0. But it only will give alerts for major releases, not dev builds.

**Comment by vsub** [comment]
Ok,one more question...does this option work on dev build(when it actually worded on the official versions)or it only tells you that there is a newer official version only if you are using official version(not beta)

**Comment by unknownbrackets** [comment]
It ought to work on git builds as well, but there are two problems:

http://www.ppsspp.org/version.json
1. `"0.9.9"` is missing a trailing comma, so this json is probably failing to parse.
2. `"0.9.9"` is not actually the latest stable version.

So I don't think it will work on any version right now.  We could potentially list git versions there, but more likely the solution to that problem is to release stable versions more frequently.

-[Unknown]

**Comment by unknownbrackets** [comment]
I think this has been working more recently, not updated to 1.8.0 yet.  That said, no support for dev builds at this point.

-[Unknown]

**Comment by unknownbrackets** [comment]
It seems like this and #10002 are basically the same now.  I'm going to close this since that has more comments and this has (only recently) been about the version check not working for stable builds.

-[Unknown]
