### ISSUE TITLE
PPSSPP Build New Force Close

### ISSUE THREAD

**Issue by Endarko** [hrydgard/ppsspp#8517]
I just try ppsspp v1.1.1-870-g194e9ed on android, for playing games
often go out alone

**Comment by hrydgard** [comment]
More details please. What games crash? On what device?

**Comment by Endarko** [comment]
Games: PES, NEED FOR SPEED MOST WANTED, GTA VICE CITY STORIES, 

DEVICE: LENOVO A316i 
RAM: 512MB 
GPU: MALI-400MP

**Comment by Endarko** [comment]
Game: monster hunter freedom united.  Device: haier w858 cpu ARMv7 processor rev 3 (v7l) gpu adreno 305 RAM 1GB
Device: Samsung Star Duos Pro GPU:Mali RAm:512
Game: God Of War:chains of olympus

**Comment by unknownbrackets** [comment]
Can you try some older git builds?  If you can find the FIRST build that started crashing, and the LAST build that was working fine, it would help a lot.  That might help us find the problem very quickly.

Also, are these all happening with default settings?  Often, turning on hacks can cause crashes.

-[Unknown]

**Comment by Endarko** [comment]
I do not know what makes a game out alone while longer play. there
may be one script wrong: l
