### ISSUE TITLE
Tales of eternia broken nothing view (Black screen)

### ISSUE THREAD

**Issue by maximu** [hrydgard/ppsspp#8520]
Only heart sound 
Device : Samsung galaxy 3 neo 
GPU : Adreno 305 

I'll try that commit breaks I have not found him sorry ::(

**Comment by maximu** [comment]
I found where the game stops working 
In v1.1.1-585-g5037cd1 - https://github.com/hrydgard/ppsspp/commit/5037cd15e1afcc39a107dedd28dfdf528926557a  working  
v1.1.1-597-gb29f46f - https://github.com/hrydgard/ppsspp/commit/b29f46f9aca736320075973149f788c5be22edc7 not working

We needs test changes in v1.1.1-585-g5037cd1 to v1.1.1-597-gb29f46f  builds

**Comment by unknownbrackets** [comment]
https://github.com/hrydgard/ppsspp/compare/5037cd15e1afcc39a107dedd28dfdf528926557a...b29f46f9aca736320075973149f788c5be22edc7

Suspect #8347.  But, there were things broken by that commit that were fixed later, and these would've definitely affected Adreno 305 devices.  Are you sure it was broken at 481be1cd34e6a46cc940f4c6b150c3ef2a1d9086 as well?  That's v1.1.1-645-g481be1c.

-[Unknown]

**Comment by maximu** [comment]
With https://github.com/hrydgard/ppsspp/commit/481be1cd34e6a46cc940f4c6b150c3ef2a1d9086 you're right working in this rev.

But no working in the actual code  I'll keep looking for where rev broken in some devices.

**Comment by unknownbrackets** [comment]
This is probably the same as #8492 then.  Different devices being weird.  It also affects Ridge Racer on some devices.  I'm going to close this as a duplicate.

-[Unknown]
