### ISSUE TITLE
Saints Row: Undercover

### ISSUE THREAD

**Issue by Nmzik** [hrydgard/ppsspp#8522]
Seems Saints Row: Undercover is not working on PPSSPP 1.1.1 (endless logo when i start the game)

**Comment by daniel229** [comment]
Press X button.This game works fine in 1.1.1,but crash in the latest build.
![9](https://cloud.githubusercontent.com/assets/3481559/12672037/7b27914c-c6ae-11e5-82a6-16d0473c4396.png)

**Comment by Nmzik** [comment]
Whoops , sorry

**Comment by unknownbrackets** [comment]
So this worked in 1.1.1?  It's a pre-release, but as I understand they released it only because it worked in PPSSPP?

Would help if someone wants to bisect where it broke.  Maybe we can make it work.

-[Unknown]

**Comment by Nmzik** [comment]
Yeah, this game is working on ppsspp 1.1.1. My bad. You just need to click X on the logo

**Comment by hrydgard** [comment]
Culprit is d273deedeb28356c0028b759fcf48d7f5d8d8296 , so this is simply a 32MB/64MB RAM size detection issue - as this is some sort of pre-alpha, presumably it just assumes 64MB like on a devkit (I guess).

**Comment by hrydgard** [comment]
Here's info about the prototype, by the way:
https://www.unseen64.net/2016/01/25/saints-row-undercover-fall-psp-cancelled/

And the download, apparently released by Volition themselves so should be legal, as far as I can tell:
https://www.unseen64.net/saintsrowundercover/

**Comment by daniel229** [comment]
On PSP2000 with 661pro-c2,also need to enable 64mb ram to run.

**Comment by daniel229** [comment]
Add it to the HDmaster list,it works fine.
```
	{ "ULUS12345", 0x04000000, false }, // Saints Row 2
```
![2](https://cloud.githubusercontent.com/assets/3481559/12692362/ee54a1e6-c730-11e5-9f31-fddced4cca4a.png)

**Comment by unknownbrackets** [comment]
ULUS12345 is almost definitely placeholder.  I haven't checked it yet, but if there's a UMD_DATA.BIN with a reasonable hash, I think we can just add that and be done.  There's definitely good reason to attempt to retain support for an alpha release the developer made of a canceled game, imho.

UMD_DATA.BIN contains a `6E197A8FB304B3DB` which looks unique enough.  I think we should include that and put it in the remasters list, but mark it with a comment as an alpha release, e.g. `// Saints Row 2 / Undercover - alpha (needs extra ram, not a remaster)` or something.

I'm personally a fan of such moves by developers and it would be a huge shame IMHO if they went to the trouble releasing it (and that page mentions it does work in PPSSPP), only to have it not work in the latest version of PPSSPP.  So adding milestone.

-[Unknown]

**Comment by unknownbrackets** [comment]
Just saying, the download could be around 25% the size if they were distributing it as a .cso...

-[Unknown]
