### ISSUE TITLE
Monster Hunter Portable 3rd crash after save in Android

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#8524]
Do mission
Cancel mission
save
crash

crash log by @xiushudongfang 
https://gist.github.com/sum2012/1aa9266b77cd7622a9e9

Up to now test
v1.1.1-486-g842ff40 good
v1.1.1-488-g368eef5 bad

That mean #8328 

@hrydgard @unknownbrackets 
We still need fix hidden bug

**Comment by unknownbrackets** [comment]
In Dissidia 012, this crash is also happening.  It trapped when arm pc was 942fbb84.  I logged all the BKPT writes there... here's what it was overwriting:

```
  [0x942fbb78] b30405f0 MOVWLT r0, 45f0
  [0x942fbb7c] b3400885 MOVTLT r0, 0885
  [0x942fbb80] baf8114d BLT &001000BC
* [0x942fbb84] e59a2008 LDR r2, [r10, #8]
  [0x942fbb88] e3520001 CMP r2, #1
  [0x942fbb8c] e3a00001 MOV r0, #1
  [0x942fbb90] e58a0010 STR r0, [r10, #16]
  [0x942fbb94] 0a000003 BEQ &002FBBA8
  [0x942fbb98] e2577003 SUBS r7, r7, #3
  [0x942fbb9c] ea000005 B &002FBBB8
```

Which seems to put the mips pc into r0 - yay.  088545f0.  Here's the relevant mips in that area:

```
  088545E0	bne	a0,a1,pos_08854660
  088545E4	nop	
  088545E8	jal	pos_08A50140
  088545EC	nop	
* 088545F0	li	a0,0x1
  088545F4	bne	v0,a0,pos_08854660
  088545F8	nop	
```

I suppose this is either when compiling 088545F0, or when compiling the jal at 088545E8.

-[Unknown]

**Comment by unknownbrackets** [comment]
Debugged this some, found some potential issues, but still crashing.

```
23.222  EXIT ADDR = 088e9e60->08ad0810, NUM=0, 13198->13199 PROX:b=0,eb=0
29.838  EXIT ADDR = 088e9e60->08ad0810, NUM=0, 13198->18620 PROX:b=0,eb=0
41.656  EXIT ADDR = 088e9e60->08ad0810, NUM=0, 13198->24372 PROX:b=0,eb=0
```

So here, it's unlinked the block and relinked it.  That's one case where we definitely were handling things badly - we'd go past the previously written BKPTs.  That wasn't hard to fix.  I also added more safety around proxy blocks - to make sure we were never trying to write exits of a pure proxy.

Anyway, that didn't fix the above problem.  It's STILL trying to overwrite that block.  Here's a bit earlier, though, including the first instruction which it actually links (before that is the SUBS as expected):

```
43.075  EXIT ADDR = 088545e8->08a50140, NUM=0, 22365->29255 PROX:b=0,eb=0
  [0x94224afc] eaff0bf4 B &001E7AD4
  [0x94224b00] b30405f0 MOVWLT r0, 45f0
  [0x94224b04] b3400885 MOVTLT r0, 0885
  [0x94224b08] baf86d6b BLT &000400BC
* [0x94224b0c] e59a2008 LDR r2, [r10, #8]
```

It's indeed the jal, so here's what's happening: it's writing out a block exit directly (08a50140 is already compiled), but then 08a50140 is getting invalidated.  Now the epilogue is short.

Works with that.

-[Unknown]

**Comment by hrydgard** [comment]
@sum2012  this should work now, can you test?

**Comment by xiushudongfang** [comment]
@hrydgard @unknownbrackets  yes, fixed  Monster Hunter Portable 3rd.

**Comment by sum2012** [comment]
Thanks again @xiushudongfang
My phone does not have this issue
So that only he can test
