### ISSUE TITLE
Xyanide Resurrection freezing

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8526]
Seems like a scempeg bug
![5](https://cloud.githubusercontent.com/assets/3481559/12694260/a2e6e7be-c762-11e5-8162-c17dae9b035c.png)

log
https://gist.github.com/daniel229/15538499b882fcf3a39c

**Comment by hrydgard** [comment]
Did it ever work before?

**Comment by daniel229** [comment]
Not happen in v1.0.1-891-g1c67de0 ,but happen in v1.0.1-898-gbb96478
https://github.com/hrydgard/ppsspp/compare/v1.0.1-891-g1c67de0...v1.0.1-898-gbb96478

even not freezing in v1.0.1-891-g1c67de0,bu still has this error,
 ```
45:27:097 DecodeThread I[ME]: HW\MediaEngine.cpp:87 FF: Could not find codec parameters for stream 1 (Audio: mp3, 0 channels, s16p): unspecified frame size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
```

**Comment by unknownbrackets** [comment]
During the log you posted:

```
57:38:567 DecodeThread N[ME]: HLE\sceMpeg.cpp:1125 sceMpegAvcDecode(0990bc4c, 094c937c, 512, 094c94dc, 09fbda9c)
57:38:598 DecodeThread W[ME]: HLE\sceMpeg.cpp:1770 UNIMPL sceMpegFlushAllStream(0990bc4c)
57:38:598 DecodeThread N[ME]: HLE\sceMpeg.cpp:1669 UNIMPL sceMpegChangeGetAuMode(0990bc4c, 17, 1): changing type=0
57:38:598 DecodeThread N[ME]: HLE\sceMpeg.cpp:1669 UNIMPL sceMpegChangeGetAuMode(0990bc4c, 18, 0): changing type=0
57:38:598 DecodeThread N[ME]: HLE\sceMpeg.cpp:1386 128=sceMpegRingbufferAvailableSize(0946aebc)
57:38:598 DecodeThread N[ME]: HLE\sceMpeg.cpp:1448 sceMpegRingbufferPut(0946aebc, 27, 128)
57:38:600 DecodeThread I[ME]: HLE\sceMpeg.cpp:348 Stream offset: 2048, Stream size: 0x10C800
57:38:600 DecodeThread I[ME]: HLE\sceMpeg.cpp:349 First timestamp: 90000, Last timestamp: 900810
57:38:625 DecodeThread I[ME]: HW\MediaEngine.cpp:87 FF: More than one AAC RDB per ADTS frame
57:38:625 DecodeThread I[ME]: HW\MediaEngine.cpp:87 FF:  is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
57:38:625 DecodeThread I[ME]: HW\MediaEngine.cpp:87 FF: Sample rate index in program config element does not match the sample rate index configured by the container.
57:38:628 DecodeThread I[ME]: HW\MediaEngine.cpp:87 FF: Inconsistent channel configuration.
57:38:628 DecodeThread I[ME]: HW\MediaEngine.cpp:87 FF: get_buffer() failed
57:38:629 DecodeThread I[ME]: HW\MediaEngine.cpp:87 FF: Could not find codec parameters for stream 1 (Audio: aac (SSR), 3.0, fltp, 372 kb/s): unspecified sample rate
Consider increasing the value for the 'analyzeduration' and 'probesize' options
57:38:630 DecodeThread I[ME]: HW\MediaEngine.cpp:87 FF: deprecated pixel format used, make sure you did set range correctly
57:38:630 DecodeThread I[ME]: HW\MediaEngine.cpp:87 FF: No accelerated colorspace conversion found from yuv420p to rgba.
```

It seems to think that the video has aac audio.  I wonder if we're flushing wrong... maybe logging sceIo would help us understand if it's trying to play two different videos or just one?

-[Unknown]

**Comment by daniel229** [comment]
sceIo log
https://gist.github.com/daniel229/4e77d1541ce2c5544a63

**Comment by unknownbrackets** [comment]
It reads less data:

```
00:00:727 StreamThread N[IO]: HLE\sceIo.cpp:917 sceIoReadAsync(4, 093d5e6c, 6000): deferring result
```

And then seeks to the beginning:

```
00:00:738 StreamThread N[IO]: HLE\sceIo.cpp:1212 0 = sceIoLseekAsync(4, 0, 0)
```

It then flushes, which we survive, and then flushes again, which we don't.  Seems strange.

There's also stuff like this:

```
59:58:684 DecodeThread W[ME]: HLE\sceMpeg.cpp:1770 UNIMPL sceMpegFlushAllStream(0990bc4c)
59:58:685 DecodeThread I[ME]: HLE\sceMpeg.cpp:348 Stream offset: 2048, Stream size: 0x10C800
59:58:685 DecodeThread I[ME]: HLE\sceMpeg.cpp:349 First timestamp: 90000, Last timestamp: 900810
59:58:701 DecodeThread I[ME]: HW\MediaEngine.cpp:87 FF: Header missing
59:58:701 DecodeThread I[ME]: HW\MediaEngine.cpp:87 FF: Header missing
59:58:701 DecodeThread I[ME]: HW\MediaEngine.cpp:87 FF: Could not find codec parameters for stream 1 (Audio: mp3, 0 channels, s16p): unspecified frame size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
59:58:701 DecodeThread I[ME]: HW\MediaEngine.cpp:87 FF: deprecated pixel format used, make sure you did set range correctly
59:58:702 DecodeThread I[ME]: HW\MediaEngine.cpp:87 FF: No accelerated colorspace conversion found from yuv420p to rgba.
```

I suspect we're trying to decode garbage, or header data, or something we ought not to...

-[Unknown]

**Comment by sum2012** [comment]
v1.2.2-839-gfb05c05 same problem
log:
https://drive.google.com/file/d/0B3OaSdeV0L8kaEFMZ1hKT1Y1S1k/view?usp=sharing

**Comment by sum2012** [comment]
jpcsp hang earily with this log:
12499 [DecodeThread] WARN  hle.sceMpeg - Audio frame length 0x810 with incorrect header (header: 01 01 01 01 01 01 01 01)

**Comment by benderscruffy** [comment]
PPSSPP v1.5.4-997-g3472d62ff Windows 64 bit
still the same problem
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/2037957/ppsspplog.zip)

**Comment by benderscruffy** [comment]
@unknownbrackets 
from this thread http://forums.ppsspp.org/showthread.php?tid=1984
i tested all 3 that you uploaded and the game worked in all three
could you upload anything between v1.2.2-568 and v1.2.2-786 and i will test them to narrow it down

**Comment by unknownbrackets** [comment]
Will have to compile later.  Sounds like we're down to:
https://github.com/hrydgard/ppsspp/compare/v1.2.2-568-g63e730446...v1.2.2-786-gfa3f219fd

-[Unknown]

**Comment by unknownbrackets** [comment]
Here's one in the middle: [v1.2.2-680-g0519b3ef7.zip](https://github.com/hrydgard/ppsspp/files/2064695/v1.2.2-680-g0519b3ef7.zip)

-[Unknown]

**Comment by benderscruffy** [comment]
ok v1.2.2-614-g7814cdced.zip works
v1.2.2-680-g0519b3ef7.zip is broken
keep em coming

**Comment by unknownbrackets** [comment]
To narrow that range a bit to more likely commits:
https://github.com/hrydgard/ppsspp/compare/v1.2.2-614-g7814cdced...5da0375

Just gonna send the exe now, reuse the other files from v1.2.2-680-g0519b3ef7.

[v1.2.2-634-g606856c9a.zip](https://github.com/hrydgard/ppsspp/files/2065203/v1.2.2-634-g606856c9a.zip)
[v1.2.2-648-ge72cc3321.zip](https://github.com/hrydgard/ppsspp/files/2065204/v1.2.2-648-ge72cc3321.zip)
[v1.2.2-658-gce8d2bef5.zip](https://github.com/hrydgard/ppsspp/files/2065206/v1.2.2-658-gce8d2bef5.zip) - if only this fails, it's #8803.

The game has logged "bad video stream":
https://report.ppsspp.org/logs/game/NPEH00060_1.00
https://report.ppsspp.org/logs/game/ULES00634_1.01

And it seems to use both Psmf and Mpeg.

-[Unknown]

**Comment by benderscruffy** [comment]
ok v1.2.2-648-ge72cc3321.zip works
v1.2.2-658-gce8d2bef5.zip doesnt work

**Comment by unknownbrackets** [comment]
Okay so to confirm that even better, here's a build with #8803 reverted.  We still want those changes for sure, but this will confirm if the latest version works without them.  Again, just the exe - use with assets from v1.6.2 or the latest git build.

[revert-8803.zip](https://github.com/hrydgard/ppsspp/files/2065554/revert-8803.zip)

If that does, here's a few for partial reverts of that PR (I think the last 3 commits are most likely to be related):

[revert-8803-last3-c8d0270.zip](https://github.com/hrydgard/ppsspp/files/2065556/revert-8803-last3-c8d0270.zip)
[revert-8803-last2-4ee39f8.zip](https://github.com/hrydgard/ppsspp/files/2065557/revert-8803-last2-4ee39f8.zip)
[revert-8803-last1-04dcaea.zip](https://github.com/hrydgard/ppsspp/files/2065558/revert-8803-last1-04dcaea.zip)

I wonder what `mpegLibVersion` is being used here.  Last build - this will show a message with the mpegLibVersion so there's no question.  Maybe there's something funny happening here.

[mpeg-ver-alert.zip](https://github.com/hrydgard/ppsspp/files/2065560/mpeg-ver-alert.zip)

-[Unknown]

**Comment by sum2012** [comment]
I 1 years leave,good news hear from this game,
anyway revert-8803.zip don't work

**Comment by sum2012** [comment]
mpeg-ver-alert log
https://gist.github.com/sum2012/f579f3cdaec503539af7b32288819018

**Comment by unknownbrackets** [comment]
Okay, so it's using the firmware version which should be the latest.

Hmm: https://github.com/hrydgard/ppsspp/pull/8867#issuecomment-234754373 notes Xyanide impacted then, so presumably working when that was merged to some degree...

It gets tricky if two different things broke it.  We could try reverting 8803, 8867, 9014, and 9484.  If it's all related to Mpeg, those should be the PRs that cause it.  Want to try that or should I try to make a build?

-[Unknown]

**Comment by sum2012** [comment]
revert 8803 have tested fail. (You have made it to me to test)
For  8867, 9014, and 9484 , can you make a build? (I don't know how to resolve conflict)

**Comment by unknownbrackets** [comment]
Here's all of them reverted: [revert-8803-8867-90149484.zip](https://github.com/hrydgard/ppsspp/files/2065697/revert-8803-8867-90149484.zip)

-[Unknown]

**Comment by sum2012** [comment]
revert-8803-8867-90149484.zip don't work

**Comment by benderscruffy** [comment]
revert-8803.zip worked for me no problems
but
revert-8803-last3-c8d0270.zip
revert-8803-last2-4ee39f8.zip
revert-8803-last1-04dcaea.zip 
none of these worked

**Comment by sum2012** [comment]
@unknownbrackets I want to find out which commit in #8803 have problem ,  but checkout submodule error ,can you help me ? thanks 
![1](https://user-images.githubusercontent.com/2177532/41198459-5b29960c-6caf-11e8-9dbb-526819c53097.png)

**Comment by unknownbrackets** [comment]
Hmm... you might have to try `git submodule sync --recursive`.  I think it was pointing to a different git repo then, and `git submodule update` doesn't change repos of submodules.

It changed in this commit:
https://github.com/hrydgard/ppsspp/commit/b46bb1efdb77340e424dfdd02d50c59c0876ddc0#diff-8903239df476d7401cf9e76af0252622

-[Unknown]

**Comment by sum2012** [comment]
Thanks,that work.
A small finding in  v1.2.2-658-gce8d2bef5 
sometimes hang ,sometimes not hang .........

**Comment by unknownbrackets** [comment]
Ah - that could even mean it broke earlier on then, just not consistently.

-[Unknown]

**Comment by sum2012** [comment]
Hmm, v1.2.2-648-ge72cc3321 test 5 times not hang

**Comment by sum2012** [comment]
git bisect result:
https://github.com/hrydgard/ppsspp/pull/8803/commits/41f2999a2b53225276d893c072a3171f5fba71cd

garbage data can be proved from good log:
05:58:435 DecodeThread I[ME]: HLE\sceMpeg.cpp:351 Stream offset: 2048, Stream size: 0x10C800
05:58:435 DecodeThread I[ME]: HLE\sceMpeg.cpp:352 First timestamp: 90000, Last timestamp: 900810
05:58:465 DecodeThread I[ME]: HW\MediaEngine.cpp:85 FF: deprecated pixel format used, make sure you did set range correctly
05:58:465 DecodeThread I[ME]: HW\MediaEngine.cpp:85 FF: No accelerated colorspace conversion found from yuv420p to rgba.
05:58:718 RenderThread I[ME]: HW\MediaEngine.cpp:85 FF: error while decoding MB 26 9, bytestream -13
05:59:118 RenderThread I[ME]: HW\MediaEngine.cpp:85 FF: error while decoding MB 11 12, bytestream -11

**Comment by unknownbrackets** [comment]
Maybe this change is now truncating a frame (sometimes) at a ringbuffer boundary and it's not working properly or not providing more data the way we expect...?

https://github.com/hrydgard/ppsspp/commit/41f2999a2b53225276d893c072a3171f5fba71cd#diff-7569aff64133d9c49602eec78c0dfd5bL1447

Hm.

-[Unknown]

**Comment by sum2012** [comment]
I find out another bad change is https://github.com/hrydgard/ppsspp/pull/8867/commits/558b4620e8643ef46c1bf0d45cba5eae75e26860
pull 8867 + revert https://github.com/hrydgard/ppsspp/commit/41f2999a2b53225276d893c072a3171f5fba71cd + revert 
https://github.com/hrydgard/ppsspp/pull/8867/commits/558b4620e8643ef46c1bf0d45cba5eae75e2686 is okay.

But in the current master,maybe I revert some wrong https://github.com/sum2012/ppsspp/commit/6760c3d7eed991c9f02224f2c2fc3657375f51d0 , video suddenly become black.
I cannot do  myself  some more work to fix this.Hope you have idea to fix this,Thanks

**Comment by Panderner** [comment]
Same happens on latest build

this is a text that spams in the log when i encounter freezing
```
DecodeThread W[ME]: HLE/sceMpeg.cpp:1102 sceMpegAvcDecode(0990bc4c, 094c937c, 512, 094c94d8, 09fbda9c): mpeg buffer empty
```

**Comment by sum2012** [comment]
Update the log to v1.10.3-1052-gf3c05cb81-windows-amd64 
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/5469208/ppsspplog.zip)

**Comment by sum2012** [comment]
@shenweip Thanks again

**Comment by Panderner** [comment]
it's seems this game is broken again after #13663 Merge.

**Comment by shenweip** [comment]
> it's seems this game is broken again after #13663 Merge.

Oops, just a mistake.
