### ISSUE TITLE
Controls mapping without 1,2,3,4,5 ?

### ISSUE THREAD

**Issue by n1dminhd** [hrydgard/ppsspp#8527]
How can I put the keys 1,2,3,4,5 ?

![uljm05436_00000](https://cloud.githubusercontent.com/assets/4449742/12695204/a467325e-c778-11e5-91f0-89d1252fdd53.jpg)

**Comment by sum2012** [comment]
Controls->Combo key setup

**Comment by n1dminhd** [comment]
No, I know, I know
assign keyboard on 1,2,3,4,5

**Comment by sum2012** [comment]
Use key mapping software to do that

**Comment by n1dminhd** [comment]
key mapping not 1,2,3,4,5

**Comment by xiushudongfang** [comment]
You  can  map several keys to one physical key of the keyboard in Control mapping.

**Comment by n1dminhd** [comment]
Inconvenience
Not always used
