### ISSUE TITLE
The sound is louder than before after loading a savestate

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8528]
Since https://github.com/hrydgard/ppsspp/pull/8140
TOP for example.
![10](https://cloud.githubusercontent.com/assets/3481559/12696221/6f8d41dc-c79f-11e5-929e-45d6bcd25589.png)

**Comment by unknownbrackets** [comment]
Hmm, looks like we never propagate the reverb settings on load state.  Possibly might not be saving some of them...

-[Unknown]

**Comment by hrydgard** [comment]
@daniel229  did that change help?

**Comment by daniel229** [comment]
Yes,fixed it.
