### ISSUE TITLE
Broken translation in [DesktopUI]

### ISSUE THREAD

**Issue by vnctdj** [hrydgard/ppsspp#8529]
The "Display Rotation" string is not translated, here is a screenshot provided by @sum2012 :
![a3a29e86-c790-11e5-960e-fbee6f747d50](https://cloud.githubusercontent.com/assets/3978690/12696405/7080aaf0-c76a-11e5-92c4-9f8d2ddae6f7.jpg)

I don't know how to fix this issue... Did you forgot to do something in https://github.com/hrydgard/ppsspp/pull/8182, @LunaMoo ? ;)

**Comment by hrydgard** [comment]
Should really change the translation system to go by command instead of by menu position at some point...

**Comment by vnctdj** [comment]
Oh ok, it's indeed not very intuitive !
