### ISSUE TITLE
Tekken 5 Dark Resurrection Graphi Bug report 

### ISSUE THREAD

**Issue by AizerMortenort** [hrydgard/ppsspp#8548]
removed.

**Comment by hrydgard** [comment]
Seems odd. Do you have a video of what the laser looks like on the real PSP? 

For Soul Calibur, this is the issue: https://github.com/hrydgard/ppsspp/issues/7395  - and yeah, it hasn't been solved yet.

**Comment by AizerMortenort** [comment]
It looks exactly straight like the first laser beam I showed in the video where the normal version has no bugs at all. I can't record a real gameplay video on my PSP since it will take a lot of time converting files switching cables etc. The laser is exactly as the first time I did it but points downwards.

**Comment by hrydgard** [comment]
OK, got it.

**Comment by daniel229** [comment]
Also happen in PSP,I just try.

**Comment by hrydgard** [comment]
In that case, it's not a bug.

**Comment by AizerMortenort** [comment]
THAT'S NOT TRUE! 
It doesn't happen on real PSP I would have noticed it so far.

**Comment by daniel229** [comment]
JUst record one from PSP
https://youtu.be/gNHBJK_pm1o

**Comment by hrydgard** [comment]
Hm, it does seem to look a little bit different. We know we have some math bugs in the Tekken games due to the "shaking legs syndrome", so the difference may be related, if I'm not imagining it.

**Comment by ppmeis** [comment]
This is not a bug. As @daniel229 showed up, this effect only happens when laser path "touch" the camera. It also looks bigger because of the distance between character and camera.

**Comment by daniel229** [comment]
Yes,a bit different.

**Comment by AizerMortenort** [comment]
Weird... I don't remember this on my PSP. Let me check once the file is transferred. 
I apology if my memory served me bad. Let's see . 
Ahh yes the moving legs. Is there a fix to this.

**Comment by hrydgard** [comment]
There is no fix, if so #5399 would have been closed.

**Comment by AizerMortenort** [comment]
Anyway. Still great work so far. Waiting for transfer to complete.

**Comment by daniel229** [comment]
Even the same distance,still not exactly the same.
PSP
https://youtu.be/_Nzdri2DovQ

PPSSPP
https://youtu.be/nHbix1Qmqq4
