### ISSUE TITLE
Tekken 5 Dark Resurrection Graphic Bug report 

### ISSUE THREAD

**Issue by AizerMortenort** [hrydgard/ppsspp#8549]
Since someone landed with the lie this also happens on real psp in my first issue case -  it's not true. This has never happened on my PSP console when playing this game I wouldn't create an issue if the problem happens on PSP as well. 

Video Report of the bug
https://youtu.be/dBKQW73BCPc

This also happens in Tekken 6
Can the devs take a look.
Also what happened to Soul Calibur's missing color for textures when attacking opponents. The issue still remains unsolved.

**Comment by hrydgard** [comment]
Please continue in #8548

**Comment by unknownbrackets** [comment]
As a rule, please do not open new issues just because you don't like the discussion that's happening on the original issue.  It's not like it being closed means you can't comment or it can't be reopened.

-[Unknown]

**Comment by AizerMortenort** [comment]
Before jumping on me Unknown know that I wasn't been able to reopen my issue because no such option or button appear. I don't like how you jump and hate on me from previous comments. Learn to respect the others first then to ask for stuff!

**Comment by hrydgard** [comment]
@AizerMortenort You can comment even on closed issues.

**Comment by AizerMortenort** [comment]
Thank you Henrik. I can comment but cant reopen

**Comment by unknownbrackets** [comment]
Respect is a two way street.  I don't give much respect to people who don't show much.  You're asking people to fix things for free, just because you want them to.  Why aren't you following your own advice?

-[Unknown]

**Comment by AizerMortenort** [comment]
I was sure the issue doesn't happen on real PSP and I got angry for closing the issue so quick and being unable to reopen it. You don't even know me to judge me OK! You don't even know how much stuff I also have shared for free for the console scene and modding scene on PC! I apologized to daniel229 because I saw he showed proof behind his words in the end. You don't come to teach me what to do and what not ok! I don't care if you respect others or not . STAY OUT OF MY WAY!

**Comment by hrydgard** [comment]
@AizerMortenort You're way out of line here. Closing is not a final thing, and @daniel229 has earned a lot of trust, while you haven't, yet. If he says something happens on a real PSP, I believe him. Attacking @unknownbrackets is also obviously not a smart thing to do, given his immense contributions to the project. It's not really relevant here how much you have contributed to the scene in general as you certainly have not contributed a lot to PPSSPP yet.

This is the end of this discussion.

**Comment by AizerMortenort** [comment]
I don't care how much someone has contributed to something I don't like showing this either on my side. UnknownBrackets mackets I don't care what he has done after jumping on me several times.
