### ISSUE TITLE
question Core/Loaders.cpp

### ISSUE THREAD

**Issue by latot** [hrydgard/ppsspp#8555]
Hi, a little question: in this lines:
```
FileLoader *ConstructFileLoader(const std::string &filename) {
	if (filename.find("http://") == 0 || filename.find("https://") == 0)
		return new CachingFileLoader(new DiskCachingFileLoader(new RetryingFileLoader(new HTTPFileLoader(filename))));
	return new LocalFileLoader(filename);
}
```
the filename var can start with "http/https" or exist cases where the http/https is in the middle of the var?

Thx.

**Comment by hrydgard** [comment]
It does check that the position of "http://" or "https://" is equal to 0, which means that it will only use the http file loader when the URL begins with either of those two strings.

So I don't think there's an issue here.

**Comment by latot** [comment]
was only a question :D
