### ISSUE TITLE
Bug Buffered Rendering Mode Gods Eater Burst on latest build 1.1.1-912

### ISSUE THREAD

**Issue by ekkysw** [hrydgard/ppsspp#8563]
Gods Eater Burst have some bugs in build 1.1.1-912 in buffered mode
1. Opening Movie not appear
2. Preview item at menu select in battle mode not appear

**Comment by unknownbrackets** [comment]
Works fine for me.  On what device?  What's the first git build it stopped happening in, and the last git build it worked in?

-[Unknown]

**Comment by ekkysw** [comment]
Asus zenfone 4...last git build worked in 1.1.1-888 and last i try 1.1.1-912 this bug appear

**Comment by ekkysw** [comment]
Ok i solved this problem....

**Comment by unknownbrackets** [comment]
I'm guessing it was settings?

-[Unknown]

**Comment by ekkysw** [comment]
Yup, must checklist simulate transfer block effect
