### ISSUE TITLE
Two small problems

### ISSUE THREAD

**Issue by vsub** [hrydgard/ppsspp#8565]
That's not how you normally use ppsspp but:

Audio preview(first time)
1.Start ppsspp,right click on any game and exit using the back button
2.Use the arrow keys to navigate to a game that have audio preview(the audio is not played if the first game you select have audio preview...selecting another after that makes all of them to work)

Game background image and audio preview
1.Use the arrow keys(or the gamepad)to navigate to any game
2.Right click on the game(or some other game)and go back(you have to click twice because the mouse looses focus after using something other than the mouse to navigate...right click work but not left until you click twice)

PPSSPP will show the image as a background of the game you right clicked(rather than those moving buttons)and it will keep playing(if there is audio),the audio of the game on which you right clicked

Right clicking on any other game which has audio preview and going back will keep playing the audio of that game and it will keep showing the image as a background from the first game on which you right clicked.

The music will keep playing everywhere(including global settings)and the background will be displayed on all games lists(recent,games,homebrews)

You can also trigger this problem if you navigate to any game=>press triangle=>use the mouse to go back

To restore the default behavior,you have to either restart ppsspp or use the arrow keys(or the gamepad)to select a game(the mouse only can't fix this)

**Comment by hrydgard** [comment]
Still not perfect, but that should help a bit.

**Comment by unknownbrackets** [comment]
Hmm, I can't reproduce any of the other problems now?

-[Unknown]

**Comment by hrydgard** [comment]
If you select a game with the keyboard, then rightclick on _another_ game to get into the game screen, when you get back, it will fade from the wrong background image, but it's only wrong for a fraction of a second before it's normal :)

I can live with that.

**Comment by unknownbrackets** [comment]
Oh, heh.  I guess if we made right click also discard keyboard focus, it would fix that... seems pretty tiny though, indeed.

-[Unknown]
