### ISSUE TITLE
I got a black screen with tekken5

### ISSUE THREAD

**Issue by ordinaryparksee** [hrydgard/ppsspp#8567]
I can choose and start tekken iso file but nothing happens, and just black.
Here is my debug console.

![2016-02-09](https://cloud.githubusercontent.com/assets/7455855/12915026/785d6d40-cf6b-11e5-9804-8ffe5d18c6f1.png)

My os is Windows 10.

**Comment by sum2012** [comment]
Does the name same as Tekken Dark Resurrection ?
Does it also don't work in windows 7 or Android ?

**Comment by unknownbrackets** [comment]
I think this means an ISO that has been hacked.

-[Unknown]

**Comment by ordinaryparksee** [comment]
I leave more information

The iso image is tekken5 dark resurrection, And my android phone is can run tekken5 dark resurrection.

**Comment by unknownbrackets** [comment]
Well, one way or another, "could not read 2048 bytes from block" is a bad thing.  It probably means the ISO file is corrupt, truncated, broken, or otherwise messed up.

If it's exactly the same file on Android, maybe we're handling the error scenario differently.... which would be a bug.  But either way, I would check the crc and re-rip it from your PSP.

-[Unknown]

**Comment by vnctdj** [comment]
@unknownbrackets 
Could it be useful to implement in PPSSPP a system which check the CRC32 of the ISO at game launch, in order to avoid problems ?
Or maybe it would be too "expensive" for the device, especially on mobile... ?

**Comment by unknownbrackets** [comment]
Actually, I really think that might be a good idea.  I think you'd suggested it before, and I thought it'd never work on mobile, but I'm thinking different now.

We could crc the ISO in the background, on a thread, with probably little impact on overall performance.  This could be used for reporting (yay), and could potentially also be used to identify bad rips.

Additionally, crc'ing an ISO in the background would also likely load the ISO into memory on desktops with enough RAM, even if the "load full ISO into RAM" setting is disabled.

That being said, it might be a performance issue when the ISO is loaded via network (e.g. http://.)

-[Unknown]

**Comment by hrydgard** [comment]
I would be worried about battery drain. Accessing the flash is one of the more power-intensive things you can do on mobile.

**Comment by Zetchzie** [comment]
Runs just fine for me on latest git on Win10 x64

**Comment by unknownbrackets** [comment]
We do the crc thing for reporting now.  Since it looks like this was a bad disc, one way or another, closing.

-[Unknown]
