### ISSUE TITLE
Background default ppsspp

### ISSUE THREAD

**Issue by ekkysw** [hrydgard/ppsspp#8568]
Could i change background default ppsspp android? Maybe in the future, we can change background ppsspp with own image?

**Comment by ppmeis** [comment]
It could be a good idea. Please add on your title [Feature Request]. Just to know this is not a bug.

**Comment by xiushudongfang** [comment]
How about this ? You can select picture from picture explorer.But there are some bugs.
![screenshot_2016-02-12-19-09-06](https://cloud.githubusercontent.com/assets/8541580/13005534/77b97560-d1bd-11e5-9fe8-196570c82c96.png)
![screenshot_2016-02-12-19-09-11](https://cloud.githubusercontent.com/assets/8541580/13005536/77ba91fc-d1bd-11e5-8721-ea527d054de7.png)
![screenshot_2016-02-12-19-09-56](https://cloud.githubusercontent.com/assets/8541580/13005535/77ba9aee-d1bd-11e5-8da0-416a0341234d.png)

**Comment by ekkysw** [comment]
How do you get that build ?

**Comment by vgturtle127** [comment]
This could be cool, I do worry about people pulling 10MB+ 4K images off the internet and then crashing because of the size and resolution of the image. Or getting a weirdly formatted codec or something and having it crash that way. Or just bad performance due to the image being high resolution or having a large file size.

Maybe some sort of limitations for the image?

**Comment by xiushudongfang** [comment]
@vgturtle127   If you select 10MB+ 4K images or a weirdly formatted codec,it did not crash but the background will be black.  The format can be png or jpg.

**Comment by xiushudongfang** [comment]
@ekkysw  it is my build.

**Comment by ekkysw** [comment]
Wow its so cool can be that..i hope my ppsspp can change background that too :)

**Comment by vgturtle127** [comment]
@xiushudongfang Can we see the code? Maybe open a pull request?

I think png and jpg will satisfy everybody, good job. :smile: 

Did you try large images in your build? Why would it be black instead of just telling the user that the image resolution too high or something? Just curious.

**Comment by Endarko** [comment]
Version 1.2 can not change the background

**Comment by hrydgard** [comment]
@Endarko Of course not, that is just a proposed feature. Not implemented yet.

**Comment by Zetchzie** [comment]
This would be a nice feature Id like to have custom animated background support or gif support.

**Comment by xiushudongfang** [comment]
@vgturtle127  my code may be ugly and messy ,It  is base on 1.1.1-468 . I will rebase  it in several days. There are some problems and I don't know how to  solve these,although I use some hacks to make it work .I am not a programmer ,so my code might look strange and wrong ,but  useful.
Yes , I have tried large images ,and the background return default. Informing the user is a good idea.

**Comment by Endarko** [comment]
if I may try ppsspp have you? @vgturtle127

**Comment by Endarko** [comment]
f I may try ppsspp have you? @xiushudongfang

**Comment by vgturtle127** [comment]
@xiushudongfang If you wrote some code, then you are a programmer. Don't sell yourself short. :wink:

**Comment by xiushudongfang** [comment]
@Endarko  give me your email or send me

**Comment by Endarko** [comment]
this is my email end4rko@gmail.com @xiushudongfang

**Comment by xiushudongfang** [comment]
I have updated. The "Custom Background" branch. @vgturtle127

**Comment by EsKacang** [comment]
@xiushudongfang
Hey Bro, May i Try PPSSPP you Have?
Maybe I Can Fix The Problem :)

**Comment by vgturtle127** [comment]
@xiushudongfang Thanks!

**Comment by adityaStorm** [comment]
@xiushudongfang can i try your build ppsspp? I promise for not public your ppsspp please

**Comment by adityaStorm** [comment]
@xiushudongfang if you want, you can sent to my email : adityastormz@gmail.com i promise do not publicated your build :D

**Comment by vgturtle127** [comment]
@adityaStorm He released the source code, it is already public. If you want to try it, you will have to build the source code for yourself.

**Comment by adityaStorm** [comment]
@vgturtle127 Hmm where i can get my source code?

**Comment by vgturtle127** [comment]
@adityaStorm [HERE](https://github.com/xiushudongfang/ppsspp/tree/Custom-background-)

**Comment by adityaStorm** [comment]
@vgturtle127 i can't understand about that-_-

**Comment by vgturtle127** [comment]
@adityaStorm Probably best you wait until it is in the developer builds. You can get those [here](http://www.ppsspp.org/downloads.html#devbuilds).

**Comment by adityaStorm** [comment]
Thanks for your information :) ill be waiting

**Comment by brynijusan** [comment]
I actually have the Gold Android version of PPSSPP. When will you add the Background Change settings? getting really excited to it.

**Comment by unknownbrackets** [comment]
@xiushudongfang I've added a simplified version of the texture handling in #9501.

Want to try to rebase your changes with the Android dialog?  A few notes:
 * Don't worry about resume, it should work now.
 * After the user selects an image, call `NativeApp.sendMessage("bgImage_updated" , "");` to make it update.
 * I recommend using `System_SendMessage("bgImage_select", GetSysDirectory(DIRECTORY_SYSTEM));` to launch selection.  This will pass the directory to save the image in to Java.

-[Unknown]

**Comment by xiushudongfang** [comment]
Thanks a lot .I have no time to do this recently,but i'd like to do it when i am free.

**Comment by unknownbrackets** [comment]
This was implemented in #9653.

-[Unknown]
