### ISSUE TITLE
[ARM] ppge_atlas.cpp:610:60: error: use of undeclared identifier 'nanf'

### ISSUE THREAD

**Issue by sergiobenrocha2** [hrydgard/ppsspp#8569]
Is it a problem with newer version of clang and gcc? It's building fine on ubuntu 14.04 (clang = 3.4 and gcc = 4.8.4 )

It's weird that it was building fine until hrydgard/ppsspp-lang@c370729

```
clang++ -c -pipe -Wno-unused-function -Wno-unused-variable -Wno-strict-aliasing -fno-strict-aliasing -Wno-unused-parameter -Wno-multichar -Wno-uninitialized -Wno-ignored-qualifiers -Wno-missing-field-initializers -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -march=armv7-a -mtune=cortex-a8 -mfpu=neon -ftree-vectorize -O3 -ffast-math -fPIC -std=c++0x -Wall -W -D_REENTRANT -DUSING_QT_UI -DUSE_FFMPEG -DSHARED_SNAPPY -DSHARED_ZLIB -DSHARED_LIBZIP -DARM -D_ARCH_32 -DPPSSPP_GIT_VERSION="\"1.1.1\"" -D__STDC_CONSTANT_MACROS -DUSING_GLES2 -DQT_NO_DEBUG -DQT_CORE_LIB -I. -I../Common -I../../ppsspp-1.1.1 -I../ext/native -I../Core/MIPS -I../ext/xbrz -isystem /usr/include/arm-linux-gnueabihf/qt5 -isystem /usr/include/arm-linux-gnueabihf/qt5/QtCore -I.moc/Core -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -o .obj/Core/ppge_atlas.o ../Core/Util/ppge_atlas.cpp
../Core/Util/ppge_atlas.cpp:610:60: error: use of undeclared identifier 'nanf'
    {0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.0000f, -nanf, 0.0000f, 0, 0},  // ac02
                                                           ^
../Core/Util/ppge_atlas.cpp:611:60: error: use of undeclared identifier 'nanf'
    {0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.0000f, -nanf, 0.0000f, 0, 0},  // ac03
                                                           ^
../Core/Util/ppge_atlas.cpp:613:60: error: use of undeclared identifier 'nanf'
    {0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.0000f, -nanf, 0.0000f, 0, 0},  // ac05
                                                           ^
../Core/Util/ppge_atlas.cpp:614:60: error: use of undeclared identifier 'nanf'
    {0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.0000f, -nanf, 0.0000f, 0, 0},  // ac06
                                                           ^
```

https://launchpadlibrarian.net/237392044/buildlog_ubuntu-wily-armhf.ppsspp_1.1.1-r120.p4.l1715.a164.t83~43~ubuntu15.10.1_BUILDING.txt.gz

**Comment by hrydgard** [comment]
Huh, bizarre. We should not be generating NaN values in the atlas file...

**Comment by unknownbrackets** [comment]
This is probably something related to how the atlas is being built by your build scripts.  It could also be related to the fonts being used, e.g. this may not work with the officially packaged rasterized Arial characters.

Maybe the atlas just became too big with a few extra characters and the ttfs you're using.  Or maybe the ttf has a bad character in it with weird metrics.

-[Unknown]

**Comment by hrydgard** [comment]
The atlas generator can probably be easily fixed to avoid outputting a NaN there, which would be a good workaround until you find fonts that have all the chars...

**Comment by sergiobenrocha2** [comment]
@hrydgard typo

```
/«PKGBUILDDIR»/ext/native/tools/atlastool.cpp: In function 'void RasterizeFonts(const FontReferenceList&, std::vector<CharRange>&, float*, Bucket*)':
/«PKGBUILDDIR»/ext/native/tools/atlastool.cpp:430:5: error: 'dot' was not declared in this scope
     dot.voffset = 0;
     ^
```

**Comment by sergiobenrocha2** [comment]
I'm using these fonts btw, instead Arial (in the atlasscript.txt):

RobotoCondensed-Regular.ttf
LiberationSans-Regular.ttf
DejaVuSans.ttf
DroidSansJapanese.ttf
DroidSansHebrew-Regular.ttf
NotoSansThai-Regular.ttf
UnDotum.ttf

And these instead KozGoPro-Medium (in the ppge_atlasscript.txt):

DroidSans.ttf
DejaVuSans.ttf
NanumGothic.ttf
DroidSansJapanese.ttf
mona.ttf

**Comment by hrydgard** [comment]
@sergiobenrocha2  can you confirm that it's fixed with my fix? :)

**Comment by sergiobenrocha2** [comment]
Yeah, it's fixed, thanks!
