### ISSUE TITLE
Unable to make an Android build

### ISSUE THREAD

**Issue by Witiko** [hrydgard/ppsspp#8578]
Hi, I'm making an Android build of commit `5bfeafc` with a limited amount of success. (This is likely just my issue rather than a bug in the code base. I apologize if this is the wrong place to post.)

```
$ uname -a
Linux witiko 4.3.0-1-amd64 #1 SMP Debian 4.3.5-1 (2016-02-06) x86_64 GNU/Linux
$ yes | sudo apt install build-essentials
$ git pull --recursive https://github.com/hrydgard/ppsspp && cd ppsspp
$ git checkout 5bfeafc
$ NDK_VERSION=r9d
$ DIR=android-ndk-$NDK_VERSION
$ URL="http://dl.google.com/android/ndk/android-ndk-$NDK_VERSION-linux-x86_64.tar.bz2"
$ [ -d $DIR ] || curl "$URL" | tar xjv
$ # The android-8 platform in the archive lacks some required header files (EGL/egl.h).
$ sed -i '/--android)/s/${CMAKE_ARGS}/-DANDROID_NATIVE_API_LEVEL=android-9 &/' b.sh
$ ANDROID_NDK="$PWD"/$DIR ./b.sh --android
```

The libraries are built successfully, but there is an error at linkage time:
```
[  0%] Generating something_that_never_exists
[  0%] Built target cityhash
-- Found Git: /usr/bin/git (found version "2.7.0") 
[  2%] Built target kirk
[  2%] Built target GitVersion
[  6%] Built target Common
[  8%] Built target udis86
[  8%] Built target rg_etc1
[ 21%] Built target libzip
[ 25%] Built target png17
[ 26%] Built target vjson
[ 27%] Built target native_audio
[ 28%] Built target snappy
[ 28%] Built target xbrz
[ 29%] Built target xxhash
[ 29%] Built target sfmt19937
[ 40%] Built target GPU
[ 62%] Built target native
[ 63%] Linking CXX shared library ../android/libs/armeabi-v7a/libppsspp_jni.so
CMakeFiles/ppsspp_jni.dir/Core/MIPS/MIPSAsm.cpp.o:MIPSAsm.cpp:function MIPSAsm::MipsAssembleOpcode(char const*, DebugInterface*, unsigned int): error: undefined reference to 'runArmips(ArmipsArguments&)'
lib/libnative.a(app-android.cpp.o):app-android.cpp:function AndroidEGLGraphicsContext::Shutdown(): error: undefined reference to 'ANativeWindow_release'
lib/libnative.a(app-android.cpp.o):app-android.cpp:function AndroidEGLGraphicsContext::Init(ANativeWindow*, int, int, int): error: undefined reference to 'HostGL_CreateGLInterface()'
lib/libnative.a(app-android.cpp.o):app-android.cpp:function Java_org_ppsspp_ppsspp_NativeActivity_runEGLRenderLoop: error: undefined reference to 'ANativeWindow_fromSurface'
lib/libnative.a(native_audio.cpp.o):native_audio.cpp:function AndroidAudio_Resume(): error: undefined reference to 'OpenSLWrap_Init(int (*)(short*, int), int, int)'
lib/libnative.a(native_audio.cpp.o):native_audio.cpp:function AndroidAudio_Pause(): error: undefined reference to 'OpenSLWrap_Shutdown()'
collect2: error: ld returned 1 exit status
CMakeFiles/ppsspp_jni.dir/build.make:4224: recipe for target '../android/libs/armeabi-v7a/libppsspp_jni.so' failed
make[2]: *** [../android/libs/armeabi-v7a/libppsspp_jni.so] Error 1
CMakeFiles/Makefile2:419: recipe for target 'CMakeFiles/ppsspp_jni.dir/all' failed
make[1]: *** [CMakeFiles/ppsspp_jni.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 
```

Do you have any idea what the issue might be?

**Comment by unknownbrackets** [comment]
You probably want r10e:
http://developer.android.com/ndk/downloads/index.html
(note that it is no longer bzip2.)

It seems like that might be using CMake.  We don't actively use CMake for the Android build, we have a slightly more carefully tuned build for Android.  It might be nice if CMake worked for Android, but I'm not sure if the .neon and .arm stuff would work out.

https://github.com/hrydgard/ppsspp/wiki/Build-instructions#building-for-android

Anyway, you can just run this if you have ant setup, you don't need any Eclipse or IDE or anything, you don't even need to run ab:

    cd android/
    ant release -Dndkbuildopt="APP_ABI=armeabi-v7a -j6"

We normally do use `android-9`, but the CMake Android build is just unmaintained, I think.

-[Unknown]

**Comment by sum2012** [comment]
It is interesting to use this command
(I used to use ab.bat and Eclipse)

    cd android/
    ant release -Dndkbuildopt="APP_ABI=armeabi-v7a -j6"

However I fail
![1](https://cloud.githubusercontent.com/assets/2177532/13005520/66d157f4-d1bd-11e5-96ba-e7e887bc32f4.png)

**Comment by Witiko** [comment]
It would appear you need to either set the appropriate environment variables:

```
set ANDROID_HOME=/path/to/android-sdk/
set NVM=/path/to/android-nvm/
ant release [...]
```

or create a file `local.properties` in the `android/` directory with the following contents:

```
sdk.dir=/path/to/android-sdk/
ndk.dir=/path/to/android-ndk/
```

**Comment by sum2012** [comment]
Thanks, now [aapt] invalid resource directory name: E:\Project\test\292\ppsspp\android\bin\res/crunch
full log:https://gist.github.com/sum2012/fb4d4552d760d17e3bb3

**Comment by unknownbrackets** [comment]
You have to delete the android/bin folder when switching between using Eclipse and ant, iirc.

I'm not really sure why.  I forgot about that because I haven't used Eclipse to build ppsspp now in a long time.

And yes, thanks - still need to set the env vars.

-[Unknown]

**Comment by sum2012** [comment]
Thanks,after delete the android/bin folder.
Build success

**Comment by unknownbrackets** [comment]
Okay, I'm going to close this then - it sounds like it's working for both of you.

-[Unknown]

**Comment by Witiko** [comment]
I didn't get to it until now, but it does seem to be working. Thank you.

**Comment by sum2012** [comment]
If I use 1 st set method ,still fail.1
Seems that it did not read the ndk setting
```
set ANDROID_HOME=E:/QQDownload/adt-bundle-windows-x86_64-20140702/adt-bundle-windows-x86_64-20140702/sdk/
set NVM=/=E:/QQDownload/android-ndk-r10d-windows-x86_64/android-ndk-r10d/
ant release -Dndkbuildopt="APP_ABI=armeabi-v7a -j6"
```

![2](https://cloud.githubusercontent.com/assets/2177532/13019891/1eb5bcf8-d20d-11e5-982e-c1c563095cfa.png)
![3](https://cloud.githubusercontent.com/assets/2177532/13019894/234dbcfc-d20d-11e5-9607-a900a9fed853.png)

**Comment by sum2012** [comment]
I know that now.
It is typo

**Comment by sum2012** [comment]
Just update by @hrydgard 
The command should be 

ant release -Dndkbuildopt="-j6"

rather than

 ant release -Dndkbuildopt="APP_ABI=armeabi-v7a -j6"

(for support armv8)

**Comment by unknownbrackets** [comment]
Yes, that was just an example showing how args can be passed.  You can omit it as well, iirc.  `-j6` makes it use 6 cores for compilation, which depending on what CPU you have, may be too few or too many for your preference.

-[Unknown]
