### ISSUE TITLE
Phantasy Star Portable 2 crash at start with PPSSPP 1.2 in D3D9

### ISSUE THREAD

**Issue by Robsoie** [hrydgard/ppsspp#8593]
Hi, just tried PSP2 the new PPSSPP 1.2 release on x86 and during game load on its start up , PPSSPP crash with a "PPSSPP encountered a problem..." window error message.
I am using the Direct3D9 backend, in OpenGL that game does not seem to crash (or at least does not crash during the game load/startup as i have not played extensively with it in 1.2 ).
I tested a couple other games but they worked correctly, so i assume it's PSP2 specific.

I have been using 1.1.1 - 870 for x86 until then and PSP2 worked (and still work as i revert to this version to retest) greatly in Direct3D9 there.

I uploaded pictures of the console log to imgbox in case it may help to see what's going wrong
http://imgbox.com/R3wNo4GW
http://imgbox.com/4leJtZFW

**Comment by Robsoie** [comment]
Just tested the latest build , v1.1.1-949-ge954768 , and while the game still crashed, the console log added more messages that may be useful  
http://imgbox.com/NTfaS3By

**Comment by daniel229** [comment]
It looks fine for me,can you find out which is the first build start to crash,which is the last build working.

**Comment by Robsoie** [comment]
Note : it's only for D3D9 for that game, i don't see any problem with OpenGL

The last working version with PSP2 in D3D9 
ppsspp-v1.1.1-880-gb68f2de-windows-x86.7z

The first "crash on load" version for the same game
ppsspp-v1.1.1-882-ga1ff899-windows-x86.7z

**Comment by unknownbrackets** [comment]
Works fine for me as well.  I tried 32-bit and 64-bit Direct3D 9, and played through the intro until you can first swing your sword.  Make sure you're not using (a) cheats, (b) "read framebuffers to memory", (c) a broken iso.  Try with the default settings.  Also try updating your graphics drivers.

Does it not crash if you check "disable slow framebuffer effects"?

What video card are you using?  It shows in System Info.  Also, which version of Windows?

There are pretty careful guards, I thought, to bail in that code if you don't have INTZ support.  That's the only thing I can think would be crashing there.

-[Unknown]

**Comment by Robsoie** [comment]
Hi, the iso is correct, no cheat enabled, default settings. I'm using an Intel "card" (oddly, it's more OpenGL that has dodgy drivers than D3D ones on Intel, and surprisingly in OpenGL the game load correctly).
Now as you suggested i ticked "Disable Slower Effect (Speedup)" before launching the game, and ... it worked without any single crash.

It's strange, as there does not seem to be any kind of special effect during the game loading. And the oddity is that this crash on load does not happen for any other game i tried and didn't happened either on version of PPSSPP before ppsspp-v1.1.1-882-ga1ff899-windows-x86 .

Anyways, with "disable slower effect" it can confirm it works perfectly again with D3D9 , i don't even notice anything missing from the game visual once i am in actual gameplay, as i even played a full mission and defeated the boss of it before returning to the main base.

**Comment by daniel229** [comment]
With "disable slower effect",it get graphic artifact in some area in both OpenGLand D3D.
![01](https://cloud.githubusercontent.com/assets/3481559/13096309/781536c2-d553-11e5-805a-2e31b51d5029.png)

**Comment by Robsoie** [comment]
Just saw that one, it's on the missions taking place in the abandonned coal mine on planet Moatoob
Oddly this does not happen in mission using other maps that i re-tried so far.
Re-enabling while ingame the "slower effect" crash instantly ppsspp as expected if i use 882 and up, so it does not seem to be something that can happen only at the loading .
http://imgbox.com/2dLJAGxc

I guess i'll stick with my previous 870 version as there was no such problem :
http://imgbox.com/Zfubpkio

**Comment by sum2012** [comment]
It seems driver problem
@Robsoie what is your GPU ?
Can you try to update driver ?

**Comment by Robsoie** [comment]
It's an old Intel G41, using the latest available drivers, no more new drivers are made unfortunately for this "card" so if that's a driver problem it can't be solved, fortunately for me v1.1.1-880 run it perfectly so far so i'll just stick with it.

**Comment by sum2012** [comment]
@unknownbrackets 
We try to avoid crash to that code or blacklist the gpu ?

**Comment by unknownbrackets** [comment]
I suppose.  I'm thinking maybe it doesn't support INTZ, which means other old GPUs might be affected too, but I can't tell why the check wouldn't work...

I'd rather not blacklist explicitly because there's probably a whole class of GPUs that have this problem, just not super common since they're all on the older side.

-[Unknown]

**Comment by sum2012** [comment]
@Robsoie 
Does this build work ?
https://drive.google.com/file/d/0B3OaSdeV0L8kVDBtTHlXb0EtRWc/view?usp=sharing

**Comment by sum2012** [comment]
@Robsoie 
My sister netbook require this directx update to run it.(D3DX9_24  to D3DX9_29)
Can you also try to install it ? Thanks.
http://www.shdon.com/files/D3DX9_dll_update.zip

**Comment by Robsoie** [comment]
I already had the D3DX9_29 dll, it was part of the last DX9 update from microsoft (june 2010).

I tried your build and same problem, it crash during PSP2 is loading.
the console log at the time of the crash on your build show something similar in red to the other build
http://imgbox.com/MuXopSq5

Similarly as the ppsspp-v1.1.1-882-ga1ff899-windows-x86 and later builds too that crash in same condition, in OpenGL there's no crash with your build too.

**Comment by sum2012** [comment]
How about this ?
https://drive.google.com/file/d/0B3OaSdeV0L8kdlZyYWtud0JRMEE/view?usp=sharing
This should pop up more information when crash

**Comment by unknownbrackets** [comment]
Where are you logging?  What I'd be interested in is what's happening here:

https://github.com/hrydgard/ppsspp/blob/3acdd4e2372181ed493be86e756c3fd0e7896511/GPU/Directx9/helper/dx_fbo.cpp#L55

Does forcing `supportsINTZ = false;` fix this crash?  Is `supportsINTZ` even getting set to true on this card, and if so what is the value of `intzFormat`?  Maybe the driver is reporting it supports it, but it actually doesn't.

Looking at this more, though, maybe I should've checked also the D3DFMT_A8R8G8B8 format.  What happens if you change this:

```c++
HRESULT intzFormat = d3d->CheckDeviceFormat(D3DADAPTER_DEFAULT, D3DDEVTYPE_HAL, displayMode.Format, D3DUSAGE_DEPTHSTENCIL, D3DRTYPE_TEXTURE, FOURCC_INTZ);
supportsINTZ = SUCCEEDED(intzFormat);
```

To:

```c++
HRESULT displayINTZ = d3d->CheckDeviceFormat(D3DADAPTER_DEFAULT, D3DDEVTYPE_HAL, displayMode.Format, D3DUSAGE_DEPTHSTENCIL, D3DRTYPE_TEXTURE, FOURCC_INTZ);
HRESULT fboINTZ = d3d->CheckDeviceFormat(D3DADAPTER_DEFAULT, D3DDEVTYPE_HAL, D3DFMT_A8R8G8B8, D3DUSAGE_DEPTHSTENCIL, D3DRTYPE_TEXTURE, FOURCC_INTZ);
supportsINTZ = SUCCEEDED(displayINTZ) && SUCCEEDED(fboINTZ);
```

It may be that it only supports INTZ in combination with a 16-bit display buffer or D3DFMT_X8B8G8R8 or something.  I actually wonder if it's even necessary to check if it supports it for the display format... hmm.

-[Unknown]

**Comment by sum2012** [comment]
unknown,I gave him debug build,I test other computer that do not debug version of vs2013 runtime,It is interest that pop up what error message,
Anyway,I would give him your suggestion to compile to test after I come back home in 7 hours.

**Comment by sum2012** [comment]
@unknownbrackets I don't mean that "Is supportsINTZ even getting set to true on this card, and if so what is the value of intzFormat?"

**Comment by Robsoie** [comment]
Hello, sorry i didn't noticed you uploaded a debug build, so here's the console log from this debug build at the time it is crashing 
http://imgbox.com/ElpDVkib

and as the last 2 lines are cut by the window size, here's the cut part of them 
http://imgbox.com/4adCTIQJ

**Comment by sum2012** [comment]
@Robsoie  Did ppsspp pop up useful error message when crash ? (I don't mean console log)

**Comment by Robsoie** [comment]
It's only the generic window message "PPSSPP has encounted an error"... etc, so i don't think it's helpful
The additional information it gives is 
AppName: ppssppdebug.exe	 AppVer: 1.2.1.31	 ModName: ppssppdebug.exe
ModVer: 1.2.1.31	 Offset: 004438fe

And if i look in the "more" details at that kind of memory offset, there's just nothing listed
http://imgbox.com/0h3E6sjQ

**Comment by sum2012** [comment]
@Robsoie 
Try this build
It try to disable supportsINTZ
https://drive.google.com/file/d/0B3OaSdeV0L8kNmR3VTdEZWJKWlU/view?usp=sharing

**Comment by Robsoie** [comment]
Hello,
 I just tested your new build and this time it does not crash in D3D9 during loading , it probably confirm that there's some kind of problem between my card driver and this INTZ thing , it looks to be working the same as the version of PPSSPP i use currently (ppsspp-v1.1.1-880-gb68f2de-windows-x86)
http://imgbox.com/jtstP7yg
http://imgbox.com/CQKbgzgO

**Comment by sum2012** [comment]
@Robsoie Try this build
It may be that it only supports INTZ in combination with a 16-bit display buffer or D3DFMT_X8B8G8R8 or something

https://drive.google.com/file/d/0B3OaSdeV0L8kOVZPNkVKcGpta3c/view?usp=sharing

**Comment by Robsoie** [comment]
Hello,
This new build is working too, i could load the game in D3D9 and play around a bit without crashes too.
http://imgbox.com/d0VV4gu2
http://imgbox.com/eCalpjR5

But i noticed something, i don't know if it's related or if it's a completely different new problem but in the mission selection previews (to the upper right of the screenshot), the image is wrong
http://imgbox.com/N9A4LxBi.

This didn't happened on the previous build you uploaded, the preview image was correct

**Comment by unknownbrackets** [comment]
I think the image being wrong is related to 8a39794c47dfe44832246ce51323d2e86b056348.  I don't thin it's related to these changes.

So is `supportsINTZ = SUCCEEDED(displayINTZ) && SUCCEEDED(fboINTZ);` the version that worked?  That seems safe enough.

-[Unknown]

**Comment by sum2012** [comment]
@Robsoie so last (?) test build: try to revert https://github.com/hrydgard/ppsspp/commit/8a39794c47dfe44832246ce51323d2e86b056348 

https://drive.google.com/file/d/0B3OaSdeV0L8kdzZTTjNxaXM3T0U/view?usp=sharing

**Comment by Robsoie** [comment]
Hello, i just gave a try to your new build, but the mission preview is still wrong
http://imgbox.com/CDykyWEX

**Comment by sum2012** [comment]
@Robsoie how about this build ?
It is same as above ppsspp 's same git version but disable supportsINTZ
https://drive.google.com/file/d/0B3OaSdeV0L8kWkl4UEFCUVllemc/view?usp=sharing

**Comment by Robsoie** [comment]
Hello, this build display the mission preview correctly
http://imgbox.com/oLXnmiHm

Odd that it seemed to affect only that mission picture but not the background universe image that the planets are rotating in front of.

**Comment by sum2012** [comment]
@unknownbrackets 
So is `supportsINTZ = SUCCEEDED(displayINTZ) && SUCCEEDED(fboINTZ);` version not work correctly

**Comment by unknownbrackets** [comment]
So you're saying:

1. The current master's supportsINTZ detection causes crashes.
2. `supportsINTZ = SUCCEEDED(displayINTZ) && SUCCEEDED(fboINTZ);` presumably causes it to have `supportsINTZ = false;`, but causes glitches.
3. `supportsINTZ = false;` works fine.

Is that right?  You said you reverted 8a39794, which I don't understand.  That commit would've probably fixed issues, so reverting it would bring them back.  Did the first build you sent, which didn't crash, already have 8a39794 in it?

I feel like logically, `supportsINTZ = SUCCEEDED(displayINTZ) && SUCCEEDED(fboINTZ);` on the current master, without reverting anything, ought to work.  If it doesn't work, I'd like to understand why it causes that weird corruption and `supportsINTZ = false;` doesn't.  If that is the case, I guess it must mean `supportsINTZ = true;` still, but somehow without crashes.

-[Unknown]

**Comment by sum2012** [comment]
@unknownbrackets Yes 1,2,3 points are right
last test https://github.com/hrydgard/ppsspp/issues/8593#issuecomment-200803472 doesn't revert https://github.com/hrydgard/ppsspp/commit/8a39794c47dfe44832246ce51323d2e86b056348

**Comment by unknownbrackets** [comment]
Right but https://github.com/hrydgard/ppsspp/issues/8593#issuecomment-200314712 you reverted it, I don't understand why?

And the one before that, https://github.com/hrydgard/ppsspp/issues/8593#issuecomment-199450749, was created after 1970d3865059647585bd0a46c7e761d76a4d8a2d, so probably has the bug that 8a39794 fixed.

So I think `supportsINTZ = SUCCEEDED(displayINTZ) && SUCCEEDED(fboINTZ);` DOES work, but one of the test builds simply included a totally separate Direct3D9 bug that has been since fixed on master.

-[Unknown]

**Comment by sum2012** [comment]
@unknownbrackets So do you let me give him v1.1.1-882-ga1ff899 with  `supportsINTZ = SUCCEEDED(displayINTZ) && SUCCEEDED(fboINTZ);`  version ?

**Comment by Robsoie** [comment]
Hello, after reading the " d3d9: Check actual FBO format for INTZ support #8665 " i gave a try to the latest build , ppsspp-v1.2.2-230-g4ad0af4 , and it seems to fix the crash and image preview
http://imgbox.com/oBKVOOwj
http://imgbox.com/KwwmZegP

So it seems the problem is fixed, at least for what concern my system as apparently it worked for other people

**Comment by hrydgard** [comment]
Great! I'm closing, let's reopen if we get any more reports.

**Comment by Robsoie** [comment]
Playing a bit with this version, i noticed a very old problem seems to have a resurfaced 
http://imgbox.com/CV5z68kw

Sometime (as it's not constant), when you're moving/rotating the view, it can happen that you see some lights through walls, like in the case of that screenshot, some of the lights that were in the tunnel behind the rock.

I say very old problem, because i remember this could happen in older versions of PPSSPP, but you had fixed it at some point, as on the PPSSPP version i was actively playing with, v1.1.1-880-gb68f2de , this didn't happened anymore

I do not know if it's related to the whole ordeal between my chipset D3D9 drivers and the FBO/INTZ or if it is a new (at least since  v1.1.1-880-gb68f2de as i couldn't test further version in D3D9 with that game due to the crash that got recently fixed) problem
