### ISSUE TITLE
Chinese font issue

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#8596]
@hrydgard 
You have re-build font atlas but why still miss font ? Thanks
(It is in [Dialog] Confirm Save )
![1](https://cloud.githubusercontent.com/assets/2177532/13047913/5588e1f8-d41d-11e5-951f-2bd7cf24c2f7.jpg)

**Comment by hrydgard** [comment]
Oh it's the "ppge_atlas". In this case it's harder because the text can be supplied by the game...

**Comment by sum2012** [comment]
No,the text is from here
https://github.com/hrydgard/ppsspp/blob/b5959be2eca8f0065f3d172d826c86532f26850b/chinese.txt#L222

**Comment by hrydgard** [comment]
Oh, ok. I'll get it done

**Comment by sum2012** [comment]
Thanks :)

**Comment by hrydgard** [comment]
@sum2012  I have updated it, can you have a look?

**Comment by sum2012** [comment]
Yes,fixed , thanks again
