### ISSUE TITLE
K-On Houkago Live Issues

### ISSUE THREAD

**Issue by ModiFlasher** [hrydgard/ppsspp#8598]
For this Update 1.2.0.0 so may bug for this game
1. For first Song "Watashi no Koi wa Hotch Kiss" when before finish video its stuck but notes still play
2. For Main menu Music not continous play its stop anyway
3. For song Mezase Happy 100%↑↑↑ Thats no show Music Preview

**Comment by Panderner** [comment]
The game works perfectly on latest builds

**Comment by Panderner** [comment]
But please note that main menu music stops playing after first loop.

**Comment by sum2012** [comment]
@Panderner Will you open another issue for music stops playing problem ?
