### ISSUE TITLE
[Windows] PPSSPP Exit crash

### ISSUE THREAD

**Issue by Anuskuss** [hrydgard/ppsspp#8600]
I don't know if I have read it somewhere, but I also have problems when exiting PPSSPP through the GUI.

###### PPSSPP has stopped working
`A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available.`

[Debug] [Close program]

**Comment by sergiobenrocha2** [comment]
Maybe related to #8026 ?

**Comment by Anuskuss** [comment]
Maybe... how can I make sure? Tell me @sergiobenrocha2

**Comment by Anuskuss** [comment]
If found out what the problem was (kinda).

`ppsspp.ini -> [Recent]`
If there was a .iso noted within `FileNameX`, **PPSSPP** would sometimes crash (start, exit, repeat).
When I deleted the entries, it doesn't crash anymore.

Also it seems that it doesn't happen on **1.2.1**. I will reopen if it happens again.

**Comment by hrydgard** [comment]
Hm, I'd like to fix this properly. Are you able to manually modify a ppsspp.ini enough to get it to crash? If so, can you paste the [Recent] section here?

**Comment by Anuskuss** [comment]
![Change .png to .mp4](https://cloud.githubusercontent.com/assets/7157389/13234553/81b7d24c-d9b9-11e5-9b79-962017c6d479.png)

**Comment by Anuskuss** [comment]
[Change .txt to .mp4](https://github.com/hrydgard/ppsspp/files/141516/PPSSPP.txt)
