### ISSUE TITLE
Jak and Daxter - The Lost Frontier (hangs)

### ISSUE THREAD

**Issue by Levan7** [hrydgard/ppsspp#8606]
This game keeps randomly hanging 
update: it's not random it hangs when game is loading new locations 

Here is a part of output
`
51:54:291 video_sound_ E[CPU]: MIPS\MIPSInt.cpp:169 BREAK!
51:54:291 video_sound_ E[CPU]: MIPS\MIPSInt.cpp:169 BREAK!
51:54:291 video_sound_ E[CPU]: MIPS\MIPSInt.cpp:169 BREAK!
51:54:291 video_sound_ E[CPU]: MIPS\MIPSInt.cpp:169 BREAK!
51:54:291 video_sound_ E[CPU]: MIPS\MIPSInt.cpp:169 BREAK!
51:54:291 video_sound_ E[CPU]: MIPS\MIPSInt.cpp:169 BREAK!
51:54:291 video_sound_ E[CPU]: MIPS\MIPSInt.cpp:169 BREAK!
51:54:291 video_sound_ E[CPU]: MIPS\MIPSInt.cpp:169 BREAK!
51:54:292 video_sound_ E[CPU]: MIPS\MIPSInt.cpp:169 BREAK!
51:54:292 video_sound_ E[CPU]: MIPS\MIPSInt.cpp:169 BREAK!`

here is the full output 
http://slexy.org/view/s21sFuso41

**Comment by sum2012** [comment]
Does this build fix ?
Just give memory check in the Replace_memcpy_jak
https://drive.google.com/file/d/0B3OaSdeV0L8kMmtxNXNUejRTc00/view?usp=sharing

**Comment by Levan7** [comment]
I don't know if i messed up because I didn't understand the language and I think I created a custom profile for this game but **the problem still exists**

here is the output 
http://paste.ubuntu.com/15230839/

**Comment by sum2012** [comment]
Does v1.3-540-g29739c8 or newer version fixed ?
http://buildbot.orphis.net/ppsspp/

**Comment by Levan7** [comment]
Update I managed to finish this game on the emulator it didn't hang on me
