### ISSUE TITLE
PPSSPP Force Close in android

### ISSUE THREAD

**Issue by Tktw** [hrydgard/ppsspp#8618]
App does not run in Android newest build version and google play
not run : v1.2.1-31-g9bde45d
work : v1.1.1

Device: SHL22
Android 4.2.2

CPU
Qualcomm Snapdragon 600
Processor : ARMv7 Processor rev 0 (v7l)

RAM : 2GB

GPU/Graphics
Renderer Adreno (TM) 320
Vendor Qualcomm
Version OpenGL ES-CM 1.1

**Comment by hrydgard** [comment]
Any chance you could get some ADB logs?

**Comment by Tktw** [comment]
Excuse me　I don't know how to use the ADB.

**Comment by Tktw** [comment]
I'm not sure, but the log
[ADB_log.txt](https://github.com/hrydgard/ppsspp/files/153080/log.txt)

**Comment by asl97** [comment]
@Tktw as far as I can tell, your log doesn't contain any useful information.
____
@hrydgard my logs using `adb logcat -c; adb logcat -s "DEBUG" > ppsspp-log-asl97.txt`

hopefully I didn't filter out important information.

[ppsspp-log-asl97.txt](https://github.com/hrydgard/ppsspp/files/175270/ppsspp-log-asl97.txt)

**Comment by unknownbrackets** [comment]
That's super interesting:

```
I/DEBUG   (  285):     #00  pc 00019988  /system/lib/libc.so (strlen+72)
I/DEBUG   (  285):     #01  pc 0000f8fd  /system/lib/libutils.so (android::String8::setTo(char const*)+8)
I/DEBUG   (  285):     #02  pc 0000c943  /system/lib/libEGL.so
I/DEBUG   (  285):     #03  pc 0000c613  /system/lib/libEGL.so (android::egl_display_t::makeCurrent(android::egl_context_t*, android::egl_context_t*, void*, void*, void*, void*, void*, void*)+106)
I/DEBUG   (  285):     #04  pc 0000e90f  /system/lib/libEGL.so (eglMakeCurrent+234)
```

So it crashed in strlen, fault addr = 0...

(warning hash is from random search...)
https://android.googlesource.com/platform/frameworks/native/+/3292cae8c37fc8d7cd8bf77fafaa55e6fc7a8cc5/opengl/libs/EGL/eglApi.cpp#519

So somewhere here:

https://android.googlesource.com/platform/frameworks/native/+/3292cae8c37fc8d7cd8bf77fafaa55e6fc7a8cc5/opengl/libs/EGL/egl_display.cpp#351

Anyway, my top suspect so far...

```c++
void egl_context_t::onMakeCurrent(EGLSurface draw, EGLSurface read) {
    this->read = read;
    this->draw = draw;

    /*
     * Here we cache the GL_EXTENSIONS string for this context and we
     * add the extensions always handled by the wrapper
     */

    if (gl_extensions.isEmpty()) {
        // call the implementation's glGetString(GL_EXTENSIONS)
        const char* exts = (const char *)gEGLImpl.hooks[version]->gl.glGetString(GL_EXTENSIONS);
        gl_extensions.setTo(exts);
        if (gl_extensions.find("GL_EXT_debug_marker") < 0) {
            String8 temp("GL_EXT_debug_marker ");
            temp.append(gl_extensions);
            gl_extensions.setTo(temp);
        }

        // tokenize the supported extensions for the glGetStringi() wrapper
        std::stringstream ss;
        std::string str;
        ss << gl_extensions.string();
        while (ss >> str) {
            tokenized_gl_extensions.push(String8(str.c_str()));
        }
    }
}
```

Are we somehow getting a core profile or something?

-[Unknown]

**Comment by ThePhoenixRises** [comment]
Just noticed his device only has Version OpenGL ES-CM 1.1 - surely that's the problem it's not version 2 or upwards.

**Comment by hrydgard** [comment]
It's an Adreno 320 - that's definitely good enough. Don't know what's up with that version number.

**Comment by asl97** [comment]
@hrydgard just wanted to say mine is Adreno 305 but it should support the same thing as an Adreno 320 even though it is less powerful.

**Comment by hrydgard** [comment]
Try with the latest build from the buildbot: http://buildbot.orphis.net/ppsspp/

**Comment by Tktw** [comment]
work!
Thank you,hrydgard.

**Comment by Enyby** [comment]
Maybe need close this issue because author reported about work on new builds.
