### ISSUE TITLE
dai-2-ji super robot taisen z screen mess up

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8625]
Since https://github.com/hrydgard/ppsspp/pull/8613
![01](https://cloud.githubusercontent.com/assets/3481559/13552797/abd2d260-e3ab-11e5-8945-ba026cade344.png)

before
![02](https://cloud.githubusercontent.com/assets/3481559/13552798/abd964b8-e3ab-11e5-9c1d-888a2d8dbeac.png)

**Comment by daniel229** [comment]
Brave Story also.

**Comment by Tktw** [comment]
Same issue METAL GEAR  series (OPS+, ACID, ACID2)
ppsspp-v1.2.1-24-gf9ec9d5 or later.

**Comment by hrydgard** [comment]
Hm, very interesting. I'll check it out.

**Comment by Kingcom** [comment]
@hrydgard I checked out SRWZ2, adding the following before the return statement here (https://github.com/hrydgard/ppsspp/blob/master/Core/FileSystems/ISOFileSystem.cpp#L316) fixed it for me:
```
				if (entry->isDirectory && !entry->valid) {
					ReadDirectory(entry);
				}
```

**Comment by hrydgard** [comment]
@Kingcom , right, I found exactly that problem 5 minutes ago :)

**Comment by hrydgard** [comment]
Thank you all for finding this issue, btw. Silly oversight from my side...
