### ISSUE TITLE
Yay, more UI graphical Corruption in the Linux-SDL port!

### ISSUE THREAD

**Issue by Joelgp83** [hrydgard/ppsspp#8629]
Hey guys, just updated to the latest ppsspp available in the linux ppa.  Launched it to be greeted by this lovely menu screen:
![screenshot from 2016-03-06 23 06 23](https://cloud.githubusercontent.com/assets/7368696/13562722/4a9a1ebe-e3f0-11e5-8786-88944a854c20.png)

Running Linux mint 17.3 Rosa.  Can I get confirmation from anyone else?

**Comment by unknownbrackets** [comment]
I'm not sure how you installed this or how the ppa works, but this either a problem in that process, or a problem of some zim file not being updated.  It would work fine if you used a version straight from this repo.

@hrydgard maybe we can include a version or random code in the zim so that when it doesn't match the compiled binary, we can issue a warning somehow?  Although, we won't have a font...

-[Unknown]

**Comment by Joelgp83** [comment]
I just installed the update through mint's native software update applet.  The applet grabs whatever it needs from the ppa at http://ppa.launchpad.net/ppsspp/testing/ubuntu, no special install kung-fu was done.

I should note that normally the updating is all done very smoothly and without issue.  I don't know what could have gone differently this time.

**Comment by unknownbrackets** [comment]
Well, that ppa is doing some weird stuff related to Debian licensing or something.

-[Unknown]

**Comment by sergiobenrocha2** [comment]
You guys can address these kind of packaging issues to me too, otherwise it'll be hard to know them

I can't reproduce this here, ubuntu 14.04. Purge ppsspp, ppsspp-sdl, and ppsspp-common packages and install them again.

**Comment by sergiobenrocha2** [comment]
Is it getting the trusty or xenial packages?

**Comment by Joelgp83** [comment]
Linux mint 17.3 Rosa, so that'd be trusty.

**Comment by sergiobenrocha2** [comment]
Is it working now?

**Comment by Joelgp83** [comment]
Sorry, been super busy with work this weekend, probably won't be able to test till Monday.  Thought I do appreciate that you are making attempts to correct the issue.

**Comment by Joelgp83** [comment]
Just got a chance to try it out.  No good, still garbled.  This is specifically the 64bit, testing branch.  Haven't tried a complete purge+reinstall yet, been to busy to back up in preparation for it.

**Comment by sergiobenrocha2** [comment]
Purge & intall again. I just published the 1.2.2 @Joelgp83

**Comment by Joelgp83** [comment]
Confirmed, a purge and reinstall did the trick.  Many thanks, @sergiobenrocha2! :)
