### ISSUE TITLE
Preview in windows hang since v1.2.1-55-g6f30401

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#8631]
#8628 
@unknownbrackets

**Comment by vsub** [comment]
Can you be a little more specific
I just tried D3D(x64)with intel and nvidia card and it's not crashing no matter what I try(translating what "Preview in windows" could mean)

Maybe it's game specific or because of some option

**Comment by sum2012** [comment]
(OMG,re-test this time also hang in opengl)
Run a game,restart ppsspp,mouse right click the game,hang
hang in bellow picture in newest version
![1](https://cloud.githubusercontent.com/assets/2177532/13580011/386b73d2-e4db-11e5-848d-39789bdbefe1.jpg)

**Comment by vsub** [comment]
Ok this time I can confirm.
Start ppsspp=>right click on any game while using D3D in buffereder rendering mode=>ppsspp freeze

In non buffered,it's fine

**Comment by unknownbrackets** [comment]
It loads things in a background thread anyway, I don't think having the background on hand will hurt so much even if you zoom through several items.

I don't think buffered / non-buffered had any impact on this.

-[Unknown]
