### ISSUE TITLE
Revert back to Java EGL for 1.2.2

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#8638]
Can't seem to solve the remaining issues :( So I plan to revert.

I guess a need a bigger stable of test devices.

Let's try again in 1.3, which will have Vulkan support.

**Comment by unknownbrackets** [comment]
Perhaps we can look more closely at the Java implementation in the Android sources to see what it's doing to choose things better than we are?  But yeah, it's a lot easier with a good set of affected devices and the time to test them.

What we really need is to recruit some testers...

-[Unknown]

**Comment by unknownbrackets** [comment]
Closing based on #8642.

-[Unknown]
