### ISSUE TITLE
Final Fantasy Type-0 reverb level (Minor Issue)

### ISSUE THREAD

**Issue by rkguy** [hrydgard/ppsspp#8645]
Very minor issue compared to all the other madness you guys have to fix, but I thought you guys should know. The reverb is set at an excessively high level in Final Fantasy Type-0, although one probably wouldn't notice if just playing for a couple minutes. I wish I could suggest a value in the code, but sadly my programming skills have a long way to go.

**Comment by hrydgard** [comment]
The reverb volume for each reverb type is pretty much a guess right now. Is it too high in all the game or just in some places?

**Comment by rkguy** [comment]
Technically it is in all the game. The sound effects specifically for the characters are the biggest problem. One can hear it clearly when fighting, and slightly when out of battle. I didn't see any problems with the reverb in the cut scenes.

**Comment by benderscruffy** [comment]
Is this still an issue ??

**Comment by rkguy** [comment]
No, it was solved when the reverb level adjuster was implemented.
