### ISSUE TITLE
Vulkan API bugs

### ISSUE THREAD

**Issue by zminhquanz** [hrydgard/ppsspp#8656]
When i'm maximize windows PPSSPP , is appear bug graphic
![image](https://cloud.githubusercontent.com/assets/11285640/13923092/bd29fba8-efb1-11e5-8d2a-72bba6aaca5e.png)

**Comment by hrydgard** [comment]
Yeah, window resizing has not been implemented properly for Vulkan yet. Thanks for making the report.

**Comment by zminhquanz** [comment]
and the crash when i'm load save from God Of War Series
![image](https://cloud.githubusercontent.com/assets/11285640/13944003/05f52696-f034-11e5-82fe-86e24175f099.png)
GOW Chains of Olympus
![image](https://cloud.githubusercontent.com/assets/11285640/13944013/1964ed06-f034-11e5-8353-fb3efec87582.png)
GOW Ghost of Sparta

**Comment by Mori-S** [comment]
Getting save crashing here too. Also the game hud is a bit messed up in ridge racer US
![rr](https://cloud.githubusercontent.com/assets/15892211/13950428/279a8404-efe8-11e5-82e9-bbb9c10e4f14.jpg)

**Comment by xiushudongfang** [comment]
Dose it work on Android? It seems no effect on my phone.

**Comment by hrydgard** [comment]
No it does not.

**Comment by Mori-S** [comment]
It IS very fast and very usable too! Sorry about the premature bug report by the way.  All i ever do is play ridge racer in ppsspp so I jumped on it too quickly, lol

**Comment by zminhquanz** [comment]
next update , please fix issue and implement Buffered rendering

**Comment by ufdada** [comment]
**Device:**
_Samsung Galaxy S6 Stock
Android 6.0_

If i set the Graphic Backend to Vulkan and force close PPSSPP (remove it from the open app list) and start it again the Screen is flipped vertical.

![screenshot_20160407-105132](https://cloud.githubusercontent.com/assets/3787188/14346226/827dce0a-fcb1-11e5-800e-d77f7fbb3b38.png)

I even don't get a restart message on switching backends, which i normally get on windows. Is that intended?

**Comment by hrydgard** [comment]
It's not using Vulkan yet, just a vulkan style transform matrix :).

Please ignore the Vulkan option on Android for now, I will remove it shortly until we get it working.

**Comment by ufdada** [comment]
No Problem, i just wanted to point that one out :). But if it works sometime you should probably find a way to restart ppsspp on Android too, so the backend is used as well.

**Comment by hrydgard** [comment]
Most of this is fixed since some time. Vulkan still has issues, though.

**Comment by min050820** [comment]
@hrydgard If most of is Vulkan on Android is still disabled? I made sure my device supports Vulkan (has libvulkan and hardware caps are reported correctly) but I still don't have the Vulkan option.

If it's still disabled intentionally, I wonder why it's disabled when you said most of those issues are fixed.

**Comment by hrydgard** [comment]
I plan to work on that soon.
