### ISSUE TITLE
Request: Add "Cheat" option to games before launching it

### ISSUE THREAD

**Issue by GamerzHell9137** [hrydgard/ppsspp#8658]
Found out that there's no way to disable cheats before launching games and its kinda annoying to launch the game, hit the option menu, get inside the Cheat menu and disable it.
There's probably a way to add the cheat menu for all games before launching them.
Eg. Right click on the game> Cheats
Mockup concept
![012](https://cloud.githubusercontent.com/assets/2002038/13949309/8cff66ca-f024-11e5-8da5-3a396a4ff050.jpg)

**Comment by zminhquanz** [comment]
![image](https://cloud.githubusercontent.com/assets/11285640/13971485/3e697f9c-f0c3-11e5-950b-f25a64c5cfe3.png)
PPSSPP have cheat , can you explore all feature that ?

**Comment by GamerzHell9137** [comment]
@zminhquanz Edited the title of the request. Guess it was a bit confusing.

**Comment by unknownbrackets** [comment]
You can create a game config and toggle the setting there, I suppose.

What makes cheats special?  I can see this argument for any setting, by replacing "cheats" for the name of that setting.  Enable networking, software skinning, etc.

-[Unknown]

**Comment by GamerzHell9137** [comment]
@unknownbrackets Yeah but going into the PPSSPP folder and search for the .ini of the game in the Cheats folder is not so.... convenient. I know that you can just open the game, enable cheats and then restart the emulation to get the effects of the cheats but its kinda slow compared to enabling/disabling cheats before launching the game? I'm probably nitpicking but something as that wouldn't be too hard to implement, no ?
