### ISSUE TITLE
[Feature request] add mingw64 build script

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#8659]
My friend want to compile ppsspp.But he is no money to buy vs2015.
vs2015 express only have 90 days trial,
I take a search that  mingw64 is free windows compiler for windows 32 and 64 bit.
I know that now focus to vulkan first.
Just leave this issue open.

**Comment by hrydgard** [comment]
Your friend should get "VS 2015 Community Edition", it's free and it works to build PPSSPP.

**Comment by sum2012** [comment]
Thanks

**Comment by hrydgard** [comment]
Just a reminder, you do need to be careful to choose the right options when installing (C++ is not installed by default).

And it would still be good to have a mingw script of course, I'll merge pull requests that implement it.

**Comment by sum2012** [comment]
I try to compile mame by mingw.But fail

**Comment by sum2012** [comment]
Now I only can compile with Mingw64 with Windows 7 64 bit
Compile with mingw32 with Windows 7 64 bit fail.
Compile with mingw32 with Windows XP ok.
I think that it is a good start

**Comment by sum2012** [comment]
I fixed mame makefile bug,
If not detect MINGW64 then use MINGW32
