### ISSUE TITLE
Multithreading issue

### ISSUE THREAD

**Issue by zminhquanz** [hrydgard/ppsspp#8663]
#some games it have a bug graphic and crash
you can see link when i debug : https://gist.github.com/zminhquanz/3d02e41bd66b836a6b58
![image](https://cloud.githubusercontent.com/assets/11285640/14010029/1177636c-f1c4-11e5-9cad-849955c47259.png)

**Comment by GamerzHell9137** [comment]
iirc mulithreaded is yet to be supported, its in beta state and almost all games have issues with it.

**Comment by unknownbrackets** [comment]
Closing this for the exact same reasons as already described to you in #8112 which you also opened.

-[Unknown]
