### ISSUE TITLE
Unable to compile 

### ISSUE THREAD

**Issue by animaonline** [hrydgard/ppsspp#8675]
Hi, I'm unable to compile the latest ppsspp repo (14363a22db1c21c2fac0e359da2d00c57967b806) on OSX , I'm getting this error: 

```
Android NDK: ../ext/native/Android.mk: Cannot find module with tag 'glslang' in import path    
Android NDK: Are you sure your NDK_MODULE_PATH variable is properly defined ?    
Android NDK: The following directories were searched:    
Android NDK:         
jni/Android.mk:515: *** Android NDK: Aborting.    .  Stop.
```

Is this somehow related to these new Vulkan commits, or am I missing something?

**Comment by animaonline** [comment]
Solved by switching to the stable branch.

**Comment by unknownbrackets** [comment]
I assume you forgot to run `git submodule update --init`.  The glslang submodule is new.

-[Unknown]

**Comment by animaonline** [comment]
Yeah, that too :)
