### ISSUE TITLE
Unable to build the stable-1.2 branch for Android

### ISSUE THREAD

**Issue by animaonline** [hrydgard/ppsspp#8678]
I'm trying to build the **stable-1.2** branch for android, using the ./ab.sh script, the compilation appears to be working, but when inspecting the android/libs/ directory, I can see that no platform specific libraries are available, all the subdirectories are empty.

OS: OSX 10.11.4 and Ubuntu 15.10
NDK: 11b

Here's the last few lines of the compilation log:

```
[arm64-v8a] StaticLibrary  : libppsspp_core.a
[arm64-v8a] StaticLibrary  : libnative.a
[arm64-v8a] StaticLibrary  : libzip.a
[armeabi-v7a] StaticLibrary  : libppsspp_core.a
[armeabi-v7a] StaticLibrary  : libnative.a
[armeabi-v7a] StaticLibrary  : libzip.a
[x86] StaticLibrary  : libppsspp_core.a
[x86] StaticLibrary  : libnative.a
[x86] StaticLibrary  : libzip.a
[x86_64] StaticLibrary  : libppsspp_core.a
[x86_64] StaticLibrary  : libnative.a
[x86_64] StaticLibrary  : libzip.a
[arm64-v8a] SharedLibrary  : libppsspp_jni.so
[armeabi-v7a] SharedLibrary  : libppsspp_jni.so
[x86] SharedLibrary  : libppsspp_jni.so
[x86_64] SharedLibrary  : libppsspp_jni.so
/Users/roman/Library/Android/sdk/ndk-bundle/toolchains/x86-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/i686-linux-android/4.9/../../../../i686-linux-android/bin/ld: warning: shared library text segment is not shareable
/Users/roman/Library/Android/sdk/ndk-bundle/toolchains/x86-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/i686-linux-android/4.9/../../../../i686-linux-android/bin/ld: error: treating warnings as errors
collect2: error: ld returned 1 exit status
make: *** [obj/local/x86/libppsspp_jni.so] Error 1
make: *** Waiting for unfinished jobs....
```

What could be the reason for this? Compiling **master** doesn't seem to work either.

**Comment by sum2012** [comment]
Try degrade the NDK to 10e

**Comment by animaonline** [comment]
Thanks @sum2012 , it actually worked! :+1:  

Please keep this issue open until this has been fixed and the latest ndk is supported.

**Comment by unknownbrackets** [comment]
This is basically related to #8677.

Apparently a bunch of ffmpeg's assembly is written in a way that is deprecated on Android.  It seems like we may have to disable optimizations on x86 Android within ffmpeg, which sounds kinda terrible...

-[Unknown]

**Comment by hrydgard** [comment]
@animaonline Could you try building master on your setup now?

**Comment by unknownbrackets** [comment]
#8651 fixed this for others.  Since we haven't gotten feedback, I'm going to close this assuming that the fix worked out here too.

If it didn't, feel free to comment and we'll reopen.

-[Unknown]
