### ISSUE TITLE
Pangya: Rapid seizure-inducing flickering when booting (all backends)

### ISSUE THREAD

**Issue by thedax** [hrydgard/ppsspp#8691]
Somewhere between 1.1.1 and 1.2, the game started booting with terrible screen flickering while the copyright and "don't remove the Memory Stick" screens display. In-game is fine, no flickering, it's just the booting screens. I'm still bisecting, but it's definitely not a desirable bug to have. I don't know if it's exclusive to Windows either.

**Comment by thedax** [comment]
git.exe bisect bad

9327749f16693c442697f9806d3e596f841105be is the first bad commit
commit 9327749f16693c442697f9806d3e596f841105be
Author: Unknown W. Brackets <checkins@unknownbrackets.org>
Date:   Wed Dec 30 17:29:20 2015 -0800

Allow setting the display off.

Final Fantasy Tactics does this to avoid some brief flicker.

:040000 040000 3c4f4cfaf52452841f7ce07d57849934915107e9 08859b54f4985fb3f355b3d9f81d2ddd5c1ce524 M	Core

**Comment by unknownbrackets** [comment]
Interesting.  Maybe this means it's turning off the display every other frame?

I wonder if there's a lag or something...

-[Unknown]

**Comment by hrydgard** [comment]
Or we are not respecting the flag when drawing video frames directly, or something.. we've seen cases where we end up with a buffer for every second frame and no buffer for the other..

**Comment by thedax** [comment]
@unknownbrackets, is this something I can help test, since I have the game? Or did you mean a pspautotest needed to be written?

**Comment by unknownbrackets** [comment]
Well, a log of the `sceDisplaySetFramebuf` calls would probably help, since I'm no sure what it's actually doing.  Or a JpcspTrace...

I also think `sceDisplaySetFramebuf` does some sort of validation (never really tested it properly.)  My suspicion is that this validation is triggering and so it's not *actually* disabling the framebuffer on real firmware.

It seemed like if the current render target was 8888 you couldn't set a 565 display, or something... maybe only if it's the same pointer.

-[Unknown]

**Comment by thedax** [comment]
I'll see what I can do when I get some time. :)

**Comment by unknownbrackets** [comment]
Made some changes based on sceDisplay testing, and reporting shows this game is impacted... maybe fixed?

-[Unknown]

**Comment by thedax** [comment]
@unknownbrackets, yeah, it's fixed now. Should I bother figuring out which commit did it?

**Comment by unknownbrackets** [comment]
It might be useful in case any of them cause problems for other games, but I think they're all fairly safe.

Gonna mark as closed either way, since it's fixed.  Yay.  Thanks for testing.

-[Unknown]
