### ISSUE TITLE
Regarding OpenGL and AMD Crimson driver 16.4.1 Hotfix

### ISSUE THREAD

**Issue by chaosjs1** [hrydgard/ppsspp#8698]
Hello to all, Just thought I would let you all know that on latest git version 1.2.2 r288 and earlier I have been experiencing TDRs with my AMD R7 260X 2gig Graphics Card with OpenGL only and as for the latest official version 1.2.2 I will test now and let you all know further in a little while afterwards..  Anyways, Thanks for listening and have a nice day ahead. Also I just got done testing the official release 1.2.2 and it still does occur eventually..  Thanks again for listening and all..

**Comment by hrydgard** [comment]
If you're getting TDR that's a driver bug...

**Comment by chaosjs1** [comment]
Okay, Thanks for letting me know..

**Comment by unknownbrackets** [comment]
Is this still a problem with the latest driver?

-[Unknown]

**Comment by chaosjs1** [comment]
I am currently the very latest to greatest Beta 16.5.1 beta on my New APU Which has R7 AMD Radeon Graphics integrated and yes on OpenGL It still has TDRs just after getting into the game known as FF4  Complete Final Fantasy 4 Game..  Thanks again for listening..

**Comment by Nucleoprotein** [comment]
Same for me, I get TDR in Star Ocean First Departure every time. I have tested some AMD's 2016 OpenGL ICDs and all crashes, latest stable is from 15.7.1, (2015, pre-Crimson Software drivers.

System: Windows 10 x64, Radeon R7 360, Catalyst 16.7.1 (16.7.2 only fixes restore defaults in Radeon Settings...)

@chaosjs1
Copy this files: http://www70.zippyshare.com/v/M4qbC099/file.html to game directory (included both x64 and x86 OpenGL ICDs) and test.

**Comment by unknownbrackets** [comment]
Does it stop happening if you uncheck "Simulate block transfer" and check "Disable slower effects"?  Does it happen with the "Skip buffer effects" rendering mode?

-[Unknown]

**Comment by Nucleoprotein** [comment]
Even worse because driver do not TDR but I got full screen of those artifacts so I need to force reboot...
This is clearly driver bug because OpenGL ICDs (in my case x64 - atio6axx.dll) version: 6.14.10.13399 and 6.14.10.13411 works fine, first crashing is 6.14.10.13420.

**Comment by unknownbrackets** [comment]
Well, that sounds like a pretty good revision range.  Also, it's interesting that disabling those things doesn't help - the main special thing that Star Ocean does is rely on stencil data in certain ways.  Those settings should effectively disable those features, I think.... odd.

Does this _only_ happen with Star Ocean 1?  It may help if it can be reproduced with, for example, a PSP demo (Lunar comes to mind as potentially somewhat similar.)  That might allow the driver developers to test it directly.

Alternatively - can you describe exactly when it happens?  Here's the initial drawing I see normally:

1. The Square Enix logo fades in (white BG)
2. Fade to black
3. A video starts playing (first frame is reddish)
4. Skipping the video fades quickly to black
5. A menu (white text) is displayed

Does it crash between any of those points?  Or later on?

If you can give me a narrow enough range, I might be able to check what it's drawing during that period and come up with some likely suggestions for an AMD bug report.

-[Unknown]

**Comment by Nucleoprotein** [comment]
Crashes right after videos or on load game (save from first city).

**Comment by unknownbrackets** [comment]
Does it stop happening if you check the speedhack "Disable stencil test"?

-[Unknown]

**Comment by Nucleoprotein** [comment]
Let me crash my system again ;) Please wait :P

**Comment by unknownbrackets** [comment]
Just to add some color, this game uses a stencil map to determine what objects you're underneath or above:

![starocean-stencil](https://cloud.githubusercontent.com/assets/191233/3140752/8cec5baa-e939-11e3-8613-0c1c6790ee32.gif)

But it sounds like this driver is basically crashing with any PSP game?  If you can find a homebrew or demo that crashes, that may be enough for a bug report to AMD.  That would be enough for them to reproduce.

-[Unknown]

**Comment by Nucleoprotein** [comment]
I tested all home-brew from build in store and include cube.iso and all works fine :/ and PSP Demo archive (from link on PPSSPP fiste) seem to be down for maintenance.

**Comment by Nucleoprotein** [comment]
@unknownbrackets
Any news about this ? Do you have time to investigate what connects crashing games?

**Comment by unknownbrackets** [comment]
Unfortunately, I don't have Tekken or Ape Escape.  I'd suggest you try using the GE debugger but I think the crashes would make it hard.

Indeed God of War and Dante's Inferno use a bunch of effects.

Supposedly this makes it possible to download the demos:
https://play.google.com/store/apps/details?id=com.curtrostudios.demoarchive

I think the Lunar demo and a few others are available there, at least they show when browsing from a PSP.  I haven't used the Android app.

-[Unknown]

**Comment by KabutoKun** [comment]
We can easily get those demos here too:
http://apps.curtrostudios.com/pspdemos

Just click download for the demo you want and you get a .xpd file, open it with some text editor and you will see the direct link of the .PBP file, then just copy this link to your web browser and download the actual demo.

However, for some reason a couple of those demos are not directly working in PPSSPP, you get an error saying "Could not load game. failed to load executable: file corrupt". To fix this you have to extract the .PBP file of the demo (you can use EBOOT2ISO in Windows) and then decrypt the extracted EBOOT.BIN with PRXdecrypter_27a_fix using a REAL PSP.

**Comment by mirh** [comment]
Instead of GE debugger, you could even try GPU PerfStudio [frame debugger](http://developer.amd.com/tools-and-sdks/graphics-development/gpu-perfstudio/gpu-perfstudio-frame-debugger/). 

It even support remote sessions.

**Comment by Nucleoprotein** [comment]
@KabutoKun 
But I need a legal and easy way to demonstrate this to AMD, so using decrypter on PSP is useless for AMD report.

@mirh 
I will try that.

**Comment by mirh** [comment]
@Nucleoprotein 
Baad. For as much as.. shouldn't you see which state preceded crash? 
Anyway, you may want to try [codeXL](https://github.com/GPUOpen-Tools/CodeXL) then.

**Comment by Nucleoprotein** [comment]
If somebody knows a PSP demos that do not need decryption on PSP give me know, I will test them all maybe I find crashing one ...

**Comment by Nucleoprotein** [comment]
"Optional" (new hotfix name...) 17.1.1 is out and still no fix ...

**Comment by hrydgard** [comment]
Still a problem? Might want to try the D3D11 or Vulkan backends too..

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

Hopefully having more backend options has made this less of a problem.  We probably can't do a lot to work around some of the driver bugs, and this hardware is getting less common which is making getting feedback even harder.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
