### ISSUE TITLE
Video Previews of games

### ISSUE THREAD

**Issue by kamijoutouma** [hrydgard/ppsspp#8702]
This is less an issue and more of a cosmetic change. 

I understand that ppsspp isn't compatible with all games yet however it would be nice if ppsspp could "when possible" load the preview videos in games like an actual psp does and when it can't, just load the preview image like it currently does.

Again this is more of a cosmetic change and should be really low priority for the other things that can be done.

Also excuse me if this has already been talked about before ( i looked and couldn't find an issue talking about this so if it has been then i missed it.)

**Comment by unknownbrackets** [comment]
There's already a request for this #2585.  Most likely videos would play fine, someone just needs to write video timing code to actually display it.

Closing this as a duplicate.

-[Unknown]
