### ISSUE TITLE
[Question] Is Vertex Shader JIT running similar like Citra

### ISSUE THREAD

**Issue by zminhquanz** [hrydgard/ppsspp#8704]
Can you explain with this ?

**Comment by unknownbrackets** [comment]
Not really.  Citra's vertex shader jit runs on the CPU, I think, not on the GPU.  We do not have a shader jit for the software renderer yet.  But we do create shaders in a just in time fashion for glsl.

This is really a question more for the forum, not an issue.  Closing.

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, to summarize, we run the corresponding thing (fixed function transform) on the GPU already, so what we have is more efficient than Citra's vertex JIT already.

**Comment by unknownbrackets** [comment]
Although, Citra's thing might be a little similar in some ways to listjit (jitting and caching displaylists) I suppose, which was a mostly failed experiment...

-[Unknown]

**Comment by hrydgard** [comment]
Not that much, the vertex programs that Citra JITs to CPU instructions is pretty much the same part of the pipeline as the fixed function transform we simulate directly with vertex shaders. The 3DS also has some form of display lists with commands in them, relatively similar to the PSPs DLs.

**Comment by zminhquanz** [comment]
and it is peformance gain on ARM or x86 Chip when Vertex JIT complete

**Comment by unknownbrackets** [comment]
Not sure what you mean.  Even if we implemented something like Citra's vertex shader jit, it would only be for the software renderer.  If you were using OpenGL, Vulkan, or Direct3D, there would be no performance gain at all.

We also use a vertex decoder jit (I call it vertexjit), which is a different thing.  I don't know if Citra has anything similar or not.  The vertex decoder jit definitely does give a performance gain.

-[Unknown]
