### ISSUE TITLE
[Qt] Homebrew download doesn't work on Linux

### ISSUE THREAD

**Issue by sergiobenrocha2** [hrydgard/ppsspp#8711]
Homebrew download is not working on Linux, it can't find ~/.local/share/ppsspp//ppsspp.dl. It seems PPSSPP is not creating this path at first.

Issue is happening only on Qt, SDL port works fine.

```
I: http_client.cpp:401: Completed downloading http://store.ppsspp.org/index.json to memory
I: http_client.cpp:401: Completed downloading http://store.ppsspp.org/icons/cavestory_icon0.png to memory
16:22:539 UI/Store.cpp:278 I[HLE]: Triggering install of http://store.ppsspp.org/files/cavestory.zip
I: http_client.cpp:401: Completed downloading http://store.ppsspp.org/files/cavestory.zip to /home/sergio/.local/share/ppsspp//ppsspp.dl
E: http_client.cpp:403: Failed writing download to /home/sergio/.local/share/ppsspp//ppsspp.dl
16:29:056 Util/GameManager.cpp:101 I[HLE]: Download completed! Status = 200
16:29:056 Util/GameManager.cpp:105 E[HLE]: Downloaded file /home/sergio/.local/share/ppsspp//ppsspp.dl does not exist :(
```

**Comment by unknownbrackets** [comment]
Why is that .local instead of .config?  Does SDL use the same path?

-[Unknown]

**Comment by sergiobenrocha2** [comment]
SDL saves the game at ~/.config/ppsspp/PSP/GAME/

I can see a ppsspp.dl in Core/Util/GameManager.cpp: 

```
return g_Config.externalDirectory + "/ppsspp.dl";
```

**Comment by sergiobenrocha2** [comment]
SDL saves the temporary file to /tmp/ppsspp.dl, while Qt tries to save at ~/.local/share/ppsspp//ppsspp.dl

Changing that line from GameManager.cpp to

```
return "tmp/ppsspp.dl";
```

works. Maybe g_Config.externalDirectory is mis-configured in Qt?

**Comment by unknownbrackets** [comment]
It's coming form here:

https://github.com/hrydgard/ppsspp/blob/master/ext/native/base/QtMain.cpp#L440

SDL passes /tmp.  This may be an issue for iOS as well @hrydgard. Maybe we should just use memstickDirectory as a writable temp dir?

-[Unknown]

**Comment by hrydgard** [comment]
Hm, yes, that seems wrong...

**Comment by sergiobenrocha2** [comment]
It's working now, thanks. It's saving the tmp file in ~/.config/ppsspp//ppsspp.dl now
