### ISSUE TITLE
Allow Non-Buffered Rendering and Auto Frameskip

### ISSUE THREAD

**Issue by kuwoh** [hrydgard/ppsspp#8713]
i get alot of slowdowns in tekken 6 since my phone is a bit old and on an old version of ppsspp i could enable auto frameskip while using non-buffered rendering. How can i force enable the two or something

**Comment by Anuskuss** [comment]
There was a specific setting which you should enable on your phone, but I can't remember it.

**Comment by kuwoh** [comment]
already have that on :/

**Comment by leopard20** [comment]
@unknownbrackets Huh?!

**Comment by unknownbrackets** [comment]
Frameskip doesn't mesh well with "skip buffer effects" (used to be called non-buffered but that was misleading), and causes flickering or just black screens.  This is a feature request to try to find some way to make frameskip and "skip buffer effects" usable together.

-[Unknown]

**Comment by leopard20** [comment]
That's what my huh was about actually! In my mind they're mutually exclusive! :)

**Comment by hrydgard** [comment]
I'm gonna close this, as devices get faster the need for unbuffered rendering is going away - of course I'm not removing it, but additional efforts like this will not happen.
