### ISSUE TITLE
Allow > 5x PSP resolution for devices like iPad Pro 12.9

### ISSUE THREAD

**Issue by iOSSOi** [hrydgard/ppsspp#8714]
I know this might not be high on the priority list, but would it be possible for you guys to optimize the emulator for the iPad Pro 12.9 screen resolution? The menus looks pretty fussy today, and it  seems to affect the resolution of the games played. it would be nice to have them as sharp as possible.

Some people will probably start to complain about the games doesn't even run full speed, and that's actually true, but they are a few games does run full speed without the JIT on non-jailbroken ipad pro 12.9, even without JIT.

(that way the emulator will be ready when JIT finally can be enabled.

Would it be possible?

IPad Pro Screen Res: 2732 x 2048

**Comment by iOSSOi** [comment]
I have tested a few more games, actually, a few game run full speed without jit on the 12,9 Pro. Most YS games does. Please, can we have this the optimized for the for the emulator. I hate when other people ask for optimizations like this, and now I'm the one who's asking. 😩

**Comment by unknownbrackets** [comment]
Speed is going to be bad in some games without jit.

We have recently implemented (mostly @hrydgard) a new, experimental interpreter - it still doesn't use jit, but it pre-processes the MIPS code to generate something that is faster to interpret.  In other words, it does the 25% of what jit does, the part that is allowed on Apple devices.

Actually, this new interpreter may allow us to make jit even faster on devices that support it.  So Apple devices may still lag behind everyone else in speed.

It not enabled by default, and is still buggy.  But you can enable it in the latest git builds via Tools -> Developer Options.  When it works, it should be faster than the interpreter.

As far as resolution, I assume you've selected a higher internal rendering resolution?  You'd want to select 6x PSP to have a sharp render at that resolution, but I'm doubtful the device's GPU could keep up with such a high resolution.

Remember, 480x272 is 1x PSP.  That means 4x PSP is 1920x1088 (near 1080p.)  No multiple of the PSP's resolution matches the iPad Pro's, but 6x PSP is 2880x1632... whatever resolution you use, I recommend setting this to have a border around it to avoid fuzziness (in the Display Layout Editor.)

-[Unknown]

**Comment by iOSSOi** [comment]
@unknownbrackets @hrydgard now i really dont know where to start. You guys are amazing, amaziiiiiiiiimg!!!!!!!!!!! With IR interpreter i can play KH:BBS in full speed on my non jail-broken ipad pro! Im using 5xPSP in buffered rendering. No hacks at all. Im only using multithreaded.

As far as the resolution, im actually speaking about the application itself, not the in-game resolution. Because the application isn't optimized for the 2732x2048, the menu of the emulator is fuzzy, and that seems to effect the games loaded. Playing at the highest resolution still makes games a little, just a little bit.

So optimizing the whole application for ipad pro (menus) and adding 6xPSP (maybe even higher, 10xPSP)really shouldn't be a bad idea.

I remeber the days when the YouTube app wasn't optimized for the resolution of the ipad pro 12.9, every video looked horrible. But when google optimized thr menus to 2732x2048, it also effected the videos. Even if the resolution of the ipad isnt 4k, the 4k videos looked alot sharper. My theory is that the same thing will happen to PPSSPP. i think upgrading the whole app to 2732x2048 will not only make the menus more sharp, even the games will. Please correct me if im wrong! This is only my theory. And if im wrong i will 🤐

**Comment by hrydgard** [comment]
I don't have access to an iPad Pro at the moment. What does it look like? Is the major failing that it's simply running at the wrong resolution, or are things stretched or out of place?

**Comment by iOSSOi** [comment]
Nothing is out of place, its only running at the wrong/lower resolution.

**Comment by iOSSOi** [comment]
@hrydgard @unknownbrackets Thinking of it, I remember the first time i booted PPSSPP on a iPhone 6 plus, the menus was messed up. If you would like to change the resolution I would be happy to leave all the feedback i possible can. If anything will seem stretched or out of order i can upload some pictures.

**Comment by iOSSOi** [comment]
@unknownbrackets @hrydgard it seems that the ir interpreter isgeiiting famous on reddit. Please, please can we have this resolution upgrade + maybe 10xPSP. Please, please. Im not gonna be nagging anymore, promise🤐

**Comment by iOSSOi** [comment]
Any chance the optimization can be ready for 1.4?

**Comment by Purpleistacky** [comment]
@iOSSOi hey! I can't get any game to launch on my iPad pro. any tips? anything in the settings? Cheers.

**Comment by iOSSOi** [comment]
Any chanse we can get ppsspp resolution native to iPad pro 12.9 2732x2048?

**Comment by unknownbrackets** [comment]
Contributions are welcome, especially from contributors with iOS devices.

-[Unknown]

**Comment by unknownbrackets** [comment]
It sounds like this issue isn't really iOS specific, actually.  It's just requesting higher render resolutions than 5x (2400x1360) for the iPad Pro (2732x2048), right?

This would in theory also affect Android tablets that are closer to "4K", like QHD.

-[Unknown]

**Comment by iOSSOi** [comment]
Correct, an option up to 10x would be nice = )

The interface itself isnt optimised for the iPad Pro 12.9 eiter. Lunching ppsspp on the iPad Pro 12.9 (2732x2048) at the moment shows the interface in the Regular 9.7 inch resolution (2048x1536). Is it possible to bump that up to 2732x2048?

Why im asking is that the output resolution to the screen at the moment are limited to 2048x1536. Rendering anything higher than that wont actually make a difference if the app/ppsspp isnt nativly opening at 2732x2048 on the 12.9 inch.

Does that make any sense? I tend to have bad explanations, english isnt my native language = )

**Comment by AkiraMiyakoda** [comment]
More than 5x window sizes would be nice for Windows/Linux with 4K (or more) displays too.

**Comment by hrydgard** [comment]
Maybe @KentuckyCompass has some idea about how to tell iOS that we want to use the full resolution of an iPad Pro 12.9?

**Comment by KentuckyCompass** [comment]
iOS checks whether an app supports certain resolutions based on the presence of a launch screen or otherwise launch images of the correct sizes. If not, you get a legacy resolution. That's most likely what's happening to PPSSPP on the iPad Pro. [Here's a stackoverflow thread about it](https://stackoverflow.com/questions/33860390/force-ipad-pro-to-full-resolution-without-launch-screen).

A launch screen can be easier because you do it once in a WYSIWYG UI designer and specify how it scales, as opposed to a half dozen images that need special sizes and filenames. I'm still figuring out how to make CMake cooperate.

We just need to decide what launching should look like. See [Apple's guidelines](https://developer.apple.com/ios/human-interface-guidelines/icons-and-images/launch-screen/). They discourage showing a logo and recommend just the background of the app without foreground stuff like text. Maybe just the blue gradient?

**Comment by hrydgard** [comment]
Ah, so that's what it is. The blue gradient would be perfect.

**Comment by JuliusSenkus** [comment]
Hi,

Came here from #12815 (TL;DR agreed to test performance of 10x, 9x, 8x etc on my owned devices and if it seemed reasonable create PR to enable this functionality for all devices).

Tested on [Samsung Galaxy S8 (Exynos 8895)](https://www.gsmarena.com/samsung_galaxy_s8-8161.php), [Samsung Tab s5e](https://www.gsmarena.com/samsung_galaxy_tab_s5e-9581.php) and [Khadas VIM3 Pro (connected 4k display)](https://www.khadas.com/vim3).

**Benchmarks for comparison**:

- S8 [Geekbench](https://browser.geekbench.com/v5/cpu/1775468), 3D Mark (slingshot, OpenGL) 3293
- S5e [Geekbench](https://browser.geekbench.com/v5/cpu/1774130), 3D Mark (slingshot, OpenGL) 1749
- VIM3 (Note: bare chip, no cooling) [Geekbench (not my owned device)](https://browser.geekbench.com/v4/cpu/9397860) [alternative (from product page)](https://static.wixstatic.com/media/04a2a6_dccd9c0b3a144d62ab129bfe39c3b1e5~mv2.jpg/v1/fill/w_980,h_551,al_c,q_90/04a2a6_dccd9c0b3a144d62ab129bfe39c3b1e5~mv2.webp), 3D Mark (slingshot, OpenGL) 1689

**Tested games**:
[Valkyria Chronicles III(with english patch applied)](https://en.wikipedia.org/wiki/Valkyria_Chronicles_III) Sweet spot somewhere around 6x for S5e and VIM3, but S8 can run it on 10x (only  in title meniu game speed drops to ~90%).
[Need for Speed: Most Wanted (PSP)](https://en.wikipedia.org/wiki/Need_for_Speed:_Most_Wanted_(2005_video_game)) S8 can run 9x, others 7x.
[Tekken 6](https://en.wikipedia.org/wiki/Tekken_6) Have not managed to run 100% speed on any device even on 1x.
Also looked into DBZ Tag team, only on S8, 5x seems to be a lot.

**Summary**:
Useful only for flagship devices and not counting downscaling, full 10x resolution is used with external monitors (Samsung Dex, Android 10 Desktop etc). Might create influx of issues in github from users with with lower end devices.

**Comment by unknownbrackets** [comment]
I'm going to close this now given #12821.  There are still issues I think on some iOS devices, but that's covered in #11677 and really a separate problem from render resolution.

-[Unknown]
