### ISSUE TITLE
[Feature] Language Patch

### ISSUE THREAD

**Issue by Anuskuss** [hrydgard/ppsspp#8719]
Now that you guys are working on texture replacement support, would it be possibe to include replacing for language files in games? Like patching a asian game to play it in you language? Or would it be better to patch the ROM instead?

**Comment by hrydgard** [comment]
There's no general format for text or language files in games, games do text very differently. So each game needs to be hacked the good old way in general.

**Comment by Anuskuss** [comment]
@hrydgard I understand it wouldn't be possible to change "hardcoded" text, but when text is being requested, couldn't PPSSPP hypothetically "intercept" it and then replace it?

**Comment by unknownbrackets** [comment]
PPSSPP doesn't know games are "requesting" text.  Not all games even do that.

It's like saying, can't we stop watering plants, and just give them water when they "request" it?  Wouldn't that save water?

By looking at a specific game, you might be able to figure out how to deal with text for that one game, which is called rom hacking.  Just like you might know specifically how to tell when a certain plant really can't go on without any more water.  But from a general sense it's not that simple.

-[Unknown]

**Comment by Anuskuss** [comment]
Okay, thanks for clarifying.
