### ISSUE TITLE
[Android - 1.2.2.0] Immersive mode breaks virtual keys

### ISSUE THREAD

**Issue by iformas** [hrydgard/ppsspp#8728]
When immersive mode is enabled, due the screen redimension, the virtual keys are repositioned as expected, but the action region remains in its old location

**Comment by iformas** [comment]
Tested in Android 6 - Moto G 3 8gb

**Comment by unknownbrackets** [comment]
I'm not sure what this means.  On my phone, immersive mode means that the virtual Android buttons slide out of the way, and I can use the full screen to play the game.  The PSP virtual buttons are different and still remain active.

I'm able to slide by finger to bring the virtual keys back, as in other apps as well.  Tapping the area the buttons were doesn't work without making that gesture first.

Are you saying that even when the buttons have slid out of the way (like the Back button), it still actives when you tap on it and pauses the emulator?

-[Unknown]

**Comment by iformas** [comment]
Here is an example of the virtual keys (from PSPP) action region without immersive mode option enabled..all work as espected
![screenshot_20160522-204014](https://cloud.githubusercontent.com/assets/2334904/15457841/9fff4dec-205f-11e6-8c70-f1c8b700a25c.png)

Here is an example of the virtual keys action region (marked with green) with the immersive mode option enabled
![screenshot_20160522-204014](https://cloud.githubusercontent.com/assets/2334904/15457843/a219280a-205f-11e6-8e04-12e8c8a7d761.jpg)

**Comment by unknownbrackets** [comment]
Interesting.  If you enable immersive mode, exit PPSSPP from the menu, and then restart it, does this still happen?

Or is it only when you switch immersive mode during the game, or something?

-[Unknown]

**Comment by iformas** [comment]
When immersive mode is enabled in a specific game config, after restart ppsspp
 and run the game, immersive option appears as checked but i still can see the android status bar and right buttons...re-checking it hide them, but i return to the first bug

When immersive mode is enabled in the global config, after restert it get fixed

**Comment by TempestDeShooting** [comment]
Please how do I resolve ppsspp button getting stuck on my Infinix Hot 5?
