### ISSUE TITLE
Full screen deactivates when active work space is changed.

### ISSUE THREAD

**Issue by orbea** [hrydgard/ppsspp#8729]
OS: `Slackware64-current`
`spectrwm-3.0.1-x86_64-1_SBo`
`ppsspp-2c84411_2016.05.07_master-x86_64-1_git`

When using ppsspp with the window manager spectrwm any time I toggle full screen on and then go to another work space (To complete other tasks) I find that ppsspp is no longer full screen when I return to the work space it is running in. The full screen should not reset every time the active workspace is changed. However full screen will not be reset if ppsspp itself is moved to another workspace.

**Comment by orbea** [comment]
I have tested it further and found that that it does not always happen. Here are some conditionals.

* It will not happen if I change to an empty workspace.
* When it does happen it will switch between windowed and fullscreen each time I alternate between those two workspaces.
* Workspaces with open terminals (urxvtc) will often cause it, sometimes workspaces with other windows wont have it until a new terminal is opened.
* As does a workspace with a firefox window.
* Tiled or floating does not seem to matter.

**Comment by orbea** [comment]
I have no interest in reporting issues for ppsspp anymore so I'm going to close this now.

**Comment by hrydgard** [comment]
If it's an issue, it's an issue no matter who's interested in it. It should be closed when it's fixed.

**Comment by asl97** [comment]
The issue is due to SDL,  setting a hint should fix it.

https://valadoc.org/sdl2/SDL.Hint.VIDEO_MINIMIZE_ON_FOCUS_LOSS.html

I uses the environment variable, `SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0` as a workaround atm.

**Comment by orbea** [comment]
I just want to add that environment variable only works when changing workspaces. ppsspp will still fail to respect fullscreen when first started.

**Comment by asl97** [comment]
@orbea that's another issue: #9086
