### ISSUE TITLE
Pspspp lagging, fps, speed reduced on android 6.0 devices

### ISSUE THREAD

**Issue by Alien1204** [hrydgard/ppsspp#8730]

**Comment by hrydgard** [comment]
Since when? Since Android 5.0?

**Comment by Alien1204** [comment]
God Eater 2 hardware transform error, after enemies appear few seconds... screen became dark, and keeping darker, fps and speed reduced too... that bugs keeping til fps drop down 30fps => 3, 5fps

And on Abandon city map, everything turn to white all when i steps out shadow to sunshine (buffered render)....=.=" 
My device s Galaxy Note4 Octa, android 6.0.1

**Comment by Alien1204** [comment]
Nope, when i was 5.0 or 5.1 pspspp run very smoothly , all games run with 30/30fps

**Comment by unknownbrackets** [comment]
Are you able to get an `adb logcat`?  Do you have "Enable compatibility server reports" enabled?

I'm guessing you have some sort of shader compiler error, but hard to tell why without seeing what the error is.

-[Unknown]

**Comment by Alien1204** [comment]
Pls check them out
https://youtu.be/wq_YIQuV0HU
And
https://youtu.be/j8VfnIH3nUk

**Comment by Alien1204** [comment]
Great job !!! Fps and speed on newest updare better, but god eater burst and god eater 2 shader still error, everything turn to white on Abandon City map, but when i turn of "hardware transform" graphic return to normal, but lag when i turn it off =…="

**Comment by asbel123** [comment]
i got that same problem too i update my samsung galaxy s6 edge to 6.0.1 last week guess what they fix is sukioden 3d version its works perfect no more white screen but speed is so bad i cant play any  psp game anymore like tales of phantasia cross editon its not fullspeed at all.

its fullspeed on my old firmware is 5.11. speed is like my samsung galaxy s4 speed on andriod m.

**Comment by Alien1204** [comment]
asbel123 Download newest buildbot ver, speed and fps has been fixed

**Comment by unknownbrackets** [comment]
Are you able to get an `adb logcat`?  Do you have "Enable compatibility server reports" enabled?

I'm guessing you have some sort of shader compiler error, but hard to tell why without seeing what the error is.

-[Unknown]

**Comment by Alien1204** [comment]
Yep... i  sent a feedback report multiple times... @.@
My note4, s7 s strong devices, but playing very lag ...

**Comment by unknownbrackets** [comment]
Hmm, I'm not seeing any reports of shader compile errors - except some from older versions of PPSSPP (pre 1.2.x) that are due to already fixed bugs, and a steady stream from Mali-400 devices (GPUs that can't handle hardware transform.)

Did you get the same "hardware transform error" while you had "Enable compatibility server reports" checked?  It can only report it when it happens, and I think you need to have an internet connection at the time too.

When it reports that error to the server, it includes debugging information, which is what I'm looking for.  It may be a driver bug introduced by 6.0, but if we can see the error, we may be able to work around it.

-[Unknown]

**Comment by Alien1204** [comment]
Force close when i sending report feedback... 
Version 1.2.2-678-g239d6d3

**Comment by Alien1204** [comment]
Buffered rendering mode on god eater 2 game speed very bad, whereas other games remain stable speed

**Comment by Alien1204** [comment]
Samsung devices

**Comment by Alien1204** [comment]
samsung devices is locked bootloader after the update 6.0
It can affect to JIT ??? Some games running slow as i turned it off when i was 5.1
