### ISSUE TITLE
God Eater Burst/God Eater 2 turned on white screen on Abandon City map when update android 6.0   

### ISSUE THREAD

**Issue by Alien1204** [hrydgard/ppsspp#8746]

**Comment by Alien1204** [comment]
Graphic error when turned on hardware transform...

**Comment by unknownbrackets** [comment]
This issue is being closed as a duplicate of #8730.

Would you like me to email you every day to ask you if you've learned programming and fixed it yet?

-[Unknown]

**Comment by vjjulius** [comment]
I have the same issue. White screen on city.
build ppsspp-v1.2.2-758-g1f8afd7-android
Samsung S7 edge
