### ISSUE TITLE
Combo key setup : not analog

### ISSUE THREAD

**Issue by n1dminhd** [hrydgard/ppsspp#8753]
Please, add analog on "Combo key setup"
Analog Up
Analog Down
Analog Left
Analog Right
Sorry I bad Eng !

**Comment by ResurrectionRedmi9** [comment]
Touch gesture is better https://github.com/hrydgard/ppsspp/pull/13107

**Comment by Gamemulatorer** [comment]
This wasnt fixed by https://github.com/hrydgard/ppsspp/commit/57b4cd394a69029dcb8943e1bad33a4d149dcf99?

**Comment by unknownbrackets** [comment]
I think #13869 doesn't quite cover this.  Would need to add directions to the list of bindings for custom controls (i.e. analog left.)

-[Unknown]
