### ISSUE TITLE
MapRegVS() failed on second try

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8754]
It happen in Kenka Banchou with win64,win32 is fine.Since https://github.com/hrydgard/ppsspp/pull/8725
![02](https://cloud.githubusercontent.com/assets/3481559/15364811/7d2fdb9a-1d50-11e6-959e-dcceb23ac93d.png)

**Comment by unknownbrackets** [comment]
Can you get a stack trace?

-[Unknown]

**Comment by daniel229** [comment]
Stack trace
![03](https://cloud.githubusercontent.com/assets/3481559/15365208/fc5e36ae-1d51-11e6-862c-1c1fe3a80aea.png)

**Comment by hrydgard** [comment]
vmmul? Hm.. haven't changed vmmul in the regular JIT lately as far as I remember.. Must be another op affecting the regalloc somehow?

**Comment by hrydgard** [comment]
I reverted a minor thing which I don't think should affect this .. but maybe does

**Comment by daniel229** [comment]
It does.
