### ISSUE TITLE
Patapon 3 Adhoc squad De-sync

### ISSUE THREAD

**Issue by TehPlayer14** [hrydgard/ppsspp#8771]
you play as the same character and the 2nd one is unassinged (desync)

**Comment by lightfirst** [comment]
I will be work if play PPSSPP with PSP

**Comment by Alcarmor** [comment]
tested with the last devbuild yesterday and still not working.

every player in the lobby seems to control the host character while the others remain unassinged

**Comment by Tail870** [comment]
Issue still here.
Tested with PPSSPP x64 versions:
1.7.4 
v1.7.5-308-gfb3ba7007

**Comment by Saramagrean** [comment]
Try with cheat in here, it's work!! 
https://forums.ppsspp.org/showthread.php?tid=16972&pid=132752#pid132752

**Comment by Tail870** [comment]
> Try with cheat in here, it's work!!
> https://forums.ppsspp.org/showthread.php?tid=16972&pid=132752#pid132752

I almost did it: https://forums.ppsspp.org/showthread.php?tid=24844
Still 3rd player just kicks himself and 2nd player from server.

**Comment by sodomon2** [comment]
I tried to play the patapon 3 multiplayer but it doesn't create the game it stays in creating room and from there it crashea the game

My version of PPSSPP is: v1.9

**Comment by ANR2ME** [comment]
@sodomon2 could you test it again using the test build from this post http://forums.ppsspp.org/showthread.php?tid=9037&pid=135523#pid135523
It's an attempt to make adhoc works properly or at least better

**Comment by unknownbrackets** [comment]
Is this still an issue on the latest git build with recent networking improvements?

-[Unknown]

**Comment by ANR2ME** [comment]
multiplayer cheats are no longer needed, or rather it could break multiplayer since player's slot has been fixed by now.
