### ISSUE TITLE
Build failing (Gentoo)

### ISSUE THREAD

**Issue by Q3CPMA** [hrydgard/ppsspp#8772]
Hello, I'm trying to build ppsspp-1.2.2 with `qmake PPSSPPQt.pro CONFIG+='release' CONFIG+='system_ffmpeg' && make -j8` (I updated every submodule, except tests and ffmpeg), but I get these errors:
```
/tmp/ppsspp-1.2.2/Qt/libNative.a(gl3stub.o): In function `gl3stubInit':
gl3stub.c:(.text+0x16): undefined reference to `eglGetProcAddress'
gl3stub.c:(.text+0x2c): undefined reference to `eglGetProcAddress'
gl3stub.c:(.text+0x43): undefined reference to `eglGetProcAddress'
gl3stub.c:(.text+0x5a): undefined reference to `eglGetProcAddress'
gl3stub.c:(.text+0x71): undefined reference to `eglGetProcAddress'
/tmp/ppsspp-1.2.2/Qt/libNative.a(gl3stub.o):gl3stub.c:(.text+0x87): more undefined references to `eglGetProcAddress' follo
```
Do you have any idea of the reasons? Thanks.

**Comment by Q3CPMA** [comment]
Since this is gentoo, I'll try to precise the ebuild a little bit:
```
qt5? (
                dev-qt/qtsvg:5
                dev-qt/qtgui:5
                dev-qt/qtcore:5
                dev-qt/qtopengl:5
                dev-qt/qtmultimedia:5
                dev-qt/qtwidgets:5
                dev-qt/qt-mobility[multimedia]
        )
```
These are the qt5 version dependencies. Does somethign seem superfluous or missing to you?

And here are the USE flags for these dependencies that seem related to gles/egl:
```
qtgui
   egl           : Enable EGL integration (set)
   eglfs         : Build the EGL Full Screen/Single Surface platform plugin (unset)
   gles2         : Use GLES 2.0 or later instead of full OpenGL (set)

qtopengl
   gles2 : Use GLES 2.0 or later instead of full OpenGL (set)

qtmultimedia:
   gles2        : Use GLES 2.0 or later instead of full OpenGL (set)
   widgets      : Build the QtMultimediaWidgets module (not related to egl/gles, but seems important, unset)
```

**Comment by unknownbrackets** [comment]
Not very familiar with the Qt build.  Are you using qmake or cmake?  I think you have to use qmake.

https://github.com/hrydgard/ppsspp/blob/c30287c4e58f00ca73e03c6650594df7658c1223/Qt/Settings.pri#L41

Perhaps this line isn't passing, and so EGL isn't added to the link?

-[Unknown]

**Comment by Q3CPMA** [comment]
I shouldn't even need egl, anyway. I'm on a desktop.

**Comment by unknownbrackets** [comment]
Hmm, well you have it set for qtgui.

Also, since you're using GLES2, we're assuming that you're using EGL currently.  Maybe this is a mistake, but typically you wouldn't use GLES2 on a desktop anyway.

c

Does it help to change this line:

https://github.com/hrydgard/ppsspp/blob/master/ext/native/gfx_es2/gl3stub.c#L19

To:
```c++
#if 0
```

Or do you just hit more errors?  I'm not really sure that'll work at all.  You can also try disabling the line that's adding GLES2 in Settings.pri.

-[Unknown]

**Comment by Q3CPMA** [comment]
After rebuilding all the Qt packages without gles2, I can finally compile. But it segaults with:
```
(gdb) run
Starting program: /tmp/ppsspp/Qt/ppsspp 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
28:42:693 Core/Config.cpp:948 I[LOAD]: Loading controller config: /home/hadrien/.config/ppsspp/PSP/SYSTEM/controls.ini
[New Thread 0x7fffe83af700 (LWP 16057)]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff06867ea in XQueryExtension () from /usr/lib64/libX11.so.6
```
(I could compile with `-Og -g` if you want)

**Comment by Q3CPMA** [comment]
It's alive! Just used `/usr/lib/qt5/bin/qmake` instead of `qmake`.
