### ISSUE TITLE
Conception - Ore no Kodomo o Unde Kure!! hangs after video

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8781]
Since https://github.com/hrydgard/ppsspp/pull/8757/commits/f08c873a4baeed8c04753ba9991824b47e992d1b in https://github.com/hrydgard/ppsspp/pull/8757
slow effect helps it.
```
50:09:523 user_main    W[ME]: HLE\scePsmf.cpp:1446 scePsmfPlayerReleasePsmf(08f81bc0)
50:09:523 user_main    I[ME]: HLE\scePsmf.cpp:1400 scePsmfPlayerDelete(08f81bc0)
50:09:556 user_main    W[ME]: HLE\scePsmf.cpp:1054 scePsmfPlayerBreak(08f81bc0)
50:09:556 user_main    E[ME]: HLE\scePsmf.cpp:1057 scePsmfPlayerBreak(08f81bc0): invalid psmf player
50:09:625 user_main    I[SCEGE]: Common\FramebufferCommon.cpp:414 Creating FBO for 00044000 : 480 x 272 x 1
50:09:657 AT3Thread0   E[FileSys]: FileSystems\DirectoryFileSystem.cpp:560 DirectoryFileSystem::OpenFile: FAILED, 3 - access = 1
50:09:657 AT3Thread0   E[IO]: HLE\sceIo.cpp:1301 ERROR_ERRNO_FILE_NOT_FOUND=sceIoOpen(ms0:PSP/SAVEDATA/NPJH50583DAT/bgm001.at3, 40000001, 00000000) - file not found
50:09:660 AT3Thread0   I[ME]: HLE\sceAtrac.cpp:1898 0=sceAtracSetDataAndGetID(08e78ba0, 00018000): atrac3+ stereo audio
50:09:740 idle0        I[SCEGE]: GLES\Framebuffer.cpp:1897 Decimating FBO for 00088000 (480 x 272 x 3), age 6
50:09:908 DataPool::Se W[MM]: MemmapFunctions.cpp:91 ReadFromHardware: Invalid address 00000008
50:09:908 DataPool::Se W[MM]: MemmapFunctions.cpp:91 ReadFromHardware: Invalid address 00000009
50:09:908 DataPool::Se W[MM]: MemmapFunctions.cpp:91 ReadFromHardware: Invalid address 0000000a
50:09:908 DataPool::Se W[MM]: MemmapFunctions.cpp:91 ReadFromHardware: Invalid address 0000000b
50:09:908 DataPool::Se W[MM]: MemmapFunctions.cpp:91 ReadFromHardware: Invalid address 00000004
50:09:908 DataPool::Se W[MM]: MemmapFunctions.cpp:91 ReadFromHardware: Invalid address 00000008
```

**Comment by unknownbrackets** [comment]
Maybe we should more aggressively decimate unused buffers when a new one is created, or at least flush safe ones and clear the safe flag.  That could work...

Try adding this:
```c++
		for (VirtualFramebuffer *vfb : vfbs_) {
			if (!g_Config.bDisableSlowFramebufEffects && vfb->safeWidth > 0 && vfb->safeHeight > 0) {
				ReadFramebufferToMemory(vfb, true, 0, 0, vfb->safeWidth, vfb->safeHeight);
				vfb->safeWidth = 0;
				vfb->safeHeight = 0;
			}
		}
```

Right above this line:
https://github.com/hrydgard/ppsspp/blob/63e7304467b9e24544b2c85722d129e98bf1c91f/GPU/Common/FramebufferCommon.cpp#L414

Not sure if this might have negative performance impacts...

-[Unknown]

**Comment by daniel229** [comment]
It doesn't help.

**Comment by Mori-S** [comment]
Works fine with the vulkan and software backend. Kinda odd that it crashes with D3D9 and Opengl

**Comment by LunaMoo** [comment]
Phantasy Star Portable series seems to be glitched by this as well and again code above doesn't help, disabling slow effects does.
 Potentially other games which people report new problems with like [Tekken 6](http://forums.ppsspp.org/showthread.php?tid=1274&pid=118342#pid118342) or [Kingdom Hearts Birth By Sleep](http://forums.ppsspp.org/showthread.php?tid=445&pid=118392#pid118392) might also belong here, but I don't have those to test.

 At least for now "Me & My Katamari" might be the only game which needs https://github.com/hrydgard/ppsspp/pull/8757/commits/f08c873a4baeed8c04753ba9991824b47e992d1b so maybe it should find it's way into compat.ini? It will make harder to see if other games with some old bugs needed it, but seems better than having new issues.

**Comment by daniel229** [comment]
Tekken 6 's hang is the same bug.Kingdom Hearts Birth By Sleep I don't konw,but the final mix looks fine in the same area.

**Comment by unknownbrackets** [comment]
Another option is to update memory after the first safe draw, when switching to another buffer or at end of frame.  That will still capture a lot of one-frame-renders, which is the situation in the Katamari game.  But it'd be slightly more expensive.

Still, it'd definitely be a more general solution to the category of problem than giving up and using an ini file.

-[Unknown]

**Comment by daniel229** [comment]
Bleach 6 hangs after video.

**Comment by unknownbrackets** [comment]
Does this help?

https://github.com/hrydgard/ppsspp/compare/master...unknownbrackets:gpu-minor

-[Unknown]

**Comment by daniel229** [comment]
Yes,it does.

**Comment by unknownbrackets** [comment]
Hmm, I'm not seeing problems in Kingdom Hearts either way, but I only just tried going through the intro to when you have a ship to visit the first world.  Maybe I did something wrong.

-[Unknown]

**Comment by unknownbrackets** [comment]
Is this fixed now?

-[Unknown]

**Comment by LunaMoo** [comment]
Well Phantasy Star Portable series fixed, thanks:3.
Don't have anything else mentioned here to check through.

**Comment by daniel229** [comment]
All are fixed now.
