### ISSUE TITLE
For JIT recompiler on iOS 9 (64-bit) someone knows how to enable it

### ISSUE THREAD

**Issue by Fadi5555** [hrydgard/ppsspp#8786]
I was want to write this thread a while ago.
Anyway if you want to know how to enable JIT to iOS 9 jailbroken (64-bit) you have to ask @jpd002 about it. Because it could makes his ps2 emu (play!) run on iOS 9 jailbroken (64-bit) a long time ago.
This is a proof about that.
https://github.com/jpd002/Play-/issues/419#issuecomment-222398504

Also there is someone called @williamlcobb who could get JIT working on his project too. His project is called GC4iOS (gamecube) it's basically a port of dolphin emu for ios.
And this is his link to see his process specially about JIT.
https://github.com/WilliamLCobb/GC4iOS
And this is an image of his JIT on his project:
![image](https://cloud.githubusercontent.com/assets/10546081/17460225/5ca7a8b8-5c65-11e6-873c-1872c949ff8c.jpeg)

I just give you this information to be familiar with JIT more. I mean why other projects like GC4iOS as well as Play! Could implement JIT on their project and this amazing project still not?

Anyway I really hope all this information could help you out about how to enable JIT on this amazing project.

**Comment by hrydgard** [comment]
It's back!

**Comment by Fadi5555** [comment]
Yeah and it's works great.
But I noticed some stuttering on some games however my device is ipad air 2. Is that normal?
Thanks.

**Comment by hrydgard** [comment]
JIT doesn't mean that it's perfect, it's just our fastest CPU core. iOS devices are fast though so most games are likely to be quite playable, at least with 1 frameskip.
