### ISSUE TITLE
The Conveni Portable wrong savefile

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8810]
The save created by PPSSPP can't be loaded in either PPSSPP or PSP.
Compare the save of PPSSPP's and PSP's,the PIC1 is 170KB in PPSSPP,but the PSP one is 152KB,replace the 170KB with 152KB,then it works.

![ppssppsave](https://cloud.githubusercontent.com/assets/3481559/15990109/c4ae1b06-30bc-11e6-9a18-9862e21eece5.png)

![pspsave](https://cloud.githubusercontent.com/assets/3481559/15990110/c4cb96d6-30bc-11e6-8e88-b065a76be8b2.png)

debug log
![ppsspplog](https://cloud.githubusercontent.com/assets/3481559/15990141/6234b9ca-30bd-11e6-936d-c68b70cf6279.jpg)

jpcsptrace
![jpcsptracelog](https://cloud.githubusercontent.com/assets/3481559/15990145/700b50b8-30bd-11e6-82fb-a949a09d0779.jpg)
(rename jpg to rar)

**Comment by unknownbrackets** [comment]
Do the PIC1 images look the same, visually?  Can you attach them?

I'm wondering if it trims trailing nulls or something.  I'm not sure, but that might be safe with PNGs...

-[Unknown]

**Comment by daniel229** [comment]
Yes,look the same.
(rename jpg to 7z)
![pic1](https://cloud.githubusercontent.com/assets/3481559/15991256/06398fd8-30e0-11e6-95ca-da3fb02cadef.jpg)

**Comment by unknownbrackets** [comment]
Hmm, mostly zeros, but there's some random garbage.  Maybe the PSP actually looks for the IEND chunk... will need to do some tests.

-[Unknown]

**Comment by unknownbrackets** [comment]
Looked more closely at the JpcspTrace, and it specifies 152 KB, it was just using the wrong field for the file size.

-[Unknown]
