### ISSUE TITLE
SD Gundam G Generation Portable invalid addresses

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8816]
Since https://github.com/hrydgard/ppsspp/pull/8743

![01](https://cloud.githubusercontent.com/assets/3481559/16178217/c4e3dbca-3674-11e6-8b1b-746c89f59a28.png)
![02](https://cloud.githubusercontent.com/assets/3481559/16178218/c4f31856-3674-11e6-9c4a-e391e089867a.png)

**Comment by unknownbrackets** [comment]
Hmm.  A JpcspTrace would help, I think.... maybe there's some behavior that is allowed, which I missed.

sceDisplaySetFrameBuf 0x289D82FE xddd

-[Unknown]

**Comment by daniel229** [comment]
Jpcsptrace
https://gist.github.com/daniel229/659dcacaa77c7122be2296ae6043f49f

**Comment by unknownbrackets** [comment]
Well, that looks all correct.  If you look at a debug log, or change sceDisplaySetFrameBuf to NOTICE_LOG, does it make the same calls?  It seems like the initial one is missing in PPSSPP:

```
07:36:17.178116 user_main - -> sceDisplaySetFrameBuf 0x4088000, 512, 3, 1 = 0x0
07:36:17.178190 user_main - <- sceDisplaySetFrameBuf 0x4088000, 512, 3, 1 = 0x0
```

-[Unknown]

**Comment by daniel229** [comment]
Looks the same
https://gist.github.com/daniel229/8db6f92e64349789531d1dcedb03f0e3

**Comment by daniel229** [comment]
It's https://github.com/hrydgard/ppsspp/pull/8743/commits/44cee09adc41cce84c1ee38ef3db742781182b38

**Comment by daniel229** [comment]
Typo here?
https://github.com/hrydgard/ppsspp/pull/8743/commits/44cee09adc41cce84c1ee38ef3db742781182b38#diff-4a63423fd3c6e0ac181a90222b514dd8R824

**Comment by unknownbrackets** [comment]
Well, it might be that values other than `PSP_DISPLAY_SETBUF_NEXTFRAME` and `PSP_DISPLAY_SETBUF_IMMEDIATE` should result in errors for `sceDisplayGetFramebuf`.  But I don't see anything wrong on that line - it simply gives you the info you asked for.  It doesn't matter if you've latched the next frame yet or not.

Are you saying if you change that line back, it starts working again?

-[Unknown]

**Comment by daniel229** [comment]
Yes.

**Comment by hrydgard** [comment]
I changed it back for the 1.3.0 release, and commented why.

**Comment by unknownbrackets** [comment]
I'm going to mark this fixed, optimistically.  If it's still an issue, please comment and we'll reopen.

-[Unknown]
