### ISSUE TITLE
ppsspp danganronpa truth bullets

### ISSUE THREAD

**Issue by TMchimp** [hrydgard/ppsspp#8820]
i downloaded ppsspp on my pc and after that i downloaded danganronpa trigger happy havoc and everything seems to go well but i dont know how to shoot truth bullets (in trials), it says to press triangle but i dont know which key is triangle. can someone please help me asap? thank you

**Comment by GhettoGirl** [comment]
Simple as that.
Next time read manuals, enter configuration menus, google, etc. and don't open such useless issues.
![screenshot_20160621_181102](https://cloud.githubusercontent.com/assets/13280758/16237287/066ee158-37dc-11e6-9125-b5887160f86e.png)
![screenshot_20160621_181115](https://cloud.githubusercontent.com/assets/13280758/16237286/05800ac4-37dc-11e6-9e51-51d371df017e.png)
![screenshot_20160621_181135](https://cloud.githubusercontent.com/assets/13280758/16237288/06925228-37dc-11e6-85b1-cad434e0137e.png)

**Comment by TMchimp** [comment]
@GhettoGirl thank you so much!!!!!
