### ISSUE TITLE
opengl differnce to direct 3d plugin

### ISSUE THREAD

**Issue by asbel123** [hrydgard/ppsspp#8824]
i try opengl on my new laptop with nvdia 940mx grapchis its so slow its same speed is doilphin emulator i put direct 3d its faster than opengl u need to fix opengl speed more like andriod now.

i tell u why pcsx2 is fullspeed on opengl why it so slow on ppsspp opengl  i am not using speed hacks on pcsx2 opengl its kills my crappy computer i bought.

**Comment by asbel123** [comment]
fix it now

**Comment by hrydgard** [comment]
That's odd. Please try to download the latest drivers from your graphics card here:

http://www.nvidia.com/Download/index.aspx?lang=en-us

Make sure to choose the right operating system etc to get the right driver.

**Comment by asbel123** [comment]
i got updated lastest drivers ur missing something ppsspp is chose the video card like doilphin emulator does u can chose intel or nvdia gpu on the laptop. i am using windows 10.

**Comment by asbel123** [comment]
i try change the video card to nvdia still same speed problem on opengl its too much like my speed in samsung galaxy s6edge.

**Comment by ppsspp-gamer** [comment]
set ppsspp to use the discrete display card from nVidia display control panel.

**Comment by asbel123** [comment]
i fix it now i update the lastest driver i now understand about drivers its fixes performance problem and why andriod mali drivers is crap in new firmware 6.0 u can get fullspeed only nvdia get fullspeed with new drivers. i closed this issues its perfect. thank u hygard
