### ISSUE TITLE
PPSSPP crashes at startup after choosing Vulkan backend (the GPU supports Vulkan)

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [hrydgard/ppsspp#8826]
SO: Windows 10 x64
GPU: Nvidia 820M and Intel HD 4600 (I'm using the Nvidia gpu by default)

The drivers and the emulator are updated. Before the driver update which enabled Vulkan support, PPSSPP didn't let me choose Vulkan mode. Now I can choose it, but after that the emulator crashes every time I open it.

**Comment by LunaMoo** [comment]
Make sure to switch to "Skip buffer effects" rendering mode, Vulkan is still WIP and does not work with buffered rendering.

**Comment by RafaelTrepaUnCarballo** [comment]
That option doesn't fix the bug.

I want to clarify something: This crash happens any time I open PPSSPPWindows64.exe. It's not related with any game, it's the whole ppsspp emulator which crashes at booting.

Of course, I can't change the backend back to OpenGL or DirectX because the emulator crashes before I can see and open the configuration menu.

**Comment by unknownbrackets** [comment]
You can change it back in the ini file, or just by renaming away the ini file.  It can usually be found in Memstick/SYSTEM/ppsspp.ini.

We may not be handling Vulkan init properly when there are multiple physical devices available.  Vulkan exposes this differently than GL does.

-[Unknown]

**Comment by RafaelTrepaUnCarballo** [comment]
So, is Nvidia Optimous and my two GPUs the cause of my crash?

I hope you guys will find a way to make compatible my GPU. Is there a way to send you data about these crashes? Some kind of logs or usage data?

**Comment by HarlockTheSin** [comment]
![immagine](https://cloud.githubusercontent.com/assets/8268782/25508225/e983ea2e-2bb0-11e7-8507-b79b0043b924.png)
Where the hell is the bloody ppsspp.ini file?

I installed the emulator downloading the exe opened it, said cool it supports vulkan, let's use it. 
Emu crashed. retried to launch it and it still crashes...
![immagine](https://cloud.githubusercontent.com/assets/8268782/25508255/21096e6a-2bb1-11e7-99c2-65fada152a97.png)

Uninstalled and reinstalled same issue.

Downloaded the zip, overwrote, same issue.

Uninstalled with iobit uninstaller and reinstalled and still the same.

What can I do to play wipeout pure?

Any help is appriciated.

**Comment by hrydgard** [comment]
How is this now?

**Comment by HarlockTheSin** [comment]
I just installed version 1.4.2 and there is the same error.


[cid:9735df65-9f95-4811-a797-42c0ade1759b]

I have no idea...


Now I am not able to switch to direct3d anymore.


Regards,

Giovanni.


________________________________

**Comment by unknownbrackets** [comment]
Please try the latest git build:
https://buildbot.orphis.net/ppsspp/

We don't go back and modify past releases.  What was 1.4.2 will always be 1.4.2.  It will always have this bug, forever and ever.

-[Unknown]

**Comment by HarlockTheSin** [comment]
Using v1.4.2-738-gd4c345c87<https://github.com/hrydgard/ppsspp/commit/d4c345c870ca3a1e444993e22f94703fdad5db43>

This time it gives me error of Vulkan Device not found, and proposes me to switch back to OpenGl, so it starts..

My drivers should support Vulkan, What hardware do I need?

NVS 4200M should support it.


Thank you for the follow up!

________________________________

**Comment by hrydgard** [comment]
Well, at least that's a better outcome...  Really not sure, it starts up fine on all my devices that have Vulkan support.

**Comment by HarlockTheSin** [comment]
Sorry If I look dumb.

this is my driver version:

http://www.nvidia.com/download/driverResults.aspx/108579/en-us

[http://www.nvidia.com/content/DriverDownload-March2009/includes/us/images/Quadro_P6000_Driver-Family-220x200.png]<http://www.nvidia.com/download/driverResults.aspx/108579/en-us>

Quadro Desktop/Notebook Driver Release Windows 10 R367<http://www.nvidia.com/download/driverResults.aspx/108579/en-us>
www.nvidia.com
Download drivers for NVIDIA products including GeForce graphics cards, nForce motherboards, Quadro workstations, and more. Update your graphics card drivers today.

Doesn't this say that my card should support Vulkan?


Or maybe it's just PPSSPP who doesn't recognize the driver correctly...

Thank you for the help and support.


Regards.


________________________________

**Comment by hrydgard** [comment]
Searching https://vulkan.gpuinfo.org/ , there isn't a single report from an 820M, so maybe nVidia is just quietly not supporting that model .. I'm not sure.

**Comment by HarlockTheSin** [comment]
In the release notes of my driver it say that it supports Vulkan 1.0

http://us.download.nvidia.com/Windows/Quadro_Certified/369.49/369.49-win10-quadro-grid-release-notes.pdf
Release 367 Quadro, NVS, Tesla, GRID, & Notebook Drivers ...<http://us.download.nvidia.com/Windows/Quadro_Certified/369.49/369.49-win10-quadro-grid-release-notes.pdf>
us.download.nvidia.com
TABLE OF CONTENTS Release 367 Quadro, NVS, Tesla, GRID, & Notebook Drivers - Version 369.49 RN-07954-369.49_v01 | i 1 Introduction to Release Notes ...


Page 7 existing support.


Does PPSSPP supports Vulkan 1.0?

Regards.
________________________________

**Comment by RafaelTrepaUnCarballo** [comment]
I'm pretty sure my 820M don't support Vulkan.There are some contradictory information in internet because it seemed originally Nvidia was going to add OpenGL support to it, but in the end no fermi GPU got Vulkan support. There's nothing PPSSPP can do.

PPSSPP no longer crashes when I select Vulkan, it warns me something is wrong and allows me to change to openGL. It's the right behaviour.

**Comment by eekdkat** [comment]
Open file location

> SO: Windows 10 x64
> GPU: Nvidia 820M and Intel HD 4600 (I'm using the Nvidia gpu by default)
> 
> The drivers and the emulator are updated. Before the driver update which enabled Vulkan support, PPSSPP didn't let me choose Vulkan mode. Now I can choose it, but after that the emulator crashes every time I open it.

Open location file PPSSPP 64 or 86/memstick/PSP/SYSTEM/ppsspp/GPUBackend = 2 (change this value to 0 or 1 then save. Restart PPSSPP.

**Comment by eekdkat** [comment]
Open location file PPSSPP 64 or 86/memstick/PSP/SYSTEM/ppsspp/GPUBackend = 2 (change this value to 0 or 1 then save. Restart PPSSPP.
