### ISSUE TITLE
Are you plan to rewrite or introduce new Multithreading ?

### ISSUE THREAD

**Issue by zminhquanz** [hrydgard/ppsspp#8830]
Because , some game have bug glitch and crash , not perfect
Example : FF 7 Crisis Core , FF Type-0 , The 3rd Birthday

**Comment by unknownbrackets** [comment]
Questions like this are better for the forum:

http://forums.ppsspp.org/showthread.php?tid=18288

We already have issues about multithreading.  Closing.

-[Unknown]
