### ISSUE TITLE
Where can we find the latest build of ppsspp for non-jailbroken please?

### ISSUE THREAD

**Issue by Fadi5555** [hrydgard/ppsspp#8837]
Hi there I have an ipad air 2 on ios 9.3.2 can you give me the link to download the latest build for non-jailbroken devices please? This is for using IR Interpreter.

**Comment by Fadi5555** [comment]
Any answer please?

**Comment by hrydgard** [comment]
Sorry, I don't know how that stuff works anymore. Things have changed, now anyone can build and run executables on their own device using xcode. I don't know if there's some easy-install wrapper that uses that functionality or not, I haven't had time to keep up with the iOS scene.

**Comment by xiushudongfang** [comment]
May I put download link here?

**Comment by Fadi5555** [comment]
Yes please I really need it.

**Comment by xiushudongfang** [comment]
http://fir.im/15vn?release_id=574077c4f2fc42607400000f

**Comment by xiushudongfang** [comment]
Open this link by safari

**Comment by Fadi5555** [comment]
@xiushudongfang thank you so much for give me the link. that's really appreciate.
Love you. Now i will try to put games on it to try IR Interpreter

**Comment by Fadi5555** [comment]
@xiushudongfang thank you so much. Well if you can upload latest version of ppsspp on that same website I'll be grateful.

**Comment by Fadi5555** [comment]
@xiushudongfang please can you give me the latest build of ppsspp which is currently (v1.2.2-766)
Please upload it like when you did this before. I will be very grateful.
Thanks

**Comment by Loxe** [comment]
=-  = it's my build... ipa.... Why do some people come here release @xiushudongfang

**Comment by Fadi5555** [comment]
@Loxe hi there. I opened this thread before I jailbroken my device.
But now if I want the latest version of ppsspp of course I'll take from cydia.
Also if you want you can always upload the latest version of ppsspp for non-jailbroken device to could use it as well.
Thanks.

**Comment by Loxe** [comment]
@Fadi5555 http://fir.im/15vn?release_id=57c6dcfeca87a805f100223f
look here ，new version 1.2.2.898 
but this version iOS9.3.4.or later crsh 
befor iOS9.3.4 no crash and 30fps XD

**Comment by Loxe** [comment]
@Fadi5555 http://fir.im/15vn?release_id=57c6dcfeca87a805f100223f
look here ，new version 1.2.2.898 
but this version iOS9.3.4.or later crsh 
befor iOS9.3.4 no crash and 30fps XD

**Comment by Loxe** [comment]
@Faid5555 My blog has a lot of other simulators.
 i'am resign ，you can install on non-jb deivce http://iloxe.com

**Comment by Loxe** [comment]
i just resign ipa, share to all

**Comment by Fadi5555** [comment]
@Loxe thank you so much for sharing ipa version of ppsspp regularly. For non-jailbroken devices.

**Comment by unknownbrackets** [comment]
This isn't a forum ([although we have one](http://forums.ppsspp.org/)), so questions aren't the best format here.  It seems like #8942 is more relevant so I'm closing this.

-[Unknown]
