### ISSUE TITLE
Performance degradation of IR interpreter, and crashes

### ISSUE THREAD

**Issue by jettan** [hrydgard/ppsspp#8848]
Updating to v1.22-758 from v1.22-693 has so far caused more startup crashes when loading a game and performance degradation of ~5-6 fps (30 fps -> 24). Audio stutters even more than before and CPU load has increased (observed more battery drain).

Tested game:
Valkyria Chronicles 3 Extra Edition

**Comment by jettan** [comment]
Forgot to mention that I am testing on iOS 9.0.2, iPhone 6S

**Comment by hrydgard** [comment]
Hm. Are you sure this isn't due to some other setting that has been changed? Like for example setting Rendering Mode to any of the two read modes, etc. Try resetting settings.

**Comment by jettan** [comment]
Just resetted settings and the same problems still occur. Rendering mode has always been on buffered rendering.

**Comment by zero2029** [comment]
Indeed I am having the same issues as Jettan. Every time I load a game ppsspp crashes..... Even when loading a save state. I have stock iOS 9.3.2 iPhone 6s Plus. The ppsspp build from a week ago was working great with IR interpreter on. No crashes whatsoever. I tried to change settings but ppsspp still crashes upon loading a game. 😞

**Comment by zero2029** [comment]
If only I knew what the problem was...... I'm not very good with coding or debugging. 🤔 We apreciate your work though Hrydgard.

**Comment by hrydgard** [comment]
These would be the suspects then:

https://github.com/hrydgard/ppsspp/pull/8843
https://github.com/hrydgard/ppsspp/pull/8840

But both seem pretty safe...

**Comment by hrydgard** [comment]
@zero2029 are you also playing Valkyria, or does this happen with any game on ios?

**Comment by hrydgard** [comment]
I found some bugs in the IRJit. Stand by for a new build, I guess...

**Comment by zero2029** [comment]
It happens with any game. Thank you for looking in to it.

**Comment by jettan** [comment]
Thanks for the effort!
1.22-759 is now out on cydia, but same problems persist. So there is something more going on.

**Comment by jettan** [comment]
Also, no loading from ppsspp savestate was used, just a regular load game from save file.

**Comment by unknownbrackets** [comment]
Hmm, just to confirm - can you try using a desktop with the same games and IR interpreter, just to see if you have the same problems?  The IR code is all the same for all platforms, but if this only happens on iOS devices or only on mobile devices, it may help us find the problem faster.

-[Unknown]

**Comment by jettan** [comment]
Nice idea! I can compile for linux myself :)

**Comment by jettan** [comment]
Just tested and the problems are not present on linux SDL versions with IR interpreter.

**Comment by zero2029** [comment]
The latest build is working a little better but still crashes sometimes when selecting a game. https://twitter.com/zero2029/status/751498750758047745

**Comment by hrydgard** [comment]
I made another commit that I wouldn't expect to really help but just might, as it fixes an issue on Mac:

https://github.com/hrydgard/ppsspp/commit/c6d49660677ad8c620fac1122f26104c9456c703

**Comment by jettan** [comment]
Is it possible to get an iOS build with PR #8843 and #8840 separately. Maybe we can narrow down the search by testing each of the suspected PRs. Unfortunately I cannot build for iOS myself since I don't have access to a machine with OSX.

**Comment by jettan** [comment]
@hrydgard:
The last fix you commited (1.22-761 on Cydia) actually gets rid of the startup crashes and lowered performance graphic wise. Sound is still worse than it was originally on 1.22-693, but the rest seems to have returned to the original level of performance. :D

Thanks for your efforts and keep up the good work.

**Comment by hrydgard** [comment]
Sound is highly dependent on general performance to sound good, so if speed really is back up, I'd expect the sound to be as good/bad as before.. 

Anyway, seems like this can be closed. If there's a really big difference in audio quality, could you make a few recordings to compare and open a new issue? Thanks :)

**Comment by unknownbrackets** [comment]
Does this imply that Symbian would have crashes and performance issues?

-[Unknown]

**Comment by jettan** [comment]
Oops, seems the dissapearance of the problems was a false report. Somehow upgrading in cydia put my interpreter settings to the default one instead of IR.
So the problems are still there >_<

Please reopen this issue.

**Comment by zero2029** [comment]
Latest version of ppsspp 1.2.2-771-gd0b8e83 still crashes when loading games on IR Interpreter. 😞

**Comment by hrydgard** [comment]
Found another issue and fixed it. Try it whenever the buildbot is ready with it :)

**Comment by zero2029** [comment]
I sure will! Thank you sir! I will provide feedback when I do try it. Thank you for your hard work and dedication. 🙂👍🏼

**Comment by jettan** [comment]
So far no new build yet (cydia still showing 1.22-771)

**Comment by Dribblejam** [comment]
And still no new build. Not even on the main website:/

**Comment by zero2029** [comment]
It seems that the new ppsspp build fixed the IR Interpreter crashes. 😃 So far everything is running great.

**Comment by jettan** [comment]
I can confirm the startup crashes have been fixed. The slowdown of 5-6 fps has not.

**Comment by jettan** [comment]
Forgot to mention: 1.22-786

**Comment by sum2012** [comment]
Can close this issue ?

**Comment by jettan** [comment]
Not yet, as only half of the problem has been solved.

**Comment by unknownbrackets** [comment]
Is this still happening?  Is it a different snipe hunt than #9197?

-[Unknown]
