### ISSUE TITLE
Fails to start if SDL was built with SDL_JOYSTICK_DISABLED

### ISSUE THREAD

**Issue by jbeich** [hrydgard/ppsspp#8851]
DragonFly has broken joystick support in SDL, so it ends up disabled during configure. While that's fixable as DragonFly shares libusbhid with FreeBSD I can't easily test under VM (bhyve) as PPSSPP also wants OpenGL 2.0 and it doesn't work with swrast. Maybe call `SDL_Init()` several times with less stuff initialized until it succeeds or give up.

```
$ ppsspp
Unable to initialize SDL: SDL not built with joystick support
```

**Comment by hrydgard** [comment]
That's an easy one. I think that should do the trick.
