### ISSUE TITLE
Lumines 2 JP ULJM05232 not work after "now loading"

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#8853]
ppsspp forum link: http://forums.ppsspp.org/showthread.php?tid=15525

It never work , however USA version work.

v1.2.2-763-gdddb3c3
JP log (not work): https://gist.github.com/sum2012/1db7a93b247cb1e3bd15677c9d62243c
USA log (work): https://gist.githubusercontent.com/sum2012/c1b7ea2ed7a9bfc9868c056b7f5cf910/raw/7dc01057af387b2f528ace4bb826545fc50e2257/gistfile1.txt

disassum
![2](https://cloud.githubusercontent.com/assets/2177532/16710529/79360d88-4664-11e6-9b15-75d95852d9b1.png)

**Comment by unknownbrackets** [comment]
Whatever is at 0x08d13918 seems like it's wrong.  It seems like that thing is 0xef2440d1... but was probably expected to be a smaller value.  Something must be overwriting that memory.

Maybe if you set a breakpoint, where and how many times does it write there before the error?

-[Unknown]

**Comment by sum2012** [comment]
Do you mean that set 0xef2440d1 breakpoint write only ?

**Comment by unknownbrackets** [comment]
Oh, sorry, I meant 0x08d13918.  0xef2440d1 isn't a valid address, but seems to be the value at 0x08d13918.  I'm wondering what is writing to 0x08d13918 - it's possible that's the problem.

-[Unknown]

**Comment by sum2012** [comment]
It only 2 times
![1](https://cloud.githubusercontent.com/assets/2177532/16711857/2ef5ae06-46a3-11e6-949a-fd73ca7798b5.png)
![2](https://cloud.githubusercontent.com/assets/2177532/16711858/3314d2f0-46a3-11e6-9d90-d28732d4dbcc.png)

**Comment by sum2012** [comment]
@unknownbrackets 
v1.2.2-881-g22cef33
The first invalid address is related cpu speed.
cpu speed default:
48:17:907 lumines_main I[KERNEL]: HLE\sceKernelThread.cpp:1974 305=sceKernelCreateThread(lumines_file, 0880ff4c, 0000006f, 65536, 00000000, 00000000)
48:17:907 lumines_main I[KERNEL]: HLE\sceKernelThread.cpp:2053 0=sceKernelStartThread(305, 1052, 08ad26e8)
48:17:908 lumines_file I[KERNEL]: HLE\sceKernelThread.cpp:2140 sceKernelExitDeleteThread(0)
48:17:908 lumines_main W[MM]: MemmapFunctions.cpp:93 ReadFromHardware: Invalid address 37f579d1 PC 0888df3c LR 0888ddc8

cpu speed 100:
47:32:883 lumines_main I[KERNEL]: HLE\sceKernelThread.cpp:1974 305=sceKernelCreateThread(lumines_file, 0880ff4c, 0000006f, 65536, 00000000, 00000000)
47:32:883 lumines_main I[KERNEL]: HLE\sceKernelThread.cpp:2053 0=sceKernelStartThread(305, 1052, 08ad26e8)
47:32:885 lumines_main I[SCEGE]: Common\FramebufferCommon.cpp:414 Creating FBO for 00198000 : 256 x 256 x 0
47:32:886 lumines_main W[SCEGE]: Common\FramebufferCommon.cpp:447 FBO reusing depthbuffer, 00198000/00110000 and 00000000/00110000
47:32:917 lumines_file I[KERNEL]: HLE\sceKernelThread.cpp:2140 sceKernelExitDeleteThread(0)

Seem nornal cpu clock DeleteThread too fast,Not sure you have idea or not.
full log of both:
https://gist.github.com/sum2012/5b6bd1b37177359e9b9e07dd837cca25
https://gist.github.com/sum2012/b14419e3cb2aff4d70367d17cb7a7463

**Comment by unknownbrackets** [comment]
Does lumines_file call any sceIo functions?  It looks like no from those logs...

-[Unknown]

**Comment by sum2012** [comment]
Yes,it call  sceIo functions

cpu clock default:
5:46:443 lumines_main I[KERNEL]: HLE\sceKernelThread.cpp:1974 305=sceKernelCreateThread(lumines_file, 0880ff4c, 0000006f, 65536, 00000000, 00000000)
25:46:443 lumines_main I[KERNEL]: HLE\sceKernelThread.cpp:2053 0=sceKernelStartThread(305, 1052, 08ad26e8)
25:46:443 lumines_file D[IO]: HLE\sceUmd.cpp:317 0x32=sceUmdGetDriveStat()
25:46:443 lumines_file D[IO]: HLE\sceIo.cpp:1398 4=sceIoOpen(disc0:/sce_lbn0x60a0_size0x10f320, 00000001, 000001ff)
25:46:443 lumines_file D[IO]: HLE\sceUmd.cpp:317 0x32=sceUmdGetDriveStat()
25:46:443 lumines_file D[IO]: HLE\sceIo.cpp:1258 1110816 = sceIoLseek(4, 0, 2)
25:46:443 lumines_file D[IO]: HLE\sceUmd.cpp:317 0x32=sceUmdGetDriveStat()
25:46:443 lumines_file D[IO]: HLE\sceIo.cpp:1258 0 = sceIoLseek(4, 0, 0)
25:46:443 lumines_file D[IO]: HLE\sceUmd.cpp:317 0x32=sceUmdGetDriveStat()
25:46:443 lumines_file D[IO]: HLE\sceIo.cpp:968 sceIoRead(4, 08cbab50, 10f320): deferring result
25:46:446 lumines_file D[IO]: HLE\sceIo.cpp:1406 sceIoClose(4)
25:46:446 lumines_file I[KERNEL]: HLE\sceKernelThread.cpp:2140 sceKernelExitDeleteThread(0)
25:46:446 lumines_main W[MM]: MemmapFunctions.cpp:93 ReadFromHardware: Invalid address 37f579d1 PC 0888df3c LR 0888ddc8

cpu clock 100

30:52:465 lumines_main I[KERNEL]: HLE\sceKernelThread.cpp:1974 305=sceKernelCreateThread(lumines_file, 0880ff4c, 0000006f, 65536, 00000000, 00000000)
30:52:465 lumines_main I[KERNEL]: HLE\sceKernelThread.cpp:2053 0=sceKernelStartThread(305, 1052, 08ad26e8)
30:52:467 lumines_main I[SCEGE]: Common\FramebufferCommon.cpp:414 Creating FBO for 00198000 : 256 x 256 x 0
30:52:467 lumines_main W[SCEGE]: Common\FramebufferCommon.cpp:447 FBO reusing depthbuffer, 00198000/00110000 and 00000000/00110000
30:52:469 lumines_file D[IO]: HLE\sceUmd.cpp:317 0x32=sceUmdGetDriveStat()
30:52:469 lumines_file D[IO]: HLE\sceIo.cpp:1398 4=sceIoOpen(disc0:/sce_lbn0x60a0_size0x10f320, 00000001, 000001ff)
30:52:469 lumines_file D[IO]: HLE\sceUmd.cpp:317 0x32=sceUmdGetDriveStat()
30:52:469 lumines_file D[IO]: HLE\sceIo.cpp:1258 1110816 = sceIoLseek(4, 0, 2)
30:52:469 lumines_file D[IO]: HLE\sceUmd.cpp:317 0x32=sceUmdGetDriveStat()
30:52:469 lumines_file D[IO]: HLE\sceIo.cpp:1258 0 = sceIoLseek(4, 0, 0)
30:52:469 lumines_file D[IO]: HLE\sceUmd.cpp:317 0x32=sceUmdGetDriveStat()
30:52:469 lumines_file D[IO]: HLE\sceIo.cpp:968 sceIoRead(4, 08cbab50, 10f320): deferring result
30:52:481 lumines_file D[IO]: HLE\sceIo.cpp:1406 sceIoClose(4)
30:52:481 lumines_file I[KERNEL]: HLE\sceKernelThread.cpp:2140 sceKernelExitDeleteThread(0)
30:52:483 idle0        I[SCEGE]: GLES\Framebuffer.cpp:1922 Decimating FBO for 00000000 (480 x 272 x 3), age 6
30:52:580 lumines_main I[KERNEL]: HLE\sceKernelThread.cpp:1974 307=sceKernelCreateThread(lumines_file, 0880ff4c, 0000006f, 65536, 00000000, 00000000)
30:52:580 lumines_main I[KERNEL]: HLE\sceKernelThread.cpp:2053 0=sceKernelStartThread(307, 1052, 08ad26e8)
============================
Update with sceio debug full log:
cpu clock default:
https://gist.github.com/sum2012/a388f6ef46c9e3f243c6d4fc347fbdb0
cpu clock 100:
https://gist.github.com/sum2012/07c4c5db5abff8af9ab62da814956320

**Comment by sum2012** [comment]
@hrydgard @unknownbrackets 
jpcsp just fix the game in https://github.com/jpcsp/jpcsp/commit/82957225f4f4fe52f9c63f7fe0cbfe21af48a529 
Maybe ppsspp also need the same change (alloc/free callbacks).

**Comment by hrydgard** [comment]
Yes, seems likely. Nice.

**Comment by sum2012** [comment]
A small note that  anyone port above jpcsp 's code
you also need port https://github.com/jpcsp/jpcsp/commit/598e8d606258b39591ec3f78d969620499a563ee and https://github.com/jpcsp/jpcsp/commit/92a7d29f1419d4a6ad8a440f8ae82509ad8a3fec
otherwise Gran Turismo would crash in-game (if enable fast memory)

**Comment by sum2012** [comment]
Also need this for" Grisaia no Kajitsu: Le Fruit de la Grisaia - ULJM06232 & ULJM06233 "
https://github.com/jpcsp/jpcsp/commit/20e4582da310468ac2af9392ffb3996898b1bea5

**Comment by benderscruffy** [comment]
still happens in v1.9.3-164-g0a5ec4838

**Comment by unknownbrackets** [comment]
None of the IO timing methods make a difference either, right?

-[Unknown]

**Comment by benderscruffy** [comment]
nope no difference at all
