### ISSUE TITLE
Jikkyou Powerful Pro Yakyuu 2012 Ketteiban broken savedata

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8854]
The save made by PPSSPP does not work in PSP,but the one made by PSP works in PPSSPP.
jpcsptrace
https://gist.github.com/daniel229/ba8926d5e12c949824194bed5a0bc3de

debug log
https://gist.github.com/daniel229/b7e2b8368c02de46eedf663c02451bb7

the save(rename jpg to 7z)
Apparently the size of PARAM.SFO in NPJH50708BK is different. The PSP one is 5k,the PPSSPP one is 2K
![ppssppsave](https://cloud.githubusercontent.com/assets/3481559/16788184/6864bc02-48d5-11e6-8eab-173d0b0dd267.jpg)

![pspsave](https://cloud.githubusercontent.com/assets/3481559/16788185/68661390-48d5-11e6-8f63-327f0f15e114.jpg)

**Comment by daniel229** [comment]
Ingame save NPJH50708SM looks weird.
With PPSSPP save
![ppsspp](https://cloud.githubusercontent.com/assets/3481559/16788381/08107416-48d7-11e6-8ec6-d9707498aa24.png)

With PSP save
![psp](https://cloud.githubusercontent.com/assets/3481559/16788382/0822ed26-48d7-11e6-9373-f0a5b706e9c3.png)


![ppsspp_save2](https://cloud.githubusercontent.com/assets/3481559/16788407/5760b4ae-48d7-11e6-9023-25cd4b1cbf6c.jpg)
![psp_save2](https://cloud.githubusercontent.com/assets/3481559/16788408/576a71c4-48d7-11e6-8f3d-21b6d5dab691.jpg)

**Comment by unknownbrackets** [comment]
NPJH50708BK is missing SAVEDATA_FILE_LIST, which wasn't included because secureMode was false, presumably.  Tests show that should create a (blank) file list.

Not sure if that will fix this bug or not...

-[Unknown]

**Comment by unknownbrackets** [comment]
I'm going to close this and assume that it was fixed, until someone reports otherwise.  If you're reading this, and seeing the same bug in a recent git build or a newer version than v1.12.0, please comment and we'll reopen.

-[Unknown]
