### ISSUE TITLE
Port to x360

### ISSUE THREAD

**Issue by metalex10** [hrydgard/ppsspp#8856]
you port this excellent emulator to xbox360?

**Comment by hrydgard** [comment]
This has been done in the past, but the maintainer of the port has disappeared and there's noone left to do it.

**Comment by metalex10** [comment]
the emulator not play movies of games

**Comment by metalex10** [comment]
check this repository https://github.com/Ced2911/ppsspp

**Comment by unknownbrackets** [comment]
Yes, see #4716.  But Ced2911 didn't have enough time and interest to keep working on it.  Much of his work still exists in PPSSPP today, but some of it needs updating for improvements we've made to PPSSPP since then.

Are you volunteering?

-[Unknown]

**Comment by saywaking** [comment]
I would like to know which changes from ced2911 are merged into the official project. If you can tell me, what part's are changed and needs to be updated, i can look into this.

**Comment by hrydgard** [comment]
None, it's all been ripped out because it was impossible to maintain.

**Comment by saywaking** [comment]
Hmm, ok thanks.
I saw some merges, which are still in the official repo today. Like DirectX stuff etc.
But i guess, i will look into some old code till then.

**Comment by hrydgard** [comment]
Well yeah, DirectX support has been implemented but the particularities for the Xbox 360 version of DX9 have not been kept around. And more importantly, X360 is "big-endian" and we have not kept up compatibility with that. Even if you do proceed with restoring it and fixing all those bugs, you'll next run into porting FFMPEG. Have fun...
