### ISSUE TITLE
Undo Load/Save State

### ISSUE THREAD

**Issue by Anuskuss** [hrydgard/ppsspp#8861]
I don't know how feasible this is, but Libretro just released their new [RetroArch 1.3.6](http://www.libretro.com/index.php/retroarch-1-3-6-released/) which features a **Undo Load/Save State** mechanic.

> RetroArch now has the ability to undo a save- or load-state action through some automatic state-shuffling that happens behind the scenes, so you never have to worry about these situations again.
> **Undo Load State** – Before the ‘current’ state is altered by e.g. a ‘Load Savestate’ operation, ‘current’ is saved in memory and ‘Undo Load State’ restores it; you can also undo this option by using it again, which will make you flip-flop between 2 states.
> **Undo Save State** – If there was a savestate file that was overwritten, this option restores it.

Can we have something similar for PPSSPP?

**Comment by unknownbrackets** [comment]
We do have an undo feature now - its UI may be a bit lacking, but it is available.  Currently, it's disabled on mobile by default, I believe.  Maybe we should turn it on.

-[Unknown]

**Comment by Anuskuss** [comment]
Closed by #10737.
