### ISSUE TITLE
Error in DirectX mode

### ISSUE THREAD

**Issue by NgJinXiang14** [hrydgard/ppsspp#8863]
Hello, Im using windows xp, when i play game such as mhfu,dynasty warrior strikeforce it with give me (The instruction at "0x16240169" referenced memory at "0x15f680000". The memory could not be read.).this error show in ramdom time and situlation. Im using ppsspp 1.2.2 version in directx mode. Any help?

**Comment by NgJinXiang14** [comment]
![error](https://cloud.githubusercontent.com/assets/6142827/16985797/6f8d29b6-4eb5-11e6-9162-3d47bd1629b5.jpg)
This is the picture

**Comment by unknownbrackets** [comment]
Does this happen if you disable "fast memory" in the settings?

-[Unknown]

**Comment by NgJinXiang14** [comment]
Yes

**Comment by NgJinXiang14** [comment]
With or without fast memory it also same

**Comment by unknownbrackets** [comment]
And just to confirm - you're not able to use OpenGL?  Or it doesn't happen in OpenGL?

Are you using save states?  Does it happen if you load the game from normal saves only?

Can you try running DebugLog.bat and upload the log file it generates to gist.github.com?

-[Unknown]

**Comment by NgJinXiang14** [comment]
1.I unable to use OpenGL because of old gpu.
2.No,i dont use save state, i just normaly open it. 
3.Whats that?

**Comment by sum2012** [comment]
@NgJinXiang14 
![1](https://cloud.githubusercontent.com/assets/2177532/17111737/7da3ab1e-52d5-11e6-88a1-512306d80f3d.png)

After run the game,ppsspplog.txt would be generated

**Comment by NgJinXiang14** [comment]
https://www.dropbox.com/s/hyqg90sq3ng5tmo/ppsspplog.txt?dl=0.  This is the link to the ppsspplog.txt

**Comment by NgJinXiang14** [comment]
Why put no feedback

**Comment by unknownbrackets** [comment]
Has this improved at all, either with the latest git build of PPSSPP or with newer drivers?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
