### ISSUE TITLE
IR Interpreter mode

### ISSUE THREAD

**Issue by zero2029** [hrydgard/ppsspp#8869]
Latest version of iOS ppsspp 1.2.2-771-gd0b8e83 still crashes when loading games on IR Interpreter. 😞 Is there a way we can download a build from a ppsspp version when it didn't crash?

**Comment by hrydgard** [comment]
Duplicate of #8848, closing. I hear you.

**Comment by zero2029** [comment]
Indeed. Thank you for working on it. 🙂
