### ISSUE TITLE
PPSSPP JIT ios 9.3.3 Pangu

### ISSUE THREAD

**Issue by FerrazaDazzle** [hrydgard/ppsspp#8872]
Does PPSSPP Jit function on ios 9.2-9.3.3 with Pangu. JIT was broken in 9.0.2 so is it still broken in 9.3.3?

**Comment by unknownbrackets** [comment]
Most likely yes.  Questions are probably better suited for the forum, but #8122 would be updated if some workaround was available.

-[Unknown]

**Comment by Jamesthecanaidian** [comment]
I recently jail broke iOS 9.3.3 on my iPhone 6s as well and I don't believe jit functions or at least right now. I have a iPhone 5s that's jail broken and uses the jit function and runs at the same speed as my 6s when trying to run ppsspp but that was yesterday and the jailbreaks new so I'll have to check again. I'll be back if I find anything different

**Comment by Jamesthecanaidian** [comment]
I'm back. It still doesn't work, but that's probably because it just haven't been updated to use the jit on iOS 9.3.3 since the jailbreak is so new. Give it a week or two and hopefully it should work better

**Comment by Anuskuss** [comment]
@Jamesthecanaidian That's not an issue with how new the jailbreak is. You may have noticed that you have to start the jailbreak helper app everytime you reboot. They haven't patched the kernel so no JIT for you (please read #8122 before commenting again).

**Comment by Jamesthecanaidian** [comment]
Well I'm sorry I have bothered you and will try not to waste your time next time. Thanks

**Comment by Fadi5555** [comment]
I know someone who could implement JIT on jailbroken ios 9 devices (64-bit)

He creates an iOS port of dolphin emu. and could bring JIT successfully.
This is his project link. I think if @hrydgard knowing his method it could effect here and see JIT support again.

**Comment by Jamesthecanaidian** [comment]
ok good idea.
