### ISSUE TITLE
PES 2014 TEXTURE BLACK

### ISSUE THREAD

**Issue by Endarko** [hrydgard/ppsspp#8875]
after replace texture and mipmaping activated. pes 2014 game texture to black
![Uploading Screenshot_2016-07-27-03-49-26.png…]()
![Uploading Screenshot_2016-07-27-03-49-26.png…]()

**Comment by unknownbrackets** [comment]
Are you replacing with valid textures?  Are you using the latest git build?  Your images did not upload.

-[Unknown]

**Comment by curtisstephan86** [comment]
Good
