### ISSUE TITLE
CMake problem

### ISSUE THREAD

**Issue by tgwaste** [hrydgard/ppsspp#8883]
ted-mac/Users/ted/PSP/ppsspp/build-ios$ cmake -DCMAKE_TOOLCHAIN_FILE=../ios/ios.toolchain.cmake -GXcode ..
CMake Deprecation Warning at /opt/local/share/cmake-3.6/Modules/CMakeForceCompiler.cmake:79 (message):
  The CMAKE_FORCE_C_COMPILER macro is deprecated.  Instead just set
  CMAKE_C_COMPILER and allow CMake to identify the compiler.
Call Stack (most recent call first):
  ios/ios.toolchain.cmake:50 (CMAKE_FORCE_C_COMPILER)
  /opt/local/share/cmake-3.6/Modules/CMakeDetermineSystem.cmake:95 (include)
  CMakeLists.txt:3 (project)

CMake Deprecation Warning at /opt/local/share/cmake-3.6/Modules/CMakeForceCompiler.cmake:93 (message):
  The CMAKE_FORCE_CXX_COMPILER macro is deprecated.  Instead just set
  CMAKE_CXX_COMPILER and allow CMake to identify the compiler.
Call Stack (most recent call first):
  ios/ios.toolchain.cmake:51 (CMAKE_FORCE_CXX_COMPILER)
  /opt/local/share/cmake-3.6/Modules/CMakeDetermineSystem.cmake:95 (include)
  CMakeLists.txt:3 (project)

CMake Deprecation Warning at /opt/local/share/cmake-3.6/Modules/CMakeForceCompiler.cmake:79 (message):
  The CMAKE_FORCE_C_COMPILER macro is deprecated.  Instead just set
  CMAKE_C_COMPILER and allow CMake to identify the compiler.
Call Stack (most recent call first):
  ios/ios.toolchain.cmake:52 (CMAKE_FORCE_C_COMPILER)
  /opt/local/share/cmake-3.6/Modules/CMakeDetermineSystem.cmake:95 (include)
  CMakeLists.txt:3 (project)

CMake Deprecation Warning at /opt/local/share/cmake-3.6/Modules/CMakeForceCompiler.cmake:93 (message):
  The CMAKE_FORCE_CXX_COMPILER macro is deprecated.  Instead just set
  CMAKE_CXX_COMPILER and allow CMake to identify the compiler.
Call Stack (most recent call first):
  ios/ios.toolchain.cmake:53 (CMAKE_FORCE_CXX_COMPILER)
  /opt/local/share/cmake-3.6/Modules/CMakeDetermineSystem.cmake:95 (include)
  CMakeLists.txt:3 (project)

CMake Error at ios/ios.toolchain.cmake:129 (message):
  No iOS SDK's found in default seach path .  Manually set CMAKE_IOS_SDK_ROOT
  or install the iOS SDK.
Call Stack (most recent call first):
  /opt/local/share/cmake-3.6/Modules/CMakeDetermineSystem.cmake:95 (include)
  CMakeLists.txt:3 (project)

-- Configuring incomplete, errors occurred!
ted-mac/Users/ted/PSP/ppsspp/build-ios$ ls
CMakeCache.txt CMakeFiles
ted-mac/Users/ted/PSP/ppsspp/build-ios$ cmake -DCMAKE_TOOLCHAIN_FILE=../ios/ios.toolchain.cmake -GXcode .. > t
CMake Deprecation Warning at /opt/local/share/cmake-3.6/Modules/CMakeForceCompiler.cmake:79 (message):
  The CMAKE_FORCE_C_COMPILER macro is deprecated.  Instead just set
  CMAKE_C_COMPILER and allow CMake to identify the compiler.
Call Stack (most recent call first):
  ios/ios.toolchain.cmake:50 (CMAKE_FORCE_C_COMPILER)
  /opt/local/share/cmake-3.6/Modules/CMakeDetermineSystem.cmake:95 (include)
  CMakeLists.txt:3 (project)

CMake Deprecation Warning at /opt/local/share/cmake-3.6/Modules/CMakeForceCompiler.cmake:93 (message):
  The CMAKE_FORCE_CXX_COMPILER macro is deprecated.  Instead just set
  CMAKE_CXX_COMPILER and allow CMake to identify the compiler.
Call Stack (most recent call first):
  ios/ios.toolchain.cmake:51 (CMAKE_FORCE_CXX_COMPILER)
  /opt/local/share/cmake-3.6/Modules/CMakeDetermineSystem.cmake:95 (include)
  CMakeLists.txt:3 (project)

CMake Deprecation Warning at /opt/local/share/cmake-3.6/Modules/CMakeForceCompiler.cmake:79 (message):
  The CMAKE_FORCE_C_COMPILER macro is deprecated.  Instead just set
  CMAKE_C_COMPILER and allow CMake to identify the compiler.
Call Stack (most recent call first):
  ios/ios.toolchain.cmake:52 (CMAKE_FORCE_C_COMPILER)
  /opt/local/share/cmake-3.6/Modules/CMakeDetermineSystem.cmake:95 (include)
  CMakeLists.txt:3 (project)

CMake Deprecation Warning at /opt/local/share/cmake-3.6/Modules/CMakeForceCompiler.cmake:93 (message):
  The CMAKE_FORCE_CXX_COMPILER macro is deprecated.  Instead just set
  CMAKE_CXX_COMPILER and allow CMake to identify the compiler.
Call Stack (most recent call first):
  ios/ios.toolchain.cmake:53 (CMAKE_FORCE_CXX_COMPILER)
  /opt/local/share/cmake-3.6/Modules/CMakeDetermineSystem.cmake:95 (include)
  CMakeLists.txt:3 (project)

CMake Error at ios/ios.toolchain.cmake:129 (message):
  No iOS SDK's found in default seach path .  Manually set CMAKE_IOS_SDK_ROOT
  or install the iOS SDK.
Call Stack (most recent call first):
  /opt/local/share/cmake-3.6/Modules/CMakeDetermineSystem.cmake:95 (include)
  CMakeLists.txt:3 (project)

**Comment by unknownbrackets** [comment]
Did you install the iOS SDK?  It says it is not installed.

-[Unknown]

**Comment by tgwaste** [comment]
You mean Xcode?  Yes.  Maybe the problem is the new beta?  8.0

**Comment by unknownbrackets** [comment]
Xcode does not come with the iOS SDK by default.  I think it's under Preferences -> Downloads or something like that.

If you've installed that, maybe they've changed the way paths are set up again.

-[Unknown]

**Comment by tgwaste** [comment]
Ya im not finding that anywhere.

**Comment by tgwaste** [comment]
The fix:

cmake -DCMAKE_IOS_SDK_ROOT=/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -DCMAKE_TOOLCHAIN_FILE=../ios/ios.toolchain.cmake -GXcode ..

:)

**Comment by tgwaste** [comment]
When trying to open now I get: Incompatible Project Version.

**Comment by unknownbrackets** [comment]
Ah, if it's in some Xcode-beta.app location, you may need to edit ios.toolchain.cmake (since that appears to have a hardcoded Xcode.app path in it.)

Make sure to delete the build directory and re-run cmake in it from scratch.  Re-running cmake will only update some files, so it's better to start with a fresh buil directory.

-[Unknown]

**Comment by tgwaste** [comment]
Done.  Same issue.  :(

**Comment by unknownbrackets** [comment]
Is this still an issue?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.  It might be that we don't support beta versions of Xcode or the SDK, but it's been some time so I assume the motivation to use the beta has passed.

It's hard to tell when fixes in PPSSPP might fix other issues.  If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with iOS builds, just create a new issue instead.

-[Unknown]
