### ISSUE TITLE
PPSSPP (Dev-Latest) fails to install.

### ISSUE THREAD

**Issue by AlphAlyo** [hrydgard/ppsspp#8899]
I am on ios 9.3.2 , and I am trying to download the PPSSPP dev latest build, but I keep getting a buffer write error. Please help me for this issue.

**Comment by sum2012** [comment]
In the chinese forum ,they said can install but crash when load game.
Can you confirm this ?

**Comment by hrydgard** [comment]
Is this still a problem? If so it sounds like a Cydia problem more like a PPSSPP problem..

**Comment by jianmingyong** [comment]
Facing this in ios 9.3.3. Still doesn't work.

**Comment by ijoinit** [comment]
I think it's been fixed now
