### ISSUE TITLE
Afterburner Black Falcon video flicking since v1.1.1-673-g6d3368b

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#8902]
Just flicking in beginning

last good v1.1.1-669-g07dadca 
first bad v1.1.1-673-g6d3368b

It mean #8433 

v1.1.1-669-g07dadca log:
https://gist.githubusercontent.com/sum2012/5fb1efa86b39b33b2876f1a5ad84dc19/raw/49b80b0cb419ffda90c0a50de9983fa973d6082e/gistfile1.txt

v1.1.1-673-g6d3368b log:
https://gist.github.com/sum2012/ed14d3b3b80da5b4ea52fa2404ea1ce1

--
AFTER BURNER: BLACK FALCON - [EUR 1.00](http://report.ppsspp.org/game/ULES00753_1.00) / [EUR 1.00](http://report.ppsspp.org/game/ULES00785_1.00) / [USA 1.00](http://report.ppsspp.org/game/ULUS10244_1.00)

**Comment by unknownbrackets** [comment]
Perhaps we should add to assets/compat.ini?  Seems a bit ugly and unfortunate... but we don't have a good story with depth.

-[Unknown]

**Comment by unknownbrackets** [comment]
Oh, is this a duplicate of #8514?

-[Unknown]

**Comment by sum2012** [comment]
Yes,I close this one
