### ISSUE TITLE
Non-buffered rendering issue when closing/opening

### ISSUE THREAD

**Issue by zminhquanz** [hrydgard/ppsspp#8906]
![screenshot_2016-08-09-13-15-58](https://cloud.githubusercontent.com/assets/11285640/17506678/1c9ba766-5e35-11e6-84b7-a162a8daea3c.jpg)
When i'm home button to close ppsspp on android , open again on recent app ( multitask) , it going happen this issue

**Comment by zminhquanz** [comment]
@unknownbrackets

**Comment by vsub** [comment]
Non-buffered rendering is a hack and problems are to be expected while using it.
If the problem don't exist while using buffered rendering,then I kinda doubt you'll see a fix for this

**Comment by zminhquanz** [comment]
@vsub on PC , switch to Non-buffered rendering , is no having problem , but on Mobile is appear that problem

**Comment by sum2012** [comment]
@zminhquanz  what game do you test ?

**Comment by zminhquanz** [comment]
@sum2012 God Eater Burst , and i think almost game is appear that bug on Mobile

**Comment by marcotiger280998** [comment]
This is not a big issue. And sometimes it is white boxes, black boxes, or just the on screen button and text become black, or ppsspp asset (ppsspp logo, onscreen button image, etc). If set to buffered, when go to homescreen, it doesn't happen, but if the power button pressed (locked and screen off), the game will have missing texture or model (don't know what it is).

It is just a comment though. Not a big deal of problem.

**Comment by sum2012** [comment]
v1.2.2-962-g8e4bcd7 or newer may be fixed this

**Comment by zminhquanz** [comment]
@hrydgard i test latest version 1.3.0.1 , bug is appear again ( regression )

**Comment by hrydgard** [comment]
@zminhquanz  ready now.

**Comment by zminhquanz** [comment]
@hrydgard i don't know for another people test is it , but for me , it's fixed

**Comment by unknownbrackets** [comment]
We'll reopen or open other issues if we receive more reports.

-[Unknown]
