### ISSUE TITLE
Crashes on Galaxy S7

### ISSUE THREAD

**Issue by naendow** [hrydgard/ppsspp#8908]
Hello 

PPSSPP doesn't run on my Galaxy S7. If I try to load a ROM, it crashes or runs for a few seconds until it does it. I tried to disable JIT, but it doesn't make any difference.

I never used PPSSPP before, so you can call me a noob. It would be really great if someone could help me.

Thx =)

**Comment by hrydgard** [comment]
Try to sideload one of the latest builds: http://buildbot.orphis.net/ppsspp/  

We have a workaround that hopefully will help. An official release will be out in the reasonably near future...

**Comment by naendow** [comment]
Perfect, that helped! Thank you 👍
