### ISSUE TITLE
My game runs slow when I play dragon ball z 

### ISSUE THREAD

**Issue by solarlion** [hrydgard/ppsspp#8909]
When I play dragon ball z tag team and another road or shin budokai and when I play it it goes in slow motion idk why I heard that the speed runs on storage then I open icleaner and I see that my "/" is almost full is this the reason why it goes in slow motion? Please help

**Comment by unknownbrackets** [comment]
A better place for questions like these is [the forum](http://forums.ppsspp.org/).  You're likely to get a faster and better response from people who have actually played this particular game.

Free disk space normally isn't a factor in performance, but you should read the performance guides and look at the specs of your phone.

Closing this as it isn't about a bug.

-[Unknown]
