### ISSUE TITLE
transparencies issues on shield TV

### ISSUE THREAD

**Issue by tails101** [hrydgard/ppsspp#8911]
the shield TV suffer of transparency issues in ppsspp android.
flow is not playable with opaque water and ridge racer have issues with black shadows and some missing HUD element.
all with default settings.
but the speed is fast.

**Comment by unknownbrackets** [comment]
Is this with the latest git build?

-[Unknown]

**Comment by tails101** [comment]
playstore one.

**Comment by unknownbrackets** [comment]
The latest git build has fixes for transparency issues on the SHIELD.  It'll be in the next release, v.1.3.0, or you can download the git build from http://www.ppsspp.org/downloads.html.

This has already been fixed, so I'm closing - you can continue to reply though if you still have problems.

-[Unknown]
