### ISSUE TITLE
Naruto Shippuden Kizuna Drive switch back from power problem (Android)

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#8912]
@hrydgard @unknownbrackets 
Before switch power button
![screenshot_2016-08-14-16-14-07](https://cloud.githubusercontent.com/assets/2177532/17648242/630170be-6240-11e6-8f5d-69a92d208565.jpg)

switch back from power button
![screenshot_2016-08-14-16-14-43](https://cloud.githubusercontent.com/assets/2177532/17648244/729cec10-6240-11e6-8c57-a72fbf53d78b.jpg)

log (v1.2.2-853-g0924dbf) : https://gist.github.com/sum2012/3cd92abf38d986e7f0ebb02042e460bc

**Comment by unknownbrackets** [comment]
This doesn't happen when going to the menu and back?  Only when hitting power?

> NativeApp.audioInit() -- Using OpenSL audio! frames/buffer: 1152 optimal sr: 48000 actual sr: 44100
> AUDIO_OUTPUT_FLAG_FAST denied by client

That's probably not ideal.  1152 is causing us to miss the fast path (if it has one.)

> GLES/DrawEngineGLES.cpp:647 Unexpected buffer freed (10) but not tracked
> call to OpenGL ES API with no current context (logged once per thread)

Looks like something was cleared improperly, not sure if this is related.

-[Unknown]

**Comment by sum2012** [comment]
going to the menu and back menu and back have problem only have 20%
in-game 100% have problem (no use skill)

**Comment by unknownbrackets** [comment]
Did this used to work in v1.2.2 or an ealier version?

-[Unknown]

**Comment by sum2012** [comment]
1.2.1 work
1.2.2 don't work

**Comment by unknownbrackets** [comment]
Sounds like it might be related to our EGL stuff then.

If you force javaGL off (change [this line](https://github.com/hrydgard/ppsspp/blob/1c47778b4e92183642d1491deff54e933370a2f4/UI/NativeApp.cpp#L239) to `return "false";`), does it work again?

-[Unknown]

**Comment by sum2012** [comment]
No

**Comment by sum2012** [comment]
last work v1.2.1-63-gb137bf1
First break  v1.2.1-69-geaeddc6
It mean #8642

**Comment by unknownbrackets** [comment]
Thanks - that's pretty helpful.  I think we're deleting things during gl restore and also creating things, and sometimes we're deleting things we just created.  I'm just separating it out into two phases, which I think will be clearer.  We'll see, hopefully it fixes this.

-[Unknown]

**Comment by sum2012** [comment]
v1.2.2-962-g8e4bcd7 fixed,closing
