### ISSUE TITLE
Controller issues in the latest nightly

### ISSUE THREAD

**Issue by GamerzHell9137** [hrydgard/ppsspp#8915]
Something going on with the Controller settings
http://puu.sh/qCIIc/cd89a7f4bf.png

And it seems if a controller is seen as a second controller it can't be used on PPSSPP.
Can you guys look into adding support for that?

**Comment by GamerzHell9137** [comment]
@hrydgard Can you guys look at the controller thing thou?
For w/e reason PPSSPP doesn't recognize it even thou the controller works on PC games and other emulators (DS3 controller with the SCP Server)

**Comment by unknownbrackets** [comment]
There's no need for a duplicate of #8250.

It's probably not something I'm personally going to spend time on anytime soon.  Feel free to muster the courage and try it - this isn't a particularly tricky or complicated part of the code, so it's probably a good thing for someone newer to coding.

-[Unknown]
