### ISSUE TITLE
The save state preview is displayed when starting a game.

### ISSUE THREAD

**Issue by vsub** [hrydgard/ppsspp#8916]
This happens only on games that have custom settings

If the save state for the current game is set to anything other than slot 1 while starting a game,when you start the game,the preview will be displayed

For example:
1.Start a game and create a save state on slot 1 and any other slot
2.Exit while slot 1 is selected and when you start the game again you'll see no preview
3.Exit while another slot is selected(that have a save state)and when you start the game you'll see a preview

**Comment by unknownbrackets** [comment]
Hmm, it seems that `iCurrentStateSlot` is considered a game-specific setting, so it basically sees it as if you just changed the slot (i.e. by pressing the shortcut to cycle slots.)  That's why it shows.

If you put this at the end of `bootComplete()`, does it fix it?

```c++
	saveStateSlot_ = SaveState::GetCurrentSlot();
```

-[Unknown]

**Comment by vsub** [comment]
I can't compile ppsspp but that seems to be correct...if I select the first slot and exit a game that have game specific settings,when I start it again,the preview is not displayed.
