### ISSUE TITLE
PPSSPP crashes When changing some option for example Vertex cache 

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8918]
Open PPSSPP ->click Settings -> click Vertex cache -> crash.  But it doesn't crash in bebug build.
![01](https://cloud.githubusercontent.com/assets/3481559/17720098/d25097ac-6451-11e6-8e78-27b5ca70c56c.png)

![01](https://cloud.githubusercontent.com/assets/3481559/17720757/0fff66d2-6457-11e6-9b04-d5172b8c5667.png)

**Comment by unknownbrackets** [comment]
Oops, does it help to change all `[&]` to `[=]` in the GameSettingsScreen.cpp file?

-[Unknown]

**Comment by daniel229** [comment]
Yes,it does.

**Comment by unknownbrackets** [comment]
e4b0f295b20af3a0dc67bc1dd9da67aae30a12b2

-[Unknown]
