### ISSUE TITLE
Patapon 2 saves

### ISSUE THREAD

**Issue by camman0000** [hrydgard/ppsspp#8922]
I have gotten a patapon 2 ios for my ppsspp emulator and the game seems to work, after hours of research i have finally moved my psp save files for patapon 2 over into SAVEDATA for ppsspp. I have no clue on how to get them to pull up my old saves, continue says 'there is no data' when i try to use it. The only thing that i have noticed thats different from anything is that the icon of the 1 'save' i have on the emulator is green while the saves i brought over from psp are purple. I might be dumb but to be honest I just have no clue why they shouldn't work seeing as that I copied the saves from psp straight to the savedata of ppsspp. Please give me a hand if you are so kind?

**Comment by Anuskuss** [comment]
Your version of Patapon 2 for PSP is different than the ISO in PPSSPP. Try to rip your UMD instead of downloading it.

**Comment by camman0000** [comment]
Do you know of a good guide to do so?

**Comment by camman0000** [comment]
well, the problem is, i dont actually have a umd copy of patapon 2, it broke a long time ago, but i still have the 52 hours on a save i wanted to go back to. I just ended up putting patapon 3 on my pc...    whoops.

**Comment by camman0000** [comment]
is there a way for me to find out the version of the patapon 2 game i had on save and find that specific emulator like download?

**Comment by Anuskuss** [comment]
Well, you said you moved your saves from PSP to PPSSPP. Look at the name of the Savefolder (e.g. `UCES011770000`) on your PSP and compare it to the Savefolder from PPSSPP. You can look up all the Product ID's on [GameFAQs](http://www.gamefaqs.com/psp/950766-patapon-2/data) and when you got your ID, try to google your specific game.

**Comment by camman0000** [comment]
I found out how to, thank you so much for the help!
