### ISSUE TITLE
Gundam Memories can't go ingame

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8926]
since https://github.com/hrydgard/ppsspp/pull/8701

**Comment by unknownbrackets** [comment]
Well, the real change is here:

https://github.com/hrydgard/ppsspp/pull/8701/commits/f9ba0d7321598b597bf20610fc83946c0afb71a3#diff-81fdce96b452cd0ebc9b0752a485331bR288

It was previously ignoring the dependencies, which made Kamen Rider OOO fail to run.

What's the log look like?  Which modules is it loading, and which one is failing?  Maybe it's loading a module from a prx, which isn't accounted for here...

-[Unknown]

**Comment by daniel229** [comment]
user_main    E[UTIL]: HLE\sceUtility.cpp:288 8002013c=sceUtilityLoadModule(00000308): dependent module 0303 not loaded

**Comment by daniel229** [comment]
58:53:434 user_main    I[UTIL]: HLE\sceUtility.cpp:306 0=sceUtilityLoadModule(00000301)
58:53:467 user_main    I[UTIL]: HLE\sceUtility.cpp:306 0=sceUtilityLoadModule(00000300)
58:53:484 user_main    I[UTIL]: HLE\sceUtility.cpp:306 0=sceUtilityLoadModule(00000302)
58:53:516 user_main    I[UTIL]: HLE\sceUtility.cpp:306 0=sceUtilityLoadModule(00000304)

**Comment by unknownbrackets** [comment]
Does it have an mpegbase.prx or mpeg.prx anywhere?  Are there any sceKernelLoadModule* calls?

-[Unknown]

**Comment by daniel229** [comment]
Look like libdeflt.prx and libfont.prx
```
08:28:455 user_main    I[HLE]: HLE\scePower.cpp:369 scePowerSetClockFrequency(333,333,166)
08:28:491 user_main    I[MODULE]: HLE\sceKernelModule.cpp:1049 ~SCE module, skipping header
08:28:491 user_main    I[HLE]: ELF\PrxDecrypter.cpp:308 Missing key 5B, cannot decrypt module
08:28:491 user_main    I[MODULE]: HLE\sceKernelModule.cpp:1766 288=sceKernelLoadModule(name=disc0:/PSP_GAME/USRDIR/Module/libdeflt.prx,flag=00000000,(...))
08:28:491 user_main    I[MODULE]: HLE\sceKernelModule.cpp:1798 sceKernelStartModule(288,asize=00000000,aptr=00000000,retptr=09fff510,00000000): faked (undecryptable module)
08:28:492 user_main    I[MODULE]: HLE\sceKernelModule.cpp:1049 ~SCE module, skipping header
08:28:492 user_main    I[MODULE]: HLE\sceKernelModule.cpp:1063 Loading module sceFont_Library with version 0101, devkit 06030510
08:28:492 user_main    I[HLE]: ELF\PrxDecrypter.cpp:308 Missing key 5B, cannot decrypt module
08:28:492 user_main    I[MODULE]: HLE\sceKernelModule.cpp:1766 289=sceKernelLoadModule(name=disc0:/PSP_GAME/USRDIR/Module/libfont.prx,flag=00000000,(...))
```

**Comment by daniel229** [comment]
total four .prx loaded
15:40:395 user_main    I[MODULE]: HLE\sceKernelModule.cpp:1766 428=sceKernelLoadModule(name=disc0:/PSP_GAME/USRDIR/Module/libpsmfplayer.prx,flag=00000000,(...))

15:40:394 user_main    I[MODULE]: HLE\sceKernelModule.cpp:1766 427=sceKernelLoadModule(name=disc0:/PSP_GAME/USRDIR/Module/psmf.prx,flag=00000000,(...))

**Comment by daniel229** [comment]
full log
https://gist.github.com/daniel229/971a203db0d9ffdfcdb50060dca85653

**Comment by unknownbrackets** [comment]
Hmm, it does eventually load 0x303:

18:31:012 user_main I[UTIL]: HLE\sceUtility.cpp:306 0=sceUtilityLoadModule(00000303)

But then it unloads it:

18:32:556 user_main I[UTIL]: HLE\sceUtility.cpp:327 0=sceUtilityUnloadModule(00000303)

What does the log look like with `ModuleLoadInfo(0x0308, 0x0003c000, mp4ModuleDeps),` changed to `ModuleLoadInfo(0x0308, 0x0003c000),`?

-[Unknown]

**Comment by daniel229** [comment]
it go ingame now.
```
26:48:320 user_main    I[ME]: HLE\sceMp4.cpp:51 sceMp4Init()
26:48:320 user_main E[ME]: HLE\sceMp4.cpp:57 UNIMPL sceMp4Finish()
```
instead

full log
