### ISSUE TITLE
Crash on trying to pause on Kubuntu 16.04

### ISSUE THREAD

**Issue by napolinkinpark3r** [hrydgard/ppsspp#8930]
Just got **1.2.2** version from **ppa:ppsspp/stable** and tried to play couple of games (X Men Legends 2, MUA 1, Midnight Club 3). But every time i'm trying to pause (not just via Esc key, i've tried other ones, on gamepad too), emulator crashes
_(I wish I could give you some logs but I didn't figure out how to make it on Linux)_

**Comment by unknownbrackets** [comment]
If you install gdb, you can run it like this:

```sh
gdb /path/to/PPSSPPSDL
```

Then, at the `(gdb)` prompt, type `run`.  Now just make it crash.

Once it crashes, you'll have a `(gdb)` prompt again.  Type `bt`.  Then copy all the output from after you typed `run` and paste it here: https://gist.github.com/, then paste a link to that as a reply here.

-[Unknown]

**Comment by napolinkinpark3r** [comment]
@unknownbrackets there is log from crash https://gist.github.com/napolinkinpark3r/8bd660f58ddbebb8a5d09823e0c6aace

I want to note that development version form ppa:ppsspp/testing doesn't reproduce this issue (this one works just fine)

**Comment by unknownbrackets** [comment]
If it works in a more recent version, it probably means we've fixed it.  Sounds like it'll be resolved in v1.3.0.

I'm not really sure what the fix could be.  If you're interested, you can use a bisect:

https://github.com/hrydgard/ppsspp/wiki/How-to-bisect-to-find-what-broke-a-game

Just swap "good" and "bad".  Say "bad" when it doesn't crash, and "good" when it does crash.  Then it will find the "first bad commit" which is the first one that fixed the crash.  There are around 900 commits so this would take ~10 compile/test runs or so.

-[Unknown]

**Comment by unknownbrackets** [comment]
Well, it might be nice to confirm that it's for sure fixed, but I'm going to go ahead and close this since it works with more recent code than v1.2.2.  Just comment here if I'm mistaken or if you find it's not, and we'll reopen.

-[Unknown]
