### ISSUE TITLE
Jit is not working

### ISSUE THREAD

**Issue by justlamb07** [hrydgard/ppsspp#8936]
Cant enable jit on my phone i dont know why

**Comment by Fadi5555** [comment]
Yeah currently is not available. But don't worry the devs here are working to implement it again.
And they get a good results so far. It's matter of time to get it work again.

This is an official link about JIT on iOS: you can ask questions there if you want.
https://github.com/hrydgard/ppsspp/issues/8122

Good luck.

**Comment by hrydgard** [comment]
Now you can, in the latest builds!

**Comment by justlamb07** [comment]
Wow thank you so much !! It is working now 😊👍👍😀👍
