### ISSUE TITLE
Stutter on Win7 (May has something to do with Async IO)

### ISSUE THREAD

**Issue by arimasu5** [hrydgard/ppsspp#894]
When it stutter, I noticed that there was always a function "sceIoChangeAsyncPriority" appeared in the log window.

And there is an known issue on Win7, which is a system issue though.
http://social.msdn.microsoft.com/Forums/en-US/windowsgeneraldevelopmentissues/thread/8941dc4b-8c91-406b-884b-36b9d3ad93ab/

I'm not sure if this Win7 system issue has anything to do with the ppsspp stutter problem,
but just a clue, thanks.

**Comment by unknownbrackets** [comment]
There hasn't been a reply in over a year, and there have been many performance improvements.  Stutter may be improved by changing the "IO timing method" in system settings.

If we want to do any specific things with shader caching or etc. (which have tradeoffs...), those seem like separate bugs.

-[Unknown]
