### ISSUE TITLE
resign deb -> ipa install on the non-jailbreak system 

### ISSUE THREAD

**Issue by Loxe** [hrydgard/ppsspp#8942]
i'am build ipa with non-Jailbreak iOS 
test iOS7 iOS8 perfect （fps30）
but iOS9 open game~ crash  
version 1.2.2.898

**Comment by Loxe** [comment]
sorry! 
now test 
iOS9.1 no crash
iOS9.3 crash

XD XD XD

**Comment by Loxe** [comment]
test iOS9.3.4 or last crash

**Comment by Loxe** [comment]
yesterday test 
iOS9.3.3 or later crash

XD XD XD

**Comment by unknownbrackets** [comment]
So if I'm understanding right, we fixed it just in time for iOS 9.3.4 to break it again?

-[Unknown]

**Comment by Emurig** [comment]
Just tested  PPSSPP 1.2.2.898 from the link above on non-jailbroken iphone 6 and iphone 5S both on ios 9.3.3.
Interpreter-crash when try to start any game, iphone 6,iphone 5S
Dynarec JIT-crash when try to start any game,iphone 6,iphone 5S
IR Interpreter-crash when try to start any game,iphone 6,iphone 5S.
It seems that latest PPSSPP not working at all on no-jailebroken devices.

**Comment by seadil** [comment]
How did you install it?

**Comment by unknownbrackets** [comment]
This is a pretty old issue, and there are newer issues about iOS.  Recent devices should run in IR Interpreter mode.

I'm going to close this issue since I think it's about more outdated devices and SDKs.

-[Unknown]
