### ISSUE TITLE
Games intro music is played on the pause screen

### ISSUE THREAD

**Issue by vsub** [hrydgard/ppsspp#8944]
I don't know if this is a feature or a bug but:

1.Right click on a game that have music in the game info screen
2.Click on the Play button
3.Press Esc to go to the Pause screen
The game intro music will continue playing from the position you stop it when you click on the play button

If you directly start the game(without entering the game info screen),then going to the pause screen will not play the music

And there is something else too(not related to this but I don't know if it wort making another issue)

In the Display Layout Editor the text in the middle is divided like this
S
tr
et
in
g

**Comment by hrydgard** [comment]
#8952 says it's fixed, so let's close. Please reopen if you see this again.

**Comment by hrydgard** [comment]
Eh doh, it probably didn't do anything about the audio.

**Comment by vsub** [comment]
About the text wrapping...now it's wrapping it like this
Stretchin
g

I'm using Comic Sans MS as a font

**Comment by unknownbrackets** [comment]
Okay, changed that in #8954 also.

-[Unknown]
