### ISSUE TITLE
1.2.2 android built error

### ISSUE THREAD

**Issue by lcrjeff** [hrydgard/ppsspp#8946]
1.2.2 built for android ,
ab.cmd,flash to back
ndk r12b

**Comment by sum2012** [comment]
You need latest git source
Also ,do you forget git submodule update --init --recursive

**Comment by unknownbrackets** [comment]
You can look at Travis to see how we build - it's intentionally easy and reproducible.

If you're having problems setting up a development environment, you'll probably get better feedback [posting in the forum](http://forums.ppsspp.org/forumdisplay.php?fid=3).  I think there are even posts about how to set one up.

-[Unknown]
