### ISSUE TITLE
Strange increase in the cpu usage

### ISSUE THREAD

**Issue by vsub** [hrydgard/ppsspp#8953]
When I just start ppsspp,my cpu core usage is barely moving above 2% and the cores speed is 800Mhz(meaning idle)
If I go to "Controls Mapping" the cpu usage goes up and the cores speed is increased twice(1.6Ghz)
And if I go there while a game is running,it will increase the cpu usage even more and it will make the cpu to go in turbo mode which is 3.7-3.9Ghz

i7 4771

**Comment by vsub** [comment]
It acts now a little batter(it rarely goes to 1.6ghz outside a game)but while ingame the cpu is always at turbo mode.

**Comment by vsub** [comment]
It's not fixed,the high cpu usage is still happening on those screens only while ingame and I found the reason...it's vsync
![2016-09-05_064354](https://cloud.githubusercontent.com/assets/5032540/18236943/51516392-7334-11e6-9bbb-7c4e22440380.jpg)

**Comment by unknownbrackets** [comment]
With vsync on or off?  Doesn't happen for me - the only cpu usage I could reproduce was text size measurement (control settings was doing a lot of that since there were tons of little text views.)

Did this not used to happen?  Maybe finding the first/last would help.

-[Unknown]

**Comment by vsub** [comment]
With vsync on...it could be something on my end but I don't remember seeing thing before(or maybe I never gone to those menus while ingame)

I'll try some old revs when I get home.
I'm using Win 7 x64 with aero enabled and as I said,it happens only in those menus and only while ingame

1.Start ppsspp with vsync already enabled
2.Start some game and go to the pause screen
3.Go to some of the screens I mention above

**Comment by unknownbrackets** [comment]
Right - I'm also on Win7 x64 with Aero.  I'm using an NVIDIA GTX 950 card and recent drivers.  I set Vsync on, restarted, opened Crisis Core, pause -> Settings -> Developer Tools.  PPSSPP is using virtually no CPU.

Using VerySleepy, I can see that all the threads are pretty quiet.  Profiling the main thread, it's spending 96% of its time sleeping, 3% rendering, and 1% swapping.

-[Unknown]

**Comment by daniel229** [comment]
This happen while Vsync on and Threaded Optimization on in nvidia control panel for me.

**Comment by unknownbrackets** [comment]
Hmm, I tried setting both of those to On (they were previously Auto/app controlled), but still did not reproduce.  The driver version I'm using is 10.18.13.5645, a bit older than I thought.  Are you using a newer one?

-[Unknown]

**Comment by vsub** [comment]
I'm not using the latest drivers but I also notest that it only happens while using OGL(the cpu speed don't move from 800mhz even in the controller settings screen while using DX\Vulkan)

The easiest solution(but not actually fixing the problem)is to display the game background(since it happens only while ingame)in all screens\menus

I'm with GTX750TI and the 364.51 drivers version

**Comment by hrydgard** [comment]
Maybe you're just reaching some threshold in the driver to switch it to internally threaded mode (which nvidia drivers often do), and that for some reason is just enough to switch your CPU up in frequency? I dunno. Seems strange...

**Comment by daniel229** [comment]
I am using the latest one 372.70.Sometime it can't be reproduced,try resetting the computer.

**Comment by vsub** [comment]
If I disable vsync in ppsspp and set it to On/Adaptive in the nVidia Control Panel(force on),then this happens on all screens(even while not ingame)and it returns to normal if I pause a game/right click on it to see the background rather than that blue screen with moving buttons.

There  must be something that is causing this because it happens even on ppsspp 0.9.1

**Comment by unknownbrackets** [comment]
Are you able to compile it?  If so:

Option 1. Use VerySleepy, http://www.codersnotes.com/sleepy/, point it at PPSSPPWindows64.exe, and then ideally just profile any thread that's > 10% cpu usage on the right side.

Option 2. In Visual Studio, press Alt-F2.  Check "CPU Usage", and then click "Start".

After exiting, you should get a CPU profile.  This shows what functions are using all the juice.  The culprit should be near the top - a screenshot should be enough.

-[Unknown]

**Comment by vsub** [comment]
Do I have to start ppsspp with VerySleepy or select it from the running processes...or it doesn't matter.

I think I saw something similar in process hacker....some drivers validation.
If I suspend certain ppsspp thread for around 10 seconds after I start and then resume it,then the problem is gone from everywhere until I restart ppsspp

**Comment by vsub** [comment]
Here is the log from VerySleepy
http://www60.zippyshare.com/v/nPYGEAbd/file.html

**Comment by unknownbrackets** [comment]
Well, this looks like you didn't compile it, so there's no symbols.  That being said, it's spending 88% of its time sleeping, 3-4% swapping, and some other time on multithreading.

Maybe the driver is what's actually clocking up the CPU?

-[Unknown]

**Comment by vsub** [comment]
Which driver....cpu or gpu.
I have some power saving\managing options enabled in bios

**Comment by vsub** [comment]
With threaded optimization disabled,the problem is gone and for whatever reason,I get more speed when it's disabled(not that I actually need it)....from 10 all the way to 50 and more depending on the game and the screen I am at

**Comment by unknownbrackets** [comment]
Well, I was thinking of the GPU driver.

The most intensive thing happening in that background is the moving symbols, which shouldn't be very intensive.

Does it change if you remove this part?  This is what does the animated symbols:

https://github.com/hrydgard/ppsspp/blob/b06359edd182456c4b107b00d6424b52b0193a99/UI/MiscScreens.cpp#L91-L99

When it draws the game background, it doesn't draw these.

Hmm... that's odd.  Sounds like the threaded optimization isn't working well.  I know I've seen it benefit me greatly on a 9800 GT, but it's harder to tell on this GTX 950...

-[Unknown]

**Comment by vsub** [comment]
Sadly I can't compile ppsspp

Threaded optimization helps a little(or there is no difference)only while I'm doing something crazy like 10x resolution along with 5x texture scaling and fps limit off

**Comment by daniel229** [comment]
Disable the moving symbols does help it,cpu usage dropping from 20% to 2%

**Comment by unknownbrackets** [comment]
If you leave `ui_draw2d.DrawImageStretch(img, dc.GetBounds());` is it fine?

If you cut down to only 10 symbols (just the 100 in `for (int i = 0; i < 100; i++) {`), is it already faster?  Or does even drawing any symbols incur the wrath of 20% cpu usage? 

-[Unknown]

**Comment by daniel229** [comment]
27 symbols or less takes 2% cpu usage.
28 symbols or more takes 20% .

**Comment by unknownbrackets** [comment]
Hmm, clearly sounds like some heuristic by the GPU driver... 

What happens if you add `ui_draw2d.Flush();` right after `ui_draw2d.DrawImageStretch(img, dc.GetBounds());` and also right after `ui_draw2d.DrawImageRotated(symbols[n], x, y, 1.0f, angle, colorAlpha(colors[n], alpha * 0.1f));`?

This would normally make it slower, but it might cause the heuristic not to trip.  This isn't a fix, just wanting to validate.

-[Unknown]

**Comment by daniel229** [comment]
With that, it's 3%~4%.

**Comment by hrydgard** [comment]
Odd stuff, probably caused by dynamic VBO allocation to draw the little symbols, tripping the driver into another mode. Not sure it makes sense to optimize for the heuristics of a particular driver... especially if in-game performance isn't much affected.

**Comment by unknownbrackets** [comment]
Oh, good idea - what if you change this line:

https://github.com/hrydgard/ppsspp/pull/8894/files#diff-fe1a86ac85c791c4647731895d97d913R83

To:

```c++
gl_extensions.IsCoreContext = true;
```

Which would cause us to use our own VBOs and VAOs - just wondering if this keeps us in the fast path, without any other changes.

-[Unknown]

**Comment by daniel229** [comment]
Also works with that.

**Comment by unknownbrackets** [comment]
Is this still a problem with the latest and greatest drivers?  If it isn't, I don't think we should try to fight heuristics in external code.

-[Unknown]

**Comment by unknownbrackets** [comment]
We're using core contexts by default now - presumably fixing this, per the above.

I'm going to close, assuming that it's fixed (or as best we can), but if it's still an issue please comment.

-[Unknown]
