### ISSUE TITLE
Can you give a explanation on how to build c++ libries

### ISSUE THREAD

**Issue by freshindee** [hrydgard/ppsspp#8962]
Hi,

Can you give a explanation on how to build c++ libraries for android emulator.

and is there specific Visual Studio version for build it.

Thanks

**Comment by hrydgard** [comment]
Don't open issues for questions, this place is for bug reporting.

Go to http://forums.ppsspp.org if you want to ask questions.

**Comment by hrydgard** [comment]
Also: https://github.com/hrydgard/ppsspp/wiki/Build-instructions
