### ISSUE TITLE
Artifact in SOCOM U.S. Navy SEALs games

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8973]
Artifact in the middle of the screen,Since https://github.com/hrydgard/ppsspp/pull/8804
SOCOM U.S. Navy SEALs Fireteam Bravo 3
![03](https://cloud.githubusercontent.com/assets/3481559/18422665/50bf3ebc-78d0-11e6-8b1d-8304d05cb368.png)

SOCOM U.S. Navy SEALs Tactical Strike
![04](https://cloud.githubusercontent.com/assets/3481559/18422673/63155e52-78d0-11e6-98e6-819e7bf39dfc.png)

**Comment by unknownbrackets** [comment]
From the log, what FBO is being destroyed when that image goes away?  If you set a breakpoint, is anything else writing to that area of memory before the FBO is destroyed?

We're probably not catching a memcpy/memset.

-[Unknown]

**Comment by daniel229** [comment]
```
28:15:289 idle0        I[SCEGE]: GLES\Framebuffer.cpp:1938 Destroying FBO for 00000000 : 480 x 272 x 1
28:15:300 idle0        I[SCEGE]: GLES\Framebuffer.cpp:1938 Destroying FBO for 00044000 : 480 x 272 x 1
28:15:301 idle0        I[SCEGE]: GLES\Framebuffer.cpp:1938 Destroying FBO for 000cc000 : 128 x 272 x 3
28:15:302 idle0        I[SCEGE]: GLES\Framebuffer.cpp:1938 Destroying FBO for 000dc000 : 128 x 272 x 3
```
Is it this
![05](https://cloud.githubusercontent.com/assets/3481559/18423146/edbd29e6-78d4-11e6-8baf-5e5433f2f33a.png)

**Comment by unknownbrackets** [comment]
That looks like it could be it, yes.  It's doing three lbus and doing some averaging or something?  But it seems to ultimately be clearing the memory.

-[Unknown]

**Comment by daniel229** [comment]
SOCOM U.S. Navy SEALs Tactical Strike does not break.
```
06:35:783 idle0        I[SCEGE]: GLES\Framebuffer.cpp:1938 Destroying FBO for 00000000 : 480 x 272 x 1
06:35:784 idle0        I[SCEGE]: GLES\Framebuffer.cpp:1938 Destroying FBO for 00044000 : 480 x 272 x 1
```

**Comment by unknownbrackets** [comment]
Ah, I guess what's happening is that it draws the frame initially, but then it draws black, and it relies on memory being updated with the black too.

If we did that, we'd bring back the problems #8804 fixed in other games...

But maybe we could explicitly memset when a clear happens.  If you step frame when the original logo is shown, does it ever do a clear (this is just a regular draw, but clear mode is on.)  If so, we could use those to update memory when we first see them too.

-[Unknown]

**Comment by daniel229** [comment]
This noe?
![07](https://cloud.githubusercontent.com/assets/3481559/18423802/e47d4d56-78da-11e6-9b71-80e10a36a76e.png)

**Comment by unknownbrackets** [comment]
Try finding this [in DrawEngineGLES.cpp](https://github.com/hrydgard/ppsspp/blob/92d930887f36a8487da952a89732c5addf5e1b05/GPU/GLES/DrawEngineGLES.cpp#L990-L992):

```c++
			int scissorX2 = gstate.getScissorX2() + 1;
			int scissorY2 = gstate.getScissorY2() + 1;
			framebufferManager_->SetSafeSize(scissorX2, scissorY2);
```

And replace with:

```c++
			int scissorX1 = gstate.getScissorX1();
			int scissorY1 = gstate.getScissorY1();
			int scissorX2 = gstate.getScissorX2() + 1;
			int scissorY2 = gstate.getScissorY2() + 1;
			framebufferManager_->SetSafeSize(scissorX2, scissorY2);

			// If easy, immediately clear the RAM too.
			bool singleByteClear = (clearColor >> 16) == (clearColor && 0xFFFF) && (clearColor >> 24) == (clearColor & 0xFF);
			if (g_Config.bBlockTransferGPU && colorMask && alphaMask && singleByteClear) {
				const int bpp = gstate.FrameBufFormat() == GE_FORMAT_8888 ? 4 : 2;
				const int xoff = scissorX1 * bpp;
				const int xlen = (scissorX2 - scissorX1) * bpp;
				const int stride = gstate.FrameBufStride() * bpp;

				u8 *const addr = Memory::GetPointer(gstate.getFrameBufAddress() + xoff);
				for (int y = scissorY1; y < scissorY2; ++y) {
					memset(addr + y * stride, clearColor, xlen);
				}
			}
```

This is probably not a perfect fix - there are more cases to handle and maybe it could be more efficient, but if this works it might be a good option.  Also, if this breaks other games then an improved version would likely also break other games.

-[Unknown]

**Comment by unknownbrackets** [comment]
Wait, that won't work here actually... but here's a version that should (definitely could be more optimal...)

```c++
			int scissorX1 = gstate.getScissorX1();
			int scissorY1 = gstate.getScissorY1();
			int scissorX2 = gstate.getScissorX2() + 1;
			int scissorY2 = gstate.getScissorY2() + 1;
			framebufferManager_->SetSafeSize(scissorX2, scissorY2);

			// If easy, immediately clear the RAM too.
			if (g_Config.bBlockTransferGPU && colorMask && alphaMask) {
				u8 *addr = Memory::GetPointer(gstate.getFrameBufAddress());
				const bool singleByteClear = (clearColor >> 16) == (clearColor && 0xFFFF) && (clearColor >> 24) == (clearColor & 0xFF);
				if (singleByteClear) {
					const int bpp = gstate.FrameBufFormat() == GE_FORMAT_8888 ? 4 : 2;
					const int xoff = scissorX1 * bpp;
					const int stride = gstate.FrameBufStride() * bpp;
					const int xlen = (scissorX2 - scissorX1) * bpp;
					addr += xoff;
					for (int y = scissorY1; y < scissorY2; ++y) {
						memset(addr + y * stride, clearColor, xlen);
					}
				} else {
					u32 *addr32 = (u32 *)addr;
					const int stride = gstate.FrameBufStride();
					for (int y = scissorY1; y < scissorY2; ++y) {
						for (int x = scissorX1; x < scissorX2; ++x) {
							addr32[y * stride + x] = clearColor;
						}
					}
				}
			}
		}
```

-[Unknown]

**Comment by daniel229** [comment]
I try the second version, still something else on the screen.
![08](https://cloud.githubusercontent.com/assets/3481559/18424590/1202f164-78e4-11e6-98cd-87ce14da5f05.png)

**Comment by unknownbrackets** [comment]
Oops, I'm still wrong.  Try this one (could really make this more optimal...):

```c++
			int scissorX1 = gstate.getScissorX1();
			int scissorY1 = gstate.getScissorY1();
			int scissorX2 = gstate.getScissorX2() + 1;
			int scissorY2 = gstate.getScissorY2() + 1;
			framebufferManager_->SetSafeSize(scissorX2, scissorY2);

			// If easy, immediately clear the RAM too.
			if (g_Config.bBlockTransferGPU && colorMask && alphaMask) {
				u8 *addr = Memory::GetPointer(gstate.getFrameBufAddress());
				const bool singleByteClear = (clearColor >> 16) == (clearColor && 0xFFFF) && (clearColor >> 24) == (clearColor & 0xFF);
				const int bpp = gstate.FrameBufFormat() == GE_FORMAT_8888 ? 4 : 2;
				if (singleByteClear) {
					const int xoff = scissorX1 * bpp;
					const int stride = gstate.FrameBufStride() * bpp;
					const int xlen = (scissorX2 - scissorX1) * bpp;
					addr += xoff;
					for (int y = scissorY1; y < scissorY2; ++y) {
						memset(addr + y * stride, clearColor, xlen);
					}
				} else if (bpp == 4) {
					u32 *addr32 = (u32 *)addr;
					const int stride = gstate.FrameBufStride();
					for (int y = scissorY1; y < scissorY2; ++y) {
						for (int x = scissorX1; x < scissorX2; ++x) {
							addr32[y * stride + x] = clearColor;
						}
					}
				} else if (bpp == 2) {
					u16 *addr32 = (u16 *)addr;
					const int stride = gstate.FrameBufStride();
					for (int y = scissorY1; y < scissorY2; ++y) {
						for (int x = scissorX1; x < scissorX2; ++x) {
							addr32[y * stride + x] = clearColor;
						}
					}
				}
			}
```

-[Unknown]

**Comment by daniel229** [comment]
Look like it's Okay now,same as before missing some framebuffer effect.
![09](https://cloud.githubusercontent.com/assets/3481559/18424952/7e971da2-78e7-11e6-82bd-80dddd4a54c8.png)

**Comment by hrydgard** [comment]
By the way it seems that there's likely something else wrong with SOCOM graphics as people are saying that a framebuffer effect is missing.

**Comment by piau9000** [comment]
The problem still persists, even with the last commit.

Here is a screeshot showing the problem:
![](http://i.imgur.com/qWCzdHy.jpg)

Now, if you press esc and enter ppsspp menu then return to the game, it starts to flicker:
![](http://i.imgur.com/Nl3VX1Z.jpg)

If you look up (to the sky) while it's flickering you can see that there's a ghost image of the screen before the flickering:
![](http://i.imgur.com/I48nAf0.jpg)

Each time you enter the menu and quit the last image on the screen is kinda saved.

**Comment by hrydgard** [comment]
That commit has not been merged though. I'll look into doing that soon.

**Comment by hrydgard** [comment]
I think this has been fixed for some time?
