### ISSUE TITLE
Pursuit Force Crash

### ISSUE THREAD

**Issue by Anuskuss** [hrydgard/ppsspp#8974]
##### So this issue is really weird:

I can play **Pursuit Force** normally on my **Windows 7** and my **iPhone 6**. Then I tried to move the **.iso** on my PC to a **different location**, and it still **runs fine**. But as soon as I **rename** it, it **crashes** right after the **in-game logo**.

I tried to recreate it, but it **didn't happen** again. Also in the past, I tried to **convert** it into a **.cso** for my iPhone, and while testing the result on my PC, it **crashed** at the **same time** again (haven't tested now but I could if it's worth it).

So I don't know what's triggering it, and why it can go in-game, but I noticed another thing: When trying to start the (renamed) game from a **HTTP server**, it again **crashes** on the **same scene** - so I think this might be somewhat related.
##### The log right before the crash

``` log
51:27:546 idle0        W[FileSys]: FileSystems\ISOFileSystem.cpp:515 Reading beyond end of file, clamping size 512000 to 511349
51:27:617 idle0        E[LOAD]: FileLoaders\DiskCachingFileLoader.cpp:473 Unable to read disk cache data entry.
```
##### The log with the normal ISO

``` log
54:38:789 idle0        W[FileSys]: FileSystems\ISOFileSystem.cpp:515 Reading beyond end of file, clamping size 512000 to 511349
54:39:154 user_main    I[IO]: HLE\sceIo.cpp:1022 stdout: c:/Workdir/Game03/Source/MemoryCard_Handler.cpp: ready detected
```

If you need more log messages, I can provide that since these are just guesses from me where the error is.
##### Game Info

**Name:** Pursuit Force
**Game ID:** UCES00019
**CRC32:** E708D084

**Comment by hrydgard** [comment]
Weird. Seems likely that it does have something to do with the game reading off the end of the ISO. Is it a clean dump?

**Comment by Anuskuss** [comment]
It has to be a clean dump since I can play it normally, only when renaming or streaming it crashes.

##### CSO Info log
```log
32:56:908 user_main    I[G3D]: GLES\ShaderManager.cpp:165 Linked shader: vs 13 fs 14
32:56:958 Thread 1     W[FileSys]: FileSystems\ISOFileSystem.cpp:515 Reading beyond end of file, clamping size 512000 to 511349
```

##### CSO Debug log
```log
34:12:392 user_main    D[IO]: HLE\sceIo.cpp:999 sceIoReadAsync(4, 09f9dfc0, 1000): deferring result
34:12:392 user_main    D[IO]: HLE\sceUmd.cpp:317 0x32=sceUmdGetDriveStat()
34:12:392 user_main    D[IO]: HLE\sceIo.cpp:2062 511349 = sceIoWaitAsyncCB(4, 09fff4b0): waiting
34:12:392 idle0        D[KERNEL]: HLE\sceKernelThread.cpp:3032 Context switch: user_main -> idle0 (276->272, pc: 08989470->08000000, io waited) +50us
34:12:392 user_main    D[KERNEL]: HLE\sceKernelThread.cpp:3032 Context switch: idle0 -> user_main (272->276, pc: 08000000->08989470, idle) +83us
```

Also I could reproduce the error when playing the game from an external drive (unrenamed) while the beta (UCET00007) was running just fine.

**Comment by unknownbrackets** [comment]
What do you have your IO timing set to?  Does changing that setting affect whether it crashes?

-[Unknown]

**Comment by Anuskuss** [comment]
Can't recreate this so I hope it's gone.
