### ISSUE TITLE
Ratchet & Clank - Size Matters ( Android )

### ISSUE THREAD

**Issue by Fokusuke** [hrydgard/ppsspp#8976]
When I select "Skip buffer effects" and attack enemies or break the boxes, then there are artifacts. How can I fix it?
[Video]https://www.youtube.com/watch?v=CJ4lDpzSWnI&feature=youtu.be)

**Comment by hrydgard** [comment]
Don't select "Skip buffer effects". It's obviously necessary for some effects to work, the option is there because on some devices the effects are slow and can in many games be lived without.
