### ISSUE TITLE
I can not run ppsspp

### ISSUE THREAD

**Issue by nfjorgebueno** [hrydgard/ppsspp#8979]
from the review ppsspp-v1.2.2-898-g22b6988-windows-amd64, the filter smart screm  prevents me run s ppsspp and it tells me that this application can damage the computer It is strange because ppsspp this virus free  , I have the original Windows 10 64bit,thanks for your attention.I'm sorry I forgot, I download EmuCR-ppsspp-20160912-x64 and I could run without problems

**Comment by unknownbrackets** [comment]
I'm not sure what we can do about such heuristics except hope they fix them?

Does it still happen with the latest git build?

http://buildbot.orphis.net/ppsspp/index.php?m=get&rev=v1.2.2-971-g2adec71&platform=windows-amd64

-[Unknown]

**Comment by nfjorgebueno** [comment]
download ppsspp-v1.2.2-973-g2019542-windows-amd64 and keeps going the same I can not run. download EmuCR-ppsspp-20160915-x64 and works well thanks for your attention

**Comment by vsub** [comment]
Right click on the file=>Properties and see if in General there is a button called Unblock...click on it if there is

**Comment by nfjorgebueno** [comment]
download ppsspp-v1.3 and works well thanks for your attention

**Comment by unknownbrackets** [comment]
Okay, let's hope it was a temporary issue.  Closing.

-[Unknown]
