### ISSUE TITLE
Networking Over VPN Between Android  and Windows PTP problem 

### ISSUE THREAD

**Issue by adenovan** [hrydgard/ppsspp#8983]
i am hosting a proadhocserver and openvpn server a week ago to be alternative for android device to play online the thread can be found here http://forums.ppsspp.org/showthread.php?tid=20437 . but there is a issues specific to android platform with ptp on high latency. the issues did not happen on windows build. pdp send and pdp recv seem to be normal on both build over the internet.

i am test it on local network also but the ip and the traffic tunneled to local openvpn server and it seems the problem is not there with a very low ping. so i assume there is something wrong with the android build when playing over the internet with openvpn. because playing with 2 windows build the issues did not happen.

I am producing the issues using Monster Hunter Freedom Unite game.
Android Taking the quest and windows joins = PTP Listen seems normal and can enter area normally 
Windows Taking the quest and Android joins = broke of on game the ptp closed on windows log.

here is the log picture i can catch. the first ptp listen is windows taking the quest
![screenshot 135](https://cloud.githubusercontent.com/assets/5246143/18562828/fc049f58-7bb7-11e6-8833-50bf27f47ed6.png)
and the second with error log is android taking the quest.

the issues seems happened too while playing between 2 android device. the community trick this issues with 10% alt speed before depart from a quest. so no one desync on the game. after entering game area both build seems to be normally synchronized. 

i can give you access to the server if you want @hrydgard  . the server bill is payed by community on facebook. located on Asia and the purpose is to playing ppsspp online with android and windows device.

**Comment by adenovan** [comment]
Adb logcat info. its seems android fail to connect to windows if windows hosting the quest

windows host = failed 
here is the logcat ptp connect log  a socket error 114 and 115 (operation in progress) 
[windowshost.txt](https://github.com/hrydgard/ppsspp/files/483095/windowshost.txt)

android host = success 
here is the logcat 
[androidhost.txt](https://github.com/hrydgard/ppsspp/files/483096/androidhost.txt)

**Comment by adenovan** [comment]
this issues is temporary fixed by my latest 2 commit on auto toogle branch here https://github.com/adenovan/ppsspp/commits/autotoogle but its dirty and ugly . need clean solution to prevent game spamming ptp connect on linux build and android build. can some dev give me advice ? i am new to github and c++ . previously i am java and web programmer .

**Comment by hrydgard** [comment]
So #9058 is a cleaner fix? Sure looks that way...

**Comment by adenovan** [comment]
yes its cleaner already test it  no need for autotoogle this issues can be closed if that pull request merged

**Comment by hrydgard** [comment]
OK, merged.
