### ISSUE TITLE
SDL2 Controller Database Support

### ISSUE THREAD

**Issue by neilmunday** [hrydgard/ppsspp#8986]
Hi,

SDL2 supports loading control pad (joystick) mappings from a "controller database", see https://github.com/gabomdq/SDL_GameControllerDB which can then be loaded using the SDL_GameControllerAddMappingsFromFile SDL2 function.

I've used this in some of my own projects together with the SDL2 GameController API to make life a lot easier when incorporating control pad support into my SDL2 based apps.

Would it be possble to add such support to PPSSPP?

Thanks,

Neil.

**Comment by unknownbrackets** [comment]
Would you be interested in submitting a pull request?

-[Unknown]

**Comment by neilmunday** [comment]
Sure. I've almost got something working, just need to do some testing with some other models of control pad to be sure. If all goes well I'll create a pull request.

I should add that C/C++ isn't my main language so I apologise in advance!

**Comment by unknownbrackets** [comment]
Sounds great - thanks.  C/C++ isn't my main language either, actually, but that's what code review is for, heh.

As long as non-SDL isn't really changed, I think it can only be better.  This could be related to #7847 and #8849.

-[Unknown]

**Comment by neilmunday** [comment]
Pull requested submitted: https://github.com/hrydgard/ppsspp/pull/8993

I had to update ext/native/base/PCMain.cpp to enabled SDL2's game controller support as well as adding a copy of the game controller database to the assets directory.

Seems to work for me under Linux with PS3 and XBOX 360 control pads.

Let me know what you think.

Cheers,

Neil.

**Comment by neilmunday** [comment]
As the pull request has been merged, this issue can now be closed.
