### ISSUE TITLE
OpenGL ES "lost": Avoid GL calls on shutdown

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#8988]
Seems we still aren't doing everything correctly - apparently once we've lost the context we can't make any further GL calls.

![capture2](https://cloud.githubusercontent.com/assets/130929/18608536/659ad0f6-7cec-11e6-9293-e3664c129d74.JPG)

**Comment by unknownbrackets** [comment]
I think this might be from thin3d / gameinfocache / GPU lost.  At least now the deletes aren't being run during restore and deleting actual things, but yeah it'd be best to clean them up.

-[Unknown]

**Comment by unknownbrackets** [comment]
Is this fixed now with #10366?

-[Unknown]

**Comment by unknownbrackets** [comment]
I think we caught another of these recently - any left?  Should we keep this open?

-[Unknown]
