### ISSUE TITLE
[Android] PPSSPP (build) 1.3 Sound stuttering when connecting to external Bluetooth speaker 

### ISSUE THREAD

**Issue by Isov91** [hrydgard/ppsspp#8989]
So I wanted to try playing with a external speaker JBL FLIP 3 Bluetooth speaker. When I connect it sound starts to Stutter. My game runs without a stuttering but the sound is stuttering with small delays. When disconnecting the speaker the problem goes away. 

What I tried was changing sound latency in audio settings but didn't fix it.

Here's video links for more help. I use God Eater Burst for the example

https://streamable.com/pssn **Without Bluetooth speaker (device speakers)**
https://streamable.com/c5to **with Bluetooth speaker JBL FLIP 3**

Phone:   

Sony Xperia X performance F8131 
Android: 6.0.1 
PPSSPP Version: 1.3

**Comment by hrydgard** [comment]
Most likely the same as #8738, follow that issue please.

The current latency setting is a bit weird, I plan to replace it with a different one that should be usable to solve this issue.
