### ISSUE TITLE
Missing sem.h for Android OSK

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#8995]
My WIP:
https://github.com/sum2012/ppsspp/commit/dd3f4ac50e9baa478a00a2c516f6bba183cf8f34
I take a search that I find out need to use sem to lock thread,
But I am missing it.Anyone help ? Thanks

**Comment by hrydgard** [comment]
You could probably just use our mutex instead. ext/native/base/mutex.h

Make sure to match up your lock/unlock pairs, and only operate on the shared data inside the lock.

That said, I doubt you actually need it here..

**Comment by sum2012** [comment]
![1](https://cloud.githubusercontent.com/assets/2177532/18670388/3893cd32-7f72-11e6-97b6-c778a0710560.png)

Not sure which change make thing bad

**Comment by sum2012** [comment]
Hmm,I do not have that error on fresh source

**Comment by sum2012** [comment]
I still a bit not understand,can you help me ?
In Core\Config.h declare "static recursive_mutex OSKlock;"
Then in Core\Dialog\PSPOskDialog.cpp 
	lock_guard lock(g_Config.OSKlock);
	g_Config.OSKlock.lock();
In the UI\NativeApp.cpp I call g_Config.OSKlock.unlock();
Not sure why compile complain undefined refernce  Config::OSKLock
The new change:
https://github.com/hrydgard/ppsspp/compare/master...sum2012:Android_OSK?expand=1

**Comment by hrydgard** [comment]
static class members need to be declared outside of the class too.

Add the following line somewhere near the top of Config.cpp:

recursive_mutex Config::OSKlock;

**Comment by sum2012** [comment]
I am not sure why need press "input name" after input name to display name.

**Comment by sum2012** [comment]
I tried to use loop check with std::this_thread::sleep_for(500)
but ppsspp hang
