### ISSUE TITLE
Comparison of constant is always true

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#8996]
I afraid our code is something wrong
![2](https://cloud.githubusercontent.com/assets/2177532/18671181/a82cd69a-7f75-11e6-9773-9143f4c8116a.jpg)

![3](https://cloud.githubusercontent.com/assets/2177532/18671184/ad5026cc-7f75-11e6-9173-8dca966d80f4.jpg)

**Comment by hrydgard** [comment]
Yeah, that's not our code though, it's the "glslang" compiler we use for Vulkan to compile GLSL shaders into SPIR-V. I'm going to update to a new version soon, hopefully they've fixed it up.

**Comment by unknownbrackets** [comment]
Does this still happen?  I checked the travis build logs briefly and it seems not to be.

-[Unknown]
