### ISSUE TITLE
Missing Few .h file

### ISSUE THREAD

**Issue by niznet** [hrydgard/ppsspp#8998]
Error: http://pastebin.com/JarUbZiR

Missing file:
1.string.h
2.assert.h
3.corecrt.h
4.crtdbg.h
5.ctype.h
6.stddef.h
7.stdio.h
8.stdlib.h

i already checking with ~ git pull -v --progress "origin" ~
![error](https://cloud.githubusercontent.com/assets/7384923/18700963/4542aeda-8004-11e6-97a5-b2b764c474e8.png)

sorry if my english bad... I still newbie #_#

**Comment by Bigpet** [comment]
Those are C standard headers and one Microsoft C runtime header. This is not an issue with ppsspp those headers are supposed to ship with your compiler.

**Comment by niznet** [comment]
how i fix that?
i already trying add $(UniversalCRT_IncludePath) and $(UniversalCRT_LibraryPath_x64)

**Comment by niznet** [comment]
now fixed with reinstalling visual studio
now i have 1 problem missing files

Cannot open include file: ''ext/tinyformat/tinyformat.h': No such file or directory (compiling source file Directx9\StencilBufferDX9.cpp)

i already checking and it's up to date

**Comment by unknownbrackets** [comment]
You probably ran `git submodule update --init`, but it actually needs to be `git submodule update --init --recursive`.  The tinyformat code is actually a submodule of armips - so it's a "grandchild".

-[Unknown]

**Comment by niznet** [comment]
ah... thx xD
