### ISSUE TITLE
Comic Party Portable hang in first video since v1.2.2-821-geac1848

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#9002]
@unknownbrackets 
hang from commit https://github.com/hrydgard/ppsspp/pull/8867/commits/558b4620e8643ef46c1bf0d45cba5eae75e26860
in #8867 
good log (v1.2.2-815-gef95bb0) : https://gist.github.com/sum2012/80188c347e462e2e1402670eec2db43c
bad log(v1.3-7-g175f331-windows-amd64): https://drive.google.com/file/d/0B3OaSdeV0L8kdmZIQnhmaGhUcWs/view?usp=sharing

keep calling these
34:09:728 user_main    D[ME]: HLE\sceMpeg.cpp:1679 80618001=sceMpegGetAtracAu(099ede60, 00000002, 099edeb0, 09fbf910)
34:09:728 user_main    D[ME]: HLE\sceMpeg.cpp:1539 ERROR_MPEG_NO_DATA=sceMpegGetAvcAu(099ede60, 00000001, 099ede98, 09fbf910)
34:09:728 user_main    D[ME]: HLE\sceMpeg.cpp:1646 ERROR_MPEG_NO_DATA=sceMpegGetAtracAu(099ede60, 00000002, 099edeb0, 09fbf910)
34:09:728 user_main    D[ME]: HLE\sceMpeg.cpp:1539 ERROR_MPEG_NO_DATA=sceMpegGetAvcAu(099ede60, 00000001, 099ede98, 09fbf910)
34:09:728 user_main    D[ME]: HLE\sceMpeg.cpp:1646 ERROR_MPEG_NO_DATA=sceMpegGetAtracAu(099ede60, 00000002, 099edeb0, 09fbf910)

**Comment by sum2012** [comment]
JPCSPTrace log:
https://gist.github.com/sum2012/0067728fe024931214eea14b40029cf0

Real psp keeping return ERROR_MPEG_NO_DATA in sceMpegGetAtracAu  for first video
I cannot log sceMpegAvcDecode  and sceMpegAtracDecode  together because psp would hang.

**Comment by unknownbrackets** [comment]
I think it may be an off-by-one frame issue.  Does #9014 help?

-[Unknown]

**Comment by sum2012** [comment]
Yes fixed
log:https://gist.github.com/sum2012/2e9da0bfd27904782265d8d08095dffb
