### ISSUE TITLE
Gundam Battle Chronicle freeze on mission exit

### ISSUE THREAD

**Issue by DarkD** [hrydgard/ppsspp#9003]
Battle Chronicle freezes **every** time after mission end or exiting to menu from mission. Testing on latest 1.3-7.
That's what I have in console when that happens:

```
39:19:526 user_main    I[SCEGE]: Common\FramebufferCommon.cpp:414 Creating FBO for 00000000 : 480 x 272 x 1
39:19:614 idle0        I[SCEGE]: GLES\Framebuffer.cpp:1922 Decimating FBO for 00044000 (480 x 272 x 1), age 6
39:19:679 idle0        I[SCEGE]: GLES\Framebuffer.cpp:1922 Decimating FBO for 00000000 (480 x 272 x 1), age 6
39:19:915 idle0        I[G3D]: GLES\ShaderManager.cpp:165 Linked shader: vs 43 fs 44
39:19:916 idle0        I[G3D]: GLES\ShaderManager.cpp:165 Linked shader: vs 30 fs 34
39:21:322 idle0        I[G3D]: GLES\ShaderManager.cpp:165 Linked shader: vs 38 fs 14
39:23:351 user_main    W[G3D]: Common\FramebufferCommon.cpp:886 Inter-buffer block transfer 04000000 -> 04044000
39:23:384 user_main    I[HLE]: HLE\scePower.cpp:369 scePowerSetClockFrequency(222,222,111)
39:23:550 user_main    E[G3D]: GPUCommon.cpp:251 sceGeListEnqueue: can't enqueue, stack address 09EEB508 already used
39:23:550 user_main    E[G3D]: GPUCommon.cpp:251 sceGeListEnqueue: can't enqueue, stack address 09EEB508 already used
39:23:869 ATRAC3 play  I[ME]: HLE\sceAtrac.cpp:1671 0=sceAtracReleaseAtracID(0)
39:23:869 ATRAC3 play  I[KERNEL]: HLE\sceKernelThread.cpp:2151 sceKernelExitDeleteThread(0)
```

Issue is not recent, 2 reports with GTS250 are mine http://report.ppsspp.org/game/ULJS00122_1.02 Note that I put 1 star for gameplay only for reason you can't complete missions because of this issue, there's no issues in gameplay itself besides that, but it alone prevents from progressing.
The purpose of second report was in showing those settings on reports with "Perfect" not solving it.

**Comment by daniel229** [comment]
same as https://github.com/hrydgard/ppsspp/issues/7136 ?

**Comment by DarkD** [comment]
Battle Universe freezed on loading mission and it does freeze in default settings, but with settings I have it's not. Forgot what I actually tweaked there to work, will write there after check. This one freezes after trying exiting from in-game to menu.

**Comment by daniel229** [comment]
Set cpu clock to 1000 helps it?

**Comment by DarkD** [comment]
Not here, only to BU, Chronicle still freezes on mission exit.

**Comment by daniel229** [comment]
I think you need a build odler than v1.2.2-946-gad0167c ,try v1.2.2-942-ga8d1091 and set cpu clock to 1000

**Comment by DarkD** [comment]
Reporting - 942 works, 946 freezes and setting cpu clock to 1000 changes nothing in both cases.

**Comment by daniel229** [comment]
Sound like it is same as https://github.com/hrydgard/ppsspp/issues/7136 timing issue related.

**Comment by DarkD** [comment]
I don't know where to write this now, as it's more fitting there, than here, but details are here... So I've tried for BU 942 and 946 - both freezes on mission start without cpu clock set to 1000

**Comment by DarkD** [comment]
Yes, yes, yesssssssssss!
Indeed this works, but I should check and report another ones of this bunch too...
