### ISSUE TITLE
Constant I/O usage in the game info screen

### ISSUE THREAD

**Issue by vsub** [hrydgard/ppsspp#9004]
Since v1.2.2-853-g0924dbf https://github.com/hrydgard/ppsspp/pull/8900
The more saves(not save states)you have,the bigger it will be.

I have 103 and it's around 830kb per second.

**Comment by unknownbrackets** [comment]
Probably it's calling `GetSaveDataDirectories`.  If your OS is not broken and you have at least a tiny bit of free RAM, it should cache this, so it's probably not really causing any performance concerns or even keeping your disk awake.

I guess it might be ideal to save a flag on the info object but it's not really a big deal.

-[Unknown]

**Comment by vsub** [comment]
The os is fine(Win7 x64)and I have plenty of free ram.
Its just that it didn't do that before that rev
