### ISSUE TITLE
Bug?!

### ISSUE THREAD

**Issue by StoneArtz** [hrydgard/ppsspp#9005]
Does anyone know about this kind of bug? It's really annoying me

It's on non-buffered and played on Android ppsspp version 1.3-7-g175f311
The game is Dissidia 012: Duodecim Final Fantasy

![screenshot_2016-09-23-17-33-18](https://cloud.githubusercontent.com/assets/22261916/18782477/4758c68a-81b9-11e6-9b68-df4e9c56e3fc.jpg)

**Comment by StoneArtz** [comment]
For more images...
![screenshot_2016-09-23-20-45-57](https://cloud.githubusercontent.com/assets/22261916/18786277/ad60fcca-81cf-11e6-8300-c57db3451c1a.jpg)

**Comment by unknownbrackets** [comment]
Is this the same as #8906?  I'm guessing you're using the "skip buffer effects" speed hack.

Also, what device are you using?

-[Unknown]

**Comment by StoneArtz** [comment]
I've tried disabling the cheats and it's still the same...
