### ISSUE TITLE
Proposal: Cancel ports to unmaintained platforms

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#9010]
Some ports are holding us back (for example, we can't even use C++11 fully) so I propose that we stop attempting to keep compatibility with mostly-dead platforms and only support platforms with updated compiler toolchains.

That is, we'll keep attempting to support the following platforms, that all have updated compilers:
- Windows
- Android
- Linux/SDL
- Linux/Qt
- iOS (semi-supported)
- Mac/SDL
- (Mac/Qt - does this work?)

While we ditch support for the following:
- Blackberry
- Symbian
- Any others

Users of these platforms can use 1.3 and below as they please, or maintain support separately.

Thoughts? Did I forget any platforms that are currently supported?

**Comment by Orphis** [comment]
👍

**Comment by unknownbrackets** [comment]
We may also want to drop the original Raspberry Pi (not the newest one though for sure)?  I know it had some weird syscalls we had to make like `bcm_init` - I don't mean that we remove those syscalls, but just that we don't officially support it anymore.

Definitely in favor of dropping Symbian etc. at this point - sorry to fans of them.  I think existing releases for those platforms are already pretty good options indeed.

-[Unknown]

**Comment by dolphinmyna** [comment]
how about UWP plan? i don't know if ppsspp could sales on windows store, but nesbox sales for $10 on windows store.

**Comment by hrydgard** [comment]
@dolphinmyna See #8315

**Comment by Orphis** [comment]
Blackberry code removed in #9050 and Symbian one removed in #9051

**Comment by Orphis** [comment]
Maemo removed in #9055

**Comment by zhykzhykzhyk** [comment]
Mac/Qt basically works well (at least on my computer).

**Comment by hrydgard** [comment]
We're done here, the only thing left to drop is Windows XP which there is a separate issue for. That will happen in 1.5, letting us use the latest Windows SDKs instead of being stuck at 8.
