### ISSUE TITLE
Rendering issue in Spongebob Yellow Avenger 

### ISSUE THREAD

**Issue by RinMaru** [hrydgard/ppsspp#9018]
once in game the 2.5D sections render weirdly but the 3D sections (inside houses) work perfectly
![ules00280_00000](https://cloud.githubusercontent.com/assets/15071652/18835155/b0f14ab2-83c7-11e6-82c4-c91b4dfdaada.jpg)

**Comment by unknownbrackets** [comment]
Did this ever used to work?  Is this with default settings?

-[Unknown]

**Comment by Zetchzie** [comment]
yea default settings. ive tried other settings but no dice. Im not sure if this ever worked.

**Comment by unknownbrackets** [comment]
Reports say it used to work in v1.2.2 with default settings:

http://report.ppsspp.org/game/ULES00280_1.01

Can you try that version?  If it worked then, what's the first git build that stopped working and the last git build that still works?

If v1.2.2 also doesn't work, maybe this has to do with your video card.  What device are you using?  Which backend?  Driver / OS version?

-[Unknown]

**Comment by Zetchzie** [comment]
Windows 10 x64 Home Anniversary Update 
Intel HD 3000

**Comment by kuwoh** [comment]
are you using opengl or direct3d

**Comment by Zetchzie** [comment]
@kuwoh  Both backends have the issue

**Comment by unknownbrackets** [comment]
There's a very good chance this is broken on Intel devices, if other people are seeing it working.

https://github.com/hrydgard/ppsspp/wiki/How-to-find-a-graphic-issue-with-the-GE-debugger

Can you try to find any area when the game suddenly draws gray?  This means going through the draws twice: first, step through to see when it draws gray, then hit "Step Frame" and step through again - but stop just before it's about to draw the gray part.  If you can post the GE debugger data here, it might help.

-[Unknown]

**Comment by Zetchzie** [comment]
![capture](https://cloud.githubusercontent.com/assets/15071652/19011692/2a52f20a-876c-11e6-81ce-39c2bf453bba.PNG)
Im not good at this sort of thing

**Comment by Zetchzie** [comment]
everything works fine inside buildings

![ules00280_00001](https://cloud.githubusercontent.com/assets/15071652/19011723/01083e86-876d-11e6-95d4-2fff9a2d5e39.jpg)

**Comment by benderscruffy** [comment]
PPSSPP v1.5.4-997-g3472d62ff Windows 64 bit
still the same problem

**Comment by unknownbrackets** [comment]
Could you try exporting a GE debugger dump on PC?

To do this, open the game and select Debug -> GE debugger..., then when it's displaying the scene, press Record in the top right.  After a second or so, it'll finish and save a trace of the drawing activity.

After that, check the memstick/PSP/SYSTEM/DUMP folder and it'll have created a file named something like "ULES12345_0000.ppdmp".  You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by RinMaru** [comment]
![ules00280_00002](https://user-images.githubusercontent.com/15071652/45003377-ecb19a00-afaf-11e8-80cc-68d52bcd78d3.jpg)
[ULES00280_0001.zip](https://github.com/hrydgard/ppsspp/files/2346691/ULES00280_0001.zip)

**Comment by Panderner** [comment]
Hmm this bug is existed in latest versions of PPSSPP.
![Screenshot_2020-01-09-20-27-24-61_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/72067816-a8aa7400-331e-11ea-8a84-dd205a54e217.png)

**Comment by Panderner** [comment]
Here's a footage on a real PSP:
![Screenshot_2020-03-22-21-47-47-41](https://user-images.githubusercontent.com/37503397/77251042-f0d30480-6c86-11ea-8f8d-a8f09f0e6686.png)

**Comment by Panderner** [comment]
This how it's looks in software renderer:
![Screenshot_2020-03-24-12-20-42-35_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/77388043-013fc800-6dca-11ea-99f2-1172a17da0ed.png)

**Comment by Panderner** [comment]
v1.10.3-1375-g52c6169a5 Still happens:

OpenGL:
![Screenshot_2020-12-23-20-14-44-977_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/102995334-c8e93800-455b-11eb-9ca8-1ae0e44e64a5.jpg)

Vulkan:
![Screenshot_2020-12-23-20-15-03-396_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/102995381-e0282580-455b-11eb-9cb3-68dc368b631f.jpg)

**Comment by Panderner** [comment]
Direct3D 11:
![Screenshot (2)](https://user-images.githubusercontent.com/37503397/112570424-fc6c8480-8e20-11eb-997b-5b8e161a5f35.png)

Direct3D 9:
![Screenshot (3)](https://user-images.githubusercontent.com/37503397/112570476-1312db80-8e21-11eb-806e-84a6b4a0c4aa.png)

I tested vulkan on windows but it crashes when i go outside:
![Screenshot (1)](https://user-images.githubusercontent.com/37503397/112570620-58cfa400-8e21-11eb-9f9a-4f6dca125de6.png)

**Comment by hrydgard** [comment]
Those logs look like from some previous savedata-related crash? Anyway, logs are not going to help debug this one...

**Comment by Gamemulatorer** [comment]
Can't enjoy playing this with a blackscreen as a background using openGL but the issue in Vulkan makes this game unplayable on my phone :(

**Comment by hrydgard** [comment]
I'm just saying you don't need to post logs of this game. It's a complicated rendering issue.

**Comment by Gamemulatorer** [comment]
I notice that tantalus media games on ppsspp is problematic on graphics 😅
https://www.tantalus.com.au/games_psp.html
https://github.com/hrydgard/ppsspp/issues/9850
https://github.com/hrydgard/ppsspp/issues/9604
https://github.com/hrydgard/ppsspp/issues/13846

**Comment by Gamemulatorer** [comment]
Vulkan issue on this game started in v1.8.0
![Screenshot_2021-09-03-11-28-14-412_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/131946347-0277d0b5-7204-43a2-9de3-7fa4a68463e3.jpg)
Using v1.7.1 Vulkan
![Screenshot_2021-09-03-11-26-46-499_org ppsspp ppssppgold](https://user-images.githubusercontent.com/37603562/131946393-3ccfc21c-f16e-4fda-96ba-6c87c27eb112.jpg)
Disable Stencil Test ON
![Screenshot_2021-09-03-11-27-43-160_org ppsspp ppssppgold](https://user-images.githubusercontent.com/37603562/131946437-58bc7d90-255b-4170-ad61-318ec970cc8d.jpg)

**Comment by XLabProductions** [comment]
Has this been fixed already?

**Comment by Unknowncat1991** [comment]
> Has this been fixed already?

Yes, probably.

**Comment by hrydgard** [comment]
This is fixed since a long time.

**Comment by XLabProductions** [comment]
Ah, I just figured it out hghg. My bad,
