### ISSUE TITLE
Can't Ed some buttons( android )

### ISSUE THREAD

**Issue by Juliex** [hrydgard/ppsspp#9022]
Can't move/resize the combo keys,start,select,unthrottle buttons when they are in action buttons area (lower right of screen)
When action buttons are unvisible or visible,
And in select , start n unthrottle area lower center of screen.

**Comment by unknownbrackets** [comment]
What device is this on?  Is this happening on the latest git build, and has it always happened - or is it only happening in recent versions?

-[Unknown]

**Comment by Juliex** [comment]
In recent versions it occurred,
but in 1.3.37,it is a lot better and they can move if u press the screen repeatedly and multiple touch them very fast.

OK,its good.
