### ISSUE TITLE
Android: Project Diva Crash

### ISSUE THREAD

**Issue by Juliex** [hrydgard/ppsspp#9023]
In Project Diva,When i pause the game,where the save states are, more times it takes several seconds to pause,and, when I quit the settings,Always it takes several seconds to return to pause screen,n it will freeze 99% times after return to pause.a _not responding_error also appears,and cant do anything Until i quit ppsspp.

I almost forgot about it that the possibility of crashing when immersive mode is on is very higher than when softkeys are visible and resolution is locked on 1184x720(1192x720 in older versions).

**Comment by unknownbrackets** [comment]
What device is this on?  Are you using 1.3, and does it happen with the latest git build (not very far from 1.3 yet)?

Are you streaming the game over the network, or is it on your device?

-[Unknown]

**Comment by Juliex** [comment]
Oh...unfortunately,this problem is for all games... My is 1.3.37 g8b5693b

This problem was from first to last(version).

Device is p8 Lite.
No network connection, also,can't use ad hoc in Gran turismo and hatsune n another...(can't connect to coldbird...
Never mind.better close.
If didn't find any fix for it,i will open another issue.

**Comment by unknownbrackets** [comment]
Does it work if you go back to v1.2.2 on the download page?  Or do you mean it's always happened in every version on your device?

-[Unknown]

**Comment by Juliex** [comment]
fixed in build 146 
tnx.
