### ISSUE TITLE
Build Android: Can't Find "native"

### ISSUE THREAD

**Issue by niznet** [hrydgard/ppsspp#9028]
build android with Eclipse, got this error
i already imported native folder to eclipse (Existing Project into Workspace)

09:34:08 **** Incremental Build of configuration armv7profiler for project ppsspp ****
"D:\\Tools\\Android\\SDK\\android-ndk-r12b\\ndk-build\\ndk-build.cmd" ANDROID_NDK_PROFILER=1 TARGET_PLATFORM=android-9 NDK_DEBUG=0 APP_ABI=armeabi-v7a -j5 
Android NDK: ..\ext\native\ext/libzip/Android.mk: Cannot find module with tag 'native' in import path    
jni/Android.mk:527: *** Android NDK: Aborting.    .  Stop.
Android NDK: Are you sure your NDK_MODULE_PATH variable is properly defined ?    
Android NDK: The following directories were searched:    
Android NDK:         

09:34:13 Build Finished (took 5s.373ms)

**Comment by unknownbrackets** [comment]
You need to have the NDK_MODULE_PATH set.  It may be easier to just use `ab.cmd` or use `ant`.

-[Unknown]

**Comment by niznet** [comment]
still same error.

**Comment by niznet** [comment]
the problem is build configuration, my brother changed it
Sorry for my mistake.

**Comment by fzx19910714** [comment]
Hello, I have a same problem, could you tell me his solution?

**Comment by hrydgard** [comment]
@fzx19910714  did you follow the build instructions and cloned with --recursive?

**Comment by fzx19910714** [comment]
yes ,I have imported to the local project, but compile jni folder when prompted:

"D:\Tools\Android\SDK\android-ndk-r12b\ndk-build\ndk-build.cmd" ANDROID_NDK_PROFILER=1 TARGET_PLATFORM=android-9 NDK_DEBUG=0 APP_ABI=armeabi-v7a -j5
Android NDK: ..\ext\native\ext/libzip/Android.mk: Cannot find module with tag 'native' in import path
jni/Android.mk:527: *** Android NDK: Aborting. . Stop.
Android NDK: Are you sure your NDK_MODULE_PATH variable is properly defined ?
Android NDK: The following directories were searched:
Android NDK:

I can't solve this problem,

**Comment by xiushudongfang** [comment]
I think you should update submodule.

**Comment by fzx19910714** [comment]
@xiushudongfang   you have QQ or wechat?

**Comment by xiushudongfang** [comment]
yeah,you can find it in my host.

**Comment by 846524417** [comment]
@fzx19910714  加我QQ846524417
