### ISSUE TITLE
How to edit games Textures?

### ISSUE THREAD

**Issue by Juliex** [hrydgard/ppsspp#9029]
What are the following:
.
*save new textures*
*Replace textures*
.
 options for?

Is them for export textures in
.../PSP/TEXTURES/game-id/new

then replace those exported textures with built-in game textures?

**Comment by tywald** [comment]
This is more appropriate to ask in the forums.

**Comment by unknownbrackets** [comment]
See here:

http://forums.ppsspp.org/showthread.php?tid=18963

-[Unknown]
