### ISSUE TITLE
ppsspp1.3 hangs on rom selection/loading on ios7.0.6 

### ISSUE THREAD

**Issue by dilmish** [hrydgard/ppsspp#9036]
after updating from 1.2.2-163-g6831f6f to 1.3, ppsspp 1.3 no longer load most iso/roms on my jailbroken ipad2 ios 7.0.6. the only thing it was able to load is monster hunter portable 3rd HD and its even slower than 1.2.2, most games will be stuck on iso/rom loading and makes the device hang and requires hard reset. i want to reinstall the 1.2.2-163-g6831f6f version(or any 1.2.2 with combo buttons untill the bug on 1.3 is fixed) but could not find a 1.2.2 .deb or ipa for ios version.

**Comment by Theo1996** [comment]
me too.

**Comment by unknownbrackets** [comment]
Is this working now in the latest version?

-[Unknown]

**Comment by hrydgard** [comment]
Do we even support iOS 7? I don't think so...

**Comment by unknownbrackets** [comment]
Oh, right, we don't.

-[Unknown]
