### ISSUE TITLE
Totori no Atelier Plus - Arland no Renkinjutsushi 2 - Official PlayView blank screen but music plays

### ISSUE THREAD

**Issue by benderscruffy** [hrydgard/ppsspp#9049]
when you load the game
just comes up with the message
no game data is found
install the game data
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/521970/ppsspplog.zip)

**Comment by benderscruffy** [comment]
stupid me put it in the wrong directory

**Comment by benderscruffy** [comment]
from the menu onwards nothing but a blank screen but the music plays
UNIMPL sceJpegDecodeMJpeg
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/523554/ppsspplog.zip)

**Comment by unknownbrackets** [comment]
This is a duplicate of #1504, all "PlayView" apps have the same problem.

-[Unknown]

**Comment by benderscruffy** [comment]
ok
