### ISSUE TITLE
como descargar

### ISSUE THREAD

**Issue by rasta13** [hrydgard/ppsspp#9062]
Con una molestia, de mi parte. ¿Como puedo descargar el juego???

**Comment by mrcmunir** [comment]
Please we no support piracy/warez read the ppsspp rules 

Don't ask for warez/where to download games or post links to them!

http://forums.ppsspp.org/announcements.php?aid=5

Por favor no apoyamos la pirateria lea las normas de ppsspp antes de postear gracias.
