### ISSUE TITLE
How to import it in Android Studio?

### ISSUE THREAD

**Issue by AntiSaby47** [hrydgard/ppsspp#9064]
is there a way to import it in Android Studio ?

**Comment by hrydgard** [comment]
Hopefully soon, working on it: #9038

**Comment by unknownbrackets** [comment]
This is working now, right?

-[Unknown]

**Comment by abdessamad911** [comment]
Any one has the Android studio version please ?
I tried to import it to studio from eclipse , but it keeps saying
----------------------------------------------------- 
A problem occurred evaluating root project 'android'.
> Plugin with id 'com.android.application' not found.
------------------------------------------------------
Any help ? Thank you

**Comment by hrydgard** [comment]
What? Eclipse hasn't been supported for a long time.

Follow the [build instructions](https://github.com/hrydgard/ppsspp/wiki/Build-instructions) - just clone recursively and then open the folder in Android Studio - then wait for it to get ready. Make sure to choose a good build config such as NormalOptimized.

**Comment by abdessamad911** [comment]
i did it, but now when i test it on my phone, the app says

>the native part of ppsspp for abi armeabi-v7a is missing,
> try downloading an official build?

what's the problem with it ?

**Comment by hrydgard** [comment]
If you're using Android Studio 2.3 in the configuration window, you need to also choose the right ABI. Fro example (If I remember correctly) NormalOptimizedArm instead of Arm64 or x86 or whatever.
