### ISSUE TITLE
Car Jack Streets blank white screen

### ISSUE THREAD

**Issue by benderscruffy** [hrydgard/ppsspp#9065]
after you start a new game the screen goes white but the music still plays

**Comment by daniel229** [comment]
Looks fine on the latest build v1.3-450-g052660b .
![03](https://cloud.githubusercontent.com/assets/3481559/22468939/42c00ce8-e805-11e6-8f83-2cc7b4d419db.png)

**Comment by hrydgard** [comment]
Thanks for testing! Since the original report was without detail (like device etc), I'll consider it solved until further reports.
