### ISSUE TITLE
iOS JIT related crashes

### ISSUE THREAD

**Issue by DarrenBranford** [hrydgard/ppsspp#9069]
Hi all.

I have experienced crashes on iOS that appear to be unique to that platform (they don't happen on Windows).

Outrun: When the stage is about to change (when you approach the junction) PPSSPP will crash
Pursuit Force: Once a mission is loaded and you are prompted to press start, doing so will trigger the crash.

While debugging the issue in xCode, both examples appear to be the same issue.

My devices are Jailed iOS 10.0.2

![x](https://cloud.githubusercontent.com/assets/5956037/19387481/60a533a8-9212-11e6-88b6-ef9728116d04.jpeg)

**Comment by hrydgard** [comment]
Sorry for the close, wrong button. 

Thanks for the report. That it would have something to do with the vertex decoder jit makes sense, maybe we're having it use some register that's only reserved on iOS.

Do you know if you're running an ARM32 or ARM64 build? Looks a little bit like the 32-bit, from the pointers in the various debugger views.

**Comment by DarrenBranford** [comment]
Yes, I am running a 32-bit build. I actually get a couple of buildtime errors when I try to build with arm64.

> /Projects/ppsspp/ext/native/base/basictypes.h:55:94: Invalid output constraint '=l' in asm

> /Projects/ppsspp/ext/native/base/basictypes.h:56:68: Invalid output constraint '=l' in asm

If I can figure that out, I will try to reproduce the issue on an arm64 build.

**Comment by unknownbrackets** [comment]
I think we don't build ffmpeg for arm64/iOS.  AFAIK no one has ported ppsspp to iOS arm64 yet.

For the `jitted_` crash - what is the value of `jitted_` from the debugger?  It should be a function pointer, but the stack trace looks suspicious - is it `0x0ff00010` (or whichever bad address it reports), or is the value of `jitted_` different?

If it's the same, that means it's not even able to initially run the jitted code.  If it's different, it means it's crashing in the middle of running jitted code.

Also, if it is different - could you try setting a breakpoint on that line?  Just click the line number, and run.  Then select Step Into (should be in a Debug menu somewhere), and see where it takes you.  I'm curious to know if it runs any jit.

Also, as a short-term workaround you can change "VertexDecJit" in ppsspp.ini to False.  Or, equivalently (I don't know how easy it is to edit the ini on iOS) you can remove these lines:
https://github.com/hrydgard/ppsspp/blob/20195424965ff1ba3da4237876bcea2c43982151/GPU/Common/VertexDecoderCommon.cpp#L1312-L1317

It'll be slower but it'll skip the vertex jit entirely.

-[Unknown]

**Comment by DarrenBranford** [comment]
OK. So setting a breakpoint suspends the game as soon as it launches.

`jitted_` , in this instance, has a value of `0x0f468010`. Step into takes me to `DrawEngineGLES::DecodeVertsStep()`

![z](https://cloud.githubusercontent.com/assets/5956037/19438926/004747e4-9474-11e6-99a1-5047bb635d6a.jpeg)

**Comment by unknownbrackets** [comment]
I think that means that, sometimes, it jits fine.  Since that value also ended with `010`, it seems less suspicious.

Maybe these games are using a vertex type that by accident uses a register in a way not allowed on iOS.  Ugh.

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, I think that's probably the most likely explanation. One thing I know is different is that we can't use r9 on iOS while we can on all other platforms, maybe we accidentally do so in the vertex jit..

**Comment by hrydgard** [comment]
These particular crashes are fixed, I believe.
