### ISSUE TITLE
Android: CPU problems in update.

### ISSUE THREAD

**Issue by Juliex** [hrydgard/ppsspp#9084]
I have updated my 1.3.47 to 1.3.121   .
In system information/Device info/CPU informations ,
It only detected 1 core on my device after update.
Also, it didn't show CPU name(Unknown)

There are problems with multithreading,Before, it have 7/7 FPS(when it detected 8 cores on device),but now it is between 3/3 ~ 1/1(when it says 1 core).
Also it have a 0.5 frame skiping (a thing between 0 and 1 frame skip),while high range area is running.

**Comment by Orphis** [comment]
What phone do you have?

**Comment by mrcmunir** [comment]
Yeah In my phone too it's Armeabi-v7a  not sure if happen on x86/x86-64 or armv8 devices too 

CPU INFORMATION 
Name Unknown 
Cores 1 

Also No detected correct CPU extension Missing a lot extensions i.e Neon . VFPU version if 3 , 4 etc).

**Comment by Orphis** [comment]
I have an idea. I separated the Android and Linux platforms and some code would not be enabled anymore. But Android is a Linux, so that code path should be working.
Trying a local build and pushing a fix once I confirm a fix!

**Comment by Orphis** [comment]
New build on the way with a potential fix. Check the buildbot in 20 minutes!

**Comment by mrcmunir** [comment]
@Orphis thanks https://github.com/hrydgard/ppsspp/pull/9085 CPU info detected correct now.

**Comment by Orphis** [comment]
Great, thanks for reporting!
