### ISSUE TITLE
Growlanser: The letter 'f' renders as 'y'.

### ISSUE THREAD

**Issue by orbea** [hrydgard/ppsspp#9093]
OS: `Slackware64-current`
`ppsspp-2016.10.24_dba95bd_master-x86_64-1_git`

In the game game Growlanser Wayfarer of Time during the opening scene after starting a game the letter `f` will render as `y`. Is there anything that can be done to correct this?

Example:
![1](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/2016-10-24-114234_1680x1050_scrot.png)

**Comment by LunaMoo** [comment]
This game(among quite a few others) uses psp system fonts and will not look correctly without it. To fix it, you have to dump original PSP fonts and place them inside flash0\font replacing the free fonts that PPSSPP comes with.

 We have ongoing issue about it ~ #2788 so I'm closing this as duplicate.

  Unfortunately as of now there are no free fonts which would work without glitches in every game and the original fonts are copyrighted, so no fix exists for people without PSP.

**Comment by orbea** [comment]
Okay, thanks for the explanation. I made this issue because this has improved in Growlanser since I last saw it.
