### ISSUE TITLE
Android Send Message OSK Bug

### ISSUE THREAD

**Issue by adenovan** [hrydgard/ppsspp#9095]
Send empty string message from android will cause force close , happened on change nickname and pro adhocserver also.

the culprit is this line , the chatscreen OSK also affected by this issues, i guess we re acessing empty vector on inputboxValue[1] or inputboxValue[1] is not created by split string function.

https://github.com/hrydgard/ppsspp/blob/master/UI/NativeApp.cpp#L768

someone have a quick fix?

**Comment by xiushudongfang** [comment]
It dosen't crash on old build .

**Comment by adenovan** [comment]
its crashed when first time opened only and the input is empty string > how to produce easily on android, open ppsspp > change nickname >delete all the value from OSK >send > and crash 

open ppsspp > change nikcname > send > change nickname > delete all string > send > not crash, if the first time input from send message is not empty the next input with empty string didn't crash it.

**Comment by hrydgard** [comment]
Easy fix.
