### ISSUE TITLE
Ppsspp opening bug 

### ISSUE THREAD

**Issue by kevin0070** [hrydgard/ppsspp#9097]
Hi whenever I try to open ppsspp a black screen appears and I can't do anything else on my phone I need to hard reset it. The it will open again but if I kill the app and try reopen it. It does the same thing so I always need to hard reset to play.

**Comment by sum2012** [comment]
Try newest version in
http://buildbot.orphis.net/ppsspp/

**Comment by hrydgard** [comment]
Any luck trying the latest builds @kevin0070  ?

**Comment by hrydgard** [comment]
Closing due to no response.
