### ISSUE TITLE
ppsspp v1.4

### ISSUE THREAD

**Issue by moura464** [hrydgard/ppsspp#9098]
![asdwweqeq](https://cloud.githubusercontent.com/assets/22099440/19787815/8572911e-9c83-11e6-93f7-3b206685f316.png)

**Comment by unknownbrackets** [comment]
Expect the release of version 1.4 sometime between 2012 and 2042.  Unless Nostradamus was wrong...

-[Unknown]

**Comment by moura464** [comment]
![asww](https://cloud.githubusercontent.com/assets/22099440/20246997/b707ca2c-a9a9-11e6-9d38-434c5c678bd1.png)

**Comment by Orphis** [comment]
Stop this.
