### ISSUE TITLE
ppsspp now is only in English

### ISSUE THREAD

**Issue by itornukem64** [hrydgard/ppsspp#9103]
The app is Now only in English and when I try to change the languaje it does not show the others languajes.

**Comment by sum2012** [comment]
Yes,lang directory has changed to assets\lang .The buildbot only fixed windows build.
The Android build still not fixed.

**Comment by hrydgard** [comment]
Right, I found that the issue was the script on the buildbot not being updated. We should really move that script into the repo, but for now I've fixed it. Next build will be ok.

**Comment by sum2012** [comment]
@hrydgard Since v1.3-140-g547b362 , the buildbot of Android broke

**Comment by sum2012** [comment]
Thanks @hrydgard fixed
