### ISSUE TITLE
Building against system ffmpeg with CMake

### ISSUE THREAD

**Issue by akien-mga** [hrydgard/ppsspp#9105]
Hi there,

I'm looking at updating my (ppsspp package for Mageia](http://madb.mageia.org/package/show/name/ppsspp/release/cauldron), but I noticed that version 1.3 has no qmake buildsystem anymore. It was however the only one which exposed a way to build against the system-wide ffmpeg libraries AFAIK (there are still [traces of it in b.sh](https://github.com/hrydgard/ppsspp/blob/master/b.sh#L30-L32)).

Is there a way to get the same behaviour with the CMake buildsystem, and if not, could it be added?

**Comment by Orphis** [comment]
I'm actually working on fixing it right now. Stay tuned!

**Comment by unknownbrackets** [comment]
I was always under the (perhaps very mistaken?) impression that this did something:

https://github.com/hrydgard/ppsspp/blob/master/CMakeLists.txt#L78

-[Unknown]

**Comment by akien-mga** [comment]
> I was always under the (perhaps very mistaken?) impression that this did something:
> 
> https://github.com/hrydgard/ppsspp/blob/master/CMakeLists.txt#L78

I'll give it a try asap :)

**Comment by akien-mga** [comment]
The CMake `USE_SYSTEM_FFMPEG` option seems to work fine, so this is a non-issue, sorry :)

Side question: which frontend is the recommended one for desktop Linux? Qt5 or SDL2?
