### ISSUE TITLE
Parsing version on release (static) tarballs

### ISSUE THREAD

**Issue by akien-mga** [hrydgard/ppsspp#9106]
Building PPSSPP for a Linux distro, I'm using a static tarball of the v1.3 tag. It seems that the versioning system has been changed to rely on git (`git_-version.cpp`), but since such a tarball contains no `.git` folder, it fails and I end up with an `unknown` version instead of `1.3`.

From a quick look I haven't seen an option that would allow to default to a "stable release" versioning system, but I might have just missed it.

**Comment by moura464** [comment]
Building PPSSPP V1.4

**Comment by hrydgard** [comment]
you can modify git-version.cpp (after it's been generated) to force it to stay at a version:

https://github.com/hrydgard/ppsspp/blob/master/git-version.cmake#L37

**Comment by akien-mga** [comment]
Well of course it works, but I don't believe it should be the task of the packager to patch generated files to define the version upstream chose themselves in their git tag/release announcement :)

But it's indeed simple enough to do, so if there's no wish to improve the upstream buildsystem, it can indeed be closed as wontfix.

**Comment by hrydgard** [comment]
Well, if you have a suggestion for how you think it should be done, I'm all ears.

**Comment by akien-mga** [comment]
Well it mostly depends how you want to version your project. As I understand it, the new system simply uses the git commit hash as version string, so there is no longer a stable "PPSSPP v1.3", but only a version 6d0d36b.

So the real question is whether you want to stick to this system, or reintroduce a way to have stable (tagged) versions labelled as such. For the latter, you'd need to hardcode a version string somewhere.

What many open source projects do is that they have a hardcoded version string (that get bumped for new releases), and they add to it the commit hash *when* built from a git repo, so:
- static tarball: `PPSSPP_GIT_VERSION = "v1.3 (stable)"`
- built from git: `PPSSPP_GIT_VERSION = "v1.3 (git - 6d0d36b)"` or `PPSSPP_GIT_VERSION = "v1.3-dev (6d0d36b)"` (or whatever formatting you like best).

There are many possibilities, and as I'm not a ppsspp developer, I won't pretend that I have the best solution to propose. If you do decide to readd a version number, then the changes to be made in the CMake buildsystem are relatively trivial (basically concatenate the relevant info based on conditional checks of the availability of git and a `.git` folder).

**Comment by unknownbrackets** [comment]
Why use a tarball?

If you use git, you'll get a cryptographic hash that verifies the release, and git will automatically verify the files downloaded properly with the same cryptographic hashes.  If there's a disk failure, it'll be detected.  Moreover, you'll get the version string generated exactly the way you want, and also get submodules.

Or, you can use tarballs.  Disk failures and hacking/MITM won't be easily detected, nothing is verified, and you have to manually patch the git-version.cpp.  You also need to manually download the right versions of the submodules yourself.

Note that the tarball is just automatically generated by GitHub, and the specifics of how it is generated are opaque: we have no control over it.

Having a file that is always dirty in the tree after build is a smelly and bad practice, not something to imitate.  Is there even a good reason to use a tarball, though?

-[Unknown]

**Comment by akien-mga** [comment]
Distro packaging (at least RPM and DEB) happens with tarballs. It allows to ensure reproducible builds and availability of the source (the tarball is uploaded to distro repos), which you can't guarantee if you have to clone a git repo which might disappear tomorrow. There are many (older) projects for which you can only find the source in distro repositories nowadays. To guarantee reproducible builds and proper licensing, distro packaging is even done usually without access to the network, to prevent buildsystems from downloading third party binaries.

I'm not sure what you are talking about regarding a file being dirty after each build, as I did not propose that. Your current `git-version.cpp` is also always dirty after each build, no? I'm just proposing thingns that match your current system.

What I proposed is:
- Have the "static" version information somewhere, e.g.:
```
// version.txt
1.3
```
Or something more complex if you want to be able to do some advanced parsing of the version string, e.g. major/minor/patch, etc. You can also have it in the CMakeLists.txt instead like many projects do, and use it to manually update the files from 6d0d36b, thus reducing hardcoding (one place vs three).
- Keep your existing logic, but modify it to generate a `PPSSPP_GIT_VERSION` that contains both the static version and the commit hash (when it can be parsed), or only the static version if the commit hash can't be parsed.

**Comment by akien-mga** [comment]
Also a tarball is arguably smaller and faster to download and deploy than cloning at git repo with 20k commits. And no, limiting the depth is not an option as I'd then need to checkout the tag I want to package, so I can't just clone with `--depth=1`.

**Comment by unknownbrackets** [comment]
If you're generating the tarball from git, why not also generate the git-version.cpp from git?

-[Unknown]

**Comment by akien-mga** [comment]
Because my whole point is that, IMO, it's upstream's job to define their version in a way that makes it work when packaged in distributions. Now, if you don't think it's important, it's fine, I can patch it myself. Or just do nothing and let people enjoy ppsspp version `unknown` in Mageia, but I believe the bug reports you would get from our users would not be very helpful.

**Comment by akien-mga** [comment]
I can do anything, patch the buildsystem to generate the proper version, or fix the generated file with sed, it's not the problem. But the above discussion shows that you don't think it important to properly define your program's version, and that's ok, which is why this issue is closed as *wontfix*.

**Comment by hrydgard** [comment]
@akien-mga , don't assume that, it's just really us not being very used to dealing with package management and its demands.

Previously, I think we did create build numbers that looked like 1.2-abcdef . Not sure what changed it...

**Comment by unknownbrackets** [comment]
We just use `git describe`, which uses git tags.  As long as you have the tag for v1.2, the it will generate "v1.2" or "v1.2-1-g123456" as the case may be.  That's what's expected.  You can run `android/git-version-gen.sh` to generate it (this works for all platforms except Windows, but does expect bash.)

I'm just suggesting that if a tarball needs to be assembled, this seems like part of the tarball creation.  The information is in git (just like which versions of submodules we use), and so at whatever step you remove git from the process, that's the right step to hardcode the version in `git-version.cpp`.

Other alternatives result in:
 * All dev builds becoming "v1.2-dev" with no information about what build they are for the reporting server or end users.
 * Committing an updated git-version.cpp with every single commit, so that it "works" for dev builds (the merge conflicts will be frightening.)
 * Having a tracked file that's modified all the time but only committed sometimes / automatically updated by a bot, and causes frequent local conflicts.

None of these alternatives are desirable.  Whenever git is transformed to a `.git`-less tarball, `git-version-gen.sh` needs to be run.  Compiling will run this automatically for you (assuming you have git installed and a `.git` dir), but it can be run without compiling.

-[Unknown]

**Comment by Orphis** [comment]
I think the easiest solution is to have a checked in version, as in "1.3.1". Releasing is quite rare, so pushing an extra commit to bump this shouldn't be too bad.
If we can get more information from git, then great, let's have that too but it shouldn't be mandatory or show some "unknown". Missing information would be implied as tarball build (probably).
