### ISSUE TITLE
Akaya Akashiya Ayakashi UMD switch not possible 

### ISSUE THREAD

**Issue by kurasamesusaya** [hrydgard/ppsspp#9110]
I've been playing the game "Akaya Akashiya Ayakashi no" which requires a UMD switch halfway through the game. At the end of Disc 1 the game asks you to change the UMD while it's running. So I pause the emulation, Switch the UMD and resume, but nothing happens.

**Comment by sum2012** [comment]
Cam you zip the save folder, then upload the file to http://drive.google.com ?

**Comment by kurasamesusaya** [comment]
Here it is: https://drive.google.com/file/d/0B8JHSXbyKsXwendGTU9PcU54SzA/view?usp=sharing

**Comment by sum2012** [comment]
@unknownbrackets notice this in log: HLE\sceKernelThread.cpp:3479 __KernelNotifyCallback - invalid callback 00000000
info log: https://gist.github.com/sum2012/b0feabd47c7e3d39fcc5aa516be5da09
debug log: https://drive.google.com/file/d/0B3OaSdeV0L8kaVdZcnp2dmJRSjg/view?usp=sharing

**Comment by sum2012** [comment]
Sorry, @kurasamesusaya I should try this method early.
