### ISSUE TITLE
Commit e4a0a3cea3 broke Playstation 4 controller mappings

### ISSUE THREAD

**Issue by atomnuker** [hrydgard/ppsspp#9111]
Hi,

Commit e4a0a3cea3bc22f82a6d0760420116337c72ff78 made several buttons on playstation 4 controllers unusable: the 2 buttons under the joysticks and the right top shoulder button. The bottom shoulder buttons are now regarded as axis as well. This makes the gamepad nearly unusable as you can't bind many useful features like save/state to buttons which didn't have an analogue on the PSP.

**Comment by Bigpet** [comment]
Thumbstick buttons were simply missing but I'm not sure I understand the issue with the shoulder buttons. I only have PS3 pad available but binding the shoulder buttons wasn't an issue.

Sure they're indicated as axis, but they can be bound to functions just like buttons for me.

**Comment by hrydgard** [comment]
Now that the missing thumbsticks are fixed you should at least have two new buttons.

Also, it works fine to bind axises as buttons indeed, so I'm just gonna close this.
