### ISSUE TITLE
Phantasy Star Portable 2 Blackscreen / Blank on Android

### ISSUE THREAD

**Issue by adenovan** [hrydgard/ppsspp#9118]
2 user with android device reported Phantasy Star Portable 2 got a black screen no display at all when fast memory turned off. fast memory turned on its display correclty.

Edit
Android device affected by this issues
-Xiaomi redmi 3 , Snapdragon 650 and Adreno 510
-Lenovo A6010 Snapdragon 510 Adreno 306

could it be a driver bug on Snapdragon chipset?

**Comment by hrydgard** [comment]
Sounds very weird, seems unlikely that fast-memory would have some interaction with display drivers.

Does it really only affect those devices, are there others that are not affected?

**Comment by hrydgard** [comment]
I wonder if this is still a problem on the latest builds?

**Comment by AkiraJkr** [comment]
Just throwing this around, I'll get around to testing this on another device if I can.

Screenshot of the game
![image](https://cdn.discordapp.com/attachments/479715219413663775/544548256261079061/Screenshot_2019-02-11-13-57-21.png)
Specs of the device tested

![image](https://cdn.discordapp.com/attachments/479715219413663775/544548256743686145/Screenshot_2019-02-11-13-58-59.png)

**Comment by unknownbrackets** [comment]
Has anything changed in the latest git builds?

-[Unknown]

**Comment by adenovan** [comment]
its normal on recent adreno device , doesn't know in old ones cause the phone mentioned on the issues is not mine can close if you want. 

![Screenshot_20200413-023243](https://user-images.githubusercontent.com/5246143/79076775-4f901900-7d2f-11ea-9742-9e30a49eb60b.png)
![Screenshot_20200413-023217](https://user-images.githubusercontent.com/5246143/79076779-5454cd00-7d2f-11ea-8e94-9562d2ec4fee.png)

**Comment by unknownbrackets** [comment]
Hm, I know there was a bug in Adreno 5xx drivers that we tried to workaround.

I'm going to close this then hoping it's fixed.  If it's not fixed, hopefully someone will come along and let us know.

-[Unknown]
