### ISSUE TITLE
Commandline --escape-exit doesn't work anymore

### ISSUE THREAD

**Issue by substring** [hrydgard/ppsspp#9119]
Hi,

I'm building PPSSPP for pi3. The `--escape-exit` was working fine in v1.2.2. Had to bumpt to commit 7ddd68de1798ac8ce5d626a1e05a910236c2ca5d and the switch is broken on this switch. I believe it might be related to https://github.com/hrydgard/ppsspp/pull/8993

**Comment by Orphis** [comment]
How are you building?
Can you show me your first CMake call? It should be using -DCMAKE_TOOLCHAIN_FILE=../cmake/Toolchains/raspberry.armv7.cmake

**Comment by substring** [comment]
it's not, i'm buildiong through buildroot, look :
```
/home/subs/git/recalbox-build-pi3/output/host/usr/bin/cmake /home/subs/git/recalbox-build-pi3/output/build/ppsspp-7ddd68de1798ac8ce5d626a1e05a910236c2ca5d/ -DCMAKE_TOOLCHAIN_FILE="/home/subs/git/recalbox-build-pi3/output/host/usr/share/buildroot/toolchainfile.cmake" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="/usr" -DCMAKE_COLOR_MAKEFILE=OFF -DBUILD_DOC=OFF -DBUILD_DOCS=OFF -DBUILD_EXAMPLE=OFF -DBUILD_EXAMPLES=OFF -DBUILD_TEST=OFF -DBUILD_TESTS=OFF -DBUILD_TESTING=OFF -DBUILD_SHARED_LIBS=ON  -DARMV7=1 -DUSE_FFMPEG=1 -DUSE_SYSTEM_FFMPEG=0 -DFFMPEG_BUILDDIR=1 -DUSING_FBDEV=1 -DUSING_GLES2=1 -DARM_NEON=1 -DARMV7=1
```

**Comment by Orphis** [comment]
This is not likely to work since you are using a different toolchain file than the one we provide with the right options.
Try ours and tell us if it works better!

**Comment by Orphis** [comment]
@joolswills Would you care to help this fellow RPI user and tell him how to build the current version please? :)

**Comment by joolswills** [comment]
I cannot advise on how to build on the recalbox buildroot I'm afraid - but you can see the RetroPie build script/module here - https://github.com/RetroPie/RetroPie-Setup/blob/master/scriptmodules/emulators/ppsspp.sh

**Comment by substring** [comment]
Errrr ... Guyz, it's not a compilation problem, but a commandline option that was working in v1.2.2, but not anymore now. Are hou sure this is linked to how PPSSPP is built ?

**Comment by LunaMoo** [comment]
Except that commandline works fine;p.

 There could be I guess 2 reasons it doesn't work for you:
 - nothing is mapped to pause button, but then you couldn't even pause the game,
 - you're building it with mobile flag or something as that feature is disabled for mobiles.

 This feature uses virtual key for pause and should really work same on all platforms it's enabled, so yeah it definitely can be a build issue.

**Comment by substring** [comment]
pebkac then ... is there a message saying it's compiling for mobile devices ?

**Comment by LunaMoo** [comment]
I have no idea about cmake and building for Pi, so can't really help, but confirming if you built a mobile version or not should be as easy as checking PPSSPP ui since there are quite a few differences between mobile and non mobile builds. For example mobiles have rendering resolution setting limited to x5 max, texture scaling to x3 max, don't have Fullscreen option either etc..

**Comment by substring** [comment]
OK, I guess i've narrowed down the problem
https://github.com/hrydgard/ppsspp/blob/master/SDL/SDLJoystick.cpp#L109-L110 defines the "guide" button to pause/back. BUT : `--escape-exit` won't work until the Pause button is set in settings/control. In other words, `--escape-exit` only works with gamecontrollerdb.txt if there is `Pause = 1-111,10-4
` in the controls.ini. I used to fully configure the controls.ini before switching to gamecontrollerdb.txt, this is why it was working before.

So this is definitely not a compilation problem, but a small miss in how a pad should be handled since https://github.com/hrydgard/ppsspp/pull/8993

**Comment by substring** [comment]
OK, I'm closing the issue as mapping in contorls.ini as said works. NKCodes are fixed for SDL gamepads through gamecontrolleddb.txt, so `10-4`will always be the guide button for Pad1
