### ISSUE TITLE
Random Matching Crash Phantasy Star Portable 2

### ISSUE THREAD

**Issue by adenovan** [hrydgard/ppsspp#9120]
Stack Trace
![screenshot 142](https://cloud.githubusercontent.com/assets/5246143/20281760/b3c170cc-aaec-11e6-9737-d542ed8597dd.png)

is this crash related to fast memory not turned off? 
my friend can't turn it off because he playing on android and have #9118  issues.

Edit 
- crashed on android when doing adb logcat :D lucky
[android crash log.txt](https://github.com/hrydgard/ppsspp/files/591537/android.crash.log.txt)

**Comment by hrydgard** [comment]
There's very little about the actual crash there in that log, I want the stack trace :)

However it's pretty clear that there may be some race conditions in that code. For the crash we can see above, context must have changed in the background during execution of that method, which it can because it doesn't lock peerlock in AfterMatchingMipsCall::SetContextID ...

**Comment by adenovan** [comment]
im just wondering we use wrong transport layer on maching event. the whole matching input thread is transfered through sceNetAdhocPdpSend and use PDP to transfer the matching event.

when the proadhoc.h have PSP_ADHOC_MATCHING_EVENT_DATA_ACK on https://github.com/hrydgard/ppsspp/blob/master/Core/HLE/proAdhoc.h#L634 .

looks like we use wrong transport layer . AFAIK UDP did not have ACK  on the transport layer. and that behavior cause race condition on bad network. or sometimes weird behavior on some event like player leaving the matching group because the packet did not arrived due to udp nature. it can lead to crash too.

coldbird itself stated on forum he use wrong transport layer on first attempt to emulate the adhocctl library ( proadhocserver) he use UDP instead of TCP and after moved to TCP more game become compatible.

some user also stated PSP and PPSSPP matching event is not connected when playing this game http://forums.ppsspp.org/showthread.php?tid=22654 

between PPSSPP instance it will just work because we use PDP to emulate that matching event. but sometimes its cause weird behavior too when connnect and disconnecting to the matching group several times.

should we move it to TCP and create some event on proadhocsever , it seems the matching event is using adhocctl connection to do the transfer and have some thread running on it.

need more digging on psp side. i wonder if this game working using pro online plugin between real psp. im just having one psp to test.

**Comment by unknownbrackets** [comment]
Is this still an issue on the latest git build with recent networking improvements?

-[Unknown]

**Comment by ANR2ME** [comment]
AdhocMatching could cause crashes in the past because it's running the mipscall callback on any random thread which cause memory/register corruption when returning, but nowadays it has it's own thread and shouldn't cause a crash anymore.
