### ISSUE TITLE
Games arnt loading on LG V20 Android 7.0

### ISSUE THREAD

**Issue by LonliestRocket** [hrydgard/ppsspp#9121]
This is the version of my phone LG-H918.
It is currently running android version 7.0
Also open gl es 3.2

**Comment by hrydgard** [comment]
What happens, does the emulator not start, or does it crash when you try to start a game?

**Comment by LonliestRocket** [comment]
When I try to load a game, it just loads to a black screen. No sound either. I know the game works, it worked on my other Android device.
