### ISSUE TITLE
Unable to make an Android build on win64 system

### ISSUE THREAD

**Issue by whisperlin** [hrydgard/ppsspp#9122]
I'm trying to make an android build on win7 64 System using NDK 10e and got same error:
Here's the log

D:/adt-bundle-windows/android-ndk-r10d/toolchains/aarch64-linux-android-4.9/preb
uilt/windows-x86_64/lib/gcc/aarch64-linux-android/4.9/../../../../aarch64-linux-
android/bin\ld.exe: cannot find -latomic
clang++.exe: error: linker command failed with exit code 1 (use -v to see invoca
tion)
make.exe: *** [obj/local/arm64-v8a/libppsspp_jni.so] Error 1
make.exe: *** Waiting for unfinished jobs....

**Comment by whisperlin** [comment]
Ijust modify  Application.mk to  

APP_STL := gnustl_static
APP_PLATFORM := android-9
APP_ABI := armeabi-v7a  x86
APP_GNUSTL_CPP_FEATURES := 
NDK_TOOLCHAIN_VERSION := clang

all done well

**Comment by hrydgard** [comment]
You should update to a newer NDK, 13b.

**Comment by pjacket** [comment]
APP_STL = gnustl_static 
APP_PLATFORM = หุ่นยนต์-9 
APP_ABI = armeabi-x86 v7a 
APP_GNUSTL_CPP_FEATURES = 
NDK_TOOLCHAIN_VERSION = เสียงดังกราว

ทำทุกอย่างดี

**Comment by hrydgard** [comment]
Not sure what you mean. You should not alter APP_ABI like that if you want to support 64-bit devices correctly (they will run a 32-bit PPSSPP but not quite as fast).
