### ISSUE TITLE
Crash when installing the game

### ISSUE THREAD

**Issue by whisperlin** [hrydgard/ppsspp#9123]
My library is compiling and linking fine but shows this error at runtime.
i got the error from the log.
E/dalvikvm(15202): dlopen("/data/app-lib/org.ppsspp.ppsspp-1/libppsspp_jni.so") failed: dlopen failed: cannot locate symbol "__tls_get_addr" referenced by "libppsspp_jni.so"...

Thanks in advance

**Comment by whisperlin** [comment]
I change  NDK_TOOLCHAIN_VERSION = 4.6
 , it work well

**Comment by hrydgard** [comment]
That's odd, seems that you have an old android device that is no longer well supported by the NDK .. definitely a bug in the NDK though, not in the emulator. Sigh...

**Comment by unknownbrackets** [comment]
Is this still an issue?

-[Unknown]

**Comment by hrydgard** [comment]
It's probably not worth keeping this open.
