### ISSUE TITLE
PPSSPP (latest version) crashes in Valkyria Chronicles 2 & 3

### ISSUE THREAD

**Issue by 8BitBeat** [hrydgard/ppsspp#9129]
iOS (9.3.3) with the latest ppsspp build. Settings are default.

Game crashes time to time if you select a character to start an action for the first phase at the start of a mission. For some reason, it sometimes won't crash if you skip your turn and select a character for action on any other phases.

Is there a way I can get a crash dump log so I can post this here?

**Comment by hrydgard** [comment]
Is the crash unique to iOS (that is, does it happen on Windows/Android or not?)

**Comment by LunaMoo** [comment]
Probably iOS or ARM specific, maybe another issue related to #9114.

 Definitely doesn't happen on x86_64/windows where both games run fine at least using fairy default-ish settings with some enhancements.

**Comment by hrydgard** [comment]
That probably fixes this, can you please test again when there's a new build?

**Comment by v8786339** [comment]
I am the authoe of #9140
1.3-175 also has the problem
I can show the savings to repeat the crash if need
only ios has the problem

**Comment by v8786339** [comment]
latest version donot solve it，i am sure
in my iphone ，the problem are happen by the turns below
1 play the game
2 save game ，all ok
3 load game， ok
4 play ok
5 sometimes lock the screen in the 2d mode
6 unlock the screen，enter ppsspp，enter 3d mode crash，load the latest saving ，crash
7 while there is a way to fix the problem
8 do not use all fucking savings，restarting game ，all ok

ios 9.0.2

**Comment by v8786339** [comment]
@ lunamoo can give me your email，i will send the fucking savings for analysis

**Comment by v8786339** [comment]
oh i only test the load the original saving and crash but NOT test restarting the game from begin and trying to repeat making the problem saving

**Comment by 8BitBeat** [comment]
Ah, sorry for being a bit inactive after opening this issue. I'll test it again with the newest build (which I assume is already in the dev build in cydia)

**Comment by hrydgard** [comment]
Pretty sure this is fixed now. Please reopen if not.
