### ISSUE TITLE
Undefined Reference to symbol 'XDisplayScreen' while compiling

### ISSUE THREAD

**Issue by andoruB** [hrydgard/ppsspp#9130]
I've got the latest commit ( 7390d1f ) and I've tried compiling it on Debian Sid, and I'm getting this error right at the end:
```
[100%] Linking CXX executable PPSSPPSDL
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libavutil.a(hwcontext_vdpau.o): undefined reference to symbol 'XDisplayString'
//usr/lib/x86_64-linux-gnu/libX11.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/PPSSPPSDL.dir/build.make:841: recipe for target 'PPSSPPSDL' failed
make[2]: *** [PPSSPPSDL] Error 1
CMakeFiles/Makefile2:428: recipe for target 'CMakeFiles/PPSSPPSDL.dir/all' failed
```

**Comment by hrydgard** [comment]
In CMakeLists.txt, does it help if you do the following change around line 309:

	 if(NOT USING_GLES2)
		 include_directories(${OPENGL_INCLUDE_DIR})
		 find_package(GLEW)
                 # THE NEW 3 LINES HERE 
                 if (LINUX)
                     find_package(X11)
                 endif()
                 # END OF NEW LINES
		 if(NOT GLEW_FOUND)
			 add_definitions(-DGLEW_STATIC)
			 add_library(glew STATIC
				 ext/native/ext/glew/GL/glew.h
				 ext/native/ext/glew/GL/glxew.h
				 ext/native/ext/glew/GL/wglew.h
				 ext/native/ext/glew/glew.c)
			 target_link_libraries(glew ${OPENGL_LIBRARIES})
			 include_directories(ext/native/ext/glew)
			 set(GLEW_LIBRARIES glew)
		 endif()
	 else()
		 find_package(X11)
	 endif()

?

**Comment by andoruB** [comment]
It seems to have done something, however I now get this: 
```
[100%] Linking CXX executable PPSSPPSDL
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libavcodec.a(tiff.o): undefined reference to symbol 'lzma_stream_decoder@@XZ_5.0'
//lib/x86_64-linux-gnu/liblzma.so.5: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/PPSSPPSDL.dir/build.make:845: recipe for target 'PPSSPPSDL' failed
make[2]: *** [PPSSPPSDL] Error 1
CMakeFiles/Makefile2:428: recipe for targ
```

Mind you, I have updated the tree to e1e3358

**Comment by hrydgard** [comment]
Okay, got no explanation for that one...  very weird. Looks like on your machine the script is using a system ffmpeg instead of the supplied one though for some reason... ?

**Comment by andoruB** [comment]
I haven't done any modifications to the source files except what you told me...
What's more, I tried clearing the whole tree and cloning it again, and made the following modifications:

```
if(NOT USING_GLES2)
	 include_directories(${OPENGL_INCLUDE_DIR})
	 find_package(GLEW)
             # THE NEW 3 LINES HERE 
             if (LINUX)
                 find_package(X11)
				 find_package(liblzma)
             endif()
             # END OF NEW LINES
	 if(NOT GLEW_FOUND)
		 add_definitions(-DGLEW_STATIC)
		 add_library(glew STATIC
			 ext/native/ext/glew/GL/glew.h
			 ext/native/ext/glew/GL/glxew.h
			 ext/native/ext/glew/GL/wglew.h
			 ext/native/ext/glew/glew.c)
		 target_link_libraries(glew ${OPENGL_LIBRARIES})
		 include_directories(ext/native/ext/glew)
		 set(GLEW_LIBRARIES glew)
	 endif()
 else()
	 find_package(X11)
	 find_package(liblzma)
 endif()

```

Basically added find_package(liblzma) in the same vein of your previous modification, but now I get: 

```
[ 49%] Building CXX object CMakeFiles/Core.dir/Core/Debugger/SymbolMap.cpp.o
/home/andoru/sources/ppsspp/Core/Debugger/SymbolMap.cpp:40:39: fatal error: ext/armips/Core/Assembler.h: No such file or directory
 #include "ext/armips/Core/Assembler.h"
                                       ^
compilation terminated.
CMakeFiles/Core.dir/build.make:1478: recipe for target 'CMakeFiles/Core.dir/Core/Debugger/SymbolMap.cpp.o' failed
make[2]: *** [CMakeFiles/Core.dir/Core/Debugger/SymbolMap.cpp.o] Error 1
CMakeFiles/Makefile2:116: recipe for target 'CMakeFiles/Core.dir/all' failed
```

:/

**Comment by hrydgard** [comment]
That's an easy one though. 

    git submodule update --init --recursive

**Comment by andoruB** [comment]
Yeah, I was an idiot, never mind about that reply. Forgot I needed the dependencies on this git.

**Comment by hrydgard** [comment]
So did that solve it, or are we back on square one?

**Comment by andoruB** [comment]
Okay, previously I got the submodules manually (changed directory to the submodules and cloned the repos from there), and I seem to have forgotten to do that for ffmpeg. Now with your more elegant solution, I reverted back to your modification in CMakeLists.txt (https://github.com/hrydgard/ppsspp/issues/9130#issuecomment-264210567 -- without referencing liblzma), and compiled, but yet again I get an error right at the end:

```
[100%] Linking CXX executable PPSSPPSDL
lib/libCore.a(sceAtrac.cpp.o): In function `__AtracShutdown()':
sceAtrac.cpp:(.text+0x2314): undefined reference to `av_packet_free'
lib/libCore.a(sceAtrac.cpp.o): In function `__AtracSetContext(Atrac*)':
sceAtrac.cpp:(.text+0x6abd): undefined reference to `av_packet_alloc'
lib/libCore.a(sceAtrac.cpp.o): In function `_AtracSetData(Atrac*, unsigned int, unsigned int, unsigned int, int)':
sceAtrac.cpp:(.text+0x6da9): undefined reference to `av_packet_free'
lib/libCore.a(sceAtrac.cpp.o): In function `void WrapI_IU<&(sceAtracLowLevelInitDecoder(int, unsigned int))>()':
sceAtrac.cpp:(.text+0x7bad): undefined reference to `av_packet_free'
lib/libCore.a(sceAtrac.cpp.o): In function `void WrapI_UUUU<&(sceAtracSetAA3HalfwayBufferAndGetID(unsigned int, unsigned int, unsigned int, unsigned int))>()':
sceAtrac.cpp:(.text+0x8c95): undefined reference to `av_packet_free'
sceAtrac.cpp:(.text+0x8dde): undefined reference to `av_packet_free'
lib/libCore.a(sceAtrac.cpp.o): In function `void WrapI_UUUU<&(sceAtracSetAA3DataAndGetID(unsigned int, unsigned int, unsigned int, unsigned int))>()':
sceAtrac.cpp:(.text+0x92aa): undefined reference to `av_packet_free'
lib/libCore.a(sceAtrac.cpp.o):sceAtrac.cpp:(.text+0x9406): more undefined references to `av_packet_free' follow
collect2: error: ld returned 1 exit status
CMakeFiles/PPSSPPSDL.dir/build.make:845: recipe for target 'PPSSPPSDL' failed
make[2]: *** [PPSSPPSDL] Error 1
CMakeFiles/Makefile2:428: recipe for target 'CMakeFiles/PPSSPPSDL.dir/all' failed
```

**Comment by hrydgard** [comment]
Very strange. @unknownbrackets haven't we seen this before?  Not sure..

**Comment by andoruB** [comment]
Got the latest commit ( 8bcb5f0 )... and it compiled flawlessly... ? I did not have to modify anything, yet it worked fine. Was there a fix for this in the code? I'm closing this issue, hoping that nobody else will encounter the same problem as I did.
Thanks hrydgard for your help and for your work on this emulator :)
