### ISSUE TITLE
FIFA 14 crashes

### ISSUE THREAD

**Issue by Robsoie** [hrydgard/ppsspp#9134]
I am used to play FIFA 14 with with no problem on an older PPSSPP 1.1.xxx version on my winxp 32bits in D3D9 (i don't play in OpenGL) , as the few games i have with it are working perfectly.

Today i decided to give a try to latest build of PPSSPP, to see how some of the games behaved , so i downloaded ppsspp-v1.3-150-g7930d1f-windows-x86.
tested FIFA14 then it just crashed during loading, a bit before the main menu

Went to try "stable" PPSSPP 1.3 and there FIFA14 crashed even faster, couple of second after launch of it.

Decided to find the version in which the crash started and after downloading and testing i found out 

1.2.2-698-gb676922 is the 1st that start to crash FIFA14 during loading.
1.2.2-693-g12be183 is the last one that perfectly works with FIFA14
The comment on the build page seems to refer to a D3D9 (and Vulkan) change, so probably that OpenGL isn't affected.

(there's no versions to download for win32 in between so can't pinpoint more than that)
It's not much important to me as i still can play my trusty old PPSSPP version, but in case it can help for future bug report i prefer to post it.

note : while testing versions, i found some odd ones like 1.2.2-799-gcbf0a47 , that while still crashing , will crash later instead of during the loading time , that version by example crash when you confirm which team you are and which one is assigned to AI.

**Comment by Konealassane701** [comment]
Jolie

**Comment by hrydgard** [comment]
Thanks for the detailed information! I'll see if I can figure something out.

**Comment by Robsoie** [comment]
Hello, 
a bit of update after testing latest available ppsspp build ( 1.3-483-gc1f9f96-windows-x86 ) 

While FIFA14 still is crashing, the location of the crash has changed slightly and crash after you have assigned the player and the AI team, not before the main menu.

1.2.2-693-g12be183 is still the last version that has FIFA14 working 100%
I can't say if the other FIFA games are affected though, not having any of them, they're using the same engine but who knows.

**Comment by sum2012** [comment]
I test no problem on v1.3-493-g83ff9f4 win 32 build of directx 9
My display card is Nvidia GTX 750
![1](https://cloud.githubusercontent.com/assets/2177532/22622259/f0e6237a-eb70-11e6-9739-46c8c72fa5c6.jpg)

**Comment by Robsoie** [comment]
Hmm, very odd

I just tried with latest version ( v1.3-554-g9dd3e18 ) and didn't used my saved data and system data from the working last version i used (1.2.2-693-g12be183), so basically starting the game as if it has been the 1st time, with default settings and etc in case one of the old setting was breaking new ppsspp version.

After loading, i press Start and the game ask me to choose a level of experience (as it did the first time i played FIFA14) , after selecting one, i'm then asked to create (or not) a profile in order to save or not my progress (normal as it's as if it was the 1st time i play) and regardless of me clicking yes or no, PPSSPP just crash there.

Then to test i reload, and when it reach the time i need to press START, it crashes just there.

It is very odd, and the other oddity is that the other games i tried with this version of PPSSPP works the same (very well) as in the "working" version of PPSSPP i was always using, i wonder what's going on then specifically with FIFA14 for version 1.2.2-698-gb676922 to have started breaking it on my system and not breaking the other games.

If it works on other people 32bits i guess it has either to do with window XP or with my intel G41, oh well i'll keep my trusty 1.2.2-693-g12be183 as everything i have works great .

**Comment by sum2012** [comment]
No,I think that your Intel display card G41 has driver problem,
Anyway ,do you mean  v1.2.2-698-gb676922 start not working ?
https://drive.google.com/file/d/0B3OaSdeV0L8kSDhELVllUUVDZTg/view?usp=sharing

**Comment by sum2012** [comment]
That mean #8825 started breaking the problem

**Comment by sum2012** [comment]
@Robsoie can you help test 3 build to know which change making problem.
First ,test this build 
https://drive.google.com/file/d/0B3OaSdeV0L8kQU1QR0kyYlMtZ2c/view?usp=sharing
This is  4c94cd764d0aeb9436699d364b86eb6e5371ce21

**Comment by Robsoie** [comment]
Hello sum2012

I downloaded and tried your build (ppsspp-v1.2.2-684-g4c94cd7-windows-x86) , seems like it is using a font i didn't had so the interface has some odds square and missing characters but after editing the language setting in the ppsspp.ini from zh_CN to en_US it worked correctly and i could switch to direct3d9

I managed to launch FIFA14 with it without problems , i could create a new profile (as i didn't used my saved game for it) and launch a match without problem, freeze or crash.

**Comment by sum2012** [comment]
@Robsoie Thanks for testing.it mean https://github.com/hrydgard/ppsspp/pull/8825/commits/79101736b868fe1195808a7039275e309d80a6ba does not support decode directly into texture buffer in your display card.
@hrydgard Any workaround method for fix crash for https://github.com/hrydgard/ppsspp/pull/8825/commits/79101736b868fe1195808a7039275e309d80a6ba 
for  intel G41 display card ?

**Comment by hrydgard** [comment]
I believe there might be a bug in 7910173 where it can occasionally write out of bounds, I saw something similar when messing with texture loads for D3D11. Will look into it.

**Comment by hrydgard** [comment]
I think I may have fixed it. Try a new build.

**Comment by hrydgard** [comment]
@Robsoie  Please try the latest build from http://buildbot.orphis.net/ppsspp/ , and close this issue if it works now (it should).

**Comment by hrydgard** [comment]
No response, but pretty sure I caught it, so I'm closing.

**Comment by Robsoie** [comment]
Sorry i wasn't home recently.
I just downloaded and tried ppsspp-v1.3-697-gdfae4b6-windows-x86

And unfortunately after launching PPSSPP without any save or ppsspp.ini (so i could use everything default) switching first to D3D9, same thing : the game crash either if i try to create a profile (there's no save so you're asked if you want one), or if i choose not to create a profile i can choose the teams, assign me and AI to specific team but after that while the game is loading the actual match it just crashed.

**Comment by Robsoie** [comment]
in case it can help, i tried to use the debuglog.bat ( on ppsspp-v1.3-697-gdfae4b6-windows-x86 ) and on the 2 crashes i had, here the content of the last timing on a crash that happened during the match loading after i declined creating a profile , the 1st crash 

53:14:031 user_main    D[KERNEL]: HLE\sceKernelThread.cpp:3032 Context switch: SND_SAS -> user_main (373->276, pc: 088041f4->08deeb30, blocking audio) +12us
53:14:046 idle0        D[KERNEL]: HLE\sceKernelThread.cpp:3032 Context switch: user_main -> idle0 (276->272, pc: 08ae9b44->08000000, interrupt) +2471us
53:14:046 idle0        D[KERNEL]: HLE\sceKernelAlarm.cpp:81 Entering alarm 0000011b handler: 08b51fcc
53:14:046 idle0        D[KERNEL]: HLE\sceKernelAlarm.cpp:96 Rescheduling alarm 0000011b for +10000ms
53:14:046 user_main    D[KERNEL]: HLE\sceKernelThread.cpp:3032 Context switch: idle0 -> user_main (272->276, pc: 08000000->08ae9b44, left interrupt) +5us
53:14:046 user_main    D[SCEGE]: HLE\sceGe.cpp:413 sceGeDrawSync(mode=0)  (0=wait for completion, 1=peek)
53:14:046 SND_SAS      D[KERNEL]: HLE\sceKernelThread.cpp:3032 Context switch: user_main -> SND_SAS (276->373, pc: 08b525b4->088041f4, audio drain) +3059us
53:14:046 SND_SAS      D[SCESAS]: HLE\sceSas.cpp:302 0=__sceSasCore(08f636c0, 09293d00)
53:14:046 user_main    D[KERNEL]: HLE\sceKernelThread.cpp:3032 Context switch: SND_SAS -> user_main (373->276, pc: 08804c30->08b525b4, sas core) +15us
53:14:046 SND_SAS      D[KERNEL]: HLE\sceKernelThread.cpp:3032 Context switch: user_main -> SND_SAS (276->373, pc: 08b525ac->08804c30, woke from sas mix) +243us
53:14:046 SND_SAS      D[AUDIO]: HLE\sceAudio.cpp:130 00000100 = sceAudioOutputPannedBlocking(00000005, 00008000, 00008000, 09293d00)
53:14:046 user_main    D[KERNEL]: HLE\sceKernelThread.cpp:3032 Context switch: SND_SAS -> user_main (373->276, pc: 088041f4->08b525ac, blocking audio) +12us
53:14:046 SND_SAS      D[KERNEL]: HLE\sceKernelThread.cpp:3032 Context switch: user_main -> SND_SAS (276->373, pc: 08b525ac->088041f4, audio drain) +5534us
53:14:046 SND_SAS      D[SCESAS]: HLE\sceSas.cpp:302 0=__sceSasCore(08f636c0, 09294100)
53:14:046 SND          D[KERNEL]: HLE\sceKernelThread.cpp:3032 Context switch: SND_SAS -> SND (373->372, pc: 08804c30->088041f4, sas core) +15us
53:14:046 SND          D[KERNEL]: HLE\sceKernelSemaphore.cpp:413 0=sceKernelWaitSema(369, 1, 0)
53:14:046 SND          D[SCESAS]: HLE\sceSas.cpp:272 fffffffe=sceSasGetEndFlag(08f636c0)
53:14:046 SND          D[KERNEL]: HLE\sceKernelSemaphore.cpp:304 sceKernelSignalSema(369, 1) (count: 0 -> 1)
53:14:046 SND          D[AUDIO]: HLE\sceAudio.cpp:271 00000000 = sceAudioSetChannelDataLen(00000006, 00000200)
53:14:046 SND          D[AUDIO]: HLE\sceAudio.cpp:130 00000200 = sceAudioOutputPannedBlocking(00000006, 00008000, 00008000, 09292d00)
53:14:046 user_main    D[KERNEL]: HLE\sceKernelThread.cpp:3032 Context switch: SND -> user_main (372->276, pc: 088041f4->08b525ac, blocking audio) +55us
53:14:046 SND_SAS      D[KERNEL]: HLE\sceKernelThread.cpp:3032 Context switch: user_main -> SND_SAS (276->373, pc: 08b525ac->08804c30, woke from sas mix) +188us
53:14:046 SND_SAS      D[AUDIO]: HLE\sceAudio.cpp:130 00000100 = sceAudioOutputPannedBlocking(00000005, 00008000, 00008000, 09294100)
53:14:046 user_main    D[KERNEL]: HLE\sceKernelThread.cpp:3032 Context switch: SND_SAS -> user_main (373->276, pc: 088041f4->08b525ac, blocking audio) +12us
53:14:046 idle0        D[KERNEL]: HLE\sceKernelThread.cpp:3032 Context switch: user_main -> idle0 (276->272, pc: 08afffb4->08000000, interrupt) +808us
53:14:046 idle0        D[CPU]: HLE\sceKernelInterrupt.cpp:151 Entering interrupt handler 08affdc4
53:14:046 idle0        D[SCEGE]: Common\FramebufferCommon.cpp:886 Displaying FBO 00000000
53:14:062 user_main    D[KERNEL]: HLE\sceKernelThread.cpp:3032 Context switch: idle0 -> user_main (272->276, pc: 08000000->08afffb4, left interrupt) +5us

**Comment by Robsoie** [comment]
Now for the 2nd crash, that happened after i created a profile

49:00:828 idle0        D[CPU]: HLE\sceKernelInterrupt.cpp:151 Entering interrupt handler 08affdc4
49:00:828 idle0        D[SCEGE]: Common\FramebufferCommon.cpp:886 Displaying FBO 00000000
49:00:859 user_main    D[KERNEL]: HLE\sceKernelThread.cpp:3032 Context switch: idle0 -> user_main (272->276, pc: 08000000->08b52570, left interrupt) +5us
49:00:859 SND_SAS      D[KERNEL]: HLE\sceKernelThread.cpp:3032 Context switch: user_main -> SND_SAS (276->373, pc: 08b525ac->088041f4, audio drain) +59us
49:00:859 SND_SAS      D[SCESAS]: HLE\sceSas.cpp:302 0=__sceSasCore(08f636c0, 09294100)
49:00:859 SND          D[KERNEL]: HLE\sceKernelThread.cpp:3032 Context switch: SND_SAS -> SND (373->372, pc: 08804c30->088041f4, sas core) +15us
49:00:859 SND          D[KERNEL]: HLE\sceKernelSemaphore.cpp:413 0=sceKernelWaitSema(369, 1, 0)
49:00:859 SND          D[SCESAS]: HLE\sceSas.cpp:272 ffffffff=sceSasGetEndFlag(08f636c0)
49:00:859 SND          D[KERNEL]: HLE\sceKernelSemaphore.cpp:304 sceKernelSignalSema(369, 1) (count: 0 -> 1)
49:00:859 SND          D[AUDIO]: HLE\sceAudio.cpp:271 00000000 = sceAudioSetChannelDataLen(00000006, 00000200)
49:00:859 SND          D[AUDIO]: HLE\sceAudio.cpp:130 00000200 = sceAudioOutputPannedBlocking(00000006, 00008000, 00008000, 09293500)
49:00:859 user_main    D[KERNEL]: HLE\sceKernelThread.cpp:3032 Context switch: SND -> user_main (372->276, pc: 088041f4->08b525ac, blocking audio) +55us
49:00:859 SND_SAS      D[KERNEL]: HLE\sceKernelThread.cpp:3032 Context switch: user_main -> SND_SAS (276->373, pc: 08b525b4->08804c30, woke from sas mix) +117us
49:00:859 SND_SAS      D[AUDIO]: HLE\sceAudio.cpp:130 00000100 = sceAudioOutputPannedBlocking(00000005, 00008000, 00008000, 09294100)
49:00:859 user_main    D[KERNEL]: HLE\sceKernelThread.cpp:3032 Context switch: SND_SAS -> user_main (373->276, pc: 088041f4->08b525b4, blocking audio) +12us
49:00:859 SND_SAS      D[KERNEL]: HLE\sceKernelThread.cpp:3032 Context switch: user_main -> SND_SAS (276->373, pc: 08b525ac->088041f4, audio drain) +5605us
49:00:859 SND_SAS      D[SCESAS]: HLE\sceSas.cpp:302 0=__sceSasCore(08f636c0, 09293d00)
49:00:859 user_main    D[KERNEL]: HLE\sceKernelThread.cpp:3032 Context switch: SND_SAS -> user_main (373->276, pc: 08804c30->08b525ac, sas core) +15us
49:00:859 SND_SAS      D[KERNEL]: HLE\sceKernelThread.cpp:3032 Context switch: user_main -> SND_SAS (276->373, pc: 08b525b4->08804c30, woke from sas mix) +173us
49:00:859 SND_SAS      D[AUDIO]: HLE\sceAudio.cpp:130 00000100 = sceAudioOutputPannedBlocking(00000005, 00008000, 00008000, 09293d00)
49:00:859 user_main    D[KERNEL]: HLE\sceKernelThread.cpp:3032 Context switch: SND_SAS -> user_main (373->276, pc: 088041f4->08b525b4, blocking audio) +12us
49:00:859 idle0        D[KERNEL]: HLE\sceKernelThread.cpp:3032 Context switch: user_main -> idle0 (276->272, pc: 08b525ac->08000000, interrupt) +3326us
49:00:859 idle0        D[KERNEL]: HLE\sceKernelAlarm.cpp:81 Entering alarm 0000011b handler: 08b51fcc
49:00:859 idle0        D[KERNEL]: HLE\sceKernelAlarm.cpp:96 Rescheduling alarm 0000011b for +10000ms
49:00:859 user_main    D[KERNEL]: HLE\sceKernelThread.cpp:3032 Context switch: idle0 -> user_main (272->276, pc: 08000000->08b525ac, left interrupt) +5us
49:00:859 SND_SAS      D[KERNEL]: HLE\sceKernelThread.cpp:3032 Context switch: user_main -> SND_SAS (276->373, pc: 08b525ac->088041f4, audio drain) +2269us
49:00:859 SND_SAS      D[SCESAS]: HLE\sceSas.cpp:302 0=__sceSasCore(08f636c0, 09294100)
49:00:859 SND          D[KERNEL]: HLE\sceKernelThread.cpp:3032 Context switch: SND_SAS -> SND (373->372, pc: 08804c30->088041f4, sas core) +15us
49:00:859 SND          D[KERNEL]: HLE\sceKernelSemaphore.cpp:413 0=sceKernelWaitSema(369, 1, 0)
49:00:859 SND          D[SCESAS]: HLE\sceSas.cpp:272 ffffffff=sceSasGetEndFlag(08f636c0)
49:00:859 SND          D[KERNEL]: HLE\sceKernelSemaphore.cpp:304 sceKernelSignalSema(369, 1) (count: 0 -> 1)
49:00:859 SND          D[AUDIO]: HLE\sceAudio.cpp:271 00000000 = sceAudioSetChannelDataLen(00000006, 00000200)
49:00:859 SND          D[AUDIO]: HLE\sceAudio.cpp:130 00000200 = sceAudioOutputPannedBlocking(00000006, 00008000, 00008000, 09292d00)
49:00:859 user_main    D[KERNEL]: HLE\sceKernelThread.cpp:3032 Context switch: SND -> user_main (372->276, pc: 088041f4->08b525ac, blocking audio) +63us
49:00:859 SND_SAS      D[KERNEL]: HLE\sceKernelThread.cpp:3032 Context switch: user_main -> SND_SAS (276->373, pc: 08b525b4->08804c30, woke from sas mix) +109us
49:00:859 SND_SAS      D[AUDIO]: HLE\sceAudio.cpp:130 00000100 = sceAudioOutputPannedBlocking(00000005, 00008000, 00008000, 09294100)
49:00:859 user_main    D[KERNEL]: HLE\sceKernelThread.cpp:3032 Context switch: SND_SAS -> user_main (373->276, pc: 088041f4->08b525b4, blocking audio) +12us
49:00:859 SND ATRAC PL D[KERNEL]: HLE\sceKernelThread.cpp:3032 Context switch: user_main -> SND ATRAC PLAYER (276->431, pc: 08b525ac->088041f4, audio drain) +1255us
49:00:859 SND ATRAC PL D[ME]: HLE\sceAtrac.cpp:1562 sceAtracGetNextSample(0, 09fd59fc): 2048 samples left
49:00:859 SND ATRAC PL D[ME]: HLE\sceAtrac.cpp:1317 00000000=sceAtracDecodeData(0, 09298d80, 09fd59f4[00000800], 09fd59f0[00000000], 09fd59f8[12])
49:00:859 user_main    D[KERNEL]: HLE\sceKernelThread.cpp:3032 Context switch: SND ATRAC PLAYER -> user_main (431->276, pc: 08b76b9c->08b525ac, atrac decode data) +12us
49:00:859 SND ATRAC PL D[KERNEL]: HLE\sceKernelThread.cpp:3032 Context switch: user_main -> SND ATRAC PLAYER (276->431, pc: 08b525b4->08b76b9c, woke from hle delay) +2301us
49:00:859 SND ATRAC PL D[AUDIO]: HLE\sceAudio.cpp:271 00000000 = sceAudioSetChannelDataLen(00000004, 00000800)
49:00:859 SND ATRAC PL D[AUDIO]: HLE\sceAudio.cpp:130 00000800 = sceAudioOutputPannedBlocking(00000004, 00008000, 00008000, 09298d80)
49:00:859 user_main    D[KERNEL]: HLE\sceKernelThread.cpp:3032 Context switch: SND ATRAC PLAYER -> user_main (431->276, pc: 088041f4->08b525b4, blocking audio) +12us
49:00:859 idle0        D[KERNEL]: HLE\sceKernelThread.cpp:3032 Context switch: user_main -> idle0 (276->272, pc: 08b525ac->08000000, interrupt) +1231us
49:00:859 idle0        D[CPU]: HLE\sceKernelInterrupt.cpp:151 Entering interrupt handler 08affdc4
49:00:859 user_main    D[KERNEL]: HLE\sceKernelThread.cpp:3032 Context switch: idle0 -> user_main (272->276, pc: 08000000->08b525ac, left interrupt) +5us
49:00:859 user_main    D[SCEGE]: HLE\sceGe.cpp:357 sceGeListEnQueue(addr=08ec8604, stall=00000000, cbid=00000000, param=00000000)
49:00:859 user_main    D[G3D]: GPUCommon.cpp:807 Starting DL execution at 08ec8604 - stall = 00000000
49:00:859 user_main    D[G3D]: Common\FramebufferCommon.cpp:275 Est: 00000000 V: 480x272, R: 480x272, S: 480x272, STR: 512, THR:1, Z:00000000 = 480x272
49:00:859 user_main    D[SCEGE]: Common\FramebufferCommon.cpp:477 Switching render target to FBO for 00000000: 480 x 272 x 1 
49:00:859 user_main    D[SCEGE]: HLE\sceGe.cpp:364 List 889192496 enqueued.
49:00:859 user_main    D[DISP]: HLE\sceDisplay.cpp:859 0=sceDisplaySetFrameBuf(04000000, 512, 1, 0)
49:00:859 idle0        D[KERNEL]: HLE\sceKernelThread.cpp:3032 Context switch: user_main -> idle0 (276->272, pc: 08b00994->08000000, interrupt) +28us
49:00:859 idle0        D[CPU]: HLE\sceGe.cpp:122 Entering GE interrupt handler 08afba04
49:00:859 user_main    D[KERNEL]: HLE\sceKernelThread.cpp:3032 Context switch: idle0 -> user_main (272->276, pc: 08000000->08b00994, left interrupt) +6us
49:00:859 user_main    D[SCEGE]: HLE\sceGe.cpp:357 sceGeListEnQueue(addr=091c8640, stall=00000000, cbid=00000000, param=00000000)
49:00:859 user_main    D[G3D]: GPUCommon.cpp:807 Starting DL execution at 091c8640 - stall = 00000000
49:00:859 user_main    D[G3D]: Common\FramebufferCommon.cpp:275 Est: 00044000 V: 480x272, R: 480x272, S: 480x272, STR: 512, THR:1, Z:440cc000 = 480x272
49:00:859 user_main    D[SCEGE]: Common\FramebufferCommon.cpp:477 Switching render target to FBO for 00044000: 480 x 272 x 3 
49:00:859 user_main    D[G3D]: Common\TextureCacheCommon.cpp:610 Render to texture detected at 04044000!
49:00:859 user_main    D[G3D]: Common\TextureCacheCommon.cpp:452 Texture different or overwritten, reloading at 09a57430: different params
49:00:859 user_main    D[G3D]: Directx9\TextureCacheDX9.cpp:88 Deleting texture 10F43800

**Comment by hrydgard** [comment]
Argh sorry to hear that, I found such a plausible cause... Hmm.

**Comment by hrydgard** [comment]
One more attempt...

**Comment by hrydgard** [comment]
I'm gonna close this again to check this off my v1.4 milestone, please reopen if it still crashes.

**Comment by Robsoie** [comment]
I finally could try and i confirm FIFA14 is working in v1.3-747-gd84f579 without anymore problems
I created profiles without crashes and could load a match without crashes.
Played a couple of matches with different teams for both player and AI, again without crashes.
Good job !

**Comment by hrydgard** [comment]
Great, thanks for testing!
