### ISSUE TITLE
Using ppsspp with openemu 

### ISSUE THREAD

**Issue by 0341rah** [hrydgard/ppsspp#9135]
I have tried 5 different games and the only one that has worked is Fifa Street. The other games were 
Fight night round 3
GTA Vice City Stories
Midnightclub
Def Jam 
Need for Speed most wanted
The games open up but when i try to start a career mode they freeze and they freeze the openemu app i have to force quit any advise?

**Comment by hrydgard** [comment]
All or most of those should work fine in regular PPSSPP. We don't support the OpenEmu integration here, if there are specific issues then they will have to deal with it.
