### ISSUE TITLE
application crashed immediately. just 'click' the game 

### ISSUE THREAD

**Issue by ewlkkf** [hrydgard/ppsspp#9144]
(I just bought Iphone7 2 days ago)
when I clicked the game, PPSSPP crashed immediately.

device : Iphone 7
version : 1.3-142-gda97119
IOS : 10.1.1

1. download ppsspp (using non-jailbreakers install method) 
2. put ISO in the folder using ITunes. (Computer connect)
3. game click
4. crashes without anything error message.

I also try using NewGamePad(multi-platform emulator) to boot game, but it also crashes after game logo passed.

no matter how I change setting, still crash.

Persona 3 Portable : atlus -> criware -> CRASH (normally, opening movie will be shown.)
Metal Gear Solid - Peace Walker : CRASH (normally, opening movie will be shown.)
Crisis Core - FFVII : CRASH (normally, main menu will be shown.)

does emulator goes wrong, or my mistake?

**Comment by hrydgard** [comment]
Try the following:

Go to Settings->Tools->Developer Tools and change the CPU Core to IR Interpreter instead of JIT.

What happens then?

**Comment by ewlkkf** [comment]
boot success, but crash after 3 seconds.

**Comment by kajinka13** [comment]
Same problem with the game "dragon ball shin budokai" T_T

**Comment by sum2012** [comment]
People in baidu forum report that last week no problem,but after that update ppsspp would crash

**Comment by hrydgard** [comment]
This is fixed, except for the JIT in 64-bit iOS builds.

**Comment by Anonamyss** [comment]
Use Interpreter instead of JIT, works fine now with me.
