### ISSUE TITLE
signed integer overflows

### ISSUE THREAD

**Issue by latot** [hrydgard/ppsspp#9145]
Hi all, well experimenting a little i found ops with overflows.., here is the list:

Confirmed:
Core/HLE/sceKernel.cpp:351
Core/HLE/sceRtc.cpp:299
Core/HLE/sceKernelMutex.cpp:814
Core/HLE/sceKernelMutex.cpp:397
Core/HLE/sceMpeg.cpp:434
Core/HLE/sceMpeg.cpp:280

Potential:
Common/ArmEmitter.h:436
Common/ArmEmitter.h:442
Common/Arm64Emmiter.cpp:902
Core/MIPS/MIPSInt.cpp:772
Core/Util/DisArm64.cpp:80
GPU/Common/TextureDecoder.cpp:327
GPU/State.cpp:80

I found this with clang and other apps.

Thx. Cya.

**Comment by hrydgard** [comment]
Please send pull requests fixing it instead, these are a bit time consuming to go through as-is...
