### ISSUE TITLE
Shift negative values

### ISSUE THREAD

**Issue by latot** [hrydgard/ppsspp#9146]
Hi, here again, with the same method as the previous issue, here:

Confirmed:
Core/MIPS/MIPSCodeUtils.cpp:80
Core/MIPS/x86/CompBranch.cpp:325
Core/MIPS/x86/CompBranch.cpp:401
Core/MIPS/x86/CompBranch.cpp:517
Core/Font/PGF.cpp:484
Core/Font/PGF.cpp:485
Core/Font/PGF.cpp:507
Core/Font/PGF.cpp:508
Core/HW/MpegDemux.cpp:200

Potential:
Common/ArmEmmiter.cpp:889
Common/ArmEmmiter.cpp:1168
ext/native/ext/jpge/jpgd.cpp:566
ext/native/ext/jpge/jpgd.cpp:2680

Thx. Cya.

**Comment by hrydgard** [comment]
Please just send pull requests instead :)

**Comment by latot** [comment]
Hi, is possible re-open the last 2 issues please?, the reason of why i open this instead send a pr is because there are parts i don't know how solve..., i'll need some guide to can work on it, and following a little this, where i can get info of how psp and emulators works?, to can understand how this works.

**Comment by hrydgard** [comment]
Nah, just do the changes and send pull requests anyway. If I see something wrong I'll tell you.

**Comment by latot** [comment]
Hi!, first i found i wasn't compiling the PSPHeadless so some logs are old, so recompiling and retesting i found new things, and i don't know what do, because is possible some parts don't is a problem of the vars, instead can be bugs in some other part of the program and this show it, so fix that don't will fix the base problem, some examples, i found this types of problems:

  - overflows
    - is trying to set negative val to an unsigned var
    - the var don't support the length
    - some value assignations or operations with excessive big numbers
  - negative shift
  - misaligned address 
  - invalid type assignment
  - division by zero
  - null pointers
  - address don't point to a right object type

i think i can try and research with some of this when i found some type of fix or experimental fix i'll send a pr, but, there us a lot of points i don't know what do with it, i don't have the knowledge to work on it, like:

```
/home/pipe/Documentos/git/ppsspp/ext/native/ext/cityhash/city.cpp:296:36: runtime error: unsigned integer overflow: 10909143366566412288 + 11160318154099408983 cannot be represented in type 'unsigned long'
```
or this, it belongs to ppsspp code:
```
/home/pipe/Documentos/git/ppsspp/Core/CoreTiming.cpp:240:26: runtime error: unsigned integer overflow: 135213 + 18446744073709551615 cannot be represented in type 'unsigned long long'
```

That is an exessive big number, c++ don't have a type to can represent that...

For this reason is hard to me fix this..., i still think this probably don't is a bug in the var, can have other things behind it.
do you prefer if i upload a file with the list of bugs i found?

And, can you recommend me some doc related with this bugs to read please?

Thx. Cya.

**Comment by latot** [comment]
Note, fsanitize of clang seems is very very bug, there was a lot of false positives, so using gcc version seems works better, (tested in clang-3.7.1)

**Comment by Orphis** [comment]
That's because you use an old clang.
Clang is always better for sanitizers, and if there's an issue, it's often true (but effects might be benign and controlled). No care has been taken to make sure everything works with them, so you shouldn't try them probably!

**Comment by latot** [comment]
Hi, the type of bug i found for example is in the overflows, there was operations like ```-1 + 2``` and is say  was an overflow with ```65535 + 2```, basically the overflow shown is different from the value executed in  code..., but i can try update clang and llvm, Thx.

**Comment by Orphis** [comment]
It's not a bug, it's undefined behavior in C++, but it is defined within the compilers we use. So that's fine.

**Comment by latot** [comment]
..?, i think that should not be a undefined behavior, plus that numbers i think is fine and the result is positive and if the bug is right is little hard to work on it if clang show other values instead of the used in the executable (we always can use gdb), anyway, before continuing this lets wait when i can update clang to 3.9 (compiling), and then lets se how works.

Thx.

**Comment by latot** [comment]
Hi, now i'm sure, 99% probable was bugs in clang-3.7, now with 3.9 the output of sanitize match with gcc and all the weird messages where i can't found problems is gone, so updating was the solution!

Thx. Cya.

**Comment by latot** [comment]
let me check something..

**Comment by latot** [comment]
mm, i found other issue, anyway that goes to other place, the log change a lot, so, lets start this again..
