### ISSUE TITLE
Appimage request

### ISSUE THREAD

**Issue by Sunderland93** [hrydgard/ppsspp#9154]
It would be great, if you'll provide Appimage-package that run on any Linux distribution https://github.com/probonopd/AppImageKit
Please, make it!

**Comment by Sunderland93** [comment]
I prepared a simple recipe for build Appimage-package of PPSSPP-SDL. It uses Trusty PPA, simply put it converts deb-packages from PPA to Appimage. Tested on Ubuntu 14.04-16.10, Debian 8-testing and Fedora 25.

https://gist.github.com/Sunderland93/df7a509d7ed049204038bb243889f127#file-ppsspp-sdl_appimage-sh

**Comment by probonopd** [comment]
Also see https://github.com/probonopd/AppImages/pull/157

**Comment by unknownbrackets** [comment]
Since AppImage/AppImages#157 is still open after almost 2 years with no feedback, I'm going to close this.

-[Unknown]

**Comment by probonopd** [comment]
I answered almost 2 years ago. I got the AppImage running in no time, but found the error messages confusing (no real GUI telling me what to do and how to get "homebrew games in the memstick directory structure".

https://github.com/AppImage/AppImages/pull/157#issuecomment-266275615

So I think the AppImage part itself is solved, the rest is a bit of UX polishing in the app itself, no? If you need further assistance, I'm happy to help. (But don't assume I know ppsspp or anything gaming related, for that matter.)

**Comment by JimScript** [comment]
I know this is 4 years old, but why was this closed? There is no Appimage to download officially yet like RPCS3 or PCSX2, you still have to use an unofficial Flatpak to get the Linux version without building it yourself, along with the fact you can't change your memstick folder makes it a pain to use.

**Comment by probonopd** [comment]
https://github.com/RPCS3/rpcs3-binaries-linux/releases has an RPCS3 AppImage. It looks official to me.

**Comment by JimScript** [comment]
As does PCSX2 and Duckstation, PPSSPP is the only Playstation emulator without an official Appimage, and that make me sad.

**Comment by unknownbrackets** [comment]
Well, it was closed because apparently the maintainers of the AppImage repo didn't want to merge something someone did.  If you want this to change, the best way is to push on it yourself.  PPSSPP is on Brew and various other places, and all of these are because some interpid person (such as yourself) did the work to make it available.

I'm sure RPCS3 is just as easy/hard to run homebrew with, so I guess maybe the unwillingness from 2016 might've changed.  Or not.  Since you're really passionate about AppImage, and probably know more about it than me (I know about as much as this issue existing), sounds like you're the best qualified person to make this happen.

-[Unknown]

**Comment by JimScript** [comment]
Unfortunately, my only experience with Linux is the Steam Deck I got, I like the Appimages because of the ease of use they provide. If I can't do it, then maybe this issue should be open to keep the prospect out there for someone who can.

**Comment by LunaMoo** [comment]
I don't see the point of re-opening, the work was already done by someone like 6 years ago, the fact it's not merged by appimage maintainers is not a PPSSPP problem and really can't be solved by further discussions in here. Any future questions regarding when it will happen should go directly to https://github.com/AppImage/pkg2appimage/pull/157 as that's the only place it can happen.

 Many years ago I thought "linux" is like a paradise of open world programming, but with time it seems it's more of a hell with millions of distributions and thousands of projects failing at dealing with it, with sure, lots of programmers, but mostly behaving like their way is the only proper way.

**Comment by Miguel-hrvs** [comment]
I would like to post my unofficial release if someone wants a ppsspp appimage: https://gitlab.com/Miguel-hrvs/ppsspp-appimage/-/releases
