### ISSUE TITLE
Windows low, medium, high, ultra

### ISSUE THREAD

**Issue by moura464** [hrydgard/ppsspp#9155]
GameSettingsScreen.h error ???????

const HRESULT result = SHGetFolderPath(NULL, CSIDL_PERSONAL, NULL, SHGFP_TYPE_CURRENT, myDocumentsPath);

GameSettingsScreen.cpp    OK

static const char *latency[] = { "Low", "Medium", "High", "ultra" };

**Comment by Margen67** [comment]
Stop opening useless issues. #9132

**Comment by hrydgard** [comment]
Yeah, what?
