### ISSUE TITLE
Request: Add savedata synchronization between platforms

### ISSUE THREAD

**Issue by andreyorst** [hrydgard/ppsspp#9156]
Well, this might be **silly**, but yesterday i came with idea of synchronization your savedata files between platforms. As PPSSPP user on PC and Android, i play several games on each one, but some of the games i have on both PC and Android. So i transfer my savedata files between platforms via usb to continue playing on PC when i came home and when i leave home to play while i'm on the go to my work. But transferring via usb is not suitable enough, so synchronization will be great solution. 

This idea came to me earlier when i saw Nintendo Switch console which allows you to play games on your TV when you at home, and you just unplug console from dock and play on the go. Of Course this can't be done as it is, but i believe save synchronisation can give closest experience.

**Comment by hrydgard** [comment]
Yeah, this idea has been around for some time: https://github.com/hrydgard/ppsspp/issues/1019

Still haven't gotten around to it unfortunately...
