### ISSUE TITLE
Xcode Project

### ISSUE THREAD

**Issue by kajinka13** [hrydgard/ppsspp#9158]
There is the possibility of using xcode for this project? currently I can only get the .app, but I would like to use Xcode, perhaps for debugging. Can you show me how to proceed?

**Comment by hrydgard** [comment]
You can use CMake to generate an XCode project. See instructions at https://github.com/hrydgard/ppsspp/wiki/Build-instructions .

**Comment by DarkLegend481** [comment]
If you get the .xcodeproj folder. Please, sent me. I want make a UWP Application...

**Comment by hrydgard** [comment]
Follow the instructions and make it yourself.

Either way, this is the wrong way to make UWP. I am planning a native port but it will take some time.

**Comment by DarkLegend481** [comment]
I learned, if you have the .xcodeproj folder, WinObjC and UWP Extensions to Visual Studio, you can make a UWP Version of that project... I'm not disagreeing, just commenting on what I know...

**Comment by DarkLegend481** [comment]
Or if you have the x32 desktop version of an app or installer, you can convert it into UWP...

**Comment by hrydgard** [comment]
Well, that's good to know. The result is still a slow mess, and I'm going to do it properly, by adding a DX11 backend. Stay tuned (it'll take a while though).

**Comment by DarkLegend481** [comment]
The DX11 backend it's for Windows 10 Mobile users, huh?

**Comment by hrydgard** [comment]
And for proper UWP support. And XBox One, I suppose...

**Comment by DarkLegend481** [comment]
If ain't wrong, Xbox One uses OpenGL (https://www.youtube.com/watch?v=BAXMZAYXNF8) and DX11...

**Comment by DarkLegend481** [comment]
WinPSPe (on video) haves audio problems. Any project for audio fix? Plugins like DirectSound?

**Comment by hrydgard** [comment]
In the video the audio problems are just from running too slow.

**Comment by DarkLegend481** [comment]
Oh, okay. I'm thinking... If you use the iOS icons for tiles and splash screen?

**Comment by DarkLegend481** [comment]
JIT is new for Windows 10-based plataforms (Xbox One and Lumia phones), maybe, only for now, they needed to use ANGLE to convert OpenGL into Direct3D11.
