### ISSUE TITLE
UWP Port of PPSSPP: WinPSPe

### ISSUE THREAD

**Issue by DarkLegend481** [hrydgard/ppsspp#9159]
Hi!

This emulator is not mine, I found it on the Windows Store and decided to talk about him here.

Here are my screenshots:

![wp_ss_20161211_0001](https://cloud.githubusercontent.com/assets/22161127/21079946/226895ae-bf89-11e6-921a-6a070f2ae117.png)

![wp_ss_20161211_0002](https://cloud.githubusercontent.com/assets/22161127/21079991/982733e4-bf8a-11e6-8f40-eb6bdade24f7.png)

![wp_ss_20161211_0003](https://cloud.githubusercontent.com/assets/22161127/21079994/c60a189e-bf8a-11e6-83fa-9799b0758ec8.png)

**Comment by hrydgard** [comment]
Sigh, I guess that's not a surprise... Need to get around to doing an official UWP port.

They're violating the GPL though by not publishing the source.

**Comment by DarkLegend481** [comment]
Only a question, the WinPSPe needs to be free? Or can continuing be paid? (I am Brazilian, my English it's so bad...)

**Comment by hrydgard** [comment]
They need to release the source code of their changes. Can't prevent them from selling it.

**Comment by DarkLegend481** [comment]
Probably, they used Project Centennial to convert a 32-bit of PPSSPP. But, how they make GIT works on Windows 10 Mobile?

**Comment by DarkLegend481** [comment]
Or used the iOS UWP Bridge...
