### ISSUE TITLE
How do i create a pull request ?

### ISSUE THREAD

**Issue by zminhquanz** [hrydgard/ppsspp#9161]
How do i pull requests and up build version , i'm writing code and build ppsspp is success but i can't sync pull requests . I'm a new developer

**Comment by hrydgard** [comment]
You push changes to a branch in your own fork of the repo, then a button will show up on github that lets you make a pull request of the branch. 

https://help.github.com/articles/creating-a-pull-request-from-a-fork/ 

or google for simpler tutorials. This is not an issue in PPSSPP, so I'm closing.
