### ISSUE TITLE
Menu and controls glitch after minimizing

### ISSUE THREAD

**Issue by andreyorst** [hrydgard/ppsspp#9162]
**Device:** Nexus 5X
**OS:** Android 7.1.1
**PPSSPP Version:** 1.3.0.1

I didn't close ppsspp, just returned to homescreen, and ppsspp was still in background. Then i left my phone for a while launched several apps, and when i opened ppsspp again, i saw this. Relaunched emulator, and tried again - reproduces.

Steps to reproduce:
1. Open a game;
2. Go back to emulator game menu;
3. Go home;
4. Open several applications;
5. Open ppsspp (from desktop icon).

**Update** You don't even need to open another app, just minimize emulator while in game menu.
![image](https://cloud.githubusercontent.com/assets/19470159/21188240/c3c3adc2-c22b-11e6-9578-fecb84be0e30.png)
![image](https://cloud.githubusercontent.com/assets/19470159/21188246/c7a77bd0-c22b-11e6-9ac3-592d254adbeb.png)
![image](https://cloud.githubusercontent.com/assets/19470159/21188251/cc845524-c22b-11e6-92be-d620cd4034c0.png)

**Comment by blackman91** [comment]
Can confirm, happens on android 4.2.2 and 4.4 too.

**Comment by andreyorst** [comment]
Any response? I do minimize ppsspp a lot while playing, and this bug forces me to do a save state, then relaunch ppsspp and load that savestate, which is annoying. Still happens on Android 7.1.2

**Comment by hrydgard** [comment]
Like #9295, I'll look at this soon, just busy with D3D11 now.

**Comment by blackman91** [comment]
Just tested on android lolipop and marshmallow devices and this bug happens too.

**Comment by unknownbrackets** [comment]
Does this still happen?

-[Unknown]

**Comment by hrydgard** [comment]
Likely to have been resolved with my redone Android GL reinit code. Closing, please reopen if needed.
