### ISSUE TITLE
Ppsspp uwp port is now running. But...

### ISSUE THREAD

**Issue by alanmcj** [hrydgard/ppsspp#9164]
It is not playable for now, maybe in a future update.
![wp_ss_20161215_0006](https://cloud.githubusercontent.com/assets/24596988/21246566/b9ab56c4-c310-11e6-81a4-38d5b528c7da.png)
![wp_ss_20161215_0004](https://cloud.githubusercontent.com/assets/24596988/21246565/b9a3aba4-c310-11e6-9d6b-3e946fd63930.png)

**Comment by alanmcj** [comment]
![wp_ss_20161215_0007](https://cloud.githubusercontent.com/assets/24596988/21246800/255a9780-c312-11e6-9749-c092f103a531.png)

**Comment by DarkLegend481** [comment]
Hey, can you send the .appx file of WinPSPe? I want to test the emulator on my Nokia Lumia 635. Thanks.

**Comment by Bigpet** [comment]
@DarkLegend481 this looks like a version compiled with the iOS bridge. Not sure this is the same thing that's in the store.

**Comment by DarkLegend481** [comment]
But, the Windows version haves the touch inputs. For me looks like the Windows version, not from an iOS Device.

**Comment by DarkLegend481** [comment]
And, it's running on an Windows PC. I asked the .appx file for test on a Lumia 635.

**Comment by hrydgard** [comment]
Yeah I'm really confused as to what this is. 

The right way is to do a D3D11 backend and a proper port in general, not whatever hackery they've done...

**Comment by alanmcj** [comment]
lumia 635 it will not run because of low ram memory (512 ram), I'm testing on lumia 1520 (2gb ram)

**Comment by alanmcj** [comment]
http://www.mediafire.com/?1dcj0yao6kl976t

**Comment by alanmcj** [comment]
i left the link of appx file for testing

**Comment by zminhquanz** [comment]
@hrydgard you can to quick to contribute official UWP port

**Comment by alanmcj** [comment]
Ppsspp on Xbox one

https://m.youtube.com/watch?v=BAXMZAYXNF8

**Comment by DarkLegend481** [comment]
I tested the emu with Cave Story, with the fastest settings, when I open the game, the emulator crashes...

**Comment by hrydgard** [comment]
I plan to do a proper UWP port in the future. Don't hold your breath though, it'll be a while.

**Comment by DarkLegend481** [comment]
Hey, I can install it on Xbox One? My parents give me one (Christmas)...

**Comment by pjacket** [comment]
#9164

**Comment by hrydgard** [comment]
Maybe you can, but I'd recommend waiting for the official UWP port :)

**Comment by DarkLegend481** [comment]
If this .zip was a .appx, I can develop it using Device Portal...

**Comment by DarkLegend481** [comment]
Hey, now this UWP it's working on 512MB RAM??
