### ISSUE TITLE
Tekken 6 - Network Menu Problem

### ISSUE THREAD

**Issue by Orlha** [hrydgard/ppsspp#9170]
Tried to play Tekken 6 with to PC's via LAN.
Installed PPSSPP version 1.3 and played a bit. However, when I try to go back to main menu - I just stack in battle lobby forever. It would not be a problem, but all multiplayer statistics, winrate, acquired money and stuff are lost forever, because game saves all the data to memory stick in main menu and you can't get back there.

You don't even need to play multiplayer game to get this bug, you can just enter a battle lobby and then press "back". Now you stuck here and have to restart the game.

Then I tried version 1.2.2 and 1.1.1 and problem still here.
However, it seems like it works with version 0.9.9.1 which is very outdated one (and where "Enable networking" is not marked as beta). So, problem appeared somewhere after version 0.9.9.1

Would be happy to see it fixed.

**Comment by InusualZ** [comment]
The author, recently pushed a PR related to this. You may want to download the development build and test it with the game

**Comment by Orlha** [comment]
Just tested "v1.3-202-g2cf3f02" from this page: http://www.ppsspp.org/downloads.html
Problem still here.

**Comment by adenovan** [comment]
latest build log, doesn't know what is happening.
![image](https://cloud.githubusercontent.com/assets/5246143/21451698/f55fc372-c93b-11e6-983b-e12637bb9842.png)

that bad object handle didn't present on ppsspp 0.9.9.1 and below log.

**Comment by adenovan** [comment]
force returning on sceNetAdhocTerm() will exit the menu succesfully , but we have another problem if it forced return , it cant reconnect to battle lobby nor playing the battle because there is some block allocator fail. if the dummy thread hack address is not initialized the game can process normally. its a cleanup problem

`return SCE_KERNEL_ERROR_LWMUTEX_NOT_FOUND;`

**Comment by adenovan** [comment]
im hacking the retun 0 to return SCE_KERNEL_ERROR_LWMUTEX_NOT_FOUND; the game only call it once but expect twice behavior. something weird there

**Comment by GabbyAnims** [comment]
I managed to fix it a few days ago  I just played with the network settings(WLAN switch, adhoc), etc) in the ppsspp. I'm currently using 1.9.4. But after days of not playing multiplayer mode i forgot how to fix it. Right now I'm trying to figure out how to fix it again but it doesn't work much. Any help would be appreciated.

**Comment by ANR2ME** [comment]
> 
> 
> really old post and I don't really know if its fixed or not
> I managed to fix it a few days ago I just played with the network settings(WLAN switch, adhoc), etc) in the ppsspp. I'm currently using 1.9.4. But after days of not playing multiplayer mode i forgot how to fix it. Right now I'm trying to figure out how to fix it again but it doesn't work much. Any help would be appreciated.

As i remembered the latest one at https://buildbot.orphis.net/ppsspp/ no longer stuck

**Comment by unknownbrackets** [comment]
Okay, going to close this then.  If it's still happening, reply and we can reopen.

-[Unknown]
