### ISSUE TITLE
Attemp to build for wrong architecture

### ISSUE THREAD

**Issue by thesourcehim** [hrydgard/ppsspp#9174]
I'm trying to build ppsspp on Fedora 25 x86_64 machine using b.sh script. Somehow it tries to build ppsspp for armmips:
CMake Error at ext/cmake/armips/CMakeLists.txt:11 (add_library):
  Cannot find source file:

    ../../armips/ext/tinyformat/tinyformat.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error: Cannot determine link language for target "armips".
CMake Error: CMake can not determine linker language for target: armips

**Comment by thesourcehim** [comment]
Bisect results:

46fdc0f5f5212c806bee984db11ed0f5f4b99611 is the first bad commit
commit 46fdc0f5f5212c806bee984db11ed0f5f4b99611
Author: Florent Castelli <florent.castelli@gmail.com>
Date:   Sun Dec 18 19:01:05 2016 +0100

    cmake: Move some cmake includes to ext

:100644 100644 39318dd94b1f33725cc542fb5fa2a895351c3282 909b897993a314227e728a0f6ef24e167e25e9c9 M      CMakeLists.txt
:040000 040000 b0d0eb850016ad1b3ab147d3bee6533cc80243cf 80d124054cea2d4e210e2ff5c0bfb839187d9e83 M      Common
:040000 040000 e468745d398abdea204c47bbe7e3c4f29b25fb97 04cb160b640f7027e289f25516bfe554dac1c4f0 M      Core
:040000 040000 edc57679844de21b3114860e9ae81788dc792aee 814e89f4bc8646c6b538e3323115e8524308389a M      GPU
:040000 040000 d25c1216a76cf98b762283013b7ac9f99d405145 a6965b672a43215144e32c9f509faa490274230a M      UI
:040000 040000 0d3adde4eeb8e52db0b718424a40d9d4b34f50a0 3515fba843fa3cba693545cfeca044f8a5f5493e M      android
:040000 040000 73f7183f96b0f9c640f373d739a6c07077e05b64 f48d19d237f49246943e83cee2da1c8efb637c19 M      cmake
:040000 040000 cd25fbd025b49bafe9d37aff8cf9b90c04f5df04 f00ff468d20d208d8e8b6f9ea6bdc3fe7d9f1437 M      ext

**Comment by Orphis** [comment]
git submodule update --init --recursive
When you have such a message from CMake, it means the file is missing, in this case because you didn't get the submodule of the submodule.
