### ISSUE TITLE
ffmpeg for aarch64

### ISSUE THREAD

**Issue by joolswills** [hrydgard/ppsspp#9177]
Building on ODroid-C2 (Ubuntu 16.04 / aarch64), I had to make a small adjustment to CMakeLists.txt

I first compiled ffmpeg to "ffmpeg/linux/arm64" and made this change

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 299681c..41b971e 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -405,6 +405,8 @@ if(USE_FFMPEG)
           set(PLATFORM_ARCH "linux/armv7")
         elseif(ARM)
           set(PLATFORM_ARCH "linux/arm")
+        elseif(ARM64)
+          set(PLATFORM_ARCH "linux/arm64")
         elseif(MIPS)
           set(PLATFORM_ARCH "linux/mips32")
         elseif(CMAKE_SIZEOF_VOID_P EQUAL 8)

```

Is this something you would include ? Probably should include a ffmpeg build script for aarch64. I can do a PR, but do you prefer linux/arm64 or linux/aarch64 for the folder. Should I include a prebuilt ffmpeg in the PR ?

**Comment by Orphis** [comment]
So, the ffmpeg binaries are in a submodule, so you'll have to submit the PR there first.
I've started refactoring the build scripts, so it would be great if you could do something like the mac and iOS ones that load the shared-options.sh and adjust whatever is needed then for the platform.

Then, the change above should be easy to integrated, though it's probably better to name it aarch64 as it is the traditionnal name on Linux!

**Comment by hrydgard** [comment]
Just to be clear, here's where you should submit that change: https://github.com/hrydgard/ppsspp-ffmpeg

**Comment by joolswills** [comment]
thanks.

**Comment by substring** [comment]
@joolswills hey just pushed https://github.com/hrydgard/ppsspp-ffmpeg/pull/44
Works fine on recalbox for C2 as it was my testing device, wanna give a try on retropie ?
