### ISSUE TITLE
Project (Play!) is ps2 emu for all platforms. Including (android , iOS) need your help please.

### ISSUE THREAD

**Issue by Fadi5555** [hrydgard/ppsspp#9181]
Well first of all I would to thank you for this amazing project I really like it And using it daily.

Anyway this project as I said it's calld (Play!). It's ps2 emu for windows , MacOS , linux , iOS , android.
The creator of this project is called @jpd002 for long time he work on his project alone so that's why the project is slightly getting improve. Of course because of his work alone. So that's why we need you to help him on his project please. All of us dreaming to could play ps2 games on go like on android and iOS devices. We'll be very thankful for your help and appreciate a lot.

This is his link of his project:
https://github.com/jpd002/Play-

And this is an official thread talk about need people for help if you want to join or say something here:
https://github.com/jpd002/Play-/issues/503

And this is a screenshot of play! On my iPad Air 2 running resident evil 4:
![image](https://cloud.githubusercontent.com/assets/10546081/21419273/c321999e-c837-11e6-82cb-cce66e9f80c9.png)
![image](https://cloud.githubusercontent.com/assets/10546081/21419274/c362b0f0-c837-11e6-8a46-2af1ec6c1d38.png)

I'm sure you'll help him to improve it further more.
Thanks a lot for your kindness.

**Comment by hrydgard** [comment]
I'm sure it's a great project, but this issue tracker is for PPSSPP problems. I wish I had time to contribute to more emulators but I really don't.
