### ISSUE TITLE
F1 2006 eur ( UCES00238 ) crash in-game 

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#9185]
First I need set "simulate UMD delay" to fix crash in beginning,then in-game crash

v1.3-241-g92db2b0 log:
https://drive.google.com/file/d/0B3OaSdeV0L8kRm5FTlhiTm1XTVk/view?usp=sharing

crash struce

	PPSSPPDebug64.exe!SasInstance::MixVoice(SasVoice & voice) Line 536	C++
 	PPSSPPDebug64.exe!SasInstance::Mix(unsigned int outAddr, unsigned int inAddr, int leftVol, int rightVol) Line 560	C++
 	PPSSPPDebug64.exe!__SasThread() Line 111	C++
 	PPSSPPDebug64.exe!std::thread::Func<int (__cdecl*)(void)>::Run() Line 245	C++
 	PPSSPPDebug64.exe!std::thread::RunAndDelete<std::thread::Func<int (__cdecl*)(void)> >(void * param) Line 286	C++
 	PPSSPPDebug64.exe!invoke_thread_procedure(unsigned int(*)(void *) procedure, void * const context) Line 92	C++
 	PPSSPPDebug64.exe!thread_start<unsigned int (__cdecl*)(void * __ptr64)>(void * const parameter) Line 115	C++

 	[External Code]	

![1](https://cloud.githubusercontent.com/assets/2177532/21470787/53cffb6e-cad3-11e6-9363-234215fc5316.png)
![2](https://cloud.githubusercontent.com/assets/2177532/21470789/583592a4-cad3-11e6-9ceb-110a3a3449be.png)

**Comment by sum2012** [comment]
Hmm 

Good
v1.3-7-g175f331

bad
v1.3-250-g33b3330

**Comment by sum2012** [comment]
good
v1.3-215-ge9bea75
bad
v1.3-224-g8222a66
it mean #8950

**Comment by sum2012** [comment]
@hrydgard 
I cannot test further becuase ext/glslang sub module has removed
![2](https://cloud.githubusercontent.com/assets/2177532/21500215/9e15feb2-cc77-11e6-9d25-82487704a961.png)

**Comment by hrydgard** [comment]
Oh, yeah, we switched the repo we sync glslang from. To fix that, just rm -rf ext/glslang and git submodule update --init.

**Comment by hrydgard** [comment]
Anyway, I think my latest commit may have fixed this. Please try again.

**Comment by Orphis** [comment]
No! "git submodule sync" is the right command :p

**Comment by sum2012** [comment]
I open another issue.Closing
