### ISSUE TITLE
Cannot run PPSSPP on iOS developer account (64-bit issue)

### ISSUE THREAD

**Issue by blueneogeo** [hrydgard/ppsspp#9188]
I am an Apple registered  iOS developer and I was able to compile, install and run PPSSPP on an iPad before, but lately I can run PPSSPP, however opening a .CSO will give me an EXC_BAD_ACCESS exception.

I figured this might be JIT related so in settings I switched to interpreted, but I still get the error. I tried changing the signatures as well, as well as setting them myself per project... but all with the same result.

<img width="962" alt="screen shot 2016-12-26 at 19 08 21" src="https://cloud.githubusercontent.com/assets/832382/21485282/2a19d910-cba1-11e6-8a58-e8d024798dcd.png">

**Comment by blueneogeo** [comment]
Update, commit aa964ea2e53686f95422de9f17f43747e2d65b21 from december 9 does work.

Found this information here: http://forums.ppsspp.org/showthread.php?tid=22143

**Comment by Orphis** [comment]
It would be great if you could bisect the changes and find the faulty change!
Also, what iPad do you have? Is it an armv7 or arm64 one?

**Comment by hrydgard** [comment]
If that fails, we probably failed to allocated the memory we need for RAM, or otherwise setting up the memory map, otherwise that shouldn't fail.

By looking at the pointers, we can tell that this is a 64-bit build, which is new for iOS and probably simply needs some fixes to work as we haven't enabled such builds until recently.

If you can tell CMake to generate a 32-bit project for you, things should work.

**Comment by blueneogeo** [comment]
I will try the next versions to see where it breaks.

I have an iPad Pro 9.7 inch.

**Comment by blueneogeo** [comment]
Hi, I've been testing every version upwards until it broke.

9d7983eee821a034e7e6947ea9512c851aafd3b9 (Remove the ability to turn off prescaleUV entirely. It's simply better to do it in the vertex decoder.) on dec 20 was the last version that worked for me.

1dbeca0618966f4c8156d81e5b25d40f9f8b89e0 (Only support decoding UV to float in vertex formats. Supporting u8 and 16 was more complexity than it's worth) and upwards stopped working. So that commit seems to be the culprit.

Ps, can you tell me how I tell CMake to generate a 32 bit project? Is there a parameter I can pass to "cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/Toolchains/ios.cmake -GXcode .." that makes it generate the project for 32 bit?

**Comment by hrydgard** [comment]
Oh! That's really interesting and a good clue. I'll look into this.

**Comment by Orphis** [comment]
It will build for both armv7 and arm64. Your iPhone should be able to use the right version automatically.
You can probably also pass -DIOS_ARCH=armv7 to force it to one arch, or just make a local change to the toolchain if that doesn't work (it should work).

**Comment by blueneogeo** [comment]
I tried the -DIOS_ARCH=armv7 parameter but that did not seem to change my build settings, so I changed them in the project like this:

![screen shot 2017-01-09 at 18 54 24](https://cloud.githubusercontent.com/assets/832382/21776928/1aa1d396-d69d-11e6-87d8-e8f714e96450.png)

However, when testing, I still got this error:

![screen shot 2017-01-09 at 18 54 24](https://cloud.githubusercontent.com/assets/832382/21776986/41a49424-d69d-11e6-9fde-fd83fc0df8ca.png)

Perhaps this is not just an ARM64 problem?

**Comment by blueneogeo** [comment]
I see in the git change log that on dec 20th two changes were made to VertexDecoder, could that be connected? This is in that same 1dbeca0618966f4c8156d81e5b25d40f9f8b89e0 commit after all...

**Comment by Orphis** [comment]
Well, that is an armv7 build you are running already, so sure, it won't be different.

**Comment by blueneogeo** [comment]
Hi Orphis, I understood that the iPad Pro was automatically picking the arm64 version since it has a 64 bit processor, and that that was what crashed PPSSPP.

So to solve that, I tried to force the build to use armv7 only.

Am I missing something obvious? Thank you for your help.

**Comment by Orphis** [comment]
Well, the pointers in your screenshot seems to be 32bit, so you are probably using armv7 already.
It's probably some other issue.

**Comment by hrydgard** [comment]
This is fixed now, although the 64-bit JIT still doesn't work so avoid that.
