### ISSUE TITLE
Tactics orge on powervr is Pixelated/Blocky 2D in-battle sprites ( regression)

### ISSUE THREAD

**Issue by zminhquanz** [hrydgard/ppsspp#9189]
![screenshot_2016-12-26-20-26-52](https://cloud.githubusercontent.com/assets/11285640/21487664/82b99df2-cc01-11e6-8a46-dfab3a161c29.jpg)
![screenshot_2016-12-26-20-26-48](https://cloud.githubusercontent.com/assets/11285640/21487665/82c21b4e-cc01-11e6-8427-c8085a50b267.jpg)
![screenshot_2016-12-26-20-26-44](https://cloud.githubusercontent.com/assets/11285640/21487666/82d12c6a-cc01-11e6-95b0-eb3e5f305696.jpg)
i choose to render resolution 2x and upscale 2x, and the blurred not fix on powervr

**Comment by hrydgard** [comment]
I think we've seen this before, some weird texture coordinate precision issue... seems to only affect PowerVR indeed.

**Comment by zminhquanz** [comment]
And this game even on PC Windows , sometimes it's slow down

**Comment by zminhquanz** [comment]
Regression from #7150 , bug is appear again on 1.3.0.1 @hrydgard

**Comment by zminhquanz** [comment]
@hrydgard you can mention this issue

**Comment by lokifrit** [comment]
was the pixelated issue for Tactics Ogre fixed? im using Asus zenfone 5, set to buffered rendering. When i switch to Read Frame Buffers to mem (GPU) the pixelated issue is gone, but it is slow

**Comment by zminhquanz** [comment]
@lokifrit is doesn't fixed that , i think it's a regression

**Comment by lokifrit** [comment]
what do you mean by regression? sorry for my ignorance

**Comment by hrydgard** [comment]
regression means that something got worse since the last release, for example.

**Comment by lokifrit** [comment]
oh okay. i tried versions 1.3 and 0.9. I noticed that final fantasy tactics has the same behavior.

**Comment by hrydgard** [comment]
I believe the issue is that the game has a texture matrix enabled, which cause us to perform texture projection (including division), which unfortunately works horribly badly on older PowerVR due to a lack of precision in fragment shader calculations. I don't think the division is actually required, so one way might be to hack around it, another to detect in the texture matrix that no projection will be needed. I think I might try the second..

**Comment by lokifrit** [comment]
is there any other phone model that doesn't have this problem?

**Comment by hrydgard** [comment]
Yeah, nearly all of them.

**Comment by lokifrit** [comment]
@hrydgard so this only happens to older phones?

**Comment by hrydgard** [comment]
Yes, older PowerVR-based phones. Haven't seen or heard about it happening in any others.

**Comment by hrydgard** [comment]
Merged the fix (although I haven't actually reproduced the issue, only verified that things still work). Please re-open if issue remains in future builds.

**Comment by zminhquanz** [comment]
@hrydgard it seems regression , i update 1.4 on ASUS Zenfone , it still doesn't fix

**Comment by hrydgard** [comment]
This still happens on 1.4? Does it still look like the screenshot at the top of this thread?

**Comment by zminhquanz** [comment]
Yes it does , there is have the same issue , blocky vs pixelate graphics
![screenshot_2017-04-05-17-55-29 1](https://cloud.githubusercontent.com/assets/11285640/24702600/a1c6ce56-1a29-11e7-8f18-5428a2302daf.jpg)
![screenshot_2017-04-05-17-55-52 1](https://cloud.githubusercontent.com/assets/11285640/24702602/a52b7808-1a29-11e7-8f39-c3ed5e1e74e8.jpg)

**Comment by hrydgard** [comment]
Hm, surprising, I thought I fixed the cause ... Apparently not. Thanks for letting me know.

**Comment by hrydgard** [comment]
Gonna guess this still happens on the latest build?
