### ISSUE TITLE
Final Fantasy VII Crisis Core crash in-game

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#9190]
v1.3-248-g619f918 log:
https://drive.google.com/file/d/0B3OaSdeV0L8kWFJ1eWJtNVFRSVU/view?usp=sharing
crash strace:

	PPSSPPDebug64.exe!SasInstance::MixVoice(SasVoice & voice) Line 509	C++
 	[External Code]	
 	PPSSPPDebug64.exe!thread_start<unsigned int (__cdecl*)(void * __ptr64)>(void * const parameter) Line 115	C++
 	[External Code]	

![1](https://cloud.githubusercontent.com/assets/2177532/21495226/3834ba64-cc51-11e6-814f-92b5bc36b0b2.png)

**Comment by hrydgard** [comment]
yup, this was caused by my linear resampling thing. Will investigate.

**Comment by hrydgard** [comment]
By the way, where in the game is this? Is it close to the start, or do you have a save? I lost my save so I just started over and it's not happening yet.

**Comment by sum2012** [comment]
It is reported by baidu forum by someone
It is in ch 4
save satus:
https://drive.google.com/file/d/0B3OaSdeV0L8kQWN6MkVrWFdfZzQ/view?usp=sharing

**Comment by sum2012** [comment]
https://github.com/hrydgard/ppsspp/commit/88ad1cb3d8925dce2e2b3364ab5cab561262e07a not fix
![2](https://cloud.githubusercontent.com/assets/2177532/21498709/1058c5d0-cc6a-11e6-8f9a-31342416bcf9.png)

**Comment by sum2012** [comment]
Sorry,I forget mention it is tested by a chinese patch

**Comment by sum2012** [comment]
Game save by reporter
https://drive.google.com/file/d/0B3OaSdeV0L8kaGdxYy0wb3d3NDQ/view?usp=sharing
He reported that he use ~v1.2.2-258 andvoid version can pass that crash

**Comment by hrydgard** [comment]
Did this solve it? 
https://github.com/hrydgard/ppsspp/commit/88ad1cb3d8925dce2e2b3364ab5cab561262e07a

**Comment by sum2012** [comment]
No ,https://github.com/hrydgard/ppsspp/commit/88ad1cb3d8925dce2e2b3364ab5cab561262e07a didn't solve it

**Comment by hrydgard** [comment]
I got a repro using the save state, even though I had to load it into the wrong region game :) I'll fix it.

**Comment by sum2012** [comment]
Yes,follow that not sure is chinese patch problem
![1](https://cloud.githubusercontent.com/assets/2177532/21510302/b9752e44-cccc-11e6-94c5-0fd2ad85d052.png)

**Comment by hrydgard** [comment]
That should probably be a separate issue, unless it appeared at the same commit.
