### ISSUE TITLE
Build failure after b46bb1efdb77340e424dfdd

### ISSUE THREAD

**Issue by Barthalion** [hrydgard/ppsspp#9191]
I'm unable to build flatpak image after b46bb1efdb77340e424dfdd02d50c59c0876ddc0 commit. Console says:

```-- Install configuration: "Release"
CMake Error at ext/glslang/glslang/cmake_install.cmake:36 (file):
  file cannot create directory: /usr/local/lib.  Maybe need administrative
  privileges.
Call Stack (most recent call first):
  ext/glslang/cmake_install.cmake:38 (include)
  ext/cmake_install.cmake:39 (include)
  cmake_install.cmake:37 (include)```

**Comment by hrydgard** [comment]
Hm, I suppose the install step of the upstream glslang (https://github.com/KhronosGroup/glslang) might do something bad when used as a library.

They are very open to pull requests fixing build issues, so will probably be easy to get one through that adds an option to not install at all, similarly to my previous https://github.com/KhronosGroup/glslang/pull/639 .

**Comment by Barthalion** [comment]
I will follow this tomorrow. Thanks for the pointer.

**Comment by Barthalion** [comment]
After getting some sleep, I guess the real problem is that flatpak attempts to run `make install` unconditionally. I reported it upstream and made a silly workaround locally. I don't think it's common practice to set a variable that disables install target completely.
