### ISSUE TITLE
F1 2006 eur ( UCES00238 ) need simulate UMD delay

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#9193]
otherwise will crash\black screen in beginning

ppsspp-v1.3-276-gad04f97-windows-amd64

Fast (lag on slow storage) (bad) log: https://gist.github.com/sum2012/7b4bd18a70369caa52e8cee7cc82a206
simulate UMD delay (Good) log:
https://gist.github.com/sum2012/552e8fcf5c22d3594245355283fe5632

**Comment by hrydgard** [comment]
I think we need to create a big table of games that are broken by UMD delay and games that are broken with it off. Hopefully we'll figure something out, because it should really be on by default.
