### ISSUE TITLE
Multiple fingers cause buttons to stick

### ISSUE THREAD

**Issue by ProjectWildfire** [hrydgard/ppsspp#9203]
On my device running Android 4.2.2 , pressing 3 buttons on the screen simultaneously can cause all of the pressed buttons to remain pressed even after you stop touching the screen.
Going to settings and back resets the controls back to normal, but the issue still reappears if you do it again. Quite a bother.

**Comment by tausifj15** [comment]
R u rooted

**Comment by tausifj15** [comment]
Or did u have gmd multigesture

**Comment by unknownbrackets** [comment]
This probably only happens on older devices with poor multitouch support.  Since this was reported almost 3 years ago, are people still experiencing this with recent phones?

We may not be able to fix this if it's a hardware limitation.

-[Unknown]

**Comment by hrydgard** [comment]
I keep getting reports of this issue on various devices, it must be some touch shortcut app or system settings that interferes, or just crappy hardware because on most devices there are no such issues.
