### ISSUE TITLE
D3D11 dll missing error message on XP

### ISSUE THREAD

**Issue by Trokinos** [hrydgard/ppsspp#9204]
Hello, on window XP , latest tested build (at the time ppsspp-v1.3-282-g98c7a73 ) when trying to launch will throw a missing D3D11.dll error (as expected as there's no DirectX11 available for old OS), even with no ppsspp.ini setup (if i remember it should default to opengl, not d3d in this case).

Is D3D9 support removed or will it still be available along the apparently planned D3D11 ?

**Comment by hrydgard** [comment]
It will still be available. Adding a hard dependency already was not intentional, I'll fix that up
