### ISSUE TITLE
A version of ppsspp for Windows 10 Mobile

### ISSUE THREAD

**Issue by RosGar** [hrydgard/ppsspp#9206]
Hi people!
I was wondering if exist a version of ppsspp for Windows 10 mobile or if you think to do a new version of app to transform ppsspp for Win10M

**Comment by LunaMoo** [comment]
Closing as duplicate of #7854 please use search before posting. You can also check #8315 which has some early work on the whole Universal Windows Platform that would include windows 10 phones.

 Make note this is an issue tracker not a forum, avoid non dev discussions, questions, bumping and other spam as it just makes it harder to track and solve actual problems.
