### ISSUE TITLE
invalid submodule reference

### ISSUE THREAD

**Issue by yoshi314** [hrydgard/ppsspp#9209]
When updating submodules i get this : 

Fetched in submodule path 'ext/glslang', but it did not contain 807a0d9e2f4e176f75d62ac3c179c81800ec2608. Direct fetching of that commit failed.

**Comment by Bigpet** [comment]
when new submodules get added you need to initialize them first. Try `git submodule update --init --recursive`

**Comment by yoshi314** [comment]
```
Submodule 'ext/tinyformat' (https://github.com/Kingcom/tinyformat) registered for path 'ext/armips/ext/tinyformat'
Cloning into '/mnt/sources/psp/ppsspp/ext/armips/ext/tinyformat'...
Submodule path 'ext/armips/ext/tinyformat': checked out 'b7f5a22753c81d834ab5133d655f1fd525280765'
error: no such remote ref 807a0d9e2f4e176f75d62ac3c179c81800ec2608
Fetched in submodule path 'ext/glslang', but it did not contain 807a0d9e2f4e176f75d62ac3c179c81800ec2608. Direct fetching of that commit failed.

```

**Comment by Bigpet** [comment]
I guess did you fetch from the remotes? `git fetch --recurse-submodules` or `git submodule foreach git fetch` or something to that effect

**Comment by Orphis** [comment]
The submodule changed to a different location.
When you have issues with submodules, you may also need to run "git submodule sync --recursive" and then "git submodule update --init --recursive".

**Comment by yoshi314** [comment]
Ok, i'll try that in a few hours.

**Comment by yoshi314** [comment]
Ok, that seems to have fixed it.
