### ISSUE TITLE
[Regression] Do not apply Texture Scaling to FMVs

### ISSUE THREAD

**Issue by DonelBueno** [hrydgard/ppsspp#9215]
xBRZ scaling doesn't produce good results when scaling FMVs, the performance penalty is also huge, so it should be a good idea not to apply it to FMV textures (I know they can be differentiated from normal textures, right?).

Why do I say "not to apply it to FMV textures" intead of "disabling it when an FMV plays"? Because there are some games that do use FMVs as background menus (Burnout Legends and Burnout Dominator, for example). In those cases, xBRZ is still interestting in HUD elements, so disabling it altogether is not a good idea.

Some comparison shots:

- Burnout Legends Menu (Texture Scaling off, Linear filtering on FMVs on) = constant 400+ FPS at 8x Native resolution

![2- no xbrz](https://cloud.githubusercontent.com/assets/4239694/21958810/ba96b188-da9d-11e6-9c01-e372af9faebe.png)

- Burnout Legends Menu (5x Hybrid + Deposterize Texture Scaling, Linear filtering on FMVs on) = irregular framerate, with drops to 30-40 FPS at 8x Native resolution

![2- xbrz](https://cloud.githubusercontent.com/assets/4239694/21958811/c0dd522c-da9d-11e6-801d-3f855db47433.png)

Related to Issue [9125](https://github.com/hrydgard/ppsspp/issues/9125)

I can confirm that PR #8720 is the culprit and that before it, the emulator worked just like I said it would be optimal. So this is not a feature request, it's regression.

**Comment by LunaMoo** [comment]
It's not "related to", it's the same thing and as such I'm closing this.

 This is issue tracker, it doesn't matter if issues have activity or not, avoid opening duplicates, it will not magically cause people to solve problems, quite the opposite spamming in this place is only making issues harder to track.
