### ISSUE TITLE
Drop Windows XP support?

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#9217]
Windows XP will soon be 16 years old (though yes, SP3 is only 9 years old...).

Keeping support for XP requires us to do ugly hacks to get access to modern Windows features, and makes D3D11 support a pain. 

So are there significant numbers of people still relying on XP support? And if so, could they stay on 1.3? I really would like to drop XP support in 1.4.

**Comment by MarcoEstevez** [comment]
WinXP was an honorable OS, lets remain in peace :+1:

**Comment by Sarkie** [comment]
I always use this

http://store.steampowered.com/hwsurvey

Windows 10 64 bit48.97%+0.60%
Windows 7 64 bit29.02%+0.20%
Windows 8.1 64 bit8.45%-0.14%
Windows 75.23%-0.17%
Windows 101.22%-0.01%
Windows 8 64 bit1.14%-0.05%
Windows XP 32 bit1.14%-0.05%
Windows 8.10.26%-0.01%
Windows Vista 32 bit0.13%-0.01%
Windows 80.10%0.00%
Windows Vista 64 bit0.06%-0.01%

**Comment by zminhquanz** [comment]
if using computer older hardware like Pentium 4 , Windows XP is a best choice , so if you build to using modern API like D3D11 , write code to detected windows version , Win 7 is able to run this , but win xp is gray out , you can't choose this

**Comment by mrcmunir** [comment]
@zminhquanz  The mid laborious problem is other at the level implementations of NT 5.1 vs. 6.0+ some syscalls Microsoft not added support in XP.

* If we update for newer ffmpeg libs has stopped giving support for Windows XP  they added syscalls only in Vista and higher because windows XP doesn't support condition variables .

Its is very frustrating that at the level of Microsoft has left it aside

**Comment by hrydgard** [comment]
@zminhquanz It's possible to still keep it running, yes, but it's extra work. Is it worth it? I'm not sure, but I doubt it at this point.

**Comment by zminhquanz** [comment]
Maybe you can drop support Windows XP , because survey , Windows XP today not using for gaming , but use the Internet , office and learning English , some enterprise , school use Windows XP

**Comment by meepingsnesroms** [comment]
It should be dropped,there are new and free OSes available if you want to run modern programs.(or dual boot XP with Linux)

**Comment by zminhquanz** [comment]
@meepingsnesroms oh , good idea , if you using older PC , you can Install Linux and Remix OS to use PPSSPP , it's better

**Comment by sum2012** [comment]
@hrydgard Can make v1.3.1 is last build of windows XP ?
There are some bug have fixed after v1.3

**Comment by hrydgard** [comment]
Yeah, I might consider to keep 1.4 (which I will name the next version, even if there haven't been really big changes) XP compatible, but that'll probably be the last. Looking to do that release in a few weeks.

**Comment by zminhquanz** [comment]
After release Windows XP compatible version , you can remove D3D9 backend , to be fast to compiler code

**Comment by GamerzHell9137** [comment]
@zminhquanz I think there's stiil a need for DX9 because not all GPUs have support for it but can run PPSSPP just fine.

**Comment by zminhquanz** [comment]
oh , may be , but drop Windows XP support , because today it's buggy OS . About DX9 , some games is higher FPS than OpenGL

**Comment by GamerzHell9137** [comment]
@zminhquanz if DX9 is bound with the XP thing (which i think its not) then i guess they both need to go.

**Comment by hrydgard** [comment]
As mentioned in another thread, we can keep DX9 without any issues, which will probably be useful on older Vista or Win7 laptops.

**Comment by GamerzHell9137** [comment]
Yeah. for a second thought it was weird to drop DX9 because ist pretty much used for forever on every OS.

**Comment by zminhquanz** [comment]
So , you can drop Windows XP , but keep D3D9 backend

**Comment by hrydgard** [comment]
I found a way around this, will probably not need to drop XP anytime soon.

**Comment by Anonymphous** [comment]
Hello there, @hrydgard ,since 1.5 years have passed, I want to ask if DX9 backend is going away anytime soon?

As I understand, that's the only thing forcing to use "Windows XP support for C++" toolset component with Visual Studio, and the DX11 support was added by major VGA card manufacturers somewhere around middle of 2010...

**Comment by hrydgard** [comment]
Even China is mostly Windows 7+ now :) So yeah, it might be time?

**Comment by Degerz** [comment]
Windows XP is still ~10% in China but I still think you should drop the DX9 backend :smile:

Once Vulkan becomes superior to modern desktop OGL in every way, we can consider axing it in 2021 and keep DX11/GLES 3 as the minimum for until 2025 but that's for another topic.

**Comment by unknownbrackets** [comment]
https://go.microsoft.com/fwlink/?linkid=2023588 - sounds like Visual Studio 2019 is expected to drop Windows XP support.

-[Unknown]

**Comment by hrydgard** [comment]
PPSSPP is likely to build on VS2017 for quite some time after 2019 is released, as there aren't really many new compelling features as far as I know, so we can extend XP compat a bit longer than that, if anyone still cares.

**Comment by Sarkie** [comment]
> I always use this
> 
> http://store.steampowered.com/hwsurvey
> 
> Windows 10 64 bit48.97%+0.60%
> Windows 7 64 bit29.02%+0.20%
> Windows 8.1 64 bit8.45%-0.14%
> Windows 75.23%-0.17%
> Windows 101.22%-0.01%
> Windows 8 64 bit1.14%-0.05%
> Windows XP 32 bit1.14%-0.05%
> Windows 8.10.26%-0.01%
> Windows Vista 32 bit0.13%-0.01%
> Windows 80.10%0.00%
> Windows Vista 64 bit0.06%-0.01%

from 1.14% to
Windows XP 32 bit 0.12%-0.01%

and 
http://gs.statcounter.com/os-version-market-share/windows/desktop/worldwide

2.16% WORLDWIDE.

It's dead Dave.

**Comment by hrydgard** [comment]
Yeah, I won't make a change now, but as soon as it becomes inconvenient due to VS2019, it goes.

**Comment by Narugakuruga** [comment]
@hrydgard "He's dead, Jim" actually.😂

**Comment by Narugakuruga** [comment]
http://gs.statcounter.com/os-version-market-share/windows/desktop/worldwide
Windows XP's market share keeps rising from October to December, what a joke.

**Comment by mrcmunir** [comment]
@Narugakuruga Maybe it's from people in protest because Valve Steam no longer be compatible with Windows XP.
Keep in mind that XP for retro works much better than current Windows.

**Comment by hrydgard** [comment]
Well, that rise is so tiny that it's just in the noise anyway...

Still, we'll keep XP support right up until VS ditches it.

**Comment by LunaMoo** [comment]
It seems it happened ~ VS2019 is out and no longer supports XP compatibility with it's latest toolset.

 Since we use $(DefaultPlatformToolset)_xp to automaticaly select toolset allowing to build on multiply VS versions, by default builds with VS2019 will now fail since there's no _XP for 142 toolset version.

**Comment by hrydgard** [comment]
If anyone still cares about XP, I could create a Win32XP VS configuration setting it to $(DefaultPlatformToolset)_xp which would only build in 2017, while having everything build by default but non-XP compatible in 2017 and 2019 in the default configuration but building release builds with 2017. Otherwise I'm inclined to just drop _xp ...

**Comment by Sarkie** [comment]
http://gs.statcounter.com/os-version-market-share/windows/desktop/worldwide - 1.74%

https://store.steampowered.com/hwsurvey - doesn't even make the list anymore.

Goodbye Sweet Prince, you served us well.

**Comment by jcchikikomori** [comment]
Here's my few points to say about this:

I became a fellow Windows XP user since 2007 and i love that OS. I'd used PPSSPP before with some ATRAC hacks (the dll injections, lol)
However, we need to start using new

Many Linux distributions nowadays are being made for Windows XP and up, in order to easily adapt Linux and eliminate the "Linux is hard" stereotype

I am playing PPSSPP now on Linux, and it has Gamepad support already without adding any drivers

Industry-wise, they have to move on, otherwise the development structure would be really hard to maintain

**Comment by Degerz** [comment]
Are you still going to keep DX9 for Vista or older hardware system users on Windows 7 or should it be dropped ?

**Comment by LunaMoo** [comment]
This has really nothing with D3D9 backend, the reasons to drop win XP are mostly to support modern features without hacks and nasty workarounds as well as support modern toolset and SDK versions.

**Comment by hrydgard** [comment]
Yeah, DX9 is staying.
