### ISSUE TITLE
fps drop in tekken games

### ISSUE THREAD

**Issue by tausifj15** [hrydgard/ppsspp#9219]
Sir henrik since 283 build in tekken games fps drop found and sound flicker also pls fix it
build.board: mt6592
build.bootloader: unknown
build.brand: Micromax
build.cpu_abi: armeabi-v7a
build.cpu_abi2: armeabi
build.device: A311
build.display: cm_A311-userdebug 6.0.1 MOB31K 3c77648877 test-keys
build.fingerprint: Micromax/cm_A311/A311:6.0.1/MOB31K/3c77648877:userdebug/test-keys
build.hardware: mt6592
build.host: instance-1
build.id: MOB31K
build.manufacturer: Micromax
build.model: A311
build.product: cm_A311
build.radio: unknown
build.serial: unknown
build.tags: test-keys
build.time: 1483016034000
build.type: userdebug
build.user: root
version.codename: REL
version.incremental: 3c77648877
version.release: 7.1.1
version.sdk_int: 23

01-18 22:09:01.212 I/ActivityManager(1402): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.ppsspp.ppsspp/.PpssppActivity bnds=[26,346][166,506] (has extras)} from uid 10120 on display 0
01-18 22:09:01.400 I/ActivityManager(1402): Start proc 15674:org.ppsspp.ppsspp/u0a168 for activity org.ppsspp.ppsspp/.PpssppActivity
01-18 22:09:03.832 I/MediaFocusControl(1402):  AudioFocus  requestAudioFocus() from android.media.AudioManager@fa59c5corg.ppsspp.ppsspp.AudioFocusChangeListener@a4fcb65 req=1flags=0x0
01-18 22:09:04.157 I/MediaFocusControl(1402):  AudioFocus  requestAudioFocus() from android.media.AudioManager@fa59c5corg.ppsspp.ppsspp.AudioFocusChangeListener@a4fcb65 req=1flags=0x0
01-18 22:09:04.838 I/MediaFocusControl(1402):  AudioFocus  abandonAudioFocus() from android.media.AudioManager@fa59c5corg.ppsspp.ppsspp.AudioFocusChangeListener@a4fcb65
01-18 22:09:05.194 E/        (15674): appName=org.ppsspp.ppsspp, acAppName=/system/bin/surfaceflinger
01-18 22:09:05.439 E/        (15674): appName=org.ppsspp.ppsspp, acAppName=/system/bin/surfaceflinger
01-18 22:09:05.550 I/ActivityManager(1402): Displayed org.ppsspp.ppsspp/.PpssppActivity: +4s200ms
01-18 22:09:10.842 I/NativeApp(15674): 09:10:842 Core/Config.cpp:1022 I[LOAD]: Config saved: /storage/7651-15E0/PSP/SYSTEM/ppsspp.ini
01-18 22:09:10.922 I/NativeApp(15674): 09:10:922 Core/System.cpp:387 I[BOOT]: PPSSPP v1.3-299-g3eaa815
01-18 22:09:11.170 I/NativeApp(15674): 09:11:170 Core/Config.cpp:1022 I[LOAD]: Config saved: /storage/7651-15E0/PSP/SYSTEM/ppsspp.ini
01-18 22:09:31.817 I/NativeApp(15674): 09:31:817 user_main    I[G3D]: GLES/ShaderManager.cpp:1035 Saving the shader cache to '/data/user/0/org.ppsspp.ppsspp/cache/UCES00356.glshadercache'
01-18 22:09:35.211 I/NativeApp(15674): 09:35:211 Core/Config.cpp:1022 I[LOAD]: Config saved: /storage/7651-15E0/PSP/SYSTEM/ppsspp.ini
01-18 22:09:36.153 I/NativeApp(15674): 09:36:153 Core/Config.cpp:1022 I[LOAD]: Config saved: /storage/7651-15E0/PSP/SYSTEM/ppsspp.ini
01-18 22:09:36.201 I/NativeApp(15674): 09:36:201 Core/System.cpp:387 I[BOOT]: PPSSPP v1.3-299-g3eaa815
01-18 22:09:36.319 I/NativeApp(15674): 09:36:319 Core/Config.cpp:1022 I[LOAD]: Config saved: /storage/7651-15E0/PSP/SYSTEM/ppsspp.ini
01-18 22:09:45.214 I/NativeApp(15674): 09:45:214 user_main    I[G3D]: GLES/ShaderManager.cpp:1035 Saving the shader cache to '/data/user/0/org.ppsspp.ppsspp/cache/ULES01376.glshadercache'
01-18 22:10:06.332 I/NativeApp(15674): 10:06:332 user_main    I[G3D]: GLES/ShaderManager.cpp:1035 Saving the shader cache to '/data/user/0/org.ppsspp.ppsspp/cache/ULES01376.glshadercache'
01-18 22:10:09.196 I/NativeApp(15674): 10:09:196 Core/Config.cpp:1022 I[LOAD]: Config saved: /storage/7651-15E0/PSP/SYSTEM/ppsspp.ini
01-18 22:10:09.785 I/NativeApp(15674): 10:09:785 Core/Config.cpp:1022 I[LOAD]: Config saved: /storage/7651-15E0/PSP/SYSTEM/ppsspp.ini
01-18 22:10:10.871 I/NativeApp(15674): 10:10:871 Core/Config.cpp:1022 I[LOAD]: Config saved: /storage/7651-15E0/PSP/SYSTEM/ppsspp.ini
01-18 22:10:11.059 I/WindowState(1402): WIN DEATH: Window{6cd8661 u0 org.ppsspp.ppsspp/org.ppsspp.ppsspp.PpssppActivity}
01-18 22:10:11.060 W/WindowManager(1402): Force-removing child win Window{814f7fb u0 SurfaceView} from container Window{6cd8661 u0 org.ppsspp.ppsspp/org.ppsspp.ppsspp.Ppssp

**Comment by tausifj15** [comment]
Since build 283

**Comment by hrydgard** [comment]
I found the cause for this, the fix will be a little involved though. Stay tuned.
