### ISSUE TITLE
Burnout Legends: Strange menu behavior

### ISSUE THREAD

**Issue by DonelBueno** [hrydgard/ppsspp#9221]
1- When you click on an icon to see the avaliable events in that location, the background of the screen is darkened (which is normal), but when you hit back (O), the screen keeps dark:

![ules00125_00000](https://cloud.githubusercontent.com/assets/4239694/22094387/3cef1bee-ddf4-11e6-9dc7-c288cc8fe3f5.png)
![ules00125_00001](https://cloud.githubusercontent.com/assets/4239694/22094388/3cf2580e-ddf4-11e6-842d-e9426977be4c.png)

2- When you are navigating the events on a given location and scroll down the menu, the icons corresponding to the events completion goe down and get out of place:

![ules00125_00002b](https://cloud.githubusercontent.com/assets/4239694/22094515/10ddd6e8-ddf5-11e6-81cd-2f97af01cf1d.png)
![ules00125_00002](https://cloud.githubusercontent.com/assets/4239694/22094389/3cf46ed2-ddf4-11e6-83ca-9bc443f22655.png)

Debug steps:

Tested on all backends, software rendering, native resolution, turned off texture filtering and texture scaling. Nothing helped.

System Specs:

Windows 10 Pro 64 bits
i7 980x @ 4.04 GHz
GTX 770 2GB
12 GB DDR3

**Comment by FlatOutPS2** [comment]
The game is fine on my end with PPSSPP 1.3 and latest git build.

**Comment by hrydgard** [comment]
I also don't see this. Strange.

**Comment by DonelBueno** [comment]
Wow, turns out this was the 60 fps cheat (made by Kabuto_Kun) I'm using.

I'm going to contact him, sorry for the inconvenience.

**Comment by hrydgard** [comment]
Huh, that's a bit surprising :)

**Comment by 1ashton** [comment]
Is there a way to fix it?

**Comment by hrydgard** [comment]
Someone will need to make a better 60fps cheat without the issue.
