### ISSUE TITLE
DX9: color and lighting issue.

### ISSUE THREAD

**Issue by xebra** [hrydgard/ppsspp#9224]
I'm testing with bezier in pspgl, it's working fine on OpenGL and Vulkan but it does not work properly on DX9.
1. Background color is BLUE, but it's RED only on DX9.
2. Lighting does not work on DX9 with Hardware Transform, but working if it's off.

DX9 with hardware transform
![menu_00000](https://cloud.githubusercontent.com/assets/1607422/22111705/a1f26546-dea3-11e6-9b70-89c3aedd2c9d.jpg)
DX9 without hardware transform
![menu_00001](https://cloud.githubusercontent.com/assets/1607422/22111708/a1f6819e-dea3-11e6-9184-0d78a1405f57.jpg)
OpenGL and Vulkan with/without hardware transform
![menu_00002](https://cloud.githubusercontent.com/assets/1607422/22111706/a1f33354-dea3-11e6-8960-a32eea69165b.jpg)

**Comment by hrydgard** [comment]
Interesting, we should fix this before merging your hardware splines. Can you upload the binary somewhere?

**Comment by xebra** [comment]
pspgl official site is here.
http://www.goop.org/psp/gl/#getting-code
But it seems can't download the binary.

Here is the binary
https://srv07.bitsend.jp/download/6f1b6b1aa588df063b044e8ad5e758bc.html?setLang=en
It's including several pspgl demos.

**Comment by hrydgard** [comment]
Thank you! I'll look into it in the weekend.

**Comment by mrcmunir** [comment]
Binarys it's http://www.goop.org/psp/gl/pspgl-demos.zip? I think If direct download not work 

You can http://www.goop.org/psp/gl/pspgl-demos.html and try Download pspgl-demos.zip

**Comment by xebra** [comment]
@hrydgard Thank you! I tried to fix them but I couldn't quickly.

@mrcmunir Oh, thank you! I deleted my archive. If anyone need this, please download from official.

**Comment by hrydgard** [comment]
That fixes the background color. Now onto the missing lighting...

**Comment by hrydgard** [comment]
It's using spotlights, something seems broken about them on DX9...

**Comment by hrydgard** [comment]
OK I'm totally stumped. It's like the light positions just stay zero for no reason at all. And it works with the other backends. No idea what's going on...

**Comment by hrydgard** [comment]
Bah nevermind, got it :)
