### ISSUE TITLE
New build tested (v1.3-388 - 1.3-390) break texture in some games

### ISSUE THREAD

**Issue by Ar37** [hrydgard/ppsspp#9239]
some games tested Bournout legend, NFS Most Wanted

OS: Android 4.2
Harware:
Armv7 neon
Mali-400

**Comment by Ar37** [comment]
.

**Comment by Ar37** [comment]
screenshots:

[](https://i.imgsafe.org/9c7d6170d7.png)

[](https://i.imgsafe.org/9c7805ff0b.png)

**Comment by hrydgard** [comment]
Thanks for reporting, will look into it.

**Comment by Ar37** [comment]
welcome. here some of logcats which appearing:
01-26 18:56:49.430 E/NativeApp(16856): 56:49:430 user_main    E[LOAD]: FileSystems/BlockDevices.cpp:341 Inflate frame 244224: failed - error[-5]
01-26 18:57:41.104 E/NativeApp(16992): 57:41:104 main         E[IO]: HLE/sceIo.cpp:1873 UNIMPL sceIoChangeAsyncPriority(5, 107)

**Comment by Ar37** [comment]
more detail screenshot which it shows broken textures https://i.imgsafe.org/9e6b402ecd.png

**Comment by sum2012** [comment]
@Ar37 There is no offical version v1.3-888 in http://buildbot.orphis.net/ppsspp/

**Comment by Ar37** [comment]
oh sorry that was typo, (v1.3-388 - 1.3-390) i meant

**Comment by Ar37** [comment]
I tried new latest build v1.3-403-g52a4467, and still has the same issue even it sett by default ppsspp configurations

**Comment by hrydgard** [comment]
Yeah, I've been working on other issues. This will be fixed, stay tuned.

**Comment by Ar37** [comment]
hrydgard@ ok, hope this issue will be fixed. thank you

**Comment by hrydgard** [comment]
Just tested on PC, works fine. Gonna have to dig out my S3...

**Comment by iOS4all** [comment]
Nice work.

**Comment by hrydgard** [comment]
Nice work what? All I did was test that I can't repro on the PC. It may still be a problem on Mali GPUs.

**Comment by sum2012** [comment]
@Ar37 Does v1.3-437-g1044796 fixed ?

**Comment by Ar37** [comment]
@sum2012 yes, this issue has been fixed on new build v1.3-437-g1044796
it seems perfectly fine now.
screenshot: https://i.imgsafe.org/e0ab38d438.png
thank you @hrydgard

**Comment by hrydgard** [comment]
Thanks for testing!
