### ISSUE TITLE
Software rendering regression

### ISSUE THREAD

**Issue by LunaMoo** [hrydgard/ppsspp#9247]
Last working v1.3-250-g33b3330:
![1sr](https://cloud.githubusercontent.com/assets/5485237/22396273/0231cf5c-e555-11e6-89c7-90881786dea4.jpg)

Starting from thin3D rework v1.3-275-gc89ad22:
![2sr](https://cloud.githubusercontent.com/assets/5485237/22396275/06781472-e555-11e6-8854-9c0903c354e8.jpg)

Degraded even more after v1.3-369-g4571c22:
![3sr](https://cloud.githubusercontent.com/assets/5485237/22396278/0f127f5a-e555-11e6-84eb-f8e5ff9cd021.jpg)

**Comment by hrydgard** [comment]
Thanks for reporting, I'll look into it soon.
