### ISSUE TITLE
Android: PPSSPP crashes when pressing home

### ISSUE THREAD

**Issue by Juliex** [hrydgard/ppsspp#9248]
trying the latest build, 1.3.413  ..

It runs fine, but after pressing home button, it exits from ram,in other word,it crashes..

https://drive.google.com/file/d/0B9xRb1mk7Go0QWVkaExfRy02d28/view?usp=drivesdk

**Comment by hrydgard** [comment]
Yeah there's some instability right now, I'm reworking lots of systems... Will be fixed soon.
