### ISSUE TITLE
Pursuit Force (USA) hardware tessellation terrain missing.

### ISSUE THREAD

**Issue by ppsspp-gamer** [hrydgard/ppsspp#9249]
![pursuit force](https://cloud.githubusercontent.com/assets/8726272/22397748/80bf3716-e5b3-11e6-9d72-da1965e51c5b.jpg)

Tested ppsspp-v1.3-413 windows x64 build on Windows 8.1 with Nvidia GTX760M.

steps to reproduce this bug:
(1) download ppsspp-v1.3-413-windows-amd64.7z from official web site.
(2) extract ppsspp to a clean folder.
(3) only change graphic setting to enable Hardware Tessellation.
(4) load Pursuit Force (USA).
(5) start Capelli Family first mission.

**Comment by ppsspp-gamer** [comment]
I found this bug is related to hardware transform. If I disable hardware transform, the terrain is back, but frame rate drops from 30 to 20.

**Comment by hrydgard** [comment]
@xebra ? :)

**Comment by LunaMoo** [comment]
Works fine here on AMD gpu & win 7. Can reproduce the issue on linux under virtual box generic gpu drivers and it looks like that when shader fails to compile.

 With current code it still can fail to compile as mentioned [here](https://github.com/hrydgard/ppsspp/issues/9234#issuecomment-275670160) which has to be fixed(aka completely disabled on hardware that doesn't support it:P).

@ppsspp-gamer could you post a screenshot of the bottom of the "settings->tools->system information->device info" page? Just to make sure it uses nvidia gpu with decent shading language version as if it does it could be yet different issue, if it doesn't, well ~ this feature will probably not work on integrated graphics(would be too slow on that anyway;p).

**Comment by ppsspp-gamer** [comment]
@LunaMoo here is the screenshot that you requested.
![device_info](https://cloud.githubusercontent.com/assets/8726272/22398514/04dfc888-e5c5-11e6-939b-6273e2d69f64.jpg)

**Comment by LunaMoo** [comment]
Well it does use Nvidia, I think it should work fine, possibly it has another problem with compiling a shader.

 Could you run ppsspp through InfoLog.bat, play until you reproduce the problem, then upload ppsspplog.txt on gist?
 Or activate debug->log console and see if there's a shader compilation error, disabling/re-enabling hardware tesselation should probably cause it to show up. Shader compilation errors are very verbose, so it would help a lot in figuring this out.

**Comment by ppsspp-gamer** [comment]
@LunaMoo here is the [ppsspp log](https://gist.github.com/ppsspp-gamer/2c353ba737726267358f75502e19231f) that you requested.

**Comment by LunaMoo** [comment]
That's bad:C, all shaders compile fine. Meaning it can be still be a bug in hardware tesselation code, just will be very hard to find.

 Could also be the driver of that mobile nvidia gpu fault, I recall reading something about mobile versions of nvidia gpu's using same drivers while not having same features, that could be how program get's compiled, yet failing to run properly.

**Comment by ppsspp-gamer** [comment]
I found ppsspp's opengl shader cache caused this bug. 

If I purge PPSSPP's opengl shader cache, then everything works fine until next time running Pursuit Force.

**Comment by moura464** [comment]
![ucus98640_00002](https://cloud.githubusercontent.com/assets/22099440/22399484/877e0eb2-e584-11e6-8ca4-152ebbf17ffe.jpg)

**Comment by moura464** [comment]
![asdasdqeqe](https://cloud.githubusercontent.com/assets/22099440/22399522/1151e316-e585-11e6-9481-f3deffa0d4cf.png)

**Comment by LunaMoo** [comment]
@ppsspp-gamer  well at least it's not completely failing.
 Still, can't reproduce this, my cache is unchanged after a bunch of restarts. I'm using v1.3-420-g14d2bf5 through, our usual spammer who doesn't know english and speaks with screenshots seems to also be on latest build, maybe try updating?

**Comment by hrydgard** [comment]
Ah, we need to update the shader cache version so it doesn't reuse old shaders. I'll take care of it.

**Comment by hrydgard** [comment]
Never mind, I read too quickly. That it reoccurs is curious.

**Comment by hrydgard** [comment]
Never mind again, looking at the code that seems to already be the case. Hm.

**Comment by hrydgard** [comment]
No, now I think I got it :) Hang on...

**Comment by xebra** [comment]
Fix? @hrydgard Thanks :)

I thought shader cache issue relate to surround this code with if-statement 
```
		if (g_Config.bHardwareTessellation) {
			id.SetBit(VS_BIT_BEZIER, doBezier);
			id.SetBit(VS_BIT_SPLINE, doSpline);
			id.SetBit(VS_BIT_HAS_COLOR_TESS, hasColorTess);
			id.SetBit(VS_BIT_HAS_TEXCOORD_TESS, hasTexcoordTess);
			id.SetBit(VS_BIT_NORM_REVERSE_TESS, gstate.isPatchNormalsReversed());
		}

```
Never mind if it fixed.

**Comment by hrydgard** [comment]
No that part should be fine, it will just be two separate shaders cached if g_Config.bHardwareTesselation is on or off. The other stuff was more problematic since the bools spline and bezier were never set when the shaders were loaded from disk, so the uniform IDs were never fetched, and thus the shaders got bogus uniform values.

**Comment by hrydgard** [comment]
I guess it's not a new idea though to use instancing for tesselation, here's from 2008:

http://developer.download.nvidia.com/presentations/2008/GDC/Inst_Tess_Compatible.pdf

:)

**Comment by xebra** [comment]
Thank you for your props :)
Of course, I have big respect to you @hrydgard .
Dolphin and PPSSPP is the best emulator I have ever seen before. And I know very early released PSP emulator named Potemkin. Also I tried to fix to play games, and some stuffs fixed but I quit to develop because I realised atrac3plus can not decode...
Anyway, I'm happy to developing with you :)

Yeah, Instanced tessellation is not my idea :) I think that is major technique with old graphics api. And I told before I referenced NVIDIA's sample :p
Also, I want to try modern tessellation implementation using like "tessellation shader".

**Comment by hrydgard** [comment]
Oh right!

Thing is, I think the modern tesselation shaders actually may be a worse match. It has its own ideas about what a good triangle pattern is, and we can never match PSP that way, while with instanced tesselation, we can.

**Comment by xebra** [comment]
Hmm, I actually don't almost know what about the modern tessellation shader.
But, I'm just curious, so I'll try to check the detail and try implement.
Also, I have an idea to improve "instanced tessellation" with 4x4(one patch) spline/bezier. Pursuit Force is using so many 4x4 bezier patches, so it may be able to some performance up.
