### ISSUE TITLE
Code Lyoko screen problem in android

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#9250]
![screenshot_20170129-194323](https://cloud.githubusercontent.com/assets/2177532/22403756/df4371dc-e65b-11e6-9c16-7ea40665b582.jpg)

It should be 
![2](https://cloud.githubusercontent.com/assets/2177532/22403759/13f0ae86-e65c-11e6-89b7-a99e21907873.jpg)

My phone is Asus zenfone 3

edit:test on v1.3-433-g03b607f in windows and android

**Comment by sum2012** [comment]
tag @punysub

**Comment by sum2012** [comment]
Hmm v1.3 work 
v1.3-388-g56acafd not work

**Comment by sum2012** [comment]
Hmm
v1.3-375-g19e309c	work
v1.3-386-g98e0ccf not work

**Comment by hrydgard** [comment]
Most likely I've somehow screwed up in this commit: https://github.com/hrydgard/ppsspp/commit/98e0ccf1e138d877eef57526ef1a414ae193b1c7

I'll take a look.

**Comment by sum2012** [comment]
@hrydgard  Yes,I compile myself v1.3-385-gf9d2fda ,ir work
that mean https://github.com/hrydgard/ppsspp/commit/98e0ccf1e138d877eef57526ef1a414ae193b1c7 has problem

**Comment by hrydgard** [comment]
Yep, and I found the problem. Fixing it.
