### ISSUE TITLE
Dies irae Amantes amentes  ULJM06107 cannot switch umd

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#9254]
This time I don't have idea now.
v1.3-437-g1044796 log: https://gist.githubusercontent.com/sum2012/7fde5b455ea656c553625cc2a0bb1e9e/raw/ac6cda43d336dc133315886e18fbacebd863876b/gistfile1.txt

1=sceUmdCheckMedium() then  0=sceUmdCheckMedium() finally 1=sceUmdCheckMedium()

**Comment by sum2012** [comment]
I try this change but still fail
static int sceUmdWaitDriveStatCB(u32 stat, u32 timeout)
{
	if (!UMDInserted) {
		WARN_LOG(SCEIO, "sceUmdWaitDriveStatCB(stat = %08x, timeout = %d): UMD is taking out for switch UMD", stat, timeout);
		return SCE_KERNEL_ERROR_ACCESS_ERROR;
...
	}

**Comment by hrydgard** [comment]
Hm, I really don't know. This has never worked before, right?

**Comment by sum2012** [comment]
Yes

**Comment by sum2012** [comment]
Oh yes,I need another change to make it work :)

**Comment by hrydgard** [comment]
@sum2012  nice and simple :)

**Comment by sum2012** [comment]
Hope no more switch UMD problem :)
