### ISSUE TITLE
Regression : Graphical glitches in Split Second

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#9263]
Since https://github.com/hrydgard/ppsspp/pull/9176/commits/1dbeca0618966f4c8156d81e5b25d40f9f8b89e0 in https://github.com/hrydgard/ppsspp/pull/9176
Textures are changing while it's moving
![01](https://cloud.githubusercontent.com/assets/3481559/22468377/000694dc-e803-11e6-9c31-99dd2f596938.png)
![02](https://cloud.githubusercontent.com/assets/3481559/22468378/000c5340-e803-11e6-91ba-dfb8378051c4.png)

**Comment by hrydgard** [comment]
Yeah, this needs fixing. Thanks for finding the commit responsible!

**Comment by hrydgard** [comment]
Okay, finally narrowed down to a vertex cache problem. If you turn off the vertex cache, the problem goes away.

Now, to figure out what the actual problem with the vertex cache is... It appears to have something to do with how the game draws stuff twice to apply environment mapping.

**Comment by moura464** [comment]
![ulus10513_00001](https://cloud.githubusercontent.com/assets/22099440/22622219/d9e67be8-eb1b-11e6-9982-f3be741c9f61.jpg)

**Comment by moura464** [comment]
Split Second ^_^ Build :+1:
