### ISSUE TITLE
Has Qt4 support been dropped?

### ISSUE THREAD

**Issue by zhykzhykzhyk** [hrydgard/ppsspp#9267]
The whole QMake build script was removed, which had been used to build with Qt4. (CMake build script requires Qt5).
Was this intended or not? If it was intended, I think README should be updated to claim this.

**Comment by hrydgard** [comment]
Yes, it was intended, to reduce the number of build systems to maintain. I'll update the README.

**Comment by hrydgard** [comment]
Hm, I assume you mean the wiki build instructions? no mention of Qt in the README.

**Comment by hrydgard** [comment]
Updated the wiki, got rid of some obsolete instructions.
