### ISSUE TITLE
Regression : Motor Strom graphical glitch

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#9275]
Since https://github.com/hrydgard/ppsspp/pull/9269/commits/1c1139870c274b4319ea10b88e5ee013bbd6e846 in https://github.com/hrydgard/ppsspp/pull/9269

![01](https://cloud.githubusercontent.com/assets/3481559/22576323/c1528d0a-e9f5-11e6-935f-56791274dd96.png)

![02](https://cloud.githubusercontent.com/assets/3481559/22576324/c15312e8-e9f5-11e6-98b2-4434cff1b48a.png)

**Comment by LunaMoo** [comment]
Seems like this is affecting more games.

**Comment by daniel229** [comment]
Yes, Assassin's Creed Bloodlines and Dantes Inferno also

**Comment by xebra** [comment]
> Since 1c11398 in #9269

Why my changes?
Seems this issue occured more old revision.

**Comment by xebra** [comment]
Ah, right, I confirmed it. I'll fix it.

**Comment by xebra** [comment]
I think this issue causes by this.
```
void FramebufferManagerGLES::BlitFramebuffer(VirtualFramebuffer *dst, int dstX, int dstY, VirtualFramebuffer *src, int srcX, int srcY, int w, int h, int bpp) {
	if (!dst->fbo || !src->fbo || !useBufferedRendering_) {
		// This can happen if they recently switched from non-buffered.
		fbo_unbind();
		return;
	}

	bool useBlit = gstate_c.Supports(GPU_SUPPORTS_ARB_FRAMEBUFFER_BLIT | GPU_SUPPORTS_NV_FRAMEBUFFER_BLIT);
```
So I'll split the checker single and multi.

**Comment by xebra** [comment]
Hmm, it's not single or multi...
It's ANY or ALL.

**Comment by zminhquanz** [comment]
i think hardware tessellation caused this :)

**Comment by xebra** [comment]
No, it's not hardware tessellation issue, and fixed :)
