### ISSUE TITLE
iOS arm64 jit crash

### ISSUE THREAD

**Issue by PugaTang** [hrydgard/ppsspp#9283]
I get EXC_BAD_ACCESS error when i launch a rom with the latest arm64 ppsspp.
Error break at Arm64Jit.cpp
```
void Arm64Jit::RunLoopUntil(u64 globalticks) {
	PROFILE_THIS_SCOPE("jit");
	((void (*)())enterDispatcher)();
}
```
But It is fine when i build it only with armv7.

#9232 I don't know it is the same issue, but my code is the latest.

**Comment by hrydgard** [comment]
Yeah this is known, and is the remaining problem in #9232. I spend two days debugging it without success so I had to take a break.

Closing because #9232 already covers this.
