### ISSUE TITLE
Split Second Velocity v1.3-192-ga2b49fd  vs v1.3-508-gabf7a7a

### ISSUE THREAD

**Issue by moura464** [hrydgard/ppsspp#9285]
![asdadaeeeee](https://cloud.githubusercontent.com/assets/22099440/22658014/b896e328-ec7f-11e6-9c0e-093af788d133.png)

**Comment by hrydgard** [comment]
Is there a problem? Both pictures look fine to me.

**Comment by unknownbrackets** [comment]
It looks like the road under the car is a bit funky in the newer one.  Does this still happen?

-[Unknown]

**Comment by hrydgard** [comment]
That one's been fixed indeed. And I was wrong in the comment above, we figured it out in #9263, yes.
