### ISSUE TITLE
Regression: All games icons are black on Shield Portable

### ISSUE THREAD

**Issue by ms2048** [hrydgard/ppsspp#9286]
The preview icons of games seen in game selection menus are all black (including backgrounds except for the standard background), making the 'Recent' menu unusable (and the whole menu ugly in general). Sizes (shapes) are preserved though.

Tested under Nvidia Shield Portable, Android 4.4.2.

I've bisected the problem via installing apk's from the website. The regression manifests itself since v1.3-248-g619f918 up until current version. It has been introduced somewhere between v1.3-241-g92db2b0 (icons seem ok) and v1.3-248-g619f918 (icons are black).

Screenshot from v1.3-248-g619f918 follows:

![screenshot_2017-02-06-21-54-13](https://cloud.githubusercontent.com/assets/25595047/22666235/148ce1a4-ecb8-11e6-86f7-f61a021c892c.png)

**Comment by hrydgard** [comment]
Yup, I noticed this one recently on mine. It's quite weird given that it works on all other Android devices I've tried. I'll look into it soon.
