### ISSUE TITLE
Twisted Metal: Head-On no Fx sound

### ISSUE THREAD

**Issue by Levan7** [hrydgard/ppsspp#9290]
Well i am using the 1.3-530-ge5c20b4 version of ppsspp and there is no effects sound in the game, however the music works just fine.

[DebugLog.zip](https://github.com/hrydgard/ppsspp/files/758462/DebugLog.zip)
[InfoLog.zip](https://github.com/hrydgard/ppsspp/files/758463/InfoLog.zip)

**Comment by SamueldeSena** [comment]
this problem has already been corrected in the new version of ppsspp v1.5.4 this topic can already be closed
