### ISSUE TITLE
PPSSPP crashes when turning screen off and on

### ISSUE THREAD

**Issue by xsm1997** [hrydgard/ppsspp#9295]
Hello, there. Recently a problem occurred to me that when I turning screen off and on after loading a game, PPSSPP crashes.
I tested some versions of ppsspp in the buildbot, it seems that it starts crashing since version 1.3-515. It isn't crashing when using version 1.3-508. I can't test the versions between 508 and 515 because there are no builds in the buildbot.
I also uploaded the crash backtrace on the Android Monitor, and wish that helps.
![image](https://cloud.githubusercontent.com/assets/4453837/22775158/54d0a4ce-eee5-11e6-894f-e3a33bc9b45c.png)

I also found another problem, that is, when I turn on the upscaling function, whatever it is xBRZ or other things, after turning screen off and on, PPSSPP get frozen on version 1.3-508. The problem even occurs on PPSSPP 1.2.2 downloaded on ppsspp.org.
I'm using XiaoMi 5 running Mokee 71.1 ROM. I notice that when my phone is running MIUI 8 the freezing problem also recurs. Even on my old phone RedMi Note 2 running MIUI 7 it also has the problem. The difference between MIUI ROM and Mokee ROM is that it also freezes when pressing HOME button and switching back to PPSSPP on MIUI ROM. I had tested the version 1.2.2 on my recent phone and it also has the problem. I can't test it on my old phone but I remember that the problem is old enough that at least version 1.2 is affected.

Outline:
My phone:
XiaoMi 5 (recent)
  Qualcomm Snapdragon 820
  Adreno 530
  3Gb Memory
  MIUI 8(Android 6.0) and MOKEE 71.1(Android 7.1)

RedMi Note 2 (former)
  MediaTek Helios X10
  PowerVR G6200
  2Gb Memory
  MIUI 7(Android 5.0)

Problem 1: PPSSPP crashes when turning screen off and on
1.3-515 (crashing)
1.3-508 (not crashing)

Problem 2: PPSSPP freezes when turning on upscaling after turning screen off and on
Recent Phone: at least 1.2.2 (freeze)
Former Phone: at least 1.2 (freeze)

Thank you all, and looking forward to solution

**Comment by hrydgard** [comment]
Yeah, will look into the on/off problem soon when I'm done with D3D11. One thing at a time :)

Including in the 1.4 milestone. As for the upscaling one, that's probably related.

**Comment by ProjectXsent** [comment]
I'm currently using the 493 build so I'll wait until it fixes the issue

**Comment by Hydroque** [comment]
This could be a programmatic error that has to do with the thread scheduling. When I alt tab, when the code is a certain way, PPSSPP will crash on the release I am on, which I got about a week ago. I am not really sure how to replicate it.

**Comment by xsm1997** [comment]
Hi, there. I have a news about the off and on issue.

When I turn the screen rotation of my screen as well as the lock screen rotation on, after turning the screen off and on without rotation my screen (always landscape), I find that PPSSPP is not crashing.
In addition, I even find the upscaling problem disappeared.

Running the latest version of PPSSPP (1.3-842), it showed a different crash message from the log, and it seems that the issue has something to do with Framebuffer.
Android logcat shows the crash is from the execution in _ZN24FramebufferManagerCommon12DecimateFBOsEv+60. I had read the code difference between 1.3-508 and 1.3-515, and it seems that there were a lot of changes to Framebuffer.

Hope that useful, and look forward to solving the problem.

Thanks.

**Comment by hrydgard** [comment]
Thanks, that's lots of useful info! I have some ideas.

**Comment by Hydroque** [comment]
Btw I am not having this problem anyone on PC

**Comment by hrydgard** [comment]
@xsm1997  Please test again with the newest builds from buildbot.orphis.net/ppsspp/ .

**Comment by hrydgard** [comment]
@ProjectXsent , please also test the latest builds on your device.

**Comment by hrydgard** [comment]
As far as I can tell this is fixed. Please reopen if you still have issues.

**Comment by ProjectXsent** [comment]
Ok sir I will try. Are you gonna release ppsspp 1.4 or 1.3.1 tomorrow?

**Comment by xsm1997** [comment]
Yeah, the issue has been fixed. The upscaling issue also disappeared. Thank you for your awesome job!

**Comment by hrydgard** [comment]
@ProjectXsent  in about a week, 1.4.
