### ISSUE TITLE
Build stops at 2% (Building CXX object CMakeFiles/xbrz.dir/ext/xbrz/xbrz.cpp.o)

### ISSUE THREAD

**Issue by Adrien2002** [hrydgard/ppsspp#9301]
Hello,
I'm not good at building things and I'm using a system where packages are installed in /usr/pkg/lib instead of /usr/lib.
ffmpeg libs are installed in /usr/pkg/lib/ffmpeg3 (because we have every versions available in our package manager)

Even if I enter them manually in CMakeCache.txt that way : 

> //Path to a file.
> FFmpeg_INCLUDE_avcodec:PATH=/usr/pkg/include
> 
> //Path to a file.
> FFmpeg_INCLUDE_avdevice:PATH=/usr/pkg/include
> 
> //Path to a file.
> FFmpeg_INCLUDE_avfilter:PATH=/usr/pkg/include
> 
> //Path to a file.
> FFmpeg_INCLUDE_avformat:PATH=/usr/pkg/include
> 
> //Path to a file.
> FFmpeg_INCLUDE_avutil:PATH=/usr/pkg/include
> 
> //Path to a file.
> FFmpeg_INCLUDE_postproc:PATH=/usr/pkg/include
> 
> //Path to a file.
> FFmpeg_INCLUDE_swresample:PATH=/usr/pkg/include
> 
> //Path to a file.
> FFmpeg_INCLUDE_swscale:PATH=/usr/pkg/include
> 
> //Path to a library.
> FFmpeg_LIBRARY_avcodec:FILEPATH=/usr/pkg/lib/ffmpeg3/libavcodec.so.57.64.100
> 
> //Path to a library.
> FFmpeg_LIBRARY_avdevice:FILEPATH=/usr/pkg/lib/ffmpeg3/libavdevice.so.57.1.100
> 
> //Path to a library.
> FFmpeg_LIBRARY_avfilter:FILEPATH=/usr/pkg/lib/ffmpeg3/libavfilter.so.6.65.100
> 
> //Path to a library.
> FFmpeg_LIBRARY_avformat:FILEPATH=/usr/pkg/lib/ffmpeg3/libavformat.so.57.56.100
> 
> //Path to a library.
> FFmpeg_LIBRARY_avutil:FILEPATH=/usr/pkg/lib/ffmpeg3/libavutil.so.55.34.100
> 
> //Path to a library.
> FFmpeg_LIBRARY_postproc:FILEPATH=/usr/pkg/lib/ffmpeg3/libpostproc.so.54.1.100
> 
> //Path to a library.
> FFmpeg_LIBRARY_swresample:FILEPATH=/usr/pkg/lib/ffmpeg3/libswresample.so.2.3.100
> 
> //Path to a library.
> FFmpeg_LIBRARY_swscale:FILEPATH=/usr/pkg/lib/ffmpeg3/libswscale.so.4.2.100

Maybe it's not enough for building process to find out everything it needs. I think I should be able to add lib folders in CMakeLists.txt so they can be correctly used (only suppositions, I don't know enough to be sure of what I say).

Here is the full `cmake .. && make` : 

> $ cmake .. && make
> -- The C compiler identification is GNU 5.4.0
> -- The CXX compiler identification is GNU 5.4.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- The ASM compiler identification is GNU
> -- Found assembler: /usr/bin/cc
> -- No build type selected, default to Release
> CMAKE_SYSTEM_PROCESSOR: x86_64
> Generating for x86, Release
> Generating for x86_64, Release
> -- Google Mock was not found - tests based on that will not build
> --  Found avcodec: /usr/pkg/include /usr/pkg/lib/ffmpeg3/libavcodec.so.57.64.100
> --  Found avdevice: /usr/pkg/include /usr/pkg/lib/ffmpeg3/libavdevice.so.57.1.100
> --  Found avfilter: /usr/pkg/include /usr/pkg/lib/ffmpeg3/libavfilter.so.6.65.100
> --  Found avformat: /usr/pkg/include /usr/pkg/lib/ffmpeg3/libavformat.so.57.56.100
> --  Found avutil: /usr/pkg/include /usr/pkg/lib/ffmpeg3/libavutil.so.55.34.100
> --  Found postproc: /usr/pkg/include /usr/pkg/lib/ffmpeg3/libpostproc.so.54.1.100
> --  Found swresample: /usr/pkg/include /usr/pkg/lib/ffmpeg3/libswresample.so.2.3.100
> --  Found swscale: /usr/pkg/include /usr/pkg/lib/ffmpeg3/libswscale.so.4.2.100
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/ui_atlas.zim
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/.git
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/README.md
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/ar_AE.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/az_AZ.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/bg_BG.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/ca_ES.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/cz_CZ.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/da_DK.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/de_DE.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/dr_ID.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/en_US.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/es_ES.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/es_LA.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/fa_IR.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/fi_FI.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/fr_FR.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/gl_ES.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/gr_EL.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/he_IL.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/he_IL_invert.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/hu_HU.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/id_ID.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/it_IT.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/ja_JP.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/jv_ID.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/ko_KR.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/lo_LA.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/lt-LT.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/ms_MY.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/nl_NL.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/no_NO.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/pl_PL.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/pt_BR.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/pt_PT.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/ro_RO.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/ru_RU.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/sv_SE.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/tg_PH.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/th_TH.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/tr_TR.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/uk_UA.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/vi_VN.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/zh_CN.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/lang/zh_TW.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/shaders
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/shaders/4xhqglsl.fsh
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/shaders/4xhqglsl.vsh
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/shaders/5xBR.fsh
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/shaders/5xBR.vsh
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/shaders/aacolor.fsh
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/shaders/aacolor.vsh
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/shaders/bloom.fsh
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/shaders/cartoon.fsh
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/shaders/cartoon.vsh
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/shaders/crt.fsh
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/shaders/defaultshaders.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/shaders/fxaa.fsh
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/shaders/fxaa.vsh
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/shaders/grayscale.fsh
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/shaders/inversecolors.fsh
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/shaders/natural.fsh
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/shaders/natural.vsh
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/shaders/scanlines.fsh
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/shaders/sharpen.fsh
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/shaders/upscale_spline36.fsh
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/shaders/upscale_spline36.vsh
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/shaders/vignette.fsh
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/ppge_atlas.zim
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/compat.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/langregion.ini
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/gamecontrollerdb.txt
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/unknown.png
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/flash0
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/flash0/font
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/flash0/font/jpn0.pgf
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/flash0/font/kr0.pgf
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/flash0/font/ltn0.pgf
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/flash0/font/ltn1.pgf
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/flash0/font/ltn10.pgf
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/flash0/font/ltn11.pgf
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/flash0/font/ltn12.pgf
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/flash0/font/ltn13.pgf
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/flash0/font/ltn14.pgf
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/flash0/font/ltn15.pgf
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/flash0/font/ltn2.pgf
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/flash0/font/ltn3.pgf
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/flash0/font/ltn4.pgf
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/flash0/font/ltn5.pgf
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/flash0/font/ltn6.pgf
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/flash0/font/ltn7.pgf
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/flash0/font/ltn8.pgf
> -- Installing: /home/Adrien2002/Téléchargements/ppsspp/build/assets/flash0/font/ltn9.pgf
> -- Configuring done
> CMake Warning at CMakeLists.txt:1735 (add_executable):
>   Cannot generate a safe runtime search path for target PPSSPPSDL because
>   files in some directories may conflict with libraries in implicit
>   directories:
> 
>     runtime library [libz.so.1] in /usr/lib may be hidden by files in:
>       /usr/pkg/lib
> 
>   Some of these libraries may not be found correctly.
> 
> 
> -- Generating done
> -- Build files have been written to: /home/Adrien2002/Téléchargements/ppsspp/build
> Scanning dependencies of target GitVersion
> [  1%] Generating something_that_never_exists
> -- Found Git: /usr/pkg/bin/git (found version "2.10.2") 
> [  1%] Built target GitVersion
> Scanning dependencies of target cityhash
> [  1%] Building CXX object CMakeFiles/cityhash.dir/ext/native/ext/cityhash/city.cpp.o
> [  1%] Linking CXX static library lib/libcityhash.a
> [  1%] Built target cityhash
> Scanning dependencies of target kirk
> [  1%] Building C object CMakeFiles/kirk.dir/ext/libkirk/AES.c.o
> [  1%] Building C object CMakeFiles/kirk.dir/ext/libkirk/amctrl.c.o
> [  2%] Building C object CMakeFiles/kirk.dir/ext/libkirk/SHA1.c.o
> [  2%] Building C object CMakeFiles/kirk.dir/ext/libkirk/bn.c.o
> [  2%] Building C object CMakeFiles/kirk.dir/ext/libkirk/ec.c.o
> [  2%] Building C object CMakeFiles/kirk.dir/ext/libkirk/kirk_engine.c.o
> [  2%] Linking C static library lib/libkirk.a
> [  2%] Built target kirk
> Scanning dependencies of target rg_etc1
> [  2%] Building CXX object CMakeFiles/rg_etc1.dir/ext/native/ext/rg_etc1/rg_etc1.cpp.o
> [  2%] Linking CXX static library lib/librg_etc1.a
> [  2%] Built target rg_etc1
> Scanning dependencies of target xbrz
> [  2%] Building CXX object CMakeFiles/xbrz.dir/ext/xbrz/xbrz.cpp.o
> In file included from /home/Adrien2002/Téléchargements/ppsspp/ext/xbrz/xbrz.cpp:17:0:
> /usr/include/g++/cmath:1067:11: error: ‘::double_t’ has not been declared
>    using ::double_t;
>            ^
> /usr/include/g++/cmath:1068:11: error: ‘::float_t’ has not been declared
>    using ::float_t;
>            ^
> /usr/include/g++/cmath:1087:11: error: ‘::copysign’ has not been declared
>    using ::copysign;
>            ^
> /usr/include/g++/cmath:1195:11: error: ‘::scalbln’ has not been declared
>    using ::scalbln;
>            ^
> /usr/include/g++/cmath:1199:11: error: ‘::scalbn’ has not been declared
>    using ::scalbn;
>            ^
> *** Error code 1
> 
> Stop.
> make[2]: stopped in /home/Adrien2002/Téléchargements/ppsspp/build
> *** Error code 1
> 
> Stop.
> make[1]: stopped in /home/Adrien2002/Téléchargements/ppsspp/build
> *** Error code 1
> 
> Stop.
> make: stopped in /home/Adrien2002/Téléchargements/ppsspp/build

A little help to understand what could be wrong would be appreciated.

**Comment by hrydgard** [comment]
You should never poke around in CMakeCache.txt, it's much better to solve problems properly.

Is there any reason why you can't use the bundled FFMPEG? FFMPEG changes its APIs and behaviours quite often, and because it's a royal pain to build FFMPEG on many platforms, and keeping support for two simultaneous versions is not easy, we strongly recommend to use the FFMPEG that's bundled in the submodule.

**Comment by unknownbrackets** [comment]
This sounds like a likely cmake misconfiguration by hand editing as noted.  But - also keep #9026 in mind, we know there are issues and crashes with newer FFmpeg versions due to subtle API changes.

-[Unknown]
