### ISSUE TITLE
Bind Default/All

### ISSUE THREAD

**Issue by Anuskuss** [hrydgard/ppsspp#9302]
Can we have a feature to delete the current control configuration and then a bind default/all setup? Would make it harder to mess something up and would be easier to configure for unsupported gamepads.

**Comment by LunaMoo** [comment]
So to make it clear basically you're asking for something which ppsspp already had from long ago?
That's under Settings->Controls->Control Mapping->"Clear all" & "Restore defaults" >.>  ...right, I'll just close this then.

**Comment by Anuskuss** [comment]
@LunaMoo Sorry if I wasn't clear enough: In RetroArch for example you can hit "Bind Default" and there will be a popup with the button that needs to be configured (with a x-seconds timeout) and that would make it easy to map all the buttons in one go (default = needed buttons, all = all; no key press = skip/dont bind).

**Comment by LunaMoo** [comment]
Ok, that's different, so I can reopen. Don't have much sense to go through all gamepad mappings just to customize a button or two, but I guess you want something like adding new entries to gamecontrollerdb.txt if those don't exist. This can already be done by external apps like [this](http://www.generalarcade.com/gamepadtool/) ~ which work the way you describe ~ or some other sdl gamepad tools.
