### ISSUE TITLE
MLB Games 06-11 Pitching Meter Freezes

### ISSUE THREAD

**Issue by Tnaddy16** [hrydgard/ppsspp#9308]
MLB Games 06-11 Pitching Meter Freezes

**Comment by hrydgard** [comment]
No screenshot? Android or Windows or what platform? This is not a useful bug report.

**Comment by Tnaddy16** [comment]
Sorry for my original report here are my screenshots, my system specs, and more information about the issue. 

System Specs: 

Operating System
	Windows 10 Home 64-bit
CPU
	Intel Core i3 4130T @ 2.90GHz	
	Haswell 22nm Technology
RAM
	8.00GB Dual-Channel DDR3 @ 798MHz (11-11-11-28)
Motherboard
	Dell Inc. 03V3TG (CPU 1)	
Graphics
	ELEFW504 (1920x1080@60Hz)
	2047MB NVIDIA GeForce GPU (Dell)	
Storage
	931GB Western Digital WDC WD10JPVX-75JC3T0 (SATA)

The pitch meter freezes during the  wind-up, and speeds up to the accuracy indicator, which is then impossible to pitch accurately. You have to use classic pitching instead of meter pitching, which doesn't allow for an effective pitching game at all.
![mlbpitchingmeter](https://cloud.githubusercontent.com/assets/25571678/23002963/2c0574f2-f3b3-11e6-86e9-8e1708651d98.jpg)

**Comment by unknownbrackets** [comment]
Does this still happen?

Could you try exporting a GE frame dump?  These help a lot.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by tahzib1451** [comment]
> Does this still happen?
> 
> Could you try exporting a GE frame dump? These help a lot.
> 
> See here for instructions - it's not hard and works on Android too:
> https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump
> 
> You can zip that and then drag and drop it into a reply here.
> 
> -[Unknown]

since the OP dint reply, i am chiming in....here is the dump file zipped....i took the recording from android phone, so i dont know if it came out okay or not....
[recording.zip](https://github.com/hrydgard/ppsspp/files/5754508/recording.zip)

**Comment by unknownbrackets** [comment]
I looked through the dump, but unfortunately it doesn't seem like the game drew the pitching meter on that frame at all.

You can open the generated file in PPSSPP, and it'll show what was captured.  In this case, we need one that shows the pitching meter itself so we can tell how the game is drawing it.

-[Unknown]

**Comment by tahzib1451** [comment]
> I looked through the dump, but unfortunately it doesn't seem like the game drew the pitching meter on that frame at all.
> 
> You can open the generated file in PPSSPP, and it'll show what was captured. In this case, we need one that shows the pitching meter itself so we can tell how the game is drawing it.
> 
> -[Unknown]

reminded me not to use phone to do these stuff......
took the recording from the PC....
[UCUS98758_0004.zip](https://github.com/hrydgard/ppsspp/files/5763065/UCUS98758_0004.zip)

**Comment by tahzib1451** [comment]
I tried making a dump from my PC, but all I could get was a screenshot type
image....is there any way to make a video snippet?

**Comment by Panderner** [comment]
[UCUS98758.zip](https://github.com/hrydgard/ppsspp/files/5996740/UCUS98758.zip)
GE dumps here.

**Comment by unknownbrackets** [comment]
It takes until 11811/13482 to get the background drawn, which ends up with mostly clear stencil (except shadows) and filled depth (but some depth values on the field.)  The players and the mound use depth.

At 13240/13482, we're finally to the pitching meter itself.  It uses the same texture for a bunch of draws, and finally draws the actual meter at 13362/13482.  This is just a triangle strip (146 verts), not a patch or anything.

The texture is pretty small, I wonder if this is a texture hashing issue like the Z.H.P. issue somehow?  It doesn't look like it, though.

If you create a texture ini for this game (like you were creating texture replacements), and then change the hash to xxh64, does it work?  If yes, this is likely a texture hash issue...

-[Unknown]

**Comment by unknownbrackets** [comment]
It'd also help to confirm whether this works fine under the software renderer (it probably does, but it may be slow.)

-[Unknown]

**Comment by arielsl** [comment]
Just here to confirm the pitching meter works with software renderer but it runs at around 20 FPS for me. Playing MLB 08 The Show specifically.

Version 1.12.3-922-g1f71a69be

**Comment by unknownbrackets** [comment]
Okay, then it does seem likely it might be a small texture issue or some framebuffer write being missed.  FWIW, the latest git build may improve performance of the software render by a chunk compared to that version, although it probably still won't be full speed I suppose.

Interesting if XXH64 doesn't help.  That makes it seem like it's a framebuffer write.

-[Unknown]

**Comment by unknownbrackets** [comment]
There's a video of the problem here: https://github.com/hrydgard/ppsspp/issues/11596#issuecomment-1355767097

It does seem like some of it shows, and then it hits collisions or something.

-[Unknown]

**Comment by ppmeis** [comment]
Tested in latest build under Vulkan backend. Pitcher bar HUD is not showing charge position correctly. In software render you can see power line bar in the whole bar perfectly:

![UCUS98696_00000](https://user-images.githubusercontent.com/4381277/208202286-085659e0-517f-478a-8a07-24ea44b86bb4.jpg)

But in any other render (well at least Vulkan an Direct3D 11) power line bar dissapear up to the mid of the power bar and then comes back:

![UCUS98696_00001](https://user-images.githubusercontent.com/4381277/208202457-18108acc-1ca8-413e-a356-04757a280b33.jpg)

Here is a video to explain the issue better:


https://user-images.githubusercontent.com/4381277/208203241-912ae834-4311-43be-b4ea-edd9d921d0ed.mp4

**Comment by jayjun911** [comment]
The problem has repro'd consistently for last years. Could you bump up the priority?

**Comment by hrydgard** [comment]
Aha! The texture is swizzled, which means it's stored in memory in Nx8 blocks. But the texture is only 4 pixels high, so the texture wastes 4 vertical pixels of space, doubling the space requirements. We calculated the range of memory to hash as if it was linear, so effectively we only hashed the left half of the texture, leading to the freeze!

Fixing.

**Comment by jayjun911** [comment]
@hrydgard Thanks for your time and expertise. It's been a problem nagging for half a decade. :)
