### ISSUE TITLE
Metal rendering (feature request)

### ISSUE THREAD

**Issue by iOS4all** [hrydgard/ppsspp#9309]
@hrydgard I just wonder if we can get metal rendering support besides vulkan, OpenGL and D3D11?
I'm sure it gonna help to increase performance on a lot. It also could fix all known issues if we get metal api support.
Btw the latest jailbreak for iOS 10 it gives a fully KPP bypass and kernel files unencrypted if that's help.
Thanks.

**Comment by hrydgard** [comment]
Metal is just another rendering API, it won't "fix all issues". You are right that performance might increase though. Right now I have other priorities, but I'm leaving this open though, because it's certainly something that I might do in the future.

**Comment by iOS4all** [comment]
@hrydgard thank you so much for planning to support metal api.
Take your time and we'll waiting for supporting this patiently.

**Comment by iOS4all** [comment]
If you have a good time just give iOS port some love.
And we'll always be waiting patiently for something new related to iOS.
Thanks a lot.

**Comment by hrydgard** [comment]
https://developer.apple.com/macos/whats-new/   Heh, Apple is now officially deprecating OpenGL. I guess we're gonna have to add MoltenVK support at some point.

**Comment by hrydgard** [comment]
Decided we won't do this but we will eventually do MoltenVK (which is a Vulkan implementation which runs on top of Metal, and gets most of the performance).
