### ISSUE TITLE
Sync Saved States between Platforms using cloud

### ISSUE THREAD

**Issue by araujoigor** [hrydgard/ppsspp#9311]
I was thinking in developing a feature where some data is sync to the user's Google Drive account so game state can be shared among different platforms.

The idea would be to have a "Sync" button in the main UI, which would sync local data with Cloud data, taking in account which one is more recent (newer data is pushed either upstream or downstream).

I usually play games on my Android device and my computer, so I usually share my progress between the two platforms. If the feature is accepted, I could start working on it myself.

**Comment by LunaMoo** [comment]
This was already requested/discussed in #1019 so I'll close this, if you happen to write such feature feel free to open pull request.
