### ISSUE TITLE
Updating fonts & Rebuilding the atlas

### ISSUE THREAD

**Issue by animaonline** [hrydgard/ppsspp#9313]
I'm trying to update the font and the background image, I have built the SDL version on macOS and got it working, but I've noticed that the fonts didn't change, I suspect that I need to rebuild the atlas, or whatever it's called? Could you please provide some details on how to do that?

**Comment by LunaMoo** [comment]
You have to build yourself an [atlastool](https://github.com/hrydgard/ppsspp/tree/master/ext/native/tools) then follow instructions from there. Feeding it with config file(default one is [here](https://github.com/hrydgard/ppsspp/blob/master/atlasscript.txt) you can just modify it) will result in 3 files. To change ui stuff, you get zim which goes to the assets replacing ui_atlas.zim and two files which describe it which should go to ui and replace ui_atlas.* files, then you have to build ppsspp with those new files.

 Don't expect it to be user friendly process through, there's no guarantee atlastool will even compile on your platform.

**Comment by animaonline** [comment]
Sounds kind of weird when you say that there's no guarantee that it will compile :)

But it looks like you're right, now it's complaining that freetype2/ftbitmap.h' file is not found.

I have installed the latest freetype lib from MacPorts, is there something else I could do?

**Comment by hrydgard** [comment]
This stuff is all a bit of a pain, I haven't really bothered to clean it up because it unintentionally also makes it slightly harder for people to release too many reskinned copies on google play :) Though people do that anyway so probably no point.

Right now I'm mostly focusing on stabilizing all the backends again after all the refactoring and implementation of D3D11 but I do intend to make this a lot nicer one of these days...

Anyway, you need to install freetype2-devel or something like that, IIRC.

**Comment by unknownbrackets** [comment]
Compiling the atlastool should be easier now, and require less steps.  See #12653.  It's also easier to replace the atlas without having to rebuild PPSSPP now.

After compiling atlastool, you can just run `./buildatlas.sh`.  You may need to copy the assets folder to the right place afterward.

I'm going to close this now given that it's easier but please do comment if there are still problems.

-[Unknown]

**Comment by Mark0kleon** [comment]
#12653. has not provided enough steps to build atlastool and zimtool, can't you provide steps to build atlas/zimtool
