### ISSUE TITLE
D3D11: Finish up

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#9317]
Remaining features to fix and/or implement:

 - [x] Framebuffer depalettization (FF: Type-0 shadows, Sonic Riders, etc)
 - [x] Framebuffer readback
 - [x] Framebuffer debug features, rework GE debugger to not use GL
 - [x] FramebufferManagerD3D11::BlitFramebuffer
 - [x] Postprocessing shaders (autotranslate from GLSL using SPIRV-Cross)
 - [x] Mysterious missing text in PaRappa
 - [x] Full support for "framebuffer blending" (REPLACE_BLEND_COPY_FBO)
      * DBZ: Tenkaichi Tag Team
      * https://github.com/hrydgard/ppsspp/pull/6350 ?
      * Requires BlitFramebuffer
 - [x] Logic op blend
 - [x] Make sure depth buffer copies work (Saint Seiya)
 - [x] Fix most resource leaks
 - [x] Fix all remaining significant resource leaks

For Windows 7:

- [x] Avoid using DXGI_FORMAT_B4G4R4A4_UNORM which is only available on Win8+

Please report other issues with D3D11 in this issue.

**Comment by mrcmunir** [comment]
NOTE : In the info shading language returned N/A  but load UI and render.

bugs detected 

Gripshift (Background) Black screen or partially in the logo REDMIE and no 3D  load can't view this problem not exist in DX9.

![screenshot_222](https://cloud.githubusercontent.com/assets/1274014/23064800/6d996102-f512-11e6-86e3-3c6d9fe842f2.png)

![screenshot_223](https://cloud.githubusercontent.com/assets/1274014/23064873/da8e4084-f512-11e6-8e5b-53d945fb2ee7.png)

**Comment by xebra** [comment]
I think it also needs backends selection menu in MainWindowMenu.cpp.

**Comment by hrydgard** [comment]
Thanks @xebra , adding that soon.

**Comment by zminhquanz** [comment]
@xebra if D3D11 backed work great , and you can continue to implement HW Tessellation

**Comment by hrydgard** [comment]
hardware tess for D3D11 should be as easy as with GL. I'll leave it for @xebra :)

**Comment by hrydgard** [comment]
Alright, that's three checkboxes :)

**Comment by mrcmunir** [comment]
@hrydgard  Grihpshift bug DX11 are fixed. only  has glitch flickering in the inferior of screen but this bug happen in DX9/OpenGL too  I open new issue for that?

**Comment by hrydgard** [comment]
Yeah, I think that deserves an issue. Please make a search first and see if there is one already, I don't remembre.

**Comment by xebra** [comment]
Yeah, now I'm trying :)

**Comment by tywald** [comment]
All of my games crashes when I try to open them if I turn on any kind of texture scaling(xBRZ etc.). Maybe it's just not implemented yet?

**Comment by hrydgard** [comment]
Good catch, I haven't tried that yet. I'll fix it up.

**Comment by hrydgard** [comment]
@tywald found the bug, committed a fix. Should be all good now.

**Comment by xebra** [comment]
I implemented it on DX11 but it has some issues similar as DX9 one.
I'll try to fix it so please wait a while.
Anyway, shader compilation very slower than OpenGL.

**Comment by hrydgard** [comment]
At least you shouldn't be running up against any limits in D3D11...

**Comment by xebra** [comment]
Probably fixed it without using "instanced tessellation" only with spline.
It's heavy duplicated vertex calculation at the edges of each patch.
Of course, it's no problem in bezier but it's wasted in spline.
This fixes probably improve also DX9 a bit.

Well, DX11 backend still buggy on my PC(Win7), so I can't test well.
The error occurs almost always in CheckAlphaRGBA8888SSE2(), I avoided this issue with commented out this SSE version function, I think this may be alignment issue.

Also, FF4CC doesn't work with unstable error. FF4 is the best platform with testing about spline/bezier.
I know Win7 still unsupported, so I'll wait for this backend more improved :)

**Comment by hrydgard** [comment]
Oh, yes, that sounds like a possible alignment issue - are you on 32-bit? On 64-bit all allocations should be aligned by default.

Though the main issue on windows 7 is that for some silly reason the B4G4R4A4 texture format is not supported so we need to upconvert those textures to RGBA8888, which is a pain because the code currently assumes that the format converted to has the same amount of bits...

**Comment by hrydgard** [comment]
@xebra  I fixed the alignment crash.

**Comment by xebra** [comment]
Thanks!
Well, I'm on 64-bit anyway.

**Comment by xebra** [comment]
Ah, this fixes for 32-bit...
Hmm, anyway, Now I'm testing.

**Comment by xebra** [comment]
Noooo, I was misunderstanding.
I'm using Win7 64-bit but ppsspp builds was 32-bit so it's fixed :)

**Comment by xebra** [comment]
I saw the issue about Win7. It's 16-bit texture format issue, I think it also crashes with 5551 and 565 not only 4444.
Tales of Eternia is using format 5551, and crashes when texture creation.
I searched about format, 16-bit textures are supported DX11.1 or higher. Win7 must be supported DX11.1 with SP1 applied hotfix KB2670838. I'm using Win7 SP1 and already applied it but error occurs...
Probably Win7 is supported the formats but error occurring because of runtime-library bug...?

**Comment by mrcmunir** [comment]
@xebra Pixel formats 5551, 565 or 4444 Only implemented in Windows 8 and higher.

So these variables
DXGI_FORMAT_B5G6R5_UNORM
DXGI_FORMAT_B5G5R5A1_UNORM
DXGI_FORMAT_B4G4R4A4_UNORM

Microsoft never implemented it under Windows 7 system

**Comment by hrydgard** [comment]
Yup, so we'll need to convert them all to 32-bit texture formats to work correctly on Win7. Silly of Microsoft, I guess they didn't think anyone would want such poor texture formats anymore, but we do :) And so did others because they're back in Win8.

**Comment by xebra** [comment]
Yeah, it's silly decision anyway :(

**Comment by xebra** [comment]
CreateTexture() must returns success or fail, if 16-bit texture is unsupported, it must return fail(reason is unknown/unsupported format), but crashes in the function so it's a BUG I mean.

**Comment by hrydgard** [comment]
Well, not really a bug, it's defined not to work. So we'll just work around it. Well, I will. Soon :)

**Comment by xebra** [comment]
I found a bug with Pursuit Force. See below. This seems polygons flipped front face to back face.

![ucus98703_00000](https://cloud.githubusercontent.com/assets/1607422/23146487/905236e6-f81a-11e6-8119-ddc1b2c35efc.jpg)
![ucus98703_00001](https://cloud.githubusercontent.com/assets/1607422/23146495/aef65d48-f81a-11e6-8957-7e12723d4930.jpg)

**Comment by xebra** [comment]
Hmm, maybe depth buffer or alpha blending issue...

**Comment by hrydgard** [comment]
Yeah, looks more like broken depth buffering...

**Comment by hrydgard** [comment]
@xebra , Now that that's been merged, should no longer crash on 16-bit textures on D3D11. Please try it :)

**Comment by xebra** [comment]
@hrydgard Nice work, thanks :)

**Comment by LunaMoo** [comment]
D3d11 still closes on boot for me on win 7 when not running with VS debugger attached, but I used CodeXL to debug and got https://github.com/hrydgard/ppsspp/blob/master/ext/native/thin3d/thin3d_d3d11.cpp#L752 with 
```
The thread tried to read or write data that is misaligned on hardware that does not provide alignment. For example, 16-bit values must be aligned on 2-byte boundaries; 32-bit values on 4-byte boundaries, and so on.
```

Win 10 unaffected.

**Comment by hrydgard** [comment]
But it does work with it attached? 

Bizarre that alignment would be an issue when callign the shader compiler. Same result with both 32-bit and 64-bit builds?

**Comment by LunaMoo** [comment]
Yeah with VS debugger attached it does run fine.

**Comment by hrydgard** [comment]
You should be able to attach MSVC to the crashed binary before pressing the close button in the dialog that comes up (in some cases the crash dialog should even display a debug button but I can't remember what makes that happen). I'm baffled though.

**Comment by hrydgard** [comment]
Dolphin uses the old D3DX11CompileFromMemory instead, though I think nowadays that just forwards to D3DCompile. Not sure if it would be worth doing the same for backwards compatibility with something.

**Comment by LunaMoo** [comment]
One of my pc's was just closing without any error, but with another I could attach debugger after crash, maybe something useful here:
![crash](https://cloud.githubusercontent.com/assets/5485237/23235236/10527ece-f955-11e6-937e-ac0e7373ffc2.png)

**Comment by hrydgard** [comment]
We can see that ptr_D3DCompile is nullptr. That makes it impossible to build shaders so we need to bail.

Probably simply need to use Dolphin's method to load the shader compiler as it's more backwards compatible.

However, the thing where it only worked in the debugger on one of your PCs is still odd.

**Comment by LunaMoo** [comment]
I mean it works from the debugger on both pc's, but if I run ppsspp normally outside of VS, only one pc get's error message, the other closes silently.
Maybe this is also useful:
![crash2](https://cloud.githubusercontent.com/assets/5485237/23235515/1282afec-f956-11e6-8ef2-68e4db499e96.png)

**Comment by xebra** [comment]
I got the same issue. I think this issue is missing DLL.
So take the "d3dcompiler_47.dll" to the folder of exe's root or "Windows/System32(SysWOW64)", it fixed. 
Seems Win7 doesn't have the DLL by default, however VS has it in "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin".

**Comment by hrydgard** [comment]
Hm, I wonder what you need to install to get it, like a DX redistributable or something. Or if there's another version that's available by default.

**Comment by LunaMoo** [comment]
Thanks for the hint xebra, I copied C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64 into C:\Windows\System32 and 64 bit build works fine:). And indeed this file is installed with Win 10(althrough slightly different version than the VS one).

**Comment by mrcmunir** [comment]
d3dcompiler_47.dll found in SDK windows 8.1 so maybe fault too in Windows 8 .


Windows Kits\8.1\Redist\D3D\x64 -> For Runtime x64
Windows Kits\8.1\Redist\D3D\x86 -> For Runtime x86

**Comment by xebra** [comment]
BTW, running on Win7 works fine so we don't need below code in GameSettingsScreen.cpp anymore :)
```
	if (!DoesVersionMatchWindows(6, 2)) {
		// Hide the D3D11 choice if Windows version is older than Windows 8.
		// We will later be able to support Windows 7 and Vista (unofficially) as well,
		// but we currently depend on a texture format that's only available in Win8+.
		renderingBackendChoice->HideChoice(2);  // D3D11
	}
```

**Comment by hrydgard** [comment]
So the issue is that while the latest available version of DirectX for a Windows version is always installed by Windows Update, D3DCompiler.dll is not: https://msdn.microsoft.com/en-us/library/ee416644.aspx

"Note  The HLSL compiler (D3DCompile*.dll) and the D3DX utility library for Direct3D 11 (D3DX11*.dll) are not built into any version of the Windows operating system, but they can be deployed as part of an application's installer by using the existing DirectSetup technology; for more information about using DirectSetup, see DirectX Installation for Game Developers"

Most games can precompile their shaders so you don't need to ship the compiler, but we can't.

Sigh. So will need to redistribute it somehow, I wonder if it's alright to just grab the _47 DLL and ship it or if we should link to an installer.

**Comment by hrydgard** [comment]
Apparently it is alright to redistribute it, at least according to this answer:

http://stackoverflow.com/questions/25873609/directx-11-2-development-on-windows-7d

**Comment by hrydgard** [comment]
wrong button
