### ISSUE TITLE
PPSSPP doesn't seem to support PSP_O_EXCL

### ISSUE THREAD

**Issue by Hydroque** [hrydgard/ppsspp#9322]
Initiative:
I am using PSPDEV PSPSDK. I am trying to compile my program, using the PSP_O_EXCL flag on my file io operations, however, the sceIoOpen doesn't return an error. This is breaking. This is under the windows build and has not been tested on any other. I have done some extensive testing. I cannot affirm that this problem is an asynchronized only feature or it works with the asynchronized functions.

Description:
PSP_O_EXCL doesn't cause an error when file already exists

Debugging:
It is affirmed to work on a PSP
Tested only in Windows 7
It doesn't matter what combination of bit-flags you use

Example:
```
	int uid = sceIoOpen(path, PSP_O_WRONLY | PSP_O_CREAT | PSP_O_EXCL, | PSP_O_TRUNC, 0777);
	printf("Opened file: %d\n", uid); // 4
	if(uid < 0)
		crash(uid, "Opening File", "File could not be opened!");
```

PSP_O_EXCL is 0x0800

Testcase

The src, makefile, and the files are included in the zip. In the root of the zip are the makefile, main.c, and the test.txt. text.txt is copied into the bin folder by the build bat file. Run executes the EBOOT.PBP in the bin folder with ppsspp. The bin folder houses a built PBP, elf, PARAM.SFO, diff.txt (file which should error), test.txt (copied, and read from by program), test2.txt (created by the program if not found). The EBOOT.PBP in bin is built for running on PPSSPP in that the path is set up properly to run on both machines. The EBOOT.PBP in bin2
[bin.zip](https://github.com/hrydgard/ppsspp/files/785407/bin.zip)

 is built for running on PSP for the same reason. Not all EBOOT.PBP are umd's, and the difference doesn't seem to be present between the two machines.

**Comment by hrydgard** [comment]
Yeah, this is probably a bug. Nice catch!

**Comment by Hydroque** [comment]
Thanks, writing a tutorial for IO operations at https://en.wikibooks.org/w/index.php?title=PSP_Development and I wanted to make sure I understood what I was talking about. I think its in order to check everything. Where it is affirmed RDONLY, WRONLY, RDWR, DIROPEN, APPEND, CREAT, TRUNC are tested successful. I have not a clue what NBLOCK or NOWAIT does. I haven't even gotten to seeking files with PSP_O_SET/CUR/END.

#define 	PSP_O_RDONLY   0x0001
#define 	PSP_O_WRONLY   0x0002
#define 	PSP_O_RDWR   (PSP_O_RDONLY | PSP_O_WRONLY)
#define 	PSP_O_NBLOCK   0x0004
#define 	PSP_O_DIROPEN   0x0008
#define 	PSP_O_APPEND   0x0100
#define 	PSP_O_CREAT   0x0200
#define 	PSP_O_TRUNC   0x0400
#define 	PSP_O_EXCL   0x0800
#define 	PSP_O_NOWAIT   0x8000
#define 	PSP_SEEK_SET   0
#define 	PSP_SEEK_CUR   1
#define 	PSP_SEEK_END   2

To further my quest, does PPSSPP define anything that I can easily grab in my source file to switch between the two? Such as a flag like, #ifndef __cplusplus

**Comment by hrydgard** [comment]
Well since you compile one binary using PSPSDK and run it on both PSP and PPSSPP (I suppose) then you can't use compile time checks like ifdef, you need a runtime check. And I discourage using those because if you start depending on differences in behavior you're screwed if PPSSPP fixes the differences, best to fix the emulator.

That said, there are definitely ways. PPSSPP's VFPU emulation is not 100% accurate, there are missing system functions, etc.

**Comment by Hydroque** [comment]
I was never expecting it to be perfect. I am in the process of making a work around via PPSSPP. In the case that it does fix, the operation will still be the same as expected. It is also my job to keep updated, and anything archived is definitely worth exploring if it is the latest. It would be bad practice to have readers of the article do that small fix. It is definitely much easier to state that it is broken. I might mention it is broken on Windows 7.

It was an example. Is there any definite runtime checks I can do?

**Comment by hrydgard** [comment]
Well, O_EXCL isn't the most important feature ever. I think it's fine if you leave it out of your tutorial and move on to other subjects until it can be fixed in the emulator.

I will fix this in PPSSPP though, but it's not top priority.

**Comment by Hydroque** [comment]
Continuing the conversation about my tutorial is out of the scope of this thread. I feel like I have nothing further to add that is on topic.

**Comment by hrydgard** [comment]
Well, this was easy enough. If you're building PPSSPP yourself, can you try that pull request? 

Hopefully that fixes it on both Windows and unix.

**Comment by Hydroque** [comment]
Confirmed works in latest commit with light testing.
