### ISSUE TITLE
Supporting OpenGL 3.0 instead of 2.0 for newest iOS devices (feature request)

### ISSUE THREAD

**Issue by iOS4all** [hrydgard/ppsspp#9323]
@hrydgard hi there. I just wondering why until now using OpenGL 2.0 of ppsspp instead of 3.0
If you can see from iPhone 5s and up as well as from iPad Air and up they use OpenGL 3.0.  but under these devices it just uses OpenGL 2.0
Maybe it could help for enhancing performance if we support it besides 64-bit and metal api rendering (in the future).

Thanks.

**Comment by hrydgard** [comment]
It's better to go directly to Metal, which I plan to do sometime later this year. Our OpenGL code is mostly aimed at compatibility with older devices, and I intend for it to become the "legacy" option and use better API:s where available.

Here's the end goal:

 - D3D11 or Vulkan on Windows, D3D9 as fallback for very old Windows
 - Vulkan on newer Android and modern Linux
 - OpenGL ES on older Android and legacy Linux platforms
 - Metal on iOS and MacOS

As you can see, spending time on minor OpenGL improvements does not make sense.

**Comment by iOS4all** [comment]
@hrydgard I see. Yeah I clearly understand now. So yeah it's better to go directly to metal instead of OpenGL.
