### ISSUE TITLE
Rainbow Six: Vegas graphics glitch (now: performance)

### ISSUE THREAD

**Issue by Levan7** [hrydgard/ppsspp#9324]
I am using the v1.3-660-gbd63143 build and noticed this graphics problem.
[log.zip](https://github.com/hrydgard/ppsspp/files/785020/log.zip)
![ulus10206_00000](https://cloud.githubusercontent.com/assets/5770076/23093330/a416f496-f5f9-11e6-8bf1-9206324475df.jpg)

**Comment by LunaMoo** [comment]
If I recall this glitch was caused by simulating block transfer effects. Not sure if any real effect goes missing when disabling those or not as the game doesn't appear to use it for anything obvious.

**Comment by hrydgard** [comment]
Looks like a typical "bloom cascade" effect that going slightly out of bounds. Due to the way the PSP GPU works we have to guess how large to make our virtual framebuffers, and there's still more tweaking left to do.

**Comment by unknownbrackets** [comment]
Does this happen in all backends (like Vulkan and Direct3d!!) in the latest git build?  To confirm, it doesn't happen in software rendering, right?

-[Unknown]

**Comment by hrydgard** [comment]
Is this on Android or PC? Does it still happen?

**Comment by marosis** [comment]
I think this Is same problem what was in tombraider. Try newest build

**Comment by ppmeis** [comment]
Tested with latest build, default settings Vulkan, OpenGL and Direct3D11 same issues:
![image](https://user-images.githubusercontent.com/4381277/33936551-3b360010-e000-11e7-82ae-fa2222a55f90.png)

@unknownbrackets it doesn't happen in software rendering:
![image](https://user-images.githubusercontent.com/4381277/33936652-8a07f018-e000-11e7-9f53-033d413cba6e.png)

**Comment by Levan7** [comment]
Still happening on v1.6

**Comment by weihuoya** [comment]
It's like a  depal issue, disable slower effect will fx issue.

with this two lines code,  sonic rival 2 become a little bright and Rainbow Six glitch, but fx regression.

Is it need delay to set depal false ?
```c++
void TextureCacheVulkan::ApplyTextureFramebuffer(TexCacheEntry *entry, VirtualFramebuffer *framebuffer) {
	} else {
		entry->status &= ~TexCacheEntry::STATUS_DEPALETTIZE;

		framebufferManager_->RebindFramebuffer();  // TODO: This line should usually not be needed.
		imageView_ = framebufferManagerVulkan_->BindFramebufferAsColorTexture(0, framebuffer, BINDFBCOLOR_MAY_COPY_WITH_UV | BINDFBCOLOR_APPLY_TEX_OFFSET);
		
		// remove follow two lines
		//drawEngine_->SetDepalTexture(VK_NULL_HANDLE);
		//gstate_c.SetUseShaderDepal(false);

		gstate_c.SetTextureFullAlpha(gstate.getTextureFormat() == GE_TFMT_5650);
	}
}
```

**Comment by unknownbrackets** [comment]
It sounds like that just means we're texturing from a framebuffer when we draw this garbage, without depal (or with failed depal?)

In that case, it could be a framebuf upload we don't detect is supposed to clear this texture, or it could be an FBO that was decimated earlier and never saved a clear.

-[Unknown]

**Comment by unknownbrackets** [comment]
Could you try exporting a GE debugger dump on PC?

To do this, open the game and select Debug -> GE debugger..., then when it's displaying the scene, press Record in the top right.  After a second or so, it'll finish and save a trace of the drawing activity.

After that, check the memstick/PSP/SYSTEM/DUMP folder and it'll have created a file named something like "ULES12345_0000.ppdmp".  You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by ppmeis** [comment]
@unknownbrackets tested with latest Windows build, same issues. GE Debugger dump:

[ULES00584_0001.zip](https://github.com/hrydgard/ppsspp/files/2363776/ULES00584_0001.zip)

**Comment by unknownbrackets** [comment]
We're definitely blooming some bleed in there.  The source is mostly black - I wonder if we're missing a memcpy download of the video RAM.

-[Unknown]

**Comment by Gamemulatorer** [comment]
Issus still present using the latest git build of ppsspp v1.9.3-998
![Screenshot_20200604-134905](https://user-images.githubusercontent.com/37603562/83719739-51f55c00-a66a-11ea-9944-1d64d67fa7d8.png)

**Comment by twitchplaystrading** [comment]
I've tried disabling Simulate Block Transfer Effects on Android but the glitch persists with both OpenGL and Vulkan. 

Device: Samsung Galaxy Z Flip 3 5G
GPU: SD 888

**Comment by EternalsDarkhole** [comment]
> I've tried disabling Simulate Block Transfer Effects on Android but the glitch persists with both OpenGL and Vulkan.
> 
> Device: Samsung Galaxy Z Flip 3 5G GPU: SD 888

Did you try the latest build of ppsspp from automated buildbot?

**Comment by twitchplaystrading** [comment]
> > I've tried disabling Simulate Block Transfer Effects on Android but the glitch persists with both OpenGL and Vulkan.
> > Device: Samsung Galaxy Z Flip 3 5G GPU: SD 888
> 
> Did you try the latest build of ppsspp from automated buildbot?

Thank you for the suggestion. I did try the latest one 1.12.3-980-g3bfab6326. Software rendering removes it but it's basically unplayble (~1 fps). 
![photo6106995010588225907](https://user-images.githubusercontent.com/74666134/155641371-9da3dfef-5ddb-4b58-a776-26b8c58e3122.jpg)
![photo6106995010588225908](https://user-images.githubusercontent.com/74666134/155641379-f175f6d9-131b-4e6e-8b85-01b97f4f12ac.jpg)

**Comment by EternalsDarkhole** [comment]
@twitchplaystrading just use vulkan without block transfer effects enable and try to disable also hw transform.

**Comment by Gamemulatorer** [comment]
Can no longer reproduce this issue but this game now is super slow...
I'm using ppsspp https://github.com/hrydgard/ppsspp/commit/2097a9c39baaeaf74205def5cf755756811e16e3
![Screenshot_2022-09-27-01-04-06-10](https://user-images.githubusercontent.com/37603562/192337826-8487b75c-0d0a-4ca1-adb4-eb43cbe01f7d.png)
[ULUS10206.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/9648240/ULUS10206.ppdmp.zip)

**Comment by hrydgard** [comment]
Good that the artifact is gone, but the slowness is not expected, will look at it!

**Comment by Gamemulatorer** [comment]
This looks better in terms of performance.
![Screenshot_20221125_144622_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37603562/203917563-ac020816-2b39-47e9-9dd8-60ecd2666971.jpg)

**Comment by hrydgard** [comment]
Cool. Still slightly slower than before though, or is it?

Either way, I'm postponing any further work on this until after 1.14.

**Comment by ppmeis** [comment]
Tested in latest build. A bit of performance impact in certains moments:

![image](https://user-images.githubusercontent.com/4381277/208267458-85fcca7b-99b1-48a4-8f33-39384e0023e6.png)
