### ISSUE TITLE
PPSSPP Passes Incorrect Argument

### ISSUE THREAD

**Issue by Hydroque** [hrydgard/ppsspp#9326]
Initiative:
It seems like the default location, which is passed to the program, is umd0:/EBOOT.PBP. However, things booted from the memory stick should have the path ms0:/PSP/GAME/folder/EBOOT.PBP. This could be potentially breaking in some applications or games.

One suspected fix is to use iso/bin to determine a UMD and let raw EBOOT.PBP emulate ms0:/PSP/GAME/folder/EBOOT.PBP, while instead writing to where it is located. However, the latter seems to have a problem when previous directories are referenced, such as the MUSIC folder. The same problem occurs when the EBOOT.PBP is in the ppsspp/memstick/PSP/GAME/folder directory.

Current workaround is coding the program based on target platform. It should be stated there is also directory listings and recursive iterations thereof who may be affected.

Related Issues:
#7872

Expected:
Things booted from the umd are passed umd0:/EBOOT.PBP
Things booted from the memstick are passed ms0:/PSP/GAME/folder/EBOOT.PBP

**Comment by hrydgard** [comment]
That pull request should take care of it, feel like testing it before I merge?

**Comment by Hydroque** [comment]
You want me to test before you merge to master branch?

**Comment by hrydgard** [comment]
I think most homebrew is designed to work on actual PSPs, and it should all work.

Well now that it's on master, you can download a fresh Windows build here:

**Comment by Hydroque** [comment]
Confirmed working with light testing.
