### ISSUE TITLE
Default Folder Location

### ISSUE THREAD

**Issue by Hydroque** [hrydgard/ppsspp#9333]
I noticed that initially PPSSPP didn't have a full memstick folder including everything from a formatted magic gate memory stick duo. Possible breakage on applications that will want access to other folders to display information. Also, support for homebrew and PS1 games (they come in form of PBP).

Root
> MUSIC
> PICTURE
> VIDEO
> PSP
> > COMMON
> > GAME
> > SAVEDATA
> > THEME

Another thing that is very related is the start location of PPSSPP. It seems to start at the directory listing, ignoring your 'last played location' and 'the memstick PSP/GAME' folders. It would be a cool improvement to have hotkeys for such a task instead of navigating to where the memory stick is stored each time.

**Comment by hrydgard** [comment]
Well, the Homebrew tab is already a shortcut to PSP/GAME, effectively, and there are definitely possible improvements to navigation. There is already a mechanism to save shortcuts to folders, the  "+" directories, but it's highly unintuitive.

Point taken about the missing folders, thought - it really should auto create at least the ones under PSP.

**Comment by Hydroque** [comment]
Woah the homebrew tab wasn't immediately apparent to me. I guess it was back when I was trying to build the directory chain myself for PSP, having to learn that memstick folder needed creating. I understand what you mean by the "+" being inintuitive. I do see what possible improvements you are talking about the homebrew tab. For one, there is a button that doesn't work that will pan with the amount of homebrews listed. The other is the identification of such homebrews. You have to right click each of the ? pictures in order to know which one you are picking. I might want to add that my recent is being flooded by such homebrew. Maybe a recent homebrew separate from iso games?

**Comment by Hydroque** [comment]
Guess which one is UserInput tutorial
![image](https://cloud.githubusercontent.com/assets/7494772/23125979/9638979a-f742-11e6-93ac-685804e1542d.png)

**Comment by hrydgard** [comment]
Haha, yeah, I know that's a bit hopeless. Should be able to do better.

You can switch both the Games and the Homebrew to a list view with text names, maybe should add that capability to Recent as well.

**Comment by Hydroque** [comment]
Well with the addition of proper homebrew support you did with correcting the path, I think this leads up very well to a next step!

**Comment by hrydgard** [comment]
By the way, here's a quick tip: Go into PSP/SYSTEM/ppsspp.ini and change GridView1 = False . That way you will get a listview on Recent, though there's no UI for changing this setting.

**Comment by LunaMoo** [comment]
~ I hope it will stay that way:P, don't like the idea of sacrificing a row just for two square icons it looks bad  and I belive that was the reason of removing them from recent list to begin with. We could find a different place for those buttons through which could also make homebrew list a bit nicer to look at.

**Comment by Hydroque** [comment]
To be honest, everything is jampacked and scales with the window. I think more space allocation would be a nice first step in improving the UI, but that conversation is for a new issue, and out of scope for this issue.

**Comment by Hydroque** [comment]
This is NOT fixed. On second run, the folders are created. This should probably be either first run or if not exist.

**Comment by hrydgard** [comment]
Woops, I didn't test in an empty folder. Fixing.

**Comment by hrydgard** [comment]
That should take care of that.

**Comment by Hydroque** [comment]
Let me verify
