### ISSUE TITLE
Possible bug in .PBP ISO looks bogus? Giving up

### ISSUE THREAD

**Issue by mrcmunir** [hrydgard/ppsspp#9336]
I detected when some folder has .PBP returned ISO looks bogus you can't into in that folder I think is a bug tested in SDL2 linux.

**Comment by LunaMoo** [comment]
Any chance you happen to have PARAM.SFO inside that folder?

 PPSSPP might be just treating it as an extracted game and tries to load the folder as a game, hence doesn't allow you to enter it like a folder. I considered that planned feature, through I tend to delete all other files so it's not a problem for me.

**Comment by mrcmunir** [comment]
It  happened me with some PSX image to .PBP
could it be improved that the folder will not be hidden when a file bogus ISO problem detected?

Anyway  separating the affected images from the folder solved the problem.

**Comment by hrydgard** [comment]
The idea behind the folder thing is to get a nice listing when games are in folders like they usually are in PSP/GAME. It is annoying in this case though yeah.
