### ISSUE TITLE
sceIoDread

### ISSUE THREAD

**Issue by tilkinsc** [hrydgard/ppsspp#9344]
```
	while(sceIoDread(uid, &dir) > 0) {
		if(dir.d_name[0] == '.')
			continue;
		printf("Read.\n");
		printf("%s \n", dir.d_name);
		printf("name gotten.\n");
	}
```
The above works fine.

```
	while(sceIoDread(uid, &dir) > 0) {
		printf("Read.\n");
		printf("%s \n", dir.d_name);
		printf("name gotten.\n");
	}
```

The above crashes.

Initiative:
sceIoDread() returns, on the PSP, d_name . for one iteration. While making a homebrew, which transverses the filesystem, it should be known that PPSSPP doesn't crash on attempts to feed char d_name[256] to the printf function while there is only . So I am wondering if there is unexpected leniency between both PSP and PPSSPP. This means %s and %c are interchangeable for the first value and char d_name[256] acts as a %s when the PSP reads it as %c.

**Comment by hrydgard** [comment]
Uh, so d_name is not zero terminated on the PSP if it is '.'?  That's weird and surprising. I wouldn't expect either loop to crash, really.

If you memset(&dir, 0, sizeof(dir)); before each sceIoDread call, what happens then?

**Comment by Hydroque** [comment]
That is what I originally thought - it wasn't null terminated. Being an array of char, though, they are automatically set to 0. It may be possible that a fully filled char array isn't null terminated, for you would end up having to free it if it isn't automatic. So the buffer would be 255 instead of 256.

Anyways, it is null terminated by definition, but it seems like it is default passed as a single char...

Could you tell me your thoughts on ``memset(&dir, 0, sizeof(dir))`` and what the variables point to?

**Comment by hrydgard** [comment]
"Being an array of char, though, they are automatically set to 0" 

That just isn't true.

struct x_thing { char hello[256]; }

int main() {
  x_thing my_x;
  // my_x.hello is garbage, not zero-initialized
  // to zero initialise:
  memset(&my_x, 0, sizeof(my_x));
  // my_x.hello is now zero-initialized
}

**Comment by Hydroque** [comment]
Sorry that was a grammar error.

**Comment by hrydgard** [comment]
Either way, printf is not a built-in HLE function, it's in libraries that are linked to your program. So the only difference here (excluding CPU emulation bugs, but those aren't likely for such basic things) can be in what sceIoDread() writes to the struct, and how that can cause or not cause that kind of crash I don't quite understand.

**Comment by Hydroque** [comment]
I understand what you mean. PPSSPP does a good job in crashing when it needs to. Since all the core PSP libraries are mapped (http://psp.jim.sh/pspsdk-doc  https://github.com/pspdev/pspsdk/blob/master/src/ctrl/sceCtrl.S) it is no problem that writing for the PSP should produce problems PSP-specific. I am just reporting things I find which works on PPSSPP that doesn't on the PSP.

**Comment by tilkinsc** [comment]
So I found out what was wrong with this after reading through my terrible explanation.

When I listed the directory, I was getting `.` and `..` which thereof wasn't present in one of PPSSPP or PSP. I guess I never reported this. My solution was to skip `.` and `..` (as they were just eye candy for trans-versing the directory).

**Comment by unknownbrackets** [comment]
If we're listing `.` or `..` somewhere the PSP doesn't, that's a bug.  Do you know what directory it was - have a test app showing this?

-[Unknown]

**Comment by tilkinsc** [comment]
Let me run some tests when I get to it.

**Comment by tilkinsc** [comment]
This is my test case
<details>
<summary>216 Lines of C code</summary>

```
// include psp stuff
#include <pspkernel.h>
#include <pspdebug.h>
#include <pspdisplay.h>

// calloc, malloc, relloc
#include <stdlib.h>
// snprintf
#include <stdio.h>

// include commons stuff
#include "../common/callback.h"


// configure PSP stuff
#define VERS    1
#define REVS    0

PSP_MODULE_INFO("FileIO", PSP_MODULE_USER, VERS, REVS);
PSP_MAIN_THREAD_ATTR(PSP_THREAD_ATTR_USER); 

// make printing easier on us
#define printf pspDebugScreenPrintf


// limits.h doesn't have PATH_MAX
#define PATH_MAX 4096


#define TITLE "bin"

// #define ROOT "ms0:/PSP/GAME/" TITLE "/"
#define ROOT "umd0:/"


void crash(int error, const char* crasher, const char* message) {
	sceDisplayWaitVblankStart();
	printf("Error (%d) : %s\n", error, crasher);
	printf("%s\n", message);
	sceKernelSleepThread();
}

void test_crash() {
	sceDisplayWaitVblankStart();
	printf("No crash occured.");
	sceKernelSleepThread();
}



void check_file(SceIoStat* info, const char* path) {
	// open file description
	int status;
	if((status = sceIoGetstat(path, info)) < 0)
		crash(status, "Checking File", "File not found or no access!");
}

int open_file(const char* path, int params, int chmod) {
	// open file handle
	int uid = sceIoOpen(path, params, chmod);
	if(uid < 0)
		crash(uid, "Opening File", "File not found or no access!");
	return uid;
}

void close_file(int uid) {
	int status;
	if((status = sceIoClose(uid)) < 0)
		crash(status, "Close File", "File could not be closed!");
}

void write_file(int uid, const char* out, int size) {
	// write to file
	if(sceIoWrite(uid, out, size) != size)
		crash(uid, "Writing File", "File wrote incorrect number of bytes!");
}

void read_file(int uid, char** out, int size) {
	// allocate, read into buffer, pad with \0
	char* buffer = calloc(size+1, sizeof(char));
	if(buffer == 0)
		crash(0, "Memory Allocation", "Memory allocation failed!");
	int read = sceIoRead(uid, buffer, size);
	if(read != size)
		crash(read, "Read File", "File size read doesn't match expected!");
	buffer[size] = '\0';
	*out = buffer;
}



void do_example1() {
	const char* src = ROOT "test.txt";
	
	// Reading file (existant) src > (char*) file_data
	char* file_data;
	SceIoStat info;
	check_file(&info, src);
	
	printf("%d\n", (int)info.st_size);
	
	int uid = open_file(src, PSP_O_RDONLY, 0777);
	read_file(uid, &file_data, (int)info.st_size);
	close_file(uid);
	
	printf("Read data:\n");
	printf("%s\n", file_data);
	free(file_data);
	file_data = 0;
}

void do_example2() {
	const char* new = ROOT "test2.txt";
	const char output[] = "Hello World 123\nabc";
	
	// Writing new file output[] > (non-existant) test2.txt
	int uid = open_file(new, PSP_O_WRONLY | PSP_O_CREAT | PSP_O_EXCL | PSP_O_TRUNC, 0777);
	write_file(uid, output, sizeof(output)-1);
	close_file(uid);
}

void do_example3() {
	const char* src = ROOT "test.txt";
	const char* out = ROOT "diff.txt";
	
	// Copy file test.txt > diff.txt
	char* file_data;
	SceIoStat info;
	check_file(&info, src);
	
	// multiple files can be open at once, but since using one variable
	// closing the file would be wise before losing the data
	int uid = open_file(src, PSP_O_RDONLY, 0777);
	read_file(uid, &file_data, (int)info.st_size);
	close_file(uid);
	
	uid = open_file(out, PSP_O_WRONLY | PSP_O_CREAT | PSP_O_TRUNC, 0777);
	write_file(uid, file_data, (int)info.st_size);
	close_file(uid);
	
	free(file_data);
	file_data = 0;
}

void get_files() {
	
	const char* src = ROOT;
	
	// open the directory
	int uid = sceIoDopen(src);
	if(uid <= 0)
		crash(uid, "Directory Iteration", "Failure or empty directory");
	
	printf("Opened, reading directory.\n");
	
	// iterate over the directory for files, print name and size of array (always 256)
	// this means you use strlen() to get length of file name
	SceIoDirent dir;
	char temp_name[PATH_MAX]; // 4096 is linux's forced policy
	while(sceIoDread(uid, &dir) > 0) {
		printf("Read `%s` (%d) \n", dir.d_name, sizeof(dir.d_name));
		
		// format a path, print it (remember to include stdio.h)
		snprintf(temp_name, PATH_MAX, "%s%s", ROOT, dir.d_name);
		printf("@%s\n", temp_name);
	}
	
	printf("Done reading directory.\n");
	
	// clean up
	sceIoDclose(uid);
}



int main(int argc, char** argv)
{
	// basic init
	setupExitCallback();
	pspDebugScreenInit();
	
	sceDisplayWaitVblankStart();
	pspDebugScreenSetXY(0, 0);
	
	printf("Dumping args\n");
	int i;
	for (i=0; i<argc; i++)
		printf("%s\n", argv[i]);
	printf("Done.\n");
	
	printf("%s\n", ROOT);
	
	// printf("Reading file\n");
	// do_example1();
	// printf("Done.\n");
	// printf("Writing file\n");
	// do_example2();
	// printf("Done.\n");
	// printf("Copying file\n");
	// do_example3();
	// printf("Done.\n");
	
	printf("Listing ROOT files...\n");
	get_files();
	printf("Done.\n");
	
	while(!isRunning()) {
		sceDisplayWaitVblankStart();
	}

	// Sleep Thread
	sceKernelSleepThread();
	
	sceKernelExitGame();
	return 0;
}
```

</details>

Here is the output from this program. As you can see `@umd0:/.` and `@umd0:/..` are invalid directories. This isn't on PSP when I test it. umd0:/ is the ROOT directory, which is passed through to the main function as the argument where the program was executed from. As you note the ROOT macro, this is changed in the ordinance of EBOOTS/ISOs being outside of `PPSSPP/MEMSTICK/PSP/GAME/FOLDER/*`.

![image](https://user-images.githubusercontent.com/7494772/40871240-1d82e5c4-6606-11e8-82e6-aabd8f38011e.png)

**Comment by unknownbrackets** [comment]
Ah - when we mount a directory as `umd0:/` (instead of an ISO), we're probably indeed listing `.` and `..`.  Maybe we could just check `GetLocalPath(path) == basePath` or something.

-[Unknown]

**Comment by tilkinsc** [comment]
It does it on mount as PSP/GAME/FOLDER/* too, except the screenshot doesnt update @umd0:/ to be the correc tone

![image](https://user-images.githubusercontent.com/7494772/40872308-13929104-661a-11e8-9536-c1bd53a960d0.png)

**Comment by tilkinsc** [comment]
It also does it on ms0:/PSP/GAME/*/EBOOT.PBP

![image](https://user-images.githubusercontent.com/7494772/40872330-90b3600a-661a-11e8-9281-791a8af0a790.png)

**Comment by unknownbrackets** [comment]
Wait, you're saying that if I list ms0:/PSP/SAVEDATA on a real PSP, it lists `.` and `..`, but if I list ms0:/PSP/GAME/bin it doesn't?

-[Unknown]

**Comment by tilkinsc** [comment]
No, same effect.

**Comment by tilkinsc** [comment]
So I take it you were able to reproduce the problem?

**Comment by unknownbrackets** [comment]
Just for directories.

-[Unknown]

**Comment by tilkinsc** [comment]
Yeah exactly! Good work 👍 as I explore more of the API I will open up these 'useful' bug reports. I admit I haven't much as of late because I have been programming my LuaConsole project. Good to know that these minor details aren't being ignored.
