### ISSUE TITLE
Is Vulkan backend abandoned?

### ISSUE THREAD

**Issue by Sunderland93** [hrydgard/ppsspp#9349]

**Comment by Hydroque** [comment]
No. A quick look up in code shows very active development https://github.com/hrydgard/ppsspp/tree/master/GPU/Vulkan

**Comment by xebra** [comment]
Unfortunately, actually Vulkan backend is still unstable.
So I think we need to gather issues and informations about Vulkan to one thread like D3D11 to improve this backend more.

**Comment by hrydgard** [comment]
@Hydroque That development is just keeping it in sync with the others while refactoring.

It will return to development though! Just need to finish D3D11 and the UWP port and 1.4...

**Comment by MarcoEstevez** [comment]
And I have to say you are doing an amazing job with D3D11
