### ISSUE TITLE
Android switch back problem again since v1.3-631-ga99bad0

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#9358]
@hrydgard 
It crash when switch back.
Last work v1.3-615-ge110196
First not work  v1.3-631-ga99bad0
That mean  #9314

**Comment by hrydgard** [comment]
Thanks, I'll dig into this soon.

**Comment by Ar37** [comment]
maybe related with this issue #9331 i guess.

**Comment by sum2012** [comment]
Test v1.3-812-g9f17c7f fixed
Thanks @hrydgard
