### ISSUE TITLE
Sound Problem in NPlusPLus

### ISSUE THREAD

**Issue by cyb3rm4n** [hrydgard/ppsspp#9360]
When i start the game, the sound is stuttering and glitching for this game. Using latest buld.

**Comment by unknownbrackets** [comment]
Anything in the log?  Is the game showing that it's running at full speed?

-[Unknown]

**Comment by cyb3rm4n** [comment]
60 FPS ingame, no FPS drop. Soon i will make dumplog and post it here.

**Comment by unknownbrackets** [comment]
Does this still happen?  Got an updated log?

Did this used to work in older versions?

-[Unknown]

**Comment by hrydgard** [comment]
Didn't we have another issue about this game recently, where we found it was clipping due to some volume issue in Vaudio? Can't find it though, impossible to search for "N+"...

**Comment by LunaMoo** [comment]
This was mentioned in #9379 which has very similar problem. It sets volume to much higher value, where working max in ppsspp is 0x8000.
 Very easy to [hack around](https://github.com/hrydgard/ppsspp/issues/9379#issuecomment-307278409), I also made a cwcheat workarounds for both of those games.

**Comment by hrydgard** [comment]
Thanks LunaMoo. Closing this one as duplicate since we started investigating in #9379.
