### ISSUE TITLE
With the release of Android 7, will the Vulkan renderer be making a return on Android?

### ISSUE THREAD

**Issue by gannon345** [hrydgard/ppsspp#9363]
I remember there was an attempt a ways back to implement Vulkan on Android but it was removed. With Android 7's release and more devices supporting Vulkan, will it be implemented for mobile devices in the near future?

**Comment by gannon345** [comment]
I remember there was an attempt a ways back to implement Vulkan on Android but it was removed. With Android 7's release and more devices supporting Vulkan, will it be implemented for mobile devices in the near future?

**Comment by hrydgard** [comment]
That depends on what you mean with "near future" but yes it will happen eventually.
