### ISSUE TITLE
Scale window of PPSSPPSDL

### ISSUE THREAD

**Issue by multiSnow** [hrydgard/ppsspp#9367]
`ext/native/base/PCMain.cpp` shows that `--scale` and some others could do it, but `UI/NativeApp.cpp` also parse command line options by itself.
It causes that anything not starts with `-` will be treated as a file name to load at boot time:
```
 $>>  ./PPSSPPSDL --scale 2
1 = sscanf 2
OpenGL 2.0 or higher.
W: file_util.cpp:163: IsDirectory: stat failed on 2
File not found: 2
 $>>  ./PPSSPPSDL --xres 1920 --yres 1088
1 = scanf 1920
1 = scanf 1088
OpenGL 2.0 or higher.
W: file_util.cpp:163: IsDirectory: stat failed on 1920
File not found: 1920
 $>> 
```
Maybe we should bring the two command line parser together, or  add an option to scale the window ?

**Comment by hrydgard** [comment]
Yeah, agree that it's silly to have two parsers, getting rid of that would be quite a project though. I think this can be fixed separately though.
