### ISSUE TITLE
Support for vulkan + ES 3.2 in galaxy S6 nougat update

### ISSUE THREAD

**Issue by brujo5** [hrydgard/ppsspp#9368]
Hi is possible add Vulcan support for galaxy s6?

Just tested Vulcan in dolphin emulator and work great

**Comment by hrydgard** [comment]
Your screenshot doesn't load.

Is it confirmed the S6 Nougat update will have Vulkan? That's really good news if so, got a link?

**Comment by brujo5** [comment]
Yes, some dev in xda developer ported s7 nougat to s6/s6 edge using sources from g920a (att) nougat update. 

All work Vulkan and es 3.2 .
![screenshot_20170228-173729](https://cloud.githubusercontent.com/assets/4172898/23440996/df812548-fddc-11e6-808a-094df1d2477a.jpg)
![screenshot_20170228-015911](https://cloud.githubusercontent.com/assets/4172898/23441003/f55115cc-fddc-11e6-804c-d9b0e5e2849d.png)

**Comment by hrydgard** [comment]
Assuming the official update will get the same graphics drivers, that's great!

Like I said, I do plan to improve the Vulkan support. First by catching up to the other backends feature-wise, then I'll enable it on Android, and then later make use of Vulkan's unique abilities to get more speed on mobile GPUs. However both steps will be after the 1.4 release and the UWP release. Currently trying to find a second hand Windows 10 phone to test the latter :)

**Comment by hrydgard** [comment]
There's nothing really actionable right now in this issue so I'm closing.

**Comment by ddanjovi** [comment]
Thought I would share this. I managed to get the Unreal demo: sequencer running on android. Tested and running on the s6 edge. 
https://www.youtube.com/watch?v=dfzCHRy_rkc

**Comment by hrydgard** [comment]
Well, that's good I guess, wonder when my S6 will get Nougat..

**Comment by brujo5** [comment]
Nougat S6/edge  for F variant it's out since few weeks ago.
You can flash any custom rom based in nougat without upgrade to N bootloader. 
For example I have g920i (still not oficially release yet) but I have nougat running in my device.
