### ISSUE TITLE
ppsspp direct3d 11 

### ISSUE THREAD

**Issue by moura464** [hrydgard/ppsspp#9369]
![aaaaaaa](https://cloud.githubusercontent.com/assets/22099440/23482938/a267f442-feaf-11e6-85e7-46640565a85f.png)

**Comment by moura464** [comment]
Direct3d11 error  :/ ????

**Comment by hrydgard** [comment]
I don't see anything wrong in the screenshot?

**Comment by moura464** [comment]
![adasdadaeqeeee](https://cloud.githubusercontent.com/assets/22099440/23484469/dfe60f2e-feb5-11e6-9282-9317a1017aed.png)

**Comment by mrcmunir** [comment]
@moura464 What it's you gpu and with driver version?

**Comment by moura464** [comment]
@hrydgard http://www.rastertek.com/dx11s2tut03.html

**Comment by tywald** [comment]
@moura464 can you name your graphics card?(placa gráfica).

**Comment by hrydgard** [comment]
That might have gotten D3D11 working on some older GPUs.

**Comment by moura464** [comment]
Build working ![1f603](https://cloud.githubusercontent.com/assets/22099440/23588419/1d0739d0-019c-11e7-82c4-a694bd94fdcb.png)

**Comment by hrydgard** [comment]
great!

**Comment by moura464** [comment]
@hrydgard Build travis ci ?????
