### ISSUE TITLE
Texture scaling causes crash after thread-cleanup-2 merge

### ISSUE THREAD

**Issue by LunaMoo** [hrydgard/ppsspp#9372]
Any game I tried starting from v1.3-758-gfb0b82f
![texture scaling](https://cloud.githubusercontent.com/assets/5485237/23498904/183aea4c-ff2a-11e6-80d9-fb8a368ae6cd.png)

**Comment by hrydgard** [comment]
Alright, I'll fix it up.

In the long run I'd really like to kill off the CPU texture scaling and replace it with a GPU solution...

**Comment by hrydgard** [comment]
Urgh, our threadpool code really needs a rewrite anyway.

This is another case where the new mutexes are really helpful - when you run in debug mode they catch a lot of misuse.

**Comment by LunaMoo** [comment]
Thanks for fixing:).

 If we could process every texture via external shader, like post process effects now, it could be used for scaling and maybe also custom filtering to invent something which would avoid glitches caused by linear with increased rendering res in some games ~ but I guess implementing the system itself would not be easy.:c

**Comment by hrydgard** [comment]
Yeah, that's the idea. Though I wouldn't have too much hope for universally fixing those glitches. 

Anyway, for later, other priorieties now :)
