### ISSUE TITLE
WEIRD Stuttering when didnt touch screen on android

### ISSUE THREAD

**Issue by wisesnake** [hrydgard/ppsspp#9375]
when i play ppsspp android version, and didnt 

touch screen, the performance gonna low.

fps and speed rate dipped.

it could be interruption for gamepad users

**Comment by hrydgard** [comment]
Probably your phone boosting the CPU when you touch the screen to get smoother scrolling. Pretty common and very annoying. Android power management is hell...

**Comment by unknownbrackets** [comment]
Unfortunately, I don't think there's much we can do here.  We're always trying to improve performance, and the latest version should perform better - this may help on devices that throttle power when you're not touching the screen.

-[Unknown]
