### ISSUE TITLE
Ppsspp app stuck in black screen

### ISSUE THREAD

**Issue by brujo5** [hrydgard/ppsspp#9376]
Ppsspp app stuck in black screen

Last build working is ppsspp-v1.3-755-g54f862c

Tested in galaxy s6 android 7.0 

Here a video  http://es.tinypic.com/r/30wku1l/9

**Comment by tausifj15** [comment]
Yeah its stuck since build 758 and still present in 766😵😵

**Comment by hrydgard** [comment]
Should be fixed now.
