### ISSUE TITLE
Running game comes Mali GLES errorcode: 500

### ISSUE THREAD

**Issue by whitelok** [hrydgard/ppsspp#9377]
While I running game, it comes these error:

W/NativeApp: 34:03:706 user_main    W[G3D]: GLES/TextureCacheGLES.cpp:912 Got an error in texture upload: 00000500 (invalid_enum) (components=1908 components2=1908 dstFmt=1401 w=128 h=16 level=0)
W/MALI: _gles_set_error:82: [WARNING]Mali GLES errorcode: 500

**Comment by whitelok** [comment]
uploading the game image
[DigiviceVerPortableCHS.zip](https://github.com/hrydgard/ppsspp/files/815878/DigiviceVerPortableCHS.zip)

**Comment by hrydgard** [comment]
I believe this might be the same problem as https://github.com/hrydgard/ppsspp/issues/9331 , see that issue to follow the investigation.
