### ISSUE TITLE
Red Bull X-Fighters - NPEZ00100 music and save issue

### ISSUE THREAD

**Issue by benderscruffy** [hrydgard/ppsspp#9378]
v1.3-773-ga272a4e
music stops playing straight away and you cannot save your game
rename txt to zip
[ppsspplog.txt](https://github.com/hrydgard/ppsspp/files/818307/ppsspplog.txt)

**Comment by sum2012** [comment]
It seems that jpcsp fix this game
https://github.com/jpcsp/jpcsp/commit/6162ae3071fc1b72b42255c7739686e8d80bab86

**Comment by sum2012** [comment]
How to save ? I just play finish 1 stage

**Comment by benderscruffy** [comment]
it saves automatically 
just choose play game then basics and after you complete the first trick it will come up with the error

**Comment by sum2012** [comment]
I used USA version test
I do not get error
Do you have changed CPU clock or something ?

**Comment by benderscruffy** [comment]
must only happen on the Europe version

**Comment by benderscruffy** [comment]
v1.5.4-933-g386c9d4fc
still present

**Comment by benderscruffy** [comment]
v1.7.1-210-g9bda7cb64
still happens

**Comment by benderscruffy** [comment]
v1.7.5-566-gf316a6590
still the same problem
24:48:266 thread       E[SCEUTIL]: Dialog\PSPSaveDialog.cpp:68 A save request is already running, not starting a new one
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/2966115/ppsspplog.zip)

**Comment by benderscruffy** [comment]
fixed

**Comment by unknownbrackets** [comment]
Thanks for validating.  I wonder if this might've been the volatile locking or something related to secureVersion.

-[Unknown]
