### ISSUE TITLE
iOS arm 64 dev lastest totally not work now ,press the PPSSPP icon crash immediately .

### ISSUE THREAD

**Issue by ijoinit** [hrydgard/ppsspp#9381]
JBiOS10，in baidu post bar，some buddies have the same crash，just immediately crash and build a empty psp\system folder in documents

**Comment by hrydgard** [comment]
Open, close, open, close? Which is it?

**Comment by ijoinit** [comment]
It is true,the crash

**Comment by ijoinit** [comment]
But I backed up some earlier available  versions
