### ISSUE TITLE
Nozomi Kanaetamae - Daydream Reconstruct - NPJH00092

### ISSUE THREAD

**Issue by benderscruffy** [hrydgard/ppsspp#9382]
v1.3-773-ga272a4e
music cuts off during the intro and then the game freezes up 1-2 mins later
rename txt to zip
[ppsspplog.txt](https://github.com/hrydgard/ppsspp/files/818386/ppsspplog.txt)

**Comment by moura464** [comment]
v1.3-774-g8a2d80a3c

**Comment by moura464** [comment]
@benderscruffy v1.3-774-g8a2d80a3c

**Comment by unknownbrackets** [comment]
Possibly related to aac: UNIMPL sceAacInit(09fff158) #3870.

-[Unknown]

**Comment by benderscruffy** [comment]
closing in favour of #3870
