### ISSUE TITLE
Crash when taking screenshot with D3D11

### ISSUE THREAD

**Issue by tywald** [hrydgard/ppsspp#9389]
Tested on a fresh v1.3-790-ga04e24c

![gfhrtjrtjrj](https://cloud.githubusercontent.com/assets/10337060/23588524/feff2150-01be-11e7-956e-936ab309c90d.png)

![hfghgky](https://cloud.githubusercontent.com/assets/10337060/23588525/01899856-01bf-11e7-8af2-70647606b67c.png)

![gbfnjnk](https://cloud.githubusercontent.com/assets/10337060/23588526/0347b632-01bf-11e7-933a-ec2004a1fd08.png)

**Comment by moura464** [comment]
que ? working Build

**Comment by hrydgard** [comment]
For some reason when you press F12 in the debugger, you get the first stack trace there, doesn't occur outside. The other one was a real crash that I fixed in https://github.com/hrydgard/ppsspp/commit/042d09a049d0d6859fc1b22e97aa7cbcd0930111 , same as #9390.
