### ISSUE TITLE
Crash when taking screenshot in the PPSSPP menu with OpenGL & D3D9 when a game is not running.

### ISSUE THREAD

**Issue by tywald** [hrydgard/ppsspp#9390]
Tested on a fresh v1.3-790-ga04e24c

![thhfgb](https://cloud.githubusercontent.com/assets/10337060/23588152/72b68ba2-01b9-11e7-962d-32af624d534c.png)

![sdfgfgh](https://cloud.githubusercontent.com/assets/10337060/23588206/50bb4dca-01ba-11e7-8e5e-6df8bc19aa2d.png)

![gregh](https://cloud.githubusercontent.com/assets/10337060/23588166/bcb63b6c-01b9-11e7-8d75-7c9351f4e4bd.png)

Went back to check when it started to crash for me and it's since v1.3-515-g96c450e.
v1.3-508-gabf7a7a was the last build that worked.

**Comment by hrydgard** [comment]
Good catch, thanks! I'll get it fixed soon.
