### ISSUE TITLE
ODD CRASH IN LOCOROCO ON ANDROID

### ISSUE THREAD

**Issue by whoomay** [hrydgard/ppsspp#9391]
The crash occurs in ( seemingly ) all the " Mojas everywhere , run ! " stages ( the last staged in every world ) when I spend more than 20 seconds near the big Moja . I am able to pass the level if I just skip and run past the big Moja .

Sorry for the odd formating.

**Comment by hrydgard** [comment]
![uces00304_00000](https://cloud.githubusercontent.com/assets/130929/23590622/cd07d582-01e3-11e7-8f4f-dacad877ffe8.jpg)

You mean this guy? I just messed around near him for a couple of minutes without issues.

**Comment by whoomay** [comment]
@hrydgard Hmm... Then I dunno. Might this could be something to do with the ISO I am using or some setting?

**Comment by hrydgard** [comment]
Might be Android specific, I tested on PC. I guess I'll try that too later..

**Comment by xebra** [comment]
@whoomay Is enabling Hardware Tessellation?

**Comment by whoomay** [comment]
@xebra Nope, the option is actually grayed out for me.

**Comment by xebra** [comment]
Okay. 
Oh, I just remembered that I know the issue with software tessellation.
It cause crash when huge tessellation.
I don't know  this issue is related to tessellation or not, but I'll fix it later anyway.

**Comment by xebra** [comment]
I tested it and I have no problem to defeat the big moja on zenfone 5.

**Comment by unknownbrackets** [comment]
Does this still happen?

-[Unknown]
