### ISSUE TITLE
Resize problem when switching from window mode to fullscreen and vice versa in OpenGL

### ISSUE THREAD

**Issue by tywald** [hrydgard/ppsspp#9392]
Tested on v1.3-790-ga04e24c

![ulus10391_00003](https://cloud.githubusercontent.com/assets/10337060/23590548/4fd9b752-01e2-11e7-8a57-34d133d39f59.jpg)
![gerghhtrjrr](https://cloud.githubusercontent.com/assets/10337060/23590552/644b6a82-01e2-11e7-96e0-709e79c79a96.png)

Right now you have to pause then unpause(ESC -> Continue) to work around it.

Edit* it doesn't happen in Non-buffered mode.

**Comment by hrydgard** [comment]
Yup, reprod. Will fix.

**Comment by moura464** [comment]
![ulus10391_00001](https://cloud.githubusercontent.com/assets/22099440/23592182/d00b5720-01db-11e7-8243-49c45c464ec0.jpg)
![ulus10391_00002](https://cloud.githubusercontent.com/assets/22099440/23592183/d00c7182-01db-11e7-93a0-ae59aaf2ab70.jpg)

**Comment by hrydgard** [comment]
@moura464  yes the game works fine, the problem is only when switching between window and fullscreen.

**Comment by moura464** [comment]
ppsspp Game Jogos v1.3-790-ga04e24c ![1f44d_1f3fb](https://cloud.githubusercontent.com/assets/22099440/23592284/39c78caa-01dd-11e7-9f88-0d230145abb2.png)![1f601](https://cloud.githubusercontent.com/assets/22099440/23592285/39c9ece8-01dd-11e7-8c09-33c7c9f17f8e.png)
