### ISSUE TITLE
Cannot Set controls with a teensy(adruino) 3.2 based joypad.

### ISSUE THREAD

**Issue by AnnCoulter** [hrydgard/ppsspp#9394]
I cannot set up control with my portable rpi3 system. Uses a teensy 3.2 to interance the 2 joystick and 16 buttons, but ppsspp does not recognize my controls when i try to set it up in the menu. Is the a config file or shell script around somewhere i can manually add my controls?

**Comment by hrydgard** [comment]
Does the joystick work with other SDL applications?

**Comment by LunaMoo** [comment]
Maybe it just need an entry in [gamecontrollerdb.txt](https://github.com/hrydgard/ppsspp/blob/master/assets/gamecontrollerdb.txt). There should be some SDL2 gamepad tools to add new gamepads to this.

 If I understand it - I think if the gamepad isn't in the database, it currently just gives up(?) ~ [here](https://github.com/hrydgard/ppsspp/blob/5ce074ddacf94601f4f59f1e8e18eff98be12fb3/SDL/SDLJoystick.cpp#L74).

**Comment by AnnCoulter** [comment]
Thanks for the tip! I added 

03000000c01600008704000011010000,Serial/Keyboard/Mouse/Joystick,platform:Linux,a:b12,b:b10,x:b13,y:b11,back:b4,start:b5,leftstick:b14,rightstick:b15,leftshoulder:b9,rightshoulder:b8,dpup:b0,dpdown:b2,dpleft:b3,dpright:b1,leftx:a1,lefty:a0,rightx:a2,righty:a3,lefttrigger:b6,righttrigger:b7,

to the gamecontroller.txt file and now it works just fine. Maybe you can include this in the file now? I use case is a bit specific though.

also btw, it was a pain in the ass to find the SDL2 GUID for the teensy 3.2, especially since i had to do it via ssh into a raspberry pi lol.

**Comment by hrydgard** [comment]
Adding it!
