### ISSUE TITLE
The later versions of ppsspp on iOS just crash immediately when we click on ppsspp icon 

### ISSUE THREAD

**Issue by iOS4all** [hrydgard/ppsspp#9397]
As I mentioned in the title all later versions of ppsspp are crashed when we select it from homescreen.
This crash including the latest one which is (v1.3-797).

**Comment by hrydgard** [comment]
Already reported in #9381. Will fix soon.

**Comment by ijoinit** [comment]
i opened the same issue at #9381,totally not work ,I also tried it on iOS 6,still not work ,just keep black screen

**Comment by iOS4all** [comment]
I didn't know it's already talked about this issue.
It's ok waiting for the fix
Thanks.

**Comment by hrydgard** [comment]
Fix for the insta-crash problem committed.
