### ISSUE TITLE
PPSSPP BUILD NEW  LAG

### ISSUE THREAD

**Issue by Endarko** [hrydgard/ppsspp#9399]
ppsspp latest build highly lag for pes 2014. frameskip 1

**Comment by Endarko** [comment]
on android 5.1.1 quadcore. gpu adreno

**Comment by tausifj15** [comment]
Bro new build lags in all games

**Comment by hrydgard** [comment]
Please try some older builds from here: http://buildbot.orphis.net/ppsspp/

And figure out which one is the oldest one that "lags". That way we can easily find and fix the cause.

**Comment by ijoinit** [comment]
iOS lag too,i have some iOS information，1.3-718 was ok,but I missed 724 to 748,then I have 749,maybe not lag,I forget,but I found UI missing in Project Diva 2andex,NPJH50465 and ULJM05681,then 754 when choose a game will crash，and then 758 touch icon crash, and 812 fixed crash but I  missed,now is 819 lag and UI missing:the UI words turn to black blankets ,miku chan's lyric black too

**Comment by hrydgard** [comment]
OK, that's weird. I'll look into it soon.

**Comment by tausifj15** [comment]
Sir 831 fixed the lag but why u remove alternative speed to 1000 from 600

**Comment by ijoinit** [comment]
But I found 823 already fixed,and no black blanket,yesterday it's 819 in  repo ,weird and funny,

**Comment by hrydgard** [comment]
I haven't changed alternative speed, it's still 1000. You must be running the wrong builds, or our build server is doing something very wrong. Check the version number at the top right in the PPSSPP window.

**Comment by tausifj15** [comment]
Its 823 sir

**Comment by tausifj15** [comment]
sorry 831

**Comment by tausifj15** [comment]
Sorry sir it was the stable version 831 also lags but less then other
builds pls fix it iknow u can 😊
