### ISSUE TITLE
Cydia Repo Is Down

### ISSUE THREAD

**Issue by Yato64** [hrydgard/ppsspp#9403]
Idk why but it is. Can't even download new builds from the downloads section of ppsspp.org

**Comment by hrydgard** [comment]
Site was broken before today due to disk full, it's been fixed. Please reopen if there are still issues.

**Comment by hrydgard** [comment]
Never mind, not fixed at all. Got some kind of db corruption, trying to sort it out..

**Comment by hrydgard** [comment]
The forum tables are all fine. A couple of the ppsspp_report tables are broken though.. darn :/

**Comment by Yato64** [comment]
Just so you know this site is still throwing me the same error. Going to try the repo next

**Comment by ijoinit** [comment]
PPSSPP repo will be empty after refreshed many times

**Comment by Yato64** [comment]
Can't add it now. Assuming it's still down? By the way I have a working IPA if you want to post it on your site. Pretty easy to side load. Kinda wondered why you didn't use ipa's to start with

**Comment by hrydgard** [comment]
Mostly because I have no idea what an IPA really is or how to make one. I haven't done much iOS stuff really, Android has been a much bigger focus since it isn't actively hostile (JIT is allowed, Play Store is allowed etc).

**Comment by hrydgard** [comment]
Need to sleep now, will try to finish the database restoration tomorrow, it's being a pain.

**Comment by ijoinit** [comment]
i just use 7zip,unzip deb file and rezip Payload\ppsspp.app and rename .zip to .ipa,ipa file is  installed in var,save some root path space

**Comment by iOS4all** [comment]
@hrydgard yeah you have to take some rest.
 by the way the repo is back and the crash is fixed as well.
Thanks.

**Comment by hrydgard** [comment]
Database restore completed (except the reports system). Forums are up and running.
