### ISSUE TITLE
Where we can find latest version of ppsspp for non-jailbroken devices?

### ISSUE THREAD

**Issue by iOS4all** [hrydgard/ppsspp#9404]
@hrydgard hi there as I mentioned above on the title.
Thanks.

**Comment by ijoinit** [comment]
You can make it yourself,unzip the deb file and zip to ipa,cydia impacter can install ipa file on unjailbreak devices ,it can't be the AppStore .by the way the latest PPSSPP builds seems too much lag and slow than earlier versions on jailbroken iOS

**Comment by iOS4all** [comment]
@ijoinit thanks for sharing this information. I already did all that but unfortunately when I select any game the ppsspp crashes immediately. Any idea?

**Comment by ijoinit** [comment]
if you use a unjailbreak device？ have to change Jit to Ir interpreter，jit not work on unjailbreak

**Comment by hrydgard** [comment]
Jit does work on "unjailbreak" if you run directly from the XCode debugger. Probably not really an everyday solution though.

**Comment by iOS4all** [comment]
Unfortunately neither JIT nor interpreter work with me on non-jailbroken device

**Comment by hrydgard** [comment]
Could be that the "vertex jit" is still activated. If you can find and modify PPSSPP.ini, change VertexDecJit to false. 

Should probably automatically turn that off when JIT is turned off...

**Comment by iOS4all** [comment]
I remember while ago I was able to play ppsspp on non-jailbroken devices with JIT enable. Because of your new way to implement JIT. Please can u help with this?

**Comment by ijoinit** [comment]
I know a "chat app ",but if type in the "code "get from their website,it become a R18 hentai manga reader,maybe PPSSPP can go to AppStore by this way too ?fake to a office app,we type in some code

**Comment by kenthinson** [comment]
The best way to get the newest version on non jailbroken iOS is to build it yourself. Using xcode / terminal. The wiki has easy to follow instructions. It's free. Also the certificate wont be revoked by Apple as it's one given just to you.

**Comment by cutecycle** [comment]
Wasn't sure if I wanted to start a new thread for this -- but I'm currently building/provisioning PPSSPP and JIT is throwing EXC_BAD_ACCESS when starting any game [iPhone 6 Plus 16GB, iOS 10.3.1, non-jailbroken]. IR and Interpreter are functioning. Does JIT work on non jailbroken devices when building it yourself?
![screen shot 2017-04-18 at 3 21 00 am](https://cloud.githubusercontent.com/assets/12169942/25118954/49b11642-23e6-11e7-9c60-7481dc139880.png)
![screen shot 2017-04-18 at 3 20 53 am](https://cloud.githubusercontent.com/assets/12169942/25118955/49bdcb76-23e6-11e7-9354-d38cba1e867c.png)
![screen shot 2017-04-18 at 3 20 50 am](https://cloud.githubusercontent.com/assets/12169942/25118956/49be2404-23e6-11e7-841c-5514faf3fe09.png)

**Comment by hrydgard** [comment]
I've been able to run it from the debugger like that, fairly recently, non non-jail-broken devices. Though only on 32-bit. Still not sure why it won't work with 64-bit.

**Comment by atsumori666** [comment]
Sorry, I haven't been following ios development the last several months.  Was the new JIT that worked on non-jailbroken devices removed in the newest builds?  I've had 1.3 working flawlessly on my non-JB 6s for a year or so now but now that I've tried updating to 1.4.2 I can't get JIT to work anymore.

Am I just missing a build setting?  Or is it an issue with the dynarec on 64bit?  Something else?

**Comment by hrydgard** [comment]
The dynarec will currently crash in 64-bit builds. I know the cause and plan to fix it eventually, though it is a bit tricky.

**Comment by atsumori666** [comment]
Thank you for the response.  I'll look forward to a fix in the future then!

**Comment by unknownbrackets** [comment]
It seems like the issues here are fixed.  It runs on iOS 10 now.  Please comment if you have further issues.

-[Unknown]
