### ISSUE TITLE
Dissidia 012 Gilgamesh problems (Missing certain weapons)

### ISSUE THREAD

**Issue by leo412** [hrydgard/ppsspp#9411]
When playing as Gilgamesh, the Genji Sword will never appear, he will be literally holding nothing when attacking, does anyone has this problem?

Before the newer version of PPSSPP, everytime Gilgamesh tried to use Genji Sword, it will just crash, however in 1.3 the weapon merely do not show up and not causing crashing. (there will be no hit box, no damage and no effect upon anything)

Only Genji Sword has this problems, it can even happen in ex mode where it will cause Gilgamesh to wield nothing at all.

**Comment by unknownbrackets** [comment]
Can you upload a save state nearby?  Ideally, before the sword is missing but where it will soon be visibly missing (in case the game loads the texture before the fight or etc.)

-[Unknown]

**Comment by SamueldeSena** [comment]
this problem has already been corrected as you can see in the photos below in the new version of ppsspp v1.5.4 this topic can already be closed
![screenshot_20171206-143137](https://user-images.githubusercontent.com/34135636/33672919-38e2993e-da8a-11e7-99c6-c3552bc29c57.png)

![screenshot_20171206-143141](https://user-images.githubusercontent.com/34135636/33672884-226d22d2-da8a-11e7-87fa-86adbde92d19.png)

**Comment by hrydgard** [comment]
@leo412 please verify that it's been corrected in the latest, re-open if not.
