### ISSUE TITLE
ps vita

### ISSUE THREAD

**Issue by moura464** [hrydgard/ppsspp#9412]
ps vita emulator @hrydgard  ??? Jogos  what? No

**Comment by unknownbrackets** [comment]
Unrelated to PPSSPP.  The PSP is a MIPS device using a fixed-function GPU and disc drive.  The Vita is an ARM device using a PowerVR GPU with cards.  The Vita is as different from the PSP as from the Wii, for the most part.

That means that PPSSPP's GPU backends, HLE code, jit, etc. are basically of no use to a Vita emulator.  Sounds like a new project, but not an issue in PPSSPP.

-[Unknown]

**Comment by moura464** [comment]
unknownbrackets Fuck  .l. :/ c suck

**Comment by MarcoEstevez** [comment]
What? O_o, moura464, you might need some professional help, seriously.

**Comment by moura464** [comment]
@MarcoEstevez  hahahha  :v:  :V

**Comment by hrydgard** [comment]
@moura464  That's not a way to behave here. Unknown is perfectly correct.

In fact, there's a project to implement Vita support in RPCS3 - the Vita is closer to the PS3 than the Vita. 

But you are now banned.

**Comment by Orphis** [comment]
Oh finally.

**Comment by iOS4all** [comment]
@hrydgard can be ppsspp port to vita? If yes it would be amazing.
The most important thing from this port is to could play psp in high resolution. Because psp on vita is so pixelated.

**Comment by Orphis** [comment]
Possible? Probably.
Worth it? Hell no.

You have a device more powerful in your pocket already, stop trying to get every device in the world run everything, it's just a waste of time.

**Comment by unknownbrackets** [comment]
The problem is the Vita is actually not very powerful (remember that it was released in 2011.)  It's definitely stronger than the PSP, but the Vita just doesn't have the Mhz or the GPU power to emulate PSP games at higher resolutions than the native Vita PSP emulator does (1x.)

-[Unknown]

**Comment by iOS4all** [comment]
Other question: can other filters like xbrz port to adrenaline/TN-V if we could it would be very nice and play psp in hd without bringing ppsspp to vita.
