### ISSUE TITLE
 Software rendering broken since #9329

### ISSUE THREAD

**Issue by LunaMoo** [hrydgard/ppsspp#9422]
Might not be affecting all games, but causes black screen in quite a lot of games, easy to reproduce in some homebrew like "Yellow Rose of Texas" or "Planet Hively".
 Problem starts from https://github.com/hrydgard/ppsspp/pull/9329/commits/eabcb22623494b35745c4f8f3c0255fc8c59c69b

**Comment by hrydgard** [comment]
Just a silly oversight, thanks.
