### ISSUE TITLE
pls improve multiplayer option

### ISSUE THREAD

**Issue by tausifj15** [hrydgard/ppsspp#9432]
Sir henrik is there anyway to play multiplayer in ppsspp games like wwe 2011 tekken 6,5 ?

**Comment by hrydgard** [comment]
Yes through networking, though it's pretty tricky to set up.

You'll never be able to play 2-player like on the PS2 with two controllers in the same instance of PPSSPP, because the PSP of course only has a single screen and a single set of controls.

**Comment by tausifj15** [comment]
im talking about two devices?
