### ISSUE TITLE
If PPSSPP starts in "small mode", fonts stay small even if you resize the window

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#9437]
The fonts should enlarge once the window is big enough.

Also, the default size on Windows should be DPI aware - it should start in 4x by default instead of 2x if the DPI is 2x, for example. Maybe we should even call that 2x... not sure.

**Comment by Hydroque** [comment]
Would it be faster to stretch and draw frames or render the game stretched?

Testing on my old PC there is a huge performance hit when the window is 2x, but the render size is 1x.

**Comment by hrydgard** [comment]
That's weird, even on an old PC that should be fast.

**Comment by Hydroque** [comment]
1.8 dual core amd64 using 64 bit version GeForce 7000M gfx (1919mb available ram, 0 shared system vdieo, 1663 shared system, that leaves 256mb dedicated?) with settings floored (especially in ppsspp) with 4gb ddr2 ram. I don't think memory is an issue whatsoever. I even cache the entire rom in memory as per the setting. Enabling the dual core tests didn't give noticable results. I get audio cracking too X_X. Screen refresh rate is 60 and vsync is off. Turning it on doesn't have any performance effect.

**Comment by Hydroque** [comment]
Is there any option where I can stretch the 1x rendered image without anything special added? The bigger I make the window, the more lag I get. I don't notice any change outside a 3% difference when it was already lagging for screen resolution.

**Comment by hrydgard** [comment]
Well, just set Rendering Resolution to 1x and turn off any postprocessing.

**Comment by Hydroque** [comment]
Post processing is off and rendering solution was 1x and window size was 1x. It was because I had 'skip buffered rendering' off. I switched to buffered and all was well.

**Comment by unknownbrackets** [comment]
When I start at 1x, and then change to 2x, fonts do get larger.  I'm not on 4K, just using standard DPI, though.

First frame is start @ 1x, resize to 2x, second frame is start @ 2x, below.  Fonts are the same size.
![small-window-2x](https://cloud.githubusercontent.com/assets/191233/24027156/b60dcab0-0a82-11e7-8ad3-d41c3df2a739.gif)

Is `g_dpi_scale` changing to a value less than `1.0f` and also less than the previous value?

To confirm, if it starts at 2x or some other non-smallWindow size, the behavior works as expected?  Are you resizing some other way than dragging the window size or selecting 1x/2x/etc.?

-[Unknown]

**Comment by hrydgard** [comment]
This is on high-DPI yes.

Yeah, works as expected if starting at 2x (well, 4x...). Just dragging.

I'm going to investigate more later.

**Comment by hrydgard** [comment]
That takes care of it. But how could it have worked before?

**Comment by unknownbrackets** [comment]
Oh, I guess it was just because it was always drawing at 1.0f scale there on non-high DPI now that I didn't see it, oops.

-[Unknown]
