### ISSUE TITLE
Convert JIT to not JIT

### ISSUE THREAD

**Issue by Hydroque** [hrydgard/ppsspp#9439]
Is it possible to stop doing JIT and create files that are already compiled and start using them with PPSSPP. Maybe I misunderstand something or don't comprehend the reason for JIT, but that would be a neat feature that I assume would resolve iOS problems with JIT?

**Comment by Orphis** [comment]
It's not easy, the PSP allows self modifiable code.
Then, you would need to install a new emulator package for every game separately, since otherwise, it is still about generating code and executing it.

All of that is quite hard and probably not worth it.

**Comment by Hydroque** [comment]
Ahh alright.
