### ISSUE TITLE
Emergency Stop on Linux 4.4.52 when open most games.(Manjaro)

### ISSUE THREAD

**Issue by YuSuu** [hrydgard/ppsspp#9440]
# basic information
my system basic information is 
**Linux ted-E3 4.4.52-1-MANJARO #1 SMP PREEMPT Sun Feb 26 12:00:44 UTC 2017 x86_64 
GNU/Linux**
my cpu is **E3 1230V2,** my gpu is **AMD HD7850.**
and in the screenfetch my system identify my gpu like this
**GPU: Gallium 0.4 on AMD CAPE VERDE (DRM 2.43.0 / 4.4.52-1-MANJARO, LLVM 3.9.1)**
# Crash on 《MHP3》
The error below occurs when i open  MonsterHunterPortable3 ,after I created the role and cant go on.. and 
```
18:06:702 user_main    I[ME]: HLE/sceMpeg.cpp:353 First timestamp: 90000, Last timestamp: 10978878
18:06:769 readThread   I[ME]: HLE/sceMpeg.cpp:352 Stream offset: 2048, Stream size: 0x1ED1000
18:06:769 readThread   I[ME]: HLE/sceMpeg.cpp:353 First timestamp: 90000, Last timestamp: 10978878
**18:07:308 videoThread  E[ME]: HW/MediaEngine.cpp:82 FF: Assertion 0 failed at libavcodec/utils.c:601**
fish: 'ppsspp' terminated by signal SIGABRT (Abort)
⋊> ~         
```            

# Another crash on 《Final Fantasy Type0》
The error is this..
```
19:52:704 SQEXTEC Movi I[ME]: HLE/sceMpeg.cpp:352 Stream offset: 2048, Stream size: 0x1031000
19:52:704 SQEXTEC Movi I[ME]: HLE/sceMpeg.cpp:353 First timestamp: 90000, Last timestamp: 10035936
**19:52:714 SQEXTEC Movi E[ME]: HW/MediaEngine.cpp:82 FF: Assertion 0 failed at libavcodec/utils.c:601**
fish: 'ppsspp' terminated by signal SIGABRT (Abort)
⋊> ~   
```
# The same crash on《Venus & Braves:The Witch and the Goddess and the Prophecy of Destruction》
```
32:54:323 FSReadThread I[ME]: HLE/sceMpeg.cpp:353 First timestamp: 90000, Last timestamp: 12321219
32:54:364 FSReadThread I[SCEGE]: GLES/Framebuffer.cpp:1900 Decimating FBO for 00044000 (480 x 272 x 1), age 6
32:54:367 user_main    E[ME]: HW/MediaEngine.cpp:82 FF: Assertion 0 failed at libavcodec/utils.c:601
fish: 'ppsspp' terminated by signal SIGABRT (Abort)
⋊> ~        
```
# At last
some game can run smoothly ,
But how can i solve the errors above?
Hope ppsspp can be better and better XD
thanks in advance!

**Comment by YuSuu** [comment]
sorry for bothering!
i download from the official website, 
the error above doesnt show.
I installed from the AUR previously!

**Comment by unknownbrackets** [comment]
This seems likely to be #9026.

-[Unknown]

**Comment by YuSuu** [comment]
yeah~i read that post before, 
then i tried to install from other sources instead of AUR.
finally it works. XD
 @unknownbrackets
