### ISSUE TITLE
MotorStorm - Arctic Edge (USA) Bugs

### ISSUE THREAD

**Issue by Cibomatto2002** [hrydgard/ppsspp#9441]
When playing the game the music is not there also the grafx is messed up. Here is a video of the bugs.

https://www.youtube.com/watch?v=jsLo5Q5MnMA

I'm on Windows 10 also all the Backend do it.

**Comment by Cibomatto2002** [comment]
I just looked this game up I see it has been turned in before sorry.

**Comment by hrydgard** [comment]
Yup, known issues :/
