### ISSUE TITLE
Linux build broken (can not link snappy)

### ISSUE THREAD

**Issue by thesourcehim** [hrydgard/ppsspp#9443]
With latest git version I get the following error when trying to build with b.sh:

-- Found Snappy: /lib64/libsnappy.so  
CMake Error at CMakeLists.txt:389 (target_link_libraries):
  Target "Snappy::Snappy" of type UNKNOWN_LIBRARY may not be linked into
  another target.  One may link only to STATIC or SHARED libraries, or to
  executables with the ENABLE_EXPORTS property set.

**Comment by Orphis** [comment]
I'll have a look!

**Comment by mrcmunir** [comment]
I can confirm this with can't target link some libraries i.e libsnappy armips now

**Comment by hrydgard** [comment]
Yup, if libsnappy-dev is installed (say, through apt-get) then it won't work. @Orphis , some Cmake magic? :) 

I'd say we just stop trying to use the system snappy and use the bundled one instead..
