### ISSUE TITLE
To aru majutsu no index no longer works

### ISSUE THREAD

**Issue by SearchingForName** [hrydgard/ppsspp#9452]
The game was playable in the stable version 1.3 but occasionally it won't show the main menu (the one which has the press the start button) and the only fix i found for it was to reinstall the emulator so i decided to try the version "v1.3-978-gde72005"
the emulator crashed just right after selecting the iso
i also tried using version "v1.3-747-gd84f579" it also crashed

crash log:
[ppsspplog13_gde72005.docx](https://github.com/hrydgard/ppsspp/files/852778/ppsspplog13_gde72005.docx)
(change . docx to .zip)

the game log when it works and when it show a black screen
[ppsspplog13stable_info_gamedoesntwork.txt](https://github.com/hrydgard/ppsspp/files/852760/ppsspplog13stable_info_gamedoesntwork.txt)
[ppsspplog13stable_info_gameworks.txt](https://github.com/hrydgard/ppsspp/files/852761/ppsspplog13stable_info_gameworks.txt)

**Comment by unknownbrackets** [comment]
Try turning off networking.

-[Unknown]

**Comment by SearchingForName** [comment]
checked the settings .. it is already turned off

**Comment by SearchingForName** [comment]
version "v1.3-215-ge9bea75" the game works

**Comment by unknownbrackets** [comment]
That's helpful - if you go by halves, it'll go quicker.  So between 350 and 718, does ~530 or so work?

-[Unknown]

**Comment by SearchingForName** [comment]
"v1.3-464-gdc19e11" also works

**Comment by SearchingForName** [comment]
"v1.3-615-ge110196" works

the bug is somewhere between 615 and 631

all commits between 615 and 631 have no build

**Comment by unknownbrackets** [comment]
Thanks, that's very helpful - that points to #9314 being the problem.

 * Are you using any post-processing shaders (I suppose the answer is no)?
 * Can you try using a different graphics backend, like Direct3D 9 or Direct3D 11?

-[Unknown]

**Comment by SearchingForName** [comment]
postprocessing shader is set to off

backend:
openGl -- crash
Direct 3d 9 -- works
Direct 3d 11 -- works

--- also something i forgot to mention
i notice a huge performance drop when i switch the game to full screen ( or try to increse the window size)
something like when you switch video speed from 1 to 0.25
it can be noticed just being at the main screen (press any key to start) and try to resize the window

**Comment by SearchingForName** [comment]
about the performance drop it got fixed by setting the "frameskipping" to anything except '0' or 'off'

**Comment by benderscruffy** [comment]
PPSSPP v1.5.4-997-g3472d62ff Windows 64 bit
this can be closed now as it goes ingame with opengl
