### ISSUE TITLE
Qt builds do not recognize /usr/share/ppsspp/assets

### ISSUE THREAD

**Issue by duganchen** [hrydgard/ppsspp#9453]
I've noticed that if you do both an SDL and a Qt build, the SDL build will recognize /usr/share/ppsspp/assets, but the Qt build will not.

This behavior seems to be set here:

https://github.com/hrydgard/ppsspp/blob/fc648f5f32ae77f67acbf77c361527f1c720a0e9/UI/NativeApp.cpp#L317

I'd submit a pull request, but I'm not sure if this is intentional.

I'm referring to Linux builds, btw.

**Comment by hrydgard** [comment]
Got to be an oversight - pull requests accepted.
