### ISSUE TITLE
gamecontrollerdb.txt only recognized if located relative to EXE

### ISSUE THREAD

**Issue by duganchen** [hrydgard/ppsspp#9460]
The code that loads gamecontrollerdb.txt can only find it if it's in an "assets" subdirectory in the same directory as the .exe.

It looks to me like this is set here:

https://github.com/hrydgard/ppsspp/blob/5ce074ddacf94601f4f59f1e8e18eff98be12fb3/SDL/SDLJoystick.cpp#L38

This is incorrect for (almost?) every platform PPSSPP supports, as the location of the assets directory can have other valid values. The valid values are set here:

https://github.com/hrydgard/ppsspp/blob/master/UI/NativeApp.cpp#L318

**Comment by hrydgard** [comment]
Yup, that's a mistake. The problem is that SDL_GameControllerAddMappingsFromFile requires a filename and doesn't go through our "VFS" virtual file system, though it can be worked around several ways.

**Comment by hrydgard** [comment]
OK @duganchen , here's an exercise for you!

Use VFSReadFile to read the data, then use SDL_RWFromConstMem (http://www.jose.it-berater.org/sdl/core/sdl_rwfromconstmem.htm) to put it in an SDL_RW, then use SDL_GameControllerAddMappingsFromRW to load it instead. Then send a pull request :)

**Comment by duganchen** [comment]
Do you intend to keep supporting the $PPSSPP_GAME_CONTROLLER_DB_PATH environment variable after this is done?

**Comment by hrydgard** [comment]
I'm not really sure how useful it is if asset loading works correctly. What do you think?

**Comment by Hydroque** [comment]
Some people require an infinite amount of customization.
