### ISSUE TITLE
Give PPSSPP a cool window skin

### ISSUE THREAD

**Issue by Hydroque** [hrydgard/ppsspp#9462]
Along with updates to the UI in the future that was briefly discussed in past issues, there should be a cool window update too. Merging the menu bar with the title bar would be cool. Something that really catches the ppsspp-esque.

**Comment by hrydgard** [comment]
Too much effort for little benefit, not gonna happen. Believe me, that stuff is actually quite difficult, I don't dare to think about how much effort the Chrome developers have spent on making their tab/title bar look good _on all versions of Windows_, matching all the themes.
