### ISSUE TITLE
Move flash0 into assets?

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#9468]
flash0 contains the font files, and they're mostly static (unless you manually replace fonts) so would seem to belong there, it would just be a little neater to only have one folder by default, and simplify a few of the build scripts a tiny bit.

Any reason not to? Otherwise I'll do this soon.

**Comment by unknownbrackets** [comment]
I don't think there's a reason not to, as long as the user override locations still work.

-[Unknown]

**Comment by InusualZ** [comment]
Yeah, "backward compatibility" need to be a thing
