### ISSUE TITLE
Sony Android TV remote can't be used to navigate the menus properly

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#9471]
http://forums.ppsspp.org/showthread.php?tid=22740

Not sure it's worth fixing though, depends on if the remote has enough buttons to play ... But still would be good to figure out what the problem is, what Android key that the Enter button on the remote sends.

**Comment by hrydgard** [comment]
Turns out it's NKCODE_DPAD_CENTER , which seems like something we should support as an enter press.

**Comment by arshamatonyan** [comment]
Separate ui controls mapping from in game mapping. Then for different input devices crate different profile. 
I think that will be right way to do.
Thanks.
