### ISSUE TITLE
Support the new audio API in Android "O"

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#9475]
Android "O" adds a new very simple audio API, promising lower latency than ever. I guess they finally gave up on making OpenSL fast... 

We'll obviously add support. Here's the only code sample I could find so far: 

https://github.com/googlesamples/android-audio-high-performance

Android O won't be in production devices for quite a while though so setting this to milestone "Future".

**Comment by ijoinit** [comment]
I found something here https://en.m.wikipedia.org/wiki/OpenSL_ES

**Comment by iOS4all** [comment]
Can you port this feature to iOS as well?

**Comment by Orphis** [comment]
Please, this is an Android API, not iOS.

**Comment by zminhquanz** [comment]
Android 5.0 (API level 21) and above support this, i read this document
https://developer.android.com/ndk/guides/audio/opensl-for-android.html

**Comment by unknownbrackets** [comment]
This issue isn't about OpenSL (which we already use), but about AAudio:
https://developer.android.com/ndk/guides/audio/aaudio/aaudio.html

-[Unknown]

**Comment by hrydgard** [comment]
Yep. I now have a device that runs the O beta but will hold off on this until the NDK r15 with headers for the new API is available.

**Comment by hrydgard** [comment]
Not sure whether to bother with this, the AAudio API had a very rough start with major bugs shipping in devices (when will Google ever put some real resources into audio??). closing for now.

**Comment by RaceDriverMIKU** [comment]
It is closed, but I hope to see the new AAudio API is coming to PPSSPP.
I play Project DIVA, and DJMAX often. and I assume AAudio API gonna helps the game experience a lot because of very low latency.

**Comment by EternalsDarkhole** [comment]
Oboe audio is better than AAudio hope ppsspp can have this.
https://github.com/google/oboe

**Comment by Gamemulatorer** [comment]
> Oboe audio is better than AAudio hope ppsspp can have this. https://github.com/google/oboe

Ain't no plan of implementing Oboe?
Flycast emulator already have this.
![Screenshot_20230314_073252](https://user-images.githubusercontent.com/37603562/224855063-70de11ac-bed5-452e-bb12-ab3bcca024b7.jpg)

**Comment by hrydgard** [comment]
oboe is just a wrapper around AAudio and OpenSL that works around a few platform bugs. Which is good, but Oboe also has this limitation:

> Note: To use Oboe, you must specify a minimum API level of 16 and NDK release of 18 for the Android Game SDK libraries. If you don't, Oboe can't be found at build time.

We specify a minimum API level of 9, and it's kind of a point of pride to still support extremely old Android devices. I'm sure that can be hacked around somehow, but it's not convenient for us.

I might instead add an AAudio backend that we can switch to on newer devices, and look at Oboe for ways to avoid the platform bugs.

**Comment by Gamemulatorer** [comment]
> We specify a minimum API level of 9, and it's kind of a point of pride to still support extremely old Android devices.

Does someone still using android gingerbread? 😅

> I might instead add an AAudio backend that we can switch to on newer devices, and look at Oboe for ways to avoid the platform bugs.

I'm waiting for that because the crackling audio in ppsspp is very annoying :/

**Comment by Fatcat2024-cpu** [comment]
> oboe is just a wrapper around AAudio and OpenSL that works around a few platform bugs. Which is good, but Oboe also has this limitation:
> 
> > Note: To use Oboe, you must specify a minimum API level of 16 and NDK release of 18 for the Android Game SDK libraries. If you don't, Oboe can't be found at build time.
> 
> We specify a minimum API level of 9, and it's kind of a point of pride to still support extremely old Android devices. I'm sure that can be hacked around somehow, but it's not convenient for us.
> 
> I might instead add an AAudio backend that we can switch to on newer devices, and look at Oboe for ways to avoid the platform bugs.

After you implented the 16kb page size https://github.com/hrydgard/ppsspp/pull/19658
you will drop support for api level 9 extremely old android phone? Then you can add a new AAudio backend using oboe?
