### ISSUE TITLE
DJ Max Portable 3 crashes/black screen when launched from memstick.

### ISSUE THREAD

**Issue by yyuukbdu** [hrydgard/ppsspp#9477]
My phone is XiaoMi Mi Max and I've been trying to get DJ Max to work. I've downloaded the cube test program to check if  the emu is working on my device and i got the test cube program to run ONLY when fastmem is on.

When fastmem is enabled on the emu, launching dj max will crash my device. I've googled and some users said that turning off fastmem might get it to work. But when fastmem is disabled, the test cube program is not working along with dj max. Both shows a black screen

**Comment by mrcorra** [comment]
I'm having a very similar problem.

**Comment by hrydgard** [comment]
Sounds like some ARM64 JIT bug. I'll see if I can reproduce cube-without-fastmem black screen...

**Comment by hrydgard** [comment]
Likely related to #9488?

**Comment by hrydgard** [comment]
I can reproduce cube.elf broken with slow memory on ARM64 devices. Not good...

**Comment by hrydgard** [comment]
Bug appears to be in SetScratch1ForSafeAddress, but the code seems right...

**Comment by hrydgard** [comment]
With that, you should be able to test without fast memory.

Though if it crashes with fast mem, there's still a bug somewhere..

**Comment by yyuukbdu** [comment]
Tested with the latest build. I am still faced with black screen but there are some changes. After letting it run for about 15 seconds, there would be a notification saying "Running slow. Try frameskip, sound is choppy when slow" before crashing.

**Comment by mrcorra** [comment]
Same here. Only I can't change the choppy sound. As a matter of fact, I think it got worse. Actually, I'll explain it in another post.

**Comment by unknownbrackets** [comment]
Just to make sure, this crash still happens with fast memory on, and doesn't happen with it off, right?

Does anyone know if older 32-bit phones (not arm64, but arm32) crash?  Or if it crashes on desktops (something with an Intel chip)?

-[Unknown]

**Comment by hrydgard** [comment]
If I remember correctly from some previous discussion, and am not confusing it with something else, it works fine on ARM32 so likely to be an ARM64 jit bug, maybe some obscure regalloc stuff, who knows..

**Comment by hrydgard** [comment]
So apparently this works fine if you disable Fast Memory, which is a little curious.

**Comment by unknownbrackets** [comment]
Could this have been affected by the rounding fix on thread switch?

-[Unknown]

**Comment by Saramagrean** [comment]
Test on latest build v1.5.4-980
- JIT+FastMem on or off = Crash
- IR Interpreter+FastMem on or off = Crash
- Interpreter+FastMem on or off = Not crash, swtich CPU core to JIT, game run full speed but stuck at loading screen after choose song. 😂

**Comment by Saramagrean** [comment]
v1.7.5-414 use JIT game can run with checked "Static regalloc" in JIT debug tools, but game freeze after choose song.

**Comment by hrydgard** [comment]
Thanks, that's really interesting!

**Comment by unknownbrackets** [comment]
Hm, that static regalloc affects this at all might mean that somewhere we're misusing a static reg?

-[Unknown]

**Comment by hrydgard** [comment]
Got my hands on this now (along with a bunch of weird promo/pre-release games from some seller on FB marketplace, heh) and can't get it to run at all on ARM64, no matter how much of the JIT I disable. Hm.

**Comment by hrydgard** [comment]
Just noting that the game works fine on Linux x64 (Ubuntu). So whatever it is, it's something Android specific.. ???

**Comment by unknownbrackets** [comment]
IR Interp works fine on those devices though, right?

-[Unknown]

**Comment by hrydgard** [comment]
No, in fact it currently crashes in the IR interpreter too.

**Comment by Saramagrean** [comment]
v1.7.5-553 checked Static regalloc not help, game crash on boot again. but game can run if set CPU core to Interpreter after game boot change to JIT, and game not hang after choose song, can playable in-game.

![53341328_301969893801497_8421061923939811328_n](https://user-images.githubusercontent.com/26355472/54009253-ad514980-419c-11e9-9ecc-14b8254a03c7.png)

**Comment by hoholee12** [comment]
v1.8.0 armjit64 same issue black screen on boot for djmax portable black square edition. only the very first djmax portable seems to work without problems..

**Comment by unknownbrackets** [comment]
v1.7.5-553 (tested in March) is very close to 1.8.0, so that's expected.  If anything were to change, it'd be in the latest git builds which a few hundred changes/fixes/improvements/new bugs since v1.8.0.

Is it possible to validate this on non-Android ARM?  That might help narrow things down.  Specific options would include:

 * iOS (though PPSSPP is not very stable on iOS in general)
 * Linux ARM/ARM64 (such as Raspberry Pi)
 * Windows 10 on ARM

Also, does it crash on Windows (7, 8, 10, whatever - but Intel x64) with fast memory on?  What about Windows x32?

If it crashes across CPU and GPU variants (including x86), I'd think it's something to do with one of:
 * Platform type sizes (i.e. time_t or tm)
 * Disk IO (i.e. like the 64-bit problems we saw with hacked ISOs)
 * Bad memory access we don't detect but is silently ignored on Windows x64.

-[Unknown]

**Comment by hrydgard** [comment]
Signed vs unsigned char is another of those wacky ARM differences that popped up in my head when I saw this issue again now..

**Comment by hoholee12** [comment]
> v1.7.5-553 (tested in March) is very close to 1.8.0, so that's expected. If anything were to change, it'd be in the latest git builds which are a few hundred changes/fixes/improvements/new bugs since v1.8.0.
> 
> Is it possible to validate this on non-Android ARM? That might help narrow things down. Specific options would include:
> 
> * iOS (though PPSSPP is not very stable on iOS in general)
> * Linux ARM/ARM64 (such as Raspberry Pi)
> * Windows 10 on ARM
> 
> Also, does it crash on Windows (7, 8, 10, whatever - but Intel x64) with fast memory on? What about Windows x32?
> 
> If it crashes across CPU and GPU variants (including x86), I'd think it's something to do with one of:
> 
> * Platform type sizes (i.e. time_t or tm)
> * Disk IO (i.e. like the 64-bit problems we saw with hacked ISOs)
> * Bad memory access we don't detect but is silently ignored on Windows x64.
> 
> -[Unknown]

djmax 3 and black square have no issue whatsoever on intel64 even with fast memory enabled

**Comment by Saramagrean** [comment]
Found a fix for crashing on PPSSPP main screen on android.
Go to Settings > System > Change Memory Stick Folder > From "/storage/emulated/0" to "storage/emulated/0/ppsspp

https://forums.ppsspp.org/showthread.php?tid=11405&pid=134687#pid134687

**Comment by LunaMoo** [comment]
Added not a bug label since it's working as it should, game detects running of memstick and intentionally doesn't work as an anti-piracy feature.

**Comment by hrydgard** [comment]
Whoa. I think it's up to the emulator to work around this, this is very surprising behavior for users. Leaving open.
