### ISSUE TITLE
Tactics Ogre: Let Us Cling Together crashes (Android ARM64)

### ISSUE THREAD

**Issue by mrcorra** [hrydgard/ppsspp#9488]
When I play Tactics Ogre, the game always crashes after a certain point. When I disabled fastmem, the app wouldn't crash, but it would be taken into an endless loading screen. The phone I am using is an LG Stylo 2 Plus.

**Comment by hrydgard** [comment]
Just curious, what's the "certain point" where it crashes?

**Comment by hrydgard** [comment]
With that latest commit, fast memory turned off should work. Might be worth trying (though there's obviously a real bug too).

**Comment by mrcorra** [comment]
Well, its very early. In the beginning, it shows you how the battle system works. After that its a small cut scene. After the cut scene, that's when it crashes. And like I said, turning off fast memory doesn't work either. It just stays in an endless loading screen.

**Comment by hrydgard** [comment]
Also, you sure you have a clean dump? I think lots of people have been playing this game without reporting this issue...

**Comment by mrcorra** [comment]
Weird, when I try to update it, it says "App not installed". Although, I'm sure that's not a problem that has to do with the app or update. Thanks anyway.

**Comment by sum2012** [comment]
@mrcmunir try uninstall old ppsspp first((You need backup save fist)

**Comment by mrcmunir** [comment]
@sum2012 me? you wrong nick

**Comment by hrydgard** [comment]
yeah, he means @mrcorra - mrcorra, see above.

**Comment by sum2012** [comment]
@mrcmunir sorry,please ignore
@mrcorra try uninstall old ppsspp first (You need backup save fist)

**Comment by mrcorra** [comment]
OK, the update didn't work. The game still acts up in the exact same manner. I think I forgot to mention, when I change the games speed by pressing the fast forward button, or if I change the fps, the screen will flicker.

**Comment by hrydgard** [comment]
Has this ever worked with an old version of PPSSPP? I'm really starting to suspect you have a broken ISO.

**Comment by sum2012** [comment]
I test no problem " In the beginning, it shows you how the battle system works. After that its a small cut scene. After the cut scene, that's when it crashes" on Asus zenfone 3 on USA version default expect frame skip 2

**Comment by mrcorra** [comment]
The ISO worked on my laptop.

**Comment by mrcorra** [comment]
I'm probably making some sort of mistake. I'm sorry.

**Comment by sum2012** [comment]
Can you try to update again in http://buildbot.orphis.net/ppsspp/ ,It fix crash in android in other issue

**Comment by sum2012** [comment]
@mrcorra Can you try to update again in http://buildbot.orphis.net/ppsspp/ ,It fix crash in android in other issue

**Comment by unknownbrackets** [comment]
I double checked this on a Pixel running arm64, played until the end of Tynemouth Hill, with fast memory off.  No crashes, using a clean USA copy.

Closing - if you're still experiencing, we'll reopen.  But please double check the version number on the main screen (it should be something like v1.4.2-267-g033676ca4 or at least v1.4.2), and please give the crc of the ISO and which region you're using.

-[Unknown]
