### ISSUE TITLE
Android Beta Program, versioning issues

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#9490]
On Google Play, there's now the possibility to let anyone sign up to be a beta tester for an app. There are also now nice API:s to push new builds automatically, instead of manually uploading APKs from the web interface.

It would therefore be quite possible to have an automatically-updating beta program, plus a mostly-automated way for me to make new official releases much easier than the way I've done it currently (lots of manual clicking around, building and copying files).

I've set up a private Jenkins server that I can use to trigger builds, and I'm writing a python script that will run at the end of the build process to upload the APK to a Beta channel on Google Play.

Unfortunately this server needs to be private due to key management for the signing, but I'll open up some of the scripts that I use on it later.

Anyway, here's the practical issue. Even beta builds need incrementing Android version numbers, and we thus need to decide on a numbering scheme. We can easily get "git describe" from gradle with the following:

	def getGitDescribe = {
		def stdout = new ByteArrayOutputStream()
		exec {
			commandLine 'git', 'describe', '--tags'
			standardOutput = stdout
		}
		return stdout.toString().trim()
	}

and we can use ```defaultConfig { versionCode = ... versionName = "..." }``` to override the version numbers from AndroidManifest.xml.

My proposal is as follows:

  * Use git-describe, and munge the output as follows: ```v1.3-1108-g24720f9 -> { versionName: "1.3-1108" versionCode=13001108 }```

So we're moving from 4-digit version codes to 8-digit. No-one really looks at those codes anyway, so it should be fine.

The only drawback I can see with this pattern is that we're limited to 9999 versions per major version, but that should be OK. Could also add more digits but seems like overkill.

There are also other ways than shelling out to git like https://github.com/gladed/gradle-android-git-version which imports jgit, but that seems like a bit overkill.

Opinions or other ideas?

Here's an article with some other tricks, but I don't think we want to use that approach: http://orip.org/2013/10/versioning-android-apps-with-git-tags.html

**Comment by tausifj15** [comment]
Sir i joined the beta programme but isnt get any update?

**Comment by tausifj15** [comment]
But at this web got many updates😇

**Comment by hrydgard** [comment]
Not yet, the auto updating system isn't finished. I will start it up sometime after 1.4.

**Comment by unknownbrackets** [comment]
Well, I think ppsspp-report already makes this 9999 assumption, so I'm not against doubling down on that.  (It uses `10230004` for `1.2.3-4-g*` - which means `1.20.3-4` is okay but not `1.2.30-4`.)

I'm not sure if we'd actually go to `1.10.0` or `1.5.10`, although I think it's safer if we stick away from `1.4.0.1` for all version numbering.

We'd only do beta builds for master, so the non-linearity of git describe numbers isn't a problem, right?

-[Unknown]

**Comment by hrydgard** [comment]
Right, I don't want to throw multiple branches into the mix. So the numbering will be consistently increasing.

**Comment by InusualZ** [comment]
About the 9999 limit, you can't add something like an `alpha`, `beta` or `pre-release` tag?

**Comment by hrydgard** [comment]
The version code is a number, it's what the Play Store uses to distinguish builds.

**Comment by InusualZ** [comment]
Ohhh, good to know.

**Comment by hrydgard** [comment]
Found an awesome gradle plugin that does exactly this: https://github.com/gladed/gradle-android-git-version . Implementing shortly.
