### ISSUE TITLE
Report from baidu before v1.4

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#9493]
Android: Qualcomm 820 frameskip  1 make game very lag(full fps also lag)
Direct x 11 crash (gpu :Nvidia gtx 660) edit:windows7 64 bit
chinese font issue:edit:I would ask him detail

**Comment by zminhquanz** [comment]
i think DX 11 it isn't fix all bugs , but on Android using Qualcomm Snapdragon i think it's driver weird or CPU Core IPC not powerful IPC

**Comment by sum2012** [comment]
His phone detail:
![1](https://cloud.githubusercontent.com/assets/2177532/24292122/dca9790e-10c6-11e7-9602-079b51f6a768.jpg)
![2](https://cloud.githubusercontent.com/assets/2177532/24292124/dcad8a76-10c6-11e7-9a80-07974269279a.jpg)
![3](https://cloud.githubusercontent.com/assets/2177532/24292123/dcabd91a-10c6-11e7-8e46-d5cd3112c3f3.jpg)
![4](https://cloud.githubusercontent.com/assets/2177532/24292125/dcae4cc2-10c6-11e7-81ff-eae6e362708f.jpg)

**Comment by hrydgard** [comment]
So, it works fine with frameskip 0? 

Seems like there could be some power management going crazy when PPSSPP waits for the time to show the next frame, otherwise I don't have any good ideas about this...

**Comment by hrydgard** [comment]
For the DX11 crash, any chance of a stack trace?  (run in the VS debugger and see where it crashes)

**Comment by sum2012** [comment]
@hrydgard Yes,his phone also lag in v1.2
For the DX11 crash, I am telling him to install VS2015

**Comment by hrydgard** [comment]
OK, then it's not a regression at least, so we don't have to hunt for a broken change. Would still be good to solve if possible though. One possibility might be to output each frame twice, would still be less rendering work than rendering at a full 60hz but more expensive than waiting to skip a frame.

**Comment by sum2012** [comment]
You can just make a branch,I  compile to him test

**Comment by sum2012** [comment]
@hrydgard Another user report use vulkan in fullscreen would blackscreen,As vulkan use non-buffer rendering,can we ignore this report ?

**Comment by hrydgard** [comment]
Vulkan is "experimental", still need to spend some time on fixing it up properly. Would ignore it for now.

**Comment by sum2012** [comment]
DX11 crash reporter said that this picture error
I said that to him that try to install full option
![1](https://cloud.githubusercontent.com/assets/2177532/24326745/22effc1a-11f0-11e7-81bc-cad0b31147e7.png)

**Comment by sum2012** [comment]
DX11 crash reporter said that no problem after reinstall VS2015
Seem some run-time have been installed or updated

**Comment by sum2012** [comment]
A mac user report that play God of War and mhp3 a while,the system said no memory not enough or crash in v1.3.
1.22 version no problem.His device is 16gb

**Comment by sum2012** [comment]
Some Android user report that enable "io multi-thread" would lead to cannot save in-game.

**Comment by hrydgard** [comment]
"cannot save", does that mean hang, crash or just a failure?

**Comment by sum2012** [comment]
http://imgur.com/a/5NacH
English mean that disk is full cannot save

**Comment by unknownbrackets** [comment]
If we're showing an osm that the disk is full, it should mean that the disk really is full.  It's definitely not?

We specifically show that message on "ENOSPC":
https://github.com/hrydgard/ppsspp/blob/master/Core/FileSystems/DirectoryFileSystem.cpp#L305
https://github.com/hrydgard/ppsspp/blob/master/Core/FileSystems/DirectoryFileSystem.cpp#L352

`errno` is supposed to be a magic thread-safe macro, but I don't know for sure if it is on Android.  But I woudln't expect other calls to commonly generate ENOSPC anyway...

-[Unknown]

**Comment by sum2012** [comment]
More information from him.
His phone is oppo,OS:Color OS,Android 4.4.4
Default setting.Need change "io multi-thread" false to fix

**Comment by sum2012** [comment]
1.4 has came,closing this
