### ISSUE TITLE
Portable Ops Plus freeze issue on Ad-hoc plus

### ISSUE THREAD

**Issue by kikongokiller** [hrydgard/ppsspp#9494]
When playing Portable Ops Plus, the game simply freezes when looking for matches on adhoc plus.

Are there any differences in the netcode from 9.9.1 to 1.3? 9.9.1 being the only version of ppsspp that works with adhoc on MPO+

**Comment by JacobMrox** [comment]
same

**Comment by unknownbrackets** [comment]
Is this still an issue on the latest git build with recent networking improvements?

-[Unknown]

**Comment by MojoJojoDojo** [comment]
This got fixed as far as I know since at least 1.10.3-908 or before it (Don't know what happened after that git build though.).
