### ISSUE TITLE
Warriors Orochi 2 FMV bug (Windows)

### ISSUE THREAD

**Issue by Ofunniku** [hrydgard/ppsspp#9498]
FMV bug tracked down to first showing in build 982, still present in latest builds.
http://buildbot.orphis.net/ppsspp/index.php?m=get&rev=v1.3-982-gd30116b&platform=windows-amd64

This build and prior builds did not have this issue.
http://buildbot.orphis.net/ppsspp/index.php?m=get&rev=v1.3-979-g2336792&platform=windows-amd64

![2017 03 25-01 51](https://cloud.githubusercontent.com/assets/5677089/24320075/7d09d9c4-1168-11e7-8567-067e9c61b16a.jpg)

All the Warriors Orochi 2 FMVs are displayed that way, but Soul Calibur FMVs seem fine.

Here is the log output:
```
23:42:985 user_main    E[ME]: HLE\sceMpeg.cpp:1968 UNIMPL sceMpegAvcInitYCbCr(09fff5dc, 1, 480, 272, 094161e0)
23:55:403 user_main    E[ME]: HLE\sceMpeg.cpp:1253 UNIMPL sceMpegAvcDecodeStopYCbCr(09fff5dc, 09ecf97c, 09fff404)
23:55:788 user_main    E[ME]: HLE\sceMpeg.cpp:1968 UNIMPL sceMpegAvcInitYCbCr(09fff5dc, 1, 480, 272, 094161e0)
```

**Comment by Ofunniku** [comment]
UPDATE: Turns out, 981 also has this problem, I just checked it (previously skipped because it was a 32-bit build)
http://buildbot.orphis.net/ppsspp/index.php?m=get&rev=v1.3-981-gf6463ae&platform=windows-x86
So it's either #9451 or #9449 that kicked this up.

**Comment by unknownbrackets** [comment]
Thanks for finding the range.  The git build numbers aren't exactly linear - here's the comparison for working in v1.3-979-g2336792, broken in v1.3-981-gf6463ae:

https://github.com/hrydgard/ppsspp/compare/2336792...f6463ae

Which means this is #9449.  To me, it looks like this is a bug somewhere else that was just exposed by this change (maybe some video upload / drawpixels function not dirtying state.)

-[Unknown]

**Comment by unknownbrackets** [comment]
Can you check the GE debugger while the video is playing?  Follow just the first four steps of this:

https://github.com/hrydgard/ppsspp/wiki/How-to-find-a-graphic-issue-with-the-GE-debugger

What I want to confirm is:
 * Does it draw each slice of the video (the repeating part) separately?  If yes, you'll see it likely highlight the entire screen red, then each slice red in sequence as you click "Step Prim".  Red indicates where it's about to do something.

 * If so, does the text under the left image (when it says "Texture L0: ..." - ignore "Texture: disabled") always say the same thing?  For example, "Texture L0: 0x04110000 (512x512)".

If the answer to either is no, then that disproves my theory for why #9449 could've broken this.

-[Unknown]

**Comment by Ofunniku** [comment]
Texture L0: 0x041d70c0 (128x512) is always the frame it draws to, and doesn't seem to change on every "step prim" during video playback

**Comment by Ofunniku** [comment]
PR #9500 has addressed this issue nicely and video is now back to normal, thanks.

**Comment by Ofunniku** [comment]
(Whops, busted mouse problems, sorry for reopening, can you guys close this, please?)
