### ISSUE TITLE
Choppy sound

### ISSUE THREAD

**Issue by mrcorra** [hrydgard/ppsspp#9499]
So before I updated the app to unsucsessfully fix the problems with Tactics Ogre, it would run perfectly with Final Fantasy VII Crisis Core. I was even able to make the resolution double plus add a bloom effect, and it'd still work perfectly. But since the update, the sound is choppy even with absolute minimal graphics.

**Comment by hrydgard** [comment]
Please give more information when reporting issues, you can't expect people to remember from your previous ones. For example, what hardware are you running? What operating system?

**Comment by ijoinit** [comment]
You need a downgrade,just for android and windows here http://buildbot.orphis.net/ppsspp/index.php?m=fulllist

**Comment by mrcorra** [comment]
So the thing is, Tactics Ogre

**Comment by mrcorra** [comment]
Crisis Core works fine. Sorry.
