### ISSUE TITLE
Tekken 6 crashes if allowed to show intro Video

### ISSUE THREAD

**Issue by 007flawless** [hrydgard/ppsspp#9503]
As of build v1. 3-1126 Android, Tekken 6 crashes if allowed to play the intro video.. The only way I bypass this is by holding down the Fast Forward button and smashing the start button till it gets to the main menu

My hardware is Galaxy S5 (Snapdragon 801) running Android 6.0.1

Aside that the game works perfectly and fast too

**Comment by unknownbrackets** [comment]
What's the last build that worked without crashing, and the first build that started crashing?

-[Unknown]

**Comment by 007flawless** [comment]
I've been on v1.3.0.1 stock playstore version for a long time now because of data.. I just decided to check out the new build just incase of any improvements..

**Comment by 007flawless** [comment]
I just ran some tests and the last build with working video was build 699


The first build with crashing video is build 703

**Comment by sum2012** [comment]
I test no problem on Asus zenfone 3
Can you try to move the iso to "/storage/emulated/0/" ?

**Comment by Ofunniku** [comment]
I've actually been having this issue as well, I'll try this myself...

**Comment by Ofunniku** [comment]
Disregard, it was a bad dump, redumped and works fine on the latest windows builds

**Comment by 007flawless** [comment]
@sum2012 The game crashes after video playback irrespective of storage location.. This is not related to storage location

@ofunniku Am using the Android build as I stated before, I don't know about windows build cause I haven't tested nor use it

**Comment by unknownbrackets** [comment]
Hmm, the main change there I see is this:

https://github.com/hrydgard/ppsspp/compare/40e414c...31dd8fd#diff-75c8069425e8a3b0579a812b68c853f6R86

Are you using "retain changed textures" or "multithreading"?  Does it help if you turn off either setting?  Are you using any tools that lie about your device's graphics capabilities (like "Chainfire3D" - these just cause crashes with PPSSPP)?

-[Unknown]

**Comment by 007flawless** [comment]
Disabling "Retain changed textures"  completely fixed it. Since the introduction of this option, I completely enabled it in all my games settings, and so far have had no issues.. What changed in those two builds to result in this crash now? 


I never use multithreading at all because it most often ruins my game performance so I avoid it 100%

Also chainfire? Never used it before

**Comment by 007flawless** [comment]
Thanks for yr help anyway! 😀

**Comment by unknownbrackets** [comment]
Could you try it again in v1.3-1128-g13c7241 with the setting on?

-[Unknown]

**Comment by 007flawless** [comment]
In build 1128, it's worse nw wit the option on.. If allowed to play d video, it goes One second in, then crashes the emulator.. Before this, the video would play well, then when done would crash 


But nevertheless, if i turn off Retain texture, it fixes this.

**Comment by unknownbrackets** [comment]
I'm curious if you get any benefit from using the secondary cache - my tests previously (haven't done them in a while) showed that it was generally slower in most games.  However, this fix might help that.

It is much faster in a few games, mostly games that do a lot of colorswapping.

-[Unknown]
