### ISSUE TITLE
broken linux build std::atomic<bool>' invokes deleted constructor

### ISSUE THREAD

**Issue by mrcmunir** [hrydgard/ppsspp#9507]
>In file included from /run/media/mrc/C0D47D0DD47D0746/psp/ppsspp/UI/NativeApp.cpp:89:
/run/media/mrc/C0D47D0DD47D0746/psp/ppsspp/UI/GameInfoCache.h:67:33: error: copying member subobject of type 'std::atomic<bool>' invokes deleted constructor
        std::atomic<bool> dataLoaded = false;
                                       ^~~~~
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.3.1/../../../../include/c++/6.3.1/atomic:66:5: note: 'atomic' has been explicitly marked deleted here
    atomic(const atomic&) = delete;
    ^
In file included from /run/media/mrc/C0D47D0DD47D0746/psp/ppsspp/UI/NativeApp.cpp:89:
/run/media/mrc/C0D47D0DD47D0746/psp/ppsspp/UI/GameInfoCache.h:129:36: error: copying member subobject of type 'std::atomic<bool>' invokes deleted constructor
        std::atomic<bool> sndDataLoaded = false;
                                          ^~~~~
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.3.1/../../../../include/c++/6.3.1/atomic:66:5: note: 'atomic' has been explicitly marked deleted here
    atomic(const atomic&) = delete;
    ^
2 errors generated.
make[2]: *** [CMakeFiles/PPSSPPSDL.dir/build.make:87: CMakeFiles/PPSSPPSDL.dir/UI/NativeApp.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:440: CMakeFiles/PPSSPPSDL.dir/all] Error 2
make: *** [Makefile:128: all] Error 2

**Comment by hrydgard** [comment]
I know, already fixed it.

**Comment by mrcmunir** [comment]
Right Fixed in that commit compile now  thanks
