### ISSUE TITLE
[Idea] XMB Mode for PPSSPP

### ISSUE THREAD

**Issue by DarkLegend481** [hrydgard/ppsspp#9512]
Hi! I was wondering... How about adding an XMB mode? Yes, I know about copyright, but not emulate the XMB, and yes, just add a view mode of the games in the XMB style. I knew there are several projects that use the XMB interface or imitate it and Sony never interfered in these projects...

**Comment by mrcmunir** [comment]
For now you can alternative  with JPCSP emulator https://github.com/jpcsp/jpcsp/tree/master/src/jpcsp/HLE/VFS/xmb

They add support for that if these folder files from dump psp firmware 

In PPSSPP I do not think it will ever happen since the developers are reactions to support it

**Comment by DarkLegend481** [comment]
My idea:

• Add on Graphics settings the option to change into PPSSPP Mode and XMB Mode
• If you use the XMB Mode, add 3 folders to PSP/SYSTEM: CATEGORIES and ICONS

A little description:
* CATEGORIES folder: Add folders with names of your custom categories like GAMES, HOMEBREWS and more...
* ICONS: Add icons to your categories (needs a file to assign icons like icons.txt)

To add games, you need a file to assign games to categories like game.txt or something like that...

**Comment by DarkLegend481** [comment]
Oh, and If this issue become a part of PPSSPP... Enable this on UWP (W10M, PC and XONE).

**Comment by hrydgard** [comment]
We have our own UI and I'm not really interested in creating a second different one, it's too much work. 

If it happens, though, it will obviously be on all platforms so don't worry about UWP.

**Comment by zminhquanz** [comment]
I think it's too much work for team , i think create UMD Video it's interesting for now

**Comment by DarkLegend481** [comment]
Oh, ok... I will close this. Just commenting, I like PPSSPP UI, I just give this idea to turn PPSSPP more like the original PSP...

**Comment by DarkLegend481** [comment]
When UWP Version comes up?

**Comment by hrydgard** [comment]
When it's done, but fairly soon hopefully. Need to sort out the file browser and how to do automatic builds with signing for the store.

**Comment by DarkLegend481** [comment]
@hrydgard I know a little about C#, maybe, I can help with something. 😊

**Comment by hrydgard** [comment]
There's no C# in it :)

**Comment by DarkLegend481** [comment]
Ahhhhhh! But, is there any way I can help? (Just wait is boring... 🙁) I have VS2015 installed on my PC and some C++, C# and UWP tools on it.

**Comment by meepingsnesroms** [comment]
This should be doable using the retro Arch xmb menu, but I have no experience with this.

This is assuming you are not going to switch to lle and write all the firmware decryption routines to get the official OS running.

**Comment by DarkLegend481** [comment]
@meepingsnesroms Retroarch's XMB Menu Skin: Easy on PC, hard on Mobile...

And I did not say "emulate XMB" or "add the PSP OS" and yes, just gave a idea to create a UI mode to "simulate" XMB.

(Forgive my English...)
