### ISSUE TITLE
[Regresion] Hw tesselation can't select now in mesa3d driver

### ISSUE THREAD

**Issue by mrcmunir** [hrydgard/ppsspp#9514]
In the recent changes https://github.com/hrydgard/ppsspp/pull/9510

The main problem is Extension gpu shader4 is not supported in mesa3d driver 
If we check for the Extension shader4 never work in mesa3d drivers and  Hack I pull some mouth ago are disable for that unsuported extension

https://github.com/hrydgard/ppsspp/blob/master/tesselationhwON-mesa3drun.sh

 I use Opengl 3.3COMPAT core .and working fine no needed checked that extension.

Any ideas?

**Comment by unknownbrackets** [comment]
Well, normally, I think 3.0 and higher incorporates EXT_gpu_shader4 into core?

-[Unknown]

**Comment by hrydgard** [comment]
Querying extensions in GL is such a mess...

**Comment by mrcmunir** [comment]
@unknownbrackets I research and tested force core to Opengl 3.0/3.1/3.2 in mesa3d and won't work  they miss gl_InstanceID reference.

is Opengl 3.3COMPAT -> Opengl 3.3/3.3 GLSL minimum run fine for the implemented HW tesselation  in mesa3d.

**Comment by mrcmunir** [comment]
@hrydgard @unknownbrackets 

I detected when force Opengl 4.3 core tesselation is enable and works

 export MESA_GL_VERSION_OVERRIDE=4.3COMPAT

If You change to lower core than Opengl 4.3 can't pass the check need disable the check.

It's kind of strange here to require Opengl 4.3  ¿Any real reason Opengl 3.3 core to Opengl 4.3 core can pass the check?

**Comment by unknownbrackets** [comment]
If the latest update to #9976 doesn't help, it'd help if you could list what extensions 4.3 shows that 4.2 doesn't, for you.

-[Unknown]

**Comment by mrcmunir** [comment]
Fixed by https://github.com/hrydgard/ppsspp/pull/9976
