### ISSUE TITLE
god eater2(NPJH50832),high light too dazzling

### ISSUE THREAD

**Issue by ijoinit** [hrydgard/ppsspp#9515]
hi.boss,I got 2 pictures to compare,,when buffered rendering light too dazzling,when use non-buffered no light but sub only show a little half(due to iPad's 4:3 screen ratio?),on OpenGL,but i don't have a real PSP to compare.
![2017-03-3110_59_14 png](https://cloud.githubusercontent.com/assets/26176492/24534993/eaa71dc6-1603-11e7-8b80-2b79d959fc98.jpg)
![2017-03-312010_58_54_png](https://cloud.githubusercontent.com/assets/26176492/24534994/eab974ee-1603-11e7-8ca5-6df98717f8da.jpg)

**Comment by ijoinit** [comment]
OpenGL can't handle it very well While D3D11 is doing the right thing ![img_0350](https://cloud.githubusercontent.com/assets/26176492/24575921/c647a05e-16e4-11e7-8827-d4e7e24fbbd5.PNG)

**Comment by LunaMoo** [comment]
We already track this issue in #5562 and as such I'm closing this, there's no need for duplicates of same problem even if it's different game version.

**Comment by ijoinit** [comment]
Oh, I was just to close this,because,I just finally figured out,just need turn of the "Disable alpha test(PowerVR speedup,artifacts)",and the funny highlights will gone,thank you guys.

**Comment by ijoinit** [comment]
Yeah,that #5562 issue will stand in page 20s forever,I think.

**Comment by ijoinit** [comment]
I think I'm tired of the unofficially supported PPSSPP for ios,i might need a galaxy s8,but that's a lot of money,damn
