### ISSUE TITLE
Autosave wont work on mod nation racer please fixs

### ISSUE THREAD

**Issue by omarguerrero5310** [hrydgard/ppsspp#9517]

**Comment by unknownbrackets** [comment]
What happens?  Did it used to work?  What platform are you using?  Can't be fixed without more information.

-[Unknown]

**Comment by omarguerrero5310** [comment]
Android and Windows and iOS

**Comment by omarguerrero5310** [comment]
Yes it did work before but now it doesn't

**Comment by unknownbrackets** [comment]
Thanks - I'll close this as a duplicate of #6078.

-[Unknown]
