### ISSUE TITLE
Unable to use/map controllers in 1.4 source build on Ubuntu 14.04 Linux

### ISSUE THREAD

**Issue by rcampbel3** [hrydgard/ppsspp#9519]
Hi,

I have quite regularly built from source on a slightly modified Ubuntu 14.04 base since about version 1.1 days. Recently I've had an issue with my source builds -- Neither the QT nor the SDL builds since about mid 1.3 seem to recognize my wired PS2 joysticks as input -- it's as if they don't exist, yet they definitely do and work in everything else. The 1.3 build from the Ubuntu PPA continues to work as expected with the same joystick, and up until a few months ago, I was building from source regularly with no issue. Output logs don't offer me much clue.
I see this, but I can't use controller nor input new control mappings:
> loading control pad mappings from gamecontrollerdb.txt: SUCCESS!

I get the same thing with no old config files and new configuration data as well.

**Comment by hrydgard** [comment]
Since you can do source build, do you think you could do a git bisect to find the commit where it stopped working for you? That would be very useful in finding out what's wrong. Should be about 2000 revs, log2 that is 11 so ~12 tests. You'll need to "git submodule update --init --recursive" after every step which is a bit of a pain though.

**Comment by rcampbel3** [comment]
Interesting - I didn't know about git bisect. I'll see what I can do. It's also possible that I changed something on my system that might explain the issue, but I build a ton of stuff from source on this system, and joystick input works everywhere else. Will investigate further.

**Comment by jbeich** [comment]
Maybe related to #8993. My guess, SDL_GameController API only accepts joysticks that have buttons mapped to the standard (Xbox 360 style) layout. As PPSSPP doesn't have UI to do the mapping if the joystick is absent in `assets/gamecontrollerdb.txt` you may need to generate the string using **antimicro** or `test/controllermap.c` (from SDL source). Append it to the file or use `SDL_GAMECONTROLLERCONFIG` environment variable. Other OSes may have a central database which is updated as soon as you plug an unknown joystick with "Game Pad" in USB HID.

Alternatively, check if [my patch](https://github.com/freebsd/freebsd-ports/blob/064f9430ec9a/emulators/ppsspp/files/extra-patch-old-joy) which restores old joystick code has any effect. I've created it to work around a [dowstream bug](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=218289).

**Comment by rcampbel3** [comment]
I'll try this.  I can also confirm that a clean 1.4 source checkout produced the same result and that when I got the 1.4 binary update via the PPA, my joystick stopped working as well.

**Comment by rcampbel3** [comment]
Confirmed: This patch against latest source returns my ability to use my PS2 controllers which are connected via a USB-PS2 adapter.

**Comment by unknownbrackets** [comment]
Does this work now?  I think that the old code was restored when the mapping isn't found.

-[Unknown]

**Comment by rcampbel3** [comment]
I'll test this tonight - I recently did a build and was surprised that I could configure my joystick, but I thought it must have been related to the steam helper running that exposes my joystick as an xinput device. Will be happy if I can finally update my version to latest source.

**Comment by rcampbel3** [comment]
Confirmed! I can now again map any inputs on any controller without needing a gamecontrollerdb.txt file
