### ISSUE TITLE
Addition of errors (SD Gundam G Generation on V1.4)

### ISSUE THREAD

**Issue by LightVR0** [hrydgard/ppsspp#9520]
SD Gundam G Generation (portable/World/Overworld) + V1.4 = missed fonts!!!

**Comment by hrydgard** [comment]
Argh, I know why. My last minute change ... doh. I'll fix it. This should only affect the Android version.

**Comment by hrydgard** [comment]
Fix has been pushed to Google Play.

**Comment by LightVR0** [comment]
Some bug detected on the last git. This bug no happens on Windows.

**Comment by hrydgard** [comment]
Ah, yeah, buildbot still had an issue. I fixed its script. Making a dummy commit to make a new build shortly.
