### ISSUE TITLE
Namco Museum - Battle Collection - ULUS100035 loading problem

### ISSUE THREAD

**Issue by benderscruffy** [hrydgard/ppsspp#9523]
using ppsspp 1.4
any game you choose from the left hand side (originals) it just sits on the now loading screen and nothing else
if you choose any game from the arrangement side they all load 
here is a debug log 
rename txt to zip
[ppsspplog.txt](https://github.com/hrydgard/ppsspp/files/887379/ppsspplog.txt)

**Comment by ijoinit** [comment]
Oh,that's a really big log file,my notebook even get stucked,Mine 1.4 on windows no such problem,I don't know,but when you copy the new 1.4 files to your ppsspp folder,you should delete all old files first,except memstick folder and ISOs

**Comment by unknownbrackets** [comment]
Did this used to work in some past version of PPSSPP?  If so, what build made it stop working?

-[Unknown]

**Comment by benderscruffy** [comment]
went back as far as 1.1.1 and still the same problem

**Comment by sum2012** [comment]
JPCSP work,log:
 https://gist.github.com/sum2012/eda0d730592c2be2da97b5ce8fa701ec
Mainly missing these
17:46:50  INFO   loader - SceWaveMain - Found ModuleInfo at 0x095F6174, name:'pacman', version: 0101, attr: 0x00000002, gp: 0x09660AD0
17:46:50  INFO   loader - SceWaveMain - Found 83 unresolved imports
17:46:50  INFO   loader - SceWaveMain - 83 NIDS mapped

**Comment by thecommanderox** [comment]
So is there a fix for this in a newer version or what?

**Comment by sum2012** [comment]
@thecommanderox There is still do not know the real reason that why this game not work,

Update log to v1.4.2-308-g945f57af3
https://gist.github.com/sum2012/cbf933a83adce753db50a9cf88dc5615

debug log:
https://drive.google.com/file/d/0B3OaSdeV0L8kVWJTWTFEYmVabUk/view?usp=sharing

**Comment by benderscruffy** [comment]
v1.5.4-933-g386c9d4fc
still present any game you choose from the left hand side (originals) it just sits on the now loading screen and nothing else

**Comment by Panderner** [comment]
Still happens on 1.9.2

**Comment by Gamemulatorer** [comment]
I can repro this issue using ppsspp v1.9.3-908

I get white screen and black screen on title screen.

### 1st loading white screen
![Screenshot_20200521-224305](https://user-images.githubusercontent.com/37603562/82571210-33e12380-9bb5-11ea-91e3-e1665a725afc.png)
ge dump 
[white screen.zip](https://github.com/hrydgard/ppsspp/files/4663068/white.screen.zip)
### press start got black screen
![Screenshot_20200521-224403](https://user-images.githubusercontent.com/37603562/82571309-5c691d80-9bb5-11ea-8e77-e7f45aaebf16.png)
ge dump 
[black screen.zip](https://github.com/hrydgard/ppsspp/files/4663079/black.screen.zip)

Also tried changing I/O Timing Method doesn't help this issue.

**Comment by sum2012** [comment]
Can you share the game save ?
I lost the game save.

在 2020年5月21日週四 22:50，Angelo Burgos <notifications@github.com> 寫道：

**Comment by Gamemulatorer** [comment]
> the

Savestate or Savedata? 😅

**Comment by sum2012** [comment]
save data

在 2020年5月22日週五 06:46，Angelo Burgos <notifications@github.com> 寫道：

**Comment by Panderner** [comment]
> I can repro this issue using ppsspp v1.9.3-908
> 
> I get white screen and black screen on title screen.
> 
> ### 1st loading white screen
> ![Screenshot_20200521-224305](https://user-images.githubusercontent.com/37603562/82571210-33e12380-9bb5-11ea-91e3-e1665a725afc.png)
> ge dump
> [white screen.zip](https://github.com/hrydgard/ppsspp/files/4663068/white.screen.zip)
> 
> ### press start got black screen
> ![Screenshot_20200521-224403](https://user-images.githubusercontent.com/37603562/82571309-5c691d80-9bb5-11ea-8e77-e7f45aaebf16.png)
> ge dump
> [black screen.zip](https://github.com/hrydgard/ppsspp/files/4663079/black.screen.zip)
> 
> Also tried changing I/O Timing Method doesn't help this issue.

@Gamemulatorer i can't produce this issue, it works fine for me except games from original section it's stuck at loading screen. but your ISO is corrupted.

**Comment by sum2012** [comment]
Sorry, I misunderstand the other game.
This game is infinite loading.

v1.9.3-924-gbff3c15d6
debug log:  
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/4668567/ppsspplog.zip)

**Comment by sum2012** [comment]
The game is 90% similar then super old jpcsp(hang)
We have chance to fix it
![1](https://user-images.githubusercontent.com/2177532/82905884-ff93ab80-9f96-11ea-9a5d-73ba7bcb1bba.jpg)

**Comment by sum2012** [comment]
hmm,jpcsp: 1bb99afe bad ,16b84c97 good

**Comment by sum2012** [comment]
Test again,bad thing the screen is not update but logic is running (press start can play).
I cannot find the solution from jpcsp ....
