### ISSUE TITLE
Error: ppsspp_config.h: No such file or directory

### ISSUE THREAD

**Issue by Sunderland93** [hrydgard/ppsspp#9525]
Error compile PPSSPP 1.4 on Ubuntu 16.04 and Debian 8

`Scanning dependencies of target file
make[4]: Leaving directory '/home/sunderland93/Загрузки/ppsspp-1.4/ext/native/tools/build'
make[4]: Entering directory '/home/sunderland93/Загрузки/ppsspp-1.4/ext/native/tools/build'
[ 45%] Building CXX object file/CMakeFiles/file.dir/chunk_file.cpp.o
[ 47%] Building CXX object file/CMakeFiles/file.dir/zip_read.cpp.o
[ 49%] Building CXX object file/CMakeFiles/file.dir/file_util.cpp.o
/home/sunderland93/Загрузки/ppsspp-1.4/ext/native/file/file_util.cpp:1:27: fatal error: ppsspp_config.h: No such file or directory
compilation terminated.
file/CMakeFiles/file.dir/build.make:110: recipe for target 'file/CMakeFiles/file.dir/file_util.cpp.o' failed
make[4]: *** [file/CMakeFiles/file.dir/file_util.cpp.o] Error 1
`

**Comment by hrydgard** [comment]
How did you launch this build, did you use b.sh ?  This should work.

**Comment by Sunderland93** [comment]
No, I use Debian's rules-makefile:

`export DEB_LDFLAGS_MAINT_APPEND=-Wl,--as-needed

export QT_SELECT := qt5

ARCH=$(shell dpkg-architecture -qDEB_HOST_ARCH)

# See issue #7817
ifeq ($(ARCH),armhf)
COMPILER=QMAKE_CC=clang QMAKE_CXX=clang++
endif

%:
	dh $@ --buildsystem=qmake --sourcedirectory="Qt/" --parallel

override_dh_auto_configure:
	mkdir ext/native/tools/build
	cd ext/native/tools/build && \
		cmake ../ && \
		$(MAKE)
	./buildatlas.sh
	./build_ppgeatlas.sh
	dh_auto_configure -- $(COMPILER) PPSSPPQt.pro`

**Comment by Sunderland93** [comment]
No, I use Debian's rules-makefile (create deb-package):

```
export DEB_LDFLAGS_MAINT_APPEND=-Wl,--as-needed

export QT_SELECT := qt5

ARCH=$(shell dpkg-architecture -qDEB_HOST_ARCH)

ifeq ($(ARCH),armhf)
COMPILER=QMAKE_CC=clang QMAKE_CXX=clang++
endif

%:
	dh $@ --buildsystem=qmake --sourcedirectory="Qt/" --parallel

override_dh_auto_configure:
	mkdir ext/native/tools/build
	cd ext/native/tools/build && \
		cmake ../ && \
		$(MAKE)
	./buildatlas.sh
	./build_ppgeatlas.sh
	dh_auto_configure -- $(COMPILER) PPSSPPQt.pro
```

**Comment by hrydgard** [comment]
Well, the file is there so there's obviously some include path that needs fixing. Pull requests accepted.

Also there's no need to build the tools directory or the atlas, we include them prebuilt in git.

**Comment by Orphis** [comment]
That script is out of date as it is using QMake and we dropped support for it anyway.
Talk to the maintainer to have him update it.

**Comment by sergiobenrocha2** [comment]
@Sunderland93 where did you get the deb package?

I updated it: https://code.launchpad.net/~ppsspp/ppsspp/+git/debian

**Comment by Sunderland93** [comment]
@sergiobenrocha2  I just used scripts that I already had. I looked at the scripts in PPA and yes, they works fine. Thanks!
