### ISSUE TITLE
PPSSPP for iOS updates only change version.txt since 27th March,stuck in 1.3-1140

### ISSUE THREAD

**Issue by ijoinit** [hrydgard/ppsspp#9528]
i downloaded the latest 1.3-1160 dev working version from cydia,but it shows 1.3-1140 in the app 
![img_0351](https://cloud.githubusercontent.com/assets/26176492/24580207/c85b4736-1736-11e7-9ae3-002e27472544.PNG)

**Comment by ijoinit** [comment]
It's up to 1.4 now

**Comment by ijoinit** [comment]
Now,I'm thinking is that a jock for April first?i have been fooled?

**Comment by ijoinit** [comment]
I'm sorry,but I have to reopen this issue again,I download it from here http://build.ppsspp.org still the same thing,only version.txt updated,still show 1.3-1140 in app,and the disable alpha test is still there,something went wrong.

**Comment by ijoinit** [comment]
![img_0353](https://cloud.githubusercontent.com/assets/26176492/24584372/3b821a0c-179e-11e7-8c30-426e5b18ea51.JPG)

**Comment by angelXwind** [comment]
Should be fixed. Reinstall the latest version from Cydia and all should be fine.

![img_7533](https://cloud.githubusercontent.com/assets/1980487/24584806/230fc236-1748-11e7-8f96-f04aa5892bb2.PNG)

**Comment by ijoinit** [comment]
Thank you,and your repo,we love you!

**Comment by ijoinit** [comment]
We love you,I love you.
