### ISSUE TITLE
Reducing Gran Turismo texture popping???

### ISSUE THREAD

**Issue by ppsspp213** [hrydgard/ppsspp#9530]
Is their anyway to reduce the texture popping in Gran Turismo, I have mip mapping turned off but at varying distances it's still changing between two textures, one has the windows black tinted so you can't see through the glass then when camera gets closer to the car it pops in a clear glass texture so you can see through, the texture seems to also be of slightly higher resolution as the badges are less aliasied.
It's more noticable in the replays when camera is in reverse looking back towards the camera.

http://i.imgur.com/6Naw8sm.jpg
http://i.imgur.com/GMmErTM.jpg

**Comment by hrydgard** [comment]
The game is working correctly, it's just the game logic switching models by distance (LOD). On the PSP's low res screen, the sensible distance to switch models is too close for our high resolutions. Not much that can be done about it except for hacking the game unfortunately, there are some patches for this game in the forums ( http://forums.ppsspp.org/ ) but not sure if this issue has been tackled.

**Comment by ppsspp213** [comment]
Is their any difference between the video outputs at all?
screen vs video out when driving in the interior view I think I saw the screen shaking slightly or maybe my eyes are going goggly.
Is this disabled in video out?  https://www.gtplanet.net/why-gran-turismo-psp-looks-so-good/

**Comment by hrydgard** [comment]
Yup, and that just causes shaking at higher resolutions. There's a cheat in the forums to remove that antialiasing shake, can't find it right now though...

**Comment by ppsspp213** [comment]
I think I have v2.00 UCES-01245, UMDGen shows version v1.1, disc version v2.00 
ppsspp crashed just before loading the track and going in-game with this code
http://forums.ppsspp.org/showthread.php?tid=4799&pid=125138#pid125138
