### ISSUE TITLE
[Question] about D3D11

### ISSUE THREAD

**Issue by hanooty** [hrydgard/ppsspp#9534]
I download ppsspp v 1.4 android note_3 but i don't found D3D11 option please help me

**Comment by hanooty** [comment]
I mean, 
The option D3D11 is it available on android GPU or just windows? ????

**Comment by hrydgard** [comment]
Only on Windows, Android doesn't support D3D11.

Instead, Android supports Vulkan, but PPSSPP's vulkan support is not good enough yet. In the future it will be available on Android phones that support Vulkan.

**Comment by hanooty** [comment]
Thanks for your informations bro
