### ISSUE TITLE
A question about possibility to port ppsspp on Nintendo switch.

### ISSUE THREAD

**Issue by iOS4all** [hrydgard/ppsspp#9538]
Hi there. I know it's still early to ask this question but if the Nintendo switch get hacked is it possible to port ppsspp on it? Because it uses nivida X1 same on android TV.
Thanks.

**Comment by DarkLegend481** [comment]
NVidia X1 is the graphic card, right?

**Comment by hrydgard** [comment]
There's no point in speculating about this until we can execute code on it. If full code execution can be achieved, then yeah, of course a port is possible, but not likely to happen in the near future anyway.

No, X1 is the whole system-on-chip.

**Comment by iOS4all** [comment]
Oh thanks for clearing this to us.

**Comment by seanbperiod** [comment]
How about now? :D
