### ISSUE TITLE
Army of Two: The 40th Day ------> D3D11: Texts problem

### ISSUE THREAD

**Issue by roioros** [hrydgard/ppsspp#9539]
"Army of Two: The 40th Day" has a bug in the texts using D3D11 and the last version of PPSSPP (1.4), using OpenGL or D3D9 this error does not happen.

Examples:

**D3D9**

[![D3D9.jpg](https://s28.postimg.org/ei7awha6l/D3_D9.jpg)](https://postimg.org/image/8h9lzenk9/)

**D3D11**

[![D3D11.jpg](https://s11.postimg.org/wk81fl89v/D3_D11.jpg)](https://postimg.org/image/wk81fl89r/)

**Comment by unknownbrackets** [comment]
This may have been the Windows 7 bug that LunaMoo fixed recently.  Does it still happen in the latest git build?

-[Unknown]

**Comment by roioros** [comment]
Now the problem completely disappeared, thank you very much for the fix.
