### ISSUE TITLE
[Question] about controllers

### ISSUE THREAD

**Issue by hanooty** [hrydgard/ppsspp#9540]
PPSSPP on android is it support 2 controllers ( joy-stick) pad1 pad2????
Is it support it how can i do it..???
Because i have pes games and I'm always play by 1 controller  (pad1)

**Comment by unknownbrackets** [comment]
What are you wanting the second controller to do?  Remember that the physical PSP only had one set of buttons and a single analog stick.  PPSSPP isn't a package of game remakes that support split screen or two players on a single device or anything.

-[Unknown]

**Comment by hanooty** [comment]
Thanks  [UK]...
I'munderstanding you..
____
Ok, I've orher questions on frameskip..
When i set frame skip like
1,2 or 3
And i checked
AutoFrameSkip
I see flickering in screen 
How can i fix this????

**Comment by unknownbrackets** [comment]
That depends.  Do you have "Rendering Mode" set to "Skip buffer effects (non-buffered, faster)"?  That setting can cause flickering.  "Buffered rendering" is the best setting, but can be a little slower.

If that doesn't help, it is probably a bug in PPSSPP.  What game are you playing when it flickers?

-[Unknown]

**Comment by hanooty** [comment]
The flicker happened when i play  [PES 17]
in buffering rendering mode, 
Don't worry bro I will try to fix it by settings ...but how can i use 
[altrantive speed] option to be standard or alternative by volume+ key?????
