### ISSUE TITLE
[ASK] about "alternate speed" option

### ISSUE THREAD

**Issue by hanooty** [hrydgard/ppsspp#9543]
alternate speed is a very useful option but i don't know how can i use it..please tell me ho can i do it works with volume up+ key to be standard or alternative? ?????

**Comment by hanooty** [comment]
Someone help please

**Comment by hrydgard** [comment]
Just map it to that key in control settings? what's the problem?

**Comment by hanooty** [comment]
No bro, i mean alternative speed in settings 》》 frame rate control

**Comment by hanooty** [comment]
The problem is not working with me

**Comment by unknownbrackets** [comment]
Questions like this might be better asked on the forum or in a chat room about PSP gaming.  It's hard to understand what you're asking and what you're having a problem with in this context.

-[Unknown]
