### ISSUE TITLE
Unresponsive ui in some games starting with v1.3-433-g03b607f

### ISSUE THREAD

**Issue by LunaMoo** [hrydgard/ppsspp#9546]
Got a "weirdly behaving game"(WWE All Stars) from a friend to check and turns out some games might spam sceUmdReplaceProhibit and sceUmdReplacePermit many times per frame causing very heavy cpu usage and unresponsive ui starting from v1.3-433-g03b607f.:]

 No idea why it even calls those syscalls as it's a ps store copy and removing them all via cwcheat works for a workaround, but I don't think we should update ui on any syscall at all, that's "a bit" on the insane side;p.
 Why this is even required for that feature? In normally behaving games "Switch UMD" seems to be always available in the windows ui anyway even when game doesn't asks for it, why bother updating? Is it just to lock it down?

**Comment by unknownbrackets** [comment]
Is it calling it multiple times per frame, or is calling it once per frame enough to cause problems?

-[Unknown]

**Comment by LunaMoo** [comment]
Multiply times per frame, stopped counting after 10th call, might call it much more and it's running at 60fps. The game itself doesn't even slow down, ui just constantly flashes and lags behind any input, after few seconds it's hard to even close ppsspp without killing it from task manager.

**Comment by unknownbrackets** [comment]
We could just make it set a flag and then actually update the ui once per frame, maybe.  Except during stepping, but that updates ui anyway.

-[Unknown]

**Comment by LunaMoo** [comment]
Maybe it would be possible to check if it wants to change in same frame like running both permit and prohibit and just ignore such case completely. I know people are fast, but nobody is fast enough to switch umd x times per frame so actual feature requiring it shouldn't call both syscalls in same frame.

**Comment by unknownbrackets** [comment]
Right - ideally we'd have consistent behavior on Android, Windows, etc.  The flag only matters at the end of a frame on Android, and the option can only be selected if enabled.  No need to update Windows UI more often than that, really.

-[Unknown]

**Comment by hrydgard** [comment]
Changed it to update the enabled/disabled state of Windows menu items on dropdown. This way we can completely avoid calling UpdateUI here. Doesn't seem like other platforms make any use of UpdateUI.

**Comment by LunaMoo** [comment]
Yup, that works great, don't have much to test that either, but in that spammy game I set some breakpoints and the option does indeed update after opening the menu without any problems.
