### ISSUE TITLE
cmake says 'Could NOT find PNG' - Ubuntu 14.04

### ISSUE THREAD

**Issue by rcampbel3** [hrydgard/ppsspp#9547]
This is non-critical because the resultant binary *SEEMS* to play just fine, but when I run cmake from latest source on Ubuntu 14.04 machine, I get the following message:
[...]
-- Could NOT find PNG (missing:  PNG_LIBRARY PNG_PNG_INCLUDE_DIR)
[...]

I have the system libpng libraries and the development bits installed in the default locations, so I'm guessing that something in the cmake detection for libpng isn't quite right for Linux

On Ubuntu 14.04 png.h is here:
/usr/include/libpng12/png.h
and libpng.so is here:
/usr/lib/x86_64-linux-gnu/libpng.so

also, if it's helpful, the binary that gets built doesn't show a link against libpng.so at all. Output of 'ldd /usr/local/bin/PPSSPPSDL |grep png' is null.

**Comment by Orphis** [comment]
We're using a much newer version of libpng that isn't available on your system.
This just shows we didn't find it on the system, so we fall back to the bundled version and link it statically.
Any such message isn't an error, it's just regular feature detection.
