### ISSUE TITLE
UWP not moving cursor and wrong screen ON XB1

### ISSUE THREAD

**Issue by metalex10** [hrydgard/ppsspp#9555]
Hi compile the uwp version in xbox one and what i see is that the cursor does not work and also the screen looks very big

Can make an exception to emulate the mouse with the jostick and put the emulator in a resolution of 1920x1080?

**Comment by metalex10** [comment]
https://docs.microsoft.com/en-us/uwp/api/Windows.Gaming.Input.Gamepad

**Comment by metalex10** [comment]
UWP requires the use of Windows.Gaming.Input (or the XINPUT translation library xinput_uap.lib), and does not support DirectInput.

**Comment by metalex10** [comment]
https://docs.microsoft.com/en-us/windows/uwp/input-and-devices/designing-for-tv#mouse-mode

**Comment by metalex10** [comment]
https://docs.microsoft.com/en-us/uwp/api/Windows.Gaming.Input

**Comment by hrydgard** [comment]
Ah yes. How many input APIs are MS going to invent....

**Comment by DarkLegend481** [comment]
@hrydgard Can you release a .appx/.appxbundle? I can use for test on my Xbox One (Interop Tools).

**Comment by DarkLegend481** [comment]
Or a .zip w/ appxmanifest.xml...

**Comment by DarkLegend481** [comment]
Just for test

**Comment by metalex10** [comment]
@hrydgard check this screenshot
![screenshot_2017-04-05_11-18-20](https://cloud.githubusercontent.com/assets/3173507/24720469/db414142-1a02-11e7-90fd-2b7165232bd2.png)

**Comment by metalex10** [comment]
this pic is after of you fix code but not center screen?

**Comment by hrydgard** [comment]
Quite surprising that it's not filling the screen, no idea why...

**Comment by unknownbrackets** [comment]
Not because of this?

https://github.com/hrydgard/ppsspp/blob/f5e5614645188dae54f3a8118bb3e7ed3efc5ecd/Windows/GPU/D3D11Context.cpp#L90

-[Unknown]

**Comment by metalex10** [comment]
yes ,it is

but various games is slow as hell?!

**Comment by metalex10** [comment]
https://github.com/metalex10/ppsspp/commit/dee160f52ac26cfb0532fdac9fbec29f9ea53a03 fix for xbox one experimental

**Comment by hrydgard** [comment]
@unknownbrackets D3D11Context is not used on UWP, instead we use the D3D context code from UWP samples (just to be sure it's right with resizing and all that stuff).

**Comment by hrydgard** [comment]
@metalex10  Am I right that the joystick navigation issue is fixed, and only the resolution problem remains here?

**Comment by metalex10** [comment]
yes only problem is a resolution 

the problem is a resolution with position x,y on screen

**Comment by metalex10** [comment]
I found fix for this problem

**Comment by unknownbrackets** [comment]
Can you post the fix?  Is this resolved now?

-[Unknown]

**Comment by hrydgard** [comment]
This should be OK now, I think - people report that XB1 work mostly okay, especially after the back button fix.
