### ISSUE TITLE
Shapo NPUZ00111 graphic glitches d3d11

### ISSUE THREAD

**Issue by benderscruffy** [hrydgard/ppsspp#9556]
ppsspp-v1.4-37-ge99f1c0
using d3d11 lines trhoughout the screen
![npuz00111_00000](https://cloud.githubusercontent.com/assets/2696404/24685209/9811c2b2-19de-11e7-9d4c-90119a757ada.jpg)

using ogl screen is correct
![npuz00111_00001](https://cloud.githubusercontent.com/assets/2696404/24685218/ac4b8ace-19de-11e7-9b0e-74468f158e29.jpg)

**Comment by unknownbrackets** [comment]
Could you try exporting a GE debugger dump on PC?

To do this, open the game and select Debug -> GE debugger..., then when it's displaying the scene, press Record in the top right.  After a second or so, it'll finish and save a trace of the drawing activity.

After that, check the memstick/PSP/SYSTEM/DUMP folder and it'll have created a file named something like "ULES12345_0000.ppdmp".  You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by benderscruffy** [comment]
this has been fixed

**Comment by unknownbrackets** [comment]
Cool, probably color testing.

-[Unknown]
