### ISSUE TITLE
HELP ME (MULTIPLAYER VIA HOTSPOT ANDROID)

### ISSUE THREAD

**Issue by Endarko** [hrydgard/ppsspp#9562]
please help me. I've set up a network of ppsspp is correct as in the forums ppsspp to play together with friends through hotspot android . but why is it always not connected ppssppnya. I have tried in the game super bike 8 and 9, pes 2014 . in the ppsspp version is the latest build

**Comment by unknownbrackets** [comment]
The forum is probably the best place for questions and troubleshooting like this.

This list is meant to track issues.

-[Unknown]
