### ISSUE TITLE
Can no longer start game from commandline

### ISSUE THREAD

**Issue by mac1202** [hrydgard/ppsspp#9564]
Hi just complied the latest git version and I can no longer directly start a game from commandline. In previous version 'ppsspp /path/to/game/game.cso' directly start the game now it only open the ppsspp main menu.

**Comment by jbeich** [comment]
Works fine here using either `PPSSPPSDL` or `PPSSPPQt`. Do you mean downstream builds? For example, ArchLinux recently [introduced](https://git.archlinux.org/svntogit/community.git/commit/?h=packages/ppsspp&id=54c64014aa62) wrapper scripts but doesn't propagate `$@`.

**Comment by unknownbrackets** [comment]
In that case you'll need to file a downstream bug with Arch.  It doesn't seem like this changed in PPSSPP.

-[Unknown]

**Comment by mac1202** [comment]
Thanks  jbeich for putting me in the right direction, contacted the guy at retroarch and now it's fixed.
