### ISSUE TITLE
Colin 2005+

### ISSUE THREAD

**Issue by Michal1324** [hrydgard/ppsspp#9571]
Game errors out with unable to access disc but it clearly can

**Comment by sum2012** [comment]
Does the full game name is "Colin McRae Rally 2005" ?

**Comment by Michal1324** [comment]
its "Colin McRae Rally 2005+"

**Comment by sum2012** [comment]
I test in-game no problem
![1](https://cloud.githubusercontent.com/assets/2177532/24829481/22f78010-1ca5-11e7-9c98-72ca987a3b60.jpg)

**Comment by Michal1324** [comment]
Then its probably corrupt or something not working on android

**Comment by sum2012** [comment]
I try android build also ok.
Try update your ppsspp in http://buildbot.orphis.net/ppsspp/
![screenshot_20170408-215828](https://cloud.githubusercontent.com/assets/2177532/24829555/9c833810-1ca6-11e7-8cbd-2904d52a6e62.jpg)

**Comment by sum2012** [comment]
Note to myself "This game : Unimplemented HLE function sceUtilitySetSystemParamInt"

**Comment by Michal1324** [comment]
Ok I've found the issue it was corrupted rom

Please Close and Thanks for help
