### ISSUE TITLE
Not changeable PSP save directory (Android)

### ISSUE THREAD

**Issue by TehPlayer14** [hrydgard/ppsspp#9573]
Since my phone has low built in free storage space could anyone implement saving on external sd card?

**Comment by sum2012** [comment]
Hmm,the keyword is g_Config.externalDirectory

**Comment by ThePhoenixRises** [comment]
Or better still upload to a Dropbox account, so we can save our internal memory being used up, as my Nexus 7 tablet has no SD card slot, so use Dropbox for game saves.
Everybody gets a 2.5 gig free account on Android, not sure about other devices.

**Comment by sum2012** [comment]
https://github.com/hrydgard/ppsspp/blob/master/UI/NativeApp.cpp#L341
The code is already point to external_dir .
Not sure what's problem

**Comment by unknownbrackets** [comment]
In most cases, PSP game saves are very small:

https://www.gamespot.com/forums/playstation-nation-1000002/about-how-big-are-psp-game-saves-25640893/

What saves are you seeing take a lot of space?  If the game has an install feature, I'd recommend not using it.  In most cases, this was just for improved performance, and doesn't make any difference with PPSSPP.

-[Unknown]

**Comment by Michal1324** [comment]
My device has small internal space that's why I requested that + dlc of a game

**Comment by Hydroque** [comment]
I think it would be okay to note that in issue #1019 that was actually a future goal. So I don't think the ability to do so should be overlooked.
