### ISSUE TITLE
UWP don't compile on ARM

### ISSUE THREAD

**Issue by DarkLegend481** [hrydgard/ppsspp#9575]
What I do?

**Comment by hrydgard** [comment]
If something doesn't compile, the obvious thing to do is to at least post the error message you get in the issue you create. Come on.

**Comment by DarkLegend481** [comment]
When I put compile, several files say:
No such file or directory

**Comment by hrydgard** [comment]
Come on, just paste the error message. Can't diagnose from just a comment like that.

I just built it for ARM and it built fine.

You didn't forget

    git submodule update --init --recursive

after checking out, did you?

**Comment by DarkLegend481** [comment]
My mother it's using my PC now...

I just downloaded it and tried compile it...

**Comment by DarkLegend481** [comment]
I will close this for now... If this happens again, I reopen it.

**Comment by DarkLegend481** [comment]
So @hrydgard, how I compile it correctly?

**Comment by hrydgard** [comment]
You open the UWP project, select ARM in the architecture dropdown, then in the dropdown next to the architecture dropdown select Device, connect your device by USB and press F5. That should build and run under the debugger. If that doesn't work, please, please paste the errors you get here. I can't see what's going wrong for you from here.

**Comment by DarkLegend481** [comment]
![sem titulo](https://cloud.githubusercontent.com/assets/22161127/25046184/7fd3f128-2106-11e7-98ce-96c114bfbedd.png)

**Comment by DarkLegend481** [comment]
I downloaded the máster branch and all the submodules, put them on their specified folder and this still not working!

**Comment by DarkLegend481** [comment]
@hrydgard what I do now?

**Comment by hrydgard** [comment]
The errors above are a sure sign that you didn't, in fact, download the submodules properly, it's done like this:

    git submodule update --init --recursive

That will do all the work for you.

Then try again.

**Comment by DarkLegend481** [comment]
For now, closing it again

**Comment by Toff-kun** [comment]
Sorry for the possible noobish question, but how do I fix the following errors that prevent me from compiling a UWP version?

![sshot-472](https://user-images.githubusercontent.com/10385850/31393777-2fe89c9c-ade5-11e7-9df8-5929f2d74d76.png)

**Comment by hrydgard** [comment]
It's just fallen behind, I'll fix it up. We currently don't have any continouos build of the UWP stuff so won't notice when it breaks.

**Comment by Toff-kun** [comment]
Thank you, managed to compile successfully now.
Btw, is Dynarec (JIT) currently broken for UWP ARM and if so, is fixing it still on the roadmap?

**Comment by hrydgard** [comment]
It's broken due to a bug in Windows 10 for ARM (the FlushInstructionCache function is missing from the list of UWP-approved functions, and it's really required. See https://msdn.microsoft.com/en-us/library/windows/desktop/ms679350(v=vs.85).aspx - it's desktop-only). If MS fixes that in an update, we can trivially fix it.

**Comment by Toff-kun** [comment]
Getting compiling errors again.

First it said that 'bSeparateCPUThread' is not a member of 'Config'.
I added the line `bool bSeparateCPUThread;` to \Core\Config.h.
This fixed the above error, but gave me 3 new ones:

![image](https://user-images.githubusercontent.com/10385850/33702174-2dc8b3fc-db2b-11e7-821d-80c2372d0339.png)

I did run `git submodule update --init --recursive`, didn't help.
