### ISSUE TITLE
Kurohyou Ryu Ga Gotoku Shinshou (Yakuza) - No clipping of 3d characters behind backgrounds based on depth within screen.

### ISSUE THREAD

**Issue by SausageDog** [hrydgard/ppsspp#9576]
Kurohyo uses 2d backdrops with 3d characters rendered on top of them. PPSSPP does not clip the 3d model when they are "behind" objects in the 2d background. Tested on PPSSPP 1.4 but has not worked on previous versions of the emulator either.

The attached screenshot shows the character floating in space in front of some cupboards instead of being hidden behind them.

![npjh50333_00000](https://cloud.githubusercontent.com/assets/3155859/24834171/1442bfae-1d21-11e7-9a7a-8ffbf5e557d5.jpg)

**Comment by unknownbrackets** [comment]
Does this work on any backend (such as Vulkan)?  Is it the same broken on all 4 backends?

Also - if you try the software renderer (it will be slow), does it render properly there?

Is there a way to get this to happen in the demo?

-[Unknown]

**Comment by SausageDog** [comment]
All backends render incorrectly, including OpenGL, D3D9, D3D11, and Vulkan.

I tried the software renderer with the OpenGL backend, and it renders correctly with the characters correctly obscured by the foreground geometry in the scene.

I don't have a copy of the demo for this game so I can't say if it works in that or not.

![npjh50333_00000](https://user-images.githubusercontent.com/3155859/34371604-bbee9b36-eb22-11e7-8972-9480c644dfe9.jpg)

**Comment by unknownbrackets** [comment]
Interesting.  I wonder if this game is downloading depth - I seem to recall it was doing that in other places for effects at the start of fights (we currently don't render those effects properly.)

-[Unknown]

**Comment by hrydgard** [comment]
Since the background is prerendered, it seems more likely that it's *up*loading a depth buffer, similar to how Star Ocean uploads a stencil buffer. We don't currently initialize depth buffers with contents of the VRAM where they are created, and we don't detect block transfers to them. Maybe the latter would catch this, that would be convenient.

**Comment by unknownbrackets** [comment]
Is there an easy way to upload depth?  I guess it ought to be doable on Vulkan...

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, you can output depth from a fragment shader, like we do with our pixel depth rounding hack. So you just need to upload the depth as a texture (depth or single-channel color, whatever) and draw a single quad writing the sampled texture to gl_Depth or whatever the output is called.

**Comment by JimsAlliance** [comment]
This issue persists in the latest version of PPSSPP - ppsspp-v1.8.0-585.

**Comment by dante3732** [comment]
Still not fixed.

**Comment by hrydgard** [comment]
I am very aware I have not done the work to fix this yet.

**Comment by Gamemulatorer** [comment]
Is this pr https://github.com/hrydgard/ppsspp/pull/14833 could possibly help this issue?

**Comment by unknownbrackets** [comment]
Very doubtful.  This is probably uploading depth as noted above, which isn't implemented yet in any backend.

-[Unknown]

**Comment by dante3732** [comment]
> Is this pr #14833 could possibly help this issue?

I tested it and it doesn't fix the problem. Don't need to enable any options, right?

**Comment by hrydgard** [comment]
Just like unknownbrackets says, it's an unrelated problem, which will need some major work to fix. It's not possible to get it to work right now.

**Comment by dante3732** [comment]
Still not fixed.

**Comment by hrydgard** [comment]
Fix coming up: https://github.com/hrydgard/ppsspp/pull/15772

**Comment by Gamemulatorer** [comment]
> Fix coming up, needs testing: #15772

How?

**Comment by dante3732** [comment]
It seems that after the cutscenes everything breaks down.
![NPJH50333_00026](https://user-images.githubusercontent.com/66036249/182336462-8159e81b-b6d6-415c-97e0-dd404a400ab7.jpg)

**Comment by dante3732** [comment]
I make savestate.
https://drive.google.com/file/d/15mIcJfkLprfMSZBSL1Zub378Ena9tKRK/view?usp=sharing

**Comment by hrydgard** [comment]
Ok, I'll take a look. Thanks so much for your helpful testing!

**Comment by dante3732** [comment]
This did not happen after every video. This time, there was a video first, then a 3d battle, then videos, and then a transition to a city with a 2d background.

If you go to the pause menu and back, the masks will flash if you stand behind them.

If you do a quick save when an error occurs and then upload, then Depth/Z will work fine.

**Comment by hrydgard** [comment]
Seems to be reading data from a directory in SAVEDATA that doesn't exist for me: 

80010002=sceIoOpen(ms0:/PSP/SAVEDATA/NPJH50333DAT/DATA08.DNS, 1073758209, 8612): file not found

Could you zip up your NPJH50333DAT directory?

**Comment by dante3732** [comment]
> Seems to be reading data from a directory in SAVEDATA that doesn't exist for me:
> 
> 80010002=sceIoOpen(ms0:/PSP/SAVEDATA/NPJH50333DAT/DATA08.DNS, 1073758209, 8612): file not found
> 
> Could you zip up your NPJH50333DAT directory?

https://drive.google.com/file/d/1I7XDGbbWD5v-ZLGw0GQNgX_-pBsWJT2l/view?usp=sharing

**Comment by dante3732** [comment]
Such a bug happens randomly after FMV videos, not after each one.

**Comment by hrydgard** [comment]
I changed how the fix works recently, are there still issues after FMV videos?

**Comment by dante3732** [comment]
> I changed how the fix works recently, are there still issues after FMV videos?

It flickering.
https://drive.google.com/file/d/1pgvRL1IsrQ24dM3Zk8Jomkdi-raX6VVL/view?usp=sharing

**Comment by hrydgard** [comment]
OK, thanks for testing. Can't close this yet then

**Comment by Gamemulatorer** [comment]
Here's the ge dump
[NPJH50333.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/9425458/NPJH50333.ppdmp.zip)

**Comment by Gamemulatorer** [comment]
> > I changed how the fix works recently, are there still issues after FMV videos?
> 
> It flickering. https://drive.google.com/file/d/1pgvRL1IsrQ24dM3Zk8Jomkdi-raX6VVL/view?usp=sharing

I think the flickering is a fmpeg issue and should be separated to this?

**Comment by hrydgard** [comment]
Well the flickering shown in dante's video doesn't look like an ffmpeg issue.

**Comment by lim2222** [comment]
I think this is the flickering issue talk about here
[Screenrecorder-2022-08-25-22-33-53-652.zip](https://github.com/hrydgard/ppsspp/files/9425682/Screenrecorder-2022-08-25-22-33-53-652.zip)

save state
[PPSSPP_STATE.zip](https://github.com/hrydgard/ppsspp/files/9425721/PPSSPP_STATE.zip)

ge dump
[NPJH50333.zip](https://github.com/hrydgard/ppsspp/files/9425762/NPJH50333.zip)

**Comment by Gamemulatorer** [comment]
Its not really flickering on my phone but have a graphics glitch after finishing the cutscene 

https://user-images.githubusercontent.com/37603562/186698109-8bc816a4-9b8e-44ba-ba72-d29140ab3be9.mp4

**Comment by hrydgard** [comment]
@Gamemulatorer is the glitch still happening?

**Comment by Gamemulatorer** [comment]
> @Gamemulatorer is the glitch still happening?

Not anymore using the latest build.

https://user-images.githubusercontent.com/37603562/190608361-f5f36b87-a824-445c-994b-809379580b12.mp4

**Comment by hrydgard** [comment]
Hm, in your video, still looks like a little flicker left of the square button?

**Comment by Gamemulatorer** [comment]
It's from my screen recorder

**Comment by dante3732** [comment]
> @Gamemulatorer is the glitch still happening?

It is still flickering, there is a person on the right, in front of whom there is an object and flickering is visible there. 
You need to stand behind a bicycle, for example, and the flicker will be visible.

**Comment by dante3732** [comment]
> > @Gamemulatorer is the glitch still happening?
> 
> Not anymore using the latest build.
Then what happened in this place?
![32323](https://user-images.githubusercontent.com/66036249/190621219-952279db-0667-442c-b33e-db0d6d703e49.png)

**Comment by Gamemulatorer** [comment]
I'm only focusing on this glitch.
![Screenshot_2022-09-16-19-35-39-74](https://user-images.githubusercontent.com/37603562/190630269-88e119f4-6071-428e-93ff-853de6f955b8.png)

**Comment by hrydgard** [comment]
Ah, okay. Good that that one is gone, then.

The little flickers... Dunno. Strange :/

Anyway, gonna consider this good enough for 1.4, moving further work to the next version. Maybe the tiny glitch will be fixed by something else.

**Comment by hrydgard** [comment]
This broke again in #16150 . 

GE dump: 
[Kurohyou depth problem NPJH50333_0001.zip](https://github.com/hrydgard/ppsspp/files/9709754/Kurohyou.depth.problem.NPJH50333_0001.zip)

Probably due to the trick it does where it reads a 565 buffer as depth, and we use some bits in the address to detect that, and those are normalized-away somewhere. I'll look into it.

**Comment by hrydgard** [comment]
Fixed, my bad.

**Comment by hrydgard** [comment]
I think we can probably close this now, and deal with any remaining bugs or artifacts separately, such as in https://github.com/hrydgard/ppsspp/issues/15956 .
