### ISSUE TITLE
Qt build does not use /usr/share/ppsspp for assets folder

### ISSUE THREAD

**Issue by handrake0724** [hrydgard/ppsspp#9578]
It looks like assets folder in /usr/share/ppsspp is not recognize by ppsspp in linux.
I just modified UI/NativeApp.cpp as follows but it is workaround for my case.

	// We want this to be FIRST.
#ifdef USING_QT_UI
	**VFSRegister("", new DirectoryAssetReader("/usr/share/ppsspp/assets/"));**
	VFSRegister("", new AssetsAssetReader());
#elif defined(IOS)
	// Packed assets are included in app
	VFSRegister("", new DirectoryAssetReader(external_dir));
#endif

**Comment by jbeich** [comment]
In **v1.4** Qt switched to CMake build (shared with SDL) turning `AssetsAssetReader()` into nop as assets are no longer bundled into the executable. Maybe you're confused by [harmless](https://github.com/hrydgard/ppsspp/blob/d7038860f1ba/UI/NativeApp.cpp#L327) warnings like
```
W: file_util.cpp:163: IsDirectory: stat failed on /usr/bin/assets/flash0/font/jpn0.pgf
W: file_util.cpp:163: IsDirectory: stat failed on /usr/bin/flash0/font/jpn0.pgf
W: file_util.cpp:163: IsDirectory: stat failed on /usr/bin/assets/flash0/font/jpn0.pgf
W: file_util.cpp:163: IsDirectory: stat failed on /usr/bin/flash0/font/jpn0.pgf
```
When PPSSPP* can't really find assets it crashes after
```
E: TextureUtil.cpp:143: Failed to read file ui_atlas.zim
26:01:243 Common/MsgHandler.cpp:57 E[SYSTEM]: Warning: Failed to load ui_atlas.zim.

Place it in the directory "assets" under your PPSSPP directory.
Failed to load ui_atlas.zim.

Place it in the directory "assets" under your PPSSPP directory.
E: NativeApp.cpp:594: Failed to load ui_atlas.zim
```

**Comment by handrake0724** [comment]
@jbeich I realized the repository I have is out-dated and updated the repository to latest.
Now it works. Thanks.
