### ISSUE TITLE
Quality of Life improvement ideas

### ISSUE THREAD

**Issue by Anuskuss** [hrydgard/ppsspp#9586]
Here are some QoL improvements I'd like to see in **PPSSPP**:

- [ ] When pausing a game with a user defined button, that button should also allow the user to leave the pause menu. The correct behaviour only happens when that button is mapped to `ESCAPE`.
- [ ] While holding the analog stick, IMO it shouldn't trigger other buttons when you drag too far. For that matter, once a finger (touch input) is on the display, it should only trigger the first interacted button.
- [x] **Low priority** Would it make sense to hook up hardware buttons on smartphones (like `VOLUME-UP` or `VOLUME-DOWN`)? That way you could map them e.g. for *Save state* or *Load state*.
- [ ] **Low priority** Similar to above, it would be neat to hide the volume hud on iOS since it is really intrusive and blockes half the screen for a good amount of time. Maybe one could go one step further and implement a custom volume animation?
- [ ] A photo picker for smartphones when choosing a custom background image (#9501)
- [ ] When creating custom settings, it saves all settings for that game (so when a user changes something for all games, I wouldn't apply to the custom settings game). I would rather see something like *patches*, where you could change everything but when one game needs something (like control changes or a hack) it would overwrite that on top of the global settings.
- [ ] (Option to) Automatically show/hide touch controls when a controller is detected (for smartphones)
- [ ] And the dead issues already submitted #8861 (bind all controls) #9302 (undo load/save state)

**Comment by hrydgard** [comment]
Checked off one that's already done.

**Comment by unknownbrackets** [comment]
Aren't these already separate issues?  Is there benefit to a separate wishlist issue?

-[Unknown]

**Comment by Anuskuss** [comment]
@unknownbrackets These are just the things I'm proposing. If something gets resolved I'll of course check it myself so you don't have to do the extra work :relaxed:

**Comment by unknownbrackets** [comment]
Well, maybe a few people want background images, but don't care so much about iOS.  And maybe there are other people who are uninterested in backgrounds, but would really like that iOS volume thing fixed.

Should each github user create their own github issue, tracking checkboxes of all the issues they find important to them?  We could label the 683 currently open issues each as "Issue" and then have the 700 or so lists of issues as "Wishlist".

To me it seems rather like having the loaf of bread you need to purchase at the market on your groceries list multiple times.

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, @unknownbrackets is right, this should be a bunch of separate issues.

**Comment by Anuskuss** [comment]
@unknownbrackets @hrydgard I didn't want to spam the issue tracker with so many issues all at once, but if it helps you keep track of everything I'll obviously make seperated issues.
