### ISSUE TITLE
Text won't appear 

### ISSUE THREAD

**Issue by ob1996** [hrydgard/ppsspp#9589]
Hello, I'm new here and new to ppsspp. I downloaded yu gi oh 5ds tag force 4 and the text won't appear at all. How do I fix this problem? The same things happened with tag force 3. Thank you in advance. 
Ps: I'm using the emulator on PC. 
![no text](https://cloud.githubusercontent.com/assets/27214425/24863168/fee70fcc-1dff-11e7-9f6e-4f377a621708.PNG)

**Comment by unknownbrackets** [comment]
Guessing this is #2788.  If you pill your fonts from a real PSP, it may work.

-[Unknown]

**Comment by ob1996** [comment]
So what should I do exactly?

**Comment by benderscruffy** [comment]
google "PSARDumper"

**Comment by hrydgard** [comment]
Actually if you have modern custom firmware on your PSP it's way easier to get the fonts that way. Just press SELECT , then use the menu to mount flash0: on USB, then go into USB mode, connect to your PC and just copy the files out.

**Comment by sum2012** [comment]
I test no problem
![1](https://cloud.githubusercontent.com/assets/2177532/24908607/2dd34d3e-1ef3-11e7-928f-4e19da20ec55.jpg)

Can you update your ppsspp in http://buildbot.orphis.net/ppsspp/

**Comment by ob1996** [comment]
Thanks a lot everybody. I downloaded the latest ppsspp version for the PC and it seems to working fine with tag force 4 though tag force 3 seems to have the same problem. You are all amazing :)

**Comment by ob1996** [comment]
Nevermind, it's working properly now. Thanks everybody
