### ISSUE TITLE
Naruto Shippuden Ultimate Ninja Heroes 3 : Black screen after title logo - Since 1.3-37-g8b5693b

### ISSUE THREAD

**Issue by Saramagrean** [hrydgard/ppsspp#9591]
On: Windows 10 64 bit & Android 7.1.1 ARM

Last work: 1.3-31-gb3a7c0e
First break: 1.3-37-g8b5693b
I try test on latest build agian (1.4-70) but not work fine.

Here log: https://drive.google.com/file/d/0B4Y2FBdaxHTDYTRoQ2Z2LWJpVGM/view?usp=drivesdk

**Comment by unknownbrackets** [comment]
Most likely #9014, but I'm not sure what's happening.  From the log, it looks like it's not happy that sceMpegGetAtracAu is returning 80618001, possibly it's doing so a frame too early or something.

-[Unknown]

**Comment by jack00** [comment]
Cheat code that works with version newer than 1.3-31

_S ULUS-10518
_G Naruto Shippuden Ultimate Ninja Heroes 3 (US)
_C1 skip intro movie
_L 0xE0010003 0x000C8450
_L 0x100C8450 0x0000000D

_S ULES-01407
_G Naruto Shippuden Ultimate Ninja Heroes 3 (EU)
_C1 skip intro movie
_L 0xE0010003 0x000C84EC
_L 0x100C84EC 0x0000000D

**Comment by deikatsuo** [comment]
@jack00 thanks

**Comment by D3shly** [comment]
Does anyone know how to import these cheat codes into iOS ppsspp?

**Comment by D3shly** [comment]
Can anyone reply to my previous comment?

**Comment by Saramagrean** [comment]
Do you have PC? Try import cheat code from cheat database file (cheat.db), I added this cheat code complete.

https://drive.google.com/file/d/1dYfCEUU5G2CODFOpBNUYAqo6RfN4Glr9/view?usp=drivesdk

Extract file and put in folder PSP > Cheats.

How to use info (on iOS, maybe similarly Android/PC).
https://forums.ppsspp.org/showthread.php?tid=3590

//Sorry for my horrible english. 😂

**Comment by D3shly** [comment]
Thank you so much for replying, but I’m very bad at dealing with these sorts of things so could you kindly give me a step for step guide on how to fix this? I do have a PC but I want to play the game on my iPhone. Thank you, have a good day.

**Comment by D3shly** [comment]
Can you reply as soon as possible because I’m really short on time. Thanks!

**Comment by Saramagrean** [comment]
Sorry, i don't have iOS device but i record clip on my phone (Android) step by step, how to use for Cheat database.
https://youtu.be/AFBmxe1G3fg

Hope this helps a little bit. :)

**Comment by GoldenPvE** [comment]
So what about mac os el captian?

**Comment by hrydgard** [comment]
This is now fixed.

**Comment by Saramagrean** [comment]
😀👍
