### ISSUE TITLE
Held touch buttons shouldn't trigger other buttons

### ISSUE THREAD

**Issue by Anuskuss** [hrydgard/ppsspp#9593]
While holding the analog stick, IMO it shouldn't trigger other buttons when you drag too far. For that matter, once a finger (touch input) is on the display, it should only trigger the first interacted button.

**Comment by unknownbrackets** [comment]
Just to note, I prefer almost entirely the opposite.  I mash X and slide my finger over to O quite often.

That said, for the analog stick specifically I think it may make sense.  Have never intentionally moved off it onto a button.

-[Unknown]

**Comment by ResurrectionRedmi9** [comment]
This probably fixed by https://github.com/hrydgard/ppsspp/pull/14843?
