### ISSUE TITLE
Automatically show/hide touch controls

### ISSUE THREAD

**Issue by Anuskuss** [hrydgard/ppsspp#9597]
(Option to) Automatically show/hide touch controls when a controller is detected (for smartphones).

**Comment by hrydgard** [comment]
I'm not sure if this is necessary - we already have an option to fade out the controllers if the screen is not touched for a while - which it presumably won't be if you're using a controller to play.

**Comment by Anuskuss** [comment]
@hrydgard Yeah I think that solution is the best of both worlds. The wish list is getting smaller :relaxed:
