### ISSUE TITLE
Growlanser - Wayfarer of Time ULUS10593 text problem 

### ISSUE THREAD

**Issue by benderscruffy** [hrydgard/ppsspp#9598]
v1.4-72-g56c3753 	
using my own fonts that i dumped aswell
the text through out the game is messed up
happens in both d3d11 and ogl
![ulus10593_00000](https://cloud.githubusercontent.com/assets/2696404/24889422/6844427c-1e9c-11e7-9c64-f4ac8548c8fd.jpg)
![ulus10593_00002](https://cloud.githubusercontent.com/assets/2696404/24889440/7bb05fe4-1e9c-11e7-990a-a5d0a6eded79.jpg)

**Comment by unknownbrackets** [comment]
You've put the fonts in memstick/PSP/flash0/font/, correct?  If you put them somewhere else, they won't work.

Recently some paths related to fonts were changed, so you might've had them somewhere where it seemed to work.  The correct place is under PSP/.

-[Unknown]

**Comment by benderscruffy** [comment]
yes memstick/PSP/flash0/font/ that is where i have put them

**Comment by deadair3210** [comment]
It doesn't look like its grabbing the wrong glyph due to the font being wrong, as it seems to be just replacing random characters with y

**Comment by unknownbrackets** [comment]
I can't even get in game - bisected it down to e9d5eb6, the fix for #7887.

-[Unknown]

**Comment by deadair3210** [comment]
Just got into game, at least as far as in game dialog with someone

ppsspp-v1.4-72-g56c3753-windows-amd64


![14714](https://cloud.githubusercontent.com/assets/1053504/24891736/593d8004-1e3d-11e7-80b6-6e597c968922.PNG)

**Comment by unknownbrackets** [comment]
Yes, I can verify that's what the correct fonts look like - the first screenshot is of the wrong fonts.

For me, right after the logos and loading message, it displays an intro video.  Pressing O to skip it causes a crash (note that I have ignore invalid memory access off - fast memory should crash.)  Using ULUS10593_1.00.

-[Unknown]

**Comment by benderscruffy** [comment]
@deadair3210
keep going further when they are in the camp site and the text is really messed up

**Comment by unknownbrackets** [comment]
Just to make it clearer, here's a comparison of the wrong fonts with the right fonts:

![growlanser-fonts](https://cloud.githubusercontent.com/assets/191233/24892214/acf9367e-1e2f-11e7-9273-cc51e0c0f719.gif)

It definitely looks like you have the wrong fonts.  Maybe double check PSP/flash0/font/ltn0.pgf and the like?

PPSSPP used to (but no longer does) look in flash0/fonts/ where the executable is.

-[Unknown]

**Comment by benderscruffy** [comment]
ok just redumped my fonts
ok the first part was ok but the next part in the camp still has a problem 
![ulus10593_00002](https://cloud.githubusercontent.com/assets/2696404/24892689/17cd0d6e-1eb1-11e7-9712-2ae9cf5e0d0e.jpg)
![ulus10593_00003](https://cloud.githubusercontent.com/assets/2696404/24892697/1f6ceca6-1eb1-11e7-9900-afdffcac1954.jpg)
can someone check as well

**Comment by benderscruffy** [comment]
ok there was a problem with my first redump of the fonts i think 
i have redumped them again and no problem this time
closed
