### ISSUE TITLE
Samurai Warriors - State of War ULUS10089 d3d11 problem

### ISSUE THREAD

**Issue by benderscruffy** [hrydgard/ppsspp#9599]
v1.4-72-g56c3753 	
using d3d11 there is black flashing boxes during the devlopers screens and intro

![ulus10089_00000](https://cloud.githubusercontent.com/assets/2696404/24889634/aaa96c54-1e9d-11e7-97ac-3dfe8d60d174.jpg)
![ulus10089_00001](https://cloud.githubusercontent.com/assets/2696404/24889641/b6c8b3fa-1e9d-11e7-93f2-f3c52600f4b0.jpg)
![ulus10089_00002](https://cloud.githubusercontent.com/assets/2696404/24889650/c3c0df92-1e9d-11e7-8498-ec6829eab1d3.jpg)
using ogl there is no problems

**Comment by hikarinnohikari** [comment]
i have same problem for this game. Warriors orochi have same problem too

**Comment by hikarinnohikari** [comment]
warriors orochi and dynasty warriors also have same problem

**Comment by unknownbrackets** [comment]
Has this improved, or does it still happen?

What about Vulkan and Direct3D 9?  It would help to know if they do or don't have the same bug.

-[Unknown]

**Comment by unknownbrackets** [comment]
Could you try exporting a GE debugger dump on PC?

To do this, open the game and select Debug -> GE debugger..., then when it's displaying the scene, press Record in the top right.  After a second or so, it'll finish and save a trace of the drawing activity.

After that, check the memstick/PSP/SYSTEM/DUMP folder and it'll have created a file named something like "ULES12345_0000.ppdmp".  You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by benderscruffy** [comment]
this has been fixed
