### ISSUE TITLE
PPSSPP suddenly crashing on launch

### ISSUE THREAD

**Issue by MegaMoses** [hrydgard/ppsspp#9600]
Tried to start the emulator (v1.2.2) for the first time in a while.  Immediately get a "PPSSPP has stopped working" error before anything loads at all.  Tried it again with the most recent version (v1.4) and the same thing happened.  It worked fine before, so as far as I know, it's not a hardware issue.

The problem details I get from the error are as follows:
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	PPSSPPWindows64.exe
  Application Version:	1.4.0.0
  Application Timestamp:	58de2718
  Fault Module Name:	StackHash_cab9
  Fault Module Version:	6.1.7601.23677
  Fault Module Timestamp:	589c99e1
  Exception Code:	c0000374
  Exception Offset:	00000000000bf3e2
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	cab9
  Additional Information 2:	cab9f133e19a92eb0b0f90c062724bea
  Additional Information 3:	c6ca
  Additional Information 4:	c6cacda73c50a8998d69aeb48abc9096

Using Windows 7 SP1 with an AMD Phenom II X4 955 and a 1024MB ATI AMD Radeon HD 6800 Series (Sapphire/PCPartner) GPU.

**Comment by unknownbrackets** [comment]
Make sure all your drivers are updated - this can mean a problem with a driver.

Also, try downloading the latest git build here:
http://buildbot.orphis.net/ppsspp/

And unzip it into a new folder, and try running from there.  This won't use your settings or save data - if it works, that might mean one of those things are causing the problem.

-[Unknown]

**Comment by MegaMoses** [comment]
Turns out I did have a driver update that the Catalyst Control Center didn't pick up the first time.  Thanks, AMD!

**Comment by MegaMoses** [comment]
Actually, reopening this.  Guess I got lucky last night and now it only crashes most of the time.

So, my drivers are up to date and I tried extracting the latest git to a new folder.  Neither one worked.

**Comment by unknownbrackets** [comment]
If you can get it to run long enough, try switching to the Direct3D 11 backend.  I know we've seen "Catalyst AI" (an AMD feature) crash PPSSPP before, and it seems like Direct3D 11 is a safer option on AMD.

-[Unknown]

**Comment by MegaMoses** [comment]
I've managed to get it to run long enough (in between a ton of instant crashes) for me to select that in the menu, but when I select it, it crashes before it has the chance to restart, so the change doesn't stick.  Sometimes it'll say something along the lines of "Wait for emu thread timed out" before crashing.

Is there any other way to switch to D3D11?

**Comment by unknownbrackets** [comment]
Open memstick/PSP/SYSTEM/ppsspp.ini and look for:

GPUBackend = 0

Change the line to:

GPUBackend = 2

-[Unknown]

**Comment by MegaMoses** [comment]
Again, it seemed to work for a couple tries, and now it's back to crashing.  Looks like the problem details might be slightly different now, though?

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	PPSSPPWindows64.exe
  Application Version:	1.4.0.0
  Application Timestamp:	58de2718
  Fault Module Name:	StackHash_9b74
  Fault Module Version:	6.1.7601.23714
  Fault Module Timestamp:	58bf89e8
  Exception Code:	c0000374
  Exception Offset:	00000000000bf3e2
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	9b74
  Additional Information 2:	9b746793f288ed668a685890795d8405
  Additional Information 3:	0aa6
  Additional Information 4:	0aa64ee312cc01c692a80998f0cafc84

**Comment by unknownbrackets** [comment]
Is this still happening with the latest git build and drivers?  I'm not really sure what it could be, outside that.

-[Unknown]

**Comment by MegaMoses** [comment]
Sorry for the late reply, but yes the issue is still occurring with the latest build.  And drivers are still up to date.

**Comment by MegaMoses** [comment]
I did get a new error last time I tried this though.  Not sure if it means anything.  This isn't the first time I've gotten a more unusual error messages beyond the usual "PPSSPP has stopped working message", but since they're rare and I'm just clicking through the usual message, I typically fail to capture them.

"The insruction at 0x6a01c9f0 referenced memory at 0x00000010.  The memory could not be read.

Click on OK to terminate the program
Click on CANCEL to debug the program"

**Comment by unknownbrackets** [comment]
Does that happen with 1.5.4, or with the latest git build?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
