### ISSUE TITLE
MX vs. ATV Reflex (USA) ULUS10429 graphics problem

### ISSUE THREAD

**Issue by benderscruffy** [hrydgard/ppsspp#9604]
v1.4-80-gd2172c7
it looks like  it has the same problem as #7459 
happens with both d3d11 and ogl 
![ulus10429_00001](https://cloud.githubusercontent.com/assets/2696404/24986968/d2eb2944-202f-11e7-96d5-1a04814bcdc7.jpg)

**Comment by sum2012** [comment]
https://github.com/hrydgard/ppsspp/wiki/How-to-find-a-graphic-issue-with-the-GE-debugger

**Comment by benderscruffy** [comment]
MX vs. ATV Untamed (USA)

**Comment by unknownbrackets** [comment]
Does it look correct in the software rendererer?

-[Unknown]

**Comment by benderscruffy** [comment]
v1.5.4-933-g386c9d4fc
now the screen is black
![mx](https://user-images.githubusercontent.com/2696404/39340090-b5bdeba0-49fe-11e8-8df6-24e864345304.PNG)

**Comment by benderscruffy** [comment]
v1.6.3-526-g669079454
still the same problem
[ULUS10429_0001.zip](https://github.com/hrydgard/ppsspp/files/2437972/ULUS10429_0001.zip)

**Comment by unknownbrackets** [comment]
Unfortunately, this dump didn't work out - I think it may be caused by the recently fixed render-to-texture bug.  Could you create a new one?  Sorry.

-[Unknown]

**Comment by benderscruffy** [comment]
ok here is a new one 
[ULUS10429_0001.zip](https://github.com/hrydgard/ppsspp/files/2612081/ULUS10429_0001.zip)

**Comment by DanteDraconi** [comment]
Hey sorry for the bump

Using v1.9.3-355-g3f382ec9d this still happens to MX vs ATV Untamed
I remember some older versions being either all black or showing the sky + black terrain, might be wrong though. But I'm unaware if it helps in any way

![PPSSPPWindows64_rKpl0Y6GfZ](https://user-images.githubusercontent.com/9718875/75717795-21500000-5cd2-11ea-94f3-53b1cb26fe9a.png)

[ULES00993_0001.zip](https://github.com/hrydgard/ppsspp/files/4277949/ULES00993_0001.zip)

Stepping through the GE debugger i noticed there's a point where it looks fine but the 16px bands Unknown mentioned get drawn on top of

**Comment by Panderner** [comment]
v1.10.3-1117-g3e6d12101 Just black screen only sound effects

**Comment by Panderner** [comment]
https://github.com/hrydgard/ppsspp/commit/88e772cdf7417ddbf0eff8cdf5697b774364baeb fixed menus and fmvs but still black screen in-game only hud.
![Screenshot_2020-11-04-07-35-21-25_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/98052209-95016880-1e70-11eb-87b3-f6835c024374.png)

**Comment by Panderner** [comment]
v1.10.3-1614-g3aa099f2d same happens tried OpenGL and Vulkan
![Screenshot_2021-01-23-12-14-14-528_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/105568489-a9b91280-5d74-11eb-8aee-db27ea495883.jpg)

**Comment by sum2012** [comment]
I get a _dbg_assert_ in v1.10.3-1614-g3aa099f2d
![1](https://user-images.githubusercontent.com/2177532/105580595-448f0c80-5dc8-11eb-8bd6-03e493c890d5.png)
![2](https://user-images.githubusercontent.com/2177532/105580599-49ec5700-5dc8-11eb-87b9-c7769c646281.png)

**Comment by sum2012** [comment]
Redo: I get a_dbg_assert_ in v1.10.3-1614-g3aa099f2d
![1](https://user-images.githubusercontent.com/2177532/105580692-de56b980-5dc8-11eb-8b0e-1fb6e033c209.png)
![2](https://user-images.githubusercontent.com/2177532/105580695-e31b6d80-5dc8-11eb-9e8a-2118bbfa07c0.png)

**Comment by MiguelCardonaG** [comment]
On Android you also have the same problem/error.

https://github.com/hrydgard/ppsspp/issues/13993

**Comment by Gamemulatorer** [comment]
ReinterpretFramebuffers ***ON***
![Screenshot_2021-10-09-16-05-06-530_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/136650049-3bc29fab-337e-4349-92be-2aa1ba3d25e6.jpg)
ReinterpretFramebuffers ***OFF***
![Screenshot_2021-10-09-16-06-04-537_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/136650053-219a9dbe-6990-4694-9123-d6cf1e956e6a.jpg)

**Comment by MojoJojoDojo** [comment]
LOL I was about to check if replays recorded from the PSP could work on PPSSPP but the game shits itself for most of the replays.
The only one I got that showed correctly is this one:
![image](https://user-images.githubusercontent.com/33392696/147882221-ebb1be41-8afa-4296-aa94-5648575d29ed.png)

Also the game is very stuttery and slow in places.

**Comment by Gamemulatorer** [comment]
Software
![Screenshot_2022-01-09-08-22-58-133_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/148664474-37cc594d-1d43-4d8a-89dd-b94b710e5475.jpg)

**Comment by Panderner** [comment]
Software Mode
![Screenshot (19)](https://user-images.githubusercontent.com/37503397/184073769-b54d4342-e975-482f-a61f-3b98a107e284.png)

**Comment by Panderner** [comment]
Please note that hardware modes hit 100% of cpu usage for my I3-12100F

Hardware mode:
![Screenshot (20)](https://user-images.githubusercontent.com/37503397/184074515-4c897915-b4dd-4007-aa8c-3510ff4cb7cf.png)

Software Mode:
![Screenshot (23)](https://user-images.githubusercontent.com/37503397/184074549-7665a40f-64a2-4793-bd21-4e6a9cf99dfe.png)

**Comment by Panderner** [comment]
Here's a screenshot for Untamed running software mode
![PPSSPP v1 13 1-447-g192133878 24_08_2022 8_29_56 pm](https://user-images.githubusercontent.com/37503397/186418677-282031a1-ef8b-4c42-8992-6feb1bc5e6f2.png)

**Comment by Panderner** [comment]
Only MX vs. ATV: On The Edge is playable for hardware modes 
Only for Reflex and Untamed is affected.

**Comment by Gamemulatorer** [comment]
> ReinterpretFramebuffers _**ON**_ ![Screenshot_2021-10-09-16-05-06-530_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/136650049-3bc29fab-337e-4349-92be-2aa1ba3d25e6.jpg) ReinterpretFramebuffers _**OFF**_ ![Screenshot_2021-10-09-16-06-04-537_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/136650053-219a9dbe-6990-4694-9123-d6cf1e956e6a.jpg)

This is kinda improved in the latest build.
![Screenshot_2022-08-26-19-38-41-032_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/186895504-cb46a0cb-e4e9-423d-b4db-fabcf4eda2a2.jpg)
