### ISSUE TITLE
Ability to extract files from RAM?

### ISSUE THREAD

**Issue by alpakeno** [hrydgard/ppsspp#9608]
There is a DLC savedata files ( which is encrypted ) and when loading the game it decrypted into the RAM...
And i want to retrieve these decrypted files from RAM.
So can ppsspp extract these files from ram?

**Comment by hrydgard** [comment]
There's not much built-in dumping functionality, but if you want to dump things after decryption, just go into the loader code (Core/HLE/sceKernelModule.cpp, __KernelLoadElfFromPtr) and add some fopen() and fwrite() calls to write out what you need to disk.

**Comment by Enyby** [comment]
@alpakeno You can use any third-party tool for dump memory on PPSSPP process and extract what you need from this dump.

**Comment by unknownbrackets** [comment]
You can dump PSP RAM from within the memory viewer.

https://camo.githubusercontent.com/4751b3e07671732250dfd49632c2a3c7873d82ad/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f353330363834392f323531373634322f33373835306339322d623435622d313165332d386537372d3861323834316338333166612e6a7067

-[Unknown]
