### ISSUE TITLE
Pause menu button not showing..

### ISSUE THREAD

**Issue by Juliex** [hrydgard/ppsspp#9609]
Using several builds, until 1.4.80 ..
Show pause menu is on at settings but it's not showing on screen in any game.

**Comment by Juliex** [comment]
Hmm..
so.. on android..
well it's annoying on phones with soft buttons..
I always was using this option,
Because at older versions,when i used back key, the emulator 77% times crashed..
And with reporting issues and problems i found that with using pause button,it will not be crashed as always.

**Comment by unknownbrackets** [comment]
The pause button should be restored in a git build soon.

That said, it's not expected that using the back key would crash.  Does this still happen in the latest version?

-[Unknown]

**Comment by Juliex** [comment]
No, after build 1.2.30 and about it, the crash solved.
