### ISSUE TITLE
Can't hide onscreen pause button

### ISSUE THREAD

**Issue by Levan7** [hrydgard/ppsspp#9612]
I can't hide a onscreen pause button and neither i can't disable on screen notifications that ppsspp sometimes prints like about fps and sound lag.

![10](https://cloud.githubusercontent.com/assets/5770076/25039226/a157fa4e-2113-11e7-8bf0-615effa24fc5.jpg)

**Comment by LunaMoo** [comment]
You can hide the button, you just have to do it before launching a game. There's pretty solid reason to disable it completely when not using touch control through as when it was fixed, it's now being shown by default on all windows platforms where touch is merely an option and not a standard, I opened a pr with that.


 The slow down message is a great thing as it finally forces affected people to learn the fact that their "extremely powerful devices that can run some completely unrelated natives game just fine" is not good enough to emulate stuff they want, with settings they used ~ at full speed.
 As far as I can tell it only displays after running at lower speed for more than a few seconds and doesn't even show more than once per ppsspp run.
 That message is really not something users should ignore as running games under full speed is worse than playing on actual psp, so if you really don't want to ever be reminded that your hardware isn't good enough, you will have to manually edit ppsspp.ini and set "HideSlowWarnings" to false under CPU ~ it should look like:

```
[CPU]
HideSlowWarnings = False
```

Currently it has to be done per game, but doesn't seem like there's any sense in doing that, so in my pr I proposed a change for that as well, if it get's merged this setting should be enough to set in main ppsspp.ini.

**Comment by Levan7** [comment]
@LunaMoo 
Thank you for the reply, how do i disable the pause button before the launch (I couldn't find anything in the settings)
About slow down warning under linux it is more common than under windows. (sadly)

**Comment by unknownbrackets** [comment]
Have you tried enabling auto frameskip?  If you see the slowdown warning, it means it's running slow.

Or are you sure the game is running at full speed, but you're seeing the warning anyway?

-[Unknown]

**Comment by Levan7** [comment]
@unknownbrackets 
Well slow down message isn't a big problem to be honest. Yes the fps skip and giving the emulator a high priority helps not to see that massage. However i can't seem to find a way to disable that annoying pauses icon, that i get in the middle of the screen.

**Comment by LunaMoo** [comment]
Right click/Triangle/hold with touch on a game icon in the list to open game/info screen. There you can open per-game settings before running the game ~ as I assume that's your problem as I also wrote in my pr.

**Comment by unknownbrackets** [comment]
This was fixed by #9613, right?

-[Unknown]
