### ISSUE TITLE
The Bigs - ULUS10284 no music or sound fx

### ISSUE THREAD

**Issue by benderscruffy** [hrydgard/ppsspp#9618]
v1.4-84-ga4cb215 	
no music or sound fx during the intros, title screen or ingame
here is an info log
rename txt to zip
[ppsspplog.txt](https://github.com/hrydgard/ppsspp/files/923435/ppsspplog.txt)

**Comment by benderscruffy** [comment]
v1.5.4-933-g386c9d4fc
this has been fixed

**Comment by unknownbrackets** [comment]
Thanks for validating, glad it's fixed.

-[Unknown]
