### ISSUE TITLE
Software renderer doesn't perform mipmapping

### ISSUE THREAD

**Issue by unknownbrackets** [hrydgard/ppsspp#9621]
See also #5350 and #6357 (as well as related water animation), which utilize mipmapping for effects.

@hrydgard can the mipmap level actually vary for a single triangle (per comments in `ApplyTexturing()`)?  Aside from `GE_TEXLEVEL_MODE_SLOPE`, the lod is just based on derivatives of x, y, s, and t right?  So it should be constant over an entire triangle.

I'm not sure how the LOD slope works, though.

-[Unknown]

**Comment by hrydgard** [comment]
Yes, definitely. Because of perspective, LOD can vary drastically across a triangle. Imagine a road triangle that goes toward the horizon. On most GPUs, I believe the PSP included, the LOD is computed by always computing a 2x2 quad of pixels together, and taking something like the log2 of the horizontal and vertical deltas in texture coordinates inside that pixel quad as the LOD level for that entire pixel quad.

**Comment by unknownbrackets** [comment]
Ah right, of course.  So in the rasterizer, this is based on the w0/w1/w2 parameters, essentially.

Though, I wonder if we could skip that in the common case of large draws with `flatZ`...

-[Unknown]

**Comment by hrydgard** [comment]
Well, yes, since the texture coordinates are computed using them. It's probably best to do it the quad way. Also a SIMD opportunity...

Yes, computing the deltas is not necessary when all three corners of the triangle have the same depth, or if the mipmapping mode is set to fixed, which is what I think those games do that use it to crossfade (they set it to fixed then vary the bias).

**Comment by unknownbrackets** [comment]
Mipmap behavior based on hardware tests:

 * Magnify _MIPMAP_NEAREST/_MIPMAP_LINEAR doesn't do anything, as expected.
 * All mips can be any size (larger, same, smaller than half, etc.)
 * SLOPE so far forces to mip 0 regardless of bias (in through/rect.)
 * AUTO does what you'd expect, adjusted by bias (negative affects mag, uses min filt.)
 * CONST uses bias directly.
 * Bias 0x07 rounds down, 0x08 rounds up.
 * Bias is simple two's complement times 16 (0x87 rounds negative, 0x88 rounds positive.)
 * GU_NEAREST/GU_LINEAR disable mips (as expected.)
 * Mip levels are ignored if > max level setting (as expected.)
 * Even in throughmode, texcoords scale for mips (i.e. w7 * u / w0 for level 7.)
 * UV (8, 1) or (1, 8) minifies same as (8, 8) - so it takes the max side.
 * TODO: How does slope work?

Separately, GLES notes (not complete for all cases above):

 * GLES does not seem to take max side to calculate minify level.
 * GLES incorrectly ignores bias in AUTO mode (in this case, it is a bias.)
 * GLES incorrectly treats CONST as a delta bias - it SHOULD select a constant mip level.
 * GLES incorrectly selects mip level 0 for CONST 0x10.
 * GLES obviously doesn't really support non-halving mip levels.
 * GLES treats SLOPE as AUTO, but not sure what it's supposed to do.

-[Unknown]

**Comment by hrydgard** [comment]
Impressive, and mostly as expected. The mipmapping hardware is really one of the most non-standard parts of the PSP's pixel pipeline, but as we've seen it can emulate a standard one very well, and games don't often go outside the standard path. When they do though ...

As for slope mode, no idea.

To simulate the non-halving mipmaps, I think the only sane path is to upscale all mips to the same size and put it all in a 3D texture. Then we'd use the various parameters together with texture coordinate derivatives (dFdx and dFdy in GLSL) in the fragment shader (bias, const) to manually compute a mip level and use that as the Z coordinate when looking up the texture. Round the Z coordinate to integers if in GU_NEAREST and let the 3D texture do the filtering when in GU_LINEAR.

The drawback of this method is of course that 3D texture support is required, which means that we can only do this in GLSL3, Vulkan or DX11. GLES2 and DX9 can't do it. For those we could simulate 3D textures by packing them next do each other in big 2D textures and simulating 3D lookups by making two lookups and blending, but that makes wrapping tricky which would be a problem for that Macross game or whatever it was that uses this for a water surface, and probably not really worth the trouble.

**Comment by unknownbrackets** [comment]
Yeah, I was thinking the same.

Theoretically, for CONST, we could simulate it on GLES with a second texture stage.  Since the mip level is constant, CONST can only ever involve 1 or 2 mip levels - never more (and if MIPMAP_NEAREST, it can only involve one period.)

-[Unknown]

**Comment by unknownbrackets** [comment]
Oops, I wasn't setting the separate tex slope register properly.  It seems to act as a scaling factor for the mipmap level calculation, though there's more to it.

 * SLOPE doesn't seem like it's doing any calculation involving z, at least not in throughmode.
 * The sign of the slope register doesn't seem to matter.
 * A slope register of 0.0f is the same as const mip 0, regardless of bias.
 * A slope register of 64.0f selects mip 7, + bias, such that 0x80 bias means mip 0.
 * A slope register of 32.0f selects mip 6 + bias, such that 0x10 bias means mip 7.
 * A slope register of 512.0f selects mip 7 + (bias + 3), such that 0x80 bias means mip 2.
 * So, it seems like SLOPE *almost* means CONST `1 + log2f(texSlope) + bias` (non-powers of two match also, so do values less than 1.0f.)

However, there's still more to it.  When I set reversed mip levels (going up from 1x1, 2x2, 4x4, etc.), sometimes it consistently selects an unexpected mip level.  For example, slope = 1.0f, bias = 0.0f, 4x4 magnify and 4x0.5 minify both select mip 1, while 0.5x4 minify, 2x2 minify, and even 256x256 minify select mip 2.  This is even with a constant (flat) Z.

I'm not really sure what games use it... need to look at some real world usage.

-[Unknown]

**Comment by unknownbrackets** [comment]
Actually, I missed that similar behavior occurs with CONST too:

```
[x] Reversed mips (CONST) +08:
[r]   1:1: 101010
[r]   Magnify: 080808
[r]   Minify 2x WH: 101010
[r]   Minify 4x W: 080808
[r]   Minify 4x H: 101010
[r]   Minify 64x: 101010
[r]   Minify 256x: 101010
```

In this case, 4x4 magnify and 4x0.5 minify are selecting mip 0.5.  Maybe it has something to do with tex wrap - in the reversed case, the base level is only 1x1, If I start mip 0 at 4x4, it behaves as expected (2x2 does not behave as expected.)  Probably some obscure hardware bug that no game uses, if it only happens at < 4x4 mip 0.

-[Unknown]

**Comment by unknownbrackets** [comment]
Now being performed by the software renderer - closing.

-[Unknown]
