### ISSUE TITLE
Compilation fails on generic armv7 (odroid XU4) because 'Linking CXX executable' fails 

### ISSUE THREAD

**Issue by Polypodiales** [hrydgard/ppsspp#9630]
I'm trying to compile ppsspp from source on an odroid XU4. The machine is running kernel
4.9.23-1 and uses proprietary drivers for the Mali-T628 GPU with OpenGL ES 3.1 which have been installed correctly and cmake seems to play well with the files it needs for 3D acceleration. It seems to compile just fine but after it reaches 100% and gets to `[100%] Linking CXX executable PPSSPPSDL` it crashes.

```
...
[100%] Building CXX object CMakeFiles/PPSSPPSDL.dir/UI/ui_atlas.cpp.o
[100%] Building CXX object CMakeFiles/PPSSPPSDL.dir/UI/TextureUtil.cpp.o
[100%] Building CXX object CMakeFiles/PPSSPPSDL.dir/UI/ComboKeyMappingScreen.cpp.o
[100%] Linking CXX executable PPSSPPSDL
lib/libCore.a(TextureDecoder.cpp.o): In function `CheckAlphaRGBA8888Basic(unsigned int const*, int, int, int)':
TextureDecoder.cpp:(.text+0xc60): undefined reference to `CheckAlphaRGBA8888NEON(unsigned int const*, int, int, int)'
lib/libCore.a(TextureDecoder.cpp.o): In function `CheckAlphaABGR4444Basic(unsigned int const*, int, int, int)':
TextureDecoder.cpp:(.text+0xd44): undefined reference to `CheckAlphaABGR4444NEON(unsigned int const*, int, int, int)'
lib/libCore.a(TextureDecoder.cpp.o): In function `CheckAlphaABGR1555Basic(unsigned int const*, int, int, int)':
TextureDecoder.cpp:(.text+0xe0c): undefined reference to `CheckAlphaABGR1555NEON(unsigned int const*, int, int, int)'
lib/libnative.a(fast_math.c.o): In function `InitFastMath':
fast_math.c:(.text+0xc): undefined reference to `fast_matrix_mul_4x4_neon'
fast_math.c:(.text+0x10): undefined reference to `fast_matrix_mul_4x4_neon'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/PPSSPPSDL.dir/build.make:884: PPSSPPSDL] Error 1
make[1]: *** [CMakeFiles/Makefile2:86: CMakeFiles/PPSSPPSDL.dir/all] Error 2
make: *** [Makefile:117: all] Error 2

```

I see it's complaining about ``undefined reference to `fast_matrix_mul_4x4_neon'`` and I have found another bug report about someone who encountered this issue on the RaspberryPi here: #9104

> I'm having some linking issues now due to missing fast_matrix_mul_4x4_neon

He ended up fixing it by modifying the toolchain file (raspberry.armv7.cmake) to properly set some flags through a workaround. I tried to apply the same fix he came up with to my toolchain file (generic.armv7.cmake,) but it makes no difference. Am I even on the right track?

I have uploaded the entire build log with the default verbosity, just in case in could be helpful. 
[ppssppbuildlog.txt](https://github.com/hrydgard/ppsspp/files/948742/ppssppbuildlog.txt)

All of this is without qt, just running ./b.sh

`clang version 4.0.0    Target: armv7l-unknown-linux-gnueabihf`

**Comment by unknownbrackets** [comment]
Does it fix it if you change this line:

https://github.com/hrydgard/ppsspp/blob/a1b3a4384c341316c4c912721ec4d8e5cfd2e32a/GPU/Common/TextureDecoder.cpp#L571

To:

```c++
#elif PPSSPP_ARCH(ARM_NEON)
```

I'm guessing NEON isn't enabled.

-[Unknown]

**Comment by sergiobenrocha2** [comment]
I think it's worth put this thread from where this issue came from: https://forum.odroid.com/viewtopic.php?f=91&t=26822#p187859

**Comment by sergiobenrocha2** [comment]
@Polypodiales are you trying to build to FBDEV or X11? I just use

```
-DUSING_GLES2=ON -DUSING_EGL=ON -DUSING_QT_UI=ON
```

in the cmake, it builds & works nicely (X11 environment, LXDE desktop). I have an issue with SDL port, it builds but segfault (see #7815). I tested only in the Odroid U3

**Comment by sagitter** [comment]
Hello!
Does exist a fix for this issue?

**Comment by AreaScout** [comment]
This should help you #11344

**Comment by sagitter** [comment]
Thanks.

Could your [definitions](https://github.com/hrydgard/ppsspp/issues/11344#issuecomment-417914109) conflict with those ones used by default on fedora-arm7 (`-march=armv7-a -mfpu=vfpv3-d16 -mtune=generic-armv7-a -mabi=aapcs-linux -mfloat-abi=hard`) ?

**Comment by AreaScout** [comment]
ahh those are the default definitions gcc is compiled with ?, if yes then they are overwritten

``odroid@odroid:~$ gcc -v``
``Using built-in specs.``
``COLLECT_GCC=gcc``
``COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/7/lto-wrapper``
´´Target: arm-linux-gnueabihf``
``Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 7.3.0-16ubuntu3' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --with-as=/usr/bin/arm-linux-gnueabihf-as --with-ld=/usr/bin/arm-linux-gnueabihf-ld --program-suffix=-7 --program-prefix=arm-linux-gnueabihf- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libitm --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --enable-multilib --disable-sjlj-exceptions --with-arch=armv7-a --with-fpu=vfpv3-d16 --with-float=hard --with-mode=thumb --disable-werror --enable-multilib --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 7.3.0 (Ubuntu/Linaro 7.3.0-16ubuntu3)``

**Comment by sagitter** [comment]
>huh ? fedora is adding those definitions by default to g++ ... interesting, definitions added by cmake would override it I guess, just try to add VERBOSE=1 to make command (make -j7 VERBOSE=1) and see what is defined last (suffix), if my definitions are the last ones then they are used.

They aren't overrided but appended: [build log on arm7hl](http://koji.rpmfusion.org/kojifiles/work/tasks/6795/256795/build.log)
ppsspp is now compiled without errors.

**Comment by AreaScout** [comment]
That's what I was asking you indirectly if those definitions are added to g++ by fedora i.e environment variable (then the variable would be just overwritten) or did you mean the one which are compiled in for g++ and used then by default if nothing was specified (then they would be 'appended'), those compiled in CPU features can be varying across Linux distributions.

**Comment by unknownbrackets** [comment]
It sounds like you got this to compile and it's working now.  I know we also made some changes a little while back to make sure NEON support detection was more consistent.

Going to close this now assuming it's been fixed.  If you're still seeing issues here, please feel free to comment and we'll reopen.  If you're seeing a new issue, different from before, it's better to create a new issue.

-[Unknown]
