### ISSUE TITLE
Ppsspp gold and jar touch screen

### ISSUE THREAD

**Issue by skelletR** [hrydgard/ppsspp#9636]
Hi.. Very good app the best.. I have a question.. In ppsspp gold I found I trick and can play old jar games with emulator but some jar  games is touch screen and the ppsspp gold can put touch in emulator?

**Comment by hrydgard** [comment]
Yeah, there's some homebrew Java JAR emulator for PSP that you can run.

Unfortunately the PSP never had touch input so that JAR emulator running inside PPSSPP has no knowledge of touch screens, so this isn't really possible.

Whether gold or not doesn't matter so removing from issue title.
