### ISSUE TITLE
Random glitches on loading savestates in some games

### ISSUE THREAD

**Issue by LunaMoo** [hrydgard/ppsspp#9637]
I believe it might be problem from [this thread](http://forums.ppsspp.org/showthread.php?tid=22879), I can reproduce loading savestates some times causing black or discolored screen, same thing can happen when changing rendering modes ie buffered rendering-> skipping buffers -> buffered rendering again = black screen.

 Changing resolution destroys FBO's and as such does restore correct graphics.

Edit: Renamed since the problem left isn't about FBO's.

 Also to list  easy test case for reproducing D3d11 savestate loading problem - Cave Story from homebrew store. Save at main menu then continuosly load.:3

**Comment by unknownbrackets** [comment]
Loading a savestate should always delete all FBOs - what's the behavior where you're seeing that?

-[Unknown]

**Comment by LunaMoo** [comment]
It feels random just load a savestate a few times, sometimes it loads correctly, sometimes graphics are missing, are discolored or everything's black. But seems to affect only some games, for example happens in Valkyrie Profile, 7th dragon 2020, but can't reproduce at all in others like Jeanne D'Arc or Patapon.

**Comment by unknownbrackets** [comment]
I'm seeing this error in D3D11:

```
D3D11 ERROR: ID3D11DeviceContext::DrawIndexed: Input Assembler - Vertex Shader linkage error: Signatures between stages are incompatible. Semantic 'COLOR' is defined for mismatched hardware registers between the output stage and input stage. [ EXECUTION ERROR #343: DEVICE_SHADER_LINKAGE_REGISTERINDEX]
D3D11: **BREAK** enabled for the previous message, which was: [ ERROR EXECUTION #343: DEVICE_SHADER_LINKAGE_REGISTERINDEX ]
```

I don't think it's related to the FBOs.

-[Unknown]

**Comment by LunaMoo** [comment]
You're probably right, also noticed selecting same rendering res that's being used is enough to fix the messup from loading savestates, but that doesn't count as resizing, so FBO's aren't destroyed.

**Comment by hrydgard** [comment]
I've seen that one on occasion too, haven't quite figured out what's going on there yet...

**Comment by LunaMoo** [comment]
No idea where this problem occurs, but I made myself a workaround for this issue by adding:
````
					if (gpu) {
						gpu->ClearCacheNextFrame();
					}
````
on successful SAVESTATE_LOAD, which works, so maybe it can give any hint to someone where to look for the actual problem.

**Comment by unknownbrackets** [comment]
All that should do is trigger a texture cache clear.  What's weird is: loading a save state already clears the texture cache.

It seems to make it happen less often for me (maybe?  subjective), but I reproduced it even with that code there.

-[Unknown]

**Comment by LunaMoo** [comment]
Thanks for testing, maybe I just got into lucky rhytm when loading state in a heavier game avoiding problems by accident, tested now in cave story which states probably loads faster and it still happens about as often as without. Eh placebo;c.

 Could you try this instead:
````
					if (gpu) {
						gpu->Resized();
					}
````
 Since tried it now and it seems working even with Cave Story, but maybe it's again just my luck.

 Probably obvious, but I'm trying that code since resizing window seems like the quickest and least changing way of getting rid of those glitches and it does only call gpu->ClearCacheNextFrame() and gpu->Resized().

**Comment by unknownbrackets** [comment]
I think I found it - our input layout map uses the vshader pointer as a key.  If we delete vshaders, we also need to clear out input layout map.

-[Unknown]
