### ISSUE TITLE
Flickering on The Legend of Heroes: Trails in the Sky

### ISSUE THREAD

**Issue by Hydroque** [hrydgard/ppsspp#9642]
IDK if it is just my hardware or what, but using,

OpenGL
With and without vertex cache and hardware transform
Skip buffer effects
Multithreaded
Fast memory off
CPU clock 222mhz
Anisotropic filtering 4x
Linear scaling and texture filter

I get to-black flicking whenever a move takes place. So, I click attack and it goes to select a monster mode, it will flicker all black for a frame or so.
Which this concerns me, as the first battle place I could go to (in the sewers) had an icky black diamond in the center of the ground.

Can anyone confirm this?
-cut-

**Comment by LunaMoo** [comment]
Awful settings:
- skip buffer effects,
- multithreading,
- cpu clock forced to 222mhz,

 All could easily cause this:] which makes this bug report useless. Revert to default settings and try again.

Also we don't support piracy, I removed warez link from your post.

**Comment by Hydroque** [comment]
It wasn't to download it, it was to show which game. Anyways, it is abandon ware.

Skip buffer effects must be on, but that doesn't stop testing, but instead I got a bm.

**Comment by LunaMoo** [comment]
There's no such thing like "abandonware" people use that term to justify downloading games illegaly when they can't obtain them anymore, at least that's how the term was used before shops like GOG started obtaining rights to sell ancient games and those now sold games didn't disappeared from abandonware aka warez sites.
 Even if such term would exist legally(and it doesn't) The Legend of Heroes: Trails in the Sky is actively sold on many platforms, from PSP to even PC.

 Skip buffer effects is a hack that disables buffers from being used by game, games absolutely require those to do certain effects and in some cases everything you see on the screen, we even have a warning printed on the screen when that option is selected. It's not a setting that "must be on", it's a setting that "you might use for performance on a really weak device, if you don't mind missing, flashing or bad graphics":].

 Also I have the original game not some "abandonware" and tested it - nothing like that happens, at least not on PC, doesn't even matter the backend or settings. I can't reproduce neither flashing nor missing stuff in this game, the only hack which breaks this game's graphic is forcing depth draw and with it's simple graphics it even works well in software rendering(which is known to be buggy for most games).

 To sum it up:
- you didn't listed device you're using,
- nor ppsspp version which looking at quality of the report might as well also be some outdated copy downloaded from warez site,
- used game breaking settings/hacks and didn't reverted to default ones when being told they could cause this,
- included a warez link and defended it after being told we don't support warez,
- most likely used that pirated game copy which you consider "abandonware", those are often bad/incomplete dumps or rips causing random errors from missing content to freezes, even if they would be proper dumps, downloading large files from awful sites by itself would easily damage them,
- say you're getting BM'ed for lack of special snowflake treatment.

 Honestly I don't mind writing longer posts informing user about all the other stuff that I might have skipped when seeing something awful and concentrating on that in a quick answer while being busy with other stuff, but I can't stand people with nose in the clouds who expect being handled like a rotten egg, so I put this on ignore. It's most likely a driver problem, outdated ppsspp or a bad game copy with corrupted files.
