### ISSUE TITLE
Can't assign letter keys for buttons

### ISSUE THREAD

**Issue by thesourcehim** [hrydgard/ppsspp#9648]
On button assignment screen when I try to reassign a button, only some keys work (shift, atl...), but pressing letters does nothing, "reassign" dialog is not vanishing, assignment stays the same. Linux build, v1.4-142-g14e6667

**Comment by thesourcehim** [comment]
Working again in v1.4-200-gf9b2272

**Comment by hrydgard** [comment]
Weird, but ok.

**Comment by unknownbrackets** [comment]
I've gotten some weird focus issues on Windows sometimes - focusing another window and back will often fix it.  Usually it affects the scroll wheel but uncommonly it also affects keyboard.

But it only really happens if the debugger or log console is open.  Not sure what causes it.

-[Unknown]
