### ISSUE TITLE
Dissidia 012 save state graphics freeze in 1.4 (D3D11)

### ISSUE THREAD

**Issue by XSeoHD99** [hrydgard/ppsspp#9652]
Savestates from 1.4 freezes on load. savestates from 1.3 loads normally on 1.4.when loading 1.4 save states bgm works else is frozen.

Edit: happens only in direct3d11

**Comment by unknownbrackets** [comment]
Does this still happen?

-[Unknown]

**Comment by XSeoHD99** [comment]
Saves states made in 1.4 still freeze when loaded in 1.5.2 but saves states
made in 1.5.2 are working (D3D11)

**Comment by unknownbrackets** [comment]
I'm going to close this since it hasn't been an issue since for newer save states.  Sometimes save states memorialize old bugs, it's basically the nature of a save state.

-[Unknown]
