### ISSUE TITLE
Metal gear portable OPS Directx 11 backend bugs after loading a savestate

### ISSUE THREAD

**Issue by rashvash** [hrydgard/ppsspp#9660]
Win 7, x64, Videocard: ATI radeon HD 7870, driver ver. whql-win7-64bit-radeon-software-crimson-relive-17.1.2-feb6. Backend: D3D11. Game: Metal gear portable OPS. While playing everything seems to be alright, but as soon as you try to load a savestate:

![bug 1](https://cloud.githubusercontent.com/assets/28275367/25596394/9ad7499c-2ed1-11e7-9244-6340687c8c09.jpg)
![bug 2](https://cloud.githubusercontent.com/assets/28275367/25596481/f7604858-2ed1-11e7-972c-7d0064cd3c58.jpg)
![bug 3](https://cloud.githubusercontent.com/assets/28275367/25596483/fcb92e96-2ed1-11e7-85b8-dc6bca3c8850.jpg)

**Comment by hrydgard** [comment]
Likely related to #9652

**Comment by LunaMoo** [comment]
Does reloading a few times or changing rendering resolution(even to same one) helps?
 If the game doesn't freeze, but just show up weird glitches with randomly missing graphics it could be a duplicate of #9637

**Comment by rashvash** [comment]
Well, if you reload a numerous times it randomly gets normal. But it can be the 2nd time or the tenth time absolutelly randomly. And it's a random bug, one time after the reload it can be a completely blue screen or completely black screen or some parts of the image missing etc. (see screenshots). Sometimes even after reloading 20-30 times it doesn't get normal. Yes, changing resolution helps.

**Comment by LunaMoo** [comment]
I'll close this as a duplicate of the issue I noted above then, this affects a lot of games, including some from homebrew store which makes it easy to reproduce, no point tracking it per game.
