### ISSUE TITLE
Need for Speed Underground Rivals crashes on one race

### ISSUE THREAD

**Issue by Maarcis12** [hrydgard/ppsspp#9661]
Hello, i'm having this issue whenever i start this race: 
![ppsspp_appcrash](https://cloud.githubusercontent.com/assets/26842473/25644299/bfa0f4d0-2fad-11e7-938e-d5d86cba7e66.jpg)

It results in crashing : 
![ppsspp_appcrash1](https://cloud.githubusercontent.com/assets/26842473/25644310/d35e616a-2fad-11e7-8da1-5b3742878afd.jpg)

I'm also attaching error report from that crash: 
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	PPSSPPWindows64.exe
  Application Version:	1.4.0.0
  Application Timestamp:	58de2718
  Fault Module Name:	StackHash_1e37
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	00000000
  Exception Code:	c0000005
  Exception Offset:	000000013e058e25
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1062
  Additional Information 1:	1e37
  Additional Information 2:	1e373e69fff075aed81f57003e66ce10
  Additional Information 3:	9f0e
  Additional Information 4:	9f0e095f32a88249d7a2b7eca4e322ea

Is there any fix for that or should i use older versions?

**Comment by Maarcis12** [comment]
my extreme apologies, as it turns out, my european copy of need for speed underground rivals was just broken or damaged, so i got north american copy, which actually works just fine.

**Comment by LeRutY** [comment]
Well strange for me it doesn't work neither, it has to be a problem with european copies.
