### ISSUE TITLE
PPSSPP 1.4

### ISSUE THREAD

**Issue by FullaDelNay** [hrydgard/ppsspp#9663]
i dont know if this is an issue or not but okay here's my issue:

Im currently playing Monster Hunter Portable 3rd with 1.2 and i got full 30 fps at most.
but only 24 - 27 with 1.4

my spec is :
Intel Celeron BB800 1.50 Ghz
2gb RAM
Windows 7 32bit

is PPSSPP the problem or it's just my woody pc?

Thank you in advance.

**Comment by Krakn** [comment]
> it's just my woody pc?

99% chance it's just your PC... :(

**Comment by FullaDelNay** [comment]
i see, thx
