### ISSUE TITLE
Partial restart on backend switch feature probably never worked right

### ISSUE THREAD

**Issue by pal1000** [hrydgard/ppsspp#9666]
1. v1.4-93-g 1a9e93d (feature debut) - v1.4-146-g dbd8085 (Thin3D GUI hangs when switching from D3D11 to OpenGL). The other way works just fine. 

I don't have Vulkan support on my system, also I didn't install D3D9 runtime. I basically have no program on my system that require it anymore. 

2. Somewhere after v1.4-146-g dbd8085, v1.4-153-g 712fb08 being confirmed affected, Still present on latest build. PPSSPP crashes when switching backends. Doesn't seam to matter from which backend you switch to any other.

**Comment by hrydgard** [comment]
@unknownbrackets 

I haven't tested this much myself yet but the little I have, worked for me. I'll test a little more and see if there's something obvious I can fix.

**Comment by hrydgard** [comment]
Hm, you're right, it doesn't work at all right now. The WindowsHost instance gets replaced by a NativeHost instance which then does not initialize the new graphics context. Looking into it.

**Comment by unknownbrackets** [comment]
What video card do you have?  Are there any logged errors?

-[Unknown]

**Comment by pal1000** [comment]
@hrydgard latest commits restored the situation to what was before v1.4-153-g 712fb08.
In the meantime I installed D3D9 runtime in order to do a complete test. Thin3D hang is still present when switching from D3D9 or D3D11 to OpenGL. Switching from OpenGL to any D3D backend or switching from any D3D backend to the other works with no issues.
I have an old laptop with this configuration:
![thin3d-hang1](https://cloud.githubusercontent.com/assets/1138235/25748981/acfca02c-31b5-11e7-9d47-0e394089643a.png)
![thin3d-hang2](https://cloud.githubusercontent.com/assets/1138235/25749001/b4c19132-31b5-11e7-850b-a65f1e2e5944.png)

**Comment by unknownbrackets** [comment]
Maybe we can at least keep doing it on NVIDIA?  I really like having the debugger stay attached in VS.

Ideally we could find the part where OpenGL init fails and properly trigger a restart...

-[Unknown]

**Comment by hrydgard** [comment]
I'm all for that.

**Comment by pal1000** [comment]
I also tried Mesa llvmpipe to check if it's indeed driver bug. llvmpipe is a bit smarter, avoiding a Thin3D hang by forcing a full restart somehow. Pre-built llvmpipe for both 32 and 64-bit are  available [here](https://github.com/pal1000/mesa-dist-win).

**Comment by unknownbrackets** [comment]
Yeah, if we're able to detect that OpenGL init fails for some reason, we force a full restart.  On NVIDIA, this doesn't happen except when going from OpenGL to Vulkan, but apparently we're not catching a case for your driver on OpenGL init.

This could mean we are shutting down D3D11 incorrectly, somehow, and NVIDIA is just smoothing it over for us...

-[Unknown]

**Comment by hrydgard** [comment]
I know we do leak a few resources on D3D11 shutdown, should track those down. Other than that it should be OK...

**Comment by hrydgard** [comment]
I think we've done what we can do easily now, and this should not be any issue for users anymore. Closing.
