### ISSUE TITLE
Test drive unlimited low frame rate

### ISSUE THREAD

**Issue by Levan7** [hrydgard/ppsspp#9671]
So i started the game on PPSSPP v1.4-181-g42a6943 and noticed that it has unusually bad frame rate even in menus.

[log.zip](https://github.com/hrydgard/ppsspp/files/981655/log.zip)

**Comment by LunaMoo** [comment]
That's known issue see #7347, closing as a duplicate.

If you have US version of this game, you can check it's forum thread for a hackish solution that just removes the nasty block transfer effect altogether.
