### ISSUE TITLE
Regression with VertexDecoder from recent optimization

### ISSUE THREAD

**Issue by LunaMoo** [hrydgard/ppsspp#9679]
Notice the dark shadow on water:
![uljs00321_00000](https://cloud.githubusercontent.com/assets/5485237/26025893/9009e578-37f1-11e7-92bf-c0be58fb75ec.jpg)
![uljs00321_00001](https://cloud.githubusercontent.com/assets/5485237/26025895/94910d42-37f1-11e7-89aa-680c01909e08.jpg)

Happens only on 64 bit builds, so was easy to find:
https://github.com/hrydgard/ppsspp/pull/9674/commits/0fe927aaa7cb0278e0954b9cf6adc37a627427c5
Seems like reverting the change just in VertexDecoderJitCache::Jit_NormalFloat() is enough to fix it.
Edit: actually it might be just a typo there :) posoff instead of nrmoff ~ checking(or rather I will after my VS finishes updating >.>).

**Comment by hrydgard** [comment]
Yup, that's such a typo indeed - good catch.

**Comment by unknownbrackets** [comment]
Oops, sorry.  Thanks for catching.

-[Unknown]

**Comment by LunaMoo** [comment]
:3 You're welcome, btw thanks for those softGPU mipmaps. Got back to this macross game just to check them and the water animation looks nice in softGPU now:).
