### ISSUE TITLE
FX Sound PPSSPP

### ISSUE THREAD

**Issue by Endarko** [hrydgard/ppsspp#9687]
Why on android 6.0.1 (MM). The Dolby FX sound can not influence PPSSPP

**Comment by hrydgard** [comment]
Don't know for sure, but PPSSPP uses OpenSL playback directly and configures it for lowest possible latency (audio delay) on your device. It's possible that this bypasses Dolby effects.

**Comment by Endarko** [comment]
But in android games. Dolby fx affects to ppsspp

**Comment by Endarko** [comment]
But in android games. Sound dolby effect can affect it

**Comment by Emulatorer** [comment]
@Endarko I tried a custom rom 6.0.1 Marshmallow with built-in Dolby Atmos FX and it is influencing the sound now in the current gitbuild of PPSSPP.

**Comment by hrydgard** [comment]
I'm gonna close this.
