### ISSUE TITLE
PPSSPP doesn't launch anymore?

### ISSUE THREAD

**Issue by GamerzHell9137** [hrydgard/ppsspp#9689]
I'm not sure when it started happening but the latest nightly build PPSSPP isn't launching on my PC.

I'm using GTX 960 and i'm on Windows 10 Pro x64.
I'll try to find out the revision on which it stopped working.

Maybe the Creator Update has done something to it?

EDIT: Ahh, nvm. I've replaced the older PPSSPP with the newer one and it made some kind of issues it seems, it didn't want to load. Putting the new revision in another folder fixed it.

**Comment by GamerzHell9137** [comment]
Well i'd like to open it again.
Downloaded the latest github and its not working for whatever reason. Double clock with Admin or without nothing happens. No error or whatsoever. Same specs.

**Comment by GamerzHell9137** [comment]
It happens even with the 1.4.1 stock version. 1.3 works fine. Ohh and it seems it has to do with the PPSSPP.exe file. Latest versions of PPSSPP launch fine trough DebugLog.bat

**Comment by unknownbrackets** [comment]
Are you using the 32-bit or 64-bit version of PPSSPP?

DebugLog.bat mostly just runs the exe:
https://github.com/hrydgard/ppsspp/blob/master/Windows/DebugLog.bat#L6

-[Unknown]

**Comment by GamerzHell9137** [comment]
x64 bit but Windows x64 would run either, wouldn't it?

**Comment by hrydgard** [comment]
Might this be some antivirus, Windows Defender or similar kind of false positive?

**Comment by GamerzHell9137** [comment]
@hrydgard Didn't get any triggers from Windows Defender. Its weird that it launches fine trough Debuglog thou.

**Comment by hrydgard** [comment]
Did this get resolved?

**Comment by unknownbrackets** [comment]
There haven't been other reports, so assuming this hasn't recurred.  Please comment here if that's not the case.

-[Unknown]

**Comment by GamerzHell9137** [comment]
It was Windows Defender. Was supposed to disable couple of things to make it work but no issues now and you don't need to do anything to fix it.
It didn't report it as a virus, it just didn't let it run.

**Comment by Salamander3** [comment]
Same here, last thing i did was changed render mode to vulkan for testing (PC win10).
ppsspp stopped working, crashed.
Now, i try to start it and the cursor changes to a circle as if it was loading but then goes back to normal and doesn't start.
Downloaded 5 build from github, and latest stable from the site. nothing works.
Restarted the PC, same, compatibility mode, run as admin. Same.

Does it save some config on the resgitry or elsewhere?
