### ISSUE TITLE
Cannot Load ISO If Path Contains Spaces

### ISSUE THREAD

**Issue by Enverex** [hrydgard/ppsspp#9692]
This is a little weird and I'd imagine someone else has ran into this issue before me, but I couldn't find an existing report.

The problem is that PPSSPP doesn't work with any files that contain a space or who's path contains a space. Escaping doesn't work either, regardless how you try. Examples:

Typical backslash escapes:
```
ppsspp /mnt/store/Emulation/Games/Sony\ -\ PSP/Yu-Gi-Oh\ GX\ Tag\ Force\ 2.iso
OpenGL 2.0 or higher.
38:18:214 Core/Config.cpp:1021 I[LOADER]: Loading controller config: /home/arcade/.config/ppsspp/PSP/SYSTEM/controls.ini
W: file_util.cpp:163: IsDirectory: stat failed on /mnt/store/Emulation/Games/Sony
File not found: /mnt/store/Emulation/Games/Sony
```

Quoted?
```
ppsspp "/mnt/store/Emulation/Games/Sony - PSP/Yu-Gi-Oh GX Tag Force 2.iso"
OpenGL 2.0 or higher.
45:16:409 Core/Config.cpp:1021 I[LOADER]: Loading controller config: /home/arcade/.config/ppsspp/PSP/SYSTEM/controls.ini
W: file_util.cpp:163: IsDirectory: stat failed on /mnt/store/Emulation/Games/Sony
File not found: /mnt/store/Emulation/Games/Sony
```

Backslash AND quoted:
```
ppsspp "/mnt/store/Emulation/Games/Sony\ -\ PSP/Yu-Gi-Oh\ GX\ Tag\ Force\ 2.iso"
OpenGL 2.0 or higher.
38:32:759 Core/Config.cpp:1021 I[LOADER]: Loading controller config: /home/arcade/.config/ppsspp/PSP/SYSTEM/controls.ini
W: file_util.cpp:163: IsDirectory: stat failed on /mnt/store/Emulation/Games/Sony\
File not found: /mnt/store/Emulation/Games/Sony\
```

Literally impossible to give the file to PPSSPP. If I create a symlink to the file and use a path that doesn't contain spaces, e.g. /tmp/psp.iso and load that, it works.

**Comment by hrydgard** [comment]
Huh, pretty sure that has worked before...

**Comment by hrydgard** [comment]
This mystifies me a bit, because it appears to work for me. Mind, this is on a Mac:

    ./b.sh --debug
    build/PPSSPPSDL.app/Contents/MacOS/PPSSPPSDL ../psp/Wipeout\ Pure.cso

Starts up just fine with no issues.

**Comment by unknownbrackets** [comment]
I seem to remember some Linux packagers are using "start up scripts" for PPSSPP.  If `ppsspp` is customized, it may be a bug the packager introduced.

-[Unknown]

**Comment by Enverex** [comment]
Let me double check first that it's not something stupid like that then.

**Comment by unknownbrackets** [comment]
Wow, that even messes up relative paths...

-[Unknown]

**Comment by Enverex** [comment]
Yeah, I'll raise a point about it on the AUR page for the package (as it's the Arch AUR ppsspp-git package).
