### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by Silent-Night** [hrydgard/ppsspp#9696]
I really love and enjoy using your app and i follow you on github but it seems that most requests only follow the PC version. I only have access to android and would like to contribute. How would this be possible without forking the entire git repository if only interested in the android side of things?

**Comment by hrydgard** [comment]
You still need the entire repo, most of the code is shared between the platforms, and is built for all of them. Only a few bits are platform-specific.

**Comment by Rokkest** [comment]
can make destination folder for kitkat or watever, like

setting Internal /PSP

SD card /PSP

like this app https://i.imgur.com/BWT35Z8.png

**Comment by hrydgard** [comment]
That's a possibility, but it seems unrelated to this discussion. Please create a new issue.
