### ISSUE TITLE
Should use the Android Download Manager for homebrew store downloads

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#9700]
Large downloads should be done this way so they can safely happen in the background, and we can get notified when it's done to perform the install.

https://developer.android.com/reference/android/app/DownloadManager.html

**Comment by LoungeKatt** [comment]
https://www.androidtutorialpoint.com/networking/android-download-manager-tutorial-download-file-using-download-manager-internet/

**Comment by hrydgard** [comment]
Not likely to bother doing this. Downloads work okay as they are.
