### ISSUE TITLE
Android hang on file open without storage permissions

### ISSUE THREAD

**Issue by unknownbrackets** [hrydgard/ppsspp#9704]
See #9697 for more details.

---

I guess our two options are:

1. Ignore the parameter, and just show the standard UI prompting for permission and then allowing browse.
2. Show a separate prompt and launch the game after click.

The second is probably the better one.  It feels weird to receive an intent to open a file without having permission to read the file... how do other apps handle?

-[Unknown]

**Comment by InusualZ** [comment]
I have seen a couple of app that ask when they request to read an file that it's `out of bound`. By they I mean the client.

**Comment by hrydgard** [comment]
I'm fine with option 1 as it's a bit of an edge case, usually the first time you start the emulator is not through some file manager (though maybe some users are a little weird :). But yeah, 2 would be ideal.
