### ISSUE TITLE
Metal Gear Solid Peacewalker crashes on S8 Exynos

### ISSUE THREAD

**Issue by sero583** [hrydgard/ppsspp#9708]
I tried so many settings none work.

**Comment by sero583** [comment]
Also off topic, is Vulkan API planned?

**Comment by sero583** [comment]
Ugh saw now that its already in the source files my fault😅

**Comment by sero583** [comment]
Well last question the S8 indeed got Vulkan why can't I select it? Im on v.1.4-g648bc5d

**Comment by hrydgard** [comment]
Because our Vulkan stuff is not good enough yet. Working on it.

Regarding the crash, not really sure, but thanks for reporting.

**Comment by hrydgard** [comment]
Confirmed working (though slow) with the interpreter so it's a JIT bug.

**Comment by hrydgard** [comment]
Rewriting the dispatcher and then returning to it turned out to be a bad idea. Was unable to identify exactly why, but after changing it to not do that when clearing, the problem went away. Maybe parts of it changed size due to smart MOVI2R calls etc. Fix coming up.

**Comment by sero583** [comment]
Ugh I'm not professional programmer like you so I don't really know what some parts mean, anyway so its gonna work thanks!

**Comment by hrydgard** [comment]
I mostly wrote that log for myself, don't worry about it :) 

Yeah, download the newest build from http://buildbot.orphis.net/ppsspp/ or just wait for the update.

**Comment by sero583** [comment]
@hrygard thanks for developing such an amazing emumator! :D
