### ISSUE TITLE
Weird pauses in some homebrew

### ISSUE THREAD

**Issue by LunaMoo** [hrydgard/ppsspp#9711]
Investigated it a bit more, so I think it deserve a separate issue.

Some homebrew might suffer from pauses with random timing affected by something early on which then repeats at constant intervals, along with pauses FPS drops to lower values. Depending on luck pauses might take most of the time with game running at single digit fps, sometimes potentially freezing completely at 0 fps, but also might not happen at all.

Known cases:
- Frontier 1337 - problem starts on homebrew boot
- Wolfenstein 3D - problem starts after game is selected since first it boots into a selection menu which has no issues

Both of those seems to control fps based on passage of time abusing:
```
sceKernelLibcTime
sceKernelLibcGettimeofday
```

What seems to happen is game checks whenever new time is higher than old time by at least 2 before continuing, if it's not, it continues checking until it is which sometimes doesn't happen for a while causing pause/freeze then get's updated by much bigger value at once, why it wouldn't be updated all the time potentially affected on something which happens on game boot - I have no idea:C.

 It weirdly feels like the problem is more often worse when using fast forward/unthrottle and might be easier to avoid when limiting speed and patiently waiting, but it could as well be just random luck.

 Edit: Just noticed, not sure if it's exactly same, but could be a duplicate of #8748.

**Comment by unknownbrackets** [comment]
Does it fix it to change...

```c++
		DoFrameTiming(throttle, skipFrame, (float)numVBlanksSinceFlip * timePerVblank);
```

To:

```c++
		DoFrameTiming(throttle, skipFrame, (float)timePerVblank);
```

I suspect the way this game is doing timing is confusing PPSSPP's frame timing routine, and causing it to think the game is going to lower FPS than it really is.

-[Unknown]

**Comment by LunaMoo** [comment]
Nope, both of those games still have freezes + low "max fps" with that change and just run at few times faster speed.

**Comment by LunaMoo** [comment]
I experimented a bit and changed sceKernelLibcGettimeofday to 
```
	s64 additionalUs = CoreTiming::GetGlobalTimeUs();
	s64 nextUs = additionalUs << 32;
	u32 t = (u32)(additionalUs >> 32);
	u32 t2 = (u32)(nextUs >> 32);

	DEBUG_LOG(SCEKERNEL, "sceKernelLibcGettimeofday(%08x, %08x)", timeAddr, tzAddr);
	hleEatCycles(1885);

	if (Memory::IsValidAddress(timeAddr)) {
		Memory::Write_U32(t, timeAddr);
		Memory::Write_U32(t2, timeAddr+4);
	}

	hleReSchedule("libc timeofday");
	return 0;
```
I can tell it's horribly wrong, but what matters is that it did directly affected the freezes, from somewhat random very common freezes, they turned into much rarer(but also lasting longer) ones, going to check some other day how exactly that affected those freezes, but I guess this confirms we indeed have some problem with sceKernelLibcGettimeofday that causes that:].

**Comment by unknownbrackets** [comment]
Hm, theoretically that would make 20 hours pass per frame - unless the return value of the struct is entirely incorrect.

It doesn't look like there's an actual test for this function yet:
https://github.com/hrydgard/pspautotests/search?utf8=%E2%9C%93&q=sceKernelLibcGettimeofday&type=

Possibly the important thing is the tz parameter:
https://github.com/jpcsp/jpcsp/blob/79086c2dc741088818624d47a275a393060cee9b/src/jpcsp/HLE/modules/UtilsForUser.java#L337

-[Unknown]

**Comment by unknownbrackets** [comment]
Maybe we should compare a JpcspTrace of the sceKernelLibcGettimeofday function calls to see if the timing or space of return values is wildly different.

-[Unknown]

**Comment by LunaMoo** [comment]
I think one thing I should put more effort into figuring out is why sometimes the problem doesn't happen at all ~ I mean even if the time function get's buggy, what factor would be different each time the emulation is restarted that would be making the difference here.

 Maybe it's actually the other time syscall used there(sceKernelLibcTime) as it add's "start_time" which would be different each run, but same until emulation is restarted, that would match how the issue behaves.

**Comment by unknownbrackets** [comment]
Does it help if `start_time` always starts at zero?

Maybe there's some bug happening based on the partial seconds (i.e. milliseconds/microseconds) of start_time....

-[Unknown]

**Comment by LunaMoo** [comment]
No luck, I tried to not add it at all and even forcing it to value that was used when game is running fine and the problem was still randomly occuring or not.

 I tried comparing debug logs when freezes happen and when they don't, but I can't catch "don't happen" part for debug log;p, might be possible that while I was messing with the game in disassembly some breakpoints(which I tend to abuse a lot using them as bookmarks:]) affected something allowing the game to ocassionally boot properly, or it's just rarer than I would hope. I could however compare the debug log from workind poorly(~ 20fps) and working terribly (~ 2 fps, more paused than not:P), and the only differences in the log started soon after using time functions for the first time.

When the problem results in ~ 2fps:

```
00:03:608 idle0        D[SCEKERNEL]: HLE\sceKernelThread.cpp:30 Context switch: user_main -> idle0 (276->272, pc: 0886883c->08000000, interrupt) +16475us
00:03:608 user_main    D[SCEKERNEL]: HLE\sceKernelThread.cpp:30 Context switch: idle0 -> user_main (272->276, pc: 08000000->0886883c, idle) +731us
00:03:613 idle0        D[SCEKERNEL]: HLE\sceKernelThread.cpp:30 Context switch: user_main -> idle0 (276->272, pc: 088685dc->08000000, interrupt) +15951us
00:03:617 user_main    D[SCEKERNEL]: HLE\sceKernelThread.cpp:30 Context switch: idle0 -> user_main (272->276, pc: 08000000->088685dc, idle) +219us

```
and when it's slightly more bearable:
```
58:58:296 idle0        D[SCEKERNEL]: HLE\sceKernelThread.cpp:30 Context switch: user_main -> idle0 (276->272, pc: 0886883c->08000000, interrupt) +16475us
58:58:308 user_main    D[SCEKERNEL]: HLE\sceKernelThread.cpp:30 Context switch: idle0 -> user_main (272->276, pc: 08000000->0886883c, idle) +202us
58:58:313 idle0        D[SCEKERNEL]: HLE\sceKernelThread.cpp:30 Context switch: user_main -> idle0 (276->272, pc: 088681b4->08000000, interrupt) +16480us
58:58:325 user_main    D[SCEKERNEL]: HLE\sceKernelThread.cpp:30 Context switch: idle0 -> user_main (272->276, pc: 08000000->088681b4, idle) +219us

```
 Longer diff of those context switches on [gist](https://gist.github.com/LunaMoo/7468e0a91b361454e64b4b9e112eedbc), but it doesn't seem like anything interesting.

 While I was looking at it I managed to run the game near full fps(32) and full(35 fps ~ confirmed by homebrew source) short time after another, but the latter also froze with 0fps after final loading screen, kind of like it wasn't trully random, but progressing with time, it's possible it saves a time during loading screen or when booting that's then get's used as a part of the whole time/fps mess which is why it doesn't change in-game>.>.

**Comment by hrydgard** [comment]
Hm. Starting to suspect edge case bugs in CoreTiming...

**Comment by LunaMoo** [comment]
@hrydgard saw my edit?(should have just new post it I guess) I think this will be easily fixed by not rounding time:].

**Comment by LunaMoo** [comment]
I see the problem now __RtcTimeOfDay used for sceKernelLibcGettimeofday is adding CoreTiming::GetGlobalTimeUs() + usec of rtcBaseTime divided by 1000000, sceKernelLibcTime is just adding CoreTiming::GetGlobalTimeUs() divided by 1000000.

 So we either have to not add those usec in __RtcTimeOfDay  or add it also in sceKernelLibcTime. Which solution is more proper?
