### ISSUE TITLE
Multithreading issues

### ISSUE THREAD

**Issue by zminhquanz** [hrydgard/ppsspp#9712]
When i'm playing Persona 3 , when i run at single core mode and enable multithreading , it's improvement speed , but when i start game after enable multithreading , it slower speed , and disable multithread ( single core mode ) it normal

**Comment by unknownbrackets** [comment]
Part of the problem is that your graphics driver makes guesses, and whether we run the CPU on a separate thread or not influences these guesses.

There might also be a bug, but we're probably going to (eventually) remove and replace the multithreading with a different approach.

-[Unknown]

**Comment by zminhquanz** [comment]
When Multithreading was rewrite , after 1.4.1 release ??

**Comment by zminhquanz** [comment]
@unknownbrackets Is multithreading remove in next 1.4.2 version ?
