### ISSUE TITLE
MEMSIZE flag not respected in homebrew(?)

### ISSUE THREAD

**Issue by LunaMoo** [hrydgard/ppsspp#9719]
Tried to check that Quake II port homebrew for other issues, and it's currently crashing due to lack of memory despite having MEMSIZE flag set to 1, as can be seen:
![quake 2 memsize](https://cloud.githubusercontent.com/assets/5485237/26392815/2885d96e-4068-11e7-94e0-e168d4f54734.jpg)
In case the location matters, it's PARAM.SFO is packed inside memstick\PSP\GAME\QuakeII\EBOOT.PBP.
Extracted PARAM.SFO looks ok I guess - 
![quake param](https://cloud.githubusercontent.com/assets/5485237/26392994/b81e64ce-4068-11e7-936a-98a63567a60f.jpg)

When it comes to MEMSIZE, it certainly does work fine with commercial games, that is while using ISO, not sure why it fails with homebrew.:]

**Comment by unknownbrackets** [comment]
Is it not reaching here?  https://github.com/hrydgard/ppsspp/blob/2c6161c2cf03daa3cc60841e5a7d8a7832aa9a3c/Core/PSPLoaders.cpp#L151

-[Unknown]

**Comment by LunaMoo** [comment]
It wasn't reaching to neither of the two MEMSIZE checks there, and yeah it goes through PSP_PBP_DIRECTORY then to Load_PSP_ELF_PBP which doesn't have MEMSIZE check.
