### ISSUE TITLE
Remaining problems with identifying homebrew

### ISSUE THREAD

**Issue by LunaMoo** [hrydgard/ppsspp#9724]
Just a list of things that would be nice to handle better in some potentially distant future:
 - per game settings,
 - texture replacement,
 - compatibility settings,
 - normal screenshots.

 Maybe also for cosmetic stuff like:
 - window titlebar,
 - game info screen(replacing the common Loco Roco ID).

 Potentially forgetting about something.

 Kind of wonder if those could be reduced together with savestates and cheats(which handle it separately) into one common function as those features are spread all around:].

**Comment by hrydgard** [comment]
Well, it all comes down to the issue of there not being any safely unique ID to use with homebrew. I suppose we could take the first 9 characters of the folder name and pretend it's a normal game ID though, but it won't be unique across machines as people sometimes rename stuff etc.

**Comment by LunaMoo** [comment]
Made a fakeID function which generates ID based on the folder name:
![titlebar fakeid](https://cloud.githubusercontent.com/assets/5485237/26507124/3deabb9c-424f-11e7-897b-864e0c3e1e21.jpg)
Only experimenting for now, so picked the quickest thing to check - titlebar, ID is basically first 4 letters(uppercase) of folder name, if the name is shorter than 4 it add's "HOME" before reducing to 4, then the number is sum of all characters in the folder name. Seems fine so I'll work more on that, hopefully can get folder name everywhere where ID is needed.

**Comment by hrydgard** [comment]
Yeah, I guess that's fairly reasonable :)

**Comment by unknownbrackets** [comment]
Hmm, I'd worry about overlap.  Is anything dependent on the digits?  I can imagine the length might matter some places...

-[Unknown]

**Comment by LunaMoo** [comment]
I don't think homebrew will be in any case detected as other games, you would have to specially find a name that results with both prefix and number from combined sum to match some real game ID. There are no homebrew named like that:]. Anyway I opened a PR with what I did for now.

**Comment by ThePhoenixRises** [comment]
How about a renaming function that we can click on, and displayed on the Sub menu, found here:
![screenshot_20170527-175120](https://cloud.githubusercontent.com/assets/6565304/26523056/dbeb3338-4305-11e7-92d3-e9170d1493cd.png)
That way we can rename it to whatever we wish, also was thinking of long pressing the icon with ? to select a different icon from our images / pictures folder, to improve the look of the homebrew.

**Comment by LunaMoo** [comment]
Renaming/Changing icon should be requested as separate feature, it's not related to emu functions not working for homebrew and should also not be limited to homebrew either.

 Imo it's not even that useful, changing text is just whatever, most people doesn't even know of that screen existence and while missing icons look bad on the list, once we have gameID for everything, we can just try to use first screenshot before ending up with question mark/unknown icon, in fact I just added that to my pr:].

**Comment by ThePhoenixRises** [comment]
Thanks for reply LunaMoo, as I don't usually get a reply, so makes a change!
