### ISSUE TITLE
What going on ? PPSSPP app was missing on Google Play

### ISSUE THREAD

**Issue by zminhquanz** [hrydgard/ppsspp#9734]
I will update to 1.4.2 , but this app is missing , i force go on website to download APK file , it is uncomfortable

**Comment by hrydgard** [comment]
Some overeager app reviewer bumped it, I don't understand why. I've appealed and hopefully it will be back soon.

**Comment by hrydgard** [comment]
There's been progress. Stay tuned...

**Comment by hrydgard** [comment]
... aannd we're back!

https://play.google.com/store/apps/details?id=org.ppsspp.ppsspp
