### ISSUE TITLE
Danball Senki Boost - Character body dissapear. Since : v1.3-703

### ISSUE THREAD

**Issue by Saramagrean** [hrydgard/ppsspp#9740]
My device : Samsung J2 Prime
Spec : CPU - MediaTek MT6735 , GPU - Mali-T720, Ram - 2 GB., OpenGL ES 3.1, Android 6.01
PPSSPP Settings : default

Last work : v1.3-699-g40e414c

First break : v1.3-703-g31dd8fd

I tried to test latest version 1.4.2 but same issue.

Thanks. :)

![screenshot_20170530-171226](https://cloud.githubusercontent.com/assets/26355472/26578725/46454f32-455b-11e7-8ad9-855f60e78d6b.png)

**Comment by unknownbrackets** [comment]
@hrydgard https://github.com/hrydgard/ppsspp/compare/40e414c...31dd8fd

Does this mean we're copying stencil when we blit depth?  Could be the cause of this issue.

-[Unknown]

**Comment by hrydgard** [comment]
Hm, this is interesting. Blit lets us copy depth and stencil separately while Copy doesn't seem to allow that. I think that's a plausible theory.

**Comment by unknownbrackets** [comment]
I think it's more than plausible: `glCopyImageSubData` doesn't take any flags, it just takes the renderbuffer name.  In contrast, `glBlitFramebuffer` can take `GL_DEPTH_BUFFER_BIT` and `GL_STENCIL_BUFFER_BIT` separately.

 So `glCopyImageSubData` must copy the entire framebuffer, depth and stencil included.

-[Unknown]

**Comment by hrydgard** [comment]
Alright, so we'll just need to disable the CopyImageSubData path when stencil copy bit != depth copy bit.
