### ISSUE TITLE
Post process shaders broken since #9713

### ISSUE THREAD

**Issue by LunaMoo** [hrydgard/ppsspp#9742]
Glitches are various, in here screen is doubled and bottom copy is flashing:
![glitches](https://cloud.githubusercontent.com/assets/5485237/26587309/3c332856-4552-11e7-895e-64e0b1ed3409.jpg)
can differ per game.
Nvm about pre-vulkan hardware, I just had disabled post process in games I tested on my vulkan hardware, they're glitched on both of my systems;p.

**Comment by hrydgard** [comment]
That's a very categorical statement, how much hardware do you have to test on? :)

But alright, some regressions are expected from a big refactor like that (it was really required if we're gonna do Vulkan properly) so yeah, this needs debugging.

**Comment by LunaMoo** [comment]
Oh wait, yeah I think the statement was wrong:P, it must be something in my config as it got fixed when I started from new folder. Going to see if I can find what, hopefully it's nothing that should work:].

**Comment by hrydgard** [comment]
Ah! Okay, will look at that soon.

**Comment by hrydgard** [comment]
Okay, that was easy, I think. Can't repro on GL at least with that.

**Comment by hrydgard** [comment]
Still broken with D3D11 but progress I guess :)

**Comment by LunaMoo** [comment]
:P you're too fast, I started looking for it before figuring out it's with my settings and went nowhere.

**Comment by hrydgard** [comment]
Well, I knew what changed in the refactor, and it had to be somewhere around there :)  Not sure why it didn't fix D3D11 though. Will look into it later.

**Comment by LunaMoo** [comment]
Seems like scaling shaders are still broken in OGL. Those were problematic in d3d11 due to some uniforms passing inaccurate data, maybe it's related.

**Comment by hrydgard** [comment]
How about now? Also can't repro the problems I had with D3D11, strange.

**Comment by LunaMoo** [comment]
Yup, works great, thanks.

 Also tested - the HLSL precision workaround(+ 0.000001 to coords in some effects) seems to no longer be needed:).
