### ISSUE TITLE
Post-processing shaders not implemented for the Vulkan backend

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#9743]
This should be pretty easy, some more shader translation tricks with SPIR-V / glslang / spirv-cross. The latter has improved quite a bit since I added the original D3D11 post proc stuff so we can improve that to a cleaner way now.

**Comment by brujo5** [comment]
cool. just tested vulkan api in my one plus3t and galaxy s6 edge and work smooth af. been waiting for this long time. 
thank you.
