### ISSUE TITLE
Intel iGPU OpenGL only instant crash

### ISSUE THREAD

**Issue by pal1000** [hrydgard/ppsspp#9744]
Since #9713.
System:
Intel Core i3-2375M 1.5 Ghz 4 threads, Intel HD Graphics 3000.
A system incapable of Vulkan support.
Windows 10 Version 1703.
4GB DDR3 RAM,
It appears there is some change the graphics driver doesn't like as llvmpipe isn't affected.
With fresh copy crash occurs before ppsspp.ini creation.

**Comment by hrydgard** [comment]
Hm, interesting, I don't recall changing much around OpenGL init...

**Comment by unknownbrackets** [comment]
Could be related to #9751 (both using OpenGL < 3 perhaps)?

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, very likely.

**Comment by pal1000** [comment]
Confirmed fixed.
