### ISSUE TITLE
Software skinning not working properly in Vulkan

### ISSUE THREAD

**Issue by supermilleno** [hrydgard/ppsspp#9753]
![capture _2017-05-31-19-04-29](https://cloud.githubusercontent.com/assets/29108634/26657798/1f76aab6-4634-11e7-96b8-4213a5400e4d.png)

![capture _2017-05-31-19-07-20](https://cloud.githubusercontent.com/assets/29108634/26657848/6d7ad8ea-4634-11e7-96a7-a9196b275bbd.png)

I'm using an LG G6, and on the latest build (1.4.2-81) with Vulkan Project Diva Extend and Project Diva 2nd display these weird models. This wasn't a problem when I was using 1.4.2-46. I tried turning off a 60fps cheat, and it didn't change anything.

The actual performance is not that much different from previous versions, and Vulkan seems to work a bit better than OpenGL, although on both backends my device seems to slow down drastically after a few minutes.

**Comment by hrydgard** [comment]
Turn off software skinning, it doesn't work correctly currently.

**Comment by hrydgard** [comment]
I hijacked this issue to reflect the wider problem.

**Comment by hrydgard** [comment]
No, I said I hijacked this, the issue is definitely not fixed yet :) Reopening.

**Comment by supermilleno** [comment]
oops sorry!
