### ISSUE TITLE
The 3rd Birthday bloom effect

### ISSUE THREAD

**Issue by magimagica** [hrydgard/ppsspp#9759]
Test build: v1.4.2-81-g7001b84-windows-x86
Test mode: Direct3D9
Graphics setting: Default, at x2 resolution
Bug: 
![ulus10567_bug1](https://cloud.githubusercontent.com/assets/11667484/26670884/b14ab1d6-46dd-11e7-9625-c50fb558a563.jpg)

![ulus10567_bug2](https://cloud.githubusercontent.com/assets/11667484/26670906/c0a5fb9a-46dd-11e7-8839-a57ab7c57f23.jpg)
 
 
 
Last known good build: v1.2.2
![ulus10567_fix1](https://cloud.githubusercontent.com/assets/11667484/26670930/dd0d8154-46dd-11e7-8896-7709214fb1e6.jpg)

![ulus10567_fix2](https://cloud.githubusercontent.com/assets/11667484/26670935/e39bfb68-46dd-11e7-9534-aa2af84665b2.jpg)

Btw, the F12, screen shot shortcut, doesn't work in latest build.

nb:
Same fix applied to Ys Seven, where v1.2.2 is the good known build where its map is showing instead of black like this
![ys](https://cloud.githubusercontent.com/assets/11667484/26671018/3a2ec442-46de-11e7-9ffb-f3f978b86d4d.jpg)

**Comment by magimagica** [comment]
Enabling "Disable slower effects" will disable bloom effect completely.
Changing rendering mode to Read to memory, will make the bloom effect back to it's place near the object/character, but causes another artifact.

**Comment by LunaMoo** [comment]
To avoid it being closed too quickly - this doesn't seem to be the usual bloom broken with high render res, at least for 3rd Birthday d3d9 goes mental with drawing it, looks like coords are swapped(using some ogl code?).

**Comment by unknownbrackets** [comment]
Did this work in v1.4.0?  v1.2.2 to v1.4.2-81-g7001b84 is a big range.

-[Unknown]

**Comment by magimagica** [comment]
Hello sir unknownbrackets
Like I said in previous post, the last good known version that's works is v1.2.2
So from 1.3 to latest is bugged.

**Comment by unknownbrackets** [comment]
http://buildbot.orphis.net/ppsspp/index.php?m=fulllist

What about v1.2.2-483-gd6c2b6e?  Does it work?  If you test by halves from v1.3.0 to v1.2.2, you can find the one that broke it in about 9-10 tries.  Then we'd know exactly what change broke it.

-[Unknown]

**Comment by magimagica** [comment]
Alright, let me check them

**Comment by magimagica** [comment]
Sorry, looks like I mistook the version that is bugged.

Here is report from what I tested:
v1.3 = Fine, like the ss
v1.3-301-g47283db = Fine, like the ss
v1.3-515-g96c450e = Fine, but character missing its bloom effect, object like PC in ss is okay, though the bloom look shaking when I move.
v1.3-705-gb94ad12 = same as v1.3-515-g96c450e
v1.3-851-gcfb93a7 = Missing all bloom effect
v1.3-1133-g576c1b7 = Bugged like the ss
v1.4 = same as v1.3-1133-g576c1b7

**Comment by hrydgard** [comment]
Is this still an issue? Only in Direct3D9?

**Comment by DmdHoH000** [comment]
Hello i can confirm for the 3rd birthday the issue is gone
![ulus10567_00000](https://user-images.githubusercontent.com/44216669/52488911-177bcc00-2ba8-11e9-90cc-ee1773ba3d55.png)

**Comment by hrydgard** [comment]
thanks for testing!
