### ISSUE TITLE
software renderer regression for ridge racer (us)

### ISSUE THREAD

**Issue by spring568** [hrydgard/ppsspp#9761]
It'll now crash the entire emulator while trying to complete a race and the road looks quite a bit worse. Before the road polygons would disappear that would get close to the players view (maybe a depth issue? I dunno), but now they turn black and have a warping effect on them in addition to that. It doesn't happen in my g42a6943 build so it probably has something to do with changes after that

OS: win 10 64bit
render: Opengl software
build rev: g7822e5b

Edit: I attached some images. Sorry about it being a window capture, but the screenshot feature would cause a crash
![g42a6943](https://cloud.githubusercontent.com/assets/27930237/26691127/e29dec94-46b0-11e7-8bd3-0d82e31fac57.jpg)
![g7822e5b](https://cloud.githubusercontent.com/assets/27930237/26691137/ec68a296-46b0-11e7-9c32-8d83ef44e978.jpg)

**Comment by unknownbrackets** [comment]
The road issue is #9622, but the crash is a typo.

-[Unknown]

**Comment by spring568** [comment]
The crash fix also fixed the black lines on the road textures so I'm going to assume it was related. It's also pretty nice seeing you work on ppsspp again too! thanks for all your hard work : )

**Comment by unknownbrackets** [comment]
Ah, you're right - I was still seeing a lot of issues with the road, but some of it was caused by that bug.

-[Unknown]
