### ISSUE TITLE
Better combo keys request

### ISSUE THREAD

**Issue by i30817** [hrydgard/ppsspp#9762]
There are quite a few annoying games that use the d-stick in 'kicktime' events (for example, obscure the aftermath is one). Even if a general macro of combo keys over time is not in the cards, i'd like to request two special combo option to continuously circle right and left the d-pad as close to possible to the optimum circle, for as long as the button is pressed so that these and other can be easily be circumvented. 

It's all fun and games until you're playing with a keyboard and even the on-screen touch controls with a mouse aren't precise enough, or you're old enough for your fingers to ache with this bad design.

I don't actually know of another extremely bad combos i'd like to have a preset on the psp, these two are honestly the worst i remember, the situation is not nearly as bad as the wii in terms of controller gimmicks fortunately.

Although, that said, this game also has other 'simon says' minigames using a single key pressed on a timer that would probably benefit from a combo macro creator, it's just that the d-pad wraggle seems very difficult to make it on such a hypothetical thing since it's all continuous, and it seems very popular since it's the most straightforward 'skill' quicktime event control on the psp.

**Comment by i30817** [comment]
BTW, if anyone is looking for a solution of this bad design of bad games, i have a simple linux hack with a tool to control the mouse... might not work in the successor of X (forgot the name) though.

use this on the shell. Your mouse will circle obviously, but you can still move it a bit and click (do it on the d-pad when touchscreen controls are enabled. The increment number controls speed.

`rad=0; while true; do xdotool mousemove --polar $rad 80; rad=$((rad+5)); done`

**Comment by ResurrectionRedmi9** [comment]
This should improve by https://github.com/hrydgard/ppsspp/pull/13869

**Comment by hrydgard** [comment]
We have the circle ones yeah, I don't know if there's more that needs to be done here. closing.
