### ISSUE TITLE
Error when i transfer DLC and play Project Diva Extend

### ISSUE THREAD

**Issue by zminhquanz** [hrydgard/ppsspp#9764]
![image](https://cloud.githubusercontent.com/assets/11285640/26708397/c1fd8eca-4775-11e7-80df-320703101a5b.png)
I can't transfer DLC data in Project Diva Extend

**Comment by zminhquanz** [comment]
@unknownbrackets @hrydgard

**Comment by zminhquanz** [comment]
And it's stopped working when i started game since update 1.4.2

**Comment by unknownbrackets** [comment]
Great to hear this is working, I'll close for now.  If it's still happening, we can reopen.

It might be specific to certain regions of the game or DLC, though, but hopefully it was just a bug that's been fixed.

-[Unknown]
