### ISSUE TITLE
Vulkan crash by changing resolution

### ISSUE THREAD

**Issue by sero583** [hrydgard/ppsspp#9765]
On my S8 (Exynos) I tried Vulkan and it has small rendering bugs (I changed in the .ini file it to tje constant value 3 so it was set to it) but I think you know about those but thats not the point (like for example in DBZ tag team characters arent drown proper and glitched and only some kind of it but it also fixes the OpenGL rendering bugs on my device when using DBZ Shin Budokai another road (2)), the real issue is you may not know about when you change resolution during playing and pressing on continue on the pause menu it crashes

**Comment by brujo5** [comment]
To bad the s8 exynos have serious drivers bug and there is not fix from ARM devs.
Vulkan not work property in Mali GPU.

I just tried those games games in adreno 530/540 and work perfectly

**Comment by hrydgard** [comment]
DBZ Tag Team needs more work to, well, work on Vulkan, it uses some tricks that are not implemented yet. There's more work to be done on Vulkan so bugs you see can either be my fault or driver bugs, but so far for me the Exynos seems to behave mostly as expected. But we'll see.

Crash on resize is definitely a bug on our side which needs fixing, not a driver bug.

**Comment by hrydgard** [comment]
Should be fixed now. Please reopen if not.
