### ISSUE TITLE
PPSSPP Sound problem (no sound) [Android]

### ISSUE THREAD

**Issue by Saramagrean** [hrydgard/ppsspp#9771]
I tested on My device Android (Samsung Galxy J2 & J2 Prime) ...PPSSPP Since v1.4.2-66-g7bfccfb all games that play no sound at all. but on My PC (Windows 10 64 bit), the sound comes in normally well. 

Thank you in advance. :-)

**Comment by unknownbrackets** [comment]
So to confirm, v1.4.2-66-g7bfccfb has no sound, and if you reinstall v1.4.2-64-geff60ca, it has sound?

-[Unknown]

**Comment by hrydgard** [comment]
Sounds odd. (hah). Though there were some initializaton changes in 66 so it's not entirely implausible that it's that. Will investigate tomorrow.

**Comment by Saramagrean** [comment]
Yes. I comfirm 66 no sound (on both my device j2 & j2 prime). 64 sound is normlly, Sir.

**Comment by Saramagrean** [comment]
Opps!, Today i try install latest build and reinstall v.1.4.2-66 again. Sound is normally fine. :p Maybe it's my own mobile that has problems.

Sorry to waste time. Thanks for helping. :)

**Comment by Saramagrean** [comment]
Sorry, reopen again sir.

My friend's device Huawe P9 Plus found the same issue on latest build. 

Thanks.

**Comment by Saramagrean** [comment]
More details: 

After install PPSSPP first time, then Give permission (is stuck), and start game. sound is comes to normal fine. but when enabled Immersive mode > exit PPSSPP > open PPSSPP after that start game again, Game does not sound at all.

Change backend to vulkan (while in game) >  app crash > Open PPSSPP, sound came back to normal. 

Here my test clip: https://youtu.be/9tIrEdXlc14

I tried the old version of ppsspp. This problem began to occur from 1.4.2 build 66 onwards. 😀

**Comment by adenovan** [comment]
Some friend reported to me the sound is gone after he tap exit on the main screen. 

The sound is fine on the first app run. But after tapping exit he need to clear cache or force stop ppsspp from Android app settings to make it work again. 

This issues occured on Android 7.1.1 and 6.0.1 also

**Comment by hrydgard** [comment]
Yep, I'm aware. Fix coming soon, I think I know what it is.

**Comment by hrydgard** [comment]
Just merged a change that might help.

**Comment by Saramagrean** [comment]
Still the same, sir. 😂

**Comment by hrydgard** [comment]
Hm, ok. Thanks for testing, anyway..

**Comment by mpamxl** [comment]
I've been waiting for fix...

**Comment by hrydgard** [comment]
Just for reference, the culprit commit is apparently: https://github.com/hrydgard/ppsspp/commit/7bfccfbb132a8c9697b759a8ba582a16505bc597 .

With this, we no longer exit(0) the process in NativeShutdown on Android, but instead live on and might get re-used if the app is started again, so we might end up starting with not all globals cleared. There might be some driver bug that doesn't like starting up OpenSL again, or we are accidentally relying on some global state we shouldn't... But if it was the latter I'd expect all devices to be affected and they clearly aren't. Weird.

**Comment by Saramagrean** [comment]
When start app sometime (after granted permission in first time), PPSSPP dose not create file ppsspp.ini 😐

**Comment by hrydgard** [comment]
Hm, does that cause any problems? It should be able to create it later when you change settings or the next time you start the emulator after granting permissions.

**Comment by hrydgard** [comment]
Just managed to repro this and it turns out that in the same sessions, menu sounds work. So it's got nothing to do with OpenSL initialization. Digging...

**Comment by hrydgard** [comment]
(not that commit)

**Comment by Saramagrean** [comment]
OK, I understood. 
Thanks for explanation.  😀

**Comment by hrydgard** [comment]
So, this mainly happens when you start, exit using the Exit button, and then relaunch. I don't notice this normally since when developing I always do a full restart.

It seems the state of the StereoResampler gets messed up and it starts producing only zeroes in this case. Investigating.

**Comment by hrydgard** [comment]
More notes to self: There's a bug where __PushExternalAudio gets called with zero buffer even if ingame, resulting in clearing the audio buffer which is not good.

**Comment by hrydgard** [comment]
Sigh, seems the UI state got stuck in EXIT, causing that behaviour. Fixing.

**Comment by hrydgard** [comment]
This should be completely fixed now - if not, please re-open.

**Comment by Saramagrean** [comment]
Nice Work!!  👍
