### ISSUE TITLE
winning eleven 2014 black grass problem on v1.4.2-120-g0f5c59d

### ISSUE THREAD

**Issue by Rokkest** [hrydgard/ppsspp#9775]
I think v1.4.2-120-g0f5c59d have no mip map or in oldupdate {2mount} its fine thanks 🙏 [on same system setting.ini]

Info:

Version: 0.48.4
Language: en
layout:     
Mode: 1
App: com.UCMobile.intl
Android: 6.0.1
Model: ASUS_Z007
Manufacturer: asus
ID: KVT49L

🏃

**Comment by Rokkest** [comment]
Fix use v1.3[2016] if mipmaping is ✔ enable
delete old system_urgame.ini & set again or disable mipmaping
because on v1.4 its gone
thanks ╾━╤デ╦︻ 🙏

**Comment by hanooty** [comment]
I have also this problem in pes 2017.iso
Black screen in some textures like grass, crowds, nets...
Any solution brothers? ???

**Comment by benderscruffy** [comment]
cant reproduce any off the problems
should be closed

**Comment by unknownbrackets** [comment]
Possibly this was related to the slope mipmapping functionality.  I think it needs more work, but it was worse before.  Thanks for retesting.

-[Unknown]
