### ISSUE TITLE
PPSSPP game slows down.

### ISSUE THREAD

**Issue by cloud9350** [hrydgard/ppsspp#9778]
Device : Samsung Galaxy S7 Edge (Exynos)
Android : 7.0 / Stock firmware
PPSSPP Version : 1.4.2v stable
Step by step reduce
1. First, run 60FPS game (God of war, etc..)
2. Wait for second..
3. Game is now slowly..
Video (1080p 60fps video): https://www.youtube.com/watch?v=NarBqdW3z04

**Comment by hrydgard** [comment]
Does your device also get hot? Sounds like power throttling to me.

When #9738 is implemented, you might want to try it to get a slightly lower but more sustainable performance.

**Comment by cloud9350** [comment]
@hrydgard Can you play this video?
https://youtu.be/rs4V2j0Dcn0

**Comment by hrydgard** [comment]
I see it. I don't think it's PPSSPP's fault though, it has to be some kind of power management thing in the OS... We don't deliberately slow things down like that.

**Comment by Michal1324** [comment]
You could try lastest ppsspp and use vulkan if it works fine without few calls

**Comment by cloud9350** [comment]
@Michal1324 Now working. (Use Vulkan)

**Comment by unknownbrackets** [comment]
Okay, will close.  Most likely Vulkan is just using less CPU, and therefore your phone is doing less to slow things down and keep the device from burning up.

-[Unknown]
