### ISSUE TITLE
Launching EBOOT from command line gives relative path errors, segfault

### ISSUE THREAD

**Issue by wickles** [hrydgard/ppsspp#9785]
I like to run from the command line for quick dev testing, so usually I do something like `ppsspp ./EBOOT.PBP` (sometimes had issues with `ppsspp EBOOT.PBP`). I'm using the version built by MacOS Homebrew so I guess the bin `ppsspp` would otherwise be called `PPSSPPSDL`. 

AFAIK this worked fine for me in version 1.3 and 1.4.0. But it doesn't seem to be working anymore in version 1.4.2, where I now get a bunch of errors like:
```
26:28:300 user_main    E[FILESYS]: FileSystems/MetaFileSystem.c RealPath: inPath "/sound.wav" is relative, but current directory is empty
26:28:300 user_main    E[SCEIO]: HLE/sceIo.cpp:1375 SCE_KERNEL_ERROR_NOCWD=sceIoOpen(/sound.wav, 00000001, 000001b6) - no current working directory
26:28:314 user_main    W[FILESYS]: FileSystems/MetaFileSystem.c Path is relative, but current directory not set for thread 276. returning 8002032C(SCE_KERNEL_ERROR_NOCWD) instead.
```
Complete log here: https://gist.github.com/wickles/26c6e35e627b5d395b138b2c8d2fb684

This was a handy workflow so it would be nice to get fixed (or figure out if it's just me doing something dumb).

**Comment by unknownbrackets** [comment]
Does it work again if you revert 6e83ef0a1bbe8fb4f9be96259fd401e67964d9aa?

It may be the lack of a / in that "umd0:"...

-[Unknown]

**Comment by hrydgard** [comment]
We now require that homebrew reside in a directory under Memstick/PSP/GAME, as they are on the real PSP, which fixes other issues. Not sure if there's a good way to make all homebrew happy from any directory..

**Comment by i30817** [comment]
Speaking of that, i noticed that my cave story+ mod eboot doesn't start the game now if started from outside of the  ~/.config/ppsspp/PSP/ folder like it did before. 

It's a pain to have all games on a filesystem and 'those single homebrew games' not work because of this. Granted, it's quite likely that it wouldn't work anyway (because i'm planning to store/use that cave story folder in a read-only filesystem later, along with the other games).

Is there any alternative to requiring the user to copy, for example, copying the folder with a eboot to the right dir; or transparently replacing the folder to 'appear as if it was on the PSP filesystem on the right place' with a virtual filesystem?

**Comment by wickles** [comment]
@unknownbrackets Yes it works after reverting https://github.com/hrydgard/ppsspp/commit/6e83ef0a1bbe8fb4f9be96259fd401e67964d9aa.

**Comment by unknownbrackets** [comment]
@hrydgard I guess the good way would be:

1. Make sure MetaFileSystem supports "overlapping" mount points, choosing the longest match first.
2. Mount the EBOOT's containing directory as "ms0:/PSP/GAME/something/" where "something" is the containing directory's basename.
  -> Note: this might actually hide a real dir, but that's fine.
3. Run as normal, as if the game were really in ms0:/PSP/GAME/something/EBOOT.PBP".
4. A few things might not work, like listing the ms0:/PSP/GAME dir, but working around that gets really hacky, and it's probably pretty unlikely.

That wouldn't handle the case where the homebrew tries to access something in a parent directory (say `../assets/foo.png`), but it would probably handle the common case.

Headless (for unittests) actually already has a -r option that specifies a root for parent directory handling.  We could extend it to you could end up with `PSP/GAME/something/bin/EBOOT.PBP` and `../assets/foo.png` would work.  Or something like that.

-[Unknown]
