### ISSUE TITLE
Ppsspp crash when launched 

### ISSUE THREAD

**Issue by brujo5** [hrydgard/ppsspp#9786]
Ppsspp crash when launched since https://github.com/hrydgard/ppsspp/commit/871260fcc4db07d85897ecaac4d568f2e00db17c

Last build working ppsspp-v1.4.2-165-g705499c

Tested in galaxy s6 edge

**Comment by unknownbrackets** [comment]
I've regenerated the latest build with the fix - make sure the apk is 24576399 bytes.  It will also be fixed for all future builds, i.e. when #9784 and #9783 are merged.

-[Unknown]

**Comment by brujo5** [comment]
Thanks work perfectly.
