### ISSUE TITLE
PPSSPP emulation is lagging when audio backend is turned on

### ISSUE THREAD

**Issue by Terrarian51** [hrydgard/ppsspp#9787]
I was noticed a strange behaviour of emulator with audio backend. The emulation is running just excellent, except one minor thing: if the audio system is turned on, it's causing minor lagging in anything game, and underrun counter freezes on the place (is this all good?). But, the emulation begins to work just flawlessly when i turns off the audio. In this case, the underrun counter starts counting again. Also, PPSSPP begins to lag insanely, if I'm forcing emulation to stop through the Dev menu. This is pretty strange issue.
My system specs is:
Notebook Acer Aspire 5750G, Intel i3 with 2.1 GHz and 3 GB RAM DDR3, Nvidia GeForce GT540M 1 Gb onboard, new HDD 500 Gb Hitachi TravelStar, OS is Windows 7 x64.
This is a pretty good machine for gaming.
This issue will be solved soon, I hope.
Sincerely, Terrarian51

**Comment by Hydroque** [comment]
Have you tried all the options in the audio menu?

**Comment by Terrarian51** [comment]
Yes, I have tried all of them. There is no difference between anything of three audio backends. Changing of audio latency don't took any effect for gameplay lags. Also, speed hack enabling can't changed anything too.

**Comment by unknownbrackets** [comment]
Underruns are a bad thing: it means there's not enough audio data.  Of course, when audio is disabled, this happens.  It's a good thing when the underrun counter is frozen in place - that means you're not dropping audio frames.

Not sure what's causing the performance issue when audio is enabled.  You don't have any recording software or other audio related software installed/running, do you?

-[Unknown]

**Comment by Terrarian51** [comment]
Well, I have installed Dolby Advanced Audio v2 into my W7 system, along with Realtek Audio Driver is installed too :). But I don't think what the DAA program is causing any lags within the PPSSPP's emulation process.
Hey, buddy, I know, what this emulator's issue was described a lot of times already, and you can find tens of topics all around the Internet. However, this issue remains unsolved. Is this pretty strange thing, isn't it?

**Comment by Terrarian51** [comment]
I'm closing the topic because a cause of an issue was found by the community.

**Comment by unknownbrackets** [comment]
What was the issue?  Maybe someone else will have the same problem.

-[Unknown]

**Comment by Terrarian51** [comment]
[Unknown], this issue is including choppy sounds, which you can hear during the gameplay process. This sounds was caused by small size of underrun buffer.  Emulation itself has  lagging black textures too. So, i'm thinking what the issue's source was found and described already - at the end of your own topic.
https://github.com/hrydgard/ppsspp/pull/8246
