### ISSUE TITLE
Monster Hunter Portable 3rd

### ISSUE THREAD

**Issue by PepeJulio** [hrydgard/ppsspp#9801]
So, this game runs very slow on both my phone and my PC without frameskipping, so is there any way to make it faster? whats the deal with this game, anyway? is it too difficult to emulate it?

**Comment by tywald** [comment]
What are your computer specs? I can run this at full speed all the time on a i7 3770k 3.5Ghz, GTX680. Even on a HP Pavilion dm4 laptop; no good on my Xperia Z though, it's too weak.

Some things you can try(on PC):
- Turn off software skinning.
- Switch backends, try D3D11 or example.
- Lower rendering resolution.
- Double check that you aren't toggling alternative speed or started recording(has happened before on our discord).

**Comment by PepeJulio** [comment]
My PC is an HP stream 11, 2.56ghz dual core, 2gb ram, 64 bits and intel hd graphics. Yeah, on D3D11 it seems to run it faster.

But im more concerned about my phone. Its a Xperia XA, 2.0ghz octacore Mediatek MT6755 Helio P10 chip, Mali T860MP2 gpu, 2gb ram and 64 bits. I dont know, but for me it seems that my phone should be more than able to handle it, but i cant get the game to run fast

**Comment by tywald** [comment]
Are you testing with the HD version or the PSP version of the game? I guess it's the latter due to no HD in this issue title.

**Comment by PepeJulio** [comment]
Ive tried both HD version and the PSP version with the PAUTH files. No luck with either of them

**Comment by unknownbrackets** [comment]
Your PC is most likely held back by its Intel HD graphics:
https://www.notebookcheck.net/Intel-Celeron-N2840-Notebook-Processor.117418.0.html

Your XA has a 2.0 Ghz CPU, although the GPU is decent as far as phones go:
https://www.notebookcheck.net/ARM-Mali-T860-MP2-Benchmarks-and-Specs.163318.0.html

That said, it's not a high-end GPU either.  What speed do you get specifically at 1x render resolution, 1x hardware scaler, software skinning off, and no frameskip?

-[Unknown]

**Comment by PepeJulio** [comment]
21/30 frames per second = 70% speed at village
30/30 frames per second = 100% speed at quest zones with no monsters
19/30 frames per second = 64% speed at quest zones where monsters appear
which, surprisingly, is the same i get at native resolution settings

**Comment by unknownbrackets** [comment]
Okay, well, that probably means you're bound by # of vertices or driver overhead, rather than fill rate.

If your device has gotten relatively recent Android OS updates, you can try downloading the latest git build and switch to Vulkan.  If your problem is driver overhead (which is not at all unlikely), it could help.  The Vulkan backend isn't finished yet, but it works for most rendering - just might miss some special effects in a few scenes, mainly.

-[Unknown]

**Comment by PepeJulio** [comment]
hi dude, does vulkan option at backend shows for everyone or does the emu check if your phone is able to use it, in order to show it?

**Comment by hrydgard** [comment]
It checks. And only in versions after 1.4.2, so make sure you use builds from the buildbot if you'd like to try it.

**Comment by PepeJulio** [comment]
Yeah, already trying. The problem is that it doesnt look like working. I mean, i can start the game and such but, for example, MHFU looks like this:

https://m.imgur.com/riHlwRa

So I asked because if the emu checks, it means that my phone actually supports vulkan.

Is this an issue with, specifically, MHFU or is there something in settings that causes this?

**Comment by hrydgard** [comment]
Could be bugs in the Vulkan backend, it's not fully completed yet.

**Comment by PepeJulio** [comment]
Monster Hunter games seem to be the only ones with this issue. After testing with other games, Vulkan does give a performance boost.  

Thanks for the emu. Its the best at what it offers by far, and Im looking forward to new improvements :)

**Comment by ralphuy** [comment]
Cant play well in LG G5 without frameskip. Below are my average FPS without frameskip

Village:21/30 fps
Farm:23/30 fps
In game 1 monster: ok but sometimes drop to 26/30 FPS depending on effects
Cant play multiplayer without frameskip

Settings:
Non buffered
Off simulate blocks
Display resolution 2x
On hardware transform
Off software skinning
On vertex cache
On lazy texture
Off retained texture
On disbale slower effects
Low spline curves quality
Off upscale
Off Anisotropic
Auto texture filter
Linear screen scaling

Developer tools: off debug logging

System settings:
On fast memory
On multithread(tested. faster on other mediatek cpu devices)
Cpu:auto or 222mhz or 333mhz no difference

The rest are default

**Comment by PepeJulio** [comment]
Yes, Vulkan backend gives a perfect FPS performance with MHP3rd, now its always 30/30.

Only thing left to wait for is the fix for this:
http://m.imgur.com/nM7zQPH

**Comment by hrydgard** [comment]
@PepeJulio I don't recognize that error, is there a separate issue for that?

**Comment by PepeJulio** [comment]
Nah, it was the same bug. I probably made 2 issues because it happened in both Monster Hunter games.

**Comment by hrydgard** [comment]
So why are you waiting for a fix, if it's fixed? Or if you mean that it's a separate issue that's still alive affecting both games, please link it.

**Comment by hrydgard** [comment]
Oh sorry, I didn't see that the message was from August :D
