### ISSUE TITLE
Hang loading short cwcheat files

### ISSUE THREAD

**Issue by TheDauthi** [hrydgard/ppsspp#9804]
Platform: Windows 10
Version: 1.4.2 (x64)

Loading a cwcheat file where the current game is the last one in the file can hang.

Loading the following while running ULES-00850: 
```
_S ULES-00850
_G Final Fantasy Tactics: The War of the Lions [EUR]
_C0 10, 000, 000 Gile
_L 0x20C4B404 0x00989680
```
will hang PPSSPP.

Loading the following
```
_S ULES-00850
_G Final Fantasy Tactics: The War of the Lions [EUR]
_C0 10, 000, 000 Gile
_L 0x20C4B404 0x00989680
_S ULES-99999
_G A Dummy Game
```

will load fine.

Problem is a missing EOF check that causes a loop to go infinite.

Pull Request Inbound

**Comment by unknownbrackets** [comment]
Can you open TheDauthi/ppsspp#1 pointing to hrydgard/ppsspp?

https://github.com/hrydgard/ppsspp/compare/master...TheDauthi:cwcheat-parse-infinite-loop

-[Unknown]
