### ISSUE TITLE
Will not direct sound to headphones when they are plugged in

### ISSUE THREAD

**Issue by nagisa** [hrydgard/ppsspp#9805]
If you plug the headphones in after you start the game, no sound will be audible until the emulator is restarted.

Happens with both the audio backends on Windows 10.

Reproduction steps:
* Unplug the headphones;
* Start the emulator;
* Start a game;
* Plug the headphones;
* No sound will be audible;
* Restart the emulator;
* Start the game;
* Audio will be audible.

**Comment by unknownbrackets** [comment]
I guess we should use MMDeviceAPI to detect this (`OnDefaultDeviceChanged`):
https://msdn.microsoft.com/en-us/library/windows/desktop/dd756609(v=vs.85).aspx

Maybe we could basically restart `WASAPIAudioBackend::RunThread()` in that situation (in case of different formats, etc...)

For DirectSound on pre-Vista, I guess we could either decide not to support this, or else periodically re-enumerate devices to see if the default changed... maybe there's a better way.

-[Unknown]

**Comment by hrydgard** [comment]
I set up the callback interface in https://github.com/hrydgard/ppsspp/tree/wasapi-audio-routing . However, when plugging/unplugging on my laptop, it works and I only get a bunch of property changes, not OnDefaultDeviceChagned which is what I'd expect to see if there's a problem...

**Comment by unknownbrackets** [comment]
Strange, I am getting OnDefaultDeviceChanged (when changing it in the audio settings.)

-[Unknown]
