### ISSUE TITLE
1.4.2 - ULES00172 Crash Team Racing - No More Working after updgraded version...

### ISSUE THREAD

**Issue by DjDiabolik** [hrydgard/ppsspp#9806]
For months i use the "old" version 1.3 and this games it's perfectly working................. about five minutes ago i have upgraded my version to recent 1.4.2 and now the games it's HANG when try to access to the "virtual" Memory Stick.

I have also tryed to extract the 1.4.2 on a clean and newest directory... when i launch the same ISO files the games hang at same point.

I re-extract the 1.3 on another folder and whit this version all it's working ever it's do.....

It's a bug ?

**Comment by DarkD** [comment]
1.3 was released on 17 September 2016, 1.4.2 - 27 May 2017. Practically half year passed with 1.4 and 1.4.1 between them. Can you check if it works in 1.4, 1.4.1 and latest dev. build?
It would be even better if you'll tell exact last working dev. build and one where it stopped so developers will pinpoint which changes led to hanging and will be able to fix those.

**Comment by DjDiabolik** [comment]
mmmmmmmmm..... ok....  how i can pick the 1.4 and 1.4.1 ? The "old" zip files it's in some parts ??

About last working dev.... how i can pick the last dev ? I need to compile on my pc ? If yes it's simply ? If you following me i thinks i can test all whitout any problems....

**Comment by DarkD** [comment]
Well, at least you narrowed it to somewhere between 1.3 and 1.4, not later, good.
Can you narrow it further? Of course there's no need to check every build ever compiled, try 1.3-508, if error is still there - 250. If it's on 250 - try 125 and if not - 321. Narrowing and narrowing the potential list of builds where it may have happened. Though it may've happened early and if you try say 125 and bug is present you may skip later ones.
Yeah, I know, it's tedious, but that way you'll be able to tell developers where things exactly went wrong.

**Comment by DjDiabolik** [comment]
mmmmmmmmmmmmmm... ok... i thinks i can first... take a summary.... i need to download at test 1.3 git...

need to download the 508... 250..... 125..... 321...... etc etc.... i thinks there's not bad idea to start whit the lower git version and see what's append.....

Wait some other feedback in next days :)

**Comment by DarkD** [comment]
So you found exact version with culprit change?

**Comment by DjDiabolik** [comment]
not exactly... i have other to do whit "life" in this past weeks and i have stop to test version.......

**Comment by DarkD** [comment]
2 month later... Anything new about this? Maybe it was fixed already, had you tried latest builds?

**Comment by DjDiabolik** [comment]
no... i have no more play whit this games... try if you need serious report...

**Comment by LunaMoo** [comment]
Oh I know what's wrong here:P the solution is in the title, will fix in a second.

**Comment by DjDiabolik** [comment]
mmmmmmmmm.. great... i can pick and test this 1.5.x or 1.6.x ? Or it's only need to pick a daily of 1.4.2 at today ?

**Comment by hrydgard** [comment]
Yeah just get the latest daily, it has this..

**Comment by DjDiabolik** [comment]
YEAH.. it's work... on this latest daily i have some "glitch" on graphics and some clip problems on audio but the games it's start right now whitout any problems...
