### ISSUE TITLE
Running Lua PSP SDK sample in latest dev build fails

### ISSUE THREAD

**Issue by suicvne** [hrydgard/ppsspp#9808]
hi all, 

i'm developing my own homebrew game for the PSP and until i find mine or get my hands on another, i'm heavily relying on PPSSPP for loose testing of my somewhat simple game. one component of the game is Lua. so this morning when the game compiled just fine against the latest PSP SDK available but crashed the latest Linux dev builds of PPSSPP, I was a bit concerned. 

trying to get to the bottom of things, I ran just the barebones sample that's supplied by the Lua psp-port and put in some debug flags to try and figure out where the game crashed. it crashed right when trying to call `luaL_openLibs`. attached is the full log from Terminal (from run, to crash).

I'm running PPSSPP 1.4.2-199-g3249d81 on Ubuntu 16.04.02 LTS through Parallels on my MacBook Pro. (PSP SDK refuses to build under macOS for whatever reason, whatever). and for reference, [here](https://github.com/pspdev/psp-ports/tree/master/lua) is the psp-ports Lua I'm talking about so you can build and test for yourselves.

[Here's the full log ppsspp-log.txt](https://github.com/hrydgard/ppsspp/files/1092301/ppsspp-log.txt)

I will be more than willing to provide any further information. Also, I tried this on the stable PPA available for Ubuntu and also got a seg fault in the end.

**Comment by hrydgard** [comment]
Thank you, nice report. will look into it soon.

**Comment by suicvne** [comment]
I just borrowed a friend's PSP 3000 to test my game against and ran into similar issues, including the same exact ones regarding the Lua SDK. i will file a report on the pspdev/psp-ports repository

**Comment by suicvne** [comment]
I'm able to run the Lua 5.3.4 sample that I setup just fine on real hardware and in the same build of PPSSPP that I filed this bug report with. I believe this can be closed then. i've submitted a PR to the psp-ports repo to replace Lua 5.2 with Lua 5.3.4
