### ISSUE TITLE
Shin Megami Tensei: Persona - Item boxes are invisible

### ISSUE THREAD

**Issue by Ennea** [hrydgard/ppsspp#9813]
Using PPSSPP 1.4.2, DirectX 11 and Upscaled Textures, the item boxes in Shin Megami Tensei: Persona disappear visually. Tested with both the 32 bit and 64 bit binaries.

**Comment by hrydgard** [comment]
Can you post screenshots of both when they are visible (say with OpenGL) and when they're invisible?

**Comment by Ennea** [comment]
There you go: https://imgur.com/a/cHbs2

**Comment by hrydgard** [comment]
Huh, curious. Also there's something going on with the pink plant - looks different. I remember having some issue with it way back..

**Comment by Ennea** [comment]
That thing's just pulsating ;)

**Comment by hrydgard** [comment]
Oh, right :)

**Comment by unknownbrackets** [comment]
Can reproduce - note that it doesn't immediately disappear.

It's a CLUT4 texture, swizzled with no levels.  The size is 128x64, but bufw is 96.  Texturing from 090a1320, so no render funny business.  The GE debugger shows a source texture that's blank, so apparently it's not there at all.

And to confirm, it only happens in D3D 11...

-[Unknown]
