### ISSUE TITLE
App crashes on Lenovo Yoga after it was updated to Android 6.0

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#9814]
Presumably this resulted in it now using the x86-64 build, and that build seems to have issues according to Intel, who have informed me that it is unstable. Multiple users have reported the Yoga as an affected device.

**Comment by mrcmunir** [comment]
@hrydgard  What happen no load UI? Crash with specific game/some config? I tested with recents changes AOSP image and working fine

**Comment by hrydgard** [comment]
Do not know. Got a device to debug on on the way, will investigate once it arrives.

**Comment by hrydgard** [comment]
Got bad problems with FFMPEG for Android-x86_64. Pushing to 1.6.

**Comment by unknownbrackets** [comment]
https://github.com/hrydgard/ppsspp-ffmpeg/commit/0668c45b81d1a40817f1e1f94956335be16edbd4

Maybe it does need asm disabled?  I know we disabled it because of the text rels:
https://github.com/hrydgard/ppsspp-ffmpeg/commit/1fe67798842c2c9d101c028973383bfd1278fd77

Perhaps it was just not being reported on x86_64, or I was wrong that it wasn't needed.

-[Unknown]

**Comment by mrcmunir** [comment]
But what's ffmpeg problem? In general? Perfomance? / Crash in some game?

I have tried it on an image marsmallow/nougat from the code that offers Android-x86 site and loads correctly and I could not detect any crash in a few months ago

I will try now with the current code to see if I can detect any accident with ffmpeg.

**Comment by hrydgard** [comment]
@unknownbrackets There were some flags added to the Android x86_64 build that caused it to link but eliminated a ton of symbols in the process, so the resulting binary fails to run on Android x86-64. See https://github.com/hrydgard/ppsspp/blob/master/CMakeLists.txt#L1616 .

Removing those lines from the CMakeLists, the linker indeed complains about relocations. So we might need to disable asm and rebuild indeed, I just can't be bothered right now so x86_64 Android will have to live with 32-bit builds for a little while longer.

**Comment by unknownbrackets** [comment]
Hmm, it seems like we should be explicitly exporting symbols we need to export...  It used to be, iirc at least, that that could be used on ARM as well to reduce build size but lose debug traces without having the build files to recalculate.

Oh well, probably better to lose that workaround, even if it means ffmpeg is probably running is some sort of slow mode without optimized asm...

-[Unknown]

**Comment by hrydgard** [comment]
With those flags it zaps the JNI entry points, and carefully marking them with JNIEXPORT and JNICALL doesn't help at all. It's a bit strange that this only happens in the x86-64 build though, but clearly it's eating code that we need because the relocation warnings go away, and they shouldn't if the asm code is "bad".

**Comment by mrcmunir** [comment]
The configuration from android-x86  team use similar flags -Wl,--no-fatal-warnings -Wl,-Bsymbolic 

See https://sourceforge.net/p/android-x86/external_ffmpeg/ci/oreo-x86/tree/android/build.mk#l73

Also See comment https://lists.ffmpeg.org/pipermail/libav-user/2013-May/004528.html
>If you are trying to combine several ffmpeg libraries into a single shared library  as I have seen some apps try to do then  you need to use the following linker flag on the final library build step. -shared -Wl,-Bsymbolic

But strange only needed it for x86_64 ?

**Comment by mrcmunir** [comment]
I have not had time before so I just downloaded from the buildbot and load properly x86_64  only sometimes when exit app crash ppsspp popup.

![alt text](http://i65.tinypic.com/2zekvph.png "Logo Title Text 1")

![alt text](http://i67.tinypic.com/29o1wly.png "Logo Title text 2")

The buildbot is using android studios or using  ndk-build - ant build??

**Comment by hrydgard** [comment]
The one on the buildbot simply doesn't build for x86-64 anymore, only x86. That runs fine on x86-64 but loses a small amount of speed.

**Comment by mrcmunir** [comment]
@hrydgard yep i'm very confused because said ABI x86_64 native in the menu detected and I decompile apk from buildbot is found x86_64 compiled folder
  
![](http://i64.tinypic.com/rksa61.png)

**Comment by hrydgard** [comment]
Oh, hm. Right, the buildbot uses the old way of building with ndk-build. That still builds x86-64, sorry for the confusion. So if that works, it should be possible to figure out why, and apply to the CMake-based build which is used for official releases...

**Comment by unknownbrackets** [comment]
So is this just a bug in that the symbolic stuff ISN'T being used on x86-64 with cmake?

-[Unknown]

**Comment by hrydgard** [comment]
Maybe? But we had it in before, and it didn't work?

**Comment by mrcmunir** [comment]
i'm looking at how to implement it in cmake will load android-x86 images and avd emulator

```set(CMAKE_SHARED_LINKER_FLAGS "-Wl,--no-fatal-warnings -Wl,-Bsymbolic")```

But not sure what cause this problem in cmake some code c++ <-> java is little diferent
