### ISSUE TITLE
Xbox One Version of PPSSPP Freezes When Trying to Back Out of the Menu (UWP)

### ISSUE THREAD

**Issue by Ploggy** [hrydgard/ppsspp#9816]
The Xbox One version (UWP) of PPSSPP freezes if I try to back out of the Menu, But only if a game is loaded .
Before loading a game I can mess with the settings and back out fine.

**Comment by WodsonKun** [comment]
Same thing happen if you open the control mapping settings, without needing open a game

**Comment by WodsonKun** [comment]
When the fix comes out?

**Comment by Ploggy** [comment]
> Dump Summary
> ------------
> Dump File:	PPSSPP_UWP.exe.4004.dmp : C:\Users\Mam\Desktop\PPSSPP_UWP.exe.4004.dmp
> Last Write Time:	09/07/2017 12:07:54
> Process Name:	PPSSPP_UWP.exe : S:\Program Files\WindowsApps\0ad29e1a-1069-4cf5-8c97-620892505f0c_1.0.0.0_x64__efsvx4pb9b836\PPSSPP_UWP.exe
> Process Architecture:	x64
> Exception Code:	0xC0000005
> Exception Information:	The thread tried to read from or write to a virtual address for which it does not have the appropriate access.
> Heap Information:	Not Present
> 
> System Information
> ------------------
> OS Version:	10.0.15063
> CLR Version(s):	
> 
> Modules
> -------
> Module Name	Module Path	Module Version
> -----------	-----------	--------------
> PPSSPP_UWP.exe	S:\Program Files\WindowsApps\0ad29e1a-1069-4cf5-8c97-620892505f0c_1.0.0.0_x64__efsvx4pb9b836\PPSSPP_UWP.exe	0.0.0.0
> ntdll.dll	C:\Windows\SYSTEM32\ntdll.dll	10.0.15063.3054
> KERNELBASE.dll	C:\Windows\System32\KERNELBASE.dll	10.0.15063.3054
> combase.dll	C:\Windows\System32\combase.dll	10.0.15063.3054
> ucrtbase.dll	C:\Windows\System32\ucrtbase.dll	10.0.15063.3054
> RPCRT4.dll	C:\Windows\System32\RPCRT4.dll	10.0.15063.3054
> kernel32legacy.dll	C:\Windows\System32\kernel32legacy.dll	10.0.15063.3054
> bcryptPrimitives.dll	C:\Windows\System32\bcryptPrimitives.dll	10.0.15063.3054
> WS2_32.dll	C:\Windows\System32\WS2_32.dll	10.0.15063.3054
> sechost.dll	C:\Windows\System32\sechost.dll	10.0.15063.3054
> d2d1.dll	C:\Windows\SYSTEM32\d2d1.dll	10.0.15063.3054
> XINPUTUAP.dll	C:\Windows\SYSTEM32\XINPUTUAP.dll	10.0.15063.3054
> msvcrt.dll	C:\Windows\System32\msvcrt.dll	7.0.15063.3054
> d3d11.dll	C:\Windows\SYSTEM32\d3d11.dll	10.0.15063.3054
> dxgi.dll	C:\Windows\SYSTEM32\dxgi.dll	10.0.15063.3054
> advapi32legacy.dll	C:\Windows\System32\advapi32legacy.dll	10.0.15063.3054
> win32u.dll	C:\Windows\System32\win32u.dll	10.0.15063.3054
> SspiCli.dll	C:\Windows\System32\SspiCli.dll	10.0.15063.3054
> gdi32.dll	C:\Windows\System32\gdi32.dll	10.0.15063.3054
> gdi32min.dll	C:\Windows\System32\gdi32min.dll	10.0.15063.3054
> minuser.dll	C:\Windows\System32\minuser.dll	0.0.0.0
> DWrite.dll	C:\Windows\SYSTEM32\DWrite.dll	10.0.15063.3054
> XAudio2_9.dll	C:\Windows\SYSTEM32\XAudio2_9.dll	10.0.15063.3054
> vccorlib140_app.DLL	S:\Program Files\WindowsApps\Microsoft.VCLibs.140.00_14.0.24124.0_x64__8wekyb3d8bbwe\vccorlib140_app.DLL	14.0.24123.0
> OLEAUT32.dll	C:\Windows\System32\OLEAUT32.dll	10.0.15063.3054
> msvcp_win.dll	C:\Windows\System32\msvcp_win.dll	10.0.15063.3054
> MSVCP140_APP.dll	S:\Program Files\WindowsApps\Microsoft.VCLibs.140.00_14.0.24124.0_x64__8wekyb3d8bbwe\MSVCP140_APP.dll	14.0.24123.0
> VCRUNTIME140_APP.dll	S:\Program Files\WindowsApps\Microsoft.VCLibs.140.00_14.0.24124.0_x64__8wekyb3d8bbwe\VCRUNTIME140_APP.dll	14.0.24123.0
> D3DCOMPILER_47.dll	C:\Windows\SYSTEM32\D3DCOMPILER_47.dll	10.0.15063.3054
> CRYPT32.dll	C:\Windows\SYSTEM32\CRYPT32.dll	10.0.15063.3054
> MMDevAPI.DLL	C:\Windows\SYSTEM32\MMDevAPI.DLL	10.0.15063.3054
> AVRT.dll	C:\Windows\SYSTEM32\AVRT.dll	10.0.15063.3054
> MSASN1.dll	C:\Windows\SYSTEM32\MSASN1.dll	10.0.15063.3054
> CRYPTSP.dll	C:\Windows\SYSTEM32\CRYPTSP.dll	10.0.15063.3054
> DEVOBJ.dll	C:\Windows\SYSTEM32\DEVOBJ.dll	10.0.15063.3054
> cfgmgr32.dll	C:\Windows\SYSTEM32\cfgmgr32.dll	10.0.15063.3054
> PROPSYS.dll	C:\Windows\SYSTEM32\PROPSYS.dll	7.0.15063.3054
> shcore.dll	C:\Windows\System32\shcore.dll	10.0.15063.3054
> procthreadexthost.dll	C:\Windows\SYSTEM32\procthreadexthost.dll	10.0.15063.3054
> remotewinrt.dll	C:\Windows\SYSTEM32\remotewinrt.dll	10.0.15063.3054
> kernel.appcore.dll	C:\Windows\System32\kernel.appcore.dll	10.0.15063.3054
> twinapi.appcore.dll	C:\Windows\System32\twinapi.appcore.dll	10.0.15063.3054
> bcrypt.dll	C:\Windows\SYSTEM32\bcrypt.dll	10.0.15063.3054
> WinTypes.dll	C:\Windows\System32\WinTypes.dll	10.0.15063.3054
> xamapi.dll	C:\Windows\SYSTEM32\xamapi.dll	10.0.15063.3054
> AuthBroker.dll	C:\Windows\SYSTEM32\AuthBroker.dll	10.0.15063.3054
> EtwPlus.dll	C:\Windows\SYSTEM32\EtwPlus.dll	10.0.15063.3054
> XboxLiveTitleId.dll	C:\Windows\SYSTEM32\XboxLiveTitleId.dll	10.0.15063.3054
> wkscli.dll	C:\Windows\SYSTEM32\wkscli.dll	10.0.15063.3054
> netutils.dll	C:\Windows\SYSTEM32\netutils.dll	10.0.15063.3054
> usermgrcli.dll	C:\Windows\SYSTEM32\usermgrcli.dll	10.0.15063.3054
> WINHTTP.dll	C:\Windows\SYSTEM32\WINHTTP.dll	10.0.15063.3054
> procthreadexthostxbox.dll	C:\Windows\SYSTEM32\procthreadexthostxbox.dll	10.0.15063.3054
> xosproxy.dll	C:\Windows\System32\xosproxy.dll	10.0.15063.3054
> OneCoreUAPCommonProxyStub.dll	C:\Windows\System32\OneCoreUAPCommonProxyStub.dll	10.0.15063.3054
> windowscodecs.dll	C:\Windows\system32\windowscodecs.dll	10.0.15063.3054
> CoreUIComponents.dll	C:\Windows\system32\CoreUIComponents.dll	10.0.15063.3054
> ntmarta.dll	C:\Windows\SYSTEM32\ntmarta.dll	10.0.15063.3054
> CoreMessaging.dll	C:\Windows\SYSTEM32\CoreMessaging.dll	10.0.15063.3054
> ciumd_wddm.dll	C:\Windows\SYSTEM32\ciumd_wddm.dll	10.0.15063.3054
> SC_DLL.dll	C:\Windows\SYSTEM32\SC_DLL.dll	1.23.15020.1000
> xg.dll	C:\Windows\SYSTEM32\xg.dll	10.0.15063.3054
> mfpalsra.dll	C:\Windows\SYSTEM32\mfpalsra.dll	10.0.15063.3054
> usermgrproxy.dll	C:\Windows\System32\usermgrproxy.dll	10.0.15063.3054
> scache.dll	C:\Windows\SYSTEM32\scache.dll	0.0.0.0
> USERENV.dll	C:\Windows\SYSTEM32\USERENV.dll	10.0.15063.3054
> profapi.dll	C:\Windows\System32\profapi.dll	10.0.15063.3054
> profext.dll	C:\Windows\SYSTEM32\profext.dll	10.0.15063.3054
> mrmcorer.dll	C:\Windows\System32\mrmcorer.dll	10.0.15063.3054
> windows.ui.dll	C:\Windows\SYSTEM32\windows.ui.dll	10.0.15063.3054
> dcomp.dll	C:\Windows\SYSTEM32\dcomp.dll	10.0.15063.3054
> TextInputFramework.dll	C:\Windows\SYSTEM32\TextInputFramework.dll	10.0.15063.3054
> inputhost.dll	C:\Windows\SYSTEM32\inputhost.dll	0.0.0.0
> UiaManager.dll	C:\Windows\System32\UiaManager.dll	10.0.15063.3054
> windows.ui.core.textinput.dll	C:\Windows\SYSTEM32\windows.ui.core.textinput.dll	10.0.15063.3054
> Windows.Graphics.dll	C:\Windows\System32\Windows.Graphics.dll	10.0.15063.3054
> rometadata.dll	C:\Windows\SYSTEM32\rometadata.dll	4.7.2046.0
> CRYPTBASE.dll	C:\Windows\SYSTEM32\CRYPTBASE.dll	10.0.15063.3054
> Windows.Storage.ApplicationData.dll	C:\Windows\System32\Windows.Storage.ApplicationData.dll	10.0.15063.3054
> windows.storage.dll	C:\Windows\System32\windows.storage.dll	10.0.15063.3054
> shlwapi.dll	C:\Windows\System32\shlwapi.dll	10.0.15063.3054
> powrprof.dll	C:\Windows\System32\powrprof.dll	10.0.15063.3054
> AUDIOSES.DLL	C:\Windows\SYSTEM32\AUDIOSES.DLL	10.0.15063.3054
> Windows.Gaming.Input.dll	C:\Windows\System32\Windows.Gaming.Input.dll	10.0.15063.3054
> deviceaccess.dll	C:\Windows\System32\deviceaccess.dll	10.0.15063.3054
> Windows.System.UserDeviceAssociation.dll	C:\Windows\System32\Windows.System.UserDeviceAssociation.dll	10.0.15063.3054
> Windows.StateRepository.dll	C:\Windows\System32\Windows.StateRepository.dll	10.0.15063.3054
> StateRepository.Core.dll	C:\Windows\SYSTEM32\StateRepository.Core.dll	10.0.15063.3054


Here is the .DMP file...

[PPSSPP_UWP.exe.4004.zip](https://github.com/hrydgard/ppsspp/files/1133820/PPSSPP_UWP.exe.4004.zip)

**Comment by Ploggy** [comment]
It's been a while but could you look into this issue? @hrydgard @unknownbrackets

**Comment by hrydgard** [comment]
I guess this one changed into #10948 ?

**Comment by Ploggy** [comment]
No this is another bug which still happens. Unrelated to the B button bug.

Load Game
Once loaded, open the settings menu
Change some graphics options
Try to back out of settings. It freezes and I'm forced to quit PPSSSPP from the Xbox home button.

**Comment by unknownbrackets** [comment]
Thanks for verifying.

-[Unknown]
