### ISSUE TITLE
Final Fantasy Tactic graphic glitch on android

### ISSUE THREAD

**Issue by asl97** [hrydgard/ppsspp#9817]
Glitch when opening town menu after the second fight.

ppsspp 1.4.2, android 4.2.2, Adreno 305
Buffered rendering
Simulate block transfer effects enabled
Rendering resolution 1xPSP

Note:
It works fine on linux with PPSSPPSDL 1.4.2 with the same settings
It works fine when using the SoftwareRenderer on android

![screenshot_2017-06-28-07-38-23](https://user-images.githubusercontent.com/4752645/27615298-c7bdcb18-5bd9-11e7-855e-7a88f4c26570.png)

ADB logcat 'Dump Next Frame To Log': https://gist.github.com/asl97/5dbab5127982b749238f0ba1d8836bf5

**Comment by unknownbrackets** [comment]
Does this still happen in the latest git build?

Does this happen using Vulkan?

-[Unknown]

**Comment by asl97** [comment]
It doesn't seem to be happening anymore and Vulkan isn't available on my device.
