### ISSUE TITLE
Corpse Party Book of Shadows no music loop only with 1.2.2,1.3 and 1.4.2. With 1.1.1 is OK.

### ISSUE THREAD

**Issue by Tsuhirito** [hrydgard/ppsspp#9826]
Music plays and after stops without loop. With 1.1.1 I don't have this problem.

**Comment by Michal1324** [comment]
Check if the lastest ppsspp version got that fixed if not

enable the audio improvement in audio tab

**Comment by Tsuhirito** [comment]
I tried, no fix :(. There is always this bug, so I have to play with 1.1.1. And this is another bug https://github.com/hrydgard/ppsspp/issues/9815

**Comment by phly95** [comment]
I'm having the same issue. Guess I'll play with 1.1.1 then until this is fixed (or I finish this game and move on to blood drive)

**Comment by benderscruffy** [comment]
this has been fixed
it can be closed

**Comment by benderscruffy** [comment]
Can be closed
