### ISSUE TITLE
Duplicate textures in "Save Textures"

### ISSUE THREAD

**Issue by Endarko** [hrydgard/ppsspp#9827]
Can this be fixed? There is one picture textures. But during save textures. Appears to be three or more, the image is just the same size and different name. ? It is very annoying because i have to override those three images, to make permanent textutes, if one picture is not in overpass then textures will return to original.

**Comment by hanooty** [comment]
Which game you happen this???

**Comment by Endarko** [comment]
#PES 2013 & 2014
#SBK-09: Superbike World Championship

**Comment by Endarko** [comment]
![screenshot_20170706-034833](https://user-images.githubusercontent.com/16800334/27884324-28fa7f3c-61fe-11e7-815a-8926923aba3c.png)

**Comment by Endarko** [comment]
![screenshot_20170706-035443](https://user-images.githubusercontent.com/16800334/27884543-f7ebcada-61fe-11e7-8e89-866233d9cc9a.png)

**Comment by carlsmith** [comment]
I'm having the same issue on macOS with GTA Vice City Stories. I get about five copies of each texture, but each at a different resolution, from low def and blurry to relatively sharp.

**Comment by unknownbrackets** [comment]
See #13133, #6256, #9665, #9482.

These hashes are of the CLUT and texture data provided to PPSSPP, which may be subtly different in ways that could even result in no obviously visible difference.  While this isn't ideal, PPSSPP is replacing textures based on the information the game makes available - which is somewhat limited.  You can use the ini file to control parts of this.

Technically, the game is indeed specifying separate textures.

Closing this as it's more about how to use texture replacements and might be better for the forum.

-[Unknown]
