### ISSUE TITLE
Primary post-processing shaders directory points to wrong location

### ISSUE THREAD

**Issue by AlpacaRotorvator** [hrydgard/ppsspp#9831]
**Issue:**
For a while now I've noticed PPSSPP's settings menu tells me I have no post-processing shaders, even though I have the relevant folder with the stock ones in my filesystem.

A little fidgeting around revealed PPSSSPP is set up to look in /shaders rather than /assets/shaders, which is how shaders(and other assets) are stored in the filesystem.

**Solution:**
Solving this seems to be a one line(114) fix to /GPU/Common/PostShader.cpp . I'm creating a pull request parallel to this Issue that implements it.

**Comment by hrydgard** [comment]
Hm. Assets should be one of the "root" directories so just "shaders" should work. Works for me as-is on Windows and I think on Android (though haven't tried recently).

What system are you on?

**Comment by AlpacaRotorvator** [comment]
>Assets should be one of the "root" directories so just "shaders" should work.
Oh, I did find it weird that this somehow flew under you guys' radar for more than a couple of days, and indeed the shaders showed up in my Android device without intervention.

I'm running Manjaro Linux(Stable repositories, 4.8 kernel, if it matters).

**Comment by unknownbrackets** [comment]
Hmm, so Qt only registers `AssetsAssetReader` for Qt, perhaps that's it.

Are you using Qt?  If so, does this happen on SDL?

-[Unknown]
