### ISSUE TITLE
iOS 11 support.

### ISSUE THREAD

**Issue by xurayg** [hrydgard/ppsspp#9833]
Since iOS 11 will not support armv7 app. Is there any plan to fix it ?

**Comment by hrydgard** [comment]
We don't even know yet if iOS 11 will be jailbroken and if so what restrictions will apply on JIT.

But yeah, I plan to fix the ARM64 issue for iOS 10 at least.

**Comment by iOS4all** [comment]
Please when you'll port metal iOS api as rendering like Vulkan and directX

I'm sure it'll fix many bugs including the performance as well as the stutter.

**Comment by Michal1324** [comment]
Vulkan would only improve framerate if the cpus is slow

Directx is only on windows and Xbox

**Comment by iOS4all** [comment]
Yes I know that. And metal is the same as Vulkan and directx I mean as api. I'm sure it'll also improve framerate much more. And @hrydgard said long ago he will implement it in near future.

**Comment by Michal1324** [comment]
Directx isnt the same as Vulkan...

Vulkan is cross device and cross platform and might work a little bit different

**Comment by iOS4all** [comment]
Yes I mean they  are all api rendering. Anyway thanks for you info.

**Comment by iOSSOi** [comment]
Will ppsspp be updated för 64bit. Im running ios 11 beta, and the app wont open if its not 64bit compatible.

**Comment by fuzzywalrus** [comment]
PPSSPP on iOS 11 compiles and launches but as expected, freezes when certain settings are changed or any game is attempted to be loaded.

**Comment by hrydgard** [comment]
Might be worth trying again with unknown's latest fixes.

**Comment by xurayg** [comment]
@hrydgard  I have tried it on iPhone7 Plus with iOS11.1.2  . When I load a game, it crashed...

**Comment by xurayg** [comment]
I tried to sign PPSSPP.app with embedded.mobileprovision inside it . It didn't crash . BTW the xcode project I run shows that the app do not need sign .  Nice work~
