### ISSUE TITLE
PPSSPP using GL ES instead of full OpenGL on Shield tablet

### ISSUE THREAD

**Issue by gannon345** [hrydgard/ppsspp#9836]
Not sure if this is an issue or not, so apologies if this is intended. The Shield tablet, Shield K1 tablet, and the Shield Consoles all support full OpenGL spec, but it appears the tablet is currently running PPSSPP in GLES 3.

**Comment by Michal1324** [comment]
I belive if the OS is android the wendor used by defualt is GL ES

**Comment by gannon345** [comment]
Is it possible to detect the Shield tablet and use full OpenGL spec? Or would that break stuff? The Shield tablet and Shield K1 support OpenGL 4.4, and the console with the X1 chip supports OpenGL 4.5.

Not sure if this might bring performance gains to those devices or not though, but it's my understanding that GL ES is more limited in terms of instructions than full OpenGL.

**Comment by hrydgard** [comment]
It's possible, but we need to change a new GL extension loader, which is some work and compatibility list. We currently use separate solutions on Android (simple one that came with a sample) vs Windows/other desktops (glew).

Not that we actually use a lot of desktop-only features though...

**Comment by i30817** [comment]
Is the OP thinking that he'll get better performance in full opengl mode? I'd think it wouldn't matter, considering GL ES is supposed to be a subset right? But who knows what drivers do in the dark.

**Comment by Michal1324** [comment]
Isn't Vulkan basicly managed OpenGL gannon give it a shot if you can play with it

**Comment by gannon345** [comment]
Vulkan is looking good, though introduces some new graphical bugs in some games. For example, Madden 2012 the field is black like the players are running in space, and in Way of the Samurai Portable, character face textures seem to be half duplicated.

**Comment by Michal1324** [comment]
gannon its not really bugs its just missing some of the calls that other renders have

**Comment by gannon345** [comment]
Gotcha. Well, hopefully it's sorted out at some point. Either way I'm glad the Vulkan renderer was added to Android.

**Comment by Michal1324** [comment]
Yeah since mobile devices have lower clock speeds than few years old desktop cpus

mobile focuses more on cores so

**Comment by gannon345** [comment]
Fair enough. Given that this is a non-issue and just how you guys handle things on the Android side, feel free to close the issue. Thanks for all the info.

**Comment by hrydgard** [comment]
I think we already have some related issues, and yeah, Vulkan is the future anyway. Closing.
