### ISSUE TITLE
Monster Hunter Portable 3rd android graphic issue

### ISSUE THREAD

**Issue by exorzia** [hrydgard/ppsspp#9841]
Hi, I'm testing this game on my phone, Redmi 4a. The game is running really well, with auto frameskip enabled but then i encounter this weird glitch on the ground and plains when doing quest. I realize it happen with buffered rendering enabled. Settings are on default with Opengl backend. I test it from version 1.1 to the latest version both MHP3rd HD and non HD version and it still there, also test it on pc and only happen on phone.
I kinda unsure there is problem with my phone cause other games seems to run surprisingly well, so far. Or, something with my adreno gpu cause my other phone Redmi 2 (almost same specifications, older) encounter the same problem, or just android common issue that still unsolved. I hope there is some fix for this issue. Thanks

Here some shots

![screenshot_2017-07-11-13-54-02-445_org ppsspp ppsspp](https://user-images.githubusercontent.com/30068745/28094716-6c25efb6-66c8-11e7-80ed-c37392d92c69.png)
![screenshot_2017-07-11-13-54-52-683_org ppsspp ppsspp](https://user-images.githubusercontent.com/30068745/28094724-75106f70-66c8-11e7-8527-6cb4ffc96695.png)
![screenshot_2017-07-11-13-55-45-335_org ppsspp ppsspp](https://user-images.githubusercontent.com/30068745/28094726-7521eade-66c8-11e7-8e63-a0437e13cdbc.png)
![screenshot_2017-07-11-13-54-11-395_org ppsspp ppsspp](https://user-images.githubusercontent.com/30068745/28094948-e78c3a56-66c9-11e7-8b72-075048d550c1.png)
![screenshot_2017-07-11-13-55-55-623_org ppsspp ppsspp](https://user-images.githubusercontent.com/30068745/28094959-f28e105a-66c9-11e7-9f5a-2c871eb8f61f.png)

**Comment by Hydroque** [comment]
Is there any way to render your game in triangles? I wonder if the geometry is malformed or if it is just the shading. This looks like a common bug where two triangles are on top of each other: the two mix in a sort of scanline-like fashion.

**Comment by hrydgard** [comment]
I feel like we've seen this issue before, I recognize it. Seems to be the same:
https://github.com/hrydgard/ppsspp/issues/7218

Looks like a depth precision/Z-fighting issue. Quite odd...

**Comment by exorzia** [comment]
When i use non buffer it looks pretty normal, but still kinda curious why in buffered rendering this thing happen...

**Comment by exorzia** [comment]
Oh just for information, both adreno is using open gl es 3.0.., maybe there somewhat something about this cause my pc is using open gl 3.1 and it doesn't have this issue. Hope that helps, and i hope this fixed in the future

**Comment by unknownbrackets** [comment]
FWIW this visually looks similar to the lighting issue in Blade Dancer (see https://github.com/hrydgard/ppsspp/issues/4140#issuecomment-304530070), the screenshot is clean, but depending on how you rotate, you get that banding.  It does look like z-fighting, but I wonder if it's the same issue.

-[Unknown]

**Comment by omarsupercool5310** [comment]
How did you boot up the game

**Comment by Hydroque** [comment]
I wonder if this is because floating point cancerism.

**Comment by Emulatorer** [comment]
I think this issue already fixed in the latest build 🤔

**Comment by unknownbrackets** [comment]
Okay, let's hope it got fixed by the same changes that fixed Blade Dancer.  They looked similar.

-[Unknown]

**Comment by passingbycat** [comment]
Where did you get your mhp3rd English for psp emu? Please share it to me

**Comment by Saramagrean** [comment]
Here.
http://www.romhacking.net/translations/2043/
