### ISSUE TITLE
Missing texture in  mod nation racer

### ISSUE THREAD

**Issue by omarguerrero5310** [hrydgard/ppsspp#9851]
![screenshot_2017-07-17-11-28-56](https://user-images.githubusercontent.com/26820148/28283683-494f27ea-6ae3-11e7-9630-af3353bf3379.png)
![screenshot_2017-07-17-11-28-18](https://user-images.githubusercontent.com/26820148/28283684-49509d46-6ae3-11e7-8dca-cd52cd4f7023.png)
![screenshot_2017-07-17-11-27-58](https://user-images.githubusercontent.com/26820148/28283685-4970cfc6-6ae3-11e7-9413-9418302504fe.png)

**Comment by unknownbrackets** [comment]
The last screenshot makes me think you have the wrong assets for your version of PPSSPP.  Try downloading the latest version, and make sure to extract all files, including those in the assets directory.

It's probably rendering the car and using it as a texture.  Make sure you're using the default settings and the latest git build.  Does it still happen?

Does this work when using the "software renderer"?  It will be very slow.

-[Unknown]

**Comment by ppmeis** [comment]
Tested with latest Windows build. Default settings. When you save a car creation, mini car texture are missing in all of them. Nevertheless, keyboard looks fine when you type a name for a new car creation:

![image](https://user-images.githubusercontent.com/4381277/34458222-33845b1e-edca-11e7-92c7-8b8a4068f86d.png)

Missing Textures:
![image](https://user-images.githubusercontent.com/4381277/34458245-23bf2c80-edcb-11e7-856d-fdc4902d32cd.png)

**Comment by unknownbrackets** [comment]
Interesting that even the software renderer is affected.  Maybe the car creation part is just missing a framebuffer download, but that doesn't really explain software missing all those icons.  Hm.

-[Unknown]

**Comment by FlatOutPS2** [comment]
> Interesting that even the software renderer is affected. Maybe the car creation part is just missing a framebuffer download, but that doesn't really explain software missing all those icons. Hm.

The Kart creation doesn't save the icon when using a hardware renderer. If you create a Kart while using the software renderer the icon will be saved and visible, even when using a hardware renderer.

**Comment by FlatOutPS2** [comment]
I noticed something different happens when using the D3D11 renderer.

![modnation](https://user-images.githubusercontent.com/15942346/34630535-c587b29e-f26c-11e7-9ba6-c96bc0b9eb7f.jpg)

This screenshot was taken while using the OpenGL hardware renderer. The visible kart was created while using the software renderer. The invisible one on the top right and selected invisible one at the bottom right are OpenGL, the bottom left is D3D9, and the middle ones showing a distorted image were made with the D3D11 renderer(this also happens on older builds, so it's not a recent change).

**Comment by benderscruffy** [comment]
this can be closed
![modnation](https://user-images.githubusercontent.com/2696404/71640169-d90b6600-2cbf-11ea-82b2-fd81b21886e1.PNG)

**Comment by unknownbrackets** [comment]
Thanks for retesting - very interesting, wonder what fixed this.  Maybe it was the volatile memory VRAM check.

-[Unknown]
