### ISSUE TITLE
ppsspp 1.3 jit on xcode for ios 10.3.2

### ISSUE THREAD

**Issue by noelesther** [hrydgard/ppsspp#9853]
Hello.

I can't speak English but i will try explain to you.

I have iPad pro 12.9 ios 10.3.2. And I want to play ppsspp. also turn on jit.

I founded ppsspp on builds.io, there is 1.3 ver.

I paid account and installed 1.3 but i can play anything when i turned on jit.

After that I searched how can use ppsspp turn on jit to ios 10.3.2 non-jailbreak.

Someone said "use lastest ver!" So I downloaded 1.4.2 and cydiaimpactor.

When I installed 1.4.2 on ipad, i can't play anything turn on jit.

I felt sad. but I tried again. I searched all issues.

I found, someone said(atsumori666), "when i use 1.3 fix jit on xcode, i can play. but 1.4.2 can't play turn on jit. Is it change something?[#9404](https://github.com/hrydgard/ppsspp/issues/9404#issuecomment-294964221)

I thought if i fix 1.3, i can play ppsspp & jit on my ipad pro gen2 12.9 ios 10.3.2!

but, I met big problem. I never used xcode before. And I couldn't find any information of fix 1.3 jit on xcode.

but, I also tried that. Download xcode, ppsspp 1.3 source. and tried all of iOS Build Instructions readme.md.

Finally I made PPSSPP.xcodeproj file. and play on xcode. 

![2017-07-19 12 33 19](https://user-images.githubusercontent.com/25280660/28331236-83f03078-6c1a-11e7-8d7a-52b1b6bdcd00.png)

but, I don't know how can fix jit. also i can't find arm64jit.ccp

plz help me. I want to know how can use jit on ppsspp 1.3 for ios 10.3.2.

I did as much as I could... thanks.

**Comment by unknownbrackets** [comment]
This appears to basically be describing the issue in #9232.  The latest version now has jit fixed in #10465.

-[Unknown]
