### ISSUE TITLE
SOCOM: Fireteam Bravo 3 - crash after a mission

### ISSUE THREAD

**Issue by Levan7** [hrydgard/ppsspp#9858]
I am using the latest build 1.4.2-267-g033676ca4 64 bit and when you finish mission (stockpile) the ppsspp crashes.

Same thing happens stable 1.4.2 and 1.3.2

[log.zip](https://github.com/hrydgard/ppsspp/files/1167638/log.zip)

**Comment by rizky29** [comment]
Keren

**Comment by unknownbrackets** [comment]
Did this always happen, or did it start in a certain version?

Have you tried with default settings, and using an ingame save without touching any save states?

-[Unknown]

**Comment by SamueldeSena** [comment]
this problem has already been fixed in the new version of ppsspp v1.5.4 this topic can already be closed

**Comment by hrydgard** [comment]
@Levan7 might want to check that this works for you in the latest. In the meantime, I'm closing.
