### ISSUE TITLE
I solve the Simpson the video game problem 

### ISSUE THREAD

**Issue by omarsupercool5310** [hrydgard/ppsspp#9862]
Just diable lazy texture caching and disable slower effect

**Comment by tywald** [comment]
Might be related to #6697 ?

Insufficient information what exactly has been fixed when you disabled those settings.

**Comment by omarsupercool5310** [comment]
![2017-07-24-14-18-34--1242026462](https://user-images.githubusercontent.com/30366777/28545250-1fce14d8-707b-11e7-8fb1-e1473f914ead.jpg)

**Comment by omarsupercool5310** [comment]
![2017-07-24-14-17-45-1478687641](https://user-images.githubusercontent.com/30366777/28545263-2e9404aa-707b-11e7-815d-be6dfd819f4c.jpg)
