### ISSUE TITLE
Seems we should change default ad-hoc server value to empty?

### ISSUE THREAD

**Issue by hong620** [hrydgard/ppsspp#9865]
![screenshot_20170422-073543](https://user-images.githubusercontent.com/12625315/28620933-0b3510f0-724a-11e7-86b7-bb6aa75f1211.png)

seems it's time we should empty the default ad-hoc server adress value.

if recommend 'running own server' to users, we need more additional functions for convenience.
1. 'show user's own ip/port adress' when check the 'Bulit-in adhoc server active'
2. the button for copy that value to clipboard on android/windows
3. if user is so begginer on network, a button for other announcement article link
(about fortfoward or use other method like VPN)

**Comment by adenovan** [comment]
this is related to #7268  to play online many client isp still behind a nat or blocked the game connection port so tunneling it through a single port will be a good options to have between ppsspp instance. it will not compatible with the psp but we can play online more easily. if a public server provide proxying and tunneling of course it will make server bill higher. relay / proxying them is resource hungry on server with many client. it will make all player appears and it will be much suitable for playing adhoc games with internet connection . other benefit of tunneling it through single port is we can make direct connection between player if the client can port forward one port to be used as tunneler port. if user can't do port forward it will be relayed through public server. that is im trying to develop right now.

for local adhoc network betwenn ppsspp and psp the research it still on progress #9334  , if that research is done we can make PSP Mode options to play more easily with local friend either with ppsspp or psp.  there is another problem with host machine adapter i guess. 

and for the adhoc server default value there is no need to change that. its a credit for the original pro adhoc server author colbird for its works on reverse engineering the PSP matching library and the pro adhoc server. in the future if many isp give client public ip or we have global ipv6 support there is no problem with that implementation. and it will be still compatible either with psp or ppsspp to play.

so we can create a 3 mode adhoc network options  which each mode has its deficiencies and advantages.

1. Pro Adhoc Server Mode for PPSSPP and PSP through internet or Lan Infrastructure
2. Tunneled and relay Mode between PPSSPP 
3. PSP Original Mode for adhoc network betwen PPSSPP and PSP locally 

its better right?

**Comment by Hydroque** [comment]
I wouldn't worry about developing PSP and PPSSPP connectivity in one module. You should branch off and allow an option to determine which module to use. PSP->PC compat (which has limits) and PPSSPP->PPSSPP compat.

**Comment by ANR2ME** [comment]
It would also be nice to have a Adhoc Server Scanner (something like lobby scanner on most PC's LAN multiplayer games) which shows a list of available adhoc server within IP-ranges (ie. LAN IPs which includes VPN IPs), 
so even noobs can simply select the IP and connect to that adhoc server :) better than copy pasting the IP right?

**Comment by Hydroque** [comment]
Well there are definitely plans for people to make huge matchmaking lobbies like Gamespy did. Once more network support is added, you will see some pull requests probably.

**Comment by unknownbrackets** [comment]
So, 9b9f382b0b0e8513aaaa7300fd9736723143596f changed this.  Should we close this?

-[Unknown]
