### ISSUE TITLE
Android split-screen multitasking does not actually works.

### ISSUE THREAD

**Issue by andreyorst** [hrydgard/ppsspp#9866]
If I will open ppsspp with the second application via android's multitasking feature this will happen:
![default](https://user-images.githubusercontent.com/19470159/28671230-94a6048a-72e4-11e7-9417-95275479fe3c.png)
![default](https://user-images.githubusercontent.com/19470159/28671172-64d3a4b0-72e4-11e7-85f1-dd1320aa3a66.png)
And controls in this mode are totally messed up.

Maybe you should have a message that your app doesn't support split-screen like other apps do:
![default](https://user-images.githubusercontent.com/19470159/28671141-43ef42b8-72e4-11e7-8139-3cfbbc837e96.png)
(camera was a good example)

**Comment by Michal1324** [comment]
This can be fixed by openning supported window 1st like youtube then ppsspp about control just remap them

**Comment by hrydgard** [comment]
Yeah, we are (wrongly) using the display size instead of the actual window size to configure the graphics. This needs fixing.
