### ISSUE TITLE
UNO game doesn't work on PPSSPP (v1.4.2)

### ISSUE THREAD

**Issue by lexterror** [hrydgard/ppsspp#9867]
The game starts fine but the "cards" for playing UNO aren't visible...

I have the exact same issue as this user: http://forums.ppsspp.org/showthread.php?tid=7559&highlight=uno 

I've tried most previous versions and it's the same issue. I have also tried all options with no luck.

**Comment by sum2012** [comment]
We have open the issue in https://github.com/hrydgard/ppsspp/issues/9035
