### ISSUE TITLE
Font folder for Mac OSX?

### ISSUE THREAD

**Issue by JohnTitor95** [hrydgard/ppsspp#9868]
Ive been trying to play Yu-Gi-Oh TagForce 5 with a friend over LAN. However, the game seems to give him issues since he doesnt have the original psp font. Where do we place the font folder on Mac OSX? (we can't find any folder with assets/flash0/font.

**Comment by omarrrio** [comment]
Try either:
- Creating the path assets/flash0/font and put the fonts in there.
- Creating flash0/font right beside the ppsspp exe and put the fonts in it.

**Comment by JohnTitor95** [comment]
Where do we put the assets folder? We tried a bunch of combinations of assets/flash0/font or MacOSX/assets/flash0/font or just flash0/font, and we tried putting this in directly with the exe, in the folder with save data, in the folder with PSP right before savedata, the folder right before that, etc. Each time no luck.

**Comment by omarrrio** [comment]
PPSSPP Folder
 |
 |
 |
  ---PPSSPP.exe
 |
 |
 |
  ---Assets
 |       |
 |       |
 |        -----Flash0
 |                   |
 |                    ----Font
 |
 |
  ----Flash0
           |
            ----Font

**Comment by JohnTitor95** [comment]
Do we need Assets AND flash0 separately? also, is it assets or Assets? Also, we tried pretty much every combination of folder nestings besides having multiples. i.e. We tried every iteration of assets/flash0/font or flash0/font, etc. We just never did both an assets/flash0/font and flash0/font at the same time. Keep in mind, this is for Mac OSX. Im not sure where the OSX version is getting it's font.

**Comment by omarrrio** [comment]
Then i am sorry mate, try looking into the ini files, maybe one of them has the font folder path set there.

**Comment by JohnTitor95** [comment]
Oh, okay, we found it. Sorry, it looks like we are just retarded. We didn't realize this whole time we were running an .app file. The fonts were in there.

**Comment by unknownbrackets** [comment]
To override the fonts, make a flash0 directory next to SAVEDATA.  I'm not sure where this is on iOS.

So to clarify, there's two places where fonts can be:

1. In assets, which are replaced when you upgrade.  So you might see "lang" and "flash0" and "shaders" here, and "fonts" inside "flash0".
2. Next to your savedata, which should be kept on upgrade.  Inside a folder named PSP should be a "SAVEDATA" (for saved games) and "SYSTEM" for system settings.  "flash0" can be created here, and put a "fonts" folder inside there.

This goes for all platforms - Linux, Windows, Mac, iOS, Android, etc. - this is how you override fonts.  Where exactly this is on your platform is the same question as "where is my savedata?"

-[Unknown]

**Comment by JohnTitor95** [comment]
Oh, okay thanks! Seems to work on windows 7 at least, but i could have sworn we tried this on the mac, but it didn't work. Ill have to double check i guess.

**Comment by unknownbrackets** [comment]
Well, on Mac and Linux, saves are in ~/.config/ppsspp/ - that's a "hidden" folder by default in Mac OS X.

-[Unknown]

**Comment by JohnTitor95** [comment]
Yeah, i know. That's where we put the flash0/font folder but it didnt work.

**Comment by unknownbrackets** [comment]
I think it's different on iOS due to the way iOS manages files.  It's defined as the "Documents path" by iOS, and it's app-specific.  It'll be some long path.

Don't really mess with the network stuff too much, in part because a lot of what's there now is mostly purpose-built for Monster Hunter, a game I don't have.  The networking APIs are also more complex to test, and I'm not terribly interested in any PSP games that use it, so it just doesn't excite me much.

It could be due to ports (I think some "port offset" feature was added because of this.)  Linux and Mac don't allow user programs to use ports < 1024, but Windows does.  If only Windows doesn't crash, the game is probably using low-numbered ports (a common thing PSP games would do, since they had no such restrictions.)

-[Unknown]
