### ISSUE TITLE
Audio Doesn't Play After Hibernation

### ISSUE THREAD

**Issue by tilkinsc** [hrydgard/ppsspp#9871]
Windows 7.

It would be nice if enabling the sound again refreshed the audio context. Nothing is even being sent to speakers. Restarting fixed it.

**Comment by Michal1324** [comment]
This is probably related to this issue #9805

**Comment by unknownbrackets** [comment]
Has this improved in the latest git build?

-[Unknown]

**Comment by tilkinsc** [comment]
I am on windows 10, idk. Will test when I get the chance.

**Comment by hrydgard** [comment]
@tilkinsc  got a chance yet? There's a possibility this has improved in the recent builds.

**Comment by tilkinsc** [comment]
Close this
