### ISSUE TITLE
New Dualshock 4 Controller not Recognized

### ISSUE THREAD

**Issue by VVVFO** [hrydgard/ppsspp#9872]
The new dualshock 4 does not get recognized in both macOS and Ubuntu 16.04 version of PPSSPP, the following manual tests have been done:

Testings done for macOS:

- New Dualshock 4 + PPSSPP 1.4.2 + macOS 10.12.5 + MacBook Pro 2016 -> **Doesn't work**
- New Dualshock 4 + OpenEmu + macOS 10.12.5 + MacBook Pro 2016 -> **Works**
- Old Dualshock 4 + PPSSPP 1.4.2 + macOS 10.12.5 + MacBook Pro 2016 -> **Works**

The above 3 results are perfectly reproduced on another Mac (MacBook Air mid-2011).

Testings done for Ubuntu 16.04:

- New Dualshock 4 + PPSSPP 1.4.2 + Ubuntu 16.04 + MacBook Air Mid-2011 -> **Doesn't Work**
- New Dualshock 4 + `jstest-gtk` + Ubuntu 16.04 + MacBookAir Mid-2011 -> **Works**

Based on the above result I believe this is an issue of PPSSPP. See this link for the difference between the "new" and "old" dualshock 4: [https://www.psu.com/feature/31122/New-PS4-Controller-vs-original-DualShock-4--what%E2%80%99s-the-difference](https://www.psu.com/feature/31122/New-PS4-Controller-vs-original-DualShock-4--what%E2%80%99s-the-difference).

Edit: additional information

For cases that "doesn't work":

- changing from Bluetooth connection to USB did not help
- key presses are not picked up (cannot use controller to "select a new key for XXX")

**Comment by unknownbrackets** [comment]
See #9825.

-[Unknown]
