### ISSUE TITLE
Work around for pixel shuddering with Nearest texture filter?

### ISSUE THREAD

**Issue by tilkinsc** [hrydgard/ppsspp#9878]
I get shuddering when I am using nearest while moving, however linear looks better on terrain and distanced objects. Nearest looks better on near and detailed objects.

Linear:
![image](https://user-images.githubusercontent.com/7494772/28949771-f77fa37e-788c-11e7-87ed-0e628f30071e.png)

Nearest:
![image](https://user-images.githubusercontent.com/7494772/28949784-052b6bf2-788d-11e7-8631-aa1d178c781f.png)

Is there anyway I can improve this? I was figuring we can try swapping bilinear for trilinear filtering, but I don't know if it's really possible to do this. This method fixes some of the pixel shuddering in the game programming tests I have done in the past.

**Comment by unknownbrackets** [comment]
You can enable further sampling by enabling anisotropic in the settings.  The game can also specify mipmap levels and activate mip and min linear to get what you probably mean by trilinear.

Presumably this improves with higher render resolutions, right?

-[Unknown]

**Comment by Hydroque** [comment]
It does indeed improve with increasing render resolution (up to max), but it still shudders. Anisotropic filtering is x16. I have mipmapping enabled.

**Comment by tilkinsc** [comment]
I wasn't able to fix this, but I suspect that they don't use mipmaps for the terrain so too many pixels draw for the area. Which makes sense because they were pushing the PSP's ability. At the same time it couldn't be because less pixels to draw is desirable.

 I wonder if its possible to generate mips for things that just don't use it. Like going back to including PNGs or JPEGs the like into games, which don't feature in-file mipmaps like DDS DXT or S3TC (or force you to load separate files for mipmaps you have to make yourself). You'd call, in open, `glGenerateMipmap()`.

**Comment by tilkinsc** [comment]
Actually, setting it to auto fixes everything, giving it a few seconds.

**Comment by hrydgard** [comment]
Really? Wouldn't have expected that.

Either way, autogen mipmap is definitely something that can be added. We used to do that but don't anymore since we now load the native mipmaps (since a long time), but if they aren't there, we could generate them.

**Comment by tilkinsc** [comment]
Yeah I noticed things flickering and then going correct.
