### ISSUE TITLE
Make PPSSPP be built in windows without MSVS

### ISSUE THREAD

**Issue by Hydroque** [hrydgard/ppsspp#9879]

**Comment by hrydgard** [comment]
It's probably possible with some minor patches and changes to the CMakeLists.txt file, but I don't think anyone has done the setup work.

**Comment by Hydroque** [comment]
*sighs* When ya want something to build right you gotta do it yourself (in the C/C++ world)

lol

**Comment by unknownbrackets** [comment]
What's the motivation for this?

-[Unknown]

**Comment by Hydroque** [comment]
For people who think MSVS is literal cancer

**Comment by hrydgard** [comment]
People who think that are silly, MSVC has a perfectly good compiler. I guess you could object to the closed-source nature, but I don't see how that's cancer. Anyway, I guess compiling with clang or something under Windows is still a legitimate if a bit unnecessary goal, so leaving open.

**Comment by Hydroque** [comment]
I'm sort of working towards it. MSVC is more like aids. It is the reason for a few of the posts I put here. Very unintuitive packaging, too. Does MSVC ship with only compiler and related tools? I do not dare burden another installation of OS, if anything a virtual PC.

**Comment by unknownbrackets** [comment]
This has now been done for libretro, I believe.  Please comment if you believe otherwise.

-[Unknown]

**Comment by Hydroque** [comment]
Do you have any commits to clarify what you mean?

**Comment by unknownbrackets** [comment]
https://github.com/hrydgard/ppsspp/pulls?utf8=%E2%9C%93&q=is%3Apr+mingw+is%3Aclosed+

-[Unknown]

**Comment by Hydroque** [comment]
Well done!
