### ISSUE TITLE
PPSSPP on Windows 10 help

### ISSUE THREAD

**Issue by blazingkyuubii** [hrydgard/ppsspp#9880]
Hey there, I recently played GoW on my PPSSPP on Windows 10. It doesn't seem to work well with my laptop, there's some cracky sound and a little bit of lag on the gameplay. I didn't allow it to go beyond 60fps btw.

Here are my specs:
Core i7-7500 (2.70 GHz)
Nvidia GeForce 920MX

Just ask me if you need more info about my laptop.

Can y'all please help me get the perfect settings for my laptop? Not only for playing GoW but also playing other games! ^^

**Comment by Michal1324** [comment]
Lower the rendering resolution and enable speed increase options you can try the Lastest PPSSPP build and try to use Vulkan and see if it works good enough

**Comment by Hydroque** [comment]
@blazingkyuubii did you leave the options at default settings when you ran GoW?

**Comment by blazingkyuubii** [comment]
@Michal1324  Hey there, I wasn't sure about the enable speed increase (idk where is it lol) but when I tried it, Vulkan on my version isn't yet compatible with buffering settings, and GoW needs the settings to be on buffering. So I changed it and it stopped working.

@Hydroque I saw some settings from another website on how to have a best settings, dumb me didn't realize wth im doing, ended up being soooo laggy. I had to reset to default. Then do what michal commented. 

I somehow experimented too, I lowered the settings but it's still not that good.

**Comment by unknownbrackets** [comment]
Try the latest git build.  Vulkan works better and may perform better on your hardware.

If you're not getting a notice that warns you that crackling sound probably just means the game is running too slow, you're probably running an older, slower, buggier version of PPSSPP than you should.  The latest release has that warning.

This game in general is especially demanding.  There are some hacks on the forum which help (by patching the game.)

-[Unknown]

**Comment by blazingkyuubii** [comment]
@unknownbrackets i just recently downloaded ppsspp too, probably just a month ago since I got this laptop also a month or less ago. So yeah I'm testing Vulkan right now and it's actually amazing, but there are still a bit of cracks and just bits of lags. Is this the best it can do?

**Comment by Hydroque** [comment]
Yeah get the latest version. About a month ago is about the time we switched to v1.4 and v1.3 is hella obsolete.

**Comment by blazingkyuubii** [comment]
@Hydroque yeah yeah the current version is 1.4.2 right? That's the one I downloaded since that's what's on the top. I tried Vulkan already and again it's working damn good, but it has some sound cracks but just some bits, and some gameplay lags. Is this the best of it? Or I can still do some changes to totally remove all the cracks and lags?

**Comment by blazingkyuubii** [comment]
![image](https://user-images.githubusercontent.com/28000565/29073172-30ad80be-7c7d-11e7-86b8-245daa01b64c.png)

And now I tried Assassin's Creed and I'm sad lmao. I changed back to OpenGL but it became black so switched back to Vulcan. Disappointed.

**Comment by Michal1324** [comment]
Try Directx mode then

**Comment by blazingkyuubii** [comment]
Assassin's Creed is checked. Now the only issue I have is with GoW, another freaking issue. Since I'm using Vulkan happily, after beating Basilisk, the screen went black but the game is still on. The cutscene's audio is playing but the video isn't. No gameplay at all.

sighs

**Comment by unknownbrackets** [comment]
Vulkan currently doesn't support some features - it may prevent video from playing correctly.

-[Unknown]

**Comment by blazingkyuubii** [comment]
@unknownbrackets damn what should i do then lol, wanted to continue the game but the only way to play it like a normal person is through Vulkan.

**Comment by hrydgard** [comment]
You should wait for us to fix it or play on something more powerful, like a PC :)

So are you saying that after the cutscene, the gameplay doesn't resume? A savegame or savestate before the error might help investigation.

**Comment by Hydroque** [comment]
Could we get an update? We are at 1.5 and @hrydgard is proud of the vulkan improvements.

**Comment by unknownbrackets** [comment]
Vulkan works pretty well now and OpenGL has some speed improvements.

I'm going to close this since it hasn't had feedback in a while.

If this is still an issue, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
