### ISSUE TITLE
Midnight club 3 and Midnight club LA remix sound disappeared

### ISSUE THREAD

**Issue by Blacob777** [hrydgard/ppsspp#9884]
Android in new dev version v1.4.2-282 sound disappeared

**Comment by Blacob777** [comment]
the sound is lost not only in this game, but rarely lost

**Comment by Hydroque** [comment]
On 'Android in dev version v1.4.2-282' the sound disappears randomly on what device?

**Comment by unknownbrackets** [comment]
The sound was present in v1.4.2-281-g3ce8680d9?  Or has it never played?  What's the first version it stopped working in?

-[Unknown]

**Comment by hrydgard** [comment]
Likely related to #9771

**Comment by hrydgard** [comment]
This should be fixed now, please try the latest builds from https://buildbot.orphis.net/ppsspp/

**Comment by marosis** [comment]
Same status?

**Comment by hrydgard** [comment]
@marosis are you saying that you experience this, or not? I'm gonna guess not, and close.

**Comment by marosis** [comment]
I've tryed to help you

**Comment by marosis** [comment]
Tried*
