### ISSUE TITLE
The Godfather black square instead of radar (ANDROID)

### ISSUE THREAD

**Issue by Blacob777** [hrydgard/ppsspp#9885]
![screenshot_2017-07-16-00-30-25-377_org ppsspp ppsspp](https://user-images.githubusercontent.com/29165096/29004457-e68a2e94-7af9-11e7-824e-faa6b225f847.png)

**Comment by hrydgard** [comment]
Did you by any chance uncheck the setting "Simulate block transfer effects"?

**Comment by Blacob777** [comment]
thank you it worked

**Comment by Blacob777** [comment]
vulkan is still a black square

**Comment by hrydgard** [comment]
Yup, our Vulkan backend is still lacking some functionality. I think we have a separate issue for various Vulkan problems, so closing this one.
