### ISSUE TITLE
Create Unique Tag for old, possibly fixed with time issues

### ISSUE THREAD

**Issue by Hydroque** [hrydgard/ppsspp#9888]
Ideas? I went through all 750+ issues and picked out ones that should be brought back by commenting on them or closed. I think it is pretty structured, but there was a lot of issues that couldn't be resolved without further testing. No Feedback tag is probably what that is used for, but I don't really see it being used too much. For this specific purpose, I don't think feedback tag is needed for this strain of issues, moreso a 'Not current build' tag.

**Comment by hrydgard** [comment]
I changed the name of it to "No feedback / Outdated?". Please use that tag for such issues.
