### ISSUE TITLE
Jeanne d'Arc Bug in latest ppsspp for Android.

### ISSUE THREAD

**Issue by blackman91** [hrydgard/ppsspp#9891]
Using vulkan in Android 7, also changing apps and going back to ppsspp makes it crash using vulkan.

![screenshot_20170808-183515](https://user-images.githubusercontent.com/6578180/29099148-14179dd6-7c69-11e7-838d-458141c6b048.png)

**Comment by deadair3210** [comment]
Other than the crashing, are there any other bugs? I can't seem to see any

**Comment by blackman91** [comment]
Did you see the screenshot? The character models are in the wrong position. Happens in every stage.

**Comment by blackman91** [comment]
Another more clear example.
![screenshot_20170808-211936](https://user-images.githubusercontent.com/6578180/29102531-6a96cb3a-7c7f-11e7-886c-af8806067219.png)

**Comment by hrydgard** [comment]
Yeah, Vulkan support is still work-in-progress and has bugs like this. Thanks for the report.

**Comment by unknownbrackets** [comment]
I believe this bug was fixed recently - it's rendering properly now.  Please comment if you're still seeing it and we'll reopen.

-[Unknown]
