### ISSUE TITLE
[Android] Version 1.4.2-308 Interface display problem

### ISSUE THREAD

**Issue by mpamxl** [hrydgard/ppsspp#9892]
When I play the game halfway through home to return to the desktop and then re-enter the PPSSPP game, the interface will be unusual. Please fix it.

**Comment by ThePhoenixRises** [comment]
Hi mpamxl,
What do you mean?
Take screen shot on your Android device, by pressing Down Volume & Power button at same time.
And upload it on here, to explain what you mean.

**Comment by hrydgard** [comment]
That would probably be Android, returning to the home screen while playing and then going back to the emulator. After recently redoing the screen sizing code, I tested it for a bit on a few phones and it worked, but I guess there might still be some remaining issues...

**Comment by mpamxl** [comment]
I don‘t know why I upload pictures always fail..
I have XiaoMi2S..
Then I would like to ask can you optimize multi - core processing?
Because my device is now running some games is caton..

**Comment by Michal1324** [comment]
About the performance mpamxl either your gpu or cpu is holding you back don't expect luck with Aderno 320

**Comment by hrydgard** [comment]
Should be mostly solved now, remaining issues tracked in #10128
