### ISSUE TITLE
Danganronpa Bug in latest ppsspp for Android.

### ISSUE THREAD

**Issue by blackman91** [hrydgard/ppsspp#9896]
As you can see in the screenshots using the opengl backend you can talk to people normally but using vulkan you can't select them at all or any objects, which is a shame because this game seems to run full speed and fps on vulkan but not in opengl in Android.
![screenshot_20170812-000845](https://user-images.githubusercontent.com/6578180/29238123-8559eada-7ef3-11e7-96d7-899e3a5d94cd.png)
![screenshot_20170812-001011](https://user-images.githubusercontent.com/6578180/29238124-92e93660-7ef3-11e7-802a-528309ff4ed6.png)

**Comment by hrydgard** [comment]
Yeah, the Vulkan backend is still missing some features like framebuffer readback, which this game relies on.

**Comment by unknownbrackets** [comment]
I wonder if it still runs at full speed...

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, the synchronous readback will slow it down, but it will still likely be faster than GL. Might be enough as the game isn't that intensive, IIRC. @blackman91 can you try with a fresh build and report the performance you're getting?

**Comment by blackman91** [comment]
Using latest dev I get the now the same performance with GL and Vulkan.

**Comment by hrydgard** [comment]
So it's too slow?

**Comment by blackman91** [comment]
Same with both backends as screenshot 1 now.

**Comment by hrydgard** [comment]
Thanks for reporting that. We might be able to solve this with asynchronous readback, which is easier to do reliably in Vulkan.
