### ISSUE TITLE
[Request] Let layout editor ignore aspect ratio when resizing screen.

### ISSUE THREAD

**Issue by blackman91** [hrydgard/ppsspp#9897]
The layout editor is great but when resizing the screen manually it can't ignore the aspect ratio, so you can't change width and height individually, this feature would be useful for android if you play with touchscreen controls so that your fingers don't cover the gameplay screen, resizing the screen any way you want even ignoring the aspect ratio is something other Android emulators have done successfully like drastic. Do you think this could be added for future releases?

**Comment by Gamemulatorer** [comment]
This is not implemented?

**Comment by hrydgard** [comment]
This is fixed with the new Aspect Ratio setting.
