### ISSUE TITLE
Graphical bugs in FFT.

### ISSUE THREAD

**Issue by blackman91** [hrydgard/ppsspp#9904]
Using opengl in android latest dev build, does not happen with vulkan.
![screenshot_20170816-212351](https://user-images.githubusercontent.com/6578180/29393904-743b550e-82cc-11e7-8ac2-6e81a82a9082.png)

**Comment by unknownbrackets** [comment]
Make sure you are NOT using "retain changed textures" and also try turning off "lazy texture caching".

-[Unknown]

**Comment by blackman91** [comment]
I am using default settings, those are not on. The bug still appears.

**Comment by hrydgard** [comment]
Thanks for reporting, probably some regression from the state optimizations.

**Comment by hrydgard** [comment]
Curiously, adding:

	gstate_c.Dirty(DIRTY_FRAGMENTSHADER_STATE);

to the beginning DrawEngineGLES::DoState() solves it. But in that case I'd expect it to be broken in all the backends.. Hm.

**Comment by hrydgard** [comment]
Found it, fix committed.
