### ISSUE TITLE
App broken on Android after gcd4304978

### ISSUE THREAD

**Issue by GuilhermeGS2** [hrydgard/ppsspp#9907]
Any version after gcd4304978 isn't working on my phone, the app stops working when I try to open it. Probably something wrong with sustained performance mode, don't know if it's working well on Android 7+, but not here on Android 6.1.1.

**Comment by brujo5** [comment]
Work fine. 
Tested in one plus 5 and galaxy s6 

Sustained perfonanse mode require sdk 24 android 7 up

**Comment by hrydgard** [comment]
@GuilhermeGS2 Sorry about that, should be fixed with the last commit.
