### ISSUE TITLE
Error in FFT on latest dev build ppsspp for Android.

### ISSUE THREAD

**Issue by blackman91** [hrydgard/ppsspp#9908]
Using opengl with default settings I constantly get this error message, what does it mean?
![screenshot_20170817-154815](https://user-images.githubusercontent.com/6578180/29433235-ef87b7ec-8363-11e7-9166-89d44370dcdb.png)

**Comment by hrydgard** [comment]
That's bad, it means it failed to compile a vertex shader.

Can you get ADB logs when this happens? What hardware is that?

**Comment by blackman91** [comment]
I am using a motog5 plus, will try to get a log but my device is not rooted.

**Comment by hrydgard** [comment]
Don't need root for ADB logs, just USB and you need to put the device in developer mode (which is very easy and does not require rooting). Just google up some instructions (sometimes you don't need a driver even though old instructions say you do)

**Comment by unknownbrackets** [comment]
If you enable reporting (in Settings -> System -> Enable compatibility server reports), it'll log them to the server.  No need to use adb then.

When reported, it'll show up under one of these (whatever region you use):
http://report.ppsspp.org/games?name=fantasy%20tactics

Click "See reported log data for this game." after clicking into the region to see it.  I see some errors but I think they were a state optimizations issue that was already fixed recently.

-[Unknown]

**Comment by blackman91** [comment]
Thanks I finally had time to play I think mine is the third one because I am using the latest dev:
![screenshot_20170823-161206](https://user-images.githubusercontent.com/6578180/29638845-324a0544-881e-11e7-9c19-2c8781e1d6b9.png)

**Comment by hrydgard** [comment]
Huh, thanks. That's really curious..

**Comment by unknownbrackets** [comment]
Are you using hardware tessellation?

-[Unknown]

**Comment by blackman91** [comment]
Nope, default settings.

**Comment by unknownbrackets** [comment]
Interesting.  My best bet is there's no some case where we use an initialized ShaderId when all state optimizations are optimized away, or something.  That shader is trying to do hw transform + tessellation + throughmode, afaict.  It's a very confused shader.

-[Unknown]

**Comment by hrydgard** [comment]
You mean uninitialized? ShaderId has a constructor that zeroes itself so there's gonna have to be some very strange bug for that.

Maybe the shader cache got broken? Can you try to "clear cache and settings" or whatever it's called for the app in Android app settings (as that's where store the shader cache)?

**Comment by unknownbrackets** [comment]
Does this still happen?

**Comment by unknownbrackets** [comment]
We did fix some bugs in the shader cache since.  I'm going to close this - please comment if it's still happening and we'll reopen.

-[Unknown]
