### ISSUE TITLE
[Linux] PS3 wireless controller don't work

### ISSUE THREAD

**Issue by andreyorst** [hrydgard/ppsspp#9910]
Hello. I'm running Arch Linux and ppsspp version from git installed through AUR. And i have a Playstation(R)3 controller which works out of the box via USB and supports bluetooth connection with `bluez`, `bluez-plugins` and `bluez-utils` installed. So I tested my controller in some apps and there are results:
- [X] KDE Settings
- [x] PCSX2
- [X] Steam
- [X] Dolphin Emu
- [ ] PPSSPP
- [ ] PPSSPP-Qt

So i think that you can assume that controller is working in my system. But in ppsspp, both SDL and Qt versions from `community` repo and `ppsspp-git` from AUR, there is no response at all. Literally nothing happens. I have a setting app opened in background and i can see which key i press, but ppsspp cant register that. And i'm sure i can remember that in 2016 my controller worked this way.

So can you help me, because google shows nothing but old your github issues that are already closed and did not contain any useful info (for me at last). If i can provide any logs please specify which logs do you want and i'll send it to you.

**Comment by mrcmunir** [comment]
I think is old bug i tested it with ps3 wireles and won't work no key assigned and the analog can't move
Need test what commit are broken

**Comment by vnctdj** [comment]
@andreyorst :
> And i'm sure i can remember that in 2016 my controller worked this way.

Bisecting should help then, [here](https://github.com/hrydgard/ppsspp/wiki/How-to-bisect-to-find-what-broke-a-game) is some help if needed.

**Comment by hrydgard** [comment]
I'm sure this is the same SDL2 controller thing that everyone is reporting. For some reason the new controller stuff requires profiles for every controller otherwise it gets ignored.

Not sure what to best do about it..

**Comment by vnctdj** [comment]
> > I don't know the freshness of Arch Linux repositories

> FRESH AS MOUNTAIN AIR

I'd rather say several months old :)
From [ppsspp-git Arch Linux repo](https://aur.archlinux.org/packages/ppsspp-git/) : `Last Updated: 2017-05-19 23:32`

**Comment by hrydgard** [comment]
@andreyorst  See #9825

**Comment by andreyorst** [comment]
> I'd rather say several months old :)

I forgot the `<sarcasm>` tag. Well I'll install ppsspp form [link, that you mentioned](https://build.ppsspp.org/?page/downloads#linux) and will report back, but if this issue is a duplicate of #9825 you can close it

**Comment by binaryronin** [comment]
@vnctdj That is the last time the actual PKGBUILD had to be updated, when running any AUR Git package it pulls from the latest master and compiles. So by installing the Git package you get a snapshot of the latest version on any given day.

Also, I have the same issue with the DS4V2, which is likely due to #9825 .

**Comment by SoulEst** [comment]
I created a [pull request](https://github.com/hrydgard/ppsspp/pull/9954) for adding the mappings of the PS3 controller under USB and Bluetooth.

**Comment by unknownbrackets** [comment]
Since that was merged, is this solved now?

-[Unknown]

**Comment by SoulEst** [comment]
For 1st party PlayStation 3 controllers, yes.

**Comment by andreyorst** [comment]
After last Archlinux update I cant pair my DualShock3 via Bluetooth, so i can't check now :D

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other issues, and sometimes certain settings may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.

-[Unknown]
