### ISSUE TITLE
Dante inferno texture bug in vulkan api after state optimizations

### ISSUE THREAD

**Issue by brujo5** [hrydgard/ppsspp#9911]
Here before 

![screenshot_20170818-001333](https://user-images.githubusercontent.com/4172898/29446667-ab50a970-83aa-11e7-950d-d997ef450f2a.png)

After

![screenshot_20170818-001204](https://user-images.githubusercontent.com/4172898/29446679-b88bb346-83aa-11e7-9456-5463b1728071.png)

This happend con galaxy s6 using vulkan

**Comment by hrydgard** [comment]
Huh, that's odd, thanks for reporting. As a workaround, you should be able to simply turn off the vertex cache in graphics settings until I can fix it.

**Comment by brujo5** [comment]
Thanks 

I did but nothing change. Tested in ppsspp-v1.4.2-362-g750c124c3-android.apk

**Comment by brujo5** [comment]
Ok 

Culprid is from this range ppsspp-v1.4.2-309 to ppsspp-v1.4.2-323
No build available for download. Cant test more.

**Comment by hrydgard** [comment]
OK, thank you. Will try to figure it out.

**Comment by brujo5** [comment]
Work fine in opengl
![screenshot_20170818-160030](https://user-images.githubusercontent.com/4172898/29479298-8eaac15a-842e-11e7-932a-861b77db4b4b.png)

**Comment by brujo5** [comment]
fixed thx
