### ISSUE TITLE
Widget stops working after restart

### ISSUE THREAD

**Issue by shae23** [hrydgard/ppsspp#9920]
A widget for ppsspp creates a shortcut to a specified game, which works perfectly until the phone is restarted, then the widget fails to launch said game, happens on lollipop, marshmallow and nougat

**Comment by unknownbrackets** [comment]
This is definitely reproducible, strange.

-[Unknown]

**Comment by hrydgard** [comment]
I have a feeling it's got something to do with the file permission stuff - maybe PPSSPP was "running enough" in the background that the platform still gave permission, though we forget to ask for it when starting "from the command line" on Android so on next reboot that's forgotten.

**Comment by hrydgard** [comment]
Eh, nope - it just doesn't get the parameter anymore after a reboot. What...

**Comment by hrydgard** [comment]
Okay so extras don't persist very well. I'm moving the filename into the "Data" part of the shortcut object, that seems to work better.
