### ISSUE TITLE
Windows issue - PPSSPP menu is blank, clicking makes blue squares

### ISSUE THREAD

**Issue by agjios** [hrydgard/ppsspp#9922]
As you can see in the screenshot, when launching PPSSPP, I can't even get the menus to load. Windows 10 64 bit, i7 processor, GTX 560 Ti graphics card. The game worked for the past 5 months, but when going to it this week, it started presenting this error.

Any ideas where to start troubleshooting? I've tried reinstalling. 

If I click around, the selected portion where the menu item is supposed to be turns that blue color. So, it is like my menu items have been replaced with invisible squares that turn blue when I click on them. Games launch fine, but then trying to use save states brings me back to this messed up menu area.
![ppsspp error1](https://user-images.githubusercontent.com/31225003/29540707-70a53118-8695-11e7-9f41-d83d8cbcff3f.PNG)

**Comment by hrydgard** [comment]
Hm, never seen anything like this. Maybe a failure of the new font rendering, but other than that this really puzzles me - still shouldn't look this weird.

One thing to try:  Edit ppsspp/memstick/PSP/SYSTEM/ppsspp.ini and change GPUBackend to 1, 2 or 3. 3 probably isn't going to work (Vulkan) but 2 or 1 might (D3D11, D3D9). 

Also update your graphics drivers, and please also try the latest build from buildbot.orphis.net/ppsspp/ .

**Comment by Michal1324** [comment]
If you are running some overlay on top of PPSSPP Don't it causes PPSSPP to freak out sometimes

**Comment by unknownbrackets** [comment]
Does this still happen in the latest git build?

-[Unknown]

**Comment by unknownbrackets** [comment]
Without feedback, assuming this was caused by the overlay or graphics drivers being out of date, as mentioned above.  Haven't heard any other reports.

Please comment if it's still happening and you have more info, and we'll reopen.

-[Unknown]
