### ISSUE TITLE
FF:Type 0 Graphic bug (Android) 

### ISSUE THREAD

**Issue by Saramagrean** [hrydgard/ppsspp#9926]
Use PPSSPP latest build (391) on my PC is works flawlessly all backend, This problem is only found on Android, Backend OpenGL only,  Vulkan graphic is work fine.

My android device: Huawei P9+ (CPU: Kirin 955, GPU: Mali T880)
Settings: default. 

When enabled Hardware Transform. 

![screenshot_20170823-074812](https://user-images.githubusercontent.com/26355472/29593935-85fa3a52-87d7-11e7-8d0f-c62d46c47ec3.png)

When disabled Hardware Transform. 

![screenshot_20170823-074819](https://user-images.githubusercontent.com/26355472/29593972-d601024c-87d7-11e7-8768-72f15bba29e5.png)

**Comment by unknownbrackets** [comment]
Reminds me of #4199.  Does vertex cache affect this?

-[Unknown]

**Comment by Saramagrean** [comment]
Oh, sorry for the delay reply.
I tried disabled Vertex cache but graphical issue still present.

**Comment by hrydgard** [comment]
I guess for now, use Vulkan...  Wonder if it's our bug or a driver bug.

**Comment by Saramagrean** [comment]
OK, Sir.

**Comment by unknownbrackets** [comment]
Could it be some NEON swizzling bug or something?

-[Unknown]

**Comment by hrydgard** [comment]
You mean in the vertex decoder? Seems plausible I guess.

**Comment by hrydgard** [comment]
@Saramagrean does this still happen in the latest builds?

**Comment by Saramagrean** [comment]
Yes, Latest build (747) Is still the same with OpenGL. 😂
![screenshot_20180324-223716](https://user-images.githubusercontent.com/26355472/37865793-2c2dcfae-2fb4-11e8-92a9-25b4c03ab2bb.png)

**Comment by hrydgard** [comment]
I don't get this :)  Has to be some really obscure graphics driver bug...

**Comment by unknownbrackets** [comment]
It looks kinda amazing in a way.

I wonder if this area draws without vertex colors or something.  There must be something about the prims here that triggers the bug...

-[Unknown]

**Comment by unknownbrackets** [comment]
Brave Story was mentioned in a presumed duplicate - this doesn't use flat shading there right?

I wonder if something is expected to be aligned for some drivers but is not sufficiently aligned...

-[Unknown]

**Comment by hrydgard** [comment]
Since the triangles look "whole", at least the positions got to be decently aligned...

**Comment by Saramagrean** [comment]
Try again with v1.6.3-483-g1f881d790, this issue is gone!!. 
Thanks for your hardwork, sir. :+1:
