### ISSUE TITLE
PLEASE ADD BUTTON PAUSE

### ISSUE THREAD

**Issue by Endarko** [hrydgard/ppsspp#9928]
Please ppsspp added button pause. But pause is still on the game screen. Not to ppsspp settings

**Comment by Kxze** [comment]
I don't understand this, do you want to be able to bind a button to pause the emulation?

**Comment by hrydgard** [comment]
Yeah I'm rather confused too. On platforms without a Back button we do show a pause button. Do you want to be able to remove it?

**Comment by Endarko** [comment]
I mean the touch button stops while playing the game. button rich L R Star button. but the button stops working. to stop when playing the game. so we can grab the screenshots easily

**Comment by unknownbrackets** [comment]
Do you mean that the buttons fade out?  You can change "Auto-hide buttons after seconds" under Controls settings to stop this from happening.

-[Unknown]

**Comment by unknownbrackets** [comment]
Still unclear what's meant here.  Another possible interpretation: you can turn off immersive mode in settings, which will keep your phone's back button visible without having to gesture to bring it back.

I'm going to close this now, but if that doesn't help, please comment with more detail.

-[Unknown]
