### ISSUE TITLE
cant load kingdom hearts since recent update

### ISSUE THREAD

**Issue by davidbepo** [hrydgard/ppsspp#9932]
when i click the game icon the screen flickers and one secons later the emulator crashes
i got this when launching from terminal:
WriteRest: op out of range (0x40d5f30d uses 0x5588b9221a10)

**Comment by hrydgard** [comment]
I'm guessing Linux? Can you try running it under GDB and get us a stack trace? (or lldb if on mac?)

     gdb your/path/to/PPSSPPSDL

Then start kingdom hearts, wait for it to crash

Then type:

     bt

and paste the output here.

**Comment by davidbepo** [comment]
yes im on linux

**Comment by davidbepo** [comment]
the output:
(gdb) r
Starting program: /opt/ppsspp/PPSSPPSDL 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff3685700 (LWP 9036)]
OpenGL 2.0 or higher.
Pixels: 960 x 544
Virtual pixels: 960 x 544
I: gpu_features.cpp:136: GPU Vendor : Intel Open Source Technology Center ; renderer: Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2)  version str: 3.0 Mesa 17.1.7 ; GLSL version str: 1.30
I: thin3d_gl.cpp:276: Shader module created (0x555557bf0810)
I: thin3d_gl.cpp:276: Shader module created (0x555557bf1390)
I: thin3d_gl.cpp:276: Shader module created (0x555557bf1a20)
I: thin3d_gl.cpp:276: Shader module created (0x555558044a70)
I: NativeApp.cpp:599: NativeInitGraphics
[New Thread 0x7fffd7fff700 (LWP 9037)]
I: NativeApp.cpp:676: NativeInitGraphics completed
[New Thread 0x7ffff3644700 (LWP 9038)]
E: PCMain.cpp:662: Output audio samples: 1024 (requested: 2048)
loading control pad mappings from gamecontrollerdb.txt: SUCCESS!
[New Thread 0x7fffc77fe700 (LWP 9259)]
[New Thread 0x7fffc5dfc700 (LWP 9260)]
[New Thread 0x7fffc55fb700 (LWP 9261)]
WriteRest: op out of range (0x401b330d uses 0x5555561cda10)

Thread 5 "PPSSPPSDL" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc77fe700 (LWP 9259)]
0x00000000401b3304 in ?? ()
(gdb) bt
#0  0x00000000401b3304 in ?? ()
#1  0x0000000000000000 in ?? ()

**Comment by hrydgard** [comment]
This might be fixed in the latest build after 8d0498303ac438cd276e3ad9485ca4cccbc7b61a, can you retest?

**Comment by davidbepo** [comment]
the game now indeed loads correctly :)
but the screen still flickers when i click the icon

**Comment by hrydgard** [comment]
Thanks for testing!
