### ISSUE TITLE
PPSSPP crash problem android..

### ISSUE THREAD

**Issue by hanooty** [hrydgard/ppsspp#9934]
PPSSPP v1.4.2-393-g2180b1d55 last build for android have crash when loading many games...please try to fix it or give a solution 
#SETTINGS
by default

**Comment by hrydgard** [comment]
this should be fixed in -394. Unfortunately the build server seems not to have built it for some reason? I'm going to make another commit soon, and we'll see if it works...

**Comment by hrydgard** [comment]
OK, please download and try the latest from https://buildbot.orphis.net/ppsspp/ .

**Comment by hanooty** [comment]
Thanks alot
