### ISSUE TITLE
Vulkan: Software skinning off slow on certain Mali devices in Monster Hunter

### ISSUE THREAD

**Issue by PepeJulio** [hrydgard/ppsspp#9944]
Up until last week (I believe?) Monster Hunter games performed at stable 30 FPS, but now they perform at roughtly 2 FPS.

**Comment by PepeJulio** [comment]
To be more precise, build v1.4.2-373-gc2bd739b4.android is the last one which performs properly.

**Comment by hrydgard** [comment]
That would be #9916, weird. In my testing so far I've only seen performance increases, but I'll look into it.

**Comment by hrydgard** [comment]
Which specific Monster Hunter game slowed down, and on what hardware?

**Comment by PepeJulio** [comment]
Both MHFU and MHP3rd. Phone is Xperia XA, Mediatek powered and our ever-failing Mali T-860MP2.

**Comment by hrydgard** [comment]
Not seeing this at all on a fresh build on my Mali-powered S8, performance is great.

Tried resetting settings to default? If you want to try this, please save your PSP/SYSTEM/ppsspp.ini first so we can check for differences.

**Comment by PepeJulio** [comment]
Well, looks like unticking Software Skinning was causing it. But why? Up until now, I've always disabled it since it used to give performance improvements on Monster Hunter games.

Well, it still isnt like if I was able to play the game anyway. I don't know what's the deal with my GPU, but the problem in issue #9895 is still present.

In any case, thanks for the support. It's nice to see that this emulator has such active devs.

**Comment by hrydgard** [comment]
Oh, interesting. It shouldn't drop performance like that, needs investigation. Thanks for pinpointing it.

Though I can't repro #9895 on any of my Vulkan-capable devices..

**Comment by PepeJulio** [comment]
Regarding #9895, is there any way I can provide any useful information to you? I'd like to help with at least that

**Comment by hrydgard** [comment]
Did the problem disappear or why did you close?

**Comment by PepeJulio** [comment]
Yeah, it seems that it was fixed at some point in the past. Not sure of what caused it or when it fixed, though.

**Comment by hrydgard** [comment]
Ok, I guess we'll just leave it at that.
