### ISSUE TITLE
I use a usb controller when i move the analog it is the same as moving the d pad i tried fixing this in the settings butt it is the same thing

### ISSUE THREAD

**Issue by Heisenberg45** [hrydgard/ppsspp#9946]
I use a usb controller when i move the analog it is the same as moving the d pad i tried fixing this in the settings butt it is the same thing

**Comment by Heisenberg45** [comment]
please help

**Comment by hrydgard** [comment]
OK, you're gonna need to give us more information than that. Is this on PC (OS?) or Android? What controller are you using?

**Comment by Heisenberg45** [comment]
Nevermind i fixed it

Dana 31. kol 2017. 01:24 AM osoba "Henrik Rydgård" <notifications@github.com>
napisala je:

**Comment by ProudNoob** [comment]
Close this issue if you fixed it
