### ISSUE TITLE
NASCAR 07 graphics issue

### ISSUE THREAD

**Issue by Maarcis12** [hrydgard/ppsspp#9948]
Hello, it's me again,
i was trying to play NASCAR 07 on my emulator, but unfortunately i'm encountering this bug, is there any fix for that? and i've tried both european and na version of that game.
![nascar07](https://user-images.githubusercontent.com/26842473/29899805-4d03d8a0-8df6-11e7-8a41-5f431930b6e9.jpg)
![nascar07-1](https://user-images.githubusercontent.com/26842473/29899809-4fcfd246-8df6-11e7-9c10-0242d116726d.jpg)

**Comment by hrydgard** [comment]
Looks odd. Not sure, but it might be related to #9527 .  That's not really gonna help you though, just a note for us developers.

**Comment by Maarcis12** [comment]
Ok, no problems, i can be patient and wait for that issue to get fixed. And thanks for answering my issue.

**Comment by unknownbrackets** [comment]
Could you try exporting a GE debugger dump on PC?  Or check it using the software renderer?  I want to confirm if it's related to #9527.

To do this, open the game and select Debug -> GE debugger..., then when it's displaying the scene, press Record in the top right.  After a second or so, it'll finish and save a trace of the drawing activity.

After that, check the memstick/PSP/SYSTEM/DUMP folder and it'll have created a file named something like "ULES12345_0000.ppdmp".  You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by Maarcis12** [comment]
Uhmm, sure, but since it's fixed now, i might just download old version to show it, would that sound good?

**Comment by unknownbrackets** [comment]
Oh, even better if it's already fixed.  Maybe it was that bezier advance verts thing.  Thanks for reporting.

-[Unknown]
