### ISSUE TITLE
Multiple Graphical Issues On Android (PowerVR only)

### ISSUE THREAD

**Issue by NightK15** [hrydgard/ppsspp#9951]
Hello,

Recently i downloaded the latest PPSSPP Android version and i tried some games like Soul Eater: Battle Resonance, Sunday vs. Magazine,etc. and they work fine and with good Framerate, but when i tried Soul Calibur:Broken Destiny it runs pretty well but there are graphical issues with the character's texture, but when i turn off the Hardware Transform the issues are gone but the Framerate is too low, i tried almost every option to fix this but with no success, in the 1.3.0 i activated the ''Disable alpha test'' and it solves the issue except for the hair of all the characters (When HW Transform is activated, when is deactivated is just like the 1.4.2).

Screenshots:

1.4.2 With HW Transform Enabled:

![screenshot_2017-08-31-16-31-38](https://user-images.githubusercontent.com/31520555/29944830-ef91be0e-8e6c-11e7-8662-8093f9e0ac53.png)

![screenshot_2017-08-31-16-31-53](https://user-images.githubusercontent.com/31520555/29944881-153103b8-8e6d-11e7-94d5-ddfd03c8d792.png)

![screenshot_2017-08-31-16-32-01](https://user-images.githubusercontent.com/31520555/29944890-18f00c9c-8e6d-11e7-9d3a-cdedfdf0fc25.png)

![screenshot_2017-08-31-16-32-09](https://user-images.githubusercontent.com/31520555/29944895-1afb6144-8e6d-11e7-8551-1fb61a197d7d.png)

1.4.2 Without HW Transform (Laggy):

![screenshot_2017-08-31-16-32-48](https://user-images.githubusercontent.com/31520555/29944963-5806029c-8e6d-11e7-8338-174d8e5ef43b.png)

1.3.0.1 With HW Transform and ''Skip buffer efffects'' enabled:

![screenshot_2017-08-31-16-41-26](https://user-images.githubusercontent.com/31520555/29945008-8e3d345c-8e6d-11e7-89fe-e14d17c807e6.png)

(The white parts in Ivy's Hair are bad, it's not a light effect, her hair disappears and appears again just like in PPSSPP 1.4.2, the same happens to all the other characters, mostly the hair)

Something similar happens with WipEout:Pure and WipEout:Pulse (With pulse happens rarely, but the FPS still too low) but with the ship's texture, i disabled the HW Transform and it solves the graphical issue but again the Framerate is too low, on WipEout:Pure i got a extra issue, when i enter to the game menu runs flawlessly but when is in-game there's a gray color on almost every part of the screen, it solves when i change from buffer rendering to ''Skip buffer efffects'', but the Framerate decreases a lot.

Screenshots (PPSSPP 1.4.2 - 1.3.0.1 - WipEout:Pure):

WipEout:Pure (Buffered Rendering):

![screenshot_2017-08-31-16-33-47](https://user-images.githubusercontent.com/31520555/29945247-6b59bfea-8e6e-11e7-86f5-8784e90829e5.png)

![screenshot_2017-08-31-16-33-56](https://user-images.githubusercontent.com/31520555/29945252-6fe42df2-8e6e-11e7-91a8-73ad0c0c3092.png)

WipEout:Pure (HW Transform Enabled, Buffered Rendering Disabled):

![screenshot_2017-08-31-16-34-10](https://user-images.githubusercontent.com/31520555/29945318-b5236950-8e6e-11e7-9187-dea0abc9a7fd.png)

![screenshot_2017-08-31-16-34-14](https://user-images.githubusercontent.com/31520555/29945321-b7cb6c5c-8e6e-11e7-9837-40735d518d21.png)

WipEout:Pure (HW Transform Disabled, Buffered Rendering Disabled):

![screenshot_2017-08-31-16-34-24](https://user-images.githubusercontent.com/31520555/29945366-df4a32b8-8e6e-11e7-859b-fb5f82c31fc7.png)

My GPU is a PowerVR SGX540, on PC i don't have any issues.

Thanks!

**Comment by Michal1324** [comment]
What device are you trying this on?

**Comment by hrydgard** [comment]
Really odd stuff.. gonna have to dig out some PowerVR device I guess. Thanks for reporting.

**Comment by zminhquanz** [comment]
@hrydgard Did it mention in #7740 ?

**Comment by NightK15** [comment]
@Michal1324 I'm trying on a Motorola Razr XT910

**Comment by Michal1324** [comment]
About the FPS your gpu might have trouble rendering alot of frames so like disabling those effect should give you more fps instead

**Comment by NightK15** [comment]
@Michal1324 Wich effects?, by the way, as i said in the post i tried almost every option (if not all of them) and the results were: 

*Bad graphics, good FPS
*Good graphics, low FPS

And as i said in the post, i haven't tried only graphical settings, i tried the other sections too, inclusive i tried with other versions but it's the same, and if i disable frameskipping in some games doesn't affect negatively, but in others it lags or the audio is horrible, or both of them. And by the way i really don't use effects if no necessary, and i make no use of them in games that gives me lag, in others where the FPS are good i enable one or two but only if these effects don't give me lag. Anyway thanks for the reply :)

**Comment by zminhquanz** [comment]
@hrydgard and it mention in #1313

**Comment by hrydgard** [comment]
Still happens?

**Comment by unknownbrackets** [comment]
How does this look on v.1.7.x?

-[Unknown]

**Comment by zminhquanz** [comment]
@unknownbrackets I try to test again on PowerVR SGX 544 device ( my old Zenfone ) . Issue still happen , not fixed

**Comment by Gamemulatorer** [comment]
@zminhquanz what about now using recently build?

**Comment by hrydgard** [comment]
I don't see this at all on my PowerVR device, it's still very slow though.

**Comment by hrydgard** [comment]
I'm gonna assume this stuff has been fixed by now, if it hasn't in the latest builds, please re-open.
