### ISSUE TITLE
Fate/Extra screen transition

### ISSUE THREAD

**Issue by Arrkhon** [hrydgard/ppsspp#9957]
It seems to work fine in 3D11
![ulus10576_00000](https://user-images.githubusercontent.com/12532554/30106928-6730788a-92fd-11e7-9e72-adf89914573d.png)
But in OpenGL instead of showing last frame or whatever that is it instead shows black screen with some white formation in top left
![ulus10576_00004](https://user-images.githubusercontent.com/12532554/30106970-8e9c0c68-92fd-11e7-9483-a16310d0fd8d.png)
In Vulkan the same thing happens but without white thing
Also rendering resolution doesn't seem to affect the bug
Using version 1.4.2-429

Ultimately it's not something that really matters since only place that uses that transition is school but it's still a bug

**Comment by unknownbrackets** [comment]
Does this still happen in Vulkan?

-[Unknown]

**Comment by Arrkhon** [comment]
It works on all of them now
Thank you for your work
