### ISSUE TITLE
Valkyrie Profile Screen Problem on 1.4.2 new builds

### ISSUE THREAD

**Issue by xt89ann** [hrydgard/ppsspp#9959]
I'm using a stable version "1.4.2" that I downloaded from the site ppsspp.org, everything working perfectly without problems. Out of curiosity, I wanted to test a new version downloaded from the website buildbot.orphis.net/ppsspp "v1.4.2-429-g49c92c69c" and I found a very uncomfortable problem with Valkyrie Profile [ULUS10107], you will be able to see the problem in the photos that I will show soon.

[1.4.2 -P1](http://i.imgur.com/GfCPK1E.jpg)
[1.4.2 -P2](http://i.imgur.com/LnAA1i2.jpg)
[1.4.2 -P3](http://i.imgur.com/f8Ks1dL.jpg)

[1.4.2-429-g49c92c69c -P1](http://i.imgur.com/QsLNSLw.jpg)
[1.4.2-429-g49c92c69c -P2](http://i.imgur.com/LJr1EQx.jpg)
[1.4.2-429-g49c92c69c -P3](http://i.imgur.com/eamxbET.jpg)

Yes, I'm using the same settings on both versions.
I already tried to disable/enable almost all the options to see if it was some new implemented 'thing' that was causing the problem, no results.

Any idea ?

**Comment by hrydgard** [comment]
Obviously some new regression, could be related to the state optimizations. Needs to be looked into before the next major release, thank you for reporting!

**Comment by xt89ann** [comment]
Thanks for your attetion, I've tested until v1.4.2-308-g945f57af3, no problems detected with Valkyrie Profile, 
the problem appeared from version v1.4.2-324-g00f57a5d4+
