### ISSUE TITLE
FlatOut Head On (Android)

### ISSUE THREAD

**Issue by Alissonjos** [hrydgard/ppsspp#9962]
The game speed is around of 49% ~ 60% in some parts, is there any fix for that?
My device: Vibe K5 Plus Snapdragon 616, Adreno 405, android 6

**Comment by Michal1324** [comment]
Try lastest build with Vulkan
or 
Try it on PC the same moment it slows down if it doesn't that means your device might be too slow (that means you have to change graphical settings in PPSSPP)

**Comment by Alissonjos** [comment]
My pc and my smartphone doesn't support Vulkan, but I've tried the emulator's CPU clock  set to 92Mhz and I got a bit more speed in some parts like 58% ~ 85%
here 3 screenshots of my setup.
![screenshot_20170912-182919](https://user-images.githubusercontent.com/24876699/30350025-7d3c04d0-97eb-11e7-8529-f9580eb53e04.png)
![screenshot_20170912-182949](https://user-images.githubusercontent.com/24876699/30350026-7d45fe54-97eb-11e7-9dc0-d1a2f7549076.png)
![screenshot_20170912-183339](https://user-images.githubusercontent.com/24876699/30350027-7d535a4a-97eb-11e7-8edb-60040c546f9a.png)
![screenshot_20170912-183351](https://user-images.githubusercontent.com/24876699/30350028-7d5ce574-97eb-11e7-8798-d265a2a9cdca.png)
![screenshot_20170912-183400](https://user-images.githubusercontent.com/24876699/30350032-7e49a698-97eb-11e7-95fb-31dda2123533.png)
![screenshot_20170912-184600](https://user-images.githubusercontent.com/24876699/30350030-7dadb5c6-97eb-11e7-954d-3b96f8a75178.png)
![screenshot_20170912-184609](https://user-images.githubusercontent.com/24876699/30350031-7dc4f5a6-97eb-11e7-9fbf-ee4dffeaf31b.png)
![screenshot_20170912-184628](https://user-images.githubusercontent.com/24876699/30350029-7d649ea4-97eb-11e7-98d9-075c201a64ba.png)

**Comment by GuilhermeGS2** [comment]
There's nothing to be done, you need a faster phone. The only way to a Cortex A53 to handle racing games (or other CPU-intensives) on PPSSPP with good performance is taking advantage of Vulkan.
