### ISSUE TITLE
ULJS00329 can not find Savedata but the savedata do exist

### ISSUE THREAD

**Issue by Jack-Myth** [hrydgard/ppsspp#9965]
ULJS00329 can not find Savedata. it ask me to create a new save data,but after create the game will show a black screen.I restart the game,but it ask to create a new save data again. it seems game can not access the save data.
1.4.2 release does not have this issue but the last build version has.

**Comment by unknownbrackets** [comment]
What is the first git build that started to have the issue, and the last one that worked fine?

If you put the save data from the old version in the new version's folder, does it work?  Or does the same thing happen?

-[Unknown]

**Comment by unknownbrackets** [comment]
Did you figure out the cause?  Want to post the solution in case other people have the same problem?

-[Unknown]

**Comment by Jack-Myth** [comment]
Sorry about this issue. I didn't get Github's notification (or I didn't see the e-mail) and this bug has been fixed on a later version, so I forgot this issue. It has no problem anymore. Thanks for your help.

**Comment by unknownbrackets** [comment]
Thanks - in that case, it was probably fixed by #11215.  Good to know.

-[Unknown]
