### ISSUE TITLE
Regression: Silent Hill: Origins - Distorted sound starting with ppsspp-v1.4.2-278 (Windows 32-bit)

### ISSUE THREAD

**Issue by Rekrullurker** [hrydgard/ppsspp#9967]
This is the Windows 32-bit version running under XP Pro, SP3 and using onboard, Realtek HD audio. I tested the available builds to narrow down when it started.

In v1.4.2-270, the sound in Silent Hill: Origins seems to work fine, although the volume is much lower than it should be. With my speakers set at a comfortable level in other games, I can barely hear the music at the beginning of the game and all other sound effects are fairly quiet as well. 

In v1.4.2-278, the sound is much louder (which is probably the level it should be), but the audio is distorted in spots. The opening cutscenes mostly sound fine, except when your character yells "Hey!" in the second one, which is distorted. As you run down the road, the music is fine, but you can hear pops in the audio. However, once you pass that section and get to the burning house, all the speech is distorted and there is an almost constant crackling to the audio. The distortion and crackling is _not_ present in v1.4.2-270.

I tried changing some of the audio options, but nothing seemed to help.

To quickly get to that point, load the game, start a new game, when the opening cutscene starts, press Start and then Circle to skip it, then Start & Circle to skip the second cutscene, then hold down the Square button and use the analog stick to guide your character down the road. You'll hear an occasional pop in the audio as you run. The distortion and crackling will start at the burning house, right after you pass the Silent Hill sign. The crackling starts in the cutscene and continues as you move through the house.

**Comment by Michal1324** [comment]
Have you tried different sound settings?

**Comment by Rekrullurker** [comment]
I tried turning Audio Sync off and setting the Latency to low, medium and high, in all possible combinations. None of it helped.

Are there other audio options beyond those in the Audio settings menu I should try?

I assume this doesn't happen for you?

**Comment by Michal1324** [comment]
Haven't tested that game yet on that build 

Try changing audio backend 
Try Enabling audio hack

**Comment by Rekrullurker** [comment]
I don't have an option to change the audio backend;

![audio settings](https://user-images.githubusercontent.com/23264794/30436204-92cc2498-9939-11e7-8b9a-3aaad446a69a.png)

Either it's not included in the 32-bit Windows version, or maybe my system can only support one audio backend, so the option isn't displayed.

If by audio hack, you mean the Sound Speed Hack, yup I tried that too.

**Comment by Michal1324** [comment]
Yeah WASAPI was added in Vista so...

Perhaps provide here a save state when this happens so I can check that game if it occur for me as well

By the way download lastest PPSSPP build and try again if it appears again

**Comment by Rekrullurker** [comment]
OK, I just tried the most recent build, v1.4.2-238, and the sound is still distorted. Attached is a save state right at the start of the cutscene where it's most noticeable. Save state made with v.1.4.2-238, 32-bit Windows version.

[Silent_Hill_Origins_USA.zip](https://github.com/hrydgard/ppsspp/files/1304362/Silent_Hill_Origins_USA.zip)

**Comment by Michal1324** [comment]
Thanks I will give it a shot tomorrow

**Comment by Michal1324** [comment]
Had the same cracks in audio can confirm it exists

**Comment by Rekrullurker** [comment]
Thank you for the confirmation.

**Comment by Rekrullurker** [comment]
Just tried the latest version, 1.4.2-524, no change.

**Comment by unknownbrackets** [comment]
Seems like this is caused by https://github.com/hrydgard/ppsspp/compare/797c0e50f...fd5bf0e0a, which almost certainly points to #9874.

This indeed was meant to fix the volume issue you were experiencing.

I suspect shifting is failing to clamp properly.

-[Unknown]

**Comment by tywald** [comment]
There is a loud screeching noise when BGM volume is set to 5 in Monster Hunter games.
Started to happen with this build as well(v1.4.2-278-gfd5bf0e0a), does not happen on v1.4.2-270-g797c0e50f

**Comment by hrydgard** [comment]
Yeah, definitely that same commit, there's got to be something wrong with it.

**Comment by hrydgard** [comment]
OK so the problem is that it's supposed to distort a little bit, but _mm_slli_s16 is not a saturating/clamping operation, it'll wrap when it hits the ceiling, and that sounds really bad.

Our non-SSE/NEON method does the same thing unfortunately. So I'm gonna fix that and disable the NEON/SIMD paths when the audio levels are high enough that it clamps.
