### ISSUE TITLE
[Google Play] PPSSPP RED - PREMIUM PSP EMULATOR SIMULATOR

### ISSUE THREAD

**Issue by andreyorst** [hrydgard/ppsspp#9973]
Hello, please check this app i've found on main page of Google Play in recomindation section:
[PPSSPP RED](https://play.google.com/store/apps/details?id=com.pspemulator.ppssppred.games&hl=en)
![image](https://user-images.githubusercontent.com/19470159/30634290-3cb89510-9df7-11e7-9cd7-dceee227b804.png)

It is clearly your ppsspp, but with ads. And it has good rating and downloads
![image](https://user-images.githubusercontent.com/19470159/30634235-171e21d0-9df7-11e7-9e62-3ffd68039418.png)
![image](https://user-images.githubusercontent.com/19470159/30634265-2e690ddc-9df7-11e7-82a5-fd558845e4cd.png)
I think it is illegal to do this, so i want to bring your attention
![image](https://user-images.githubusercontent.com/19470159/30634664-80fb1878-9df8-11e7-963a-0d48ec758273.png)

**Comment by hrydgard** [comment]
No source and copying way too much. Time to bring out the old DMCA request.

Closing this though because it's not an issue with PPSSPP itself specifically.

**Comment by tywald** [comment]
Damn, no shame violating GPL 2.0 there...

**Comment by andreyorst** [comment]
There are plenty of others PSP emulators in the store, based on yours. Some of which are referencing to ppsspp, some are not, but all of those are containing ads. Most of them are lying in the description and explain to users that it is a fork down below at the end of description. Fun fact some comments are saying that some games run better on this forks, rather than on ppsspp which i can't believe.
Do you need a list of them?

**Comment by hrydgard** [comment]
Yeah, I know there's a bunch, most of the violating GPL. Just got pissed that this even stole the logo. It's such a pain to go around and check...

**Comment by andreyorst** [comment]
1. [super pssp](https://play.google.com/store/apps/details?id=com.fifa.emulatorHD.PSPGames) -this one is using your logo, with changed color from cyan to blue. In prescription it says: Please note that Emulator is created for educational purposes and based solely on legitimate and free sources owned all the games before playing. Contains ads.

2. [New Tips of Ppsspp 2018 Gude](https://play.google.com/store/apps/details?id=com.pspvnbidy.newtipsppssppguide&rdid=com.pspvnbidy.newtipsppssppguide) - This one is using your logo too, gold, but without outline. Inside the app only instructions how to setup and use ppsspp (every tap invokes ads). Not shure if using logo is enough, but anyway.

3. [PSP Emulator](https://play.google.com/store/apps/details?id=woaemama.arcade.pspemu) - this one is jus a ppsspp copy with ads. And fake screenshot in the store. Inside app you will see one button that lounches ppsspp and says "base ppsspp"

4. [Emulator for PSP Cool 2017](https://play.google.com/store/apps/details?id=coolpsp.psp.emulator.pspgame&rdid=coolpsp.psp.emulator.pspgame) - this one is a plain copy of ppsspp, with ads. Description says that it is based on ppsspp. Don't work on my Android O

5. [AwePSP](https://play.google.com/store/apps/details?id=com.awesome.emulator.awepsp) - nothing about ppsspp in description. Don't work on my Android O

6. [Fast Emulator for PSP](https://play.google.com/store/apps/details?id=app.appslikemake.fastpsp) - says that based on opensource GPL 2.0. Inside welcome message says thank for your ppsspp.

7. [PSSPLAY HD Emulator For PSP](https://play.google.com/store/apps/details?id=com.RROEmulator.android&rdid=com.RROEmulator.android) - description says: "Important notice: this PSP emulator is created for educational purposes and based on PSSPLAY emulator for PSP which is open source (GPL 2.0)". I don't know what _pssplay_ is, but inside is just your ppsspp with welcome "base ppsspp"

8. [Golden PSP Emulator 2017](https://play.google.com/store/apps/details?id=goldenpspemulator.psp_emulator_new) - again this one says nothing about ppsspp in the description. App is similar to 7.

9. [Emulator PSP Pro 2017](https://play.google.com/store/apps/details?id=com.pspemulator.forGame.pspfifa) - this one says nothing about ppsspp in the description, and inside app says "emultech ltd free software under GPL 2.0+". It is a ppsspp with red background

10. [Vita PSP Emulator New](https://play.google.com/store/apps/details?id=emulatorpsp.psp_new_psp&rdid=emulatorpsp.psp_new_psp) - this one says you can emulate psp, psx and psone lol. Inside app is similar to 7. Nothing about ppsspp in the description.

And i can go on.

**Comment by unknownbrackets** [comment]
Well, it looks like it's back just with a new id:
https://play.google.com/store/apps/details?id=com.freepspemulator.ppssppgames.ppssppred

Probably unending.  I think there are a bunch of PSP emulators on the app store, all of which are clones of PPSSPP with ads, some of which also include piracy helpers.

-[Unknown]

**Comment by andreyorst** [comment]
no shame at all.
Google Play policy is really bad. And without app filtration we got this type of situation. 
I think this issue can be closed because there is not so much that can be done about this. Unless @hrydgard will close part of source code, so nobody can build android apk, but I think that it is not easy to do, because actually it will stop contributions from people across the world.

**Comment by hrydgard** [comment]
Sigh. Alright, giving up for now.

**Comment by Gamemulatorer** [comment]
> 1. [super pssp](https://play.google.com/store/apps/details?id=com.fifa.emulatorHD.PSPGames) -this one is using your logo, with changed color from cyan to blue. In prescription it says: Please note that Emulator is created for educational purposes and based solely on legitimate and free sources owned all the games before playing. Contains ads.
> 2. [New Tips of Ppsspp 2018 Gude](https://play.google.com/store/apps/details?id=com.pspvnbidy.newtipsppssppguide&rdid=com.pspvnbidy.newtipsppssppguide) - This one is using your logo too, gold, but without outline. Inside the app only instructions how to setup and use ppsspp (every tap invokes ads). Not shure if using logo is enough, but anyway.
> 3. [PSP Emulator](https://play.google.com/store/apps/details?id=woaemama.arcade.pspemu) - this one is jus a ppsspp copy with ads. And fake screenshot in the store. Inside app you will see one button that lounches ppsspp and says "base ppsspp"
> 4. [Emulator for PSP Cool 2017](https://play.google.com/store/apps/details?id=coolpsp.psp.emulator.pspgame&rdid=coolpsp.psp.emulator.pspgame) - this one is a plain copy of ppsspp, with ads. Description says that it is based on ppsspp. Don't work on my Android O
> 5. [AwePSP](https://play.google.com/store/apps/details?id=com.awesome.emulator.awepsp) - nothing about ppsspp in description. Don't work on my Android O
> 6. [Fast Emulator for PSP](https://play.google.com/store/apps/details?id=app.appslikemake.fastpsp) - says that based on opensource GPL 2.0. Inside welcome message says thank for your ppsspp.
> 7. [PSSPLAY HD Emulator For PSP](https://play.google.com/store/apps/details?id=com.RROEmulator.android&rdid=com.RROEmulator.android) - description says: "Important notice: this PSP emulator is created for educational purposes and based on PSSPLAY emulator for PSP which is open source (GPL 2.0)". I don't know what _pssplay_ is, but inside is just your ppsspp with welcome "base ppsspp"
> 8. [Golden PSP Emulator 2017](https://play.google.com/store/apps/details?id=goldenpspemulator.psp_emulator_new) - again this one says nothing about ppsspp in the description. App is similar to 7.
> 9. [Emulator PSP Pro 2017](https://play.google.com/store/apps/details?id=com.pspemulator.forGame.pspfifa) - this one says nothing about ppsspp in the description, and inside app says "emultech ltd free software under GPL 2.0+". It is a ppsspp with red background
> 10. [Vita PSP Emulator New](https://play.google.com/store/apps/details?id=emulatorpsp.psp_new_psp&rdid=emulatorpsp.psp_new_psp) - this one says you can emulate psp, psx and psone lol. Inside app is similar to 7. Nothing about ppsspp in the description.
> 
> And i can go on.

Sunshine
https://play.google.com/store/apps/details?id=com.expertarts.sunshine
Turbo Rocket PSP
https://play.google.com/store/apps/details?id=com.emultech.rocketpsp

**Comment by hrydgard** [comment]
Thanks, but it's impossible to get rid of them unfortunately :(

**Comment by ZGStuff** [comment]
yo PPSSPP Red was created for minecraft psp edition i think! but idk about it, it seems like just a copy of ppsspp with a different logo
