### ISSUE TITLE
No Android build being released

### ISSUE THREAD

**Issue by GuilhermeGS2** [hrydgard/ppsspp#9979]
Maybe you devs already know this issue, but the last Android build released is v1.4.2-417-gb2057256b from almost a month ago.

**Comment by hrydgard** [comment]
Right, will soon have time to look into it...

@Orphis  any idea?

**Comment by hrydgard** [comment]
/android/src/org/ppsspp/ppsspp/NativeActivity.java:1203: error: strings in switch are not supported in -source 1.5
            switch (params) {
                   ^
    (use -source 7 or higher to enable strings in switch)

I'll see if I can reconfigure the buildbot..
