### ISSUE TITLE
Crash on OpenGL 1.x

### ISSUE THREAD

**Issue by ghost** [hrydgard/ppsspp#9980]
When I tries to use ppsspp on Ubuntu 14.04, it fails... I tested on newly installed ubuntu. 

This is error message.

--------------------------------------------------------------------

32:35:122 Core/Config.cpp:1390 E[LOADER]: Failed to read /home/kaze/.config/ppsspp/PSP/SYSTEM/controls.ini. Setting controller config to default.
W: gl_lost_manager.cpp:32: GL resource holder not initialized, cannot register resource
Segmentation fault

**Comment by hrydgard** [comment]
Can you run it in gdb and print the stacktrace?

    gdb PPSSPPSDL
    r

(run it until it crashes)

     bt

And print the output.

**Comment by kamikaze123** [comment]
I figured out why ppsspp crashed... I was using OpenGL version: 1.4

When I changed graphic card, ppsspp worked perfectly!!! Sorry for making stupid question.

**Comment by hrydgard** [comment]
Hm. In that case, we should probably still print a warning and exit or something instead of crashing.

Can you switch GPU back and try the mentioned steps once, and paste the output here? Then just go back to your good graphics card :)

**Comment by benderscruffy** [comment]
Is this still an issue ??

**Comment by hrydgard** [comment]
I don't think we'll ever bother, honestly. Closing.
