### ISSUE TITLE
SDL: Segfault when setting spline/bezier curves quality

### ISSUE THREAD

**Issue by Bracket-** [hrydgard/ppsspp#9986]
How to reproduce (from default config):  
Settings --> Graphics --> Rendering Resolution --> Any  
Settings --> Graphics --> Spline/Bezier curves quality --> High  

Backtrace:  
https://privatebin.net/?55abbe445c4eef05#eklP6HCyMCus7CKBaKZeWpZBeiJAcBZzrDrBBD2Negg=

PPSSPP: 479eb48  
Linux/Arch x86_64, GCC 7.2.0, SDL 2.0.6

**Comment by hrydgard** [comment]
Strange. Tried a bunch of scenarios and failed to reproduce this on Mac. Have not tried on Linux yet.

**Comment by unknownbrackets** [comment]
I guess 0x5555570c84a0 doesn't exist anymore?  Seems like that's what was clicked.

Maybe it has to do with event order somehow, and we're recreating views?  Not sure why we'd recreate in this scenario.

-[Unknown]

**Comment by unknownbrackets** [comment]
I think we changed something that could've been related based on a Google Play log of a crash.

Does this still happen?

-[Unknown]

**Comment by Bracket-** [comment]
I'm no longer able to reproduce this on my system even with known bad commits, so it may have been related to my system. If I remember correctly, I did test this with both Clang and GCC and mesa stable and git.

For what it's worth, I believe I was able to reproduce about a month ago on my system with 08041d877 since that was the last time I built PPSSPP.
