### ISSUE TITLE
Regression: ppsspp does not recognize gamepad.

### ISSUE THREAD

**Issue by orbea** [hrydgard/ppsspp#9987]
## Description

With the SDL2 or Qt5 frontends PPSSPP does not recognize my gamepad (Horipad One using the xpad driver). It however does work with the PPSSPP libretro core and RetroArch.

### Bisect Results

I found this regressed in two places.

First bad commit for gamepad buttons.
```
db2cc49e0dd1b04d8b20ca4ccc52648e72f6b738 is the first bad commit
commit db2cc49e0dd1b04d8b20ca4ccc52648e72f6b738
Author: Neil Munday <neilmunday@users.noreply.github.com>
Date:   Sun Sep 18 23:23:36 2016 +0100

    Modified SDL2 code to make full use of SDL2's Game Controller API.

:040000 040000 927add97bc9c6db07039a7c7d0062553223fdc83 4eaae6da805457195278ae60be251a2ac8a660fe M	SDL
:040000 040000 164419420df51754566f5650953970dacadd21bb c8c7643f65832a16d4b23620e2ef78ff841e2652 M	ext
```
db2cc49e0dd1b04d8b20ca4ccc52648e72f6b738

First bad commit for analog sticks.
```
commit 67425d7d477d1e95dfa3347df607806dc214c873
Author: Neil Munday <neilmunday@users.noreply.github.com>
Date:   Sun Sep 18 00:33:28 2016 +0100

    Initial attempt at adding SDL's game controller database to PPSSPP.

:040000 040000 cc7ac605476a55810de8959b6b3abe0566509d80 927add97bc9c6db07039a7c7d0062553223fdc83 M	SDL
:040000 040000 d5819be803066a9199987095feb8623c1c8e31e1 18f17488d4d0ac57789eb40d0c324e3571607f62 M	assets
```
67425d7d477d1e95dfa3347df607806dc214c873

### Version/Commit
You can find this information under Information/System Information

`ppsspp-2017.09.29_1b6c5c4_master-x86_64-1_git`

### Environment information

- OS: `Slackware64-current`

**Comment by orbea** [comment]
@neilmunday Can you take a look at this regression?

**Comment by orbea** [comment]
I submitted a PR to add my gamepad config here. https://github.com/hrydgard/ppsspp/pull/9988

However if I understand this issue correctly if a gamepad is not included in `assets/gamecontrollerdb.txt` ppsspp will not allow the user to manually configure their gamepad as it used to before the above commits which still seems like a bug.

**Comment by orbea** [comment]
Some duplicate issues.
https://github.com/hrydgard/ppsspp/issues/9825
https://github.com/hrydgard/ppsspp/issues/9910

I suggest closing this issue after the PR is merged and continue tracking this issue in the other related issues.

**Comment by neilmunday** [comment]
Hi all. Sorry to hear about the issues above. Perhaps the ability to create/update control pad mappings could be built into PPSSPP? I've done this in an application I maintain already.

**Comment by orbea** [comment]
That sounds like a possible solution. Adding the config was not hard once I understood what ppsspp expected, but there are a lot of users who may not find it as easy and being able to configure the controller inside ppsspp if a config doesn't already exist would resolve at least several issue reports.

**Comment by hrydgard** [comment]
@neilmunday Pull requests accepted :) Would be nice if we could somehow generate a default config if none is available, even if not all the buttons will be correctly named..

**Comment by neilmunday** [comment]
A default config is difficult as for some control pads because buttons act as hats or an axis.

**Comment by unknownbrackets** [comment]
Hmm, but sometimes wrong hats or etc. might be better than nothing at all.  There was an issue about allowing people to change the UI buttons which might ultimately go together with that.

-[Unknown]

**Comment by neilmunday** [comment]
Please see pull request above.
