### ISSUE TITLE
No texture.ini create/load options in android version.

### ISSUE THREAD

**Issue by droidnafiz** [hrydgard/ppsspp#9989]
hello, using the latest dev version. there is a option in pc version where it says create/save texture.ini. but there are no such option in android. also it seems it doesn't reading the texture.ini in android too.. so hash textures are tough to deal with. have to manually change every hash textures.

**Comment by unknownbrackets** [comment]
You can create your own.

```
[options]
version = 1
hash = quick

[hashes]

[hashranges]
```

It's disabled on mobile devices because it's more trouble to edit the file there.  It's expected you'd probably edit on a laptop or desktop and just copy to the mobile device.  Maybe this isn't a true assumption for everyone.

-[Unknown]
