### ISSUE TITLE
Savestates not being loaded

### ISSUE THREAD

**Issue by leveophan1987** [hrydgard/ppsspp#9998]
After latest update none of previous savestate files are possible to load.
"Load savestate failed". Reproduced on "v1.4.2-468-g356b25e3c" build.

**Comment by hrydgard** [comment]
Latest update? From which version to which version?

**Comment by leveophan1987** [comment]
Just checked on "v1.4.2-452-ga38e90347". Savestates still not working. Latest build with working savestates for me is "v1.4.2-417-gb2057256b". Checking on android device galaxy s7 edge.

**Comment by hrydgard** [comment]
Okay, then it's https://github.com/hrydgard/ppsspp/commit/42cb559a8d0eed9aeb0b7d3eb8519e4c90b2dc45 , thanks.

Hm, it seemed to do things right...
