### ISSUE TITLE
Yu-Gi-Oh! GX Tag Force Saga Hud and UI Glitch -Android

### ISSUE THREAD

**Issue by Hjalbried** [hrydgard/ppsspp#9999]
hello this is my first issue post because im a new member here but, not for that, im new using and testing ppsspp, so with my experience i just ask for help when i certainly know i can't solve the error so here there is:
Version: PPSSPP v1.4.2
System: AndroidTV 4.4.2  with 5 GB ram 
2 cores of 1,4 GHz or high

This is the thing, first i initiate the game normally and the menu looks normal 
![img_20171004_013053](https://user-images.githubusercontent.com/32505848/31162626-391fa1de-a8a4-11e7-8b47-57b5c8974ea1.jpg)
I played some free duels to see how works the game but in the 2nd one i found this when i use a specific field card Umiiruka, i tested 3 field cards:
![img_20171004_004816](https://user-images.githubusercontent.com/32505848/31162692-877d1852-a8a4-11e7-8f83-0bcee0b31988.jpg)
and story mode has same errors in certain places vanishing the HUD with the conversation text box:
![img_20171004_004904](https://user-images.githubusercontent.com/32505848/31162899-53373464-a8a5-11e7-85c0-3a2e2dabfea7.jpg)
I think they will be necessary for the solution so here I leave my graphyc configurations of the emulator, it is also worth mentioning that I use the system default ones among many others both suggested and personal:
Backend=openGL
Mode=buffered rendering 
simulate block transfer effect=on
frame skip=off
auto frameskip=off
prevent from fps exceeding 60= 0
post processing shader=off
inmersive mode=on
rendering resolution= 1xPSP
display resolution=2x PSP
hardware transform=on
software skinning=on
vertex cache=on
Lazy,retain textures=off
spline/beziet curves quality=(i already mentioned it but..) tested with low/medium/hight
upscale level=of
upscale type=xBRZ
Desposterize=of/on
anisotropic filtering=off
texture filter=linear
screen scaling filter=nearest
and the rest of graphic options are off  

Before i created this, first I saw the other sections of the page to see if there were similar errors, just one was similar but the problem is not exactlythe same as the solutions, well at least i think that becuase i played enough (without some cards) and i never had a blackscreen crash (except for the emulator gba UO gpsp kai but that's for later...) (#3613)
Any options  or suggests are appreciated.
PS: i cant use my own computer to try the emulator , its really a bad girl with almost ones. And about this glitch, is nothing close to the black cards error. -Thanks for taking a (big) moment to read this-

**Comment by unknownbrackets** [comment]
Has this improved at all in the latest version?

I'd suggest "auto" for texture filter, "off" for vertex cache, which should be better settings.  It's also worth trying Vulkan for the backend, in case it changes anything.

-[Unknown]

**Comment by hrydgard** [comment]
No feedback for a long time, closing.
